### ISSUE TITLE
sparklines and icons

### ISSUE THREAD

**Issue by patagoniahiker** [olifolkerd/tabulator#1]
Hello, how can I add sparklines and icons to the rows

**Comment by olifolkerd** [comment]
You would need to assign a custom formatter to the column,

create a function with the following parameters:
```js
myFormatter = function(value, data, cell, row, options){
		return "<a href='mailto:" + value + "'>" + value + "</a>";
}
```
The function paramters are denied as follows
- **value** - value for cell of cell
- **data** - data for whole row
- **cell** - DOM element for cell
- **row** - DOM element for row
- **options** - custom options passed from column definition

The function must return the desired cell contents

Then assign this to the column using the formatter parameter:
```js
 {title:"sparklines", field:"value", sortable:true, sorter:"number", width:200, formatter:myFormatter},
```

**Comment by olifolkerd** [comment]
There is a new example available in the demo section that shows how to use Sparklines with Tabulator.

Check it out [here.](http://olifolkerd.github.io/tabulator/examples/#sparklines)
