### ISSUE TITLE
Proper way to show/hide all groups.

### ISSUE THREAD

**Issue by MusinAmir** [olifolkerd/tabulator#1002]
Hey @olifolkerd 
I need to show/hide all groups in tabulator table on button click.
Now i'm doing it like this:
```javascript
        var groups = $("#tabulator").tabulator("getGroups");
        groups.forEach(function(group){
            group.show();
        });
```
But it's to slow. 
Is it any other way to do this?
I was thinking about reinitializing new table with groupStartOpen option depending on show/hide state. 
And then scroll to position where i was before.

**Comment by quangkieu** [comment]
I think you could try something like 
`$("#id .tabulator-group .tabulator-arrow").click()`

As the getGroups then show/hide would need to lookup the DOM from component so I think it would slower than tell it directly which one to run on?

**Comment by MusinAmir** [comment]
Hey @olifolkerd 
I tried your approach, it's work if we changing groupBy field. So i did like this
``` javascript
//start groups open
$("#example-table").tabulator("setGroupStartOpen", true);
//change grouping
$("#example-table").tabulator("setGroupBy", "name");
//trigger group on gender column
$("#example-table").tabulator("setGroupBy", "gender");
```
It works fine. But is it anyway to scroll to position where i was before mass toggle?

**Comment by olifolkerd** [comment]
Hey @MusinAmir 

At the moment that isnt possible, but i will add it to the roadmap.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @MusinAmir 

If you are collapsing or expanding all of your groups it is very likely that position no longer exists as the table has completely changed size.

Could you give an example

Cheers

Oli :)

**Comment by MusinAmir** [comment]
Sorry, i mean scroll to group not position.

**Comment by olifolkerd** [comment]
At the moment you can only scroll to a specific row not a group header.

if the group is open you could call the ***getRows*** function on the group component and then the ***scrollTTo*** function on the first row component in the returned array

**Comment by gowrishetty09** [comment]
hey olifolkerd

I like Tabulator very much, its really awesome framework for data tables.
I got solutions for all the challenges I face, but can we show first group open and other groups closed.

**Comment by alecgregory** [comment]
You can scroll to a group by using the JS function `scrollIntoView`.

E.g. `group.getElement().scrollIntoView(true)`

The true parameter aligns the group to the top of the screen. There are other options too: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView

**Comment by pirex360** [comment]
Still i cannot change the behaviour, when I expand the last group on the list...tabulator jumps to first row of table...losing focus on the element that was trigger.

`            groupClick: function(e,group){
                table.scrollToRow(group.getRows()[0].getIndex());
                group.getElement().scrollIntoView(true);


            },`

**Comment by ortwic** [comment]
I don't know, but this is not working at all in later Tabulator versions. Testsed with 5.5 and 6.2.1, see my related issue, if you're interested in more details...
