### ISSUE TITLE
How to set header title and fields dynamically/from database for grid.

### ISSUE THREAD

**Issue by makwana8055** [olifolkerd/tabulator#1003]
I need to display olny those columns which i have entered in database.

**Comment by olifolkerd** [comment]
Hey @makwana8055 

There are a couple of approaches to this, you can either use the ***setColumns*** function to change the column definition array to match the selection from your database.

or you could call the ***hide*** or ***show*** function on each column component to change its visibility as needed.

Have a look at the [Column Management Documentation](http://tabulator.info/docs/3.4#column-management) for more info.

Cheers

Oli :)

**Comment by makwana8055** [comment]
Thanks a lot 
it works...

**Comment by makwana8055** [comment]
How to set movableColumns for only selected columns other columns must be not moveable is it possible to do that?

**Comment by olifolkerd** [comment]
Hey @makwana8055 

Tabulator has [Frozen Columns](http://tabulator.info/docs/3.4#frozen-col) that let you fix columns to the right or left of the table.

Cheers

Oli :)
