### ISSUE TITLE
getRows & selectRow

### ISSUE THREAD

**Issue by OsemaPatron** [olifolkerd/tabulator#1004]
Hello sir 
What ever arguments i put with these two functions it searches only by index 
for example I want to get the row that contains the word "test" in the 3rd column . it seems like it searches only by index when i put "2" for exemple it returns the 3rd row in my table .
Any help please 
Thank you so much

**Comment by quangkieu** [comment]
I think you could do something like 
`$("#example-table").tabulator("getRow", {looup_field:"lookup_value"})`
Replace the sample with the field that you want to lookup and the value.

**Comment by olifolkerd** [comment]
Hey @OsemaPatron 

Im afraid that @quangkieu suggestion wouldn't work.

The ***getRow*** and ***selectRow*** function are only designed to return a single row and, will only accept any of [Row Component Lookup Options](component-lookup), which are an instance of the row component you are looking for, the DOM element of the row, or the value of its index field which is by default the ***id*** column.

All retrieval functions will only accept the standard lookup options.

In your case I would suggest using the ***getRows*** function, then using a ***filter*** function on that. For example:

```js
//find all rows with a value of "test" in the field "col2
var matchingRows = $("#example-table").tabulator("getRows").find(function(row){
    return row.getData().col2 == "test";
});
```

If you want to filter the rows visible to the user, then Tabulator has a range of inbuilt functions to do this for you. Have a look at the [Filter Documentation](http://tabulator.info/docs/3.4#filtering) for more information.

Let me know how you get on.

Cheers

Oli :)

**Comment by OsemaPatron** [comment]
It worked Sir .
Thank you alot
