### ISSUE TITLE
Frozen columns shows info blanks when data is reloaded and scrollbars are not in initial position

### ISSUE THREAD

**Issue by alfredormorales** [olifolkerd/tabulator#1008]
Hi, thanks for this awesome tool, It help me a lot with a personal project.

I have a bug to report, when I first load the tabulator.info with an array with an array of json objects, it works fine and the info display correctly on the tabluator.info.

In the options I have turned on scrollbars on tabulator.info because I have some frozen columns and normal columns, some of these last are not displayed, they exceed display area, so I need to play with scorllbars to see this columns.

When I leave the scrollbars positions for display this columns that are hidden as it is and by an action ejecuted by code reload the data of tabulator.info with setData method with a new array that have same columns and size rows (the only difference is that the some values ​​are changed when the data is loaded again from database) then on displayed grid on front-end the info is reload again but the frozen columns are displayed in blank, there is no info display on all cells of this columns, but when I move the scrollbars of the tabulator.info, the frozen columns shown the info correctly again.

this only happens if scrollbars are not in initial position, if scrollbars are in initial position and data info is reloaded frozen columns info are displayed correctly.

Sorry for my english but it is not my native language, I hope you can understand my poor english, If you need screen shots and/or code let me know.

thank for your awesome tool, I like it very much!

Regards.

**Comment by olifolkerd** [comment]
Hey @alfredormorales 

Im afraid i don't understand what you mean by "turned on scrollbars", there is no option for this, Tabulator will always use scrollbars when needed?

Which version of Tabulator are you using? could you make sure you are running the latest, 3.4.6

Could you post a copy of your table constructor so i can understand how your table is setup?

Cheers

Oli :)

**Comment by alfredormorales** [comment]
Hi Oli, thanks for you response. 

I'm using 3.4.3 Tabulator version, I will replace to the new version for solve any problems and maybe the one that I have, If this happen I let you know.

Anyway, I explain in others way the thing of "turned on scrollbars", I think I did not know how to make this clear, is not an option of Tabulator, the real thing it is that the height option is setup to a fixed size, rows of my data exceed the heigh and width size, then the scrollbars are displayed in the grid of Tabulator as you say scrollbars are always display when needed.

This is my constructor:

$(".tabulator_grid").tabulator({
      height : "80vh",
      tooltips: true,
      columnVertAlign:"bottom", 
      columns:columns,     //"columns" is a json object that is defined dynamicly by database values, but 
                                        //on this I don't have problem because it displayed righ at first load     
      langs: {
           "es-mx" : {
                 "headerFilters":{
                     "default":"" 
                  }
      }
}); 
//call to method setLocale for set locale my native language
$(".mon_cli_grid").tabulator("setLocale", "es-mx");

//call to method setData to set info of Tabulator, the object "gridData" is a json arrray with the structure of
//columns defined on constructor, at first time I charge this with an intial database values                
$(".mon_cli_grid").tabulator("setData", gridData);

.
.
.
//I have another method that in certain period of time run automaticly and reload with new values the //object "gridData" but with the same structure of columns defined on constructor then recall setData //method.
$(".mon_cli_grid").tabulator("setData", gridData);
.
.
.
if the scrollbars are moved in the tabulator and this method of periodic data recharging is called, when the values ​​are loaded again, the fixed columns lose the data and blank cells are shown.

I add images with scenarios.

first load of data
![image](https://user-images.githubusercontent.com/7409557/38402253-830afa3e-3920-11e8-9c4a-4671ce2dfe13.png)


after reload data
![image](https://user-images.githubusercontent.com/7409557/38402276-a5256fa0-3920-11e8-82bd-5982858e04a7.png)

I hope this information can help you to better understand my approach.

Cheers!

**Comment by olifolkerd** [comment]
Hey @alfredormorales

Thanks for the info, i will really need a copy of some of your column definitions as the determine how the columns are frozen. 

Once your table is loaded you can access the column definitions with the ***getColumnDefinitions*** funtion if that helps:
```js
var colDefs = $("#example-table").tabulator("getColumnDefinitions")
```

Cheers

Oli :)

**Comment by alfredormorales** [comment]
Hi Oli

this is my column definitios:

`var columns = [{"title":"Turno","field":"turno","width":80,"frozen":true,"headerFilter":"input"},{"title":"Unidad","field":"device","width":85,"frozen":true,"headerFilter":"input"},{"title":"Operador","field":"operador","width":160,"frozen":true,"headerFilter":"input"},{"title":"Nombre de la Ruta","field":"ruta","width":160,"frozen":true,"headerFilter":"input"},{"title":"Punto de Inicio","field":"punto_inicio","width":160},{"title":"Punto 1","columns":[{"title":"Prog.","field":"pp1","align":"center","width":70},{"title":"Real","field":"pr1","align":"center","width":70}]},{"title":"Punto 2","columns":[{"title":"Prog.","field":"pp2","align":"center","width":70},{"title":"Real","field":"pr2","align":"center","width":70}]},{"title":"Punto 3","columns":[{"title":"Prog.","field":"pp3","align":"center","width":70},{"title":"Real","field":"pr3","align":"center","width":70}]},{"title":"Punto 4","columns":[{"title":"Prog.","field":"pp4","align":"center","width":70},{"title":"Real","field":"pr4","align":"center","width":70}]},{"title":"Punto 5","columns":[{"title":"Prog.","field":"pp5","align":"center","width":70},{"title":"Real","field":"pr5","align":"center","width":70}]},{"title":"Punto 6","columns":[{"title":"Prog.","field":"pp6","align":"center","width":70},{"title":"Real","field":"pr6","align":"center","width":70}]},{"title":"Punto 7","columns":[{"title":"Prog.","field":"pp7","align":"center","width":70},{"title":"Real","field":"pr7","align":"center","width":70}]},{"title":"Punto 8","columns":[{"title":"Prog.","field":"pp8","align":"center","width":70},{"title":"Real","field":"pr8","align":"center","width":70}]},{"title":"Punto 9","columns":[{"title":"Prog.","field":"pp9","align":"center","width":70},{"title":"Real","field":"pr9","align":"center","width":70}]},{"title":"PLANTA","columns":[{"title":"Prog.","field":"llegada_programada","align":"center","width":70},{"title":"Real","field":"llegada_real","align":"center","width":70}]},{"title":"Estatus","field":"min_tarde","width":160}]`

Cheers

**Comment by olifolkerd** [comment]
Hey @alfredormorales 

Thanks for sending that over, i have identified the issue and will hopefully have a fix out for the coming 3.5 release.

I will let you know when i have pushed a fix.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
A fix for this has now been pushed to the 3.5 branch, which should be released in the coming week.

Thanks for the detailed description, it really helped in isolating the problem.

Cheers

Oli :)

**Comment by alfredormorales** [comment]
Hi Oli, thank you for sharing this awesome work!

and thanks for resolve this problem so quick I will upgrade the new branch when it comes the coming week, if there is other problem to report I will pleasure to help in some way to optimise this awesome widget.

Cheers

**Comment by olifolkerd** [comment]
Hey @alfredormorales 

Version 3.5 has now been released!
