### ISSUE TITLE
Calculations in Group

### ISSUE THREAD

**Issue by MusinAmir** [olifolkerd/tabulator#1010]
Hi again @olifolkerd :)
I need to show calculations in the group row. 
I think its will be useful. 
You can add another option to column definitions like groupCalc. 
What do you think about it? Is it possible to add this to your roadmap?

**Comment by olifolkerd** [comment]
Hey @MusinAmir 

There already calculations in groups, when you have groups enabled on your table, the ***topCalc*** and ***bottomCalc*** values will show up in each group instead of at the top and bottom of the table.

Cheers

Oli :)

**Comment by MusinAmir** [comment]
I know about topCalc and bottomCalc. I need to show calculation row in group's row.
![image](https://user-images.githubusercontent.com/14330661/38403473-25985308-397d-11e8-92d9-380650c6c2a1.png)

**Comment by olifolkerd** [comment]
Hey @MusinAmir 

Im afraid that wont be possible because of the way Tabulator renders rows.

Could you explain your reasons why you need that and i might be able to suggest a different option.

Cheers

Oli

**Comment by MusinAmir** [comment]
Hey @olifolkerd 
It's makes table more compact and readable. 
I was thinking about hidding groups headers and adding listener to calc row to open Group.

**Comment by olifolkerd** [comment]
Hey @MusinAmir,

You can apply styles to the calculation row to make them look more integrated into the group header. any calculation row has the *** tabulator-calcs-holder*** class applied to it.

As for allowing the calculations to be visible when a group closes, that would be an easy addition to the system, i will add it for the next release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @MusinAmir 

Looks like i had already added the functionality for visible calculations on group close, and completely forgotten.

You can set calcs to be visible on group close using the ***groupClosedShowCalcs*** option:

```js
$("#example-table").tabulator({
    groupClosedShowCalcs:true, //show column calculations when a group is closed
});
```

Cheers

Oli :)

**Comment by saleyn** [comment]
For some reason this doesn't seem to be working.
I have the `groupClosedShowCalcs: true` option set, but it doesn't seem to display the calc values when a group is collapsed. See here: https://jsfiddle.net/saleyn/a6hyxe24/135/.  Am I doing something wrong?
