### ISSUE TITLE
Questions about selectrow extension 

### ISSUE THREAD

**Issue by pointware** [olifolkerd/tabulator#1012]
I try to make new extension is header checkbox feature like this capture

![image](https://user-images.githubusercontent.com/10867281/38367635-349e6b26-391e-11e8-9b36-17b1051ef40f.png)

so I tried to use selectrows.selectrows of extension, 
if parameter is undefined, selectrows function select all rows using row manager.

so i use that for all select or unselect.

but, if exists any selected row in selectrows, selected row of selectrow is overflowed.
(it seems that only process about exists selectableRollingSelection exists in _selectrow function)

I think it needs duplicate check if exists selected rows.

if this is what you intended, could you tell me why?

**Comment by olifolkerd** [comment]
Hey @pointware 

Im a bit confused by your explanation, could you post a copy of your table constructor and the code you are using to select the rows so i can try it for myself?

Cheers

Oli :)
