### ISSUE TITLE
Complex table input

### ISSUE THREAD

**Issue by sumitb555** [olifolkerd/tabulator#1013]
I am trying to build table cells which have Typeahead functionality while editing the field but the cell should be color coded and has a URL.

As I understand this will require custom Formatter and Editor. Is there any example / documentation for Typeahead implementation using the custom editor?

Thank you,
Sumit.

**Comment by olifolkerd** [comment]
Hey @sumitb555 

I have avoided putting in any default typehead functionality as every developer has their own favourite library and i didn't want to confine people to my choice.

That being said it is really easy to make your own custom editor, the [Editing Data Documentation](http://tabulator.info/docs/3.4#manipulating-data) has an example custom editor based on a date input element. you can use this as a template for your own editor.

the key points to take away are:

- The editor must return the element that is to be displayed in the table cell
- The ***success*** function that is passed into the editor should be called when the value has been chosen, and the chosen value should be passed into the success function
- The ***cancel*** function that is passed into the editor should be called when the user aborts their edit, for example on a blur event if the value hasn't changed
- If you pass a callback into the ***onRendered*** function that is passed into the editor, it will be called once the element has been added to the DOM, so if there is anything that needs to be called when the element is visible, or you want to set focus on something, you should pass it in the callback

There is a fully working example of a custom editor in the [Examples Section](http://tabulator.info/examples/3.4#editable)

Let me know how you get on.

Cheers

Oli :)

**Comment by sumitb555** [comment]
Hi Oli,

Thanks for the advise, I have got the editor and formatter working. but in the process I may have found a Bug, This issue I am facing is related to ColumnGrouping. I am getting the following error as soon as I attempt to group Columns. 
_
> Uncaught TypeError: Cannot read property 'indexOf' of undefined
>     at y.mccFormatter1
_
trace of this error is below.

```
            	var mccFormatter1 = function(cell, formatterParams){
            	       var value = cell.getValue();
            	        if(value.indexOf("MCC") == 0 && mccNumbers.includes(value)){
            	        	console.log("Returning URL");
            	        	return "<a href=javascript:poptastic('mywin1',20,20);>" + value + "</a>";

            	        }else if(value.indexOf("MCC") == 0 && !mccNumbers.includes(value)){
            	        	console.log("Selected MCC not available in dashboard")
            	        	cell.getElement().css("color", "red");
            	            return value;
            	        }else if(value.indexOf("NA") == 0){
            	        	console.log("Returning URL");            	        	
            	        	cell.getElement().css("background-color", "grey");
            	            return value;
            	        } else {
            	        	console.log("Returning URL");            	        	
            	        	return value;            	        	
            	        }
            	    };
```
![image](https://user-images.githubusercontent.com/6050591/38460881-20b127a6-3a91-11e8-87f3-ac6da32f770b.png)

**Comment by olifolkerd** [comment]
Hey @sumitb555 

That error suggest that you are applying your custom formatter to a cell with an undefined value. so when you are calling `value.indexOf("MCC")` you are calling it on a value of undefined which is causing the error.

If you can be certain that is not the case, then please post a copy of your table constructor along with one row of sample data so i can test it.

Cheers

Oli
