### ISSUE TITLE
Bug on resize

### ISSUE THREAD

**Issue by dazkona** [olifolkerd/tabulator#1014]
tabulator.js:15907
I've change the line to:
  table.element.tabulator("redraw");
instead of current line
  this.table.element.tabulator("redraw");

**Comment by olifolkerd** [comment]
Hey @dazkona 

Great minds think alike, i found that one the other day, it has been fixed on the 5.5 branch which will be released in a week or so.

Let me know if you find any others.

Cheers

Oli :)
