### ISSUE TITLE
Column grouping height

### ISSUE THREAD

**Issue by MusinAmir** [olifolkerd/tabulator#1015]
Hey @olifolkerd 
I'm using column grouping and dynamically hiding columns. It's causes issues with height.

Initial:
![image](https://user-images.githubusercontent.com/14330661/38417700-c618186a-39b2-11e8-8381-a8438cb1dba2.png)

After hiding:
![image](https://user-images.githubusercontent.com/14330661/38417715-d1f1d946-39b2-11e8-967e-002bd1e102e4.png)

How i hide columns: generating newColumns object where some columns are hiden and setting it's to table
Setting newColumns:
```javascript
        $("#tabulator").tabulator("setColumns", getTabulatorColumns());
        $("#tabulator").tabulator("setData",tableData);
        $("#tabulator").tabulator("redraw", true);
```
Columns example:
```javascript
       //columns before
        {title: month,
            columns: [
                {
                    title: hours,  columns: [
                        {title: "План", field:"plan_" + month, headerSort:false, minWidth: 200},
                        {title: "Факт", field:"fact_" + month, headerSort:false, minWidth: 200},
                    ],
                }
            ],
        },

       //columns after
        {title: month,
            columns: [
                {
                    title: hours,  columns: [
                        {title: "План", field:"plan_" + month, visible: false, headerSort:false, minWidth: 200},
                        {title: "Факт", field:"fact_" + month, headerSort:false, minWidth: 200},
                    ],
                }
            ],
        },
```

**Comment by olifolkerd** [comment]
Hey @MusinAmir 

I will have a look into that for you. 

Can i ask why you are calling the ***redraw*** function? that should only be called to redraw the table if the dimensions change or it changes from hidden to visible.

Cheers

Oli :)

**Comment by MusinAmir** [comment]
Hi @olifolkerd 
Redraw function unnecessary here. I was trying it to fix my issue but forgot to delete.

**Comment by MusinAmir** [comment]
Hey @olifolkerd 
I noticed that after hiding column in group appears extra border-right. 
![image](https://user-images.githubusercontent.com/14330661/38494244-963d7186-3c0e-11e8-9f92-abe8784bce2d.png)

Hidden column: 
![image](https://user-images.githubusercontent.com/14330661/38494288-bc1bf652-3c0e-11e8-9b82-1ddc7ff5e8e4.png)

Css:
![image](https://user-images.githubusercontent.com/14330661/38494330-e958e436-3c0e-11e8-8e7a-2825a7d1014d.png)
Hidden column not hidding border.

**Comment by olifolkerd** [comment]
Hey @MusinAmir 

I cant replicate your issues in the 3.5 branch so give that a try when it comes out in a couple of days.

On a side not, if you are not changing your data you don't need to reload it into the table when you change the columns, Tabulator will deal with that for you.

Cjeers

Oli
