### ISSUE TITLE
additional info on row click

### ISSUE THREAD

**Issue by freaklaw** [olifolkerd/tabulator#1016]
Hi,

first of all: Great Plugin - love it :) 

I'm wondering what would be the best solution for my needs. 

Lets make a simple example (shortened, so it will be easier to acknowledge)

I have columns in my mysql table:

**Name, surname, age, description**

Table shows name, surname, age - these are column headers. 

OnRowclick i want to display description below the clicked row. On another click, hide the description.
I also wish, i could show multiple descriptions at once (from different rows).

Im not sure, which way would be best to achieve that?

Im using ajax with json to fullfill the table. ajax gets all the results ( select * from mytable) with json_encode and echo. 

I know from other issues here, that you plan to implement similar option in future version. 

I had some ideas, how to do this, but im not so deeply familiar with your plugin to be sure i wouldnt mess anything up... ;/ , so i hope you could point me some solid direction.

**Comment by olifolkerd** [comment]
Hey @freaklaw 

Thanks for getting in touch.

You should use the ***rowFormatter*** to append a div to your row, then use the ***rowClick*** callback to toggle its visibility.

```js
$("#example-table").tabulator({
	columns:[...],
	rowFormatter:function(row){
		var holder = $("<div class='details-holder'>You Info Goes In Here</div>");

		holder.css({
			display:"none",
		})

		row.getElement().append(holder);
	},
	rowClick:function(e, row){
		$(".details-holder", row.getElement()).toggle();
	},ter:
})
```

Let me know if that helps.

Cheers

Oli :)

**Comment by freaklaw** [comment]
Awesome, it works, much appreciated!  A

Altought one more question:

Which function should i use to fill data into "Your info goes in here" place? This data is just another columns from mysql databse, which isnt show yet in my "#example-table". 

This data is in json file that table uses, but how to specify which data is for which row to show, not sure which function/variable should i put here ?

 I could try to instert there some another function using ajax, but i think there is some easier method to do so.

**Comment by olifolkerd** [comment]
Hey @freaklaw 

Both of those callbacks get passed in a row component representing the affected row as an argument, so the ***rowFormatter*** function gets called once for each row in the table

If you use the ***getData*** function on the row component that is passed into those callbacks,  it will return an object which contains all of that rows data, including data that was passed into the table but not displayed as a column:

```js
var rowData = row.getData();
```

I hope that helps.

Cheers

Oli :)

**Comment by freaklaw** [comment]
Ok. I think i got it. Was strugglin with "where do i put the mysql column name?". 

but its like:
var rowData = row.getData().nameofcolumn 

after that i can use rowData as var in my divs. So as far all is ok . 

Thank you very much, bro! o/
