### ISSUE TITLE
Selecting a row programmatically at the beginning

### ISSUE THREAD

**Issue by RodFarias** [olifolkerd/tabulator#1017]
In some cases, I need to show a selected row from the beginning in the table. A simplified example:

```
var tabla, ini;
$(document).ready(function(){
    tabla=$("#tabla");
    ini = 1111;    //actually I get this value from the url
    tabla.tabulator({
        ajaxURL:               "api/facturas", //     [{id, numero, cliente}, ...]
        selectable:            1,
        selectablePersistence: true,
        columns:               [
            {title:            "Número", field:"numero"},
            {title:            "Cliente", field:"cliente"}
        ],
        initialSort:           [{column:"numero", dir:"desc"}],
        rowClick:              function(e, r){action(r.row.data.id);},
        tableBuilt:            alIniciar
    });
});

function alIniciar(){
    tabla.tabulator("scrollToRow", ini);  
        //Scroll Error - No matching row found: 1111
    tabla.tabulator("selectRow", ini);
        //Selection Error - No such row found, ignoring selection: 1111
    action(ini);
}
function action(id){
    //etc...
}

```

I tried to select the row in tableBuilt and dataLoaded callbacks, but it always gives me the same information, without selecting the row. 

> Scroll Error - No matching row found: 1111
>
> Selection Error - No such row found, ignoring selection: 1111

If instead I select it later, for example with a click on a button, it works.

How can I detect that the rows are already available to be selected? 

Thanks.

**Comment by olifolkerd** [comment]
Hey @RodFarias,

You want the ***renderComplete*** callback

Cheers

Oli :)

**Comment by RodFarias** [comment]
Yes, that's the way.

The only thing that has to be said is that renderComplete can trigger many times, so I had to put a flag at the beginning of the load and delete it after selectRow.

Thank you very much, tabulator is amazing.

Rodrigo
