### ISSUE TITLE
Using movableCols and sortable together - column data does not catch up with title

### ISSUE THREAD

**Issue by cokechan** [olifolkerd/tabulator#102]
Hi Oli, 

Thank you for this wonderful table api - it was very easy to embrace and use!

I wished to create a table that allows user to move the column headers. However, when testing with Mozilla Firefox browser (currently, using ver 50.0) and setting "true" for "movableCols" and "sortable", i wish to report that there is an issue when i move a column, there are "unpredictable"  times where  yes the column title is moved but the column values do not catch up - please see my attached screenshot. I was using your codepen tutorial to try out and indeed, the same issue is present.  

However, this issue does not seem to happen for Edge or Chrome. Also, this issue will not happen if i set 'sortable' to 'false' for Mozilla Firefox.

Greatly appreciate your advice on how to work around for Mozilla Firefox.
coke c.

![ffissue](https://cloud.githubusercontent.com/assets/24190417/20640894/b9d44b22-b426-11e6-9546-1a8d19e11aca.png)

**Comment by olifolkerd** [comment]
hey,

thanks for getting in touch, glad to hear you are enjoying tabulator. I will have a look into the bug for you this afternoon and get back to you

**Comment by olifolkerd** [comment]
Turns out there was a bug in the new column layout system that wasn't updating the column render list when things were reordered. Good Spot!

I have just committed a fix for this.

Cheers

Oli

**Comment by cokechan** [comment]
Thanks and great fix, Oli. :)
