### ISSUE TITLE
cell context click event- how to access value in first column of that row

### ISSUE THREAD

**Issue by edtaaffe** [olifolkerd/tabulator#1020]
Hi Oli,
Thanks for previous help.
I cant find an answer to this in the documentation.
I need to handle right click and pick up the value in column 2 of the row that was clicked before processing. 
Is that possible?

Ed

**Comment by olifolkerd** [comment]
Hey @edtaaffe 

you can use the ***rowContext*** callback to handle right clicking:
```js
$("#example-table").tabulator({
    rowContext:function(e, row){
        //e - the click event object
        //row - row component

        e.preventDefault(); // prevent the browsers default context menu form appearing.
    },
});
```

Im not sure what you mean be "before processing"?

Cheers

Oli :)

**Comment by edtaaffe** [comment]
Thanks. 
I did consider this, but I need both the contents of column 2 current row and the value of the cell clicked
e.g the row is a record for one branch of the business.  the cell is for Wine sales. I want to process information about wine sales for that specific branch. I need branch name and winde sales.
If i use rowContext, i get the row but not the cell value.
Below is the latest attempt, but have not tested yet:


$("#example-table").tabulator({
cellContext:function(e, cell){
 var sales=cell.getvalue();
 var row= cell.row;
 var Branch=row.getdata.Branch;
processSales(Branch,Sales)
//var rowindex=row.getindex();
//var colindex=?
//var Runner=row.getCells(rowindex,colindex)

**Comment by olifolkerd** [comment]
Hey @edtaaffe 

You can use the ***cellClick*** callback on the column and then `cell.getRow.getData()` to get the data on the row.

Cheers

Oli

**Comment by edtaaffe** [comment]
Brilliant, Thanks
