### ISSUE TITLE
Frozen columns with Column Grouping

### ISSUE THREAD

**Issue by MusinAmir** [olifolkerd/tabulator#1023]
Hello again @olifolkerd :)
Is it possible to freeze column group? 
I also use groupBy property.
I tried this, but nothing changed.
``` javascript
{title: 'Project Groups',
  columns: [
      {
         title: "Hours", columns: [
           {title: "Type", field:'project_group', topCalc: totalString, headerSort:false, minWidth: 200, frozen: true},
         ],
      }
   ],
 },
```
Maybe i'm doing something wrong?

**Comment by olifolkerd** [comment]
Hey @MusinAmir 

Column groups are not columns in themselves, just convenient wrappers for holding columns together, so you can only apply properties to the columns in the group, You would need to add a ***frozen*** property to each of the columns in the group.

I hope that helps,

Cheers

Oli :)

**Comment by MusinAmir** [comment]
Hey @olifolkerd 
Unfortunately i can't freeze column with column grouping.
``` javascript
        {title: 'Project Groups',
            columns: [
                {
                    title: "Hours", columns: [
                        {title: "Type", field:'project_group', topCalc: totalString, headerSort: false, minWidth: 180, frozen: true},
                    ],
                }
            ],
        },
```

Without grouping it works fine
```javascript
  {title: "Type", field:'project_group', topCalc: totalString, headerSort: false, minWidth: 180, frozen: true}
```

**Comment by akki-jat** [comment]
@olifolkerd I am facing the same problem
