### ISSUE TITLE
Row Edit behaviour: stay in row until save or cancel 

### ISSUE THREAD

**Issue by michaelongithub** [olifolkerd/tabulator#1024]
Hi Oli
I am talking about the inline edit. 
Often systems have the following behavior:
If you start editing a cell in a row: Esc once ends editing the cell, Esc twice stops editing the row.
And one cannot leave the row (keeps having the focus and in edit state) until Cancel or Save.
The specific keys are not important. And the row is kind of "modal" with regard to the other rows (still being inline, not overlay)

MS Access was a very good example for that kind of behaviour

The row components "Row Updated" f.e. does not react to "Cell Edited"  in current tabulator version.

The details vary a little but the basic idea is that:
the grid knows a rows edit state
it knows that row editing has started
it knows if the data of a row have changed
it forces to either cancel or save, i.e makes a row in edit state kind of "modal" with regard to other rows.

So as far as I understand it, it would mean to introduce the management of the edit state of a row and its GUI management.

Is this something you consider worth discussing? 

Cheers, Michael

**Comment by olifolkerd** [comment]
Hey @michaelongithub ,

You could manage this yourself with some custom editors that handle the escape key in the way you want.

I have used Tabulator is some fairly advanced editable tables, with navigation and progression blocked by certain states, even going so far as to allow navigation through text area editors, that then progresses to vertically neighbouring cells, but also takes account of an autocomplete that is attached to the text area. 

And also on invoicing rows that update calculations in unit-cost, net-cost, VAT and qty based on changing values, not allowing the user to progress from the cells until all data is entered.

You can use a mix of custom editors, validators and mutators to achieve almost any form of user experience that you like.

Im not sure what you mean by "Row Updated" f.e. does not react to "Cell Edited"?


I hope that helps.

Cheers

Oli :)

**Comment by michaelongithub** [comment]
Ok, thanks for Your info. I have a more detailed look at how far I can go with the present implementation. 
And see if I need to come back.
Cheers
