### ISSUE TITLE
tabulator.min.js:2 Data Loading Error - Unable to process data due to invalid data type 

### ISSUE THREAD

**Issue by rivman** [olifolkerd/tabulator#1026]
Hello, 
After reading almost all of the similar issues, and didn't understand how to solve my problem, I will try to explain and hope to get some help for making the grid work.
Here is my constructor :

`$("#pool_data_stats").tabulator({

   			 	colVertAlign: "center",
    			ajaxURL:"<?php echo $json_pool_stats; ?>",
    			ajaxConfig:"GET",
    			ajaxResponse:function(url, params, response){
      			  	//url - the URL of the request
        			//params - the parameters passed with the request
        			//response - the JSON object returned in the body of the response.
				return response.stats ;
    			},

    			columns:[ //Define Table Columns
        			{title:"Total envoyes", field:"hashes", align:"left"},
        			{title:"ETN (current)", field:"balance", align:"left"},
        			{title:"N° paiements", field:"payments", align:"left"},
        			{title:"Total paiements", field:"paid", align:"left"},
        			{title:"Total moyenne (10 min.)", field:"hashrate", align:"left"},
        			],
        		locale:true,
        		setLocale : "fr-fr",
        		 langs:{
        	"fr-fr":{	
            "columns":{
                "name":"Nom", //replace the title of column name with the value "Name"
            },
            "ajax":{
                "loading":"Chargement...", //ajax loader text
                "error":"Erreur", //ajax error text
            },
            "groups":{ //copy for the auto generated item count in group header
                "item":"item", //the singluar for item
                "items":"items", //the plural for items
            },
            "pagination":{
                "first":"Prémier", //text for the first page button
                "first_title":"Premiere page", //tooltip text for the first page button
                "last":"Last",
                "last_title":"Dernierre Page",
                "prev":"Prev",
                "prev_title":"Page precedente",
                "next":"Next",
                "next_title":"Page suivate",
            },
            "headerFilters":{
                "default":"filter la colonne...", //default header filter placeholder text
                "columns":{
                    "name":"filter la colonne ...", //replace default header filter text for column name
                }
    			}
    		}
    	},	
    	});`
Here I have the Json data :
`{
  "stats": {
    "hashes": "860712521",
    "lastShare": "1523293134",
    "balance": "890",
    "lastChanged": "1521506152",
    "minPayoutLevel": "1000",
    "payments": "42",
    "paid": "24460",
    "hashrate": "53.20 H",
    "payoutThreshold": 10
  },
  "payments": [
    "15a246b1c2z7f8e415f5dfe9de9a8c0f511153bfe3a90a51a2cae1f53a5d5822:1020:3000:0",
    "1523162318",
    "27a82c264d5b6da0b401b83f51c3aca04955366dbc639d58c5e76a52467c8258:1010:3000:0",
    "1523126195",
    "76e72f05022f6cdf0d5321d9f974e3304bf57fe6b1756a28d6dba0bf3cb051aa:1050:3000:0",
    "1523086518"
  ],
  "charts": {
    "payments": [
      [
        1521860033,
        "1070"
      ],
      [
        1521893946,
        "1390"
      ]
    ]
  }
}`

I was trying the method mentioned at the begining of this post and the method 
$("#pool_data_stats").tabulator("setData", "<?php echo $json_pool_stats; ?>", {key1:"stats"});

Both methods throw the error :
`tabulator.min.js:2 Data Loading Error - Unable to process data due to invalid data type 
Expecting: array 
Received:  object 
Data:      {hashes: "860813823", lastShare: "1523296441", balance: "932", lastChanged: "1521506152", minPayoutLevel: "1000", …}`

How can I make this work knowing that I have already another table in same page (with another # ) that works just fine with the same constructor but the Json is not exactly the same :
`{
  "workers": [
    {
      "rigId": "Mainframe",
      "hashRate": "840.80 H/sec"
    },
    {
      "rigId": "This-PC",
      "hashRate": "1364.40 H/sec"
    }
  ]
}`

Many thanks for opening my eyes.

**Comment by olifolkerd** [comment]
Hey @rivman 

Tabulator is expecting an array of objects, with one object representing one row in the table.

The example below is loading 3 rows into a table:
```js
$("#pool_data_stats").tabulator("setData", "", [
    {key1:"stats"},
    {key1:"more stats"}, 
    {key1:"yet more stats"}
]);
```
Let me know if that helps,

Cheers

Oli :)
