### ISSUE TITLE
Table blinks on refresh

### ISSUE THREAD

**Issue by JimSmithJr** [olifolkerd/tabulator#1027]
I'm sure this is minor - even petty.  However, I have and issue I think my users will find annoying.  
I have a grid configured with a double click which opens a detail form in a separate window.  On close I trigger a refresh of the grid using "setData".

Though it's quick the grid does this blink.  The whole grid briefly disappears then reappears with fresh data.

This is exactly the desired behavior with the exception of the blink and I was hoping there may be a quick solution I can implement.  I did experiment with the ajaxLoaderLoading setting to no avail.

As always - thanks so much for the amazing plugin!
Jim

**Comment by olifolkerd** [comment]
Hey @JimSmithJr 

The blink is actually the ajax loader message being briefly displayed, and then dissapearing as the data is loaded, you clearly have a fast server returning your data.

You can disable this by setting the ***ajaxLoader*** to false;
```js
$("#example-table").tabulator({
    ajaxLoader:false,
});
```

In the 3.5 release, coming out later this week, there will be a new param ***replaceData*** function designed to silently refresh data in the table, keeping it in the current position.

Let me know if that helps.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @JimSmithJr
