### ISSUE TITLE
Clear cell on cell editing

### ISSUE THREAD

**Issue by MusinAmir** [olifolkerd/tabulator#1028]
I need to clear cell on cell editing if it's value is 0.
``` javascript
        cellEditing:function(cell){
            var value = cell.getValue();
            if (value == 0){
                cell.setValue("", false);
            } 
        },
```
 After cell.setValue() cellEdited callback is calling and trying to save empty value on server. 
How can i change cell value without calling cellEdited callback?

**Comment by olifolkerd** [comment]
Hey @MusinAmir 

To update values of an edit you should be using an [Edit Mutator](http://tabulator.info/docs/3.4#get-set) not the ***cellEditing*** callback.

That would prevent the callback loop you have been having.

If you can wait a couple of days, the mutator system has had an overhaul for 3.5 so there will be loads more functionality when it is released later this week.

Cheers

Oli :)

**Comment by MusinAmir** [comment]
Hey @olifolkerd 
I don't know how i missed this, this is very useful!

**Comment by MusinAmir** [comment]
Unfortunately this doesn't fit me, it's working after editing,  but i need before

**Comment by olifolkerd** [comment]
what do you mean you need it before?

**Comment by MusinAmir** [comment]
I have table for planning hours (all editable cells is numbers). 
For more comfortable input i need to clear value if it's zero, if i don't do this user will typing numbers after 0, like this:
![image](https://user-images.githubusercontent.com/14330661/38599927-c415df12-3d7b-11e8-89d4-1180390ec10c.png)

What i'm trying to acheive:
When user starts editing a cell clear its value if it's zero.
``` javascript
if (value == 0)
  return "";
```
After cellEdited if value is empty set zero value.

**Comment by olifolkerd** [comment]
ahh, i think i follow you.

So this really comes down to whether you want to store the values in the table as a 0 or as an empty string.

If you want to store them as a zero then have you thought about a custom editor that will clear out the cell if the value is 0 when the user clicks on it.

If you want to store them as an empty string then you should use a mutator to mutate the data as it is loaded into the table, and when it is edited to convert 0's to an empty string, and then use a formatter on the cells to show empty strings as 0's

I hope that helps,

Cheers

Oli :)

**Comment by MusinAmir** [comment]
Hey @olifolkerd 
You are a genius! :)
I tried to store zero value as empty string and formatting it to zero, it's works perfectly. 
This is exactly what I needed
