### ISSUE TITLE
How to convert json timestamp into date in tabulator

### ISSUE THREAD

**Issue by weusthofm** [olifolkerd/tabulator#1029]
Hello,

We read a database from external source. This works fine. 
However, we would like the timpstamp, which is unix 13 bit, represented as a date and time on the timestampfield. This can be done via date(timestamp). However, I have no full examples found where the use of mutators is shown. I think that the mutator is feasable for this. I have the value of timestamp -> goto mutator->arrange according funtion the result and present.
Our current setting is 
{title:"Timestamp", field:"timestamp", align:"left"},
I think that the setting should be something like
{title:"Timestamp", field:"timestamp", align:"left", mutator:changetimestamp2date},

Function changetimestamp2date(value, data,type,cell)
{
     date(timestamp);
}
return timestamp

Do I have to add in the program something like
Tabulator.extendExtension("mutator", "mutators", {
    changetimestamp2date(value, type, data){
        return value > 5;
    },
});

I have really  no clue at this moment how to set this up.

Please inform me how to implement this in my script. Also if my function is incorrect, let me know.

**Comment by olifolkerd** [comment]
Hey @weusthofm 

Thanks for getting in touch, a mutator would be a great way to go and you almost have it there, you should update your ***changetimestamp2date*** mutator to:
```js
function changetimestamp2date(value, data,type,cell)
{
     return date(timestamp);
}
```

You only need to extend the mutator extension if that is a function you want to use on other tables, and want to reference it with a string instead of a function. For a simple table it isnt needed.

Let me know if that helps.

Cheers

Oli :)

**Comment by weusthofm** [comment]
Oli,


How should I implement an if then else function in the following

$("#ajax-trigger").click(function(){
    $("#example-table").tabulator("setData", "/exampledata/ajax");
});

This should b a replacement on the previous mail.

I think with a comparison condition if array[1] == accelerometer change setcolumn else default.


Please inform me about this last question.


Marcel

________________________________
Van: Oli Folkerd <notifications@github.com>
Verzonden: dinsdag 10 april 2018 20:05:43
Aan: olifolkerd/tabulator
CC: Weusthof, M.H.H. (EWI); Mention
Onderwerp: Re: [olifolkerd/tabulator] How to convert json timestamp into date in tabulator (#1029)


Closed #1029<https://github.com/olifolkerd/tabulator/issues/1029>.

**Comment by olifolkerd** [comment]
Hey @weusthofm 

Im afraid i don't understand what you are asking, if then else what?

You have included a ***setData*** function there but with no explanation about what you are trying to achieve?

Also if what array == accelerometer, there is no context around what is being asked here.

Are you saying you would like to change the column deinitions based on the ajax data url?

Cheers

Oli :)

**Comment by weusthofm** [comment]
Oli,

Indeed based on the Ajax url import the columns should be changed via setcolumn.
The if status is depending on the requested database. This could be in our case accelerometer, gyrometer, barometer,etc. The outcomeome should be presented in the same table. There for we have the if then else option.
Is this possible and is my approach correct.

Marcel
Verzonden vanaf mijn Huawei mobiele telefoon

-------- Oorspronkelijk bericht --------
Onderwerp: Re: [olifolkerd/tabulator] How to convert json timestamp into date in tabulator (#1029)
Van: Oli Folkerd
Aan: olifolkerd/tabulator
Cc: "Weusthof, M.H.H. (EWI)" ,Mention


Hey @weusthofm<https://github.com/weusthofm>

Im afraid i don't understand what you are asking, if then else what?

You have included a setData function there but with no explanation about what you are trying to achieve?

Also if what array == accelerometer, there is no context around what is being asked here.

Are you saying you would like to change the column deinitions based on the ajax data url?

Cheers

Oli :)
