### ISSUE TITLE
How to have nested grouping?

### ISSUE THREAD

**Issue by senglory** [olifolkerd/tabulator#1030]
Can you provide something like this:

http://mleibman.github.io/SlickGrid/examples/example-grouping

but compatible with Bootstrap?

**Comment by olifolkerd** [comment]
Hey @senglory 

You are in luck, Tabulator can already do this.

Have a look at the [Grouping Documentation](http://tabulator.info/docs/3.4#grouping) there is a section on multi level grouping.

Cheers

Oli :)
