### ISSUE TITLE
Column and header alignment when using column-header filters and ajaxFiltering

### ISSUE THREAD

**Issue by qlj** [olifolkerd/tabulator#1031]
Hi Oli,

I'm having the problem where the columns and headers are misaligned after ajax-retrieving the data on a column-header filter.  If the column is right to the table's view port and I apply a filter, the data portion of the table is left aligned but the column-header portion doesn't left align, so the table looks out of whack.

I know this has been covered a few times on this discussion board.  Did you arrive at a workaround/solution for this problem?  If so, can you point me to the discussion item.

Regards,

Quentin

**Comment by olifolkerd** [comment]
Hey @qlj 

There is an issue with this on version 3.4, it has been fixed in version 3.5 which will be released in a couple of days.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @qlj 

Version 3.5 has now been released!
