### ISSUE TITLE
Grouped columns narrower than parent column

### ISSUE THREAD

**Issue by dargiejg** [olifolkerd/tabulator#1034]
I have a table with column grouping where:
a) the parent group is a date (e.g. "2017-12-25")
b) the child groups represent event times in the day (e.g. "am", "pm", "CDay")

The column width are not working well if the combination of the child columns are narrower than the single parent column.
e.g. Something like this might break the widths.
|---2017-12-24---|
|am|pm|

It's most noticeable if there is only one narrow subcolumn:
e.g. 
|---2017-12-25---|
|CDay|

On the screenshot attached there is NO third column in the first group.
The 3rd column (with the green tick) is really under "DATE IS 2017-12-10"/"am".

![screen shot 2018-04-11 at 14 42 36](https://user-images.githubusercontent.com/38287726/38620579-ad8fe61e-3d96-11e8-9233-8a73d0861f0d.png)

John
PS. Still really like what I've been able to do in 24 hours.

**Comment by olifolkerd** [comment]
Hey @dargiejg 

That is a very interesting point, i dont think i have actually come across that particular table setup before. I will have a look into it over the next couple of days and include a fix of it in this weekends 3.5 release.

Thanks for the heads up.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @dargiejg 

I have just pushed a fix for this to the 3.5 branch for release this weekend.

Thanks for the heads up.

Cheers

Oli :)
