### ISSUE TITLE
Question: Custom validator with promises?

### ISSUE THREAD

**Issue by shaunhurley** [olifolkerd/tabulator#1035]
Super greatful for all your work on Tabulator!

I understand that custom validators need to return true or false, and that works fine.

I have a custom validator defined which makes use of a promise to validate that the data being validated exists in a database table, and then a cellEdited function to update the data into the database if it sucessully validate.

Tabulator appears to treat the unresolved promise return as a "true", hence carries on executing the cellEdited function prior to the promise resolving.

Am I missing something obvious?  Is there a means to have Tabulator evaluate a promise in a validator return?

THanks!

**Comment by olifolkerd** [comment]
Hey @shaunhurley 

Thanks for your kind words, it is great to hear that you are enjoying using Tabulator.

In JavaScript, function execution does not wait for promises to return, the code continues executing past them and only the functionality in the ***then*** gets executed on the promise return. so essentially the promise is being ignored if you are using it to affect the return value of a function.

At the  moment there is no way to run an async ajax query in a validator, though i will look at allowing for this in future.

What you could do is outside of the validator build an array of validating data that you could then query from inside the validator without needing to make an ajax request.

Cheers

Oli :)

**Comment by shaunhurley** [comment]
Thanks Oli, suspected that was the case. Thanks for the rapid response!

Sent from my iPhone

On Apr 12, 2018, at 3:14 AM, Oli Folkerd <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @shaunhurley<https://github.com/shaunhurley>

Thanks for your kind words, it is great to hear that you are enjoying using Tabulator.

In JavaScript, function execution does not wait for promises to return, the code continues executing past them and only the functionality in the then gets executed on the promise return. so essentially the promise is being ignored if you are using it to affect the return value of a function.

At the moment there is no way to run an async ajax query in a validator, though i will look at allowing for this in future.

What you could do is outside of the validator build an array of validating data that you could then query from inside the validator without needing to make an ajax request.

Cheers

Oli :)
