### ISSUE TITLE
Window resizing causes "this.table.element.tabulator("redraw");" to fail with "this.table is undefined" message

### ISSUE THREAD

**Issue by sbuethe** [olifolkerd/tabulator#1036]
Hi,
First of all, many, many thanks for this absolutely wonderful and extremly helpful project!

I just tried out the current release (1291 commits) and upon resizing the browser window an error in line 15915 is triggered: "this.table is undefined"

Its the following statement which fails: this.table.element.tabulator("redraw");

Before trying out this release, I was using the version with 1253 commits without any issues.

Cheers,

Sven

**Comment by olifolkerd** [comment]
Hey @sbuethe 

Thanks for getting in touch,

This issue has already been reported several times, and you will be happy to hear there is a fix for it on the 3.5 branch being released this weekend.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @sbuethe 

Version 3.5 has now been released!
