### ISSUE TITLE
Show in tabulator Database names grouped with dynamical tables

### ISSUE THREAD

**Issue by weusthofm** [olifolkerd/tabulator#1037]
Hello,

I would like to read from the server different databases. These databases have in general the same tables. 
How can I present them with tabulator. This means grouped by the database name and then in row represented the tables.
This is a example of the the json file for database and tables.

{"database_01":["accelerometer","barometer","battery","battery_charges","battery_discharges","bluetooth","gsm","gyroscope","magnetometer","wifi"]}

Please inform me, i thought that via grouping  this could work, but somehow I cannot get the database name correct and the tables are not put in a row.

Hopefull someone can inform me.

Marcel

**Comment by olifolkerd** [comment]
Hey @weusthofm 

Thanks for getting in touch,

I am a bit confused by the data you have posted there, is that just an array of column headers?

Could you post a few rows of actual data so i can recommend a solution?

Cheers

Oli :)

**Comment by weusthofm** [comment]
Hello,

I’ll send you a link where you can see my json script after asking for the database and included tables.
https://couch.utwente.nl/list_all_databases_and_tables
I would like to present this in a list with all tables in a row.
Something like
Database: baos
-->accelerometer
                --> application_crashes,
--> etc
Marcel

**Comment by olifolkerd** [comment]
Hi Marcel,

Im afraid i still dont understand what you are asking, there is no data in the link you sent over, only an array of strings.

Is that a list of individual table names, or a list you want displayed all in one column?

if you could draw out what you are hoping thee table will look like that might help me understand what you are asking for

Cheers

Oli
