### ISSUE TITLE
Selectable download column

### ISSUE THREAD

**Issue by CptFantastic-be** [olifolkerd/tabulator#1040]
As you have the possibility to toggle the visibility setting for columns, would it be possible to add a way to toggle the download setting for a columns.
For big tables one, maybe, may only be interested in a subset of columns to download.
Thanks

**Comment by olifolkerd** [comment]
Hey @CptFantastic-be 

You can set whether a column is downloadable using the ***download*** property in its column definition

```js
$("#example-table").tabulator({
    columns:[
        {title:"Hidden Column", field:"secret", download:false} //hide data in download
    ]
});
```
I hope that helps,

Cheers

Oli :)
