### ISSUE TITLE
[Question] How to cascade columns

### ISSUE THREAD

**Issue by lgraziani2712** [olifolkerd/tabulator#1041]
Hello!

I have two columns: `Year` and `Date`. `Date` can only be edited if the `Year` cell is setted. `Date` is limited by `Year`, hence if `Year` changes, the value stored on `Date` must be invalidated.

Is it possible to implement this in Tabulator as it's now?

By the way, I could _partially_ implement it (but I'm not convinced with my actual solution). I don't know how to invalidate another cell's data, though.

Thank you! Luciano

**Comment by olifolkerd** [comment]
Hey @lgraziani2712 

Thanks for getting in touch, if you don't want the column to be editable in the first place you can use the ***editable*** property in the column definition and use a callback to determine if it can be edited:

```js
var editCheck = function(cell){
    //cell - the cell component for the editable cell

    //get row data
    var data = cell.getData();

    return !!data.Year; //only allow the date cell to be edited if the year is set
}

//in your column definition for the column
{title:"Date", field:"Date", editor:"input", editable:editCheck}
```

You could then use the ***cellEdited*** callback on the column to check the value and wipe the year if needed

```js
var checkYear(cell){
   if(!cell.getValue)){
       component.getRow().getCell("Date").setValue("");
   }
    return value;
}
//in your column definition for the column
{title:"Year", field:"Year", editor:"input", cellEdited:checkYear}
```
Let me know if that helps.

Cheers

Oli :)

**Comment by lgraziani2712** [comment]
Yes!!!

Thank you @olifolkerd !!

The **cellEdited** callback was the most important part and what I was ignoring!!

Thank you again :)
