### ISSUE TITLE
What one improvement would you like to see on the tabulator.info website

### ISSUE THREAD

**Issue by olifolkerd** [olifolkerd/tabulator#1044]
Hey All,

As tabulator has grown and its feature set has expanded, It has in some cases become hard to find the documentation you want on the website because there are so many features to explore.

Before I start work on version 4.0 I am going to give the website a bit of TLC, to break the documentation section down into reasonable chunks and make it searchable. 

While I am doing this I was wondering if there were any other features that users would like to see on the website that would make there experience better/easier/more awesome!

Let me know your thoughts.

Cheers

Oli :)

**Comment by quangkieu** [comment]
Hi,
I see that you would like to break the documents into small chunk. I would recommend the flow where the link in the sideline do not redirect the main page.
Like load the document in child iframe or nested them in tabululator grouped rows or jQuery Accordion

**Comment by michaelongithub** [comment]
Hi Oli
example(s) for large number of rows and columns would be useful to demonstrate performance.
Cheers Michael

**Comment by adel314** [comment]
I understand the need for a decoupling and separation of the Table Definition and Table Data mechanisms however there are times when certain table rows have non overlapping or partially overlapping data that may not be relevant for a particular column - for example if a task list for a timesheet may have different task rows with different column start and end dates but all presented on a single table.    
In this case some of the Table Definition features like edit etc should be turned off for certain cell for certain rows.   This would be data driven. Now this could be done programmatically (which is probably what I will need to do) but it would be nice to have a feature that  turns off editing automatically if there is not data for a particular column.

**Comment by adel314** [comment]
The feature I would most like to see would be a clear object structure with all the methods and properties clearly separated.   I am on top of it now and can probably navigate my way around it but during the earlier times I had no idea what properties were supported by which methods and even at a higher level what methods were supported by which objects.   To me this was the most single issue affecting my adoption of the library.   
The main reason behind this is that there is not distinction between "example features" code and code actually required to get the features to work to your needs.   While the "VIew Code" is useful  it is not a developers view of the world.    I hope this helps.

**Comment by michaelongithub** [comment]
document the "destroy" function. Mentionen in ahttps://github.com/olifolkerd/tabulator/issues/1151. Did not find it.

**Comment by roypardi** [comment]
Hi again, late to the party . . One thought: I learn a lot by going through the "closed" issues here but maybe other users don't dig so deeply? So maybe an "FAQ", "Cookbook" or "How do I . . .?" section of the web site?

**Comment by michaelongithub** [comment]
Good idea, thougt oftentimes something like that could be helpful. Suggest: lets wait until 4 is there. Oli also said he would change the format of doku. Then lets coordinate that with Oli ?

**Comment by olifolkerd** [comment]
Hey @roypardi 

I completely agree. once i have got 4.0 released in a few weeks i will be having an overhaul of the website and will be getting an FAQ section up and running. 

Thanks for the feedback

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey All,

The version 4.0 beta is now available for you to have a play with.

It is still under development in some areas but all the core functionality is in and working, if you find any bugs or have any feedback please create an issue so i can track it all.

Checkout the [Version 4.0 Documentation](http://tabulator.info/docs/4.0) for more information.

### Website Updates
The website has also had a bit of a going over, there are now:

[Release Notes](http://tabulator.info/docs/4.0/release) to explain all the new functionality,

A step by step [Upgrade Guide](http://tabulator.info/docs/4.0/upgrade) to take you through how to transition to 4.0

A [Browser Support](http://tabulator.info/docs/4.0/browsers) page to take you through what browsers are supported by Tabulator, 

A [jQuery Wrapper Guide](http://tabulator.info/docs/4.0/jquery) for those of you that want to keep your jQuery code as untouched as possible 

And a new [FAQ Section](http://tabulator.info/faq) to cover some of the most frequent questions i see on the issue list.

Let me know how you get on

Cheers

Oli :)

**Comment by quangkieu** [comment]
Hi, Just a quick comment on the Document >Data Manipulation>  Column Calculations.
I would suggest to change the name to something like "Column Aggregate". The name Column Calculation which I assumed is calculate across multiple columns of a row to a new cell in the row.

**Comment by cmlara** [comment]
I know this has closed out but I don't really want to pollute the system with another ticket for this.

I would love to see the documentation side-nav bar available as an 'INDEX" under the top menu.

I often read on smaller platforms (phone) so I can recline back (similar to reading a book)  but the side navbar is hidden on small screens and as such the only way I have found to get to the documentation is to use google and hope it takes me to the right page , otherwise there is no way on a mobile device to visit all the documentation pages.
