### ISSUE TITLE
How to make  a custom formatter work in html-tables?

### ISSUE THREAD

**Issue by sourrounder** [olifolkerd/tabulator#1045]
Is it possible, to use a custom formatter like "printIcon" within a html-table?

//custom formatter definition
`var printIcon = function(value, data, cell, row, options){ //plain text value
    return "<i class='fa fa-print'></i>"
};`

//column definition in the columns array
`{formatter:printIcon, width:40, align:"center", onClick:function(e, cell, val, row){alert("Printing row data for: " + row.name)}},`

I tried in the table header like:
`<th class="text-center" tabulator-formatter="printIcon" tabulator-width="150">`
`ICON`
`</th>`

as well as in the data rows like:
`<tr>`
	`<td>`
`tabulator-formatter="printIcon"`
	`</td>`
`</tr>`

Nothing worked. 

Common formatters like "tickCross" work as they should.

Thanks!

**Comment by olifolkerd** [comment]
Hey @sourrounder 

If you want the html import to work with a custom formatter, you will need to extend the formatter extension to add it to the list of built in formatters that you can then call by name.

It is a fairly easy process, you can find out more information about how to do it in the [Extension Documentation](http://tabulator.info/docs/3.5#extension-format)

Cheers

Oli :)

**Comment by sourrounder** [comment]
Thanks,
works perfect:

`<th class="text-center" tabulator-formatter="buttonDetails" tabulator-width="80"></th>`
...
`<td></td>`
...
`<script>`
`Tabulator.extendExtension("format", "formatters", {`
   ` buttonDetails:function(cell, formatterParams){`
         `return "<button type='button' class='btn btn-info btn-sm'><i class='fa fa-info'></i>` `Details</button>";` 
` },`
`});`
`</script>`
