### ISSUE TITLE
Unable to addRow using mobile chrome

### ISSUE THREAD

**Issue by dannykhoo** [olifolkerd/tabulator#1046]
(tabulator version 3.5)
I'm noticed that unable to addRow when testing in android chrome latest version 65.0.3325.109  , however do not have problem when using android firefox ...  is this a chrome bug or?   

$("#list-table").tabulator("addRow",
                           {InvtID:"1234",Descr:"testing",Quantiy:"123",Barcode:"12345678"}
                        );
                        $("#list-table").tabulator("redraw", true);

**Comment by olifolkerd** [comment]
Hey @dannykhoo 

What is happening when you try and add the row? also you dont need to redraw the table, Tabulator will do that for you on add row,

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @dannykhoo 

I have just tried testing this on chrome and android, and it seems to work fine.

Im using the demo at http://tabulator.info/examples/3.5#adddel

Try adding the row without calling ***redraw*** and let me know how you get on.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
If you are still having issues after that, could you post a copy of your table constructor so i can run a test that matches your table setup

**Comment by dannykhoo** [comment]
Hi, 

After i tried to clear cache and clear all site setting , its working now , thanks for your help :)
