### ISSUE TITLE
cell.getRow().delete() deleting the row but erroring too

### ISSUE THREAD

**Issue by answerquest** [olifolkerd/tabulator#1047]
Hi, this this happening since v3.5.0, tested with source files downloaded just half an hour ago.

For this column definition:
```
{formatter:"buttonCross", align:"center", title:"del", headerSort:false, cellClick:function(e, cell){
	cell.getRow().delete();
	// other commands 
}}
```
On clicking the red cross the row *is being deleted*, but the function errors out at the same time and other commands after it do not run anymore. In the browser console, an error is reported:

```
Uncaught ReferenceError: index is not defined
    at Row.delete (tabulator.js:4855)
    at RowComponent.delete (tabulator.js:4272)
    at Object.cellClick (misc.js:65)
    at HTMLDivElement.<anonymous> (tabulator.js:5104)
    at HTMLDivElement.dispatch (jquery-3.3.1.min.js:2)
    at HTMLDivElement.y.handle (jquery-3.3.1.min.js:2)
```
I'm seeing the same effect happening from two different pages/scripts using the `cell.getRow().delete()` command this way. All errors lead to ` at Row.delete (tabulator.js:4855)`.  
Looking at the next function's lines my guess is `index` variable has not yet been defined in this function.

**Comment by answerquest** [comment]
Update: yes, adding this line just before L4855 fixes the issue:
`var index = this.table.rowManager.getRowIndex(this);`

**Comment by answerquest** [comment]
Created a pull request. Added the `var index...` line on top. Also made minified .min.js .

**Comment by olifolkerd** [comment]
Hey @answerquest 

Thanks for that, i have added a note to the pull request, as the change will need to made on the source file too.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @answerquest 

I have pushed the update for this to the master branch, and will include it in the patch release later in the week.

Thanks for letting me know.

Cheers

Oli :)
