### ISSUE TITLE
Background color "Sorted" Header

### ISSUE THREAD

**Issue by MvErven** [olifolkerd/tabulator#105]
Hello Oli,

Question: Theming/CSS.

I'm using the midnight theme at this moment. I can't clearly view which column is sorted.
So I wander which css entry I must change to achieve this.

When a column is sorted (both asc and desc), the header of the column  changes the backgroud color to blue. In the attached example, the column "training" is sorted (I highlighted it yellow for this example)

![tabular-sorting-color](https://cloud.githubusercontent.com/assets/17900348/20758844/64e7a24c-b71b-11e6-9cb3-6b322c3c6276.png)

ps: I managed to get data into and from a mysql db. (*proud to myself*)
Michiel.

**Comment by olifolkerd** [comment]
You can use the following selector css selector:
```css
.tabulator .tabulator-header .tabulator-col[aria-sort="ascending"], .tabulator .tabulator-header .tabulator-col[aria-sort="descending"]{
    /*Your styling goes here*/
}
```
