### ISSUE TITLE
bootstrap4  selectable behaviour error or design?

### ISSUE THREAD

**Issue by michaelongithub** [olifolkerd/tabulator#1050]
Hi Oli
Concerns Tabulator 3.5.

I find two peculiarities:
Click on row: select color appears only **after** cursor leaves row. This is different from tabulator css standard behaviour(as one would expect) and for user not really good.

table-striped:
no select color appears for greyed even rows.

See attached example therein i also have a format row, to see if this is the culprit, which is not the case.
Thanks for looking into it.
Cheers, Michael
[Tabulator35_Selectrow.zip](https://github.com/olifolkerd/tabulator/files/1914349/Tabulator35_Selectrow.zip)

**Comment by olifolkerd** [comment]
Hey @michaelongithub 

Thanks for the detailed description there, i have pushed a fix for those to the master branch and will include them in this weekends patch release.

Let me know if you find any more quirks in the new theme.

Cheers

Oli )
