### ISSUE TITLE
Using tabulator with additional custom scrollbars

### ISSUE THREAD

**Issue by mikexmagic** [olifolkerd/tabulator#1051]
Hi there,

any chance to use tabulator together with a jquery custom scrollbar addin?

The simple issue I have is, that the column header dont scroll together with the content anymore. I know that there is an event handler for moving the column header while scrolling the table content... But there is no 'real' scrollbar anymore.

Any hints?

**Comment by olifolkerd** [comment]
Hey @mikexmagic 

I would strongly recommend against replacing any of the internal elements of tabulator using 3rd party widgets.

While Tabulator looks like a simple table on the outside, it is a very complicated set of divs and bindings that rely on each other to work properly.

The table is comprised of a header div and a table holder div to allow the vertical scrollbar to appear below the headers. there are then event bindings on the horizontal scroll of the table holder that cause the header to scroll too.

Tabulator is constantly changing the scroll position when it renders rows and columns using the Vitrual DOM and when data changes.

If you are saying that in a standard configuration with no 3rd party widgets, the header dosnt scroll then that is an issue, please let me know if that is the case.

If you can let me know what you are hoping to achieve with the scroll bar plugin, i might be able to suggest an alternative solution.

Cheers

Oli :)
