### ISSUE TITLE
Issue : rows is not defined

### ISSUE THREAD

**Issue by Halkreen** [olifolkerd/tabulator#1052]
Hello, 

When I try to build Tabulator over an existing table, I have an exception : 

Uncaught ReferenceError: rows is not defined.

It references this function here : 

     var o = this;
            t("tr:first td", e).each(function(e) {
                var i = {
                    title: "",
                    field: "col" + e
                };
                t("td:eq(" + e + ")", rows).data("field", i.field);
                var n = t(this).attr("width");
                n && (i.width = n),
                o.table.options.columns.push(i)
            })
        }

Where rows is, indeed, not defined. 

Any clue ? Thanks

**Comment by Halkreen** [comment]
Ok so I might have fixed that by adding 

rows = $("tbody tr", element);

L.14873 of the unminified version. But I don't know if it's the only problem there ?

**Comment by olifolkerd** [comment]
Hey @Halkreen 

There appears to be a bug when importing tables with no header rows. i will get a patch in for this weekends update release.

In the mean time, if you add headers to your table you should be fine.

would you be able to paste a copy of the structure of your table so i can run some tests and make sure i have fixed the bug?

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @Halkreen 

In answer to your question, you can set attributes on the ***th*** elements that will then get parsed into Tabulator, in this case you will want to use the HTML formatter so you will be looking to add the following to the th tag of that column `tabulator-formatter="html"`

Let me know if that helps,

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @Halkreen 

I have pushed a fix for your first issue to the master branch and will include it in this weekends patch release.

Cheers

Oli :)

**Comment by Halkreen** [comment]
Hi Oli !

Thanks for the update, my problem was solved yes, I dug deeper in the documentation and found what I needed.

Thank you ! :)
