### ISSUE TITLE
Using Tabulator in JQuery-UI Tabs breaks local pagination

### ISSUE THREAD

**Issue by Nyut0n** [olifolkerd/tabulator#1053]
Hey, 

I found that using Tabulator with local pagination inside a jquery-ui tab partially breaks the pagination. Basic navigation works, but the page numbers aren't displayed. 

See this fiddle:
http://jsfiddle.net/wag39wby/1

Same without tabs:
http://jsfiddle.net/wag39wby/4/

I'm not sure if you support this kind of usage, but since jquery-ui is a dependency I thought it would be worth mentioning (:

**Comment by olifolkerd** [comment]
Hey @Nyut0n 

You are correct, that does seem to be interfering with it some how. i will look into it in more detail this week, and get a patch ready for the weekend update.

In the mean time, if you instantiate the tabs plugin after the Tabulator it should work.

Cheers

Oli :)

**Comment by Nyut0n** [comment]
Yep, thanks for that workaround! I didn't even consider changing the order. Works great now 👍 
Keep up the great work.

**Comment by Nyut0n** [comment]
Ahh damn. Just tried to implement that quickfix in the actual project. Unfortunately it pulls the actual data through an AJAX request once a button is pressed. That causes the page numbers to disappear again. :( I'll wait for your fix then.
Just a little heads-up for this case when you are looking into it.
Thank you!

**Comment by olifolkerd** [comment]
Hey @Nyut0n 

I have just pushed a fix for this to the master branch and will include it in today's update.

Cheers

Oli :)
