### ISSUE TITLE
HTML Table Element and fitColumns with Responsive Columns

### ISSUE THREAD

**Issue by markfenner** [olifolkerd/tabulator#1055]
Hi Oli

Tabulator 3.5.0

I've been asked for some help in to improve the front end of a clunky site and it's mass of tables without major server side or JS changes. Tabulators HTML table import makes this feasible and it looks great. It's a cool project!

I am however having an issue with the order in which the columns hide. Tabulator does not appear to respond to the tabulator-responsive setting in the HTML. I've tried both a numeric and numeric string and the table still collapses in the right to left order. Any suggestions. HTML & minimal JS below.

Notes: The first column is variable width but should be last to be hidden. The other columns are either fixed width or hidden in the order that the responsive variable defines (middle two hidden first). There is a fifth column which is invisible and contains a link reference.

Thanks
Mark

<table id="tabulator" tabulator-layout="fitColumns" tabulator-responsiveLayout="hide">
<thead><tr>
<th tabulator-minWidth="200" tabulator-formatter="html" tabulator-responsive="0">Title</th>
<th width="150" tabulator-formatter="star" tabulator-responsive="3" tabulator-align="center">Our Rating</th>
<th width="150" tabulator-formatter="html" tabulator-responsive="2" tabulator-align="center">Your Attempts</th>
<th width="150" tabulator-formatter="html" tabulator-responsive="1" tabulator-align="center">Your Score</th>
<th width="1" tabulator-visible="false">Link</th>
</tr></thead>
<tbody> 
<tr><td>Series A</td><td>1</td><td>3</td><td>16</td><td>A2SGSJ</td></tr>
<tr><td>Series B</td><td>5</td><td>1</td><td>3</td><td>B2SGSJ</td></tr>
<tr><td>Series C</td><td>2</td><td>0</td><td>0</td><td>C2SGSJ</td></tr>
<tr><td>Series D</td><td>5</td><td>12</td><td>35</td><td>D2SGSJ</td></tr>
</tbody>
</table>

HTML NOTATION FOR ABOVE TABLE
table id="tabulator" tabulator-layout="fitColumns" tabulator-responsiveLayout="hide"
th tabulator-minWidth="200" tabulator-formatter="html" tabulator-responsive="0">Title
th width="150" tabulator-formatter="star" tabulator-responsive="3" tabulator-align="center">Rating
th width="150" tabulator-formatter="html" tabulator-responsive="2" tabulator-align="center">Att
th width="150" tabulator-formatter="html" tabulator-responsive="1" tabulator-align="center">Score
th width="1" tabulator-visible="false">Link

JAVASCRIPT
<script>
$(document).ready(function(){
	$("#tabulator").tabulator();
	});
	
$(window).resize(function()
	{$("#tabulator").tabulator("redraw");
	});
</script>

**Comment by olifolkerd** [comment]
Hey @markfenner 

Good spot! it looks like the responsive options are missing from the table importer, i will make sure they are added in this weekends patch release!

In the mean time you can add a column definition to the tabulator constructor to force the functionality.

Cheers

Oli :)

**Comment by markfenner** [comment]
Oli - You are a superhero in the realms of @mdo and @fat, Keep up the (too often) thankless work :)
Mark

**Comment by olifolkerd** [comment]
Hey @markfenner 

Thank you for the extreme complement there :D It is great to hear you are enjoying Tabulator!

I have pushed a fix for this to the master branch and will include it in this weekends update.

Let me know if you spot anything else.

Also, if there are any features you can think of that you would like to see in Tabulator, drop me a note in issue #1043

Cheers

Oli :)

**Comment by byezgi** [comment]
Hello,

We like tabulator a lot, but it has occurred to us that there is no option to make tables horizontally scrollable on mobile. The only option is to either hide columns or collapse them under. Is this something you are thinking of changing in the upcoming version? For CRMs horizontal scrolling is a very commonly used approach on data tables.

**Comment by olifolkerd** [comment]
Hey @byezgi 

Thanks for getting in touch, please make sure if you have a question that you raise it on a new issue not on closed issues as it makes it hard for others to find answers to the same question.

Tabulator offers horizontal scroll behaviour as default, it is only disabled if you enable ***responsive*** mode, if you leave out this option then it will scroll horizontally on all devices.

I hope that helps,

Cheers

Oli :)

**Comment by byezgi** [comment]
Thank you for responding so fast and my apologies :) New to the world of Github threads.

My table is set to FitColumn and the responsive layout is not enabled. which means it will take up 100% of its container.  I was hoping to get something similar to the Responsive Bootstrap Table, where you don't need to define a "min-width" for any columns. The table starts to scroll horizontally only when the table is too small to fit all of its column values in one line. https://getbootstrap.com/docs/4.1/content/tables/#responsive-tables

**Comment by olifolkerd** [comment]
Hey @byezgi 

Im afraid in ***fitColumn*** mode the table will attempt to fit the data to the table regardless of table size, you will need to use the ***minWidth*** property to stop the columns shrinking below a given value.

you can also use the ***widthGrow*** and ***widthShrink*** properties to specify which columsn grow and shrink at which rate.

At the moment there is no layout mode that does as you request, but i will add it to the roadmap for cosideration.

Cheers

Oli :)

**Comment by byezgi** [comment]
Thank you again for your help and considering this for a future release.

In the meantime I will use min-widths on each column to get the same behavior as you suggested.
