### ISSUE TITLE
fit row height to HTML content

### ISSUE THREAD

**Issue by jgenyuk** [olifolkerd/tabulator#1056]
I have a table which has HTML content in every cells wrapped in a div, so I use html formatter. However, when the actual content height is more than one line, part of the content is hidden. I've tried variableHeight=true but this doesn't work. My guess is that the table doesn't know the actual height of the div before rendering, so can't calculate the row height correctly. Is there a good way to adjust the row heights after rendering, or another way to deal with this? Thanks again for your help.

**Comment by olifolkerd** [comment]
Hey @jgenyuk 

Could you post a copy of your table constructor so i can see how your table is setup and how your formatter works.

Cheers

Oli :)

**Comment by jgenyuk** [comment]
Here's a simple example using your data:

   	 var tabledata = [
        {id:1, name:"<div>Oli Bob</div>", progress:12, gender:"male", rating:1, col:"red", dob:"14/04/1984", car:1},
        {id:2, name:"<div>Mary May</div>", progress:1, gender:"female", rating:2, col:"blue", dob:"14/05/1982", car:true},
        {id:3, name:"<div>Christine <br>Lobowski</div>", progress:42, gender:"female", rating:0, col:"green", dob:"22/05/1982", car:"true"},
        {id:4, name:"<div>Brendon Philips</div>", progress:100, gender:"male", rating:1, col:"orange", dob:"01/08/1980"},
        {id:5, name:"<div>Margret <br>Marmajuke</div>", progress:16, gender:"female", rating:5, col:"yellow", dob:"31/01/1999"},
        {id:6, name:"<div>Frank Harbours</div>", progress:38, gender:"male", rating:4, col:"red", dob:"12/05/1966", car:1,},
        {id:7, name:"<div>Jamie <br>Newhart</div>", progress:23, gender:"male", rating:3, col:"green", dob:"14/05/1985", car:true},
        {id:8, name:"<div>Gemma Jane</div>", progress:60, gender:"female", rating:0, col:"red", dob:"22/05/1982", car:"true"},
        {id:9, name:"<div>Emily Sykes</div>", progress:42, gender:"female", rating:1, col:"maroon", dob:"11/11/1970"},
        {id:10, name:"<div>James Newman</div>", progress:73, gender:"male", rating:5, col:"red", dob:"22/03/1998"},
	 ];
   
      $("#example-table").tabulator({
           height:"32rem",
           responsiveLayout:true,
           data: tabledata, 
           columns:[
           {title:"Name", field:"name", width:200, responsive:0, formatter:"html", frozen:true}, //never hide this column
           {title:"Progress", field:"progress", align:"right", sorter:"number", width:150},
           {title:"Gender", field:"gender", width:150, responsive:2}, //hide this column first
           {title:"Rating", field:"rating", align:"center", width:150},
           {title:"Favourite Color", field:"col", width:150},
           {title:"Date Of Birth", field:"dob", align:"center", sorter:"date", width:150},
           {title:"Driver", field:"car", align:"center", width:150},
           ],
       });

**Comment by olifolkerd** [comment]
Hey @jgenyuk 

I don't appear to have any issues when running that code, everything renders correctly.

Which theme are you using?

Cheers

Oli :)

**Comment by jgenyuk** [comment]
Oli,
Here's a complete minimalistic example, no changes in stylesheets:

    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8">
            <link href="/interface/tabulator/dist/css/tabulator_simple.css" rel="stylesheet">
            <script type='text/javascript' src='/interface/jquery/jquery-2.1.1.min.js'></script>
            <script type='text/javascript' src='/interface/jquery/jquery-ui.min.js'></script>
            <script type='text/javascript' src='/interface/tabulator/dist/js/tabulator.min.js'></script>
        </head>
        <body>
            <div id='example-table' style='width:400px;'></div>
            <script type='text/javascript'>
             var tabledata = [
                {id:1, name:"<div>Oli Bob</div>", progress:12},
                {id:2, name:"<div>Mary May</div>", progress:1},
                {id:3, name:"<div>Christine <br>Lobowski</div>", progress:42},
                {id:4, name:"<div>Brendon Philips</div>", progress:100},
                {id:5, name:"<div>Margret <br>Marmajuke</div>", progress:16},
                {id:6, name:"<div>Frank Harbours</div>", progress:38},
                {id:7, name:"<div>Jamie <br>Newhart</div>", progress:23},
                {id:8, name:"<div>Gemma Jane</div>", progress:60},
                {id:9, name:"<div>Emily Sykes</div>", progress:42},
                {id:10, name:"<div>James Newman</div>", progress:73},
             ];

            $("#example-table").tabulator({
                 height:"400px",
                 data: tabledata, 
                 columns:[
                 {title:"Name", field:"name", width:200, responsive:0, formatter:"html", frozen:true}, 
                 {title:"Progress", field:"progress", align:"right", sorter:"number", width:150},           
                 ],
             });
       </script>
        </body>
    </html>

Screenshot without frozen option:

![image](https://user-images.githubusercontent.com/4752842/38893014-3712b5ac-4246-11e8-8b0a-e9607121890e.png)

Screenshot with frozen:

![image](https://user-images.githubusercontent.com/4752842/38892920-e9d39ebe-4245-11e8-8ad4-c0adcd719343.png)

**Comment by olifolkerd** [comment]
Ahhh,

Thanks for the visuals, that was very helpful.

It looks like the row height calculations were not taking abosloutly positioned cells, like frozen columns into consideration. 

I have pushed a fix for this to the master branch and will include it in this weekends patch update.

Thanks for letting me know.

Cheers

Oli :)
