### ISSUE TITLE
editor Select - search function?

### ISSUE THREAD

**Issue by chppppp** [olifolkerd/tabulator#1058]
I am populating a list with 250+ entries into a select. Is there a search capability for the select editor?

**Comment by olifolkerd** [comment]
Hey @chppppp 

Are you looking for an autocomplete sort of lookup?

Cheers

Oli :)

**Comment by chppppp** [comment]
Hey @olifolkerd - Thanks for your reply!!!

Yes! I am looking for some kind of search/auto complete that can filter a select drop down with a zillion items.

Thank you!

**Comment by olifolkerd** [comment]
Hey @chppppp 

There is no built in autocomp editor, but it would be really easy to implement this yourself using a [Custom Editor](http://tabulator.info/docs/3.5#manipulating-data)

Do you have a prefered auto complete element?

Cheers

Oli :)

**Comment by chppppp** [comment]
Thanks Ollie. I am a newb to JS so I dont have any preferred libraries :) Any recommendations? Feel free to close this or I will tomorrow. 

Thank you
