### ISSUE TITLE
3.5 Movable Rows Connected Tables issue

### ISSUE THREAD

**Issue by distraub** [olifolkerd/tabulator#1059]
In the example if you click on a row on the receiver end that you have just moved. You will receive this.connectedRow.getComponent is not a function

It looksl ike this.connectedRow is a bool at that point.

**Comment by distraub** [comment]
I fixed this for now by just returning if this.connectedRow is false or if this.connectedTable is false
in the MoveRows function

**Comment by olifolkerd** [comment]
Hey @distraub 

Thanks for the heads up, that is definitely a bug. I have just pushed a fix for it to the master branch and will include it in the patch release this weekend.

There was an issue with a mouseup binding on the table not being unset after row movement had completed.

Cheers

Oli

**Comment by distraub** [comment]
I found a very similar problem on EndMove, but am not positive how I triggered it.

this.moving.getElement is not a function
    at MoveRows.endMove (tabulator.js:15909)


Which brings me to a question, I am not seeing movableRowsSentFailed or movableRowsReceivedFailed When I begin moving a row, but drop it in the same table. The row appears to delete, but then after scrolling it reappears in the from table.

**Comment by olifolkerd** [comment]
Hey @distraub 

When you drop a row in the same table it came from nothing should happen. the Failed callbacks are only triggered when the receiver rejects the move, if it is droped somewhere invalid, like outside the table or on the source table the do not fire,

Any chance you could stick up a code pen or something with an example that shows what you are experiencing?

Cheers

Oli :)

**Comment by distraub** [comment]
I can get it to happen in the example :) I dragged all of the names onto the same table or left of it.
![screen shot 2018-04-17 at 5 28 15 pm](https://user-images.githubusercontent.com/4632731/38899069-cc305e28-4264-11e8-9cd2-0905359ab47d.png)

As you can see in the image there are no rows left on the left side, but none have been moved to the right.

**Comment by distraub** [comment]
For reference that is in chrome Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by olifolkerd** [comment]
Hmm,

That is wierd... i can see it two on the demo site, but not on my dev machine, this warrants further digging, i will have a look into it in more detail tomorrow.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @distraub 

I have just pushed a fix for this to the mater branch and will include it in todays patch release.

Cheers

Oli :)

**Comment by YendorMc** [comment]
Hi Oli, should this issue now be working on the Tabulator web site?
Example: http://tabulator.info/examples/3.5?#movable-between-tables

Like Distraub, I cannot drag a column over.

Thanks!

**Comment by olifolkerd** [comment]
Hey @YendorMc 

Could you confirm which browser you are using?

Cheers

Oli
