### ISSUE TITLE
Copy element styling to clipboard on copy

### ISSUE THREAD

**Issue by htfranek** [olifolkerd/tabulator#1061]
Could I ask you to allow for the format to be copied along with the data? 

We are generating table reports for clients and I have fully converted my code to work with your great tabulator, but when I copy it to Clipboard, and try to paste it to Outlook or anywhere else, it doesn't have the complete format and only the cell locations are saved into the clipboard.

Thank you for this project.

**Comment by htfranek** [comment]
Well if you will look at my [webpage working copy,](https://herobot.hero-translating.com:8081/SDLdev) you will see that upon selecting the Totals table (scroll down) and copying it with CTRL + C, you will be able to paste it with styling. (trying Outlook). Yet when I copy your Table at the top, it will only insert the data (by cell locations I mean that it remembers the positions, but not the table itself).

Please check how the results look:

TABULATOR:
[](https://ctrlv.cz/shots/2018/04/18/mEIz.png)

ORIGINAL:
[](https://ctrlv.cz/shots/2018/04/18/GIMS.png)

**Comment by olifolkerd** [comment]
Hey @htfranek 

Thanks for the link and the explanation that was very helpful!

The first version of the clipboard functionality is primarily aimed at people copying data to and from other tables and programs like excel and google sheets, it is more of a data transfer thing than anything else.

I see what you are looking for there, that could be rather tricky as bringing the styling information with the table data is handled by the browser, there may be a possibility of achieving this, i will add it to the road map for one of the next couple of releases.

Thanks for the feedback

Cheers

Oli :)

**Comment by htfranek** [comment]
That is great to hear. I will be looking forward for when this feature is implemented. 

Again thanks for the great work you are doing here. 🥇 

Kind regards,
Richard

**Comment by olifolkerd** [comment]
Hey @htfranek 

You will be happy to hear that support for this is now available on the 4.0 branch which is being released later this weekend.

Cheers

Oli :)

**Comment by htfranek** [comment]
Excellent news. Thanks for the update :)
