### ISSUE TITLE
How to color column headers

### ISSUE THREAD

**Issue by swapnil7002** [olifolkerd/tabulator#1063]
Can you help me on coloring column headers in tabulator with out css.

**Comment by olifolkerd** [comment]
Hey @swapnil7002 

Tabulator is primarily built to be styled with CSS, what is preventing you from adding some CSS to style the headers?

Cheers

Oli :)

**Comment by swapnil7002** [comment]
I want to do background color and color to the column header and group header. so how can i do?
![table](https://user-images.githubusercontent.com/38519813/38983582-4a480f76-43e2-11e8-871d-a3d10f59189e.PNG)

**Comment by MusinAmir** [comment]
Adding today class for current month.
```javascript
renderComplete:function(){
            var columns = $("#project-groups-plan").tabulator("getColumns");
            if (currentYear == todayYear){
                var todayColumns = columns.filter(function(obj){
                    var field = obj.column.field;
                    return field == "plan_" + todayMonth || field == "fact_" + todayMonth || field == "exp_" + todayMonth;
                });
           
                todayColumns.forEach(function(column){
                    column.getElement().addClass("today");
                });
                
                var todayColumn = todayColumns[0].getElement();

                var normColumn = todayColumn.parent().siblings(".tabulator-col-content");
                normColumn.addClass("today");
                
                var monthColumn = normColumn.parent().parent().siblings(".tabulator-col-content");
                monthColumn.addClass("today");

            }
        },
```
![image](https://user-images.githubusercontent.com/14330661/38983819-bd90033e-43de-11e8-99d4-fbfa62bbecbb.png)

**Comment by olifolkerd** [comment]
Hey @swapnil7002 

You can also use the ***cssClass*** column definition property to automatically assign a given class to each column:

```js
$("#example-table").tabulator({
    columns:[
        {title:"Name", field:"name", cssClass:"blue-background"},
    ]
});
```

Alternatively you can also use the ***tabulator-field*** which is present on all column header and cell elements, that can help you style a given column. in the case of the name field in the above example it would be:

```css
.tabulator .tabulator-header .tabulator-col[tabulator-filed="name"]{
    //your styles go here
}
```

There is a full list of all tabulator classes in the [Theming Documentation](http://tabulator.info/docs/3.5#css) 

I hope that helps

Cheers

Oli :)
