### ISSUE TITLE
Tooltip callback not fired on updateOrAddData when row already exists in table

### ISSUE THREAD

**Issue by sbuethe** [olifolkerd/tabulator#1065]
Hey @olifolkerd,

If I am not mistaken, tooltip callbacks are not fired when updating existing rows. Could please check.

Many thanks.

Sven

**Comment by olifolkerd** [comment]
Hey @sbuethe 

There are two modes of tooltip generation. By default tabulator will only create the tooltips when the data is loaded into the table, as this is more efficient and suits the majority of usage cases.

If you set the ***tooltipGenerationMode*** option to ***hover*** it will cause the tooltip callbacks to be triggered as the tooltip is displayed to the user.

```js
$("#example-table").tabulator({
    tooltipGenerationMode:"hover", //regenereate tooltip as users mouse enters the cell;
});
```

Let me know if that helps

Cheers

Oli :)

**Comment by sbuethe** [comment]
Hey,
It is working now using the row.reformat(); function. My updateOrAddData call was only updating data fields which were evaluated in a tooltip and a formatter callback while the value of the actual data field bound to the according cell remained unchanged by the updateOrAdd statement. Tabulator therefore did not trigger any reformatting functions - which is understood and makes perfect sense.
Thanks
Sven
