### ISSUE TITLE
Validator warning message

### ISSUE THREAD

**Issue by MusinAmir** [olifolkerd/tabulator#1066]
Hey @olifolkerd 
I need to show validation error message.
How can i do that?

**Comment by olifolkerd** [comment]
Hey @MusinAmir 

There is a ***validationFailed*** callback that will be triggered in the event of a validation failure, you can use this to trigger a modal, popup or other notification:

```js
$("#example-table").tabulator({
    validationFailed:function(cell, value, validators){
        //cell - cell component for the edited cell
        //value - the value that failed validation
        //validatiors - an array of validator objects that failed
    },
});
```

Cheers

Oli :)
