### ISSUE TITLE
switching between scroll and pagination

### ISSUE THREAD

**Issue by cschnelting** [olifolkerd/tabulator#1067]
Hi Oli,
I have updated my tabulator to v3.5.0 and have one question now:
Is it possible to switch between scroll and pagination modes? I would like to let the user decide the mode.

Thanks!

**Comment by Nyut0n** [comment]
@cschnelting  I'm not sure there's a built in way to do this, but in my project I made a dropdown to let users change the page size. Same method could be used to change the page size to the total number of rows. But you'll have to use fixed table height and remember the initial page size somewhere to allow switching back I think.

See a working example here:
http://jsfiddle.net/wag39wby/40/

**Comment by olifolkerd** [comment]
Hey @cschnelting 

@Nyut0n is correct, there is no way to do this directly once the table has been built, you would need to replace the existing table.

To do this you could call the ***destroy*** function on the table, which would turn it back into an empty div:
```js
$("#example-table").tabulator("destroy"):
```

And then create a new table on the element passing in an updated config object.

Cheers

Oli :)
