### ISSUE TITLE
Site is blocked by AV

### ISSUE THREAD

**Issue by gishman** [olifolkerd/tabulator#1068]
Hi,

Great library!

FYI, my buddy sent me a screenshot shaying tabulator.info site is blocked by AV for malicious content.
Not sure if it's a mistake or maybe you have some unknown malware?

**Comment by olifolkerd** [comment]
Hey @gishman 

Thanks for getting in touch,

Ive had no other reports of this and there is definitively no malware on the server, what AV software was your friend using? could you post a copy of the screen shot?

Cheers

Oli :)

**Comment by gishman** [comment]
![fullsize_distr](https://user-images.githubusercontent.com/33009228/39082592-8b7e4612-450a-11e8-8dfc-c85ecd940ed3.jpg)

Also, I'm sure you're a busy guy, but I'm building a generator tool for tabulator using tabulator. It creates 2 tables... one for the Table Config, and one for the Columns.  (kind of meta). The idea is you can use tabulator to create tabulator tables from this lol.  Let me know if you're interested in looking at it.

The table columns would be something like ...
[ { 
field: "id", 
 title: "ID",
width:10,
}, {
field: "FieldName",
  title: "Field Name", headerFilter:"input",headerFilterPlaceholder:"Search...",
 editor:"input",
}, {
field: "Title",
  title: "Field Label",
 editor:"input",
}, {
field: "visible",
  title: "Hide",
defaultValue: 1,
width: 55,
formatter: checkBox,
align: "center",
}, {
field: "HeaderFIlter",
  title: "Header Filter", 
formatter: checkBox,
width: 65,
align: "center",
},  ....]

**Comment by olifolkerd** [comment]
@gishman 

Thanks for the screenshot,

I have reported the issue to the company that ESET use to categorise websites, hopefully they should have it resolved shortly.

Nice idea with the table creating table, it is always great to see the new ways of using Tabulator that people come up with.

I am looking at adding similar functionality to the Tabulator website later in the year, to help people build their tables, it would be interesting to see how you get on with yours.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @gishman 

So the AV blacklist has been removed, if your friend tries again tomorrow he should be able to get through with no warning.

Thanks for the heads up

Oli :)
