### ISSUE TITLE
Drawing vector graphs in a custom cell?

### ISSUE THREAD

**Issue by mgmoulton** [olifolkerd/tabulator#1069]
Hi,

I used a spreadsheet development tool in a Windows desktop C++ app where I could declare a full screen 3x3 grid where the center cell had a very large row height and a very wide column width.  I declared the big cell as a custom cell format and wrote vector based graphics to it.

Can tabulator handle this scenario as long as I provide the vector graphics?

Thanks ...

**Comment by olifolkerd** [comment]
Hey @mgmoulton 

Thanks for getting in touch, could you post an image of the sort of layout you are looking for.

Cheers

Oli :)

**Comment by mgmoulton** [comment]
Hi,
Thanks for the fast response.I do not really have an image,  but I will try to explain it better.1) Declare a spreadsheet with 3 rows and 3 columns.2)  Make column 1 and column 3 50 pixels wide, but make column 2 1000 pixels wide.3) Make row 1 and 3 50 pixels high, but make row 2 800 pixels high.4) This means the center cell (column 2 row 2) is 1000 x 800 pixels.5)  Set this cell as a custom cell type.  (I could do this in the C++ app spreadsheet)6)  Draw custom vector graphics to the center custom cell which basically acts as a container or canvas depending on how you look at it.  (I also could do this.)I used this scheme for creating reports in the C++ app spreadsheet were some of the pages were custom business graphics with headers and footers.Can I repeat these steps in Tabulator?Thanks,Marc
-----Original Message-----

**Comment by olifolkerd** [comment]
Hey @mgmoulton 

How you approach this depends on if the table is a fixed size, or scales with the size of the screen.

If you want it to scale, you should use the ***fitColumns*** layout mode, set the widths on the outer two columns and let Tabulator scale the middle column to fit. you should then use some CSS to set the row heights, and a custom formatter on the middle column to add your vector element:

```css
#example-table{
	height:100%; //set table height
}
	
#example-table .tabulator-row{
	height:50px; //set row height
}

#example-table .tabulator-table > :nth-child(2){
	height:calc(100% - 100px); //set middle row height
}
```
```js
// table data (3 rows)
var data = [{},{},{}];

$("#example-table").tabulator({
    data:data,
    layout:"fitColumns",
    columns:[
        {title:"column1", field:"column1", width:50},
        {title:"column2", field:"column2", formatter:function(cell, formatterParams){
            //cell - the cell component
            //formatterParams - parameters set for the column

           return; //this should return your canvas element or svg
        }},
        {title:"column3", field:"column3", width:50},
    ]
});
```

I hope that helps.

Cheers

Oli :)
