### ISSUE TITLE
Title is not defined error

### ISSUE THREAD

**Issue by edtaaffe** [olifolkerd/tabulator#1070]
Hi Oli,

Thanks for all your help in the past.
I have run into a blocker that is probably simple for you to spot. First table went well and ran first time. 
Another smaller and simpler table, I copied the same code and adjusted it. Can see nothing wrong but it produces a blank page. Digging with chrome debugger I found "title is not defined". Title is  not part of my dataset, but I thought it to be a property of tabulator. What might be causing this?
-----------------------------------------------
//the dataset:
```js
    'HISTORY':[
        {'date':'1/1/2017','venue':'Cheltenham','distance':'16','code':'nh','class':'3', 'going':'gd','position':'1','lengths':'1','beaten':'werty','Jockey':'Jones','days':'200','goodrun':'1'},
        {'date':'21/1/2017','venue':'Ascot','distance':'16','code':'nh','class':'3', 'going':'sft','position':'1','lengths':'4','beaten':'werty','Jockey':'Jones','Days':'20','goodrun':'1'},
        {'date':'1/2/2017','venue':'Newcastle','distance':'20','code':'nh','class':'1', 'going':'sft','position':'7','lengths':'8','beaten':'tytyu','Jockey':'Jones','Days':'30','goodrun':'0'},
        {'date':'15/3/2017','venue':'Cheltenham','distance':'16','code':'nh','class':'1', 'going':'hy','position':'1','lengths':'1','beaten':'sdfff','Jockey':'Jones','Days':'30','goodrun':'1'},
   
        {'date':'1/1/2018','venue':'Cheltenham','distance':'16','code':'nh','class':'3', 'going':'gd','position':'1','lengths':'1','beaten':'werty','Jockey':'Jones','days':'200','goodrun':'1'},
        {'date':'21/1/2018','venue':'Ascot','distance':'16','code':'nh','class':'3', 'going':'sft','position':'1','lengths':'4','beaten':'werty','Jockey':'Jones','Days':'20','goodrun':'1'},
        {'date':'1/2/2018','venue':'Newcastle','distance':'20','code':'nh','class':'1', 'going':'sft','position':'7','lengths':'8','beaten':'tytyu','Jockey':'Jones','Days':'30','goodrun':'0'},
        {'date':'15/3/2018','venue':'Cheltenham','distance':'16','code':'nh','class':'1', 'going':'hy','position':'1','lengths':'1','beaten':'sdfff','Jockey':'Jones','Days':'30','goodrun':'1'},
              ]
    
};
```
The above is retrieved from a bigger file as objH and verified in a watch window just before tabulator is called, cant attach the screen
```js
//the tabulator code
$("#history").tabulator({
         height:"420px",
         movableCols:false,
         movableRows:false,
         tooltips:false,
         columnMinWidth:20, 
         persistenceMode:"cookie",
         columns:[
           {title:"Date", field:"date", sorter:"date", editable:false,width:40,cssClass:"classhead classCell"},
           {title:"Course", field:"venue", sorter:"string", align:"left", editable:false,cssClass:"classhead classCell"},
           {title:"Distance", field:"distance", sorter:"number", align:"left",  editable:false,cssClass:"classhead classCell"},
           {title:"Code", field:"code", sorter:"number", align:"left",  editable:false,cssClass:"classhead classCell"},
           {title:"Class", field:"class", width:40, sorter:"number", editable:false,cssClass:"classhead classCell"},
           {title:"Going", field:"going",  align:"centre", sorter:"string", width:40, editable:false,cssClass:"classhead classCell"},
           {title:"Fieldsize", field:"fieldsize", width:100, sorter:"number", align:"left",editable:true,cssClass:"classhead classCell"},
           {title:"Position", field:"position",  align:"centre", sorter:"number", width:40, editable:false,cssClass:"classhead classCell"},
           {title:"Margin", field:"lengths",  align:"centre", sorter:"number", width:40, editable:false,cssClass:"classhead classCell"},
           {title:"Nearest", field:"beaten",  align:"centre", sorter:"string", width:40, editable:false,cssClass:"classhead classCell"},
           {title:"DLR", field:"Days",  align:"centre", sorter:"number", width:40, editable:false,cssClass:"classhead classCell"},
           {title:"Run", field:"goodrun",  align:"centre", sorter:"number", width:40, editable:false,cssClass:"classhead classCell"}
            
           ] /*,*/
       });
        $("#history").tabulator("setData", objH);
      
        $(window).resize(function(){
  $("#history").tabulator("redraw");
});      
```

**Comment by olifolkerd** [comment]
Hey @edtaaffe 

That probably has to do with the persistence mode, have you tried setting a ***persistenceID*** ?

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @vasiliyaltunin 

I was referring to the ***persistenceID*** if you are using Tabulator <3.5 it can have issues if you change the column definitions without updating the ID.

Bu as you are saying you are still having issue with that remove, that cant be it.

Is the table element visible when it is instantiated?

Could you post a copy of the error from the console.

Cheers

Oli :)

**Comment by edtaaffe** [comment]
Thanks Olli, I wasn't aware of using a persistence id, hadn't got around to working on it yet. I understand that I only need that when there are two or more tables
Nothing is visible.
If I place breaks on the working table, hovering over each line {title: date    shows that the row has been instantiated.
Hovering on the broken table says "title undefined" so it never gets to the setdata part.
I removed all the 
 height:"420px",
         movableCols:false,
         movableRows:false,
         tooltips:false,
         columnMinWidth:20, 
         persistenceMode:"cookie",
Makes no difference.
I removed most of the ros too, still no good.
I played with the order of the include files to make sure dependencies are higher up the page etc
None of this helps,
I started form scratch in a new file using the same example as a template and arrived in the same place. 
All the time the first table works perfectly.

Any more ideas?

**Comment by olifolkerd** [comment]
Hey @edtaaffe 

Out of curiosity are you passing an array or an object to the ***setData*** function. because your dataset that you are posting in seems to be an object containing an array of objects, where it should just be an array of objects

Cheers

Oli :)

**Comment by edtaaffe** [comment]
Hi Oli,
Thanks for that. As far as I am aware the answer is thAT I am passing arrays.
The confusion,(perhaps mine) is probably caused by the sample I pasted in.
There is a large JavaScript object some thing like this
{"1":"John","2":"smith", "numbers":{""a":"1","b","2"}, history{[ {"month":"jan"},{"month":"feb"},{"month":"March"}]}
},
then I do  
var objHistory = myObj.history;
so an array of objects called history is nested in a larger object.
This is the approach I used with the table that works fine.

Also I get the sense that it is failing to create the empty object shell before ever it gets to adding the data.
I do realise that I am way out of practice and I won't be upset if you point out a silly error. I make them all the time.
Ed

**Comment by olifolkerd** [comment]
Hey Ed,

I would be happy to accept that it is Tabulator, but the fact that no one else is experiencing this error seems to suggest it is related to the unique environment of the table.

I have a few more questions for you:

- which version of Tabulator are you using and where are you getting it from
- have you tried the table on a blank html page with nothing else, to isolate it from anything that might be interfereing
- Could you post a screenshot of the console log of the error. without the rest of the details of the console log it is difficult to isolate exactly what the issue is.

Cheers

Oli :)

**Comment by edtaaffe** [comment]
Thanks Oli, I fully expect to find an issue somewhere in my code. I am finding childish errors because I am out of practice and the mindset has not quite returned.
below is a html file I have been using to test..
I hardcoded the array for simplicity, the main json is huge.
here is a grab of chrome debugger checking the array is OK.  
 https://gyazo.com/e38405e7d1fbf7014cb1de5317d4b4ff
The grab is exactly the same as when I extract it from json.

below is the page:
<!DOCTYPE html>

<html>
    <head>
        
       
        <meta charset="UTF-8">
        <title>history</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="css/tabulator_bootstrap.css" rel="stylesheet" type="text/css"/>
        <link href="css/simple-grid.css" rel="stylesheet" type="text/css"/>
        <link href="css/cardcss.css" rel="stylesheet" type="text/css"/>
        <link href="css/style.css" rel="stylesheet" type="text/css"/>
        <script src="js/testformat.js" type="text/javascript"></script>
        <script src="js/session.js" type="text/javascript"></script>
        <script src="js/racecard8.js" type="text/javascript"></script> 
        <script src="js/jquery-3.3.1.min.js"></script>
        <script src="js/jquery-ui.min.js"></script>
        <script src="js/jquery.sparkline.js" type="text/javascript"></script>
        <script src="js/callbacks.js"></script>
        <script  src="js/tabulator.js" type="text/javascript"></script>
       
       
<style>
body, html {
  height: 100%;
  margin: 0;
  font-family: Arial;
}

/* Style tab links */
.tablink {
  background-color: #555;
  color: white;
  float: left;
  border: none;
  outline: none;
  cursor: pointer;
  padding: 8px 16px;
  font-size: 14px;
  width: 25%;
  border-radius: 8px 8px 0 0;
}

.tablink:hover {
  background-color: #777;
}


.tabcontent {
  color: black;
  display: none;
  padding: 70px 20px;
  height: 100%;
}

</style>        
     
        
<script>
    
   var objHistory = [
        {'date':'1/1/2017','venue':'Cheltenham','distance':'16','code':'nh','class':'3', 'going':'gd','position':'1','lengths':'1','beaten':'werty','Jockey':'Jones','days':'200','goodrun':'y','early':'text','middle':'text','late':'text','season':'text','orplusminus':'test','racecond':'cl4 FlatHandicap','days':'24','trackstyle':'tough,lhanded'},
        {'date':'21/1/2017','venue':'Ascot','distance':'16','code':'nh','class':'3', 'going':'sft','position':'1','lengths':'4','beaten':'werty','Jockey':'Jones','Days':'20','goodrun':'y','early':'text','middle':'text','late':'text','season':'text','orplusminus':'test','racecond':'cl4 FlatHandicap','days':'24','trackstyle':'tight,rhanded'},
        {'date':'1/2/2017','venue':'Newcastle','distance':'20','code':'nh','class':'1', 'going':'sft','position':'7','lengths':'8','beaten':'tytyu','Jockey':'Jones','Days':'30','goodrun':'n','early':'text','middle':'text','late':'text','season':'text','orplusminus':'test','racecond':'cl4 FlatHandicap','days':'24','trackstyle':'galloping,lhanded'},
        {'date':'15/3/2017','venue':'Cheltenham','distance':'16','code':'nh','class':'1', 'going':'hy','position':'1','lengths':'1','beaten':'sdfff','Jockey':'Jones','Days':'30','goodrun':'y','early':'text','middle':'text','late':'text','season':'text','orplusminus':'test','racecond':'cl4 FlatHandicap','days':'24','trackstyle':'tough,rhanded'},
        {'date':'1/1/2018','venue':'Cheltenham','distance':'16','code':'nh','class':'3', 'going':'gd','position':'1','lengths':'1','beaten':'werty','Jockey':'Jones','days':'200','goodrun':'y','early':'text','middle':'text','late':'text','season':'text','orplusminus':'test','racecond':'cl4 FlatHandicap','days':'24','trackstyle':'tough,lhanded'},
        {'date':'21/1/2018','venue':'Ascot','distance':'16','code':'nh','class':'3', 'going':'sft','position':'1','lengths':'4','beaten':'werty','Jockey':'Jones','Days':'20','goodrun':'y','early':'text','middle':'text','late':'text','season':'text','orplusminus':'test','racecond':'cl4 FlatHandicap','days':'24','trackstyle':'tight,rhanded'},
        {'date':'1/2/2018','venue':'Newcastle','distance':'20','code':'nh','class':'1', 'going':'sft','position':'7','lengths':'8','beaten':'tytyu','Jockey':'Jones','Days':'30','goodrun':'n','early':'text','middle':'text','late':'text','season':'text','orplusminus':'test','racecond':'cl4 FlatHandicap','days':'24','trackstyle':'tough,rhanded'},
        {'date':'15/3/2018','venue':'Cheltenham','distance':'16','code':'nh','class':'1', 'going':'hy','position':'1','lengths':'1','beaten':'sdfff','Jockey':'Jones','Days':'30','goodrun':'y','early':'text','middle':'text','late':'text','season':'text','orplusminus':'test','racecond':'cl4 FlatHandicap','days':'24','trackstyle':'tough,rhanded'}
              ]; 
    
    
  // for testing spoof the variables received on url
  // sRunner="Premier Bond";
  // var sKey="KEMPT-01:15";
  // var objHistory = getHist(objJson,sRunner,sKey);  
   $("#history").tabulator({
         columns:[
           {title:"Date", field:"date", sorter:"date", editable:false,width:40,cssClass:"classhead classCell"},
           {title:"Course", field:"venue", sorter:"string", align:"left", editable:false,cssClass:"classhead classCell"},
           {title:"Distance", field:"distance", sorter:"number", align:"left",  editable:false,cssClass:"classhead classCell"},
           {title:"Code", field:"code", sorter:"number", align:"left",  editable:false,cssClass:"classhead classCell"},
           {title:"Class", field:"class", width:40, sorter:"number", editable:false,cssClass:"classhead classCell"},
           {title:"Going", field:"going",  align:"centre", sorter:"string", width:40, editable:false,cssClass:"classhead classCell"},
           {title:"Position", field:"position",  align:"centre", sorter:"number", width:40, editable:false,cssClass:"classhead classCell"},
           {title:"Margin", field:"lengths",  align:"centre", sorter:"number", width:40, editable:false,cssClass:"classhead classCell"},
           {title:"Nearest", field:"beaten",  align:"centre", sorter:"string", width:40, editable:false,cssClass:"classhead classCell"},
           {title:"DLR", field:"Days",  align:"centre", sorter:"number", width:40, editable:false,cssClass:"classhead classCell"},
           {title:"Run", field:"goodrun",  align:"centre", sorter:"number", width:40, editable:false,cssClass:"classhead classCell"}
          ] 
       });
        $("#history").tabulator("setData", objHistory);
/*     
 $(window).resize(function(){
  $("#history").tabulator("redraw");
});      
  */      
</script>
    </head>
    <body>
        <div id="history"> </div>
    </body>
    
    
</html>

**Comment by edtaaffe** [comment]
https://gyazo.com/bcb2d687f6e9fa260e6177f8d4e84b57
grab of title undefined

**Comment by olifolkerd** [comment]
Hey @edtaaffe,

Looking at that error it looks like an issue with the dataset, if you try passing in an empty array to the ***setData*** function, does it work?

Cheers

Oli :)

**Comment by edtaaffe** [comment]
Hi Oli,
The reason I am raising it is that I sort of agree that it must be something other than a failing tabulator script.
On the other hand, I debugged a working table and then the problem table and this contradicts your theory in that; the working table shows a successfully created blank table has been created in memory and hovering over it show the definition.
Doing the same with the problem table shows an error message as demonstrated previously. That points strongly to a problem in defining the table rows and columns as I see it, and I accept I know nothing of tabulator.
Also the debugger clearly demonstrates that the array has been created without an issue and is in memory.  to test this you can simply run the  code I pasted in yesterday.
Further to that: Yesterday I wrote my own grid scrip to build a table form the same array.
My script runs fine and builds a nice table albeit without the sorting which I liked, but more responsive to small screens.
I can't afford to spend any more time on this, I will write a sort function one day soon and use my own code, but I think it is probably  avery small thing causing this issue and I would have preferred to stick with your otherwise very nice script.
Thanks for all your help and support and keep up the good work.
