### ISSUE TITLE
flexible Height of the tble conainer

### ISSUE THREAD

**Issue by rexxitall** [olifolkerd/tabulator#1071]
Hi - great work.
At the moment i struggling a bit with a flexible layout. I want that the length and height follows the size of the outer div container where the table lives in. Width is easy and perfectly working. But i want also set the height in the same way. (i want also that the headers stay still on top) I tryed the height property and some css tricks but somehow nothing will work out. Maybee i am blind or to stupid - both might be possible. But if someone can give me a hint i would be very thankful. 
I have a event which fires on every resizing. So i think i just need to know how to kick tabulator to perform a redraw or something like that.
Best regards Thomas

**Comment by Nyut0n** [comment]
you're probably looking for this:
```javascript
$("#example-table").tabulator("redraw");
```
There's a small paragraph about changing table height in the documentation, Just CTRL+F for "setHeight" :)
