### ISSUE TITLE
Hiw to on some option on tabulator

### ISSUE THREAD

**Issue by weusthofm** [olifolkerd/tabulator#1072]
Hello, 

I would like to have the 50 or 100 option available on a button for pagination. I mean that there is a button extra with a option of the amount of row I would like to see. For example 50 or 100 rows in one table. How should I implement this.
Second question is how can I filter based on two arguments. For example I would kikelike to filter on date between 1-2-2014 and 1-3-2018. How can this be done?
Third question is more complex. If I select a row, is it possible to get the values if the colums, so that I can make a use of these value. This could be a string  or double, date,integer in our case. I would like to get the values so that I can use it for example select from in database request. So database name and tablename are in tabulator, after selecting the row, or maybe later only one cell, put a request like select * from database.table. How can I maje this work. 
Thanks in advance.

Marcel Weusthof

**Comment by olifolkerd** [comment]
Hey @weusthofm 

In answer to your questions.

**Pagination Buttons**
You can add any buttons or select or input elements anywhere outside the table, you just need to use an event on one of those elements to call the ***setPageSize*** function on the table to change its page size:

```js
$("#example-table").tabulator("setPageSize", 50);
```

Please read the [Pagination Documentation](http://tabulator.info/docs/3.5#pagination) for more information.

**Filtering**
You can pass multiple filters into the ***setFilter*** function
```js
///filter age great than 10 and less than 52
$("#example-table").tabulator("setFilter", [
    {field:"age", type:">", value:10},
    {field:"age", type:"<", value:52},
]);
```

Please read the [Filter Documentation](http://tabulator.info/docs/3.5#filtering) for more information.

**Row Selection**
You can use the ***rowSelected*** callback to get  [Row Component](http://tabulator.info/docs/3.5#components) for the selected row, then call the ***getData*** function on the component to get an object of all the data in that row:
```js
$("#example-table").tabulator({
    rowSelected:function(row){
        //row - row component for the selected row

        var rowData = row.getData();
    },
});
```
Please read the [Selectable Rows Documentation](http://tabulator.info/docs/3.5#selectable) for more information.

I hope that helps you out.

Cheers

Oli :)

**Comment by weusthofm** [comment]
Hello, thanks sofar for the answers.
However for the second question I think I wrote my question incorrect. The way you explain was known to me, but my question was related to the search filter on top in the column. Now you can only filter on one string or value. I would like filter based on two filter. As example I mentioned between 1-2-2018 and 1-3-2018.
How can I do that.
Verzonden vanaf mijn Huawei mobiele telefoon

-------- Oorspronkelijk bericht --------
Onderwerp: Re: [olifolkerd/tabulator] Hiw to on some option on tabulator (#1072)
Van: Oli Folkerd
Aan: olifolkerd/tabulator
Cc: "Weusthof, M.H.H. (EWI)" ,Mention


Hey @weusthofm<https://github.com/weusthofm>

In answer to your questions.

Pagination Buttons
You can add any buttons or select or input elements anywhere outside the table, you just need to use an event on one of those elements to call the setPageSize function on the table to change its page size:

$("#example-table").tabulator("setPageSize", 50);

Please read the Pagination Documentation<http://tabulator.info/docs/3.5#pagination> for more information.

Filtering
You can pass multiple filters into the setFilter function

///filter age great than 10 and less than 52
$("#example-table").tabulator("setFilter", [
    {field:"age", type:">", value:10},
    {field:"age", type:"<", value:52},
]);

Please read the Filter Documentation<http://tabulator.info/docs/3.5#filtering> for more information.

Row Selection
You can use the rowSelected callback to get Row Component<http://tabulator.info/docs/3.5#components> for the selected row, then call the getData function on the component to get an object of all the data in that row:

$("#example-table").tabulator({
    rowSelected:function(row){
        //row - row component for the selected row

        var rowData = row.getData();
    },
});

Please read the Selectable Rows Documentation<http://tabulator.info/docs/3.5#selectable> for more information.

I hope that helps you out.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @weusthofm 

There is an example of how to do this on the [Header Filter Example](http://tabulator.info/examples/3.5#filter-header), have a look at the progress column.

Cheers

Oli :)

**Comment by weusthofm** [comment]
Thanks for the fast response.

Marcel

Verzonden vanaf mijn Huawei mobiele telefoon

-------- Oorspronkelijk bericht --------
Onderwerp: Re: [olifolkerd/tabulator] Hiw to on some option on tabulator (#1072)
Van: Oli Folkerd
Aan: olifolkerd/tabulator
Cc: "Weusthof, M.H.H. (EWI)" ,Mention


Hey @weusthofm<https://github.com/weusthofm>

There is an example of how to do this on the Header Filter Example<http://tabulator.info/examples/3.5#filter-header>, have a look at the progress column.

Cheers

Oli :)

**Comment by weusthofm** [comment]
Hello,
How can I echo the RowData. I would like to see what the content if it's correct.
And would like to add it on the screen.
If I put an echo command in the function, the function is not working properly.

Marcel
Row Selection
You can use the rowSelected callback to get Row Component<http://tabulator.info/docs/3.5#components> for the selected row, then call the getData function on the component to get an object of all the data in that row:

$("#example-table").tabulator({
    rowSelected:function(row){
        //row - row component for the selected row

        var rowData = row.getData();
    },
});


________________________________
Van: Weusthof, M.H.H. (EWI)
Verzonden: zondag 22 april 2018 10:50:40
Aan: olifolkerd/tabulator
Onderwerp: Re: [olifolkerd/tabulator] Hiw to on some option on tabulator (#1072)

Thanks for the fast response.

Marcel

Verzonden vanaf mijn Huawei mobiele telefoon

-------- Oorspronkelijk bericht --------
Onderwerp: Re: [olifolkerd/tabulator] Hiw to on some option on tabulator (#1072)
Van: Oli Folkerd
Aan: olifolkerd/tabulator
Cc: "Weusthof, M.H.H. (EWI)" ,Mention


Hey @weusthofm<https://github.com/weusthofm>

There is an example of how to do this on the Header Filter Example<http://tabulator.info/examples/3.5#filter-header>, have a look at the progress column.

Cheers

Oli :)

**Comment by weusthofm** [comment]
How can I echo the RowData. I would like to see what the content if it is.
If I put an echo command in the function, the function is not working properly.
And I don't know how to get the VAR data out of the function.
And how can I present this data in a table.
I've added the structure

{
    rowSelected:function(row){
        //row - row component for the selected row

        var rowData = row.getData();
    },


To the following

         $("#example-table-grouping").closest("article").on("build", function(){

         //Grouping Example
         $("#example-table-grouping").tabulator({
             rowSelected:function(row){     //row - row component for the selected row
               var rowData = row.getData();
                },
             height:"560px",
             layout:"fitColumns",
             selectable:true, //make rows selectable
             movableRows:true,
             pagination:"local",
             paginationSize:10,
             groupBy:"schema_name",
             columns:[
             {title:"schema_name", field:"schema_name", width:200},
             {title:"table_name", field:"table_name"},
               ],
             rowSelectionChanged:function(data, rows){
             //update selected row counter on selection change
             $("#select-stats span").text(data.length);
            },
         });


         $("#example-table-grouping").tabulator("setData", 'database_tables.json');

         });

         $("#example-marcel").closest("article").on("build", function(){

         //AJAX Example
         $("#example-marcel").tabulator({
             height:"311px",
             layout:"fitColumns",
             placeholder:"No Data Set",
             columns:[
                    {title:"schema_name", field:"schema_name", width:200},
                           {title:"table_name", field:"table_name"},
                           ],
             });

         $("#marcel-trigger").click(function(){
             $("#example-marcel").tabulator("setData", rowData);

         })

         });



I've try to present the data via

$("#example-table").tabulator("setData", rowData);

However it's appearently empty, because my table is blank. The row is selected. That is confirmed by the
And when I try to echo this value I get no message at all.
What is wrong, and what do I have to change?
I also put on a click service That works fine. Only I've to find out how to position the button on the bottom site next to the other pagination. That something to find out.
I'll continue now with the selection part of a datestring on the header.  Selecting between two datestring is this a diffucult task, compared with the min max function in your example? Because of the datestring.

Marcel



________________________________
Van: Weusthof, M.H.H. (EWI)
Verzonden: zondag 22 april 2018 10:50
Aan: olifolkerd/tabulator
Onderwerp: Re: [olifolkerd/tabulator] Hiw to on some option on tabulator (#1072)

Thanks for the fast response.

Marcel

Verzonden vanaf mijn Huawei mobiele telefoon

-------- Oorspronkelijk bericht --------
Onderwerp: Re: [olifolkerd/tabulator] Hiw to on some option on tabulator (#1072)
Van: Oli Folkerd
Aan: olifolkerd/tabulator
Cc: "Weusthof, M.H.H. (EWI)" ,Mention


Hey @weusthofm<https://github.com/weusthofm>

There is an example of how to do this on the Header Filter Example<http://tabulator.info/examples/3.5#filter-header>, have a look at the progress column.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @weusthofm 

echo is a PHP function that runs server-side, as such it cannot be used client side with JavaScript. what are you trying to do, are you trying to dump it out to the console log, or display it onscreen for the user?

Cheers

Oli :)

**Comment by weusthofm** [comment]
Oli,

I would like to have it on screening, and to check if the row is selected correct. Based on the selection I would make use for request to the SQL. The row has information about database and tables containing in the database. So var rowdata is an array of database and table in my case. This should bevused tp make a following request in my sql.

Marcel

Verzonden vanaf mijn Huawei mobiele telefoon

-------- Oorspronkelijk bericht --------
Onderwerp: Re: [olifolkerd/tabulator] Hiw to on some option on tabulator (#1072)
Van: Oli Folkerd
Aan: olifolkerd/tabulator
Cc: "Weusthof, M.H.H. (EWI)" ,Mention


Hey @weusthofm<https://github.com/weusthofm>

echo is a PHP function that runs server-side, as such it cannot be used client side with JavaScript. what are you trying to do, are you trying to dump it out to the console log, or display it onscreen for the user?

Cheers

Oli :)

**Comment by weusthofm** [comment]
Oli,


I solved this problem. But I still have a question. If I groupby there is also the amount or row in the groupby. How can I extract this value. I would like to make a button where i select for pagination all rows. I've now the selection of 50 and 100 rows. But the amount of rows could be 44. So how to extract and present all the rows based on the maximum amount of rows.


Marcel

________________________________
Van: Weusthof, M.H.H. (EWI)
Verzonden: dinsdag 24 april 2018 07:48:50
Aan: olifolkerd/tabulator
Onderwerp: Re: [olifolkerd/tabulator] Hiw to on some option on tabulator (#1072)

Oli,

I would like to have it on screening, and to check if the row is selected correct. Based on the selection I would make use for request to the SQL. The row has information about database and tables containing in the database. So var rowdata is an array of database and table in my case. This should bevused tp make a following request in my sql.

Marcel

Verzonden vanaf mijn Huawei mobiele telefoon

-------- Oorspronkelijk bericht --------
Onderwerp: Re: [olifolkerd/tabulator] Hiw to on some option on tabulator (#1072)
Van: Oli Folkerd
Aan: olifolkerd/tabulator
Cc: "Weusthof, M.H.H. (EWI)" ,Mention


Hey @weusthofm<https://github.com/weusthofm>

echo is a PHP function that runs server-side, as such it cannot be used client side with JavaScript. what are you trying to do, are you trying to dump it out to the console log, or display it onscreen for the user?

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @weusthofm 

If you can get the [Group Component](http://tabulator.info/docs/3.5#component-group) for the group in question you could call get ***getRows*** function on it and then get the length of that array:

```js
var rowsInGroup = group.getRows().length
```

There are various grouping callbacks that return group components along with the ***getGroups*** function.

Cheers

Oli :)

**Comment by weusthofm** [comment]
Oli,

Is there a way to hide a column/field if this field has no data or is empty. I would likevto.make a big table with all the possible fields. If this field is empty, it should automatically hide these colums. Or do you know another way how to make automatically table with different fields.
Maybe based on hide and select the table based on name.
Another question is how to deselect a previous selected row if I select another row. The only option I found at your site was via buttons. It would be nice to do this automatically.

Marcel

Verzonden vanaf mijn Huawei mobiele telefoon

-------- Oorspronkelijk bericht --------
Onderwerp: Re: [olifolkerd/tabulator] Hiw to on some option on tabulator (#1072)
Van: Oli Folkerd
Aan: olifolkerd/tabulator
Cc: "Weusthof, M.H.H. (EWI)" ,Mention


Hey @weusthofm<https://github.com/weusthofm>

If you can get the Group Component<http://tabulator.info/docs/3.5#component-group> for the group in question you could call get getRows function on it and then get the length of that array:

var rowsInGroup = group.getRows().length

There are various grouping callbacks that return group components along with the getGroups function.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @weusthofm 

When it comes to hiding columns, you can call the ***hide*** or ***show*** function on a [Column Component](http://tabulator.info/docs/3.5#component-column) or you can call the ***showColumn*** or ***hideColumn*** function on the table.

You can also set the ***visible*** property on a [Column Definition](http://tabulator.info/docs/3.5#define-column-headers)

If you wanted to change the visibility of lots of columns at once, you could build a new column definition object array and pass it to the ***setColumns*** function

With the row selection, if you pass a value of 1 to the ***selectable*** setup option it will allow a rolling selection of one row.
```js
$("#example-table").tabulator({
	selectable:1,
});
```

I hope that helps you out :)

Could I ask that you take a moment to have a look through the [Examples](http://tabulator.info/examples/3.5) on the website and read through the [Documentation](http://tabulator.info/docs/3.5). Tabulator is extensively documented with working examples for most of the standard usage cases, and while i am certainly happy to continue answering questions on here, you will probably be able to find the answers to your queries much faster by having a quick read of the documentation.

Cheers

Oli :)

**Comment by weusthofm** [comment]
Hello Oli,


I understand your remark about reading through documentation.  But not all my question where in the documentation.

But I have for the moment a final question.


I would like to make from the following.

Based on array[1], in my example string test, I would like  to use this array[1] name for making the var accelerator available for setting the column.

I have no idea how I can transfer the array[1] name test in a var so that I can put in the content of var accelerator.

This array of test should be used for the fieldname and then set the columns acoording var accelerometer.


array[1] = test;

        var accelerometer = [
        {title:"_id", field:"_id", sorter:"string",width:75,responsive:0},
        {title:"Date", field:"timestamp", align:"left",mutator:function(value,data){
        var newDate = new Date();
        newDate.setTime(value);
        dateString = newDate.toLocaleString();
        return dateString },headerFilter:minMaxFilterEditor, align:"center",headerFilterFunc:minMaxFilterFunction,responsive:0,width:200},
        {title:"device_id", field:"device_id",align:"left",headerFilterPlaceholder:"enter...",headerFilter:"input",width:275,responsive:0},
        {title:"double_values_0", field:"double_values_0",width:175,responsive:2},
        {title:"double_values_1", field:"double_values_1",width:175 },
        {title:"accuracy", field:"accuracy", align:"center",headerFilter:"number", headerFilterPlaceholder:"at least...", headerFilterFunc:">=",widthGrow:2},
        {title:"Label", field:"label", align:"center",widthGrow:2}
        ];
        var fieldname = new Array() // an empty array of length 0
        fieldname = array[1]       // THIS IS NOT WORK AS ARRAY
        console.log(fieldname);    //HERE APPEARS ONLY THE NAME TEST, BUT SHOULD BE FILLED WITH THE VAR ACCELOREMETER
        $("#example-marcel").tabulator("setColumns", fieldname);
        So my question is, how can I get a array[1] name in such a way that I can put in the information of var accelerometer.

If the real accelerormeter

$("#example-marcel").tabulator("setColumns", accelerometer);
instead of
$("#example-marcel").tabulator("setColumns", fieldname);

the setColumns with accelerometer is working and not with fieldname.
Now I would have the same funtionality with a fieldname defined by array[1].

Please help me with this question.

Marcel




________________________________
Van: Oli Folkerd <notifications@github.com>
Verzonden: donderdag 26 april 2018 00:09:25
Aan: olifolkerd/tabulator
CC: Weusthof, M.H.H. (EWI); Mention
Onderwerp: Re: [olifolkerd/tabulator] Hiw to on some option on tabulator (#1072)


Hey @weusthofm<https://github.com/weusthofm>

When it comes to hiding columns, you can call the hide or show function on a Column Component<http://tabulator.info/docs/3.5#component-column> or you can call the showColumn or hideColumn function on the table.

You can also set the visible property on a Column Definition<http://tabulator.info/docs/3.5#define-column-headers>

If you wanted to change the visibility of lots of columns at once, you could build a new column definition object array and pass it to the setColumns function

With the row selection, if you pass a value of 1 to the selectable setup option it will allow a rolling selection of one row.

$("#example-table").tabulator({
        selectable:1,
});

I hope that helps you out :)

Could I ask that you take a moment to have a look through the Examples<http://tabulator.info/examples/3.5> on the website and read through the Documentation<http://tabulator.info/docs/3.5>. Tabulator is extensively documented with working examples for most of the standard usage cases, and while i am certainly happy to continue answering questions on here, you will probably be able to find the answers to your queries much faster by having a quick read of the documentation.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @weusthofm 

That isn't really a Tabulator question, but i would be happy to help

In your code above you are never assigning there ***accelerormeter*** array to the ***fieldname*** you also seem to be defining your arrays in a weird fashion.

If you want to assign one array to another you can just use the ***=*** operator:
```js
var accelerormeter= [...]; //your accelerormeter array definition

var fieldname = accelerormeter; //assign array to fieldname variable;
```

If you plan to change anything in the array, then you will need to do it slightly differently, in JavaScript arrays are passed by reference, so if you used the above code, changing one will change the other.

if you are only going to be adding or removing columns then a shallow clone will work and you can use the array ***slice*** function
```js
var fieldname = accelerormeter.slice(0); //shallow clone array into fieldname variable
```

I hope that helps.

Cheers

Oli :)
