### ISSUE TITLE
A quick query regarding a feature

### ISSUE THREAD

**Issue by prattyy** [olifolkerd/tabulator#1073]
hello
thank you very much  for this awesome plugin
havent started using it yet but just looking at the documentation it looks amazing
i need a quick direction from your side regarding the editable cell feature.
The examples show that when i click a cell it become editable Could you please let me know how can be a autocomplete implemented  using a library like jquery autocomplete or similar 
so that when i click a cell and start type i could get a drop-down list showing autocomplete options.
Any hint would be appreciated 
Thanks again

**Comment by olifolkerd** [comment]
Hey @prattyy 

This does seem to be a popular question at the moment, so i have added a custom autocomplete editor to the [Editor Example](http://tabulator.info/examples/3.5#editable) on the examples page of the website.

Try typing in any of the countries in the table into a cell in the ***Location*** column of the table.

The source for the editor can be found by clicking the ***View Source*** button under the table.

I hope that helps

Cheers

Oli :)
