### ISSUE TITLE
Reset Data?

### ISSUE THREAD

**Issue by jherjati** [olifolkerd/tabulator#1074]
Hay, using tabulator is enjoyable, however i get a bit confuse.

I'm using tabulator to form table that always update whenever user choose data input. Yet, i always end up with this kind of notif

"Tabulator does not allow options to be set after initialization unless there is a function defined for that purpose"

For example,
I provide 3 json and user can choose which one to display in table, till this there isn't any problem.
But while user want to change the data source, from which line i should change my code?
```js
//Data preparation
var key = temp.parentNode.parentNode.firstElementChild.firstElementChild.id;
var fitur = map.querySourceFeatures(key, {
	'sourceLayer': key
});
var jproperties = fitur.map(function (el) {
	return el.properties;
});
var keyNames = Object.keys(jproperties[0]);
var col = [{
	formatter: "rownum",
	align: "center",
	width: 40,
}];
var kolom = keyNames.map((keyName) => {
	return {
		field: keyName,
		title: keyName,
		sorter: typeof (jproperties[0][keyName]),
		align: typeof (jproperties[0][keyName]) == 'number' ? "left" : [],
		width: 100,
	}
});
col = col.concat(kolom);

$("#example-table").tabulator({
	height: 500, // set height of table to enable virtual DOM
	placeholder: "No Data Set",
	history: true,
	pagination: "local",
	paginationSize: 20,
	movableColumns: true,
	tooltipsHeader: false,
	selectable: true,
	layout: "fitColumns", //fit columns to width of table (optional)
	columns: col,
	rowSelectionChanged: function (data, rows) {
		//update selected row counter on selection change
		$("#select-stats span").text(data.length);
	},
});

$("#example-table").tabulator("setData", jproperties); 
```

**Comment by olifolkerd** [comment]
Hey @jherjati 

You can call the ***setData*** function as many times as you want, passing in a different set of data each time.

Cheers

Oli :)

**Comment by jherjati** [comment]
ok, i have another strategy sir, thank you for the answer

**Comment by BarkMergers** [comment]
Hi, did your other strategy work? Can you say what it was? Reloading new data with new columns is causing a real headache for me!

**Comment by olifolkerd** [comment]
Hey @BarkMergers 

What particular issues are you having, is calling ***setColumns*** and ***setData*** not working for you?

Another option is to build several tables and then only show the correct one to the user.

i hope that helps,

Cheers

Oli :)
