### ISSUE TITLE
Changing one line color 

### ISSUE THREAD

**Issue by OsemaPatron** [olifolkerd/tabulator#1075]
Hello 
I want to check each line if the 1st colon have a certain value (for example "Unknown managed entity ") the background of the line or the line color change into red for example .
I want to know if that is possible ? 
Thanx

**Comment by Nyut0n** [comment]
Hey @OsemaPatron ,
you can do this with a rowFormatter function in the constructor.
If you search (CTRL+F) the documentation page for "Row Formatting", there is an explanation with a code sample that does exactly what you are looking to do.
