### ISSUE TITLE
PDF Download question

### ISSUE THREAD

**Issue by shaunhurley** [olifolkerd/tabulator#1077]
Oli,

Great work with the jsPDF / AutoTable integration, I was starting to play with doing this manually when you dropped 3.5 and have saved me a great deal of pain! :)

One question relating to this - am I correct in assuming that the PDF output shows the raw table data, and that any cell, row or column formatter effects (currency, column totals, etc.) are lost?

Much appreciated,

Shaun

**Comment by olifolkerd** [comment]
Hey @shaunhurley 

Glad to hear you are enjoying the new feature!

You are correct, by default it uses the raw table data. If you would like to alter it before it is added to the download, you can use a download accessor, which can be set on the ***accessorDownload*** property of that columns defintion.

Have a look at the [Accessors Documentation](http://tabulator.info/docs/3.5#accessors) for more info.

I hope that helps.

Cheers

Oli :)
