### ISSUE TITLE
Question on Dropdown (editor: "select")

### ISSUE THREAD

**Issue by JoshWahlIntertek** [olifolkerd/tabulator#1079]
I have a dropdown that works great when i click on it but the problem I am having is that when it originally is populated the values (1,2,3) are being displayed, not the text associated with it (Active, Disabled, Deleted).  I am thinking I am doing something wrong with the formatter but I am unsure at this point and cant seem to find an example or documentation for what I am trying to do.  Any help would be appreciated.

**Comment by olifolkerd** [comment]
Hey @JoshWahlIntertek 

Could you post a copy of your table constructor object, i can then hopefully offer you some advice.

Cheers

Oli :)

**Comment by JoshWahlIntertek** [comment]
Thanks for the super quick reply.  We found our error was in a different part.  It was a typo that was causing our list to be create  displaying the numbers by accident.
