### ISSUE TITLE
Bootstrap 4 pagination buttons styling

### ISSUE THREAD

**Issue by michaelongithub** [olifolkerd/tabulator#1080]
Hi Oli
I wonder if it is possible to adapt Your tabulator_bootstrap.css to this styling:
https://getbootstrap.com/docs/4.0/components/pagination/
The current styling in .tabulator-page is not conform to the orininal b4 look.

Thanks for information or addition.
Cheers, Michael

**Comment by olifolkerd** [comment]
Hey Michael,

No problem, i had completely missed the pagination for the bootstrap 4 theme. I will include it in the next patch update

Thanks for the link, that will make it much easier.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @michaelongithub 

I have pushed an update for this to the master branch, i will include it in the patch release this evening.

Cheers

Oli :)

**Comment by michaelongithub** [comment]
Hi Oli

are You sure, that that is the desired result ?
![grafik](https://user-images.githubusercontent.com/5064432/40355916-f3f80c6c-5db7-11e8-81a7-cb6891f3e2a0.png)
Pager does not seem similar to https://getbootstrap.com/docs/4.0/components/pagination/

And loading newest file:
![grafik](https://user-images.githubusercontent.com/5064432/40356109-6fe5e63c-5db8-11e8-95aa-d88a9314156e.png)

Wondering if this is what You want.
Cheers, Michael

**Comment by olifolkerd** [comment]
Hey @michaelongithub 

You asked for it on the bootstrap 4 stylesheet, but you are including the bootstrap 3 stylesheet in your code.

you want to use ***tabulator_bootstrap4.min.css***

Cheers

Oli :)

**Comment by michaelongithub** [comment]
GRRRRRR embarassing, and thanks for replying
