### ISSUE TITLE
navigateDown() error

### ISSUE THREAD

**Issue by leonardorame** [olifolkerd/tabulator#1081]
Hi Oli!, this seems to be a bug.

When I call `$("#mytable").tabulator("navigateDown")` I get `TypeError: this.table is undefined[Learn More]`

I'm using 3.5.1

Regards,
Leonardo.

**Comment by olifolkerd** [comment]
Hey @leonardorame 

Thanks for the headsup, i have pushed a fix for this to the master branch and will include it in next weeks patch release.

Cheers

Oli :)
