### ISSUE TITLE
When will you add subtables?

### ISSUE THREAD

**Issue by Rodbjartson** [olifolkerd/tabulator#1082]
Hey Oli,
yet again thank you tremendously for your awesome plugin. It is handsdown, the best JS-library for tables.

The 3.4 and 3.5 releases added a lot of great functionality, and these patches just confirmed that you listen very carefully to the users and the great tabulator-community.

The only thing that prevents our company from taking full use of tabulator is the lack of subtables. It is an extremely important feature that I think many people really would love to see.
I can understand that it is quite hard and time-consuming to implement it. I would really like to help you out if you need help!

The roadmap just says "future" regarding this feature. I have using tabulator since November, and I would like to know whether you have more concrete plans regarding the sub-table feature.

Kind regards
Rodbjartson

**Comment by olifolkerd** [comment]
Hey @Rodbjartson 

You will be happy to hear you can already do this, there is an example of it in action on the [Examples Page](http://tabulator.info/examples/3.5#nested-tables)

The roadmap entry is to cover some more advanced nested table functionality after the 4,0 release is complete.

If you need any help with subtable just let me know.

Cheers

Oli :)
