### ISSUE TITLE
Highlight Changes on "Refresh"

### ISSUE THREAD

**Issue by xXmrotsXx** [olifolkerd/tabulator#1085]
Hey Oli,

I'm probably going about this the wrong way, but at the moment I'm querying a MySQL db in PHP and sending the JSON to populate my tabulator... All good there...

In a particular table, data will be refreshed (setdata) every ~30secs from the db. Is there a way in tabulator to compare data before and after the refresh, and highlight (jQuery .effect) the changes?

I'm thinking I may have to compare my jsons externally to tabulator and then add the effect manually, but it would be great if there was something I could use already.

Thanks again.

**Comment by olifolkerd** [comment]
Hey @xXmrotsXx 

Im afraid there is nothing built in to Tabulator to do this, you would have to do it manually.

Though feel free to post your solution here as it may help others.

Cheers

Oli :)
