### ISSUE TITLE
Getting page size or getting all table options

### ISSUE THREAD

**Issue by aswzen** [olifolkerd/tabulator#109]
Hot to get page size in tabulator from script?

Try with this code have no results
$("#table_id").tabulator('getPageSize');

or at least how getting all options that setted on tabulator?

Thank you in advance

**Comment by olifolkerd** [comment]
When using remote pagination the page size is set by the amount of data returned from the server. but if you want to find out client side, I suggest you use the ***getData*** function and get the length of the array.
```js
var pageSize = $("#example-table").tabulator("getData").length;
```
