### ISSUE TITLE
Adding sort arrows to column group header

### ISSUE THREAD

**Issue by jfmarasigan** [olifolkerd/tabulator#1094]
Hi, I'm trying to use the column group functionality and I noticed that the header for the column group does not have the arrows (or the sorting functionality). That's understandable since I think its up to the users to figure out the sorting.

I'm using the headerClick event for the custom sort and I want to have the same display effects for the column group header compared to the ordinary table columns with sorting. Is there any way to do this?

**Comment by olifolkerd** [comment]
Hey @jfmarasigan 

You can only sort by columns, there is no way to sort by a column group as it has no specific data of its own, and is made up of a series of columns with their own specific sorters.

Cheers

Oli :)
