### ISSUE TITLE
Add Header Filter to all Columns Programmatically...

### ISSUE THREAD

**Issue by Cdat24** [olifolkerd/tabulator#1095]
Hello all,
I'm currently creating a table programmatically via a table. I would like to add a header filter to each column without knowing the column title due to the user being able to select table columns based on a multi select... Is this possible?

**Comment by Cdat24** [comment]
I was able to accomplish this by creating an array of objects and passing the array to the columns option. 
Example:
// Array of Objects to be passed to the tabulator columns option.
      var headerFilters = []

      $.each(colArray, function (index, col) {
        //object creation
        headerFilters.push({title: col, headerFilter: true})
      })

      //console.log(JSON.stringify(headerFilters))

      // Call Tabulator on Table
      $('#ReportPreview').tabulator({
        layout: 'fitColumns',
        headerFilterPlaceholder:"filter data...",
        columns: headerFilters
      })

**Comment by adel314** [comment]
Would you be able to share the complete code?
