### ISSUE TITLE
Show / hide nested tables

### ISSUE THREAD

**Issue by GerritKnippschild** [olifolkerd/tabulator#1096]
Hi Oli,

at first: Nested table function of tabulator.js 3.5 is a great feature.
My question is (sorry if I should have overseen the solution in your tutorials): It is possible to show / hide nested tables within nested tables to visualize a tree structured with multiple hierarchies?

Thank you very much in advance!

Best regards,
Gerrit

**Comment by olifolkerd** [comment]
Hey @GerritKnippschild 

Thanks for the feedback, it is great to hear people are liking the feature.

Issue #1038 shows how to toggle nested tables visibility.

There would be nothing to stop you adding a rowFormatter to your second table, to embed a third in it if that is what you want.

I hope that helps.

Cheers

Oli :)

**Comment by rNianios** [comment]
Hi Oli,

Would it be possible to have a working example?
