### ISSUE TITLE
addRow function is not working properly on version 3.5

### ISSUE THREAD

**Issue by blackgod000** [olifolkerd/tabulator#1099]
When I want to add row to the top of the table, like this:
   `$(selector).tabulator("addRow", {_id: 0}, true);`
I get this error:
   "ReferenceError: activeRows is not defined[Learn More] tabulator.min.js:2:29240"

This code was working on version 3.4.*

**Comment by answerquest** [comment]
Just came here to report the same problem. For tables that have existing rows,***addRow*** is working fine. But where the table is empty, ***addRow*** is failing with this error. When using the full tabulator.js, here's where it's erroring: https://github.com/olifolkerd/tabulator/blob/master/dist/js/tabulator.js#L2783 
```
tabulator.js:2783 Uncaught ReferenceError: activeRows is not defined
    at RowManager.addRowActual (tabulator.js:2783)
    at RowManager.addRow (tabulator.js:2686)
    at tabulator.js:2720
    at Array.forEach (<anonymous>)
    at RowManager.addRows (tabulator.js:2718)
    at t.(anonymous function).(anonymous function).addRow (http://localhost:5000/lib/tabulator.js:6812:31)
    at t.(anonymous function).(anonymous function).addRow (http://localhost:5000/lib/jquery-ui.min.js:6:4499)
    at HTMLDivElement.<anonymous> (jquery-ui.min.js:6)
    at Function.each (jquery-3.3.1.min.js:2)
    at w.fn.init.each (jquery-3.3.1.min.js:2)
```

**Comment by answerquest** [comment]
Correction: this error is happening if..  

- [x] the table is empty,
- [x] and the second argument for adding row to top of table is set as ***true***
- [x] and (seemingly) if pagination is enabled.

I'm searching around the code now for ways to initialize ***activeRows*** variable.

**Comment by answerquest** [comment]
Yay, fixed it! Added ***activeRows*** declaration at the start of the function:
```
    RowManager.prototype.addRowActual = function (data, pos, index, blockRedraw) {

      var row = new Row(data || {}, this),
          top = this.findAddRowPos(pos),
          dispRows,
          activeRows = this.activeRows; // <-- define activeRows, copying from other places in the code

      if (!index && this.table.options.pagination && this.table.options.paginationAddRow == "page") {

        dispRows = this.getDisplayRows();

        if (top) {

          if (dispRows.length) {

            index = dispRows[0];
          } else {

            if (activeRows.length) { // <-- where the error was happening because activeRows wasn't defined
```
@olifolkerd I'm not going to do a PR as you'll need to compile in gulp and all. Will learn that stuff some day so I can contribute. 

@blackgod000 as a temporary fix, change your js src to **tabulator.js**, open it in a text editor, and add a line `var activeRows = this.activeRows;` at line number 2772, that should make things work for you.

**Comment by blackgod000** [comment]
Temporary fix is working and
thank you for the fast response.

**Comment by olifolkerd** [comment]
Hey @blackgod000  and @answerquest 

Thanks for letting me know, i will get a fix out for that this weekend.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @blackgod000 

I have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)

**Comment by irupeshprasai** [comment]
while i adding new row using  $('#BudgetAndInvoiceDetails').tabulator("addRow", {}, false); i have dropdown list in the table iteems all the time i add the addrow teh dropdoen list is reset in the table
