### ISSUE TITLE
getData returns wrong data immediately after deleteRow

### ISSUE THREAD

**Issue by vshankaa** [olifolkerd/tabulator#11]
After deleting a row, if I use getData method to get the data of the table, it's returning incomplete data.

**For example, if the table contains the following data...**
`{id:1, name:"Oli Bob", age:"12", gender:"male", height:1, col:"red", dob:"", cheese:1, lucky_no:5},`

`{id:2, name:"Mary May", age:"1", gender:"female", height:2, col:"blue", dob:"14/05/1982", cheese:true, lucky_no:10},`

`{id:3, name:"Christine Lobowski", age:"42", height:0, col:"green", dob:"22/05/1982", cheese:"true", lucky_no:12}`

**...And after deleting Row 2, getData returns...**
`{id:1, name:"Oli Bob", age:"12", gender:"male", height:1, col:"red", dob:"", cheese:1, lucky_no:5},`

`{Undefined}`

Am I doing something wrong?

**Comment by olifolkerd** [comment]
I will run a test this evening and correct the bug

**Comment by vshankaa** [comment]
Thank you. Looking forward for your test results.

**Comment by olifolkerd** [comment]
I have uploaded a fix for this now

**Comment by vshankaa** [comment]
Thank you!
