### ISSUE TITLE
it is possible the value in formatter:progress visible

### ISSUE THREAD

**Issue by kurtknippschild** [olifolkerd/tabulator#110]
Hi Oli,

a question.
It's possible the value in the cell with formatter: progress to show?
With hover or direct?

Thanks in advance.

MG Kurt

**Comment by olifolkerd** [comment]
You can set tooltips to show on hover on any column by setting the ***tooltip*** property to ***true*** in the column definition:

```js
$("#example-table").tabulator({
    columns:[
        {title:"progress", field:"progress", formatter:"progress", tooltip:true},
    ],
});
```

Full details of this feature can be found in the ToolTips section of the [Formatting Documentation](http://localhost/docs/#formatting);

**Comment by kurtknippschild** [comment]
Hi Oli,

thanks  for the quick and helpful answer.
It works.
Great compliment to your work.

MG Kurt
