### ISSUE TITLE
How to get selected data (or rows) in the displayed order?

### ISSUE THREAD

**Issue by zegkljan** [olifolkerd/tabulator#1101]
Using ``getData, true`` and ``getRows, true`` one can get all the data (rows) as they are filtered and sorted. However, ``getSelectedData`` and ``getSelectedRows`` return the selected data (rows) in the order they were selected. Is there any way to merge these two behaviors together, i.e. get selected data (or rows) that are not filtered out and in the order as are sorted? Or, equivalently, is there a any way to find out if a row (from ``getRows``) is selected or not?

**Comment by olifolkerd** [comment]
Hey @zegkljan 

There is currently no way to change the order of the row components from the ***getSelectedRows*** function, but you can call the ***getPosition*** function on the row component to get its current position in the table.

Let me know if that helps.

Cheers

Oli :)

**Comment by zegkljan** [comment]
@olifolkerd, thanks for advice but I have already found a workaround.

I disabled selecting and instead I added an extra "selected" column and a row click callback which toggles the boolean value in this column (which has some nice boolean-friendly formatter). I can then just use getData or getRows and ask for the value of this "selected" column.
