### ISSUE TITLE
Setted column widths remain unaltered

### ISSUE THREAD

**Issue by mariahanna** [olifolkerd/tabulator#1102]
Hey Oli,

I need the manually setted (dragged) column widths to remain unaltered after a postback or browser refresh. Probably stored in the session. How can I do that? 

Thanks!

**Comment by Nyut0n** [comment]
You could use the columnResized callback to read the new column width, save it in a cookie and then load/restore it when the page loads the next time.
Instead of a cookie you could AJAX it to the server if you have to use sessions for that, but I'd rather go the cookie way. :]

**Comment by mariahanna** [comment]
Thanks a lot, persistentLayout worked! :)
