### ISSUE TITLE
nested objects arrays

### ISSUE THREAD

**Issue by ryhill** [olifolkerd/tabulator#1104]
great library.

i am trying to get this thing working with nested arrays and objects.
I have the below json. I am trying to get subjects in the same row.
Any help on how i can access the subjects

[{id:2, 
name:'cain', 
parent:{id:01, parent_name:'adam'}
subjects:[
	{id:01,name:'science'},
	{id:01,name:'english'},
	{id:01,name:'maths'},
	{id:01,name:'computers'},
	{id:01,name:'german'},
	{id:01,name:'sanskrit'},
	]
}
],

**Comment by olifolkerd** [comment]
Hey @ryhill 

Thanks for your kind words.

Could you post a diagram of how you would like the table to be laid out based on that data, i can then provide you an example to help.

Cheers

Oli :)

**Comment by ryhill** [comment]
Hi Oli,

Thanks for the quick reply.

I am attaching the screenshot of how it can be displayed. Any help will be greatly appreciated

![tabulators](https://user-images.githubusercontent.com/33457591/39849875-240ea310-542c-11e8-81de-4c81f33f8a1e.png)

Thanks a ton in advance
Kiran

**Comment by olifolkerd** [comment]
Hi @ryhill 

You would not be able to achieve that directly from data formatted in that way, as it is not in a format that Tabulator can directly understand.

You would need to reformat it first, something like this:

```js
var originalData = [
    {
        id:2,
        name:'cain',
        parent:{id:01, parent_name:'adam'}
        subjects:[
            {id:01,name:'science'},
            {id:01,name:'english'},
            {id:01,name:'maths'},
            {id:01,name:'computers'},
            {id:01,name:'german'},
            {id:01,name:'sanskrit'},
        ]
    }
]

function reformatData(data){
    var output = [];

    data.forEach(function(student){
        student.subjects.forEach(function(subject){
            var row = {
                id:student.id,
                name:student.name,
                parent:student.parent,
                subjects:subject,
            }

            output.push(row);
        });
    });

    return output;
}

$("#example-table").tabulator("setData", formatData(originalData));
```

I hope that helps.

Cheers

Oli :)
