### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by ronaldlynn** [olifolkerd/tabulator#1105]
I want to use this plugin in one of my company's applications, but I haven't found a browser support matrix or other documentation about browser support.

What is the earliest version of Internet Explorer that is supported?
My apologies if this is the wrong place to ask.

**Comment by olifolkerd** [comment]
Hey @ronaldlynn 

Tabulator supports IE 11, all versions of edge, and pretty much all edge/chrome/safari versions since IE11 was released.

I hope that helps.

Cheers

Oli :)

**Comment by ronaldlynn** [comment]
Hi Oli,

Thanks for the quick reply. Unfortunately, we need to go back to at least IE 10 for this project, but I will definitely keep Tabulator in mind for future projects.

Thanks again,
Ron
