### ISSUE TITLE
JQuery Dependency

### ISSUE THREAD

**Issue by ydennisy** [olifolkerd/tabulator#1106]
Hello,
Is there any way to use this without the jQuery dependency?
If not - does the tabulator package load jQuery itself?
Thanks

**Comment by olifolkerd** [comment]
Hey @ydennisy 

At the moment, Tabulator is dependant on jQuery so there is no way to use it by itself. and it dosn't load jQuery itself to give you maximum flexibility over the version you use.

As of version 4.0 (being released around July this year) it will no longer be dependant on jQuery and will be able to run by itself.

Cheers

Oli :)
