### ISSUE TITLE
Column Definition: Visible does not reflect current status

### ISSUE THREAD

**Issue by bammv** [olifolkerd/tabulator#1107]
Should I expect the value of "visible:" to update in the column definition when its visibility is changed with showColumn, hideColumn, or toggleColumn? In my testing, the field value does not seem to update.

**Comment by olifolkerd** [comment]
Hey @bammv 

The column definition is used as a reference base state for the column, as such it is not updated by actions that change the column.

if you want to get access to that information you should use the ***getColumnLayout*** function which returns a subset of the column definition relating to the current layout state

Cheers

Oli :)
