### ISSUE TITLE
Issue on Internet Explorer

### ISSUE THREAD

**Issue by adryx92** [olifolkerd/tabulator#1109]
It's not a real issue, but IMHO it's not the expected behavior: on Internet Explorer if I filter the rows in the table (for eg. with a filter in the table header) then I cancel the value of the filter trough the "x" in the input element, the input is empty but the filter is not removed.

I think that can be easy fixed like this https://stackoverflow.com/a/14007839

**Comment by olifolkerd** [comment]
Hey @adryx92 

Thanks for getting in touch,

I will have a look into that for you this weekend and see if i can apply the suggested fix on the next patch release.

Cheers

Oli :)

**Comment by adel314** [comment]
I know this comment is not going to be helpful but I really hope we don't have to go down the dark path once again supporting IE and its non compliance.   The amount of grief Microsoft caused to developers in the past was monumental!

**Comment by olifolkerd** [comment]
Hi @adryx92 

Thanks for your feedback, Tabulator officially supports IE11 and will continue to do so for the foreseeable future.

While it does increase the development workload, it is still a critical part of a lot of enterprise systems, and so at least for the time being it is important to keep it supported.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @adryx92 

Thanks for the info. I have removed the "X" functionality from all microsoft browsers as none of them seem to implement it correctly at this time.

I have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)
