### ISSUE TITLE
Updating data from HTML tables

### ISSUE THREAD

**Issue by minalkArmstrong** [olifolkerd/tabulator#111]
I am using html table into tabulator. I am binding the data on dropdown changed event.
Issue is the new data is append on previous table entry. What i want is every time select change event call the new set of data should be displayed. tabulator clear function  is not working .
Black mark row is old data and red one is new data on select changed event.
![image](https://cloud.githubusercontent.com/assets/24350278/20857255/bef69806-b94b-11e6-82c3-bea66a694e6a.png)

**Comment by olifolkerd** [comment]
could you post the code for your Tabulator constructor and the on change binding and i will see what i can do for you.

Cheers

Oli

**Comment by minalkArmstrong** [comment]
**This is HTML code which bind to a div from  ajax function**
<table id='example-table'><thead><tr><th style='width:50px' >Sr.no</th><th>Partcode</th><th>Description</th><th>Delivery Location</th><th>Quantity</th><th>Delivery Date</th><th>UOM</th><th>Remarks</th><th>Attachment</th><th></th><th>RowId</th></thead><tbody><tr><td>1</td><td>MP-MS-BL-FO-L2000-W294-T1.5-00011</td><td>MS Cable Tray-Machined Part-Mild Steel-Solid Black-Formed-Length 2000mm-Width 294mm-Thickness 1.5mm-6.93kg/pc</td><td>nsk</td><td>3</td><td>04/12/2016</td><td>kg</td><td>test4</td><td></td><td><input  type='checkbox' onchange='selectID(6)'/></td><td>6</td></tr><tr><td>2</td><td>MP-MS-FO-L314.8-W276.4-T1.5-00346-1LC</td><td>Laser Cutting of  Chain Sprocket Cover, Inner-Manufactured Part-Mild Steel-Formed-Length 314.8mm-Width 276.4mm-Thickness 1.5mm-0.83kg/pc</td><td>thane</td><td>22</td><td>15/12/2016</td><td>kg</td><td>test</td><td></td><td><input  type='checkbox' onchange='selectID(26)'/></td><td>26</td></tr><tr><td>3</td><td>BO-DM-EL-ENC-RTL-AE1035500 200*300*155</td><td>Enclosure, 200Wx300Hx155D, with single door, one gland plate in the base, Right hand door hinge, cam lock, gasket, mounting plate, Powder coated RAL7035-Bought Out-Direct Material-Electrical and Electronics-Enclosures-Rittal</td><td>thane</td><td>34</td><td>03/12/2016</td><td>kg</td><td>test 23</td><td></td><td><input  type='checkbox' onchange='selectID(29)'/></td><td>29</td></tr><tr><td>4</td><td>BO-DM-ME-FS-APL-DIN09346SS</td><td>SS Hexagonal Nut M6 -Bought Out-Direct Material-Mechanical-Fasteners-Agrawal Fastenars</td><td>test</td><td>3645</td><td>30/11/2016</td><td>kg</td><td>test</td><td></td><td><input  type='checkbox' onchange='selectID(37)'/></td><td>37</td></tr><tr><td>5</td><td>MP-MS-FO-L1250-W134-T1-00029</td><td>MS Small width Cable Tray Cover Short -Manufactured Part-Mild Steel-Formed-Length 1250mm-Width 134mm-Thickness 1mm-1.31kg/pc</td><td>abc</td><td>45</td><td>30/11/2016</td><td>kg</td><td>test</td><td></td><td><input  type='checkbox' onchange='selectID(38)'/></td><td>38</td></tr><tr><td>6</td><td>SA-SF-A345 STANDS-A345 -03119</td><td>A345 Stands-Sub-Assembly-Stand (Fixed)-A345 Stands-164.5</td><td>thane</td><td>3</td><td>30/11/2016</td><td>kg</td><td>remarks</td><td></td><td><input  type='checkbox' onchange='selectID(41)'/></td><td>41</td></tr><tr><td>7</td><td>BO-CAPEX-RS-TPL-L4573-T2.4-C/Z-20024-C/Z-20024-Precoated </td><td>Z Perlin-C/Z-20024-C/Z-20024-Precoated-Bought Out-Capex-Rolled Section-Tata Perlin-Length 4573mm-Thickness 2.4mm-7.17</td><td>nsk</td><td>4</td><td>08/12/2016</td><td>m</td><td>test clr</td><td>Koala.jpg</td><td><input  type='checkbox' onchange='selectID(48)'/></td><td>48</td></tr><tr><td>8</td><td>BO-DM-EL-SE-WNG-IQ350NK70VA3</td><td>Inductive Proximity Switch (Sensor), Non Flush, Range 35mm, PNP NO/NC-Bought Out-Direct Material-Electrical and Electronics-Sensors-Wenglor</td><td>test</td><td>4</td><td>20/12/2016</td><td>kg</td><td>test</td><td>file-512.png</td><td><input  type='checkbox' onchange='selectID(57)'/></td><td>57</td></tr></tbody></table>



Code for tabulator:
  document.getElementById('example-table-demo').innerHTML = result;
         
          $("#example-table").tabulator({
              fitColumns: true,
              tooltips: true,
              progressiveRender: true,
              pagination: "local", //enable local pagination.
              paginationSize: 15, // this option can take any positive integer value (default = 10)
              columns: [


			{ title: "Sr.no", sorter: "number", width: 70 },
			{ title: "Partcode", sorter: "string", align: "left", headerFilter: true },
			{ title: "Description", width: 100, sorter: "string", width: 300, headerFilter: true },
			{ title: "Delivery Location", align: "center", sorter: "string", editable: true, headerFilter: true },
			{ title: "Quantity", sorter: "number", width: 95, editable: true, headerFilter: true },
			{ title: "Delivery Date", sorter: "date", align: "center", editable: true, headerFilter: true },
			{ title: "Remarks", align: "center", sorter: "string", editable: true, headerFilter: true },
			{ title: "UOM", sorter: "string", width: 70, editable: true, headerFilter: true },
			{ title: "Attachment", sorter: "string" },
			{ title: "RowId", visible: false },

			],
              cellEdited: function(id, field, value, oldValue, data, cell, row) {




                  Update(data);

              }
          });


On change Function:
function FetchIndentRecords() {
    var projcode = document.getElementById('<%=ddlprojectcode.ClientID%>').value;
    var userid = document.getElementById('<%=hdnuserID.ClientID%>').value;
    var loc = "IndentGen.aspx/FetchIndentRecords";
    $.ajax({
        type: "POST",
        url: loc,
        data: '{"Projcode":"' + projcode + '","UserID":"' + userid + '"}',
        contentType: "application/json; charset=utf-8",
        dataType: "json",
        success:
      function ClearControls(response) {
          var result = response.d;
          document.getElementById('example-table-demo').innerHTML = '';
          document.getElementById('example-table-demo').innerHTML = result;// result content the above html code.
       
          $("#example-table").tabulator({
              fitColumns: true,
              tooltips: true,
              progressiveRender: true,
              pagination: "local", //enable local pagination.
              paginationSize: 15, // this option can take any positive integer value (default = 10)
              columns: [


			{ title: "Sr.no", sorter: "number", width: 70 },
			{ title: "Partcode", sorter: "string", align: "left", headerFilter: true },
			{ title: "Description", width: 100, sorter: "string", width: 300, headerFilter: true },
			{ title: "Delivery Location", align: "center", sorter: "string", editable: true, headerFilter: true },
			{ title: "Quantity", sorter: "number", width: 95, editable: true, headerFilter: true },
			{ title: "Delivery Date", sorter: "date", align: "center", editable: true, headerFilter: true },
			{ title: "Remarks", align: "center", sorter: "string", editable: true, headerFilter: true },
			{ title: "UOM", sorter: "string", width: 70, editable: true, headerFilter: true },
			{ title: "Attachment", sorter: "string" },
			{ title: "RowId", visible: false },

			],
              cellEdited: function(id, field, value, oldValue, data, cell, row) {
                  Update(data);
              }
          });
      }

    });
}

This control is fabulous. It will be great if u solve my problem then i can use this control my project.This control is satisfies all my requirement. Thank you in advance.

**Comment by olifolkerd** [comment]
You seem to be parsing a new HTML element in each time, which is a bit unorthodox, usually you would make an ajax request for JSON data rather than an HTML formatted table. Then use the ***setData*** function to parse the data.

This way of doing things means you are calling the tabulator constructor more than once, which is resulting in data persisting from the previous setting. 

If you want to keep on doing things the way you are then you will need to call the ***destroy*** method on the existing Tabulator before you set the innerHTML of the table element to clear all the existing data and settings, then call the constructor again after:
```js
$("#example-table").tabulator("destroy");
```
This will mean you will loose any user config changes on the table when the data changes (column resizing, column reorders, sorting etc...)

As i have said though, this is seems very odd way to do things, not only does it result in having to rebuild the table every time, and the loss of user config settings, it also sends unnecessary markup along with the data. I would recommend checking out the [Ajax Example](http://olifolkerd.github.io/tabulator/examples/#ajax) for a better way to send data fro a server to the table.

**Comment by minalkArmstrong** [comment]
Dear oli,
Is it possible to add fileupload control to table like tickcross checkbox control?

**Comment by olifolkerd** [comment]
Hi Minalk,

Would you mind raising this as a separate issue so other people can find the answer if they search for it, i will of course be happy to show you how to do it.

Cheers

Oli

**Comment by minalkArmstrong** [comment]
ok no problem
