### ISSUE TITLE
Possible to filter across multiple fields?

### ISSUE THREAD

**Issue by dpatel20** [olifolkerd/tabulator#1111]
There is an example [here](http://tabulator.info/examples/3.5?#filter) of filtering but that is filtering a specific field at a time.

Is it possible to filter across all/multiple fields (i.e. search and filter). I know there might be issues of different types (string, number, etc) but I wonder if there is a way to search and filter, for example, all string fields when the user types in a search box?

**Comment by olifolkerd** [comment]
Hey @dpatel20 

You can certainly do this using [Complex Filtering](http://tabulator.info/docs/3.5#filtering), this allows you to run multiple filters using an ***OR*** comparison so if any of the specified columns match, the row passes the filter:

```js
$("#example-table").tabulator("setFilter", [
    [
        {field:"height", type:"<", value:142}, //with a height of less than 142
        {field:"name", type:"=", value:"steve"}, //or a name of steve
    ]
]);
```

I hope this helps,

Cheers

Oli :)

**Comment by dpatel20** [comment]
Sorry, I should have been clearer in my question. Is there a way to search and filter through ALL fields rather than me have to manually type each field into a complex filter function? Or can I just create a `.map` function that uses `getColumns()` to create an `or` filter array. Something like the following (this does not work for me - I get various errors):

```
function filterEverywhere(){
	var cols = $("#example-table-demo").tabulator("getColumns");
	var fields = [];
	cols.forEach(function(col){
		if(col.getField())
			fields.push(col.getField());
	})
	var filterData = fields.map(function(field){
			return {field: field, type:"like", value:"someVal"};
	});

	$("#example-table-demo").tabulator("setFilter", [
		filterData
	]);
}
```
But I assume that I would need some check in the `.map()` function that checks the type of the field (e.g. is is string, number, boolean, etc) and then return an appropriate value for `type:` (so, "like", "="). I was hoping to use `getSorters()` to do this but it always returns an empty array (bug?).

Anyway, if you could provide any assistance with this, it would be most appreciated.
