### ISSUE TITLE
Question re: inserting new row and updating new rowIndex from database

### ISSUE THREAD

**Issue by JimSmithJr** [olifolkerd/tabulator#1113]
My apologies for interrupting.  I have become a fan of your work do not want to deter your progress, however I am unable to find the answer to the following:
I have a table where I can either update existing data or add a new row and insert a new record.  I can return the new row from the database with the new rowIndex.  
Under "Add Data" on http://tabulator.info/docs/3.5 you mention that the function will check each row and either add or update existing data.  The new row is a result of a row insert so there is no rowIndex yet (from my database) My question is how would one update the rowIndex from the server?

**Comment by olifolkerd** [comment]
Hey @JimSmithJr 

No need to apologies, I am happy to answer any Tabulator questions you have.

There would be no way to do that with the add row functionality in tabulator as you have no index with which to refer to the original row, although if you knew its position in the table you could use the ***getRowFromPosition*** function to get the row component and then call the ***update function on that*.

I have two suggestions. if you are uploading all your updated table data to the server in one go then i suggest you just return the updated data, complete with index's, from that request and call the **setData*** or ***replaceData*** functions to replace all the data in one go.

If you only send the row to the server after a user has edited it, using something like the ***cellEdited** callback, then you could use the Cell Component to get the Row Component and then call update on that.

For example:

```js
$("#example-table").tabulator({
  	cellEdited:function(cell){
  		$.ajax({
  			url: "/url/to/server",
  			type: "post",
  			data:cell.getData(),
  			dataType:'json',
  			success: function (data) {
  				cell.getRow().update({id:data.id})
  			},
  		});
  	},
});
```

I hope that helps,

Cheers

Oli :)

**Comment by JimSmithJr** [comment]
Hi Oli,

I just wanted to thank you for your help on this subject - albeit late.  The solution is exactly what is working for me and is what I now have in production.  On my update I return the id of the value I updated, so if it's a new item and the id in the table returns null, then I'll update with the value returned from my api.  

I can thank you enough!

Jim
