### ISSUE TITLE
fitDataFill problem..columns are squeezed

### ISSUE THREAD

**Issue by ryhill** [olifolkerd/tabulator#1114]
Hi, 

When i try to apply fitDataFill, the columns are scrambled as in the image attached. but again when i manually  hit sort on any column, the table behaves properly

any idea for this kind of behaviour

Thanks

KIRAN

![fitdatafill](https://user-images.githubusercontent.com/33457591/39961419-2aaa96d8-5653-11e8-9489-6cddae25118c.PNG)

**Comment by olifolkerd** [comment]
Hey @ryhill 

That looks like you are loading data into the table when it is not visible, Tabulator can only layout the table correctly when the table is visible as elements that are not displayed have no dimensions.

To get round this you should call the ***redraw*** function on the table when you make it visible:

```js
$("#example-table").tabulator("redraw");
```
I hope that helps,

Cheers

Oli
