### ISSUE TITLE
is there an ajax memory leak in version 3.5.0?

### ISSUE THREAD

**Issue by ctlkkc** [olifolkerd/tabulator#1115]
Hi I used tabulator v3.4.6 which used to fixed an ajax memory leak issue when using ajax to 'setData', which acts as refreshing in the data in the table. In version 3.5.0 there is a new function 'replaceData' to replace 'setData' silently, using this function, it seems the memory leak behavior is back like version 3.3: memory usage increased as 'replaceData' called and new data populated into table(s). 
Can you help? Thank you in advance.

**Comment by olifolkerd** [comment]
Hey @ctlkkc 

Can you confirm that ***setData*** is working correctly and that the memory leak is only in ***replaceData*** or is it in both?

Cheers

Oli

**Comment by ctlkkc** [comment]
I'm using Google 66.0.3359.139 32bits as browser, and uses:
ajaxConfig: to update the page ajax update status element;
height:100%: to make the table a virtual dom;
copyboard..: enable copy functions;
ajaxResponse: process the ajax responses for the table columns;
formatter in column;
cellclick in column: to call self-defined functions for the clicked cell;
uses replaceData function: update the data periodically;

In Chrome taskmgr can see:
Javascript memory: stable;
shared memory: stable;
private memory: increases to GBs;
memory: increases to GBs;

**Comment by olifolkerd** [comment]
Hey @ctlkkc 

Thanks for the detailed info, that will help get to the bottom of the issue,

How fast are you seing the memory usage increasing, how many requests are you making per min etc?

Are you sending a lot of data to the table, how many rows/columns are you using?

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @ctlkkc 

I have tried to replicate this issue but i am having trouble creating any major leak.

I am testing with a dataset with 1000 rows and 22 columns

Looking at the performance montior, the memory usage is in the 20MB-30MB's sort of range, no where near the GB's you are proposing, (to get to the gigabyets you must be using some seriously large datasets or image content)

There is a slight increase in memory usage after a setData or refreshData command, which is to be expected, but after a few calls to the command the browsers JS garbage collector kicks in as expected and the memory usage returns to usual.

Could you provide some information on the size of your dataset, the number of columns/rows and if any of the content is media

are you using a lot of formatters on your data.

could you post a copy of your table constructor?

Cheers

Oli :)
