### ISSUE TITLE
sort data on load.

### ISSUE THREAD

**Issue by sumitpatil2405** [olifolkerd/tabulator#1116]
I am trying to to do 2 sort on table load and using the code from documentation but seems like its just doing only one sort.
kindly take a look on the sort function below and let me know whats wrong. 

	$("#table-bln-tabulator").tabulator("setData", tabledata); // Load Data into Table
			$("#table-bln-tabulator").tabulator({
			/ initialSort: [
               { column: "modified", dir: "desc" }, //sort by this first
                { column: "stage_id", dir: "asc" }, //then sort by this second
			    ]
		});

**Comment by olifolkerd** [comment]
Hey @sumitpatil2405 

That is correct, it will sort by one column then the next. If it is not sorting the way you expect try swapping the order of the two sorts.

Cheers

Oli :)

**Comment by sumitpatil2405** [comment]
Hey @olifolkerd  it works .. thank you for quick response.
