### ISSUE TITLE
PDF download question

### ISSUE THREAD

**Issue by adryx92** [olifolkerd/tabulator#1117]
Hello,
I'm trying to print a PDF table but I can't figure out if it's possibile to add some additional data. I checked the AutoTable sample on its website/GitHub and i saw that the table to print is constructed differently than in Tabulator. 
I mean...

AutoTable:
```
examples.content = function () {
    var doc = new jsPDF();

    doc.setFontSize(18);
    doc.text('A story about a person', 14, 22);
    doc.setFontSize(11);
    doc.setTextColor(100);
    var text = "foo bar"
    doc.text(text, 14, 30);

    var cols = getColumns();
    cols.splice(0, 2);
    doc.autoTable(cols, getData(40), {startY: 50, showHeader: 'firstPage'});

    doc.text(text, 14, doc.autoTable.previous.finalY + 10);

    return doc;
};
```
and Tabulator:
```
$("#example-table").tabulator("download", "pdf", "data.pdf", {
    orientation:"portrait", //set page orientation to portrait
    title:"Dynamics Quotation Report", //add title to report
    autoTable:{ //advanced table styling
        styles: {
            fillColor: [100, 255, 255]
        },
        columnStyles: {
            id: {fillColor: 255}
        },
        margin: {top: 60},
    },
);
```
I'd like to do something like this: https://simonbengtsson.github.io/jsPDF-AutoTable/#content

I saw on the Tabulator Documentation that it's possible to build a custom formatter but, if I understand correctly, it has nothing to do with that. What do you suggest to do? Is it possible to make something like the linked example (with some information on the top, page numbers, title size, etc.)?
Thank you

**Comment by olifolkerd** [comment]
Hey @adryx92 

Thanks for getting in touch,

At the moment that isnt possible with the inbuilt PDF downloader, the basics of the PDF download were added in the last release, the next release will contain a series of updates that will allow for customisation of the content of the PDF.

In the mean time you could create your own PDF download function to add this functionality, issue #666 has an example of someone creating their own downloader.

I hope that helps,

Cheers

Oli :)

**Comment by adryx92** [comment]
Ok, thank you.
