### ISSUE TITLE
How to hide the header row from tabulator

### ISSUE THREAD

**Issue by cemmons** [olifolkerd/tabulator#1118]
Hi Oli,

I'm working on a selectable users from table A to table B, it should look like this:

![image](https://user-images.githubusercontent.com/5125512/40033849-31a0cb44-57c8-11e8-8aa3-cb4667e5f7af.png)

I figured i could use tabulator with two tables and the drag & drop feature, it also makes the loading of the data very simple.

What I want to replicate is to not have a header with the descriptions. is there a way to achieve this with some custom configuration?.

Thanks in advance. Your tabulator  has really come in handy.

**Comment by olifolkerd** [comment]
Hey @cemmons 

Tabulator is not designed to work without the column headers, but you could try using CSS to set the height of the ***.tabulator-header*** class to 0.

I hope that helps.

Cheers

Oli :)

**Comment by roypardi** [comment]
Just confirming that seems to work.

```
.tabulator-header {
    height: 0;
}


```

**Comment by ozzi-** [comment]
Try https://tabulator.info/docs/4.9/columns#vertical

**Comment by tilkeshnyatihomefirst** [comment]
How can we add this inline?
