### ISSUE TITLE
Repeatable Column Grouping Formatting Error

### ISSUE THREAD

**Issue by adel314** [olifolkerd/tabulator#1119]
I have a suggestion.  After a fair bit of head scratching it is safe to say that  if the number of fields in the data declaration do not match the number of fields in the columns declaration, then Tabulator just grabs the next fields that match and eventually the formatting and the data getting corrupted.    I am sure this is known behaviour and means that the developer must ensure that there is a match.   An option could be to Tabulator to just not render the columns that do not have matching data.

It was my inexperience with Tabulator that caused a bit of grief with this issue but I offer the suggestion anyway.   Any thoughts?

**Comment by olifolkerd** [comment]
Hey @adel314 

The number of fields in the row data should have no impact at all on the table layout, if a field is missing in the row data it is just treated as undefined, and any extra fields are ignored.

If you are having trouble, could you post a copy of the table constructor along with a picture of an visual issues you are having.

Cheers

Oli :)

**Comment by adel314** [comment]
Thanks Oli.   It must have been my inexperience with structuring the column data which I have been auto generating and it may have been this that was causing the first headings to not render.   Anyway, everything now appears to be working very well and thanks for taking the time to answer
