### ISSUE TITLE
Row calculations

### ISSUE THREAD

**Issue by kreamas** [olifolkerd/tabulator#1123]
Hi, I'm wondering if there's a way to create a row calculation.

I have a table with Years as rows and Months as columns, so I would like to  have the sum of the total year, but at the same time if the user writes another number in any month, then the sum of total year changes automatically and the difference two consecutive years can be calculated in  the cell next to the total.

Is it possible to do it?

Thanks in advance

**Comment by olifolkerd** [comment]
Hey @kreamas 

You could create an additional column to hold the calculation, make up a field name for it, then use a mutator to set the value of the column based on a sum of the other needed columns.

If you need a more specific example i would be happy to provide some more detailed pointers.

I hope that helps

Cheers

Oli :)

**Comment by kreamas** [comment]
Oli, Thanks a lot for your response :)

I'm also wondering if there's a way to get / set the value of a specific cell (even if it's not selected) using some [row, column] coordinates, maybe some type of matrix notation (something like cells(row, column) in VBA or df.iat[row, column] in pandas dataframe).

I must admit I'm all new in Tabulator, but I've found it just AWESOME :)

Regards from Mexico

**Comment by kreamas** [comment]
Oli, thanks a lot for your response.

I think I've got what I was looking for with similar instructions as yours.

I've done a 4 x 4 matrix of tables which must interact in some manner.  I want to trigger a cellEdited call which must update data in the rest of the tables.  I'm wondering if there's a way to get the <div> "id" from the table in which the cell was edited (every table has a different "id", for instance "t11", "t12", and so on).

Getting the div "id" I can pass it to the $("#idFromTableCellEdited").tabulator("getRowFromPosition...");

Is there a way to get that id?

Thanks a lot.

**Comment by olifolkerd** [comment]
Hey @kreamas 

You could always find the table element from the element of the cell component. in the cellEdited callback it would be something like:

```js
var id = cell.getElement().closest(".tabulator").attr("id");
```

I hope that helps.

Cheers

Oli :)

**Comment by OksanaRomaniv** [comment]
Hello @olifolkerd ,

Thank you for the great plugin!

I'm struggling with the same issue in my project with calculating row. I have a column "Total" that should display the sum of values of previous cells ("Drinks", "Event", "Catering") in the same row. When I set "mutator" function on the "Total" column to calculate the sum of needed cells the total is correctly calculated when the table is loaded. But it is not recalculated when I update any of the "Drinks", "Event", "Catering" cells values, only when I edit the "Total" cell. I would like to be able to show new total when any of the subtotal cell values change. Is this possible?

My column definition: 

```
{
    title: 'Total',
    field: 'total',
    align: 'center',
    editor: false,
    mutator: this.getTotalCost,
}
```
And the mutator function:

```
getTotalCost(value, rowData) {
    let total = 0;
    total = rowData.drinks + rowData.catering + rowData.cost;
    return total;
}
```
Thank you!

**Comment by kreamas** [comment]
Hi, I’ve solved that issue doing the following:

In my Ajax call I’ve defined this:

		       		//Unidades
					$("[id='" + id1 + "']").tabulator({

						//height:"100%",

						cellEdited:function(cell){
					   	     $("#listas").addClass('wait');
							var indice = cell.getRow().getIndex();
							cambioCelda(cell, meses, indice);
					   	     $("#listas").removeClass('wait');

						},			    

					    columns:kolumna,				    

					});          

					$("[id='" + id1 + "']").tabulator("setData", UniMdo);


Where id1 is the id of the div that contains my table….then in javascript I’ve defined the following function called “cambioCelda(cell, meses, indice)”..

Here is a extract of my code that first take the old value from the cell (I use it to refresh the values of the tables above by substracting the old value and adding the new value) and then it refresh everything.

function cambioCelda(celda, meses, posicion){


	//Get the row
	var viejoVal = celda.getOldValue();
	var nuevoVal = celda.getValue();

	var columna = celda.getField();

	var row = celda.getRow();
	var id = celda.getElement().closest(".tabulator").attr("id");

	var valor = id.substr(id.length - 7);

	if (valor == 'nidades'){
		valor = 'Unidades'
	}


	var renglon = $("[id = '" + id + "']").tabulator("getRow", posicion).getData();

	//List of old units
	var mUnitsOld = [];
	for (i = 1; i < (meses.length+1); i++){

		if (meses[i-1] == columna) {
			mUnitsOld.push(viejoVal);
		} else {
			mUnitsOld.push(parseFloat(renglon[meses[i-1]]));

		}

	}

	//List of old values (money)
	var balores = $("[id = '" + id.substr(0, id.length-8) + "Valores']").tabulator("getRow", posicion).getData();
	var mValueOld = [];
	for (i = 1; i < (meses.length+1); i++){
		mValueOld.push(parseFloat(balores[meses[i-1]]));
	}



	//Unidades Pack -----------------------------------------------------------------------------------------------------------
	//Recorremos el renglon para poner la suma del elemento actual
	var renglon = $("[id = '" + id + "']").tabulator("getRow", row).getData();

	var suma = 0;
	for (i = 1; i < (meses.length); i++){
		suma = suma + parseFloat(renglon[meses[i-1]]);
	}


	//Ponemos el Total
	$("[id = '" + id + "']").tabulator("getRow", row).update({'Total':suma});

}

My need was to modify an specific SKU in an specific month (at the bottom of my tables) and then it must also refresh the total year, total Share, Growth (from the current and the following years)…and it also has to refresh all the tables above because they contain the values of the total Brand, total family, total Customer and total Market (in that order).


It’s important to note that the algorithm runs much faster in Chrome than in Firefox and Edge (I don’t know why ☹)

Hope this helps
