### ISSUE TITLE
Unexpected row height increase when using row.update

### ISSUE THREAD

**Issue by kreamas** [olifolkerd/tabulator#1124]
Hi.

I've used the row.update({'MyColumn': 'MyNewValue'});

But the row in which it was applied increased its height unexpectedly.

Is there any way to prevent this behavior?

**Comment by olifolkerd** [comment]
Hey @kreamas 

Are you by any chance using a custom font in the table?

If that is the case then sometimes the table can load before the font has fully loaded, causing the first rendered rows to be shorter than they should be. when they are then updated, they are redrawn which fixes the initial sizing issue,

If this is the case let me know as i can suggest a way to prevent this.

Cheers

Oli :)
