### ISSUE TITLE
scrollToRow - Could not get it to work.

### ISSUE THREAD

**Issue by maheshkrishnappa** [olifolkerd/tabulator#1125]
I am using v3.5

Following is the table, columns and options set up.
$("#table-one").tabulator({
	index:"Column1",				
	layout:"fitColumns",
	width : "100%",
	placeholder:"No Data Set",
	scrollToRowPosition: "bottom",
	paginationSize:50,
	columns:[
		{title:"Column1", field:"column1_value", sorter:"number"}, 
		{title:"Column2", field:"column2_value", sorter:"string"},
		{title:"Column3", field:"column3_value", sorter:"string"}
	]
});
$('#table-one').tabulator("setData", aDataSet);

aDataSet: It is an array which has the data in the required key value pair to populate the table.

30 Records are loaded.

On the page where this table is rendered a button called Scroll is available. On click of this button a function "scrollToBottom()" is called.
function scrollToBottom(){
	$("#table-one").tabulator("scrollToRow", 30);
	//$("#table-one").tabulator("scrollToRow", 30, "bottom");
	//$("#table-one").tabulator("scrollToRow", 30, "bottom", true);
	//$("#table-one").tabulator("getRow",$("#table-one").tabulator("getRows")[$("#table-one").tabulator("getData").length-1].row).scrollTo();
}

I have tried the above mentioned 4 types of call to scrollToRow to scroll to bottom but I couldn't get it work.
When I inspect with breakpoints for the first 3 types of call to scrollToRow, true value is returned but doesn't scroll.
Also, after the table in rendered, on the chrome console, I tried running all the above mentioned call to scrollToRow, true is returned but it doesn't scroll.

I am not able to find out where I am going wrong.
Could you please help me to get it working?

**Comment by olifolkerd** [comment]
Hey @maheshkrishnappa 

You are trying to scroll to a row with an index value of ***30*** but nowhere in your row data have you created an index field to contain that value.

In tabulator, the index of a row is not its position in the table, but a unique key stored in the row data that can be used to link records back to server side databases, this has to be defined by the user, by default, this is set to the ***id*** field of the row data.

If you do not want to create an index in your data then you will need to look up the row by poisition (positions are 0 indexed) and can then scroll to that:

```js
var row = $("#example-table").tabulator("getRowFromPosition", 29, true);
row.scrollTo();
```

I hope that helps,

Cheers

Oli :)
