### ISSUE TITLE
Can't get the number from .getPosition()

### ISSUE THREAD

**Issue by kreamas** [olifolkerd/tabulator#1128]
Hi.

I'm trying to get the row position that comes from a cellEdited action.

The following is a snippet of my code:

				cellEdited:function(cell){
						var lista = ['January', 'February', 'March'];
						var campo = cell.getField();
						var row = cell.getRow();
						var posicion = row.getPostion();
						alert(posicion);
                                   },

But nothing is returned in my alert.

What am I doing wrong?

Thanks in advance

**Comment by olifolkerd** [comment]
Hey @kreamas 

you have a typo in your code, the function is ***getPosition*** not ***getPostion***

Cheers

Oli :)

**Comment by kreamas** [comment]
Oli, sorry for my dumb question...I feel shame.

Thanks a lot for all your unvaluable help. :D

**Comment by olifolkerd** [comment]
Hey @kreamas 

No problem, we all make typos from time to time :)
