### ISSUE TITLE
Export to XLSX or CSV Missing Parent Header Columns Names

### ISSUE THREAD

**Issue by YendorMc** [olifolkerd/tabulator#1129]
Hi Oli!

When exporting to XLS, or CSV, the "Parent" Column Name is missing.  In my case below, it's the Years (2019,2020,2021) that are missing in the export. 

 Would this a function of Tabulator or SheetJS?

As a workaround, can the field names be used instead of the headers?  The  JSON download  is working okay in that regard.

Here's the column definition:

```
"columns" :[
		{"title":"First Name", "field":"fname","headerFilter": true, "align":"center", "width":100,"headerSort":false,"frozen":true},
		{"title":"Last Name", "field":"lname","headerFilter": true, "align":"center", "width":100,"headerSort":false,"frozen":true},
		{"title":"2019","columns": [
			{"title":"Target", "field":"2019_Target" ,"align":"center", "width":80,"headerSort":false},
			{"title":"Achieved", "field":"2019_Achieved","align":"center", "width":80,"headerSort":false},
			{"title":"Bonus", "field":"2019_Bonus","align":"center", "width":80,"headerSort":false}
			]
		},
		{"title":"2020","columns": [
			{"title":"Target", "field":"2020_Target" ,"align":"center", "width":80,"headerSort":false},
			{"title":"Achieved",	"field":"2020_Achieved","align":"center", "width":80,"headerSort":false},
			{"title":"Bonus", "field":"2020_Bonus","align":"center", "width":80,"headerSort":false}
			]
		},
		{"title":"2021","columns": [
			{"title":"Target", "field":"2021_Target" ,"align":"center", "width":80,"headerSort":false},
			{"title":"Achieved","field":"2021_Achieved","align":"center", "width":80,"headerSort":false},
			{"title":"Bonus", "field":"2021_Bonus","align":"center", "width":80,"headerSort":false}
			]
		}
	]
```

**Comment by olifolkerd** [comment]
Hey @YendorMc 

It should use the column title be default, is this not happening for you?

Cheers

Oli :)

**Comment by YendorMc** [comment]
Tabulator seems to be using the 'secondary' column titles ONLY on export, which in my case they're all the same title.

For example, it's exporting as:
First Name,Last Name,Target,Achieved,Bonus,Target,Achieved,Bonus,Target,Achieved,Bonus
and can't distinguish the years.

I was hoping that the 'primary' column (e.g. 2019, 2020, 2021) would be on the 'top' row, on export, like it is shown in the actual Tabulator table.  

The workaround, unless there's something else I'm missing, would be to use the downloadTitle. 

Thanks!

**Comment by olifolkerd** [comment]
Hey @YendorMc 

I follow you now, only actual columns are included in downloads at the moment, not column groups.

An update in one of the next releases will allow column groups, row groups and calculations to show up in downloads.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @YendorMc 

As there is a lot of interest in new features for the download functionality i have created one issue where people can share their thoughts.

#1436

Cheers

Oli :)
