### ISSUE TITLE
With pagination, new row added above the last row

### ISSUE THREAD

**Issue by fcpana** [olifolkerd/tabulator#1130]
In version 3.5.1, with local pagination and paginationSize specified, adding a new row will add it above the last row instead of at the end. Disabling pagination seems to work.

Here is a jsfiddle example:
https://jsfiddle.net/vgt7vdu8/

**Comment by olifolkerd** [comment]
Hey @fcpana 

Thanks for the fiddle, that was very helpful.

It looks like an issue that only affects pages that do not have a full number of rows yet. i will get a fix out for this in the next patch release.

Thanks for the heads up!

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @fcpana 

I have just pushed a fix for this to the master branch, i will include it in this evenings patch release.

Cheers

Oli :)
