### ISSUE TITLE
Validate data on setData

### ISSUE THREAD

**Issue by MaceGames** [olifolkerd/tabulator#1131]
Hi,
Is there a way to validate data when you are setting it with setData?

//load sample data into the table
$("#example-table").tabulator("setData", tabledata);

So that table gets populated with data and the incorrect data automatically gets highlighted in red?

**Comment by thiagojulio** [comment]
## The table
```
$("#tabela").tabulator({
    height:"100%",
    weight:"100%",
    columns:[
        {title:"ID", field:"id", width:"8%"},
        {title:"Data", field:"data",width:"12%"},
    ],
    rowFormatter:function(row){
        if(row.getData().data >= "01/05/2018"){
            row.getElement().css({"background-color":"red"});
        }
    },
});
```

## The sample data
```
var tabledata = [
    {id:1, data:"01/05/2018"},
    {id:2, data:"01/07/2018"},
    {id:3, data:"01/04/2018"},
];
$("#tabela").tabulator("setData", tabledata);
```
### Set it any way you want
```
rowFormatter:function(row){
        /*  If date is greater than "01/05/2018" ,will be red */
        if(row.getData().data >= "01/05/2018"){
            /* Defining a line with the red color */
            row.getElement().css({"background-color":"red"});
        }
    },
```

### Result:
![Result](https://i.imgur.com/Qz3msrw.png)

# See more here, hope that I have helped.

[Documentation](http://tabulator.info/docs/3.5?#formatting)

[Example](http://tabulator.info/examples/3.5#formatters)

## __If you are updating your data you may need to redraw__...

**Comment by olifolkerd** [comment]
Hey @MaceGames 

You would have to do this manually using a series of [Custom Formatters](http://tabulator.info/examples/3.5?#clipboard) that check the value against some sort of validation function.

Tabulators inbuilt validation system is designed to prevent users from entering invalid data into the table in the first place. It assumes that all data provided my the ***setData*** function is valid.

Cheers

Oli :)
