### ISSUE TITLE
Add selection of table page size #paginationSize

### ISSUE THREAD

**Issue by thiagojulio** [olifolkerd/tabulator#1132]
# Add selection of table page size #paginationSize

as in the image, I already added and used the following function:
```
$("#linhas").change(function(){
    $("#tabela").tabulator("setPageSize", $(this).val());
    $("#tabelainativos").tabulator("setPageSize", $(this).val());
});
```

When selecting works, but ends up losing the style.
(style that is added in:
```
renderComplete:function(){
    $("[tabulator-field='codigo_barras']").addClass("number");
    $("[tabulator-field='preco_venda_principal']").addClass("number");
    $("[tabulator-field='descricao']").addClass("bold");
    $("[tabulator-field='id']").addClass("number");
},
```

is there an "Change paginationSize" sample function?or something like that?

thx ;

![Image of Yaktocat](https://i.imgur.com/bsKc81Q.png)

**Comment by olifolkerd** [comment]
Hey @thiagojulio 

You shouldn't be trying to trying to style the elements like that, direct manipulation of DOM elements will not work because of tabulators Virtual DOM.

if you want to add a CSS class to a given column you can use the ***cssClass*** property in that columns definition:
```js
{title:"Codigo Barras", field:"codigo_barras", cssClass:"number"}
```

I hope that helps

Cheers

Oli :)

**Comment by thiagojulio** [comment]
Would not have set the css only on the cell? without defining it in the header.

thx ;

**header must be bold and black and not red.**

![Print](https://i.imgur.com/oRZdIZ4.png)

**Comment by olifolkerd** [comment]
Hey @vasiliyaltunin 

That would add the class to both the cell and the header elements.

but you could easily restrict the focus of that with appropriate .tabulator-cell or .tabulator-class selectors.

If you cant use those selectors then i would recommend using a custom formatter to apply those classes:

```js
//custom formatter
var customNumberFormatter = function(cell, formatterParams){
    cell.getElement().addClass("number");

    return cell.getValue();
}

//column definition
{title:"Codigo Barras", field:"codigo_barras", formatter:customNumberFormatter }
```

Let me know if that helps.

Cheers

Oli :)

**Comment by thiagojulio** [comment]
Thank you, it worked perfectly.
