### ISSUE TITLE
Issues with clipboard in IE11

### ISSUE THREAD

**Issue by gzalo** [olifolkerd/tabulator#1133]
Hi! 

I'm having issues with the new clipboard functionality in IE11.371.16229.0. When attempting to copy a table row (either with ctrl+c or with copyToClipboard), a dialog window opens (which asks if you want the page to access the clipboard) but then it throws an errow and it doesn't modify the clipboard.

> “Unable to get property 'getData' of undefined or null reference” 

This issue can be reproduced in the example: http://tabulator.info/examples/3.5?#clipboard

Many thanks, Gonzalo

**Comment by olifolkerd** [comment]
Hey @gzalo 

Thanks for letting me know, i will look at getting a fix for this into the next patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @gzalo 

I have just pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)

**Comment by gzalo** [comment]
Awesome! Thanks
