### ISSUE TITLE
Missing check for null in copyToClipboard formatter

### ISSUE THREAD

**Issue by sbuethe** [olifolkerd/tabulator#1136]
Hi Oli,

I think, I encountered an issue with the programmatically triggered copyToClipboard function (clipboardCopySelector == 'active'). When "value == null" it is not handled on line 9871.

            if (typeof value == "undefined") {
              value = "";
            }
            value = typeof value == "undefined" ? "" : value.toString(); <-- code breaks here on line 9871

Also, check for typeof value == "undefined" is double.

Many thanks,

Sven

**Comment by olifolkerd** [comment]
Hey @sbuethe 

Sorry for the delay in getting back to you on this one, it seems to have slipped through the cracks.

Good spot there, i have just pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)
