### ISSUE TITLE
Mouse over effect for "simple" theme not working for odd rows

### ISSUE THREAD

**Issue by sbuethe** [olifolkerd/tabulator#1137]
Hi Oli,

If I use the simple theme css from a current commit, the hover effect is not working for odd rows. With commit 1273 it is still working.

Cheers,

Sven

**Comment by olifolkerd** [comment]
Hey @sbuethe 

In the simple theme there is no odd/event row colouring. please make sure you only include either the tabulator.css OR the tabulator_simple.css, not both.

Cheers

Oli
