### ISSUE TITLE
Getting Parent Group Information/Defintions

### ISSUE THREAD

**Issue by adel314** [olifolkerd/tabulator#1138]
I notice that there are new `getSubColumns` and `getParentColumn `methods however there does not appear any way to get the `ParentColumn `from the cell methods.   Is anyone able to shed light on this please?

I can get the column definitions using

`    		var column = cell.getColumn();
    		var def = column.getDefinition()`
but it appears not the `ParentColumn`.  

If possible it would be good to enhance the documentations so the object attributes/properties are declared as at the moment I am using a `convertToText` routine to convert the object to text but it is failing with the column objects due to "too much recursion".

Thanks

**Comment by olifolkerd** [comment]
Hey @adel314 

Thanks for getting in touch,

The functions for the component objects are fully documented on the website [Here}(http://tabulator.info/docs/3.5#components)/

you can get the column for a [Cell Component](http://tabulator.info/docs/3.5#component-cell) by calling the ***getColumn*** function on it, this returns a [Column Component](http://tabulator.info/docs/3.5#component-column) that you can then call the ***getSubColumns*** or ***getParentColumn*** function on this.

For example:
```js
var parentColumn = cell.getColumn().getParentColumn();
```

I hope that helps.

Cheers

Oli :)
