### ISSUE TITLE
Add row functionality doesn't work

### ISSUE THREAD

**Issue by hyperion0x** [olifolkerd/tabulator#1139]
Hi,

i'm tryng to use the addRow function but when i click on the adding button, nothing happens and no new row has shown.
in tabulator i have the followings parameters:

```js
$("#mytable").tabulator({
	height:240, // set height of table (in CSS or here), this enables the Virtual DOM and improves render speed dramatically (can be any valid css height value)
	//layout:"fitColumns", //fit columns to width of table (optional)
	selectable:true, //make rows selectable
	pagination:"local",
	paginationSize:5,
	movableColumns:true,
	layout:"fitDataFill",
	placeholder:"Nessun dato",
        locale:"it-it",
	addRowPos:"bottom",
```
and 

```js
$("#add-row").click(function(){
    $("#mytable").tabulator("addRow", {},true);
});
```
and of course the html button that points to "add-row" function above. When i click on this nothing happen, no errors and cannot see any new row in the bottom. Some suggestions?Could be maybe some parameters conflicts?

thanks a lot,

**Comment by olifolkerd** [comment]
Hey @hyperion0x 

Which version of Tabulator are you using?

if it is < 3.5 then it will be adding the row to the end of the table rather than the end of the page. if you are 3.5+ then this should be working, the new ***paginationAddRow*** was added in 3.5 to give control on how the addRow function behaves with paginated tables.

I hope that helps.

Cheers

Oli :)

**Comment by hyperion0x** [comment]
Hi Oli,
thanks for your prompt reply. I'm currently using 3.5 version.I'll try with paginationAddRow parameter and let you know ;)

**Comment by hyperion0x** [comment]
nothing to do :( doesn't work even with paginationAddRow setted. It looks like when i  press the "Add a new row" button nothing happen..any clue?

`$("#mytable").tabulator({
	height:240, // set height of table (in CSS or here), this enables the Virtual DOM and improves render speed dramatically (can be any valid css height value)
	//layout:"fitColumns", //fit columns to width of table (optional)
	selectable:true, //make rows selectable
	pagination:"local",
	paginationAddRow:"table",
	paginationSize:5,
	movableColumns:true,`

**Comment by olifolkerd** [comment]
Hey @hyperion0x 

are you getting any error messages in your console?

if you put a console.log in your click binding does that get triggered?

Cheers

Oli :)

**Comment by hyperion0x** [comment]
Hi Oli,

yes...i've put the following alert and it is shown, but no sign for the new row :(

`$("#add-row").click(function(){
		alert("Botton has been clicked!");
    $("#mytable").tabulator("addRow", {},true);
	});`

**Comment by hyperion0x** [comment]
this is the error shown on the console
![error_tabulator](https://user-images.githubusercontent.com/39456618/40588568-adefcdf0-61df-11e8-8113-76ca1befe0ea.PNG)

**Comment by olifolkerd** [comment]
I am afraid im not getting those errors when i run your code.

Where are you getting your source files from for Tabulator?
