### ISSUE TITLE
Making Data Editable

### ISSUE THREAD

**Issue by kkaramouzis** [olifolkerd/tabulator#114]
Can cells act like inputs and work with a submit button, so we could import data in database?

**Comment by olifolkerd** [comment]
Great question!

This has a two part answer. 
### Editing Data
To update cells you can use editors, you define the ***editor*** to use in the column definition array:
```js
$("example-table").tabulator({
    columns:[
        {title:"Name", field:"name", editor:"input"},
    ],
});
```

### Saving Data
You can get the edited data out of tabulator using the ***getData*** function. this will return an array of all the row objects:
```js
var updatedData = $("example-table").tabulator("getData");
```

You could then send this to the server with a ***post*** request for example:
```js
$.post("/url/fordata/", {tableData:updatedData});
```
Full details on how to use both of these function can be found in the [Editors Documentation](http://olifolkerd.github.io/tabulator/docs/#manipulating-data)

**Comment by olifolkerd** [comment]
Has this answered your question?

**Comment by olifolkerd** [comment]
Did this resolve your question? if i dont hear back from you in 7 days i will close this question due to inactivity
