### ISSUE TITLE
Can Anyone Tell me how to get the "Title" for the Parent Column Please

### ISSUE THREAD

**Issue by adel314** [olifolkerd/tabulator#1140]
I am able to access the the column object via

`var parentColumn = cell.getColumn().getParentColumn();`

but on the [(http://tabulator.info/docs/3.5#components)/](url) there is not mention of the properties or child methods to this object .  

If I loop through the methods/properties I get

column, type, getElement, getDefinition, getField, getCells, getVisibility etc

None return the  `Title`  and some of these return `undefined `so I am rather confused..

What I need is the ParentColumn Title

**Comment by olifolkerd** [comment]
Hey @adel314 


As mentioned in the documentation, this function returns a [Column Component](http://tabulator.info/docs/3.5#component-column) which means you can use any of the column component functions.

If you want to access the title of a column then you need to call the ***getDefinition*** function to return the column definition object that was used to create it. You can then look for the title on this object.

```js
var parentTitle = cell.getColumn().getParentColumn().getDefinition().title;
```

I hope that helps,

Cheers

Oli :)

**Comment by adel314** [comment]
Thanks Oli - much appreciated.  You have done an amazing job with this and I am learning by trial and error but for example I could not find any list of properties associated with `getDefinition` on your site.  Had I been able to find it I probably would not have needed to as the question because I was aware of the `getDefintion`  method.  Are the properties listed anywhere or is it that I have just not looked hard enough :-)

**Comment by olifolkerd** [comment]
Hey @adel314 

Thanks for your kind words.

The column definitions are the objects you set to build your columns, a full list of the availble options can be found in the [Column Definition Documentation](http://tabulator.info/docs/3.5#define-column-headers)

Cheers

Oli :)

**Comment by adel314** [comment]
Thanks Oli - I feel a bit silly now. For some inexplicable reason I did not see the relationship between methods and the properties used to build the tables :-(

**Comment by olifolkerd** [comment]
No problem,

its always tricky when you first pickup a new library, feel free to create more issues if you have any other questions.

Cheers

Oli :)
