### ISSUE TITLE
Support for rich text clipboard copying (text/html)

### ISSUE THREAD

**Issue by gzalo** [olifolkerd/tabulator#1143]
Hi
Right now, tabulator only supports copying a table as a text/plain data (tab separated values). This type of table can only be pasted in a spreadsheet program. It would be awesome if there was a way to copy the table as an html table, so that it could be pasted directly into an email, for instance.
Ideally it would share the same styles (borders, background color, font, ...) as the shown table, but it might be difficult to implement that way.

Here is a simple sample showing how it could be implemented (not working in IE11 😄 ): https://jsfiddle.net/km7prgv4/324/ 

Keep up the good work!
Thanks, Gonzalo

**Comment by gzalo** [comment]
Sorry, I just realised my request it's a duplicate of #1061 😞

**Comment by olifolkerd** [comment]
no problem, there are a lot to look through.

it is on the roadmap and should be available in the next couple of months.

Cheers

Oi :)
