### ISSUE TITLE
rowVal check in 'like' custom filter

### ISSUE THREAD

**Issue by dpatel20** [olifolkerd/tabulator#1145]
Hi Oli - with regards to issue #1111, I have my filter working but as mentioned in the other issue I have had to make the following change your code:

> Also, I had to add the following check to the "like" filter as rowVal could be undefined or null:
>`if(typeof rowVal != 'undefined' && rowVal)`

Would you consider this a bug or an issue in my implementation or how I have set up my table?

Here's my function:

```JS
	function filterEverywhere(input, exact_match) {
		var cols = $("#admin-fixture-data").tabulator("getColumnDefinitions");

		var filterData = [];
		cols.forEach(function (col) {
			if (col.field) {
				if (col.sorter === "string" || col.sorter === "alphanum") {
					if (isNaN(input)) {
						if (exact_match)
							filterData.push({ field: col.field, type: "=", value: input });
						else
							filterData.push({ field: col.field, type: "like", value: input });
					}
				}
				else if ((col.sorter === "number"))
					filterData.push({ field: col.field, type: "=", value: Number(input) });
			}
		});

		$("#admin-fixture-data").tabulator("setFilter", [
			filterData
		]);
	}
```

**Comment by olifolkerd** [comment]
Hey @dpatel20 

The like filter is currently only designed to handle strings so i would consider your update to the like filter to be an enhancement.

Would you like to submit a pull request to have the update included in Tabulator?

Cheers

Oli :)

**Comment by dpatel20** [comment]
Done...please see #1148.
