### ISSUE TITLE
Unable to change column header color

### ISSUE THREAD

**Issue by kreamas** [olifolkerd/tabulator#1146]
Hi, I'm trying to change column header color.

I'm trying to replicate the example of "Manually Adjusted Theme" with a table I've just made, but when 
I set in my CSS the following code:

#ValoresMercado .tabulator-header {
    background-color:#333;
    color:#fff;
}
...only the text is coloured in white but the columns are still the default gray.

Am I missing something in my code?, Is it possible to change the color only on a specific column ( For instance I hace a Column named "Total" which I would like to color its header Blue and a Column named "Growth" which I would like to color its header Orange)?

Is it also possible to change the background color of a specific cell?

Thanks in advance.

**Comment by olifolkerd** [comment]
Hey @kreamas 

The issue you are having is because you are changing the colour of the header bar which the column headers sit in front of, so you will also need to style the ***.tabulator-col*** class:
```css
#ValoresMercado .tabulator-header .tabulator-col
```

I hope that helps.

Cheers

Oli :)

**Comment by kreamas** [comment]
Thanks a lot Oli, it worked like a charm :)

Is there  a way to change the background color of a specific cell?
