### ISSUE TITLE
Mathemetical operations on cells on edit

### ISSUE THREAD

**Issue by kkaramouzis** [olifolkerd/tabulator#115]
Hello, is it possible to make operations between cells and not refresh the row like excel?

**Comment by olifolkerd** [comment]
Could you give me an example of what you mean, im not sure i completely understand.

**Comment by kkaramouzis** [comment]
i am sorry for my English, I meant mathematical operations between cells like addision or division 
for example if i have a quantity of 3 in the first cell and a price of 4$ in the second cell i want the third cell to come up with the multiplying effect of 3 and 4 =12 but if  i change one of the values in first cell or the second cell the third cell must change it s content automatically with the new multiplying effect.

**Comment by olifolkerd** [comment]
Ah yes you can certainly do that using the ***cellEdited*** callback:
```js
$("#example-table").tabulator({
    columns:[
        {Title:"Col 1", field:"col1", editor:"input"},
        {Title:"Col 2", field:"col2", editor:"input"},
        {Title:"Result", field:"result"},
    ],
    cellEdited:function(id, field, value, oldValue, data, cell, row){
        //id - the id of the row
        //field - field of the cell
        //value - the new value for the cell
        //oldValue - the old value for the cell
        //data - the data for the row
        //cell - the DOM element of the cell
        //row - the DOM element of the row
        
        //make sure correct calculation happens on correct cell edits
        switch(field){
            case "col1":
            case "col2":
                //calculate new value
                var sum = data.col1 * data.col2;
                
                //trigger value update on result cell
                $(".tabulator-cell[data-field=result]", row).trigger("editval", sum);
            break;
        }

    },
});
```

**Comment by olifolkerd** [comment]
Did this solve your problem?

**Comment by olifolkerd** [comment]
Did this resolve your question? if i dont hear back from you in 7 days i will close this question due to inactivity
