### ISSUE TITLE
set Pagination false

### ISSUE THREAD

**Issue by ryhill** [olifolkerd/tabulator#1151]
Hi,

is there any way to set pagination false

$("#example-table").tabulator("setPagination", "false");

Thanks

KIRAN

**Comment by adryx92** [comment]
The pagination is disabled by default, unless you explicitly enable it.
http://tabulator.info/docs/3.5#pagination

**Comment by olifolkerd** [comment]
Hey @ryhill 

Im afraid there is no way to toggle pagination once the table is created, as it is a completely different mode of operation from the standard table. Though having said this I am looking to make this possible later in the year.

In the mean time, people have worked around this by rebuilding the table with a new config object. you can call the ***destroy*** function on the table to remove it:
```js
$("#example-table").tabulator("destroy");
```
and then call the new constructor on it with the updated pagination settings.

I hope that helps.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
@Roman9961 

I think you have got confused there, this issue has nothing to do with calculations?

Cheers

Oli :)
