### ISSUE TITLE
Added Functionality

### ISSUE THREAD

**Issue by robcastle** [olifolkerd/tabulator#1152]
I added some functionality to the tabulator. I couldn't find a way to do remote paging against a javascript API (Qlik Sense) instead of against an AJAX call.

So I added a pagination type of "api" and added the ability to pass a callback function for paging for this new pagination type.

My question is this: I have made this change manually since I'm not sure of the proper way to build and package the tabulator. Do you have documentation on how to set up your build environment and how to run the build?

Alternatively do you have a way to extend the page object without messing with your code?

Also, I'm happy to submit my change to you if you would like it. If you would like to have the code I can write up the changes that I have made. They are fairly simple.

**Comment by olifolkerd** [comment]
Hey @robcastle 

You can already configure all the request options for the AJAX requests made through Tabulator.

In version 4.0 (coming in July) there will be a new promise based request system that will allow you to easily extend Tabulator to make any changes you want to the request architecture.

The [Extension Documentation](http://tabulator.info/docs/3.5#extending) takes you through how to setup the build environment.

You need to have Node.js installed then run ```npm install``` in the command line in the root of the repo, then when you are ready to build run ```gulp```

Cheers

Oli :)
