### ISSUE TITLE
Download CSV XLSX

### ISSUE THREAD

**Issue by mfenton01** [olifolkerd/tabulator#1156]
Oli, Discovered Tabulator a few days ago. Working on one of the demos to test functionality. The download button does not show up. Is there additional documentation I should review.

Versions installed
jquery ui 1.12
Jquery 3.3.1
Tabulator 3.5

[demo_test.txt](https://github.com/olifolkerd/tabulator/files/2037330/demo_test.txt)

Code attached

**Comment by olifolkerd** [comment]
Hey @mfenton01 

There is no download button built in to Tabulator, you should add the button anywhere you want and then use it to trigger the ***download*** function.

I hope that makes sense.

Cheers

Oli
