### ISSUE TITLE
Pagination Error - Requested page is out of range of 1 - 1   (2): Remote Pagination Error - Server response missing 'last_page' property

### ISSUE THREAD

**Issue by sajidkhaki** [olifolkerd/tabulator#1157]
$("#cardData").tabulator({
      height:500, // set height of table (in CSS or here), this enables the Virtual DOM and improves render speed dramatically (can be any valid css height value)
      layout:"fitColumns", //fit columns to width of table (optional)
      columns:[
        {title:"Card Type", field:"cardType"},
        {title:"Denomination", field:"denomination"},
        {title:"Card Number", field:"cardNumber"},
        {title:"Card Status", field:"cardStatus"},
        {title:"Supplier Name", field:"supplierName"},
      ],
      pagination:"remote", //enable remote pagination
      ajaxConfig:"GET", //ajax HTTP request type
      ajaxURL: "/cardServices/getcards/",
      layout:"fitColumns",
      paginationSize:1,
      contentType: 'application/json; charset=utf-8',
      responsiveLayout: true,
      paginationDataReceived: {
        "max_pages": "5" //change last_page parameter name to "max_pages"
      },

    });
    $("#cardData").tabulator("setPage", "/cardServices/getcards/");

**Comment by olifolkerd** [comment]
Hey @sajidkhaki 

Thanks for getting in touch,

When you are paginating data it requires a different ajax response to the standard table, it should resemble this:

```js
{
    "last_page":15, //the total number of available pages (this value must be greater than 0)
    "data":[ // an array of row data objects
        {id:1, name:"bob", age:"23"}, //example row data object
    ]
}
```

Full details can be found in the [Pagination Documentation](http://tabulator.info/docs/3.5#pagination)

I hope that helps,

Cheers

Oli
