### ISSUE TITLE
Is there any example of full CRUD? Maybe using PHP :-) 

### ISSUE THREAD

**Issue by alxbbarbosa** [olifolkerd/tabulator#1159]
Sorry for my English! 
this component looks wonderful. Very nice! Congratulations on your excellent work!
But I did not find any "crud" sample code. I tried creating one, but I had some difficulties: how to insert a new record line or how to update a record line.
I would like to use this component for many applications, but I am not able to create a correct crud using the tab.
I was able to retrieve data from the database and send it to an update form. And also delete. Got it! But, I have no idea how to update a record line after saving the data to a form or adding a new row after saving new data to a form. Do you have any php crud code?
I'm sure many will like an example like this and I'll post on a blog if you give me permission.

**Comment by olifolkerd** [comment]
Hey @alxbbarbosa 

Thanks for your kind words.

The [Editing and Manipulating Data documentation](http://tabulator.info/docs/3.5#manipulating-data) is full of a list of commands for doing exactly this sort of thing.

You can insert rows with the ***addRow*** function:
```js
$("#example-table").tabulator("addRow", {name:"Billy Bob", age:"12", gender:"male", height:1}, true);
```

and update rows with the ***updateRow*** function:
```js
$("#example-table").tabulator("updateRow", 1, {id:1, name:"bob", gender:"male"});
```

Please have a quick read through that section of the documentation and let me know if you have any questions.

Cheers

Oli :)

**Comment by tomvanlier** [comment]
I am currently using tabulator to develop something which will heavily rely on (C)RUD operations, so far I am only at ythe reading part and that's going very smooth. For the U/D part, I have some ideas in mind ... feel free to ask about them. 

I will probably use callbacks to update the db
