### ISSUE TITLE
FitToWidth and Scroll X

### ISSUE THREAD

**Issue by bvisonl** [olifolkerd/tabulator#116]
Is there a possibility to have the table initially fit the columns to width or have the sum of the width of all the columns be 100% and if you resize to a point where data cannot be displayed then permit the scrolling in the X direction? I know this is kind of asking for an inbetween of the fitColumns toggle but doesn't hurt to ask.

**Comment by olifolkerd** [comment]
There is a global ***colMinWidth*** setting that you can set to prevent columns shrinking beyond a certain width, at that point the table will scroll:
```js
$("#example-table").tabulator({
    colMinWidth:80, //Minimum column width in px (default = 40)
});
```
Would this be what you need, or would you be looking to set a min-width on a per column basis? if that is the case, it doesn't exist at the moment, but i would be happy to add it. let me know if you would like column based min-widths, I should be able to get it in this week.

**Comment by bvisonl** [comment]
It would be awesome if you could set the percentage instead of the pixel, I am trying to figure out how to use a standard configuration that I could open on any monitor and keep the content nice and aligned, if I open the table in a very big screen then I have a huge empty space unless I use the fitColumns which would then cause the scrollX not to show up in case someone resizes the window... so if let's say you have 5 columns and you set the width to 20% each then you will fill up the entire screen and if the person resizes then they would see the scrollX after the content cannot be shown anymore..

I know I am asking for a lot in just one paragraph but that's where I am leaning towards with this, but I guess that if that is not possible any time soon then I will have to play with the colMinWidth in every column

Let me know what you think or if I am overthinking this

**Comment by olifolkerd** [comment]
Great idea! i will look at enabling any valid css values for the width of columns, this may take slightly longer to implement, but i can certainly get it in for the next release.

I will post on here to keep you apprised of progress

**Comment by olifolkerd** [comment]
Good news, I have updated this section of Tabulator.

You can now set column widths in percentages:
```js
$("#example-table").tabulator({
    columns:[
        {title:"Name", field:"name", width:"50%"},
    ]
});
```

You can also define a minimum width per column:
```js
$("#example-table").tabulator({
    columns:[
        {title:"Name", field:"name", width:"50%", minWidth:70},
    ]
});
```

This should allow you to have columns that scale to fit the container and allow for overflow scrolling when the table gets to small

**Comment by bvisonl** [comment]
Sweet! this is what I was looking for, that solves many of my issues that I have with the other table that I am using.. Thanks for the quick response btw! keep it up

**Comment by olifolkerd** [comment]
Thank you for the great suggestion! let me know if you can think of any other great features!
