### ISSUE TITLE
prevent deselect the last selected row

### ISSUE THREAD

**Issue by mikexmagic** [olifolkerd/tabulator#1160]
Hi Experts,

how can I prevent that no one row is selected? I like to have always one row selected. I tried to play around with rowDeselected() and selectableCheck() callbacks...

Option 'selectable: is set to 1. It means max selected row = 1. How can I realize min selected row = 1 ??

Thx Mike

**Comment by olifolkerd** [comment]
Hey @mikexmagic 

You could use the ***selectableCheck*** callback for this. This callback is triggered to check whether the selection state of a row can be changed. by checking if there is only one item currently selected and that it matches the row being clicked you can block the deselect.

So you would be looking at something like this.

```js
$("#example-table").tabulator({
    selectableCheck:function(row){
        //row - row component
        
        var selectedRows = $("#example-table").tabulator("getSelectedRows");

        if(selectedRows.length == 1 && selectedRows[0] === row){
            return false; //block deselection if it is the last row
        }

        return true; //allow selection
    },
});
```

I hope that helps,

Cheers

Oli :)
