### ISSUE TITLE
Prevent negative numbers in tabulator

### ISSUE THREAD

**Issue by dpatel20** [olifolkerd/tabulator#1161]
What is the best option in tabulator to prevent negative numbers? Would I write a simple mutator which I assign to each column or is there a more global option I can set (e.g. a global mutator for all columns with `editor: "number"`?

**Comment by olifolkerd** [comment]
Hey @dpatel20 

Have a look at the [Validation Documentation](http://tabulator.info/docs/3.5#validation)

It will allow you to create a custom validator that will prevent users entering negative numbers into the table.

I hope that helps,

Cheers

Oli :)

**Comment by dpatel20** [comment]
Thanks...I was looking through the docs and didn't see it!! :/
