### ISSUE TITLE
Loading a big amount of tables takes a lot of time (c.a. 20 minutes)

### ISSUE THREAD

**Issue by kreamas** [olifolkerd/tabulator#1162]
Hello.

I've developed a web site which generates dynamically a lot of tables (nearly 500 tables) which comes from an Ajax call recieving information from Django.

Each table has 12 rows and 15 columns, however it takes about 20 minutes to be loaded into the web site and the Chrome message of "Page not responding" appears over and over again.

Django sends the information via Json within an array in which each entry is the information of each table from which then I loop element by element (table by table) using Javascript to dynamically create <div> with dynamic id's to load each table from the array.

Meanwhile, the tables recently created, make some calculations, for example, I have a bunch of tables of monthly prices and when it is loaded, another table is created with the monthly growth of each price.

As I stated at the beginning of this post, all the tables are loaded but it takes (I think) a lot of time to be loaded...is there a faster way to load this (or even greater) amount of tables?

Thanks a lot

**Comment by olifolkerd** [comment]
Hey @kreamas 

Wow that is a lot of tables!

I think you might be running out of memory in your browser trying to add that many tables to one page, each table can take 10-30MB of RAM, with 500 tables that is pushing into the GB's that will cause you serious issues.

You cant possibly be displaying all of these tables at the same time, how can a user take in all that information at once, it would be better practice to create the tables as they are displayed to the user and destroy them as they are hidden (eg as a user clicks on a tab), that would minimize data usage.

If you could post a copy of your table constructor i might be able to offer some optimisation tips

Cheers

Oli

**Comment by kreamas** [comment]
Yes, you're right Oli, thanks a lot for your time.

I think I'll display some filters to let my users display only the needed information.

Unfortunately (at least here in Mexico) there are a lot of people who ask things like "ok I need a software neither in Excel nor in desktop or Google Spreadsheets but a web development that has THE SAME behavior as Excel...what I need is...a bunch of tables interconnected that can be displayed on line...and when I say Excel, I'm thinking of a bunch of tables that if I change the value of a cell it affects a lot of interconnected tables"

But I think the best approach is the thing you suggested, by creating filters to display tables that need to be analyzed.

Again...Thanks a lot for your unvaluable time.

:)

**Comment by kreamas** [comment]
By the way, it is a web development that forecasts the brands of some pharmaceutical laboratories and their competitors.

So that's the reason I use Django to use Python and R from serverside and Ajax and Jquery to recieve and display the data.
