### ISSUE TITLE
ajax filter problem 

### ISSUE THREAD

**Issue by jlemaireWolf** [olifolkerd/tabulator#1163]
Hi Oli, 
i want reload my table paginate table with my filter , when i click on a button radio , but there is nothing happening, 
my button  :  
`if ($('#attend_statut').is(':checked')) {
$("#example-table-ajax").tabulator("setData","/strategie/gdpr/donnees&transform", {filter:"nomRole", filter_value:"Collaborateur", fitler_type:"like"});
}`
the url : /strategie/gdpr/donnees&transform?filter=nomRole&filter_value=Collaborateur&fitler_type=like&pageNumber=1&size=5  

Why is it not working?  i need your lights  :)

thank you in advance 

jérémy

**Comment by olifolkerd** [comment]
Hey @jlemaireWolf 

That isnt the correct way to add a filter to tabulator.

You should set the config option for ***ajaxURL*** of the table to the base url, in this case `/strategie/gdpr/donnees&transform` in your table constructor. and make sure that you have the ***ajaxFiltering*** option set to `true`.

you can then call the ***setFilter*** function on Tabulator, that will correctly trigger the loading of data.

I hope that helps,

Cheers

Oli :)

**Comment by jlemaireWolf** [comment]
Hey Oli,
yes my ajaxFiltering option set to true .
but there is this nagging feeling that I'm missing something.
When i click on my checkbox, nothing is filter :-/it is calling the url with my filter but my table not changed, i have the same datas

`$("#example-table-ajax").tabulator({
		width:"70%",
		sortBy:"dateLimite",
		sortDir:"asc",
		selectable:true,
		pagination:"remote", //enable remote pagination
  	        ajaxURL:"/strategie/gdpr/donnees&transform", //set url for ajax request
	        paginationDataSent:{
                     "page":"pageNumber",
			  //change page request parameter to "pageNo"
               } ,
		ajaxSorting:true,
		ajaxFiltering:true,
		paginationSize:5,
		height:"400px",
		layout:"fitColumns",
		placeholder:"Pas de collaborateur(s) correspondant au critère",`


and my checkbox with my filter :  
'$('#attend_statut').on('click',function () {
		if ($('#attend_statut').is(':checked')) {
			$("#example-table-ajax").tabulator("setFilter", "idUtilisateur", "like", 27304);
		}
	});
'

Thank you
Cheers

**Comment by olifolkerd** [comment]
in the dev console on your browser can you see the updated request being made?

**Comment by jlemaireWolf** [comment]
![capturebug3](https://user-images.githubusercontent.com/39595612/40849585-9d700152-65c2-11e8-8112-f7cad90835ee.PNG)

**Comment by olifolkerd** [comment]
Hey @jlemaireWolf 

In that case the issue is on the code you have server side that is processing the request.

You have to implement the filter functionality yourself server side,

Cheers

Oli :)
