### ISSUE TITLE
Stuck on rebuilding the same table with different data

### ISSUE THREAD

**Issue by hooodephuck** [olifolkerd/tabulator#1164]
Hi, 
Thanks for this excellent script.
I have achieved quite a bit, but now I am stuck.
I have a function called buildtable and it does the job. I made a calculation base don font size and recalcualte the size I need my table to be each time base don number of rows.
That worked when I was refreshing the page each time.
What I need though is the speed of changing data without the refresh.
I wrote a menu and started calling my buildtable() function from the onclick()

now when I click the menu it does build the table, but does not resize it and I get the error message
"cannot call methods on tabulator prior to initialization; attempted to call method 'setData"
Presumably if I don't change layout it will be OK, but that's not possible

What I need to achieve is 👍
 1. that I can click my menu for different subjects and in response load the correct data and change the table.(works fine if no table already exists). 
2. Resize to just fit the number of rows no scrolling or dark areas.
The data structure is always the same but the number of rows can change significantly.
3. I need to get a responsive  layout so I can hide a lot of columns on mobiles and tablets, but I have to write a function to switch to the missing columns. (This last bit I assume I can do with hide and show columns)

I had no luck with responsive at all. I had been considering making three tables in three divs, but there must be a better way,

I don,t know any way to destroy an object from memory in Javascript or that might solve the error I am getting to let me build it again, My tables are small and load time is instant, but refreshing the page is ugly and slow in my view and I really don't want this.

Ant suggestions how I might do it.

H

**Comment by olifolkerd** [comment]
Hey @hooodephuck 

That error message suggest your are trying to call the ***setData*** function on tabulator, before you can called the constructor function to build the table.


Have a look at the order of the calls you are making to avoid that issue.

How many rows are you loading into the table? if you dont want a scroll bar you can disable the virtual DOM by setting the ***virtualDOM*** property to `false`, you then wont need to set a height on the table, it will automatically resize to fit all the rows, but if you are loading a lot of data this will be VERY slow

Have a look at the [Responsive Collapsed List](http://tabulator.info/docs/3.5#responsive-layout-collapse) that lets you show the missing data as a list, which may be able to help you display everything you need.

You can use the ***destroy*** method on a jQuery plugin like tabulator to remove it:
```js
$("#example-table").tabulator("destroy");
```

I hope that helps,

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @hooodephuck 

The responsive mode is only available with the virtual DOM enabled, which is why it is no longer working for you, sorry i should have been clearer with that in my answer.

could you post a copy of your full table constructor, it will be easier to give you advice if i can see how the whole table is setup.

Cheers

Oli :)

**Comment by hooodephuck** [comment]
code

` $("#tab").tabulator({
         virtualdom:true,
         responsiveLayout:true,
         layout:"fitDataFill",
         layout:"fitColumns",
         movableCols:true,
         persistentLayout: true,
         persistentLayoutID:"ePerststance",
         persistenceMode:"cookie",
         movableRows:true,
         tooltips:true,
         columnMinWidth:28, 
         columns:[
           {title:"id", field:"1", sorter:"string", editable:false,width:40,responsive:0},
           {title:"name", field:"name", sorter:"string", align:"left", editable:false,headerTooltip:"",cssClass:"classhead classCell",responsive:0,cellContext:rclick,formatter:ulink},
           {title:"no", field:"no", sorter:"number", align:"left",  editable:false,headerTooltip:"",cssClass:"classhead classCell",responsive:0,cellContext:rclick,headerTooltip:""},
           {title:"buy", field:"buy", width:40, sorter:"string", editable:false,headerTooltip:"",cssClass:"classhead classCell",cellContext:rclick, responsive:10},
           {title:"sell", field:"sell",  align:"centre", sorter:"number", width:40, editable:false,headerTooltip:"", responsive:8,cssClass:"classhead classCell",cellContext:rclick},
           {title:"Shortlist", field:"Shortlist", width:100, sorter:"string", align:"left",responsive:1,editable:true,cssClass:"classhead classCell",formatter:"star",editor:"star",cellContext:rclick,headerTooltip:""},
           {title:"Direction", field:"Direction", width: 140, editable:false,cssClass:"classhead classCell",cellContext:rclick,headerTooltip:"",formatter:function(cell,formatterParams){
    setTimeout(function(){ //give cell enough time to be added to the DOM before calling sparkline formatter
        cell.getElement().sparkline(cell.getValue(), {width:"100%", type:"line", disableTooltips:true,lineColor: '#2ba029',cellContext:rclick,
    fillColor: '#CBD831',  minSpotColor: '#ff0000', maxSpotColor: '#007f3f', highlightSpotColor: '#00bf00',cellContext:rclick,
    highlightLineColor: '#007f00'});
    }, 10);
}    
   },
           //{title:"Naps ", field:"6",  align:"centre", sorter:"number", width:40, editable:false,headerTooltip:"",cssClass:"classhead classCell",formatter:progressFormatter,cellContext:rclick},
          {title:"Potential", field:"Potential",  align:"centre", sorter:"number", width:40, editable:false,headerTooltip:"",cssClass:"classhead classCell",formatter:progressFormatter,tooltip:ttips,cellContext:rclick,responsive:9},
          {title:"rating", field:"rating",  align:"centre", sorter:"number", width:40, editable:false,cssClass:"classhead classCell", formatter:progressFormatter,tooltip:ttips,headerTooltip:"",cellContext:rclick},
          {title:"ratio1 ", field:"ratio1",  align:"centre", sorter:"number", width:40, editable:false,cssClass:"classhead classCell",formatter:progressFormatter,tooltip:ttips,headerTooltip:"",cellContext:rclick},
          {title:"ratio2", field:"ratio2",  align:"centre", sorter:"number", width:40, editable:false,cssClass:"classhead classCell",formatter:progressFormatter,tooltip:ttips,headerTooltip:"",cellContext:rclick},
          {title:"ratio3", field:"ratio3",  align:"centre", sorter:"number", width:40, editable:false,cssClass:"classhead classCell",formatter:progressFormatter,tooltip:ttips,headerTooltip:"",cellContext:rclick},
          {title:"ratio4", field:"ratio4",  align:"centre", sorter:"number", width:40, editable:false,cssClass:"classhead classCell",formatter:progressFormatter,tooltip:ttips,headerTooltip:"",cellContext:rclick},
          {title:"Team", field:"13",  align:"centre", sorter:"number", width:40, editable:false,cssClass:"classhead classCell",formatter:progressFormatter,tooltip:ttips,cellContext:rclick,responsive:7},
          {title:"Vibe", field:"15",  align:"centre", sorter:"number", width:40, editable:false,headerTooltip:"",cssClass:"classhead classCell",formatter:progressFormatter,tooltip:ttips,cellContext:rclick,responsive:8},
          {title:"reports", field:"reports",  align:"left", sorter:"number", width:80, editable:false,headerTooltip:"",cssClass:"classhead classCell",cellContext:rclick,responsive:5},
          {title:"perf", field:"perf",  align:"centre", sorter:"number", width:40, editable:false,headerTooltip:"",cssClass:"classhead classCell",formatter:progressFormatter,tooltip:ttips,cellContext:rclick,responsive:6},
          {title:"Class", field:"class",  align:"centre", sorter:"number", width:40, editable:false,headerTooltip:"",cssClass:"classhead classCell",cellContext:rclick,responsive:4},
          {title:"Profile", field:"Profile",  align:"centre", sorter:"string", width:100, editable:false,headerTooltip:"",cssClass:"classhead classCell",cellContext:rclick,responsive:3},
          {title:"dates", field:"dates",  align:"centre", sorter:"number", width:40, editable:false,headerTooltip:"",cssClass:"classhead classCell",formatter:progressRevFormatter,tooltip:ttips,cellContext:rclick,responsive:2}
          ],
       });
        $("#race").tabulator("setData", objStats);
      
        $(window).resize(function(){
  $("#tab").tabulator("redraw");
});
`

Hope that helps.  I had to disguise it a little because some information is sensitive

Even after  reinstating virtualdom still no luck with responsive.
Thanks
H

**Comment by hooodephuck** [comment]
align is ineffective too

**Comment by hooodephuck** [comment]
Ok I have built a new test version of the table.
I removed all custom formatters there is no code other than to run the table.
$("#test").tabulator({ virtualdom:true,
 responsiveLayout:true, 
 layout:"fitDataFill"
, movableCols:true,
 movableRows:true, 
 tooltips:true,
 columnMinWidth:28,
 columns:[


when I resize the browser the table just disappears under the edge.
The columns marked with responsive:n  are not hidden
I gave each column a different number so there are many priorities from 0 upwards
nothing helps.
What am I dong wrong?

H

**Comment by olifolkerd** [comment]
hey @hooodephuck 

Is there any chance you could create a JS Fiddle with a working example of your table, that may make it easier to understand what you mean.

I dont understand what you mean by dissapearing table, if you mean that a horizontal scrollbar appears then that is expected behaviour when a table cannot fit all columns in the width of the table.

Cheers

Oli :)
