### ISSUE TITLE
Formatter Doesn't Return Cell Value

### ISSUE THREAD

**Issue by adel314** [olifolkerd/tabulator#1167]
I have written a small cell validation routine that works in turning the cell red (for example if it is over 100) but it either is not returning the original value of the cell or it is being hidden and can't figure out which?

         `for (var i=fieldIndex; i < nMondays+fieldIndex; i++) {
 		var newColumn = new Object;
 		var columns = [];
 		newColumn.title = "Week Commencing "+newDate(startDate, weekCount++);
 		newColumn.align = "center";
 		newColumn.columns = columns;
 		newColumn.columns.push( {title:"Hrs Tasked", field:"assigned_hours"+i});
 		newColumn.columns.push({title:"Hrs Billed",field:"billed_hours"+i});
 		var obj = {};
 		obj.title = "Utilisation";
 		obj.field = "utilisation"+i;
 		obj.formatter = function(cell, formatterParams) { validateUtilisation(cell,formatterParams)};
 		newColumn.columns.push(obj);   
 		//	newColumn.columns.push({title:"Utilisation",field:"utilisation"+i});
		projectTable.tabulatorColumns.push(newColumn);
	   }`
I have changed the colours to both 'red' and 'transparent' and the original value is still being masked.
Here is the validation routine:

        `function validateUtilisation(cell, formatterParams) {
             var cellValue = cell.getValue();
             alert(cellValue);
             if (cellValue > "100") {
               cell.getElement().css({
              "background-color": "red"
                });
              return cellValue;
           } else {
              cell.getElement().css({
              "background-color": "transparent"
              });
            return cellValue;
         }
       }`

**Comment by olifolkerd** [comment]
Hey @adel314 

There is already a validation system in-place in Tabulator, check out the [Validation Documentation](http://tabulator.info/docs/3.5#validation) for more information, it applies a class of ***.tabulator-validation-fail*** to the cell that you can use to style it.

If you want to trigger a change of style outside the validation system, You can only do this inside the **formmater*** function bound to the column definition, any attempts to change it otherwise will likely be overwritten by the vitualDOM. Have a look at the [Formatting Data Documentation](http://tabulator.info/docs/3.5#formatting) it includes an example for using a custom formatter.

In this case it could be something as simple as:

```js
{title:"Utilisation", field:"util", formatter:function(cell, formatterParams){
        //cell - the cell component
        //formatterParams - parameters set for the column

        var value = cell.getValue();

        if(value >100){
            cell.getElement().css("background-color","red"); //highlight cell
        }else{
            cell.getElement().css("background-color",""); //clear highlight
        }
        return value; //set display content of cell to its value
    },
}
```

I hope that helps.

Cheers

Oli :)

**Comment by adel314** [comment]
Thanks Oli, yes that does help.  Thankyou.

**Comment by adel314** [comment]
Sorry to be a pain Oli, but I still think there is something wrong.   The code above does not work for some reason and I think there is something else at play.   Because I create the tables dynamically (ie. columns are data driven) I need to create the columns template on a user click and I have a feeling that this may have something to do with it.   I am guessing.  It is interesting that my original code actually set the background colour but masked the value whereas the code above does nothing, although if I place an alert() in there it does trigger.

**Comment by adel314** [comment]
Okay, an update on making the original code work.   Replace the function declaration with a variable declaration
 `obj.formatter = cellValue`;

and 

       var cellValue = function validateUtilisation(cell, formatterParams) {
        var cellValue = cell.getValue();
        if (cellValue > "100") {
           cell.getElement().css({
            "background-color": "rgba(255, 128, 128, 0.3)" //"#F1948A"
          });
         return cellValue;
        } else {
          cell.getElement().css({
           "background-color": "transparent"
          });
        return cellValue;
       }
    }`
