### ISSUE TITLE
rowheader creation using tabulator 

### ISSUE THREAD

**Issue by snjus** [olifolkerd/tabulator#1174]
is it possible to create rowheader as of now using tabulator? Rowheader should be fixed and shall not scroll when data is scrolled horizontally. it shall be accessible using role like rowheader.

**Comment by olifolkerd** [comment]
Hey @snjus 

The only thing link this at the moment is the group header.

if you were to group by the index of the row then you might be able to acheive the affect you are after.

I hope that helps.

Cheers

Oli :)
