### ISSUE TITLE
How do Validation parameters work?

### ISSUE THREAD

**Issue by SpectralEdge** [olifolkerd/tabulator#1176]
I would like to send 3 parameters with the validation, but can't figure out from the documentation how to use parameters at all.

var noDivideFive = function(cell, value, parameters){
    //cell - the cell component for the edited cell
    //value - the new input value of the cell
    //parameters - the parameters passed in with the validator
    return value % 5; //dont allow values divisible by 5;
}

//in your column definition for the column
{title:"Age", field:"age", editor:"input", validator:noDivideFive}

The code mentions the parameters, but there is no mention anywhere on how to set them or retrieve them.

**Comment by Rodbjartson** [comment]
Agreed! I did not understand how parameters should be passed either!
@olifolkerd

**Comment by olifolkerd** [comment]
Hey @SpectralEdge  & @Rodbjartson 

Sorry for the delay in getting back to you. Apologies, the documentation for the validator params could definitely use improvement. 

when using a validator with the shorthand notation, the parameter is the value after the colon ```:``` in the validator string. for example in the below example the max validator is being called with a parameter that has a value of 5:
```js
{title:"Rating", field:"rating", editor:"input", validator:["max:5"]}
```
Though this wont work for the custom validator function or multiple paramters, in that case you need to use the object notation:
```js
{title:"Rating", field:"rating", editor:"input", validator:{
    type:noDivideFive,
    parameters:{
        name:"steve",
        age:27,
        driver:true,
    },
}}
```

I will look at improving this part of the documentation soon,

I hope that helps.

Cheers

Oli :)

**Comment by Rodbjartson** [comment]
Great!

**Comment by olifolkerd** [comment]
I have updated the documentation on the website to make this clearer.
