### ISSUE TITLE
Internet Explorer Versus Chrome

### ISSUE THREAD

**Issue by mfenton01** [olifolkerd/tabulator#1177]
Is there an incompatibility with Explorer 11. Works great in Chrome

receive the following console errors in IE
![image](https://user-images.githubusercontent.com/2854433/40942384-fbcf32b2-681b-11e8-958e-ccee2453148d.png)

**Comment by olifolkerd** [comment]
Hey @mfenton01 

Tabulator should be fully compatible with IE 11. 

Looking at your console log it looks like you have issues with your version of jQuery that is causing an issue in IE11.

I hope that helps,

Cheers

Oli :)

**Comment by ckieffer** [comment]
@mfenton01, try adding IE compatibility tags as discussed on [Stackoverflow](https://stackoverflow.com/questions/6771258/what-does-meta-http-equiv-x-ua-compatible-content-ie-edge-do). 

```
<!DOCTYPE html> 
<html> 
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
```

**Comment by olifolkerd** [comment]
Hey @mfenton01,

Looking at those errors it looks like something invalid is being passed into Tablulator could you confirm which version of Tabulator you are using and post a copy of your table constructor

Cheers

Oli

**Comment by olifolkerd** [comment]
@ckieffer 

That tag is a compatability tag for Pre IE 11 it dose not apply here im afraid

Those errors suggest that Tabulator is expecting a node to be passed into one of its properties but it is getting something else which either points to something being incorrectly set in the constructor, or if @mfenton01 is using the v4.0 beta, that there may be an issue he has identified.

either way without the constructor object they are using there is little i can offer in the way of help at this point.

Cheers

Oli
