### ISSUE TITLE
Setting the Table Width of a Tabulator Table

### ISSUE THREAD

**Issue by adel314** [olifolkerd/tabulator#1178]
I have scoured the documentation and even though the concept of a "Table Width" is mentioned in the documentation it appears that it can't be set independent of the container.    I am displaying the table within a Bootstrap Tab container which is locking the Table within the Tab setting even though the actual panel is much larger.
Is there an method available to set the width independent of the container?

Thanks

**Comment by adel314** [comment]
It is possible to move into another container and have control over the width

**Comment by olifolkerd** [comment]
Hey @adel314 

You can set the width of the table using CSS.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
@2001617 
```js
.tabulator{
    width:400px;
}
```

**Comment by DenishTechtic** [comment]
Hey oil , i need to customize the tabulator source code in that i have to set maximum width of the cell according the whole table data , how i can do that

**Comment by DenishTechtic** [comment]
i have 1000 data , so maximum width should be set according to data

**Comment by Tohtanbek** [comment]
> i have 1000 data , so maximum width should be set according to data

i'm also looking for how to manage it.

**Comment by javaanne** [comment]
I thought the limit of the tabulator is 1000 columns however my table will only show less than 20 columns and if its exceed it the table will not show anymore

**Comment by olifolkerd** [comment]
There is no limit on columns. But if you use a lot of columns you will need to use the virtual horizontal renderer or the table may take a long time to load
