### ISSUE TITLE
How to differentiate between programmatic row selection and user-side row selection?

### ISSUE THREAD

**Issue by zegkljan** [olifolkerd/tabulator#1180]
When a user clicks a row (provided selectable rows are enabled), the `rowSelected` callback is fired. However, when the row is selected programmaticaly, either via `.tabulator('selectRow')` or `rowComponent.select()`, the callback is fired too. Is there a way to differentiate between these two situations?

**Comment by zegkljan** [comment]
@Rodbjartson See this jsbin: https://jsbin.com/yicasozuki/1/edit?html,output

There is a simple table from the Quick Start, plus 2 additional buttons. The first one selects the first row via `.tabulator("selectRow", 1)`, the other one via `.tabulator("getRow", 1).select()`. The table itself has defined `rowSelected` callback. In both cases (or in all three if I count the actual selection of the row) the callback is fired and I don't know how it came to be. The original question is, when I'm in the callback, how do I know whether the row was selected programmatically or the user actually selected the row? Or is it even possible to determine this?

**Comment by zegkljan** [comment]
@Rodbjartson I see. I was hoping that maybe some information about the event is stored somewhere but not documented in the API. Of course I can work around this with some global variables, I was just hoping I could avoid that. Well, thanks for the answer.

**Comment by Rodbjartson** [comment]
@olifolkerd maybe you know something more?

**Comment by olifolkerd** [comment]
Hey @zegkljan 

@Rodbjartson is correct, The event is fired because a row is selected, Tabulator does not differentiate where that event came from.

That being said, you could use ***rowClick*** event to trigger the row selection, that way you would know where the click event originated.

I hope that helps

Cheers

Oli :)
