### ISSUE TITLE
change callbacks after table is already in use?

### ISSUE THREAD

**Issue by mikexmagic** [olifolkerd/tabulator#1181]
Hi guys,

I have the following situation: Two tables on the same page. One as main and the second as subtable. Both tables are 'build' using the same function and got almost the same options. Also the dataLoaded callback is the same. Both tables receives AJAX data.

When the selection in the main table is changed, a getData is triggered for the subtable.

Now, if the sub table is updated, I like to do additional stuff. How can I realize that?

Can I change the loadData callback after the table is aready initialized?

Thx Mike

**Comment by Rodbjartson** [comment]
Adding if and else ifs? In the callback function?

**Comment by olifolkerd** [comment]
Hey @mikexmagic 

Im afraid that you cannot change the callbacks after the table is loaded, but you could either use some if/else logic in the function as @Rodbjartson suggests or you could make a more detailed table construction function that passes in a different loadData callback to each table.

I hope that helps,

Cheers

Oli :)
