### ISSUE TITLE
Can I get only rows which is not filtered

### ISSUE THREAD

**Issue by falcomavin** [olifolkerd/tabulator#1185]
getRows returns all the rows. Do I have a way to identify rows that are filtered out and not displayed in the table? In fact, I used formatter tick in the last column. I want to use a checbox out of the table to batch modify the value present for that 'formatter tick'. But when some rows of this table are filtered out, it should not be modified in my business logic. If there are other ways to achieve my goal?

**Comment by olifolkerd** [comment]
Hey @falcomavin 

passing a value of ***true*** into the ***getRows*** function, will return only the filtered rows.

```js
var rows = $("#example-table").tabulator("getRows", true); //return currently filtered data
```

if you want the invert of this, you could use the ***getRows*** function to get an array of all rows, then the same function with a argument of ***true*** to get the filtered rows and then compare the arrays, if an item is in one but not the other it has been filtered out.

I hope that helps

Cheers

Oli :)

**Comment by falcomavin** [comment]
Thanks @olifolkerd 
it works! May I ask another question: could getrows get the current page rows as well as not filted ones?

**Comment by olifolkerd** [comment]
Hey @falcomavin 

You cant get the page rows direct from the ***getRows*** function, but you could use it to return all rows then use the ***getPageSize*** and ***getPage*** function to work out the subset of the array that is the current page.

Cheers

Oli :)
