### ISSUE TITLE
Cell edition crashes when pressing enter if validation fails and if html instance is wrapped in a form tag

### ISSUE THREAD

**Issue by lgraziani2712** [olifolkerd/tabulator#1186]
Updated description:

### Scenario

1. Tabulator html instance is wrapped with a `<form>` tag.
2. Edit a cell.
3. Add an invalid value.
4. Press enter.
5. Validation fails (but nothing is printed).
6. Edition stop working.

This doesn't happens with the `tab` key or a click.

### Versions

- jQuery: v3.3.1
- jQueryUI: v1.12.1
- Tabulator: v3.5.2

### Demo

https://codepen.io/lgraziani/pen/dKvVyE?editors=0010

Thank you! Luciano.

**Comment by olifolkerd** [comment]
Hey @lgraziani2712 

Could you post a copy of your table constructor, or build a JS fiddle to show how your table is setup.

Which version of Tabulator are you using?

Cheers

Oli :)

**Comment by lgraziani2712** [comment]
Sure! Here is the configuration: https://codepen.io/lgraziani/pen/dKvVyE?editors=0010

~~I tested it there and everything works. I still don't know why it doesn't work~~

I found the error!!! It happens when tabulator is inside a form tag. The pen is updated with the bug

**Comment by lgraziani2712** [comment]
I tried to fix this by myself, but I failed :(

@olifolkerd, if you can tell me which files/functions I could check, I would try to fix this in no time heh :)
