### ISSUE TITLE
Calculations For Grouped Data Issue Starting Closed

### ISSUE THREAD

**Issue by ubergeekzone** [olifolkerd/tabulator#1187]
having a bit of an issue..

When i have a grouped data `groupStartOpen: false` the calculation column does not show when i open the group.

**Comment by olifolkerd** [comment]
Hey @ubergeekzone 

Calcs on closed groups are hidden by default, you need to use the ***groupClosedShowCalcs*** option to show calcs on closed groups

```js
$("#example-table").tabulator({
    groupClosedShowCalcs:true, //show column calculations when a group is closed
});
```

I hope that helps,

Cheers

Oli :)

**Comment by ubergeekzone** [comment]
the issue is i do not want to show the calcs until the group is open, once the group is closed i'd like to hide them again.

**Comment by olifolkerd** [comment]
could you post a copy of your table constructor object so i can understand how your table is set up?

Cheers

Oli :)

**Comment by ubergeekzone** [comment]
`	$("#shows_schedule-list").tabulator({
		layout: "fitDataFill",
		resizableRows: true,
		placeholder: "Please choose a host and date range to load settle up information",
		//height: "600px",
		paginationSize: data['module'][module]['views']['list']['pageCount'],
		ajaxResponse: function(url, params, response) {
			return helpers.php_crud_api_transform(response)[module];
		},
		groupBy: "locations_id",
		groupHeader: function(value, count, data, group) {
			return data[0].locations[0]['location_name'];
		},
		groupStartOpen: false,
		groupClosedShowCalcs:true,
		columns: [{
				title: "Location",
				field: "locations_id",
				formatterParams: {
					table: "locations",
					index: 0,
					display_as: "location_name"
				},
				formatter: function(cell, params) {
					var data = cell.getData();
					return data[params.table][params.index][params.display_as]
				}
			},
			{
				title: "Date",
				field: "shows_schedule_game_date",
				editor: "input",
				formatter: function(cell, formatterParams) {
					return helpers.convertDate(cell.getValue());
				}
			},
			{
				title: "Time",
				field: "shows_schedule_time",
				editor: "input",
				formatter: function(cell, formatterParams) {
					return helpers.convertTime(cell.getValue());
				}
			},
			{
				title: "Host",
				field: "users_id",
				editor: "select",
				editorParams: usersList,
				formatterParams: {
					table: "users",
					index: 0
				},
				formatter: function(cell, params) {
					var data = cell.getData();
					return data[params.table][params.index]['user_first_name'] + " " + data[params.table][params.index]['user_last_name'];
				}
			},
			{
				title: "Price",
				field: "show_prc",
				editor: "number",
				mutatorParams: {
					display_as: "shows_schedule_attributes"
				},
				mutateType: "data",
				mutator: function(value, data, type, params, component) {
					var json = helpers.isUndefinedJSON(data[params.display_as]);
					if(json) {
						return json.extra.show_prc;
					}
				}
			},
			{
				title: "Received Amount",
				field: "amt_collected",
				editor: "input",
				align: "center",
				mutatorParams: {
					display_as: "shows_schedule_attributes"
				},
				mutateType: "data",
				mutator: function(value, data, type, params, component) {
					var json = helpers.isUndefinedJSON(data[params.display_as]);
					if(json) {
						return json.extra.amt_collected;
					}
				}
			},
			{
				title: "Canceled",
				field: "canceled",
				editor: "select",
				align: "center",
				editorParams: {
					"0": "N",
					"1": "Y"
				},
				formatterParams: {
					display_as: "shows_schedule_attributes"
				},
				formatter: function(cell, params) {
					var data = cell.getData();
					var obj = $.parseJSON(data[params.display_as]);
					if (obj.extra.canceled == 0) {
						return "N";
					} else {
						return "Y";
					}
				}
			},
			{
				title: "Scores",
				field: "scores_in",
				editor: "select",
				align: "center",
				editorParams: {
					"0": "N",
					"1": "Y"
				},
				mutatorParams: {
					display_as: "shows_schedule_attributes"
				},
				mutateType: "data",
				mutator: function(value, data, type, params, component) {
					var json = helpers.isUndefinedJSON(data[params.display_as]);
					if(json) {
						return json.extra.scores_in;
					}
				}
			},
			{
				title: "Teams",
				field: "teams_count",
				align: "center",
				editor: "number",
				mutatorParams: {
					display_as: "shows_schedule_attributes"
				},
				mutateType: "data",
				mutator: function(value, data, type, params, component) {
					var json = helpers.isUndefinedJSON(data[params.display_as]);
					if(json) {
						return json.extra.num_teams;
					}
				}
			},
			{
				title: "People",
				field: "num_players",
				align: "center",
				editor: "number",
				mutatorParams: {
					display_as: "shows_schedule_attributes"
				},
				mutateType: "data",
				mutator: function(value, data, type, params, component) {
					var json = helpers.isUndefinedJSON(data[params.display_as]);
					if(json) {
						return json.extra.num_players;
					}
				}
			},
			{
				title: "Notes",
				field: "shows_schedule_notes",
				editor: "textarea"
			},
			{
				title: "Host Rate",
				field: "host_rate",
				editor: "number",
				mutatorParams: {
					display_as: "shows_schedule_attributes"
				},
				mutateType: "data",
				mutator: function(value, data, type, params, component) {
					var json = helpers.isUndefinedJSON(data[params.display_as]);
					if(json) {
						return json.extra.host_rate;
					}
				}
			},
			{
				title: "Misc",
				field: "misc",
				editor: "input",
				mutatorParams: {
					display_as: "shows_schedule_attributes"
				},
				mutateType: "data",
				mutator: function(value, data, type, params, component) {
					var json = helpers.isUndefinedJSON(data[params.display_as]);
					if(json) {
						return json.extra.misc;
					}
				}
			},
			{
				title: "Total Due",
				field: "amt_due",
				bottomCalc: "sum",
				mutatorParams: {
					display_as: "shows_schedule_attributes"
				},
				mutateType: "data",
				mutator: function(value, data, type, params, component) {
					var json = helpers.isUndefinedJSON(data[params.display_as]);
					if(json) {
						return json.extra.host_due;
					} else {
						return value;
					}
				}
			},
			{
				title: "In",
				field: "in",
				align: "center",
				formatterParams: {
					"table": module,
					display_as: "shows_schedule_attributes"
				},
				formatter: inOut
			},
			{
				title: "Out",
				field: "out",
				align: "center",
				formatterParams: {
					"table": module,
					display_as: "shows_schedule_attributes"
				},
				formatter: inOut
			},
			{
				title: "Approved",
				field: "shows_schedule_status"
			},
			{
				title: "Actions",
				field: "edit",
				formatter: function(cell, formatterParams) {
					return '<button class="btn btn-warning">Edit</button>';
				},
				cellClick: function(e, cell) {
					window.location = '#' + module + '#update#' + cell.getData().id;
				}
			},
		],
		cellEdited: function(cell) {
			var input = {},
				column = cell.getColumn().getField(),
				data = cell.getData(),
				newValue = cell.getValue(),
				id = data.id;
			if (column.indexOf(module) <= -1) {
				var json = $.parseJSON(data[module + "_attributes"]);
				json.extra[column] = newValue;
				data[module + "_attributes"] = JSON.stringify(json);
				delete data[column];
			}
			api.update(api_uri, module, data, id, function(boolean) {
				if ($.isNumeric(boolean)) {
					$.alert("#alert", 5000, "Recorded Updated", "Recorded was updated in the database", true).success();
					$("#shows_schedule-list").tabulator("setData");
				} else {
					$.alert("#alert", 5000, "Recorded Not Updated", "Recorded was not updated in the database", true).danger();
				}
			});

		}
	});`

**Comment by ubergeekzone** [comment]
so, what i want to happen is when the group is closed not to show the calculations , when group is open show the calculations .

**Comment by olifolkerd** [comment]
Hey @ubergeekzone 

When i test with that code, the bottom calc works as expected.

In grouped state the column calculation row will appear at the bottom of the group, if the table is paginated then this can mean that the "bottom" of that group is on a different page, therefor the bottom calc will be shown on whatever page contains the last item in that group.

The only way to have a fixed row that is always at the bottom of the table is to use a ***columnCalcs*** option of ***table*** which will fix the calcs to the top and bottom of the table, but then the calculations will be for the table as a whole rather than individual groups.

Can i as why you are paginating grouped data, generally this would be considered bad UX as it doesn't allow the user to easily navigate a grouped structure. Tabulators Virtual DOM means there is no additional overhead to holding large tables (as long as you define a height on the table) so you could probably load this in a non paginated table without there being to much of a problem.

I hope that helps,

Cheers

Oli :)

**Comment by ubergeekzone** [comment]
@olifolkerd pagination will be removed, this started out as non grouped data. let me play around with it some more.

**Comment by olifolkerd** [comment]
@ubergeekzone 

You could look at filtering the data in the table using a dropdown or buttons to restrict the data that is on display to the user.

Cheers

Oli :)
