### ISSUE TITLE
Tooltip not working

### ISSUE THREAD

**Issue by sarkariajatt** [olifolkerd/tabulator#1188]
Hi
i am trying to enable the tooltip on table but by using the step given in documentation i set the tooltip:true but still not able to make it woking.

It is working in chrome but not in firefox

		$("#entity_tableView").tabulator({
			layout:"fitColumns", //fit columns to width of table (optional)
			pagination:"local", //enable local pagination.
			paginationSize:100, // this option can take any positive integer value (default = 10)
			//paginationElement:$("#pagination-element"), //build pagination controls in this element if want custom pagination 
			columns:[ //Define Table Columns
				{title:"Entity Name", field:"name", width:150,height:19},
				{title:"Description",field:"description"},				
				{title:"Data Fields", field:"fields", align:"left"},
				{title:"Data Filter",field:"filter"},
				{title:"Id", field:"id", visible:false}
			],			
			rowClick:function(e, row){ //trigger an alert message when the row is clicked
				//alert("Row " + row.getData().id + " Clicked!!!!");
			},			
			selectable:true,
			getHtml:true,
			selectable:1,
			tooltips:true
		});

**Comment by Rodbjartson** [comment]
@olifolkerd can you check this out?

**Comment by olifolkerd** [comment]
I will have a look into it this weekend, could i ask how you are passing data into the table, and could you provide one rows woth of sample data?

Cheers

Oli :)

**Comment by sarkariajatt** [comment]
Hi here is the sample data 
[{"name":"Test_entity","description":"testing","fields":["CRD_FIID"],"filter":"OR","id":1}]

**Comment by olifolkerd** [comment]
Hey @sarkariajatt 

Trying with your exact code that is working just fine, when i hover my mouse over a cell the tooltip appears as normal,

What are you experiencing/expecting?

Which browser are you using?

Cheers

Oli :)
