### ISSUE TITLE
Providing Text for BottomCalc Row

### ISSUE THREAD

**Issue by adel314** [olifolkerd/tabulator#1189]
Can someone help with this request please.

I have a set of columns that display **hours**, and **percentage complete**,  per week for example.   When I sum the columns I multiply the **hours** by a rate to get a dollar value.   Now because the **bottomCalc** now has a different dimension to the column headings I would like to add some text on the bottom row left hand cell to indicate what the summed values are.   For example **Total Revenue**.

I suppose the question that I am asking is how do you access the methods and properties of the bottomCalc row?   I can't seem to figure out how to do this from the doco;  does anyone have an insight on how to approach it?

**Comment by olifolkerd** [comment]
Hey @adel314 

You cannot directly access the data in the calculation row, but you can apply a formatter to the calculation output using the ***bottomCalcFormatter*** column definition option, which and take any of the standard formatters or you can build a custom one to add the text you want.

```js
{title:"Rating", field:"rating", bottomCalc:"avg",  bottomCalcFormatter:"star",  bottomCalcFormatterParams:{stars:5}}
```
I hope that helps,

Cheers

Oli :)

**Comment by adel314** [comment]
Thanks Oli - yes that gave me the idea of just using the bottomCalc function of the frozen column to return the text I need from a function.  

Thanks again !
