### ISSUE TITLE
movableCols and getData

### ISSUE THREAD

**Issue by cokechan** [olifolkerd/tabulator#119]
Hi Oli,

Thank you for your previous fix on movableCols with sortable. I met with another issue  when i try to use movableCols with getData. The retrieved data does not seem to follow the order of the moved columns.. Adding "true" to getData has no effect.. As example, I forked the codepen  [https://codepen.io/anon/pen/aBYXgj](https://codepen.io/anon/pen/aBYXgj) , where i try to move the Name column after Favourite Color but could not obtain the same column order for data.

Is there a direct way to obtain the data is that is the same column order as the moved columns ? 

Appreciate your advice
coke c.

**Comment by olifolkerd** [comment]
The ***getData*** function returns an array of objects.

The properties of an object will always be displayed in alphabetical order, that is just how JavaScript handles objects.

What you can do is use the ***getColumns*** function to get information about the current order of the columns:
```js
var colDefs = $("#example-table").tabulator("getColumns")
```
And then use that to format your data appropriatly

**Comment by cokechan** [comment]
Thanks, Oli, for your advice!
