### ISSUE TITLE
Row click function

### ISSUE THREAD

**Issue by hyperion0x** [olifolkerd/tabulator#1190]
Hi, 

i have two tabulator tables and i would like to see the selected rows (one or many) into the second table when i click on them on the first table.
the first table show rows with 10 columns. I'm tryng to get the result with the following code but when i click but i have this error:

![error1](https://user-images.githubusercontent.com/39456618/40888495-3766e168-6758-11e8-833c-b3f053704211.PNG)

```js
rowClick:function(e, id, data, row)
	{ 
		//load data	
		var idbo=row.getData().IDBO;
		
		$("#mytable2").tabulator("setData", [{IDBO:row.getData().IDBO,}]); //make ajax request with advanced config options
	},
```

IDBO is one of the 10 columns composing a selected row in the first table. 
1. Is it the sintax correct?
2.Am i obliged to specify all 10 columns that normally compose the first selected row?

thanks a lot,

**Comment by olifolkerd** [comment]
Hey @hyperion0x 

Thanks for getting in touch.

You appear to have too many arguments in your row click callback, it only passes in the ***e*** and ***row*** objects:

```js
$("#example-table").tabulator({
        rowClick:function(e, row){
        //e - the click event object
        //row - row component
    },
});
```

If you change to having those two values it should work.

Could i ask where you found the documentation that included the 4 arguments? if it is on the Tabulator site i will get that updated straight away.

Cheers

Oli :)

**Comment by hyperion0x** [comment]
Hi Oli,

thanks for your answer.
Now it works fine but i have two only doubts now:
1) how can i make appear in the second table two selected rows? or many rows that have been selected in the first rows?
2) i would like to take the ID of these selected rows (in second table) and use them in another php page to do some logic, how can i export these IDs coming from the selected rows?

thanks a lot as always for your support :)

**Comment by olifolkerd** [comment]
Hey @hyperion0x 

You can call the ***selectRow*** function and pass in an array of rows:
```js
$("#example-table").tabulator("selectRow", [1, 5, 7, 9]);
```

You could use the ***getSelectedData*** function which returns an array of the selected row data, you could then iterate through this data and build an array of the ID's

```js
var selectedData = $("#example-table").tabulator("getSelectedData"); 
```

I hope that helps,

Cheers

Oli :)
