### ISSUE TITLE
Setting editable just specific cells

### ISSUE THREAD

**Issue by kreamas** [olifolkerd/tabulator#1191]
Hi.

I'm wondering if it's possible to set editable just a few range of cells or just specific cells instead of the whole column (field).

Thanks in advance

**Comment by olifolkerd** [comment]
Hey @kreamas 

You can do this using the ***editable*** callback in a column definition:

```js
var editCheck = function(cell){
    //cell - the cell component for the editable cell

    //get row data
    var data = cell.getRow().getData();

    return data.age > 18; // only allow the name cell to be edited if the age is over 18
}

//in your column definition for the column
{title:"Name", field:"name", editor:"input", editable:editCheck}
```

Let me know if that helps,

Cheers

Oli :)
