### ISSUE TITLE
redirect pdf to email instaed of download

### ISSUE THREAD

**Issue by ryhill** [olifolkerd/tabulator#1192]
Hi Oli,

I have a requirement to email a pdf report at regular intervals [Schedule].  I am trying to use tabulator to generate the pdf. Is it possible to change the output to email instead of download

Thanks in advance

KIRAN

**Comment by olifolkerd** [comment]
Hey @ryhill 

To do this you would need to send the data to a mail server somewhere, you cannot trigger an email direct from the browser. assuming that you have a mail server setup, you can intercept the output from the download function in blob format using the ***downloadReady*** callback, you could then include this in your request to a mail server:

```js
$("#example-table").tabulator({
    downloadReady:function(fileContents, blob){
        //fileContents - the unencoded contents of the file
        //blob - the blob object for the download

        //custom action to send blob to server could be included here

        return blob; //must return a blob to proceed with the download, return false to abort download
    }
});
```

I hope that helps.

Cheers

Oli :)

**Comment by ryhill** [comment]
I tried this way.

$("#reports_table").tabulator({
downloadReady:function(fileContents, blob){
   var dataString = "imageData=" + blob + "&emails=" + email_to + "&subject=" + report_title;
     $.ajax({
      type: "POST",
      url: "export.php",
      data: dataString,
      success: function() {
       
        }
      });
 return false;
		    }
		});


and in export.php, i am taking the blob.

Is it right way??

**Comment by olifolkerd** [comment]
Hey @ryhill 

You almost have it, to pass different paramters in the post request you want to pass an object to the data option on the ajax request:

```js
var dataObj = {
    imageData:blob,
    emails:email_to ,
    subject:report_title
}

$.ajax({
     type: "POST",
     url: "export.php",
     data: dataObj ,
     success: function() {
      
    }       
});
```

I hope that helps,

Cheers

Oli :)

**Comment by ryhill** [comment]
Thanks Oli. Great direction..I missed to ask this simple question..

How to make a call to this function and assuming blob is the result_data

Thanks

KIRAN

**Comment by ryhill** [comment]
I am getting this error

**_Options Error - Tabulator does not allow options to be set after initialization unless there is a function defined for that purpose_**

**Comment by olifolkerd** [comment]
Hey @ryhill 

You cannot change the setup object once tabulator has been created, which is why you are getting that error.

You need to include the ***downloadReady*** callback in the original table definition object, where you set the columns ect.

Cheers

Oli :)

**Comment by ryhill** [comment]
Has anyone tried to save the blob as .xlsx file on server using PHP. I can't save the blob.
I am able to post the blob to php file, but cannot work on it.
Hi Oli, can you help here please

Thanks in advance

**Comment by olifolkerd** [comment]
Hey @ryhill 

Have a look at this:

https://stackoverflow.com/questions/36044064/saving-blob-object-as-a-file-on-server

Cheers

Oli :)

**Comment by ryhill** [comment]
Its sorted Oli.

Thanks for the direction

Cheers

KIRAN
