### ISSUE TITLE
Pagination placeholder display issue

### ISSUE THREAD

**Issue by mateddy** [olifolkerd/tabulator#1196]
When I use ajaxfilter on remote pagination and there is no result using the filter, the "No result found" message is shown in a vertical scrollbar, as opposed to that without pagintion/filtering.
![image](https://user-images.githubusercontent.com/2744288/41323854-b09c6cdc-6ee3-11e8-9385-87b5edb7a8b6.png)

It seems that a workaround is to manually style the placeholder property.

Tabulator constructor shown below:

`table.tabulator({
    layout: 'fitColumns',
    columns: columns,
    placeholder: "No result found",
    // placeholder: $("<p style='text-align: center; font-weight: 700; font-size: 20px;'>No result found</p>"),
    pagination: 'remote', paginationSize: 10,
    ajaxURL: url, ajaxParams: { action: 'select' }, ajaxFiltering: true,
  });`

**Comment by olifolkerd** [comment]
Hey @mateddy 

Thanks for getting in touch,

There is definitely an issue there to be sorted,

While your approach does work on tables that have no height set, it will not vertically align correctly on tables that use the Virtual DOM.

At the moment, it seems that the inbuilt system works with the virtual DOM but not on paginated tables like yours.

I have pushed a fix to the master branch for this and will include it in this evenings update.

Cheers

Oli :)
