### ISSUE TITLE
Load both columns and data from json files

### ISSUE THREAD

**Issue by stevenguyen102** [olifolkerd/tabulator#1197]
Hi Oliver,

I'm trying to build a simple html file with tabulator in local directory.
I've known the command to load .json file for data table. Something like that:
    $("#example-table").tabulator("setData", "./table.json");

Could you please give me the command to load "columns" info from .json file.

Thanks,
Steve

**Comment by olifolkerd** [comment]
Hey Steve,

You can call me Oli :)

You can set the columns using the ***setColumns*** function, but you will have to do an ajax loading and json parsing yourself as this function only accepts an array of column definition objects.

I hope that helps

Cheers

Oli :)
