### ISSUE TITLE
Unable to load tabulator in OpenMCT project

### ISSUE THREAD

**Issue by pr331570** [olifolkerd/tabulator#1198]
Hi Team,

I am unable to load the tabulator into the openMCT project.

I followed https://github.com/nasa/openmct/blob/master/docs/src/tutorials/index.md to create a plug-in in OpenMCT.

here is the code for the tabulator for the plug-in.

https://github.com/nasa/openmct/issues/2059

**Comment by olifolkerd** [comment]
Hey @pr331570 

Sorry for the delayed response.

Im not an OpenMCT developer myself, but looking at the docs for the framework it uses a virtualized DOM, so you will have to call the constructor function after your table has been added to the DOM.

there is usually a callback that is triggered when the dom has been constructed.

I hope that helps,

Cheers

Oli :)
