### ISSUE TITLE
How does one edit table data programmatically?

### ISSUE THREAD

**Issue by Pinaz9** [olifolkerd/tabulator#1199]
In the documentation, under the header `Row Index`, it is mentioned that one should set the row index, as it is important for programmatically altering table data. However, how to do so is omitted throughout the rest of the documentation.

I need to be able to edit the value of a specific cell whenever I want. It doesn't necessarily need to edit the underlying data, however, what is displayed does need to change. How can I accomplish this?

**Comment by olifolkerd** [comment]
hey @Pinaz9 

the index of a row is just its ***id*** field by default, or if you want to use a custom field, whatever you set the ***index*** option to in the table constructor:
```js
$("#example-table").tabulator({
    index:"age", //set the index field to the "age" field.
});
```

In terms of editing a cell there are numerous ways to to it depending on your usage case, you could pass updated data to the ***updateRow*** function or to a [Row Components](http://tabulator.info/docs/3.5#row-component) ***update*** function or you could call the ***setValue*** function on a [Cell Component](http://tabulator.info/docs/3.5#cell-component)

If you can be more specific about how/why you need to update the cell i can give you a more specific example.

I hope that helps.

Cheers

Oli :)

**Comment by Pinaz9** [comment]
I ended up doing some more digging and finding `Row.getCell(column)` and `Cell.setData()`. Between the two, I was able to accomplish my goal. However, these pieces of documentation were difficult to find. 

Your current docs seem to consist of a single page that explains the common ways to do things, but the documentation on the methods that various components offer is unlinked on the page. I eventually found them with the aid of Google, however, perhaps a more explicit mention of them is in order.

**Comment by olifolkerd** [comment]
Hey @Pinaz9 

Thanks for the feedback, i am looking to overhaul the docs in the next couple of months and will do a full API spec at that point.

What i would say is that of all the documentation, the Component Objects are the one bit of the documentation that have a full listing of ever function available on them in a list :)

Cheers

Oli :)
