### ISSUE TITLE
Adding Tooltip to show truncated cell data

### ISSUE THREAD

**Issue by vshankaa** [olifolkerd/tabulator#12]
If the content of the cell exceeds the cell width then only partial data is shown. How can we show the full cell data, may be on hover via a tooltip?

**Comment by olifolkerd** [comment]
Nice idea, i will add a tooltip parameter to the column definitions this evening

**Comment by vshankaa** [comment]
Thanks!

**Comment by olifolkerd** [comment]
Tooltips have been added to version 1.9.0. They can either be set globally using the ***tooltips*** options parameter:
```js
$("#example-table").tabulator({
	tooltips:true,
});
```
Or on a per column basis in the column definition array:
```js
//column definition in the columns array
{formatter:printIcon, width:40, align:"center", tooltip:true},

```

The tooltip parameter can take three different types of value
- **boolean** - a value of ***false*** disables the tooltip, a value of ***true*** sets the tooltip of the cell to its value
- **string** - a string that will be displayed for all cells in the matching column/table.
- **function** - a callback function that returns the string for the cell. see below:

See [Formatting Data](https://github.com/olifolkerd/tabulator/wiki/Formatting-Data#tooltips) for full details.

**Comment by vshankaa** [comment]
Thank you very much! It's working great! :+1:

**Comment by texperts** [comment]
Its very nice but if we option to style, then it would be more comfortable.

**Comment by olifolkerd** [comment]
They are built in browser tool tips. There is no styling option for this.

If you want a more.custom experience with tooltips then I would suggest using a custom formatter function and use one of the many high quality tooltip libraries that are out there.

Cheers

Oli 🙂
