### ISSUE TITLE
Why there is no built in rows numbering?

### ISSUE THREAD

**Issue by aswzen** [olifolkerd/tabulator#120]
I think it's a great idea if Tabulator have their own rows numbering (ex: 1,2,3,4 that appears in left side of table), like other jquery datatable.

Best Regards
Git

**Comment by olifolkerd** [comment]
Are you looking for auto numbering purely for display or that is shown in the data as well?

At the moment there is no auto increment index because that would cause issues for people using the table to create data that is then stored in a database where the index would be created at that point, not in the table.

If you just want one from a purely visual perspective then this is really easy to do with a custom formatter:
```js

//automatic number generating formatter
var autoNumFormatter = function(){
	return $("#example-table .tabulator-row").length + 1;
};

//build table
$("#example-table").tabulator({
    columns:[
        {formatter:autoNumFormatter, width:40}, //incrementing row number
        {title:"Name", field:"name"},
    ]
});
```

**Comment by aswzen** [comment]
thank you, its working as well.
but we all know when there are many columns on the table and we try to scroll to right side the row number will disappear (not frozen).

**Comment by olifolkerd** [comment]
Frozen rows and columns are on the development roadmap, but they wont be about for a few months i am afarid

**Comment by olifolkerd** [comment]
As this has resolved the initial question i am going to close it, if you wish to track the progress of column/row freezing please raise it as a sepereate issue so others can find it more easily.

Cheers

Oli

**Comment by mikefarrel7** [comment]
Hi Olifolkerd,

How about numbering with pagination table, I use the syntax numbering 
//automatic number generating formatter
var autoNumFormatter = function(){
	return $("#example-table .tabulator-row").length + 1;
};

//build table
$("#example-table").tabulator({
    columns:[
        {formatter:autoNumFormatter, width:40}, //incrementing row number
        {title:"Name", field:"name"},
    ]
});
but when these codes are using with paging tables, the numbering is not recursive in the next paging??. please help me for this. Thank You Olifolkerd.

**Comment by olifolkerd** [comment]
Hey,

You can use the ***getPage*** function to determine the current page and work out the maths from that, you will need to know the page size you are using so i suggest you put that in a variable somewhere as well:

```js

var pageSize = 10;

//automatic number generating formatter
var autoNumFormatter = function(){
    var page = $("#example-table").tabulator("getPage")
    var rowNo = $("#example-table .tabulator-row").length + 1;

    return (pageSize * (page-1)) + rowNo;
};

//build table
$("#example-table").tabulator({
    paginationSize:pageSize,, 
    columns:[
        {formatter:autoNumFormatter, width:40}, //incrementing row number
        {title:"Name", field:"name"},
    ]
});
```


Additionally you might be interested to know you can now freeze columns in Tabulator:
```js
$("#example-table").tabulator({
    paginationSize:pageSize,, 
    columns:[
        {formatter:autoNumFormatter, width:40, frozen:true}, //incrementing row number
        {title:"Name", field:"name"},
    ]
});
```
Full information on this feature can be found [here](http://olifolkerd.github.io/tabulator/docs/#frozen-col)

Let me know if that all works out for you

Cheers

Oli

**Comment by mikefarrel7** [comment]
Thank you Oli, I really want to Thank you. It's works nice. :)

**Comment by olifolkerd** [comment]
Hey Mike,

Glad to hear it all worked out. let me know if you have any other issues.

Cheers

Oli

**Comment by mikefarrel7** [comment]
Hi Oli,

Yeah, thank you, I really happy with your table pluggins :), btw thank you
for your kindness to share your pluggins, btw I acctually want to ask about
another issues, not about the table, but about web security, do you know
about that? because I don't know to much about web security but now I built
them. I just worries for the future if my web had a problem. :(, I want to
ask about security just like htaccess, index.php how to secure them?, but
if you don't know about them, no problem. :).

regards
Mike

**Comment by olifolkerd** [comment]
Hey Mike,

Web security is a complex subject with many different aspects to cover. it is ofetn a good idea to use frameworks such as Laravel, in your backend PHP as they take car of a lot of issues for you.

here is a link to an interactive site that will give you a rough guide to some of the key concerns with web secuirty:
http://edu.williamdurand.fr/web-security-101-slides/#/2/1

if you are after a more technical run through the the Open Web App Security Project (OWASP) is a great place to learn more. a list of the most serious common vulnerabilities can be found here: https://www.owasp.org/index.php/OWASP_Top_Ten_Cheat_Sheet

I hope that starts you off in the right direction.

Cheers

Oli

**Comment by mikefarrel7** [comment]
Ok Oli,

Thank you again oli, btw now I want to ask about the table plugin again,
how to make "colspan" and "rowspan" in your table plugins?

thank you in advance.

regards
Mike

**Comment by olifolkerd** [comment]
Hi Mike,

There are currently no inbuilt ways to handle rowspan or colspan in Tabulator.

That being said, you can use ***Column Groups*** and ***rowFormatters*** to create a wide array of scenarios.

If you have a specific scenario in mind, could you create a separate issue (one issue per question please). with a description of what you are trying to achieve and ideally a diagram of the cell/row/column layout you are hoping for.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey,

Version 2.11 of tabulator now has the ***rownum*** formatter that provides incrementing row numbers:
```js
$("#example-table").tabulator({
    columns:[
        {formatter:"rownum"}, //add auto incrementing row number
        {title:"Name", field:"name"},
    ],
});
```

An example of it in action can be found [here](http://olifolkerd.github.io/tabulator/examples/#formatters)

Cheers

Oli

**Comment by timothymarois** [comment]
I was using this for row numbers and then came across this, didn't know there was a built-in version.  But now that I know. I'll switch over to `rownum` not sure if there are any performance improvements. 

```js
var autoNumFormatter = function(cell){
        var row = cell.getRow()
        var rowIndex = row.getPosition(false);
        return (rowIndex+1);
 };
```

**Comment by dua-tanjung** [comment]
> I built this for using this for row numbers and then just came across this thread, didn't know there was a built-in version. But now that I know. I'll switch over to `rownum` not sure if there are any performance improvements.
> 
> ```js
> var autoNumFormatter = function(cell){
>         var row = cell.getRow()
>         var rowIndex = row.getPosition(false);
>         return (rowIndex+1);
>  };
> ```

If you use remote pagination with built-in row numbering, the counter will always start at 1 on every pages. 

I'm using your solution, modify it a little to count starting row number.

Thanks.

**Comment by KilledDebtor** [comment]
I'm think better if it will be an autoincrement value.

For example, if u create 3 rows and remove first, next row that u create is 3.
![изображение](https://user-images.githubusercontent.com/56230793/77134875-0b845e00-6a7a-11ea-954c-2e6fcb2f4ceb.png)

**Comment by ismael-elatifi** [comment]
> ```js
> width:40
> ```

I would rather use :  
```
function autoNumFormatter(cell){
	return cell.getRow().getPosition()+1
}
```

**Comment by ismael-elatifi** [comment]
> ```js
> var autoNumFormatter = function(){
> 	return $("#example-table .tabulator-row").length + 1;
> };
> ```

I would rather use :  
```javascript
function autoNumFormatter(cell){
	return cell.getRow().getPosition()+1
}
```

**Comment by olifolkerd** [comment]
Hey @ismael-elatifi 

This is a very old issue, there is now the `rownum` formatter to do this for you.

Cheers

Oli :)
