### ISSUE TITLE
Stuttering frozen columns with horizontal scrolling (chrome).

### ISSUE THREAD

**Issue by icaromelog** [olifolkerd/tabulator#1200]
Hi!

I have multiple tables, some of then have great number of data. the first columns are frozen, when i scrolling horizontally, the columns stutters. I suspect its a delay with the function that recalculates left position of the columns, to make columns stay fixed on horizontal scrolling. that issue only occurs when i have multiple columns, in chrome specifically.

Any ideas how i can solve this little annoying problem?

Thanks!

**Comment by olifolkerd** [comment]
Hey @icaromelog 

could you post a copy of your table constructor so we can see how your table is setup.

Cheers

Oli :)

**Comment by icaromelog** [comment]
Sure.

$("#" + idTabela).tabulator({
            height: 380,
            layout: "fitColumns",
            movableColumns: true,
            columns: colunas[idTabela],
            data: data[idTabela],
            dataLoaded:function(data){
            },
            cellClick:function(e, cell){
              let idClicado = cell.cell.table.element[0].id;
              // console.time('regerarTabela');
              var columnLayout = $('#'+idClicado).tabulator("getColumnLayout");
              var i = 0;
              colunas[idClicado].forEach((k) => {
                if (k.field == columnLayout[i].field) {
                  k.visible = true;
                }
                i++;
              });
              regerarTabela(e, cell, data[idClicado], colunas[idClicado], idClicado);
              // console.timeEnd('regerarTabela');
            },
         });

**Comment by olifolkerd** [comment]
Hey @icaromelog 

Could you show your columns array, that is key to understanding how the table is setup to work, especially if you are using frozen columns.

Even better would be a JS Fiddle of a working table.

Cheers

Oli :)

**Comment by icaromelog** [comment]
Hi Oli! Thanks for the replys.

Actually i'm using a JSON to build the tables.

Here's a example of my columns:

```
columns: [
{
title: "Lorem Ipsum 1",
field: "lorem-1",
headerSort: false,
minWidth: 80,
headerClick: "",
frozen: true,
visible: true
},
{
title: "Lorem Ipsum 2",
field: "lorem-2",
headerSort: false,
minWidth: 80,
headerClick: "",
frozen: true,
visible: true
},
{
title: "Lorem Ipsum 3",
field: "lorem-3",
headerSort: false,
minWidth: 80,
headerClick: "",
align: "center",
frozen: false,
visible: false
},
]
```

**Comment by olifolkerd** [comment]
Hey @icaromelog 

Is that all your columns? in order to get to the bottom of what is happening to your table i have to be able to replicate it exactly otherwise i wont be able to help

If you dont feel comfortable posting the exact code, thats fine. If that is the case, could you share a JS Fiddle that replicates the issue.

Cheers

Oli :)

**Comment by icaromelog** [comment]
Hi Oli! 

Your own example of frozen columns, replicates exactly what is happening in my tables.

http://tabulator.info/examples/3.5?#frozen-col

Open in google chrome, simulate mobile resolution, then scroll the table, you will see the stuttering happening on frozen columns.

I Think its better you analyse your proper example, than my JSFiddle.

Much thanks for support <3

Cheers!

**Comment by olifolkerd** [comment]
Hey All,

To make it easier to notify everyone of progress with the rendering system i have created one issue #1437 where i will report progress.

Cheers

Oli :)
