### ISSUE TITLE
Possible Error in Bootstrap 4 Theme

### ISSUE THREAD

**Issue by Pinaz9** [olifolkerd/tabulator#1201]
https://github.com/olifolkerd/tabulator/blob/master/src/scss/bootstrap/tabulator_bootstrap4.scss#L388

My IDE does not like the fact that the argument is in quotes. Based on my research, it looks like an error.

**Comment by olifolkerd** [comment]
Hey @Pinaz9 

good spot! that is a hangover from the days when Tabulator used to be styled with LESS,

it should still render in browsers correctly as any decent sass compiler will still convert it into CSS, but i will make sure it is fixed for the next patch release.

Cheers

Oli

**Comment by olifolkerd** [comment]
This actually affected every style sheet.

I have just pushed a fix to the master branch for this and will include it in this evenings patch release.

Thanks for letting me know.

Cheers

Oli :)
