### ISSUE TITLE
[Documentation] Ajax Sorting and getSort

### ISSUE THREAD

**Issue by mateddy** [olifolkerd/tabulator#1203]
In documentation,
The array of sorter objects will take the same form as those returned from the getSort function:
[
    {column:"age", dir:"asc"},
    {column:"height", dir:"desc"}
]

However, it seems to be 'field' instead of 'column' as reported from my testing.

**Comment by olifolkerd** [comment]
Hey @mateddy 

Appologies for the mixup there, the text description was correct there are actually three properties, but the example code was outdated.

The ***getSort*** function will return an array of sort objects with three properties, column the column component for the sorted column, field a string of the field name for the sorted column, and dir a string of either "asc" or "desc" indicating the direction of sort.

```js
[
    {
        column:column, 
        field:"age", 
        dir:"asc"
    },
    {
        column:column, 
        field:"height"
        dir:"desc"
    }
]
```

I have updated the documentation on the website.

Thanks for getting in touch,

Oli :)
