### ISSUE TITLE
Selectable Rows highlight vs true

### ISSUE THREAD

**Issue by cemmons** [olifolkerd/tabulator#1207]
Hi Oli,

I'm working on a custom checkbox and found a problem with the selectable rows option. I'll show you the images:

Using selectable: "highlight"

Config:

```
 function CreateAppsTable() {

            var selectIcon = function (cell, formatterParams) { //plain text value
                var data = cell.getData();

                if (data.selected == true)
                    return "<i class='material-icons'>check_box</i>";
                else
                    return "<i class='material-icons'>check_box_outline_blank</i>";
            };

            var selectClick = function (e, cell) {
                var cellValue = cell.getValue();
                var row = cell.getRow();
                cell.setValue(!cellValue);
                row.toggleSelect();
            }


            $('#apps-table').tabulator({
                layout: "fitColumns",
                height: 300,
                index: "AppID",
                ajaxURL: "<%= ResolveUrl("users-wizard.aspx/GetApps") %>", //ajax URL
                ajaxConfig: ajaxConfig, //ajax HTTP request type
                ajaxResponse: function (url, params, response) {
                    var data = JSON.parse(response.d);

                    return JSON.parse(data.Result); //return the tableData peroperty of a response json object
                },
                ajaxLoaderLoading: $('#apps-spinner').html(),
                responsiveLayout: true,
                selectable: "highlight",
                columns: [
                    {
                        title: "", field: "selected", width: 30, formatter: selectIcon, cellClick: selectClick
                    },
                    {
                        title: "APPS", field: "AppID", widthGrow: 1, formatter: function (cell, formatterParams) {
                            var data = cell.getRow().getData();
                            return "<div class='d-flex'><p>" + data.AppName + " " + data.AppVersion + "</p></div>";
                        }
                    }
                ],

            });
        }
```

Behavior

![file1](https://user-images.githubusercontent.com/5125512/41598898-9cfb4368-739f-11e8-824e-a43c869711c2.gif)

Using selectable: true
```

 function CreateAppsTable() {

            var selectIcon = function (cell, formatterParams) { //plain text value
                var data = cell.getData();

                if (data.selected == true)
                    return "<i class='material-icons'>check_box</i>";
                else
                    return "<i class='material-icons'>check_box_outline_blank</i>";
            };

            var selectClick = function (e, cell) {
                var cellValue = cell.getValue();
                var row = cell.getRow();
                cell.setValue(!cellValue);
                row.toggleSelect();
            }


            $('#apps-table').tabulator({
                layout: "fitColumns",
                height: 300,
                index: "AppID",
                ajaxURL: "<%= ResolveUrl("users-wizard.aspx/GetApps") %>", //ajax URL
                ajaxConfig: ajaxConfig, //ajax HTTP request type
                ajaxResponse: function (url, params, response) {
                    var data = JSON.parse(response.d);

                    return JSON.parse(data.Result); //return the tableData peroperty of a response json object
                },
                ajaxLoaderLoading: $('#apps-spinner').html(),
                responsiveLayout: true,
                selectable: true,
                columns: [
                    {
                        title: "", field: "selected", width: 30, formatter: selectIcon, cellClick: selectClick
                    },
                    {
                        title: "APPS", field: "AppID", widthGrow: 1, formatter: function (cell, formatterParams) {
                            var data = cell.getRow().getData();
                            return "<div class='d-flex'><p>" + data.AppName + " " + data.AppVersion + "</p></div>";
                        }
                    }
                ],

            });
        }
```

Behavior

![file2](https://user-images.githubusercontent.com/5125512/41598945-b96ba72c-739f-11e8-82d2-be73ba6478ca.gif)

Am i doing something wrong here?

**Comment by Nyut0n** [comment]
What result did you expect?
selectable:true makes the row selectable when you click on it. If you implement a custom checkbox in a row that calls toggleSelect on the row, it will deselect the row right after your click on the row has selected it.

**Comment by cemmons** [comment]
Is there a way to make row selectable without having the row highlighted?

**Comment by Nyut0n** [comment]
I don't know of any way to do this in Javascript. Maybe Oli does. 
Only way I could think of is deleting the **.tabulator-row.tabulator-selectable:hover** selector from the CSS.

**Comment by olifolkerd** [comment]
Hey @cemmons 

In this scenario @Nyut0n is right, you are selecting then immediately deselecting the row.

There are two solutions to this, the first is to not enable row selection, in this scenario you can still force the selection using the ***toggleSelection*** function.

The other option is to keep row selection enabled and to bind to the click event on your checkbox and use an `e.stopPropagation()` to stop the click event bubbling up to the row and triggering the selection.

In terms of preventing the row highlighting, @Nyut0n was almost there, you can override the default styling in your own stylesheet as long as you include it after the tabulator.css:

```js
.tabulator-row.tabulator-selectable:hover {
  background-color: inherit;
  cursor: auto;
}
```

I hope that helps,

Cheers

Oli :)

**Comment by cemmons** [comment]
Oh, I didn't know I could use the selection with the selectable:false. Thanks a lot. 

And thanks @Nyut0n too.

**Comment by Nyut0n** [comment]
Hey @olifolkerd,
> not enable row selection, in this scenario you can still force the selection using the toggleSelection function.

I'm curious, what do you mean by "not enable" it? If the selectable option is set to false in the constructor, you cannot select rows programmatically. I tried :(

**Comment by olifolkerd** [comment]
Hey @Nyut0n 

You definitely can from the row component i do it on several of my projects.

Cheers

Oli :)

**Comment by Nyut0n** [comment]
@olifolkerd it would be really useful for one of my projects, cause right now I'm using a complicated workaround to achive this.
Take a look: http://jsfiddle.net/bgfaz1nr/
Changing selectable:false to true makes the button work.
