### ISSUE TITLE
Responsive Layout with nested tables problem

### ISSUE THREAD

**Issue by mrslayer01** [olifolkerd/tabulator#1208]
I'm having an issue when using a responsive layout with a nested table, inside another nested table. When i resize the page it distorts the table, and the headers even disappear.

I have tried to replicate it using the example, and i could not, the only difference i see is that i'm using an ajax call to populate my table, but when i pass the data manually it works fine.

Any ideas?

![image](https://user-images.githubusercontent.com/13773643/41609890-cdf8fe78-73b9-11e8-9297-1e0b185aff5d.png)

**Comment by olifolkerd** [comment]
Hey @mrslayer01 

That will likely be because you need to call the ***redraw*** function on top level table when the page is resized to redraw the elements it contains.

That is quite a complicated setup you have there, it will be fairly difficult to give you an exact solution without an example. Any chance you could put together a JS Fiddle that shows the issue?

Also what browser are you using?

Cheers

Oli :)

**Comment by mrslayer01** [comment]
Not quite sure about JSFiddle sine i use Ajax Calls to populate my data, but hopefully this will give you a good look at my table.

`

    $("#TestTable").tabulator({
        resizableColumns: false,
        groupToggleElement: "header",
        highlight: false,
        selectable: false,
        layout: "fitDataFill",
        groupBy: "GroupId",
        groupHeader: [
            function (value, count, data) {
                return "<span style='color:#375d9d;'>" + value + "</span>";
            }
        ],
        groupStartOpen: false,
            rowFormatter: function (row) {
                var holderEl = $("<div></div>");
                var tableEl = $("<div></div>");

                holderEl.append(tableEl);

                row.getElement().append(tableEl);

                tableEl.tabulator({
                    layout: "fitDataFill",
                    groupToggleElement: "header",
                    resizableColumns: false,
                    selectable: false,
                    data: row.getData().GroupId,
                    groupBy: "GroupId",
                    groupHeader: [
                        function (value, count, data) {
                            return "<span style='color:#375d9d; padding-left:30px;'>" + value + "</span>";
                        }
                    ],
                    groupStartOpen: false,
                    rowFormatter: function (row) {
                    var holderEl = $("<div></div>");
                    var tableEl = $("<div></div>");

                    holderEl.append(tableEl);

                    row.getElement().append(tableEl);

                    tableEl.tabulator({
                        layout: "fitDataFill",
                        selectable: false,
                        placeholder: "No Data Available",
                        responsiveLayout: "collapse",
                        columns: [
                            { formatter: "responsiveCollapse", width: 30, minWidth: 30, align: "center", resizable: false, headerSort: false },
                            { title: "Value 1", field: "Value1Data", align: "center", sorter: "string" },
                            { title: "Value 2", field: "Value2Data", align: "center", sorter: "alphanum" },
                            { title: "Value 3", field: "Value3Data", align: "center", sorter: "alphanum", responsive: 0 },
                            { title: "Value 4", field: "Value4Data", align: "center", headerSort: false, responsive: 0 },
                            { title: "Value 5", field: "Value5Data", align: "center", sorter: "alphanum", responsive: 0 },
                            { title: "Value 6", field: "Value6Data", align: "center", sorter: "alphanum", responsive: 0 },
                            { title: "Value 7", field: "Value7Data", align: "center", sorter: "alphanum", responsive: 0 },
                            { title: "Value 8", field: "Value8Data", align: "center", headerSort: false, responsive:1 },
                            { title: "Value 9", field: "Value9Data", headerSort: false, responsive:2 },
                            { title: "Value 10", field: "Value10Data", headerSort: false, align: "center", formatter: "tickCross", responsive: 0},
                        ],

                    })
                    $(tableEl).tabulator("setData", "/api/Data2");
            }
            })
        }
    });

    $("#TestTable").tabulator("setData", "/api/Data1");

    $(window).resize(function () {
        $("#TestTable").tabulator("redraw");
    });


`

At first i was thinking it might be messing p because i re-use the variables for the table holders, but I'm not sure.

**Comment by olifolkerd** [comment]
Thanks for the fiddle, that was a great help.

That is definitely a bug, i will see if i can get a fix out for it at the weekend.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @mrslayer01 

On closer inspection it appears that you are trying to use Tabulator with no columns defined on the top table.

Tabulator was never designed to be used in this fashion so it will likely behave very unsually.

There was a bug causing group collapse on redraw in classic render mode, which i have just pushed a fix for to the master branch and will include in this evenings patch release.

However groups in the sub-table will not remember their open/closed state at this point, this is because the redraw function will cause the sub-table to be rebuilt on resize, so it is essentially reset back to its original state.

Cheers

Oli :)
