### ISSUE TITLE
Responsive collapse : editing 

### ISSUE THREAD

**Issue by tomvanlier** [olifolkerd/tabulator#1209]
Hi there,

I am trying to construct the following :

* Every client in our company has a filing card, and I am rewriting the digital version, that's where tabulator comes in.
I am planning to divide the data into seperate tables on one page, but even then a table containing e.g. general information is too big for 1 screen. There are then several options, like row formatting, making buttons to show and hide or ...

I am however trying to work with the responsive collapse. Now, my problem is with editing. Since the collapsed data is rendered in a table in a div .tabulator-responsive-collapse, I can't access them the normal way (editor:true) and I don't know how the dummy variables would work and if it would get me any further into editing the data (that then also would need to be uploaded to a server, which I think I know how to do with ajax Callbacks in 'normal' cells).

A workaround would be to use a responsiveLayoutCollapseFormatter, and adding id's to the list elements (or making a table there and giving the td elements an id or smth), which involves writing quite some code.

So if there is any built-in functionality, which would prevent the workaround by possibly using the dummy variables, that would save me some time.
If not : tabualtor is a great tool anyway.

The idea would be to have the collapsed entries editable and get them uploaded to a mysql database after validating/editing ... (like most others)

Thx a bundle for the answer !

**Comment by olifolkerd** [comment]
Hey @tomvanlier 

At the moment there is no ability to edit collapsed lists built in to tabulator, you would have to add that yourself with the ***responsiveLayoutCollapseFormatter*** as you suggest.

The other option you could look at is [Nested Tables](http://tabulator.info/examples/3.5#nested-tables)

You could even go super fancy and use the collapse formatter to create a nested table.

I hope that helps,

Cheers

Oli :)

**Comment by tomvanlier** [comment]
Thx for the idea,

I am implementing a taboulator inside the responsiveLayout :)

**Comment by olifolkerd** [comment]
@tomvanlier 

Thanks for your ind words, it is great to hear that people enjoy using Tabulator.

Thanks for the offer, i have a [Patreon Page](https://www.patreon.com/olifolkerd/memberships) for people who want to make a donation.

Cheers

Oli :)

**Comment by andering** [comment]
Hello, today i dive into same issue, while looking through js code I got 3 idea (with no deep understanding tabulator structure). In order to make this task supper easy there would be to get row or cell, solution with what i have i come up with:

1. abusing formatter (where usability in not responsive mode is ruined:
`{title:"Subject", formatter: function(cell, formatterParams, onRendered){ return cell;}, field:"subject",width:1000, editor: "textarea"},`
2. allow overload generateCollapsedRowData:
`this.generateCollapsedRowData = this.table.options.customGenerateCollapsedRowData || this.generateCollapsedRowData;`
3. add second argument "row" to collapseFormatter:
`contents = this.collapseFormatter(this.generateCollapsedRowData(row),row);`

**Comment by rtman** [comment]
Hey @olifolkerd I was wondering if you could perhaps shed some more light on how this could be accomplished? `responsiveLayoutCollapseFormatter ` doesn't seem to provide data on whether or not the cell is editable, and I'm not sure how the nested table idea would work?

Also where do you think this sits in terms of an official feature?

Thanks

**Comment by olifolkerd** [comment]
@rtman if it has collapsed it is not editable, there is no actual cell for it to work it so there is nothing to edit.

It is probably about 6 months away as a feature.

Cheers

Oli :)

**Comment by rtman** [comment]
@olifolkerd Yup I understand that part. 
But you allude to it being possible above and @tomvanlier says he has it working. Do you think you could provide a bit more in depth of a description for how this would work?

**Comment by niftylettuce** [comment]
Related to #1300
