### ISSUE TITLE
Formatter: DateTime and Time Delta

### ISSUE THREAD

**Issue by Pinaz9** [olifolkerd/tabulator#1210]
Suggestion: Two new column formatters:

DateTime: An ISO 8601 compliant display that can be calculated from an object with any number of optional parameters, such as milliseconds past the second, seconds past the minute, minutes past the hour, hours past midnight, days since Jan 1, years since 1970, UNIX timestamp (seconds since 00:00:00 1 Jan 1970 UTC), timezone, and any others that may be useful. Each parameter would have a default, so that a DateTime without parameters would end up displaying as the aforementioned UNIX epoch. Parts of the display could be disabled, but all would display by default.

Time Delta: Displays a difference in two times, such as time elapsed between the Unix epoch and the current time, or an arbitrary quantity such as 300 seconds (5 minutes). Like Date Time, this could be constructed using an object with any number of optional attributes. However, it would also be useful to be able to specify an arbitrary number of seconds and have the formatter return a string formatted as minutes and seconds, or hours minutes and second, if there are more than 3600 seconds to deal with. Default values could be zeros all around.

Time Delta is the one I'm most interested in, as I'm now faced with writing a mutator for a project I am currently working on. I would be happy to contribute JS code to the effort, as I will shortly be writing it anyway.

**Comment by olifolkerd** [comment]
Hey @Pinaz9 

Great idea! i love it, i will add that to the roadmap for the 4.0 release in July.

In the mean time i would suggest using a custom formatter that uses the [moment.js library](https://momentjs.com/) to take care of all the formatting for you.

I hope that helps,

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @Pinaz9 

I have just pushed updates to the 4.0 branch for these,

a new ***datetime*** formatter:
```js
{title:"Date of Birth", field:"dob", formatter:"datetime", formatterParams:{inputFormat:"DD/MM/YYYY hh:mm:ss", outputFormat:"YYYY-MM-DD hh:mm:ss", invalidPlaceholder:"Invalid Date"}}
```
and a new ***datetimediff*** formatter:
```js
{title:"Last Service", field:"service_date", formatter:"datetimediff", formatterParams:{inputFormat:"DD/MM/YYYY hh:mm:ss", humanize:true, suffix:true, nvalidPlaceholder:"Invalid Date"}}
```

Version 4.0 will be released later today,

Thanks for the suggestion,

Cheers

Oli :)

**Comment by Pinaz9** [comment]
No problem!
