### ISSUE TITLE
Show/hide function not working for multi level grouping

### ISSUE THREAD

**Issue by wcyharry** [olifolkerd/tabulator#1211]
I'm trying to do multi level grouping inside a nested sub table, `tableEl` in this case. However the show/hide function of the banner for the first level group doesn't work. Clicking on the arrow in the first level group banner has no effect on the content displayed. I was expecting that it should hide all of its underlying sub groups? Could anyone enlighten me, thx.

![image](https://user-images.githubusercontent.com/40449977/41698925-b1a89a3a-7553-11e8-80f6-30c6cc53b5b5.png)

Here's the the tabulator:

```js
$("#alert_table").tabulator({
        layout:"fitDataFill",
        groupBy:"table",
        groupToggleElement:"header",
        columns:[
            {title:"ALERTS", field:"table",  sortable:false, align:"center", visible:false},
        ],
        rowFormatter:function(row){
           //create and style holder elements
           var holderEl = $("<div></div>");
           var tableEl = $("<div></div>");

           holderEl.css({
               "width":"99.6%",
               "box-sizing":"border-box",
               "padding":"15px 15px 15px 15px",
               "border-top":"1px solid #333",
               "border-bottom":"1px solid #333",
               "background":"#ddd",
           })

           tableEl.css({
               "border":"1px solid #333",
           })
           holderEl.append(tableEl);

           row.getElement().append(holderEl);

           //create nested table
           tableEl.tabulator({
               layout:"fitColumns",
               groupBy:["url_list","feature"],
               //groupStartOpen:[true, false],
               groupToggleElement:"header",
               data:row.getData().thresholds,
               columns:[
                   {title:"URL LIST", field:"url_list", headerSort:true, align:"center", visible:true},
                   {title:"FEATURE/ERROR CODE", field:"feature", headerSort:false, align:"center", visible:true},
                   {title:"METRIC", field:"metric", headerSort:true, align:"center"},
                   {title:"THRESHOLD", field:"threshold", headerSort:false, align: "center", editor:"number", editorParams:{step:0.01}},
               ]
           })
        }
    });
```

**Comment by olifolkerd** [comment]
Hey @wcyharry 

That is quite a complex table setup you have there, i have had a couple of issue from people attempting to do nested grouping inside nested tables, and it is a little outside the standard usage case for Tabulator so hasnt been extensively tested.

I will have a look into grouping and subtables in the next couple of weeks and see if i can release a patch to address the issue.

Cheers

Oli :)

**Comment by wcyharry** [comment]
Glad to hear that. Thx a lot sir @olifolkerd

**Comment by olifolkerd** [comment]
Hey @wcyharry 

There was an issue with group collapse in tables using classic render mode.

I have pushed a fix for this to the master branch and will include it in this evenings patch release

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @wcyharry 

sometimes it can take a day or so for the update to propagate to their systems.

If it isn't available by Tuesday i will drop them a message.

Cheers

Oli :)
