### ISSUE TITLE
headerFilterFunc in html-table

### ISSUE THREAD

**Issue by sourrounder** [olifolkerd/tabulator#1212]
Hello,

filtering works like:
`{title:"Age", field:"age", headerFilter:"input", headerFilterPlaceholder:"Max Age", headerFilterFunc:"<="}`

so i tried in html-table:
`<th class="text-center"  tabulator-headerFilter="input" tabulator-headerFilterFunc="<=" tabulator-width="150">`

But in html-tables the FilterFunc does not work as expected, it still uses "like". Results are the same as without headerFilterFunc.

I would like to filter in tables head counts (numbers) , for example every number >= 10.

Now i changed to json-data.

Filtering >=5 does not show a number like 120! But 120>5 - or is there a special filter vor numbers, which i oversaw?

What am i doing wrong?

**Comment by olifolkerd** [comment]
Hey @sourrounder 

Could i ask what version of Tabulator you are using? and is the data you are filtering actually numertic or a string of numbers?

Cheers

Oli :)

**Comment by sourrounder** [comment]
Hello,
i am using Tabulator 3.4.2.

Yeah, i see, obviously i am filtering a string of numbers. What's the best way within Tabulator to convert to numeric?

Mutator, Formatter, Accessor, Validator? The data is read by php from a database an json_encoded by php.
Maybe there is an even simpler way, for examble in definiton of the table's columns?

Too many ways ...

Thanks.

**Comment by olifolkerd** [comment]
a mutator would be the best approach for this

**Comment by sourrounder** [comment]
Thanks!

Indeed, very easy, very comfortable!
