### ISSUE TITLE
Change the color of a specific cell by position

### ISSUE THREAD

**Issue by kreamas** [olifolkerd/tabulator#1215]
Hi.

Is it possible to change the color of a specific cell by its position instead of a specific condition?

I have a table that display both historical data and forecasts and I would like to be able of change the color of those cells that contains only the forecasts.

Thanks in advance.

**Comment by joaosalvado10** [comment]
Did you find a way to do it ?

**Comment by olifolkerd** [comment]
Hey @joaosalvado10 

What is your usage case? i may be able to suggest a solution for you?

Cheers

Oli :)
