### ISSUE TITLE
getHTML not working for nested Json 

### ISSUE THREAD

**Issue by ryhill** [olifolkerd/tabulator#1216]
var table = $("#example-table").tabulator("getHtml","true");

I tried this option , but the output from json is first level data.
Columns generated using notation like person.name is ignored.

**Comment by olifolkerd** [comment]
Hey @ryhill 

That is definitely a bug,

i have pushed a fix to the master branch and will include it in this evening patch release.

Cheers

Oli :)

**Comment by ryhill** [comment]
Cheers Oli.

Tabulator has been of gr8 help.
