### ISSUE TITLE
[wishlist] Initial ajax filter?

### ISSUE THREAD

**Issue by mateddy** [olifolkerd/tabulator#1217]
For ajax loading, Is there an initial filter option similar to initialSort?  Although a server-side workaround is possible by detecting absence of 'filters' in the paginationDataSent.

I also tried setFilter, but it seems that setFilter could only be called after a tabulator is initialized.

**Comment by olifolkerd** [comment]
Hey @mateddy 

At the moment that is not possible, but i love the idea!

I will include it in the 4.0 release next month.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @mateddy 

This is now available on the 4.0 branch which will be released later today.

Cheers

Oli :)
