### ISSUE TITLE
CDN Links not working !

### ISSUE THREAD

**Issue by kumar499** [olifolkerd/tabulator#1218]
Hi olifolkerd,

Given CDN Links from your documentation are not available . Can you provide right cdn links please as per the latest version .

<link href="https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.5.3/css/tabulator.min.css" rel="stylesheet">

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.5.3/js/tabulator.min.js"></script>

Thanks

**Comment by olifolkerd** [comment]
Hey @kumar499 

This has now been resolved, that link should work correctly.

Cheers

Oli :)
