### ISSUE TITLE
[Question] What is the purpose of returning the column on tabulator('getSorters')

### ISSUE THREAD

**Issue by lgraziani2712** [olifolkerd/tabulator#1219]
Today I encountered a problem while trying to implement ajax sorting in my tables. The default ajax sorting works perfect, but I have a persistence process where I want to add the active filters and sorters so I can return the updated data correctly filtered and sorted. The filtering works, but the sorting not.

This is the code that fails:

```js
const data = {
  // my data
  filters: myTable.tabulator('getFilters', true),
  sorters: myTable.tabulator('getSorters'),
};
const parsedData = jQuery.param(data);
```

jQuery crashes because `too much recursion`. When I checked what kind of data had the sorters array, I saw the `column` field, which has a lot of metada about the column.

I fixed it like this:

```js
const data = {
  // my data and filters
  sorters: myTable.tabulator('getSorters').map(({ field, dir }) => ({ field, dir })),
};
```

The question is: what is the purpose of returning the `column` attribute? Isn't it better to only return the `field` and `dir` attributes?

Thank you! Luciano.

**Comment by olifolkerd** [comment]
Hey @lgraziani2712 

Thanks for getting in touch, the column value is the [Column Component](http://tabulator.info/docs/3.5#component-column) for the column that is being sorted.

If allows you to programtically trigger all sorts of function on the column itself.

I hope that helps,

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @lgraziani2712 

The column component is not meta data, it allows functional actions to be taken on the column and as with the row component and cell component it is returned form almost every function and callback that relates to the column, the whole point of the components it to make it easier to control the table, adding another lookup to that process would only make that more convoluted.

If anything it should be added to the return from the sort function.

i do agree that there should be a ***getColumn*** function that allows you to look up the column by field name as there is a getColumn function on the row component and i try to replicate those globaly, and will add that to the road map.

Thanks for your feedback, it is appreciated, but i will definitely not be removing the column component from the results of the function, it is useful in a wide variety of circumstances.

I would encourage you to read the documentation for the different component objects and what they can do as they are a powerful part of how Tabulator should be used.

Cheers

Oli :)
