### ISSUE TITLE
How to add fileupload control to tabulator

### ISSUE THREAD

**Issue by minalkArmstrong** [olifolkerd/tabulator#122]
Dear olifolkerd,
Is it possible to add fileupload control to table like tickcross checkbox control?
If it is possible with custom formatter function
then how? And Can we show the list of already attach document on cell.

**Comment by olifolkerd** [comment]
To approach this problem, we should break it down into its two component tasks, displaying a list of files, and uploading a file.

### Displaying a file List
This can be achieved by passing an array of filenames into one of your data fields and using a custom formatter to show that data as a list (i will leave how you format the list with CSS up to you).

In this example I will define the data array manually, but you could lookup the files server side and pass this data over ajax:
```js
//example table data
var data = [
 {name:"Bob Misterson", files:["cheese.txt", "cake.jpg", "chocolate.yum"]},
];

//file formatter
var fileFormatter = function(value, data, cell, row, options, formatterParams){
    var list = $("<ul></ul>");

    value.forEach(function(filename){
        list.append("<li>" + filename + "</li>");
    });

   return list;
}

//define table
$("example-table").tabulator({
    columns:[
        {title:"Name", field:"name"},
        {tile:"Files", field:"files", formatter:fileFormatter},
    ],
});
```

### Upload file button
The process of uploading a file with a button will have two main parts, a custom formatter that adds the button, then an event binding in that formatter that triggers the upload.

I wont go into the details of triggering a file upload from a button as that is a whole area of coding on its own, but I will point you in the direction of an excellent library that I use all the time called [Plupload](http://www.plupload.com/) which is great button based file uploads, they have a load of demos that you can use to work out how to achieve this.

To create the upload button you want to create an [icon column](http://olifolkerd.github.io/tabulator/docs/#formatting) that uses a custom formatter to create the button:
```js
//upload button formatter
var uploadButton = function(value, data, cell, row, options){ //plain text value
    var button = $("<button>Upload</button>");

    button.on("click", function(){
        //trigger your file upload here
    });

    return button;
};

//define table
$("example-table").tabulator({
    columns:[
        {title:"Name", field:"name"},
        {formatter:uploadButton},
    ],
});
```

I hope this helps point you in the right direction

**Comment by minalkArmstrong** [comment]
**Fileupload Fucntion**
function fileinfo(fileupload,id)
{
var file=fileupload.files[0].name;
  var projcode = document.getElementById('<%=ddlprojectcode.ClientID%>').value;
    var userid = document.getElementById('<%=hdnuserID.ClientID%>').value;
                      PageMethods.UploadAttachmenttoTemp(id,file,projcode,userid,OnSuccess);           



}
function OnSuccess(response) {
alert("file uploaded successfully!!");
var data=response.toString();
   $(document).ready(function() {
 $("#example-table-demo").tabulator("setData", data);
 });
         

**code for file attachment:**
{width: 200  ,formatter:function(value, data, cell, row, options, formatterParams){
        //value - the value of the cell
        //data - the data for the row the cell is in
        //cell - the DOM element of the cell
        //row - the DOM element of the row
        //options - the options set for this tabulator
        //formatterParams - parameters set for the column
         var items = Object.values(data);
        return "<div><input type='file' id='flupld' onchange='fileinfo(this,"+items[9]+")'/></div>"; // must return the html or jquery element of the html for the contents of the cell;
    }},

**on set data this is happend:**
![fileupload](https://cloud.githubusercontent.com/assets/24350278/21042567/31b22e34-be18-11e6-972b-63d4c4b31072.png)

**Tabulator code:
Currently I am binding data using global variable.**
     $(document).ready(function() {
     $("#example-table-demo").tabulator({
            fitColumns:true,
			tooltips:true,	
			data:[<%=TableData %>],
			tooltipsHeader:true,
			colResizable:false,
			  pagination: "local", //enable local pagination.
              paginationSize: 15, // this option can take any positive integer value (default = 10)
              columns: [


				{ title: "Sr.no",field:"id",   width: 70 ,  visible: false},
			{ title: "Partcode",field:"Partcode", sorter: "string", align: "left", headerFilter: true ,   width: 250},
			{ title: "Description",field:"Description", width: 100, sorter: "string", width: 300, headerFilter: true },
			{ title: "Qty",field:"Quantity", sorter: "number", width: 95, editable: true, headerFilter: true },
			{ title: "UOM",field:"UOM", sorter: "string", width: 70, editable: true, headerFilter: true },
			{ title: "Delivery Location",field:"DeliveryLocation", align: "center", sorter: "string", editable: true, headerFilter: true },
			
			{ title: "Delivery Date",field:"DeliveryDate", sorter: "date", align: "center", editable: true, headerFilter: true },
			{ title: "Remarks",field:"Remarks", align: "center", sorter: "string", editable: true, headerFilter: true },
			
			{ title: "Attachment",field:"Attachment",   width: 150  , formatter:function(value, data, cell, row, options, formatterParams)
			{
			var list = $("<ul></ul>");

    value.forEach(function(filename){
        list.append("<li>" + filename + "</li>");
    });

   return list;
			} },
			{ title: "RowId",field:"RowId",  visible: false},
			{width: 200  ,formatter:function(value, data, cell, row, options, formatterParams){
        //value - the value of the cell
        //data - the data for the row the cell is in
        //cell - the DOM element of the cell
        //row - the DOM element of the row
        //options - the options set for this tabulator
        //formatterParams - parameters set for the column
         var items = Object.values(data);
        return "<div><input type='file' id='flupld' onchange='fileinfo(this,"+items[9]+")'/></div>"; // must return the html or jquery element of the html for the contents of the cell;
    }},
             {formatter:"tickCross", field:"Status",  align:"center",sortable:false},
           
			],
              cellEdited: function(id, field, value, oldValue, data, cell, row) {                 
                  Update(data);              
              }
          });
         
     });

**Somewhere i am going wrong?
What i want is when file attach to is done and ajax function returns new set of object array  then it should be reflected in table without postback.**

**Comment by olifolkerd** [comment]
That looks like there is an error when loading the data, have you had a look in your developer console to see if any messages are displayed?

**Comment by olifolkerd** [comment]
did you get any further with this?

Were there any error messages displayed in your debug console?

**Comment by olifolkerd** [comment]
closed due to inactivity

**Comment by philipborbon** [comment]
Is there a solution for using "editor" in v5?

**Comment by olifolkerd** [comment]
@philipborbon 

No there is no built in file upload editor for Tabulator, nor will there be in future, the nature of file uploads is so specific to the site on which it is being used, that building an editor to handle this would be impractical.

It would be far better for you to build a custom editor using an off the shelf file upload component.

Cheers

Oli :)
