### ISSUE TITLE
Adding data with "addData" quite slow

### ISSUE THREAD

**Issue by TomSmartBishop** [olifolkerd/tabulator#1220]
I'm dynamically adding data on click like this:

rowClick: function (e, row) {
	$("#my-table").tabulator("addData", row.getData().subrows, false, row.getData().id);
}

However, it feels quite slow (compared to the data initially loaded). In Edge it's already getting sluggish after 10 items or more. Chrome is also getting slow when inserting more than 30 items. Is there anything obvious I can do?

Thanks,  Thomas

**Comment by olifolkerd** [comment]
Hey @TomSmartBishop 

Could you include a copy of your table constructor so we can see how your table is configured?

Cheers

Oli :)

**Comment by TomSmartBishop** [comment]
Yeah sure:

```
var data = {
	id: 2, name: "A", subrows: [
		{
			id: 3, name: "A/B", subrows: [
				{
				id: 4, name: "A/B/C", subrows: [
					{
					id: 5, name: "A/B/C/D", subrows: [
						{ id: 6, name: "A/B/C/D/E"},
						{ id: 7, name: "A/B/C/D/E/a-1"},
						{ id: 8, name: "A/B/C/D/E/a-2"},
						{ id: 9, name: "A/B/C/D/E/b-1"},
					],
					}
				],
				}
			],
		},
		{
			id: 10, name: "A/F", subrows: [
				{
				id: 11, name: "A/F/G", subrows: [
					{
					id: 12, name: "A/F/G/H", subrows: [
						{ id: 13, name: "A/F/G/H/I"},
						{ id: 14, name: "A/F/G/H/I/j-1"},
						{ id: 15, name: "A/F/G/H/I/j-2"},
						{ id: 16, name: "A/F/G/H/I/k-1"},
					],
					}
				],
				}
			],
		},
	],
},
{
	id: 17, name: "L", subrows: [
		{ id: 18, name: "L/M"},
		{ id: 19, name: "L/M/n-3"},
		{ id: 20, name: "L/M/n-2"},
		{ id: 21, name: "L/M/o-1"},
	],
},
{
	id: 22, name: "P", subrows: [
		{
			id: 23, name: "P/Q", subrows: [
				{ id: 24, name: "P/Q/R"},
				{ id: 25, name: "P/Q/R/s-1"},
				{ id: 26, name: "P/Q/R/s-2"},
				{ id: 27, name: "P/Q/R/t-4"},
				{ id: 28, name: "P/Q/R/1-1"},
				{ id: 29, name: "P/Q/R/2-1"},
				{ id: 30, name: "P/Q/R/3-2"},
				{ id: 31, name: "P/Q/R/4-4"},
				{ id: 32, name: "P/Q/R/5-3"},
				{ id: 33, name: "P/Q/R/6-1"},
				{ id: 34, name: "P/Q/R/7-2"},
				{ id: 35, name: "P/Q/R/8-4"},
				{ id: 36, name: "P/Q/R/9-5"},
				{ id: 37, name: "P/Q/R/10-1"},
				{ id: 38, name: "P/Q/R/11-2"},
				{ id: 39, name: "P/Q/R/12-4"},
				{ id: 40, name: "P/Q/R/13-6"},
				{ id: 41, name: "P/Q/R/14-1"},
				{ id: 42, name: "P/Q/R/15-2"},
				{ id: 43, name: "P/Q/R/16-4"},
				{ id: 44, name: "P/Q/R/17-3"},
				{ id: 45, name: "P/Q/R/18-1"},
				{ id: 46, name: "P/Q/R/19-2"},
				{ id: 47, name: "P/Q/R/20-4"},
			],
		},
	],
},
```

**Comment by TomSmartBishop** [comment]
So I'm inserting the 'subrows' on click. When doing that for "P/Q" it actually takes some time...

**Comment by olifolkerd** [comment]
Hey @TomSmartBishop 

Thanks for posting the data, could you post the constructor object you use to configure your table so we can understand which setup options you have used.

Cheers

Oli :)

**Comment by TomSmartBishop** [comment]
I removed the formatters, but the setup is really simple:

`var init = {
	layout: "fitColumns",
	layoutColumnsOnNewData:true,
	columns: [
		{
			title: "Name", field: "name", frozen: true, widthGrow: 6, headerSort: false
		},
		{ title: "#Covered<br>Lines<br>", minWidth: 60, field: "c", widthGrow: 1, headerSort: false, visible:false, formatter: function (cell, formatterParams) {
				var data = cell.getRow().getData();
				return getVal(data.c);
			},
		},
	],
	rowClick: function (e, row) { ... }
}

$("#my-table").tabulator(init);`

**Comment by TomSmartBishop** [comment]
A bit more context: I have hierarchy that expands when clicking the parent (the code you see). With a slightly different code I hide and un-hide the rows again when clicking again. I do that because deleting the rows was painfully slow, would be really nice to have an efficient bulk delete as well.

**Comment by olifolkerd** [comment]
Hey @TomSmartBishop 

Have you declared a height anywhere on your table element? if you havnt it will be using classic render mode which is really slow. if your table has a defined height then Tabulator can use its Virtual DOM which is much faster.

There is some documentation of this in the [Quick Start Guide](http://tabulator.info/quickstart/3.5)

I hope that helps,

Cheers

Oli :)

**Comment by TomSmartBishop** [comment]
Thanks, I did that (height: "100%") and indeed is speeds up by roughly 1/3. However I now lose the scroll position when adding data. So, after clicking, the page 'scrolls' to the top of the page.
