### ISSUE TITLE
Dynamically building content of headerFilter drop down

### ISSUE THREAD

**Issue by arminus** [olifolkerd/tabulator#1222]
I'm presently evaluating switching from datatables to tabulator, one thing I'm struggling with is to build the headerFilter dropdown dynamically from all values in that column. 

So I've read #809 - so I assume I'd hook into tableBuilt and loop through all my rows and build a list of unique values for a column, but how do I then set this list of options for the editorParams and/or headerFilterParams ? I only see declarative examples of that in the example and using a function there instead of a static string would be too early, right?

Also, I have a case where a 2nd filter (let's say a list of states) would need to be updated after a country filter had been set - same logic here I guess, but again, to be triggered from tableBuilt I suppose?

**Comment by c3pos-brother** [comment]
Ive been struggling with this too, did you find a resolution?

**Comment by arminus** [comment]
I'm afraid I haven't...

c3pos-brother <notifications@github.com> schrieb am Do., 23. Aug. 2018,
19:47:

**Comment by olifolkerd** [comment]
Hey @arminus and @c3pos-brother 

Sorry for the delayed response, i seem to have missed your original query.

you would need to build your filter element outside of tabulator, do you could access it anywhere:

```js
var select = $("<select></select>");
```

then create an editor that uses this:
```js
var selectEditor = function (cell, onRendered, success, cancel, editorParams) {
    select.css({
        "padding":"3px",
        "width":"100%",
        "box-sizing":"border-box",
    });

    //Set value of select to the current value of the cell
    select.val(cell.getValue());

    //set focus on the select box when the select is selected (timeout allows for select to be added to DOM)
    onRendered(function(){
        select.focus();
        select.css("height","100%");
    });

    //when the value has been set, trigger the cell to update
    select.on("change blur", function(e){
        success(select.val());
    });

    //return the select element
    return select;
}
```

you could then asign this to a column and use the ***dataLoaded*** callback to populate it with values:

```js
$("#example-table").tabulator({
    columns:[
        {title:"Filter Me", field:"color", headerFilter:selectEditor},
    ],
    dataLoaded:function(data){
        //empty the select element
        select.empty();

        //fill the select element with options from the data
        data.forEach(function(item){
            select.append("<option value='" + item.color + "'>" + item.item + "</option>");
        });
    },
});
```

I hope that helps,

Cheers

Oli :)

**Comment by pup71** [comment]
Hi Oli,

Have made the switch from dataTable to Tabulator, much nicer and easier to use. 

Struggling a bit with Dynamic Filter Header too. Have tried the following above but getting an error on load.  Uncaught TypeError: s.setAttribute is not a function at tabulator.min.js.

**Comment by cgountanis** [comment]
@olifolkerd 

Just curious if the values: true went away with v5?

title: "Status",
minWidth: 80,
headerFilter: "list", <--Used to be select...
headerFilterParams: {
	values: true,
	sort: "asc"
}

**Comment by olifolkerd** [comment]
It changed to valuesLookup

**Comment by cgountanis** [comment]
Thanks a ton, saved me a few hours.
![image](https://user-images.githubusercontent.com/14899817/196816735-51d1411a-c4e7-468d-a176-b354ef2b97aa.png)
