### ISSUE TITLE
[Documentation] typo

### ISSUE THREAD

**Issue by mateddy** [olifolkerd/tabulator#1224]
Under Editing & Manipulating Data -> Editable Data -> Custom editor:
Blue event -> Blur event

Under Editing & Manipulating Data -> Replacing Data:
aja loading -> ajax loading 

Under Editing & Manipulating Data -> Interaction History:
Callback: should this be h3 instead of h2?

**Comment by olifolkerd** [comment]
Hey @mateddy 

Thanks for pointing these up,

I have fixed them for the 4.0 site update.

Cheers

Oli :)

**Comment by KES777** [comment]
[Also:](http://tabulator.info/docs/4.1/data#ajax)

> You can also load data at any point by ajxa by passing

Notice: `ajxa`
