### ISSUE TITLE
How to get error from setData with Ajax

### ISSUE THREAD

**Issue by michaelongithub** [olifolkerd/tabulator#1225]
Hi 
if I do tabulatorObject.tabulator("setData", url); I dont know how to handle if that produces an error.

Does not produce a try/catchable error

F.i. it produces an Ajax Load Error or so, the grid shows Load Error, also error on console.
But how to catch programmatically for displaying some meanigful info and handle situation programmatically.

Did not find something about that in docu.

Thanks for info.

Cheers, Michael

**Comment by olifolkerd** [comment]
Hey @michaelongithub 

The ***ajaxError*** callback handles this:

```js
$("#example-table").tabulator({
    ajaxError:function(xhr, textStatus, errorThrown){
        //xhr - the XHR object
        //textStatus - error type
        //errorThrown - text portion of the HTTP status
    },
});
```

I hope that helps,

Cheers

Oli :)

**Comment by michaelongithub** [comment]
Thanks
