### ISSUE TITLE
Add/Remove rows on nested table

### ISSUE THREAD

**Issue by ltomaz** [olifolkerd/tabulator#1227]
Hello. Is it possible to add/remove rows in a nested table? Has anyone had similar experience and could share ideas / solutions? Thank you very much

**Comment by olifolkerd** [comment]
Hey @ltomaz 

That would very much depend on how you are passing data into your nested table, it it is just pulling in from the row data i would suggest finding the row component of the row that needs updating, calling the ***update*** function on that row component passing in the new data and then if needed calling the ***reformat*** function on the row after.

I hope that helps,

Cheers

Oli :)
