### ISSUE TITLE
Addata by ajax without removing existing data

### ISSUE THREAD

**Issue by Rodbjartson** [olifolkerd/tabulator#1230]
Hey!
I am wondering if it is possible to setData with ajax without replacing the current data in the table.
Say I have a table with 10 rows. I want to add 2 rows from a different source. Then by using setdata I will replace all rows with these two. Is there a way to add these rows to the existing 10?

**Comment by olifolkerd** [comment]
Hey @Rodbjartson 

If you wanted to do that you would need to make the ajax call outside of tabulator and then use the ***updateOrAddData*** to pass it into the table.

I hope that helps,

Cheers

Oli :)
