### ISSUE TITLE
Question around headerFilter  custom editor

### ISSUE THREAD

**Issue by jmjdev** [olifolkerd/tabulator#1233]
Hi,

I was hoping you could help with two questions.

I've got my table setup with multiple-select header filters using this custom editor, then applying the options dynamically:
```
Tabulator.extendExtension("edit", "editors", {
	selectEditor:function(cell, onRendered, success, cancel, editorParams){
		var editor = $("<select id='"+this.table.element["0"].id+"-headerFilterSelect-"+editorParams+"'   multiple></select>");
		editor.css({
			"width":"100%",
			"box-sizing":"border-box",
			"margin":"0",
		});
								
		onRendered(function(){
			editor.focus();
		});

		editor.on("change blur", function(e){
			success(editor.val());
		});

		editor.on("keydown", function(e){
			if(e.keyCode == 13){
				success(editor.val());
			}
		});
	 return editor;
	},
});
```

This works well, though the first reason for using the multi-select is to be able to deselect a filter option.
When I do this, the table clears as if it can't find anything for a filter, rather than returning to an unfiltered state.

I've logged the filters and can see, for example, when I deselect _something_ then the filter goes from:
`field:"row"
type:"="
value:Array(1)
	0:"something"
	length:1`
to:
`field:"row"
type:"="
value:Array(0)
	length:0`

How best would I set this to clear the deselected filter only, retaining any active filters from other columns?

The second question is around filtering on multiple.

If I have multiple selected, then the log of the filter looks like this:
`field:"row"
type:"="
value:Array(2)
	0:"something"
	1:"else"
	length:2`

What would I need to modify to get this to filter on both individually, rather than combined?

Thanks in advance,

Jack

**Comment by olifolkerd** [comment]
Hey @jmjdev 

Thanks for getting in touch.

I think i can answer both your questions at once.

Have a look at the ***headerFilterFunc *** property, it lets you create your own custom filter function. you could then pass an array of values from your header filter into this function to then filter against them.

That way any change to the value in the header filter would result in a re-filter of the table data as needed.

let me know if that helps,

Cheers

Oli :)

**Comment by jmjdev** [comment]
Hi @olifolkerd,

Thanks very much!

The following worked for me.

```
Tabulator.extendExtension("filter", "filters", {
	//----------------------------//
	// Custom Header Filter Function for Multiple Select 
	//---------------------------//
	multiselectHeaderFilter:function(headerFilterValue, cellValue){
		
		var equivalent = false;
		
		headerFilterValue.forEach(function(v){
			if(v.indexOf(cellValue) > -1){
				equivalent = true;
			}
		});

		if (headerFilterValue.length == 0) {
			equivalent = true;
		}
		
		return equivalent;
		
	}
});
```

And then adding `headerFilterFunc:multiselectHeaderFilter` to my columns.

Cheers,

Jack
