### ISSUE TITLE
Movable Rows not working with Firefox 60.0.2 (64-Bit)

### ISSUE THREAD

**Issue by f466162** [olifolkerd/tabulator#1237]
Hi,

today I tried the movable rows functionality. While trying I figured out that moving rows is not possible with my current Firefox build. Even the example is not working - rows can be dragged, but they are not exchanged between different tables. A custom insert function (copied from the docs with an additional console.log(...) call is not fired. The same behavior happens when using the example on the examples page. 

With Chromium (version 66.0.3359.181) everything works fine... Is there any additional workaround required for Firefox that I missed?

Regards and thanks for your effort in advance,
Fabian

**Comment by f466162** [comment]
Seems to be related to #1184 (or: a duplicate...;-))

**Comment by olifolkerd** [comment]
Hey @f466162 

This is indeed a duplicate, im looking into it, 

something seems to have changed in the order that firefox is handling vairous mouse events that is breaking it,

I will include a fix for it in the 4.0 release.

Cheers

Oli :)
