### ISSUE TITLE
Question using Select Editor

### ISSUE THREAD

**Issue by mfenton01** [olifolkerd/tabulator#1238]
Oli, Have to commend you on this application. Great tool!! Finding new ways to use. 
Working on a new project accessing MySQL. I want to use data from a  DB table for a dropdown in Tabulator. 

Not sure how to implent in Tabulator using your example 
{title:"Name", field:"name", editor:"select", editorParams:function(cell)  { **?**  }

I have the ajax function to  return the json formatted query 

     	//AJAX Method
		$.ajax({
		url: '/mfg_names.php',
		dataType: 'json',
		type: 'get',
		cache: 'false',
		success: function(data)	{
				$(data.mfgnames).each(function(index,value){
				console.log(value);
    		});
			}
		});

Sample Json formatted data: 

{
    "mfgnames": [
        {
            "Name": "3COM"
        },
        {
            "Name": "8e6 Technologies"
        },
        {
            "Name": "AIPhone"
        },
        {
            "Name": "AJA"
        },
        {
            "Name": "Ambery"
        },
        {
            "Name": "APC"
        },
        {
            "Name": "Apple"
        },
        {
            "Name": "AppNeta"
        },
        {
            "Name": "ArcSight"
        },

**Comment by olifolkerd** [comment]
Hey @mfenton01 

Thanks for your kind words, it is great to hear that Tabulator is appreciated

The issue you are having is two fold.

Firstly the ***editorParams*** property will not execute a function that is passed to it (but i think this is a very interesting idea and will include it in the 4.0 release)

The second would be that ajax calls are asynchronous so the list will have been rendered before the ajax call returns with the value.

To get round this i would suggest that you load your data in the background outside of Tabulator before it is needed, and then reference a variable outside of tabulator to provide this data for the list.

I hope that helps.

Cheers

Oli :)
