### ISSUE TITLE
SyntaxError in Firefox

### ISSUE THREAD

**Issue by bonegabor** [olifolkerd/tabulator#124]
Hello,

I cannot see the tables in Firefox, even on your page. I've tried on two computers running on Debian 8.6 jessie. Do you have any idea why am I getting th following errors in Firefox - firebug console:

> SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function
> TypeError: $(...).tabulator is not a function

See also the screenshot:

I have also tried on my wife's laptop which is running on Linux Mint, and there it was ok.

Thank you,
Gábor

![snapshot3](https://cloud.githubusercontent.com/assets/23358648/21009118/ad90d986-bd4d-11e6-884f-87d5d734dadd.png)

**Comment by olifolkerd** [comment]
do you know which version of firefox you are running?

**Comment by bonegabor** [comment]
Mozilla Firefox 45.5.1

**Comment by olifolkerd** [comment]
It looks like there was an issue with the way firefox 45.5 handled the order of function declarations when in strict mode. the issue doesn't seem to be present in earlier or later versions.

**Comment by bonegabor** [comment]
Thank you very much for your help. I've upgraded to the latest version, and it works fine now.

**Comment by olifolkerd** [comment]
I have put in a fix for this so it should no longer cause any issues on firefox 45
