### ISSUE TITLE
[Question] The name differenciation between select and lookup is expected?

### ISSUE THREAD

**Issue by lgraziani2712** [olifolkerd/tabulator#1240]
Hello! Is expected to have two different names for the select input?

Is that because you would need to use the `editorParams` and `formatterParams` objects? If it is that, couldn't be better to reuse one of them? E.g. naive approach:

```js
Tabulator.extendExtension('format', 'formatters', {
  select(cell) {
    return cell.getColumn().getDefinition().editorParams[cell.getValue()];
  },
});
```

Or instead, in the editor, use the formatterParams. Or maybe check first which of them is setted? With bigger param objects, more data you have to send from the server.

Thank you! Luciano.

**Comment by olifolkerd** [comment]
Hey @lgraziani2712 

Thanks for getting in touch,

On the whole the formatter and the editors used in Tabulator use very different params, the select/lookup option being one of the few where this is similar. that is why they are kept separate as it is the correct course for the majority of combinations.

There is nothing to stop you storing the params in a variable outside of tabulator and then referencing it twice, once for the editor and once for the formatter.

Cheers

Oli :)
