### ISSUE TITLE
How to do row grouping in tabulator?

### ISSUE THREAD

**Issue by Praveene7** [olifolkerd/tabulator#1241]
![row merge](https://user-images.githubusercontent.com/20556109/42167718-79f5bb18-7e2c-11e8-8db5-c3ba5895982b.JPG)

**Comment by olifolkerd** [comment]
Hey @Praveene7 

Thanks for getting in touch,

Im afraid that style of row grouping isnt directly possible.

Yow you can either use tabulators in-built [row grouping](http://tabulator.info/docs/3.5#grouping) or a [nested table](http://tabulator.info/examples/3.5#nested-tables)

you could also look at the possibility of a row formatter to create a custom row layout.

I hope that helps,

Cheers

Oli :)
