### ISSUE TITLE
buttonCross as fieldLabel 

### ISSUE THREAD

**Issue by bioragul** [olifolkerd/tabulator#1243]
Hello,
I want to provide hyperlinks to buttoncross values in a column. Is it possible to use buttonCross as fileldLabel while using formatter:"link".?
{title:"Sdata", field:"Shandle", formatter:"link", formatterParams:{urlPrefix:"https://www.google.com/search?q=", fieldLabel:"buttonCross" } }
Thanks.

**Comment by olifolkerd** [comment]
Hey @bioragul 

Thanks for getting in touch,

you should be using ***labelField*** not fieldLabel for the param if you want to pull the data from another field in the row data, if you just want to display it as test then you should use the ***label*** property.

I hope that helps

Cheers

Oli :)
