### ISSUE TITLE
Header Filter Like Multiple Word

### ISSUE THREAD

**Issue by dasio86** [olifolkerd/tabulator#1244]
Hi,
i have i big table of 60000 records. I nedd to apply the "LIKE" criteria for the multiple word typed in the Header Filter.
Example:
The user type : "IP bullet";
what i need is that the search criteria should be "%IP% %bullet%" so it's ignore the order of the word.

I hope i was clear.
Thank you

**Comment by olifolkerd** [comment]
Hey @dasio86 

Thanks for getting in touch,

At the moment the inbuilt "LIKE" filter is very simplistic and will try and see if a string contains a substring of the filtered value.

You would need to use a [Custom Filter Function](http://tabulator.info/docs/3.5#filtering) to achieve this, and either use a regex or a couple of indexOf functions.

I hope that helps,

Cheers

Oli :)

**Comment by dasio86** [comment]
Thanks @olifolkerd  for your support. I tried this solution but having 60,000 records  the execution time is very very very long. Maybe i did something wrong.
What i do is:
```
var search = headerValue.replace(/ /g, "|");
return headerValue.match(new RegExp(search, 'i'));
```

**Comment by olifolkerd** [comment]
Hey @dasio86 

Do you have the virtual DOM enabled on your table (dose it have a height and a scroll bar?)

Cheers

Oli :)

**Comment by dasio86** [comment]
Hi @olifolkerd 
finally I found a compromise between speed and result; i used this code:
`
  pattern = headerValue.trim().split(' ').map(function(el) { 
          return '(?=.*' + el + ')';
        });
        //join if there is something in the array
        pattern = pattern.join("");

  return rowValue.match(new RegExp(pattern, 'i')); `ù
thank you for your support
