### ISSUE TITLE
Ajax Response Blocked

### ISSUE THREAD

**Issue by dasio86** [olifolkerd/tabulator#1246]
Hi,
I found slowness during loading and during troubleshooting analysis i found this message in the console.

`Ajax Response Blocked - An active ajax request was blocked by an attempt to change table data while the request was being made`

it is repeated several time and i think it can be the problem for slowness loading.

Hope you can help me.
Regards

**Comment by olifolkerd** [comment]
Hey @dasio86 

That warning isnt a problem in itself, what it means is that while it was loading data for the table someone carried out an action on the table that made it request data again, it therefor ignores the data from the previous request when it is returned and awaits the new data instead.

If that is part of normal table use then it can be safely ignored.

Cheers

Oli :)
