### ISSUE TITLE
headerClick fires after sorting

### ISSUE THREAD

**Issue by zegkljan** [olifolkerd/tabulator#1248]
When a `headerClick` callback is defined on a column which is header sortable, this callback is fired after the sort is performed. In my opinion, it should fire before sorting in order for the programmer to be able to prevent the sort.

**Comment by olifolkerd** [comment]
Hey @zegkljan 

Thanks for the suggestion,

I have made the change on the 4.0 branch which will be released later this weekend.

Thanks for getting in touch.

Cheers

Oli :)
