### ISSUE TITLE
Cell not losing focus when clicked outside the table

### ISSUE THREAD

**Issue by vinayrevanna** [olifolkerd/tabulator#1249]
I have created editable table. Cell take two values instead of one single text. I have used a plugin bootstrap-tokenfield(http://sliptree.github.io/bootstrap-tokenfield/) to achieve this. Only when I make changes inside the cell, editor updates the value and cell looses focus. But When I click outside the table cell is not losing focus.

here is my editor code:

          var mccEditor = function(cell, onRendered, success, cancel){
        	        if(!checkSaveDisabled()){
			var tokeninputtag = "<input id='mccInput' type='text' />";
        	        var editor = $(tokeninputtag);
					var value = cell.getValue();
        	        editor.css({
        	           // "padding":"2px",
						//"box-sizing":"border-box",
        	        });

        	        //Set value of editor to the current value of the cell
        	        //editor.val(cell.getValue());
					$(function(){
						console.log("mccEditor2");
					 editor.tokenfield({
						  tokens: value,
						  beautify : false,
						  minWidth : 280,
						  limit : 2,
						  showAutocompleteOnFocus: true,
					  });
					});
					
        	        //set focus on the select box when the editor is selected (timeout allows for editor to be added to DOM)
        	        onRendered(function(){
        	          //editor.focus();
        	          //editor.css("height","100%");
					});
        	        
				
        	        //when the value has been set, trigger the cell to update
        	        editor.on("change blur", function(e){
        	        	
        	        	success(editor.val());
						
        	        });
        	        
				 
        	      //submit new value on enter
        	        editor.on("keydown", function(e){
        	            if(e.keyCode == 13){
			  success(editor.val());
        	            }

        	            if(e.keyCode == 27){
        	                cancel();
        	            }
        	        }); 
        	      
					
					//return the editor element
        	        return editor;
				}
				return false;
        	    }; 

![image](https://user-images.githubusercontent.com/26703303/42359738-81bf24a6-8101-11e8-87fe-37d6be7e38ec.png)

Please help
Thanks and Regards,
Vinay

**Comment by olifolkerd** [comment]
Hey @vinayrevanna 

The issue is probably happening because the blur event is not correctly propagating. and is likely related to the  tokenfield plugin you are using. if it is not firing the blur event then your blur event binding will not be triggered.

If you put a console log in the blur event binding, does it show up when you click outside the editor? if not then that is your problem.

You could have a look at the tokenfield plugin documentation to see how it handles this.

I hope the helps,

Cheers

Oli :)

**Comment by vinayrevanna** [comment]
Thank you very much Oli.
I was able to solve the issue after seeing tokenfield plugin docs.

Regards,
Vinay
