### ISSUE TITLE
nested data 

### ISSUE THREAD

**Issue by Knight2601** [olifolkerd/tabulator#125]
is it possible to access values in nested data?
i have 
`[
{
fields: {
systemWorkItemType: "Feature",
systemState: "New",
systemReason: "New",
systemTitle: "initial work item",
systemBoardColumn: "New",
systemBoardColumnDone: false,
microsoftVSTSCommonStateChangeDate: "2016-12-07T14:02:24.24Z",
microsoftVSTSCommonPriority: 2,
microsoftVSTSCommonValueArea: "Business",
microsoftVSTSCommonRisk: "3 - Low",
weF_8107056482E145ECA07BC00173CF6A70_KanbanColumn: "New",
weF_8107056482E145ECA07BC00173CF6A70_KanbanColumnDone: false,
systemDescription: "a test description"
},
id: 2,
relations: [ ],
rev: 4
}
]`

im trying to add the field values into the table but neither "fields["systemState"] or fields.systemState work?
id and rev come out fine...
e.g. column
`{ title: "Name", field: "fields.systemTitle", sorter: "string", sortable: true },`
any ideas?

**Comment by olifolkerd** [comment]
Im afraid nested properties are not accessible as column fields, although you can use a object as a value and then use a custom formatter to render the values out in a single cell (great for cells that show a list of values etc.

In your case I would suggest you create a function to flatten the data before you input it into Tabulator, this example will flatten so you then could access data in the fields object using an underscore delimiter *(eg. fields_systemTitle)* :

```js
//flatten data

function flattenData(data){
	var output = [];
	

	function flatternRow(row){
		var outputRow = {};

		for(var prop in row){
			if(typeof row[prop] !== "object"){
				outputRow[prop] = row[prop];
			}else{
				var flat = flattenData(row[prop]);
				for(var flatProp in flat){
					outputRow[prop + "_" + flatProp] = flat[flatProp];
				}
			}
		}

		return outputRow;
	}

	data.forEach(function(row){
		output.push(flatternRow(row));
	});

	return output;
}

//load data into table
$("#example-table").tabulator("setData", flattenData(data));

```

**Comment by Knight2601** [comment]
Hi

Yes, i had to flatten the structure of the data to a single level.

Thanks

**Comment by genius257** [comment]
But if flattened, some data could be lost for reference with events?
Example: {id:2, name:'cain', parent:{id:1, name:'adam'}}
But i admit, i have no idea how problematic it would be to implement, and how big of a percentage of users would benefit from it.

**Comment by olifolkerd** [comment]
Using the code I posted above to flatten it, that would be:

```js
{id:2, name:'cain', parent_id:1, parent_name:'adam'},
```

so no dater would be lost, and it could easily be reconstituted back into a multi dimensional object by parsing for the delimiter in the property names.

It would be very difficult to build in multidimensionall field selectors as it currently stands, and would only offer benefit in a very restricted set of circumstances as there is already  functional work around for it. i will stick it on the road map to look at later down the line, but im afraid i probably wont be looking to add it for a long while yet.

Thanks for your example :)

Oli

**Comment by ntidev** [comment]
Is there a way to use this along with Ajax? without having to implement your own request  through $.ajax ...

**Comment by bvisonl** [comment]
Is there a way to use this along with Ajax? without having to implement your own request through $.ajax ...

**Comment by JeremyMorel** [comment]
One item to note for anyone wishing to use the function Oli has provided to "flatten" their data structure:  There were two typos, which I have corrected in this version.  
`flatternRow` should read `flattenRow`, and the  line `var flat = flattenData(row[prop]);` should instead be `var flat = flattenData(row[prop]);`, else the function will fail at the foreach clause when it reaches the first nested object.   Hopefully it saves someone a few cycles around the debugger! :)
```javascript
//flatten data

function flattenData(data){
	var output = [];
	function flatternRow(row){
		var outputRow = {};
		for(var prop in row){
			if(typeof row[prop] !== "object"){
				outputRow[prop] = row[prop];
			}else{
				var flat = flattenRow(row[prop]);
				for(var flatProp in flat){
					outputRow[prop + "_" + flatProp] = flat[flatProp];
				}
			}
		}
		return outputRow;
	}
	data.forEach(function(row){
		output.push(flatternRow(row));
	});
	return output;
}

//load data into table
$("#example-table").tabulator("setData", flattenData(data));
```

**Comment by olifolkerd** [comment]
Hey,

Thanks for spotting the typos there!

I have edited the original to avoid confusion, Thanks for getting involved in the conversations, always great to see the community helping eachother out :)
Cheers

Oli

**Comment by olifolkerd** [comment]
Hey,

You will be happy to hear that Tabulator 3.2 has just been released, and with it the the ability to bind columns to nested data, simply use dot notation in the field name:
```js
{title:"age", field:"user.age"), //link column to age property inside user object
```

Full information can be found in the [Column Definition Documentation](http://olifolkerd.github.io/tabulator/docs/3.2/#field-nesting)

Cheers

Oli

**Comment by KaranMah** [comment]
Is there way to autoread nested json and make columns from them?

**Comment by jmartsch** [comment]
@KaranMah This is possible. Please look at http://tabulator.info/docs/4.4/columns#field-nesting and if you have autoColumns: true option set, it will generate the columns
