### ISSUE TITLE
Hidden Columns and Popup

### ISSUE THREAD

**Issue by simonwatz** [olifolkerd/tabulator#1250]
Hi,

I can't seem to figure out how to do this, let alone if it is possible?

I have 4 columns that I have hidden at the end of the table and would like to add a column with just an icon that if you hover over it or press it it will show the values of the other 4 columns.

Is this possible?

Thanks

**Comment by olifolkerd** [comment]
Hey @simonwatz 

Have a look at the [Formatting Documentation](http://tabulator.info/docs/3.5#formatting) there is a section called "Icon/Button Columns" that explains exactly how to do this.

I hope that helps,

Cheers

Oli :)

**Comment by simonwatz** [comment]
Hey @olifolkerd 

Thanks for getting back to me, I had managed to get that far previously but was trying to get a hover working  like so using SemanticUI or something similar:

https://semantic-ui.com/modules/popup.html#/examples

Apologies if I am missing something obvious

Thanks

**Comment by olifolkerd** [comment]
Hey @simonwatz 

You would need to use a custom formatter to achieve that, setup the hover element according to the documentation for the hover library you are using and return the element from the function.

Cheers

Oli :)
