### ISSUE TITLE
Changing table's look and feel

### ISSUE THREAD

**Issue by Pranav-Rastogi** [olifolkerd/tabulator#1252]
Is there a way to change the look and feel of the table to something like this?
![How I want my table to look](https://preview.ibb.co/gxSc6o/Whats_App_Image_2018_07_01_at_11_06_42_PM.jpg)

**Comment by olifolkerd** [comment]
Hey @Pranav-Rastogi 

You can restyle the table in anyway you like using CSS.

The [Classes and Styling Documentation](http://tabulator.info/docs/3.5#css) has a full description of all the classes applied to the various Tabulator elements, you just need to override these with your own styles.

I hope that helps,

Cheers

Oli :)

**Comment by Pranav-Rastogi** [comment]
Thanks, @olifolkerd, I'll try it out and revert at the latest possible.

**Comment by Pranav-Rastogi** [comment]
@olifolkerd This worked for me so I would be closing this issue.

Thanks.
