### ISSUE TITLE
header formatter

### ISSUE THREAD

**Issue by haddady** [olifolkerd/tabulator#1253]
Hello over there !! 

it should be great  to add icons to cols headers and also to customize their fg and bg 

Thanks very much.

**Comment by olifolkerd** [comment]
Hey @haddady 

The good news is you can already do all of this.

You can pass html into the ***title*** property of a column definition to add additional elements to the column headers.

The background and foreground colors can be managed using CSS (as can all of Tabulators theming) you can use the ***.tabulator-col*** class to style these.

I hope that helps,

Cheers

Oli :)

**Comment by haddady** [comment]
Thank you so much Oil,
