### ISSUE TITLE
Multiple cells edit 

### ISSUE THREAD

**Issue by freaklaw** [olifolkerd/tabulator#1254]
Hi,

i was wondering if there is any option to have one button outside of the table which could change all visible (after filtering) cells to a single value?

For example:
Each row is a salary of a worker for his work done each month. Like 10 rows for each worker (different tasks). So i filter results only for Worker 1, filter date range for previous month, and i have column named "status" where i would like to change status to "Payment received" for all of 10 at once.

At this moment i have this "status" column editable with select options and it triggers the ajax call to mysql and it works ok, but i dont want to manualy change every single row. 

Is there anyway to do it for multiple rows at once (only those rows, which are visible after filtering)?

**Comment by olifolkerd** [comment]
Hey @freaklaw 

as long as you have a unique index property (id by default) on each of your rows, you can use the ***updateData*** function to achieve this,

You need to pass in an array of row data objects that contain the property for the row index and then any fields you wish to update:

```js
$("#example-table").tabulator("updateData", [{id:1, name:"bob", gender:"male"}, {id:2, name:"Jenny", gender:"female"}]);
```

Cheers

Oli :)
