### ISSUE TITLE
Losing Scroll Position when adding data using virtual DOM (height: "100%")

### ISSUE THREAD

**Issue by TomSmartBishop** [olifolkerd/tabulator#1255]
I menationed this issue in https://github.com/olifolkerd/tabulator/issues/1220 , however since is a new issue I will post it here:

I'm creating a table with height 100% and then insert data with "addData". Unfortunately this will reset the scrollbar and I  end up at the top of the page. For Edge I can remember the scroll position and just restore it after adding the data (with seme jquery), but for other browser that doesn't work.

Any body hit this problem before?

**Comment by maheshkrishnappa** [comment]
Even I am facing the same problem. It would be of great help if someone could provide a solution for this problem.

**Comment by slobqi** [comment]
I have came across the same issue which it keep scrolling to the top of the page after data insert.

**Comment by olifolkerd** [comment]
Hey Guys,

Sorry to hear you are experienceing this issue,

I am currently working on version 4.0 of Tabulator and completely rebuilding the rendering system so i hope to have this fixed for you then.

Im running a bit behind on the 4.0 release but it should be out by the end of August.

Cheers

Oli :)
