### ISSUE TITLE
Datetime sort with momentjs not working

### ISSUE THREAD

**Issue by JStirland** [olifolkerd/tabulator#1256]
Apologies if I'm missing something but i can't seem to get datetime sorters to work. I don't get an error but the data isn't sorted. All other sorters work correctly.

I am initialising the column in my table as below:

   {
         title: "Date Enrolled", 
         field: "endate", 
         sorter: "datetime", 
         sorterParams: { format: "DD/MM/YYYY HH:mm:ss" }, 
         formatter: function (cell, formatterParams) {
                   return moment(cell.cell.value).format('DD/MM/YYYY HH:mm:ss')
                }
   }

Can anyway point out where i'm going wrong please?

Thanks in advance!

**Comment by mrslayer01** [comment]
Might need to check your formatter,

try

formatter: function (cell, formatterParams) {
return moment(cell.**getData()**.value).format('DD/MM/YYYY HH:mm:ss')
}

**Comment by olifolkerd** [comment]
Hey @JStirland 

@mrslayer01 is correct that your formatter code needs tweaking, but that is not the reason your sorter is not working.

The formatter only affects the way that data is displayed in the table, it does not affect the data itself.

The sorter will work on the un-formatted data that was passed into Tabulator, so you need to make your sorter params match that.

I hope that hels,

Cheers

Oli :)
