### ISSUE TITLE
jsPDF multiple tables question

### ISSUE THREAD

**Issue by mrslayer01** [olifolkerd/tabulator#1257]
Hey Oli,

I'm trying to display two different tables with different data, in a single pdf document.

I have tried following the documentation, but it does not say anything about multiple tables that i can see.

I have also seen, and tried to follow this post, but I assume this method is now out dated. https://github.com/olifolkerd/tabulator/issues/666

here is a jsfiddle I threw together.

https://jsfiddle.net/z7vbh5j2/65/

Any ideas?

**Comment by olifolkerd** [comment]
Hey @mrslayer01 

At the moment, multi table download is only available in the excel download function. but it will be coming in a later release.

At the moment your best bet would be to retrieve the data from each table using the ***getData*** function and manually build the PDF yourself.

If you have a look in the /src/js/extensions/download.js file you will see how the inbuilt pdf downloader works and can copy that.

I hope that helps,

Cheers

Oli :)

**Comment by mrslayer01** [comment]
Looking into that now.

Thank you very much Oli!
