### ISSUE TITLE
Create table from more then one HTML Table Element

### ISSUE THREAD

**Issue by kurtknippschild** [olifolkerd/tabulator#126]
Hi Oli, 

I have a problem with create from HTML-Element.
In my example index_3.html there are two tables and the generation of the tables are wrong.
The first table has too many rows and the second table has also the columns and rows from the first table.
[aktivitaeten_tabulator.zip](https://github.com/olifolkerd/tabulator/files/641606/aktivitaeten_tabulator.zip)

What can I do.

MG Kurt

**Comment by olifolkerd** [comment]
Looking into it, there appears to be an issue with the way Tabulator is handling the construction of multiple tables. I will have a loo into it over the next couple of days for you.

Thanks for letting me know

Cheers

Oli

**Comment by olifolkerd** [comment]
There was an issue with array pointers not being reset when tabulators were built from HTML table elements.

I have just committed a fix for this, if you pull down the latest version you should be all good.

Thanks for pointing out the issue

Oli

**Comment by bipushosti** [comment]
Hi Oli,

I have the same issue with the newest version(3.3). Is there something that I should do to make sure this does not happen?

Thanks.

**Comment by olifolkerd** [comment]
could you post a copy of your table constructors please

**Comment by rri195** [comment]
I have the same issue, you can see example here
https://jsfiddle.net/odmg2wnd/5/
