### ISSUE TITLE
editable cell in Firefox is too slow

### ISSUE THREAD

**Issue by kreamas** [olifolkerd/tabulator#1261]
Hi.

I've developed a javascript function to be used when the user modify a Cell which must refresh several tables.

Everything's ok when I try it with Chrome (it lasts about a half second to be executed)...my issue is when I try it with Firefox...the same action lasts about 8 seconds.

The same issue is happening to me when creating my tables...Chrome is much faster than Firefox

Is there any kind of compatibility issues when using Fireforx?

Thanks in advance

**Comment by olifolkerd** [comment]
Hey @kreamas 

Could you post a copy of your table constructor?

Are you setting a height on your tables?

could you post some details on this function that is called when a cell is modified?

Cheers

Oli :)

**Comment by kreamas** [comment]
Hi Oli

This is my table constructor (it is built dynamically with jquery):

		       		//Unidades
					$("[id='" + id1 + "']").tabulator({

						//height:"100%",

						cellEdited:function(cell){
					   	     $("#listas").addClass('wait');
							var indice = cell.getRow().getIndex();
							cambioCelda(cell, meses, indice);
					   	     $("#listas").removeClass('wait');

						},			    

					    columns:kolumna,				    

					});          


I didn't set a default height in my table

Below is a extract of the function I call when CellEddited (cambioCelda):

//Cambio de celdas
function cambioCelda(celda, meses, posicion){


	//Obtenemos el renglon
	var viejoVal = celda.getOldValue();
	var nuevoVal = celda.getValue();

	var columna = celda.getField();

	var row = celda.getRow();
	var id = celda.getElement().closest(".tabulator").attr("id");

	var valor = id.substr(id.length - 7);

	if (valor == 'nidades'){
		valor = 'Unidades'
	}


	var renglon = $("[id = '" + id + "']").tabulator("getRow", posicion).getData();

	//Lista de unidades Viejas
	var mUnitsOld = [];
	for (i = 1; i < (meses.length+1); i++){

		if (meses[i-1] == columna) {
			mUnitsOld.push(viejoVal);
		} else {
			mUnitsOld.push(parseFloat(renglon[meses[i-1]]));

		}

	}

	//Lista de valores Viejos
	var balores = $("[id = '" + id.substr(0, id.length-8) + "Valores']").tabulator("getRow", posicion).getData();
	var mValueOld = [];
	for (i = 1; i < (meses.length+1); i++){
		mValueOld.push(parseFloat(balores[meses[i-1]]));
	}



	//Unidades Pack -----------------------------------------------------------------------------------------------------------
	//Recorremos el renglon para poner la suma del elemento actual
	var renglon = $("[id = '" + id + "']").tabulator("getRow", row).getData();

	var suma = 0;
	for (i = 1; i < (meses.length); i++){
		suma = suma + parseFloat(renglon[meses[i-1]]);
	}


	//Ponemos el Total
	$("[id = '" + id + "']").tabulator("getRow", row).update({'Total':suma});

	//Lista unidades Nuevas
	var mUnitsNew = [];
	for (i = 1; i < (meses.length+1); i++){
		mUnitsNew.push(parseFloat(renglon[meses[i-1]]));
	}



	//Valores Pack -------------------------------------------------------------------------------------------------------------
	//Recorremos el renglon para multiplicar por el precio
	precioID = id.substr(0, id.length-8) + "Precios"
	valorID = id.substr(0, id.length-8) + "Valores"



	var sacaNew = $("[id = '" + id + "']").tabulator("getRow", posicion).getData();
	var mUnitsNew = [];
	for (i = 1; i < (meses.length+1); i++){
		mUnitsNew.push(parseFloat(sacaNew[meses[i-1]]));
	}



	var suma = 0;

	for (j = 1; j < (meses.length); j++){

		//var padre = parseFloat($("[id = '" + idpadre + "']").tabulator("getRow", i).getData()[meses[j-1]]);
		var unidades = parseFloat($("[id = '" + id  + "']").tabulator("getRow", posicion).getData()[meses[j-1]]);
		var precios = parseFloat($("[id = '" + precioID + "']").tabulator("getRow", posicion).getData()[meses[j-1]]);


		var valores = unidades * precios;

		columnasBasico(j, valorID, posicion, valores);

	}


	var renglon = $("[id = '" + valorID + "']").tabulator("getRow", posicion).getData();
	var mValueNew = $("[id = '" + valorID + "']").tabulator("getRow", posicion).getData();



	var suma = 0;
	for (i = 1; i < (meses.length); i++){
		suma = suma + parseFloat(renglon[meses[i-1]]);
	}

	//Ponemos el Total
	$("[id = '" + valorID + "']").tabulator("getRow", posicion).update({'Total':suma});


	//Lista de valores Nuevos
	var balores = $("[id = '" + valorID + "']").tabulator("getRow", posicion).getData();

	var mValueNew = [];
	for (i = 1; i < (meses.length+1); i++){
		mValueNew.push(parseFloat(balores[meses[i-1]]));
	}



	//Sumamos hacia los padres Unidades y Valores-------------------------------------------------------------------------------------------------------------

	for (k =1; k < 3; k++){


		if (k == 1){
			var metrica = "Unidades";
			var usarOld = mUnitsOld;
			var usarNew = mUnitsNew;
		} else {
			metrica = "Valores"
			var usarOld = mValueOld;
			var usarNew = mValueNew;
		}

		for (j = 1; j < 5; j++){

			if (j == 1){
				var miID = "Mercado";
			} else if (j == 2) {
				var miID = "Laboratorio";
			} else if (j == 3) {
				var miID = "Familia";
			} else {
				var miID = "Producto";
			}

			//alert(miID + metrica);

			var datines = $("[id = '" + miID + metrica + "']").tabulator("getRow", posicion).getData();
			var datoNuevo = [];

			for (i = 1; i < (meses.length+1); i++){
				datoNuevo.push(parseFloat(datines[meses[i-1]]));
			}


			for (i = 1; i < (meses.length+1); i++){


				//var padre = parseFloat($("[id = '" + idpadre + "']").tabulator("getRow", i).getData()[meses[j-1]]);
				var padreActual = parseFloat(datoNuevo[i-1]);
				var hijosAnterior = parseFloat(usarOld[i-1]);
				var hijosActual = parseFloat(usarNew[i-1]);

				var valores = padreActual - hijosAnterior + hijosActual;

				columnasBasico(i, miID+metrica, posicion, valores);

			}

		}

	}

I don't know if this is helpful...I can share my whole code with you.

I can't realize why Firefox is behaving that way.  Do you have any idea?

**Comment by olifolkerd** [comment]
Hey @kreamas 

If your tables do not have a height the virtual DOM will not be enable so the tables will be trying to render all of the rows at once which will slow things down.

Chrome has much faster JavaScript and rendering engines that Firefox which is why this will be causing you issues depending on how many tables and rows you are trying to update at once.

Cheers

Oli :)
