### ISSUE TITLE
Virtual DOM not rendering all rows in 3.5.3

### ISSUE THREAD

**Issue by GregAC** [olifolkerd/tabulator#1262]
I think I've seen this issue: https://github.com/olifolkerd/tabulator/issues/887 crop up again in 3.5.3

The problem is in firefox for a simple table that generates a vertical scroll bar not all of the rows actually get rendered, resizing the browser window or bringing up the developer console often fixes it.

In 3.4.6 I do not see this issue

I've got a couple of code pens that demonstrate the problem:

https://codepen.io/anon/pen/PBwEgJ?editors=1000 - v3.4.6 - Renders properly in firefox 
https://codepen.io/anon/pen/VBYQLP?editors=1000 - v3.5.3 - Rendering broken in firefox

I've just taken the basic getting started example added height: 100% to body and HTML (as recommended in #887), replicated the data a few times so there's lots of rows and increased height to 600 from 200

I'm using firefox version 61.0.1

**Comment by olifolkerd** [comment]
Hey @GregAC 

try adding this after your table constructor:

```js
 $("#example-table").tabulator("redraw", true);
```

Cheers

Oli :)

**Comment by GregAC** [comment]
Great thanks for the suggestion.

I've noticed another oddity.  If you use the "fitData" or "fitDataFill" option for layout then it initially only fits the columns to the originally visible rows (before the first redraw) when you add a second redraw it fits the columns to all of the rows.

Another code pen to demonstrate: https://codepen.io/anon/pen/vaOKGa?editors=1000

If you comment/uncomment the second redraw you'll see the differing layout behaviour

Cheers

Greg

**Comment by olifolkerd** [comment]
Hey Greg,

are you finding this happens outside of codepen, it happens in code pen because of the way the it renders the page, if you try this in a blank HTML document with nothing else do you still experience the issue?

Cheers

Oli :)
