### ISSUE TITLE
rowMoved and new rows order list

### ISSUE THREAD

**Issue by emeggiolaro** [olifolkerd/tabulator#1263]
Hi, I'm a newbie.
When I change row order by using drag & drop, how can I retrieve update ID (==index) array ordered? 
If I could get this new order I could pass it to a php script and save new rows order (e.g. using a custom field show_index in my DB table).
Thanks

**Comment by olifolkerd** [comment]
Hey @emeggiolaro 

Thanks for getting in touch.

you are looking for the row position, you can call the ***getPosition*** function on the row component that is passed into the ***rowMoved*** callback.

```js
$("#example-table").tabulator({
    rowMoved:function(row){
        //row - row component

        var pos = row.getPosition();
    }
});
```

The id/index of the row is something that you set to help link data back to records in your database and is not altered by Tabulator.

I hope that helps

Cheers

Oli :)

**Comment by infspiredBAT** [comment]
Is there anyway to get the old row position, or the rows affected?

**Comment by olifolkerd** [comment]
Hey @infspiredBAT 

Im afraid this is not possible once the row has been moved, you could look at using the ***rowMouseEnter*** callback to get the position of the row before it is moved, then access that on ***rowMoved***

Cheers

Oli :)

**Comment by scry-UrjitDesai** [comment]
I tried using the rowMouseEnter way, but the rowMouseEnter gets triggered every time you move over a row even while dragging over other rows. How can I get the initial and the final position of the row on rowMoved ?
