### ISSUE TITLE
how to deselect all selected rows/rows on an button event.

### ISSUE THREAD

**Issue by prk53** [olifolkerd/tabulator#1264]
while creating the tabulator i keep the "selectable:true", i want to deselect all the selected rows on a button click event.

i tried doing
onbuttonclick=function()
{
 var selectedRows=$("#table-name").tabulator("getSelectedRows");
      for(var i=0;i<selectedRows.length;i++)
      {
           selectedRows[i].deselect();
//or i tried using below also both(above one and below one not working;
   selectedRows[i].toggleSelect();
       }

}

**Comment by Nyut0n** [comment]
The function looks right to me. Are you sure your button click event fires properly?
You could add a console.log(selectedRows) after the variable assignment to check what it contains and whether that piece of code gets executed at all.
