### ISSUE TITLE
Configuring data without mentioning columns

### ISSUE THREAD

**Issue by aditya-thimphu** [olifolkerd/tabulator#1265]
Hi,
Is it possible to set data from a Json data without mentioning columns? My columns are dynamically generated, so wouldn't know the field names. Basically I want to display all data with default settings.

Thanks,
Aditya

**Comment by olifolkerd** [comment]
Hey @aditya-thimphu 

You can set data and columns at any time using the ***setColumns*** and ***setData*** functions.

Creating a table without columns will look empty though.

Cheers

Oli :)
