### ISSUE TITLE
Suggestion for new column callback

### ISSUE THREAD

**Issue by Nyut0n** [olifolkerd/tabulator#1267]
Hey @olifolkerd ,

I'd like to toss in a suggestion for a new column callback. This new callback should run after the cell and its contents were added to the DOM.
This would be handy whenever you try to add cells that contain certain JQuery-UI widgets. For instance, the [ui-spinner](https://jqueryui.com/spinner/) constructor won't work if the target element isn't in the DOM yet. So you can't create an input element and turn it into a ui-spinner through a formatter function. You need to make sure that the input is already in the DOM before running the constructor. Running the spinner constructor after the Tabulator constructor doesn't work as well, because any table resize, page change or scrolling through the virtual dom will break the spinner.

This is the formatter function I'm using right now to have an ui-spinner in a cell that edits table data on-the-fly:
```javascript
function spinnerCellFormatter( cell ) {
	var input = $("<input>").val( cell.getValue() );
	new MutationObserver( function() {
		if( document.contains(input[0]) ) {
			input.spinner( {
		                // Set some options based on cell data
		                // ...
				change: function() {
					$(this).stop();
				},
				stop: function() {
					cell.setValue( parseInt($(this).val()), false );
				}
			} );
			this.disconnect();
		}
	} ).observe( document, {
		attributes: false,
		childList: true,
		characterData: false,
		subtree:true
	} );
	return input;
}
```

This is how I'd prefer to do it:
```javascript
function spinnerCellFormatter( cell ) {
	return input = $("<input>").val( cell.getValue() );
}
function newFancyCallbackFunction( cell ) {
	var cellElement = cell.getElement();
	cellElement.find("input").spinner( {
		// Set some options based on cell data
		// ...
		change: function() {
			$(this).stop();
		},
		stop: function() {
			cell.setValue( parseInt($(this).val()), false );
		}
	} );
}
```

I'm sure you could use [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) to implement such callback. It's compatible with all modern browsers and even IE11.

Let me know what you think :)
Cheers

**Comment by olifolkerd** [comment]
Hey @Nyut0n,

That is a great idea, that feature is already in for editors as an onRendered function that is passed into the call back, I will add the same functionality to the formatters.

I will schedule that for the 4.0 release

Thanks

Oli :)

**Comment by olifolkerd** [comment]
Hey @Nyut0n 

I have just added this on the 4.0 branch and will include it in this weekends release.

Cheers

Oli :)
