### ISSUE TITLE
New Layout Possibility & Other Idea

### ISSUE THREAD

**Issue by jwb12345** [olifolkerd/tabulator#1268]
Hi,

I was wondering if it would be possible to create a new couple of layouts: fitDataAndHeaders and fitDataAndHeadersFill.  I use both fitData and fitDataFill, but often my headers are wider than the widest column and the header gets truncated.

Also, I'm curious if you have considered adding the ability to create a matrix where in addition to column headers the user defines row headers.  Where the contents of column 1 are Row Headers that have all of the same functions as column headers.  The user would be able to filter columns, sort columns, etc.  It would be really cool if the user also had the ability to swap the orientation of the matrix switching the row headers to be column headers and the column headers to be row headers.  Does that make sense?

Thanks so much.

**Comment by olifolkerd** [comment]
Hey @jwb12345 

Thanks for getting in touch, sorry for the delay in getting back to you.

The fitData layout functions should also respect the width of the header as well, if not then that is a bug and i would ask if you can include a copy of your table constructor so i can look into fixing that.

As for the row header functionality you are after, at the moment you could achieve some basic functionality like that with a custom formatter and some use of the click events.

The idea for a side justifiable set of headers is an interesting one, but it would also be incredibly difficult to implement and likely need a complete ground up rebuild of tabulator as it is simply not designed to function in that way.

I may have a look into it later down the line as the concept is interesting but im afraid it would be making an appearance on the roadmap for at least a year.

Thanks for the suggestions, let me know if you have any other ideas.

Cheers

Oli :)
