### ISSUE TITLE
Issues with colors

### ISSUE THREAD

**Issue by zjwelch** [olifolkerd/tabulator#1273]
I believe there may be a bug with the color formatter. Also at the end is a suggestion for improvement here.

Issue is that declaring the '\[formatter:"color"] option in the column declaration, but not declaring a color seems to make all data in that column not appear. I tried various ways in attempts to understand how it works (the documentation for this option could be much better), and the only correction was to completely remove the formatter option, refresh and try again.

Here is a code example:
```
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
		<script src="https://www.gstatic.com/charts/loader.js"></script>
		<link href="https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.5.3/css/tabulator.min.css" rel="stylesheet">
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.5.3/js/tabulator.min.js"></script>	
code omitted

<div class="chart">
	<div id="ajaxTable"></div>
</div>
		<script type="text/javascript">
		
			$("#ajaxTable").tabulator({
				
			  fitColumns:true,
			  columns:[
				{title:"Period", field:"date", sortable:false, width:100 },
				{title:"6.20", field:"620", sortable:false },
				{title:"6.30", field:"630", sortable:false },
				{title:"7.20", field:"720", sortable:false },
				{title:"7.30", field:"730", sortable:false },
				{title:"Redlines", field:"redline", sortable:false, width:100 },
				{title:"Redesigns", field:"redesign", sortable:false, width:100 },
				{title:"Vertek", field:"vertek", sortable:false, width:100 },
				{title:"Totals", field:"total", sortable:false, formatter:"color" }
			  ],
			});

			var sampleData = [
			  {date:"Jan", 620:"1043", 630:"23", 720:"66", 730:"63", redline:"35", redesign:"1", vertek:"38", total:"1109" },
			  {date:"Feb", 620:"652", 630:"18", 720:"47", 730:"47", redline:"24", redesign:"0", vertek:"52", total:"699" },
			  {date:"Mar", 620:"875", 630:"59", 720:"56", 730:"56", redline:"27", redesign:"0", vertek:"144", total:"942" },
			  {date:"Q1 AVG", 620:"857", 630:"33", 720:"55", 730:"55", redline:"29", redesign:"0", vertek:"78", total:"917" },
			  {date:"Apr", 620:"913", 630:"38", 720:"82", 730:"63", redline:"43", redesign:"2", vertek:"144", total:"995" },
			];

			$("#ajaxTable").tabulator("setData", sampleData);

			$(window).resize(function(){
			  $("#ajaxTable").tabulator("redraw");
			});
</script>
	</body>
```

Add formatter:"color" to any column for the issue to present.
![image](https://user-images.githubusercontent.com/28605977/42717248-b2930d6e-86cd-11e8-83b2-7bc4349cad48.png)

** Also, a suggestion for future. Since the color choice issue seems to be very clunky, and I would imagine most people using this for responsive dynamic charting would want to play with colors, it might make sense to have some styling features "always available", as if the formatter:"XYZ" for that style option was on by default and/or including the style option in the formatter declaration. Also coloring the text itself would be a welcome addition.

This could be accomplished for columns in a model where [formatter:"color:#AABBCC"] was acceptible. Or in rows by those formatters in default "on" status, and simply checking for an instance of "text-color:#AABBCC" or similiar in the associative data array for that row.

Obviously these should be able to be toggled back to off for those who want to save on memory/load time issues.  Thank you for the consideration of these ideas.

**Comment by olifolkerd** [comment]
Hey @zjwelch 

Thanks for getting in touch,

The formatter is working correctly, the problem you are having is that you are not passing a valid color value in the ***total*** filed which you have specified to use the color formatter. to use this formatter the value of that property must be a valid css colour ***eg, #ff0000, #f00, rgb(255,0,0), red, rgba(255,0,0,0), hsl(0, 100%, 50%)***

An example of the color formatter in action can be seen [here](http://tabulator.info/examples/3.5#formatters)

if all you want to do is color that column a particular color then i would suggest using CSS to style the background color of the cell.

```css
.tabulator .tabulator-cell [tabulator-field="total"]{
    background-color:red;
}
```

I hope that helps,

Cheers

Oli :)
