### ISSUE TITLE
blob for php

### ISSUE THREAD

**Issue by ryhill** [olifolkerd/tabulator#1275]
Hi Oli,

I am getting the blob like below.

     var dataObj = {
     imageData:blob,
     emails:email_to ,
     subject:report_title
     }

     $.post( "export.php", dataObj );
     
I wanted to pass the BLOB to a php function in the same page without POSTING to another page.
Tabulator extensions can help??

I am trying to implement tabulator in cron job. Any directions will be of great help

Thanks

KIRAN

**Comment by olifolkerd** [comment]
Hey Kiran,

PHP code is handled server side so there is no way to handle that in PHP on the client, you would need to post it back to the server to be handled there.

I hope that helps,

Cheers

Oli :)
