### ISSUE TITLE
Export to excel not working

### ISSUE THREAD

**Issue by nwoow** [olifolkerd/tabulator#1276]
I am trying to load table data onclick method I am fetching data from api call each time I am calling a new data and displaying it to my table for that I am using this code:
`        

         var j = $( "#example-table" ).hasClass( "tabulator" ) 
          if (j) {
            $("#example-table").tabulator("destroy");
           
   
          }
          $("#example-table").tabulator({
            layout:"fitColumns"});
         
          //set new columns
          $("#example-table").tabulator("setColumns", res["column"]);
          
          //set new data
          $("#example-table").tabulator("setData", res["data"]);

          $("#download-xlsx").click(function(){
            $("#example-table").tabulator("download", "xlsx", "data.xlsx");
          });
      
          $("#download-csv").click(function(){
            $("#example-table").tabulator("download", "csv", "data.csv");
        });
        
        //trigger download of data.json file
        $("#download-json").click(function(){
            $("#example-table").tabulator("download", "json", "data.json");
        });`

And in my html I am using this code:

    
            `  <button class ="table-button" id ="download-xlsx">Download XLSX</button>
          <button class ="table-button" id ="download-csv">Download CSV</button>
         <button class ="table-button" id ="download-pdf">Download PDF</button>
          <button class ="table-button" id ="download-json">Download JSON</button>

         <div id="example-table" style="margin-bottom: 100px; margin-top: 30px;" ></div>
                 </div>`

As you can see I can show my data but the problem is when I am loading data onclick for example three times it download three files my question is how can I empty tabulator download data each time when I click.

**Comment by olifolkerd** [comment]
Hey @nwoow 

I think the issue is that you are putting your download click bindings inside the function that handles the request for data, so a new binding is created every time the data is loaded, if you put them outside this function it should work fine.

you also shouldnt be instantiating your table in this binding, you only need to create it once, you can then update the settings whenever you like.

I hope that helps,

Cheers

Oli :)

**Comment by nwoow** [comment]
I am putting this code:

`  $("#download-xlsx").click(function(){
    $("#example-table").tabulator("download", "xlsx", "data.xlsx");
  });
  
  $("#download-csv").click(function(){
    $("#example-table").tabulator("download", "csv", "data.csv");
  });
  
  //trigger download of data.json file
  $("#download-json").click(function(){
    $("#example-table").tabulator("download", "json", "data.json");
  });`

Outside the function which is calling my ajax data but same thing is happening. In my case data can be loaded multiple times. I want to know how this can be reset each time a click event is happening.
