### ISSUE TITLE
Table returns no data when clearing header range filters

### ISSUE THREAD

**Issue by jjames344** [olifolkerd/tabulator#1277]
Hi there!
I have a working date range filter as a table header filter. Inputting dates works just fine, however when I clear either date filter or click off the date filter without inserting dates into it, the table returns no data.

I have tried to 'setData' when the filter value isn't valid, however this still doesn't seem to work.

Any ideas to get around this would be extremely helpful! I've included the code for the date range filters below.

Thanks.

`

            var minMaxFilterEditor = function (cell, onRendered, success, cancel, editorParams) {

                var container = $("<span></span>")

                //create and style inputs
                var start = $("<input type='number' placeholder='Min' min='0' max='100'/>");
                var end = $("<input type='number' placeholder='Max' min='0' max='100'/>");

                container.append(start).append(end);

                var inputs = $("input", container);

                inputs.css({
                    "padding": "4px",
                    "width": "50%",
                    "box-sizing": "border-box",
                })
                    .val(cell.getValue());

                function buildValues() {
                    return {
                        start: start.val(),
                        end: end.val(),
                    };
                }

                //submit new value on blur
                inputs.on("change blur", function (e) {
                    success(buildValues());
                });

                //submit new value on enter
                inputs.on("keydown", function (e) {
                    if (e.keyCode == 13) {
                        success(buildValues());
                    }

                    if (e.keyCode == 27) {
                        cancel();
                    }
                });

                return container;
            }

            //custom max min filter function
            function minMaxFilterFunction(headerValue, rowValue, rowData, filterParams) {
                //headerValue - the value of the header filter element
                //rowValue - the value of the column in this row
                //rowData - the data for the row being filtered
                //filterParams - params object passed to the headerFilterFuncParams property

                if (rowValue) {
                    if (headerValue.start != "") {
                        if (headerValue.end != "") {
                            return rowValue >= headerValue.start && rowValue <= headerValue.end;
                        } else {
                            return rowValue >= headerValue.start;
                        }
                    } else {
                        if (headerValue.end != "") {
                            return rowValue <= headerValue.end;
                        }
                    }
                }

                return false; //must return a boolean, true if it passes the filter.
            }

            //custom header filter
            var dateFilterEditor = function (cell, onRendered, success, cancel, editorParams) {

                var container = $("<span></span>")
                //create and style input
                var start = $("<input type='date' placeholder='Start' />");
                var end = $("<input type='date' placeholder='End'   />");

                container.append(start).append(end);

                var inputs = $("input", container);

                inputs.css({
                    "padding": "4px",
                    "width": "50%",
                    "box-sizing": "border-box",
                })
                    .val(cell.getValue());

                function buildDateString() {
                    return {
                        start: start.val(),
                        end: end.val(),
                    };
                }

                //submit new value on blur
                inputs.on("change blur", function (e) {
                    success(buildDateString());
                });

                //submit new value on enter
                inputs.on("keydown", function (e) {
                    if (e.keyCode == 13) {
                        success(buildDateString());
                   cancel();
                    }

                    if (e.keyCode == 27) {
                        cancel();
                    }
                });

                return container;
            }

            //custom filter function
            function dateFilterFunction(headerValue, rowValue, rowData, filterParams) {
                //headerValue - the value of the header filter element
                //rowValue - the value of the column in this row
                //rowData - the data for the row being filtered
                //filterParams - params object passed to the headerFilterFuncParams property

                var format = filterParams.format || "DD/MM/YYYY";
                var start = moment(headerValue.start);
                var end = moment(headerValue.end);
                var value = moment(rowValue, format)
                if (rowValue) {
                    if (start.isValid()) {
                        if (end.isValid()) {
                            return value >= start && value <= end;
                        } else {
                            return value >= start;
                        }
                    } else {
                        if (end.isValid()) {
                            return value <= end;
                        }
                    }
                }

                return false;//must return a boolean, true if it passes the filter.

            }`

**Comment by olifolkerd** [comment]
Hey @jjames344 

The issue you have is that your filter function is returning false when the value of the filter is empty, this means it is failing every row so none are displayed. to get the functionality you are after your filter function should return true if the filter value is empty.

I hope that helps,

Cheers

Oli :)

**Comment by jjames344** [comment]
Thanks Oli!
