### ISSUE TITLE
Column Header Maximize Problems

### ISSUE THREAD

**Issue by drewmarshburn** [olifolkerd/tabulator#1278]
Although I am using an old (and customized) version of Tabulator, from what I can see this issue might still be present in the current version. When double clicking a divider to maximize a column, it does not properly get the width of the column header. I think it is due to [this line](https://github.com/olifolkerd/tabulator/blob/master/dist/js/tabulator.js#L2178) because that affects the header, whereas you have updated all of the column values to use [this](https://github.com/olifolkerd/tabulator/blob/master/dist/js/tabulator.js#L5486) (and commented out the previous version right above, the one still applied to the header). 

For the behavior we wanted, I added a different function to maximize the headers because we liked the collapsed headers as the table loads (makes large tables cleaner). It's essentially just the relevant parts of reinitializeWidth() and fitToData() thrown together. I'd be happy to pass it along if you want.

**Comment by drewmarshburn** [comment]
Actually, I spoke too soon. I had to approximate the proper maximum. This is probably not an elegant way to do it, but it works:
```javascript
      //Go thru the children and see how much space should be allocated
      for (var i = 0; i < this.element[0].children.length; i++) {
        var child = this.element[0].children[i];
        if (child.className === 'tabulator-col-content') {
          // Compute ideal length of header
          var canv = document.createElement('canvas');
          var ctx = canv.getContext('2d');
          ctx.font = this.element.css("font-size") + ' ' + this.element.css("font-family");
          maxWidth += ctx.measureText(child.innerText).width
        } else {
          maxWidth += child.clientWidth;
        }
      }
```

**Comment by olifolkerd** [comment]
Hey @drewmarshburn 

Would you be able to create a JS fiddle or a code pen that demonstrates your issue with appropriate data so i can understand it better.

Many Thanks

Oli :)
