### ISSUE TITLE
Vertical column header text orientation

### ISSUE THREAD

**Issue by aditya-thimphu** [olifolkerd/tabulator#1280]
Hi,

Is it possible to have vertical column header for some columns (header text rotated by 90 or 270 degrees)? I tried using css class and css, it works but it doesn't automatically adjust height/width of the header and the column. If this feature isn't there inbuilt, any other workaround solution will be appreciated.

Thanks,
Aditya

**Comment by olifolkerd** [comment]
Hey @aditya-thimphu 

At the moment this isnt possible, but it is on the roadmap to be released in the next couple of versions.

Cheers

Oli :)
