### ISSUE TITLE
How to Enable Tabulator Controls

### ISSUE THREAD

**Issue by trabalhotemporario** [olifolkerd/tabulator#1281]
In the first example on page tabulator.info has a "Filter Table By Name" field. How can I create this option?

**Comment by olifolkerd** [comment]
Hey @trabalhotemporario 

The [Filters Example](http://tabulator.info/examples/3.5#filter) has a demo of this in action along with sample code.

essentially you add an input element above the table element an then use ***change*** and ***keyup*** bindings to trigger the ***setFilter*** function on the table.

I hope that helps,

Cheers

Oli :)

**Comment by deva2010** [comment]
please give me the tutorial
