### ISSUE TITLE
Overwrite file during download

### ISSUE THREAD

**Issue by RuchiTrehan** [olifolkerd/tabulator#1283]
Can we overwrite file when a download as JSON functionality is called ? What i see right now it always make a new file appended with index when the file already exists.
Or how can we write the updated table in a json file ?

**Comment by olifolkerd** [comment]
Hey @RuchiTrehan 

Im afraid that has nothing to do with Tabulator, that is how your browser/operating system handle file downloads when the name of the file already exists in download directory.

Cheers

Oli :)
