### ISSUE TITLE
Documentation error: getFilter

### ISSUE THREAD

**Issue by diegoleonuy** [olifolkerd/tabulator#1287]
In the documentation says:
	`var filters =   $("#example-table").tabulator("getFilters");`
But you must say:
	`var filters = $("#example-table").tabulator("getFilter");`

Thank you for your work

**Comment by olifolkerd** [comment]
Hey @diegoleonuy 

Thanks for getting in touch, Could you let me know where in the documentation is mentions that, i will get it fixed ASAP.

Cheers

Oli :)

**Comment by diegoleonuy** [comment]
http://tabulator.info/docs/3.5#filtering
Additional Filter Functions
Get Current Filters

**Comment by olifolkerd** [comment]
Hey @diegoleonuy,

I am afraid you are mistaken there, as of version 3.5 the correct function is ***getFilters***, it used to be ***getFilter*** in previous versions.

Cheers

Oli :)
