### ISSUE TITLE
How do I prevent high memory usage when returning large data sets?

### ISSUE THREAD

**Issue by AbsAlnaffakh** [olifolkerd/tabulator#1288]
Hi Oli,

Thanks again for this awesome library.

I am having to deal with large amount of data to be displayed within the Tabulator grid, and am trying to utilise everything it offers to prevent performance degredation such as Virtual DOM, progressive Ajax Loading(Pagination) etc..

But when the amount of available rows reaches the 4000 mark it tends to cause issues where the memory consumed by the browser rises to about 1.5 GB and as a result the browser becomes very sluggish.

Is there anything I can do to prevent this from happening?

P.S: I am still going to submit those additional features in compliance with your feedback to my previous pull request.

Best Regards,
Abs

**Comment by olifolkerd** [comment]
Hey @AbsAlnaffakh 

I have had the table running with 100,000's of rows with no issue.

Could you post a copy of your table constructor so i could offer more specific advice.

Cheers

Oli :)

**Comment by AbsAlnaffakh** [comment]
Hi Oli,

Thanks for the reply.

Here you go:

$("#memberships-grid").tabulator({
        layout: "fitColumns",
        height: "600px",
        ajaxURL: "/Membership/GetAll",
        ajaxProgressiveLoad: "load",
        paginationSize: 30,
        placeholder: "No Data Set",

        columns: [
            { title: "VRM", field: "registration", editor: "input", headerFilter: "input" },
            { title: "Category", field: "categoryname", editor: "input", headerFilter: "input" },
            { title: "Value Remaining", field: "valueremaining", editor: "input", headerFilter: "input" },
            { title: "Visis Remaining", field: "visitsremaining", editor: "input", headerFilter: "input" },
            { title: "Id", field: "membershipid", editor: "input", headerFilter: "input" },
            { title: "Title", field: "title", editor: "input", headerFilter: "input" },
            { title: "Initials", field: "initials", editor: "input", headerFilter: "input" },
            { title: "Surname", field: "surname", editor: "input", headerFilter: "input" },
            { title: "Address", field: "address", editor: "input", headerFilter: "input" },
            { title: "Postcode", field: "postcode", editor: "input", headerFilter: "input" },
            { title: "Contact No", field: "telno", editor: "input", headerFilter: "input" },
            { title: "Email", field: "email", editor: "input", headerFilter: "input" },
            { title: "Valid", field: "valid", editor: "input", headerFilter: "input" },
            { title: "Start Time", field: "starttime", editor: "input", headerFilter: "input" },
            { title: "Expiry Time", field: "expirytime", editor: "input", headerFilter: "input" },
            { title: "Notes", field: "notes", editor: "input", headerFilter: "input" },
        ],
    });

**Comment by AbsAlnaffakh** [comment]
I think it might be because I am not specifying pagination as remote:

`pagination:"remote"`

**Comment by olifolkerd** [comment]
Hey @AbsAlnaffakh 

Could you confirm which version of Tabulator you are using?

Cheers

Oli :)

**Comment by AbsAlnaffakh** [comment]
Hi @olifolkerd 

It's 3.5.3.

Best Regards,
Abs

**Comment by AbsAlnaffakh** [comment]
In the browser console window I get errors which complain about setting properties that can only be set upon table creation unless they can be set through a function later on, such as height and pagination, this make me think that it may be that I shouldn't allow for progrssive loading from within the constructer and do it after the table has been intialised but I don't see how this can be done yet.

**Comment by AbsAlnaffakh** [comment]
Hi @olifolkerd 

I was having a look at issue #1090 and was wondering if my issue was relating to the number of columns I am using therefore I have reduced them down to two but the same problem remained, I also took away removed the column filtering property but still no luck :(

Best Regards,
Abdullah

**Comment by AbsAlnaffakh** [comment]
Hi @olifolkerd 

If I don't use progressive loading and use the setData() method via an Ajax call I face none of the issues faced above, I have tried this with 10000 records so far and it seems great so far.

It is only when progressive loading is used and specified within the table constructer that I get these issues.

Is this a bug then? Or am I doing something wrong?

Best Regards,
Abs

**Comment by olifolkerd** [comment]
Hey All,

To make it easier to notify everyone of progress with the rendering system i have created one issue #1437 where i will report progress.

Cheers

Oli :)
