### ISSUE TITLE
print tabulator as pdf as it appears on the page

### ISSUE THREAD

**Issue by ryhill** [olifolkerd/tabulator#1289]
I have been using Kendo ui js to generate pdf. Hope this will be of some help who is looking to print tabulator to pdf as it lloks on the screen with filters, sorters, groupby applied.

This actually takes a screenshot of the div which tabulator hold
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.5/jspdf.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/2.3.2/jspdf.plugin.autotable.js"> 
    </script>
    <script src="https://kendo.cdn.telerik.com/2018.1.221/js/kendo.all.min.js"></script> 
    <script src="https://kendo.cdn.telerik.com/2018.2.516/js/pako_deflate.min.js"></script>

    if(export_format == 'PDF'){

    kendo.drawing.drawDOM("#mfd_canvas",{  forcePageBreak: ".page-break"})
    .then(function (group) {
    // Render the result as a PDF file
    return kendo.drawing.exportPDF(group, {
    paperSize: "auto",
    margin: { left: "1cm", top: "1cm", right: "1cm", bottom: "1cm" }
       });
    })
    .done(function (data) {
    var dataObj = {
    imageData:data ,
    emails:'ryhilltechnologies@gmail.com' ,
    subject:'Printing Tabulator in PDF''
    };
    $.ajax({
    type: "POST",
    url: "ryhill_export_pdf.php",
    data: dataObj,
    success: function() {
                 }
    });
    });
    }

in export.php

    $filenamePDF = 'test/'. time() . 'ryhill_report.pdf';
    $b64file= trim(str_replace('data:application/pdf;base64,', "", $_POST["imageData"]) );
    $b64file= str_replace( ' ', '+', $b64file);
    $decodPdf= base64_decode($b64file);
    file_put_contents($filenamePDF, $decodPdf);

**Comment by aditya-thimphu** [comment]
Hi @ryhill,

Does it also work for progressively loaded Tabulator data? I mean client side progressively loaded table where height property is set.

Thanks,
Aditya

**Comment by kiran-peddikuppa** [comment]
I haven't tested it. But yes, It should work.

**Comment by aditya-thimphu** [comment]
Hi,
I tried and it exports only what is visible on the screen, not the full report/table. I used the following code:

$("#download-pdf").click(function(){
            var draw = kendo.drawing;
            kendo.drawing.drawDOM("#report-table",{  forcePageBreak: ".page-break"})
                .then(function (group) {
                    return kendo.drawing.exportPDF(group, { paperSize: "A3", landscape: true, margin: { left: "1cm", top: "1cm", right: "1cm", bottom: "1cm" }})
                            .done(function(data) {
                                kendo.saveAs({
                                    dataURI: data,
                                    fileName: "report.pdf"
                                });
                    });
                });
        });

I am looking for a solution to print complete report as it is displayed for the the following Tabulator setting (it is client side progressively loaded table which has grouping and column calculations):

$("#report-table").tabulator({
            placeholder:"Select required parameters/filters to view report.",
            height:"600px",
            movableColumns: true,
            columnCalcs:"both",
            .........
}

**Comment by ryhill** [comment]
$("#download_pdf").click(function(){

    var initialPageSize = $("#example").tabulator("getPageSize");
    var rows = $("#example").tabulator("getDataCount");
    var groups = $("#example").tabulator("getGroups");

    $("#example").tabulator("setPageSize", rows + groups.length);
    $("#example").tabulator("redraw");
    
    kendo.drawing.drawDOM("#myCanvas", 
    {  forcePageBreak: ".page-break",

    }).then(function(group){
        kendo.drawing.pdf.saveAs(group, "mfd_report.pdf")
    });

    $("#example").tabulator("setPageSize", initialPageSize);
    $("#example").tabulator("redraw");
    
    //console.log(initialPageSize);
    //console.log(rows);
    //console.log(groups.length);

    });

            //trigger print
    $('#print_pdf').click(function() {

    var initialPageSize = $("#example").tabulator("getPageSize");
    var rows = $("#example").tabulator("getDataCount");
    var groups = $("#example").tabulator("getGroups");

    $("#example").tabulator("setPageSize", rows + groups.length);
    $("#example").tabulator("redraw");


    kendo.drawing.drawDOM("#myCanvas", 
    {   allPages: true,
        avoidLinks: true,
        paperSize: "A4",
        margin: { top: "1cm", left: "1cm", right: "1cm", bottom: "1cm" },
        landscape: true,
        repeatHeaders: true,
        scale: 0.6,
    }).then(function(group){
        kendo.drawing.pdf.saveAs(group, "mfd_report.pdf")
    });

    $("#example").tabulator("setPageSize", initialPageSize);
    $("#example").tabulator("redraw");


    });

**Comment by aditya-thimphu** [comment]
Thank you @ryhill. I think got your point, but I have a large report (around 2000 rows); redraw takes a lot of time (in minutes) and memory usage. That is why I am using progressive loading. I tried your solution, but that also takes a lot of time (made the page unresponsive). Maybe I am doing something wrong!

**Comment by olifolkerd** [comment]
Hey @aditya-thimphu 

If you have lots of data it may well take a lot of time to process into a PDF im afraid.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @aditya-thimphu  

You will be happy to hear that the print functionality has finally arrived in Tabulator!

Checkout the [Print Documentation](http://tabulator.info/docs/4.3/print) for full details

Cheers

Oli :)

**Comment by aditya-thimphu** [comment]
Hi @olifolkerd,

Thanks a lot. I already went through the documentation; I am excited about it.

Just to let you know, noticed a few typos in the documentation Release Notes; one is under the News, you have mentioned Version 4.2 instead of 4.3 release.

Thank you once again for the great package. Look forward to using the print feature.

Regards,
Aditya

**Comment by olifolkerd** [comment]
@aditya-thimphu  good spot, i was rather tired when i wrote that bit, i will double check the docs, let me know if you find any other typos.

Cheers

Oli :)
