### ISSUE TITLE
Dropdown in Custom Formatter 

### ISSUE THREAD

**Issue by minalkArmstrong** [olifolkerd/tabulator#129]
Hi oli,
Sorry to bother you again..
I want to add one dropdown in tabulator which contains value/options bind from database table directly 
And selected option value return in data object to update data.

Is it possible to such provision on tabulator?

**Comment by olifolkerd** [comment]
Hey,

No need to apologise, all questions are welcome here.

You certainly can do that, you would need to create a custom editor containing a select element. Luckily, there is already an example of this in the documentation [here](http://olifolkerd.github.io/tabulator/docs/#manipulating-data)

All you would then need to do, is tweak the editor to include an ajax statement that pulled down the values for the select and added the option elements accordingly.

If the values for the select weren't going to change once the table was drawn could do this outside the editor function and reference the values so you didn't make the ajax request every time the editor was called.

If you would like a more specific code example on here, just let me know i would be happy to stick one up

**Comment by minalkArmstrong** [comment]
In dropdown i want to add vendor name  and their table row id as value .From above ref link we can add static options to dropdown . I want to fetch data from database and bind to the dropdown on tabulator load and in object  vendor parameter returns me the selected option value.

**Comment by olifolkerd** [comment]
So just to clarify:

You want to have a select element populated by an ajax request

***AND***

Do you want to filter the data in your table by row id using the select value?
***OR***
Do you want to load a new set of data via ajax based on the value of the select?

Let me know which of the two it is, or if i am completely confused and i will put together an example for you.

Oli :)

**Comment by minalkArmstrong** [comment]
![image](https://cloud.githubusercontent.com/assets/24350278/21251245/507d80a2-c372-11e6-9e90-4e5d35303b66.png)
I hope you will get idea from this.

**Comment by olifolkerd** [comment]
Thanks for the image that was a great help.

For the sake of ease i'm going to store the persistent value for the select in the localStorage object rather than sending it to the server, as how you do that will depend on your individual setup, but you should easily be able to convert it to your own way of working.

So to start with we are going to need a bit of css to style our table header select element:

```css
#example-table .vendor-selector{
	width:100%;
}
````

Then we will define our tabulator, adding the select element to the title of the vendor column
```js
$("#example-table").tabulator({
	height:"320px",
	columns:[
	{title:"Partcode", field:"partcode"},
	{title:"Description", field:"description"},
	{title:"Vendor <div><select class='vendor-selector'></select></div>", field:"vendor"}, //add select box to column header
	],
});

```
Then we will add some event bindings to our select box to trigger the needed functions
```js
//prevent clicking on the select box from triggering the column sort
$("#example-table .vendor-selector").click(function(e){
	e.stopPropagation();
});

//trigger filter on table data when filter is changed
$("#example-table .vendor-selector").change(function(e){
	if($(this).val()){
		$("#example-table").tabulator("setFilter", "vendor", $(this).val());
                localStorage.setItem("vendor", $(this).val());
 	}else{
		$("#example-table").tabulator("setFilter");
                localStorage.setItem("vendor", "");
	}
});
```

Then we will load data into our table an into the select box from the same ajax request
```js
$.ajax({
	url: "/path_to_data",
	type: "get",
	async: true,
	dataType:'json',
	success: function (data) {
		//clear the select and add an empty option to enable user to clear the filter
		var select = $("#example-table .vendor-selector");
		select.empty()
		select.append("<option value=''></option>");
		
		//load vendors into select element
		data.forEach(function(row){
			select.append("<option value='" + row.vendor + "'>" + row.vendor + "</option>");
		})
		
		//load data into table
		$("#example-table").tabulator("setData", data);

		//set select filter value to persistent value if available
		var vendor = localStorage.getItem("vendor");
		if(vendor){
			select.val(vendor);
		}else{
			select.val("");
		}

		//trigger filter update
		select.change()
	},
});
```
Hopefully that should give you what you need to get started.

Let me know if you have any issues

Cheers

Oli

**Comment by AndrewHutcheson** [comment]
Hi, this question is one I had as well, thanks.

And it looks like I can just use the same callback function on a custom filter so that a filter-data-in-header allows for filtering by dropdown?

**Comment by olifolkerd** [comment]
you could certainly use the ***headerFilter*** option to add a dropdown in the column header.

You  would need to adjust the selector for the dropdown in the ajax success function to pick the correct element to assign the options to.
