### ISSUE TITLE
Website is unavailable

### ISSUE THREAD

**Issue by lavigor** [olifolkerd/tabulator#1291]
Hello, Oli!

Thank you for such a great plugin, it's really feature rich and useful!
However I'm forced to browse Google Webcache for accessing the docs because `tabulator.info` cannot be loaded. Tested with different browsers and IPs: I suppose your website can be blocked in Russia.

I just wanted to let you know about that, maybe you'll be able to find some workarounds for this issue (GitHub Pages work OK, but you introduced redirects to `tabulator.info` that I cannot access).

Best regards,
Igor

**Comment by olifolkerd** [comment]
Hey @lavigor 

I seem to be able to load the tabulator website without issue.

What message are you seing in your browser?

Cheers

Oli :)

**Comment by lavigor** [comment]
@olifolkerd the page loads for about a minute with a message `Connecting to tabulator.info...` and then displays a message that the connection is timed out.

**Comment by olifolkerd** [comment]
Hey @lavigor 

I seem to be able to connect to it fine, which is odd.

which browser are you using?
what url are you going to?
are you behind a firewall?
what country are you in?

Cheers

Oli  :)

**Comment by lavigor** [comment]
Hi, @olifolkerd 

>which browser are you using?

I use Firefox, but the problem stays in IE and Edge too.

>what url are you going to?

http://tabulator.info/

>are you behind a firewall?

No, as I've said, `Tested with different browsers and IPs`. By different IPs I meant different Internet providers.

>what country are you in?

As I've said, `I suppose your website can be blocked in Russia`, however I explore a different behaviour with blocked resources. Your site just gives a timeout.

I typed `ping tabulator.info` in the command line and it also gives a timeout message (100% loss for packages).
`tracert tabulator.info` shows timeout after the third IP, it seems that the problem can originate from provider but I'm not sure.

**Comment by olifolkerd** [comment]
Have you tried www.tabulator.info

**Comment by lavigor** [comment]
@olifolkerd just tried that too with the same result.

**Comment by olifolkerd** [comment]
I can still access it on a variety of vpns which would suggest there may be
DNS issues at your end.
