### ISSUE TITLE
Get all editeded Cells

### ISSUE THREAD

**Issue by JeepRubicon2012** [olifolkerd/tabulator#1293]
Is it possible to get a list of all editeded Cells in a JSON structure or a loop ?

Greetings Stefan

**Comment by olifolkerd** [comment]
Hey @JeepRubicon2012 

Sorry for the delay in getting back to you.

you cannot get this directly out of tabulator, but there would be nothing to stop you using the ***cellEdited*** function to push the cell that has just been edited into an array so you could access the list whenever you want.

i hope that helps,

Cheers

Oli :)
