### ISSUE TITLE
Just wanted to say THANK YOU!

### ISSUE THREAD

**Issue by hrstoyanov** [olifolkerd/tabulator#1294]
Oli, I was going to ask if you plan on getting rid of jQuery, when I saw this:
```
Version 4.0 Comming Soon
- Tabulator will be free of core dependencies, no more need for JQuery!
...
I'm hoping to get the release out by the end of July, so keep your eyes peeled for more news
```

BIG TANK YOU! How can I help testing Tabulator 4? Is Tabulator 4 available on CDN?

**Comment by ortega225** [comment]
When will Tabulator 4 be ready for testing?

**Comment by olifolkerd** [comment]
Hey @hrstoyanov 

Thanks for your kind words.

Things got a bit hectic at work last month so im running slightly behind at the moment with 4.0

I hope to have a beta release available in a couple of weeks time for people to have a play with, with a planed final release around the end of Aug.

Thanks for your patience Guys and Girls.

Cheers

Oli :)

**Comment by hrstoyanov** [comment]
Awesome!

**Comment by olifolkerd** [comment]
Hey Guys & Girls,

I just wanted to drop you a quick message to let you know that a beta version for 4.0 should be available through the tabulator.info site Wednesday evening UK time.

Thanks for your patience while i have been putting it all together.

It has taken quite a while to extract all the jQuery from every nook and cranny and over two weeks work just to convert the website over to the new format and convert all the examples over to the new vanilla JS options.

I look forward to seeing what you all think.

Cheers

Oli :)

**Comment by Rodbjartson** [comment]
@olifolkerd  really looking forward to this!
I have two questions:
How will the vanilla tabulator work for us who already have set it up using jquery? Will it be easy just continuing to use it like today?
And have you been able to do anything with the pdf printing options? One of the features I miss the most is the simple formatting options for printing from tabulator to pdf!

**Comment by ortega225** [comment]
@olifolkerd, just wanted to say thank you for creating such a nice grid for us to use. Can't wait to test/try out Tabulator 4

**Comment by olifolkerd** [comment]
Hey @Rodbjartson 

You will be happy to hear there is a jQuery wrapper so you can keep your code as it is, and i havnt had a chance to do and tweaks to the PDF system yet, but it is a couple of weeks at least before 4.0 will be released so im hoping to get it in by then.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @ortega225 

Thanks for your kind words, it is great to hear that Tabulator is appreciated!

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey All,

The version 4.0 beta is now available for you to have a play with.

It is still under development in some areas but all the core functionality is in and working, if you find any bugs or have any feedback please create an issue so i can track it all.

Checkout the [Version 4.0 Documentation](http://tabulator.info/docs/4.0) for more information.

### Website Updates
The website has also had a bit of a going over, there are now:

[Release Notes](http://tabulator.info/docs/4.0/release) to explain all the new functionality,

A step by step [Upgrade Guide](http://tabulator.info/docs/4.0/upgrade) to take you through how to transition to 4.0

A [Browser Support](http://tabulator.info/docs/4.0/browsers) page to take you through what browsers are supported by Tabulator, 

A [jQuery Wrapper Guide](http://tabulator.info/docs/4.0/jquery) for those of you that want to keep your jQuery code as untouched as possible 

And a new [FAQ Section](http://tabulator.info/faq) to cover some of the most frequent questions i see on the issue list.

Let me know how you get on

Cheers

Oli :)

**Comment by hrstoyanov** [comment]
awesome!

**Comment by olifolkerd** [comment]
Hey @Rodbjartson,

You will be happy to hear that i have pushed some updates to the PDF download system to the 4,0 branch.

You can now pass a function into the ***autoTable*** property, this should return the AutoTable options object. The ***jsPDF*** document object will be passed in as the first argument of this function which will allow you to call any of the jsPDF API functionson the document, so you can for example add additional text to your PDF or set the font.

```js
table.download("pdf", "data.pdf", {
    orientation:"portrait", //set page orientation to portrait
    autoTable:function(doc){
        //doc - the jsPDF document object

        //add some text to the top left corner of the PDF
        doc.text("SOME TEXT", 1, 1);

        //return the autoTable config options object
        return {
            styles: {
                fillColor: [200, 00, 00]
            },
        };
    },
});
```

Cheers

Oli :)

**Comment by Rodbjartson** [comment]
@olifolkerd 
I think that I do not understand how this works, I am getting this error when I try your example:
`The options parameter should be of type object, is: function`

```
$("#item-table-modal").tabulator("download", "pdf", "data.pdf", {
                    orientation: "landscape", //set page orientation to portrait
                    autoTable: function (doc) {
                        //doc - the jsPDF document object

                        //add some text to the top left corner of the PDF
                        doc.text("SOME TEXT", 1, 1);

                        //return the autoTable config options object
                        return {
                            styles: {
                                fillColor: [200, 00, 00]
                            },
                        };
                    },
                });
```

**Comment by olifolkerd** [comment]
Hey @Rodbjartson 

If you are getting that error, it means you are likely running on version 3.5 code. When I run your example on version 4.0 it works correctly.

Just so you know, there is no need to bump me (i appreciate it came from a good place), I get notifications any time anyone comments on this repo, there is only one of me so i have to prioritise what i can answer around the rest of my life. As you're an experienced Tabulator user, and this was a non critical issue,  i was prioritising helping out the newbies till i had a bit of time to respond to you on the weekend.

If your still having issues with this could you create a new issue as this conversation has drifted considerably from the purpose of this issue.

Cheers

Oli :)
