### ISSUE TITLE
Vertical Rows

### ISSUE THREAD

**Issue by rjd584** [olifolkerd/tabulator#1295]
I can't find this anywhere, so sorry if it's been asked before. 

Are vertical rows possible/planned?

**Comment by Rodbjartson** [comment]
Why would you like to have that?

**Comment by rjd584** [comment]
-Rodbjartson, the data I need to display has a large graphic in it. Sort of like the cheese example. I need to display as many rows as possible. Right now I'm doing it with regular old html tables.

**Comment by olifolkerd** [comment]
Hey @rjd584 

Im afraid Tabulator has no concept of a vertical row, but with a bit more information im sure we can come up with a solution for you.

You can set at many columns as you want, and change them with the ***setColumns*** function, so if you can structure your row and column data in a way that Tabulator can understand it should be possible to meet you needs.

I hope that helps,

Cheers

Oli :)
