### ISSUE TITLE
Unable to get selected rows to persist after pagination 

### ISSUE THREAD

**Issue by Grant-Lawton** [olifolkerd/tabulator#1297]
Hi Oli,
I will start off as so many others do, by saying: Thanks for Tabulator, It is truly awesome!

im not sure where im going wrong, but im unable to get my selected rows to persist after paging .
Im using 3.5.3, I understand that selections will not persist after calling setData, I am just paging using tabulator's paging buttons.

EDIT: I actually cant even get the selected rows to persist after filtering.

I did try to see if I could hook the rowSelectionChanged callback, although the selected rows have been cleaned out by the time the callback is triggered.

My constructor is:
`$(tabulatorElementName).tabulator({
        layout: "fitColumns",
        layoutColumnsOnNewData: true,
        ajaxFiltering: true,
        ajaxSorting: true, 
        addRowPos: "top",
        pagination: "remote",
        selectable: true,
        selectablePersistence: true,
        paginationSize: pageSize, 
        columns: [
            { title: "Comment", field: "comment", headerFilter: true, align: "center", editor: true }
		// removed some columns to save space
        ],
        cellEdited: function (cell) {
            var row = cell.getRow();
            var rowData = row.getData();
            UpdateRow(rowData);
        },
        rowAdded: function (row) {
            newTabulatorRow = row;
        },
        rowContext: function (e, row) {
            row.toggleSelect();
            e.preventDefault(); 
        },
        ajaxResponse: function (url, params, response) {
            if (response.data[0] == []) {
                $(tabulatorElementName).tabulator("clearData");
             }
            else { return response;}
        },
    });`

any ideas?

**Comment by Grant-Lawton** [comment]
I will leave the question open in case there is a proper way to solve this, However in the meantime I have put together this workaround:

```
$(tabulatorElementName).tabulator({
layout: "fitColumns", 
layoutColumnsOnNewData: true, 
ajaxFiltering: true, 
ajaxSorting: true, 
addRowPos: "top", 
pagination: "remote", 
selectable: true, 
selectablePersistence: true, 
paginationSize: pageSize, 
columns: [ 
    { title: "Comment", field: "comment", headerFilter: true, align: "center", editor: true } 
    // removed some columns to save space ], 
cellEdited: function (cell) { var row = cell.getRow(); var rowData = row.getData(); UpdateRow(rowData); }, rowAdded: function (row) { newTabulatorRow = row; }, 
rowContext: function (e, row) { row.toggleSelect(); e.preventDefault(); }, 
ajaxResponse: function (url, params, response) { 
    if (response.data[0] == []) { $(tabulatorElementName).tabulator("clearData"); } 
    else { return response;} },
rowSelectionChanged: function (data, rows) {
    // This callback is used to add any selected rows in to an array
    // also add the row data into another array in case I need that
            $.each(data, function (idx, obj) {
                if (tabulatorSelectedIndexes.indexOf(obj.id) == -1) {
                    tabulatorSelectedIndexes.push(obj.id);
                    tabulatorSelectedData.push(obj);
                }
            })
        },
dataLoaded: function (data) { 
    // This callback is used to look at each row in the current page of data
    // and work out if it has been added to our array of selected rows, if so select the row.
            $.each(data, function (idx, obj) {
                if (tabulatorSelectedIndexes.indexOf(obj.id)> -1) {
                    $(tabulatorElementName).tabulator("selectRow", obj.id);
                } 
            })
        },
        
    });
    var tabulatorSelectedData = [];
    var tabulatorSelectedIndexes = [];`

// Call ClearSelections to remove any selected rows, then empty the arrays
function ClearSelections(tabulatorName) {
    var data = $(tabulatorName).tabulator("getData", false); //get all results in the dataset to ensure everything is deselected.
    $.each(data, function (index, obj) { $(tabulatorName).tabulator("deselectRow", obj.id); });
    tabulatorSelectedData = [];
    tabulatorSelectedIndexes = [];
}
```

**Comment by olifolkerd** [comment]
Hey @Grant-Lawton 

Thanks for your kind words, it is great to hear that Tabulator is appreciated.

Sorry for the delay in getting back to you.

The issue you are having is because you are using ajax pagination.

In ajax pagination the contents of the internal rows array that holds all rows in the table is emptied and reset every time a page is pulled down from the server. because the table only holds references to rows that exist in the internal rows array the selection data is cleared out on each pagination request.

if you used local pagination this option would work.

If you need to keep using ajax pagination, which is understandable, then i would suggest using the ***rowSelectionChanged*** to maintain an array of selected row indexes outside of Tabulator and pulling it back in when the table is paginated.

Cheers

Oli :)

**Comment by Grant-Lawton** [comment]
Good stuff @olifolkerd , 
Thanks for getting back to me, That makes perfect sense.

Really appreciate your work !
Have a great day.

**Comment by antman3351** [comment]
As I stumbled on this page while googling the same question, I'll leave a code snippet here for other people:

Tabulator v. 5.x
```js
const selectedIds = new Set();

table.on( "rowSelected", function ( row )
{
    const id = row.getData()[this.options.index] ?? null;
    if ( id !== null )
    {
        selectedIds.add( id );
    }
} );

table.on( "rowDeselected", function ( row )
{
    const id = row.getData()[this.options.index] ?? null;
    if ( id !== null )
    {
        selectedIds.delete( id );
    }
} );

table.on( "dataProcessed", function ()
{
    table.selectRow( Array.from( selectedIds.values() ) );
} );
```
