### ISSUE TITLE
Can't delete a row that was added

### ISSUE THREAD

**Issue by machua416** [olifolkerd/tabulator#13]
If you add a row and then try to delete that row, it fails.  You can only delete rows that were initially loaded.

**Comment by olifolkerd** [comment]
What were you passing to the deleteRow function? Was it an id, an object or the jquery DOM element for the row.

Could you post the function call you used.

**Comment by machua416** [comment]
Here is my function.  I know it's a little convoluted as I was not able to just pass the row object.

			function deleteUser(row) {
				// since i don't know what is the id of this row, i'll need to traverse the entire table and look for it
				var data = $("#table-editable").tabulator("getData");
				var id = -1;
				for(a in data) {
					//console.log("ui: " + data[a].userid + "   fn: " + data[a].firstname + "   ln: " + data[a].lastname + "   un: " + data[a].username + "   pw: " + data[a].password + "   em: " + data[a].email + "   co: " + data[a].company + "   uc: " + data[a].userclass + "   a: " + data[a].active);
					if(data[a].userid == row.userid && data[a].firstname == row.firstname && data[a].lastname == row.lastname && data[a].username == row.username 
						&& data[a].password == row.password && data[a].email == row.email && data[a].company == row.company && data[a].userclass == row.userclass 
						&& data[a].active == row.active) {
							//console.log(a);
							//$("#table-editable").tabulator("deleteRow", parseInt(a, 10));
							id = a;
							break;
					}
				}
				if(id != -1) {
					console.log(id);
					id = parseInt(id, 10);
					$("#table-editable").tabulator("deleteRow", id);
				}
			}

**Comment by machua416** [comment]
Here is the column that I have button on the grid that calls my deleteUser function.

{formatter: deleteButton, width: 40, align:"center", onClick:function(e, cell, val, row){deleteUser(row);}}

**Comment by olifolkerd** [comment]
You just need to pass the row directly to the ***deleteRow** function an that will remove the correct row for you.
```js
$("#table-editable").tabulator("deleteRow", row);
```

**Comment by machua416** [comment]
Tis worked.  Thanks for your help.

**Comment by olifolkerd** [comment]
Hi Guys,

I have just launched a new documentation site for tabulator, check it out:
http://olifolkerd.github.io/tabulator/

Oli
