### ISSUE TITLE
SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function

### ISSUE THREAD

**Issue by RobyAbraham** [olifolkerd/tabulator#130]
I am getting "SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function tabulator.js:517:12"... please help.

Thanks for the great work!

**Comment by bonegabor** [comment]
Hi, I've had this problem few days ago. Look at issue https://github.com/olifolkerd/tabulator/issues/124
