### ISSUE TITLE
Editable cells on responsivelayout:collapse?

### ISSUE THREAD

**Issue by AndrewHutcheson** [olifolkerd/tabulator#1300]
Is there a way to do this currently? It would be great for a future release.

**Comment by olifolkerd** [comment]
Hey @AndrewHutcheson 

Thanks for getting in touch.

With collapse mode enabled all cells are editable as usual, but the list of collapsed values is read only im afraid.

I hope that helps,

Cheers

Oli :)

**Comment by AndrewHutcheson** [comment]
Is this something that can be added to the roadmap?

**Comment by olifolkerd** [comment]
yup no problem.

At the moment the roadmap it a bit messy. once ive see how much i can pack into the version 4.0 release this month i will tidy it up and allocate things out properly.

Cheers

Oli :)

**Comment by AndrewHutcheson** [comment]
Hi,

I was just wondering if you were still planning on making collapsed cells editable? It would allow a lot of usefulness in mobile pages.

Thanks!

**Comment by olifolkerd** [comment]
Hey @AndrewHutcheson 

It is still on the roadmap, but i have had to rejig things a bit with the release of 4.0 so it wont be available for a while.

Cheers

Oli :)

**Comment by niftylettuce** [comment]
Would love to have this... can you re-open?

**Comment by AndrewHutcheson** [comment]
It is on the roadmap. But it's under "the future" so it might be awhile.

https://trello.com/b/rPZ0Yavc/tabulator-roadmap

**Comment by darren1713** [comment]
Adding our support for this feature need as mobile users and small format screens loose the ability to cleanly edit tables. Great library btw.

**Comment by AndrewHutcheson** [comment]
@olifolkerd any ETA on this feature?

**Comment by AndrewHutcheson** [comment]
Hi @olifolkerd, I see this is still on "the future" in the roadmap, is there any update? Mobile is pretty much a majority nowadays.
