### ISSUE TITLE
HTML is not parsing in creating table from HTML table

### ISSUE THREAD

**Issue by p-wldz** [olifolkerd/tabulator#1301]
I want to create table from my HTML table. But in this table i have links, buttons. When i'm declaring the table - it works, but i see everything like a plaintext. HTML is not parsing.

![obraz](https://user-images.githubusercontent.com/40058980/43263549-dade3666-90e3-11e8-9512-5a0e3db183d2.png)

**Comment by Nyut0n** [comment]
I think you have to use the html formatter on these colums.

From the docs:

> **Complex Options Setup**
If you need to set up any column options on the imported table you can declare these in table constructor as you would do for any other table. It is important to note that the title parameter for each column definition must match the text in the table element's header cell exactly for the imported data to link to the correct column. 

> If you use a column definition array in the Tabulator constructor, the order of columns in this array will take priority over the order of the columns in the table element.

So, to format the "Notes" column, do something like this in the constructor:

```javascript
$("#example-table").tabulator({
    columns:[
        {title:"Note", formatter:"html"},
        // other colums here ...
    ],
});
```

Check the docs for more info and examples.

**Comment by p-wldz** [comment]
That's helps a lot, thanks!
