### ISSUE TITLE
Printing large Tabulator reports

### ISSUE THREAD

**Issue by aditya-thimphu** [olifolkerd/tabulator#1302]
Hi Tabulator users,

How are you managing to print large Tabulator reports (ones having thousands of rows)? I use progressive loading to display on the screen; my tables also have groupings and summaries (sum, count, etc). I am not able to print such reports. I want to print a report as it is displayed on the screen including all rows, columns, groups and summaries.

Any suggestions/ideas will be appreciated.

Thanks,
Aditya

**Comment by olifolkerd** [comment]
Hey @aditya-thimphu 

Thanks for getting in touch.

Advanced print functionality will be coming later in the year in version 4.1

in the mean time you could use the ***getHtml*** function to return an html table containing all the rows, that you could then print.

I hope that helps,

Cheers

Oli :)

**Comment by dannycallaghan** [comment]
Hi Oli

Firstly, thanks so much for this project, it's amazing.

I was interested in this question when it was first asked, and was excited to hear of the (then) forthcoming advanced print functionality. Now that we're at 4.1.4, are you able to point me at the new features, as they don't seem to be documented as of yet?

Thanks again.

**Comment by olifolkerd** [comment]
Hey @dannycallaghan 

You will be happy to hear that the print functionality has finally arrived in Tabulator!

Checkout the [Print Documentation](http://tabulator.info/docs/4.3/print) for full details

Cheers

Oli :)
