### ISSUE TITLE
Download (allow download hidden columns, but do not download filtered out rows)

### ISSUE THREAD

**Issue by MikhailKlemin** [olifolkerd/tabulator#1303]
Hi!
I have not used the tabulator since version 2.X I think and it was great experience. 
The 3.5 is much better :-) 

Does it possible somehow to download say CSV in the way that only rows which filtered are presented, but with all columns regardless of their visibility?

**Comment by AndrewHutcheson** [comment]
I would also like this feature.

**Comment by olifolkerd** [comment]
Hey @MikhailKlemin 

Thanks for the suggestion, i think that is a great idea, i will add it to the roadmap for the next couple of releases.

at the moment the download system will only download the raw data in the table, there are a lot of updates coming to it that will allow it to handle paged, groups and filtered data.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @MikhailKlemin and @AndrewHutcheson 

As there is a lot of interest in new features for the download functionality i have created one issue where people can share their thoughts.

#1436 

Cheers

Oli :)
