### ISSUE TITLE
Multiple column sorting issue.

### ISSUE THREAD

**Issue by hjmakwana** [olifolkerd/tabulator#1304]
I want to sort multiple column.
tabulator provide this functionality but i need below results

Name 		Age 		Country
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
A			15			India	
B			16			Australia	
C			17			New Zealand	
D			14			Bangladesh	
A			10			Zimbabwe	
B			18			London	
C			15			New Zealand		
D			20			London	

Now i'm sorting by name asc

Name 		Age 		Country
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
A			15			India	
A			10			Zimbabwe
B			16			Australia	
B			18			London	
C			17			New Zealand	
C			15			New Zealand		
D			14			Bangladesh	
D			20			London	

Now i'm sorting by age Asc using shift key (Multi column sorting)

Name 		Age 		Country
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
 A			10			Zimbabwe
A			15			India	
B			16			Australia	
B			18			London	
C			15			New Zealand		
C			17			New Zealand	
D			14			Bangladesh	
D			20			London	

Now i'm sorting by age Desc using shift key (Multi column sorting)

Name 		Age 		Country
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
A			15			India
A			10			Zimbabwe	
B			18			London	
B			16			Australia	
C			17			New Zealand	
C			15			New Zealand		
D			20			London	
D			14			Bangladesh

**Comment by hjmakwana** [comment]
Hey @olifolkerd 

      I stuck in this issue so i cannot submit my project in college so please reply asap.

Thanks.

**Comment by hjmakwana** [comment]
Hey @olifolkerd 

I want to <a href="https://datatables.net/examples/basic_init/multi_col_sort.html"> this type of </a> sorting.

Use Shift + Columns Click for multi column ordering. Please reply asap.


Thanks

**Comment by hjmakwana** [comment]
Hey @olifolkerd 

I tried to implement sort as you said in comment but still sorting is not working as per requirement is there any other way to do this because when i set header sort false i am not getting dir value for asc or descending so i can not use setSort function for sorting on headerClick event.

I want to know that can i use both headerSort and headerClick or only one of them can be used?

I have also tried your reference code in Closed issue #483 for sorting but it was not working with me.

Thanks for your suggestion and support other functionalities are too good and usefull and let me know if any solution for my issue.

I hope we will get more and more from you.

Cheers!!

**Comment by olifolkerd** [comment]
Hey @hjmakwana 

If you use the ***headerSort*** false option then you can use the ***getSorters*** function to retrieve the current sort direction of the column,

Version 4.0 will be coming out in a few weeks, crammed with even more features.

Cheers

Oli :)

**Comment by answerquest** [comment]
Hi @olifolkerd , I'm sorting on data load using the ***setSort*** function.
```
$("#right-table").tabulator("setSort", [
	{ column:"Fpartial", dir:"desc"}, //sort by this first
	{ column:"JjaroW", dir:"desc"} //then sort by this second
]);
```
The table is being sorted **only** by the second option, though it displays as if sorted by the two columns.
Here are screenshots:  
1. When the data is loaded, with the `setSort` function executed:  
![tabulator-sort-issue-1](https://i.imgur.com/JQC9J1m.png) -> only second, `JjaroW` column actually sorted

2. When I manually click the `Fpartial` column twice to sort it descending:  
![tabulator-sort-issue-2](https://i.imgur.com/tuhpgdf.png) -> now first, `Fpartial` column sorted. 

**Desired output:** We can see that from second row onwards where first `Fpartial` column is same, the data should have been sorted by the second `JjaroW` column.

Here are the column definitions:
```
	{title:"Fpartial", field:"Fpartial", headerFilter:"input", sorter:"number" },
	{title:"JjaroW", field:"JjaroW", headerFilter:"input", sorter:"number" },
```
So even in programmed `setSort` function it's not working as defined. Sorting only by the second column. Using Tabulator v3.5.3, latest downloaded.

No hurries, but pls look into this for v4 release, and thanks again for the excellent documentation work.

**Comment by olifolkerd** [comment]
Hey @answerquest 

The sorts are occurring correctly, the issue there is that only the last sort arrow is being highlighted.

any programtic sort, either using ***setSort*** or the ***initialSort*** property will sort all of the columns in the correct order but only the last sort in the list will be highlighted.

multiple arros are only highlighted when the user manually sorts by clickin on the column headers.

Cheers

Oli :)

**Comment by answerquest** [comment]
Hi @olifolkerd ,
Please see my first screenshot carefully. I got the exact opposite result of what you described.  
![bad sort](https://i.imgur.com/JQC9J1m.png)

1. I got ALL the sort arrows highlighted as expected, so UI side there wasn't an issue.
2. My data is being sorted only by the _last_ column I defined in **setSort** options. It is _overriding_ everything else. The first column's sorting never happened. 
3. It's not supposed to be `75,78,56,56,78,67` as happening, seen in screenshot. That column hasn't been sorted at all.
4. There is no ***combined*** sorting happening, as one expects in an excel sheet when one specifies more than one column to sort by. Data is being sorted only by one single column, that too the last one defined (which is supposed to be last priority)

this is the sorting command:
```
$("#right-table").tabulator("setSort", [
	{ column:"Fpartial", dir:"desc"}, //sort by this first
	{ column:"JjaroW", dir:"desc"} //then sort by this second
]);
```
What I'm getting is not the same as what the original poster of this issue posted, but the title is more matching to my scenario. Let me know if I should just open another ticket for this, or if I should set up something live for you to see for yourself.
