### ISSUE TITLE
IE Compatibility ?

### ISSUE THREAD

**Issue by Keorl** [olifolkerd/tabulator#1305]
Would it be possible to have a version of tabulator.min.js made compatible with old IE, or especially IE11 running in ie5-8 modes due to stupid policies ?
Here are a few things I fixed in tabulator.min.js before giving up :
- functions named "delete", renamed to "del" (javascript reserved word)
- same with some occurrences of "default"
- same with 2 functions named "in"
- replaced 2x "xxx.myfunction||Object.defineProperty(xxx,myfunction,function(){})" with "xxx.myfunction=function(){}"
At that point the next errors happening in IE were not possible to fix easily in .min.js

**Comment by Keorl** [comment]
I might be wrong, I think it would be accomplished by compiling Tabulator with a change in gulpfile.js, line 66 : "browsers": ["last 4 versions", "ie >= 8"]

If it works it would output a corporate-compatible tabulator.min.css . Maybe less optimized but at least not broken with IE enterprise mode or "use compatibility mode for intranet" greyed option.

**Comment by olifolkerd** [comment]
Hey @Keorl 

Sorry for the delayed response.

Tabulator currently has compatibility with IE 11, but im afraid that is as far back as it goes.

IE 11 is only just about capable of running Tabulator, the virtual DOM take a huge amount of processing, which old browsers can barely handle. There are a considerable number of work arounds in place just to get it to work on IE, and even then it has a degraded performance.

Im afraid it isn't as simple as telling babel to transpile the code, there are numerous polyfills and workaround needed for old browsers, they make the code base much bigger and harder to maintain.

Given the small proportion of users running on older IE browsers im afraid i simply can spare the enormous amount of additional time it would take to make Tabulator any more backwards compatible that it already is,

Cheers

Oli :)
