### ISSUE TITLE
Problem with export excel method with column with json object as data

### ISSUE THREAD

**Issue by alfredormorales** [olifolkerd/tabulator#1306]
Hello Oli, 

I have an issue when I want to export a tabulator.info grid with a column that is defined in its object as a json data, when  call the method for export it, it show this message in console:

"n.t.match is not a function"

this only happens when I have a column defined in its data as a json object, this is an example:

`data.column1.push({
    id: "some id" ,
    value: "some value"
 });`

I know this feature is supported by a third provider and it happens because this method doesn't support export json objects :( 

Perhaps as a suggestion it would be great to add a functionality in tabulator.info for not export some columns to avoid this kind of problems, maybe an attribute that indicates some column should not be exported.

Cheers!

**Comment by Nyut0n** [comment]
Have you tried using the downloadDataFormatter callback to remove the column(s) that you don't want to export?

**Comment by alfredormorales** [comment]
Sorry I don't see all the documentation content of the export excel features, now I see there is a guide for hide columns on the export table:

"Hide Column In Download"

maybe I was stuck with old documentation or just I did not review all the documentation well and I assumed that there was no way to fix this supposed issue.

Oli Could I close this topic.

Thank you Nyut0n

Cheers!
