### ISSUE TITLE
processing 10000 records is taking a long time

### ISSUE THREAD

**Issue by PayalY** [olifolkerd/tabulator#1308]
In my code,10000 record and 23 columns so tabulator take 2 minutes to bind it .There is any solution to bind a data in seconds

**Comment by olifolkerd** [comment]
Hey @PayalY 

That depends a lot on how your table is configured, but it shouldnt take that long to load.

Could you post a copy of your table constructor so we can see how your table is setup, we can then offer some advice.

Cheers

Oli :)

**Comment by PayalY** [comment]
$("#Indenttable").tabulator({ 
height: 500, 
tooltips: true, 
tooltipsHeader: true, 
index: "Id", 
columns: [ 
// { title: "Status", field: "Status", formatter: "textarea", align: "Center", headerFilter: "input", align: "center", visible: false }, 

{ 
title: "Select", field: "Id", width: 42, align: "center", frozen: true, formatter: function (cell, formatterParams) { 
var row = cell.getValue(); 
return "<div class='checkbox-custom checkbox-primary' style='margin-top:0px;margin-bottom:0px'><input type= 'checkbox' onchange='selectRow(" + row + ",this)' /><label></label></div>"; //return the contents of the cell; 
}, 
}, 

{ 
title: "", field: "indstatus", visible: true, width: 70, align: "Center", headerFilter: "input", 
formatter: function (cell, formatterParams) { 
var value = cell.getValue(); 
if (value == "In progress") { 
return "<i class='icon md-circle' aria-hidden='true' style='color: Yellow;font-size: 14px;' title='In process'></i>"; 
} 
else if (value == "GRN done after commitment") { 
return "<i class='icon md-circle' aria-hidden='true' style='color: Orange;font-size: 14px;' title='GRN done after commitment'></i>"; 
} 
else if (value == "GRN done on/before commitment") { 
return "<i class='icon md-circle' aria-hidden='true' style='color: Green;font-size: 14px;' title='GRN done on/before commitment'></i>"; 
} 
else if (value == "Commited date is crossed") { 
return "<i class='icon md-circle' aria-hidden='true' style='color: Red;font-size: 14px;' title='Commited date is crossed'></i>"; 
} 
}, 
}, 
{ title: "Part code", field: "Pcode_code", formatter: "textarea", width: 190, headerFilter: "input", align: "left" }, 
{ 
title: "Description", field: "Pcode_Description", formatter: "textarea",width: 282, align: "left", headerFilter: "input", visible: false 
}, 
{ title: "Cost Center", field: "cost", width: 70, headerFilter: "input" }, 
{ title: "Qty UOM", field: "UOM", width: 60, headerFilter: "input" }, 
{ 
title: "Status", field: "strstatus", width: 140, headerFilter: "input" 
, formatter: function (cell, formatterParams) { 
var value = cell.getValue(); 
return "<label title='" + cell.getData().Remarks1 + "'>" + value + "</label>"; 
}, 
}, 
{ title: "Indent Date", field: "SavedOn", width: 81, align: "Center", headerFilter: "input", align: "left" }, 
{ title: "Req.Date", field: "date", width: 76, align: "Center", headerFilter: "input", align: "left" }, 
{ title: "Commited Date", field: "strCommitedDate", width: 76, align: "Center", headerFilter: "input", align: "left" }, 
{ title: "PO Date", field: "PODate", width: 76, align: "Center", headerFilter: "input", align: "left" }, 
{ title: "GRN Date", field: "GRNdate", width: 76, align: "Center", headerFilter: "input", align: "left" }, 
{ title: "Last Updated On", field: "UpdatedOn", width: 84, align: "Center", headerFilter: "input", align: "left" }, 
{ 
title: "Indent No", field: "Id1", width: 58, align: "Center", headerFilter: "input", align: "left" 
, formatter: function (cell, formatterParams) { 
var value = cell.getValue(); 
return "<label title='" + cell.getData().location + "'>" + value + "</label>"; 
}, 
}, 
{ title: "PO No", field: "PONo", width: 166, align: "Center", headerFilter: "input", align: "left" }, 
{ title: "Vendor Name", field: "VendorName", width: 166, align: "Center", headerFilter: "input", align: "left" }, 
{ title: "Indenter", field: "username1", width: 100, align: "Center", headerFilter: "input", align: "left", visible: false }, 
{ title: "Last Updated By", field: "username", width: 71, align: "Center", headerFilter: "input", align: "left" }, 
{ title: "Id", field: "Id", width: 43, align: "Center", headerFilter: "input", align: "left", visible: false }, 
{ title: "Division", field: "DivisionName", width: 88, align: "Center", headerFilter: "input", align: "left", visible: false }, 
{ 
title: "SCM remarks", field: "Remarks1", width: 150, align: "Center", headerFilter: "input", align: "left" 
}, 
{ title: "Location", field: "location", width: 88, align: "Center", headerFilter: "input", align: "left" }, 
{ 
title: "Indent Remarks", field: "PartRemarks", headerFilter: "input", width: 150, align: "left" 
}, 
{ 
title: "Indenter's Remarks", field: "Indenterrmk", headerFilter: "input", width: 150, align: "left" 
}, 
{ title: "Expected date", field: "strExpectedDate", width: 88, align: "Center", headerFilter: "input", align: "left", visible: false }, 
{ title: "Assembly status", field: "AssStatus", width: 88, /*align: "Center",*/ /*headerFilter: "input", align: "left",*/ editor: AssemblyEditor }, 
{ 
title: "cnt", field: "cnt", width: 30, visible: false, formatter: function (cell, formatterParams) { 
document.getElementById("hdncnt").value = cell.getValue(); 

}, 
}, 

], 
}); 

----- Original Message -----

**Comment by olifolkerd** [comment]
Hey @PayalY 

How are you setting the data on your table?

Cheers

Oli :)

**Comment by PayalY** [comment]
Hey olifolkerd , 

My data is come from the database and return a JSON data then set a tabulator using following function 




$.ajax({ 
url: "R_frmIndentTracker2.aspx/FetchTracker", 
method: 'Post', 
data: "{'costcenter':'" + document.getElementById('ddlcostcenter').value + "','Indenter':'" + document.getElementById('ddlindenter').value + "','Status':'" + message + "','jobcodenewP':'" + document.getElementById('ddlprojectcode').value + "','Id':'" + 0 + "'}", 
contentType: "application/json; charset=utf-8", 
dataType: "json", 
success: function (r) { 
$("#Indenttable").tabulator("setData", r.d); 
document.getElementById('divloader').style.display = 'None'; 
} 
}); 

----- Original Message -----

**Comment by olifolkerd** [comment]
Have you check to see weather it is the request that is taking a long time to return, or Tabulator taking a long time to process the data?

**Comment by PayalY** [comment]
Yes, i have check tabulator taking a long time to process the data 

----- Original Message -----

**Comment by olifolkerd** [comment]
Hey All,

To make it easier to notify everyone of progress with the rendering system i have created one issue #1437 where i will report progress.

Cheers

Oli :)
