### ISSUE TITLE
row.getTable() and cell.getTable() NEW feature

### ISSUE THREAD

**Issue by Rodbjartson** [olifolkerd/tabulator#1309]
Very useful when you have a cell and can get the tablename easily.
Maybe a new feature?

**Comment by olifolkerd** [comment]
Hey @Rodbjartson 

Could you explain a bit more about what you are looking for, are you looking for the JS object representing the table?

Cheers

Oli :)

**Comment by Rodbjartson** [comment]
Yes the JS object would be great!
Or, as a start, the name.
It would help a lot when you deal with a cell, or a row or a column, but you do not know where this cell/column/row belongs.

**Comment by olifolkerd** [comment]
Hey  @Rodbjartson 

No problem, i will add it into the 4.0 release.

Cheers

Oli :)

**Comment by Rodbjartson** [comment]
Thanks mate!

**Comment by olifolkerd** [comment]
This is now on the 4.0 branch :)
