### ISSUE TITLE
Send Filter/Sort parameters in ajax request - Filter input in column header

### ISSUE THREAD

**Issue by Gonzalo788** [olifolkerd/tabulator#131]
Is there any possible solution to add a filter input in the header which starts a new ajax request? What I want is a select menu or text input for filtering over the whole dataset.

**Comment by olifolkerd** [comment]
Hey,

That is certainly possible, you can create your own filter function  (a custom editor) but remove the usual event bindings that would trigger an internal data filter:

```js
//filter generator
function ajaxFilter(cell, value, data){
	//create and style input
	var input = $("<input type='text'/>");
	input.css({
		"padding":"4px",
		"width":"100%",
		"box-sizing":"border-box",
	})

	//wait till element is added to dom before altering event bindings
	setTimeout(function(){
		//block existing filter event bindings
		input.off("keyup change blur keydown");

		//submit new value on blur
		input.on("change blur keydown", function(e){
			//AJAX CODE GOES HERE
		});
	}, 300);

	return input;
}

//build tabulator element
$("#example-table").tabulator({
    columns:[
        {title:"Name", field:"name", headerFilter:ajaxFilter},
    ],
});
```

Let me know if that works for you.

Cheers,

Oli

**Comment by Gonzalo788** [comment]
Thank you that worked for me. I did this with a select element which triggers a new ajax request. 

`$("#projects-ajax-table").tabulator("setData", "/projects/get",
						{
							filter : "status",
							filter_value : editor.val()
						});`

This method has a drawback because I need to set filter parameters manually because no ajax request is triggered and filtering happens locally.

**Comment by olifolkerd** [comment]
that is an interesting idea, i will have a look at adding a setting that allows sort/filter commands to pass to the server. they already do on paginated requests

**Comment by Gonzalo788** [comment]
For now I wrote a reusable function which creates the editor and sets the ajax request function. At the moment I'm working on a customizable header. I need a header which contains the select or input only.

**Comment by olifolkerd** [comment]
when you say select or input only, do you mean with no header title text? if so you can pass html directly to the column definition ***title*** property and it will be displayed instead of plain text

**Comment by bvisonl** [comment]
I am not sure if this was implemented or not since you closed this issue... if so, how are all the filters passed to the Ajax request?

**Comment by olifolkerd** [comment]
Using the above method, you would need to do this yourself in the space marked ```js //AJAX CODE GOES HERE ``` using a ***setData*** command and passing the filtered as a paramter

**Comment by bvisonl** [comment]
got it, this would mean that I have to create a different filter for each of the column headers that should trigger ajax? Trying to wrap my head around the events.. because for the row editor parameter you get the cell, value, data parameters but when using it for the headerFilter you don't get any reference back to which header was that filter applied to (in case for example I have 5 inputs I was thinking on using the same custom filter for those 5 and just get the name of the field in the ajax call)

let me know if I am overthinking this...

**Comment by olifolkerd** [comment]
Hey,

Sorry for the delay in getting back to you, had a bit of a full on week at work catching up with the xmas break.

If you are sending the filter parameters back as part of the set data function then the column that triggers the sort dosn't matter, only the values of each of the column headers, which you can iterate though when the filter is triggered:

```js
//filter generator
function ajaxFilter(cell, value, data){

	//create and style input
	var input = $("<input type='text' class='ajax-filter'/>");
	input.css({
		"padding":"4px",
		"width":"100%",
		"box-sizing":"border-box",
	})

	//wait till element is added to dom before altering event bindings
	setTimeout(function(){
		//block existing filter event bindings
		input.off("keyup change blur keydown");

		//submit new value on blur
		input.on("change blur keydown", function(e){
			var params = {};

			$("#example-table .tabulator-header").each(function(){

				var element = $(this);

				if(element.val() !== ""){
					params[element.closest(".tabulator-col").data("field")] = element.val();
				}

				$("example-table").tabulator("setData", "/url/to/data", params);
			
			})
		});
	}, 300);

	return input;
}
```

Let me know if that helps

**Comment by leonardorame** [comment]
Hi all, here's a generic "ajaxFilter" I'm usin for one of my apps. I just save this code into a file called `ajaxFilter.js` and add it to my `index.html`, then I reference the global function `ajaxFilter` from columns definition just like Oli explained at the beginning of this thread.

Any improvement will be appreciated:

```
ajaxFilter = function (cell, value, data){
  var params = {};
  //create and style input
  var input = $("<input type='text' class='ajax-filter'/>");
  input.css({
    "padding-left":"2px",
    "padding-right":"2px",
    "font-weight": "normal",
    "width":"100%",
    "box-sizing":"border-box",
    "border": "1px solid gray",
    "border-radius": "1px"
  })

  //wait till element is added to dom before altering event bindings
  setTimeout(function(){
    //block existing filter event bindings
    input.off("keyup change blur keydown");

    //submit new value on change
    input.on("change", function(e){
      var tabulator = $('#' + cell.closest(".tabulator")[0].id);

      // generate parameter's list
      $(tabulator.selector + " .tabulator-header-filter .ajax-filter").each(function(){
        var element = $(this);
        var key = element.closest(".tabulator-col").data("field");

        if(element.val() !== ""){
          params[key] = element.val();
        } else {
          delete params[key];
        };
      });
      // get the original ajaxURL
      var ajaxURL = tabulator.tabulator("option").ajaxURL;
      // perform the ajax call
      tabulator.tabulator("setData", ajaxURL, params);
    });
  }, 300);

  return input;
}

```

**Comment by bvisonl** [comment]
@leonardorame are those params sent over via $_GET variables? I can't see the text that I input in the text field on the request. I just see the page and the size ones...even though the ajax request is being made after I hit enter... what could I be missing?

**Comment by leonardorame** [comment]
Excelent!.

**Comment by shrutis0896** [comment]
> Hi all, here's a generic "ajaxFilter" based on the example @olifolkerd showed here. I just save this code into a file called `ajaxFilter.js` and add it to my `index.html`, then I reference the global function `ajaxFilter` from columns definition just like @olifolkerd explained at the beginning of this thread.
> 
> Any improvement will be appreciated:
> 
> ```js
> ajaxFilter = function (cell, value, data){
>   var params = {};
>   //create and style input
>   var input = $("<input type='text' class='ajax-filter'/>");
>   input.css({
>     "padding-left":"2px",
>     "padding-right":"2px",
>     "font-weight": "normal",
>     "width":"100%",
>     "box-sizing":"border-box",
>     "border": "1px solid gray",
>     "border-radius": "1px"
>   })
> 
>   //wait till element is added to dom before altering event bindings
>   setTimeout(function(){
>     //block existing filter event bindings
>     input.off("keyup change blur keydown");
> 
>     //submit new value on change
>     input.on("change", function(e){
>       var tabulator = $('#' + cell.closest(".tabulator")[0].id);
> 
>       // generate parameter's list
>       $(tabulator.selector + " .tabulator-header-filter .ajax-filter").each(function(){
>         var element = $(this);
>         var key = element.closest(".tabulator-col").data("field");
> 
>         if(element.val() !== ""){
>           params[key] = element.val();
>         } else {
>           delete params[key];
>         };
>       });
>       // get the original ajaxURL
>       var ajaxURL = tabulator.tabulator("option").ajaxURL;
>       // perform the ajax call
>       tabulator.tabulator("setData", ajaxURL, params);
>     });
>   }, 300);
> 
>   return input;
> }
> ```

Hi @leonardorame ,

Can you quote a proper implementation in typescript as it is not working for me. I am using Angular 2+. Please if someone could provide the implementation
