### ISSUE TITLE
Tabulator: lose Cells array when refresh page 

### ISSUE THREAD

**Issue by saraAshraf99** [olifolkerd/tabulator#1310]
I'm trying to click cells dynamically when i first enter the page and bind grid i first get all rows then for each row i call getCells() this function only retun cells at first entering the page but when refresh i lose those cells as object not view as it appears to me. Any advice?

**Comment by saraAshraf99** [comment]
Any advice please I need to fix this issue before deploy ?

**Comment by saraAshraf99** [comment]
I'v got the problem , when i go to API i see tableBuilt function so i go and put my binding code then try to find those cells it's null too and from debug the table binded  by data  with in the function then the data removed after execution of table Built , I need to know when should i set the data and also where i should my code that access the cells so the rows been rendered.

**Comment by olifolkerd** [comment]
Hey @saraAshraf99 

Can i ask what you are trying to do with the cell components as that will affect the advice i give you on how to achieve your aim.

Cheers

Oli

**Comment by saraAshraf99** [comment]
I'm trying to click cells dynamically inside code I know it's positions already ( row number and column number). 

The Steps I follow to achieve that 
1. call function getRows()
2. for each row I access it's Cells()

This is what i'm trying to do on my function at line that check (row.cells ) it came null .
//----------------------------------------------------------------------------------//
function bindSelectedData() {
    var rows = $("#editTech_grid").tabulator("getRows");
    var selectedTech = data["selectedTechnicians"];
    var row;
    var empData;
    var columnKey;
    $.each(selectedTech, function (index, tech) {
        // get technician row by technican id & date
        row = rows[tech.rowIndex].row;
        if (row) {
            $.each(tech.selectedSlots, function (i, slot) {
                for (var key in slot) {
                    var columnIndex = Number(key.replace("slot_", "")) + 2;
                    if (row && row.cells && row.cells.length > 0) {
                        var cell = row.cells[columnIndex];
                        // toggle to unselected because click toogle it again to be selected a final
                        if (cell) {
                            cell.row.data[key + "_selected"] = false;
                            $(cell.element).trigger("click");
                        }
                    }
                }
            });
        }
    });
}

**Comment by olifolkerd** [comment]
Hey @saraAshraf99 

Im in its current format im afraid that wont work.

Tabulator uses a virtual DOM which means that only the elements that are currently visible actually exist, as you scroll the table row and cell DOM elements are created and destroyed in real time, as they become visible/hidden.

This allows tabulator to handle large datasets without slowing down.

Which means that any attempts to trigger events on the cell elements will not work as intended.

Tabulator does already have [Row Selection](http://tabulator.info/docs/3.5#selectable) as a built in feature if that is what you are looking for.

I hope that helps,

Cheers

Oli :)

**Comment by saraAshraf99** [comment]
okay , I'll find some work around thanks for your patience.

**Comment by saraAshraf99** [comment]
okay , I'll find some work around thanks for your patience.
