### ISSUE TITLE
How to save the State? (Persistence Scrolled Row)

### ISSUE THREAD

**Issue by webebox** [olifolkerd/tabulator#1312]
How can I save the table state? for example when I have a scroll table loaded with ajax data, I scroll it to row 1000 , I want to save this state, so when I refresh the page the table should back to its last (row 1000) scrolled position.
Thank you

**Comment by olifolkerd** [comment]
Hey @webebox 

That functionality isnt built into Tabulator but you might be able to achieve it using a mix of [local storage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) to persistently store the current row and a call to the ***scrollToRow*** function once the table data has been loaded.

i hope that helps,

Cheers

Oli
