### ISSUE TITLE
How to group the rows in tabulator.

### ISSUE THREAD

**Issue by prk53** [olifolkerd/tabulator#1315]
i want to group the rows . how to do that in tabulator. i have attached a ".png" file for sample table.
![groupbyrow](https://user-images.githubusercontent.com/41157621/43546608-b9e1318a-95f6-11e8-8f63-1c9449aa208c.png)

please help..
Thanks in advance...

**Comment by olifolkerd** [comment]
Hey @prk53 

Im afraid this functionality is not built into Tabulator, but you could look at using a combination of [Row Formatter](http://tabulator.info/examples/3.5#row-formatter) and [Nested Tables](http://tabulator.info/examples/3.5#nested-tables) to acheive the result you are looking for.

I hope that helps,

Cheers

Oli :)

**Comment by vikash208** [comment]
Could you help me in getting the same result as mentioned above?
Could you post any sample code here ?

**Comment by ajith-om** [comment]
Please post any sample code for the same ? I want to implement the same scenario at the earliest. Kindly help. Thanks in advance.
