### ISSUE TITLE
Rename callback functions to events like "on*"

### ISSUE THREAD

**Issue by quangkieu** [olifolkerd/tabulator#1316]
Hi @olifolkerd,
I saw that you are overhaul the code base so I just want to suggest to rename the callback hooks and other extensions to more suggestive of what type of value need to passed in like "on*" for functions extension, callback or list*, *(e)s for array.

Cheers
Quang

**Comment by olifolkerd** [comment]
Hey @quangkieu 

Thanks for your suggestion.

Im already making major changes at the moment, and i dont want to make the upgrade burden too high for people for this release, so im going to stick with them as they are for the 4.0 release, but i will bear that in mind for the 5.0 release next year.

Thanks for your input.

Cheers

Oli :)
