### ISSUE TITLE
"height" is confusing in the website

### ISSUE THREAD

**Issue by amitron72** [olifolkerd/tabulator#1318]
Perhaps it is possible to replace the height in the examples with "weight" or "meters" (or something else)?

I wanted to figure out how height of tables and rows is configured... but when searching the webpage for height I got too many results... this is happening because the examples have a "height" column (and data field).

(thanks for this amazing component!)
Thank you
Amit

**Comment by olifolkerd** [comment]
Hey Amit,

Thanks for your suggestion. In the next few months the Tabulator website will be getting an overhaul, the documentation will be broken down into different sections and then a site wide search will be available to make it easier to find what you are looking for.

Did you find the answer you needed or would you like some help with that?

Cheers

Oli:)

**Comment by amitron72** [comment]
Thank you
Good luck with the overhaul
Amit
