### ISSUE TITLE
Problem in ajax Heading Filter

### ISSUE THREAD

**Issue by webebox** [olifolkerd/tabulator#1319]
Hi, I have this code
        $("#example-table").tabulator({
            height: '78vh',
            layout: "fitColumns",
            ajaxConfig: "POST",
            ajaxURL: "/Home/TestJson",          
            ajaxProgressiveLoad: "scroll",
            ajaxFiltering: true, 
            columns: [
                { field: "id", title: "id", headerFilter: true},
                { field: "name", title: "name"  },
            ],
        });

but it does not work when I type something in column filter. my JSON is correct and I return last_page parameter. When I type something it pass the filter parameter an the server returns correct JSON but tabulator is not able to refresh the data based on the new received json.
please help. Thank you

**Comment by olifolkerd** [comment]
Hey @webebox 

Thanks for getting in touch.

If the data is returned in the correct format it should be displayed in the table. Are you getting any errors or warnings in your console log?

Cheers

Oli :)
