### ISSUE TITLE
Table always empty with remote pagination

### ISSUE THREAD

**Issue by bvisonl** [olifolkerd/tabulator#132]
I am having some trouble loading my data via Ajax and using remote pagination. I am using the very basic sample from the documentation. As you can see in the picture below the tabulator makes the request and gets back the response with the expected format { data: [], last_page: ~ } but the table stays gray and doesn't render the data. 

![capture png 1](https://cloud.githubusercontent.com/assets/4421747/21186007/f6141cf8-c1e0-11e6-8b19-dfbc80e1db88.PNG)

The html that I am using is a plain <div> with the Id below, doubt it's this since the tabulator get's initialized and shows the gray background.

The JS that I am using is the following:

`<script type="text/javascript">

        $("#example-table-simple").tabulator({
            pagination: "remote",
            ajaxURL: "/list/",
        });

        $(window).resize(function(){
            $("#example-table-simple").tabulator("redraw");
        });

 </script>`

I started by using the example with the local data and it worked out perfectly with the data in a JS variable.

What could I be missing?

**Comment by bvisonl** [comment]
Nevermind....

Forgot to add the columns.... 

`      $("#example-table-simple").tabulator({
            pagination: "remote",
            ajaxURL: "/app_dev.php/logMonitor/rest/",
            columns:[
                {title:"id", field:"id", sorter:"string", width:200},
                ....
            ],
        });`

For some reason thought that it would pick them up from the actual structure since in the documentation there are no columns property.

**Comment by olifolkerd** [comment]
Hey,

Glad to hear you sorted the problem.

Sorry to hear the documentation was confusing, i have avoided putting in other possible setup options in the code examples to avoid people thinking they are mandatory in all situations.

I will update the documentation in this case to make it clearer.

Thanks for your feedback :)

**Comment by ribipul** [comment]
$('#error-table').tabulator({
ajaxURL: '@Url.Action("GetErrorListPaging", "Error")',
ajaxParams: { db: $('#dbname option:selected').text(), pgNo: 0, pgSize: 20 },
pagination: "remote",
paginationSize: 50,
paginationDataSent: { "page": "pageNo" },
paginationDataReceived: {
"last_page": 10,
},
columns: [
{ title: "Serial", field: "ID", sortable: false, sorter: "number", align: "center", formatter: "rownum" },
{ title: "Procedure Name", field: "ProcedureName", sortable: false, sorter: "string", width: 300 },
{ title: "Err Number", field: "ErrorNumber", sortable: false, sorter: "number", width: 120, align: "center" },
{ title: "Err Line", field: "ErrorLine", sortable: false, sorter: "number", width: 100, align: "center" },
{ title: "Error Message", field: "ErrorMessage", sortable: false, sorter: "string", width: 470, formatter: "textarea" },
{ title: "Error Date", field: "DateofErr", sortable: false, sorter: "date", width: 170 },
],
});

If i use pagination: "remote" then table is empty.

But when use pagination: "local" then data display properly.

What is the problem in pagination: "remote" ???

Thank u...
