### ISSUE TITLE
Can't change the amount of page numbers in tfoot

### ISSUE THREAD

**Issue by D19cannon** [olifolkerd/tabulator#1320]
Hey! I have been trying to figure out for quite some time now how to add the pagination footer of the table. Currently, it has 9 buttons and i would like to remove some of them.

As you can see in the image there are quite a few buttons:
<img width="434" alt="screen shot 2018-08-03 at 14 34 11" src="https://user-images.githubusercontent.com/14916043/43640917-6edad68e-972a-11e8-91ac-bf0911b13967.png">

I did like to remove page 4 and 5 and if also possible the pseudo element 'page:' and the 'search' text

Let me now how to do it. I couldn't find it in your documentations.

**Comment by olifolkerd** [comment]
Hey @D19cannon 

you can use the ***paginationButtonCount** property and pass in the number of buttons you want.

```js
$("#example-table").tabulator({
    paginationButtonCount:7,
});
```

my sincere apologies as this appears to have been left out of the documentation, i will fix that now.

Cheers

Oli :)
