### ISSUE TITLE
Tabulator in Joomla

### ISSUE THREAD

**Issue by ryaneric100** [olifolkerd/tabulator#1321]
Hi - I'm trying to get tabulator running in Joomla (in a Joomla Module) - has anyone experience with that, respectively managed to get it working?

Thanks in advance, 

Ryan

**Comment by olifolkerd** [comment]
Hi @ryaneric100 

What particular issues are you experiencing?

Cheers

Oli :)

**Comment by ryaneric100** [comment]
Hi Oli

thnx for your comment. I want to use tabulator in a Joomla module but I can't get it running. Eventually it is jquery problem, I am not sure. 

In the default file of the module I load jquery and the files I need for for tabulator (from cloudfare):

$doc = JFactory::getDocument();
JHtml::_('jquery.framework', true, true);
JHtml::_('jquery.ui');

$doc>addStyleSheet('https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.5.3/css/tabulator.min.css',"text/css");
$doc>addScript('https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.5.3/js/tabulator.min.js',"text/javascript");


then I add a javascript, deined in the helper and module class of joomla:

$doc -> addScriptDeclaration($script_test_table);

and finally call the table via div tag in the default class:

 echo'<div id="example-table"></div>';


.... so I don't what I am missing here. I use the same apporach in Joomla for other libraries (like for example amcharts) and there it works fine...

any help appreciated, 

Ryan

**Comment by ryaneric100** [comment]
sorry was missing a part:

echo '<script type="text/javascript">',

**Comment by olifolkerd** [comment]
Hey @ryaneric100 

If you can hold out a couple of weeks, i have removed jQuery from the latest release so it should be much easier to integrate into other libraries.

Cheers

Oli :)

**Comment by ryaneric100** [comment]
Hi Oli - 

just tried to use tabulator 4 in Joomla - still can't get it working in a module. 

In the defaul class of the module I have the following code: 

	defined( '_JEXEC' ) or die( 'Restricted access' ); 

	$doc = JFactory::getDocument();
        
	$modulePath = JURI::base() . 'libraries/tabulator_4/dist/js/';
	$skinPath = JURI::base() . 'libraries/tabulator_4/dist/css/';

	$doc->addScript($modulePath.'tabulator.min.js' ,"text/javascript");
	$doc->addStyleSheet($skinPath.'tabulator.min.css',"text/css");
	
	$doc -> addScriptDeclaration($script_test_table);
    
	 echo'<div id="example-table"></div>';

any experience, ideas with Joomla?

Thanks a lot, 

Ryan

**Comment by ryaneric100** [comment]
where in $script_test_table I included the example of the quickstart in the helper file of the Joomla module. 

	public static function getTestTable($uniqid)
	{
	
	
	$script ='
	var table = new Tabulator("#example-table", {
 	height:205, 
 	layout:"fitColumns", 
 	columns:[ 
	 	{title:"Name", field:"name", width:150},
	 	{title:"Age", field:"age", align:"left", formatter:"progress"},
	 	{title:"Favourite Color", field:"col"},
	 	{title:"Date Of Birth", field:"dob", sorter:"date", align:"center"},
 	],
 	rowClick:function(e, row){ 
 		alert("Row " + row.getData().id + " Clicked!!!!");
 	},
	});

	
	var tabledata = [
		{id:1, name:"Oli Bob", age:"12", col:"red", dob:""},
		{id:2, name:"Mary May", age:"1", col:"blue", dob:"14/05/1982"},
		{id:3, name:"Christine Lobowski", age:"42", col:"green", dob:"22/05/1982"},
		{id:4, name:"Brendon Philips", age:"125", col:"orange", dob:"01/08/1980"},
		{id:5, name:"Margret Marmajuke", age:"16", col:"yellow", dob:"31/01/1999"},
	];
	
	
	table.setData(tabledata);


	';


	return $script;	
	}

**Comment by olifolkerd** [comment]
Hey @ryaneric100 

sadly im not a Joomla developer so i cant be a great deal of help.

are you getting any errors in your console?

does this article help? https://docs.joomla.org/Adding_JavaScript#Using_a_JavaScript_Framework

Cheers

Oli :)

**Comment by ryaneric100** [comment]
Hi Oli

thanks for the link - I will look into it and let you if it works.  

Cheers, Ryan
