### ISSUE TITLE
Question: specifying a target attribute for URL's in a link field

### ISSUE THREAD

**Issue by shaunhurley** [olifolkerd/tabulator#1322]
Hi,

Apologies if I have missed something glaringly obvious, but I'm using the link field option and trying to have the URL open in a new page, but I haven't been able to find any way to inject a target="_blank" attribute into the underlying <a> tag.  Is there a means of doing such?

Thanks,

Shaun

**Comment by Nyut0n** [comment]
Hi,
see https://github.com/olifolkerd/tabulator/issues/1097

**Comment by shaunhurley** [comment]
Perfect, thank you!
