### ISSUE TITLE
How to use validationFailed?

### ISSUE THREAD

**Issue by jemrusalem07** [olifolkerd/tabulator#1324]
Can you please kindly help me how to use the parameters to show the error? What are the properties I can use? I tried the following but not working. Thank you.

```
$("#example-table").tabulator({

columns:[ //Define Table Columns
        {title:"LINK NAME", field:"label", width:400, editor:true, validator:["required", "minLength:3", "maxLength:250", "string"], headerSort:false}
    ],
    validationFailed:function(cell, value, validators){
        //cell - cell component for the edited cell
        //value - the value that failed validation
        //validatiors - an array of validator objects that failed

        alert( "Column Name: " + cell.field );
        alert( validators[0].type); 
    },
});
```

**Comment by olifolkerd** [comment]
Hey @jemrusalem07 

Thanks for getting in touch,

Have a look through the [Component Object](http://tabulator.info/docs/3.5#components) documentation, that contains all the information you should need.

if you are trying to access the field of a cell then you can use the ***getField*** functionL

```js
alert( "Column Name: " + cell.getField() );
```

I hope that helps,

Cheers

Oli :)

**Comment by jemrusalem07** [comment]
thank you very much!

**Comment by jemrusalem07** [comment]
I'm able to get the values now and shows in alert.
I just want to show alert message once but it keeps showing endlessly. Would you know why this happens? Thank you again.

	validationFailed:function(cell, value, validators){
	     alert( "Column Name: " + cell.getField() + ", Value: " + value );
             return false;
	}

**Comment by jemrusalem07** [comment]
I'm trying to check if there's error in validation before I will allow the form to be submitted.
I set $hasError variable to true if there's error.
However if there's no error, it doesn't pass in validationFailed function already so that I cannot set the $hasError to false and for me to allow form to be submitted in the javascript.

	validationFailed:function(cell, value, validators){
	 	$fieldName = cell.getField();
	 	if ($fieldName=="label") { 
		 	$errorMsg =  "Invalid value for column Description, character length should be 3 to 350 only.";
		 	$hasError = true;
		} else {
			$hasError = false;
		}   
	}



$("#save").click(function() {
     	if ($hasError==true) {
		alert($errorMsg);
	} else {
              // Submit Form
             document.getElementById("myForm").submit();
        }
});

**Comment by jemrusalem07** [comment]
Can you please help me know how to do: 

1. Show error message in alert once. The validationFailed shows alert message repeatedly forever.
2. I want to have a submit button that will check first if it have errors before allowing form submit.

Thank you.

**Comment by olifolkerd** [comment]
Hey @jemrusalem07 

The issue is happening because the alert is stealing focus from the cell, which the validation function wont allow because it has failed validation, so the both end up fighting for focus.

Using Java Script alerts is not good practice these days, i would suggest a notification bar or hovering message that is styled to fit with the table.

You can use the ***validationFailed*** and ***cellEdited*** callbacks to toggle a variable outside the table that shows weather it is ok to proceed or not.

I hope that helps,

Cheers

Oli :)

**Comment by jemrusalem07** [comment]
hi @olifolkerd , thank you very much and very much appreciated your help. More power to you!
