### ISSUE TITLE
server side through client (not ajax)

### ISSUE THREAD

**Issue by mikila85** [olifolkerd/tabulator#1325]
We are trying to use tabulator as our main tables component, so far it looks really awesome but we hit a wall with the data fetching.

We have our own communication layer and all requests must go through it.

The options that tabulator gives us are:
1. client (feed the table all the data on init)
2. server (give the table a url and it will make the calls by it self via ajax)

We need a third option (that might be there and we are missing it or that it is easy to add) which will invoke a function with the parameters (sort, filter, page...) and we will get the data using our request and call a callback/promise with the data.

please help.

**Comment by erez86** [comment]
+1

**Comment by Nyut0n** [comment]
what keeps you from fetching the data using whatever method you like and then forward it to tabulator like this:
```javascript
$("#example-table").tabulator("setData", tableData);
```

?

**Comment by mikila85** [comment]
Thanks @Nyut0n for the fast response, we tried it in both options.
1. Client: page/filter/sorting changes does not trigger an event/callback for us to reSet the data.
2. Server: we tried to return false on `ajaxRequesting` and then do our request and set the data like you said but it causes a "maximum stack reached" loop.

Is there something we missed?

**Comment by olifolkerd** [comment]
Hey @mikila85

Thanks for getting in touch,

You ask a good question, and as it happens helps is on the way...

So at the moment this isnt really possible, you could create a lot of bindings to the filtering, and sorting callbacks to go and get your data then trigger the ***setData** function, but in your usage case that would be a lot of work.

In version 4.0 (revised launch date is now end of aug) it will be moving to a promised based architecture for the ajax request. you will have the option to replace the ajax handling promise with your own promise, that can go away and do any processing you like and then return the data to Tabulator.

so if you can wait a few weeks all your prayers will be hopefully answered.

I hope that helps,

Cheers

Oli :)

**Comment by mikila85** [comment]
Hi @olifolkerd,
We were so happy to see your answer!
Thank you very much for your taking the time to write and explain all of this :)
We will look forward to V4.0 and for now hold our tables development.

Cheers
Miki

**Comment by erez86** [comment]
Hi @olifolkerd 

Any news about the 4.0 version release with the promise data/fetch function?

Thanks,
Erez
