### ISSUE TITLE
Ho to download the grouped data from tabulator in below format..

### ISSUE THREAD

**Issue by prk53** [olifolkerd/tabulator#1326]
![grouped data](https://user-images.githubusercontent.com/41157621/43766381-e76db0e4-9a4f-11e8-8423-8e20df77e124.PNG)
 i want to download  the above table  data in a csv format described below:---

![download_csv](https://user-images.githubusercontent.com/41157621/43766741-e5ff3830-9a50-11e8-89cc-120590dc6a66.PNG)

How to get  data, in this format, getting no clue... please  help.

**Comment by olifolkerd** [comment]
Hey @prk53 

Im afraid at the moment the download function only works with the table data itself, not with any grouping.

This functionality is on the roadmap and should be available in a couple of releases time.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @prk53 

As there is a lot of interest in new features for the download functionality i have created one issue where people can share their thoughts.

#1436

Cheers

Oli :)
