### ISSUE TITLE
rowDblClick does not deliver data

### ISSUE THREAD

**Issue by Aspersat** [olifolkerd/tabulator#1327]
i got this code:

  columns:[
              {rowHandle:true, formatter:"handle", headerSort:false, frozen:true, width:30, minWidth:30},
              {title:"CollectionID", field:"CollectionID", sorter:"string", width:200},
              {title:"CollectionName", field:"CollectionName", sorter:"string", width:200},
              {title:"Order", field:"OrderNum"},
              {title:"Start", sortable:false}           
          ],
          rowMoved:function(row){
           alert("row moved");
           alert(row.getPosition(true));
           alert(row.getData().CollectionID);     
          },
          rowDblClick:function(row){
            alert("row Doubleclicked");
            alert(row.getPosition(true));
            alert(row.getData().CollectionID); 
          },

if i move a row i get three alerts the first is "row moved" and the other two containing the Information needed (Position and CollectionID

if I doubleclick a row i get only one alert "Row doubleckliced" the others do not work.

Am I missing something?

**Comment by olifolkerd** [comment]
Hey @Aspersat 

You are missing an argument in your ***rowDblClick*** function. the first argument is the click event object, the second is the row component.

It should be:

```js
$("#example-table").tabulator({
        rowDblClick:function(e, row){
        //e - the click event object
        //row - row component
    },
});
```

I hope that helps,

Cheers

Oli :)
