### ISSUE TITLE
headerFilterParams and editorParams as function dosen't  work

### ISSUE THREAD

**Issue by Roman9961** [olifolkerd/tabulator#1328]
I initialize a table with a row:

{
                title: "Send Status",
                field: "status",
                align: "left",
                width: 50,
                editor:"select",
                editorParams:statusFilter,
                headerFilter:true,
                headerFilterParams:statusFilter
            }

`var statusFilter = function(cell){

    var rows = $("#shortNumber-table").tabulator("getRows");

    var options = {};

    rows.forEach(function(row){

        var data = row.getData();

        options[data.status] = data.status;

    }
);
    return options;
};
`
but after tabulator("setData", data) I have empty select in header filter

**Comment by olifolkerd** [comment]
Hey @Roman9961 

Im afraid that currently isnt a feature in Tabulator, but it will be comming in this month 4.0 release.

Cheers

Oli :)
