### ISSUE TITLE
Filtering Table Data

### ISSUE THREAD

**Issue by mriganksingh** [olifolkerd/tabulator#1329]
Can Multiple Checkboxes be applied to filter table data instead of typing?

**Comment by olifolkerd** [comment]
Hey @mriganksingh 

You can filter data however you like using the ***setFilter*** function.

are you asking about header filters?

Cheers

Oli :)

**Comment by mriganksingh** [comment]
Sir I was trying to filter table data based on checkbox inputs, the same as we have on e-commerce websites. So can I achieve that with tabulator?

**Comment by olifolkerd** [comment]
Hey @mriganksingh 

You certainly can, you just need to build a function that is triggered by a change of the checked state of your check boxes and the builds a set of filters to pass to the ***setFilter*** function.

I hope that helps,

Cheers

Oli :)

**Comment by mriganksingh** [comment]
![screenshot 98](https://user-images.githubusercontent.com/28643525/44004984-5003554a-9e89-11e8-8eab-fa855969ccb8.png)

I want my table's current_class column filtered by two values to say 1 and 2, currently can only give one value that is 2.How to give two values and result of the rows containing those two values are displayed?

**Comment by olifolkerd** [comment]
Hey @mriganksingh 

You can use complex filtering for that:

```js
var val1 = 32;
var val2 = 45
$("#example-table").tabulator("setFilter", [
    [
        {field:"current_class", type:"=", value:val1}, //check that current_class has a value of 32
        {field:"current_class", type:"=", value:val2}, //or a value of 45
    ]
])
```
nesting the filters in a second array makes the ***serFilter*** function treat them as OR's rather than AND's.

Full details of how to use the filter system can be found in the [Filtering Documentation](http://tabulator.info/docs/3.5#filtering)

Cheers

Oli :)
