### ISSUE TITLE
Generate duration using system date and another date from json file

### ISSUE THREAD

**Issue by kjdabbous** [olifolkerd/tabulator#1330]
Hi Oli!

I am using tabulator.info to display a table from a json file.

The json includes employee_id, entry_time, exit_time & duration.

There are cases when the exit_time is available (employee did exit) and other cases where the employee has not yet left so exit_time is null.

How is it possible to generate column stay_duration which is the duration between exit_time & entry_time if exit does exist, otherwise if exit_time is null then stay_duration would be the difference between current system date and entry_time displaying a ticking duration (by the second) in hh:mm:ss format?
[employee_log_tabulator.zip](https://github.com/olifolkerd/tabulator/files/2271792/employee_log_tabulator.zip)

**Comment by olifolkerd** [comment]
Hey @kjdabbous 

Thanks for getting in touch.

You can certainly do that, you could create an extra column in your table that references a field that is not in your data, lets call it "diff", then you could assign a [Mutator](http://tabulator.info/docs/3.5#mutators) to that column to calculate the value for that cell.

I hope that helps,

Cheers

Oli :)
