### ISSUE TITLE
Error while loading columns via JSON

### ISSUE THREAD

**Issue by ptwline** [olifolkerd/tabulator#1331]
I'm new to tabulator, love the program, I'm having trouble with dynamic columns. I want to return both Data and Columns with JSON. Using Doc Ready, and I've tried with the columns defined and with the commented out as below. Reading through this help guide I see some comments about special handling for JSON returns for columns and Data, but doesn't really show any examples. I validated my JSON data and it appears test correct. 
Any help is greatly appreciated. Cheers Paul
 $(document).ready(function () {
             $("#example-table").tabulator({
                 height: 205, // set height of table (in CSS or here), this enables the Virtual DOM and improves render speed dramatically (can be any valid css height value)
                 layout: "fitData", //fit columns to width of table (optional)
                // columns: [ //Define Table Columns
                  //   { title: "Course", field: "Coursename", xwidth: 150 },
                  //   { title: "Passed", field: "Pending", align: "left", xformatter: "progress" },
                   //  { title: "Completed", field: "Completed" },
                   //  { title: "Failed", field: "Missed", sorter: "date", align: "center" },
                // ],
                 rowClick: function (e, row) { //trigger an alert message when the row is clicked
                     alert("Row " + row.getData().id + " Clicked!!!!");
                 },
             });          
             
             $.ajax({
                 "url": '/admin/reports/?test=HELLO%20WORLD!',
                 "success": function (json) {
                     var tableHeaders;
                     var tdata;
                    tableHeaders = JSON.stringify(json.columns);
                     console.log(tableHeaders);
                     tdata = JSON.stringify(json.data);
                     $("#example-table").tabulator("setData", tdata);
                     $("#example-table").tabulator("setColumns", tableHeaders);
                     console.log(tdata);
                   },
                 "dataType": "json"
             });
            });
tableHeaders
[{"title":"Course","field":"Coursename","xwidth":"150"},{"title":"Passed","field":"Pending","align":"left","xformater":"progress"},{"title":"Completed","field":"Completed"},{"title":"Failed","field":"Missed","sorter":"date","align":"center"}]

Error Returned
Unhandled exception at line 2, column 2127 in https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.5.3/js/tabulator.min.js
0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'forEach'

**Comment by Keorl** [comment]
You don't have to stringify your data. Json is already parsed into js objects by ajax, you can pass the result directly : 
$("#example-table").tabulator("setData", json.data);
$("#example-table").tabulator("setColumns", json.columns);

**Comment by ptwline** [comment]
You are a steely-eyed missile man. Thank you very much.
