### ISSUE TITLE
XLSX data export date problem

### ISSUE THREAD

**Issue by Roman9961** [olifolkerd/tabulator#1332]
here is my column
 {
                title: "Date",
                field: "calldate",
                sorter: "date",
                sorterParams: {format: "DD-MM-YY hh:mm:ss"},
                minWidth: 60,
                accessorDownload:accessorDateTime
            }

```
var accessorDateTime =function(value, data, type, params, column){
        return moment(value).format("YYYY-MM-DD HH:mm:ss");
    }
```

in exported file all date cells have a single qoute at start  '2018-07-03 13:00:15
I'm also tying format like this "YYYY-MM-DDTHH:mm:ss" but have the same result

**Comment by olifolkerd** [comment]
Hey @Roman9961 

That is odd, what happens if your log the output of your format to the console? does it display correctly there?

Cheers

Oli :)

**Comment by Roman9961** [comment]
Yes in console everything looks fine
here is console
![image](https://user-images.githubusercontent.com/22012446/44016962-893f9bec-9edf-11e8-8590-0b0b2e8f0a94.png)
and here what i have in excel
![image](https://user-images.githubusercontent.com/22012446/44017057-c49a8c1a-9edf-11e8-8199-bac82b4c8c0d.png)

**Comment by olifolkerd** [comment]
Hey @Roman9961 

I can see your issue, your data is not formatted correctly. 

your date time is:
18-7-02 15:44:28,

but to be correctly formatted matching the formatter "YYYY-MM-DD HH:mm:ss" it should be:
2018-07-02 15:44:28

I hope that helps,

Cheers

Oli :)

**Comment by Roman9961** [comment]
???  Data formated exactly as you say "YYYY-MM-DD HH:mm:ss"
