### ISSUE TITLE
Number Page in the PDF table data export feature

### ISSUE THREAD

**Issue by VeinzX** [olifolkerd/tabulator#1334]
Is there any way to put something like "1 out of 4" in the exported PDF with the data of the table?

Thanks for your hard work!

**Comment by olifolkerd** [comment]
Hey @VeinzX 

Not at the moment, but there will be a load of improved PDF functionality coming in the version 4.0 release in a few weeks time, so keep your eyes peeled for more news.

Cheers

Oli :)

**Comment by VeinzX** [comment]
That's sweet, thanks Oli!


I do not know if I should open a new issue for another question, anyway I'll ask another question here if you do not mind :)


It's possible to invert the selected rows in the table? Example:

In a table with 10 rows i select the row 2 and 8, if i click the "invert selected data" all rows but 2 and 8 will be the selected ones.


Thanks for your help and hard work Oli, i love your work! :)

**Comment by VeinzX** [comment]
I found a solution, here's the code if someone needs it too.

$("#inverse-selection").click(function(){
var allrows = $("#example-table").tabulator("getRows");
allrows.forEach(function(row){
    row.toggleSelect();
});

Thank you again!
