### ISSUE TITLE
cellClick Function using JSON delivered setColumns Data

### ISSUE THREAD

**Issue by ptwline** [olifolkerd/tabulator#1335]
Sorry for the newbie questions but I'm delivering my columns using JSON so I can build the Table Dynamically. Is there a way to target cells using the cellClick function? I'm not able to pass the function using JSON since its evaluated as a string. Both Columns and Data are delivered in a JSON array and then I use setData and setColumns to invoke the tabulator table.

**Comment by Nyut0n** [comment]
Since JSON doesn't stringify and parse functions, I think you have to modify your array before you pass it into setColums.

Example:
```javascript
$("example-table").tabulator( "setColumns", yourColumns.map( function(column) {
  if( column.field === 'something' ) column.cellClick = function() { /* do something */ };
  return column;
} );
```
