### ISSUE TITLE
Tabulator

### ISSUE THREAD

**Issue by PayalY** [olifolkerd/tabulator#1338]
In button click ,how to checked the cheboxes of all filter data??

This is my code :-

In tabulator this is column .I add the checkbox,
{
                    title: "Select", field: "Id", width: 42, align: "center",topCalc:Count, frozen: true, formatter: function (cell, formatterParams) {
                        var row = cell.getValue();
                        return "<div class='checkbox-custom checkbox-primary' style='margin-top:0px;margin-bottom:0px'><input type= 'checkbox' class='test' id='chktest' onchange='selectRow(" + row + ",this)' /><label></label></div>"; //return the contents of the cell;
 },
 In cellclick it work correct.

I taken button

 <button type="button" class="btn btn-sm btn-icon btn-dark btn-round waves-effect waves-classic" title="Selele parts" data-placement="top" id="btnSelectFilter" value="" onclick="SelectFilterRecords()">
                    <i class="icon fa-check-square-o" aria-hidden="true"></i>
                </button>

In onclick event write the following function,

 function SelectFilterRecords() {
$("#Indenttable").tabulator('selectRow', true);
}

for that function select all the filter record but checkbox is not checked 
So How to checkbox is checked all the filter records??

**Comment by Rodbjartson** [comment]
First off, use code brackets when posting code <>. You can find them in the menu within your comment.

Secondly, I do not understand what you want.

Please provide:
-The table constructor 
-The onClick() function

**Comment by PayalY** [comment]
In cell click checkbox checked and unchecked work properly.But filter records on a button click select all records but checkbox is not checked. 


This is my table structure 
< 


$("#Indenttable").tabulator({ 
height: 500, 
tooltips: true, 
tooltipsHeader: true, 
index: "Id", 
columns: [ 
// { title: "Status", field: "Status", formatter: "textarea", align: "Center", headerFilter: "input", align: "center", visible: false }, 

{ 
title: "Select", field: "Id", width: 42, align: "center",topCalc :Count, frozen: true, formatter: function (cell, formatterParams) { 
var row = cell.getValue(); 
return "<div class='checkbox-custom checkbox-primary' style='margin-top:0px;margin-bottom:0px'><input type= 'checkbox' onchange='selectRow(" + row + ",this)' /><label></label></div>"; //return the contents of the cell; 

}, 
}, 


{ title: "Part code", field: "Pcode_code", formatter: "textarea", width: 190, headerFilter: "input", align: "left", frozen:true }, 
{ 
title: "", field: "indstatus", visible: true, width: 70, align: "Center", headerFilter: "input", 
formatter: function (cell, formatterParams) { 
var value = cell.getValue(); 
if (value == "In progress") { 
return "<i class='icon md-circle' aria-hidden='true' style='color: Yellow;font-size: 14px;' title='In process'></i>"; 
} 
else if (value == "GRN done after commitment") { 
return "<i class='icon md-circle' aria-hidden='true' style='color: Orange;font-size: 14px;' title='GRN done after commitment'></i>"; 
} 
else if (value == "GRN done on/before commitment") { 
return "<i class='icon md-circle' aria-hidden='true' style='color: Green;font-size: 14px;' title='GRN done on/before commitment'></i>"; 
} 
else if (value == "Commited date is crossed") { 
return "<i class='icon md-circle' aria-hidden='true' style='color: Red;font-size: 14px;' title='Commited date is crossed'></i>"; 
} 
}, 
}, 
{ 
title: "Description", field: "Pcode_Description", formatter: "textarea",width: 282, align: "left", headerFilter: "input", visible: false 
}, 
{ title: "Cost Center", field: "cost", width: 70, headerFilter: "input" }, 
{ title: "Qty UOM", field: "UOM", width: 60, headerFilter: "input" }, 
{ 
title: "Status", field: "strstatus", width: 140, headerFilter: "input" 
, formatter: function (cell, formatterParams) { 
var value = cell.getValue(); 
return "<label title='" + cell.getData().Remarks1 + "'>" + value + "</label>"; 
}, 
}, 
{ title: "Indent Date", field: "SavedOn", width: 81, align: "Center", headerFilter: "input", align: "left", sorter:"date", sorterParams:{format:"DD/MM/YY"}}, 
{ title: "Req.Date", field: "date", width: 76, align: "Center", headerFilter: "input", align: "left" ,sorter:"date", sorterParams:{format:"DD/MM/YY"}}, 
{ title: "Commited Date", field: "strCommitedDate", width: 76, align: "Center", headerFilter: "input", align: "left",sorter:"date", sorterParams:{format:"DD/MM/YY"}}, 
{ title: "PO Date", field: "PODate", width: 76, align: "Center", headerFilter: "input", align: "left", sorter:"date", sorterParams:{format:"DD/MM/YY"} }, 
{ title: "GRN Date", field: "GRNdate", width: 76, align: "Center", headerFilter: "input", align: "left",sorter:"date", sorterParams:{format:"DD/MM/YY"} }, 
{ title: "Last Updated On", field: "UpdatedOn", width: 84, align: "Center", headerFilter: "input", align: "left",sorter:"date", sorterParams:{format:"DD/MM/YY"} }, 
{ 
title: "Indent No", field: "Id1", width: 58, align: "Center", headerFilter: "input", align: "left" 
, formatter: function (cell, formatterParams) { 
var value = cell.getValue(); 
return "<label title='" + cell.getData().location + "'>" + value + "</label>"; 
}, 
}, 
{ title: "PO No", field: "PONo", width: 166, align: "Center", headerFilter: "input", align: "left" }, 
{ title: "Vendor Name", field: "VendorName", width: 166, align: "Center", headerFilter: "input", align: "left" }, 
{ title: "Indenter", field: "username1", width: 100, align: "Center", headerFilter: "input", align: "left", visible: false }, 
{ title: "Last Updated By", field: "username", width: 71, align: "Center", headerFilter: "input", align: "left" }, 
{ title: "Id", field: "Id", width: 43, align: "Center", headerFilter: "input", align: "left", visible: false }, 
{ title: "Division", field: "DivisionName", width: 88, align: "Center", headerFilter: "input", align: "left", visible: false }, 
{ 
title: "SCM remarks", field: "Remarks1", width: 150, align: "Center", headerFilter: "input", align: "left" 
}, 
{ title: "Location", field: "location", width: 88, align: "Center", headerFilter: "input", align: "left" }, 
{ 
title: "Indent Remarks", field: "PartRemarks", headerFilter: "input", width: 150, align: "left" 
}, 
{ 
title: "Indenter's Remarks", field: "Indenterrmk", headerFilter: "input", width: 150, align: "left" 
}, 
{ title: "Expected date", field: "strExpectedDate", width: 88, align: "Center", headerFilter: "input", align: "left", visible: false ,sorter:"date", sorterParams:{format:"DD/MM/YY"}}, 
{ title: "PO Handler", field: "POhandler", width: 88, /*align: "Center",*/ /*headerFilter: "input", align: "left",*/ }, 
{ title: "Is Assembly", field: "IsAssembly", width: 30, headerFilter: "input", formatter: function (cell, formatterParams) { 
if (cell.getData().IsAssembly ==1) { 
return "Yes"; 
} 
else 
return "No"; 
},}, 
{ title: "Module No", field: "ModuleNo", width: 70, headerFilter: "input" }, 
{ title: "Assembly status", field: "AssStatus", width: 88, /*align: "Center",*/ /*headerFilter: "input", align: "left",*/ editor: AssemblyEditor }, 
{ 
title: "cnt", field: "cnt", width: 30, visible: false, formatter: function (cell, formatterParams) { 
document.getElementById("hdncnt").value = cell.getValue(); 

}, 
}, 

], 
}); 
> 

Button:- 
< 


<button type="button" class="btn btn-sm btn-icon btn-dark btn-round waves-effect waves-classic" data-toggle="tooltip" data-original-title="Selele parts" data-placement="top" id="btnSelectFilter" value="" onclick="SelectFilterRecords()"> 
<i class="icon fa-check-square-o" aria-hidden="true"></i> 
</button> 
> 

Onclick function:- 
< 


function SelectFilterRecords() { 
$("#Indenttable").tabulator('selectRow', true); 


} 
> 
----- Original Message -----
