### ISSUE TITLE
Headers are not align with content while scrolling

### ISSUE THREAD

**Issue by bvisonl** [olifolkerd/tabulator#134]
I have seen similar issues here already but not quite the one that I am experiencing. When I have a table and the page loaded with all the content everything is well aligned, as soon as I start moving the X Scroll the header doesn't go along with the columns:

All good initially:
![11111111](https://cloud.githubusercontent.com/assets/4421747/21194605/8c9cbc76-c1fe-11e6-9241-e7bd1610d658.PNG)

When scrolling:
![2222222222222](https://cloud.githubusercontent.com/assets/4421747/21194617/91d2f444-c1fe-11e6-943a-93b7ac69be31.PNG)

My javascript:
`        $("#logs_tabulator").tabulator({
                height: "500px",
                pagination: "remote",
                ajaxURL: '/list',
                columns:[
                    {title:"id", field:"id", sorter:"string", width: "5%"},
                    {title:"date", field:"date", sorter:"string", width: "15%"},
                    {title:"level", field:"level", sorter:"string", width: "10%"},
                    {title:"action", field:"action", sorter:"string", width: "10%"},
                    {title:"entity", field:"entity", sorter:"string", width: "20%"},
                    {title:"message", field:"message", sorter:"string", width: "30%"},
                    {title:"user", field:"user", sorter:"string", width: "15%"},
                    {title:"exception_code", field:"exception_code", sorter:"string", width: "10%"},
                    {title:"exception_line", field:"exception_line", sorter:"string", width: "10%"},
                    {title:"exception_file", field:"exception_file", sorter:"string", width: "20%"},
                    {title:"serialized_entity", field:"serialized_entity", sorter:"string", width: "20%"},
            ],
        });`

I am not sure if this is a bug or what.. I have tested this on Chrome Version 54.0.2840.99 m (64-bit) and also on Firefox 50.1.0

One thing that I just noticed while writing this is that this only happens if I use the Width property, for the sake of testing I removed the width of all columns and manually expanded all the columns so that the X scroll appeared and when I scrolled then it did not happen.

Any ideas?

**Comment by olifolkerd** [comment]
It appears to be an issue with percentage widths, i will have a look into it this evening for you

**Comment by olifolkerd** [comment]
Turns out there are two issues going on here:

- As the scroll occurs the header element is stretching, causing the percentage contents to stretch
- When the table is resized, the percentage changes do not update the columns, only the headers

It will take me a couple of days to get round to fixing this, i will let you know when it is all back up and working.

Sorry for the inconvenience

Oli

**Comment by bvisonl** [comment]
I see, glad you could identify the problem.

Thank you for your quick response also!, and no inconvenience at all, glad to be helping on finding these small things!

Will keep an eye for the fix :) 

Thanks!

**Comment by olifolkerd** [comment]
I have committed a fix for this, it required changes in the css and js so make sure you pull down a new copy of Tabulator.

Let me know how it goes for you

Oli

**Comment by bvisonl** [comment]
Hey,

Your fix worked perfectly!...now is that I had the time to test it out..crazy month..

I have found something else though, this is not a huge deal but when I enabled movable columns and you scroll and then try to move a column the headers misalign again until you try to scroll or resize..

See a picture: 

1. During the column grab
2. After the column is dropped somewhere else

![issue](https://cloud.githubusercontent.com/assets/4421747/21566680/281570b4-ce73-11e6-88bd-89eb81b91fde.png)

Let me know what you think and/or if you want to reopen this same issue or a new one for this.

**Comment by olifolkerd** [comment]
Is this issue with percentage widths as well?

**Comment by bvisonl** [comment]
Seems to be, I am only using percentages, it happened with exactly the same settings from above, I just updated the tabulator as you indicated and noticed that right away

**Comment by olifolkerd** [comment]
Ok no problems,

As the percentage widths are new there are bound to be a few niggles here and there to sort. I will have a look into that over the weekend.

Could you send over a coyt of your tabulator constructor so i have a good starting point.

Cheers

Oli

**Comment by bvisonl** [comment]
sure:
$("#logs_tabulator").tabulator({
                height: "600px",
                pagination: "remote",
                paginationSize: 20,
                movableCols:true,
                persistentLayout: true,
                persistentLayoutID:"abcdefehijklmn",
                ajaxURL: "/list"
                columns:[
                    {title:"Id", field:"id", sorter:"string", width: "5%"},
                    {title:"Date", field:"date", sorter:"string", width: "15%"},
                    {title:"Level", field:"level", sorter:"string", width: "10%"},
                    {title:"Action", field:"action", sorter:"string", width: "10%"},
                    {title:"Entity", field:"entity", sorter:"string", width: "20%"},
                    {title:"Message", field:"message", sorter:"string", width: "30%"},
                    {title:"User", field:"user", sorter:"string", width: "15%"},
                    {title:"Exception Code", field:"exception_code", sorter:"string", width: "10%"},
                    {title:"Exception Line", field:"exception_line", sorter:"string", width: "10%"},
                    {title:"Exception File", field:"exception_file", sorter:"string", width: "20%"},
                ],
            });
