### ISSUE TITLE
Header css trouble

### ISSUE THREAD

**Issue by Roman9961** [olifolkerd/tabulator#1343]
Hi! I have multiple select filter in header and I need it looks like this
![image](https://user-images.githubusercontent.com/22012446/44024724-d3e2e37c-9ef6-11e8-846b-9cac1aa098a6.png)
with default css  it hide  inside header and it looks
![image](https://user-images.githubusercontent.com/22012446/44024860-25624314-9ef7-11e8-82d9-1b64bc46ebc9.png)
I find solution: I set .tabulator-header and .tabulator-col  overflow:initial; but then I have another problem: when content of the table have scrolling the header stucks
![image](https://user-images.githubusercontent.com/22012446/44025095-d1c5033a-9ef7-11e8-92fa-61a87c7fdce6.png)

...and one more, this multiple select is inside .tabulator-col and when I click on select, sorting event is fired, I try to set stopPropagation() and it work but sort still fired please help me solve these problems.

**Comment by olifolkerd** [comment]
Hey @Roman9961 

Im afraid what you are looking for isnt possible if you are trying to add your popup to the column header element.

What i would suggest you do (and it is what a lot of popups and context menus do) is to add your popup element to the root of the DOM (the body tag) and absolutely position it on the page by the header element, that way there are no overflow issues to consider.

The propagation issue is likely down to an issue with the event binding you are using but without more information about the code you have used i would be unable to offer any specific advice.

Cheers

Oli :)
