### ISSUE TITLE
Question around dynamically grouping rows

### ISSUE THREAD

**Issue by jmjdev** [olifolkerd/tabulator#1353]
Hi Oli,

I was wondering if there is a way that I can pass a variable containing the expression for grouping to the groupBy option?

Currently, I am doing this like below but would like to remove the need for eval:

```
if (groupByValue .indexOf("function")>=0) {
	groupByValue = [eval('(' + groupByValue + ')')];
}

$("#"+tabulatorTable).tabulator({
	groupBy:groupByValue,
});
```
where `groupByValue` could be something like:
`var groupByValue = "function(data) {return data.xID + ' - ' + data.xDescription + ' - ' + data.xStatus + ' - Some Details: ' + data.xDetails;}";`
or:
`var groupByValue = "xDescription";`

I'm happy to change the data sctructure if necessary, though I'm not sure where to begin.

I was thinking I could extend `groupRows` for this, but again, not sure where to begin.

Any help would be greatly appreciated.

Thanks,

Jack

**Comment by olifolkerd** [comment]
Hey @jmjdev 

Sorry for the delayed response.

you can pass a function into the ***gruopBy*** option, that can be used to determine the group,

```js
groupBy:function(data){
    //data - the data object for the row being grouped
    return data.gender + " - " + data.age; //groups by data and age
}
```

I hope that helps,

Cheers

Oli :)

**Comment by jmjdev** [comment]
If anyone is curious, I got this to work using this:

First, I added the columns and text I wanted, separated by a comma, to the tabulator div.
`data-group-by="someID,xDescription,xStatus,Description:,xDescription"`

Then the construct.
```
$('div.tabulator-table').each(function () {

	...
	var groupByValue =this.getAttribute("data-group-by");

	...
	if (groupByValue) {
		var gbFnParams = groupByValue;
	}
	else {
		var gbFnParams = "";
	}

	$("#"+tabulatorTable).tabulator({
		...
		groupBy:function(data){
			if (gbFnParams) {
				var res = gbFnParams.split(",");
				var str = "";
				jQuery.each(res, function(i, val) {
					if (val.charAt(0) == val.charAt(0).toUpperCase()) {
						str = str + val + " ";
					} else  {
						res = data[val];
						str = str + res + " - ";
					}
				});
				str = str.substring(0, str.length - 3);
				return str;
			}
		},
		...
	});
});
```
