### ISSUE TITLE
rows not rendering inside hidden container in IE and FF

### ISSUE THREAD

**Issue by mikexmagic** [olifolkerd/tabulator#1354]
Hi,

I use tabulator in a jquery UI tab widget. The table is part of the second tab which is hidden when the widget is showing. I set the table data before I show the tab widget.
When I click on the second tab, the table rows are not rendered. But I can access the table data.
It needs a 'redraw', then the rows appears. Also resizing the browser will render the rows.

I have this issue only in IE and FF. Chrome works well...

What can I do?

Thx, Mike :-)

**Comment by Nyut0n** [comment]
Hey @mikexmagic ,
you have named both the problem and the solution already. If you are using Tabulator in UI-Tabs, you're supposed to call the **_redraw_** function when the tab activates. See the official answer and a code sample here: https://github.com/olifolkerd/tabulator/issues/272

**Comment by mikexmagic** [comment]
@Nyut0n 
thx, I will. :-)
