### ISSUE TITLE
Creating and deleting rows in nested tables

### ISSUE THREAD

**Issue by olizhu** [olifolkerd/tabulator#1355]
Hi Oli,

Thanks so much for this wonderful library, it's by far the best table library I've used and your documentation is superb.

I have a question on modifying rows in nested tables.
I need create and delete buttons on each row of my table. For example, in a flat table, the following definition in columns works fine to delete a row:

    cellClick:function(e, cell){
        cell.getRow().delete();
    }

In a nested table, the UI changes to show the deleted row, but if I call `getData` on the parent table, the original data is shown. My guess would be that the new tabulator instance being created does not feed back changes in the table size to its parent table.

I've been trying to figure out a workaround and I think I should be able to get it to work by using the `updateRow` function on the parent table instead. But to do this, I will need to get the row id of the parent table when the user clicks on a row inside a nested table. Is there a way to obtain this?

**Comment by Nyut0n** [comment]
Hi @olizhu ,
as a workaround, maybe you can use a **_rowClick_** callback on the parent table that calls the **_normalizeHeight_** function on its own row. That should work if the event is propagated through the nested table all the way down to the parent table's row.

**Comment by olifolkerd** [comment]
Hey @olizhu 

You are correct, data passed into a table is isolated from its source so deleting it in one table will not cause it to be deleted in another.

When you declare the sub-table in the row formatter there is nothing to stop you using the row component passed into the scope of that function in your sub-table callbacks.

The example nested table code below outlines what im talking about. towards the bottom of the example have a look inside the ***cellClick*** callback, it references the parent row component.

```js
//define table
$("#example-table").tabulator({
    height:"311px",
    layout:"fitColumns",
    resizableColumns:false,
    data:nestedData,
    columns:[
        {title:"Make", field:"make"},
        {title:"Model", field:"model"},
        {title:"Registration", field:"reg"},
        {title:"Color", field:"color"},
    ],
    rowFormatter:function(parentRow){
        //create and style holder elements
       var holderEl = $("<div></div>");
       var tableEl = $("<div></div>");

       holderEl.css({
           "box-sizing":"border-box",
           "padding":"10px 30px 10px 10px",
           "border-top":"1px solid #333",
           "border-bottom":"1px solid #333",
           "background":"#ddd",
       })

       tableEl.css({
           "border":"1px solid #333",
       })

       holderEl.append(tableEl);

       parentRow.getElement().append(holderEl);

       //create nested table
       tableEl.tabulator({
           layout:"fitColumns",
           data:parentRow.getData().serviceHistory,
           columns:[
               {title:"Date", field:"date", sorter:"date"},
               {title:"Engineer", field:"engineer"},
               {title:"DELETE CELL", cellClick:function(cell){
                    parentRow.update({}); //CARRY OUT ACTION ON PARENT ROW
               }},
           ]
       })
    },
});
```

I hope that helps,

Cheers

Oli :)

**Comment by olizhu** [comment]
Thanks for your help @Nyut0n and @olifolkerd - I have implemented Oli's solution and it's working now.
