### ISSUE TITLE
Order and Sort numbers working incorrectly!

### ISSUE THREAD

**Issue by D19cannon** [olifolkerd/tabulator#1358]
Hi guys!

I mentioned in an earlier issue (with another issue within that one) that the **order** function isn't working correctly when it comes to numbers/digits.

Before I was using this simple function according to your documentation:
`order: [[1, "desc"]]`

It sort of works, however, the function thinks that **9** is greater than **45** because it looks at the digit at the first position, thus comparing 9 and 4.

Since there was no response yet on my previous issue. I have been digging around the documentation if I could find an alternative solution. Well there is a **sort** function which  have been trying to implement:

`        
columns: [

          { title: "ID", field: "id", sorter: "number" },

          { title: "Temperature", field: "temperature", sorter: "number" },

          { title: "Update", field: "update", sorter: "number" },

          { title: "Battery", field: "battery", sorter: "number" },

          { title: "Chart", field: "chart", sortable: false }
        ]

      $("#sensor_table").tabulator(
        "setSort",
        "temperature",
        "desc"
      );
`

Any solutions to fix this problem?

Daniel

**Comment by Nyut0n** [comment]
You will have to post your constructor code, ideally with a data sample.
The number sorter works fine in the latest Tabulator version. Can't reproduce your issue. http://jsfiddle.net/wag39wby/64/

**Comment by Roman9961** [comment]
I have same issue, just check the numbers is integers

**Comment by olifolkerd** [comment]
any unexpected spaces or non numeric characters in the value will likely cause the sort to be erratic

**Comment by D19cannon** [comment]
Hi, sorry for the confusion. I haven been working between Tabulator and DataTables, because I keep running into small problems in both of them. 

Honestly, there is a problem with the sort function but then from the DataTables library. I will convert it quickly back to Tabulator to see if it works. (can't remember why I exactly switched between the two of them, I think it had to do with some documentation problems such as the length of the pagination. I will let you know when I do)
