### ISSUE TITLE
Row groups in Tabulator

### ISSUE THREAD

**Issue by aswzen** [olifolkerd/tabulator#136]
How to create row groups in tabulator?

For example i want to group data with Type = 'A', so all data typed 'A' will be grouped or collapsed as default.

Thank you in advance :)

by the way i feel tabulator already surpass all dynatable features... amazing...

**Comment by olifolkerd** [comment]
If you are simply grouping by a field in the data then you can use the ***groupBy*** setup option:

```js
$("#example-table").tabulator({
    groupBy:"type",
    columns:[
        {title:"Name", field:"name"},
        {title:"Type", field:"type"},
    ],
});
```

Documentation for this feature can be found on the website, [here](http://olifolkerd.github.io/tabulator/docs/#grouping)

An interactive demo can be found [here](http://olifolkerd.github.io/tabulator/examples/#grouping) with the code used to make the demo available if you click the green "View Source" button under the table.
