### ISSUE TITLE
Mutator.prototype.mapDepricatedFunctionality variable declaration and compatibility issues

### ISSUE THREAD

**Issue by LeeIsMe77** [olifolkerd/tabulator#1360]
I have upgraded from v3.3 to 3.5.3 and encountered a couple mutator-related bugs.

First and foremost, the Mutator.prototype.mapDepricatedFunctionality function contains 2 lines that both contain compilation errors:

`key = "mutator" + (type.charAt(0).toUpperCase() + type.slice(1));`
`column.defintion[key] = column.definition.mutator;`

On the first line, the variable **type** is not defined, and should probably be **column.definition.mutateType**.
On the second line, **defintion** is misspelled, and should be **definition**.

Further, backwards compatibility with mutators is broken even after correcting the compilation bugs. When switching mutateType to mutatorEdit, as having the property mutator also set (the original property used) results in the mutator being executed on cell edit AND binding data.

**Comment by olifolkerd** [comment]
Hey @LeeIsMe77 

That is a glaring bug there! not sure how that one made it through!

I will make sure that is fixed in the upcomming 4.0 release.

Cheers

Oli

**Comment by olifolkerd** [comment]
I have just pushed a fix for this to the 4.0 branch.

Thanks for letting me know.

Cheers

Oli :)
