### ISSUE TITLE
Icons as column titles

### ISSUE THREAD

**Issue by mikehobson** [olifolkerd/tabulator#1361]
Hi, newbie question is it possible to have the column headers as an icon rather than as text, im limited with space and an icon would really help my layout rather that text

Thanks

Mike

**Comment by mikehobson** [comment]
Hi , Sorry I didnt explain well, I can see using a formatter i can use icons in the data but what i actually want is to use an Icon in the column titles , so in your screenshot instead of having the text Ordertype Id like to use an icon

**Comment by Nyut0n** [comment]
Use titleFormatter to format headers. It works the same way as formatters.
You can also write plain HTML into the title property. It isn't sanitized iirc.

**Comment by Rodbjartson** [comment]
@Nyut0n could you provide an example?:) Would be very useful!

**Comment by mikehobson** [comment]
Hi thats working fine, thank you

**Comment by Nyut0n** [comment]
> @Nyut0n could you provide an example?:) Would be very useful!

using titleFormatter:
```{field: "something", align: "center", titleFormatter: function() { return "<i class='fa fa-print'></i>"; } }```
There's another example in the docs too, which utilizes the default "star" formatter-

using HTML titles:
```{title:"<i class='fa fa-print'></i>", field: "something", align: "center" }```
