### ISSUE TITLE
multi-select functionality

### ISSUE THREAD

**Issue by phineas629** [olifolkerd/tabulator#1362]
Not sure if my search was incorrect.
Sorry if this has already been answered.

Does tabulator have multi-select checkboxes or multi-select dropdown functionality?
Or is there example code somewhere?

I'm interested in using Tabulator as a simple CRUD app but need multi-select functionality for a field in a row.

**Comment by vemyles** [comment]
Hi
I've been working with tabulator for a project. Wonderful tool. I am also interested in being able to implement a multi-select dropdown in a cell. It seems like it would be possible with a custom editor but any pointers or sample code of any kind would be greatly appreciated. Thanks much.

**Comment by tomvanlier** [comment]
I will come back on this, because I will try to do the same soon.

**Comment by olifolkerd** [comment]
Hey @phineas629  and @vemyles 

There is no built in multi-select element as there isnt one built in to HTML and i try not to include external libraries where possible to keep the size of the code base down and not tie people into certain libraries.

if you find a multi select you like, you are of course free to build a [Custom Editor](http://tabulator.info/docs/3.5#manipulating-data) to include that in your table.

Pretty much every part of Tabulator can be extended to add your own functionality.

Cheers

Oli :)
