### ISSUE TITLE
Multi level group top group calculation

### ISSUE THREAD

**Issue by Roman9961** [olifolkerd/tabulator#1364]
![image](https://user-images.githubusercontent.com/22012446/44457718-a867e680-a60c-11e8-9d91-9a3128dc15d9.png)

I have multilevel  group but calculations shows only for inner groups how can I show overal by date group?

**Comment by olifolkerd** [comment]
Hey @Roman9961 

Im afraid that is not an available option, you can either have column calculations that show at the top and bottom of the table, or at the lowest lever of nested grouping.

Cheers

Oli :)
