### ISSUE TITLE
groupStartOpen function bug

### ISSUE THREAD

**Issue by Roman9961** [olifolkerd/tabulator#1365]
there is no group component:
groupStartOpen:function(value, count, data, group){
                            console.log(value, count, data, group);
                            return group.level==0;
 },
![image](https://user-images.githubusercontent.com/22012446/44460448-c6861480-a615-11e8-97fc-648dbb280e52.png)

**Comment by olifolkerd** [comment]
Hey @Roman9961 

Good spot, i have just pushed a fix for this to the 4.0 branch and will include it in the next update

Thank for lett me know

Cheers

Oli :)
