### ISSUE TITLE
groupCalc and regular bottomCalc formatters

### ISSUE THREAD

**Issue by Roman9961** [olifolkerd/tabulator#1366]
I want use different formatter for groupCalc and regular bottomCalc is it possible?

**Comment by olifolkerd** [comment]
Hey @Roman9961 

Im afraid i dont follow you there, there is no such option as ***groupCalc*** , could you clarify what you mean?

Cheers

Oli :)

**Comment by Roman9961** [comment]
I mean bottomCalcFormatter for whole table and for gruop

**Comment by olifolkerd** [comment]
Hey @Roman9961 

Im afraid that is not possible at present.

Sorry

Oli :)
