### ISSUE TITLE
Validation issue after making new row

### ISSUE THREAD

**Issue by tomvanlier** [olifolkerd/tabulator#1368]
Hi there,

I ran into this issue, I think it's a bug. I know some ways I could work around it, but thought I would signal it. Could be doing something wrong myself evidently as well.

I have a tabulator with 4 columns. 1 is this one :

 {title:"Inhoud", field:"inhoud", formatter:"textarea",headerSort:false,editor:true,validator:"required"}

Now when I edit this the validator works fine, but when I first add a row 

$("#todolijstje").tabulator("addRow", {todoid:"", inhoud:"", datum:today, afgesloten:'0'});

then do a callback

                rowAdded:function(row){
     
                                row.getCell("inhoud").edit();
                       
                }

I put the focus on this column, because I want some input (I created a db-row and I want some info there), but when I leave the column and cell empty, the validation doesn't fire and I am left with an empty input. console.log gives nothing for the value of that cell, however when I put something in it all works fine (so the cell doesn't get defined until there's input or anything?).

I will probably make a workaround server-side, because I want to be 100% sure a user inputs something before making a line in the db, but I want to know why the validation fails and the input is empty.

Thx.

Edit: could this be because the newly created row isn't loaded in the original construction of the tabulator?

**Comment by Rodbjartson** [comment]
@olifolkerd gave me this reply in a similiar issue I posted:

> The callback does fire after the row is added to the table, however the cells in a row are not generated until the row is first visible, This is how the Virtual DOM works to speed up rendering of the table it only creates the parts of the table it need to display, therefor it doesn't have to process all the data the moment it is loaded into the table.
> 
> in version 4.0 coming in July i am looking to improve this part of the system, so you may get the ability to get the components then.
> 
> Cheers
> 
> Oli :)

**Comment by tomvanlier** [comment]
Big thanks :)

**Comment by Rodbjartson** [comment]
Did it work?

**Comment by tomvanlier** [comment]
I am waiting on v4.0 to make the last implementations on that (No rush mr Folkerd, I have more than enough other work at hand and v3.5 already is a masterpiece)
