### ISSUE TITLE
Ajax load - pageNo is always 1 when next button is pressed.

### ISSUE THREAD

**Issue by RobyAbraham** [olifolkerd/tabulator#137]
I also tried using paginator but result is same. Is there anything I have to do?

`<script >
          $("#example-table").tabulator({
            pagination: "remote",
            paginationSize: 5,  
            fitColumns: true,
            ajaxURL: "/users?format=json", //ajax URL
            columns: [
            { title: "Id", field: "id", align: "center", },
            { title: "Name", field: "name", align: "center", formatter: "link", },
            { title: "Password", field: "pwd", align: "center", },
            ],
            paginator: function (url, pageNo, pageSize, ajaxParams) {
                //url - the url from the ajaxURL paramter
                //pageNo - the requested page number
                //pageSize - the value of the paginationSize paramter
                //ajaxParams - the value of the ajaxParams parameter

                return "/users?format=json&page=" + pageNo + "&size=" + pageSize; //must return the string of the page request URL
            },
        });
    </script>`

**Comment by olifolkerd** [comment]
The issue is probably arsing because you are passing the ***format*** parameter as part of the URL string which is causing the auto generate URL with the injected ***page*** attribute to be corrupted. you also don't need to create your own custom paginator, Tabulator will do this for you based on your other settings.

The correct way would be to use the ***ajaxParams*** options to set the parameter:
```js
$("#example-table").tabulator({
    pagination: "remote",
    paginationSize: 5,
    fitColumns: true,
    ajaxURL: "/users",
    ajaxParams:{format:"json"},
    columns: [
        { title: "Id", field: "id", align: "center", },
        { title: "Name", field: "name", align: "center", formatter: "link", },
        { title: "Password", field: "pwd", align: "center", },
    ],
});
```

If this doesnt work could you let me know what request is being generated in the network tab of your browses debug console and i  will see what i can do for you.

Cheers

Oli

**Comment by RobyAbraham** [comment]
Thanks for the reply... But this doesn't work for me.... I tried using ajaxParams:{format:"json"},

This is the url generated:
http://localhost:53125/users?format=json&page=1&size=15&sort=user_name&sort_dir=asc

**Comment by olifolkerd** [comment]
Hey Roby,

I see you have closed the issue, did you get to the bottom of what was going wrong?

**Comment by olifolkerd** [comment]
When you click the next button is it the same url generated each time or does the ***page*** value change?

**Comment by RobyAbraham** [comment]
No... the issue is not solved... issue got closed by mistake... the page number is same (1) on every 'Next' button click...

**Comment by olifolkerd** [comment]
do you have an example of the JSON object you are returning in response to the pagination request?

**Comment by olifolkerd** [comment]
do the page number buttons and the other last, first and prev? is it just the next one that is broken?

what browser are you using?

**Comment by RobyAbraham** [comment]
{"last_Page":11,"data":[{"id":9,"user_name":"binimvarghese@gmail.com","pwd":"bini@123EB"},{"id":13,"user_name":"binimvarghese@gmail.com","pwd":"bini@123EB"},{"id":5,"user_name":"binimvarghese@gmail.com","pwd":"bini@123EB"},{"id":21,"user_name":"binimvarghese@gmail.com","pwd":"bini@123EB"},{"id":17,"user_name":"binimvarghese@gmail.com","pwd":"bini@123EB"}]}

Every time Next is clicked url does not change . The url is 
http://localhost:53125/users?format=json&page=1&size=5&sort=user_name&sort_dir=asc

first and prev button is in disabled format
When click last button Loading error happened...
 I use firefox and microsoft edge

**Comment by RobyAbraham** [comment]
{"last_Page":11,"data":[{"id":9,"user_name":"binimvarghese@gmail.com","pwd":"bini@123EB"},{"id":13,"user_name":"binimvarghese@gmail.com","pwd":"bini@123EB"},{"id":5,"user_name":"binimvarghese@gmail.com","pwd":"bini@123EB"},{"id":21,"user_name":"binimvarghese@gmail.com","pwd":"bini@123EB"},{"id":17,"user_name":"binimvarghese@gmail.com","pwd":"bini@123EB"}]}

Every time Next is clicked url does not change . The url is 
http://localhost:53125/users?format=json&page=1&size=5&sort=user_name&sort_dir=asc

first and prev button is in disabled format
When click last button Loading error happened...
 I use firefox and microsoft edge

**Comment by olifolkerd** [comment]
When you server returns paginated data it must use the following format:
```js
{
    "last_page":15, //the total number of available pages
    "data":[ // an array of row data objects
        {id:1, name:"bob", age:"23"}, //example row data object
    ]
}
```

It must return the ***last_page*** property to tell Tabulator how many pages are available, otherwise it will default to one, which is why you are not getting any other pages in the request.

full documentation on remote ajax pagination can be found [here](http://olifolkerd.github.io/tabulator/docs/#pagination-remote)

let me know if that helps.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hod did that go for you? are you back up and running now?

**Comment by olifolkerd** [comment]
Closed due to inactivity
