### ISSUE TITLE
Scrolling is not working properly in firefox(52.9.0 (32-bit)), but same code is working fine in chrome(68.0.3440.106  (64-bit))

### ISSUE THREAD

**Issue by prk53** [olifolkerd/tabulator#1372]
below is the screen shot of table.
In chrome (68.0.3440.106  (64-bit)) table is show properly:- below is chrome version
![test_chorme_image](https://user-images.githubusercontent.com/41157621/44604141-92bc1200-a802-11e8-98d9-af6a97299037.png)

But in firefox (52.9.0 (32-bit)):- table is not getting displayed properly:-
it is showing some rows, below that  some empty space is coming, below is firefox example:--
![test_firefox_image](https://user-images.githubusercontent.com/41157621/44604131-8c2d9a80-a802-11e8-99a6-dd29b2ce934f.png)

below is the complete  code i am using to create tabulator:---

 ** In app.css file** code :-

.tabulator-font {
  font-family: 'Roboto', sans-serif;
}
.tabulator-col-title {
  white-space: normal !important;
}

 **test.html file:----** code :-

**<div id="example-table" class="tabulator-font" ></div>**

**test.js file:-** code:- 

//function to build tabulator
self.buildTabulator();
// function to set data in to tabulator
self.setData();

////function to build tabulator
   self.buildTabulator = function () {
          var heightHere=$(window).height()*70/100;
        //create Tabulator on DOM element with id "flow-db-table"
      $("#example-table").tabulator({
    height:heightHere, // set height of table (in CSS or here), this enables the Virtual DOM and improves render speed dramatically (can be any valid css height value)
    layout:"fitColumns", //fit columns to width of table (optional)
    placeholder: "No data to display",
    tooltips:true,
    columns:[ //Define Table Columns
        {title:"Name", field:"name", width:150},
        {title:"Age", field:"age", align:"left", formatter:"progress"},
        {title:"Favourite Color", field:"col"},
        {title:"Date Of Birth", field:"dob", sorter:"date", align:"center"},
    ],
   
});
      };

    
    // function to set data in to tabulator

    self.setData = function () {
         
         var tabledata1 = [
    { name:"Oli Bob", age:"12", col:"red", dob:""},
    { name:"Mary May", age:"1", col:"blue", dob:"14/05/1982"},
    { name:"Christine Lobowski", age:"42", col:"green", dob:"22/05/1982"},
    { name:"Brendon Philips", age:"125", col:"orange", dob:"01/08/1980"},
    { name:"Margret Marmajuke", age:"16", col:"yellow", dob:"31/01/1999"},
    
];

  var tabledata2 = [
    { name:"abc", age:"12", col:"red", dob:""},
    { name:"Mary", age:"1", col:"blue", dob:"14/05/1982"},
    { name:"Christine Lobowski", age:"42", col:"green", dob:"22/05/1982"},
    { name:"Brendon Philips", age:"125", col:"orange", dob:"01/08/1980"},
    { name:"xyz", age:"16", col:"yellow", dob:"31/01/1999"},
    
];
for(var i=0; i<100;i++)
{
    tabledata1.push(...tabledata2);
}

//load sample data into the table
$("#example-table").tabulator("setData", tabledata1);
         
         
      };

Note:- when table height is more this issue is coming. table scrolling is also working fine ,but in bottom of tabulator container empty while spaces is coming.

**Comment by olifolkerd** [comment]
Hey @prk53 

There is a pesky bug with the virtual DOM rendering that seems to occasionally add a small amount of white space to the top or bottom of the table when it is scrolled quickly.

Im looking into it and hoping to get a fix out in the 4.0 release.

Thanks for letting me know.

Cheers

Oli :)
