### ISSUE TITLE
Scroll stops when pressing shift+drag

### ISSUE THREAD

**Issue by Rodbjartson** [olifolkerd/tabulator#1374]
I want to select multiple rows in my table by holding shift and clicking and dragging down. This works like a charm up until the point my table needs to scroll. Then the table won't scroll and the whole idea breaks.
Say I want to select 50 rows, but if my table height is so that the 15th row exceeds the height and I need to scroll, I would like that the table just keeps scrolling.

![ezgif com-optimize 1](https://user-images.githubusercontent.com/11444201/44710507-91157700-aaac-11e8-81d6-d63af8b9be57.gif)

**Comment by olifolkerd** [comment]
Hey @Rodbjartson 

That is how scroll works in all browsers im afraid. i have to work within the confines of the functionality of browsers.

Oli :)
