### ISSUE TITLE
Edit on double click

### ISSUE THREAD

**Issue by roman-dvorak** [olifolkerd/tabulator#1375]
Start edit mode on one click is bad for using with 'link' render. You can click to link and editor is opened at the same time.

**Comment by olifolkerd** [comment]
Hey @roman-dvorak 

Please be more specific in your requests, are you looking for an example of how to acheive an edit on double click?

**Comment by roman-dvorak** [comment]
Dear @olifolkerd,

I have trayed new version (4.0) and the problem is the same. And I have looked at the examples.

My code is:
The table defined with columns:
`
columns:[
	        {title:"#", field:"id", sorter:"number", width:25, editor:"input", editable:false},
	        {title:"počet", field: "count", sorter:"number", width: 80, editor:"input", editable:false, topCalc:"sum"},
	        {title:"Značka", field:"Ref", editor:"input", editable:false, cellDblClick:editf},
	        {title:"Položka", field:"Value", editor:"input", editable:false, cellDblClick:editf},
	        {title:"Poznámka", field:"note", editor:"textarea", editable:false, cellDblClick:function(e, cell){ cell.edit(true);} },
	    ],
`


And function for double click callback.
`
function editf(e, cell){
    console.log('dbl_click:', cell);
    cell.edit(true);
}
`
The function will start on double click but cell editor is not opened...

Please, can you help me how to solve this problem?

**Comment by olifolkerd** [comment]
Hey,

Thanks for posting the constructor, that was very helpful.

It looks like you have found a bug there! your code should be working.

I have just pushed a fix for this to the 4.0 branch and will include it in next weekends release.

Cheers

Oli :)
