### ISSUE TITLE
Bug in v 3.5.2 : columnResized event

### ISSUE THREAD

**Issue by HenrikBP** [olifolkerd/tabulator#1377]
Hi - there seems to be a bug in v 3.5.2.

In ResizeColumns.prototype._mouseDown (),  the line:
        $("body").off("mouseup", mouseMove);
should be
        $("body").off("mouseup", mouseUp);
Otherwise the mouse up event is never freed.

**Comment by olifolkerd** [comment]
Hey @HenrikBP 

Good catch, i have pushed a fix for this to the 4.0 branch and will include it in the next release.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @HenrikBP 

This should now be fixed on the 4.0 branch.

Thanks for letting me know.

Cheers

Oli :)
