### ISSUE TITLE
record counter

### ISSUE THREAD

**Issue by LastExile16** [olifolkerd/tabulator#138]
Hello Oli
First of all, thank you for your efforts on creating tabulator _making it very easy to use_ and thanks for your time trying to answer and solve the issues posted here.
How could I make tabulator show number of records on the bottom of the table like **showing 1 to 10 of 100 entries** (as datatables do), and indicate it if filtering is applied (instant column filtering).

**Comment by olifolkerd** [comment]
Hey,

Thanks for getting in touch, it is always great to hear people are enjoying using Tabulator.

To answer your question, you could place a div (or other element of your choice) at the bottom of your table and then use some of Tabulators callbacks to populate it with information.

So in this case we will put a div below the table:
```html
<div id="example-table"></div>
<div id="example-table-info"></div>
```

We can then use the ***dataFiltered*** callback to update our info element. This is triggered whenever the data filter is changed and also when data is first loaded into the table.

```js
$("#example-table-demo").tabulator({
	columns:[
	{title:"Name", field:"name", width:150},
	{title:"Age", field:"age"},
	{title:"Gender", field:"gender"},
	{title:"Height", field:"height"},
	],
	dataFiltered:function(data, field, type, value){
		//data - the subset of the total table data that has passed the filter and is now visible
		//field - the field being filtered
		//type - the type of filter being used
		//value - the value of the filter

		//set text in info element to show the number of rows and filters currently applied
		$("#example-table-info").text("rows:" + data.length + ", filter:" + field  + type  + value);
	}
});
```

A full list of all the available callbacks can be found in the documentation [here](http://olifolkerd.github.io/tabulator/docs/#callbacks)

Let me know if this works for you.

Cheers

Oli

**Comment by olifolkerd** [comment]
just edited the previous answer to show the total number of rows in the info data

**Comment by LastExile16** [comment]
Thanks for your prompt answer
Dear Oli my data comes from server so **get data** is always the same as **data length**
I want to show current data length and the total number of entries.
something like: 
rows 1 - 10 of 100 rows
and when column filter used:
rows 1 - 10 of 15 rows (filtered from 100 total rows)

by the way the above example of yours show this message in filter section:
rows:10 of 10, filter:function colFilter(data){
 var match = true;
 
 for(var field in filters){
 if(typeof data[field] == "string"){
 if(data[field].toLowerCase().indexOf(filters[field].toLowerCase()) == -1){
 match = false;
 }
 }else{
 //match everything else explicitly
 if(data[field] != filters[field]){
 match = false;
 }
 }
 }
 
 return match;
 }=undefined

**Comment by olifolkerd** [comment]
I have a two part answer for you

**Total Data Count:**
Are you u using ajax pagination on your table? if so i can recommend a different approach.

**Filter String**
That looks like you are using header filters. (by the way i put in a big enhancement of header filters this afternoon so recommend you download the latest version of tabulator).

If you are filtering using custom filter functions (as is the case for the header filters) then you cannot directly access the filtered fields as they dont technically exist, only the combined output of the filter function is considered.

In this case I would recommend that in the ***dataFiltered*** callback you check through each of the filter input elements and add an entry for each with a truthy value.

Let me know about the ajax pagination and i will get back to you.

Cheers

Oli

**Comment by LastExile16** [comment]
Yes I use ajax pagination 
for filtering, I don't want to show any information except I want to be able to show the total number of filtered result and the total number of non-filtered data

**Comment by olifolkerd** [comment]
Could you post a copy of your tabulator constructor so i make sure i auggest the right thing

**Comment by LastExile16** [comment]
$("#ajax-table2").tabulator({
		    fitColumns:true,
		    pagination:"remote",
		     movableRows: true,
		      movableCols: true,
		    tooltips:function(field, value, data){
		        return  field + " - " + value;
		    },
		    ajaxURL:"./ajax/data2.php", 
		    ajaxType:"POST",
		    columns:[
		        {title:"first name", field:"first_name", sorter:"string", editable:true, headerFilter:true},
		        {title:"last name", field:"last_name", sorter:"string", editable:true, headerFilter:true},
		        {title:"position", field:"position", sorter:"string", editable:true, headerFilter:true},
		        {title:"email", field:"email", sortable:false, editable:true, formatter:"email", editable:true, headerFilter:true},
		        {title:"office", field:"office", sorter:"string", editable:true, headerFilter:true},
		        {title:"start date", field:"start_date", sorter:"date", editable:true, headerFilter:true},
		        {title:"age", field:"age", sorter:"number", editor:"number", editable:true, headerFilter:true},
		        {title:"salary", field:"salary", sorter:"number", editor:"number", formatter:"money", editable:true, headerFilter:true},
		        {title:"seq", field:"seq", sorter:"number", editor:"number", editable:true, headerFilter:true},
		        {title:"extn", field:"extn", sorter:"number", editor:"number", editable:true, headerFilter:true},

		        //column definition in the columns array
				{formatter:printIcon2, width:40, align:"center", onClick:function(e, cell, val, row){alert("Printing row data for: " + row.first_name)}}
		    ],
		});
		// #search is a search button to look into all columns in the database to find match
		$("#search").click(function () {
			$("#ajax-table2").tabulator("setData","./ajax/data2.php", {filter:"1", filter_value:$("#stext").val(), fitler_type:"like"}, "POST");
		});

		// to reset data loading
		$("#reset").click(function () {
			$("#ajax-table2").tabulator("setData","./ajax/data2.php", {}, "POST");
			$("#stext").val('');
		});

**Comment by olifolkerd** [comment]
Thanks, i will have a play with that and post you a solution tommorow :)

**Comment by LastExile16** [comment]
Hello Dear Oli
have you tried it, please?

**Comment by LastExile16** [comment]
Hello Mr.Oli
I want to apply tabulator in my project but I'm still waiting for your answer...
could you update me please.

**Comment by olifolkerd** [comment]
Hey LastExile16,

Its great to hear you are so interested in Tabulator, and i'm always happy to help, but please understand that I am currently the sole contributor to this project which I do voluntarily around my day job, so while I try and respond as fast as possible, I can not always get back to questions as fast as I would like, but I guarantee I will always answer questions when they are asked as soon as I can.

That being said, here is my suggestion for your situation.

The issue you have is that at present the total number of rows possible is never known by Tabulator because it only receives the page count not the row count.

To solve this we will need to send some additional information in the response to the pagination request that we can then extract and use to fill the footer. In this case we will add a ***row_count*** property to the JSON object that the server returns

```js
{
    "last_page":15, //the total number of available pages
    "row_count":200, //the total number of rows available
    "data":[ // an array of row data objects
        {id:1, name:"bob", age:"23"}, //example row data object
    ]
}
```

We can then include the ***ajaxResponse*** callback in our tabulator constructor (which is triggered whenever data is received) to extract this new property and use it along with the pagination parameters sent to the server to set the contents of our footer element.

```js
$("#example-table").tabulator({
    ...
    columns:[...]
    ...
    ajaxResponse:function(url, params, response){
        //url - the URL of the request
        //params - the parameters passed with the request
        //response - the JSON object returned in the body of the response.
        
        //set max and min values
        var page_size =  Math.floor(response.row_count / response.last_page);
        $("#table-footer .start").text = (page_size * (params.page - 1)) + 1;

        var end_row = page_size * params.page;
        $("#table-footer .end").text = end_row > response.row_count ? response.row_count : end_row ;

        //set total record count in footer
        $("#table-footer .max").text = response.row_count;

        return response; //return the response data to tabulator (you MUST include this bit)
    },
});
```
To make life easier now that the data for the footer is coming from numerous sources I would recommend adding a number of spans to the footer element that you can then programatically set from where ever you source the data:
```html
<div id="table-footer">
    <span class="start"></span> - <span class="end"></span> of <span class="max"></span> rows
</div>
```

Let me know how you get on, if you need any more advice i would be happy to help.

Happy Tabulating :)

**Comment by LastExile16** [comment]
Thank you Oli
yes it's working, thank you again,
there is another issue I will post it now.

**Comment by olifolkerd** [comment]
Great news! Glad to hear it is working.

I have replied to your new post so hopefully we can get that sorted soon.

Cheers

Oli :)

**Comment by mhaddy** [comment]
> To solve this we will need to send some additional information in the response to the pagination request that we can then extract and use to fill the footer. In this case we will add a row_count property to the JSON object that the server returns

>{
    "last_page":15, //the total number of available pages
    "row_count":200, //the total number of rows available
    "data":[ // an array of row data objects
        {id:1, name:"bob", age:"23"}, //example row data object
    ]
}

Where would I put the above code, @olifolkerd?

**Comment by x11joe** [comment]
Do you have to create your own custom footer for this to work or is there a way to overide the default UI with the page numbers, next and prev buttons etc?
