### ISSUE TITLE
Use AJAX Progressive Loading in Oracle APEX

### ISSUE THREAD

**Issue by apexuser** [olifolkerd/tabulator#1380]
Hello,

I'm using Oracle APEX framework for web development and I would like to use Tabulator in my application. I'm new to Tabulator and tried only some simple examples. Here is a problem with AJAX Progressive Loading, which I would like to solve.
As I understand, I need (on the client side) to provide Tabulator with URL and some other request data and (on the server side) create some code, which will return table data. But for some reason it is not very convenient way in APEX. Simpler solution is to use Oracle APEX's JS API. There is a js function (`apex.server.process`) which can make all the job (it already knows all addresses, checksums, etc.) and return data. Is there a good way to make Tabulator use this function somehow for progressive loading?

**Comment by olifolkerd** [comment]
Hey @apexuser 

Thanks for getting in touch.

At the moment that would not be possible, but you are in luck. in the next couple of weeks version 4.0 of tabulator will be launching that allows you to replace its inbuilt ajax function with your own, allowing you to insert any custom functionality you want into the request architecture.

Cheers

Oli :)

**Comment by apexuser** [comment]
Hello @olifolkerd, 

Thank you for a great news!
