### ISSUE TITLE
Updating a select filter

### ISSUE THREAD

**Issue by flamingwitch** [olifolkerd/tabulator#1382]
Hi,

Is there a way to update a select list header filter with new values?  My table gets row updates occasionally that would potentially add new values, but I can't seem to figure out how to update the header filter list with those new values.

**Comment by Rodbjartson** [comment]
I do not think this is possible, perhaps a new feature suggestion?
@olifolkerd any comments?

**Comment by olifolkerd** [comment]
Hey @flamingwitch 

Sorry for the delay in getting back to you, i wanted to wait till the updates to 4.0 relating to this question had been implemented before getting back to you.

At the moment this is only possible with some fairly hacky DOM manipulation, which you will find in the many answers to this question already posted in these issue lists.

As of version 4.0 this become much easier thanks to the use of ***param lookup functions*** that allow you to pass a function that generates an object to param properties, and the new ***setHeaderFilterValue*** function on the column component that allows the header filter to be recreated.

in the example below we will be working on the "color" column.

To start with we build a param lookup function that will build a list of header filter values from the data loaded into the table:
```js
function paramBuilder(){

	var list = {"":""};

	var data = this.getData().map(a => a.color);

	data.forEach(function(item){
		if(typeof item !== "undefined"){
			list[item] = item;
		}
	});

	return list;
}
```
next we build our table and set the ***headerFilterParams*** option to our paramBuilder function, as well as using the ***dataLoaded*** callback to trigger a regeneration of the column header when new data is loaded into the table:

```js
var table = new Tabulator("#example-table", {
	columns:[
		{title:"Favourite Color", field:"color", headerFilter:"select", headerFilterParams:paramBuilder},
	],
	dataLoaded:function(){
		this.getColumn("color").reloadHeaderFilter();
	}
});
```

version 4.0 is currently in public beta, and should be released in a couple of weeks.

I hope that helps,

Cheers

Oli :)

**Comment by flamingwitch** [comment]
Thanks Oli.  I did go with finding the select input and updating it manually for now.  Looking forward to the new version.

**Comment by RandomGHUser** [comment]
This works quite well, thank you.

Before I write a custom filtering function, do you by chance have any code snippets for tiered filtering...for example:

There are 5 columns, you select a dropdown filter from one column, then the rest of the dropdown filters only show choices from whatever is already filtered, and so on.

I'd surmise that I would need to expand the paramBuilder function to iterate over the other header dropdown lists and check that the item will only get populated if it contains the other filters.

**Comment by bra-fsn** [comment]
@olifolkerd: could you please add this as a documentation/example (preferably with a more flexible syntax, allowing it to be usable for multiple columns for the poor souls who don't really know JS)?
Thanks. :)

**Comment by bra-fsn** [comment]
So the above example would look like this:
```javascript
function paramBuilder(column){
  var list = {"":""};
  var data = this.getData().map(a => a[column]);

  data.forEach(function(item){
	    if(typeof item !== "undefined"){
		       list[item] = item;
	    }
  });
  return list;
}

function partial(func /*, 0..n args */) {
  var args = Array.prototype.slice.call(arguments, 1);
  return function() {
    var allArguments = args.concat(Array.prototype.slice.call(arguments));
    return func.apply(this, allArguments);
  };
}
```
And in columns you could reference paramBuilder as:
```javascript
{title:"Location", field:"location", headerFilter:"select", headerFilterParams:partial(paramBuilder, 'location')},
```

**Comment by birbilis** [comment]
a combobox (there should be some implementations that also filter their own dropdown list as you type) would be nice to have too apart from a dropdown option for the header filter

**Comment by olifolkerd** [comment]
Hey @birbilis 

Tabulator already has built in select and autocomplete editors, both of which can be used as header filters.

For more information please read the [Header Filter Documentation](http://tabulator.info/docs/4.8/filter#header) and [Built In Editor List](http://tabulator.info/docs/4.8/edit#edit-builtin)

Cheers

Oli :)

**Comment by birbilis** [comment]
Thanks for the pointer, hadn't spotted the "Build in Editor List" page

**Comment by bmarotta** [comment]
Does this still work in version 5.0? I'm doing as following (_change dataLoaded to on("dataLoaded")_):
```javascript
var table = new Tabulator("#table", {
  columns: [{title:"id", field:"id"  , headerFilter: true}, 
                {title:"code", field:"code"  , headerFilter: true}, 
                {title:"title", field:"title"  , headerFilter: true}, 
                {title:"user_id", field:"user_id"  , headerFilter: "select", headerFilterParams: partial(paramBuilder, 'user_id')}, 
                {title:"type", field:"type"  , headerFilter: "select", headerFilterParams: partial(paramBuilder, 'type')}, 
                {title:"dots", field:"dots"  , headerFilter: true}, 
                {title:"filename", field:"filename" , formatter:"html" }, 
                {title:"is_public", field:"is_public"  , headerFilter: "select", headerFilterParams: partial(paramBuilder, 'is_public')}, 
                {title:"alphabet", field:"alphabet"  , headerFilter: "select", headerFilterParams: partial(paramBuilder, 'alphabet')}, 
                {title:"fontSize", field:"fontSize"  , headerFilter: "select", headerFilterParams: partial(paramBuilder, 'fontSize')}, 
                {title:"style", field:"style"  , headerFilter: "select", headerFilterParams: partial(paramBuilder, 'style')}, 
                {title:"hintFile", field:"hintFile"  , headerFilter: "select", headerFilterParams: partial(paramBuilder, 'hintFile')}]
  });
  table.on("dataLoaded", function() {
                this.getColumn("user_id").reloadHeaderFilter();
                this.getColumn("type").reloadHeaderFilter();
                this.getColumn("is_public").reloadHeaderFilter();
                this.getColumn("alphabet").reloadHeaderFilter();
                this.getColumn("fontSize").reloadHeaderFilter();
                this.getColumn("style").reloadHeaderFilter();
                this.getColumn("hintFile").reloadHeaderFilter()            
  });
```
But all the filters are empty...

**Comment by funglkf** [comment]
In version 5, `headerFilter: "select"` becoming `headerFilter: "list"` 
And it will work when i changed the dataLoaded event function like this

```js
var table = new Tabulator("#table", {
  columns: [{field: "colName",headerFilter: "list"}]
});

table.on("dataLoaded", (data) => {
  let list = { "": "" };
  let colData = data.map((a) => a["colName"]);
  colData.forEach(function (item) {
    if (typeof item !== "undefined") {
      list[item] = item;
    }
  });

  table.updateColumnDefinition("colName", {
    headerFilterParams: { values: list },
  });
});

```
