### ISSUE TITLE
Undo triggers rowAdded

### ISSUE THREAD

**Issue by tomvanlier** [olifolkerd/tabulator#1384]
I found in my project that undo triggers rowAdded when replacing a deleted row.

More specifically I work in a rowDeleted callback, where in some cases (data comes thorugh ajax) I need to undo the deletion, after which the rowAdded callback is called.

While this might be expected behaviour (after all a row is added), it bothered me because it triggered something I only wanted executed when a totally new row was added.

Moreover, it was very strange to me that in the rowAdded I could perfectly use the row.getCell function, whereas that was impossible right after the undo.

So I don't know if it's a bug, or even worth considering, I took a global boolean var which I change values to detect the addrow being an undo-action or not, but I thought I'ld share my findings :) and if it's not meant behaviour, there we go :)

**Comment by olifolkerd** [comment]
Hey @tomvanlier 

It does indeed call that callback, just as the rowDeleted callback is triggered when a rowAdd is undone.

I have had users put forward arguments both for and against that mode of operation, and have opted to go for calling the callbacks as a number of users had usage cases where this was useful.

But i will add it to the roadmap for consideration of an option to block this.

as for the ***getCell*** function, it will only work if the cells are available. if the row has not been visible yet it will not have any cell components as these are only added once the row is made visible for the first time.

It is part of the efficiency saving of the virtual DOM. if there is a specific reason you need the cell let me know and i can suggest another approach for you.

Cheers

Oli :)
