### ISSUE TITLE
Obtain the actual order of the table in an array.

### ISSUE THREAD

**Issue by VeinzX** [olifolkerd/tabulator#1388]
Hello again!

I'm loving the tabulator since i started working with it and i consider it one of the most complete plugins you can find out there.

Lets get to business.

I'm currently extracting the values of a certaing column in and storing it in an array, howerver, i wonder if its possible to do this with the exact sorting it has applied in the moment of the extraction.

Maybe i should sort it myself after the array has been created? Or is there anyway to get the array directly sorted from the tabulator?

**Comment by olifolkerd** [comment]
Hey @VeinzX 

Thanks for getting in touch

if you pass a Boolean of ***true*** into the first argument of the ***getData*** function it will return an array of the sorted/filtered rows
```js
var data = $("#example-table").tabulator("getData", true);
```

I hope that helps,

Cheers

Oli :)

**Comment by VeinzX** [comment]
Thanks oli! It worked pretty well.
