### ISSUE TITLE
How to set data-attributes & individual cell id's

### ISSUE THREAD

**Issue by point-nine** [olifolkerd/tabulator#1389]
I may be missing something, but I need to be able to set id's & data-attributes on individual columns and cells.  For example, in an html table, I set something like `<td id="cell_1234" data-userId="1234"></td>`  In using a table like this and applying tabulator, it either doesn't pick up that data, or I just don't seem to be able to get to it.  

I have only started working with this great package (v3.5), but have found the above to be impossible (so far).  Again, am I missing something?  I would appreciate any help ... Thanks!

**Comment by point-nine** [comment]
Looks like github dropped my example ... try that again:

`<td id="cell_1234 data-userId=1234"></td>`

**Comment by olifolkerd** [comment]
Hey @point-nine 

Thanks for getting in touch, i can certainly take you through how to do that.

But before i do, can i ask why you need to do it? if it is for applying a style then that makes sence if it is so you can access the cell from outside Tabulator then im afraid that work, because Tabulator uses a Virtual DOM, only the rows that are visible actually exist, the rows are created and destroyed as you scroll the table

If you can let me know what you are trying to achieve i can let you know the best way to approach it with Tabulator,

Cheers

Oli :)

**Comment by point-nine** [comment]
Thanks for the quick response!

I need to be able to set/retrieve the contents and data-attributes of td cells by row/column id.  If that isn't possible, I'll have to use html table then.  

Thank you for all your work on this package ... maybe I can use it further on down the road ;)

**Comment by olifolkerd** [comment]
Hey @point-nine 

Tabulator dosnt use td elements for its display

To use Tabulator (and all JS table libraries) you need to think about tables slightly differently from the way u would from a a physical table.

Tabulator builds the table in javascript from an array of row data objects, it creates Column Components and Row Components in Javascript that represent each column and row and allow you to carrie out loads of operations on the rows/columns as well as access their data.

There are loads of functions you can call on Tabulator to get sepecific columns or rows, there is the ***getColumns*** and ***getRows*** functions to return arrays of all the rows and columns, or you can call the ***getRow** or ***getColumn*** functions to get a specific row or column.

Do you just need to access the data or do you need to perform some operation on it?

Could you describe your usage case in a bit more detail, what is it you are trying to acheive, are you trying to highlight a cell, or take some action bassed on a user clicking on a cell, or trying to access the table data or update a cell?

Cheers

Oli

**Comment by olifolkerd** [comment]
for example, if you wanted to access the cell in the ***name*** column on the row with an id of ***24***, you would do something like this:
```js
var cell = $("#example-table").tabulator("getRow", 24).getCell("name");
```
This would then return the Cell Component for the cell, you could then get the cell value using the ***getValue*** function:
```js
var cellVal = cell.getValue();
```
or set the value with the ***setValue*** function:
```js
cell.setValue("Steve");
```


or if you just want to update data on a given row you can call the ***update*** function:
```js
$("#example-table").tabulator("getRow", 24).update({name:"steve");
```

I hope that points you in the right direction.

Cheers

Oli :)

**Comment by point-nine** [comment]
I think it will ... thanks again!
