### ISSUE TITLE
Setting up group headers

### ISSUE THREAD

**Issue by markomijat** [olifolkerd/tabulator#1390]
Hello Oli,

I'm trying to customize the look of a group header using the 'setGroupHeader' function.
I am also using Multi Level Grouping. My problem is : I don't have the access to row data when top level header (level 0) is created. So I can't really customize it's look using the table data.
Is there a way to access the row data in top level headers ?
Thanks !

**Comment by olifolkerd** [comment]
Hey @markomijat,

Thanks for getting in touch,

You should be using the ***groupHeader*** option to set the header for the groups, this is passed in the data for the group as the third argument to the callback

```js
groupHeader:function(value, count, data, group){
    //value - the value all members of this group share
    //count - the number of rows in this group
    //data - an array of all the row data objects in this group
    //group - the group component for the group

    return value + "<span style='color:#d00; margin-left:10px;'>(" + count + " item)</span>";
},
```
I hope that helps,

Cheers

Oli :)

**Comment by markomijat** [comment]
Hi Oli,

Thank you for your quick response. 
I can't seem to get what I want with the groupHeader option. I get 'undefined' in my header. My code is as follows : 
``` 
groupBy : ["no_affaire","no_code"],           
groupStartOpen: [true,false],

groupHeader : [
  function(data) {              
    return data.no_affaire + " - " + data.affaire_description ;
  }, 
  function(data) {
    return data.no_code;
  },],
```  
The only way I can get the wanted result is if instead of defining groupHeader, I define my groupBy parameter as follows : 
``` 
groupBy : [ 
function(data) {         
    return data.no_affaire + " - " + data.affaire_description;
 }, 
function(data) {
     return data.no_code;
},],
groupStartOpen: [true,false],
```

The problem I have then is that when I toggle multiple times the group (open/close/open...), clicking on header , my bottom calculations seem to multiply. (see my 2 attached photos) 
 
![pic1](https://user-images.githubusercontent.com/30549573/46573948-a2e81500-c99c-11e8-94b0-48ad66678f43.png)
![pic2](https://user-images.githubusercontent.com/30549573/46573949-a2e81500-c99c-11e8-9fb9-ecc7a36fecc7.png)


The only way I can go around that problem is if I redraw my table as follows : 
```
groupVisibilityChanged:function(group, visible){
    if (group.group.level==0){
      $("#rapport-table").tabulator("redraw");                        
    }
```
Any thoughts on why this happens ?

Thanks
Marko

**Comment by olifolkerd** [comment]
Hey Marko,

You are not accepting the correct number of arguments in the function you are putting in your ***groupHeader*** array, the data comes in the 3rd argument not the 1st which is why you are getting undefined, it should be:
```js
groupBy : ["no_affaire","no_code"],           
groupStartOpen: [true,false],

groupHeader : [
  function(value, count, data, group){            
    return data.no_affaire + " - " + data.affaire_description ;
  }, 
  function(value, count, data, group){
    return data.no_code;
  },],
```

I hope that helps,

Cheers

Oli :)

**Comment by markomijat** [comment]
Hi Oli,
Yes it was a silly mistake, but I 'am not getting anything in my header even with the correct number of arguments.
Maybe it is because I'm loading data in 
$.ajax({ ... 
success : ... 
 $("#rapport-table").tabulator('setData', data);
...
I'll keep on looking ...
Thanks again for your help
Marko

**Comment by olifolkerd** [comment]
Hey @markomijat 

Have you had a look at the data your are receiving in the data argument?

If you try just setting it to a static text string does it show up?

Cheers

Oli :)

**Comment by markomijat** [comment]
Hey Oli,

Tha 'data' argument I get in groupHeader is an empty array for some reason.
The data in the table is well set and grouped.
It is just in the header that I can't get access to it.

If I return a static string in my groupHeader function, it does show up. 

Cheers
Marko
