### ISSUE TITLE
Possible problem with initialSort and numbers

### ISSUE THREAD

**Issue by dedacpo** [olifolkerd/tabulator#1393]
Hello everyone!

I'm having a little trouble to make the initialSort work properly. Aperently it is not working with numbers, as you can see on first image. The value 100 is the greater value, so it should be on the bottom. The number 15.4 is not greater than 100.

![image1_tabulator](https://user-images.githubusercontent.com/39910218/45304697-05a9d600-b4ef-11e8-93ca-2a9963c7daf2.PNG)

But, when I remove the initialSort and sort the column manualy, it works properly, as you can see on the second image. 
![image2_tabulator](https://user-images.githubusercontent.com/39910218/45304714-0b072080-b4ef-11e8-8ed4-d907122268ef.PNG)

It also happens with non decimal numbers
![image3_tabulator](https://user-images.githubusercontent.com/39910218/45304729-14908880-b4ef-11e8-8180-7dac561cf485.PNG)

Am I using it correctly?

This is a link to js bin
https://jsbin.com/dakimogece/edit?html,js,output

**Comment by olifolkerd** [comment]
try setting the ***sorter*** on your value column to ***number***

I hope that helps,

Cheers

Oli :)

**Comment by dedacpo** [comment]
@olifolkerd you are right. It works now! Ok, I'm a little embarrassed since the solution is very simple... lol

thanks! =)
