### ISSUE TITLE
custom formatter not working with pagination

### ISSUE THREAD

**Issue by bioragul** [olifolkerd/tabulator#1394]
Hi,  I am using custom formatter to use HTML to display the cell data. The HTML code uses CSS and javascript to add and color text. I am using pagination:"local" and paginationSize:10. It works fine for the first page of the table but it is not working if I sort or move to the next page.
Any help is appreciated.
Thanks.

**Comment by olifolkerd** [comment]
Hey @bioragul 

Thanks for getting in touch,

It is quite hard to offer advice for your problem without knowing how your table is setup, could you post a copy of your table constructor object and we can then help you out.

Cheers

Oli :)

**Comment by bioragul** [comment]
Hi,
Below is my table constructor. 
'myinputseq' is the js variable. I am trying to align and color the strings from 'myinputseq' and cell.getValue() using the CSS and javascript. Any help is appreciated. Thanks.

<div id="mytable"></div>
<script>
alignmentFormatter = function(cell, formatterParams){
  var data = cell.getData();
  return "<p class=\"ali inp\"><span class=\"t1ali seqali\">" + myinputseq + "</span><BR><span class=\"t2ali seqali\">" + cell.getValue() +"</span><BR><span class=\"ast\"></span></p>";
  }

  $("#mytable").tabulator({
  pagination:"local",
  paginationSize:10,
  layout:"fitColumns",
  initialSort:[
  {column:"alignment_score", dir:"desc", sorter:"number"},
  ],
  columns:[
  {title:"Name", field:"name" },
  {title:"ID", field:"id" },
  {title:"Type", field:"type" },
  {title:"Length", field:"length"},
  {title:"Score", field:"alignment_score", sorter:"number" },
  {title:"Alignment", field:"match", align:"center", width:250, formatter:alignmentFormatter},
  ],
  });
  $("#mytable").tabulator( "setData", mydata );
</script>

**Comment by bioragul** [comment]
Hi,
Below is my table constructor.
'myinputseq' is the js variable. I am trying to align and color the strings from 'myinputseq' and cell.getValue() using the CSS and javascript. Any help is appreciated. Thanks.

alignmentFormatter = function(cell, formatterParams){
  var data = cell.getData();
  return "<p class=\"ali inp\"><span class=\"t1ali seqali\">" + myinputseq + "</span><BR><span class=\"t2ali seqali\">" + cell.getValue() +"</span><BR><span class=\"ast\"></span></p>";
  }

  $("#mytable").tabulator({
  pagination:"local",
  paginationSize:10,
  layout:"fitColumns",
  initialSort:[
  {column:"alignment_score", dir:"desc", sorter:"number"},
  ],
  columns:[
  {title:"Name", field:"name" },
  {title:"ID", field:"id" },
  {title:"Type", field:"type" },
  {title:"Length", field:"length" },
  {title:"Score", field:"alignment_score", align:"center", sorter:"number" },
  {title:"Alignment", field:"match", align:"center", width:250, formatter:alignmentFormatter},
  ],
  });
  $("#mytable").tabulator( "setData", mydata );
