### ISSUE TITLE
Ajax filtering

### ISSUE THREAD

**Issue by aklaver** [olifolkerd/tabulator#1395]
Tabulator v3.5.3
I am trying to figure out the Ajax filtering(sorting). In the docs I see:

ajaxFiltering:true,
The array of filter objects will take the same form as those returned from the getFilters function:
[
    {field:"age", type:">", value:52}, //filter by age greater than 52
    {field:"height", type:"<", value:142}, //and by height less than 142
]

Yet when I use a header filter on the column geography_desc I  see:

"GET /complex_table_data/list/?year=1999&page=1&size=12&filters%5B0%5D%5Bfield%5D=geography_desc&filters%5B0%5D%5Btype%5D=like&filters%5B0%5D%5Bvalue%5D=miss HTTP/1.1" 200 -

The filter elements are passed back as individual elements instead of an array.

I also wonder about the below from the pagination section:
Request URL

Tabulator will automatically create a page request URL when a user selects a page.

By default a url will be generated using the provided ajaxURL and a number of system generated parameters:

    page - the page number being requested
    size - the number of rows to a page (if paginationSize is set)
    sort - the first currently sorted field (if any)
    sort_dir - the first currently sort direction (if any)
    filter - the first currently filtered field (if any)
    filter_value - the first current filter value (if any)
    filter_type - the first current filter type (if any)

I do not see the sort and filter parameters in the URL, even with ajaxSorting and ajaxFiltering set and doing a sort or filter. This is with pagination: 'remote'.

**Comment by olifolkerd** [comment]
Hey @aklaver 

Thanks for getting in touch.

That is how you pass array data back as get parameters, your server-side framework should decode that into an array for you.

As for the second part of your question it sounds like your table might have some configuration issues, could you post a copy of your constructor object so i can see how it is currently setup and offer you some advice.

Cheers

Oli :)

**Comment by aklaver** [comment]
Using Flask this:

GET /complex_table_data/list/?year=1999&page=1&size=12&filters%5B0%5D%5Bfield%5D=geography_desc&filters%5B0%5D%5Btype%5D=like&filters%5B0%5D%5Bvalue%5D=miss

gets decoded as:

ImmutableMultiDict([('year', '1999'), ('page', '1'), ('size', '12'), ('filters[0][field]', 'geography_desc'), ('filters[0][type]', 'like'), ('filters[0][value]', 'miss')])

The filter array(from getFilters) is not kept together and I do not see how it could be as each part of the array is a separate GET parameter.

I was expecting something more along the lines of(from another project on Django):

"GET /tag_changes_table/update/?data=[{%22change_id%22:15886,%22change_confirmed%22:true}]&changeset_id=2574

<QueryDict: {'data': ['[{"change_id":15885,"change_confirmed":true}]'], 'changeset_id': ['2574']}>

**Comment by aklaver** [comment]
Table constructor below. What I get back with  AJAX filtering/sorting is shown in post above.
```
    $("#complex_table").tabulator({
        ajaxURL: "/complex_table_data/list/",
        ajaxParams: {"year": 1999},
        ajaxSorting: true,
        ajaxFiltering:true,
        // ajaxProgressiveLoad:true,
        pagination: "remote",
        paginationSize: 12,
        height: "400px",
        layout:"fitColumns",
        columns:[
                {title:"Id", field:"line_id", sorter:"number", width:100},
                {title:"Geography", field:"geography_desc", sorter:"string", headerFilter:true},
                {title:"Description", field:"commodity_desc", sorter:"string", editor:true},
                {title:"Type", field:"attribute_desc", width:200},
                {title:"Unit", field:"unit_desc", sorter:"string"},
                {title:"Year", field:"year_id", sorter:"string"},
                {title:"Period", field:"timeperiod_id", sorter:"number"},
                {title:"Amount", field:"amount", sorter:"number", editor:true},
                ],
            });
 
```

**Comment by olifolkerd** [comment]
Hey  @aklaver 

Yes they show up as separate parameters, but that is the industry standard format for sending arrays as get parameters, pretty much every framework out there knows to convert them back to arrays. I myself and a large number of Tabulator users have used it across a variety of frameworks with no issue and you will notice that is exactly how ajax library make those requests as well when not sending json data. (you are literally the first person to find this to be an issue)

You proposed option is to send back JSON formatted params, which of course you are entirely able to do if you want to handle the request generation yourself, but it is not the standard way to include them as a parameter

Ahh i now understand what you are asking in the second part of your question, it looks like you are looking at some outdated documentation there, a bout a year ago Tabulator used to only send the first filter and sorter in ajax requests using that format, then it moved to sending them in the ***sorters*** and ***filters*** params. if you let me know where in the documentation you found that i will be happy to correct it.

I hope that helps,

Cheers

Oli :)

**Comment by aklaver** [comment]
http://tabulator.info/docs/3.5#pagination
"Request URL

Tabulator will automaticly create a page request URL when a user selects a page.

By default a url will be generated using the provided ajaxURL and a number of system generated parameters:

    page - the page number being requested
    size - the number of rows to a page (if paginationSize is set)
    sort - the first currently sorted field (if any)
    sort_dir - the first currently sort direction (if any)
    filter - the first currently filtered field (if any)
    filter_value - the first current filter value (if any)
    filter_type - the first current filter type (if any)
"

**Comment by aklaver** [comment]
Maybe a documentation issue or my not understanding docs. From here:
http://tabulator.info/docs/3.5#set-data
I see:
"The array of filter objects will take the same form as those returned from the getFilters function:
[
    {field:"age", type:">", value:52}, //filter by age greater than 52
    {field:"height", type:"<", value:142}, //and by height less than 142
]"

Which I also see when I do:
$("#complex_table").tabulator("getFilters", true);
(2) […]
​0: Object { field: "geography_desc", type: "like", value: "miss" }
​1: Object { field: "year_id", type: "like", value: "1998" }
​length: 2
​
__proto__: Array []

What I see on the receiving end(converted to JSON):

{"filters[0][field]": "geography_desc", "filters[0][type]": "like", "filters[0][value]": "miss", "filters[1][field]": "year_id", "filters[1][type]": "like", "filters[1][value]": "1998", "page": "1", "size": "12", "year": "1999"}

I expected something like:
[[{ field: "geography_desc", type: "like", value: "miss" }, { field: "year_id", type: "like", value: "1998" }], "page": "1", "size": "12", "year": "1999"}]

Is this what you see(or something similar)?
If so what framework(s) are you referring to?

**Comment by olifolkerd** [comment]
Hey @aklaver 

You are receiving the correct data you are just not interpreting it correctly, if you look at ajax libraries like jQuery or axios when not sending data in JSON mode they will behave a exactly like this. it is a standard transfer protocol for this sort of transaction.

As i have already explained you are expecting JSON data to be sent back which is not standard, though you can encode it however you like if you want it in that way.

Im sorry that this continues to frustrate you but i suggest you read the documentation for whichever server side framework/language you are using to understand how to correctly decode it, im afraid i can offer you no further advice on the matter.

I have updated the documentation to remove the outdated sort_dir, filter_value and filter_type  params from the list of pagination parameters.

Thanks

Oli :)

**Comment by olifolkerd** [comment]
Hey @aklaver 

I am sorry to hear that this was unclear for you. For developers used to dealing with get parameter arrays it will make sense,

Im happy to hear you now understand how it works.

Cheers

Oli :)

**Comment by aklaver** [comment]
Got around to reading the link posted earlier. So name[ ][ ]= is a PHPism that maybe recognized or not, but is not a standard. In the Ruby world Rails recognizes it, the Python frameworks I use do not. They follow the other convention, field1=value1&field1=value2&field2=value3.  Now that I know what the problem is I can start exploring ways to deal with it.  Also I do not see jQuery using this:
```
var data1 = [{field:"age", type:">", value:52}, {field:"height", type:"<", value:142}];
$.ajax({  
    type: 'GET',
    url: '127.0.0.1:5000/complex_table/',
    data: data,
   });
```
GET
http://127.0.0.1:5000/complex_table/127.0.0.1:5000/complex_table/?undefined=52&undefined=142

In fact:
http://api.jquery.com/jquery.param/
"

Note: Because some frameworks have limited ability to parse serialized arrays, developers should exercise caution when passing an obj argument that contains objects or arrays nested within another array.

Note: Because there is no universally agreed-upon specification for param strings, it is not possible to encode complex data structures using this method in a manner that works ideally across all languages supporting such input. Use JSON format as an alternative for encoding complex data instead.
"
I am only harping on this because I really like the Tabulator library and would like to see it grow into new areas.

**Comment by olifolkerd** [comment]
Hey @aklaver 

Thanks for the additional feedback there.

When version 4.0 launches later today you will be able to use the new ***ajaxURLGenerator*** function to structure the request in any way you like:

```js
var table = new Tabulator("#example-table", {
    ajaxURLGenerator:function(url, config, params){
        //url - the url from the ajaxURL property or setData function
        //config - the request config onject from the ajaxConfig property
        //params - the params object from the ajaxParams property, this will also include any pagination, filter and sorting properties based on table setup

        //return request url
        return url + "?params=" + encodeURI(JSON.stringify(params)); //encode paramters as a json object
    },
});
```

Cheers

Oli :)

**Comment by aklaver** [comment]
That is great. Will check it out. I really appreciate the time and effort you put into this.
