### ISSUE TITLE
Progressive load true

### ISSUE THREAD

**Issue by aklaver** [olifolkerd/tabulator#1396]
Tabulator v3.5.3
When doing:
ajaxProgressiveLoad:true,

I get:
Pagination Error - no such pagination mode: progressive_true

ajaxProgressiveLoad:"scroll" and ajaxProgressiveLoad:"load" work fine.

**Comment by olifolkerd** [comment]
Hey @aklaver 

Thanks for getting in touch, without seeing your full constructor object it will not be possible to point out any configuration issues you may have. If you could post a copy of your full constructor object that would help.

Cheers

Oli :)

**Comment by aklaver** [comment]
The constructor is:

```
$("#complex_table").tabulator({
        ajaxURL: "/complex_table_data/list/",
        ajaxParams: {"year": 1999},
        ajaxProgressiveLoad:true,
        height: "400px",
        layout:"fitColumns",
        columns:[
                {title:"Id", field:"line_id", sorter:"number", width:100},
                {title:"Geography", field:"geography_desc", sorter:"string", headerFilter:true},
                {title:"Description", field:"commodity_desc", sorter:"string", editor:true},
                {title:"Type", field:"attribute_desc", width:200},
                {title:"Unit", field:"unit_desc", sorter:"string"},
                {title:"Year", field:"year_id", sorter:"string"},
                {title:"Period", field:"timeperiod_id", sorter:"number"},
                {title:"Amount", field:"amount", sorter:"number", editor:true},
                ],
            });

```

**Comment by olifolkerd** [comment]
Hey @aklaver 

The issue is you cannot pass the value of ***true*** to the ***ajaxProgressiveLoad:true*** option. it must be either ***load*** or ***scroll*** depending on how you want it to behave.

I hope that helps,

Cheers

Oli :)

**Comment by aklaver** [comment]
The docs  are unclear on this:
http://tabulator.info/docs/3.5#ajax-progressive
"...
$("#example-table").tabulator({
    ajaxURL:"http://www.getmydata.com/now", //ajax URL
    ajaxProgressiveLoad:true, enable progressive loading
    ajaxProgressiveLoadDelay:200 //wait 200 milliseconds between each request
});
...
"
