### ISSUE TITLE
movableColumns disable contextual click?

### ISSUE THREAD

**Issue by EddieAguirre** [olifolkerd/tabulator#1397]
When I enable movableColumns the columns become draggable by clicking and dragging as expected. But when right clicking the column follows the mouse (after click, not dragging). This conflicts with my custom header contextual menu handler. Is there a way to only allow movableColumns on click and drag, turn off contextual click.

**Comment by olifolkerd** [comment]
Hey @EddieAguirre 

Thanks for getting in touch, that looks like a bug you have found there.

I will make sure that it is fixed for the v4.0 release next week.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @EddieAguirre 

I have just pushed a fix for this to the 4.0 branch and will include it in next weekends release.

Thanks for your feedback.

Cheers

Oli :)

**Comment by EddieAguirre** [comment]
Thanks for the fix, I appreciate it.
