### ISSUE TITLE
Header hide

### ISSUE THREAD

**Issue by vmontal** [olifolkerd/tabulator#140]
Two identical (I swear) structure table in two identical `<div>;` the first one is ok; the second one I see the header only after I click in the footer navigation button ( pagination: "local", paginationSize: 10,)
Please, someone help me! I'm going crazy

**Comment by olifolkerd** [comment]
Is the second table (the one with issues) visible when the constructor is called? if not then tabulator cannot calculate the header dimensions properly as hidden elements have no accessible dimensions until they are first show.

If this is the case then Fear Not! this happens all the time, all you need to do is trigger the ***redraw*** function when you show the second function and it will fix the issue for you:
```js
$("#example-table").tabulator("redraw");
```

Let me know how you get on, if this doesn't fix your issue then can you post a copy of both of your Tabulator constructors and i will see what i can suggest.

Cheers

Oli

**Comment by vmontal** [comment]
I tried, but ...Nothing!!!
Now It's too late for me!

See you tomorrow (or better later!)

**Comment by olifolkerd** [comment]
sad times, if you have an example html file you can post on here i would be happy to take a look at it for you :)

**Comment by vmontal** [comment]
So, where we stopped?

1. The table with the iusse is not visible when the constructor is called ( and this is something normal in my code);

2. I tried to call the redraw function  according your advice, but the behaviour is the same (header not show until I click on Prev / Next Buttons);

I attach HTLM and JS files (it's a mess, I know, but please don't throwing the stones!!!)

[schedaBanca.html.txt](https://github.com/olifolkerd/tabulator/files/668318/schedaBanca.html.txt)
[schedaMutuo.js.txt](https://github.com/olifolkerd/tabulator/files/668319/schedaMutuo.js.txt)

Thanks, in advance for your help

**Comment by olifolkerd** [comment]
Hey,

Sorry for the delay in getting back to you, its been a busy xmas.

Im afriad the files you have sent over arnt much help as they are missing any css and the includes to the tabulator library so i cant get anything to work as you would have coded it.

Is there an example of this running online that i could have a look at?

Cheers

Oli

**Comment by vmontal** [comment]
Hi,

are u asking me a demo access (no problem) to the app;

Attached the css files used:
[gestioneUtenti.css.txt](https://github.com/olifolkerd/tabulator/files/692849/gestioneUtenti.css.txt)
[tabulator.css.txt](https://github.com/olifolkerd/tabulator/files/692850/tabulator.css.txt)

**Comment by olifolkerd** [comment]
Hey,

if i could get access that would be great, if you want to keep it private you can email the access details to oliver.folkerd@gmail.com

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey,

Thanks for the login,

Looking at your other tables, you are not setting any data in them, so they have nothing to display.

The background appears transparent because you have set the background colour on the ***.tabulator-tableHolder*** or ***.tabulator-table*** elements which are invisible when the table has no data. if you set it on the ***.tabulator*** element instead, you wont have that issue.

I would put some ***console.log()*** functions in the statements when you call the ***setData*** functions on the tables to check if they are being called and to dump the data to the console log to make sure it is correct.

Let me know if you need any further help.

Cheers

Oli

**Comment by olifolkerd** [comment]
Did this help solve your problem at all?

**Comment by vmontal** [comment]
I don't know! I have to try!
Always thank
V.

Get Outlook for iOS




On Sat, Jan 21, 2017 at 7:13 PM +0100, "Oli Folkerd" <notifications@github.com> wrote:












Did this help solve your problem at all?

**Comment by vmontal** [comment]
Hey Oli,
I'm driving up the wall...

I tried everything, but nothing....

I cannot understand why ONLY these three tables (in all my projects over the world) show the header only after a refresh (change page i.e.); and more if I don't set pagination: "local", I'll never see the header....

Help me, please!

**Comment by olifolkerd** [comment]
my only thought is that table is still hidden when you are calling the ***redraw*** function.

Have you tried putting a timeout function around the redraw you call when you show the dialog to give it a bit more time to become visible.

```js
setTimeout(function(){
    $("#example-table").tabulator("redraw", true):
}, 1000);
```

In the example i have set the timeout at 1 second which is far too long and will result in not refreshing immediately, but if it works after a second it will tell you that that is your problem, and you can reduce the time to make it render faster. Usually100-300 ms works.

Let me know if that helps

Cheers

Oli

**Comment by vmontal** [comment]
IT'S WORKING!!! IT'S WORKING!!! IT'S WORKING!!!

.... and now I realized that I didn't develop a WebApp ... I created a Monster (my worst nightmare)

Thank for the time you spent with me!!!

**Comment by olifolkerd** [comment]
Great news!!!

Happy to hear its all working.

Give me a shout if you need any other help.

Cheers

Oli
