### ISSUE TITLE
Fixed header

### ISSUE THREAD

**Issue by Ibra1994** [olifolkerd/tabulator#1402]
How to freeze header?

**Comment by olifolkerd** [comment]
The header is frozen at the top of the table by default, the only occasion it isnt is if you have disabled the Virtual DOM.

In order to use the virtual DOM the table must have a height set on it.

Full information on this can be found in the [Quick Start Guide](http://tabulator.info/quickstart/3.5#rendering)

I hope that helps,

Cheers

Oli :)

**Comment by Rapster** [comment]
Would it be possible to have a fixed header and column headers without table scroll but with page scroll? As an example: https://datatables.net/extensions/fixedheader/examples/options/columnFiltering.html

**Comment by olifolkerd** [comment]
@Rapster if you set the ***virtualDOM*** option to false in the table setup it will not scroll

**Comment by formtapez** [comment]
@Rapster 
Edit your .css file and remove "overflow: hidden;" from ".tabulator".

Additionaly add:
`position: sticky;
top: 0px;`
to ".tabulator .tabulator-header".

**Comment by rossofiorentino** [comment]
> Edit your .css file and remove "overflow: hidden;" from ".tabulator".
> Additionaly add:
> position: sticky; top: 0px;
> to ".tabulator .tabulator-header".

@Rapster @formtapez @formtapez 
I'm not clever with css, but this worked form me, just also add z-index.

.tabulator .tabulator-header {
  position: sticky; 
  top: 146px;  /*my position*/
  z-index: 100;
}

**Comment by re-hopo** [comment]
.tabulator .tabulator-header {
    position: sticky;
    top: 0;
    z-index:9
}

**Comment by re-hopo** [comment]
```
.tabulator .tabulator-header {
    position: sticky;
    top: 0;
    z-index:9
}
.tabulator{
    overflow: unset;
}
```

**Comment by Diemon-zp** [comment]
> ```
> .tabulator .tabulator-header {
>     position: sticky;
>     top: 0;
>     z-index:9
> }
> .tabulator{
>     overflow: unset;
> }
> ```

Thanks, works in Tabulator v6.3.0
