### ISSUE TITLE
Pagination on refresh

### ISSUE THREAD

**Issue by mikehobson** [olifolkerd/tabulator#1403]
Hi Oli

Great product its really made my life easier, I'm now stuck with one small issue, I have a lot of football data and I refresh the page every 60 seconds by using Setdata, this works perfectly unless im not on page 1 of my data, if Im on page 2 or higher and the refresh starts I go back to page 1

Is there a way round this or do I need to get the current page before setdata and then set the page after ?

Thanks

Mike

**Comment by olifolkerd** [comment]
Hey @mikehobson,

Thanks for your kind words!

The ***setData*** function will completely reset the table and load new data. have a look at using the ***replaceData*** function, it should keep eveything where it was when the data was replaced.

I hope that helps,

Cheers

Oli :)

**Comment by mikehobson** [comment]
Oli that worked perfectly, thank you Again
