### ISSUE TITLE
Mouse wheel scrooll problem

### ISSUE THREAD

**Issue by boumboum** [olifolkerd/tabulator#1404]
I'm testing V4.0 right now.
I have some issues with mouse wheel scrolling.
Actually it does not work... After some time and some clicks on other applications, tabs, the scrolling becomes fluid.
Hm. Weird.

**Comment by olifolkerd** [comment]
Hey @boumboum 

Thanks for getting in touch, could you confirm what browser you are using and post an example table constructor that replicates your issue.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @boumboum 

I cant seem to replicate your issue on the latest code from 4.0

There will be further improvements coming in 4.0 to make it even smoother.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
you can keep track of changes to the rendering system in issue #1437
