### ISSUE TITLE
V4 builtin formatting for date

### ISSUE THREAD

**Issue by boumboum** [olifolkerd/tabulator#1405]
Is there any possibility to have builtin formatting for date, time and datetime values without creating a custom formatting function?

**Comment by olifolkerd** [comment]
Hey @boumboum 

Great idea, i will stick it in this weekend.

Thanks for the feedback

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @boumboum 

I have just pushed the new ***datetime*** formatter to the 4.0 branch.

it can be used as follows:
```js
{title:"Date of Birth", field:"dob", formatter:"datetime", formatterParams:{inputFormat:"DD/MM/YYYY hh:mm:ss", outputFormat:"YYYY-MM-DD hh:mm:ss", invalidPlaceholder:"Invalid Date"}}
```

Thanks for the suggestion.

Cheers

Oli :)

**Comment by boumboum** [comment]
You're great, man!
I'll have a look on that.
