### ISSUE TITLE
custom editor for headerFilter returning false results in table not filtering

### ISSUE THREAD

**Issue by 3iMichael** [olifolkerd/tabulator#1406]
When using a custom header Filter, calling the "success" function with the value as boolean false will result in no filtering happening.

This is likely caused by this bit of code in the filter extension:

`	function success(value){`
`        (...)`
`		if(value){`

Which probably is supposed to check that there actually is a value passed - but as written, results in header filters trying to filter for boolean values not working as intended.

I've built a workaround by having the select in the header filter return the strings "true" and "false" and using a custom filter function, but unless this has implications elsewhere that I'm not aware of it would likely be better to change the check in filter.js to `if (value !== undefined)` or something like that.

**Comment by olifolkerd** [comment]
Hey @3iMichael 

Thanks for getting in touch,

You are right that is indeed the issue however it gets more complicated as it depends on the header fliter as to what an empty field should look like as it would be "" for an input not undefined.

I will have a look at this over the weekend and see if i can offer a better solution for it for v4.0

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @3iMichael 

I have just pushed some updates to the 4.0 branch to address this issue.

From now on the built in tick header filters will consider ***true*** and ***false*** to be valid values to filter on.

There is also now a new ***headerFilterEmptyCheck*** column definition property that lets you tell Tabulator when it should consider a header filter empty

```js
{title:"Allowed", field:"allowed", headerFilter:"tick", headerFilterEmptyCheck:function(value){
    return !value; //only filter when the value is true
}},
```

Version 4.0 will be launched later today

Thanks for your feedback,

Cheers

OIi :)
