### ISSUE TITLE
V4 number cell editor: editor params not working

### ISSUE THREAD

**Issue by michaelongithub** [olifolkerd/tabulator#1408]
Hi Oli 
I can 
editor: "number", editorParams: { "min": 1, "max":1000 }
or
editor: "number", editorParams: { min: 1, max:1000 }
(what would be the correct way ?
Both:
Number editor showing, correct increment BUT:
can enter any values like 0, -1, 50000

Cheers, Michael

**Comment by olifolkerd** [comment]
Hey @michaelongithub 

The number editor uses a standard number type input element and that is the behavior of that element im afraid.

you could either use a custom editor that uses some JS to prevent it going out of range or use a validator to prevent an invalid value being accepted.

I hope that helps,

Cheers

Oli :)
