### ISSUE TITLE
V4 custom cell editor: not updating value

### ISSUE THREAD

**Issue by michaelongithub** [olifolkerd/tabulator#1409]
Hi Oli

const quantityEditor = function (cell, onRendered, success, cancel) {
    var editor = document.createElement("input");

    editor.setAttribute("type", "number");
    editor.setAttribute("min", "1");
    editor.setAttribute("max", "100");

    //create and style input
    editor.style.padding = "3px";
    editor.style.width = "100%";
    editor.style.height = "20px";

    editor.value = cell.getValue();

    onRendered(function () {
        editor.focus();
        editor.style.css = "100%";
    });

    //when the value has been set, trigger the cell to update
    function successFunc() {
        success(editor.val()); //dont need any formatting
    }

    editor.addEventListener("change", successFunc);
    editor.addEventListener("blur", successFunc);

    //return the editor element
    return editor;
}

Editor is displayed. But after tabbing out of cell not updated. Probably I am not understanding how to implement the successFunc.
And error: Uncaught TypeError: editor.val is not a function at HTMLInputElement.successFunc  .

**Design:**
![image](https://user-images.githubusercontent.com/5064432/45618026-9c890c00-ba74-11e8-9b56-4580390e9307.png)

In addition to the editor there appears a surrunding frame with height of cell. Not desirable.
Can be removed with some attributes ?
Or by design? If yes: would prefer to see just editor.

Cheers Michael

**Comment by olifolkerd** [comment]
Hey @michaelongithub 

You have a typo in your ***successFunc*** it should be `editor.value` not `editor.val()`

I hope that helps,

Cheers

Oli :)

**Comment by michaelongithub** [comment]
Thanks and in the 4.0 http://tabulator.info/docs/4.0/edit example it is still edtior.val(). 
But now works as You suggest.
Cheers, Michael

**Comment by olifolkerd** [comment]
Hey @michaelongithub 

Thanks for letting me know about that, i have fixed the docs.

Cheers

Oli :)
