### ISSUE TITLE
Change ajaxParams later

### ISSUE THREAD

**Issue by Gonzalo788** [olifolkerd/tabulator#141]
Is it legal to change the ajaxParams at any time with $("#my-table").tabulator({ajaxParams : {testParameter: "testValue"}}); without affecting values from the initial setup?

**Comment by olifolkerd** [comment]
is this for remote pagination or a standard remote data load?

**Comment by Gonzalo788** [comment]
This is for remote pagination. What I actually want is to set a filter value for the backend.

**Comment by olifolkerd** [comment]
In that case can I suggest that you use a custom pagination to build your pagination request.

This passes through the url and params from the setup option and then allow you to build you own URL where you can add your own filter property:

```js
$("#example-table").tabulator({
    pagination:"remote", //enable remote pagination
    ajaxURL:"http://testdata.com/data", //set url for ajax request
    paginator: function(url, pageNo, pageSize, ajaxParams ){
        //url - the url from the ajaxURL paramter
        //pageNo - the requested page number
        //pageSize - the value of the paginationSize paramter
        //ajaxParams - the value of the ajaxParams parameter

        return ""; //must return the string of the page request URL
    },
});
```

Full details of this can be found [here](http://olifolkerd.github.io/tabulator/docs/#pagination-remote)

**Comment by Gonzalo788** [comment]
At the moment my solution is to call tabulator("setData", "/get", {filter_value: getValue()} on every change event of an input control with a debounce timer. Maybe your solution is a lot better because it looks nicer.

**Comment by Gonzalo788** [comment]
I rewrote my code with a custom paginator as in your post. This works fine as expected. Thanks for you time. This is a great javascript table library.

**Comment by olifolkerd** [comment]
Great News!!!

Thanks, its always great to hear people are enjoying using Tabulator. give me a shout if you have any other questions.

Cheers

Oli

**Comment by parth55** [comment]
Hi,

I don't want to change the ajax parameter However, I want that it will pass the latest value at each request,

```
var _this = this;
  this.tabulator = new Tabulator("#example", {
	ajaxParams:{last_page:_this.iTotalPage, paginationSize: this.iRowsPerPage},
	ajaxURL: "/tableData",
  //   ajaxURLGenerator:function(url, config, params){
  //     //url - the url from the ajaxURL property or setData function
  //     //config - the request config object from the ajaxConfig property
  //     //params - the params object from the ajaxParams property, this will also include any pagination, filter and sorting properties based on table setup
  //     params = {last_page:_this.iTotalPage, paginationSize: _this.iRowsPerPage}
  //     //return request url
  //     return url + "?last_page ="+ _this.iTotalPage +"&paginationSize =" +this.iRowsPerPage;
  // },
	autoColumns:true,
	height:"500px",
	movableColumns: true,
	ajaxProgressiveLoad:"scroll",
	paginationSize: this.iRowsPerPage,
	ajaxProgressiveLoadScrollMargin: 400,
	ajaxLoader: true,
	ajaxLoaderLoading: 'updating data',
	ajaxProgressiveLoadDelay: 200,
	dataFiltering:function(filters){
  
	},
	ajaxResponse:function(url, params, response){
	  if(!_this.aColumns.length){
		_this.aColumns =  Object.keys(response.data[0]);            
	  }
	  _this.iTotalPage = response.last_page;          
	  return response;
	}
  });
```

I am trying to send the latest value with {last_page:_this.iTotalPage, paginationSize: this.iRowsPerPage} but I can't do so, also I have tried ajaxURLGenerator to do the same, but with that, I am not able to manage filter and sorter parameters passed automatically with the request.

can you please guide me on same?
