### ISSUE TITLE
row_manager.js typo: offsetWidt (without h)

### ISSUE THREAD

**Issue by 3iMichael** [olifolkerd/tabulator#1410]
in rowmanager.js, there's a typo that probably makes part of it not work right: 

`if(this.element[0].scrollWidth > this.element[0].offsetWidt){`

The property is offsetWidth, so this comparison probaly is defunct ;)

Note: in the 4.0 branch, the code compares `this.element.offsetWidt` in case you want to do a search-and-replace

**Comment by olifolkerd** [comment]
Hey @3iMichael 

Thanks for the headsup, i have just pushed a fix for this to the 4.0 branch.

Cheers

Oli :)
