### ISSUE TITLE
How to add serial no column automatically when the data is getting populated/filtered.

### ISSUE THREAD

**Issue by prk53** [olifolkerd/tabulator#1412]
I want to auto generate  an serial number/ID , when the tabulator is getting populated with data or whenever tabulator data is  getting filtered so that i can finally keep track total rows.
for example below is the screenshot
![tabulator_autogenerated_serialnumber](https://user-images.githubusercontent.com/41157621/45685231-5a3ff780-bb66-11e8-9d7a-852157b54faf.png).

**Comment by ryhill** [comment]
columns:[
    {formatter:"rownum", align:"center", width:40},
....
]

**Comment by prk53** [comment]
Hi Ryhill, thanks for the reply.
Above code is working fine, but when i am applying filter on that table i want the results in new serial number. like 1,2,3,4,5..  and so on. but currently i am getting the previous row serial number of item. I am attaching the screenshot.
![filter_data_tabulator](https://user-images.githubusercontent.com/41157621/45708417-0b628400-bb9f-11e8-9b51-95e11307e4b1.png)
 I want the result after filtering  is something like  for first row- 1, for second row :-2  for third row :-3  .. and so on. can we achieve something like this..

**Comment by olifolkerd** [comment]
Hey @prk53 

this is happening because the formatter is only run when the row is first generated, updating the filter dosnt update the data of the row so the formatter isnt updated.

you can get round this by calling the ***redraw*** function on the table in the ***dataFiltered*** callback to force the rows to update:

```js
$(#example-table").tabulator({
	dataFiltered:function(filters, rows){
	        $(#example-table").tabulator("redraw", true);
	},
});

I hope that helps,

Cheers

Oli :)
