### ISSUE TITLE
Focus on edit on the first column of a new row

### ISSUE THREAD

**Issue by mindcreations** [olifolkerd/tabulator#1413]
Hello,
I'm experimenting with Tabulator 5.5 and it is my first try.

I've to accomplish a simple task.

After adding a row with 

`$("#table").tabulator("addRow", {});`

I would like to automatically edit the first column (cell) of the new row.

I've tried using the event *rowAdded*

`rowAdded:function(row){ }`

and then call `cell.edit()`

but I can't get the row edited... it seems to me that the event happens before the row is actually added and not after thus it cannot be edited.

Can you direct me on the right way to do this?

Thank you for any help.

**Comment by aklaver** [comment]
I am interested in this also. Similar to  #1399.

**Comment by tomvanlier** [comment]
Try something like this 
`rowAdded: function (row) {


           do{
               
             setTimeout(function(){row.getCell("gebruikersnaam").edit();},100);
  
                  
           }
           
           while(row.getData().gebruikersnaam === "undefined");

        }
        },`

where gebruikersnaam is the fieldname of the first column.
I had to put the timeout in, because this callback sometimes triggers before the column is initialised.

**Comment by olifolkerd** [comment]
Hey All,

For the moment a setTimeout with a 200ms delay should do it, but it is a bit limited.

version 4.0 is moving over to returning promises from all functions that update the DOM which will then let you know when the row is ready.

Check out the update when it goes in this weekend.

Cheers

Oli :)

**Comment by mindcreations** [comment]
> Try something like this
> 
> ```
>      rowAdded: function (row) {
> 
>        do{
>            
>          setTimeout(function(){row.getCell("gebruikersnaam").edit();},100);
> 
>               
>        }
>        
>        while(row.getData().gebruikersnaam === "undefined");
> 
>     }
>     },
> ```
> where gebruikersnaam is the fieldname of the first column.
> I had to put the timeout in, because this callback sometimes triggers before the column is initialised.
> The 100 ms is quite arbitrary btw ...

Yes! It did the trick.
Thank you very much!

But as @olifolkerd said, with promises it would be cleaner.
