### ISSUE TITLE
Can we apply multiple filter (pass multiple column values  ) on Tabulator.

### ISSUE THREAD

**Issue by prk53** [olifolkerd/tabulator#1414]
I want to pass multiple value to filter the tabulator and display the results.:

for example:-
below the given table:-
![tabulator_autogenerated_serialnumber](https://user-images.githubusercontent.com/41157621/45709253-38179b00-bba1-11e8-8140-7ac7ceea035d.png)

i want to apply multiple filter like :--  gender1=male,gender2=female, rating=1 or 3,then it should return 4 rows as a results:- i.e row no :-  4,5,7,8. How to do that.

**Comment by olifolkerd** [comment]
Hey @prk53 

You can either use a custom filter function to achieve this, with any custom logic you like:

```js
function customFilter(data, filterParams){
    //data - the data for the row being filtered
    //filterParams - params object passed to the filter

    return data.name == "bob" && data.height < filterParams.height; //must return a boolean, true if it passes the filter.
}

$("#example-table").tabulator("setFilter", customFilter, {height:3});
```

or you can use complex filter arrays, The example below applies a filter that will let through rows with a age of greater than 52 AND (either a height of less than 142 OR with the name steve)

```js
$("#example-table").tabulator("setFilter", [
    {field:"age", type:">", value:52}, //filter by age greater than 52
    [
        {field:"height", type:"<", value:142}, //with a height of less than 142
        {field:"name", type:"=", value:"steve"}, //or a name of steve
    ]
]);
```

Full details of all of this can be found in the [Filtering Documentation](http://tabulator.info/docs/3.5#filtering)

I hope that helps,

Cheers

Oli :)

**Comment by jasperandrew** [comment]
@olifolkerd Could you give an example of how you would set a filter using the expression `a OR (b AND c)`? It doesn't seem possible, since you can't nest another AND operator inside the OR array.

**Comment by jessaskey** [comment]
@olifolkerd Im curious about this as well, is it possible to do 

(a AND b)
OR
(c AND d)
OR
(e AND f)

From the documentation, it is possible to do only...

(a OR b)
AND
(c OR d)
AND
(e OR f)

I did try putting a 3rd level of array thinking that it might go back to a nested AND, but it didnt seem to work... maybe that is an approach to solve this?

((a AND b) OR (c AND d)
AND
((e AND f) OR (g AND h)
AND
((i AND j) OR (k AND l))

**Comment by x11joe** [comment]
Yeah I also want to know this

**Comment by tripower** [comment]
I would also be interested for a solution
cool would be a combination of the filtrex lib
https://github.com/joewalnes/filtrex
 and tabulator 

here I found an example of filtrex 
but instead of coloring the data,
it should filter the content of a tabulator table
https://rawgit.com/joewalnes/filtrex/master/example/highlight.html

maybe somebody has an idea
thx🙏

greetings Klaus 🤗
