### ISSUE TITLE
Can we change the tabulator  Empty Table placeholder value at run time.

### ISSUE THREAD

**Issue by prk53** [olifolkerd/tabulator#1415]
eg  while building tabulator  we define something like below.
$("#example-table").tabulator({
    placeholder:"Loading..", //display message to user on empty table
});

on some condition i want to change the placeholder text to something like   
$("#example-table").tabulator({
    placeholder:"found..", //display message to user on empty table
});
 i tried but it is not working.
  thanks in advance.

**Comment by olifolkerd** [comment]
Hey @prk53 

You cannot change the text directly, but if you passed in an element then you could change the text in that:

```js
var placeholder = $("<span>initial text</span>");

$("#example-table").tabulator({
placeholder:placeholder,
});

//change place holder text
placeholder.text("new text");
```

I hope that helps,

Cheers

Oli :)

**Comment by prk53** [comment]
i wrote below code in .js file 
declaration:-
var self = this;
self.placeholderText = $("<span>initial text</span>");


tabulator code:- 
$("#customers-table").tabulator({
            height: $('#bodyPage').height() - 300, // set height of table (in CSS or here), this enables the Virtual DOM and improves render speed dramatically (can be any valid css height value)
            layout:"fitColumns", //fit columns to width of table (optional)
            placeholder: self.placeholderText,
            tooltips:true,
            columns:[ //Define Table Columns
                {title:"Name", field:"Name", headerTooltip:true},
                {title:"Remarks", field:"remark", align:"left", width: "80", visible:false,headerTooltip:true},
            ],
            
        });


function to change the place holder text
:-  
      self.updateFilter = function (event, ui) {
        var val= event.detail.value;
        self.palceholderText("No Data Found");   
      };


but it is not working. and it is showing no placeholder.

**Comment by olifolkerd** [comment]
Hey @prk53 

As with my example above you need to put that text in a span element.

Cheers

Oli

**Comment by BirukTes** [comment]
Dear future reader,

Here is my working solution, 

`//display message to user on empty table, but only at the beginning as of now, there is a delay between empty table and data displayed. Changed on datachange below...
                    placeholder: 'Loading Data... <span class="fa-3x"><i class="fas fa-spinner fa-pulse"></i></i></span>',`

Contains FontAwesome stuff, can remove it...

To change it,
`table.element.children[1].children[1].children[0].innerText = 'No Data Available';`

**Comment by ivostoykov** [comment]
Hi @olifolkerd 

I bumped into the same problem and tried suggested solution. Unfortunately it throws an error during creation:

```
tabulator.min.js:4 Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at s.redraw (tabulator.min.js:4)
    at e.h.redraw (tabulator.min.js:6)
    at ResizeObserver.<anonymous> (tabulator.min.js:12)
```
tabulator version is 4.9.3. jsfiddle: https://jsfiddle.net/ivos/6pq75brv/3/

the setup is simple:
```
var data = [{id:1}, {id:2}, {id:3}];
var placeholder = $("<span>Waiting for data</span>");
var conf = {
//  placeholder: "Waiting for data",
  placeholder: placeholder,
  columns: [
    { title: "Id", field: "id", headerFilter: "input" },
  ],
  dataFiltered: (filters, rows) =>{
    placeholder.text(filters.length > 0 ? 'No Results': 'Waiting for data');
  },
};
var t = new Tabulator('#tbl', conf);
setTimeout(function(){ t.setData(data)}, 5000);
```

If I apply a filter (i.e. 5) I got

```
Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at s.redraw (tabulator.min.js:4)
    at e.h.redraw (tabulator.min.js:6)
    at ResizeObserver.<anonymous> (tabulator.min.js:12)
```
