### ISSUE TITLE
Get history size or know in advance if I can undo/redo

### ISSUE THREAD

**Issue by mindcreations** [olifolkerd/tabulator#1416]
Hello,
I think it could be an idea to check the history of a table in order to enable/disable the Undo/Redo buttons.

For example, I think that when you open a table and you have not done anything, you should see the Undo button in a disabled state or no Undo button at all (your choice).
After you do something, the Undo button can be enabled to really undo something you have done.

To enable the Undo button theoretically I'll have to check if there is something in the history like 

`$("#table").tabulator("getUndoHistorySize")`

If I have something in the history, I can enable the Undo button otherwise it will stay disabled.

Of course, there will be

`$("#table").tabulator("getRedoHistorySize")`

to implement the same idea for the Redo action.

Another approach would be to add two new functions like these, returning a boolean:

`$("#table").tabulator("isThereSomethingToUndo")`
`$("#table").tabulator("isThereSomethingToRedo")`

What do you think about this?

**Comment by olifolkerd** [comment]
Hey @mindcreations 

I think that is a great idea, i will add it into the 4.0 release this weekend.

Thanks for the suggestion.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @mindcreations 

The new ***getHistoryUndoSize*** and ***getHistoryRedoSize*** functions have been added to the 4.0 branch and the documentation updated. 

It will be included in this weekends release.

Cheers

Oli :)
