### ISSUE TITLE
Add a native way to know if a edited row is selected

### ISSUE THREAD

**Issue by mindcreations** [olifolkerd/tabulator#1418]
In cellEdited event I need to check if the edited row is also a selected one, so I arranged this code to know about it:

```javascript
cellEdited:function(cell) {
   if(cell.getRow().row.extensions.select.selected) {
     do something 
   }
}
```

But it wouldn't be better to have something like

```javascript
cellEdited:function(cell) {
   if(cell.getRow().isSelected()) {
     do something 
   }
}
```

Or have I missed something?

**Comment by Rodbjartson** [comment]
Is it safe to access properties like you did in the first example?

My method would be a call to getSelectedRows and use a for loop to see if it is amongst the selected rows. Just put it into a method and called it isSelected.
But I agree that the more native methods, the better. 
What about creating a pull request with the correct code for finding out whether the row is selected?

**Comment by mindcreations** [comment]
> Is it safe to access properties like you did in the first example?

I think it is safe until the package maintainer doesn't change the implementation... thus it is not safe IMHO.
> My method would be a call to getSelectedRows and use a for loop to see if it is amongst the selected rows. Just put it into a method and called it isSelected.

It will be safe in this case but very slow, I have to cycle through a big table just to know if the CURRENT row is selected, it seems a very expensive task just to know a piece of data that it is immediately available.
> But I agree that the more native methods, the better. 

:+1: 
> What about creating a pull request with the correct code for finding out whether the row is selected?

Let's see before what the maintainer says about this.

**Comment by Rodbjartson** [comment]
Not at all.
`var selectedRows = $("#example-table").tabulator("getSelectedRows"); //get array of currently selected row components.`

```
for(i=0; i < selectedRows.length; i++)
{
    if(selectedRows[i] == myRow)
   { //do something
   }
}
```

Very often selectedRows will be an array of only one row

**Comment by mindcreations** [comment]
> Not at all.
> Very often selectedRows will be an array of only one row

I see. But I've considered the worst case, when you have for eg. 10000 rows in a table and you click on a button like "Select all". In this scenario, in the worst case you'll need to cycle through 10000 items to find if it is selected.

**Comment by Rodbjartson** [comment]
What if you followed my last example?

```
var selectedRowMap= {
    '1': true,
    '2': false,
    '3': true,
    '4': true
    }

alert( selectedRowMap['2'] );    // alerts false
```

Here you have a map of rows on the left side, and their values on their right side. The value tells you if it is selected or not. 1 means the row with id 1. Say you instead in your application have something called Orders. Each row is an order. The order, the row, has an unique ID, the orderID. The orderID is the left side in the map.

**Comment by olifolkerd** [comment]
Hey All,

If you have a look at the v4.0 [Release Notes](http://tabulator.info/docs/4.0/release#component-row) you will see there is a new ***isSelected*** function on the row component coming in next weeks release. which will sort all your problems.

In terms of trying to access properties directly like in your first example, i would consider that to be very UNSAFE, not only could i change those without notice as they are considered private, because you do not know what other systems use those variables you do not know how/when they could change or what effect directly manipulating them could have.

I hope that helps,

Cheers

Oli :)

**Comment by mindcreations** [comment]
Sorry, just read your reply too fast.

Yes, in this case you will get an indexed result and thus it will be fast.
Anyway, before that, you have to call "getSelectedRows" and of course this is not cheap in terms of CPU cycles when you have a lot of data:

From the current source code:

```javascript
SelectRow.prototype.getSelectedRows = function(){
	var rows = []
	this.selectedRows.forEach(function(row){
		rows.push(row.getComponent());
	})
	return rows;
};
```

**Comment by Rodbjartson** [comment]
Why would you need to call getSelectedRows?
You can directly access the row you want.
Use `theRow = cell.getRow()`
Now you have the row, and you want to see if it is selected, right? 
Then you simply get the unique id of that row, say you have a column called orderID:
`var id = theRow.getData().orderID;`
Then simply access the map in O(1) time;
`var isSelected = selectedRowMap['2']; //gives you false`

**Comment by mindcreations** [comment]
> Why would you need to call getSelectedRows?
> You can directly access the row you want.

But, it wasn't your suggestion to use getSelectedRows?

https://github.com/olifolkerd/tabulator/issues/1418#issuecomment-422748087

I've just commented on that. Anyway, I think it is not useful to continue this thread.

**Comment by Rodbjartson** [comment]
Keep in mind that also native methods do labor..
