### ISSUE TITLE
Access sort options in custom paginator

### ISSUE THREAD

**Issue by Gonzalo788** [olifolkerd/tabulator#142]
I wrote a custom paginator which you can see below. Is there any chance to access the sort parameters from tabular to pass it to the url. 

```
	paginator: function(url, pageNo, pageSize, ajaxParams ){
		var searchValue = $("#inpit-id").val();
		
		var queryParameters = {
			page: pageNo,
			size: pageSize
		};
		
		if(searchValue != "") {
			queryParameters["filter_value"] = searchValue;
		}
		
		queryParameters["sort"] = ajaxParams;
		
		return url + "?" + $.param(queryParameters);
	}
```

**Comment by olifolkerd** [comment]
You can use the getSort function.

Sorry for short reply. Not at keyboard at the mo. If u run into issues let
me know and i can post an example

**Comment by olifolkerd** [comment]
You can use the ***getSort*** function:

```js
$("#example-table").tabulator("getSort");
```

This will return an object with the sort information as properties:
```js
{
    field:"name", //field name
    dir:"asc", //sort direction (asc|desc)
}
```
