### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by mikehobson** [olifolkerd/tabulator#1420]
Hi Oli

My page is now finished and working really well, I have one last issue. I'm trying to add predefined filters and I wondered is it possible to add a filter that applies 2 fields.

So typically a filter would be 

            $("#example-table").tabulator("setFilter", [
                {field:"home_score", type:"=", value:2},
               ]);

and this works fine but what to do is have a filter

            $("#example-table").tabulator("setFilter", [
                {field:"home_score", type:"=", value:"away_score"},
                ]);

So if home_score and away_score are equal then thats the result I get, I have tried using variuos options but I cant get it to work

My work around would be to have 2 conditions

 {field:"home_score", type:"=", value:0},
 {field:"away_score", type:"=", value:0},

but I would also like the filter to pick up 1 - 1 scores

So my filter would now be 
if home_score=0 and away_score=0
OR
if home_score=1 and away_score=1

but I cant figure out the logic for this either

Any advice would be greatly appreciated

**Comment by olifolkerd** [comment]
Hey @mikehobson 

You would need to use a custom filter function to achieve this. you can read more about it in the [Filter Documentation](http://tabulator.info/docs/3.5#filtering)

I hope that helps,

Cheers

Oli
