### ISSUE TITLE
How to create table in svg foreign object??

### ISSUE THREAD

**Issue by satyam10zs** [olifolkerd/tabulator#1423]
Hi,

I have two files list.svg and list.html 

**LIST.svg**

**list.html**

Kindly rename the attached files to list.html and list.svg.

Unable to create table. Please suggest where I am doing wrong
[list_html.txt](https://github.com/olifolkerd/tabulator/files/2399802/list_html.txt)
[list_svg.txt](https://github.com/olifolkerd/tabulator/files/2399803/list_svg.txt)

**Comment by olifolkerd** [comment]
Hey @satyam10zs 

The issue that you have is that you are missing your ***example-table*** div.

In your code you are using `document.getElementsByClassName('example-table')` but you have no element with that class in your body.
```js
<div class="example-table"></div>
```

a Tabulator can only be created on a ***div*** or ***table*** tag.

I hope that helps,

Cheers

Oli

**Comment by satyam10zs** [comment]
Please check list_svg.txt(list.svg) which will be loaded by list.html. List.svg contains 

`<div class='example-table'></div>
`

following lines were supposed to create the table.
var svgObject = document.getElementById('layers').contentDocument;
var obj = svgObject.getElementsByClassName('example-table')[0];
....
var table = new Tabulator(obj,...

**My Fix**
Tabulator.prototype.initializeElement = function (element) {

	//Added by Satyam Singh
	this.element = element;
	return true;

	if (element instanceof HTMLElement) {

		this.element = element;

		return true;
	} 
.....
}

Please provide a suitable solution.

**Comment by olifolkerd** [comment]
Hey @satyam10zs 

I am happy to help, but im afraid the onus is on you to provide an example of you issue, im afraid i dont have the time to trying and build projects from source files on here.

i would start by suggesting that you check what your ***obj*** variable contains, and then check that has been added to the DOM before Tabulator is instantiated.

Your approach is a bit non standard so im afraid i cant comment on how it would work inside an object tag.

Sorry i cant be more helps,

Cheers

Oli :)
