### ISSUE TITLE
xlsx export with column groups

### ISSUE THREAD

**Issue by anthonydonx** [olifolkerd/tabulator#1427]
Can i export table data with **Column Group** titles? Column Group titles are not export with download option.Tabulator didn't  support with column groups?Help me to resolve,

Table Structure 
`columns:[
        {title:"Name", field:"name", width:160},
        {//create column group
            title:"Work Info",
            columns:[
                {title:"Progress", field:"progress", align:"right"},
                {title:"Rating", field:"rating", align:"center"},
                {title:"Driver", field:"car", align:"center"},
            ],
        },
        {//create column group
            title:"Personal Info",
            columns:[
                {title:"Gender", field:"gender"},
                {title:"Favourite Color", field:"col"},
                {title:"Date Of Birth", field:"dob"},
            ],
        },
    ],

`
![screenshot from 2018-09-20 19-02-50](https://user-images.githubusercontent.com/6302284/45821882-e2a9ce00-bd07-11e8-921c-00a75c601739.png)

**Comment by olifolkerd** [comment]
Hey @anthonydonx 

Im afraid this isnt currently possible, Tabulator only exports the base columns at the moment.

This will be coming in a future release though.

Cheers

Oli :)

**Comment by alfredormorales** [comment]
Hi Oli, theres is a new about this request on 4.1 version or is on queue for next features?

Cheers!

**Comment by olifolkerd** [comment]
Hey @alfredormorales 

Thanks for getting in touch,

Just a note for the future, there is no need to post the same question across multiple issues, i get notified when any one post, so just one post is enough.

Yes this functionality came in version 4.1 and is enabled by default.

Cheers

Oli :)

**Comment by alfredormorales** [comment]
Sorry Oli I don't see the duplicate label on this question, thank you for your response, I will upgrade to 4.1 for apply this new functionality.
