### ISSUE TITLE
Version 4 doc reversed definition

### ISSUE THREAD

**Issue by aklaver** [olifolkerd/tabulator#1428]
Pretty sure the below is reversed:

http://tabulator.info/docs/4.0/jquery

"Table Defintion

Anywhere it shows the new way of instantiating a table:

$("#example-table").tabulator({
  //table setup options
});

You can use the old method:

var table = new Tabulator("#example-table", {
  //table setup options
});
"

**Comment by olifolkerd** [comment]
Hey @aklaver 

Thanks for the headsup, i have updated the documentation

Cheers

Oli :)

**Comment by tomvanlier** [comment]
Minor error in doc (if there's a better way to report this, let me know) I believe

http://tabulator.info/docs/4.0/edit#edit-builtin

in the datEditor, doesn't it need to be date in the attribute, after type? It didn't work with number in mine, but works with date (which makes sense)

**Comment by olifolkerd** [comment]
Hey @tomvanlier 

Good spot!, just pushed a fix for that now.

Cheers

Oli :)

**Comment by tomvanlier** [comment]
Also when I emplement the date-editor as in your code, the succesFunc() happens twice : 

Edit Success Error - cannot call success on a cell that is no longer being edited

**Comment by olifolkerd** [comment]
Hey @tomvanlier 

Yes that happens on a few of the editors as a result of them needing to catch the blur result as well a enter/success.

It doesn't affect table function as they just get ignored.

I am looking at removing the warning before i launch 4.0 as it is more confusing that it is helpful.

Thanks for the feedback.

Oli :)
