### ISSUE TITLE
table.addRow({ }) creates text "undefined" in 4.0

### ISSUE THREAD

**Issue by fortrax** [olifolkerd/tabulator#1430]
Hi Oli,

I used to add a blank row with addRow({ }) in one of my tables. The button "Add blank row to button" seems to works on your 4.0 examples page. But it is not editable.

When I tested this with 4.0, adding the row first seems fine. But when you click in one of the cell editors, it shows the text "undefined".

Cheers,
Andreas

**Comment by aklaver** [comment]
I am seeing the same thing, 'undefined' showing up in new rows when entering an editor in version 4.0.

That example did not allow editing in the 3.5 case either. Pretty sure it is because the actual table definition(not the one in View Source) has:
```
cellEdited:function(cell){

	     },
```

**Comment by olifolkerd** [comment]
Hey @fortrax 

Are you running on the latest version of 4.0? this was definitely an issue in the earlier 4.0 code, but i pushed a fix for it earlier in the week. it was down to formatters not handling the undefined value correctly.

If you belive you are on the latest version and this is still the case could you please post a copy of your table constructor so i can replicate the issue.

@aklaver the cellEditied callback has no affect on editing or the value of data, it is called after the update.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @fortrax 

if you want a column to be editable you need to specify that in the column definition.

Cheers

Oli :)

**Comment by aklaver** [comment]
@fortrax  was referring to this example:

http://tabulator.info/examples/4.0#adddel

also:

not being editable

**Comment by olifolkerd** [comment]
Hey @fortrax @aklaver 

That example isnt supposed to be editable, it is demonstrating the manipulation of rows, not editors.

Cheers

Oli :)

**Comment by aklaver** [comment]
How can that be when editors are set?

**Comment by aklaver** [comment]
I got the code from here:

https://github.com/olifolkerd/tabulator/archive/4.0.zip

on September 20th. 
How often is 4.0.zip is refreshed?

**Comment by olifolkerd** [comment]
Hey @aklaver 

Ahh that is some bad example code there, that has the ***editable*** property set to true, which means the cell would be allowed to be editable if the ***editor*** property had been set.

I have removed the confusing lines of code from the example

Cheers

Oli :)

**Comment by olifolkerd** [comment]
@aklaver @fortrax 

Ahh i see your issue now i was misread your initial message, it is the same issue that the formatters which i fixed but it is happening with the editors.

 I will work on a fix for that now, Thanks for the headsup

Oli :)

**Comment by olifolkerd** [comment]
The issue should now be resolved,

i have pushed a fix to the 4.0 branch and updated the website.

you many need to force refresh your browser on the 4.0 example page.

Cheers

Oli :)

**Comment by aklaver** [comment]
@olifolkerd 
The 4.0 example works for me now.
Thanks.
