### ISSUE TITLE
getOldValue() in custom validator returns null

### ISSUE THREAD

**Issue by mindcreations** [olifolkerd/tabulator#1434]
cell.getOldValue() in custom validator returns null

Is it normal or... ?

The column has an editor of type "select".

**Comment by olifolkerd** [comment]
Hey @mindcreations 

If the value has never changed then that is correct. at the point the validator is called the cell has yet to change value.

If you want the value before the user edited it just call the ***getValue*** function as the value isnt updated till the validator returns true.

Cheers

Oli :)

**Comment by mindcreations** [comment]
You are right. Sorry for the silly question.

**Comment by olifolkerd** [comment]
@mindcreations No need to apologies, im sure plenty of people have run into this and now they can find the answers on here :)
