### ISSUE TITLE
Features for improved download module

### ISSUE THREAD

**Issue by olifolkerd** [olifolkerd/tabulator#1436]
Hey All,

I have had a few people looking for additional functionality for file downloads, including:

- ✔️ allowing download of hidden columns
- choosing if filtered rows are in the download
- ✔️ showing grouped rows in the download
- ✔️ showing column group headers in the download
- ✔️ include column calculations in downloads

Rather than having lots of issues relating to this, i thought i would create one issue where people can share their thoughts so i can put it on the roadmap for the next version.

Cheers

Oli :)

**Comment by JHenneberg** [comment]
I definetly would appreciate this feature. I have a massive table and only a small fraction is shown but the complete table should be downloaded. 
Thanks for this great framework

**Comment by tentus** [comment]
I'm trying to figure out a simple way to make downloads where the value is `null` render as empty rather than rendering as the string "null". I suspect there's probably already a way to do this but I haven't quite found it yet.

**Comment by olifolkerd** [comment]
Hey @tentus 

You can use a download accessor for this:
```js
//define custom accessor
var nullToEmptyString = function(value, data, type, params, column){
	//value - original value of the cell
	//data - the data for the row
	//type - the type of access occurring  (data|download|clipboard)
	//params - the accessorParams object passed from the column definition
	//column - column component for the column this accessor is bound to

	return value || ""; //return the new value for the cell data.
}

//column definition
{title:"Name", field:"name", accessorDownload:nullToEmptyString}
```

I hope that helps,

Cheers

Oli :)

**Comment by Rodbjartson** [comment]
Hey @olifolkerd 
Any status on the option to download hidden columns? Would love to see this feature!
Are you planning on releasing it in 4.2?

**Comment by olifolkerd** [comment]
@Rodbjartson Yes i will look at adding that in 4.2 :)

**Comment by Rodbjartson** [comment]
Happy days!

**Comment by Remph** [comment]
Hey, @olifolkerd 

Are there any plans for adding the column calculations to the xlsx or pdf exports?

**Comment by olifolkerd** [comment]
when version 4.2 is released on monday you will be able to include hidden columns in the download by setting the ***download*** property to ***true*** in the column definition:
```js
 {title:"id", field:"id", visible:false, download:true}
```

Column calculations will also be included in downloads by default

Cheers

Oli :)

**Comment by ipalfy** [comment]
Not being able to download the full table - I use remote paging with many pages - is a bit frustrating. However, it could be somehow done by setting pagination to "max" before/while downloading.

Getting a sample of how to do it would be good enough ...

**Comment by LuisCarrizo** [comment]
Hey, @olifolkerd. I´m recently using the library, and it´s great. 

I there a way to format a column total when exporting the table?

this is the code for the column definition:

{title:"Sales", field:"sales", width:150 , align:"right"  ,
              bottomCalc :"sum",bottomCalcFormatter:"money" , 
               bottomCalcFormatterParams:{
                decimal:","   ,  thousand:"."  ,  symbol:"$ "  ,  symbolAfter:false  ,  precision:false,
              },
              formatter:"money", formatterParams:{
                decimal:"," ,  thousand:"." , symbol:"$ " , symbolAfter:false , precision:false,
              },
              sorter:"number",
              accessorParams:{}, accessor:caSales,
            },

      var caSales= function(value, data, type, params, column){
        return numeral(value).format('$ 0,0'); 
      } 

The column data is exported with the correct format, but column total is exported without format.

try both export to PDF and XLSX.

Thanks in advance,

Luis

**Comment by sogrbilja** [comment]
I use this approach to include a hidden column (my hidden column is ID):

```
if (_downloadCSV) {
  _downloadCSV.addEventListener('click', function (e) {
    _table.showColumn(_table.options.index);
    _table.download("csv", window._modelClass + ".csv", {delimiter: ";", bom: true});
    _table.hideColumn(_table.options.index);
  });
}
```

**Comment by olifolkerd** [comment]
@sogrbilja this is a really old issue, the download attribute was added to the column definition a couple of years ago that lets you specify that a hidden column should be included in a download.

Cheers

Oli :)

**Comment by sogrbilja** [comment]
hehe, agreed, but this one works as well, and maybe someone likes it this way!

**Comment by Keorl** [comment]
> Hey [@tentus](https://github.com/tentus)
> 
> You can use a download accessor for this:
> 
> //define custom accessor
> var nullToEmptyString = function(value, data, type, params, column){
> 	//value - original value of the cell
> 	//data - the data for the row
> 	//type - the type of access occurring  (data|download|clipboard)
> 	//params - the accessorParams object passed from the column definition
> 	//column - column component for the column this accessor is bound to
> 
> 	return value || ""; //return the new value for the cell data.
> }
> 
> //column definition
> {title:"Name", field:"name", accessorDownload:nullToEmptyString}
> 
> I hope that helps,
> 
> Cheers
> 
> Oli :)

Thought about that solution but it isn't very satisfying, which is why I ended here after a google search.
A global parameter for this, or a defaultAccessorDownload defined at table level would be great, so we don't have to add an accessorDownload for every single column just because of possible nulls :)
