### ISSUE TITLE
Tabulatro filtering example

### ISSUE THREAD

**Issue by mfenton01** [olifolkerd/tabulator#1439]
Hi Oli, 

Question on filtering example.  Following your example  though I am modifying the return in the custom filter.  When selecting the drop-down filter. The filter does not provide the result expecting.  Could I be missing a step? 
```js
//Custom filter example
function customFilter(data){
	return data.Datacenter == "ADC1";
}

//Trigger setFilter function with correct parameters
function updateFilter(){

	var filter = $("#filter-field").val() == "function" ? customFilter : $("#filter-field").val();

	if($("#filter-field").val() == "function" ){
		$("#filter-type").prop("disabled", true);
		$("#filter-value").prop("disabled", true);
	}else{
		$("#filter-type").prop("disabled", false);
		$("#filter-value").prop("disabled", false);
	}

	$("#example-table").tabulator("setFilter", filter, $("#filter-type").val(), $("#filter-value").val());
}
```

**Comment by olifolkerd** [comment]
Hey @mfenton01 

I would suggest putting some console.log statements in there and seeing what values are getting passed into your functions.

If you can work out what is being sent into the functions let me know,

Cheers

Oli :)

**Comment by mfenton01** [comment]
Thus  was a syntax issue. A silly bracket where it should not be.
