### ISSUE TITLE
precision false on money formatter

### ISSUE THREAD

**Issue by tomvanlier** [olifolkerd/tabulator#1442]
Hey,

I try to use a money formatter with precision false 

    {title:"cost", field:"cost",formatter:"money",formatterParams: {decimal : "," , precision:"false"},visible : false, editor:true}

But the number gets rounded on the unit. If for instance I enter 12,5 it shows 12. When I enter 12.5 it shows 13. When I re-edit the cell however the value was saved (so it's only a showing issue). I however understood that precision false will show the precision after the decimal seperator.

Using the standard decimal seperator also doesn't help. This is tabulator 4.0

**Comment by olifolkerd** [comment]
Hey @tomvanlier 

You need to pass the boolean ***false*** not the string ***"false"*** to the precision property.

I hope that helps,

Cheers

Oli :)

**Comment by tomvanlier** [comment]
Thjat's what I also thought, but that throws the following error, which is why I changed it to string.

**Comment by olifolkerd** [comment]
Hey @tomvanlier 

Definitely a bug you have found there, i have just pushed a fix for this to the master branch and will include it in this weekends patch release.

Cheers

Oli :)
