### ISSUE TITLE
Tabulator doesn't display if the boolean value is FALSE for a column

### ISSUE THREAD

**Issue by kiran-peddikuppa** [olifolkerd/tabulator#1443]
If the column is boolean, only TRUE is displayed and FALSE is left out as blank.How to display both true and false

**Comment by olifolkerd** [comment]
Hey @kiran-peddikuppa 

You need to use a formatter in your column definition to display a boolean value.

You could either use the ***tickCross*** formatter that will display them as graphical ticks or crosses:
```js
{title:"Likes Cheese", field:"cheese", formatter:"tickCross"}
```
Or you could use a custom formatter function to display them as text:
```js
//define formatter
var booleanFormatter = function(cell){
    return cell.getValue() ? "true" : "false";
}

//in your column definition
```js
{title:"Likes Cheese", field:"cheese", formatter:booleanFormatter }
```

I hope that helps,

Cheers

Oli :)

**Comment by kiran-peddikuppa** [comment]
awesome Oli..
