### ISSUE TITLE
icon/button columns with empty headers (html imported table)

### ISSUE THREAD

**Issue by andybutkaj** [olifolkerd/tabulator#1445]
Hello,

I can't seem to find out (Documentation 4.0) how to display several icon/button columns (e.g. 5 columns but without header title) while the table is created from the HTML table element. 

I understand that the issue is that columns don't have the unique title (as header in html is `<th></th><th></th>...`), and javascript: 

                {title:"", formatter:"html", width:40, headerSort:false},
                {title:"", formatter:"html", width:40, headerSort:false},

If I choose unique title (title:"c1"), it would create extra column. and I cannot put my title to html <th></th>, as I want my header empty (css style hiding does not work).

Is there a way how to have several html icon/button columns, while header for each of them is empty but somehow they have unique title/id so it does not create problems for javascript? (table created from HTML table element)

Your help or any advice is much appreciated.

**Comment by andybutkaj** [comment]
This is not a bug. Everything works when I have html header
`<th>a</th><th>b</th>
`and javascript:

            {title:"", formatter:"html", width:40, headerSort:false},
            {title:"", formatter:"html", width:40, headerSort:false},

the only issue I have is that the header title is not empty. Thank you.

**Comment by olifolkerd** [comment]
Hey @andybutkaj 

You can define the columns in your column definition then you dont need to include them in the actual table at all if that helps?

Cheers

Oli :)

**Comment by andybutkaj** [comment]
Hey Oli,
Thank you for your answer!

I have these columns dynamically added/hidden and It would be too complicated for me to take the logic to JS/column definitions now. I believe I'll find a way to hide these particular header titles in CSS (that will be easier in my case) .

Cheers!
