### ISSUE TITLE
Need dynamic row/cell Adjustment. 

### ISSUE THREAD

**Issue by MaheshBW** [olifolkerd/tabulator#145]
I am requesting to implement a new feature which I need to use in the one of the app, which I am developing.

Here is the scenario :
In One of the column and in each cell I need to show name and path.
Ex: CARS (D:\Basic\Developers\Assets)
Above representation can be done in "formatter" and that is fine.
Main scenario is below which I am not able to implement 
ex: there are 3 files in drive D and in some folder. Their names are CARS, HOMES, FLATS

then I need to show them in a cell as bellow:
>(Arrow mark or image) should appear if there are multiple rows like below and when clicked these will be shown when clicked on Arrow mark if it is collapsed, if it is expanded mode it should close on click and view should be single row size(20px as normal). When it is in expanded mode whole row size(height) should increase according to number or rows in cell (as below)
 
CARS(D:\Basic\Developers\Assets\Cars) 
HOMES(D:\Basic\Developers\Assets\HOMES) 
HOMES(D:\Basic\Developers\Assets\FLATS) 

How do we can achieve such behavior ? Is it possible to implement in current 2.8 Version ?
If so please let me know. If not can you please this as a new feature candidate to be introduced in upcoming release.

Also I see one more problem. Row selection behavior can be, only one row should get selected at a time. Right now all the clicked rows gets selected. Can we select only one row at a time?
Thanks 
Mahesh

**Comment by olifolkerd** [comment]
Hi Mahesh,

Thanks for getting in touch

Could you post a picture of what you are trying to create (a rough sketch would do) so i can visualise what you are trying to do.

Also if you only want one row to be selectable then you can pass an integer value to the ***selectable*** option:
```js
$("#example-table").tabulator({
	selectable:1, // allow only one row to be selected
});
```

**Comment by MaheshBW** [comment]
![image](https://cloud.githubusercontent.com/assets/24955822/21794971/ef19ec44-d724-11e6-8ddd-833d5f2cc9db.png)

Thank you Oli Folkerd for considering my suggestion. 
Due to internal policies I cannot post any screenshot of the page. Please find a similar behavior in above image. 

I am exploring tabulator to use in our project. We have around 50 to 70 tables in which we are going to introduce tabulator for each table. Tabulator is approved by the team to include in projects.

Also Is it possible to implement lazy loading(As user scrolls down data/rows will be fetched from back end and appends to existing table list, may be 50 rows fetched each time when user reaches end of the page/table) ? We need to implement this behavior using web service call (POST but not GET). We are trying to avoid pagination in this case. 

One more point what I observed is, in case of "Remote Pagination" : URL gets updated with page numbers when we click on pagination numbers, how ever We have AJAX POST calls to execute. With tabulator we cannot use pagination if we use POST calls to the backend. Please enlighten me I am wrong.

Thank you very much for the reply and your support matters a lot. 
Please let me know if I am still not clear to convey my points. 

Thanks
Mahesh

**Comment by olifolkerd** [comment]
Hey Manesh,

Thanks for the image, that is much clearer, i can certainly help you out there. im a bit pressed with work today but i will post a solution for you tomorrow evening.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hi Manesh,

The good news is Tabulator can do everything you are after. I will breakdown my response to answer each of your questions.

## List Values Formatter
To display multiple values in one cell is perfectly possible. in this example we will be storing multiple path values in a array in the ***path*** field in the data array:
```js
var data = [
	{id:1, path:["C:\Graphs"]},
	{id:2, path:["C:\Images", "C:\Stuff"]},
]
```

We will then need to create a custom formatter that builds the "multiple" selection header when there are moth than one items in the array, and then creates an ordered list of those items to display:

```js
var pathFormatter = function(value, data, cell, row, options, formatterParams){

	if(value){
		if(value.length == 1){
			//handle single value
			return value[0];
		}else{
			//handle multiple values

			//build holder element
			var element = $("<div><div class='header'><span class='arrow'></span><span>Multiple</span></div><ul style='display:none;'></ul></div>");

			var list = $("ul", element);

			//add data
			value.forEach(function(path){
				list.append("<li>" + path + "</li>");
			});

			//hadle toggle of show/hide state
			$(".header", element).on("click", function(e){

				//show list
				$(".arrow", $(this)).toggleClass("open");
				list.toggle();

				//resize row to fit list
				$(".tabulator-cell, .tabulator-row-handle", row).css({"height":""});
				$(".tabulator-cell, .tabulator-row-handle", row).css({"height":row.innerHeight() + "px"});
			});

			return element;
		}
	}

	//handle no value
	return "";
}
```

We will also need a bit of css to style the arrow icon:
```css
<style type="text/css">
	.tabulator-row .arrow{
		display: inline-block;
		box-sizing: border-box;
		vertical-align: middle;

		height:10px;
		width:10px;

		margin-left:5px;
		margin-right:10px;
		border-left: 6px solid transparent;
		border-right: 6px solid transparent;
		border-top: 6px solid #a00;
		border-bottom: 0;
	}

	.tabulator-row .arrow.open{
		border-top: 6px solid transparent;
		border-bottom: 6px solid transparent;
		border-left: 6px solid #a00;
		border-right: 0;
	}
</style>
```

We can then build our table with the following constructor:
```js
$("#example-table").tabulator({
	height:300,
	columns:[
		{title:"Path", field:"path", width:200, formatter:pathFormatter},
	],
});

$("#example-table").tabulator("setData", data);
```

## Progressive Rendering via Ajax with POST
you can set the type of ajax request made using the ***ajaxType*** option, so in your case you would use something like:
```js
$("#example-table").tabulator({
    progressiveRender:"remote", //enable progressive rendering
    ajaxURL:"/data/page", //set the ajax URL
    ajaxType:"POST", //ajax request type
    progressiveRenderSize:50, //number of rows to get in page request
});
```

Let me know if this has answered all your questions.

Many Thanks

Oli

**Comment by MaheshBW** [comment]
Hi Oli,

Thank you. I was out of office. I will try your suggestion and come back with results.

Thanks
Mahesh
