### ISSUE TITLE
Duplicated pagination? (top and bottom at the same time)

### ISSUE THREAD

**Issue by studio404pl** [olifolkerd/tabulator#1452]
Hi @olifolkerd , i am working since 2 days with this library and i am really enjoying it. Documentation is well written but still some things are not covered. It's inevitable :)

Is there a way to duplicate/clone pagination module to show it also at the top of the table? I want to be able to display controls on top and the bottom of table to make navigation more intuitive. I am already querying. Currently i am using custom element to display it:

```
paginationElement: document.getElementById("sample_table_pagination"),
```

and it works fine but looks like i can pass only one DOM element. I was trying this:

```
paginationElement: document.querySelectorAll(".pagination")
```

and no success.

**Comment by olifolkerd** [comment]
Hey @studio404pl 

Im afraid Tabulator has no built in support for multiple sets of pagination controls.

However you could implement this functionality yourself with your own DOM elements and call the ***setPage*** functions your self.

Cheers

Oli :)

**Comment by Shreyas-BS** [comment]
This would be a good feature to add.

**Comment by saidie** [comment]
Following code provides two pagination modules. There might be some side effects but so far it seems ok on my end.

```js
const top = document.getElementById("tabulator-top-pagination");
const bottom = document.getElementById("tabulator-bottom-pagination");

const table = new Tabulator(..., {
  ...
  paginationElement: top,
  ...
});

const observer = new MutationObserver(function (mutations, observer) {
    bottom.innerHTML = top.innerHTML;
});
observer.observe(top, {childList: true, subtree: true});
```

**Comment by dmorgan** [comment]
PLEASE PLEASE PLEASE unsubscribe me. I have tried three times vis web site without success. Great product. But I do NOT want emails!!!THANK YOU. 🙏🏼🙏🏼🙏🏼? -> !On Jul 3, 2023, at 5:09 AM, Hiroshi Saito ***@***.***> wrote:﻿
Following code provides two pagination modules. There might be some side effects but so far it seems ok on my end.
const top = document.getElementById("tabulator-top-pagination");
const bottom = document.getElementById("tabulator-bottom-pagination");

const table = new Tabulator(..., {
  ...
  paginationElement: top,
  ...
});

const observer = new MutationObserver(function (mutations, observer) {
    bottom.innerHTML = top.innerHTML;
});
observer.observe(top, {childList: true, subtree: true});
