### ISSUE TITLE
Column sort application order works backwards.

### ISSUE THREAD

**Issue by schrag** [olifolkerd/tabulator#1454]
**Describe the bug**
table.setSort's argument elements are applied in reverse order, w.r.t. documentation.  It's supposed to sort first on the first element, etc.

**Tabulator Info**
- Which version of Tabulator are you using?  
4.0
- Post a copy of your construct object if possible so we can see how your table is setup
Is there a table.method to create this?  I would be happy to share.

**Screenshots**

Table is rendered thus, with `initialSort` arg as shown.

![image](https://user-images.githubusercontent.com/4502215/46049427-312de280-c0e3-11e8-8d84-7bd9e0db25b8.png)

**Desktop (please complete the following information):**
Linux
Chrome
61.0.3163.100 (Official Build) (64-bit)

**Comment by olifolkerd** [comment]
Hey @schrag 

Thanks for getting in touch,

That is doing exactly what the documentation is describing, it is not the priority of the sorts it is the order in which the are applied. so in your case it is sorting by the ***Out_Eff*** column and then taking the results from that and sorting by the ***Over_Eff*** column.

I hope that clears things up.

In case you need it for future issue, the constructor object is the object you pass into the Tabulator constructor function:
```js
var table  = new Tabulator("#selector",{... this is the constructor object ...});
```

Cheers

Oli :)

**Comment by schrag** [comment]
Hi, Oli.

Thanks for the quick response.  Might be helpful to put an example in the documentation (didn't see one in the [section](http://tabulator.info/docs/4.0/sort#manage) I read)---given that this treatment is opposite of (e.g.) MS Excel.

Best,
Bob
