### ISSUE TITLE
Filter not applied when adding new datta

### ISSUE THREAD

**Issue by clemshubs** [olifolkerd/tabulator#1457]
Hi !

I'd like to report what I suppose to be a bug.

When I add data to the table (which I do every 1/5th of a second), the regex of header columns filters are not effective on the newly added data. I use the addData method to do so.

It doesn't work either when I set the filter programmatically (setFilter()....).
Trying to reapply the filter every now and then is not usable.

In the Filter documentation, it says "Filters will remain in effect until they are cleared, including during setData calls". 

- Is it a normal behavior ? 
- Would it be possible to have the same behavior with addData and addRow (i tried both, both failed) ? 
- If not, how can I have the same behavior ? 
- I presume using setData every 1/5th of a second will not be very effective. Am I wrong ?

I work on Firefox 45.8 and I develop a simple log viewer for complex systems.

Love your work,
Cheers,
Clement

**Comment by olifolkerd** [comment]
Hey @clemshubs 

Thanks for getting in touch,

Could i ask that when you raise future issues you use the template provided as it will prompt you for the information needed to resolve a bug, The reason i ask is that in order to resolve an issue it is often necessary to know more about your setup, such as the browser you are using (not just the OS), the version of Tabulator you are using etc.

In order to get to the bottom of your issue i need to know a bit more information, could you provide the constructor object for the table along with the call you are making to update the table.

Cheers

Oli :)

**Comment by clemshubs** [comment]
Hi Oli !
I'm sorry I didn't saw the template :(

Here is my reformulated question :

**Describe the bug**
When I add data to the table (which I do every 1/5th of a second), the regex of header columns filters are not effective on the newly added data. I use the addData method to do so.

It doesn't work either when I set the filter programmatically (setFilter()....).
Trying to reapply the filter every now and then is not usable.

In the Filter documentation, it says "Filters will remain in effect until they are cleared, including during setData calls".


**Tabulator Info**
- Tabulator V4.0
```
Tabulator('#table',{
  data: logs,
  layout: "fitColumns"
  placegolder: "Waiting for Logs",
  addRowPos: "top",
  movaleColumns: true,
  resizableRows: false,
  initialSort:[{column: "date", dir "desc"}],
  columns: [{ "title": "date", "field": "date", "formatter":"textarea", "headerFilter": "input", "headerFilterFunc":"regex"},
            { "title": "level", "field": "level", "formatter":"textarea", "headerFilter": "input", "headerFilterFunc":"regex"},
            { "title": "textmsg", "field": "textmsg", "formatter":"textarea", "headerFilter": "input", "headerFilterFunc":"regex"}],
rowFormatter: function(row,data){
  switch(row.getData().level){
    case "err":
      row.getElement().style.backgroundColor="rgba(255,0,0,0.7)";
      break;
    case "warn":
      row.getElement().style.backgroundColor="rgba(255,225,10,0.7)";
      break;
  }
}
```

**To Reproduce**
- Set a filter on one or several headers
- Add new data through addData or AddRaw methods
-> The newly added data is not filtered

**Expected behavior**
The filter should reapply to these news rows.


**Desktop (please complete the following information):**
 - OS: RHEL 6.5
 - Firefox
 - 45.8

**Additional context**
I develop a simple log viewer for complex systems. The goal is to have a realtime view of a Logstash Output, so there is a continuous flow of information (hence, the real time filtering need).

Hope it fits the template !

Cheers,
Clement

**Comment by olifolkerd** [comment]
Hey @clemshubs 

Thanks for the details there.

The ***addRow*** and ***addData*** functions do not pay attention to the header filters. the reason for this is to allow people to for example add a new row blank row to the table when it is filtered that they may then want the user to fill in.

I would suggest that you maintain your data in an array outside of Tabulator and then dump it all back into your table using the ***replace*** data function that will keep the scroll in the same position when the data is replaced.

The other option would be to use the promise return from the ***addRow*** and ***addData*** functions to call the ***setHeaderFilterValue*** function on the appropriate column component to reinstate the filter.

I hope that helps,

Cheers

Oli :)

**Comment by clemshubs** [comment]
Oli,

OK I get it. I'll try what you suggest :)

Cheers,
CHA
