### ISSUE TITLE
Feature request: !default flags on SCSS vars

### ISSUE THREAD

**Issue by dahfazz** [olifolkerd/tabulator#1458]
**Is your feature request related to a problem? Please describe.**
Writing Tabulator code in SCSS and using Theme structure is a great opportunity to allow anyone to create (and share) his own custom theme. The only thing missing is the ability to set Tabulator SCSS vars being sure they won't be reset by Tabulator code.

**Describe the solution you'd like**
The solution would be to add a `!default` flag on every SCSS vars.
That way, if I define one of your var before loading your SCSS code, I'm sure your var definition won't override mine.

**Additional context**
example...

Let say I write something like

```scss
$backgroundColor: magenta;
@import 'tabulator';
````

Without `!default`, the following code would make my code totally useless
 ```scss
//Tabulator Containing Element
$backgroundColor: #888; //background color of tabulator
````

But, simply adding the `!default` flag would fix this
 ```scss
//Tabulator Containing Element
$backgroundColor: #888 !default; //background color of tabulator
````

With `!default` flag, you are sure that you variable will be set unless it has already been before.
That way, you can add `!default` on all your variables and allow anyone to create a custom theme.

**Comment by olifolkerd** [comment]
Hey @dahfazz 

Great suggestion!

I would be happy to add that in for the 4.1 release. or if you fancy contributing yourself you would be welcome to submit a pull request with the tweaks in.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
all done now

**Comment by dahfazz** [comment]
Hi @olifolkerd 
Great to see my PR already merged.
You no have the opportunity to highlight the new feature on the website: "Custom theme creation"

Tabulator might be used by the company I'm working for now, but customizing the theme was the only missing feature. If we go for it now, I'll let you know.

++

**Comment by olifolkerd** [comment]
Hey @dahfazz 

Yes i will update it on the website when the release goes out later today.

Cheers

Oli :)
