### ISSUE TITLE
Setting CSV Separator as it's not the same for all countries.

### ISSUE THREAD

**Issue by fabricecouvert** [olifolkerd/tabulator#146]
Hi,
**Is there a way  to set which separator  should be used when exporting to csv ?**

As an example I'm a french user and in my case csv separator should be ";" not "," as "," is used as decimal separator in our country.
setting csv separator permits 'noob' user to open file in excel by double clicking on  it without having to import it from text (as 90% of them don't know how to do that :) ).

Thanks for this amazing plugin :).

**Comment by olifolkerd** [comment]
Hey,

Thanks for getting in touch, glad to hear you are enjoying using Tabulator

You can make any file type you want using a custom file formatter. The function below will make a semi-colon delimited csv file.:

```js
//custom file formatter
var fileFormatter = function(columns, data){
    //columns - column definition array for table (with columns in current visible order);
    //data - currently displayed table data

    //get field lists
    var titles = [];
    var fields = [];
    var delimiter = ";";

    columns.forEach(function(column){
    	if(column.field){
    		titles.push(column.title)
    		fields.push(column.field)
    	}
    });

    //generate header row
    var fileContents = [titles.join(delimiter)];

    //generate each row of the table
    data.forEach(function(row){

    	var rowData = [];

    	fields.forEach(function(field){
    		rowData.push(row[field]);
    	})

    	fileContents.push(rowData.join(delimiter));

    });

    //return data URI formatted string
    return 'data:text/csv;charset=utf-8,' + encodeURIComponent(fileContents.join("\n"));
}

//trigger file download
$("#example-table").tabulator("download", fileFormatter, "test.txt");
```

Full documentation for this feature can be found [here](http://olifolkerd.github.io/tabulator/docs/#download)

Let me know if you have any questions.

**Comment by fabricecouvert** [comment]
Thanks ..

**Comment by olifolkerd** [comment]
Hey,

Version 2.11 of Tabulator now has enhanced CSV generation.

All data is automatically sanitised and escaped so there are no data import issues.

You can also set a custom delimiter character using the new options object:

```js
$("#example-table").tabulator("download", "csv", "data.csv", {delimiter:"."}); //use fullstop delimiter in CSV
```
Full information can be found [here](http://olifolkerd.github.io/tabulator/docs/#download)

Cheers

Oli
