### ISSUE TITLE
Native internal search

### ISSUE THREAD

**Issue by mindcreations** [olifolkerd/tabulator#1461]
In my use case I would like to avoid duplicates on the table.

For example, the table has three columns: Name, Surname and Notes.
I would like to check if Name and Surname are already on the table and prevent the user from adding the same person two times.

While I can filter anything I want regarding *display*, I can't see a native method to search on the contents of the table.

I was thinking this could be an interesting feature to add regarding validation, but of course, general search functions are even better.

In the meantime this will or will not be implemented, do you have any suggestions on how to efficiently query the table from Js to achieve such goal?

Thank you for your continuous efforts :1st_place_medal:

**Comment by olifolkerd** [comment]
Hey @mindcreations 

At the moment that isnt available as a built in feature, but with a few additions to the filter function i can certainly make that a reality, i will add it to the road map for the next release.

In the mean time i suggest you use the ***getData*** function which will return an array of table data and then user the JS [Filter Function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) on that array to determine if anything exists that matches your data.

I hope that helps,

Cheers

Oli :)

**Comment by mindcreations** [comment]
Thank you for the suggestion, I've used the JS [Find function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) instead of Filter Function because I needed only to find duplicates, so if I found one, I can stop searching.

**Comment by olifolkerd** [comment]
Hey @mindcreations 

Version 4.1 launched today with the new ***searchRows*** and ***searchData*** functions:

```js
var rows = table.searchRows("age", ">", 12);//get row components for all rows with an age greater than 12
var data = table.searchData("age", ">", 12);//get row data for all rows with an age greater than 12
```

Thanks for your input,

Cheers

Oli :)
