### ISSUE TITLE
setSort issue

### ISSUE THREAD

**Issue by marmo79** [olifolkerd/tabulator#1462]
Hello,
i'm using the new 4.0 version of tabulator
If i try to use setSort function, my number column doesn't work properly: the row with a value of 1000 (for example) is the smaller value after 0 (but before 170, in my example)

All works perfectly if i don't use setSort function

.

**Comment by olifolkerd** [comment]
Hey @marmo79 

Thanks for getting in touch, if you are having issues can you please make sure you use one of the issue templates as they will prompt you to enter the information we need to answer your question.

It is quite hard to tell from your description how your table is setup an so what the issue might be, ideally we would need to see a copy of your table constructor object and an example of your ue of the setSort function.

Have you made sure you have defined a sorter on that column?
```js
{title:"Age", field:"age", sorter:"number"}
```
Checkout the [Sorter Documentation](http://tabulator.info/docs/4.0/sort) for more info.

Cheers

Oli?

**Comment by marmo79** [comment]
//Build Tabulator
var table = new Tabulator("#example-table", {
height:"800",
    pagination:"local", //enable local pagination.
    cellEdited:function(data){
   var campo=data.getField();
    var dati=data.getRow().getData();
    var demo=dati[campo];
    
    $.ajax({
           url: "salva.php?id="+dati.id+"&"+campo+"="+demo,
               type: "post",
           success: function(response, textStatus, xhr){
           },
           error: function(XMLHttpRequest, textStatus, error){
             alert("AJAX error: " + textStatus + "; " + error);
           }
         })
    },
    groupBy:"sesso",
       ajaxURL:"json.php",
    columns:[
      {title:"id", field:"id", sorter:"number",width:10},
      {title:"Sex", field:"sesso", sorter:"string", width:40,headerFilter:true,editor:"select", editorParams:{
    "U":"U",
    "D":"D"
},
         headerFilterParams:{
   "U":"U",
    "D":"D",
    "":""
}},
 {title:"Tab", field:"tabellone", sorter:"numeric", width:70,headerFilter:true,editor:"input"},
           {title:"Forza", field:"forza", sorter:"numeric",headerFilterFunc:"=", width:50,headerFilter:true},
        {title:"cognome", field:"cognome1", sorter:"string", width:110,editor:"input", headerFilter:true},
         {title:"nome", field:"nome1", sorter:"string", width:110,headerFilter:true,editor:"input"},
          {title:"class", field:"classifica1", sorter:"string", width:50,headerFilter:true,editor:"input"},
       {title:"cognome", field:"cognome2", sorter:"string", width:110,editor:"input", headerFilter:true},
         {title:"nome", field:"nome2", sorter:"string", width:110,headerFilter:true,editor:"input"},
          {title:"class", field:"classifica2", sorter:"string", width:50,headerFilter:true,editor:"input"},
             
         
          {title:"Note", field:"desiderata", sorter:"string",width:130,headerFilter:true,editor:"textarea"},
});
table.setSort([
     {column:"forza", dir:"desc"}, 
    {column:"tabellone", dir:"asc"},
   {column:"sesso", dir:"desc"}, 
]);

**Comment by olifolkerd** [comment]
Hey @marmo79 

The setSort Function is probably just working differently that you expect, in your example it is sorting by forza, then taking the result of that and sorting by abellone, then taking the result of that and sorting it by sesso.

so you many want to reverse the order of your sorters.

Cheers

Oli :)
