### ISSUE TITLE
increasing row height with partially collapsed row when calling updateRow()

### ISSUE THREAD

**Issue by rflmk** [olifolkerd/tabulator#1463]
I have a table with layout set to "fitColumns", responsiveLayout set to "collapse", and several columns defined with a fixed width.  Many of the columns use custom formatters.

I've been using the `updateRow` and `updateOrAddRow` functions to update specific cells after the table is rendered (updating custom progress bars, etc). This works fine when the page is full width, but if the page is narrow enough for some of the columns to collapse underneath the row I notice a strange behavior. Subsequent calls to `updateRow` or `updateOrAddRow` add extra space to the row as well as updating the cells with the provided data. Each call adds about 1 line height's worth of vertical space to the row. Looking at the rendered page source it looks like the html `height` property is getting increased.  

This only happens when some of the columns are collapsed in responsive mode, not when all the columns are visible in the row proper.  I've noticed it in Tabulator v3.5 and also the latest 4.0.x release.

**Comment by olifolkerd** [comment]
Hey @rflmk 

Thanks for getting in touch. it is funny you should mention that as i experienced exactly the same issue today.

I have stuck it on my list to fix this weekend, i will release a patch release on sunday with a few small tweaks in.

As a side note if you are rasing an issue for a bug could you use the appropriate issue template, it makes sure that we capture all the details needed to fix a bug.

Thanks for the feedback, i will make sure it is resolved this weekend.

Cheers

Oli :)

**Comment by rflmk** [comment]
Thanks Oli! For now I’m working around it by fetching the cell object and setting the value directly. This has the desired outcome without the resizing issue, just takes a little more work up front.

**Comment by olifolkerd** [comment]
Hey @rflmk 

I have just pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)
