### ISSUE TITLE
New callback - Load rows from vDOM into DOM

### ISSUE THREAD

**Issue by Alarich** [olifolkerd/tabulator#1464]
**Is your feature request related to a problem? Please describe.**
I've added a checkbox on each row with a master checkbox in the column title, a bulk select, as one would call it. But I'm keeping track of the selections outside of Tabulator because it seemed like too much work to tie everything with the Tabulator row selection. 
Here's my problem though, if check all is checked, any new row added when scrolling/loading from ajax should have it's checkbox checked, but there doesn't appear to be any event for the loading of rows into the DOM.
This could be solved by changing the data through dataLoaded/dataLoading (I'm not entirely sure what the difference is). But that only works for when data is loaded and might be too costly on larger tables, as I'd have to parse through all that html.

I'm expecting that utilizing row selection would lead me down the "correct" path, but I fear the same issue with the checkboxes would remain - how to check the checkbox if the row is selected in Tabulator.
(Having a checkbox is required, even if it would only be for the visuals.)

**Describe the solution you'd like**
A new callback for when a row or a set of rows are loaded from vDOM into DOM.
I would prefer a set of rows, but since these callbacks seem relatively similar, maybe it wouldn't be difficult to do both.
It would give the ability to modify the rows visually at the exact time that it is required, without modifying the underlying data, be it html formatted or not.

**Describe alternatives you've considered**
1. dataLoaded/dataLoading - too expensive for my needs
2. rowAdded - does not appear to be handling the addition of rows to the DOM
3. renderComplete (and renderStarted) - This I expected to work, but I guess redraw is not what I thought it to be.
4. pageLoaded - Progressive reload doesn't utilize this. Though maybe it should?
5. setInterval / setTimeout - It works, sure, but it just seems really dirty. I think I'll have to go down this path until I find a better way, as I have a product to deliver.

**Comment by Nyut0n** [comment]
Hi @Alarich 
Cell formatters and row formatters are called when the row is being added to the DOM.

You could just create a cell formatter for your checkbox cell that renders the checkbox depending on the status of your header bulk checkbox.

```javascript
var checkboxFormatter = function() {
  var headerCheckbox = document.getElementByID("header-checkbox-id");
  var checkedString = headerCheckbox.checked ? " checked" : "";
  return "<input class='row-checkbox' type='checkbox'" + checkedString + ">";
};
```
(I didn't test this code. It's just to give you an idea.)
Then with the header checkbox, just toggle all checkboxes of the row-checkbox class.

I hope I didn't misunderstand your issue.

**Comment by Alarich** [comment]
Hey @Nyut0n 

Thanks for the tip!

While it should in theory work, there is an issue that arises:

It might be a bit difficult to understand from a simple description, but what I see happening is that when checking/unchecking the main checkbox, a segment of the rows remains checked or unchecked. 
It appears to go by batches of 20 or so. Incidentally it is just about the amount of rows that are loaded into DOM. 
Though I have to mention, at one point there was a batch of 50, which had the wrong state.
After scrolling far enough and returning, the checkboxes are loaded correctly.

Is it possible that there is a batch already preformatted, but not yet in the DOM? After  that batch everything works.

Anyway, it was a good thought, but seems like the format isn't applied right when the row is moved to DOM, though there may be a separate issue that I can't deduce correctly.

I also attempted to add a function that handles everything in DOM every time the formatter for the bulk checkbox is called, but that seemed to be much worse performance wise than my setTimeout solution.

**Comment by Nyut0n** [comment]
> Is it possible that there is a batch already preformatted, but not yet in the DOM? After that batch everything works.

Hmm, possibly. I don't know, but I'm sure @olifolkerd can answer it.

However, the formatter function has an onRendered callback since the 4.0 release that you can use to trigger the checking/unchecking action on your checkbox after the element has really been added to the DOM. See the docs for details and usage examples.

**Comment by Alarich** [comment]
Yeap, I found it while stalking your profile and found your suggestion to Oli.

It feels faster, but the issue still remains, some elements are not checked/unchecked, and it's always the next batch or batches to be rendered.

This is a common visual, though rarely so small: http://prntscr.com/kzvndi

**Comment by Alarich** [comment]
Maybe there's some cache, I suppose it would seem pretty unreasonable to continually render the elements, but what if someone needs to?
I clearly see that elements that don't exist in DOM are not sent through the onRendered and, I guess by extension, the formatter functions when I finally reach them. Thus their contents aren't updated.

I should try to dig through the source code instead of coming up with crazy ideas, but the task seems daunting.

Hopefully Oli is out there and knows the answer :)

**Comment by olifolkerd** [comment]
Hey @Alarich 

The formatters are only called when the elements change, that is either when they are first scrolled into view, or after any data in the row is updated.

To achieve what you are after i suggest binding that column to a field in your row data, that gets updated when the selection is changed, that way your select boxes will stay in sync.

I hope that helps,

Cheers

Oli :)
