### ISSUE TITLE
responsiveCollapse with show/hide not working

### ISSUE THREAD

**Issue by VengefulToaster** [olifolkerd/tabulator#1466]
**Describe the bug**
When you create a responsive collapse and include the formatter:
```
{formatter:"responsiveCollapse", headerSort:false}
```
Nothing happens when you click the (-) icon to hide the responsive list.

**Tabulator Info**
Tabulator v4.0

My constructor (But I also saw the problem with the example for Responsive Layout Collapsed List on <http://tabulator.info/examples/4.0>):

```javascript
var table = new Tabulator('#fileInfo', {
        data: rows,
        height:"500px",
        responsiveLayout:"collapse",
        layout : "fitDataFill",
        pagination:"local", 
        paginationSize:5, 
        columns:[
            {formatter:"responsiveCollapse", width:30, minWidth:30, align:"center", resizable:false, headerSort:false},
            {title: 'User',field: 'user',},
            {title: 'Date',field: 'date_run',sorter:'date',},]
});
```

**To Reproduce**
1. Go to '<http://tabulator.info/examples/4.0>'
2. Scroll down to 'Responsive Layout Collapsed List'
3. Click on one of the hide/show elements to hide/show the collapsed list.
4. See error - Nothing happens and the collapsed list does not hide.

**Expected behavior**
I expect the collapsed list to be hidden/shown accordingly and the icon to change to match. I do see this behavior if I check the example for Tabulator v3.5.

**Desktop (please complete the following information):**
 - OS: Win 10 x64
 - Browser: Tested both in Chrome 69 and FF 52

**Additional context**
Not sure if this is a legit fix but it at least lets me do what I need.
I compared behavior from the v3.5 and noticed the DOM elements weren't changing in v4.0. Dug a little bit into the JS for 4.0 and found the following things I needed to change to get it to work. From what I found the collapse var is returning as undefined.

1. changed line 12797 
```javascript
tabulator.js getElementsByClassName(".tabulator-responsive-collapse")[0]; //Changed to
tabulator.js getElementsByClassName("tabulator-responsive-collapse")[0]; //removed dot
```
This made the collapsed list hide and show correctly but the icon was not changing accordingly.

2. added line 12806
```javascript
el.classList.remove("open"); //Icon now changed properly
```
The total toggleList function now looks like:
```javascript
function toggleList(isOpen) {
	var collapse = cell.getRow().getElement().getElementsByClassName("tabulator-responsive-collapse")[0];
	open = isOpen;

	if (open) {
		el.classList.add("open");
		if (collapse) {
			collapse.style.display = 'block';
		}
	} else {
		el.classList.remove("open");
		if (collapse) {
			collapse.style.display = 'none';
		}
	}
}
```

**Comment by olifolkerd** [comment]
Hey @VengefulToaster 

That is definitely a regression with 4.0 i will include a fix for it in this weekends patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @VengefulToaster 

I have just pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)
