### ISSUE TITLE
pagination error v3.5

### ISSUE THREAD

**Issue by kiran-peddikuppa** [olifolkerd/tabulator#1468]
When columncalc is yes I dont get the page numbers in pagination block

      $("#example").tabulator({
            pagination:"local",
                    paginationSize:30,                
                    layout:layoutPlan,
                    resizableColumns:true,
                    tooltips:true,
                    selectable: true,
                    tooltipsHeader:true,
                    groupToggleElement:"header",
                    groupBy : grp_by_field,
                    initialSort : sort_arr,
                    groupClosedShowCalcs:true,
                    columns : columns_arr
                });

![paging](https://user-images.githubusercontent.com/7722043/46248625-54d18f80-c439-11e8-8826-b2fe85e65780.PNG)

**Comment by olifolkerd** [comment]
Hey @kiran-peddikuppa 

This has been resolved in the 4.0 release.

Cheers

Oli :)
