### ISSUE TITLE
headerFilter - Multiple Value

### ISSUE THREAD

**Issue by JamesnxD** [olifolkerd/tabulator#147]
Hi all,

i have a issue with the filters in the column header. I need filters, which accepts multiple value like "value1;value" or something like that.

Is there any way to do this?

**Comment by olifolkerd** [comment]
so you want to use a semi colon seperated list is that correct? i would be happy to put an example up on hear if that is what you are after, it should be simple to achieve.

**Comment by JamesnxD** [comment]
the way how i solve this is not important. The goal is to filter a column on one or more values. 

In the moment i say in the columndefinition "headerfilter:true" then a textbox in the columnheader is shown and now i want to filter on more that one value. If the way is a semi colon seperated list or a dropdown with more choosable values is not important for me.

**Comment by olifolkerd** [comment]
If you want to use a dropdown that is no problem. all you need to do is define a custom editor (in this case im going to use gender as an example):

```js
var genderEditor = function(cell, value){
     //cell - JQuery object for current cell
     //value - the current value for current cell

     //create and style editor
     var editor = $("<select><option value=''></option><option value='male'>male</option><option value='female'>female</option></select>");
     editor.css({
         "padding":"3px",
         "width":"100%",
         "box-sizing":"border-box",
     })

     //Set value of editor to the value of the cell
     .val(value);

     //set focus on the select box when the editor is selected (timeout allows for editor to be added to DOM)
     if(cell.hasClass("tabulator-cell")){
         setTimeout(function(){
             editor.focus();
         },100);
     }


     //when the value has been set, update the cell
     editor.on("change blur", function(e){
         cell.trigger("editval", editor.val());
     });

     //return the editor element
     return editor;
 }
```

Then assign that editor to the header filter for that column:
```js
$("#example-table-filters-header").tabulator({
         columns:[
                  {title:"Name", field:"name", width:150, headerFilter:true},
                  {title:"Progress", field:"progress", headerFilter:genderEditor},
         ],
 });
```

**Comment by JamesnxD** [comment]
Thank you, works fine for me !

**Comment by uinfobrera** [comment]
Hi folks, I call the data from a json. Is it possible to populate select/option from it?
