### ISSUE TITLE
Docs: `colTitleChanged` callback became `columnTitleChanged` in 4.0

### ISSUE THREAD

**Issue by bahoo** [olifolkerd/tabulator#1470]
**Describe the bug**
The documentation at http://tabulator.info/docs/4.0/columns#edit-titles has the old method name and signature for the callback for changing column titles.

**Tabulator Info**
- Which version of Tabulator are you using? 4.0.1
- Post a copy of your construct object if possible so we can see how your table is setup

```
var table = new Tabulator("#tabulator-table", {
                    columns: [ ... ],
                    colTitleChanged:function(value, col, cols){

                        // snipped
                    },
                    data: [ ... ]
                });
```

**To Reproduce**
1. Go to http://tabulator.info/docs/4.0/columns#edit-titles
2. See documentation for `colTitleChanged`
3. Attempt to use, nothing fires

**Expected behavior**
My callback should fire as described in the documentation.

**Desktop (please complete the following information):**
 - OS: mac OS
 - Browser: Chrome
 - Version: 69

**Additional context**
After searching the code I discovered the callback had changed to:

```
columnTitleChanged: function(column){
                        // snipped
                    },
```

**Comment by olifolkerd** [comment]
Hey @bahoo 

Thanks for letting me know, i have now updated the docs

Cheers

Oli :)
