### ISSUE TITLE
Filtering happens at Json level and not at the table level

### ISSUE THREAD

**Issue by kiran-peddikuppa** [olifolkerd/tabulator#1471]
Hi Oli,
A quick question
When Json is provided to Tabulator, the missing keys are are termed as undefined. But when setFilter is used, it happens on the Json but not on the table, which means Json is filtered first and then the Tabulator generates the table with the filtered data.

In this case we cannot filter the undefined values.

I am sorry if this is already answered, but I am curious to find setFilter to work on the table

Thanks

KIRAN

**Comment by olifolkerd** [comment]
Hi @kiran-peddikuppa 

Im not sure what you are asking, but here is how tabulator handles data.

When data is provided to Tabulator in what ever format, be that JSON or array, it is parsed into an array of data.

Each element in that array is converted into a Row Component that contains may functions for row manipulation and the data for the row itself.

You are correct that filtering happens on the data that is set on each row.

If you want to filter out undefined data then you would need to use a custom filter function, in this example i assume you are looking to remove rows where the name field is undefined:

```js
function customFilter(data, filterParams){
    //data - the data for the row being filtered
    //filterParams - params object passed to the filter

    return typeof data.name !== "undefined";
}

table.setFilter(customFilter);
```

I hope that helps,

Cheers

Oli :)
