### ISSUE TITLE
The paste of the clipboard function does not work properly with IE11.

### ISSUE THREAD

**Issue by snowcat7** [olifolkerd/tabulator#1473]
Nothing will work and errors will not occur.
This works correctly with chrome. The copy will work correctly on both IE 11 and chrome.

I checked the operation on the following demo page.
http://tabulator.info/docs/3.5?#clipboard

IE 11.285.17134.0
Chrome 69.0.3497.100

**Comment by olifolkerd** [comment]
Hey @snowcat7 

Unfortunately IE does not seem to allow paste events on non editable div's, this makes it impossible to add the past functionality to the table for IE im afraid.

If you feel you have a way around it im all ears.

Sorry its not better news.

Cheers

Oli :)

**Comment by snowcat7** [comment]
Thank you for your reply.
I like Tabulator better than ag-grid and I use it. However, with ag-grid, even IE11, I can also select a range and copy & paste it. Can you do the same thing?
https://www.ag-grid.com/example.php

**Comment by olifolkerd** [comment]
Hey @snowcat7 

You can select rows for copy and pasting by enabling [Row Selection](http://tabulator.info/docs/4.0/select)

At the moment there is no cell range selection, but this is on the roadmap and should arrive in one of the next couple of releases.

Cheers

Oli :)

**Comment by snowcat7** [comment]
Hi olifolerd,

That's great news!
I really appreciate your cooperation.

**Comment by richard-slabbert94** [comment]
Hi Oli,

Sorry to post on an old thread.

Just want to check whether cell range select is still on the roadmap? As far as I am aware, I think there is only row selection.

Thanks for a great library!
Richard

**Comment by olifolkerd** [comment]
@richard-slabbert94  The 5.0 release which i am currently working on is receiving an overhaul that will allow cell based range selections.

I am hoping to release it towards the end of March.

Cheers

Oli :)

**Comment by richard-slabbert94** [comment]
Thanks Oli, looking forward to the release!  All the best for the
development!

Regards,
Richard
