### ISSUE TITLE
Tabulator 4.0 Target parameter for Link Formatter is not working

### ISSUE THREAD

**Issue by chuckpt** [olifolkerd/tabulator#1474]
I'm upgrading to Tabulator 4.0, but the parameter **Target** for the link formatter is not working due to a typo in the Tabulator code.
`if (formatterParams.t**ra**get) {
	el.setAttribute("target", formatterParams.traget);
}`

Great work,
Carlos Oliveira

**Comment by olifolkerd** [comment]
Hey @chuckpt 

Thanks for letting me know, i have pushed an update for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)
