### ISSUE TITLE
extendModule gives Tabulator.extendModule is not a function

### ISSUE THREAD

**Issue by mindcreations** [olifolkerd/tabulator#1475]
Migrating the code from 3.5 -> 4.0.4 I've encountered a problem extending keybindings actions.

```
Tabulator.extendModule("keybindings", "actions", {
	navNext: () => ... my code ...
});
```
produces this JS error:

> Uncaught TypeError: Tabulator.extendModule is not a function

I still use JQuery to do some stuff on the page but I've converted all jquery invocations related to Tabulator to the new pure js style.

With or without the inclusion of  jquery_wrapper.min.js the error is still there.

I had the same problem extending keybindings:

I've converted:

```
Tabulator.extendExtension("keybindings", "bindings", { scrollToEnd: false });
```

to
```
Tabulator.extendModule("keybindings", "bindings", { scrollToEnd: false });
```
But got the same error, so I've placed it into the Tabulator definition and it works fine:

```
keybindings: {
	scrollToEnd: false,
}
```
Note that all my code resides into a JQuery 

```
$(function() { ... the code ... });
```

Any advice is appreciated!

Thank you.

**Comment by mindcreations** [comment]
By reading at the source code, I tried to call extendModule this way:
```
Tabulator.prototype.extendModule("keybindings", "actions", {
	navNext: () => { ...  my code ...  },
});
```
Now it works... but, is it intended to work this way?

In this case, I think you should update the documentation about usage.

**Comment by olifolkerd** [comment]
Hey @mindcreations 

Sorry there is definitely an error in the documentation there, it should be `Tabulator.prototype.extendModule`

it was missing the ***prototype*** property in the documentation.

I hope that helps,

Cheers

Oli :)

**Comment by Darkseal** [comment]
I've stumbled upon this issue today: even though it's closed, it seems that the docs still need some updates, for example here:

http://tabulator.info/docs/4.0/upgrade#modules

Which is arguably the main doc source for those who are still upgrading from 3x.

I would suggest to fix that asap :)

**Comment by olifolkerd** [comment]
Hey @Darkseal 

Thanks for the headsup, i had updated the modules docs but missed the upgrade guide.

That is now fixed.

Cheers

Oli :)
