### ISSUE TITLE
table in vuejs problem

### ISSUE THREAD

**Issue by dannykhoo** [olifolkerd/tabulator#1479]
i have followed official guide but the result is not correct  , can guide me how to setup tabulator in vuejs?  thanks

`<template>
  <div ref="table"></div>
</template>

<script>
  var Tabulator = require("tabulator-tables");
  // import Tabulator from "tabulator-tables";
  export default {
    data: function () {
      return {
        tabulator: null, //variable to hold your table
        tableData: [{
            id: 1,
            name: "Oli Bob",
            age: "12",
            col: "red",
            dob: ""
          },
          {
            id: 2,
            name: "Mary May",
            age: "1",
            col: "blue",
            dob: "14/05/1982"
          },
          {
            id: 3,
            name: "Christine Lobowski",
            age: "42",
            col: "green",
            dob: "22/05/1982"
          },
          {
            id: 4,
            name: "Brendon Philips",
            age: "125",
            col: "orange",
            dob: "01/08/1980"
          },
          {
            id: 5,
            name: "Margret Marmajuke",
            age: "16",
            col: "yellow",
            dob: "31/01/1999"
          },
        ],
      }
    },
    watch: {
      //update table if data changes
      tableData: {
        handler: function (newData) {
          this.tabulator.replaceData(newData);
        },
        deep: true,
      }
    },

    mounted() {
      //instantiate Tabulator when element is mounted
      this.tabulator = new Tabulator(this.$refs.table, {
        data: this.tableData, //link data to table
        columns: [{
            title: "Name",
            field: "name",
            width: 150
          },
          {
            title: "Age",
            field: "age",
            align: "left",
            formatter: "progress"
          },
          {
            title: "Favourite Color",
            field: "col"
          },
          {
            title: "Date Of Birth",
            field: "dob",
            sorter: "date",
            align: "center"
          },
        ], //define table columns
      });
      console.log(this.tabulator)
    },
  };
</script>`

![image](https://user-images.githubusercontent.com/33983019/46476778-90929d80-c81b-11e8-8600-7a147f4f3a08.png)

**Comment by olifolkerd** [comment]
Hey @dannykhoo 

Looks like there is no CSS there, you need to pull in the `/dist/css/tabulator.min.css` file into your project.

Cheers

Oli :)

**Comment by dannykhoo** [comment]
Yes, its working now,  thanks!
