### ISSUE TITLE
Double click event

### ISSUE THREAD

**Issue by sadscoot** [olifolkerd/tabulator#148]
Hi Oli,

First of all I just want to say that this library is really cool, and would be ideal for some of the projects I am currently working on.
However, I would like to suggest a couple of enhancements. Having a double click option similar to rowClick but using the dblclick event. This would especially be useful when the selectable option is turned on. I am using the table to open the selected entity in a new tab, but would like it to only occur when double clicking.

Look forward to hearing your thoughts.
Kind Regards,
Scott

**Comment by olifolkerd** [comment]
Great idea! i will get it in this weekend!

**Comment by olifolkerd** [comment]
There are now double click events available on both columns and rows:

```js
$("#example-table").tabulator({
    columns:[
        {title:"Gender", field:"gender", onDblClick:function(e, val, cell, row){
                alert("Cell Double Clicked!");
        }},
    ],
    rowDblClick:function(e, id, data, row){
		alert("Row Double Clicked!");
    },
});
```

Full documentation can be found [here](http://olifolkerd.github.io/tabulator/docs/#callbacks)

**Comment by sadscoot** [comment]
Thanks, it works great!
