### ISSUE TITLE
Setting Placeholder for Filter

### ISSUE THREAD

**Issue by tentus** [olifolkerd/tabulator#1482]
In /src/js/modules/filter.js (currently line 189 in version 4.0.4) there's a minor typo that caught my eye: **placeholdder** where it should be **placeholder**. Except, now that I'm looking at the logic, I don't think the `else` statement that it is in is even reachable, since the whole logic is inside an `if(field){` already.

Just figured I'd point it out, thanks for making such a cool library!

**Comment by olifolkerd** [comment]
Hey @tentus 

Thanks for letting me know, i have pushed a fix for this to the master branch and will include it in the next patch release.

Cheers

Oli :)
