### ISSUE TITLE
Next/Prev row

### ISSUE THREAD

**Issue by mindcreations** [olifolkerd/tabulator#1483]
I think it would be useful to have on the RowComponent the next() and prev() functions to obviously get the next and previous row.

For example, it would be useful to easily redefine navUp/navDown keys regarding a selected row for a table with **selectable: 1**.

**Comment by olifolkerd** [comment]
Hey @mindcreations 

I think that is a great idea, i will add it to the roadmap for the next release in a few weeks time.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @mindcreations 

Version 4.1 has been released today with two new row component functions:
```js
var nextRow = row.getNextRow();
```
and
```js
var prevRow = row.getPrevRow();
```

Thanks for your input!

Cheers

Oli :)
