### ISSUE TITLE
Multi select Shift + Click (without drag)

### ISSUE THREAD

**Issue by sadscoot** [olifolkerd/tabulator#149]
Hi Oli,

Selecting multiple rows with the shift + click (drag) doesn't work great in IE. It selects the text inside the table as I drag. See image:
![image](https://cloud.githubusercontent.com/assets/25082606/21896021/b93b992e-d8dc-11e6-90aa-1bb455b045c5.png)

Is there any way around this at all?
One solution could be to have a click to select the first item, then shift + click to select another which then selects all the items between them.

Kind Regards,
Scott

**Comment by olifolkerd** [comment]
ahh that is an easy fix, it is missing a vendor prefix in the css for that, i will fix it this weekend,

Great Spot!

**Comment by olifolkerd** [comment]
Hey,

This should now be fixed across all browsers.

Thanks for letting me know.

Cheers

Oli

**Comment by sadscoot** [comment]
Hi Oli,

Shift multi selecting doesn't seem to be working, it only ever selects one item. Seems to be caused by another issue you fixed at the weekend (#152). When commenting out that code it works fine.
Possibly I'm missing something. Although I can repro it on your selectable rows example.
http://olifolkerd.github.io/tabulator/examples/#selectable

Cheers,
Scott

**Comment by olifolkerd** [comment]
Hi Scott,

Good catch, this should now be resolved.

Cheers

Oli

**Comment by olifolkerd** [comment]
I have just upgraded the row selection features to allow for selection persistence when sorting, filtering and paging data.

More information can be found [here](http://olifolkerd.github.io/tabulator/docs/#selectable)

Cheers

Oli

**Comment by funkindy** [comment]
@olifolkerd text selection can be easily disabled with js+css, but sometimes shift+dragging selection skip rows for no reason, even if doing slow:
![image](https://user-images.githubusercontent.com/17568549/52031531-cda73c00-253e-11e9-8dec-a7b71c9f240b.png)

**Comment by olifolkerd** [comment]
Hey @sadscoot 

Thanks for getting in touch,

Please do not comment on closed tickets, if you feel you have found a bug, please create a new ticket and include the relevant information.

Could you please also create a JS Fiddle or Codepen to demonstrate your issue, it is very hard to diagnose a problem from a picture alone.

Cheers

Oli :)
