### ISSUE TITLE
Styling column group headers

### ISSUE THREAD

**Issue by jgenyuk** [olifolkerd/tabulator#1491]
Hi Oli,

Is there any way to style column group headers  (version 3.5)? Looks like neither csmClass nor tabulator-field is showing up in the header code.

**Comment by olifolkerd** [comment]
Hey @jgenyuk 

column group headers have the ***tabulator-col-group*** clas if you are looking to style them all, if you want to style a specific column header you could look at using the ***aria-title*** attribute as something unique as that will match the title of the column group

I hope that helps,

Cheers

Oli :)
