### ISSUE TITLE
Use scss variable for .tabulator-page.active color 

### ISSUE THREAD

**Issue by tentus** [olifolkerd/tabulator#1493]
**Is your feature request related to a problem? Please describe.**
In the scss for the simple theme, there is no `$primary` color var, instead some elements like `.tabulator-page.active` are hardcoded to values like `#d00`.

**Describe the solution you'd like**
The easiest solution would be to add a `$footerActiveColor` var and use it in that particular style. 

**Describe alternatives you've considered**
A more complete solution would be to refactor the simple theme to have a base color like the modern theme, but that's probably overkill at this point in time.

**Additional context**
I'm of course able to work around this by overriding the fully-qualified style after the fact, but this is inelegant and brittle against future changes.

**Comment by olifolkerd** [comment]
version 4.1 has just been released and includes the new variable in all themes
