### ISSUE TITLE
Moving Rows Between Tables not working

### ISSUE THREAD

**Issue by rkarlberg** [olifolkerd/tabulator#1496]
In Tabulator 3.5, I was able to move rows back and forth between 2 tables.  In 4.0, that is no longer possible - I can only move from table A to Table B.

I'm using the CDN version of Tabulator 4.0.4.

**To Reproduce**
Try moving a row from the second table to the first.  I have adapted the example given in the documentation below.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome

 `    <link href="https://unpkg.com/tabulator-tables@4.0.4/dist/css/tabulator.min.css" rel="stylesheet">
    <script type="text/javascript" src="https://unpkg.com/tabulator-tables@4.0.4/dist/js/tabulator.min.js"></script>

    <div id="example-table-sender"></div>
    <div id="example-table-receiver"></div>

    <script>
        var tabledata = [
            {name:"Oli Bob"},
            {name:"Brendon Philips "},
            {name:"Margret Marmajuke "},
            {name:"Frank Harbours "},
            {name:"Jamie Newhart "},
            {name:"Gemma Jane "},
            {name:"Emily Sykes "},
            {name:"James Newman "}
        ];

        //Table to move rows from
        var table = new Tabulator("#example-table-sender", {
            height: 311,
            layout: "fitColumns",
            movableRows: true,
            movableRowsConnectedTables: "#example-table-receiver",
            movableRowsReceiver: "add",
            movableRowsSender: "delete",
            placeholder: "All Rows Moved",
            data: tabledata,
            columns: [{
                title: "Name",
                field: "name"
            }, ],
        });

        //Table to move rows to
        var table = new Tabulator("#example-table-receiver", {
            height: 311,
            layout: "fitColumns",
            movableRows: true,
            movableRowsConnectedTables: "#example-table-sender",
            movableRowsReceiver: "add",
            movableRowsSender: "delete",
            placeholder: "Drag Rows Here",
            data: [],
            columns: [{
                title: "Name",
                field: "name"
            }, ],
        });
    </script>`

Errors:

tabulator.min.js:7 Uncaught TypeError: t.getElement.addEventListener is not a function
    at tabulator.min.js:7
    at Array.forEach (<anonymous>)
    at S.connect (tabulator.min.js:7)
    at S.commsReceived (tabulator.min.js:8)
    at p.receive (tabulator.min.js:4)
    at t.c.tableComms (tabulator.min.js:4)
    at tabulator.min.js:4
    at Array.forEach (<anonymous>)
    at p.send (tabulator.min.js:4)
    at S.connectToTables (tabulator.min.js:7)

tabulator.min.js:7 Move Row Error - Table cannot accept connection, already connected to table: <div id=​"example-table-receiver" class=​"tabulator tabulator-movingrow-receiving tabulator-block-select tabulator-movingrow-sending"

tabulator.min.js:8 Uncaught TypeError: Failed to execute 'removeEventListener' on 'EventTarget': The callback provided as parameter 2 is not an object.
    at S.disconnect (tabulator.min.js:8)
    at S.commsReceived (tabulator.min.js:8)
    at p.receive (tabulator.min.js:4)
    at t.c.tableComms (tabulator.min.js:4)
    at tabulator.min.js:4
    at Array.forEach (<anonymous>)
    at p.send (tabulator.min.js:4)
    at S.disconnectFromTables (tabulator.min.js:7)
    at S.endMove (tabulator.min.js:7)

**Comment by olifolkerd** [comment]
Hey @rkarlberg 

Thanks for the headsup, that is definitely a bug, i have just pushed a fix for it to the master branch and will include it in this evenings patch update.

Cheers

Oli :)

**Comment by rkarlberg** [comment]
Thanks Oli!  So far, that is the only bug I found, and I have been using Tabulator 4.0 extensively.  It's really an amazing product.

**Comment by rkarlberg** [comment]
Ok, I updated my CDN from 4.0.4 to 4.0.5 and it works now - I can verify the bug is fixed.  I also signed up on Patreon to support this amazing product.  So far, it has all the features I could ask for.  Thanks again.

**Comment by olifolkerd** [comment]
Hey @rkarlberg 

Great to hear that is working for you, and Thanks for becoming a Patreon!

Cheers

Oli :)

**Comment by schmidty1913** [comment]
@olifolkerd I think this issue is happening again in version 4.5.3 and 4.6.0

I can only move 1 direction not bi-directional
