### ISSUE TITLE
Typing error in ColumnComponent.prototype.scrollTo

### ISSUE THREAD

**Issue by sbuethe** [olifolkerd/tabulator#1497]
Hi Oli,
I found a typing error in declaration of "ColumnComponent.prototype.scrollTo"

"columManager" is referenced but it should be "columnManager" instead (line 1025 in tabulator.js - 1599 commits)

I am using version 4.04 (1599 commits).

Congrats for 4.0 release and many thanks again for your hard work!

Sven

**Comment by olifolkerd** [comment]
Hey @sbuethe 

Thanks for letting me know, i have pushed a fix for this to the master branch and will include it in this weekends patch release.

Cheers

Oli :)
