### ISSUE TITLE
cell.getElement.addClass in 4.0

### ISSUE THREAD

**Issue by mrslayer01** [olifolkerd/tabulator#1499]
I have been looking everywhere and I can't find the replacement to adding a class to my cell via the formatter. 

Here is what i'me trying to do and it is giving me errors.

`cell.getElement().addClass("table-warning");`

Can anyone please point me in the right direction?

**Comment by olifolkerd** [comment]
Hey @mrslayer01 

This is because Tabulator 4.0 no longer use jQuery, so ***getElement*** is no returning a DOM node instead of a jQuery element.

For DOM nodes you need to use 'classList.add' instead.

```js
cell.getElement().classList.add("table-warning");
```

I hope that helps,

Cheers

Oli :)
