### ISSUE TITLE
deleteRow does not refresh Grouping

### ISSUE THREAD

**Issue by vshankaa** [olifolkerd/tabulator#15]
I am not sure if it's intended to do this, however `.tabulator("deleteRow",` id)` does not refresh the grouping. 

- The Item number remains the same (Example: If there were 2 rows before deletion, it still shows **(2 item)** after deleting one of the rows.

- If there is only one row under a group then after deleting, the grouping drop down (grey bar group name and item number) with remains with no rows under it. Ideally it should disappear.

**Comment by olifolkerd** [comment]
I will have a look into that this evening for you.

**Comment by olifolkerd** [comment]
Fix uploaded now. group headers will now update on row deletion and groups will be removed when no rows are left.

Cheers

Oli

**Comment by vshankaa** [comment]
Works perfectly, thanks!
