### ISSUE TITLE
Get row number when a cell in a particular column is clicked.

### ISSUE THREAD

**Issue by jbasemvd** [olifolkerd/tabulator#150]
The last column of my data table is a tickcross. I would like to get the row number when that tickcross is clicked in any row. Is that possible?

**Comment by olifolkerd** [comment]
Hey,

That is no problem at all, you can use the ***onClick*** callback on that column to access any of the row data:
```js
$("#example-table").tabulator({
    columns:[
        {title:"Name", field:"name", sorter:"string", width:150},
        {title:"Gender", field:"gender", width:100, sorter:"string", onClick:function(e, cell, val, data){
            //the data arfument contains the data object for the row, so you can access any information in this object including its index.
        }},
    ],
});
```
If you wanted to get the physical position of the row in the table then you could use the same definition as above, but check the previous number of rows in the table before the current row:
```js
$("#example-table").tabulator({
    columns:[
        {title:"Name", field:"name", sorter:"string", width:150},
        {title:"Gender", field:"gender", width:100, sorter:"string", onClick:function(e, cell, val, data){
            var position = row.prevAll(".tabulator-row").length; //get current positions in table
        }},
    ],
});
```

Let me know if that answers your question

Cheers

Oli

**Comment by olifolkerd** [comment]
Did this solution help you out at all? or  you need any further help?
