### ISSUE TITLE
tickCross in IE11 with 4.0

### ISSUE THREAD

**Issue by NHSDevGuy** [olifolkerd/tabulator#1500]
Hi all,

I have to use IE11 here (as I think I've said before, it's an NHS standard). I've just made the switch to v4 so I don;t know if this happens in 3.5, or indeed if I've messed something up.

adding a tickCross formatter increases the height of each row to a massive extent.

Using v4.0.4:

$(document).ready(function () {
    var viewHeight = $("main").height() - 100;
    $("body").unblock();

    $.ajax({
        url:"/Lookup/GetReviews",
        dataType:'json',
        cache:false,
        async:false,
        success: function (json) {
            try {
                var table = new Tabulator("#iccTable", {
                    layout: "fitColumns",
                    history: false,
                    initialSort: [{ column: "AuthoredDtm", dir: "desc" }],
                    height: viewHeight,
                    columnVertAlign: "bottom",
                    selectable: 1,
                    columns: [
                        { title: "ICC_ID", field: "ICC_ID", visible: false },
                        { title: "MPI", field: "IDCode", headerFilter: "input", sorter: "number" },
                        { title: "Visit #", field: "VisitIDCode", sorter: "number" },
                        //{
                        //    title: "Patient Name",
                        //    columns: [
                        //        { title: "First", field: "FirstName", sorter: "string" },
                        //        { title: "Last", field: "LastName", sorter: "string" },
                        //    ],
                        //},
                        { title: "Date of Birth", field: "DoB", sorter: "date", align: "center" },
                        { title: "Gender", field: "GenderCode", sorter: "string" },
                        { title: "Race", field: "RaceCode", sorter: "string" },
                        { title: "Admitted", field: "AdmitDtm", sorter: "date", align: "center" },
                        {
                            title: "Authored",
                            columns: [
                                { title: "On", field: "AuthoredDtm", sorter: "date", align: "center" },
                                //{ title: "By", field: "CreatedBy", sorter: "string" },
                            ],
                        },

                        {
                            title: "Reviewed",
                            columns: [
                                { title: "Y/N", field: "InICC", sorter: "boolean", align: "center", formatter:"tickCross" },
                                { title: "On", field: "ReviewCreatedOn", sorter: "date", align: "center" },
                                //{ title: "By", field: "ReviewCreatedBy", sorter: "string" },
                            ],
                        },
                    ],
                    rowDblClick: function (e, row) {
                        showForm(row.getData());
                    },
                    rowContext: function (e, row) {
                        e.preventDefault(); // prevent the browsers default context menu form appearing.
                    },

                });
            }
            catch (e) {
                var x = e.responseText;
                alert(x);
            }

            table.setData(json);
            table.redraw(true);
        },
        error:function (e) {
            var x = e.responseText;
            alert(x);
        }
    });
});

(The commented out columns are due to them containing confidential data - I get the same result with them included)

Chrome v69 with tickCross:
![image](https://user-images.githubusercontent.com/42267843/46856740-2cfe0680-cdff-11e8-967b-014d7547fbe6.png)

IE11 v11.245 with tickCross:
![image](https://user-images.githubusercontent.com/42267843/46856813-5f0f6880-cdff-11e8-9f9e-13073d573951.png)

Chrome v69 without tickCross:
![image](https://user-images.githubusercontent.com/42267843/46856848-76e6ec80-cdff-11e8-86de-40d144bbf33d.png)

IE11 v11.245 without tickCross
![image](https://user-images.githubusercontent.com/42267843/46856917-9a119c00-cdff-11e8-8001-137840e22958.png)

This is running from VS2017 v15.8.7 on Windows 10

**Comment by olifolkerd** [comment]
Hey @NHSDevGuy 

Im afraid i cant replicate your issue at all, it seems to wrok fine this end, are you sure you are running on version 4.0.0 for both the css and the js?

Have you made sure nothing is cached in the browser?

Have you tried running the code on a blank HTML page to see if anything else is interfering with the styling?

Cheers

Oli :)

**Comment by NHSDevGuy** [comment]
Looks like it doesn't like UIKit. I'll won't use tickCross for now and I'l rtace it through when I get some time.

**Comment by olifolkerd** [comment]
Hey @NHSDevGuy 

You can always use a custom formatter that uses the built in UIKit icons, below is an example i have thrown togeather based on their docs (cant guarentee it will work, havnt used UIKit before):

```js
//define formatter
```function tickCrossUIKitFormatter (cell, formatterParams, onRendered){
	var value = cell.getValue(),
	element = cell.getElement(),
	empty = formatterParams.allowEmpty,
	truthy = formatterParams.allowTruthy,
	tick = '<span uk-icon="icon: check"></span>',
	cross = '<span uk-icon="icon: close"></span>';

	if((truthy && value) || (value === true || value === "true" || value === "True" || value === 1 || value === "1")){
		element.setAttribute("aria-checked", true);
		return tick;
	}else{
		if(empty && (value === "null" || value === "" || value === null || typeof value === "undefined")){
			element.setAttribute("aria-checked", "mixed");
			return "";
		}else{
			element.setAttribute("aria-checked", false);
			return cross;
		}

	}
}

//use formatter in column definition
{titile:"Reviewed", field:"reviewed", formatter tickCrossUIKitFormatter},
```

I hope that helps,

Cheers

Oli :)

**Comment by NHSDevGuy** [comment]
Brilliant, thanks Oli - would never have got that. Made one minor change in that I think UIKit icons were only introduced in v3 whereas we're using v2.7.5. Whatever, it didn't display anything so I changed to fontawesome icons:

            tick = '<span><i class="fa fa-check" style="color:green;"></i></span>',
            cross = '<span><i class="fa fa-times" style="color:red;"></i></span>';

Works like a dream.
