### ISSUE TITLE
extending css

### ISSUE THREAD

**Issue by ugokanain** [olifolkerd/tabulator#1504]
first off, thanks, useful tool, and has worked great

Been trying to have a background image on the tables, however tabulator doesn't include this. I could do it either by having a transparent background on the table (my page already has one), or adding a background image (which I did). 

I ended up modifying the css, but is there a file where changes should go. This way they would survive updates. This file would extend or add your own classes.

For instance i ended up adding the css code for a background image to tabulator-row and tabulator-frozen. There probably is a better suited class for this.

**Comment by olifolkerd** [comment]
Hey @ugokanain 

Unless you have forked your own version of tabulator I would recommend against editing any of Tabulators source code.

Instead add your own source code in its own file, make sure you use the same CSS selectors as the tabulator source, as long as your file is included after the tabulator files it will take precedence.

All the available CSS classes are explained in the [Styling Documentation](http://tabulator.info/docs/4.0/style#css)

It is worth noting that rows and cells can have background colours which may cover any image on the background of your table. 

Your best bet would be to apply it to either the ***.tabulator*** class or the ***.tabulator-tableHolder*** class.

I would warn you though that most developers go for a plain background on tables to enhance readability, textured backgrounds can often make it harder to read text that is directly on top of them.

I hope that helps,

Cheers

Oli :)
