### ISSUE TITLE
Documentation React Setup - variable naming Issue

### ISSUE THREAD

**Issue by pl86** [olifolkerd/tabulator#1505]
There is variable named `divRef` but never used
```JavaSript
  divRef = React.createRef();
...
  render(){
    return (<div ref={el => (this.el = el)} />);
  }
```

You should rename `divRef` to `el` or `this.el` to `this.divRef`

Found at Tabulator 4.0 Documentation -> React Setup example: [http://tabulator.info/docs/4.0/frameworks#react](http://tabulator.info/docs/4.0/frameworks#react)

More information how to use Refs in React: [https://reactjs.org/docs/refs-and-the-dom.html](https://reactjs.org/docs/refs-and-the-dom.html)

**Comment by olifolkerd** [comment]
Hey @pl86 

Thanks for letting me know, i have corrected the documentation.

Cheers

Oli :)
