### ISSUE TITLE
Vue Component 

### ISSUE THREAD

**Issue by olifolkerd** [olifolkerd/tabulator#1507]
Hey All,

Now that jQuery is out of the way, users are asking to use Tabulator more and more with different frameworks.

It would be great if we could create a component for each framework to make it even easier for users to integrate Tabulator into their projects.

@ngduc has kindly already created the [react-tabulator](https://github.com/ngduc/react-tabulator) wrapper to create a react component

Sadly Im too busy managing the core library to have the time to build these components as well, so i was wondering if one of the community would be willing to take on the challenge of building a Vue Component for Tabulator.

The wrapper would also get a link to from the [Tabulator Website](http://tabulator.info/docs/4.0/frameworks#vue)

If you are interested the please leave a message here.

Cheers

Oli :)

**Comment by angeliski** [comment]
Hey @olifolkerd  
I can help in that. Do you have suggestions  for that component?

**Comment by olifolkerd** [comment]
Hey @angeliski 

Thankyou for your very kind offer, that would be much appreciated!

To start with a basic component that is dependent on the main Tabulator library that replicates all of Tabulators setup options through to params would be great.

If you were feeling adventurous you could even use emitters on some of the callbacks like ***tableBuilding*** and  ***tableBuilt*** etc.

Ideally available on npm to make it easy for users to install in their system, and that uses Tabulators selection of style sheets.

Once you have your repo setup and build a basic component, if you make me a contributor on your project i would be happy to offer advice and help answer issues that arrise.

How does that sound?

Cheers

Oli :)

**Comment by angeliski** [comment]
Hey @olifolkerd I like that way, sounds good.
I will start soon and update you on progress and I will try release a version soon as possible,

Cheers

**Comment by olifolkerd** [comment]
Hey @angeliski 

Great to see you have started work on the component!

I was wondering how things are going. i'm looking to launch version 4.2 of Tabulator at the end of Jan and would love to be able to publicise the new Vue component if you think you will have version 1.0 ready to go by then!

If you don't think it will be ready thats no problem, i can publicise it at a later date.

Cheers

Oli :)

**Comment by angeliski** [comment]
Hi @olifolkerd 
I started created some simple wrapper. I will try make some progress and give you a report in the last jan week. I believe is possible release a simple version. The current version you can create a table and update data and options inside Vue.

What do you think is priority in a 1.0 version release in Tabulator features?

**Comment by olifolkerd** [comment]
Hey @angeliski 

Sorry for lack of reply ive had a hectic few weeks at work.

im going to be releasing 4.2 tommorow and was wondering if you wanted me to include a link to your Vue component, or would you prefer i hold off for now?

Cheers

Oli :)

**Comment by olifolkerd** [comment]
I have just released version 4., have a look at the new [Data Reactivity](http://tabulator.info/docs/4.2/reactivity) section, you might find it very useful for your component

**Comment by angeliski** [comment]
Really nice @olifolkerd ! I will make some tests using that new feature.
I believe soon we can release some stable version.

**Comment by angeliski** [comment]
Hey @olifolkerd Just yo you know, I put the vue-tabulator in release candidate.
I using in my work, but i think is better a rc before a major version. 
I will create the version 1.0.0 in one week.

Thank you for the support.

**Comment by morficus** [comment]
I would love to test this.
I have quite a few complex use cases with tabulator + Vue at the moment.

I'll try to make the switch this week and let you know how it goes.

**Comment by angeliski** [comment]
Amazing @morficus !
The current component is pretty simple, but the purpose is update that to a better Vue integration.

Your feedback can help me improve a lot in that 
:smiley:

**Comment by angeliski** [comment]
Nice @morficus 
My current use case is simple, but is evolving. You can open a issue in [vue-tabulator](https://github.com/angeliski/vue-tabulator/issues) proposing a api for that `extendModule` operation.
So we can discuss and implement

**Comment by olifolkerd** [comment]
Hey @angeliski 

Great work! it is great to hear it is comming along so well.

Im putting togeather the 4.3 release at the mo, and would love to include some information about your wrapper there. are you ok if i copy a bit of your example code for a demo. i will of course include a link to your site.

Could i also ask that you include a link back to the Tabulator docs on your site to direct people back to all the different Tabulator configuration options?

Cheers

Oli :)

**Comment by angeliski** [comment]
Yes @olifolkerd you can copy, I will update the docs to Tabulator config

**Comment by angeliski** [comment]
Done @olifolkerd 
https://angeliski.github.io/vue-tabulator/guide/#options

**Comment by olifolkerd** [comment]
Hey @angeliski 

Thanks for that, i will include the link in the documentation.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @angeliski 

You will be happy to hear that i will be including a link to the Tabulator Vue component in the website when i release the 4.3 update today

Cheers

Oli :)
