### ISSUE TITLE
Frozen columns

### ISSUE THREAD

**Issue by zozolapino** [olifolkerd/tabulator#151]
would be usefull! :)

Thanks!

**Comment by olifolkerd** [comment]
A few people have requested this, i should be able to get it in in next months update

**Comment by olifolkerd** [comment]
This feature is now available!!!

You can use the ***frozen*** property in a column definition object to freeze a row:
```js
$("#example-table").tabulator({
    [
        {title:"Name", field:"name", frozen:true}, //frozen column on left of table
        {title:"Age", field:"age"},
        {title:"Eye Colour", field:"eyes"},
    ]
});
```

Full documentation can be found [here](http://olifolkerd.github.io/tabulator/docs/#frozen-col)

Let me know if you have any questions.

Cheers

Oli
