### ISSUE TITLE
New Built In Editors

### ISSUE THREAD

**Issue by olifolkerd** [olifolkerd/tabulator#1513]
Hey @ngduc

You mentioned in one of your previous posts that would be willing to contribute some editors to Tabulator. If you are still up for it I have a challenge for you.

There are two editors that are often requested to be built in to Tabulator, and in an ideal world i would like the editors to not be dependent on another library.

### Multi Select Editor
Similar to the current select editor but allowing selection of multiple values from the drop down with the maximum number of editable values to be set in a param. if this is implemented well i may even look to replace the built in select editor with it.

### Autocomplete Editor
Similar to the Auto Complete editor in the [Editors Example](http://tabulator.info/examples/4.0#editable) but not dependant on the jQuery auto complete library. with values being set in params

Let me know if you are up for it? if so i have a few other areas i could do with a hand on if you are interested,

Cheers

Oli :)

**Comment by ngduc** [comment]
@olifolkerd I found this select box in vanilla JS that looks good - https://github.com/Mobius1/Selectr
If it's powerful enough, maybe it can be used for both Multi Select Editor & Autocomplete field.
(also for column filter dropdown)

what do you think?

**Comment by olifolkerd** [comment]
Hey @ngduc 

I was more looking for a simple inbuilt one, ideally i dont want users to have to have to include dependencies to use the inbuilt editors.

It should be a relatively simple task to position a div under the input element when a user starts typing and build a list in it, i have built quite a few auto complete systems in the past, i would be happy to give you some pointers.

As a side note the filter system actually uses the editors for the header filter elements so you only have to do it once.

The idea of having a combined editor that is auto complete / select / multi select, that can be configured by a few options is very appealing, i would be happy to go down that route.

Cheers

Oli :)

**Comment by ngduc** [comment]
I see the need of having no dependencies. Then I think those editors should not be built-in. It's better to create them as custom editors which user can import them separately when needed.

If it's a custom editor, I think I should use Selectr (it's lightweight) (rewriting it from scratch is ok but it will be reinventing the wheel). Let me know if that's ok, I will try with that approach.

**Comment by olifolkerd** [comment]
Hey @ngduc 

I am specifically looking for built in editors with those functions because they are most used by people.

They don't need all the functionality of the other auto comp libraries out there, if they did then that is when i recommend people make their own custom editor with their own autocomp, in fact i already include an example to that effect.

But for basic multi selection and a simple auto complete tool it wouldn't be more than a few hours work to put one together and would see to 90% of users needs with minimal effort and no extra dependency. Ive written loads of them in the past. but i would not be looking for a pull request that features an external library for such a simple part of the system

No problem if you dont fancy that, just thought i would throw it your way as you had expressed an interest in making some editors. if you dont fancy it i will happily do them myself when i do the rest of the 4.1 release this weekend.

Cheers,

Oli :)

**Comment by olifolkerd** [comment]
To give you a better idea of the simple level of functionality im look for, for the multi select editor it would have a signature similar to this:
```js
{title:"Name", field:"name", editor:"multiselect", editorParams:{
    selectable:2,
    values:{
        "steve":"Steve Boberson",
        "bob":"Bob Jimmerson",
        "jim":"Jim Stevenson",
    }
}}
```

where the ***selectable*** param is the number of list items selectable, and the ***values*** param is the list of possible values, following the same format as the select editor.

and with the autocomp editor, the values would either be a list like the select editor, where a like comparision is used between the title and the value entered in the input element
```js
{title:"Name", field:"name", editor:"autocomp", editorParams:{
    values:{
        "steve":"Steve Boberson",
        "bob":"Bob Jimmerson",
        "jim":"Jim Stevenson",
    }
}}
```

or a function that returns the array of values.

```js
{title:"Name", field:"name", editor:"autocomp", editorParams:{
    values:function(){}
}}
```

for both they could then be displayed in a list under the input.

This is why i would suggest they could all be the same thing, because if you had an autocomp boolean as one of the options and just put it all under select editor then you could either make the list appear as the user types for an autcomp, or the moment the trigger the editor for a select.

Nothing special needed, simple text values. anything else and users can use a custom formatter with a proper autocomp tool

**Comment by ngduc** [comment]
@olifolkerd Thanks for explaining.
It makes sense. I'll try and open a pr.
