### ISSUE TITLE
Calculated top column gets same value in each cell

### ISSUE THREAD

**Issue by farlane75** [olifolkerd/tabulator#1514]
I'm trying to create a calculated cell with a custom function on all but two of my table columns. For some reason all calculated cells get the same value (the last one calculated it seems )

I use a custom formatter to get the correct values for those columns

NB
What an incredible piece of software you made, my compliments!

**Tabulator Info**
4.0.5

**To Reproduce**
Create some HTML:
```html
<link href="https://unpkg.com/tabulator-tables@4.0.5/dist/css/tabulator.min.css" rel="stylesheet">
<script type="text/javascript" src="https://unpkg.com/tabulator-tables@4.0.5/dist/js/tabulator.min.js"></script>
```
<div id="data-table-group">
</div>

And some JS:
```javascript
function formatValue(cell, params) {
  let demand = cell.getValue()[params.index];

  return demand + "%";
};

function averageAllocation(values, data, calcParams) {

  let sum = 0;

  if (data.length > 0) {

    for (let i = 0; i < data.length; ++i) {
      sum += values[i][calcParams.index];
    }
    sum /= data.length;
  }
  console.log(sum);

  return Math.round(sum) + "%"
}

var groupTable = new Tabulator("#data-table-group", {
  height: 300,
  layout: "fitData",

  columns: [{
      title: "Employee",
      width: 300,
      field: "name",
      align: "left",
      headerFilter: true
    },
    {
      title: "Group",
      width: 150,
      field: "group",
      align: "left",
      headerFilter: true
    },
    {
      title: "test1",
      field: "weeks",
      formatter: formatValue,
      formatterParams: {
        index: 0
      },
      topCalc: averageAllocation,
      topCalcParams: {
        index: 0
      }
    },
    {
      title: "test2",
      field: "weeks",
      formatter: formatValue,
      formatterParams: {
        index: 1
      },
      topCalc: averageAllocation,
      topCalcParams: {
        index: 1
      }
    }
  ]
});


data = [{
  name: "1",
  group: "",
  weeks: [10, 20]
}, {
  name: "2",
  group: "",
  weeks: [10, 20]
}];

groupTable.setData(data);

```

**Expected behavior**
Only the correct column should be updated.

**Screenshots**
See also https://jsfiddle.net/62cz7qx1/2/

**Desktop**
 - OS: Windows
 - Firefox 62.0.3 (64bits)
- Chrome 69.0.3497.100 (64bits)

**Comment by olifolkerd** [comment]
Hey @farlane75 

Thanks for getting in touch, and thanks for your kind words about Tabulator.

The issues you are having are likely because you have used the same field name on two columns, which can cause the system to get confused. i would recommend using fake field names on your two columns, "week1" and "week2", for example, and then use a [Mutator](http://tabulator.info/docs/4.0/mutators) to assign the value to that column when the table is loaded.

If you need a more specific example let me know, i would be happy to put one together for you.

Cheers

Oli :)

**Comment by farlane75** [comment]
Hey Oli,
Thanks in advance for precious your time.

I think i have it now like you propose, but the (correct) average is not displayed, it is always zero. ( Mind you, the actual averaging is somewhat more complicated so i can't use the built-in "avg" )

```javascript
function weekMutator(value, data, type, params, component) {
  if (!data.weeks)
    return 0;

  return data.weeks[params.index];
}

function formatValue(cell, params) {
  let demand = cell.getValue();

  return demand + "%";
};

function averageAllocation(values, data, calcParams) {

  if (values.length == 0)
    return -1;

  let sum = 0;
  values.forEach(function(e) {
    sum += e;
  });

  return Math.round(sum / values.length);
}

var groupTable = new Tabulator("#data-table-group", {
  height: 300,
  layout: "fitData",

  columns: [{
      title: "Employee",
      width: 300,
      field: "name",
      align: "left",
      headerFilter: true
    },
    {
      title: "Group",
      width: 150,
      field: "group",
      align: "left",
      headerFilter: true
    },
    {
      title: "test1",
      field: "weeks0",
      formatter: formatValue,
      mutatorData: weekMutator,
      mutatorDataParams: {
        index: 0
      },
      topCalc: averageAllocation,
      topCalcFormatter: formatValue
    },
    {
      title: "test2",
      field: "weeks1",
      formatter: formatValue,
      mutatorData: weekMutator,
      mutatorDataParams: {
        index: 1
      },
      topCalc: averageAllocation,
      topCalcFormatter: formatValue
    }
  ]
});


data = [{
  name: "1",
  group: "",
  weeks: [10, 20]
}, {
  name: "2",
  group: "",
  weeks: [10, 20]
}];

groupTable.setData(data);
```

**Comment by olifolkerd** [comment]
Hey @farlane75 

as a first step i would suggest you use a console.log in your ***averageAllocation*** to see what values are being passed in to see what is actually happening with the data.

Let me know how it goes.

Cheers

Oli :)

**Comment by farlane75** [comment]
Hello Oli,
I probably should have left that in, but i checked that before posting :)

I have a feeling it is linked to the fact that in the mutator i have to check if the weeks field is null. If i leave that out i get an TypeError: data.weeks is undefined from within tabulator.js/_display.

I suspect i'm still doing something tabulator doesn't like and then stops its processing the source data.

**Comment by olifolkerd** [comment]
Hey @farlane75 

There is definitely something strange going on there, i will investigate in fore detail this evening and get back to you with a solution.

Cheers

Oli :)

**Comment by farlane75** [comment]
If i can do anything to help you out please say so... :)

**Comment by olifolkerd** [comment]
Hey @farlane75 

Sorry for the delay in getting back to you, things have been a bit manic since the launch of 4.0

So on further investigation i have gotten to the bottom of what is going on here:

Tabulator hijacks the normal row object to build a calculation row, and normaly this works fine without any issue. in this case however the mutators that are applying to your normal row data are also being applied to the calc row data, which is setting the values back to 0 because the other data that the mutators rely on is missing.

I am having a look at how i can prevent the mutators kicking in now.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
I have pushed a fix for this to the master branch and will include it in this evenings patch release.

Thanks for baring with me there.

Cheers

Oli :)

**Comment by farlane75** [comment]
Hi Oli,

Thanks a bunch, will test on my setup asap for confirmation.
