### ISSUE TITLE
Ability to change column title.

### ISSUE THREAD

**Issue by medvedar** [olifolkerd/tabulator#1517]
Hello!
Sorry for question here. Is it possible to change the title of the column? Cells I can change easy. But how to do it with columns title?

Thank you!

**Comment by CaptainCodey** [comment]
Hey @medvedar 

Was just checking my post and saw you had asked this question, thought I'd answer.
If I understand what your saying correctly, to change the title of the column just use `title:"Name"` in the column.

e.g.

```
columns:[ 
  //Define Table Columns
  {title:"ID", field:"id"},
  {title:"Name", field:"name"},
  {title:"Job", field:"job"},
],
```

The Example above would show a table with Column's Named -> **ID**, **Name** and **Job**.

Hope I understood the question if not I'm sure I'll be corrected :p

**Comment by olifolkerd** [comment]
Hey @medvedar 

once the column has been created it cannot be changed, but you can remove the existing column and replace it with another column with an updated definition:

remove existing column:
```js
table.deleteColumn("fieldName");
```
add column:
```js
table.addColumn({title:"Age", field:"age"});
```
More details can be found in the [Column Definition](http://tabulator.info/docs/4.0/columns#replace)

I hope that helps,

Cheers

Oli :)
