### ISSUE TITLE
Validator Functions with parameters not working

### ISSUE THREAD

**Issue by agbianchessi** [olifolkerd/tabulator#1519]
**Describe the bug**
Validator Functions with parameters not working: cell is always marked red (invalid value).

**Tabulator Info**
Tabulator version: 4.0.5

**To Reproduce**
es.
validator:["required", "maxLength:64", "string"]

**Additional context**
changing line 17452 in tabulator.js
from `parts = value.split(":", 1);` to `parts = value.split(":", 2);` solves the problem.

**Comment by ckieffer** [comment]
I can confirm both the issue and the change's impact. I'm using an integer validator with min and max values.

**Comment by olifolkerd** [comment]
Hey @agbianchessi  and @ckieffer 

Thanks for the information, i will be doing a patch release this weekend and will include a fix for this.

Thanks for the feedback

Oli :)

**Comment by olifolkerd** [comment]
I have pushed a fix for this to the 4.1 branch and will include it in the next release.

Thanks for letting me know.

Cheers

Oli :)
