### ISSUE TITLE
Selected row doesn't change

### ISSUE THREAD

**Issue by leonardorame** [olifolkerd/tabulator#152]
Hi Oli, I'm playing with the selectable row attribute, but I must say, I don't like the way it works when I only need one selected row.

When I set "selectable: 1" I would like Tabulator to let me select only one row at a time, but if I click on a different row, then it should be selected and the former de-selected, just like the 1nst example here http://demos.telerik.com/kendo-ui/grid/selection.

Is there a way to get that result?.

**Comment by leonardorame** [comment]
The workaround I found for this is:

        rowSelectionChanged: function(data, rows) {
          if(data.length > 1) 
            $("#tabulator").tabulator("deselectRow", data[0].id);
        }

The "data" array is ordered from older to newer, so deselecting the 1nst element in fact de-selects the previously selected row.

**Comment by olifolkerd** [comment]
Hey,

Thanks for your feedback, i agree with your suggested workflow for row selection. 

I have updated tabulator so that you no longer need the workaround it will now work like this by default.

update documentation can be found [here](http://olifolkerd.github.io/tabulator/docs/#selectable)

Cheers

Oli

**Comment by olifolkerd** [comment]
Hi Cemmons,

I have just upgraded the row selection features to allow for selection persistence when sorting, filtering and paging data.

More information can be found [here](http://olifolkerd.github.io/tabulator/docs/#selectable)

Cheers

Oli

**Comment by olifolkerd** [comment]
I have just upgraded the row selection features to allow for selection persistence when sorting, filtering and paging data.

More information can be found [here](http://olifolkerd.github.io/tabulator/docs/#selectable)

Cheers

Oli
