### ISSUE TITLE
Cell input custom validator not working

### ISSUE THREAD

**Issue by iliass3** [olifolkerd/tabulator#1520]
Hi everybody,

I appreciate the work olifolkerd did to realise such a great work, I discovered Tabulator a week ago, and I'm already in love with it.

I'm trying to use a custom validator to validate user input in one of my columns, I'm following the Tabulator official documentation, I have tried a similar function to the example your are providing but it didn't work.

here is my column definition : 

        var editable_obj = {
          title : editable_col,
          field : editable_col,
          editor : "input",
          validator : function(){
            return false;
          }

could you tell me if there is something wrong about my code ??

thank you in advance

**Comment by olifolkerd** [comment]
Hey @iliass3 


Thanks for your kind words, it is great to hear that Tabulator is appreciated.

The custom validator in your example is always returning ***false*** so validation will always fail.

Cheers

Oli :)

**Comment by iliass3** [comment]
thank you for your quick reply, i think I did not explain my problem very well : 

actually with the same validator definition above, when i edit a cell the edited cell accepts all values even if the function is supposed to always return false.

when I assign my function to a variable, I get a warning message from tabulator that the validator :  undefined is not taken into consideration (the variable is global).

I hope you can help me solve this problem.

thank you

**Comment by iliass3** [comment]
To give you more detail here is the output of my console.log : 

![image](https://user-images.githubusercontent.com/44297364/47283987-cdb1aa80-d5e5-11e8-9d87-570f61918436.png)

The object at index 1 is the editable column the validator field is absent from the object ?? however when i try a built-in validator such as "required" it is displayed as a property of the object
