### ISSUE TITLE
4.0 Docs link issues

### ISSUE THREAD

**Issue by aklaver** [olifolkerd/tabulator#1521]
**Describe the bug**
The row component look up links are not working.

**Tabulator Info**
4.0

**To Reproduce**
1. Go to http://tabulator.info/docs/4.0/update#alter-add
2. Click on http://tabulator.info/docs/4.0/update#component-lookup

**Expected behavior**
Navigate to http://tabulator.info/docs/4.0/components#lookup

**Desktop (please complete the following information):**
 - OS: openSUSE Leap 42.3
 - Browser Firefox
 - Version 60.2.2esr

**Comment by olifolkerd** [comment]
Hey @aklaver 

Thanks for the headsup, i will get that fixed.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
I push a fix for this on the 4.1 branch of the docs and will run the update to the site over the weekend

Thanks again for the heads up.

Cheers

Oli :)
