### ISSUE TITLE
HeaderFilter custom editor - ajax - Tabulator 4.0

### ISSUE THREAD

**Issue by leonardorame** [olifolkerd/tabulator#1527]
Hi Oli, I'm porting an app from Tabulator 3.5 to 4.0 that uses `ajaxFiltering` and a custom filtering function, and found it isn't working as expected, even after replacing the jQuery references.

My new ajaxFilter.js is this:

```javascript 
ajaxFilter = function (cell, onRendered, success, cancel, editorParams){

  //create and style input
  var editor = document.createElement("input");
  editor.setAttribute("type", "text");
  editor.style.paddingLeft = "2px";
  editor.style.paddingRight = "2px";
  editor.style.fontWeight = "normal";
  editor.style.width = "100%";
  editor.style.boxSizing = "border-box";
  editor.style.border = "1px solid gray";
  editor.style.borderRadius = "1px";
  editor.value = cell.getValue();

  //wait till element is added to dom before altering event bindings
  var keyDown = function(e) {
    if(e.keyCode == 13){
      success(editor.value);
    };
  };
  editor.addEventListener("keydown",keyDown);

  //remove extra event bindings added by tabulator
  setTimeout(function(){
        editor.removeEventListener("change", keyDown);
        editor.removeEventListener("type", keyDown);
        editor.removeEventListener("search", keyDown);
        editor.removeEventListener("keyup", keyDown);
    }, 100)
  return editor;
}
```
In 3.5, this filter only triggered the ajax request after pressing <kbd>Enter</kbd>, but now it's triggering after every key press.

**Comment by olifolkerd** [comment]
Hey @leonardorame 

header filters in input elements trigger on change (with a 300 ms delay to give people a chance to finish typing before it sends the request)

Which version of 4.0 are you using,  the initial version had an issue of tirggering the header filter a few too many times, that was fixed in the latest patch release.

Cheers

Oli :)

**Comment by leonardorame** [comment]
@olifolkerd, I'm using 4.0.4.

What I want to do is to trigger the ajax request only after pressing <kbd>Enter</kbd>, not after each key press (not even after the 300ms delay).

Leonardo.

**Comment by olifolkerd** [comment]
Hey @leonardorame  

I would definitely advise moving up to 4.0.5, nothing changes in the api but it does fix a number of 4.0 teething issue.

Im afraid that isnt an option at the moment, and technically it wans't an option on 3.5 either, there was just a bug in the ajax filtering that was preventing it from working properly.

But i do take on board what you are saying so i will add it to the road map for the 4.1 release in a week or two to add a column definition parameter to prevent the keyup and search listeners being added to header filters.

Cheers

Oli :)

**Comment by leonardorame** [comment]
Ok, I'll update to 4.0.5 and wait for the 4.1 release.

Thanks!.

**Comment by olifolkerd** [comment]
Hey @leonardorame 

Version 4.1 has just been released!

The new ***headerFilterLiveFilter*** column definition option will prevent live filtering of data:

```js
{title:"Name", field:"name", headerFilter:"input", headerFilterLiveFilter:false}
```

I hope that does the trick

Cheers

Oli :)
