### ISSUE TITLE
Display Empty Groups + Move Rows into Empty Groups

### ISSUE THREAD

**Issue by dkharton** [olifolkerd/tabulator#1529]
I've been trying to create a table with a set number of groups. Sometimes, though, the groups could be empty (have no rows). As well, I'm planning to be able to drag and drop rows from one group to another, and I'd like to be able to drop them into an empty group as well.

I'd like to be able to display empty groups, and move rows into the empty groups.

I've attempted to hack it together using some hidden rows, but when doing that, I am unable to move the existing rows into the other groups. I have considered trying to break the table into sub-tables instead of using Groups, but everything else about the Groups is perfect for my scenario.

Loving Tabulator so far, and thanks for listening to my request!

**Comment by olifolkerd** [comment]
Hey @dkharton 

Thanks for getting in touch.

At the moment Tabulator does not support empty groups, though i can certinaly see how they would be useful in your scenario. 

i will stick something on the roadmap to see if i can make that a possibility for you.

Cheers

Oli :)

**Comment by dkharton** [comment]
Hi @olifolkerd 

Wow, thank you so much! This will be very useful.

Cheers,

Dan

**Comment by olifolkerd** [comment]
This feature has been pushed into the 4.2 branch and will be released on monday.

Cheers

Oli :)

**Comment by raiamit44** [comment]
Could you please let me know , how we can use "groupValues" at run time after applying "setGroupBy" ? is there any method like setGroupValues() ?

How we can expand/collapse the each row in case of multilevel grouping during run time on any action ?
How we can save the tabulator grid state (grouping/filtering/sorting/selection states) to memory and reuse it on next login ? I have seen persistenceMode, but it's only for sorting/filter ? 

Please let me know, I am stuck on this!

Thanks.
