### ISSUE TITLE
Create an action button with link to edit a row item

### ISSUE THREAD

**Issue by venkatrams** [olifolkerd/tabulator#153]
Hello,

Thanks in advance.
I just started exploring Tabulator and it is very resourceful so far. 
I am looking to create an action button on each row of the table auto generated (probably by mutator or Formatter) to edit the row item by taking the user to an edit form. as I currently see cell click event rather than a custom button/control click event.

Is there an example I missed on your site? 

Please suggest/recommend an approach

**Comment by olifolkerd** [comment]
This should be fairly simple to implement. I will break this down into parts for you to make the explanation simpler

### Triggering Dialog Load
You could do this in a number of ways, in each of these method i wlil assume you have your own ***loadDialog*** function that opens a dialog with the provided row data object, i would suggest the jQuery UI dialog, i have used it many times.

You could use the ***rowClicked*** callback to open the dialog when a user click anywhere on a row:
```js
$("#example-table").tabulator({
    columns:[
        {title:"Name", field:"name", sorter:"string", width:150},
        {title:"Rating", field:"rating", formatter:"star", align:"center", width:100},
        {title:"Favourite Color", field:"col", sorter:"string", sortable:false},
    ],
    rowClick:function(e, id, data, row){
        loadDialog(data);
    },
});
```

Another option would be to use an icon in one of the columns and use the columns ***onClick*** function to load the table when the user clicks on that cell (in this case i am use a fontawesome vector font icon:

```js

//custom formatter definition
var openIcon = function(value, data, cell, row, options){ //plain text value
    return "<i class='fa fa-search'></i>"
};

$("#example-table").tabulator({
    columns:[
        {title:"Name", field:"name", sorter:"string", width:150},
        {title:"Rating", field:"rating", formatter:"star", align:"center", width:100},
        {title:"Favourite Color", field:"col", sorter:"string", sortable:false},
        {title:"" , sortable:false, formatter:openIcon, onClick:function(e, cell, value, data){
                loadDialog(data);
        }},
    ],
});
```

Another option would be to have a button element added in a custom formatter and have the user click that to open the dialog:
```js
//custom formatter definition
var openButton = function(value, data, cell, row, options){ //plain text value
    var button = $("<button>Edit Row</button>");
    
    button.on("click", function(){
        loadDialog(data);
    });

    return button;
};

$("#example-table").tabulator({
    columns:[
        {title:"Name", field:"name", sorter:"string", width:150},
        {title:"Rating", field:"rating", formatter:"star", align:"center", width:100},
        {title:"Favourite Color", field:"col", sorter:"string", sortable:false},
        {title:"" , sortable:false, formatter:openButton},
    ],
});
```

### Updating Table After Edit

When the data has been edited in the dialog, the table can then be updated using the ***updateData*** function. 

You should convert the data in your form back into a object in the same form it was given in the above step and the send it back to Tabulator:
```js
$("#example-table").tabulator("updateData", [data]); 
```

Let me know if this has answered your question.

Cheers

Oli

**Comment by venkatrams** [comment]
Thank you. Will explore all these options.

What I am trying to do is to create a button to take the user to the edit form of the record instead of a dialog.

**Comment by venkatrams** [comment]
And Preferably pass on the item id to the query string variable for the button click event link

like EditForm.aspx?id=20

**Comment by olifolkerd** [comment]
Ahhh, then that is even simpler!

You can use all the same code as above, just replace the line:
```js
loadDialog(data);
```
with the line:
```js
location.href = "EditForm.aspx?id=" + data.id;
```
And you should be all sorted.

Oli

**Comment by venkatrams** [comment]
Hello Oli.

Thank you for your prompt response but the data.id returns undefined and the page refreshes and reloads instead of redirecting to the edit page.

Thanks again

**Comment by olifolkerd** [comment]
The property you need to use depends on the data structure you are passing into tabulator. i was just assuming you used the ***id*** property. you will need to use which ever one is appropriate base on the row object you pass in the data array.

The path you pass in is also down to you to put in, the code i provided only demonstrates how to load a page in the browser and how to assign a property from the table into it.

if you have an example of your row object then i would be happy to tweak the example to fit your data.

**Comment by venkatrams** [comment]
Hello Oli,

Thanks for your response for more clarity here is my code that I am using.

 var editButton = function(value, Dashboard1, cell, row, options){ //plain text value
    var button = $("<button>Edit</button>");
    
    button.on("click", function(){
    alert(Dashboard1.id);
        window.location = "https://collaborate.st.dhs.gov/dev/venkatsdev/Lists/TABTEST/EditForm.aspx?id=" + data.id;
        // location.href = "https://collaborate.st.dhs.gov/dev/venkatsdev/Lists/TABTEST/EditForm.aspx?id=" + data.id;
       // document.location.href = "https://collaborate.st.dhs.gov/dev/venkatsdev/Lists/TABTEST/EditForm.aspx?id=" + data.id,true;
    });

   return button; 
};

 var Dashboard1 = CreateDash(options);
 
  $("#FirstDash").tabulator(
  {
  data:Dashboard1,
  columns:col,
  fitColumns:true,
  movableCols: true,
  paginationSize:5,
  groupby:"Title",
  pagination:"local"});
 });

**Comment by venkatrams** [comment]
Thank you. It worked for me. I ignored case sensitivity.

Thanks a ton and for a great tool

**Comment by ramshadken** [comment]
how to add two more icons in a same column and trigger as separate one ,
example in the case of product table we need an action column for view update delete and may be set status .

**Comment by AlainEdwards** [comment]
@ramshadken I found the best and simplest way to do is to put each button in its' own cell and utilize the cell `onclick` trigger.

I was trying to do the same thing and found it difficult to get the row objects to manipulate the table data; esp. when using a tree structure.

**Comment by erbaafidotama** [comment]
> This should be fairly simple to implement. I will break this down into parts for you to make the explanation simpler
> 
> ### Triggering Dialog Load
> You could do this in a number of ways, in each of these method i wlil assume you have your own _**loadDialog**_ function that opens a dialog with the provided row data object, i would suggest the jQuery UI dialog, i have used it many times.
> 
> You could use the _**rowClicked**_ callback to open the dialog when a user click anywhere on a row:
> 
> ```js
> $("#example-table").tabulator({
>     columns:[
>         {title:"Name", field:"name", sorter:"string", width:150},
>         {title:"Rating", field:"rating", formatter:"star", align:"center", width:100},
>         {title:"Favourite Color", field:"col", sorter:"string", sortable:false},
>     ],
>     rowClick:function(e, id, data, row){
>         loadDialog(data);
>     },
> });
> ```
> 
> Another option would be to use an icon in one of the columns and use the columns _**onClick**_ function to load the table when the user clicks on that cell (in this case i am use a fontawesome vector font icon:
> 
> ```js
> //custom formatter definition
> var openIcon = function(value, data, cell, row, options){ //plain text value
>     return "<i class='fa fa-search'></i>"
> };
> 
> $("#example-table").tabulator({
>     columns:[
>         {title:"Name", field:"name", sorter:"string", width:150},
>         {title:"Rating", field:"rating", formatter:"star", align:"center", width:100},
>         {title:"Favourite Color", field:"col", sorter:"string", sortable:false},
>         {title:"" , sortable:false, formatter:openIcon, onClick:function(e, cell, value, data){
>                 loadDialog(data);
>         }},
>     ],
> });
> ```
> 
> Another option would be to have a button element added in a custom formatter and have the user click that to open the dialog:
> 
> ```js
> //custom formatter definition
> var openButton = function(value, data, cell, row, options){ //plain text value
>     var button = $("<button>Edit Row</button>");
>     
>     button.on("click", function(){
>         loadDialog(data);
>     });
> 
>     return button;
> };
> 
> $("#example-table").tabulator({
>     columns:[
>         {title:"Name", field:"name", sorter:"string", width:150},
>         {title:"Rating", field:"rating", formatter:"star", align:"center", width:100},
>         {title:"Favourite Color", field:"col", sorter:"string", sortable:false},
>         {title:"" , sortable:false, formatter:openButton},
>     ],
> });
> ```
> 
> ### Updating Table After Edit
> When the data has been edited in the dialog, the table can then be updated using the _**updateData**_ function.
> 
> You should convert the data in your form back into a object in the same form it was given in the above step and the send it back to Tabulator:
> 
> ```js
> $("#example-table").tabulator("updateData", [data]); 
> ```
> 
> Let me know if this has answered your question.
> 
> Cheers
> 
> Oli

Helloo. i try to follow this step and i try to put console.log(data) in onClick:function but nothing response. is this bugs or my wrong?
sorry for my bad english. thx

**Comment by mirulboy90z** [comment]
Hello. I have a trouble in making custom formatter button.

How to insert the data for following this example?

![image](https://user-images.githubusercontent.com/76030160/112686915-a8f64700-8eb1-11eb-94ed-ae52d6134b82.png)

![image](https://user-images.githubusercontent.com/76030160/112687051-dcd16c80-8eb1-11eb-83f9-615be0032b2e.png)

Here is the data:
![image](https://user-images.githubusercontent.com/76030160/112687107-ed81e280-8eb1-11eb-884b-705417ea8a0d.png)

Here is the error result:
![image](https://user-images.githubusercontent.com/76030160/112687151-05f1fd00-8eb2-11eb-88b7-50b4d2714e5d.png)

Please help me for this issue

**Comment by xtlc** [comment]
@olifolkerd can you provide some assistance please:

I can get one version of your idea to work, but not the other and I'd like to understand why (I am new to JS)

**works:**
```
let btncallback = function ( e, cell) {
    console.log( cell.getData() );
};

let btn = function( value, data, cell, row, options ) {
    return `<button type="button" class="btn btn-sm btn-secondary">test</button>`;
};

var table = new Tabulator("#example-table", {
        layout: "fitColumns",
        pagination: "local",
        paginationSize: 25,
        paginationSizeSelector: [50, 100],
        ajaxURL: "test/",
        columns: [ {title: "", formatter: btn, cellClick: btncallback}],
});
```


**does not work:**
```
let button = function( value, data, cell, row, options ) {
    let btn = $(`<button type="button" class="btn btn-sm btn-secondary">test</button>`);
    btn.on("click", function( event ) {
        console.log( cell.getData() );
    }); 
    return btn;
};

var table = new Tabulator("#example-table", {
        layout: "fitColumns",
        pagination: "local",
        paginationSize: 25,
        paginationSizeSelector: [50, 100],
        ajaxURL: "test/",
        columns: [ {title: "", formatter: button}],
});
```

I tried both your examples and I would appreciate if you could show me why the second one is not working with tabulator v4.9. thanks!

**Comment by abhijitgujar86** [comment]
@mirulboy90z it late but here is one option . 
use  value instead of data like this  
`
value.getData() 

`

It returns object of clicked row
