### ISSUE TITLE
After header filtering grid is scrolled to first column

### ISSUE THREAD

**Issue by leonardorame** [olifolkerd/tabulator#1531]
When a grid with header filters has many columns and a fixed width, after scrolling the grid to display a far right column then filtering, the grid scrolls to the first column **WHEN THERE'S NO RESULTS**.

As an example, the next image shows a grid with many columns, scrolled to the right to let the user see the column "Agendado":

![image](https://user-images.githubusercontent.com/1405017/47565256-4a05ff80-d8fe-11e8-837b-b8a95cce5231.png)

Then, after typing a date into the "Agendado" -> "Fecha" filter, the grid is filtered and scrolled to the left most column, if the result dataset is empty:

![image](https://user-images.githubusercontent.com/1405017/47565463-e4664300-d8fe-11e8-8925-00068f1d5cbb.png)

I think the grid shouldn't scroll after filtering.

**Comment by olifolkerd** [comment]
Hey @leonardorame 

If you are reporting a bug please can you use the bug template as it prompts with the questions i most need answers to to be able to help out.

Can i ask which version of Tabulator you are using and on what browser?

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Could you post a copy of your table constructor so i can try and replicate the issue.

Cheers

Oli :)
