### ISSUE TITLE
Image formatter escaping /

### ISSUE THREAD

**Issue by tentus** [olifolkerd/tabulator#1532]
**Describe the bug**
When using `formatter: "image"` the url cannot contain the / character, or the src will be malformed.

**Tabulator Info**
- 4.0.5

**To Reproduce**
```
    <div id="example-table"></div>
    <script>
      var table = new Tabulator("#example-table", {
        columns: [
          {field: "id"},
          {
            field: "src",
            formatter: "image"
          }
        ]
      });
      table.setData([
        {id:1, src:'https://via.placeholder.com/150x30'},
        {id:2, src:'https://via.placeholder.com/150x30'},
      ])
    </script>
```

**Expected behavior**
Image src should not have `sanitizeHTML` called on it in `Format.formatters.image`

**Comment by olifolkerd** [comment]
Hey @tentus 

There is already a patch for this on the 4.1 branch, which i am hoping to get released in the next week.

Thanks for letting me know.

Cheers

Oli :)
