### ISSUE TITLE
Layout mode that allows "fit to data" and "forced width"

### ISSUE THREAD

**Issue by c-dante** [olifolkerd/tabulator#1533]
I have a table with 4 grouped columns, each with 41 columns inside (total 164 columns).

The "fitData" layout mode takes ~6s to render the table (virtual dom is on)
The "fitColumns" layout mode takes ~.5s, but is not ideal for the use case as I cannot fit data on ~4 of the columns (headers) and then use fixed-width for the remaining 37 (data).

Looking at the layout module, there is no layout mode to do this. Ideally, I'd like something that's "fitToData" on the column, and a "fixedWidth" on the remaining cells. This would be a best-of-both-worlds for very wide tables.

For now, my workaround is going to be use "fitColumns", each data column having the properties below, then manually re-size my "fit data" columns (first 4).

**Tabulator Info**
- Which version of Tabulator are you using?
4.0

- Post a copy of your construct object if possible so we can see how your table is setup
```js
{
	layout: 'fitColumns', // fitData takes 6s
}
```

And for my columns (omitting field/title):
```js
{ // forces size in fitColumns
	width: 150,
	minWidth: 150,
	widthShrink: 0,
	widthGrow: 0,
}
```

**Comment by olifolkerd** [comment]
Hey @c-dante 

Thanks for getting in touch, rendering tables with a large number of columns is already a know issue, This is because the virtual DOM currently only works on the row scrolling not the column scrolling.

issue #1437 has been setup to track progress on this issue. i hope to get an update out to fix this around xmas time.

Thanks for the feedback

Oli :)

**Comment by c-dante** [comment]
@olifolkerd just to post my workaround for now -- I set my table to be `fitColumns`, and then for my data column defs, I have `minWidth: 100` (or some constant), for the non-data columns, I have `minWidth: 75` (Ideally, I'd like this to fit the data OR the title, whichever is larger).

Then, after I render the data, I manually run:
```js
headerFields.forEach(field => {
	const column = this.table.getColumn(field);
	if (column._column) {
		column._column.reinitializeWidth();
	}
});
```
on the non-data columns. This gives me a fairly-fast render.

The use case is a set of frozen "header columns", and then a large number of scrollable "data columns"
