### ISSUE TITLE
Date Sorter

### ISSUE THREAD

**Issue by pup71** [olifolkerd/tabulator#1538]
I have a Grid setup but the date sorter is not working as expected.

 var tableasales = new Tabulator("#gvAdvisorSales", {
                   
                        ajaxURL: aUrl, 
                        selectable: false,
                        ajaxParams: { dealercontactid: DealerContactID },
                        ajaxConfig: "GET", 
                        virtualDom: false,
                        height: "100%",
                        layout: "fitColumns",
                        layoutColumnsOnNewData: true,
                        layout: "fitColumns",
                        paginationSize: 16,
                        placeholder:"No Sales Data Available", 
                        pagination: "local", 
                        columns: [
                        {title:"Investor", field:"Investor", visible:true},
                        {title:"Amount", field: "Amount", visible: true, formatter:"money"},
                        { title: "Date Received", field: "DateReceived", visible: true, align: "center", sorter: "date", },
                        { title: "Date Invested", field: "DateInvested", visible: true, align: "center", sorter: "date", }
                        ],
                    });

DateReceived and DateInvested are in formated mm/dd/yyyy from database.

Sample of sorting
![image](https://user-images.githubusercontent.com/43763974/47619970-d6f5b800-daba-11e8-832e-e43e4699f34d.png)

Thanks Bill.

**Comment by olifolkerd** [comment]
Hey @pup71 

That is because you need to tell Tabulator what format the date is in so it knows how to format it,

To do this you need to set the ***format*** property in the column definitions ***sorterParams***:
```js
{ title: "Date Received", field: "DateReceived", visible: true, align: "center", sorter: "date",  sorterParams:{
    format:"MM/DD/YYYY",
}},
```

I hope that helps,

Cheers

Oli :)

**Comment by pup71** [comment]
Will do next time? That worked.
