### ISSUE TITLE
Filter Data

### ISSUE THREAD

**Issue by kurtknippschild** [olifolkerd/tabulator#154]
Hi Oli,

I have a question. 
Is there a chance to select the filter value from the list of values in the table?

Thank you in advance.

MG Kurt

**Comment by olifolkerd** [comment]
So just to check i understand what you are looking for.

after data has been loaded into the table you want to have a select element as a header filter that contains an option for each type of value in that column?

let me know if that is correct, if so i can put together a quick solution together for you in no time.

Cheers

Oli

**Comment by kurtknippschild** [comment]
Hi Oli,

thanks for your quick response.

On the Example on http://olifolkerd.github.io/tabulator/examples/#filter
can you extend this example for the Gender und Favourit Color.
So that when  in the Filter Parameters the Field Gender or Favorit Color is selected the Value is a Combobox with the Data from the table.

Thank you in advance.

MG Kurt

**Comment by olifolkerd** [comment]
Hey,

There is a simple solution to that one, i will post it on here when i finish work today.

Cheers

Oli

**Comment by olifolkerd** [comment]
We can use the code from the filter example you included to make the filter you need.

We can use the ***dataLoaded*** callback to populate a select element, that can then trigger the filter when it detects a change in value:

#### HTML
```html
<select id="gender-filter"></select>
```

#### JS
```js
//trigger filter on selection
$("#gender-filter").on("change", function(){
    $("#example-table").tabulator("setFilter", "gender", "=", $(this).val());
});

//Build Tabulator
$("#example-table").tabulator({
    height:"311px",
    fitColumns:true,
    columns:[
        {title:"Name", field:"name", width:200},
        {title:"Progress", field:"progress", formatter:"progress", sorter:"number"},
        {title:"Gender", field:"gender"},
        {title:"Rating", field:"rating", formatter:"star", align:"center", width:100},
        {title:"Favourite Color", field:"col"},
        {title:"Date Of Birth", field:"dob", align:"center", sorter:"date"},
        {title:"Driver", field:"car", align:"center", formatter:"tickCross"},
    ],
    dataLoaded:function(data){
        //data - all data loaded into the table
        
        var options = []; //hold list of unique options

       //create list of unique options
        data.forEach(function(item){
            var value = item.gender;

            if(options.indexOf(value) == -1){
                options.push(value);
            }
        });

       //clear any old options
        var select = $("#gender-filter");
        select.empty();

       //load list of options into select box
        options.forEach(function(option){
            select.append("<option value='" + option + "'>" + option + "</option>");
        });
    },
});
```

Let me know if that helps you out.

Cheers

Oli

**Comment by RandomGHUser** [comment]
The example above uses a pre-created #gender-filter element, is there a way to bind these values into a header filter dropdown?

**Comment by olifolkerd** [comment]
Hey @RandomGHUser 

This is an old example, you can now use the built in ***select*** editor to do this in a much more concise way:
```js
{title:"Gender", field:"gender", editor:"select", editorParams:{"male":"Male", "female":"Female"}, headerFilter:true, headerFilterParams:{"male":"Male", "female":"Female"}},
```

You can see it in action on the [Header Filter Exampl](http://tabulator.info/examples/4.0#filter-header) on the website,

I hope that helps,

Cheers

Oli

**Comment by RandomGHUser** [comment]
I am not looking to have any editor parameters on my columns, I'm just looking to generate the headerFilterParams based upon the unique cells in each column.
  
The code you posted above will automatically generate the dropdown list, but needs an element to bind it to, and I can't seem to generate headerFilterParams without also requiring a "select" editor for the column cells, which I do not want.

**Comment by olifolkerd** [comment]
Hey @RandomGHUser 

Ahh in that case that exact scenario has already been covered in issue #1382

You use a combination of a param lookup function, the ***dataLoaded*** callback and the cell component ***reloadHeaderFilter*** function.

Have a look at the previous issue for more information.

Cheers

:)

**Comment by jack2ky** [comment]
How do you add the show all on the "tickCross" column for the select header filter 

`{title:"closed", field:"closed", sorter:"boolean", align:"center", formatter:"tickCross", editor:"select", editorParams:{"true":"Open", "false":"Closed"}, headerFilter:true, headerFilterParams:{"true":"Open", "false":"Closed"}},`

I added the filter for the select element now I want to add the 3rd option to show all opened and closed. Basically, I want to get rid of the filter when the user selects all
