### ISSUE TITLE
JSON data handled badly with progressiveLoading

### ISSUE THREAD

**Issue by remipassmoilesel** [olifolkerd/tabulator#1541]
Hi, 
Thanks, for this great tool.

**Describe the bug**
I try to use tabulator to display a few thousands of elements with custom renderers and progressive
loading. 
Each data row is a complex JSON object with nested arrays (but not so heavy)
All works normally on the first try, but after the second or third data loading, the original data get buggy and seems serialized in a bad way.

For example, with this kind of data: 
```
[
  company:{
    numbers: [1,2,3]  
  }
]
```
And with a very simple formatter like that: 
```
 function(cell: any, formatterParams: any, onRendered: any) {
     return JSON.stringify(cell.getData()["numbers"]);
 }
```

After the first data loading, data cell content looks good:
```
[   company:{     numbers: [1,2,3]     }  ]
```

But if I load data one or two times more, the data just loaded is fine, but the previous data looks like:
```
[   company:{     numbers: {0:1,1:2,3:3}     }  ]
```
(Arrays become objects)

**Tabulator Info**
- Which version of Tabulator are you using?
Taken from: https://unpkg.com/tabulator-tables@4.0.5/dist/js/tabulator.min.js
- Post a copy of your construct object if possible so we can see how your table is setup
```
    Vue.component("custom-data-table", {
        template: '<div ref="table" id="custom-data-table"></div>',
        data: function (): any {
            return {
                tabulator: null,
                dataTableService: null,
            };
        },
        mounted() {
            this.dataTableService = new DataTableService();
            this.dataTableService.getColumnDefinitions().then((columns: IColumnDefinition[]) => {

                this.dataTableService.applyFormatters(columns); // affect formatters depending on columns, nothing fancy
                console.log("Using column definitions: ", columns);

                this.tabulator = new Tabulator(this.$refs.table, {
                    layout: "fitColumns",
                    columns,
                    ajaxURL: this.dataTableService.getApiBasePath(),
                    ajaxProgressiveLoad: "scroll",
                    ajaxProgressiveLoadScrollMargin: 1200,
                    paginationSize: 100
                });

            });
        },
    });

    const app = new Vue({
        el: "#custom-data-table-app"
    });
```

**To Reproduce**
1. Setup a progressive loading table
1. Add a JSON.stringify() formatter or a console.log(JSON.stringify())
1. Scroll down two or three times, then scroll up and see data changes

**Expected behavior**
Data should be consistent, and format should not be changed.
```
[   company:{     numbers: [1,2,3]     }  ] // ok

[   company:{     numbers: {0:1,1:2,3:3}     }  ] // not ok
```

**Desktop (please complete the following information):**
 - OS: Xubuntu 18
 - Browser Vivaldi
 - Latest version

Thanks for your help !

**Comment by olifolkerd** [comment]
Hey @remipassmoilesel 

Thanks for getting in touch, sorry to hear you are having issues.

Could you confirm if this happens if your site is viewed in Chrome or one of the other supported browsers? Tabulator currently does not offer support for Vivaldi so it would need to be confirmed as an issue on a supported browser

Also are your loading any remote fonts, it is possible if you are that the first set of data loaded before the font did causing the spacing to be different.

A screenshot of the different layouts would be really useful to help see what is going on.

Cheers

Oli :)

**Comment by remipassmoilesel** [comment]
Hi @olifolkerd ,
I tested it with Chrome, results are buggy too.

I do not load so much things (no fonts), I think it is not a display issue, as my example show. I think data structure is modified as the JSON.stringify() output show (in DOM or in web console) 

How do you store data ? It seems that stored data rows are not properly stored/restored.

P.S.: I tried it outside of VueJS, results are the same.

**Comment by olifolkerd** [comment]
@remipassmoilesel 

Thanks for the additional information, could you please post a screen shot as it is the easiest way for me to properly understand what is going on with your data.

Data is stored in the original objects that it is passed into tabulator and only changes if the value is explicitly altered if a mutator is used or with an update call on the row or cell edit. formatters take that data and render an output for the screen which is not stored and exists only in the DOM element for that cell so there is no reason it should be any different.

To understand exactly what is going on i would need to see your table constructor including column definitions, and a screenshot of the issue. or ideally a JS Fiddle or a code pen with a working example.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @remipassmoilesel 

I have just run several tests on my computer and i am afraid i am unable to replicate the issue you are facing, the JSON data loads consistently every time.

It is quite hard to diagnose without knowing how your columns are setup, but can i ask why your formatter is using the ***getData*** function on the cell and then loading the data from a field of this, rather than calling the ***getValue*** function on the cell which will return the value for that column, which would be the standard approach?

Cheers

Oli :)

**Comment by remipassmoilesel** [comment]
Hey @olifolkerd , thanks for your interesting response. Tomorrow is a day off, but I will post soon a better sample. Maybe I've done a mistake with methods.

Cheers.

**Comment by remipassmoilesel** [comment]
Hi !
Here are the screenshots and a working sample :)

First loading, array content of the cell looks good:
![selection_007](https://user-images.githubusercontent.com/11815076/47859505-c614b180-ddee-11e8-926f-cade68294749.png)

But after a few loading, data is inconsistent:
![selection_008](https://user-images.githubusercontent.com/11815076/47859545-d62c9100-ddee-11e8-8137-36b2fa3a2154.png)

Here is the complete code, in Typescript:

```

declare const Vue: any;
declare const dataTable: any;
declare const Tabulator: any;

(function() {

    interface IColumnDefinition {
        title: string;
        field: string;
        sorter?: string;
        align?: string;
        visible?: boolean;
        formatter?: any;
    }

    interface IColumnFormatterDefinition {
        tableId: string;
        formatters: {
            field: string;
            formatter: string | Function;
        }[];
    }

    // Here you can define dynamic formatters for tables
    const dynamicTableFormatters: IColumnFormatterDefinition[]  = [
        {
            tableId: "suppliers-table",
            formatters: [
                {
                    field: "cpv",
                    formatter: function(cell: any, formatterParams: any, onRendered: any) {
                        return JSON.stringify(cell.getValue()); // here we stringify the cell data for demonstration
                    }
                }, {
                    field: "marker",
                    formatter: function(cell: any, formatterParams: any, onRendered: any) {
                        return cell.getValue().length;
                    }
                }
            ]
        }
    ];

    class DataTableService {

        public getColumnDefinitions = (): Promise<IColumnDefinition[]> => {
            return new Promise((resolve, reject) => {
               $.get(this.getApiBasePath() + "?columnDefinitions=true")
                    .done(resolve)
                    .fail((err: any) => {
                        this.showFailError(err);
                        reject(err);
                    });
            });
        }

        public applyFormatters(columnDefinitions: IColumnDefinition[]): void {
            const formattersGroup =  _.find(dynamicTableFormatters, form => form.tableId === this.getTableId());
            if (!formattersGroup) {
                console.log("No dynamic formatters found for tableId " + this.getTableId());
                return;
            }
            _.forEach(columnDefinitions, col => {
                const dynamicFormatter = _.find(formattersGroup.formatters, form => {
                    return form.field === col.field;
                });
                if (dynamicFormatter) {
                    col.formatter = dynamicFormatter.formatter;
                }
            });
        }

        public getApiBasePath = () => {
            return dataTable.apiBasePath;
        }

        public getTableId = () => {
            return dataTable.tableId;
        }

        public showFailError = (err: Error) => {
            alert(`Erreur lors du chargement des données: ${err.message}`);
        }
    }

    Vue.component("sln-data-table", {
        template: '<div ref="table" class="sln-data-table"></div>',
        data: function (): any {
            return {
                tabulator: null,
                dataTableService: null,
            };
        },
        mounted() {
            this.dataTableService = new DataTableService();
            this.dataTableService.getColumnDefinitions().then((columns: IColumnDefinition[]) => {

                this.dataTableService.applyFormatters(columns);
                console.log("Using column definitions: ", columns);

                this.tabulator = new Tabulator(this.$refs.table, {
                    layout: "fitColumns",
                    columns,
                    ajaxURL: this.dataTableService.getApiBasePath(),
                    ajaxProgressiveLoad: "scroll",
                    ajaxProgressiveLoadScrollMargin: 500,
                    paginationSize: 300
                });

            });
        },
    });

    const app = new Vue({
        el: "#sln-data-table-app"
    });

})();

```

It looks like a bad Object handling, Arrays seem to have lost their special properties (like length)

**Comment by olifolkerd** [comment]
Hey @remipassmoilesel 

Thanks for the detailed information, it looks like the data is being entered into Tabulator in that JDON column is being stored in objects not arrays, I have already run a number of tests and cannot replicate this issue, nor does Tabulator manipulate the data coming into the table in any way that could result in the issue you are experiencing. (i use json data extensively in tables i build with Tabulator and have never experienced this issue).

Unless you use a mutator Tabulator does not touch the row data in any way, so it is likely that this is the result of data being entered into the table in that format.

As a first port of call i would suggest that you double check the data that is being sent to Tabulator to make sure it is correctly formatted.

Cheers 

Oli

**Comment by olifolkerd** [comment]
Are you getting any errors appearing in the console?

**Comment by olifolkerd** [comment]
Got to the bottom of it!

There was an issue in the data isolation function that deep clones the data when it leave the table to isolate it from the internal data, under a very specific set of circumstances it was not recognising arrays and treating them as objects.

I have included a fix in the 4.1 branch that i will release later this weekend.

Thanks for bearing with me and providing so much information.

Cheers

Oli :)

**Comment by remipassmoilesel** [comment]
Great job ! 

Can I see the commit ?

**Comment by Keyframe** [comment]
I got bit by this as well, in a bit different circumstances (I check for dataEdited): https://github.com/olifolkerd/tabulator/issues/1579
