### ISSUE TITLE
Scroll docs

### ISSUE THREAD

**Issue by aklaver** [olifolkerd/tabulator#1544]
**Describe the bug**
Example for scrollToRow is incorrect.

**Tabulator Info**
Tabulator 4.0

**To Reproduce**
http://tabulator.info/docs/4.0/navigation#scroll-row
The example is:
```
table.scrollToRow("age", "middle", false)
.then(function(){
    //run code after row has been scrolled to
})
.catch(function(error){
    //handle error scrolling to row
});

```
Looks to me like it is a cut and paste from the scrollToColumn.

**Expected behavior**
Pretty sure the above should be something like:

```
table.scrollToRow(23, "middle", false)
.then(function(){
    //run code after row has been scrolled to
})
.catch(function(error){
    //handle error scrolling to row
});

```

**Comment by olifolkerd** [comment]
Hey @aklaver 

Thanks for the headsup, i have fixed it on the 4.1 branch of the docs and will make it public with the 4.1 release this weekend.

Cheers

Oli :)
