### ISSUE TITLE
When i am opening the tabular to IPAD, it is showing error and not opening with the data.

### ISSUE THREAD

**Issue by ciosynergy** [olifolkerd/tabulator#1546]
**Describe the bug**

**Tabulator Info**
- Which version of Tabulator are you using?
- Post a copy of your construct object if possible so we can see how your table is setup

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by olifolkerd** [comment]
Hey @ciosynergy 

You seem to have missed out answering most of the questions in the template that we need answers to in order to help you out.

Please create another issue and fill out the answers to the questions for help.

Cheers

Oli :)
