### ISSUE TITLE
scrollToRow behavior

### ISSUE THREAD

**Issue by aklaver** [olifolkerd/tabulator#1547]
**Describe the bug**
The docs say scrollToRow(id, "top") should:
"top - position row with its top edge at the top of the table (default)"
I am not seeing that.

**Tabulator Info**
Tabulator 4.0.5
```
var order_li_tbl = new Tabulator("#order_liitem_container", {
    ajaxURL:"/order_li_records/list/",
    ajaxParams:{"order_no" : $("#li_order_no").val()},
    ajaxConfig:{
        method:"GET",
        credentials: 'include'
    },
    ajaxResponse: function(url, params, response){
        return response.rs;
    },
    layout: "fitColumns",
    height: "200px",
    index: "line_id",
    addRowPos: "top",
    // pagination: "local",
    // paginationSize: 5,
    columns: [
        {title: "line_id", field: "line_id", visible: true},
        {title: "Order", field: "order_no"},
        {title: "Item #", field: "item_no"},
        {title: "Category", field: "category"},
        {title: "Description", field: "item_desc"},
        {title: "Quantity", field: "quantity"},
        {title: "Note", field: "note"}
    ],
    rowClick: function(e, row){
        var row_data = row.getData();
        $("#li_line_id").val(row_data.line_id);
        $("#li_item_no").val(row_data.item_no);
        $("#category_fld").val(row_data.category);
        $("#item_fld").val(row_data.item_desc);
        $("#quantity").val(row_data.quantity);
        },
    });

```

**To Reproduce**
1. Go to page with table.
2. In console run order_li_tbl.scrollToRow(12289, "top")

**Expected behavior**
That the row with index of 12289 would scroll to top of the table.

**Screenshots**
Before:
![screenshot-2018-10-31 cascade cuts](https://user-images.githubusercontent.com/658260/47796400-81e7bb00-dce1-11e8-884b-f51e078652a3.png)
After:
![screenshot-2018-10-31 cascade cuts 1](https://user-images.githubusercontent.com/658260/47796465-a0e64d00-dce1-11e8-93a2-45d71c96c491.png)

**Desktop (please complete the following information):**
openSUSE Leap 42.3
Firefox
60.3.0esr (64-bit)

**Additional context**
I commented out the pagination code as scrollToRow() failed with:
```uncaught exception: Scroll Error - Row not visible```
when trying to scroll a record on a page other then the first.

**Comment by olifolkerd** [comment]
Hey @aklaver 

Thanks for the screenshots there they were very helpful!

Looking at the screenshot i can see that the row you are trying to scroll to is the last one in table, so there is no room for it to scroll to the top.

Cheers

Oli :)

**Comment by aklaver** [comment]
It does not scroll to the top if it is not the last row either. It seems the docs are wrong specifying 'top' :

"top - position row with its top edge at the top of the table (default)"

does not get the row to the top of the table.  It just brings it into view. Also it does not work with local pagination, which I find odd as all the rows are there.

**Comment by olifolkerd** [comment]
It will only scroll it to the top of the table if there are enough rows under it to allow it to reach the top.

In a paginated view there should be only enough rows to fill the view so there should be no scrollbar so there would not be enough rows for it to reach the top.

**Comment by aklaver** [comment]
I would have thought with VirtualDOM it would be possible to scroll into the buffer?
The docs should probably point out the scroll behavior is contingent on the number of rows and where you are in the rows.
At any rate what I am trying to do is on input into a field select the appropriate row and have it appear at the top of the table.  selectRow(index)  will select a row that is not visible in the table, but not move to it. I can find nothing that programmatically moves a row. I see callbacks that respond to user's moving a row. Am I missing something?

**Comment by olifolkerd** [comment]
There is no function to move a row at the moment a user must do it, but i like the idea so i will add it to the roadmap.

In the mean time as a work around you could use ***getData*** to get all the rows, move the row in the array to the top then use the ***replaceData*** function to put it back in the table.

I hope that helps,

Cheers

Oli :)

**Comment by aklaver** [comment]
Alright thanks for the tip, I will see how that works.

**Comment by aklaver** [comment]
Well tried it and it works. In a jQuery autocomplete for the select action:
```
var rows = order_li_tbl.getData();
var idx = rows.findIndex(item => item.item_no === ui.item.value)
if (idx != -1){
    rows.unshift(rows.splice(idx, 1)[0]);
    lid = rows[0].line_id;
    order_li_tbl.replaceData(rows);
    order_li_tbl.selectRow(lid);
            }
```
