### ISSUE TITLE
Filter by Multiple fileds

### ISSUE THREAD

**Issue by wasimxe** [olifolkerd/tabulator#155]
Hi, 

Is this possible to filter by multiple fields, I read customFilter but don't know how to apply "like" filter on multiple fields, Could you please explain a little, 

Thanks for such a great app btw :)

**Comment by olifolkerd** [comment]
Hey Wasimxe,

Great to hear you are enjoying Tabulator. the good news is that this exact question has already been answered in issue #143 

Have a look at that and see if it answers your questions

Cheers

Oli

**Comment by wasimxe** [comment]
but I don't understand how to use type = like, I understand that how to use multiple filter using operator =, >=, <=, >, < but what about "like"
![screenshot_1](https://cloud.githubusercontent.com/assets/5351856/22159538/35aa8c36-df63-11e6-974d-87a9bdde6f32.png)
?

**Comment by wasimxe** [comment]
I understand it now, using regexp and match function, thanks for help.
