### ISSUE TITLE
MoveRows loses focus for tables on modal form

### ISSUE THREAD

**Issue by charlesfrisbee** [olifolkerd/tabulator#1550]
**Describe the bug**
I have two Tabulator tables on a modal form. I wish to drag rows from one table to the other via the existing functionality. I am able to click on and drag the row to the other table, but during dragging the row is shown behind the modal form. If I drop the row in the correct place (albeit shown behind) it moves as expected to the other table.

**Tabulator Info**
version 4.0.5

**_Code:_**

_Modal form_: (origin table: #modal-full-staff-table, target table: #modal-project-staff-table)

    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Add project staff</h4>
                </div>
                <div class="modal-body">
                    <div id="modal-full-staff-table"></div>
                    <div id="modal-project-staff-table"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary" onclick="read_data()">Add</button>
                </div>
            </div>
        </div>
    </div>

_Tabulator constructors_:

            //Table to move rows from
            var origin_table = new Tabulator("#modal-full-staff-table", {
                height: 311,
                layout: "fitColumns",
                movableRows: true,
                movableRowsConnectedTables: "#modal-project-staff-table",
                movableRowsSender: "delete",
                placeholder: "All Rows Moved",
                data: [
                    { id: 1, name: "Billy Bob" },
                    { id: 2, name: "Mary May" },
                ],
                columns: [
                    { title: "Name", field: "name" },
                ],
            });

            //Table to move rows to
            var target_table = new Tabulator("#modal-project-staff-table", {
                height: 311,
                layout: "fitColumns",
                movableRowsReceiver: "add",
                placeholder: "Drag Rows Here",
                data: [],
                columns: [
                    { title: "Name", field: "name" },
                ],
            });

**To Reproduce**
1. Open modal form
2. Drag row element from origin table
3. See row behind modal form

I have only tested this on a desktop (Chrome Version 70.0.3538.77)

Thanks

**Comment by olifolkerd** [comment]
That is probably because your modal has a higher z-index than the moving row.

try the following, you just need to make sure the z-index is higher than that of the modal

```css
.tabulator-row.tabulator-moving{
    z-index:99999;
}
```

I hope that helps,

Cheers

Oli :)
