### ISSUE TITLE
Group labels are missing in a grouped option list of the editable cell

### ISSUE THREAD

**Issue by apexuser** [olifolkerd/tabulator#1551]
**Describe the bug**
I create a table with editalbe cells. I try to use an option list with grouped options in the Select element, but group labels are not displayed.

**Tabulator Info**
Version 4.0
Full HTML example:

```
<html>
<head>
    <link rel="stylesheet" href="tabulator.css">
</head>
<body>
<div >
    <button class="menu-button" type="button" onclick="tbl.addRow({});">Add row</button>
</div>
<div id="tbltr">

</div>
<script src="tabulator.js"></script>
<script>
    var typeList = [
        { label: 'Default types',
            options: [
                {label: 'number',   value: 'number'},
                {label: 'varchar2', value: 'varchar2'},
                {label: 'date',     value: 'date'},
                {label: 'clob',     value: 'clob'}
            ]
        },
        { label: 'Custom types',
            options: [
                {label: 'Mytype1', value: 'mytype1'},
                {label: 'Mytype2', value: 'Mytype2'}
            ]
        },
        { label: 'Entities (add reference)',
            options: [
                {label: 'Entity1', value: 'entity1'},
                {label: 'Entity2', value: 'entity2'}
            ]
        }
    ];

    var tbltrColumnSettings = [
        {title:'Column name', field:'name', editor: 'input', headerSort:false},
        {title:'Type', field:'type', editor: 'select', editorParams: typeList, headerSort:false},
        {title:'Size', field:'size', editor: 'input', headerSort:false},
        {title:'Default', field:'default', editor: 'input', headerSort:false},
        {title:'Show', field:'show', editor:true, formatter:'tickCross', align: 'center', headerSort:false},
        {title:'Delete', field:'delete', formatter:'buttonCross', align: 'center', headerSort:false},
        {title: 'Advanced', field: 'advanced', visible:false}];

    var tbl = new Tabulator('#tbltr', {columns: tbltrColumnSettings});

</script>

</body>
</html>
```

**To Reproduce**
1. Open HTML file above.
1. Click "Add" button.
2. Click in the cell in column "Type".

**Expected behavior**
List with group options

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox (v. 62), Chrome (v. 70), Safari (v. 12).

**Screenshot**

<img src="https://farm5.staticflickr.com/4883/45679095191_e75c60e2ee.jpg"></img>

**Comment by olifolkerd** [comment]
The select editor has been upgraded in todays 4.1 release which should fix the issue for you.

Cheers

Oli :)

**Comment by apexuser** [comment]
Thank you very much!

But I found a new issue today in a new version (for me it is OK, just FYI). My table is situated inside a div with `z-index: 2`, so the new select list is shown below the div:

<img src="https://farm2.staticflickr.com/1904/44799782675_aa67d5a8ac.jpg" >

Currently, I solved this by adding a CSS to my project:
```
.tabulator-edit-select-list {
  z-index: 2;
}
```

**Comment by olifolkerd** [comment]
Good spot. Im doing a patch release this eve so i will get that fixed then
