### ISSUE TITLE
Default ajaxParams to false

### ISSUE THREAD

**Issue by cmlara** [olifolkerd/tabulator#1552]
**Is your feature request related to a problem? Please describe.**
Yes,  by default tabulator has an empty object for its ajaxParams which causes the request to have an appended question mark at the end making the URI "http://url/path" be "http://url/path?" 

At least one minimally implemented data source that parses the url for path information (json plugin of OLSRD)  treats the ? (incorrectly) as  part of the URI and returns 404  as "path?" does not equal "path"

This appears to be caused by Tabulator.prototype.defaultOptions having  ajaxParams set to "{}" by default which causes  a true return on if (this.table.options.ajaxParams) inside of Ajax.prototype.initialize which causes the Query string separator "?" to be appended to the request URI even though no query strings are being sent.

While the ultimate flaw of the server incorrectly parsing the URI is not the responsibility of Tabulator and Tabulator should be able to assume that servers will correctly respond to data requests it is possible other such flawed implementations are out there and may be used as sources to display data with Tabulator. It is also possible that other poorly implemented sources may act in unpredictable ways when they encounter a query string with no query attached potentiality causing difficult to diagnoses retrieval issues instead of an (obvious) 404 failure that occurred in this scenario.

The only use I can see for a blank query is some proxies may not cache the request if it has a query string on it, but that is not a guaranteed result as some proxies do.

**Describe the solution you'd like**

Change 
"ajaxParams: {}, //params for ajax loading"
to
"ajaxParams: false, //params for ajax loading

**Describe alternatives you've considered**
"ajaxParams:false" can be set when initializing the table causing the "?" not to be appended to the URI.

This should also work for setData but has not been tested in my lab.

Both cases however will requiring manually setting to false every initialization.

If kept as is a sub note in the documentation clarifying "{}" results in an empty query string being sent might be useful as it was not immediately obvious to me until I read the source code that "{}" was being treated as a desire to send a blank query string vs not wanting to send any query string.

**Additional context**
None at this time.

**Comment by olifolkerd** [comment]
Hey @cmlara 

Thanks for getting in touch,

That is definitely a bug there, i have pushed a fix for the issue to the 4.1 branch which will be released tommorrow.

I have taken a slightly different approach, leaving ***ajaxParams*** as it is but handling things better in the ajax module.

Cheers

Oli :)

**Comment by cmlara** [comment]
Thanks for the quick resolution on this! 

Your coded solution looks more elegant than what I suggested, 👍
