### ISSUE TITLE
Bootstrap menu Conflict with jquery-3.2.1.js

### ISSUE THREAD

**Issue by minalkArmstrong** [olifolkerd/tabulator#1553]
Hey ...
in my website we used bootstrap menu which conflict with file jquery-3.2.1.js used in tabulator .
If i comment this file menu works with it all functionality and tooltip of tabulator gets disturbed else its stops working.Please help me to resolve this issue.Its will solve issue of many pages of my web application.
Please refer attachment to see the issue.
[BugReport.pdf](https://github.com/olifolkerd/tabulator/files/2544823/BugReport.pdf)

**Comment by olifolkerd** [comment]
As of version 4.0 released last month Tabulator does not use jQuery

**Comment by minalkArmstrong** [comment]
Hi..
We have used tabulator in our software in many pages and if i replace old version with 4.0 then it  will not support old screen which are lived already  as new version have different tabulator definition.It will create issue  do you have any other solution to resolve this issue.

**Comment by olifolkerd** [comment]
Hey @minalkArmstrong 

If you want to continue using jQuery with tabulator 4.0, it still offers a jQuery wrapper to allow you to do this, checkout the [jQuery Support Documentation](http://tabulator.info/docs/4.0/jquery) for more information.

As for the version of jQuery you use, that is entirely up to you, Tabulator does not come packaged with jQuery so you can include what ever version you like, it should work with anything version of jQuery 2.0 and above.

Cheers

Oli :)
