### ISSUE TITLE
Consideration for children utilization in a Data Tree Layout

### ISSUE THREAD

**Issue by YendorMc** [olifolkerd/tabulator#1554]
This really hit the nail on the head on a project I'm working on  - Thanks!  However I'm using d3 for some visualizations, and was hoping you'd consider this feature in the future for an enhancement.

**Is your feature request related to a problem? Please describe.**
Would like for Tabulator "Data Tree" layout to utilize d3 techniques for identify children instead of utilizing _children construct.

**Describe the solution you'd like**
children would indicate an open tree element
_children would indicate a closed tree element

This way it can be controlled programmatically.

**Describe alternatives you've considered**
replace, duplicate or convert existing json tree structures to have a _ in front of children to use with tabulator.  have a separate json tree for d3 visualizations.

**Additional context**
This will allow one json structure to be used for d3 collapsible trees and have the same data in tabulator.

Examples of data structures using 'children':
https://bl.ocks.org/d3noob/43a860bc0024792f8803bba8ca0d5ecd
https://bl.ocks.org/mbostock/1062288
https://bl.ocks.org/mbostock/1093130

The once a click occurs, it closes the branches and converting it to "_children".  Seems to be a 'loose' standard.

**Comment by olifolkerd** [comment]
Hey @YendorMc 

Thanks for getting in touch, im glad to hear that you are enjoying the new feature,

Im afraid that D3's way of handling children does not follow Tabulators design principals.

Im trying to keep the functioning of the nested nature of the tree structure similar to the way the nested grouping structure works, allowing easy adoption by existing developers.

No other parts of Tabulator use field values to alter the function of the table so i feel it would be a bit outside the expected design flow.

That being said i would be happy to allow multiple fields to be designated for children, at that point you could use the existing ***dataTreeStartExpanded*** function to handle the changes for you.

In the mean time can i suggest a work around for you that would get the functionality you are after:

- use the ***dataTreeChildField*** to change the the child field to use the ***mychildren***field
- add mutators to the ***children*** and ***_children*** fields that copies the children to the ***mychildren*** field
- use a function on the ***dataTreeStartExpanded*** option that check to see if there is data in the ***children*** field and opens the node if present and closes it if not.

I hope that helps,

Cheers

Oli :)
