### ISSUE TITLE
tick/tickCross

### ISSUE THREAD

**Issue by aklaver** [olifolkerd/tabulator#1555]
**Describe the bug**
The 4.1 Release Notes say the tick formatter is deprecated in favor of the tickCross formatter. That to me says it is still usable just on the way out. However using the tick formatter creates an error that prevents display of the table

**Tabulator Info**
4.1.0
```
var proj_tbl = new Tabulator("#proj_table", {
    ajaxURL:"/proj_table/list",
    ajaxParams:{"p_item_no":$("#id_p_item_no").val(), "year_start":$("#id_year_start").val(), "year_end":$("#id_year_end").val()},
    ajaxConfig:{
        method:"GET",
    credentials: 'include'
    },
    height:"500px", // set height of table, this enables the Virtual DOM and improves render speed dramatically (can be any valid css height value)
    layout:'fitColumns',
    index:"line_id",
    addRowPos:"top",
    columns:[
        {title:"Id", field:"line_id", visible:false},
        {title:"P_id", field:"p_item_no"},
        {title:"Year", field:"year"},
        {title:"C_id", field:"c_id"},
        {title:"Trial", field:"trial", formatter:"tick"},
        {title:"Method", field:"method"},
        {title:"Sub", field:"sub_method"},
        {title:"Qty", field:"qty"},
        {title:"Pot#", field:"pot_ct"},
        {title:"Link", field:"link_key"},
        {title:"Vendor", field:"v_number__v_s_name"}
    ],
...
```

**To Reproduce**
1. Load a page with the above table.
2. Error:
```
TypeError: column.definition.formatterParams is undefined[Learn More]
tabulator.js:14238:10
Format.prototype.initializeColumn
http://127.0.0.1:8000/static/cc_app/js/external/tabulator/tabulator.js:14238:10
Column.prototype._buildColumnHeader
http://127.0.0.1:8000/static/cc_app/js/external/tabulator/tabulator.js:1521:4
Column.prototype._buildHeader
http://127.0.0.1:8000/static/cc_app/js/external/tabulator/tabulator.js:1290:4
Column
http://127.0.0.1:8000/static/cc_app/js/external/tabulator/tabulator.js:1151:3
ColumnManager.prototype._addColumn
http://127.0.0.1:8000/static/cc_app/js/external/tabulator/tabulator.js:328:16
ColumnManager.prototype.setColumns/<
http://127.0.0.1:8000/static/cc_app/js/external/tabulator/tabulator.js:313:4
forEach self-hosted:261:13 ColumnManager.prototype.setColumns
http://127.0.0.1:8000/static/cc_app/js/external/tabulator/tabulator.js:311:3
Tabulator.prototype._buildElement
http://127.0.0.1:8000/static/cc_app/js/external/tabulator/tabulator.js:6838:3
Tabulator.prototype._create
http://127.0.0.1:8000/static/cc_app/js/external/tabulator/tabulator.js:6721:3
Tabulator
http://127.0.0.1:8000/static/cc_app/js/external/tabulator/tabulator.js:6226:3
<anonymous>
http://127.0.0.1:8000/static/cc_app/js/cc_app/forms/plant_selector.js:85:16
```

Code involved:
```
//set column formatter
		switch (_typeof(column.definition.formatter)) {
			case "string":

				if (column.definition.formatter === "tick") {
					column.definition.formatter = "tickCross";

					if (typeof column.definition.formatterParams.crossElement == "undefined") {
						column.definition.formatterParams.crossElement = false;
					}

					console.warn("DEPRICATION WANRING - the tick formatter has been depricated, please use the tickCross formatter with the crossElement param set to false");
				}

```

**Expected behavior**
That the table loads.
Looks to me like the code is not doing the automatic conversion of tick --> tickCross.
Manually converting the formatters from tick --> tickCross solves the issue, but it would nice to get the 
deprecation warning instead of an error as the heads up.

**Desktop (please complete the following information):**
 openSUSE Leap 42.3
Firefox 60.3.0esr

**Comment by olifolkerd** [comment]
Hey @aklaver 

Thanks for the information, that is definitely a bug.

When i deprecate something i put in place a mapping function that maps the old setting on to the new functionality. in this case i had made an oversite and it was not handling situations when there was no formatterParams object set when the tick formatter was used.

I have pushed a fix for this to the master branch and will include it in the mornings patch release.

Thanks for the heads up,

Cheers

Oli :)

**Comment by tentus** [comment]
BTW, I know this issue has been closed, but while we're on the topic I'd like to mention that there are some typos in the deprecation warnings that are slightly misleading, for example:
"DEPRICATION WANRING - values for the select editor must now be passed into the valuse property of the editorParams object, not as the editorParams object"
should be
"**DEPRECATION WARNING** - values for the select editor must now be passed into the **values** property of the editorParams object, not as the editorParams object"
