### ISSUE TITLE
Tristate checkbox filterbar editor reverts to unchecked value on blur

### ISSUE THREAD

**Issue by haferje** [olifolkerd/tabulator#1558]
**Describe the bug**
When setting a tristate checkbox as a column's headerFilter, if you cycle through the different states, then click anywhere outside the checkbox, the column filters as if the checkbox were unchecked.

**Tabulator Info**
- Which version of Tabulator are you using?
4.1.1

**To Reproduce**
1. Go to https://jsfiddle.net/y26tpfzr/
2. Click on "Driver" headerFilter checkbox
3. Cycle through checked, unchecked, and indeterminate values
4. Click anywhere outside the checkbox
5. See how the grid filters as if the checkbox were unchecked

**Expected behavior**
The table should filter according to the state of the checkbox

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome
 - Version 68.0.3440.84 (Official Build) (64-bit)

**Additional context**
I believe the issue is in your setValue() function of Edit.prototype.editors.tickCross().  This method is called once onchange, but again onblur, which confuses the current state.

**Comment by olifolkerd** [comment]
Hey @haferje 

Thanks for the headsup, i will be doing a patch release this weekend so will include a the fix for this then,

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @haferje 

I have just pushed a fix for this to the master branch and will include it in this evenings update

Cheers

Oli :)

**Comment by haferje** [comment]
Awesome! I won't be able to test it right away, but the code change looks great.

**Comment by haferje** [comment]
It works great - just what I was looking for!
Thanks
