### ISSUE TITLE
Allow contributions to the documentation site

### ISSUE THREAD

**Issue by haferje** [olifolkerd/tabulator#1559]
**Is your feature request related to a problem? Please describe.**
Was just wondering if there were any plans to allow contributions to the documentation at http://tabulator.info/docs?

**Describe the solution you'd like**
I would like to give back and contribute to this project in some way.  The easiest way is in adding to or modifying documentation and examples/demos. Some projects host their documentation in a GitHub Pages repository so the documentation for a GitHub project can itself be cloned, modified, and committed for a pull request.

**Comment by olifolkerd** [comment]
Hey @haferje 

Thanks for your interest in contributing, at the moment i dont really want to make the documentation source entirely public as i am working on a number of things (such as a forum and case study articles) where it could be dangerous to allow access to the full source.

That being said, the source is hosted on a private bit bucket repo so i would have no issue allowing access to specific contributors.

What sort of things would you like to add to the documentation?

Cheers

Oli :)

**Comment by haferje** [comment]
For now, it is just spelling corrections in the docs and additions to some of the demos.  There were a couple times I had to read the source to understand what I needed to specify to get a feature working. Nothing major at the moment.

**Comment by olifolkerd** [comment]
Any feedback would be welcome.

When you say read the source, what do you mean? all of the table examples on the site have a "view source" button under them that shows how to set them up, is there something missing from these?

Cheers

Oli :)

**Comment by haferje** [comment]
No, I'm aware of the "View Source" button on the examples.  I can't remember what it was, but at the time I had to do a quick skim of Tabulator's source library files to understand what I needed to specify in my code. It was probably something I was doing wrong, so don't worry about it.

My main question was simply if you had open-sourced the documentation, but I understand if you can't at the moment.

Thanks!
