### ISSUE TITLE
Visible Columns when creating from HTML Table Element

### ISSUE THREAD

**Issue by sadscoot** [olifolkerd/tabulator#156]
Hi Oli,

I have another enhancement request. Would it be possible to check whether column header has the display attribute set, and if it is set to none, then set the column visibility to false? Similar to how you are checking the column width attribute.

Thanks,
Scott

**Comment by olifolkerd** [comment]
Hi Scott,

I will have a look into that this weekend. Is there a particular reason you would do this over setting it in the column definition array?

Cheers

Oli

**Comment by sadscoot** [comment]
You would not need a column definition array, as it loads from the table headers.
http://olifolkerd.github.io/tabulator/examples/#table-load

Thanks,
Scott

**Comment by olifolkerd** [comment]
Hey,

looking into the HTML specification (and after a bit of testing), adding a ***display:none*** to a table header does not hide the column, only the table header.

As this does not have a consistent behaviour throughout the table it would not be suitable to add this as an option to Tabulator.

I would suggest that you use the column definition array, setting the ***visible*** property to false on columns that you do not wish to show.

Thanks for your suggestion

Oli

**Comment by olifolkerd** [comment]
I have just had an interesting idea,

I could look at allowing you to set custom ***tabulator-property*** attributes in the column headers, which could then be parsed in to Tabulator, allowing you to set most tabulator options in the table headers.

would that be of use to you?

Cheers

Oli

**Comment by sadscoot** [comment]
Hi Oli,
That would be very useful.
Cheers,
Scott

**Comment by olifolkerd** [comment]
Hi Scott,

You can now set table and column options using ***tabulator-*** attributes directly in your HTML table:

```html
<table tabulator-fitColumns="true">
    <thead>
        <th tabulator-align="center">Name</th>
    </thead>
</table>
```

Full details can be found [here](http://olifolkerd.github.io/tabulator/docs/#table-load)

Thanks for the suggestion!

Cheers

Oli :)
