### ISSUE TITLE
Sorted Select Editor Option

### ISSUE THREAD

**Issue by daitau** [olifolkerd/tabulator#1560]
The new options to auto populate the select list with all the values of the cells column is really useful. However it seems that it is not possible to control the order of the returned values from `getUniqueColumnValues()`. Currently I change the last line to say `return Object.keys(output).sort();` but I think it may be useful to have a proper option/custom function for sorting those values.

**Comment by olifolkerd** [comment]
Hey @daitau 

I have added the new ***sortValuesList*** option to the editorParams for select and autocomplete editors to sort the auto generated lists

```js
{title:"Example", field:"example", editor:"select", editorParams:{
    values:true, //create list of values from all values contained in this column
    sortValuesList:"asc", //if creating a list of values from values:true then choose how it should be sorted
}}
```

I have pushed this update to the 4.2 branch and it will be included in the public release on monday.

Cheers

Oli :)

**Comment by cgountanis** [comment]
It would be cool is sortValuesList:"asc" worked on values: that are not set to true such as dynamically generated.
