### ISSUE TITLE
Different group levels in same table

### ISSUE THREAD

**Issue by hramenko** [olifolkerd/tabulator#1565]
Hi, I need to display tree  like this

group
-- subgroup
---- record 1 
---- record 2
group 
-- record 1
-- record 2

Is it possible ?

**Comment by olifolkerd** [comment]
Hey @hramenko 

You can pass in an array of fields to the ***groupBy*** option, if we asume that your are grouping by the filed of "group" then by the field of "subgroup" it would be:

```js
groupBy:["group", "subgroup"],
```

I hope that helps,

Cheers

Oli :)

**Comment by hramenko** [comment]
> Hey @hramenko
> 
> You can pass in an array of fields to the _**groupBy**_ option, if we asume that your are grouping by the filed of "group" then by the field of "subgroup" it would be:
> 
> ```js
> groupBy:["group", "subgroup"],
> ```
> 
> I hope that helps,
> 
> Cheers
> 
> Oli :)

I want two levels for some records, but for others only the first level is needed. If grouping by two fields is set, then this applies to the entire table.

**Comment by olifolkerd** [comment]
Hey @hramenko 

Ahh yes, sorry i missed that in your first post. im afraid that isnt possible, the same level of grouping has to be used throughout the table.

Cheers

Oli :)

**Comment by hramenko** [comment]
>  im afraid that isnt possible, the same level of grouping has to be used throughout the table.
Ок. maybe bossible to show some records as subheaders?  
just like merged cells in excel:

[record title][recordfield1][decordfield2]
[record title][recordfield1][decordfield2]
[record title][recordfield1][decordfield2]
[record title merged -----------------     ]
[record title][recordfield1][decordfield2]
[record title][recordfield1][decordfield2]

**Comment by olifolkerd** [comment]
You could probably use a mixture of [Grouping](http://tabulator.info/docs/4.1/group) and [Data Trees}(http://tabulator.info/docs/4.1/tree) to achieve something similar.

You could also have a look at [Row Formatting](http://tabulator.info/docs/4.1/format#row) which can allow you to alter the contents of a row

I hope that helps,

Cheers

Oli :)
