### ISSUE TITLE
Ajax Load Error with IE11

### ISSUE THREAD

**Issue by berr56** [olifolkerd/tabulator#1566]
Hi,
Here I'm trying to upgrade my tabulator from 3.5 to 4.1

I have some problem , with IE11
( while with Crome work perfectly, and it is very fast)
Please help me
the code;

```html
<script type="text/javascript" src="fetch.js"></script>
<script type="text/javascript" src="polyfill.min.js"></script> 
<script type="text/javascript" src="tabulator.min.js"></script>
```

```js
table = new Tabulator("#patient-table",
	{
	...
   	ajaxError:function(xhr, textStatus, errorThrown){
		.....	
        },	
});

table.setData(getlocalUrl() + "cce/dash/CceRest/patients");
```

returned values from ajaxError funcion:
xhr contain  "fetch not found"
textStatus is null
errorThrown is null
      
while, into script debugger console, I have two error:

Syntax Error
File: fetch.js row 78

Ajax Load Error: ReferenceError: 'fetch' is not defined
Possible Unhandled Promise Rejection: undefined

 Thanks for a lot of help!!!

**Comment by olifolkerd** [comment]
Hey @berr56 

Thanks for getting in touch.

As mentioned in the [Browser Support Documentation ](http://tabulator.info/docs/4.1/browsers#ie) Tabulator uses the built in ***fetch*** api and ***Promises*** for making ajax requests. As IE is a legacy system it is missing both of these features.

Not to worry though there are a couple of nice polyfills you can include in your project to add this functionality to ie:

https://github.com/taylorhakes/promise-polyfill
https://github.com/github/fetch

Just make sure to include them in your project before Tabulator.

I hope that helps,

Cheers

Oli :)

**Comment by berr56** [comment]
hi,
 thanks for reply,
 but, has you can see in my previus post ,I have already included the features mentioned.
(sorry, the code is not easily readable due to incorrect formatting of the editor)

The problem is that I obtain the following error

Syntax Error
File: fetch.js row 78

Ajax Load Error: ReferenceError: 'fetch' is not defined
Possible Unhandled Promise Rejection: undefined

**Comment by olifolkerd** [comment]
Hey @berr56 

Sorry for this misunderstanding, i have reformatted your question to make the code clearer :)

Could you post a copy of your whole table constructor so i can better understand how your table is configured.

Cheers

Oli :)

**Comment by berr56** [comment]
the code:

var table;
function defineTable()
{
	table = new Tabulator("#patient-table",
	{
		layout:"fitColumns",
		columns:[
	    	{title:"", field:"idtiporicovero",visible:false},
	        {title:"Cognome", field:"surname", sorter:"string"},
	        {title:"Nome", field:"name", sorter:"string"},
	        {title:"Nascita", field:"stringDataNascita",width:105,align:"center",sorter:"date", sorterParams:{format:"DD/MM/YYYY"}},
	        {title:"M/F", field:"sex",width:60,align:"center", sorter:"string"},
	        {title:"C.F.", field:"codfisc",width:160,align:"center", sorter:"string"},
	        {title:"Id Paz.", field:"idpaziente",width:90,align:"right", sorter:"number"},
	        {title:"Nosologico", field:"visit_number",width:125,align:"center", sorter:"number"},
	        {title:"Data R.", field:"stringDataRicovero",width:105,align:"center",sorter:"date", sorterParams:{format:"DD/MM/YYYY"}},
	        {title:"Regime", field:"regime_descrizione",width:100	,align:"left",headerTooltip:"Regime ricovero"},
	        {title:"Letto", field:"letto_corrente",width:100,align:"right"},
	    ],
	   
    
    dataLoaded:function(data){        	$("#numerOfResult").text(data.length);   	},
    	ajaxError:function(xhr, textStatus, errorThrown){
    		log.error("ricoverati ajax error:"+textStatus);
        },	
});

	table.setSort( [
	    {column:"surname", dir:"asc"}, //sort by this first
	    {column:"name", dir:"desc"}, //then sort by this second
	]);
};

table.setData(getlocalUrl() + "cce/dash/CceRest/pazienti/pazientiAttualmenteRicoverati",{contesto:G_SESSIONID, surname: $("#surname").val(),name:"",sdo:"",idpaz:"",idcdc:G_cdc});
thanks!

**Comment by olifolkerd** [comment]
Hey @berr56 

Sorry for the delay in getting back to you.

After running some tests, i cant replicate your issue at all, when i pull in the dependencies everything runs smoothly

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/fetch/2.0.4/fetch.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
```

If i were you i would check that they have actually loaded.

Cheers

Oli :)

**Comment by berr56** [comment]
hey Oli,
with above dependencies now work fine
thanks a lot
