### ISSUE TITLE
Open pdf in new window/tab

### ISSUE THREAD

**Issue by Rodbjartson** [olifolkerd/tabulator#1567]
Hi I am wondering whether it is possible to open pdf in a new tab?
Now it can be downloaded, which is great, but I would love the possibility of being able to hit a button in my program and this button fires the jspdf+autotable generation and immediately opens the generated pdf document in a new browser tab/window.

**Comment by olifolkerd** [comment]
an interesting idea, but I dont think this would be possible as the file content is generated in the client and attempting to open it in a new tab would probably break the browser sand boxing rules.

I have an idea for a tweak that might work, but i am doubtful.

I will have a try over the weekend and let you know.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
That is the approach i was thinking about.

In that case i will add it as a feature to 4.2

In the mean time you can probably acheive this using the ***downloadReady*** callback:

```js
var table = new Tabulator("#example-table", {
    downloadReady:function(fileContents, blob){
        //fileContents - the unencoded contents of the file
        //blob - the blob object for the download

        //custom action to send blob to server could be included here

        window.open(window.URL.createObjectURL(blob));

        return false; //must return a blob to proceed with the download, return false to abort download
    }
});
```

Let me know if that works

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Just tested it, that does work!

Go Team!

**Comment by Rodbjartson** [comment]
Terrific!! 🥇
