### ISSUE TITLE
dataTree VirtualDOM not working

### ISSUE THREAD

**Issue by aklaver** [olifolkerd/tabulator#1568]
**Describe the bug**
dataTree does not seem to work with Virtual DOM

**Tabulator Info**
Tabulator 4.1.0
```
var reverseTable = new Tabulator("#reverse_tag_table", {
    ajaxURL:"/reverse_tag_table_data/list",
    dataTree: true,
    layout:"fitColumns",
    // height: "1000px",
    // pagination: "local",
    // paginationSize: 15,
    columns: [
        {title: "Link Key", field: "link_key"},
        {title: "Common", field: "common"},
        {title: "Item No", field: "p_item_no"},
        {title: "Pot Ct", field: "pot_ct"}
    ]

});
```

**To Reproduce**
1. Open page with height set.
2. Data is truncated.

**Expected behavior**
The entire data set is present.

**Screenshots**

With height set:
![screenshot-2018-11-6 cascade cuts](https://user-images.githubusercontent.com/658260/48082414-6714bb00-e1a7-11e8-8736-ad151bfacd76.png)

With height not set:
![screenshot-2018-11-6 cascade cuts 2](https://user-images.githubusercontent.com/658260/48082550-ca9ee880-e1a7-11e8-9c5c-092f8c38a3e2.png)

**Desktop (please complete the following information):**
openSUSE Leap 15
Firefox 60.3.0esr (64-bit)

**Comment by olifolkerd** [comment]
Hey @aklaver 

It is working correctly in the examples on the website and they all use the virtual DOM so im not sure that the virtual DOM is the root cause of your issues.

Could you try defining your table in an empty HTML page and see how it works with no other code interacting with it.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
I have just tried your sample code in chrome, firefox and ie on my windows 10 machine and they are working correctly.

Is your table hidden when the data is loaded?

Cheers

Oli :)

**Comment by aklaver** [comment]
It works if I make the height so it displays less then 20 rows in the container. In that case a vertical scroll bar appears and I see all the rows.

**Comment by olifolkerd** [comment]
Im afraid i still cant replicate what you are describing, with 20 rows or 200 it just works for me. is there any way you could put together a codepen or JS fiddle for this as we are clearly each doing something different

**Comment by kalimuthu123** [comment]
cdn not works with can u send me the cdn for datatree tables

**Comment by aklaver** [comment]
See below,  though I would change 4.2.4 -->  4.2.5 to get latest.
http://tabulator.info/docs/4.2/install#sources-cdn
