### ISSUE TITLE
dataTree replaceData

### ISSUE THREAD

**Issue by aklaver** [olifolkerd/tabulator#1569]
**Describe the bug**
replaceData() does not  seem to work correctly with dataTree data.

**Tabulator Info**
Tabulator 4.10.0
```
var reverseTable = new Tabulator("#reverse_tag_table", {
    ajaxURL:"/reverse_tag_table_data/list",
    dataTree: true,
    layout:"fitColumns",
    // height: "1000px",
    // pagination: "local",
    // paginationSize: 15,
    columns: [
        {title: "Link Key", field: "link_key"},
        {title: "Common", field: "common"},
        {title: "Item No", field: "p_item_no"},
        {title: "Pot Ct", field: "pot_ct"}
    ]

});
```

**To Reproduce**
1. Use reverseTable.replaceData("/reverse_tag_table_data/list", {"prj_yr": yr})
2. This will work the first time it is called on an open table.
3. If it is used again on the table with new data it will not replace the data.
4. Using reverseTable.setData("/reverse_tag_table_data/list", {"prj_yr": yr}) works as expected.

**Expected behavior**
The data should be replaced with the new data set.

**Desktop (please complete the following information):**
openSUSE Leap 15
Firefox 60.3.0esr (64-bit)

**Comment by olifolkerd** [comment]
Hey @aklaver 

I have just run a test on my side and im afraid i cant replicate this, could you make sure you are on the latest code 4.1.1 and try int on a new blank HTML doc.

Cheers

Oli :)

**Comment by aklaver** [comment]
Same solution as #1568. Display 20 rows or less and this works.

**Comment by olifolkerd** [comment]
Im afraid i still cant replicate what you are describing, with 20 rows or 200 it just works for me. is there any way you could put together a codepen or JS fiddle for this as we are clearly each doing something different

**Comment by aklaver** [comment]
Yeah, I will get to that later.

**Comment by aklaver** [comment]
Codepen example:

https://codepen.io/aklaver/pen/GwoJwy

Uncomment height to see what I am talking about.

**Comment by olifolkerd** [comment]
Im afraid i still dont see any issue, it is working fine on Chrome.

What browser are you using?

Cheers

Oli :)

**Comment by aklaver** [comment]
Firefox.

**Comment by olifolkerd** [comment]
Im afraid that all still just works for me, sorry
