### ISSUE TITLE
Grouping Data the Group close as initial

### ISSUE THREAD

**Issue by kurtknippschild** [olifolkerd/tabulator#157]
Hi Oli,

another questions.
Is there any paramter for "groupBy: "xxx", that the groups are closed and not opend when the table is generated?

The second question.
Group in group is this possible?

Thanks in advanced.

MG Kurt

**Comment by olifolkerd** [comment]
There is currently no way of specifying whether a group should be open or closed when it is generated, but that is a great idea! i will add that to the road map and get it out soon.

Nested groups are currently not possible, could you give me an example usage case for nested groups and how you would expect them to be rendered. i would be happy to look into it for you.

Cheers

Oli

**Comment by kurtknippschild** [comment]
Hi Oli,

thanks for the quick answers.
A parameter for open or close of groups a great nice feature.

Here are screenshot for a table with nested groups:
![bildschirmfoto 2017-01-21 um 11 00 30](https://cloud.githubusercontent.com/assets/22855656/22173638/bf45c256-dfc9-11e6-9010-b358868aca47.png)

This is a table of a hirarchical structure.
That was great when tabulator.js this function in the future has.

MG Kurt

**Comment by olifolkerd** [comment]
Hey,

You can now set the open or closed state for a group using the ***groupStartOpen*** property:
```js
$("#example-table").tabulator({
    groupBy:name,
    groupStartOpen:false,
});
```
You can pass a value of ***true***, ***false***, or a function to this property to set the open state for each group.

Full documentation can be found [here](http://olifolkerd.github.io/tabulator/docs/#grouping)

Cheers

Oli :)

**Comment by olifolkerd** [comment]
for the time being, nested groups will not be possible, but i will add it to the road map to look at in the future.

Thanks for the great suggestion!

Cheers

Oli
