### ISSUE TITLE
Allow headerFilters to share a row

### ISSUE THREAD

**Issue by haferje** [olifolkerd/tabulator#1571]
I have a bunch of textbox headerFilters in my grids.  My grid header text is specified to wrap to the next line, which pushes the filter down, and is then misaligned with filter boxes from other columns where the header text doesn't wrap.

It would look a little cleaner if I could specify all headerFilters to be on a shared row, separate from the column titles.  This could be achieved through an option or some kind of custom filter rendering method maybe?

This is something I can achieve with some custom CSS, but to me it seems a little hacky and isn't 100% correct.

**Comment by olifolkerd** [comment]
Hey @haferje 

have you tried:
```js
columnVertAlign:"bottom",
```

that should vertical align the header to the bottom rather than the top of the header

**Comment by haferje** [comment]
I tried `columnVertAlign`, but when I don't have a filter on a column, the text is at the very bottom, and no longer aligned with the text from other columns.  Ultimately, I would like to top-align all header titles with some columns wrapping, and bottom-align all the header filters so they appear on the same horizontal.

If this feature request is not appealing, I can get by through other means.

Thank you.

**Comment by olifolkerd** [comment]
I can certainly see the appeal of what you propose.

Unfortunately it would take quite a lot of effort to implement at this point, and i already have more pressing issue for the next few releases.

I will add it to the roadmap to investigate later down the line, but i wouldn't be able to get it in for a few months yet.

Cheers

Oli :)
