### ISSUE TITLE
ability to customize default styles and attributes on `tickCross`, `input`, etc

### ISSUE THREAD

**Issue by niftylettuce** [olifolkerd/tabulator#1572]
I noticed that a lot of people want to customize the styles, but it should be also possible to customize attributes and override defaults.  A simple option or object could be passed that would extend styling and attrs.

**Comment by olifolkerd** [comment]
Hey @niftylettuce 

Major styling to the table should be done using CSS as that is what it is designed for, it is also more easily reusable between tables, Tabulator is a complex beast (just have a look at the style sheets to see for yourself) and JavaScript based styling is rigid an inflexible.

Checkout the [Styling Documentation](http://tabulator.info/docs/4.1/style) for a full list of classes and SCSS variables.

Tabulator also comes with a series of [Pre Built Themes](http://tabulator.info/examples/4.1#theming) to give people a variety of good starting points for building their own varients.

Cheers

Oli :)
