### ISSUE TITLE
Accessing the global variable Tabulator

### ISSUE THREAD

**Issue by Rodbjartson** [olifolkerd/tabulator#1573]
This is a question that most likely should be on stackoverflow, but I have no user there at the moment.
I would like to extend tabulator with a traffic light formatter(been on the roadmap for a while, and I understand you have more important features to be implemented). 

How should I do this?
I have tried to paste your example from the docs in my code;
```
Tabulator.prototype.extendModule("format", "formatters", {
    bold:function(cell, formatterParams){
        return "<strong>" + cell.getValue() + "</strong>"; //make the contents of the cell bold
    },
    uppercase:function(cell, formatterParams){
        return cell.getValue().toUpperCase(); //make the contents of the cell uppercase
    }
});
```
However, my code cannot find the variable Tabulator(unexpected identifier). How can I access it? I have loaded in tabulator through cdn;
```
    <link href="https://unpkg.com/tabulator-tables@4.1.1/dist/css/tabulator.min.css" rel="stylesheet">
<script type="text/javascript" src="https://unpkg.com/tabulator-tables@4.1.1/dist/js/tabulator.min.js"></script>
```
Plus, the wrapper, as I still use jquery.
Do I have to load in the "un"minified version for it to work?

**Comment by Rodbjartson** [comment]
It worked, just an error.

**Comment by olifolkerd** [comment]
Good to hear you got it working. I would love to see it when you have finished the formatter

**Comment by Rodbjartson** [comment]
I am not sure how you pictured the traffic light formatter. For me I just needed a fast visual representation of a server's status at our company.
Green would indicate a server that is up and running.
Yellow indicates a server that is under maintenance.
Red indicates a server that is down and has experienced an unknown failure.

While coding I realized that this traffic light formatter thing is very domain specific. In some instances you can go with data returning -1, 0, or 1. In other cases, like our own, it was more complicated. I ended up coding something that probably cannot be used by others, so I think keeping the approach you use by having us extend our own formatters is great. 

One very simple approach could be;
```
Tabulator.prototype.extendModule("format", "formatters", {             
                trafficLight: function (cell, formatterParams) {
                    var value = "";
                    alert(cell.getValue())
                    if (cell.getValue() > 3) { value = "<i class='fa fa-circle' style='color: #2DC214;'></i>" }
                    else if (cell.getValue() < 1) { value = "<i class='fa fa-circle' style='color: #CE1515;'></i>" }
                    else  { value = "<i class='fa fa-circle' style='color: #f4e542;'></i>" }
                    return value //make the contents of the cell uppercase
                }
            });
```
And inside your tabulator constructor object:
`{ title: "Status", field: "SERVER_STATUS_INC", align: "center", formatter:"trafficLight"}`

I simply used font-awesomes representation of a circle :)

![trafficlight](https://user-images.githubusercontent.com/11444201/48137971-8abd2b80-e2a3-11e8-92fb-f34bafd42645.png)

**Comment by olifolkerd** [comment]
Thanks for the info,

I have built a dynamic color system for the progress bar i can adapt for a traffic light formatter. though your feedback on needing specific values for each colour is noted, i will make sure it can do that too.

Thanks for the feedback

Cheers

Oli :)
