### ISSUE TITLE
CSV Export with BOM option

### ISSUE THREAD

**Issue by michaelongithub** [olifolkerd/tabulator#1574]
Hi Oli
first congrats to Your 4.1. Great as always !

**Is your feature request related to a problem? Please describe.**
Very often the CSV Export is used by users to be opened in Excel and the file needs to be a CSV, not Excel for user company handling reasons.

The CSV Export currently writes UTF-8 without BOM.
Excel can open such files not  with correctly representing the character set (without configuring an explicit import) if one has special chars, german umlaut etc.

**Describe the solution you'd like**
Make CSV export standard with BOM or offer that as optional parameter in the table.download("csv", "data.csv", {delimiter:"."}, {bom:true});

Cheers Michael

**Comment by olifolkerd** [comment]
Hey @michaelongithub 

Glad to hear you like it.

I can certainly add a BOM option for the CSV downloader, i will stick it on the roadmap,

Cheers

Oli :)

**Comment by michaelongithub** [comment]
Great and thanks.

**Comment by olifolkerd** [comment]
This has been added to the 4.2 branch which will be released on monday 

Cheers

Oli :)
