### ISSUE TITLE
Hidden columns in a column group break the column alignment

### ISSUE THREAD

**Issue by philipsouthwell** [olifolkerd/tabulator#1575]
**Describe the bug**
Hidden columns in a column group break the column alignment. This happens when the column header width is larger than the sum of the children column widths.

**Tabulator Info**
I'm using Tabulator 3.5. Here's an example of the misalignment. Notice that from the "Gender" column the whole table has shifted to the left.

![example](https://user-images.githubusercontent.com/2056498/48155770-a95f0900-e31b-11e8-9063-1807541e5ae6.png)

My table construction is taken from the Tabulator website with two hidden columns inserted, and the text in the column header made longer than the sum of the tables.

        $("#example-table").tabulator({
            data: tabledata,
            columnVertAlign:"bottom", //align header contents to bottom of cell
            columns:[
                {title:"Name", field:"name", width:160},
                {//create column group
                    title:"Work Info let's make this heading long so we break the format",
                    columns:[
                        {title:"Progress", field:"progress", align:"right", sorter:"number", minWidth:100},
                        {title:"Hidden column 1", field:"hidden1", align:"center", visible: false},
                        {title:"Hidden Column 2", field:"hidden2", align:"center", visible: false},
                        {title:"Rating", field:"rating", align:"center", minWidth:80},
                        {title:"Driver", field:"car", align:"center", minWidth:80},
                    ],
                },
                {//create column group
                    title:"Personal Info",
                    columns:[
                        {title:"Gender", field:"gender", width:90},
                        {title:"Favourite Color", field:"col", width:140},
                        {title:"Date Of Birth", field:"dob", align:"center", sorter:"date", width:130},
                    ],
                },
            ],
        });

**Comment by olifolkerd** [comment]
Hey @philipsouthwell 

Thanks for getting in touch, sorry to hear you are having issues.

I dont think it is a hidden column that is the problem, if you remove the two definitions from the table all toegather you will probably still have the issue because the group header text is wider than the columns.

Is that the case?

Cheers

Oli ;)

**Comment by philipsouthwell** [comment]
If I remove the hidden columns the formatting error goes away, and the table renders as it should

![selection_002](https://user-images.githubusercontent.com/2056498/48178910-2ade8780-e36c-11e8-8bfe-5429bc72e575.png)

**Comment by olifolkerd** [comment]
Ahh interesting. I will investigate further this evening

**Comment by Rodbjartson** [comment]
@1299

**Comment by philipsouthwell** [comment]
I can confirm that it's fixed in 4.1
