### ISSUE TITLE
make group with colspan

### ISSUE THREAD

**Issue by sphynx79** [olifolkerd/tabulator#1576]
How can i make the group row with rowspan like this:

![2018-11-07_22-26-57](https://user-images.githubusercontent.com/5004160/48162009-469a4d00-e2dc-11e8-889a-9f58a546b55e.png)

![2018-11-07_22-27-33](https://user-images.githubusercontent.com/5004160/48162041-57e35980-e2dc-11e8-8de5-0a752db8e36c.png)

Thanks

**Comment by sphynx79** [comment]
```javascript

**Comment by olifolkerd** [comment]
Nice use of a row formatter!
