### ISSUE TITLE
JSON Arrays are turned into objects (with indices) 

### ISSUE THREAD

**Issue by Keyframe** [olifolkerd/tabulator#1579]
I can't tell if this is a feature or a bug :)

If you feed JSON with arrays into tabulator, for example: 

```
{
"someField": "blabla", 
"someArray": ["one", "two"]
}
```
Once tabulator edits data (dataEdited fired), JSON arrays are changed into objects with indices, like this: 

```
{
"someField": "blabla", 
"someArray": { "0": "one", "1": "two"}
}
```

What gives? Is there a way to keep original format of JSON?

**Comment by remipassmoilesel** [comment]
I'm not sure this issue is fixed, I didn't see the fix for that.

**Comment by Keyframe** [comment]
I've located where it is (and fixed locally). It's an issue in core.js

in `deepClone: function(obj){`

`var clone = {};`

should be more like

`var clone = Array.isArray(obj) ? [] : {};`

**Comment by olifolkerd** [comment]
This issue was fixed in the 4.1.0 release

**Comment by Keyframe** [comment]
Oddly enough, 4.1.1. is where my log now shows. Fixed in any case. Let's see if it pops up anywhere else.

**Comment by remipassmoilesel** [comment]
Great, good news !

**Comment by Keyframe** [comment]
@olifolkerd it's fixed now!
