### ISSUE TITLE
Frozen column on right overflowing other non frozen columns

### ISSUE THREAD

**Issue by marovargovcik** [olifolkerd/tabulator#1582]
**Description of problem**
Frozen column on right side of table is overflowing another columns. I believe there is missing padding-right applied on table that would create empty space reserved for width of frozen column.

**Version:** 4.1.1
```javascript
var table = new Tabulator("#example-table", {
    data: [
        {name: "Anna", progress: 25, gender: "Female", rating: 5, dob: "22/05/1982", car: true}
    ],
    columns:[
        {title:"Name", field:"name"},
        {title:"Progress", field:"progress", formatter:"progress"},
        {title:"Gender", field:"gender"},
        {title:"Rating", field:"rating",  formatter:"star"},
        {title:"Date Of Birth", field:"dob"},
        {title:"Driver", field:"car", formatter:"tickCross", frozen: true},
    ],
});
```
**Live example of this behavior**
I prepared this example to see issue:
https://stackblitz.com/edit/js-rxjpgb

**Expected behavior**
Even with frozen column on right, all other non frozen columns should not be overflown by frozen one.

When frozen column is fixed on the left there is `padding-left: {widthOfFrozenColumn}px` applied to all rows. When frozen column is fixed on the **right side** there is only `padding-left: 0` but there should be also `padding-right: {widthOfFrozenColumn}px`.

**Screenshots**
![logo](https://i.imgur.com/vVFjekE.jpg)

**Affected browsers**
I tested the latest Firefox and Chrome versions.

I tried looking for this issue but no luck so I decided to create one. 
Is there any possible workaround at the moment?

Thank you and have a nice day.

**Comment by marovargovcik** [comment]
I noticed that in this file [frozen_columns.js](https://github.com/olifolkerd/tabulator/blob/master/src/js/modules/frozen_columns.js) there is commented line 129 that is supposed to do something with padding-right. 

So I tried to uncomment this line and rebuild Tabulator and it's working fine (`padding-right` is now correctly being added to row now) but there is buggy behavior when scrolling horizontally fast. It's hard to explain so here is a video with this behavior captured.
https://drive.google.com/open?id=1M_ovNG7Je3JunpUF9KKfUVwSgIudOijc

That's definitely more acceptable bug than hidden column because it does not limit readability of table data.

**Comment by olifolkerd** [comment]
Hey @marovargovcik 

Thanks for the information. a right margin needed to be added to the ***tabulator-table*** element.

I have pushed a fix for this to the master branch and will include it in this evenings patch update.

Cheers

Oli :)
