### ISSUE TITLE
Cannot read 'removeChild' property from null

### ISSUE THREAD

**Issue by hramenko** [olifolkerd/tabulator#1583]
**Describe the bug**
Table data are grouped by two fields, and there are some calculated totals.
Clicking on a top level group header leads to an error.
tabulator.js: 15451 Uncaught TypeError: Cannot read 'removeChild' property from null

**Tabulator Info**
4.1.2
OS win7.sp2 x64, - Opera 58.0.3134.0 x64

 var tblData = [
   {"id":1, "title": "record 1", "cat":1, "subcat":1, "qty":2, "value1": 1, "value2": 11, "rowtotal":0},
   {"id":2, "title": "record 2", "cat":1, "subcat":1, "qty":8,  "value1": 2, "value2": 12, "rowtotal":0},
   {"id":3, "title": "record 3", "cat":1, "subcat":1, "qty":12,  "value1": 3, "value2": 13, "rowtotal":0}, 
   {"id":4,"title": "record 1", "cat":1, "subcat":2, "qty":7, "value1": 1, "value2": 11, "rowtotal":0},
   {"id":5,"title": "record 2", "cat":1, "subcat":2, "qty":6,  "value1": 2, "value2": 12, "rowtotal":0},
   {"id":6,"title": "record 3", "cat":1, "subcat":2, "qty":9,  "value1": 3, "value2": 13, "rowtotal":0},    
 ];
  
var Tablecalc = new Tabulator("#table1", {
    data: tblData,    
    layout:"fitColumns",
    groupBy:["cat","subcat"],
    groupClosedShowCalcs:true,
    groupToggleElement:"header",
    cellEdited:function(cell){ 
          var row = cell.getRow();       
          var data = row.getData();
          var val = (data.value1 + data.value2) * data.qty;
          row.update({"rowtotal":val});
          row.reformat();
    },
   columns: [
   {title:"title", field:"title", width:200},        
   {title:"cat", field:"subcat", width:200, visible:false}, 
   {title:"subcat", field:"subcat", width:200, visible:false}, 
   {title:"qty", field:"qty", width:200, editor:true, bottomCalc:"sum"},
   {title:"value1", field:"value1", width:200},
   {title:"value2", field:"value2", width:200},
   {title:"Total", field:"rowtotal", width:200, bottomCalc:"sum", 
      formatter:function(cell, formatterParams){
        var data = cell.getRow().getData();
        value = (data.value1 + data.value2) * data.qty;
        data.rowtotal = value;
        return value;
      }, 
      mutator: function(value, data, type, params, component){
         var val = (data.value1 + data.value2) * data.qty; 
             if (val) {value = val; }
			       return parseFloat(value);
		    },      
      },
    ]
});

![sltevl 1](https://user-images.githubusercontent.com/2073226/48443591-8f914c00-e789-11e8-8f13-20b506edce50.png)

**Comment by olifolkerd** [comment]
Hey @hramenko 

Sorry to hear you are having trouble there.

Thankyou for the detailed error report there, it looks like there is an unusual interaction between the column calculations and multi level grouping.

I will work on a fix for that this evening.

Cheers

Oli :)

**Comment by hramenko** [comment]
Oli. This bug also produces a double footer.
Check this https://codepen.io/hramenko/pen/vQGpeb just click/dblclick on first group header

**Comment by olifolkerd** [comment]
Hey @hramenko 

I have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)
