### ISSUE TITLE
Error when use datatree and groupBy

### ISSUE THREAD

**Issue by dasio86** [olifolkerd/tabulator#1585]
**Describe the bug**
I'm using the last version in beta and i setup the beatuful datatree Option. But when i set also the groupBy i receive this errore:

`Uncaught (in promise) TypeError: Cannot read property 'children' of undefined
    at tabulator.js:11231
    at Array.forEach (<anonymous>)
    at DataTree.getRows (tabulator.js:11230)
    at RowManager.refreshActiveData (tabulator.js:3541)
    at RowManager._setDataActual (tabulator.js:2765)
    at tabulator.js:2718
    at new Promise (<anonymous>)
    at RowManager.setData (tabulator.js:2700)
    at Tabulator._setData (tabulator.js:7099)
    at Tabulator.setData (tabulator.js:7050)`

**Tabulator Info**
  Version 4.1.2

` window.tabella_apparati = new Tabulator("#tabella_apparati", {
        height:$(window).height()-200,
        dataTree:true,
        dataTreeStartExpanded:true,
        dataTreeBranchElement:true,
        dataTreeChildIndent:20, 
        layout:"fitData",
        groupBy:"sede",
        columns:[
        
        {title:"Contratto", field:"contratto", }, //never hide this column
        {title:"Cliente", field:"cliente",},
        {title:"Sede", field:"sede" }, //hide this column first
        {title:"Gruppo", field:"gruppo"},
        {title:"Tipologia", field:"tipologia", align:"center"},
        {title:"Marca", field:"marca"},
        {title:"Modello", field:"modello", topCalc:"count"},
        {title:"Numero Seriale", field:"numero_seriale"},
        {title:"", field:"id",visible:false},
        ],
            tableBuilding:function(){
                    carica_apparati();
            },
    });`

**Comment by olifolkerd** [comment]
Hey @dasio86 

Thanks for getting in touch,

Sorry to hear you are having issues, that is definitely a bug there. it should be a quick fix.

I am doing a patch release later this week so i will include a fix for that then.

Cheers

Oli :)

**Comment by zokrad** [comment]
found a quick fix for this

https://github.com/olifolkerd/tabulator/blob/20b33b3dec9d63f7b7bbd55e2af208482bcab81b/dist/js/tabulator.js#L3503

move `case "group"`  below `case "tree"`

https://github.com/olifolkerd/tabulator/blob/20b33b3dec9d63f7b7bbd55e2af208482bcab81b/dist/js/tabulator.js#L3528

**Comment by olifolkerd** [comment]
Hey @dasio86 

I have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)
