### ISSUE TITLE
`select` editor with `input`

### ISSUE THREAD

**Issue by johnrichardrinehart** [olifolkerd/tabulator#1588]
I'd like to be able to type a custom value into a cell for which the editor is of the `select` type. This would be helpful in cases for which *most* of the cells have one of a few values. This would require making modifications to the `select` editor. I'm imagining an option that could be passed to the `editorParams` which is `customText: true` or analogous.

A reasonable approximation would be to modify the `autocomplete` editor to show a dropdown during editing, which is filtered as the user types in the cell. Similarly, I'm imagining an option that could be passed to the `editorParams` which is `dropdown: true` or analogous.

I'd like to help implement this feature. Please advise as to which of the two options (modifying the 'select' editor or the `autocomplete` editor) you'd like to pursue.

**Comment by olifolkerd** [comment]
Hey @johnrichardrinehart 

Im afraid i dont follow you, the autocomplete editor is already capable of doing what you describe.

By setting the ***freetext*** property in the editor params the user can either select from the list or use the custom value they have entered:

```js
{title:"Example", field:"example", editor:"autocomplete", editorParams:{
    freetext:true, //allow the user to set the value of the cell to a free text entry
    values = [], //array of possible values
}}
```

If you would like the user to be presented with a list of all the preset values when empty you can use the ***showListOnEmpty*** property:

```js
{title:"Example", field:"example", editor:"autocomplete", editorParams:{
    showListOnEmpty:true, //show all values when the list is empty,
    freetext:true, //allow the user to set the value of the cell to a free text entry
    values = [], //array of possible values
}}
```

Please let me know if i have misunderstood you there.

Cheers

Oli :)

**Comment by johnrichardrinehart** [comment]
Oli, that was exactly what I was looking for. Thanks a lot for your help.

I should have read the documentation more clearly.
