### ISSUE TITLE
Support for Labels/Tags as value

### ISSUE THREAD

**Issue by kdabir** [olifolkerd/tabulator#1589]
First off, great project. It really saves a lot of time. Kudos for making such a great library open source.

**Problem**
When I need to display some Array-like data in a column (classic example is labels or tags of an item),  I could not find any out-of-the-box formatter for doing so in Tabulator. Also the sorting does not work on such columns. 

I would actually like to filter columns by tags/labels. Can't see how to do that.

**Additional context**
Something like Gmail labels or like following from Github Issues from this project itself, which shows issue labels. I understand this(screenshot) is not really a table, however it helps to visualize the idea. 

![image](https://user-images.githubusercontent.com/735240/48473011-8782ec00-e81d-11e8-8fee-cabae6725b6e.png)

Currently this is how it appears (without specifying any formatter)
```
data: {... "tags":["a", "b", "c"]...}
columns: {title:"Tags", field:"tags", width:350},
```

![image](https://user-images.githubusercontent.com/735240/48473581-c49bae00-e81e-11e8-81ca-32917f6713c8.png)

**Comment by olifolkerd** [comment]
Hey @kdabir 

Thanks for getting in touch, it is great to hear you are enjoying using Tabulator!

That particular formatter is not currently built in, but will be coming in the next release.

In the mean time it would be easy to write a custom formatter to use for something like that:
```js
//define custom formatter function
var tagFormatter = function(cell, formatterParams, onRendered){
    var vaules = cell.getValue();
    var tags = "";

    if(values){
        values.forEach(function(value){
             tags += "<span class='tag'>" + value + "</span>";
        });
    }
    return tags;
}

//then assign to a column in your column definition
{title:"Tags", field:"tags", formatter:tagFormatter , width:350},
```

you could the use some CSS to style the ***tag*** class however you like to make them look like square badges.

I hope that helps,

Cheers

Oli :)

**Comment by kdabir** [comment]
Hey, Thanks for the response. 

I figured that with custom formatter I could make the field look like tags, However, I called it a feature request because filtering and sorting is still needs to based on tags, which does not work right now

**Comment by olifolkerd** [comment]
Hey @kdabir 


### Sorting

There is already a built-in sorter for sorting arrays, the ***array*** sorter:

```js
{title:"Tags", field:"tags", sorter:"array", sorterParams:{
    type:"sum",
}}
```

in the ***sorterParams*** you need to set the ***type*** property to tell the sorter how to aggregate the array data to a sortable value, full details can be found in the [Sorter Documentation](http://tabulator.info/docs/4.1/sort)

### Filtering

If you are filtering using the ***addFilter*** function, you just need to pass in a custom filter function:

```js
function customFilter(data, filterParams){
    //data - the data for the row being filtered
    //filterParams - params object passed to the filter

    return data.tag.indexOf(filterParams.searchTerm) > -1, true if it passes the filter.
}

table.setFilter(customFilter, {searchTerm:"a"});
```

If you are using header filters then you use a custom ***headerFilterFunc***:
```js
function customHeaderFilter(headerValue, rowValue, rowData, filterParams){
    //headerValue - the value of the header filter element
    //rowValue - the value of the column in this row
    //rowData - the data for the row being filtered
    //filterParams - params object passed to the headerFilterFuncParams property

    return rowValue.indexOf(headerValue) > -1, true if it passes the filter.
}

//column definition object in table constructor
{title:"Age", field:"age", headerFilter:"input", headerFilterFunc:customHeaderFilter}
```


I hope that helps,

Cheers

Oli :)

**Comment by kdabir** [comment]
@olifolkerd Wow, this certainly does help. And provided me good starting point. Also, I realize now that there is no natural way to sort column by tags. But I want to just filter by given tag. Thanks again for answering.

**Comment by Igloczek** [comment]
Not strictly related to this issue, but I want to leave this here since it's undocumented but useful when working with array-type data like tags.

If you need to set multiple filters at once and one of them is a custom function, it gets tricky, the documentation only mentions `setFilter(customFunction, customParams)` for single filters. So you might think you need to call `addFilter` / `removeFilter` manually to combine it with others.

But instead, you can do this:

```js
table.setFilter([
  { field: "status", type: "=", value: "active" },
  {
    field: customFunction,  // ← this is your custom filter function
    type: customParams      // ← this becomes the filterValue passed into the function
  }
]);
