### ISSUE TITLE
Place a checkbox in the header?

### ISSUE THREAD

**Issue by jbasemvd** [olifolkerd/tabulator#159]
First of all I must tell you that I really like Tabulator. It's so flexible it's almost too easy.

Here is my question:

I use a formatter to create a column of checkboxes. Is there a way to also place a checkbox in the header of that column so I can then use an onclick to select all rows?

Also I'm using pagination so is there a way to include the rows not on the current page? In other words when I click the checkbox in the header I get the entire table not just the visible rows.

Thanks in advance.

**Comment by olifolkerd** [comment]
Hey,

Thanks, it is always great to hear people are enjoying using Tabulator!

You can pass HTML into the ***title*** property and then bind onto that
```js
$("#example-table").tabulator({
    columns:[
        { title:"<input id='select-all' type='checkbox'/>"},
    ],
});

$("#select-all").on("change", function(){
    if($(this).is(":cheked")){
        $("#example-table").tabulator("selectRow");
    }else{
        $("#example-table").tabulator("deselectRow");
    }
});
```
At the moment selection is limited to visible rows only. in next months release i will be looking to expand this functionality so will probably have a new property that lets you decided if the selection is for the current view od data or all data in the table.

**Comment by jbasemvd** [comment]
Thanks Oli I'll give that a try. The ability to select all the items in a table would be great in my case because I have very little space on this page and need two tables. A table could easily have 1000 rows so going through each page selecting would be very time consuming.

I appreciate your help.

**Comment by cemmons** [comment]
Row Selection Changed Event doesn't mark the rows that were deselected? 

I'm doing this code 

`$("#gridStrategyRoute").tabulator({
            height: "300px",
            fitColumns: false,
            colResizable: false,
            columns: strategyRouteCols,
            rowSelectionChanged: function (data, rows) {
                var bool;
                if ($('#select-all').is(":checked")) {
                    bool = true;
                } else {
                    bool = false;
                }
                $.each(data, function (key, value) {
                    $("#chk_" + value.rotCode.trim()).prop('checked', bool);
                });
            }
        });`

It only works when a select all the rows, but data is empty when I deselect all rows.

**Comment by olifolkerd** [comment]
Hi Cemmons,

the ***selectionChanged*** event only passes the currently selected rows in its data, when you deselect all it means there are no rows selected and so it is correct that the data is empty in this case,

i would suggest that you deselect all the row selection checkboxes on a ***selectionChanged*** event and then reselect the ones in the array.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hi Cemmons,

I have just upgraded the row selection features to allow for selection persistence when sorting, filtering and paging data.

More information can be found [here](http://olifolkerd.github.io/tabulator/docs/#selectable)

Cheers

Oli

**Comment by cemmons** [comment]
Hi, how are you?

I'm trying to do the select all feature but with a custom checkbox selection, not the selectRow function..

Adding my fiddle here:

https://jsfiddle.net/cemmons/6fghegn4/2/


So this works, I can select all rows on header click, using the updateData function, but this data object is 15 or 16 rows, my original data is 330 rows.

I use progressive rendering so I have 20 rows loaded on each scroll, when I do the header click, the updateData just breaks.. It takes too long to update and my browser crashes.

I have the select all function in the on click event of the checkbox.. and on the renderComplete event of the tabulator.

Any help or pointer into a better way to achieve this functionality?

**Comment by snehilameta** [comment]
Even though the hack mentioned by Oli works in essence, it doesn't overrides the default sort action associated with the column header. 
               So each time the checkbox is checked/unchecked the table is sorted again in descending/ascending order alternatively.

        Can anyone describe an easy way to add a checkbox on the header which when clicked doesn't trigger the sort event on column ?

**Comment by olifolkerd** [comment]
you need to use a ***stopPropagation*** call on the click event on the input to stop this
