### ISSUE TITLE
"Out of Stack Space" error when using rowcomponent function getIndex

### ISSUE THREAD

**Issue by phunksta** [olifolkerd/tabulator#1590]
Given a Tabulator with setup such as:

```javascript
                var table = new Tabulator("#example-table", {
                    ajaxURL: "Brand",
                    columns: [
                        { title: "BrandId", name: "BrandId" },
                        { title: "BrandName", name: "BrandName" }
                    ],
                    index: "BrandId",
                    rowClick: function (e, row) { //trigger an alert message when the row is clicked
                        var rowIndex = row.getIndex();
                        alert(rowIndex);
                    },
                    ajaxRequestFunc: TabOd.queryOdata
                });
```
The line in rowClick calling row.getIndex() causes a javascript error:
```
SCRIPT28: Out of stack space
```
Tabulator Version 4.1
The expectation was I could echo the BrandId as an alert, or whatever the 'index' column was for a given table.

Windows 10
Microsoft Edge 42.17134.1.0

**Comment by olifolkerd** [comment]
Hey @phunksta 

Sorry to hear you are having issues,

You definitely shouldn't be getting that error.

The ***getIndex*** function will return the value in the rows data that is defined as the index, by default this is the "index" property. This should be a unique property per row used to lookup the row.

to change this to a different field you can use the ***index*** field in the table constructor:

```js
var table = new Tabulator("#example-table", {
    index:"age", //set the index field to the "age" field.
});
```

in your case you may want to use the ***getData*** function:
```js
alert(row.getData().BrandId);
```

I hope that helps,

Cheers,

Oli :)

**Comment by phunksta** [comment]
Hi Oli, thanks for the feedback.

Unfortunately, it doesn't help, as the index has been defined dynamically, and I'm relying on tabulator to return it via this function, depending on how it was set up in the constructor.

I can't therefore use row.getData() without some sort of back reference to which field is required.

You closed my issue, is this going to be a 'won't fix'? As if so I will need to build a patch of my own to get around this. I'm embarking on quite a major project and tabulator is our trial and favourite table library at the moment for the project.

**Comment by olifolkerd** [comment]
Hey @phunksta 

I close all comments if i dont get a response to users after a period of time, if you are still experiencing issues then i am happy to reopen it for you.

Could you created a JS Fiddle or code pen with a working example of your issue, as i am unable to replicate it my end which makes it hard to track down any potential issue.

Cheers

Oli :)

**Comment by phunksta** [comment]
In trying to make a JS Fiddle for this, I think I found the root of the problem.
I was setting the index property of the Tabulator at construction time, but following that it was being unset somehow. I am trying to track down when/why this happens, but inspecting the tabulator elements I see the index property is 'undefined'.

For whatever reason under those conditions, Tabulator core code enters an infinite loop and runs out the stack space.
If I find anything more on this I will post it up here, but for the purposes of this issue I think it could be closed as Tabulator only misbehaves after being damaged.
