### ISSUE TITLE
Table Header Background not changing

### ISSUE THREAD

**Issue by HappyCustomers** [olifolkerd/tabulator#1597]
**Describe the bug**

when i apply the following CSS property, the tabulator header is not reflecting the background color in chrome

#customer-interactions .tabulator-header {
    background-color:#333;
    color:#fff;
}

**Tabulator Info**
Version 4.1

**To Reproduce**
1. Add the HTML Code 
<div id="customer-interactions"></div>
2. Add the following CSS
#customer-interactions .tabulator-header {
    background-color:#333;
    color:#fff;
}

**Expected behavior**
The header background color has to change

**Screenshots**
![image](https://user-images.githubusercontent.com/34091588/48687919-aef50280-ebe9-11e8-9ebe-8841121b3380.png)

**Desktop 
Windows 10
Chrome 
Version 70.0.3538.102 (Official Build) (64-bit)

**Comment by Rodbjartson** [comment]
Try adding !important after the color code; #333 !important;

**Comment by Rodbjartson** [comment]
Try
```
#customer-interactions .tabulator-header .tabulator-col {
                background: #cce2ff !important; }
```
