### ISSUE TITLE
row number Formatter with custom formatter

### ISSUE THREAD

**Issue by gayathriramprasath** [olifolkerd/tabulator#1598]
Hi,
I want to get background color to rownum formatter to my code? I used the custom formatter below
var nullFormatter = function(cell, formatterParams){
        cell.getElement().style.backgroundColor = "red";
 };

I'm using columns array like this {formatter:"rownum", headerSort:false, frozen:true, width:30, minWidth:30 },

how can I do the two with in single formatter

**Comment by olifolkerd** [comment]
Hey @gayathriramprasath 

Thanks for getting in touch,

You can only apply one formatter to a column, so you would have to use a custom formatter that does both, something like this:

```js
var customFormatter = function(cell, formatterParams, onRendered){
	cell.getElement().style.backgroundColor = "red";
	return this.table.rowManager.activeRows.indexOf(cell.getRow()._getSelf()) + 1;
}
```

I hope that helps,

Cheers

Oli :)
