### ISSUE TITLE
Download xlsx file formatting parameters

### ISSUE THREAD

**Issue by pPratik7** [olifolkerd/tabulator#1599]
Hi oli,
Sorry for the question but I couldn't figure it out how to do it.
I want formatted xlsx file such that I can change row width, column width or use some table from format table as option...
I also want to add hyperlinks in xlsx...I did it by
downloadDataFormatter: function (data) {
     data.forEach(function (row) {
      row.field =  "=HYPERLINK(\" https://......\" , \""link"\")";
                                })
                             return data;
                            },
But still I need to click on that cell to make it hyperlink...I will be thankful if you can help in this direction

**Comment by olifolkerd** [comment]
Hey @pPratik7 

Im afraid at the moment you cannot set the width on columns in the xlsx downloader, to do this you would need to implement your own xlsx downloader.

the same also goes for clickable hyperlinks, im afraid.

I will look at adding these improvements to the roadmap.

Cheeers

Oli :)
