### ISSUE TITLE
Set data using Ajax (POST parameters)

### ISSUE THREAD

**Issue by ECardenal** [olifolkerd/tabulator#16]
First, thank you for this great library :trophy:

I need to pass a few parameters to my Ajax data source via POST. Now, I can "compose" the URL with the parameters and perform a GET request, but I find it a bit "inelegant", and maybe it will collide with the promised Ajax pagination...

May I pass the parameters with POST instead ?

  	e.g:  _data: { offset: "0", limit: "100", text1: "SearchText1", text2: "SearchText2",},_

thanks

**Comment by olifolkerd** [comment]
Hey,

At the moment the only way to pass parameters is in-line with the request url, but you raise a good point.

I will add a second parameter to the ***setData*** to allow you to pass parameters separately from the url.

I should be able to get this setup this evening.

**Comment by ECardenal** [comment]
Great!

**Comment by olifolkerd** [comment]
You can now pass request parameters to the ***setData*** function using a object with key value pairs.

```js
$("#example-table").tabulator("setData","http://www.getmydata.com/now", {key1:"value1", key2:"value2"});
```

**Comment by ECardenal** [comment]
:smile::thumbsup: thanks a lot!

**Comment by olifolkerd** [comment]
Hi Guys,

I have just launched a new documentation site for tabulator, check it out:
http://olifolkerd.github.io/tabulator/

Oli

**Comment by nayaz22** [comment]
Hi,
I have a api that i'm using to fetch data to tabulator, but i want that api to be POST request not GET when i used POST request it throws Ajax load error statusText: "Method Not Allowed".

Help me in this plzz.
