### ISSUE TITLE
Delete rows doesn't update pagination controls

### ISSUE THREAD

**Issue by jbasemvd** [olifolkerd/tabulator#160]
If I have 5 pages of data and I delete 1 entire page using deleteRow the pagination control does not update to reflect the new number of pages. Is this by design or am I not doing something correctly?

My code is like this:

$("#passedTable").tabulator("deleteRow", data._index);
$("#passedTable").tabulator("redraw", true);

Thanks

**Comment by olifolkerd** [comment]
I think you have found a bug there, it should be updating the page numbers, but that doesn't seem to be happening when rows are added/deleted.

Are you using local or remote pagination? could you post a copy of your Tabulator constructor object so i can replicate the scenario fully.

I should be able to get a fix in for this tomorrow evening.

Cheers

Oli

**Comment by jbasemvd** [comment]
Here is the code I'm using. Thanks for the help.

		  $("#passedTable").tabulator({
			  selectable: false,
			  pagination: "local",
			  height: "214px",  // Table height
			  fitColumns: true, // Fit columns to width of table
			  // Call JWS
			  ajaxURL: "http://restrictions-dev.cookgroup.nao/cgi-bin/jws?lots.jws.json.sub" + lots,
			  //Define Table Columns
			  columns: [{
				  title: "LOT",
				  field: "lot",
				  sorter: "string",
				  width: 150
			  }, {
				  title: "RPN",
				  field: "rpn",
				  sorter: "string",
				  align: "right"
			  }, {
				  title: "GPN",
				  field: "gpn",
				  sorter: "string",
				  align: "right"
			  }, {
				  title: "WHO",
				  field: "who",
				  sorter: "string",
				  align: "right"
			  }, {
				  title: "DATE",
				  field: "date",
				  sorter: "date",
				  align: "right"
			  }, {
				  title: "HOLD TYPE",
				  field: "holdtype",
				  sorter: "string",
				  align: "right"
			  }, {
				  id: "del-row",
				  title: "DELETE",
				  field: "delete",
				  align: "center",
				  sortable: false,
				  formatter: "buttonCross", // Insert the X at the end of each row
				  // Define what to do when the X's are clicked
				  onClick: function(e, cell, val, data) {
				  	$("#passedTable").tabulator("deleteRow", data._index); // Delete row.
				  	$("#passedTable").tabulator("redraw", true); // Redraw table.
				  },
			},],
		});

**Comment by olifolkerd** [comment]
Looks like this bug is going to take a little more work to fix, as there are a number of functions that share the same issue. i will have it all sorted this weekend :D

**Comment by jbasemvd** [comment]
Thanks for the update. I'll wait to hear from you.

**Comment by olifolkerd** [comment]
Hey,

The fix for this is now in!

Thanks for letting me know about it.

Cheers

Oli
