### ISSUE TITLE
Add children to row

### ISSUE THREAD

**Issue by Bazsi96** [olifolkerd/tabulator#1600]
Hi!
My name is Balázs. I'am really enjoy to use Tabulator.
In my site I would like to use tree view data set, but when I instancing the Tabulator I don't know, which rows has children. So is there any way, to add children to row?

I found updateRow() function, and I use this `tabulator_table.updateRow(11760, {_children:[{name:"bob",id:"12"},]});` and the promise run resolved, but children doesn't added.

Have a good day!
Balázs

**Comment by olifolkerd** [comment]
Hey @Bazsi96 

Thanks for your kind words.

At the moment children can only be added when the data is loaded through the ***setData*** or ***replaceData*** function, so i would suggest that you retrieve all the data from your table using the ***getData*** function, add the children, then set the table data again.

The ability to change the number of children by updating the children object will be coming in the next release.

Cheers

Oli :)
