### ISSUE TITLE
When a new column is added, hidden columns become visible.

### ISSUE THREAD

**Issue by curioustolearn** [olifolkerd/tabulator#1601]
**Describe the bug**
When I hide a column using `table.hideColumn('age')` it hides the `age` column as expected.
Then, if I add another column using `columns.push(newcol)` followed by `table.setColumn(columns)`, the new column is added (as expected). *But* the `age` column also becomes visible again.

**Tabulator Info**
- Which version of Tabulator are you using?
4.1.2
- Post a copy of your construct object if possible so we can see how your table is setup. 
I am calling the code below in my Vue component. I am trying out the example in Tabulator quickstart documentation.

     `mounted(){
             //instantiate Tabulator when element is mounted
            this.tabulator = new Tabulator(this.$refs.table, {
                data: this.tableData, //link data to table
                columns: this.columns, //define table columns
                layout: 'fitColumns',
                layoutColumnsOnNewDatay: true,
                responsiveLayout: true,
                movableColumns: true,
            })
      },`

**Expected behavior**
Hidden columns should not show up automatically when changes are made to a table, unless explicitly requested by the user.

**Desktop (please complete the following information):**
 - Mac OSX 10.11.6
 - Chrome
 - Version 70.0.3538.102 (Official Build) (64-bit)

**Comment by curioustolearn** [comment]
First, thanks so much for creating Tabulator. I am hoping to use your library. 

I am using tabulator in a Vue component. Unfortunately, after I played around with it yesterday, I made some major changes to that code and now I cannot test it again. However, this is what I had in my Vue component. If this is not helpful, I will update the issue when I have had a chance to test it again in a few days. 

```
import Tabulator from 'tabulator-tables';
import { find as _find} from 'lodash';
import { findIndex as _findIndex} from 'lodash';


//define some sample data
 var tabdata = [
 	{id:1, name:"Oli Bob", age:"12", col:"red", dob:""},
 	{id:2, name:"Mary May", age:"1", col:"blue", dob:"14/05/1982"},
 	{id:3, name:"Christine Lobowski", age:"42", col:"green", dob:"22/05/1982"},
 	{id:4, name:"Brendon Philips", age:"125", col:"orange", dob:"01/08/1980"},
 	{id:5, name:"Margret Marmajuke", age:"16", col:"yellow", dob:"31/01/1999"},
 ];

var columns = [ //Define Table Columns
	 	{title:"Name", field:"name", width:150},
	 	{title:"Age", field:"age", align:"left", formatter:"progress"},
	 	{title:"Favourite Color", field:"col"},
	 	{title:"Date Of Birth", field:"dob", sorter:"date", align:"center"},
];

export default {
    data: function() {
        return {
            tabulator: null, //variable to hold your table
            columns: columns,
            tableData: tabdata, //data for table to display
        }
    },

    methods: {
        changedata(){
            let res = _find(this.tableData, (val) => {
                return val.age == "42";
            })
            let idx = _findIndex(this.tableData, (val) => {
                return val.age == "42";
            })
            res.age = "32";
            this.tableData.splice(idx, 1, res)
            this.tabulator.replaceData(this.tableData);
        },
        addcolumn() {
            let newcol = {title: "NewCol", field: "grade", align: 'center'}
            this.columns.push(newcol);
            this.tabulator.setColumns(this.columns);
            this.tabulator.redraw(); // so that there isn't an empty column after hide.
        },
        hideage() {
            this.tabulator.hideColumn('age')
            this.tabulator.redraw(); // so that there isn't an empty column after hide.
        }
    },

    mounted(){
        //instantiate Tabulator when element is mounted
        this.tabulator = new Tabulator(this.$refs.table, {
            data: this.tableData, //link data to table
            columns: this.columns, //define table columns
            layout: 'fitColumns',
            layoutColumnsOnNewDatay: true,
            responsiveLayout: true,
            movableColumns: true,
        })
    },
}
```




> Hey @curioustolearn
> 
> Thanks for getting in touch, sorry to hear you are having issues.
> 
> Could you post a copy of your full table constructor object, or a js fiddle so we can accuratly replicate how your table is setup for testing.
> 
> Cheers
> 
> Oli :)

**Comment by olifolkerd** [comment]
Hey @curioustolearn 

The issue is because you are pushing your original column definition back into the table with the new column, so the original visibility state of the column is being used.

The correct approach would be to use the ***addColumn*** function:

```js
table.addColumn({title:"New Col", field:"new"}, true, "age");
```
For more information see the [Column Setup Documentation](http://tabulator.info/docs/4.1/columns#add)

Cheers

Oli :)

**Comment by curioustolearn** [comment]
> Hey @curioustolearn
> 
> The issue is because you are pushing your original column definition back into the table with the new column, so the original visibility state of the column is being used.
> 
> The correct approach would be to use the _**addColumn**_ function:
> 
> ```js
> table.addColumn({title:"New Col", field:"new"}, true, "age");
> ```
> 
> For more information see the [Column Setup Documentation](http://tabulator.info/docs/4.1/columns#add)
> 
> Cheers
> 
> Oli :)

Thanks so much. I should have realized that. Sorry for wasting your time.
