### ISSUE TITLE
datatree add child

### ISSUE THREAD

**Issue by aklaver** [olifolkerd/tabulator#1603]
**Is your feature request related to a problem? Please describe.**
Not a problem but a known limitation:
http://tabulator.info/docs/4.1/tree
"Child Rows
At the moment child rows can only be set when data is loaded into the table, changing the number of rows in the _children property after the table has rendered will not alter the number of children in the table.

**Describe the solution you'd like**
The ability to add child records on the fly w/o having to reload the table.

**Describe alternatives you've considered**
Currently using setData() to reload the table.

**Comment by olifolkerd** [comment]
Hey @aklaver 

You are in luck, this is coming in the next release!

Cheers

Oli :)

**Comment by aklaver** [comment]
Should have asked before, which release is that? I see 4.1.3 is out, but I do not see anything about adding child records. Am I not looking in the correct place or is this coming in the next major release e.g. 4.2?

**Comment by olifolkerd** [comment]
Hey @aklaver 

That will be the 4.3 release.

Tabulator uses the [Semantic Versioning Scheme](https://semver.org/) so major releases (such as 4.0.0) will only happen when there are wholesale changes to the codebase or massive breaking changes (ie, removal of jQuery, significant code refactors etc), sets of new individual features are included in minor releases (such as 4.1.0) and bug fixes will occur on patch released (4.1.1)

I hope that makes sense.

Cheers

Oli :)

**Comment by aklaver** [comment]
Got it.

**Comment by jmtalves** [comment]
hi, 
I need to create a table with editable fields (property "editor") only in hierarchy "tree" and allow to add new rows ("children") on any node. Is this already possible? or only in the next versions?

**Comment by aklaver** [comment]
From what I understand questions should be asked on StackOverflow:

https://stackoverflow.com/search?q=tabulator

**Comment by jmtalves** [comment]
Okay, I put the doubt here because it seemed like a related topic.

**Comment by olifolkerd** [comment]
This has been added to the 4.2 branch which will be released on monday 

Cheers

Oli :)

**Comment by drunkskunk** [comment]
I cuurently have version 4.2 in my device, how do i add children nodes after the table is loaded?

**Comment by olifolkerd** [comment]
you update the _children array of the parent

**Comment by manisha2108** [comment]
I was using 4.1.5 before.
As wished to use data tree and update children on fly upgraded to 4.2.
But facing issues. 
Promise is undefined.

**Comment by olifolkerd** [comment]
Hey @manisha2108 

Sorry to hear you are having issues.

Please create a new issue using the bug template, it will prompt you to provide all the info we need to fix the problem.

Cheers

Oli :)
