### ISSUE TITLE
Several space-separated classes don't work in column definition

### ISSUE THREAD

**Issue by jgenyuk** [olifolkerd/tabulator#1605]
Version 4.1.3
Having space separated class names  in column definition cssClass option throws an error:

InvalidCharacterError: String contains an invalid character

Traced this to element.classList.add in Column.prototype._buildColumnHeader and  Cell.prototype._configureCell
Not sure if this is a code or documentation issue.

**Comment by jgenyuk** [comment]
Got it. I've hacked your code for now but it would be great if you add this because I'm trying to upgrade from version 3 where it worked. Thanks for your lightning-quick response!

Julia

**Comment by olifolkerd** [comment]
Hey @jgenyuk 

No problem, it happened as a result of removing jQuery from the code in 4.0 which handled that for me. it should be a quick fix in the next release.

Cheers

Oli :)

**Comment by puffsnow** [comment]
Hi @olifolkerd ,
This problem may be solved in https://github.com/olifolkerd/tabulator/pull/1625. I believe you can close this issue.
