### ISSUE TITLE
dataTree and row search

### ISSUE THREAD

**Issue by aklaver** [olifolkerd/tabulator#1607]
**Is your feature request related to a problem? Please describe.**
The problem I am having is that tbl.getRow() or tbl.searchData() do not see child rows in the table. Not sure if this is a bug, a feature to be requested or maybe something that is coming in the next release. Figured I would ask.

**Describe the solution you'd like**
Be able to use tbl.getRow() or tbl.searchData() to find child rows.

**Describe alternatives you've considered**
I have not figured out any alternatives yet.

**Comment by aklaver** [comment]
Well the use case is to find a specific child row.  I figured out the getTreeChildren() method off the parent records. That got me to wondering if that could be an option to getRow() and searchData(), something like getRow(children)? That would then automatically use getTreeChildren to traverse the child rows of any parent that has them.

**Comment by ray007** [comment]
Hmm, sorting with 1 child row at least seems to work correct.
I would also have expected for there to be an index by id for all rows including childrows.
But the row-manager does not seem to know about childrows at all.
Is this expected to change sometime?

**Comment by scott-oliver** [comment]
Is there a solution for getting the grand and great grand children of a row (without the need for looping)?

**Comment by dynamicapps** [comment]
I'll chime in on this one.  My child rows are just as important as my parent rows as they're all just data at different levels of the hierarchy.  My particular use case for finding rows is to persist the expand/collapse state.  I was surprised when getRow(index) didn't find child rows.
John

**Comment by r4cker** [comment]
I use this function to search for a pseudo row in data Tree

```
function findRowInDataTree(id, rows) {
		for (let row of rows) {
			if (row.getIndex() == id) {
				return row;
			}
			var children = row.getTreeChildren();
			// Check for child rows in the data tree
			if (children && children.length > 0) {
				let foundRow = findRowInDataTree(id, children);
				if (foundRow) {
					return foundRow;
				}
			}
		}
		return null;
}
```
