### ISSUE TITLE
Multi-select with CTRL/CMD

### ISSUE THREAD

**Issue by gillez** [olifolkerd/tabulator#1609]
Hi Oli,

I'm loving Tabulator but have a request which is similar to #1425.  That' issue is now closed and the fix that it adds is welcome but only really addresses the SHIFT-click behaviour, not CMD/CTRL-click.

When selectable is set to true, the current behaviour is that clicking on rows toggle them on and off. In my opinion, this should be the expected behaviour (for me at least)  only when CTRL or CMD are pressed.  With no modifiers I think clicking on an item should select only that row and turn others off (like with selectable=1). 

This is like a combination of selectable=true and selectable=1.  I believe this is fairly standard behaviour in many apps on the desktop and in Windows/AppOS generally (the current behaviour is of course great for mobile where CTRL-click is not available).

Is there an option for this that I'm missing in Tabulator?

Regards,
Giles

**Comment by olifolkerd** [comment]
Hi Giles,

Thanks for your feedback, unfortunately depending on the grid system people have used before Tabulator they all have their own view on what the "standard" behaviour is in this situation (in truth i have probably received about 30 different requests for this with each of them having a different definition of standard).

The honest truth is that there is no standard. Tabulator implements two of the most popular methodologies. if you would like to add additional functionality then i would happily accept a pull request. 

the ***selectableRangeMode*** option allows the user to choose selection modes so if you added another option for this property then i would be happy to consider it.

Cheers

Oli :)

**Comment by gillez** [comment]
Hi Oli,

Thanks for the reply.  I have implemented the behaviour that I want by setting selecatable=highlight and handling selection in the rowClick event.  This was straightforward and all works great thanks to the awesome hooks and functions provided by Tabulator.  It also allowed me to implement the dynamic-selectable behaviour that I asked about in #1610.

This all works fine for me.  However, I would be happy to incorporate it into selectableRangeMode and submit a pull request if you would like this.  Please let me know.

Thanks,
Giles
