### ISSUE TITLE
Keep selected row after "setData"

### ISSUE THREAD

**Issue by leonardorame** [olifolkerd/tabulator#161]
Hi Oli, I would like to know if there's way to do this with Tabulator. 

My grid has the property `selectable: true`. What I want to do is:

1. Select a row. 
2. Open a dialog and edit the data selected in the row.
3. After editing call `.tabulator("setData")` to refresh the grid and keep the original row selected.

What I'm looking for is how to solve point number 3. What happens now is when I refresh the grid, the selected rows aren't selected anymore.

Regards,
Leonardo.

**Comment by olifolkerd** [comment]
He Leonardo,

If you are only editing a row, then you can use the ***updateRow*** function to update that row in the table without loading all the data again:

```js
$("#example-table").tabulator("updateRow", 1, {id:1, name:"bob", gender:"male"});
```

Or alternatively you can use the ***updateData*** function to update multiple rows of data
```js
$("#example-table").tabulator("updateData", [{id:1, name:"bob", gender:"male"}, {id:2, name:"Jenny", gender:"female"}]);
```

See the [Editing & Manipulating Data Documentation](http://olifolkerd.github.io/tabulator/docs/#manipulating-data) for full details.

To answer your third point you could achieve this by using the ***getSelectedData*** function before calling the ***setData*** function, then after calling ***setData*** itterate through the array and call ***selectRow*** for each row:

```js
//get currently selected data
var selectedData = $("#example-table").tabulator("getSelectedData");

// load new data
$("#example-table").tabulator("setData", newData);

//select previously selected rows
selectedData.forEach(function(row){
    $("#example-table").tabulator("selectRow", row.id);
});
```

Let me know if that answers your question.

Cheers

Oli

**Comment by leonardorame** [comment]
Great. While looking at the code I wonder if this can't be added to the main tabulator. I mean, when the "selectable" property is set.

**Comment by olifolkerd** [comment]
Thanks for the idea,

In the case of the ***setData*** function, I would not be looking to add that as a default feature because the new data provided to the function could be a completely different set of data (for example a table with option buttons to load 4 sets of different data with the same format).

However i am expanding the selection functionality in the next release so i will look as adding it as an additional option as i can see that it could be useful in certain circumstances.

Cheers

Oli

**Comment by leonardorame** [comment]
Thanks I'm looking forward for the next release.

**Comment by olifolkerd** [comment]
Hi Cemmons,

I have just upgraded the row selection features to allow for selection persistence when sorting, filtering and paging data.

More information can be found [here](http://olifolkerd.github.io/tabulator/docs/#selectable)

Cheers

Oli
