### ISSUE TITLE
Event to call Ajax after creating a Row?

### ISSUE THREAD

**Issue by cemmons** [olifolkerd/tabulator#162]
Hi, great work with Tabulator.

I'm looking for a way to.. after typing values into a row, when I press enter or defocus from it.. calls an event that saves that data through ajax.

So far I have the rowAdded and cellEdited events.. but does events trigger after I create a row, so it sends null value data to my ajax.

Any thoughts?

**Comment by olifolkerd** [comment]
Hi Cemmons,

Thanks, its always great to hear people are enjoying Tabulator!

Im not sure i follow you there, the ***cellEdited*** only fires after you have edited a value in the row, not when the row is added. If you call your ajax function only in the ***cellEdited*** function then you should have no issues with null rows.

If you don't want to send the ajax request until all the cells have values in them, then can i suggest you iterate through the expected properties in the data object when it is passed to the ***cellEdited*** callback, checking if they are null, then only proceed to send the ajax request once all the expected properties have a value.

Does that answer your question or have i got the wrong end of the stick?

Cheers

Oli,

**Comment by cemmons** [comment]
Oh!! I didn't thought of that ... and that resolve my problem with the ajax call... thanks a lot.
