### ISSUE TITLE
IE 11 Create From Existing Table (4.1.3)

### ISSUE THREAD

**Issue by Alarich** [olifolkerd/tabulator#1621]
**Describe the bug**
When using IE 11 and Tabulator 4.1.3, creating from existing table runs into an issue. This issue is also present within Tabulator examples.

**Tabulator Info**
Latest version on Tabulator.info (4.1.3)

**To Reproduce**
1. Go to http://tabulator.info/examples/4.1#table-load with IE 11
2. Wait for ages.
3. Observe the broken output table.

**Expected behavior**
A functional table

**Screenshots**
http://prntscr.com/lqjvoc

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Internet Explorer 11
 - Version 11.665.16299.0

**Additional context**
Error message: Unable to get property 'name' of undefined or null reference 
Location: HtmlTableImport.prototype._extractOptions
Line: if ((typeof attrib === 'undefined' ? 'undefined' : _typeof(attrib)) == "object" && attrib.name && attrib.name.indexOf("tabulator-") === 0) {

**Comment by olifolkerd** [comment]
Hey @Alarich 

Im afraid i cant replicate the issue, the example loads straight away and renders correctly.

I agree there appears to be an issue in the console (which i will look into) but it dosnt seem to have affected the render of the table in any way. 

In your example picture the table looks fine, am i missing something?

Cheers

Oli :)

**Comment by Alarich** [comment]
Hey @olifolkerd!

From the image you can see that the table is not sortable, I believe that is the only visual cue I can provide just from images. It is rendered, but not functional. There's also no drag handles etc, simply a styled div container.

I've tried on multiple PC's on IE11, so in theory it could just be my bad experience, but that seems strange.

**Comment by olifolkerd** [comment]
Hey @Alarich 

i have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)

**Comment by Alarich** [comment]
Thank you @olifolkerd :)
