### ISSUE TITLE
Using a period in field name silently breaks

### ISSUE THREAD

**Issue by mLuby** [olifolkerd/tabulator#1624]
**Describe the bug**
Using a field name with a period in it doesn't work.

**Tabulator Info**
- Which version of Tabulator are you using? **tabulator-tables@4.0.5**
- Post a copy of your construct object if possible so we can see how your table is setup
```json
{
  "columns": [{"title": "flattened.object.prop", "field": "flattened.object.prop"}],
  "data": [{"flattened.object.prop": 2}]
}
```

**To Reproduce**
1. use the JSON above
2. Error is where 2 should be it's blank.

**Expected behavior**
Cell value should be 2 not blank.

**Desktop (please complete the following information):**
 - OS: MacOS 10.13.6
 - Browser Chrome
 - Version 70

**Additional context**
Worth noting that replacing `.` with `_` fixes the problem.

PS this library is _awesome_—thanks! 🎉

**Comment by olifolkerd** [comment]
Hey @mLuby 

Thanks for getting in touch, 

This is not a bug but a feature. As the [Documentation](http://tabulator.info/docs/4.1/columns#field-nesting) describes, by default tabulator uses dot notation in field names to allow you to access data stored in nested data.

in this case it would be looking for the value in:

```js
{
    flattened:{
        object:{
            prop:2
        }
    }
}
```

You can disable this feature by setting the ***nestedFieldSeparator*** option to false in your table constructor:

```js
{
  nestedFieldSeparator:false,
  "columns": [{"title": "flattened.object.prop", "field": "flattened.object.prop"}],
  "data": [{"flattened.object.prop": 2}]
}
```

Which will result in your table working as you want.

Cheers

Oli :)
