### ISSUE TITLE
When using setPage on an AJAX Paginated Tabulator, Pagination Buttons disappear ignoring the paginationButtonCount

### ISSUE THREAD

**Issue by distraub** [olifolkerd/tabulator#1626]
In Tabulator 3.5

When I use the setPage parameter like this

$('#myTabulator').tabulator('setPage', 34)
The Pagination Buttons that are set on init disappear

like this :

{paginationButtonCount: 5}
Is there a way to set paginationButotnCount after init, or refresh them so they come back?

I found a way to fix this :

There appears to be a bug with AJAX Pagination. When tabulator calculates the current page this.page it is a string.

For example if I setPage to 3

In the setPageButtons function :

Math.min(parseInt(this.page) + o, this.max)
Adding parseInt fixes the issue, since it is concatenating this.page ("3") with o which happens to be 2, so if I have more than 32 pages it sets the number of page buttons that it generates to 32.

If you have that many page buttons there is a function that checks the width of the footer against the width of the page buttons span, if the page buttons span is larger, it hides it.

**Comment by distraub** [comment]
Hi Oli I will see if I can confirm it in 4.1
I haven't moved the project to 4 yet and it is large.

Although I did fix it in what I have pulled down, it was as simple as adding a parseInt call in one spot. I just wanted to let you know.

I can pull the repository down and make the change and submit a PR if you like.
Or I can just have it on my side until I upgrade to 4

Alex

**Comment by distraub** [comment]
Hi Oli,

I am closing this issue, it wasn't a bug. It was happening because I was accidentally passing a string to setPage, adding parseInt to the goto page control before I pass it in fixes the issue.

Alex

**Comment by olifolkerd** [comment]
Hey @distraub 

Thanks for letting me know. i will put in a tweak on the 4.2 release to allow it to handle string values too.

Cheers

Oli :)
