### ISSUE TITLE
Make `columns` optional

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#1628]
Feature request
Because `Tabulator` [expects a JSON encoded array of row objects](http://tabulator.info/docs/4.1/data#ajax-response) there is no need to fill `columns` parameter. I

t can be filled by next defaults:

if object response is 

    {"id":1, "name":"bob", "age":"23"}

the columns will be `id, name, age`
which can be expanded to 

    [ 
      { title: "id", field: "id" }, 
      { title: "name", field: "name" }, 
      { title: "age", field: "age" } 
    ]

This will allow to start even more easy

**Comment by olifolkerd** [comment]
Hey @KES777 

Thanks for your feedback, 

This option is already on the roadmap for the next release and has already been suggested in issue #1043

Cheers

Oli :)
