### ISSUE TITLE
Fill two tables with the same data?

### ISSUE THREAD

**Issue by jbasemvd** [olifolkerd/tabulator#163]
I'm using ajax to fill a table. I'd like to fill a second table with the same data without making the ajax call a second time. Is that possible? Thanks.

**Comment by olifolkerd** [comment]
Hey,

That is no problem at all, you just need to make an ajax request to get the data, then call the ***setData*** function on both of your tables:

```js
$.ajax({
	url: "path/to/data",
	type: "get",
	async: true,
	dataType:'json',
	success: function (data) {
		$("example-table1").tabulator("setData", data);  
		$("example-table2").tabulator("setData", data);
	},
});
```

Let me know if that helps

Cheers

Oli

**Comment by olifolkerd** [comment]
Did this answer your question?

**Comment by jbasemvd** [comment]
Yes sir that was the answer I was looking for and it works perfectly. Thank
you.
