### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#1630]
This [section](http://tabulator.info/docs/4.1/layout#virtual-dom) says:

>In order for the virtual DOM to function correctly you must ensure that the table element has a height you can either define this in the CSS for the element or set it using the height option in the table constructor, this can be set to any valid CSS value. If no height is set the table will revert to the standard DOM mode and try and render all rows at once, which will have a performance impact on tables with a large number of rows.

But [here](http://tabulator.info/docs/4.1/options#table) `virtualDOM` option does not mention this.
Probably you should put link from here to the paragraph above

You should put a note about the `true` is falling back to `false` when table has no `height`

**Comment by KES777** [comment]
Also typo [here](http://tabulator.info/examples/4.1#fittodatafill)

>resize the columns to fit thier data, 

`their`

**Comment by KES777** [comment]
Another typo [here](http://tabulator.info/docs/4.1/layout#virtual-dom-buffer)

>Disabling the Virtual DOM
f you need to disable virtual rendering

`if`

**Comment by KES777** [comment]
Links on the [page](http://tabulator.info/docs/4.1/format) are broken:

>The function accepts one argument, the CellComponent for the cell the tooltip is being generated for.

>The function accepts one argument, the RowComponent for the row being formatted.

CellComponent/RowComponent

**Comment by KES777** [comment]
[Typo](http://tabulator.info/docs/4.1/components#component-group)
>Get Element
The getElement function returns the DOM node for the gruop header.

`group`

**Comment by KES777** [comment]
[Typo](http://tabulator.info/docs/4.1/components#lookup)
>Any function that takes a component as an argument will also attempt to find that component based on the value provided if it is not a component iteslf

`itself`

**Comment by KES777** [comment]
Would be cool if Tabulator will support ability to change default value of **headerSort** property
[here](http://tabulator.info/docs/4.1/sort#header)

```javascript
	var table = new Tabulator("#example-table", {
		height      : "25rem",
		headerSort  : false, <<< disabled by default
		columns: [
			{ title: "",   field: "" },  <<< disabled
			{ title: "",   field: "" },  <<< disabled
			{ title: "",   field: "" },  <<< disabled
			{ title: "",   field: "", headerSort: true },   <<< enable
		],
	});
```
this would be much clear than:
```javascript
	var table = new Tabulator("#example-table", {
		height      : "25rem",
		columns: [
			{ title: "",   field: "", headerSort: false },  <<< disabled
			{ title: "",   field: "", headerSort: false },  <<< disabled
			{ title: "",   field: "", headerSort: false },  <<< disabled
			{ title: "",   field: "" },   <<< enable
		],
	});
```

**Comment by olifolkerd** [comment]
Hey @KES777 

Thanks for heads up on the typos, they should all be fixed now.

Thanks for your feedback on the ***headerSort*** property, but im going to keep it where it is for the time being. There are lots of users who want to disable sort on a per column basis.

Cheers

Oli :)

**Comment by KES777** [comment]
>but im going to keep it where it is for the time being.

I am not asking to change things. Just extend the behavior by allowing to change default value. Look into [example](https://github.com/olifolkerd/tabulator/issues/1630#issuecomment-445449517) more precisely ;-)

**Comment by KES777** [comment]
if you are not afraid I will continue to post issues about the DOC here.

[improve](http://tabulator.info/examples/4.1#fittodata)

your example shows table with data, but `source code` do not show how data are fetched into table.
Anther examples also hide this fact. ;)

**Comment by olifolkerd** [comment]
@KES777 

Please feel free to post any other issues you notice here. 

Cheers

Oli :)

**Comment by KES777** [comment]
[ambiguous](http://tabulator.info/docs/4.1/group#manage)
>Change the Header Formatter
>You can use the setGroupHeader function to change the header generation function for each group. This function has one argument and takes the same values as passed to the groupHeader setup option.

The `groupHeader` returns string to represent the group value, but here you return bool.
possibly the example should belongs to **Change the Start Open States** section

**Comment by KES777** [comment]
[Typo](http://tabulator.info/docs/4.1/components#component-cell)

>Navigation
You can navigat any direction around the table using the following functions:

`navigate`

**Comment by KES777** [comment]
[improve](http://tabulator.info/docs/4.1/modules#module-keybindings)

probably you should put a word about that `navPrev` is an action.

and use this action name when you extend keybindings actions:

```javascript
Tabulator.prototype.extendModule("keybindings", "bindings", {
    customActionName:"shift + 9",         // <<<< NOTICE HERE
});

The default list of keybinding actions and their functions can be extended:

Tabulator.prototype.extendModule("keybindings", "actions", {
    "customActionName":function(){ //delete selected rows      <<<<  NOTICE HERE
        var rows = this.table.getSelectedRows();

        rows.forEach(function(row){
            row.delete();
        });
    },
});
```

because http://tabulator.info/docs/4.1/keybindings does not show how to setup custom action's handler.

**Comment by KES777** [comment]
[Typo](http://tabulator.info/docs/4.1/modules#module-persistence)

>so that a users preferences can be remembered

`a user preferences` or `users preferences` ("a" may not be used with plurals, but I may wrong)

**Comment by KES777** [comment]
[Typo](http://tabulator.info/docs/4.1/tree#layout-colexp)
>Both options can take either an html string representing the contents of the toggl element

`toggle`

**Comment by KES777** [comment]
would be cool if you allow to copy links to paragraph like this:

![__](https://user-images.githubusercontent.com/799021/49755446-5e8d3400-fcc1-11e8-9115-b5a660460438.jpg)
https://metacpan.org/pod/Mojolicious#before_routes

![__](https://user-images.githubusercontent.com/799021/49755635-a3b16600-fcc1-11e8-9c23-76aae3ab7d0d.jpg)

https://mojolicious.org/perldoc#CONVENTIONS

**Comment by KES777** [comment]
[Typo](http://tabulator.info/docs/4.1/tree#component)
>tree events on that that row.

`that that` -> `that`

**Comment by KES777** [comment]
[ambiguous](http://tabulator.info/examples/4.1#row-formatter) at row formatter example:
```javascript
    rowFormatter:function(row, data){
        var element = row.getElement(),
        data = row.getData(),    
        width = element.element.offsetWidth,
```
if you get `data` as function argument why you define `data` again?

**Comment by KES777** [comment]
[Typo](http://tabulator.info/examples/4.1#formatters)
>buttonTick - displays a tick icon on eac row (for use as a button)
buttonCross - displays a cross icon on eac row (for use as a button)

`each`

**Comment by KES777** [comment]
[Typo](http://tabulator.info/docs/4.1/select#setup-rolling)
>If you want to disabled

`to disable`

**Comment by KES777** [comment]
[Typo](http://tabulator.info/docs/4.1/components#component-cell)
>//force the editor to open even if editable is set to false

`open edit`

**Comment by KES777** [comment]
[Typo](http://tabulator.info/docs/4.1/tree#component)
>Get Child rows

plural is `children`

**Comment by KES777** [comment]
[Typo](http://tabulator.info/docs/4.1/data#ajax)
>You can also load data at any point by ajxa

`ajax`

Also here:
>If you have already set the URL using the ajaxURL option in the table constructor then you can trigger a reload of the data at any point by calling the setData function without any arguments.
    table.setData();

May you please to explicitly name this as: `Refresh/Reload`. It would be more handy. thank you.

**Comment by KES777** [comment]
This is not clear what is top and bottom calculations: http://tabulator.info/docs/4.1/column-calcs#format http://tabulator.info/docs/4.1/format

Please put appropriate links which describe what is `topCalcFormatterParams` and `bottomCalcFormatterParams`

**Comment by olifolkerd** [comment]
Hey @KES777 

Thanks for info on the typos, i have fixed the ones that where appropriate.

In answer to your other points *(im just providing feedback on points, please understand i am not looking to get into a lengthy discussion on these issues i just want to clarify my standing on them)* :
- the ***groupHeader*** function return this can be any thing you want, it can be a string, a number a boolean it dosn't matter as long as the comparison function can handle it.
- the ability to copy links to paragraphs is already planning and will be coming out on the site next year
- top and botom calc params are defined in that sentence and there is a link to the formatter params docs that clearly outlines how params should be used
- Formatter lists, to keep the page headers clear i am only including 1 level of nesting in the headers lists, if you need to find specific things the search box in the site header can be used to find things.

Thanks for the feedback

Oli :)

**Comment by olifolkerd** [comment]
Hey @KES777 

Can i ask, are you working your way through every page of the site, or are you actually coming across these issues as you use the system.

Please forgive my questioning, im am just curious because over the last few days you have been very active over the issues list *(and i really appreciate the engagement)* but it feels that you are only going skin deep in terms of skim reading the pages rather than actually using them in a project.

The reason i say this is because i would far rather that you got something out of Tabulator by using it and feeding back your experience to the community, instead of skim reading things and providing feedback based on a cursory look at things rather than practical experience as this can confuse more junior users/developers.

If you are keen to contribute to the Tabulator community i would love to welcome you on board and can  offer you some pointers on more specific ways you can contribute to the project that will benefit all the users in a constructive way.

Cheers

Oli :)

**Comment by KES777** [comment]
@olifolkerd, I come to those issues because I am trying to use Tabulator in my real project. Currently I code [this](https://github.com/olifolkerd/tabulator/files/2672885/mismatch.html.txt). I am not trying to just skim.

>can offer you some pointers on more specific ways you can contribute to the project
Yes, you are welcome to advice me ;-)

PS. I am sorry, if my sentences probably does not sound kindly. That is because I do not know perfect/sharp word to use.

**Comment by KES777** [comment]
Please create `sample data to be used in all tabulators` section on [`example`](http://tabulator.info/examples/4.1) page. This will allow to copy data from page and not looking into example source

![__](https://user-images.githubusercontent.com/799021/49921318-db80ff00-feb5-11e8-80db-0bc653a2bed9.jpg)

**Comment by olifolkerd** [comment]
@KES777 The example data is already defined in the [Data Documentation](http://tabulator.info/docs/4.1/data)

It is the purpose of the examples section to inform users about specific configurations of the table not to show them start to finish exercises in how to build a basic table, there is a [Quickstart Guide](http://tabulator.info/docs/4.1/quickstart) for this.

Any part of the system that requires that the table have a different format of data entry includes an example of that in the main documentation, which is where it belongs. the example section provides quick access to see features in action with links to the correct documentation to look at things in more detail.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
@KES777 

Thanks for your response

At this point it just feels to me like you are going through the site trying to find the tiniest of hole to point out here, i mean in your last post you were actually looking into the source code for the website which is a bit excessive.

Most of the last few issues you have raised seem to come from a very personal perspective *(ie this information wasn't exactly where ***I*** wanted it to be)* which isn't very helpful to me, no documentation is ever going to be exactly the way you want it im afraid,

There are all sort of searching and linking features built in the website to help people locate the information they are after, if you choose not to use them that is up to you. I simply don't have the time to address every pet niggle of every user of the website, and quite frankly that isn't the point of this issues list.

If there are genuine issues that actually stopped you using the website then i would love to hear about them, and hearing about any typos is great as im crap at spelling, but if it is just a personal usability preference im sorry but you will just have to get used to the site as it is. everyone has their own preferences and i cant cater for them all.

In terms of usefully contributing to the project, my first suggestion would be that go and gain significant experience in using certain function of the table, you can then offer insights from real world experience when answering questions in the issues list. You will see that Tabulator has 4-5 main responders to issues that have been raised, each of them has been using Tabulator for years in specific ways and when they respond the provide sample code and links to the website that are clearly tied back to the question asked.

I understand that you are enthusiastic about Tabulator, and that is great! Im really happy that it is working well for you, but when you go round the issues list trying to redirect users to use your issues, or trying to answer feature requests from other developers that are trying to ask me for new functionality it makes my life much harder because i use this list to manage the development flow of Tabulator and when you start doing that i then have to spend hours going through and correcting it all which makes it all that much more confusing for other users and wastes time that i could actually be spending developing Tabulator.

If there are any areas that you feel you would be suited to when it comes to contributing the Tabulator, such as pull requests, or documentation or anything else, please let me know and i can see if there is a specific way you can contribute more significantly to Tabulator that suits you.

Cheers

Oli :)

**Comment by KES777** [comment]
>It is the purpose of the examples section to inform users about specific configurations of the table

Yes, I agree with you, but from my newbie point of view that is worth to put a word about how tables are initialized and where to get the data. Because I am not just see the different configurations but also try them.

**Comment by KES777** [comment]
some HTML tags are not closed
![__](https://user-images.githubusercontent.com/799021/49954234-b073cb00-ff08-11e8-8e79-251f304a1991.jpg)

**Comment by KES777** [comment]
[Typo](tabulator.info/docs/4.1/mutators#mutators)

>Accessor Types example
{title:"Under Age", field:"age", accessor:ageAccessor, accessorParams:{legalAge:16} accessorDownload:ageAccessor, accessorDownloadParams:{legalAge:18} }

missed comma before `accessorDownload`

**Comment by KES777** [comment]
It is not clear from `Accessor Type` example what it does:

     return value >= params.legalAge;

1. Does it return transformed data?
2. Does it just check access right to data? if `false` - null data is returned, if `true` - value is returned/displayed for user

**Comment by KES777** [comment]
[documentation]() does not cover how to control header formatter:

is it shrinked or `...` padded

![__](https://user-images.githubusercontent.com/799021/50043401-2e0c1800-007c-11e9-8243-8391089d8f40.jpg)

[JS Fiddle](https://jsfiddle.net/KES777/yrqjt16w/3/)

```
    columns:[
        {title:"Long title",  field:"id",         width:40 },
        {title:"Long title",  field:"country_id", width:40, headerSort: false },       
    ],
```

Currently I just notice different rendering for title when `headerSort` is enabled or not

**Comment by KES777** [comment]
replace: `layoutColumnsOnNewData` -> `responsiveLayoutCollapseStartOpen`
![__2](https://user-images.githubusercontent.com/799021/50043734-3a936f00-0082-11e9-83a6-b76b42778202.jpg)

**Comment by olifolkerd** [comment]
@KES777 

Thanks for the feedback, i have fixed the areas in the docs.

Cheers

Oli :)

**Comment by KES777** [comment]
[Typo](http://tabulator.info/docs/4.1/data#ajax-alter)
>You can retrieve the current AJAX URL of the table with the gtAjaxUrl function.
var url = table.gtAjaxUrl();

`gtAjaxUrl` -> `getAjaxUrl`

**Comment by olifolkerd** [comment]
thanks, i have just fixed that on the site :)

**Comment by KES777** [comment]
[Typo](http://tabulator.info/docs/4.1/data#ajax-filter)
>the name of this parameter can be set in the in the paginationDataSent option

`in the in the`

**Comment by KES777** [comment]
same feature named differently: `Remote pagination` VS `Ajax filtering`. I was thought that there is no remote filtering/sorting support. Actually it is.

Would be nice if it will be mentioned on [sort](http://tabulator.info/docs/4.1/sort)/[filter](http://tabulator.info/docs/4.1/filter) pages

**Comment by KES777** [comment]
[Typo?](http://tabulator.info/docs/4.1/page#remote-url)
>sorters - the first current sorters(if any)

Did not run code on this example, but it seems obvious that client should send to server all its state (array of current sorters, not just first one) thus server can return correct sorted data

**Comment by KES777** [comment]
On [this page](http://tabulator.info/docs/4.1/jquery) broken link: http://tabulator.info/docs/4.1/overview-install
![__](https://user-images.githubusercontent.com/799021/50333318-ac9a0700-050d-11e9-9010-86cf4a257e19.jpg)

**Comment by KES777** [comment]
[superfluous information](tabulator.info/docs/4.1/filter#initial)
headerFilterPlaceholder:"Max Age",
section `Filter Comparison Types`

The example contains: `headerFilterPlaceholder:"Max Age"`. In that example this parameter is superfluous. 

Next examples in this section even hide required info:

![__](https://user-images.githubusercontent.com/799021/50440692-06307600-0900-11e9-9b39-00a333b1769c.jpg)

Thus remove `headerFilterPlaceholder` from examples in this section. Also `headerFilterPlaceholder` is described in next section `Placeholder Text`

**Comment by olifolkerd** [comment]
@KES777 

As the documentation states you can use ***ANY*** editor as a header filter, there are numerous examples of other header filters in use in the example page.

As the header filter docs state:
> you can pass a string to this parameter containing any of the standard editors listed in the Manipulating Data section

Cheers

Oli :)

**Comment by KES777** [comment]
documentation contain ambiguous info https://github.com/olifolkerd/tabulator/issues/1683#issuecomment-450088342

**Comment by KES777** [comment]
Also clarify `row component` documentation for `update` method.
https://github.com/olifolkerd/tabulator/issues/1682#issuecomment-450091258

Thank you.

**Comment by KES777** [comment]
[doc](http://tabulator.info/docs/4.1/components#component-row)
>Get Cell in Specific Column
>The getCell function returns the CellComponent for the specified column from this row.
> var cells = row.getCell(column);

cells -> cell, because method return only one cell, not array.

**Comment by KES777** [comment]
[Typo?](http://tabulator.info/docs/4.1/filter#header)

>Filter Comparison Types 
```javascript
function customHeaderFilter(headerValue, rowValue, rowData, filterParams){
    //headerValue - the value of the header filter element
    //rowValue - the value of the column in this row
    //rowData - the data for the row being filtered
    //filterParams - params object passed to the headerFilterFuncParams property
```

>rowValue - the value of the column in this row

do you mean:

    cellValue - the value of the cell in this row

**Comment by KES777** [comment]
[here](http://tabulator.info/docs/4.2/release)
>Framework Compatability

>The data reactivity module has been built to be compatable with all other reactive front end frameworks like vue, react and angular. This means that when you include Tabulator in your framework project you only need to pass the data array to it when you instantiate the table. you can then manipulate the array and data objects through the framework and Tabulator will automatically update

`You` should be capital

**Comment by KES777** [comment]
[here](http://tabulator.info/docs/4.2/columns#visibility)

>Alternativly if you have the ColumnComponent of the column you wish to toggle, you can call the toggle function directly on the component.

Alternatively

**Comment by KES777** [comment]
code have comment:

    //register table for inderdevice communication

this is typo for `inderdevice`

**Comment by KES777** [comment]
tabulator.info/docs/4.2/group#setup-toggle

    To then set the default open

**Comment by KES777** [comment]
The example speaks about different things:

![_](https://user-images.githubusercontent.com/799021/59215473-ffea3980-8bc1-11e9-854f-4f544e62a4f0.jpg)

https://tabulator.info/docs/4.2/group

HeaderFormatter should return the display string instead of boolean value

**Comment by KES777** [comment]
![_](https://user-images.githubusercontent.com/799021/59280316-0c2bd080-8c6e-11e9-9dcb-a42e4d56d9db.jpg)

Menu link is not clickable  http://tabulator.info/docs/4.2/group#multi

**Comment by KES777** [comment]
Documentation missed info about forth parameter:

![_](https://user-images.githubusercontent.com/799021/59281734-6ded3a00-8c70-11e9-8f12-1ae6b6469430.jpg)

http://tabulator.info/docs/4.2/group#multi

**Comment by KES777** [comment]
http://tabulator.info/docs/4.3/release
```
allow users to cleare the cells value easily.
```

should be `clear`

**Comment by KES777** [comment]
At [section](http://tabulator.info/docs/4.5/update#alter-add) `Update or Add Data`:

>If the data you are passng to the table

passing

**Comment by KES777** [comment]
On [page](http://tabulator.info/docs/4.5/update) links to `Row component` are broken: http://tabulator.info/docs/4.5/update#component-row

**Comment by KES777** [comment]
Please describe the format of an `item`

http://tabulator.info/docs/4.6/edit#edit-builtin

![image](https://user-images.githubusercontent.com/799021/78424059-974ddb00-7673-11ea-8e52-7a3b3df90d2d.png)

**Comment by KES777** [comment]
http://tabulator.info/docs/4.6/reactivity#reactive-data

Typo: `Replacing Entier Data Array` -> `Replacing Entir Data Array`

@olifolkerd  Hi, Oli. Does this issue alive? Are my posts here useful?

**Comment by KES777** [comment]
![image](https://user-images.githubusercontent.com/799021/83872383-8e908880-a73a-11ea-8c90-8ab8144ac26d.png)

Please update documentation on this page http://tabulator.info/docs/4.6/edit#edit

![image](https://user-images.githubusercontent.com/799021/83872348-7c164f00-a73a-11ea-98ea-2888396fc718.png)

**Comment by olifolkerd** [comment]
Hey @KES777 

Thanks for those, yes it is still helpful when you post the feedback on here.

Cheers

Oli :)

**Comment by KES777** [comment]
Probably I am not english speaker. But these two description seems similar to me:

![image](https://user-images.githubusercontent.com/799021/84019524-0c969e80-a98a-11ea-94cb-41f665a4738e.png)

Probably this should be reworded to be more explicit

**Comment by KES777** [comment]
http://tabulator.info/docs/4.9/edit

>If you want to generate the options when the select editor is triggered, then you can pass a function into the editorParams, that must return the option list in one of the two formats outlined above

above aoutlined six formats. Which `two` of them you mean? 

probably you mean `any`

**Comment by KES777** [comment]
Typo at http://tabulator.info/docs/5.0/modules


![image](https://user-images.githubusercontent.com/799021/122038756-9ddef300-cdde-11eb-8492-ec441d29b325.png)

**Comment by KES777** [comment]
![image](https://user-images.githubusercontent.com/799021/131477838-3367eeec-0c50-410b-87e9-1edd0615da09.png)

row? It seems I do not understand this. Or just misread (

**Comment by KES777** [comment]
https://tabulator.info/docs/5.4/jquery#overview
![image](https://user-images.githubusercontent.com/799021/222618849-0498d77c-8528-4d39-a018-a37d34e515e8.png)

It would be better, to my mind put links to CDN *.js files. or provide examples how to include those. Similarly to https://tabulator.info/docs/5.4/jquery#overview-install

Thank you.

**Comment by olifolkerd** [comment]
Thanks for the feedback.

In this case I'm gonna disagree. With jQuery there are many ways to include it in the project and it is up to the developer to decide what is best for them.

Also especially with jQuery, it is not a case of using Tabulator means you need to include jQuery, it is a case of you are already using jQuery and you want to add tabulator so it will already be setup in your project.

The links to each of the third party docs include instructions on how to set them up

Cheers

Oli

**Comment by KES777** [comment]
Yep, agree. But it is still better to provide link to that part of documentation where developer could choose how to connect that library, instead of link to main page of jQuery.
![image](https://user-images.githubusercontent.com/799021/222975722-ff199046-8868-4b92-8b99-cbebd07d06a7.png)

**Comment by KES777** [comment]
https://tabulator.info/examples/5.4?#editable
![image](https://user-images.githubusercontent.com/799021/230658283-a4723a47-1f76-4309-a57e-7a58c3e8becd.png)

**Comment by KES777** [comment]
Link does not work:
![image](https://user-images.githubusercontent.com/799021/230658913-bb8ea7cb-dbe1-41bc-9cb3-e12264b0adaf.png)

**Comment by KES777** [comment]
https://tabulator.info/docs/5.4/columns#definition
![image](https://user-images.githubusercontent.com/799021/230659659-d6af76c3-de7a-4f9d-8142-a4676b51fa72.png)

But in this example: 
https://tabulator.info/examples/5.4?#movable

those fields are not used to define column with row handles:
![image](https://user-images.githubusercontent.com/799021/230659889-1efc737c-4f47-4500-a531-350496748b47.png)

Please fix documentation about requirements.

**Comment by KES777** [comment]
https://tabulator.info/examples/5.4?#movable-between-tables

This example does not work in FireFox

**Comment by KES777** [comment]
Seems loading never ends:
![image](https://user-images.githubusercontent.com/799021/230661363-a9f4a8f9-0302-41e3-8b9b-ef5e764d0ddd.png)

**Comment by KES777** [comment]
https://tabulator.info/docs/5.4/data#ajax-sort

It is not clear what `column:column` means

![image](https://user-images.githubusercontent.com/799021/230664975-77592c3c-c0bb-4759-b5a9-4f4afca205c9.png)

**Comment by KES777** [comment]
https://tabulator.info/docs/5.4/select#overview

>Holding down the shift key and click dragging over a number of rows to toggle the state of all rows the cursor passes over. 

Please put a note that this feature does not work on FF.

**Comment by KES777** [comment]
Small typos. Missed `"` for second key/value:
![image](https://user-images.githubusercontent.com/799021/236957981-762ce4d3-8acc-4fbc-a476-51bc7893642c.png)

https://tabulator.info/docs/5.4/format#formatter-lookup
