### ISSUE TITLE
Allow Filter module extensions to accept headerFilterFuncParams

### ISSUE THREAD

**Issue by haferje** [olifolkerd/tabulator#1633]
**Is your feature request related to a problem? Please describe.**
When extending modules, many allow a "Params" value to be sent along when the method is called.  These include Accessors, Column Calculation, Edit, Format, Mutators, and Validate Data.  However, for Filter Data, this is not permitted.

**Describe the solution you'd like**
I would like for the `headerFilterFuncParams` to be passed to the Filter module extension methods, not only when defining a custom FilterFunc function.  Unlike the way I set up custom Formatters through module extensions, for Filters I had to inline a method in order to be able to pass additional parameters.  I would prefer to follow the design of module extensions.

**Describe alternatives you've considered**

**Additional context**
I like the idea of extending modules to add custom functionality, but Filters seem to work slightly different than others.  It is easier when they all have similar signature.

**Comment by olifolkerd** [comment]
Hey @haferje 

That is a very good point, i must have missed that when i implemented that part of the system.

I will stick it on the roadmap for the next release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
This has been fixed on the 4.2 branch and will be released on monday.

Cheers

Oli :)
