### ISSUE TITLE
Docs typo, autocomplete editor, listFormatter

### ISSUE THREAD

**Issue by moorecode** [olifolkerd/tabulator#1636]
Hey Oli,
I noticed in the docs that in the example and explanation of the editorParams for the autocomplete editor, it refers to an option `listFormatter`, it should be `listItemFormatter`.

**Comment by KES777** [comment]
You may put all issues which belongs to documentation into this ticket: #1630

**Comment by olifolkerd** [comment]
Hey @moorecode 

Thanks for the headsup, I have updated the website accordingly.

Cheers

Oli :)
