### ISSUE TITLE
Docs clarification for Download module

### ISSUE THREAD

**Issue by superdweebie** [olifolkerd/tabulator#1637]
Docs should note that when using tabulator_core and the download module, the accessor module is also required for the download module to work.

And+1 for an amazing and useful library.

**Comment by KES777** [comment]
you may put documentation issues into #1630

**Comment by olifolkerd** [comment]
With all due respect @KES777 

Please do not tell other users how to use this issues list.

If you wish to continue doing through the website with a fine tooth comb, then please do continue adding your issues their.

But i would prefer other users raise their own issues so i can alert them with my response.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
@superdweebie 

Good spot, i will ensure the documentation is suitably updated.

Cheers

Oli :)
