### ISSUE TITLE
Request: Define column for tree data expand/collapse/branch elements 

### ISSUE THREAD

**Issue by Nyut0n** [olifolkerd/tabulator#1638]
Hi,
I'm toying with the new tree data function, which is pretty cool so far. The only thing that keeps me from implementing it is a missing option to define the coulmn where the control elements should be added. I haven't found anything in the docs related to that.

**Is your feature request related to a problem? Please describe.**
So apparently, the collapse and expand elements are always added to the first column of the table. That's somehow a limiting factor.

**Describe the solution you'd like**
A simple table option that lets us define the column where we want the collapse/expand/branch elements to be prepended.

**Describe alternatives you've considered**
No idea, I think it's pretty straightforward.

**Additional context**
Here I'd like to have the expand buttons in the item column, not in the icon column.
![image](https://user-images.githubusercontent.com/38189661/49708251-24735200-fc2f-11e8-9808-f1b6a41aac52.png)

Thanks for your consideration :)

**Comment by KES777** [comment]
is [this](http://tabulator.info/examples/4.1#responsive-layout-collapse) what are you looking for?

![__](https://user-images.githubusercontent.com/799021/49885641-7939e700-fe40-11e8-84ee-0d4062a53365.jpg)

or, maybe, [this](http://tabulator.info/examples/4.1#formatters)

![__](https://user-images.githubusercontent.com/799021/49885809-dd5cab00-fe40-11e8-8237-f6f0724f00ab.jpg)  and `cellClick` handler

**Comment by Nyut0n** [comment]
absolutely not.

**Comment by olifolkerd** [comment]
@KES777 I really appreciate your enthusiasm with Tabulator and its issue list, but please can i ask that you take a bit of time to properly get to know Tabulator and understand its features before you start to respond to issues.

You have replied to a couple of issues now with responses that are clearly not related to the questions. i understand that you are eager to help out, but could you please leave things like feature requests to me.

This is a forum for developers to let me know what new features they are looking for in the system and for discussion there upon.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
@Nyut0n 

I see where you are comming from, that will be an easy addition for the next release.

I will stick it on the roadmap.

Thanks for the suggestion

Cheers

Oli :)

**Comment by Nyut0n** [comment]
Sounds great, thanks a lot!

**Comment by olifolkerd** [comment]
Hey @Nyut0n 

I have just added the ***dataTreeElementColumn*** option to the 4.2 branch so you can choose which column the toggle element is inserted into:

```js
var table = new Tabulator("#example-table", {
    dataTree:true,
    dataTreeElementColumn:"name", //insert the collapse/expand toggle element in the name column
});
```

It will be included in mondays release.

Cheers

Oli :)
