### ISSUE TITLE
Sorting headerFilterParams

### ISSUE THREAD

**Issue by flipoo** [olifolkerd/tabulator#1639]
{field:'org', title:'Organisatie', headerFilter:'select', headerFilterParams:{values:true}},...

Due to setting the headerFilterParams values to true, all items of this column are visible in this header.
But the filter items are displayed in the order as the row data.
I was looking to find a solution to display the filter items in alphabetical order, like contents.sort()....

The solution in https://github.com/olifolkerd/tabulator/issues/1560 doesn't work for headerFilterParams... 
How can I sort the headerFilterParams?

**Comment by olifolkerd** [comment]
Hey @flipoo 

Thanks for getting in touch.

When you say that the example dosnt work for you, could you clarify what the issue is that you are having?

Cheers

Oli :)

**Comment by flipoo** [comment]
I want to display the list in alphabetic order (It's not a selection list anymore like in version 4.0)
Now the sort order is how the data order from the ajaxResponse, before the initialSort.

If you have a country list:
{field:'country', title:'Country', headerFilter:'select', headerFilterParams:{values:true}},...
the options now are displayed as: China, Brazil, Australia, Denmark
And not as: Australia, Brazil, China, Denmark,...

Thanks!

**Comment by olifolkerd** [comment]
Hey @flipoo 

They should be displayed in the order they have been declared in the object

Cheers

Oli :)

**Comment by flipoo** [comment]
Thanks Oli,
But what do you mean with 'the object'?
I can order 1 headerfilter (select) with the mysql query: '... order by country', but the problem is that I have more than 1 headerfilter (select).
Or is there a way to get those data and to sort it after displaying?

**Comment by olifolkerd** [comment]
how you structure it server side is down to you. with javascript if you define the properties of an object in a certain order they can be read out in that way, but that will depend on how you json encode your data

**Comment by flipoo** [comment]
I find a solution to sort the items in all the column filters:
By adding a dynamicSort() function at the beginning of the function fillList().

`function fillList() {
     displayItems.sort(dynamicSort("value"));
   ....
}


function dynamicSort(property) {
    var sortOrder = 1;
    if(property[0] === "-") {
        sortOrder = -1;
        property = property.substr(1);
	    }
    return function (a,b) {
        if(sortOrder == -1){return b[property].localeCompare(a[property]);}
        else{return a[property].localeCompare(b[property]);}        
    	}
	}
`

**Comment by udos** [comment]
late to the party but thanks to this issue I found out that `sortValuesList` does work (I'm using version 4.9.3) in `headerFilterParams`:
```js
...
headerFilterParams: { values: true, sortValuesList: "asc" },
...
```

**Comment by ssada1975** [comment]
sortValuesList doesn't wor at list in ver 6.3
Which could be the solution?
