### ISSUE TITLE
dataType and contentType to JSON

### ISSUE THREAD

**Issue by johnomorales** [olifolkerd/tabulator#164]
How to make the ajaxRequest dataType and contentType to JSON?

Like on JQuery 

> $.ajax({
				url : <url>,
				type : "post",
				data : jsonInput,
				dataType : 'json',
				contentType : "application/json; charset=utf-8",

**Comment by olifolkerd** [comment]
You shouldn't need to set either of these. ajax request made by Tabulator are already configured to accept a JSON response.

Are you having a specific issue?

**Comment by johnomorales** [comment]
I believe this one already answered the question.

[https://github.com/olifolkerd/tabulator/issues/165](url)

Since request header manipulation is not yet possible using the built-in "ajaxURL" feature, i'll just construct a jquery ajax call and load the data.

The issue I'm having here, is that my backend requires it (contentType and dataType) for parsing.
(I'm using Jackson)

Thank you for your immediate response.
