### ISSUE TITLE
Grouping rows into several levels and hide / show them

### ISSUE THREAD

**Issue by kreamas** [olifolkerd/tabulator#1640]
Hi Oli.

I'm wondering if there's a way to create a table in Tabulator that can group levels of rows in the following way:

Suppose we have sales data by state (level 1), county (level 2), brand (level 3) and I want to group them by:

1) Always display the number of total sales by State.
2) Click on a State and display sales by County.
3) Click on a County and display sales by brand.

* Texas      100,000
****Houston    50,000
********Brand 1  25,000
********Brand 2  25,000
****Dallas       50,000
********Brand 1  25,000
********Brand 2  25,0000

Where Texas contains (hide) both Houston and Dallas and such counties have Brand 1, 2 (hide).  

Something like Excel's group rows functionality.

Thanks a lot.

**Comment by KES777** [comment]
Hi, @kreamas 
Probably you are looking for: [Multi Level Grouping](http://tabulator.info/docs/4.1/group#setup-toggle)

```javascript
groupBy:["gender", "color"], //group by gender then favourite color
```

If you want to more control how to work with nested data, you can try my script. It is not ideal. Count it as another source of example: 
[mismatch.html.zip](https://github.com/olifolkerd/tabulator/files/2672754/mismatch.html.zip)

**Comment by kreamas** [comment]
Thanks a lot.

I haven't noticed that there's a Tree Structure table which is just what I was looking for :)

Regards
