### ISSUE TITLE
Removing programmatically row leaves empty space

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#1644]
**Describe the bug**
when row is deleted from group, empty space is left

[Kazam_screencast_00005.mp4.zip](https://github.com/olifolkerd/tabulator/files/2672796/Kazam_screencast_00005.mp4.zip)

**Tabulator Info**
- Which version of Tabulator are you using? 4.1.3
- Post a copy of your construct object if possible so we can see how your table is setup

The full code of the page you can find here:
[mismatch.html.txt](https://github.com/olifolkerd/tabulator/files/2672885/mismatch.html.txt)

**To Reproduce**
see attached video

**Expected behavior**
No empty space should be left

**Screenshots**
see attached video

**Desktop (please complete the following information):**
 - OS: linux mint 18.3
 - Browser Chrome 
 - Version v68

**Comment by KES777** [comment]
I replace my `html.zip` with `html.txt`.

@olifolkerd Never heard that `zip` is dangerous. Would it be OK if I put video into `tar.gz`?

**Comment by olifolkerd** [comment]
Hey @KES777 

I would still prefer a simplified example.

It is not the purpose of this issues list to debug people code, it is to identify specific issue and fix them, you will see in almost all examples on this list, users either post a sample constructor or a link to a code pen with a working example

I sadly do not have time to look through peoples code to decipher what is going on, quite often examples are complicated and involve other functionality which is not related to the issue. a clean pure js snippet (included inline in the issue) or a JS fiddle will be fine.

Cheers

Oli :)

**Comment by KES777** [comment]
OK. Thank you for notices. I will simplify code to JS fiddle.

PS. But note, it is not more secure in compare to `.zip` file, because nowdays (thanks LLVM) we can construct such JavaScript and predict particular ASM commands are issued and use Intel's CPU backdoor. [prof](https://habr.com/post/427757/) (see example at the end of article)

Thus cracker can run any instructions set at any OS level by just adding special javascript to snippet ;-)

**Comment by olifolkerd** [comment]
Please have a look at issues raised by @Nyut0n as his are a perfect example of a correctly raised issue
