### ISSUE TITLE
Failed validation freezes IE

### ISSUE THREAD

**Issue by adamxi** [olifolkerd/tabulator#1645]
**Describe the bug**
Hey, I'm currently looking into using Tabulator in our project and i noticed that the validation example (http://tabulator.info/examples/4.1?#validation) freezes the browser (IE 11) when the validation is not valid.

**Tabulator Info**
Tabulator 4.1

**To Reproduce**
1. Go to: http://tabulator.info/examples/4.1?#validation
2. Click inside a cell, E.g a "Name" cell.
3. Remove all characters.
4. Click outside the cell and notice that the validation has failed (red cell border). Also notice that IE has now frozen and is completely unresponsive.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: IE
 - Version: 11.726.16299.0

**Comment by olifolkerd** [comment]
Hey @adamxi 

That definitly looks like a bug, i will get that resolved for this evenings patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @adamxi 

I have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)
