### ISSUE TITLE
Row.update does not call bottomCalc

### ISSUE THREAD

**Issue by timofverberg** [olifolkerd/tabulator#1646]
Updating a row using row.update() does not call the column calc function (calculateSuccessfulOrderRows).
{title:"Status", field:"ordered", formatter: "tickCross", formatterParams:{allowEmpty: true}, bottomCalc: calculateSuccessfulOrderRows},

It is called when updating the entire table using table.setData().
Is there a way to trigger column calculation manually?
One hack is to trigger it by using table.setData(table.getData()).

I am using version 4.1.3 from UNPKG in Firefox 63.0.3.

**Comment by olifolkerd** [comment]
Hey @timofverberg 

Sorry to hear you are having trouble.

Could you post a copy of your table constructor so i can see how your table is setup? The calculation updates can happen a number of different ways depending on the structure of the table so once i know that i can look at fixing that for you.

Cheers

Oli :)

**Comment by timofverberg** [comment]
Hello Oli,
Of course!

```
var table = new Tabulator("#tabell", {
 	layout:"fitColumns",
 	columns:[
	 	{title:"Radnummer", field:"ORRWID"},
	 	{title:"Benämning", field:"NAME"},
	 	{title:"Artikel", field:"ITEMNO", cellClick: copyItemno},
	 	{title:"Ersatt av", field:"replacedby"},
	 	{title:"Antal beställda", field:"ONUM"},
	 	{title:"Pris", field:"CBUYPR", formatter: "money", formatterParams:{symbol: "€", symbolAfter:"p"}},
	 	{title:"Nytt inköpspris", field:"newprice", formatter: "money", formatterParams:{symbol: "€", symbolAfter:"p"}, bottomCalc: calculateTotalSum, bottomCalcFormatter: "money", bottomCalcFormatterParams:{symbol: "€", symbolAfter:"p"}},
	 	{title:"Status", field:"ordered", formatter: "tickCross", formatterParams:{allowEmpty: true}, bottomCalc: calculateSuccessfulOrderRows},
	 	{title:"Availability", field:"availability", formatter: "tickCross", formatterParams:{allowEmpty: true}},
 	],
});
```

**Comment by virusivv** [comment]
Hello Oli,
did you had time to control this issue? I need it too :D

Best regards

**Comment by olifolkerd** [comment]
I have pushed a fix for this to the 4.2 branch and will include it in mondays public release

Cheers

Oli :)

**Comment by virusivv** [comment]
thanks for your work , it's awesome :D (will check the new version)

**Comment by timofverberg** [comment]
Thank you!

Mvh,
Tim

-----
Tim Öfverberg
Consultim
T: 0707 - 87 87 21
http://www.consultim.se

**Comment by virusivv** [comment]
Hello Oli,

Can you please let us know how to trigger the tabulator to recalculate after rowupdate?
