### ISSUE TITLE
Incorrect sizing of table headers when toggling visibility of a column belonging to hidden column group after updating to 4.x

### ISSUE THREAD

**Issue by tytusd** [olifolkerd/tabulator#1649]
**Describe the bug**
It is easier to see what the problem is than to describe it. Basically, when there is more than one column group defined and one attempts to show one of the column groups (which is initially hidden), the header table (as a whole) increases its height without a reason and it never decreases.

**Tabulator Info**
- 4.1.3
- See [https://jsfiddle.net/ycnvjLq8/11/](https://jsfiddle.net/ycnvjLq8/11/)

**To Reproduce**
1. Go to [https://jsfiddle.net/ycnvjLq8/11/](https://jsfiddle.net/ycnvjLq8/11/)
2. Click on "Toggle visibility of columns C3 &amp; C4" button (above the table)
3. When the columns C3 and C4 are shown, the header increases in height (without any reason) and never goes back to the original height (even after hiding the columns again).
4. Click on the "Toggle visibility of columns C3 &amp; C4" button again and again
5. Header increases its height even more.

**Expected behavior**
The column header should not change its height when toggling visibility of columns if its not required by their contents. If the increase in height is required by the contents of the headers of the columns that are shown, the column header should go back to the previous height when hiding these columns again.

**Screenshots**
![image](https://user-images.githubusercontent.com/7070963/49968975-9bf2fb00-ff27-11e8-8820-53a31508b333.png)
![image](https://user-images.githubusercontent.com/7070963/49968994-a90fea00-ff27-11e8-9095-b46862e46e1d.png)
![image](https://user-images.githubusercontent.com/7070963/49969009-b331e880-ff27-11e8-9d57-8004cfdc365f.png)
![image](https://user-images.githubusercontent.com/7070963/49969019-b9c06000-ff27-11e8-88c4-e5c426a2c1f7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 71.0.3578.80

**Additional context**
Previously I used the Tabulator versions 3.x and everything worked fine in this scenario. So, it seems that tbe bug was introduced in versions 4.x.

**Comment by olifolkerd** [comment]
Hey @tytusd 

Thanks for letting me know.

I have pushed a fix for this to the master branch and will include it in this evenings release.

Cheers

Oli :)

**Comment by tytusd** [comment]
@olifolkerd many thanks for quick action, works great now!
