### ISSUE TITLE
BeforeSend request header?

### ISSUE THREAD

**Issue by johnomorales** [olifolkerd/tabulator#165]
On Jquery

`$.ajax({
			url : <url>,
			beforeSend : function(xhr) {
				xhr.setRequestHeader("authorization", token);
			},`

how to add request header on tabulator?

**Comment by olifolkerd** [comment]
At the moment it is not possible to do this directly in Tabulator, though i can see why it would be useful, i will look at adding some advance config options in a future release.

In the mean time i would suggest that you make your own ajax request and pass the data to Tabulator using the ***setData*** function.

```js
function loadData(){
	$.ajax({
		url: "path/to/data",
		type: "get",
		async: true,
		dataType:'json',
		headers:{
			"authorization":token,
		},
		success: function (data) {
			$("#example-table").tabulator("setData", data);
		},
	});
}
```

**Comment by johnomorales** [comment]
Thank you for your immediate response.

That will do.

**Comment by johnomorales** [comment]
Is there a way for remote pagination to work with this setup?

`success: function (data) {
			$("#example-table").tabulator("setData", data);
},`

`ajaxURL: <url>,`
`ajaxType:"POST"`,

`ajaxParams:{filterId: $("#searchId").val() },`
`pagination: "remote",`
`paginationSize: $("#pageSize").val(),`
`paginationDataReceived:{`
`   "last_page":"maxPage"`
`},`


With this setup, pagination was handled internally by tabulator.

how to set and get the following variables from tabulator?

size, page, last_page, sort, sort_dir

**Comment by olifolkerd** [comment]
If you need this token on all requests, then can i suggest you make a global adjustment to the jQuery ajax function. if you include the following line at the start of your project before making any request, then all future requests will be made with the header and you wont need to set it on each request:
```js
$.ajaxSetup({ headers: {"authorization":token} });
```

**Comment by johnomorales** [comment]
OK, Nice workaround, never thought of that.

Thanks again. :)
