### ISSUE TITLE
Columns do not grow to fill available space with fitDataFill

### ISSUE THREAD

**Issue by bs85** [olifolkerd/tabulator#1650]
**Describe the bug**
When using `layout: "fitDataFill"`, columns are not expanded to fill the whole available space

The code below seems to treat `fitData` and `fitDataFill` the same:

https://github.com/olifolkerd/tabulator/blob/08ec6e2b2447885c318f41db2bf1c5c0a3cd5061/src/js/modules/layout.js#L32-L51

**Tabulator Info**
v4.1.3

**To Reproduce**
Display a table with a single, small column in a wide container while using the `fitDataFill` layout.

**Expected behavior**
Column is stretched the entire width of the table.

**Comment by olifolkerd** [comment]
Hey @bs85 

Thanks for getting in touch.

If you want the collumns containing the data to fill the table you want to be using the ***fitColumns*** layout, ***fitDataFill*** will keep the columns the same size and just stretch the width of the row to fill out the space

```js
layout: "fitColumns"
```

Examples of all three layout methods can be found on the [Examples Page](http://tabulator.info/examples/4.1#fittowidth)

Cheers

Oli :)
