### ISSUE TITLE
The focus is not moved to current value

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#1653]
**Is your feature request related to a problem? Please describe.**
When we edit field with "select" editor and this select list is long it is more handy to highlight current value.
This will allow us to see closest options.

**Describe the solution you'd like**
It would be nice if select list scrolled to current value

**Describe alternatives you've considered**
None

**Additional context**
Here we can see that `hdd` value is hidden 
![__](https://user-images.githubusercontent.com/799021/50019374-14ff5a80-ffdb-11e8-9397-e4445d67d6d6.jpg)

Here `ram` is highlighted because it is at the top of list
![__2](https://user-images.githubusercontent.com/799021/50019375-1597f100-ffdb-11e8-9757-3080131f8cc8.jpg)

Would be nice also to move scrolls down when we navigate down to items with bottom <arrow-down>

**Comment by olifolkerd** [comment]
This has been resolved on the 4.2 branch and will be included in Mondays release.

Cheers

Oli :)
