### ISSUE TITLE
why tabulator 4.1 release is not backword compatible????

### ISSUE THREAD

**Issue by skjavedb** [olifolkerd/tabulator#1655]
Please ask questions on www.stackoverflow.com the issues list is now reserved for feature requests and bug reports.

Cheers

Oli :)

**Comment by skjavedb** [comment]
I am using tabulator 4.1 version. and now i want to get the all data of table by using id, it is not happing with this version why....?????

**Comment by skjavedb** [comment]
i want use like this please suggest me, if i am doing something wrong with version 4.1
var data = $("#example-table").tabulator("getData");

**Comment by Rodbjartson** [comment]
First, read this `http://tabulator.info/docs/4.0/upgrade`
Tabulator is fully backwards compatible and even has a wrapper module for Jquery, which means that by including the wrapper module, you can use tabulator like you did before.
