### ISSUE TITLE
Editor for 'null' and 'undefined' values

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#1657]
**Describe the bug**
JavaScript distinguish two types of data: null, undefined

And when the editor:"textarea" is handling 'null' value it converts value to string 'null'

I do not expect here 'null' string for `null` value

**Tabulator Info**
- Which version of Tabulator are you using? 4.1.3
- Post a copy of your construct object if possible so we can see how your table is setup
```javascript

var tabledata = [
	{id:1, country_id: 1, comment: null  },
	];
  
var table = new Tabulator("#example-table", {
    height:"311px",
    data: tabledata,
    columns:[
        {title:"ID", field:"id", width:40 },
        {title:"Comment", field:"comment", editor:"textarea"},
        {title:"NA", field:"not_exists", editor:"textarea"},
    ],
});
```

**To Reproduce**
1. Go to [JS fiddle](https://jsfiddle.net/KES777/7j45qzb0/3/)
2. Click on 'Comment' field
3. Click on 'NA' field
4. move focus something else
compare result at 'Comment' and 'AN' cells

**Expected behavior**
When editing 'null' it should not be converted to 'null' string'

**Screenshots**
![__](https://user-images.githubusercontent.com/799021/50091452-21222c80-0214-11e9-8c5d-e26df62432ad.jpg)
![__2](https://user-images.githubusercontent.com/799021/50091461-254e4a00-0214-11e9-9091-ceba02e2d210.jpg)

**possible workaround**
If there is null just display input's placeholder. If placeholder is not initialized, just initialize its as 'null' when value is 'null' or 'undefined' when such field does not exists.

**Desktop (please complete the following information):**
 - OS: Linux Mint 18.3
 - Browser FF
 - Version v64

**Comment by KES777** [comment]
also for "autocomplete"
![__](https://user-images.githubusercontent.com/799021/50346867-6019f000-053c-11e9-9071-29eb60ebe995.jpg)

**Comment by olifolkerd** [comment]
Hey @KES777 

I have pushed a fix for this to the master branch and will in clude it in this evenings patch release

Cheers

Oli :)

**Comment by KES777** [comment]
I will retest when major patch release occur

Thank you.

**Comment by KES777** [comment]
with [4.2.1](https://jsfiddle.net/KES777/noy7qs3k/2/) version woks fine

**Comment by webseitz** [comment]
@KES777 

> but for "autocomplete" still shows undefined

Will there be an update to fix this behavior?

**Comment by KES777** [comment]
this should be question to @olifolkerd

**Comment by olifolkerd** [comment]
hey @webseitz 

Yup, i will include it in this weekends patch release.

Cheers

Oli :)

**Comment by webseitz** [comment]
Hey @olifolkerd 

I am not 100% sure, but I think I still have the issue with version 4.2.5.

[Here](https://jsfiddle.net/webseitz/yseqr6c5/7/) is the updated fiddle from @KES777 with my autocomplete code.

**Comment by olifolkerd** [comment]
booo.

I fixed it on the select editor but must have missed something on the autocomplete

**Comment by olifolkerd** [comment]
I have pushed a fix for this to the master branch and will include it in this weekends patch release

Cheers

Oli :)

**Comment by webseitz** [comment]
Thanks man, now it works great👍🏻

**Comment by garg10may** [comment]
Text Area still shows undefined

**Comment by olifolkerd** [comment]
Hey @garg10may 

If you are having issues relating to a different formatter please create a new issue, this one has been resolved.

Cheers

Oli :)
