### ISSUE TITLE
Prevent movable row 

### ISSUE THREAD

**Issue by shadyb** [olifolkerd/tabulator#1659]
I am able to move a row from one table to the other, but I now have a use-case whereby if a certain condition is not fulfilled then the row cannot be dropped into the other table.

I was hoping firing a return false on the movableRowsReceived callback might do the trick but it appears not. Is this possible with the current version of tabulator ?

**Comment by olifolkerd** [comment]
Hey @shadyb 

Thanks for getting in touch, but could i ask that in future you ask questions on [StackOverflow](https://stackoverflow.com) , this board is for bug reports and feature requests only.

You cannot return false from that callback as it is triggered after the row has been received into the table you will need to use a custom [Receiver Function](http://tabulator.info/docs/4.1/move#rows-table-receiver) and return ***false*** from that to block the move.

I hope that helps,

Cheers

Oli :)

**Comment by ogggy4858** [comment]
Hi, i not good at English.
I want to prevent users from moving the row to another group. Help me
