### ISSUE TITLE
Sort custom fieldname

### ISSUE THREAD

**Issue by johnomorales** [olifolkerd/tabulator#166]
Assume:

`columns:[
		{title:"Date Joined", field:"dateJoined", sorter:"string", sortable: true},
]`

When i sort, it returns sort=**dateJoined**

but what i needed is **date_joined**.

Will it be possible to define the sort fieldname?

like

`columns:[
		{title:"Date Joined", field:"dateJoined", sortfield: "date_joined",sorter:"string", sortable: true},
]`

**Comment by olifolkerd** [comment]
If you want to sort a field by a different field then you will need to define a custom sorter:
```js
//define custom sorter (string comparison on date_joined field
var customSorter = function(a, b, aData, bData){
    return String(a.date_joined).toLowerCase().localeCompare(String(b.date_joined).toLowerCase());
}

$("#example-table").tabulator({
    columns:[
        columns:[ {title:"Date Joined", field:"dateJoined", sorter:customSorter, sortable: true}, ]
    ],
});
```

Full information on sorters can be found [here](http://olifolkerd.github.io/tabulator/docs/#sorting).

Can i ask why the two columns of almost identical names? are you using one for display and one for sorting?

If that is the case can i suggest you just use the original ***date_joined*** column which you can sort normally, then use a ***formatter*** to transform the value that is displayed to the user.

```js
//define custom sorter (string comparison on date_joined field
var customFormatter = function(value, data, cell, row, options, formatterParams){
        //value - the value of the cell
        //data - the data for the row the cell is in
        //cell - the DOM element of the cell
        //row - the DOM element of the row
        //options - the options set for this tabulator
        //formatterParams - parameters set for the column

        //modify the value here and return the text you want displayed.
        return value;
}

$("#example-table").tabulator({
    columns:[
        columns:[ {title:"Date Joined", field:"date_joined", formatter:customFormatter , sorter:"string", sortable: true}, ]
    ],
});
```

Full details on formatters can be found [here](http://olifolkerd.github.io/tabulator/docs/#formatting)

Let me know if you need any more info.

Cheers

Oli

**Comment by johnomorales** [comment]
Thank you for your immediate response,

The custom sorter will do.

I had to do this because of naming convention, I'm using a Java Backend and the naming convention is not snakecase (Camel Case) , and I want it straight to my DAO layer which is expecting a snakecase.

**Comment by rasadulalam** [comment]
I have two columns, one is start_date and another one is start_time.
Now i want to sort first start_date then start_time if i click any of them.

{ title: "Start Date", field: "start_date ", align: "center" },
{ title: "Start Time", field: "start_time ", align: "center" },
How can i do this


Thanks in advance.

**Comment by olifolkerd** [comment]
Have a look at #485 it has an answer for exactly that problem.

In future can you create a new issue when you have a problem rather than posting on closed issues, it makes it easier for other users to find solutions to the same problem.

Let me know if that helps,

Cheers

Oli

**Comment by rasadulalam** [comment]
Lest forget it.
I have three columns, EmployeeDate, DateOfBirth, EmplyeeID. But I am showing only first two columns (EmployeeDate, DateOfBirth) in the HTML.
Now I want to short EmployeeDate then EmplyeeID. Is it possible? If so then how.

Thanks in advance.
