### ISSUE TITLE
Cell.prototype._generateContents has null value issue

### ISSUE THREAD

**Issue by EnochG1** [olifolkerd/tabulator#1661]
**Describe the bug**
Hi, I'm trying to upgrade tabulator from 3.4 to 4.1 and after version upgrade there's issue like this.
When cell value is null, javascript typeof(null) is 'object', not 'null'.
So your code returns console.warn like below screenshot.

![image](https://user-images.githubusercontent.com/19601207/50126363-fa193880-02af-11e9-8d8b-7ed44b2ab509.png)

It's minor issue cause it's just warning in devTools but I thought I had to share you about this.
Hope you to check this out before next patch.

Thanks.

**Tabulator Info**
Tested in 4.1.3, 4.1.4
Using ajax module

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 70.0.3538.110 (64bit)

**Additional context**

**Comment by olifolkerd** [comment]
Hey @EnochG1 

Thanks for the headsup. I managed to catch most of those when i converted away from jQuery but a couple must have slipped through.

I will get that fixed in the next patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
I have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)
