### ISSUE TITLE
Can't use ajaxLoaderLoading with html string

### ISSUE THREAD

**Issue by EnochG1** [olifolkerd/tabulator#1662]
**Describe the bug**
Hi, I'm upgrading from 3.4 to 4.1 (4.1.4)
Then when I use ajaxLoaderLoading with not default, using html string, then error occurs at below code

![image](https://user-images.githubusercontent.com/19601207/50133120-900f8c00-02cd-11e9-9b64-b3c8c4a2d5a2.png)

I checked 3.4 code and there's a modified code that you changed the way of append html element to this.msgElement (append -> appendChild).
But since this.loadingElement is not html element but html string(according to your documentation) , "Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'" error caught in Promise of ajax.sendRequest.
FYI, It called from page.setPage(1) when loading initial data.

**Tabulator Info**
- Which version of Tabulator are you using? : 4.1.4
- Post a copy of your construct object if possible so we can see how your table is setup
part of tabulator options was below (pagination exists, using ajax)
`{
				paginationSize: 20,
				paginationButtonCount: 9,
				paginationScrollable: true,
				paginationParam: { page: 'PageIdx', size: 'PageSize' },
				persistenceMode: false,
				selectSyncCheckbox: false,
				movableColumns: false,
				ajaxConfig: 'POST',
				ajaxContentType: 'json',
				ajaxResponse: this.response,
				ajaxParams: { categoryCode: 'C001003004' },
				ajaxURL: 'GetSkuCategory',
				ajaxLoaderLoading:
					'<img class="imgWait" src=/front/Mobile/common/loader.gif' style="width: 24px;">',
}`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: 40

**Comment by olifolkerd** [comment]
Hey @EnochG1 

Thanks for the headsup, that is a hangover from the removal of jQuery in version 4.0, i will get a fix out for that in this weekends patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @EnochG1 

I have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)
