### ISSUE TITLE
when setup to remote option in pagination, initial data can be null or empty array to

### ISSUE THREAD

**Issue by pointware** [olifolkerd/tabulator#1663]
**Is your feature request related to a problem? Please describe.**

> 		if(self.options.pagination == "local"){
> 			if(self.options.data.length){
> 				self.rowManager.setData(self.options.data);
> 			}else{
> 				if((self.options.ajaxURL || self.options.ajaxURLGenerator) && self.modExists("ajax")){
> 					self.modules.ajax.loadData();
> 				}else{
> 					self.rowManager.setData(self.options.data);
> 				}
> 			}
> 		}else{
> 			self.modules.page.setPage(1);
> 		}
> 

When setup to remote option in pagination, it calls setPage(1) in _loadInitialData function of Core.js.

When page is loaded, it call setPage or not, I need to control that.

As shown below

>             if(self.options.paginationFirstSearch){
> 			  self.modules.page.setPage(1);
> 		      }else{
> 		         self.rowManager.setData([]);
>             }

option name is whatever can be.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by olifolkerd** [comment]
@pointware Thanks for getting in touch.

Im afraid i don't understand the usage case for your feature request, you could just return an empty array from the request to the server.

Could you explain a bit more about why you need this functionality so i can understand the context of your request better.

Cheers

Oli :)

**Comment by EnochG1** [comment]
@olifolkerd,
I'm facing similar issue.
If ajax and remote pagination, Page.prototype.setPage(1) is called when new Tabulator() is executed.
But I don't want to call it before I call table.setData() because ajaxParam from user's input is not ready.
In this case, that option would be helpful when developer don't want to set page data when Tabulator initial loaded, but set when setData called. (when click 'Search' button, and so on)

**Comment by olifolkerd** [comment]
Hey @EnochG1 

Thanks for the explanation. I have just pushed an update to the master branch to help you with this.

If you set your ***ajaxURL*** property to an empty string in your table constructor, and set the ***pagination*** property to "remote", it will initially load an empty table.

When you then call ***setData*** passing in the required URL it will then make the request for the data.

Thanks for the feedback.

Cheers

Oli :)
