### ISSUE TITLE
Vue Setup Should be Updated

### ISSUE THREAD

**Issue by angeliski** [olifolkerd/tabulator#1665]
I get some errors trying use the Vue example in the doc, because the example is for the Vue 1.x.
Would be Nice update the Vue example to current version (2.x) and/or put on alert of example is using the version 1.x.

Thank's for the support.

**Comment by olifolkerd** [comment]
Hey @angeliski 

Thanks for getting in touch. sorry to hear you are having issues, if you could point out any particular errors i would be happy to update the example.

Cheers

Oli :)

**Comment by angeliski** [comment]
Nice @olifolkerd 
The error in the example it's basicaly in the watch. That snippet:
```
watch(){
    //update table if data changes
    tableData:{
      handler: function (newData) {
        this.tabulator.replaceData(newData);
      },
      deep: true,
    }
  },
```

Should be: 
```
  watch: {
    tableData: {
      handler: function(newData) {
        this.tabulator.replaceData(newData);
      },
      deep: true
    }
  },
```
The only difference is in the declaration of watch, in your example watch is a function, but that doesn't work (I don't could  do that work).

I was believed it was the Vue version, my fault

Best regards

**Comment by olifolkerd** [comment]
ahh yes, good spot. i have just pushed a fix for this to the website.

Thanks for the info

Oli :)
