### ISSUE TITLE
extract "autocomplete" editor as component

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#1667]
**Is your feature request related to a problem? Please describe.**
Your "autocomplete" editor is so handy, that it can be used as standalone component

Like jQuery's autocomplete, but yours is much better

**Describe the solution you'd like**
would be nice if you allow to create "autocomplete" editor manually out of Tabulator.

**Describe alternatives you've considered**
I have tried jQuery "autocomplete" UI

**Additional context**

**Comment by olifolkerd** [comment]
Hey @KES777 

Thanks for your kind words, it is great to hear you are enjoying it.

I would be happy to create a separate repo for that and structure it as a component in its own right.

I will see if i can squeeze it in this weekend, if not it will be after xmas.

Cheers

Oli :)
