### ISSUE TITLE
Black area on close groups - width not resize

### ISSUE THREAD

**Issue by angeliski** [olifolkerd/tabulator#1668]
**Describe the bug**
When I use the property 'groupStartOpen': true and close all groups, the first column don't get all the space, showing a black area 

**Tabulator Info**
- Which version of Tabulator are you using? **4.1.4.**
- Post a copy of your construct object if possible so we can see how your table is setup

Demo: https://codesandbox.io/s/6ymvxrvo03

**To Reproduce**
1. Go to the demo url.
2. Close all groups in the table below the title 'Bug on close'
3. Se the bug:

![tabulator_group_closed_-_codesandbox](https://user-images.githubusercontent.com/1574240/50165872-fb0c9300-02cc-11e9-917f-7cea45b9db78.png)

**Expected behavior**
The Grid should be equal the grid above, closed but fit the width.

**Comment by olifolkerd** [comment]
Hey @angeliski 

That happens because the virtual DOM is disabled in that example. with the virtual DOM enabled it should work correctly.

I will look at resolving that in the next patch release so it also works in classic render mode

Cheers

Oli :)

**Comment by angeliski** [comment]
Great @olifolkerd 
Thank's for your support

**Comment by olifolkerd** [comment]
Hey @angeliski 

I have pushed a fix for this to the master branch and will include it in this evenings patch update.

Cheers

Oli :)
