### ISSUE TITLE
Strange behavior of deleteRow

### ISSUE THREAD

**Issue by cemmons** [olifolkerd/tabulator#167]
![cataloggroupdetailglitch](https://cloud.githubusercontent.com/assets/5125512/22398599/46cb47c6-e562-11e6-8626-0a8e7193edbe.gif)

I have this odd behavior that i cannot resolve.. anything that maybe I'm skipping?

![image](https://cloud.githubusercontent.com/assets/5125512/22398612/b0153138-e562-11e6-81ea-89aca84aa516.png)

**Comment by olifolkerd** [comment]
The issue is when you are creating the new rows they are not automatically assigned an id (this is done incase you want to assign id's server side). so all the new rows technically have the same id.

To solve this i would recommend passing the jquery object of the row to the deleteRow function, this will make sure it knows which row to delete.

Cheers

Oli

**Comment by cemmons** [comment]
Sorry for the dumb question... but how i pass the jquery object of the row inside the event?

**Comment by olifolkerd** [comment]
Thats not a dumb question at all, my bad for not explaining more clearly.

Instead of passing **data.id*** to your ***deleteRow*** function, do the following:
```js
$("#gridCatalogGroupDetail1").tabulator("deleteRow", cell.closest(".tabulator-row"));
```

That should do the trick

**Comment by olifolkerd** [comment]
On a separate note, what app did you use to record your screen? that was very helpful!

**Comment by cemmons** [comment]
Perfect, i had this glitch for over a day now xD thanks a lot.

The app I use is called ScreenToGif 

https://github.com/NickeManarin/ScreenToGif/

It has a lot of features that I don' use but it is very intuitive... I record a piece of my screen do the feature that i want to show, and then transform it to gif... It is handy to show people new features in your app.. without having to write :+1: 

Thanks a lot.. i have other questions with this tabulator.. but let me see if i can figure it out.

**Comment by olifolkerd** [comment]
Thanks for the link, i will definitly use that ScreenToGif in future.

Feel free to give me as shout with any other Tabulator questions, im always happy to help!

Cheers

Oli
