### ISSUE TITLE
4.1: Still getting Uncaught (in promise) undefined issue with ajax (after most recent update)

### ISSUE THREAD

**Issue by mtstedman** [olifolkerd/tabulator#1672]
When I upgraded to 4.1 I started getting "Uncaught (in promise) undefined" on code that had previously worked I read the other thread about this issue, and the fixed applied there don't seem to have fixed whatever the issue here is

	function refreshTable() {

		var apiURL    = "https://mydomain.com/api/server/list/";

		var aJaxRequest = { filterType: $("#CPAFilter").val() };

		var columnSchema = [            {title:"Server",        field:"URL",           sorter:"string", align: 'left', formatter:chevron},
						{title:"Price",         field:"price",         sorter:"number", align: 'left', width:125, formatter:"money", formatterParams: {symbol:"$"}},
						{title:"Region",        field:"region",        sorter:"string", align: 'left', width:150, formatter:regionFormat},
						{title:"Creator",       field:"user_name",     sorter:"string", width:150},
						{title:"Packages",      field:"package_count", sorter:"number", align: 'center', formatter:packageCount, width:50},
		 ];

		buildTable(apiURL, aJaxRequest, columnSchema, container);

	}

	function buildTable(apiURL, aJaxRequest, columnSchema, container) {
		if ($(container).hasClass('tabulator')) $(container).tabulator("destroy");
	        var table = new Tabulator(container, {
			ajaxRequesting:function(){
				$(container).addClass('loading');
			},
			renderComplete:function(){
				$(container).removeClass('loading');
			},
			ajaxURL: apiURL,
			ajaxLoaderLoading:customLoadingIndicator,
			ajaxConfig: "GET",
			ajaxParams: aJaxRequest, 
			columnMinWidth: 120,
			responsiveLayout: 'collapse',
			columns: columnSchema,
			rowFormatter: function(row) {
				//Format here if needed
			},
			index: "id",
			layout:"fitColumns"
		});
	}

	refreshTable();

**Comment by olifolkerd** [comment]
Hey @mtstedman 

Sorry to hear you are having trouble.

Can i ask why you are rebuilding your table everytime you update the url? you only need to call the ***setData*** function on the already built table and it will simply pull in the new data to the existing table so your updated code would look something like this

```js

//Define your table (you only need to do this once)
var table = new Tabulator(container, {
	ajaxRequesting:function(){
		$(container).addClass('loading');
	},
	renderComplete:function(){
		$(container).removeClass('loading');
	},
	ajaxURL: apiURL,
	ajaxLoaderLoading:customLoadingIndicator,
	ajaxConfig: "GET",
	ajaxParams: aJaxRequest, 
	columnMinWidth: 120,
	responsiveLayout: 'collapse',
	columns: [  
	    {title:"Server", field:"URL", sorter:"string", align: 'left', formatter:chevron},
		{title:"Price", field:"price", sorter:"number", align: 'left', width:125, formatter:"money", formatterParams: {symbol:"$"}},
		{title:"Region", field:"region", sorter:"string", align: 'left', width:150, formatter:regionFormat},
		{title:"Creator", field:"user_name", sorter:"string", width:150},
		{title:"Packages", field:"package_count", sorter:"number", align: 'center', formatter:packageCount, width:50},
	],
	rowFormatter: function(row) {
		//Format here if needed
	},
	index: "id",
	layout:"fitColumns"
});

//change table data
function refreshTable() {
	table.setData("https://mydomain.com/api/server/list/", { filterType: $("#CPAFilter").val() })
}
```


I hope that helps,

Cheers

Oli :)

**Comment by mtstedman** [comment]
I'm not rebuilding it every time, but I have multiple table constructors that call buildTable, and send the data to different elements that's just one of the initializors.

**Comment by mtstedman** [comment]
Just tested the following still returns:

    Uncaught (in promise) undefined

Code:

	function buildTable(apiURL, aJaxRequest, columnSchema, container, subTable = false) {

		var table = new Tabulator(container, {
			ajaxRequesting:function(){
				$(container).addClass('loading');
			},
			renderComplete:function(){
				$(container).removeClass('loading');
			},
			ajaxLoaderLoading:customLoadingIndicator,
			ajaxConfig: "GET",
			columnMinWidth: 120,
			responsiveLayout: 'collapse',
			columns: columnSchema,
			rowFormatter: function(row) {
				if (subTable) {
					buildSubtableContainer(row);
				}
			},
			index: "id",
			layout:"fitColumns"
		});

		table.setData("https://mydomain.com/api/server/list/", { filterType: $("#CPAFilter").val() })

	}

**Comment by olifolkerd** [comment]
Hey @mtstedman 

Ok no problem, i will look into it further on the next patch release.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @mtstedman 

There was an uncaught exception coming through when the ajax request failed.

I have pushed a fix for this to the master branch and will include it in this evenings patch release.

What i would say is that this bug could only be triggered if the ajax request failed, so you might need to investigate when your request was failing in the first place.
Cheers

Oli :)
