### ISSUE TITLE
Losing Row formatter click listener on Ascending sort, works on descending sort (also losing it on some filters)

### ISSUE THREAD

**Issue by mtstedman** [olifolkerd/tabulator#1673]
I have a row that I added an onClick listener to expand \ create a subtable, the code works on load, or in descending sort, but the onClick event stops tracking when I switch to ascending sort (it starts working again if I go back to descending).  I've tested an it seems to apply to the click event in general, as I tested it with just an alert on the listener.  Also noticed it occasionally gets weird with filters too but haven't pinned down specific rhyme or reason what triggers it on those:

	function buildTable(apiURL, aJaxRequest, columnSchema, container, subTable = false) {
		if ($(container).hasClass('tabulator')) $(container).tabulator("destroy");
		$(container).tabulator({
			ajaxRequesting:function(){
				$(container).addClass('loading');
			},
			renderComplete:function(){
				$(container).removeClass('loading');
			},
			ajaxURL: apiURL,
			ajaxLoaderLoading:customLoadingIndicator,
			ajaxConfig: "GET",
			ajaxParams: aJaxRequest, 
			columnMinWidth: 120,
			responsiveLayout: 'collapse',
			columns: columnSchema,
			rowFormatter: function(row) {
				buildSubtableContainer(row);
			},
			index: "id",
			layout:"fitColumns"
		});
	}

	function buildSubtableContainer(row) {

		var server_id = row.getData().id;  
		var parentRow = row.getElement();

		var subTableEl          = $('<div id="SUBTABLE_' + server_id + '" style="background-color:white; margin:0; max-width:100%;"></div>');
		var subTableContainerEl = $('<div id="SUBCONTAINER_' + server_id + '" class="sub-table"></div>');
		subTableContainerEl.append(subTableEl);

		parentRow.click(function(){
			$('#SUBCONTAINER_' + server_id).toggle();

			var apiURL    = "https://mydomain.com/api/server/list/landers/";
			var container = "#SUBTABLE_" + server_id;

			var aJaxRequest = { server: server_id };

			var columnSchema = [
									{title:"Name",          field:"name",      sorter:"string"},
									{title:"Index",         field:"index",     sorter:"string", align: 'left', width: 300},
									{title:"Shared",        field:"shared",    sorter:"number", align: 'center', width: 50, formatter:"tickCross"},

			];

			buildFooterTable(apiURL, aJaxRequest, columnSchema, container, row.getData().id);
        
		});

		parentRow.attr('data-toggle', 'collapse');                
		parentRow.attr('href', '#SUBCONTAINER_' + server_id);
		parentRow.after(subTableContainerEl);

		$('#SUBCONTAINER_' + server_id).toggle();

	}

**Comment by olifolkerd** [comment]
Hey @mtstedman 

Sorry to hear you are having trouble

Can i ask which version of Tabulator you are using? If you are filling a bug report, please use the bug issue template as it tells you what information to provide so that we can help you.

Cheers

Oli :)

**Comment by mtstedman** [comment]
Using Tabulator v3.5.3

**Comment by mtstedman** [comment]
Solved the issue with a code workaround.

**Comment by olifolkerd** [comment]
Hey @mtstedman 

Glad to hear you resolved your issue. A lot of things were rebuilt in the 4.0 release so your issue may go away completely if look at upgrading :)

Cheers

Oli :)
