### ISSUE TITLE
Movable Rows between Tables broken on Firefox

### ISSUE THREAD

**Issue by shadyb** [olifolkerd/tabulator#1674]
The Movable rows between tables feature is broken on FF. I cannot drag from one table to another; works fine on Chrome. I am running the latest version of FF. You can replicate the bug by trying the one from the examples page in FF:

http://tabulator.info/examples/4.1#movable-between-tables

**Comment by olifolkerd** [comment]
Hey @shadyb 

Thanks  for getting in contact, sorry to hear you are having trouble.

This is a known bug, that has already been reported in #1184

It is due to firefox firing events certain mouse events in an odd order. It is on the roadmap to resolve this soon.

Cheers

Oli :)

**Comment by aklaver** [comment]
When is this going to be fixed. I can confirm it is still an issue in 4.2.0

**Comment by olifolkerd** [comment]
@aklaver this is covered by #1184 and it is still open

**Comment by aklaver** [comment]
Then can you add a note to docs that this non-functional in FF.

**Comment by abhijitgujar86** [comment]
waiting for this fix
