### ISSUE TITLE
Can not sort data in nested table. 

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#1675]
**Is your feature request related to a problem? Please describe.**
When we [nest table](http://tabulator.info/examples/4.1#nested-tables) but expand/collapse it by row click on parent table (row click - because it is more handy in compare to [nested data toggle](http://tabulator.info/docs/4.1/tree#layout-colexp))
[JS fiddle](https://jsfiddle.net/KES777/q837zLhc/3/) 

It is fine, but when we click row in nested table, the nested table is collapsed

You may notice workaround `stopPropagation` on click for row at nested table.
But this does not work for column headers (can not sort, nested table is collapsed too)

At line 23 of JS fiddle there should be easy way to check if is row or nested data was clicked

**Describe the solution you'd like**
![__](https://user-images.githubusercontent.com/799021/50294225-166ad000-047e-11e9-874e-f70b95efd10c.jpg)

As you can see row cells and nested table are near each others. I consider cells should be wrapped into some `div` to group them together. and assign onclick handler to this `div` and not tabulator-row itself

**Describe alternatives you've considered**
I may suppose this issue was resolved when you work with [tree structure](http://tabulator.info/docs/4.1/tree). It seems at this area more robust reusable interface should be implemented to get more control over nested data.

Thank you.

**Comment by olifolkerd** [comment]
Hey @KES777 

Thanks for your feedback.

Tabulator itself has no specific systems built for managing nested tables, it is simply creating a new table inside of a row formatter with no inherent links between the two. It is therefore currently down to the user to manage any functionality linking between the two.

In a future version of Tabulator i will be overhauling the row formatting system to allow for much more direct relations between rows and any contained tables, and will add functionality along a similar line to the tree system to achieve this. which will then allow for sorting, filtering, row manipulation and much much more.

But there are a number of other systems i need to get in place first for this to be achievable in an efficient and sensible manor so it will likely be a good few months before this is implemented as part of Tabulator by default.

Cheers

Oli :)
