### ISSUE TITLE
Vertical column header rendering issues in IE11

### ISSUE THREAD

**Issue by bedaes** [olifolkerd/tabulator#1676]
**Describe the bug**
I have a table with lots of columns so I tried the vertical column headers feature. Sadly it has some rendering issues in IE11, looks like the headers height is somehow wrong.

**Tabulator Info**
 Tabulator 4.1.4

**To Reproduce**
1. Open IE11
2. Go to http://tabulator.info/examples/4.1?#column-vertical

**Expected behavior**
Vertical column headers look like in every other browser :)

**Screenshots**
![vertical-column-headers-ie11](https://user-images.githubusercontent.com/8410205/50349335-c3575280-053b-11e9-882a-e1da5063bf22.png)

**Desktop (please complete the following information):**
Internet Explorer 11 (Windows 10)

**Comment by olifolkerd** [comment]
Hey @bedaes 

Thanks for letting me know. it looks like IE has some issue with the CSS there, I will look at resolving that in the next patch update.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @bedaes 

Looking into this further im afraid that IE does not support the CSS needed to achieve this.  I will update the documentation to explain this feature is not available in IE.

Given it will take considerable effort to change the functionality to make it work correctly in IE i will not be looking to make the changes as it affects a small feature on a browsers that is only used by a increasingly small number of Tabulator users.

If you want to look into it more yourself i would be happy to accept a pull request.

Cheers

Oli :)

**Comment by simon276** [comment]
is there a workaround for this issue?
