### ISSUE TITLE
Property named 'undefined' added to data objects.

### ISSUE THREAD

**Issue by bedaes** [olifolkerd/tabulator#1677]
**Describe the bug**
Adding `[{"id":1}]` into a table with columns defined like `[ {title: "id", field:"id"}, {formatter:"buttonCross"} ]` adds a new property named `undefined` to the object. 

Therefore `table.getData()[0]` returns `{ id: 1, undefined: undefined }`

**Tabulator Info**
Tabulator 1.4.1

**To Reproduce**
1. Open any browser
2. Go to https://jsfiddle.net/s9xa8yut/1/
3. Check the output in the dev console

**Expected behavior**
`table.getData()[0]` returns `{ id: 1 }`

**Comment by olifolkerd** [comment]
Hey @bedaes 

Thanks for the headsup

I will get that resolved in this weekends patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @bedaes 

I have pushed a fix for this to the master branch and will include it in this weekends patch release.

Cheers

Oli :)
