### ISSUE TITLE
Scrolling not working good

### ISSUE THREAD

**Issue by mikila85** [olifolkerd/tabulator#1678]
**Describe the bug**
Scrolling not working good,
https://codepen.io/mikila85/pen/jXmJzx

**Tabulator Info**
- Latest (4.1.4)
- In Codepen: https://codepen.io/mikila85/pen/jXmJzx

**To Reproduce**
1. Go to codepen https://codepen.io/mikila85/pen/jXmJzx
2. scroll
3. scroll stops

**Expected behavior**
should not lose focus and keep scrolling smoothly

**Screenshots**
![scroll](https://user-images.githubusercontent.com/3965957/50401264-e5e4a800-0795-11e9-87ed-256e094d4274.gif)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version Latest 71

**Additional context**
* not sure when (for some data sets and width works well)

**Comment by olifolkerd** [comment]
Hey @mikila85 

Can i ask why your table is so impossibly small, if you have your table at a reasonable height it seems to work fine.

Cheers

Oli :)

**Comment by mikila85** [comment]
Yes bro we have a few tables that are 3-4 lines hight and they do this problem

**Comment by mikila85** [comment]
Can we fix this bug?
