### ISSUE TITLE
big white space is appeard before first row while fast scrolling up and down.

### ISSUE THREAD

**Issue by skjavedb** [olifolkerd/tabulator#1679]
**Describe the bug**

**Tabulator Info**
- Which version of Tabulator are you using?
- Post a copy of your construct object if possible so we can see how your table is setup

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by skjavedb** [comment]
and i am using tabulator version 3.5

**Comment by skjavedb** [comment]
if anything detail required then please tell em.. thanks.

**Comment by puffsnow** [comment]
Hi @skjavedb,
You didn't write any description in your first comment, there is only title and your tabulator version. Please copy your construct object or write down the steps to reproduce, and others may find the solutions with your problems. Thanks.

**Comment by skjavedb** [comment]
Hi @puffsnow,
i am using 3.5 version of tabulator, and follwing is my code
			$("#eventHistoryOutputDiv").tabulator({
				height : 300,
				layout:"fitColumns",
				tooltips:true,
				placeholder:"No Data Available",
				data : tranTableData,
				columns: tranTableColumns,
				restoredRowFormatter: formatTabulatorRow,
				initialSort:[
					{column:"epoctime", dir:"asc"},
				],
				rowFormatter:function(row){
				    var data = row.getData() ;
				    if(data.classname){
				    	row.getElement().addClass(data.classname) ;
					}
				}
			}) ;

this issue has comes some time only whenever i scrolling up and down fastly.

**Comment by skjavedb** [comment]
some time white space will come before the first row and some time it comes after the last row. attaching another screen shots.
please help me in this, really i am stuck into it.
![screenshot from 2018-12-27 10-56-12](https://user-images.githubusercontent.com/24657362/50467689-42c8a400-09ca-11e9-90da-de905e381143.png)

**Comment by olifolkerd** [comment]
@skjavedb Thanks for the details, This is a know bug with the virtual DOM when row height takes up a chunk of the table

I am putting in some updates to the virtual DOM for version 4.2 which should fix the issue

Cheers

Oli :)

**Comment by skjavedb** [comment]
Thanks @olifolkerd for your quick response,
If possible please update the next release date of version 4.2

Thanks :)

**Comment by olifolkerd** [comment]
Hey @skjavedb 

Probably looking at the end of jan for the 4.1 release.  keep an eye on the #1437 issue for info on when the virtual DOM improvements are complete

Cheers

Oli :)
