### ISSUE TITLE
Columns Width not working on rows

### ISSUE THREAD

**Issue by cemmons** [olifolkerd/tabulator#168]
I have this behavior 

![cataloggroupwidth](https://cloud.githubusercontent.com/assets/5125512/22399332/a35af622-e570-11e6-91c2-c251570b4c6c.gif)

The rows are not getting the same width as the headers.

This is the Code

![image](https://cloud.githubusercontent.com/assets/5125512/22399343/d2234f18-e570-11e6-9d3d-99b99091600f.png)

**Comment by olifolkerd** [comment]
could you past a text version of your code so i can test with it.

Thanks

**Comment by olifolkerd** [comment]
is the table visible when it is created?

**Comment by cemmons** [comment]
Yes, the main form is that grid, and i also have a modal with a grid inside that is not visible. Let me get a text version..

**Comment by cemmons** [comment]
[js.txt](https://github.com/olifolkerd/tabulator/files/737120/js.txt)
[html.aspx.txt](https://github.com/olifolkerd/tabulator/files/737121/html.aspx.txt)

**Comment by olifolkerd** [comment]
It turns out you managed to find a bug in Tabulator there, Good Spot!!! there was an issue rendering column widths in tables with ***fitColumns*** disabled after hidden columns.

I have just committed a fix, download the latest version and you should be all set.

Thanks for pointing it out.

Cheers

Oli

**Comment by cemmons** [comment]
Great, Thanks a lot! It's good to know that I'm collaborating at least with finding bugs xD 


Now it is working all right, But the other grid.. I don't know if i'm doing something wrong.

![image](https://cloud.githubusercontent.com/assets/5125512/22399784/1f57bdaa-e57b-11e6-9b42-04b5a9fc3335.png)

I'm adding a new record so, i pull up the modal, and it should show the grid with the headers. I load the tabulator on first page load and not when i pull up the modal.

![image](https://cloud.githubusercontent.com/assets/5125512/22399800/8b50e4c8-e57b-11e6-905e-fe36ea26bd09.png)

This is the behavior.

![cataloggroupemptygrid](https://cloud.githubusercontent.com/assets/5125512/22399836/4914fee0-e57c-11e6-94ba-6edad5078cdd.gif)

**Comment by olifolkerd** [comment]
The issue you have there is that the tabulator in the dialog cannot properly calculate it layout because it is initialised when it is hidden (hidden elements have no height or width).

In the function where you show the dialog you need to call the ***redraw*** function on the table just as it becomes visible, this will cause it to adjust its layout to match its size:

```js
$("#example-table").tabulator("redraw");
```

**Comment by cemmons** [comment]
Excellent, thanks a lot.. i have been working a lot recently with tabulator.. so i'm new to this xD

**Comment by olifolkerd** [comment]
Always happy to help.

Let me know if there are any feature you think need adding.

Cheers

Oli

**Comment by cemmons** [comment]
Hi again it's me... 

I rewrite the code but it is not working

![image](https://cloud.githubusercontent.com/assets/5125512/22400303/6127ee60-e587-11e6-93bb-c196b0ca3a2d.png)

 ` function CreateDetailGrid() {

        var catalogGroupDetCols = [
       {
           title: "Catalog", field: "catCode", width: "70%", editable: true, editor: function (cell, value, data) {
               var editor = $('#dropcatalog').clone();

               var dat = value;
               
               editor.val(dat);


               editor.css({
                   "padding": "3px",
                   "width": "100%",
                   "box-sizing": "border-box",
               })


               if (cell.hasClass("tabulator-cell")) {
                   setTimeout(function () {
                       editor.focus();
                   }, 100);
               }

               editor.on("change blur", function (e) {
                   cell.trigger("editval", editor.val());
               });
               return editor;
           }
       },
       { title: "Order", field: "cgdOrder", width: "20%", editable: true, align: "right", editor: "number" },
        {
            formatter: "buttonCross", width:"10%", align: "center", onClick: function (e, cell, val, data) {
             
                bootbox.confirm("Desea borrar el Catalogo: " + data.catCode + "  ", function (result) {
                    if (result) {
                        $("#gridCatalogGroupDetail").tabulator("deleteRow", cell.closest(".tabulator-row"));
                    }
                });
            }
        },
        ]

        $("#gridCatalogGroupDetail").tabulator({
            height: "300px",
            fitColumns: false,
            colResizable: false,
            columns: catalogGroupDetCols

        });
    }


   

    $("#newCatalogGroupDetail").click(function () {

        addDetailrow();
       
    });

    $("#btnAddCatalogGroup").click(function () {
        $("#txtCatalogGroupCode").prop('disabled', false);
        $('#modalCatalogGroupDetail').modal('show');
       

        $("#modalCatalogGroupDetail").on('shown.bs.modal', function () {
            $("#gridCatalogGroupDetail").tabulator('redraw');
        });
    });`

**Comment by olifolkerd** [comment]
try:
```js
$("#gridCatalogGroupDetail").tabulator('redraw', true);
```

**Comment by cemmons** [comment]
Thanks a lot again!! That worked like a charm.

**Comment by kenseii** [comment]
table.redraw(true); in case you are using tabulator in raw js
