### ISSUE TITLE
Docs validator functions

### ISSUE THREAD

**Issue by aklaver** [olifolkerd/tabulator#1680]
**Describe the bug**
http://tabulator.info/docs/4.1/validate#func

"Minimum String Length

The maxLength validator allows string values that have a length greater than or equal to parameter
"
Looks like cut and paste from:

"
Maximum String Length

The maxLength validator allows string values that have a length ... "

**Tabulator Info**
Version 4.1 docs.

**Comment by aklaver** [comment]
Also see Required and Unique text.

**Comment by olifolkerd** [comment]
Hey @aklaver 

Thanks for the headsup, i will get the documentation updated over the weekend.

Cheers

Oli :)
