### ISSUE TITLE
Improve interface for headerFilter

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#1681]
For example `autocomplete` editor get filter function as next:

```javascript
          editor          : "autocomplete",
          editorParams: {
              searchFunc      : function( ... ) { ... } // better to rename to filterFunc
          },
```

I suppose that `headerFilter` should allow same:
```javascript
headerFilter: "input",
headerFilterParams: {
     filterFunc: function( ... ) { ... },  //
}
```

```javascript
headerFilter: "input",
headerFilterParams: {
     filterFunc: "<="
}
```

instead of `headerFilterFunc`, `headerFilterFuncParams`

Also please rename `searchFunc` to `filterFunc` for editor, because the function is filtering data.

**Comment by olifolkerd** [comment]
Hey @KES777 

Thanks for getting in touch the filter function for header filters is set in the  ***headerFilterFunc*** column definition property, this function is used to determine how the value of the filter is match to which rows to show.

The ***searchFunc*** in the autocomplete editor is used to search through the list of available values for the autocomplete editor to present a list for the user to choose from, the chosen value is then applied to the ***headerFilterFunc*** if set to the choose the rows for the table.

As the input filter has no list of items to lookup it does not need that functionality.

As header filter elements just use the standard editors all params must match the params for the editor and nothing more, any other specific filter properties are declared in the column definition

A full list of column definition options can be found in the [Column Setup Documentation](http://tabulator.info/docs/4.1/columns#definition)

Cheers

Oli :)

**Comment by KES777** [comment]
Another inconvenience I have found is when I try to filter column with `editor:"autocomplete"`

I can not reach displayed value. Probably here tabulator should pass sort `item` as value of `rowValue/cellValue` parameter.

under `item` I mean item of `values` paremeter of `searchFunc:function(term, values){`
