### ISSUE TITLE
Initial sorters are not applied

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#1683]
**Describe the bug**
when I use `initialSort` feature the data is not sorted, but sorters are applied

![__](https://user-images.githubusercontent.com/799021/50455129-c9429e80-0954-11e9-8e58-c44b67e7206c.jpg)
![__2](https://user-images.githubusercontent.com/799021/50455130-c9429e80-0954-11e9-9c74-b30d714ab08d.jpg)

as you can see on picture despite on sorters data is in same order

**Tabulator Info**
- Which version of Tabulator are you using? 4.1.3
- Post a copy of your construct object if possible so we can see how your table is setup

```
      initialSort : [
        { column: "resource_type_id", dir: "asc" },
        { column: "service_type_id",  dir: "asc" },
      ],
      columns:[
        {
          title           : "Resource",
          field           : "resource_type_id",
          minWidth        : 100,
          formatter       : "lookup",
          formatterParams : resource_list,
          editor          : "autocomplete",
          editorParams: function(){
            var params =  {
              values          : resource_list,
              showListOnEmpty : true,
              searchFunc      : filter_list,
            };
            return params;
          },
          cellEdited : package_detail_update,
        },
        {
          title           : "Service / Price",
          field           : "service_type_id",
          minwidth        : 230,
          formatter       : "lookup",
          formatterParams : service_list,
          editor          : "autocomplete",
          editorParams: function(){
            var params =  {
              freetext        : true,
              values          : service_list,
              showListOnEmpty : true,
              searchFunc      : filter_list,
            };
            return params;
          },
          mutatorEdit: function( value, data, type, params, component ){
            var found =  value.match( /^p(.*)/ );
            if( found ) {
              data.price =  found[1];
              value      = null;
            }
            return value;
          },
          cellEdited : package_detail_update,
        },
```

**To Reproduce**
1. See code above
2. Try to sort on many columns

**Expected behavior**
Data should be sorted

**Desktop (please complete the following information):**
 - OS: Linux Mint 18.3
 - Browser FF v64

**Comment by KES777** [comment]
If I provide custom filter call back it is not called:

```javascript
      ...
      columns:[
        {
          sorter          : function(a, b, aRow, bRow, column, dir, sorterParams){
            console.log( 'sort' );
            return a -b;
          },
    ...
```

it is called only when I explicitly click on column header while multi column sorting

**Comment by olifolkerd** [comment]
The table in your image looks correctly sorted, it would be sorted with the service column in the correct order looking at your array and that is what your image shows.

Please have a look at the [Sort Order Documentation[(http://tabulator.info/docs/4.1/sort) to better understand how sorters are applied to the table.

**Comment by KES777** [comment]
As [DOC](http://tabulator.info/docs/4.1/sort#intial) states:

```javascript
var table = new Tabulator("#example-table", {
    initialSort:[
    {column:"age", dir:"asc"}, //sort by this first
    {column:"height", dir:"desc"}, //then sort by this second
    ]
});
```

In my example the first column is **`resource_type_id`**, but, as you can see, the table is sorted by **second column.** (thank you. I even did not notice that)

If I put columns in **vice-versa** order:
```javascript
    var subTable = new Tabulator(tableEl, {
      layout:"fitColumns",
      ajaxURL: "/api/package_details?package_id=" + row.getData().id,
      initialSort : [
        { column: "service_type_id",  dir: "asc" },
        { column: "resource_type_id", dir: "asc" }, // Now this is second field, but sorted first!
      ],
```
it is sorted, but I consider this a bug. (or please fix documentation)

Thank you.

**Comment by KES777** [comment]
Oh. sorry, I have found another section [`Sort order`](http://tabulator.info/docs/4.1/sort):

>So the data displayed on screen will be sorted in order of height, with any equal height values being sorted by age. The same sort order applies when clicking on multiple column header sorts.

Here you say that sorting is done by `height` **first**, but in example below you say that: **then sort by height second**. This is contr intuitive

**Comment by olifolkerd** [comment]
@KES777 

Im sorry you miss understood the documentation, but both the documentation and the functionality are correct and this is not a bug

Iit is the intended operation for the table and it will be staying that way

Thanks for your feedback

Oli :)

**Comment by KES777** [comment]
May be yes. sorry. But [databases](http://www.postgresqltutorial.com/postgresql-order-by/), and [libraries](https://metacpan.org/pod/DBIx::Class::ResultSet#order_by) sort first by first listed column, then by second.

**Comment by Nazar84** [comment]
I think @KES77 is  right. I have table with `InitialSort` configured  as next:

```
  initialSort : [
    { column: "client_name", dir: "asc"  },
    { column: "kredit",      dir: "desc" },
  ],
```

but, as you can see, table is sorted by `kredit` first:
![изображение](https://user-images.githubusercontent.com/56727082/83127839-4e4e5c00-a0e3-11ea-90a8-e256f1196501.png)


Expected results:
![изображение](https://user-images.githubusercontent.com/56727082/83128042-8bb2e980-a0e3-11ea-8655-59f4f7e93ce8.png)

This is achieved when I reverse sorting:
```
  initialSort : [
    { column: "kredit",      dir: "desc" },
    { column: "client_name", dir: "asc"  },
  ]
```

**Comment by olifolkerd** [comment]
Hey @Nazar84 

This issue was closed over two years ago, please dont try to reopen issues this old as they are clearly based on a much older codebase

The image you have posted is behaving exactly as expected. the order of the list is not primary sort, then secondary sort. it is saying sort this data by "client_name" then take that sorted data by "kredit" which is exactly what is happening.

the correct approach is to reverse the list

Cheers

Oli

**Comment by Nazar84** [comment]
ok)  I`ve got it
