### ISSUE TITLE
Download function not downloading the data

### ISSUE THREAD

**Issue by aditya-thimphu** [olifolkerd/tabulator#1689]
**Describe the bug**
Download function does not download the data. The report data is loaded and visible in the Tabulator table. I have a download link with the below given code. The data is there when I call console.log(report.getData(true)), however, the downloaded file is empty (only the column titles are shown).

**Tabulator Info**
Tabulator 4.1

$("#download-pdf").click(function(){
            console.log(report.getData(true));
            console.log(report.getColumnDefinitions());
            report.download("pdf", "EmployeeDetails.pdf",{orientation:"landscape",title:"Employees Details"});
        });

**Expected behavior**
Download function should download the current

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome Version 70.0.3538.110 (Official Build) (64-bit)

**Comment by olifolkerd** [comment]
Hey @aditya-thimphu 

Thanks for gettng in touch,

Im afraid without a working example of your table it will be very difficult to figure out what is going wrong. do you get any console errors?

Could you create a JS Fiddle or Code Pen that shows your table in action so i can better understand the issue.

Cheers

Oli :)
