### ISSUE TITLE
How to setPageSize on remote?

### ISSUE THREAD

**Issue by johnomorales** [olifolkerd/tabulator#169]
Hi, 

 I was wondering how to modify the pageSize **after the remote pagination was already set.**

> You can change the page size at any point by using the setPageSize function. (this setting will be ignored if using remote pagination with the page size set by the server)

 `$("#example-table").tabulator("setPageSize", 50); // show 50 rows per page`

Assuming I have an html select for page sizes, and I want to change the pageSize on jquery change event.

**Comment by olifolkerd** [comment]
with remote pagination, the page size is set by the number of rows the server returns, i would suggest you pass it as an additional parameter in the pagination request and then make the server return the desired number of rows

**Comment by johnomorales** [comment]
Hi @olifolkerd ,

I don't think that's possible in combination with ajaxUrl because after the tabulator was initiated, ajaxParams 

`$("#member-table").tabulator({`
`	ajaxURL: <url>,`
`	ajaxType:"POST",`
`	ajaxParams:{filterId: $("#searchId").val() },`
`	pagination: "remote",`
`	paginationSize: $("#pageSize").val(),`
`	paginationDataReceived:{`
`	 "last_page":"maxPage"`
`},`
The size becomes fixed and to update it,

I need to do something like this:

`
$("#refreshBtn").unbind('click').click(function(event) {
				event.preventDefault();
				$("#member-table").tabulator("setData",<url>, {filterId: $("#searchId").val(), pageSize: $("#pageSize").val()}, "POST");
			});
`

however I need to handle the other events, like (sort, change page,etc)


unless tabulator has something like this to update the ajaxParams so that the other events are affected.

`$("#member-table").tabulator("setAjaxParams", {}); `

**Comment by olifolkerd** [comment]
tou can use the ***paginatior*** callback to construct a pagination url on each request:
```js
$("#example-table").tabulator({
    pagination:"remote", //enable remote pagination
    ajaxURL:"http://testdata.com/data", //set url for ajax request
    paginator: function(url, pageNo, pageSize, ajaxParams ){
        //url - the url from the ajaxURL paramter
        //pageNo - the requested page number
        //pageSize - the value of the paginationSize paramter
        //ajaxParams - the value of the ajaxParams parameter

        return ""; //must return the string of the page request URL
    },
});
```

Full documentation can be found [here](http://olifolkerd.github.io/tabulator/docs/#pagination)

Cheers

Oli

**Comment by johnomorales** [comment]
Hi @olifolkerd,

 But the callback will force me to use "Get Parameters" and append it to the URL and I'm using POST method :( 

 If there's no current way for POST, It's a minor setback anyways.

 I'm willing to wait.

Do you have plans for 
`
$("#example-table").tabulator("setPageSize", 50); `

to work on remote pagination in the future releases?

Many Thanks,
John

**Comment by olifolkerd** [comment]
Hi John,

Could you try and let me know what the results are.

Cheers

Oli

**Comment by johnomorales** [comment]
Hi @olifolkerd ,

 I tried the codes above, it will not be enough as workaround,

 it doesn't contain the "sort" and "sort_dir" provided by the paginator.

 + the getparameters / queryparam mess that it will create on a POST method URL.

 I think I'm sticking with the built-in remote paginator feature, it's doing great except for the unable to update the setPaginationSize on the fly.

I'll just set it to a fixed value.

Many Thanks,
John

**Comment by olifolkerd** [comment]
Hi John,

you can get the sort details with the ***getSort*** function.

```js
var currentSort = $("#example-table").tabulator("getSort");
```
