### ISSUE TITLE
columnResized callback has unexpected column arg depending on direction of resize

### ISSUE THREAD

**Issue by c-dante** [olifolkerd/tabulator#1690]
**Describe the bug**
The argument passed to the `columnResized` callback is dependent on the direction you approach the resize handle. It should instead always be the column that is being altered.

Fiddle Link:
http://jsfiddle.net/seedante/w05oxste/5/

**Tabulator Info**
- Which version of Tabulator are you using?
4.1.4

**To Reproduce**
1. Attempt to resize column A.
2. Approach the resize handle from the left (column A -> B) and resize, the callback fires with column A.
3. Approach the resize handle from the right (column B -> A) and resize, the callback fires with column B.

In either case, column A is the one being resized. But the callback is incorrect from the right.

**Expected behavior**
The column arg to the `columnResized` method should always be the column whose width/size is altered.

**Desktop (please complete the following information):**
Windows
Google Chrome
Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by KES777** [comment]
This is depend on which handle you drag: from column A or column B

Compare:
![__](https://user-images.githubusercontent.com/799021/50705633-17962280-1064-11e9-92b6-8e3023fb2233.jpg)

![__2](https://user-images.githubusercontent.com/799021/50705636-19f87c80-1064-11e9-9a9d-7c7be402854d.jpg)

**Comment by c-dante** [comment]
The issue is that grabbing the previous handle on B actually resizes A -- B is not the column being resized.

The event being broadcasted isn't "which handle did I grab", but "which column got resized".

As you show in the comparison, only A is changing sizes, but B is broadcasting it's constant size each time you drag from that direction.

**Comment by olifolkerd** [comment]
Hey @c-dante 

Good spot! that is definitely a bug!

I will resolve that in this weekends patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @c-dante 

I have just pushed a fix for this to the master branch and will include it in this weekends patch release.

Cheers

Oli :)
