### ISSUE TITLE
Undo of deleteRow places restored row in different position

### ISSUE THREAD

**Issue by bobabarbanel** [olifolkerd/tabulator#1691]
**Describe the bug**
I am deleting a row with a cellClick function
 **cellClick: function(e, cell) {
            cell.getRow().delete();
          }**

When I run **table.undo(),** the row is restored, but not in the same table location where it had been.

**Tabulator Info**
- Which version of Tabulator are you using? 4.1
- Post a copy of your construct object if possible so we can see how your table is setup
new Tabulator('#tabulator-example', {
      layout: 'fitColumns',
      history: true,
      pagination: 'local',
      paginationSize: 12,
      initialSort: [{ column: 'email', dir: 'asc' }],
      
      columns: [
        {
          title: 'Email',
          field: 'email',
          editor: 'input',
          widthGrow: 2,
          minWidth: 120,
          formatter: emailPlaceHolder
        },
        {
          title: 'Product',
          width: 160,
          field: 'product',
          editor: 'select',
          editorParams: { values: ['Author', 'Reader'] },
          formatter: productPlaceHolder
        },
        {
          formatter: 'buttonCross',
          width: 40,
          align: 'center',
          headerSort: false,
          cellClick: function(e, cell) {
            cell.getRow().delete();
          }
        }
      ]
    });

**To Reproduce**
1. Click on the X in the third column.
2. Click on the button (not shown) that runs table.undo()

**Expected behavior**
The deleted row should be restored exactly where it was in the table rows.

**Screenshots**
See Before , After  and AfterUndo images.

**Desktop (please complete the following information):**
 - OS: Windows 10 Build 13174.472
 - Browser: Version 71.0.3578.98 (Official Build) (64-bit)
BEFORE
![before](https://user-images.githubusercontent.com/15395940/50577517-9548fc80-0dde-11e9-9051-fb3d7f17f544.png)
AFTER
![after](https://user-images.githubusercontent.com/15395940/50577518-9da13780-0dde-11e9-899e-e24fa720c496.png)
AFETRUNDO
![afterundo](https://user-images.githubusercontent.com/15395940/50577519-af82da80-0dde-11e9-9b4c-6f196f120c33.png)

**Additional context**

**Comment by Rodbjartson** [comment]
I suspect that initialSort might play a vital role in this issue. Have you tried without the initial sort? Will the restored row be placed in the same place before deletion?

**Comment by bobabarbanel** [comment]
I "solved" this problem by resorting after every restore of a row that was deleted..
historyUndo: function(action, component, data) {
        if (action === 'rowDelete') {
          table.setSort(table.getSorters());
}

**Comment by olifolkerd** [comment]
@Rodbjartson is right, the table has no way to track the historic order of rows, so if you have sorted in the mean time it will be placed in a different position

**Comment by bobabarbanel** [comment]
I am resorting based on the current sorted lists after every undo of a deleted row.

Bob Abarbanel
+1 206.499.1443
