### ISSUE TITLE
Stuttering frozen columns with horizontal scrolling (FireFox)

### ISSUE THREAD

**Issue by 13Homer** [olifolkerd/tabulator#1696]
Hi Oli,
thank you for excellent library!

**Describe the bug**
I think it is the same as https://github.com/olifolkerd/tabulator/issues/1200 but for FireFox on Linux, on Chrome is working flowlessly.

**Tabulator Info**
In fact it's React Component using Tabular, but I belive it is using newset version, at least example page exposes the same behaviour: http://tabulator.info/examples/4.1#frozen-col

**To Reproduce**
This sandboxcode is a small example: https://codesandbox.io/s/53wox3yxqp
Header is not jumping, only rows below.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: FireFox
 - Version: Ubuntu 16.04 LTS, F 64.0

**Comment by olifolkerd** [comment]
Hey @13Homer 

Thanks for your kind words.

Yes that is a known issue with firefox, its rendering engine is not as efficient as Chrome so it struggles on some tasks.

In the next couple of releases i will be improving the efficiency of the virtual DOM which should make it render better on these browsers.

Cheers

Oli :)
