### ISSUE TITLE
cssClass should apply to calculation column (or a new calcColumnCssClass param)

### ISSUE THREAD

**Issue by gillez** [olifolkerd/tabulator#1699]
**Describe the bug**
The cssClass column parameter applies to Header and table data.  I think it should also apply to the column calculations row.  Alternatively, if there is a reason not to do this, there should be a separate calcColumnCssClass paramater that I can set which would be added to the calculation row.

**Tabulator Info**
v4.1.4

**To Reproduce**
Setup a table with a calculation row and columns containing ```cssClass: "redBorder"``` and setup a css class with
```
.redBorder {
  border: 1px solid red;
}
```

Displaying this table, the column headers and table data have a red border, but the calculation row does not.  

I might be missing something but I can't see any way in the docs of setting a cssClass on the calculation columns.

**Expected behavior**
The cssClass should apply to the calculation row as well, or there should be another parameter that can be set for the calculation columns.

**Desktop (please complete the following information):**
 - OS: MacOS 10.11.16
 - Chrome v64.0.3282.140

**Additional context**
I have fixed this in my fork of this project.  I can provide a merge request of this fix, but if you would like a sneak preview, you can see it here:
https://github.com/gillez/tabulator/commit/b8e74cc095d7e6e98320c0cd0375976c784e10b9

**Comment by olifolkerd** [comment]
Hey @gillez 

That is a good point, i will put in a fix for this on the patch release this weekend.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @gillez 

I have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)
