### ISSUE TITLE
Potential Error in Internet Explorer

### ISSUE THREAD

**Issue by fey227223** [olifolkerd/tabulator#17]
tabulator.js:1021

_generateTooltip(cell, data, tooltip){

Causes an Error in Internet Explorer.
This can be fixed by changing it to
_generateTooltip: function(cell, data, tooltip){

**Comment by olifolkerd** [comment]
well spotted, will fix this even.

Thanks

oli

**Comment by olifolkerd** [comment]
This has now been fixed.
