### ISSUE TITLE
Add dropdown to tabulator.js cells

### ISSUE THREAD

**Issue by GerritKnippschild** [olifolkerd/tabulator#170]
Hi Oli,

is it possible to combine tabulator.js with a drop down menü, in away, that opens a separate dropdown menü as a popup on top of the table, when clicking on a specific cell?
It would be a great function, which would allow us to connect table data with certain functions, that can be initiated via the dropdown menü.

Kind regards,
Gerrit

**Comment by olifolkerd** [comment]
Hi Gerrit.

Im not sure i follow you, but I am certain that Tabulator can offer what you are after.

if you are looking for a dropdown editor for a cell then this is certainly possible. In fact there is an example of exactly this sort of custom editor in the documentation [here](http://olifolkerd.github.io/tabulator/docs/#manipulating-data) and in the gender column of the example editor [here](http://olifolkerd.github.io/tabulator/examples/#editable)

If you are looking for a drop down in the column header then you can use header filters, an example of this can be found in the gender column of the example [here](http://olifolkerd.github.io/tabulator/examples/#filter-header).

If you want a drop down outside of the table then you can bind to its change event and then programatically alter your Tabulator using any number of functions.

If you want to open a dialog box with a select element in, then you would need to choose how to display the dialog, jQuery UI does a nice dialog element, which you could then open using the ***onClick*** property of the column definition object.

if you want to detect a right click and display your own context menu then you could use the ***rowContext*** callback.

Could you confirm which of these you are after and which functions you would like to trigger and i would be happy to give you a more specific example. R rough sketch of the ui you are hoping to acheive would also be a great help.

Cheers

Oli

**Comment by cemmons** [comment]
Hi, dropping by in this thread... I have a dropdown inside my cell.. and the dropdown has data on it... when i click the dropdown.. i lose the data thatwas in that cell... is there a way to open the dropbox and selects the same data from the cell that's in..

PD.. my dropdown is an outside select element that is attached to my tabulator.

**Comment by olifolkerd** [comment]
Hi cemmons, are you using the same editor as included in the example, if so it will auto set its value to the same as the cell as long as the value is in the list of select options

**Comment by cemmons** [comment]
Hmmm.. I think I found the problem... going to test it before

**Comment by GerritKnippschild** [comment]
Hi Oli,

thank you very much for the quick response. I want a drop down outside of
the table. I will try the  onClick property or rowContext callback.
We are already using tabluator in our web app. Currently we are using
separate columns in the table with icons. the user can press an icon to
initiate functions like open a popup, deleting, editing of data. we were
thinking of to get rid of this columns and related icons and  introduce a
drop down outside of the table instead which then gives access to the same
functions.

Cheers,
Gerrit


2017-01-31 21:19 GMT+01:00 Oli Folkerd <notifications@github.com>:

**Comment by olifolkerd** [comment]
Ahh, i follow you now, a sort of action dropdown.

In that case could i suggest possibly using the ***selectable*** option with a value of 1. this will allow the user to select one row at a time, giving a clear visual indication of the  row that is selected, you could then use ***selectionChanged*** callback to update the select box as to which row is selected. (although you could set this value at any number and allow the user to carry out actions on many rows at once if you wanted. information on row selection can be found [here](http://olifolkerd.github.io/tabulator/docs/#selectable)

You can then call the appropriate function on the table when the select box changes, such as ***deleteRow***, ***updateRow***, etc...

Lt me know how it goes.

Cheers

Oli
