### ISSUE TITLE
Editor does not distinguish `null`, 0, '' values

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#1700]
**Describe the bug**
When cell has `''` value and I input `0` value then no `cellEdited` event
because **Tabulator** does not distinguish these values.

[prof](https://github.com/olifolkerd/tabulator/blob/master/dist/js/tabulator.js#L5838)

    if (this.value != value) {

**Tabulator Info**
- Which version of Tabulator are you using? 4.1.3

**Comment by aklaver** [comment]
That is a Javascript thing:

var empty_string = ''
var zero_var = 0

empty_string == true
false
zero_var == true
false
zero_var == empty_string
true
zero_var != empty_string
false

For more info see:
https://stackoverflow.com/questions/19839952/all-falsey-values-in-javascript#46555636

**Comment by KES777** [comment]
@aklaver 
Also do not forget about: `===`

```javascript
empty_string == zero_var
true
empty_string === zero_var
false
```

I mean that editor should use more strict `===` comparison for testing new value

**Comment by aklaver** [comment]
Well that would be for Oli to rule on as it would change behavior of users existing code. In the meantime have you tried cellEditing as way of changing the behavior?

**Comment by aklaver** [comment]
So you have created a custom editor, correct? 
What actually happens in?:
The issue raises when I implement editor with Set NULL functionality

**Comment by KES777** [comment]
sorry for my english. I just tried to implement as on the screenshot.
this try was failed, because tabulator's editor do not raise `cellEdited` event.
It counts that `''`, `0`, `null` are same

**Comment by aklaver** [comment]
Something else is going on as I cannot replicate. 
Can you outline your setup?:
Table definition.
How the data is getting into the table?

**Comment by KES777** [comment]
[JS Fiddle](https://jsfiddle.net/KES777/hfxp2vby/)

Try to replace `0` by empty string. Then again write `0` instead of empty string

**Comment by aklaver** [comment]
When I change 0 to '' it works and also when I change '' back to 0. Now if I backspace the 0 and do not replace it with anything then nothing happens. Seems an actual NULL value is not seen. Went back to my code and realized it is running on Tabulator 4.0.4, so not a direct comparison. Not sure what is going on here.

**Comment by aklaver** [comment]
Updated to 4.1.3. Also realized in my test case here I was changed from a number other then 0 to NULL. When I started with a 0 value and changed to NULL I saw same behavior. This only happens for the initial change. After changing 0 to '' or some other number and then back to 0, changing to NULL calls the cellEdited event.

**Comment by KES777** [comment]
This is happened only once, because when table is initialized the value is numeric, but when you enter `0` again that is string `"0"`. Because `"0" != ""` is true. You can see the `change` event.

**Comment by olifolkerd** [comment]
Hey @KES777 

It is not as simple as that, there are cases where the loose comparison is necessary.

But i do take the point on board, i will look at adding a more complicated comparison function based on cell value type for the next minor release.

Cheers

Oli :)

**Comment by KES777** [comment]
My proposition is to implement flag. Thus developer can chose which comparison Tabulator will use

    strictComparison

By default it will be `false` to keep current behavior.

`true` - to use strict comparison

`function(){}` -- to allow user do old/new value detection on his own.

**Comment by john159753** [comment]
Oli, sorry to comment on this closed issue, but did you end up implementing something to help with this?

Like others above i am having an issue with setting cells to null when the grid is loaded with a '0'. Currently my work around is setting the cell to a non-zero number and then clearing it out.
