### ISSUE TITLE
Scroll to top when subtable inside a row

### ISSUE THREAD

**Issue by MrViSiOn** [olifolkerd/tabulator#1701]
**Describe the bug**
When I place a subtable inside a row... and container has overflow and vertical scroll, in certain point of scrolling, it goes automatically to top.

**Tabulator Info**
- Tabulator v4.1.4
`table = new Tabulator(
        wrapperTable,
        {
          layout: "fitDataFill",
          responsiveLayout:"collapse",
          columns: columns,
          // dataTree: true,
          height: "600px",
          movableColumns: true,
          responsiveLayoutCollapseFormatter: function(data){
            var list = document.createElement("ul");

            for(var key in data){
              var item = document.createElement("li");
              item.innerHTML = "<strong>" + key + "</strong> - " + data[key];
              list.appendChild(item);
            }

            return Object.keys(data).length ? list : "";
          },
          rowFormatter:function(row){
            $( row.getElement() ).append( $( '<div class="subtable-holder"></div>' ) );
          }
        }
      );`

**To Reproduce**
Fill parent table, fill child subtable and scrolling down

**Expected behavior**
Not go scroll to top

**Video**
https://youtu.be/78FyFAs0l2Q

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome

**Comment by olifolkerd** [comment]
Hey @MrViSiOn 

Thanks for getting in touch,

This is a know issue when row hight is closer or greater than the height of the table (which is true in this case with your nested tables).

It is covered in issue #1437 and should be resolved in the next minor version release.

Cheers

Oli :)
