### ISSUE TITLE
Allow filtering for "autocomplete" columns

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#1702]
**Is your feature request related to a problem? Please describe.**
Filtering is restricted if `editor: "autocomplete"`. See question [here](https://stackoverflow.com/q/54011054/4632019)
That is OK, because default filters do not know how to deal with such column: filter by value or display label.

But If I know what to do and supply custom filter, there is no reason to restrict this

**Describe the solution you'd like**
My proposition is to extend [your condition](https://github.com/olifolkerd/tabulator/blob/master/src/js/modules/filter.js#L237) by checking if developer supply his own function for filtering:

     && !headerFilterFunc

**Comment by olifolkerd** [comment]
Hey @KES777 

The point of the autocomplete filter and the select filter is to provide a value once it has been selected by the user, therefore live filtering in these instances makes no sense.

Sorry

Oli :)

**Comment by KES777** [comment]
This has sense if there are many similar data to chose from

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/799021/50728441-8772de80-1132-11e9-862d-53739a2500ee.gif)

Here the list 100+ items

**Comment by olifolkerd** [comment]
in that case you need to use the ***freetext*** option on the autocomplete editor which allows you to use an item not on the list

**Comment by KES777** [comment]
`freetext` for headerFilter and for editor are different things. I still restrict user to input freetext as cell value.
But it is handy to filter as freetext
