### ISSUE TITLE
sometimes scrollbar is not appeared

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#1703]
**Describe the bug**
![__](https://user-images.githubusercontent.com/799021/50700731-fb8a8500-1053-11e9-871a-d5a117fa0998.jpg)

**Tabulator Info**
- Which version of Tabulator are you using? 4.1.3
- Post a copy of your construct object if possible so we can see how your table is setup

**To Reproduce**
Do not know. Sometimes it is appeared, sometimes not.
resizing the window forces scrollbar to appear

Both tables have initial `height`

**Expected behavior**
Scrollbar should appear always when there is no sufficient space for rows

**Screenshots**
after resising:
![__2](https://user-images.githubusercontent.com/799021/50700851-54f2b400-1054-11e9-8adb-6df7d1ac289d.jpg)

**Desktop (please complete the following information):**
 - OS: Linux Mint 18.3
 - Browser FFv64

**Comment by KES777** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/799021/50725130-98572c00-1101-11e9-8d3f-76a44be149ea.gif)

**Comment by olifolkerd** [comment]
Hey @KES777 

Please can you include JSFiddles or Codepens with your requests, it is almost impossible to determine the solutions for your issues when you just post a video, especially when you are using reasonably complex table setups.

Cheers

Oli :)
