### ISSUE TITLE
Rendering issue of > and < characters

### ISSUE THREAD

**Issue by csjoe** [olifolkerd/tabulator#1710]
Hi,

Could you advise on the following please. I couldn't find any settings to resolve this rendering issue.
Many thanks!

**Describe the bug**

`> and < are rendered as &gt; and &lt;`

```
<table id="table">
	<thead>
		<tr>
			<th>col_1</th>
			<th>col_2</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><1</td>
			<td><2</td>
		</tr>
		<tr>
			<td>"Quoted text"</td>
			<td>2 > 1 </td>
		</tr>
	</tbody>
</table>
```

```
let table_cfg = {
	movableColumns: true,
	movableRows: true,
};

let tabulator= new Tabulator('#table', table_cfg);
```

**To Reproduce**
1. Create a simple table and add < or > in any of the cells
2. Apply tabulator
3. Cell data will be rendered encoded: `&lt; &gt;`

**Expected behavior**
Show > < as is and let it be edited

**Screenshots**
![download 31](https://user-images.githubusercontent.com/5880252/50776325-fcf8bf00-1298-11e9-8084-97880b36359e.png)

**Desktop:**
 - OS: Linux Ubuntu 16.04
 - Browser: Chrome
 - Version 69.0.3497.100

**Comment by Nyut0n** [comment]
I'm pretty sure this is expected behavior. Tabulator always sanitizes the values by default to prevent code injection.
What you can do is apply the html formatter to your colums.
Add a  tabulator-formatter="html" attribute to your <th> elements:
```
<th tabulator-formatter="html">col_1</th>
<th tabulator-formatter="html">col_2</th>
```
But be aware this might make your app vulnerable.

**Comment by csjoe** [comment]
Thanks @Nyut0n! Using the html formatter did the trick for me.
