### ISSUE TITLE
Avoid table update when AjaxResponse

### ISSUE THREAD

**Issue by rspadim** [olifolkerd/tabulator#1712]
Could AjaxResponse be aborted? today i'm using throw to abort the data update, maybe returning NULL could result the same effect?

i'm talking about this:
https://github.com/olifolkerd/tabulator/blob/3d7a48af30dcbdee702682e95c6ccd4de2155a86/src/js/modules/ajax.js#L250

**Comment by olifolkerd** [comment]
Hey @rspadim 

Could you be a bit more specific about why you need to abort? has there been an error is it a user pressing a button.

What would you want to happen to the data? be cleared or stay as it was?

Cheers

Oli :)

**Comment by rspadim** [comment]
I call set data to execute ajax load
But mu ajax data tell me to avoid update, and i raise n error to avoid setdata to execute update

If i return null the tabulator clean the table, if i raise any error the ajax update is avoided

I want to know if raise an error is ok, or the could return null or false to ajax function
