### ISSUE TITLE
Select editor disable editable text

### ISSUE THREAD

**Issue by galuha** [olifolkerd/tabulator#1713]
**Is your feature request related to a problem? Please describe.**
The built-in select editor for Tabulator version 4.1 allows to edit cell as plaintext while showing options. Which is not convenient on mobile. Because it opens unnecessary keyboard when pressing the select cell.

**Describe the solution you'd like**
It should be readonly by default, because editing select as plaintext is useless. And it is possible with autocomplete with freetext:true

**Describe alternatives you've considered**
 I would like an editorParam to make it readonly.

**Additional context**

**Comment by galuha** [comment]
Opened pull request

**Comment by olifolkerd** [comment]
Hi@galuha 

I think you may have misunderstood things there.

If you don't want a cell to be editable simply don't include the ***editor*** in the column definition. if you want a cell to only be editable under certain circumstances you can set the ***editable*** callback.

Under no circumstances should an editor be read only, then it has no use as an editor, editors are solely for editing data.

Full details can be found in the [Editor Documentation](http://tabulator.info/docs/4.1/edit)

Cheers

Oli :)

**Comment by galuha** [comment]
No, Oli. You don't understand.
There is a bug.
If I don't include "select" editor, I won't get the select behavior.
But if I include, I do get not only select behavior, but a plaintext editor behavior on input field also because of this.
Like this: https://drive.google.com/open?id=1cRil7zgsReEzWv5IyzYRnBiVoLPWTF_r
There shouldn't be a cursor

**Comment by rspadim** [comment]
agree, i'm with this bug right now too

**Comment by rspadim** [comment]
and for example, using this image

if you type Female, and the select is marked at Male, and you press enter, the editor will select male instead of the text typed

**Comment by galuha** [comment]
Pull request has been merged into master

**Comment by hhlim333** [comment]
agree, i'm with this bug right now too
