### ISSUE TITLE
Uncaught ReferenceError: XLSX is not defined

### ISSUE THREAD

**Issue by answerquest** [olifolkerd/tabulator#1716]
**Describe the bug**
XLSX download triggers "Uncaught ReferenceError: XLSX is not defined"
```
Uncaught ReferenceError: XLSX is not defined
    at rowsToSheet (tabulator.js:11977)
    at generateSheet (tabulator.js:12131)
    at Download.xlsx (tabulator.js:12162)
    at Download.download (tabulator.js:11485)
    at Tabulator.download (tabulator.js:8385)
    at downloadAll (map.html:748)
    at HTMLButtonElement.onclick (map.html:144)
```

**Tabulator Info**
- Which version of Tabulator are you using? : v4.1.5, on cdnjs
- Post a copy of your construct object if possible so we can see how your table is setup
```
var table1 = new Tabulator("#table1", {
 	height:primaryTableHeight, // set height of table (in CSS or here), this enables the Virtual DOM and improves render speed dramatically (can be any valid css height value)
 	data:json1, //assign data to table
 	layout:"fitColumns", //fit columns to width of table (optional)
	selectable:1,
	columns: tabulatorColumnGenerator(json1),
	persistentLayout: true,
    persistentSort: true,
    persistenceID:"table1Perststance",

 	rowSelected:function(row){ 
		var id = row.getData().metainstanceid;
		//alert("Row " + id + " Clicked!!!!");
		// filter the 5 plot tables by this id
		ha1.setFilter("parentuid", "=", id);
		ha2.setFilter("parentuid", "=", id);
		ha3.setFilter("parentuid", "=", id);
		ha4.setFilter("parentuid", "=", id);
		ha5.setFilter("parentuid", "=", id);

		for(let i=1; i<=5; i++) {
			$('#filter'+i+'Status').html('Note: Table is filtered for parentuid = "' + id + '"');
		}
		// mapping : no need to do from here, the tables' dataFiltered callback takes care of it.
 	},
	rowDeselected:function(row){
		clearFilters();
	}
});
// the columns array is generated by a function by reading the incoming json:
function tabulatorColumnGenerator( jsonTable ) {
	if(!jsonTable.length) return [];
	var cols = Object.keys(jsonTable[0]);
	var tableCols = [];
	for(let i=0;i<cols.length;i++) {
		tableCols.push({title: cols[i], field: cols[i], minWidth:100, headerTooltip:cols[i], headerSort:false, headerFilter:"input", editor:"input" })
	}
	return tableCols;
}
```

Here's the download statement, triggered by a button:
```
table1.download("xlsx", "data.xlsx", {sheetName:"MyData"});
```

**To Reproduce**
1. Go to  http://nikhilvj.co.in/files/odk/map.html
2. Keep developer console open (F12)
3. Click on 'Download all tables in an excel' button around bottom of the page.

**Expected behavior**
An excel (.xlsx) file should start to download.

**Screenshots**
Pasted full text of error in console above. Please tell if you really need a screenshot of it too.

**Desktop (please complete the following information):**
 - OS: Lubuntu 18.04 64-bit
 - Browser Chromium browser
 - Version 70.0.3538.77
- Also getting same output on Firefox 63.0.3 (64-bit)

**Additional context**
CSV download is working fine. XLSX : single sheet or multiple sheets, both aren't working.

**Comment by answerquest** [comment]
In the code, replacing "XLSX" with "xlsx" didn't work out either. `XLSX` really is not defined anywhere and I can't figure out where it's supposed to be.

**Comment by answerquest** [comment]
Are we supposed to include some other JS library having this stuff?

**Comment by olifolkerd** [comment]
This is not an error.

The XLSX download functionality is dependent on a 3rd party library, please read the [XLSX Downloader Documentation](http://tabulator.info/docs/4.1/download#xlsx) the first part of the documentation explains how to use it correctly.

Cheers

Oli :)

**Comment by answerquest** [comment]
Yikes! Sorry, my bad! Yes, it's working fine now. I thought I'd checked but turns out I missed that crucial first paragraph.
