### ISSUE TITLE
Version number.

### ISSUE THREAD

**Issue by mikeshow** [olifolkerd/tabulator#172]
Hi,
Wouldn't it be nice if the version number was in the js file too?

**Comment by olifolkerd** [comment]
Hi Mike,

How are you including the script in your project? if you are using a package manager then the version number will be stored in the relevant package file.

Do you have a specific use case for when you would look in the js rather than a package file?

Cheers

Oli

**Comment by mikeshow** [comment]
Hi Oli,

I'm currently using tabulator in a wordpress project and wordpress is not particularly composer/npm friendly, so I just have the js file in the plugin. If I want to check which version I'm using in that plugin I can't. Currently I'm using tabulator in one project, but if use it in others, sooner or later it will be the source of wasted time.

That said, it's not the end of the world. It's just to make life easier. If this is a problem to you it's fine with me. As I said "wouldn't it be ...", meaning if it's no trouble to you, otherwise don't bother I can live with it.

Cheers,

Mike.

**Comment by olifolkerd** [comment]
Hi Mike,

The reason i don't maintain the version number in the .js file is that i only do major/minor version increments on releases through the package managers (approx once a month). which is where most Tabulator users get their code.

The .js file itself changes quite a lot in the month between each release, with minor upgrades and patches to fix issues. if i maintain a version number in this file then i will also need to increment the patch number, which would be an additional burden im afraid i don't really have time for at the moment, and would most likely result in me missing a patch number now and then which i would be keen to avoid.

I certainly like the idea, and would be keen to implement it later down the line as the project expands and more contributors come on board. but in the short term of the next few release i don't think i can implement it with the level of attention it deserves, but i will definitely stick it on the roadmap for future implementation.

Thanks for your input. Give me a shout if you have any other suggestions

Cheers

Oli :)

**Comment by mikeshow** [comment]
No Problem. Thanks.
