### ISSUE TITLE
Number sorter breaks on numbers with more than 2 commas

### ISSUE THREAD

**Issue by Brobin** [olifolkerd/tabulator#1724]
**Describe the bug**

When the value in a column is "1,000,000" or more, the number sorter breaks.

**Tabulator Info**

4.1.4

**To Reproduce**

```javascript 
  var table = new Tabulator("#inventory-table", {
    data: [
      {"inventory": "1,000,000"},
      {"inventory": "950,000"},
      {"inventory": "500"},
    ],
    columns: [
      {title: "Inventory", field: "inventory", sorter: "number"}
    ]
  });
```

**Expected behavior**

Descending Sort: 1MM, 950k, 500
Ascending Sort: 500, 1MM, 950k

**Actaul behavior**

Descending Sort: 950k, _1MM_, 500
Ascending Sort: 500, _1MM_, 950k

**The culprit?**

[String.replace()](https://github.com/olifolkerd/tabulator/blob/master/src/js/modules/sort.js#L295-L296) only replaces the first instance (unlike in python). A combo of split/join must be used.

Therefore, "1,000,000" is evaluating to `1000`

**Comment by olifolkerd** [comment]
Hey @Brobin 

It seems you have already come up with a good solution in your pull request.

I have left you some notes on the pull request.

Cheers

Oli :)
