### ISSUE TITLE
Question: Persistent header filter

### ISSUE THREAD

**Issue by marovargovcik** [olifolkerd/tabulator#1726]
Hey,

in documentation there is stated that persisent filtering in header filters are coming in the next releases. 
I checked your Trello board but could not find anything about it.

I would really appreciate your answer and estimated release number where I can expect this feature.

Thank you very much and have a nice day.

**Comment by olifolkerd** [comment]
Hey @marovargovcik 

That is indeed down for the 4.2 release (i just missed it of the Trello board, but that is fixed now)

It should be out for around the end of Jan

Cheers

Oli :)

**Comment by marovargovcik** [comment]
Hey, 

just noticed that 4.2 is out but docs are still saying that they are coming in the next releases.

Any information about this feature?

**Comment by manuFL** [comment]
Much interested me to, also to any workaround to implement this myself... thank you in advance
