### ISSUE TITLE
Make header title wrapping?

### ISSUE THREAD

**Issue by MikhailKlemin** [olifolkerd/tabulator#173]
Hi!
Does it possible to make header title wraps over, so it's not cut like "Very...", but instead keep it all wrapped over  "Very long column name" ? 
Oh it was mentioned in the docs, but adding this  to style

```
.tabulator .tabulator-header .tabulator-col,
.tabulator .tabulator-header .tabulator-col-row-handle {
    white-space: normal;
}
```
Makes no changes... 

I think I made it work, had to change as well
```
.tabulator .tabulator-header .tabulator-col .tabulator-col-content .tabulator-col-title {
    white-space: normal;  
}
```

**Comment by olifolkerd** [comment]
Yup, you got the correct answer there! :)
