### ISSUE TITLE
Validation issues.

### ISSUE THREAD

**Issue by n4ks** [olifolkerd/tabulator#1730]
**Describe the bug**
Hi Oli, I found few problems with validation.

**1. Validation and pagination.**
When i validate cell and click to another table page - > i can't edit cells after.
1. Set cell validator: "required";
2. Click on cell, delete value,  click to another place, callback validation
3. Click to another page on pagination
4. Can't edit any cell after it (on previous page too)

**1.5 AddRow and ClearTable buttons.**
1. Add buttons for clearing and add row.
2. 2. Click on cell, delete value,  click to another place, callback validation
3. Click to addRow or clearTable buttons
4. Can't edit any cell.

**2. Validation freezes in IE11.**
I have a bug like a described here https://github.com/olifolkerd/tabulator/issues/1645
In version 4.1.5. still have this bug, found your commit https://github.com/olifolkerd/tabulator/commit/85cd7095eb62fa0e061ba42cb85f35540614af7a
In version 4.1.5. that string uncommented
1. Comment `self.focusCellNoEvent(cell);`
2. Validation for validtor: "input" worked. ("number" still freezes)

**2.5 Validation freezes in IE11 and Chrome (not tested Firefox and etc.)**
1.  Set cell validator: "number";
2. Click on cell, delete value, fast click few times in another place.
3. Page freezes.

**3. Can input string values in cell validator: "number" in IE11.**
1. Set cell validator: "number";
2. Can input numbers and string values in that cell. (in Chrome only number values).

Sorry for the large amount of text.

**Tabulator Info**
4.1.5.

**For 1 and 1.5 bug**s i trying to block pagination buttons in validationFailed callback like:
(sorry im new in JS :) )
```
            validationFailed: function (cell, value, validators) {
                // disable buttons
                if (!addButton.hasAttribute("disabled") && !clearButton.hasAttribute("disabled"));
                addButton.setAttribute("disabled", "");
                clearButton.setAttribute("disabled", "");

                // disable pagination
                for (var button = 0; button < paginationButtons.length; button++) {
                    if (!paginationButtons[button].hasAttribute("disabled")) {
                        paginationButtons[button].setAttribute("disabled", "");
                    }
                }
                // Enable buttons when ESC pressed
                window.addEventListener("keydown", function (evt) {
                    if (evt.keyCode === 27) {
                        evt.preventDefault();
                        addButton.removeAttribute("disabled");
                        clearButton.removeAttribute("disabled");
                    }
                });
            }
```
and activate it in cellEdited callback, that's work for me, but I'm not sure that my code does not lead to errors.

**for 2 and 2.5 bugs**
If i uncomment `self.focusCellNoEvent(cell);` and comment next string `rendered();`
validation works fine in IE11 and Chrome (for "input" and "number" type, but i lose focus on cell)

**Comment by olifolkerd** [comment]
Hey @n4ks 

Thanks for getting in touch, Sorry to hear you are having trouble.

Could i ask that you raise a seperate issue for each of your bugs, it makes ie easier to track progress in resolving them rather than having them all in one big ticket.

Cheers

Oli :)

**Comment by n4ks** [comment]
> Hey @n4ks
> 
> Thanks for getting in touch, Sorry to hear you are having trouble.
> 
> Could i ask that you raise a seperate issue for each of your bugs, it makes ie easier to track progress in resolving them rather than having them all in one big ticket.
> 
> Cheers
> 
> Oli :)

Created separate topics, if something is described poorly or need more information I will gladly provide
https://github.com/olifolkerd/tabulator/issues/1736
https://github.com/olifolkerd/tabulator/issues/1734
https://github.com/olifolkerd/tabulator/issues/1735
https://github.com/olifolkerd/tabulator/issues/1733

Thank you!
