### ISSUE TITLE
Table addRow and clearTable buttons and validation issue.

### ISSUE THREAD

**Issue by n4ks** [olifolkerd/tabulator#1734]
Add buttons for clearing table and add row.
Set cell validator to "required"
Click on cell, delete value, click to another place, callback validation
Click to addRow or clearTable buttons
Can't edit any cell.

**Tabulator Info**
4.1.5.

If i disable addRow and clearTable buttons in validationFailed callback user can't "break" the table. (and turn them on in cellEdit callback). but it is rather a temporary solution.
```
                // disable buttons
                if (!addButton.hasAttribute("disabled") && !clearButton.hasAttribute("disabled"));
                addButton.setAttribute("disabled", "");
                clearButton.setAttribute("disabled", "");
```

**Comment by nigels-com** [comment]
Confirming this.  Similar problem here.  Tabulator: 4.1.5

**Comment by olifolkerd** [comment]
Hey @n4ks 

The root cause of this is identical to your other issue #1733 so i will provide feedback fro it there

Cheers

Oli :)
