### ISSUE TITLE
Can input string values in cell validator: "number" in IE11.

### ISSUE THREAD

**Issue by n4ks** [olifolkerd/tabulator#1735]
Set cell validator: "number";
Can input numbers and string values in that cell. (in Chrome only number values).
Its bug or IE11restriction?

**Tabulator Info**
4.1.5.
- Post a copy of your construct object if possible so we can see how your table is setup

**Comment by olifolkerd** [comment]
there is no "number" validator.

There is a "numeric" vaildator that works correctly.

If you are refereing to being able to type characters into a "number" editor then that is just something that IE allows on the input type. but with the "numeric" validator being used it does block it.

There was an issue in 4.1.5 where validators on IE got stuck in an infinite focus loop if the validation failed, but a fix for that issue has been pushed to the 4.2 branch for release on monday.

Cheers

Oli :)
