### ISSUE TITLE
Validation freezes in IE11 and Chrome (not tested Firefox and etc.)

### ISSUE THREAD

**Issue by n4ks** [olifolkerd/tabulator#1736]
**Validation freezes in IE11.**
I have a bug like a described here #1645
In version 4.1.5. still have this bug, found your commit 85cd709
In version 4.1.5. that string uncommented

if i comment `self.focusCellNoEvent(cell)`;
Validation for cell with validator: "input" worked. ("number" still freezes)

**and same bug in IE11 and Chrome**
Set cell validator: "number";
Click on cell, delete value, fast click few times in another place.
Page freezes.

If i uncomment `self.focusCellNoEvent(cell);` and comment next string `rendered();`
validation works fine in IE11 and Chrome (for "input" and "number" type, but i lose focus on cell)

Described both bugs in the same ticket as they are very similar

**Tabulator Info**
4.1.5.

**Comment by olifolkerd** [comment]
This has been fixed  on the 4.2 branch which will be released on monday.

Cheers

Oli :)
