### ISSUE TITLE
sparklines crashes on scrolling 

### ISSUE THREAD

**Issue by alialwahish** [olifolkerd/tabulator#1738]
**Describe the bug**
the sparklines crashes the table after displaying around 20 rows i get these errors

Uncaught TypeError: $(...).sparkline is not a function
    at Object.renderedCallback (dashBoard.js:83)
    at E.cellRendered (tabulator.min.js:6)
    at l.cellRendered (tabulator.min.js:3)
    at tabulator.min.js:3
    at Array.forEach (<anonymous>)
    at r.initialize (tabulator.min.js:3)
    at n._addBottomRow (tabulator.min.js:3)
    at n.scrollVertical (tabulator.min.js:3)
    at HTMLDivElement.<anonymous> (tabulator.min.js:2)
(anonymous) @ dashBoard.js:83
E.cellRendered @ tabulator.min.js:6
l.cellRendered @ tabulator.min.js:3
(anonymous) @ tabulator.min.js:3
r.initialize @ tabulator.min.js:3
n._addBottomRow @ tabulator.min.js:3
n.scrollVertical @ tabulator.min.js:3
(anonymous) @ tabulator.min.js:2

Uncaught TypeError: Cannot read property 'removeChild' of null
    at l.delete (tabulator.min.js:4)
    at r.deleteCells (tabulator.min.js:3)
    at r.initialize (tabulator.min.js:3)
    at n._addBottomRow (tabulator.min.js:3)
    at n.scrollVertical (tabulator.min.js:3)
    at HTMLDivElement.<anonymous> (tabulator.min.js:2) 

**Tabulator Info**

<link href="css/tabulator_modern.min.css" rel="stylesheet">

<script type="text/javascript" src="js/tabulator.min.js"></script>

<script type="text/javascript" src="http://oss.sheetjs.com/js-xlsx/xlsx.full.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.5/jspdf.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/2.3.2/jspdf.plugin.autotable.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-sparklines/2.1.2/jquery.sparkline.min.js"></script>

**Screenshots**

**Desktop (please complete the following information):**

 - Browser [chrome
![tb](https://user-images.githubusercontent.com/29131387/51351636-0b9d5e00-1a71-11e9-9dea-eaeb76e404f7.png)
,]

**Comment by olifolkerd** [comment]
Hey @alialwahish 

Sorry to hear you are having trouble. are you running on the latest version of Tabulator, v4.1.5?

Could you create a JS Fiddle or CodePen that show it in action. it is hard to diagnose the issue unless i can see a working example.

Cheers

Oli :)

**Comment by alialwahish** [comment]
Thanks for responding Oli 

This issue is resolved the problem was not with tabulator ! 

fetching PDO php database and assign it to tabulator will cause a problem if the database fetching doesn't happen in the construct method, the problem was me fetching the database in the index function in the controller ! 

Thanks 
Ali
