### ISSUE TITLE
Pass the to another php script

### ISSUE THREAD

**Issue by kalule** [olifolkerd/tabulator#174]
Good day, Thanks for this wonderful library. Iam really enjoying using this library. I just have a question. I need to post id of particular record such that  when i click on a particular row, it should take me to another php  page so that i can edit the record. Is it possible to do that?

**Comment by olifolkerd** [comment]
Hey,

Thanks for getting in touch, its always great to hear people are enjoying using Tabulator!

You can certainly achieve this using the ***rowClick*** callback:

```js
$("#example-table").tabulator({
        columns:[...],
        rowClick:function(e, id, data, row){
        //e - the click event object
        //id - the id of the row
        //data - the data for the row
        //row - the DOM element of the row

        window.location.href = "/path/to/new/page/" + id;
    },
});
```

Let me know if that is what you were after?

Cheers

Oli

**Comment by kalule** [comment]
Hi Oli,

Thanks for great  work you are doing.

I managed to figure it out and make my application work.

Thank again . Have a great day
