### ISSUE TITLE
Duplicate header/content on the tabulator.info

### ISSUE THREAD

**Issue by izerozlu** [olifolkerd/tabulator#1751]
**Describe the bug**
Duplicate content in tabulator.info

**To Reproduce**
1. Go to http://tabulator.info/docs/4.1/page#manage
2. Scroll to "Change Page Size" header.

**Expected behavior**
Single "Change Page Size" header and content.

**Screenshots**
![screenshot-2019-01-24-16-21-05](https://user-images.githubusercontent.com/17386157/51680915-241ef280-1ff4-11e9-9540-41252d36cf40.png)

PS: thanks for the awesome tool!

**Comment by olifolkerd** [comment]
Hey @izerozlu 

Sorry for the delayed response, I have been busy working on the 4.2 release for next week

I will ensure this is fixed when i update the website with the 4.2 release next week.

Cheers

Oli :)
