### ISSUE TITLE
Drag and Drop issue with grouped column

### ISSUE THREAD

**Issue by kdabir** [olifolkerd/tabulator#1752]
**Describe the bug**
When a row is dropped on another group, the dragged row is not visible and group also does not expand. When other groups are expanded then the group (on which row is dropped) expands. Captured a GIF.

**Tabulator Info**
- "react-tabulator": "^0.7.11"
- config:

        layout: "fitDataFill",
        ajaxURL: "/some-url",
        ajaxFiltering: true,
        ajaxSorting: true,
        groupBy: "groupId",
        movableRows: true,

**To Reproduce**
Follow the config and the gif

**Expected behavior**
dropped row should be visible and group should be expandable immediately. 

**Screenshots**
![dnd](https://user-images.githubusercontent.com/735240/51691329-95749a80-2020-11e9-97f4-b3f91dad14a8.gif)

**Desktop (please complete the following information):**
MacOS / Chrome 71

**Comment by olifolkerd** [comment]
Hey @kdabir 

Sorry for the delayed response, I have been busy working on the 4.2 release for next week

Thanks for the headsup, i will make sure that is resolved for next weeks 4.2 release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
This should now be resolved on the 4.2 branch which will be released on monday.

Cheers

Oli :)
