### ISSUE TITLE
downloadTitle value ignored when downloading grouped column tables

### ISSUE THREAD

**Issue by alex-macy** [olifolkerd/tabulator#1753]
The downloadTitle field is ignored when downloading to csv using Tabulator v4.1.x

The field is being assigned to column.definition.title in Download.prototype.processDefinition(), but Download.prototype.downloaders() only looks at the value in column.title

**Comment by olifolkerd** [comment]
Hey @alex-macy 

Sorry for the delayed response, I have been busy working on the 4.2 release for next week

Im afraid i cant replicate your issues here, it seems to be working fine when i use it.

If you feel this is a bug you need to use the Bug template when creating the issue and it will take you through providing all the info i need to fix a bug. i would also advise that you create a JS fiddle that replicates the issue as it is easier to get to the bottom of a problem on a working example.

Cheers

Oli :)

**Comment by amiriahmad72** [comment]
Hey @alex-macy
You are right. see https://github.com/olifolkerd/tabulator/issues/2030
