### ISSUE TITLE
move column programmatically

### ISSUE THREAD

**Issue by jmlolo** [olifolkerd/tabulator#1754]
Hi,
is it possible to move a column position programmatically ?
Best regards,
JM

**Comment by olifolkerd** [comment]
Hey @jmlolo 

It isnt available in version 4.1

But you are in luck, i just added that exact feature to the 4,2 branch a few days ago.

If you can wait till next monday it will be in the 4.2 release :)

Cheers

Oli :)

**Comment by jmlolo** [comment]
Hey @olifolkerd,
You said that feaature is added in the 4.2 release, but I do  not see any infomation in the documentation to do that.
Cheers,

**Comment by olifolkerd** [comment]
Hey @jmlolo 

http://tabulator.info/docs/4.2/components#component-column

**Comment by jmlolo** [comment]
Hi @olifolkerd and thanks for your reply.
While waiting for the 4.3, how we can update or implement that feature in the 4.2 ?
Cheers,

**Comment by olifolkerd** [comment]
you would have to expose the ***moveColumn*** function on the columnManager through the public api defined in the core.js

**Comment by jmlolo** [comment]
Hi,
I am sorry, but How I can do that ?
Cheers,

**Comment by olifolkerd** [comment]
Hey @jmlolo 

I have just pushed this feature to the 4.4 branch which will be released in the next couple of weeks.

Cheers

Oli :)
