### ISSUE TITLE
Endless focus/blur loop on edit validation failure on IE 

### ISSUE THREAD

**Issue by bedaes** [olifolkerd/tabulator#1755]
**Describe the bug**
See #1645 (which is already closed).

This looks like a regression to me. The bug was fixed with https://github.com/olifolkerd/tabulator/commit/85cd7095eb62fa0e061ba42cb85f35540614af7a but basically reverted in https://github.com/olifolkerd/tabulator/commit/1c8615d0f2038a7618fdafc0881bda48c91b539b

**Tabulator Info**
4.1.5

**Comment by olifolkerd** [comment]
Hey @bedaes 

Thanks for the info, actually fixing this causes a reversion of another bug so the two have been caught in a bit og a loop the last two versions. i will be resolving them both in the 4.2 release.

Cheers

Oli :)

**Comment by bedaes** [comment]
I see :)

I don't know about the severity of the other bug, but this one makes validators in IE11 basically unusable. Also, IE11 gets completely unresponsive most of the time, therefore you have to kill it.

Do you know of any workaround I could use in the meantime (besides forking and applying your patch again ;) )?

Thanks!

**Comment by olifolkerd** [comment]
I Have pushed a fix for this to the 4.2 branch and will include it in mondays release.

Cheers

Oli :)
