### ISSUE TITLE
cellEdited throws an error when when leaving cell.

### ISSUE THREAD

**Issue by driverjb** [olifolkerd/tabulator#1756]
**Tabulator v4.1.4**

**Describe the bug**
I have a table that users are performing data entry. One of the fields is UserID. When the user enters a computing ID the cellEdited event is triggered and it makes a call to the server to lookup the rest of the information if the UserID exists. Pretty standard. If the user entering the data types in the UserID and presses 'Enter' or clicks on the next cell everything works fine. When they press 'Tab' to move to the next cell they get an unhandled exception and the data doesn't update.

This is only happening on Chrome.

**Tabulator Info**
- Which version of Tabulator are you using?
- Post a copy of your construct object if possible so we can see how your table is setup

**To Reproduce**
1. Create a table with data entry cells (input type)
2. Have one of the cells call out to the server and load the row with data when it gets filled.
3. Enter data that will trigger a row fill
4. Press 'Enter' to confirm everything is working
4. Repeat step 3, then press 'Tab'  and see the error.

**Expected behavior**
I expect the cellEdited callback to work the same regardless of how the user exits the cell. Tab is the most efficient way to make your way across a row of data when entering values.

**Desktop**
- Windows 10
- Chrome 71.0.3578.98 (Official Build) (64-bit) = ERROR
- FireFox 64.0.2 = SUCCESS
- Edge (Microsoft Edge 44.17763.1.0) = SUCCESS

Odd, its usually Chrome that always works and everything else that is broken. This is only used internally by my team, so thankfully I do not have to support IE11... my app doesn't work on that at all. Sadly, everyone wants to use Chrome (can you blame them?) so I need to get this resolved.

**Error Details:**
```
Uncaught (in promise) DOMException: Failed to set the 'innerHTML' property on 'Element': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?

l._generateContents  @  tabulator.min.js:4
l.setValueActual  @  tabulator.min.js:4
l.setValueProcessData  @  tabulator.min.js:4
(anonymous)  @  tabulator.min.js:3
r.updateData  @  tabulator.min.js:3
s.update  @  tabulator.min.js:3
(anonymous)  @  request:284
xhr.onload  @  util.js?ver=1.13.4:35
load (async)      
SAP_Util.ajax.get  @  util.js?ver=1.13.4:28
cellEdited  @  request:278
l.setValue  @  tabulator.min.js:4
i  @  tabulator.min.js:6
s  @  tabulator.min.js:6
w.focusCellNoEvent  @  tabulator.min.js:6
w.editCell  @  tabulator.min.js:6
l.edit  @  tabulator.min.js:4
right  @  tabulator.min.js:4
next  @  tabulator.min.js:4
navNext  @  tabulator.min.js:8
z.checkBinding  @  tabulator.min.js:8
(anonymous)  @  tabulator.min.js:8
keyupBinding  @  tabulator.min.js:8
```

**Comment by olifolkerd** [comment]
Hey @driverjb 

Sorry for the delayed response, I have been busy working on the 4.2 release for next week

Thanks for the info.

Please could you create a JS Fiddle or code pen that replicates the issue, it is quite hard to find the cause of the issue without a working example.

Cheers

Oli :)
