### ISSUE TITLE
Stars editor working inconsistently

### ISSUE THREAD

**Issue by hhtab** [olifolkerd/tabulator#1757]
**Describe the bug**
In your example http://tabulator.info/examples/4.1#editable 
the editor "stars" doesn't work:
restores the old value on mouseDown.

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.2
- Browser Safari 12.0.2 and Firefox 64.0.2

**Comment by olifolkerd** [comment]
Hey @hhtab 

Thanks for the headsup,

I will get that fixed for the 4.2 release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @hhtab 

I have pushed a fix for this to the 4.2 branch which will be released on monday

Cheers

Oli :)
