### ISSUE TITLE
Progress Editor not working at low values

### ISSUE THREAD

**Issue by hhtab** [olifolkerd/tabulator#1758]
**Describe the bug**
In your example http://tabulator.info/examples/4.1#editable
the editor "progress" doesn't work if the progresses is close to zero.
(Example person: Mary May).

**Tabulator Info**
4.1

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.2
 - Browser Safari 12.0.2 and Firefox 64.0.2

**Comment by olifolkerd** [comment]
Hey @hhtab 

Thanks for the headsup, i will make sure that is resolved for the 4.2 release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @hhtab 

I have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)
