### ISSUE TITLE
Issue with IE 11

### ISSUE THREAD

**Issue by Billmcsill** [olifolkerd/tabulator#1763]
**Describe the bug**
I am getting an error when loading the table in IE11. 

It works without any issues on Chrome.

**Tabulator Info**
4.2 - I was using 4.1 which also didn't work but just upgraded to 4.2 as I saw it had been uploaded.
- Post a copy of your construct object if possible so we can see how your table is setup

            var table = new Tabulator("#search-table", {
                ajaxURL: BuildURL(),
                ajaxConfig: "post",
                height: "calc(100vh - 300px)",
                layout: "fitColumns",
                placeholder: "No Data Available",
                initialSort: [
                    { column: "transactionId", dir: "desc" }
                ],
                columns: [
                    { title: "Id", field: "transactionId", width: 100, tooltip: true, sorter: "number" },
                    { title: "Type", field: "messageType", width: 120, tooltip: true },
                    { title: "Description", field: "description", tooltip: true },
                    { title: "Product Code", field: "productCode", width: 130, tooltip: true },
                    { title: "Serial Number", field: "packSerialNumber", width: 170, tooltip: true },
                    { title: "Batch Id", field: "batchId", width: 140, tooltip: true },
                    { title: "Expiry Date", field: "batchExpDate", width: 110, tooltip: true },
                    { title: "Status", field: "packStatus", width: 120, tooltip: true },
                    { title: "Reason", field: "reason", tooltip: true },
                    {
                        title: "Details", align: "center", width: 85, formatter: formatDetailsIcon, tooltip: "View Message Details", cellClick: function (e, cell) {
                            Load("/History/Details/" + cell.getRow().getData().transactionId, 'Message Details')
                        }
                    },
                ]
            });

**To Reproduce**
1:) Load the data in IE11 instead of Chrome

**Expected behavior**
The data should load and be displayed in the table

**Screenshots**
![image](https://user-images.githubusercontent.com/47108649/51837518-7e24fe00-22fb-11e9-9a5c-25e06961aa90.png)

**Desktop (please complete the following information):**
 - OS: Windows Server 2012
 - Browser: IE11
 - Version:11

**Additional context**

**Comment by olifolkerd** [comment]
Hey @Billmcsill 

Thanks for getting in touch,

4.2 has not been released yet, it is an unstable development branch. please do not use unreleased versions as they are undocumented and in no way stable. as such i cannot offer support on them.

If you think you have an issue, please mockup a JS Fiddle or Code Pen that shows the issue in action, then i can look into it further

Cheers

Oli :)

**Comment by aklaver** [comment]
Noticed that the error is being thrown by jquery.min.js. 
Do you have jquery support loaded?:
http://tabulator.info/docs/4.1/jquery

**Comment by Billmcsill** [comment]
Hi Oli/Aklaver,

I am using jquery, the error was down to me not reading the compatibility requirements. It worked after I referenced the fetch and promise polyfills but it's a lot slower and often displays blank areas while it catches up on the scroll.

It's annoying because I absolutely love the functionality of tabulator and the speed it loads the data in the virtual dom in Chrome but due to my users needing it to work in IE the only workaround was to limit the number of rows to a reasonable quantity and paginate it. 

I've been trying to avoid this as users need the ability to select multiple rows from a list of around 1000 items and it doesn't seem to push the row indexes from pages that aren't currently displayed correctly.

If only I could insist that Chrome was the only option as it works amazingly with it!

I'm open to suggestions but keep up the great work Oli! I'll try and make a donation next time I'm paid :)

**Comment by olifolkerd** [comment]
Hey @Billmcsill 

Im afraid there is no way to speed things up for IE. It takes a lot of calculations to make Tabulator work and im afraid that IE simply isn't powerful enough to do it smoothly.

Tabulator already runs in a fallback mode when it detects it is running in IE that strips the rendering back to the bare bones, there isn't much more that can be done im afraid.

With regards to the selected rows, that is because you are using remote pagination, in that mode the selection is cleared out with each page because the previous pages rows are destroyed when the new page is loaded. in remote pagination mode only the current page worth of data exists in Tabulator, therefore there can be no selection of rows on other pages.

I hope that makes sense.

Cheers

Oli :)
