### ISSUE TITLE
Theme for Bulma

### ISSUE THREAD

**Issue by stvowi** [olifolkerd/tabulator#1765]
There are no great grid for [Bulma CSS](https://bulma.io/).
Would the developer team please support this CSS Framework with a tabulator theme for Bulma?

**Comment by olifolkerd** [comment]
Hey @stvowi 

Thanks for getting in touch,

I will certainly have a look into that, if you are lucky i might get it in in time for the 4.3 release next weekend.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
I have pushed this to the 4,2 branch and will include it in the monday release.

Thanks for the suggestion.

Cheers

Oli :)
