### ISSUE TITLE
headerClick not working

### ISSUE THREAD

**Issue by swatiwak** [olifolkerd/tabulator#1766]
Column Callbacks are not working. 
Below is the piece of code for headerClick.

Please let me know if anything is wrong in below code

`$("#example-table").tabulator({
        height:"320px", // set height of table (optional)
        fitColumns:true, //fit columns to width of table (optional)
        columns:[ //Define Table Columns
            {title:"Name", field:"name", sortable:false,headerClick:function(e, column){
                           alert("Hello")
            }},
            {title:"Age", field:"age", sorter:"number", align:"left", formatter:"progress"}
    });`

**Comment by aklaver** [comment]
Tabulator version?
I could get it to work here.
When I reformatted your code(and got rid of inline comments) I noticed there was no ending ] to the columns array.
FYI I believe you want headerSort: false not sortable: false. That did not affect the results in any case.

**Comment by swatiwak** [comment]
Hi 
I tried with latest version and it is working now.

Thanks for the correction. headerSort is correct configuration.
