### ISSUE TITLE
Automatically hide responsiveCollapse expando when nothing is hidden

### ISSUE THREAD

**Issue by tominventisbe** [olifolkerd/tabulator#1768]
**Is your feature request related to a problem? Please describe.**
I'm looking for a way to automatically hide or disable the `responsiveCollapse` "expando" or toggle button when there are no rows hidden behind it. Currently, it seems this expando is always visible, even if there is nothing to expand.

**Describe the solution you'd like**
The expando should hide itself when there is nothing to display in it or its content is empty. Optionally the column could also disappear, but that may be more difficult to implement.

**Describe alternatives you've considered**
I've currently worked around this by confguring a `responsiveLayoutCollapseFormatter`. I'll display my code here for reference to others that desire this functionality in case this won't be implemented or until it can be implemented.

```js
const findAllCollapseToggleButtons = (el) => {
    return el.querySelectorAll('.tabulator-responsive-collapse-toggle');
};

// ...

// Inside the Tabulator configuration:
responsiveLayoutCollapseFormatter: function (data) {
    const shouldHideResponsiveToggles = Object.keys(data).length === 0;

    findAllCollapseToggleButtons(this.table.element).forEach((el) => {
        if (shouldHideResponsiveToggles) {
            el.classList.add('h-hide');
        } else {
            el.classList.remove('h-hide');
        }
    });

    // Delegate to original implementation.
    return this.table.modules.responsiveLayout.formatCollapsedData(data);
},
```

This solution isn't great and can perform badly with many rows as the element scan will happen multiple times. I don't really immediately see a way out of this as the rows are rendered one-by-one (i.e. only triggering this the first time will only solve the problem for the first row) and you can't know when this method is being called for the last row, nor do you appear to have access to the current row you're formatting for.

Someone looking to solve that could perhaps fetch the total row count somewhere, keep an internal counter and only execute this when the counter matches the row count.

Another solution may be to do this process somewhere after data is loaded by scanning if there is a collapsed element somewhere.

Thanks!

**Comment by olifolkerd** [comment]
Hey @tominventisbe 

That is a good point you make there. 

I will see if i can get an improvement in for the 4.2 release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @tominventisbe 

I have pushed an update for this to the 4.5 branch that will be released in the next few weeks.

Cheers

Oli :)
