### ISSUE TITLE
Tabbing through filters will scroll header but not body, causing column misalignment

### ISSUE THREAD

**Issue by haferje** [olifolkerd/tabulator#1769]
**Describe the bug**
I have a table with a number of columns that extend well beyond the containing table's width - allowing the table to horizontally scroll.  Each column has a text filter in its header.  When I tab from one column filter in view to the next column filter, either partially in view or entirely obscured by the grid container, the hidden filter textbox is scrolled into view so it is entirely visible.  This scrolls the entire header to the left, but the data rows of the table are unaffected.  This results in the header columns and body columns becoming misaligned, until I attempt to horizontally scroll the grid.

**Tabulator Info**
- Which version of Tabulator are you using?
4.1.5

**To Reproduce**
1. Go to https://jsfiddle.net/haferje/saexz51d/5/
2. Click in the filter checkbox of Col 1.
3. Use the 'tab' key to tab through the header filter text boxes.
4. Once you reach one where the column is not totally in view, see how the header has scrolled, but the body has not.

**Expected behavior**
The body of the table should scroll the same amount as the header, when filter text boxes are given focus.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 71.0.3578.98

**Comment by olifolkerd** [comment]
Hey @haferje 

Thanks for your feedback, 

That is a very interesting point you make there, i hadn't considered that option.

I will look into a fix for that for you. 

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @haferje 

I have pushed a fix for this to the 4.2 branch that will be released on monday

Cheers

Oli :)

**Comment by haferje** [comment]
My initial tests show that it works as expected!
Thank you!
