### ISSUE TITLE
Callback function for onBlur and onChange on cell in a row

### ISSUE THREAD

**Issue by injoum** [olifolkerd/tabulator#1772]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by injoum** [comment]
ah sorry the ticket was posted without me writing the problem specifications, but it's in the title.... sorry about that....

well I have a function that I want to call onBlur and onFocus in angular 6 in text input but there is nothing about that written in the documentation. does anyone have any idea how to perform that without custom editors

**Comment by olifolkerd** [comment]
Hey @injoum 

Please ask questions on StackOverflow, this issues list is for bug fixes and feature requests only.


In answer to your question, tabulator has a wide selection of [Callbacks](http://tabulator.info/docs/4.1/callbacks) to cover almost any usage case.

There is a ***cellEdited*** callback that will be triggered when a cell is edited, that can either be bound on the table as a whole to track any edits:
```js
var table = new Tabulator("#example-table", {
    cellEdited:function(cell){
    //cell - cell component
    },
});
```
or in a specific column definition on only track edits in that column:
```js
{title:"Name", field:"name", cellEdited:function(cell){
    //cell - cell component
    },
}
```
there is also a ***cellEditCancelled*** callback that will be triggered when a cell edited is aborted, that can either be bound on the table as a whole to track any edit aborts:
```js
var table = new Tabulator("#example-table", {
    cellEditCancelled:function(cell){
    //cell - cell component
    },
});
```
or in a specific column definition on only track edit aborts in that column:
```js
{title:"Name", field:"name", cellEditCancelled:function(cell){
    //cell - cell component
    },
}

I hope that helps,

Cheers

Oli :)
