### ISSUE TITLE
Can't pass event to tabulator in angular 6

### ISSUE THREAD

**Issue by injoum** [olifolkerd/tabulator#1773]
**Describe the bug**
I have created a custom editor for an input cell, I want to flush the change in the cell and then navigate to the next cell, but when I used table.navigateNext(). I get the error ReferenceError: e is not defined
    at Tabulator.navigateNext (vendor.js:238497), I don't know if this is a Tabulator bug or an angular bug, or me not knowing how to handle this error.

**Tabulator Info**
- latest version of Tabulator

**To Reproduce**
This is my code for the textEditor: 

let textEditor = (cell, onRendered, success, cancel) => {
      var editor = document.createElement("input");
      editor.setAttribute("type", "text");

      editor.style.padding = "3px";
      editor.style.width = "100%";
      editor.style.boxSizing = "border-box";

      editor.value= cell.getValue();

      onRendered(() => {
        editor.focus();
        editor.style.css = "100%";
      });

      let  successFunc = ()  => {
        table.navigateNext();
        success(cell.getValue());
        
      }

      let successBlurFunc = () => {
        console.log(cell.getValue());
        success(cell.getValue());
        table.navigateNext();
      }

      editor.addEventListener("change", successFunc);
      editor.addEventListener("blur", successFunc);

      return editor;
    }

**Expected behavior**
table.navigateNext() to navigate to the next editable cell.

**Desktop (please complete the following information):**
 - Browser Chrome latest version

**Comment by injoum** [comment]
let textEditor = (cell, onRendered, success, cancel) => {
      var editor = document.createElement("input");
      editor.setAttribute("type", "text");

      editor.style.padding = "3px";
      editor.style.width = "100%";
      editor.style.boxSizing = "border-box";

      editor.value= cell.getValue();

      onRendered(() => {
        editor.focus();
        editor.style.css = "100%";
      });

      let  successFunc = ()  => {
        table.navigateNext();
        success(cell.getValue());
        
      }

      let successBlurFunc = () => {
        console.log(cell.getValue());
        success(cell.getValue());
        table.navigateNext();
      }

      editor.addEventListener("change", successFunc);
      editor.addEventListener("blur", successFunc);



      return editor;
    }

this is a better snippet of the code

**Comment by olifolkerd** [comment]
Hey @injoum 

Thanks for getting in touch,

Looks like you have found a bug there, i have pushed a fix for this to the 4.2 branch which will be released on monday,

Thanks for the headsup.

Cheers

Oli :)
