### ISSUE TITLE
responsiveCollapse conflicts with selectable rows

### ISSUE THREAD

**Issue by tominventisbe** [olifolkerd/tabulator#1775]
**Describe the bug**
When the `responsiveCollapse` column is enabled and `selectable` is true, clicking the responsive column expando (or around it in the column itself) will expand the row, but will also select the row.

**Tabulator Info**
- Which version of Tabulator are you using? 4.1.5

**To Reproduce**
1. Add a `responsiveCollapse` column: `columns: [{formatter: 'responsiveCollapse', minWidth: 42, width: 50, resizable: false, headerSort: true},],`
2. Set `selectable` to true: `selectable: true`,
3. Make the table small enough to see the expando
4. Click the expando
5. The row is now selected as well as expanded

**Expected behavior**
The row is expanded, but not selected.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 65

**Additional context:**
I worked around this problem by attaching a `capture` (this is important) event handler higher up the DOM to invert the selection again.

```js
const isRowSelected = (el) => {
    for (const selectRow of tabulator.getSelectedRows()) {
        if (selectRow._row.element === el) {
            return true;
        }
    }

    return false;
};

tabulator.element.addEventListener('click', (e) => {
    if (e.target.closest('.tabulator-responsive-collapse-toggle') === null) {
        return;
    }
   
    // Invert the selection again.
    const row = e.target.closest('.tabulator-row');

    if (isRowSelected(row)) {
        tabulator.deselectRow(row);
    } else {
        tabulator.selectRow(row);
    }
}, true);
```

**Comment by olifolkerd** [comment]
Hey @tominventisbe 

Thanks for pointing that out, i have pushed a fix for that to the 4.2 branch which will be released on monday,

Cheers

Oli :)
