### ISSUE TITLE
Frozed column in Tree View

### ISSUE THREAD

**Issue by adamxi** [olifolkerd/tabulator#1777]
**Describe the bug**
Hey Oli,

I noticed that having a frozen column seems to glitch on some rows when having a tree view table.

Looking at the screenshot below, first level row cells are correctly placed. However, child nodes in the hierarchy starts with an incorrect offset. This is not the case for all child nodes however.
Using chromes element inspected i have highlighted a cell with an incorrect offset relative to the first "name" column.

**Tabulator Info**
- 4.1.5

**Screenshots**
![image](https://user-images.githubusercontent.com/8067804/52338237-1f9e0500-2a0a-11e9-90a7-ea6a32f417ac.png)

**Desktop**
 - OS: Win 10
 - Browser: Chrome

**Comment by olifolkerd** [comment]
Hey @adamxi 

Thanks for the headsup,

I have pushed a fix for this to the 4.2 branch which will be released on Monday

Cheers

Oli :)
