### ISSUE TITLE
Link Formatter incorrectly parsing URL string from JSON array (4.1.4)

### ISSUE THREAD

**Issue by possiBri** [olifolkerd/tabulator#1778]
**Describe the bug**
When using a link formatter my URL is not being parsed correctly (forward slashes come up as the html unicode version of the character `&#x2f;`)

**Tabulator Info**
- Which version of Tabulator are you using?
4.1.4

- Post a copy of your construct object if possible so we can see how your table is setup
`var tableData = jQuery.parseJSON(Drupal.settings.steinbeck.tabledata);`
`			`
`var table = new Tabulator("#proposals-table", {`
`	data: tableData,`
`	layout:"fitColumns",`
`	index:"sid", //set the index field to the "SID" field.`
`	pagination:"local", //paginate the data`
`	paginationSize:20,`
`	placeholder:"No Proposal Submissions Available",`
`	initialSort:[             //set the initial sort order of the data`
`		{column:"submitted", dir:"desc"},`
`	],`
`	columns:[`
`	    	{title:"Approval Status", field:"approval_status", headerFilter:true},`
`	        {title:"Site Name", field:"sub_url", formatter:"link", formatterParams:{labelField:"site_name"}, headerFilter:true},`
`	        {title:"Submitted", field:"submitted", sorter:"datetime", sorterParams:{`
`				    format:"MM/DD/YYY - h:mma",`
`				    alignEmptyValues:"top",}},`
`	        {title:"Form", field:"form", headerFilter:true},`
`	],`
`});`

One item in the JSON array:

`[{"sid":"153927","nid":"250048","form":" Unvetted Application for a University Community Partnership","site_name":"U.S. Department of State","submitted":"01\/17\/2019 - 8:57am","approval_status":"Needs Review","sub_url":"\/node\/250048\/submission\/153927"}`

**To Reproduce**
1. Create a Tabulator table with a JSON array that contains relative URL string
2. Set one of the columns to this URL field and give it a formatter: Link, pick another field for its label.
3. Refresh the table
4. See that link has been added, but isn't properly formatted/encoded.

**Expected behavior**
I expect the URL string provided in my JSON array to be properly parsed back into a URL.

**Desktop (please complete the following information):**
 - OS: OS X Yosemite
 - Browser: Chrome 
 - Version 71.0.3578.98 (Official Build)

**Additional context**
I am implementing this in a Drupal 7 template using CDN links. Thanks for your help!

**Comment by possiBri** [comment]
After doing some more testing with different versions of Tabulator 4.x with no luck I decided to actually look deeper at how the link formatter is created. I noticed that if I don't specify a urlField param (if the field I'm using _is_ the URL field) that it uses getValue() instead of getData() — I'm not sure if this is the cause as I'm pretty noob with JS/jQuery, but figured I'd point that out. So, noticing the difference I went ahead and chose a different field as the column's base field and then set the fieldLabel and fieldURL params and the link is now being generated correctly.

In the documentation it is implied that you can use the URL field as the base field, but that is what appears to be broken. If that wasn't the intention, then it would be super helpful to clarify in the documentation.

Thanks!

**Comment by olifolkerd** [comment]
Hey @possiBri 

Thanks for getting in touch,

This is happening because Tabulator sanitizes the data to prevent code injection, but i do take your point that in this instance it is counter intuitive.

I will put in a fix for it for the 4,2 release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
I have pushed a fix for this to the 4,2 branch that will be released on Monday.

Cheers

Oli :)
