### ISSUE TITLE
Total loaded and visible records

### ISSUE THREAD

**Issue by diegoleonuy** [olifolkerd/tabulator#178]
Hello
First of all, I must thank you for your great work.
Few people share it with such generosity.
It even shows that your attention to the queries is very correct and fast.

I'm using Tabulator on my intranet.
I already searched and I did not find a simple way to be able to enter an account of how many total records have been loaded and how many records are visible if there is a filter applied.

Thanks since now

**Comment by olifolkerd** [comment]
Hey,

Thanks for getting in touch, it is always great to hear that people are enjoying using Tabulator.

If you want to check the number of rows in the table, i suggest using the ***getData*** function and using its length:

```js
//total number of rows
var totalDataCount = $("#example-table").tabulator("getData").length;

//number of filtered rows
var filteredDataCount = $("#example-table").tabulator("getData", true).length;
```

Let me know if that answers your question.

Cheers

Oli

**Comment by diegoleonuy** [comment]
Thank you very much.
It works perfectly.
I'm already incorporating it.
Thanks again.
