### ISSUE TITLE
Calculation of row height

### ISSUE THREAD

**Issue by adamxi** [olifolkerd/tabulator#1782]
**Describe the bug**
Hey Oli,

It seems that the calculation of row heights does not take css margin top and bottom into consideration.

In my case i need to add a bit of margin to the bottom of my rows to create some row spacing. Setting _margin-bottom_ on the _tabulator-row_ class works fine visually except whenever the table redraws, the vertical scroll position jumps a bit up, because the row height calculation does not add margin to its outerHeight variable.

For now i fixed the issue with the following code patched directly into the tabulator.js file:

```
Row.prototype.calcHeight = function () {

	var maxHeight = 0,
		minHeight = this.table.options.resizableRows ? this.element.clientHeight : 0;

	this.cells.forEach(function (cell) {

		var height = cell.getHeight();

		if (height > maxHeight) {

			maxHeight = height;
		}
	});

	this.height = Math.max(maxHeight, minHeight);

	//this.outerHeight = this.element.offsetHeight;
	this.outerHeight = getAbsoluteHeight(this.element);
};

function getAbsoluteHeight(el) {
	var styles = window.getComputedStyle(el);
	var margin = parseFloat(styles.marginTop) +parseFloat(styles.marginBottom);
	return Math.ceil(el.offsetHeight + margin);
}
```

I realize that this would also be an issue for all element calculations on cells, headers, etc.

**Tabulator Info**
- 4.1.5

**Desktop:**
 - OS: Win 10
 - Browser: Chrome

**Comment by olifolkerd** [comment]
Hey @adamxi 

You are correct Tabulator does not take account of margin on rows, and i plan on it staying that way as the additional maths will slow down the rendered.

The best approach would be to use padding to space things out more. which is taken into account

Cheers

Oli :)
