### ISSUE TITLE
With selectable=false, table.selectRow or row.select() gives a TypeError

### ISSUE THREAD

**Issue by gillez** [olifolkerd/tabulator#1786]
This issue was mentioned in #1610.  However, as that issue is now closed, I am opening this as a new issue.

I have now made a very simple codepen to demonstrate this.  It just sets up a table, sets selectable to false, and adds a rowClick() callback which calls row.toggleSelect()
https://codepen.io/gillez/pen/qgYBRp

The callback is called, however toggleSelect causes a type error because t.modules.select is undefined.  To see this, run the codepen, open the console and click on a row.   If I set selectable to "highlight" it works as expected.  

I think the fix is to either always enable the select module regardless of the value of selectable, or state in the documentation that table.selectRow(), row.select() and similar are not available with selectable=false.

Thanks,
Giles

**Comment by olifolkerd** [comment]
Hey @gillez 

Thanks for the headsup, that is a really easy fix, just need to check that the select property is set on the modules first.

i will include a fix for it in the weekend patch update.

Cheers

Oli :)

**Comment by gillez** [comment]
Hi Oli,

I agree that checking that the select property is set on the modules would stop the TypeError  exception from occurring.  However, wouldn't this stop the select() and toggleSelect() functions from working when selectable is false?  

From your suggestion in [this comment](https://github.com/olifolkerd/tabulator/issues/1610#issuecomment-443431937), this should be possible.  This is either not correct and selectable should be "highlight" (or another value) if you want to select rows programmatically, or the select module should always be enabled regardless of the value of selectable.

TBH, it's not really a problem for me if selectable=false means that the select functions are not available.  It kinds makes sense really.  selectable=false sounds like rows are not selectable.  It's only because you recommended it previously that I'm mentioning it (I think I saw it suggested in another thread as well).

Currently I'm using selectable="highlight" which is working fine.  The reason why I would prefer to use "false" is because I don't want the rows to be highlighted when I hover over them.  To get around this, I have changed the CSS to remove the highlight styling.

Thanks,
Giles

**Comment by olifolkerd** [comment]
Hi @gillez 

Sorry my misscommunication there, i would need to set it if it isnt there. Either way this is a very simple fix, leave it with me and i will resolved it in the weekends patch release.

Cheers

Oli

**Comment by gillez** [comment]
Thanks Oli.   A very quick reply as well. :)

**Comment by olifolkerd** [comment]
Hey @gillez 

I have pushed a fix for this issue to the master branch and will include it in todays patch release.

Cheers

Oli :)
