### ISSUE TITLE
Table switches to classic view if the containing UI has no size on load

### ISSUE THREAD

**Issue by c-dante** [olifolkerd/tabulator#1789]
**Describe the bug**
Fiddle: https://jsfiddle.net/seedante/ukL47r1x/37/

When creating a tabulator table the row manager forces "classic" rendering on init if the table has no size. This causes elements that get their size later (from code, perhaps) to no longer take advantage of virtual rendering, which can crash pages with larger tables.

Modern presentation frameworks often create/destroy/show/hide elements based on some code execution (React, Angular, etc.). They also apply styles based on runtime states, which may developers use as sizing/positioning.

Offending line: https://github.com/olifolkerd/tabulator/blob/3b2ca3c83e80a381d3e187052bd6dd3e570e3223/src/js/row_manager.js#L1139

**Tabulator Info**
Version: 4.1.5

**To Reproduce**
1. Load, it chooses "virtual" correctly.
2. Click "Hide Table" and "Show Table".
3. The render type switches to "classic", despite the element having size.
4. Clicking "redraw" does not fix this issue.

Note that calling `table.rowManager.setRenderMode();` inside the "refreshTable" example will correctly re-draw as virtual, since the table as size. This is not a valid solution since Tabulator does an initial draw as classic mode, which actualizes each row.

**Expected behavior**
When the table is set to virtual, it always renders as virtual. Even if that produces no rows.

**Desktop (please complete the following information):**
Chrome Version 72.0.3626.96 (Official Build) (64-bit)

**Comment by olifolkerd** [comment]
The fact that tabulator must be declared with a height for the virtual DOM to work is extremely well documented. without a height the system has no way to know how to layup the table. (this can be set in CSS or in the ***height*** property of the table itself).

There are many examples of Tabulator working correctly in all the major frameworks, i myself use it in Vue and React without any issue. You must make sure that you instantiate the table after the view has been mounted

If you are having trouble with your setup can i suggest that you create a JS fiddle or Code Pen with an example and we can provide you with some pointers to get things up and running.

Cheers

Oli :)

**Comment by c-dante** [comment]
Is there a particular reason for that design decision? If the layout fails because the DOM isn't refreshed with a height (for example, inside resizable flex parents, etc), then why is the decision to force classic mode correct? I would assume that just rendering nothing is better (if the user wants to coerce virtual rendering).

I'm fine if this isn't considered a bug -- as you said, it's well documented.

**Comment by olifolkerd** [comment]
Hey @c-dante 

You will find that with the advent of the ES8 Resize observer that becomes less of an issue, Tabulator already uses it to track changes in element dimensions where available, but at the moment that is only in chrome. As that roll out to more browsers that will become an issue consigned to history.

As i say I have used it on a lot of projects and not come across the issues you are facing, it is likely that you are simply instantiating Tabulator in the wrong point in the render process, in fact the are libraries built for both Vue and React that implement Tabulator as a component without any of the issues you describe,

If you can create JS fiddle or Code Pen with an example and we can provide you with some pointers to get things up and running and overcome the issues you are facing.

Cheers

Oli :)

**Comment by c-dante** [comment]
After updating the fiddle, I think the problem is fixed when I ask the row manager to set its render style on when I set the data -- if the table is instantiated hidden, the row manager never updates the render style (even if it gets its size later).

I'm A-OK with that being the design decision, so no need to really change that. I think the unexpected thing for me is when element pop in and out of existence, that state can change without being told to update. Closing the issue.

**Comment by olifolkerd** [comment]
Great to hear you got it working! :)

**Comment by c-dante** [comment]
Just to update if anyone else hits this, I fixed it by calling `setRenderMode` before calling `setData` in case sizing/visibility changed between instantiation and data.

Example update on the fiddle:
https://jsfiddle.net/seedante/ukL47r1x/46/

**Comment by c-dante** [comment]
Woof, sorry to be terrible about this, but that fix doesn't work.

So, turns out since the virtual hook is set on row manager init. There doesn't seem to be a way to hack around init with 0 height and then set virtualization, or to transition between classic and virtual rendering at runtime.

**Comment by olifolkerd** [comment]
As I keep on saying please post a JS Fiddle and I can help you get it working. there are many people that have had no problems setting things up but I need to see ur config to offer u the advice to fix it.

**Comment by c-dante** [comment]
This fiddle shows the issue I'm hitting, and I'm 100% okay with that use case not being supported by tabulator.
https://jsfiddle.net/seedante/ukL47r1x/69/

The flow is:
On load, table has a height, everything virtualizes nice.
If you show/hide the element (even with redraw when hidden), everything is still nice.

If you create the table while hidden, the table get set to classic -- showing the element after, even having it redraw after it is shown and has height, will never get out of classic mode.

My question (since this is definitely not an issue/bug, as the docs are very clear about it) is: why?

If I'm able to create the virtualized table with a height, hide it (so, no longer has a height), and set data or redraw, there's no problem. But if I happen to make the table instance with no element height, it gets forced into classic mode.
