### ISSUE TITLE
Table Destroy has console error, undeclared self variable

### ISSUE THREAD

**Issue by clurect** [olifolkerd/tabulator#1790]
**Describe the bug**
I'm really excited about the new release, I found this testing it today:
In tabulator destroy there is a `self` where it should be `this` here:
https://github.com/olifolkerd/tabulator/blob/master/src/js/core.js#L579

**Tabulator Info**
- Tabulator v4.2.0

**To Reproduce**
1. setup a new table
2. run `table.destroy();`

**Expected behavior**
To delete the table without console errors

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Chrome
 - Version 71.0.3578.98

**Comment by clurect** [comment]
Upon further use I realized that line should be changed to:
`if(this.options.reactiveData && this.modExists("reactiveData", true)){`

Both conditionals were referencing `this.table` which should have been just `this`

Thanks

**Comment by olifolkerd** [comment]
Hey @clurect 

Thanks for getting in touch, That is definitely a bug, i will get it fixed in this weekends patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @clurect 

I have pushed a fix for this to the master branch and will include it in this evenings release.

Cheers

Oli :)
