### ISSUE TITLE
4.2.0 ReactiveData: Uncaught (in promise) ReferenceError: origFuncs is not defined

### ISSUE THREAD

**Issue by Tommy-Hoo** [olifolkerd/tabulator#1792]
**Describe the bug**
Reactive data module throws an error on calling **setData()** method. If I switch the **ReactiveData** option to **false**, that error is not going to occur.

**Tabulator Info**
- Which version of Tabulator are you using?
- 4.2.0

**To Reproduce**
1. Go to 'https://codepen.io/wonderfultommy/pen/zeWVpE'
2. Click on 'Set Data' button
3. See error

**Expected behavior**
The new data should be set properly without error message

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome 70.0.3538.110 (Official Build) (64-bit)
 - Version 4.2.0

**Additional context**
Maybe there was an issue in **ReactiveData.prototype.unwatchData** method at 
https://github.com/olifolkerd/tabulator/blob/c09b7480499542f1fbf5f3643895fe3d2cf9a14b/src/js/modules/reactive_data.js#L155. 
I'm confused on that the "value" is always "origFuncs.push" when it restores the methods of Array. Should we use "this.origFuncs[key]" ?

Thanks,
Tommy

**Comment by olifolkerd** [comment]
Hey @Tommy-Hoo 

Thanks for getting in touch, That is definitely a bug! i will get it fixed in this weekends patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
I have pushed a fix for this to the master branch and will include it in a release this evening

Cheers

Oli :)
