### ISSUE TITLE
Add deleteRows function that deletes multiple rows with single redraw

### ISSUE THREAD

**Issue by pklog** [olifolkerd/tabulator#1793]
**Is your feature request related to a problem? Please describe.**
I will preface this request in that I haven't tried this with version 4.2 yet. Due to our process I am still at 3.5. As far as i can tell there isn't efficient way to bulk delete multiple rows from a table. Each row has to be deleted separately driving a bunch of extra rendering. I see that this capability has been handled for adding and updating already.

In analyzing the 4.2 source code, it looks like you aren't far from offering this capability as it looks like the row manager and row has some use of a function parameter "blockRedraw", but it doesn't appear that that value will ever be true nor does it seem that the API offers a means to specify the 'blockRedraw' value.

**Describe the solution you'd like**
A new function 'deleteRows' should be made available, similar to deleteRow, but instead takes an array of row keys. Each row should then be removed prior to a redraw occurring.

**Describe alternatives you've considered**
So far I've tried 'setData', but found an improvement 'replaceData'. This is far more performant than doing several deletes. 

**Additional context**
My data set so far has been in the 100s of rows with 12 columns.

**Comment by olifolkerd** [comment]
Hey @pklog 

Thanks for getting in touch, for the time being, replace rows is your best bet.

But i do see where you are coming from, there is an addRows function that lets you add multiple rows before triggering a redraw but o equivalent for removing them, i will add it to the roadmap for the next release.

The internal functionality you are referring to is used for various internal functions within the table, but would be hard to extend for a public method.

Cheers

Oli :)

**Comment by Rodbjartson** [comment]
Sounds like a nice little enchancement there

**Comment by hookedupjoe** [comment]
For this one I was able to make it perform well  while removing / adding hundreds of documents with the reactiveData setting turned on.

I submitted a change request to include the changes needed to allow for a well performing mass update of data.  Naturally you can review / test / update as needed.   More details on the 2084 merge request.

**Merge Request:** 
Update to allow flags for add / remove performance #2084

**Comment by olifolkerd** [comment]
Hey @pklog 

I have just pushed an update to the 4.5 branch that allows the ***deleteRow*** function to take an array of rows to be deleted. This should be released in the next few days.

```js
table.deleteRow([10, 15, 27]);
```


Cheers

Oli :)
