### ISSUE TITLE
add rowUpdated callback

### ISSUE THREAD

**Issue by morficus** [olifolkerd/tabulator#1794]
**Is your feature request related to a problem? Please describe.**
When making edits in a grid there is no clear way to identify when something with in a specific row has been updated. Tabulator only provides a data-level callback (`dataEdited`) and a cell-level callback (`cellEdited`)

**Describe the solution you'd like**
* For the `rowUpdated` to be triggered when any data in that row gets updated
or
* Create a new callback named `rowEdited`
or
* Update the documentation to make it clear that the `rowUpdated` callback does not get triggered on regular data updates like `cellEdited` and provide alternatives.

**Describe alternatives you've considered**
Currently I am working around this by using the `cellEdited` callback and then calling `cell.getRow()` inside of it. While this does work, it feels a bit clunky (personal opinion) and this work around isn't documented anywhere.

**Additional context**
When making edits in a grid, Tabulator offers two levels of granularity for detecting those changes:
* broad/coarse-grained with the `dataEdited` callback, which returns the entire table data
* granular/fine-grained with the `cellEdited` callback, which returns specific cell that was changed

This request is for a medium-granularity callback at the row level or at the very least a documentation update to provide alternatives.

**Comment by olifolkerd** [comment]
Hey @morficus 

Thanks for getting in touch.

There is is one primary reason for there not being a rowUpdated callback. Tabulator simply has no way to know when that is the case.

Fine for things like input editors it could check if you have tabbed into the next cell on the same row, but for a lot of editors such as star edtiors or progress editors the action of the user making a selection on the editor ends the edit and does not move focus onto the next cell at which point the rowUpdated callback would erroneously fire,

When making updates to tabulator i have to consider all of the uses cases and in this case i cant see a reliable way of tracking the concept of a row update

also there is nothing to stop you from getting the row data back on a cell edit, you can call the `cell.getRow()` function to get the row component.

Cheerss

Oli

**Comment by morficus** [comment]
Hi @olifolkerd - thanks for the detailed response. 

You suggestion around using `cell.getRow()` is exactly what I ended up doing. 
Would it be possible to update the documentation to include this?

**Comment by olifolkerd** [comment]
Hey @morficus 

I am looking at adding a case study section to the website so i will cover it in that when it is up.

Cheers

Oli :)
