### ISSUE TITLE
Any short way to create auto IDs when addding Rows?

### ISSUE THREAD

**Issue by mikexmagic** [olifolkerd/tabulator#1795]
Hi guys,

I'm wondering, if there is a way to auto increment IDs when adding rows using addData or addRow.

I like to offer an empty table to the user. The user is able to add persons to this table row by row. It would be nice, if record IDs are created automatically in a callback or something else... 
Maybe there is already an option?

Thx for your help ;-)

**Comment by nigels-com** [comment]
We could use something similar.  We number the rows in order before handing them over to Tabulator, assign increments for inserted rows, then strip then out once we're done editing.   Seems like something that could be wired in as a module.  But perhaps a bit beyond my JS wizardry, just now.

**Comment by olifolkerd** [comment]
Hey Guys,

You could use a mutator that references a global variable that increments with each new row.

More information can be found in the [Mutator Documentation](http://tabulator.info/docs/4.2/mutators#mutators)

I hope that helps,

Cheers

Oli :)
