### ISSUE TITLE
Frozen column glitching

### ISSUE THREAD

**Issue by adamxi** [olifolkerd/tabulator#1796]
**Describe the bug**
Hey Oli,

I have noticed some glitching when side scrolling while having a frozen column.
The bug is actually present if you side scroll in the frozen column demo: http://tabulator.info/examples/4.2?#frozen-col
You can notice that the frozen row sometimes flickers and slightly moves for a frame. The bug is more present when side scrolling fast.

**Tabulator Info**
- 4.2.0

**Desktop (please complete the following information):**
 - Browser: Chrome

**Comment by olifolkerd** [comment]
Hey @adamxi 

There is a very slight momentary jitter to the scroll if the computer is under load, but i wouldn't say it constitutes an issue, maybe a possible render improvement in the future, 

all improvements to the rendered are tracked on issue #1437 
Cheers

Oli :)
