### ISSUE TITLE
layout : "fitDataFill" is not working as expected

### ISSUE THREAD

**Issue by swatiwak** [olifolkerd/tabulator#1798]
layout : "fitDataFill" is not working as expected.
Aa per definition fitDataFill layout mode functions ensures that rows are always at least the full width of the table.

When I have 20 columns, this works pretty well.
But when I have 3 columns, columns occupy required width and there is empty column in remaining width. Whereas it should work as fitCoumns as per definition **rows are always at least the full width of the table.**

If I use layout: "fitColumns" then table having 20 columns, columns get shrinked. 

`var tabulator = new Tabulator("#upload_grid_data", {
                            height:"400px",
                            layout:"fitDataFill",
                            tooltips:true,            //show tool tips on cells
                            tooltipsHeader:true,
                            movableColumns:true,      //allow column order to be changed
                            resizableColumns: true,
                            placeholder:"No Data available",
                            layoutColumnsOnNewData:true,
                            columns:[]
                });`

**Comment by olifolkerd** [comment]
Hey @swatiwak 

That is exactly how fitDatafill is supposed to work, it fits all the columns to their data then stretches the row to visually take up the remaining space.

Cheers

Oli :)

**Comment by swatiwak** [comment]
Hey @olifolkerd ,

layout: "fitDataFill" is not working in the same way.
It is not stretching to take up remaining space.

Could you please check once.

Thanks in advance.

**Comment by olifolkerd** [comment]
@swatiwak It is working exactly as expected, a functioning example can be found [Here](http://tabulator.info/examples/4.2#fittodatafill)

**Comment by glancia** [comment]
As per the definition in the official page, no, it's not working as expected.

![image](https://user-images.githubusercontent.com/26585392/59049048-84a12480-885d-11e9-9648-580f285af6fe.png)

**Comment by olifolkerd** [comment]
Hey @glancia 

That is exactly what it is supposed to do, it is working correctly, if you look at the ***fitData*** layout the table background is visible. in fit data fill the row is stretched to fill the gap.

If you want to stretch the column contents to fill it you should be using ***fitColumns*** layout mode

Cheers

Oli :)

**Comment by powerbuoy** [comment]
Old and closed issue, but I'd like to add that I agree that the current behaviour is a little disappointing. One would hope it would work just like fitColumns until they no longer fit at which point you'll get a scrollbar.

With fitDataFill you get a huge whitespace to the right in high res, but it work fine in low res. With fitColumns it looks great in high res, but the cols are now absolutely tiny in low res.
