### ISSUE TITLE
Add the same row (same row_id) multiple times.

### ISSUE THREAD

**Issue by muhaNERD** [olifolkerd/tabulator#18]
What is the point for allowing multiple rows with the same id to be added?

I suggest giving the user the possibility to detect duplicate by defining a custom "equals" method. For example, two rows are equal when they have the same id...

**Comment by olifolkerd** [comment]
it was more out of flexibility than anything, as there are more ways to select a row than by id alone. but you raise a point, i will look at adding an option to restrict ids.
