### ISSUE TITLE
Feauture request: add delay (n sec) option to header filter

### ISSUE THREAD

**Issue by MikhailKlemin** [olifolkerd/tabulator#180]
Hi!

Does it possible to add a delay to header filter? For example I want to filter "New York" when I type it tries to filter N, then Ne, then New and so on, which is quite annoying on relatively large dataset.  
Would be nice to have a possibility to add n-sec delay, so it will be enough to type whole word to filter off. 

Thanks, Mike!

**Comment by olifolkerd** [comment]
Hey Mike,

You raise a good point there!

I will have a look at adding that this weekend.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hi Mike,

You raise a good point there!

If you were using a custom editor as the basis for your header you could wrap the ```js  cell.trigger("editval", editor.val()); ``` function in a setTimout to add the delay.

I could see this being very useful in general. i will have a think over the weekend and see if i can make it a standard feature of the header filters as it would be very helpful.

Cheers

Oli

**Comment by MikhailKlemin** [comment]
Hi, thanks! I just thinking abou it, would be good if timer resets after
each keyup, so that you can type a long string without interruption.

9 февр. 2017 г. 9:34 PM пользователь "Oli Folkerd" <notifications@github.com>
написал:

**Comment by olifolkerd** [comment]
I have added a 300ms rolling delay to the input to prevent excessive table redrawing.

Thanks for the suggestion!

Cheers

Oli

**Comment by MikhailKlemin** [comment]
hi, I just tried 2.10 and I see no difference, well I seen the 300 delay in the source file (however there my javascript expertise ends) , but when I type in header filter it tries to filter just right away, instead to wait when I finish type the search  phrase ...

**Comment by olifolkerd** [comment]
How have you downloaded the update? it will not be available through a dependency manager yet as i have not made a new release for it yet, that will be coming with a few more upgrades in the next few days, for now you will need to download the tabulator.js file from github.

**Comment by MikhailKlemin** [comment]
Hi, yes I downloaded as zip from github, and replaced js and css by new (downloaded) ones. But hang on please I will double check later to be sure I do it all in the right way.

**Comment by olifolkerd** [comment]
There shouldnt be a noticeable delay before it refreshes the view, 

300ms is enough time for people to type normally without it triggering on every single keypress, but will cause the list to refresh quickly after they take a quick pause. if you are typing slowy then you can expec the list to refresh after each key press.

**Comment by MikhailKlemin** [comment]
Well I guess it depends on personal preferences, however other tables are using much longer default delays, like footable uses 4 times longer default delay.

I have tried to simple change 300 to 3000 in the tabulator.js, but seen no difference... 

```
cellEditor.on("keyup", function(e){
	var element = $(this);
	if(typingTimer){
 	 clearTimeout(typingTimer);
	}
	typingTimer = setTimeout(function(){
	 filter.trigger("editval", element.val())
	},3000);
});
```

**Comment by olifolkerd** [comment]
are you tabing or clicking out of the filter element or pressing enter after you have entered your search term, this will trigger the search instantly.

What browser / OS are you using.

**Comment by olifolkerd** [comment]
i have now tried on chrome and ie and cannot seem to replicate your issues,

have you tried force refreshing your browser incase you are running of a cached version of the library
