### ISSUE TITLE
option to tell 'select' editor not to open the dropdown & allow up/down navigation ?

### ISSUE THREAD

**Issue by ducwings** [olifolkerd/tabulator#1804]
**Is your feature request related to a problem? Please describe.**

Problem: can't use Up/Down arrow keys to navigate around the table when it focuses on a select editor.

**Describe the solution you'd like**

- Have an option to tell 'select' editor not to open the dropdown & allow up/down navigation ?
- Or allow navigation (using keyboard) but don't enable "Edit Mode" yet until user press "Enter" on a Cell to start editing it.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

Thanks.

![image](https://user-images.githubusercontent.com/18273254/52887147-92eef780-312b-11e9-847a-22dd48c74aa8.png)

**Comment by olifolkerd** [comment]
Hey @ducwings 

Nice idea, i will add it to the roadmap for the 4.3 release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @ducwings 

I have just pushed an update to the 4.5 branch that adds a new ***verticalNavigation*** editorParam to a lot of editors to make it easier to customise the navigation experience.

This should be released in the next few weeks.

Cheers

Oli :)
