### ISSUE TITLE
Wraptext inside the cell value

### ISSUE THREAD

**Issue by kevalkothari** [olifolkerd/tabulator#1805]
**Is your feature request related to a problem? Please describe.**
Currently when making column width smaller it hides text and gives ...   is it possible to show full text in any resized width by increasing row height?

**Additional context**
https://www.dropbox.com/s/0i4weodflqo2t41/2019-02-16_12-21-57.png?dl=0

**Comment by Alarich** [comment]
I believe You are looking for the textarea formatter, described here:
http://tabulator.info/docs/4.2/format#format-builtin

**Comment by kevalkothari** [comment]
Thanks @Alarich  that's exactly what I was looking for
