### ISSUE TITLE
Tabulator - Autocomplete - filterList/searchFunc pass in items rather than values

### ISSUE THREAD

**Issue by Jaise** [olifolkerd/tabulator#1808]
On line 13081 of the tabulator.js filterList() function. When checking editorParams.searchFunc, it is passing in 'values' rather than 'allItems'. This prevents the searchFunc from using the item as objects, only providing the string values and erroring out later indicating that it cannot add ".ele" to type string.

By providing the 'alItems' variable instead, the searchFunc now works with your example searchFunc.

Hopefully this makes sense. I have corrected it in my un-minified version but it would be nice to see this push to production as I am sure others will encounter this issue as well. Let me know if you'd like more information on this. Thank you.
![image](https://user-images.githubusercontent.com/1450710/52916524-d79aa000-329d-11e9-9525-a87396c878a3.png)

**Comment by Jaise** [comment]
This issue also exists in v4.2

**Comment by olifolkerd** [comment]
Hey @Jaise 

Thanks for getting in touch,

This is not a bug, the functionality of the editor matches the description in the documentation as an array of possible values.

Having said that i do understand where you are coming from and think that it could be a useful feature to make more information available, so i will add it to the roadmap for the 4.3 release. Though it is not as simple as returning the ***allItems*** array as that contains other properties that are for internal use of the editor only.

In the mean time you could easily [Extend Tabulator](http://tabulator.info/docs/4.2/modules#module-edit) with your own [Custom Editor](http://tabulator.info/docs/4.2/edit#edit-custom) if you want more bespoke functionality

Could i ask that in future you use one of the defined "Bug" or "Feature" issue templates when you are creating an issue as it will guide you through providing the information i need to take things further.

Cheers

Oli :)

**Comment by Jaise** [comment]
@olifolkerd 

Thanks for your response. I suppose I understand what you are referring to. I was simply using your example with my '_values_' defined as objects rather than '_true_' and when using the **searchFunc** I was receiving errors as **item.value** is null i.e. string values don't have a **.value** property. 

When I went looking for why I came across the section of code I outlined previously and all other methods were using '_allItems_' and the **searchFunc** was using '_values_'. Furthermore, I was receiving errors if I simply returned the '_values_' without creating and returning a '_matches_' array. This is because when it was trying to '**fillList**', the returned values do not have an _item.element_ and I received more errors. All of the **filterList** functionalities besides **searchFunc** add the '_item_' object to _matches_ where the way it is now, **searchFunc** would only add a string and cause issues.

This is why I identified it as a bug.

Understanding what you are meaning about exposing 'allItems' the 'fix' I instituted is what allowed me to check the values. I just check 'allItems' .value and add the whole item and don't alter any of the other properties.

Hopefully what I said makes sense and if I can help more, let me know. I will use the templates in the future, forgive me for overlooking that.

![image](https://user-images.githubusercontent.com/1450710/52917157-4deed080-32a5-11e9-8296-e6a9fbdd031e.png)

**Comment by Jaise** [comment]
The way it was previously;
1) matches would be set to an array of string.
2) would be set to that array of strings.
3) would attempt to iterate that list of strings and use each string as an object trying to access a .element property which does not exist on strings.

![image](https://user-images.githubusercontent.com/1450710/52917251-7c20e000-32a6-11e9-95fd-f924e2d88124.png)

**Comment by KES777** [comment]
Issue related to #1647

**Comment by olifolkerd** [comment]
@KES777 

As i described above this is not a bug, the fact that the original function exposed internal variables from inside Tabulator was very much a bug and this was a simple fix.

As i mentioned in my comment (and have tag as an enhancement) i will be looking to improve this option in the 4.3 release to give a much wider range of access to information in the function, but this will be done in a controlled manner that dosnt expose internal functional objects.

Cheers

Oli :)

**Comment by KES777** [comment]
Now I understand you. The bug was with this: ![__](https://user-images.githubusercontent.com/799021/53825208-71d93400-3f7e-11e9-89dc-0233b479f2b1.jpg)

And after fixing it you will fix an example that @Jaise pointed

**Comment by olifolkerd** [comment]
The 4.6 upgrade, coming later this weekend includes an overhaul to the autocomplete editor which should help with this.

Cheers

Oli :)
