### ISSUE TITLE
Cannot read property 'options' of undefined when destroy() function called

### ISSUE THREAD

**Issue by ElijahKaftanov** [olifolkerd/tabulator#1809]
TypeError: Cannot read property 'options' of undefined
Tried to execute block 
```
if(self.table.options.reactiveData && this.table.modExists("reactiveData", true)){
	this.table.modules.reactiveData.unwatchData();
}
```

Tabulator 4.2
React Tabulator 0.7.11

**Comment by olifolkerd** [comment]
This is a duplicate of #1790 and was fixed in the 4.2.1 release yesterday
