### ISSUE TITLE
Seeking advice on write back to Rest Service

### ISSUE THREAD

**Issue by doghousedev** [olifolkerd/tabulator#1812]
I just love Tabulator!  I am successfully using it to format tables on incoming data retrieved from a REST service from our SaaS. The responses are easy to implement into Tabulator and display in an <div> on a custom form (JSP page).   

My desire, like many, is to send a POST, PUT, DELETE to the REST service of Jthe tabulator JSON formatted data changes and deletions.  I know Tabulator is not intended for CRUD processes, but what is the a "best practices" or coding pattern that I can follow from an example of how to implement this.   I saw requests to add a Tabulator method that returns changes only, but it is not something currently implemented (or may never be).

I  would use a "Save" button to initiate a method/function/call(s) to the REST service to process the JSON. I am a little confused on how I would go about handling what was deleted, what has changed, and what was added to the Virtual DOM so that I could extract that info for the REST call. 

Thanks in advance.   Examples would be greatly appreciated. 

Ron Dog

**Comment by Rodbjartson** [comment]
Hey I cannot help you with this.

However, this page is now for bug reports only, please go to stackoverflow and ask within the tabulator tag.

**Comment by doghousedev** [comment]
Ok. Thanks. I'll try there
