### ISSUE TITLE
Combine Local Data with Ajax Paging / Sorting / Filtering

### ISSUE THREAD

**Issue by bjth** [olifolkerd/tabulator#1814]
**Is your feature request related to a problem? Please describe.**
When using AJAX for paging, sorting and filtering, the first time the table loads our backend code goes and gets the column headings and the first page of data. It would be great if there was a way to disable the first AJAX page load, and also set the maxPages manually.

For example server loads columns and injects them into the columns parameter, server loads data and injects that into the data property. There is currently no way to set the maxPages to expand the pagination control (table.setMaxPage) doesn't seem to work.

**Describe the solution you'd like**
To be able to pass the maxPage size on table initilization, and a set of columns and data, while still taking advantage of the "remote" pagination and sorting and filtering.

**Describe alternatives you've considered**
Writing my own pagination control.

**Comment by olifolkerd** [comment]
Hey @bjth 

Thanks for getting in touch, if you set the ***ajaxURL*** to ***false*** it should prevent the first load, you can then set the URL by passing it to the ***setData***

If you believe you are experiencing issues with the ***setMaxPage*** function please create a JSFiddle or Code Pen that highlights the issue as it is quite hard to isolate issues without a working demonstration.

Cheers

Oli :)
