### ISSUE TITLE
Editable data bug

### ISSUE THREAD

**Issue by labidus** [olifolkerd/tabulator#1815]
The 2 samples related to dateEditor  or autocompEditor have an issue. But can be corrected easily by removing the "change" event, just keep the blur. 

Also the textarea is nearly impossible to edit as soon you enter a character at least with Chrome.
I try to make it work by copying the code, but the issue is related to cell.getRow().normalizeHeight();

As soon as cell.getRow().normalizeHeight(); is called, it cancel the edition, this is the main issue. I guess correcting the behavior of cell.getRow().normalizeHeight will correct the edition of textarea and maybe the 2 others without any hack. 

**Tabulator Info**
- Lastest version
- I use the demo for the edition of dateEditor  or autocompEditor, for the textarea just a editor: "textarea" with formatter: "textarea"

**Comment by olifolkerd** [comment]
Hey @labidus 

I cant seem to replicate your issues, could you create a JSFiddle or Code Pen that replicates the issue, i can then isolate the problem.

Cheers

Oli :)

**Comment by labidus** [comment]
one way easy to replicate using EditableData  http://tabulator.info/examples/4.2#editable
just edit the date by using the button, it will end as soon you push the button

[
![image](https://user-images.githubusercontent.com/10580216/53640260-cb95d300-3bf9-11e9-969d-8d45e0415d3c.png)
](url)

I will check later for adding another one in fsfiddle with a textarea thank!!

**Comment by olifolkerd** [comment]
Hey @labidus 

Thanks for the graphic, that was very helpful, that should be a quick fix, i will have a look into it later today.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @labidus 

I have updated the documentation for the date editor, the example had a change event in it, that it didnt need as you stated.

The textarea and autocomplete editors are working correctly for me in all browsers. if you feel yuo are having issues, please created a Code Pen or JS fiddle that demonstrate the issue as it may be related to a specific configuration of your table.

Cheers

Oli :)

**Comment by labidus** [comment]
ok I was not able to reproduce with jsfiddle the issue i was having, maybe 4.2.2 resolved the issue i will recheck, thanks

**Comment by labidus** [comment]
One thing, when you edit when you push HOME/END to move the cursor at the begining or end of the input it cancel the edition :)

**Comment by labidus** [comment]
Also one suggestion would be to select the text when you start editing text because you end up at the end of the text, when you edit number its hard a little bit, you end up push home with shft to select and get out of the selection :)
