### ISSUE TITLE
exclusion of null _children in datatree

### ISSUE THREAD

**Issue by pythonBerg** [olifolkerd/tabulator#1816]
It would be great if tables that use the datatree show expand element if not only the typeof childfield  is not undefined, but also if the value of the child field is not null. I think the code in row.js, row 556 is what would be modified but I haven't figured out to build modification. This would support serializers for both parents and single entities

		if(self.table.options.dataTree !== false && self.table.modExists("dataTree") && typeof data[this.table.modules.dataTree.getChildField()] !== "undefined" && data[this.table.modules.dataTree.getChildField()] !== null){
			this.table.modules.dataTree.initializeRow(this);
			this.table.rowManager.refreshActiveData("tree", false, true);
		}

**Comment by olifolkerd** [comment]
Hey @pythonBerg 

Thanks for getting in touch, im afraid i don't see what your usage case is. If you have one child putting that as one element in an array is not particularly hard, if you need to be able to parse data into tabulator i can show you how to use the ***ajaxResponse*** callback

Cheers

Oli :)

**Comment by pythonBerg** [comment]
Use case is this...I serialize records that may or may not have children.
My serialiizer will create json where _children = null for those without.
When presented in Tabulator, every item have a child expand button. When
pressed, things fail with None cannot be iterated. It fails immediately if
tree expanded option set to true

I am post processing my json to remove _children = null. Would be nice to
not have to loop another time when this is already done at rendering.

Thanks. Becoming bigger fan of tabulator every day...

**Comment by olifolkerd** [comment]
Hey @pythonBerg 

Ahh sorry i think i misread your earlier statement, there is actually already an issue about the 'null' condition, which will be fixed in the next patch release.

Its great to hear you are enjoying Tabulator!

Happy Tabulating!

Oli :)
