### ISSUE TITLE
Exception occurred when adding new row.

### ISSUE THREAD

**Issue by SuperXuTeng** [olifolkerd/tabulator#1817]
exception js : reactive_data.js

exception position : override array push function 

exception message : "Uncaught TypeError: undefined is not a function"

exception reason : Array.from(arguments);  not be supported by some browser's or be out of date 

solution : replace to  Array.prototype.slice.call(arguments);

**Comment by olifolkerd** [comment]
Hey.

Please can you recreate this issue using the bug issue template when
creating a bug. It prompts you for all the information I need to fix an
issue.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
@SuperXuTeng Could you confirm which browser you are experiencing this on? 

If the array.push function is missing on that browser then your original call to push to the array would also have failed in the first place.

In this case i would suggest if you want to push to arrays you need to use a pollyfill in your code to add that functionality.

Cheers

Oli :)
