### ISSUE TITLE
select child rows on tree grid

### ISSUE THREAD

**Issue by shaulnaim** [olifolkerd/tabulator#1819]
I tried to add a select boxes to tree grid soi will be able to select the parent in tree grid and make is children selected automatically... but it seems not to work

can you add this feature?
thanks
Shaul

**Comment by Rodbjartson** [comment]
Could you create/draw an image for this so we can see exactly what you mean in your suggestion?

**Comment by shaulnaim** [comment]
https://www.ag-grid.com/best-angular-2-data-grid/tree-data.mp4 
selecting a parent will select his children

**Comment by Rodbjartson** [comment]
Seems like a handy feature!

**Comment by olifolkerd** [comment]
I have pushed this feature to the 4.6 branch that will be released next weekend.

You will be able to enable it by setting the ***dataTreeSelectPropagate*** option to ***true***

```js
var table = new Tabulator("example-table", {
   dataTreeSelectPropagate:true,
});
```

Thanks for the suggestion!

Oli :)
