### ISSUE TITLE
Exporting comma delimited - deal with imbedded comma

### ISSUE THREAD

**Issue by KeeperSparky** [olifolkerd/tabulator#182]
In the download function, when you download to CSV, you should check the cell content for imbedded commas.

After this line
*var value = typeof row[field] == "object" ? '"' + JSON.stringify(row[field]) + '"' : row[field];*

		// Check for imbedded commas
		if (value && value.indexOf(",")>=0) {
			value = '"'+value+'"';
		}

Roughly line 705

**Comment by olifolkerd** [comment]
Hey,

Thanks for the suggestion, i am having an overhaul of the CSV generation section this weekend, so i will have a look at this shortly.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey,

Version 2.11 of Tabulator now has enhanced CSV generation.

All data is automatically sanitised and escaped so there are no data import issues.

You can also set a custom delimiter character using the new options object:

```js
$("#example-table").tabulator("download", "csv", "data.csv", {delimiter:"."}); //use fullstop delimiter in CSV
```
Full information can be found [here](http://olifolkerd.github.io/tabulator/docs/#download)

Cheers

Oli

**Comment by KeeperSparky** [comment]
Thanks..

 

Very nice product, nice enhancement idea.    How would someone use it to create a tab delimited file though?

**Comment by olifolkerd** [comment]
Not a problem!

The following code will generate a tab delimited file:
```js
$("#example-table").tabulator("download", "csv", "data.csv", {delimiter:"\t"});
```

Cheers

Oli

**Comment by KeeperSparky** [comment]
Thanks, I suspected as much, but wanted to make sure…

 

Are you removing dependencies?   There is a nice library for doing XLSX exports…

**Comment by olifolkerd** [comment]
Which library would you recomend for the xlsx exports? I would be happy to add the integration.

**Comment by KeeperSparky** [comment]
https://github.com/SheetJS/js-xlsx

 

Very nice library and very active

**Comment by olifolkerd** [comment]
Thanks. I will have a look into it this week

**Comment by MikhailKlemin** [comment]
Hi Oli,
I can not confirm right now with example, but it seems that comma in the multiline header still messes out CSV
for example {title:"More tools per 10,000 people"} breaking CSV column on comma.

**Comment by olifolkerd** [comment]
Hey,

Good Spot! turns out it was only esc aping the values not the titles. i have just committed a fix for this.

Cheers

Oli
