### ISSUE TITLE
Enable de posibility to select more than just 1 row with SelectableRangeMode:"click" enabled

### ISSUE THREAD

**Issue by VeinzX** [olifolkerd/tabulator#1820]
Just the title.

If i enable SelectableRangeMode:"click" i can't select more than one row without holding CTRL, if disable that option i can select more than 1 row by clicking on them

Thanks.

**Comment by olifolkerd** [comment]
Hey @VeinzX 

Thanks for getting in touch, That is the whole point of the ***click*** mode, the only way to select a range of rows is to click with ctrl held, i will improve the documentation to make that clearer.

Thanks for your feedback.

Cheers

Oli :)
