### ISSUE TITLE
Ability to detect row selection change from within a cell

### ISSUE THREAD

**Issue by morficus** [olifolkerd/tabulator#1821]
**Is your feature request related to a problem? Please describe.**

A common use case for selecting a row is to create a left-most column with some type of element that toggles the row selection (this approach has even been [recommended by Oli in the past](https://github.com/olifolkerd/tabulator/issues/789)). A common UI control for cases like this is a checkbox (checked = select row, unchecked = deselect row).

Another common use case with selectable rows is having the ability to select all rows at once (which can also be done programmatically using [`table.selectRow()`](http://tabulator.info/docs/4.2/select#manage) 

The challenge is that when all rows are selected programmatically, that left-most cell responsible for toggling individual row selection has no way of knowing the "selected state" of its row. Meaning that by programmatically selecting all rows there is no way to change the UI element in the individual cell (in this example, selecting the checkbox and therefor the rows all end up selected but the checkbox remains unchecked).

**Describe the solution you'd like**
Tabulator currently has a [number of row-selection callbacks](http://tabulator.info/docs/4.2/callbacks#select) but they are only available at the table and row level. What I would like to see if for these callbacks to be available at the cell-level as well. That way individual cells can change as needed based on row selection.

**Describe alternatives you've considered**
One solution I have in mind is to use CSS to hide/show the UI element responsible for row selection since Tabulator will add the class tabulator-selected to anything that is highlighted. But this seems more like a hack and won't work well for situations like using a checkbox.

Another alternative (which I haven't tried yet) is to use the [MutationObserver API](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) to detect when a class is added or removed from the row.

**Additional context**
I originally [asked this question on StackOverflow](https://stackoverflow.com/questions/54772921/detect-row-selection-change-from-inside-a-cell-component) but haven't gotten any suggestions as yet.

**Comment by morficus** [comment]
Here is my custom formatter using the `MutationObserver`.
It turned out much better than expected and seems to be a suitable alternative, predictable alternative for the time being.

```
/**
 * A custom formatter/cell to enable the selection of an individual row
 *
 * @param {Object} cell Tabulator Cell object
 * @returns {HTMLElement}
 */
export default function(cell) {
  const checkbox = document.createElement('input')
  checkbox.type = 'checkbox'
  checkbox.onchange = function() {
    cell.getRow().toggleSelect()
  }

  // Callback function to execute when mutations are observed
  function mutationCallback(mutationsList) {
    for (let mutation of mutationsList) {
      checkbox.checked = mutation.target.classList.contains('tabulator-selected')
    }
  }

  // Create an observer to only watch for attribute changes (like CSS classes) and activate it
  const rowEl = cell.getRow().getElement()
  // list of all available config options: https://developer.mozilla.org/en-US/docs/Web/API/MutationObserverInit
  const config = { attributes: true, attributeFilter: ['class'], attributeOldValue: true }
  const observer = new MutationObserver(mutationCallback)
  observer.observe(rowEl, config)

  return checkbox
}

```

**Comment by olifolkerd** [comment]
Hey @morficus 

Thanks for your suggestion, fortunately it does not fit with the way Tabulator works, updating any UI elements inside Tabulator should only be done when either the formatter is called on the cell or the row. triggering a change in any other way will cause irregular behaviour in the DOM.

The correct approach would be to use a formatter on the cell that sets the selected state of the toggle based on the selected state of the row, which can be retrieved using `cell.getRow().isSelected()`,

you could then use the ***rowSelectionChanged*** callback and the ***reformat*** function on the row component to trigger a reformat of that row when its selection state is changed:
```js
var table = new Tabulator("#example-table", {
    rowSelectionChanged:function(data, rows){
        rows.forEach(function(row){
            row.reformat();
        });
    },
});
```

I hope that helps,

Cheers

Oli :)
