### ISSUE TITLE
getColumnLayout missing properties

### ISSUE THREAD

**Issue by Jojoshua** [olifolkerd/tabulator#1826]
**Describe the bug**
Calling getColumnLayout is not returning all the column properties.

**Tabulator Info**
4.2

let tableConfig = {
    data: [
      { id: 1, name: "Oli Bob", location: "United Kingdom", gender: "male", rating: 1, col: "red" },
      { id: 2, name: "Mary May", location: "Germany", gender: "female", rating: 2, col: "blue" },
      { id: 3, name: "Christine Lobowski", location: "France", gender: "female", rating: 0, col: "green" },
      { id: 4, name: "Brendon Philips", location: "USA", gender: "male", rating: 1, col: "orange" },
      { id: 5, name: "Margret Marmajuke", location: "Canada", gender: "female", rating: 5, col: "yellow" },
      { id: 6, name: "Frank Harbours", location: "Russia", gender: "male", rating: 4, col: "red" },
      { id: 7, name: "Jamie Newhart", location: "India", gender: "male", rating: 3, col: "green" },
      { id: 8, name: "Gemma Jane", location: "China", gender: "female", rating: 0, col: "red" },
      { id: 9, name: "Emily Sykes", location: "South Korea", gender: "female", rating: 1, col: "maroon" },
      { id: 10, name: "James Newman", location: "Japan", gender: "male", rating: 5, col: "red" }
    ],
    height: "100%",
    layout: "fitColumns",
    columns: [{ title: "Name", field: "name", editor: "input" }]
  };

  const table = new Tabulator(`#table`, tableConfig);
  console.log(table.getColumnLayout());

![capture](https://user-images.githubusercontent.com/5598169/53303144-fcaa8800-3834-11e9-9881-8f55e559dc6e.JPG)

**Expected behavior**
I was expecting to see the editor property and it was missing.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser:chrome
 
**Additional context**
 I intend to save the entire configuration in the database and reload. There may be other missing properties that I did not test but I would want everything that can be specified when calling "addColumn" to be return via getColumnLayout

**Comment by Jojoshua** [comment]
I found that getColumnDefinitions includes the editor property. It seems this method is more relevant to be part of the Persistent module. I am not sure what the intention of getColumnDefinitions  vs getColumnLayout should be.

**Comment by olifolkerd** [comment]
Hey @Jojoshua 

The ***getColumnLayout*** function returns the current layout of the columns, ie current widths and visibility, rather than their original definitions. It is used by people who want to export the current layout of the table to be imported at a later date.

Cheers

Oli :)
