### ISSUE TITLE
Nested Data indicators show for all empty data but undefined

### ISSUE THREAD

**Issue by haferje** [olifolkerd/tabulator#1827]
**Describe the bug**
DataTrees show the expand/collapse icon for rows even if their `_children` data is an empty array or null.  The code checks for undefined only.  It should also check for null, as it throws an error.

**Tabulator Info**
- Which version of Tabulator are you using?
v4.2.1

**To Reproduce**
1. Go to https://jsfiddle.net/3goLac5x/2/
2. Notice how the second and third rows appear to have nested data
3. Try to expand row 2 and 3

**Expected behavior**
Nested data indicators should not show if nested data field is null or empty array.

**Additional context**
A null value for nested data will also throw errors because it is not checked before being iterated.  I believe `undefined`, `null`, and empty array should all be considered as no nested row data.

**Comment by olifolkerd** [comment]
Hey @haferje 

I agree that is definitely a bug. funnily enough i have actually had users thanking me for showing the expand/collapse for non array values. i will prevent the error on the next patch release, and make some more comprehensive setup options in 4.3

Thanks for the feedback

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @haferje 

I have pushed a fix to the master branch to prevent the expand element showing if the child field has a value of ***null*** . it will be included in tommorows patch release

i am going to leave in the ability to show the expanded element with an empty array for the time being as some people are using it to ajax load in the children.

In version 4.3 im going to add more support for complex loading of children including other possible values for the property, at that point i will make it so empty arrays do not show the expand element.

Cheers

Oli :)
