### ISSUE TITLE
Nested Data column width resize issue with dataTreeChildIndent

### ISSUE THREAD

**Issue by haferje** [olifolkerd/tabulator#1828]
**Describe the bug**
When resizing the indicator column for Nested Data tables, columns become misaligned.

**Tabulator Info**
- Which version of Tabulator are you using?
v4.2.1

**To Reproduce**
1. Go to https://jsfiddle.net/haferje/zr1n2vLm/6/
2. Resize the first column as small as you can make it
3. Notice how the first column is of different widths for each nested level

**Expected behavior**
The entire column should be the same width and align properly.

**Additional context**
This seems to be an issue only when dataTreeChildIndent is defined

**Comment by olifolkerd** [comment]
Hey @haferje 

Ooooooh that is a rather exciting UI bug, i will get a fix out for that in the next patch release.

Thanks for the feedback

Oli :)

**Comment by olifolkerd** [comment]
I have pushed a fix for this to the master branch and will include it in this evenings patch release

Cheers

Oli :)
