### ISSUE TITLE
Documentation typo dataTreeCollapseElement font awesome class

### ISSUE THREAD

**Issue by michaelongithub** [olifolkerd/tabulator#1830]
**Describe the bug**
dataTreeCollapseElement:"<i class='fa**_s_** fa-minus-square'></i>", //fontawesome toggle icon

**Tabulator Info**
4.2

**To Reproduce**
So in docu.

**Correct to**
<i class='fa fa-minus-square'></i>"

Tree functionality really great. Could use it right away for very important client functionality
Cheers, Michael

**Comment by michaelongithub** [comment]
**Describe the bug**
`dataTreeCollapseElement:"<i class='fas fa-minus-square'></i>", //fontawesome toggle icon`

**Tabulator Info**
4.2

**To Reproduce**
So in docu.

**Correct to**
`dataTreeCollapseElement:"<i class='fa fa-minus-square'></i>", //fontawesome toggle icon`

**Comment by michaelongithub** [comment]
Grrrr: didnt know how to insert html and pressed th wrong button, sorry

**Comment by waruyama** [comment]
You are probably referring to this part of the Tabulator documentation: http://tabulator.info/docs/4.2/tree#layout-colexp

The `fa` attribute has been deprecated and `fas` is one of the new attributes to be used, according to this Font Awesome documentation page:
https://fontawesome.com/how-to-use/on-the-web/setup/getting-started

Therefore I think this is not a bug.

**Comment by olifolkerd** [comment]
Hey @michaelongithub 

@waruyama is correct as of font awesome 5 it is now 'fas' and not 'fa'

Cheers

Oli :)
