### ISSUE TITLE
selectableCheck callback is not triggered on programatic selection of row

### ISSUE THREAD

**Issue by morficus** [olifolkerd/tabulator#1832]
**Describe the bug**
When calling "grid.selectRow()" or "row.toggleSelection()", the selectableCheck does not get fired

**Tabulator Info**
- Which version of Tabulator are you using? 4.2
- Post a copy of your construct object if possible so we can see how your table is setup
You can use this JS Fiddle: https://jsfiddle.net/morficus/by34sr98/26/

**To Reproduce**
You can use this JS Fiddle: https://jsfiddle.net/morficus/by34sr98/26/

**Expected behavior**
The "selectableCheck" should trigger no matter how a row selection takes place

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.3
 - Browser Chrome
 - Version  72.0.3626.119

**Smartphone (please complete the following information):**
not applicable

**Additional context**
None

**Comment by olifolkerd** [comment]
Hey @morficus 

The ***selectableCheck*** callback is only intended to be called on selection of elements by users, the programmatic functions intentionally ignore this to allow a forced selection of any row in the table if needed.

Cheers

Oli :)

**Comment by morficus** [comment]
Would it be possible to update the documentation to reflect this intention?

**Comment by olifolkerd** [comment]
Yup no problem, I will update it this weekend
