### ISSUE TITLE
support for RXJS Observables as a data source

### ISSUE THREAD

**Issue by dcanning** [olifolkerd/tabulator#1833]
**Is your feature request related to a problem? Please describe.**
feature request

**Describe the solution you'd like**
able to assign an rxjs observable as the data source and have tabulator update when the observable changes

**Describe alternatives you've considered**
can subscribe to observable and call setdata on tabulator

**Comment by olifolkerd** [comment]
Hey @dcanning 

Thanks for getting in touch, i must admit i am unfamiliar with the RxJS framework, but i would certainly be happy to look at adding it to the list of comparable frameworks.

If this is something you are interested in it would be great to hear from you if you have any suggestions on how their observables work and could be integrated into Tabulator.

Cheers

Oli :)

**Comment by shaulnaim** [comment]
@dcanning, @olifolkerd 
 i am using tabulator on angular with rxjs and it is possible to work with it.
in order to update the tabulator on stream update, you need to  call tabulator constructor after the subscribe but only on the first time... after that, you should call setData or replaceData to update the grid content
`.subscribe(value => {
        if (!this.table) {
          this.buildTable(); //Tabulator constructor
        } else {
          this.table.replaceData(
            this.currentNestedConnectionsTree
          );
        }`

**Comment by dcanning** [comment]
@olifolkerd sure, I'd love to.  I like this page for summarizing: https://rxjs.dev/guide/observable
I'll try to take a look at making this work with tabulator, but I don't know how much time I'll have.

**Comment by dcanning** [comment]
@shaulnaim I like that, I'll take a look at using set or replace data.  Not sure how that will work with user experience as far as sorting/pagination, etc, but if the underlying data is changing anyway resetting those is probably ok.

**Comment by olifolkerd** [comment]
Hey @dcanning 

If you would like this to be a feature, i will be relying on you to submit it as a pull request as i do not develop with rxjs.

As such im going to close this issue, but i look forward to receiving your pull request if it is something you are interested in.

Cheers

Oli :)

**Comment by dcanning** [comment]
@olifolkerd Sorry, I've just been slammed between day job and home life, if anyone else is interested feel free to take up the sword on it, I'd love to do this but I don't know when I'm going to have time.
