### ISSUE TITLE
Programatic selection of a range of rows + visible rows on a page

### ISSUE THREAD

**Issue by morficus** [olifolkerd/tabulator#1834]
**Is your feature request related to a problem? Please describe.**
Tabulator has a method that allows for programmatic selection of all rows (`grid.selectRow()`) as well as selecting a specific row (`grid.selectRow(25)`), but there is no way to programmatically select a range of rows or limit the selection of rows to the current page (when rows are paginated)

**Describe the solution you'd like**
I would be great to introduce new programmatic row selection functionality such as:
* `grid.selectRow(25, 30)` to allow for programatic range selection
* `grid.selectRow('page')` to only select rows that are visible in the cases where pagination is enabled.

**Describe alternatives you've considered**
Currently I am using a wrapper function which calls `grid.selectRow(#)` in a loop. 
```
function selectRowRange(start, end) {
   for(let i = start; i <= end; i++) {
      grid.getRowFromPosition(i).select()
   }
}
```

**Additional context**
When enabling pagination, `grid.selectRow()` will select all rows across all pages. There are many use cases where from a UX perspective only the visible rows need to be selected (this is common in many email applications, such as GMail). So introducing something like `grid.selectRow('page')` would make this significantly easier.

Additionally, Tabulator can currently be configured to allow [a range selection with user interaction](http://tabulator.info/docs/4.2/select#setup-range) but there is no way to perform this programatically. Introducing something such as `grid.selectRow(25, 30)` would bring parity between the type of selection possible with the user interaction vs programatic selection.

**Comment by olifolkerd** [comment]
Hey @morficus 

Thanks for the suggestion, i think that is a great idea, i will add it to the roadmap for the 4.3 release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @morficus 

Sorry for the late reply, this feature was added in the 4.5 release. you can now select the visible rows with the below command:

```js
table.selectRow("visible")
```

Cheers

Oli :)
