### ISSUE TITLE
Row Formatting examples in documentation did not work

### ISSUE THREAD

**Issue by vasiliyaltunin** [olifolkerd/tabulator#1836]
in documentation - http://tabulator.info/docs/4.2/format#row

in **Row Formatting** there are an example code:

```
var table = new Tabulator("#example-table", {
    rowFormatter:function(row){
        //row - row component

        var data = row.getData();

        if(data.col == "blue"){
            row.getElement().css({"background-color":"#A6A6DF"});
        }
    },
});
```

when it try to use it i get error
`(index):162 Uncaught (in promise) TypeError: row.getElement(...).css is not a function` in console, 

but when i change it like this:

`$(row._row.element).css({"background-color":"#FF704D"});`

it works just fine

**Comment by morficus** [comment]
Hey @vasiliyaltunin 

when you do `row.getElement()`, that returns a raw [DOM node](http://tabulator.info/docs/4.2/components#component-row). 
`.css()` is not a method on a "raw" DOM node.

( Here is some additional information on [MDN about DOM nodes](https://developer.mozilla.org/en-US/docs/Web/API/Node) )

Meanwhile... doing `$(row._row.element)` is wrapping the DOM node in a jQuery object.... which does have a `.css()`method.


So with that being said, I have two recommendations for you:

**Use the native DOM node methods**
You could set the [`style` property](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style) by doing this:
`row.getElement().style["background-color"] = "#A6A6DF"`
or
`row.getElement().setAttribute("style", "background-color: #A6A6D")`

**Wrap your call in a jQuery object**
If you prefer to use jQuery for everything, then you can do the following:
`$(row.getElement()).css({"background-color":"#FF704D"});`

**Comment by morficus** [comment]
You are correct in that the documentation has a syntax error tho.
I imagine this is leftover from when jQuery was a hard dependency (pre-4.0)

**Comment by olifolkerd** [comment]
Hey @vasiliyaltunin 

Thanks for highlighting the syntax error, i will get that resolved this weekend.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
the correct code should have been:
```js
row.getElement().style.backgroundColor = "#A6A6DF";
```

I have made a fix for this on the website and will make it live later today.

Thanks for the feedback

Oli :)
