### ISSUE TITLE
Tabulator jQuery syntax doesn't work

### ISSUE THREAD

**Issue by justingolden21** [olifolkerd/tabulator#1839]
**Description**

Tabulator jQuery syntax doesn't work

**Tabulator Info**

I'm using Tabulator 4.2.1

**To Reproduce**

Here's my jQuery and jQuery UI CDNs:

<code>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.1/jquery.min.js"></script>

<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>

</code>

and here are my CDNs for Tabulator, imported after Tabulator of course:

<code>

<link href="https://unpkg.com/tabulator-tables@4.2.1/dist/css/tabulator.min.css" rel="stylesheet">

<script type="text/javascript" src="https://unpkg.com/tabulator-tables@4.2.1/dist/js/tabulator.min.js">

</script>

</code>

My javascript code is simple, right form the [demo](http://tabulator.info/examples/3.1):

<code>

let table;

$(function() {

table = new Tabulator("#example-table", {

    height:"311px",

    addRowPos:"bottom",

    columns:[

        {title:"Name", field:"name", width:200, editable:true},

        {title:"Progress", field:"progress", width:100, align:"right", sorter:"number", editable:true},

        {title:"Gender", field:"gender", editable:true},

        {title:"Rating", field:"rating", align:"center", width:80, editable:true},

        {title:"Favourite Color", field:"col", editable:true},

        {title:"Date Of Birth", field:"dob", align:"center", sorter:"date", editable:true},

        {title:"Driver", field:"car", align:"center", editable:true},

    ],

});

});

</code>

But when I replace:

<code>table = new Tabulator("#example-table", {</code>

with:

<code>$("#example-table").tabulator({</code>

then I get: "tabulator is not a function"

**Expected behavior**

I expected it to create a table, however it did nothing and gave errors in the console.

**Desktop**

I am on Windows 10, and have tested this on Chrome, Firefox, and Edge, which are all up to date at time 
of writing, all of which work with normal syntax and crash with jQuery syntax. Note that jQuery works 
perfectly fine elsewhere.

This is my first time trying Tabulator and I've spent a long time trying ot get it to work, only to find that 
the jQuery syntax is the problem. Thank you for looking into this issue.

**Comment by Rodbjartson** [comment]
It does work, and it is clearly stated in the documentation that this is a javascript library as of Tabulator version 4.0.
In order to make use of Jquery you need to simply add the wrapper:


`<script type="text/javascript" src="https://unpkg.com/tabulator-tables@4.2.1/dist/js/jquery_wrapper.min.js"> </script>`

**Comment by olifolkerd** [comment]
@Rodbjartson Thanks for the kind words about the documentation 😊

**Comment by justingolden21** [comment]
@rodbjartson Thank you for the link. Could you send the link to where this is in the documentation, I couldn't find it after searching for a long time. Maybe I'm just in the wrong place. Thank you again.

**Comment by olifolkerd** [comment]
the [jQuery Support Documentation](http://tabulator.info/docs/4.2/jquery)

**Comment by olifolkerd** [comment]
The [jQuery Support Documentation](http://tabulator.info/docs/4.2/jquery)

**Comment by justingolden21** [comment]
Great, thank you

**Comment by olifolkerd** [comment]
@justingolden21  there is a search box at the top right of every page that lets you search all the documentation.
