### ISSUE TITLE
4.2 Horizontal scroll in chrome extremely slow

### ISSUE THREAD

**Issue by c-dante** [olifolkerd/tabulator#1842]
**Describe the bug**
Holding shift and using the mouse wheel to horizontally scroll a table is very very slow.

Seems 4.2 has a regression around holding shift and using the mouse wheel. 4.1 does not have this issue.

![tabulator horizontal scroll slow](https://user-images.githubusercontent.com/6332726/53575920-937e8980-3b40-11e9-9e72-db28f3dffd50.gif)

**To Reproduce**
1. View any of the demos on 4.2
2. Hold shift and use the mouse wheel to scroll
3. Hardly scrolls. See gifs

**Desktop (please complete the following information):**
 - OS: Arch Linux, GNOME 3.30.2
 - Browser: Google Chrome, Version 72.0.3626.119 (Official Build) (64-bit)

**Comment by morficus** [comment]
This seems like it is related to https://github.com/olifolkerd/tabulator/issues/1831 and could be considered a duplicate.


On a related note, I'm not expereince the slow horizontal scrolling issue as reported here (I'm also using Chrome 72.0.3626.119 (64-bit) but I'm on MacOS)

**Comment by olifolkerd** [comment]
Hey @c-dante 

This is the same issue as #1831 

It will be resolved in the next patch release.

Cheers

Oli :)

**Comment by c-dante** [comment]
Sounds good -- found that issue but I didn't know if the visual matched. Thanks!
