### ISSUE TITLE
PDF Download not working

### ISSUE THREAD

**Issue by icedvigilante** [olifolkerd/tabulator#1843]
When clicking on the Download PDF option, nothing is happening. I thought it must be me, but I can repeat the issue at http://tabulator.info/docs/4.2/download

Console export from http://tabulator.info/docs/4.2/download

jspdf.plugin.autotable.js:1114 The data should be an object or array, is: undefined
validateInput @ jspdf.plugin.autotable.js:1114
jsPDF.API.autoTable @ jspdf.plugin.autotable.js:2272
pdf @ tabulator.min.js:6
y.download @ tabulator.min.js:6
u.download @ tabulator.min.js:5
(anonymous) @ download:441
dispatch @ jquery-3.2.1.min.js:3
q.handle @ jquery-3.2.1.min.js:3
jspdf.plugin.autotable.js:1188 Uncaught TypeError: inputHeaders.forEach is not a function
    at Object.createModels (jspdf.plugin.autotable.js:1188)
    at Object.jsPDF.API.autoTable (jspdf.plugin.autotable.js:2277)
    at y.pdf (tabulator.min.js:6)
    at y.download (tabulator.min.js:6)
    at t.u.download (tabulator.min.js:5)
    at HTMLButtonElement.<anonymous> (download:441)
    at HTMLButtonElement.dispatch (jquery-3.2.1.min.js:3)
    at HTMLButtonElement.q.handle (jquery-3.2.1.min.js:3)
createModels @ jspdf.plugin.autotable.js:1188
jsPDF.API.autoTable @ jspdf.plugin.autotable.js:2277
pdf @ tabulator.min.js:6
y.download @ tabulator.min.js:6
u.download @ tabulator.min.js:5
(anonymous) @ download:441
dispatch @ jquery-3.2.1.min.js:3
q.handle @ jquery-3.2.1.min.js:3

using Chrome 72.0.3626.119 (all plugins disabled)

**Comment by icedvigilante** [comment]
Just found the solution.
The new CDN's resolve the issue.

jsPDF-Autotable
https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.0.10/jspdf.plugin.autotable.min.js

jsPDF
https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.5.3/jspdf.min.js

**Comment by waruyama** [comment]
Yes, the PDF export seems to be quite sensitive to the version combinations of jsPdf and autotable plugin at the moment. I ran into the same issue.

Maybe this issue should be ignored for a while and then, when the PDF libraries become stable, the documentation can be updated to the new versions.

**Comment by 805bluebell** [comment]
> 
> 
> Just found the solution.
> The new CDN's resolve the issue.
> 
> jsPDF-Autotable
> https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.0.10/jspdf.plugin.autotable.min.js
> 
> jsPDF
> https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.5.3/jspdf.min.js

That saved a lot of time. Thank's for posting solution.

**Comment by azzok** [comment]
> https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.5.3/jspdf.min.js

Yeah, It's working.
