### ISSUE TITLE
dataTrees are not indenting in Bootstrap 4 theme

### ISSUE THREAD

**Issue by jhenriksen** [olifolkerd/tabulator#1844]
**Describe the bug**
Data trees are not following the dataTreeChildIndent property when using the Bootstrap 4 theme.

**Tabulator Info**
4.2
````
var table = new Tabulator("#data-table", {
	height:"400px", // set height of table (in CSS or here)
	data:tableDataNested, //assign data to table
	//data:tabledata,
	dataTree:true,
	dataTreeChildIndent: 15,
	dataTreeStartExpanded:true,
	columns:[ //Define Table Columns
		{title:"Name", field:"name", width:200, responsive:0}, //never hide this column
		{title:"Location", field:"location", width:150},
		{title:"Gender", field:"gender", width:150, responsive:2}, //hide this column first
		{title:"Favourite Color", field:"col", width:150},
		{title:"Date Of Birth", field:"dob", align:"center", sorter:"date", width:150},
	],
	rowClick:function(e, row){ //trigger an alert message when the row is clicked
		alert("Row " + row.getData().name + " Clicked!!!!");
	},
});
````
**To Reproduce**
Apply bootstrap 4 theme to a datatree with at least one parent - child - grandchild node.

**Expected behavior**
For the left side of child rows to indent by the amount of pixels defined in the dataTreeChildIndent properties. This should be cumulative, so grandchildren should indent 2x, etc.

**Screenshots**
![example](https://user-images.githubusercontent.com/4923471/53598139-cfbde400-3b58-11e9-8851-a4b3b4b70ce5.png)

**Desktop (please complete the following information):**
Windows 7, Chrome 72

**Comment by olifolkerd** [comment]
Hey @jhenriksen 

Sorry to hear you are having issues, i will have a look into that this weekend and include a fix in the next patch release,

Cheers

Oli

**Comment by olifolkerd** [comment]
I pushed a fix to the master branch earlier today to fix another issue, which also fixes this one. It will be included in this evenings patch release.

Cheers

Oli :)
