### ISSUE TITLE
There is an error in the filters sample code

### ISSUE THREAD

**Issue by taka2** [olifolkerd/tabulator#1845]
http://tabulator.info/docs/4.2/filter#overview

Click "View Source"

> table.clearFilter());

There is an extra close bracket at the end of the line.

**Comment by olifolkerd** [comment]
Hey @taka2 

Thanks for the headsup, i will get that fixed this weekend.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
fixed :)

**Comment by taka2** [comment]
Thank you!
