### ISSUE TITLE
Moveable + Cell editing 

### ISSUE THREAD

**Issue by rspadim** [olifolkerd/tabulator#1846]
**Describe the bug**
moveable row start before cell editing

**Tabulator Info**
- Which version of Tabulator are you using?
4.2

**To Reproduce**
Setup a tabulator with a blank page (only tabulator)
100% height
1024x768
set column to select
set editable
set moveable rows

when you go to end of tabulator (500 lines +-) at bottom of page
if you click the select cell to edit, the tabulator start moveable row instead of cell editing

**Expected behavior**
cell edit instead of moveable row

**Screenshots**

**Desktop (please complete the following information):**
chrome linux

**Smartphone (please complete the following information):**
not tested

**Additional context**

**Comment by olifolkerd** [comment]
If you are using movable rows and editing i would suggest using row handles as shown in the [Movable Rows Example](http://tabulator.info/examples/4.2#movable)

It will lead to a cleaner experience for all users.


Cheers

Oli :)
