### ISSUE TITLE
Collapse all columns when using responsive collapse

### ISSUE THREAD

**Issue by Rodbjartson** [olifolkerd/tabulator#1849]
I might have overlooked this in the docs, but I cannot find a way to make my table either just show my table "normally" or to just collapse all. Rigth now I do not like how one row after the other is collapsed when I have set the ResponsiveLayout to collapse(not hide) rows. 

I would like to have an option to set once the minWidth is exceeded, ALL rows are collapsed simultaneously, not one after the other. What do you think about this approach? If you want a clearer example I could create a drawing if you would like.

Thanks

**Comment by Rodbjartson** [comment]
If you have little time on your hands, and find implementing this a hassle, I might look into creating a pull request for this.

**Comment by olifolkerd** [comment]
Hey @Rodbjartson 

Im not sure what you mean, all rows should collapse at the same time, there isnt a responsive collapse scenario that should affect one row over another?

Are you talkin about the toggleable collapse element, in that case there is the ***responsiveLayoutCollapseStartOpen*** option

```js
var table = new Tabulator("#example-table", {
    responsiveLayoutCollapseStartOpen:false,
});
```

i hope that helps,

Cheers

Oli :)

**Comment by Rodbjartson** [comment]
![screeenshoot](https://user-images.githubusercontent.com/11444201/53635353-2260d400-3c1d-11e9-930c-a5039795bbf0.gif)

**Comment by olifolkerd** [comment]
Hey @Rodbjartson 

Thanks for the clear example there, i now understand where you are coming from. At the moment there is nothing built in that would be able to do that for you.

I can certainly add something for that though, i will add it to the roadmap for a future release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Having thought this through some more,

Im not sure it makes sense to move to a table where all the columns are fully collapse, as the table headers would then not correctly represent anything. Which i don't think would be a desirable format.

For this reason i am not looking to add this as a feature.

If you have suggestions on your preferred functionality i would be happy to consider reopening this issue.

Cheers

Oli :)
