### ISSUE TITLE
Custom Filter for tabulator

### ISSUE THREAD

**Issue by venkatrams** [olifolkerd/tabulator#185]
Hello again,

I am trying to set data in the table using setFilter but the callback function is not being called when i set the property to the function name.

So basically when the page loads the tabulator would check for this data in the datasource and show only the records that we have set the filter for.

Please let me know if I am reading too much into the tabulator filtering capabilities.

Your help is greatly appreciated as always

**Comment by olifolkerd** [comment]
Hi,

You can't set data with the ***setFilter*** function, you should use the ***setData*** function

Passing a custom filter function to the ***setFilter*** function allows you to filter data in any way you want.

Could you post a copy of your current code along with a description of what you are trying to achieve and which callbacks you are expecting to be triggered. and i would be happy to post a solution for you.

Cheers

Oli

**Comment by venkatrams** [comment]
Thank you for your response but I am trying to create a function which filters the data when the page loads and set that function to setFilter property.

**Comment by venkatrams** [comment]
function customFilter(data){
    //data - the data for the row being filtered
   alert("TEST")
    //return data.Title like "CSRDC"; //must return a boolean, true if it passes the filter.
}

    // Options to be pushed to tabulator
		var options =
		{
		         // CAML Query to pull data from the list
			"setFilter": customFilter
			
		};

**Comment by olifolkerd** [comment]
I see the issue,

You can not pass the ***setFilter*** function as a callback in the options, it is a function that must be called programmatically ***after*** the table has been constructed.

```js
//define custom filter
function customFilter(data){
    //data - the data for the row being filtered
    return data.name == "bob" && data.height < 3; //must return a boolean, true if it passes the filter.
}

//define table
$("#example-table").tabulator({
    columns:[
        {title:"Name", field:"name"},
        {title:"Age", field:"age"}
    ],
});

//set data
$("#example-table").tabulator("setData", data);

//set filter
$("#example-table").tabulator("setFilter", customFilter);
```

If you want to filter your data after every load then you can use the ***dataLoaded*** callback to trigger the filter after data has been loaded into the table:
```js
//define custom filter
function customFilter(data){
    //data - the data for the row being filtered
    return data.name == "bob" && data.height < 3; //must return a boolean, true if it passes the filter.
}

//define table
$("#example-table").tabulator({
    columns:[
        {title:"Name", field:"name"},
        {title:"Age", field:"age"}
    ],
    dataLoaded:function(){
        //set filter
        $("#example-table").tabulator("setFilter", customFilter);
    }
});

//set data
$("#example-table").tabulator("setData", data);
```

Let me know if that answers your question.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey venkatrams,

Did this answer your query?

**Comment by venkatrams** [comment]
Hello Oli,

Thanks that helped.

**Comment by taimoorkhann** [comment]
$("#example-table").tabulator("setData", data); i'm getting an error on this line
Uncaught (in promise) TypeError: $(...).tabulator is not a function
