### ISSUE TITLE
DataTree dataTreeStartExpanded always returns parent row

### ISSUE THREAD

**Issue by adamxi** [olifolkerd/tabulator#1852]
Hey Oli,

Having a datatree and setting the dataTreeStartExpanded property to a function, the row object returned seems to always be the parent of the child row in the iteration.

**Tabulator Info**
- 4.2.1

**Comment by olifolkerd** [comment]
Hey @adamxi 

Thanks for the heads up, that was definitely a bug. i have pushed a fix to the master branch and will include it in tomorrows patch release.

Cheers

Oli :)
