### ISSUE TITLE
Bottom Rows Disappear

### ISSUE THREAD

**Issue by scott-oliver** [olifolkerd/tabulator#1853]
Originally I had labelled this ticket as bottom rows disappear on fast scroll, but as you can see with my comment below I'm also experiencing the same issue when the window is much larger (without even scrolling).

When scrolling rather quickly, the bottom rows are disappearing/showing as white space.

I'm using the stock standard 4.2.1 template.

I have tried this with large and small data sets alike, still the same problem. There are two screen shots attached to demonstrate.

Table construct is below.

```
var table = new Tabulator
(
	"#example-table",
	{
 		height:(window.innerHeight)-20, // I need a slim buffer before the footer of my window
		headerFilterPlaceholder: '',
		selectable:1,
		data: [**Data** ] ,
		dataTree:true,
		dataTreeStartExpanded:true,
		dataTreeBranchElement: false,
		dataTreeChildIndent: 25,
		dataTreeCollapseElement: !1,
		dataTreeStartExpanded: !0,
 		layout:"fitColumns",
 		columns:[ **Columns** ],
		rowFormatter:function(row)
		{
			var rowColor = row.getData().color
			row.getElement().style.backgroundColor = rowColor;
		},

	}
);
```

I have tested this on both IE and Safari.

![fast scroll](https://user-images.githubusercontent.com/47340261/53674373-8baa1b00-3ce1-11e9-954a-db7739424314.png)
![slow scroll](https://user-images.githubusercontent.com/47340261/53674374-8c42b180-3ce1-11e9-9f61-7dbb169c7328.png)

**Comment by scott-oliver** [comment]
I've also noticed that when displaying my table in a larger window this also happens.

Please keep in mind, I'm not resizing my window after the table is loaded. As you can see, without even scrolling this same imaginary border is displayed limiting the number of rows being displayed.

I have modified the CSS slightly, the major items I have listed below, but I have also copied in file for further review.

```
#example-table{
border: 1px solid #E6E6E6;
margin-top: 0px;
padding-top: 0px;
margin-bottom: 0px;
padding-bottom: 0px;
}
 .tabulator{
    position:relative;
    margin-top: 0px;
    background-color:#FFFFFF;
    font-family: Arial;
    font-size:10px;
    color:#505050;
    overflow:hidden;
    /* border:1px solid #999; */
    /* text-align:left; */
    /* transform:translatez(0) */
}
```

![before scroll](https://user-images.githubusercontent.com/47340261/53679687-f8460980-3d23-11e9-94ef-3bd26a7849a9.png)
![after scroll](https://user-images.githubusercontent.com/47340261/53679690-fb40fa00-3d23-11e9-8f3a-b43f595c2f8b.png)
[Tabulator CSS.txt](https://github.com/olifolkerd/tabulator/files/2921922/Tabulator.CSS.txt)

**Comment by olifolkerd** [comment]
Hey @scott-oliver 

To start with i would recommend against trying to tie the table height to the `window.innerHeight` value, instead use CSS for this.

If you are seing white space it suggests that the table has been resized without redraw being called on the table so it dosnt know to expand the virtual DOM rendering window.

Can you create a JS Fiddle or Code Pen that can demonstrate the issue as i cannot replicate it here.

as a side note you will definitly see some flickering when fast scrolling on IE, while tabulator is compatibly with it you will experience a degraded experience as IE simply isn't powerful enough to cope with a lot of Tabulators features.

Cheers

Oli :)

**Comment by mariusroets** [comment]
Hi,

I would like to reopen this issue, as I'm experiencing the same problem. I have a large table with a few  1000 rows. Upon loading it looks fine, and if I scroll slowly, it remains ok. When I scroll faster however, the bottom rows disappear.

Before scroll:
![tabulator1](https://user-images.githubusercontent.com/378906/55141086-4216e980-5142-11e9-9faf-5390ab894bb2.png)

After scroll:
![tabulator2](https://user-images.githubusercontent.com/378906/55141063-375c5480-5142-11e9-80d6-1770fac6947d.png)

The table construction is really simple (There is only a 100 rows in this example, but it illustrates the issue):

    <script>
        var tabledata = [{"id": 1231, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0610405064"}, {"id": 1232, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0610405064"}, {"id": 1233, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0610405064"}, {"id": 1234, "resource_name": "METER", "right": "W", "facility_type": "SUPPLY_POINT", "facility_id": "0510001876"}, {"id": 1235, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0510001876"}, {"id": 1236, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0510001876"}, {"id": 1237, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0510001876"}, {"id": 1238, "resource_name": "METER", "right": "W", "facility_type": "SUPPLY_POINT", "facility_id": "4054303418"}, {"id": 1239, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "4054303418"}, {"id": 1240, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "4054303418"}, {"id": 1241, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "4054303418"}, {"id": 1242, "resource_name": "METER", "right": "W", "facility_type": "SUPPLY_POINT", "facility_id": "0590502276"}, {"id": 1243, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0590502276"}, {"id": 1244, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0590502276"}, {"id": 1245, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0590502276"}, {"id": 1246, "resource_name": "METER", "right": "W", "facility_type": "SUPPLY_POINT", "facility_id": "0620389244"}, {"id": 1247, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0620389244"}, {"id": 1248, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0620389244"}, {"id": 1249, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0620389244"}, {"id": 1250, "resource_name": "METER", "right": "W", "facility_type": "SUPPLY_POINT", "facility_id": "0610352573"}, {"id": 1251, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0610352573"}, {"id": 1252, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0610352573"}, {"id": 1253, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0610352573"}, {"id": 1254, "resource_name": "METER", "right": "W", "facility_type": "SUPPLY_POINT", "facility_id": "0610364521"}, {"id": 1255, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0610364521"}, {"id": 1256, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0610364521"}, {"id": 1257, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0610364521"}, {"id": 1258, "resource_name": "METER", "right": "W", "facility_type": "SUPPLY_POINT", "facility_id": "0570995980"}, {"id": 1259, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0570995980"}, {"id": 1260, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0570995980"}, {"id": 1261, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0570995980"}, {"id": 1262, "resource_name": "METER", "right": "W", "facility_type": "SUPPLY_POINT", "facility_id": "0610182743"}, {"id": 1263, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0610182743"}, {"id": 1264, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0610182743"}, {"id": 1265, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0610182743"}, {"id": 1266, "resource_name": "METER", "right": "W", "facility_type": "SUPPLY_POINT", "facility_id": "0640007911"}, {"id": 1267, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0640007911"}, {"id": 1268, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0640007911"}, {"id": 1269, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0640007911"}, {"id": 1270, "resource_name": "METER", "right": "W", "facility_type": "SUPPLY_POINT", "facility_id": "0510003698"}, {"id": 1271, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0510003698"}, {"id": 1272, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0510003698"}, {"id": 1273, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0510003698"}, {"id": 1274, "resource_name": "METER", "right": "W", "facility_type": "SUPPLY_POINT", "facility_id": "0510003650"}, {"id": 1275, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0510003650"}, {"id": 1276, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0510003650"}, {"id": 1277, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0510003650"}, {"id": 1278, "resource_name": "METER", "right": "W", "facility_type": "SUPPLY_POINT", "facility_id": "610225831"}, {"id": 1279, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "610225831"}, {"id": 1280, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "610225831"}, {"id": 1281, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "610225831"}, {"id": 1282, "resource_name": "METER", "right": "W", "facility_type": "SUPPLY_POINT", "facility_id": "0610246463"}, {"id": 1283, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0610246463"}, {"id": 1284, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0610246463"}, {"id": 1285, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0610246463"}, {"id": 1286, "resource_name": "METER", "right": "W", "facility_type": "SUPPLY_POINT", "facility_id": "0650918902"}, {"id": 1287, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0650918902"}, {"id": 1288, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0650918902"}, {"id": 1289, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0650918902"}, {"id": 1290, "resource_name": "METER", "right": "W", "facility_type": "SUPPLY_POINT", "facility_id": "0610182989"}, {"id": 1291, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0610182989"}, {"id": 1292, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0610182989"}, {"id": 1293, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0610182989"}, {"id": 1294, "resource_name": "METER", "right": "W", "facility_type": "SUPPLY_POINT", "facility_id": "0640020051"}, {"id": 1295, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0640020051"}, {"id": 1296, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0640020051"}, {"id": 1297, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0640020051"}, {"id": 1298, "resource_name": "METER", "right": "W", "facility_type": "SUPPLY_POINT", "facility_id": "0520010747"}, {"id": 1299, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0520010747"}, {"id": 1300, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0520010747"}, {"id": 1301, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0520010747"}, {"id": 1302, "resource_name": "METER", "right": "W", "facility_type": "SUPPLY_POINT", "facility_id": "0620386986"}, {"id": 1303, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0620386986"}, {"id": 1304, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0620386986"}, {"id": 1305, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0620386986"}, {"id": 1306, "resource_name": "METER", "right": "W", "facility_type": "SUPPLY_POINT", "facility_id": "0520011214"}, {"id": 1307, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0520011214"}, {"id": 1308, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0520011214"}, {"id": 1309, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0520011214"}, {"id": 1310, "resource_name": "METER", "right": "W", "facility_type": "SUPPLY_POINT", "facility_id": "0590361222"}, {"id": 1311, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0590361222"}, {"id": 1312, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0590361222"}, {"id": 1313, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0590361222"}, {"id": 1314, "resource_name": "METER", "right": "W", "facility_type": "SUPPLY_POINT", "facility_id": "0520011146"}, {"id": 1315, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0520011146"}, {"id": 1316, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0520011146"}, {"id": 1317, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0520011146"}, {"id": 1318, "resource_name": "METER", "right": "W", "facility_type": "SUPPLY_POINT", "facility_id": "4056923269"}, {"id": 1319, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "4056923269"}, {"id": 1320, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "4056923269"}, {"id": 1321, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "4056923269"}, {"id": 1322, "resource_name": "METER", "right": "W", "facility_type": "SUPPLY_POINT", "facility_id": "0570994727"}, {"id": 1323, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0570994727"}, {"id": 1324, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0570994727"}, {"id": 1325, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0570994727"}, {"id": 1326, "resource_name": "METER", "right": "W", "facility_type": "SUPPLY_POINT", "facility_id": "0570615611"}, {"id": 1327, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0570615611"}, {"id": 1328, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0570615611"}, {"id": 1329, "resource_name": "METER", "right": "R", "facility_type": "SUPPLY_POINT", "facility_id": "0570615611"}, {"id": 1330, "resource_name": "METER", "right": "W", "facility_type": "SUPPLY_POINT", "facility_id": "0650928008"}];
        var table = new Tabulator("#table", {
            height: 600,
            layout: "fitColumns",
            movableColumns: true,
            columns: [
                {title: "Id", field: "id"},
                {title: "Resource Name", field: "resource_name"},
                {title: "Right", field: "right"},
                {title: "Facility Type", field: "facility_type"},
                {title: "Facility Id", field: "facility_id"},
            ]
        });
        table.setData(tabledata);
    </script>
      
This is on Firefox and Tabulator 4.2.3

**Comment by fr0z3nfyr** [comment]
Please reopen the  issue.

Facing pretty much the same problem as quoted by @mariusroets except that I'm using a `dataTree` and the problem exists even on initial load with about a 1000 rows. On scroll, the bottom padding increases (more rows are hidden). 

Below screenshots show behavior with `dataTreeStartExpanded` set to `true/false`. With `dataTreeStartExpanded:false`, rows start hiding once I expand rows that may go beyond the `table height - bottom padding` otherwise rows are hidden if tree is expanded at `init`. 

From page inspector, I can see that this happens when a `padding-bottom` is added to `<div class="tabulator-table">` and is reproducible 100%. In my case it happens irrespective of scroll speed.

Basic setup is as follows:
var table = new Tabulator("#example-table", {
    height:"600px",
    data:tableDataNested,
    dataTree:true,
    columns:[
	    {title:"Account Name", field:"name", width:300, responsive:0}, //never hide this column
	    {title:"Type", field:"type", width:150},
	    {title:"O/P Balance", field:"op_total", width:200, responsive:2}, //hide this column first
	    {title:"C/L Balance", field:"cl_total", width:200},
    ],
});

See screenshots

**CASE 1:** `dataTreeStartExpanded:false`

**_Initial state_**
![image](https://user-images.githubusercontent.com/5248866/55381543-082e5480-5541-11e9-9ff8-c22d78ee3144.png)

**_Little Expansion_**
![image](https://user-images.githubusercontent.com/5248866/55381732-6e1adc00-5541-11e9-8edb-22e8fb9455f9.png)

**_Further Expansion (Height all visible rows > table height - padding added on `<div class="tabulator-table">`)_**
![image](https://user-images.githubusercontent.com/5248866/55381941-01541180-5542-11e9-9fa5-fb6d6367a567.png)

CASE 2: `dataTreeStartExpanded:true`

**_Initial state_**
![image](https://user-images.githubusercontent.com/5248866/55382564-9a375c80-5543-11e9-9db7-0b6afc3cc223.png)

**_After scroll_**
![image](https://user-images.githubusercontent.com/5248866/55384248-da004300-5547-11e9-892f-de586c57e367.png)

**Comment by olifolkerd** [comment]
Hey @fr0z3nfyr 

This will be because your table has been resized but the ***redraw*** function hasnt been called on the table so it has not resized the virtual DOM buffer to fill the bigger space.

Cheers

Oli :)

**Comment by fr0z3nfyr** [comment]
Thanks for the reply @olifolkerd 

So, are you suggesting that a `redraw()` should be enough to handle this or there is a specific `resize` function available? I did it like this:

```
new Tabulator('#example-table', {
    ...
}).redraw();        // <--- this here
```

This seemed to work (although, it didn't work the first time but worked after a `CTRL+F5`) but I'm not sure if this the best way or is it working just by fluke and may fail in some edge cases! Do I also need to add an event listener for each `.tabulator-data-tree-control` to make sure a redraw is done on every expand/collapse? To achieve that, I had something like below in mind:
```
let exCl = document.querySelectorAll('.tabulator-data-tree-control');
Array.prototype.forEach.call(exCl, function(element, index) {
	element.addEventListener('click', function(){
	    table.redraw();
	});
});
```

Is there a specific `resize` call available like `redraw` that must be called. From docs, I could only find about `autoResize:true, // auto resizing of table` setting in available in table configuration, which I doubt is what you were suggesting. Anyway, I believe that it is set to `true` by default. If this not how it must be done, can you point me in right direction?
