### ISSUE TITLE
Data tree plus positioning

### ISSUE THREAD

**Issue by pythonBerg** [olifolkerd/tabulator#1854]
Suggestion...When using data tree, currently the expand icon is always assigned to column 1, whether or not it is visible. Would suggest it be assigned to first visible instead...

**Comment by olifolkerd** [comment]
Hey @pythonBerg 

Great suggestion, i hadnt considered the possibility of the first column being invisible, i will include that in a patch release today.

On a side note, you can use the ***dataTreeElementColumn*** option to specify a specific column for the element if you are having issues.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @pythonBerg 

I have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)

**Comment by pythonBerg** [comment]
Great. Thanks
