### ISSUE TITLE
Unimified version is minified

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#1856]
**Describe the bug**
I upgrade to 4.2.1 but unminified version of tabulator now looks like minified:

![__](https://user-images.githubusercontent.com/799021/53701013-60b6e880-3e01-11e9-88b5-9ffd38b0919e.jpg)

**Tabulator Info**
- Which version of Tabulator are you using? 4.2.1

**Comment by adamxi** [comment]
Fixed in the next version: https://github.com/olifolkerd/tabulator/issues/1851

**Comment by olifolkerd** [comment]
as @adamxi says this was fixed in [v4.2.2](https://github.com/olifolkerd/tabulator/releases/tag/4.2.2) which was released just under two hours ago.

Cheers

Oli :)
