### ISSUE TITLE
Horizontal scroll performance 4.2.2

### ISSUE THREAD

**Issue by adamxi** [olifolkerd/tabulator#1858]
Hey Oli,

First off, great work :) the scroll performance of 4.2.2 is a lot more smooth and the columns are not lagging along.
I normally wouldn't noticed this but since i am coming from 4.1.5, i noticed that the horizontal scrolling of 4.2.2 still have a lower framerate overall.

I traced the culprit down to the line saying: 
**this.element.scrollLeft = left;** 
in the **RowManager.prototype.scrollHorizontal** function.

When i comment out **this.element.scrollLeft = left;** horizontal scroll performance seems to be a 100% the same as in 4.1.5.

Thanks

**Comment by olifolkerd** [comment]
I have reverted the changes introduced in 4.2 that resulted in a slower framerate  in a commit to the master branch

i will include it in this weekends patch release

Cheers

Oli :)
