### ISSUE TITLE
selectRow() doesn't work

### ISSUE THREAD

**Issue by GarryG** [olifolkerd/tabulator#186]
I tried using selectRow to re-select a row after refreshing the displayed content. I got the error:

ReferenceError: slef is not defined[Learn More]  tabulator.js:3555:4
	.selectRow http://mx.mlfwd.de/flexi/js/tabulator.js:3555:4

Looks like a typo in 3555:
                        rowData = slef._findRow(row);

changing it to "self" instead lets it continue, though I still get an error about row.addClass not a function a couple lines down ...

**Comment by GarryG** [comment]
P.S. - probably same typo in line 3622

**Comment by olifolkerd** [comment]
Hey,

That is definitely a typo in the code, i have just push a fix.

let me know if that fixes it for you.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey, just fixed the but with the "row.addClass" issue as well.

Let me know if you are all up and running now.

Cheers

Oli

**Comment by GarryG** [comment]
The JS errors are gone now ;) Not sure why it doesn't do what I want it to, though ...

**Comment by olifolkerd** [comment]
What are you trying to do?

Could you post an example of the code you are using and what you are trying to achieve and i can help you out.

Cheers

Oli

**Comment by GarryG** [comment]
Hi,
On 19.02.2017 16:35, Oli Folkerd wrote:
>
> What are you trying to do?
>
> Could you post an example of the code you are using and what you are
> trying to achieve and i can help you out.
>
Basically, I do a reload of the data displayed, and want to have the
previously selected row re-selected ... seems pretty straight-forward ...

function refreshList(selected)
  {
      $("#global-table").tabulator("setData").tabulator("selectRow",
selected);
  }

the setData part works fine, but doing some additional debugging it
seems that setData is asynchronous, so selectRow is already called when
no data is present (or the old data is still there), so the subsequent
actual refresh clears the selected row. Guess I need to put some sort of
wait-till-finished in there ... didn't see anything helpful in the docs
about that, though ...

Really like the Tabulator package! Very flexible and nice to use!!

Thanks, -garry

**Comment by olifolkerd** [comment]
Thanks, its always great to hear people are enjoying using Tabulator.

That should be easy to fix,

There is a ***dataLoaded*** callback that you should use to trigger an event after data has been successfully loaded into the table:

```js
$("#example-table").tabulator({
    dataLoading:function(data, params){
        //data - the data or url passed to the setData function
        //params - the params object passed to the setData function
    },
});
```

Stick your selection function in there and you should be sorted.

Cheers

Oli

**Comment by olifolkerd** [comment]
accidentally posted the wrong callback example above, i have now edited it to include the correct callback

**Comment by GarryG** [comment]
Hm ... that didn't work, but what did was renderComplete ... working fine now ...

**Comment by olifolkerd** [comment]
Ah yes of course, you cannot select an element at present until the row is rendered, good call with the ***renderComplete*** callback.

Next months update will allow the option of row selection to persist across data loads and to select currently hidden rows.

Let me know if you have any thoughts for new features or find any other bugs.

Happy Tabulating !!!

Oli

**Comment by olifolkerd** [comment]
Out of curiosity, what data were you passing into the ***selectRow*** function?

**Comment by GarryG** [comment]
It's done via Ajax load ...

**Comment by olifolkerd** [comment]
sorry i meant, when you call the ***selectRow*** function, are you passing it the row index value (integer or string), the row data object or the jQuery row object?

**Comment by GarryG** [comment]
Ah, no, calling it with the index id from the actual data ... it's what I use in the rest of the code to reference the data set ...
