### ISSUE TITLE
Rows on v4.2.2 on ie11 are missing and the scroll handle is jumping.

### ISSUE THREAD

**Issue by shaulnaim** [olifolkerd/tabulator#1860]
I am using the latest version 4.2.2 and on chrome all cool !!
but ie 11 wit fallbacks ... besides its poor performance on large data its also not rendering all the rows...
I gave  the tabulator fixed height
I
![capture](https://user-images.githubusercontent.com/2099185/53726067-e2e0f480-3e75-11e9-8b78-71e8cdf0fc91.PNG)
![capture2](https://user-images.githubusercontent.com/2099185/53726076-e70d1200-3e75-11e9-9792-c653fc625e8f.PNG)

 also calling table.redraw(true) after the constructor.

but still, on ie11 not all rows shows...

**Comment by clurect** [comment]
How many rows are you dealing with? 

Are you setting the table data at the creation of the table? Or do you create the table and then set the data after with the `setData()` function on the Tabulator object?

I think I'm experiencing a similar problem, but I'm still trying to determine the reason behind it.

**Comment by shaulnaim** [comment]
i am setting the data on creation but also i have polling every 2 minutes to refresh the data using th  replaceData method. its about 10k rows using the virtual scroll it shouldn't be a problem.... i think... but IE is hell....

**Comment by shaulnaim** [comment]
OMG, the missing few rows were on EDGE... 
on iIE11 it's much worse... I can see only one row even if i set the data to only 100 rows....
![ie11](https://user-images.githubusercontent.com/2099185/53799725-bbf0f400-3f43-11e9-83b5-1d8c3bf97de2.PNG)
   /// please help I must support this bad stuff.....

**Comment by olifolkerd** [comment]
Hey @shaulnaim 

This is almost certainly because the table is either initialized when it is hidden, or it is resized in someway without the  ***redraw*** function being called.

This dosnt happen on Chrome because Chrome implements the ES8 ***ResizeObserver*** so it always knows when it has changed size. on other browsers you need to tell it to redraw when it changes size.

Cheers

Oli :)
