### ISSUE TITLE
Broken layout in bottomCalc when using frozen columns

### ISSUE THREAD

**Issue by waruyama** [olifolkerd/tabulator#1861]
**Describe the bug**
When using Tabulator with frozen columns, the x-offset of the cells in the bottom calculation row is wrong. 

**Tabulator Info**
- Tabulator v4.2.2

**Working Example**
Here is a codepen that shows this behaviour:

https://codepen.io/anon/pen/WmxaZZ

**To Reproduce**
1. Open the Codepen at https://codepen.io/anon/pen/WmxaZZ
2. Scroll down the table
3. You can see the wrong layout of the calculation rows.

**Expected behavior**
Cells in the calculation row should be aligned with the columns.

**Screenshots**
This is how the first bottom calc row looks in Chrome:

![image](https://user-images.githubusercontent.com/43434568/53729798-816d5580-3e76-11e9-986a-469fb8b92d49.png)

And the second row has even more offset, but in the other direction:

![image](https://user-images.githubusercontent.com/43434568/53729777-6864a480-3e76-11e9-96c5-2aefee126117.png)

**Desktop**
 - Device: Laptop, Windows 7
 - Browser: Chrome 2.0.3626.119, Firefox 65.0.1 

**Additional context**
In the first row the row padding is 227px, while it should be 317px. 
In the second row the padding is correct (317px), but the first two (frozen) cells do not have position absolute, but relative, so they shift the other cells to the right.
These may actually be two separate bugs.

**Comment by olifolkerd** [comment]
Hey @waruyama 

Looking into this further there is a bit of a unique interaction between the row grouping, frozen rows and calculations systems with the specific configuration of your table.

I have isolated the source of the issue but it wont be a quick fix so i'm pencilling it in for the 4.3 release in May when i'm reorganising the relationship between those systems.

Cheers

Oli :)

**Comment by xXmrotsXx** [comment]
Hi @olifolkerd,

I'm on an old version of Tabulator so haven't reported in the past, but could this issue also cause a frozen column of formatted cells (with images - like the cheese example) to misbehave if more columns were added to the right? 

I see it freeze to the RHS of the table instead of its position on the left like defined in the constructor. Removing the freeze fixes my issue.

**Comment by olifolkerd** [comment]
@xXmrotsXx  if it is freezing to the right it means there was an unfrozen column between the left frozen columns and that column. that is expected behaviour

**Comment by olifolkerd** [comment]
Hey @waruyama 

I have pushed a fix for this to the master branch and will include it in this weekends patch release.

Cheers

Oli :)
