### ISSUE TITLE
Table Slicer functionality?

### ISSUE THREAD

**Issue by yuvgin** [olifolkerd/tabulator#1862]
Hi Oli, 

Is there some way to hide/show rows/columns by button click activity? (Similar to a [slicer](https://support.office.com/en-us/article/use-slicers-to-filter-data-249f966b-a9d5-4b0f-b31a-12651785d29d) in Excel).
That is, linking a button to (completely) hide or show specific columns/rows based on cell value. This could be useful for selective viewing/column calculations. 

Is this possible with the current version? If so, how would you go about it? I couldn't find anything relevant in the API...
If not, it's definitely a feature I'd love to see added in future versions of the package. 

Cheers and keep up the fantastic work!

**Comment by waruyama** [comment]
You can implement this with a master data object, where each row or column can have an attribute that indicates if the row/column should be hidden on click. If the button is clicked, you create a copy of the master data object and omit the marked rows/columns. Then you set the new data object and call `replaceData()` on the table. This will keep the table's scroll position and display the new data.

**Comment by Rodbjartson** [comment]
[THIS](http://tabulator.info/docs/4.2/filter#func) is not what you want?

**Comment by waruyama** [comment]
@Rodbjartson's suggestion with filters is much better than mine. Please try filters first.

**Comment by yuvgin** [comment]
Great. That does it 👍 :)
Thanks to you both!
