### ISSUE TITLE
movableRowsReceiver: toRow is empty 

### ISSUE THREAD

**Issue by takuy** [olifolkerd/tabulator#1863]
**Describe the bug**
When movableRowsReceiver is triggered on the receiving table, toRow is empty even if dropped properly onto a row.

**Tabulator Info**
- Version 4.2.2
- construct example included in codepen below

**Working Example**
https://codepen.io/tako1337/pen/ywaJQB

**To Reproduce**
1. drag row (from second table) onto another row (on first table)
2. attempt to use movableRowsReciever to catch drop
3. toRow always undefined

**Expected behavior**
toRow == the row you drop on

**Desktop (please complete the following information):**
 - OS: Windows 10 - 1803
- Chrome
 - Version 72

**Comment by takuy** [comment]
This seems to be an issue when ``movableRows`` is not set on both tables.

``MoveRows.prototype.initializeRow`` is not called on rows of a table without that property - so ``config.mouseup`` is never set.

**Comment by olifolkerd** [comment]
i will update the documentation for this in this evenings website update

Cheers

Oli :)
