### ISSUE TITLE
Allow to setup initial value for autocomplete editor

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#1867]
When user tries to edit field with `autocomplete` editor
The initial value is selected by default:
![__](https://user-images.githubusercontent.com/799021/53828591-c54f8000-3f86-11e9-83b2-8ca82ccb1218.jpg)

This is not so handy for `autocomplete`, because forces user to clear the field to be able select new value:

![__2](https://user-images.githubusercontent.com/799021/53828685-08115800-3f87-11e9-9c81-bf9804d10931.jpg)

But pay attention that this behavior: select initial value, is useful for `select` editor.

The problem with `autocomplete` editor that initial value hides the lookup list

**Describe the solution you'd like**
provide the option which allow to setup some initial value
In my case I need `null` or '' as default

**Describe alternatives you've considered**
none

PS. Actually does not related to this feature request, but you can notice that the **raw** cell value is displayed. It will be more handy if cell.text is displayed instead.
This issue occur when I use formatrers on the cell along with autocomplete editor:

        formatter       : "lookup",
        editor          : "autocomplete",

**Comment by olifolkerd** [comment]
Hey @KES777 

Thanks for the feedback, i will look at adding a series of options for customising the opening behaviour in the 4,3 release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @KES777 

I have pushed this feature to the 4.4 branch that will be released later today.

There is now a ***defaultValue*** option on the editor to allow setting of the default value for undefined cells.

Cheers

Oli :)
