### ISSUE TITLE
Text columns with HeaderFilter will filter on null values as "null" string

### ISSUE THREAD

**Issue by haferje** [olifolkerd/tabulator#1868]
**Describe the bug**
I have table columns that are string/text types.  When I enable filtering, any cell with a null value will filter as if the value of the cell was the string "null".  In testing, I also found that this occurs for "undefined" values as well.

**Tabulator Info**
- Which version of Tabulator are you using?
v4.2.2

**Working Example**
https://jsfiddle.net/haferje/gj0kampx/2/

**To Reproduce**
1. Go to the JSFiddle URL that I linked
2. In the filter of column 'Col 2', type the values 'null' or 'undefined'
3. See how the values are not treated as empty strings

**Expected behavior**
Typing 'null' and 'undefined' in the filter should produce no matching rows

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome

**Additional context**
The issue occurs at line 69 of the filter module in `initializeColumn()`.
`String(column.getFieldValue(data))` produces `"null"` and `"undefined"` for their respective value.

**Comment by olifolkerd** [comment]
Hey @haferje 

Thanks for the demo there that is very helpful, i think you have found one of the last stragglers for the jQuery remove.

I will add that to the list for the next patch release.

Cheers

Oli :)

**Comment by haferje** [comment]
Any update on a fix for this?

**Comment by olifolkerd** [comment]
Hey @haferje 

Im looking to do a patch update for this over the weekend, one of my family has been in hospital recently so i have been a bit distracted. usual service to resume shortly.

Cheers

Oli :)

**Comment by haferje** [comment]
Sorry to hear that.
I'll be patient.

**Comment by olifolkerd** [comment]
Hey @haferje 

You will be happy to hear i have pushed a fix for this to master and will be including it in the patch release later today.

Cheers

Oli :)

**Comment by haferje** [comment]
Code change looks good - I'll try it when I get back to work Monday.
Thank you!
