### ISSUE TITLE
"deselectRow" function not working properly

### ISSUE THREAD

**Issue by ifedefi** [olifolkerd/tabulator#187]
Every time I use the function "deselectRow", the data parameter in the tabulator event "rowSelectionChanged" remains the same

**Comment by olifolkerd** [comment]
Hey,

Could you post a copy of your Tabulator constructor and of the deselectRow function you are using along with the value you are passing to the function, i would be happy to have a look into that for you.

Cheers

Oli

**Comment by olifolkerd** [comment]
also have you tried running the latest version of tabulator, a bug-fix was committed for this function 3 hours ago.

**Comment by ifedefi** [comment]
I'm not very confident with github, where can I download that commit? Do I have to re-download the entire project?

**Comment by olifolkerd** [comment]
the only file that was updated was tabulator.js which you can find [here](https://raw.githubusercontent.com/olifolkerd/tabulator/master/tabulator.js)

**Comment by olifolkerd** [comment]
if you have cloned a copy of the repo then just pull the latest code using a ```git pull``` command

**Comment by olifolkerd** [comment]
Hey 	ifedefi,

Did this answer your query?

**Comment by ifedefi** [comment]
Not really, I just can't check it right now but I remember that it was not
working yet, I'll let you know as soon as I can

Thank you for your patience

Il 27 feb 2017 9:45 PM, "Oli Folkerd" <notifications@github.com> ha scritto:

**Comment by olifolkerd** [comment]
Ok, no problem.

When you get a chance if you can send over a copy of your Tabulator constructor and the code you are using to deselect a row (including the arguments you pass to the function). I would ba happy to take a look and see what can be done to get you up and running.

Cheers

Oli

**Comment by ifedefi** [comment]
Here is the constructor:
```
table.tabulator({
    fitColumns: true,
    responsiveLayout: true,
    columns: tabulatorIntest,
    data: json,
    sortBy: "id",
    sortDir: "asc",
    selectable: true,
    tooltips: true,
    rowSelectionChanged: function(data, rows) {
        if (data.length == 1) {
            $("#modifica").prop("disabled", false);
            $('.inputs').each(function() {
                $(this).val(data[0][$(this).attr("name")]);
            });
            $("#elimina").prop("disabled", false);
        } else {
            $("#modifica").prop("disabled", true);
            $(".inputs").val("");
            if (data.length == 0)
                $("#elimina").prop("disabled", true);
            else
                $("#elimina").prop("disabled", false);
        }
    }
});
```
"#modifica" and "#elimina" are simple buttons that I need to enable / disable according to the length of the variable data (theorically, the selected cells), but when I remove one or more rows, the variable data does not change...

Here is the response from the server after I click the button "#elimina":
(rowIds is an array containing the ids of the elements that I have to delete)
```
case "delete":
    var rowIds = JSON.parse(httpreq.responseText);
    //console.log(rowIds);
    for (var i = 0; i < rowIds.length; i++) {
        table.tabulator("deleteRow", rowIds[i]);
    }
    $('.inputs').val("");
    $('#modifica').prop("disabled", true);
    $('#elimina').prop("disabled", true);
    act = "";
    break;
```
If you need any other information, please let me know
Thank you in advance

**Comment by olifolkerd** [comment]
Hey,

I have pushed an update to the repo this morning that should fix your issue.

Many Thanks

Oli
