### ISSUE TITLE
FR: Reactive Data for remote data

### ISSUE THREAD

**Issue by mohshraim** [olifolkerd/tabulator#1870]
**Is your feature request related to a problem? Please describe.**
As mentioned in  documentation that Reactive Data works with Local Data Only...
We are loading a huge number of records partially using `( ajaxRequestFunc:'',  ajaxProgressiveLoad: 'scroll') `, end user click on record to show a popup to update record data... at this point we can't reflect the changes to table without reload the entire data from server...

We try different way like use table.setData with our cached (updated) array at client side; but this will stop ajax from loading and request next page on scroll.

Is there any workaround for this??
Or we should reimplement the scroll progressive loading ??

Thanks

**Comment by olifolkerd** [comment]
Hey @mohshraim 

Reactive data can only work on local data because with remote data there is no array to watch. if you wat progressive scroll loading then you cannot use it at the same time as reactive data.

But i dont think that is your issue.

You can easily update the data in the table without reloading it all, if the update happens as the result of a user editing data in a modal after a row click, you can pass the row component from the click callback to the modal, and then call the ***update*** function on the row with the new data, this will update just that row in the table:

```js
row.update({"name":"steve"}); 
```

Or if you want to update a set of specific rows in the table you can use the ***updateData*** function
```js
table.updateData([{id:1, name:"bob", gender:"male"}, {id:2, name:"Jenny", gender:"female"}]);
```

I hope that helps,

Cheers

Oli :)

**Comment by mohshraim** [comment]
Hey Oli,

First would like to thank for great component..
I opened this as feature request as already read the documentation...
I have tried many work around but failed...
following my table setup using ajax Func 
 
`        
   
            tableSpaceList = new Tabulator("#tableSpaceList", {
             height: '300px',
            ayout: 'fitColumns',
 
        reactiveData:true, 
        ajaxURL: 'space',
        ajaxRequestFunc: space.tabulator_loadRequest,
        ajaxConfig: space, //"post", //ajax HTTP request type ==> this oobject will appear in ajaxConfig at tabulator_loadRequest
        ajaxProgressiveLoad: 'scroll',
        ajaxProgressiveLoadDelay: 200, //wait 200 milliseconds between each request
        ajaxProgressiveLoadScrollMargin:300, //triger next ajax load when scroll bar is 300px or less from the bottom of the table.
.....
` 

So my main task is load on scroll... on the same time user can edit records (not from table directly) through a popup (modal) and some cases a button on table record to update record status on DB...
what we are looking for is to update the client side affected row without reload the table records,,
i already tried `row.update({data});` but table doesn't reflect changes...

Any work around? as it seems hard to implement this FR..

Thanks
Moh Shraim

**Comment by mohshraim** [comment]
Hey @olifolkerd ,

About your suggestion `row.update({"name":"steve"}); `
I don't know if this a bug but i found the source of problem that we have nested object that used in column `[{title: "Title", field: "doc.title"}, {title: "Name", field: "doc.name"}, ...]`
when u trace the `row.update` function i found that does update as following


          //update affected cells only
			for (var attrname in data) {
				var cell = _this6.getCell(attrname);
				if (cell) {
					if (cell.getValue() != data[attrname]) {
						cell.setValueProcessData(data[attrname]);
						if (visible) {
							cell.cellRendered();
						}
					}
				}
			}

from code its only check the first level of keys in data, so any nested object like our case will not be rendered.
do you consider it as bug? or we should not use nested object ?
Thanks

**Comment by mohshraim** [comment]
Hello @olifolkerd 

I did a work around function to solve the nested objects for update case...

     const updateTableRow = function (row) {
        const rowData = row.getData();
        const cells = row._row.cells;

    getNestedData = function (fieldStructure) {
        var dataObj = rowData,
            structure = fieldStructure,
            length = structure.length,
            output;

        for (var _i = 0; _i < length; _i++) {
            dataObj = dataObj[structure[_i]];
            output = dataObj;
            if (!dataObj) {
                break;
            }
        }
        return output;
    };


    for (var i = 0; i < cells.length; i++) {
        var cell = cells[i];
        const fs = cell.column.fieldStructure;
        if (fs.length > 1) {
            cell.setValueProcessData(getNestedData(fs));
        } else {
            cell.setValueProcessData(rowData[fs[0]]);
        }
    }
    };


i call it after `row.update(objectWithNestedData);`
sending my row..

I would like to help solve it on Tabuator core but still not familiar with library, just moving from BTTable..

Thanks
Moh Shraim
