### ISSUE TITLE
internal function call broken - Reactive data

### ISSUE THREAD

**Issue by angeliski** [olifolkerd/tabulator#1872]
**Describe the bug**
The reactive module broken on use row delete method.

**Tabulator Info**
- Which version of Tabulator are you using?
Latest - 4.2.2
**Working Example**
Please include a JS Fiddle or Code Pen that demonstrates the problem, it is very hard to diagnose an issue from a simple description
I use in Vue, but I believe is a JS error:
https://codesandbox.io/s/040k8kv93n

**To Reproduce**
1. Create a Tabulator instance using the **reactiveData** 
2. Implement some method to use cell component
3. Call the delete funciton inside the row component (provided by cell component)
4. See error (Uncaught (in promise) TypeError: Cannot assign to read only property 'name' of object '#<Object>')

**Expected behavior**
Just delete the row. If you update reactiveData to false, that works

Enviroment info:
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-2500S CPU @ 2.70GHz
  Binaries:
    Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
    Yarn: 1.7.0 - ~/.yarn/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
  Browsers:
    Chrome: 72.0.3626.121
    Firefox: Not Found
    Safari: 12.0.3

**Comment by olifolkerd** [comment]
Hey @angeliski 

Thanks for the heads up, that is definitely a bug, i will get that resolved for the next patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @angeliski 

I have pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)
