### ISSUE TITLE
validator not working

### ISSUE THREAD

**Issue by mrslayer01** [olifolkerd/tabulator#1873]
I'm currently working with an input field that only accepts numbers and i want to limit the field to a max of nine numbers, but as soon as i add a validator it fails no matter what i put in.

` var Clickable = function (cell, formatterParams) {
     cell.getElement().classList.add("pointer");
     return cell.getValue();
        };`

`{ title: "SSO", field: "Sso", editor: "input", formatter: Clickable, responsive: 0, validator: ["numeric", "max:9"]},`

Any help on this would be appreciated.

**Comment by olifolkerd** [comment]
Hey @mrslayer01 

Please confirm what version of Tabulator you are using, there was a bug in validation in the 4.0 release, please make sure you are running on the latest version.

Cheers

Oli :)
