### ISSUE TITLE
TickCross filter showing wrong filtered data on Alt / Alt + Tab key press

### ISSUE THREAD

**Issue by akki-jat** [olifolkerd/tabulator#1874]
**Describe the bug**
When using tickCross filter if we move to another window (press alt + tab) and come back or press alt key when focus is on tickCross filter then tabulator is showing wrong data until clicked outside (anywhere)

**Tabulator Info**
- Version: 4.2.2

**Working Example**
Same behaviour can be seen on tabulator website. [Link - Tabulator Filter Header](http://tabulator.info/examples/4.2?#filter-header)
For Detail look at the GIF attached.

**To Reproduce**
2. Check tickCross filter
3. Press Alt or Alt + Tab
4. Observe the filtered column (Showing wrong filtered data)

**Expected behavior**
Should not show wrong filtered data on Alt or Alt + Tab click

**GIF**
![tabulor_tickcross_issue](https://user-images.githubusercontent.com/26685162/53982735-a6461f00-413b-11e9-9b6e-4b63f9a0b84b.gif)

**Desktop:**
 - OS: Window 10
 - Browser: Chrome - 72

**Comment by akki-jat** [comment]
Hi @olifolkerd, for fix this issue I have added check for tickCross to disable live update ( I think there is no need for live update on tickCross but you are the man behind Tabulator so, you would know better and also it would be if you share your thoughts ).

So, take a look at PR #1875.

Thanks,

Akshay Jat  (@akki-jat )

**Comment by olifolkerd** [comment]
Hi @akki-jat 

Im afraid i don't understand what your issue is, i cant seem to replicate any bad behaviour, the header filter is working exactly as i would expect and i cant make it do anything to match your demo, using alt or alt tab has no effect on it at all for me.

Cheers

Oli :)

**Comment by akki-jat** [comment]
@olifolkerd make sure focus is on tickCross filter checkbox when you press alt or alt + tab.

**Comment by akki-jat** [comment]
@olifolkerd still facing the same problem in version 4.2.3.
And unable to find changes for this bug fix.
