### ISSUE TITLE
Unable to download table as Excel

### ISSUE THREAD

**Issue by dota2Pro** [olifolkerd/tabulator#1876]
Getting error in console
Uncaught ReferenceError: i is not defined
    at tabulator.min.js:6

**Tabulator Info**
- 4.2 latest
I am just using the website http://tabulator.info documentation

**Working Example**
http://tabulator.info/docs/4.2/download#xlsx

**To Reproduce**
1. Go to 'http://tabulator.info/docs/4.2/download#xlsx'
2. Click on 'Download XLSX'
3.. See error "Uncaught ReferenceError: i is not defined
    at tabulator.min.js:6"

**Comment by olifolkerd** [comment]
Hey @dota2Pro 

That is due to a bug introduced in the 4.2.2 release, that will be resolved in this weekends 4..2.3 release.

there is pull request for it here #1859

Cheers

Oli :)

**Comment by denniswennen** [comment]
Hi @olifolkerd, thanks for this great plugin.

I am still getting an error, even after updating to 4.2.3, is that possible?

`xlsx.min.js:14 Uncaught TypeError: ke is not a constructor
    at om (xlsx.min.js:14)
    at km (xlsx.min.js:14)
    at Object.xm [as write] (xlsx.min.js:14)
    at y.xlsx (tabulator.min.js:6)
    at y.download (tabulator.min.js:6)
    at t.u.download (tabulator.min.js:5)
    at HTMLDivElement.<anonymous> (blink-table-script.js:324)
    at HTMLDivElement.dispatch (jquery.min.js:2)
    at HTMLDivElement.y.handle (jquery.min.js:2)`

**Comment by olifolkerd** [comment]
Hey @denniswennen 

Sorry to hear that, i will look into it further and get it fixed in the next patch release.

Cheers

Oli :)

**Comment by Tuxus** [comment]
Hi @dota2Pro  @denniswennen 

Could you perform tests with this cdn?
<script src="https://unpkg.com/xlsx/dist/xlsx.full.min.js"></script>

**Comment by dota2Pro** [comment]
> Hi @dota2Pro @denniswennen
> 
> Could you perform tests with this cdn?
> 
> <script src="https://unpkg.com/xlsx/dist/xlsx.full.min.js"></script>

Use <script type="text/javascript" src="http://oss.sheetjs.com/js-xlsx/xlsx.full.min.js"></script>
as per http://tabulator.info/docs/4.2/download#example-table-download

**Comment by olifolkerd** [comment]
it looks like there are issues when using date objects in the table, i will fix in the next patch release

**Comment by olifolkerd** [comment]
Im afraid i cannot replicate your issues, when using a table set up as per the documentation it is all downloading correctly for me.

If you feel you are still having issues please create a JS fiddle that demonstrates the issue as it is likey related to the data you are trying to download.

Cheers

Oli :)

**Comment by denniswennen** [comment]
Hi @olifolkerd, thanks for looking into it. Sorry you didn't hear back from me for a while. I am taking up the project and will do some tests and get back to you if necessary. Thanks again!

**Comment by denniswennen** [comment]
I found the issue after some research. Including the library xlsx.**full**.min.js did the job. Previously I was using the xlsx.min.js.
