### ISSUE TITLE
Feature Request - Slider Toggle

### ISSUE THREAD

**Issue by Jojoshua** [olifolkerd/tabulator#1879]
Create an editor that can take boolean or tri-state values similar to the tick. Something like https://github.com/kevinchappell/kcToggle

**Comment by olifolkerd** [comment]
Hey @Jojoshua 

Great idea, and as it happens i have already built slider toggles before, i will add one in 4.3

Cheers

Oli :)

**Comment by Jojoshua** [comment]
Great. If possible it would be nice to have text/color association and a formatter for read only mode. Not sure how a tri-state would work with it... Maybe it could be as simple as text on the left and a pill-like shape to the right of the text which upon click cycles through an array of pre-determined text/color array.

**Comment by olifolkerd** [comment]
Having had a think about this further i think i am going to not include a toggle editor in Tabulator by default.

It doesn't really fit the current editor paradigm where editors are only made visible when the cell has focus as it would want to be always visible.

In that case it should be a formatter, but none of the formatters built in to Tabulator have editor functionality so i feel it may be incongruous to add this in.

If users want to add a toggle then as you have pointed out there, there are a great many options for 3rd party libraries that do this task very well. Looking at a few of the options they are all quite opinionated on the styling of the element and i would rather let users choose a toggle that was the best fir for their design.

Thanks for the suggestion.

Cheers

Oli :)
