### ISSUE TITLE
Export xlsx doesn't work

### ISSUE THREAD

**Issue by porkydenny** [olifolkerd/tabulator#1880]
Tryng to create an export in xlsx of a table it return: 
Uncaught ReferenceError: i is not defined
    at tabulator.min.js:6
    at Array.forEach (<anonymous>)
    at c (tabulator.min.js:6)
    at tabulator.min.js:6
    at Array.forEach (<anonymous>)
    at a (tabulator.min.js:6)
    at r (tabulator.min.js:6)
    at w.xlsx (tabulator.min.js:6)
    at w.download (tabulator.min.js:6)
    at t.d.download (tabulator.min.js:5)

Link with simple test tryng the lib, hope it will help!
https://jsfiddle.net/7ehp0bto/

**To Reproduce**
Click on xlsx button

**Comment by gravjean** [comment]
The function parseRow use a variable i.

But this variable dont exist. I think the variable to use is value event if i dont understand why the value cant be date.

[
rowData.push(!(**i** instanceof Date) && (typeof value === 'undefined' ? 'undefined' : _typeof(value)) === "object" ? JSON.stringify(value) : value);
}
To
[
rowData.push(!(**value** instanceof Date) && (typeof value === 'undefined' ? 'undefined' : _typeof(value)) === "object" ? JSON.stringify(value) : value);
]

in tabulator.

**Comment by porkydenny** [comment]
Hi gravjean,

modifing in that way the export work correctly.
Awesome!!!

Thank you for support!
