### ISSUE TITLE
CellEdited Callback event fires multiple times for other cells

### ISSUE THREAD

**Issue by jobele** [olifolkerd/tabulator#1884]
I have been evaluating Tablator for some time now. This is a wonderful JS table UI. I have question in how to control or deal with multiple events callback behavior.

I wanted to use cellEdited callback to update backend database with the changes made on each cell using Ajax post .

What happens is that the first cell edit callback will work. Subsequently cell edit will fire back the previously completed edited cell events thereby corrupting the updates and producing unpredictable results.

Attempt to fix this behavior with stopPropagation or Return False or stopImmediatePropagation has not work. This is a key behavior for the use case I am evaluating.

Ant suggestion on this?

**Comment by aklaver** [comment]
I have done something similar and it worked, can you show the code you are using?

**Comment by jobele** [comment]
cellEdited:function(cell){			   			 
	var cellValue = cell.getValue();						
	var rowData = cell.getRow().getData();							   		   
	$.ajax({
		headers: {
			'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
		},										
		type: 'POST',
		url: "{{ URL::route('book.updateComment') }}",
		data: {
			  'userNum': rowData.user_num,
			  'userId': rowData.user_id,
			  'itemValue': cellValue,									  
		},
		success: function(data) {					

			if ((data.errors)) {
				alert("Error updating record, please reload.");
			} else {											 
				 cell.getRow().update({USER_COMMENT":data.book_comment});
			} 	
		}, 
	});	//END 			   			   
				
},
