### ISSUE TITLE
edit cell validator Maximum call stack size exceeded

### ISSUE THREAD

**Issue by hack7621** [olifolkerd/tabulator#1887]
**To Reproduce**
The price does not allow less than 0, click Edit Price if you enter the <0 number, then click on the other cells to edit the error  "Maximum Call stack size exceeded."

```js
// I use Chrome devtools to debug display errors out now  tabulator.js row:13276
Edit.prototype.focusCellNoEvent = function (cell) {
		this.recursionBlock = true;
		if (this.table.browser !== "ie") {
			cell.getElement().focus();
		}
		this.recursionBlock = false;
	};
```
In addition, can you provide version 4.2 of the API documentation to GitHub, easy to use offline viewing

> Sorry, my English is very poor, I hope I have expressed my problem 

**Describe the bug**
Uncaught RangeError: Maximum call stack size exceeded.
    at Edit.focusCellNoEvent (tabulator.js:13276)
    at success (tabulator.js:13323)
    at onChange (tabulator.js:13594)
    at HTMLInputElement.<anonymous> (tabulator.js:13582)
    at Edit.focusCellNoEvent (tabulator.js:13276)
    at success (tabulator.js:13323)
    at onChange (tabulator.js:13594)
    at HTMLInputElement.<anonymous> (tabulator.js:13582)
    at Edit.focusCellNoEvent (tabulator.js:13276)
    at success (tabulator.js:13323)
Edit.focusCellNoEvent @ tabulator.js:13276
success @ tabulator.js:13323
onChange @ tabulator.js:13594
(anonymous) @ tabulator.js:13582
Edit.focusCellNoEvent @ tabulator.js:13276
success @ tabulator.js:13323
onChange @ tabulator.js:13594
(anonymous) @ tabulator.js:13582

**Tabulator Info**
Tabulator 4.2.3

**Working Example**
```js
var table = new Tabulator("#example-table", {
  layout: "fitColumns", //fit columns to width of table (optional)
  columns: [ //Define Table Columns
    {
      title: "price", field: "price", editor: "number", validator: {
        type: "min",
        parameters: 0,
      },
    },
    {
      title: "Number", field: "number", editor: 'number', validator: "numeric",
    },
  ],
});
```
**Desktop (please complete the following information):**
 - OS: windows 7
 - Browser  Google Chrome  72.0.3626.121

**Comment by hack7621** [comment]
In the case of validation failure, there is no problem with the first click outside the editor, the second click will appear error, this will not happen in firefox58.0.2

**Comment by aklaver** [comment]
Well I can confirm it errors on Chrome, but not FF:
https://jsfiddle.net/aklaver/3n7shkzo/2/

I do not have an answer though.

**Comment by olifolkerd** [comment]
Hey @hack7621 

Sorry to hear you are having issues, i will look into this for the next patch release.

Cheers

Oli :)

**Comment by cacuestai** [comment]
Hello:
The same problem in Chrome.
regards
![error-stack](https://user-images.githubusercontent.com/2236441/55512989-3471d000-562a-11e9-8548-1eaa5696b6b5.png)

**Comment by olifolkerd** [comment]
there was an issue with the number editor that caused multiple event bindings to be created on validation fail which cascaded and used the whole call stack.

I have pushed a fix for this to the master branch and will include it in today's patch release

Cheers

Oli :)

**Comment by Biomaj** [comment]
Hi Oli,

I'm running 4.2.5 with the fix for this, however I've just had exactly this issue trigger. I've not been able to recreate it again though.

I've got this validation against a couple of cells :
`validator:"required"` 

I think this bug might still be present :)

**Comment by jcramirez** [comment]
Hi @olifolkerd , 

I am experiencing this issue as well using Electron. 

> Uncaught RangeError: Maximum call stack size exceeded
> 
> ...........\node_modules\tabulator-tables\dist\js\tabulator.js:9480

 

Using:
"tabulator-tables": "^4.4.3"
