### ISSUE TITLE
add Persist option  for data tree expansion 

### ISSUE THREAD

**Issue by shaulnaim** [olifolkerd/tabulator#1888]
can we have a persistExpantion option on setup for data tree?

what is the easiest way for doing it right now?

thanks, Oli for the great Tabulator!

**Comment by olifolkerd** [comment]
Hey @shaulnaim 

Thanks for the kid words, it is great to hear you are enjoying using Tabulator.

Could you take me through what scenarios you feel it should persist where it currently isnt?

Cheers

Oli :)
