### ISSUE TITLE
Create filter on input keyup based on all row

### ISSUE THREAD

**Issue by CerDennis** [olifolkerd/tabulator#1889]
I've just created for my self a filter that on keyup of 'filtervalue' input return the rows witch have this string at least in one tabledata. It would be awesome if you can include this type of filter.
At the bottom you can find the code that i wrote if can help with the development( i'm a junior dev maybe what i wrote is simple trash ).

```js
function customFilter( data ){

        var stringFrominput = $(".filter-value").val();

        for( var dato in data ){

            if( data[dato].toLowerCase().includes( stringFrominput ) ){
                return data;
            }

        }

    }

    function updateFilter(){

        var filter = customFilter;
        table.setFilter( filter, '=', $(".filter-value").val() );

    }
     
    $(".filter-value").keyup(updateFilter);
```

**Comment by olifolkerd** [comment]
Hey @CerDennis 

Thanks for getting in touch.

I intentionally don't include anything with Tabulator that works with elements outside the table as there is no way for me to know what they will be or how they will be controlled.

In this case you have added custom functionality to do this which is exactly what you should be doing.

Cheers

Oli :)
