### ISSUE TITLE
Combobox (input with select list) for headerFilter

### ISSUE THREAD

**Issue by takuy** [olifolkerd/tabulator#1891]
**Is your feature request related to a problem? Please describe.**
I'd like for the ability to have an input field (``headerFilter:"input"``) while also populating a list of matching elements that are valid inputs (``headerFilter:"select", headerFilterParams:{values:true}``). 

``headerFilter:"select", headerFilterParams:{values:true}`` gets close to this, but doesn't allow you to type, or clear once you've selected something.

**Describe the solution you'd like**
I'd like for something like this:
``headerFilter:"input", headerFilterParams:{values:true}, headerFilterNullable: true``

You can define you want an input, with a list of autocomplete or possible valid issues, that you can decide is also nullable (adds an empty option in the select list). Essentially, like the Autocomplete editor but for a headerFilter. 

**Describe alternatives you've considered**
I've tried numerous configurations with the latest Tabulator version and haven't figured out if you can have a select menu while also allowing manual input options.

**Comment by olifolkerd** [comment]
Hey @takuy


The ***autocomplete *** editor already does this for you have a look at the [Editor Documentation](http://tabulator.info/docs/4.2/edit#edit-builtin) for more information.

It also has options to allow free text and restrict empty values:
```js
{title:"Example", field:"example", editor:"autocomplete", editorParams:{
    showListOnEmpty:true, //show all values when the list is empty,
    freetext:true, //allow the user to set the value of the cell to a free text entry
    allowEmpty:true, //allow empty string values
}}
```

I hope that helps,

Cheers

Oli :)

**Comment by takuy** [comment]
Hi @olifolkerd - I am looking to do this as a headerFilter - not an editor. Does this still apply?

**Comment by olifolkerd** [comment]
Hey @takuy 

as per the documentation, the header filters use the built-in editors so yes you can still use this.

Cheers

Oli :)
