### ISSUE TITLE
hearder filter search values in table.getAjaxUrl()

### ISSUE THREAD

**Issue by fingers10** [olifolkerd/tabulator#1892]
Hi,

> First of All thanks for this awesome Tabulator. I really love this.

 I need a help on how to get current header search values in `getAjaxUrl()`.

I'm generating custom url with `ajaxUrlGenerator()`.

```
ajaxURLGenerator: function (url, config, params) {
        //url - the url from the ajaxURL property or setData function
        //config - the request config object from the ajaxConfig property
        //params - the params object from the ajaxParams property, this will also include any pagination, filter and sorting properties based on table setup
        params.offset = params.limit * (params.offset - 1);
        if (params.offset === 0) {
          delete params.offset;
        }

        const filters = params.filters;
        delete params.filters;

        let pagination = Object.keys(params).map(k => `${k}=${encodeURIComponent(params[k])}`).join('&');
        let search = filters.map(a => 'search=' + encodeURIComponent(a.field.toLowerCase() + ' eq ' + a.value)).join('&');
        search = search != '' ? '&' + search : search;
        this.fullAjaxUrl = url + "?" + pagination + search;
        console.log(this.fullAjaxUrl);

        //return request url
        return this.fullAjaxUrl; //encode parameters as a json object
      },
```

I need the url with search filters so that I can pass that to server for generating report. But this `getAjaxUrl()` gives only url as per docs. Please could you assist ?

**Comment by aklaver** [comment]
Why not use ajaxFiltering?:
http://tabulator.info/docs/4.2/data#ajax-url

Have you checked what shows up on the server?

**Comment by fingers10** [comment]
@aklaver As per tabulator docs, 

`var url = table.getAjaxUrl();`

> Note: This function will return the url set on the ajaxURL property or the latest url set with the setData function, it will not include any pagination, filter or sorter parameters

But I'm looking for an option in tabulator to return my custom generated url within `ajaxURLGenerator`

Any possibilities?

**Comment by aklaver** [comment]
I am not understanding. In your original post you are concerned with what shows up on the server, so why not check the request on the server?

If not maybe?:
http://tabulator.info/docs/4.2/callbacks#ajax
`ajaxRequesting:function(url, params){
    //url - the URL of the request
    //params - the parameters passed with the request
    },`

**Comment by fingers10** [comment]
Let me make it clear. I'm generating a custom url with the search parameters in the URL as per my need. And that works fine and filters are applied in server and results are returned and displayed in tabulator.

My question - is it possible to retrieve the custom url which gets generated dynamically based on the my header search values? Tabulator anywhere storing this custom url?

I have url set in Ajax url property as `https://...com/api/values`

After applying header filter, now my url looks like
`https://...com/api/values?search=name eq some name`

Let's say like this is the last request made by tabulator to the server. Now if I call `getAjaxUrl` I'm getting the default url which is `https://...com/api/values`

Is it possible to get `https://...com/api/search=name eq somename` from `getAjaxUrl` method?

Am I clear now?

**Comment by aklaver** [comment]
Not from getAjaxUrl as far as I know. The only place I can  find is this:

http://tabulator.info/docs/4.2/callbacks#ajax
Ajax Request

The ajaxRequesting callback is triggered when ever an ajax request is made.
`
var table = new Tabulator("#example-table", {
    ajaxRequesting:function(url, params){
    //url - the URL of the request
    //params - the parameters passed with the request
    },
});
`
