### ISSUE TITLE
Autocomplete editor doesn't work when specifying label/values and custom search function

### ISSUE THREAD

**Issue by dcanning** [olifolkerd/tabulator#1894]
**Is your feature request related to a problem? Please describe.**
Autocomplete editor does not work when specifying display labels that are different than the value you want to store, i.e. 
```
{title:"Name", field:"name", editor:"autocomplete", editorParams:{
    values:{
        "steve":"Steve Boberson",
        "bob":"Bob Jimmerson",
        "jim":"Jim Stevenson",
    }
}}
```
and specifying a custom searchFunc:
```
    searchFunc:function(term, values){ //search for exact matches
        var matches = []

        values.forEach(function(item){
            if(item.value === term){
                matches.push(item);
            }
        });

        return matches;
    },
```

**Describe the solution you'd like**
When using both searchFunc and the object key/value pair for different label values, I would like to be able to return the same object key/value pair structure as specified in the values propery

**Describe alternatives you've considered**
I have tried returning an object with matching key/value pairs from the searchFunc as initially sent to the values property, and returning just an array of the matching keys, neither works

**Comment by dseiler** [comment]
I have noticed a similar issue when trying to use custom searchFunc with autocomplete editor like this:

{ title: "Epic", field: "epic", editor:"autocomplete", editorParams: {
              showListOnEmpty: true,
              freetext: true,
              allowEmpty: true,
              searchFunc: function(term, allItems){
                  console.log(allItems);
                  var matches = [];

                  allItems.forEach(function(item){
                      if(item.value === term){
                          matches.push(item);
                      }
                  });

                  return matches;
              },
              values: ["Accounts", "Products", "Quotation"], //array of possible values
            }
          },

When running this I always get the following exception:

tabulator.min.js:7 Uncaught TypeError: Cannot create property 'element' on string 'Accounts'
    at tabulator.min.js:7
    at Array.forEach (<anonymous>)
    at l (tabulator.min.js:7)
    at a (tabulator.min.js:7)
    at HTMLInputElement.<anonymous> (tabulator.min.js:7)
    at tabulator.min.js:7
    at w.edit (tabulator.min.js:6)
    at HTMLDivElement.<anonymous> (tabulator.min.js:6)

**Comment by harihsb** [comment]
@dseiler I too get the same error.

**Comment by olifolkerd** [comment]
Hey all,

i cant say i have come across this issue myself. would one of you be able to put together a Code Pen or JS Fiddle that replicates the issue, so i can find the fix for you.

Cheers

Oli :)

**Comment by dseiler** [comment]
Hi Oli
Thanks for your message. Here is a code pen showing the issue:
https://codepen.io/dseiler/pen/MRKbvb

If you try to edit on of the three example rows and open the developer console in chrome you see the following error:

Uncaught TypeError: Cannot create property 'element' on string 'Accounts'
    at tabulator.min.js:7
    at Array.forEach (<anonymous>)
    at l (tabulator.min.js:7)
    at a (tabulator.min.js:7)
    at HTMLInputElement.<anonymous> (tabulator.min.js:7)

Thanks a lot for your support.

BR

Daniel

**Comment by olifolkerd** [comment]
Thanks for the Code Pen, that was very helpful

That is definitely a bug, i will get it fixed in this weekends patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey All,

So the issue relates specifically to when the ***searchFunc*** was being used, it wasn't consistently handling the results from the different types of the values passed into the ***values*** property.

I have tweaked the way the function operates, regardless of the type of input the ***searchFunc*** function will be passed in an array of search item objects with the format:
```js
{
    title:"Steve", the title shown in the list
    value:"steve", the value of the item
}
```

The function must now return an array of these objects that match your search criteria, (these must be the same objects passed in to the function, you cannot rebuild them or it will break the references)

so an example search function that does a strict comparison would be:
```js
searchFunc: function(term, allItems){
    var matches = [];

    allItems.forEach(function(item){
        if(item.value == term){
            matches.push(item);
        }
    });

    return matches;
},
```

I will include these changes in the 4.2.4 patch release later this weekend and update the documentation to match.

Cheers

Oli :)

**Comment by harihsb** [comment]
Thanks Oli!

**Comment by dseiler** [comment]
Thanks Oli

This is just amazing support!!

Best

Daniel
