### ISSUE TITLE
Move between tables in IE11

### ISSUE THREAD

**Issue by rs199483** [olifolkerd/tabulator#1896]
**Describe the bug**
When I select a row to drag on the sender table, instead of showing the draggable row under my mouse, it is appearing in the upper left hand corner of the browser.

**Tabulator Info**
- Which version of Tabulator are you using? 4.2.3
It is set up exactly like the demo in the documentation. See fiddle below.  

**Working Example**
Please include a JS Fiddle or Code Pen that demonstrates the problem, it is very hard to diagnose an issue from a simple description
https://jsfiddle.net/acLgxzvu/1/

**To Reproduce**
Hold mouse down on a row of the sender table.  
You will see upper left corner of browser shows the selected item.
Selected item should appear under mouse.  Makes drag and drop very awkward.

**Desktop (please complete the following information):**
 - OS: Win 10 64-bit
 - Browser IE
 - Version 11

**Additional context**
Works fine in Chrome and Edge

![tabulator-IE11](https://user-images.githubusercontent.com/8175216/54303666-837b9680-4591-11e9-844a-6d8884f51231.png)

**Comment by olifolkerd** [comment]
Hey @rs199483 

Thanks for letting me know about this issue, i will have a look into this further at the weekend and see if i can resolve it in the next patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @rs199483 

It turns you that IE was missing some of the properties i was using to determine the state of the window.

I have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)

**Comment by rs199483** [comment]
Looks good in 4.2.5.  Thanks for the fix!
