### ISSUE TITLE
Make editable column values changeable on AJAX load

### ISSUE THREAD

**Issue by daniel1596** [olifolkerd/tabulator#1897]
Hey Oli-
First of all, great work on Tabulator - I have been using it for a while and really enjoying it.

I thought of a feature that - as far as I know of - does not exist on Tabulator yet, but might be really useful.

I have some columns in my table that I can make editable, but I would like the user to select between a few pre-set values (with a "select" editor). However - I would like those values to be dynamic, coming from the back-end of the app and loaded via AJAX.

I know on each Tabulator object there's an ajaxResponse callback and I already use that for data loading. What would be neat is if, in this callback, I could have a setter to set the table's column editors, and then set my editorParams' values here. Something like:

`ajaxResponse: function (url, params, response) {`
`  // set column 0 to have editor "select" and editorParams with the list of values provided by response.foo`
`  setColumnEditor(0, "select", response.foo);`
`}`

Does that make sense? Also, if there is already a way to do that in Tabulator, that would be amazing.

Thank you!

**Comment by Rodbjartson** [comment]
[link](http://tabulator.info/docs/4.2/release#edit)

There is already an inbuilt select/autocomplete, does this help you?

**Comment by daniel1596** [comment]
@Rodbjartson  Well, I was wanting to use a select, but instead of using it with values: true, or with a hardcoded list of values, I was wanting to use it with a list of values that I wouldn't know until runtime and would want to get from a back-end API.

But I hadn't seen the autocomplete editor - that could definitely help my UI so I appreciate that!

**Comment by Rodbjartson** [comment]
Not sure if this can help you out;

If you want to generate the options when the select editor is triggered, then you can pass a function into the editorParams, that must return the option list in one of the two formats outlined above

```
{title:"Name", field:"name", editor:"select", editorParams:function(cell){
    //create a options list of all values from another column in the table
    var rows = table.getRows();
    var values = {};

    rows.forEach(function(row){
        var data = row.getData();

        values[data.fullname] = data.fullname;
    });

    return {values:values};
}
```

**Comment by daniel1596** [comment]
@Rodbjartson Oh! I had missed that when scrolling through the "select" docs. That was exactly what I was looking for.

That solves my problem. Thanks so much!
