### ISSUE TITLE
Ajax Load Error - Server return Error 500 v4.2 vs Status OK 200 v3.5

### ISSUE THREAD

**Issue by cemmons** [olifolkerd/tabulator#1898]
**Describe the bug**
I branched my project to upgrade tabulator to version 4.2 from 3.5 using the upgrade guide 3.5 to 4.0 I'm having a problem loading data in version 4.2.

In v3.5 it is working like this:

![image](https://user-images.githubusercontent.com/5125512/54362513-d1eb6c80-4647-11e9-921c-145a64a5c4a0.png)

When I upgrade to 4.2 the same data gives me error:

![image](https://user-images.githubusercontent.com/5125512/54362820-6950bf80-4648-11e9-8c38-a387adc4937c.png)

Is there anything wrong with my implemetation?

**Comment by rob196** [comment]
@cemmons check your ajaxConfig

This works for me (note the use of method not type in the below):
ajaxConfig:{
            method: "post",
            headers: {
                "Content-type": 'application/json; charset=utf-8', //set specific content type
            },
        },

**Comment by cemmons** [comment]
This is my ajaxConfig.

```

var ajaxConfig = {
    method: "post",
    headers: {
        "Content-type": 'application/json; charset=utf-8'
    }
};
```

**Comment by rob196** [comment]
And if you add ajaxConentType

`
var table = new Tabulator("#example-table", {
    ajaxURL:"http://www.getmydata.com/now", //ajax URL
    ajaxConfig:ajaxConfig
    ajaxContentType:"json", // send parameters to the server as a JSON encoded string
});
`

**Comment by cemmons** [comment]
Excellent, that ContentType worked. 

Thank you very much!!
