### ISSUE TITLE
Tabulator table works slower and slower

### ISSUE THREAD

**Issue by HitandRun** [olifolkerd/tabulator#1899]
The tabulator producttable functions well at first, but gets slower and slower after each brand lookup ("Merk/Leverancier" lookup).

I am using the latest version of Tabulator (4.2)

Webpage where the producttable can be found :
...

I think it's a memory issue (F12 : see screen shot). There are a lot of Detached HTMLInputElement, 
Detached InternalNode, Detached EventListener, Detached V8EventListener and
Detached HTMLDivElements etc. that increase after each brand lookup.

I am not a specialist but I think the culprit is the function clearHeaderFilter(). When I comment out these lines in my code, the problem doesn't occur : 
productstable.clearHeaderFilter("product_brands_text");
productstable.clearHeaderFilter("name");

**Comment by Rodbjartson** [comment]
Please post your tabulator constructor(object)

**Comment by HitandRun** [comment]
Constructor of productstable :

 

             productstable = new Tabulator('#products-table', {

                           langs:{"nl-be":{"pagination":{"first":"Eerste", "first_title":"Eerste Pag.", "last":"Laatste", "last_title":"Laatste Pagina", "prev":"Vorige", "prev_title":"Vorige Pagina", "next":"Volgende", "next_title":"Volgende Pagina"}}},

                           locale:"nl-be",

                           columns:[

                                        {title:"Id", field:"id", visible:false},

                                        {title:"Productafbeelding", field:"product_photos_thumbnail", align:"left", width:200, responsive: 3, headerSort:false, formatter:"image"},

                                        {title:"Naam", field:"name", sorter:"string", align:"left", responsive: 1, headerFilter:"input", headerFilterPlaceholder:"Naam Filter"},

                                        {title:"Merk", field:"product_brands_text", align:"left", width:150, responsive: 4, headerFilter:"select", headerFilterPlaceholder:"Merk Filter", headerFilterParams:{values:true}},

                                        {title:"Cnk-code", field:"product_cnk", align:"left", responsive: 5},

                                        {title:"Prijs", field:"product_publicPrice", align:"left", responsive: 2, formatter:moneyFormatter, formatterParams:{decimal:".", thousand:"", symbol:" €", symbolAfter:true}},

                                        {title:"Korting", field:"product_discount", visible:false},

                                        {title:"", field:"product_prescription", formatter: prescriptionIcon, align:"center", responsive:0, headerSort:false},

                                        {title:"", field:"product_activeIngredients", formatter: piggyIcon, align:"center", responsive:0, headerSort:false},

                                        {formatter:searchIcon, align:"center", responsive:0, headerSort:false, cellClick:function(e, cell){

                                                      jQuery('#product-detail').empty();

                                                      var rowdata = cell.getData();

                                                      var id = rowdata["id"];

                                                      // product loading spinner

                                                      jQuery('#product-spinner').show();

                                                     jQuery.getJSON('https://www.actipharma.be/actiphar/joomla/mycode/drugreservation/php/drugreservation.php', {subject_key: 'detail', subject_value: id}, function (data) {

                                                                   productdetail = JSON.stringify(data);

                                                                   createAccordion(productdetail);

                                                                   });

                                                      }},

                                        {formatter:cartIcon, align:"center", responsive:0, headerSort:false, cellClick:function(e, cell){

                                                      jQuery('#product-pane-tabbuttons').tabs("enable", "#products-selection");

                                                      jQuery('#product-pane-tabbuttons').tabs("enable", "#products-reservation");

                                                      jQuery('#product-pane-tabbuttons').tabs("option", "active", 2);

                                                      var rowdata = cell.getData();

                                                     rowdata["product_amount"] = "1";

                                                     rowdata["product_subtotal"] = rowdata["product_publicPrice"];

                                                     shoppingcarttable.addRow(rowdata);

                                                     shoppingcarttable.setSort("name", "asc");

                                                      shoppingcarttable.redraw();

                                                      cell.getRow().delete();

                                                      }},

                                        ],

                           columnVertAlign:"center",

                           index:"id",

                           layout:"fitDataFill",

                           layoutColumnsOnNewData:false,

                           pagination:"local",

                           paginationSize:6,

                           responsiveLayout:"hide",

                           dataLoaded:function(data){

                                        jQuery('#product-spinner').hide();

                                        jQuery('#products-table').show();

                                        }

                           });

 

Data is loaded dynamic with json :

 

             // get productinfo

             function productList(searchtype, searchitem) {

                           resetSearch(searchtype);

                           jQuery('#product-spinner').show();

                           jQuery('#products-table-text').html('<h4>Klik op <span style="color: green;"><i class="fas fa-cart-plus fa-2x"></i></span> om een product toe te voegen aan winkelmand.<br><br><i class="fas fa-search fa-2x"></i> detailinfo opvragen <span style="color: blue;"><i class="fas fa-piggy-bank fa-2x"></i></span> alternatieve producten zoeken <span style="color: red;"><i class="fas fa-user-md fa-2x"></i></span> op voorschrift <i class="fas fa-caret-up fa-2x"></i> oplopend sorteren <i class="fas fa-caret-down fa-2x"></i> aflopend sorteren</h4>');

                          productstable.replaceData('https://www.actipharma.be/actiphar/joomla/mycode/drugreservation/php/drugreservation.php', {subject_key: searchtype, subject_value: searchitem}).then(function(){

                                        productstable.setFilter([{field:"product_publicPrice", type:"!=", value:"geen data"}]);

                                        productstable.getColumn("product_brands_text").reloadHeaderFilter();

                                        productstable.clearHeaderFilter("product_brands_text");

                                        productstable.clearHeaderFilter("name");

                                        productstable.redraw(true);

                                        });

                           }

 

In annex complete javascript

 

If you comment out like this, there is no problem anymore :

// productstable.clearHeaderFilter("product_brands_text");

// productstable.clearHeaderFilter("name");

 

PS: I like tabulator very much. Nice work.

 

Kind Regards

 

Van: Rodbjartson [mailto:notifications@github.com] 
Verzonden: vrijdag 15 maart 2019 9:31
Aan: olifolkerd/tabulator <tabulator@noreply.github.com>
CC: HitandRun <hit_and_run@telenet.be>; Author <author@noreply.github.com>
Onderwerp: Re: [olifolkerd/tabulator] Tabulator table works slower and slower (#1899)

 

Please post your tabulator constructor(object)

**Comment by Rodbjartson** [comment]
What  happens when you set a height in your constructor?

**Comment by HitandRun** [comment]
No change at all.

Slow down is caused by increasing use of browser memory.

Can be seen by using F12 and monitoring memory after each time data is loaded in tabulator.

After refreshing browser, speed is back to normal (but decrease again after each load of data into tabulator).

 

Commenting out clearHeaderFilter function solves the problem but I want to remove the filter after each data load.

Otherwise the user sees less - or no - information if he forgets to clear the header filter.

 

Kind Regards

 

Van: Rodbjartson [mailto:notifications@github.com] 
Verzonden: maandag 18 maart 2019 14:23
Aan: olifolkerd/tabulator <tabulator@noreply.github.com>
CC: HitandRun <hit_and_run@telenet.be>; Author <author@noreply.github.com>
Onderwerp: Re: [olifolkerd/tabulator] Tabulator table works slower and slower (#1899)

 

What happens when you set a height in your constructor?

**Comment by HitandRun** [comment]
I have the impression that I have sold the problem but I don't understand why :-(
I replaced productstable.clearHeaderFilter("product_brands_text");
by productstable.getColumn("product_brands_text").setHeaderFilterValue("");
And productstable.clearHeaderFilter("name");
by productstable.getColumn("name").setHeaderFilterValue("");

**Comment by olifolkerd** [comment]
#1723
