### ISSUE TITLE
NOT working in IE

### ISSUE THREAD

**Issue by vmontal** [olifolkerd/tabulator#19]
Tabulator works fine in Chrome / Firefox but NOT in IE; what can I do?
Trans in advance!

**Comment by vmontal** [comment]
Thanks

**Comment by olifolkerd** [comment]
Could you confirm which version of ie you are using?

**Comment by vmontal** [comment]
See attached img!

 

 

Saluti

Valerio.NET

 

When I was in the middle of the river, I raised my arms crying with a load voice: “Is There Anybody Over There?”

The Might One answered… So I began to code!

 

Da: Oli Folkerd [mailto:notifications@github.com] 
Inviato: martedì 12 aprile 2016 14:33
A: olifolkerd/tabulator <tabulator@noreply.github.com>
Cc: Valerio Montalbano <valerio.net@valeriomcse.eu>
Oggetto: Re: [olifolkerd/tabulator] NOT working in IE (#19)

 

Could you confirm which version of ie you are using?

**Comment by vmontal** [comment]
![ie version](https://cloud.githubusercontent.com/assets/10527458/14463088/030ec6ac-00ca-11e6-8e16-53bfcda3a69a.png)

**Comment by olifolkerd** [comment]
Seems to be running fine to me, do you have any screenshots of the table rendering badly, example code, or any of the error messages you are getting in the console?

**Comment by vmontal** [comment]
I just upgraded to last version (3/9/2016) and now it's working fine in IE, too!
thanks a lot the same for the time you spent!
