### ISSUE TITLE
ajaxURL behavior.

### ISSUE THREAD

**Issue by cemmons** [olifolkerd/tabulator#190]
Hi, I've been working a lot with tabulator these days... and I have been using this method to retrieve data to my table without problems.

Code Behind.
```

[WebMethod(CacheDuration = 0)]
        public static string GetRoomList()
        {
            string result;
            using (var ctx = new ServiceContext())
            {
                var roomList = (from c in ctx.Rooms
                                select c);
               
               result =  JsonConvert.SerializeObject(roomList);
            }
            return result;
        }
```

Javascript

```
function createRoomData() {
        $("#gridRoom").tabulator({
            height: "400px",
            fitColumns: true,
            columns: [
                { field: "roomID", visible: false },
                { title: "Code", field: "roomCode", sorter: "string" },
                { title: "Description", field: "roomDescription" },
                { title: "Habited", field: "roomHabited", align: "center" },
            ],
        });
    }
```
```

function loadRoomData2() {
        $.ajax({
            url: "room.aspx/GetRoomList",
            type: "POST",
            contentType: 'application/json; charset=utf-8',
            dataType: 'json',
            beforeSend: function () {
                // $(".l-preloader").show();
                //spinner.spin(spinnerTarget);
            },
            success: function (data) {
                var json = data.d;
                $("#gridRoom").tabulator("clear")
                                        .tabulator("setData", json);
                //spinner.stop();
            },
            error: function (xhr, textStatus, errorThrown) {
                manageError(xhr, textStatus, errorThrown);
                //spinner.stop();
            },
        });
    }
```
```

    createRoomData();
    loadRoomData2()
```

This implementation for Visual Studio C# code works fine. Now, I tried to use a different approach... use the ajaxURL option to fill my table, like This.

Javascript

```
    function loadRoomData() {
        $("#gridRoom").tabulator("setData", "room.aspx/GetRoomList", {}, "POST");
    }
```

That implementation throws this error:

![image](https://cloud.githubusercontent.com/assets/5125512/23138614/c60f5c74-f77e-11e6-8533-5609ec9adf36.png)

Now, I've seen that for ajax request to work in Visual Studio I need to specify options 

```
 type: "POST",
 contentType: 'application/json; charset=utf-8',
 dataType: 'json'
```
So I don't know if I can set this options using the ajaxURL or the Params in the setData function.

Could you clarify me if I'm doing something wrong?

Thanks!!

**Comment by olifolkerd** [comment]
Hi,

That error means that the JSON being returned from the URL *room.aspx/GetRoomList* is invalid.

I would suggest you use the dev console to see the data that is being returned in the request. As you are getting an unexpected ***<*** character i would suggest that you are returning an HTML response not a JSON one.

Cheers

Oli

**Comment by cemmons** [comment]
ok I'll check

**Comment by cemmons** [comment]
Mmm yeah... I'm getting the whole HTML page as a returning object... Read in other forums that for webMethods I need to explicitly set the contentType option as JSON ... then it works... Think I 'll have to keep using the $.ajax method to retrieve my data.

**Comment by olifolkerd** [comment]
I will look at adding the ability to set headers etc in the ***setData*** mehod in next months release

**Comment by cemmons** [comment]
Okok, thanks a lot!

**Comment by lac616** [comment]
I use page WebMethods too and as a workaround you can add the line highlighted in the tabulator.js file. Works like a charm.

![capture](https://cloud.githubusercontent.com/assets/27359692/24964344/062248fe-1f6f-11e7-90d2-5aabb923f3ff.PNG)

**Comment by olifolkerd** [comment]
Great News!

Version 1.12 of Tabulator has just been released with the new ***ajaxConfig*** option that lets you set any of the jQuery ajax config object options:

```js
$("#example-table").tabulator({
    ajaxURL:"http://www.getmydata.com/now", //ajax URL
    ajaxParams:{key1:"value1", key2:"value2"}, //ajax parameters
    ajaxConfig:{
        type:"POST".
        contentType: 'application/json; charset=utf-8',
    }
});
```

Full details can be found [here](http://olifolkerd.github.io/tabulator/docs/#ajax)

Let me know how it goes.

Cheers

Oli :)

**Comment by lac616** [comment]
No issues here, works beautifully!

**Comment by cemmons** [comment]
Hi, it's me again, thanks a lot for the new feature, now I'm implementing it and my response using a web method is something like this.

```
{"d":"
	[
	{\"surCode\":\"01\",\"intCode\":\"rpm011700002\",\"cusCode\":\"0001958259\",\"rotCode\":\"rpm01\",\"sicValid\":true},
	{\"surCode\":\"01\",\"intCode\":\"rpm011700004\",\"cusCode\":\"0001462551\",\"rotCode\":\"rpm01\",\"sicValid\":true}
	]"

```
I can't remove that d from the response, because it is a security fix implemente by .net3.5 so I was hoping you'd now any way to get inside that d.. from tabulator, using the setData function.

Right now my grid doesn't show any data. but it is returned correctly
