### ISSUE TITLE
rowClick firing on Chrome 73 when editing

### ISSUE THREAD

**Issue by tentus** [olifolkerd/tabulator#1900]
**Describe the bug**
The expected behavior for clicking an editable cell is that `rowClick` should not be fired. As far as I can tell, there's been a change somewhere in Chrome that makes this no longer the case.

**Tabulator Info**
- 4.2 and also 4.1

**Working Example**
Js Fiddle: https://jsfiddle.net/dnzwp06y/7/

**Steps To Reproduce**
1. Click on an editable cell
2. See the effects of the `rowClick` function, indicated in the fiddle by incrementing the clicks number

**Expected behavior**
`rowClick` should not trigger when editing.

**Desktop (please complete the following information):**
 - OS: Windows, Mac, and Linux
 - Browser: Chrome (Firefox does not seem to exhibit this behavior)
 - Version: 73

**Additional context**
For anyone looking for a short-term fix while this gets sorted, you can use this to exit out of your rowClick function:
```
if(row.getElement().classList.contains("tabulator-row-editing")) { return; }
```

**Comment by Rodbjartson** [comment]
It is not being triggered here for me, I am using:
OS: Windows 10
Browser: Chrome 
Version: 72

**Comment by tentus** [comment]
Correct, this starts specifically with Chrome 73.

**Comment by Rodbjartson** [comment]
Haha, now that is funny

**Comment by olifolkerd** [comment]
Interesting, that looks like chrome may have changed the sequence of the click event firing in the 73 release.

i will keep an eye on it, a lot of these sorts of things tend to be transient glitches that get patched
in the browser.

Cheers

Oli :)
