### ISSUE TITLE
AJAX sorting direction always "asc" with autoColumns

### ISSUE THREAD

**Issue by funkindy** [olifolkerd/tabulator#1901]
In Tabulator 4.2.3, when using AJAX table with `ajaxSorting: true`, the sorting direction is always sent as "asc" and header pic doesnt change. This only appears with `autoColumns: true` feature.

Similar issues: #632, #720

Setup:
 - Tabulator 4.2.3
 - Windows 10
 - Google Chrome
 - Version: 72

**Comment by Rodbjartson** [comment]
Tabulator constructor object please

**Comment by funkindy** [comment]
```
var product_table = new Tabulator("#content-table", {
        placeholder: "No records",
        autoColumns: true,
        pagination: "remote",
        paginationSize: 25,
        ajaxURL: "product_search", 
        ajaxConfig: {
            method: "POST",
            headers: {
                "X-CSRFToken": csrf
            }
        },
        ajaxContentType: "json",
        ajaxParams: {
            filters: {}
        },
        ajaxSorting: true,
        paginationSizeSelector: [10, 25, 50, 100]
});
```
Cant JSfiddle this as no ajax available.

**Comment by Rodbjartson** [comment]
Have you read [this](http://tabulator.info/docs/4.2/sort#ajax-sort)

**Comment by funkindy** [comment]
Of course. To be honest i dont see anything under the link except the way ajax sorting works. And it works great if columns are explicitly defined, but the issue is related to `autoColumns: true` option.

**Comment by olifolkerd** [comment]
Hey @funkindy 

Sorry to hear you are having issues.

You raise a very interesting point there. The reason this is happening is because the autoColumns system regenerates the columns any time the table receives a new data set, which in the case of ajax requests is any time a new request comes in. this is causing the sort to be reset on the column each time.

I will have a look at covering off these scenarios to prevent regeneration of the columns unless ***setData*** etc is specifically called.

Cheers

Oli :)

**Comment by funkindy** [comment]
Hey @olifolkerd! Thanks a lot for detailed clarification. I also want to add that Tabulator is just amazing!

**Comment by olifolkerd** [comment]
Hey @funkindy 

This will be a tricky bit of functionality to add so im going to move it from a bug fix to an enhancement and aim to have something out for it in the May 4.3 release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @funkindy 

I have just pushed an update for this to the 4.6 branch, which will be released in a few weeks.

Cheers

Oli :)

**Comment by taniamm20022** [comment]
> Of course. To be honest i dont see anything under the link except the way ajax sorting works. And it works great if columns are explicitly defined, but the issue is related to `autoColumns: true` option, which is the feature of 4.2+ AFAIK.



> Of course. To be honest i dont see anything under the link except the way ajax sorting works. And it works great if columns are explicitly defined, but the issue is related to `autoColumns: true` option, which is the feature of 4.2+ AFAIK.

Hey,

Sorry for bothering you can you share what kind of parameter you you use in you server side code 
so you can get the column name and the order - desc or asc which you have clicked for ordering.  I mean when I set ajaxSort: true I see that it triggers a call to my api but I cannot get any other info So i can  sort the data on server side. 


s
