### ISSUE TITLE
Moving First Item in Grouped Table Leaves a Blank

### ISSUE THREAD

**Issue by rs199483** [olifolkerd/tabulator#1903]
**Describe the bug**
When moving an item from a grouped table into a receiver table, the sender row is left and is blanked out instead of removed completed

**Tabulator Info**
4.2.3

**Working Example**
https://jsfiddle.net/9f5x7ek0/

**To Reproduce**
1. Move a row from any group to the receiver table
2. The receiver table will accept the row
3. Look at the send table and you will see the text was removed from the cell but the row remains
4.  This always happens for the first time you move a row in each group.  Therefore, you can move another row from a different group and the same will happen.

**Expected behavior**
The row moved should be removed from the sender

**Screenshots**
![GroupedByBug](https://user-images.githubusercontent.com/8175216/54434271-dcffd480-46fb-11e9-9a7a-b81656df5f18.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win 10 64-bit
 - Browser Tested on chrome
 - Version 72.0.3626.121

**Comment by aklaver** [comment]
I added:

`movableRowsSent:function(fromRow, toRow, toTable){fromRow.delete();},`

to tablesender, leaving `movableRowsSender: "delete",` in place and the row was deleted.

**Comment by rs199483** [comment]
That did the trick!  Hopefully it can get fixed in the component at some point in the future.  Thanks for that!

**Comment by olifolkerd** [comment]
Hey @rs199483 

Sorry to hear you are having trouble,

Thanks for the JS Fiddle that is a great help, i will make sure that is fixed in the next patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @rs199483 

There was a graphical glitch affecting deleting rows from groups that has been fixed as a result of another issue.  If you check this evenings 4.2.4 release it should be working.

Cheers

Oli :)
