### ISSUE TITLE
Expanding/Collapsing Groups Becomes Less Responsive Over Time

### ISSUE THREAD

**Issue by rs199483** [olifolkerd/tabulator#1904]
**Describe the bug**
The more you expand/collapse groups, it becomes less responsive to clicks

**Tabulator Info**
4.2.1

**Working Example**
https://jsfiddle.net/9f5x7ek0/

**To Reproduce**
1. Expand and collapse the different headers multiple times
2. After a short while it will take 2, 3 or more clicks to expand and collapse
3. Sometimes the group will not expand or collapse at all until you wait or expand/collapse the other group.

**Expected behavior**
Each group should expand/collapse on a single click

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win 10
 - Browser Chrome 
 - Version  72.0.3626.121

**Comment by tentus** [comment]
I can somewhat corroborate the issue on Chrome 73 and Firefox on Mac, though what I'm seeing doesn't seem to have a time component, but rather a the issue has to do with the jumping back and forth between groups. You can toggle a single group as expected without issue, but if you try to collapse them all and then open them all you'll have to click multiple times.

**Comment by rs199483** [comment]
Thanks tentus, I agree it's a bit tricky to repro, but there is definitely something going on.

**Comment by olifolkerd** [comment]
Hey @rs199483 

Thanks for the info, i think the issue you are experiencing is actually that the click hotspot on the arrow is literally the icon itself and not a box around it so you have to be very precise where you click, and it varies depending on whether it is opened or closed.

I will look at expanding the clickable area to a box around the arrow to aid accessibility

In the mean time you could look at using the ***groupToggleElement*** option to make the entire header clickable for the toggle to make it easier on your users

```js
var table = new Tabulator("#example-table", {
   groupToggleElement:"header", //toggle group on click anywhere in the group header
});
```

I hope that helps,

Cheers

Oli :)

**Comment by rs199483** [comment]
Thanks @olifolkerd , the group header behaves much better.  Thanks for the excellent work on Tabulator.
