### ISSUE TITLE
horizontal table

### ISSUE THREAD

**Issue by TadjerouniMohamedAdel** [olifolkerd/tabulator#1906]
hello please how can i create a stacked table like:
columns1 | data1 | data2 | data3 .....
columns2 | data1 | data2|data3

thanks

**Comment by aklaver** [comment]
No built in way that I know of. I suppose you could fake it by doing something like:
`columns:[
        {title:"Col Name", field:"col_name"},
        {title:"Data 1", field:"data_1"},
        {title:"Data 2", field:"data_2"},
        ....
]`

That would depend on you rotating the data at the source. Also that there was a fairly fixed set of data for each column.

**Comment by olifolkerd** [comment]
@aklaver is correct, Tabulator currently does not support horizontal columns.

This is a feature that will come in at some point but isn't a high priority at the moment im afraid.

Cheers

Oli :)
