### ISSUE TITLE
Reactive array manipulation with Data Grouping not working

### ISSUE THREAD

**Issue by xogoc** [olifolkerd/tabulator#1907]
When I delete row with splice method on Reactive Data Array in Tabulator with Data Grouping enabled I get following error:
```
Uncaught (in promise) TypeError: Cannot assign to read only property 'yyy' of object '#<Object>'
    at Column._setFlatData (tabulator.js:121)
    at Cell.setValueActual (tabulator.js:301)
    at Cell.build (tabulator.js:291)
    at new Cell (tabulator.js:289)
    at Column.generateCell (tabulator.js:145)
    at tabulator.js:59
    at Array.forEach (<anonymous>)
    at ColumnManager.generateCells (tabulator.js:59)
    at Row.generateCells (tabulator.js:250)
    at Row.initialize (tabulator.js:252)
```
Example of Tabulator constructor object:
```
resizableColumns: false,
virtualDom: false,
layoutColumnsOnNewData: true,
reactiveData: true,
data: reactiveArray,
groupBy: 'xxx',
groupStartOpen: true,
columns: [
  {title:"Yyy", field:"yyy",},
  {title:"Zzz", field:"zzz",},
],
```
Tabulator v4.2.1
Google Chrome 72.0.3626.121

Also when I push new row to data array, it renders in wrong group (at table bottom) :(

**Comment by xogoc** [comment]
Updated to 4.2.3
Now there is no error in console. But row stays in table after deleting from array. And "render in wrong group" remains on push :(

**Comment by xogoc** [comment]
Well, I think I've found workaround:
```
dataEdited:function(data){
                    //data - the updated table data
                    table.setGroupBy("xxx");
                },
```
When I trigger grouping on dataEdited event I get it working, but I also get unwanted page scroll to top :(

**Comment by olifolkerd** [comment]
Hey @xogoc 

Sorry to hear you are having issues,

Thanks for your detailed report i will look into fixing this in the next patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @xogoc 

The issue turned out to be because a couple of the internal row delete events were firing in the wrong order.

I have pushed a fix for this to the master branch. the fix will be included in this evenings patch release.

Cheers

Oli :)
