### ISSUE TITLE
select all checkbox

### ISSUE THREAD

**Issue by theblizzle** [olifolkerd/tabulator#1909]
i am using tabulator 4.2 and i have a "select all" checkbox but it only checks the "visible window"? checkboxes from what i am reading? ie. i click the select all checkbox in the header and it checks ~20 rows if you scroll down and then click the select all box it selects ~20 rows from where u scroll and down if i set height to 100% it selects all the checkboxes fine.  is there something im missing?  (Please forgive me if this has already been addressed ive looked tirelessly trying to find an answer but couldnt)

**Comment by aklaver** [comment]
The code you are using would help.

**Comment by theblizzle** [comment]
$("#example-table").tabulator("setSort",[
		{column:"date", dir:currentSort}
	]);
}
		var table = new Tabulator("#example-table", {
 	height:"247px",			
			ajaxProgressiveLoad:"scroll",
			ajaxProgressiveLoadScrollMargin:300,
			columnHeaderSortMulti:false,
			contentType: 'application/json; charset=utf-8',
			resizableColumns:false,
			ajaxRequestFunc:queryRealm,
			ajaxURL: "datatable.php",
			layout:"fitColumns",
			//placeholder:"No Data Available",
			 rowClick:function(e, row){
				 	row.getElement().classList.remove("unread");
				 	row.getElement().classList.add("read");
			 },
			 rowFormatter:function(row){
	if(row.getElement().firstChild.childNodes[0].getAttribute("data-seen") == 0) {
	row.getElement().classList.add("unread");
	}			 
},
 	columns:[ //Define Table Columns
	 	{ title:"<input type='checkbox' class='select-all'>", formatter: "html", field: "chkbox", headerSort:false, width:25},
	 	{title:"<i class='fas fa-paperclip'></i>", formatter: "html", headerSort:false, sortable:false, field:"attach", align:"left",  width:20},
	 	{title:"from", formatter: "html", field:"from"},
		{title:"subject", formatter: "html", field:"subject"},
	 	{title:"date", field:"date", sorter:"date"}
 	],
})
		$("#example-table .select-all").on("change", function(){
    if($(this).is(":checked")){
        $("#example-table .checkbox").prop("checked", true)
    }else{
        $("#example-table .checkbox").prop("checked", false);
    }
});

**Comment by aklaver** [comment]
You have a height set so Virtual DOM kicks in. Then there is the use of Progressive Load. In scroll mode this will only send the data needed to fill the visible table(plus margin) at a time. Both mean your select-all code will only be working on the ~20 rows at a time. 

I see two options:
a) Load the entire data set if feasible.
b) Have the select-all function go back to the server and update the checkbox data to checked.

**Comment by theblizzle** [comment]
thanks what i ended up doing and this might be a stupid way of doing it was  rowFormatter:function(row){ i added  if ($(".select-all").is(":checked")){ row.blah .setattribute(checked, checked) and then do a table.setData() onchange of select all checkbox ... thank you aklaver for the help

**Comment by olifolkerd** [comment]
hey @theblizzle 

@aklaver is almost right, it isnt the vitural DOM, that is working fine, the issue is the progressive load.

Tabulator can only select rows it knows about, because rows are only loaded into the table as you scroll, Tabulator can only select those rows it has been passed by the server at the time the button is pressed, if the user latter loads more data by scrolling further down the table these will be unselected.

Cheers

Oli :)

**Comment by theblizzle** [comment]
i opted for the server side method...works GREAT! thank you guys for the help.
