### ISSUE TITLE
row order

### ISSUE THREAD

**Issue by Kris-B** [olifolkerd/tabulator#191]
Hi,
I'm using getData to retrieve the data from the table.
Users can change the row order (`movableRows: true`). How can I retrieve the row order in the extracted data?

**Comment by olifolkerd** [comment]
Hey,

You can pass a second Boolean parameter ***true***  to the ***getData*** method to retrieve the data as it is displayed in the table.

```js
var data = $("#example-table").tabulator("getData", true); //retrieve data as rendered in table
```

Let me know if that answers your question.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hi Kris,

Did this resolve your query?

**Comment by Kris-B** [comment]
Hi Oli,
Yes, issue solved.
Many thanks!

Chris
