### ISSUE TITLE
Show only the last group

### ISSUE THREAD

**Issue by opiums9** [olifolkerd/tabulator#1910]
Hello! Since stackoverflow is not responding to me, I ask for help here. 
I'm trying to find an opportunity or a ready-made example of functions for displaying only the last group, could you tell me? Here is an example of my code:

```
var lastGr = function(value, count, data, group){
    return group(count) > group(count)-1; // Show only the last group
};

var table = new Tabulator("#tables", {
    groupStartOpen:lastGr,
...
```
Can I display only the last group and hide the rest?

**Comment by tentus** [comment]
Not the prettiest code, but this should work...
```
var table = new Tabulator("#tables", {
    groupStartOpen: false,
    dataGrouped: function (groups) {
      groups.slice(-1)[0].show();
    },```

**Comment by opiums9** [comment]
Apparently something is missing, in the console error:
`Uncaught (in promise) TypeError: Cannot read property 'insertBefore' of null`
[For the test, I posted the code here.](https://jsfiddle.net/opiums/54mjdL98/8/)

**Comment by tentus** [comment]
Hrm, looks like a cornercase with the pagination, I think?

You could hack around it by using 
```
var table = new Tabulator("#tables", {
	data:tabledata,
	reactiveData:true,
	history:true,
	groupStartOpen: function (value, count, data, group) {
		return value === group._group.groupManager.groupList.slice(-1)[0].key;
	},
	groupBy:"numb",
...
```
but I hesitate to even show that code because it relies on directly referencing non-api attributes.

**Comment by opiums9** [comment]
Yes, but it works fine, thanks!

**Comment by tentus** [comment]
I realized I had overlooked an obvious call that fixed a number of issues in my previous response, so I've edited the answer for posterity.
