### ISSUE TITLE
Render bug when unfreezing columns

### ISSUE THREAD

**Issue by OOnogul** [olifolkerd/tabulator#1911]
Hi Oli,
I have encountered a rendering problem. Here is the issue, when there is frozen column(s) in table and I unfreeze them all there is a space on the left side with the width of the unfreezed columns total width.

version 4.2.3
Example: https://jsfiddle.net/9f2yxsqz/3/

Astonishing work on the 4.2 version btw.
Cheers.

**Comment by olifolkerd** [comment]
Hey @OOnogul 

Thanks for your kind words, im glad you are enjoying 4.2

Sorry to hear you have run in to issues. there is definitely a bug there, but just to be clear you are actually replacing all of your columns definitions in that example,

It appears when they are all replaced the freeze padding is not being cleared from the rows.

I will get a fix for this in the next patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @OOnogul 

I have pushed a fix for this to the master branch, it will be included in this evenings patch release

Cheers

Oli :)
