### ISSUE TITLE
Select & AutoComplete do not show dropdown options inside a modal

### ISSUE THREAD

**Issue by Jojoshua** [olifolkerd/tabulator#1914]
The Select and AutoComplete editors do not show the dropdown options if Tabulator is put inside a bootstrap modal. 

A complete JSFiddle to show the issue can be found here. Click the Launch modal button.
https://jsfiddle.net/jojoshua/y73egjwo/

**Tabulator Info**
- 4.2

 - Browser: Tested with Chrome,Firefox, Edge with same results.

**Additional context**
Looks like the options are being appended to the document and likely underneath the modal.

**Comment by olifolkerd** [comment]
Hey @Jojoshua 

Interestingly it is show, it is just that bootstrap is messing with the z-index's of everything so the list is showing behind the dialog.

I will have a look into what is going on and include a fix in the next patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @Jojoshua 

Turns out it was the CSS minifier i was using, for some reason it was altering the values of the z-index's when it was minifying the code. I have turned this "feature" off and regenerated the dists.

I will include this in this weekends patch release.

Cheers

Oli :)
