### ISSUE TITLE
clipboard amelioration

### ISSUE THREAD

**Issue by julien-barbier-minesales** [olifolkerd/tabulator#1915]
Thank you for your application. I use it alot.

When i tried to use the clipboard, i didnt find a way to exclude some column from the table in the clipboard like you did with the download:false in the download section.

Do you think it's possible to add this feature in your next release ?
Good luck for the future.

**Comment by olifolkerd** [comment]
Hey @julien-barbier-minesales 

Thanks for your kind words, it is great to hear that you are enjoying Tabulator.

Thanks for the good suggestion, i think that would be a great idea, i will look at including that on the roadmap for a future release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @julien-barbier-minesales 

This functionality was added in the 4.3 release:
```js
var table = new Tabulator("#example-table", {
    columns:[
        {title:"Hidden Column", field:"secret", clipboard:false} //hide data in clipboard data
    ]
});
```

Sorry for not mentioning this sooner

Cheers

Oli :)

**Comment by julien-barbier-minesales** [comment]
Thank you for this improvement and good luck for more feature.
