### ISSUE TITLE
ajaxLoaderError does not convert string to object

### ISSUE THREAD

**Issue by cbracco** [olifolkerd/tabulator#1916]
**Tabulator Info**
- Which version of Tabulator are you using? **4.2.3**

**Describe the bug**

Hi there! 

Thanks for creating such an awesome tool. While setting up a Tabulator instance I noticed that when I pass a string to the `ajaxLoaderError` option, it does not convert the string to Node the same way that `ajaxLoaderLoading` option does ([See code here](https://github.com/olifolkerd/tabulator/blob/e279f5efdc7e4381a37cfed4d8cd048e3e5b64ed/dist/js/modules/ajax.js#L45-L47)).

Is there any reason why you are not converting the string to a Node here?

**Comment by olifolkerd** [comment]
Hey @cbracco 

Thanks for your kind words, it is great to hear you are enjoying using Tabulator.

I think this is a great idea, i will respond to your comments in your pull request.

Cheers

Oli :)
