### ISSUE TITLE
Datatree with frozen expanded row

### ISSUE THREAD

**Issue by dlewand691** [olifolkerd/tabulator#1919]
Is there a way to freeze the opened/nested tree row so it doesn't scroll horizontally? The parent table will have columns added to it quarterly but need to keep the expanded row width locked.

I posted the question to StackOverflow but haven't gotten any replies yet so wanted to post here. 
https://stackoverflow.com/questions/54952743/tabulator-datatree-with-frozen-expanded-row

And live working example can be found here:
https://qapublisher.cognizant.com/jobs-of-the-future-index

![kCeDZ](https://user-images.githubusercontent.com/1159913/54691429-9ba36680-4af9-11e9-8652-d43875ea23f6.jpg)

**Comment by olifolkerd** [comment]
Hey @dlewand691 

Thanks for getting in touch, sorry for the delayed reply, i have been off on holiday the last couple of weeks.

The row formatter will always take up the full width of the row, if the row overflows the width of the table then so will the formatter.

Nice work by the way, that is one of the most complex and good looking uses of the row formatter that i have seen.

Looking at your table i would say you don't actually need to use frozen columns to fit it all in, your data almost fits in the table by itself, and by shrinking the columns by a few px it should all fit. If you look at using the ***fitColumns*** layout and only set the width on your ***jobs*** and ***names*** columns, Tabulator should resize the others so it all fits perfectly.

I hope that helps,

Cheers

Oli :)

**Comment by dlewand691** [comment]
Hey Oli-
Thanks for the tips and writing back!

I'm sorry, I wasn't quite 100% clear in my explanation. Each quarter, a new column of data will be added to the right, so the table will continue to grow wider and wider. That means the opened tree row will also grow wider and wider. We'd like to keep the opened row locked to the width of the area and not let it scroll horizontally.

Is this possible? Thanks again for your help, very much appreciated.

**Comment by dlewand691** [comment]
Following up my question. Any ideas on a solution?

**Comment by olifolkerd** [comment]
Hey @dlewand691 

Im afraid there isnt really anything built in that could help you there.

Your best bet would be to open the content outside of the table and just use the table as a selector.

You could possibly hack something togeather that listens to the ***scroll*** event on the ***.tabulator-tableHolder*** element and adds margin/padding to the open row to offset it (that is kind of how the frozen column system kind of works)

I hope that helps,

Cheers

Oli :)

**Comment by dlewand691** [comment]
Hey Oli-
Ok, thanks for the thoughts. We'll work something out and I'll share the results soon.

Thanks!
Danny
