### ISSUE TITLE
Great Grid

### ISSUE THREAD

**Issue by RCNCapitalDomains** [olifolkerd/tabulator#192]
We are using it, and love it.  Would like support your great work with a monetary donation.  Didn't see any links anywhere for that.

**Comment by olifolkerd** [comment]
Hey,

Sorry for taking so long to get back to you,

Thanks for your kind offer.

At the moment I am creating Tabulator as a chance to give back to the coding community so i am not accepting donations. but later in the year I will be releasing version 3.0 of Tabulator, a dependency free, pure JavaScript version of the library.

At that point i will be launching a new website complete with loads of new feathers, and any donations towards hosting costs etc would be much appreciated.

Thanks for getting in touch.

Cheers

Oli
