### ISSUE TITLE
ReplaceData using Remote Pagination

### ISSUE THREAD

**Issue by agustingrigoriu** [olifolkerd/tabulator#1920]
Hi! Im' trying to use replaceData to refresh my table. The idea is to keep the table in the same page after refreshing it, but replaceData is not working. It takes me to the first page again. Also, I'm using remote pagination, could this have anything to do? Thanks in advance.

**Comment by aklaver** [comment]
Could this be the issue:
http://tabulator.info/docs/4.2/update#alter-replace

"Note The replaceData function will only maintain scroll position when the Vitrual DOM has been enabled by setting a height on the table."

Otherwise could you show the code?

**Comment by olifolkerd** [comment]
if you are using remote pagination then the data is all being handled remotely so there is nothing for Tabulator to replace with, the ***replaceData*** function is primarily to be used when loading whole data sets into the table not individual pages.

Having said that there is nothing to stop you using the ***getPage*** function to retrieve the current page number before you update the table, then calling the ***setPage*** function to restore it after you change the data sourcce.

Cheers

Oli :)
