### ISSUE TITLE
How to Dynamically Change table layout

### ISSUE THREAD

**Issue by rs199483** [olifolkerd/tabulator#1921]
Is it possbile to change the layout after you define the table?
`var table = new Tabulator("#example-table", {
    layout:"fitData",
});
`

Something like this:
table.setLayout("fitColumns");

**Comment by aklaver** [comment]
You can change the height using setHeight(). There is setColumns() where you can supply a different set of column definitions. AFAIK you cannot change the data layout on the fly.

**Comment by rs199483** [comment]
Well I was hoping to have a couple buttons on my page that let's the user toggle between fitColumns and fitData.  I could probably re-define/initialize the table each time but that doesn't seem very clean.

**Comment by aklaver** [comment]
At this point this looks to be the only option.

**Comment by olifolkerd** [comment]
Hey @rs199483 

You cannot change this on a table as such, it is such a big change to the layout that it would essentially mean trashing the table and starting again.

The correct approach in this instance would be to destroy the existing tabulator by calling the ***destroy*** function on it, then reinstatiating it with the new layout mode set in the table definition.

Cheers

Oli :)
