### ISSUE TITLE
How to set custom header filter operator for ajax filtering?

### ISSUE THREAD

**Issue by fingers10** [olifolkerd/tabulator#1925]
Hi Tabulator Team,

First of all thanks for your awesome work. I started using Tabulator a month ago and I started loving Tabulator.

I'm trying to pass a custom header filter operator for each column in my ajaxFiltering, but the filter params always returns `like` value.

here is my scenario.
i'll be sending my filters in the server url as follows:
`https://localhost/api/test?search=name eq test&dob gt 12/12/2012&...`

so in my columns definition,
```
      {
        title: 'Name',
        field: 'name',
        headerFilter: 'input',
        headerFilterLiveFilter: false,
        type: 'eq'
      },
      {
        title: 'DOB',
        field: 'dob',
        headerFilter: 'input',
        headerFilterLiveFilter: false,
        type: 'gt',
      },...
```
But my `params.filters` array in `ajaxURLGenerator` always returns `type: "like"` for all the fields.
it would be nice if there is an option to make my `params.filters` array to return the type I mention in the column definition of each column like `type: "eq"`, `type: "gt"`, etc..

Am I missing something from docs?

I searched and could'nt find a way. Help would be much appreciated.

**Comment by aklaver** [comment]
http://tabulator.info/docs/4.2/filter
Filter Comparison Types 
...

"f you want to specify the type of filter used you can pass it to the headerFilterFunc option in the column definition object. This will take any of the standard filters outlined above or a custom function:"

**Comment by fingers10** [comment]
HI aklaver,

I tried like this

```
        {
        title: 'Name',
        field: 'name',
        headerFilter: 'input',
        headerFilterLiveFilter: false,
        headerFilterFunc: '>'
      },
      {
        title: 'DOB',
        field: 'dob',
        headerFilter: 'input',
        headerFilterLiveFilter: false,
        headerFilterFunc: 'gt',
      },...
```

if I use operators in `headerFilterFunc: '>='`, I'm getting that in filter params as `type: >=`, but if I use my own operators like `headerFilterFunc: 'gt'` or `headerFilterFunc: 'eq'`, params.filters gives `type: like`.

Any configuration needs to be done?

**Comment by tentus** [comment]
To my knowledge there's not a way to register in new kinds of filters (though admittedly my knowledge is very limited). From looking at your examples though, it kind of seems like you're looking to just translate the types over to a format your api accepts, not adding any unusual new kinds of filters. If that's the case, you can iterate over the `params.filters` in the `ajaxURLGenerator` function like you mentioned and swap out the types, like so:
```
          const operators = {
            '=': 'eq',
            '>': 'gt',
            '>=': 'gte',
            '<': 'lt',
            '<=': 'lte',
            '!=': 'neq',
          };

          (params.filters || []).forEach(function (filter) {
            filter.type = operators[filter.type] || filter.type;
          });
```

**Comment by aklaver** [comment]
Per the link above it will only take the filter operators(functions) defined by Tabulator.  You can create a custom function but that will be supplied as the function name. You could do what @tentus  mentioned above or what I do which is make the translation on the server end in what ever is processing your request.

**Comment by fingers10** [comment]
@tentus I was even thinking of something like this. This works. But it would be great if we get a chance to add our own operators for server side filtering directly to column definitions. If possible Tabulator team can implement this useful feature in future releases.

Thanks for the help. We can close this.

**Comment by olifolkerd** [comment]
Hey @fingers10 @tentus 

Almost everything in Tabulator is customisable

#### Custom Filter Function
You can either pass a callback into the ***headerFilterFunc*** which is covered in the [Header Filter Documentation](http://tabulator.info/docs/4.2/filter#header)

#### Extend Filter Module
You can also expand Tabulator to add custom built in filters, checkout the [Filter Module Docs](http://tabulator.info/docs/4.2/modules#module-filter) for more information on how to do this,

you can then pass that string of the key into the ***headerFilterFunc*** to reference a specific filter.

Because this string is passed back in the ajax request if all you need it for is to pass back the string you can define the filter function as an empty callback and it will do what you need.

I hope that helps,

Cheers

Oli :)
