### ISSUE TITLE
GetData function returns an array of undefined

### ISSUE THREAD

**Issue by telpat0298** [olifolkerd/tabulator#1926]
Im a using version 4.2:
Used js files and modules:
- jquery.min.js
- tabulator.min.js
- tabulator_core.min.js
- edit.min.js
- moment.min.js

Constructor:
`tabulator = new Tabulator("#tabulator", {
                    columns:[
                        {title:"Name", field:"name", sorter:"string", width:200, editor:true},
                        {title:"Age", field:"age", sorter:"number", align:"right", formatter:"progress"},
                        {title:"Gender", field:"gender", sorter:"string", cellClick:function(e, cell){console.log("cell click")},},
                        {title:"Height", field:"height", formatter:"star", align:"center", width:100},
                        {title:"Favourite Color", field:"col", sorter:"string"},
                        {title:"Date Of Birth", field:"dob", sorter:"date", align:"center"},
                        {title:"Cheese Preference", field:"cheese", sorter:"boolean", align:"center", formatter:"tickCross"}
                    ],
                    data: [
                        {id:1, name:"Billy Bob", age:"12", gender:"male", height:1, col:"red", dob:"", cheese:true},
                        {id:2, name:"Mary May", age:"1", gender:"female", height:2, col:"blue", dob:"14/05/1982", cheese:true},
                        {id:3, name:"Christine Lobowski", age:"42", height:0, col:"green", dob:"22/05/1982", cheese:"true"},
                        {id:4, name:"Brendon Philips", age:"125", gender:"male", height:1, col:"orange", dob:"01/08/1980"},
                        {id:5, name:"Margret Marmajuke", age:"16", gender:"female", height:5, col:"yellow", dob:"31/01/1999"},
                        {id:6, name:"Billy Bob", age:"12", gender:"male", height:1, col:"red", dob:"", cheese:true},
                        {id:7, name:"Mary May", age:"1", gender:"female", height:2, col:"blue", dob:"14/05/1982", cheese:true},
                        {id:8, name:"Christine Lobowski", age:"42", height:0, col:"green", dob:"22/05/1982", cheese:"true"},
                        {id:9, name:"Brendon Philips", age:"125", gender:"male", height:1, col:"orange", dob:"01/08/1980"},
                        {id:10, name:"Margret Marmajuke", age:"16", gender:"female", height:5, col:"yellow", dob:"31/01/1999"}
                    ]
                });`

Im initializing an instance when the document-ready function triggers and everything seems to work properly.
(The tabulator variable is declared in as global variable and not as local variable in the ready function)
But when im executing the command tabulator.getData() in the console (chrome->developer options), it returns an array of undefined items(same number as rows in table btw) as mentioned in the attached screenshot. 

 - OS: Debian 8
 - Browser chrome
 - Version 73.0.3683.75

Thx in advance
Greetings
Patrick
![getData](https://user-images.githubusercontent.com/48835517/54837165-04d7d500-4cc6-11e9-8742-223de5af6b4c.PNG)

**Comment by tentus** [comment]
Would you make a JS Fiddle illustrating your issue (https://jsfiddle.net/)? It'll make diagnosis much quicker and more reliable.

**Comment by telpat0298** [comment]
Yeah sure. https://jsfiddle.net/cgbvz367/2/

**Comment by tentus** [comment]
If you remove the tabulator_core.min.js resource (since you already have tabulator.min.js in there) then `getData()` will work as expected.

https://jsfiddle.net/0125kbd7/

**Comment by telpat0298** [comment]
Ohh.. haven't noticed that. Thanks a lot
