### ISSUE TITLE
Sorting & Re-drawing very slow in IE11

### ISSUE THREAD

**Issue by thejuice33** [olifolkerd/tabulator#1927]
**Describe the bug**
Seeing significant delay in IE11 when sorting or updating the pagination page size on a table with 100 rows.  This works fine in Chrome.  Sorting on a paginated table of 100 rows can take 5-8 seconds.  The issue worsens with the more data that is shown in the table at once (increasing page size).

**Tabulator Info**
- v4.2
- loading JSON data
- Layout: fitColumns
- pagination: local
- responsiveLayout: collapse / hide (this is optional for us)
- tooltips: true
- 14 columns max (may be able to remove a few)
- Importing promise polyfill for IE11
- Importing .min dependencies wherever possible
- Importing jquery independently (didn't seem to be bundled?) v 1.10.1
- Importing moment.js

**Working Example**
https://jsfiddle.net/zuth2g1x/

**To Reproduce**
1. Load a bit over 100 rows in a paginated table
2. Set page size to 100 to show 100 rows at once (and two total pages)
3. Click a sortable column header (see delay)
4. or; Update Page Size for table redraw (see delay)

**Expected behavior**
I'd expect the sort / re-draw to be much faster with this small amount of data.  Once we get up into the 1000-1500 range these speeds for re-sorting / re-drawing would be more acceptable.

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit
 - Browser IE11
 - Version 11.0.14.14393.0

**Additional context**
Must support IE11 unfortunately at my work and need this to be faster in IE11.

Aside from this problem this is an awesome table design.  We are currently evaluating a few different products and if I can get this to be more responsive in IE11 it will be the clear winner in our teams evaluation of which solution to go with.  Thank you!

**Comment by olifolkerd** [comment]
Hey @thejuice33 

Your JS Fiddle seems to be missing a table, there is just a search text box.

Cheers

Oli :)

**Comment by thejuice33** [comment]
First timer here apologies :)  I think I've got it sorted now...

https://jsfiddle.net/uLb2q8ev/5/

Thanks for looking Oli!
