### ISSUE TITLE
row.getElement(...).css is not a function

### ISSUE THREAD

**Issue by anonthemon** [olifolkerd/tabulator#1929]
I am trying to change the color of a row based on it's value in a database. However, I am getting row.getElement(...).css is not a function as an error. I am using the latest Tabulator js and css files. I used the example given in the documentation. 

    var tabledata = [
 	{id:1, name:"Oli Bob", age:"12", col:"red", dob:""},
 	{id:2, name:"Mary May", age:"1", col:"blue", dob:"14/05/1982"},
 	{id:3, name:"Christine Lobowski", age:"42", col:"green", dob:"22/05/1982"},
 	{id:4, name:"Brendon Philips", age:"125", col:"orange", dob:"01/08/1980"},
 	{id:5, name:"Margret Marmajuke", age:"16", col:"yellow", dob:"31/01/1999"},
     ];

    var table = new Tabulator("#example-table", {
 	height:205, // set height of table (in CSS or here), this enables the Virtual DOM and improves render speed dramatically (can be any valid css height value)
 	data:tabledata, //assign data to table
 	layout:"fitColumns", //fit columns to width of table (optional)
 	columns:[ //Define Table Columns
	 	{title:"Name", field:"name", width:150},
	 	{title:"Age", field:"age", align:"left", formatter:"progress"},
	 	{title:"Favourite Color", field:"col"},
	 	{title:"Date Of Birth", field:"dob", sorter:"date", align:"center"},
 	],
 	rowClick:function(e, row){ //trigger an alert message when the row is clicked
 		alert("Row " + row.getData().id + " Clicked!!!!");
 	},
    rowFormatter:function(row){
    //row - row component

    var data = row.getData();

    if(data.col == "blue"){
    row.getElement().css({"background-color":"#A6A6DF"});
    }
    },
    });

   I also get: Uncaught (in promise) TypeError: row.getElement(...).css is not a function

**Comment by anonthemon** [comment]
Sorry I saw the issue that Tabulator no longer uses jQuery and fixed the issue with getElement().style.backgroundColor.

**Comment by jamsoft** [comment]
How is this closed yet the documentation is still out of date?

http://tabulator.info/docs/4.0/format#row
