### ISSUE TITLE
addRow add two rows  when no data filter is active 

### ISSUE THREAD

**Issue by Paraplegix** [olifolkerd/tabulator#193]
Hello it's me again with a new little bug :
Reproduction : http://olifolkerd.github.io/tabulator/examples/#adddel
1) Add row with the button 
2) (optional) change a value in the new row
3) click on the header to trigger a refresh of the table
4) the new row will be duplicated in the table and also in the tabulator("getData") wich is kinda annoying

I didn't do extensive testing  so don't know how wide this affect the library, but i've looked into the code and i can say that the problem is around [here L1678](https://github.com/olifolkerd/tabulator/blob/master/tabulator.js#L1678) and [here L1264 to L1272](https://github.com/olifolkerd/tabulator/blob/master/tabulator.js#L1264)
My guess is with no filter `activeData `and `data `have the same reference, and when you add a row, it push at the same time in `activeData `and `data` so data is duplicated

Workaround until its patched: 
set a filter to a unexisting column , asking it to be different (!=) from something, As long as the filter is not removed, it shouldn't add any more a row twice !

At the same time lets pop in some suggestions : 
- Create "**calculated field**" : i've tryed doing that with formater, but it doesn't get updated when you edit a cell (the aim is to do a total of other cells, and update it in realtime). I've working around by throwing a `updateData` from a `cellEdited `callback but I don't find it pretty :(
- progressiveRender : Make the `tabulator-table` class div (the one that containe the rows) the estimated height of all the rows when displayed, this will make the vertical scrollbar the good size and it will help the user visualise how big the data set is.
- keep the current state of the groups (open or closed) when the table is refreshed
- when filtering data, make the view back to the rows the user was looking when the view is refreshed (currently it just stay at the same height, but the row the user was seing do not stay in front of him)
Also progressiveRender  is currently unusable with data grouping :( 

for the progressive Rendering i'd guess its a work in progress ? it might be interessting to develop it further for huge datasets

Keep up the good work, this plugin is great !

(sorry for my bad English)

**Comment by olifolkerd** [comment]
This should now be resolved
