### ISSUE TITLE
row.getElement().style.backgroundColor not working with a stored variable 

### ISSUE THREAD

**Issue by anonthemon** [olifolkerd/tabulator#1930]
I am using row.getElement().style.backgroundColor to change a row background. This works with quotes and a direct color like "blue". However, if I store it in a variable, as I am getting the variable default_color from my database, it won't change the color properly. 

    rowFormatter:function(row){
				var data = row.getData(); //get data object for row
				var color = "\""+ row.getData().default_color +  "\""
				console.log(color);
				if(data.default_color == "blue"){
					row.getElement().style.backgroundColor = color;  //apply css change to row element
					
				}
			},

Vs when I do just 

    if(data.default_color == "blue"){
					row.getElement().style.backgroundColor = "blue";  //apply css change to row element
					
				}
The variable is properly stored as I echo it in the console. But it won't change the color. Am I missing something?

**Comment by olifolkerd** [comment]
The issue is because you are storing the quotes as part of the string for some reason. you can asign the value directly to the property:
```js
row.getElement().style.backgroundColor = data.default_color;
```
I hope that helps

Cheers

Oli :)
