### ISSUE TITLE
The data is displayed only within the half of the given height + date formatting issue

### ISSUE THREAD

**Issue by boumboum** [olifolkerd/tabulator#1932]
For any reason the grid (the number of visible rows) is not displayed within the whole given height, while the vertical scrollbar takes all the 800px.
When I'm scrolling the amount of displayed rows change aleatory a bit.

Also I have an issue for formatting the date.
The input format is regular iso format: 2006-01-01T00:00:00.000Z
What should I give for the inputFormat?
I'm using version 4.2 and Firefox 66 under Windows (Chrome displays fine the given length)
```
			var table = new Tabulator("#mytable", {
				ajaxConfig:"POST",
				ajaxURL:"http://192.168.100.11/", 
				height:800,
				columns:[ 
					{title:"id", field:"id", width:100},
					{title:"Név", field:"nev", width:150},
					{title:"felettes", field:"felettes", width:100},
					{title:"koltseghely", field:"koltseghely", width:100},
					{title:"Munkavégézés", field:"munkavegzes_hely", width:200},
					{title:"mmk", field:"mmk", align:"right", sorter:"number", },
					{title:"belepes", field:"belepes", sorter:"date", align:"center", 
					 formatter:"datetime", formatterParams:{
										inputFormat:"YYYY-MM-DDThh:mm:ss",
										outputFormat:"YYYY-MM-DD",
										invalidPlaceholder:"wrong format"}
					},
					{title:"maradek_szabi", field:"maradek_szabi", sorter:"number", align:"right"},
					{title:"aktiv", field:"aktiv", sorter:"boolean", align:"center", formatter:"tickCross"},
				],
			});
```

**Comment by aklaver** [comment]
Re: datetime input format did you?:
http://tabulator.info/docs/4.2/format#format-builtin
"You will need to include the moment.js library  ..."
If you have what is the exact issue?

As to grid height, I do not understand what the issue is.
Can you be more specific?
