### ISSUE TITLE
Numeric formatter for bottomCalcParams

### ISSUE THREAD

**Issue by boumboum** [olifolkerd/tabulator#1933]
It would be nice to have a proper formatting for the column calculation cells.
For the regular cells, there is the possibility to define the decimal symbol or the thousand separator what is nice, but for the bottomCalc cell only the precision tag is available.
So either the calculated cells should inherit the formatting from the column definition (this one would be preferable) or the same values should be added to the bottomCalcParams as for the formatterParams

**Comment by aklaver** [comment]
Have you ;looked at formatters:

tabulator.info/docs/4.2/column-calcs
"Formatting Calculation Cells

You can apply formatters (see Formatting Data for more information) to any calculation cells, using the topCalcFormatter and bottomCalcFormatter options in a columns definition object. you can also pass in additional parameters to the formatter functions using the topCalcFormatterParams and bottomCalcFormatterParams options: "

Use the money formatter w/o the symbol parameter.

**Comment by boumboum** [comment]
Of course I've looked at the docs. 
But for the bottomCalcFormatter there is only the precision option available.
Of course I've tried to cheat and use the other formatting options but that had no effect.

**Comment by aklaver** [comment]
Please show us what you did when you used the formatter.

**Comment by olifolkerd** [comment]
@boumboum as @aklaver says, any of the built in formatters can be used to format calculation cells
