### ISSUE TITLE
By doubleclicking on a word in a cell 1-3 others words from other cells are also selected

### ISSUE THREAD

**Issue by boumboum** [olifolkerd/tabulator#1934]
Strange behaviour: 
If I double click on the first word of a cell, the contents of the 2-3 previous cells are also selected.
If I double click on the last word of a cell, the contents of the 2-3 following cells are also selected.
If there is a singe word in a cell and I double click on it, some previous AND some following cells are also selected.
BUT if there are several words in a cell (like an address) and I double click on a word in the middle, only the clicked word will be selected

**Comment by olifolkerd** [comment]
Hey @boumboum 

Sorry to hear you are having issues,

That is very odd behaviour that i certainly havnt seen before.  could you create a JS Fiddle or Code Pen that demonstrates the behaviour you are experiencing?

Cheers

Oli :)

**Comment by boumboum** [comment]
Hi,
No need any JS Fiddle. Just use your own examples on http://tabulator.info/examples/4.2.
Different behaviour on Firefox and Chrome.
On Firefox:
If there are more then one string (or even a 3 part date) in cell, you cannot select the last word/string by double clicking on it, but you can do this on the remaining previous ones.
If you click 3 times on any word, the whole content of the cell is selected. This one seems to be a standard GUI behaviour as I can reproduce it with other components as well.

On Chrome:
If there are at least 3 words in a cell (i.e a date) and you double click in a word in the middle, then the only this word is selected.
If you double click on the first, or the last word, the some previous words in some previous cells or subsequent words in some subsequent cells are selected.
If I click 3 times then the whole content of the selected cell will be selected (as in Firefox), even if after the second click some other words have been selected (as described above)

I've never seen this kind behaviour elsewhere.

**Comment by cschnelting** [comment]
Hi Oli,

i have the same behaviour on Tabulator. Do you have a solution for this?

Thanks!

**Comment by fingers10** [comment]
Dear Oli,

This looks weird. I checked with the examples in the documentation and its happening. Just double click on **Rogahn** in the second row Name Column. You can see that happening.

Attached a screen print for your reference.

![image](https://user-images.githubusercontent.com/43729469/58225421-99e76080-7d3f-11e9-83de-2fbaac86b7f9.png)


Thanks,
Abdul

**Comment by boumboum** [comment]
Oli,
You don't have to close this issue, as now there is an other strange behaviour (taken from your website: http://tabulator.info/examples/4.2)
I you double click on the first word, it is OK, but you cannot double click on the second word (like on Cruickshank from the first record of Herbert Cruickshank) The first name is double clickable, but you cannot select the second word (Cruickshank) by double clicking on it.
This is the same on every lines.
All this in Firefox

**Comment by olifolkerd** [comment]
Hey @fingers10 

As per your other issue this morning i have pushed a fix to the 4.3 branch that fixes this and will be released later today

Cheers

Oli :)
