### ISSUE TITLE
Row Formatter .css() doen't work

### ISSUE THREAD

**Issue by dota2Pro** [olifolkerd/tabulator#1935]
**Describe the bug**
Unable to set background color of a row using rowformatter

as per [documentation](http://tabulator.info/docs/4.2/components#component-row)

**Tabulator Info**
-v 4.2.3

**Working Example**
['Jsfiddle'](https://jsfiddle.net/dota2pro/hr4vzefj/11/)

**To Reproduce**
1. Go to ['thisJsfiddle'](https://jsfiddle.net/dota2pro/hr4vzefj/11/)
2. See error in console. Uncaught TypeError: row.getElement(...).css is not a function

**Expected behavior**
Should set the background color to #A6A6DF

**Comment by rob196** [comment]
Think the documentation might be outdated, but please see [https://github.com/olifolkerd/tabulator/issues/1929](url) for fix/alternative

**Comment by dota2Pro** [comment]
> Think the documentation might be outdated, but please see [https://github.com/olifolkerd/tabulator/issues/1929](url) for fix/alternative

@rob196  Issue # 1929 doesn't exist ( broken link )

**Comment by rob196** [comment]
@dota2Pro sorry my bad, correct link: [#1929](https://github.com/olifolkerd/tabulator/issues/1929)
