### ISSUE TITLE
Row groupings don't update automatically

### ISSUE THREAD

**Issue by takuy** [olifolkerd/tabulator#1936]
**Describe the bug**
Not sure if this intentional or not, but when changing a value in a row (where that value is the groupBy value) - the groups don't update unless you manually call setGroupBy(). unfortunately, this reloads the whole table and makes you lose your position. 

I am aware that the drag and drop behavior works fine, but my table has too many groups for that to be effective. 

**Tabulator Info**
4.2 - table config included in codepen below

**Working Example**
https://codepen.io/tako1337/pen/qveoYY

**To Reproduce**

**Expected behavior**
Groups update when row values change.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome 73

**Comment by olifolkerd** [comment]
Hey @takuy 

That will be happening because you have not got a height set on the table, and so the virtual DOM is not being used. without the virtual DOM tabulator has no way of regrouping rows without redrawing the whole table.

If you set a height it should work.

Cheers

Oli :)

**Comment by takuy** [comment]
Hi @olifolkerd, Thanks for the response - I am setting a height on the table in my production code. I forgot to do it on the test codepen - so that has been updated, and I am getting the same results. The groups only update if I call setGroupBy() - and then, it still redraws the whole table.

**Comment by olifolkerd** [comment]
Hey @takuy 

Thanks for the update to the code pen, that certainly looks buggy to me, i will look at including a fix in the next patch release.

Cheers

Oli :)

**Comment by takuy** [comment]
Thanks @olifolkerd! Your work on Tabulator is much appreciated.

**Comment by takuy** [comment]
Btw @olifolkerd can you un-close this? Just so I can get a notification if there's an update. Closed issues don't seem to send notifications. :)

**Comment by olifolkerd** [comment]
@takuy if you update to 4.2.5 do you still have the issue?

**Comment by takuy** [comment]
@olifolkerd Yes - I updated the codepen with 4.2.5 and it's still happening.

**Comment by olifolkerd** [comment]
Hey @takuy 

ok i will investigate further in the next patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @takuy 

Ahh sorry i follow you now, i did put some fixes into row movement but not for this specific circumstance.

It is actually intended behaviour for it to behave this way at the moment because it could be jaring for the user if they are working there way along a row and it suddenly moves to a new group.

But i do take your point on board, i will look at setting this as an option in the 4.3 release in may.

Thanks for the feeback

Cheers

Oli :)

**Comment by takuy** [comment]
no problem. The main thing for reporting this was due to the inconsistency - moving a row between groups updates the value, but changing the value doesn't update the grouping.

Is there currently a way to redraw the table at the current/specific position? Might have missed in the documentation. I only see a way to do it when replacing or setting the data. I can just force it to happen on CellEdited(). SetGroupBy() seems to reset the position.

**Comment by takuy** [comment]
@olifolkerd Hey Oli, thanks again for another great release! It's been a few months since we spoke about this specific issue. I don't see it on the roadmap, so I just wanted to know if this is still a plan to look at it. I can look into doing this myself as well, but I don't see an obvious way to redraw but keep current position.

**Comment by AndrewHutcheson** [comment]
Is this fixed? I tried on 4.5.3 and it seems to still be the same.

**Comment by olifolkerd** [comment]
The PR linked to this issue has been approved for merge in the 4.8 release next week.

Cheers

Oli :)
