### ISSUE TITLE
download xlsx with multiple sheets does not allow you use selector for current table

### ISSUE THREAD

**Issue by takuy** [olifolkerd/tabulator#1939]
**Describe the bug**
very low priority 

Tabulator XLSX's download feature for multiple sheets does not allow you use selector for current table.
In this case the first sheet -  #table1 is never found. Even if included with a DOM element, it always reports that it could not find that table. I don't see why you wouldn't be able to reference the sheet by selector or DOM. 

It's just a bit inconsistent that you have to use "true" to identify the current table. 

`Table Connection Error - No tables matching selector found #table1`
```
$table1.download("xlsx", "Test.xlsx", {
    sheets: {
      "table1": "#table1",
      "table2": "#table2"
      }
  });
```

**Tabulator Info**
- 4.2.3

**Working Example**
https://codepen.io/tako1337/pen/OGLyoe

**To Reproduce**
1. open codepen
2. click Download
3. look at console log for error/warning

**Expected behavior**
all tables included in object by selector or DOM should be found and downloaded

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome 73

**Comment by olifolkerd** [comment]
Hey @takuy 

It isnt a  bug, you have to specify that the current table is used somewhere in the list as this function cannot be used to generate a download of tables unrelated to the current table.

as it is possible to define two tables using the same selector it would create a great deal of confusion and lead to inconsistent results if that was used to select the current table.

and also a selector isnt needed as the table knows what it is so it doesn't need to go through the process of looking itself up.

For these reasons i will not be looking to change this functionality.

Cheers

Oli :)
