### ISSUE TITLE
Hide pagination control?

### ISSUE THREAD

**Issue by jbasemvd** [olifolkerd/tabulator#194]
Is there a way to hide the pagination control when there is only a single page to display?

Thanks in advance.

**Comment by olifolkerd** [comment]
Hey,

That is not problem at all. You can use the ***renderStarted*** callback to deiced whether on not or show the pagination footer based on the ***getPageMax*** value:

```js
$("#example-table").tabulator({
	pagination:true,
	columns:[
	    {title:"Name", field:"name"},
	],
	renderStarted:function(){
		if($("#example-table").tabulator("getPageMax") > 1){
			$("#example-table .tabulator-footer").show();
		}else{
			$("#example-table .tabulator-footer").hide();
		}
	},
});
```

Let me know if that answers your question.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey jbasemvd,

Did this answer your query?
