### ISSUE TITLE
Tabulator 4.2 - Sorting does not work when initialized but works when clicking the column

### ISSUE THREAD

**Issue by nrietsch** [olifolkerd/tabulator#1941]
Hi,

I'm using a single table element and load 3 different sets of data depending on a condition (i.e. tab selection).

I therefore use the following 2 commands when changing tab:
```
table.setColumns(ctrlColumns);
table.setSort("Type", "asc");
```

The Type column is a number between 1 and 18.
When the table gets initialized (i.e. the above commands), my Type column is sorted like 1,10,11,...19,2,3,...,9

If I click on the column header however, the columns do get sorted as expected: 1,2,3,....18,19

This is my column definition:
`{title:"Type", field:"Type", width:70, align:"center", formatter:"plaintext", editor:"number", sorter:function(a, b){return a - b;}},`

Note: I tried to use sorter:"number" and sorter:"string" but it would not sort correctly either way resulting in 1,10,11,...19,2,3,...,9 all the time.

I'd like to point out that on another column, I'm loading a picture so that table does take a second or two total to load completely. Is that the reason why the sorter does not work correctly up front?

Is this an issue or am I doing wrong?

**Comment by morficus** [comment]
Did you try removing the "formatter" value from the column definition?

**Comment by nrietsch** [comment]
just removed the formatter to no avail

**Comment by morficus** [comment]
Here is a quick sample attempting to recreate your setup but I'm not able to replicate your issue:
https://jsfiddle.net/morficus/7nrhkxzq/4/

notice how the "age" property is a string.
I'm loading both the columns, the data and setting the sort order after initializing the table.

could you share your table config or maybe you have a custom sorter defined elsewhere?

**Comment by nrietsch** [comment]
Hi,

I think that loading the pictures in the table is what's causing the problem because it delays the 'display' of the table.

Here is my structure:

```
 	var table = new Tabulator("#table", {
//    	height: tableheight,
		data:[],
//		resizableColumns:false,
		layout:"fitColumns",
		tooltips:true,
		addRowPos:"top",
		history:true,
		index:"Id",
		dataEdited:function(data){
			$("#tabulator-controls  button[name=undo]").show();
			$("#tabulator-controls  button[name=cancel]").show();
			$("#tabulator-controls  button[name=save-data]").show();
		},
		rowSelectionChanged:function(data, rows){
			rowcount = data.length;
			(rowcount > 0) ? $ ("#tabulator-controls  button[name=delete]").show() : $("#tabulator-controls  button[name=delete]").hide();
		},
		columns:[],
	});
```
And this is the actual table I'm having issues with:

```
	var ctrlColumns = [
		{rowHandle:true, formatter:"handle", headerSort:false, frozen:true, width:30, minWidth:30, cellClick: 	function (e, cell) {
			//var id = cell.getRow().getData().Id;
			cell.getRow().toggleSelect();
			$("#tabulator-controls  button[name=add-row]").toggle();
			}
		},
		{title:"Id", field:"Id", visible:false},
		{title:"Model", field:"Model", width:80, editor:"input"},
		{title:"Type", field:"Type", width:70, align:"center", editor:"number", sorter:function(a, b){return a - b;}},
		{title:"Picture", field:"Type", width:200, align:"center", formatter:ctrlpicture, variableHeight:true, cellClick:pictureEdit},
		{title:"SSD", field:"SSD", width:90,  align:"center", formatter:"tickCross", sorter:"boolean", editor:true},
		{title:"SAS", field:"SAS", width:90,  align:"center", formatter:"tickCross", sorter:"boolean", editor:true},
		{title:"NLSAS", field:"NL_SAS", width:90,  align:"center", formatter:"tickCross", sorter:"boolean", editor:true},
		{title:"SATA", field:"SATA", width:90,  align:"center", formatter:"tickCross", sorter:"boolean", editor:true},
		{title:"Controller PN", field:"PartNumber", width:130, editor:"input"},
		{title:"Battery PN", field:"Battery_PN", width:130, editor:"input"},
		{title:"Compatible Arrays", field:"Compatible_Arrays", editor:"input"},
	];

```
As you can see, there is a picture column with formatter:ctrlpicture:
```
	var ctrlpicture= function(cell, formatterParams){
		var value = this.sanitizeHTML(cell.getValue());
		if (typeof value !== "undefined") {
			var image_url = "./img/" + value + ".jpg";
			
			if (imageExists(image_url)) {
				var img = $("<img src='" + image_url + "' style='max-width: 200px;'/>");
			} else {
				var img = $("<img src='./img/noImageAvailable.gif'/>");
			}
			img.on("load", function(){
				cell.getRow().normalizeHeight();
			})
			return img[0];
		}
	};
```
THIS function checks if the image file does exist or not. If it gets a 404 answer, it will display a default picture.

The result being that this table is taking 3 seconds to load. I think, but I may be wrong, that this is what is causing the issue.

**Comment by nrietsch** [comment]
one more thing, that ctrlpicture is being called a hundred times which is why I added the `if (typeof value !== "undefined") {` test...

I have no idea why.

**Comment by morficus** [comment]
@nrietsch - if you remove/comment out the pictures column, does the issue go away?

As for why `ctrlpicture` was being called hundred of times... it will be called for each row in your table. So if you table has 200 rows... then it would get called 200 times every time the grid re-renders.

**Comment by olifolkerd** [comment]
Hey @nrietsch @morficus 

The issue is happening because you are calling the commands one after the other and the ***setColumns*** command hasnt finished executing before the ***setSort*** is being called.

for the record formatters have ***nothing*** to do with sorting, they are in no way related, formatters are for display only, sort works on the row data.

If you have to keep your original table i would suggest that you set the table data to an empty array, then set your columns, then set your sort, then set your data.

The better solution though would be to redefine your table since you are changing everything about it (it will also be much more efficient than calling each function in turn as each one will trigger a table redraw.  to do this call the ***destroy*** function on the original table and then reinistatate it with a new table definition object. you can then use the ***initialSort*** option on the table to define the initial sort.

I hope that helps,

Cheers

Oli :)

**Comment by nrietsch** [comment]
Year, good idea for the test.. My head is so buried that I didn't even think about it.
Anyhow, If I disable my picture column, the type column gets ordered correctly.
So, it's the delay in loading (and checking) the pictures that makes the initial sorting fail; it's confirmed now.

As for the amount of times the function is called, I have 18 entries in my table...
