### ISSUE TITLE
Custom fileformatter running into data.forEach is not a function

### ISSUE THREAD

**Issue by anonthemon** [olifolkerd/tabulator#1943]
I am trying to use a custom fileformatter so I can download my data as a tab delimited text file. Here is what I have:

    var fileFormatter = function(columns, data, options, setFileContents){
    //columns - column definition array for table (with columns in current visible order);
    //data - currently displayed table data
    //options - the options object passed from the download function
    //setFileContents - function to call to pass the formatted data to the downloader

    //create a list of all name fields
    var names = [];
	

    data.forEach(function(row){
        names.push(row.name);
    });

    //trigger file download, passing the formatted data and mime type
    setFileContents(names.join("\t"), "text/plain");
    }

      $("#download-button").on("click", function(){
        table.download(fileFormatter, "test.txt");

    });

However, I am getting this error:

data.forEach is not a function
    at y.fileFormatter (sampletemplate.php:923)
    at y.download (tabulator.min.js:6)
    at t.u.download (tabulator.min.js:5)

Is there an update that is keeping me from using the forEach? I am using the latest version of tabulator and jquery 3.3.1

**Comment by aklaver** [comment]
My experience with this error is that it indicates that what is being passed into data is not an array. .forEach is a method(function) of the Array type so if you try to call it on something that is not an array it fails with 'forEach is not a function'.  I would verify  that 'test.txt' is an array.

**Comment by rob196** [comment]
Think you need to use data.data i.e.:

```
data.data.forEach(function(row){
    names.push(row.name);
});
```
The data in my test app contains data & calcs as per below screenshot
![image](https://user-images.githubusercontent.com/20188626/55311903-7fda8180-5464-11e9-9fa2-f100cf4e0c6c.png)

**Comment by aklaver** [comment]
Well I was not thinking straight in my previous post. 'test.txt' is the output file so no need to verify that it is an array.
