### ISSUE TITLE
'success'/'error' like feature in fetch ajaxConfig in version 4.2

### ISSUE THREAD

**Issue by ctlkkc** [olifolkerd/tabulator#1944]
Hi Oli, im a user migrating from version 3.5 to 4.2. Noticing the method has been migrated from ajax to fetch, I am not sure how to define success or error actions in this new framework: I used:

```
var ajaxConfig = {
		cache: false, 
		timeout: 6000,
		success: function(results) {
			console.log( moment.tz(moment.tz.guess()) + " - Retrieved data from server successfully.");
			document.getElementById('status').setAttribute('style','background-color: #00CD00;');
			$("#status_text").val(' UPDATING');
			//console.log(results);
		},
		error: function() {
			console.log( moment.tz(moment.tz.guess()) + " - Failed to retrieve data from server.");
			document.getElementById('status').setAttribute('style','background-color: #FF1919;');
			$("#status_text").val(' DISCONNECTED');
		}
};
```

in version 3.5 to indicate page element is ajax response is successful but seems I cannot handle the fetch promise inside the ajaxconfig definition. Can you help providing an idea?

Thanks!

**Comment by olifolkerd** [comment]
Hey @ctlkkc 

You need to use the ***ajaxResponse*** and ***ajaxError*** callbacks in the tabulator definition to handle this, the shouldn't be set in the ajax config

Full details can be found in the [Ajax Documentation](http://tabulator.info/docs/4.2/callbacks#ajax)

I hope that helps,

Cheers

Oli :)

**Comment by ctlkkc** [comment]
Thank you, it works!
