### ISSUE TITLE
Sort IP adress

### ISSUE THREAD

**Issue by vipera7** [olifolkerd/tabulator#1947]
I would like to add a sorter in tabulator. The possibility to sort by ip adress. I build a custom function. I hope it help.

In the function I convert the ip adress into numeric format.
```
{title:"IP", field:"ip", sorter:function(a, b, aRow, bRow, column, dir, sorterParams){
    var d = a.split('.');
    var res_a = ((((((+d[0])*256)+(+d[1]))*256)+(+d[2]))*256)+(+d[3]);
    var p = b.split('.');
    var res_b = ((((((+p[0])*256)+(+p[1]))*256)+(+p[2]))*256)+(+p[3]);
    return res_a - res_b;
},},
```

A one line solution : 

```
{title:"IP", field:"ip", sorter:function(a, b, aRow, bRow, column, dir, sorterParams){
    return ((((((+a.split('.')[0])*256)+(+a.split('.')[1]))*256)+(+a.split('.')[2]))*256)+(+a.split('.')[3]) - ((((((+b.split('.')[0])*256)+(+b.split('.')[1]))*256)+(+b.split('.')[2]))*256)+(+b.split('.')[3]);
},},
```

**Comment by olifolkerd** [comment]
Hey @vipera7 

I think an ip address sorter is a great idea, i will look at adding one in the next release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @vipera7 

Looking into this further, the existing alpha numeric sorter should work correctly on IP addresses, let me know if i am missing something.

Cheers

Oli :)
