### ISSUE TITLE
Tabulator 4.2.1 topcalc shifts into adjacent columns when using toggleColumn

### ISSUE THREAD

**Issue by Darth-Ender** [olifolkerd/tabulator#1948]
When using toggleColumn on a normally not visible column and again immediately after, on a normally visible column to hide that one (they are both the left-most columns at any given time), all of the topCalc elements shift left one column.  The table layout doesn't seem to matter.  Upon reversing the visibility of the two columns again (executing toggleColumn on them again), the topCalc's return to their rightful place. 

Also, topCalc doesn't seem to work at all if the column is not visible initially.  

I'm using vanilla javascript to interact with tabulator - no other addons/libs/modules etc.

**Comment by Darth-Ender** [comment]
It seems there is no div class="tabulator-calcs-holder" created for columns where visibility = false at column setup.   This leads to an offset when display is set to None when a normally visible column is made hidden. 

Only workaround is to make the columns initially visible and then hide them.

**Comment by Darth-Ender** [comment]
Upon further troubleshooting.   it seems you must call table.redraw() after toggling a column in order for the topCalc's to adjust to where they should be. 

I'm not sure if this is a bug or if it's implied that this second function call is always required to be executed after using toggleColumn.  I dont recall it being mentioned in the documentation however.

**Comment by olifolkerd** [comment]
Hey @Darth-Ender 

Thanks for bringing this to my attention, i will have a look into this at the weekend.

In the mean time, could you give me some bullet point instructions on how to recreate the issue. or better yet provide a JS Fiddle or Code Pen to show me it in action.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hi @Darth-Ender 

There was an issue where calculation cells where not being generated if the column was initially hidden so they were not then available if the column was made visible.

I have pushed a fix for this to the master branch and will include it in this evenings update.

Cheers

Oli :)
