### ISSUE TITLE
Ajax Header Filter gets Triggered on Tabbing to  next header input

### ISSUE THREAD

**Issue by fingers10** [olifolkerd/tabulator#1949]
Dear Tabulator Team,

I'm using Tabulator table inside bootstrap modal and my ajax header filter is triggered if I enter values in the header input and tab to next header input. Is this is the default behavior? 

Thanks,
Abdul

**Comment by aklaver** [comment]
What version of Tabulator?
Also take a look at:
https://github.com/olifolkerd/tabulator/issues/1476

**Comment by fingers10** [comment]
Hi @aklaver ,

I'm using Tabulator 4.2.3, What happens is that when I type search text in header filter and press tab key, Tabulator triggers ajax request to the server with header filter values. This is valid scenario and I'm fine with this. Now if I remove the same search text and press tab key, no ajax request is made to server. But it triggers only if I press enter after clearing the search input.

Any way to make ajax search happen only if I press  enter key?

Thanks,
Abdul

**Comment by olifolkerd** [comment]
Hey @fingers10 

This is the correct behaviour yes, an ajax request is triggered on any header filter update when using ajaxFiltering.

Cheers

Oli :)
