### ISSUE TITLE
getData and getSelectedData empty when loading data from ajax

### ISSUE THREAD

**Issue by 1manfactory** [olifolkerd/tabulator#195]
Hello. Love your work. Thanks for offering this to us.

A problem which hounds me:

When filling the table with data inside HTML I can use getData and getSelectedData as stated in the documentation.

But when I fill the table with

$("#example-table").tabulator("setData","getdata.php");

everything is fine: sorting, filtering, selecting - except for getData and getSelectedData. When using this functions now I get an empty result, no matter what I select.

LINE: $("#example-table").tabulator("setData", tabledata); // works

LINE: $("#example-table").tabulator("setData","getdata.php"); // does not work

Are there any additional settings? Or do I have to give to script a special treatment?

All code is loaded at the end of page.

Juergen

**Comment by olifolkerd** [comment]
Hi Jurgen,

Thanks for getting in touch, great to hear you are enjoying Tabulator!

It shouldn't matter how you fill your table, get data should always work. To help get to the bottom of the issue could you answer a few questions:

- Could you post a copy of your tabulator constructor so i can try and isolate the issue.
- Are you getting any errors in your console when you call the ***setData*** command for the url?
- have you checked that the output your are providing from the URL is correctly formatted JSON?
- does the data from the url have correctly set indexes.
- what browser are you using?

Cheers

Oli

**Comment by 1manfactory** [comment]
Hello, that's a fast answer.

- there are no errors in console
- data is generated from an sql result array with php's function json_encode - so I guess it is ok. It looks ok to me and the data is loaded as expected into the table.
- indexes are set and they are all unique, from 1 to ...
- Chrome 64 and Opera Windows 7 64, everything up to date, no filtering, running on development server

Here comes the constructor:

`$("#bestand").tabulator({
	
	selectableCheck:function(data, row){
		//data - data object for this row
		//row - jQuery element for this row
		
		return data.Online == 1; //only allow rows with an age greater than 50 to be selected.
	},	
	
	
    pagination:"local",
    paginationSize:20,	
	selectable:true,
	dateFormat:"dd.mm.yyyy",
    fitColumns:true,
    sortBy:'Bestellnummer', // when data is loaded into the table, sort it by name
    sorDir:'desc', //when data is loaded into the table, sort it in ascending order.	
	
    columns:[
	{title:"Bestnr.", field:"Bestellnummer", headerFilter:true, align:"left", sortable:true, sorter:"number", tooltipHeader:"Die Bestellnummer"},
	{title:"ISBN", field:"ISBN", sortable:false, headerFilter:true, align:"left", tooltipHeader:"Zugewiesene ISBN"},
		
	{title:"Typ", field:"Typ", headerFilter:function(cell, value, data){
			//cell - JQuery object for current cell
			//value - the current value for current cell
			//data - the data for the current row

			//create and style editor
			var editor = $("<?php print $gettypen; ?>");
			editor.css({
				"padding":"3px",
				"width":"100%",
				"box-sizing":"border-box",
			})

			//Set value of editor to the current value of the cell
			editor.val(value);

			//set focus on the select box when the editor is selected (timeout allows for editor to be added to DOM)
			if(cell.hasClass("tabulator-cell")){ //check to make sure this editor isnt being used as a header filter
				setTimeout(function(){
					editor.focus();
				},100);
			}

			//when the value has been set, trigger the cell to update
			editor.on("change blur", function(e){
				cell.trigger("editval", editor.val());
			});

			//return the editor element
			return editor;
		},
	},

	{title:"Imprint", minWidth:140, field:"Imprint", headerFilter:function(cell, value, data){
			//cell - JQuery object for current cell
			//value - the current value for current cell
			//data - the data for the current row

			//create and style editor
			var editor = $("<?php print $getimprints; ?>");
			editor.css({
				"padding":"3px",
				"width":"100%",
				"box-sizing":"border-box",
			})

			//Set value of editor to the current value of the cell
			editor.val(value);

			//set focus on the select box when the editor is selected (timeout allows for editor to be added to DOM)
			if(cell.hasClass("tabulator-cell")){ //check to make sure this editor isnt being used as a header filter
				setTimeout(function(){
					editor.focus();
				},100);
			}

			//when the value has been set, trigger the cell to update
			editor.on("change blur", function(e){
				cell.trigger("editval", editor.val());
			});

			//return the editor element
			return editor;
		},
	},

	{title:"Serie", field:"Serie", headerFilter:function(cell, value, data){
			//cell - JQuery object for current cell
			//value - the current value for current cell
			//data - the data for the current row

			//create and style editor
			var editor = $("<?php print $getserien; ?>");
			editor.css({
				"padding":"3px",
				"width":"100%",
				"box-sizing":"border-box",
			})

			//Set value of editor to the current value of the cell
			editor.val(value);

			//set focus on the select box when the editor is selected (timeout allows for editor to be added to DOM)
			if(cell.hasClass("tabulator-cell")){ //check to make sure this editor isnt being used as a header filter
				setTimeout(function(){
					editor.focus();
				},100);
			}

			//when the value has been set, trigger the cell to update
			editor.on("change blur", function(e){
				cell.trigger("editval", editor.val());
			});

			//return the editor element
			return editor;
		},
	},
        
		{title:"Autor", field:"Autor", minWidth:200, headerFilter:true, sorter:"string"},
		{title:"Titel (intern)", minWidth:200, field:"TitelIntern", headerFilter:true, sorter:"string"},
		{title:"Erstauflage", field:"Erstauflage", align:"center", sorter:"date", headerFilter:true, tooltipHeader:"Erstauflage"},
        {title:"Seiten", field:"Seitenzahl", headerFilter:false, align:"left", sortable:true, sorter:"number", tooltipHeader:"Anzahl PDF-Seiten"},
		
		
		
		
		
		{title:"Preis", field:"Europreis", align:"center", sorter:"number", headerFilter:function(cell, value, data){
				//cell - JQuery object for current cell
				//value - the current value for current cell
				//data - the data for the current row

				//create and style editor
				var editor = $("<?php print $getpreise; ?>");
				editor.css({
					"padding":"3px",
					"width":"100%",
					"box-sizing":"border-box",
				})

				//Set value of editor to the current value of the cell
				editor.val(value);

				//set focus on the select box when the editor is selected (timeout allows for editor to be added to DOM)
				if(cell.hasClass("tabulator-cell")){ //check to make sure this editor isnt being used as a header filter
					setTimeout(function(){
						editor.focus();
					},100);
				}

				//when the value has been set, trigger the cell to update
				editor.on("change blur", function(e){
					cell.trigger("editval", editor.val());
				});

				//return the editor element
				return editor;
			}, formatter:function(value, data, cell, row, options, formatterParams){
            return value.replace('.', ',') + " €";
			}, tooltipHeader:"Ladenpreis inkl. Steuern."
		},		
		
		

		{title:"Fehler", field:"Fehler", sorter:"string"},
        {title:"Online", field:"Online", align:"center", sorter:"boolean", formatter:"tick", headerFilter:true},
        
        
    ],
});`

**Comment by 1manfactory** [comment]
Hello.
I found the error myself. It was my mistake
I used
```
var selectedData = $("#bestand").tabulator("getSelectedData");
var filteredData = $("#bestand").tabulator("getData", true);
```
which only works for the initial load of the page and does not work when data is loaded afterwards.

So I  simply had to build two functions around it.

```
function get_selected_data() {
	return $("#xxx").tabulator("getSelectedData");
}

function get_filtered_data() {
	return $("#xxx").tabulator("getData", true);
}
```
