### ISSUE TITLE
Rows per page should not include grouping and totals

### ISSUE THREAD

**Issue by HenrikBP** [olifolkerd/tabulator#1955]
We are using pagination on a table where the rows are grouped and there are rows with totals.
When specifying f.ex. 25 rows per page (using tabulator.setPageSize(25) ), this may mean that only 15 rows of actual data is displayed per page, the remaining 10 rows are used for the grouping and the totals.

**Describe the solution you'd like**
We'd like an option to specify if the specified number of rows per page should include grouping and totals.
When the option is enabled, tabulator.setPageSize(N) should mean that N rows of data will be displayed per page, even if this means that the total number of rows displayed is more than N, eg. N data rows + 3 grouping rows + 2 totals rows.

**Additional context**
We have been considering modifying Page.prototype.getRows() ourselves, but we feel it is better left to the experts...

**Comment by olifolkerd** [comment]
Hey @HenrikBP 

The pagination system is built to try and maintain a consistent height of the pages, therefor it counts group headers in the number.

I would argue that using a mix of grouping and pagination leads to a very poor user experience as there is no way for the user to see the groups ahead of time or not where they are likely to find group headers.

I would suggest that a cleaner solution would be to present them with a table of closed groups that they could open to explore their contents.

I do not intend to alter the default behaviour of the table in this instance as i feel it offers the most consistent experience.

That being said i can see your usage case and it could be useful under certain circumstances.

I would be happy to add it to the road map for investigation, but i will be honest that i have a lot of higher priority tasks to tackle at the moment so i wouldn't get round to it for a few releases.

You are welcome to submit a pull request if you want to add the feature faster, if you do there are a few notes:
- changes must be made on src not dist files
- this must be an option that can be set with a boolean in the constructor object options
- this must not be the default behaviour
- your change must work in all table configurations

Thanks for getting in touch

Cheers

Oli :)

**Comment by HenrikBP** [comment]
Hi - thanks for the reply.

I agree that the current default behaviour is the most consistent, but for us there are situations where we really need the suggested behaviour.

We might consider paying you to develop the solution, if that would be of interest.
