### ISSUE TITLE
Search box missing on mobile view at tabulator.com

### ISSUE THREAD

**Issue by YendorMc** [olifolkerd/tabulator#1956]
I cannot find the search box under the hamburger bar when looking at tabulator on a safari on an iPhone.  Can this be added or am I missing something?  Like to be able to search documentation away from desktop.

**Comment by olifolkerd** [comment]
Hey @YendorMc 

The search bar isnt available on the mobile version at the moment.

This will become available when i do the next website update in a month or two.

Cheers

Oli :)
