### ISSUE TITLE
Is there a way to disable movable column for a specific column ?

### ISSUE THREAD

**Issue by jmlolo** [olifolkerd/tabulator#1957]
Is there a way to disable movable column for a specific column when moveColumns is activated ?

**Comment by aklaver** [comment]
No and I'm not sure if that would even be possible as by action if you move one column you are moving the others.

**Comment by aklaver** [comment]
Replied without thinking:( There are frozen columns:
http://tabulator.info/docs/4.2/layout#frozen-column
Though that only applies to columns on the left and right of the table and they need to be contiguous.

**Comment by olifolkerd** [comment]
Hey @jmlolo 

@aklaver  is correct, you can freeze columns if they are on the edge of the table, but if you can move other columns then you can just swap them about thereby moving the "unmovable" column

Cheers

Oli :)
