### ISSUE TITLE
ajaxProgressiveLoad: fixed scroll size on the basis of total pages

### ISSUE THREAD

**Issue by parth55** [olifolkerd/tabulator#1958]
Hi,

How to achieve a fixed scroll from total no. of pages with ajaxProgressiveLoad:"scroll"?

More specifically in below configuration,
http://tabulator.info/examples/4.2#ajax-progressive

**Comment by aklaver** [comment]
Not exactly sure what you want but, set up pagination?:
http://tabulator.info/docs/4.2/data#ajax-progressive
"All the ususal pagination options, such as paginationSize, paginationDataSent etc can be used in this mode, you can find out more about the options and expected response in the Remote Pagination Documentation"

**Comment by parth55** [comment]
We know the no of pages, after first ajax call but height of scroll bar is varying(increasing) as we scroll down with each new ajax request, although we already know the total no of records (pages* no of records/page). User is not getting real idea of scrolling(how much to scroll and how many records are still left) even after all records have been loaded.

**Comment by aklaver** [comment]
You will need to show your table constructor. 

An example from my code:
![Screenshot-2019-4-4 Table - Tabulator](https://user-images.githubusercontent.com/658260/55574887-63d41b80-56c2-11e9-843e-9c0e9a7a88dc.png)
![Screenshot-2019-4-4 Table - Tabulator(1)](https://user-images.githubusercontent.com/658260/55574896-6898cf80-56c2-11e9-8d2a-6e780da330a9.png)

**Comment by aklaver** [comment]
And the relevant constructor bits:
`
ajaxProgressiveLoad: "scroll",
pagination: "remote",
paginationSize: 12,
`

**Comment by parth55** [comment]
Hi,

below is my code 
```

this.tabulator = new Tabulator("#example", {
       // ajaxParams:{last_page:_this.iTotalPage, paginationSize: this.iRowsPerPage},
       ajaxURL: "/tableData",
       ajaxURLGenerator:function(url, config, params){
         params.last_page = _this.iTotalPage;
         params.paginationSize = this.iRowsPerPage;       
         return url + "?params=" + encodeURI(JSON.stringify(params));
     },
       autoColumns:true,
       height:"500px",
       movableColumns: true,
       ajaxProgressiveLoad:"scroll",
       paginationSize: this.iRowsPerPage,
       ajaxProgressiveLoadScrollMargin: 400,
       ajaxLoader: true,
       ajaxLoaderLoading: 'updating data',
       ajaxProgressiveLoadDelay: 200,
       dataFiltering:function(filters){
     
       },
       ajaxResponse:function(url, params, response){
         if(!_this.aColumns.length){
           _this.aColumns =  Object.keys(response.data[0]);            
         }
         _this.iTotalPage = response.last_page;          
         return response;
       }
     });
```

and it's working exactly as shown in documentation http://tabulator.info/examples/4.2#ajax-progressive
 (including variable scroll bar size)

**Comment by aklaver** [comment]
All I can think of is to use:
http://tabulator.info/docs/4.2/format#format
"Row Number
The rownum formatter shows an incrementing row number for each row as it is displayed"

in the table and use _this.iTotalPage x this.iRowsPerPage to get total row count that you display to help the user determine where they are in the dataset.

**Comment by parth55** [comment]
Hi, 
I got your idea a) showing row number with each row and b) showing the total number of rows somewhere in the page.

I agree that this will solve the confusion to some extent, however, my concern is, irrespective of new data fetched from the server, the total number of rendered rows will be fixed as we are using virtual DOM, then why scroll bar size (height) is increasing with scrolling?

**Comment by aklaver** [comment]
You say your table is operating the same as the example at the Tabulator. I do not see any change in height when using the example. That is testing with Firefox 60.6.1esr  and Chrome  73.0.3683.86 . You will need to provide a screenshot or a more detailed description of what you are seeing.

**Comment by olifolkerd** [comment]
If you are using pagination you should not set a height on the table, then the table will resize to fit the number of rows and there will be no scroll bar

**Comment by parth55** [comment]
> If you are using pagination you should not set a height on the table, then the table will resize to fit the number of rows and there will be no scroll bar

Thanks! but I am not using pagination.

> You say your table is operating the same as the example at the Tabulator. I do not see any change in height when using the example. That is testing with Firefox 60.6.1esr and Chrome 73.0.3683.86 . You will need to provide a screenshot or a more detailed description of what you are seeing.

![image](https://user-images.githubusercontent.com/14799110/55703829-4ff92400-59f8-11e9-883e-cdf395038e15.png)


![image](https://user-images.githubusercontent.com/14799110/55703953-a49c9f00-59f8-11e9-88f4-a65fce2c5101.png)

**Comment by aklaver** [comment]
@parth55 
Alright I see what you are talking about. From what I see the scroll marker starts at  a size and after scrolling is changed to a smaller size  and stays that way(going up or down) until the table is refreshed. It is less noticeable on FF which is what I use day-to-day and is why I did not pick up on it, that and old eyes:) For me it is not really something I would consider a worry.

**Comment by olifolkerd** [comment]
@parth55 Thanks for the visuals, i understand what you are talking about.

Given that the scroll size and position of the scroll bar is set by the number of rows in the table, it will naturally change as you scroll and new lines are added to the table (shrinking the scroll bar and pushing it slightly up).

It should only be slightly jumpy and it should have no effect on the actual scroll position of the table.

There is not much that can be done to fix this as the exact number of rows in the table are not known at any point.

I use this all the time and i cant say it has caused any issues with my users.

Thanks for the feedback

Oli :)

**Comment by parth55** [comment]
no of rows =  last_page * no of rows per page

It's not causing any issue UI wise but users are not getting the idea that when actually all records have been loaded to the table and there are no more new records to load via scroll.

**Comment by olifolkerd** [comment]
It's not that simple I'm afraid, that only gives a rough approximation of the number of rows, as there could be anywhere between 1 and the page size number of rows on that final page.

I understand where you are coming from, and I am happy to stick the idea on the roadmap, but I will be honest with you, I am unlikely to get round to looking at it for a few releases as I have more pressing issues to deal with and no other user has considered it an issue.

Cheers

Oli :)

**Comment by parth55** [comment]
> @parth55
> 
> I am not following. When the scroll bar hits bottom there are no new records or are you seeing something different.

You are right that when scroll bar hits bottom, ideally there is no new record loading in the background. But in my case, I have more than 1 Lakh records and sometimes server delay is also there. Hence, It's a bit confusing.

**Comment by aklaver** [comment]
Seems to me you would be better served using remote pagination.
