### ISSUE TITLE
selectableCheck does not prevent selection

### ISSUE THREAD

**Issue by 1manfactory** [olifolkerd/tabulator#196]
I tried

```
selectableCheck:function(data, row){
	return data.Online == 1;
},
```

To only make online elements selectable. This only works partly. Mouse over effects do not work for the not "online" rows. But I can still click them and select them. And also tabulator("getSelectedData") is filled with it.

I am using the latest Chrome Browser on Windows 7 64

**Comment by olifolkerd** [comment]
Hey,

I cant seem to replicate your issue. Could you post a copy of your Tabulator constructor and a sample of your data with a couple of selectable and unselectable rows so i can setup a test that matches yours.

Cheers

Oli

**Comment by 1manfactory** [comment]
I was able to handle this.
I had two similar selectableCheck functions  (guess too much Copy &Paste) inside the constructor, one at the beginning and one at the end. And I guess both knockes each other out.

**Comment by olifolkerd** [comment]
Ahh yes, that could lead to some strange behaviour.

Cheers

Oli
