### ISSUE TITLE
Wrong display of first column of dataTree after editing

### ISSUE THREAD

**Issue by dvopalecky** [olifolkerd/tabulator#1962]
**Describe the bug**
When using the dataTree, and when the first column is editable, after edit the display of the tree structure is lost if it's not the root node of the tree.

**Tabulator Info**
Tabulator 4.2.4

**Working Example**
https://codepen.io/dannyvop/pen/BELZXj

**To Reproduce**
1. Go to https://codepen.io/dannyvop/pen/BELZXj
2. Click on cell 'Adam' or 'Peter', edit it and click Enter

**Expected behavior**
The tree structure icons (square and branch icons) should be kept even if I edit the text.

**Screenshots**
Original
<img width="206" alt="Screen Shot 2019-04-07 at 22 42 49" src="https://user-images.githubusercontent.com/22667578/55689590-81390c00-5986-11e9-9c79-35b2c47c3fcd.png">

After first edit
<img width="204" alt="Screen Shot 2019-04-07 at 22 42 21" src="https://user-images.githubusercontent.com/22667578/55689592-81390c00-5986-11e9-844a-b75528868d55.png">

After second edit
<img width="211" alt="Screen Shot 2019-04-07 at 22 42 33" src="https://user-images.githubusercontent.com/22667578/55689591-81390c00-5986-11e9-955a-e09980875a87.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.14.4
 - Browser: Chrome 73.0.3683.86 (Official Build) (64-bit)

**Comment by aklaver** [comment]
You need to update the _children array:

https://github.com/olifolkerd/tabulator/issues/1603

or as of 4.2.2:
https://github.com/olifolkerd/tabulator/releases
"In data tree mode allow a single row object to be passed directly to the _children property instead of being passed in an array"
