### ISSUE TITLE
header filter not works properly

### ISSUE THREAD

**Issue by pptsk** [olifolkerd/tabulator#1963]
Hi,
my header filter ofcourse does not works if my numeric data are converted to text,
can someone help how to set filter for this job??

> 
				{title:"Access (1-16)", field:"access", headerFilter:"input", width:'140',
					formatter:function(cell, formatterParams){
						var value = cell.getValue();
						var result = "";
						for(var i = 0; i < 16; i++){ 
							result+= ( value & (1 << i )) === 0 ? "0" : "1";                              // get value of each bite from value (16 digits)
						}
						return "<span style='color:blue; font-weight:bold;'>" + result + "</span>";						
					},
				},

> 
thank you
pptsk

**Comment by olifolkerd** [comment]
cast the input value to a number using ***Number***:

```js
var value = Number(cell.getValue() || 0);
```

I hope that helps,

Cheers

Oli :)

**Comment by pptsk** [comment]
Ho Oli,
I have tried your solution but from some reason does not works.
Access data are converted to binnary for better orientation.
example before filter:
![1](https://user-images.githubusercontent.com/9829483/55774267-b9c70b80-5a94-11e9-9242-e6d9135ad739.PNG)
 and this is result:
![2](https://user-images.githubusercontent.com/9829483/55774325-f0048b00-5a94-11e9-8236-f9dc85bab696.PNG)
data comes in json format:

> var esp_data = [
	{ "name": "Stefan Adamcok","card": "4789","access": 1},
	{ "name": "Miroslav Hurajt","card": "4789","access": 1},
	{ "name": "Peter Pinka" ,"card": "188dabf","access": 0},
	{ "name": "Ivan Sykora","card": "45ea87a","access": 401},
	{ "name": "Dusan Sloboda","card": "eddaf34","access": 296},
	{ "name": "Vlado Kascak","card": "547890d","access": 65535},
	{ "name": "Jan Golian","card": "aa78f5c6","access": 964},
	{ "name": "Stano Oravec","card": "4875215","access": 784},
	{ "name": "Jan Hanak","card": "d7854125","access": 1524},
]

> 
amn main part of the table>

> var table = new Tabulator("#example-table", {
				data: local_data,	
				pagination:"local",
				paginationSize:9,
				addRowPos:"top",
				layout:"fitColumns",
				placeholder:"No Data Available",			
                rowFormatter:function(row){ 
					var row_data = row.getData();
                    var a = row_data.access;
					var color = row_data.col;
					console.log("color: " + color);
                    if(a == 0 ){                                                                         // if user has no access make row red
						row.getElement().style.backgroundColor = "#ff9999";
					}	
					else if(a == 65535 ){
						row.getElement().style.backgroundColor = "#b3ff99";                              // if user has full access make row green
					}
					else if(a > 0 ){
						row.getElement().style.backgroundColor = "#F9F9F9";                              // if user has nor full or any access make row gray
					}
					console.log("acces value= " + a);
				},							
				index:"id",
				
				initialSort:[                                                                            // Define the sort order:
				{column:"id", dir:"asc"},     
				],
				
				columns:[			
				{title:"#", field:"id", align:"center", width:'50', topCalc:"count"},
				{title:"Name", field:"name", headerFilter:"input"},
				{title:"Card ID", field:"card", headerFilter:"input"},
				{title:"Access (1-16)", field:"access", headerFilter:"input", width:'140',
					formatter:function(cell, formatterParams){
						var value = cell.getValue();
						var result = "";
						for(var i = 0; i < 16; i++){ 
							result+= ( value & (1 << i )) === 0 ? "0" : "1";                              // get value of each bite from value (16 digits)
						}
						return "<span style='color:blue; font-weight:bold;'>" + result + "</span>";						
					},
				},
							

> 
can you please help what I am doing wrong?
thank you
pptsk

**Comment by olifolkerd** [comment]
@pptsk 

Sorry i think i missunderstood you there, my first comment was related to the formatter which is completely unrelated to your comment.

Could you explain what column you are trying to filter, what the behaviour you want is and what is actually happening?

Cheers

Oli :)

**Comment by pptsk** [comment]
Hi Oli,
Thank you for response!
I want to filter column access. 
I converted each value from json source to binnary format for easiest view of access rights of each user.
Now I want to filter users according their access rights in binnary(16 bites = 16 floors ), see previous pictures.
As you can see at second picture  I started filtering with value 100 so there should be 3 users(nr 1,2 and 4) with access starting 100xxxxxxxxxxxxx but result is empty.
Thank you!
pptsk

**Comment by olifolkerd** [comment]
The issue is because the data is still stored as a number. Formatters are purely visual they have no effect on the data, so sorters and filters aren't affected by them.

If you want it to affect filters you need to look at using a mutator to alter the underlying data.

**Comment by pptsk** [comment]
Hi Oli,
Thank you for tip.
I have last question-
As you can see I am changing row color
```
if(a == 0 ){ // if user has no access make row red
   row.getElement().style.backgroundColor = "#ff9999";
}
```
but I dont know how to set row color back to default.
Can you help?
pptsk

**Comment by olifolkerd** [comment]
To remove a style, pass an enpty string to the property:
```js
row.getElement().style.backgroundColor = "";
```

**Comment by pptsk** [comment]
Hi Oli,
Thank you so much!!!
All works fine now.
Is it possible to make row with custom color highlighted on hover ?

**Comment by olifolkerd** [comment]
If you want to do that you would need to do it by adding classes to the row that define that behaviour as you can add hover behaviours with javascript

**Comment by pptsk** [comment]
Hi Oli,
I meant the same behaviour with mouse cursor over row, like on default table but with custom color...
