### ISSUE TITLE
My table is not loading properly whenever i am refreshing browser. Only half table is loading in view.

### ISSUE THREAD

**Issue by aswinkumar007** [olifolkerd/tabulator#1964]
Hi oli,

Good Day...!

Actually, I am new to Angular js. I am making use of tabulator plugin in my project. My concern is whenever i am trying to refresh my page, only half the table is loading in my  view.
 
I tried to fix it but i can't able to fix the issue.

![error screen](https://user-images.githubusercontent.com/49431736/55794857-071e9980-5ae4-11e9-95ed-c385a91c73e1.PNG)
![expected screen](https://user-images.githubusercontent.com/49431736/55794865-0e45a780-5ae4-11e9-9142-cbec88d1ed6f.PNG)

==============================================================
My HTML Code

<div id="example-table"></div>

==============================================================
My JavaScript Code
app.controller('Accrued_Interest_Ctrl', function ($scope, $http, $window, myFactory, $route) {

angular.element(document).ready(function () {

         $scope.urlforcalling = myFactory.getUrl();

        var table = new Tabulator("#example-table", {
            headerFilterPlaceholder:"search",
            layout:"fitDataFill",
            height:"311px",
            resizableColumns:false,
            selectable:false,
            placeholder:"No Data Available",

            initialSort:[             
                                    {column:"executionDate", dir:"dsc"},
                                ],
            columns:[
            {title:"Sl.No", formatter:"rownum",align:"right",headerSort:false },
            {title:"Circle", field:"circleName", align:"left", headerFilter:true},
            {title:"Network", field:"network",align:"left", headerFilter:true},
            {title:"Module", field:"module", align:"left", headerFilter:true },
            {title:"Region", field:"region",align:"left", headerFilter:true},
            {title:"Branch Name", field:"branchName",align:"left", headerFilter:true},
            {title:"Branch Code", field:"branchCode",align:"right", headerFilter:true},
            {title:"Account Name", field:"dealerName",align:"left", headerFilter:true},
            {title:"Account Number", field:"accountNumber",align:"right", headerFilter:true},
            {title:"SCFU Outstanding", field:"outStandingSCFU",align:"right",formatter:"money", headerFilter:true},
            {title:"CBS Outstanding", field:"outstandingCore",align:"right",formatter:"money", headerFilter:true},
            {title:"Since Date", field:"executionDate",align:"right", headerFilter:true},
            ],
        });

        var data1 = {role : $scope.mainScopeVariables1.userRole, requestDate: $scope.datefrompicker2};

        $scope.loading = true;

        var request = {
                method: 'post',
                url: $scope.urlforcalling + '/accintzero',

                contentType: 'application/json',
                data: JSON.stringify(data1)             
            };

            $http(request)
                .success(function (jsonData) {
                    $scope.pro = jsonData;     [error screen][1]
                    var myJSON = JSON.stringify($scope.pro);
                    table.setData(myJSON);
                    $scope.loading = false;

                })
                .error(function () { $window.alert('error in calling recondetailed method ');
                $scope.loading = false;
                }); 

}
})

**Comment by aklaver** [comment]
1)  I am not certain what the conditions are for the first and second screenshots. 

2)  In second screenshot there is field title 'CC Limit' which does not show up in your table code, so are we looking at the same thing? 

3)  At any rate "fitDataFill" will try to fill the table horizontally, spacing on the data values, until it runs out of horizontal space in the container at which point a scroll bar will appear to allow reaching the columns on the right. Where you expecting different behavior?

**Comment by aswinkumar007** [comment]
Thank you for your quick response. :-)

1. My first screenshot is the error screen which i am getting whenever i am refreshing the browser, only half table is showing in view without scrollbar. 

2. My second screenshot is the expected screen.(correct one)

3. I am using "fitDataFill", even though my table is not loading properly.

**Comment by aklaver** [comment]
Does it behave better with "fitColumns"?
I am just not sure of what happens when there is no actual data for fitData* to work on?
Have you looked at what is returned by the request when you initially load the data and when you refresh the page?
Also how are you refreshing?
Have you looked at:
http://tabulator.info/docs/4.2/frameworks#angular
Have you looked at
