### ISSUE TITLE
vertical alignments for text inside cells and header

### ISSUE THREAD

**Issue by lalitapatil1993** [olifolkerd/tabulator#1967]
Describe the bug:
While doing vertical text alignment as top bottom and middle for cells and header.
Tabulator not allow me to set display property  as table-cell or inline. because of that property table get distorted. Thats why i am not able to do vertical alignment of the cells and header.
Please help me for this issue.

Tabulator Info
- Which version of Tabulator are you using- 4.1

Expected behavior
Need to allow different display properties without distortion of table UI.
because for vertical-align css property i need table-cell or inline as a display property.

Desktop (please complete the following information):
 - OS: windows
 - Browser:chrome

**Comment by olifolkerd** [comment]
@lalitapatil1993 

Im afraid you cant just alter the display property of elements in the table, these are set for a very specific reason that they are needed for the table to function correctly.

there is already the ***columnVertAlign*** table option that lets you set whether headers should be aligned to "top" "middle" and "bottom"

```js
var table = new Tabulator("#example-table", {
    columnVertAlign:"bottom", //align header contents to bottom of cell
});
```
Cheers

Oli :)

**Comment by lalitapatil1993** [comment]
Hi,
I think you misunderstood my question. I want vertical alignments for header text and cells text also. And your solution is only for header text.

Thanks,
Lalita

**Comment by JaldhiR** [comment]
Description:

As a user when I want to do the vertical text alignment as top bottom and middle for cells inside the table and header.
Tabulator not allow me to set display property as table-cell or inline. because of that property table get distorted. Please help me for this issue.

Tabulator Info
Which version of Tabulator are you using- 4.1

**Comment by olifolkerd** [comment]
Hey @JaldhiR 

Yes you are correct, the ***.tabulator-cell*** element MUST have its display set as inline-block in order for the table to function correctly, you cannot expect to be able to alter the core display properties of a system and have it still render as expected, they inherently define its function.

In your case i would suggest that you use a custom formatter to insert a new div inside the .tabulator-cell, absolutely position it withing the cell with top,bottom,left and right set to 0 and then put your own styles on that element and put your content inside it.

Information on using custom formatters can be found in the [Formatter Documentation](http://tabulator.info/docs/4.2/format#format-custom)
 
I hope that helps.

Cheers

Oli :)
