### ISSUE TITLE
Star Formatter Not Working in collapse responsiveLayout Mode

### ISSUE THREAD

**Issue by fingers10** [olifolkerd/tabulator#1969]
Dear Tabulator Team,

I'm using Tabulator v4.2.5 and chrome browser.

I'm using a star formatter which works perfectly in normal layout. But breaks in `responsiveLayout: collapse`.

**Here is the screenshot:**

**Normal Layout:**
![image](https://user-images.githubusercontent.com/43729469/55875426-eee16580-5b49-11e9-81d0-a8c25f6fdfda.png)

**Collapsed Layout:**
![image](https://user-images.githubusercontent.com/43729469/55875197-4f23d780-5b49-11e9-8f2d-a1f0d283e559.png)

Instead of stars, `[object HTMLSpanElement]` is displayed.

Please assist.

Thanks,
Abdul

**Comment by aklaver** [comment]
I'm going to say it is similar to:
http://tabulator.info/docs/4.2/layout#responsive
"Collapsed List Column Formatting

By default any formatter set on the column is applied to the value that will appear in the list. while this works for most formatters it can cause issues with the progress formatter which relies on being inside a cell."

Might try:
If you would like to disable column formatting in the collapsed list, you can use the responsiveLayoutCollapseUseFormatters option:

var table = new Tabulator("#example-table", {
    responsiveLayoutCollapseUseFormatters:false,
});

**Comment by olifolkerd** [comment]
i will have a look into that, but @aklaver is correct it will be the same issue facing the progress bar

**Comment by olifolkerd** [comment]
It turns out there was an issue with the collapse system handling formatters that output DOM Nodes instead of text strings,

I have pushed a fix for this to the master branch and will include it in this weekends patch release.

Cheers

Oli :)
