### ISSUE TITLE
Link to Firebase Database

### ISSUE THREAD

**Issue by ihmunro** [olifolkerd/tabulator#197]
Afternoon

Is there a way to have the tables setup with a link to a firebase database for realtime table updates ?

Iain

**Comment by olifolkerd** [comment]
Hey, 

Thanks for getting in touch. I havnt used firebase myself but looking through the guide i cant see it being a problem.

How you use the system would depend on the data structures you set up in firebase. In this example i am going to assume that you are using a ***posts*** object that contains a series of post objects that you want to list in your table. in this example we will trigger a complete reload of data into the table any time a row changes. in reality you probably want to add a listener to each of the objects in your posts object and trigger an ***updateRow*** function for that row on a change, which will be more efficient than redrawing the table each time.

As a rough guide you could do something like the following (this code wont work directly, but should point you in the right direction when you have setup your credentials etc)

**Initialize the SDK**
```js
 var config = {
    apiKey: "apiKey",
    authDomain: "projectId.firebaseapp.com",
    databaseURL: "https://databaseName.firebaseio.com",
    storageBucket: "bucket.appspot.com"
  };
  firebase.initializeApp(config);

  // Get a reference to the database service
  var database = firebase.database();
```
**Define your Tabulator:**
```js
$("#example-table").tabulator({
    columns:[
        {title:"Name", field:"name", sorter:"string"},
        {title:"Title", field:"title", sorter:"string"},
    ],
});
```

**Fill your Tabulator and watch for changes:**
```js
//get database reference
var postsRef = database().ref('posts');

//trigger reload of database on update
postsRef.on('value', function(data) {
 
  //convert objects to array of objects that Tabulator can read
  var dataArray = [];

  for(var id in data){
    //set index on post object
    data[id].id = id;
    
    //add post object to data array
    dataArray.push(data[id]);
  }
  
  //set the data in the table
  $("#example-table").tabulator("setData", dataArray);
});
```

That should give you a rough idea of how to get started.

Give me a shout if you need any more help

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey Iain,

Did this answer your query?

**Comment by ihmunro** [comment]
That's Great Oli

I a man working through it. 

Once I get something working I will let you know. 

Thanks for the plugin. 

Iain

**Comment by ihmunro** [comment]
Hi Oli

Just wanted to let you know, I have it all working - very slick

Many thanks for your work.

Iain

**Comment by borderstep** [comment]
> Hey,
> 
> Thanks for getting in touch. I havnt used firebase myself but looking through the guide i cant see it being a problem.
> 
> How you use the system would depend on the data structures you set up in firebase. In this example i am going to assume that you are using a _**posts**_ object that contains a series of post objects that you want to list in your table. in this example we will trigger a complete reload of data into the table any time a row changes. in reality you probably want to add a listener to each of the objects in your posts object and trigger an _**updateRow**_ function for that row on a change, which will be more efficient than redrawing the table each time.
> 
> As a rough guide you could do something like the following (this code wont work directly, but should point you in the right direction when you have setup your credentials etc)
> 
> **Initialize the SDK**
> 
> ```js
>  var config = {
>     apiKey: "apiKey",
>     authDomain: "projectId.firebaseapp.com",
>     databaseURL: "https://databaseName.firebaseio.com",
>     storageBucket: "bucket.appspot.com"
>   };
>   firebase.initializeApp(config);
> 
>   // Get a reference to the database service
>   var database = firebase.database();
> ```
> 
> **Define your Tabulator:**
> 
> ```js
> $("#example-table").tabulator({
>     columns:[
>         {title:"Name", field:"name", sorter:"string"},
>         {title:"Title", field:"title", sorter:"string"},
>     ],
> });
> ```
> 
> **Fill your Tabulator and watch for changes:**
> 
> ```js
> //get database reference
> var postsRef = database().ref('posts');
> 
> //trigger reload of database on update
> postsRef.on('value', function(data) {
>  
>   //convert objects to array of objects that Tabulator can read
>   var dataArray = [];
> 
>   for(var id in data){
>     //set index on post object
>     data[id].id = id;
>     
>     //add post object to data array
>     dataArray.push(data[id]);
>   }
>   
>   //set the data in the table
>   $("#example-table").tabulator("setData", dataArray);
> });
> ```
> 
> That should give you a rough idea of how to get started.
> 
> Give me a shout if you need any more help
> 
> Cheers
> 
> Oli :)

Hi Oli,

Tabulator is great!

What could be the reason that this doesn't work on a fresh install of Tabulator? Is this from a previous version?
I, too, am trying to set up Tabulator to display data from firebase but get "Uncaught TypeError: $(...).tabulator is not a function"

Any ideas would be greatly appreciated.

**Comment by olifolkerd** [comment]
Hey @borderstep 

That is because the example above is using the jQuery wrapper.

if you are not using jQuery then you define your table using:
```js
var table = new Tabulator("#example-table", {
    columns:[
        {title:"Name", field:"name", sorter:"string"},
        {title:"Title", field:"title", sorter:"string"},
    ],
});
```
then set your data using:
```js
table.setData(dataArray);
```

I hope that helps,

Cheers

Oli :)

**Comment by rumblersull** [comment]
Hello, I followed all these steps but am getting the following error and have no idea how to fix it - any ideas? - 
ReferenceError: document is not defined
>      at TabulatorFull.initializeElement (/home/functions/node_modules/tabulator-tables/dist/js/tabulator.js:7758:20)
>      at new Tabulator (/home/functions/node_modules/tabulator-tables/dist/js/tabulator.js:7740:12)
>      at new TabulatorFull

**Comment by rumblersull** [comment]
Ok I finally solved this by just putting all the javascript for tabulator and generating the table elements dynamically in the html file. Was not able to generate the tabulator table from the separate js file.
