### ISSUE TITLE
Dynamically sized table with maximum height

### ISSUE THREAD

**Issue by takuy** [olifolkerd/tabulator#1972]
**Is your feature request related to a problem? Please describe.**
I have a table that may contain anywhere between 1 row to 500 rows. At around 250px, a table with one row leaves a lot of empty space. Setting the table height to 'auto' is fine with a low amount of rows, but is insane for anything over 10. 

Obviously, I'd like to use the virtual DOM features for peak efficiency when using a lot of rows. 

I tried setting this: `max-height: 250px; height: auto;` set on the table's style - my hope was that, the table would grow with each row (like with auto) until it reaches 250px, and then go into Virtual DOM mode and have a scrollbar.

With the CSS-based solution, I'm not sure if it enters Virtual DOM mode - but the scrollbar definitely doesn't appear. The overflow just gets cut off. 

**Describe the solution you'd like**
I'd like for the table to be able to grow with it's contents until it hits a defined maximum and doesn't grow beyond that point. 

I'm not sure how this syntax could work from the table options object perspective?
```js
new Tabulator("...", {
   height: "auto",
   max-height: "500"
// or
   height: [500, "auto"],
});
```
**Describe alternatives you've considered**
The CSS method described above.

**Comment by Rodbjartson** [comment]
I think this is a great suggestion, not sure if it can be implemented though. Let us see what Oli thinks.

**Comment by olifolkerd** [comment]
Hey @takuy 

Thanks for the suggestion, i think that is a great idea, it could be tricky to make it switch between the two render modes while the table is in use, but im up for giving it a go.

I will stick it on the road map

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @takuy 

I have pushed an update to the 4.6 branch that allows the table to take a max-height set on the table element into account so that you get the scrollbar instead of it overflowing.

```js
var table = new Tabulator("#example-table", {
    maxHeight:"100%", //do not let table get bigger than the height of its parent element
});
```

This will be released in a few weeks time.

Cheers

Oli :)

**Comment by antman3351** [comment]
Hello,

I also have the need (not really a need, more a nice to have) to dynamically size the table until a max-height while still using the virtual DOM (The `maxHeight` doesn't use virtual DOM or am I doing something wrong?, v.4.9). 

In my case I have HTML before and/or after the table, so a table only showing a few rows with a fixed height that allows for "lots" of rows will leave a white space.

Here's what I came up with, Instead of growing the table I shrink it once it's been initialized. Obviously if the data is changed the table height will have to be reset. 

```JS
const tabulator = new Tabulator("#example-table", {
   height:"80vh", 
   renderComplete: function ()
                        {
                            const tabulator = this;
                            const table = tabulator.element;
                            const rowsContainer = table.querySelector( '.tabulator-tableHolder' );

                            if (
                                table.clientHeight === 0 || // Table is hidden we can't calculate the height
                                rowsContainer.scrollHeight > rowsContainer.clientHeight  // Scroll bar is present, leave height as is
                            )
                            {
                                console.log( table.clientHeight === 0 ? 'Table not visible' : 'No need to shrink' );
                                return;
                            }

                            const height = table.querySelector( '.tabulator-header' ).clientHeight +
                                table.querySelector( '.tabulator-table' ).clientHeight +
                                2; /* Add a "buffer"*/

                            console.log( `Shrinking table to ${height}px` );

                            tabulator.setHeight( `${height}px` );
                        }
});

```
