### ISSUE TITLE
Automatically setup `autoColumns` if there is no `columns` defined

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#1976]
Than you Oli for so nice Tabulator #1043. I would like to see next feature

**Is your feature request related to a problem? Please describe.**
I have this code snippet
```
	var opts =  {
		height      : 600,
		autoColumns : !obj.columns,
	};
	if( obj.columns ) {
		opts.columns =  obj.columns;
	}
	new Tabulator( '#id', opts );      
```

It seems excess to setup `autoColumns` manually if there is no `columns` defined.

Also next code fail because of `columns` is null
```
	var opts =  {
		height      : 600,
		autoColumns : !obj.columns,
		columns: obj.columns,
	};
```

**Describe the solution you'd like**
It would be nice if Tabulator will do internally: `this.autoColumns = !this.columns`

**Comment by olifolkerd** [comment]
Hey @KES777 

Thanks for the feedback. but there are a few usage cases where users don't define columns to start with. 

When importing a table from and HTML table, you don't define the columns when you build the table.

Also a number of people work with tables where the column definition depends on user selections elsewhere on their site so they set the columns after initialising the table.

It is only setting one boolean property which isn't exactly tricky. so in this instance i wont be looking to add this to the codebase.

Thanks for the idea though.

Cheers

Oli :)
