### ISSUE TITLE
Ajax Promise function

### ISSUE THREAD

**Issue by pumppi** [olifolkerd/tabulator#1979]
**Is your feature request related to a problem? Please describe.**
Theres no any problems, but this would more dynamic way to implement other ajax/rest libraries like Loopback 3

**Describe the solution you'd like**
Simply in configuration there could be option. ajaxPromise = new Promise() ...etc
This way the catch could be show error dialog and in success presenting the data.
With this solution you could also implement paging component with REST-APIs

**Describe alternatives you've considered**
Hacking the code :) Implementing own Ajax module like this https://github.com/olifolkerd/tabulator/blob/master/src/js/modules/ajax.js 

**Additional context**
This looks better than datatables, good work 👍

**Comment by aklaver** [comment]
I don't entirely follow the above, but I wonder if the below would help or not?:

http://tabulator.info/docs/4.2/data#ajax-promise

**Comment by olifolkerd** [comment]
Hey @pumppi 

as @aklaver states, this is already available in the existing library.

Cheers

Oli :)
