### ISSUE TITLE
cell and can perform calculations.

### ISSUE THREAD

**Issue by yoyomule** [olifolkerd/tabulator#1981]
Great project. Can you consider supporting the reference to data in other locations in the cell and can perform calculations. The operation is like excel,  get the data by entering a formula. In addition, if cross-cell data entry is supported, is it possible to become a data filing and reporting system?Thanks

**Comment by aklaver** [comment]
My guess is that what you want is already possible, though to eliminate the assumptions:
Can you be more specific e.g show some examples of what you want?

**Comment by yoyomule** [comment]
Thanks,I recorded some cases.
![1](https://user-images.githubusercontent.com/10000818/56189985-dd252400-605b-11e9-9786-41102722a7c4.gif)
![2](https://user-images.githubusercontent.com/10000818/56189995-e0201480-605b-11e9-83aa-7ff3f415b046.gif)

**Comment by aklaver** [comment]
I got it now. In your original post you had:
"..reference to data in other locations in the cell.." 

That was actually supposed to be references to other cells in the table. 

From the screenshot above I gather you want to be able to do real time changes in a cell using something similar to the Row/Column notation in a spreadsheet, is that correct?

**Comment by yoyomule** [comment]
Yes, it is. And we hope that the value of this change can also be saved, so that it can be used for later data analysis.

**Comment by aklaver** [comment]
First the easy part, data can be saved in a cell and somewhere else e.g. database. That can be done by the row or per cell.
Replicating spreadsheet ad-hoc Row/Column formula building is not builtin to Tabulator AFAIK. To do that would probably require building a custom editor that hooked into cell components:
http://tabulator.info/docs/4.2/components#component-cell
Have not done that and honestly have no idea how to at this point.

**Comment by olifolkerd** [comment]
Hey @yoyomule 

You would need to build a custom editor to handle this at the moment.

Importantly Tabulator is NOT a spreadsheet library, it is an interactive table library and as such does not have full excel level functionality,

More cell based "spreadsheet" functionality will be coming in the version 5.0 release.

Cheers

Oli :)
