### ISSUE TITLE
Is there a way to set parent folder for Tabulator library?

### ISSUE THREAD

**Issue by bioscorpion** [olifolkerd/tabulator#1982]
I installed the download zip version of the Tabulator. I am getting an error "Tabulator is not defined" when I try to set the Tabulator library in previous directory. I have placed the Tabulator library in the previous directory to where the application lives.

I have tried to set the previous directory path in my application.

```
<link href="../tabulator-master/dist/css/tabulator.min.css" rel="stylesheet">
<script type="text/javascript" src="../tabulator-master/dist/js/tabulator.min.js"></script>
```

My application tree view:
```
/somelongserverpath/tabulator-master/
/somelongserverpath/MyApplicationUsingTabulator/
```

I am expecting this library to work, but I am getting an error "Tabulator is not defined" when I load the page.

This library works successfully when I place it in the application directory. But I need the library to be in the parent directory as I have other applications to build using this library.

I did post this question on StackOverFlow early last week: https://stackoverflow.com/questions/55616366/is-there-a-way-to-set-parent-folder-for-tabulator-library

**Comment by aklaver** [comment]
This would seem to depend on what your application/framework does to resolve URL references. Also possibly permission issues on the directory structure.  An answer is going to need more information:

1) Is this a framework or a custom built application?
2) Do you see errors in the debugging(network) console about loading the JS and CSS links?
3) Have you looked at the permissions on the directory tree to see if the application can access files in the parent?

**Comment by aklaver** [comment]
This would seem to depend on what your application/framework does to resolve URL references. Also possibly permission issues on the directory structure.  An answer is going to need more information:

1) Is this a framework or a custom built application?
2) Do you see errors in the debugging(network) console about loading the JS and CSS links?
3) Have you looked at the permissions on the directory tree to see if the application can access files in the parent?

**Comment by iAmVaeVictus** [comment]
Do you happen to be using PhpStorm/Webstorm? If so, it's a false flag. 

https://stackoverflow.com/questions/21987225/webstorm-cannot-resolve-directory

**Comment by bioscorpion** [comment]
@aklaver Here are the answers to your questions:
1. Custom Built Application.
2. Two Errors I See In The Console Are
          i. Uncaught SyntaxError: Unexpected token else tabulator.min.js:4 
          ii. Uncaught ReferenceError: Tabulator is not defined VM94 myapplicationname.php:24 
3. Yes I Did Set `tabulator-master` permissions and ownership correctly. I even tried setting permission to 777 but that did not work either. 

@iAmVaeVictus No I am not using any framework.

**Comment by aklaver** [comment]
Some suggestions and questions:
1) At least temporarily use tabulator.js to maybe get a more helpful traceback.

2) What if you use an absolute path instead of a relative path?

3) What do you specify when the library is in the application directory?

**Comment by bioscorpion** [comment]
@aklaver Here are the results of you last three suggestions and questions:
1. When I use tabulator.js I just get an error: Uncaught SyntaxError: Unexpected token ; tabulator.js:3310
This is the line 3310 in tabulator.js
`if (toGroup === fromGroup) {
				this._moveRowInArray(toGroup.rows, from, to, after);
			} else {`
I cannot tell much from this line. 
2. Yes I have tried that too and the same error appears.
3. `<link href="tabulator-master/dist/css/tabulator.min.css" rel="stylesheet">
    <script type="text/javascript" src="tabulator-master/dist/js/tabulator.min.js"></script>`

**Comment by aklaver** [comment]
Hmm.
Just because it has not been asked, what Tabulator version?

So it seems tabulator.js is being loaded regardless of which directory is being pointed at. It would be good to confirm this. In FireFox I use the Network tab in Tools --> Web Console to see if assets are being found and loaded.

Are the contents of the  tabulator-master/ directories the same in the application and parent directories?

So what is line 24 at:
Uncaught ReferenceError: Tabulator is not defined VM94 myapplicationname.php:24
doing?

**Comment by bioscorpion** [comment]
@aklaver I am using Tabulator version 4.2

I have attached a screenshot of the Firefox Network Web Console and it shows the tabulator loading.
`GEThttp://192.168.20.51/nsg/MySQLReports/community_outreach_territory_master_database_edit.php
[HTTP/1.1 200 OK 638ms]

GEThttp://192.168.20.51/nsg/tabulator-master/dist/css/tabulator.min.css
[HTTP/1.1 200 OK 0ms]

GEThttp://192.168.20.51/nsg/tabulator-master/dist/js/tabulator.min.js
[HTTP/1.1 200 OK 0ms]

Unknown property ‘user-select’.  Declaration dropped. tabulator.min.css:2:355
Error in parsing value for ‘display’.  Declaration dropped. tabulator.min.css:2:1880
Unknown pseudo-class or pseudo-element ‘-ms-clear’.  Ruleset ignored due to bad selector. tabulator.min.css:2:2738
Error in parsing value for ‘display’.  Declaration dropped. tabulator.min.css:2:3692
Error in parsing value for ‘display’.  Declaration dropped. tabulator.min.css:2:5487
Unknown property ‘user-select’.  Declaration dropped. tabulator.min.css:2:6588
Error in parsing value for ‘display’.  Declaration dropped. tabulator.min.css:2:8231
Error in parsing value for ‘display’.  Declaration dropped. tabulator.min.css:2:11121
Error in parsing value for ‘display’.  Declaration dropped. tabulator.min.css:2:11891
Error in parsing value for ‘display’.  Declaration dropped. tabulator.min.css:2:13070
GEThttps://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js
[HTTP/2.0 200 OK 0ms]

GEThttp://192.168.20.51/favicon.ico`
![TabulatorLoadingFirefoxNetworkConsole](https://user-images.githubusercontent.com/48683345/56366567-0f986380-61b9-11e9-8f8d-65e49d3faa24.JPG)

Line 24 is the ajax code:
`// This callback is called any time a cell is deleted.
                            $.ajax({
                              url: ("cotmdb_ajax_response_request.php?action=delete"), //+ cell.getIndex()
                              data: cell.getRow().getData(), // sends this row record to $_REQUEST
                              type: "post",
                              success: function(response, textStatus, xhr){
                                //alert("AJAX cellClick del result: " + response + "; status: " + textStatus);
                              },
                              error: function(XMLHttpRequest, textStatus, error){
                                alert("AJAX cellClick error: " + textStatus + "; " + error);
                              }
                            })`

**Comment by aklaver** [comment]
I see from above that you are using jQuery, but not including the Tabulator jQuery wrapper:
http://tabulator.info/docs/4.2/jquery

See above for how to load. Not sure if that is problem, but loading it would eliminate a possibility.

**Comment by bioscorpion** [comment]
@aklaver I included the jQuery wrapper but that created another error:
`jquery_wrapper.min.js:2 Uncaught ReferenceError: jQuery is not defined
    at jquery_wrapper.min.js:2
    at jquery_wrapper.min.js:2
(anonymous) @ jquery_wrapper.min.js:2
(anonymous) @ jquery_wrapper.min.js:2
`

**Comment by aklaver** [comment]
Dependency issues:

http://tabulator.info/docs/4.2/jquery
"Dependencies

The jQuery wrapper is depedent on both the jQuery and jQuery UI libraries, you must have both included in your project before you include Tabulator and the wrapper in your code."
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by bioscorpion** [comment]
@aklaver Yes I have both in there:
`<script type="text/javascript" src="../tabulator-master/dist/js/tabulator.min.js"></script>
<script type="text/javascript" src="../tabulator-master/dist/js/jquery_wrapper.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
`

**Comment by bioscorpion** [comment]
@aklaver Yes I have all of them as shown here:
`<script type="text/javascript" src="../tabulator-master/dist/js/tabulator.min.js"></script>
<script type="text/javascript" src="../tabulator-master/dist/js/jquery_wrapper.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>`

**Comment by takuy** [comment]
I believe order matters - JQuery should be included before the Wrapper.

**Comment by aklaver** [comment]
@takuy 
That is correct, per the link above.

**Comment by bioscorpion** [comment]
@aklaver I made this change still same errors:
`Uncaught SyntaxError: Unexpected token else
jquery_wrapper.min.js:2 Uncaught TypeError: t.widget is not a function
    at jquery_wrapper.min.js:2
    at jquery_wrapper.min.js:2
    at jquery_wrapper.min.js:2
(anonymous) @ jquery_wrapper.min.js:2
(anonymous) @ jquery_wrapper.min.js:2
(anonymous) @ jquery_wrapper.min.js:2
VM375 myapplicationname.php:24 Uncaught ReferenceError: Tabulator is not defined
    at VM375 myapplicationname.php:26`

**Comment by aklaver** [comment]
I routinely run Tabulator outside the app directory and all the folks that use the CDN versions are pulling it from an entirely different machine.  That leads me to believe there is something happening in your application with regard to how it is pulling the libraries in. Can you show how you are setting up the JS and CSS files in your app/templates?

**Comment by bioscorpion** [comment]
@aklaver Is this what you you are asking for:
`<link href="../tabulator-master/dist/css/tabulator.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="../tabulator-master/dist/js/tabulator.min.js"></script>
    <script type="text/javascript" src="../tabulator-master/dist/js/jquery_wrapper.min.js"></script>`

**Comment by aklaver** [comment]
Sorry I did not catch it earlier, but the jquery_wrapper also needs jQuery UI installed. The next question is are you using jQuery to access your Tabulator components? Also does the above still work when you are using it in the application directory?

**Comment by bioscorpion** [comment]
Originally when I created this application I placed the `tabulator-master` in the application and it worked successfully.

So I downloaded jquery and placed in the parent directory like this:
```
<script src="../js/jquery-3.4.0.min.js"></script>
<script type="text/javascript" src="../tabulator-master/dist/js/tabulator.min.js"></script>
<script type="text/javascript" src="../tabulator-master/dist/js/jquery_wrapper.min.js"></script>
```
looks like it made a bit of progress, but still getting errors:
```
Uncaught SyntaxError: missing ) after argument list
jquery_wrapper.min.js:2 Uncaught ReferenceError: jQuery is not defined
    at jquery_wrapper.min.js:2
    at jquery_wrapper.min.js:2
(anonymous) @ jquery_wrapper.min.js:2
(anonymous) @ jquery_wrapper.min.js:2
myapplicationname.php:93 Uncaught ReferenceError: $ is not defined
```

**Comment by aklaver** [comment]
If you are going to use the jquery_wrapper then you will need jQuery UI also.
Also what version of Tabulator are you using?
Lastly, while doing this troubleshooting I would suggest using the un-minified versions of JS, so you get more informative error messages.

**Comment by bioscorpion** [comment]
@aklaver I am using Tabulator version 4.2
I made all the changes to use the un-minified versions of JS:
```
<script src="../js/jquery-3.4.0.js"></script>
<script src="../js/jquery-ui-1.12.1.custom/jquery-ui.js"></script>
<script type="text/javascript" src="../tabulator-master/dist/js/tabulator.js"></script>
<script type="text/javascript" src="../tabulator-master/dist/js/jquery_wrapper.js"></script>
```
I am getting these errors:
```
jquery-3.4.0.min.js:2 Uncaught SyntaxError: missing ) after argument list
jquery-ui.js:14 Uncaught ReferenceError: jQuery is not defined
    at jquery-ui.js:14
    at jquery-ui.js:16
(anonymous) @ jquery-ui.js:14
(anonymous) @ jquery-ui.js:16
jquery_wrapper.min.js:2 Uncaught ReferenceError: jQuery is not defined
    at jquery_wrapper.min.js:2
    at jquery_wrapper.min.js:2
(anonymous) @ jquery_wrapper.min.js:2
(anonymous) @ jquery_wrapper.min.js:2
myapplicationame.php:94 Uncaught ReferenceError: $ is not defined
    at myapplicationame.php:94
```

**Comment by bioscorpion** [comment]
@aklaver Okay it finally works now!!!! :-)))))

The above errors inthe last comment were because I did not have a space in the comment, I was commenting out all the minified JS and not having the space caused the above errors in the last comment.

I did make all all the JS to be the full versions (not minified) like this:
```
<script src="../js/jquery-3.4.0.js"></script>
<script src="../js/jquery-ui-1.12.1.custom/jquery-ui.js"></script>
<script type="text/javascript" src="../tabulator-master/dist/js/tabulator.js"></script>
<script type="text/javascript" src="../tabulator-master/dist/js/jquery_wrapper.js"></script>
```

For what ever reason the minified versions worked when I placed the Tabulator in the application directory, but not in the parent directory.

Therefore in order for this to work I had to use the full JS versions as you advised with the Tabulator in the parent directory. Why??? I don't quite understand that yet but all that matters is that it works now!!!!

Thank you @aklaver for all your help! I appreciate it very much!!!!

**Comment by aklaver** [comment]
Well when you started this thread you did not have the jquery_wrapper or jQuery UI in any form(minified/un-minified). After that there where a lot of parts in motion. My suspicion is that if you where to replicate the working solution you have above in minified form it would work.

**Comment by bioscorpion** [comment]
@aklaver I was actually thinking that after I gave it more thought. So then I decided to give the minified version another chance:
```
<script src="../js/jquery-3.4.0.min.js"></script>
<script src="../js/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
<script type="text/javascript" src="../tabulator-master/dist/js/tabulator.min.js"></script>
<script type="text/javascript" src="../tabulator-master/dist/js/jquery_wrapper.min.js"></script>
```

But I am getting errors using these minified version:
```
jquery-3.4.0.min.js:2 Uncaught SyntaxError: missing ) after argument list
jquery-ui.min.js:6 Uncaught ReferenceError: jQuery is not defined
    at jquery-ui.min.js:6
    at jquery-ui.min.js:6
jquery_wrapper.min.js:2 Uncaught ReferenceError: jQuery is not defined
    at jquery_wrapper.min.js:2
    at jquery_wrapper.min.js:2
community_outreach_territory_master_database_edit.php:97 Uncaught ReferenceError: $ is not defined
    at community_outreach_territory_master_database_edit.php:97
```

Could possibly be one of the minified versions is a bad file, at least that what these errors show.

**Comment by aklaver** [comment]
If there is it looks like the jquery-3.4.0.min.js.
To test you might try: 

1) Using the uncompressed version of it with the minified version of the others.
or
2) Download the file again or use a CDN version to see if is download corruption.
or
3) Another minified version of jQuery:
https://code.jquery.com/jquery/

**Comment by bioscorpion** [comment]
@aklaver I did download a the latest production minified version and that fixed the issue! For whatever reason when I first downloaded the jQuery package from the beginning as you first recommended I had the corrupt minified version the whole time.

So now this works:
```
<script src="../js/jquery-3.4.0.min.js"></script>
<script src="../js/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
<script type="text/javascript" src="../tabulator-master/dist/js/tabulator.min.js"></script>
<script type="text/javascript" src="../tabulator-master/dist/js/jquery_wrapper.min.js"></script>
```

Thnak you for all your help @aklaver !!!! :-)
