### ISSUE TITLE
Make (S)CSS more customizable

### ISSUE THREAD

**Issue by demkani** [olifolkerd/tabulator#1983]
**Is your feature request related to a problem? Please describe.**
For a project I need a 'more customizable' tabulator. Working with nested selectors (and so a higher css specificity level) makes it pretty hard.

**Describe the solution you'd like**
I'd like to refactor the css… 
Actually I've already simplified almost the whole (and mighty ;) ) tabulator.scss: resolved nested selectors, started adding BEM naming and added a lot of descriptive comments. Everything works still fine.

So far I didn't touch any of the properties. Visually it's still the same.
In the end I'd like to add more theming variables.

**Describe alternatives you've considered**
No idea ¯\_(ツ)_/¯

**Additional context**
Just to make sure, I don't want to say the current css is bad or similar. Just want to help to improve it a bit :) I could share my current fork so you could have a look at the current state…

![Bildschirmfoto 2019-04-15 um 18 13 11](https://user-images.githubusercontent.com/1410361/56148246-24eb7300-5faa-11e9-97cd-205d668cb912.png)

**Comment by olifolkerd** [comment]
Hey @demkani 

I dont disagree with your approach, but you can easily use the existing SCSS in that way. it just needs slightly longer definition in your override script. as long as it is the same specificity as the existing selector it will override it if you include your code after.

I would be happy to add more variables if you feel there are ones that are missing, but i certainly wouldnt be looking at a wholesale refactor of the CSS until the next major version change which will likely be next year.

Cheers

Oli :)
