### ISSUE TITLE
ajaxLoaderLoading not showing

### ISSUE THREAD

**Issue by morkers** [olifolkerd/tabulator#1984]
`ajaxLoaderLoading` is not showing when used in combination with `ajaxProgressiveLoad` and `ajaxSorting` and `ajaxFiltering` when sorting and filtering data.

**Tabulator Info**
4.2.5
```
{
  ajaxProgressiveLoad: 'scroll',
  ajaxSorting: true,
  ajaxFiltering: true,
  ajaxLoader: true,
  ajaxLoaderLoading: 'Loading test'
}
```

**Comment by aklaver** [comment]
I thought was supposed to be defined as HTML:

http://tabulator.info/docs/4.2/options#table

"When loading data, Tabulator can display a loading overlay over the table. This consists of a modal background and a loader element. The loader element can be set globally in the options and should be specified as a div with a display style of inline-block."

There are examples below the above quote.

**Comment by morkers** [comment]
Found the problem.
When using `ajaxProgressiveLoad: 'scroll'`, request for data (https://github.com/olifolkerd/tabulator/blob/master/src/js/modules/page.js#L539) is called with `silent = true` (https://github.com/olifolkerd/tabulator/blob/master/src/js/modules/ajax.js#L249) and loading message is skiped.

**Comment by olifolkerd** [comment]
Hey @morkers 

This is correct, under usual operation the loading should happen in the background without the user being aware of it so there was no need for the loader to be show,

If you have a usage case in mind that i haven't covered i would love to hear more.

Cheers

Oli :)

**Comment by morkers** [comment]
@olifolkerd Hi!

It would be useful to show loader when loading first page when used with progresive load. This way user would see loader after/duaring ajax search and sorting.

**Comment by mischmid** [comment]
@olifolkerd 
I agree, it would be useful to atleast notify the user that the initial page is loading.
