### ISSUE TITLE
White space issue while resize last column

### ISSUE THREAD

**Issue by lalitapatil1993** [olifolkerd/tabulator#1985]
Describe the bug:

We want last column to freeze while re-sizing. We found that while resizing the last column there is white space at the end.
Is there any solution where we can fix the last column at the end like we have fixed the movement of first column from the left corner 

Tabulator Info
- Which version of Tabulator are you using-4.1

Expected behavior
While resizing column it should not show white space

Desktop (please complete the following information):
 - OS: windows
 - Browser : chrome

**Comment by olifolkerd** [comment]
Hey @lalitapatil1993 

Please create a Code Pen or JS Fiddle that recreates your issue.

Cheers

Oli :)

**Comment by JaldhiR** [comment]
Hi Olifolkerd,

Please see the screen record shared at the below location:
https://drive.google.com/file/d/1JPoOoOI8aH8PfoN7XeaLKg2lkaGWMEic/view

We have used tabulator libraries.
We are facing issues while resizing the column.
If we adjust column width of the last column, then we can see the white space at the end of the table.
As a user this space at the end doesn't look good.
Suggest what can be done?

![image](https://user-images.githubusercontent.com/49673438/57368564-09d6e200-71a9-11e9-84dc-dfb190beda56.png)
