### ISSUE TITLE
Bug with column group

### ISSUE THREAD

**Issue by labidus** [olifolkerd/tabulator#1987]
When you double click (multiple click) on the column line, the line move a little, then you start resizing the column and by now the entire columns alignment are scrap and nothing can repair it unless you reload the page.

Using the latest version and be able to reproduce on your examples
![image](https://user-images.githubusercontent.com/10580216/56206164-b645fe00-6019-11e9-9c5e-fc127d5f327d.png)

**Comment by takuy** [comment]
Does this happen in all browsers for you?

**Comment by takuy** [comment]
This seems to happen if you double-click on the left-side of the handle - either in the middle divider or the end divider. Doesn't happen on the right-side of the handle.

**Comment by labidus** [comment]
I only use Chrome, I just try Edge and it do the same thing

**Comment by olifolkerd** [comment]
Hey @labidus 

This appears to be a small graphical glitch on the column redraw, i will look at fixing it in the next minor release.

Cheers

Oli :)

**Comment by labidus** [comment]
thank you really appreciated :)

**Comment by olifolkerd** [comment]
Hey @labidus 

I have pushed a fix for this to the master branch and will include it in this weekends patch update.

Cheers

Oli :)

**Comment by labidus** [comment]
great thanks!!
