### ISSUE TITLE
community snippets list (or something)

### ISSUE THREAD

**Issue by takuy** [olifolkerd/tabulator#1988]
I'm ditching the format if you don't mind - what I'd like to suggest is some kind of community-managed snippets list or database. There's tons of things users of Tabulator have done with the package that other users can look at for inspiration or get an idea of how to do. 

While demos and documentation show a good portion, some people don't natively think beyond that or don't understand all the callbacks and hooks. 

I'm not sure if something like CodePen Collections would be the way to go but I'd definitely like to encourage more sharing of various Tabulator set ups.

**Comment by olifolkerd** [comment]
I am looking at setting up a case studies section on the website after the 4.3 release in may that will allow users to show of their own creations.

Is that what you would be after?

Cheers

Oli :)

**Comment by takuy** [comment]
That'd definitely work!

**Comment by olifolkerd** [comment]
Hey @takuy 

I have just added the [Tabulator Ideas Repo](https://github.com/olifolkerd/tabulator-ideas/blob/master/README.md) for the community to share link to any useful code or inspirational tools built on Tabulator.

I will include more info on it in the 4.8 site update tommorow.

Cheers

Oli :)
