### ISSUE TITLE
Positioning of new column

### ISSUE THREAD

**Issue by mrdo23** [olifolkerd/tabulator#199]
hi there,

i can't seem to position a new column properly.

i'm using the code example that you supplied:

$("#tableEditor").tabulator("addColumn", { title: "Age", field: "age" }, "true", "score");

switching between true and false for the above column always seems to place it before the "score" column in this case.
i also can't seem to get positioning by index to work using the following syntax:

$("#tableEditor").tabulator("addColumn", { title: "Age", field: "age" }, 2);

no matter the index, the column is always placed at the beginning.

any ideas?

i also get two rows added to my table when using the 'addRow' method. each of these results in 2 extra rows when i call the 'getData' method (i.e 4 extra rows in total).

let me know if you need me to provide extra code samples.

many thanks for your hard work - it's very much appreciated!

**Comment by olifolkerd** [comment]
Hey,

You seem to be passing a string value for ***"true"*** or ***"false"*** , but the ***addColumn*** function takes a Boolean for this value so you shouldn't use quotation marks:

```js
//Incorrect way to add column before
$("#tableEditor").tabulator("addColumn", { title: "Age", field: "age" }, "true", "score");
//correct way to add column before
$("#tableEditor").tabulator("addColumn", { title: "Age", field: "age" }, true, "score");

//Incorrect way to add column after
$("#tableEditor").tabulator("addColumn", { title: "Age", field: "age" }, "false", "score");
//correct way to add column after
$("#tableEditor").tabulator("addColumn", { title: "Age", field: "age" }, false, "score");
```

In your second example you are missing the ***before*** parameter which you must include if your are going to include the ***position*** paramter:
```js

$("#tableEditor").tabulator("addColumn", { title: "Age", field: "age" }, false, 2);
```

The duplicate row issue is a bug introduced in the latest version of Tabulator. i should have a fix out for it this weekend.

Let me know if that helps

Cheers

Oli

**Comment by mrdo23** [comment]
hi oli,

as expected that solved the problem - it had been a long day by that point on friday! thanks for the quick reply. 

do you know if the duplicate row issue has been resolved?

thanks again!

**Comment by olifolkerd** [comment]
Hey,

Good to hear you are all sorted.

The duplicate row issue has just been resolved as well.

Cheers

Oli

**Comment by mrdo23** [comment]
Hi Oli,

Thanks again for your assistance - sorry to bother you again.

I'm still having a couple of issues:

I get 2 rows when calling the following:
$("#tableEditor").tabulator("addRow");
This is called on a jQuery click event which I am unbinding to ensure that it fires only once.
I'm using the CDN version of your code which I'm assuming is always the latest?

If I try to add a single row and get 2 (number of displayed rows = 3, number of actual rows (from getData) = 3.
When I try and delete a row, the displayed rows decreases by one but the actual rows stays the same. When I delete the second newly-added row, the displayed row is removed and both actual rows are deleted.
I'm using the following to delete rows:
$("#tableEditor").tabulator("deleteRow", cell.closest(".tabulator-row"));

The other issue is that I'm still having problems adding a column at a specified position.
Using your code, the following doesn't work for me:

$("#tableEditor").tabulator("addColumn", { title: "Age", field: "age" }, false, 1);

Any ideas?

**Comment by olifolkerd** [comment]
Hey mrdo23,

The CDN version of the code is only updated when a new version is released (approximately once a month), the latest changes are only available through the github repo untill the next version is released in a couple of weeks.

in the mean time i would suggest downloading your updated source from github.

Cheers

Oli

**Comment by mrdo23** [comment]
Hi Oli,

I'm now referencing the code locally - I still get 2 new rows displayed when I can the following function:

$("#tableEditor").tabulator("addRow");

Only one row is actually added when I call getData.

Any ideas as to what in my code might be causing this? As I said, I'm unbinding the jQuery event so that's only firing once.

I'm still not able to add a column using:

$("#tableEditor").tabulator("addColumn", { title: "Age", field: "age" }, false, 1);
or
$("#tableEditor").tabulator("addColumn", { title: "Age", field: "age" }, true, 1);

Thanks again for your assistance.

**Comment by olifolkerd** [comment]
Could you post a copy of your Tabulator constructor so i can try and recreate your issue with a similar table setup.

Cheers

**Comment by mrdo23** [comment]
Hi Oli,

Hope this helps.

Cheers

[tabulator.txt](https://github.com/olifolkerd/tabulator/files/813888/tabulator.txt)

**Comment by mrdo23** [comment]
Hi Oli,

Just to let you know that I'm still getting multiple rows when I call the addRow function.

I've attached another copy of a simpler table that I'm working with which has the same issue.

Many thanks

[tabulator2.txt](https://github.com/olifolkerd/tabulator/files/822166/tabulator2.txt)

**Comment by olifolkerd** [comment]
Hey,

Sorry for the delay in getting back to you, ive had a buy week at work. i will have a look through this this evening.

Thanks for baring with me

Oli

**Comment by mrdo23** [comment]
hi Oli,

no worries - i know that feeling! your efforts are very much appreciated.

**Comment by olifolkerd** [comment]
Hey,

So i have had a look through your example and i found a bug in Tabulator that was stopping the ***addColumn*** function working for column index's, which i have just pushed a fix in for.

As for adding rows, when i use the ***addRow*** function on your example table, it only adds one row as expected.

if you want to prevent a button from triggering the sort in the header you will need to call the ***stopPropagation*** function on it, declare this after constructing your tabulator:
```js
$(".tabulator .tabulator-col button").on("click", function(e){
    e.stopPropagation();
});
```

Cheers

Oli

**Comment by mrdo23** [comment]
hi Oli,
thanks for taking the time to get back to me - much appreciated!
i had already tried stopPropagation with no success. i've also updated my code to point to the latest source and still no success.
i'll try and find some time to investigate properly - do you think my issues could be caused by having multiple ctors? i set a lot of my data server-side and so declare the columns and then the data and finally add another column.
thanks again for taking the time to get back to me.

**Comment by olifolkerd** [comment]
In that case it is likely because the element is being added after the event binding has been added.

Try this instead:
```js
$(".tabulator .tabulator-header").on("click", "button", function(e){
    e.stopPropagation();
});
```

**Comment by mrdo23** [comment]
hi Oli - that still didn't work for me - clicking on the button (actually a bootrap 'a' tag) still sorts that column before calling the function.

i'll take some time later today to tty and run some tests client-side only and see what happens. it sounds like building up some of the params and data server-side is causing strange behaviour!

thanks again for your efforts.
