### ISSUE TITLE
Unable to join 2 values in field

### ISSUE THREAD

**Issue by ryhill** [olifolkerd/tabulator#1990]
**Describe the bug**
I am unable to join two values for a field

**Tabulator Info**
4.1.4

**Working Example**

            var table = new Tabulator("#osdetails", {
                data:$scope.usersdata,
                columns:[
                    {title:"Date", field:"created_date"},
                    {title:"OS Type", field:"user_data_json.os_type" +  "user_data_json.os_release"},
                    {title:"Platform", field:"user_data_json.platform"},
                    {title:"System Name", field:"user_data_json.system "},
                    {title:"User Name", field:"user_data_json.user "},
                    {title:"Stage", field:"user_data_json.stage"},
                  
                ],
            });

**Comment by takuy** [comment]
I don't think this is a feature? You can do this with either a formatter or mutator depending on your data access needs.

**Comment by olifolkerd** [comment]
Hey @ryhill 

You should use a mutator for this.

You should bind the column to a new field that dosn't exist yet, for example "os" and then use a data mutator to create the value:
```js
//define custom mutator
var customMutator = function(value, data, type, params, component){
	//value - original value of the cell
	//data - the data for the row
	//type - the type of mutation occurring  (data|edit)
	//params - the mutatorParams object from the column definition
	//component - when the "type" argument is "edit", this contains the cell component for the edited cell, otherwise it is the column component for the column

	return data.user_data_json.os_type +data.user_data_json.os_release; //return the new value for the cell data.
}

{title:"OS Type", field:"user_data_json.os", mutator:customMutator},
```

I hope that helps,

Cheers

Oli :)

**Comment by ryhill** [comment]
Thanks a lot. custom mutators are great

A quick question. How do i replace all 'nulls' to ''  in data before i download in a downloadDataFormatter


       var downloadFormatter = function (data) {
        data.forEach(function (row) {
            row.forEach(function (object) {
                for (key in object) {
                    if (object[key] == null)
                        object[key] = '';
                }
            });
        });
        return data;
