### ISSUE TITLE
redo bug with groupBy rule and one row table

### ISSUE THREAD

**Issue by lawfulneut** [olifolkerd/tabulator#1992]
Tabulator 4.2

Just reporting a little bug here:  .redo( ) doesn't group a row it returns to the table (after using undo) if the row was the only one left. Redrawing or updating data doesn't help. It works fine when you have 2 or more rows.

1. Empty table with groupBy rule (I group data by 2 columns) and history,
2. Use addRow function to create one row (row has group level/s),
3. Undo changes,
4. Redo changes (now you have row with no group levels),
5. Add new row (now everything's back to normal).

**Comment by olifolkerd** [comment]
Hey @lawfulneut 

Thanks for getting in touch,

Sorry to hear you are having trouble, i will look into it further for the next patch release.

Could i ask that in future you use the bug issue templates when reporting a bug, it will prompt your for all the information i need to know to resolve your issue quickly.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @lawfulneut 

After digging into this a bit further it was because the row group wasn't being correctly reinitialized when the row was re-added that contained a new grouping.

I have pushed a fix for this to the mastr branch and will include it in todays patch release.

Cheers

Oli :)
