### ISSUE TITLE
cell.setValue forces reformat of the cell though sometimes maybe it should not

### ISSUE THREAD

**Issue by Alarich** [olifolkerd/tabulator#1995]
**Is your feature request related to a problem? Please describe.**
Say I have created a formatter, which has attached a calculation function on input, but I also want to make sure Tabulator has the current inputted value set in its' internal data. 
Currently, when calling cell.setValue(value) in the formatter, the cell contents are reformatted, thus causing the focus to be lost from within the input field, as it has been entirely replaced.

Using an editor might solve this issue, but offered other issues so I don't consider it a solution in my case.

**Describe the solution you'd like**
Would it be possible to add a third parameter to cell.setValue, which by default is true, but can be turned off to disable a reformat for that call?
`
cell.setValue(value, mutator, reformat)
`

This would seem to require a change in `Cell.prototype.setValueActual` to not call `this._generateContents();` if the added boolean commands such. Assuming the user knows what they're doing, there should not be any errors resulting from the change.

**Describe alternatives you've considered**
Using the input event, but only calling cell.setValue(value) on change/blur event, but this causes the other cell data values to be in the correct state during input, while the cell that calls the event cannot be.

There may be better alternative solutions and I'm open to thoughts. 
I'm also aware the reformatting is most likely there for a good reason, but in this situation there would be no difference in the cell content with and without a reformat, other than allowing the user to keep typing.

**Additional context**
The request should be clear enough to not warrant additional information.

**Comment by takuy** [comment]
This definitely seems like something an Editor should be used for. Can you provide some sample code that demonstrates the problem you're experiencing?

**Comment by Alarich** [comment]
Editor didn't allow all fields to be editable at the same time which was a requirement. I can't remember the other issues currently, but there was something else.

On Apr 17, 2019 13:55, Sam <notifications@github.com> wrote:

This definitely seems like something an Editor should be used for. Can you provide some sample code that demonstrates the problem you're experiencing?

**Comment by olifolkerd** [comment]
@takuy is right, that is the purpose of editors not formatters, any time a value changes the formatter must be called otherwise the display information is out of date.

You say that you want to be able to edit all cells at once, but the browser will only provide focus to one element at a time.

Im afraid without seeing a JS Fiddle or Code Pen of this in action it will be difficult to offer specific advice.

Cheers

Oli :)

**Comment by Alarich** [comment]
I was attempting to solve for multiple issues.

By going with editors:
1. Visually indicate all cells to be editable at the same time.
Solution: Create a formatter for each cell and turn it into what the editable version would look like. BAD
Solution 2: CSS somehow? Not something I excel at.
2. Have formulas across the row attached to events on the inputs.
Solution: Instead of using the field inputs as formula data sources, use the tabulator data itself. GOOD
3. Have multiple inputs within one cell.
Solution: Give up probably.
4. Ability to attach tabulator to an existing form and post that form with the data from tabulator inputs
Solution: None.

By going with formatters, I managed to solve each issue and possibly a few others I couldn't remember currently.

Now I will say, performance in IE11 tanked, it's not exactly unusable, but close to it.

It is understandable that Tabulator was never meant to be used in such a manner, but it works. The only thing I couldn't solve for, was the input event, so I didn't end up using it.

In any case, as this use case wasn't meant for Tabulator, I understand if an option to disable the regeneration of cell contents is not something you would want to offer, it isn't anything critical.

Thank you for the attention @olifolkerd  and @takuy and thank you @olifolkerd for the great library. :)
