### ISSUE TITLE
Cannot paste into table when initially selecting a non-editable cell

### ISSUE THREAD

**Issue by webtango** [olifolkerd/tabulator#1996]
**Describe the bug**
Cannot paste into table when initially selecting a non-editable cell. Using the library through angular

**Tabulator Info**
- Which version of Tabulator are you using? 4.2.5
- Post a copy of your construct object if possible so we can see how your table is setup
table = new Tabulator(this.tab, {
        data: this.tableData,
        reactiveData: true,
        columns: this.columnNames,
        height: this.height,
        layout: 'fitColumns',
        clipboard: true,
        clipboardPasteAction: 'replace',
        keybindings: {
          'scrollToStart': false,
          'scrollToEnd': false,
        },
        clipboardPasteParser: this.PasteParser,
        clipboardPasted: this.ValidatePaste,
        selectable: true,
        tooltips: this.firstColumnToolTip,
        cellEditing:function(cell){
          self.errorMessage = '';
        },
      });
**Working Example**
Please include a JS Fiddle or Code Pen that demonstrates the problem, it is very hard to diagnose an issue from a simple description

**To Reproduce**
1. Have a table where the first column does not have any editors
2. Subsequent columns have editors.
3. Click on a cell in the first column
4. Hit ctrl+v to paste data
5. No paste occurs
6. Click in cell in column 2.
7. Click back to first column cell.
8. Hit ctrl+v to paste data
9. Table gets populated with new content

**Expected behavior**
My data should paste into the table and be displayed.

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser Chrome
 - Version 73

**Comment by aklaver** [comment]
To me that seems like normal behavior for pasting clipboard data. In general I can't paste clipboard contents to anything that does not accept input, in your case un-editable cells Can you elaborate on what your use case is, to see if there maybe another way of achieving what you want?

**Comment by webtango** [comment]
@aklaver I forgot to add in the original that it works in Firefox if you just initially click in the uneditable cell.

My use case is allow users to easily paste in data as closely as to how it works in excel. My table is a matrix so the upper left cell cannot have content in it, so I figured it was a good place to allow them to paste.

If you attempt to paste a table of data into a cell, it just fills that cell.

**Comment by aklaver** [comment]
Looks like this is going to need more info or better yet a jsFiddle or CodePen example. I would leave the reactiveData(Angular) part out of it for now. The important part is the code for the overridden clipboardPasteParser and clipboardPasted parts.

**Comment by aklaver** [comment]
I set up a jsFiddle:

https://jsfiddle.net/aklaver/12u7j4oe/22/

What I see is that in Chrome I can paste using any non-editable field that does not have the 'handle' formatterHandle column). In FF I can use the Handle column as well. In either case if I paste into editor field(Name) the data is entered into the field not the table.

**Comment by webtango** [comment]
Sorry I couldn't get back to you guys with the long Easter weekend. After some testing it looks like removing the reactiveData: true value fixes the issue for me. 

I will link to a fiddle I put together based on my code for you
[fiddle](https://jsfiddle.net/webchaos/q5wj0daz/15/)

Thanks for the help and the responses.
