### ISSUE TITLE
non-table custom row

### ISSUE THREAD

**Issue by Stylesoftware** [olifolkerd/tabulator#1997]
**Is your feature request related to a problem? Please describe.**
In a table of many columns, i'd like to be able to create a custom row made up of html of my choice. 
Example would be clicking on a 'More/Less Info' cell button and having a div expand below the current row containing for example a photo or graph or some paragraph of text.
The only solution at the moment that I can see is diving in to the DOM and inserting it myself, however that sounds problematic with your virtual-DOM examples.

**Describe the solution you'd like**
Provide a way to identify or assign an id to the div of the selected, editable or current row
var id = table.getRowID();
$(id).appendHTML("Big DIV we want to show or hide related to this data row"); 
// tacking of the additional html for closing and opening will can be in the user scope as its outside of tabulator

**Describe alternatives you've considered**
For a selectable row getting 'tabulator-selected' out of the DOM is okay
For an editable row i'm not seeing 'tabulator-selected' or any identifiers :/
Looked at rowFormatter, but it seems to me i'd be reinventing all the table formatting and functionality that tabulator already does so well.

**Comment by takuy** [comment]
I am pretty sure what you're describing is basically explained in the Nested Tables example on the website. I am not sure how it interacts with the virtual dom. In this case, the Nested table is just another html element appended to the row. Using that example, I wrote something that hides and shows the nested table, but can be applicable to any HTML element really. I'll share that example in a bit.

**Comment by takuy** [comment]
@Stylesoftware  Here's an example adapted from the [Nested Tables example](http://tabulator.info/examples/4.2#nested-tables). It's not the neatest (the CSS/styling should probably be moved to an actual CSS file) but it works.

https://codepen.io/tako1337/pen/ROMWLy

 @olifolkerd could probably confirm if Virtual DOM would still work?

**Comment by Stylesoftware** [comment]
Ahh I had a brief look at Nested tables but the demo didn't seem to present itself in the manor I was after, not sure why, as your example is pretty much what I was after. 
Thank you so much!

**Comment by olifolkerd** [comment]
@takuy is bang on with the example, that should not have any major issues with the virtualDOM, the only thing to be aware of is making sure its open state is stored somewhere so it remanins open next time it is redrawn

Cheers

Oli :)

**Comment by Stylesoftware** [comment]
Been using your tabulator to many depths over the last 3 weeks and I'd shake your hand with a big smile if I could.
After using the example code above, i found a problem I can't seem to solve.
If the table is sorted via InitialSort or user sort, before the custom row is generated, it uses the wrong row data.
Hope you can help

**Comment by takuy** [comment]
@Stylesoftware would you be able to provide an example in a codepen?

**Comment by Stylesoftware** [comment]
Hi,
Incase anyone else is using the above code pen, I noticed:
var pos = row.getPosition(true);

I changed it to:
var pos = row.getPosition(false);

That solves the problem of when the custom row is hidden and a sort is
applied, the row was showing the wrong data but maybe only in my case.

However in the above codepen it uses an image, where as im using html, and
I can't understand the line with "img" in it..
If I change it to "div", all sorts of weird things happen from rows
disappearing or sometimes hidden columns pop up
described here:
https://codepen.io/stylesoftware/pen/pmwxNV

**Comment by takuy** [comment]
@Stylesoftware You can actually just remove that line entirely most likely. Since rowFormatter() handles hiding/showing the row, (it's called again on row.reformat()), that line is just redundant.

**Comment by Stylesoftware** [comment]
Great worked like a charm!
Thank you so much.
