### ISSUE TITLE
ResizableRow

### ISSUE THREAD

**Issue by englich12345** [olifolkerd/tabulator#1998]
I checked ResizableRow : true but it's not working. Can you test this feature ?

**Comment by takuy** [comment]
@englich12345  The parameter should be "resizableRows" ie; `resizableRows:true,` - can you paste what your Tabulator set up looks like?

**Comment by englich12345** [comment]
yea, in the render(){
const options = {
      movableRows: true,
      dataTreeBranchElement: false,
      resizableRows: true
}
and
<ReactTabulator
                        className={"table-bordered"}
                        ref={ref => (this.ref = ref)}
                        data={this.props.data}
                        columns={editableColumns(this.openSideBar)}
                        options={options}
                      />
Something like this. Also, when I move resizableRows:true in Element ReactTabulator not working too.
