### ISSUE TITLE
add column header formatter to show a hamburger actions menu...

### ISSUE THREAD

**Issue by shaulnaim** [olifolkerd/tabulator#1999]
hi Oli, thanks for the good work :) i have an issue that you might help with...
I tried to pull it out but it's not easy. I am trying to make it look like you see here when you hover column header.
 https://www.ag-grid.com/javascript-grid-grouping/#example-auto-column-group
I used titleFormatter as Oli suggested here https://stackoverflow.com/questions/53301995/tabulator-add-menu-button-to-column-header
but  ( i am in the anggular project) I have no jquery . and when I click the button the dd is not opening and the sorting is activated...
can it be done easilly? can anybody show me jsfiddle with example doing it?
thanks

**Comment by takuy** [comment]
I think you would have to disable event propogation on your click handler. Can you provide an example of how you're trying to do it with angular now?

**Comment by shaulnaim** [comment]
oh man the link you gave is for the old angularjs (2013) the preventdefault is not the only issue also the drop down menu is not shown )using bootstrap) its hidden (z-index not helping).
 thanks for your help

**Comment by takuy** [comment]
Can you show some sample code as to what you're doing? a codepen or JS fiddle would be super helpful

**Comment by shaulnaim** [comment]
hi, see this roughly demo 
https://jsfiddle.net/Lgfq9pja/ 
i will want to have on the select header a burger icon with a dropdown of actions. I am using the bootstrap dropdown and it's not opening
Thanks.

**Comment by takuy** [comment]
@shaulnaim This seems to be a CSS issue. The bootstrap dropdown IS opening, you just can't see it. Try applying this in your CSS:

```
.tabulator-header, .tabulator-col-title, .tabulator-col {
  overflow: visible!important;
}
```

**Comment by shaulnaim** [comment]
thanks @takuy !  I will check.
 yes, I just added some code to an existing old tabulator example in jsfiddle so its an old version and not in angular, but was enough to demonstrate the issue. 
 BTW do you have a code example for selecting rows using a column of checkboxes and not row click? its very common and needed functionality and that will be appreciated.

**Comment by takuy** [comment]
@shaulnaim Here's an example with jQuery for the checkbox select/deselect: https://codepen.io/tako1337/pen/KYEdBp?editors=1010

Not sure of a comparable way to do it with Angular.
