### ISSUE TITLE
Get row index on cell click

### ISSUE THREAD

**Issue by sachadee** [olifolkerd/tabulator#200]
Hi,

Thanks a lot for your great job !

I'm trying to get the row index of a cell onclick

`{title:"Ação", field:"acao", align:"center", formatter:"tickCross", sorter:"boolean", onClick:function(e,cell, val,  data){alert(index);}}`

I want to delete the row on the cell click !

Thanks

**Comment by olifolkerd** [comment]
Hey,

Thanks, its always great to hear people are enjoying using Tabulator.

If you want to delete a row then you can pass the row object to the ***deleteRow*** function like this:
```js
{title:"Ação", field:"acao", align:"center", formatter:"tickCross", sorter:"boolean", onClick:function(e,cell, val, data){
    $("#example-table").tabulator("deleteRow", cell.closest(".tabulator-row"));
}}
```

Let me know if that helps you out.

Cheers

Oli

**Comment by sachadee** [comment]
Thanks a lot that's it !!!

2017-02-26 18:16 GMT-02:00 Oli Folkerd <notifications@github.com>:
