### ISSUE TITLE
ReactiveData doesnt work on nested object

### ISSUE THREAD

**Issue by mohshraim** [olifolkerd/tabulator#2000]
**Describe the bug**
ReactiveData doesnt work on nested object

**Tabulator Info**
- Which version of Tabulator are you using? 4.2

the source of problem that we have nested object that used in column
            
           [
           {title: "Title", field: "doc.title"}, 
           {title: "Name", field: "doc.name"}, 
          ...]

when u trace the row.update function i found that does update as following

      //update affected cells only
		for (var attrname in data) {
			var cell = _this6.getCell(attrname);
			if (cell) {
				if (cell.getValue() != data[attrname]) {
					cell.setValueProcessData(data[attrname]);
					if (visible) {
						cell.cellRendered();
					}
				}
			}
		}
from code its only check the first level of keys in data, so any nested object like our case will not be rendered.
do you consider it as bug? or we should not use nested object ?
Thanks

**Comment by olifolkerd** [comment]
This is a know limitation in the 4.2 release, and is stated as such in the documentation.

I will be added as a feature later this year

Cheers

Oli :)
