### ISSUE TITLE
Header columns do not align on horizontal scroll

### ISSUE THREAD

**Issue by dasboe** [olifolkerd/tabulator#2001]
**Describtion**

When scrolling horizontal the header columns do not always align with the data columns below when scrolling stops. While scrolling this is known behaviour ([#1437](https://github.com/olifolkerd/tabulator/issues/1437)) but when scrolling stops it is a bug. I've tested this in previous versions of Tabulator and the problem only occurs in 4.2.0 and later versions. 4.1.5 is not having this issue.

There is no problem when scrolling with dragging the scroll bar. For me the bug only appears by scrolling with a trackpad (Macbook) or with a mouse (finger swipe on Apple Magic Mouse).

**Tabulator Info**

- Tested on: 4.1.5 (aligns properly), 4.2.0 (buggy), 4.2.5 (buggy)

**Examples**

[Codepen for Version 4.1.5 (aligns properly - no bug)](https://codepen.io/anon/pen/XQEzEK)
[Codepen for Version 4.2.5 (buggy)](https://codepen.io/anon/pen/xeWXQb)

**To Reproduce**

1. Open Codepens above
2. Scroll left/right and stop scrolling abruptly (I used a Macbook Touchpad or an Apple Magic Mouse)
3. Columns do not align properly when scrolling stops

**Expected behavior**
Header columns always align with data columns below after scrolling stops

**Example Videos**

4.1.5 (aligns properly - no bug)
[![Tabulator 4.1.5](https://img.youtube.com/vi/o2Hw78yi2FY/0.jpg)](https://youtu.be/o2Hw78yi2FY)

4.2.5 (buggy)
[![Tabulator 4.2.5](https://img.youtube.com/vi/3lcZvjE3Itw/0.jpg)](https://youtu.be/3lcZvjE3Itw)

**Enironment**
 - OS: MacOs, Macbook Pro (2013) - Retina Display
 - Browser: Latestest Version of Chrome, Safari, Firefox

**Comment by olifolkerd** [comment]
Hey @dasboe 

I will look into this further for the next patch release.

Cheers

Oli :)

**Comment by dasboe** [comment]
Great - thanks Oli! :)

**Comment by olifolkerd** [comment]
i have pushed a fix for this to the master brnach and will include it in this weekends patch release.

Cheers

Oli :)

**Comment by dasboe** [comment]
Sweet - thanks for the quick fix! 👍
