### ISSUE TITLE
Adding arbitrary columns or rows to XLSX Download 

### ISSUE THREAD

**Issue by takuy** [olifolkerd/tabulator#2002]
**Describe the solution you'd like**
There doesn't seem to be a way to currently add arbitrary columns or rows to a download. Using the downloadDataFormatter callback still makes it match up to the defined columns array.  Not sure what syntax would be comfortable for this but I'll think of something.

**Describe alternatives you've considered**
This is doable if you make your own plain text (or a CSV) custom file formatter, but not as easily do-able with an XLSX download. 

Sorry this is kind of vague, wanted to get it posted before I forgot. I'll update with better ideas soon.

**Comment by aklaver** [comment]
http://tabulator.info/docs/4.2/download#advanced-config
"Hide Column In Download

If you don't want to show a particular column in the downloaded data you can set the download property in its column definition object to false:"

**Comment by takuy** [comment]
Right--what I'm looking to do is add arbitrary data. Not hide. This data might not be in a column or row already but generated at runtime. Kind of like calcs.

**Comment by aklaver** [comment]
I could see leveraging this:
https://github.com/SheetJS/js-xlsx/issues/817

**Comment by takuy** [comment]
Yeah, I'll probably write a custom file formatter using the existing XLSX as a base to handle what I need...

**Comment by aklaver** [comment]
Well the link above shows how to:
/* make the worksheet */
var ws = XLSX.utils.json_to_sheet(data);

Where data is an array of JSON objects. 
table.getData() will return that and you could modify it and pass to json_to_sheet() and build your own XLSX without dealing with the existing one.

**Comment by takuy** [comment]
I ended up making a new variation of the existing XLSX downloader that accepts extra rows and columns. If there's shown to be a need for it, I'll do a PR.

**Comment by aklaver** [comment]
I would just do the PR.

**Comment by olifolkerd** [comment]
@takuy if you set the ***visible*** property of the column to false, and the ***download*** property to true it will create a column that is visible in the download only and not the actual table.

Cheers

Oli :)
