### ISSUE TITLE
Custom footer Row in VueJS Global Scope Issue

### ISSUE THREAD

**Issue by timothymarois** [olifolkerd/tabulator#2003]
Currently, there is only `bottomCalc` and `topCalc` which only accept global functions. I can not seem to get these methods to run within the data prop of VueJS components. 

```
data: () => ({
tableColumns : [
            { title: "Campaign", field: "name", width: 300 },
            { title: "Account", field: "account_id" },
            { title: "CPA", field: "bid", bottomCalc:totalCPA, topCalc:totalCPA },
            { title: "BUDGET", field: "budget", align:"right" },
        ]
}),
```

This won't allow the column methods to run because they must exist in the global scope.

**Comment by olifolkerd** [comment]
@timothymarois 

I dont follow you, Functions of any scope can be passed in to any of the callbacks at any point in tabulator.

Absolutely nothing needs to be in the global scope, it is extremely bad practice to leave functions in the global scope.

The issue you are having is likely because you are trying to define your column definitions in the return of your data function therefore they have no access to the scope of the vue component the are instantiated in,

if you define your columns in the mounted function they would then have access to all the properties and functions of your vuew component.

I hope that helps,

Cheers

Oli :)

**Comment by timothymarois** [comment]
@olifolkerd Thanks. I do move some around. 

There is one thing about the bottomCalc or topCalc I want to ask if this exist currently, I cant find it in the documentation. 

But what I am trying to do is calculate the "totals" on the server-side, and I pass them in its own variable, so my server response is `data` for the table data and `totals` for the total row data. But what I noticed right now is I cant find a way to pass that information into the bottomCal function. 

Right now I've rigged it so that it places a span with a class, and I later replace those classes with the current inner text once the ajax complete (but that is not a good practice, it's just a work around)

**Comment by olifolkerd** [comment]
Hey @timothymarois 

At the moment you would need to use a custom calculation function for that, that pulls those values from an object.

You could setup that object using the ***ajaxResponse*** callback to set the values based on the info returned from the server.

I hope that helps,

Cheers

Oli :)

**Comment by timothymarois** [comment]
Hey @olifolkerd 

As I've been using this table structure on a larger scale of the application I do encounter issues with reactive states. Tabulator isn't exactly functionality with all features using VueJS. Here is another issue regarding this original problem. 

For instance, once Ajax loads in new data, if you use any custom filters, you are unable to add binding events like `@click`, once the table is loaded, all html within the rows are static and unable to render vuejs methods/data. Unless you have a better solution to the problem, but I don't see how the table is reactive like Tabulator says. This could only be an issue regarding Ajax rendering of data, but I'm not entirely sure. I want to create specific links within columns with vuejs click events to open up modals and do other actions, but I can not seem to accomplish this with Tabulator.

**Comment by angeliski** [comment]
Hi @timothymarois You can put some examples of your problem?
I create the lib [vue-tabulator](https://github.com/angeliski/vue-tabulator) to help in that integration. 
The rc version is just a simple component, but I will add new vue features for a better integration.

About your issue using the ajax, maybe you can use the [custom format](http://tabulator.info/docs/4.2/format#format-custom), in my project I use that to render a new component in cell specific.
That allow use vue reactivite inside the Tabulator.
