### ISSUE TITLE
Column Reordering with fixed header row alignment glitch

### ISSUE THREAD

**Issue by timothymarois** [olifolkerd/tabulator#2004]
As you can see the alignment of the header is off when dragging the header column. It drops down to the second header (which is for the total bar). When you release the drag, it goes to the location you want, but its a glitch aesthetically. 

![Screenshot 2019-04-19 20 52 15](https://user-images.githubusercontent.com/2489333/56449294-52eff080-62e5-11e9-852d-bbe1f7fccb11.png)

Its only an issue if using `topCalc`

**Comment by olifolkerd** [comment]
@timothymarois 

Please use the bug issue template if you are reporting a bug it will prompt you to answer the questions i need to fix things for you.

Could you please repost this issue using the template.

Cheers

Oli :)

**Comment by timothymarois** [comment]
@olifolkerd Hope this helps.

**Describe the bug**
As screen in the screenshot above, the alignment of the dragging column while trying to move it, drops down to the second row (which is the topcalc row)

**Tabulator Info**
 4.2.5

**Working Example**
It's easy to test. (below)

**To Reproduce**
Steps to reproduce the behavior:
1. Setup table with draggable/moveable columns
2. Create `topCalc` row so you have 2 fixed rows at the top, one the header, one the `topCalc` row.
3. Now drag one of the columns between the other columns like you're going to move it, you will see that the dragging box for that column drops to the second row instead of staying on the first. 

**Expected behavior**
I would assume dragging the header column to move it between other columns should stay within the header row, just like it does when you don't use the `topCalc` row. 

**Screenshots**
(above)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Comment by olifolkerd** [comment]
Hey @timothymarois 

Thanks for the details,

Could you setup a JS Fiddle or Code Pen that demonstrates the issue you are having.

Cheers

Oli :)
