### ISSUE TITLE
add RTL option for xlsx download

### ISSUE THREAD

**Issue by amiriahmad72** [olifolkerd/tabulator#2005]
**problem**
If direction of web page is rtl, then the result of using tabulator is rtl too. but when download data as xlsx, the result xlsx file is ltr.

**solution**
As described in [SheetJs Document](https://github.com/sheetjs/js-xlsx), the RTL option can be set using wb.Workbook.Views object (Views is a Workbook-Level Attributes).

**Comment by olifolkerd** [comment]
Hey @amiriahmad72 

great suggestion, i will include this in the next RTL system update.

Cheers

Oli :)

**Comment by amiriahmad72** [comment]
Thanke you @olifolkerd 

Your library is so awesome.
I write some `js` and `css` code for start support RTL.
1.Add RTL option to tabulator.core.js
2.Add tabulator-rtl class to tabulator.scss and write some basic RTL CSS Style.
3.On _buildElement function add tabulator-rtl class when RTL option us true.
3.Download XLSX file with RTL option Using tabulator RTL option.
4.Using RTL option on resize_columns.js for resize column in true direction
---------------------
I want to resolve FrozenColumns problem with RTL mode and some others things related to RTL.
I'm really happy to be working with you.

**Comment by olifolkerd** [comment]
Hi @amiriahmad72 

I have just pushed an update to the 4.5 branch that exposes the SheetsJS workbook object so you can make any customisations you like there:

```js
table.download("xlsx", "data.xlsx",{
    documentProcessing:function(workbook){
        //workbook - sheetJS workbook object

        //enable RTL on the workbook
        workbook.Workbook.Views = {
               RTL:true,
	};

        return workbook;
    }
}); //download a xlsx file using SheetJS properties
```

This will be released in a few weeks.

Cheers

Oli :)
