### ISSUE TITLE
Will you consider adding a google material theme style?

### ISSUE THREAD

**Issue by solo114114** [olifolkerd/tabulator#2007]
Will you consider adding a google material theme style. Also, can you implement the Add Columns feature? You can then also set the data for the cells in the column to be calculated by the formula. For example, the data in column C is obtained by multiplying the data of columns A and B respectively.Thanks

**Comment by aislanmaia** [comment]
Material Theme should be all I need for now, since I'm using material styles a lot in my projects, whatever framework I use, React, Vue or etc. 
+1

**Comment by solo114114** [comment]
Another question，can you implement the Add Columns feature? You can then also set the data for the cells in the column to be calculated by the formula. For example, the data in column C is obtained by multiplying the data of columns A and B respectively.Thanks

**Comment by takuy** [comment]
@solo114114  - this should be posted as a separate issue, but you can basically already do this by adding another column in your columns array and using a Mutator function.

**Comment by solo114114** [comment]
Thank you！I will try it.

**Comment by olifolkerd** [comment]
@solo114114 

Im always happy to add new themes, could you post a link to the documentation for the material theme table so i have a reference point to work from.

with regards to your second question have a look at issue #1990 it has an example of what you are after.

Cheers

Oli :)

**Comment by timothymarois** [comment]
I would assume we want it based on the actual [Material Design](https://material.io/) by Google. This is a great idea because I also use the Material theme. It's very popular among the SPA frameworks like VueJS. And being compatible with like [Vuetifyjs](https://vuetifyjs.com/en/).

**Comment by aislanmaia** [comment]
I'm using [Quasar](https://v1.quasar-framework.org) vue framework and its table solution (of course, it has material design theme by default). If this gets material theme, I would use `tabulator` any time over quasar [tables](https://v1.quasar-framework.org/vue-components/table) because tabulator is way better, more customizable and more easy to use.

What tabulator is lacking is only a proper [Material Design](https://material.io/design/components/data-tables.html#behavior) table design and theme.

**Comment by olifolkerd** [comment]
Hey All,

I will be looking at adding this in the 4.3 release.

Cheers

Oli :)

**Comment by morficus** [comment]
Just for general reference and easy lookup, here is the Trello card that talks about adding a Material Design theme: https://trello.com/c/lyUFSniV/256-material-design-theme-2007

**Comment by morficus** [comment]
Is anyone currently working on this?
If not, I would be interested in picking it up.

**Comment by olifolkerd** [comment]
Hey @morficus 

Im looking to include this in the 4.4 release in a couple of weekends time. If you recon you can get it in for then i would welcome the pull request.

Some things to take note of, you must build the styles in SCSS, look in the src folder for exiting examples (bulma / bootstrap are good examples)

The new stylesheet must be created in its own folder in the `/src/scss` folder

The variables must be defined in a variables.scss file, ideally taken from an existing such file from the standard theme to make it easier for people to integrate with their own custom builds.

You must follow the existing design style for the SCSS file, a complete rebuild will not be accepted as it will be too difficult to maintain and integrate with other systems

Let me know if you want to give it a go

Cheers

Oli :)

**Comment by morficus** [comment]
@olifolkerd  - 18 days later but I'm finally able to get started on this today :-)

**Comment by olifolkerd** [comment]
Hey @morficus 

How goes your theme generation, im looking to do a release in the next couple of weeks and it would be a great addition.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
I have pushed a materialize theme to the 4.5 branch which should cover the material design look and feel. which will be released in a few weeks.

Let me know your thoughts.

Cheers

Oli :)
