### ISSUE TITLE
Exception occurred on adding new row from last page

### ISSUE THREAD

**Issue by sahaneja** [olifolkerd/tabulator#2008]
**Issue Description**
Browser:Chrome 73.0 (64 bit)
I am trying to create a new row, add some default content in it and apply validations on it. Everything works fine when I am on the first page, but as soon as I navigate to some other page and try to add row, I get exception "Uncaught TypeError: cellComponent.getElement is not a function" on line:
let fieldElement = cellComponent.getElement();
On debug I found that in this case, the value of cells attribute of rowComponent is an empty array.     
_row-> cells:[]
So, rowComponent.getCell(fieldName) returns "false", instead of the actual cell.

**Tabulator Info**
- version 4.2

**Code Snippet** 
**addNewRow() is called when user clicks on Add Row button. 
**Exception raised at 2nd line of function isCellContentCorrect  ie. rowComponent.getCell(fieldName)

```js
tabulatorData = new Tabulator("#table", {
            addRowPos: "top", //when adding a new row, add it to the top of the table
            cellEdited: cellEdited, //triggered when a user starts editing a cell
            columns: defineColumns(), //define the table columns
            data: tableData, //load row data from array
            history: true, //allow undo and redo actions on the table
            initialSort:[ {column:"application_id", dir:"asc"} ], //sort the data in the table
            layout: "fitColumns", //fit columns to width of table
            movableColumns: false, //allow column order to be changed
            pagination: "local", //paginate the data
            paginationSize: 20, //allow 20 rows per page of data
            reactiveData: true, //turn on data reactivity
            resizableRows: false, //allow row order to be changed
            rowClick: onRowClick, //rowClick callback is triggered when a user clicks on a row
            rowFormatter: rowFormatter, //alter each row of the table based on the data it contains
            selectable: 1, //make rows selectable (only 1 in this case)
            selectableCheck: selectableCheck, //check if the current row should be selectable
            selectablePersistence: false, //allow rolling selection
            tooltips: true //show tool tips on cells
        });


function getfieldsDescription() {

              const fieldsDescription = {
            active: { mandatory: true, editor: "select", select: ["true", "false"], default: "false" },
            code: { mandatory: true, editor: "input" },
            country: { mandatory: true, editor: "select", select: ["IND","GBR"], default: "IND" },            
            application_id: {}
        }

        return fieldsDescription;
    }



function addNewRow(newRowContent) {    	
        const id = 1;
        const fieldsDescription = getfieldsDescription();
        onAddingMode = true;

        if (! newRowContent) {
            newRowContent = {};
            for (var [fieldName, field] of Object.entries(fieldsDescription)) {
                newRowContent[fieldName] = field.default;
            }
        }

        newRowContent["id"] = id; // put the id at 1
        tabulatorData.addRow(newRowContent);
        tabulatorData.selectRow(id); // select row with id = 1

        let newRowComponent = tabulatorData.getRow(id); // get row component with id = 1
        isRowContentCorrect(newRowComponent);
    }

    function isRowContentCorrect(rowComponent) {
        let isRowContentCorrectBool = true;
        let fieldsDescription = getfieldsDescription();

        for (var [fieldName, fieldDescription] of Object.entries(fieldsDescription)) {
            let fieldCellComponent = rowComponent.getCell(fieldName);
            if (! isCellContentCorrect(fieldCellComponent, fieldName, fieldDescription)) isRowContentCorrectBool = false;
        }

        return isRowContentCorrectBool;
    }

    function isCellContentCorrect(cellComponent, fieldName, fieldDescription) {
        let fieldElement = cellComponent.getElement();
      ....
      ....
    }
```
Could you please assist in this issue.
Thanks
![TabulatorIssue](https://user-images.githubusercontent.com/45755588/56636265-d44cd780-6685-11e9-8628-5a2d4bb03089.JPG)

**Comment by Rodbjartson** [comment]
What version is this 4.2.0? Have you tried this with 4.2.5(latest release).
Not sure if this will help, but I know there have been  a number of bugs that were fixed in the latest patches.

**Comment by sahaneja** [comment]
Yes, tried with version 4.2.5 too. Got the same issue.

Thanks

**Comment by aklaver** [comment]
Could you create a jSFiddle or CodePen to illustrate?
In meantime, what are your columns?
What happens if you turn off reactiveData?

**Comment by olifolkerd** [comment]
This is happening because the cell you are trying to get is not yet defined.

Cells are only created when the row is first made visible, if it has not been made visible by the time you call your function the ***getCelll*** function will return false.

the ***addRow*** function returns a promise which lets you know when the row has been added to the table, this promise also resolves to pass you a row component so you could simplify your code:

```js
table.addRow(newRowContent)
.then(function(row){
    row.select();
    isRowContentCorrect(row);)
})
```

Bu as i say if the row is not visible on the screen then it will not yet have cell components.

Cheers

Oli :)

**Comment by sahaneja** [comment]
Thanks for your response. Yes the cell component is not created if the row is not on current page. May be this is how the API is designed to work. For my case, I used the function tabulatorData.setPage to first go to that page where the row is located and then perform further operations on it.

Regards,
Sahil
