### ISSUE TITLE
paste validation - tabulator-validation-fail class removed on unchanged invalid values

### ISSUE THREAD

**Issue by webtango** [olifolkerd/tabulator#2009]
**Describe the bug**
If a cell is marked as invalid by the paste validator, then you click in that cell, the red styling is removed even though the value is still invalid.

**Tabulator Info**
- Which version of Tabulator are you using? 4.2.5
- Post a copy of your construct object if possible so we can see how your table is setup

**Working Example**
Please include a JS Fiddle or Code Pen that demonstrates the problem, it is very hard to diagnose an issue from a simple description

[fiddle](https://jsfiddle.net/webchaos/gq8acdks/13/)
**To Reproduce**
1. Select and copy some data from an excel sheet
2. Paste into the table in the fiddle
3. Second cell in first row should be marked invalid
4. Click in cell
5. Do not change value
6. Click out of the cell

tabulator-validation-fail class is removed, text is normal again.

**Expected behavior**
The cell should stay red since the value is still invalid.
Column validator should be called even if the cell value does not change to see if it is still invalid.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS
 - Browser [e.g. chrome, safari] Chrome and FF
 - Version [e.g. 22] latest

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aklaver** [comment]
From what I see Tabulator is doing the correct thing and showing the validation/invalidation on the paste. I do not see a column validator on 'Value2', so I do not see how it would be called?

**Comment by olifolkerd** [comment]
That is working correctly,

Validators are only called if the value in the cell has changed otherwise it is treated as a cancel event.

Tabulaor allows invalid values to be set in the data, validators are only called when data is changed by the user.

Cheers

Oli :)
