### ISSUE TITLE
Table not redraw on mobile responsive collapsed layout

### ISSUE THREAD

**Issue by prateeks39** [olifolkerd/tabulator#2010]
I'm using tabulator responsive layout collapsed when I redrawing table it will not show all rows.
Step to reproduce for mobile view.
1.- Load table in hidden div.
2-  Now div will set display block.
3- check table it will show only first column values others will hidden.

The redraw function works well with out responsive collapsed but in responsive collapsed it won't work.

**Comment by tentus** [comment]
What version does this apply to? What OS/browser/etc have you tested this on?

Please include a JS Fiddle or Code Pen that demonstrates this problem.

**Comment by prateeks39** [comment]
[Tabulatortables.zip](https://github.com/olifolkerd/tabulator/files/3114917/Tabulatortables.zip)
Hi tentus,
thanks for your reply, I'm using React js and tabulator-tables.
pls check attached file.
step to reproduce:-
1.  Copy given code in react application setup.(mobile view).
2.  Load table on componentDidMount and div should be in hidden state at first.
3. Now click on show button and call table.redraw() function on componentDidUpdate.
4. Check responsive collapse not working. a horizontal scroll is there.

**Comment by olifolkerd** [comment]
Hey @prateeks39 

Please use the issue templates when creating an issue, we cannot help you if you do not provide the information we ask for to better explain your issue.

Please only post links to JS Filldes or Code Pens, we will not download entire websites to work with, it is impractical to go through and setup sites for every issue that comes up on these lists.

Cheers

Oli :)
