### ISSUE TITLE
How do i get pdf and xls blob from tabulator

### ISSUE THREAD

**Issue by ryhill** [olifolkerd/tabulator#2013]
Is it possible to get  PDF and xlsx blobs with version 4.2

**Comment by aklaver** [comment]
http://tabulator.info/docs/4.2/download#advanced-intercept

**Comment by ryhill** [comment]
That is when you trigger download. I wanted to get it like
table.getblob() or table.getPdfBlob() without triggering download.

**Comment by aklaver** [comment]
You are going to download it/ move it at some point aren't you?
If not what do you plan to do with the blob?
You could also look here:
https://github.com/olifolkerd/tabulator/blob/master/src/js/modules/download.js
and use that to create your own variation.

**Comment by takuy** [comment]
You can trigger a download, get the blob and return false. This will stop it from actually downloading but you can still get the data.

**Comment by Rodbjartson** [comment]
Inside tabulator constructor you can;

```
downloadReady: function (fileContents, blob) {
                    //fileContents - the unencoded contents of the file
                    //blob - the blob object for the download

                    //custom action to send blob to server could be included here

                   // sendEmailVB(blob);

                    window.open(window.URL.createObjectURL(blob));

                    return blob; //must return a blob to proceed with the download, return false to abort download
                },
```

**Comment by ryhill** [comment]
Thanks guys... return false helped
