### ISSUE TITLE
Table data loss when moving between column filters

### ISSUE THREAD

**Issue by ac3112** [olifolkerd/tabulator#2014]
Using the example found here (http://tabulator.info/examples/4.2#filter-header), if you select the min value input on the progress column, then move to the name filter for example, the entire table data is lost.

Currently using Chrome version 73.0.3683.103

**Comment by aklaver** [comment]
Using:
Chrome 74.0.3729.108

The problems I see are:
1)  That the second input has a placeholder of Min, when it should actually be Max if you follow the code in minMaxFilterEditor. 
2) The comparison code in minMaxFilterFunction is looking for !=" " or a number. Looks like it may be hitting a bug if the search value is null.

**Comment by ac3112** [comment]
@aklaver I was using this site as an example, as i've used that as a base. Both the issues you've described have been fixed on my local version, but still produce them same issue as I originally described. Local code below:

`             
      var timestampFilterEditor = function(cell, onRendered, success, cancel, editorParams){
                var end;

                var container = document.createElement("span");

                //create and style inputs
                var start = document.createElement("input");
                start.setAttribute("type", "datetime-local");
                start.style.padding = "4px";
                start.style.width = "50%";
                start.style.boxSizing = "border-box";

                start.value = cell.getValue();

                function buildValues(){
                    success({
                        start:start.value,
                        end:end.value,
                    });
                }

                function keypress(e){
                    if(e.keyCode == 13){
                        buildValues();
                    }

                    if(e.keyCode == 27){
                        cancel();
                    }
                }

                end = start.cloneNode();

                start.addEventListener("change", buildValues);
                start.addEventListener("blur", buildValues);
                start.addEventListener("keydown", keypress);

                end.addEventListener("change", buildValues);
                end.addEventListener("blur", buildValues);
                end.addEventListener("keydown", keypress);


                container.appendChild(start);
                container.appendChild(end);

                return container;
            }

      function timestampFilterFunction(headerValue, rowValue, rowData, filterParams){
                //headerValue - the value of the header filter element
                //rowValue - the value of the column in this row
                //rowData - the data for the row being filtered
                //filterParams - params object passed to the headerFilterFuncParams property

                var format = filterParams.format || "DD MMMM YYYY HH:mm:ss";
                var start = moment(headerValue.start);
                var end = moment(headerValue.end);
                var value = moment(rowValue, format);

                if(rowValue){
                    if(start.isValid()){
                        if(end.isValid()){
                            return value.isSameOrAfter(start) && value.isSameOrBefore(end)
                        }else{
                            return value.isSameOrAfter(start)
                        }
                    }else{
                        if(end.isValid()){
                            return value.isSameOrBefore(end)
                        }
                    }
                }

                return false; //must return a boolean, true if it passes the filter.
            }`

**Comment by aklaver** [comment]
Hmm, datetimes are involved that complicates things. Without an example with the date data you are using it will be hard to determine what is going on.

**Comment by olifolkerd** [comment]
Hey @aklaver 

thanks for the headsup on the error with the placeholders in the example, i will fix that on the website in the 4.3 update

Cheers

Oli :)
