### ISSUE TITLE
Filtered rows lost on custom filter

### ISSUE THREAD

**Issue by ac3112** [olifolkerd/tabulator#2015]
Using the example here (http://tabulator.info/examples/4.2#filter-header), if you enter a number in the min filter for the progress column, say 6 for example, the Mary May line should be filtered out, but isn't until you leave the input. Pressing enter will temporarily filter the data, but as soon as you let go of the enter key, the data becomes unfiltered again.

Currently using Chrome 73.0.3683.103

**Comment by aklaver** [comment]
From the code for minMaxFilterEditor:

start.addEventListener("change", buildValues);
start.addEventListener("blur", buildValues);
start.addEventListener("keydown", keypress);

where buildValues is the function that sets the values.

https://www.w3schools.com/jsref/event_onchange.asp
"The difference is that the oninput event occurs immediately after the value of an element has changed, while onchange occurs when the element loses focus, after the content has been changed. "

If you use the spinner it will do as you want.
