### ISSUE TITLE
Can't bind enter key (keycode 13)

### ISSUE THREAD

**Issue by rtman** [olifolkerd/tabulator#2016]
Hi @olifolkerd 

Great job with tabulator, it's really awesome!

I think I may have found a bug as I'm unable to bind the enter key (keycode 13). I can bind other keys successfully though. 

Please have a look at this [demo fiddle](https://jsfiddle.net/rtman/5htm98u4/3/), the first column is editable and where I would like to be navigating down on enter. As far as I know the documentation doesn't say you can't bind the enter key, so hopefully I haven't missed something here.

Thanks

**Tabulator Info**
- Which version of Tabulator are you using?
4.2.5

**Expected behavior**
The enter key on web and mobile would be bound to a navigation direction.

 - OS: 
win 10
chrome
Version 73.0.3683.103

**Comment by aklaver** [comment]
I going to guess that this has to do with the input editor catching the enter first. A work around is probably going to involve building a custom editor:

http://tabulator.info/docs/4.2/edit#edit-custom

Not sure how at the moment.

**Comment by rtman** [comment]
@aklaver 

Hey thanks for your thoughts, I thought that might be the case but I'm also not sure how to fix it at the moment.

I did see [#1093](https://github.com/olifolkerd/tabulator/issues/1093) where @olifolkerd mentions:

> You can easily do this yourself using the Cell Component passed into the editor.
> 
> you could watch for the enter key and then trigger the cell.nav().next() function on it.

But again I'm not sure how to do this at the moment or if this is even still valid as it is from may 2018. But I will look into it.

**Comment by aklaver** [comment]
I forked your fiddle:
https://jsfiddle.net/aklaver/rqbe5cam/19/
Using some suggestions from here:
https://stackoverflow.com/questions/24028225/addeventlistener-keypress-wont-work
I found out that using an empty eventerHandler() for the keypress in a custom editor achieved what you want. Test and see if it works for you.

**Comment by rtman** [comment]
Man! Well done, that works great. I just tested it on desktop and mobile, both working great. Wish I could send you a tip or something!
