### ISSUE TITLE
Textarea is not resizing (multiline) automatically

### ISSUE THREAD

**Issue by fwidtmann** [olifolkerd/tabulator#2017]
**Describe the bug**
If i edit an cell (textarea) with a long text, its multline but the cell is not changing the size. I need first to redraw the table. 
The issue with this workaround, if i type a text, and want to jump into the next cell with key tabulator, after the redraw the focus is lost.

**Tabulator Info**
tabulator-rails (1.1.2)

**Comment by Rodbjartson** [comment]
Tabulator rails?

**Comment by fwidtmann** [comment]
> Tabulator rails?

https://github.com/js-rails/tabulator-rails

**Comment by Rodbjartson** [comment]
Never heard about, so I cannot help you sorry

**Comment by fwidtmann** [comment]
its not about that rails gem https://github.com/js-rails/tabulator-rails

its about that the height of the textarea cell is not automatically resizing if multiline.
in the screenshot you can see that the text is multiline, but the height of the cell is not adjusting
<img width="620" alt="Screenshot 2019-04-26 at 10 48 53" src="https://user-images.githubusercontent.com/671591/56795514-ec049700-6810-11e9-822f-e21f5c2bd034.png">

**Comment by olifolkerd** [comment]
Hi @fwidtmann 

If the cell dosnt have a formatter of ***textarea*** it will not resize vertically to fit its contents.

I would also raise an note of caution that that library appears to be using version 4.1.2 of Tabulator and we are currently on version 4.2.5 and about to move to 4.3

The [Formatter Documentation](http://tabulator.info/docs/4.2/format) explains more about how to setup your table.

Cheers

Oli :)

**Comment by fwidtmann** [comment]
@olifolkerd thx for your reply - but i already used **textarea**
i just got the newest version and example from github:
index.html

```
var tabledata = [
 	{id:1, lorem:"Oli Bob "}
 ];

//Build Tabulator
var table = new Tabulator("#example-table", {
    data:tabledata, //assign data to table
    height:"311px",
    layout:"fitColumns",
    columns:[
    {title:"Line Wraping", field:"lorem" ,formatter:"textarea",editor:"input"}
    ],
});
```

when im now clicking in the field and type a long text, it loos like:
<img width="364" alt="Screenshot 2019-04-29 at 09 35 21" src="https://user-images.githubusercontent.com/671591/56881881-231db700-6a62-11e9-9852-dc92802a90ca.png">


so its a normal behavior or im doing something wrong?

**Comment by olifolkerd** [comment]
If you use Tabulator outside of the tabulator-rails project does it work correctly, because the image you are showing is definitely broken and i cannot replicate that with raw Tabulator.

Cheers

Oli :)

**Comment by fwidtmann** [comment]
```
<!DOCTYPE html>
<html lang="de">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="dist/css/tabulator.min.css" rel="stylesheet">
<script type="text/javascript" src="dist/js/tabulator.min.js"></script>
    <title>Titel</title>
  </head>
  <body>
<div id="example-table"></div>
  </body>
    <script>

    	//define some sample data
 var tabledata = [
 	{id:1, lorem:"Oli Bob "}
 ];

//Build Tabulator
var table = new Tabulator("#example-table", {
	data:tabledata, //assign data to table
    height:"311px",
    layout:"fitColumns",
    columns:[
    {title:"Line Wraping", field:"lorem" ,formatter:"textarea",editor:"input"}
    ],
});
  </script>
</html>
```

thats the full index.html

**Comment by olifolkerd** [comment]
@fwidtmann 

im afraid i cant replicate your issue at all it works correctly for me.

There appear to be a load of garbage characters appearing after the text value on your browser which is rather odd. i would suggest there is probably something corrupted in your source files. 

Try downloading the source files again.

Cheers

Oli :)

**Comment by fwidtmann** [comment]
> @fwidtmann
> 
> im afraid i cant replicate your issue at all it works correctly for me.
> 
> There appear to be a load of garbage characters appearing after the text value on your browser which is rather odd.

lol no i typed this! if there is the text "Oli Bob" like in tabledata, than i CLICK in the CELL and EDIT the value with a long text (garbage characters), the text should be so long that it goes MULTILINE, but the CELL DONT GROW automatically on HEIGHT and its looks like in the screenshot. It ONLY GROW if i reload the side or call method redraw

**Comment by fwidtmann** [comment]
@olifolkerd do you have an example of editing an textarea field?

**Comment by angela318** [comment]
Is this being resolved yet? As I still see the issue in my project

**Comment by angela318** [comment]
This issue happen always when it involves some window size change. It happens everytime. when changing from landscape to portrait mode on phone.

**Comment by olifolkerd** [comment]
Hey @angela318 

This issue was closed last year, if you feel you are still having a problem please create an issue using the [Bug Reporting Template](https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Possible+Bug&template=bug_report.md&title=) filling in all the requested information and providing a JS Fiddle or Code Pen that demonstrates the problem

Cheers

Oli :)
