### ISSUE TITLE
make _children not selectable in data tree

### ISSUE THREAD

**Issue by yeonggyulim** [olifolkerd/tabulator#2018]
**Is your feature request related to a problem? Please describe.**
I'm using Tabulator and I'm frustrated that I couldn't figure out how to make _children not selectable in data tree.

**Describe the solution you'd like**
I want the parent rows to be selectable, but children rows not to be selectable.
In the screen shot, I need adb rows to be selectable, and the other rows(name, gender, grade) to be not selectable.

In addition, I hope the parent(adb) row to be collapsed all the columns.
Can it be added?

**Additional context**

![question](https://user-images.githubusercontent.com/36085009/56790126-b1195800-683e-11e9-9d9f-b8858f259ae2.PNG)

**Comment by Rodbjartson** [comment]
Can you possibly create a callback that returns false so that you are not allowed to select the children?

```
selectableCheck: function (row) {

                        var selectedRows = $("#PO-table").tabulator("getSelectedRows");
                        if (selectedRows.length < 18)
                        {
                            
                            
                                return false;
                            
                        }
                                             
                        
                        return true; //alow selection of rows where the age is greater than 18
                    },
```

**Comment by takuy** [comment]
As @Rodbjartson described, you should be able to use the selectableCheck callback to see if the row has a parent, using the `row.getTreeParent();` function. It will return false if the row does not have a parent.
