### ISSUE TITLE
When building ajax params, adding them to url will always start with '?'

### ISSUE THREAD

**Issue by PeToEEA** [olifolkerd/tabulator#2019]
Just one simple thing I noticed is that when tabulator is appending parameters to ajaxUrl (like page or size) it will add them always starting with '?' which is not okay if the ajaxUrl already has some parameters.

Issue is in this part where this function is defined:

Ajax.prototype.defaultURLGenerator

I made a simple not so very nice quickfix to solve this:

if(url.indexOf("&") > -1) {
      url += "&" + this.serializeParams(params);
   } else {
      url += "?" + this.serializeParams(params);
   }

//instead of just

 url += "?" + this.serializeParams(params);

**Comment by aklaver** [comment]
There is ajaxURLGenerator:
http://tabulator.info/docs/4.2/data#ajax-url

for overriding the default.
