### ISSUE TITLE
Custom text on Filter Text

### ISSUE THREAD

**Issue by ilogic** [olifolkerd/tabulator#202]
Hello. I'm from Spain, and i'm testing this fantastic plugin.

When I localized my table, all text are correctly changed to "es-es" (using setLocale) but "Filter Colum...". I can change it manually, but the right way would be to include this label into the langs array... Can you improve it? 

Thanks!!

PS: Sorry for my poor english. This is my first issue on GitHub too...

**Comment by olifolkerd** [comment]
Hey,

Great idea! i will get the change in tommorow evening!

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey,

Sorry for the delay in getting back to you, had a busy month at work!

I have just added header filter localization to the repo:

```js
$("#example-table").tabulator({
  langs:{
    "es-es":{
      "headerFilters":{
        "default":"Filter Column...", //default header filter placeholder text
        "columns":{
          "name":"Filter Name...", //replace default header filter text for column name
        }
      }
    }
  },
});
```

Full details of this feature can be found [here](http://olifolkerd.github.io/tabulator/docs/#localization)

Cheers

Oli
