### ISSUE TITLE
FR: move row to new parent

### ISSUE THREAD

**Issue by ray007** [olifolkerd/tabulator#2020]
I have a table showing alarm data. When a new alarm arrives, it often supersedes an existing alarm, which I then would like to show as child of the new alarm.

**My wish**
The `moveRow` method of the tabulator instance has a 3rd parameter for before/after.
Consider a 3rd option for it saying "asChild".

**What I currently do**
I currently do this by deleting the old row and adding a new row as child of the new arrived alarm row.

**Comment by aklaver** [comment]
Could you use:

http://tabulator.info/docs/4.2/release#tree
"Updating

When you use the update function on a row component to update the _children array it will now redraw the rows children to match the new data"

**Comment by ray007** [comment]
I'm already using `updateRow` with `_children` to get the row into its new place.
But I still have to delete it first from its old position where it didn't have a parent, right?
It also seemed unneeded to rerender all children of its new parent for adding one row.

Btw: is there an api-option I missed to add a new row into its sorted position?
I currently always call `setSort` after adding new rows...

**Comment by aklaver** [comment]
The way I think of the children, at present, is that they are attributes of the parent row not rows in their own right. That means the work around you are using is best practices at the moment.

Re: adding new rows(am assuming you are talking about parent rows). The only option I know of is the third option to addRow, that is the row index to place the new row either above or below:

http://tabulator.info/docs/4.2/update#addrow

That would still some sort of lookup ahead of time to find the target row.
