### ISSUE TITLE
hello! can anybody help me with adding (installing) tabulator to laravel 5?

### ISSUE THREAD

**Issue by iBek23** [olifolkerd/tabulator#2021]
i'm new to laravel and js and having problem with adding tabulator js library to laravel 5.4.
1. i did NPM installation with following command: **npm install tabulator-tables --save**
2. now i don't have any idea where to add: **var Tabulator = require('tabulator-tables');**

**Comment by tentus** [comment]
`/resources/assets/js/bootstrap.js`

I'd recommend referencing how axios/jquery/etc is required.

**Comment by iBek23** [comment]
> 
> 
> `/resources/assets/js/bootstrap.js`
> 
> I'd recommend referencing how axios/jquery/etc is required.

thanks for reply!!! but, maaan i'm stupid. i need instructions.

**Comment by olifolkerd** [comment]
Hey @iBek23 

In your app.js you need to add a line:
```js
window.Tabulator = require('tabulator-tables');
```

I hope that helps,

Cheers

Oli :)
