### ISSUE TITLE
Add page button title to pagination locale options.

### ISSUE THREAD

**Issue by funkindy** [olifolkerd/tabulator#2022]
Current locale options provide great customization opportunity for users. My tiny suggestion is to also add the "Show page #" title, which appears on page number buttons to localization options.

Since we now have `pagination|page_size` this new can be something like `pagination|page_num`

![image](https://user-images.githubusercontent.com/17568549/56801004-da81b600-6835-11e9-8787-6afa8989b9dd.png)

**Comment by olifolkerd** [comment]
Hey @funkindy 

There is actually a pull request for this sort of functionality already, wi will be reviewing it for the 4.3 release.

Cheers

Oli :)

**Comment by funkindy** [comment]
Oh, ive missed it. Thank a lot Oli!
