### ISSUE TITLE
.

### ISSUE THREAD

**Issue by dota2Pro** [olifolkerd/tabulator#2024]

**Comment by olifolkerd** [comment]
Hey @dota2Pro 

Thanks for getting in touch.

Could you explain what you mean by "Solution for angular setup demo", is there a problem with the current one, if so could you go into more detail about what the issue is and how your solution fixes it.

Cheers

Oli :)

**Comment by dota2Pro** [comment]
@olifolkerd sorry about being vague, I created a demo for the code as per documentation, https://stackblitz.com/edit/angular-mssvrt and you can see tabulator doesn't render, maybe it used to work in previous versions of angular I am not sure the demo link has the latest 7.2.5 . this is from TCantele's comment in this [thread](https://github.com/olifolkerd/tabulator/issues/1509#issuecomment-461929722)
Basically we should initialize Tabulator  on Angular's ngOnInit() lifecycle hook rather than redrawing the table every time on ngOnChanges()

Detailed Steps:
_____________________________________________________________________
After pulling in the Tabulator source to your project using one of the methods in the Install Guide create a component as follows, in this example we will be saving the code(Typescript) for the component in the tabulator-tables.component.ts file

**Typescript in tabulator-tables.component.ts**

```

import { Component, Input, OnInit } from '@angular/core';
import Tabulator from 'tabulator-tables';

export interface IPerson {
  id: number,
  firstName: string,
  lastName: string,
  state: string
} // Use Interface for datatypes in Typescripts

@Component({
  selector: 'app-tabulator-table',
  template: `<div id="tabulator-div"></div>`, // Html for Tabulator
  styles: []
})
export class TabulatorTableComponent implements OnInit {
  people: IPerson[] = [];
  columnNames: any[] = [];
  myTable: Tabulator;

  ngOnInit() {
    this.people = [
      { id: 1, firstName: "John", lastName: "Smith", state: "Ohio" },
      { id: 2, firstName: "Jane", lastName: "Doe", state: "Iowa" },
      { id: 3, firstName: "Bill", lastName: "Great", state: "Hawaii" },
      { id: 4, firstName: "Ted", lastName: "Adventure", state: "Arizona" }
    ];
    this.columnNames = [
      { title: "Id", field: "id" },
      { title: "First Name", field: "firstName" },
      { title: "Last Name", field: "lastName" },
      { title: "Location", field: "state" }
    ];
    this.myTable = new Tabulator("#tabulator-div", {
      height: 205, // set height of table (in CSS or here), this enables the Virtual DOM and improves render speed dramatically (can be any valid css height value)
      data: this.people, //assign data to table
      layout: "fitColumns", //fit columns to width of table (
      columns: this.columnNames
    });
  }
}

```
**CSS**

Include Tabulator CSS in Angular.json to load Tabulator Styles
```
    "styles": [
        "./node_modules/tabulator-tables/dist/css/tabulator.min.css"
    ],
```
working [demo](https://stackblitz.com/edit/angular-ckujf9)
