### ISSUE TITLE
automatic AJAX events for callbacks.

### ISSUE THREAD

**Issue by takuy** [olifolkerd/tabulator#2025]
It'd be neat if we could define a URL endpoint for callbacks instead of just functions:
```js
table = new Tabulator(..., {
    rowAdded: {
        ajaxURL:  "https://myapi.local",
        ajaxMethod: "POST",
        ajaxAdditionalParams: {"hi": "wow"}, // the request would send the original data to the callback and any additional params you define
        ajaxCallback: function(row, ajaxData) { //this would be called with both the original data sent to post and the response of the ajax call
        },
    },
});
```

**Comment by olifolkerd** [comment]
Hey @takuy 

Im afraid i dont follow you at all, Tabulator already has a fully customizable ajax system.

what do you mean a URL endpoint for callbacks?

Cheers

Oli :)

**Comment by takuy** [comment]
Unless I'm missing something, Tabulator only allows the usage of AJAX to pull or query data. If you add a row to a table, the server isn't notified unless you do your own AJAX call. This can get messy. If you allow the use of an Ajax setup object (similar to the params in the table constructor) this could make offloading somethings to the server easier. Like, a cell edited validation function for example.

**Comment by olifolkerd** [comment]
Ahh I see what you mean now.

For most usage cases it wouldn't be practical, any callback with a return is generally designed to wkrk synchronously therefore prohibiting the use of async methods such as Ajax.

Validation is a perfect example in fact.validation is triggered when focus is lost in a cell and in most case focus is passed to another cell in the process. This means that the validation process must be completed synchronously before the focus event shows the editor in the next cell to be triggered. So there is no time for an Ajax request.

Most other callbacks are notifications that a specific event has happened. These then pass in component objects that allow the users access to a large amount of info regarding the event. There is no meaningfull way to determine which bit of information a user might need to get out of a component, not a sensible way to serialise it all to send over http.

There are also a great number of ways that developers like to send data back to their servers and to cover then all off would be a huge and unnecessary undertaking.

The callbacks allow you to trigger any functionality you like. And if you need to make an Ajax request when a row is added you can do that yourself in any way you like, using your Ajax library of choice and formatting the data how you need it to be formatted. Which is exactly the point of the callbacks.

Thank you for your suggestion, but at this point it is not something I would be looking to add to Tabulator

Cheers

Oli :)
