### ISSUE TITLE
wrong behavior on titleFormatter in column definition

### ISSUE THREAD

**Issue by amiriahmad72** [olifolkerd/tabulator#2026]
**Describe the bug**
When using titleFormatter in column definition the returned contents added to column.element instead of title element.

**Tabulator Info**
- tabulator-4.2.5

**Expected behavior**
returned contents add to title element

**Comment by amiriahmad72** [comment]
Hi Oli.
my suggestions: `Column.prototype._formatColumnHeaderTitle` function use `el` instead of `this.element`

thank u :)

**Comment by olifolkerd** [comment]
Hey @amiriahmad72 

Good spot!, i will include a fix for this in tonights patch release.

Thanks for the feedback

Cheers

Oli :)
