### ISSUE TITLE
Set different colors for different column groups

### ISSUE THREAD

**Issue by kreamas** [olifolkerd/tabulator#2028]
Hi.

I've built a table that has different column groups in this way:

          var columnaskpi = [

            {title: 'NIVEL', field: 'NIVEL', visible:false},
            {title: 'EMPLOYEE', field: 'ITEM', cssClass:'EMPLEADO'},

            {title:  "VENTAS", cssClass: 'Ventas', columns: [

              {title: 'CUOTA', field: 'CUOTAS', cssClass:'Ventas',  formatter:'money', formatterParams:{precision:'0'}},
              {title: 'VENTA', field: 'VENTA', cssClass:'Ventas', formatter:'money', formatterParams:{precision:'0'}},
              {title: 'COB. CUOTA', field: 'ALCANCE', cssClass:'Ventas', formatter:'money', formatterParams:{precision:'2'}},

            ],},

            {title:  "VISITAS", cssClass: 'Calls', columns: [

              {title: 'OBJ. VISITA', field: 'CALLS', cssClass:'Calls',  formatter:'money', formatterParams:{precision:'0'}},
              {title: 'VISITA', field: 'VISITAS', cssClass:'Calls', formatter:'money', formatterParams:{precision:'0'}},
              {title: 'COB. CALL', field: 'COB_CALLS', cssClass:'Calls',  formatter:'money', formatterParams:{precision:'2'}},

            ],},

            {title:  "PERFIL", cssClass: 'RX', columns: [

              {title: 'Decrece', field: 'Decrece', cssClass:'RX',  formatter:'money', formatterParams:{precision:'0'}},
              {title: 'Mejora', field: 'Mejora', cssClass:'RX',  formatter:'money', formatterParams:{precision:'0'}},
              {title: 'Nuevo', field: 'Nuevo', cssClass:'RX',  formatter:'money', formatterParams:{precision:'0'}},
              {title: 'Mantiene', field: 'Mantiene', cssClass:'RX',  formatter:'money', formatterParams:{precision:'0'}},

            ],},

          ];

I've set up the colors of columns at the lowest level on the table, by assigning them a cssClass and then changing its color this way:

          $("#tabla1 .EMPLEADO").css({"background-color":"#006332", "color":"white", "text-align": "center"});
          $("#tabla1 .Ventas").css({"background-color":" #2a5858", "color":"white", "text-align": "center"});
          $("#tabla1 .Calls").css({"background-color":"#923332", "color":"white", "text-align": "center"});
          $("#tabla1 .RX").css({"background-color":"#002856", "color":"white", "text-align": "center"});

However I would like to set the group header with the same color of their children.

Is it possible?

Thanks in advance.

**Comment by olifolkerd** [comment]
Hey @kreamas 

Thanks for getting in touch, at the moment this isnt possible, but i like the idea.

I will add it to the roadmap for a later release.

Cheers

Oli :)

**Comment by adamxi** [comment]
I have come across similar need where i need to assign a class to a column group.
As the **cssClass** property is not used by tabulator when constructing column groups, i added to following to the **Column.prototype._buildGroupHeader** function:

```
var self = this,
    def = self.definition;

if (def.cssClass) {
    var classeNames = def.cssClass.split(" ");
    classeNames.forEach(function (className) {
        self.element.classList.add(className);
    });
}
```

Tabulator will now use the **cssClass** property on the column definition, when constructing column groups.

**Comment by olifolkerd** [comment]
Hey @adamxi 

I have pushed an update for this to the 4.5 branch that will be released in a few weeks.

Cheers

Oli :)
