### ISSUE TITLE
Empty data on download

### ISSUE THREAD

**Issue by mazzanti** [olifolkerd/tabulator#2029]
The downloaded file have empty data. But correct columns. 

In module download.js/tabulator.js v4.2.5 method Download.prototype.processData:

When downloading a file if groupBy is an empty array, "[]", the value of this.config.rowGroups is true. Groups is length 0 so the groups.forEach will push no data!

I suggest to handle the empty array parameter in groupBy.
Thank you for great job.

**Comment by aklaver** [comment]
Have you tried?:
http://tabulator.info/docs/4.2/download#advanced-config
"Download Configuration

By default Tabulator includes column headers, row groups and column calculations in the download output.

You can choose to remove column headers groups, row groups or column calculations from the output data by setting the values in the downloadConfig option in the table definition:"
