### ISSUE TITLE
Scroll Syncing between tables

### ISSUE THREAD

**Issue by ISNIT0** [olifolkerd/tabulator#203]
Perhaps specify a global 'scrollId' in table config, then whenever anything with that id is scrolled, everything else scrolls with it.

**Comment by olifolkerd** [comment]
Hey,

Thanks for getting in touch. With an appropriate event binding you should be able to do that yourself:

```js
$("#example-table-source").on("scroll", ".tabulator-tableHolder", function(){
    var source = $(this);
     $("#example-table-destination").scrollLeft(source.scrollLeft()) //match left scroll
    .scrollTop(source.scrollTop()) //match top scroll
    .scroll() //trigger scroll event on table holder to trigger update in rest of table ui.
});
```
If you create the same binding for each table they should mirror eachothers scrolls.

Let me know if that helps.

Cheers

Oli
