### ISSUE TITLE
downloadTitle does not  work for column group

### ISSUE THREAD

**Issue by amiriahmad72** [olifolkerd/tabulator#2030]
**Describe the bug**
DownloadTitle option does not  work for column group.

**Tabulator Info**
- tabulator 4.2.7

**Working Example**
[jsfiddle example code](https://jsfiddle.net/amiriahmad72/L9bwxm0z/45/)
compare download title with column group and without it.

**Comment by amiriahmad72** [comment]
I see another problem right now. The title of first column in second layer is empty when using column group.

![image](https://user-images.githubusercontent.com/23294400/56950137-0361be00-6b4a-11e9-9764-90494258338b.png)

**Comment by nie7321** [comment]
I think I'm having the same problem -- `downloadTitle` is not being respected for my CSV export for the columns that are in a group.

**Comment by olifolkerd** [comment]
Hey @amiriahmad72 

This isnt a bug so much as a missing feature, at the moment that option is not available for column groups, the [Column Documentation](http://tabulator.info/docs/4.2/columns#groups) explains which options are available for column groups.

I will add it to the roadmap for the next release to add this.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
This has been merged into the master branch and will be included in this weekends 4.3 release.

Cheers

Oli :)

**Comment by amiriahmad72** [comment]
Well done :)
