### ISSUE TITLE
Firefox-specific navigation error when tabbing through editor cells

### ISSUE THREAD

**Issue by tentus** [olifolkerd/tabulator#2032]
**Describe the bug**
When tabbing through editor cells, Firefox will prematurely think it has run out of elements to cycle through. This means that it will put focus on outside elements rather than the next cell, or barring outside elements it will prematurely set focus to the first cell.

**Tabulator Info**
- version 4.2.7

**Working Example**
https://jsfiddle.net/89yb1k5n/

**To Reproduce**
1. In firefox, go to the fiddle above
2. Click on one of the middle columns in the middle of the table
3. Tab a few times, enough that you should have gotten to the same column on the next row

**Expected behavior**
Each editable column should be tabbed through in each row.

**Desktop (please complete the following information):**
 - OS: macOS 10
 - Browser: Firefox
 - Version: 66.0.3

**Addendum**
This is slightly off-topic, but while we're on the subject of bindings/tabbing/navigation, would you be interested in a keybinding example for the examples page? It's slightly odd to go looking for a baseline for my fiddle and find no references to the navigation feature on that page.

**Comment by aklaver** [comment]
The problem actually seems to be with the number editor. Change the editor for the progress field from number to input and the tabbing works. Best guess is it has to do with the below from 4.2.6 release:
"fixed the blur event on the number editor that regressed in the 4.2.4 release, the editor should now work on Firefox again"

**Comment by tentus** [comment]
Mmm, good catch @aklaver that is exactly the case.

**Comment by olifolkerd** [comment]
Dam Firefox, it is a tricky bugger!

Thanks for the headsup, i will look into this for the next patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Im closing this issue as it appears to have be resolved by a later release.

Cheers

Oli :)
