### ISSUE TITLE
Can't get links to download all files

### ISSUE THREAD

**Issue by Chris-Dees** [olifolkerd/tabulator#2033]
So my problem is that I need all links in the table to force download. This is for an intranet site that I am building for work. I added the target:"download" and that works for mp3 but not for .wav files. 

I added this to the end of my page to modify the links:
        $("#selection a").attr("download","");
Again, this works for the links that come up in the table but not the ones that are created on the fly whey I change pages. Below is what it looks like on the "working" link.

When I click the link for this one, Chrome automatically downloads it.
`<a href="uploads/SVU/2019/2019-00019831/Primary/File_1_2019-00019831 L1271.wav" download="">File_1_2019-00019831 L1271.wav</a>`

When I use the target: "download" it looks like this but does not work for the .wav files:
`<a href="uploads/SVU/2019/2019-00019831/Primary/File_1_2019-00019831 L1271.wav" target="download">File_1_2019-00019831 L1271.wav</a>`

Here is my table declaration:

let table = new Tabulator("#selection",{
            height:"320px",
            layout:"fitColumns",
            groupBy:"caseNum",
            movableRows:true,
            pagination:"remote",
            columns:[
                {title:"Case Number", field:"caseNum",sorter:"string"},
                {title:"Case Type", field:"caseType",sorter:"string"},
                {title:"File", field:"webURL",formatter:"link",id:"webURL",formatterParams:{
                    labelField:"new_fileName",
                        urlPrefix: "",
                        urlField:"webURL",
                    }},
                {title:"Notes", field:"notes",sorter:"string"},
                {title:"Date Uploaded", field:"upload_date_time.date",formatter:"datetime",formatterParams:{
                    inputFormat:"YYYY-MM-DD",
                    outputFormat:"MM/DD/YYYY",
                    invalidPlaceholder:"(invalid date)",
                    }},

            ],
        });

        table.setData(resultsArray).then(function(){}).catch(function(error){console.log(error)});

![Capture](https://user-images.githubusercontent.com/17259265/57032850-4e96d200-6c19-11e9-89fc-74e0d5c3c928.PNG)

**Comment by olifolkerd** [comment]
at the moment you would need to use a custom formatter to achieve this as the target property is not the same as setting the download attribute.

I will add it to the roadmap to add this feature in the next release.

Cheers

Oli :)

**Comment by Chris-Dees** [comment]
Any idea how the custom formatted would look? I played around with formatters but couldn’t get it to work right.

Sent from my iPhone

On May 8, 2019, at 16:08, Oli Folkerd <notifications@github.com<mailto:notifications@github.com>> wrote:


at the moment you would need to use a custom formatter to achieve this as the target property is not the same as setting the download attribute.

I will add it to the roadmap to add this feature in the next release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
@Chris-Dees you can copy the existing formatter and add the ***download*** attribute:

```js
    function(cell, formatterParams, onRendered){
		var value = cell.getValue(),
		urlPrefix = formatterParams.urlPrefix || "",
		label = this.emptyToSpace(value),
		el = document.createElement("a"),
		data;

               el.setAttribute("download", true); //make the link a download link

		if(formatterParams.labelField){
			data = cell.getData();
			label = data[formatterParams.labelField];
		}

		if(formatterParams.label){
			switch(typeof formatterParams.label){
				case "string":
				label = formatterParams.label;
				break;

				case "function":
				label = formatterParams.label(cell);
				break;
			}
		}

		if(formatterParams.urlField){
			data = cell.getData();
			value = data[formatterParams.urlField];
		}

		if(formatterParams.url){
			switch(typeof formatterParams.url){
				case "string":
				value = formatterParams.url;
				break;

				case "function":
				value = formatterParams.url(cell);
				break;
			}
		}

		el.setAttribute("href", urlPrefix + value);

		if(formatterParams.target){
			el.setAttribute("target", formatterParams.target);
		}

		el.innerHTML = this.emptyToSpace(this.sanitizeHTML(label));

		return el;
	}
```

 I hope that helps,

Cheers

Oli :)

**Comment by Chris-Dees** [comment]
Thank you Oli very much. When I get to work tomorrow I will try this.

Sent from my iPhone

On May 20, 2019, at 17:32, Oli Folkerd <notifications@github.com<mailto:notifications@github.com>> wrote:


@Chris-Dees<https://github.com/Chris-Dees> you can copy the existing formatter and add the download attribute:

    function(cell, formatterParams, onRendered){
                var value = cell.getValue(),
                urlPrefix = formatterParams.urlPrefix || "",
                label = this.emptyToSpace(value),
                el = document.createElement("a"),
                data;

               el.setAttribute("download", true); //make the link a download link

                if(formatterParams.labelField){
                        data = cell.getData();
                        label = data[formatterParams.labelField];
                }

                if(formatterParams.label){
                        switch(typeof formatterParams.label){
                                case "string":
                                label = formatterParams.label;
                                break;

                                case "function":
                                label = formatterParams.label(cell);
                                break;
                        }
                }

                if(formatterParams.urlField){
                        data = cell.getData();
                        value = data[formatterParams.urlField];
                }

                if(formatterParams.url){
                        switch(typeof formatterParams.url){
                                case "string":
                                value = formatterParams.url;
                                break;

                                case "function":
                                value = formatterParams.url(cell);
                                break;
                        }
                }

                el.setAttribute("href", urlPrefix + value);

                if(formatterParams.target){
                        el.setAttribute("target", formatterParams.target);
                }

                el.innerHTML = this.emptyToSpace(this.sanitizeHTML(label));

                return el;
        }

I hope that helps,

Cheers

Oli :)
