### ISSUE TITLE
dateEditor

### ISSUE THREAD

**Issue by UnsterblichMedic** [olifolkerd/tabulator#2034]
Using Tabulator 4.2.7.  I want my start and end cell to use the custom editor dateEditor that is depicted in the documentation and examples.  I cannot get it to work.  I have gone through the documentation, examples, and searched for an answer.  Nothing seems to work for me.  I have included a JSFiddle that demonstrates the start and end date column setup to use the custon dateEditor.  When you click the cell, nothing happens.  I would like the calendar to popup to select a date as the examples show.

https://jsfiddle.net/s83w5zru/1/

**Comment by aklaver** [comment]
I have not gone through all the code in the Fiddle, but the first thing I noticed is that moment.js is not being imported.  
It is needed for the editor:
http://tabulator.info/docs/4.2/edit#edit-custom
editor.value = moment(cell.getValue(), "DD/MM/YYYY").format("YYYY-MM-DD")

**Comment by dota2Pro** [comment]
did you get a chance to search on stackoverflow ?

> Using Tabulator 4.2.7. I want my start and end cell to use the custom editor dateEditor that is depicted in the documentation and examples. I cannot get it to work. I have gone through the documentation, examples, and searched for an answer. Nothing seems to work for me. I have included a JSFiddle that demonstrates the start and end date column setup to use the custon dateEditor. When you click the cell, nothing happens. I would like the calendar to popup to select a date as the examples show.
> 
> https://jsfiddle.net/s83w5zru/1/
Did you get a chance to search on stackoverflow ?

https://stackoverflow.com/questions/55714997/tabulator-4-2-sorterdate-not-working

**Comment by UnsterblichMedic** [comment]
Well I am not trying to sort the dates, so I did not see that article.  However, I have tried importing moment.js and still cannot get it to work.  Here is an updated JSFiddle with that imported and still not working.  By the way, love tabulator.  I am still kind of new to HTML, Javascript, etc., but it has been really fun to work with.  Strong work.

https://jsfiddle.net/s83w5zru/2/

**Comment by dota2Pro** [comment]
> Well I am not trying to sort the dates, so I did not see that article. However, I have tried importing moment.js and still cannot get it to work. Here is an updated JSFiddle with that imported and still not working. By the way, love tabulator. I am still kind of new to HTML, Javascript, etc., but it has been really fun to work with. Strong work.
> 
> https://jsfiddle.net/s83w5zru/2/

Fixed it, Please post questions on stackoverflow next time :) 
define **dateEditor** before using it
https://jsfiddle.net/dota2pro/85j0bq3e/9/

**Comment by UnsterblichMedic** [comment]
I was just typing that I figure out you need to define dateEditor before the table.  Thank you.  I tried to post on stackoverflow but it was locking up everytime I tried to submit it.  I am going to try to troubleshoot that.  Again, still kind of new to all of this and have been self teaching while working through this project.  Appreciate your help and taking a look at my code.  Cheers!
