### ISSUE TITLE
[Feature] Page Size for Persistence mode

### ISSUE THREAD

**Issue by timothymarois** [olifolkerd/tabulator#2035]
We have layout, sorting, and filters saved to the Persistence cookie.

http://tabulator.info/docs/4.2/persist

We should also have **page size**. If some users want to save their workspace as 500 rows, and others only want 100, this should be allowed to save to the user's Persistence cookie.

**Comment by olifolkerd** [comment]
Hey @timothymarois 

Great suggestion, i will add it to the development roadmap.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @timothymarois 

I have pushed this to the 4.5 branch which will be released in a few days.

Cheers

Oli :)

**Comment by timothymarois** [comment]
@olifolkerd Thanks for your hard work. We appreciate it!
