### ISSUE TITLE
Sort event triggered when resize column by drag

### ISSUE THREAD

**Issue by ssehoony** [olifolkerd/tabulator#2036]
**Describe the bug**
Browse zoom set 80% or 120% (not 100%) `<-- key point`
Resize column width by column header border drag.
Frequently (not always), sort event triggered.

**Tabulator Info**
- Tabulator : 4.2.7

**To Reproduce**
1. Go to 'http://tabulator.info/examples/4.2'
1. Set browser zoom to 80%
1. Drag Virtual DOM example table's column header border between Name column and Progress column.
1. Sort event triggered when mouse button up after drag.

**Expected behavior**
Browser zoom is 100% or not, No sort event triggered when mouse button up after drag.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser [chrome, firefox]

**Comment by omkark** [comment]
What is the fix for this?
