### ISSUE TITLE
Virtual scroll not rendering correctly in Firefox/Edge with 100% height 

### ISSUE THREAD

**Issue by dasboe** [olifolkerd/tabulator#2037]
if tabulator height is set to 100% the virtual scroll is not rendering enough rows so the table is not filled to the bottom of the table

[codepen](https://codepen.io/anon/pen/mgNNbR)

![Bildschirmfoto 2019-05-03 um 12 31 17](https://user-images.githubusercontent.com/119371/57132877-3f429080-6da1-11e9-973d-597e9ab9d1c1.png)

**Comment by aklaver** [comment]
Went to the CodePen and I am not seeing that with FF 60.6.1esr (64-bit). What versions of FF/Edge are you working with?

**Comment by dasboe** [comment]
I'm on Mac FF 66.0.3 (64-Bit). My colleague at work has been testing Windows 10 Firefox 66.0.3 (64-Bit) and EdgeHTML 17.17134. We both had the same issue. It's visible on vertical scroll. After resizing the window everything looks fine.

**Comment by dasboe** [comment]
As a temporary fix a `redraw()` after the Tabulator instance is created fixes the issue 

```js
let tabulator = new Tabulator("#table", {
  height: '100%',
  columns: columns,
  data: tableData
})

tabulator.redraw()
```

**Comment by aklaver** [comment]
Hmm, I went back to your original screenshot and noticed that the data cut off at 20 rows. I have seen this before in FF. It seems FF does not always play well with size in %(esp 100%). My solution has been to specify the table using a height value that is not a percent.

**Comment by dasboe** [comment]
in my current project I have a header, a footer and the Tabulator table should fill the vertical space inbetween. I think a very common use case. A fixed value for the height is not an option. Using vh, %, flex values results all in the same buggy behaviour.

**Comment by aklaver** [comment]
So when you view the CodePen above you see the behavior you describe? I ask because I do not see any scroll issue. It could be down to my version of FF, trying to eliminate possibilities. I do not use Windows so I do not have Edge available.

**Comment by aklaver** [comment]
I just tried it with FF 66.0.3 and I don't see a scroll issue.

**Comment by dasboe** [comment]
I just tried the codepen again and I always have the issue with Firefox 66.0.3. It's running on latest MAC OS on a MacBook Pro 15" 2013. Maybe there is a race condition and the bug depends on rendering performance:


![scroll_firefox](https://user-images.githubusercontent.com/119371/57193885-87e48000-6f40-11e9-9b33-29dad0572640.gif)

**Comment by olifolkerd** [comment]
The issue is because the tables height is being changed after the table is drawn, 

If this happens you must call the ***redraw*** function in order for the virtual DOM to recalculate how many rows to show.

The reason it isnt an issue on Chrome, is because Chrome implements the ES8 Resized Observer feature that allows Tabulator to automatically know when it has been resized.

Cheers

Oli :)
