### ISSUE TITLE
Custom Mutator fails midway

### ISSUE THREAD

**Issue by davemacluskie** [olifolkerd/tabulator#2038]
I created a custom mutator to alter a comma separated string (e.g.  "edit,delete,remote") into a set of anchor tags. However, the act of splitting the string seems to cause the mutator to fail. Almost any data manipulation efforts seem to fail. (Using Tabulator 4.2 in Firefox 65)

Even a simple example that just fires console.log and returns the value un-mutated fails.

Without the mutator, or if I comment out the line with value.split(","), it works fine.

```
var actionMutator = function(value, data) {
	console.log("actionMutator");
	console.log("value=" + value); // the value of the cell right now (before mutation)
	console.log("doc id=" + data.id); // works.
	console.log("data=" + Object.keys(data)); // the whole data object for the row
	
	// works to here, everything below fails
	
	console.log("value split on commas = " + value.split(",")); // no error in console, but never logs	
	
	return value;
};

// Tabulate the table
var table = new Tabulator("#documentTable", {
	layout:"fitColumns",
	placeholder:"No data available.",
	ajaxURL: appPath + "/classroom/json/documentTableFlat",
    ajaxParams:{
    	"classroomId": classroomId, 
    	"tabName": tabName
    },
    columns:[
    	{title:"Type", 		field:"type", 		sorter:"string",  headerFilter:true,  minWidth:120},
    	{title:"Filename", 	field:"filename", 	sorter:"string",  headerFilter:true,  minWidth:300},
    	{title:"Size", 		field:"bestSize", 	sorter:"number",  headerFilter:true,  minWidth:50},
    	{title:"Contract", 	field:"contract", 	sorter:"string",  headerFilter:true,  minWidth:200},
    	{title:"Actions", 	field:"actions", 	mutator:actionMutator, 	headerFilter:false, minWidth:100}
    ]
});
```

Results from console.log:
actionMutator
value=edit,delete,remove
doc id=18178
data=id,type,filename,url,size,contract,actions

I've tried using a custom mutator as a function and as a module extension with the same results.

My goal was to convert "edit,delete,remove" into a three anchor tags unique to the data on the row and place them in the Actions column.   These actions change from row to row, hence the manipulation using the mutator.

**Comment by aklaver** [comment]
Well the first thing I would try is using the entire signature for the function:

http://tabulator.info/docs/4.2/mutators#mutators
function(value, data, type, params, component)
