### ISSUE TITLE
Scroll to first selected item

### ISSUE THREAD

**Issue by GarryG** [olifolkerd/tabulator#204]
When programmatically selecting data rows, it would be nice if either the table would automatically change the view as to display the first (or next depending on the current view) selected row, or if one could do a call to change the view to display a certain entry. E.g., there are 100 items in the table, after a refresh the item 50 is selected, so I want the view to be updated so that I can actually see the 50th item without manually scrolling down.

**Comment by olifolkerd** [comment]
Hey Garry,

Thanks for your suggestion, so if i can generalize that out, would you like a ***scrollToRow*** function that could be called at any point (on selection for example) to scroll automatically to a given row?

If that is the case i can happily get that in the march release!

Cheers

Oli

**Comment by GarryG** [comment]
> Thanks for your suggestion, so if i can generalize that out, would you
> like a */scrollToRow/* function that could be called at any point (on
> selection for example) to scroll automatically to a given row?
>
> If that is the case i can happily get that in the march release!
>
both setting and inquiring would be good ... that way, a program could
inquire e.g. the first visible row before updating the table view, then
return to that after an update of the data.

Tnx, -garry

**Comment by olifolkerd** [comment]
Hey Garry,

The ***scrollToRow*** function is now available:
```js
$("#example-table").tabulator("scrollToRow", 23);
```

Full documentation can be found [here](http://olifolkerd.github.io/tabulator/docs/#scroll-to-row)

Let me know if that helps

Cheers

Oli
