### ISSUE TITLE
Vue.js: Using local css breaks formatting. CDN hosted works

### ISSUE THREAD

**Issue by iAmVaeVictus** [olifolkerd/tabulator#2040]
**Describe the bug**
When using CDN hosted version of tabulator.min.css (or tabulator.css), test app works great in Vue.js, but when using locally hosted version, the CSS breaks. 

Downloading the css file from GitHub and replacing the node_modules version locally does not help. 

(NOTE: There is also an error:
`VM12225 tabulator.min.js:1 Uncaught SyntaxError: Unexpected token <`

I'm trying hard to troubleshoot this myself, but after about 1.5 hours of trying, I'm asking the expert. 

**Tabulator Info**
- Which version of Tabulator are you using? 
 4.2.7 
- Post a copy of your construct object if possible so we can see how your table is setup

```
//index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="icon" href="<%= BASE_URL %>favicon.ico">
    
   <!-- ******* This file does not work ********
    <link rel="stylesheet" href="/node_modules/tabulator-tables/dist/css/tabulator.min.css">
-->
    <!-- ******* This file works ********* -->
    <link href="https://unpkg.com/tabulator-tables@4.2.7/dist/css/tabulator.min.css" rel="stylesheet">
    

    <script type="text/javascript" src="/node_modules/tabulator-tables/dist/js/tabulator.min.js"></script>


    <script type="text/javascript" src="/node_modules/tabulator-tables/dist/js/tabulator.min.js"></script>
    <title>tabletest</title>
  </head>
  <body>
    <noscript>
      <strong>We're sorry but tabletest doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>
    </noscript>
    <div id="app"></div>
    <!-- built files will be auto injected -->
  </body>
</html>
```

```
//Testpage.vue
<template>
    <div ref="table"></div>
</template>

<script>
    var Tabulator = require('tabulator-tables')
    export default {
        name: 'Test',
        data: function () {
            return {
                tabulator: null, // variable to hold your table
                tableData: [
                    {name: 'Billy Bob', age: '12'},
                    {name: 'Mary May', age: '1'}
                ] // data for table to display
            }
        },
        watch: {
            // update table if data changes
            tableData: {
                handler: function (newData) {
                    this.tabulator.replaceData(newData)
                },
                deep: true
            }
        },
        created: function () {
            console.log('Test', this.$refs)
        },
        mounted () {
            // instantiate Tabulator when element is mounted
            this.tabulator = new Tabulator(this.$refs.table, {
                data: this.tableData, // link data to table
                columns: [
                    {title: 'Name', field: 'name', sorter: 'string', width: 200, editor: true},
                    {title: 'Age', field: 'age', sorter: 'number', align: 'right', formatter: 'progress'}
                ]
            })
        }
    }
</script>
```
```
//router.js
import Vue from 'vue'
import Router from 'vue-router'
import Home from './views/Home.vue'
import Table from './views/Testpage.vue'

Vue.use(Router)

export default new Router({
  mode: 'history',
  base: process.env.BASE_URL,
  routes: [
    {
      path: '/',
      name: 'home',
      component: Home
    },
    {
      path: '/about',
      name: 'about',
      // route level code-splitting
      // this generates a separate chunk (about.[hash].js) for this route
      // which is lazy-loaded when the route is visited.
      component: () => import(/* webpackChunkName: "about" */ './views/About.vue')
    },
    {
      path: '/table',
      name: 'table',
      // route level code-splitting
      // this generates a separate chunk (about.[hash].js) for this route
      // which is lazy-loaded when the route is visited.
      component: Table
    }


  ]
})

```

**Screenshots**

WORKING (CDN hosted CSS):
![Screen Shot 2019-05-03 at 6 35 44 PM](https://user-images.githubusercontent.com/7082654/57170466-a88ec780-6dd2-11e9-8a2d-c6b59a20b545.png)

NOT WORKING (Locally hosted CSS):
![Screen Shot 2019-05-03 at 6 36 38 PM](https://user-images.githubusercontent.com/7082654/57170440-86954500-6dd2-11e9-9c2a-aa4ddbf153f0.png)

CONSOLE (with either version):
![Screen Shot 2019-05-03 at 6 37 14 PM](https://user-images.githubusercontent.com/7082654/57170461-a298e680-6dd2-11e9-8b9d-cd07b6140b33.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser [e.g. chrome, safari]: Brave (Version 0.63.48 Chromium: 74.0.3729.108 (Official Build) (64-bit), Chrome (Version 73.0.3683.103 (Official Build) (64-bit)

**Comment by aklaver** [comment]
To me it looks like your server is serving local CSS files as the wrong type. As a start add type="text/css" to your local stylesheet link.

**Comment by iAmVaeVictus** [comment]
Thank you for the reply @aklaver 

Modified the index.html file, with no change in the output. Changing to the local css file with text/css still breaks the formatting on the table. 
```
//index.html snippet
<!-- This file does not work -->
     <link type="text/css" href="/node_modules/tabulator-tables/dist/css/tabulator.min.css" rel="stylesheet">

    <!-- This file works
    <link href="https://unpkg.com/tabulator-tables@4.2.7/dist/css/tabulator.min.css" rel="stylesheet">
-->
```
I'd prefer to not refer to the CDN in production.... I'm sure I'm doing something boneheaded.

**Comment by aklaver** [comment]
I just noticed that the error you are getting is for the minified JS file. This error also showed up in this issue:
https://github.com/olifolkerd/tabulator/issues/1982
The fix was download that file again as there was corruption in it. You might try that.
