### ISSUE TITLE
Top level headersort

### ISSUE THREAD

**Issue by dcanning** [olifolkerd/tabulator#2042]
**feature request**: allow setting the state of headerSort for all columns in the tabulator at the tabulator definition level so you don't have to set the headerSort property of each column in order to turn headerSort off completely.

**Comment by olifolkerd** [comment]
Hey @dcanning 

Thanks for the input, i will look at adding that to the roadmap,

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @dcanning 

I have just pushed this feature to the 4.4 branch which should be released in the next couple of weeks.

Cheers

Oli :)
