### ISSUE TITLE
French translate in Localization example

### ISSUE THREAD

**Issue by blr21560** [olifolkerd/tabulator#2043]
Hi,

It isn't a bug.
The French translate isn't good for all properties in Localization example (http://tabulator.info/examples/4.2)
my translation proposal :
"fr-fr":{ //French language definition
            "columns":{
                "name":"Nom",
                "progress":"Progression",
                "gender":"Genre",
                "rating":"Évaluation",
                "col":"Couleur",
                "dob":"Date de Naissance",
            },
            "pagination":{
                "first":"Premier",
                "first_title":"Première Page",
                "last":"Dernier",
                "last_title":"Dernière Page",
                "prev":"Précédent",
                "prev_title":"Page Précédente",
                "next":"Suivant",
                "next_title":"Page Suivante",
            },
        },
Thanks,
Regards,

**Comment by Rodbjartson** [comment]
:P

**Comment by olifolkerd** [comment]
Hey @blr21560 

Thanks for the suggestion, i will include it in the next website update.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @blr21560 

These will go live with the website update later today

Thanks

Oli :)

**Comment by ant-sv** [comment]
"Show page" title is out of localization
