### ISSUE TITLE
Delete row with tree children

### ISSUE THREAD

**Issue by pythonBerg** [olifolkerd/tabulator#2045]
When parent row is deleted, shouldn't the children be deleted as well? They don't appear to standalone very well given their original subordinate position and the tree markings remain.

**Comment by olifolkerd** [comment]
Hey @pythonBerg 

If you are reporting a bug, please use the Bug issue template as it propts you to answer all the questions that we need to know in order to fix an issue.

Please also include a JS Fiddle that demonstrates your problem.

Cheers

Oli :)
