### ISSUE TITLE
Custom Callback for particular events

### ISSUE THREAD

**Issue by Gnuffie** [olifolkerd/tabulator#2049]
First things first, i love tabulator and i see how easy it is to use but i got a particular issue with it,
i see in documentation the **custom callbacks** for each event but i want to add my own callback and i don't know how. So i just needed some explanation on how to start.

Thanks and thank you for tabulator,
Gnuf

**Comment by gillez** [comment]
The first place to look is in the examples.  E.g. http://tabulator.info/examples/4.2#movable <http://tabulator.info/examples/4.2#movable>
Unfortunately most of the examples still use jQuery but it's not difficult to modify them to use vanilla JS or other methods.
