### ISSUE TITLE
Deleting Column Groups

### ISSUE THREAD

**Issue by ravashjalil** [olifolkerd/tabulator#205]
Hello, I'll preface this by saying I'm just getting started with js but so far so good.  I'm trying to create a button that will update the table with a new set of columns.  I need it to delete the specified columns and then add the new ones, so naturally I tried the "deleteColumn" approach, however, some of my columns are under column groups and once those are deleted the column group stays throwing the table off.  This is the snippet I used...

```
		$("#del-col").click(function(){
			$("#example-table-adddel").tabulator("deleteColumn", "dob");
		})
```
Is there a way I can specify the Column Group as well? Or a better approach? Thanks!

**Comment by olifolkerd** [comment]
Hey thanks for getting in touch,

could you post a copy of your Tabulator constructor so i can replicate the error with your setup.

Cheers

Oli

**Comment by ravashjalil** [comment]
Thanks for your quick reply.  So for example below I want to get rid of the whole "Personal" section, with everything beneath it.  

```
$("#example-table-adddel").tabulator({
    columns:[
       {title:"Name", field:"name" ,sortable:true, headerFilter:true,width:150, responsive:0},
            {
               title:"Personal",
               columns:[
                    {title:"Age", field:"age", sortable:true},
                    {title:"Birthday", field:"dob", sortable:true},
                    {title:"Sex", field:"sex", sortable:true},
],
                    },

    ],
});
```

**Comment by olifolkerd** [comment]
Thanks for sending that over,

At the moment there is no way to delete column groups and their children, but that is definitely a needed feature.

I will have a look at getting that implemented for you in the next couple of days.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey,

I have just pushed some updates to the repo for this.

Hiding or deleting columns will now update the column groups as well.

Cheers

Oli
