### ISSUE TITLE
Data Integrity Issue

### ISSUE THREAD

**Issue by ryderdale** [olifolkerd/tabulator#2050]
After working with the column.getCells() function, I noticed that the function was not returning all the cells in the column. I inspected the table's object in whole and it does not contain all the cells within the columnManager, however, it does contain all the rows and cell values within the rowManager. I did an "npm install" just in case something in the package was inadvertently modified and the issue persisted. All 63 rows are displaying within the UI 

Screenshot of data object linked: 
**https://www.dropbox.com/s/b8szipapyrfwptb/Screenshot%202019-05-09%2012.47.57.png?dl=0**

**Comment by aklaver** [comment]
Seeing the table constructor would help along with Tabulator version. Still I am going to guess you have Virtual DOM enabled and the table is only displaying 34 rows. AFAIK until the row is displayed the cell component does not exist.  If you want all the data in the table see table.getData():
http://tabulator.info/docs/4.2/update#retrieve-data

**Comment by ryderdale** [comment]
When disabling Virtual DOM mode all the rows came through on the object. That's a detail to be careful with. I'm on Version 4.2. Thanks!
