### ISSUE TITLE
Would like to format a column based on the sum of the column.

### ISSUE THREAD

**Issue by phallett** [olifolkerd/tabulator#2051]
I have a resource allocation table in which a user is allocated a work activity. In the table, each activity is a row, and there are 52 columns signifying each week of the year.  If the user has 1 or more activities, I sum the weeks activity allocated.  If this goes above a business rule, then I want to colour the column based on how far over allocated they are.  So, for example, if we say a working week is 30 hours. If they are 30 or under, I colour the column green, if 30-32 yellow and above 32 Red.  I am summing the values, but I don't know how to add conditional formatting based on the sum value, it's not clear in the documentation, so I think you can't.  

Can this be added as a feature?
<img width="912" alt="Screenshot 2019-05-10 at 11 07 06" src="https://user-images.githubusercontent.com/676839/57519687-cf3d8880-7313-11e9-8982-8ef5476e89ff.png">

**Comment by aklaver** [comment]
Do you want to color all the cells in the column or just the calculated cell?

**Comment by phallett** [comment]
Hi, I'd want to make the whole column red, yellow or green, at least the outline.

If not possible, then the cell or even just the 'sum' cell

Cheers

**Comment by aklaver** [comment]
A rough draft for the sum cell:
https://jsfiddle.net/aklaver/j7eqg3db/56/

**Comment by phallett** [comment]
Cheers AKLaver.  New to this object so learning, appreciate the help.  That works well by the way.

Cheers

Paul

**Comment by phallett** [comment]
I tried to extend that a little, but var cells = col.getCells(); doesn't appear to get the cells as the loop doesn't work at all.

Any ideas? 

    var colorFormatter = function(cell, formatterParams, onRendered){

        var val = cell.getValue();    
        console.log(val);   
        var col = cell.getColumn();
        var cells = col.getCells();

        cells.forEach(function(cell, val){
            console.log(cell.getValue());
            if (val <= 37){
                cell.getElement().style.backgroundColor="green";
            }else if (val > 37 && val <= 40){
                cell.getElement().style.backgroundColor="yellow";
            } else if (val > 40){
                cell.getElement().style.backgroundColor="red";
            }
        });
        return val;
    };

**Comment by aklaver** [comment]
I tried that as well. It works if you do it from the browser console outside the callback function. I'm pretty sure it is a timing issue on when the formatter is called. Still thinking on how to make it work.

**Comment by phallett** [comment]
Ok, I'll give that a go.  There's a little bit of latency with the sum anyway, but I'll look at putting that outside the callback and see how it performs.  Be good to get it working on the callback though!  It's cracking gear though, just what I was looking for.

**Comment by aklaver** [comment]
As close as I can come at the moment:
https://jsfiddle.net/aklaver/q736mkor/74/
Uses a button to color the columns. I left in the topCalc formatter, but that is redundant I believe.

**Comment by phallett** [comment]
One to work with; I am wondering if I can fabricate an event to fire the button function, as such.

**Comment by aklaver** [comment]
Yeah that is one of those chicken and egg problems:) If you had the event you could just attach the function to it without going through a button. There maybe something meets your needs here:
http://tabulator.info/docs/4.2/callbacks

**Comment by takuy** [comment]
could probably just do it on tableBuilt();

**Comment by phallett** [comment]
I am also updating the data live via Ajax so the values change

**Comment by aklaver** [comment]
I guess you could try to hook into this:
http://tabulator.info/docs/4.2/callbacks#ajax

**Comment by phallett** [comment]
I update another table with the data as well as the 'parent' table.  The Ajax callback works well with the 'parent' table.  But as the other table uses that value as part of a view, I have to refresh that table,

**Comment by aklaver** [comment]
The other function being fetchAllUserProjects?
If so how does that function move the data into the table and is there a callback associated with that data loading that can be used?

**Comment by phallett** [comment]
yes, when a cell is edited, this table is updated live via Ajax and then on success, the other table is 'reloaded' (I can't think of a way to edit one cell on the other table):

   function fetchAllUserProjects(userid) {

        console.log("/getusrprojs " + userid);
        $.ajax({
                url : "/getusrprojs", //"{{url_for('checkalloc')}}", 
                data: {userid:userid},
                type: 'GET',
                contentType: "application/json;",
                success: function(data){
                    var obj = $.parseJSON(data);
                    console.log(data)
                    if(data.length>2){                   
                        var table = new Tabulator("#user-project-table", {
                        etc, etc



I can't see how I can link data being changed on #project-member-table" to data in the #user-project-table

**Comment by aklaver** [comment]
Well this is getting off topic, but as an outline:
1) Data edited callback:
http://tabulator.info/docs/4.2/callbacks#data

2) In above update data in other table:
http://tabulator.info/docs/4.2/update#alter-update

3) You may to throw in a table redraw:
http://tabulator.info/docs/4.2/layout#redraw

**Comment by phallett** [comment]
I agree,  I alter the data in a cell edited call back, then once the success comes back, simply issue a table redraw in method, but I will try the other method if I can.

Thanks
