### ISSUE TITLE
AMD dependencies for jquery_wrapper incomplete

### ISSUE THREAD

**Issue by pmulreid** [olifolkerd/tabulator#2053]
AMD modules are being loaded out of order due to incomplete/incorrect dependencies.

jquery_wrapper depends on jquery-ui and Tabulator

v4.2.7

https://jsbin.com/sohenohuzi/edit?html,console,output

{
        data:[
          {name:"Test Data"}
        ],
        autoColumns:true
}

Fully repeatable

jquery_wrapper.js should not load until jquery-ui and Tabulator are available

chrome

![jquery_wrapper](https://user-images.githubusercontent.com/33301410/57554753-39811800-736a-11e9-8dc0-e79d4b4182d7.png)

**Comment by pmulreid** [comment]
So this is closed, what is the resolution?

**Comment by olifolkerd** [comment]
Hey @pmulreid 

As the jquery wrapper is an optional feature for backwards compatibility the dependency is not automatically loaded, 

If you wish to use the jquery wrapper you are required to load jquery before you require the Tabulator library.

Cheers

Oli :)

**Comment by pmulreid** [comment]
Thanks, and I understand and agree with all that. However with requirejs, there is no way to influence the library load order for AMD compliant modules, save the module correctly declaring it's dependencies. 

Whether optional, or not, the jQuery wrapper does depend on both jQuery-ui and Tabulator and, as such, should declare itself dependent. I can't see what would be wrong in doing so. I've made the changes in a fork of the code and it works perfectly.

Kind regards

Peter

**Comment by olifolkerd** [comment]
Hey @pmulreid 

If you have a solution that covers the jQuery scenario without pulling in unnecessary dependencies for normal non-jquery usage then please feel free to submit a pull request with your proposal.

Cheers

Oli :)

**Comment by pmulreid** [comment]
Done #2090

**Comment by olifolkerd** [comment]
Merged!

Thanks for the pull request :)

Cheers

Oli
