### ISSUE TITLE
CI enviroment to tests

### ISSUE THREAD

**Issue by angeliski** [olifolkerd/tabulator#2054]
The main proposal for that issue is talk about a enviroment to run tests.
Please share your opnion about the topics:
1 - CI enviroment. Ex: Travis, CircleCI
2 - Testing Framework Ex: Jest, Mocha
3 - Critical features to test. Where we need start?

**Comment by olifolkerd** [comment]
Hey @angeliski 

Thanks for raising this, do you have any personal recomendations from your experience?

Cheers

Oli :)

**Comment by angeliski** [comment]
Yes, for CI I prefer Travis CI, but I don't have a lot experience in CircleCI (just run one project in that).
A prefer Jest because is really simple run and configure.
You is the best man to say where we can start, but I can think in the core e column_manager.
What do you think?

**Comment by olifolkerd** [comment]
Hey @angeliski 

Im happy for you to run with whichever tool you think best,

The column manager and row managers seem like sensible places to start

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @angeliski 

I am going to create a new issue to track this now, closer to the 5.0 release notice, The codebase has been refactored to make unit testing easier so i would really like to encourage the community to implement this now.

Cheers

Oli :)
