### ISSUE TITLE
Shrink table width to column width

### ISSUE THREAD

**Issue by gso** [olifolkerd/tabulator#2055]
I have a table in which all the columns have the width attribute set.  The table expands to the width of the containing element, while the total column width is less than the width of the containing element.  This leaves a gap between the right most column and the right hand edge of the table.  There is no way to shrink the table width to the total width of the columns.

**Comment by aklaver** [comment]
I don't know how to make the table shrink. You could use layout:"fitColumns" and widthGrow to have the columns grow into the container. This would mean un-setting  the width on one or more columns and then using widthGrow: x to have those columns expand to fit.

**Comment by olifolkerd** [comment]
Hey @gso 

At the moment this isnt possible, Tabulator is designed to fit within its element, not change the element to match its internal size.

I will flag this as a feature request for future consideration.

Cheers

Oli :)

**Comment by xXmrotsXx** [comment]
Hi @gso,

I just commented on your SO question... Can you not just set the width of the table to the width of the total of your "fixed width" columns?

**Comment by gso** [comment]
I don't think there is a way to set the width of the table, a workaround would be to set the width of the containing element.

**Comment by xXmrotsXx** [comment]
Yeah, if your columns have a fixed width, you should know the width your table needs to be... You can set the width in CSS or with a style tag in your html. So 8 x 50px columns needs a table width of 400px:

``<div id="example-table" style="width:400px"></div>``

or in CSS

``
#example-table{
    width:400px;
}
``
