### ISSUE TITLE
Add custom css classes in getHtml function

### ISSUE THREAD

**Issue by robberti4y** [olifolkerd/tabulator#2056]
The getHTML function is a great function to print tabulator tables because headers will be repeated on new pages. However: it is difficult to style the html-table because tabulator doesn't put the added css-classes in the HTML. 

So please put the classes that are added to columns with cssClass also in the html of that <td> in the HTML table.  (or is it a bug that this class is not in the HTML? in that case: sorry for creating a feature request instead of a bug)

**Comment by olifolkerd** [comment]
Hey @robberti4y 

I think that is a great idea!, im actually overhauling this functionality for the 4.3 release so i will include it then.

Thanks

Oli :)

**Comment by olifolkerd** [comment]
Hey @robberti4y 

You will be happy to hear i have just pushed this feature to the 4.5 branch which should be released in a few weeks.

Cheers

Oli :)
