### ISSUE TITLE
[Complex Filtering] getFilter function don't return correctly the complex filters applied (AND/OR condition)

### ISSUE THREAD

**Issue by Fluksy** [olifolkerd/tabulator#2057]
Hello,

When complex filters is applied to Tabulator (AND and OR condition), if we ask to Tabulator for the list of applied filters with "getFilters()" , there is a bug that causes us not to have the list of applied OR filters

**Tabulator Info**
- 4.2.7 is the version i'm using

**Working Example**
https://jsfiddle.net/51gn0cub/12/

On the JS Fiddle, there is a button who set a "complex" filter
and a button who alert the getFilter result

**Expected behavior**
When complex filtering is applied, the getFilter function could return the OR filters (in an array maybe)

**Comment by EdDonald** [comment]
up

**Comment by olifolkerd** [comment]
Hey @Fluksy 

Good catch, i will look into fixing this for the next release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @Fluksy 

I have just pushed a fix for this to the 4.3 branch and will include it in todays release

Cheers

Oli :)
