### ISSUE TITLE
Request table data format without field names for each row

### ISSUE THREAD

**Issue by mazzanti** [olifolkerd/tabulator#2058]
Hi, I am using v4.2.5, and grid accepts data using format [{colname: value}].
That's causes overhead for my scenario.

I ask if tabulator is planning to support this format of data:

//define data without overhead
var tabledata = [
    [1, "Oli Bob", 12, "male", 1, "red" ],
    [2, "Mary May", 1, "female", 2, "blue" ],
    [3, "Christine Lobowski", 42, "female", 0, "green" ]
];

instead of actual:

// data with overhead
var tabledataOverhead = [
    {id:1, name:"Oli Bob", progress:12, gender:"male", rating:1, col:"red" },
    {id:2, name:"Mary May", progress:1, gender:"female", rating:2, col:"blue" },
    {id:3, name:"Christine Lobowski", progress:42, gender:"female", rating:0, col:"green" }
];

//Build Tabulator
var table = new Tabulator("#example-table", {
    height:"311px",
    layout:"fitColumns",
    data:tabledata, //load data into table
    columns:[
        {title:"Name", field:"name", sorter:"string", width:200},
        {title:"Progress", field:"progress", sorter:"number", formatter:"progress"},
        {title:"Gender", field:"gender", sorter:"string"},
        {title:"Rating", field:"rating", formatter:"star", align:"center", width:100},
        {title:"Favourite Color", field:"col", sorter:"string", sortable:false},
    ]
});

Now I am using a function in order to normalize each row to the format supported by tabulator.

Thank you.

**Comment by aklaver** [comment]
I understand the ease of use argument, but I do not see that as practical. There are too many ways for the data to get out of sync with the table layout.
