### ISSUE TITLE
error related to tabulator Cannot read property 'getData' of undefined at Object.cellClick

### ISSUE THREAD

**Issue by PujaAhirrao** [olifolkerd/tabulator#2059]
**Describe the bug**
Error come when click on cellclik of tabulator:
T_frmPickingPlan.js:88 Uncaught TypeError: Cannot read property 'getData' of undefined
    at Object.cellClick (T_frmPickingPlan.js:88)
    at y.edit (tabulator.min.js:5)
    at HTMLDivElement.<anonymous> (tabulator.min.js:5)
    at HTMLDivElement.dispatch (jquery.min.js:3)
    at HTMLDivElement.r.handle (jquery.min.js:3)

Tabulator:
$("#PickingPlan-table").tabulator({
    tooltipsHeader: true,
    tooltips: true,
   // groupBy: "Partcode",
    groupBy: function (data) {
        return ((data.Partcode.replace(/[`*]/g, '"')).replace(/[`^]/g, "'")); //groups by data and age
    },
    index: 'IRLineId',
    rowFormatter: function (row) {
        if (row.getData().PickingStatus == "1") {
            row.getElement().css({ "background-color": "#A6A6DF" });
        }
    },
    columns: [
        { title: "Sr", formatter: 'rownum', align: "Center", width: 30 },
        { title: "POIndId", field: "POIndId", visible: false },
        { title: "IRId", field: "IRId", visible: false },
        { title: "POIndLineId", field: "POIndLineId", visible: false },
        { title: "IRLineId", field: "IRLineId", visible: false },
        { title: "PcodeId", field: "PcodeId", visible: false },
        { title: "UOMId", field: "UOMId", visible: false },
        { title: "SubLocId", field: "SubLocId", visible: false }, 
        { title: "IRType", field: "IRType", visible: false }, 
        { title: "PickingStatus", field: "PickingStatus", visible: false },
        {
            title: "Partcode", field: "Partcode", width: 175, headerFilter: "input", formatter: function (cell, formatterParams) {
                return ((cell.getData().Partcode).replace(/[`*]/g, '"')).replace(/[`^]/g, "'");
            }},
        {
            title: "Description", field: "Description", width: 280, headerFilter: "input", formatter: function (cell, formatterParams) {
                return ((cell.getData().Description).replace(/[`*]/g, '"')).replace(/[`^]/g, "'");
            }},
        { title: "Required Qty", field: "ReqQty", align: "Center", width: 80, headerFilter: "input" },
        { title: "Reserved Qty", field: "ResQty", align: "Center", width: 80, headerFilter: "input" },
        { title: "Free Qty", field: "Freeqty", align: "Center", width: 80, headerFilter: "input" },
      //  { title: "Pick Qty", field: "PickQty", align: "Center", width: 80, headerFilter: "input" },
        {
            title: "Pick Qty", field: "PickQty", align: "Center", editor: "number", width: 80, headerFilter: "input", formatter: function (cell, formatterParams) {
                var value = cell.getValue();
                if (value == "" || value == undefined)
                    return "<div style='border:1px solid #dad5d5;width:100%;'>&nbsp; </div>";
                else
                    return "<div style='border:1px solid #dad5d5;width:100%;'>" + cell.getValue() + "</div>";
                }, 
            cellClick: function (e, cell) {
                if (cell.getData().ReqQty != undefined || cell.getData().ResQty != undefined || cell.getData().PickQty != undefined) {
                    DisableAcceptqty(cell.getData().ReqQty, cell.getData().ResQty, cell.getData().PickQty);
                }
                //if (document.getElementById("hdnStatus").value == 1) {
                //    toastr.options.positionClass = 'toast-top-center';
                //    toastr.warning("You can't edit this quantity");
                //}
            },
        },
        { title: "UOM", field: "UOM", align: "Center", width: 40, headerFilter: "input" },
        { title: "Assigned Location", field: "SuggestedLoctn", width: 110, headerFilter: "input" },

    ],
    tooltips: function (cell) {
        //cell - cell component
        if (cell.getColumn().getField() == 'Description')
            return ((cell.getData().Description).replace(/[`*]/g, '"')).replace(/[`^]/g, "'");
        else if (cell.getColumn().getField() == 'Partcode')
            return ((cell.getData().Partcode).replace(/[`*]/g, '"')).replace(/[`^]/g, "'");
        else
            return cell.getValue();

    },

});

when i click on cell click of PickQty column it gives error:T_frmPickingPlan.js:88 Uncaught TypeError: Cannot read property 'getData' of undefined
    at Object.cellClick (T_frmPickingPlan.js:88)
    at y.edit (tabulator.min.js:5)
    at HTMLDivElement.<anonymous> (tabulator.min.js:5)
    at HTMLDivElement.dispatch (jquery.min.js:3)
    at HTMLDivElement.r.handle (jquery.min.js:3)

Pickqty is editable field in my tabulator but i click on Pickqty for edit then it give error.I dont understand what happen there.at cellclick i pass values and call one function  DisableAcceptqty. to disable that field on the base of values come.It works fine on my local PC values are edit but when i uploded on server it gives error.Please give suggestion.

**Tabulator Info**
- 3.5 version of Tabulator I am using
- Post a copy of your construct object if possible so we can see how your table is setup

**Working Example**
Js i use in my page.
  <script src="../../assets/ExtJS/Tabulator/tabulator.min.js"></script>
      <%--select2/smartsearch--%>
    <script src="../../global/vendor/select2/select2.min.js"></script>
     <script src="../../../global/vendor/toastr/toastr.js"></script>
    <script src="../../../global/js/Plugin/toastr.js"></script>
       <script src="../../global/vendor/bootstrap-sweetalert/sweetalert.js"></script>
    <script src="../../global/js/Plugin/bootstrap-sweetalert.js"></script>
    <script src="../../assets/examples/js/advanced/bootbox-sweetalert.js"></script>
    <script src="JS/T_frmPickingPlan.js"></script>

**To Reproduce**

**Expected behavior**
It not give any error on cellclick and value get [edited.](url)

**Screenshots**
![RefScreenshot](https://user-images.githubusercontent.com/50579746/57618557-69fec700-75a1-11e9-8fea-e486668061ac.png)

**Desktop (please complete the following information):**
 - OS: [e.g. windows 10]
 - Browser { chrome]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aklaver** [comment]
I would start with simplifying your code on the PickQty column to being just a normal input column. Same with the cellClick code, take it down to just an alert/console log. That should get a working basis. Then start making one change at a time to see where things go wrong. My suspicion is that the code you are using to transform the values is not doing what you think it is.
