### ISSUE TITLE
Multiple cell edition

### ISSUE THREAD

**Issue by Joan1899** [olifolkerd/tabulator#206]
Hi,

first of all congrats for the great job and the great community!

My users are expecting excel similar functionality for editing multiple cells at once. Therefore I was wondering if I have seen any feature capable of doing that.

I myself tried to implement something with click or keypressed events but have had no success for now.

I just need to:
a) select multiple cells and upload them via ctrl+c or
b) drag value from first selected cell to further selected cells

Have you any advice about how a feature like that could be implemented?

THX and BR!

Joan

**Comment by olifolkerd** [comment]
Hi Joan,

Thanks for getting in contact. 

Sadly at the moment there is no option for either of those in Tabulator.

The copy and paste option is already in the road map and should be available in a couple of months.

As for the excel like selection and dragging, that is a brilliant idea! I will add it to the road map, but im afraid it will probably be a couple of month before i get a chance to implement that,

In-terms of manually implementing those features yourself, i would suggest looking at how the current row selection functionality works (line 2242 in tabulator.js) i would suggest using a similar functionality across cells adding a **_.tabulator-selected_** property to the cells as they are selected and keeping an array of all selected cells for later manipulation.

Copying text to the clipboard can be tricky and support varies across browsers, but i would suggest looking at a library like [clipboard.js](https://clipboardjs.com/) for some inspiration.

if you need any help along the way, give me a shout, and if you come up with a workable solution i would be happy to pull it back into the main Tabulator codebase.

Cheers

Oli

**Comment by Joan1899** [comment]
Hi,

many thanks for your answer. Tabulator is really awesome and I just want it to be MORE awesom. I found some code in internet and extended it. It basically does what you said: mark cells and update values. It works quite fine.

================

 $(function () {
  var isMouseDown = false;
  var value;
  var refrow;
  var refcol;
  $(".tabulator-cell")
    .mousedown(function () {
      isMouseDown = true;
      value = this.getAttribute("data-value");
      
      //Implement vertical or horizontal
      
      refcol = this.getAttribute("data-index");
      var refrow = null;
      if (parseInt(this.getAttribute("data-index"))>9 && event.shiftKey){
      	$(this).toggleClass("highlighted");
      }
      if (parseInt(this.getAttribute("data-index"))>9 && event.ctrlKey){
      	$(this).toggleClass("highlighted2");
      }
      
      return false; // prevent text selection
    })
    .mouseover(function () {
      if (isMouseDown) {
      	if (parseInt(this.getAttribute("data-index"))>9 && event.shiftKey){
      		$(this).toggleClass("highlighted");
      	}
      	if (parseInt(this.getAttribute("data-index"))>9 && event.ctrlKey){
      		$(this).toggleClass("highlighted2");
      	}

      	
      }
    });
  
  $(document)
    .mouseup(function () {
      isMouseDown = false;
      if (event.shiftKey){
      	updateSelected(value);
      }else if (event.ctrlKey){
      	updateGroup();
      }
      
    });
});

================

It basically stores a value by mousedown when Shiftevent and while mousepressed it makes the cells selected. By Mouseup all selected values trigger an update (I use it with SP) and toggle to not selected. 

Sorry for the code, it is pretty ugly for I am testing lots of things.

I already added shiftevent and want to check if with ctrlevent I can select a part of a row or column and drag it to the next/previous rows/columns.

One thing I wanted to ask:  After firing update I want to have new value stored in the cells. I thought about refreshing the table but I am having some trouble in combination with the mousedown event.

Any hint?

BR,
Joan

**Comment by olifolkerd** [comment]
He Joan,

Thanks for sending over the snippet.

If you want to trigger a value update on a specific cell then you can trigger the ***editval*** event on the ***.tabulator-cell*** element you want to update:
```js
$("#selector-specific-cell").trigger("cell.trigger("editval", newVal);
```
Let me know if that helps,

Cheers

Oli

**Comment by Joao-deOliveira** [comment]
Hi All,

This is a similar feature I'm looking for.. selecting a set of cells in a column / row. Currently my workaround is to make the user selecting the rows he/she wants, then right-click on one of the cells on the desired column .. then it's "just" to pick the cells. 

Is not THE solution but for selecting only a set of cell from a column from a set of rows ... it works 

Thanks @olifolkerd for the SUPER Work  !!

cheers
João
