### ISSUE TITLE
Vertical scroll via scroll bar very slow and jumpy bis (similar to #1847)

### ISSUE THREAD

**Issue by sinopsysHK** [olifolkerd/tabulator#2061]
**Describe the bug**
Vertical scroll via scroll bar very slow and jumpy (like #1847) on large table (15000 lines x 40 columns) and few frozen columns.

**Tabulator Info**
- tabulator 4.2.7
- Table creation code
`
var table = new Tabulator("#example-table", {
  height: "500px", // set height of table to enable virtual DOM
  //virtualDomBuffer:900,
  data: tabledata,
  layout: "fitData", //fit columns to width of table (optional)
  columns: [ //Define Table Columns
    {
      title: "Lv 0",
      field: "grp0",
      sorter: "string",
      visible: false,
      frozen: true,
      headerFilter: "select",
      headerFilterParams: {
        values: true,
        sortValuesList: "asc"
      }
    },
    {
      title: "Lv 1",
      field: "grp1",
      sorter: "string",
      visible: false,
      frozen: true,
      headerFilter: "select",
      headerFilterParams: { values: true }
    },
    {
      title: "Lv 2",
      field: "grp2",
      sorter: "string",
      visible: false,
      frozen: true,
      headerFilter: "select",
      headerFilterParams: { values: true }
    },
    {
      title: "Empty Col",
      field: "none",
      sorter: "string",
      visible: true,
      frozen: true
    },
    {
      title: "Item",
      field: "item",
      sorter: "string",
      frozen: true,
      headerFilter: "select",
      headerFilterParams: { values: true }
    }
  ].concat(buildHeader(cols)),
  groupBy: ["grp0", "grp1", "grp2"]
});
`

**Working Example**
snippet reflecting my actual professional use case
[https://jsfiddle.net/sinopsysHK/aL60kwy8/](https://jsfiddle.net/sinopsysHK/aL60kwy8/)

**To Reproduce**
1. run code
2. scroll up and down with scroll bar
4. See how scrolling is lagging

**Expected behavior**
I would have expecting a more reactive behavior with scrolling achieved in less than 1s while here it can take more than 3s.
I was expected something like [https://clusterize.js.org/](https://clusterize.js.org/) step 5 even if my table is much more complex.
Wondering if virtual dom is applying

**Desktop (please complete the following information):**
 - OS: windows 10 Home & Enterprise (a bit faster with enterprise)
 - Browser: chrome
 - Version: 74.0.3729.131

**Comment by olifolkerd** [comment]
Hey @sinopsysHK 

This is happening because of the large number of columns in your table, Tabulator currently only has a virtual DOM for the vertical scroll, meaning rows with lots of columns can cause a degradation in rendering performance.

There is an issue #1437 that tracks improvements to this part of the system, you can track updates to the Virtual DOM there

Cheers

Oli :)
