### ISSUE TITLE
Floating grouping sections

### ISSUE THREAD

**Issue by sinopsysHK** [olifolkerd/tabulator#2062]
**Is your feature request related to a problem? Please describe.**
With large tables using grouping, the grouping section quickly disappears and you don’t remember where you stand while viewing current rows.

**Describe the solution you'd like**
It would be nice to set floating sections that remains at the top until scrolling to next one.

**Describe alternatives you've considered**
No alternate solution found so far

**Additional context**
Something like this: https://www.jqueryscript.net/table/iOS-Style-jQuery-Sticky-Table-Headers-Rows-Plugin-Table-Section.html
But I haven’t enough js skills to integrate it myself.

**Comment by olifolkerd** [comment]
Hey @sinopsysHK 

That is an interesting idea, i will consider it for a future release.

Cheers

Oli :)

**Comment by sinopsysHK** [comment]
Thank you for the feedback. Looking forward for this killer feature 😃
