### ISSUE TITLE
Add blank header when layout is specified as fitDataFill

### ISSUE THREAD

**Issue by haferje** [olifolkerd/tabulator#2067]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When I specify `layout: 'fitDataFill'` in the table options, each data row generates an end cell that takes up the remaining width if the columns do not fit the table width.  Can we also add a blank header for that column so the styling is uniform?

I don't like the feel of the dark empty space that is left, such as when a layout isn't specified, but I'm also not sure if a fully-blank column would be confusing for users that might be wondering if some column just isn't populating for some reason...

**Describe alternatives you've considered**
Leaving as-is.

**Additional context**
Things to consider: The column header would not need to respond to any events or apply any modules.  However, it would need to disappear (like its row cells) if data columns are resized to fit or extend beyond the table bounds, and return when decreased. This column also doesn't need to be exported/downloadable.

**Comment by aklaver** [comment]
Using fitColumns is not an option?

**Comment by haferje** [comment]
@aklaver We have master settings for every table column that specify sane default column sizes, which our users are able to resize and save as a user preference.  If all column widths sum to less than the table size, it looks kinda ugly...

**Comment by aklaver** [comment]
The best I can think of at the moment is to use fitColumns and have a dummy column that does not have a width set and has an empty title and uses say the handle formatter.

**Comment by olifolkerd** [comment]
Hey @haferje 

There is no need to generate a new header, you could simple change the CSS for the ***.tabulator-header*** class to set it to the same colour as the normal headers, which will then maintain the visual appearance for you.

Cheers

Oli :)
