### ISSUE TITLE
Tables with single row selection will allow multiple

### ISSUE THREAD

**Issue by haferje** [olifolkerd/tabulator#2068]
**Describe the bug**
When I set a table's options to `selectable: 1, selectableRangeMode: 'click',` it will allow multiple rows to be selected - either programmatically or using Shift+click.

**Tabulator Info**
- Which version of Tabulator are you using?
4.2.7
- Post a copy of your construct object if possible so we can see how your table is setup

**Working Example**
https://jsfiddle.net/haferje/gj0kampx/14/

**To Reproduce**
1. Run the example - see that two rows are selected programmatically
2. Click on an unselected row, hold Shift key, click another row - see that multiple rows in the range are selected

**Expected behavior**
If the selectable option is set to an integer, it should be a hard limit for the number of rows selected, no matter what the selectableRangeMode is.

**Comment by olifolkerd** [comment]
Hey @haferje 

Good spot!, i will look into this further

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @haferje 

I have pushed a fix for this to the 4.3 branch which i will release later today.

Cheers

Oli :)
