### ISSUE TITLE
column.getNextColumn or getPrevColumn crash when the prev or next column does not exists

### ISSUE THREAD

**Issue by labidus** [olifolkerd/tabulator#2069]
it's supposed to return false when no prev or next column but actually it's generate an error.

Uncaught TypeError: Cannot read property 'getComponent' of undefined
    at o.getNextColumn (tabulator.min.js:2)
 
As you can see

function(){
return this._column.nextColumn().**getComponent()**
}

if should do something like this instead

let column = this._column.nextColumn();
return !column ? false : column .getComponent();

thanks!

**Comment by olifolkerd** [comment]
Hey @labidus 

Sorry to hear you are having trouble, could you confirm what version of Tabulator you are using.

Can you please use the bug issue template when reporting bugs as it will prompt you to provide all the information we need to fix things.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @labidus 

I have pushed a fix for this to the 4.3 branch and will include in tomorrows release.

Cheers

Oli :)
