### ISSUE TITLE
clearFilter does not reset the filter settings

### ISSUE THREAD

**Issue by 1manfactory** [olifolkerd/tabulator#207]
I think that clearFilter does not do a clomplete job. Or I am doing something wrong.
When calling clearFilter the tab is loaded fresh with no filters on, but the filter setting (drop down selection or input values and so on) are still there. This is very confusing.
Do I have to reset every column's filter?

**Comment by olifolkerd** [comment]
Hey,

Could you post a copy of your Tabulator constructor, and the code you are using to trigger the ***clearFilter*** function, so i can run a test with your setup.

Cheers

Oli

**Comment by olifolkerd** [comment]
Are you still having issues with this?

**Comment by 1manfactory** [comment]
Yes. Still exists. Right now I just completely reload the page to reset the filters in the header section.

**Comment by olifolkerd** [comment]
Could you post a copy of your tabulator constructor and the filter functions you are using so i can isolate the issue you are having.

What browser are you using?

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey,

I have fixed this issue in the latest push to the repo, header filters should now be cleared when the ***clearFilter*** method is called.

Cheers

Oli

**Comment by 1manfactory** [comment]
GREAT
That fixes it.
But the cdnjs files are not updated yet, I had to download the files manually.
Thanks
Juergen

**Comment by olifolkerd** [comment]
Hi Juergen,

Im getting a couple of aditional features in before the next release on Wednesday.

Cheers

Oli
