### ISSUE TITLE
Feature Request: Allow Drag and Drop of a Selected Row to Second Window

### ISSUE THREAD

**Issue by rowenbuzz** [olifolkerd/tabulator#2070]
**Details**:
Although Tabulator currently allows the use of dragging and dropping rows within the table, it would be of great use to me to allow a user to utilize the drag and drop events found in the following HTML documentation from Mozilla:
  ##https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API 

**General Solution**:
Allow a user to select a Tabulator Row (via click) and drag that row from Window 1, to Window 2.
![drag_and_drop_events](https://user-images.githubusercontent.com/35744022/57856174-6db96600-77ba-11e9-9ae4-949ec924d08c.png)

**Reasoning**:
Adding the drag and drop events would allow me to:
(1) Load a chart related to the data found in the table
(2) Capture the ondrag, ondrop, ondragenter, etc. events and manipulate the data, or fire off another event, with the given row's data.
(3) Load a specific filename that is found in a column of the row's data.

**Comment by olifolkerd** [comment]
Hey @rowenbuzz 

Thanks for the great idea, you can currently drag and drop between tables on the same page.

I will need to investigate this further as that API is not compatible with some mobile browsers so could cause some issue, but i will certainly add it to the roadmap for further investigation.

Cheers

Oli :)

**Comment by andreysneg** [comment]
SImple Drag N Drop .  To and From DOM elements. 
Or simple JS events   - ondrag  ondrop  . 

I want get table data after Ondrop.
