### ISSUE TITLE
Feature Request: Allow Up/Down Arrow Navigation of a Selected Row and Change Selection

### ISSUE THREAD

**Issue by rowenbuzz** [olifolkerd/tabulator#2071]
**Current Behavior**:
Currently, when a user selects a row in tabulator, if you press the Up/Down arrows you cannot move the selected row up or down within the table.  Instead, the table itself scrolls Up/Down until you reach the Top/Bottom of the table.  Then, if you keep Pressing the Up/Down arrow keys, the webpage's vertical scrollbar begins to move Up/Down.  

The following 3 Steps Show:
(1) Selecting a row with a mouse click
(2) The current behavior when Down Arrow is Pressed and a Row is Selected
(3) The desired behavior when Down Arrow is Pressed and a Row is Selected

![arrow_selection_and_nav](https://user-images.githubusercontent.com/35744022/57861304-54b5b280-77c4-11e9-91c9-7b3b091036cf.png)

**Feature**:
Capture the Up and Down arrow key events when a row is selected and move the selected/highlighted row up or down accordingly with the key-press.   

Perhaps allow the developers to specify this type of navigation as an option using the Up/Down arrows when a row is selected.

**Note**:
The table's scrollbar should stay where it is (Step 3 above), and the row selected should move accordingly.  The only time the table should move, is when the selected row needs to stay visible in the view of the table.  The image below for example, _if_ the feature was implemented, and a user kept pressing the Down Arrow key would move the selection as well as the vertical scrollbar so as to keep the selection in view.
![arrow_selection_and_nav_stay_in_view](https://user-images.githubusercontent.com/35744022/57861315-5a12fd00-77c4-11e9-87e8-b5eba97edf78.PNG)

**Comment by olifolkerd** [comment]
Hey @rowenbuzz 

Thanks for the suggestion.

Unfortunately row selection is one of the most hotly debated topics on Tabulator,

Every developer has ideas on how it should work, and they are all completely different depending on usage case. Therefore i stick to offering some simple solutions out of the box and letting developers customise things themselves.

For your usage case you could use some custom [Keybindings](http://tabulator.info/docs/4.2/keybindings#custom) to capture the navigation and change it into row selection using the [Row Component](http://tabulator.info/docs/4.2/components#component-row) navigation and selection function.

Thanks for the suggestion.

Cheers

Oli :)

**Comment by saldal** [comment]
Sorry to open again this old ticket but I can't figure out how I can use the Keybindings to fire a custom action. With the keybindings I can only associate a different key combination to existing actions (and row selection isn't in this list).
Can you please provide a code sample of what you suggested in the proposed solution?
Thanks, Sal.
