### ISSUE TITLE
Horizontal scroll bar masks data

### ISSUE THREAD

**Issue by phallett** [olifolkerd/tabulator#2076]
When looking at multiple rows, the horizontal scroll bar masks the last line of data.  Was hoping to find a setting to give it some space but couldn't, so I am guessing it is a bug?

<img width="732" alt="Screenshot 2019-05-17 at 17 00 56" src="https://user-images.githubusercontent.com/676839/57940906-6763e080-78c5-11e9-8f81-74e3c1298b44.png">

**Comment by aklaver** [comment]
Hard to say without:
    Tabulator version.
    Table constructor.
    Browser and version.

**Comment by phallett** [comment]
Sorry, thought I'd added that:

v4.2
                    var table = new Tabulator("#project-table", {                           
                        data:obj,           //load row data from array
                        layout:"fitData",    //fit columns to width of table
                        tooltips:true,            //show tool tips on cells
                        addRowPos:"top",          //when adding a new row, add it to the top of the table
                        history:true,             //allow undo and redo actions on the table
                        movableColumns:true,      //allow column order to be changed
                        pagination:"local",       //paginate the data
                        paginationSize:25,         //allow 7 rows per page of data
                        resizableRows:false,  
                        columns:[
                            {title:"Title", field:"ar_title", frozen:true, headerFilter:"input"}, 
                        {title:"StaffID", field:"sr_id", visible:false},  
                        {title:"ResourceID", field:"ra_id", visible:false},  
                        {title:"ProjectID", field:"ra_ar_id", visible:false},  
                        {title:"Week 1", field:"wk1",editor:"input",bottomCalc:"sum",bottomCalcParams:{precision:2,}, bottomCalcFormatter: colorFormatter},
                        {title:"Week 2", field:"wk2",editor:"input",bottomCalc:"sum",bottomCalcParams:{precision:2,}, bottomCalcFormatter: colorFormatter},


                        {title:"Week 103", field:"wk103",editor:"input",bottomCalc:"sum",bottomCalcParams:{precision:2,}, bottomCalcFormatter: colorFormatter},
                        {title:"Week 104", field:"wk104",editor:"input",bottomCalc:"sum",bottomCalcParams:{precision:2,}, bottomCalcFormatter: colorFormatter},       
                        ],
                            //rowClick: function(e, row) { // Trigger an alert message when the row is clicked.
                            //    data = row.getData();
                            //    fetchAllUserProjects(data.sr_id);
                            //    
                            //},
                            /*cellClick:function(e, cell){
                            // This callback is called any time a cell is edited.

                                var row = cell.getRow();
                                var data = row.getData();
                                var cellfield = cell.getField();
                                console.log(data.sr_id);
                                var newval = cell.getValue();
                                var uid  = data.sr_id;
                                var resuidcell  = data.ra_id;
                                

                                //console.log(data.ResourceID, data.UserID, data.ra_ar_id);
                                //console.log(newval, uid, resuidcell);
                                alert(newval  + ", " +  resuidcell  + ", " + cellfield);

                            },*/
                            cellEdited:function(cell){
                            // This callback is called any time a cell is edited.
                            var row = cell.getRow();
                            var data = row.getData();
                            weekno = cell.getField();
                            newval = cell.getValue();
                            var resid  = data.ra_id;
                            var uid = data.sr_id;
                            $.ajax({
                                url : "/updatera", //"{{url_for('updatera')}}", 
                                data: {weekno:weekno,newval:newval, resid:resid},
                                type: 'GET',
                                contentType: "application/json;",
                                success: function(response){
                                    console.log(response);
                                    fetchAllUserProjects(uid);

                                },
                                    error: function(error){
                                        console.log(error);
                                }
                            })
                        },


                    });
Safari Version 12.1 (14607.1.40.1.4)

**Comment by aklaver** [comment]
FYI, Tabulator versions are three digits long so 4.2.x . Can you provide the x?

Re: the progress layout. What is the paramLookup function doing?

I do not see this on my end. 
Could you put together a simple jsFiddle/codePen example that demonstrates the problem?

**Comment by phallett** [comment]
Hi, I just downloaded from here, which said 4.2?

<img width="363" alt="Screenshot 2019-05-19 at 21 16 23" src="https://user-images.githubusercontent.com/676839/57987592-72607180-7a7b-11e9-9ff4-684186dba66f.png">

    function paramLookup(cell){
        var val = cell.getValue();   
        baseval = 37;
        lowval = baseval * .7;
        highval =  baseval * 1.3;

        if (val <= lowval && val >= 1){
            return {color:"yellow",legend:true, min:0, max:48};          
        } else if (val > lowval && val < highval){
            return {color:"green",legend:true, min:0, max:48};
        } else if (val >= highval){
            return {color:"red",legend:true, min:0, max:48};
        } else if (val < 1) {
            return {color:"yellow", min:0, max:48, legend:'0'};
        }

    }

It works fine in Chrome, apart from with the scrolling issue.

**Comment by aklaver** [comment]
It will be one of these releases:
https://github.com/olifolkerd/tabulator/releases

Look at the top of the tabulator.js file.

**Comment by phallett** [comment]
Ah, apologies, 4.2.7

**Comment by phallett** [comment]
Hi,

Did you look at this perchance?

Cheers

Paul

**Comment by aklaver** [comment]
I did but could not replicate on my end. Could you put together an example on jsFiddle/CodePen that I could try?

**Comment by phallett** [comment]
Well making no sense at all, this works!!!!!!

[https://codepen.io/anon/pen/ZdzPWV](url)

Ok, What I will do is strip down the application and add each new table one at a time.  That way I'll see what issues are happening I think.  Simply maddening!

Great kit, love it.  Must be some code I have introduced!

**Comment by phallett** [comment]
Could I possibly give you my html, JS and the data in the form of Json strings, as I cannot get it to work, but the code in the codepen is precisely what I am using, but I getting the data back from an Ajax call, which populates the data.  The data I used In codepen is simply redacted and shortened  version of it.  If I can email you the details in total, can you see if there's something obvious.  I am genuinely flummoxed by it, as it's precisely the same, but works in codepen?

**Comment by aklaver** [comment]
Yeah you can do that. Click on my profile picture and you will see my email. Probably won't be able to get  to this until tomorrow though.

**Comment by phallett** [comment]
Thanks a lot, I've sent as much as I think you need, please let me know if you need more.

I really appreciate this; I am tearing my hair out, something I can ill afford.

**Comment by phallett** [comment]
Ok, I have solved this.  Quite simple really, it happened as I had not closed off two <div> tags.  

I had this:

            <h5 class="card-header">details</h5>
            <div id="user-table"></div><br>
            <h5 class="card-header">allocation details</h5>
            <div id="user-project-table"></div><br>
            <h5 class="card-header"> same team</h5>
            <div id="user-colleague-table"></div><br>
            <h5 class="card-header"> different team</h5>
            <div id="user-non-colleague-table"></div><br>
        </div>
    </div> 

instead of this:

    <div class="card ">
        <div class="card-body">
            <h5 class="card-header"> details</h5>
            <div id="user-table"></div><br>
            <h5 class="card-header"> allocation details</h5>
            <div id="user-project-table"></div><br>
            <h5 class="card-header"> same team</h5>
            <div id="user-colleague-table"></div><br>
            <h5 class="card-header"> different team</h5>
            <div id="user-non-colleague-table"></div><br>
        </div>
    </div> 


<img width="751" alt="Screenshot 2019-06-11 at 10 16 58" src="https://user-images.githubusercontent.com/676839/59259791-52633e80-8c32-11e9-8da2-0fbc1aceb7e5.png">

I knew it would be something simple, but thanks for looking at this.  If you have malformed html, it will mess with the formatting of the table.

**Comment by aklaver** [comment]
Glad you solved it.

**Comment by phallett** [comment]
Thanks for persevering with me!  Apologies, I knew it would be something simple, but tracking it down was painful.

Thanks again.
