### ISSUE TITLE
Validator triggers 3 times on first error

### ISSUE THREAD

**Issue by shadlan** [olifolkerd/tabulator#2077]
**Describe the bug**
When the validation fails, the validationFailed callback runs three times, showing more messages than it should.

**Tabulator Info**
Tabulator v.4.2.7

**Working Example**
https://jsfiddle.net/nakd7xgu/

**To Reproduce**
On the example, click on Billy Bob's age and change it to a number above 100.

**Expected behavior**
Only one message should appear on the error-list.

**Comment by prsanjay** [comment]
@olifolkerd , Is there any solution you implemented for this? I am also facing the same issue. Using v4.7.
