### ISSUE TITLE
headerFilter:dateFilterEditor is not firing when using ajaxURL

### ISSUE THREAD

**Issue by ronbanks** [olifolkerd/tabulator#2079]
**Describe the bug**
I have a ```headerFilter:dateFilterEditor``` in a constructor for a date-range filter based on the original code from [here](https://github.com/olifolkerd/tabulator/issues/1011). It worked successfully on a constructor using a regular ajax call to obtain data but for some reason in a copy/paste version on another page except using ```ajaxURL```, it doesn't seem to call the ```dateFilterEditor``` function. There are no errors but a ```console.log``` inside the function indicates that it's never called.

**Tabulator Info**
```Tabulator v4.2.3```
```
counties_data = new Tabulator("#counties-data", {
	ajaxURL: "data/data.php",
	ajaxParams: {'get_data': '1', 'src': 'counties_data'},
	ajaxFiltering:true,
	ajaxSorting:true,
	pagination: "remote",
	paginationSize: 500,
	height: "800px",
	columns:[
		{title:"Id", field:"id", headerFilter:"input", headerFilterPlaceholder:"filter...", width:80},
		{title:"Date Created", field:"date_created", headerFilter:"input", headerFilterPlaceholder:"filter...", width:150},
		{title:"County", field:"county", headerFilter:"input", headerFilterPlaceholder:"filter...", width:123},
		{title:"Record Type", field:"record_type", headerFilter:"input", headerFilterPlaceholder:"filter...", width:120},
		{title:"Series", field:"series", headerFilter:"input", headerFilterPlaceholder:"filter...", width:98},
		{title:"Number", field:"number", headerFilter:"input", headerFilterPlaceholder:"filter...", width:92},
		{title:"Instrument Type", field:"instrument_type", headerFilter:"input", headerFilterPlaceholder:"filter...", width:189},
		{title:"Instrument Class", field:"instrument_class", headerFilter:"input", headerFilterPlaceholder:"filter...", width:152},
		{title:"Doc Number", field:"doc_number", headerFilter:"input", headerFilterPlaceholder:"filter...", width:124},
		{title:"Book", field:"book", headerFilter:"input", headerFilterPlaceholder:"filter...", width:78},
		{title:"Page", field:"page", headerFilter:"input", headerFilterPlaceholder:"filter...", width:78},
		{title:"Doc Stamps", field:"doc_stamps", headerFilter:"input", headerFilterPlaceholder:"filter...", width:133},
		{title:"Consideration", field:"consideration", headerFilter:"input", headerFilterPlaceholder:"filter...", width:133},
		{title:"File Date", field:"file_date", align:"center", sorter:"date", headerFilter:dateFilterEditor, headerFilterFunc:dateFilterFunction, width:290},
		{title:"Grantor", field:"grantor", headerFilter:"input", headerFilterPlaceholder:"filter...", width:110},
		{title:"Grantee", field:"grantee", headerFilter:"input", headerFilterPlaceholder:"filter...", width:110},
		{title:"Legal", field:"legal", headerFilter:"input", headerFilterPlaceholder:"filter...", width:185},
		{title:"Sec", field:"sec", headerFilter:"input", headerFilterPlaceholder:"filter...", width:63},
		{title:"Twn", field:"twn", headerFilter:"input", headerFilterPlaceholder:"filter...", width:63},
		{title:"Rng", field:"rng", headerFilter:"input", headerFilterPlaceholder:"filter...", width:63},
		{title:"Twn Rng", field:"twn_rng", headerFilter:"input", headerFilterPlaceholder:"filter...", width:100},
		{title:"STR", field:"str", headerFilter:"input", headerFilterPlaceholder:"filter...", width:100},
		{title:"GIS STR", field:"gis_str", headerFilter:"input", headerFilterPlaceholder:"filter...", width:125},
		{title:"Img Src", field:"img_src", headerFilter:"input", headerFilterPlaceholder:"filter...", width:100},
	],
});

//custom header filter
var dateFilterEditor = function(cell, onRendered, success, cancel, editorParams){

	var container = $("<span></span>");
	//create and style input
	var start = $("<input type='date' placeholder='Start'/>");
	var end = $("<input type='date' placeholder='End'/>");

	container.append(start).append(end);

	var inputs = $("input", container);


	inputs.css({
		"padding":"2px",
		"width":"50%",
		"box-sizing":"border-box",
	})
	.val(cell.getValue());

	function buildDateString(){
		return {
			start:start.val(),
			end:end.val(),
		};
	}

	//submit new value on blur
	inputs.on("change blur", function(e){
		console.log(start.val());
		// counties_data.clearHeaderFilter();
		if ( start.val() == '' && end.val() == '' )
		{
			counties_data.setHeaderFilterValue('file_date', null);
			return false;
		}
		else
		{
			success(buildDateString());
		}
	});

	//submit new value on enter
	inputs.on("keydown", function(e){
		if(e.keyCode == 13){
			success(buildDateString());
		}

		if(e.keyCode == 27){
			cancel();
		}
	});

	return container[0];
}

//custom filter function
function dateFilterFunction(headerValue, rowValue, rowData, filterParams){
	//headerValue - the value of the header filter element
	//rowValue - the value of the column in this row
	//rowData - the data for the row being filtered
	//filterParams - params object passed to the headerFilterFuncParams property

	var format = filterParams.format || "YYYY-MM-DD";
	var start = moment(headerValue.start);
	var end = moment(headerValue.end);
	var value = moment(rowValue, format)
	if(rowValue){
		if(start.isValid()){
			if(end.isValid()){
				return value >= start && value <= end;
			}else{
				return value >= start;
			}
		}else{
			if(end.isValid()){
				return value <= end;
			}
		}
	}

	return false; //must return a boolean, true if it passes the filter.
}
```
**Working Example**
I'm hoping that someone has a quick solution for this, I will put up a codepen as soon as possible but I have to attend to something else right now.

**To Reproduce**
Load page and no header filter inputs are appended and no errors reported.

**Expected behavior**
The ```headerFilter:dateFilterEditor``` should be fired and inputs appended.

**Screenshots**
![image](https://user-images.githubusercontent.com/6586396/58030067-863fbe00-7ae3-11e9-9dcf-f8e809bb227f.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] ```Fedora 28```
 - Browser [e.g. chrome, safari] ```Chrome```
 - Version [e.g. 22] ```Version 74.0.3729.131 (Official Build) (64-bit)```
but this happens regardless of OS/browser/mobile that I've tried it on.

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aklaver** [comment]
I don't see the code for dateFilterFunction in your example. Is it in the new page?
Can you explain more about what changed with the Ajax setup?

**Comment by ronbanks** [comment]
sure, below is the ```dateFilterFunction``` but it's the ```dateFilterEditor``` that is not being called. In the page that worked as expected, I was using a regular jquery ajax call to pull the data and calling a function to construct the table ```function render_tbl_export(tabledata)``` and assigning the data ```data:tabledata,``` and on the new page that isn't working I'm using the tabulator internal ajax functioning ```ajaxURL: "data.php",``` to pull the data. The data is being returned in both cases just fine. I just don't know why in the exact same column constructor the ```headerFilter:dateFilterEditor``` doesn't seem to be calling the ``dateFilterEditor``` function, nor is it throwing any error?

```
//custom filter function
function dateFilterFunction(headerValue, rowValue, rowData, filterParams){
	//headerValue - the value of the header filter element
	//rowValue - the value of the column in this row
	//rowData - the data for the row being filtered
	//filterParams - params object passed to the headerFilterFuncParams property

	var format = filterParams.format || "YYYY-MM-DD";
	var start = moment(headerValue.start);
	var end = moment(headerValue.end);
	var value = moment(rowValue, format)
	if(rowValue){
		if(start.isValid()){
			if(end.isValid()){
				return value >= start && value <= end;
			}else{
				return value >= start;
			}
		}else{
			if(end.isValid()){
				return value <= end;
			}
		}
	}

	return false; //must return a boolean, true if it passes the filter.
}
```

**Comment by aklaver** [comment]
I was just making sure the function was actually there. It should throw an error if it was not, but better safe then sorry.   I can't see anything obviously wrong with the table layout. The only thing I can think of is the data itself. Have you looked at the data in the file_date column in your tabledata array vs what is coming straight from the URL?

**Comment by ronbanks** [comment]
the data is from the same db table and the data comes through in both cases, eg., ```2018-01-02```, the only thing that is different is the external vs internal ajax call. I'm assuming that it's something to do with that but don't really know since I'm not seeing any errors.

**Comment by ronbanks** [comment]
perhaps I could look within the tabulator.js to try to catch where this might be happening, not sure where that might be though. I was just hoping that someone had ran into this before. I've only starting using tabulator in this project, so not too familiar with it yet, but thus far have been quite satisfied with it. I just feel like this is something simple that I'm overlooking, but without error it makes it difficult.

**Comment by aklaver** [comment]
Are you using the ajaxFiltering and ajaxSorting?
To troubleshoot this I would start at a simple starting point; just the remote Ajax call with no ajax*,  headerFilter: true, no headerFilterFunc.
Then make one change at a time to see where thing break down.

**Comment by ronbanks** [comment]
yes, as the example indicates, I am using ajaxFiltering and ajaxSorting. I just tried it with/without them and had same result. Do you know where in tabulator.js that the ```headerFilter``` makes the call to ```dateFilterEditor```?

**Comment by ronbanks** [comment]
well, it appears to be a timing issue, I wrapped in a ```$( document ).ready(function() {});``` and it works now... Thanks...

**Comment by aklaver** [comment]
Glad to see you got it working.
FYI, ajaxFiltering/Sorting means you do the action on the server not in the table. It was not obvious to me whether that was in fact being done.

**Comment by ronbanks** [comment]
understood, and again, that didn't have anything to do with the issue in question. Thanks...
