### ISSUE TITLE
Enhancement: Provide a way to change the placeholder for the filters

### ISSUE THREAD

**Issue by bvisonl** [olifolkerd/tabulator#208]
Right now the headerFilterPlaceholder property appears to be fixed to 'filter column....'. I tried to override the headerFilterPlaceholder property on a per-column basis and I wasn't able to , I noticed that you can do it globally for the whole tabulator but I wanted to put the column name as placeholder and in spanish for each column header filter..

Let me know if this makes sense.

**Comment by olifolkerd** [comment]
Hey,

You can globally set the header filter test using the ***headerFilterPlaceholder*** property:
```js
$("#example-table").tabulator({
    headerFilterPlaceholder:"enter your filter data here",
    columns:[...],
});
```

But at present there is no way to do it on a column by column basis. This will be coming in this months release.

Cheers

Oli

**Comment by alainpannetier** [comment]
There would be a way to do so with jquery and the data loaded callback no?
 - Either Targetting each column from its label.
 - Or going through the columns collection of the tabulator("instance")
If you're still looking for a solution : )

**Comment by olifolkerd** [comment]
Hey,

I have just pushed this change to the repo, you can now do this using the ***headerFilterColumnPlaceholders*** option, pass in a b=object with key value pairs for the column field and the placeholder test you want to display:
```js
$("#example-table").tabulator({
    headerFilterPlaceholder:"filter data...", //set column header placeholder text
    headerFilterColumnPlaceholders:{
        name:"choose your name", //set placeholder text on name column header filter
    },
});
```
Full details on how to use this feature can be found [here](http://olifolkerd.github.io/tabulator/docs/#filtering)

Cheers

Oli
