### ISSUE TITLE
4.2.5 Row.prototype.wipe row.element removal confusion

### ISSUE THREAD

**Issue by Alarich** [olifolkerd/tabulator#2080]
**Describe the bug**
I believe a change made in 4.2.5 to set the row.element as false causes issues in some situations.

The code is here:
https://github.com/olifolkerd/tabulator/compare/4.2.4...4.2.5#diff-829aa243ac7a36e8f091529d1289fda9R759

My issue comes from RowManager.prototype._virtualRenderFill. When it is called, self.getDisplayRows() contains Row objects which have row.element = false, which causes this function to give an error at self.styleRow(row, index), when it is attempting to add a class to the row.element.classList.
The self.styleRow and others after it are just the symptons, **the actual error seems to be that RowManager.displayRows contains rows with row.element = false**, which seem to be Row objects that are no longer usable and are set to be destroyed.
After a wipe, the rows are removed from RowManager.rows, but the instances still exist in RowManager.displayRows and possibly RowManager.activeRows.

The solution would probably be to also wipe activeRows, displayRows and set displayRowsCount to 0.

**Tabulator Info**
- 4.2.5 and higher

**Working Example**
I'm sorry I can't currently, perhaps the description is enough. Otherwise I'll try to create an example of it.

**Expected behavior**
RowManager.displayRows should not contain invalid objects.

**Screenshots**
http://prntscr.com/nr0b7c

**Additional context**
The state, in which RowManager.displayRows have not yet been reset while RowManager.rows are, could be due to something with my setup. Although I would argue that they should not be handled in a way that could cause invalid objects to exist in any of the containers used in Tabulator.

**Comment by olifolkerd** [comment]
Hey @Alarich 

Im afraid i dont understand the usage case for this, rather than taking me through the code could you explain under what circumstance you encounter the error.

Cheers

Oli :)

**Comment by Alarich** [comment]
Greetings @olifolkerd 

Thanks for the reply!

I'm using the dataLoaded event to conditionally update the table height - to match the height to row count, for example, which requires me to set a new height to Tabulator, which gives the error.
From the library I see that dataLoaded is called right before refreshActiveData, that's why the activeRows still contain the old data with removed row.element.

I switched to using renderStarted, which actually makes much more sense now that I think about it.

So, I suppose my problem is fixed, but I'm unsure if this issue should be classified as a bug or not. In dataLoaded I think we should not be attempting anything that would cause a redraw.

**Comment by olifolkerd** [comment]
Hey @Alarich 

If you always want the table to fit the number of rows, just turn of the virtual DOM, it will then do this automatically.

```js
var table = new Tabulator("#example-table", {
    virtualDom:false, //disable virtual DOM rendering
});
```

I hope that helps,

Cheers

Oli :)

**Comment by Alarich** [comment]
Hi @olifolkerd!

The resize logic is actually tied to multiple parameters, like external container height, x row height. But I'll try and see what disabling virtualDom would do for me. 

Thanks for the tip :)

**Comment by Alarich** [comment]
In the context of this issue, the solution would be to utilize another callback, thus the original point is no longer a problem.

Perhaps the only change needed would be to add a clause to the dataLoaded event that a redraw of the table should not be called during that event.

I'm closing the issue to clean up the list and because a solution was found.
