### ISSUE TITLE
Add Materialize To Packaged Themes

### ISSUE THREAD

**Issue by Elstermann** [olifolkerd/tabulator#2081]
Would be awesome to see https://materializecss.com on the list of "Packaged Themes".
Thank you for your great work, anyway!

**Comment by olifolkerd** [comment]
Hey @Elstermann 

Thanks for the recomendation.

I have the material design theme coming out in the 4.3 release. so i would only be able in to add this in the 4.4 release or later.

If you wanted to see it in sooner i would be happy to accept a pull request.

Cheers

Oli :)

**Comment by Elstermann** [comment]
Dear @olifolkerd,

thank you very much for your quick reply. I just startet working with Tabulator yesterday (loving it already).
So I don't have a clue how to implement a theme packaging yet. If you have some kind of guide/tut to show me the first steps at least I would consider to do the work. Is ist "just" kind of translating the namespace of Materialize selectors to Tabulator selectors? Like replace: ".materialize-row" with ".tabulator-row" (fictive example)?

**Comment by olifolkerd** [comment]
Hey @Elstermann 

Great to hear you are enjoying using Tabulator.

I usually start making a theme by creating a sew directory in the src/scss directory for the theme.

i then copy the tabulator.scss file into the folder as a starting point.

Then i find the scss variables file for the theme i am trying to mimic and copying that into this folder. 

Then i try and map those variables onto the tabulator scss, most of them can simply be set to the existing variables at the top of the tabulator scss file.

I hope that makes sense.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @Elstermann 

I have just pushed a materialized theme to the 4.5 branch that will be released in a few weeks.

Cheers

Oli :)

**Comment by Elstermann** [comment]
AWESOME :)
