### ISSUE TITLE
Set "headerSortTristate" On Higher Level(s)

### ISSUE THREAD

**Issue by Elstermann** [olifolkerd/tabulator#2083]
__Current Behavior | per column basis__
If I'd like to have tristate sorting I have to set it on a per column basis, which feels cumbersome if I want to have it on all columns.
```
new require('tabulator-tables')('selector', {
    data: { k1: 'v1', k2: 'v2' },
    columns: [
        {
            title: 'K1',
            field: 'k1',
            headerSortTristate: true // enable tristate sorting per column
        },
        {
            title: 'K2',
            field: 'k2',
            headerSortTristate: true // enable tristate sorting per column again & again
        },
    ]
});
```

__Desired Behavior | per table & column basis__
Set tristate sorting as a default value for all columns in advance plus having the ability to overwrite the default settings on per column basis.
```
new require('tabulator-tables')('selector', {
    headerSortTristate: true, // enable tristate sorting for all columns in advance
    data: { k1: 'v1', k2: 'v2' },
    columns: [
        {
            title: 'K1',
            field: 'k1',
            headerSortTristate: false // overwrite tristate sorting per column (optional)
        },
        {
            title: 'K2',
            field: 'k2'
        },
    ]
});
```

__Desired Behavior | per factory & table & column basis__
Set tristate sorting as a default value for "all" tables and all columns in advance plus having the ability to overwrite the default settings on a per table and per column basis.
```
let Tabulator = require('tabulator-tables');
// set tristate sorting for the factory object
Tabulator.defaults('headerSortTristate', true);
// or "setting-multiple-defaults-at-once"-syntax
Tabulator.defaults({headerSortTristate: true});
new Tabulator('selector', {
    // headerSortTristate is already set to true but can be overwritten per table as well (optional)
    data: { k1: 'v1', k2: 'v2' },
    columns: [
        {
            title: 'K1',
            field: 'k1',
            headerSortTristate: false // overwrite tristate sorting per column (optional)
        },
        {
            title: 'K2',
            field: 'k2'
        },
    ]
});
```

Cheers

Axel :)

**Comment by Elstermann** [comment]
BTW: The concept/functionality described above would be nice to see on all (at least a lot of) settings/options that are currently only available on a per column-/row-/cell-basis. Just to name a few:

- `headerFilter`
- `bottomCalc`, `topCalc`
- `editor`
- `validator`

Maybe this could be implemented as a core concept?

Cheers Again :)

Axel

**Comment by olifolkerd** [comment]
Hey @Elstermann 

Thanks for getting in touch, and thanks for the suggestion.

It would seem a bit of a confusing form of user interaction if the sort toggle was different per column, how would a user know what is expected?

Cheers

Oli :)

**Comment by Elstermann** [comment]
Dear @olifolkerd,

right you are. And so it is by now!

By now the `headerSortTristate`-option is on a __per column basis__. And as you pointed out having different features for each column may be not ideal from the UX-perspective.

By now the developer must set the option for each column over and over again instead of setting it on a higher level as I suggest with this feature request.

I also recommend this  for "all" other options that are currently set on a per column/row basis.

__Current Behavior | set `headerSortTristate`-option per column__
```
columns[
    {headerSortTristate: true}, {headerSortTristate: true}, {headerSortTristate: true}
]
```

__Desired Behavior | set `headerSortTristate`-option per table__
```
columns[
    headerSortTristate: true,
    {}, {}, {}
]
```

But I would leave the decision on how to setup the table on the developer. So still having the ability to overwrite options that are set on a higher level would be ideal imho.

Cheers

Axel :)

**Comment by tentus** [comment]
For what it's worth, this seems like a good idea to me as well, I was surprised when it wasn't already the case.

**Comment by olifolkerd** [comment]
Hey @Elstermann 

Thanks for the feedback, i will consider it for addition to the roadmap.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @Elstermann 

I have pushed this to the 4.4 branch which will be released later today

Cheers

Oli :)
