### ISSUE TITLE
Support nested column groups

### ISSUE THREAD

**Issue by mrodal** [olifolkerd/tabulator#2087]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to further group columns to give them a more defined scope

**Describe the solution you'd like**
Something like this
![image](https://user-images.githubusercontent.com/20667544/58139987-ab334e80-7c13-11e9-9640-b3a3da802e2e.png)

**Describe alternatives you've considered**
The altenetive now is to use just Parent Group or both child groups

**Additional context**
-

**Comment by olifolkerd** [comment]
@mrodal This is already a feature,

You just need to nest your column group deifintions:

```js
var table = new Tabulator("#example-table", {
    columnVertAlign:"bottom", //align header contents to bottom of cell
    columns:[
        {title:"Name", field:"name", width:160},
        {//create column group
            title:"Work Info",
            columns:[
            {title:"Progress", field:"progress", align:"right", sorter:"number", width:100},
            {title:"Rating", field:"rating", align:"center", width:80},
            ],
        },
        {//create column group
            title:"Personal Info",
            columns:[
            {title:"Gender", field:"gender", width:90},
            { //create second level column group
                title:"Additional Info",
                columns:[
                    {title:"Favourite Color", field:"col", width:140},
                    {title:"Date Of Birth", field:"dob", align:"center", sorter:"date", width:130},
                ],
            },
            ],
        },
    ],
});
```

I hope that helps,

Cheers

Oli :)

**Comment by mrodal** [comment]
Wow thanks! I swear I tried that before posting the issue.. looks like I was kind of distracted 😄
