### ISSUE TITLE
creating new blank row, where editor is set to textarea, still adds "undefined" to cell in 4.2

### ISSUE THREAD

**Issue by rhagstrand** [olifolkerd/tabulator#2088]
**Describe the bug**
creating new blank row, where editor is set to textarea, adds "undefined" to cell when new row is edited. related to issue 1430

**Tabulator Info**
4.2

**To Reproduce**
You can use this example: http://tabulator.info/examples/4.0#adddel
But change editor to "textarea"

**Comment by olifolkerd** [comment]
Hey @rhagstrand 

Thanks for rasing this, could you confirm the patch number of the version you are using, this is very important when addressing bugs as there are several patch releases for each minor version.

Cheers

Oli :)

**Comment by rhagstrand** [comment]
Hi! 

It says 4.2.7 as version. Thanks for looking into this.

regards
/Rickard

**Comment by joshkpeterson** [comment]
Can repro on 4.2.7

One workaround for this is to have the new row invocation be something like:

`yourTabulator.addRow({yourFieldNameHere: null});
`

**Comment by olifolkerd** [comment]
Hey @rhagstrand 

I have pushed a fix for this to the 4.3 branch and will include it in tomorrows release.

Cheers

Oli :)
