### ISSUE TITLE
onclick + editable:true ...    editable not works

### ISSUE THREAD

**Issue by coldev** [olifolkerd/tabulator#209]
Thanks 4 this excelent library ...

i have a any questions...

Using editable cells , some events not triggered...

+ i declare custom editor as in examples

then...  

1. event row click only works in rows frozen , in rows editables not works

       rowClick:function(e, id, data, row){
         console.log('click row ');
       },

   editing not working but click trigger yes...

**Comment by olifolkerd** [comment]
Hey,

Could you post a copy of your Tabulator constructor so i can replicated your table when testing this.

Cheers

Oli

**Comment by olifolkerd** [comment]
are you still having issues with this?

**Comment by coldev** [comment]
Thanks 4 this excellent library

 i share a possible bug or feature not documented...

when i declare cell click event works ok...
but..  cell editor not works.. in editable cells.. (onclick + editable:true = editable not works)
see console.log 4 more details

[https://mega.nz/#!HQNBEJrb!j0LMba1rOTET-nc23z35mm48xGEft_BKvdS-dsM-qhA](url)

**Comment by olifolkerd** [comment]
Hey,

I have run the example you provided and the ***rowClick*** event is triggered correctly in editable cells.

Which browser are you using?

Cheers

Oli

**Comment by coldev** [comment]
rowclick works ok

but editable not...

windows 10 x64 +  chrome 56.0.2924.87 (64-bit)

in my browser haves very weird behavior... (edit row not works)

**Comment by silv2015** [comment]
Hi! Thanks for this library, we are using it in all our web application!

We are experiencing the same problem as we want to close a small popup when we click on a cell.

the onclick event of a specific cell works well and close the popup as we want it to do but the cell does not allow to be edited

Windows 10 x64 and Windows 7 x64 with Chrome 56.0.2924.87 (64-bit)

Thanks

**Comment by olifolkerd** [comment]
Hey,

I have fixed the issue, the editing was being blocked by the **_onClick_**. now if you have a cell with **_onClick_** and **_editable_** the editing should work fine.

The **_onClick_** and **_rowClick_** are blocked by design when editing is present on cell. the reason for this is to prevent user selection events (moving a slider, selecting stars, changing a select box) from inadvertently triggering the callbacks.

Cheers

Oli

**Comment by phanhuudinh** [comment]
> The **_onClick_** and **_rowClick_** are blocked by design when editing is present on cell.

Hi @olifolkerd , I'm implement a custom editor cell for my table, it very hard without onClick event, do you have any alternative solution.

**Comment by olifolkerd** [comment]
you can use the ***cellEditing*** in addition to the ***cellClick*** and ***rowClick*** events to handle all scenarios
