### ISSUE TITLE
Double click inside cell triggers cell click twice.

### ISSUE THREAD

**Issue by fingers10** [olifolkerd/tabulator#2091]
Dear Oli,

Again, thanks for the awesome Tabulator. 

I'm facing a issue in Tabulator V4.2.3. I have a cell with `cellClick` function as below

    cellClick: function (e, cell) {
        console.log("click");
    }

when I double click, this cellClick function is triggered twice. I can see two console logs. I'm confused whether this is an issue with Tabulator or Javascript/browser. I checked in Chrome, this causes my logics to run twice. And I don't have any `cellDblClick` configured for the cell. Any idea on how this can be resolved?

Please assist.

Thanks,
Abdul

**Comment by aklaver** [comment]
From Tabulator cell.js:
`//set event bindings
  if (cellEvents.cellClick || self.table.options.cellClick){
           element.addEventListener("click", function(e){
`
From here:
https://developer.mozilla.org/en-US/docs/Web/Events
"click | A pointing device button (ANY button; soon to be primary button only) has been pressed and released on an element."

So the event callback is doing what it is supposed to. To change that would seem to involve an external mechanism to add a delay between clicks for responding to the event.

**Comment by aklaver** [comment]
Just learned something new. The click event:

https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event

tracks the number of clicks in a detail property. So something like:
`cellClick: function (e, cell) {
        if (e.detail > 1)
            {console.log("dblclick");}else{console.log("click")};
    },
`would work. At least it does here of Firefox and Chrome.

**Comment by olifolkerd** [comment]
@fingers10 

This is standard behaviour, the browsers click event will do the same thing.

@aklaver  offers the best solution.

Cheers

Oli :)
