### ISSUE TITLE
Programatically add / remove Calculations

### ISSUE THREAD

**Issue by TMCentral** [olifolkerd/tabulator#2094]
It does not appear you can remove calculations programatically.  While we have figured out a way to add calculations (getting the current columns definitions, adding the bottomCalc property to the column desired and then re-adding all of them), removing the bottomCalc property does not seem to remove the old calculation.  Make sense?

**Comment by TMCentral** [comment]
Below's a code sample... I know this may not be the intended way to do it, but if it is or could be, the other thing to note is that the 2nd (added) column calculation added only shows the total - not per Group.
  //Sample below will not remove Calculation as needed 
  //on column index 1 but will add it to column index 2 (Total only / not Group(s))
  var colDefs = table.getColumnDefinitions();
  delete colDefs[1].bottomCalc;
  colDefs[2].bottomCalc="count";
  table.setColumns(colDefs);

**Comment by olifolkerd** [comment]
Hey @TMCentral 

Thanks for getting in touch, would you be able to create a JS fiddle that demonstrates your issue, it iw quite difficult to offer the correct advice without understanding how tour table is setup.

Cheers

Oli :)
