### ISSUE TITLE
Memory leak after a series of row updates followed by treeExpand

### ISSUE THREAD

**Issue by anurag-23** [olifolkerd/tabulator#2097]
**Describe the bug**
I have a single row in my Tabulator, with 123 children and a total of 729 grandchildren (dataTree depth is 2).

I get signals in regular intervals which require the updation of a particular child/grandchild of the row with new data. On receiving the signal, I update the row using row.update(). The frequency of the signal is about 50 updates per minute.

However, on every successive update, the memory usage keeps increasing linearly. I have observed this with the updateRow(), setData() and updateData() functions as well. After around 300-400 update calls, memory usage crosses **1 GB**.

**Tabulator Info**
- Tabulator v4.2.7
- The table has a custom row formatter for a checkbox, with a listener added to the checkbox, as well as one editable column, and listeners for expand, collapse and double click.
- Virtual DOM is enabled by setting height to 100%

**To Reproduce**
Repetition of the following steps causes consistent increase in memory usage:

1. Get a row and then its child/grandchild by using the row index and child position in row.getTreeChildren()
2. Update the row by first modifying the child data and then calling any of the update functions.
3. Use treeExpand() on the parent(s) of the child/grandchild obtained in step 1, so that when a child or grandchild is updated, it becomes visible. The child is then focused using scrollTo().

NOTE: 
i. A different row/child/grandchild is updated on each signal.
ii. Omitting step 3 causes the memory utilization to be low and stable. Keeping the row in an expanded state causes the issue.
iii. If step 3 is carried out without actually updating the row in step 2, then memory usage is low.
iv. On stopping this updation process, the memory usage becomes near-constant, and doesn't decrease significantly even after calling table.clearData() or assigning the table variable to null.

**Expected behavior**
The memory usage should become stable after a point, whether the row is expanded or collapsed. Currently it crosses 1 GB within a few minutes.

**Desktop:**
 - OS: Windows
 - Browser: Chromium (In an Electron application) 
 - Version: Electron v4.0.7

**Additional context**
The row is therefore always in an expanded state, since it is expanded after every update. I suspect the garbage collector finds the older row objects to be in-use and therefore doesn't clear them.

**Comment by olifolkerd** [comment]
Hey @anurag-23 

I would either need to see the constructor object for your table, or a JS fiddle of it in action if i am to understand how to configure a table to replicate your issue.

Cheers

Oli :)
