### ISSUE TITLE
Handle click event in custom editor

### ISSUE THREAD

**Issue by phanhuudinh** [olifolkerd/tabulator#2099]
Since "The onClick and rowClick are blocked by design when editing is present on cell"
How can I develop my own cell editor without click event?

**Comment by aklaver** [comment]
Would this work?:
http://tabulator.info/docs/4.2/edit#edit-custom

**Comment by phanhuudinh** [comment]
> Would this work?:
> http://tabulator.info/docs/4.2/edit#edit-custom

Right, I know how to implement a custom editor, but problem is `The onClick and rowClick are blocked by design`

**Comment by aklaver** [comment]
Can't you use the cellClick callback? If not you will need to be more specific about what you need to do with the click event?
