### ISSUE TITLE
How to filter with remote pagination?

### ISSUE THREAD

**Issue by fhariano** [olifolkerd/tabulator#210]

**Comment by olifolkerd** [comment]
Hey,

Thanks for getting in touch.

Could you provide a bit more information please:

- How do you intend to filter your data, will you be using header filters or the ***setFilter*** function?
- Could you post a copy of your Tabulator constructor so i can provide a solution that fits with your table.

Cheers

Oli

**Comment by fhariano** [comment]
Hi.
I'm using the setFilter function with input text and button action, but when the setFilter is called isn't sent the request of filter to the server, and is just filtered the first page.

**Comment by fhariano** [comment]
Hi.
I'm using the setFilter function with input text and button action, but when the setFilter is called isn't sent the request of filter to the server, and is just filtered the first page.

**Comment by olifolkerd** [comment]
Hey,

filtering is only carried out locally within the table, if you want to include filter information in the pagination request then you will need to use a custom paginator that adds these values to your request:

```js

var filter = "cheese";

$("#example-table").tabulator({
    pagination:"remote", //enable remote pagination
    ajaxURL:"http://testdata.com/data", //set url for ajax request
    paginator: function(url, pageNo, pageSize, ajaxParams ){
        //url - the url from the ajaxURL paramter
        //pageNo - the requested page number
        //pageSize - the value of the paginationSize paramter
        //ajaxParams - the value of the ajaxParams parameter

        return url + "?page=" + pageNo + "&filter=" + filter;
    },
});
```
More details on this can be found [here](http://olifolkerd.github.io/tabulator/docs/#pagination)

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey,

If you are using ajax pagination the data will be passed to the server in the following parameters:

- page - the page number being requested
- size - the number of rows to a page (if paginationSize is set)
- sort - the currently sorted field (if data is sorted by user)
- sort_dir - the current sort direction (if data is sorted by user)
- filter - the currently filtered field (if data is filtered by user)
- filter_value - the current filter value (if data is filtered by user)
- filter_type - the current filter type (if data is filtered by user)

If you use the network tab of your browsers dev console you should see them in the request.

Let me know if you run into any issues.

Cheers

Oli
