### ISSUE TITLE
Select editor doesn't open on last rows when the table is as high as the visible area.

### ISSUE THREAD

**Issue by shadlan** [olifolkerd/tabulator#2100]
**Describe the bug**
Select editor doesn't open on last rows when the table is as high as the visible area.

**Tabulator Info**
v4.2.7

**Working Example**
https://jsfiddle.net/fs95hxdr/

**To Reproduce**

* Open the fiddle.
* Make sure that the table fills the height as to reach the bottom of the page. Make sure that it doesn't overrun this height. There should be no page scrollbar.
![image](https://user-images.githubusercontent.com/1183122/58464639-fb3b7500-812d-11e9-85b0-5d4ed1070546.png)
* Try to open one of the bottom names

**Expected behavior**
The select should open up (dropup) in these extreme situations

**Comment by shadlan** [comment]
UPDATE: Forcing a vertical scroll bar with CSS (overflow-y: scroll) on the html base tag allows it to open, even if it's off-screen

https://jsfiddle.net/0p4qwk3j/

**Comment by olifolkerd** [comment]
Hey @shadlan 

That fiddle works fine for me on chrome, could you confirm which browser you are using?

The overflow of the table should have nothing to do with it as the select should be appended directly to the page body.

Cheers

Oli :)

**Comment by shadlan** [comment]
Sorry for my late reply Oli, but I've been out of the country.

In response to your question, I'm using chrome 74.0.3729.169 in windows 10.
I don't know if there was any update, but it does seem to be working now.

**Comment by hdls19** [comment]
Hi. I have the same problem. I am using version 4.8.0. The drop-down list falls down the screen, although logically it should drop up. Tried on Opera v71.0.3770.284 and on Chrome v86.0.4240.111

**Comment by olifolkerd** [comment]
This will be a z-index issue with your page. Try making a JS Fiddle that replicates the issue

**Comment by hdls19** [comment]
Reworked the example above - https://jsfiddle.net/rqv1g846/2/

**Comment by Rajan-sust** [comment]
I'm facing the same issue...

**Comment by Rajan-sust** [comment]
It will work

```
var table = new Tabulator("#example-table", {
    autoResize:false, // prevent auto resizing of table
});
```
