### ISSUE TITLE
Add doc.putTotalPages function when printing PDF

### ISSUE THREAD

**Issue by darshanrampatel** [olifolkerd/tabulator#2102]
**Is your feature request related to a problem? Please describe.**
I need a way to add "Page 1 of n" footer when using the PDF download option. This should be possible via AutoTable and jsPDF but it needs the following lines added after doc.autoTable(...) has been called.

**Describe the solution you'd like**
Add the following code to https://github.com/olifolkerd/tabulator/blob/9e32aa87a9169503dfb6069a8eb60ec4e9d602d8/src/js/modules/download.js#L624
```
if (options.totalPagesExp) {
	if (typeof doc.putTotalPages === 'function') {
		doc.putTotalPages(options.totalPagesExp);
	}
}
```

`totalPagesExp` can then be passed as an option to the `download` function:

```
const totalPagesExp = "{total_pages_count_string}";
table.download( "pdf", "data.pdf", {
	orientation: "portrait", //set page orientation to portrait
	title: "PDF Page Numbers Test",
	totalPagesExp: totalPagesExp,
	autoTable: ( doc ) => {

		doc.autoTableSetDefaults( {
			addPageContent: ( data ) => {
				let footerStr = "Page " + doc.internal.getNumberOfPages();
				if ( typeof doc.putTotalPages === 'function' ) {
					footerStr = footerStr + " of " + totalPagesExp;
				}
				doc.setFontSize( 10 );
				doc.text( footerStr, data.settings.margin.left, doc.internal.pageSize.height - 10 );
			}
		} );
		
		//return the autoTable config options object
		return {
			columnStyles: columnStyles,
		};
	},
} );
```

**Describe alternatives you've considered**
Doesn't seem to be any way to workaround this at present.

**Additional context**
https://github.com/simonbengtsson/jsPDF-AutoTable/issues/144#issuecomment-363945044

**Samples**
[Sample PDF](https://github.com/olifolkerd/tabulator/files/3231830/data.-.2019-05-29T105244.204.pdf)
[Sample index.html test file](https://github.com/olifolkerd/tabulator/files/3231807/index.txt)

**Comment by olifolkerd** [comment]
@darshanrampatel 

Im confused, i dont see why you cant just put that functionality directly in the autotable callback without altering the Tabulator source.

Cheers

Oli :)

**Comment by darshanrampatel** [comment]
@olifolkerd 

Hi Oli,

It's because the `doc.putTotalPages(...)` call needs to happen after the `doc.autoTable(...)` call, not within it.

See this [StackOverflow answer](https://stackoverflow.com/a/46814494/5024969).

**Comment by olifolkerd** [comment]
I can see why the function needs to be called after, but your proposed solution is very specific with you essentially passing a very specific string into a very specific property.

Surely a more generic approach that allowed access to function calls on the doc after the auto-table command hand been run would be a more inclusive addition that would allow users to add any specific functionality relating to their usage case.

Im not trying to be picky but i have to consider all users when discussing updates to the Tabulator code base.

Cheers

Oli :)

**Comment by darshanrampatel** [comment]
Hi Oli,

I agree - a more generalised approach would be better.

**Comment by olifolkerd** [comment]
Hey @darshanrampatel 

i have added a new ***documentProcessing*** option to the download options object, you can pass a callback to this that gives you access to the document object to call any functions you like on:
```js
table.download("pdf", "test.pdf", {
	documentProcessing:function(doc){
		doc.text("SOME TEXT", 200, 30);
	}
});
```

It is currently on the 4.3 branch that will be released later today

Cheers

Oli :)

**Comment by darshanrampatel** [comment]
@olifolkerd Thanks for doing this change! Just got around to upgrading to 4.3.0 and it works fine:
```TS
          const totalPagesExp = '{total_pages_count_string}';          
          this.myTable.download( 'pdf', 'fileName.pdf', {
            documentProcessing: ( doc ) => {
              if ( typeof doc.putTotalPages === 'function' ) {
                doc.putTotalPages( totalPagesExp );
              }
            },
            autoTable: ( doc ) => {
              doc.autoTableSetDefaults( {
                didDrawPage: ( data ) => {
                  let footerStr = `Page ${ doc.internal.getNumberOfPages() }`;
                  if ( typeof doc.putTotalPages === 'function' ) {
                    footerStr = `${ footerStr } of ${ totalPagesExp }`;
                  }
                  doc.setFontSize( 10 );
                  doc.text( footerStr, data.settings.margin.left, doc.internal.pageSize.height - 10 );
                }
              } );

              return {                
                theme: 'grid',                
              };
            },
          } );
```
