### ISSUE TITLE
Can't edit text column in Chrome mobile

### ISSUE THREAD

**Issue by galuha** [olifolkerd/tabulator#2103]
Hello. Trying to edit text column in the Chrome mobile results in lost focus / unable to edit.
Noticed that it behaves like this only if table height is not set.

Tabulator version 4.2.7

Please see https://jsfiddle.net/galushkin/ytevz20d/6/

1. Open this fiddle in Google Chrome on your smartphone
2. Try to edit the only cell

**Comment by olifolkerd** [comment]
Hey @galuha 

That is because the keyboard appearing is changing the height of the table, causing it to be redrawn, cancelling the edit.

try setting the ***autoResize*** property to ***false*** in your table constructor.

Cheers

Oli :)

**Comment by galuha** [comment]
Thanks, Oli!
