### ISSUE TITLE
Two different nested tables in a table

### ISSUE THREAD

**Issue by rnconfalonieri** [olifolkerd/tabulator#2104]
Hello! I have a table that shows some part of a JSON and I need to show two different nested tables, each one showing  the other two parts of the JSON. I followed your example and if I show any of the subtables, it shows the correct data, but if I try to show both of them, Tabulator only shows the last.

My question is: is it possible to show two different nested tables for a principal table or it is a feature still not contemplated?

**Comment by takuy** [comment]
To clarify - you want to show two different tables nested underneath one table?

**Comment by rnconfalonieri** [comment]
Yes. That's exactly what I want  to do. Each nested table shows different data.

Thank you for answering this fast.

**Comment by rnconfalonieri** [comment]
Yes. That's exactly what I want to do. Each nested table shows different data.

Thank you for answering this fast.

**Comment by rnconfalonieri** [comment]
Please, I mitakenly closed this issue two comments up, but I reopened it and need the mentioned advice. I will thank all the help I can get.

**Comment by olifolkerd** [comment]
Hey @rnconfalonieri 

There is an example of exactly that in the [Examples Documentation[(http://tabulator.info/examples/4.2#nested-tables)

Cheers

Oli :)
