### ISSUE TITLE
Editing is started after column resize

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#2105]
**Describe the bug**
I have tabulator with sizeable columns and cell editors.
After column resizing the cell editor is started

**Tabulator Info**
- Which version of Tabulator are you using? 4.2

**To Reproduce**
1. start resize column near the cell

**Expected behavior**
after resizing no editing should occur

**Screenshots**

[Kazam_screencast_00011.mp4.zip](https://github.com/olifolkerd/tabulator/files/3233426/Kazam_screencast_00011.mp4.zip)

As you can see here. When cursor after dragging is over the cell which we can edit the editor is tarted. This should not occur.

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.3
 - Browser FF
 - Version 66

**Comment by KES777** [comment]
Probably this is another issue, but editing also starts when I only press mouse button down.

**Comment by olifolkerd** [comment]
Hey @KES777 

Can you create a JS fiddle, i cant seem to replicate that my end.

Cheers

Oli
