### ISSUE TITLE
"required" validator for "select" or "autocomplete"

### ISSUE THREAD

**Issue by pbaggiol** [olifolkerd/tabulator#2106]
The "required" validator does not seem to be working for the "select" or "autocomplete" editor.  When I tab into one of those fields, I get the text "undefined" by default, and I am able to tab out without selecting any of my options.

I've tried creating a custom validator to prevent this, but it only seems to get called once a value is populated.  

I cannot seem to find this as a known issue, but I am interested in workarounds or code-solutions.  Please advise.

Thank you.

**Comment by olifolkerd** [comment]
Hey @pbaggiol 

Thanks for getting in touch,

Sorry to hear you are having issues, could you create a JS Fiddle or Code Pen that replicates the issue?

Cheers

Oli

**Comment by doraemonxxx** [comment]
Hi there @olifolkerd 

I have the same issue, is the question and problem already solved?
