### ISSUE TITLE
cssClass to apply only to body cells and not the header cell

### ISSUE THREAD

**Issue by fingers10** [olifolkerd/tabulator#2110]
HI Tabulator Team,

I used to provide one of the column values as a link to open the record related to that in a bootstrap modal popup. Here is how I format my column for that,

```
{
                        title: 'Name',
                        field: 'Name',
                        formatter: function (cell, formatterParams, onRendered) {
                            return '<a href="#" class="text-underline" aria-haspopup="true">' + cell.getValue() + '</a>';
                        }
                    },
```

Later, I found that Tabulator has a built in link formatter to achieve the same. So I changed my column configuration as follows,

```
{
                        title: 'Name',
                        field: 'Name',
                        formatter: 'link',
                        cssClass: 'text-underline',
                        formatterParams: {
                            url: "#"
                        }
                        //formatter: function (cell, formatterParams, onRendered) {
                        //    return '<a href="#" class="text-underline" aria-haspopup="true">' + cell.getValue() + '</a>';
                        //}
                    },
```

This works fine but the `cssClass` is creating trouble. As per Tabulator docs it applies the given css class to cell and header cell. And that makes the output look like shown below:

![image](https://user-images.githubusercontent.com/43729469/58621632-7d22ce00-82e7-11e9-82b2-bcf5ec6acf41.png)

Is there any way to make `cssClass` to apply only to body cells and not to header cell?

Thanks,
Abdul

**Comment by olifolkerd** [comment]
Hey @fingers10 

Not if you are using the ***cssClass*** option. your two options are to tweak your CSS selector to only apply your style to elements that have a class of ***.tabulator-cell*** and your class, or to add the class in the cell formatter instead.

I hope that helps,

Cheers

Oli :)
