### ISSUE TITLE
Pass through download type to accessorDownload functions

### ISSUE THREAD

**Issue by darshanrampatel** [olifolkerd/tabulator#2111]
**Is your feature request related to a problem? Please describe.**
When using the download module, I need to format certain columns before outputting the file. This can be done via `accessorDownload` functions but it seems that only one function can be defined for each column.

My use case is that, when downloading a PDF, I need a column to be formatted in one way, but when downloading a CSV, it's needs to be formatted another way.

**Describe the solution you'd like**
Pass through the download type (e.g. 'csv', 'pdf', 'json', 'xlsx') as a parameter to the `accessorDownload` function.

**Describe alternatives you've considered**
Alternative is to have multiple `accessorDownloadPDF`, `accessorDownloadCSV`, etc. functions but this seems less flexible. Since `downloadDataFormatter` doesn't seem to receive the download type, it can't be used either.

**Comment by olifolkerd** [comment]
Hey @darshanrampatel 

The easiest way for you to handle this is to set a global variable to the download type before your trigger the download then reference i inside your accessor function, that way you will know what it is you are changing for.

I hope that helps,

Cheers

Oli :)

**Comment by darshanrampatel** [comment]
Hi @olifolkerd,

Thanks - didn't occur to me but that works perfectly.
