### ISSUE TITLE
Change values dynamically from function in EditorParams Autocomplete

### ISSUE THREAD

**Issue by Gnuffie** [olifolkerd/tabulator#2112]
**Is your feature request related to a problem? Please describe.**
We saw promise in Tabulator and it catered to our particular project but we since noticed an issue with autocomplete because we wanted to change the values attribute in autocomplete on change of another cell and verified that values is static and can't be changed.

**Describe the solution you'd like**
We want or rather, need on the change of a particular cell to change the list of values of editor params, dictionary or array, of autocomplete editor without the need for programming a custom editor.

**Describe alternatives you've considered**
We considered values of editor params accepting a function and changing the values considering the change of other cells

Thank you and we expect a response,
Gnuffie

**Comment by aklaver** [comment]
A quick test showed that something like:
col.getDefinition().editorParams.values = ['one', 'two', 'three']
table.redraw()
works to reset autocomplete values. I could see running that off the cellEdited callback of the changed cell.

**Comment by Gnuffie** [comment]
We don't want to redraw the table @aklaver 
I know it updates, we tried doing it with select and it worked like a charm.

**Comment by olifolkerd** [comment]
@Gnuffie 

You can pass a function into the values option and it will be passed in the search term, you can there for display and values you like.

Cheers

Oli :)

**Comment by Gnuffie** [comment]
@olifolkerd 
We tried doing what you said with no further development could you write us a small example so we could further develop it and to any person who has the same issue in the future.
We tried passing the result in array and dictionary as in the [documentation](http://tabulator.info/docs/4.2/edit#edit-builtin) and we even tried doing what you told us.

Cheers,
Gnuffie

**Comment by aklaver** [comment]
@olifolkerd 
I tried the below, but it never reached the function. What am I missing?

```javascript
	{title:"Favourite Color", field:"col", editor: "autocomplete", editorParams:
            {   showListOnEmpty: true,
                values: function(cell){
                    var color_array = ["red", "blue", "green"];
                    var out_array = [];
                    console.log(cell.getValue());
                    color_array.forEach(function(str){
                        if (str.includes(cell.getValue())){
                            out_array.push(str);
                        }
                    })
                    return {values: out_array};
                }
            }
        },
```

**Comment by l1ngoman** [comment]
Hi @olifolkerd ,

I'm having a similar problem with the autocomplete not firing a function to set its values. I unfortunately need this feature, because my associated function removes all previously selected values from the array list so that a user cannot duplicate a value. (Note: it works just fine if I set the object to the values property - just not when it's through a function call - but then I cannot dynamically alter the values.)

For the moment, I'm having to use the "select" editor instead of the "autocomplete", but I would really love to change it back if this ever gets fixed because it's much more user friendly to be able to type out the selection.

Thanks for all you do and your amazing product!

**Comment by aleksvagapitov** [comment]
I have recently stumbled upon the same issue. Although you indeed can't set the values dynamically as everything seems to build even before OnPageLoad is fired.

The solution for my issue was to create own input, which allows me to also make Ajax requests and dynamically display data on input.

```javascript
{
title: "YourFieldTitle", field: "YourFieldName", headerFilter: "input", editor: AutocompleteFunction, formatter: function (cell, formatterParams, onRendered) {
                var composed;
                $.ajax({
                    url: baseUrl + '/apiendpoint?value=' + cell.getValue(), // Need to Look Up by ID
                    type: "get",
                    async: false,
                    success: function (response, textStatus, xhr) {
                        composed = cell.getValue() + " | " + response.Param1+ " | " + response.Param2+ " | " + response.Param3;
                    },
                    error: function (XMLHttpRequest, textStatus, error) {
                    }

                })
                return composed;
            }
}

var AutocompleteFunction= function (cell, onRendered, success, cancel, editorParams) {
    var editor = document.createElement("input");
    editor.value = cell.getValue();
    editor.setAttribute("id", "autocomplete");

    editor.style.padding = "3px";
    editor.style.width = "100%";
    editor.style.boxSizing = "border-box";
    var availableTags = [{}];
    var set = new Set();

    function successFunc() {
        $.ajax({
            url: baseUrl + '/apiDifferentEndpoint?value=' + editor.value,
            type: "get",
            success: function (response, textStatus, xhr) {
                for (var i = 0; i < response.length; i++) {
                    if (!set.has(response[i].ParamPrimary)) {
                        availableTags.push({ 'label': response[i].ParamPrimary + " | " + response[i].Param2+ " | " + response[i].Param3+ " | " + response[i].Param4, 'value': response[i].ParamPrimary});
                        set.add(response[i].ParamPrimary);
                    }
                }
            },
            error: function (XMLHttpRequest, textStatus, error) {
            }

        }).done(function () {
            $("#autocomplete").autocomplete({
                source: availableTags,
                select: function (event, ui) {
                    success(ui.item.value);
                },
            });
        });
    }

    editor.addEventListener("keydown", successFunc);
    editor.addEventListener("blur", function () {
        cancel();
    });

    return editor;
}

The above example shows how to autofill values dynamically and also to format them for viewing after. I understand that this is not exactly what you are looking for, but for me it works as a workaround at the moment.
```

**Comment by aleksvagapitov** [comment]
@aklaver I am not sure if you found a solution to your question, but to answer your question, to my knowledge Tabulator doesn't allow any functions into the 'values' parameter of Autocomplete. The only way I found around that is to create a custom function and that allows you to pretty much do anything you would like (With some tinkering of course). You can check the example above for implementation.

**Comment by amchconsult** [comment]
This works for me.

```
{ title: "Group", field: "grupo", width: "auto", headerFilter: "input", editor: "autocomplete", editorParams: function(cell){
        var options = {0:""};
        vm.field_groups.forEach(function(data){
                options[data._id] = data.title;
        });
        return {values:options, showListOnEmpty:true, 
            freetext:false, 
            allowEmpty:true, 
            searchFunc:function(term, values){ 
                var matches = []
                var text = term.split(' ');
                matches = values.filter(function(item) {
                    return text.every(function(el) {
                        return item.title.toLowerCase().indexOf(el.toLowerCase()) > -1;
                    });
                });
                return matches;
            },
        }
    },
}
```

**Comment by DrDave-M** [comment]
@olifolkerd 

When i try to pass in a function to the values param as you suggested, it is never called...

    editorParams: {
    //[...]
    values: function (cell) {
        debugger;
        console.log("tabulator values call()", cell);
        return acctVals;
    },
    }

**Comment by olifolkerd** [comment]
Hey all,

When the 4.6 branch is released later today you will be able to return any values you like from the ***searchFunc*** so you will be able to handle this scenario that way.

Cheers

Oli :)
