### ISSUE TITLE
How to use updateData

### ISSUE THREAD

**Issue by dv8inpp** [olifolkerd/tabulator#2116]
I am having trouble working out why this isn't working. When I click on a row I want to be able to set the UPDATE field to TRUE so I only need to update the changed rows back to the SQL server. The version of Tabulator is 4.2. I have tried with $ROW_ID being both a string and a number. When I click on  cell I get the row number and typeof being number, I am not getting a  success or failure console message.

    var table = new Tabulator("#example-table1", {  
        cellClick:function(e, cell){
            var $ROW_ID=Number(cell.getRow().getData().CONFIG_ID);
            console.log($ROW_ID, typeof($ROW_ID));
            table.updateData([{id:$ROW_ID,UPDATE:"TRUE"}])
            .then(function(){
                var $UPDATE=cell.getRow().getData().UPDATED;
                console.log("success");
            })
            .catch(function(error){
                //handle error updating data
                console.log("failed");
            });
        },......

**Comment by tentus** [comment]
> Please ask questions on www.stackoverflow.com 

(Also it'll help get answers more reliably if you post a jsfiddle or something that illustrates the problem)

**Comment by olifolkerd** [comment]
Hey @dv8inpp 

There is no need to use the table.updateData function. you can use the ***update*** function on the row component.
```js
cell.getRow().update({update:true});
```js

i hope that helps.

Cheers

Oli :)
```
