### ISSUE TITLE
Sending Another Var Via Ajax

### ISSUE THREAD

**Issue by BenTongue** [olifolkerd/tabulator#2118]
Hi all,

On click i'm sending an ajax request with posted data:

How can I also send the Variable Colour that I have below? I can't work out how to add this to cell.getRow().getData().

> 

           {title:"EDN", field:"EDN", sorter:"string", width:100, headerFilter:"input", tooltip:"Orange = not cleared and Green = Cleared", cellClick:function(e, cell, formatterParams){ var colour = $( "#myselect option:selected" ).val();
            if (colour == ""){
                // do nothing
            } else {
            cell.getElement().style.backgroundColor = colour;
            $.ajax({
           url: "http://cttools.ctfreight.com/CTTools/?page_id=168",
           data: cell.getRow().getData(),
           type: "post",
           success: function(response, textStatus, xhr){
            alert("Colour Updated");
           },
           error: function(XMLHttpRequest, textStatus, error){
             alert("Colour Change Failed");
           }
         })  

            }
        },

Your help would be much appreciated!

**Comment by tentus** [comment]
This should be asked on stackoverflow, but here you go:
https://jsfiddle.net/f35p7gyx/
What you're looking for is the spread syntax. Using `...` on the data will let you expand it into a new object with whatever additions you need.

**Comment by BenTongue** [comment]
My apologies, would you like me to post there and you respond with the same solution?

BTW this worked perfectly!

I do have a side question, I wan to return the colour of the cell and value of the cell using the Ajax request (get table data). Currently i return the value in that column but the colour is returned in a hidden column called EDN_Colour and pulled using a formatter param within EDN: 

 `` formatter: function(cell, formatterParams) {
  var EDNColour = cell.getData().EDN_Colour;
  var cellValueEDN = cell.getData().EDN;
            cell.getElement().style.backgroundColor = EDNColour;
            return cellValueEDN;
          }``

Is there a better solution?

**Comment by tentus** [comment]
Nah you're good, I'm just trying to encourage folks to use stackoverflow while Oli is swamped, we've got too many cornercases and just the one Oli.

WRT your side question: assuming the `field` for that column is EDN you could probably shorten it like so:
```
formatter: function(cell, formatterParams) {
    cell.getElement().style.backgroundColor = cell.getData().EDN_Colour;
    return cell.getValue();
}
```
but otherwise I'm not aware of a better approach.

**Comment by olifolkerd** [comment]
Hey @tentus 

Thanks for the helping hand, i should be out of my busy period at work soon.

Cheers

Oli :)
