### ISSUE TITLE
table into a tabs

### ISSUE THREAD

**Issue by lalwende00** [olifolkerd/tabulator#212]
Hello, 
i will try to explain my problem clearly , 
i use jquery tabs and when i click on a tab ( comment tab in my case)
i use tabulator to show all comments 

![Image of com table ](http://img4.hostingpics.net/pics/273358com.png)

when i select a row a delete button is show 
when i click data into database are deleted but to delete the row of the tabulator i need the index to pass  at the method when the post request delete on database ? 

`$("#del-row").click(function(){
    $("#example-table").tabulator("deleteRow", 1);
});`

my question is in my case how to retrieve this index row ?

`              $("#comment-admin").tabulator({
 
        height:"600px",
        pagination:"local",
        paginationSize:25,
        selectable:1,
        fitColumns:true,    
                    
            columns:[
            {title: "N°",formatter:autoNumFormatter, width:40}, //incrementing row number   
            {title:"Asset Id", field:"assetId", width:100,sortable:true},
            {title:"Utilisateur", field:"assetUser", width:500, sorter:"string"},
            {title:"Commentaire", field:"comment", width:500,editable:true}
            ],
                    
                cellEdited:function(id, field, value, oldValue, data, cell, row){
                                        
                       var tableData = $("#comment-admin").tabulator("getData", true);                     
                       id = tableData[0]['assetId'];
                     
                $.ajax({
                type: 'POST',
                url: 'editable.php',
        
                data: {
                'field':field,
                'comment':value,
                'commentData':data,
                'assetId':id,
                
                }
                    
                 });
       
                },
                
                rowSelectionChanged:function(data, rows){
                    
                $('#delete').html('<button type="button" id="del-row" class="btn btn-primary" value="remove" name ="action">Supprimer</button>');
                  
                $( "#del-row" ).click(function() {
                    
                $.ajax({
                type: 'POST',
                url: 'editable.php',
                
                data:{
                    'dataDelete':data 
                    
                  },
                success: function(response){
                    
                  }
                  
               });
               
        });
                },
                
                
});
$("#comment-admin").tabulator("setData",cms);    

thank you 

             `

**Comment by olifolkerd** [comment]
Hey,

You can get the currently selected rows using the ***getSelectedData*** function:

```js
$( "#del-row" ).click(function() {
     var selectedRows = $("#comment-admin").tabulator("getSelectedData");

    selectedRows.forEach(function(rowData){
        $("#comment-admin").tabulator("deleteRow", rowData.id);
    });
});
```

The example above assumes that your table data uses the index field of ***id*** but you can change this to whatever you want.

Let me know if that helps.

Cheers

Oli

**Comment by lalwende00** [comment]
Hello thanks a lot 
all is ok 
Have a nice day !
