### ISSUE TITLE
Complex Select Editor not working as expected

### ISSUE THREAD

**Issue by moetun88** [olifolkerd/tabulator#2121]
**Describe the bug**
I'm having a few different issues with the select editor, using the complex examples option nearly verbatim
1. The disabled option is still selectable. It shows up as an option named Disabled (which is what the label is)
2. When selecting an option from the drop down list the value is displayed instead of the label

**Tabulator Info**
4.2.7 (Tried it on 4.1.2 as well)

**Working Example**
https://jsfiddle.net/7cyrouL3/

**To Reproduce**
1. Click on the drop down and select Jenny Jillerson, it switches to show the value
2. Click on the drop down and select disabled, it allows the option to be selected.

**Expected behavior**
When selecting Jenny Jillerson the label of Jenny Jillerson should be shown not the value jenny
Disabled select drop down elements should not be selectable

**Desktop
 - OS: Windows 10
 - Browser Chrome 74 / Firefox 67

**Comment by tentus** [comment]
1. Could you link me to the complex examples option you're referencing? I'm looking at http://tabulator.info/docs/4.2/edit#edit-builtin and https://github.com/olifolkerd/tabulator/blob/master/src/js/modules/edit.js and I'm not seeing any references to a disabled attribute.

2. What you're probably going to want for display value is to use the List Lookup formatter (http://tabulator.info/docs/4.2/format#format-builtin) using a flattened version of the editor values. The presentation of the editor select doesn't affect the default display value of the field.

**Comment by moetun88** [comment]
1.  http://tabulator.info/docs/4.0/edit - the second example for select
//disabled option
    {
        label:"Disabled",
        value:"disabled",
        disabled:true,
    }

2. Let me try that out and get back to you.

**Comment by tentus** [comment]
Ah, you're looking at a doc from two versions ago. Looks like that particular functionality was replaced in https://github.com/olifolkerd/tabulator/commit/be9896e5c0f7ccf5490607106e2d66d15d4de5e3#diff-c097861941d34fd9364eeed1b3c1058c
