### ISSUE TITLE
How to add data to a field

### ISSUE THREAD

**Issue by next2sin** [olifolkerd/tabulator#2123]
I am trying to add specific data to a column using the below syntax. Basically I am attempting to use the first row as column headers.  Any help would be appreciated.

let recapData = [
        'Plan Period'
      , 'Plan Cumulative'
      , 'Actual Period'
      , 'Actual Cumulative'
      , 'Forecast Period'
      , 'Forecast Cumulative'
     ]
  // Recap Table
  const recapTable = new Tabulator('#divPdfRecapTable', {
    layout: 'fitColumns',
    height: '90vh',
    columnVertAlign: 'bottom', // align header contents to bottom of cell
    columns: [
        {
            title: 'Schedule'
          , data: recapData
        }
    ],
  });

**Comment by tentus** [comment]
https://jsfiddle.net/21uwofL8/1/

**Comment by next2sin** [comment]
Thank you so much for your quick response. 

I was actually looking to make the recap table as a row header, I figured it out by doing this

let recapData = [
        {schedule: 'Plan Period'}
      , {schedule: 'Plan Cum.'}
      , {schedule: 'Actual Period'}
      , {schedule: 'Actual Cum.'}
      , {schedule: 'Forecast Period'}
      , {schedule: 'Forecast Cum.'}
     ]
  // Recap Table
  const recapTable = new Tabulator('#divPdfRecapTable', {
    layout: 'fitColumns',
    height: 400,
    columns: [
        {
            title: ''
          , field: 'schedule'
          , formatter: 'bold'
        }
    ],
    data: []
  });
