### ISSUE TITLE
Reload table data with setData after the cell click has been triggered

### ISSUE THREAD

**Issue by Lakhiii** [olifolkerd/tabulator#2124]
Initialized the table with the ajax url and the cell click callback inside the table tabulator object. Since i have an action to approve or disapprove an entity, i used a cell click to pass the ajax request to update the data in the server side from "not yet approved" to approved and my objective is to make sure the data is synced with the server side. How do i reload the data after the cell click call back? i tried putting the table.setData method but didnt work since the cell click code is inside the table tabulator initialization. 

another thing, is there any way that the header filter param values defined coming from an ajax response? i don't want to have static data set in the code . Thanks :)

**Comment by fr0z3nfyr** [comment]
Well, from the context it appears that you are using `ajax` call to update the status on server. In that case i also, believe your server must be returning the success of the task as response (if not, it should return something to tell the requester about the status of task). based on that response, you can perform an update of the row data using `row.update({"approval":"Approved"}); ` if you already have access to row component and if not, you can do something like `cell.getRow().update({"approval":"Approved"}); ` the `update` method also returns a promise which you can leverage to perform any further callbacks. 

[Read the documentation](http://tabulator.info/docs/4.2/update#row) for more information.

**Comment by Lakhiii** [comment]
Thanks for this. Really appreciate it. Keeps me going.
