### ISSUE TITLE
How to disable edit at table level

### ISSUE THREAD

**Issue by muthukvs** [olifolkerd/tabulator#2126]
How can we make a tabulator table as non editable so that non of the cells can be edited?

**Comment by tentus** [comment]
I think your question is missing some context. The default behavior is that tables are immutable, editing has to be enabled.

**Comment by muthukvs** [comment]
ok got it..which parameter in tabulator defines that editable.

I need parameter to get enabled for edit

**Comment by aklaver** [comment]
Editing is set per column not at table level:

http://tabulator.info/docs/4.2/edit

**Comment by olifolkerd** [comment]
Hey @muthukvs 

By default cells are not editable, you have to specifically enable them, so just dont set the ***editor*** property in any of your column definitions and you should be good.

Cheers

Oli :)
