### ISSUE TITLE
Function to collapse/expand all nodes in the entire tree

### ISSUE THREAD

**Issue by fr0z3nfyr** [olifolkerd/tabulator#2127]
**Is your feature request related to a problem? Please describe.**
I believe there should be an implementation of convenience function(s) to expand or collapse entire tree in nested data tree layout. For instance I start the tree with `[true, false]` state which which will initially expand only first/root level such that only root nodes and their direct children exist in DOM. Now, using a button I should be able to call a helper function that can expand all child rows, irrespective of whether they are direct or indirect children such that the entire table is available in DOM (exact opposite should happen for collapse hiding all rows except the root nodes). 
I could find helper for expanding rows using `row.treeExpand()` and `row.treeCollapse()` (please correct the code sample in [documentation](http://tabulator.info/docs/4.2/tree#component) - it says `treeExpand()` for collapse also) but there is nowhere mentioned about a way to achieve the abovesaid. At present, I just get the table data (`table.getData()`), then destroy the tabulator and re-init tabulator with initial expand state to `true` which I believe is an overkill. I remember reading a comment from you on one of the other issues that changing tabulator config on the fly is not possible so destroying the table and re-initializing is the only way possible (I think I'll create a request for that ability some other day but it's not a roadblock for me at the moment).

**Describe the solution you'd like**
Please see the above description for details. I'd love to get 2 helper functions that can expand collapse entire nested tree; something like `table.treeExpand()` and `table.treeCollapse()` which follow the same naming convention from row component.

**Describe alternatives you've considered**
Also mentioned in above description. I achieve the effect by destroying the table, then re-initializing the table with `dataTreeStartExpanded:true` which seems like too much for this. another alternative I thought about was writing a recursive function that will look at each expand row's child and expand them further if they have any children but that seemed like a very slow and resoource intensive approach compared to simply reinitializing the table.

**Comment by fr0z3nfyr** [comment]
Hello there? 
Any idea or suggestion on above will be highly appreciated

**Comment by aklaver** [comment]
Something like the below. Note the table name and index key I was using are hard coded in below. Also this  will take a while to run over an entire table of data.
`
function traverse(o, action) {
    for (var i in o) {
        if (o[i] !== null && typeof(o[i])=="object") {
            if (o[i]._children){
              let r = reverseTable.getRow(o[i].link_key)
              if (action == "expand"){
                r.treeExpand();
              }else{
                r.treeCollapse();
              }
            }
            traverse(o[i],action);
        }
    }
}
dt = reverseTable.getData()
traverse(dt, "expand");
traverse(dt, "collapse");
`

**Comment by fr0z3nfyr** [comment]
@aklaver thanks for the suggestion. What exactly is `reverseTable`? I tried it with the normal tabulator instance that was used to create the table in first place. I do it as `let table = new Tabulator('#my-table', { ... });`
Then it gives error `TypeError: r.treeExpand is not a function` in console. Initial investigation shows `Find Error - No matching row found: undefined` with `console.log(r)`.

> Also this will take a while to run over an entire table of data.
In that case, don't you think it'd be much faster and error-free to just do something like (this is what I have right now but destroying and re-initializing each time just doesn't seem right to me somehow):

```
let tData = table.getData();
setTimeout(function() {    // just for safety
    table.destroy();
}, 0);
table = new Tabulator('#my-table', {
    ...
    dataTreeStartExpanded:true    // false for collapse all
    ...
});

```

**Comment by aklaver** [comment]
reverseTable is the hard coded table name I referred to. It is a reference to an already existing table.
"Find Error - No matching row found: undefined"  means it was using undefined to find a row and failing. Best guess is that there was no actual data returned by getData(). I am thinking of rewriting this to use rows directly and row.getTreeChildren() to figure out which has rows.

**Comment by aklaver** [comment]
Alright figured out why it was not working. My initial case was just going one level deep. My function fails when you go deeper as .getRow() will not find child rows.

**Comment by aklaver** [comment]
Try this fiddle:

https://jsfiddle.net/aklaver/87hgabzd/7/

**Comment by fr0z3nfyr** [comment]
Nice work, I too tested with similar recursive function but decided not to use it due to performance issues. Your function seems to work good but as you already said (and as I expected), it was noticeably slow for an actual table with about 250 rows that goes 5 levels deep for some rows (was my actual data, not test data). Since, the expand/collapse (all) doesn't do much except show hide child rows to root/inner-most level, I'm leaving my initial code that destroys and re-initializes tabulator, which is very fast (unless it causes some unintended side effects which I'm not aware of). 

However, I think your function can work as a starting point for building a filtering function that can find and display all matching rows (with the parent rows on the table too).

**Comment by aklaver** [comment]
Not sure what you mean by destroy table and re-initialize, but what I found works is:

https://jsfiddle.net/aklaver/74190bvf/8/

**Comment by fr0z3nfyr** [comment]
Excellent. That's exactly what I was looking for.
`datatreeTable.options.dataTreeStartExpanded = true;    // or false for collapse all`

I didn't know that the `options` can be manipulated that way on the fly. That (ability to directly access `options`) opens a lot of possibilities for my implementation. 

Can't thank you enough. I'll close this issue now.

Cheers!

**Comment by aklaver** [comment]
Running on Tabulator 6.3.1 I get:
```
   Uncaught TypeError: this.listeners.forEach is not a function
    buildListenerMap InteractionMonitor.js:69
    initialize InteractionMonitor.js:62
    _initializeTable Tabulator.js:263
    _create Tabulator.js:165
    expandCollapse (index):65
    onclick (index):1
```

This traces back to from, tabulator.js:

```
_initializeTable(){
			var element = this.element,
			options = this.options;
			
			this.interactionMonitor.initialize();

...
```
If I comment out `this.interactionMonitor.initialize();` then the code works.

I will create a new issue that refers back to this one.
