### ISSUE TITLE
getColumnDefinitions doesn't return updated width

### ISSUE THREAD

**Issue by Elstermann** [olifolkerd/tabulator#2128]
According to the DOCS calling `getColumnDefinitions` should return updated column definitions that reflect updates made by an user - including **resizing**. But actually this isn't the case for the columns width by now.

> Get Column Definitions
> To get the current column definition array (including any changes made through user actions, such **resizing** or re-ordering columns), call the getColumnDefinitions function. this will return the current columns definition array.

http://tabulator.info/docs/4.2/columns#get-definition

---

I made a "quick-&-dirty-patch" for my case like that:
```
const patchColumnWidthUpdate = colComponent => {
  console.log( colComponent._column.getDefinition() ); // definition doesn't reflect new column width yet
  // get definition of resized column
  const definition = colComponent._column.getDefinition();
  // get width of resized column by column - not by definition
  // only width on Tabulator creation lives in definition but doesn't refresh on columnResized
  const width = colComponent._column.width;
  console.log( definition.width, width, definition.width === width );
  // get defninitions of all columns
  const definitions = colComponent._column.table.getColumnDefinitions();
  // find index of resized column in defninitions
  const i =  definitions.findIndex( needle => needle === definition );
  // refresh width
  definitions[ i ].width = width;
  // refresh definitions
  colComponent._column.table.setColumns( definitions );
  console.log( colComponent._column.getDefinition() ); // definition does reflect new column width now
}
new Tabulator( '[selector]', {
  columnResized: patchColumnWidthUpdate
  /* options */
} );
```

PS Tabulator Is Awesome

Cheers

Axel <3 | official Tabulator Fan Boy

**Comment by olifolkerd** [comment]
Hey @Elstermann 

It is not supposed to return the updated value of the width, it is supposed to return the original definition.

What you are looking for is the ***getColumnLayout*** function, that returns the current style of the rows.

Cheers

Oli :)

**Comment by Elstermann** [comment]
Hi @olifolkerd,

thank you for the reply!

Does then make the

> [...] (including any changes made through user actions, such resizing or re-ordering columns) [...]

part from the [documentation](http://tabulator.info/docs/4.2/columns#get-definition) make sense? Its misleading, isn't ist? At least for me it is!

Better would be something like (~~strikethrough~~ means remove and **bold** means add):

> Get Column Definitions
> To get the ~~current~~ **original** column definition array ~~(including any changes made through user actions, such as resizing or re-ordering columns)~~, call the getColumnDefinitions function. this will return the current columns definition array. **If you want to get the current updated column definition array (including any changes made through user actions, such as resizing or re-ordering columns), call the [getColumnLayout](http://tabulator.info/docs/4.2/persist#columns) function instead.**

cheers

Axel :)

**Comment by olifolkerd** [comment]
Hey @Elstermann 

Good point, will update the documentation.

Cheers

Oli :)
