### ISSUE TITLE
Tabulator Keybindings for add row

### ISSUE THREAD

**Issue by muthukvs** [olifolkerd/tabulator#2129]
Can we have keybinding like custom one

ctrl + a to add row in tabulator

**Comment by fr0z3nfyr** [comment]
Why not if you know how to do write a function that can detect `keypress` and then call `table.addRow({});`. If you are not equipped enough to write your own small custom library, you can use an existing library like [keymaster](https://github.com/madrobby/keymaster). 

**P.S:** I'm just a huge fan and user of `Tabulator` as well as `Keymaster` and in no way trying to promote any work commercially. BTW, the other library is also `MIT` licensed just like `Tabulator`.

**Comment by olifolkerd** [comment]
@muthukvs 

You can already do this, you just need to extend the keybinding module to add the additional function.

Checkout the [Keybinding Module Documentation](http://tabulator.info/docs/4.2/modules#module-keybindings) for instructions on how to do this.

Cheers

Oli :)

**Comment by muthukvs** [comment]
Thanks for response..ll explore and let you know

**Comment by fr0z3nfyr** [comment]
Hey @olifolkerd Sorry for being hasty in posting a complicated solution using a 3rd party library when the same thing can be done natively. I should have read the documentation completely before attempting to answer.

By the way, I'm just loving the library and learning something new and fancy about it every hour. Thanks and Cheers!!
