### ISSUE TITLE
Tabulator how to find edited rows

### ISSUE THREAD

**Issue by muthukvs** [olifolkerd/tabulator#2131]
I have a tabulator table which was filled by AJAX call and then allow user to edit it if required. After submition of particular page I need to know how many rows user modified .is there any existing functionality in tabulator does this ?

**Comment by aklaver** [comment]
This ?:
http://tabulator.info/docs/4.2/history

http://tabulator.info/docs/4.2/callbacks#cell
cellEdited 

http://tabulator.info/docs/4.2/callbacks#data
dataEdited

**Comment by muthukvs** [comment]
thanks...if i give history:true in my tabultor..can i get overall history in some object at any point of time?

**Comment by aklaver** [comment]
If I am following the code in:

https://github.com/olifolkerd/tabulator/blob/master/src/js/modules/history.js

correctly then the history is only for a given table session as I do not see any persistent storage.  Though I guess you could do that yourself.

**Comment by olifolkerd** [comment]
Hey @muthukvs 

The easiest approach would be to use the ***cellEdited*** callback, which is triggered on every edit. in this function you could retrieve the row component for the edited rows and push it into an array outside of tabulator.

Then when you want check edited rows, simply look for the unique row components in that array.

Cheers

Oli :)
