### ISSUE TITLE
How to make column non editable dynamically?

### ISSUE THREAD

**Issue by muthukvs** [olifolkerd/tabulator#2132]
How to make column non editable dynamically in tabulator?

**Comment by tentus** [comment]
http://tabulator.info/docs/4.2/edit#optional

**Comment by olifolkerd** [comment]
Hey @muthukvs 

Define your tables with the editors as it would be needed, then set a function on the ***editable*** property of each column that returns a boolean stored in a global variable.

You can then toggle the value of the global Boolean with your controls, then when someone clicks in a cell it will check the state of the global Boolean to determine whether it is editable or not.

No need to update any of the definitions.

I hope that makes sense,

Cheers

Oli :)
