### ISSUE TITLE
After celledited callback the focus is moving out

### ISSUE THREAD

**Issue by muthukvs** [olifolkerd/tabulator#2133]
After AJAX call the focus is moving out and focus is set on first cell in the row.

How to change focus to next successive cell after celledited callback

**Comment by aklaver** [comment]
Tabulator version?
The code?

**Comment by muthukvs** [comment]
Tabulator version 4.2
 table = new Tabulator("#example-table", {
            data:self.get('tableData'),
            selectable:true,
            height:"311px",
            layout:"fitColumns",
            addRowPos:"bottom",
            pagination:"local",
            paginationSize:6,
            paginationSizeSelector:[3, 6, 8, 10],
            columns:self.get('tableColumnData'),
            validationFailed:function(cell, value, validators){
                //cell - cell component for the edited cell
                //value - the value that failed validation
                //validatiors - an array of validator objects that failed
        
                //take action on validation fail
            },
           
            cellEdited:function(cell){   
                var row = cell.getColumn()._column.definition.field;
                var value = cell.getValue();
                var testData =  table.getData();
                testData.forEach(function(del){
                    Ember.set(del, "DELETE", "No");
                });
                self.set('testData',testData);
                self.cellBlur(row,value,testData);
            },
        });

**Comment by aklaver** [comment]
Well there is more stuff happening behind the scenes. For instance not sure where cellBlur is coming from and what it is doing. That being said you might to take a look at:

http://tabulator.info/docs/4.2/navigation#cell
"Use the navigateNext function to shift focus to the next editable cell on the right, if none available move to left most editable cell on the row below."
