### ISSUE TITLE
Unable to Delete a Tabulator Column

### ISSUE THREAD

**Issue by Jayhulageri** [olifolkerd/tabulator#2135]
Hi,

On my page load I am loading a tabulator with read only configuration and have provide a edit button where user can edit the tabulator by clicking on it. On clicking of the edit button, I am recreating a new instance of tabulator with editable configurations  like add/remove columns, rows. 
My issue is once I load the tabulator in edit mode and delete a column, the column gets deleted. Now I wont save the modified data but reload the table again in edit mode with the earlier data as I changed my mind to not delete the column. Now when I try to delete the same column again using column.delete() in headerContext function I get the below error :

Uncaught TypeError: Cannot read property 'removeChild' of null
    at t.n.delete (tabulator.min.js:2)
    at o.delete (tabulator.min.js:2)
    at n.fn.init.callback (rulesJquery.js:560)
    at HTMLLIElement.itemClick (jquery.contextMenu.js:900)
    at HTMLDocument.dispatch (jquery-2.2.4.min.js:3)
    at HTMLDocument.r.handle (jquery-2.2.4.min.js:3)

Is there any way to destroy the table and reload it again ?  I tried $("#myTable").tabulator("destroy"); but it gives no such function error.

Thanks
Jay H

**Comment by tentus** [comment]
This should be asked on stackoverflow, but for the sake of expedience, if you post a jsfiddle I'll take a look and see if I can help you.

**Comment by olifolkerd** [comment]
Hey @Jayhulageri 

There is no need to rebuild your table each time, define your tables with the editors as it would be needed, then set a function on the ***editable*** property of each column that returns a boolean stored in a global variable.

You can then toggle the value of the global Boolean with your controls, then when someone clicks in a cell it will check the state of the global Boolean to determine whether it is editable or not.

No need to update any of the definitions.

I hope that makes sense,

Cheers

Oli :)
