### ISSUE TITLE
Header row scroll position not updating

### ISSUE THREAD

**Issue by haferje** [olifolkerd/tabulator#2137]
**Describe the bug**
The header row does not properly update its horizontal scroll position when the body scrolls.

**Tabulator Info**
- Which version of Tabulator are you using?
4.2.7

**Working Example**
https://jsfiddle.net/haferje/q7o8b0mv/

**To Reproduce**
1. Run the jsfiddle

**Expected behavior**
Header row should scroll along with the data rows.

**Additional context**
When the user has horizontally scrolled the grid, and we remove and re-add a row, the body scrolls all the way to the left, but the header horizontal scroll is not updated to match.

**Comment by olifolkerd** [comment]
Hey @haferje 

Im afraid i cant replicate your issue, that jsfiddle works correctly when i scroll.

Which browser are you using?

Cheers

Oli :)

**Comment by haferje** [comment]
Google Chrome
Version 75.0.3770.100 (Official Build) (64-bit)

I just checked the jsfiddle, and the first loading of that page didn't replicate the issue, but I clicked the Run button to re-run it, and it showed the issue.

Just to be sure, here is a screenshot:
![2138](https://user-images.githubusercontent.com/6677338/61462647-f54d5d80-a940-11e9-8fcc-b82b8d8b8def.png)

I have a PR to fix the issue. Let me know if that code fix doesn't match the intended logic.

Thanks.

**Comment by olifolkerd** [comment]
Hey @haferje 

i have just looked at the code in that example.

of course that is going to cause you issues, you are manually trying to alter the scroll position of an element in the table, which is completely against spec. at no point should anyone be trying to directly alter any internal parts of Tabulator, naturally it will cause issues as the table is unable to detect the change.

the reason it happens inconsistently is because you are not waiting for the table to finish loading before making the manual fudge so sometimes it is being called before the table is renedered and other times it is not.

Oli

**Comment by haferje** [comment]
I understand that altering the internal state of Tabulator elements outside of the public methods can cause an imbalance, and assume you were referring to this bit of code.
```
// user scrolls grid
table.rowManager.element.scrollLeft = 100;
```
It was added to the fiddle, merely to simplify the process of presenting the issue.  I have since updated the [JSFiddle example](https://jsfiddle.net/haferje/q7o8b0mv/11/) to use pure Tabulator methods, and a button to simulate an actual user. Sorry, I will do better when presenting issues in the future.

The issue still stands.  The related PR I submitted is based on an inconsistency I noticed while debugging this issue.  Another area in Tabulator's source performs the same surrounding logic, and adding the missing line solves this.  Even if my JSFiddle example is incorrect, couldn't my PR logic still apply?

**Comment by olifolkerd** [comment]
Hey @haferje 

Thankyou for re-evaluating your example, that looks much better, i will take another look at it this evening. Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @haferje 

Looking at your example you appear to be trying to set the table height on a table that is in classic render mode, the set height function should only be used with the virtual DOM enabled. In classic render mode the table should take up exactly the amount of space that the rows require.

I will update the documentation and add a console wanring if people try and use this function in classic render mode.

Cheers

Oli :)
