### ISSUE TITLE
Group component does not allow to detect group fields

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#2139]
**Is your feature request related to a problem? Please describe.**
for grouping: `groupBy : [ 'agreement_id', 'period_id' ],`

```
  groupClick: function(e, group){
     group._group.field;  // <<< Implement accessor
  },
```

This will allow me to detect for which field the group is clicked

**Describe the solution you'd like**
Implement the accesor for `group._group.field`

**Describe alternatives you've considered**
None

**Comment by olifolkerd** [comment]
Hey @KES777 

Just to be clear you are not looking for the value that the row was grouped by, which is provided by the ***getKey*** function on the group component,

you are looking specifically for the field name?

Oli :)

**Comment by KES777** [comment]
```
  groupBy : [ 'agreement_id', 'period_id' ],
  groupClick: function(e, group){
    if( group._group.field == 'agreement_id' ) {
      agreement_id =  group.getKey();
      period_id = null;
    }
    if( group._group.field == 'period_id' ) {
      period_id =  group.getKey();
    }

    e.stopPropagation();
    group.toggle();
  },

```

when group is clicked I store the group id

**Comment by KES777** [comment]
those saved values I use as defaults for agreement_id, period_id field when append new row

```
{
    suma             : 0,
    service_level_id : 1,
    docdate          : moment().format( 'YYYY-MM-DD' ),
    agreement_id     : agreement_id,
    period_id        : period_id,
  }
```

**Comment by olifolkerd** [comment]
I will look at adding a getField function to the group component, but there will be some caveats on its use as a user can also pass in a function to the selector not just a field name.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @KES777 

You will be happy to hear i have just pushed this feature to the 4.4 branch which should be released in the next couple of weeks.

Cheers

Oli :)
