### ISSUE TITLE
How to fit container to the content awithout using scroll?

### ISSUE THREAD

**Issue by pifealmeida** [olifolkerd/tabulator#214]
When I define max-height, min-height and/or height as 100%, the container fits to the window height instead of to the content's height (here I mean all the rows). Is there a way for me to make it render to the number of rows?

**Comment by olifolkerd** [comment]
Hey,

Thanks for getting in touch,

If you don't define the height of the table it will automatically scale to fit the data it contains.

To make sure this happens don't set a ***min-height***, ***max-height*** or ***height*** for the table in CSS and make sure you don't set the ***height*** property in the Tabulator constructor object.

Let me know if that helps.

Cheers

Oli

**Comment by pifealmeida** [comment]
It worked! Thank you :)

**Comment by NidhiChandak** [comment]
I have not set any height property. Still my table doesn't change its size dynamically. What could be the possible reason?

**Comment by olifolkerd** [comment]
Hey @pifealmeida 

Could you post a copy of your table constructor, and describe what you are trying to acheive.

Cheers

Oli

**Comment by NidhiChandak** [comment]
I think this is a problem with chrome browser only. It works fine in other browsers. Can you please check and confirm? Thank you.

**Comment by olifolkerd** [comment]
Hey @NidhiChandak 

With out a copy of your constructor and an explanation of what your are trying to do i dont know what to look for.

Also are you running version 3.4.3?  there were some rendering issues in earlier versions.

Cheers

Oli

**Comment by NidhiChandak** [comment]
yes i am using the latest version. If i don't set the height attribute, I don't get a scroll-able section at all. 
![1](https://user-images.githubusercontent.com/36695295/36577083-f0b9047a-187a-11e8-8036-84404cc80aaa.png)

**Comment by olifolkerd** [comment]
Hey @NidhiChandak,

This is expected behaviour

If you do not set a height on your table it will render in standard mode, which will show all rows at once.In order to use the virtual DOM an have a scrolling table you must set the height of table.

A detailed explanation of how the table renderes can be found in the [Quickstart Guide](http://tabulator.info/quickstart/3.4)

Cheers

Oli :)

**Comment by NidhiChandak** [comment]
I thought there was a max-height attribute set by default.

**Comment by olifolkerd** [comment]
Hey @NidhiChandak 

Nope, there is no max-height attribute, the [Quickstart Guide](http://tabulator.info/quickstart/3.4) guide explains the two rendering modes.

Cheers

Oli
