### ISSUE TITLE
Pagination remote: show next/prev buttons according to total number of records parameter returned in response

### ISSUE THREAD

**Issue by adjblink** [olifolkerd/tabulator#2140]
I am using angular to load the data from backend. When I create a request I just want to fetch data of one page, that is next or previous page. So, basically for every page, I want to make a call to backend to fetch the data by clicking next/prev buttons. 

Currently, using tabulator pagination, is there a way to show the next/prev buttons or enable them according to the total number of records found parameter sent in the response? 

so basically I am looking for something like this:
this.exampleTable = new Tabulator("#ex-table-div",{
      height : 264,
      data: this.result,
      placeholder:"No Data Available",
      ............
      pagination:"remote",
      paginationSize:10,
      paginationSizeSelector:[10, 15, 20, 25],
      **row_count: 200, // Total number or records found at the backend**
      ..............
});

// on click of next/prev.
paging(pagingEvent){
    this.fromRow = pagingEvent.fromRow;
    this.currentPage = pagingEvent.currentPage;
    this.toRow = pagingEvent.toRow;
    this.pageSize = pagingEvent.pageSize;

   this.loadRecords();
}

Thanks

**Comment by tentus** [comment]
What you're probably looking for is the `last_page` value in the result data. So, imagining you've got something along the lines of 69 total rows, and a page size of 25, then the last_page value would be 3.

**Comment by adjblink** [comment]
Is there a way to set the last_page externally, that is, via a call back?

**Comment by tentus** [comment]
You could use the `ajaxResponse` callback for that setting the last_page value (http://tabulator.info/docs/4.2/callbacks#ajax). 

To the second part of your question, I recommend reading through http://tabulator.info/docs/4.2/data#ajax

**Comment by adjblink** [comment]
I already have the angular framework to fetch the data from the server, so, I don't require the ajax call. Seems like the Tabulator architecture is tightly coupled with the ajax call. Please provide a way to load the table data and also use the pagination with out the ajax call. If I already have the data, via other means, then I don't have to make an ajax call in order to use the pagination functionalities.

**Comment by tentus** [comment]
If you're working locally I suggest you scroll up to http://tabulator.info/docs/4.2/data#array to learn about `table.setData()`. IIRC, that calls sets the max for you, no need to set it directly- ah, and as I type this you've edited your question. Well, here's an example to reference:

https://jsfiddle.net/od0pkgue/

**Comment by adjblink** [comment]
Yes I have tried the local scenario and it works fine. What I am trying to do here is that, make a call to the backend using angular framework, when I first time load the table or click on the next button. So, what I was suggesting is that, if can avoid setting the ajax call somehow by setting the pagination to "local", but my problem here is that the next and previous buttons are be disabled.

**Comment by adjblink** [comment]
Ok so I tried using the ajaxResponse as follows:

 this.esTable = new Tabulator("#es-table-div",{
      height : 264,
      .................
      paginationSize:10,
      paginationSizeSelector:[10, 15, 20, 25],
      **ajaxResponse:(url, params, response) => {
          return this.response
      },** 
  }),

My response object is something like this:

response = {
page_length=10,
start: 0,
last_page: 10,
total: 200,
results: [....]
}

So now even after setting the last_page to 10, the next button is not getting enabled. Is the ajax call used to fetch all the data at once? Is there any way to fetch the data in chunks according to page size whenever user clicks next/prev buttons?

Thanks

**Comment by adjblink** [comment]
It seems like the Tabulator.js data table is completely dependent on the ajax for remote calls to fetch the data and display. The pagination functionalities starts failing once you use anything other than ajax.

**Comment by tentus** [comment]
Seems a bit hyperbolic, adjblink. I've updated the fiddle to https://jsfiddle.net/f6px1o28/ to test some more functionality and it seems fine to me, what seems to be failing to you?

**Comment by adjblink** [comment]
So, the example you have given creates/fetches all the data in one go; this enables the next button. However in my case I fetch/generate only one page of data from the back end; this causes the next button to be disabled. What I would like to do is enable the next / prev. buttons according to the total records or last_page, so that I can fetch the pages from the back-end when ever user clicks the next/prev buttons.

In Tabulator the last_page only works with the ajax call. Hence I was just trying out with remote pagination by returning the already fetch records in the ajax call function, as shown in my above example. However that did now work and faced the issues as mention in the above comments.

**Comment by tentus** [comment]
I think I understand what you're trying to do, but it seems like so much work to avoid the existing functionality to Tabulator I'm hesitant to make any more suggestions without a better understanding of _why_. As mentioned in the bug reporting form, a fiddle or code pen that demonstrates your approach would go a long way here.

"What I would like to do is enable the next / prev. buttons according to the total records or last_page, so that I can fetch the pages from the back-end when ever user clicks the next/prev buttons" is pretty much verbatim how Tabulator ajax pagination works.

**Comment by adjblink** [comment]
To explain you why I will have to explain you how the angular works or how any enterprise level application works. For calling the backend apis we have to create separate services, which will create the request object and make restful call. The same would generate a subscription which can be used by any application component/class to use the data. In my application I am getting input from different sources, call the apis using services and get the response object and display in the same table. So, there are multiple inputs, multiple urls and multiple request objects. Using your Tabulator ajax, I would be tightly coupling all the components just to one block.

**Comment by tentus** [comment]
I'm aware of how angular works, and have worked on enterprise level software for a living for over a decade. Not all projects require a strict adherence to the separation of concern principle- many of my favorite systems are under a thousand lines long. And, for the record, it's not **my** Tabulator, I'm just an internet rando trying to lend a hand to a library I happen to like, because it solves a problem I have quickly and easily.

Best of luck with your application.

**Comment by adjblink** [comment]
Ok correction "the Tabulator". Then I guess in this case it is not feasible to use Tabulator in my application. Thanks for the help.
