### ISSUE TITLE
TypeError: cell.getElement(...).focus is not a function

### ISSUE THREAD

**Issue by vanderhoff** [olifolkerd/tabulator#2141]
Tabulator 4.2, chrome pc

I am getting the error _TypeError: cell.getElement(...).focus is not a function_ in the following sequence

1. add a column definition on table creation with 
```
//set myColHeadArr as base column header array {"title":"Alpha","field":"alpha"}...
myColArr.editorParams=function(cell){ 
 myFunc(cell);
}
myColHeadArr .push(myColArr);
```
ajax calls for the population of options is deferred until editing

2. If cell is clicked to edit
```
myFunc(cellZ){
//foreach until cell value found on myColHeadArr
var myColArr = JSON.parse(JSON.stringify(value)); // {"title":"Alpha","field":"alpha"}
//ajax call returns select options k:v
myColArr.editorParams={values:["red", "green", "blue", "orange"]};
myColHeadArr.[keyNum]=myColArr
}
table.setColumns(myColHeadArr);
cellZ.edit(true);
```
Now we get the error 
Uncaught TypeError: cell.getElement(...).focus is not a function
```
Edit.prototype.focusCellNoEvent = function (cell) {
		this.recursionBlock = true;
		if (this.table.browser !== "ie") {
			cell.getElement().focus();  //<---error line
		}
		this.recursionBlock = false;
	};
```

We assume this is because the `table.setColumns` is resetting the cell reference.
Is there another way to dynamically update the select options and then select the cell again so the user does not have to re-click the same cell twice?

**Comment by tentus** [comment]
`editorParams` can be a function. Have you tried returning the params directly back from it? that would let you defer the population of options until editing, without forcing the complication of resetting the columns.

Example: https://jsfiddle.net/j1rgd7ms/

**Comment by vanderhoff** [comment]
@tentus thank you, that option worked. We read the doc but did not understand the pass into values until we saw your code.
