### ISSUE TITLE
After celledited callback the focus is moving out

### ISSUE THREAD

**Issue by muthukvs** [olifolkerd/tabulator#2142]
After AJAX call the focus is moving out and focus is set on first cell in the row.

How to change focus to next successive cell after celledited callback

Tabulator version 4.2

Code-
table = new Tabulator("#example-table", {
data:self.get('tableData'),
selectable:true,
height:"311px",
layout:"fitColumns",
addRowPos:"bottom",
pagination:"local",
paginationSize:6,
paginationSizeSelector:[3, 6, 8, 10],
columns:self.get('tableColumnData'),
validationFailed:function(cell, value, validators){
//cell - cell component for the edited cell
//value - the value that failed validation
//validatiors - an array of validator objects that failed

            //take action on validation fail
        },
       
        cellEdited:function(cell){   
            var row = cell.getColumn()._column.definition.field;
            var value = cell.getValue();
            var testData =  table.getData();
            testData.forEach(function(del){
                Ember.set(del, "DELETE", "No");
            });
            self.set('testData',testData);
            self.cellBlur(row,value,testData);
        },
    });

**Comment by tentus** [comment]
Not to discourage your enthusiasm for Tabulator, but can I respectfully request you ask this kind of question on stackoverflow? The submission form is pretty clear:

 > Please ask questions on www.stackoverflow.com the issues list is now reserved for feature requests and bug reports.

**Comment by KES777** [comment]
Try to use `table.navigateNext()`; to select next cell
Doc is [here](http://tabulator.info/docs/4.2/navigation#cell)
