### ISSUE TITLE
`data` is missed for multi level grouping

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#2143]
**Describe the bug**
When I use multi level grouping the `data` parameter is empty array.
For one level group there is data as expected

**Tabulator Info**
- Which version of Tabulator are you using? 4.2

```
  groupBy : function( data ){ return data.agreement_id +'-' + data.period_id },
  groupHeader : function( value, count, data, group ){
    console.log( data );
    return 'asdf';
  },
```
![_2](https://user-images.githubusercontent.com/799021/59281136-6ed19c00-8c6f-11e9-900b-6988a90e1282.jpg)

For multi level:
```
  groupBy : [ 'agreement_id', 'period_id' ],
  groupHeader : [ function( value, count, data, group ){
    console.log( data );
    return 'asdf';
  }, function( value, count, data, group ){
    console.log( data );
    return 'asdf';
  } ],
```

![_3](https://user-images.githubusercontent.com/799021/59281199-86a92000-8c6f-11e9-9a23-8e24b43c1a9b.jpg)

It seems for multi level grouping there is two extra dummy calls and once after the real row:

![_](https://user-images.githubusercontent.com/799021/59281427-f0292e80-8c6f-11e9-9c11-d18ec13e6ef0.jpg)

The table:
![_2](https://user-images.githubusercontent.com/799021/59281546-2070cd00-8c70-11e9-843d-dc2d13f35f07.jpg)

Also documentation does not mention [forth parameter](https://github.com/olifolkerd/tabulator/issues/1630#issuecomment-500874075): `group`

**Comment by KES777** [comment]
@tentus so if there is no data for parent group then I can not generate custom header for it because.... because there is no data.

>If a group contains only other groups then by definition it does not directly contain rows.
Then it should contain other groups, but it contain **nothing** ((

Look here:
![_](https://user-images.githubusercontent.com/799021/59284260-a42cb880-8c74-11e9-8027-305d66b1b5b5.jpg)

Thus this group contain one row grouped by one row.

![_2](https://user-images.githubusercontent.com/799021/59284837-9e83a280-8c75-11e9-8c92-f1b54716d371.jpg)


And here 
![_](https://user-images.githubusercontent.com/799021/59285006-ec98a600-8c75-11e9-9876-c525dd2dee9c.jpg)

is group for agrement_id == 42.
The parent group has four rows grouped together into one subgroup

**Comment by KES777** [comment]
Also you should notice that `group.getSubGroups()` does not return `an array of GroupComponent objects` as documented [here](http://tabulator.info/docs/4.2/components#component-group)
it returns subgroup rows instead.

**Comment by tentus** [comment]
It sounds to me like you're calling `getSubGroups` on a Group, not a GroupComponent that you link to. The latter wraps a call to the former, forcing the return array to be the child components rather than the children directly.

**Comment by jots** [comment]
I am having similar issue.  first group shows $x items match, but the data field is empty and so I can't get the data needed for the groupHeader callback.  How can we get access to the rows that the outer group encompasses?

**Comment by olifolkerd** [comment]
@jots this issue is over a year old and closed.

If your issue is on the latest release it is certainly unrelated to this.

Please raise a bug issue template and submit a is fiddle to show your code

Cheers

Oli

**Comment by jots** [comment]
Thanks.  I ended up using the workaround described at #2145.  I do think the data field should not be empty for top level groups if multi level grouping is used, but I understand that's subjective.
