### ISSUE TITLE
Can not delete cell value in autocomplete editor

### ISSUE THREAD

**Issue by webseitz** [olifolkerd/tabulator#2144]
**Describe the bug**
If a cell uses the autocomplete editor in combination with a lookup-formatter, the cell value cannot be deleted once the cell is filled.

**Tabulator Info**
- Which version of Tabulator are you using? 4.2.7
- Post a copy of your construct object if possible so we can see how your table is setup --> See fiddle https://jsfiddle.net/u7tsy036/

**To Reproduce**
1. Go to https://jsfiddle.net/u7tsy036/
2. Type e.g. "Cars" into the "Kategorien"-cell
3. Click on "Cars" in the dropdown menu
4. Try deleting "Cars" from the cell. --> it will not work

**Expected behavior**
I expect, that the cell would remain empty, if the button-cross is clicked, or the text is deleted from the cell.

**Desktop (please complete the following information):**
 - Browser: Safari
 - Version: 12.2

**Additional context**
This issue is maybe related to issue #1657 .

**Comment by tentus** [comment]
Can confirm this issue on Firefox and Chrome.

While it wouldn't solve this particular bug, https://github.com/olifolkerd/tabulator/pull/1881 could be considered related.

**Comment by olifolkerd** [comment]
Thanks for the headsup,

I will have a look into this.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @webseitz ,

After looking into this further, i can confirm this isnt a bug with Tabulator, there is just a missing property in your ***editorParams***, by default the autocomplete editor does not allow the user to select a value not in the list, as you are trying to select empty text, it wont allow it. 


You need to set the ***allowEmpty*** property to ***true*** to allow this:

```js
editorParams: {
        values: kategorien,
        allowEmpty:true
},
```

I hope that helps,

Cheers

Oli :)
