### ISSUE TITLE
How can i get header filter with drop down with unique values of column by default

### ISSUE THREAD

**Issue by muthukvs** [olifolkerd/tabulator#2147]
I have tabulator and column called change type there i can get values like Insert, Update , Delete

Can I get filter to choose in excel sheet filter like checkbox or dropdown with the unique values in grid?

**Comment by tentus** [comment]
Yes. The value you're looking for is "select" http://tabulator.info/docs/4.2/edit#edit-builtin

Example: https://jsfiddle.net/z5h8yweL/

Another good option is "autocomplete".
