### ISSUE TITLE
AJAX 'select' header filter

### ISSUE THREAD

**Issue by jjech** [olifolkerd/tabulator#2149]
**Is your feature request related to a problem? Please describe.**
In one of my projects, we're already using tabulator AJAX functionality with a remote server and database for pagination, sorting, etc. It's very good at these things, and was relatively quick to get up and running! So, thanks for that.

We're currently using 'input' header filters for manipulating displayed data which is working great --- every time a filter changes, tabulator sends a query to the server, and the server responds with the new data for tabulator to display.

However, there are a few columns which have only a relatively small set of possible values. For these columns, ideally we would like to be using a 'select' header filter rather than 'input.' The problem is, we want the server to tell us what the possible values should be for these filters, similar to how the server decides what pages to send, and how to sort.

**Describe the solution you'd like**
We'd like a way to specify 'select' column header filters as returned by an AJAX request to a remote server. One possible implementation would provide an option to specify an AJAX URL per column when instantiating a new tabulator table.

Example usage - instantiating new tabulator table:
`...
columns:[
    {title:"Component", field:"Component", sorter:"string", editor:"select", ajaxURL:"http://remote.server/api/getComponents", headerFilter:true},
...
`

Example JSON returned by server during tabulator instantiation:
`{"component1":"Component1", "component2":"Component2", "component3":"Component3"}`

Or maybe instead of adding a new ajaxURL option, the URL could just be passed directly into headerFilterParams.

**Describe alternatives you've considered**
We could just keep using 'input' header filters. This works fine, it's just a bit less convenient for our users than a 'select' filter would be.

**Additional context**
Hopefully I've provided enough detail for this request to be understood, but if further clarification is needed, just let me know.

There's a chance that we might implement this feature ourselves and submit a pull request at some point in the future.

**Comment by tentus** [comment]
I'm a fan of this idea, though I might suggest that instead of the `ajaxUrl` being in the column definition, it be nested into `headerFilterParams`.

In the meantime, speaking of `headerFilterParams`, you could use the function approach to make it populate itself with a remote call. The last example for `select` on http://tabulator.info/docs/4.2/edit#edit-builtin is probably pretty close to what you're looking for.

**Comment by olifolkerd** [comment]
Hey @jjech 

This has been suggested by a few users, i am certainly looking at adding it in future, but it will require a bit of rejigging to allow editors to asynchronous loading of info.

In the mean time, a work around would be to load the data in the background in to variables and then use a callback on the ***values*** properties to retrieve them

Cheers

Oli :)

**Comment by olifolkerd** [comment]
I have just pushed updates to the 5.2 branch that replaces the ***select*** and ***autocomplete*** editors with the new ***list*** editor, which will add this functionality via the new ***valuesLookup*** param.

It will be included in the 5.2 release later this month.

Cheers

Oli :)
