### ISSUE TITLE
Parent Data In Children

### ISSUE THREAD

**Issue by scott-oliver** [olifolkerd/tabulator#2150]
Similar to the following data tables plugin (below), it would be extremely useful for the children to hold their parent's identifier, rather than nesting the children's code within the parent.

Not only will this cut down and simplify the dataset, but from what I can gather it would go some way towards us being able to conditionally format, scroll to and filter the entire data set (including children).

From what I have read, it looks like you are well and truly giving children/parent some thought, but I just hoped to share another HTML table example.

Tree Tables Plugin: https://github.com/reside-ic/TreeTables

**Comment by fr0z3nfyr** [comment]
Does `row.getTreeParent();` as explained in [docs](http://tabulator.info/docs/4.2/tree#component) (see **Get Parent Row**) solve the problem here?
