### ISSUE TITLE
fitColumns with percentage widths don't redraw correctly

### ISSUE THREAD

**Issue by ikaney** [olifolkerd/tabulator#2151]
Tabulator v4.2.7

I create a Tabulator table with 'fitColumns' layout, the columns are set to be percentage widths of the parent element total width. System draws table fine.

The parent element is resized, redraw is called with the force parameter set to true, the column widths remain the same even though they should use the percentage of the new width of parent element.

I have abused the code to fix this in my environment by adding 'column.setWidth(colWidth)' into the 'fitColumns' function as such:

columns.forEach(function (column) {
                var width, minWidth, colWidth;
                if (column.visible) {
                    width = column.definition.width;
                    minWidth = parseInt(column.minWidth);
                    if (width) {
                        colWidth = calcWidth(width);
                        fixedWidth += colWidth > minWidth ? colWidth : minWidth;
                        if (column.definition.widthShrink) {
                            fixedShrinkColumns.push({
                                column: column,
                                width: colWidth > minWidth ? colWidth : minWidth
                            });
                            flexShrinkUnits += column.definition.widthShrink;
                        }
                        // IK FIX <----
                        column.setWidth(colWidth);                        
                    } else {
                        flexColumns.push({
                            column: column,
                            width: 0
                        });
                        flexGrowUnits += column.definition.widthGrow || 1;
                    }
                }

**Comment by tentus** [comment]
Could you throw together a quick jsfiddle or codepen to illustrate your issue, and some details about which browsers etc you've tested this on?

Quick tip, you can use three backticks (the ` in the top left of your keyboard) to start and end a block of code, which makes it much easier to read.
