### ISSUE TITLE
Cannot use form elements inside custom editors

### ISSUE THREAD

**Issue by morficus** [olifolkerd/tabulator#2152]
**Describe the bug**
When using a form element inside a custom editor, the cell prematurely exits from "edit mode" when switching element focus.

**Tabulator Info**
- Which version of Tabulator are you using?
4.2.7
- Post a copy of your construct object if possible so we can see how your table is setup
See working example for details

**Working Example**
https://jsfiddle.net/morficus/y6qdew1v/105/

**To Reproduce**
See the "working example" link for steps

**Expected behavior**
The custom editor would stay open until the `success()`or `cancel()` callback is triggered

**Screenshots**
Not applicable. 

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.5
 - Browser: Chrome  74.0.3729.169

**Smartphone (please complete the following information):**
Not applicable

**Additional context**
I dug a bit in to the Tabulator code to see where this was happening... and figured out that it has to do with the `focus` even and the listener that is setup line [/src/js/modules/edit.js#L124](https://github.com/olifolkerd/tabulator/blob/master/src/js/modules/edit.js:124).
When the user moves between form elements on the custom editor... it naturally triggers a "focus" event. This event gets captured by the listener that was setup in `bindEditor()` and ultimately calls [this line](https://github.com/olifolkerd/tabulator/blob/master/src/js/modules/edit.js#L152) which forcefully cancels the editing.

**Comment by aklaver** [comment]
Is this not covered by?:
http://tabulator.info/docs/4.2/edit#edit
"Blur Event
It is important to note that a custom editor must specify how to handle a blur event on its element by either calling the success or cancel functions. This is because when a user clicks or tabs out of a cell, the blur event will be fired and must be handled to move on to the next cell. As a fallback Tabulator will cancel the edit if an editor is blured and the event has not been correctly handled. "

**Comment by morficus** [comment]
@aklaver yeah I think it is related to that but not covered by it.
In my case the cell is still being edited but the edit gets canceled when interacting with any form fields in the custom editor.

**Comment by olifolkerd** [comment]
Hey @morficus 

This is because your editor is not setup correctly, it is not cancelling the edit on a full blur and is not handling the blur of the input element correctly.

Cheers

Oli :)

**Comment by sksaifuddin** [comment]
I am also facing the issue, I have multiple inputs and when the user edits the one input it emits blur event and goes out of edit. @morficus  did you  find any work around for this ?
