### ISSUE TITLE
4.3 version tabulator will be released recently?

### ISSUE THREAD

**Issue by yoyomule** [olifolkerd/tabulator#2153]
Hi, may I ask whether the 4.3 version tabulator will be released recently? We felt that tabulator was a good tool and were going to try it out for the next project, but we wanted to go straight to version 4.3 because we saw that we would be adding a Google Material theme.

**Comment by olifolkerd** [comment]
Hey.

Ive had a busy couple of months at work so I'm running a bit behind on version 4.3.

It should be released at some point in the next few weeks

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hi Chaps, a quick update on this can be found in #2213

Cheers

Oli :)
