### ISSUE TITLE
Possibility to extend default actions ?

### ISSUE THREAD

**Issue by pynog** [olifolkerd/tabulator#2154]
Hi,

Is there an easy way to extend the set of actions we can use on rows?
I wanted to try to do something like below:
  'keybindings': {"test": "82"}
And somewhere in the Js define:
  function test(e) {console.log("test")}

but it seems it has to be first defined in the Keybindings.prototype.actions and I am not sure how to extend it. 

Thanks
Olivier

**Comment by morficus** [comment]
Hey @pynog - 
You can extend modules in Tabulator by doing the following:
```
Tabulator.prototype.extendModule("keybindings", "bindings", {
    navPrev:"shift + 9",
});
```

Here is the documentation around the `extendModule` function: http://tabulator.info/docs/4.2/modules#extend
And here is documentation around keybindings: http://tabulator.info/docs/4.2/modules#module-keybindings

Cheers

**Comment by pynog** [comment]
Hi, 

It works perfectly well, thanks a lot for your help !
