### ISSUE TITLE
How can I make rowheight automaticly adjust to custom editor?

### ISSUE THREAD

**Issue by rhagstrand** [olifolkerd/tabulator#2156]
Hi, im trying to create a simple custom editor with a textarea and a save-button. 
This code is not done, but Im having issues making the row automaticly adjust height (like the normal textarea editor does).

Can anyone help me?

var buttonEditor = function (cell, onRendered, success, cancel, editorParams) {
    //cell - the cell component for the editable cell
    //onRendered - function to call when the editor has been rendered
    //success - function to call to pass the successfuly updated value to Tabulator
    //cancel - function to call to abort the edit and return to a normal cell
    //editorParams - params object passed into the editorParams column definition property

    //create and style editor
    var editor = document.createElement('DIV');
    editor.setAttribute("class", "editArea");
    editor.setAttribute("style","height:100%;")
    

    //create and style input
    editor.style.padding = "3px";
    editor.style.width = "100%";
    editor.style.boxSizing = "border-box";

    //set focus on the select box when the editor is selected (timeout allows for editor to be added to DOM)
    onRendered(function () {
        editor.focus();
        editor.style.css = "100%";
        $('.editArea').append($('<textarea id="textarea" style="width:100%;height:100%;"></textarea>'));
        $('.editArea').append($('<input type="button" value="Spara" class="save" />'));
        $('#textarea').val(cell.getValue());
        $('#textarea')[0].addEventListener("change", successFunc);
        $('#textarea')[0].addEventListener("blur", successFunc);
    });

    //when the value has been set, trigger the cell to update
    function successFunc() {
        success($('#textarea').val());
    }
    //return the editor element
    return editor;
};

**Comment by rhagstrand** [comment]
ILl answer my own question (example code below adds save-button and abort-link to handle the editing, code is NOT fully done and probably buggy, but works more or less). cell.getRow().normalizeHeight() is the MVP here.

var buttonEditor = function textarea(cell, onRendered, success, cancel, editorParams) {
    var self = this,
        cellValue = cell.getValue(),
        value = String(cellValue !== null && cellValue !== "undefined" ? cellValue : ""),
        count = (value.match(/(?:\r\n|\r|\n)/g) || []).length + 1,
        inputWrapper = document.createElement("DIV"),
        input = document.createElement("TEXTAREA"),
        inputBtn = document.createElement("BUTTON"),
        abortLink = document.createElement("a"),
        scrollHeight = 0;

    //create and style input
    inputWrapper.style.height = "100%";
    inputWrapper.style.width = "100%";
    inputWrapper.style.boxSizing = "border-box";
    inputWrapper.style.display = "block";

    input.style.padding = "2px";
    input.style.whiteSpace = "pre-wrap";
    input.style.resize = "none";

    inputBtn.style.height = "25px";
    inputBtn.style.width = "50px";
    inputBtn.textContent = "Spara";
    inputBtn.addEventListener("click",saveChanges);
    
    abortLink.textContent = "Avbryt";
    abortLink.style.marginLeft = "10px";
    abortLink.addEventListener("click", abortChange)
    abortLink.href = "#";

    inputWrapper.appendChild(input);
    inputWrapper.appendChild(inputBtn);
    inputWrapper.appendChild(abortLink);

    input.value = value;

    onRendered(function () {
        input.focus();
        input.style.height = "1px";
        setTimeout(function () {
            input.style.height = (input.scrollHeight) + "px";
            cell.getRow().normalizeHeight();
        }, 1);

        
    });

    function saveChanges() {

        if ((cellValue === null || typeof cellValue === "undefined") && input.value !== "" || input.value != cellValue) {
            success(input.value);
            setTimeout(function () {
                cell.getRow().normalizeHeight();
            }, 300);
        } else {
            cancel();
            cell.getRow().normalizeHeight();
        }
    }

    function abortChange(e) {
        cancel();
        cell.getRow().normalizeHeight();
    }

    //submit new value on blur or change
    inputWrapper.addEventListener("change", abortChange);
    inputWrapper.addEventListener("blur", abortChange);

    input.addEventListener("keyup", function () {

        input.style.height = "1px";

        var heightNow = input.scrollHeight;

        input.style.height = heightNow + "px";

        if (heightNow != scrollHeight) {
            setTimeout(function () {
                scrollHeight = heightNow;
                cell.getRow().normalizeHeight();
            }, 1);
        }
    });

    input.addEventListener("keydown", function (e) {
        if (e.keyCode == 27) {
            cancel();
        }
    });

    return inputWrapper;
}

**Comment by olifolkerd** [comment]
Hey @rhagstrand 

you need to set the ***variableHeight*** property on the column definition to ***true***

Cheers

Oli :)
