### ISSUE TITLE
Safari: Can't change values on checkboxes

### ISSUE THREAD

**Issue by truthspirit** [olifolkerd/tabulator#2157]
Safari Version 12.1.1 (13607.2.6.1.2)
OSX Version 10.13.6

When I click on a check column, on the tabulator.info main site, I can't change the value in Safari. Works fine in Chrome.

**Comment by tentus** [comment]
I can confirm the behavior on the same safari/mac combo, and also that checkboxes work as expected in Firefox. Bug also shows up on http://tabulator.info/examples/4.2#editable if that helps, and I made a little fiddle that also illustrates the issue https://jsfiddle.net/aystpjLf/

**Comment by pboyd04** [comment]
I've got two separate users complaining about this on my site. When I sent them to the tabulator example they both experienced the issue as well. The 'tick' editor is the only one that seems broken. Other editors seem to work fine.

**Comment by tentus** [comment]
Did a bit more digging, I suspect this is related to https://github.com/olifolkerd/tabulator/issues/825

In the meantime, on that issue there Oli mentioned a trick that might serve as a stopgap until this is fixed:
```
{title:"Driver", field:"car", width:50, align:"center", formatter:"tickCross", cellClick:function(e, cell){
    cell.setValue(!cell.getValue());
}},
```

**Comment by olifolkerd** [comment]
I will see if there is anything i can do to help with this on the weekend.

Cheers

Oli :)

**Comment by AndrewHutcheson** [comment]
Is this issue on the roadmap to be fixed? I can confirm it happens with the latest safari on desktop, and iPhone7 and iPhone 11.

**Comment by rjaros** [comment]
This issue should be reopened. Checkboxes don't work on Safari 14.1.

**Comment by sjiampojamarn** [comment]
This issue is not yet fixed. Reproduce on macOS Monterey 12.1 with Safari Version 15.2 

http://tabulator.info/examples/5.0#editable

Unable to edit checkboxes but able to edit other fields.

No issues with Chrome Version 97 on the same machine

**Comment by olifolkerd** [comment]
Hey everyone,

I have just pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)
