### ISSUE TITLE
Textarea formatter cell height bug in Chrome

### ISSUE THREAD

**Issue by alanbentley** [olifolkerd/tabulator#2159]
**Describe the bug**
Resizing the table that has a fixed height and a column using the textarea formatter causes the text to disappear behind the next row due to the height of the row being too small for the content.

This seems to only happen the table has a height and I believe it is because the height calculation is carried out on the virtual dom where the scrollbar does not exist and therefore the reduced width in the cell is not accounted for. 

**Tabulator Info**
- Version: 4.2.7

**Working Example**
https://jsfiddle.net/alanbentley/zhceofwg/

**Screenshots**
https://ibb.co/cCSzfSV

**Desktop**
 - OS: macOS 10.4 and windows 7
 - Browsers: Chrome, Firefox, Safari and IE11

**To Reproduce**
On a mac you will need to set your scroll bars to always display: system preferences/general and under 'show scroll bars' choose 'always'

Go to https://jsfiddle.net/alanbentley/zhceofwg/ an in the rendered table you will see the message cell with cropped content.

**Comment by tentus** [comment]
I haven't been able to replicate what I think you're describing but maybe I'm misreading your post. Can you share a couple screenshots highlighting the issue? Knowing what version of Chrome you're on might also be helpful.

**Comment by alanbentley** [comment]
Thanks for looking into this - below is a screenshot:
https://ibb.co/cCSzfSV

Chrome version: 74.0.3729.169

**Comment by alanbentley** [comment]
Thanks for looking into this - below is a screenshot:
https://ibb.co/cCSzfSV

Chrome version: 74.0.3729.169

**Comment by tentus** [comment]
Interesting, I'm not able to reproduce on Chrome 75 (or firefox, safari, even opera). I assume this is not happening on Firefox or any other browsers you have handy?

**Comment by alanbentley** [comment]
Updated to Chrome 75 and its now working as expected. I'll check on other browsers later - but looks as though its only an issue with Chrome 74

**Comment by alanbentley** [comment]
Sorry, got that wrong - its still not working - I was looking at the version where the table was set a 600px. The problem is still there in Chrome 75

**Comment by alanbentley** [comment]
Finished testing cross browsers and platform. The bug is in on both mac and windows in firefox, chrome, safari, and ie.

You wont see the bug on a mac unless you force scroll bars to appear: system preferences/general and under 'show scroll bars' choose 'always'

**Comment by tentus** [comment]
Oh wow, yep you're absolutely right, forcing macOS to always show the scrollbar causes the bug to appear. Good find!

At this point I have to admit I'm out of my depth, hopefully Oli will be able to swoop in with a clever fix. I was hoping to be able to come up with a short-term workaround but I've come up empty-handed so far. :(

**Comment by olifolkerd** [comment]
Hey @alanbentley 

Thats an interesting one you have found there, good work!

That should be a quick fix i can see what needs to be called in the render functions.

I will make sure that is included in the weekends release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @alanbentley 

Looking into this further, it is an extremely niche occurrence.

It will only occur in tables where the initial rows are just not quite enough to fill the height of the table, and setting the text area width then causes the row heights to adjust enough to cause a scrollbar to appear.

It is only present in fitColumns layout mode and only when there are textarea that has no width set, and even in that case only if the table was just about full enough but not quite at the point it needs a scroll bar.

I will certainly look into it further, but given the niche set of requirements to set it up and the fact that it can be mitigated by calling `table.redraw(true);` after the table has been instantiated, iam going to stick it on a lower priority than some of the more critical bugs, so will get to it in one of the upcoming releases.

Cheers

Oli :)
