### ISSUE TITLE
GetData using index?

### ISSUE THREAD

**Issue by cemmons** [olifolkerd/tabulator#216]
Hi, it's me again xD.. great work by the way.

I have a problem, does tabulator let you get data using an id as filter?

Something like, 

```
varr  indexValue = 1;
var data = $("#example-table").tabulator("getData", indexValue);
```

I can do something like  getting all the data and then filtering using jquery, but I'm looking for performance here.

Thanks in advance

**Comment by olifolkerd** [comment]
Hey,

Are you trying to get the data of a single row, or all of the rows for a single column?

Cheers

Oli

**Comment by cemmons** [comment]
I'm trying to get the data of a single row, something like SQL

`SELECT * FROM table WHERE id = 1`

What I'm doing is trying to get the data from the row, to populate a popover html with some data, edit that data and then Update the row again using updateRow.

So far I've been using CellClick on a button column, that shows the popover.

**Comment by olifolkerd** [comment]
A function specifically for that will be coming in next months release.

In the mean time i would suggest using a jquery selector to do the same thing:
```js
var rowData = $("#example-table .tabulator-row[data-index=" + indexValue + "]").data("data");
```
Cheers

Oli

**Comment by cemmons** [comment]
Thanks, I could resolve my problem with the popover.
