### ISSUE TITLE
bottomCalcParams crashes table

### ISSUE THREAD

**Issue by bhanson-techempower** [olifolkerd/tabulator#2161]
**Describe the bug**

`Uncaught ReferenceError: value is not defined`

ReferenceError when calling bottomCalcParams.

**Tabulator Info**

- Which version of Tabulator are you using? 4.2.7
- Post a copy of your construct object if possible so we can see how your table is setup. See jsfiddle

**Working Example**

https://jsfiddle.net/bhanson_techempower/2zq15Lrp/

**To Reproduce**

1. Run jsfiddle
2. Open console and see error

**Expected behavior**

Table should display without error.

**Desktop (please complete the following information):**

 - OS: Windows 10 Version 1809 (Build 17763.557)
 - Browser: Chrome 75.0.3770.100

**Additional context**

https://github.com/olifolkerd/tabulator/blob/master/dist/js/tabulator.js#L10796

See line 10796.

http://tabulator.info/docs/4.2/column-calcs#func-builtin

According to the documentation, this value is supposed to be `values - array of column values`

We believe we have identified the issue and have a fix locally - would you like us to open a pull request?

**Comment by tentus** [comment]
Your logic makes sense to me, I'd say go ahead and make the PR. 

Your PR would just be to add the missing `s` to `value`, right? Highest commit-message-to-commit-contents ratio ever :D

**Comment by bhanson-techempower** [comment]
See pull request #2165

**Comment by olifolkerd** [comment]
Hey @bhanson-techempower 

Thanks for the headsup and the PR, i will get that merged in at the weekend.

Cheers

Oli :)
