### ISSUE TITLE
bottomCalc doesn't update on setting "both"

### ISSUE THREAD

**Issue by bhanson-techempower** [olifolkerd/tabulator#2164]
**Describe the bug**

When `columnCalcs` is set to `both` only the grouped `bottomCalc` is called. The one for the entire table does not get updated.

**Tabulator Info**

- Which version of Tabulator are you using? 4.2.7
- Post a copy of your construct object if possible so we can see how your table is setup. See jsfiddle

**Working Example**

https://jsfiddle.net/bhanson_techempower/bLay8u5m/

**To Reproduce**

1. Run jsfiddle
2. Edit Age fields
3. See bottom calculation not updating

**Expected behavior**

On a cell edit, `bottomCalc` will be called for both the group and the entire table.

**Desktop (please complete the following information):**

 - OS: Windows 10 Version 1809 (Build 17763.557)
 - Browser: Chrome 75.0.3770.100

**Additional context**

Very closely related to issue #1646

**Comment by olifolkerd** [comment]
Hey @bhanson-techempower 

Thanks for the headsup,

I will look at getting a fix for this in for the next release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @bhanson-techempower 

I have pushed a fix for this to the 4.3 branch and will include it in tomorrows release.

Cheers

Oli :)
