### ISSUE TITLE
The & operator has been used instead of && in validate.js

### ISSUE THREAD

**Issue by darshanrampatel** [olifolkerd/tabulator#2166]
**Describe the bug**
The & operator (bitwise AND) has been used instead of && (logical AND) in the required function in `validate.js`

**Tabulator Info**
- Which version of Tabulator are you using? 4.2.7

**To Reproduce**
https://github.com/olifolkerd/tabulator/blob/ff2dc1ec5f85e8e5ad2f214abd7ed35fd8ae1d49/src/js/modules/validate.js#L206

**Expected behavior**
Use && instead of &

**Additional context**
Both this issue and issues #2163 and #2161 could have been found if TypeScript checking was enabled.

**Comment by aklaver** [comment]
PR created:
https://github.com/olifolkerd/tabulator/pull/2175

**Comment by darshanrampatel** [comment]
@aklaver See PR #2167
