### ISSUE TITLE
Column Calculations At every level in Row Grouping

### ISSUE THREAD

**Issue by kpkalwa** [olifolkerd/tabulator#2168]
I was evaluating tabulator for a requirement. In which i need the calculation of columns at each and every row group.

Currently, the column calculations are computed only at the overall level or the nth level in the tabulator. 

Is the feature for calculation of column at every level is present in your roadmap ? If so, when can we expect the feature to be released. If not, can you add this to your roadmap .?

**Comment by aklaver** [comment]
The options here:

http://tabulator.info/docs/4.2/column-calcs#visibility

don't meet your needs?
If not then you will need to mock up what it is you want.

**Comment by kpkalwa** [comment]
![Table](https://user-images.githubusercontent.com/10389768/60160944-1b854f00-9814-11e9-9575-a6e499bf7cdd.PNG)

I need the grouping summation to be enabled at each level , if we have 2 or more group by condition as shown in the image.

Currently, tabulator provides grouping at outermost i.e., Grand total and subtotal at innermost child element.

**Comment by kpkalwa** [comment]
> The options here:
> 
> http://tabulator.info/docs/4.2/column-calcs#visibility
> 
> don't meet your needs?
> If not then you will need to mock up what it is you want.

**Comment by kpkalwa** [comment]
> The options here:
> 
> http://tabulator.info/docs/4.2/column-calcs#visibility
> 
> don't meet your needs?
> If not then you will need to mock up what it is you want.

I need the grouping summation to be enabled at each level , if we have 2 or more group by condition as shown in the image.

Currently, tabulator provides grouping at outermost i.e., Grand total and subtotal at innermost child element.
![Table](https://user-images.githubusercontent.com/10389768/60161192-a1a19580-9814-11e9-92ce-e1cad67c729f.PNG)

**Comment by aklaver** [comment]
Alright I see what you are after. That will need to be something Oli comments on. As it is now the issue is closed. Not sure if you can reopen it or not? If not you might want to create another issue that points to this one to keep your request in view.
