### ISSUE TITLE
setPage at startup got Pagination Error - Requested page is out of range.

### ISSUE THREAD

**Issue by dua-tanjung** [olifolkerd/tabulator#2170]
Hi, I'm using tabulator v4.2.7

I'm trying to remember the last page on a table (in a php page), so when I get back to the table, I want the table to go immidiately to specific page. I'm saving the last page in a php session.

```
CurrentPage = <?=$current_page?>;
tbl = new Tabulator("#tbl1",{
    ajaxURL: "json.php",
    ajaxConfig: "POST",
    ajaxContentType: "json",
    ajaxParams: tblParam,
    columns: cols.tabCols(),
    height: 500,
    layout: "fitDataFill",
    selectable: 1,
    ajaxFiltering: true,
    ajaxSorting: true,
    pagination: "remote",
});
tbl.setPage(CurrentPage)
.then(function(){
    //run code after table has been successfuly updated
})
.catch(function(error){
    //handle error loading data
});
```
But I'm getting error, and the loaded data was page 1.
![image](https://user-images.githubusercontent.com/8489404/59896140-919f4580-9411-11e9-9279-cd449f74159b.png)

What is wrong with my code?
Thanks.

Edit: Just see the persistent settings, it would be wonderful if it can store the last page showed too.

**Comment by tentus** [comment]
Take a look at the http://tabulator.info/docs/4.2/callbacks page and familiarize yourself with the execution order: I think there may be gotchas that could give you some headaches with implementing this particular feature.

Something that might make your life easier is to use javascript's`localStorage` in place of the php session: as useful as php sessions are, trading values back and forth with the window can be a bit cumbersome. For example, in my own main project I use a this combination to keep the pagination size persisted: 
```
paginationSize: localStorage.getItem('pagination_size') || 10,
```
and 
```
$(document).on("change", "select.tabulator-page-size", function () {
  localStorage.setItem('pagination_size', this.value);
});```

**Comment by dua-tanjung** [comment]
Thanks for replying.

As your suggestion, I've read the callbacks information but I can't find anything useful to solving my problem. 

I don't have any problem saving the last page number in php session (and apparently I will change that to local storage). The real problem is, when I request to load specific page with setPage method (without calling setData first) I got pagination error and the ajax requested page 1 instead.

I think requesting page other than 1 without setData first will trigger the error, because tabulator have no idea how many pages the data will be.

**Comment by tentus** [comment]
I hesitate to suggest this, since it feels like a risky assumption to me, but if you're going to take on faith that the last page number is still valid, then you can also take on faith that the max page is at least that number. So, you could precede your `tbl.setPage(CurrentPage)` line with a `tbl.setMaxPage(CurrentPage);` line, and then the ajax call should update the max for you. Here's an example roughly illustrating what I mean:

https://jsfiddle.net/kbvqmjhs/

**Comment by dua-tanjung** [comment]
Yes, I tried that and thats solved my problem.

Thanks for your help.
