### ISSUE TITLE
Negative number filtered incorrectly.

### ISSUE THREAD

**Issue by eoslund** [olifolkerd/tabulator#2171]
I just started using tabulator for an application. Much is working very well, but when I included filtering for numeric column with a min - max using the example code  "minMaxFilterEditor" the negative numbers are not handled correctly. with min = -1 and max = 0 the results are between -1 and -2.46 in my case.
![image](https://user-images.githubusercontent.com/19439186/59942572-113b0d80-942e-11e9-9507-11a50f38148e.png)

Is there an easy fix for this, I would prefer not to create a custom function.

**Comment by tentus** [comment]
Two probable answers spring to mind: one, javascript's typecasting often causes issues. Consider the following:
```
>   -1.3 >= "-1"
false

>   "-1.3" >= "-1"
true
```
Presumably your column is made up of floats, but unfortunately values derived from html inputs (even ones marked as type=number, like in the example editor) are treated as strings. If this is the root of your issue, a little judicious application of `parseFloat` should get you up and going again.

Another possible answer is that you may be falling into a gap between events: I haven't had time to dig into this much, but there seems to be a point in the lifecycle where you could enter a value into one input, which filters, and then give focus to the second, which resets the filtering. Try playing around with this and see if it helps you out at all: https://jsfiddle.net/jh4ukoq6/

**Comment by aklaver** [comment]
What is your column definition that the filter is running on?

**Comment by eoslund** [comment]
Here is what the definitions look like. Any suggestions for improvement
would be appreciated.


1.  align: "right"

2.  field: "End Wt May2019"

3.  headerDblClick: *ƒ **(e,column)*

4.  headerFilter: *ƒ **(cell, onRendered, success, cancel, editorParams)*

1.  arguments: (...)

2.  caller: (...)

3.  length: 5

4.  name: "minMaxFilterEditor"

5.  prototype: {constructor: *ƒ*}

6.  __proto__: *ƒ **()*

7.  *[[FunctionLocation]]*: *redirect.asp?url=/gr…slund/js/vaw.js:412*

8.  *[[Scopes]]*: Scopes[3]

5.  headerFilterFunc: *ƒ **minMaxFilterFunction(headerValue, rowValue,
rowData, filterParams)*

6.  sorter: "number"

7.  title: "End Wt May2019"

8.  __proto__: Object



function minMaxFilterFunction(headerValue, rowValue, rowData, filterParams){

    //headerValue - the value of the header filter element

    //rowValue - the value of the column in this row

    //rowData - the data for the row being filtered

    //filterParams - params object passed to the headerFilterFuncParams
property



        if(rowValue){

            if(headerValue.start != ""){

                if(headerValue.end != ""){

                    return rowValue >= headerValue.start && rowValue <=
headerValue.end;

                }else{

                    return rowValue >= headerValue.start;

                }

            }else{

                if(headerValue.end != ""){

                    return rowValue <= headerValue.end;

                }

            }

        }

**Comment by eoslund** [comment]
Thanks, that is an excellent explanation. works perfectly.
