### ISSUE TITLE
FIlter based on number in scientific notation

### ISSUE THREAD

**Issue by BinLiu9205** [olifolkerd/tabulator#2173]
Hello, dear developers 

I really appreciate the library you have developed, it is really helpful. However, when I was using it, I realized a small flaw in filtering function. The project I am working on generates a lot of extremely small numbers, which are usually written in scientific notation format, such as 5E-12. When I added a filter on such columns to have a threshold (e.g. headerFilterFunc:">="), these numbers are always causing problems. It seems that the filter can only understand the digits before E and compare these with the customized threshold. 
For example, if I search in the column for numbers greater than 4, I would have 5E-12, which is clearly not the case. Is it possible you add some new features in supporting filtering numbers which are written in scientific notations?
Thank you again for the tool.

**Comment by tentus** [comment]
It sounds like your perhaps your data is returning values as strings rather than numbers, but it's hard to diagnose without seeing what you're doing.

Here, I've started a fiddle for you, please fork this into an illustration of your issue:
https://jsfiddle.net/okn5uzms/

**Comment by BinLiu9205** [comment]
Thank you tentus. You are right about the string and number issue. I solved it by writing a function to change all the numbers in decimals instead of using the scientific notation. Happy to know tabulator also supports scientific notation and the problem was caused by my input. Thanks again for the tool
