### ISSUE TITLE
change indendation for tree: text of same level aligned

### ISSUE THREAD

**Issue by wivaku** [olifolkerd/tabulator#2174]
It would be nice if text for same level can be aligned.
Left is mockup of the the current situation, right is the aligned version.
![image](https://user-images.githubusercontent.com/2084872/60017420-fc0deb00-9688-11e9-80fb-8e314ec37744.png)

**Comment by aklaver** [comment]
Hmm fooling around in the code got the below, would that work?:
![Screenshot-2019-6-28 Table - Tabulator](https://user-images.githubusercontent.com/658260/60373072-b10b1500-99b3-11e9-9678-bd90aad894f3.png)

**Comment by wivaku** [comment]
nice. I think I would prefer it without an "empty box". The box suggests it has relevance, plus it makes it harder to distinguish the ones with and without the +

**Comment by olifolkerd** [comment]
Hey @wivaku 


You could achieve fairly simply.

by default the ***dataTreeChildIndent*** setup option has a default of ***9*** which is the number of pixels margin between the branch element and the cell contents. if you were to increase this to ***25*** *(the width of the checkbox and its extra padding)* in your table constructor.

and then in the CSS on the ***.tabulator-data-tree-control*** selector add a ***margin-left*** of ***-16px*** this will then shift the checkbox back over the empty space.

I hope that makes sense

Cheers

Oli :)

**Comment by wivaku** [comment]
great workaround, thanks. The `.tabulator-data-tree` does the trick. It does overlap the + with the |_ but that's a detail. The `dataTreeChildIndent` does `<indent> |_ text` instead of `|_ <indent> text`, right?
