### ISSUE TITLE
undo rowDelete problem

### ISSUE THREAD

**Issue by GaoFolk** [olifolkerd/tabulator#2176]
Hello.
After deleting a row on click a button - cell.getRow().delete();
undo action cannot restore it back.

$("#history-undo").on("click", function(){
  table.undo();
});

I think problem covers in this part of code:

    var index = _this6.table.rowManager.getRowIndex(_this6);

			_this6.deleteActual();

			if (_this6.table.options.history && _this6.table.modExists("history")) {

				if (index) {

					index = _this6.table.rowManager.rows[index - 1];
				}
				
				_this6.table.modules.history.action("rowDelete", _this6, { data: _this6.getData(), pos: !index, index: index });
			}

![image](https://user-images.githubusercontent.com/24685372/60091404-2de88580-974d-11e9-9614-2c2665944c75.png)

'pos' always get false.

Tabulator v4.2.7

**Comment by tentus** [comment]
Please provide a fiddle or codepen that illustrates your bug, and other data mentioned in the submission template.

To help you out, here's a fiddle that shows undo restoring rows after they're deleted:
https://jsfiddle.net/z192s8uo/
