### ISSUE TITLE
Fit column to 

### ISSUE THREAD

**Issue by julien-barbier-minesales** [olifolkerd/tabulator#2177]
Hello,
Thx for your application.

Actually I have a table who use "Fit To Width" as layout but i wanted some of my column to fit data but i didnt find a way to do it.

Do you have a way to put the proprety of "FitData" to a single column ?

Best Regards

**Comment by tentus** [comment]
To my knowledge there's no convenient trick to accomplish this, with the layout modes currently available. What you'll need to do instead is extend the layout modules (see http://tabulator.info/docs/4.2/modules#extend) to have a new mode that supports this.

If you get it working please do share your extension here, it's easy to imagine that other people would love to have such a mode available.

**Comment by julien-barbier-minesales** [comment]
Thx for your quick response. 
I dont think i have the technical level to do this.
But i keep your advice in mind.

Best Regards
