### ISSUE TITLE
Unintuitive select + autocomplete behavior

### ISSUE THREAD

**Issue by joshkpeterson** [olifolkerd/tabulator#2178]
Okay so with a classic html select input, you have:
`<select>
    <option value="val for posting goes here">Label goes here</option>
</select>
`

So after reading the docs, I make an object to go in editorParams > values like {valueforposting1: 'label', valforposting2: 'label2'}

This shows all the labels in the dropdown list, which is great. But then when the user selects an option, it displays the text I'm trying to post! This isn't how `<select>` works. Maybe you think this editor should work differently, but then can we get some documentation? Because this seems like a classic use-case. I just tried a bunch of things with formatter + listItemFormatter but couldn't get it right.

Thanks!

**Comment by tentus** [comment]
Make a lookup formatter against your object, something like this: 
```formatter: (cell) => valuesForPosting[cell.getValue()]```

here's a simple example that might be clearer: https://jsfiddle.net/93fjy2ho/

**Comment by joshkpeterson** [comment]
@tentus thanks - from your example I found that the problem was I was putting the formatter inside editorParams inside of the column level. Maybe the docs example for select could have a formatter. Closing.
