### ISSUE TITLE
Json bool in column format

### ISSUE THREAD

**Issue by wollo** [olifolkerd/tabulator#2179]
I am passing the following cloumn json definition in one of my tabulators (BTW I start to love tabulator! many thanks!):
`{"headerFilterParams":{"values":"1"},"field":"Rolle","headerFilter":"select","title":"angemeldet als:"}`

This json string is generated from a php object and this is genertating for the boolean value true for the item "values" the string "1". With this the auto generation of the select values is not working. I have to change explicitly "1" to true, even though both is valid json. The problem is, that php json_encode is always returning the string  "1"  instead of true for this string.
Can this be changed in tabulator?

**Comment by tentus** [comment]
It kinda sounds like you're hitting a db issue more than a php or tabulator issue. Consider the following php snippet: http://www.ideone.com/UJHbG9

The json output of the boolean value is a bool, not a 0 or 1. If you can, would you share your source data and I'll see if I can give you any suggestions about how to encode it. (Any additional context about how you're currently encoding it would also be helpful).
