### ISSUE TITLE
Width of grouped columns in the footer row keeps oscillating during data updates

### ISSUE THREAD

**Issue by saleyn** [olifolkerd/tabulator#2180]
**Describe the bug**

Once the table is constructed, everything concerning column widths seems fine, and the table looks like this after `replaceData()` call:

![image](https://user-images.githubusercontent.com/272543/60267490-59d44a00-98b8-11e9-8e3e-a9932fde4d63.png)

The script sets up a timer, which every several seconds calls `equity_table.redraw(true);` in order to force updates of a calculated column, which displays the number of seconds that elapsed for a data row since its last update.

Very shortly after that call happens, the widths of columns in the footer row for the grouped columns increase and get misaligned:

![image](https://user-images.githubusercontent.com/272543/60267608-9a33c800-98b8-11e9-8612-d762c5704866.png)

Shortly after that the column widths of footer return back to normal asynchronously by themselves.

It seems that this might be related to the presence of the first `rownum` frozen column. If I remove `frozen: true` setting on that column, this side effect disappears, and the column widths begin to work properly.

**Tabulator Info**
Version: 4.2.7

```
equity_table = new Tabulator("#equity-table", {
    height:              "65%",
    persistentLayout:    true,
    persistentSort:      true,
    persistentID:        "equity-table-layout",
    persistenceMode:     "local",
    selectable:          true,
    selectableRangeMode: "click",
    layout:              "fitData",   //fit columns to width of table
    tooltips:            false,       //show tool tips on cells
    initialSort: [                    // set the initial sort order of the data
      {column:"drawdown", dir:"desc"},
    ],
    rowFormatter: function(row) {
      var data = row.getData();
      var el   = row.getElement();
      if (data.mgn_lev <= 2.0)
        el.style.color = "#CEE9FB";
      else if (Date.now() - data.ts_ago > 15000)
        el.style.color = "#DECBFA";

      el.style.backgroundColor = data.profit == 0 ? "#A3A9AD"
                               : data.profit <  0 ? "#CE0000" : "#00A400";
    },
    groupBy: "group",
    columns: [           //define the table columns
      {title:"##",       field:"rownum",   formatter:"rownum", frozen:true, headerSort:false, responsive:0},
      {title:"Account Info", columns: [
        {title:"BrokAcct", field:"id",       responsive:0},
        {title:"Account",  field:"acct",     responsive:0},
        {title:"HostInst", field:"host_inst",responsive:0},
        {title:"Group",    field:"group",    responsive:0},
        {title:"Env",      field:"env",      responsive:0}
      ]},
      {title: "Equity and Profit", columns: [
        {title:"Equity",   field:"equity",   align:"right", sorter:"number", responsive:0, formatter:"money", formatterParams:{symbol: "$"}, bottomCalc:"sum", bottomCalcFormatter:"money", bottomCalcFormatterParams:{precision:2, symbol:"$"}},
        {title:"Balance",  field:"balance",  align:"right", sorter:"number", responsive:0, formatter:"money", formatterParams:{symbol: "$"}, bottomCalc:"sum", bottomCalcFormatter:"money", bottomCalcFormatterParams:{precision:2, symbol:"$"}},
        {title:"FreeMgn",  field:"free_mgn", align:"right", sorter:"number", responsive:0, formatter:"money", formatterParams:{symbol: "$"}, bottomCalc:"sum", bottomCalcFormatter:"money", bottomCalcFormatterParams:{precision:2, symbol:"$"}},
        {title:"Profit",   field:"profit",   align:"right", sorter:"number", responsive:0, formatter:"money", formatterParams:{symbol: "$"}, bottomCalc:"sum", bottomCalcFormatter:"money", bottomCalcFormatterParams:{precision:2, symbol:"$"}},
      ]},
      {title: "Risk", columns: [
        {title:"DDown%",   field:"drawdown", align:"right", sorter:"number", responsive:0, formatter:"money", formatterParams:{symbol: ""}},
        {title:"MgnLev",   field:"mgn_lev",  align:"right", sorter:"number", responsive:0, formatter:"money", formatterParams:{symbol: "", precision:1}},
      ]},
      {title: "Orders and Lots", columns: [
        {title:"OpenOrds", field:"ords_open",align:"right", headerSort:false,responsive:0},
        {title:"PendOrds", field:"ords_pend",align:"right", headerSort:false,responsive:0},
        {title:"MissOrds", field:"ords_miss",align:"right", headerSort:false,responsive:0},
        {title:"OpenLots", field:"lots_open",align:"right", headerSort:false,responsive:0, formatter:"money", formatterParams:{symbol: "", precision:2}},
        {title:"PendLots", field:"lots_pend",align:"right", headerSort:false,responsive:0, formatter:"money", formatterParams:{symbol: "", precision:2}},
      ]},
      {title: "Timeouts", columns: [
        {title:"TCago",    field:"tc_ago",   align:"right", headerSort:false,responsive:0, formatter:elapsedTimeFormatter},
        {title:"TimeAgo",  field:"ts_ago",   align:"right", headerSort:false,responsive:0, formatter:elapsedTimeFormatter}
      ]}
    ],
  });
```

**Expected behavior**
The widths of footer columns shouldn't intermittently change and should stay constant.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Edge

**Comment by tentus** [comment]
I tried to replicate your issue without success, but I was having to guess at a number of aspects. Please fork this fiddle so that it illustrates the bug:
https://jsfiddle.net/p45cgdn9/

**Comment by saleyn** [comment]
I managed to reproduce the effect here: https://jsfiddle.net/saleyn/a6hyxe24/15/

**Comment by tentus** [comment]
Ah, thanks, I see your issue now. I think that the problem is that you're replacing the data at a different rate than you're redrawing: if you add `equity_table.redraw()` to the tail end of your `replace()` function the jitter goes away, at least for me. So I'd say just merge the redraw loop into the replace loop and call it good.

WRT the arrow color: you're looking for the `border-top-color` of the `.tabulator-arrow` class. For the footer look into the `.tabulator-calcs-bottom` class.

**Comment by saleyn** [comment]
Thank you, your suggested workaround seems like it solves the redrawing problem.

Regarding the other two questions though, I added:
```css
#equity-table .tabulator-tableHolder .tabulator-arrow {
  border-top-color:#111;
}

#equity-table .tabulator-tableHolder .tabulator-table .tabulator-row .tabulator-calcs .tabulator-calcs-bottom{
  color:#AAA;
}
```
But the arrow image doesn't seem right when the group is collapsed (see: https://jsfiddle.net/saleyn/a6hyxe24/30/).  Adding `border-left-color` for the arrow to be displayed in the collapsed mode renders the arrow to look incorrect.  Maybe there's another way to set the color of all arrows in the table?

The `.tabulator-calcs-bottom` doesn't seem to achieve the desired effect either.

**Comment by saleyn** [comment]
Is the `redraw(true)` the right method to call if there are some calculated columns with implicitly changing values (e.g. elapsed time since record's last update timestamp) that are needed to be re-displayed?  Or possibly there's another method to call that I am not aware of (something like "invalidate") on a cell so that the `Tabulator` would figure out what to repaint?

**Comment by tentus** [comment]
It kinda sounds like what you really want is the `reactiveData` property. http://tabulator.info/docs/4.2/reactivity

Here's a quick example of it in use with a bottom calc: https://jsfiddle.net/wrxukms2/1/

**Comment by saleyn** [comment]
Thank you, yes, that's it!  Do you have any hints on the other two questions listed a couple of posts above?

**Comment by saleyn** [comment]
I figured out how to color the sort column arrows https://jsfiddle.net/saleyn/a6hyxe24/73/, but I am still unclear about how to color group row arrows so that they would keep the color when the group is collapsed/expanded.

**Comment by saleyn** [comment]
With help of stackoverflow this problem was answered:
https://jsfiddle.net/saleyn/a6hyxe24/91/
