### ISSUE TITLE
Sample code using tabulator with Typescript+Vue.js

### ISSUE THREAD

**Issue by fcappi** [olifolkerd/tabulator#2181]
Hey guys,

Do you have any sample code showing how to use Tabulator with Typescript+Vue.js?

**Comment by tentus** [comment]
The only official example I'm aware of for Vue is http://tabulator.info/docs/4.2/frameworks#vue

It's probably worth checking out https://vue-tabulator.netlify.com/, which was mentioned in https://github.com/olifolkerd/tabulator/issues/1507 a while back.
