### ISSUE TITLE
Wrap css for headers not sufficient

### ISSUE THREAD

**Issue by joshkpeterson** [olifolkerd/tabulator#2182]
I'm using version 4.2.

In the docs at http://tabulator.info/docs/4.2/layout it gives some nowrap CSS if you don't want ellipses on the headers if the column width gets to small.

`.tabulator .tabulator-header .tabulator-col .tabulator-col-content .tabulator-col-title {
    white-space: normal;
}`

I'm using layout:"fitColumns" and when I use this css, the headers go to two lines but there's a height css being set on the element by the library that keeps them at the height necessary for one line.

When the default layout option is used, the row itself breaks to two lines.

Am I missing something? Currently going to override the css and set a height that's always tall enough for two lines, but this isn't optimal and I'm guessing there would be some cases eg if filters were used where this might break things.

Thanks!

**Comment by olifolkerd** [comment]
Hey @joshkpeterson 

The height being set on the cells, is set after the CSS layout and is used for other render perpouses, it will not restrict the height of the cell to any shorter than the content has allowed.

have a look at #988 for more info.

Cheers

Oli :)

**Comment by AndyFilin** [comment]
Hi @olifolkerd 
Thank you for the great tool. I seem to face a similar issue - when I enable header wrapping through css, content height is bigger than cell height, and only first line is shown.
[Here](https://jsfiddle.net/3tfwrjqx/) is a simple fiddle to reproduce it.
Maybe I am doing something wrong?
Thanks!

**Comment by olifolkerd** [comment]
@AndyFilin  If you set a width on your columns this will work

Cheers

Oli  :)
