### ISSUE TITLE
Problem with the updating labels that are based on specific column values after filtering the table

### ISSUE THREAD

**Issue by Projo94** [olifolkerd/tabulator#2184]
Hello everyone.

I have the question about the tabulator. Moreover, I have a column from which I make some calculation, so I made calculate function. I had three json files stored locally on my machine, from which I am loading data into my table. Also I have dateFilter enabled for filtering date column in my table(it is used for range of date I need). At the first time when I load my page, the labels are updating regularly. The problem is appearing when I filter my table, but my labels are not updating(they should be dynamic, not static). 
My code is available on my github repository https://github.com/Projo94/gittab

**Comment by Projo94** [comment]
available video to show you an issue https://www.youtube.com/watch?v=rItczpbiFoc&feature=youtu.be

**Comment by olifolkerd** [comment]
Hey @Projo94

Thanks for making such a detailed video, but im afraid it is hard to diagnose a specific issue without a JS Fiddle to play with.

As a suggestion if you are trying to get tabulator to update some values outside of the table, you will need to make sure you are using the appropriate [Callbacks](http://tabulator.info/docs/4.2/callbacks) that will get triggered when the data updates.

Cheers

Oli :)
