### ISSUE TITLE
Scrolling Performance

### ISSUE THREAD

**Issue by rob196** [olifolkerd/tabulator#2185]
Hi Oli

Great work on Tabulator, best table library I have ever used by far

**Describe the bug**
Scrolling (especially large datasets) is laggy/jumpy.
Viewing the Dev Tools, I see there is a lot of violations "[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>" which I believe is causing the performance issues.

***NOTE:***
Only gives these warnings on touchstart and touchmove from what I can see.

**Tabulator Info**
- Which version of Tabulator are you using? - 4.2.7
- Post a copy of your construct object if possible so we can see how your table is setup

**Working Example**
 - Used a base provided by @dasboe in https://github.com/olifolkerd/tabulator/issues/1437
https://jsfiddle.net/rob196/0t1hacfu/55/

**To Reproduce**
1. Open Chrome Dev Tools
2. Browse to "https://jsfiddle.net/rob196/0t1hacfu/55/"
3. Scroll the table, notice the Violation count increase and the scrolling is quite slow

**Expected behavior**
Smoother scrolling

**Screenshots**
 - Initial Load:
![image](https://user-images.githubusercontent.com/20188626/60430464-a9d74780-9bfd-11e9-89a2-3d5ff221d5fe.png)

 - After quick scroll of mouse wheel
![image](https://user-images.githubusercontent.com/20188626/60430491-ba87bd80-9bfd-11e9-9ab9-dfd1211c6018.png)

- Expanded
![image](https://user-images.githubusercontent.com/20188626/60430666-2538f900-9bfe-11e9-8ee2-e7c96818319a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: GoogleChrome
 - Version: 75.0.3770.100 (Official Build) (64-bit)

**Additional context**
 - Passive option to event listeners may address the issue/drastically speed up the performance (making changes to the event listeners locally to tabulator.js helped in my case a lot)
https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md#solution-the-passive-option
 - Please take a look at the Feature Detection part as well

**Comment by olifolkerd** [comment]
Hey @rob196 

Thanks for your kind words, High Praise Indeed!!!

I dont get any violation warnings in my dev tools, what options do you have enabled in the dev tools to see that.

I had a cursory look at using passive event listeners in the past and think there was a reason i didnt use them in the end, but if im honest i cant remember what it was lol, so i will definitely take another look.

Cheers

Oli :)

**Comment by rob196** [comment]
Hi Oli

Sorry should have made it clearer its under verbose not warning
 - i.e. either use the Console sidebar or Select All levels (or at least verbose)

![image](https://user-images.githubusercontent.com/20188626/61409568-d02a0200-a8e2-11e9-8da6-5859f2afad8f.png)


Thanks
Rob

**Comment by olifolkerd** [comment]
Ooooooh, GOOOOD SPOT, i had verbose turned off (silly me)!!!!!!

Will totally look into adding that in for the 4.3 release this weekend.

Cheers

Oli :)

**Comment by takuy** [comment]
Oli, do you think this is related to my experiences in #2074? Really looking forward to 4.3 either way. :)

**Comment by olifolkerd** [comment]
Hey @rob196 

I have fixed the passive event listener issues in a commit to the 4.3 branch which i will release tomorrow.

Thanks for the headsup.

Cheers

Oli :)
