### ISSUE TITLE
Selecting "headerFilterPlaceholder" should reset Header filter 

### ISSUE THREAD

**Issue by WolfgangDpunkt** [olifolkerd/tabulator#2186]
I love the **select headerFilter** with the parameter **values: true.**
This is very handy if there are many entries. What's missing is an easy way for the user to reset the filter, respectively an empty option, to show all entries unfiltered.
It would be logical if the **headerFilterPlaceholder** could appear at the top of the selection list and could be selected to display all entries.

Pretty much the same thing is[ requested here](https://stackoverflow.com/questions/55088938/reset-of-tabulator-header-filter-by-selection-a-placeholder-value), so I think it would be useful for a lot of people. 
Thank you very much!

**Comment by tentus** [comment]
Related: https://github.com/olifolkerd/tabulator/issues/2160
