### ISSUE TITLE
Uncaught TypeError: Cannot read property 'slice' of undefined (dataTree)

### ISSUE THREAD

**Issue by hsnprojects** [olifolkerd/tabulator#2187]
tabulator version 4.2.7

[tree-demo.html.txt](https://github.com/olifolkerd/tabulator/files/3357095/tree-demo.html.txt)

Running the attached dataTree demo (from the Example section) shows no tree in the browser, and there is an error in the console.

![image](https://user-images.githubusercontent.com/52365149/60630571-5b25db00-9dc0-11e9-864d-89e788533de0.png)

**Comment by tentus** [comment]
You use the data before you define it. See fixed example below:
https://jsfiddle.net/6r9wqx4u/

**Comment by hsnprojects** [comment]
Thanks for explaining this! I should have looked at the code more closely before complaining :-)
This is not a bug!
