### ISSUE TITLE
selection not shown

### ISSUE THREAD

**Issue by lcaouen** [olifolkerd/tabulator#2189]
**Describe the bug**
when selecting a row by code (dataTableClusters.selectRow(e.target.id);)  in a multiple page tabulator, the selection doesn't change the page or scroll down if there is a scroll. By the way, the previous selection stay, we have to use the deselectRow()

**Tabulator Info**
- Tabulator 4.2.7
- Here is my tabulator intialisation:
`		dataTableClusters = new Tabulator("#table-clusters", {
			layout: "fitColumns", //fit columns to width of table
			//responsiveLayout: "hide", //hide columns that dont fit on the table
			tooltips: true, //show tool tips on cells
			pagination: "local", //paginate the data
			paginationSize: 7, //allow 7 rows per page of data
			movableColumns: true, //allow column order to be changed
			resizableRows: true, //allow row order to be changed
			selectableRollingSelection:false,
			selectable: 1,
			height: "380px",
			columns: columns,
			rowClick: (e, row) => {
				let points = row.getData().points;
				let coords = row.getData().coords;
				let id = row.getData().id;
				showPoints(points, id);
				map.fitBounds(coords);
			}
		});
`

**To Reproduce**
dataTableClusters.selectRow(e.target.id);

**Comment by tentus** [comment]
You haven't provided enough to replicate the issue. Here, I've started a fiddle for it, please fill it out until it shows your bug: https://jsfiddle.net/rwnk0yx2/

**Comment by lcaouen** [comment]
I've updated the jsfiddle.

If you click on a polygon on the map, a line should be selected in the tabulator beacause of this code:
```
	polygon.on('click', e => {
		dataTableClusters.deselectRow();
		dataTableClusters.selectRow(e.target.id);
	});

```

However, the tabulator always stays on the first tab so we don't see the selection and if the selection is the last one of the first tab, it doesn't scroll.

**Comment by tentus** [comment]
You, uh, didn't share the link. I can't see the updates you made.

**Comment by lcaouen** [comment]
Sorry, here is the link : https://jsfiddle.net/stdxheL8/

**Comment by tentus** [comment]
I think your issue is stemming from the pagination. Give this a spin:
```
	polygon.on("click", e => {
		dataTablepolygons.deselectRow();
		let row = dataTablepolygons.getRow(e.target.id);
		row.pageTo();
		row.scrollTo();
		row.select();
	});
```

I'm sure there's some tweaking you probably will want to do, for a better UX, but that should illustrate the idea: get to the right page, scroll to where you want to be, then select the row.

**Comment by lcaouen** [comment]
pageTo works but not the scrollTo.
For instance with this  polygon there is no scrolling : 2de20f7f-d6df-4f80-aff1-b70bf60e6155

**Comment by tentus** [comment]
Like I said, you'll want to tweak the code I provided, because the UX isn't perfect. In the case of that poly, perhaps the scrollTo and pageTo are firing out of sequence, so experiment with the Promises the methods return to see what works best.

**Comment by olifolkerd** [comment]
Hey @lcaouen 

This is the correct behaviour for Tabulator, selecting the row programatically only selects it, it dosnt bring it into view. if that is your desired result you will need change the page yourself.

Cheers

Oli :)
