### ISSUE TITLE
Disabiling selection toggle

### ISSUE THREAD

**Issue by leonardorame** [olifolkerd/tabulator#219]
Hi again Oli, when a row is selected `selectable: true` and I click on it it becomes selected, but when I click on an already selected it is deselected.

Is there a way to keep a row selected even when it's clicked again?. I mean, only de-select when I click on another row.

**Comment by olifolkerd** [comment]
Hey,

If you set the ***selectable*** property to a number then it will allow a maximum number of rows to be selected then deselect rows when the next one is clicked. to enable only one row at a time you can do the following:

```js
$("#example-table").tabulator({
	selectable:1,
});
```

Let me know if that helps,

Cheers

Oli

**Comment by leonardorame** [comment]
Mmm, no, sadly it doesn't do what I expect.

Let me explain my setup a little more.

I have many columns, but one of them has an onClick event defined. If I click on any other cell, the row gets selected, but if I click on the one with the onClick event, the row is unselected.

I think the problem is not related to the onClick, but to the fact that if I click again on the same row (on any column) the row is unselected. What I want is once the row is selected, keep selected until the user selects another row.

**Comment by olifolkerd** [comment]
In that case we can use some CSS trickery to help you out. add this to your CSS anywhere you like:
```css
.tabulator-row.tabulator-selected{
    pointer-events:none;
}
```

This will disable mouse actions on selected rows.

Cheers

Oli
