### ISSUE TITLE
Issue with boolean editor (tickCross formatter) on Safari (Web and iOS)

### ISSUE THREAD

**Issue by dieg0m** [olifolkerd/tabulator#2191]
Great job with this library, thank you!

When utilizing the TickCross formatter to modify boolean values, it works fine on most web browsers, but does not work on Safari both on iOs or Web (you cannot toggle the value). You can reproduce using the example from the documentation: http://tabulator.info/docs/4.2/edit

Tabulator version 4.2.3
Smartphone: iOS 12.1.3
Browser: Safari

On the Web: Safari version 11.1 9 (macOS 10.12.6)

**Comment by tentus** [comment]
Can confirm on Safari 12.1.1 on macOS 10.13.6.

**Comment by dieg0m** [comment]
Hi @tentus - agreed, same issue, looks like I might have not used the right keywords on my search.
I'll close this one. Thanks.
