### ISSUE TITLE
Get original position of row after move

### ISSUE THREAD

**Issue by digitalpenguin** [olifolkerd/tabulator#2192]
Disclaimer: Sorry if I've missed something, I'm very new to the wonderful tabulator :)

**Is your feature request related to a problem? Please describe.**
I'd like to save row positions to my database whenever they change. I understand I can use `row.getPosition();` to get the new position but I can't find a way in the docs to get the row's original position.

**Describe the solution you'd like**
It would be great to get a `row.getOriginalPosition()` function too. Then I could send both to the server and do the calculation there before reloading the table data.

**Comment by digitalpenguin** [comment]
Nevermind, I was able to get around this by providing a "position" column to use as the original value. Closing! :)

**Comment by ra-dave** [comment]
This would still be a useful feature.  I'm running into this situation right now. Any workaround is a considerable hack, especially if aren't reloading the entire table to reset your indices after a move.
