### ISSUE TITLE
csv, excel pdf downloads white screen in 4.2 with 1 million records

### ISSUE THREAD

**Issue by ryhill** [olifolkerd/tabulator#2194]
Tabulator is able to display 1 million records and when trying to download to excel or csv or pdf, system crashes. Its white screen

**CSV**:
```
MFDtable.download("csv",mfd_report.csv",{bom:true})
```
**Excel**:
```
MFDtable.download("xlsx", report_category + "_mfd_report.xlsx", 
{ sheetName: report_category })
```
**PDF**:
```
MFDtable.download("pdf",report_category + "_mfd_report.pdf", {
            orientation: "landscape",
            title: report_header,
            autoTable:{ //advanced table styling
                theme:'striped',
                styles: {
                    fontSize: 8,
                    cellPadding:5,
                    //halign:'center'
                    //fillColor: [100, 255, 255]
                },
                columnStyles: {
                    //id: {fillColor: 255}
                },
                rowGroupStyles: {
                    // id: {fillColor: 60},
                    // fillColor: [255, 69, 0]
                },
                margin: {top: 60},
            },
        });
```
When trying to generate 1 million records Tabulator is fine but download options crashes and produces white screen

![tabulator](https://user-images.githubusercontent.com/33457591/60763136-9e679e80-a08b-11e9-9787-79c590ea00fe.PNG)

**Comment by aklaver** [comment]
My guess is that if you look at the system logs you are crashing the memory. You have 1 million records loaded into the table and then you are loading them into memory(along with file specific objects) when building the file. The solution would seem to be to break the downloads into smaller sections.

**Comment by olifolkerd** [comment]
Hey @ryhill 

@aklaver it totally right there, that is a LOT of records, so mini yay that Tabulator could load them all in the first place :) but you are definitely reaching the memory capacity of the browser / blocking the DOM when you try and generate a file of that size.

Im afraid there isnt that much that can be done about that, i would recommend that if you are trying to process things on that scale that you do the file generation server side and download it to the browser after processing.

Cheers

Oli :)

**Comment by myFirmData** [comment]
Ok..Thanks for the inputs.

I am working on a desktop application using electron. So I thought downloads should actually be supporting the downloads as Tabulator is perfectly working.

It gets failed while creating the blob with file contents in tabulator.js

Any options where we can stream to a file.

I am sorry to see this closed

**Comment by ryhill** [comment]
Ok..Thanks for the inputs.

I am working on a desktop application using electron. So I thought downloads should actually be supporting the downloads as Tabulator is perfectly working.

It gets failed while creating the blob with file contents in tabulator.js

Any options where we can stream to a file.

I am sorry to see this closed

**Comment by aklaver** [comment]
It does support downloads, it just runs into a resource limit. That is going to happen with anything. It failed on the blob because it was too big for the resources you had.  The downloads are supported by third party programs:
https://github.com/sheetjs/js-xlsx
https://github.com/MrRio/jsPDF/
https://github.com/simonbengtsson/jsPDF-AutoTable
You would need to look at their API's to see if streaming is even supported. At this point it is not via Tabulator.  Your choices are smaller downloads or as Oli said do it server side and then download.
