### ISSUE TITLE
Make "Role" configurable

### ISSUE THREAD

**Issue by JohannesBayerAlbert** [olifolkerd/tabulator#2196]
Hello,

we are currently evaluating Tabulator for the new UI-system for our organization and are very happy with it. Particularly the absence of jQuery makes it a valid candidate.
Unfortunatly the jaws-screenreader reads a table as 'grid'. But our visually handicapped users expect it to be called a 'table'. Is it be possible to make the role-attributes of the table, row and cell somehow configurable?

Regards
Johannes

**Comment by olifolkerd** [comment]
Hey @JohannesBayerAlbert 

According to the ARIA specification ***grid*** is the correct role for an interactive table, ***table*** should only be used for static non interactive tables.

If you wanted a quick work around you could use the ***tableBuilt*** callback to trigger a script to replace the role of the table element when it has initially rendered.

I hope that helps,

Cheers

Oli :)
