### ISSUE TITLE
Is Tabulator Asp Core available?

### ISSUE THREAD

**Issue by prince272** [olifolkerd/tabulator#2197]
Is there a framework for asp core?

**Comment by tentus** [comment]
I'm not aware of anyone working on that. Check out http://tabulator.info/docs/4.2/frameworks for documentation on tabulator working in some of the major JS frameworks .

**Comment by prince272** [comment]
ok. thanks!

**Comment by fasteddys** [comment]
Hello I am interested as well

**Comment by olifolkerd** [comment]
Tabulator is a front end JavaScript framework designed to work in browser.

It will make standard ajax requests back to any sever you like.

It is up to you to make sure you respond to the requests with the correctly formatted JSON data.

Cheers

Oli
