### ISSUE TITLE
Is Tabulator fully supported ReactJS?

### ISSUE THREAD

**Issue by phanvinh0526** [olifolkerd/tabulator#2198]
I am writing to ask whether Tabulator is fully supported ReactJS?. I would like to use Tabulator for commercial product, is there anything i should consider such as fully customise style for all table elements?

**Comment by tentus** [comment]
As far as I know you should have no problems compiling the css to fit your needs. Here's a link to the React section of the docs: http://tabulator.info/docs/4.2/frameworks#react
