### ISSUE TITLE
Demo for adding a checkbox column

### ISSUE THREAD

**Issue by prince272** [olifolkerd/tabulator#2199]
Take a look at this https://www.gyrocode.com/articles/jquery-datatables-how-to-add-a-checkbox-column/

**Comment by prince272** [comment]
I mean row selection using checkboxes.

**Comment by tentus** [comment]
I think you're asking for an example of row selection but with visible checkboxes.

Here you go: https://jsfiddle.net/02npLza4/

**Comment by fingers10** [comment]
@prince272  check #1938
