### ISSUE TITLE
Title Head 

### ISSUE THREAD

**Issue by vmontal** [olifolkerd/tabulator#22]
is it possible to split the the title of a head column in two lines to avoid that the columun is too large or the a part of the head is hide.

**Comment by olifolkerd** [comment]
Are you after text wrapping in the header row? at the moment that isnt possible, but i can certainly add it this weekend.

**Comment by olifolkerd** [comment]
Good news, this is now possible!

If you download the latest version of tabulator it is now really easy to do this. Simply tweak the CSS for the ***tabulator-col*** and ***tabulator-col-row-handle*** as follows:
```css
.tabulator-col,.tabulator-col-row-handle{
     white-space: normal;
}
```

You will need to overwrite the existing *white-space:wrap;* value in the provided ***tabulator.css*** file.

**Comment by olifolkerd** [comment]
A working example of a multi-line header is now visible in the Theming section of examples page on the Tabulator site.

[Click here to see it in action](http://olifolkerd.github.io/tabulator/examples/#theming)
