### ISSUE TITLE
pagination problem

### ISSUE THREAD

**Issue by lalwende00** [olifolkerd/tabulator#220]
Hello
i have a little problem with the pagination
here is a part of my code 

`$("#commentTable").click(function () {
            $("#comment-admin").tabulator({

                height: "500px",
                fitColumns: true,
                pagination: "local",
                paginationSize: 5,
                selectable: 1,

                columns: [{
                        title: "N°",
                        formatter: autoNumFormatter,
                        width: 40
                    }, //incrementing row number   
                    {
                        title: "Asset Id",
                        field: "assetId",
                        width: 100,
                        sortable: true
                    },
                    {
                        title: "Utilisateur",
                        field: "assetUser",
                        width: 300,
                        sorter: "string"
                    },
                    {
                        title: "Commentaire",
                        field: "comment",
                        width: 977,
                        editable: true
                    }
                ], $("#comment-admin").tabulator("setData", cms);

in my other tab pagination is ok but not in this one 
i put to 5 the paginationSize for the example 
i have more than 5 comments in my table but the pagination doesn't appear below

`![Image of pagination](http://img4.hostingpics.net/pics/368733paginationProblem.png)
 Thank you for your help :)
Have a nice day.

**Comment by olifolkerd** [comment]
Hey,

Thanks for getting in touch.

it looks like there was a bug with pagination footers in pages containing more than one paginated table.

I have just pushed a fix for this.

Let me know if that helps

Cheers

Oli

**Comment by lalwende00** [comment]
Great it's ok thank you very much :)
Have a nice day.
