### ISSUE TITLE
Closed editor mode after formatting

### ISSUE THREAD

**Issue by meteerogl** [olifolkerd/tabulator#2200]
`{title:"Total Amount",field:"Total Amount",sorter:"string",formatter:priceFormatter,editor:true},`
I want to format my data after showing and I want to do changes on cells. But after formatter , editor mode is closing I want to use formatter and editor mode(true). How can do this

**Comment by meteerogl** [comment]
I solved, I changed editor:"input. But ı have an other error. Before formatting table data is not changing. When ı clicked some cell, displaying old data. I want to control and change data after installation. How can I  do.

**Comment by tentus** [comment]
Probably your best bet is to make a [custom editor](http://tabulator.info/docs/4.2/edit#edit-custom). Alternatively, you could use the [Data Loaded](http://tabulator.info/docs/4.2/callbacks#data) callback to actually modify the underlying data, but this will likely cause you some headaches down the road.

**Comment by meteerogl** [comment]
Actually I solved also, I am using mutator. This solution solved my problem. Thanks
