### ISSUE TITLE
Tab to Enter i.e. Jump to next field in editing by pressing Enter

### ISSUE THREAD

**Issue by 8483** [olifolkerd/tabulator#2202]
This is a UX feature where fields can be traversed by pressing Enter as well. Many people are not used to using Tab for selecting the next input.

**Comment by olifolkerd** [comment]
Hey @8483 

You could set this up on your table using the built in [Keybindings system](http://tabulator.info/docs/4.2/keybindings#custom)

Cheers

Oli :)

**Comment by 8483** [comment]
I am unable to get it working for the "enter" key. It does work for other keys, so I guess "enter" is reserved for submitting the edited data? 

Also, I can't get the new row on tab to work.

https://jsbin.com/suvibapili/edit?js,console,output
 
```javascript
let data = [
  {name: "John", surname: "Smith"},
  {name: "Alice", surname: "Chains"},
  {name: "Bob", surname: "Ross"}
]

let table = new Tabulator("#example-table", {
  tabEndNewRow: true,
  keybindings:{
    "navNext" : "13", // // enter keycode
  },
  height:500, 
  data: data,
  layout:"fitColumns",
  columns:[
    {title:"Name", field:"name", editor:"input"},
    {title:"Surname", field:"surname", editor:"input"},
  ],
  rowClick:function(e, row){
    console.log("editing")
    console.log(row.getData());
  },
  dataEdited:function(data){
    console.log(data)
  },
});
```

**Comment by 8483** [comment]
@olifolkerd Anything on this issue? Can't use the enter key.
