### ISSUE TITLE
Datepicker

### ISSUE THREAD

**Issue by 8483** [olifolkerd/tabulator#2203]
It would be awesome if a proper datepicker is used, rather than the default browser component.  

Here is a simple vanilla JS datepicker I made that can be implemented, rather than relying on jQuery.  

I will try to make it a pull request.

**Comment by olifolkerd** [comment]
Hey @8483 

Thanks for getting in touch,

I think a nicer datepicker would be lovely, but im afraid it is not so simple.

Tabulator is used all over the world, which means it needs to be able to cope with any date format used anywhere in the world. Not all countries use the western Gregorian Calendar, so any bespoke calendar picker would also need to be handle the other calendar systems used out there.

If your picker can do this then by all means submit a post request, i would love to see it. But im afraid i wont be able to include it in the core library if it is dependent on any other library.

Cheers

Oli :)

**Comment by jgorene** [comment]
Hey Oli!

First, thanks for your awesome "interactive JavaScript table library" ;)

Although this issue closed, 
I'd like to show you a method I use that works fine (for me) with Materialize.js (also included in the tabulator's styles)
I think a bit of code (shortened) will be better to show it !
Just a track if there is one and if it can be used for others anyway.

```
<!-- html (class Materialize) -->
<div>
    <input id="dateInput" type="text" class="datepicker hide">
</div>
```
```
// js
// must initialize before (better to see doc on materializecss.com;)
// options (see also doc for i18n internationalization options and other tips and tricks)

var dateInput = document.getElementById('dateInput');
var pickersWeek = M.Datepicker.init(document.getElementById('dateInput'), options);

// Create Date Editor
var dateEditor = function(cell, onRendered, success, cancel) {
  // cell, onRendered(), success(), cancel() // PM
  
  var datePickers = M.Datepicker.getInstance(document.getElementById('dateInput'));
  var editor = document.createElement("input");
  
  cell.getElement().onclick = function(e) {
    if (!cell.getValue()) return;
    datePickers.open();
    document.getElementById('dateWeek').addEventListener('change', function(e) {
      console.log(this.value);
      (this.value) ? success(this.value) : cancel();
    });
    e.stopPropagation();
  }
  
  return editor;
};

// in options table 
...
columns: [
{ title: "Date", field: "Date",  editor: dateEditor }
]
...
```
