### ISSUE TITLE
Cannot reformat rows that are children of other rows

### ISSUE THREAD

**Issue by AlphaTeal** [olifolkerd/tabulator#2204]
**Describe the bug**
Calling row.reformat() on a row that is a child of another row throws an uncaught `TypeError: i.branchEl.parentNode is null` (or similar depending on browser)

**Tabulator Info**
Found in v4.2.1 and v4.2.7
Here is a simple representative table constructor used in the Working Example below:
```javascript
const myTable = new Tabulator('#table', {
  dataTree: true,
  reactiveData: true,
  height: '100%',
  data: someTableData,
  layout: 'fitColumns',
  columns: [{
      title: 'Quiz',
      field: 'name',
    },
    {
      title: 'Answer Key',
      field: 'answer',
    },
    {
      title: 'Due date',
      field: 'date',
    },
  ],
});
```

**Working Example**
[Here is a link to a JSFiddle that concisely demonstrates the issue](https://jsfiddle.net/AlphaTeal/xfrotLku/64)

**To Reproduce**
1. Expand both tree parents, especially "Quiz #&#8203;2"
2. Click the button above the table to dynamically update the data
3. Check the console for error, and note how the "L" symbol in the row that marks that row as a child has disappeared

**Expected behavior**
Using reactive data to manipulate the data on a table with a tree causes the tree-specific items to disappear, i.e. the button used to expand and collapse parents, as well as the "L" symbol used to mark children. Calling row.reformat() on the parent rows causes the button to reappear. I would expect calling row.reformat() on the child rows to cause the "L" symbol to reappear as well

**Screenshots**
I believe using the JSFiddle above would be more useful than screenshots

**Desktop (please complete the following information):**
 - OS: Ubuntu Bionic Beaver, Windows 10 Education 1809
 - Browser: Chrome & FireFox (Although the error message is slightly different for each of these browsers, I believe the error itself is the same)
 - Version: Chrome 75, FireFox 67

**Smartphone (please complete the following information):**
Untested

**Additional context**
There are many different ways to dynamically update data in a Tabulator table, but reactive data is the best for my particular use case. I have yet to find a workaround for this issue.

**Comment by tentus** [comment]
Can confirm the issue. Haven't had any luck with finding a workaround yet, will take a second look soon as I can.

**Comment by AlphaTeal** [comment]
Upon further investigation, it appears that the error only happens when you try to reformat a row that is a child of another row **after** you change the data in the dataTreeElementColumn of that row. Changing the data in other columns, then calling reformat on that row doesn't trigger the error.

**Comment by olifolkerd** [comment]
Hey @AlphaTeal 

This is because the child rows are true rows as such, they are a cunning trick that Tabulator uses to the display the data.

I will list this as a bug, and look to fix it in one of the up coming patch releases.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @AlphaTeal 

If your are updating row data you should really be calling the ***update*** function on the row and passing in the updated data, the reason for this is that using the reformat approach will only affect row formatting, it wont affect the sort or filter of the table or trigger any of the functions that tabulator needs to use to update the table based on row data being changed.

The reformat function is really only meant to be used to handle situations in which you are using custom formatters that have content that loads asynchronously like images etc.

In your example you also have rows sharing the same ID field, this is used if you are looking rows up by index so the values should be unique to allow for correct operation.

There was however a bug with the update function where it was only detecting changes on children not on the tree element containing field. I have pushed a fix for that issue to the master branch and will include it in todays patch release.

Cheers

Oli
