### ISSUE TITLE
Built-in input form

### ISSUE THREAD

**Issue by 8483** [olifolkerd/tabulator#2205]
What do you think about a built-in form for editing data other than the editable fields?

E.g. When a row is clicked, the inputs are populated for editing.

Here is a [working prototype](https://jsbin.com/yabegevada/edit?html,js,console,output) I made.

**Comment by olifolkerd** [comment]
Hey @8483 

Thanks for getting in touch.

Im glad to hear you have been experimenting with Tabulator, it is always great to see the different uses people come up with for it,

In this instance im afraid that is not something i would be looking to include in the library. as a general rule, the Tabulator library will not touch anything outside of the Tabulator contain element, to do so would force design considerations upon the rest of a developers site.

Most developers will have frameworks or libraries they are using for their forms. and i would not want to interfere with this.

Thanks for your idea though

Cheers

Oli :)
