### ISSUE TITLE
save as pdf shows "All Files" in the dialog 

### ISSUE THREAD

**Issue by pkirankmr** [olifolkerd/tabulator#2206]
First of all, Thanks for the awesome library **Oli**

**Describe the bug**
In the save as dialog, the file type shows "All Files" even when we know the blob is pdf or csv or excel file types.

Please see the image

**Tabulator Info**
Tabulator version 4.2

![save](https://user-images.githubusercontent.com/19264265/61102776-f12ac700-a48c-11e9-805f-d9e6ac0e7a90.png)

**Comment by tentus** [comment]
I don't believe this is in the scope of what javascript can dictate, that's an OS-level UI.

**Comment by olifolkerd** [comment]
Hey @pkirankmr 

@tentus is right, this is the browsers choice, it is outside the scope of Tabulator. Imporrantly that will make no difference to the file type unless someone actually changes the file extension manually

Cheers

Oli :)
