### ISSUE TITLE
Is it possible to apply mask on tabulator column like bank account number using jquery features.

### ISSUE THREAD

**Issue by Muralee99** [olifolkerd/tabulator#2207]
Hello Oli,

I am trying to apply jquery mask feature for the account number in EMBER JS framework.

My code as follows.

var textmask = function(cell, formatterParams){
            var input = $("<input></input>");
            input.attr("data-inputmask","'mask': '9999-9999-9999-9999'"); 
            $('[data-inputmask]').inputmask();           
            //cell.value = input.value;
            return input;
        }
        $('[data-inputmask]').inputmask();

Applying mask at column level.
formatter:textmask

I am getting below warning message in browser console 
Format Error - Formatter has returned a type of object, the only valid formatter object return is an instance of Node, the formatter returned: jQuery.fn.init(1)

But I am not able to see the mask in tabulator.

Is there any possibility to implement this feature using custom formatter.
I have tried it didn't work out.

Thanks and regards.
Murali.

**Comment by tentus** [comment]
It sounds like you're returning a jquery object where you should return a node object. You can probably fix your issue by using the [get() function](https://api.jquery.com/get/). Can't be sure of that without seeing more of your setup (a jsfiddle would help).
