### ISSUE TITLE
Unable to create more than one tabulator grid in single page(component).

### ISSUE THREAD

**Issue by Muralee99** [olifolkerd/tabulator#2209]
Hello Oli,
I have a requirement to create 2 tabulator grids in same page, but I am unable to create due to the below issues. Could you please help me to move forward.

1. Is tabulator restricted to create more than one grid in same webpage.
https://jsfiddle.net/Muralee1857/wnfeh0vd/

2. Tabulator constructor is not accepting other than #example-table this id.
const table = new Tabulator("#example-table", {
  height: 205,
  data: tabledata1, 
  layout: "fitColumns", 
  autoColumns: true
});

your help is highly appreciated.

Thank you,
Murali.

**Comment by aklaver** [comment]
Your fiddle is broken as <div id="example-table"></div> and const table = new Tabulator("#example-table1" ...  Tabulator cannot find a <div> with "#example1". You can have multiple tables as long as you have unique id for each.
