### ISSUE TITLE
Can align title field in pdf  to center

### ISSUE THREAD

**Issue by ryhill** [olifolkerd/tabulator#2210]
When downloading pdf with title, the title is always aligned to left. Cannot find options to align it center or right.

```
table.download("pdf", "data.pdf", {
    orientation:"portrait", //set page orientation to portrait
    title:"Dynamics Quotation Report", //add title to report
    jsPDF:{
        unit:"in", //set units to inches
    },
    autoTable:{ //advanced table styling
        styles: {
            fillColor: [100, 255, 255]
        },
        columnStyles: {
            id: {fillColor: 255}
        },
        margin: {top: 60},
    },
});
```
I did some digging, but wasn't able to resolve. any clue, pls share

**Comment by aklaver** [comment]
I don't see an easy path without writing new code. The alignment is set:
```614                 if(title){
615                         autoTableParams.addPageContent = function(data) {
616                                 doc.text(title, 40, 30);
617                         };
618                 }
```
FYI addPageContent() is now didDrawPage(), though addPageContent remains as an alias. The doc is a jsPDF object. So it is a matter of figuring out how to pass the alignment request down through either jsPDF or jsPDF-Autotable. Will have to think on this.

**Comment by aklaver** [comment]
Well this is turning into a trip down the rabbit hole. Somewhere I'm missing a key part of the interaction between jsPDF and jsPDF-Autotable. The default 'left' alignment is the only thing that works, everything else pushes the title further left. Seems I have more learning to do.

**Comment by olifolkerd** [comment]
Hey @ryhill  

I have added a new ***documentProcessing*** option to the download options object, you can pass a callback to this that gives you access to the document object to call any functions you like on:
```js
table.download("pdf", "test.pdf", {
	documentProcessing:function(doc){
		doc.text("SOME TEXT", 200, 30);
	}
});
```

It is currently on the 4.3 branch that will be released later today

Cheers

Oli :)

**Comment by ryhill** [comment]
autoTable:function(doc){
                    var pageWidth = doc.internal.pageSize.width || doc.internal.pageSize.getWidth();
                    var heads = "Report Header";
                    var u_line = heads.replace(/./g, '_');
                    doc.setTextColor(9, 149, 204);
                    doc.setFontSize(14);
                    doc.setFontType("bold");
                    doc.text(heads,pageWidth / 2, 25, 'center');
                    doc.text(u_line,pageWidth / 2, 30, 'center');
                },
