### ISSUE TITLE
Collapse/Uncollapse columns to *tabulator-resposive-collapse* area programmatically

### ISSUE THREAD

**Issue by giuliano-marinelli** [olifolkerd/tabulator#2211]
For forced collapsed columns (always hide in collapsed area) when using responsive layout i set minWidth to a high number, like 99999, and put the column at final of the list of columns.
This works when i set the a column that always be hide, but i can't collapse/uncollapse columns dynamicly and programmaticly and that the layout adjust to this.
Is there a possibly to make this or a workaround?

In other hand, it will be nice if there was a predefined option to show / hide columns with a button on headerTitle and on collapsed listed columns.

Thanks, Regards.

**Comment by olifolkerd** [comment]
you can use a [Column Header Formatter](http://tabulator.info/docs/4.2/format#format-column) to add any content you like to a column header, which in this case could include a button.

you could then call the ***show*** or ***hide*** function on the matching [Column Component](http://tabulator.info/docs/4.2/components#component-column)

Cheers

Oli :)

**Comment by giuliano-marinelli** [comment]
The problem is that the column hide() function don't put the column in *tabulator-responsive-collapse* area, instead it remove the column from the table (like it suppouse to do).
So i can't move the column from the header area to the responsive collapsed area.

Don't know if i explain correctly.

Cheers.

**Comment by hanh090** [comment]
@olifolkerd I have same concern with @giuliano-marinelli. In detail, I want to expand data programmatically, not auto. For example: I have 20 columns, I want to show 5 columns only, and the others will expand when I select a row.
 Already ask in stackoverflow
https://stackoverflow.com/questions/57283148/how-do-i-show-a-detailed-program-in-tabulator
