### ISSUE TITLE
Selectable doesn't work on React

### ISSUE THREAD

**Issue by behrouz-s** [olifolkerd/tabulator#2214]
**Describe the bug**
I use "react-tabulator", but "selectable" option doesn't work.

**Tabulator Info**
- react-tabulator 0.9.1
```
<ReactTabulator
  className={classes.table}
  data={data}
  columns={columns}
  tooltips={true}
  columnMinWidth={200}
  selectable="true"
  rowSelectionChanged={function(data, rows) {
    console.log(data);
  }}
/>
```

**Comment by behrouz-s** [comment]
I fixed it by adding "selectable" to "defaultOptions" in "ConfigUtils" file.

**Comment by olifolkerd** [comment]
Hey @behrouz-s 

If you are having issues with react-tabulator, please raise the issue on that repo first, it is likely a but in their wrapper.

Cheers

Oli :)
