### ISSUE TITLE
Autocomplete Editor: Hightlight the first ListItem (FullList/FilteredList)

### ISSUE THREAD

**Issue by fab987** [olifolkerd/tabulator#2216]
**Is your feature request related to a problem? Please describe.**
When using the Autocomplete Editor I find it a bit disturbing to use the arrow keys or the mouse to select an item from the list. I think it would be better, if the first item in the list is pre-selected and can be accpeted by pressing _enter_

**Describe the solution you'd like**
In the fillList-function [(link)](https://github.com/olifolkerd/tabulator/blob/309138f3023c0b27e09afe675df4d5b865974cd8/src/js/modules/edit.js#L1046) replace the line `setCurrentItem(false);` with `setCurrentItem(displayItems[0]);`

**Describe alternatives you've considered**
In my Code, i also implemented an editorParams-switch, so you can change the autocomplete highligt behavior via the column definitions 

`if (!current) {`
` if(editorParams.highlightFirst){`
`setCurrentItem(displayItems[0]);	`				
`} else {`
`setCurrentItem(false)`	
`}`
`}`

**Comment by tentus** [comment]
This would be inconsistent with default browser behavior, [jqueryui](https://jqueryui.com/autocomplete/#default), [Materialize](https://materializecss.com/autocomplete.html), [easyautocomplete](http://easyautocomplete.com/), etc etc, so I'd definitely recommend such a feature be an opt-in configuration as mentioned.

**Comment by p32602** [comment]
Wow, thanks :)

I kept thinking that this would be a great feature, but I had no idea it was that easy to implement. 

I agree with tentus, opt-in would be fine.

**Comment by olifolkerd** [comment]
Hey @fab987 

An interesting idea but i think i would take a different approach, i will a ***defaultEmptyValue*** property that lets you preselect a specific value in the list if the editor is triggered on a cell with an undefined value.

That way it will allow people to hint at the correct value for a cell.

Thanks for the suggestion

Oli :)

**Comment by olifolkerd** [comment]
Hey @KES777 

I have pushed this feature to the 4.4 branch that will be released later today.

There is now a ***defaultValue*** option on the editor to allow setting of the default value for undefined cells.

Cheers

Oli :)

**Comment by KES777** [comment]
@olifolkerd um... probably this is a message from different issue =)

**Comment by olifolkerd** [comment]
Nope, it was for this issue

**Comment by leif-freshx** [comment]
Hi,

The solution with defaultValue does not really work for dynamically created list of values.

I have a free text search function using the autocomplete editor so I do not know what value will be the "default"/"correct" value when setting up the column so I agree with the original post that it would be very useful to be able to set autoSelectFirstItem=true or something similar as an opt-in feature.

Alternatively, being able to set the defaultValue during the searchFunc executing would also be a working solution.

Best regards,
Leif

**Comment by leif-freshx** [comment]
> Hi,
> 
> The solution with defaultValue does not really work for dynamically created list of values.
> 
> I have a free text search function using the autocomplete editor so I do not know what value will be the "default"/"correct" value when setting up the column so I agree with the original post that it would be very useful to be able to set autoSelectFirstItem=true or something similar as an opt-in feature.
> 
> Alternatively, being able to set the defaultValue during the searchFunc executing would also be a working solution.
> 
> Best regards,
> Leif

Hi again,

I saw that another issue mentioned similar request and there it was mentioned that it will be addressed:
https://github.com/olifolkerd/tabulator/issues/2906

So, please disregard my comment in this thread.

Best regards and thanks for a great library,

Leif
