### ISSUE TITLE
Double Click selects text in three cells

### ISSUE THREAD

**Issue by fingers10** [olifolkerd/tabulator#2217]
**Describe the bug**
Double click in a cell selects text in three cells

**Tabulator Info**
- v4.2.7

**Working Example**
Please click on following to link to see demo. [Double Click Big](https://github.com/fingers10/Tabulator-Bugs/blob/master/Tabulator-DoubleClickSelectBug.gif)

**To Reproduce**
1. Double click in a cell
2. This bug happens

**Expected behavior**
only that cell text can be highlighted

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser : Chrome
 - Version 72.0.3626.121 (Official Build) (64-bit)

**Comment by olifolkerd** [comment]
Hey @fingers10 

This happens because the cells are inline blocks, so the browser is trying to read them as one line.

I have pushed a fix to the 4.3 branch that forces the selection to the cell on double click, it will be included in todays release.

Cheers

Oli :)
