### ISSUE TITLE
Tooltip getting displayed even after setting false for frozen column header

### ISSUE THREAD

**Issue by fingers10** [olifolkerd/tabulator#2218]
**Describe the bug**
I have enabled tooltips and header tooltips on table level and if I disable tooltip on particular column level tooltips are still getting displayed. This is not possible in Tabulator?

**Tabulator Info**
- version 4.2.7

**Working Example**
Please check on the fiddle link [Tooltip bug](https://jsfiddle.net/kdjo0sne/1/)

**To Reproduce**
1. set `tooltipsHeader: true` and `tooltips: true` on table level
2. set `tooltipsHeader: false` and `tooltips: false` on column level

**Expected behavior**
tool tip should be disabled for particular column

Thanks,
Abdul

**Comment by olifolkerd** [comment]
Hey @fingers10 

When setting it on the column the property is ***headerTooltip***,

Cheers

Oli :)

**Comment by fingers10** [comment]
@olifolkerd  I tried setting the `headerTooltip` to false at column but still it shows the tooltip. Here is the updated fiddle link [Tooltip Bug](https://jsfiddle.net/L4aqrhw6/)

Thanks,
Abdul

**Comment by olifolkerd** [comment]
Hey @fingers10 

your column definition should be:
```js
headerTooltip:false, tooltip:false
```
Notice it is ***tooltip*** not ***tooltips*** in the column definition

it works fine for me here

CVheers

Oli :)

**Comment by fingers10** [comment]
@olifolkerd  thanks. That works. But I wonder why there is no error logged in console when I typed `tooltips` instead of `tooltip`?

**Comment by olifolkerd** [comment]
because at the moment tabulator only cares about paramters it is looking for, it ignores any that arnt valid
