### ISSUE TITLE
Select editor not selecting any value in v4.2.7

### ISSUE THREAD

**Issue by aliramadan8** [olifolkerd/tabulator#2219]
using select Editor as below is not changing the value ,this happens after upgrading to v 4.2.7 ,there is no change in my code same as before ,do i need to do any changes to the code ?? 

         //Build Tabulator
          var schBatchDiscountRulesGrid = new Tabulator("#schBatchDiscountRulesGrid", {
              ajaxURL: "getschBatchDiscountRulesFilteredList",
              ajaxParams: { filterValue: getCoreid() }, //ajax parameters
          
            layout: "fitColumns",
            placeholder: "No Data Set",

            index: "id",
            columns: [
                { title: "@Localizer["DeleteRow"]", formatter: DeleteIcon, width: 40, align: "center", cellClick: function (e, cell) { schBatchDiscountRulesDelete(cell.getRow().getData().id); }, headerSort: false, tooltip: "@Localizer["DeleteSignleRow"]", visible: Editable },
              
                { id: "ID", title: "@Localizer["ID"]", field: "iD", headerToolTip: "@Localizer["IDtip"]", validator: "required", editor: "number", visible: false, sorter: "number", minWidth: 50, headerSort:false , editable: false },
                { id: "DiscountID", title: "@Localizer["DiscountID"]", field: "discountID", headerToolTip: "@Localizer["DiscountIDtip"]", editor: select2Editort, editorParams: { values: DiscountIDSelect }, formatter: "lookup", formatterParams: DiscountIDSelect, minWidth: 120, headerSort:false , editable: Editable },
                { id: "Percentage", title: "@Localizer["Percentage"]", field: "percentage", headerToolTip: "@Localizer["Percentagetip"]", editor: "number", sorter: "number", formatter: "money", formatterParams: { decimal: ".", thousand: ",", symbol: "", symbolAfter: "", precision: false, }, minWidth: 50, headerSort:false , editable: Editable },
            ],
          
        });
       //#endregion

the current behaviors , the value never changes 
![image](https://user-images.githubusercontent.com/24622815/61588034-815fbf00-aba5-11e9-89aa-57b2c50b6139.png)

 while using the old verison 
![image](https://user-images.githubusercontent.com/24622815/61588041-9c323380-aba5-11e9-9c59-6a75adf673ba.png)

**Comment by olifolkerd** [comment]
Hey @aliramadan8 

You appear to be using a custom select editor rather than the built in select editor so without seing how that is setup i would be unable to offer you advice.

We would also need to know which version of Tabulator you are upgrading from to know if there are any changes you need to make

Cheers

Oli :)

**Comment by aliramadan8** [comment]
Hi Oli , 
 my previous version is 4.1.4 ,and it was workings good , 

when i changed the editor to build in select it worked fine with no issues , 

but can you help with a sample to create custom editor for select 2 ,i use the below code 

    //{ title: "Select2", field: "lucky_no", align: "center", width: 300, editor: select2Editor , editorParams: { 
    values: InvoiceToCustomerSelect } },
    var select2Editort = function (cell, onRendered, success, cancel, editorParams) {

    //create input element to hold select
    var editor = document.createElement("select");
    PopulateSelect(editor, editorParams.values, true);

    onRendered(function () {
        var select_2 = $(editor);
        select_2.select2({
            placeholder: '-',
            allowClear: true
        });
        select_2.focus().select();
        
        select_2.on('change', function (e) {
            success(select_2.value);
            
        });


        select_2.on('blur', function (e) {
            cancel();
        });
    });


    //add editor to cell
    return editor;
    };

**Comment by olifolkerd** [comment]
Is there are reason you are not using the built in select editor?

**Comment by aklaver** [comment]
What is the Editable callback doing?
What is PopulateSelect doing?
Are there any errors in the console log?

**Comment by aliramadan8** [comment]
Hi olifolkerd  ,
i use select2 control to allow search in place in the select for large data

Hi aklaver ,
Editor is just a true/false var

    //#region fill inthe array
    function PopulateSelect(select, dataSource, addBlank) {
    var index, len, newOption;
    if (addBlank) { select.appendChild(new Option('', '')); }
    console.log('inside poputale');
    $.each(dataSource, function (value, text) {
        //console.log('text is ' + text);
        newOption = new Option(text, value);
        select.appendChild(newOption);
    });
}
