### ISSUE TITLE
how to  customize a tooltip. 

### ISSUE THREAD

**Issue by yaxino** [olifolkerd/tabulator#222]
how to  customize a tooltip. 
then  It can contain HTML tags, but not show HTML tags.

thank you !

**I would like to use tabulator, I hope it is more perfect !**

**Comment by olifolkerd** [comment]
Hey,

The tooltips in tabulator use the ***title*** attribute on the ***.tabulator-cell*** div, which is then handle by the browser to create the tool tip. The HTML specification does not allow for HTML content in this attribute,

Having said this there is nothing to stop you from adding your own custom tool-tip system, or using any of the may libraries out there.

For example the [jQuery UI tooltip](https://jqueryui.com/tooltip) library comes with jQueryUI that you will already have included in your project to use Tabulator. Include the following in your project after your Tabulator definition:
```js
$(".tabulator").tooltip({
	items: ".tabulator-cell",
	content: function() {
		var element = $( this );
		var text = element.data("value");

		return "<p>This is a custom tooltip</p><p>" + text + "</p>";
	}
});
```
Alter the return value of the ***content*** function to change the output of the tooltip.

Let me know if that helps.

Cheers

Oli

**Comment by yaxino** [comment]
yes that is good .thanks
