### ISSUE TITLE
Tooltip getting displayed even after setting to false at column level

### ISSUE THREAD

**Issue by fingers10** [olifolkerd/tabulator#2220]
**Describe the bug**
I have enabled tooltips and header tooltips on table level and if I disable tooltip on particular column level tooltips are still getting displayed. This is not possible in Tabulator?

Referring #2218 I have updated the fiddle as you mentioned but still tooltip shows. And I'm opening this as #2218 was closed.

**Tabulator Info**
- version 4.2.7

**Working Example**
Please check on the fiddle link [Tooltip Bug](https://jsfiddle.net/L4aqrhw6/)

**To Reproduce**
1. set `tooltipsHeader: true` and `tooltips: true` on table level
2. set `headerTooltip: false` and `tooltips: false` on column level

**Expected behavior**
tool tip should be disabled for particular column

Thanks,
Abdul

**Comment by olifolkerd** [comment]
@fingers10 please dont create unnecessary extra issues, this is clearly the same issue that you raised the other day, if the advice i gave you on that issue did not work, please respond on that issue so that we can track progress to a solution.

closed issues can be reopend

cheers

Oli :)

**Comment by fingers10** [comment]
I apologize. I thought since that was closed I need to open new one. Sorry again.

**Comment by olifolkerd** [comment]
no problem, just add your comments to the old issue and we can work through it
