### ISSUE TITLE
Tabulator 4.3 Out Now!

### ISSUE THREAD

**Issue by olifolkerd** [olifolkerd/tabulator#2221]
### Tabulator 4.3 Out Now!

The latest version of Tabulator is now available, with new features and bug fixes, checkout the [Release Notes](http://tabulator.info/docs/4.3/release) for more information!

As promised you can find an updated roadmap for the next couple of versions [On Trello](https://trello.com/b/rPZ0Yavc/tabulator-roadmap), things are still a bit fluid at the moment, but that should give you a rough idea of what to expect.

If there are features you are keen on, please like the respective issue here on GitHub and comment on it so i know which features are most important to the user base.

Cheers

Oli :)

**Comment by Jojoshua** [comment]
Here is my planned update to the Typescript declarations. I went by the release notes to make these updates; let me know if anything is missing.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37041/commits/a881dc254c4b88ac0119f0292de8e10341ac1dc8

**Comment by olifolkerd** [comment]
@Jojoshua looking good, if you have a look at /src/js/column.js at the bottom of the file there is a list for all valid column definition properties if that is of any use to you.

Cheers

Oli :)

**Comment by Jojoshua** [comment]
Thanks @olifolkerd ,that is good to know. Column properties are the hardest to figure out because I try to keep the properties that are part of the column layout for getColumnLayout() and column definition for getColumnDefinitions() separated and just have the ColumnDefinition extend the ColumnLayout props.


    interface ColumnLayout {       
        title: string;
        field: string;
        visible?: boolean;
        width?: number | string;
    }

    interface ColumnDefinition extends ColumnLayout, CellCallbacks {
     align?: ColumnDefinitionAlign; 
    ....
    }
