### ISSUE TITLE
Build an Angular Component and Quick Setup Guide

### ISSUE THREAD

**Issue by olifolkerd** [olifolkerd/tabulator#2222]
Hey All,

Now that jQuery is out of the way, user are asking to use Tabulator more and more with different frameworks.

It would be great if we could create a component for each framework to make it even easier for users to integrate Tabulator into their projects.

@ngduc has kindly already created the react-tabulator wrapper to create a react component

Im too busy myself managing the core library to have the time to build these components as well, so i was wondering if one of the community would be willing to take on the challenge of building a Angular Component for Tabulator.

The wrapper would also get a link to from the Tabulator Website

If you are interested the please leave a message here.

Cheers

Oli :)

**Comment by dota2Pro** [comment]
You don't need any special wrapper for Angular, It works as it is [Stackblitz Demo](https://stackblitz.com/edit/angular-ckujf9)

I put details in this [post ](https://github.com/olifolkerd/tabulator/issues/2024)some time back

**Comment by olifolkerd** [comment]
Hey @dota2Pro 

We absolutely DO new a component.

While you are right it can be used without a component, the same can be said for the Vue and React integrations.

The point is that the component architecture is there to abstract away functional implementation and make it easy for people to implement with minimal additional coding. that is one of the most powerful features of these frameworks.

To be consistent with the other framework i want there to be an angular component for this project which is why i am advertising it for any developer that wants to take up the challenge.

If that isnt you then that is fine but please do not discourage people from taking on this worthwhile project. you will see from NPM that the wrappers for the other two frameworks are very popular.

Cheers

Oli :)

**Comment by dota2Pro** [comment]
Hi @olifolkerd ,

Before I start developing this more, Was this angular wrapper what you were looking for ?
https://stackblitz.com/edit/angular-c4m3yh?file=src%2Fapp%2Fhello.component.ts

`  <ng-tabulator-table
  [tableConfig]="tableConfig1"
  [tableData]="tableData1"
  [tableColumns]="tableColumns1"
></ng-tabulator-table>`

**Comment by mallenswe** [comment]
Hey Oli!

This sounds very similar to what I've made for my project, @ngduc has a similar format to what I'm using. I can transfer what I currently have to a boiler plate Angular project. The code has been suited for my use however if people like it and I can expand on the other features that I haven't used yet.

**Comment by olifolkerd** [comment]
Hey @mallenswe 

That would be amazing, ideally it would be available on npm as ***angular-tabulator*** in a similar fashion to react-tabulator.

Once you have things up and running, if you could send over an example i can include on the [Frameworks Documentation](http://tabulator.info/docs/4.6/frameworks#angular) i would then be happy to include a link to the website for your wrapper.

Cheers

Oli :)
