### ISSUE TITLE
Error while printing when there is a row number (formatter: rownum) column

### ISSUE THREAD

**Issue by aditya-thimphu** [olifolkerd/tabulator#2224]
**Describe the bug**
Below error is shown when printing a table that has row number (formatter: rownum) column. However, print works fine when the row number column is removed.

tabulator.min.js:8 Uncaught TypeError: t.getRow(...)._getSelf is not a function
    at C.rownum (tabulator.min.js:8)
    at C.formatValue (tabulator.min.js:7)
    at tabulator.min.js:9
    at Array.forEach (<anonymous>)
    at tabulator.min.js:9
    at Array.forEach (<anonymous>)
    at k.generateBodyElements (tabulator.min.js:9)
    at k.genereateTable (tabulator.min.js:9)
    at B.replaceTable (tabulator.min.js:10)
    at HTMLButtonElement.onclick (rpthrmpayrolltds:1190)
rownum @ tabulator.min.js:8
C.formatValue @ tabulator.min.js:7
(anonymous) @ tabulator.min.js:9
(anonymous) @ tabulator.min.js:9
k.generateBodyElements @ tabulator.min.js:9
k.genereateTable @ tabulator.min.js:9
B.replaceTable @ tabulator.min.js:10
.....

**Tabulator Info**
Version 4.3

**Expected behavior**
Print feature should work even when there is a rownum column in a table.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by olifolkerd** [comment]
Hey @aditya-thimphu 

Sorry to hear you are having issues, could you post a copy of your constructor as is is hard to diagnose the issue without seeing how your table is setup.

Cheers

Oli :)

**Comment by aditya-thimphu** [comment]
@olifolkerd Thank you for your response. Below is the table constructor:

report = new Tabulator("#report-table-detailed",{
            placeholder:"Select required parameters/filters to view report.",
            height:"600px",
            movableColumns: true,
            columnCalcs:"both",
            printAsHtml:true, //enable html table printing
            printCopyStyle:false, //copy Tabulator styling to HTML table
        });

Column definitions and other configurations are passed from PHP. Below is columns definition. When "Sl.#" row is removed, print report.print() works fine.

$columns = [
            ["title" => "Sl.#", "formatter" => "rownum", "headerSort" => false],
            ["title" => "Employment Type", "field" => "EmploymentType","visible"=>(empty($visibleColumns) ? false : in_array("EmploymentType",$visibleColumns)), "hasShowHide" => true, "hasGrouping" => true],
            ["title" => "Designation", "field" => "Designation","visible"=>(empty($visibleColumns) ? false : in_array("Designation",$visibleColumns)), "hasShowHide" => true, "hasGrouping" => true],
            ["title" => "Division/Unit", "field" => "Organogram","visible"=>(empty($visibleColumns) ? false : in_array("Organogram",$visibleColumns)), "hasShowHide" => true, "hasGrouping" => true],
            ["title" => "Location", "field" => "Location","visible"=>(empty($visibleColumns) ? false : in_array("Location",$visibleColumns)), "hasShowHide" => true, "hasGrouping" => true],
            ["title" => "Name", "field" => "Name","visible"=>(empty($visibleColumns) || in_array("Name",$visibleColumns)), "hasShowHide" => true],
            ["title" => "TPN", "field" => "TPN","visible"=>(empty($visibleColumns) || in_array("TPN",$visibleColumns)), "hasShowHide" => true],
            ["title" => "CID/WP No.", "field" => "CitizenshipIdNo","visible"=>(empty($visibleColumns) || in_array("CitizenshipIdNo",$visibleColumns)), "hasShowHide" => true],
            ["title" => "Basic Pay", "field" => "TotalRegularWage", "align" => "right", "formatter" => "money","bottomCalc"=>"sum","bottomCalcFormatter"=>"money","bottomCalcFormatterParams"=>["decimals"=>2]],
            ["title" => "Allowances", "field" => "Allowances", "align" => "right", "formatter" => "money","bottomCalc"=>"sum","bottomCalcFormatter"=>"money","bottomCalcFormatterParams"=>["decimals"=>2]],
            ["title" => "Gross Salary", "field" => "Gross", "align" => "right", "formatter" => "money","bottomCalc"=>"sum","bottomCalcFormatter"=>"money","bottomCalcFormatterParams"=>["decimals"=>2]],
            ["title" => "TDS from Salary", "field" => "TdsAmount", "align" => "right", "formatter" => "money","bottomCalc"=>"sum","bottomCalcFormatter"=>"money","bottomCalcFormatterParams"=>["decimals"=>2]],
            ["title" => "Health Contribution", "field" => "HealthContribution", "align" => "right", "formatter" => "money","bottomCalc"=>"sum","bottomCalcFormatter"=>"money","bottomCalcFormatterParams"=>["decimals"=>2]],
            ["title" => "Total", "field" => "TotalDeduction", "align" => "right", "formatter" => "money","bottomCalc"=>"sum","bottomCalcFormatter"=>"money","bottomCalcFormatterParams"=>["decimals"=>2]],
            ["title" => "Remarks","visible"=>(empty($visibleColumns) || in_array("Remarks",$visibleColumns)), "hasShowHide" => true]
        ];

**Comment by angeliski** [comment]
A fiddle to reproduce: https://jsfiddle.net/wva9cdt6/

**Comment by aditya-thimphu** [comment]
@olifolkerd / @angeliski, please check the fiddle: https://jsfiddle.net/f1w208zn/1/

**Comment by olifolkerd** [comment]
Hey @aditya-thimphu 

I have just pushed a fix for this to the 4.4 branch which will be released later today

Cheers

Oli :)

**Comment by aditya-thimphu** [comment]
Hi @olifolkerd,
Thank you for the fix.

While implementing version 4.4 found that the rownum column appears in the print, but the column header of rownum column is missing and thus the remaining column headers are shifted.

Please check the JS fiddle [here](https://jsfiddle.net/uc1khvrs/).

Thanks,
Aditya
