### ISSUE TITLE
in v4.3 getHTML() returns only visible rows

### ISSUE THREAD

**Issue by ryhill** [olifolkerd/tabulator#2225]
**Describe the bug**
In v4.3 getHtml() returns only visible rows of table. other rows are ignored.

**Tabulator Info**
- Which version of Tabulator are you using?
version 4.3

**Working Example**
 var htmlTable = table.getHtml();

        console.log(htmlTable);
        

**To Reproduce**
If you have more than 1 page and call getHtml(), it returns only visible rows.

as mentioned in the document, it should return all rows of the table and only when arguments are passed, it should display active rows

**Comment by olifolkerd** [comment]
Hey @ryhill 

As per the [Release Notes](http://tabulator.info/docs/4.3/release#html) this functionality changed in version 4.3

Cheers

Oli :)

**Comment by ryhill** [comment]
Ok...then printVisibleRows:false, doesn't get all rows of the table while printing... Thanks
