### ISSUE TITLE
Impossible to expand/collapse tree row if the first column is editable 

### ISSUE THREAD

**Issue by hovornyan** [olifolkerd/tabulator#2227]
**Describe the bug**
Impossible to expand/collapse tree row if the first column is editable 

**Tabulator Info**
v 4.2.7

**Comment by olifolkerd** [comment]
Yes,

In this scenario i would recommend creating a empty first column to hold the tree element

Cheers

Oli :)

**Comment by tentus** [comment]
https://jsfiddle.net/x4cta8jp/

Here's an illustration of what I believe you're referencing: the editor "eats" the click of the tree control element, meaning the user can never collapse the branch.

Related, if you click one of the children, they lose their tree elements, so that's no fun.

**Comment by tentus** [comment]
(Illustration of Oli's solution: https://jsfiddle.net/x4cta8jp/1/)

**Comment by olifolkerd** [comment]
Thanks @tentus  that is a very helpful demo

**Comment by olifolkerd** [comment]
I will look at blocking the click propagation on tree elements

**Comment by hovornyan** [comment]
For me it is important the pading of name do I tried to resolve this problem by enabling the editing of a cell by double click on it 
`{title:"Name", field:"name", width:400, responsive:0, editor:"input", editable:false,               cellDblClick:function(e, cell){ cell.edit(true);  }}`

but after editing the expand icon and brach disappear and column return to the left of the table.

**Comment by michael-ts** [comment]
In my case, I'm trying to use the last column as the toggle element column.  The reason I'm doing this is that this is a description field, and I want the description to be the field that is indented.

**Comment by olifolkerd** [comment]
Hey All,

I have pushed a fix for this to the master branch. It will be included in todays patch release.

Cheers

Oli :)
