### ISSUE TITLE
Also deploy ESM and CommonJS modules in the dist folder.

### ISSUE THREAD

**Issue by nborelli** [olifolkerd/tabulator#2228]
**Is your feature request related to a problem? Please describe.**
In order to better support JavaScript frameworks that use TypesScript, WebPack Rollup.js, etc.  It would be better to also deploy the Tabulator.info code in several module formats so that it will work the `require()` (CommonJS) and the newer ES2015 module format.

This would also allow bundlers like WebPack and Rollup.js to tree shake the code.  I

**Describe the solution you'd like**
I would like the `dist/js` folder to contain several files or sub-folders with code that is bundled in several ways.  Ideally their would be a ES2015-ESM module format, a Common JS file/folder and a UMD module file/folder.

The package.json file should include references to the entry points for the different different versions and contain lines something like this:

```json
{
  "module": "dist/js/es2015-esm.js",
  "es2015Cjs": "dist/js/es2015-commonjs.js",
  "es2015umd": "dist/js/es2015-umd.js",
  "esm2015": "dist/js/es2015-esm.js",
  "esm5": "dist/js/es5-esm.js",
}
```

**Describe alternatives you've considered**
Not a lot of great alternatives that I have found.

**Additional context**
I tend to write my code in TypeScript, so do not use Babel myself.  However, I believe Babel does support outputting to different module formats through their plugin system.

This article discusses the various formats: <https://2ality.com/2017/04/setting-up-multi-platform-packages.html>

Also see <https://babeljs.io/blog/2018/06/26/on-consuming-and-publishing-es2015+-packages>

If you want to look into rollup.js, this article is a light into: <https://risanb.com/posts/bundling-your-javascript-library-with-rollup>

Thanks,
Neal

**Comment by olifolkerd** [comment]
Hey Neal

Tabulator is already wrapped in a Universal Module Definition (UMD) to handle all the usual variants with out need it to be compiled down to different files, it can be found in the `src/core_modules.js` file.

If you feel there is one missing then let me know, but it already covers all the main module/browser/node formats

Cheers

Oli :)

**Comment by nborelli** [comment]
Hi Oli,

Yes, but an ESM module is something different.  This is the new ES2015 module format that is supported in all of the evergreen browsers and also in Node 12.  It allows you to use a script tag as follows:

```html
<script type="module" src="js/tabulator-info.esm.js"></script>
```
This will allow us to import the code from other modules using the `import` statement as well.  When using a bundler like Rollup.js or WebPack, we will also be able to tree shake the code provided it is also ES2015 code.  ESM is the new "official" module format for JavaScript now.  Node.js has moved to it as have many NPM packages.

Here are a few resources: 
<https://dev.to/bennypowers/you-should-be-using-esm-kn3>
<https://flaviocopes.com/es-modules/>
<https://hacks.mozilla.org/2018/03/es-modules-a-cartoon-deep-dive>
<https://2ality.com/2017/04/setting-up-multi-platform-packages.html>
<https://jakearchibald.com/2017/es-modules-in-browsers>
<https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules>

I believe you should be able to deliver just UMD and ESM and meet most everyone's needs.  It should make using Tabulator with Angular, TypeScript, etc. much easier as well.

Thanks,
Neal

**Comment by jandagroup** [comment]
Any updates on this? This would be particularly useful. Thanks!

**Comment by olifolkerd** [comment]
I have just pushed an commit for this to the 4.8 branch, which should be released next week.

I have only oped to include the ***module*** entry point, which will allow the use of the import statement, and all the benefits of the ESM approach. 

Cheers

Oli :)
