### ISSUE TITLE
New Feature or new Project: Forms

### ISSUE THREAD

**Issue by KarstenHahn** [olifolkerd/tabulator#2230]
Hi,

at first: many thanks for this interesting Library! I'll try it further for my next project...

I'm wondering if it is possible to reuse some features for a Forms Library. Many aspects of Tabulator fits to the requirements of such a forms library (Editors, Validators, etc...)

My programming skills are not so good to develop it, but Oli, if you have time and appetite for a new project, it would be great :-)

Thanks and best greetings,
Karsten

**Comment by olifolkerd** [comment]
Hey @KarstenHahn 

Thanks for getting in touch, That is an interesting idea you have there.

Tabulator is great at tables, and i want to keep it specialised for just that purpose.

As for a second set of libraries for managing forms, im afraid i have my hands full just managing Tabulator so wouldn't be able to focus on that myself. But i am sure there are already many great libraries out there for each of those sections, a bit of googling will probably show up a great many.

Thanks for getting in touch.

Cheers

Oli :)
