### ISSUE TITLE
Start a nested table closed 

### ISSUE THREAD

**Issue by andreaeasycloud** [olifolkerd/tabulator#2231]
It will be nice to have the possibility to start a nested table closed, and then toggle the row (showing the table) by click on a column.
The example is like this https://jsfiddle.net/aklaver/74190bvf/8/ but not using tree, but using a nested table like http://tabulator.info/examples/4.2#nested-tables

**Comment by olifolkerd** [comment]
Hey @andreaeasycloud 

Nested tables are generated using a row formatter, therefore you already have complete control of whether they are visible or not.

Simply ensure the Tabulator div element in the formatter is hidden when it is first loaded.

Cheers

Oli :)
