### ISSUE TITLE
cellEditCanceled event is triggered when using custom select component inside a cell.

### ISSUE THREAD

**Issue by shaulnaim** [olifolkerd/tabulator#2232]
love Tabulator (Thanks @olifolkerd )  ,  sure it can work the way i want can someone help ?
 i am trying to embed component inside Tabulator cell like this
```
{
          title: 'Services',
          field: 'services',
          // headerSort: false,
          editable: true,
          editor: this.serviceSelectEditor,
          formatter: this.allowRowGrowthCellFormatter.bind(this),
          formatterParams: { isValueArray: true },
          cellEditing: (cell) => { 	console.log('cellEditing in edit services');},
          cellEditCancelled: (cell) => {console.log('in canceled services');},
          cellClick: (e, cell) => {
            e.stopPropagation();
          },
        }
```
![image](https://user-images.githubusercontent.com/2099185/61721752-aa34af80-ad71-11e9-94b1-7ae797ec36ac.png)
but when i am clicking one of the options on the suggestion list (dropdown list) before i am getting to the onselect event in my component the tabulator event cellEditCancelled is triggered and closing my editor.... and therefore the selection is not happenning...

from this code in Tabulator.js
```
//prevent editing if another cell is refusing to leave focus (eg. validation fail)
		if (this.currentCell) {
			if (!this.invalidEdit) {
				this.cancelEdit();
			}
			return;
		}
```

i tried stopPropagation and preventDefault on cellClick but still Tabulator think selecting optiot is like focus out. how can i control the triggerring of cancelEdit?

**Comment by tentus** [comment]
It sounds like tabulator's seeing the click event as being a blur event, but without more context that's just speculation. Please include a JS Fiddle or Code Pen that demonstrates the problem.

**Comment by shaulnaim** [comment]
I am using tabulator in angular peoject. Van i use stackblitz to show you the issue, do you have alink to stackblitz tabulator example?

**Comment by shaulnaim** [comment]
I am using tabulator in angular peoject. Can i use stackblitz to show you the issue, do you have alink to stackblitz tabulator example?

**Comment by olifolkerd** [comment]
Hey @shaulnaim 

It will because your custom editor is using a blur event to cancel the edit on the cell, and any click on any element outside the input is counted as a blur, you need to check the origin of the blur event before triggering the cancel in your editor.

Cheers

Oli :)

**Comment by shaulnaim** [comment]
we solved the problem by adding tabIndex=-1 to the container of the custom editor component, which result not allowed loosing focus on selecting items from dropdown. think it might help to future people having the same problem

Thanks a lot @olifolkerd  keep on the good work looking forward for future Tabulator releases

**Comment by tentus** [comment]
Thanks for posting the solution you found!
