### ISSUE TITLE
Responsive don't work when adding new column or change visibility

### ISSUE THREAD

**Issue by giuliano-marinelli** [olifolkerd/tabulator#2233]
**Describe the bug**
When using responsive layout and then add a new column or use .show(), the table don't adjust it.

**Tabulator Info**
v4.2.7

**To Reproduce**
1. Use:
**autoResize: true,
layout: "fitColumns",
layoutColumnsOnNewData: true,
resizableColumns: false,
_responsiveLayout: "collapse",_
responsiveLayoutCollapseStartOpen: false**
2. Adjust the browser screen to a little size.
3. Programmaticaly add a column: **table.addColumn(_definition_, true, _otherColumn_);** or show a hidden column: **table.columnManager.getColumnByField(_"FIELD_NAME"_).show();**

JSFiddle: [https://jsfiddle.net/giuliano_marinelli/dL6og041/](https://jsfiddle.net/giuliano_marinelli/dL6og041/)

**Expected behavior**
When adding a new column or use .show() over existing one, the table may be adjusted if responsive module is active.

**Screenshots**
Before adding column:
![1](https://user-images.githubusercontent.com/5109640/61722418-accae100-ad40-11e9-8c28-9d73220510e6.PNG)
After:
![2](https://user-images.githubusercontent.com/5109640/61722431-afc5d180-ad40-11e9-9182-ff915777c850.PNG)
(same result when use show())

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 75

**Comment by tentus** [comment]
Please include a JS Fiddle or Code Pen that demonstrates the problem.

**Comment by giuliano-marinelli** [comment]
> Please include a JS Fiddle or Code Pen that demonstrates the problem.

Added

**Comment by giuliano-marinelli** [comment]
Another problem when show THE COLUMN:
![3](https://user-images.githubusercontent.com/5109640/61730405-af810280-ad4f-11e9-821d-9e5bb1732faa.PNG)

**Comment by tentus** [comment]
It looks to me that the issue in the second screenshot stems from the fact that all your columns have a width or minWidth set on them. Try loosening up your column definitions to give Tabulator more room to work with.

For the rest of it, try using the [showColumn/hideColumn functions](http://tabulator.info/docs/4.3/columns#visibility) (eg `table.showColumn("car");`) instead going all the way thru the columnManager. You're probably going to have to do some experimentation, since combining auto-collapse and explicit visibility is a pretty steep order, but that should help get you started.

**Comment by giuliano-marinelli** [comment]
- The function showColumn/hideColumn make the same effect as the mentioned (as you can see in the edited fiddle).
- If the minWidth of the columns is not setted, with responsive active and layout on "fitColumns", the columns reduce it size to the default minumum before it can be collapsed.

I been trying get this works a long time. Think it's a problem with the layout, that make the column adjustement only once at the table build.

**Comment by olifolkerd** [comment]
@giuliano-marinelli what happens if you call the ***redraw*** function on the table after you show/hide your column?

**Comment by giuliano-marinelli** [comment]
> @giuliano-marinelli what happens if you call the _**redraw**_ function on the table after you show/hide your column?

The fiddle i uploaded is doing it.
I particulary trying to make a collapse/uncollapse function for the columns when using responsive layout.
Make this functions, but didn't work as i spec:

```javascript
function tabulatorCollapseColumn(table, column) {
    var objColumn = table.columnManager.getColumnByField(column);

    console.log("------HIDE----- " + column);

    //console.log(table);
    //console.log(objColumn);

    console.log("INI -> VISIBLE: " + objColumn.visible + " VISIBLE RESPONSIVE: " + objColumn.modules.responsive.visible);

    var objLastColumn = table.columnManager.getColumnByIndex(table.columnManager.columns.length - 1);
    var definition = objColumn.definition;
    definition.minWidth = 99999;
    table.deleteColumn(column);
    table.addColumn(definition, true, objLastColumn);

    objColumn = table.columnManager.getColumnByField(column);
    objColumn.hide();
    objColumn.modules.responsive.visible = true;

    console.log("FIN -> VISIBLE: " + objColumn.visible + " VISIBLE RESPONSIVE: " + objColumn.modules.responsive.visible);

    table.modules.layout.layout();
    table.modules.responsiveLayout.initialize();
    table.modules.responsiveLayout.update();
    table.modules.layout.layout();
    table.redraw(true)

    console.log("UPDATE -> VISIBLE: " + objColumn.visible + " VISIBLE RESPONSIVE: " + objColumn.modules.responsive.visible);
}

function tabulatorUncollapseColumn(table, column, width, position) {
    var objColumn = table.columnManager.getColumnByField(column);

    console.log("------SHOW----- " + column);

    //console.log(table);
    //console.log(objColumn);

    console.log("INI -> VISIBLE: " + objColumn.visible + " VISIBLE RESPONSIVE: " + objColumn.modules.responsive.visible);

    //objColumn.show();
    objColumn.modules.responsive.visible = true;

    var objNeighColumn = table.columnManager.getColumnByIndex(position);
    var definition = objColumn.definition;
    definition.minWidth = width;
    table.deleteColumn(column);
    table.addColumn(definition, true, objNeighColumn);

    console.log("FIN -> VISIBLE: " + objColumn.visible + " VISIBLE RESPONSIVE: " + objColumn.modules.responsive.visible);

    table.modules.layout.layout();
    table.modules.responsiveLayout.initialize();
    table.modules.responsiveLayout.update();
    table.modules.layout.layout();

    console.log("UPDATE -> VISIBLE: " + objColumn.visible + " VISIBLE RESPONSIVE: " + objColumn.modules.responsive.visible);
}
```
