### ISSUE TITLE
Option to assign printHeader and printFooter during runtime

### ISSUE THREAD

**Issue by aditya-thimphu** [olifolkerd/tabulator#2234]
It will be nice if there is an option to assign printHeader and printFooter values during runtime (just before printing).

My reports are loaded using ajax based on a number of filter parameters selected by the user.
I want to show those parameters in the report header (printHeader) in the print copy.

Maybe, setPrintHeader and setPrintFooter functions will be good.

Hope I didn't miss it, if this feature is already there.

**Comment by aklaver** [comment]
I have not actually done it but the below looks like what you are after:
http://tabulator.info/docs/4.3/print#print
"Print Formatting

The printFormatter table setup option allows you to carry out any manipulation of the print output before it is displayed to the user for printing"

**Comment by olifolkerd** [comment]
@aditya-thimphu 
you can pass a callback function into both the ***printHeader*** and ***printFooter*** functions that will be called while the printout is being created. They should either return an HTML string or a dom node to be inserted into the header/footer

Cheers

Oli :)

**Comment by aditya-thimphu** [comment]
Thanks @olifolkerd and @aklaver. That's helpful.
