### ISSUE TITLE
Add sum below Each Nested Data tree for Tabulator table

### ISSUE THREAD

**Issue by 805bluebell** [olifolkerd/tabulator#2235]
I am trying to implement Column sum for a nested table. The docs show it for a simple table [here](http://tabulator.info/docs/4.3/column-calcs). But, it doesn't work for Nested table.

I have tried including `bottomCalc:"sum"` in the column definition.

```
columns: [
{ title: "New Lead", field: "newLeadCount", width: 150, bottomCalc: "sum" },
],
```
I want to achieve the sum for each Major row group or Posting ID. But currently, it's showing sum at the bottom. And that too it's not able to count because of the incorrect method. I tried this: 
https://i.stack.imgur.com/MbKho.png

**Comment by tentus** [comment]
I suspect that there's an easier way to do this, but I think this approximates what you're looking for:
https://jsfiddle.net/jmdpt32g/

All I'm doing is using a [custom calculator function](http://tabulator.info/docs/4.3/column-calcs#func-custom) to sum up the child values, with the caveat of needing to pass the field in as a param.

@olifolkerd perhaps this indicates that passing the column as a fourth param to the calc function could add some general utility, similar to how we pass the parent cell into formatters and such?

**Comment by aklaver** [comment]
@tentus  Modifying your fiddle with a groupBy gets closer to what I think @805bluebell  wants:
https://jsfiddle.net/aklaver/1rqy60v9/4/

**Comment by tentus** [comment]
If grouping's on the table then we can take it a step further, since the issue with sum is that it doesn't recurse into children:
https://jsfiddle.net/amwrfzt8/

**Comment by 805bluebell** [comment]
> 
> 
> If grouping's on the table then we can take it a step further, since the issue with sum is that it doesn't recurse into children:
> https://jsfiddle.net/amwrfzt8/
> 
> (edit: after posting this I remembered that sums are applied per-group by default, this variant adds the config to do so on the whole table: https://jsfiddle.net/amwrfzt8/1/)

That answers a lot of questions. So, we can write aggregator functions for fields. It helped. @tentus @aklaver . Thanks a lot guys!
