### ISSUE TITLE
removeFilter for complex filters

### ISSUE THREAD

**Issue by Athing** [olifolkerd/tabulator#2236]
**Describe the bug**
removeFilter is not detecting and removing applied complex filters 

**Tabulator Info**
Version 4.3

**Working Example**
https://jsfiddle.net/Athing/thoc5ky7/

**Expected behavior**
When complex filtering is applied, table should reflect call to removeFilter

**Screenshots**
Error message in console when attempting to remove complex filter:
![tabulator-remove-filter-error-message](https://user-images.githubusercontent.com/10264338/61823377-571a3580-ae21-11e9-811d-cb286ed49982.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by tentus** [comment]
Your call to `table.setFilter()` has an array of objects in an array. it should be just an array of objects.

**Comment by tentus** [comment]
Spent a bit too much time looking for a workaround: long story short, the problem is that the remove function isn't recursive, so if it matches to your Or Array then it kills the whole filter, which is obviously isn't what you want. I'll see if I can come up with a PR this weekend.

**Comment by tentus** [comment]
Thinking on it more, I'm not entire sure about how Oli would prefer the interface for this (I can imagine several reasonable approaches) so I'm just gonna go ahead and post some code here, before spinning up an entire PR:

(inside Filter module)
```
	Filter.prototype.removeFilter = function (field, type, value) {
		var self = this;

		if (!Array.isArray(field)) {
			field = [{ field: field, type: type, value: value }];
		}

		var removeFilter = function (filterList, filter) {
			var changed = false;

			for(var i = filterList.length - 1; i >= 0; i--) {
				var element = filterList[i];
				if (Array.isArray(element)) {
					if(removeFilter(element, filter)) {
						changed = true;
					}
				} else if (filter.field === element.field && filter.type === element.type && filter.value === element.value) {
					filterList.splice(i, 1);
					changed = true;
				}
			}

			return changed;
		};

		field.forEach(function (filter) {
			if (removeFilter(self.filterList, filter)) {
				self.changed = true;
			} else {
				console.warn("Filter Error - No matching filter type found, ignoring: ", filter);
			}
		});

		if (this.table.options.persistentFilter && this.table.modExists("persistence", true)) {
			this.table.modules.persistence.save("filter");
		}
	};
```

I'd love to hear some feedback from the community at large, there's a lot of potential use-cases with filters that I haven't thought of.

**Comment by Athing** [comment]
Thomas, thanks for taking such a deep look into the issue. I'm also curious as to how Oli would approach this.

**Comment by olifolkerd** [comment]
Hey @tentus @Athing 

I agree the process could be easier, but i would have concerns about removing any sub filter of a complex query with the exiting functional arguments

For example the same sub filter could be used in multiple places with different conditionals, therefor you could not simply remove it by passing in its configuration as Tabulator would have no way to distinguish which one you meant.

In this scenario i would actually suggest that we use object pass by reference (similar to how it works when removing filter functions) to solve the issue, and state that if you want to be able to remove a complex filter you must build it from object variables rather than literals, then we can pass the object variable into the ***removeFilter*** function and then compare by reference to make sure it is the correct one to remove.

That way if a person only wants to remove the sub filter once they only use that variable in one place, if they want to remove all copies of it they just need to make sure they use the variable multiple times when they pass it into the filter.

What are your thoughts on that?

Cheers

Oli :)

**Comment by tentus** [comment]
Yeah, the recurring component issue was one of the main concerns in my approach that gave me pause. I like the idea of using pass by reference to add context to nested rules.

To make sure I've got it straight: the default behavior (current) would be that passing scalars would match only on the top level. Passing objects into the function would search recursively for matches, removing any that are identical. If a user wants to manage the same subcondition in multiple places, they can reuse an object, but if they've got the same rule in multiple places and only want to remove it from one, then the solution is to make a clone of the object when building the complex condition.

**Comment by olifolkerd** [comment]
Yup that sounds good to me

**Comment by olifolkerd** [comment]
@tentus did you manage to make any progress with this one?

**Comment by tentus** [comment]
Unfortunately no, I had a coworker resign unexpectedly, so my availability dropped like a rock. :( Sorry about not updating this thread.

**Comment by olifolkerd** [comment]
@tentus All good, no rush

**Comment by grantnathanielbrown** [comment]
> so if it matches to your Or Array then it kills the whole filter, which is obviously isn't what you want.

I am actually trying to do this in a project of mine - How do you use removeFilter to get rid of complex filters (like in this example from the documentation)?

The example below applies a filter that will let through rows with a age of greater than 52 AND (either a height of less than 142 OR with the name steve)

table.setFilter([
    {field:"age", type:">", value:52}, //filter by age greater than 52
    **[
        {field:"height", type:"<", value:142}, //with a height of less than 142
        {field:"name", type:"=", value:"steve"}, //or a name of steve
    ]**
]);

**Comment by olifolkerd** [comment]
Given the lack of activity on this i will assume there is a general lack of desire for this feature from the community in general.

For most complex usage cases it is probably easier to replace all the filters at once, or call a ***gatFilters*** then manipulate the returned results before setting the filters again,.

If the community can come up with a compelling usage case and proposal i would be happy to revisit this.

Cheers

Oli :)
