### ISSUE TITLE
Is it possible to freeze specific columns

### ISSUE THREAD

**Issue by yienchen97** [olifolkerd/tabulator#2237]
Hi, 

Is there any way to freeze specific column by tabulator that I can always make my first column shown? I've been searching for any possible way for some days but still have no idea.

Thanks

**Comment by olifolkerd** [comment]
Yes,

Search frozen columns in the documentation

Cheers

Oli

**Comment by yienchen97** [comment]
@olifolkerd Got it ! 
Many thanks.
