### ISSUE TITLE
HTML download with grouping, styles, filters, calcs

### ISSUE THREAD

**Issue by ryhill** [olifolkerd/tabulator#2238]
Download the complete table as html with grouping, styles, calcs, filters etc

**Comment by aklaver** [comment]
Partially covered:
http://tabulator.info/docs/4.3/release#html

**Comment by ryhill** [comment]
First of all, Thanks to you for helping Oli to contribute your time for answering issues/questions related to tabulator. It's a great tool that has evolved over a period of time.

I have gone through the docs and understand it completely.

But i was thinking if it can be available as part of download like pdf, csv,xlsx,json etc in next releases

and also is there any page where users can show off their work on how they have used Tabulator.It should be a nice thought.

**Comment by aklaver** [comment]
I could see offering that as an option or you can do something like this:
```
var htmlFormatter = function(columns, data, options, setFileContents){
    //columns - column definition array for table (with columns in current visible order);
    //data - currently displayed table data
    //options - the options object passed from the download function
    //setFileContents - function to call to pass the formatted data to the downloader
    setFileContents(table_name.getHtml(true,true), "text/html");
};

table_name.download(htmlFormatter, "tbl.html");
```

**Comment by olifolkerd** [comment]
Hey @ryhill 

That should be easily achievable, i will stick it on the roadmap for the 4,5 release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @ryhill 

I have just pushed this feature to the 4.5 branch which should be released in a few weeks.

Cheers

Oli :)

**Comment by pkirankmr** [comment]
Thanks Oli
