### ISSUE TITLE
Header Filter dropdown with range

### ISSUE THREAD

**Issue by aerfkavu** [olifolkerd/tabulator#2239]
Hello Oli,
First I wanted to say thank you for developing an amazing product. Tabulator is absolutely fantastic! Furthermore, from what I saw so far both here and in StackOverflow, you always answer questions and find solutions for people who inquire, and it is really something to be commended for. It is not taken for granted, and kudos for all the work you put into this! 

My question/feature request is about creating a header filter with a dropdown, but in which the values would be range filters. Right now, from what I saw Tabulator can create a "select" HeaderFilter which can receive an array of values (e.g. values:true), but I was not able to pass to the headerFilterParams a list of range filters to populate in the dropdown.

For example, if I have an age column with different ages, I would like to create a header filter with a dropdown which would have the following ranges: "<5", "5-20","20-60". "60+".

How could I go about doing that? 

I imagine that the solution would be to use a custom filter/editor, but I couldn't find a way to get that to work and both include the "select" headerfilter and at the same time to populate it with range filters instead of specific values...

Any help would be much appreciated!

**Comment by aklaver** [comment]
https://jsfiddle.net/aklaver/npfq74er/32/

**Comment by aerfkavu** [comment]
Fantastic!
Thank you very much @aklaver !!
