### ISSUE TITLE
Version 2.11 tabulator.js line 3555

### ISSUE THREAD

**Issue by SGB-Ma** [olifolkerd/tabulator#224]
A bug in line 3555?
I think, you should change `s**le**f._findRow(row);` to `s**el**f._findRow(row);`.

**Comment by olifolkerd** [comment]
Hey,

Thanks for getting in touch,

This has already been raised as an issue and fixed if you pull the latest version of Tabulator.

Thanks for leeting me know

Cheers

Oli
