### ISSUE TITLE
headerSortStartingDir is not indicated in UI before clicking

### ISSUE THREAD

**Issue by hermannsblum** [olifolkerd/tabulator#2240]
**Describe the bug**

Setting `headerSortStartingDir` for a column results in the correct behaviour, which means that with the first click the sorting direction is set accordingly.
However, before clicking the grey arrow will always indicate ascending sorting, even if `headerSortStartingDir:"desc"`.

**Tabulator Info**
- Which version of Tabulator are you using?
4.2.7

**Working Example**
Please include a JS Fiddle or Code Pen that demonstrates the problem, it is very hard to diagnose an issue from a simple description

Created a small example based on the tabulator quickstart:
https://jsfiddle.net/zm2feykv/4/

Clicking on the header of 'favourite color' will flip the arrow into the correct starting direction.

**Expected behavior**

I would expect the grey arrow to already indicate the initial sorting direction before clicking.

**Comment by tentus** [comment]
As an alternate, potentially faster solution, it seems like a tristate icon would be easy to implement... perhaps something along the lines of [this](https://fontawesome.com/icons/sort-alt?style=solid)?

**Comment by aklaver** [comment]
initialSort?:
http://tabulator.info/docs/4.3/sort#intial
https://jsfiddle.net/aklaver/d97o3chj/9/

**Comment by olifolkerd** [comment]
@aklaver is correct, you havnt set the initial sort on the table so there is no sort applied, it is just the initial order of the data loaded into the table

**Comment by hermannsblum** [comment]
@aklaver `initialSort` is an option, but this does set an active sorting direction (and therefore the _active_ arrow points in the right direction). I do not want that. I only want to sort by one column, and the user may click on another column to sort by that one.

@olifolkerd here is an updated example with `initialSort` that still shows the bug: https://jsfiddle.net/numgq4ve/

**Comment by olifolkerd** [comment]
The grey arrow is just an indicator that sorting is possible. Only a colored arrow indicates active sorting on that column. I do not consider this a bug or issue I'm afraid.

**Comment by aklaver** [comment]
@hermannsblum  I am not understanding what it is you want. Are you maybe looking to disable multi-column sort?:
http://tabulator.info/docs/4.3/sort#header
```
Multi Column Sorting

By default you can sort by multiple columns at the same time by holding the ctrl or shift key when you click on the column headers.
if you wish to disable this behaviour, so only once column can be sorted at a time, you can set the columnHeaderSortMulti option to false

var table = new Tabulator("#example-table", {
    columnHeaderSortMulti:false,
});
```

**Comment by hermannsblum** [comment]
What I would have expected is that the light-gray arrow that is indicating the possibility to sort does just become a dark, _active_ arrow when I click on it at the first time, and not also switch direction, as is the case in https://jsfiddle.net/numgq4ve/ when you click on Favourite Color.

I understand that this is really a minor UI issue and I might propose a PR to fix it once I have the time.

In my specific case I have a scientific table which ranks methods based on different poissble metrics, some of them are better when higher, some are better when lower. It therefore just looks very weird with all the arrows pointing in the same direction, especially as in printed tables arrows are also often used to indicate if higher or lower values are better.

**Comment by aklaver** [comment]
We are back to, if you want to show preferred rank use initialSort. This will start the table in the preferred mode. The user then can scramble it in what ever manner they want:)

**Comment by tentus** [comment]
What he's referencing is the _presentation_ of the sort. The display for the no-sort does not reflect the sorting that will happen when clicked, it just always uses an up arrow. 

If you look at his example, Name is sortable, as indicated by a grayed up arrow. If you click it, the arrow darkens and the sort is applied. Color is also sortable, again indicated by a grayed up arrow. It's the _up_ part that can be misleading here, because when you click it the arrow switches direction and darkens.

IMO the solution is to use an icon for "sorting is possible but not applied to this column" that does not imply a direction, or implies both, like ↕ or ⥮.
