### ISSUE TITLE
Footer: buttons are too low and are covered by a "roof" line

### ISSUE THREAD

**Issue by G-WAN** [olifolkerd/tabulator#2242]
Hello,

If I remove `"margin-top:-11px"` then the buttons are _too low_ in the footer, and a _light-grey line_ appears as a "roof" covering them (see the screenshots).

The string is all on one line in the actual code, I have detached it here for clarity:

`footerElement:"<div style='float:left;margin-top:-11px;padding:7px 0' class='tabulator-footer'>`
`<button id='button-add' style='padding:0'>new</button>`
`<button id='button-del' style='padding:0'>del</button>`
`<button id='button-udo' style='padding:0'>undo</button>`
`<button id='button-rdo' style='padding:0'>redo</button>`
` <span id='undo-nbr'>0</span></div>",`

```
![tabulator-footer-buttons-not-ok](https://user-images.githubusercontent.com/506161/61991475-e78a8d00-b050-11e9-880a-11fb591ab0a8.png)
![tabulator-footer-buttons-corrected](https://user-images.githubusercontent.com/506161/61991476-e78a8d00-b050-11e9-922a-536650864d0f.png)

**Comment by olifolkerd** [comment]
@G-WAN you can adjust the CSS content of the footer in any way you like, just include custom CSS after you have imported the tabulator.css
