### ISSUE TITLE
Undo doesn't show deleted item (in table and bottomCalc) until column-sort is toggled twice

### ISSUE THREAD

**Issue by G-WAN** [olifolkerd/tabulator#2243]
Once Undo is used, the deleted entry is restored, but **not at its previous table position** - until the CURRENT column-sort refresh is _toggled twice_ manually (any simple way to _refresh_ a column-sort programmatically? a simple table redraw has no effect).

Unlike the table bottomCalc, a GROUP bottomCalc updates the number of entries without a refresh however.

As, with **multi-page tables**, this is most likely to disturb end-users (not seeing the item back in the list), any guidance about how to avoid or resolve this issue is welcome. Thank you!

**Comment by olifolkerd** [comment]
Hey @G-WAN 

It is really hard to offer advice on your situation without understanding how your table is configured, if you are having issues, please create an issue with the BUG template provided as it will prompt you to enter all the details we need to properly asses the issue.

At the least a JS Fiddle that demonstrates the issue would be vert helpfull

Cheers

Oli :)

**Comment by G-WAN** [comment]
For what it's worth, here is my solution (might benefit to others):

```
function UndoAction(action, component, data){ 
  table1.setSort(table1.getSorters()); // force current sort to see restored-entry
}

```
