### ISSUE TITLE
Default Sort Indication for Ajax Sourced Sorted Data

### ISSUE THREAD

**Issue by fingers10** [olifolkerd/tabulator#2245]
Dear Olifolkerd,

I have Ajax Sourced data sorted by a particular column by default. When the data is loaded into Tabulator for the first time I need to enable asc sort indicator on the column. I looked into the docs and that covers default sort enablement for local data. But how to make this work with Ajax Sourced Default Sorted data?

Please assist.

Thanks,
Abdul

**Comment by olifolkerd** [comment]
you need to use the ***initialSort***

```js
var table = new Tabulator("#example-table", {
    initialSort:[
        {column:"age", dir:"asc"}, //sort by this first
        {column:"height", dir:"desc"}, //then sort by this second
    ]
});
```
