### ISSUE TITLE
Add option to suppress warnings on Invalid table constructor & column definition options.

### ISSUE THREAD

**Issue by nypinstripes** [olifolkerd/tabulator#2250]
**Is your feature request related to a problem? Please describe.**

My company's app is built around custom option logic for cells that is very intricate and complex, far more so than the average need goes. We've constructed an api interface to optimize all our logic operations on the front end and pass through those options into our tabulator components with react-tabulator, to now have to strip out all the custom fields from every table and column would cripple a system that is already struggling to find every avenue possible to improve performance. 

**Describe the solution you'd like**

Add a config option or attribute to suppress console warnings for invalid options on tables and column defs.

**Describe alternatives you've considered**

![Screen Shot 2019-07-30 at 3 28 05 PM](https://user-images.githubusercontent.com/1851296/62158966-a7d8d500-b2de-11e9-99bc-67d0a861ce41.png)
Don't compulsively warn if extra data is passed into the table objects on creation.

**Additional context**

@dwolff 
@sibsibsib 
@vasiliyaltunin 
@aklaver 
@morficus 

Thanks

**Comment by olifolkerd** [comment]
You make a valid point, I will add an option to the next update to suppress them if needed.

**Comment by olifolkerd** [comment]
I have pushed an update to the 4.4 branch which will be included in todays release.

there is now a ***invalidOptionWarnings*** option that you can use to disable the warnings.

Cheers

Oli :)
