### ISSUE TITLE
Can we have tooltip animation delay

### ISSUE THREAD

**Issue by amitanup19** [olifolkerd/tabulator#2251]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by amitanup19** [comment]
Can we have an option for tooltip animation to be delayed for some second

**Comment by tentus** [comment]
I question the reliability of this little hack, but you could accomplish this by using the function approach, eg https://jsfiddle.net/edLxh8w0/1/

**Comment by amitanup19** [comment]
@tentus : i dont think it works, just try the timeout to be 10 seconds and you will see it not working.

**Comment by olifolkerd** [comment]
Hey @amitanup19 

Tabulator uses the built in tooltip functionality of the elements ***title*** attribute which does not come with support for delays.

You would need to use a custom formatter that uses a thrid party tooltip library if you wanted to have that functionality.

Cheers

Oli :)
