### ISSUE TITLE
Show undefined cells as empty cells in print view

### ISSUE THREAD

**Issue by Remph** [olifolkerd/tabulator#2252]
**Is your feature request related to a problem? Please describe.**
If you have undefined columns/cells in your tabledata, the table.print() function returns cells that have the String "undefined" as you can see here:

![UndefinedCells](https://user-images.githubusercontent.com/43972443/62195989-76fbad00-b37d-11e9-9e49-b4b6f1502f7a.PNG)

In order to achieve my result I had to add this line to the HtmlTableExport.prototype.generateBodyElements function (at line 18203):

```javascript
if (value === undefined) {
    value = ""; 
}
```

And the result looks like this: 

![FinalResult](https://user-images.githubusercontent.com/43972443/62196265-fab59980-b37d-11e9-9a16-18e5edc7d029.PNG)

**Comment by aklaver** [comment]
What are the formatters you are using for the columns?
In here:
https://github.com/olifolkerd/tabulator/blob/master/src/js/modules/html_table_export.js
.generateBodyElements uses the cell formatter to set the value if the format module is included. Otherwise 'undefined' is set to ''.

**Comment by ryhill** [comment]
When HTML is generated, we get Undefined in the tables.
I have manually replaced undefined with '' after html is generated instead of changing code in Tabulator

htmlTable = htmlTable.replace(/undefined/g,'');

**Comment by aklaver** [comment]
I can't replicate this, so can someone post a jsFiddle/CodePen example?

**Comment by olifolkerd** [comment]
Hey @ryhill 

As @aklaver says, Tabulator automatically handles undefined values and replaces them with an empty string. This suggests you are using a custom formatter.

If You are not we will need to see  working JS fiddle to understand how your table is setup in order to resolve this for you.

Cheers

Oli :)
