### ISSUE TITLE
Clear filter button for header filter dropdown

### ISSUE THREAD

**Issue by aerfkavu** [olifolkerd/tabulator#2253]
**Is your feature request related to a problem? Please describe.**
Unlike other filters, in the 'select' header filter, the "clear filter" (X) button does not appear

**Describe the solution you'd like**
Enable "X" button to clear drop down filters

**Describe alternatives you've considered**
I know there is an option to add "":"" to the values in the headerFilterParams, but this is not possible, as far as I know, in combination with allowing Tabulator to automatically build the dropdown list from the existing values. 
i.e. -  I want to be able to use "headerFilterParams:{values:true}" in order to populate the dropdown, but then also add a single "":"" value at the beginning, which would be the equivalent of the "X" clear-filter button

**Comment by aklaver** [comment]
Don't have time to set up an example, but why not try the autocomplete editor:

http://tabulator.info/docs/4.3/edit#edit-builtin

It has allowEmpty and freetext along with values: true

**Comment by aklaver** [comment]
https://jsfiddle.net/aklaver/arye3nk2/28/

Filter code shamelessly borrowed from 'like' in filter.js module of Tabulator.

**Comment by aerfkavu** [comment]
Brilliant solution. Many thanks @aklaver !
