### ISSUE TITLE
ReferenceError in RowManager.prototype.redraw when global `self` is not defined

### ISSUE THREAD

**Issue by ttomii** [olifolkerd/tabulator#2258]
ReferenceError is occured in RowManager.prototype.redraw when global variable `self` is not defined.

https://github.com/olifolkerd/tabulator/blob/90146917a84e017402b1eb016a51497d1f986a72/src/js/row_manager.js#L1652-L1663

**Tabulator Info**
4.3.0

**Working Example**

This code is executing on Node.js.

```js
const jsdom = require("jsdom");
const Tabulator = require('tabulator-tables');

const dom = new jsdom.JSDOM(`<html>
<body>
<div id="example-table"></div>
</body>
</html>`);

const window = global.window = dom.window;
global.Event = window.Event;
global.document = window.document;
global.navigator = window.navigator;

const table = new Tabulator("#example-table", {
    height: 205,
    data: [
        {id: 1, name: "Oli Bob", age: "12", col: "red", dob: ""},
    ],
    layout: "fitColumns",
    columns: [
        {title: "Name", field: "name", width: 150},
        {title: "Age", field: "age", align: "left", formatter: "progress"},
        {title: "Favourite Color", field: "col"},
        {title: "Date Of Birth", field: "dob", sorter: "date", align: "center"},
    ]
});

table.redraw(false);
// ReferenceError: self is not defined
```

**Comment by aklaver** [comment]
Can you set up a jsFiddle/CodePen example?

If you do:
```
table.redraw(true);
```
does it work?

**Comment by ttomii** [comment]
> Can you set up a jsFiddle/CodePen example?

It does not reproduce because `window.self` is existing in browser.
In `RowManager.prototype.redraw` , `self` refers `window.self`.
I think it is necessary to replace `self` to `this` or define `self = this` .

> If you do:
> 
> ```
> table.redraw(true);
> ```
> 
> does it work?

Yes, it works.

**Comment by aklaver** [comment]
The example is still going to run in a browser so I am not sure why window.self would not exist.
I do not see this behavior in a non-Node.js case. My suspicion is that this is an out of sequence problem where the redraw() is happening before the table is completely built.

**Comment by ttomii** [comment]
In a browser, `self.renderMode` is `window.renderMode`, and `self.table.options.groupBy` is `window.table.options.groupBy` . I don't think it is correct.

Another example, TypeError occurred when `window.renderMode = "classic"` .
https://jsfiddle.net/un5dxvtz/2/

**Comment by aklaver** [comment]
Alright that helps.  Changing:
```
if(self.renderMode == "classic"){ 
to 
if(self.renderMode == "classic"){ 
     self = this;
```
seems to make this go away. Will create a PR for this.

**Comment by olifolkerd** [comment]
@aklaver has fixed this, it will be included in todays release
