### ISSUE TITLE
Can not move cursor to previous line

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#2259]
**Describe the bug**

I want to move cursor one line up, but it is moved to different row when I press arrow up at the `textarea` editor

Bofore I press arrow up
![_](https://user-images.githubusercontent.com/799021/62289127-991d2a00-b466-11e9-8660-4add4ad96c8f.jpg)

After I press arrow up
![_2](https://user-images.githubusercontent.com/799021/62289145-a20dfb80-b466-11e9-932c-3a9a945aac36.jpg)

**Tabulator Info**
- Which version of Tabulator are you using? 4.2.2

**Expected behavior**
![_3](https://user-images.githubusercontent.com/799021/62289163-ac2ffa00-b466-11e9-8ad3-55dc0b0bc9c7.jpg)

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.1
 - Browser FF 
 - Version 66

**Comment by aklaver** [comment]
That is the default key binding for the up arrow. For more information and how to modify see:
http://tabulator.info/docs/4.3/keybindings#default

**Comment by KES777** [comment]
yeah, to my mind that is not the case for multi line editor. because arrowup at that editor means something different.

For example, If I tries to list over lookup editor I press arrow up - cursor is moved to next item in the select list and not to different table row

**Comment by aklaver** [comment]
Alright. In edit.js 'select' the up arrow key is caught and:
```
case 38: //up arrow
e.stopImmediatePropagation();
e.stopPropagation();
e.preventDefault();
```

This is repeated for the other arrow keys
There is no such code in 'textarea'.

@olifolkerd  will need to explain if there is a purpose for this or not?

**Comment by olifolkerd** [comment]
Hey @KES777 

You are correct, that should certainly navigate the text area better.

As it happens i have already written that functionality for another project i was working on so i can pull it back into the formatter for the 4.5 release

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey

I have just pushed an update to the 4.5 branch that adds a new verticalNavigation editorParam to a lot of editors to make it easier to customise the navigation experience.

This should be released in the next few weeks.

Cheers

Oli :)
