### ISSUE TITLE
Link Formatter: Uncaught TypeError: cell.getData is not a function

### ISSUE THREAD

**Issue by jaehocho** [olifolkerd/tabulator#2260]
I created a column with link formatter. It displays fine, but when I call table.print() function or getHtml() function, I get an error from cell.getData. I tried both approaches of 
- 'name' column using the url from 'url' column
- 'url' column using 'name' column as label

Exception:
Uncaught TypeError: cell.getData is not a function
    at Format.link (tabulator.js:15850)
    at Format.formatValue (tabulator.js:15719)
    at tabulator.js:18229
    at Array.forEach (<anonymous>)
    at tabulator.js:18199
    at Array.forEach (<anonymous>)
    at HtmlTableExport.generateBodyElements (tabulator.js:18176)
    at HtmlTableExport.genereateTable (tabulator.js:17966)
    at HtmlTableExport.getHtml (tabulator.js:18278)
    at Tabulator.getHtml (tabulator.js:8005)

**Tabulator Info**
- version 4.3.0

<script>

  var table_data = [
  {"id":8,"name":"Install 44","url":"/projects/8"}
  ];
  var col_defs =  [{"title":"Name","field":"name","frozen":true,"formatter":"link","formatterParams":{"urlField":"url","target":"_blank"}},{"title":"Project Type","field":"project_type"}];
  
  var table = new Tabulator("#data-table",
    {
      data:table_data,
      columns: col_defs,
      printVisibleRows:false,
      printAsHtml:true,
      printCopyStyle:true
    });
  

  
  | </script>

**Working Example**
https://jsfiddle.net/vpmtcLfj/1/

**To Reproduce**
1. click on 'print' link

**Expected behavior**
HTML table should be shown

**Screenshots**
![Screen Shot 2019-08-01 at 9 02 38 AM](https://user-images.githubusercontent.com/87365/62308945-4e39ed00-b43b-11e9-8ba8-dec3c63e6507.png)

**Desktop (please complete the following information):**
 - OS: MacOs Mojave
 - Browser Chrome
 - Version Version 75.0.3770.142 (Official Build) (64-bit)

**Comment by aklaver** [comment]
Duplicate of?:
https://github.com/olifolkerd/tabulator/issues/2249

**Comment by jaehocho** [comment]
@aklaver, I think you are right. I can't get the other example to show me the stacktrace, but the description sounds identical. I will close this
