### ISSUE TITLE
AjaxConfig via a function callback?

### ISSUE THREAD

**Issue by hrstoyanov** [olifolkerd/tabulator#2266]
Question/Suggestion:

It would be nice to generate AjaxConfig via a function callback for the tabulator options, or when used in setdata(). For example, I have a JWT access token stored in the browser database, and I would like to read it every time from the browser storage (because it might have expired) and set an HTTP header: "Bearer", before I shoot an Fetch call.

I think. I am asking for something like ajaxURLGenerator? I also looked at ajaxRequestFunc , but this is too much detail that I don't need to deal with - I only need to insert an extra header.

**Comment by aklaver** [comment]
ajaxURLGenerator has access to ajaxConfig:

http://tabulator.info/docs/4.3/data#ajax-url

Have you tried modifying it there?

**Comment by hrstoyanov** [comment]
@aklaver 
Thanks, on a second thought ajaxURLGenerator might do the job!
