### ISSUE TITLE
[Feature] Row resizing display entire row resize border

### ISSUE THREAD

**Issue by timothymarois** [olifolkerd/tabulator#2268]
When resizing a row, currently it only highlights a border outline on the column selected, but rather it should show a full row selection border. 

**Non-tabulator, an example of what I'm proposing.** 
![Screenshot 2019-08-04 21 50 12](https://user-images.githubusercontent.com/2489333/62433438-6ee79880-b702-11e9-911c-333cd9430939.png)

**Current Tabulator:** 
![Screenshot 2019-08-04 21 55 06](https://user-images.githubusercontent.com/2489333/62433479-8b83d080-b702-11e9-86f5-09133460d9f3.png)

I'm not aware of any way to make tabulator do this, but I am open to suggestions if it easier for implementation. So far I've only been able to manipulate the CSS which controls only the current "column" border. 

**Describe alternatives you've considered**
Other data tables provide this visual. There is something very satisfactory to the user in having this visual.

**Comment by olifolkerd** [comment]
Hey @timothymarois 

Thanks for your suggestion, 

At the moment that is not a feature i would be looking to add to Tabulator. but i would be happy to accept a pull request if it is something you would like to add your self. If you do it must be as an option function not a default function.

Cheers

Oli :)
