### ISSUE TITLE
ResponsiveLayout:"overflow"

### ISSUE THREAD

**Issue by Stylesoftware** [olifolkerd/tabulator#2269]
**Describe the solution you'd like**
I guess the easiest way to describe would be similar to responsiveLayout:"collapse", except acting like normal tabulator cells including the editing, and the header column name in-front.
It would be an 'overflow' feature adhering to the 'responsive' index number set in the columns description. 

[pic attached of two cells overflowing]

<img width="592" alt="overflow-snip" src="https://user-images.githubusercontent.com/7058247/62437506-9d638300-b797-11e9-81c1-faa3c7c494ba.PNG">

I'm currently looking at trying to gather the HTML from the row, and reformat it how I like but then I lose all the tabulator goodness, such as editing and responsiveness within the custom html etc, unless you have any ideas?

Thanks

**Comment by olifolkerd** [comment]
Hey @Stylesoftware 

Thanks for getting in touch, and thanks for your suggestion.

I am certainly looking into adding editing functionality into the responsive collapse formatter as i think that would be available tool.

However i would not be looking to add an overflow layout like above, it is not very clear what the values represent and the widths of the columns would be arbitrary, it would also have wrapping issues of its own on narrower screens.

Cheers

Oli :)
