### ISSUE TITLE
I am following the basic example on the Quick Start Guide and have the following error

### ISSUE THREAD

**Issue by mwsohn** [olifolkerd/tabulator#227]
tabulator.js:36Uncaught TypeError: $.widget is not a function
    at tabulator.js:36
    at tabulator.js:4362

My full html file looks as follows:

```html
<!DOCTYPE html>
<html>
<head>
</head>
<body>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/tabulator/2.11.0/tabulator.min.css" rel="stylesheet">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tabulator/2.11.0/tabulator.min.js"></script>
    <div id="example-table"></div>
    <script type="text/javascript">
    //create Tabulator on DOM element with id "example-table"
    $("#example-table").tabulator({
        height:"320px", // set height of table (optional)
        fitColumns:true, //fit columns to width of table (optional)
        columns:[ //Define Table Columns
            {title:"Name", field:"name", sorter:"string", width:150},
            {title:"Age", field:"age", sorter:"number", align:"left", formatter:"progress"},
            {title:"Favourite Color", field:"col", sorter:"string", sortable:false},
            {title:"Date Of Birth", field:"dob", sorter:"date", align:"center"},
        ],
        rowClick:function(e, id, data, row){ //trigger an alert message when the row is clicked
            alert("Row " + id + " Clicked!!!!");
        },
    });

    //define some sample data
    var tabledata = [
        {id:1, name:"Oli Bob", age:"12", col:"red", dob:""},
        {id:2, name:"Mary May", age:"1", col:"blue", dob:"14/05/1982"},
        {id:3, name:"Christine Lobowski", age:"42", col:"green", dob:"22/05/1982"},
        {id:4, name:"Brendon Philips", age:"125", col:"orange", dob:"01/08/1980"},
        {id:5, name:"Margret Marmajuke", age:"16", col:"yellow", dob:"31/01/1999"},
    ];

    //load sample data into the table
    $("#example-table").tabulator("setData", tabledata);
    </script>
</body>
</html>
```

**Comment by olifolkerd** [comment]
Hey,

looks like you are not including the jQueryUI library, you have included the jQueryUI css but not the js file. it should be included after jQuery.

Cheers

Oli

**Comment by Deflaktor** [comment]
Thanks, I had the same problem.
Maybe you could make it more obvious in the quickstart example what is needed to be included.

**Comment by olifolkerd** [comment]
Good Point!

I will update the documentation this weekend :)

**Comment by mwsohn** [comment]
Thank you so much. That solved the problem!

Min

**Comment by michaelongithub** [comment]
I have:
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/jquery-ui.min.js"></script>
    <link href="~/css/jquery-ui.min.css" rel="stylesheet" />

and still am getting 'Property "name" of an undefined or null reference cannot be called' at line 343 in tabulator.js (if(attrib.name && attrib.name.indexOf("tabulator-") === 0){)

Versions:
tabulator.js: downloaded today.
jQuery v2.2.0
jQuery UI - v1.12.1

Corrupt tabulator.js file ?? Error in your file?

Thanks for info

**Comment by michaelongithub** [comment]
Thanks for answering. Occurs ONLY IN IE11 (Chrome , Firefox are ok)
Reproducable in your example:
http://olifolkerd.github.io/tabulator/examples/#table-load
If you are in console/debug and reload: error on line 343.
Thanks for looking into it, Michael

**Comment by michaelongithub** [comment]
a college of me found out:
https://developer.mozilla.org/en-US/docs/Web/API/Element/attributes
"Numerical indexing is useful for going through all of an element's attributes."

So its probably the FOR IN

**Comment by olifolkerd** [comment]
I have put in a patch for this this morning.

Let me know if you are still running into trouble.

Cheers

Oli
