### ISSUE TITLE
Delay the display of Header tooltip

### ISSUE THREAD

**Issue by manuagarwal** [olifolkerd/tabulator#2270]
I am trying to delay the tooltip display for column headers. Is there a way that we can define, how many seconds to wait before displaying the header tooltip (Title contents). My aim is to display tool tip only if the user waits there for 3+ seconds.

**Comment by olifolkerd** [comment]
You cannot do this with built in tabulator tooltips, you would need to use a custom formatter that uses a 3rd party plugin to add a bespoke tooltip.

Cheers

Oli :)
