### ISSUE TITLE
Header Filter on TableTrees and Nested Data in 4.3

### ISSUE THREAD

**Issue by henneman** [olifolkerd/tabulator#2272]
**Describe the bug**

**Tabulator Info**
- Which version of Tabulator are you using?
- Post a copy of your construct object if possible so we can see how your table is setup

**Working Example**
Please include a JS Fiddle or Code Pen that demonstrates the problem, it is very hard to diagnose Hello,

I use tab 4.3.

We have a data tree that works in the basic functions but has 2 weaknesses:

1.) in the documentation for version 4.2. is to read:
"Data Tree
Filtering

Filters applied to the table are now applied to all child rows, not just to top level parent rows. "

in the documentaiton to the version 4.3 I find no more information.

Filtering the top parent rows works. But I do not know what the code for the child rows must look like. Is there an example or is it in 4.3. depricated?

2.) The table would be easier to read if the childs expand symbol were indented so far that the symbol would be under the parent's first character. Currently it is between the symbol of the parents and the first sign of the parent.

**Comment by aklaver** [comment]
As to 2):
http://tabulator.info/docs/4.3/tree
Child Indentation
dataTreeChildIndent:15

Also see:
https://github.com/olifolkerd/tabulator/issues/2174
