### ISSUE TITLE
navigator.language undefined on IE when setting locale

### ISSUE THREAD

**Issue by Remph** [olifolkerd/tabulator#2273]
**Describe the bug**
I use the localization function for my Tabulator object and the table creations crashes when using Internet Explorer. This is because in this code in line 9833:

```
if (desiredLocale === true && navigator.language) {

    //get local from system

     desiredLocale = navigator.language.toLowerCase();
}

```

the Tabulator tries to get navigator.language, which is undefined in IE. 
My temporary fix is to use navigator.browserLanguage like this:

```
if (desiredLocale === true && navigator.language) {

	//get local from system

	desiredLocale = navigator.language.toLowerCase();
}
else if (desiredLocale === true && navigator.browserLanguage) {
	
	//get local from IE
	desiredLocale = navigator.browserLanguage.toLowerCase();
}

```

**Tabulator Info**
- 4.3.0

**Comment by olifolkerd** [comment]
Hey @Remph 

navigator.language is available in IE 11. as per the [documentation](http://tabulator.info/docs/4.3/browsers#ie) Tabulator only supports IE11.

Due to the massive coding burden that supporting IE 10 would introduce, i will onlt support modern browsers and IE11.

Cheers

Oli :)
