### ISSUE TITLE
responsiveLayout collapse and getColumnLayout()

### ISSUE THREAD

**Issue by RaquelAM** [olifolkerd/tabulator#2276]
Hi,
I'm using responsiveLayout: 'collapse' and everything works fine but when I use getColumnLayout() the columns that are displayed as a list appear with visibility false. Am I doing something wrong or is this the expected behavior? 
If it is the expected behavior, can I do something to change de visibility to true to those columns? 
Also, this happens when I use persistentLayout: true, in localStorage are saved as visibility false.

**Comment by olifolkerd** [comment]
Hey @RaquelAM 

This is a side effect of the way that the responsive layout manages those columns, it hides them to remove them from the layout and then adds their data to the responsive collapse formatter.

Im afraid there is no way around this.

Cheers

Oli :)
