### ISSUE TITLE
table caption and tabulator

### ISSUE THREAD

**Issue by aamirghanchi** [olifolkerd/tabulator#2277]
[https://stackoverflow.com/q/57385622/262613](https://stackoverflow.com/q/57385622/262613)

**Comment by aklaver** [comment]
I see no information in the SO question that will help with this. See below:
https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=&template=bug_report.md&title=
for what is needed.

**Comment by aklaver** [comment]
Now that you filed this:
https://github.com/olifolkerd/tabulator/issues/2279
Please close this issue.
