### ISSUE TITLE
HTML table caption disappear after tabulator is applied

### ISSUE THREAD

**Issue by aamirghanchi** [olifolkerd/tabulator#2279]
**Describe the bug**
HTML table element's caption tag is not available any more after the tabulator is applied to it

**Tabulator Info**
- Which version of Tabulator are you using?
      The most current version at the time of this post. 
- Post a copy of your construct object if possible so we can see how your table is setup
     `var tbl = new Tabulator("#tbl", {});
`
**Working Example**
Please include a JS Fiddle or Code Pen that demonstrates the problem, it is very hard to diagnose an issue from a simple description

https://jsfiddle.net/aamirghanchi/d6jo1pnh/1/

**To Reproduce**
Please run it in JSFiddle.

**Expected behavior**
Caption test is lost. In this JSFiddle example, the table content is also lost.

**Comment by aklaver** [comment]
In your Fiddle everything is lost as the HTML for the table does not follow the form described here:
http://tabulator.info/docs/4.3/data#table
See this:
https://jsfiddle.net/aklaver/z518ghkx/5/
Per the docs:
http://tabulator.info/docs/4.3/data#table
"Note: Tabulator can only parse simple tables. Tables using multiple header rows, colspan or rowspan attributes will cause the import to fail."
html_table_import.js  only extracts td, th, tbody and tr tags.

I would suggest just using a header tag above the table to get a caption.

**Comment by aamirghanchi** [comment]
Thanks. The Note did not mention "captions", but I understand. Can captions be added to future versions as change request? By the way, very nice work! But not having caption is a deal-breaker and unfortunately, I won't be able to use tabulator. Wishing your team all the best!

**Comment by aamirghanchi** [comment]
caption features request made.

**Comment by aklaver** [comment]
Where is the feature request?
Not sure why using a header tag instead of a caption is a deal-breaker?
