### ISSUE TITLE
can't retrieve filtered and total data data

### ISSUE THREAD

**Issue by 1manfactory** [olifolkerd/tabulator#228]
```
$("#xxx").tabulator("setData","./getdata.php");
$("#xxx").tabulator("setFilter", "number", ">", 410);
console.log($("#xxx").tabulator("getData").length);
console.log($("#xxx").tabulator("getData", true).length);
```
Table is filled and filtered as it should, only showing records with number greater than 410. So far so good.

But both console log statements  which are supposed to retrieve the total record count and the filtered record count give me zero as a result.

**Comment by olifolkerd** [comment]
Hey,

Could you post a copy of your tabulator constructor object so i can run a test with your setup.

Cheers

Oli

**Comment by 1manfactory** [comment]
Hello,
i stripped down all of my code to this:

```
$("#xxx").tabulator({
    pagination:"local",
    paginationSize:20,	
	selectable:true,
	dateFormat:"dd.mm.yyyy",
    fitColumns:true,
    sortBy:'Bestellnummer', 
    sorDir:'desc',
	
    columns:[
	{title:"Bestnr.", field:"Bestellnummer", headerFilter:true, align:"left", sortable:true, sorter:"number", tooltipHeader:"Bestellnummer"},
  
    ],
});

```
And the above mentioned error still exists.

There is no error in Javascript console.

**Comment by olifolkerd** [comment]
If you are loading a lot of data into your table, then it is very likely the table is still loading the data when you call the ***getData*** function.

You either want to trigger your ***getData*** function in one of the available callbacks for example ***dataFiltered*** or set a timeout to give the table time to process the data:
```js
$("#xxx").tabulator({
    pagination:"local",
    paginationSize:20,	
	selectable:true,
	dateFormat:"dd.mm.yyyy",
    fitColumns:true,
    sortBy:'Bestellnummer', 
    sorDir:'desc',
	
    columns:[
	{title:"Bestnr.", field:"Bestellnummer", headerFilter:true, align:"left", sortable:true, sorter:"number", tooltipHeader:"Bestellnummer"},
  
    ],
    dataFiltered:function(){
        console.log("All Data", $("#xxx").tabulator("getData").length);
        console.log("Filtered Data", $("#xxx").tabulator("getData", true).length);
    }
});
```

I hope that helps you out.

Cheers

Oli

**Comment by 1manfactory** [comment]
Great. That did it.
Thanks
