### ISSUE TITLE
is there any way to fetch  top 10  and bottom 10 row  in tabulator for each column  ? Please reply  i am struggling a lot to implement this

### ISSUE THREAD

**Issue by balajis-13395** [olifolkerd/tabulator#2284]
Please ask questions on www.stackoverflow.com the issues list is now reserved for feature requests and bug reports.

Cheers

Oli :)

**Comment by aklaver** [comment]
Please ask on StackOverflow:
https://stackoverflow.com/search?tab=newest&q=tabulator
