### ISSUE TITLE
Import Data from HTML <table> / empty row comes prior contents (full example + screenshot)

### ISSUE THREAD

**Issue by G-WAN** [olifolkerd/tabulator#2285]
After importing an HTML `<table>` for Data, the first row is empty.

Tabulator v4.3
```
<!DOCTYPE html>
<html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="css/tabulator_site.css">
<script type="text/javascript" src="js/tabulator.js"></script>
</head><body>
<table id="tablexxx">
 <tr>
  <th>Name</th><th>Favorite Color</th><th>date</th></tr>
 <tr><td>Bob</td><td>Yellow</td><td>1/1/2001</td>
 </tr>
 <tr><td>Michelle</td><td>Purple</td><td>2/1/2000</td>
 </tr>
</table>
<div id="tablexxx"></div>

<script>
var tablexxx = new Tabulator("#tablexxx", {});
</script>
</body></html>
```
See attached screenshot for result.

![tabulator-empty-row-bug](https://user-images.githubusercontent.com/506161/62821874-3f121800-bb7c-11e9-8136-c62c1204f528.png)

**Comment by olifolkerd** [comment]
That is because you have two nested tr tags which is invalid.

It is also recommended that you put your header row inside thead tags and your body rows in tbody tags. That would be the correct way to define a table. 

Cheers

Oli

**Comment by G-WAN** [comment]
There are NO "nested `<TR>` tags" in this `<table>` (here better formatted):

```
 <tr><th>Name</th><th>Favorite Color</th><th>date</th></tr>
 <tr><td>Bob</td><td>Yellow</td><td>1/1/2001</td></tr>
 <tr><td>Michelle</td><td>Purple</td><td>2/1/2000</td></tr>
```
Please advise.

**Comment by olifolkerd** [comment]
As I previously stated you need to use thead and tbody tags

**Comment by G-WAN** [comment]
I will not [bother you again](https://github.com/olifolkerd/tabulator/issues/2274).

**Comment by olifolkerd** [comment]
@G-WAN 

It is not a bug to require perfectly valid HTML syntax to parse an HTML table into Tabulator.

It is considered good practice to include these elements as it provides better table structure, and improves readability of the table for accessibility tools like screen readers.

The tabulator documentation makes it very clear that these are needed in order for the table to be imported correctly.

If you could explain your usage case better i would be very happy to suggest an option that will help get the data into your table.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
I was not asking you to "not bother me" i was asking you not to go off on a rant when there are perfectly civilised ways to work through your issues.

Tabulator clearly works differently to your expectations. The userbase are patiently trying to help you with you with your issues but you are being very direct and confrontational in your replies. Working with a new library requires adapting to the features of the library and the design paradigm it is written. 

I will certainly be happy to adjust any documentation that is misleading, but you must expect a certain adaptability from your part to use the tool in the way that it is intended, it cannot be all things to all people.

Cheers

Oli :)
