### ISSUE TITLE
Print function does not print rownum column header

### ISSUE THREAD

**Issue by aditya-thimphu** [olifolkerd/tabulator#2286]
**Describe the bug**
While printing tabulator table, I got the following issues:

1. rownum column data is printed, but column header of rownum column is missing and thus the remaining column headers are shifted.
2. Row number is displayed as "0" for summary row which I expect to be blank.
3. When you click the print button multiple times (that is, call the print function multiple times), the summary row is repeated.

**Tabulator Info**
Tabulator 4.4

**Working Example**
Please check the JS fiddle [here](https://jsfiddle.net/9ocmj1px/2/).

**To Reproduce**
1. Click Print button to see the result.
2. Click Print multiple times to see the above third issue.

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome Version 75.0.3770.142 (Official Build) (64-bit)

**Comment by aklaver** [comment]
Figured out 1). You need to have a field name. See:
https://jsfiddle.net/aklaver/0Lask8h6/
3) Is related to caching. Reloading the page between prints eliminates the duplication. Needs further investigation along with 2).

**Comment by olifolkerd** [comment]
Hey @aklaver 

That is indeed why it is happening, but the behaviour is not consistent, it should be ignoring the column in both the body and header if it dosnt have a field name, so i will fix that

@aditya-thimphu as @aklaver suggests the work around for the moment would be to add a made up field name and it will with display correctly.

Cheers

Oli :)

**Comment by aditya-thimphu** [comment]
Thank you @olifolkerd and @aklaver.

**Comment by HongyuWang-2018** [comment]
Hello all,

i used a progress bar in my table, however, when i added the print out button, it can not print out the table with the progress bar. Is that possible to print out the table with the progress bar?
Thank you.
``
<script src="https://unpkg.com/tabulator-tables@4.3.0/dist/js/tabulator.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/tabulator/4.3.0/css/tabulator.min.css" rel="stylesheet" />
<button onclick="printTable()">Print

</button>
<div id="tableContainer"></div>
<script>
var tabledata = [{
    id: 1,
    name: "postp_ckmb_ngml_group_>=5.6",
    confidence: "1.08",
    acceptable: "true"
  },
  {
    id: 2,
    name: "pci_status_cd_急诊",
    confidence: "1.05",
    acceptable: "true"
  },
  {
    id: 3,
    name: "conclision_angiography_type_冠脉三支病变",
    confidence: "1.01",
    acceptable: "true"
  },
  {
    id: 4,
    name: "pci_indication_cd_STEMI的紧急PCI治疗",
    confidence: "0.89",
    acceptable: "true"
  },
  {
    id: 5,
    name: "postp_bnp_pnml_group_>500",
    confidence: "0.82",
    acceptable: "true"
  },
  {
    id: 6,
    name: "postp_bnp_pnml_group_100-500",
    confidence: "0.82",
    acceptable: "true"
  },
  {
    id: 7,
    name: "cad_presentation_cd_STEMI(7天)",
    confidence: "0.79",
    acceptable: "true"
  },
  {
    id: 8,
    name: "pci_status_cd_早期",
    confidence: "0.64",
    acceptable: "true"
  },
  {
    id: 9,
    name: "cad_presentation_cd_Non-STEMI(7天)",
    confidence: "0.61",
    acceptable: "true"
  },
  {
    id: 10,
    name: "if_pior_cvd_1.0",
    confidence: "0.37",
    acceptable: "true"
  }
];


const table = new Tabulator("#tableContainer", {
  data: tabledata,
  height: "292px",
  layout: "fitColumns",
  printAsHtml: true,
  printCopyStyle: true,
  printHeader: "<h3>Feature Selection Results<h3>",
  columns: [{
      title: "",
      field: "id",
      width: 50
    },
    {
      title: "Feature",
      field: "name"
    },
    {
      title: "Confidence",
      field: "confidence",
      sorter: "number",
      align: "left",
      formatter: "progress",
      width: 400,
      formatterParams: {
        mix: 0,
        max: 1.1,
        color: ["#296FAB"],
        legend: true,
        legendColor: "#333333",
        legendAlign: "right"
      }
    },
    {
      title: "Acceptability",
      field: "acceptable",
      align: "center",
      editor: true,
      sorter: "boolean",
      formatter: "tickCross",
      width: 150
    },
  ],
});



const printTable = () => {
  table.print(false, true);

}
</script>

**Comment by aklaver** [comment]
@HongyuWang-2018 your question is not related to this issue. Please create a new issue and include the code you are using or better yet a jsFiddle/CodePen example.

**Comment by olifolkerd** [comment]
Hey all,

I have pushed a fix to the master branch to allow columns to be fully visible in print and html output if they have no field defined.

This will be included in todays patch release.

Cheers

Oli :)
