### ISSUE TITLE
persistentLayout: true and resizableColumns: false interaction

### ISSUE THREAD

**Issue by Zmimmy** [olifolkerd/tabulator#2287]
**Describe the bug**

If you have resizableColumns set to false, persistentLayout to true and layout to fitColumns reloading the page or resizing the window does not adjust the column size.

**Tabulator Info**
- Which version of Tabulator are you using?
4.4.0

- Post a copy of your construct object if possible so we can see how your table is setup

                    data: tableData,
                    layout: "fitColumns",
                    layoutColumnsOnNewData:true,
                    height:"100%", 
                    resizableColumns:false,
                    responsiveLayout:"hide",
                    persistentLayout:true,
                    index: "id",

**Expected behavior**

I would expect that if I had resizableColumns to false then table.redraw() or reloading the page would fit the columns to the table as happens when persistentLayout is false.

**Comment by olifolkerd** [comment]
Hey @Zmimmy 

In your usage case i would suggest that you just want to use a more detailed persistence configuration to exclude the column width.

If you have a look at the [v4.5 persistence documentation](http://tabulator.info/docs/4.5/persist) you will see that the persistence module has had an overhaul to give you far more control over what is persisted.

Cheers

Oli :)
