### ISSUE TITLE
ajax remote pagination url generation when url already have querystring parameter.

### ISSUE THREAD

**Issue by byoernn** [olifolkerd/tabulator#2288]
**Describe the bug**
my configuration:
```
ajaxURL: myurl?myquerystringparmeters
ajaxProgressiveLoad: "load",

```
so the default url generation will append "?page=1&size=20", but my url already have querystring Information, so my informations get corrupted.

It would be nice if you can handle this issue with your next Version.
my not so nice workaround actually:
```
ajaxURLGenerator: (url, config, params) => {
				var queryString = Object.keys(params).map(function (key) {
					return encodeURIComponent(key) + '=' + encodeURIComponent(params[key])
				}).join('&');
				
				return url + "&"+queryString;
			}
```

**Tabulator Info**
- Which version of Tabulator are you using? 4.4.0

**Expected behavior**
The parameters will be appended by
"?" if there is no querystring and by
"&" if querystring is already there.

**Comment by aklaver** [comment]
Seems to me if you are going the custom route then either:

1) Concatenate myurl?myquerystringparmeters outside the table. You are already building the components there, so I putting them together would seem to build the logical next step.

2) Continue to use ajaxGenerator, that is it's purpose in life.

**Comment by olifolkerd** [comment]
Hey @byoernn 

I have just pushed an update to the 4.5 branch that will allow tabulator to handle urls passed into the ***ajaxURL*** option that already contain parameters.

Version 4.5 should be released in the next few weeks.

Cheers

Oli :)

**Comment by byoernn** [comment]
Thank you very much for your answer and implementing my suggestion.
I will have a look at v4.5 the next days and what kind of cool updates will come 😀.

Kind regards
Björn Nast

Mit freundlichen Grüßen
Björn Nast

________________________________
