### ISSUE TITLE
blank items showing as &nbsp

### ISSUE THREAD

**Issue by dceejay** [olifolkerd/tabulator#2290]
**Describe the bug**

If I leave say a link data item blank - It gets replaced by `&nbsp`   - I assume it's meant to be `&nbsp;` 

**Tabulator Info**
- Which version of Tabulator are you using?
Dist file on github see links below

https://github.com/olifolkerd/tabulator/blob/master/dist/js/tabulator.js#L1915
https://github.com/olifolkerd/tabulator/blob/master/dist/js/tabulator.js#L1919
https://github.com/olifolkerd/tabulator/blob/master/dist/js/tabulator.js#L1927
https://github.com/olifolkerd/tabulator/blob/master/dist/js/tabulator.js#L1931

There may be others but I'm not familiar enough with the source to find them all.

**Additional context**

**Comment by olifolkerd** [comment]
Hey @dceejay 

Good spot, i have just pushed a fix for this to the master branch and will include it in a patch update this morning.

Cheers

Oli :)
