### ISSUE TITLE
Persistent Group

### ISSUE THREAD

**Issue by hfhbd** [olifolkerd/tabulator#2291]
Currently, you can save the sorting and the columns layout. It would be awesome, if you could save the group too.

groupBy:"gender", => Default State. Will be updated with table.setGroupBy("age"); and saved, so next time the table will be group by age.

persistentGroup:true, //Enable group persistence

**Comment by olifolkerd** [comment]
Hey @hfhbd 

Thanks for getting in touch.

Quite a few people have asked for persistence for different areas of the table. In the next release i will be adding configuration settings for the persistance module so you can choose which parts of the table you want to persist.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @hfhbd 

You will be happy to hear i have just pushed this functionality to the 4.5 branch and will include it in the release in a few weeks time.

Cheers

Oli :)
