### ISSUE TITLE
topCalc not display fully across a wide table (64 columns)

### ISSUE THREAD

**Issue by Malaysiatic** [olifolkerd/tabulator#2292]
**Describe the bug**
Hi Oli, great job with Tabuator, it is an awesome tool.

I just encountered an issue using the column count function in a table with 64 columns reading the data from a MySql.

The topCalc is only displaying about halfway across the table as I scroll. I have tried it on firefox and chrome and it has the same issue. All the data fields display correctly it is just the topCalc that is not fully displaying
Below is a sample of the code and I have attached a screenshot showing the issue

(On a side note, I have been trying to use the topCalc as a stand alone for summaries where it only displays the non empty cells in a column without all the column data, is this possible?)

Appreciate any input on both the above

**Tabulator Info**
Tabulator V4.1
(I tried to update to V4.4 but the table would not display and I got console errors so I reverted back to 4.1)
     `
     `<script>//custom max min header filter
var minMaxFilterEditor = function(cell, onRendered, success, cancel, editorParams){

    var end;

    var container = document.createElement("span");

    //create and style inputs
    var start = document.createElement("input");
    start.setAttribute("type", "number");
    start.setAttribute("placeholder", "Min");
    start.setAttribute("min", 0);
    start.setAttribute("max", 500);
    start.style.padding = "4px";
    start.style.width = "50%";
    start.style.boxSizing = "border-box";

    start.value = cell.getValue();

    function buildValues(){
        success({
            start:start.value,
            end:end.value,
        });
    }

    function keypress(e){
        if(e.keyCode == 13){
            buildValues();
        }

        if(e.keyCode == 27){
            cancel();
        }
    }

    end = start.cloneNode();

    start.addEventListener("change", buildValues);
    start.addEventListener("blur", buildValues);
    start.addEventListener("keydown", keypress);

    end.addEventListener("change", buildValues);
    end.addEventListener("blur", buildValues);
    end.addEventListener("keydown", keypress);

    container.appendChild(start);
    container.appendChild(end);

    return container;
    }

    //custom max min filter function
    function minMaxFilterFunction(headerValue, rowValue, rowData, filterParams){
    //headerValue - the value of the header filter element
    //rowValue - the value of the column in this row
    //rowData - the data for the row being filtered
    //filterParams - params object passed to the headerFilterFuncParams property

        if(rowValue){
            if(headerValue.start != ""){
                if(headerValue.end != ""){
                    return rowValue >= headerValue.start && rowValue <= headerValue.end;
                }else{
                    return rowValue >= headerValue.start;
                }
            }else{
                if(headerValue.end != ""){
                    return rowValue <= headerValue.end;
                }
            }
        }

      return false; //must return a boolean, true if it passes the filter.
      }
      </script>
      <div id="myan-table"></div>
       <script>$("#myan-table").tabulator({
    height:480, // set height of table (in CSS or here), this enables the Virtual DOM and improves 
    render speed dramatically (can be any valid css height value)
    layout:"fitData", //fit columns to width of table (optional)
    columns:[ //Define Table Columns
	    {title:"No", field:"id", headerFilter:"input"},
        {title:"Asha Region", field:"Asha_Region", headerFilter:"input", topCalc:"count"},
		{title:"Asha Loc id", field:"Asha_Loc_id", headerFilter:"input"},
		{title:"Asha Site Name", field:"Asha_Site_Name",headerFilter:"input"},
		{title:"Asha PO #", field:"Asha_PO_Num", headerFilter:"input"},
		{title:"Asha Project Name", field:"Asha_Project_Name", headerFilter:"input"},
        {title:"Asha Project Sow", field:"Asha_Project_Sow", headerFilter:"input"},
		{title:"Asha Cme Dependency", field:"Asha_Cme_Dependency", headerFilter:"input"},
		{title:"Asha Ti Summary", field:"Asha_Ti_Summary", headerFilter:"input"},
		{title:"FT Admin Ptw Type", field:"FT_Admin_Ptw_Type", headerFilter:"input"},
		{title:"FT Admin Ptw Applied", field:"FT_Admin_Ptw_Applied", headerFilter:"input"},
		{title:"FT Admin Ptw_Approved", field:"FT_Admin_Ptw_Approved", align:"left", 
    headerFilter:"input"},
        {title:"Asha Plan Week", field:"Asha_Plan_Week", headerFilter:"input"},
		{title:"Asha Actual Week", field:"Asha_Actual_Week", headerFilter:"input"},
		{title:"Ti Team", field:"Ti_Team", headerFilter:"input"},
		{title:"Ti Start", field:"Ti_Start", headerFilter:"input"},
		{title:"Ti Complete", field:"Ti_Complete",headerFilter:"input"},
		{title:"Site Integrated", field:"Site_Integrated", headerFilter:"input", topCalc:"count"},
		{title:"Ft Admin Photos", field:"Ft_Admin_Photos", align:"center", formatter:"tickCross", 
    headerFilter:"tickCross", headerFilterParams: 
   {"tristate":true},headerFilterEmptyCheck:function(value){return value === null}, 
    topCalc:"count"},
		{title:"Ft Admin Srs", field:"Ft_Admin_Srs", align:"center", formatter:"tickCross", headerFilter:"tickCross", headerFilterParams:{"tristate":true},headerFilterEmptyCheck:function(value){return value === null}, topCalc:"count"},
		{title:"Ft Admin Rbs Log", field:"Ft_Admin_Rbs_Log", align:"center", formatter:"tickCross", headerFilter:"tickCross", headerFilterParams:{"tristate":true},headerFilterEmptyCheck:function(value){return value === null}, topCalc:"count"},
		{title:"Ft_Admin_Uploaded_Date", field:"Ft_Admin_Uploaded_Date", headerFilter:"input"},
		{title:"Ft Admin Decomm Checklist", field:"Ft_Admin_Decomm_Checklist", headerFilter:"input", topCalc:"count"},
		{title:"Asha Site Keys Checklist", field:"Asha_Site_Keys_Checklist", headerFilter:"input", topCalc:"count"},
		{title:"Asha Rsa Actual", field:"Asha_Rsa_Actual", headerFilter:"input", topCalc:"count"},
		{title:"Remarks Decomm Manual_Atp_Rsa", field:"Asha_RemarksDecommManual_Atp_Rsa", headerFilter:"input"},
		{title:"Sft Pic", field:"Sft_Pic", headerFilter:"input", topCalc:"count"},
		{title:"Sft Smart Ordering", field:"Sft_Smart_Ordering", headerFilter:"input", topCalc:"count"},
		{title:"Sft RfAtp Sde Finished", field:"Sft_RfAtp_Sde_Finished", headerFilter:"input", topCalc:"count"},
        {title:"Sft RfAtp Uploaded", field:"Sft_RfAtp_Uploaded", align:"left", headerFilter:"input", topCalc:"count"},
		{title:"Sft Rfatp Approved Celcom", field:"Sft_Rfatp_Approved_Celcom", headerFilter:"input", topCalc:"count"},
		{title:"Sft Rfatp Final Ver", field:"Sft_Rfatp_Final_Ver", headerFilter:"input", topCalc:"count"},
		{title:"Sft Rfatp Remarks", field:"Sft_Rfatp_Remarks", headerFilter:"input", topCalc:"count"},
		{title:"Sft Sdd Pic", field:"Sft_Sdd_Pic", headerFilter:"input", topCalc:"count"},
		{title:"Sft Sdd Sde Finished", field:"Sft_Sdd_Sde_Finished", headerFilter:"input", topCalc:"count"},
		{title:"Sft Sdd Uploaded", field:"Sft_Sdd_Uploaded", headerFilter:"input", topCalc:"count"},
		{title:"Sft Sdd Approved Celcom", field:"Sft_Sdd_Approved_Celcom", headerFilter:"input", topCalc:"count"},
		{title:"Sft Sdd Final Ver", field:"Sft_Sdd_Final_Ver", headerFilter:"input"},
		{title:"Sft Sdd Remarks", field:"Sft_Sdd_Remarks", headerFilter:"input"},
		{title:"Asha Lmr Requested", field:"Asha_Lmr_Requested", headerFilter:"input", topCalc:"count"},
		{title:"Transportation Po Received", field:"Transportation_Po_Received", headerFilter:"input", topCalc:"count"},
		{title:"Transportation Po #", field:"Transportation_Po_Num", headerFilter:"input"},
		{title:"Transportation CoC Submitted", field:"Transportation_CoC_Submitted", headerFilter:"input"},
		{title:"Transportation CoC Approved", field:"Transportation_CoC_Approved", headerFilter:"input"},
		{title:"Transportation Invoice Sent", field:"Transportation_Invoice_Sent", headerFilter:"input", topCalc:"count"},
		{title:"Local Material Po Received", field:"Local_Material_Po_Received", headerFilter:"input", topCalc:"count"},
		{title:"Local Material Po #", field:"Local_Material_Po_Num", headerFilter:"input"},
		{title:"Local Material CoC Submitted", field:"Local_Material_CoC_Submitted", headerFilter:"input"},
		{title:"Local Material CoC Approved", field:"Local_Material_CoC_Approved", headerFilter:"input"},
		{title:"Local Material Invoice Sent", field:"Local_Material_Invoice_Sent", headerFilter:"input", topCalc:"count"},
		{title:"Services Po Received", field:"Services_Po_Received", headerFilter:"input", topCalc:"count"},
		{title:"Services Po #", field:"Services_Po_Num", headerFilter:"input"},
		{title:"Services CoC Submitted", field:"Services_CoC_Submitted", headerFilter:"input"},
		{title:"Services CoC Approved", field:"Services_CoC_Approved", headerFilter:"input"},
		{title:"Services Invoice Sent", field:"Services_Invoice_Sent", headerFilter:"input", topCalc:"count"},
		{title:"Asha Additional Works Sow", field:"Asha_Additional_Works_Sow", headerFilter:"input", topCalc:"count"},
		{title:"Asha Lmr Requested", field:"Asha_Lmr_Requested", headerFilter:"input"},
		{title:"Additional Works Po Received", field:"Additional_Works_Po_Received", headerFilter:"input", topCalc:"count"},
		{title:"Additional Works Po #", field:"Additional_Works_Po_Num", headerFilter:"input"},
		{title:"CME Start AC Week Num", field:"CMEStartACWeeknum", headerFilter:"input"},
		{title:"Additional Works CoC Submitted", field:"Additional_Works_CoC_Submitted", headerFilter:"input"},
		{title:"Additional Works CoC Approved", field:"Additional_Works_CoC_Approved", headerFilter:"input"},
		{title:"Additional Works Invoice Sent", field:"Additional_Works_Invoice_Sent", headerFilter:"input", topCalc:"count"},
		{title:"Remarks Additional Works Details", field:"Remarks_Additional_Works_Details", headerFilter:"input"},
	],
    
    });</script>`
    `

**Comment by Malaysiatic** [comment]
![tab-scroll](https://user-images.githubusercontent.com/15964202/63002517-aa275b80-bea8-11e9-851c-437f88e0b62b.PNG)

Screenshot of issue attached.
(apologies about code above, it didn't want to stay in its container)

**Comment by olifolkerd** [comment]
Hey @Malaysiatic 

Yes that is a known issue, you can use the ***.tabulator-calcs-holder*** css class to override the width of that element as a temporary workaround.

I would also query whether there is a better way to represent all that data as 64 columns is a lot to ask a user to scroll through, but i dont know your usage case.

Cheers

Oli :)

**Comment by Malaysiatic** [comment]
Hi Oli, thanks for the prompt reply :-)

I found tabulator-calcs-holder in tabulator_site.css, it was set to 400% so I changed it up to 1000% and the count loads all the way across the table now.

Problem solved :-)

fyi .... I did a table last month that had 79 rows in it and I agree with you that it is a lot of scrolling but this is was my boss was demanding, he wants every field of an excel tracker exactly the same online

**Comment by olifolkerd** [comment]
Hey @Malaysiatic 

I have pushed an update to the master branch to help with this.

It will be included in todays patch release.

Cheers

Oli :)
