### ISSUE TITLE
Blank link shows as &nbsp; ... not same as #2290

### ISSUE THREAD

**Issue by dceejay** [olifolkerd/tabulator#2293]
**Describe the bug**

If I set a column to be of type link and pass in no data it renders as `&nbsp;` (once fix for #2290 is applied) with a link to nowhere. 
![image](https://user-images.githubusercontent.com/5375409/63004823-2c952880-be73-11e9-88d9-7794b81d4d63.png)

This is because line 
https://github.com/olifolkerd/tabulator/blob/master/dist/js/tabulator.js#L16053
and then following that it renders that as sanitised text rather than html and then and adds a link...

A simple fix would be to still make that call but then add and extra check for that value

    if (label === '&nbsp;') { return; }

so it doesn't bother to render anything

**Tabulator Info**
Using the dist file 
https://github.com/olifolkerd/tabulator/blob/master/dist/js/tabulator.js#L16053

Not sure where it is in the main source. Possibly add it here
https://github.com/olifolkerd/tabulator/blob/master/src/js/modules/format.js#L170

**Expected behavior**

just don't render anything for a null link

**Comment by olifolkerd** [comment]
Hey @dceejay 

Thanks for the headsup that is deffinitly an issue.

I will include a fix in the next release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @dceejay 

Just a quick note for you, as ive noticed it in most of your suggestions, formatters and editors should always return something, you will run into errors if you start returning undefined values.

In this case the isue is not the fact it is a blank space it is just that it is being parsed before being returned from the formatter so the ampersand is being turned into a &amp; which means it is being redered as text.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @dceejay 

I have pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)
