### ISSUE TITLE
Invalid number of stars shows max

### ISSUE THREAD

**Issue by dceejay** [olifolkerd/tabulator#2294]
**Describe the bug**

If I pass in nothing / null to a column defined as stars I get the maximum star rating....
surely 0  (or nothing rendered) would be more sensible ?

**Tabulator Info**
Latest tabulator.js from here
https://raw.githubusercontent.com/olifolkerd/tabulator/master/dist/js/tabulator.js

**To Reproduce**
1) set a column as showing stars
2) send in blank , null, or text (e.g. "banana")

**Expected behavior**

Either show no stars - or leave the box completely blank (as for traffic light and progress.)

**Comment by dceejay** [comment]
I think adding 

                if (isNaN(value)) { return; }

 around here would fix it to leave it blank for invalid input.
https://github.com/olifolkerd/tabulator/blob/master/dist/js/tabulator.js#L16229
(whatever that equates to in the src side.)

**Comment by olifolkerd** [comment]
Hey @dceejay 

I agree with you there about representing it as no starts, i will add a fix in the next release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @dceejay 

I have pushed an update to the star formatter to show a value of zero stars for a non numeric value.

This will be included in todays patch release

Cheers

Oli :)
