### ISSUE TITLE
formatter:"textarea" for array items 

### ISSUE THREAD

**Issue by pkitcha** [olifolkerd/tabulator#2295]
Hi Oli,

I am having issue with displaying a multi line with array items.  The formatter:"textarea" was used with array data source and I expect to see each array item should be displayed with new line item.

**Example:**

My data source is  {"observationdate":["2019-08-11","2019-09-11","2019-10-11","2019-11-11","2019-12-11"]}

I expect that after applying formatter : "textarea", I should be able to see  data in my cell with 

2019-08-11
2019-09-11
2019-10-11
2019-11-11
2019-12-11

but what I got is 

2019-08-11,2019-09-11,2019-10-11,2019-11-11,2019-12-11

I have tried to use custom formatter to add <br/> at end of each array item. But I will encounter with row height issue (style with fixed height).

Do you have any feature that match with my request? or any suggestion ?

**Comment by olifolkerd** [comment]
Hey @pkitcha 

That is an odd expectation to have, the textarea formatter is for displaying text, it therefor expects a text input not an array.

You would need to use a custom formatter to lay things out as you ask. a simple join function should suffice:

```js
return cell.getValue().join("\n");
```

I Hope that helps,

Cheers

Oli :)

**Comment by pkitcha** [comment]
Thank you Oli. I can resolve my issue now
