### ISSUE TITLE
Order Groups by count(items)

### ISSUE THREAD

**Issue by hfhbd** [olifolkerd/tabulator#2298]
Currently, the table will be first sort and than group. I would like to group the data first, and than sort/order the groups by the number of their items to see the group with the most items at top/bottom. 
It would be nice, to add an ordering function to the grouping feature.
Or is a workaround available?

**Comment by olifolkerd** [comment]
Hey @hfhbd 

Im afraid that isnt possible in tabulator im afraid.

Cheers

Oli :)
