### ISSUE TITLE
Links not styled in themes - hard to see in dark themes

### ISSUE THREAD

**Issue by dceejay** [olifolkerd/tabulator#2299]
**Describe the bug**

On Chrome (at least) - any link is default styled (dark blue) - which is hard to see if you use the midnight theme 
![image](https://user-images.githubusercontent.com/5375409/63081986-f02dff00-bf3c-11e9-91bb-f19beb41054d.png)

The dev tools show this set of styles
![image](https://user-images.githubusercontent.com/5375409/63082224-8f52f680-bf3d-11e9-8745-bd92174b64fc.png)
So it is getting in ahead of yours

Maybe you need a 

    .tabulator a { color: $rowTextColor; }

or some definition to match the style... In all the scss files ?
(Or maybe you want to be more specific)

**Tabulator Info**
Latest on github 4.4.1 dist version

**To Reproduce**
  1. Add a link type column
  2. Use the tabulator_midnight.css theme

**Expected behavior**

I think it would be nicer if links were either the default text color (they are still underlined so you can tell it's a link) across all themes - Or at least fixed in the dark theme so it can be more visible.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome 
 - Version 77

**Comment by olifolkerd** [comment]
I intentionally don't style links as people tend to opt for site wide styling for links and I don't want to interfere with that.

You can easily add your own styling with a couple of lines of CSS

Cheers

Oli

**Comment by dceejay** [comment]
Indeed - OK.
