### ISSUE TITLE
Current Page

### ISSUE THREAD

**Issue by vmontal** [olifolkerd/tabulator#23]
In a large table with many pages, how can I get the current page to use it when I back to the table in the same page where there was the record I just handler

**Comment by olifolkerd** [comment]
Are you looking for a getPage function to return the current page number?

**Comment by vmontal** [comment]
Yes!
Valerio.Net

Get Outlook for iOS

    _____________________________

**Comment by olifolkerd** [comment]
I have added the **_getPage_** function that returns the number of the current page, as well as the **_pageLoaded_** callback that is called every time a page is loaded and is passed the number of the current page.

[See the pagination documentation for full details](http://olifolkerd.github.io/tabulator/docs/#pagination)
