### ISSUE TITLE
where can I get source of very first example (Site Home)?

### ISSUE THREAD

**Issue by blasterY** [olifolkerd/tabulator#2300]
where can I get source of very first example (Site Home)? 
with filter and buttons on top.

**Comment by olifolkerd** [comment]
It is litterally underneath it on the page

**Comment by blasterY** [comment]
Thanks -but the first row with filter and buttons does not appear.

**Comment by olifolkerd** [comment]
They are just normal DOM elements that call functions on the table. Tabulator only builds the table itself, the developer is responsible for adding any elements outside the table.

If you have a look at the examples section it shows you how to call the filter functions and row manipulation functions

Cheers

Oli

**Comment by blasterY** [comment]
Thank you; great framework!
