### ISSUE TITLE
Documentation Bug: Header Filter Example

### ISSUE THREAD

**Issue by hfhbd** [olifolkerd/tabulator#2301]
The real source code differs from the code of the example in the documentation of the Header Filter example (http://tabulator.info/examples/4.4?#filter-header).

Example (wrong) source code:

{title:"Favourite Color", field:"col", headerFilter:"input"},

Used source code:
 {title:"Favourite Color", field:"col", editor:"input", headerFilter:"select", headerFilterParams:{values:true}},

**Comment by olifolkerd** [comment]
Hey @hfhbd 

Thanks for letting me know, i will get that fixed in the documentation.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
The fix for this will go live later today.

Cheers

Oli :)
