### ISSUE TITLE
adding column at runtime to table with fitColumns doesnt recalculate table width to fit container. table.redraw(true) makes no difference

### ISSUE THREAD

**Issue by rhagstrand** [olifolkerd/tabulator#2302]
**Describe the bug**
A table with layout set to fitColumns, 3 columns where the last one has no width set to make its widh fill up all available space. Works fine when loading. Then I add a new column to table at runtime. After this I call redraw(true) on the table. But width is not recalculated instead the table "spills over" the containers width

**Tabulator Info**
4.4

    var rctable = new Tabulator("#rc-table", {
        data: rcTableData,
        movableColumns: true,
        movableRows: true,
        resizableRows: false,
        layout: "fitColumns",
        layoutColumnsOnNewData: true,
        columns: [
        { title: "ROLL", field: "roll", width: 200, editor: buttonEditor, formatter: "textarea" },
        { title: "SIGN", field: "sign", width: 100, editor: "textarea", formatter: "textarea" },
        { title: "NAMN", field: "namn", editor: "textarea", formatter: "textarea" }
        ]
    });

**Working Example**
Please include a JS Fiddle or Code Pen that demonstrates the problem, it is very hard to diagnose an issue from a simple description

**To Reproduce**
Load table above with some data.
Add a column at runtime with:

rctable.addColumn({ title: "Ny kolumn", field: "new_column", width: 150, editor: "textarea", formatter: "textarea" }, true, 1);
rctable.redraw(true);

**Expected behavior**
Tables last column width should be recalculated so whole table fills containers width perfectly which it does on load.

**Comment by dota2Pro** [comment]
Working Example
Please include a JS Fiddle or Code Pen that demonstrates the problem, it is very hard to diagnose an issue from a simple description also Stackoverflow

**Comment by olifolkerd** [comment]
Hey @rhagstrand 

This is by design, at the moment the calculation is only applied when the table is initially draw, additional column manipulation does not then trigger a resize to allow users to manipulate the table how they see fit without forcing the columns to fit.

I can see the usage case so will look at adding an option for this in a future release.

Thanks for your feedback

Cheers

Oli :)
