### ISSUE TITLE
column with formatter progress does not show progressbar

### ISSUE THREAD

**Issue by Smaele** [olifolkerd/tabulator#2303]
I am new to Tabulator and trying the examples, this is what I noticed:

**Description**
The column 'age' in the example table on your documentation page "Quickstart Guide" (using version 4.4)  does NOT show the progressbar unless you sort one of the columns. This also happens when I try this example on my localhost computer (using Firefox).

**Tabulator Info**
- Version 4.4

**Other**
This problem does not occur in version 4.1 (and possibly also not in version 4.2).

**Comment by olifolkerd** [comment]
Hey @Smaele 

Im afraid i cannot replicate the issue you are describing here, all the formatters are displaying correctly in the quickstart page when i view them.

Cheers

Oli :)
