### ISSUE TITLE
How to set the custom ajax loader element ?

### ISSUE THREAD

**Issue by Velunce** [olifolkerd/tabulator#2306]
Thanks for your project.
I want to know how to set custom ajax loading element?

**Comment by aklaver** [comment]
You are going to have to be more specific about what element you are talking about?

**Comment by olifolkerd** [comment]
Hey @Velunce 

you can use the ***ajaxLoader*** property in the column definition:
```js
var table = new Tabulator("#example-table", {
    ajaxLoader:"<div style='display:inline-block; border:4px solid #333; border-radius:10px; background:#fff; font-weight:bold; font-size:16px; color:#000; padding:10px 20px;'>Loading Data</div>"
}):
```

I hope that helps,

Cheers

Oli :)
