### ISSUE TITLE
drop-down arrow to expand the data is insensitive

### ISSUE THREAD

**Issue by yoyomule** [olifolkerd/tabulator#2307]
**Describe the bug**
In the group data function, clicking the drop-down arrow to expand the data is insensitive and requires multiple clicks to expand (this is also the case with other grouping functions). hope you can optimize it.Thanks.

**Tabulator Info**
- Which version of Tabulator are you using?
  v4.4.1 demo

**Working Example**
http://tabulator.info/examples/4.4?#sorters
Grouping Data demo

**Screenshots**
![Rec 0034~3](https://user-images.githubusercontent.com/10000818/63204737-82fda380-c0cd-11e9-9473-8e24a4613d41.gif)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser :chrome

**Comment by olifolkerd** [comment]
Hey,

It isn't insensitive it just requires u to click directly on the arrow to toggle the group.

It is on the roadmap to make this easier to click on in the next release.

Cheers

Oli
