### ISSUE TITLE
is it possible to implement excel like filter using tabulator? if yes please reply 

### ISSUE THREAD

**Issue by balajis-13395** [olifolkerd/tabulator#2308]
Please ask questions on www.stackoverflow.com the issues list is now reserved for feature requests and bug reports.

Cheers

Oli :)

**Comment by aklaver** [comment]
The chances of getting an answer are in direct proportion to information provided. In other words I have no idea what you are asking.

**Comment by balajis-13395** [comment]
sorry, i mean i need to implement multi select checkbox filter in tabulator .is  that possible ?

**Comment by aklaver** [comment]
I have not done it, but I'm guessing you could build a custom filter. 
See:
http://tabulator.info/examples/4.3#filter-header
for an example of building a complex filter.

**Comment by olifolkerd** [comment]
@balajis-13395 Yes you should be able to add a custom header filter to do this, the example that @aklaver  has pointed you to includes a filter with two input elements in that should give you a good start

Cheers

Oli :)
