### ISSUE TITLE
Tree Structure

### ISSUE THREAD

**Issue by GonzaloCenteno** [olifolkerd/tabulator#2310]
Can I have two or three columns to display child tables?
for example :
http://www.jtable.org/Demo/MasterChild

**Comment by aklaver** [comment]
http://tabulator.info/examples/4.3#nested-tables

**Comment by 805bluebell** [comment]
Yeah, most of the things in that jTable example can be achieved using nested tabulator tables. Please try that.

**Comment by brimimc** [comment]
It's not obvious from the example that it would be possible to collapse/hide the nested table like in the jtable example. Is it possible to hide/show the nested table?

**Comment by olifolkerd** [comment]
@brimimc you can use the row formatter to do this, simply add a toggle to the row that you can click to hide/show the table
