### ISSUE TITLE
How to show number of filtered rows in header field?

### ISSUE THREAD

**Issue by blasterY** [olifolkerd/tabulator#2311]
how can I show the number instead of a header title?

**Comment by olifolkerd** [comment]
Hey @blasterY 

Have a look at the [Filter Callbacks](http://tabulator.info/docs/4.3/callbacks#filter) these will tell you when the table has been filtered.

you would then need to replace the column definition for the column header you want to replace with an updated one with the new title.

Cheers

Oli :)
