### ISSUE TITLE
Formatter Money Not Working When Using FormatterParam

### ISSUE THREAD

**Issue by BenTongue** [olifolkerd/tabulator#2312]
Hi all,

When I use formatter:"money" and : function(cell, formatterParams) { on the same column the formatter money stops working, see below code:

**Tabulator Info**
Version 4.4

`{title:"Outstanding Amount", field:"Out_Amount", formatter:"money", align:"right", sorter:"number", width:80,  mutator:nullToStringOut, headerFilter:"input", formatter: function(cell, formatterParams) {
          var Out_Amount = cell.getRow().getData().Out_Amount;
        if (cell.getData().Out_Amount < 0 || cell.getData().Out_Amount > 1) {
            cell.getElement().style.backgroundColor = "#185f691f";         
            return Out_Amount;
        } else if (cell.getData().Out_Amount == 0){
            cell.getElement().style.backgroundColor = "#3c940d45";  
            return Out_Amount;
         } else {
            cell.getElement().style.backgroundColor = "#e0131330";
            return 'Not in CW';
        }
          },
      },`

As you can see in the Outstanding amount it doesn't work.

![image](https://user-images.githubusercontent.com/49704263/63394354-ae043200-c402-11e9-814c-3676090f3245.png)

Regards,
Ben

**Comment by olifolkerd** [comment]
Hey @BenTongue 

The column definition is a standard JavaScript object. you can define the same property twice, the second one will overwrite the first one

Cheers

Oli :)
