### ISSUE TITLE
editor:"autocomplete" to work the same as editor:"Select"

### ISSUE THREAD

**Issue by BenTongue** [olifolkerd/tabulator#2314]
Hi all,

Currently in my table, I have the below select feature:

`{title:"Comments", field:"Comments", sorter:"string", editorParams:CommentsLookup, editor:"select", width:80,  headerFilter:"input"},`

The editorParams:CommentsLookup calls a fucntion which returns a list. When I try and do the same thing with Autocomplete it doesn't work? It returns nothing:

``{title:"Comments", field:"Comments", sorter:"string", editorParams:CommentsLookup, editor:"autocomplete", width:80,  headerFilter:"input"},``

Surly this should work in the same way? I like autocomplete as you can type and select where as the select function is purly for selecting.

I also tried the below which doesn't work:

`{title:"Comments", field:"Comments", sorter:"string", editor:"autocomplete", width:80,  headerFilter:"input", editorParams:{`
       `showListOnEmpty:true, //show all values when the list is empty,
       freetext:false, //allow the user to set the value of the cell to a free text entry
       allowEmpty:true, //allow empty string values
       values:CommentsLookup, //create list of values from all values contained in this column
       sortValuesList:"asc", //if creating a list of values from values:true then choose how it should be sorted
        }
      },`

My function looks like the following:

`var CommentSelect;`
`$.ajax({
        url: url,
        type: "post",
        success: function(response, textStatus, xhr){
        CommentSelect = JSON.parse(response) 
        },
});`
`function CommentsLookup(){
    return CommentSelect;
}`

Your help would be much appreciated.

**Comment by olifolkerd** [comment]
That isn't returning a list. Because you are calling an Ajax function which returns asynchronously you are returning undefined because the lookup function will return straight away.

At the moment the lookup functions do not support asynchronous lookup.

This will be comming in future

Cheers

Oli

**Comment by BenTongue** [comment]
Okay thanks,

Look forward to the addtion or better still if the select options was also typable that would be great.

Regards,
Ben
