### ISSUE TITLE
group callbacks 'this' binding

### ISSUE THREAD

**Issue by sibsibsib** [olifolkerd/tabulator#2316]
**Describe the bug**
Event handlers for the groups (eg `groupClick`) are called without binding to the tabulator instance, so 'this' appears in the callback to be the table options object. 

eg: https://github.com/olifolkerd/tabulator/blob/master/src/js/modules/group_rows.js#L138

**To Reproduce**
1. Create a table with groups and set the `groupClick` handler option
2. `console.log(this)` in the handler
3. you'll see the output is the table.options object

**Expected behavior**
I would expect this to be bound to the table in the same way that eg `cellClick` handler is

**Comment by olifolkerd** [comment]
Hey @sibsibsib 

Good suggestion, i will add that to the roadmap for the next release

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @sibsibsib 

I have pushed this functionality to the 4.5 branch which will be released in a few weeks time.

Cheers

Oli :)
