### ISSUE TITLE
The example tabulator for angular does not work: unrecognized type library

### ISSUE THREAD

**Issue by pgatto70** [olifolkerd/tabulator#2317]
**Describe the bug**
Hi everyone, I'm trying to use "tabulator 4.4.1" in an "Angular 5.2.5" project created with Visual Studio 2019. The following error occurs after installing tabulator with the "npm install tabulator-tables - save" command:
Error   TS2306  (TS) The file '../ClientApp/node_modules/@types/tabulator-tables/index.d.ts' **is not a module**

The error is reported on the import statement:
import {Tabulator} from 'tabulator-tables';

import { Component, Input, OnChanges, SimpleChanges } from '@angular/core';
import Tabulator from 'tabulator-tables';   <--  ERROR  !!!!!!

/**
 * This is a wrapper class for the tabulator JS library.
 * For more info see http://tabulator.info
 */
@Component({
  selector: 'app-tabulator-table',
  templateUrl: './tabulator-table.component.html',
  styleUrls: ['./tabulator-table.component.css']
})
export class TabulatorTableComponent implements OnChanges {

**Expected behavior**
After installing the library the types are recognized!!!

**Screenshots**
![Tipi Tabulator non riconosciuti](https://user-images.githubusercontent.com/54444006/63599024-041ed400-c5c1-11e9-84fe-2caf9c2616a0.PNG)

**Desktop (please complete the following information):**
 - OS: Win 10 Pro
 - chrome
 - 76.0.3809.100 (Build ufficiale) (a 64 bit)

The code reported was taken from an example of your site at the link "http://tabulator.info/docs/4.4/frameworks".

Tabulator seems like a great tool to me, I've already tested it in an html page and it works. I need to know if the 4.4.1 version libraries are compatible with angular 5.2.5 or there is a hole in the type library "node_modules/@types/tabulator-tables/index.d.ts". 

Thank you

**Comment by thiago123789** [comment]
@pgatto70 Do you already have added the style and script reference in `angular.json` file?
 
like this:
```JSON
...
"styles": [
              ...
              "node_modules/tabulator-tables/dist/css/tabulator.min.css",
 ],
 "scripts": [
              ..,
              "node_modules/tabulator-tables/dist/js/tabulator.min.js"
 ]
...
```

**Comment by pgatto70** [comment]
if I insert the two instructions, the home page no longer opens and only a few minutes later the following error appears:
Internal Server Error
-------------------------------

An unhandled exception occurred while processing the request.
IOException: The server returned an invalid or unrecognized response.
System.Net.Http.HttpConnection.FillAsync ()

HttpRequestException: An error occurred while sending the request.
System.Net.Http.HttpConnection.SendAsyncCore (HttpRequestMessage request, CancellationToken cancellationToken)

HttpRequestException: Failed to proxy the request to http: // localhost: 50568 /, because the request to the proxy target failed. Check that the proxy is running and accepting requests to http: // localhost: 50568 /.

The underlying exception message was 'An error occurred while sending the request.'. Check the InnerException for more details.
Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest (HttpContext context, HttpClient httpClient, Task <Uri> baseUriTask, CancellationToken applicationStoppingToken, bool proxy404s)

Stack Query Cookies Headers
IOException: The server returned an invalid or unrecognized response.
System.Net.Http.HttpConnection.FillAsync ()
System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync (bool foldedHeadersAllowed)
System.Net.Http.HttpConnection.SendAsyncCore (HttpRequestMessage request, CancellationToken cancellationToken)

HttpRequestException: An error occurred while sending the request.
System.Net.Http.HttpConnection.SendAsyncCore (HttpRequestMessage request, CancellationToken cancellationToken)
System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync (HttpConnection connection, HttpRequestMessage request, bool doRequestAuth, CancellationToken cancellationToken)
System.Net.Http.HttpConnectionPool.SendWithRetryAsync (HttpRequestMessage request, bool doRequestAuth, CancellationToken cancellationToken)
System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (Task <HttpResponseMessage> sendTask, HttpRequestMessage request, CancellationTokenSource cts, bool disposeCts)
Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest (HttpContext context, HttpClient httpClient, Task <Uri> baseUriTask, CancellationToken applicationStoppingToken, bool proxy404s)

HttpRequestExce

**Comment by merturl** [comment]
I solved it by add "export" in @types/tabulator-tables/index.d.ts
![image](https://user-images.githubusercontent.com/23473356/66899678-5a931680-f036-11e9-8c8f-4867857dc603.png)

**Comment by pgatto70** [comment]
Now it works for me too. Thank you!

**Comment by MBerka** [comment]
@merturl 's fix without modifying the type library:
Allow types to be found in `src/`: tsconfig.json (as of TS 4.3, but `typeRoots` has existed for years):
```json
{
  "compilerOptions": {
    "typeRoots": ["src/@types", "node_modules/@types"], /* src/@types to override tabulator-tables definition. */
  }
}
```
Then add `src/tabulator-tables.d.ts` (not found when in `src/@types/`, and needs to [match the library name](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html#testing-your-types) so that Tabulator class is available there):
```typescript
declare module "tabulator-tables" {
  export = Tabulator; 
}
```
