### ISSUE TITLE
Make all the pagination buttons configurable

### ISSUE THREAD

**Issue by cantstoplovingu** [olifolkerd/tabulator#2318]
I want to use custom buttons in pagination footer but didn't find any demo to implement all of the default change events.

Is it possible to make all the pagination buttons configurable? 
In this way, I can make a custom pagination footer like below without tears😭.

***
![image](https://user-images.githubusercontent.com/21187889/63689580-ee1d4780-c83c-11e9-8367-ac2fdd6bc148.png)
***

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @cantstoplovingu 

you can define a custom footer element and put whatever buttons you like in there, there are callbacks and functions for all aspects of pagination that you can link the buttons back to

Checkout the [Pagination Documentation](http://tabulator.info/docs/4.4/page) and [Footer Documentation](http://tabulator.info/docs/4.3/layout#footer) for more information

Cheers

Oli :)
