### ISSUE TITLE
Initial sort not included in AJAX request when using custom request function

### ISSUE THREAD

**Issue by ericmcpheron** [olifolkerd/tabulator#2320]
**Describe the bug**
I am attempting to use server-side sorting with Tabulator and noticed the initialSort value is not included in the request parameters when using a custom request function. This only happens on first load. Once data is loaded, clicking on the table headers initiates an AJAX request and sorter parameters are set properly.

**Tabulator Info**
- Which version of Tabulator are you using? Latest version 4.4.1
- Post a copy of your construct object if possible so we can see how your table is setup
`
this.tabulator = new Tabulator(this.$refs.tabulator, {
      ajaxSorting: true,
      ajaxRequestFunc: this.handleRequest(),
      columns: [
        { field: 'id', title: 'ID' },
        { field: 'first_name', title: 'First' },
        { field: 'last_name', title: 'Last' },
        { field: 'email', title: 'Email' },
        { field: 'avatar', title: 'Avatar' }
      ],
      data: [],
      index: 'id',
      initialSort: [{ column: 'email', dir: 'asc' }]
    })
`

**Working Example**

[https://jsfiddle.net/nrpg9bm1/](https://jsfiddle.net/nrpg9bm1/)

**To Reproduce**
1. See JsFiddle.
2. Open Developer Tools
3. Click on the Load Data button.
4. In the console output, "params=" contains the parameters passed in for the AJAX request and "getSorters" is the actual table sorters.

Please note this is a example to demonstrate the AJAX request parameters. The server doesn't do any sorting.

**Expected behavior**
Expected initialSort value to be included with initial request.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Firefox
 - Version: Latest

**Additional context**
I am using VueJS and calling Tabulator from within it.

**Comment by olifolkerd** [comment]
Hey @ericmcpheron 

The issues is because of the way your table is setup, the initialSort is used on when the table is first setup (it does an initial load when the table is instantiated) which is when the initialSort is used, but you dont provide a URL so the sort is done on the blank array.

If you are going to call the setData function then you would want to call the setSort function first and define the table sort.

I hope that makes sense

Cheers

Oli :)

**Comment by ericmcpheron** [comment]
Ah that makes sense. Thanks @olifolkerd
