### ISSUE TITLE
Dragging Rows or Cells outside Tabulator to any HTML Entity

### ISSUE THREAD

**Issue by rexxitall** [olifolkerd/tabulator#2321]
**Is your feature request related to a problem? Please describe.**
I store code snippets in a database which are presented as Tabulator table. So The table contains the snippet id and the snippet name.
Now i just want to drag such a header out of tabulator and let it drop on a textarea or in my case into a codemirror window. For this action i need the dragged "whatever" which will provide the table row id (to be able to fetch the real code piece by a database query)

**Describe the solution you'd like**
Some kind of hook or event which provides the on drag and if possible also the ondrop event in Tabulator

**Describe alternatives you've considered**
Forget about tabulator as general solution and implement a listbox :( but then all other goodies are also gone. Hacking Tabulator itself is also not really a option. First i am not THAT good in JS and second it might be others which like the same idea. So it should become a normal way to deal with.
**Additional context**

**Comment by olifolkerd** [comment]
Hey @rexxitall 

Thanks for the suggestion,

I think that is a really interesting idea, i will look at adding it to the roadmap to be included in a future release.

Cheers

Oli :)

**Comment by rexxitall** [comment]
Hi Olli, i was able to hack on the cell formatter to get something like that work (i just add the nedded attributes and the dragstart event...). The problem is that Tabulator has some kind of own ideas how to handle drag and drop which collides. I guess some event hussle. It slows down dramatically. You already drags rows to other tables. How about use that mechanism and just set the cells of the rows as data source. Or if more rows are selected create a virtual table. The user can now do with this data on drop he needs. Single cell drag is also a theme. Sometimes i just need one value from a steel table and for sure i want to drag the cell in my calculation sheet. So i am a bit curious with what kind of soolution you will comes up :) Thanks for the work and have a nice day :)

**Comment by olifolkerd** [comment]
Hey @rexxitall 

I have just pushed the functionality to drag a row onto an external element to the 4.7 branch which will be released later today.

Cheers

Oli :)
