### ISSUE TITLE
Download to XLSX doesn't includes nested data

### ISSUE THREAD

**Issue by 805bluebell** [olifolkerd/tabulator#2323]
The download to XLSX or PDF function doesn't work well with data tree or nested data.
It just doesn't show the nested data in the output file.

I am using version 4.0.
My table construct looks like this.
```
var table = new Tabulator("#example-table", {
    data:tableDataNested,
    dataTree:true,
    dataTreeStartExpanded:true,
    groupBy: "name",
    columns:[
      {title:"Name", field:"name", responsive:0},
      {title:"Applied", field:"applied", bottomCalc: nestedCalc, bottomCalcParams: {field: "applied"}},
      {title:"Screened", field:"screened", bottomCalc: nestedCalc, bottomCalcParams: {field: "screened"}},
      {title:"Interviewed", field:"interviewed", bottomCalc: nestedCalc, bottomCalcParams: {field: "interviewed"}},
    ],
    footerElement: "<button id='download-xl' onclick='downXL();'>Download XL</button>",


});
$(document).on('click', "#download-xl", downXL);
```

A quick running example is here https://jsfiddle.net/opankajkumar/Lzpdk1jm/7/

The table gets rendered when you hit run. Then press "Download XLSX" & view the downloaded file.

I expect exact layout as it is seen in the table with all data in XLSX file.

OS: Windows 10
Browser: Mozilla Firefox 68.0.2

**Comment by 805bluebell** [comment]
I have tried using dataset & options as in documentation & found that it indeed is a problem with nested data trees.
[1](https://jsfiddle.net/opankajkumar/hobzn17y/8/)

**Comment by olifolkerd** [comment]
Hey @805bluebell 

This is a known limitation, at the moment tree data is not available in all of the Tabulator modules,

This functionality will be coming in later releases

Cheers

Oli :)

**Comment by JAIC-be** [comment]
Has this been included yet? Or is there a way to specify the level in the data tree for download?
