### ISSUE TITLE
Add column.moveFirst() and column.moveLast() method, or column.move(0, 1, 2, 3...)

### ISSUE THREAD

**Issue by BernhardBaumrock** [olifolkerd/tabulator#2324]
**Is your feature request related to a problem? Please describe.**

Moving columns to the first or last position seems a little complicated... I'm working with lots of dynamic columns that are set from the AJAX datasource. I want to add a column with several action icons (show, trash, etc). That's my workaround:

```
table.addColumn(...); // this adds my new column
var columns = table.getColumns(); // get all columns
var col = columns[columns.length-1]; // get the newly added column
col.move(columns[0]); // move it to the first position
```

**Describe the solution you'd like**
```
table.addColumn(...);
var columns = table.getColumns();
var col = columns[columns.length-1];
col.moveFirst();
// or via index
col.move(0);
```

Thx!

**Comment by olifolkerd** [comment]
Hey @BernhardBaumrock 

Thanks for your suggestion, 

i dont really think that saves much code and it would not be consistent with any of the other move functionality so at this point i would not be looking to add it to Tabulator

Cheers

Oli :)
