### ISSUE TITLE
Make addColumn return the column object

### ISSUE THREAD

**Issue by BernhardBaumrock** [olifolkerd/tabulator#2325]
**Is your feature request related to a problem? Please describe.**

Yes and no. I'm using this workaround:
```
table.addColumn(...);
var columns = table.getColumns();
var col = columns[columns.length-1];
```

**Describe the solution you'd like**

If addColumn() returned the column it would be easier:

```
var col = table.addColumn(...);
```

**Additional context**

If https://github.com/olifolkerd/tabulator/issues/2324 also worked it would be as simple as this:

```
table.addColumn(...).moveFirst();
```

Thx!

**Comment by olifolkerd** [comment]
Hey @BernhardBaumrock 

Thanks for the suggestion.

to be consistent with other similar functions it should return a promise that resolves when the column has been added and passes the column component into the then function.

I will look at adding this in the next release

Cheers

Oli :)

**Comment by BernhardBaumrock** [comment]
Thx

**Comment by olifolkerd** [comment]
If you leave the issue open I can track it and will let you know when the feature is added

**Comment by olifolkerd** [comment]
Hey @BernhardBaumrock 

I have just pushed an update for this to the 4.5 branch which will be released in a few weeks.

The function now returns a promise that resolves with the column component when it has been fully processed

```js
table.addColumn([{title:"Name", field:"name"}])
.then(function(column){
    //column - the component for the newly created column
    //run code after column has been added
})
.catch(function(error){
    //handle error adding column
});
```

Cheers

Oli :)

**Comment by BernhardBaumrock** [comment]
Great, thx :)
