### ISSUE TITLE
Please add column width options auto + expand

### ISSUE THREAD

**Issue by BernhardBaumrock** [olifolkerd/tabulator#2327]
**Is your feature request related to a problem? Please describe.**

I wonder why there is no options for `auto` and `expand` column widths like shown here: https://getuikit.com/docs/width#auto-and-expand

Imagine a table like this:

![image](https://user-images.githubusercontent.com/8488586/63847013-3c416080-c98d-11e9-9a85-83037227170c.png)

It would be great to be able to set the first column to fit its content while some other column expands to its maximum (eg the "test" column).

I've tried `width: '1%'` but that cuts off some content in the cell. Setting the width manually works, but as I'm adding those action buttons via PHP and there can be 1, 2, 3 ... 5 buttons the width is always different.

**Comment by BernhardBaumrock** [comment]
Maybe naming it "fitData" and "expand" would make more sense. I've just tried setting width: 'fitData' on the column and this is the result:
![image](https://user-images.githubusercontent.com/8488586/63849053-790f5680-c991-11e9-9239-d8afe5c74171.png)

**Comment by 805bluebell** [comment]
> 
> 
> Maybe naming it "fitData" and "expand" would make more sense. I've just tried setting width: 'fitData' on the column and this is the result:
> ![image](https://user-images.githubusercontent.com/8488586/63849053-790f5680-c991-11e9-9239-d8afe5c74171.png)

So, you have achieved what you wanted using `fitData`

**Comment by BernhardBaumrock** [comment]
No, see the headings in the screenshot, they are totally broken. It SEEMS to work on the body rows on first sight, but you can also see a horizontal scrollbar that should not be there (because the table is set to layout 'fitColumns')

**Comment by 805bluebell** [comment]
It would be great if you share how you have initialised the table & how data is fed. A jsfiddle or codepen would be even better.

**Comment by BernhardBaumrock** [comment]
Thx for your time! https://jsfiddle.net/baumrock/04vf2ghd/7/

**Comment by 805bluebell** [comment]
Instead of setting just width you can choose to set widthGrow to some value. Refer docs tabulator.info/docs/4.1/layout
That will make sure to add some space which you want in the first column.
See https://jsfiddle.net/opankajkumar/g07p5qw6/13/

And if you are sure that the first column will have only these many elements always, just set width to some good value.

**Comment by BernhardBaumrock** [comment]
Thx, but your fix does not work:
![image](https://user-images.githubusercontent.com/8488586/63920328-e0381400-ca40-11e9-8e9c-1dd3a29f75c5.png)
![image](https://user-images.githubusercontent.com/8488586/63920348-ed550300-ca40-11e9-9702-cb49c1c61992.png)
On small screens the content of the first column is cut off, on large screens it is too wide. I want a column that has a fixed width that is based on the content. All other columns should adjust the width dynamically to take the full width of the window.

lets take this simple example:

```
x x x | description              | 10 | 20 | 30 |
```

Ideally 10, 20, 30 would be fixed width (eg 100px), xxx would be auto (minimum width based on content) and description would be "expand" to take the full width.

At the moment the best option seems to be setting a fixed width. My problem is - as I've mentioned already - that the number of items in the first column (the number of `x` in the example above) is dynamically coming from PHP. And some of those items are just an icon while others have a label. So the width can be totally different from grid to grid.

**Comment by BernhardBaumrock** [comment]
Using the `fitData` option on the column (not the table) is ALMOST working:
![fitdata](https://user-images.githubusercontent.com/8488586/63921080-6f91f700-ca42-11e9-87b3-51483592d636.gif)

If the table headings where aligned with the columns this would be exactly what I need :)

**Comment by BernhardBaumrock** [comment]
@olifolkerd No comment why you are closing this issue? :(
