### ISSUE TITLE
Cannot copy data without headers

### ISSUE THREAD

**Issue by mstlaurent-paradigm** [olifolkerd/tabulator#2328]
**Describe the bug**
When using the clipboard module, there is no way to copy data without including the header. Both configuration options dealing with the behaviour do not seem to work.

**Tabulator Info**
- Tabulator 4.4.1
- See JSFiddle for Tabulator constructor

**Working Example**
https://jsfiddle.net/mstlaurent_paradigm/965mdoLn/

**To Reproduce**
1. Select one or multiple rows in the table
2. Copy selected data using Ctrl + C
3. Paste the data in any text editor

**Expected behavior**
Pasted data does not include header

**Screenshots**
![image](https://user-images.githubusercontent.com/12598169/63856354-6421cb80-c96f-11e9-9500-01c187651b06.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 68, Chrome 76, Edge 44

**Additional context**
Note that both ways of excluding headers have been tried, and they have different behaviours:
* Using clipboardCopyHeader, which is deprecated, does nothing. The headers still appear.
* Using the new clipboardCopyConfig option creates a stranger behaviour, where empty lines are copied instead of the actual data. The right number of rows are copied, but they're all empty.

**Comment by olifolkerd** [comment]
Hey @mstlaurent-paradigm 

That looks like it might be a bug, i will look into fixing that for the next release.

Thanks for the heads up

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @mstlaurent-paradigm 

I have pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)
