### ISSUE TITLE
Vue component on custom formatter.

### ISSUE THREAD

**Issue by dluague** [olifolkerd/tabulator#2330]
Is it possible to return vue component on custom formatter?

**Comment by dluague** [comment]
Never mind i found a solution for this. Thanks to https://css-tricks.com/creating-vue-js-component-instances-programmatically/

```js
import IPs from '@/components/IPs.vue';
import Vue from 'vue';
...
{
    title: 'IP',
    field: 'ips',
    formatter({_cell}) { console.log(_cell.value);
        var ComponentClass = Vue.extend(IPs);
        var instance = new ComponentClass({
            propsData: {ips: _cell.value}
        });
        instance.$mount();

        return instance.$el;
    },
    minWidth: 200,
    variableHeight: true,
},
```

**Comment by suhailibnnisar** [comment]
Doesn't work in Vue3, any solutions to it?

**Comment by amkatyshev** [comment]
Maybe someone is using NuxtJS

I want to use the same approach that @dluague suggested.
But the problem is that when`instance.$mount();` is called, the component is not initialized with the Nuxt context (there are no Nuxt module properties in the mounted component)

Maybe someone knows how to solve this problem in NuxtJS?

P.S. Also I created issue for nuxt repo: https://github.com/nuxt/nuxt.js/issues/10205

**Comment by TheSecondCore** [comment]
This should really be a part of the Vue documentation, assuming it doesn't have any performance pitfalls.

**Comment by TheSecondCore** [comment]
If you need VueX, i18n, router or other context in the injected component, add `parent: this` to the class instantiation, like so:

```javascript
const instance = new ComponentClass({
    propsData: {ips: _cell.value},
    parent: this
});
```

**Comment by jorge-koki** [comment]
In Vue 3


`import BtnTabulatorComp from "src/components/Tabla/BtnTabulatorComp.vue";`

columns

```
{
    title: "Eliminar",
    field: "age",
    hozAlign: "center",
    formatter({ _cell }) {
      const div = document.createElement("div");
      const instance = createApp(BtnTabulatorComp, {
        cell: _cell,
        select: (val) => _select(val),
      }).mount(div);
      return instance.$el;
    },
```


BtnTabulatorComp 

```
<script setup>
import { onMounted } from "vue";

const props = defineProps(["cell", "select"]);

onMounted(() => {
  console.log("props", props.cell);
});

function returnData() {
  return props.select(props.cell.value);
}
</script>

<template>
  <div>
    <button @click="returnData()">Hey</button>
  </div>
</template>

<style scoped>
.link {
  text-decoration: none;
}
</style>

```
