### ISSUE TITLE
New column move API in 4.4?

### ISSUE THREAD

**Issue by hrstoyanov** [olifolkerd/tabulator#2332]
**Describe the bug**
Reading the release notes for 4.4 and the new programmatic column movement API, specifically the last argument (boolean). 

For the table component the release notes states:
 ```A value of false will cause to the column to be placed after the target column, a value of true will result in the column being placed before the target```

, but for the column component it states: 

```A value of false will cause to the column to be placed before the target column, a value of true will result in the column being placed after the target```

Is the "before"/"after"  deliberately confusing, or an error?

**Tabulator Info**
4.4.4

**Comment by olifolkerd** [comment]
Thanks for the info, i will have a look through the documentation

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @hrstoyanov 

The component documentation was right, i have pushed some updates to the table documentation and will make them live with other website updates later today.

Cheers

Oli :)
