### ISSUE TITLE
Documentation: Wrong selector in 'Trigger Copy Programmatically' example

### ISSUE THREAD

**Issue by mstlaurent-paradigm** [olifolkerd/tabulator#2333]
**Describe the bug**
The documentation includes the following code snippet, which is invalid: 
`table.copyToClipboard("selection"); //copy the currently selected rows to the clipboard`
The proper selector should be 'selected'

http://tabulator.info/docs/4.3/clipboard#copy

**Comment by olifolkerd** [comment]
Hey @mstlaurent-paradigm 

Thanks for letting me know,

I will get that fixed

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @mstlaurent-paradigm 

I have pushed an update to fix the docs for this function, it will be included in the website update later today.

Cheers

Oli :)
