### ISSUE TITLE
`renderComplete` callback is being called before table render complete

### ISSUE THREAD

**Issue by LizaKis** [olifolkerd/tabulator#2334]
**Describe the bug**
I've faced with an issue, when table is being rendered improperly on the slow internet. The headers and bottom part of the table are cut out, and the rows are rendered half of their real height.
I followed the approach of calling redraw() table as suggested in documentation ( http://tabulator.info/faq). I put `table.redraw()` call in the promise returned from replaceData method():

```js
_this._table.replaceData(data).then(function() {
       _this._table.redraw()
})
``` 
 
but it didn't help. And I checked that my table is always visible.
So then I put this call in the `renderComplete()` callback method, but it either didn't help.
Then I debugged and figured out that `renderComplete()` is being called before table is rendered (no tabulator styles applied so far). 

**Tabulator Info**
- Which version of Tabulator are you using?
4.4.1
- Post a copy of your construct object if possible so we can see how your table is setup
```new Tabulator('#my-table', {
    layout: "fitColumns",
    columns: columns,
    tooltipsHeader: true,
    tooltips: true,
    renderComplete:function(){
        this.redraw();
    }
})```

**Comment by olifolkerd** [comment]
Hey @LizaKis 

The symptoms you are describing suggest that you are trying to load data into a table that is not yet visible.

Calling the redraw function when it has finished loading the data will not help if the table is still hidden, it needs to be done when the table is made visible.

If you can create a JS Fiddle that demonstrates your issue i would be happy to give you some pointers on how to fix it.

Cheers

Oli :)
