### ISSUE TITLE
bottomCalcParams doesn't get all table data (only group data)

### ISSUE THREAD

**Issue by bhanson-techempower** [olifolkerd/tabulator#2336]
**Describe the bug**

`bottomCalcParams` doesn't get all table data (only group data)

**Tabulator Info**

- Which version of Tabulator are you using? 4.4.1
- Post a copy of your construct object if possible so we can see how your table is setup. See jsfiddle

**Working Example**

https://jsfiddle.net/bhanson_techempower/wuaz84xq/

**To Reproduce**

1. Run jsfiddle
2. Open console
3. See `data` only displays grouped data.

**Expected behavior**

`data` should return "all table data", see documentation:

http://tabulator.info/docs/4.4/column-calcs

```
//define lookup function
function paramLookup(values, data){
    //values - array of column values
    //data - all table data

    //do some processing and return the param object
    return {param1:"green"};
}

//column definition
{title:"Rating", field:"rating", topCalc:customCalcFunction, topCalcParams:paramLookup}
```

**Desktop (please complete the following information):**

 - OS: Windows 10 Pro Version	10.0.18362 Build 18362
 - Browser: Chrome Version 76.0.3809.132

**Comment by aklaver** [comment]
I'm not seeing that. I see the the values and data arrays being built up from 0 to 3 entries:
```
data: []

data: [
  { "id": 1,  "name": "Jane Doe",    "age": 42,    "gender": "Female"},
  {  "id": 2,    "name": "Backstreet Boy",    "age": 88,    "gender": "Male"  },
  {  "id": 3,    "name": "The Pope",    "age": 72,    "gender": "Male"  }
]
```

**Comment by bhanson-techempower** [comment]
@aklaver It only shows all 3 entries when called for the grand total "202" line. When called for one of the sub group totals, "42" or "160", `data` will only contain the grouped data instead of *all* data.

https://i.imgur.com/aiNaZNw.png

**Comment by aklaver** [comment]
I think we are seeing the same thing differently. The way I see it:
1) The values array shows just the values for the column that is being calculated.
2) The data array shows the values for all the columns in the row.
3) As the calculation is being done over groups the arrays occur in groups.

If I'm following your reasoning,  you are expecting the data array should be equivalent to table.getData().
Which is the correct interpretation is something that is going to need input from @olifolkerd .

**Comment by olifolkerd** [comment]
There are two modes for column calculations, either whole table or groups

The [Calculation Visibility Documentation](http://tabulator.info/docs/4.3/column-calcs#visibility) explains how to choose which one is visible.

Its current mode of operation is working as i would expect.

Cheers

Oli :)
