### ISSUE TITLE
AngularJS (Legacy) implementation/component

### ISSUE THREAD

**Issue by DigitalVilla** [olifolkerd/tabulator#2337]
I would like to know if there is a tutorial that can help me to use tabulator in legacy AngularJS,

**Comment by olifolkerd** [comment]
Im afraid not,

Angular support was only added to Tabulator when Angular 2 was available.

Though it is just a JavaScript library so you should be able to add it in following the existing angular guide with a few tweaks, you dont need to use the component wrapper.

I hope that helps,

Cheers

Oli :)
