### ISSUE TITLE
dataTree rows selection is not persistent

### ISSUE THREAD

**Issue by adilev26** [olifolkerd/tabulator#2338]
when creating a table with _children in dataTree and selecting the rows, the dataTree rows are being deselected upon updateOrAddData(),
moreover, the getSelectedRows() will still return the previously selected rows but the rows themselves are not set as selected.

scenario:
1. set data with _children.
2. select all rows.
3. perform updateOrAddData() for the existing data.

expected:
selection is persistent for all rows.

actual:
only parent rows selection is persistent.

**Comment by olifolkerd** [comment]
Hey @adilev26 

The row selection feature is not currently available on nested row, this feature is on the roadmap for a later version

Cheers

Oli :)
