### ISSUE TITLE
Click and drag scrolling gets stuck (Chrome)

### ISSUE THREAD

**Issue by 8483** [olifolkerd/tabulator#2339]
**Describe the bug**

Happens when the scroll bar is clicked and dragged down or up. The bar and rows scroll just a bit, and then it gets stuck.

The problem occurs above 50-60 rows. Below that it works fine.

This is not a problem in Mozilla Firefox. Just in Chrome.

Removing the formatters doesn't change anything.

It's really odd that it sometimes works, and others doesn't.

**Tabulator Info**

Tabulator version 4.4
```
let table = new Tabulator("#content-full", {
                height: "100%",
                data: data,
                layout: "fitDataFill",
                groupStartOpen: false,
                groupToggleElement: "header",
                columns: [
                    { title: "#", field: "example", formatter: "rownum" },
                    { title: "Период", field: "ym" },
                    { title: "Датум", field: "addate", formatter: dateFormatter },
                    { title: "Документ", field: "ackey", formatter: invoiceLinkFormatter },
                    { title: "Шифра", field: "clientCode" },
                    { title: "Фирма", field: "clientName", formatter: companyLinkFormatter2 },
                    { title: "Одговорен", field: "odgovoren" },
                    { title: "Комерцијалист", field: "komercijalist" },
                    { title: "Референт", field: "referent" },
                    { title: "Ставки", field: "stavki" },
                    { title: "Промет", field: "revenue", formatter: numberFormatter },
                    { title: "Разлика", field: "profit", formatter: numberFormatter },
                    { title: "Маржа", field: "margin", formatter: percentFormatter },
                    { title: "Статус", field: "status" }
                ]
            });
```

**Working Example**

I didn't manage to replicate the problem in a code pen, as it doesn't occur.

If it helps, I've added [two gifs with the behavior](https://imgur.com/a/l027ZXA).

I am also willing to give you access to the app in order to see what happens. 

**Desktop (please complete the following information):**

- OS: Windows 10 Pro Version 1803
- Browser: Chrome 75.0.3770.142 (Official Build) (64-bit)
- Version: 4.4

**Comment by olifolkerd** [comment]
@8483 

I cannot replicate this my end, please create a JS Fiddle to demonstrate the issue.

Cheers

Oli :)
