### ISSUE TITLE
Column alignment issue 

### ISSUE THREAD

**Issue by kchho** [olifolkerd/tabulator#234]
I found that the columns alignment goes wrong if I sort the column after I've ever moved it.   Could you please take a look?   Thank you so much!

![111](https://cloud.githubusercontent.com/assets/20301616/24328394/27c83a60-121b-11e7-93f5-39a16004c77a.png)

**Comment by olifolkerd** [comment]
Hey,

That is an unusual glitch you have found there, could i ask which browser you are using?

Cheers

Oli

**Comment by kchho** [comment]
Hi Oli, 
Thanks for your reply.   I am using Chrome version 57.   I think this is the latest version.
Cheers,
Kchho

![111](https://cloud.githubusercontent.com/assets/20301616/24434709/d64d9054-1463-11e7-9d6e-1008c2efac2b.png)

**Comment by mangkang** [comment]
Hi,

Thanks for creating this slick table grid.

I encountered a related drag/alignment issue on Chrome (56.0.2924.87) on OS X as well while playing with the demo. If you drag the column header but don't complete the action and instead place it back to its original location, the column data is moved but the header remains at its original location.

![screen shot 2017-03-29 at 6 43 47 pm](https://cloud.githubusercontent.com/assets/13228625/24483856/b0a19228-14af-11e7-8def-453c30fa1489.png)

To reproduce, see : 

https://drive.google.com/open?id=0B8d1XVKRZKBwRm1NNGxKWXpocEU

Thanks,

MK

**Comment by olifolkerd** [comment]
Hey,

This has now been resolved and a fix pushed to the repo :)

Thanks for your patience.

Cheers

Oli
