### ISSUE TITLE
Problem with mutator for generating data when data is updated

### ISSUE THREAD

**Issue by danke02** [olifolkerd/tabulator#2340]
Hello.
I use tabulator version 4.4. I tried mutator to generate new column data which is a sum of column A and B. As document said, I assigned field name "C"  to this column. I expected column C to be updated whenever column A or B is updated. When  table is initialized at first it succeeded but it doesn't change even though column A or B is updated by calling "Row.updateData". 

I read the code and found the reason. When "Mutator.transformRow" is called, it gets data parameter with only updated field. When col A or B is updated it has no column C. I wish mutator of col C is called but code "column.getFieldValue(data)" for column C returns "undefined" which finally prevents mutator of col A from being called.

Do you have any suggestions?

I attached the source code for your convenience. 
Thank you.

```
//apply mutator to row
	Mutator.prototype.transformRow = function (data, type, update) {
		var self = this,
		    key = "mutator" + (type.charAt(0).toUpperCase() + type.slice(1)),
		    value;

		if (this.enabled) {

			self.table.columnManager.traverse(function (column) {
				var mutator, params, component;

				if (column.modules.mutate) {
					mutator = column.modules.mutate[key] || column.modules.mutate.mutator || false;

					if (mutator) {
						value = column.getFieldValue(data);

						if (!update || update && typeof value !== "undefined") {
							component = column.getComponent();
							params = typeof mutator.params === "function" ? mutator.params(value, data, type, component) : mutator.params;
							column.setFieldValue(data, mutator.mutator(value, data, type, params, component));
						}
					}
				}
			});
		}

		return data;
	};
```

**Comment by aklaver** [comment]
You are going to have to show the table constructor and mutator code.

**Comment by olifolkerd** [comment]
It depends what type of mutator you are using in your column definition.

As @aklaver says we will need to be able to see how your table is setup to help you out. please create a JS Fiddle to show it in action

Cheers

Oli :)

**Comment by olifolkerd** [comment]
closed due to inactivity
