### ISSUE TITLE
Styling row with line-through

### ISSUE THREAD

**Issue by andreaeasycloud** [olifolkerd/tabulator#2341]
Hello sorry to write here. Can't ask on stackoverflow.

Tabulator version: 4.2.7

Question: How can i style a row with line-through css 

rowFormatter:function(row){
 	    var data = row.getData();
 	    if(data.annullato){
 	    	row.getElement().style["background-color"] = "red";
 	    	row.getElement().style["text-decoration-line"] = "line-through"; // WHY NOT WORK?
 	    }else{
 			console.log("false");
 		}
 	},

The row is red, but not lined through.
![Selection_019](https://user-images.githubusercontent.com/48676861/64197989-a96e5d80-ce87-11e9-8325-a15b550f236a.png)

Thank you

**Comment by aklaver** [comment]
Something like:
row.getCells().forEach(function(cell){cell.getElement().style["text-decoration"] = "line-through"; })

**Comment by andreaeasycloud** [comment]
Yes. Thank you @aklaver. It perfectly work! :)
