### ISSUE TITLE
GetColumndefinitions has wrong property-value for "editor" when using a custom one

### ISSUE THREAD

**Issue by rhagstrand** [olifolkerd/tabulator#2344]
**Describe the bug**
Initialize a table with some column where editor: <customeditor>. 
Later when I call tablename.getColumnDefinitions() the editor property is set to "textarea()"

**Tabulator Info**
4.4.1

my columns look like this:
columns: [
                { rowHandle: true, formatter: "handle", headerSort: false, frozen: true, width: 40, minWidth: 40 },
                { editableTitle: false, resizable: false, field: "riskHeadline", width: 200, editor: buttonEditor, editable: editRiskCheck, formatter: textAreaBoldAndBlue},
                { field: "riskText", resizable: false, editor: buttonEditor, editable: editRiskCheck, formatter: "textarea" },
                { resizable: false, editable: false, formatter: riskOptionsButton, width: 70, minWidth: 70 },
                { field: "id", visible: false, width: 0 }
            ]

**To Reproduce**
Create table with columns as above, then call
tablename.getColumnDefinitions() and you will see that all columns defined with "editor: buttonEditor" is set to "editor: textarea()"

**Expected behavior**
"editor: buttonEditor" should be reflected in getColumnDefinitions()

**Comment by rhagstrand** [comment]
I guess its since buttonEdit is a function-reference

**Comment by olifolkerd** [comment]
Hey @rhagstrand,

There are circumstances where it wont return the property if it is a function, but it should never return something completely different.

are you saying that it was showing as "textarea" for columns where the formatter was a custom function?

Cheers

Oli :)

**Comment by rhagstrand** [comment]
Yes it says textarea. It would help alot if it could atleast show the function-name as a string. Then I could in code check if that string is actually a valid function name in my script-file.

**Comment by olifolkerd** [comment]
Hey @rhagstrand 

When i run your example code and call the ***getColumnDefinitions*** function, the column definition is exactly as expected.

The ***editor*** property contains the function as expected. are you sure you are not accidentally looking at the ***formatter*** property as that does contain the string "textarea" which is the formatter being used.

At this point there is no issue i can find so i am going to close this issue. If you feel there is still a problem i will need you to create a JS Fiddle or Code Pen that demonstrates the issue in action.

Cheers

Oli :)
