### ISSUE TITLE
Warning in headerFilters causing these not working

### ISSUE THREAD

**Issue by BinLiu9205** [olifolkerd/tabulator#2345]
Hello, sorry that I can't distinguish whether it is a bug or an issue caused by my own. I am really grateful if anyone can help me out

**The bug**
I have been using Tabulator v4.2.7 for a small web application. 

Since there is more than one webpage in my own application, I just copied the same code for generating a table from a developed web page to a new page. 
However, the code was showing warnings in this particular new case. Here is a screenshot for the warning. 

![bug](https://user-images.githubusercontent.com/39727439/64327704-6ff33a80-cfcc-11e9-9ad1-4bbd7b6d66bd.png)

In brief, the header filter wasn't working due to this warning while the table and the sorter were still displayed perfectly as expected. I defined four headerFilter in the columns, three as default, and one adapted from the minMaxfilter from the example code. None of them is working in my case. The screenshot was for the last customized filter function. All the other three warnings were similar.   The table is as below

![Table](https://user-images.githubusercontent.com/39727439/64329490-a7afb180-cfcf-11e9-8b4c-5e571ae4e05f.png) 

Here is the code I have been using. The second one is to update the data in the table. But the problem occurs with no regarding whether to run the second function.

```javascript
var GOTable = new Tabulator("#GeneOntologyTable",{
  data:object_selectedGO,
  layout:"fitColumns",
  selectable:true,
  pagination:"local",
  paginationSize:10,
  paginationSizeSelector:[10, 20, 50,100],
  movableColumns:true,
  columns:[
  {title:"GO_ID", field:"GOid",sorter:"string", headerFilter:"input", headerFilterPlaceholder:"search for id ..."},
  {title:"GO_term", field:"GOName",sorter:"string", headerFilter:"input",headerFilterPlaceholder:"search for name..."},
  {title:"Annotation_for_the_GO", field:"GOGene",sorter:"string", headerFilter:"input",headerFilterPlaceholder:"search for gene..."},
  {title:"P_value", field:"GOpvalue",sorter:"number",headerFilter:minMaxFilterEditor, headerFilterFunc:minMaxFilterFunction},
],
});

function sortBasedGOterms(d){
    GOTable.setData(d)
};
```
Similar code ran really well on the other webpage and the library was sourced from the same template, so I think it might be hardly reproducible. The data object_selectedGO is a JSON object. A sliced example here:

[{GOGene: "Acsl4", GOName: "fatty-acyl-CoA biosynthetic process", GOid: "GO:0046949", GOpvalue: "7.38E-03"}]

I am really looking forward to your suggestion about the warning. As a total beginner in this area, I would also appreciate if someone can explain to me a little bit why the editor is returning HTML tags for the format of the filter instead of expected node instances and why the code works in the other page just not this one. Thanks for your help and the tool is really impressive.

**Comment by BinLiu9205** [comment]
I checked the source code, it seems that the object was in the right format, but the object itself is not instanceof Node, which was quite surprising to me, because the code works exactly as expected on the other webpage with object generated from the same previous steps. Anyway,  the issue was detoured by removing the 

`if (!(editorElement instanceof Node)) {

console.warn("Filter Error - Cannot add filter to " + field + " column, editor should return an instance of Node, the editor returned:", editorElement);

return;}`

which is apparently not the best solution since it will not be able to check whether the returned object is in the right format. So I am still looking forward to any explanation or fixation to the issue. 

Thanks!

**Comment by olifolkerd** [comment]
Hey @BinLiu9205 

Could you create a JS Fiddle with a working example of your code so we can see how it is setup, then we can offer you some advice

Cheers

Oli :)

**Comment by BinLiu9205** [comment]
Thank you very much for your kindly reply. I am sorry that I just failed in creating a Fiddle to reproduce the problem because as long as I isolating the environment, the warning is gone and everything is working smoothly again. The warning (maybe error for the webpage) pops up only on this particular page. Indeed, the same code works well even on the other page from the **same website** with **exactly the same setup** (all the scripts are sourced from the same base template). It seems that on this page all the returned editorElement objects are not instanceof Node although they are in the right format, that was how I made my detour to fix the problem by deleting part of the if condition. 

Thank you again for the very nice package and your reply. You can close the report since I do have a great problem reproducing the issue.
