### ISSUE TITLE
GroupBy uses original row index

### ISSUE THREAD

**Issue by CatherineLearmonth** [olifolkerd/tabulator#2346]
When using groupBy, the original row indexes are used on the row. So before a groupBy, a row might have an index of for example 2, but after the groupBy the index position may have changed, but the row index is still 2. This causes an issue when doing a row callBack, as the old index is returned rather than the new index when a groupBy is applied.

I am assuming here that the row id is equivalent to the row index position.

**Tabulator Info**
4.4 ReactTabulator

**Working Example**
Please include a JS Fiddle or Code Pen that demonstrates the problem, it is very hard to diagnose an issue from a simple description

**To Reproduce**
1. Use the groupBy option on the table.
2. Apply a rowClick call back.

**Expected behavior**
In the rowClick call back, I would expect row._row.data.id to have a value of the current position of the row. 

**Actual behavior**
The row._row.data.id has the value of the row before the groupBy was applied. Now the row id value is no longer correct.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 76.0.3809.100

**Additional context**

**Comment by olifolkerd** [comment]
Hey @CatherineLearmonth 

The index is not the position of the row in the Table. In Tabulator the index is a unique key added to the ***id*** field of the row data *(the field can be changed)*, therfore it is not affected by grouping

If you are having a specific issue please post a link to a JS Fiddle so we can understand how your table is setup and what you are trying to achieve and can offer some advice on how to help you out

Cheers

Oli :)
