### ISSUE TITLE
Include callbacks for the checkboxes

### ISSUE THREAD

**Issue by CatherineLearmonth** [olifolkerd/tabulator#2347]
**Is your feature request related to a problem? Please describe.**
I am using v4.4 and including the checkboxes in the table to indicate row selection. When a user clicks on the checkbox, there is no callback supplied in the documentation so that a developer can hook into this action.

**Describe the solution you'd like**
Supply call back functions for the 'select all' checkbox in the header and the 'select row' checkboxes.

**Describe alternatives you've considered**
I have created a callback once the table is loaded and used jQuery on the checkbox elements to create change events on them. We as a business are trying to remove dependency on jQuery and it would be better if there was an inbuilt callback I could use. 

**Additional context**

**Comment by cocodrino** [comment]
I've similar issue, I'm using tags, so the user can add or remove tags, similar to the example provided, the worst part is that I'm using react and the only way that seems work according to the documentation is orthogonal to react

**Comment by aklaver** [comment]
Can't you use the cell callback for the row checkboxes:
http://tabulator.info/docs/4.3/callbacks#cell
and tie it to a column as shown in the examples above.

There is also the editable callback:
http://tabulator.info/docs/4.3/edit#callbacks

For the header checkbox there are the column callbacks:
http://tabulator.info/docs/4.3/callbacks#column
