### ISSUE TITLE
Have ranges for table.selectRow

### ISSUE THREAD

**Issue by CatherineLearmonth** [olifolkerd/tabulator#2348]
**Is your feature request related to a problem? Please describe.**
A user is able to shift select multiple rows, but programmatically we can only select one row at a time. I believe that selecting one row and then another will turn off the row that was previously selected. I would like to programmatically emulate shift selecting rows. 

**Describe the solution you'd like**
Allow the developer to select multiple rows rather than just one at a time, so that the shift select function can be emulated. 

**Describe alternatives you've considered**
I am using jQuery to multi select rows but our business is trying to move away from jQuery and I think it would be good if the 'selectRow' function could be extended to select multiple rows rather than just one or all rows.

**Additional context**

**Comment by aklaver** [comment]
From here:
http://tabulator.info/docs/4.3/select#manage
"If you want to select multiple rows you can pass an array of row component look up options into the first parameter"

So something like:
table.selectRow([1,3])
