### ISSUE TITLE
Column Calculator With Grouping Shows Zero

### ISSUE THREAD

**Issue by slowsquirrel69** [olifolkerd/tabulator#2350]
When we set for grouping it works but when we add the bottomCal, the sums are all zero

<img width="1715" alt="capture0906" src="https://user-images.githubusercontent.com/14809073/64459807-d2306600-d0c6-11e9-8d72-1c146010a8ee.png">

columns:[
            {title:"ID", field:"id", sorter:"number"},
            {title:"Pit", field:"pitID", sorter:"string"},
            {title:"AccountID", field:"patronID", sorter:"number"},
            {title:"Account Name", field:"patronFullName", sorter:"string"},
            {title:"Date", field:"transactionDate", sorter:"string"},
            {title:"Time", field:"transactionTime", sorter:"string"},
            {title:"Day", field:"transactionDay", sorter:"string"},
            {title:"Transaction", field:"transaction", sorter:"string"},
            {title:"Type", field:"transactionType", sorter:"string"},
            {title:"Cashier", field:"cashier", sorter:"string"},
            {title:"Amount", field:"amount", sorter:"number", bottomCalc:"sum"},
            {title:"Cash-In", field:"cashIn", sorter:"number"},
            {title:"Cash-Out", field:"cashOut", sorter:"number"},                        
        ]

**Comment by slowsquirrel69** [comment]
I figured out the issue. The json encoded data coming back from PHP had the amounts with quotes around it from number_format function. Commented out function and now it works. So this is not an issue but still wanted the posting to reflect a solution for any other developers.

**Comment by olifolkerd** [comment]
@slowsquirrel69 you can call the ***hide*** function on the column component for the group

Cheers

Oli :)
