### ISSUE TITLE
Double click text selection in cell chrome

### ISSUE THREAD

**Issue by leleftheriades** [olifolkerd/tabulator#2351]
Using Google Chrome Version 76.0.3809.132

When editing a cell, if I double-click to select all text and then type in order to replace the text, it does not work.

Firefox works fine.

**Comment by aklaver** [comment]
I've got a feeling this is related to:
https://github.com/olifolkerd/tabulator/issues/2262

Can  you provide your table constructor?

**Comment by leleftheriades** [comment]
You can see it in the example in http://tabulator.info/ double click on a name and try to type

**Comment by aklaver** [comment]
Yeah it looks like the same thing as in the issue I referenced above, the highlighting is stealing focus from the editor. You can backspace the value out if you don't highlight(dbl click) it. @olifolkerd has identified the problem and is working on a fix for the next release.
