### ISSUE TITLE
The print out function doesn't print out the progress bar in the table

### ISSUE THREAD

**Issue by HongyuWang-2018** [olifolkerd/tabulator#2352]
**Describe the bug**
I am using Tabulator to create the table and adding a button to print out the table, however, when i click the button it shows the progress bar in my table doesn't show on the print out results.

**Tabulator Info**
- version: 4.3.0
```
<script src="https://unpkg.com/tabulator-tables@4.3.0/dist/js/tabulator.min.js"></script>
```

**Working Example**
I put the code on CodePen.(https://codepen.io/hongyuwang-2018/pen/mdbLVjM )

**To Reproduce**
1. Click the "Print out" button

**Expected behavior**
I expect to print out the table with the progress bar.

**Comment by olifolkerd** [comment]
Hey @HongyuWang-2018 

This is a known limitation at the moment, it will be coming in a future release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @HongyuWang-2018 

I have pushed an update to fis this to the 4.6 branch, which should be released in a few weeks time.

Cheers

Oli :)

**Comment by thoughtspacewebsites** [comment]
Trying to go this exact same thing in v4.9.3, and the resulting print out does not have the bar. The print preview shows it correctly, but the actual print out is missing it :/
