### ISSUE TITLE
wildcards in headerfilter

### ISSUE THREAD

**Issue by jaxnatax** [olifolkerd/tabulator#2353]
**Is your feature request related to a problem? Please describe.**
cannot filter empty or %something1%something2% values

**Describe the solution you'd like**
Please implement wildcards and negation usage in header filtering

**Describe alternatives you've considered**
cannot see existing alternative (manual filtering is not considered due it would be a full automatic work)
one another acceptable way would be a filtering input box, which processing could handle multiple fields (working on it)

**Additional context**
no additional context

**Comment by aklaver** [comment]
You can build a custom filter:

http://tabulator.info/docs/4.3/filter#header

A code sample(jsFiddle/CodePen) would help.
