### ISSUE TITLE
Column calculations for grouped data - display in the toggle element

### ISSUE THREAD

**Issue by 8483** [olifolkerd/tabulator#2355]
The current grouped calculations are displayed in a separate row, displayed below the collapsed rows the calculations are based on.  

It would be great if there was a second option to display the calculations in the same row i.e. the collapsed header that we click to expand.

This will make it much cleaner, as not many columns are actually needed for grouped calculations.

**Comment by olifolkerd** [comment]
Hey @8483 

There is a ***groupClosedShowCalcs*** property to allow you to toggle calc row visibility with groups.

You can find out more about this function in the [Grouped Row Calculation Documentation](http://tabulator.info/docs/4.3/column-calcs#groups)

I hope that helps,

Cheers

Oli :)

**Comment by 8483** [comment]
Thank you for the reply.

I am aware of this option. It's not what I was talking about.

Here's a picture for a clearer example.

https://imgur.com/a/ZccHbPA

In the second table, there are no unnecessary rows, making the table much cleaner.

**Comment by olifolkerd** [comment]
You can achieve that yourself using the ***groupHeader*** callback

**Comment by 8483** [comment]
I apologize for nagging you. Can you please explain a bit what you mean by **groupHeader** callback?  

I was not able to find it in the documentation.

**Comment by olifolkerd** [comment]
[Group Header Documentation](http://tabulator.info/docs/4.4/group#setup-headers)

You return the contents of the group header from the callback so you can put whatever you link in the group header.

Cheers

Oli

**Comment by 8483** [comment]
Damn, this is the 4th feature suggestion that turned out to exist alreadys.

Simply fantastic. Thank you.
