### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by vasiliyaltunin** [olifolkerd/tabulator#2356]
You have error in documentation http://tabulator.info/docs/4.4/format

in string:
inputFormat - the format of the date/time in the row data(default: YYY-MM-DD hh:mm:ss)

Must be:
YYYY-MM-DD hh:mm:ss

And later in text same mistake

**Comment by olifolkerd** [comment]
Hey @vasiliyaltunin 

Good spot, i will get that fixed.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @vasiliyaltunin 

I have pushed a fix for this and will include it in the website update later today.

Cheers

Oli :)
