### ISSUE TITLE
feat: combined layout (fitData and fitColumns)

### ISSUE THREAD

**Issue by britvik** [olifolkerd/tabulator#2357]
Would it be possible to get a new layout which would combine fitData and fitColumns? To be honest I expected 'fitDataFill' to do that. but it doesn't.

This is how I imagine it:
It would fit columns to data (just like fitData) and then it would expand each column to fill the remaining space. If there is no remaining space after fitData, then do nothing.

**Comment by aklaver** [comment]
Can you provide an example in jsFiddle/CodePen that illustrates.

**Comment by britvik** [comment]
https://codepen.io/britvia/pen/jONpjKP

1st table has fitData - all data is visible (good) but there is unused space (bad)
2nd table has fitColumns - some data is cropped (bad) all space used (good)
3rd table shows how the new layout would look. I know it's possible to achieve this (exactly how I did it in the example - fitColumns with set width on a column), but this is not always possible, when you don't know the width of the columns beforehand.

If you think this new layout would be useless, just close the issue. I can work around it, but thought this would be a good addition :).

Shouldn't be hard to implement either. Just do fitData, count widths of columns, subtract it from the table width, divide by number of columns and add the result to every column.

**Comment by aklaver** [comment]
The first example output looks different on Firefox vs Chrome. In FF there is no unused space in fact it ends up with a horizontal scrollbar. In both browsers the third example ends up with cropped header titles which I would find annoying(just my personal preference).  I think it points up the difficulty of predetermining a layout. Re: your suggestion, have you looked at the widthGrow, widthShrink options to fitColumns? They allow you to have the layout do dynamic column width adjustment.

**Comment by britvik** [comment]
Ah didn't realize you might have different screen size. I added a screenshot how I see it :).

I tried the widthGrow, it's great but not very usable in my scenario. I can't show you the data, but basically I have 16 columns, there are dates, texts numbers... When I fitColumns, some data is cropped. When I do fitData I can see all the data but there is a small unused space which I would like to fill :). Right now I set fixed width on some columns and used fitColumns. It looks good in most scenarios when the text width doesn't change much.

![tabulator_layout](https://user-images.githubusercontent.com/4123430/65019566-c1d08480-d92b-11e9-9938-9b78ee102c8d.PNG)

**Comment by ryanlin1986** [comment]
I'm looking for this feature as well, very important ;) 
We need having both columns types, some fit to data, and others grow to fill available spaces.

**Comment by olifolkerd** [comment]
This feature has been pushed to the 4.5 branch, there is a new layout mode called ***fitDataStretch***

Version 4.5 will be released in the next few weeks.

Cheers

Oli :)

**Comment by ryanlin1986** [comment]
Great news, thanks @olifolkerd  for the amazing works
