### ISSUE TITLE
data not showing

### ISSUE THREAD

**Issue by kumaresan-in** [olifolkerd/tabulator#2358]
var url = "https://jsonplaceholder.typicode.com/todos/";
var myJsonString;
var table = new Tabulator("#example-table", {
    height:"311px",
    layout:"fitColumns",
    ajaxURL:"",
    ajaxResponse:function(url, params, response){
			 return table.setData(response); 
    },
    ajaxProgressiveLoad:"scroll",
    paginationSize:20,
    placeholder:"No Data Set",
    columns:[
        {title:"Name", field:"userId", sorter:"string", width:200},
        {title:"Progress", field:"progress", sorter:"number", formatter:"progress"},
        {title:"Gender", field:"gender", sorter:"string"},
        {title:"Rating", field:"rating", formatter:"star", align:"center", width:100},
        {title:"Favourite Color", field:"col", sorter:"string"},
        {title:"Date Of Birth", field:"dob", sorter:"date", align:"center"},
        {title:"Driver", field:"car", align:"center", formatter:"tickCross", sorter:"boolean"},
    ],
});
      

I need to fetch the data from API with progressive load

**Comment by aklaver** [comment]
Take a look at:
http://tabulator.info/docs/4.3/data#ajax

ajaxResponse is only needed if you want to change the response coming back from the server, which you are not doing. If you do want to use it then follow the form shown here:
http://tabulator.info/docs/4.3/data#ajax-response
