### ISSUE TITLE
Cannot hide column group header

### ISSUE THREAD

**Issue by Joan1899** [olifolkerd/tabulator#236]
Hi,

how can I hide a column group header. I tried assigning a field and using hidelCol but it did not work. Should I use jquery, select the element and hide it?

**Comment by olifolkerd** [comment]
Are you trying to hide all columns in the group or just the header element?

Cheers

Oli

**Comment by Joan1899** [comment]
I want to hide all headers contained in the group and the group header itself. I am using jquery and it works. When I display one of the columns contained in a hidden group, I want the group header to display as well.

If there is no solution implemented then I will do it in jquery. It is quite laborious for I have to check what is being displayed and compare it to a reference list of existing columns (if style: height = 0 --> invisible), but it seems to be a possible workaround.

**Comment by olifolkerd** [comment]
There is currently no way to hide whole column groups, though this feature will be coming in the next release.

**Comment by Joan1899** [comment]
THX for your response and your dedication. Closing issue/question

**Comment by jmartsch** [comment]
Any news on this? I did not find an example to hide a column group in version 4.4

**Comment by olifolkerd** [comment]
you can do this by calling the ***hide*** function on the column component for the group

Cheers

Oli :)
