### ISSUE TITLE
Allow to disable scrollEventListener on select 

### ISSUE THREAD

**Issue by wdehoog** [olifolkerd/tabulator#2360]
When a select editor on the last rows opens its options list, the scroll event is triggered which calls cancelEdit which closes the list immediately. 

I am using Tabulator 4.4 and it happens on Firefox (Windows). On Chrome it does not happen.
My table height is set to 405.

So it works on Chrome but with Firefox the table is unusable for the bottom rows. By allowing to disable the 'cancel on scroll' the select editor can be used again.

**Comment by olifolkerd** [comment]
Hey @wdehoog 

Could you create a JSFiddle that demonstrates this (please use the bug issue template if you are reporting a bug, it prompts you for all the info we need to help you out)

The select dropdown is appended to the page body so it shouldn't affect the table scroll so i am a bt confused there.

Cheers

Oli :)
