### ISSUE TITLE
Allow to sort select list on labels

### ISSUE THREAD

**Issue by wdehoog** [olifolkerd/tabulator#2361]
The data set for a select options list for an editor or header filter ends up being sorted by 'value' which is in fact the key. 

The options list shows the 'label' and it would be better to have the list being sorted by that.

I got something working by adding this to the parseItems function
```

        if (editorParams.sortLabelsList) {
          if (editorParams.sortLabelsList == "asc") {
            dataList.sort(function(a, b) {return a.label.localeCompare(b.label)});
            displayList.sort(function(a, b) {return a.label.localeCompare(b.label)});
          } else {
            dataList.sort(function(a, b) {return -a.label.localeCompare(b.label)});
            displayList.sort(function(a, b) {return -a.label.localeCompare(b.label)});
          }
        }
```

**Comment by olifolkerd** [comment]
Hey @wdehoog 

I would be happy to accept a pull request for this, that allows the user to determine if it is sorted by laabel or value, as i can see uses for both.

It would need to sort by the current method as default to prevent changes to functionality for people using the system as it currently works.

Let me know if you would be interested in submitting this.

Cheers

Oli :)

**Comment by jwalker5006** [comment]
I did kinda the same thing.  I am sure you could refine it and do everything before the fillList(); to

Here is what I did.

1. Add custom function that sorts arrays by passed name.
1. hook just before fillList();

ege from StackOverflow gets credit for the function
https://stackoverflow.com/questions/1129216/sort-array-of-objects-by-string-property-value
![image](https://user-images.githubusercontent.com/6217843/67130786-0d46ae80-f1c8-11e9-8ade-81e707a6ecc4.png)


![image](https://user-images.githubusercontent.com/6217843/67130777-061fa080-f1c8-11e9-9f0c-330c1cc24e51.png)

**Comment by olifolkerd** [comment]
Hey @wdehoog 

On further inspection i am unsure what you are asking for. the values list is only sorted if it is autogenerated from column values, in which case the values and lables are the same.

If you pass in your own values in, then it is based on the order of the array values you pass in, so you can sort things before they reach the editor.

Cheers

Oli :)
