### ISSUE TITLE
styling for rows based on tree depth

### ISSUE THREAD

**Issue by michael-ts** [olifolkerd/tabulator#2362]
I'm trying to set up a theme that styles each row based on its depth in the tree when `dataTree` is true.

I'm thinking something similar to the CSS class `tabulator-group-level-X` for groups is needed.  Maybe `tabulator-tree-level-X`?

**Comment by tentus** [comment]
Makes sense to me. I went looking for a workaround and couldn't find one, but it seems like adding such a feature would be pretty easy, just hop into `DataTree.prototype.layoutRow` probably and add a class to `config.branchEl` based on the `config.index`.

**Comment by olifolkerd** [comment]
Hey @michael-ts 

That is a great idea, it would be really easy feature to add, @tentus makes a good suggestion.

I would be happy to accept a pull request on this

Cheers

Oli :)

**Comment by RaquelAM** [comment]
Hi @olifolkerd 
I would like to help with this, is still available?

**Comment by olifolkerd** [comment]
Hey @RaquelAM 

Yes this is still available, 

please have a look at how the group module handles adding its classes, and look at using a similar naming convention for the tree system.

Let me know if you need any info or feedback.

Cheers

Oli :)

**Comment by RaquelAM** [comment]
Hi
Ok, I will work this week on this.
Thanks!!
:D

**Comment by olifolkerd** [comment]
The pull request for this has been merged in.

It will be included in the 4.6 release in the next few weeks.

Cheers

Oli :)
