### ISSUE TITLE
setData -- url already contains question mark

### ISSUE THREAD

**Issue by ray73864** [olifolkerd/tabulator#2363]
I'm trying to use Tabulator to do an ajax request (using setData), and I've hit a bit of a snag with the params part of it.

My url already contains a question mark in it, eg: http://example.com/myfile.p?session=sessionid

I have to  use a function of the framework to generate the url but this means it auto-includes the session ID in it, the problem then comes when Tabulator creates the request.

If I have my setData as

```
table.setData(url, { key1:value, key2:value });
```

where url is the same as in the example at the top, the requested url by Tabulator ends up as:

http://example.com/myfile.p?session=sessionid?key1=value&key2=value

A simple fix to this would be to have Tabulator check for the presence of a ? in the url and if it exists, then it automatically starts with &, if it doesn't then it continues doing it the way it currently does.

I could change the url to just be 'myfile.p' but then I would have to make sure the sessionid is included in the list of params.

Using the CDN version of Tabulator.

Testing on a Win10 PC running latest version of Chrome.

**Comment by olifolkerd** [comment]
Hey @ray73864 

Tabulator currently only accepts a url without params to automatically add the params for you

If you want a custom behaviour for the url generation, you can use the ***ajaxURLGenerator*** function which lets you tell the table how to build the URL

Checkout the [Ajax Documentation](http://tabulator.info/docs/4.3/data#ajax-url) for information on how to use this function

I hope that helps,

Cheers

Oli :)
