### ISSUE TITLE
Frozen columns header - rest of the columns temporal misalignment on edge browser

### ISSUE THREAD

**Issue by parramito** [olifolkerd/tabulator#2364]
**Describe the bug**
If there is a table with frozen columns (this behaviour is also happening on the tabulator documentation:  [http://tabulator.info/examples/4.1?#frozen-col]) and we scroll horizontally to the right, the header of the table position seems to be updated earlier than the rest of the columns, for a small period of time. Once I stop scrolling they align themselves again.

**Tabulator Info**
Any: http://tabulator.info/examples/4.1?#frozen-col

**Working Example**
http://tabulator.info/examples/4.1?#frozen-col

**To Reproduce**
Load http://tabulator.info/examples/4.1#frozen-col on EDGE browser 
Open up a file
Scroll horizontally

**Expected behavior**
Pinned columns should be pinned to the left, and the header and rest of the columns aligned at all times.

**Comment by tentus** [comment]
I can confirm that Edge suffers from an unusually severe case of rendering lag, which is really visible on tables with frozen columns like that. There's a catch-all issue https://github.com/olifolkerd/tabulator/issues/1437 which you can reference for discussion on scrolling performance.

**Comment by olifolkerd** [comment]
Hey @parramito 

Edge does struggle with rendering issue under certain circumstances.

As edge is about to go though a major overhaul in its next release and switch to using the Chromium rendering engine i am not going to action any specific bugs as they will likely all be resolved after the update.

If this is still an issue after the update please let me know and i will look into it further

Cheers

Oli :)
