### ISSUE TITLE
It seems that sometimes tabulator doesnt sort correctly

### ISSUE THREAD

**Issue by kenseii** [olifolkerd/tabulator#2366]
I have a tabulator table of more than 450 rows(some repetitive records) sorted by a string column, and 90% of the rows are sorted/ordered correctly but there are some records that are not positioned in places they are supposed to be.

As i mentioned that there is some repetitive rows, normally they should be listed next to each other as the order column is the same value, but sometimes it is not the case.

I wonder if it is a known issue or something that have happened before.
I am using tabulator 4.3 and the browser is chrome.

**Comment by tentus** [comment]
Please post a jsfiddle or something illustrating your issue.

**Comment by olifolkerd** [comment]
closed due to inactivity
