### ISSUE TITLE
How to achieve group calculation when sub groups are available

### ISSUE THREAD

**Issue by vivekk-optimus** [olifolkerd/tabulator#2367]
Is it possible to have group calculation of all sub groups as well as whole table calculation.?

**Comment by tentus** [comment]
As I'm reading your question, yes.

Example:
https://jsfiddle.net/o9amr56x/

**Comment by vivekk-optimus** [comment]
As in your example, I need total for 'United Kingdom' and 'Germany' separately.

**Comment by tentus** [comment]
To my knowledge, there's not a built-in way to do that, the group calculations happen at the deepest level but not the intermediates. I imagine Oli would be open to a PR, it's a logical addition.

**Comment by olifolkerd** [comment]
Hey @vivekk-optimus 

Im afraid that isnt an option at the moment

As @tentus says im always up for a well structured pull request.

Cheers

Oli :)
