### ISSUE TITLE
Mouseover not initalising on first pass

### ISSUE THREAD

**Issue by mikehobson** [olifolkerd/tabulator#2369]
I have a table of data which is dynamic based on a Json feed, what i am trying to achieve is to get a tooltip to appear when the mouse is placed over  particular cells. I want this tooltip to display a graph which is provided via an iframe. In order to do this I have used the cellmouseenterfunction and a tooltip libiary called tippy 

This is my colulmn definition
columns:[
               {width:10,headerSort:false}, 
               {title:"league", field:"league",width:50,headerSort:false,visible:false,formatter:"html"},
               {title:"img/clock.png", field:"time", sorter:"date",width:40,titleFormatter:"image",headerSort:false,headerTooltip:"Time gone"},
               {title:"img/goal.png", field:"score", sorter:"string",width:70,formatter:"html",align:"center",headerSort:false,titleFormatter:"image",headerTooltip:"Current Score"},
               {title:"teams", field:"team",headerSort:false, formatter:"html",width:160},
               {title:"matchid", field:"matchid",visible:false},
               {title:"draw", field:"draw",visible:false},
               {title:"homescore", field:"homescore",visible:false},
               {title:"awayscore", field:"awayscore",visible:false},
               **{title:"img/pressure2.png",field:"pi1",width:30,formatter:"html",titleFormatter:"image",headerSort:false,align:"center",headerTooltip:"Attacking Pressure1",
 **cellMouseEnter:function(e, cell, row){var row=cell.getRow().getData();                var celldata=cell.getElement();tippy(celldata, {  content: "<iframe style=\"background:#FFFFFF;\" src=\"../pressure/showgraph.php?="+row.matchid+"&pi=pi1\" width=440 height=225></iframe>",maxWidth:"440px",a11y: false,arrow:true,**
                })},},**

This can be seen at https://soccerscanner.net/new/livescore.html.

The problem i have is that if you move the mouse over any cell in the attacking pressure1 col (first set of numbers after the team names) nothing happens the tooltip is not displayed. If you move the mouse away and back over then the tooltip is displayed.

I think this maybe because Im binding the tooltip to the cell element and maybe that doesnt exisit until the first time i move the mouse over but I cant think of any otehr way to do it, as its a tooltip it needs the element so that it can show the popup box next to it

**Comment by mikehobson** [comment]
Hi, Ive resolved this the issue was actually with tippy, it creates the tooltip the first mouseover but does not show it, maybe this will help someone else but I simply need to check if had been created if so show it, if not create and show it

So my new field def looks like
               {title:"img/pressure2.png",field:"pi1",width:30,formatter:"html",titleFormatter:"image",headerSort:false,align:"center",headerTooltip:"Attacking Pressure1",
                cellMouseEnter:function(e, cell, row){var row=cell.getRow().getData();
                var celldata=cell.getElement();if (!celldata._tippy){tippy(celldata, {  content: "Attacking Pressure<iframe style=\"background:#FFFFFF;\" src=\"../pressure/showgraph.php?gameid="+row.matchid+"&pi=pi1\" width=420 height=225></iframe>",maxWidth:"450px",a11y: false,arrow:true,
                })}celldata._tippy.show();}},

**Comment by olifolkerd** [comment]
@mikehobson 

You would be better to do this in the formatter than on the mouse enter. it would be much smoother.

Cheers

Oli :)
