### ISSUE TITLE
Theming for bootstrap, semantic-ui, material design

### ISSUE THREAD

**Issue by michaelongithub** [olifolkerd/tabulator#237]
Hi
we do all our applications usualy based on bootstrap (3 or 4) or semantic-ui. I looked at the tabulator.css and at the tabulator-simple.css.  Seems demanding to redo/modify.

Is there a simple way, to just include bootstrap or semantic-ui, so they override that and one has this framework - styling. ?

Anybody finds that very important?
Anybody has done that and make available?
A priority for tabulator maintainers ?

Thanks for info, statement, priority setting, good working / procedure ideas.

Cheers, Michael

**Comment by olifolkerd** [comment]
Hi Michael,

Thanks for your suggestion. At the moment Tabulator has a few default themes, and is not tied to the UI styling of any specific framework to make it as flexible as possible.

Having said that I think the idea of adding some compatible styling for the main UI frameworks like bootstrap, semanti-ui, jquery-ui and material design would be a great addition to the system.

It should be fairly simple to add a setting to enable a compatible design mode into the next release at the end of the month. that could then add the appropriate classes to the table to meet the needs of the other frameworks

Great Suggestion!

Cheers

Oli

**Comment by olifolkerd** [comment]
Looking into this further, both Bootstrap and Semantic UI base their table styling off of the **table** element itself.

As Tabulator does not use the table element but is instead made up of a number of specifically classed divs (the table element does not provide the flexibility necessary for all of Tabulators functions), it will not be possible to directly use the Bootstrap or Semantic-ui stylesheets to style the table.

However it should be a fairly simple task to create a stylesheet for each of the different frameworks to map the expected styles onto Tabulator, I could build them in LESS to allow for customization to match any variables used to configure the default framework stylesheets.

If that sounds like something that would be of use to you, could you let me know.

Cheers

Oli

**Comment by olifolkerd** [comment]
You will be happy to hear these features have now been pushed to the repo!

There are now themes available for Bootstrap 3 and Semantic UI.

Demos of each in action can be found [here](http://olifolkerd.github.io/tabulator/examples/#theming)

Documentation for each of the themes can be found [here](http://olifolkerd.github.io/tabulator/docs/#css)

Let me know how they workout for you.

Cheers

Oli

**Comment by michaelongithub** [comment]
Amazing, great! So incredibly productive and efficient. Will check it out, Thanks a lot.

**Comment by carterwe** [comment]
How about incorporating using jQuery UI themes since you already need jQuery UI?
