### ISSUE TITLE
rowDblClick firing when double-clicking on the resize handle

### ISSUE THREAD

**Issue by alainfrisch** [olifolkerd/tabulator#2370]
When the mouse is between two columns, the cursor turns into a left-right arrow, allowing the user to interactively resize the columns.  In this situation, double-clicking automatically resize the columns.  However, double-clicking also triggers the rowDblClick callback, and I believe it shouldn't.  As a comparison, the rowClick callback is not fired.

If the behavior is as attended, what is the suggested way to detect the situation so that the callback can decide to ignore such double-clicks?

**Comment by olifolkerd** [comment]
Hey @alainfrisch 

Thanks for your feedback, 

Im afraid i disagree with you there, if the row has a double click handler on it the user should be able to double click anywhere on the row to trigger the action, if they didnt know about the column handles then it would be a reasonable expectation.

If in your usage case you need to differentiate between the two types of double click, you can look at the target of the event object passed into the callback to find out the origin of the click event and ignore it if it is from a handle.

I hope that helps,

Cheers

Oli :)

**Comment by alainfrisch** [comment]
Thanks for your reply. Shouldn't the same argument apply to rowClick, then?

**Comment by olifolkerd** [comment]
Hey @alainfrisch 

You make a valid point, i will change the doubleClick event handling to be consistent with the click handling which has been around much longer.

I have pushed this change to the 4.5 branch, which will be released in a few weeks.

Cheers

Oli :)
