### ISSUE TITLE
Uncaught TypeError: Failed to execute 'selectNode' on 'Range': parameter 1 is not of type 'Node'

### ISSUE THREAD

**Issue by britvik** [olifolkerd/tabulator#2371]
If you double click (or click twice within 1s) on a tree [+] or [-] icon, there is this error in console:
`Uncaught TypeError: Failed to execute 'selectNode' on 'Range': parameter 1 is not of type 'Node'`

Reproducible even in the official example in Chrome:
http://tabulator.info/examples/4.4#tree

**Comment by olifolkerd** [comment]
Hey @britvik 

Good catch, thanks for letting me know. I will get that fixed in the next release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @britvik 

I have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)

**Comment by britvik** [comment]
@olifolkerd thank you for the swift fix :) good work
