### ISSUE TITLE
Table total is not showing in pdf download

### ISSUE THREAD

**Issue by vivekk-optimus** [olifolkerd/tabulator#2373]
I don't  see footer which shows whole table calculation in pdf download.

**Comment by 805bluebell** [comment]
You need to tell us how to reproduce the bug if any.
Basically, Can you bother to help us to help you?

**Comment by olifolkerd** [comment]
@vivekk-optimus 

Please provide a link to a JSFiddle that demonstrates your issue.

It is impossible for us to offer advice unless we know how your table is configured

Cheers

Oli :)
