### ISSUE TITLE
Update a value in a cell

### ISSUE THREAD

**Issue by ricardofpt** [olifolkerd/tabulator#2374]
Hey everyone, after many searches and browsing the docs, I´m still struggling with the following use case: in each row of my table there's a column that holds a paperclip icon (set through a formatter); on click, it will call a function, do some database operations and return a success or error message:

`{title:"Ações", formatter:attachIcon, align:"center", cellClick:function(e, cell) {  var result = attachProcess(proc_id, cell.getRow().getData().id, cell.getRow().getData().numero);`

Everything works as expected, but based on that result I would like to change the icon, or if that's not possible at least remove the paperclip icon. Any idea on how do I achieve that using the Tabulator API?

I´ve tried `cell.setValue()`, some `update()` methods as well, but to no avail.

Thanks in advance!

**Comment by tentus** [comment]
Most likely, you're in need of a redraw. The update method is asynchronous, so the formatter's being called before the change happens.

Here's a fiddle illustrating a very simplistic redraw:
https://jsfiddle.net/8bus6fa9/

**Comment by ricardofpt** [comment]
Yes, you're probably right :)

But there's one thing that I'm not understanding in your fiddle: you update 'numero', but 'numero' is not a column right? What changes is the 'Ações' column, so where's the relationship?

I'm sure it must be simple but I'm not getting it. Thanks for your patience!

**Comment by tentus** [comment]
It would be more proper to have the Ações column use the `field:'numero'` , I was just being lazy. The formatter uses `cell.getData().numero`, if we defined the field on the column then we could use `cell.getValue()` instead. 

I suspect you may be giving columns more weight than they actually have. The column isn't what gets changed on the click event, the underlying data (accessed through the row) is what is getting changed. The columns just define how to present that data when tabulator is looping through your rows.

**Comment by olifolkerd** [comment]
Hey @ricardofpt 

@tentus is right that you should give the Ações column a field name, you could then make the icon dependent on the value of that field and then use the row.update function to change the value which will prompt the paperclip cell to be redrawn.

no need to call the redraw function.

I hope that helps,

Cheers

Oli :)
