### ISSUE TITLE
Rows are not rendering correctly morethan #100 rows.

### ISSUE THREAD

**Issue by Muralee99** [olifolkerd/tabulator#2375]
Firstly congratulations for your great work on tabulator, it is doing greatly.

Tabulator version:  4.2
Browser: Chrome

**Problem description:** 
I am adding more than 100 rows and changing the pagination options[20, 50, 100]
With 20 rows, UI is rendering correctly.
When I change to 50 or 100 only partial rows are rendering and empty space is displaying 
Note: If I add new row, empty space is filling with rest of the rows.
I have added images for reference.

Below is my tabulator constructor.
var table = new Tabulator("#"+ self.get('name'), {
            data:self.get('tableData'),
            selectable:1,
            height:"calc(100% - 250px)",
            layout:"fitColumns",         
            addRowPos:"bottom",
            pagination:"local",
            paginationSize:100,
            paginationSizeSelector:[20, 50, 100],
            columns:self.get('tableColumnData'),
            keybindings:true,
            virtualDomBuffer:300,
            resizableColumns:"header",
            placeholder:"No Data Available",

**Pagination with 20 rows:**
![image](https://user-images.githubusercontent.com/5547028/65387167-0ca23000-dd62-11e9-9fe2-3525238447c6.png)

**Pagination with 50 rows:**
![image](https://user-images.githubusercontent.com/5547028/65387213-8f2aef80-dd62-11e9-9d34-882b3439b8e3.png)

Thanks in advance.

**Comment by tentus** [comment]
If you could post a fiddle that would help tremendously, but if I had to guess, maybe the virtualDomBuffer is too small?

**Comment by olifolkerd** [comment]
The virtualDomBuffer isn't used when pagination is enabled, but tentus right that a js fiddle would be really helpful

**Comment by Muralee99** [comment]
Sorry for delayed reply. @tentus  @olifolkerd Many thanks for your prompt response.
I have increased the virtualdombuffer to virtualDomBuffer:6000.
Now white space is coming as earlier.
Few more clarifications:
On what basis I can decide the virtualDomBuffer size. Is there any negative consequence if it increases.
If we change the table height (height:"calc(100% - 250px)",), whether table.redraw() is mandatory.

Thank you for your time.

**Comment by olifolkerd** [comment]
@Muralee99 

The ***virtualDomBuffer*** is not used at all when pagination is enabled, so changing the setting will have no effect at all.

Please create a JSFiddle to demonstrate your code in action or we will be unable to offer you assistance.

Cheers

Oli

**Comment by Muralee99** [comment]
@olifolkerd 
I am unable to reproduce it in jsfiddle(below link), it is working correctly here.
[https://jsfiddle.net/t63nyp58/1/]

I am using tabulator plugin in Ember js
As you correctly stated I am changing the table height.

In the constructor table height is [height:"calc(100% - 250px)",]

while adding new row I am changing the table height to false, I am redrawing the table.

addNewRow() {
// I am adding the below 2 properties, to set the focus(cursor) on first column while adding the new row automatically.
//without these properties I am not getting the focus.
        self.get('table').height = false;
        self.get('table').redraw = true;
       self.get('table').addRow({ id: parseInt(self.get("rowIdMax")) }).then(function (row) {
                   self.get('table').selectRow(self.get("rowIdMax"));                            
                   var cell = row.getCell(self.get('cellFocusField'));                    
                   cell.getElement().focus();  
        }
}

Thanks for your valuable suggestions.

**Comment by olifolkerd** [comment]
@Muralee99 

You cannot directly alter properties on the table like redraw and height. you can only call functions on the table once it has been instantiated.

you shouldnt need to change the table height when you add a row.

Oli :)
