### ISSUE TITLE
Scroll bar for a column, if the content does not fit in the row height.

### ISSUE THREAD

**Issue by geekyogurt** [olifolkerd/tabulator#2379]
Resizable rows option does allow the user to change the height the row to view all the content, but it is sometimes not intuitive to the user that there is more content in that column. In such cases a scrollbar for that column would be pretty helpful.

**Comment by tentus** [comment]
Makes sense. In the meantime, perhaps the textarea formatter could give users a clean experience.

**Comment by geekyogurt** [comment]
@tentus If the data is being dynamically added, textarea formatter does not give clean view.

**Comment by tentus** [comment]
I added a dynamic add (https://jsfiddle.net/tentus/4Lxzjkav/10/) and it looks ok on my end, can you provide an example illustrating the issue?

**Comment by olifolkerd** [comment]
Hey @geekyogurt,

In my opinion nesting scroll bars leads to a messy and unintuitive user interface, so i would not be looking to add that to Tabulator.

That being said tabulator allows for [Custom Editors](http://tabulator.info/docs/4.3/edit#edit-custom) so you can add this functionality yourself if you need it

Cheers

Oli :)
