### ISSUE TITLE
Sub Group Option

### ISSUE THREAD

**Issue by ihmunro** [olifolkerd/tabulator#238]
Hi Oli

Would it be possible to request a sub group feature to be added to Tabulator ?

Iain

**Comment by olifolkerd** [comment]
Hi Ian,

Thanks for getting in touch, could you give a usage case for the subgroup idea. how would you see it working?

Cheers

Oli

**Comment by jdecastroll** [comment]
I've a usage case for subgroup, is possible to show this data:

[
	{
		"DATOS": {
			"blocker_violations": "1",
			"minor_violations": "20",
			"duplicated_lines_density": "2",
			"major_violations": "74",
			"string": "1000",
			"ncloc": "461",
			"lines": "508",
			"critical_violations": "1"
		},
		"DATE_AUDIT": "21/12/2016  09:04:35",
		"FAULT_DATE": "21/12/2016  09:04:35",
		"APLICATION": "PORTAL",
		"OBJECT": "Test.java",
		"_index": 0
	}
]

**Comment by olifolkerd** [comment]
how would you like to see subgroups rendered in the table?

**Comment by jdecastroll** [comment]
If possible as a table into a cell

**Comment by ihmunro** [comment]
Hi Oli

Thanks for getting back to me. 

Yes, I have a usage case. 

I have data coming from my database which is broken out by customer and date. The main group is customer and subgroup is date. 

So when I click on the group customer, I will then see dates as subgroups - clicking on the date will give me all the details. 

Iain

**Comment by sistason** [comment]
I'd like to also show my interest in this feature.
As in #410 stated, a Country->City would then be better possible than now.

I'd basically want a table of countries, with a sub-row/group of cities. 
This is currently possible by assigning each city its country, groupby: country and getting this data to display in the groupHeader. 
That has the problem, that the table doesn't really know about countries, I would like to add/delete/move/select/callback countries as items of the table, not as groupHeaders with raw html crudely implementing the functionality one needs...

I could think of a solution like:
- columns: list  => current behaviour
- columns: object => {country: [column, column], city: [column]}, so to set the columns on data-attribute.
...but I can think of many problems with that, too. Maybe you find a good implementation for that ;)

**Comment by olifolkerd** [comment]
Hey sistaston,

You will be happy to hear that the sub-group option will be comming in this months 3.2 release :)

Thanks for showing your support for the feature, Tabulator's progress is guided by the needs of the community.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey,

You will be happy to hear that Tabulator 3.2 has just been released, and with it the Multi-Level Grouping options, you simply pass arrays to the appropriate grouping options:
```js
groupBy:["gender", "color"], //group by gender then favourite color
```

Full information can be found in the [Grouping Documentation](http://olifolkerd.github.io/tabulator/docs/3.2/#grouping)

Cheers

Oli
