### ISSUE TITLE
Dynamic header filters

### ISSUE THREAD

**Issue by ruggbo** [olifolkerd/tabulator#2380]
Hi, how can i programmatically add and remove header filters?

thanks in advance
Ruggbo

**Comment by tentus** [comment]
As seen in http://tabulator.info/docs/4.4/filter#header

> You can programatically set the header filter value of a column by calling the setHeaderFilterValue function, This function takes any of the standard column component look up options as its first parameter, with the value for the header filter as the second option
>
> ```table.setHeaderFilterValue("name", "Steve"); //set header filter for name column to  "steve"```

**Comment by olifolkerd** [comment]
If you want to physically remove/add the column filter, you will need to remove the column and add a new column with the updated definition.

The [Column Manipulation Documentation](http://tabulator.info/docs/4.3/columns#replace) explains the functions to use.

I hope that helps,

Cheers

Oli :)
