### ISSUE TITLE
Resizing height of table automatically with a Maximum height predefined

### ISSUE THREAD

**Issue by 805bluebell** [olifolkerd/tabulator#2381]
I am trying to draw a table using
```
var table = new Tabulator("#example-table", {
          ...
          height: "75vh",
          ...}
```
But, the height is always `75vh` even though contents are less which looks ugly. See the dark gray area below the table.
![Capture](https://user-images.githubusercontent.com/36482818/65580607-9e46b300-df97-11e9-8190-b6961836ad05.PNG)

I tried using the below so that height is never above a value & resizes automatically if less content is there.

```
var table = new Tabulator("#example-table", {
          ...
          height: "auto",
          maxHeight: "75vh",
          ...}
```
Suggest me some hack as I coudn't get anthing in documentation.
Lots of options are available for row. 

Can we have some for column as well?

**Comment by olifolkerd** [comment]
if you set the table height to "100%" and then resize the parent element it will resize the table correctly.

you can us the ***setHieght*** function to change the table height manually if you want

Cheers

Oli :)
