### ISSUE TITLE
custom editor return 

### ISSUE THREAD

**Issue by niexuzhong** [olifolkerd/tabulator#2382]
The editor of column is same for tabulator now. but I want to use different editor for same column in different. some of them may be text,select or readyonly cell for different row. I use customer editor to realize it. I check the row number to determine which type of editor return.  for the cell couldn't be edit. I return null. although it can solve it. but it display "underined" error in the console. if I want to remove this error. what should I return? or Is there better method to slove it?
 :)

**Comment by olifolkerd** [comment]
Hey @niexuzhong 

Please create a JS fiddle to demonstrate your issue, we can then offer advice on how to solve it

The [Editor Documentation](http://tabulator.info/docs/4.4/edit#edit-custom) outlines the acceptable return values

Cheers

Oli :)

**Comment by niexuzhong** [comment]
Dear olifolkerd:
            Thank for your kindly reply. I just browse web page about custom edit provided by you. I can use editcheck to solve my question. I can use editcheck to return false when some cells is read only. Thanks
:)
