### ISSUE TITLE
Edge miscalculates header height when using vertical text

### ISSUE THREAD

**Issue by tentus** [olifolkerd/tabulator#2383]
**Describe the bug**
Edge, in its infinite wisdom, will choose to make the header of a table ridiculously tall if you use vertical text in the headers.

**Tabulator Info**
- Tabulator version 4.4.1

**Working Example**
We can see this by viewing http://tabulator.info/examples/4.4#column-vertical actually, no need for a fiddle.

**To Reproduce**
1. Open Edge
2. Goto http://tabulator.info/examples/4.4#column-vertical

**Expected behavior**
Height of the header should be as tall as the text requires, and no more.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 44

**Smartphone (please complete the following information):**

**Comment by olifolkerd** [comment]
Hey @tentus 

As Edge is about to go through a major overhaul and switch to using Chromium in the not too distant future, i am not going to action any Edge specific transition until after the switch.

If this is still an issue after the switch please let me know and i will look into it further.

Cheers

Oli :)

**Comment by tentus** [comment]
Fair enough. Looks like the beta version of Edge (read: chromium) handles it correctly, so it's unlikely to crop back up.
