### ISSUE TITLE
The tree structure of nested data does not fully support correct headerFilter, copy, download, and bottomCalc

### ISSUE THREAD

**Issue by ctlkkc** [olifolkerd/tabulator#2384]
**Describe the bug**
The tree structure of nested data does not fully support correct headerFilter, copy, download, and bottomCalc. 

**Tabulator Info**
- tabulator.min.4.4.0.js
- An example table object can look like this:
```
[{"name":"CLC1","_children":[{"name":"X1","NV":174966820,"Qty":90820}]},{"name":"CLC2","_children":[{"name":"X2","NV":143696020,"Qty":73268}]},{"name":"CLC3","_children":[{"name":"T1","NV":33666400,"Qty":33300}]},{"name":"CLC4","_children":[{"name":"X3","NV":58653420,"Qty":34600}]},{"name":"CLC5","_children":[{"name":"T2","NV":304360,"Qty":6440}]}]
```

**To Reproduce**
A table can set up like below:
```
				dataTree: true,
				dataTreeStartExpanded: true,
				rowClick: function (e, row) {
					row.treeToggle();
				},
				dataTreeChildIndent: 50,
				columns: [
					{ title: "Filters", field: "name", headerSort: false, headerFilter: "input", headerFilterFunc: customHeaderFilter, headerFilterPlaceholder: "Search any filter here"},
					{ title: "Qty", field: "Qty", headerSort: false, width: 200},
					{ title: "NV", field: "NV", headerSort: false, width: 200}
				]
```

**Expected behavior**
Expected behaviors:

1. headerFiltershould return results on all nested levels .e.g. filter 'X1' should return both 'CLC1' and its child rows. If row 'CLC1' is collapsed, should still return the row 'CLC1' and allow user to expand it;
2. copy, download should return the whole active (non-collapsed rows), instead of only the top parents;
3. bottomCalc: bottomCalc:customCalcFunctionshould also include the child rows' available column values, or data

the above may all relate to the selected rows are only the parent rows, in this case, the rows selected are:
```
Filters,Qty,NV
CLC1,,  
CLC2,, 
CLC3,, 
CLC4,,
CLC5,,
```

**Comment by olifolkerd** [comment]
Hey @ctlkkc 

These are known limitations with the tree data system.

Tabulator is a very complex system with many features, it takes time to integrate all the features with one another, The data tree system was added as a view only feature, that with each release is being integrated with each of Tabulators other modules.

Further integrations with other parts of the system will be coming in the next few releases.

Cheers

Oli :)

**Comment by ctlkkc** [comment]
Thanks @olifolkerd 

Will expect the new releases to integrate them :)

**Comment by ctlkkc** [comment]
@olifolkerd if possible can you enable copy function to the tree table first? thanks
