### ISSUE TITLE
Add onRendered callback to custom titleFormatter

### ISSUE THREAD

**Issue by yuukuari** [olifolkerd/tabulator#2386]
Hello,

We can specify a custom `formatter` function for cells with the following signature : `function(cell, formatterParams, onRendered)` with _onRendered_ a function used to set a callback to be called after the cell has been rendered.

There is another formatter specific to headers, `titleFormatter` which is supposed to work the same way as cells formatters - according to the documentation. But its signature does not include the _onRendered_ parameter, so it is not possible to specify a callback.

It would be great to add that callback, so that we can register events (for example) on some header titles **after** they are being rendered.

Thanks !

**Comment by olifolkerd** [comment]
Hey @yuukuari 

Thanks for the feedback, i think that is a very good idea, i will look at adding it for the next release

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @yuukuari 

I have pushed the code for this update to the 4.5 branch which should be released in a few weeks.

Cheers

Oli :)

**Comment by yuukuari** [comment]
Great ! That was fast ^^

Thanks for you awesome work :)

**Comment by olifolkerd** [comment]
Hey @yuukuari 

You will be happy to hear i have just pushed this feature onto the 4.5 brnach which will be released in a few weeks.

Cheers

Oli :)
