### ISSUE TITLE
Memory from Virtual DOM is never freed

### ISSUE THREAD

**Issue by bertoverflow** [olifolkerd/tabulator#2387]
**Describe the bug**

**Tabulator Info**
- Which version of Tabulator are you using?
4.4.1
- Post a copy of your construct object if possible so we can see how your table is setup
```
const tabulatorTable = new Tabulator('#tabulator', {
      data: generatedData, // link data to table
      reactiveData: false, // enable data reactivity
      columns: columns, // define table columns
      selectable: true,
      selectableRangeMode: 'click',
      layout: 'fitColumns',
      height: 500
    });
```

**Working Example**
https://jsfiddle.net/q7e5ta6o/4/

**To Reproduce**
1. Open the JS-Fiddle an take a Memory-Snapshot with Chrome: around 50 MB in my Case
2. Scroll for a while inside the table
3. Take another Memory-Snapshot with Chrome: Around 200 MB
4. Scroll through the whole table
5. Take another Memory-Snapshot with Chrome: Around 450 MB

**Expected behavior**
The memory should not increase that much.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: chromium
 - Version: 65.0.3325.181

**Additional context**
I guess the additional memory comes from the new rows and cell-objects that are created for the Virtual DOM. Is this the expected behaviour? Or is there a memory leak?

**Comment by olifolkerd** [comment]
This is expected behaviour, as you scroll the DOM the rows are created and stored in memory for when you next scroll to them.

If the table is cleared the garbage collector should clear the rows
