### ISSUE TITLE
No Scrollbar on the Table when virtualDom is set to false

### ISSUE THREAD

**Issue by dota2Pro** [olifolkerd/tabulator#2389]
**Describe the bug**

 when setting `virtualDom: false` and table has a fixed height, there are no scrollbars to scroll all rows

https://jsfiddle.net/dota2pro/4etxd82f/2/

If I turn on virtualDom I can see scrollbars

https://jsfiddle.net/dota2pro/y6gfxcrd/2/

using Latest version 4.4.1

This can be fixed using CSS on my side, just to bring to attention raising a bug

**Comment by olifolkerd** [comment]
This is the correct behaviour, when the virtual DOM is disabled the table will display all the rows simultaneously, so there will be no scroll bar

Cheers

Oli :)
