### ISSUE TITLE
ie11 table-load sample

### ISSUE THREAD

**Issue by y-ry** [olifolkerd/tabulator#239]
thank you for nice plugin.

I used this plugin with table tags.
(http://olifolkerd.github.io/tabulator/examples/#table-load)
with ie11(win7) has error with 
 Unable to get property 'name' of undefined or null reference  (LINE 343)
![tabulator](https://cloud.githubusercontent.com/assets/15828418/24491221/47a15c38-1561-11e7-8cf8-8db6e399eb66.png)

In some case 'attrib' return 0 and attrib.name is undefined.
This error occur your sample code page and my site.

I modified your code,like
BEFORE:
if (attrib.name && attrib.name.indexOf("tabulator-") === 0) {
AFTER:
if (attrib && typeof attrib.name !== 'undefined' && attrib.name.indexOf("tabulator-") === 0) {

**Comment by olifolkerd** [comment]
i have just pushed a fix for this to the repo, if you refresh your browser it should be working now.

Cheers

Oli
