### ISSUE TITLE
Range Selection not working with Checkbox column input

### ISSUE THREAD

**Issue by fingers10** [olifolkerd/tabulator#2391]
When we have checkbox column enabled in tabulator, and if we try to make a range selection with checkbox input the range selection fails. Example Consider a table with 5 rows. Click on first row checkbox and hold shift key and press on last row checkbox; range selection will fail here. But on the flip side this works if you click on checkbox column cells not on checkbox input.

Please refer https://github.com/olifolkerd/tabulator/issues/2208#issuecomment-535564381

Thanks,
fingers10

**Comment by olifolkerd** [comment]
Hey @fingers10 

If you are having issues please create a JS fiddle that demonstrates the issue and provide step by step instructions on how to replicate it.

It is very hard to gain an accurate understanding of your issues from a simple description, i need to be able to understand in context with the tables code in a working example.

There are templates setup on the issues list when your create a bug report specifically to prompt you to fill in the details needed for me to successfully fix the issue,

When raiding bug requests please fill these in, it will make it much easier to get to the bottom of the issue and make it much easier to fix.

Cheers

Oli :)

**Comment by fingers10** [comment]
Dear @olifolkerd ,

I'm sorry for short description. Since I added a reference to a comment, I thought it would be better to leave without much detail.

Here is the [fiddle link](https://jsfiddle.net/angeliski/1vuqz42f/3/).

Steps to reproduce:

1. Open the above link.
2. Click exactly on first row checkbox.
3. Hold Shift Key.
4. Now click exactly on third row checkbox .
5. Range selection fails.

Thanks,
Abdul

**Comment by olifolkerd** [comment]
Hey @fingers10 

Thanks for the JS Fiddle, that was a big help.

Yes it looks like the tick selection formatter does not pass through the key states when handling the selection, i will resolve this in the next release.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @fingers10 

I have pushed an update to fix this to the master branch and will include it in the next patch release.

Cheers

Oli :)
