### ISSUE TITLE
Click and drag a text to copy selects a row when selectable: true is set

### ISSUE THREAD

**Issue by fingers10** [olifolkerd/tabulator#2392]
**Describe the bug**
I have noticed another issue. when tabulator is configured with `selectable: true` and now if we click and drag a text in a cell to copy it; the row will be selected. Any ways to avoid this? right now I have done a work around like adding a cellClick as shown below,

```js
cellClick: function (e, cell) {
    e.stopPropagation();
}
```

**Tabulator Info**
- v4.4.x

**Working Example**
[Tabulator Example](http://tabulator.info/examples/4.4#selectable)

**To Reproduce**
Example, click in the above link try to copy the text Bob from the first row name column and you can see the row getting selected.

**Expected behavior**
Row should not get selected when we click drag and copy a text.

**Desktop (please complete the following information):**
 - OS: win10
 - Browser: Chrome
 - Version: Latest

Thanks,
fingers10

**Comment by olifolkerd** [comment]
Hey @fingers10,

Depending on the type of selection being used this may be desirable, In your case i can see it isnt and you have used an effective workaround to avoid the issue.

Cheers

Oli :)
