### ISSUE TITLE
Tabulator Algolia results point at 4.3

### ISSUE THREAD

**Issue by tentus** [olifolkerd/tabulator#2396]
This doesn't really seem worth a github issue, but just a heads up, if you search on tabulator.info the algolia results send you to the prior version, not 4.4.

**Comment by olifolkerd** [comment]
Hey @tentus 

Thanks for the headsup, i must have forgotten to update the algolia config with the last update. I have made a PR with the update in to them, it usually gets updated within 24 hours.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
All sorted
