### ISSUE TITLE
Custom celleditor issues with Safari on a IOS device

### ISSUE THREAD

**Issue by rhagstrand** [olifolkerd/tabulator#2397]
**Describe the bug**
A custom editor MUST handle the blur() event by calling either success() or cancel() right?. This causes issues when viewing the webpage on a IOS-device. If I use for instance a custom textarea input with two buttons (Save, abort) for editing, hiding the virtual keyboard causes blur() to trigger which is not what I want. If I click the save-button in my case, blur() triggers first and aborts the edit.

**Tabulator Info**
- 4.4.1

**Working Example**
Please include a JS Fiddle or Code Pen that demonstrates the problem, it is very hard to diagnose an issue from a simple description

**To Reproduce**

**Expected behavior**
IOS virtual keyboard show/hide should not trigger blur()-event.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Iphone7
 - OS: IOS 13
 - Browser Safari

**Additional context**

**Comment by olifolkerd** [comment]
With a custom editor you can do what you want. If you want to keep the
editor open on blur then you can simply ignore the event

**Comment by rhagstrand** [comment]
Oh, then I just got this wrong :) "It is important to note that a custom editor must specify how to handle a blur event on its element **by either calling the success or cancel functions**"

In my case I just used the mousedown event on my buttons which triggers before blur and used e.preventDefault. Works like a charm now, thanks for clarifying.

**Comment by olifolkerd** [comment]
Yes the reason that is in the docs is because if you use it on the desktop and click to another cell the usual expected experience would be to close the editor. If you don't want that to happen you don't have to do it, but it may cause your desktop users issues
