### ISSUE TITLE
Default copyFormatter doesn't handle cr/lf properly

### ISSUE THREAD

**Issue by Darkseal** [olifolkerd/tabulator#2398]
If you activate the clipboard module and use it with the default formatter to copy/paste a table to Excel (using CTRL+C), all the columns containing CR/LF won't be properly formatted and will cause new lines to span into Excel. The bug seems to be in the `/src/js/modules/clipboard.js` file, rows 891-906.

More specifically, the `value` var is calculated correctly, however its updated value is not being used as the `forEach` function handles by variable and not by reference, therefore the original value (within the `row` array) is being added to the `output` (line 905).

- Tabulator Version: **4.4**

**Proposed fix**
Here's the manual patch I applied to fix the issue for good: 

	data.forEach(function (row) {
		var newRow = [];
		row.forEach(function (value) {
			if (typeof value == "undefined") {
				value = "";
			}

			value = typeof value == "undefined" || value === null ? "" : value.toString();

			if (value.match(/\r|\n/)) {
				value = value.split('"').join('""');
				value = '"' + value + '"';
			}
			newRow.push(value);
		});
		output.push(newRow.join("\t"));
	});

The above code replaces rows 891-906 of the `clipboard.js` file.

**Comment by Rodbjartson** [comment]
What a spot!

**Comment by olifolkerd** [comment]
Pull request to fix this has been merged in. it will be included in the 4.5 release in a few weeks

Cheers

Oli :)
