### ISSUE TITLE
Problem with a lot of columns and only one row

### ISSUE THREAD

**Issue by sydesb** [olifolkerd/tabulator#24]
Hi, thank you for tabulator. With ajax, there is a problem when there is a lot of columns and only one row : the value is hidden and it isn't possible to view it.
![capture](https://cloud.githubusercontent.com/assets/16446916/15272319/c32cfa72-1a73-11e6-8aec-fdde994c224b.PNG)

**Comment by olifolkerd** [comment]
did you define a table height? could you post the code for your setup options object.

**Comment by sydesb** [comment]
I don't define height because with ajax, the number of row change. Is it possible to do it ?

**Comment by olifolkerd** [comment]
looks like a rendering glitch when no height is defined, it dosnt take account of the scroll bar when it overflows.

I will release an update this afternoon that fixes the rendering glitch

**Comment by sydesb** [comment]
Thank you very. Tabulator is great !

**Comment by olifolkerd** [comment]
Thanks, it is always nice to hear Tabulator is appreciated.

I have just released Tabulator version 2.2 which includes a fix for the rendering issue you have been having.

For full details of the update checkout the [Tabulator Website](http://olifolkerd.github.io/tabulator/news/)

Let me know if there are any other features you would like to see.

**Comment by sydesb** [comment]
thank you for this update.

**Comment by olifolkerd** [comment]
I have just added another update for you.

I noticed that you were using wrapped text in your column headers and that the bordered weren't rendering properly, this is now fixed.

I haven't released a numbered version for this fix yet, but it is available on the master branch now.

**Comment by sydesb** [comment]
Thank you very much. 
I have a question. I use expandable div :
![capture](https://cloud.githubusercontent.com/assets/16446916/15275908/7d341590-1ad8-11e6-8249-d876690e0d5a.PNG) (from : [https://almsaeedstudio.com/themes/AdminLTE/pages/widgets.html](https://almsaeedstudio.com/themes/AdminLTE/pages/widgets.html ))
But when i expand, the height of the table is 0. I can't fix the height because with ajax, the number of row can change. 
Then i do this : 
`jQuery(".tableaustat").on("click", ".boutoncollapse", function(){
setTimeout(function(){ $("#example-table").tabulator("redraw", true); }, 10);
});`

But i would like the height of the table is calculate with the number of row and not with the height of the parent div(here 0px). Is it possible ? (I am sorry for my very bad english....)

**Comment by olifolkerd** [comment]
Using the ***redraw*** function is the correct approach in this case

The height of the table is calculated based on the height of the elements contained in the table (there is no fixed row height as you could use a formatter that has a very tall element in it and the rows have to be able to adapt to that), it is calculated this way to allow the various scroll bars to be created appropriately.

As a result it is not possible to calculate the height of the table if the data is loaded when it is not visible as the elements that make up the table will not yet have been rendered and will therefore have a height of 0.

In this instance the correct approach is to call the redraw function when you make the table visible.

**Comment by olifolkerd** [comment]
I have had an idea so i may be able to make it work differently in cases where there is no height set.

I will have a play over the next couple of days and let you know when i have something.

**Comment by sydesb** [comment]
Thank you again. It's just because i lost the animation when i expand.

**Comment by olifolkerd** [comment]
I have uploaded a new adjustment for you. the table height should render appropriately now even when hidden, but you will still have to call the redraw function when the table is shown to make the contents of the rows render correctly.

You should only need to use the simple redraw function, you wont need to pass the ***true*** argument.

**Comment by sydesb** [comment]
Thank you again and again !
It works perfectly ! And i don't know why but it works too without redraw.

**Comment by olifolkerd** [comment]
Happy to help!

If you aren't using any formatters and are just showing plain text, then it probably will be working without redraw.

**Comment by sydesb** [comment]
ok, i understand. Then i let the redraw.
But the header doesn't work anymore. Is it normal ?
![capture](https://cloud.githubusercontent.com/assets/16446916/15276814/02925f7a-1af3-11e6-8a56-bffdbc68fd3e.PNG)

**Comment by olifolkerd** [comment]
just uploaded the fix for that

**Comment by sydesb** [comment]
I m not in front of my computer anymore. I ll try it tomorow. THANK YOU !

**Comment by sydesb** [comment]
Very fine ! Thank you again. I'm glad I chose Tabulator ! Bravo !
