### ISSUE TITLE
Custom data grouping 

### ISSUE THREAD

**Issue by primeval1** [olifolkerd/tabulator#240]
Hello, first of all congratulations for this awsome data grid. I would like to ask if it is possible to use groupby to group data based on some custom value. eg: group together data that have id > 100 and an other group with those that have  id <=100. 

I've seen in the documentation that i can use a function to group data based on multiple collumns, so i thought  that maybe i might have to do something in that function but it is not really clear in the example. 

thanks in advance.

**Comment by olifolkerd** [comment]
Hey,

Thanks for getting in touch, its always great to hear people are enjoying using Tabulator.

What you are asking for can be achieved using the ***groupBy*** and ***groupheader*** options:

```js
$("#example-table").tabulator({
    columns[...],
    groupBy:function(data){
        return data.id <= 100; //make two groups with id <=100 and >100;
    }
    groupHeader:function(value, count, data){
        return "ID "+ (data[0].id <= 100 ? "<=" : ">") + " 100" + "<span style='color:#d00; margin-left:10px;'>(" + count + " items)</span>";
    },
});
```

Let me know if that helps you out.

Cheers

Oli

**Comment by primeval1** [comment]
Oh! i see! it is that simple after all. I was actually trying to pass something like that```
 ```
 groupBy:function(data){
        return data.id+"<= "+100; 
    } 
```
```, because in the documentation it says that it should return a string but i guess it is just for the case i want to combine collumns, i didnt even thought to do the obvious thing. Thank you very much for the quick response.
