### ISSUE TITLE
Add frozen property to Persistent Column Layout

### ISSUE THREAD

**Issue by yuukuari** [olifolkerd/tabulator#2402]
Hi :)

Persistent column layout is a great feature, but unless i'm missing something, it won't save the frozen state of columns.

I have added a configuration modal to manage columns properties (order, visibility, frozen, etc.) but when the page is reloaded and the table displayed again, columns are not frozen the way they should be. It will always use the frozen property of the column set in the options, instead of replacing it by the stored value.

It would be great that the frozen state of columns is stored along with other columns' properties, so that the table is exactly the same when it's reloaded.

Thanks ^^
Yuuk

**Comment by yuukuari** [comment]
Seems there are only 2 lines to add :
In _Persistence.prototype.mergeDefinition_ :
`from.frozen = Boolean(column.frozen)`

And in _Persistence.prototype.parseColumns_
`def.frozen = Boolean(column.getDefinition().frozen)`

Works for me, columns' frozen state is now persistent, but its not configurable, it will impact all tables using `persistentLayout:true` option.

Should i submit a PR ?

**Comment by yuukuari** [comment]
Or else we could let the user decide more precisely which column properties he wants to make persistent, for instance by letting him pass an array in persistentLayout option : `persistentLayout: ['width', 'visible', 'frozen']`. Or add a specific option `persistentLayoutProperties`.

There is a property in the Persistence contructor, `persistProps` which seems to be useless : `this.persistProps = ["field", "width", "visible"];`. It could store the column properties that are meant to be persistent.

**Comment by olifolkerd** [comment]
Hey @yuukuari 

Thanks for getting in touch.

A number of users have already requested this feature and It is actually already on the roadmap for the next release to increase the options available and allow the developer to decide what is persisted.

If you hold off for a couple of days you will see it appear on the 4.5 branch.

Cheers

Oli :)

**Comment by yuukuari** [comment]
Ah that's great ! I didn't find that specific feature request on github, is there a link with details ?
I will update my code once it's released, thanks ^^

**Comment by olifolkerd** [comment]
Hey @yuukuari 

Looking into your particular usage case more, there is no way to alter the frozen state of a row once it has been defined, so there is nothing to persist.

How are you changing the frozen state of the columns, are you adding and removing columns as depending on how you are doing this will affect whether it is detected by the table.

Could you create a JS Fiddle that demonstrates your setup

Cheers

Oli :)

**Comment by yuukuari** [comment]
I am altering the frozen state by calling setColumns with updated columns definitions.
Here is a video of the result : https://we.tl/t-xKblSwne7F.

**Comment by yuukuari** [comment]
Here is a JS Fiddle wit a simple example
https://jsfiddle.net/2t9ynu5L/2/

- Try to resize a column,
- refresh page to check column size is persistent,
- then click on the "Freeze" button,
- check that second column is now frozen,
- refresh page to see that column is not frozen anymore.

**Comment by olifolkerd** [comment]
Hey @yuukuari 

Thanks for the useful example.

I have made a push with the functionality to the 4.5 branch and will include it in the release in a few weeks time.

Cheers

Oli :)

**Comment by yuukuari** [comment]
Hi Oli,

Great ! Did you also add `freezeColumn` and `unfreezeColumn` methods to set the frozen state of a column (like `hideColumn` and `showColumn` do for the visible state) ? We still can change the frozen state with `setColumns`, but it might be useful !

Thanks ^^
