### ISSUE TITLE
Export/Import tabulator configuration

### ISSUE THREAD

**Issue by mhterres** [olifolkerd/tabulator#2403]
It would be nice to have a way to export the whole tabulator object configuration (layouts, columns, sort and filter data, all except data) and then have an option to import it back.

This way you could save the configuration on a DB and use it later when you need to reload the page.

**Comment by takuy** [comment]
Sounds like you should be able to use native Persistent Config options for this.

http://tabulator.info/docs/4.4/persist

You should also be able to extract these from localstorage yourself and store it server-side if needed. As long as you restore them before a Tabulator is initialized, it should work.
