### ISSUE TITLE
Is there a way to inject HTML elements into cells?

### ISSUE THREAD

**Issue by maxxheth** [olifolkerd/tabulator#2405]
Hi! I'm not sure if this really qualifies as an issue, but here it goes.

I'd like to be able to inject HTML elements into cells, but I couldn't find a method that would allow me to do that, so I came up with a workaround:

<pre>
const table = new Tabulator('#example-table', {

        data: data,
        columns: makeColumns('TLD', 'Company', 'Price', 'More TLDs')('tld', 'company', 'price', 'more'),
        layout: 'fitColumns',
        tableBuilt() {

            console.log('The table has been built!');

            document.addEventListener('DOMContentLoaded', () => {

                const TabulatorCellsAttrMore = [...document.querySelectorAll('[tabulator-field="more"]')];
                
                /**
                 * Grab all the tabulator cells and filter out the ones that have "more" assigned to the
                 * tabulator-field attribute.
                 * 
                 * */

                const MoreTabTextKids = TabulatorCellsAttrMore
                
                    .map(cell => cell.childNodes)
                    
                    .map(children => [...children]
                        
                    .filter(child => child.nodeType === 3))

                    .map(child => child[0]);

                // Get rid of the text nodes.

                TabulatorCellsAttrMore.forEach(cell => {

                    const cellChildren = [...cell.childNodes];

                    const textKid = cellChildren.filter(child => child.nodeType === 3)[0];

                    if (textKid !== undefined) {

                        cell.removeChild(textKid);

                    }

                });

                // Inject the anchor links containing previous text nodes.

                TabulatorCellsAttrMore.forEach((cell, cellIndex) => {

                    if (MoreTabTextKids[cellIndex] === undefined) return;

                   // There are supposed to be strings containing the opening and closing tags of an anchor element below, but for some reason it's 

                    cell.insertAdjacentHTML('afterbegin', '\<a href\="#"\>' + MoreTabTextKids[cellIndex].nodeValue + '\<\/a\>'); 
                
                });

            });
        }

      });
</pre>

So is there a better way to do this if such a feature exists? If not, I guess that would be my feature request. This package is awesome btw! =)

**Comment by maxxheth** [comment]
If the code example isn't clear, I can come up with a better example on CodePen or Fiddler later on when I'm free. Basically, my intent was to take the text nodes from a certain column of cells, wrap them in anchor tags, and inject those anchor tags back into the cells.

**Comment by olifolkerd** [comment]
You should use formatters to set the contents of cells.

It is not safe to manipulate the contents of the table from outside of Tabulator. Because it uses a virtual DOM only the visible rows actually exist at any point in time so any external function trying to alter the rows will only change some and those will be destroyed when the table is scrolled.

Look at formatters in the documentation and that should sort you out. 

Cheers

Oli :)

**Comment by maxxheth** [comment]
Wow, that was fast. Thanks Oli! I'll check those out and go back to the drawing board then. =)
