### ISSUE TITLE
Entering a cell with a select editor triggers the values function twice

### ISSUE THREAD

**Issue by shadlan** [olifolkerd/tabulator#2407]
**Describe the bug**
When I click on a editable cell of the *select* type with a custom values function, the function is triggered twice.
On the example, the Run Count gets incremented twice.

**Tabulator Info**
- Made the fiddle with version 4.4.3

**Working Example**
https://jsfiddle.net/shadlan/vbqfsjzd/11/

**To Reproduce**
Run the fiddle and click on any name to reproduce.

**Expected behavior**
The values function should only be called once everytime I start editing the cell.

**Desktop (please complete the following information):**
Using Chrome Dev 79.0.3921.0 on windows 10, but other coworkers also reported the bug on the stable Chrome

**Comment by olifolkerd** [comment]
Hey @shadlan 

Thanks for the headsup,

I will look to get this fixed in the 4.5 release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @shadlan 

I have pushed a fix for this to the 4.5 branch that will be released in a few weeks.

Cheers

Oli :)
