### ISSUE TITLE
[4.4.3] Packaged distribution has dist/js/tabulator_core.js of size 0 ?

### ISSUE THREAD

**Issue by hrstoyanov** [olifolkerd/tabulator#2408]
**Describe the bug**
The zipped distribution of 4.4.3 has this file with 0 length:  dist/js/tabulator_core.js
Is this intentional? The dist/js/tabulator_core.min.js is 24K

**Comment by olifolkerd** [comment]
That is odd. I don't build the zips, that is GitHub. Not sure what's happening there

**Comment by olifolkerd** [comment]
This will be resolved in the 4.5 release in a couple of weeks.
