### ISSUE TITLE
Ability to make moveable rows immoveable when a filter is applied on the table

### ISSUE THREAD

**Issue by McYoloSwagHam** [olifolkerd/tabulator#2410]
I have a table where I have a filter and I also have a custom function when you move a row, but I have to disable it when a filter is applied on.

so far I haven't been able to find a way to do it.

**Comment by olifolkerd** [comment]
Hey @McYoloSwagHam 

Thanks for getting in touch,

At the moment there is no way to toggle movable rows once the table has been defined.

If you want to prevent rows from being movable you would have to destroy and redefine your table with the ***movableRows*** option set to ***false***

Cheers

Oli :)

**Comment by takuy** [comment]
@olifolkerd Perhaps, as a feature, there can be a `movableValidator` option on the table that takes a function? This would get called for each row that is being moved - similar to to the column's `validator` function when something is being edited.
