### ISSUE TITLE
HTML not showing in collapsed row

### ISSUE THREAD

**Issue by mikehobson** [olifolkerd/tabulator#2411]
Hi Oli, Im tryig to do something a little clever, I have a tabulator table which is only used when my script detects a mobile device,I have set this a fixed width and to be responsivelayout="collapse". I then call a custom formatter which returns HTML, eventually this will return a stacked progress bar but at present no matter what HTML I return its not shown on the mobile device

`var table = new Tabulator("#example-table", {
           
           ajaxURL:"console.json",
           height:800,
           pagination:"local", 
           groupBy:"league",
           paginationSize:100,
           dataTree:true,
           responsiveLayout:"collapse",
           responsiveLayoutCollapseStartOpen:false,

           columns:[
                {title:"",
                columns:[
                {formatter:"responsiveCollapse", width:30, minWidth:30, align:"center", resizable:false, headerSort:false},
               {title:"league", field:"league",width:50,headerSort:false,visible:false,formatter:"html"},
               {title:"img/clock.png", field:"time", sorter:"date",width:40,titleFormatter:"image",headerSort:false,headerTooltip:"Time gone"},
               {title:"img/goal.png", field:"score", sorter:"string",width:40,formatter:"html",align:"center",headerSort:false,titleFormatter:"image",headerTooltip:"Current Score"},
               {title:"teams", field:"team",headerSort:false, formatter:"html",width:160}, 
               {title:"timep", field:"timep",visible:false},
               {title:"matchid", field:"matchid",visible:false},
               {title:"totalap1", field:"totalap1",visible:false},
               {title:"draw", field:"draw",visible:false},
               {title:"homescore", field:"homescore",visible:false},
               {title:"awayscore", field:"awayscore",visible:false},
               {title:"img/pressure2.png",field:"pi1",width:30,formatter:"html",titleFormatter:"image",headerClick:ap1sort,headerSort:false,align:"center",headerTooltip:"Attacking Pressure1",
                cellMouseEnter:function(e, cell, row){var row=cell.getRow().getData();
                var celldata=cell.getElement();if (!celldata._tippy){tippy(celldata, {  content: "Attacking Pressure"+row.matchid+"<iframe style=\"background:#FFFFFF;\" src=\"../pressure/showgraph.php?gameid="+row.matchid+"&pi=pi1&time="+row.timep+"\" width=420 height=225></iframe>",maxWidth:"450px",a11y: false,arrow:true,
                })}celldata._tippy.show();}},
                 
               {title:"img/pressure2.png",field:"pi2",width:30,formatter:"html",headerSort:false,titleFormatter:"image",headerTooltip:"Attacking Pressure2"},
               {title:"poss", field:"poss",visible:false},
               {title:"soont" , field:"shotsont", visible:false},
               {title:"sooft" , field:"shotofft", visible:false},
               {title:"dattacks" , field:"dattack", visible:false},
               {title:"attacks" , field:"attack", visible:false},
               {title:"corner" , field:"corners", visible:false},
               {title:"foul" , field:"fouls", visible:false},
               {title:"ycard" , field:"ycards", visible:false},
               {title:"rcard" , field:"rcards", visible:false},
              
               {title:"mobile",field:"mobile",formatter:progressFormatter()},
               ]},`

The last field will always be collapsed due to the fixed width applied by css

```
if (mobile)
{
  var style = document.createElement('style');
  style.innerHTML = `
  .tabulator {
  width: 480px;
  };
```

The custom formatter at the moment simply returns html
 ```
 var progressFormatter = function(cell, formatterParams){
	return '<p>This is html</p>'}
```

but all I see when I open the collapsed row is the title of the field the HTML is not displayed

![image](https://user-images.githubusercontent.com/2518239/66267703-3ceed180-e82c-11e9-8090-b359da9b4a1c.png)

I've spent ages on this and now Im starting to wonder if there is an issue thats preventing me doing this, I could pass html from the json file but I want to display 5 or 6 progress bars which will make the file huge so Id rather pass the numbers and use a custom function to change those to progress bars

**Comment by olifolkerd** [comment]
Hey @mikehobson 

Thanks for getting in touch, i do like it when people try something interesting!

Any chance you could put this in a JS Fiddle or a Code Pen, it is quite hard to work out what is going on from a few snippets of code and a screen shot. it would be much easier if there was a working example i could have a play with.

Cheers

Oli :)
