### ISSUE TITLE
rowSelectionChanged event fires during table initialization

### ISSUE THREAD

**Issue by Nyut0n** [olifolkerd/tabulator#2414]
Hi,

**Describe the bug**
The callback for rowSelectionChanged runs during table initialization.

**Tabulator Info**
- Tabulator 4.4.3
- Minimal example of table constructor:

```js
new Tabulator( '#mytable', {
  autoColumns: true,
  data: [
    {col: "123"},
    {col: "345"},
  ],
  rowSelectionChanged: function() { 
  	console.log('Whoop');
  },
} );
```

**Working Example**
https://jsfiddle.net/8qshk5zm/

**To Reproduce**
See jsfiddle, check dev console

**Expected behavior**
I'd expect the callback to run only when the row selection actually changes.

**Desktop (please complete the following information):**
 - OS: Windows 10 1903
 - Browser: Chrome
 - Version : 77

**Additional context**
It runs before the data is loaded somehow. Calling this.getData() returns an empty array, even though the table was initialized with an actual data array.

**Comment by olifolkerd** [comment]
Hey @Nyut0n 

This is because the row selection is cleared out when the initial dataset is loaded into the table. which is the case when ever data is loaded into the table.

Cheers

Oli :)
