### ISSUE TITLE
Excel export as object 

### ISSUE THREAD

**Issue by ggotsidis** [olifolkerd/tabulator#2415]
Dear Oli,

Thank you for your great effort of building tabulator! it is a remarkable module!

When exporting excel with  `table.download("xlsx", "test.xlsx", {sheetName:"testName"});`
it will be very handy if there existed something like this:
```
let myTable = new Object;
myTable.excel = table.download("xlsx", "test.xlsx", {sheetName:"testName"});
```

So we can store the generated excel file to an object for further usage: e.x. sending it to (node.js) server.

Thank you for your time!

**Comment by takuy** [comment]
See the downloadReady callback. http://tabulator.info/docs/4.4/download#advanced-intercept

**Comment by ggotsidis** [comment]
> See the downloadReady callback. http://tabulator.info/docs/4.4/download#advanced-intercept

Thank you takuy !!! didn't noticed back to documentation!

**Comment by olifolkerd** [comment]
Thanks for your kind words @ggotsidis it is always great to hear that Tabulator is appreciated :)
