### ISSUE TITLE
Row Selection inconsistencies between Shift/Ctrl clicking and Row Filtering

### ISSUE THREAD

**Issue by haferje** [olifolkerd/tabulator#2416]
**Describe the bug**
Row Selection behavior is inconsistent when using Shift+click and Ctrl+click, depending on the first row being programmatically selected or manually selected.  Other inconsistencies are present when using Row Filtering.

**Tabulator Info**
- Which version of Tabulator are you using?
v4.4.3

**Working Example**
https://jsfiddle.net/haferje/pu4xrg93/

**To Reproduce**
Steps are included in the fiddle.
There are 3 scenarios to run and compare.

**Expected behavior**
Row Selection should be consistent, no matter how the first row was selected or if filters are applied.

Should rows retain their selection state after being filtered?
Should selectableRangeMode:'click' distinguish between programmatic and manual selection?

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Version 77.0.3865.90 (Official Build) (64-bit)

**Additional Context**
I realize the steps to testing and understanding this issue might be a little complicated, so please let me know if there is anything more I can do. Also, if there is anything I am misunderstanding about these features, please let me know - we are trying to solve a customer issue but are unsure of the correct path to take.

**Comment by olifolkerd** [comment]
Hey @haferje 

Thanks for the detailed fiddle, in answer to your questions:

Test 1 - This is expected behaviour, it was specifically asked for by users that selection be persistent on filter. if you dont want this you can set the ***selectablePersistence*** option to ***false***, see the [Selection Documentation](http://tabulator.info/docs/4.4/select#setup-persistent) for full details

Test 2 & 3 - This happens because the keyboard shift click is based on user interaction with the table and discounts and programatic interaction with the table.

I hope that helps,

Cheers

Oli :)

**Comment by haferje** [comment]
I see now that there is a `selectablePersistance` option that solves one of my concerns.
However, I would like to elaborate on one of the inconsistencies that may not have come across very well in my example.

Based on your response to Test 2 & 3, you say shift click discounts any programmatic interaction.  Is this intended to be different in behavior from ctrl click?

I have set up a new [test fiddle here](https://jsfiddle.net/haferje/n3quw12a/) to show that when the first row is programmatically selected, ctrl click behaves as expected, but shift click does not.  I would expect users to believe that if a row is already selected, then both shift click and ctrl click should add to the current selection, however shift click seems to start a new collection.

I was testing a bunch of interactions in my application, so I am sorry this didn't come across very well in my initial report.

Thank you.

**Comment by olifolkerd** [comment]
Thanks for your feedback.

I understand that for your usage case you feel the behaviour is undesirable.

As I stated before the two systems behave differently with the idea being the programtic selection system does not affect the user selection system.

This is intended behaviour.

You are of course welcome to make your own modifications to the module to fit your needs.

Cheers

Oli

**Comment by haferje** [comment]
I do believe it is important to document these differences between Shift click and Ctrl click behavior.

I will look into customizing the Selectable Rows module.

Thank you for your quick response!
