### ISSUE TITLE
User Defined/Custom Field in ColumnDefinition to hold JSON object

### ISSUE THREAD

**Issue by jerrens** [olifolkerd/tabulator#2418]
I am working on a project where we dynamically add/remove columns to a Tabulator as the user selects items from a list.  Each column added/removed corresponds to a data set in a database, and is referenced by the database key (a UUID), so when the user selects an item in the list, a method is provided the UUID of the selected item, the data retrieved, then added to Tabulator.  The data from Tabulator is then used to update a chart (taking advantage of the filtering, sorting, mutators, etc in tabulator).  

We have all of this working, however, there is some information retrieved from the database record, that we would like to make available to the chart.  The short version is that the column title uses a friendly name of the dataset, but the chart needs to also know the UUID of the origin. We had hoped that we could include the information in a custom field of the ColumnDefinition Object since we're using JSON, however we found that there is a validator in place to throw an error ("Invalid column definition option...') when a key is included that is not defined in defaultOptionList. 

As a work around, we've discovered that we can add the field to the column component AFTER the column has been added to the table by getting reference to the column definition via columnManager.

Could the addColumn method add support an overload for storing a user defined field with the column component (such as 'userDefined', 'metadata', etc.) that accepts any value type?  Internally, Tabulator would not need to do anything with this field, but when current methods for retrieving a column component object are used, this user defined field would be available.

If added, this may also be an alternate search location that could be used when searching for a column (other than just the field name).  In our specific use case, the column title is made up from several fields from the database record (a friendly name), but within the code, it is easy to keep up with the UUID instead of the friendly name that was created just for the column header title.  If we could store 
    `<ColumnComponent>.metadata = { sourceUUID: '<DataUUID>' }; `
then later, do:
    table.getColumn( { sourceUUID: '<DataUUID>' }); 
    // or 
    table.getColumn( { 'metadata.sourceUUID': '<DataUUID>' });

That would be extremely helpful.  If the argument datatype in getColumn is a string, then the current method would be used.

If the search feature isn't added now, I believe adding support for the other functionality would require minimal effort and also be beneficial to other users.

Thanks for your consideration and also a huge thank you for your work on Tabulator.

**Comment by olifolkerd** [comment]
Hey @jerrens 

Thanks for getting in touch.

The warnings you are seing are only intended to help developers out if they make a typo when defining their table, they dont stop the table from functioning.

If you would like to prevent the warnings showing up in your console you can set the ***invalidOptionWarnings*** option to ***false*** in your table constructor.

```js
var table = new Tabulator("#example-table", {
    invalidOptionWarnings: false, //disable console warnings for invalid table properties
});
```

I hope that helps,

Cheers

Oli :)
