### ISSUE TITLE
React: Table not displaying properly

### ISSUE THREAD

**Issue by 8483** [olifolkerd/tabulator#2419]
**Describe the bug**
The table is not displayed properly, as seen on [this image](https://imgur.com/a/69SqRYX).

**Tabulator Info**
Version: 4.4

I am using the example provided in the documentation here: http://tabulator.info/docs/4.4/frameworks

```javascript
import React, { Component } from 'react'
import 'react-tabulator/lib/styles.css';
import { ReactTabulator } from 'react-tabulator'

export default class Deals extends Component {
    render() {
        const columns = [
            { title: "Name", field: "name", width: 150 },
            { title: "Age", field: "age", align: "left", formatter: "progress" },
            { title: "Favourite Color", field: "col" },
            { title: "Date Of Birth", field: "dob", align: "center" },
            { title: "Rating", field: "rating", align: "center", formatter: "star" },
            { title: "Passed?", field: "passed", align: "center", formatter: "tickCross" }
        ];

        var data = [
            { id: 1, name: "Oli Bobby", age: "12", col: "red", dob: "" },
            { id: 2, name: "Mary May", age: "1", col: "blue", dob: "14/05/1982" },
            { id: 3, name: "Christine Lobowski", age: "42", col: "green", dob: "22/05/1982" },
            { id: 4, name: "Brendon Philips", age: "125", col: "orange", dob: "01/08/1980" },
            { id: 5, name: "Margret Marmajuke", age: "16", col: "yellow", dob: "31/01/1999" },
        ];

        return (
            <div>
                <ReactTabulator
                    data={data}
                    columns={columns}
                    tooltips={true}
                    layout={"fitData"}
                />
            </div >
        )
    }
}
```

**Comment by 8483** [comment]
Adding the CDN CSS to index, fixed the problem.

```html
<link href="https://unpkg.com/tabulator-tables@4.4.3/dist/css/tabulator.min.css" rel="stylesheet">
```

What is the problem with the `import`?

```javascript
import 'react-tabulator/lib/styles.css';
```

**Comment by olifolkerd** [comment]
Hey @8483 

Thanks for the info there, im not sure what the issues with that are, im not a react developer myself so i only show the sample code that others produce.

I will see if i can get the demo updated.

Cheers

Oli :)

**Comment by ducwings** [comment]
@8483 both ways should work.
examples:
https://github.com/ngduc/react-tabulator
https://codesandbox.io/s/0mwpy612xw?module=/src/components/Home.js

"import" will be bundled (by webpack, if you use it) css files with your final main.css

**Comment by ngduc** [comment]
@8483 both ways should work.
examples:
https://github.com/ngduc/react-tabulator
https://codesandbox.io/s/0mwpy612xw?module=/src/components/Home.js

"import" will bundle (by webpack, if you use it) css files with your final main.css

**Comment by eagle-r** [comment]
@8483 I just encountered this issue today. I found that I had to add both CSS imports  in React (the `/lib` file and whichever theme you want from `/css`)
```
import 'react-tabulator/css/bootstrap/tabulator_bootstrap.min.css';
import 'react-tabulator/lib/styles.css';
```

**Comment by angela318** [comment]
I imported these 2 lines in my react class like the example. It works fine in local, but not in heroku deployment. 
It doesn't seems to pick up the css properly. Any help on how to set it up? 
import "react-tabulator/lib/styles.css"; // default theme
import "react-tabulator/css/bootstrap/tabulator_bootstrap.min.css"; // use Theme(s)
