### ISSUE TITLE
Moveable Columns jammed after a few moves

### ISSUE THREAD

**Issue by alainpannetier** [olifolkerd/tabulator#242]
I would like to report that I have experienced a significant number of occurrences when the columns were jammed after a few moves.
This is more likely to happen on rows with 5+ columns, but I even did it with the official doc website examples (name, age,  favourite colour).  Open this table, shrink the window a bit to bring up the h scrollbar, fetch the rightmost column and drag it a few positions to the left, don't release immediately: move back a bit on the right.  Repeat a few times if that won’t work at the first try.
Here are the most agravating factors causing this situation
-	If one enables header filtering on one or more columns (not necessary).
-	If moved columns are at the (right) end of the tabulator object and you had to scroll right to bring them into view.
-	If you move a column from the right to left (e.g. skip two or three columns on your left) and then move back a bit on the right.

**Comment by olifolkerd** [comment]
Hi Alan,

Thanks for getting in touch, are you using the latest version of tabulator from the git repo?

I have isolated where the issues are and should find time in the next couple of days to fix them.

What browser are you using?
could you post a copy of your Tabulator constructor so i can replicate the issue as closely as possible to your setup.

Cheers

Oli

**Comment by alainpannetier** [comment]
#### Zip
[sample_for_jammed_columns.zip](https://github.com/olifolkerd/tabulator/files/889829/sample_for_jammed_columns.zip)

#### Info
 - Here you go. Many thanks for your quick answer.
 - Yes I just git cloned a few days ago (28th of March).
 - I use mainly chrome 52 and FF 52.esr for devs at the moment.

#### Jammed
![screenshot from 2017-04-03 15 24 12](https://cloud.githubusercontent.com/assets/1625152/24607323/2d701344-1882-11e7-9cfc-0c60a3579d63.png)

#### Normal
![screenshot from 2017-04-03 15 21 53](https://cloud.githubusercontent.com/assets/1625152/24607137/6b960774-1881-11e7-82ce-d6851080b1b8.png)

**Comment by alainpannetier** [comment]
Just some more insights.
The pb arises when you drop the dragged column header on top of the 6px resize handle zone.

**Comment by olifolkerd** [comment]
Thanks for the info,
 i will get that fixed in this weekends release

**Comment by olifolkerd** [comment]
I put in some fixes this morning and no longer seem to be able to replicate the issue.

would you mind pulling down the latest code and let me know if you still have the issue.

Many Thanks

Oli

**Comment by alainpannetier** [comment]
Hi Oliver,

I'm afraid I still do. Here is a screenshot.
Noteworthy.
  - I have a frozen column
  - I have scrolled horizontally till the right end of the table.
  - The frozen column is still in the viewport though
  - I can drag the last column header on column borders
  - Seems to just drop the header there without snapping it to it's new slot.
I also attach a zip of the project so that you can check I have the latest, and manipulate yourself.

![screenshot from 2017-04-08 19 38 45](https://cloud.githubusercontent.com/assets/1625152/24830283/c1eaf7c2-1c93-11e7-82d9-e75ee7978575.png)
[issue_242_after_fixes.zip](https://github.com/olifolkerd/tabulator/files/907568/issue_242_after_fixes.zip)

**Comment by olifolkerd** [comment]
Looking at it the issue seems to appear when dropping the column on or immediately next to the frozen column when the table is scrolled right.

Would you agree?

Cheers

Oli

**Comment by alainpannetier** [comment]
Not necessarily close to the frozen column.
However I just noticed that the columns get sometimes jammed far from the
drop area, next to the frozen column.

- If you have a frozen column
- And the table is larger than the viewport.
- scroll right till the end
- as soon as you grab the last header and drag it - fast enough - leftward,
all colimn headers get jammed next to the frozen one

- Also another case is when the mouse x goes leftwards (still with
scrollbar full right) but y is not in the headers area (higher or lower).

**Comment by olifolkerd** [comment]
Hey,

Just a quick note to let you know that this issue will be fixed in the upcoming 3.0 release later in May!

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey,

You will be happy to hear that version 3.0 is now in beta release, and should address the issues you were having.

Head over to http://olifolkerd.github.io/tabulator/news/ to see the latest features!

Cheers

Oli
