### ISSUE TITLE
Access to HTTP Response Headers in `ajaxResponse:` callback

### ISSUE THREAD

**Issue by kdabir** [olifolkerd/tabulator#2424]
**Is your feature request related to a problem? Please describe.**
Not able to access HTTP Headers in `ajaxResponse:`. In the callback `function (url, params, response)`, response is a json body but there is no usable handle to headers.

**Describe the solution you'd like**
Either the response should be an object with `{headers, body}` but this will be backwards incompatible. In such case, we may provide additional param to the callback function
`function (url, params, response, headers)`

**Comment by olifolkerd** [comment]
What information are you looking to access in the headers? Do you have a specific usage case in mind?

It helps me to implement a better solution if I can understand a usage case as to why it is needed.

**Comment by kdabir** [comment]
I get the pagination data in `range` header (total page count etc..) and the body is directly a json array,  which i map to desired structured required for tabulator pagination to work. Here is my function:

```
  ajaxResponse: function (url, params, response) {
    return {
      last_page:  // populate this from range header,
      data: response
    }
  },
```

But since I can't access headers here, i am not able to populate `last_page`, which blows up table with `Remote Pagination Error - Server response missing 'last_page' property`

**Comment by olifolkerd** [comment]
Hey @kdabir 

Thanks for the details, that is very helpful.

I will add this to the roadmap for inclusion in a future release.

Cheers

Oli :)

**Comment by kdabir** [comment]
Thanks for adding it to roadmap @olifolkerd. Any suggested workaround in the mean time?

**Comment by olifolkerd** [comment]
Hey @kdabir 

I would suggest that you use the ***ajaxRequestFunc*** function to add your own ajax loader which will allow you to fully specify the request handling for yourself.

Have a look at the [Ajax Documentation](http://localhost:8080/docs/4.5/data#ajax-promise) for more information on how to do this.

Looking into it further im not going to look at implementing the params in the core library as it breaks the pattern for other users who want to use ***ajaxRequestFunc*** to add custom request functionality and just return the data. As this is the first time this has come up i am going to treat it as an edge case and opt for suggesting the ***ajaxRequestFunc*** for you. If more users face this issue i am happy to look into it further.

Cheers

Oli :)

**Comment by gavbaa** [comment]
I faced exactly the issue as described in this ticket (my count and pagination properties are returned as headers from my REST API), and while I will be doing the manual workaround specified, am adding a data point for headers in the response function.
