### ISSUE TITLE
Move Data between Table and inside the table

### ISSUE THREAD

**Issue by priyaec98** [olifolkerd/tabulator#2425]
I refer this example : http://tabulator.info/examples/4.3#movable-between-tables.

  Move rows between table working fine ,but move row inside the sending table not working . 
  how can i resolve this?

**Comment by olifolkerd** [comment]
If you are having issues please create a JS Fiddle of the issue and provide
step by step instructions for how to recreate it.

**Comment by priyaec98** [comment]
I attached the jsfiddle  (https://jsfiddle.net/kd374Lrs/1/)
 
Row moves between table1 to table2 is working fine.
But move row within Table1 is not working.


example :  I'm trying to move Row4 to the position of row1 ,it's not working.

**Comment by olifolkerd** [comment]
Hey @priyaec98 

Thanks for the JS Fiddle, i now understand what you are asking.

As it states in [The Documentation](http://localhost:8080/docs/4.5/move#rows-table) 

`When moving rows between tables is enabled, you will no longer be able to move rows around inside the sending table`

This is just a limitation of the table at present

Cheers

Oli :)

**Comment by tawissus** [comment]
Is the restriction still in place? 
I am currently facing the same problem.
