### ISSUE TITLE
Copy data-attributes from HTML table-element to tabulator elements

### ISSUE THREAD

**Issue by maaartinko** [olifolkerd/tabulator#2426]
**Is your feature request related to a problem? Please describe.**
Currently there's no option to load values into the data-attributes of a table and then use them after generating the tabulator.

**Describe the solution you'd like**
The data-attributes could be copied to the tabulator elements the same way as the tabulator-attributes are.

**Comment by olifolkerd** [comment]
Please explain a need for this that couldn't be handled using JavaScript
variables?

**Comment by maaartinko** [comment]
As of today `tabulator` seems to be really advanced if you initiate and load everything on the client side. (Be it with a `JS` Framework like `React` or otherwise)
But if you need to load data on the server side and only use `JS` to initiate the `tabulator` and do simple stuff like `EventListeners`, dynamic redirects (depending on a clicked or selected row) or similiar stuff, it's not that practical.
Using those `data-attributes` could fill the gap.

**Example:**
If you only initiate the `tabulator` on the client side you could add an attribute `data-anchor="someURI"` and then use a `rowClick` callback which dynamically defines a redirect to the `data-anchor` for every row.

**Comment by maaartinko** [comment]
I haven't heard anything about this issue anymore.
Would you consider adding it, if I would create a Pull Request?

**Comment by olifolkerd** [comment]
Hey @maaartinko 

My concern is that this method for transferring data to the client side is unconventional

Generally speaking you wouldnt be trying to transfer data in this way. you would either be making a separate ajax request for it to improve page loading speed or you would be embedding it as a json object in your page so it is programatically.

Tabulator never access data in the way from the DOM as it goes against the ethos of the library so i am reluctant to include this as a feature of the library.

Cheers

Oli :)
