### ISSUE TITLE
Allow choice of selection from all active rows, all visible rows or all rows

### ISSUE THREAD

**Issue by jwalker5006** [olifolkerd/tabulator#2428]
**Is your feature request related to a problem? Please describe.**
SETUP: Version 4.4.1 - Grid with header filters, no height specified in table, not using ajax filtering. 

Its quite possible that what I am wishing for already exists and I may be using the getSelectedData() wrong.

Maybe there is a getSelectedData(true); or something like that. where true says use header filters.

# Demo of Issue
The solution is below
![2019-10-14_15-36-13](https://user-images.githubusercontent.com/6217843/66781799-d7d55480-ee99-11e9-82db-b53c997e527c.gif)

### Hopeful Solutions
**reproduce Need:**
1. Load data into Tabulator grid
1. Using header filter, go ahead and filter  using client side header filters reducing rows visible
1. Click the "Select all" header checkbox 
1. Click tabulator print. notice only the visible selected rows will print
1. use the "let selectedRows = table.getSelectedData();" notice rows both filtered and unfiltered are selected into array
1. The wish is that getSelectedData would work the same as print, export to excel, csv and all the others.  Selecting all client side rows which are not excluded from client side header filters.

**Describe alternatives you've considered**
1. I thought of using service side ajax filtering, but we were really trying to keep things fast on client side
1. Tried reverse engineering how download and print works with selecting data and maybe hijacking the existing getSelecteddata. I felt like the riddler after being frozen on ice and then un-thawed.

**Additional context**
![image](https://user-images.githubusercontent.com/6217843/66781286-824c7800-ee98-11e9-8ee3-1d8b82b18c18.png)

![image](https://user-images.githubusercontent.com/6217843/66781327-94c6b180-ee98-11e9-853d-6920d77cbb59.png)

Print will select only non header filtered data - This is great
![image](https://user-images.githubusercontent.com/6217843/66781343-a0b27380-ee98-11e9-8371-2f82d2279b63.png)

![image](https://user-images.githubusercontent.com/6217843/66781398-c8094080-ee98-11e9-9c47-e84d0fe7477f.png)

![image](https://user-images.githubusercontent.com/6217843/66781461-f555ee80-ee98-11e9-9f5b-590a137d9499.png)

What we wired to the getSelected Create Batch button
```
        $("#createBatchBtn").click(function () {
            var woids = []; var Woid; var total = 0;
            var selectedRows = tableWOList.getSelectedData();

            selectedRows.forEach(function (item, index) {
                //showInfoAlert('getting woid' + $(this).data('woid'));
                Woid = item.woid;
                woids.push(Woid);
                total += item.taxableAmt;
            });

### Short on Wish Item as an issue
![2019-10-14_15-36-13](https://user-images.githubusercontent.com/6217843/66781566-3bab4d80-ee99-11e9-90c3-8e7e78575a23.gif)

```

### Load main Grid function
```
function LoadMainGrid(data) {
            tableWOList = new Tabulator("#batchBuilder-table", {
                //height: "calc(100vh-500px)", // set height of table (in CSS or here), this enables the Virtual DOM and improves render speed dramatically (can be any valid css height value)
                //ajaxFiltering: true,
                data: data, //assign data to table
                layout: "fitColumns", //fit columns to width of table (optional)
                groupBy: "projectManager", groupStartOpen:[false],
                groupClosedShowCalcs: true,
                groupHeader: [
                    function (value, count, data) { //generate header contents for gender groups
                        return value + "<span style='color:#d00; margin-left:10px;'>(" + count + " item)</span>";
                    },
                    function (value, count, data) { //generate header contents for color groups
                        return value + "<span style='color:#0dd; margin-left:10px;'>(" + count + " item)</span>";
                    },
                ],
                cellDblClick: function (e, cell) { cellWasClicked(e, cell); },
                columns: [ //Define Table Columns
                    {formatter: "rowSelection", titleFormatter: "rowSelection",width:"40", align: "center", headerSort: false, cellClick: function (e, cell) {
                            cell.getRow().toggleSelect();}
                    },
                    { title: "WOID", field: "woid", sorter: "woid", headerFilter: true, width: 75 },
                    { title: "Status", field: "woStatus",width:79, sorter: "woStatus", headerFilter: true, align: "left" },
                    { title: "CustomerID", field:"customerID", visible:false},
                    { title: "Customer", field: "customerName",width:105, tooltip: "Double Click Customer Details", sorter: "customerName", headerFilter: true },
                    { title: "SiteID", field: "siteID", visible: false },
                    { title: "Site", field: "siteNumber", minWidth: 100,tooltip:"Double Click Site Details", headerFilter: true, sorter: "siteNumber", align: "left" },
                    { title: "Job PO", field: "customerPO", headerFilter: true, minWidth: 100, sorter: "customerPO", align: "left" },
                    {
                        title: "Total", field: "taxableAmt", width:110, tooltip: "Double Click Financials on Taxable Amount", align: "right", formatter: "money", formatterParams: {decimal:".",thousand:",",symbol:"$",symbolAfter:false,precision:2,}, topCalc: "sum", topCalcFormatter: "money", topCalcFormatterParams: {
                            decimal: ",",
                            thousand: ".",
                            symbol: "$",
                            symbolAfter: false,
                            precision: 2,
                        }, headerFilter: true, width: 100, sorter: "taxableAmt", align: "left" },
                    { title: "Dept", field: "dept",minWidth:75, headerFilter: true, sorter: "dept", align: "center" },
                    { title: "Project ID", field: "ncsProject",minWidth:105, headerFilter: true, sorter: "ncsProject", align: "left" },
                    { title: "JobID", field: "ncsJobID", headerFilter: true, width: 75, sorter: "ncsJobID", align: "left" },
                    { title: "Status", field: "jobStatus", headerFilter: true, width: 87, sorter: "jobStatus", align: "left" },
                    { title: "Project Presentation", field: "presentationName", minWidth: 150, headerFilter: true, sorter: "presentationName", align: "left" },
                    { title: "Bill To", field: "billTo", headerFilter: true, minWidth: 90, sorter: "billTo", align: "left" },
                    { title: "Project Manager", field: "projectManager",minWidth:100, headerFilter: true, sorter: "projectManager", align: "left" },
                    { title: "Inv", field: "woInvoiceNow",width:70, sorter: "woInvoiceNow", formatter: "tickCross", headerFilter: "tickCross", headerFilterParams: { "tristate": true }, headerFilterEmptyCheck: function (value) { return value === null } },
                ],
            });
        }
```

**Comment by jwalker5006** [comment]
![2019-10-14_15-36-13](https://user-images.githubusercontent.com/6217843/66781799-d7d55480-ee99-11e9-82db-b53c997e527c.gif)

**Comment by jwalker5006** [comment]
I was thinking that maybe here if true is passed we could somehow verify the filter has not hidden the row? And only push visible rows. I know this would not work with a virtual DOM. But possible could if no virtual DOM used? Not sure what else to do.
![image](https://user-images.githubusercontent.com/6217843/66834912-2cbdad00-ef24-11e9-8f84-5afc964d1833.png)

**Comment by jwalker5006** [comment]
Getting closer to tracking the issue down. During this function, e.table.rowManager.rows.forEach needs to make sure the row it wants to add to the selected rows is VISIBLE (may not work when Virtual DOM) or another option, make sure the header filters would not exclude the data.


```
V.prototype.selectRows = function (t) {
        var e = this;
        switch (void 0 === t ? "undefined" : _typeof(t)) {
            case "undefined":
                e.table.rowManager.rows.forEach(function (t) {
                    e._selectRow(t, !0, !0)
                }), e._rowSelectionChanged();
                break;
            case "boolean":
                !0 === t && (e.table.rowManager.activeRows.forEach(function (t) {
                    e._selectRow(t, !0, !0)
                }), e._rowSelectionChanged());
                break;
            default:
                Array.isArray(t) ? (t.forEach(function (t) {
                    e._selectRow(t, !0, !0)
                }), e._rowSelectionChanged()) : e._selectRow(t, !1, !0)
        }
    }
```

**Comment by jwalker5006** [comment]
I figured out how to get the select all to only select the filtered data. I know this may not be the best option, but it works perfectly.  Hoping this can be an add to the build.

Otherwise each release I will download locally and update the code each time.

```
V.prototype.selectRows = function (t) {
        var e = this;
        var activeRowsused = e.table.rowManager.activeRows!=null ? true : false;
        switch (void 0 === t ? "undefined" : _typeof(t)) {
            case "undefined":
                if (activeRowsused) {
                    e.table.rowManager.activeRows.forEach(function (t) {
                        e._selectRow(t, !0, !0)
                    }), e._rowSelectionChanged();
                }
                else {
                    e.table.rowManager.rows.forEach(function (t) {
                        e._selectRow(t, !0, !0)
                    }), e._rowSelectionChanged();
                }
                break;
            case "boolean":
                !0 === t && (e.table.rowManager.activeRows.forEach(function (t) {
                    e._selectRow(t, !0, !0)
                }), e._rowSelectionChanged());
                break;
            default:
                Array.isArray(t) ? (t.forEach(function (t) {
                    e._selectRow(t, !0, !0)
                }), e._rowSelectionChanged()) : e._selectRow(t, !1, !0)
        }
    }
```

**Comment by olifolkerd** [comment]
Hey @jwalker5006 

I have renamed the issue as it isnt fixing an issue, you are requesting that the ***selectRows*** function behaves differently, its current mode of selecting active rows is correct and documented,

I am happy to look into this for the 4.5 release next month

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Infact it was a quick and easy one to do so i have just pushed an update for it to the 4.5 branch that allows selection of "all", "active", and "visible" data.

as for getting just a subset of the selected rows, this is not something i would be looking to add to tabulator, it would be easy enough for you to work this out by comparing the selected rows against the active rows.

Cheers

Oli :)
