### ISSUE TITLE
RowSelection - set row isSelected via ajax data

### ISSUE THREAD

**Issue by byoernn** [olifolkerd/tabulator#2429]
**Is your feature request related to a problem? Please describe.**
I am actually trying to send ajax data of users where some are already selected.

**Describe the solution you'd like**
The isSelected property should be set by the data of the table, "true" or "false".
For "rowSelection" column, it could accept "true" or "false" easy via an field, e.g. "IsSelected",

**Describe alternatives you've considered**
custom column with checkbox and own row selection javascript.

**Additional context**

**Comment by olifolkerd** [comment]
Thanks for getting in touch.

This would be inconsistent with the way this part of the system works. It is only setup to handle data and I would not want to start exposing random functionality to Ajax control.

That being said it would be easy enough for you to do this yourself. You could set a property in your data to determine if it is selected. When the dataLoaded callback is triggered after data is loaded. You could then use the getRows function on the table to get an array of all the rows, itterate over them, check if they should be selected then call the select function on the row component.

Cheers

Oli

**Comment by omfgicbf** [comment]
> Thanks for getting in touch.
> 
> This would be inconsistent with the way this part of the system works. It is only setup to handle data and I would not want to start exposing random functionality to Ajax control.
> 
> That being said it would be easy enough for you to do this yourself. You could set a property in your data to determine if it is selected. When the dataLoaded callback is triggered after data is loaded. You could then use the getRows function on the table to get an array of all the rows, itterate over them, check if they should be selected then call the select function on the row component.
> 
> Cheers
> 
> Oli

Just a brief note in case anyone else comes across this, the `dataLoaded` event cannot be used in this way as the rows are not populated at this point and `getRows()` will not return what you expect.

You instead need to use the `dataProcessed` event.

**Comment by olifolkerd** [comment]
@omfgicbf this article was correct at the time of writing, many years ago, this is only no longer accurate as of version 5.x because the new data processing events were added in that release
