### ISSUE TITLE
Customer filter parameter - custom options hook.

### ISSUE THREAD

**Issue by alainpannetier** [olifolkerd/tabulator#243]
I'm new to tabulator so I might not do the things the right way. However, I could not find a clean way to do this.

When you create a custom filter, you will declare your own filter call back.
What's missing though is the way to pass a parameter to this callback filter.

I could think of ecapsulating the tabiulator object in its own class and using a class member as the parameter.

Except that when the callback is invoked, it is invoked as a member if the tabulator widget. Which means that his 'this' is not my instance but the tabulator instance.  See line 1742 of tabulator.js

```
      if(typeof(self.filterField) == "function"){
        return self.filterField(row);
      }
```

So what I did was to inject a member in the tabulator instance _options_ and stick my stuff there - name collision being pretty unlikely.  Yet it would be nice to have an official options member for this: **options.custom** where fiddler like myself would have all latitude to hide their private stuff. 
Or maybe there is one already. But could not find any.

I'm attaching a real life sample.  Line 219 is where the sin is commited and 232 is where I benefit from it.

[posf.ecm.table.2.js.zip](https://github.com/olifolkerd/tabulator/files/888224/posf.ecm.table.2.js.zip)

**Comment by olifolkerd** [comment]
Hi,

Thanks for getting in touch.

If you alter you the way you have bound the _consumerFilter the you can pass a different scope to it:

```js
var self = this;
$(this.table).tabulator("setFilter", function(data){
    self._consumerFilter(data);
});
```

This should call your filter function but with the correct scope.

Cheers Oli :)

**Comment by alainpannetier** [comment]
Yes that's much cleaner. Thanks Oliver.
Just a nitpick for the next readers don't forget the 'return' otherwise the chain is broken.

```javascript
var self = this;
$(this.table).tabulator("setFilter", function(data){
    return self._consumerFilter(data);
});
```
We can close that one already!
