### ISSUE TITLE
RowSelection - option to disable/enable RowClick selection 

### ISSUE THREAD

**Issue by byoernn** [olifolkerd/tabulator#2430]
**Is your feature request related to a problem? Please describe.**
Customer will select a column, but not when clicking on some columns, cause copying information to clipboard is not handsome when row get selected immediately after the click.

**Describe the solution you'd like**
Option to "enable"/"disable" selection on rowClick when "rowSelection" formatter is available.
Maybe via formatterParameters.

**Describe alternatives you've considered**
Option do enable/disable selection specific for a column.
So when clicking on this column with selection:false is set, the row does not get selected.

If you have a better Idea to handle this, please provide.
Thank you for you creat work on this!

**Comment by olifolkerd** [comment]
You can already handle this yourself.

If you don't enable row selection on the table. then use the rowClick callback to run your logic on when to select the row. You can then call the select function on the row component to force selection even if it is disabled on the table as a whole.

Cheers

Oli
