### ISSUE TITLE
How to persist leading zeroes to a field when downloading csv

### ISSUE THREAD

**Issue by pratishthap** [olifolkerd/tabulator#2433]
I need a way to preseve leading zeroes to a field/column when using tabulator download to csv

**Comment by olifolkerd** [comment]
Hey @pratishthap 

You would need to extend the download module with a [Custom Downloader](http://tabulator.info/docs/4.4/modules#module-download) to achieve this. You could model it on  the existing CSV downloader

Cheers

Oli :)
