### ISSUE TITLE
table.getData() "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by rigogsilva** [olifolkerd/tabulator#2434]
**Description**
I am trying to get the data from the tabular table after it is all rendered. But using the following code: 

```javascript
function getData() {
  const table = this.$refs.tabulator.getInstance();
  console.log('get data');
  const data = table.getData();
  console.log(data);
}
```

The function `table.getData();` fails with the following error:
```console
[Vue warn]: Error in mounted hook: "RangeError: Maximum call stack size exceeded"

found in

---> <FinancePanel>
       <AccountView> at src/views/AccountView/AccountView.vue
         <App> at src/App.vue
           <Root>
RangeError: Maximum call stack size exceeded
    at Object.deepClone (tabulator.js?39ab:9480)
    at Object.deepClone (tabulator.js?39ab:9493)
    at Object.deepClone (tabulator.js?39ab:9493)
    at Object.deepClone (tabulator.js?39ab:9493)
    at Object.deepClone (tabulator.js?39ab:9493)
    at Object.deepClone (tabulator.js?39ab:9493)
    at Object.deepClone (tabulator.js?39ab:9493)
    at Object.deepClone (tabulator.js?39ab:9493)
    at Object.deepClone (tabulator.js?39ab:9493)
    at Object.deepClone (tabulator.js?39ab:9493)
```

**Tabulator Info**
- tabulator-table: 4.4.3
- Also using vue-tabulator: 1.2.2
```pug
      TabulatorComponent.table-sm.table-striped(
        v-model="tableSettings.data" :options="tableSettings.options" ref="tabulator"
      )
```

**Screenshots**
![image](https://user-images.githubusercontent.com/31558765/66859896-c059a280-ef51-11e9-8e32-9a51a0619602.png)

**Desktop (please complete the following information):**
 - Google Chrome: Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by olifolkerd** [comment]
Please use the issue template when creating an issue. It is very hard to offer you the correct advice without the information it prompts you to provide.

Could you creat a js fiddle that demonstrates the issue. It is hard to tell what is going on from a few lines of code. We need to be able to see how your table is configured and a sample of the data you are using.

Cheers

Oli

**Comment by xeroxstar** [comment]
> Please use the issue template when creating an issue. It is very hard to offer you the correct advice without the information it prompts you to provide.
> 
> Could you creat a js fiddle that demonstrates the issue. It is hard to tell what is going on from a few lines of code. We need to be able to see how your table is configured and a sample of the data you are using.
> 
> Cheers
> 
> Oli

it's quite old question but I had same problem today, I think the reason for the error is that I have created an `HTMLElement` in data array:
```
{
       columns            :  [{
           titile : 'column' , field : 'column'
       }],
       data     : [{
            column  : 'element',
            element : document.getElementById('anyelementID') //<--- once I removed it, the error is gone
      }]
}
```

I had to `stringify `the argument object in `deepClone ` method to make it work:
```
deepClone: function deepClone(obj) {
	obj = JSON.parse(JSON.stringify(obj)); // <---- stringify  here
	var clone = Object.assign(Array.isArray(obj) ? {} : {}, obj);

	for (var i in obj) {
			if (obj[i] != null && _typeof(obj[i]) === "object") {
				if (obj[i] instanceof Date) {
					clone[i] = new Date(obj[i]);
				} else {
					clone[i] = this.deepClone(obj[i]);
				}
			}
	}
	return clone;
}
```
Hope it helps 👍
