### ISSUE TITLE
Want to be able to css format the cells in a column, but NOT the header

### ISSUE THREAD

**Issue by ldonald067** [olifolkerd/tabulator#244]
Cannot find CSS way to select only the cell content. The header is always impacted too.

See in the image the break in the background color because of a margin-left value that I want ONLY to apply to the row cells, without the header.
![image](https://cloud.githubusercontent.com/assets/26388455/24590652/f775d3d2-17a5-11e7-96d3-dffc109fc0f8.png)

**Comment by bobabarbanel** [comment]
This was really an issue for me (bob.abarbanel@gmail.com). I was mistakenly logged in as one of my students (lmcdoanld).

**Comment by ldonald067** [comment]
how did this happen? I have no idea who you are
