### ISSUE TITLE
Editor for input type field closes immediately on mobile device. Cannot enter data.

### ISSUE THREAD

**Issue by JDGHHou** [olifolkerd/tabulator#2446]
Any time I click on a Tabulator cell on my tablet, the keyboard pops up momentarily then disappears. I attached a cellEditing event and a cell EditCancel event to see what was happening and it immediately fires EditCancel when I start editing. I am using version 4.4 in a Chrome browser.

Anyone know how to fix this?

**Comment by olifolkerd** [comment]
Hey @JDGHHou 

That is because you table height is changing when the keyboard appears which is redrawing the table, fix the height of the table and this should resolve it.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @JDGHHou

I have pushed an update to the 4.6 branch that will detect if the table is being run on a mobile and block table redraw events if the editor is open.

This should be released in a few weeks.

Cheers

Oli :)
