### ISSUE TITLE
'Number' editor doesn't allow editing with the keyboard up/down arrows  

### ISSUE THREAD

**Issue by millerox** [olifolkerd/tabulator#2447]
Hello,
First,  thanks for the library !

**The issue:**

Cell-editor 'number' doesn't allow increasing/decreasing number by the keyboard up/down arrows. Is there a plan to add this feature to the 'number' editor ?

**Tabulator Info**
Versions : 
"react-tabulator": "^0.9.1"
"tabulator-tables": "^4.2.7"

**Example**
<div id="example-table"></div>

var tabledata = [
 	{name:"Oli Bob", age:"12"},
 	{name:"Mary May", age:"1"},
 ];

var table = new Tabulator("#example-table", {
 	height: 205,
 	data: tabledata,
 	columns:[ //Define Table Columns
	 	{title:"Name", field:"name"},
	 	{title:"Age", field:"age", editor: "number", editorParams: { min: 0 } },
});

**To Reproduce**
1. Click on a cell in the 'Age' column -> input up/down arrows exist, but they are not editable by the keyboard

**Expected behavior**
'Number' editor works as an input of 'number' type

**Comment by olifolkerd** [comment]
Hey @millerox 

that is because the up and down arrow keys are used to navigate round the table.

I will consider adding an option to override this behaviour in a future release.

Cheers

Oli ;)

**Comment by olifolkerd** [comment]
Hey @millerox 

I have just pushed an update to the 4.5 branch that adds a new ***verticalNavigation*** editorParam to a lot of editors to make it easier to customise the navigation experience.

This should be released in the next few weeks.

Cheers

Oli :)

**Comment by millerox** [comment]
Thank you ! looking forward to try it out :)
