### ISSUE TITLE
Numeric download in XLSX

### ISSUE THREAD

**Issue by dogo3** [olifolkerd/tabulator#2449]
**Is your feature request related to a problem? Please describe.**
When you have a table with numeric values and download it in XLSX format, theese values are downloaded as strings, so you cannot perform numeric operations on them with MS Excel.

**Describe the solution you'd like**
It would be nice having an option on chosing the type you want for download, for example as an argument in download function.

**Describe alternatives you've considered**
No alternatives found, this is why I put this issue.

**Additional context**

**Comment by olifolkerd** [comment]
That depends on how you are storing your data in the first place, if you are handling your numbers as strings they will be treated as such in the output.
