### ISSUE TITLE
Issue with undo() when moving rows from second row to first

### ISSUE THREAD

**Issue by rhagstrand** [olifolkerd/tabulator#2450]
Tabulator Version: 4.4.1

What Im trying to achive: Lock row 1 in place in table, which means if user tries to move a row above row 1 it should be undone. In my case Im using table.undo().

Steps to recreate: 
Create a table with some datarows. 
Set history = true, and movablerows = true. 

Attach callback rowMoved looking something like this:

rowMoved: function (row) {
    //If new position is at the top, undo the rowmoved.
    if (row.getPosition() == 0) {
             this.undo();
    }
}

Behaviour: This works flawlessly for every single case, EXCEPT when I try to move the second row and make it the first row. Then its not undone().

I noticed when debugging into tabulator.js, it seemed like it was 2 "history events" whenever I tried to move any row except the second, above the first. But when trying to move the second row above the first, there was only one event in "history".

Expected behaviour: When trying to move a row so it takes the first rows place it should ALWAYS be undone().

**Comment by olifolkerd** [comment]
Try upgrading to the latest version of Tabulator. There were tweaks made to
the history system in one of the latter patch releases

**Comment by AnimusImmodicus** [comment]
I am also experiencing the same issue on version 4.4.3.

Best I can tell, the feature works correctly when dragging a row down. However, when a row is dragged up... the undo action will always misplace the row by 1.

Here is an example.

**Starting Position:**
![start](https://user-images.githubusercontent.com/2042116/67890911-f5f0b500-fb27-11e9-98ee-31bad563b4f1.JPG)

**After Drag:**
![after_drag](https://user-images.githubusercontent.com/2042116/67890919-fe48f000-fb27-11e9-9814-b36c212fd741.JPG)

**After Undo:**
![after_undo](https://user-images.githubusercontent.com/2042116/67891027-2df7f800-fb28-11e9-92cd-b58fc21396d4.JPG)

**Comment by olifolkerd** [comment]
Could you create a JS Fiddle that demonstrates the issue so i have an example to work from.

Cheers

Oli :)

**Comment by rhagstrand** [comment]
Try this https://jsfiddle.net/rhagstrand/7nf6exdb/ (I hope you can access it)

Move row "E" to for example top position. Undo is triggered, but row ends up second to last, not last position as expected.

**Comment by olifolkerd** [comment]
Hey @rhagstrand 

I have pushed a fix for this to the 4.6 branch, which will be released later this weekend.

Cheers

Oli :)
