### ISSUE TITLE
[pseudo-bug] Missing the standard "data-" prefix

### ISSUE THREAD

**Issue by ShinobiWPS** [olifolkerd/tabulator#2451]
**Is your feature request related to a problem? Please describe.**
I've noticed in the DOM that each cell has a "data"-like attribute but without the "data-" prefixes,which is a shame, because:
-  first of all, is not standard
- it removes an expected feature from JS in the browser.
using the standard prefix will fill the [**dataset**](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*) key of the DOM element object which now is empty.

**Describe the solution you'd like**
Add "data-" prefix to any tabulator attribute on dom elements:
from
`tabulator-field`
to
`data-tabulator-field`

That allows developers access the `element.dataset` key to retrieve stuff like "tabulator-field" field value.

**Describe alternatives you've considered**
*no alternatives*

**Additional context**

**Comment by olifolkerd** [comment]
Hey @ShinobiWPS 

While i take your point on board that it would currently be proper, the use of custom hyphenated attributes is currently under discussion for inclusion in a later version of the HTML specification to bring it into line with the current allowance of custom tags as long as they are hyphenated. At the moment it will have no impact on correct functioning in any browser which tolerate custom tags without issue. you only have to look at frameworks like Vue and Angular to see their extensive use of custom tags even if they do remove them as part on the initialisation process.

Also the attributes are only included to aid with CSS styling, for which attribute selection allows any attribute.

There should be no circumstance in which you need to programatically access the attributes themselves. It is bad practice to try and manipulate any element in a virtual DOM from outside the table, therefor the only usage case for trying to manipulate the cell elements would be in the formatter for that cell, in which case you should be using the cell component passed into the formatter callback.

If you feel there is a usage case i have missed i would be happy to point you in the correct direction to avoid trying to manipulate the attributes yourself.

Cheers

Oli :)

**Comment by ShinobiWPS** [comment]
got your point and didn't know about the the new RC.
At the moment I'm trying to make "Cell selection" related to his column and to know that i needed (ideally) the "dataset" key.
I've ended up using the discouraged `getAttribute()` method to get the `tabulator-field` attribute. i don't see another way to do it.

**Comment by ShinobiWPS** [comment]
I've just realised the existence of `cellClick` which gives everything i need..
Given the RC you mentioned ,i think we can close this issue
