### ISSUE TITLE
Odd Behavior when Group By Column is ommited with totals

### ISSUE THREAD

**Issue by YendorMc** [olifolkerd/tabulator#2453]
**Describe the bug**
totals are skewed to the right by one row, phantom column shows up at right when collapse is clicked.
totals align themselves if make first column wider.
May be issue with frozen column.

**Tabulator Info**
-Version: 4.4  (CDN)

- Post a copy of your construct object if possible so we can see how your table is setup
		`var table = new Tabulator("#classifysum", {
					data:data,           //load row data from array
					layout: "fitData",  //fitColumns,
					clipboard:true,			  //enable clipboard functionality
					tooltips:true,            //show tool tips on cells
					resizableRows:true,       //allow row order to be changed
					placeholder:"Loading...", //display message to user on empty table
					groupBy: "DIVISION",
					columnCalcs:"both",
					groupClosedShowCalcs:true,
					groupToggleElement:"header",
					clipboardCopyConfig:{columnCalcs:true},
					groupHeader:function(value, count, data, group){
						//value - the value all members of this group share
						//count - the number of rows in this group
						//data - an array of all the row data objects in this group
						//group - the group component for the group
						if (count == 1){
							return value + "<span style='color: gray; margin-left:10px;'>(" + count + ")</span>";
						}
						else {
							return value + "<span style='color: gray; margin-left:10px;'>(" + count + ")</span>";
						}
					},
					columns: cols
					});`
**Working Example**
https://jsfiddle.net/YendorMc/t02wvcy4/7/

**To Reproduce**
1. Go to 'jsfiddle.'
2. Click on collapse
3. Observe behavior: column is shifted over
4. See error column at right.

**Expected behavior**
Expect total columns to align without the extra row at right.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by olifolkerd** [comment]
Hey @YendorMc 

Thanks for the info

I will look into fixing that for the next release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @YendorMc 

The calculations are in the right place when i view your JS fiddle.

I agree that it looks a bit strange but that is more down to going for a right aligned frozen column with grouping enabled. which is a bit of an odd and inconsistent layout choice anyway.

Cheers

Oli :)
