### ISSUE TITLE
variable.scss file is actually a sass file

### ISSUE THREAD

**Issue by pauldjgh** [olifolkerd/tabulator#2454]
src/scss/bulma/variable.scss is actually a sass file which can (and did in my case) result in compilation error when running an scss to css compiler. 
Either convert the file to scss (by adding a ; to each line) 
or rename it to variable.sass and change the import in tabulator_bulma.scss to the new name

**Comment by olifolkerd** [comment]
Hey @pauldjgh 

Thanks for pointing out the missing semi colons, i would be happy to accept a PR with the required changes.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @pauldjgh 

I have pushed a fix for this to the master branch and will include it in the 4.5 release in a few weeks.

Cheers

Oli :)
