### ISSUE TITLE
Option to disable column definition check.

### ISSUE THREAD

**Issue by cityremade** [olifolkerd/tabulator#2455]
Hi I am using tabulator in my project where I define custom parameters on column entries. At the moment I get warnings from `Column.prototype.checkDefinition` function - would it be possible to add option to ignore/disable this check?

**Comment by olifolkerd** [comment]
Hey @cityremade 

There is already an option for this, ***invalidOptionWarnings***@

```js
var table = new Tabulator("#example-table", {
    invalidOptionWarnings:false
});
```

I hope that helps,

Cheers

Oli :)

**Comment by AlexRMU** [comment]
For some reason, this option is not available now
