### ISSUE TITLE
persistentFilter not check for headerFilterEmptyCheck

### ISSUE THREAD

**Issue by ybitso** [olifolkerd/tabulator#2457]
**Describe the bug**
My Column Definition

 ```
{
      title: "do it?",
      field: "hasToDoIt",
      responsive: 0,
      formatter: "tickCross",
      formatterParams: {
        allowEmpty: true,
        allowTruthy: false,
        tickElement: "<i class='fa fa-check'></i>",
        crossElement: ""
      },
      headerFilter: "tickCross",
      headerFilterEmptyCheck: function (value) {
        return !value; //only filter when the value is true
      },
      sorter: "string",
      headerSortTristate: true,
      width: 80,
      align: 'center'
    },

```
When filtering the checkbox normally, everything works
However, with persistentFilter: true ... when i reload the page, it only will display true=true (not false or null when unchecked)

**Tabulator Info**
- Which version of Tabulator are you using? 4.4.3
- Post a copy of your construct object if possible so we can see how your table is setup
```

new Tabulator("#" + config.Key, {
      index: "_id",
      reactiveData: true,
      persistenceMode: true,
      persistenceID: "accountsummary",
      persistentSort: true,
      persistentFilter: true,
      autoResize: true,
      layout: "fitColumns",
      responsiveLayout: true,
      virtualDomBuffer: 100,
      headerSortTristate: true, //enable tristate header sort for all columns
      data: this.state.Data,
      columns: this.state.Columns,
      groupBy: "Geo",
      groupToggleElement: "header",
      groupStartOpen: true,
      sortOrderReverse: true,
      initialSort: [{ column: "Geo", dir: "asc" }, { column: "Account", dir: "asc" }],
      rowClick: (e, row) => {
        
        });
      }
```

**Expected behavior**
when reloading the page, the tristate checkbox should apply with the persistentFilter and show all rows when unchecked

**Comment by ybitso** [comment]
ideas??

**Comment by olifolkerd** [comment]
Hey @ybitso 

Please create a JS fiddle that demonstrates your issue.

Cheers

Oli :)

**Comment by ybitso** [comment]
@olifolkerd 
I created the fiddle, but when looking at the local storage data, the persistent data values is not being stored ion the fiddle, but running it on my server it is being stored correctly
https://jsfiddle.net/ybitso/34sp8u2z/8/

**Comment by ybitso** [comment]
@olifolkerd  was that fiddle enough ?

**Comment by ybitso** [comment]
@olifolkerd
Get a chance to look into this?

**Comment by takuy** [comment]
@ybitso I believe the persistence module was re-written entirely in Tabulator 4.5 (or at least had a major overhaul) per http://tabulator.info/docs/4.5/release#persistence. 

If you update the library, do you still have the same issue?

**Comment by ybitso** [comment]
I upgraded to 4.5.1, but still same case, but looking at the note I saw:
Note: Header filters are not currently stored persistently, this feature will be coming in a future release.

That is what I need to solve my issue (header filter)

**Comment by olifolkerd** [comment]
Hey @ybitso 

You could easily add this functionality in yourself by using the ***dataFiltered*** callback to store the header filter values in localStorage and then on page load use the ***setHeaderFilterValue*** function to restore the header filter value.

I hope that helps

Cheers

Oli :)
