### ISSUE TITLE
React JS Checkbox and checkbox on header

### ISSUE THREAD

**Issue by johnsimba** [olifolkerd/tabulator#2459]
**Is your feature request related to a problem? Please describe.**
From this issue. (https://github.com/olifolkerd/tabulator/issues/159)
I would like to create that feature or function using React Js but I can't do it since I have a lack of experience.

**Describe the solution you'd like**
I would like to create a checkbox on the header to select all rows and create a checkbox on the first row that if I uncheck it, the checkbox on the header will be unchecked.

![select](https://user-images.githubusercontent.com/55875945/67563260-e7368680-f752-11e9-8638-2614934093ae.PNG)

**Comment by olifolkerd** [comment]
Hey @johnsimba 

This is already a feature, have a look at the [Select Rows With Tickbox Example](http://tabulator.info/examples/4.4#selectable-tick)

Cheers

Oli :)
