### ISSUE TITLE
Adjust font-size according to device

### ISSUE THREAD

**Issue by pifealmeida** [olifolkerd/tabulator#246]
Hello
I'm using Tabulator on this page, but I noticed that although table container adjusts to the screen size, the font-size doesn't. This ends up on plotting lots of small texts on the screen, and very long columns with tons of empty space.

How can I change the Tabulator.css to adjust font-size according to the device size (here I mean show larger texts on mobile phones, for example, than when showing the table on a desktop).

Thank you!

**Comment by olifolkerd** [comment]
Hi pifealmeida,

Thanks for getting in touch.

I would suggest using media queries in your CSS to change the text size depending on the screen size of the device.

A list of media queries for popular devices can be found here:
[https://css-tricks.com/snippets/css/media-queries-for-standard-devices/](https://css-tricks.com/snippets/css/media-queries-for-standard-devices/)

As an example here is a media query to increase the font size on an iPhone 6:
```js
@media only screen 
  and (min-device-width: 375px) 
  and (max-device-width: 667px) 
  and (-webkit-min-device-pixel-ratio: 2) { 
   .tabulator{ 
     font-size:18px;
   }
}
```
Let me know if that helps.

Cheers

Oli
