### ISSUE TITLE
Setting Table height dynamically

### ISSUE THREAD

**Issue by 805bluebell** [olifolkerd/tabulator#2460]
You can't keep the table height according to the number of rows.
If you set `height: "300",` or any other value it'll render black area below if there are too few rows like this.
[see this image](https://i.stack.imgur.com/4ryC4.png)

**Tabulator Info**
Version 4.1.1
```
var table = new Tabulator("#example-table", {
    height:"auto",
    layout:"fitColumns",
    columns:[
        {title:"Name", field:"name", width:150, headerFilter:"input"},
        {title:"Progress", field:"progress", width:150, formatter:"progress", sorter:"number"},
        {title:"Gender", field:"gender", width:150, editor:"select", editorParams:{"male":"Male", "female":"Female"}, headerFilter:true, headerFilterParams:{"male":"Male", "female":"Female"}},
        {title:"Rating", field:"rating", width:150, editor:"star", align:"center", width:100, headerFilter:"number", headerFilterPlaceholder:"at least...", headerFilterFunc:">="},
        {title:"Favourite Color", field:"col", width:150, headerFilter:"input"},
        {title:"Date Of Birth", field:"dob", width:150, align:"center", sorter:"date",  headerFilter:"input"},
        {title:"Driver", field:"car", width:150, align:"center", formatter:"tickCross",  headerFilter:"input", width:150, headerFilter:"tickCross", headerFilterParams: {tristate:true}},
    ],
    data: data,
    selectable:true,
    selectableRangeMode: 'click',
});
```

**Working Example**
https://jsfiddle.net/opankajkumar/gfhL4o3r/20/

**To Reproduce**
In the above link, see the black area below the table. That's bad.

I tried [this answer](https://stackoverflow.com/questions/54178561/setting-maximum-table-height-with-tabulator/54185276#54185276) which had Oli's approval. 
Using this approach, If we have 100 rows then overflowing rows will be hidden. And don't try to set `overflow: scroll` in CSS because you'll lose virtualDOM advantage & everything will be rendered at once which will make the browser very slow. [Preview here.](https://jsfiddle.net/opankajkumar/gfhL4o3r/24/)

**Expected behavior**
The table should handle 2 to 2000 row data in the given area without polluting the DOM.

**Possible approach**
Setting height at dynamically using `.setHeight()`
[Demo here](https://jsfiddle.net/opankajkumar/gfhL4o3r/26/). But then you'll have to calculate height yourself.

It's a big headache.

**Comment by Nyut0n** [comment]
> Using this approach, If we have 100 rows then overflowing rows will be hidden. And don't try to set `overflow: scroll` in CSS because you'll lose virtualDOM advantage & everything will be rendered at once which will make the browser very slow. [Preview here.](https://jsfiddle.net/opankajkumar/gfhL4o3r/24/)

You have this scrolling issue because you apply your max-height to the whole table instead of tabulator-tableHolder class. See this fixed fork: https://jsfiddle.net/ay9g7mkf/

As for this request I fully agree that it would be useful to have a dynamic height with a min and max while retaining the performance advantages of the virtualDOM.

**Comment by olifolkerd** [comment]
Hey @805bluebell 

Thanks for the detailed usage case, i will stick something on the roadmap to ad a hybrid mode that allow it to fit the table to the rows until it exceeds a certain value.

Cheers

Oli :)

**Comment by 805bluebell** [comment]
@olifolkerd I would like to help you add this to Tabulator.

**Comment by 805bluebell** [comment]
> 
> 
> > Using this approach, If we have 100 rows then overflowing rows will be hidden. And don't try to set `overflow: scroll` in CSS because you'll lose virtualDOM advantage & everything will be rendered at once which will make the browser very slow. [Preview here.](https://jsfiddle.net/opankajkumar/gfhL4o3r/24/)
> 
> You have this scrolling issue because you apply your max-height to the whole table instead of tabulator-tableHolder class. See this fixed fork: https://jsfiddle.net/ay9g7mkf/
> 
> As for this request I fully agree that it would be useful to have a dynamic height with a min and max while retaining the performance advantages of the virtualDOM.

What if I have two or more tables on a page? Will that apply the same height to all the tables? I think it will since same class might be used by all of them. So, it ruins all the fun. Any hopes for that?

**Comment by olifolkerd** [comment]
Hey @805bluebell 

This wouldnt be managed my classes. this would be done by setting the table in classic render mode, then watching the table expand with the resize observer until its contents exceed the height of the table container element, then switching to virtual render mode.

It should be managed on a per table basis internally within tabulator, but there would be nothing wrong with you using a class outside of tabulator to set the max height on the table.

Oli

**Comment by olifolkerd** [comment]
I have pushed an update to the 4.6 branch that keeps the virtual DOM operational even when there is no height set, so this shouldnt be an issue in future.

Version 4.6 will be released in a few weeks.

Cheers

Oli :)
