### ISSUE TITLE
How can I use vanilla Tabulator in React?

### ISSUE THREAD

**Issue by 8483** [olifolkerd/tabulator#2463]
I am getting lost in the React implementation of Tabulator and was wondering how could I use the original implementation.  

Is it advisable? How would that work?

**Comment by olifolkerd** [comment]
Hey @8483 

You certainly can, checkout the guide for [Manually Including Tabulator in React](http://tabulator.info/docs/4.4/frameworks#react)

Cheers

Oli :)

**Comment by 8483** [comment]
Hello @olifolkerd,

Can you please include a functional component example in the documentation?

I am trying to implement it, but I can't get it to work.

```javasrcipt
import React, { useState, useEffect } from "react";

import Tabulator from "tabulator-tables";
import "tabulator-tables/dist/css/tabulator.min.css";

function Journal(props) {

    let refTable = React.createRef();

    const [journalItems, setJournalItems] = useState([]);

    useEffect(() => {
        new Tabulator(refTable, {
            data: journalItems,
            reactiveData: true,
            columns: ["a", "b", "c"],
        });
    }, []); 

    return (
        <div>
            <div className="foo" ref={refTable}></div>
        </div >
    )
}

export default Journal;
```
