### ISSUE TITLE
no option to show loadingElement if progressiveLoad is enabled

### ISSUE THREAD

**Issue by byoernn** [olifolkerd/tabulator#2464]
**Describe the bug**
When progressiveLoad is true, user will not be informed about that Tabulator is loading data.

**Tabulator Info**
- Version: 4.4
- SetupOptions:
``` 
{
...
             ajaxProgressiveLoad: "scroll",
            //virtualDomBuffer: 1200, //set virtual DOM buffer to 300px
            //ajaxProgressiveLoadScrollMargin: 100,
            ajaxLoader: true,
...
}
```

**To Reproduce**
1. init table with "ajaxProgressiveLoad"
2. open page with table

**Expected behavior**
User will get informed in any way, that tabulator is loading data/ doing work in background.
So user can expect that results will appear soon and don´t get frustrated. 
Especially on first load.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: IE11, Chrome

**Comment by olifolkerd** [comment]
This is intentional, otherwise it would be constantly interrupting the user as they scroll, the whole point of it is that it happens seamlessly in the background, the scroll margin should be set big enough that the data has loaded before the user reaches the bottom of the list

Cheers

Oli :)
