### ISSUE TITLE
Reactive data change does not update sorting

### ISSUE THREAD

**Issue by pbrenna** [olifolkerd/tabulator#2465]
First of all thank you for the great work on Tabulator.

Using tabulator 4.4.3.
Steps:
 - have a tabulator with reactiveData: true
 - click a column header to sort by that field
 - change the value of that field in a row of the data, so that the order of the rows should be updated

Result: the table is shown as sorted (bold arrow in the column header) but is not.

**Comment by olifolkerd** [comment]
This is correct, at present you have to use the sort functions In Tabulator.
