### ISSUE TITLE
Simpler/custom filter data format in ajax filtering

### ISSUE THREAD

**Issue by GCSBOSS** [olifolkerd/tabulator#2466]
### Is your feature request related to a problem? Please describe.
I want to use Tabulator **remote pagination** and **ajax filtering** to search an existing GET API to say list Cars. The Problem is Tabulator ajaxFiltering **requires** the server to understand it's *proprietary* filtering input data structure. Since this API is accessed from other services, I can't just change its filtering capabilities to conform to Tabulator, thus breaking the established interface.

### Describe the solution you'd like
A **simple** way to tweak the filters data sent to the server by ajax filtering. Mainly conforming to basic RESTful query string (`name=nice&brand=cool`) without fancy JSON or alike.

### Describe alternatives you've considered
- Include a *special* parameter in my API to read from Tabulator (very undesirable/intrusive).
- Load 3 gazillion records and do local filtering (performance is definitely a requirement).
- Build my own Tabulator.
- Listen to smooth Jazz and cry a bit.

### Context
http://tabulator.info/docs/4.0/data#ajax-filter

**Comment by fingers10** [comment]
Hey @GCSBOSS ,

Try `ajaxUrlGenerator` and modify it to suit your needs. This should help you.

```js
ajaxURLGenerator: function (url, config, params) {
                        const sorters = params.sorters || [];
                        delete params.sorters;
                        sortUrl = sorters.map(sort => `orderby=${sort.field.toLowerCase()} ${sort.dir}`).join('&');

                        const filters = params.filters || [];
                        delete params.filters;

                        const operators = {
                            '=': 'eq',
                            '>': 'gt',
                            '>=': 'gte',
                            '<': 'lt',
                            '<=': 'lte',
                            '!=': 'neq',
                            like: 'co'
                        };

                        (filters || []).forEach((filter) => {
                            filter.type = operators[filter.type] || filter.type;
                        });
                        searchUrl = filters.map(filter => `search=${filter.field.toLowerCase()} ${filter.type} ${filter.value}`).join('&');

                        return `${url}?${sortUrl}&${searchUrl}`;
                    }
```
