### ISSUE TITLE
Download XLSX error

### ISSUE THREAD

**Issue by AGrazka** [olifolkerd/tabulator#2467]
Hi guys, 
it seems that there is a problem with source to js file which is responsible for dowloading xlsx data.

On your website I can see same error. "Uncaught ReferenceError: XLSX is not defined"

**Comment by claudiolupo** [comment]
Hi!! 
To solve, I used this new link: https://oss.sheetjs.com/sheetjs/xlsx.full.min.js 
It seems working good...

**Comment by olifolkerd** [comment]
Hey @claudiolupo 

Thank for the link, i have pushed it to the 4.5 version of the site which should be going live in a few days.

Cheers

Oli : )
