### ISSUE TITLE
The filter by date does not work correctly

### ISSUE THREAD

**Issue by aalopatin** [olifolkerd/tabulator#2468]
Hi, Oli!

I try to use the tabulator in Nuxt.js. You were answering me at StackOverflow.

I think I've found an error in a work of filter by date.

I can't do filter types '>' or '<'.

You can see it at your example on the site.

![image](https://user-images.githubusercontent.com/52285445/68116182-42af0400-ff0b-11e9-8ea0-38bfef6ba9d7.png)

How you can see dates that are less than the filter value get in result.

**Comment by aalopatin** [comment]
After a long time searching I found that filter by date will work if type of column will have inputFormat equals 'YYYY-MM-DD'. Any other formats don't work. Even if I specify the inputFormat in formatterParams.

Maybe I wrong. But that's all that works for me.

So I identified the column:
```
{title:"Начало", field:"startPeriod", formatter:"datetime", formatterParams:{
                  inputFormat:"YYYY-MM-DD",
                  outputFormat:"DD.MM.YYYY"
                }, sorter:"date", visible: false},
```

And so I identified the filter:

`allPeriodsInstance.addFilter("startPeriod", ">", newValue)`

Maybe tabulator doesn't use inputFormat during filtering?

P.S.  I could also do customFilter, but it's more complicated than inputFormat = "YYYY-MM-DD"

**Comment by olifolkerd** [comment]
Hey @aalopatin 

The formatter params only change how the data is displayed not how it is filtered or sorted, the filter is a simple mathematical function and as such it would handle the date as a text string. if you want to do full date based filtering you would need to use a [Custom Filter Function](http://tabulator.info/docs/4.4/filter#func-custom)

I hope that helps

Cheers

Oli :)
