### ISSUE TITLE
columnVertAlign (middle) is not work

### ISSUE THREAD

**Issue by EnochG1** [olifolkerd/tabulator#2469]
**Describe the bug**
Hi, I'm using Tabulator with formatter, adding 3 DatePickers with jquery ui.
I expected other columns are located at middle position but results are like below.
(Sorry, web page is not English. just watch align please. Red square is expected position)
![image](https://user-images.githubusercontent.com/19601207/68169796-c5d66580-ffb0-11e9-8629-2a16225eae48.png)
![image](https://user-images.githubusercontent.com/19601207/68170124-e652ef80-ffb1-11e9-99e7-363d8cc3f0b5.png)

I thought 3-Datepicker column made height longer and other column cell height becoming same height(68px), so I tried make cell height shorter but it make border and resize handle not properly.
![image](https://user-images.githubusercontent.com/19601207/68170092-c4f20380-ffb1-11e9-90d7-d0198e2c2e4a.png)

**Tabulator Info**
- tabulator-tables 4.4.3 (package.json, with vue.js)
- Using tabulator.vue wrapper (call new Tabulator in mounted cycle)

**Working Example**
      tabulator: {
        height: 509,
        columnVertAlign: 'middle',
        expandBody: false,
        resizableColumns: true,
        resizableRows: false,
        movableRows: false,
        index: 'Id',
        columns: [...],
      }

Datepicker formatter was like below but I think it isn't important if it is Datepicker or not
```
        <div id="ExpireDate">
            <span class="expiration_date">
                <input type="checkbox">
                <input type="text" style="width: 72px;" />
            </span>
            <span class="expiration_date">
                <input type="checkbox">
                <input type="text" style="width: 72px;" />
            </span>
            <span class="expiration_date">
                <input type="checkbox">
                <input type="text" style="width: 72px;" />
            </span>
        </div>
```

```

// formatter
let $renderHtml = $('#ExpireDate').clone();
        $renderHtml.find('span.expiration_date').each(function(inx, el) {
          $(el).find('input[type=text]')
            .datepicker(DatepickerConfig).change(function() {
              let inputName = this.name;
              let checkName = this.name.replace('txt', 'chk');
              $(el).find('input[name=' + checkName + ']').prop('checked', true);
            });
        });

        return $renderHtml.get(0);

```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser : chrome

**Additional context**

**Comment by olifolkerd** [comment]
Hey @EnochG1 

The ***columnVertAlign*** option only affects column header vertical alignment not cells. though i can see the confusion there, i will rename that property in the next update to make it clearer that that is the case.

You will have to use CSS to achieve the vertical alignment in the cells.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
I have pushed an update to the 4.5 branch to change the option name to ***columnHeaderVertAlign*** to make it clearer

This should be going live in a few weeks.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
I have pushed an update to the 4.6 branch to handle vertical alignment in cells. It will be in the 4.6 release next weekend
