### ISSUE TITLE
all documentation is inaccessible/missing

### ISSUE THREAD

**Issue by s-c-p** [olifolkerd/tabulator#2470]
**Describe the bug**
The documentation is inaccessible.

**Tabulator Info**
- Haven't started using Tabulator yet 

**Working Example**

**To Reproduce**
Steps to reproduce this behavior:
1. go to wiki tab (on github) of this project
2. choose any topic, say "Sorting Data"
3. this opens to https://github.com/olifolkerd/tabulator/wiki/Sorting-Data
4. you get a stub article saying the doc link's prefix has changed, so you click them link http://olifolkerd.github.io/tabulator/docs#sorting
5. browser redirects to http://tabulator.info/docs/4.4 ***irrespective of the topic you're looking for***, try same for layout or pagination or any topic listed in wiki

**Expected behavior**
Be able to access correct page of documentation when we click links.

**Comment by olifolkerd** [comment]
Hey.

Thanks for the heads-up. The wiki is no longer in use. Please go to
Tabulator.info for access to the documentation.

The library is extensively documented with working examples on the website.
You can use the search bar in the top right of the site to find anything
you need.

I will remove the wiki to prevent confusion.

Cheers

Oli

**Comment by s-c-p** [comment]
@olifolkerd 
thanks for the quick reply, I was just dumb to not click on *Installation* link under the Setup Guide.

I have one request: please include a *Table of Contents* on Tabulator 4.4's docs homepage i.e. http://tabulator.info/docs/4.4.

I suppose the content under the headings **Setup Guide** & **Upgrade Guide** get looked over by eager users like me, I am like *"I just want tabulator.min.js for my school project, why read setup"*.  
A new heading or a brightly colored link to **Getting Started** would do equally well.
