### ISSUE TITLE
Rows auto removing

### ISSUE THREAD

**Issue by GrzegorzZajac000** [olifolkerd/tabulator#2471]
**Describe the bug**
Rows in the table are automatically deleted as you scroll.

**Tabulator Info**
- Which version of Tabulator are you using? 4.4.3
- Post a copy of your construct object if possible so we can see how your table is setup - Link below

**Working Example**
https://jsfiddle.net/aklaver/e0Ltqwrx/

**To Reproduce**
1. Open elements inspector
2. Scroll on table
3. See error

**Expected behavior**
Is there any option in config which turn off this behavior?

**Screenshots**
![Screenshot 2019-11-05 12 28 38](https://user-images.githubusercontent.com/12233796/68204462-59676080-ffc8-11e9-9980-516082cb3027.png)
![Screenshot 2019-11-05 12 28 48](https://user-images.githubusercontent.com/12233796/68204464-5bc9ba80-ffc8-11e9-9686-e686376d73e9.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.1
 - Browser: Chrome 
 - Version: 78.0.3904.70

**Comment by olifolkerd** [comment]
Hey @GrzegorzZajac000 

There is no issue here, this is how the virtual DOM works, as your scroll the top rows are delete and bottom rows are added, this is reveresed as you scroll the other way.

Only the rows that are actually visible ever exist, the rest are created and destroyed as they are needed, this allows Tabulator to handles 100,000s of rows without slowing down the browser.

an explanation of the vitrual DOM can be found in the [Documentation](http://tabulator.info/docs/4.4/virtual-dom)

If you are trying to acheive something specific please let me know and i can point you in the right direction.

Cheers

Oli :)

**Comment by GrzegorzZajac000** [comment]
No, Virtual DOM shouldn't work like that. But okay, my problem disappeared, I turned off VirtualDOM and it's ok now.

**Comment by olifolkerd** [comment]
With all due respect, my description is exactly how the virtual DOM is supposed to work. I should know,I wrote this library.

I don't know if something is being lost in translation with your description. Your demo works exactly as expected, as you scroll up and down the table the rows are being created and destroyed as expected. No rows are disappearing.
