### ISSUE TITLE
leaking event listeners on repeated table.setData()

### ISSUE THREAD

**Issue by Darth-Ender** [olifolkerd/tabulator#2472]
I have a web application that will repeatedly load data into a table using setData that receives an array of dictionary values.    Each time this occurs, event listeners will be leaked (orphaned) and this results in ever increasing delays in the browser on event emission and listening(where my listener is what sets the table data)  ...eventually grinding the page to a halt.   calling table.destroy() before recreating the table (referencing the variable I'd normally be using in setData) resolves the issue. 

Browser : Chrome. 
Tabulator version : 4.4.1
My table definition looks like this:

        table = new Tabulator("#selectTable", {
            data: tableData,
            layout: sessionStorage_getItem("WSTcolumnFit", "fitColumns"),
            selectable: true,
            pagination: "local",
            tooltips: true,
            tooltipsHeader: true,
            paginationSize: 10, 
            rowClick: function(e, row){
                    let selectedDiv = document.getElementById("selectedAmnt");
                    if(row.isSelected()){
                        selectedCnt++;
                    } else {
                        selectedCnt--;
                    }
                    if(selectedCnt > 0){
                        document.getElementById("undoButton").disabled = false;
                    } else {
                        document.getElementById("undoButton").disabled = true;
                    }
                    selectedDiv.innerHTML = "Rows Selected: <B>" + selectedCnt + "</B>";
            },

            columns: [
                { title: "Index", field: "index", visible: false, headerFilter: "input", headerSort: true, headerFilterFunc: paramStartWith },
                { title: "field1", field: "Field 1", headerFilter: "input", headerSort: true, headerFilterFunc: paramStartWith  },
                { title: "field2", field: "Field 2", headerFilter: "input", headerSort: true, headerFilterFunc: paramStartWith },
                { title: "field3", field: "Field 3", headerFilter: "input", headerSort: true, headerFilterFunc: paramStartWith },
                { title: "field4", field: "Field 4", headerFilter: "input", headerSort: true, headerFilterFunc: paramStartWith },
                { title: "field5", field: "Field 5", headerFilter: "input", headerSort: true},
                { title: "field6", field: "Field 6", headerFilter: "input", headerSort: true, headerFilterFunc: paramStartWith },
                { title: "field7", field: "Field 7", headerFilter: "input", headerSort: true,  headerFilter: true, formatter: "tickCross", editable: false },
                { title: "field8", field: "Field 8", headerFilter: "input", headerSort: true, headerFilter: true, formatter: "tickCross", editable: false },
                { title: "field9", field: "Field 9", headerFilter: "input", headerSort: true, headerFilter: true, formatter: "tickCross", editable: false },
                { title: "field10", field: "Field 10", headerFilter: "input", headerSort: true},
                { title: "field11", field: "Field 11", headerFilter: "input", headerSort: true},
                { title: "field12", field: "Field 12", headerFilter: "input", headerSort: true, headerFilterFunc: paramStartWith }
            ]
        });

**Comment by olifolkerd** [comment]
Hey @Darth-Ender 

Could you create a JS Fiddle or a Code Pen that demonstrates the issue, and make sure you are on the latest version of Tabulator incase that has resolved your problem

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @Darth-Ender 

Do you have any more information on this, if i dont hear back im afraid i will have to close this issue as there is not enough information in your initial post to isolate the issue.

Cheers

Oli :)

**Comment by Darth-Ender** [comment]
Unfortunately when I tried to make a self contained simplified version of
my code, I couldn't replicate the issue and the original is for work so I
can't make that available.

Not sure why the simplified version didn't have the problem since the only
change is destroying the table and recreating it vs using setdata.  The
table is small so recreating isn't a big deal so it is a usable solution.
 I guess if nobody else has a problem like this then chalk it up to
something weird I'm doing elsewhere I guess.

**Comment by olifolkerd** [comment]
Thanks for the response.

It is likely due to a custom formatter or something similar in that case.

That is the primary reason we ask for the reduced test case as it help to isolate if the issues are coming from within Tabulator.

Cheers

Oli :)
