### ISSUE TITLE
Built-in "progress" formatter is broken in Firefox

### ISSUE THREAD

**Issue by Nyut0n** [olifolkerd/tabulator#2473]
**Describe the bug**
Built-in "progress" formatter is broken in Firefox. Cells appear empty.

**Tabulator Info**
- Tabulator 4.4.3

**Working Example**
http://jsfiddle.net/zbjwxkmn/

**Desktop (please complete the following information):**
 - OS: Windows 10 1903
 - Firefox ESR 68.2.0
 - Firefox 70.0.1

**Additional context**
This doesn't happen in other browsers. 
Could be an issue in Firefox itself. Not sure.
I have noticed that sometimes opening/closing the dev console (F12) fixes it temporarily and the progress bar appears. But after any window resize event they disappear again. It's really strange.

**Comment by olifolkerd** [comment]
Hey @Nyut0n 

Thanks for the headsup, i will look at fixing this for the next release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @Nyut0n 

I have pushed a fix for this to the 4.5 branch which will be released in a few weeks.

Cheers

Oli :)
