### ISSUE TITLE
Header Component Extensions

### ISSUE THREAD

**Issue by aleksvagapitov** [olifolkerd/tabulator#2475]
**Describe the solution you'd like**
I would like to be able to change Column Title programmatically. I have a scenario where I am using "columnTitleChanged" as a way of updating values in the column, but I would like to be able to "reset" the HeaderTitle to original value after the function runs (With changes in the column still intact).

The other solution that I think would be helpful is the ability to interact with the header component the same way we can with the cell component i.e. being able to add various inputs/descriptions into CellHeader Component.

**Describe alternatives you've considered**
I have considered [https://github.com/olifolkerd/tabulator/issues/1517](url) and [https://stackoverflow.com/questions/52874940/how-to-change-column-title-in-table-that-was-created-by-tabulator-js](url), but I need to have the column with the changes, so reloading is not an option.

Much love for working so hard on Tabulator, and hopefully the features above would be considered for next release.

**Comment by olifolkerd** [comment]
Hey @aleksvagapitov 

The answer to #1517 wuold still work for you, you just need to call the ***getDefinition*** function on the column component to get the definition object, make your changes to the definition then delete the old column and add the new column.

The 4.5 release will include a function to update the column definition which will do this for your in one go.

Cheers

Oli :)
