### ISSUE TITLE
PDF Export - autoTable is not a function

### ISSUE THREAD

**Issue by ozzi-** [olifolkerd/tabulator#2476]
**Describe the bug**
When trying to render a PDF export, "autoTable is not a function" is thrown by tabulator.min.js.

**Tabulator Info**
- Which version of Tabulator are you using?
4.4.3
- Post a copy of your construct object if possible so we can see how your table is setup
See working example.

**Working Example**
https://codepen.io/ozzi_____/pen/YzzjQyo

**To Reproduce**
1. Go to https://codepen.io/ozzi_____/pen/YzzjQyo
2. Click on "Download as PDF"
3. Check Console

**Expected behavior**
PDF is generated.

**Screenshots**
https://i.imgur.com/vDdD4Eu.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser FF 70

**Comment by olifolkerd** [comment]
You have required the jspdf dependencies in the wrong order, it must be the jspdf library then auto table, as per the [Documentation](http://tabulator.info/docs/4.4/download#pdf)

```html
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.5/jspdf.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.0.5/jspdf.plugin.autotable.js"></script>
```

Autotable is a plugin for jspdf, if the main library is not there first it has nothing to bind to.

Cheers

Oli :)

**Comment by ozzi-** [comment]
Hi Oli
Thanks for the fast reply, it works! embarrassing ... 

Cheers
