### ISSUE TITLE
Firefox issue: zebra (odd/even) rows get clumsy redraw on scroll

### ISSUE THREAD

**Issue by azev** [olifolkerd/tabulator#2478]
In Firefox 70, when using tabulator with css zebra (odd/even) rows, the odd/even rows get a **clumsy redraw when I scroll the table**. Feels like I'm using an old computer but it is not the case (i7 8Gb RAM).
In Chrome it doesn't happen.

**Comment by olifolkerd** [comment]
Please create a js fiddle that demonstrates your issue. There are thousands
of ways to configure a table and it is hard to offer advice without seeing
yours in action

Cheers

Oli
