### ISSUE TITLE
Persistance mode for all users - question

### ISSUE THREAD

**Issue by AGrazka** [olifolkerd/tabulator#2479]
Hi guys,

I have quick question. Is it possible to use persistent mode to "save" columns position, width, visibility etc. for all users? I mean - if user A makes changes, user B will be able to see them. 

Thank you in advance :-)

**Comment by olifolkerd** [comment]
Persistent data is stored on the client browser so only if they are using the same computer and browser.

To persist it globally you would need to store the information server side and pull it down with the page load.

If you have a look at the persistence documentation there are functions you can call manually to retrieve and set the persistence layout information manually.

I hope that helps

Cheers

Oli 😁
