### ISSUE TITLE
Minimum build of jquery-ui required for Tabulator

### ISSUE THREAD

**Issue by carterwe** [olifolkerd/tabulator#248]
What is the minimum build of jquery-ui required for Tabulator?

**Comment by olifolkerd** [comment]
Hey,

Do you mean version number or dependant components?

Cheers

Oli

**Comment by carterwe** [comment]
Dependent components.  Thanks!

**Comment by olifolkerd** [comment]
Hey,

I though your question was such a good one,  I have added a new section to the documentation along with a link to the minimum required build on the jQuery website.

Full details can be found in the ***Setup*** section of the documentation [here](http://olifolkerd.github.io/tabulator/docs/#dependences)

Cheers

Oli
