### ISSUE TITLE
getRow iteration on the whole table not working

### ISSUE THREAD

**Issue by kreamas** [olifolkerd/tabulator#2480]
Hi.

I've done a table which I have to iterate all over (cell by cell) to change numbers based on certain conditions.

My table has only 22 rows and 12 columns.  Everything works fine until my iteration reaches the row 21, the iteration is suddenly broken.

I've proved to get only the row 21 using:

mytable.getRow(21).getCell('myColumn').getValue(); 

but nothing happens...if I do the same up to row 20 then everything is ok.

Why is it happening?

Thanks a lot

**Comment by olifolkerd** [comment]
That is because the cell components don't exist until the row is first rendered. If you are updating the data on the rows I would suggest calling the update function on the row component instead of the set value function on the cell component

**Comment by kreamas** [comment]
Thanks a lot for your response...I'm wondering why does the row from 1 to 20 let me do the work but just the last 2 rows don't?

I mean, if it doesn't exist until the row is rendered why it's always the case until it reaches the 21st row?

**Comment by olifolkerd** [comment]
Because those other rows have been rendered. The virtual DOM renders up to
a tables height beyond the end of the table to make scrolling look smoother.

This is perfectly normal and expected behaviour. The correct approach for
your intended action is to use the row.update function

**Comment by kreamas** [comment]
Thanks a lot for your response as always Oli =D

It works perfectly.

Have a nice day!!!

**Comment by kreamas** [comment]
Following this question...how can I change the color of the rows (I've just changed the value...but I would like to change the color as well)

I used:

row[k].update({mycolumn: 'myvalue'});

...and it worked...but what if I want to change the color as well?

**Comment by olifolkerd** [comment]
Use a row formatter

**Comment by kreamas** [comment]
I've tried it setting conditionals in this way within my iteration:

if (data == 0){
   row[k].getCell('mycolumn').getElement().style.backgroundColor = "blue";
} else {
   row[k].getCell('mycolumn').getElement().style.backgroundColor = "red";
}

But the same thing...it just iterates up to row 20 :'(

**Comment by olifolkerd** [comment]
Use row.getData instead. None of your code should be referencing the cells. Work only from the data

**Comment by kreamas** [comment]
So for example, to get the element of a row in a specific column should I use:

row[k].getData()['mycolumn'].getElement().style.backgroundColor = "blue";

??

**Comment by kreamas** [comment]
Oli, sorry for being this annoying, but I haven't got what I'm trying to do.

I've tryed over and over again but can't change cell background color dynamically based on conditions.... :(

I've changed the value conditionally using "update" as you suggested...but I would also want to change the background color based on condition (if value = 0 then...color = "red", else color = "green")

The problem is the same...I can't get the cells for rows greater than 20 :(

**Comment by olifolkerd** [comment]
Im really confused as to what it is you are actually trying to acheive, in your earlier question you were trying to change the color of the row, but now you seem to be trying to change the color of the cell.

if you are trying to style a spciefic cell you should be using a custom formatter on the column, that will be called any time cell is rendered or the the value is updated 

If you are trying to color the row as a whole then you should be using the rowFormatter.

**Comment by kreamas** [comment]
Hi Oli, thanks a lot for your patient 💃 

Finally found it:


var formateaTabla = function(cell, formatterParams){
                 var value = cell.getValue();
                  if(value == 0){
                      cell.getElement().style.backgroundColor="#fd9dab"
                      //cell.getRow().getElement().style.backgroundColor="#fd9dab";
                      return "<i class='fa fa-times' style='color:red;'></i>";
                  }else{
                      cell.getElement().style.backgroundColor="#a9ff8f";
                      //cell.getRow().getElement().style.backgroundColor="#a9ff8f";
                      return "<i class='fa fa-check'  style='color:green;'></i>";
                  }
              };

Then dynamically assigned the function in formatter this way:


        kols = "";
        c = 1;
        for (i = 0; i < json.lasKols.length; i++){
          if (c==1){
            kols = kols + '{"title":"' + json.lasKols[i] + '","field":"' + json.lasKols[i] + '", "frozen":"true","align":"center","formatter":' + ponNegritas +'},'
            c = 0;
          } else {
            kols = kols + '{"title":"' + json.lasKols[i] + '","field":"' + json.lasKols[i] + '","cssClass":"tavlita","align":"center","formatter":' + formateaTabla +'},'
          }

        }

        kols = "[" + kols + "]";
