### ISSUE TITLE
Build an Ember Component and Quick Setup Guide

### ISSUE THREAD

**Issue by Edward-Chen-CN** [olifolkerd/tabulator#2481]
This library looks great. It will be really appreciate if it can support ember.js and even some tutorials

**Comment by olifolkerd** [comment]
Hey @Edward-Chen-CN 

Thanks for your kind words, It is always great to hear Tabulator is appreciated :)

Tabulator is a vanilla JS library, as such it can be used with any framework. if you have an example of using it with ember i would be happy to add a setup guide to the [Frameworks Support Documentation](http://tabulator.info/docs/4.4/frameworks)

If you are looking for a Tabulator ember component, then im afraid i leave that up to the community to create frameworks specific components that instantiate Tabulator. Which is exactly what has happened with the react and vue components. It takes all my spare time to look after the core Tabulator library.

I am happy to support development of these with information on how to best integrate Tabulator, and to link to the component from the tabulator website when it is ready.

If you would be intrested in building such a package yourself, could you please name the package ***ember-tabulator*** to fit with the naming convention of the other Tabulator components.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @Edward-Chen-CN 

I have noticed that someone has started work on [emper-tabulator](https://www.npmjs.com/package/ember-tabulator)

If this is your package, please let me know and i can look at adding it to the frameworks page on the website.

Cheers

Oli :)
