### ISSUE TITLE
Column header & data misaligned when using column groups with hidden columns

### ISSUE THREAD

**Issue by blankbadge** [olifolkerd/tabulator#2482]
**Description**
Thanks for this fantastic library, Oli!  I'm experiencing an issue where the column headers become misaligned with their data.  I've isolated it specifically to the combination of two features: Column grouping together with hiding some of those columns.  The problem is progressively worse as you scroll to columns further to the right, as the misalignment accumulates.

**Tabulator Info**
Tabulator 4.4.3
Simple construct object, but using column groups and hiding columns.

`const table = new Tabulator("#example-table", {
    columns: columns,
    data: data
});`

**Working Example**
https://jsfiddle.net/blankbadge/5stugxd9/

**To Reproduce**
Run the jsfiddle.  It builds a table of 10 rows and 100 columns, where each set of five columns are grouped together.  I then use the column.hide() method to hide every other column.  Scroll to the right.  As you get to larger numbered columns, the misalignment between the headers and the data fields becomes very clear.  

There are two variables at the top of the example: groupColumns and hideColumns.  Toggle either of them to 'false' to see that the problem only occurs when both column grouping and hiding is enabled.

**Expected behavior**
Columns and their data remain aligned.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 77.0.3865.120

**Comment by olifolkerd** [comment]
Hey @blankbadge 

Thanks for the JS Fiddle that was very helpful. It looks like something in the stylesheet has regressed. it is adding an extra 1px border on the last column header in each column group which is throwing off the header by 1 px for each group.

I will have a look into fixing this for the 4.5 release.

Cheers

Oli :)

**Comment by blankbadge** [comment]
Hi @olifolkerd,

I just noticed you released 4.5, thanks!  I tested it out, and do still see the issue.  Based on your release notes, I think it's expected, but just letting you know the JS Fiddle demonstrating the issue above is updated to the latest Tabulator version.

thanks,
james

**Comment by olifolkerd** [comment]
Hey,

Yup, I ran out of time to fix the issue before the release unfortunately.

I will comment on here and close the issue when a patch for it is available

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @blankbadge 

I have pushed a fix for this to the 4.6 branch, which will be released later this weekend.

Cheers

Oli :)

**Comment by ayushi023** [comment]
@olifolkerd  Just wanted to check if this was fixed? I am facing the same issue

**Comment by olifolkerd** [comment]
Hey @ayushi023

As per the last comment in this thread, this was closed 2 years ago, when the issue was resolved.

This issue on a very old version of Tabulator the code has been completely rewritten in the 5.x releases, and is almost certainly completely unrelated to this issue

If you are experiencing an issue i would suggest creating a new bug report and filling in the needed info.

Cheers

Oli:)
