### ISSUE TITLE
Downloading a subset of columns (and re-ordered)

### ISSUE THREAD

**Issue by darshanrampatel** [olifolkerd/tabulator#2483]
Hi Oli,

Thanks for the great library!

**Is your feature request related to a problem? Please describe.**
I have a tabulator table (that's working great) where I would like the user to be able to choose which columns they want displayed in a PDF/CSV export. They will be able to also re-order these columns.

At the moment, I am solving this by hiding the columns they have hidden (with `table.hideColumn("columnName")`) and re-ordering them (in a for loop, with `table.moveColumn("columnNameA","columnNameB", true)`).

Then I call `table.download(...)`.

I then use the `downloadComplete` table callback to re-show and re-order the columns to their prior state.

This all works fine, but I see some performance issues due to my hiding/moving lots of columns (some of which have custom formatters applied) effectively twice.

**Describe the solution you'd like**
Be able to supply an ordered list of columns to the download function that would just download those columns.

**Describe alternatives you've considered**
If that's not possible, if there could be a flag (similar to #2084) that would let me block drawing of the table and then apply my hiding/moving, then download the file, then re-able drawing of the table that would help with performance.

**Comment by olifolkerd** [comment]
Hey @darshanrampatel 

Thanks for getting in touch, it is great to hear that Tabulator is appreciated :)

You can already choose which columns are visible in the table by setting the ***download*** property in the column definition, an example of this can be found in the [Download Documentation](http://tabulator.info/docs/4.4/download#advanced-hide)

As for the column ordering, i would recommend that you look at building an array of definitions for the download setup, then store the old column config, use ***setColumns*** to replace the column layout, then trigger the download, then restore the original columns. that way you wouldnt move the columns one at a time which should speed things up.

Im considering the "block redraw" functionality in more detail for the 4.6 release.

As this is a bit of an edge case functionality i would not be looking to include row reordering for downloads in tabulator as a feature, but as outlined above there are approaches you could take to manage it yourself.

I hope that helps

Cheers

Oli :)
