### ISSUE TITLE
Issue with CORS handling

### ISSUE THREAD

**Issue by mtstedman** [olifolkerd/tabulator#2484]
**Describe the bug**
Can't replicate an ajax calls that supports cors + auth using the ajaxConfig settings.

**Tabulator Info**
Using 4.2

```
table = new Tabulator('#' + container, {
				placeholder:"No Data Set",
				movableColumns: true,
				ajaxURL: apiURL,
				ajaxConfig:{
					method:"GET",
					credentials: 'include'
                                }
				ajaxParams: aJaxRequest, 
				responsiveLayout: 'collapse',
				columns: columnSchema,
				rowFormatter: function(row) {
					console.log(tableGroups[tableIndex]);
					if (tableGroups.length - 1 > tableIndex && row.getData().id != null && !(tableGroups[tableIndex] == 'purchase')) {
						buildSubtableContainer(row, tableGroups, tableIndex, filters, container);
					}
				},
				layout:"fitColumns"
			})

```

I've also tried (the settings in the working ajax call):

```
				ajaxConfig:{
					method:"GET",
					contentType: "application/x-www-form-urlencoded; charset=UTF-8",
					traditional: true,
					crossDomain: true,
					xhrFields: {
						withCredentials: true
					},				
				},
```

**Expected behavior**
Returns some variant of a CORS error no matter what I do.  Calling the ajax first, and loading the table constructor in the success function works fine though.  Not a huge issue as I could just write the ajax call myself, but certainly odd that I couldn't find anyway to do it with the native functionality.

**Desktop (please complete the following information):**
PC
Chrome

**Comment by olifolkerd** [comment]
Hey @mtstedman 

I would suggest that you use the developer console to see what headers are being sent in your successfull ajax call, then check what headers are being sent in tabulators request.

You can then add any missing headers you need using the ***ajaxContentType*** table setup option. See the [Ajax Documentation](http://tabulator.info/docs/4.4/data#ajax-content) for more information.

Cheers

Oli :)
