### ISSUE TITLE
Pressing tab key to move focus from one cell to another is not working in IE 11

### ISSUE THREAD

**Issue by nfessel** [olifolkerd/tabulator#2485]
**Describe the bug**
Pressing the tab key to move focus from one cell to another is not working in IE 11.

**Tabulator version**
Tabulator 4.4

**To Reproduce**
Using Internet Explorer 11, go to http://tabulator.info and click on the first cell in one of the demo tables. Now press the tab key and tabulator does not focus on the next cell.

**Expected behavior**
In Internet Explorer 11, tabulator should put focus on the next cell when the user presses the tab key. This issue is unrelated to my specific implementation, because the issue occurs with the demo tables on http://tabulator.info.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Internet Explorer 11
 - Version 11.864.17763.0

**Comment by nfessel** [comment]
I commented out this if statement in focusCellNoEvent and now tabstops work in IE 11 for me. 

Does anyone know if there is an issue with removing this if block from focusCellNoEvent?

`	Edit.prototype.focusCellNoEvent = function (cell) {
		this.recursionBlock = true;
		//if (this.table.browser !== "ie") {
			cell.getElement().focus();
		//}
		this.recursionBlock = false;
	};
`

**Comment by olifolkerd** [comment]
Hey @nfessel 

That functionality is necessary to prevent recursive editor generation on failed validation in IE, and certainly cannot be removed from the core library. If validation fails the system would get caught in a loop and the browser would crash.

It does clearly seem to be having an unintended side effect of blocking tabbing from cells. so i will have a look into that when i get a second.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @nfessel 

I have pushed a fix for this to the 4.5 branch which should be released in a few weeks.

Cheers

Oli :)

**Comment by nfessel** [comment]
Excellent. Thank you very much for the fast response @olifolkerd
