### ISSUE TITLE
Implemented custom input text editor doesnot return value

### ISSUE THREAD

**Issue by gaurankpatil** [olifolkerd/tabulator#2487]
We have implemented a custom input text editor but it doesn't return value.We want text fields on load to be visible to edit and not on cell click.After implementing custom editor for drop it worked but for text field it is not working.
Any solution including CSS change will help.

**Comment by olifolkerd** [comment]
Please include a like to a js fiddle or an example of your editor code. It is impossible to offer you advice without knowing how you have things setup
