### ISSUE TITLE
Column Lock feature

### ISSUE THREAD

**Issue by muthukvs** [olifolkerd/tabulator#2488]
I am using tabulator and it is giving me fantabulous features all together.

I need a column to be editable/non-editable which can be chosen at screenlevel?

is this possible?

Like user can have a checkbox option at column level to disable editing in this column.

is this feature available?

Cheers

Muthu

**Comment by olifolkerd** [comment]
There is an editable callback you can set in the column definition that can be used to determine if the cell can be edited
