### ISSUE TITLE
Align Top for List Lookup

### ISSUE THREAD

**Issue by BillMeyerRSA** [olifolkerd/tabulator#2493]
**Is your feature request related to a problem? Please describe.**
I have a number of columns in table. One is a Lookup Formatter, and some TextArea fields. 
The Text Area fields has large row height. When clicking on the Lookup, the dropdown is at the bottom of the cell. Awkward to do dropdown selects on the cell.
**Describe the solution you'd like**
At the moment the cell alignments that I find is only for horizontal (left, centre, right) but no vertical alignment (top, middle, bottom) and it defaults to bottom. 
Would like a cell alignment for the dropdown to at least allow for top vertical alignment.

**Describe alternatives you've considered**
Only other solution that I am thinking is writing a custom cell formatter for dropdown.

**Comment by olifolkerd** [comment]
Hey @BillMeyerRSA 

Thanks for the suggestion, i think that is a great idea. I will add it to the roadmap for future release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @BillMeyerRSA 

Vertical alignment will be coming in the 4.6 release later this weekend.

Cheers

Oli :)
