### ISSUE TITLE
tabulator.min.js:10 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event.

### ISSUE THREAD

**Issue by xinxilas** [olifolkerd/tabulator#2494]
Im receiving this message,

Here is the line:
![image](https://user-images.githubusercontent.com/38674705/69017977-cdbae000-0988-11ea-9e5e-57b2892c3dcf.png)

The linK:
See https://www.chromestatus.com/feature/5745543795965952

**Comment by olifolkerd** [comment]
Which version of Tabulator are you using?

Please use the correct issue template when creating an issue or it will be closed without answer

**Comment by xinxilas** [comment]
Sorry

Tabulator v4.4.3

**Comment by olifolkerd** [comment]
@xinxilas 

Could i ask that if you are creating a bug report that you follow the  

This isnt an issue, it is a debug level warning, so not acutally a problem [Bug Reporting Community Guidelines](http://tabulator.info/community#bug) it is very important that you use the correct template as it asks you for the information we need to get to the bottom of the issue.

You also ***MUST*** provide a JS Fiddle or code pen that demonstrates the issue, it is almost impossible to get to the bottom of a problem without seing how your table is configured.

I wouldn't be concerned about that warning at all it is a debug level notice about a niche performance issue that could affect mobile but not in any meaningful way and would have no effect on desktop usage.

There is no point on disabling the event listeners on desktop, there are only a few added and the have no performance overhead.

Cheers

Oli :)
