### ISSUE TITLE
tooltipGenerationMode - hover only?

### ISSUE THREAD

**Issue by GuzziGuy** [olifolkerd/tabulator#2495]
Tabulator 4.4 - I'm using tooltipGenerationMode:"hover" so I can generate a tooltip via (synchronous) ajax.

But it seems even when it is set to hover, it still generates all visible tooltips on render/scroll - and then again on hover. This results in a huge number of ajax calls and is currently unworkable.

Could it be updated so that in this mode, tooltips are not generated when rendering, only on hovering?

**Comment by olifolkerd** [comment]
Hey @GuzziGuy 

Generating tooltips by ajax seems a bit counter intuative as if the user has a slow network connection it will not be able to immediately generate the tooltip on hover.

It would be better UX practice to cache information needed client side and generate the tooltip in browser.

Cheers

Oli :)
