### ISSUE TITLE
[Violation] 'scroll' handler took

### ISSUE THREAD

**Issue by amchconsult** [olifolkerd/tabulator#2496]
![Screen Shot 2019-11-20 at 8 40 18 AM](https://user-images.githubusercontent.com/40743265/69236014-6dd35d80-0b71-11ea-899a-0993a709a8ed.png)

I keep getting this error and editable cell became unresponsive.
I am using tabulator version /* Tabulator v4.4.3 (c) Oliver Folkerd */

Please if you can take a look.

Thank you very much

**Comment by amchconsult** [comment]
I have try using this in the html, but still the same.

<script>
// FIX tabulator error VIOLATION
(function () {
    if (typeof EventTarget !== "undefined") {
        let func = EventTarget.prototype.addEventListener;
        EventTarget.prototype.addEventListener = function (type, fn, capture) {
            this.func = func;
            if(typeof capture !== "boolean"){
                capture = capture || {};
                capture.passive = false;
            }
            this.func(type, fn, capture);
        };
    };
}());
</script>

**Comment by olifolkerd** [comment]
You need to post a like to a jsfiddle that demonstrates the issue. It is impossible to help you without seeing how your table is configured

**Comment by amchconsult** [comment]
Hi,
Thank you for answering me. 
I have upload a little demo for you.
[](https://github.com/amchconsult/table)
Just run index.html
You will see on console level verbose the errors mentioned.
Please let me know if you need something else.
Thank you very much

**Comment by amchconsult** [comment]
Hi,
Thank you for answering me.
I have upload a sample for you.
[https://github.com/amchconsult/table](url)
Just run index.html
You will see on console verbose the errors mentioned.
Thank you very much

**Comment by olifolkerd** [comment]
Hi @amchconsult 

I am very happy to help you, but i ask that you please read the [Bug Reporting Comunity Guidelines](http://tabulator.info/community#bug) first.

If you want help with a bug you ***MUST*** create a JS Fiddle or Code Pen that demonstrates the issue in action.

Im afraid with 1000's of users we simply dont have the time to spin up servers to run peoples example code. It is really simple to setup a code pen or JS fiddle and shouldnt take more than a few minutes.

Without that im afraid we cannot offer you any help on this issue.

Cheers

Oli :)

**Comment by amchconsult** [comment]
Ok, sorry 
I will create the jsfiddle.

**Comment by amchconsult** [comment]
Hi,
It took me some time, this app has big tables with a lot data on it.

https://jsfiddle.net/alecode13/8d2qjyza/

Thank you again

**Comment by olifolkerd** [comment]
Hey @amchconsult 

Thanks for the fiddle, that clears things up!

And WOW that is a lot of columns you have there.

You can ignore that message, it is a debug level message not a warning. it is occurring because it is taking longer than the browser would usually expect the scroll to happen. this is because the sheer number of columns in your table means it is taking a while for each row to be drawn.

All it means is that the scroll animation may occasionally drop a frame which could result in a slight jigger. nothing to worry about.

Cheers

Oli :)

**Comment by amchconsult** [comment]
Thank you. 
But why editable cell when you click on it, it is not responsive. It is like it was disabled?
Thank you again.

**Comment by olifolkerd** [comment]
Which particular editable cell are you struggling with.

Can you provide step by step instructions on how i replicate your issue in the fiddle.

Cheers

Oli :)

**Comment by amchconsult** [comment]
The cell edition becoming unresponsive is caused by the timeout of refresh when scrolling.
Yes, It is too many columns.
Thank you so much for your help
