### ISSUE TITLE
[4.4.3] JS error

### ISSUE THREAD

**Issue by hrstoyanov** [olifolkerd/tabulator#2497]
**Describe the bug**
```
Uncaught TypeError: Cannot read property 'tagName' of null
    at Tabulator._create (tabulator.js:7559)
    at new Tabulator (tabulator.js:6977)
    at showSkeletonList (AccountsList.html?_ijt=trhdvtlcphuuhd17hjlut9cvf6:37)
```

**Tabulator Info**
- 4.4.3

**Working Example**
https://jsfiddle.net/Lwg1xa6j/

**Expected behavior**
To see some grid.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version:  78.0.3904.97

**Additional context**
It used to work before 4.4.3

**Comment by Nyut0n** [comment]
you are using the wrong element ID in `new Tabulator( ... )`

**Comment by hrstoyanov** [comment]
My bad :-)
