### ISSUE TITLE
Minor doc fixes for 4.5 Release Notes

### ISSUE THREAD

**Issue by Jojoshua** [olifolkerd/tabulator#2498]
**Website Page**
http://tabulator.info/docs/4.5/release

- Section for persistenceReaderFunc  code snippet has wrong function

- HTML Downloader
Regarding the code snippet: table.download("html", "data.html", {style:"true"}); . The style should be a boolean true not string "true"

**Comment by olifolkerd** [comment]
Hey @Jojoshua 

Thanks for the headsup, i have just pushed a fix for those to the website.

Cheers

Oli :)
