### ISSUE TITLE
Tooltip for header.

### ISSUE THREAD

**Issue by sydesb** [olifolkerd/tabulator#25]
Hi, is it possible to display a tooltip for header to read when the title is too long :
![capture](https://cloud.githubusercontent.com/assets/16446916/15281717/fdabe472-1b3d-11e6-88a0-5f0c36f01644.PNG)
And i don't understand why tooltip for cell aren't displayed in the good position : problem of css on my website ?
![capture2](https://cloud.githubusercontent.com/assets/16446916/15281769/6c69b3ee-1b3e-11e6-8103-ea931c943e79.PNG)

**Comment by olifolkerd** [comment]
i will add the header tooltips in this evening.

the tooltips are handled by the browser, they just use the standard ***title*** attribute. which browser are you using?

**Comment by sydesb** [comment]
Thank you ! It's firefox 46.0.1

**Comment by olifolkerd** [comment]
The tooltips seem to render correctly on firefox at this end, not sure why that is happening im afraid. might be something to do with the way the js framework you are using displays the table, have you tired testing the same table on an empty page to see if the tool tips work then.

On the good news front, i have started adding the header tooltips option and should have something online in the next few hours.

**Comment by olifolkerd** [comment]
Tooltips for headers are now available, just set the ***tooltipsHeader*** option to ***true*** when you define your Tabulator.

**Comment by sydesb** [comment]
Thank you again. I'll try it this evening or this afternoon(sorry, i was left)

**Comment by sydesb** [comment]
I did not wait and I tried. The tooltip is displayed, thank you! However, it is always on the left. I'll  try to  why. I wonder if it did not relate to Bootstrap.

**Comment by olifolkerd** [comment]
The Tabulator site itself uses Bootstrap, so probably not directly related, it may have something to do with the way it is being revealed in the drop down.

Have you tried creating the table when the element is visible as a test and see if that fixes it?

Many Thanks

Oli

**Comment by sydesb** [comment]
I just tried and the problem is still here.
With Firebug, I deleted the rest of the HTML code, empty all the .css, jquery removed with the console and the problem is still here! 
I do not understand....

**Comment by olifolkerd** [comment]
Can you see what happens when you view the ***examples.html*** that comes in the tabulator package.

i have run it in  firefox 46.0.1 and the tool tips are appearing over the cells like they should

**Comment by sydesb** [comment]
It was a conflict on my website. Thank you again !
![capture](https://cloud.githubusercontent.com/assets/16446916/15456520/d261d42c-2072-11e6-9c5f-21edb3595d55.png)
!
