### ISSUE TITLE
looks like a 'finger' bug...

### ISSUE THREAD

**Issue by georgescarotte** [olifolkerd/tabulator#250]
![image](https://cloud.githubusercontent.com/assets/26894774/24647997/6561e232-1922-11e7-9a3d-acd8f36028ff.png)

![image](https://cloud.githubusercontent.com/assets/26894774/24648023/71ebfab0-1922-11e7-9a46-af48b1206543.png)

**Comment by olifolkerd** [comment]
Hey,

This was fixed a month ago in the latest commits in the repo,

A release version with this in will be coming in the next couple of weeks.

Cheers

Oli
