### ISSUE TITLE
links with display label of "false" will not show up

### ISSUE THREAD

**Issue by sellersj** [olifolkerd/tabulator#2500]
**Describe the bug**
If a link has a label of true / false, the false values will not show up. This worked in the 3.x stream.
I think that it's from the false tests in format.js
https://github.com/olifolkerd/tabulator/blob/master/src/js/modules/format.js#L188

**Tabulator Info**
Reproducible with 4.4.3 and 4.5.0

**Working Example**
https://jsfiddle.net/sellersj/c7zLxp95/1/
```
var tabledata = [
 	{id:1, name:"Oli Bob", age:"12", compliant:true, reportUrl:"http://example.com/28"},
 	{id:2, name:"Mary May", age:"1", compliant:true, reportUrl:"http://example.com/29"},
 	{id:3, name:"Christine Lobowski", age:"42", compliant:false, reportUrl:"http://example.com/49"},
 ];


//Build Tabulator
var table = new Tabulator("#example-table", {
    data: tabledata,
    layout:"fitColumns",
    columns:[
    {title:"Name", field:"name"},
    {title:"Age", field:"age"},
    {title:"Compliant", field:"compliant", formatter:"link", formatterParams:{urlField:"reportUrl"}},
    ],
});
```

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Have data that is true / false (per compliance)
2. Have a url that will be linked to it

**Expected behavior**
If the underlying label field is actually false, it expected that it would show up.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Firefox 70.0.1 / Chrome 78.0.3904.108

**Smartphone (please complete the following information):**
Untested

**Additional context**
none

**Comment by olifolkerd** [comment]
Hey @sellersj 

In this case i would consider it surprising that the values show up at all considering neither is a valid string, which is what a label should be and they are both Booleans.

In this case i would suggest that you use a [Mutator](http://tabulator.info/docs/4.5/mutators#mutators) to map your Boolean into a string which would be a valid label.

Cheers

Oli :)
