### ISSUE TITLE
While binding edit icon using formatter ,onclick event not triggered in angular

### ISSUE THREAD

**Issue by vnaveed** [olifolkerd/tabulator#2501]
Question :While binding edit icon with onclick event not triggered that function in angular

Please find my below code .Thanks in advance

import { Component, OnInit, Input, OnChanges, SimpleChanges, Output } from '@angular/core';
import Tabulator from 'tabulator-tables';

@Component({
  selector: 'app-tabulator',
  templateUrl: './tabulator.component.html',
  styleUrls: ['./tabulator.component.scss']
})
export class TabulatorComponent implements OnChanges {
  
  @Input() tableData: any[] = [
    {name:"Oli Bob", location:"name"},
    {name:"Mary May", location:"gender"},
  ];
  @Input() columnNames: any[] = [
    { title:"Name", field:"name",width:450},
    {title:"Gender", field:"gender",width:450,formatter:this.editClicked}
  ];
  @Input() height: string = '311px';
 // list properties you want to set per implementation here...
 
 tab = document.createElement('div');

  constructor() {
  }
  editClicked(){
   return "<    button onclick='clickMe()'  >Edit< /   button >";
  }
//this method not called
  clickMe(){
   alert("inside click me")
  }
  
  ngOnChanges(changes: SimpleChanges): void {
    this.drawTable();
    
  }
  ngOnInit(){
    this.functiontest();
    this.drawTable();
  }
  public drawTable(): void {
    //alert()
    new Tabulator(this.tab, {
      data: this.tableData,
      reactiveData:true, //enable data reactivity
      columns: this.columnNames,
      layout: 'fitData',
      height: this.height
    });
    document.getElementById('my-tabular-table').appendChild(this.tab);
  }
}

**Comment by MohamedYasarArafat** [comment]
Hi vnaveed

**I also faced this issue,if anyone found the solution please help us.**

**Comment by olifolkerd** [comment]
@vnaveed 

Can i ask why you used the bug reporting issue template, then deleted the entire template? It prompts you for the information we need to fix you issue.

Please read the [Reporting a Bug Guide](http://tabulator.info/community#bug) and resubmit your issue with the information needed to resolve it.

Cheers

Oli :)
