### ISSUE TITLE
Bad selected item if option value is text but starts with a digit

### ISSUE THREAD

**Issue by tlamonthezie** [olifolkerd/tabulator#2502]
**Describe the bug**
When using a 'select' editor, all options starting with digits are not correctly selected when displaying the select dropdown list.

**Tabulator Info**
Version 4.4.3

**Suggestion**
In function processComplexListItem: replace parseFloat() by Number() to add strict numeric type checking before calling setCurrentItem. Or add option so we can configure options value type

**Comment by olifolkerd** [comment]
Please use the bug template when reporting a bug.

Bug reports MUST come with a js fiddle or code pen that demonstrates the issue or they will be closed without reply
