### ISSUE TITLE
Layout issue in bottomCalc when using frozen columns and groupBy

### ISSUE THREAD

**Issue by akki-jat** [olifolkerd/tabulator#2507]
**Describe the bug**
When I set bottomCalc when using frozen columns and groupBy, layout breaks for bottom calculation row while scrolling and when you close the group and open again.

**Tabulator Info**
- Which version of Tabulator are you using?
 -> **4.5.1**

**Working Example**
[https://jsfiddle.net/akki_jat/x76ndg4m/16/](https://jsfiddle.net/akki_jat/x76ndg4m/16/)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to [this example](https://jsfiddle.net/akki_jat/x76ndg4m/16/)
2. Scroll table horizontally or close and open group.
3. bottomCalc layout will not render correctly

**Expected behavior**
bottomCalc layout should render correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/26685162/69817066-bb7e4480-11c7-11ea-946a-c30c9a269b71.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Chrome
 - Version: 78.0.3904.108

**Comment by olifolkerd** [comment]
Hey @akki-jat 

Thanks for bringing that to my attention, and for the detailed issue, that was very helpful.

I will look to include a fix of this in one of the upcoming patch releases.

Cheers

Oli :)

**Comment by magedan** [comment]
Same for the topCalc

**Comment by olifolkerd** [comment]
This has been resolved in the 4.6 release coming out later this weekend.

Cheers

Oli :)
