### ISSUE TITLE
What all triggers a render (or rerender)

### ISSUE THREAD

**Issue by carterwe** [olifolkerd/tabulator#251]
Your documentation states this: The renderStarted callback is triggered whenever the table is about to be rendered. this can be when the table is first created, when data is loaded, when pages are changed or when a redraw is called.  I'm confused by the exact meaning of "when pages are changed".  Will a change to any of these objects automatically trigger a re-rendering of the tabulator table: Changing tabulator property such as height? Calling tabulator("setColumns"...)?  Calling tabulator("setData"...)?  Do I only need to call tabulator("redraw" ... ) when "size of the element containing the Tabulator changes".  All other changes to the table are automatically handled with a rerender?  Thanks, Ed Carter

**Comment by carterwe** [comment]
Oli, I have an answer to this to my satisfaction so I believe you can close this ticket.  Correct me if I'm wrong but what I discovered after including a renderStarted() trigger was that in addition to when redraw is called the table is automatically rendered or rerendered when "setColumns" or "setData" is specified on call to tabulator().  However the table is not rendered on Initialization.  So if you Initialize, then setColumns, then setData, you get 2 renders.  However if you include your columns object in your initialization (as in most of your examples) then you get 1 net render as desired.  Ed

**Comment by olifolkerd** [comment]
Hi Ed,

Sorry for taking so long to get back to you on this one, it has been a hectic few weeks at work.

To summarise your response, you are correct, the ***renderStarted*** started callback is triggered whenever the the rows in the table are completely redrawn.

This will happen when:

- Data is loaded into the table when ***setData*** is called
- A page is loaded through any form of pagination
- Rows are added to the table during progressive rendering
- Columns are changed by ***setColumns***
- The data is filtered
- The data is sorted
- The ***redraw*** function is called

I have updated the documentation to make this clearer.

Thanks for your question.

Oli
