### ISSUE TITLE
Issues with new layout fitDataStretch v4.5.1

### ISSUE THREAD

**Issue by britvik** [olifolkerd/tabulator#2516]
**Describe the bug**
If the total width of columns is wider than the table width in the new layout **fitDataStretch**:
1. JS error occurs `ReferenceError: column is not defined`
2. Last column is stretched instead of fitted to data (might be caused by the error above)

**Tabulator Info**
v4.5.1

**Working Example**
https://codepen.io/britvia/pen/abzOwKJ

**Other Info**
If the total width of columns is narrower than the table width, the new layout works nicely :)

**Comment by olifolkerd** [comment]
Hey @britvik 

Thanks for the info, i have pushed a fix for this to master and will include it in the 4.5.2 patch release.

Cheers

Oli :)
