### ISSUE TITLE
[4.5.1] release  notes - request for clarification

### ISSUE THREAD

**Issue by hrstoyanov** [olifolkerd/tabulator#2517]
**Website Page**
http://www.tabulator.info/docs/4.5/release

**Describe the issue**
This release note:
```
Title Formatter

the titleFormatter functions now accept the onRendered callback function as thier fourth argument. 
```

Can you please provide a code example?

**Comment by olifolkerd** [comment]
Hey @hrstoyanov 

No need, the existing [Formatter Documentation](http://tabulator.info/docs/4.5/format#format-custom) already does it.

The ***onRendered*** function has been available in formatters for a long time, it was just that the ***titleFormatter*** functionality wasnt passing in the onRendered function

I hope that clears things up.

Cheers

Oli :)

The
