### ISSUE TITLE
configurable redraw delay for realtime header filters

### ISSUE THREAD

**Issue by jjech** [olifolkerd/tabulator#2522]
We are using tabulator with AJAX requests (column header filters) to work with large sets of data. The default redraw time as described in [Header Filtering: Realtime Filters](http://tabulator.info/docs/4.0/filter#header) is 300ms. The problem is, with our large data sets the filter requests take longer than 300ms to complete, and at the same time many of our users cannot finish typing their filter into the column header in only 300ms. These two factors in combination result in a "choppy" user experience as the UI is constantly updating while the user is still typing.

**Describe the solution you'd like**
Make the redraw delay / debounce time configurable to a specified value in ms, with a default value of 300. For instance, add an optional headerFilterDelay config param (default: 300) to Tabulator.

**Describe alternatives you've considered**
After reviewing the tabulator documentation, I'm not yet aware of a current solution to this problem. We could likely modify our local tabulator source to change the filter redraw delay from 300ms to the ideal value for our application, but a better solution for the community would be to enhance tabulator so that the header filter redraw delay is a configurable option, with a default value of 300ms.

**Comment by jjech** [comment]
Created PR https://github.com/olifolkerd/tabulator/pull/2529

**Comment by olifolkerd** [comment]
Great idea @jjech 

I will review your PR over the festive break

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @jjech 

Your PR has been merged in and will be included in the 4.6 release in a few weeks.

Cheers

Oli :)
