### ISSUE TITLE
Tabulator modifies original data array with undefined values and empty objects

### ISSUE THREAD

**Issue by britvik** [olifolkerd/tabulator#2524]
**Describe the bug**
Tabulator modifies original data array if a row does not have field/object that is referenced via 'field' in column definition. It creates undefined fields and objects with undefined fields. See codepen example.

**Tabulator Info**
- 4.5.1

**Working Example**
https://codepen.io/britvia/pen/ExaKYqG

**Expected behavior**
I would expect tabulator to NOT modify my data unless I use mutators.

**Comment by lorpmtp** [comment]
I agree,

When column setting property 'field' is set and the intial data property is null, the data returned by events return a wrong formatted object (instead of being set to null, it returns an object with the property.

Column Definition : 
`  
{
        field: 'field1.subField1',
        title: 'field1',
        headerFilter: true
}
`

Initial Object
`
{
        field0: 'something',
        field1: null,
        field2: 'something else'
}
`

Retreived Object
`
{
        field0: 'something',
        field1: { 
                       subField: null
                   },
        field2: 'something else'
}
`

**Comment by olifolkerd** [comment]
I will look into this further over the next couple of weeks, this is definitly a bug.

@lorpmtp proposed fix does fix this issue but unfortunatly it breaks other parts of the system.

please folllow the PR for more info.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @britvik 

I have pushed a fix for this to the 4.6 branch, which will be released later this weekend.

Cheers

Oli :)

**Comment by britvik** [comment]
Heya @olifolkerd thanks for the new release :).

I tested this issue in new version at https://codepen.io/britvia/pen/ExaKYqG and it seems the nested objects don't get created anymore. But the fields still do.

Original data inserted into table:
`{}`
Result data in v4.5.1:
`{ name: undefined, brother: { name: undefined }, favourite: { movie: { name: undefined } } }`
Result data in v4.6.1:
`{ name: undefined }`
Expected data:
`{}`
