### ISSUE TITLE
Editor is not working with custom formatters

### ISSUE THREAD

**Issue by Roman991** [olifolkerd/tabulator#2528]
**Describe the bug**
When using a *custom* formatter the ```{editor:true}``` is ignored.

**Tabulator Info**
4.5

**Working Example**
https://jsfiddle.net/3ruLzb18/1/

**EDIT

srr about that, I forgot quotes and it was failing silently

**Comment by olifolkerd** [comment]
It will be as there is no editor to match the formatter.

You need to set the specific editor you want to use as Tabulator has no way
to know

**Comment by Roman991** [comment]
You got it
```{editor: 'input'}```
solved the problem!
Thank you
