### ISSUE TITLE
doc: Wrong default values for progressiveRender and progressiveRenderSize

### ISSUE THREAD

**Issue by chdh** [olifolkerd/tabulator#253]
The documentation states that the default value for `progressiveRender` is `true` and `progressiveRenderSize` is 200. But in the source code, the default value for `progressiveRender` is `false` and `progressiveRenderSize` is 20.

**Comment by olifolkerd** [comment]
Good point, 

I will update the documentation this weekend.

Thanks for the spot!

Cheers

Oli

**Comment by olifolkerd** [comment]
The documentation has been updated to include the correct values.

Thanks

Oli
