### ISSUE TITLE
Cell navigation (cell.nav)(apparently) doesn't work properly

### ISSUE THREAD

**Issue by ShinobiWPS** [olifolkerd/tabulator#2533]
**Describe the bug**
when i use cell.nav().down() i got undefined 

**Tabulator Info**
- Which version of Tabulator are you using?
"tabulator-tables": "^4.4.3"

**Working Example**
Using a custom webpack project which i can't upload to any public online service,since custom-webpack projects are not supported yet

From a OS shell(bash,CMD,powershell) with Yarn installed system-wide:
```
yarn (to install deps)
yarn start (or webpack-dev-server --open) 
```
https://gofile.io/?c=LZUF5G
or
https://send.firefox.com/download/4c86b8e9b9ff107a/#S161GlDFRYSohkWdTKY2Fw

**To Reproduce**
A step by step guide to recreate the issue 
1. open up the inspector
2. edit a Date cell and press enter
3. with the breakpoints set ON you will see the function "addRowAutoFill" triggered
4. i can't use a.nav().down() : it returns undefined

**Expected behavior**
in that snippet i want to navigate programmatically to go "down"  1 cell and get the new cell returned then make another move to "left" with the same behaviour since I need to check if another cell is empty when i fire **cellEdited** for that column.

**Screenshots**
![Screenshot 2019-12-12 at 5 47 06 PM](https://user-images.githubusercontent.com/11430881/70731667-566a3900-1d07-11ea-8667-727a6929c79c.png)

**Desktop (please complete the following information):**
 - OS: mac os
 - Browser chrome 78.0.3904.108

**Comment by ShinobiWPS** [comment]
This functions works only on editable:true columns and with an editor key..

**Comment by sahilsetanw** [comment]
when i use cell.nav().down(), next cell automatically calls the cellEdited function.

Is there any way to prevent it?

**Comment by olifolkerd** [comment]
@sahilsetanw That is because you are finishing the edit of the currently focused cell

**Comment by sahilsetanw** [comment]
> @sahilsetanw That is because you are finishing the edit of the currently focused cell

Is there any way to prevent it?
