### ISSUE TITLE
feat: Distinguish between editable and noneditable cells

### ISSUE THREAD

**Issue by britvik** [olifolkerd/tabulator#2535]
**Is your feature request related to a problem? Please describe.**
If a table has editable and non-editable cells, you don't know what's editable unless you start clicking on every cell.

**Describe the solution you'd like**
Editable cell could have a css class, so it can by styled differently.

**Describe alternatives you've considered**
I could make custom formatters that would add css to the editable cell. But the problem is with optional editable cells (editable only when certain conditions are met), because I believe the conditions are checked on a cell click.

**Comment by aklaver** [comment]
Can't you use editorParams.elementAttributes to set an attribute:
http://tabulator.info/docs/4.5/edit

For optional edit set the attribute inside the edit check function?

**Comment by britvik** [comment]
But that would only affect the cell when it's being edited. I want to see what cells I can edit before I actually start editing them. (unless I'm missing something :)

**Comment by aklaver** [comment]
Change in plans. Using rowFormatter(http://tabulator.info/docs/4.5/format#row):
```
rowFormatter:function(row){
        //row - row component
       var cells = row.getCells();
       cells.forEach(function(cell){
            if (cell.getColumn().getDefinition().editor){
                cell.getElement().style.backgroundColor = "red";
        }
    });
    },```

**Comment by britvik** [comment]
Thanks aklaver, this did work. I even thought of same solution some time ago but forgot about it hehe. I also added calling 'editable' function from columnDefinition, since some cells are dynamically disabled.

```
rowFormatter: (row) => {
  row.getCells().filter(cell => {
    const colDef = cell.getColumn().getDefinition()
    return colDef.editor && (typeof colDef.editable === 'function' && colDef.editable(cell) === true) || colDef.editable === true
    })
  .forEach(cell => cell.getElement().className += ' xxx-cell-editable')
},
```

I will wait for Oli to decide if we want to close this as we have workaround or if he wants to add it to Tabulator.

**Comment by olifolkerd** [comment]
Hey @britvik 

Thanks for the suggestion, unfortunately in a lot of cases it isn't that simple, the editable function that determines if a cell can be edited is only called when a user is focused on that cell, as it could be dependent on elements outside the table, therefore there is not always a way to know in advance that the cell is editable

Im glad that you were able to come up with a solution for your usage case. But for the reasons above i wont be looking to add this into the main library.

Cheers

Oli :)
