### ISSUE TITLE
cellEdited does not trigger when going from 0 to empty

### ISSUE THREAD

**Issue by adamxi** [olifolkerd/tabulator#2539]
**Describe the bug**
I have set up a table where the user is able to type numbers into cells. These numbers are sent directly to a database where an empty value of NULL has a special meaning. The cell editor therefor has to treat values as strings so that numbers can be "removed". However, going from 0 to empty does not trigger the cellEdited event due to the following line in the tabulator js code.

```
Cell.prototype.setValueProcessData = function (value, mutate) {
	var changed = false;
	
	if (this.value != value) { // this translates to (0 != "") which becomes false and hence does not trigger the cellEdited event
```

**Tabulator Info**
- 4.4.3

**Working Example**
I feel that it is silly to NOT report a bug just because i do not have the time (during work hours) to create a JS fiddle demonstrating the issue - take it or leave it.

**Expected behavior**
Changing a cell value from 0 to empty should trigger **cellEdited**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 78.0.3904.108

**Comment by aklaver** [comment]
This like #2531 is data translation issue between different systems. The Tabulator table works with JSON/JS , where the data comes from and goes to is outside it's purview, at least in my opinion. In JS '' is 0 at least at the first level of comparison so it is not a change. I personally think that is incorrect but it is the standard. Even if you could get '' not to be 0 it is also not NULL in either JS or SQL:
```
'' == null
false

test_(postgres)# select '' is null;
 ?column? 
----------
 f
```
To me what you are looking for is a way to convert '' to null. See my responses in the issue link above for some ideas.

**Comment by adamxi** [comment]
Thanks for the clarification :) I believe you are correct @aklaver. The initial this.value is a number because the underlying json data source is a number. When i make the input into my cell that number is boxed into a string hence giving the scenario where a number is being compared to a string.

Since tabulator is not comparing the actual variable type, the code works fine for all input scenarios like 2 != "", except when the initial value is 0, then the expression translates to (false != "").

Since javascript does not have a concept of nullable ints, the proper way to fix this would be for me to format the underlying json source as strings instead of numbers.

**Comment by aklaver** [comment]
Have you looked at mutators:
http://tabulator.info/docs/4.5/mutators#mutators

jsFiddle example:
https://jsfiddle.net/aklaver/e1vujg74/39/
