### ISSUE TITLE
Type '"responsiveCollapse"' is not assignable to type 'Formatter'.

### ISSUE THREAD

**Issue by marekmiotelka** [olifolkerd/tabulator#2540]
**Version:** 4.5.2

As in the title, using TypeScript we get such an error.

**Example**
```TypeScript
this.tabulator
  .addColumn(
    {
      title: '',
      formatter: 'responsiveCollapse', // Type '"responsiveCollapse"' is not assignable to type 'Formatter'.
      width: 40,
      minWidth: 40,
      resizable: false,
      headerSort: false,
    }, 
    true, 
    'score'
  )
  .then((r: void) => {
    //
  });
```

This type should be added to the `Formatter` type in the index.d.ts file.

**Bypass**
Add `as any` after column options object:

```TypeScript
this.tabulator
  .addColumn(
    {
      title: '',
      formatter: 'responsiveCollapse', // Type '"responsiveCollapse"' is not assignable to type 'Formatter'.
      width: 40,
      minWidth: 40,
      resizable: false,
      headerSort: false,
    } as any, 
    true, 
    'score'
  )
  .then((r: void) => {
   //
  });
```

<br>
PS: Thanks for the great library!

**Comment by olifolkerd** [comment]
@Jojoshua setup the typings for Tabulator, he might be able to help you here

**Comment by Jojoshua** [comment]
@olifolkerd is responsiveCollapse a valid option for the column formatter property?

**Comment by Jojoshua** [comment]
Found it here http://tabulator.info/docs/4.5/format#format-module

I've got a pending commit to add this option https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41216

**Comment by olifolkerd** [comment]
@Jojoshua you are my hero!
