### ISSUE TITLE
Predefined validation "required" is applying before completing AJAX call.

### ISSUE THREAD

**Issue by Muralee99** [olifolkerd/tabulator#2541]
Hi Oli,

Thanks for the tabulator application, it is helping us in a great way.

<img width="532" alt="Bug_Screen" src="https://user-images.githubusercontent.com/5547028/71061405-ebe54d00-218d-11ea-9fa0-65835fcb2986.png">

Sorry unable to provide jsfiddle sample, because it is difficult to reproduce in jsfiddle.

**Problem description**:
I have configured for the name field as required.
{"editor":"input","validator":["required","maxLength:20"]}

As shown in the above image, I am entering number manually, on tab in cellEdited() function I am making an ajax call to the server and fetching the name and populating in the name field.

Before populating the name "**required**" validation is applying with **validationFailed** and focus is moving somewhere and grid is blocking.

Appreciating your suggestions to come out of this issue.

For manually entering fields, validations are working correctly.

**Comment by olifolkerd** [comment]
Hey @Muralee99 

Thanks for your kind words, it is always great to hear that Tabulator is appreciated

Im afraid without a JS Fiddle and step by step instructions on how to replicate this issue i wont be able to offer any advice, i dont quite understand from your above description what the actual issue is.

Cheers

Oli :)

**Comment by Muralee99** [comment]
Hello Oli,

Thanks for your time.

**I have given the sample code in the below jsfiddle, here the code is working fine.**
https://jsfiddle.net/c2nqgazs/

Step1: I configured the CustomerId and Customer Info as "**required**" fields, I have to enter the data mandatorily.
Step2: Entering or modifying customer id in the first column.
Step3: Fetching the customer info from the other service based on the customer id.
Step4: As expected if the customer info presents, it will be updated in the Customer Info column.
If no data presents returning the undefined, required validation is applying as expected.

I am using tabulator js along with Ember js.
I think in my project its not working correctly. I need to do more research i think.
My project behavior:

- To fetch the customer info with ajax call it will take some time.
- Before fetching the data required validation is applying.
- Because of this, though customer info data is fetching from the service still validation applying on the cell with red border color.

Thanks again for your response. more power to you.

**Comment by olifolkerd** [comment]
Hey @Muralee99 

The validator is working exactly as expected on your example table. the ***cellEdited*** function is only triggered when an edit has successfully passed validation.

The issue in your example is in the ***getSuccessOutput*** function where you are trying to return a value before it is set.

Ajax calls are asynchronous, so what is happening in that function is that it is triggering the ajax request, then immediately returning the undefined ***output*** variable before the ajax response is received.

Cheers

Oli :)
