### ISSUE TITLE
paginationSizeSelector

### ISSUE THREAD

**Issue by Pacamval** [olifolkerd/tabulator#2542]
Is there any way that we can have all option in pagination so that all rows of table can be displayed if the user selects all option "ALL" as an option so all the Rows in the table are showing?

example paginationSizeSelector: [10, 20, **ALL**]

**Comment by olifolkerd** [comment]
@Pacamval  im afraid that currently isnt an option, but i think that is a great idea and would be happy to add it to the roadmap.

Cheers

Oli :)

**Comment by mallenswe** [comment]
I've also had an ask to use this feature in my project. I've tried to Force an 'All' or data.length number into the dropdown but the functionality behind selecting that option isn't there.

**Comment by olifolkerd** [comment]
Hey All,

You will be happy to hear i have pushed a commit for this feature to the 4.7 branch that will be released at some point in May.

You will be able to achieve it by passing a boolean of ***true*** into the ***paginationSizeSelector*** array

```js
var table = new Tabulator("#example-table", {
    pagination:"local",
    paginationSize:10,
    paginationSizeSelector:[10, 25, 50, 100, true], //select list with an "all" option at the end of the list
});
```

Cheers

Oli :)
