### ISSUE TITLE
frozen columns shaking during  horizontal fast scrolling by touch event

### ISSUE THREAD

**Issue by zhoulijuanmiao** [olifolkerd/tabulator#2544]
**Describe the bug**
frozen columns shaking during  horizontal fast scrolling by touch event

**Tabulator Info**
- 4.5.2

**Working Example**
http://tabulator.info/examples/4.5#frozen-col

**Expected behavior**
frozen columns not shaking when fast scrolling by touch event

**Comment by olifolkerd** [comment]
Hey @zhoulijuanmiao 

Im afraid i am unable to replicate your issue on chrome, please fill in ALL the fields on the issue template as they prompt us with all the information we need to get to the bottom of your problem, (in this case browser for example)

Cheers

Oli :)

**Comment by arditnurcaj** [comment]
Hey @olifolkerd,

First thanks for this awesome library, it really helped me. 
I'm seeing the same issue on other browsers(Safari 13.0.2 / Mozilla), try opening the same working example provided in the issue on other browsers to replicate.

Thanks,
Ardit.

**Comment by arditnurcaj** [comment]
Hey @olifolkerd,

Thank you for this awesome library, it really helped me :). 

I'm seeing the same issue on other browsers(Safari 13.0.2 / Mozilla), try opening the same working example provided in the issue on other browsers to replicate.

Thanks,
Ardit.

**Comment by konsalex** [comment]
I am having the same issue in Brave browser @olifolkerd

**Comment by BaskarR96** [comment]
have you got any solution on this issue?
