### ISSUE TITLE
IE11 and Edge editable data

### ISSUE THREAD

**Issue by jmccarthyGitHub** [olifolkerd/tabulator#2546]
**Describe the bug**
I am seeing an issue in both IE11 and Edge in tabulators with editable data: http://tabulator.info/examples/4.5#editable

If I change any value in any cell, regardless of editor type, and I click Enter to accept the change, I cannot tab into the next cell. The focus on the table is lost.

For example, in the editable table from the link above.
1. Click into the Name cell Oil Bob
2. Tab into Location
3. Arrow down to highlight United Kingdom
4. Press Enter to select United Kingdom
5. Press the Tab button.
6. Observe tab location: It's no longer in the table and tabbing continues from outside the table. Focus on the table is lost.

This happens on any cell after Enter is pressed.

I expect to be able to continue tabbing through cells after pressing Enter on any editable cell.

Any thoughts?

Tabulator v4.5.1
Browsers: IE 11 and Microsoft Edge 42.17134.1.0
Windows 10

**Working Example**
http://tabulator.info/examples/4.5#editable

**Comment by olifolkerd** [comment]
Hey @jmccarthyGitHub 

This is due to limitations in the way these browsers handle focus, it should be less of a problem in the new year when edge moves over to using webpack.

If you use tab to move between cells rather than enter it works just fine.

Cheers

Oli :)
