### ISSUE TITLE
Display a single record on multiple rows

### ISSUE THREAD

**Issue by boumboum** [olifolkerd/tabulator#2548]
Is it possible to display a single record on two (or more) rows?
I didn't see it in the documentation. 
The responsiveLayout:"collapse" is not an option in my case
The table definition would something like this:
```
var table = new Tabulator("#example-table", {
    columns:[
    {title:"Name", field:"name"},
    {title:"Title", field:"title"},
    {title:"Date", field:"created_on", align:"center", sorter:"date"},
    {title:"Valid to", field:"valid_to", align:"center", sorter:"date"},
    {title:"Description", field:"description",formatter:"textarea"},
    ],
});
```
I would like to display the description field under the others having the whole table width with text wrap.

What I would like to achieve is something like this:
**Name | Title  | Date |  Valide to**      
**Description**                                                             
Bob   |   This is a title | 12-12-2019 | 31-12-2019  
This a a long description                                        
on several lines                                                       

Is it possible?

**Comment by olifolkerd** [comment]
Hey @boumboum 

Thanks for getting in  touch, please ask future questions on StackOverflow, this issues list is reserved for Bug Reports and Feature Requests

In answer to your question, you should look at using a [Row Formatter](http://tabulator.info/docs/4.5/format#row) to add a div containing the description text after the column cells, and then simply dont define it in the column definition.

I hope that helps,

Cheers,

Oli :)
