### ISSUE TITLE
Add a new way to define values as an array with objects in Autocomplete editor as well as in Select editor

### ISSUE THREAD

**Issue by aalopatin** [olifolkerd/tabulator#2552]
**Is your feature request related to a problem? Please describe.**
I found that I can't define values in Autocomplete editor as an array with objects. When I have to define values with different values and label, I should use an object likes this:
```
{
"1": "label1",
"2": "label2",
"3": "label3",
}
```

But in this way, I lose the value that equals number. It becomes to equal a String.

**Describe the solution you'd like**
I suggest doing a way to define values as an array with objects. As next:

```
[
{label:"label1", value: 1},
{label:"label2", value: 2},
{label:"label3", value: 3}
]
```

In this way, I can define value as Number.

**Comment by fingers10** [comment]
It will also be better if we are allowed to display the `Value` in the cell and get the `Key` from the cell when reading the cell data.

For example, with Tabulator latest version autocomplete editor, If we supply the following values,
```js
values:{
        "steve":"Steve Boberson"
    }
``` 

While searching, the list gets displayed with **Steve Boberson** and when we select the option, **steve** will be displayed in the cell. Instead it would be better if we display **Steve Boberson** in the cell after selecting and get **steve** while reading the data from cell.

This will be helpful in situations when the user has `values` object like shown below:
```js
values:{
        "primary-key-in-db":"Steve Boberson"
    }
``` 
So upon searching and selecting **Steve Boberson** will be displayed in cell and when reading we get **primary-key-in-db**

**Comment by olifolkerd** [comment]
I will look into this as part of the 4.7 release

Cheers

Oli :)

**Comment by olifolkerd** [comment]
This functionality has now been pushed to the 4.7 branch which i am hoping to release tomorrow

Cheers

Oli :)
