### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by zotalegre** [olifolkerd/tabulator#2556]
**Website Page**
[http://tabulator.info/docs/4.5/quickstart#setup](http://tabulator.info/docs/4.5/quickstart#setup)

**Describe the issue**
We read: 

> Example Setup
This section outlines the process of setting up for your first table in four easy steps.
A demo of basic table setup on a bolierplate HTML page can be found here.

But the linked page: [http://tabulator.info/basic/4.5](http://tabulator.info/basic/4.4) gives a Whoops!
Also page 4.4 and 4.3. The boilerplate is found only at http://tabulator.info/basic/4.2
Thanks

**Comment by olifolkerd** [comment]
Hey @zotalegre 

Thanks for the headsup, This has now been fixed.

Cheers

Oli :)
