### ISSUE TITLE
Buggy example at QuickStart

### ISSUE THREAD

**Issue by zotalegre** [olifolkerd/tabulator#2557]
**Website Page**
http://tabulator.info/docs/4.5/quickstart

**The issue**
We read

> 4 SMILE - You are all setup and ready to go!

But clicking over the example table that follows shows an alert with

> Row [object Object] Clicked!!!!

instead of the nice

> Row 3 Clicked!!!! 

witch I got doing copy + paste + running the code yesterday.
Besides, seems that the line  

> alert("Row " + row.getData().id + " Clicked!!!!");

should be something like 

> alert("Id " + row.getData().id + " Clicked!!!!");

because the alert outputs the id, not if it was a row/col index... (OK, on the example they are the same, but its useful to know)
And thanks for the nice documentation

**Comment by olifolkerd** [comment]
Hey @zotalegre 

Thanks for the headsup, the example code i the demo was fine, but the actual code that made the table run was using an old rowClick binding from version 3.5.

This has now been fixed.

Cheers

Oli :)
