### ISSUE TITLE
deselected row with edit cell

### ISSUE THREAD

**Issue by lalwende00** [olifolkerd/tabulator#256]
Hello ,
I have a little problem with deselected row.
i use  edited cell for all column except the id column .
(http://img4.hostingpics.net/pics/742921selectedrowtabulator.png)
when i click on the id column the row is selected but i would like when i click on another cell (which is editable) column this one become selected .... 
i hope my question is clear :) 
is it possible to select a row if it's an editable column ?

Thank you very much.
Have a good day !
Sarah

**Comment by olifolkerd** [comment]
Hi Sarah,

Editable cells intentionally block click events from passing through to the cell and row functions, this is specifically designed to prevent accidental selection of a row while editing.

For example the star rating requires a user to click on the cell to edit then click on a start to set the value,  this would select the row with the first click and and then deselect the row with the second click which would be a very bad user experience.

Is there a particular reason you want this behaviour, are you tying to show that the line is currently being edited or do you need it for another reason, maybe i can suggest an alternative>

Cheers

Oli

**Comment by lalwende00** [comment]
Thank you for your reply :)
yes i would like to show which line is currently edited.
Thank you .

**Comment by olifolkerd** [comment]
Great News!

I have just released version 1.12 of Tabulator! now when any cell is being edited, its parent row is given the class of ***tabulator-row-editing*** so you can apply any custom styling you want to a row that is being edited!

Let me know if that helps

Cheers

Oli
