### ISSUE TITLE
dynamic redraw for header filters

### ISSUE THREAD

**Issue by jjech** [olifolkerd/tabulator#2560]
In tabulator 4.5.3 and prior, the header filter delay to redraw the table after a user has started typing into a header filter field was 300ms. (Refer to feature request #2522 for additional details). PR #2529 adds headerFilterLiveFilterDelay to allow tabulator consumers to configure this value to a longer or shorter time according to their use case.

Another idea, which may be preferable for most use cases, would be to add something like headerFilterDynamicFilterDelay, which configures tabulator to redraw the table dynamically — after the user has _finished_ typing into the header filter field.

One possible implementation for this feature would be to add a new config param 'headerFilterDynamicFilterDelay,' false by default, which preserves the existing tabulator behavior (redraw the table 'headerFilterLiveFilterDelay' ms after the user _starts_ typing into a header filter field). If headerFilterDynamicFilterDelay is set to true, then tabulator will redraw the table 'headerFilterLiveFilterDelay' ms after the user _finishes_ typing into a header filter field.

Most of the work for this feature would be implementing a mechanism for tabulator to determine when a user has finished typing into a header filter field. One possibility for that would be to add a polling loop with a timeout since last key press.

**Comment by olifolkerd** [comment]
Im afraid i dont quite follow you there.

There is no way to know when a user is "finished" typing as such. at the moment the two trigger methods are:

- the editor triggers the success function (it is up to the editor how it chooses this, for inputs it can be when the element uses focus, for select lists it can be when the user selects a value from the list)

- the live filter where it check for keydown events on the editors input element and triggers after the specified delay from the last keystroke

How does your proposed method differ from these and what is the usage case for it?

Cheers

Oli :)

**Comment by jjech** [comment]
For some reason (perhaps just from being new to tabulator's source code) I mistakenly thought that tabulator's live filter delay triggers after the specified delay from the _first_ keydown event, not the _last_ keydown event. Tabulator is already behaving in the manner that I'm requesting here, per Oli's second bullet point as he describes in his comment above.

Closing as a duplicate of #2522
