### ISSUE TITLE
bottomCalc sum is duplicated for every print/cancel event

### ISSUE THREAD

**Issue by akohring** [olifolkerd/tabulator#2561]
**Describe the bug**
Print a table that contains a column with a bottomCalc:"sum" property.  Cancel the print, then reprint.  The subsequent prints will contain duplicated footer rows for the calculated sums.

**Tabulator Info**
4.5.3

**Working Example**
https://jsfiddle.net/r0konvzb

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Create a Tabulator table with a column containing a bottomCalc:"sum" property.
2. Call table.print(false, true)
3. Click cancel on the print dialog
4. Call table.print(false, true) again

**Expected behavior**
The calculated footer row is only displayed once on the printed table.

**Desktop (please complete the following information):**
 - OS: Xubuntu
 - Browser Google Chrome
 - Version 79.0.3945.88

**Comment by olifolkerd** [comment]
Hey @akohring 

Thanks for the headsup

I have pushed a fix for this to the 4.6 branch which should be released in a few weeks.

Cheers

Oli :)
