### ISSUE TITLE
Tabulator Not available in CDNJS from Version 4.5

### ISSUE THREAD

**Issue by fingers10** [olifolkerd/tabulator#2562]
Dear Team,

From the **V4.5**, Tabulator is not available in CDNJS. **V4.4.3** is the last one that I can find in CDNJS. [Here is the CDNJS Tabulator link](https://cdnjs.com/libraries/tabulator). I'm sorry to raise this as bug. But couldn't find any other way to communicate this to the Tabulator team.

Thanks,
Abdul Rahman

**Comment by olifolkerd** [comment]
Tabulator stopped supporting cdnjs from version 4. They are too slow to update on a new release.

If you have a look at the [install documentation](
http://tabulator.info/docs/4.5/install#setup) you can see we now use unpkg.com

https://unpkg.com/tabulator-tables@4.5.3/dist/css/tabulator.min.css

https://unpkg.com/tabulator-tables@4.5.3/dist/js/tabulator.min.js

Cheers

Oli :)
