### ISSUE TITLE
Movable rows

### ISSUE THREAD

**Issue by Saranyasambath** [olifolkerd/tabulator#2563]
Hi,
    I have issues on while moving row in a large number of rows,auto scroll  is not working.
 
    I am using version tabulator 4.2.

**Comment by olifolkerd** [comment]
Hey @Saranyasambath 

If you are having issues, please read the [Bug Reporting Guide](http://tabulator.info/community#bug) and use the issue template provided as it prompts for all the information we need to help.

You also MUST provide a working JS Fiddle or CodePen  with guide to reproduce the issue so we can understand how your table is configured.

Cheers

Oli :)
