### ISSUE TITLE
printAsHtml does not apply the custom group header function (groupHeader)

### ISSUE THREAD

**Issue by akohring** [olifolkerd/tabulator#2564]
**Describe the bug**
Custom group header formatting specified by a groupHeader function is not applied during printing.

**Tabulator Info**
Tabulator v4.5.3

**Working Example**
https://jsfiddle.net/x1f75t83/1/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Run the above jsfiddle
2. Click on the print button

**Expected behavior**
The custom header formatting should be in the print window.

**Desktop (please complete the following information):**
- OS: Xubuntu
- Browser Google Chrome
- Version 79.0.3945.88

**Comment by olifolkerd** [comment]
Hey @akohring 

Thanks for getting in touch,

I wouldnt consider this a bug, more of a missing feature. I will reveiw your pull request and get back to you shortly.

Cheers

Oli :)

**Comment by akohring** [comment]
Thanks for the feedback Oli.  I have pushed the suggested fix.  Is it possible to have this fix included in the 4.6 release?

**Comment by olifolkerd** [comment]
Hey @akohring 

Yeah i would certainly be happy to include it in the 4.6 release, when it is ready to go.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @akohring 

As part of the 4.6 build i had a rethink about how to make the export module more customisable and reusable in a broader sense across Tabulator.

As a result of this rethink u have restructure the module to allow specific callbacks for each export task, print, clipboard and html *(download coming soon)*

I have just pushed a commit to the 4.7 branch to add the new ***groupHeaderPrint*** option along with ***groupHeaderClipboard*** and ***groupHeaderHtmlOutput*** to allow greater customisation of each output.

The 4.7 branch will be released at some point in may.

Cheers

Oli :)
