### ISSUE TITLE
Pleas Re-Review #2453 Odd Behavior when Group By Column is ommited with totals

### ISSUE THREAD

**Issue by YendorMc** [olifolkerd/tabulator#2566]
Hi Oli,  Happy New Year! :)

I reviewed your response on #2453 but it seems I didn't make clear what the problem I was facing.  

When  you get a chance, please try the fiddle below again and click on the grouping to collapse. I've added a BMP to illustrate  What's happening is that the totals are shifting to the right making a misalignment with the first column.  I'm seeing this behavior in other examples and can provided more details if needed.  Please see if you see this as an issue.

**Describe the bug**
Describe the bug
totals are skewed to the right by one row, phantom column shows up at right when collapse is clicked.
totals align themselves if make first column wider.
May be issue with frozen column.

Tabulator Info
-Version: 4.5 (CDN)

Post a copy of your construct object if possible so we can see how your table is setup
var table = new Tabulator("#classifysum", { data:data, //load row data from array layout: "fitData", //fitColumns, clipboard:true, //enable clipboard functionality tooltips:true, //show tool tips on cells resizableRows:true, //allow row order to be changed placeholder:"Loading...", //display message to user on empty table groupBy: "DIVISION", columnCalcs:"both", groupClosedShowCalcs:true, groupToggleElement:"header", clipboardCopyConfig:{columnCalcs:true}, groupHeader:function(value, count, data, group){ //value - the value all members of this group share //count - the number of rows in this group //data - an array of all the row data objects in this group //group - the group component for the group if (count == 1){ return value + "<span style='color: gray; margin-left:10px;'>(" + count + ")</span>"; } else { return value + "<span style='color: gray; margin-left:10px;'>(" + count + ")</span>"; } }, columns: cols });

**Tabulator Info**
- Which version of Tabulator are you using?  4.5

**Working Example**
https://jsfiddle.net/YendorMc/t02wvcy4/7/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:

1. Go to 'jsfiddle.'
2. Click first group row to collapse group
3. Observe behavior: 1st column is shifted over to the right.

**Expected behavior**
Columns should align when collapsed.

**Screenshots**
If applicable, add screenshots to help
![TabulatorGroupingIssue](https://user-images.githubusercontent.com/10876357/71850483-6412a480-30a2-11ea-9f98-2af4752c9715.png)
 explain your problem.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [e.g. Chrome]
 - Version [e.g. ]

**Smartphone (please complete the following information):**
 - Version [e.g. 79.0]

**Additional context**

**Comment by olifolkerd** [comment]
Hey @YendorMc 

Happy New Year to you too!

Thankyou for resubmitting with a clearer description, that totally makes sense to me now, and i can see there is a bug there.

I will have a look into that in the next few weeks.

Could i ask that if you have a bug in future, you try and fill in the Browser section of the issue template, as it helps narrow down the testing and makes it easier to find the bug.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @YendorMc 

You will be happy to hear that this has been resolved on the 4.6 branch which will be released later this weekend.

Cheers

Oli :)
