### ISSUE TITLE
Tabulator with JSON

### ISSUE THREAD

**Issue by benkim-saama** [olifolkerd/tabulator#2569]
Our backend developer is attempting to optimize the JSON return.  If data does not exist for a specific sub-JSON package (array), he was not including it.  This caused Tabulator to copy values from the previous row which did have data into the new rows.  In the interim, he agreed to revert his change and pass the "segment" with null values for each field.  Tabulator was happy afterward.  Below is a sample JSON extract.  Report type A has the full message including the AdministrativeSegment.  The Group B report type does not have the AdministrativeSegment which was causing the duplication of data in the tabulator row column values for the "missing" JSON fields for this specific record.  We have a workaround for now but it would be nice if Tabulator could still show the row and ignore the fact that fields may not exist under certain circumstances.

Thanks for reviewing!

Ben
	
list	
0	
headerId	5541765
reportType	"A"
reportTypeInfo	
reportType	"A"
description	"Group A (Incident/Arrest)"
displayOrder	null
createdBy	null
createdOn	null
updatedBy	null
updatedOn	null
reportActionCode	"R"
versionNumber	2
incidentNumber	"040711124501"
submissionPeriod	"201912"
zeroReportPeriod	null
validationStatus	"R"
inputFile	"//DOWNLOADS/TEST_AGENCY/NM0260100201912701.zip"
fbiStatus	null
submittedToFbi	null
outputFile	"//UPLOADS/FBI/NM0260100201912977.zip"
administrativeSegment	
adminId	5323852
clearedExceptionally	null
clearanceInfo	null
incidentDate	1089475200000
reportDateIndicator	null
clearedDate	null
cargoTheft	null
createdBy	1
createdOn	1575920237000
updatedBy	null
updatedOn	null
sourceId	"IBR_ADMINISTRATIVE_SEGMENTS|5323852"
createdBy	1
createdOn	1575913847000
updatedBy	null
updatedOn	null
sourceId	"IBR_REPORT_HEADERS|5541765"
1	
headerId	5547961
reportType	"B"
reportTypeInfo	
reportType	"B"
description	"Group B (Arrest Only)"
displayOrder	null
createdBy	null
createdOn	null
updatedBy	null
updatedOn	null
reportActionCode	"R"
versionNumber	6
incidentNumber	"040803093201"
submissionPeriod	"201912"
zeroReportPeriod	null
validationStatus	"R"
inputFile	"//DOWNLOADS/TEST_AGENCY/NM0260100201912832.zip"
fbiStatus	null
submittedToFbi	null
outputFile	"//UPLOADS/FBI/NM0260100201912674.zip"
createdBy	1
createdOn	1575913847000
updatedBy	null
updatedOn	null
sourceId	"IBR_REPORT_HEADERS|5547961"

**Comment by olifolkerd** [comment]
Hey @benkim-saama 

Thanks for getting in touch.

Could i ask that if you are reporting a bug you read the [Bug Reporting Guide](http://tabulator.info/community#bug) and use the issue template provided as it will prompt you to provide all the information we need to help you out.

In this case i suggest that you create a reduced test case as Tabulator has absolutely no issue with rows having different sets of properties in each row and certainly wont copy the values from one row over to another, the row objects are kept totally isolated from one another so this couldn't happen internally which suggests it is related to the data not being correctly formatted as it is fed into the table.

Without knowing how your table is setup, it is not possible for me to offer you any advice on how to fix the issue, but i would recommend that in the mean time you read the above guide as it will give you a starting point to debug your code.

Cheers

Oli :)
