### ISSUE TITLE
ajaxResponse function and setting dynamic columns

### ISSUE THREAD

**Issue by lac616** [olifolkerd/tabulator#257]
Hello,

This is one of the best grid controls that I have worked with to-date. Thank you!

I am using ajax to retrieve my column list as well as my grid data, based on user selections. I am trying to invoke the ajaxResponse function to set my columns for the grid before returning data. I tried the below but it doesn't work - just get a blank screen. I assume it's happening because we are within the scope of the ajax success function. Is it possible to dynamically set the columns before returning the grid data?

        ajaxResponse: function (url, params, response) {

            var gridResponse = response.d;

            var cols = $.parseJSON(JSON.stringify(gridResponse.columns, replacer));
            var gridData = $.parseJSON(JSON.stringify(gridResponse.gridData, replacer));
           
            this.columns = cols;
            //console.log(this.columns);

            return gridData;
        }

**Comment by olifolkerd** [comment]
Hey,

Thanks for the kind words, its always great to hear people are enjoying using Tabulator!

The issue you are having is that you can't update the internal properties of Tabulator directly, setting the columns takes a great deal of internal processing, and the system has to know when to start this, so you should replace the line:
```js
this.columns = cols;
```
With the following line (replace the example-table selector with your own):
```js
$("#example-table").tabulator("setColumns", cols);
```
That should work for you.

Cheers

Oli

**Comment by lac616** [comment]
This worked, Thank you!!

**Comment by mark-zarandi** [comment]
I got "$ is not defined".
