### ISSUE TITLE
Tabulator Filters

### ISSUE THREAD

**Issue by benkim-saama** [olifolkerd/tabulator#2570]
For completeness, it would be nice if Tabulator supported a Starts With and an Ends With equality comparators for the filters (much like it supports the LIKE operator).  I know reg-ex would do the trick but including a couple of simple operators would make life a bit easier setting up screens for end-users who have no clue what RegEx even stands for.

Ben

**Comment by olifolkerd** [comment]
Hey @benkim-saama 

Thanks for the suggestion, i think that is a great ideal, i will look at adding it to the roadmap.

If you would like to contribute this as a Pull Request, i would be happy to accept it.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @benkim-saama 

you will be happy to hear i have just pushed an update to the 4.7 branch with these features in. This branch should be released at some point in may.

You will then be able to filter as such:
```js
table.setFilter("name", "starts", "ste");
table.setFilter("name", "ends", "son");
```

Cheers

Oli :)
