### ISSUE TITLE
table.getHeaderFilterValue(columnName)

### ISSUE THREAD

**Issue by jjech** [olifolkerd/tabulator#2571]
Tabulator has a function **table.setHeaderFilterValue(columnName, value)** which is used to change the value in the specified column's header filter and trigger a table redraw.

I've run into a few cases where it would be nice to quickly get the value of a specific column's header filter by calling something like **table.getHeaderFilterValue(columnName)**. However, it looks like tabulator doesn't currently have such a function defined.

It is currently possible get the value of a column's header filter by working with **table.getHeaderFilters()**, so table.getHeaderFilterValue(columnName) is not highly needed. But I think it's worth considering.

**Comment by olifolkerd** [comment]
Hey @jjech 

There is a ***getHeaderFilters*** function that returns an array of all current header filters, that you can then check for a specific column.

Checkout the [Managing Filters Documentation](http://tabulator.info/docs/4.5/filter#manage) for more information.

Cheers

Oli :)

**Comment by jjech** [comment]
Hi @olifolkerd

Thanks for your quick response! I've been using **getHeaderFilters** as a workaround when needed, but I thought it would be nice to add a **getHeaderFilterValue** function to go with **setHeaderFilterValue**.

Do you like the idea? If so, I will open a PR. Otherwise, I will close the issue.

**Comment by olifolkerd** [comment]
Yeah I think it would be nice.

Please open a PR on the 4.6 branch, then I can include it in the next release.

Cheers

Oli

**Comment by olifolkerd** [comment]
I have merged this in and will include it in the next release.

Thanks for the excellent contribution!

Cheers

Oli :)
