### ISSUE TITLE
Scrolling Reset with Nested Tables

### ISSUE THREAD

**Issue by AlphaTeal** [olifolkerd/tabulator#2576]
**Describe the bug**
I have a table with a set height (virtual DOM enabled) where each row has a collapsible nested table "inside" of it. The table loads with each row collapsed. If the user expands one of the rows to reveal its nested table, and that nested table has a large number of rows, and the user tries to scroll down in the table, it won't get very far before resetting the user's scroll position to the top of the table.

**Tabulator Info**
Tabulator version: 4.2.1

**Working Example**
[JSFiddle demonstrating the issue](https://jsfiddle.net/AlphaTeal/mb9dowv0/)

**To Reproduce**
1. Click the '+' on the top row to reveal the nested table.
2. Try to scroll down in the table

**Expected behavior**
The table should scroll smoothly and without interruption to the bottom of the table

**Screenshots**
A short video or GIF would be much more helpful than a screenshot, but I can't provide one at the moment. If I remember, I will add one later.

**EDIT**
Here is a GIF showing what I'm seeing. Hopefully it works.
![Scroll reset GIF](https://i.imgur.com/Oc4irt5.gif)

**Desktop (please complete the following information):**
 - OS: Debian 8
 - Browser: Firefox 68 and Chrome 79

**Smartphone (please complete the following information):**
N/A

**Additional context**
No browser console errors on Firefox, but I would occasionally get a console error in Chrome when scrolling. Like this:
![image](https://user-images.githubusercontent.com/39203296/72183886-19a06900-33bd-11ea-94a4-dafc3f9fe7d4.png)
I strongly suspect this issue has something to do with the virtual DOM.

**Comment by rrglomsk** [comment]
I encountered the same issue with a similar set up (nested tables in collapsible rows). I can turn off the virtual DOM since we're displaying a limited number of rows at one time- while that fixes the scrolling reset, it presents some other issues, so I'm hoping to see this resolved too :)

**Comment by takuy** [comment]
@AlphaTeal @rrglomsk See issue #2074 for a solution.
