### ISSUE TITLE
Download to XLSX should apply group header formatters on export

### ISSUE THREAD

**Issue by akohring** [olifolkerd/tabulator#2577]
**Describe the solution you'd like**
Custom group header formatters should be applied to exported data.

**Additional context**
Problem is demonstrated in the following JSFiddle:
https://jsfiddle.net/b1atpc08/1/

1. Click the XLSX button
2. Notice that the Name column values change from "CUSTOM FORMATTER" to the raw data values in the export.

**Comment by olifolkerd** [comment]
Hey @akohring 

The download module has been rebuilt for the 4.7 release to be based on the output of the export module. which will resolve this issue.

Version 4.7 will be released in the next couple of weeks.

Cheers

Oli :)
