### ISSUE TITLE
show sum of active page in footer

### ISSUE THREAD

**Issue by sohrabi2050** [olifolkerd/tabulator#2579]
I need to add both sum of page and sum of total. In all data-tables we can have both of them.

**What I need**

 can add footer for calculate sum of total for example, but I can't add sum of visible rows or in another words sum of current page only in same time.

I can add a footer to bottom or top of the table : topCalc & bottomCalc .

For example I can add sum of price.

As you can see in the example below , I added sum of price here.

Also I put the example here : https://jsfiddle.net/o2ycm5dp/

**The way maybe resolve this problem**
On this line : bottomCalc: "sum", , calculation function will called and we can see the sum of price column.

There is an option named Custom Calculations which I can add a function to calculate only current page values, but I can't have the calculation of total pages values.

Another solution maybe append an html element to the footer but I don't think it could be a good solution. Because I should handle all those functions related to Tabulator footer.

I think we need to add another options like *bottomCalcCurrent* which will calculate over active page value.
![GQm9z](https://user-images.githubusercontent.com/44164921/72243105-41334380-3600-11ea-8a50-794d9c538cc3.jpg)

**Footer**
I don't like to use footer element because I need to append an html always.

**Comment by olifolkerd** [comment]
Hey @sohrabi2050 

Thanks for getting in touch. At this point this would not be something i would be looking to add to the tabulator core library, but feel free to include it in your own fork.

You could manage a similar effect yourself by using a custom footer and carrying out some calculations on the data in the table

Cheers

Oli :)
