### ISSUE TITLE
Freeze Column Header to top of the page (sticky header)

### ISSUE THREAD

**Issue by xola123** [olifolkerd/tabulator#2580]
Hi folks,

is there any way to freeze the Column Headers to the top of the **page** while scrolling down?

Background info: I have a huge table with lots of data in it - action buttons, calculated columns and so on. I set paginationSize to 40, to not overload the interface. On smaller screens, the users have to scroll the page. In this case, I want the column headers to stick to the top, so that if you reach the middle of the table, you still see that column number 4 is the "Cost per Month" row (or such).

The reason for not setting height of the Table (which _would_ result in sticky header inside the table wrapper element) is that I do not want the space above the table to be unused (the space above contains, in my case, the navigation bar, subnavigation bar, Title of the page including breadcrumps, filter elements of table data, and other active action elements like a search field....). I want the user to be able to overscroll all that, so that the table fills the whole page.

If it is not possible at the moment, I'd suggest a new feature ;-)

Greetings! xola

**Comment by kellimarks** [comment]
I also need this

**Comment by olifolkerd** [comment]
Im afraid there is no way to scroll the table when pagination is enabled, the two modes are incompatible.
