### ISSUE TITLE
Download to XLSX does not export the bottom column calculation

### ISSUE THREAD

**Issue by akohring** [olifolkerd/tabulator#2584]
**Describe the bug**
Download to XLSX does not export the bottom column calculation.

**Tabulator Info**
v4.5.3

**Working Example**
https://jsfiddle.net/c8j5eL0t/

**To Reproduce**
1. Open the jsfiddle example
2. Notice the last row has an Age column calculation with value of 55
3. Click the XLSX button above the table and open the downloaded file
4. Notice the bottom calculation row is not exported

**Expected behavior**
The XLSX export data contains all of the data visible in the table

**Desktop (please complete the following information):**
- OS: Xubuntu
- Browser Google Chrome
- Version 79.0.3945.88

**Comment by olifolkerd** [comment]
Hey @akohring 

The download module has been rebuilt for the 4.7 release to be based on the output of the export module. which will resolve this issue.

Version 4.7 will be released in the next couple of weeks.

Cheers

Oli :)
