### ISSUE TITLE
Fix Typo in column visibility documentation

### ISSUE THREAD

**Issue by BillMeyerRSA** [olifolkerd/tabulator#2586]
**Website Page**
http://tabulator.info/docs/4.5/columns#visibility
**Describe the issue**

> Note: Due to CSS limitations, this option will not work correctly in the Internet Exploerer browser.

**Comment by olifolkerd** [comment]
Hey @BillMeyerRSA 

Thanks for the info, that will be fixed in this evenings site update.

Cheers

Oli :)
