### ISSUE TITLE
Change search criteria when HeaderFilter results is zero

### ISSUE THREAD

**Issue by Portur** [olifolkerd/tabulator#2588]
**The problem**
Searching for values using the headerFilter feature is either inaccurate using a "like" search or too precise using the "equal" search. Using both would be perfect. At the moment if an "equal" search returns no results, there is no option to detect 0 results and automatically research using a "like" search

**Describe the solution you'd like**
Currently we have : `headerFilterFunc: "="`
The need (proposed) : `headerFilterFunc: "<>&="` or `headerFilterFunc: "=&<>"` 

**Describe alternatives you've considered**
A custom header function does not react to the amount of results returned, only what the filter function returns

**Additional context**
Please see [Stackoverflow Question](https://stackoverflow.com/questions/59748799/change-search-criteria-when-headerfilter-results-is-zero)

---

As in the solution description above. It would be ideal to add additional rules to the headerFilter, such as `do "equal" then "like"` or `"do "like" then "equal"` to help the user search for the value in the column more effectively.

**Comment by Portur** [comment]
@olifolkerd Thanks for the answer on Stackoverflow. Changing the search criteria when resulting rows is 0 works.

However the ideal solution would be to have the dropdown filter its results based on the value in the headerFilter. Is this possible?

**Comment by olifolkerd** [comment]
Hey @Portur 

Thanks for the suggestion, however i feel that this is only really useful in a few edge cases, at which point i would prefer that users use the custom filter functions to tailor the table functionality to their unique needs.

Cheers

Oli :)
