### ISSUE TITLE
Missing CSS selector

### ISSUE THREAD

**Issue by eltomjan** [olifolkerd/tabulator#2589]
There is red cell border set like this:
```
.tabulator-row .tabulator-cell.tabulator-validation-fail { 
    border: 1px solid #dd0000;
}
```
But selector in use reported by FF & Chrome is:
.tabulator-row .tabulator-cell.**tabulator-editing**.tabulator-validation-fail

With this selector I can get red border in both FF & Chrome, change tested on simple table in tabulator_bootstrap.min.css, but it looks like all sheets have same problem.

**Comment by olifolkerd** [comment]
That extra selector shouldn't be needed.

All that denotes is that the cell has the class of 'tabulator-editing' and 'tabulator-validation-fail'.

The order of the class definitions in the CSS means that the validation fail takes precedence
