### ISSUE TITLE
Tree toggle button is duplicated on update row

### ISSUE THREAD

**Issue by waelghazie** [olifolkerd/tabulator#2590]
Hi, 
I'm using tabulator as a tree and adding data dynamically (lazy loading) and I having a problem when updating a row; the collapse icon is duplicated in place. I'm using row.update function to update row under the dataTreeRowExpanded callback. What is wrong/missing with my setup?

**Tabulator Info**
- Version: 4.5

**Working Example**
https://jsfiddle.net/waelghazie/jntpu17w/2/

**To Reproduce**
A step by step guide to recreate the issue in JS Fiddle:
1. Go to first node and try to expand it
2. Click on third node you will notice it's normal

**Expected behavior**
tree collapse icon should look normal after row update, like the third node in the fiddle

**Screenshots**
![image](https://user-images.githubusercontent.com/46787397/72441850-0d008400-37b4-11ea-8bb0-a359de874417.png)

**Desktop:**
 - OS: Win 10 x64
 - Browser chrome 79, firefox 71

Thank you for your efforts

**Comment by olifolkerd** [comment]
This has been resolved on the 4.6 branch which will be released in a few weeks.

Cheers

Oli :)
