### ISSUE TITLE
Average on Column Calc Has BUG

### ISSUE THREAD

**Issue by rajibulhuda** [olifolkerd/tabulator#2591]
Dear @olifolkerd ,
![Screenshot from 2020-01-15 23-27-48](https://user-images.githubusercontent.com/59895817/72456841-a600c080-37ef-11ea-8a27-3c0ee4003c20.png)
Please check this fiddle:

https://jsfiddle.net/RajibulHuda/6pvqnuok/16/
When using column definition like below:
{title:"Order Qty", field:"OrderQty", headerFilter:"input", bottomCalc:"avg" , bottomCalcParams:{precision:0}, headerVertical:false} it gives an infite error sometime!

Tabulator Version: 4.5.3

Hope you're aware of the bug.

Thanks & Regards
Rajibul

**Comment by olifolkerd** [comment]
@rajibulhuda 

This is happening because you are storing your numbers as strings rather than numbers. the average column calculation expects the input to be a number type rather than a string

Cheers

Oli :)

**Comment by rajibulhuda** [comment]
Thank you very much! Haven't notice that 🙄!

**Comment by rajibulhuda** [comment]
Hi @olifolkerd , 

Basically problem is for the JSON encoded data comes from php and mysql, the encoded data always come in double quote, i.e., as string, is there any way to remove double quote for particular field from json encoded data? Moreover sum,min, max works great in tabulator with the encoded data but the problem is only for Average .

Thanks & Regards
Rajibul
