### ISSUE TITLE
Feature Request:  UTC mode for datetime columns

### ISSUE THREAD

**Issue by nigels-com** [olifolkerd/tabulator#2593]
I'm having some good success using Tabulator _datetimediff_ formatter in combination with _Moment.js_.

However there is one issue I'm needing to workaround.

The timestamps I'm working with are UTC UNIX millisecond integers.  These are consumed happily via `formatterParams:{inputFormat:'x'}`, but are treated as **local time**.  I'm ten hours ahead of UTC, which I need to factor back into the header filtering: 

```column.setHeaderFilterValue(moment().subtract(val, 'days').subtract(10, 'hours').format('x'));```

So I would request that along with `inputFormat` there is an opt-in for UTC mode.
This mode would use the _Moment.js_ [ UTC path](https://momentjs.com/docs/#/parsing/utc/) to convert from UTC to localtime, internally.

**Comment by olifolkerd** [comment]
Hey @nigels-com 

Thanks for the suggestion, i will look into this in future, or feel free to [Submit a Pull Request](http://tabulator.info/community#pullrequest) yourself.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Looking into this a bit more i will look at adding support through moments, timezone functionality:
https://momentjs.com/timezone/docs/

I will add a parameter to allow setting of the timezone on the sorter and formatter and it will be down to the developer to ensure the timezone library has been installed, which i will link to in the docs.

I will aim to get this in on the 4.7 release

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @nigels-com 

I have just pushed an update to the 4.7 branch that will be released at some point next month.

You will be able to set a timezone for a column using the new ***timezone*** formatter param:

```js
{title:"Example", field:"example", formatter:"datetime", formatterParams:{
    outputFormat:"DD/MM/YY HH:ii",
    timezone:"America/Los_Angeles",
}}
```

Cheers

Oli :)
