### ISSUE TITLE
Spelling error on autoColumns's default value, the fakse should be false

### ISSUE THREAD

**Issue by cantstoplovingu** [olifolkerd/tabulator#2595]
**Website Page**
[options#columns](http://tabulator.info/docs/4.5/options#columns)

**Describe**
Spelling error on autoColumns's default value, the **`fakse`** should be **`false`**, right?

![image](https://user-images.githubusercontent.com/21187889/72773150-38b2bc80-3c41-11ea-8f67-f30f20c3762a.png)

**Comment by olifolkerd** [comment]
Hey @cantstoplovingu 

Good spot! i will get that fixed in the next update.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
This will be fixed in this evenings update.

Cheers

Oli :)
