### ISSUE TITLE
When make table editable, how to let the newly changed data update the original data array?

### ISSUE THREAD

**Issue by vonschbo** [olifolkerd/tabulator#26]
I just start using this API, that troubles me.
Or how to refresh the table, when I use
    var data = $("#example-table").tabulator("getData");

**Comment by olifolkerd** [comment]
To make a table editable you need to set the ***editable*** parameter to ***true*** in the column definition for the column you want your users to edit

```js
$("#example-table").tabulator({
	columns:[
		{title:"Name", field:"name", width:200, editable:true}, // editable column
	],
});
```

As soon as the cell looses focus the data in Tabulator will be updated.

You can then get an array containing the updated table data using the ***getData*** function

```js
var data = $("#example-table").tabulator("getData"); //returns an array of the updated data.
```

You should not need to refresh the table after you have edited it, it will automatically display the new value after the edit has finished.

A working example of the editable table can be found [here](http://olifolkerd.github.io/tabulator/examples/#editable)

Documentation on editing data can be found [here](http://olifolkerd.github.io/tabulator/docs/#manipulating-data)

Does this answer your question? if not can you post an example of what you are trying to achieve.

**Comment by vonschbo** [comment]
Thanks for your reply. 
One more thing I want to know is, how to create the column and read the column header name from the Json format of data, not predefine the name and number?

**Comment by olifolkerd** [comment]
If you want to set the columns after the Tabulator has been built, you can use the  ***setColumns*** function:

```js
//new column definition array
var newColumns = [
    {title:"Name", field:"name", sortable:true, sorter:"string", width:200, editable:true},
    {title:"Age", field:"age", sortable:true, sorter:"number", align:"right", formatter:"progress"},
    {title:"Height", field:"height", sortable:true, formatter:"star", align:"center", width:100},
    {title:"Favourite Color", field:"col", sorter:"string", sortable:false},
    {title:"Date Of Birth", field:"dob", sortable:true, sorter:"date", align:"center"},
],

$("#example-table").tabulator("setColumns", newColumns , false) //completely overwrite existing columns with new columns definition array
```

To get an array of the current column definitions use the ***getColumns*** function:
```js
var colDefs = $("#example-table").tabulator("getColumns") //get column definition array
```

Full documentation on manipulating column definitions can be [found here](http://olifolkerd.github.io/tabulator/docs/#movable)

Im not a great expert on node.js im afraid, [this article](http://stackoverflow.com/questions/15231864/display-html-page-with-node-js) covers how to display a web page with Node.js so you could start there.
