### ISSUE TITLE
Continous serverside scrolling. Provide working Example

### ISSUE THREAD

**Issue by michaelongithub** [olifolkerd/tabulator#260]
Hi  Oli

I have tried to do that but only the first two request are sent on initializing correctly, then nothing happens when scrolling.
```
    $('#tabulatortest').tabulator({
        height: "400px",
        fitcolumns: false,
        columns: [
            { title: "DossierNr", field: "DossierNr" },
            { title: "DossierName1", field: "DossierName1" },
            { title: "DossierName2", field: "DossierName2" },
            { title: "DossierName2", field: "DossierName2" },
        ],
        ajaxURL: daUrl,
        ajaxConfig: "GET",
        progressiveRender: "remote",
        paginationSize: 25,
        progressiveRenderSize: 10,
        progressiveRenderMargin: 100
    });
```

Should be 1370 row in db server table to scroll through. Wrong options? Bug ?

Clarification / Example / Demo (best) much appreciated.

Regards, Michal

**Comment by olifolkerd** [comment]
Your table height will need to be less than the height of your initially loaded data for progressive rendering to work. i would suggest increasing the **progressiveRenderSize*** to fill your table and a bit more.

Let me know if that helps.

Cheers

Oli

**Comment by michaelongithub** [comment]
Hi Oli

Had serverside wrong calculation of last_page.
(not completely sure in your docu, what that means: num of rows in db table / pagesize ?)
And with your hint for other options Chrome ok now tested: 

```
   $('#tabulatortest').tabulator({
        height: "600px",
        fitcolumns: false,
        columns: [
            { title: "DossierNr", field: "DossierNr" },
            { title: "DossierName1", field: "DossierName1" },
            { title: "DossierName2", field: "DossierName2" },
            { title: "DossierName2", field: "DossierName2" },
        ],
        ajaxURL: daUrl,
        ajaxConfig: "GET",
        progressiveRender: "remote",
        paginationSize: 200,
        progressiveRenderSize: 50,
        progressiveRenderMargin: 100
    });
```

IE11 howewer wrong behaviour: sends continously next request after trying to render data instead of waiting until user scrolls and new data needed.  So UI blocked until all data retrieved from server. 

Not yet tested: if other user adds / deletes rows in db table and last_page changes while scrolling behaviour still correct.

Regards, Michael

**Comment by olifolkerd** [comment]
Hey Michael,

I have just pushed an update to the repo for progressive rendering that should hopefully fix the issues you have been having.

Also make sure your ***progressisveRenderSize*** value is the same as the ***paginationSize*** of your returned data.

Let me know how that goes for you

Cheers

oli

**Comment by michaelongithub** [comment]
Hi Oli
tested with new repo version.
IE11 now ok with sending only needed request. Also Column Resize Scollbar vanish fixed, OK now. 
But still too much time for rendering, up to 30 secs after receiving data.
Chrome: OK as before.
Why progressisveRenderSize value is the same as the paginationSize  ? worked in Chrome also correctly with:
        paginationSize: 200,
        progressiveRenderSize: 50,
        progressiveRenderMargin: 100
Would like to undersatand. In Chrome even sending sometimes mutliple requests (4) consequtively if setting this equal.
Cheers, Michael

**Comment by olifolkerd** [comment]
Hey,

Just a quick note to let you know that this feature will be available in the upcoming 3.0 release later in May!

Cheers

Oli

**Comment by michaelongithub** [comment]
Great !!

**Comment by olifolkerd** [comment]
Hey,

You will be happy to hear that version 3.0 is now in beta release, with the speed of the new Virtual DOM you can now load all your table data in one request!

Head over to http://olifolkerd.github.io/tabulator/news/ to see the latest features!

Cheers

Oli
