### ISSUE TITLE
Mutator example function gets wrong argument

### ISSUE THREAD

**Issue by asterisk37n** [olifolkerd/tabulator#2600]
**Website Page**
http://tabulator.info/docs/4.0/mutators

**Describe the issue**
Example snippet has a bug. It gets params, but it expects to get mutatorParams. Snippet should be fixed by replacing params with mutatorParams in arguments (or mutatorParams with params in code).

```
var customMutator = function(value, data, type, mutatorParams, component){
	//value - original value of the cell
	//data - the data for the row
	//type - the type of mutation occurring  (data|edit)
	//mutatorParams - the mutatorParams object from the column definition
	//component - when the "type" argument is "edit", this contains the cell component for the edited cell, otherwise it is the column component for the column

	return value > mutatorParams.threshold; //return the new value for the cell data.
}
```

**Comment by olifolkerd** [comment]
Hey @asterisk37n 

Thanks for pointing that out, i will fix it on the next site update.

Cheers

Oli :)
