### ISSUE TITLE
persistenceWriterFunc not called on next/prev page

### ISSUE THREAD

**Issue by britvik** [olifolkerd/tabulator#2602]
**Describe the bug**
**persistenceWriterFunc** is not called when you change the page via buttons next/prev.

**Tabulator Info**
- 4.5.3

**Working Example**
https://codepen.io/britvia/pen/gObEaYZ

**Comment by olifolkerd** [comment]
Hey @britvik 

Thanks for the headsup, i will get that fixed in the next release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @britvik 

I have pushed a fix for this to the 4.6 branch, which will be released later this weekend.

Cheers

Oli :)
