### ISSUE TITLE
rownum not updated on row added or moved

### ISSUE THREAD

**Issue by maximp68** [olifolkerd/tabulator#2603]
Hi,

tabulator 4.5 (latest from cdn).
1 column with formatter rownum

when adding/deleting/move rows, the rownum column become inconsistent.

See this jsFiddle:
https://jsfiddle.net/maximp68/9cxkzhg2/15/

1) move a row with the handle: the rownum column keeps original values (numbering inconsistent)
2) click a row and trigger an addRow above the clicked row: the new row gets correct rownum, but all the other rows (including clicked one) keep the old rownum (numbering inconsistent)
3) order for any column (i.e. Name): the rownum column gets consistent values again

I was expecting rownum column to autoupdate always and mantain a consistent number sequence whatever action you do on the rows.

Is there any action to refresh rownum, other than ordering ?

**Comment by olifolkerd** [comment]
Hey @maximp68 

Thanks for letting me know, i will look into fixing this in a future release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @maximp68 

I have pushed a fix for this to the 4.6 branch that will be released later this weekend.

Cheers

Oli :)

**Comment by josephcrowell** [comment]
This issue currently exists on the 4.7.1 branch.
