### ISSUE TITLE
Mobile Device

### ISSUE THREAD

**Issue by sriramkrishnailla** [olifolkerd/tabulator#2604]
Detecting window size of a browser and moving Status and Edit coumn to after Count Column and changing table layout to "fitDataFill". But on first time loading it is not displaying Status and Edit column and then after changing device it is working fine. How to make that work on first time. 

**Tabulator Info**
Version : 4.5

**Working Example**
$( window ).resize(function() {
            var width = $( window ).width();
           f(width < 1200 && width > 900) {
                table.options.layout = "fitDataFill";
                table.options.columns[1]["width"] = "100";
                table.options.columns[10]["width"] = "100";
               table.moveColumn("Reviewed", "Count", true);
                table.moveColumn("isEdit", "Reviewed", true);
            }
            if(width < 900) {
                console.log(table);
                table.options.layout = "fitDataFill";
                table.options.columns[1]["width"] = "100";
                able.moveColumn("Reviewed", "Count", true);
                table.moveColumn("isEdit", "Reviewed", true);
            }
        });

function drawtable(tabledata) {
            table = new Tabulator("#example-table", {
                data: tabledata, //load row data from array
                layout: "fitColumns",
                responsiveLayout: "collapse",
                responsiveLayoutCollapseStartOpen:false,
                tooltips: true, //show tool tips on cells
                addRowPos: "top", //when adding a new row, add it to the top of the table
                history: true, //allow undo and redo actions on the table
                pagination: "local", //paginate the data
                paginationSize: 10, //allow 7 rows per page of data
                movableColumns: true, //allow column order to be changed
                resizableRows: true, //allow row order to be changed
                initialSort: [ //set the initial sort order of the data
                    {
                        column: "Name",
                        dir: "asc"
                    },
                ],
                columns: [ //define the table columns
                    {
                        formatter: "responsiveCollapse",
                        width: 30,
                        minWidth: 30,
                        title:"",
                        align: "center",
                        resizable: false,
                        headerSort: false,
                    },

                    {
                        title: "Count",
                        field: "Count",
                        headerFilter:"input",
                        width: 100,
                    },
                    {
                        title: "Date",
                        field: "Date",
                        formatter: "datetime", 
                        formatterParams: {
                            outputFormat: "MM-DD-YYYY",
                        },
                        align: "center",
                        width: 300,
                        headerFilter:dateFilterEditor, headerFilterFunc:dateFilterFunction
                    },
                    {
                        title: "Name",
                        field: "Name",
                        align: "left",
                        width: 150,
                        headerFilter:"input"
                    },
                    {
                        title: "BU",
                        field: "BusinessUnit",
                        editor:"input", headerFilter:"select", headerFilterParams:{values:true}
                    }
                    ,
                    {
                        title: "Unsafe Acts Observed",
                        field: "UnsafeActsObserved",
                        //width: 200,
                        headerFilter:"input"
                    }
                    ,
                    {
                        title: "Action Taken",
                        field: "ActionTaken",
                        //width: 100,
                        headerFilter:"input"
                    }
                    ,
                    {
                        title: "Safe Acts Observed",
                        field: "SafeActsObserved",
                        //width: 120,
                        headerFilter:"input"
                    }
                    ,
                    {
                        title: "Safe Start",
                        field: "SafeStart",
                        editor:"input", headerFilter:"select", headerFilterParams:{values:true},
                        width: 120,
                    }
                    ,
                    {
                        title: "Hazard Types",
                        field: "HazardTypes",
                        editor:"input", headerFilter:"select", headerFilterParams:{values:true},
                        width: 120,
                    }
                    ,
                    {
                        title: "Status",
                        field: "Reviewed",
                        headerFilter:"input",
                        formatter: reviewText,
                        //width: 100,
                        align: "left",
                    },
                    {
                        title: "Edit",
                        width: 50,
                        field: "isEdit",
                        formatter: editIcon,
                        align: "center",
                        cellClick: function (e, cell) { 
                            var data = cell.getRow().getData();
                            localStorage.setItem('editData', JSON.stringify(data));
                            location.href = 'index.html';
                            console.log(data);
                         }
                    }
                ]
            });
            var width = $( window ).width();
            if(width < 1200 && width > 900) {
                table.options.layout = "fitDataFill";
                table.options.columns[1]["width"] = "100";
                table.options.columns[10]["width"] = "100";
                table.moveColumn("Reviewed", "Count", true);
                table.moveColumn("isEdit", "Reviewed", true);
            }
            if(width < 900) {
                table.options.columns[1]["width"] = "100";
                console.log(table);
                table.moveColumn("Reviewed", "Count", true);
                table.moveColumn("isEdit", "Reviewed", true);
            }
        }

Below are the screenshots for first time load and then after resize detection.
![First Refresh](https://user-images.githubusercontent.com/13344491/73169083-4a083700-4121-11ea-90cc-497661fc4270.JPG)

Could you please check that

Thanks
Sriram

**Comment by olifolkerd** [comment]
Hey @sriramkrishnailla 

Please share a link to a JS fiddle that shows the issue in action, it is very hard to see what is going on from large unformatted blocks of code.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey
