### ISSUE TITLE
Possible issue with select rows

### ISSUE THREAD

**Issue by mikehobson** [olifolkerd/tabulator#2607]
Hi, Oli

Im trying to make selected rows appear in two seperate tables (on different web pages) and also my table to retain the rows on refresh and I have an odd problem which im not sure is me or a fault

So I have a table construct which has an index of matchid and runs a function when a row is selected or deselected

`         index:"matchid",
           rowDeselected:function(row) {updaterow();},
           rowSelected:function(row)   {updaterow();},`

The function update row takes a snapshot of selected rows and stores the matchid(the index) in a file

`function updaterow(){
      var array =[];
      selectedtableData = table.getSelectedRows();
      for (f = 0; f < selectedtableData.length; f++) {
            var rowIndex = selectedtableData[f].getIndex();
            array.push(rowIndex);
                }
        array =JSON.stringify(array);         
        $.ajax({
          type: "POST",
          url: 'saverows.php',
          data: array
        });  
}
```
This gives me a file which looks like this ["11950887","11950886","11950887"]

I then have a tablebuilt function which will reselect those rows when the page is reloaded

`           tableBuilt: function() {
              $.ajax({
                    url: "getrows.php",
                    cache: false,
                    dataType: "json",
                    success: function(data) 
                    {
                     table.selectRow(data); 
                    }
                 })
            
            
           }`

the getrows.php simply reads the file and returns Json.

If I now select 2 games and hit refresh it loses those games 50% of the time, even though I can see the index in the text file, if I then select extra rows they are added to the file, I can alert them to the screen but they do not select

you can see this behavior in action at https://soccerscanner.net/pro/sportsmonks/fixtures.php

Thanks

Miike

**Comment by olifolkerd** [comment]
Hey @mikehobson 

Thanks for getting in touch,

Could you have a quick read of the [Bug Reporting Guide](http://tabulator.info/community#bug). In order for us to help you out we need to see a JS Fiddle or Code Pen of a mimum usage case that replicates the issue without the rest of the site code.

Cheers

Oli :)
