### ISSUE TITLE
Select options close on scrollbar click in Internet Explorer

### ISSUE THREAD

**Issue by britvik** [olifolkerd/tabulator#2608]
**Describe the bug**
I have a column with **select** editor. If there are many options (values) there is a scrollbar. But if I click on the scrollbar or arrow (to move down in the list), it disappears. Works in Chrome.

**Tabulator Info**
- 4.5.3

**Working Example**
http://tabulator.info/examples/4.5#editable
- Try to change the location to Japan (last in the list), without using mouse scroll. Click on the scrollbar.

**Expected behavior**
Options panel should not close when I try to scroll down via clicking on arrow/scrollbar.

**Desktop (please complete the following information):**
 - Browser [Internet Explorer]
 - Version [11]

**Comment by olifolkerd** [comment]
Hey @britvik 

Thanks for the info, my first suggestion would be to stop using IE 🤣 

But on a more serious note i will have a look into that for a future release.

Cheers

Oli :)

**Comment by britvik** [comment]
@olifolkerd I honestly agree with your suggestion 😄. Unfortunately I have to support it 😭

**Comment by olifolkerd** [comment]
Hey @britvik 

I have just pushed a fix for this to the master branch and will include it in sundays patch release.

Cheers

Oli :)
