### ISSUE TITLE
resize column without scroll bar, adjust neighboring column width to offset change

### ISSUE THREAD

**Issue by ghost** [olifolkerd/tabulator#2609]
Hello,

I would like to submit a small idea that could make the use of "Tabulator" easier. 

Currently, the possibilities to resize a column are: either to have a scrollbar or to hide a column completely.

The idea would be that when you resize a column, the column next to it also resizes automatically, so that the table takes up all the available space.

This will keep as many columns as possible, in small spaces, giving the user the ability to resize freely, and without having to scroll left or right just because they had a sentence that was a bit too long.

I'm sending you 2 images (before/after) to show you a preview of the result. The last two columns are resized, but the inside of the table doesn't change its dimensions.

**Possible variant**: When you enlarge a column, you reduce the last column at the same time, and when it reaches its minimum size, it passes the relay to the column next to it. (I think this option would be more consistent with the logic of a spreadsheet).

thank you.

![Before](https://user-images.githubusercontent.com/25307076/73307298-37bff300-421e-11ea-97bb-0abea8df65c2.jpg)
![After](https://user-images.githubusercontent.com/25307076/73307297-37bff300-421e-11ea-8c54-306a7615eff4.jpg)

**Comment by olifolkerd** [comment]
Hey @Pristio 

Thanks for the suggestion, I like the idea and will consider it for a future release.

Cheers

Oli

**Comment by xeroxstar** [comment]
> Hey @Pristio
> 
> Thanks for the suggestion, I like the idea and will consider it for a future release.
> 
> Cheers
> 
> Oli

Hello @olifolkerd ,
Does the v5 support this type of layout? I couldn't find anything here [http://tabulator.info/docs/5.0/release](http://tabulator.info/docs/5.0/release).

**Comment by olifolkerd** [comment]
Hey All,

I have just pushed an update to the 5.2 branch that adds the 'resizableColumnFit' option which will provide this functionality.

It will be included in the 5.2 release later this month.

Cheers

Oli :)
