### ISSUE TITLE
column header drag and drop issue from right to left.

### ISSUE THREAD

**Issue by giriswamy** [olifolkerd/tabulator#261]
Hi,
   I observed one scenario 
  1. First I have tabe which contains  5 headers,
  2. Select third column and drag to second column(don't leave mouse, keep mouse drag in hold)
  3. try right to left and left to right and right to left(don't leave mouse) now observe third column data and second column data

**Comment by olifolkerd** [comment]
Hi,

Thanks for getting in touch,

Could you post a copy of your Tabulator constructor object so i can test with the same setup as you.

Cheers

Oli

**Comment by olifolkerd** [comment]
closed due to lack of reply
