### ISSUE TITLE
Remove all filters for a specific field 

### ISSUE THREAD

**Issue by dmahoney1213** [olifolkerd/tabulator#2611]
*Is your feature request related to a problem? Please describe.**
I am currently using a range slider and am stuck as I cannot easily clear the previous values filters.

**Describe the solution you'd like**
table.removeFilter("field")

**Describe alternatives you've considered**
1. The ability to update a filter to a new value
2. Being able to remove a filter without reloading the table

**Additional context**
My current solution involves removing the filter as the slider starts to move, but the issue is this causes the table to reload at the start and again at the end of the slider moving. 

setFilter does not work because I have multiple sliders, checkboxes etc to filter with and i do not want to replace all of the filters. addFilter piles on more and more filters everytime the slider moves to a new spot.

**Comment by dmahoney1213** [comment]
[Related question on stack](https://stackoverflow.com/questions/59977641/tabulator-range-slider-to-update-filter)

**Comment by olifolkerd** [comment]
Hey @dmahoney1213 

You can already do this with the ***clearHeaderFilter*** function on the table itself to clear all header filters:
```js
table.clearHeaderFilter();
```

The ability to clear specific header filters per column is coming in the 4.6 release.

Cheers

Oli :)

**Comment by dmahoney1213** [comment]
I ran into a very similar issue as this again. This time trying to make a search functionality outside of a header filter. I do not want to use header filters due because I want more customization of where they are at on the page, what they look like, etc. 
The crux of the issue again is that I cannot call setFilter as it wipes all previous filters set. Below is what I have now, which works until you add any more filters. 
```
$("#search").keyup(searchFilter);

function searchFilter(){
    table.setFilter("name", "like", $("#search").val())
}
```
I think being able to remove all filters of a certain field would still be a very valuable addition. Or have a way to update a certain filter.
