### ISSUE TITLE
Scrollbar is always on bottom when loading a table in Tabulator

### ISSUE THREAD

**Issue by kreamas** [olifolkerd/tabulator#2614]
Everytime I load a table, the scrollbar appears at the bottom of it.

Why is it happening? Is there a way I can set it to the top of my table?

Thanks in advance

**Comment by olifolkerd** [comment]
@kreamas If the width of your columns exceeds the width of the table then the scroll bar will be displayed.

It is a standard horizontal scroll bar and it is up to the browser where it puts it, which conventionally is at the bottom of the container.

Cheers

Oli :)
