### ISSUE TITLE
Column width skyrocket outside any bound when resizing

### ISSUE THREAD

**Issue by AlexanderPD** [olifolkerd/tabulator#2616]
I just found out that in my configuration, a simple resize of a column triggers "something" that make tabulator endlessly increase its width.
My guess is that the autoredraw function increased its width and recalls itself increasing again its width an go on..

I'm using Tabulator 4.5.1 with the latest Chrome browser

To reproduce the problem..

- create Tabulator inside a table's td tag
- use layout "fitColumns"
- use at least 2 column: the first with fixed width and the second without any width parameter
- set the height attribute on tabulator
- try to resize the first column

I made this because i wanted the second column to use all the free space in the table, as i read into the [Docs](http://tabulator.info/docs/4.5/layout#fittowidth)

JsFiddle link: https://jsfiddle.net/AlexanderPD/149ezabp/5/

**Comment by olifolkerd** [comment]
Hey @AlexanderPD 

It is because you are trying to use a textarea formatter for your title formatter. This is not a valid combination and shouldnt be needed. If you take that out you will be all good,

Cheers

Oli :)

**Comment by AlexanderPD** [comment]
thank you @olifolkerd for your answer.. but removing that titleFormatter didn't help! I also tried setting it to html, plaintext and also rowSelection, but it cannot fix that problem

I also tried inside the jsfiddle i posted and it cannot work :(
