### ISSUE TITLE
rowSelection possible for visible and active rows

### ISSUE THREAD

**Issue by ricardogffcouto** [olifolkerd/tabulator#2617]
**Is your feature request related to a problem? Please describe.**
I would like to be able to select/deselect only visible or active rows in a rowSelection header.

**Describe the solution you'd like**
Maybe a parameter which would allow me to indicate exactly which rows I would like to select/deselect (all, visible or active).

**Describe alternatives you've considered**
I modified tabulator.min.js directly, changing e.table.selectRow() to e.table.selectRow("active") and e.table.deselectRow() to e.table.deselectRow(e.table.getRows("active")).

Thanks!

**Comment by dcanning** [comment]
http://tabulator.info/docs/4.5/select#manage
`table.selectRow("visible"); //select all rows currently visible in the table viewport`
`table.selectRow(1); //select row with id of 1`
`table.selectRow(); //select all rows`

**Comment by ricardogffcouto** [comment]
I don't think you understood the feature request or maybe I didn't explain myself well. It was not a question, as I solved my problem, it was a suggested feature, as I can't find anything in the docs that allow me to do what I described: allow the **rowSelection header** to select only active rows. @dcanning as you describe I can't understand how to integrate the code you shown into rowSelection.

**Comment by danielboven** [comment]
For those still looking for a simple solution to the original question/feature suggestion that @ricardogffcouto did, it has been introduced in Tabulator v4.8. The new `rowRange` parameter in the column definitions `titleFormatterParams` option allows to only select active rows when using the checkbox in the header.
A code example of this:
```
const table = new Tabulator("#table", {
  columns: [
    {
      formatter: "rowSelection",
      titleFormatter: "rowSelection",
      titleFormatterParams: {
        rowRange: "active" // only toggle the values of the active filtered rows
      },
      hozAlign: "center",
      headerSort: false
    },
  ],
});
```
Source: http://tabulator.info/docs/4.8/release#format
