### ISSUE TITLE
Cell with editor: 'number' treats 0 and 'empty' weirdly

### ISSUE THREAD

**Issue by nirhu** [olifolkerd/tabulator#2618]
**Describe the bug**
Typing and deleting value 0 has weird behavior. 

**Tabulator Info**
v. 4.5.3

**Working Example**
https://codepen.io/nirhu/pen/OJVVodz

**To Reproduce**
1. Click on the cell and enter number 0
2. Click away (lose focus)
3. Click again on the cell and delete 0
4. Click away (lose focus) - the 0 shows up

To make the cell empty now you have to:
5. Enter any number (e.g. 1)
6. Click away
7. Delete 1
8. The cell is now empty, but when you now enter 0 and click away, it disappears

**Expected behavior**
Deleting 0 will result in an ampty cell and typing in 0 keeps it there.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version: 80.0.3987.87

Maybe there is some code that compares old and new values and considers 0 and empty to be the same, therefore it does not update the model?

**Comment by olifolkerd** [comment]
Hey @nirhu 

Thanks for the information, it is because at the moment it is doing a truthy comparison. i will look into a fix for this in the next release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @nirhu 

I have pushed a fix to the 4.6 branch for this, it will be released later this weekend.

Cheers

Oli :)
