### ISSUE TITLE
Rowheight per row, also interactively by user

### ISSUE THREAD

**Issue by michaelongithub** [olifolkerd/tabulator#262]
Hi Oli

we often have tables with large text content. Using textarea formatter serves ok for inital use.
Rowheight however does not adapt when column resize by user (by design? bug?).

A very handy feature would be to be able to change individual rowheight after initial display by user. Like initial display rowheight constant, with ellipsis if not all can be displayed. Then user mouse drag row gridline or doubleclick to change height of this row.  (A littel bit an Excel like behaviour)

Or can this already be done with a callback like initial formatting not texarea and then change for this row cell?

Interestingly enough this seems to be a real challenge for most datagrid controls (opensource or paid) and only flexgrid seems to really be able to do that.

It is no killer crit for us. How do You think about it in terms of feasabilty and priority?

Regards Michael

**Comment by olifolkerd** [comment]
Hey Michael,

Thanks for getting in touch.

Great spot on the text area column resizing, I hadn't even thought of that one, i will see if i can get a fix in for that at some point this week.

Row height adjustment is currently not in tabulator, but It is a heavily requested feature.

I was originally planning on adding it in the 3.0 release later in the year, but a few people have requested it in the last couple of months, so i will see if i can get a simple version of it in next months release as there is clearly a demand for it.

Cheers

Oli

**Comment by michaelongithub** [comment]
Hi Oli

reiterating just to divide up a little bit clearer in detail feature points:

- Feature  as it is now with textformatter made compatible with ColumnResize.

- Show ellipsis or cut off (options) and when ColumnResize adapt: Show more / Shrink Text until all shown or ellipisis / Cut off.

- Variant: Tooltip for displaying invisible text. This could maybe a much simpler functionality compared to the grow/shrink above. Not as brilliant, but helping.

- Resize row height by user.

Please note again, that only the first one is really in the proximity of a bug. Others, You know best about priorities / demand / effort / maintainability and so on.
Cheers, Michael

**Comment by olifolkerd** [comment]
Hey,

Just a quick note to let you know that these features will be available in the upcoming 3.0 release later in May!

Cheers

Oli

**Comment by michaelongithub** [comment]
Great !!

**Comment by olifolkerd** [comment]
Hey,

You will be happy to hear that version 3.0 is now in beta release, and column resizing now causes row height adjustment when needed!

Head over to http://olifolkerd.github.io/tabulator/news/ to see the latest features!

Cheers

Oli
