### ISSUE TITLE
table.getSorters() and dataSorted callback do not return all sorters

### ISSUE THREAD

**Issue by blankbadge** [olifolkerd/tabulator#2620]
Hi Oli,

When clicking multiple table columns one after another, sorting each in sequence, my expectation is that querying the current sorters would return an array containing each sorter being applied.  But I always get back an array of only one object, representing only the last applied sort.

Based on documentation, it sounds like table.getSorters() as well as the sorters value in the dataSorted callback function should be returning an array of all applied sorts.  

Does this only apply if I apply multiple sorts at once using table.setSort?  Maybe my expectation is wrong.  I thought that a sequence of individual sorts applied by clicking the column headers would be recorded.  If my expectation does not align with yours for this case, feel free to close this issue.  

**Tabulator Info**
4.5.3

**Working Example**
https://jsfiddle.net/blankbadge/sw8Lgun4/

**To Reproduce**
The testcase creates a simple numeric table with three columns, Col0 through Col2.  click each column header from Col2 to Col1 to Col0 in sequence to do an ascending sort on each column.  You can see by the table data that each sort is applied in sequence.  i.e. Col0 is ascending sorted, but then when Col0 rows have the same value, Col1 is ascending sorted for those rows, because it was the previous sort I had applied.  And same for Col2.

But this sort ordering isn't reflected when queried.  I show this in two ways.  Each time a column is sorted, it logs to the console the sorters array from the dataSorted callback.  Then, there is a button you can click which will return the table.getSorters() result, and it also only gives an array of the latest sorter.

**Expected behavior**
I expected that this sequence of applied sorts would be represented in the sorter queries, but my expectation may be wrong.  Please clarify if it's a bug or expected behavior.

**Screenshots**
Screenshot shows the result running the testcase and clicking Col2 then Col1 then Col0, then the button, and the logging of the sorters from each action.  Always only the latest sorter is shown.
![image](https://user-images.githubusercontent.com/57735852/74369734-7ebff380-4d9b-11ea-8d6f-14d7e9c99968.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 79

**Context**
Why am I looking for this behavior?  In my application I am loading different datasets as rows into the table, and the user may trigger an action that loads a different collection of datasets.  In such a case, I fully rebuild the table, but I want to retain the previous sorting.  So I was trying to query table.getSorters() to then reapply the sort on the new table, but it only captures the latest sort.  So, I'll need to manually track the sequence of sorts applied and build that history for myself.  Would have been easier if getSorters() provided it.

There are complications to tracking it in getSorters() -- suppose a user repeatedly clicks a column sort over and over, or has clicked around sorting different columns for a long time, producing a large history of sorts.  It could really impact performance to reapply all those redundant sorts again.

Thanks,
James

**Comment by olifolkerd** [comment]
Hey @blankbadge 

It would return multiple sorters if you had shift clicked on the columns applying multiple sorters simultaneously.

Clicking one sorter and then another simply replaces the previous column sort with the next.

Cheers

Oli :)
