### ISSUE TITLE
Issue using updateColumnDefinition

### ISSUE THREAD

**Issue by nrayburn-tech** [olifolkerd/tabulator#2623]
I looked at your roadmap just before submitting this and it looks like the updateColumnDefinition function got moved into "The Future" category.  If that is the case, then this can be closed.

**Describe the bug**
I am attempting to use the updateColumnDefinition to change a column.  When calling the function like `table.updateColumnDefinition('fieldName', {title: 'new title', width: 300})`, I don't see any difference in the table or in the returned column definition.

**Tabulator Info**
4.5.3

**Working Example**
[https://jsfiddle.net/zopeL3ns/](https://jsfiddle.net/zopeL3ns/)

**To Reproduce**
Open the link and it runs the code, there are not any additional steps.

**Expected behavior**
I expect the column definition that is returned from the promise to contain the updated values.
I expect the table to visually change to a wider width as well as the title change.

**Desktop**
 - OS: macOS 10.15.3
 - Browser: Chrome
 - Version: 80

**Additional context**
I am attempting to setup a column that will have the formatterParams and editorParams.values changed dynamically.  It didn't appear that this was working, so I tried a simpler example with just the title or width and the issue persisted.

**Comment by olifolkerd** [comment]
Hey @nrayburn-tech 

Thanks for the headsup, that is definitely a bug,

I will get that resolved in the 4.6 release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @nrayburn-tech 

I have pushed a fix for this to the 4.6 branch which will be released later this weekend.

Cheers

Oli :)
