### ISSUE TITLE
Tabulator performance

### ISSUE THREAD

**Issue by ecthelion07** [olifolkerd/tabulator#2625]
**Describe the bug**
We are currently using Tabulator in one of our commercial products and might have found a performance issue whenever we define a table that has a decent quantity of rows and columns and the virtual DOM setting on. 

Chrome seems to be showing performance warnings as a result of that as well, please see attached: 

![image](https://user-images.githubusercontent.com/4159643/74853079-50ab5800-5335-11ea-82e0-8239d5e89be4.png)

We are currently experiencing it while  dragging the vertical scroll bar. Please find this JSFiddle for reference: https://jsfiddle.net/16wcLbeh/

**Tabulator Info**
- As you can see in the fiddle example, we are using the following version: 
https://unpkg.com/tabulator-tables@4.5.3/dist/js/tabulator.min.js

**Working Example**
https://jsfiddle.net/16wcLbeh/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://jsfiddle.net/16wcLbeh/
2. Drag the vertical scroll bar up and down.

**Expected behavior**
We would expect for the scroll bar to move smoothly and for browsers not to show performance warnings.

**Screenshots**

![image](https://user-images.githubusercontent.com/4159643/74853273-9cf69800-5335-11ea-9826-8e0452429dbd.png)

**Desktop (please complete the following information):**

 - Browser : **Chrome** Version 79.0.3945.130 (Official Build) (64-bit)
                   **Edge** Version 80.0.361.54 (Official build) (64-bit)

**Comment by dcanning** [comment]
I see the issue with all chromium based browsers that I tried (chrome, brave, edge, opera).  I do not see the issue in firefox, appears to be a browser related issue.

**Comment by olifolkerd** [comment]
It is just a warning triggered by the render being interrupted by the scroll. It is nothing to be concerned about.

Cheers

Oli :)

**Comment by ecthelion07** [comment]
Hi Oli / dcanning,

Unfortunately, it's not just about the warnings. Tabulator seems to have a perfomance issue under these conditions, as it seems to be quite "laggy".

Please have a look yourself in the fiddle I provided: https://jsfiddle.net/16wcLbeh/

Thank you very much!

**Comment by olifolkerd** [comment]
Hey @ecthelion07 

That is because your table has a lot of columns. That warning is not the cause of the lag, it is simply the strain of trying to draw out that many columns in one go.

Tabulators virtual DOM currently only deals with rows not columns so tables with lots of columns suffer some performance lag.

It is on the roadmap to resolve this with an overhaul of the virtual DOM in the 5.0 release.

Cheers

Oli :)
