### ISSUE TITLE
Grouping headers are printed out after grouping has been removed from the table from xlsx download

### ISSUE THREAD

**Issue by rotht2** [olifolkerd/tabulator#2626]
**Describe the bug**
With a set of ungrouped data, apply a grouping and export that table to xlsx.
Remove the grouping, and export the table to xlsx
Open the latter xlsx file and note that there are groupings in the file, yet they are not present in the table.

The underlying problem is that there is state that is set to true the first time you download to xlsx with groups. This state is never reset so when you clear the groups the state still says that there are groups.

**Tabulator Info**
4.5.3

**Working Example**
https://codepen.io/tylerroth/pen/wvazKBP

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://codepen.io/tylerroth/pen/wvazKBP
2. Click on the xlsx to get an example of an expected download
3. Click on the "group" button
4. Click on the xlsx button to download the grouped spreadsheet
5. Click on the "Ungroup" button
6. Click on the xlsx button
7. Open the downloaded xlsx document
8. Note that there are grouping headers present even though the table is not grouped

**Expected behavior**
the first xlsx file matches the thirds xlsx file

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.15.3
 - All

**Comment by olifolkerd** [comment]
When you have updated you PR to removed the fix for the second issue i will approve it and close this off

Cheers

Oli :)

**Comment by rotht2** [comment]
Thanks Oli. I will get this updated within the next few days.
