### ISSUE TITLE
Add reference to current column object in Custom Formatter

### ISSUE THREAD

**Issue by carterwe** [olifolkerd/tabulator#263]
The only way that I can see to get information from the current column definition in the custom formatter function is to pass something (like the Field or Title in the FormatterParams).  I think along with the other parameters available in the formatter call back function we should have column with the the current column object.

**Comment by olifolkerd** [comment]
Hey,

Great idea! I completely see where you are coming from. how about i add an and additional parameter which is the column definition array for the column being filtered?

Cheers

Oli

**Comment by carterwe** [comment]
Perfect!  I am doing crazy complex grid with multiple values in each and
formatted column headers to match. I will send you screen shots when
finished.  Took me two days to convert my application from ag-grid to
tabulator. Now there is no turning back!

**Comment by carterwe** [comment]
In each cell.

**Comment by olifolkerd** [comment]
Hey,

You will be happy to hear this feature will be coming in next months release, version 3.0, it is a ground up rebuild with tons of new features and massively improved performance.

It would be great to see some screen shots of you r system once you have it up and running!

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey,

You will be happy to hear that version 3.0 is now in beta release, the new ***component*** objects that are passed into every callback will now give you access to that functionality.

Head over to http://olifolkerd.github.io/tabulator/news/ to see the latest features!

Cheers

Oli
