### ISSUE TITLE
Data Download Progress Indicator

### ISSUE THREAD

**Issue by muneeb706** [olifolkerd/tabulator#2631]
Download data / table functionality for large data ( >500000 ) takes time. Browser takes a lot of time to display the downloaded file for such table. There should be a mechanism to display download data progress. I have tried using downloadComplete callback for this purpose but, that callback gets triggered before the file is actually downloaded.

**Comment by dcanning** [comment]
You can do this with progressive load: http://tabulator.info/docs/4.5/data#ajax-progressive

**Comment by muneeb706** [comment]
Thanks a lot for the response,  I was able to achieve this functionality by dividing the data into chunks and then used  progressive ajax load for displaying additional data when needed.
