### ISSUE TITLE
Package Format Download

### ISSUE THREAD

**Issue by muneeb706** [olifolkerd/tabulator#2632]
If the data is larger than the threshold then data can be splitted into multiple files and all of these files can be packaged in zip file or anyother packaged format.

User can be given an option to set the threshold e-g 1M and split data accordingly.

**Comment by olifolkerd** [comment]
Hey,

Thanks for the suggestion.


I'm not sure I see any benefit in this. All files are processed in the browser so there is not actual transfer time included in the download, it is just the browser processing time.

You can also only trigger the download of one file at a time so the experience could be a bit jaring.

I also don't see any particular use case where this would be useful regularly

There is of course nothing to stop you implementing this yourself if you specifically need the functionality. You could either create a custom downloader to do this. Or you could write a function outside of Tabulator that filters the data to specific ranges and produces a file for each of those.

Cheers

Oli :)
