### ISSUE TITLE
Bootstrap 4 pagination buttons styling on Custom Pagination Control Element

### ISSUE THREAD

**Issue by schmidty1913** [olifolkerd/tabulator#2633]
**Describe the bug**
The Bootstrap 4 theme for tabulator does not apply to a Custom Pagination Control Element

**Tabulator Info**
v4.5.3

**Working Example**
https://jsfiddle.net/ku3vL2zq/1/

**To Reproduce**
Look at pagination in top right corner

**Expected behavior**
Format like it would when it is on the footer

**Screenshots**
![image](https://user-images.githubusercontent.com/24723142/75086754-52277c80-54fd-11ea-8368-5a0d25c7a40d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version N/A

**Comment by olifolkerd** [comment]
Tabulator does not have pagination controls in the top right.

If you have manually added those then you would need to style them appropriately.

Tabulator is not responsible for styling any elements outside of the table div

Cheers

Oli :)

**Comment by mivade** [comment]
How exactly does one get this styled properly? I wanted to simply move the pagination controls to the top but am unable to figure out the magical incantations required to get the style to match what I get by default. The documentation on how to specify a custom location is pretty sparse.
