### ISSUE TITLE
React Router Link component inside a Tabulator custom formatter

### ISSUE THREAD

**Issue by 8483** [olifolkerd/tabulator#2634]
I am trying to inject a Link component inside a [Tabulator table](http://tabulator.info/) cell via a [custom formatter](http://tabulator.info/docs/4.5/format#format-custom). 

Nothing is shown in the cell, as seen in [the codesandbox](https://codesandbox.io/s/sad-dust-yvbu7).

Why can't the JSX be returned from a function? **How can I achieve this?**

```javascript
const journalLinkFormatter = (cell, formatterParams) => {     // <------ Custom formatter definition
    let key = cell.getValue();
    let link = `/journals/${key}`;
    return (<Link style={{ color: "blue"}} to={link}>{key}</Link>);
};

journalsTable.current = new Tabulator(refJournalsTable.current, {
    height: "100%",
    layout: "fitColumns",
    columns: [
        {
            title: "Налог",
            field: "journalKey",
            formatter: journalLinkFormatter     // <------ Custom formatter use
        },
        { title: "Датум", field: "journalDate" }
    ]
});
```

This approach works, but it defeats the purpose as the link leaves the react app and reloads everything.

```javascript
const columns = [
    {
        title: "Налог", 
        field: "journalKey", 
        formatter: "link", 
        formatterParams: { url: cell => { return "/journals/" + cell.getValue() } }
    },
    { title: "Date", field: "date_" },
];
```

**Comment by olifolkerd** [comment]
Hey @8483 

The HTML you are trying to add using the formatter will be added after react has parsed the DOM and will therefor not be considered as react code.

For working with react and Tabulator there is the [react-tabulator](https://www.npmjs.com/package/react-tabulator) package that provides access to native react functionality.

Cheers

Oli :)

**Comment by 8483** [comment]
The reason I asked here is because this doesn't work there.  

[I've made the developer aware of it.](https://github.com/ngduc/react-tabulator/issues/135)  

So I guess I should just drop it.

**Comment by singsinghai** [comment]
Is this closed yet xd? Sorry for being 2 years late here, I just came to the same problem.
I tried with useState for the key I want to navigate, and the Navigate from react-router-dom to help me with it. Here's my solution:
```
import 'react-tabulator/css/tabulator_bootstrap3.css';
import { ReactTabulator } from 'react-tabulator';
import { Navigate } from "react-router-dom";
import { useState } from 'react';


function CompanyRanking() {

    const [company, setCompany] = useState(null);

    const columns = [{
        title: "Mã cổ phiếu",
        field: "market_symbol",
        headerHozAlign: "center",
        hozAlign: "center",
        cellClick: (e, cell) => {
            setCompany(cell.getValue());
        },
        formatter: (cell) => {
            cell.getElement().style.color = "purple";
            cell.getElement().style.fontWeight = "bold";
            return cell.getValue();
        },
    },
    ];
    return (
        company ? <Navigate to={`/company/${company}`} />
            : <ReactTabulator
                data={ranking_data}
                columns={columns}
                layout="fitColumns"
                height="100%"
            />
    );
}

export default CompanyRanking;
```
This is might be late but I think someone else will come to this problem later so I will leave the solution here just in case :(
