### ISSUE TITLE
Typos on validation documentation

### ISSUE THREAD

**Issue by mikeymckay** [olifolkerd/tabulator#2635]
**Website Page**
http://tabulator.info/docs/4.5/validate

**Describe the issue**
1. Applying multiple validators section has a typo: requred -> required
2. Custom validator section needs indentation tidying.

Keep up the great work!

**Comment by olifolkerd** [comment]
Hey @mikeymckay 

Thanks for the heads up.

I will make sure those are fixed in the 4.6 site update.

Cheers

Oli :)
