### ISSUE TITLE
blocked setData(AJAX) doesnt showLoader() when completing request

### ISSUE THREAD

**Issue by roxuss** [olifolkerd/tabulator#2636]
consecutive AJAX setData() (without waiting for the prior call to finish), within :

`
Ajax.prototype.sendRequest(silent) 
`
will call console.warn("Ajax Response Blocked...").
When the prior AJAX setData() finishes, it calls hideLoader().
But when the queue'd AJAX setData() is called, it doesnt call showLoader();

Tabulator version 4.5.3
Linux Raspbian/Debian 10.0
Chrome Version 74.0.3729.157 (Official Build) Built on Raspbian

not sure how to do a jsfiddle on this, as I need an AJAX server to send the request to ?

**Comment by olifolkerd** [comment]
Hey @roxuss,

It dosnt queue up the ajax requests, it makes them immediately upon the ***setData*** call, if they happen concurrently it will ignore the returned result of any of the early requests and only action the final request,

Cheers

Oli :)

**Comment by roxuss** [comment]
On 3/22/2020 11:37 AM, Oli Folkerd wrote:
> Hey @roxuss <https://github.com/roxuss>,
> 
> It dosnt queue up the ajax requests, it makes them immediately upon the 
> /*setData*/ call, if they happen concurrently it will ignore the 
> returned result of any of the early requests and only action the final 
> request,

OK, thanks
Yes, I am calling them concurrently.
But hideLoader() is being called too early still. Possibly when the 
first setData does return, I havent traced it down that far yet.

**Comment by olifolkerd** [comment]
Ahh, I am with you now. I will look into that and see if I can fix it for the 4.6 release

**Comment by olifolkerd** [comment]
Hey @roxuss 

I have pushed a fix for this to the 4.6 branch which will be released later this weekend.

Cheers

Oli :)
