### ISSUE TITLE
"Max Min Custom Header Filter" Filters then Reverts on a key-press

### ISSUE THREAD

**Issue by darkbdlz** [olifolkerd/tabulator#2638]
**Tabulator Info**
I am using Tabulator version 4.5.3
<link href="https://unpkg.com/tabulator-tables@4.5.3/dist/css/tabulator.min.css" rel="stylesheet">
<script type="text/javascript" src="https://unpkg.com/tabulator-tables@4.5.3/dist/js/tabulator.min.js"></script>

**Working Example**
Normally I would include a JS Fiddle but if you can easily reproduce the issue on custom header filter in the examples. 
[http://tabulator.info/examples/4.5#filter-header](url)

Reproducing Steps
1. go to [http://tabulator.info/examples/4.5#filter-header](url)
2. Navigate your mouse to the Progress column
3. Type the number 1 into the min area and 10 into the max area (make sure to fill out both before proceeding)
4. When finished hit the enter key

Expected behavior
The table filters accordingly and only the rows that satisfy the filter appear. 

Actual behavior
The table will show the rows that satisfy the filter but then it immediately switches back to the state before the filter was used.

Clicking anywhere out of the input area fixes the filter. The problem is why does it behave this way for the keypresses.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Chrome
 - Version 79.0.3945.130

**Additional context**
In this defect [https://github.com/olifolkerd/tabulator/issues/2409,](url) you explained that "number editor only changes once the cursor leaves the input element". However, this still does not explain why the filters are reverting after hitting the enter key. 

I changed the keypress function to work on any keypress which did not solve the issue. 

I have been playing around with the code listed below and I cannot prevent the reverting from occurring. How do I prevent this or is this the standard behavior?

function keypress(e){
        if(e.keyCode == 13){
            buildValues();
        }

        if(e.keyCode == 27){
            cancel();
        }
    }

This issue could be a result of a lack of my understanding of how tabulator works. So any clarification would be very appreciative.

Also as a side question when using custom header filter functions do I have to use the success function to get the headerFilter and the headerFilterFunction to communicate.

**Comment by olifolkerd** [comment]
Hey @darkbdlz 

Thanks for the headsup,

I will get the example fixed for the 4.6 documentation update.

Cheers

Oli :)

**Comment by darkbdlz** [comment]
@olifolkerd Thanks for fixing the documentation. 
My ticket used the documentation as an example but my issue is with the keypresses not working correctly. 

Is the code behaving as intended where a keypress filters the rows then un-filters the tables right afterward? 

Also, I added some more details in the  **Additional context** section of the ticket. Could you please answer my questions listed in there.

**Comment by olifolkerd** [comment]
This was due to the custom filter function returning false instead of true when one of the filters was empty.

I have updated the docs and will push these live this evening with the 4.6 release.

Cheers

Oli :)
