### ISSUE TITLE
Business model / backing

### ISSUE THREAD

**Issue by michaelongithub** [olifolkerd/tabulator#264]
Hi Oli
we are considering using tabulator in general for our web apps (we are just a small firm) because its level of abstraction for programming and features is to our liking. It is not a question of money that we probably prefer it to something like a synchfusion js gird, or others  which are very complete but require that on uses a relatively complex to high level api, that we want to aviod.

So choosing tabulator is mainly the investment / commitment to have application code dependent on such a decision. 

So we would like to ask you some questions / opinions / reqirements about going "professional / paying" with your tabulator. But GitHub is maybe not the place to do that. So is there an other way to contact You ? Or contrarily do You want that to be done here ?
Regards Michael

**Comment by olifolkerd** [comment]
Hey Michael,

You can reach me on oliver.folkerd@gmail.com if you want to discuss anything.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hi Michael,

Thanks for getting in touch

At the moment I am creating Tabulator as a chance to give back to the coding community and as a personal project to work on.  There is no backing and I am not looking to launch Tabulator as a commercial entity, it is there to provide free access for anyone to an easy to use table generation system.

I do indeed plan to move to a more modular system, and the version 3 release in a few months time will be moving away from jQuery dependency to a stand alone library.

In terms of resources I am always happy for people to collaborate through the repo and pull requests are welcome, though I will only accept substantial changes to the code base if they are agreed in advance and fit in with my roadmap.

Thanks for getting in touch.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hi Michael,

I should also add to my previous message, that i am always expanding Tabulator, and have a new release out roughly every month.

The feature set of Tabulator is largely driven by the requests of its users, so if there are any features you would like to see please create an issue and i would be happy to add them to the road map.

Most requested features are added within 1 or 2 months.

As part of version 3 the rendering system will be getting a complete overhaul to make it much more efficient in every respect, so most performance issues will be revolved then. I am holding off on making this change until i have the last few user requested features in so i have a stable codebase before i begin the refactoring into a modular system.

Cheers

Oli

**Comment by michaelongithub** [comment]
Thanks a lot for all that info, Cheers Michael
