### ISSUE TITLE
Link formatter - no link?

### ISSUE THREAD

**Issue by minceheid** [olifolkerd/tabulator#2640]
The link formatter is a great way of presenting a configurable hyperlink, and I'm using a function to customise that link according to the cell contents. However - in some circumstances, it may be useful for a link to explicitly *not* be provided (in my case, only certain values can be associated with a link).

This suggestion is that if the link formatter function returns a null/empty value that the cell contents are not formatted with a hyperlink. I've sort of worked around this by returning "javascript:void(0)" for the the hyperlink, but isn't very tidy for the user experience.

**Comment by olifolkerd** [comment]
Hey @minceheid 

Please create a JS Fiddle that outlines you usage case.

Cheers

Oli :)
