### ISSUE TITLE
findTable() can return Array.length == 1

### ISSUE THREAD

**Issue by roxuss** [olifolkerd/tabulator#2641]
```
Tabulator.prototype.findTable = function (query) {
    var results = Tabulator.prototype.comms.lookupTable(query, true);
    return Array.isArray(results) && !results.length ? false : results;
};
```
Documentation says :

> If no match is found it will return false, if one table is found it will return the Tabulator object for that table. If multiple tables are found it will return an array of all matching Tabulator objects.

So code doesnt match documentation. Which should it be tho ? Docs change, or code change ?

Tabulator 4.5.3

**Comment by olifolkerd** [comment]
Hey @roxuss 

Thanks for the info. looks like the documentation is out of date. 

I will update it for the 4.6 release.

Cheers

Oli :)
