### ISSUE TITLE
issue with fitdata when in use with bulma.

### ISSUE THREAD

**Issue by srankgit** [olifolkerd/tabulator#2644]
**Describe the bug**
When using tabulator in conjunction with Bulma,   for some reason the  layout "fitdata" is not fully respected and part of the header ( line ) expand to fit parent. 

I am afraid i am newby in bulma and tabulator. so maybe i am missing an obvious point. Sorry if it is the case.

kr.

**Tabulator Info**
4.5.3 
( was in 4.3.5 with same problem)

**Working Example**
https://codepen.io/srank/pen/oNXWXGo

**To Reproduce**
1. Go to https://codepen.io/srank/pen/oNXWXGo
2. See error

**Expected behavior**
i expect the header line to not expendant beyond the data

**Screenshots**

![headerexpand](https://user-images.githubusercontent.com/61547270/75448467-91295800-596b-11ea-870f-7c0be3d9fea1.png)

**Desktop (please complete the following information):**
any i know

**Smartphone (please complete the following information):**
any i know

**Comment by olifolkerd** [comment]
Hey @srankgit 

The table is a block level element, so it is width is set to 100% of the containing element. The fitData layout mode only affects the columns not the table itself.

Cheers

Oli :)

**Comment by srankgit** [comment]
hello, Thanks for answering. still I dont understand with the header line expand to the full width  and not stay on compact width.  (and why only this header line and not all row lines for ex) is there any way to prevent it ?

**Comment by olifolkerd** [comment]
It isnt the header line, it is the entitre table.

It is just that in this theme the header only has an underline so it looks a bit odd.

If you set a fixed width on the table to the width of the data it will resolve this.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @srankgit 

You will be happy to hear i have just pushed an update to the 4.7 branch that adds a new layout mode that will allow the table to only take up the width of the columns it contains.

```js
var table = new Tabulator("#example-table", {
    layout:"fitDataTable",
});
```

The 4.7 branch will be released some time in May.

Cheers

Oli :)

**Comment by srankgit** [comment]
hello there, , the fitdataTable is very much appreciated and does solve the problem above, but there is a new issue with regards to bulma and responsive. Use in conjunction with bulma the navigation scrollbars are not visible when table part of the table is out of screen. 
I have updated the codepen https://codepen.io/srank/pen/oNXWXGo 

Without bulma scroll bar does show with fitdatatable in some case and in at least one case does not. 

not really sure if issue is in tabulator, or bulma or its just expected behavior. In my case its a problem.

if i could force to show the scrollbar via javascript maybe i could lprobably live with  it.

thanks for eveything.

![2020-06-28 18_59_30-A Pen by sr](https://user-images.githubusercontent.com/61547270/85954218-28cca080-b976-11ea-8948-2679bf839515.png)
![2020-06-28 18_59_45-A Pen by sr](https://user-images.githubusercontent.com/61547270/85954219-29653700-b976-11ea-88cf-69744c5489cd.png)

**Comment by olifolkerd** [comment]
Hey @srankgit 

Could you create a second issue for this, as it is certainly something that i can look into, but it is unrelated to this now closed issue.

Cheers

Oli
