### ISSUE TITLE
How can I create a custom link formatter in React?

### ISSUE THREAD

**Issue by 8483** [olifolkerd/tabulator#2645]
Alright, I am aware that [react-tabulator](https://github.com/ngduc/react-tabulator/issues/135) exists, I asked a question there, with no answer.

Here is a [codesandbox with the example](https://github.com/ngduc/react-tabulator/issues/135).

I wanted to ask here, as the code should work in theory. I can create a regular link (second column), but **I don't know why the React Link component is not displayed** (first column).

I got this answer on [stackoverflow for the possible cause](https://github.com/ngduc/react-tabulator/issues/135#issuecomment-548614082).

**Your library is kick-ass, and solving this issue would make me ecstatic!**

Here is the code:

```javascript
import React, { useState, useEffect, useRef } from "react";
import { Link } from "react-router-dom";

import Tabulator from "tabulator-tables";
import "tabulator-tables/dist/css/tabulator.min.css";

function Journals() {
  const [journals, setJournals] = useState([]);

  let refJournalsTable = useRef(null);
  let journalsTable = useRef(null);

  useEffect(() => {
    fetch("http://localhost:4000/journals")
      .then(res => res.json())
      .then(data => {
        let dummy = [
          {
            id: 1,
            journalKey: "1912340000001",
            journalTypeId: 1,
            journalDate: "2019-10-14"
          },
          {
            id: 2,
            journalKey: "1912340000002",
            journalTypeId: 2,
            journalDate: "2019-10-20"
          }
        ];
        setJournals(dummy);
      })
      .catch(err => err);

    journalsTable.current = new Tabulator(refJournalsTable.current, {
      height: "100%",
      layout: "fitColumns",
      columns: [
        {
          title: "Journal NOT",
          field: "journalKey",
          formatter: cell => (
            <Link to={`/journals/${cell.getValue()}`}>{cell.getValue()}</Link>
          )
        },
        {
          title: "Journal OK",
          field: "journalKey",
          formatter: "link",
          formatterParams: {
            url: cell => {
              return "/journals/" + cell.getValue();
            }
          }
        },
        { title: "Date", field: "journalDate" }
      ]
    });
  }, []);

  // Updates the tabulator table on item change
  useEffect(() => {
    journalsTable.current.replaceData(journals);
  }, [journals]);

  return (
    <div>
      <h1>Journals</h1>
      <div className="foo" ref={refJournalsTable} />
    </div>
  );
}

export default Journals;
```

**Comment by olifolkerd** [comment]
Hey @8483 

Thanks for your kind words, it is always great to hear that Tabulator is appreciated.

Im afraid i cant offer any framework specific guidance as im not a React Developer myself, though there is a react wrapper for Tabulator which i can see you have been looking at.

They would be the best people to ask on this matter, it will be down to the way the React framework works, it will likely parse the DOM on load so any element added after that are not converted into react components. There is likely a function you can call to trigger a redraw of the DOM.

Cheers

Oli :)
