### ISSUE TITLE
Support excel formulas with SheetJS on xlsx download

### ISSUE THREAD

**Issue by rotht2** [olifolkerd/tabulator#2648]
*Is your feature request related to a problem? Please describe.**
My current problem is that after exporting to xlsx i would like to allow users to change cell values and see the total update automatically with excel formulas.

**Describe the solution you'd like**
Provide a formatter that allows SheetJS to parse the value of a cell into a formula. (SheetJS does this already if the cell object value is an array. It assumes that the first index array[1] is the formula)

Today I can provide an array but the formatter calls JSON.Stringify on it inside of download.js. My proposed fix is to check to see if this is an array object and if so pass that array right along to SheetJS.
`rowData.push(!(value instanceof Date) && typeof value === "object" ? JSON.stringify(value) : value);`

proposed solution:
`if(Array.isArray(value)){
     rowData.push(value);
 }
else{
    rowData.push(!(value instanceof Date) && typeof value === "object" ? JSON.stringify(value) : value);
}`

**Describe alternatives you've considered**

**Additional context**

**Comment by olifolkerd** [comment]
This could be a great addition, but the system still needs to be able to handle arrays being passed into the excel spreadsheet that arn't intended to be interpreted as formulas

If you can come up with a solution that allows both options i would be happy to accept a PR.

Cheers

Oli :)

**Comment by rotht2** [comment]
This solution would pass the responsibility to turn arrays into strings up to the users formatter. So if a user would want an array passed to excel they would have to convert it to a string themselves instead of relying on tabulator to do it. 

Outside of that my other thought was that we would need to create some kind of formula interpreter that we would need to run all strings through to see if the cell contents look like a formula. That almost has the flip side of the problem where 1+2 is desired as a string "1+2" instead of 3.

I went with option 1 because it allows the user to be in control if they want something different

**Comment by olifolkerd** [comment]
Hey @rotht2 

How are things going,

I would like to come to a conclusion on this issue soon if we can.

As i mentioned in the pull request, i would not be looking to change the existing functionality as from experience the vast majority of users use the download function to simply export their table data to a table without any additional functionality.

If you want this functionality to be available then we would need to a config option to allow the downloaded to know when to parse things to functions. This would be a configuration option that was added, not default behaviour.

As this is a reasonably niche usage case i would be looking for a PR to add this functionality to Tabulator as i have other more pressing areas to focus on.

If this is no longer something of use to you then please let me know and i can close this issue.

Cheers

Oli :)

**Comment by rotht2** [comment]
Hey Oli,

Life's been busy recently and I have not had a lot of extra time to sink my teeth into updating this PR. I also need to update my application to add the new config value. This is still useful to us but I am unsure when I will get the time to start hammering away at this. 

If you are looking to close some outstanding issues I can always create a new issue ticket when I have your suggested changes applied. 

Best,

Tyler

**Comment by olifolkerd** [comment]
Hey @rotht2 

No probs, i will leave it with you, let me know if you have any ideas,

Cheers

Oli :)
