### ISSUE TITLE
Tabulator and ContextMenu.js compatibility bug

### ISSUE THREAD

**Issue by giplusplus** [olifolkerd/tabulator#2649]
**Describe the bug**
Creating on-the-fly ContextMenu.js context menu on headerContext callback, needs double right click on the header for the menu to be displayed

**Tabulator Info**
Tabulator version 4.5.3

**Working Example**
https://codepen.io/giplusplus/pen/mdJrjqw

**To Reproduce**
1. Right Click on "Name" column header (callback function is called but no context menu is displayed)
2. Right Click again on "Name" column header (context menu is correctly displayed)

**Expected behavior**
The context menu should appear on first right click on the column header

**Screenshots**
NONE

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox / Google Chrome 
 - Version: 73.0.1 / 77

**Comment by olifolkerd** [comment]
Hey @giplusplus 

Built in context menus will be coming in the 4.6 release next weekend :)

Cheers

Oli :)
