### ISSUE TITLE
Persistence of Columns with Dynamic Values

### ISSUE THREAD

**Issue by emarti20** [olifolkerd/tabulator#2650]
**Describe the bug**
In 4.4 I was using cookies for persistence storage of columns.  Today I switched to v4.5 and found that cookie storage isn't currently working as expected (#2598).  I'm populating a select for a column that pulls the values into the variable via an ajax call using the tableBuilding callback.  This issue also exists using a static list as well which is used in the example.  After the first load of the grid the values are stored in local storage and no changes will be detected going forward.

**Tabulator Info**
- Version 4.5.3

**Working Example**
https://jsfiddle.net/emarti20/svmugh50/19/

**To Reproduce**
1. Click on the website column for either row and you'll see the entries in the websites object on line 3.
2.  Change one of the websites in the object to something not there, or add an additional one.
3.  Click Run
4.  Click on the website column for either row and you'll see the original list of websites.  Your change to the values is not reflected.
5.  If you delete the local storage and click run again you'll see the new value.

**Expected behavior**
I would expect this to work as it did in v4.4.  I'm not sure if this is different storage behavior with local vs cookie or a v4.5 change.  Looking at the local storage data the problem appears to be that the values entries are stored as part of the column definition data.  When the variable changes it is ignored and the list stored in local storage is used instead.  My actual use case of using ajax calls in the tableBuilding callback make this especially problematic.

![image](https://user-images.githubusercontent.com/18401318/76129308-f8728800-5fbb-11ea-98ab-59f927a1b237.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version:  80.0.3987.132

**Comment by olifolkerd** [comment]
Hey @emarti20 

Im afraid i dont follow you there, the persistence in your example is behaving as expected.

I would also say that your example does not use cookie storage, given the setup of that table it is using localStorage instead which is the default behaviour and definitely the recommended practice.

I think you may have misunderstood the column persistence functionality. It is only there to persist the column setup, it has nothing to do with persisting data in the table. If you wish to persist table data locally you will need to handle that yourself.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Having looked into this further, when cookie  mode is enabled there is an error, i have pushed a fix for this to the 4.6 branch which will be released later this weekend.

Cheers

Oli :)
