### ISSUE TITLE
Child rows API for update / insert / delete

### ISSUE THREAD

**Issue by michaelongithub** [olifolkerd/tabulator#2651]
*Is your feature request related to a problem? Please describe.**
According to doc and a number of issues this is not the case.  Leads to clumsy workarounds and not clear if these work in all situations needed

**Describe the solution you'd like**
 extend Row Component API to extend for child rows or provide Child Row component with API for insert / update / delete.

**Describe alternatives you've considered**
Provide doc How To how to handle insert / update / delete children in Doc.

**Additional context**

**Comment by olifolkerd** [comment]
Hey @michaelongithub 

Great suggestion, i will add this to the roadmap for the 4.7 release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @michaelongithub 


I have pushed this feature to the 4.7 branch that i am hoping to release soon.

There is a new ***addTreeChild*** function on the row component that lets you insert rows.

You can already update the data of a row using the ***updateData*** function on the row component.

I have updated the ***delete**** function on the row component to handle child rows and update the parents expansion status on row deletion and delete child rows if a parent is deleted.

Cheers

Oli :)

**Comment by michaelongithub** [comment]
Hi Oli
really great, thanks a lot

Cheers
