### ISSUE TITLE
Option/Question : Download Only selected rows

### ISSUE THREAD

**Issue by AEK-BKF** [olifolkerd/tabulator#2653]
Hi,
Thank you so much for this great package,
I tried to find out how to export only selected rows but I think there isn't an option for that.
If so, it's useful to add this option for download feature.

Thanks.

**Comment by olifolkerd** [comment]
This feature is coming in the 4.6 release later this month,

Cheers

Oli :)

**Comment by AEK-BKF** [comment]
Any news ?

**Comment by olifolkerd** [comment]
Hey @AEK-BKF 

Sorry, i had totally got muddled with what you had asked for there, that feature is available on the print and clipboard exports, but not on the downloaders.

I will add that to the roadmap for the 4,7 release.

Sorry for the mixup there.

Cheers

Oli :)

**Comment by AEK-BKF** [comment]
Thank you so much !
I'm waiting for it :)  Good luck

**Comment by neffnj87** [comment]
Would it be possible to export only a specified column from those selected rows? I've been trying to do it with JQuery or add it to the library, but my JavaScript skills just aren't good enough to get it there.

To better illustrate what I'm looking for here is a link to a working angular site with a tabulator table listing some servers `https://github.com/neffnj87/sample-angular-tabulatorsite` what I'd like to be able to do is export to clipboard only the 'login' column from the selected rows into the clipboard. Once I have it doing more of what I'm looking for I'd like to put up a few working angular projects for examples to help other new users (like myself) get going faster.

**Comment by olifolkerd** [comment]
Hey @AEK-BKF 

The download module has been rebuilt for the 4.7 release to be based on the output of the export module. which will resolve this issue.

Version 4.7 will be released in the next couple of weeks.

Cheers

Oli :)
