### ISSUE TITLE
Height required for dataTree, local pagination, and rowselection

### ISSUE THREAD

**Issue by jmeberst** [olifolkerd/tabulator#2654]
**Describe the bug**
When using dataTree, local pagination, and row selection height is a required field like it was in 3.3

**Tabulator Info**
- Which version of Tabulator are you using?
4.5.3

**Working Example**
YOU MUST include a link to a JS Fiddle or Codepen that demonstrates the problem, it is very hard to diagnose an issue from a simple description.
https://codesandbox.io/s/tabulator-tables-sandbox-uvw1u

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Select the second child row in any parent
2. Change the page
3. Return to the first page.
4. The row you selected is the last visible child of that parent.
5. Collapsing and expanding the parent throws an error

**Expected behavior**
previous child rows should be visible, expanding and collapsing parents should not result in an error.

**Desktop (please complete the following information):**
 - OS: [win10]
 - Browser [chrome]
 - Version [80]

**Additional context**
Adding the height property solves the issue

**Comment by olifolkerd** [comment]
This should be resolved in the updates with the 4.6 release later this month :)
