### ISSUE TITLE
Columns grouping issue

### ISSUE THREAD

**Issue by fzorin** [olifolkerd/tabulator#2655]
**Describe the bug**
There is issue with column alignment if there are more than 2 level of grouped columns

**Tabulator Info**
4.5.3

**Working Example**
https://jsfiddle.net/0v9qtxen/1/

**To Reproduce**
Run snippet and check columns alignments

**Expected behavior**
Align columns with accordance width of all nested levels. See screenshots

**Screenshots**
Now
![image](https://user-images.githubusercontent.com/47669551/76616012-2b74c880-6534-11ea-95ea-468f00d803f8.png)

After fix
![image](https://user-images.githubusercontent.com/47669551/76615903-fb2d2a00-6533-11ea-98ee-ea1d9fbd56a2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 and Ubuntu
 - Browser: chrome
 - Version: 80

**Comment by olifolkerd** [comment]
Hey @fzorin 

Are you proposing that you have a fix for this? if so please submit a PR,

Cheers

Oli :)

**Comment by fzorin** [comment]
Hi @olifolkerd, 
No,I don't have a fix. On screenshot there is just expectation.

**Comment by olifolkerd** [comment]
Hey @fzorin 

I am a bit confused, in your example you appear to be using nested groups but with only one column in, why is this?

I will have a look into this for the next release.

Cheers

Oli :)

**Comment by fzorin** [comment]
@olifolkerd ,
It was the first case which I faced with this issue. But it reproducible with more than one column in nested group.

https://jsfiddle.net/q19cwz70/
![image](https://user-images.githubusercontent.com/47669551/77283847-61594000-6cde-11ea-8e0d-6fc3b5cde835.png)

Best regards

**Comment by olifolkerd** [comment]
Hey @fzorin 

Thanks for the information. I had actually fixed this issue for single level grouping, but forgot to check that the fix propagated up for nested groups.

I have pushed a fix for this to the 4.6 branch which will be released later this weekend.

Cheers

Oli :)
