### ISSUE TITLE
Pagination size is not properly calculated

### ISSUE THREAD

**Issue by schmidty1913** [olifolkerd/tabulator#2656]
**Describe the bug**
Tabulator 4.2.7

When loading a table the pagination size is not properly calculated.
It seems like the issue is due to the tabulator_bootstrap4 css
I think the issue is in the formatting of the table using bootstrap It changes the height of the rows and that is not accounted for?

If I change tabulator line 19285 
`(self.size = self.table.options.paginationSize || Math.floor(self.table.rowManager.getElement().clientHeight / 24);`
to 
`self.size = self.table.options.paginationSize || Math.floor(self.table.rowManager.getElement().clientHeight / 50);`

It works as intended

**Screenshots**

Regular code with 24

![image](https://user-images.githubusercontent.com/24723142/76689732-e1104c00-6606-11ea-8c38-c6176cdbddc6.png)

Changed code with 50

![image](https://user-images.githubusercontent.com/24723142/76689764-34829a00-6607-11ea-98f9-5f81ecb1f357.png)

**Comment by olifolkerd** [comment]
Hey @schmidty1913 

Thanks for the info, that definitly looks like a bug, it shouldnt be using a fixed number to work out page size.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @schmidty1913 

I have pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)
