### ISSUE TITLE
movableRows being duplicated with Column Group headers

### ISSUE THREAD

**Issue by lac616** [olifolkerd/tabulator#266]
There appears to be a problem using movableRows with headers that have multiple rows (column groups). I created a JSFiddle to show: https://jsfiddle.net/tufpgpdb/6/

The row handle is being duplicated for each column group.

In addition, try setting "frozen: true" on the first column option You will see all duplicates are up front.

Let me know if you need further info!

**Comment by olifolkerd** [comment]
Hey,

Thanks for the fiddle, i will stick some data in that and see what happens.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey,

Just a quick note to let you know that this issue will be fixed in the upcoming 3.0 release later in May!

Cheers

Oli

**Comment by lac616** [comment]
Great! The more I work with this control, the more I'm impressed with its
features!

**Comment by olifolkerd** [comment]
Hey,

You will be happy to hear that version 3.0 is now in beta release, and should address the issues you were having.

Head over to http://olifolkerd.github.io/tabulator/news/ to see the latest features!

Cheers

Oli

**Comment by lac616** [comment]
Thank you but it appears the movableRowHandle has been removed altogether? Is there a way we can do grouping and have a handle? Otherwise there is no signal to the user that the row is indeed movable.

**Comment by olifolkerd** [comment]
I see your point, i will look at reinstating the handle this weekend

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey,

I have added the new ***rowHandle*** column definition property and ***handle*** formatter  to give people more control on where and how to format their row handles.

```js
$('#example-table'),tabulator({
    movableRows: true, //enable user movable rows
    columns:[
        {rowHandle:true, formatter:"handle", frozen:true, width:30, minWidth:30},
        {title:"name", field:"name"} //normal column
    ]
});
```

Full documentation and examples can be found [here](http://olifolkerd.github.io/tabulator/docs/3.0/#movable)

Let me know if that works for you.

Cheers

Oli

**Comment by lac616** [comment]
Hi Oli,

I finally had a chance to review this. The handle now appears which is great. Here are two things that are causing me issues:

1) The "rowMoved" event now has the row component only as a parameter. How do I get the new position of the row?  The 2.2 version had a new position index as parameter. Is there a way I can get this info from the row component? Please note: this is _different_ from from the getIndex() method of the row, which is the index defined for the grid, and I have that set to a primary key in my data. I need the new position (ie, from row 20 to row 3 in grid).

2) The functionality breaks when rows are grouped. I receive this message: 
![capture](https://user-images.githubusercontent.com/27359692/27144547-516f22b0-5100-11e7-8e15-41108aa149b3.PNG)

Thanks!

**Comment by lac616** [comment]
Hi Oli!

After being moved to another project for a bit, I'm finally back on my project that uses tabulator. I have updated the control to 3.2 version. However, my last set of comments on this issue are still a problem. The extensions object is null when rows are grouped and causes the error noted in my screenshot. Also, I would need the new row index so that I can update the database with the new RowOrder for the object in the row.

Let me know if you have any questions!

Laura

**Comment by olifolkerd** [comment]
Hey,

Sorry for the delay in getting back to you, i must have missed your previous comment.

I have just pushed a fix to the master branch that will address the error you were having.

As for the row index, how would you imagine that working in group situation, would it be the index of the row in the group or the table as a whole.

Cheers

Oli

**Comment by lac616** [comment]
Thanks Oli,

For the row index, I believe that either would work fine, but if I had a preference it would be the index of the row in the group. 

Laura

**Comment by lac616** [comment]
Hey Oli,

Have you had opportunity to think about this? It's the one bit that my testers keep asking about so that they can prioritize which items in the grid they want to see at the top. Basically, I just need to know if there is a way I can determine the _new_ row position/index within the rowMoved event. I'm saving the sort order of the items back to the database so that they remain persistent regardless of browser or device. 

Thanks!!

**Comment by olifolkerd** [comment]
As a temporary work around i would suggest something like the following:
```js
$("#example-table").tabulator({
    rowMoved:function(row){
        //row - row component
        var rows = $("#example-table").tabulator("getRows");
        var index = rows.indexOf(row);
    }
});
```

in the grouped scenario you could get all the groups from the ***dataGrouped*** callback, iterate through each group calling the ***getRows*** function and getting the index of the row with in that group.

Cheers

Oli
