### ISSUE TITLE
Forced reflow while executing javascript.

### ISSUE THREAD

**Issue by dbauszus-glx** [olifolkerd/tabulator#2661]
Whenever tabulator redraws there are forced reflow warnings in the Chrome developer performance tab.

I am not sure whether there is anything which can actually be done about this. I assume that rows are drawn one by one. But I also tried to create a tabulator object in a dom element which is not yet added to the document. Once the dom element is drawn I can see the forced reflow warnings.

I assume this is caused by tabulator needing to observe the size of the container to calculate the number of rows to draw.

Sorry if I cannot provide more detailed information as I don't exactly know how tabulator internally works.

It's not a big issue anyways but maybe this may be of help to you going forward with tabulator.

Thanks for all the great work with tabulator.

**Comment by olifolkerd** [comment]
On the whole these warnings are not a problem and should only occur from time to time if the table redraw is triggered repeatedly in a short period.

If you are seeing these often could you create a JS Fiddle that demonstrates the table configuration you are using so i can look into it further.

Cheers

Oli :)
