### ISSUE TITLE
Using international keyboards with a comma for a decimal point

### ISSUE THREAD

**Issue by alistairalderson** [olifolkerd/tabulator#2663]
When using a keyboard set to a European country where a comma is used as a decimal point, decimals entered with the "decimal" validator show invalid due to the comma.  Is there a work around or fix for this.  Setting the locale appears only to affect the column titles.

Many thanks in advance.

**Comment by olifolkerd** [comment]
Hey @alistairalderson 

For the moment the best option would be to use a [Custom Validator](http://tabulator.info/docs/4.5/validate#func-custom)

But you make a very valid point there, i will add it to the 4.7 release to make that validator more globally useful.

Cheers

Oli :)

**Comment by alistairalderson** [comment]
Many thanks @olifolkerd 

That would be great as Tabulator is a great piece of work.

I have added an ugly Regex to a Custom Validator to get it working as I have European users testing data input and they do not like moving away from the numeric pad.

function successFunc() {
            // Filter out the EU decimal (comma) and replace with a conventional decimal point
            var v  = editor.value.replace(/[,.]/g, function (x) { return x == "," ? "." : "."; });
            success(v);
        }

Regards,

Alistair

**Comment by olifolkerd** [comment]
Hey @alistairalderson 

Thinking on this further i will be leaving the validators as they currently are.

The ***integer***, ***float*** and ***numeric*** validators all use the build in JavaScript functions of `NaN`,  `isFinite`  and the `Math` object. all of which provide a precise way of determining the validity of a number.

And a valid floating point number in the programming sense only uses a period as a decimal point, if they were to be validated as numbers while using the comma, the sort for a numeric column would then be broken as the value would be sorted as a string not a number.

As a developer that has to work with this, how do you usually handle the conversion from a comma delimited number to something that you can actually process?

Cheers

Oli :)
