### ISSUE TITLE
Possible bug scrollToRow lo last elements of data

### ISSUE THREAD

**Issue by kalallit** [olifolkerd/tabulator#2665]
When I try to scroll for example to the last row of the data and I make an arrow up to the first row and back down with the arrow down, a navigation problem arises, the scroll does not follow the navigated row.
In this example: 
- Press "enter to go last Row"
- Click for example on name last row,
- Arrow up to the first row
- Arrow down
- The problem appears
https://codepen.io/kalallit/pen/ExjRpde
If you need additional clarification do not hesitate to ask.
Tabulator version: 4.5.3
Browser: Chrome
Thanks

**Comment by olifolkerd** [comment]
Hey @kalallit 

Im unsure of your issue. there is no way for row 35 in your example to scroll to the top of the table, tabulator dosnt allow for empty space below a row in the table, so it can only scroll that row to the bottom edge of the table.

Cheers

Oli :)

**Comment by kalallit** [comment]
I think you didn't understand the problem well. I'm sorry maybe I didn't explain myself in the best way. So, when we click on the first line and press enter we go to the last line. We click on the last line to have the focus and we return through the up arrow to the first line, if we go down with the arrow we will lose the focus of the line. can you try these in my example? Thanks
https://drive.google.com/file/d/1C7mysXAbVoYnp128LPYzXRSBd9zIAscY/view?usp=sharing
