### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by Nazar84** [olifolkerd/tabulator#2667]
on the page http://tabulator.info/docs/4.5/tree#structure you have the typo:

![_](https://user-images.githubusercontent.com/56727082/77070494-ffa18900-69f2-11ea-9578-64105476df92.jpg)

**Comment by olifolkerd** [comment]
Hey @Nazar84 

Thanks for the heads up,

I will include a fix in the website update for the 4.6 release next weekend.

Cheers

Oli :)
