### ISSUE TITLE
Column width increases on resize handler double click

### ISSUE THREAD

**Issue by iursevla** [olifolkerd/tabulator#2668]
**Describe the bug**
When a column is resizable, on double click on it's own resize handle the column will resize and increase it's width **by 1 pixel.**

**Tabulator Info**
- **v4.5.1**

**Working Example**
[Fiddle where this bug is shown](https://jsfiddle.net/p087a6xc/ ), although that fiddle isn't mine and it's on an older version (v4.1.2) we are able to replicate the bug.

**To Reproduce**
1. Create a tabulator table and allow the columns to be resizable
2. Double Click on resize handle of resizable column
3. See that it's widht increases by 1 pixel

**Expected behavior**
On double click it shouldn't increase by 1 pixel or some logic could be applied to the double click action (e.g. increase to max-witdh, etc).

**Desktop (please complete the following information):**
 - Browser Chrome v80.0.3987.132

**Additional context**
I navigated through the codebase and the place where the width is being changed:

https://github.com/olifolkerd/tabulator/blob/29091ad32672438a4e6e398ce99d8c3b2169fb0c/src/js/column.js#L1211

**Comment by olifolkerd** [comment]
Hey @iursevla 

Thanks for getting in touch, I will have a look into fixing that for the next release.

Cheers

Oli :)

**Comment by iursevla** [comment]
Hi @olifolkerd,

Thanks for the quick reply. 

Relative to the following:

> ...l or some logic could be applied to the double click action (e.g. increase to max-witdh, etc).

Do you think I should create a **Feature request** about the possibility of the double click on the resize handle to have some callback?

**Comment by olifolkerd** [comment]
Hey @iursevla 

This is not actually an issue any more, that is only present because the demo is running on very old code. If you update to version 4.5.3 then the issue isnt present any longer.

Cheers

Oli :)
