### ISSUE TITLE
Uncaught ReferenceError: tableData is not defined

### ISSUE THREAD

**Issue by mishagin-tim** [olifolkerd/tabulator#2669]
**Website Page**
http://tabulator.info/docs/4.5/columns

**Description**
In the example of "Automatic Column Generation" there is a 'tabledata' variable is initialized but where the code of **table** generation is written there is a 'table**D**ata' is used (with capital D), so this error is being thrown. 

**Possible Solution**
Replace  'tabledata' with 'tableData'
**Or**
Replace 'tableData' with 'tabledata'

**Comment by olifolkerd** [comment]
Hey @mishagin-tim 

Thanks for the headsup, i will fix that in the 4.6 site update later this weekend.

Cheers

Oli :)
