### ISSUE TITLE
Tabulator for Tabbed Panels

### ISSUE THREAD

**Issue by TAMIZsn** [olifolkerd/tabulator#267]
Hi,
 First of all thanks for your tabulator website. 
My question...How to use tabulator for **tabbed panels** ...?

**Comment by Paraplegix** [comment]
When you talk about tabbed panels, you are refering at some functionnality like [bootstrap's Tabs ](http://getbootstrap.com/javascript/#tabs)? 

If so you just have to call `.tabulator("redraw", true)` when the table div is visible on screen and it can expand.

**Comment by TAMIZsn** [comment]
But i want different  tabulator , for both panels (Tabbed Panel).

**Comment by TAMIZsn** [comment]
Thank u for Reply.But i want different tabulator for Both(tabbed)
panels..(unique tabulator)

**Comment by Paraplegix** [comment]
https://jsfiddle.net/7hxejjbb/6/

Here is a functionnal example, i hope it is more clear about what you have to do

You might have to adapt depending on how the user change the tab in your webpage
