### ISSUE TITLE
Placeholder-height problem, if height:"auto" is in use, with no elements

### ISSUE THREAD

**Issue by exetico** [olifolkerd/tabulator#2670]
**Describe the bug**
There not space for the placeholder to be shown, if i'm using `height:"auto"` at the same time.

The `tabulator-tableHolder` is cutting the `tabulator-placeholder` element.

If i add a fixed height, it's works as expected.

**Tabulator Info**
I'm running the latest version (4.5.3), but i've tried old versions, too.

**Example**
https://codepen.io/exetico/pen/ZEGqwrV

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Setup table, with `height:"auto"`, and a placeholder.
2. Initiate with no data
3. Check the height of tabulator-tableHolder

**Expected behavior**
Secure that the placeholder has proper space, to show the content. That's what i'm expecting, if i use `height:"auto"`.

**Screenshots**
![image](https://user-images.githubusercontent.com/3549445/77515627-24758080-6e79-11ea-8958-daf055ffcb15.png)
![image](https://user-images.githubusercontent.com/3549445/77515720-5850a600-6e79-11ea-83e6-fae42bb3e0e5.png)

_And as always, thanks you, for making Tabulator. I hope that you're prioritizing the family-life, in these days (I saw the sticky issue... but also COVID19)._

**Comment by olifolkerd** [comment]
Hey @exetico 

I have pushed a fix for this to the 4.6 branch, which will be released later this weekend.

Cheers

Oli :)

**Comment by exetico** [comment]
Great - and even better 👏

Thanks!
