### ISSUE TITLE
Custom Cell Formater seems to be broken

### ISSUE THREAD

**Issue by GigaJunky** [olifolkerd/tabulator#2671]
I got to work with 4.1.5 but nothing after that.

**Comment by olifolkerd** [comment]
It is hard to offer you advice without seeing what code you are using.

Please post a link to a code fiddle that demonstrates your issue.

Can you also provide a more detailed explanation of the problem you are facing. Vague posts make it impossible to offer advice. Do you see a console error, is anything being displayed in the cell?

There is an issue template for bug reporting that I suggest you have a look at as it will prompt you for all the information we need to help you.

Custom formatters are currently working in all the currently released version, you can see on the examples section of the website functional examples of custom formatters for each release. It is more likely that there is something in the custom formatter you are using that is not working as expected. If you post a like to a JS fiddle or code pen, we can point you in the right direction.

Cheers

Oli

**Comment by GigaJunky** [comment]
ok, sorry.. I got it to work 4.1.5 so I knew my code was working, but need some of the newer features also.  First time fiddle.. Hope I did it right.  Looks like there is a problem with the Sum on the bottom calc also which works in 1.5 also.
https://jsfiddle.net/L04jhcro/

**Comment by GigaJunky** [comment]
Found it!  It seems to be  autoColumns: true and also had defined columns.
