### ISSUE TITLE
Format bug in calc row when closing group

### ISSUE THREAD

**Issue by Phalanxare** [olifolkerd/tabulator#2672]
**Describe the bug**
When I close a group, the topCalc row format just break, it goes back to  normal when I use the scroll

**Tabulator Info**
- 4.5

**Screenshots**
![Capture1](https://user-images.githubusercontent.com/34352458/77655052-2cfdb200-6f72-11ea-8e7a-ef94267538af.PNG)
![unnamed](https://user-images.githubusercontent.com/34352458/77655047-2c651b80-6f72-11ea-8673-39dca44ba884.png)

**Desktop :**
 - OS: W10
 - Browser chrome

**Comment by olifolkerd** [comment]
Hey @Phalanxare 

It is important that you post a link to a JS Fiddle or Code Pen that demonstrates the issue, without it we have no way of knowing how your table is setup so no way to offer advice.

Initial testing my end seems to work correctly, but without knowing your table config i could not offer more help.

Please have a quick read of the [Bug Submission Guide](http://tabulator.info/community#bug) for some pointers on what is useful when reporting your issue.

Cheers

Oli :)
