### ISSUE TITLE
Can Tabulator be used with Functional Programming?

### ISSUE THREAD

**Issue by 8483** [olifolkerd/tabulator#2673]
I searched the documentation but couldn't find an example.

The idea is Tabulator to return the nodes, rather than attach to a node, if I'm making sense.  In other words, how can the table generation be a function that returns nodes.

Here's an [example for functional code](https://codesandbox.io/s/pedantic-varahamihira-gjwww)...

Now, how can I use Tabulator here?

The pattern for the app is similar to how React works.

Something like this maybe...

```javascript
function getTable(model) {

        let table = new Tabulator("#table", {  // <-------- Omitting this part (#id) causes an error
            reactiveData: true, //enable reactive data
            data: model.journals,
            height: "300px",
            layout: "fitColumns",
            columns: [
                { title: "id", field: "id"},
                { title: "title", field: "title" },
            ],
        });

        return table.getHtml();    // table.getNodes();
    }
```

**Comment by olifolkerd** [comment]
If you just want to get an html equivalent of the table then the ***getHTML*** table will already do this for you.

If you want the DOM node for the table itself, then you just have to define the table slightly differently:

```js

var tableEl = document.createElement("div");

let table = new Tabulator(tableEl , {  // pass table element into table constructor
    //table config goes here
});

```

I hope that helps,

Cheers

Oli :)
