### ISSUE TITLE
min/max in Header filter on progressbar column removes all rows

### ISSUE THREAD

**Issue by VanDerLars** [olifolkerd/tabulator#2674]
**Describe the bug**
_Scenario:_
- you have table with header-filter
- one column is a progressbar
- this column has a min- max- filter header

_Bug:_
- if you klick in to a filter textfield and leave it with no changes
- then all rows are filtered and hidden
- there's no way to bring them back

**Tabulator Info**
latest

**Working Example**
Your own example-page:
http://tabulator.info/examples/4.5?#filter-header

(same on local build)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by olifolkerd** [comment]
Hey @VanDerLars 

Thanks for the headsup, this was just an error with the custom filter function in the example.

I will update the documentation for the 4.6 release update

Cheers

Oli :)
