### ISSUE TITLE
Editable Column Title Callback Does Not Return As Expected

### ISSUE THREAD

**Issue by dragmecom** [olifolkerd/tabulator#2679]
**Describe the bug**
The callback for the editable column title does not return the documented variables, last two come back undefined (copy pasted from documentation)

**Tabulator Info**
Latest 

**Working Example**
https://jsfiddle.net/zcqj2p1a/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Open Console
2. Edit Any Header Title
3. See Output
4. See Error

**Expected behavior**
Should return all 3, returns object in first

**Desktop (please complete the following information):**
Chrome / MacOS

**Comment by dragmecom** [comment]
Ah! It's also a documentation error

[This is what I was going off of...](http://tabulator.info/docs/4.5/columns#edit-titles) but if you [look here it is documented how it actually responds (not how it is supposed to) ](http://tabulator.info/docs/4.5/callbacks#column), although likely still bug since I bet you wanted it to **return the new value, column changed, and full column array**.

**Comment by olifolkerd** [comment]
Hey @dragmecom 

Thanks for the headsup. i will update the docs in todays release update

This is a documentation issue only. The only thing that needs to be passed into the function is the column component, you can retrieve all other information from the component.

Cheers

Oli :)
