### ISSUE TITLE
Hide table until the filter is being used

### ISSUE THREAD

**Issue by askwpcoach** [olifolkerd/tabulator#268]
Hello,

I would like to hide the table until someone type into the filter text field. I have everything setup and working except when the js triggers the table to become visible, there are no data in the rows. 

For my css I am using:
.tabulator {
		display: none;
	}

For my JS I am using:
```js
function showGlobalsearch(elem){
	$('#filter-value').bind('keyup change',function(){
		if(this.value.length <= 0){
			document.getElementById('gst_price_filters').style.display = "none";
	  		document.getElementById('table').style.display = "block";	
		}else {
			document.getElementById('table').style.display = "none";
			document.getElementById('gst_price_filters').style.display = "block";
			document.getElementsByClassName('tabulator-table').style.display = "block";
		}
	});
}
```
Any help will be much appreciated...

Thanks

**Comment by olifolkerd** [comment]
Hey, 

The issue you are having is because you are trying to add data to the table when it is hidden, so it has no way to calculate the dimensions of the rows correctly.

you need to call the ***redraw*** function when the table becomes visible to make it display the data correctly:

```js
$("example-table").tabulator("redraw", true);
```

Let me know if that helps,

Cheers

Oli

**Comment by askwpcoach** [comment]
Hey,

Thanks for getting back to me, I apologize for the delayed reply. I made the adjustment as you suggested, but still running into an issue. Please see my js code below:

`
		$("#gst_price_filters").tabulator("setData", tabledata);

		/*$(window).resize(function(){
			$("#gst_price_filters").tabulator("redraw");
		});*/

	</script>
					<?php /*?><?php echo do_shortcode['[taxtrax id="4"]']; ?><?php */?>
					
					</div>
	</article>
	</div>
</div>
<script>
						function showGlobalsearch(elem){
							    $('#filter-value').bind('keyup change',function(){
								if(this.value.length <= 0){
									//$('#gst_price_filters').hide();
									document.getElementById('gst_price_filters').style.display = "none";
	  								document.getElementById('table').style.display = "block";
/*									$("#gst_price_filters").tabulator("hideCol","Animal");
									$("#gst_price_filters").tabulator("hideCol","Full Mount");*/
									
								}
								else {
									//$('#gst_price_filters').show();
									document.getElementById('table').style.display = "none";
									document.getElementById('gst_price_filters').style.display = "block";
									document.getElementsByClassName('tabulator-table').style.display = "block";
									$("#gst_price_filters").tabulator("setData", tabledata);

		$(window).resize(function(){
			$("#gst_price_filters").tabulator("redraw");
		});

								}
								});
							
      
						}
						`</script>``

Thanks,
Richard

**Comment by olifolkerd** [comment]
Hi Rich,

so there are a couple of bits to tweak,

The ***redaw*** function doesn't need to be in the resize binding (although it is worth having one of those on the body if your table is full width, so your function should now look like this:

```js
$("#gst_price_filters").tabulator("setData", tabledata);

function showGlobalsearch(elem){
    $('#filter-value').bind('keyup change',function(){
	if(this.value.length <= 0){								
		document.getElementById('gst_price_filters').style.display = "none";
		document.getElementById('table').style.display = "block";
	}else {
		document.getElementById('table').style.display = "none";
		document.getElementById('gst_price_filters').style.display = "block";
		document.getElementsByClassName('tabulator-table').style.display = "block";
		$("#gst_price_filters").tabulator("setData", tabledata);

		//redraw table when table is shown
		$("#gst_price_filters").tabulator("redraw");
	}
});

//redraw table if window size changes
$(window).resize(function(){
	$("#gst_price_filters").tabulator("redraw");
});
```

Can I ask why you are calling the ***setData*** function inside your *showGlobalsearch* function. are you changing the data that Tabulator is displaying? If not then there is no need to set the data again, if you are then as an alternative if you just load all your data into the table on the first load then you can use the ***setFilter*** function to filter the data inside Tabulator. Full documentation on this can be found [here](http://olifolkerd.github.io/tabulator/docs/#filtering).

Let me know if that helps.

Cheers

Oli
