### ISSUE TITLE
TitleEditor/TitleEditorParams? Documentation Expansion

### ISSUE THREAD

**Issue by dragmecom** [olifolkerd/tabulator#2680]
*Is your feature request related to a problem? Please describe.**

Goal : Add a "maxlength:10" to the TitleEditor which by default is "plaintext" _as set per the code if I understand correctly_.

_Perhaps this just my personal confusion (forgive me been on a long coding binge)_, 
but based on the [documentation](http://tabulator.info/docs/4.5/format) : 
`{title:5, field:"rating", titleFormatter:"star", titleFormatterParams:paramLookup}`

This allows for you to set your own formatter/editor for the header, instead of the automatic "plaintext"??? 

And allows for you to pass parameters via the  **titleFormatterParams**?

Is this supposed to be similar to **editorParams**? Because if it is, then is the behavior the same or was it supposed to be the same? ...or is that another bug?

I wasn't clear because the documentation did not cover how titleFormatterParams is expected to work the same way it did editorParams, and the naming makes you think it would/should act the same?

So wouldn't the titleFormatter set to "plaintext" (which is what it defaults to), then accept the following parameters like the **editorParams** does when **editor** is set to plaintext?

Example : 
`titleFormatterParams: {
                                elementAttributes:{
                                    maxlength:"10", //set the maximum character length of the input element to 10 characters
                                }
                            }`

Anyway in the end, I got pretty lost here in regards to documentation so I thought this may be a feature request just for greater clarity.

**Describe the solution you'd like**
Add "TitleEditor", "TitleEditorParams" which would work identically to "editor" and "editorParams" 

...unless of course, "titleFormatter" and "titleFormatterParams" were supposed to be the equivalent, in either case, please update the documentation here because I could not really make out the difference here.

**Describe alternatives you've considered**
I just hack jobbed it, loaded a text field with a maxlength and upon blur used the current `column.updateDefinition({title:"Updated Title"})` to update the value upon blur, which was far from ideal but worked. Like I mentioned on the other bug reports, midway through hackathon but will come back around with a proper fix unless you get to it before I do.

**Additional context**

If this is confusing, happy to jump on a zoom or what not to explain it, will be up for the next 40 hours to pump this out before the end of the hackathon.

**Comment by olifolkerd** [comment]
Hey @dragmecom 

You have definitely got confused there.

It is very simple, the title Formatter works exactly the same as the cell formatted using the same formatters or custom formatter functions, as such the maxlength is meaningless as they are formatters not editors.

There is no such thing as a title editor at this point, the ***editableTitle*** adds a simple input for editing of titles, it does not use the editor system.

Cheers

Oli :)
