### ISSUE TITLE
[Minor] Inaccurate HTML Conversion Warning On editableTitle

### ISSUE THREAD

**Issue by dragmecom** [olifolkerd/tabulator#2681]
**Describe the bug**
Creating a Tabulator table from HTML shows a warning in console erroneously when you set data-editableTitle due to case sensitivity. 

**Tabulator Info**
Latest

**Working Example**
https://jsfiddle.net/0ucs7arw/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Click Link
2. Open Developer Console
3. See error

**Expected behavior**
Shouldn't exist - kill it with fire :) 

**Desktop (please complete the following information):**
Chrome, Mac OS

**Additional context**
This was silly to report, but since I was writing the other reports, thought I would include.

**Comment by olifolkerd** [comment]
Hey @dragmecom 

Good spot, but it is actually more serious than that. case is ignored in HTML attribute properties (they are converted to lowercase by the browser) so they could never actually work.

They would need to be used as kebab case options and parsed to camel case.

This is deffo a bug, i will resolve it for today's release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @dragmecom 

Thanks for the headsup, there was a bit of legacy code left over from an old version that was mapping the lowercase properties onto the column definitions.

I have pushed a fix for this to the 4,6 branch which will be released later today,

Cheers

Oli :)
