### ISSUE TITLE
Using autocomplete error

### ISSUE THREAD

**Issue by amchconsult** [olifolkerd/tabulator#2687]
Describe the bug
When try to update a value and click somewhere else it delete the value to undefined

For example, column 1 and 2

Tabulator Info
4.6

Working Example
https://jsfiddle.net/alecode13/ruahpk13/

To Reproduce
A step by step guide to recreate the issue in your JS Fiddle:

click on any row in column 1 or 3
then click somewhere else

Desktop (please complete the following information):
MAC / OS

**Comment by olifolkerd** [comment]
Hey @amchconsult 

Thanks for the information, that definitly looks like a bug,

I will get that fixed in the next patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
I have pushed a fix for this to the master branch and will include it in the 4.6.1 release later today.

Cheers

Oli :)
