### ISSUE TITLE
Export Module with "All" does not work as expected in 4.6

### ISSUE THREAD

**Issue by westoncraig** [olifolkerd/tabulator#2688]
Tabulator is fantastic...keep up the good work!

Whether copying to clipboard using table.copyToClipboard('all') or using table.getHtml('all') the child rows in the data Trees are not included in the output.
![All - CopyRowRange ](https://user-images.githubusercontent.com/8791713/78242225-879a8f00-74d9-11ea-83bf-3a792fd15f25.jpg)

However if the 'active' CopyRowRange is selected then expanded data trees are included.
![Active - CopyRowRange ](https://user-images.githubusercontent.com/8791713/78242268-984b0500-74d9-11ea-999c-2a50eb57462b.jpg)

I would expect that 'all' would include all data trees expanded or not (possibly a parameter to expand, or not, or leave as the user has selected).

Also I note that when using copyToClipboard that the column headers are styled where in getHtml they are not.

**Comment by olifolkerd** [comment]
Hey @westoncraig 

Thanks for getting in touch.

This isnt a bug, more a limitation of the current system. because of the way data trees are generated in the row management pipeline they are only available on active table data and not available on "all" data. the same goes for row groups.

This will be comming in the future but is not currently available.

Cheers

Oli :)

**Comment by westoncraig** [comment]
Thanks Oli for getting back to me.

I did find yesterday that I got the same functionality as 'active' when
actually I set the following:

table.copyToClipboard('table') rather than table.copyToClipboard('all'). I
believe that this is because I am using the @types/tabulator-tables from
jojoshua and this is slightly out of step (v4.5.x) rather than v4.6 which I
see he is working on.

2 quick questions if I may...

1. Is there any way to format the column headers when copying to clipboard
like you can with rows and cells.

2. Is there anyway to get the column widths to stick in Excel when pasting
or and I going to have to go down the path of using the download feature,
but then currently I have seen a way to intercept the data so that it can
be styled.

Thanks for your help and am a big fan of Tabulator specifically chosen as
it has the data  tree feature.

Craig
