### ISSUE TITLE
Unable to expand grouping unless the arrow is clicked. 

### ISSUE THREAD

**Issue by rbevans-ugh** [olifolkerd/tabulator#2689]
**Describe the bug**
Unable to expand grouping unless the header arrow is clicked. 

**Tabulator Info**
4.6

**Working Example**
https://jsfiddle.net/c8j5eL0t/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Group table by a selected field
2. Attempt to expand group by clicking group header

**Expected behavior**
Group will expand when clicking the header, not just the arrow.

**Screenshots**
![image](https://user-images.githubusercontent.com/2520545/78302980-d95b0d80-7509-11ea-8ad0-116420d46d19.png)

**Additional context**

**Comment by takuy** [comment]
Doesn't look you defined the group header as the toggle element. See http://tabulator.info/docs/4.6/group#setup-toggle

**Comment by olifolkerd** [comment]
As @takuy says, this is normal function you just need to configure your table.

Oli :)

**Comment by rbevans-ugh** [comment]
Thanks all and apologizes!
