### ISSUE TITLE
Bower Updates and Performance

### ISSUE THREAD

**Issue by vasilevich** [olifolkerd/tabulator#269]
I would like to bring some bugs to your attention:

1. **first of all, new problem with version 2.12**
there appears to be a perfomance hit, whenever I load a large data set(about 200 rows) into the table, it appears that the CPU is rising to 10-30% usage which does not happen in tabulator 2.11.
ways to reproduce:
browser: Firefox 50.0
did not check weather it happens in chrome.
note maybe this happens because I use firebug, 
however it didn't happen with tabulator 2.11,
perhaps your new way of parsing the data is over tasking the browser?

2. **it appears that bower still did not update to tabulator 2.12**
last time I brought this to your attention you mentioned that it might take a day, i think almost a week has passed? maybe there is a problem? 

Thank you for your continued work!
nothing in the list is urgent to me right now but I thought it might be helpful to bring it to your attention,
cheers!

**Comment by olifolkerd** [comment]
Hey,

Thanks for getting in touch, could you post a link to a functioning example in codepen or something similar so i can see the setup you are using as i cant replicate your issues with my default test environment. ideally with test versions for your 2.11 and 2.12 setup

With bower it really is entirely down to them to detect the update. once a package is registered with them (with i did way back in early version 1) they will automatically check for the updates. im afraid there is nothing i can do to push them on with that.

Cheers

Oli

**Comment by olifolkerd** [comment]
Ive just run bower and i can see version 2.12.0 now

**Comment by vasilevich** [comment]
I don't seem to be able to reproduce the perfomance problem, however I noticed that you missed a console.log in the updateOrAdd command perhaps unintended, but it should affect perfomance a bit
(and bug in some IE versions) I believe.
type number 111111 tabulator.js (line 1441
![image](https://cloud.githubusercontent.com/assets/1217224/25208796/9f83f2ca-257f-11e7-8714-603f00e23874.png)

**Comment by olifolkerd** [comment]
Thanks for the info, that will mainly have an effect when you have the console open while generating the table.

Version 3.0 coming out in the next few weeks will resolve this.

Cheers

Oli
