### ISSUE TITLE
enable programatically to get/set column width

### ISSUE THREAD

**Issue by gd2331** [olifolkerd/tabulator#2692]
*Is your feature request related to a problem? Please describe.**
I have 2 or more tables with related information in the same columns. On resize of the column in 1 table, the other table columns are misaligned.

**Describe the solution you'd like**
Keep columns in sync by using the columnResized callback : 
   table2.getColumns(column.field).setWidth( column.getWidth() );

**Describe alternatives you've considered**
   none

**Additional context**
   none

**Comment by olifolkerd** [comment]
Hey @gd2331 

That would be an easy adition, i will add it to the roadmap.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @gd2331 

You will be happy to hear i have just pushed a commit to the 4.7 branch to add this functionality. This should be released later in May.

You will be able to get the column width in pixels using:
```js
column.getWidth();
```

You will be able to set the column width in pixels using:
```js
column.setWidth(123);
```

And you will be able to resize the column to fit its contents using:
```js
column.setWidth(true);
```

Cheers

Oli :)
