### ISSUE TITLE
4.2.2 -> 4.6.0: table.element.parentNode is null

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#2693]
[package.html.txt](https://github.com/olifolkerd/tabulator/files/4429168/package.html.txt)

**Describe the bug**

![image](https://user-images.githubusercontent.com/799021/78391354-e1d94400-75ee-11ea-893c-4c7fae303eeb.png)

```
<div id="data-table"></div>
<script type="text/javascript">
...
var dataTable =  new Tabulator( "#data-table", parentTableOpts );
</script>
```
see attached file for full code

This happen when I use tabulator inside another row of tabulator:
![image](https://user-images.githubusercontent.com/799021/78391857-e05c4b80-75ef-11ea-9e15-66ff9c9b3591.png)

**Tabulator Info**
- 4.6.0

**Expected behavior**
No error should happen

**Screenshots**
see above

**Desktop (please complete the following information):**
 - OS: Linux Mint 18.3
 - Browser FF
 - Version 72

**Comment by olifolkerd** [comment]
Hey @KES777 

Thanks for getting in touch.

 As per the [Community Guidelines](http://tabulator.info/community#bug) please can you create a JS Fiddle or Code Pen that outlines your issue. Posting large blocks of code into an issue make them hard to read and extract information. And unfortunately with the large volume of users Tabulator has, i simply don't have the time to be able to setup hosted examples of peoples code on my own computer.

Cheers

Oli :)

**Comment by KES777** [comment]
I outline the problem: `Previous tabulator does not require that parent element should be attached to DOM.`

probably, by mistake in your code you do assumption that tabulator instance is attached to DOM:

![image](https://user-images.githubusercontent.com/799021/78425197-f57ebc00-767b-11ea-9430-9ff2c72b1534.png)

Here I create element, but do not attach is to DOM
```
  var tableEl = document.createElement("div");
  tableEl.style.border = "1px solid #333";

  var table = new Tabulator(tableEl, tableOptions );
```

https://jsfiddle.net/KES777/6heudjnk/ unfortunately cloudflare has no latest version for your library

**Comment by KES777** [comment]
temporary work around

If you pass `element` into Tabulator. You should attach it to DOM first.

Notice: here I create parent element.
attach there tabulator table element
then create tabulator inside that table element

![image](https://user-images.githubusercontent.com/799021/78451233-08e65300-768d-11ea-928c-44866ee2c1ee.png)

**Comment by olifolkerd** [comment]
@KES777 

Now that you know about the new CDN would you mind creating the JS Fiddle as the nested tables example works fine on the website so it is likely a result of a quirk specific setup.

Cheers

Oli :)

**Comment by KES777** [comment]
https://jsfiddle.net/KES777/z3b9wcu8/9/

comment line 38 and uncoment line 23 to get workaround

![image](https://user-images.githubusercontent.com/799021/78452481-13f0b180-7694-11ea-874f-bc9a3c5aea37.png)

**Comment by olifolkerd** [comment]
Hey @KES777 

Thanks for that, i can certainly make it so the system can handle tables being created on detached elements.

A word of warning though, you shouldnt be manipulating the row DOM like that, when a row is invalidated and redrawn (calling row updates, table force redrawing etc) then it will not contain the table you have appended.

It would be better to use a row formatter based on a hidden row property that is then updated by the click, that way the new table would persist even if the row element is rebuilt.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @KES777 

I have pushed a fix for this to the master branch. it will prevent an error in the event that a table is instantiated when the node is not attached to the DOM.

This does have a knock on issue though, at initialisation the table binds a resize observer to its parent element to enable the table to get bigger if the parent changes size. this may under cirtain circumstances no longer happen if the table is added to the dom after initialisation.

Cheers

Oli :)
