### ISSUE TITLE
Parameter is not used

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#2696]
4.6.0

![image](https://user-images.githubusercontent.com/799021/78422950-acbf0700-766b-11ea-9ff0-4203b9466cff.png)

**Comment by olifolkerd** [comment]
Hey @KES777 

Thanks for the headsup, 

That is a handover from the old code base, i wouldn't consider it a bug as it dosnt break any functionality, but i will push a commit now to remove it as you are correct it is no longer needed.

Cheers

Oli :)

**Comment by KES777** [comment]
Yes, this is not a bug, but not a feature request too =)

Thank you, Oli
