### ISSUE TITLE
Filter is flushed when focus is changed

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#2699]
no fiddle, as there is no CDN for latest version of tabulator
![image](https://user-images.githubusercontent.com/799021/78446117-164a1000-7682-11ea-9dcc-2f08ba4223fa.png)

**How to reproduce:**
Filter table:
![_2](https://user-images.githubusercontent.com/799021/78438445-e00b9100-767f-11ea-9b66-df4200e7db78.jpg)

Click the cell with `640`:
![_](https://user-images.githubusercontent.com/799021/78438614-eb5ebc80-767f-11ea-8458-7a2bb4a19cfc.jpg)

As you can see filter is flushed.
When I filter again and click `640` cell, filter is not flushed:
![image](https://user-images.githubusercontent.com/799021/78439683-38429300-7680-11ea-801c-7cbefdfcb075.png)

**Comment by olifolkerd** [comment]
Hey @KES777 

We moved to unpkg as the CDN about a year ago, it pull directly from NPM so there is no delay in availability of new versions.

You can find the links in the [Install Documentation](http://tabulator.info/docs/4.6/install#sources-cdn)

Cheers

Oli :)

**Comment by KES777** [comment]
Thank you. I will try that.

**Comment by KES777** [comment]
https://jsfiddle.net/KES777/hqnvtg0y/2/

Click header filter in first column, then click any cell:

![image](https://user-images.githubusercontent.com/799021/78449999-11865b80-7684-11ea-9c85-7b991653d2a6.png)

**Comment by olifolkerd** [comment]
Hey @KES777 

Thanks for that, it was very helpful. This looks like it is the same bug as #2687 it is just the editor being used as a filter.

I will track the issue on #2687 as that was opened first, and will have a fix out in the next patch release.

Cheers

Oli :)
