### ISSUE TITLE
function setPageSize work not properly with param of string type

### ISSUE THREAD

**Issue by MxFulder** [olifolkerd/tabulator#27]
If in call .tabulator("setPageSize", x), param x is type of "String". Page size of table updated currectly on the first page and increase when you go to others.

**Comment by olifolkerd** [comment]
the setPageSize parameter should only be an integer representing the number of rows to be displayed on a page, it should never be a string

**Comment by MxFulder** [comment]
yes, but if it's accidentally send not integer, tabulator react with changing page size only for first page. It's non-obvious behavior. Maybe it shuld do nothing?

**Comment by olifolkerd** [comment]
I will update the system to ignore unexpected values and return ***false***. There are more warnings and exceptions being added to the system as development progresses. 

In the mean time i would suggest that you use the input parameters as they are specified in the documentation to ensure that Tabulator functions the way it has been designed.

Thanks for your feedback :)

**Comment by olifolkerd** [comment]
Just a quick update to let you know the error exceptions will be coming in this weekend. Thanks for the suggestion!

**Comment by olifolkerd** [comment]
This issue has been resolved in the latest commit
