### ISSUE TITLE
Persistent layout - row rendering issue

### ISSUE THREAD

**Issue by mbazs** [olifolkerd/tabulator#270]
Hi,
with this code:
```
$("#reportTable").tabulator({
                pagination: true,
                paginationSize: 20,
                fitColumns: false,
                persistentLayout: true,
                persistentLayoutID: 'myReport'
            });
```
the column layout of the table is stored correctly in localStorage, but when reloading the page no records are rendered anymore. Also I'm using Tabulator on a static HTML table. Maybe I'm missing something?

Thanks!

**Comment by olifolkerd** [comment]
Hey,

Thanks for getting in touch.

Could you post a copy of the html table you are parsing in so i can accurately test your situation.

Cheers

Oli

**Comment by mbazs** [comment]
```
<table id="reportTable">
    <thead>
        <tr>
            <th tabulator-frozen="true" tabulator-formatter="rownum" tabulator-sortable="false">No.</th>
            <th tabulator-frozen="true" width="100">MRN</th>
            <th tabulator-frozen="true" width="100">First Name</th>
            <th tabulator-frozen="true" width="100">Last Name</th>
            <th width="100">Referral</th>
            <th width="100">City</th>
            <th width="100">Soc</th>
            ...more usual th's, same like the last one
        </tr>
    </thead>
    <tbody>
        <tr>
              ...usual td's here
        </tr>
        ...usual tr's here
    </tbody>
</table>
```
th's, tr's and td's are OK because everything was OK before enabling the persistent layout functionality. When I delete the localStorage item (or the cookie) it's back to normal until I resize a column again. I can't provide actual data because this is a health database (legal issues). The structure is exactly the same mentioned above.

**Comment by mbazs** [comment]
I've recreated the scenario:
- visit this: http://cokmok.sytes.net:8880/tabulator_test/test.html
- table is rendered correctly
- resize a column
- refresh page
- rows disappear
- press 'Delete persistence cookie' button, then refresh page
- rows reappear

**Comment by olifolkerd** [comment]
Hey,

You will be happy to hear that version 3.0 is now in beta release, and should address the issues you were having.

Head over to http://olifolkerd.github.io/tabulator/news/ to see the latest features!

Cheers

Oli
