### ISSUE TITLE
editor > autocomplete: "Auto fill value"

### ISSUE THREAD

**Issue by exetico** [olifolkerd/tabulator#2700]
Hi,

I love the autocomplete-editor. Great job! 

I've a feature-request for it.

The "verticalNavigation" makes totally sense, however, I would like to have a hybrid, where arrow up/down, will set the selected in the input-field, but with the result of the first result, as Selected Range, while keeping the rest of the search results, untill the users uses arrow left or right.

The list should be removed, if the user are using arrow left, right, tapping away, or using the mouse (and so on).

**Why would you like that, exetico?**
Well, it's a proper "auto-complete" as seen from my point of view, and i can't get the current function to do that. I've tried a few things, but i'ts not functioning like that. (_I really hope, that i didn't miss some default related to the "auto-complete" editor-option_) :-)

![Example](https://i.imgur.com/C0MBygR.png)

By doing this, the user could:
  1. Type "Opt"
  2. Press arrow down
  3. Input should now look like this:
![image](https://user-images.githubusercontent.com/3549445/78581305-0114e300-7834-11ea-9738-9de1fd341935.png)
_The rest of the value, which are not defined by the user, in the input field, should have "selectedRange" (with setSelectionRange), and the search results should stay one the screen._

If the user are pressing arrow right, the text marker should jump to the end of the whole string, so the user can type "123". So the value in the input-field, will end up like "**Option One Reference:** `123`".
Where the **bold**-value was provided by the auto-complete function, and the `code` was typed by the user, after jumping to search item "Option One Reference:", pressed arrow right, and written "123" (like normal in the input-field, cause the search is now hidden, and the text-marked was in the end, ready for extra inputs in the end of the value, provided by the search-function).

Arrow left: Set the text marker in the start of the input-field, and hide the search-results
![image](https://user-images.githubusercontent.com/3549445/78581844-b34caa80-7834-11ea-99b1-38c61d1405a3.png)

Arrow left: Set the text marker in the end of the input-field, and hide the sreach result
![image](https://user-images.githubusercontent.com/3549445/78581820-aa5bd900-7834-11ea-917c-6093aca61ddf.png)

Does that make sense? :-) It's a bit hard to explain.

**Comment by olifolkerd** [comment]
Hey @exetico 

Thanks for getting in touch, I think it is a nice idea, but right now i feel the effort to implement it outweights the benefit it would bring to the editor. and i have a lot more urgently needed features that i need to devote my efforts to, so i would not be looking to add this to the roadmap at present.

That being said, if it is something you would like to work on yourself i would happily accept a PR for the feature.

Cheers

Oli :)

**Comment by exetico** [comment]
That's fully understandable. I think i'll do it the ugly way. I can't live up to the same quality, i guess. But i'll consider to take a look at it, at some point, if i found time, to do so.

Maybe a "quick" solution could be to define, whether an selection in the dropdown, will result in jump to the next item in the row, OR, instead, stay in the input-field, and put the selector in the end of the input-field. That sounds like a quick-fix.
