### ISSUE TITLE
Wrong sorterParams used in some cases

### ISSUE THREAD

**Issue by harbulot** [olifolkerd/tabulator#2702]
**Describe the bug**

`_sortItem` uses `sorterParams` from wrong column when going back through previous searches.

**Tabulator Info**
Version 4.6

**Working Example**
https://jsfiddle.net/dx80am19/

**To Reproduce**
- Create two columns (e.g. `category1` and `category2`) with custom `sorter`s that will rely on different `sorterParams`.
- Set up an `initialSort` using those two columns.
- Add data where some values are the same for the first column, but not the second one.

A typical example would be a "category" sorter (similar to `lookup`):

```js
function tabulatorCategorySorter(a, b, aRow, bRow, column, dir, sorterParams) {
  var categoriesMap = sorterParams.categoriesMap || {};
  var aValue = categoriesMap[a];
  if (aValue == null) {
    aValue = -1;
  }
  var bValue = categoriesMap[b];
  if (bValue == null) {
    bValue = -1;
  }
  return aValue - bValue;
}
```

```js
columns: [
	{ title: "ID", field: "id" },
	{ title: "Category 1", field: "category1",
      sorter: tabulatorCategorySorter,
      sorterParams: {
        categoriesMap: {
          "LOW": 1,
          "MEDIUM": 2,
          "HIGH": 3
        }
      }
    },
	{ title: "Category 2", field: "category2",
      sorter: tabulatorCategorySorter,
      sorterParams: {
        categoriesMap: {
          "FIRST": 1,
          "SECOND": 2,
          "THIRD": 3
        }
      }
    }
],
initialSort: [
  	{ column:"category1", dir:"asc" },
  	{ column:"category2", dir:"asc" },
]
```

**Expected behavior**

The sorter function should be called used the `sorterParams` of the columns matching the values that are in use.

However, this is not always the case.

**Screenshots**
![image](https://user-images.githubusercontent.com/80994/78612467-51ef0080-7861-11ea-8a95-b398fc6709b4.png)

**Additional context**

It seems that the cause of this problem is due to the way [`params` is re-used in `_sortItem`](https://github.com/olifolkerd/tabulator/blob/4.6/src/js/modules/sort.js#L286):

```js
//sort each item in sort list
Sort.prototype._sortItem = function(data, column, dir, sortList, i){
	var self = this;

	var params = typeof column.modules.sort.params === "function" ? column.modules.sort.params(column.getComponent(), dir) : column.modules.sort.params;

	data.sort(function(a, b){

		var result = self._sortRow(a, b, column, dir, params);

		//if results match recurse through previous searchs to be sure
		if(result === 0 && i){
			for(var j = i-1; j>= 0; j--){
				result = self._sortRow(a, b, sortList[j].column, sortList[j].dir, params);

				if(result !== 0){
					break;
				}
			}
		}

		return result;
	});
};
```

Indeed, `params` is initialised only once, for the `column` passed as a parameter.
However, when `result === 0`, `_sortRow` is then used with a different column (`sortList[j].column`, not the `column` passed as an argument), but with the same value of `params`, initialised with the initial column.

Here is one way to fix it:

```diff
                        //if results match recurse through previous searchs to be sure
                        if (result === 0 && i) {
                                for (var j = i - 1; j >= 0; j--) {
-                                       result = self._sortRow(a, b, sortList[j].column, sortList[j].dir, params);
+                                       var prevColumn = sortList[j].column;
+                                       var prevParams = typeof prevColumn.modules.sort.params === "function" ? prevColumn.modules.sort.params(prevColumn.getComponent(), dir) : prevColumn.modules.sort.params;
+
+                                       result = self._sortRow(a, b, prevColumn, sortList[j].dir, prevParams);

                                        if (result !== 0) {
                                                break;
```

**Comment by olifolkerd** [comment]
Hey @harbulot 

Thanks for bringing that to my attention, i will make sure it is fixed for the next patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @harbulot 

I have pushed a fix for this to the master branch and will include it in this weekends patch release.

Cheers

Oli :)
