### ISSUE TITLE
Cell Context Menu Placement Incorrect (Sometimes)

### ISSUE THREAD

**Issue by nrayburn-tech** [olifolkerd/tabulator#2705]
**Describe the bug**
Using the cell contextMenu option, the context menu does not always appear at the click location.  It appears somewhere towards the bottom of the screen in the fiddle.

**Tabulator Info**
4.6.1

**Working Example**
https://jsfiddle.net/d8gr3uby/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Open Fiddle
2. Right click the age column.
3. Look for the context menu.
It seems to happen with the last row every time.  It happens if you right click towards the bottom of the second row.  It does not happen with the first row.

**Expected behavior**
Menu should appear at the click location.

**Screenshots**
![MisplacedMenu](https://user-images.githubusercontent.com/52075362/78692868-218a7f00-78c0-11ea-960a-9bf8fe5f799f.png)

**Desktop:**
 - OS: macOS Catalina 10.15.4
 - Browser: Chrome
 - Version: 80.0.3987.163

**Comment by olifolkerd** [comment]
Hey @nrayburn-tech 

Thanks for the headsup, i will have a look into it this week and get a fix in the weekend patch release.

Cheers

Oli :)

**Comment by nrayburn-tech** [comment]
I am not sure how related the menus are, but I also have this issue with the rowContextMenu on the table.
The only difference is, it seems to apply regardless of which column I right click.

It is in a more complex app, so I don't have an example to share.

**Comment by olifolkerd** [comment]
The rowContextMenu will appear for all columns. It is bound to the row whole row. Not a special column

**Comment by olifolkerd** [comment]
Hey @nrayburn-tech 

I have pushed a fix for this to master and will include it in sundays patch release.

The issue arose when the table was close to the bottom edge of the body element but when there was still space in the viewport. Tabulator wasn't taking into account both heights

Cheers

Oli :)
