### ISSUE TITLE
Modern theme : Frozen columns displayed over not frozen columns even if there is enough space

### ISSUE THREAD

**Issue by JeffLeFoll** [olifolkerd/tabulator#2706]
**Describe the bug**
With modern theme, frozen columns are displayed above not frozen columns even if there is enough space to display all columns .

**Tabulator Info**
- Tabulator 4.6.1

**Working Example**
Here is a working example with standard theme : https://jsfiddle.net/15n8gLzb/3/  
We see that all columns are correctly displayed, if we reduce the view we see that name & age columns are frozen.

Here is the same example with modern theme https://jsfiddle.net/15n8gLzb/1/  
We see that data from "favourite color" column are not displayed and half of the "date of birth" column are hidden.  
If we reduce the view, we can see that the name & age columns are frozen but can't manage to see the first not frozen column.

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. setup a table with one or two frozen column
2. change theme to modern one
3. See error

**Expected behavior**
With modern theme, frozen columns should not be displayed over not frozen columns if there is enough space to display all, otherwise we should be able to see first non frozen columns using the scrollbar.

**Screenshots**
Default theme :  
![image](https://user-images.githubusercontent.com/8336918/78877685-8c1ef480-7a51-11ea-8a2d-fafdfdcf7e62.png)

Modern theme :  
![image](https://user-images.githubusercontent.com/8336918/78877778-ac4eb380-7a51-11ea-8cfb-1722c947719a.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Firefox 74 & 75 / Edge (chromium) dev build 83.0.474.

**Comment by JeffLeFoll** [comment]
What I've found so far, the modern theme has a nice colour offset in front of each row :   

![image](https://user-images.githubusercontent.com/8336918/78898569-4f182980-7a74-11ea-9985-df31f58025d0.png)

This is done in the scss file by having `padding-left: $handleWidth !important;` in the `.tabulator-row{}` rule.

This conflict with the fact that, frozen columns have an absolute position that is calculated on the ground of a left positioning at 0px.

**Comment by olifolkerd** [comment]
Hey @JeffLeFoll 

Thanks for getting in touch.

You are correct in your diagnosis of the issue. At this point i am considering removing the modern theme from the standard theme set as it takes some liberties with the table layout and it is not worth trying to update the core library just to try and handle the eccentricities of this theme.

I will have a look into it further for the next release and consider the options then.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @JeffLeFoll 

Turns out it was a quick fix, i have pushed a fix to the master branch and will include it in Sundays patch release.

Cheers

Oli :)

**Comment by JeffLeFoll** [comment]
Great !! Thank you very much @olifolkerd
