### ISSUE TITLE
Add button functionality to hide data

### ISSUE THREAD

**Issue by rbevans-ugh** [olifolkerd/tabulator#2708]
*Is your feature request related to a problem? Please describe.**
There is no way to hide data on button select

**Describe the solution you'd like**
I'd like a button to be able to hide data on button select instead of using filtering.  
For example, I would want to hide data from column B that equals Foo.

**Describe alternatives you've considered**
Multiple header filters

**Additional context**
Similar to the [select](http://tabulator.info/docs/4.6/select) feature.

**Comment by olifolkerd** [comment]
You can already achieve this using a [Custom Editor](http://tabulator.info/docs/4.6/edit#edit-custom)

Simply define an editor that returns a button element and calls the ***success*** function when the button is pressed, passing in either the value you want to filter or an empty string.

Then set that editor on the ***headerFilter*** property in the column definition for the header you want to filter.

Alternatively you may want to look at using [Column Header Menus](http://tabulator.info/docs/4.6/menu#header-menu) if that offers a more user friendly way to offer the functionality you are after

Cheers

Oli :)
