### ISSUE TITLE
Editing left-most column of table with dateTree=true results in loss of tree control elements.

### ISSUE THREAD

**Issue by jdaniels0** [olifolkerd/tabulator#2709]
**Describe the bug**
Editing left-most column of table with `dateTree=true` results in loss of tree control elements.

**Tabulator Info**
- Which version of Tabulator are you using?
4.6.2

**Working Example**
[https://jsfiddle.net/36cvLpke/1/](url)

**To Reproduce**
0. Starting state:
<img width="206" alt="Initial" src="https://user-images.githubusercontent.com/63565314/79082546-b5eb4c00-7cdb-11ea-977c-c76364a2fd3b.png">

1. Edit Son (I cancelled the edit, but doesn't matter in terms of formatting). Son is no longer a child:
<img width="204" alt="Son is no longer a child" src="https://user-images.githubusercontent.com/63565314/79082570-e92ddb00-7cdb-11ea-9a3a-413e265a9179.png">

2. Refresh (just to show each issue separately)

3. Edit Dad (cancelled edit). Dad is no longer a parent. Exception complains that removeNode not found on null:
<img width="657" alt="Dad is no longer a parent" src="https://user-images.githubusercontent.com/63565314/79082624-4de93580-7cdc-11ea-8c5f-ff4cb2b4025a.png">

**Expected behavior**
Tree control elements should persist after edit.

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome
 - Version: Chrome 76.0.3809.132 (Official Build) (64-bit)

**Additional context**
I've looked around in the issues and StackOverflow and found a few relevant ones:

[https://github.com/olifolkerd/tabulator/issues/2404](url)
[https://github.com/olifolkerd/tabulator/issues/2227](url)
[https://github.com/olifolkerd/tabulator/issues/1962](url)

The impression I got based on these is that the issue had been identified and fixed.

I tried the following approaches to get this to work:
1. Creating a custom editor and saving the cell's `innerHTML` to restores after the edit. Result never quite looked right and still would frequently fail to persist the tree control elements.
2. A custom editor that always returns `false` and / or issues `cancel()` so that I don't have to deal with creating a Node in step 1.

In conjunction with 1 & 2, I tried updating the cell data using `updateData()` and `row.update()`. `row.update()` updated the cell but failed to format it correctly.

Eventually I created a custom editor which did nothing but issue `cancel()` and `return false`. This should have had no effect on the tree controls, but even this didn't work.

But all of this struck me as heavy-handed,  I should just be able to set `editor=true` and have a correctly functioning editor.

After making the following edits to `data_tree.js` everything seems to work:

```
DataTree.prototype.checkForRestyle = function (cell) {
    if (!cell.row.cells.indexOf(cell)) {
        // Removed condition
        // if (cell.row.modules.dataTree.children !== false) {
            cell.row.reinitialize();
        // }
    }
};

DataTree.prototype.layoutRow = function (row) {
    var cell = this.elementField ? row.getCell(this.elementField) : row.getCells()[0],
        el = cell.getElement(),
        config = row.modules.dataTree;

    if (config.branchEl) {
        if (config.branchEl.parentNode) { // Added check
            config.branchEl.parentNode.removeChild(config.branchEl);
        }
    }
    
    ...
```

**Comment by olifolkerd** [comment]
Hey @jdaniels0 

Thanks for the detailed bug report, it was very helpful.

I have pushed a fix for this to the master branch and will include it in next weekends patch release.

Cheers

Oli :)
