### ISSUE TITLE
HTML Changes to page on redraw

### ISSUE THREAD

**Issue by TAMIZsn** [olifolkerd/tabulator#271]
Hi .. 
For Tabbed panel , Is there any changes in HTML page after adding  .tabulator("redraw", true) in java script page.

**Comment by olifolkerd** [comment]
The ***redraw*** function only changes the contents of the tabulator and nothing outside of its elements.

The purpose of the ***redraw*** function is to recreate the internal DOM elements of the table to fit its dimensions correctly. it should usually be called after the dimensions of the table have changed or the table has become visible after being hidden.

Cheers

Oli

**Comment by TAMIZsn** [comment]
Thank u for Reply.
Hope I am disturbing you. But i want different tabulator for Both(tabbed) panels..(unique tabulator).

**Comment by olifolkerd** [comment]
in which case please see the answer to issue #272
