### ISSUE TITLE
Blank space generated in the table while scrolling 

### ISSUE THREAD

**Issue by sarmad99** [olifolkerd/tabulator#2710]
Hi this error happens rarely and it genrateds this error in the console page:
tabulator.min.js:3 Uncaught TypeError: Cannot read property 'removeChild' of null
    at n._removeTopRow (tabulator.min.js:3)
    at n._removeTopRow (tabulator.min.js:3)
    at n._removeTopRow (tabulator.min.js:3)
    at n._removeTopRow (tabulator.min.js:3)
    at n._removeTopRow (tabulator.min.js:3)
    at n._removeTopRow (tabulator.min.js:3)
    at n.scrollVertical (tabulator.min.js:3)
    at HTMLDivElement.<anonymous> (tabulator.min.js:3)
n._removeTopRow @ tabulator.min.js:3
n._removeTopRow @ tabulator.min.js:3
n._removeTopRow @ tabulator.min.js:3
n._removeTopRow @ tabulator.min.js:3
n._removeTopRow @ tabulator.min.js:3
n._removeTopRow @ tabulator.min.js:3
n.scrollVertical @ tabulator.min.js:3
(anonymous) @ tabulator.min.js:3
tabulator.min.js:3 Uncaught TypeError: Cannot read property 'removeChild' of null
    at n._removeTopRow (tabulator.min.js:3)
    at n._removeTopRow (tabulator.min.js:3)
    at n._removeTopRow (tabulator.min.js:3)
    at n._removeTopRow (tabulator.min.js:3)
    at n.scrollVertical (tabulator.min.js:3)
    at HTMLDivElement.<anonymous> (tabulator.min.js:3)
n._removeTopRow @ tabulator.min.js:3
n._removeTopRow @ tabulator.min.js:3
n._removeTopRow @ tabulator.min.js:3
n._removeTopRow @ tabulator.min.js:3
n.scrollVertical @ tabulator.min.js:3
(anonymous) @ tabulator.min.js:3

I have video recording of the issue. Here is my js if needed:
` <script>
        $(document).ready(function () {
            var minMaxFilterEditor = function (cell, onRendered, success, cancel, editorParams) {
                var end;
                var container = document.createElement("span");

                //create and style inputs
                var start = document.createElement("input");
                start.setAttribute("type", "number");
                start.setAttribute("placeholder", "Min");
                start.setAttribute("min", 0);
                start.setAttribute("max", 100);
                start.style.padding = "4px";
                start.style.width = "50%";
                start.style.boxSizing = "border-box";

                start.value = cell.getValue();

                function buildValues() {
                    success({
                        start: start.value,
                        end: end.value,
                    });
                }

                function keypress(e) {
                    if (e.keyCode == 13) {
                        buildValues();
                    }

                    if (e.keyCode == 27) {
                        cancel();
                    }
                }

                end = start.cloneNode();
                end.setAttribute("placeholder", "Max");

                start.addEventListener("change", buildValues);
                start.addEventListener("blur", buildValues);
                start.addEventListener("keydown", keypress);

                end.addEventListener("change", buildValues);
                end.addEventListener("blur", buildValues);
                end.addEventListener("keydown", keypress);

                container.appendChild(start);
                container.appendChild(end);

                return container;
            }
            function minMaxFilterFunction(headerValue, rowValue, rowData, filterParams) {
                if (rowValue) {
                    if (headerValue.start != "") {
                        if (headerValue.end != "") {
                            return rowValue >= headerValue.start && rowValue <= headerValue.end;
                        } else {
                            return rowValue >= headerValue.start;
                        }
                    } else {
                        if (headerValue.end != "") {
                            return rowValue <= headerValue.end;
                        }
                    }
                }
                return true; //must return a boolean, true if it passes the filter.
            }
            //        var tabulator_table = new Tabulator("#example", {
            //    height:"80%",
            //});
            var tabulator_table = new Tabulator("#example", {
                //  height:"533px",
                columns: [
                    { title: "Produced In", field: "Produced In", headerFilter: "input" },
                    { title: "Production Range", field: "Production Range", headerFilter: "input" },
                    { title: "Production Prefix", field: "Production Prefix", headerFilter: "input" },
                    { title: "Production Bates Begin", field: "Production Bates Begin", headerFilter: "input" },
                    { title: "Production Bates End", field: "Production Bates End", headerFilter: "input" },
                    { title: "Production Type", field: "Production Type", headerFilter: "input" },
                ],
            });

            document.getElementById("myButtons").addEventListener("click", function () {
                tabulator_table.download("xlsx", "data.xlsx", { sheetName: "MyData" });
            });
            $(".tabulator-header-filter").find("input").attr('placeholder', 'All()')

            tabulator_table.redraw(true);
            $("#example").on("load", function () {
                if ($("#example").width() < '576') {
                    console.log($("#example").width());
                    $(".tabulator-header").find(".tabulator-col:not(.tabulator:last-child())").width("40px");
                }
            });

    </script>`
thank you. please email me for the video and more details.

**Comment by olifolkerd** [comment]
Hey @sarmad99 

Im afraid it is very hard to help you if you just post large blocks of code into an issue.

Please read through the [Reporting a Bug Guidelines](http://tabulator.info/community#bug) and use the [Bug Issue Template](https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Possible+Bug&template=bug_report.md&title=) to resubmit this bug report.

We need to know a lot more details about your setup, the browser you are using, the version of Tabulator before we are able to help you. The issue template will prompt you for the correct information.

You also need to submit a link to a JS Fiddle or Code Pen that shows a working example of the issue you are experiencing.

Cheers

Oli :)
