### ISSUE TITLE
Frozen Columns lag on nested data

### ISSUE THREAD

**Issue by ashton721** [olifolkerd/tabulator#2712]
**Describe the bug**
Frozen columns are lagging when scrolling. This appears to only happen when you don't define a height parameter in. And  it seems to only happen on nested child rows. 

**Tabulator Info**
- 4.5.3

**Working Example**
https://codepen.io/ashton721/pen/GRppwXr

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://codepen.io/ashton721/pen/GRppwXr
2. Scroll right to left
3. See lag in nested rows

**Expected behavior**
Works fine when height is defined, scroll is smooth. When you remove a height definition, the animation is laggy and unpleasant.

**Comment by olifolkerd** [comment]
Please try upgrading to the lastest version of Tabulator

**Comment by ashton721** [comment]
Thanks!
