### ISSUE TITLE
update GUI after modifying row data without redraw

### ISSUE THREAD

**Issue by michaelongithub** [olifolkerd/tabulator#2713]
If bug: needs fix.
If by design: why? 

If the current behaviour is desirable  by design. provide option in the different update mechanisms / methods above mentionend for updating GUI

**Comment by olifolkerd** [comment]
Hey @michaelongithub 

Im afraid i dont understand what it is you are asking there, there isnt enough information to go on.

please provide more details of the specific case you are trying to describe, the outcome you would like to see and the reasons for the change.

Cheers

Oli :)

**Comment by michaelongithub** [comment]
Lets say I have something like:
tabulator.updateData([{ BRAND_FAMILY_INFO_ID: "4", BRAND_FAMILY_INFO: "GUGU" }]);
If I check 
let updatedRow = tabulator.getRow("4");
console.log(updatedRow );
I see that it is updated.
But in GUI the old value is still displayed.
The display is updated only after table.redraw(true).

I would have expected featurewise the visible value to be updated also, without additional redraw.

**Comment by olifolkerd** [comment]
it should return a promise that will resolve when the data has been updated.

Im afraid i dont follow you. update data should trigger table redraw.

maybe a JS Fiddle may help in this instance.

Cheers

Oli :)

**Comment by michaelongithub** [comment]
Hi Oli
On closer analysis it is reproducible if more than 1 col is bound to the same data field. In the following example only the value in the name2 column is visibly updated.
`daTabulator = undefined;

let tabledata = [
    { id: 1, name: "Billy Bob", age: 12, gender: "male", height: 95, col: "red", dob: "14/05/2010" },
    { id: 2, name: "Jenny Jane", age: 42, gender: "female", height: 142, col: "blue", dob: "30/07/1954" },
    { id: 3, name: "Steve McAlistaire", age: 35, gender: "male", height: 176, col: "green", dob: "04/11/1982" },
];

document.addEventListener("DOMContentLoaded", function (event) {
    console.log("DOM fully loaded and parsed");

    daTabulator = new Tabulator("#ttTabulator", {
        index: "id", //set the index field to the "age" field.
        height: "311px",
        width:"1000px",
        columns: [
            { title: "Name", field: "name" },
            { title: "Name2", field: "name" },
            { title: "Progress", field: "progress", sorter: "number" },
            { title: "Gender", field: "gender" },
            { title: "Rating", field: "rating" },
            { title: "Favourite Color", field: "col" },
            { title: "Date Of Birth", field: "dob", hozAlign: "center" },
        ],
        data: tabledata
    });

    daTabulator.updateData([{ id: 2, name: "Hey There" }]); //updates visibly only Name2. Row Data are updated correctly
//    daTabulator.redraw(true); //this leads to correct situation on the GUI`

I have this situation often if I have to have different formatting needs in diff. columns for same underlying data field

**Comment by olifolkerd** [comment]
At that point that is totally understandable.

If you bind multiple columns to the same field then tabulator has no way to know which ones to update. it is designed to have one column per field.

In your scenario i would suggest using a mutator to created a mocked additional field and then using the cellEdited event to trigger an update in the additional field

Cheers

Oli :)

**Comment by michaelongithub** [comment]
Thanks
