### ISSUE TITLE
autoColumns does not work if the column-name contains a period (.)

### ISSUE THREAD

**Issue by webseitz** [olifolkerd/tabulator#2714]
**Describe the bug**
If the autoColumns feature is used and the column-name contains a period (.), like 
`{id:4, "nam.e":"Brendon Philips", progress:100, gender:"male", rating:1, col:"orange" },`

then the data for the whole column does not show up. Happens also if the data is loaded via AJAX as a JSON-Object.

**Tabulator Info**
4.6.2

**Working Example**
https://jsfiddle.net/2puwe4z8/2/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://jsfiddle.net/2puwe4z8/2/
2. The upper table uses a period inside a column name
3. The lower table is the same, just without a period in the column name

**Expected behavior**
The table should also work with a period in the column-name

**Screenshots**
See https://jsfiddle.net/2puwe4z8/2/
**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Browser: Safari
 - Version: 13.2
Problem does not depend on browser

**Comment by olifolkerd** [comment]
Hey @webseitz 

This is not actually bug, but a feature.

Dot notation is used for defining columns in nested data structures. have a look at the [Nested Data Documentation](http://tabulator.info/docs/4.6/columns#field-nesting) for more info.

You can change the default field separator symbol to prevent the issues you are experiencing by using the ***nestedFieldSeparator*** option. if you set it to any symbol other than "." you should be good

```js
var table = new Tabulator("#example-table", {
    nestedFieldSeparator:"|", //change the field separator character to a pipe
});
```
I hope that helps

Cheers

Oli :)
