### ISSUE TITLE
Horozontal Scroll with ajax

### ISSUE THREAD

**Issue by Luismvst** [olifolkerd/tabulator#2715]
Hello Oli!

I am having trouble visualizing a huge table with multiple header (4 levels) of aprox 40.000 columns, with a nested data tree of 200 rows aprox.

It takes several hours to render a few json MB of data in javascript (data and columns data).

I know tables are not meant to be showed that way, but the situation requieres it. 

I would like to ask if it is possible to include ajax to be able to scroll horizontally on the table. I am concern that this inclusion has to create the headers at the same time as data, and i dont know if it would be possible in a near future. 

Thank you for your work with tabulator, it is being an amazing experience working with it and it is really easy to build whatever you want with a fast programming experience.

**Comment by olifolkerd** [comment]
Hey @Luismvst 

That is a lot of columns there, i would argue that it would be extremely bad User Interface design to have that many columns in the first place as there is no meaningful way that a user could interact with a table with that many columns. even Excel would struggle to manage that many columns.

So while i will be looking to virtualize columns in version 5 i see a very limited usage case for AJAX loading that volumn of data. the ajax transfer time alone would be considerable.

Cheers

Oli :)
