### ISSUE TITLE
Adding Horizontal Column Alignment on 'generateColumnsFromRowData'

### ISSUE THREAD

**Issue by Joao-deOliveira** [olifolkerd/tabulator#2717]
Would like to have the Horizontal Alignment managed on the 'generateColumnsFromRowData' on the similar way that the 'sorter' is processed.

SOLUTION
````js
function generateColumnsFromRowData(data)
			{
				var cols = [],
					row,
					sorter,
					hzAlign;

				if ((typeof(data) === typeof(undefined) || data === null) || data.length == 0)
					return null;
			
				row = data[0];

				for (var key in row) 
				{
					var col = {
						field: key,
						title: key
					};

					var value = row[key];

					switch (typeof value === 'undefined' ? 'undefined' : _typeof(value)) 
					{

						case "undefined":
							sorter = "string";
							hzAlign= "left";
						break;

						case "boolean":
							sorter = "boolean";
							hzAlign= "center";
						break;

						case "object":
							if (Array.isArray(value)) 
								sorter = "array";
							else 
								sorter = "string";

							hzAlign = "left";
						break;

						default:
							if (!isNaN(Date.parse(value) && value !== ""){  // if true it's a date 
								sorter = "date";
								hzAlign= "center";
							}else 
								if (!isNaN(value) && value !== ""){ 
									sorter = "number";
									hzAlign= "right";
									
								}else {
									if (value.match(/((^[0-9]+[a-z]+)|(^[a-z]+[0-9]+))+$/i))
										sorter = "alphanum";
									else 
										sorter = "string";
										
									hzAlign = "left";
								}
						break;

					}

					col.sorter  = sorter;
					col.hozAlign= hzAlign;
					cols.push(col);
				}
				return cols;
				
			}

```

**Comment by Joao-deOliveira** [comment]
here is the code I wrote to get it working


=======================================================
generateColumnsFromRowData = function (data)
	{
		var cols = [],
			keys,
			row,
			sorter,
			hzAlign;

		if ((typeof(data) === typeof(undefined) || data === null) || data.length == 0)
			return null;
	
		var RndPoint	= Math.floor((Math.random() * TabRows.length));
		row = data[RndPoint];

		for (var key in row) 
		{
			var col = {
				field: key,
				title: key
			};

			var value = row[key];

			switch (typeof value === 'undefined' ? 'undefined' : _typeof(value)) 
			{
				case "undefined":
					sorter = "string";
					hzAlign= "left";
				break;

				case "boolean":
				case "symbol":
					sorter = "boolean";
					hzAlign= "center";
				break;

				case "object":
					if (Array.isArray(value)) 
						sorter = "array";
					else 
						sorter = "string";

					hzAlign = "left";
				break;

				case "bigint":
				case "number":
					sorter = "number";
					hzAlign= "right";					
				break;
				
				case "string":
					// default values
					sorter = "string";
					hzAlign = "left";
					// however, it migth be a special string 
					if (value !== ""){
						// Money 
						var isMoney = value.match(/^(([^a-z]*)|([\u20A0-\u20BF]?(?=\([0-9][^a-z]*\)|[^()]*$)\(?\d{1,3}(,?\d{3})?(\.\d\d?)?\)?))$/i);
						// Percentage
						var isPCent = value.match(/^((?=\(.*\)|[^()]*$)\(?\d{1,3}(,?\d{1,3})?(\.\d{1,3})?\)?\%)$/i);
						if (isMoney || isPCent){
							sorter = "alphanum";
							hzAlign= "right";
						}else{				
							var dateWrapper = new Date(value);
							if (!isNaN(dateWrapper.getDate()))
							{  // if true it's a date 
								sorter = "date";
								hzAlign= "center";
							}else{
								// Dates like : (YY)YYMMMDD | DDMMMYY(YY) | MMMDDYY(YY)
								// Dates like: (YY)YYMMDD | MMDDYY(YY) | DDMMYY(YY) not tested as a numeric column might match
								var is$Date = value.match(/^(((\d{2,4})([a-zA-Z]{3})(0[1-9]|[12][0-9]|3[01]))|((0[1-9]|[12][0-9]|3[01])([a-zA-Z]{3})(\d{2,4}))|(([a-zA-Z]{3})(0[1-9]|[12][0-9]|3[01])(\d{2,4})))$/i);
								if (is$Date){
									sorter = "alphanum";
									hzAlign= "center";
								}
							}
						}
					}
				break;

				default:
					if (!isNaN(value) && value !== ""){ 
						sorter = "number";
						hzAlign= "right";
					}else {						
						if(value.match(/((^[0-9]+[a-z]+)|(^[a-z]+[0-9]+))+$/i))
							sorter = "alphanum";
						else
							sorter = "string";
						
						hzAlign = "left";
					}
				break;

			}

			col.sorter  = sorter;
			col.hozAlign= hzAlign;
			cols.push(col);
		}
		return cols;
		
	};

=======================================================

**Comment by olifolkerd** [comment]
Hey @Joao-deOliveira 

Thanks for the suggestion, unfortunately your choice of alignment is only applicable to your usage case, others may want their data aligned in a different way.

I try not to add any code to Tabulator that forces a design choice on a developers. So while i am happy you found a solution to your usage case, i will not be looking to include this in Tabulator.

Cheers

Oli :)
