### ISSUE TITLE
Access to Column Default Option List

### ISSUE THREAD

**Issue by nrayburn-tech** [olifolkerd/tabulator#2718]
I am attempting to validate user input that is used to create a Tabulator instance.  As they input the options, I want to provide feedback if it is an invalid table or column option.
I can access the Table options through `Tabulator.prototype.defaultOptions`.  I cannot find a way to access the `Column.defaultOptionList`, without creating a Tabulator instance. For example, I can get the list through `Tabulator.prototype.comms.tables[0].columnManager.columns[0].defaultOptionList` once a Tabulator instance is created with at least one column.

**Describe the solution you'd like**
Can the `defaultOptionList` of the `Column` be exposed?  Something like, `Tabulator.prototype.Column.defaultOptionList`, or `Tabulator.prototype.columnDefaultOptionList`.

**Describe alternatives you've considered**
I could create a simple Tabulator, so that I can access the `defaultOptionList`.

**Comment by olifolkerd** [comment]
Hey @nrayburn-tech 

You could always include the Column object definition in your code by including the `/src/js/column.js` file in your code. then you could directly access the column prototype.

Cheers

Oli :)
