### ISSUE TITLE
Append menus to parent rather than document

### ISSUE THREAD

**Issue by mbulfair** [olifolkerd/tabulator#2719]
*Is your feature request related to a problem? Please describe.**
I'm trying to use this project in a web component, if that component has the shadow dom enabled, the css is not available to the rest of the project. Would it make more sense to bind all listeners to the parent element? 

**Describe the solution you'd like**
Including the line `document.body.appendChild(this.menuEl);` to `this.table.element.parentNode.appendChild(this.menuEl);` so that in this use case it would work>?

Might not be a standard use for everyone, but I personally like to contain everything my library would do and never assume something. Keeping it all nested under the markup the table generates.

**Comment by olifolkerd** [comment]
Hey @mbulfair 

By making this the default option it would create numerous issues, say for example the element was included in a modal, should the list extend past the edge of the modal it would be cropped, that is why the element is appended to the body.

That being said i see your usage case, i will look at adding an option so you can choose an alternative element for the menus to be appended to if needed

Thanks for the suggestion

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @mbulfair

I have just pushed an update to the 5.1 branch that adds the `menuContainer` option, to specify which element the menu should be appended to.

This will be included in the next release.

Cheers

Oli :)
