### ISSUE TITLE
tabbed panel

### ISSUE THREAD

**Issue by TAMIZsn** [olifolkerd/tabulator#272]
Hi,
How to use different tabulator's for tabbed panels..(must Be Unique)

**Comment by olifolkerd** [comment]
Hey,

Thanks for getting in touch, declaring two Tabulators is really simple, you follow the exact same process as for one, just using a different div for the second element.

If you want to us them inside tabs then you just need to call the ***redraw*** function on the table when the table is made visible.

below is an example using jquery tabs:

#### HTML
```html
<div id="tabs">
  <ul>
    <li><a href="#tabs-1">Tab 1</a></li>
    <li><a href="#tabs-2">Tab 2</a></li>
  </ul>
  <div id="tabs-1">
    <div id="tabulator-1"></div>
  </div>
  <div id="tabs-2">
    <div id="tabulator-2"></div>
  </div>
</div>
```

### JavaScript
```js
//create tabs
$( "#tabs" ).tabs();

//create tabulator 1
$("#tabulator-1").tabulator({
    columns:[...], //column definitions etc...
});

//create tabulator 2
$("#tabulator-2").tabulator({
    columns:[...], //column definitions etc...
});

//trigger redraw on tabulator on tab being selected
$("#tabs").on("tabsactivate", function(event, ui){
    //redraw any tables in current tab
    $(".tabulator", ui.newPanel).tabulator("redraw", true);
});
```

Let me know if that helps,

Cheers

Oli

**Comment by mccmoses** [comment]
This code is no longer valid since the release 4.0.

What would be the new syntax?
