### ISSUE TITLE
Only first page data in excel by default download

### ISSUE THREAD

**Issue by kapenzo** [olifolkerd/tabulator#2720]
Hello, 
first of all, thank you for this framework!
Now to the problem.
I have a paginated table with more pages. In the previous version 4.4.1 when I used download module to generate excel, there were by default **all data included (from all pages)**. As I see, this logic is until **4.5.3.**

Now (**4.6.0-4.6.2**) I see that by default is the "active" option used. When I generate excel now, as result I have in excel **the data only from the first page**. Is it ok/bug ?

I debugged it and have seen that:
1. There is a  bug/typo in https://github.com/olifolkerd/tabulator/blob/7600fe7fa7b75c3973b39b1e15bbb659259d808a/src/js/modules/download.js#L206
but here there will be no problem when the default ("active") option is used.
2. There variable active is set to "display" so in switch we are going here
https://github.com/olifolkerd/tabulator/blob/7600fe7fa7b75c3973b39b1e15bbb659259d808a/src/js/row_manager.js#L1172
Then the result of  the method getDisplayRows() 
https://github.com/olifolkerd/tabulator/blob/7600fe7fa7b75c3973b39b1e15bbb659259d808a/src/js/row_manager.js#L1104
is only one page data. (this.displayRows[2])

Is it expected behavior/logic ?
I guess that I can achieve the all pages using the option "all" as described in
http://tabulator.info/docs/4.6/download  section "Download Data Set"
but when using filters I will have also the data which should not be included in excel.

Thank you in advance of handle this issue.
Cheers, Tomek

**Comment by kapenzo** [comment]
I tested the option "all". It is obviously not possible because of the 1. bug/typo issue :D
I have all the time "display" option no matter what I will set.  So this is definitely a bug.

So for now only option for me to show all the pages is to use the 4.5.3 version.

**Comment by olifolkerd** [comment]
Hey @kapenzo 

Thanks for getting in touch, this does raise an interesting point.

The default behaviour has changed for the download function, this is to bring it in to line with other export functions. but you are right, i seem to have overlooked the pagination requirements.

I will look to resolve this in the next patch release.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @kapenzo 

Could you create a JS Fiddle that shows how your table is setup? do you have ***dataTree*** enabled on your table?

The lines you have mentioned only apply if the table is using a data tree otherwise, it should be displaying the correct data.

Cheers

Oli :)

**Comment by kapenzo** [comment]
Yes I use dataTree option.
https://codepen.io/kapenzo/pen/KKdBZNY
Actually I don't really need this option :D But anyway there is a bug ;)

**Comment by olifolkerd** [comment]
Hey @kapenzo 

The download module has been rebuilt for the 4.7 release to be based on the output of the export module. which will resolve this issue.

Version 4.7 will be released in the next couple of weeks.

Cheers

Oli :)

**Comment by dannykhoo** [comment]
I have facing the same problem too ,  just updated tabulator to latest version 4.7.3 but still same, when try to export csv /xlsx,  the data only from the first page. 

https://codepen.io/danny-khoo/pen/bGpbQVo
