### ISSUE TITLE
Download as Excel Multiple Header

### ISSUE THREAD

**Issue by Luismvst** [olifolkerd/tabulator#2721]
Hello Oli!

I am dealing with a bug with the download to an xlsx file. 

It happends when you try to download a multiple header table (3 levels or more) mixed with simple headers columns. In my case, we have 2 columns with one level headers at the begining of the table and columns with 3 levels next to them in the same table. The xlsx file tries to combine the cells corresponding to the multi-header dimension (which is really cool), but due to one-level columns at first, they are combined by 'eating' some of the first multi-header column names. 

We solved this problem inserting a phantom column between the single level header and the multi-level header, but now it is being tedious to use.

There is another problem with the data, related to the last column of the multi-header table.
In this case, the last column of data is missing.
We solved this problem inserting a phantom column at the end.

I hope you find the solution easily, 
![oLI](https://user-images.githubusercontent.com/27961743/79781015-24b05100-833d-11ea-838b-e59726c4cd04.PNG)
![oLI2](https://user-images.githubusercontent.com/27961743/79781019-2548e780-833d-11ea-9677-4789d4679d4c.PNG)

Thank you

**Comment by olifolkerd** [comment]
Hey @Luismvst 

Please create a JS fiddle that demonstrates your issue, it is very hard to offer advice without seeing how your table is setup.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @Luismvst 

The download module has been rebuilt for the 4.7 release to be based on the output of the export module. which will resolve this issue.

Version 4.7 will be released in the next couple of weeks.

Cheers

Oli :)
