### ISSUE TITLE
Bootstrap theme classes do not work properly

### ISSUE THREAD

**Issue by takuy** [olifolkerd/tabulator#2722]
**Describe the bug**
the Bootstrap theme's table-dark class does not work properly on table elements. The last version this worked was 4.2.5

**Tabulator Info**
Tabulator 4.6.2

**Working Example**
Version 4.2.5 with newest Bootstrap: https://codepen.io/tako1337/pen/ywaJQB
Version 4.6.2 with newest Bootstrap: https://codepen.io/tako1337/pen/eYpBjPd

**To Reproduce**
1. Add table-dark to table element class

**Expected behavior**
proper bootstrap styling

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome 80

**Additional context**
Looks like this is happening due to the following CSS:
sc:
https://github.com/olifolkerd/tabulator/blob/4531ef88896760e051e847dd5981fe18e0445d88/src/scss/bootstrap/tabulator_bootstrap4.scss#L375
https://github.com/olifolkerd/tabulator/blob/4531ef88896760e051e847dd5981fe18e0445d88/src/scss/bootstrap/tabulator_bootstrap4.scss#L830

dist:
https://github.com/olifolkerd/tabulator/blob/4531ef88896760e051e847dd5981fe18e0445d88/dist/css/bootstrap/tabulator_bootstrap4.css#L271
https://github.com/olifolkerd/tabulator/blob/4531ef88896760e051e847dd5981fe18e0445d88/dist/css/bootstrap/tabulator_bootstrap4.css#L675

**Comment by takuy** [comment]
Guess it was this commit to fix transparency that broke things like `table-dark`: https://github.com/olifolkerd/tabulator/commit/84e4a3f6399c4fd3734f57897e011ab213329dd5

**Comment by olifolkerd** [comment]
Hey @takuy 

Thanks for the headsup, i will make sure this is fixed in the next patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @takuy 

I have pushed a fix for this to the master branch and will include it in tomorrows patch update.

Cheers

Oli :)
