### ISSUE TITLE
addClass() is not a function - apparently

### ISSUE THREAD

**Issue by guanicoe** [olifolkerd/tabulator#2723]
https://jsfiddle.net/ehgydz81/

Hi, when I use the default example for using booststrap as a theme. I added the code you showed to my project and i get an error.
```
var table = new Tabulator("#example-table", {
    rowFormatter:function(row){
        if(row.getData().age >= 18){
            row.getElement().addClass("table-primary"); //mark rows with age greater than or equal to 18 as successful;
        }
    },
});
```

The error is: 
`TypeError: row.getElement(...).addClass is not a functiondashboard:51:30`

**Tabulator Info**
tabulator-tables@4.6.2

**Working Example**
Even when I only copy and past the example from the website (without any of my code) into jsfiddle. you'll see in the console output that this error shows up. I'm not good enough with javascript to be able to find a solution. As far as i am concern, the addClass is not found in tabulator.min.js, though I don't know if it's supposed to be a built-in function. 

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to [https://jsfiddle.net/ehgydz81/](https://jsfiddle.net/ehgydz81/)
2. Click on 'run'
3. Open inspector

**Expected behavior**
Add the class i guess

**Screenshots**
![image](https://user-images.githubusercontent.com/62290334/79946355-54577a00-845f-11ea-9377-34a929e10c7a.png)

**Desktop (please complete the following information):**
 - OS: Parrot
 - Browser Firefox
 - Version 74

**Additional context**
Taken out of the tutorial from the website

**Comment by takuy** [comment]
addClass() is a jQuery function. Bootstrap requires jQuery, so if you wanted to use addClass, you'd have to do `jQuery(row.getElement()).addClass("table-primary");` or the non-jQuery way: `row.getElement().classList.add("table-primary");`

The doc is just wrong for the bootstrap3 and 4 examples.

http://tabulator.info/docs/4.6/theme#framework-boot3

**Comment by olifolkerd** [comment]
Hey @guanicoe 

As @takuy says, this is a documentation error, left over from the early days when Tabulator was a jQuery library.

I will ensure this is fixed in the next website update.

Cheers

Oli :)
