### ISSUE TITLE
footer total

### ISSUE THREAD

**Issue by ashasaji** [olifolkerd/tabulator#2724]
**Describe the bug**

**Tabulator Info**
- Which version of Tabulator are you using?

**Working Example**
YOU MUST include a link to a JS Fiddle or Codepen that demonstrates the problem, it is very hard to diagnose an issue from a simple description.

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by olifolkerd** [comment]
You have not filled in any of the required parts of this issue, template. you have just written the word "footer template" as the title.

Please resubmit this with all the required details

Cheers

Oli :)
