### ISSUE TITLE
Pdf Download do not include Footer row added with bottomCalc.

### ISSUE THREAD

**Issue by ashasaji** [olifolkerd/tabulator#2726]
Hello,
Am using latest version of Tabulator (4.6.2) in Angular 8.
My tabulator settings are :
  this.myTable = new Tabulator("#tabulator-div", {
      pagination:"local", 
      height: "500px",
      layout: "fitColumns",
      groupBy: "SOC_NAME",
      tooltips: true,
      tooltipsHeader: true,
      resizableRows: true,
      columns: this.columnNames,
      columnCalcs:"both",
      placeholder: "No Data Available",
      groupClosedShowCalcs:true,
      downloadConfig:{
        rowGroups:true, //do not include row groups in download
        columnCalcs:true, 
    },
      autoTable: { 
      },
    });

Generate PDF:

  generatePDF() {
    this.myTable.download("pdf", "data.pdf", {
      orientation: "portrait", 
      autoTable: function (doc) {       
        doc.text("Client Logo/Header goes here...", 20, 20);        
        return {       
        };
      },
    });
    var doc = new jsPDF();
    doc.autoTable(this.myTable);
  }
![FooterRow](https://user-images.githubusercontent.com/37214032/79971708-54cd3080-84b2-11ea-978f-8f9cacae3e67.png)

Pinned row at the bottom highlighted in the Red colour is missing in the generted pdf.
Awaiting your feedback. Thanks in advance. Asha

**Comment by olifolkerd** [comment]
Hey @ashasaji 

Please use the [Bug Report Issue Template](https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Possible+Bug&template=bug_report.md&title=) when reporting a bug as it prompts you for the details we will need to help you out.

We will need to see a working JS Fiddle of your table so we can understand how it is setup, in order to replicate the issue.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @ashasaji 

The download module has been rebuilt for the 4.7 release to be based on the output of the export module. which will resolve this issue.

Version 4.7 will be released in the next couple of weeks.

Cheers

Oli :)

**Comment by ashasaji** [comment]
Thank you so much Oli..!

Regards
Asha
