### ISSUE TITLE
select editor: typing in first letter makes user jumps to value

### ISSUE THREAD

**Issue by edwinro** [olifolkerd/tabulator#2727]
Hello Oli,

**Is your feature request related to a problem? Please describe.**
I'm using a Tabulator table that contains a select field with plenty (100+) options. Users need to scroll a lot to find the right value.

**Describe the solution you'd like**
Typing in the first letter on the keyboard makes the user go to the right dropdown value.

**Describe alternatives you've considered**
- Not using Tabulator (create the table manually with CSS) and use 'select' module from Atlaskit (or another framework).
- Create a custom editor in Tabulator with React components.
- Stay on version 3.x.x. (where this still worked - not sure if it is a bug or feature request in case it was dropped consciously when switching away from JQuery)

**Additional context**

A codepen to illustrate:

https://codepen.io/edwinro/pen/NWGdKVB
Click on a line in column 'name' and select a value from the long list.

Kind regards,
Edwin

**Comment by nrayburn-tech** [comment]
I would definitely like this feature as well.  It is slightly confusing to some users when it doesn't work the same way as an html select element does.
There is the autocomplete editor, but I don't think that is necessarily the solution in all cases.

**Comment by olifolkerd** [comment]
Hey @edwinro 

Thanks for the suggestion, i will look at adding that to the roadmap.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @edwinro 

I have pushed an update for this to the 4.9 branch that will be released later this month.

Cheers

Oli :)

**Comment by edwinro** [comment]
Thank you @olifolkerd !
