### ISSUE TITLE
menu item generator function does not get the component object as 1st argument

### ISSUE THREAD

**Issue by vec2k4** [olifolkerd/tabulator#2729]
**Describe the bug**
The [documentation ](http://tabulator.info/docs/4.6/menu) says that when using a generator function for context menu items, the corresponding component object is passed to the function as the 1st argument:
```javascript
var table = new Tabulator("#example-table", {
    rowContextMenu: function(component){
        ...
    }
```
This is not the case for any of the functions (`rowContextMenu`, `headerMenu`, `headerContextMenu`, `contextMenu`). The `component` argument is always `undefined`.

**Tabulator Info**
4.6.2

**Working Example**
https://jsfiddle.net/vec2k4/78f0akp9/

**To Reproduce**
1. Go to the fiddle.
2. Right click on a row in the upper table
3. See output `undefined`
4. Right click on a cell in the lower table
5. See output `undefined`

**Expected behavior**
The component object should be passed to the generator function as said by the documentation.

**Screenshots**
Not necessary

**Desktop**
 - OS: Windows 10 Pro 1909 (Build 18363.778)
 - Browser: Edge 
 - Version 81.0.416.62 (64-Bit)

**Additional context**
This issue could be solved by passing the corresponding component objects to the generator functions:
- [HeaderContextMenu](https://github.com/olifolkerd/tabulator/blob/4531ef88896760e051e847dd5981fe18e0445d88/src/js/modules/menu.js#L12)
- [HeaderMenu](https://github.com/olifolkerd/tabulator/blob/4531ef88896760e051e847dd5981fe18e0445d88/src/js/modules/menu.js#L27)
- [CellContextMenu](https://github.com/olifolkerd/tabulator/blob/4531ef88896760e051e847dd5981fe18e0445d88/src/js/modules/menu.js#L40)
- [RowContextMenu](https://github.com/olifolkerd/tabulator/blob/4531ef88896760e051e847dd5981fe18e0445d88/src/js/modules/menu.js#L50)

Cheers,

Ralf

**Comment by olifolkerd** [comment]
Hey @vec2k4 

Thanks for the PR i will ensure that it is included in the patch release this weekend.

Cheers

Oli :)
