### ISSUE TITLE
Allow function to dynamically set URL target of link formatter

### ISSUE THREAD

**Issue by sjkoffman** [olifolkerd/tabulator#2735]
Similarly to allowing a function to specify the URL for a link formatter, it is also desired to set the target for the URL dynamically so that link opens in a known tab, to prevent an explosion of new browser tabs for unique HTML targets that would otherwise be created by using "_blank" target attribute.  The use case is that we have 1000s table entries that point to 10s of individual HTML files.  We would like the ability to open each of the 10s of individual files in their own tab, rather than each link navigation creating a new tab with using "_blank" target, for manageability of tabs.  We did try setting the target to a function, but that had the effect of opening all links to the same tab.  Our workflow requires having multiple "opened" links to correlate data.  Thank you for your consideration and for a most excellent product that is enjoyable to use.

**Comment by olifolkerd** [comment]
Hey @sjkoffman 

This is a bit of an edge case, and i cannot see a mass appeal in including this in the core library.

That being said, it should be very easy for you to create your own [Custom Formatter](http://tabulator.info/docs/4.6/format#format-custom) to implement this functionality in your own table.

Cheers

Oli :)

**Comment by sjkoffman** [comment]
Hi Oli,
I do agree that it is an edge case.  I hadn’t thought to use the CustomFormatter.  I’ll give that a try.  Thanks for a great product.  I’m in awe of it.

Thanks,
Stephen J. Koffman, Ph.D., TF
Senior Controls Analyst, Boeing S&IS
GNC CPAST PM/PI
562-797-8616
MATLAB CPAST Products: https://publishing.web.boeing.com/sites/GNCMatlabTools
MATLAB & Simulink CoP: https://know.web.boeing.com/sites/MatlabSimulink/Pages/home.aspx
Boeing GNC CoP: https://know.web.boeing.com/sites/GNC/Wiki/BoK.aspx
MATLAB/Simulink Training Resources: https://know.web.boeing.com/sites/GNC/Export%20Restricted%20Wiki/MATLAB%20Simulink%20Training.aspx
