### ISSUE TITLE
Support for Web Components

### ISSUE THREAD

**Issue by jandagroup** [olifolkerd/tabulator#2736]
**Is your feature request related to a problem? Please describe.**
Currently, I haven't found a straightforward way in order to get Tabulator to work within custom web components. For example, we're using a combination of LitElement as our base and Elix (https://component.kitchen/elix) for standard features/functionality and extending both for custom components as needed. 

**Describe the solution you'd like**
Enable the use of Tabulator within web components. Including thorough documentation and examples on how to properly implement the library. 

**Describe alternatives you've considered**
Too many trial and error hacks to list. None of which worked 🤣

**Comment by olifolkerd** [comment]
Hey @jandagroup 

did you find a solution to your issue?

Oli :)

**Comment by jandagroup** [comment]
@olifolkerd, I did, thanks! It appears I had to make some tweaks (at no fault to this library) on how/when I was initializing tabulator in the component lifecycle. 

One issue I did find is that when the “height” option isn’t set, the library throws an error that may be misleading (it lead me down a rabbit hole for a few days, haha). I’ll try to recreate it and post the exact error later.
