### ISSUE TITLE
Custom (non-AJAX) async data loader

### ISSUE THREAD

**Issue by rathboma** [olifolkerd/tabulator#2737]
## Problem
I'm working on an Electron desktop app. I need to load data using a custom API, not through a HTTP API, but with a TCP connection to a separate service I do not control.

I need to async-load data for the following actions:
- filtering
- paging
- sorting

I know this is supported by the `ajax` module for HTTP requests. I'd love if there was a way to generalize this approach for non-http apis.

## Suggested solution:

Be able to provide a callback to the Tabulator constructor for any/all of these actions.

```js
customLoader: (filters, paging, sorting, resolver) => {
   myWeirdApi.fetch(..).then((data) => { resolver.resolve(data) })
}

```

**Describe alternatives you've considered**
I could implement each of these individually by disabling the sorting, filtering, and paging plugins and managing my own header state, but that seems like the wrong way to do it long term.

**Comment by vec2k4** [comment]
Can't you override the [request promise](http://tabulator.info/docs/4.6/data#ajax-promise) to achieve your goal? Basically you can fetch whatever you want using whatever technique you need using this method. Plus you get all the information to do filtering, paging and sorting server-side.

I've setup a small fiddle which shows the idea: https://jsfiddle.net/vec2k4/qp518gbh/

**Comment by rathboma** [comment]
Yep that actually works great. Thanks!
