### ISSUE TITLE
movable rows in combination with grouped tabulator sometimes do not update group keys

### ISSUE THREAD

**Issue by vec2k4** [olifolkerd/tabulator#2738]
**Describe the bug**
When having a grouped tabulator with movable rows activated, moving a row from one group to another should update the row's group key like mentioned in the [documentation](http://tabulator.info/docs/4.6/move). This works fine if the row is dropped at a position in the new group that is not directly above a group row (watch the GrpKey column):
![tabulator-ok](https://user-images.githubusercontent.com/9272347/80543004-5c0ea580-89ae-11ea-85ec-5b02da7b605c.gif)

But if the row is dropped directly above a group row, it's group key is not updated and some other issues arise:
![tabulator-fail](https://user-images.githubusercontent.com/9272347/80543124-9415e880-89ae-11ea-87a5-2165f96036d5.gif)

**Tabulator Info**
- 4.6.2

**Working Example**
https://jsfiddle.net/vec2k4/ce9tbmxu/

**To Reproduce**
1. Go to the fiddle
2. Drag row with id 4
3. Drop it directly between id 3 and the group row (be careful, if you drag it too high it will work; just drop it when the placeholder gets visible)
4. See the group key for id 4 is not updating
5. Drag row with id 6
6. Drop it between id 1 and 2
7. See the group key for id 6 is updated, but id 4 moves back to the 2nd group

**Expected behavior**
I would expect the group key to be updated regardless of where in the new group the row is dropped.

**Screenshots**
see above

**Desktop:**
- OS: Windows 10 Pro 1909 (Build 18363.778)
- Browser: Edge
- Version 81.0.416.62 (64-Bit)

**Comment by olifolkerd** [comment]
Hey @vec2k4 

Thanks for the heads up,

I will add this to the fix list.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @vec2k4 

I have just pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)
