### ISSUE TITLE
Plug in to allow users to jump to a certain page if using pagination 

### ISSUE THREAD

**Issue by sarmad99** [olifolkerd/tabulator#2740]
*Why it is important to have:.**
pagination have page numbers but what if users want to jump to a certain page.
there should be ability to add an input box so the user can input a number then hit enter to go to that page. 

**Describe the solution you'd like**
there should be ability to add an input box so the user can input a number then hit enter to go to that page. 
In this link you will see same feature in [datatables](https://stackoverflow.com/questions/30666969/desired-page-in-pagination-with-datatables/30668366#30668366):

**Describe alternatives you've considered**
Using different platform
**Additional context**
This feature is highly requested for people that use [pagination  ](http://tabulator.info/docs/4.6/page) if there are 10 or 100 pages users should be able to jump to the desired page.

**Comment by nrayburn-tech** [comment]
It is possible to jump to a specific page of the table.  There is just not an input box created for you that is pre-built with Tabulator's pagination.
http://tabulator.info/docs/4.6/page#manage
https://stackoverflow.com/questions/61503969/desired-page-in-pagination-with-tabulator/61511845#61511845

**Comment by sarmad99** [comment]
Thank you for directing and helping me. This functionality works.
