### ISSUE TITLE
Deleting a row that failed validation causes mayhem

### ISSUE THREAD

**Issue by Jojoshua** [olifolkerd/tabulator#2741]
**Describe the bug**
When deleting a row which has failed validation, the table does not allow clicking any other rows/cells and the table is unusable. 

https://jsfiddle.net/jojoshua/axwfns7c/11/

**Tabulator Info**
4.6.2

**To Reproduce**
1. Click the Add Row button
2. Click inside the cell of the newly added 2nd row
3. Click outside the table(below it is fine). This causes the red validation error to display because this is set as required validator
4. Click the Delete Row button
5. Click on the cell of the existing first row. Observe thrown error e.getElement(...).focus is not a function is thrown in browser console. 

A similar scenario to reproduce is simply
1. Click the Add Row button
2. Click inside the cell of the newly added 2nd row
3. Click the delete button to delete that row

From here on out there the table is completely broken. The Add Row button will add rows but the cells are no longer editable. You cannot edit any existing data.

Appears related to previously closed issue 
https://github.com/olifolkerd/tabulator/issues/1733

**Comment by olifolkerd** [comment]
Hey @Jojoshua 

Im loving the title of this bug report!

Yup i can totally see what is going wrong there, that will be a quick fix.

I will get it in for the next patch release,

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @Jojoshua 

I have pushed a fix for this to the master branch and will include it in tomorrows patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
I also resolved an identical issue when deleting a column that contains a currently edited cell
