### ISSUE TITLE
Lazy loading 2nd level children in "Tree Structure"  does not indent correctly

### ISSUE THREAD

**Issue by Sakkanan** [olifolkerd/tabulator#2742]
Hi!
Thanks for the nice library! 

We are tying to load 10000s of rows, in tree structure, hence we need to load children record on demand ( upon clicking '+' ) otherwise perforance take a hit
 
Looks like there is no easy / direct way to update "_children", so tried with updating 'row'. but have intendation issue when we update 2nd level hierarchy 

here is the sample code 
`var tableData = [
    { name: "Oli Bob", location: "United Kingdom", gender: "male", col: "red", dob: "14/04/1984", _children: []},
    { name: "Jamie Newhart", location: "India", gender: "male", col: "green", dob: "14/05/1985" },
    { name: "Gemma Jane", location: "China", gender: "female", col: "red", dob: "22/05/1982", _children: [{name: "Emily Sykes",location: "South Korea",gender: "female",col: "maroon",dob: "11/11/1970" }]},
    { name: "James Newman", location: "Japan", gender: "male", col: "red", dob: "22/03/1998" }
];

var firstLevelChildren = [
    { name: "Mary May", location: "Germany", gender: "female", col: "blue", dob: "14/05/1982" },
    { name: "Christine Lobowski", location: "France", gender: "female", col: "green", dob: "22/05/1982" },
    { name: "Brendon Philips", location: "USA", gender: "male", col: "orange", dob: "01/08/1980", _children: [] }
];

var secondLevelChildren = [
    {name: "Margret Marmajuke", location: "Canada", gender: "female", col: "yellow", dob: "31/01/1999"},
    {name: "Frank Harbours", location: "Russia", gender: "male", col: "red", dob: "12/05/1966" }
];

var table = new Tabulator("#example-table", {
    height: 205,
    data: this.tableData,
    dataTree: true,
    layout: "fitColumns",
    columns: [
	    {   title: "Name", field: "name", width: 150},
        {   title: "Age", field: "age", hozAlign: "left", formatter: "progress"},
        {   title: "Favourite Color", field: "col"},
        {   title: "Date Of Birth", field: "dob", sorter: "date", hozAlign: "center"}
    ],
    dataTreeRowExpanded: function(row, level) {
        var rowData = row.getData();
        if (rowData["_children"].length > 0)
            return;

        if (level == 0) {
            row.update({
                "_children": firstLevelChildren
            });
        } else if (level == 1) {
            row.update({
                "_children": secondLevelChildren
            });
        }
        row.treeExpand();
    }
});`
**Tabulator Info**
4.4.3

**Working Example**
Here is the JS fiddler https://jsfiddle.net/cwe0xbdu/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Expand 1stRow Row (Oli Bob)
2. Click 3rd Row in  children list (Brendon Philips)
3. You will see 'Brendon Philips' gets indented as parent row

![image](https://user-images.githubusercontent.com/30183455/80658684-a427d980-8a3b-11ea-9867-87d434653173.png)

**Expected behavior**
Second level or nth level should get intended appropriately

**Comment by samcarswell** [comment]
This issue seems to go beyond indentation; it looks like the rows place in the tree structure is being changed when the data is lazy loaded.

I've updated the fiddle provided by @Sakkanan here: https://jsfiddle.net/069fn1sb/3/
with the following event:

`
rowClick: function(e, row) {
  console.log(row.getTreeParent())
}
`

**To Reproduce**
1. Expand Oli Bob
2. Click on Brendon Philips (don't expand it)
- This will print the Row Component for the parent; in this case the Oli Bob row. 
3. Expand Brendon Philips
4. Click on Brendon Philips again
- This will now print `false`; meaning it does not have a parent.

**Comment by Sakkanan** [comment]
Hi @samcarswell ,
Thanks for fixing this.  looking forward to have this fix in the next release

Thanks a lot !

**Comment by olifolkerd** [comment]
Hey @Sakkanan 

Thanks for the PR, i will merge it in for this Sundays patch release.

Cheers

Oli :)
