### ISSUE TITLE
header filter trick cross filters not with cross

### ISSUE THREAD

**Issue by unkelo** [olifolkerd/tabulator#2743]
In my Header Filter is use headerFilter:"tickCross" ,headerFilterParams: {tristate:true}
True Values are not filtered. They are not listet.
False works and the State for Both.

**Comment by olifolkerd** [comment]
Hey @unkelo 

If you wish to submit a bug report, please use the [Bug Report Issue Template](https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Possible+Bug&template=bug_report.md&title=) it will prompt you for all the information we need to help you out.

You must include a link to a JS Fiddle with a working example of your issue so we can understand the context of how your table is setup.

Cheers

Oli :)
