### ISSUE TITLE
Cell Height is Shrunk For Empty Strings

### ISSUE THREAD

**Issue by nrayburn-tech** [olifolkerd/tabulator#2744]
**Describe the bug**
Cells with a value of an empty string seem to render a very small height.

**Tabulator Info**
4.6.2

**Working Example**
https://jsfiddle.net/nrayburn/ujobcgz2/7/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. After opening/running the fiddle, the Table is created.
2. There are a few rows using various "bad" values.
    The row that has a value with an empty string has a very small height.  This causes it to be 
    difficult to edit.  Even after editing, it still seems to be shrunk in height.

**Expected behavior**
The cell height should be the same for an empty string value as for any other value.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Browser: Chrome
 - Version: 81.0.4044.129

**Comment by Jojoshua** [comment]
I've noticed this as well and I hope this can be improved. Have you tried calling redraw as a workaround, maybe in the cell edited event?

**Comment by nrayburn-tech** [comment]
It looks like using `table.redraw(true)` in the cell edit event will re-render the cell with the correct height once there is a value.  However, this doesn't solve the issue of the cell being difficult to initially select when it has the small height.  I think that is the bigger issue, because like you said it can just be redrawn after an edit.

**Comment by olifolkerd** [comment]
Hey @nrayburn-tech 

Ahh this is a regression in one of the last releases, this was fixed years ago. I will look into resolving it in the next patch release later this weekend.

Thanks for the heads up.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @nrayburn-tech 

I have pushed a fix for this to the master branch and will include it in this weekends patch release.

Cheers

Oli :)
