### ISSUE TITLE
persistence not saving formatterParams correctly for formatter="link"

### ISSUE THREAD

**Issue by AvnuTPM** [olifolkerd/tabulator#2745]
**Describe the bug**
This is a strange bug.  When options.persistence.column=true, the formatParams are not saved in localstorage correctly when using formatter="link".  I have a function that fixes a url for the link.  The function is not called anymore after the page is refreshed.  To recover, go to localStorage in the debugger and clear it, then refresh the page.  The function that fixes the url is called again but when the page is refreshed, it is no longer called.

**Tabulator Info**
- Tabulator 4.6

**Working Example**
https://jsfiddle.net/o26euphL/3/
https://codepen.io/mpaxson/pen/VwvMawM
NOTE:  jsFiddle and CodePen do not seem to support persistence so the problem cannot be demonstrated there.  However, the code that is posted does demonstrate the problem on Firefox and Chrome when run locally from an html file.  Below is the content for a local html file.

<!DOCTYPE html>

<html>

<head>

	<link href="https://unpkg.com/tabulator-tables@4.6.2/dist/css/tabulator.min.css" rel="stylesheet">

	<script	type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js"></script>

	<script type="text/javascript" src="https://unpkg.com/tabulator-tables@4.6.2/dist/js/tabulator.min.js"></script>

	<script type='text/javascript'>
	// https://jsfiddle.net/o26euphL/3/
	// https://codepen.io/mpaxson/pen/VwvMawM

		var FixURL = function(cell) {
			return "TextToInsert";
		};

		var tabledata = [
			{link:"1", data1:"12", data2:"red"},
			{link:"2", data1:"13", data2:"green"},
			{link:"3", data1:"14", data2:"blue"},
			{link:"4", data1:"15", data2:"yellow"},
		];
		
		var columns = [
			{title:"Link", field:"link", formatter:"link", formatterParams:{url:FixURL, target:"_blank"}},
			{title:"Number", field:"data1"},
			{title:"Color", field:"data2"},
		];
		
		$(function(){
			const div = document.createElement('div');
			document.body.appendChild(div);
			
			var myTable = new Tabulator("div", {
				data: tabledata,
				persistenceMode:"cookie",
				persistence:{
					columns:true,
				},
				columns: columns
			});	
		});
	</script>
</head>
<body>
</body>
</html>

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen or local file:
1. Create a local html file with the content shown in the working example above.
2. View the html file in a browser
3. Note the URL of the links in the first column will contain the text "TextToInsert".  This comes from the custom function FixURL
4. Refresh the page
5. Note the URL of the links no longer have the "TextToInsert".  This is the bug.
6. In the browser debugger, go to the localStorage and clear the data.
7. Refresh the browser and the "TextToInsert" is now in the URL of the links.
8. Refresh the browser and the "TextToInsert" is gone again in the URLs.
9. Disable persistence.columns by commenting it out or setting it to false.
10. Problem goes away.
11. Happens with localStorage and with Cookies.

**Expected behavior**
The custom function in the formatterParams.url is to always be called regardless of persistence.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 81.0.4044.129 and Firefox 75.0

**Comment by AvnuTPM** [comment]
For some reason, I cannot reproduce this in Chrome today.  However, the problem can be reproduced in Firefox.  Odd.

**Comment by olifolkerd** [comment]
This will because you are setting one of the values of a formatterParam property to a function. functions cannot be JSON encoded and therefore cannot be stored in local storage. which is why it does not work correctly.

Cheers

Oli :)

**Comment by AvnuTPM** [comment]
Interesting point, even though its not an inline function.  For proper operation, persistence should not be wiping out the url function in the formatterParam on restore.
