### ISSUE TITLE
Scroll To Row - Scroll to Cell pages upon Undo and/or Redo (There's a Workaround ... )

### ISSUE THREAD

**Issue by Joao-deOliveira** [olifolkerd/tabulator#2746]
This can be achieved by using row.pageTo or table.setPageToRow.

**Comment by olifolkerd** [comment]
I am unsure as to the purpose of this issue.

If you are requesting a feature, please use the [Feature Request Template](https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Suggested+Feature&template=feature_request.md&title=) it will prompt you for all the information we need.

Issues need to be more than just a title or they will be rejected.

Cheers

Oli :)
