### ISSUE TITLE
[Feature]: group row context menu

### ISSUE THREAD

**Issue by vec2k4** [olifolkerd/tabulator#2749]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to open a context menu in Tabulator by right clicking on a group header row. Even if there is a [callback ](http://tabulator.info/docs/4.6/callbacks#group) that intercepts the right click, there is (afaik) no way to simply open a context menu like there is for data rows.

**Describe the solution you'd like**
The behavior regarding context menus on groups should be the same as the behavior of context menus on data rows. So I suggest making appropriate changes to the code to achieve this behavior. The changes made in [this](https://github.com/olifolkerd/tabulator/compare/master...vec2k4:improvement-group-context-menu#diff-c1a8a21c933e1f48d90be645db83630f) commit should produce the appropriate result. A new option `groupContextMenu` is introduced analog to the option `rowContextMenu` known from data rows, which can be set to a function that works as a callback. The argument passed to the function is the corresponding group row.

A working example can be fond in [this](https://jsfiddle.net/vec2k4/7Lk5hnyp/) jsfiddle. Just right click on a group header to open the context menu.

**Describe alternatives you've considered**
Honestly, I have not considered any alternatives, because the described functionality belongs directly to Tabulator in my opinion.

**Additional context**
I will open a pull request to merge the functionality. The pull request contains the changes mentioned in issue #2729 and pull request #2730 regarding the context menus for group rows.

**Comment by olifolkerd** [comment]
Hey @vec2k4 

Great idea! Thanks for the PR, i will merge this in later this month with the 4.7 release.

I don't like having undocumented functionality sat on master, so i will keep the PR flagged for approval but not merged in until, i consolidate all outstanding PR's just before the release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
This feature has been merged in and will be included in the 4.7 release later today

Cheers

Oli :)
