### ISSUE TITLE
css add to select editor

### ISSUE THREAD

**Issue by pythonBerg** [olifolkerd/tabulator#2752]
Would be great to have css classes added to option construct for built-in select editor. I am mapping to hierarchical financial categories where debits are red...groups are bold...an optional class list associated with each option would allow css driven solution.

Low priority but helpful for my use-case.

Thanks

**Comment by olifolkerd** [comment]
Hey @pythonBerg,

Thanks for the suggestion. You actually make a good point that at the moment there is limited options for controlling anything out of the direct content of the list item.

I think we need a more extensive ***listItemFormatter*** that gives access to the containing element so you can make changes like add classes and styling directly to the list item.

As @takuy has already made a PR for this i will see if he is willing to offer a more expansive solution.

Cheers

Oli :)
