### ISSUE TITLE
Unexpected behavior custom formatter

### ISSUE THREAD

**Issue by pythonBerg** [olifolkerd/tabulator#2753]
I adding a custom select into tabulator cell. It is a large list common to all rows so pre-generating on server before render. I am successfully displaying this element in tabulator. Because the list is generic, I am hoping to use the formatter onRendered option to set a simple callback where an data attribute is set on the rows select object and a value is set using hidden column.

The callback is being executed, but this is happening before the select element is added to the DOM. This seems to defeat the whole purpose of the feature.

Is it possible to both create a custom formatted element and then provision a callback to modify once rendered. The provided example only shows post rendering callback...not prerendering format.

Thanks

**Comment by olifolkerd** [comment]
Hey @pythonBerg 

Please use the [Bug Issue Template](https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Possible+Bug&template=bug_report.md&title=) when reporting bugs as it will prompt you for the information we need to help you out.

We will need to see a JS Fiddle with a working example of the isssue so we an understand how your table is setup.

There is also a built in [Select Editor](http://tabulator.info/docs/4.6/edit#edit-builtin) available in Tabulator that may be able to help you out.

Cheers

Oli :)
