### ISSUE TITLE
Horizontal scrolling virtual DOM

### ISSUE THREAD

**Issue by imbasimba** [olifolkerd/tabulator#2758]
Hi Oli, 

You have created an amazing library! I’m currently integrating it into ESA’s astronomy portal [ESASky ](https://sky.esa.int) and most likely it is going to be integrated into a lot of other ESA astronomy archives. 

The killer feature that’s missing though is the horizontal virtual DOM, which I see you have in the “Future” column on Trello. As there is a lot of astronomy data with several hundreds of columns, this feature would be a life saver for the performance. Hidden columns still seem to have a significant impact on performance. 

I did not see any way to upvote that trello activity and I could not find a specific Github issue for this. So, on behalf of the rest of the agency, I just wanted to let you know that this feature would be very useful for us. 

Keep up the good work,
Henrik

**Comment by olifolkerd** [comment]
Hey @imbasimba 

Thanks for your kind words, It is always great to hear that Tabulator is appreciated!

And what an exciting project you are working on there! I wasnt planning on adding in a horizontal virtual DOM till version 5.0 but i have some ideas i can look to include in the 4.7 release this month that may help you out.

Can i ask what table layout mode you are using? is it "fitData"?

Cheers

Oli :)

**Comment by imbasimba** [comment]
Hi @olifolkerd 

I'm glad to hear you already have ideas for improvements.

We are using "fitDataFill", but right now it appears to behave just like "fitData". I haven't yet investigated why.

Here is a gif demonstrating the basic idea and table structure:
![TabulatorExample](https://user-images.githubusercontent.com/6043863/81412835-c066fd00-9144-11ea-9bc4-75753f24ebfc.gif)
(of course, with potentially thousands of extra rows and maybe a worst case scenario of ~500 columns)

If you still would like some sort of JSFiddle, maybe I can create something remotely similar next week. Or maybe just give you access to our integration environment

**Comment by olifolkerd** [comment]
Hey @imbasimba 

fitData works exactly the same as fitDataFill, the only difference is that with fitDataFill if the total column width is less than the width of the table it stretches the rows to fill the space. as your columns exceed the width of the table, it behaves exactly the same as fitData.

The number of rows dosnt concern me too much, one user had so many rows, they hit the maximum height for a scroll bar that a web browser will allow (in the millions of rows). the number of columns is the interesting part. 

There would be no need to replicate the whole site in a fiddle, just your table constructor and a few rows of data to dive me an idea of what i would be dealing with would be great.

Cheers

Oli :)

**Comment by imbasimba** [comment]
Hi @olifolkerd 

Yes, the performance for crazy numbers of rows is very impressive. For a high number of columns, performance starts to degrade quite quickly though, especially when tabulator writes to the real DOM. 

Here is a fiddle with some real data from the Chandra source catalog with 515 columns. 
[Fiddle](https://jsfiddle.net/wpa9x4vh/1/)
Even with only a handful of columns showing from that dataset, performance really suffers.

Cheers,
Henrik

**Comment by Joao-deOliveira** [comment]
Hi all,

Using tables with 200 columns I'm getting this also, so, would be great if we have a Horizontal Virtual DOM option.

Cheers
João

**Comment by olifolkerd** [comment]
Hey @imbasimba 

Thanks for that fiddle that is very helpful. the dataset is particularly useful there.

Are you using autocolumns in your live table definitions?, if so then your approach of hiding columns after the table has loaded will actually slow things down as the table is loaded and then the columns are hidden one by one, it would be better to specify the needed columns at the point of table definition. or if you have to use auto tables then look at using the ***blockRedraw** function to prevent redrawing of the table on each column hide, you can read more about this in the [Redraw Management Documentation](http://tabulator.info/docs/4.6/layout#virtual-dom-redraw)

I am having a tinker with a column vDOM at the moment, but this is likely to be a longer term project to get in as it isnt as simple as the vertical virtual DOM, columns widths and in some cases row heights are determined by the width and layout of column contents *(depending on layout modes)* which makes it hard to do the calculations to layout the table before the data is already in it. It would also interfere with certain row formatters and the frozen column system.

At this point I dont think i will have a finished version available for the 4.7 release as i need to get that out shortly, but i will stick it on the roadmap for 4.8 to see what i can do for then.

Cheers

Oli :)

**Comment by imbasimba** [comment]
Hey @olifolkerd 

We are not using autocolumns. Take your time with the vDOM, 4.7 already has features we will use. 

Good luck with the vDOM,
Henrik

**Comment by rathboma** [comment]
To weigh in here - I run Beekeeper Studio (https://github.com/beekeeper-studio/beekeeper-studio). A SQL editor that uses Tabulator for table views, and for SQL query results.

We LOVE tabulator, and we're excited for 4.7. But we do also struggle with very wide datasets. Many users report poor performance on tables with 30+ columns. Here's an example ticket - https://github.com/beekeeper-studio/beekeeper-studio/issues/135

What's the best way for us to support this effort? I am not very experienced with the Virtual DOM, but would love to help.

**Comment by olifolkerd** [comment]
Hey @rathboma 

Thanks for getting in touch, 

Unfortunately there wasnt enough time to get this in for the 4.7 release as it would have significatly delayed the release of the other features but i will look into getting a limited version in for the 4.8 release.

If you have an example of how your tables are currently configured i would be happy to take a look and see if i can advise and configuration changes that will speed things up for you in the mean time.

I am looking to do a complete rebuild of the virtual DOM as part of the 5.0 release later in the year so i will use this as a chance to trial some of the potential new features.

Cheers

Oli :)

**Comment by rathboma** [comment]
Hey @olifolkerd,

You rock. We use Tabulator in several places, [here is our query-results table](https://github.com/beekeeper-studio/beekeeper-studio/blob/master/src/components/editor/ResultTable.vue#L65), [here is our full-table view](https://github.com/beekeeper-studio/beekeeper-studio/blob/master/src/components/tableview/TableTable.vue#L132).

I'd say we have the most issues with our query-results. While allow users to have up to 50,000 records in the table at a time, we see the most problems with tables that have 100+ columns, even with as few as a few dozen results.

Ironically it's not scrolling left/right that causes the problem, but scrolling up/down.

Here's an example:

0. Download and install Beekeeper Studio
1. Download a basic SQLite database, [like this one](https://github.com/ivanceras/sakila/tree/master/sqlite-sakila-db)
2. Create this table 'mytable' with 63 columns: https://gist.github.com/rathboma/9de6e91470040aec592cdc15e74b86c2
3. Open a new tab and run 'select * from mytable'
4. Scroll left / right (smooth!)
5. Scroll up / down (not smooth)

**Comment by rathboma** [comment]
Is a library like 'clusterize.js' useful for this? https://github.com/NeXTs/Clusterize.js

**Comment by olifolkerd** [comment]
Not really.

Adding the horizontal aspect is complex because of the number of other modules it interacts with like frozen columns and reactive data.

I have a plan in place for how to achieve it. It I just a matter of scheduling for when I get it in.

At the moment the large number of columns is a bit of an edge case for normal users and so it has been lower down the priority list than other feature updates.

I will look at getting in a initial version in the next release and a full version will be comming in the 5.0 release as stated above.

Cheers

Oli :)

**Comment by rathboma** [comment]
Got ya. You do amazing work! Thanks so much for making Tabulator. Looking forward to the next release :-).

**Comment by olifolkerd** [comment]
Hey Everyone,

You will happy to hear i have just push the horizontal virtual DOM feature to the 4.8 branch which will be released next weekend.

Cheers

Oli :)
