### ISSUE TITLE
keywordFilter / Improved text search - Custom header filter to Built in filter

### ISSUE THREAD

**Issue by 8483** [olifolkerd/tabulator#2759]
I am aware that we can make custom filters, but I think this addition is really useful to come out of the box.

[Here's a working example of what I mean](https://codesandbox.io/s/nameless-https-oep0q?file=/src/index.js).

In the first column, it's the regular "like" text filter and if you search for a `red car` it finds 1 item.

In the second column, if you search for `red car` it finds 2 items.

The first one doesn't take into account the order of the search parameters, as well as typos.

This addition would significantly improve our lives.

I don't know the codebase well enough to code it myself for a pull request.

Here's the code:

```js
let data = [
  { string: "red car" },
  { string: "blue car" },
  { string: "black car" },
  { string: "car red" }
];

var table = new Tabulator("#example-table", {
  data: data, //load row data from array
  layout: "fitColumns", //fit columns to width of table
  columns: [
    { title: "regular search", field: "string", headerFilter: true },
    {
      title: "improved search",
      field: "string",
      headerFilter: "input",
      headerFilterFunc: improvedTextSearch
    }
  ]
});

function improvedTextSearch(headerValue, rowValue, rowData, filterParams) {
  //headerValue - the value of the header filter element
  //rowValue - the value of the column in this row
  //rowData - the data for the row being filtered
  //filterParams - params object passed to the headerFilterFuncParams property

    // extract search keywords
    let searchParts = headerValue.toLowerCase().split(" ");
    let partsArray = []
    // check if each keyword is present in the cell
    searchParts.forEach(part => {
        // add the boolean to the truth array
        partsArray.push(rowValue.toLowerCase().includes(part))
    });

  // Checks if all array elements are true
  return partsArray.every(field => field); //must return a boolean, true if it passes the filter.
}
```

**Comment by 805bluebell** [comment]
Looks promising. We can call this `keyword filtering`.
But, I am not sure if it should be packed as standard though.

**Comment by 8483** [comment]
I believe it's a common enough use case to be a standard option. ex. It's insanely common to search products with typos and different word order.

**Comment by olifolkerd** [comment]
Hey @8483 

Thanks for the suggestion, i think that is a wonderful idea.

I would certainly be happy to add that as a built in filter function so that users can choose to a full keyword search if they want.

I will add this to the roadmap for release in version 4.7 later this month.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @8483 

I have just pushed this feature to the 4.7 branch which will be released in a week or two.

There is now a builtin ***keywords*** filter. By default it will match any string containing any of the words. there is an optional ***matchAll*** filter params property to force it to include all the keywords in the match.

So from your example it would be:
```js
{
      title: "improved search",
      field: "string",
      headerFilter: "input",
      headerFilterFunc: "keywords",
      headerFilterFuncParams:{matchAll:true}
    }
```
Cheers

Oli :)

**Comment by 8483** [comment]
Awesome! Thank you so much for the inclusion.
