### ISSUE TITLE
how to insert with wordpress backend?

### ISSUE THREAD

**Issue by 1manfactory** [olifolkerd/tabulator#276]
Hello,
I am using tabulator very successfully on a very pure intranet website
Now I would like to include it into my own Wordpress backend plugin.
The problem is that Wordpress comes with it's own way of using jquery. Hence I am not allowed to use $()
I encapsuled my code with
```
(function($) {
$("#example-table").tabulator({
...
})( jQuery );
```
But I still get this errors
Uncaught TypeError: Cannot read property 'widget' of undefined
Any idea?

**Comment by olifolkerd** [comment]
That is the error you get when the jQuery UI library isn't included.

Tabulator is dependant on both jQuery and jQuery UI.

If you include the jQuery UI js file before the Tabulator js file you should be fine.

Cheers

Oli

**Comment by 1manfactory** [comment]
Sorry, don't close it.
It still does not work. I still get he same error message.
Do you have an example where it used to work?

**Comment by olifolkerd** [comment]
https://codepen.io/olifolkerd/pen/pEjOdy
