### ISSUE TITLE
updateData visible rows don't resize if needed

### ISSUE THREAD

**Issue by jots** [olifolkerd/tabulator#2760]
**Describe the bug**
when using updateData() the row doesn't get taller if needed when for example
a formatter of "html" and a call like: 
`myTable.updateData([{link:1, data1: "this<br>is<br>cut off"}]);`

**Tabulator Info**
4.6.2

**Working Example**
https://jsfiddle.net/6esyuxp7/1/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://jsfiddle.net/6esyuxp7/1/
2. Look at second column of first row, should be taller

**Comment by olifolkerd** [comment]
Hey @jots 

Thanks for getting in touch, you have definitely found a bug there,

I will look into that for the next patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @jots 

I have pushed a fix for this to the master branch and will include it in this weekends patch release.

Cheers

Oli :)

**Comment by jots** [comment]
Thank you Oli!  
It works great!  you are the best!
