### ISSUE TITLE
Header tooltip cut short

### ISSUE THREAD

**Issue by 8483** [olifolkerd/tabulator#2764]
[Sandbox](https://codesandbox.io/s/throbbing-silence-19i13?file=/src/index.js)

Ok, this might be pushing it a bit, but why is the tooltip cut short? Is there a control for this?

**Comment by nrayburn-tech** [comment]
It looks like just the `title` attribute is used on the element.  As far as I can tell, that is completely dependent on the browser/OS.  The only way to get control of that is to create custom tooltips with css and javascript.

**Comment by olifolkerd** [comment]
Hey @8483 

As @nrayburn-tech says, this is a limitation of the browser im afraid. If you want a more bespoke tooltip experience you would need to look at using a [Custom Formatter](http://tabulator.info/docs/4.6/format#format-custom) and one of the many great tooltip plugins that are out there.

Cheers

Oli :)
