### ISSUE TITLE
[Possible bug] placeholder not working in 4.6

### ISSUE THREAD

**Issue by guanicoe** [olifolkerd/tabulator#2766]
Hi, 

I cannot display placeholder to work on 4.6. It works on 4.5 though. Is this a known issue?

G

**Comment by olifolkerd** [comment]
Please follow the [Bug Reporting Guidelines](http://tabulator.info/community#bug) and use the [Bug Issue Template](https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Possible+Bug&template=bug_report.md&title=) when reporting a bug.

We need a JS fiddle to show us how your table is setup and demonstrate the issue. without it we cannot offer any meaningful advice on how to help you out.

Cheers

Oli :)
