### ISSUE TITLE
Deprecation warning when using headerFilterParams lookup function

### ISSUE THREAD

**Issue by cgountanis** [olifolkerd/tabulator#2768]
I get this warning when using the example as-is. I can live with the mispelling of WANRING but wondering if the example or the warning is not correct? You will notice I am not even using editor. All the other headerFilter: select, seem to work fine. Something with the dynamic population of the dropdown list maybe? I also think the headerFilter should be select not input as it is a dropdown example, right?

DEPRECATION WANRING - values for the select editor must now be passed into the values property of the **editorParams** object, not as the **editorParams** object tabulator.js:14533:13

```
//define lookup function
function paramLookup(cell){
    //do some processing and return the param object
    return {param1:"green"};
}

//column definition
{title:"Name", field:"name", headerFilter:"input", headerFilterParams:paramLookup}
```

![image](https://user-images.githubusercontent.com/14899817/81489204-8c6d0400-9238-11ea-84b3-de7f66b7b8ca.png)

**Comment by cgountanis** [comment]
The reason for this is ajaxProgressiveLoad: scroll but would like to have the headerFilter:select get a full distinct list for ajaxFiltering, not just what is shown on the table currently e.g. headerFilterParams: { values: true }. Maybe there is a better way?

**Comment by olifolkerd** [comment]
Hey @cgountanis 

That is just a documentation error there, the way that the editor is passed its value list changed a couple of versions ago and i must have missed that one in the documentation. I will get that updated later today.

I will also fix the typo in the warning, thanks for pointing that out.

Could i ask that you don't use block capital issue titles, they are alarmist and wont get issues seen to any faster, as per the [Community Guidelines](http://tabulator.info/community#help) it asks for issues to be submitted with a descriptive non-block capital title.

Cheers

Oli :)

**Comment by cgountanis** [comment]
No problem, I just copy pasted the error from console.
I did change the headerFilter:"input" from the example to select, why would you be populating if it didn't show up right? I am not using editor and the error seems a bit hard to understand. See what I'm saying?

**Comment by cgountanis** [comment]
Maybe there's a better way. I am brand new and so far loving Tabulator. What do you recommend to dynamically populate a drop-down from an Ajax call for example?

**Comment by olifolkerd** [comment]
I will fix the typo in todays patch update, but that message is definitely only displayed when a select editor is used as an editor or header filter.

could you post a link to a JS fiddle that shows how your table is setup, i can then offer some advice on where the issue may be.

Cheers

Oli :)

**Comment by cgountanis** [comment]
Here you go. It is switched to select which is what the example, I think, should be using since you are filling a dropdown, right? Notice I am not using editor at all.

https://jsfiddle.net/ChrisGo/a45ur9hv/4/

**Comment by olifolkerd** [comment]
Thanks for that i see the issue.

First off you are using an editor even if you don't realise it, the header filtr system uses edtiors to build the elements and manage input validation, so when you are setting the header filter to "select", what you are actually doing is telling tabulator to place a select editor in the column header and use the value to filter the column. 

> you can pass a string to this parameter containing any of the standard editors listed in the Manipulating Data section

The reason you are getting the error is becasuse you are returning a value list from your param lookup, you should be returning header filter params, so in your case it should be:

```js
function paramLookup(cell) {
        //do some processing and return the param object
        return {
            values:{ "a": "A", "b": "B" };
        };
    }
```

If you have a look at the built in [Editor Documentation](http://tabulator.info/docs/4.6/edit#edit-builtin) you can see what params are valid.

Cheers

Oli :)

**Comment by cgountanis** [comment]
Yes I think I need to use the function because I want to use Ajax to get a distinct list from the database. That hard-coded list was just for testing. we still good with that example or how would I do that?

**Comment by olifolkerd** [comment]
You wouldn't be able to use ajax in that function, it needs to return the value so using anything asynchronous like ajax would result in it returning undefined.

Your best approach in that instance would be to load the values in before hand to an external object and then reference the in,

The other option would be to use an autocomplete editor which allows you to to return a Promise from the searchFunc, so you could do an async search request there.

Cheers

Oli :)

**Comment by cgountanis** [comment]
We'll dig into that thank you. Doing all server side filtering so you can see kind of need the complete distinct list for the header filter drop down. Thanks

**Comment by cgountanis** [comment]
This worked no more warning. I did have to remove the semicolon from the end of the values: line. Might as well spice up the documentation. I am sure others are looking to populate a "select" header with values.

```
//define lookup function
function paramLookup(cell) {
	//do some processing and return the param object
	return {
		values: { "1": "Blue", "2": "Green", "3": "Red", "4": "Yellow" }
	};
}
```
