### ISSUE TITLE
Add reference to Column definition and/or mutatorParams to custom Mutators

### ISSUE THREAD

**Issue by rjcorne** [olifolkerd/tabulator#277]
This is a similar request as #263 except for custom Mutators instead of Formatters.  I'm trying to transform the value into a link to another page that includes some parameter information and values from other fields as defined in the specs, but there's no way I can see to pass that information.

By the way, love Tabulator! Thanks for creating it!

Rory

**Comment by olifolkerd** [comment]
Hi Rory,

Thanks for getting in touch, you are in luck! that exact feature is coming in the next release.

If you like Tabulator now, just wait till version 3.0 comes out next month, it is a ground up rebuild with tons of new features and massively improved performance.

Cheers

Oli

**Comment by rjcorne** [comment]
Great! I'm excited to see what all you have in store for version 3.0!

**Comment by olifolkerd** [comment]
Hi Rory,

Could you give me an example of what you are trying to pass into your mutator, is it just other data values from the same row or is it setup options?

Cheers

Oli

**Comment by rjcorne** [comment]
Hi Oli,

Ideally, I'd like to have both values from the same row and setup options. I'm trying to create a drill-thru link to another report. The config options tell which report and which fields need to be passed as parameters for the target report. Then the data values from the row are used to populate the parameters for sending.  Does that make sense? If not, I can put together a couple tables to show it better.

Thanks,
Rory

**Comment by olifolkerd** [comment]
I have just added the ***mutatorParams*** and ***accessorParams*** properties to the column definition objects.

Full documentation can be found [here](http://olifolkerd.github.io/tabulator/docs/3.0/#get-set)

Let me know if that is what you were after.

Cheers

Oli

**Comment by rjcorne** [comment]
Hey Oli,

Thanks for the update! I'm finally getting a chance to look into this again. It seems there needs to be a simple change for the extending Mutators in the 3.0 release. Currently on line 8475 it says:
`if (self.mutators[column.definition.mutator]) {`
However, "self" here does not contain the list of mutators. Looking at the similar part where formatters are defined, I see that at the beginning of the initialization along with setting the config variable, it's setting self=this.
` Format.prototype.initializeColumn = function (column) {

    var self = this,
        config = { params: column.definition.formatterParams || {} };
`
 The Mutator initialization just sets config. Other than that, 3.0 is looking good!

Thanks,
Rory

**Comment by olifolkerd** [comment]
Hey Rory,

Thanks for the feedback i have just committed a fix for this

Cheers

Oli
