### ISSUE TITLE
Header Filter doesn't work after hitting Enter

### ISSUE THREAD

**Issue by tosbaha** [olifolkerd/tabulator#2770]
**Describe the bug**
Header Filter doesn't work after hitting Enter

**Tabulator Info**
v4.6

**Working Example**
http://tabulator.info/examples/4.6?#filter-header

**To Reproduce**
1. Go to the documentation web site. 
2. Enter a value to Max input
3. Hit Enter
4. The table doesn't get updated.

**Expected behavior**
The table should update with values

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox,Safari
 - Version Latest

**Additional context**
After hitting enter, if we click outside of the table, it gets updated properly.

**Comment by olifolkerd** [comment]
Looks like an issue in the example code, i will fix that in the next site update.

It is not a  bug with tabulator itself.

Cheers

Oli :)

**Comment by tosbaha** [comment]
I tested v4.7 and the issue still exists. If it is not bug of tabulator, could you post the fixed documentation?

**Comment by olifolkerd** [comment]
The issue is still open which means I haven't got round to fixing it yet I'm afraid.

When the issue is closed it will mean a fix has been pushed.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @tosbaha 

I have fixed the example, there was a missing option in the column definition, `headerFilterLiveFilter:false`

Cheers

Oli :)
