### ISSUE TITLE
Setting Filters

### ISSUE THREAD

**Issue by cgountanis** [olifolkerd/tabulator#2771]
I have a checkbox that on toggle sets a filter, noticed it was creating duplicates with the same name. So, I tried different combinations of these examples but every every hit they cause the table to refresh. Is there a way to let the filter work happen then let the ajaxFiltering kick in after it's complete for a single hit to the API?

```
table.clearFilter();
table.removeFilter("showSomething", "=", !this.checked);
table.addFilter("showSomething", "=", this.checked);
```
https://stackoverflow.com/questions/61718690/tabulator-ajaxfiltering-add-remove-filters

**Comment by cgountanis** [comment]
https://stackoverflow.com/questions/61718690/tabulator-ajaxfiltering-add-remove-filters

**Comment by cgountanis** [comment]
I added it but I thought it might just be easier to get it right from the source :)

**Comment by takuy** [comment]
Sounds like you could just just use setFilter() instead of both removeFilter() and addFilter(). Though, from my experience though, you would still need to call clearFilter(). Sounds like something setFilter() would already take care, but it didn't work last time I used them in an app.

**Comment by cgountanis** [comment]
Set filter was creating a bunch of duplicates of the same setting.

**Comment by takuy** [comment]
Are you sure it's Tabulator that is handling the data wrong? Is your API endpoint returning dupes? Not sure how private your data is, but a JSfiddle or codepen with the issue (even with a mock API with fake data)

**Comment by cgountanis** [comment]
Yeah I sat the Ajax to post and every time you hit one of those functions it sends all of the filters and when you add a filter with the same name it just keeps sending it as multiple same with query string.

**Comment by cgountanis** [comment]
Here is a better example I guess. I switched to GET so it would be easier to visualize.  I have a check box that when clicked check/unchecked it adds the same filter and you get tons of duplicates.

I guess it would be nice if it found a matching filter name, it should just replace and not add unless people use that for some kind of same name array functionality, not sure why.

So I was thinking, I would clear or remove then add but since AJAX Fitlering is enabled it fires a call to the API each line, the remove then the add. Just unneeded hits to the API.

```
// Handles the show closed filter.
$(".show-closed-filter").on("click", function () {
    console.log("show-closed-filter");
    console.log(this.checked);
    //table.clearFilter();
    //table.removeFilter("showclosed", "=", !this.checked);
    table.addFilter("showclosed", "=", this.checked);
});
```

`?page=1&size=10&filters%5B0%5D%5Bfield%5D=showclosed&filters%5B0%5D%5Btype%5D=%3D&filters%5B0%5D%5Bvalue%5D=true&filters%5B1%5D%5Bfield%5D=showclosed&filters%5B1%5D%5Btype%5D=%3D&filters%5B1%5D%5Bvalue%5D=false&filters%5B2%5D%5Bfield%5D=showclosed&filters%5B2%5D%5Btype%5D=%3D&filters%5B2%5D%5Bvalue%5D=true&filters%5B3%5D%5Bfield%5D=showclosed&filters%5B3%5D%5Btype%5D=%3D&filters%5B3%5D%5Bvalue%5D=false&filters%5B4%5D%5Bfield%5D=showclosed&filters%5B4%5D%5Btype%5D=%3D&filters%5B4%5D%5Bvalue%5D=true`

**Comment by cgountanis** [comment]
I think I found it. The documentation should add a simple line about setFilter(). Sneaky bugger :)


`table.setFilter("showclosed", "=", this.checked);` vs `table.addFilter("showclosed", "=", this.checked);`
