### ISSUE TITLE
[Feature] cell.edit(false) to force the editor to false even if editable is set to true

### ISSUE THREAD

**Issue by Jojoshua** [olifolkerd/tabulator#2772]
I would like to see the ability to override editable on a per cell basis using the cell.edit method.

The capability already exists for overriding to true but not to false.
http://tabulator.info/docs/4.6/components#component-cell
_If you want to ignore the editable property of the column definition and force the edit, you can pass an optional value of true to the function
**cell.edit(true); //force the editor to open even if editable is set to fals**e_

**Describe the solution you'd like**
Calling cell.edit(false) would force the editor to false even if editable is set to true

**Comment by olifolkerd** [comment]
I'm not sure of the purpose of this. The cell.edit(true) dosnt change the editable property it triggers an edit in the cell.

Thefore have a false value for it would be incongruous.

If you just want to vary the editability of a cell you should pass a callback to the editable property which will be evaluated each time the cell has focus and can be used to vary the editability of the cell.

**Comment by Jojoshua** [comment]
I still want to be able to set the editable to either true or false as it is being directly set when I load the table(saved from configuration).

I think I understand what you are saying in terms of the API language though..looking in those terms I believe what I am looking for is cancelEdit, is that right?

**Comment by olifolkerd** [comment]
Hey @Jojoshua 

Im still a bit unsure what you are after, but if you want to cancel an edit after it has started then ***cancelEdit*** is the function for you.

Cheers

Oli :)

**Comment by Jojoshua** [comment]
What I am ultimately trying to do is come up with an "Append Only" mode where users can hit an Add Row button to add a new row and enter data but never edit previously saved data.

**Comment by olifolkerd** [comment]
Ahh ok for that i would suggest that you have a field in your data that is called "editable", that is set true on objects created through the "Add Row" button and false on data loaded through ajax.

Then on the column definition editable prop use a callback to check if the editable prop is true in the row data

I hope that helps,

Cheers

Oli :)

**Comment by Jojoshua** [comment]
I am actually storing the column definition to database which has the editable property and then reloading the definition along with the table data.

I tried calling cell.cancelEdit() within the cellEditing event but it did not cancel the editing and also saved the data I entered, is that a bug?

**Comment by olifolkerd** [comment]
It is hard to determine how you are using ***cancelEdit*** from a one line description with no code, so i couldnt tell you why it isnt working in your case

The approach i outline above is the correct approach in this instance. you will just need to map the function on to the editable prop of the column definition before you load it into the table.

Cheers

Oli :)

**Comment by Jojoshua** [comment]
Sorry, so for example something simple like this. If the user had clicked inside a cell to trigger the cellEditing event, do you expect they be "kicked out (loose focus and not save any changes they input)" after 2 seconds with this code? 

`(colDef.cellEditing = cell => {
    setTimeout(() => {
        cell.cancelEdit();
    }, 2000);
}),`

**Comment by olifolkerd** [comment]
Can you post a link to a JS fiddle please

**Comment by Jojoshua** [comment]
So apparently the timeout is the key.

By adding a 2sec timeout here does cancel as expected
https://jsfiddle.net/jojoshua/qLymad36/5/

Without a timeout the cancelEdit never registers and allows the user to keep editing.
https://jsfiddle.net/jojoshua/3qokdubL/1/

**Comment by olifolkerd** [comment]
Hey @Jojoshua 

You shouldn't need a whole 2 seconds, 10 - 100 ms should do the trick.

The reason this is needed is because the ***cellEditing*** callback is called as soon as the editor is triggered but before the editor has actually been instantiated, so it needs a short time to instantiate the editor before it can be cancelled.

Cheers

Oli :)

**Comment by Jojoshua** [comment]
Ok thanks, will run with this. Keep up the good work.
