### ISSUE TITLE
IE compatibility - Object doesn't support property or method 'assign'

### ISSUE THREAD

**Issue by kapenzo** [olifolkerd/tabulator#2773]
I use ver. 4.5.3
In IE 11 there is a problem with Object.assign because the IE browser doesn't support it.
Example:
https://github.com/olifolkerd/tabulator/blob/b294a53bf39ba082420a3d1d9d913b744e9dea1d/src/js/modules/mutator.js#L93
Reference:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

Could you add it to polyfills.js file to support the IE 11 browser?
Thank you in advance.

**Comment by olifolkerd** [comment]
Hey @kapenzo 

Sorry to hear you are having issues, i can certainly look into that.

Could you post a link to a JS Fiddle that replicates your issue, i need a test case the demonstrates it so i can test that i have properly fix it.

Please see the [Bug Reporting Guidelines](http://tabulator.info/community#bug) for more details.

Cheers

Oli :)

**Comment by kapenzo** [comment]
Thank you for the answer @olifolkerd 
in JSFiddle and codepen I am getting a msg that the IE11 is not supported.
Yes I added the polyfill to my code, so it was working in the end, but I wanted to warn you about this issue.

**Comment by olifolkerd** [comment]
Hey @kapenzo 

I have pushed an update to the 4.7 branch  to include this in the builtin Polyfill file.

Cheers

Oli :)
