### ISSUE TITLE
cell context menu when clicked on an editable cell, the cell becomes also in edit mode

### ISSUE THREAD

**Issue by Joao-deOliveira** [olifolkerd/tabulator#2776]
Hi there,

I've a table where most of the cells are editable having also a context menu associated at column level. What's happening is that if I click for getting the context menu, the cell becomes in mode edit at the same time, which somehow invalidates one of the two actions.. the edition and the context menu. To note that both work at the same time ... 

Is this a bug? or there's a way to prevent this behaviour ?

Thanks for this great tool .. I'm a fan :-)

cheers
João

**Comment by nrayburn-tech** [comment]
I would think if you right click, it should not go into edit mode.  It should only show the context menu.

Example
https://jsfiddle.net/nrayburn/u12jopch/5/

Run the Fiddle.
Right click a cell.
Type characters.  The context menu is displayed, while in edit mode and able to type.  Seems kind of confusing.

**Comment by Joao-deOliveira** [comment]
Hi @nrayburn-tech,

You right! 

My fault, explanation not complete. If the column has a validator associated, then the issue appears, 

if you use 
const columns = [
	{
		title: "Name",
		field: "name",
		editor: "input",
    validator: {
    	type : "string",
      minLength: 1,
      maxLength: 20,
    }
	}
]

and run the example https://jsfiddle.net/nrayburn/u12jopch/5/ then you see the problem,

Thanks for your reply, much appreciated.

As a suggestion, can we, in the future, have the possibility to pass a CSS class on the menu definition ;-) ?

**Comment by Joao-deOliveira** [comment]
> 
> 
> I would think if you right click, it should not go into edit mode. It should only show the context menu.
> 
> Example
> https://jsfiddle.net/nrayburn/u12jopch/5/
> 
> Run the Fiddle.
> Right click a cell.
> Type characters. The context menu is displayed, while in edit mode and able to type. Seems kind of confusing.

As a suggestion, think that when right-click, to get the Context Menu, on an editable cell, the edition should not be possible... as is, works but gets confusing 

Thanks for your support
Cheers

**Comment by olifolkerd** [comment]
Hey All,

Thanks for pointing that out, there are some upgrades coming out in edit, validation and menus in the 4.7 update in a few weeks, i will make sure this is patched then.

Cheers

Oli :)

**Comment by Joao-deOliveira** [comment]
> 
> 
> Hey All,
> 
> Thanks for pointing that out, there are some upgrades coming out in edit, validation and menus in the 4.7 update in a few weeks, i will make sure this is patched then.
> 
> Cheers
> 
> Oli :)

Thanks Oli :-) 

This is super 👍

**Comment by olifolkerd** [comment]
Hey All,

I have pushed a fix for this to the 4.8 branch which should be released in the next couple of weeks.

Cheers

Oli :)
