### ISSUE TITLE
the 'column.getCells()' only returns the visible cells and not all the cells on the column

### ISSUE THREAD

**Issue by Joao-deOliveira** [olifolkerd/tabulator#2779]
Hi there,

Working on something that needs to update an entire column (all cells on) with a new value. Once running I'm using the 'column.getCells()' , which accordantly to the doc, should return an array with all cells. It returns but only the ones visible on the current page and not all rows on the column.

Is this a bug? 

If it's normal due to the Virtual DOM, how can I get all cell of a column?

Thanks for your attention
Cheers
João

**Comment by olifolkerd** [comment]
Hey @Joao-deOliveira 

Cells are only created when rows are first rendered, so if the user has not yet scrolled to the row the cell will not exist.

The correct approach would be to get all of the rows of the table by calling the ***getRows*** function, then itterate over each row, chaging the value with the ***update*** function on the row component.

If you want to prevent the table from redrawing while you are changing the rows you can use the ***blockRedraw*** function of the table. for more information on this, check the [Documentation](http://tabulator.info/docs/4.6/layout#virtual-dom-redraw)

Cheers

Oli :)

**Comment by Joao-deOliveira** [comment]
> 
> 
> Hey @Joao-deOliveira
> 
> Cells are only created when rows are first rendered, so if the user has not yet scrolled to the row the cell will not exist.
> 
> The correct approach would be to get all of the rows of the table by calling the _**getRows**_ function, then itterate over each row, chaging the value with the _**update**_ function on the row component.
> 
> If you want to prevent the table from redrawing while you are changing the rows you can use the _**blockRedraw**_ function of the table. for more information on this, check the [Documentation](http://tabulator.info/docs/4.6/layout#virtual-dom-redraw)
> 
> Cheers
> 
> Oli :)

Thanks Oli for the prompt response ... that's what I imagined... 
Cheers

**Comment by Joao-deOliveira** [comment]
Hi there,

sorry being back on this issue,...
**_getRows_** returns all rows 
when we iterate over each row and using **_row.getCell("<column name>")_** if the cell isn't visible, the _**row.getCell**_ returns 'false' .. therefore we can't use **_cell.getValue_** or _**cell.setValue**_
https://jsfiddle.net/9byhpf3o/

actually, looking inside the returned array the rows having cells not visible, the row.cells array show 0 cells.

![image](https://user-images.githubusercontent.com/63957815/81794270-7003ec80-9502-11ea-8cdd-cee58fae5b60.png)
