### ISSUE TITLE
Frozen Column break layout when used with column group

### ISSUE THREAD

**Issue by Paraplegix** [olifolkerd/tabulator#278]
Jsfiddle for example : https://jsfiddle.net/zer380eo/1/

I didn't went deep into looking why it is breaking like this but it migh be because of the "frozen column" div you had around the columns and cells whom you update for `style="left:{xxx}px"` to keep them in front of the rest.

This problem is similar to #266 

I've also noted that Row group headers move alongside the cells where i would expect them to stay in place where they are, independently columns are moved to the left or to the right, frozen or not. (this is not an issue just a remark  :no_mouth: 
This is a screenshot of the div.tabulator-group-header going under other element to illustrate
![image](https://cloud.githubusercontent.com/assets/12891208/25386340/5c4a5778-29c7-11e7-9f58-3fd90fae2efb.png)

**Comment by olifolkerd** [comment]
Hey,

Good spot, i hadnt thought of the combination of frozen columns and column groups.

Version 3.0 of Tabulator is being released in a couple of weeks, and is a ground up rebuild with a load of new features so i will make sure this is resolve in that release.

Cheers

Oli

**Comment by Paraplegix** [comment]
2nd part of my message is the issue described in #284 
(to keep things organized)

**Comment by olifolkerd** [comment]
Hey,

You will be happy to hear that version 3.0 is now in beta release, and should address the issues you were having.

Head over to http://olifolkerd.github.io/tabulator/news/ to see the latest features!

Cheers

Oli

**Comment by alialwahish** [comment]
Issue is still persist Thanks

**Comment by olifolkerd** [comment]
@alialwahish 

This issue was closed over a year and a half ago, and definitely 100% resolved the issue. The codebase as since been almost completely rewritten twice since this issue was closed. It is there for definitely unrelated to this one.

If you are experiencing an issue that you think is a bug please raise a new bug report detailing the exact issue you are having with a working example and i can look into it, please do not post out of context on issues that have be closed for ages.

Cheers

Oli :)

**Comment by alialwahish** [comment]
@olifolkerd 
sorry to bother you only if i froze the column to the right of the table it will work otherwise the width of the first left column will push the header and that will make the data alignment off by that width ! 

Thanks  
Ali

**Comment by olifolkerd** [comment]
@alialwahish as i said in my last issue if you think you have found a bug and would like to bring it to my attention you **MUST CREATE A NEW ISSUE FOR IT**

I will not respond to comments on closed issues especially ones this out of date as it would make the issues list unmanageable.

If you want your issue to be fixed, you need to create a new bug issue and fill in the template with the needed details.

Please do not respond any further on this issue or i will lock the tread and delete comments

Cheers

Oli :)
