### ISSUE TITLE
Multi line headers/column groups and responsiveLayoutCollapseFormatter

### ISSUE THREAD

**Issue by jandagroup** [olifolkerd/tabulator#2781]
**Is your feature request related to a problem? Please describe.**
When using "responsiveLayout:collapse" the responsiveLayoutCollapseFormatter doesn't know if one of the columns it's parsing is a part of a group/multi-line header.  This is a major problem if you depend on the parent title to describe the child columns.  Also, it would be very helpful to be able to set each child column (in the header group) to collapse at the same time; It's really wonky to have only one column's data in the collapse layout while the rest is still in the row above (this is a huge accessibility issue as well).

**Describe the solution you'd like**
Be able to access a columns' parent group header/title when a column (that is apart of a group) is collapsed. Also, have the ability to mark multiple columns to hide at the same time/dependent on the state of others (not just depending on order of right to left).

**Comment by jandagroup** [comment]
@olifolkerd any thoughts on this? Right now, I guess the larger issue is not being able to collapse the column group as a group (right now the groups' individual columns expand/collapse as space allows).

**Comment by olifolkerd** [comment]
Hey @jandagroup 

Thanks for the feedback, the responsive collapse system will be getting an overhaul in the 5.0 release later this year, i will take your feed back into consideration when making the updates.

Cheers

Oli :)
