### ISSUE TITLE
getData() on custom property sent in JSON like last_page?

### ISSUE THREAD

**Issue by cgountanis** [olifolkerd/tabulator#2785]
Is there a way to get at a custom property from the table object? I was thinking of sending in a property like last_page at the top level of the JSON that would hold the total record count. This would be handy for remote pagination information in the footerElement:. Can't really do the math with out the exact total.

e.g. Showing 1 to 10 of 13 rows 

The 13 is an unknown with remote. I would like to send it in and d a getData("total_records") or something without having to add to every row object.

**Comment by nrayburn-tech** [comment]
Answered on StackOverflow [here](https://stackoverflow.com/questions/61800221/tabulator-getdata-on-custom-property-sent-in-json-like-last-page/61805199#61805199).

**Comment by cgountanis** [comment]
Thanks for the help guys!

https://jsfiddle.net/ChrisGo/4a2hdtcm/16/

**Comment by cgountanis** [comment]
@olifolkerd Hate to bring something up but it might be nice to include a record_count like last_page property (optional) and add a getTotalRecordCount() for those remote ajax users.
