### ISSUE TITLE
Feature:  Add  topCalctooltip and BottomCalctooltip 

### ISSUE THREAD

**Issue by YendorMc** [olifolkerd/tabulator#2787]
*Is your feature request related to a problem? Please describe.**
Cannot define tooltip for top/bottom Calcs.  This will allow additional details to be added when a user hovers over a column calculation.

**Describe the solution you'd like**
Would like to see topCalctooltip and BottomCalctooltip implemented, similar to tooltip is now.

**Describe alternatives you've considered**
Use jquery to define the title based on CSS tags

**Additional context**

**Comment by olifolkerd** [comment]
hey @YendorMc 

The standard tooltip will work on these already, please explain your usage case in more details.

Cheers

Oli :)

**Comment by YendorMc** [comment]
Hey @olifolkerd!  Thanks again for your awesome support!
In a nutshell, I'm providing some elaborate hover tootlips based on a function call:
tooltip:mytooltipfunc

Where the function returns about 8 lines of text to stuffed in the TITLE field.
`
	function mytooltipfunc(cell){
		
		var myRow = cell.getRow();
		rowdata = myRow.getData()

		var area = rowdata['area']
		var Target = parseFloat(rowdata['TARGET']);
		var Actual = parseFloat(rowdata['ACTUAL']);
		var Delta = parseFloat(rowdata['DELTA']);
		var PCCompleted = (Actual / Target) * 100;
		var PCRemaining = 100 - PCCompleted;
		
		var str = "";
		str += "Calculations for: " + area + "\n" 
		str += "Target: "+ my_Target.toFixed(2) + " SqMi\n" 
		str += "Actual: "+ my_Actual.toFixed(2) + " SqMi\n" 
		str += "___________________" + "\n" 
		str += "Delta: "+ + Delta.toFixed(2) + " SqMi\n" 
		str += "\n" 
		str += "%Completed: "+ PCCompleted.toFixed(2)+ "%\n" 
		str += "%Remaining: "+ PCRemaining.toFixed(2)+ "%\n" 
		str += "\n" 
		
		return str
	}
`
This is working great for the rows, but the generated tooltip is not showing up on the Column calculations, where I would expect it to show the same.  I see that the "TITLE" attribute is empty and thought it would be a feature.

Would there be another idea to try?

Again, many thanks!

**Comment by olifolkerd** [comment]
Hey @YendorMc 

Could you please put togeather a JS Fiddle that demonstrates the issue?

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @YendorMc 

with the introduction of the [CalcComponent](http://tabulator.info/docs/4.8/components#component-calc) in version 4.8 this is no longer needed.

If you set the tooltip generation mode to hover, to make sure tooltips are generated when needed:
var table = new Tabulator("#example-table", {
    tooltipGenerationMode:"hover", //regenerate tooltip as users mouse enters the cell;
});

Then in your generator function you can check to see if the row component for column is an instance of ***CalcComponent***, if it is then you know it is a calculation row that you are generating the tooltip for and you can handle it differently:
```js
tooltip:function(cell){
    if(cell.getRow() instanceof CalcComponent){
        //do something specific for calc tooltip
    }
}
```

I hope that helps,

Cheers

Oli :)
