### ISSUE TITLE
Feature: Allow Dynamic column updates when using AJAX and AutoColumns=true?

### ISSUE THREAD

**Issue by YendorMc** [olifolkerd/tabulator#2788]
*Is your feature request related to a problem? Please describe.**
I'm trying to use the autoColumns feature in Tabulator from data returned from AJAX, then dynamically add column definition info depending on the column, such as filters, sorting, etc. I've tried adding to both the pageLoaded and renderComplete callbacks, however, it 'overwrites' the filter values typed in the box when it returns the new dataset. Is there an ideal callback that I can add the code to without having the filters overwritten, or do I need to read the filter values and apply them back?

Here is my header example:
`var table = new Tabulator("#example-table", {
    height:"600px",
    layout:"fitColumns",
    pagination:"remote",
    paginationSize:25,
    paginationSizeSelector:[10, 25, 50, 100],
    paginationButtonCount:5, 
    ajaxSorting:true,
    ajaxFiltering:true,
    pageLoaded:function(pageno){
        //pageno - the number of the loaded page

        var columns = table.getColumnDefinitions();
        //console.log(columns);
        columns.forEach(column => {
            //console.log(column);
            column.headerFilter = "input";
        });
            table.setColumns(columns);
    },
    ajaxURL:"Pagination.php", //ajax URL
    autoColumns:true
});`
**Describe the solution you'd like**
Would like to access the column headers after ajax return or have alternative call back to address defined column attributes after ajax call.

**Describe alternatives you've considered**
manually define column definitions. 

**Additional context**

https://stackoverflow.com/questions/61198357/tabulator-where-to-add-dynamic-columns-when-using-ajax-and-autocolumns-true

**Comment by olifolkerd** [comment]
Hey @YendorMc 

This was specifically blocked to prevent columns form changing unexpectedly. it was in fact the way the autocolumns feature used to work and it had some very negative feedback.

The columns are updated if ***setData*** is called, so you may need to look at a way of using that to achieve your goals.

The other option would be to use manually set the columns yourself based on a dataLoaded or sort or filter callback

Cheers

Oli :)
