### ISSUE TITLE
Feature: Get Total Rows Read in Table Buffer on Progressive Load

### ISSUE THREAD

**Issue by YendorMc** [olifolkerd/tabulator#2789]
*Is your feature request related to a problem? Please describe.**
I'm trying to generate user feedback using the ajaxProgressiveLoad feature - like a percentage or rows/total rows indicator so the user knows when the data in the virtual DOM is finished.

I've passed the total rows from my ajax response, but I can't seem to get the total records in the table. Using ajaxResponse, I see it updating using getDataCount, but I'm always shy from the total on the last read.

Here is my constructor - noted I've used ajaxResponse, dataLoaded and dataLoading to no avail - I still end up shy.

Is there another callback I'm missing or should a new callback be needed?

`var table = new Tabulator("#example-table", {
    height:"600px",
    layout:"fitColumns",
    ajaxSorting:true,
    ajaxFiltering:true,
    headerFilterLiveFilterDelay:2000, //wait 600ms from last keystroke before triggering filter
    ajaxURL:"Pagination_PL.php", //ajax URL
    ajaxProgressiveLoad:"load", //enable progressive loading
    ajaxProgressiveLoadDelay:200, //wait 200 milliseconds between each request
    ajaxProgressiveLoadScrollMargin:300, //triger next ajax load when scroll bar is 300px or less from the bottom of the table.
    ajaxResponse:function(url, params, response){
        //url - the URL of the request
        //params - the parameters passed with the request
        //response - the JSON object returned in the body of the response.
        console.log("ajaxResponse")
        console.log("Number of Records: " + response.totalItems);
        console.log(table.getDataCount());
        console.log(table.getDataCount("active")); //return currently filtered data
        console.log(table.getDataCount("visible")); //return currently filtered data
        return response; //return the response data to tabulator
    },
     dataLoaded:function(data){
         console.log("dataLoaded")
        //data - all data loaded into the table
        console.log(table.getDataCount());
        console.log(table.getDataCount("active")); //return currently filtered data
    },
    dataLoading:function(data){
        console.log("dataLoading")
        //data - the data loading into the table
        console.log(table.getDataCount());
        console.log(table.getDataCount("active")); //return currently filtered data
    },
    columns:[
        {title:"NUMBER", field:"NUMBER", width:150,headerFilter:true},
        {title:"STATUS", field:"STATUS", width:100,headerFilter:true }
   ]`
**Describe the solution you'd like**
Update table.getDataCount()) to allow access to currently loaded data as the following doesn't work within the callback.
        console.log(table.getDataCount("active")); //return currently filtered data
        console.log(table.getDataCount("visible")); //return currently filtered data

**Describe alternatives you've considered**
I've passed the total rows from my ajax response, but I can't seem to get the total records in the table. Using ajaxResponse, I see it updating using getDataCount, but I'm always shy from the total on the last read.

I've used ajaxResponse, dataLoaded and dataLoading to no avail - I still end up shy.

**Additional context**
https://stackoverflow.com/questions/61200426/tabulator-get-total-rows-read-in-table-buffer-on-progressive-load

**Comment by olifolkerd** [comment]
The ***getDataCount*** returns the number of rows in the table:

```js
table.getDataCount();
```

Cheers

Oli :)
