### ISSUE TITLE
dataSorted callback on data tree tables gives the wrong row components

### ISSUE THREAD

**Issue by blankbadge** [olifolkerd/tabulator#2790]
**Describe the bug**
I have created a sortable table using the data tree feature and the dataSorted callback.  I observe that the sorter gets called for the children of every open parent, when either clicking the column header to sort or expanding a parent to show its children.   But, the array of row components made available in the dataSorted callback is not correct.  I would expect for each sorting call that this array is of the rows that were just sorted.  But it always gives the rows of the children of the top-most parent in the data tree.

**Tabulator Info**
4.6.3

**Working Example**
https://jsfiddle.net/blankbadge/0pc5uz7y/

**To Reproduce**
The dataSorted callback console.logs the 'id' field for each row in the array of row components.  Observe that the upon initially rendering the table, it shows that dataSorted was called four times, but each time it shows the same ids: "1 7 8 10", which are the topmost rows of the data tree.  Click to sort a few times, and each time you will see again that dataSorted is called four times, and each time it always prints those "1 7 8 10" ids in different orders.

**Expected behavior**
Expectation is that each dataSorted call would return the rows that it just sorted.  For example, if I ascending sort on the id field, I would expect to see the following printed to the console:

"id of sorted rows: 1 7 8 10"
"id of sorted rows: 9"
"id of sorted rows: 2 3 4"
"id of sorted rows: 5 6"

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 81

thanks!
blankbadge

**Comment by olifolkerd** [comment]
Hey @blankbadge 

Thanks for the information.

I will get a patch in for this in the next release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @blankbadge 

I have pushed a fix for this to the master branch and will include it in the 4.7 release later today

Cheers

Oli :)

**Comment by blankbadge** [comment]
Thanks for the quick fix, Oli!

-James
