### ISSUE TITLE
Only trigger sorting callbacks once on data tree tables

### ISSUE THREAD

**Issue by blankbadge** [olifolkerd/tabulator#2791]
**Is your feature request related to a problem? Please describe.**

I am using the dataSorted callback on a table built with data tree view.  Both dataSorted and dataSorting callbacks get called once for the children of each parent that is expanded in the tree.  I am sure this behavior makes sense in some contexts where those callbacks are used.

For my context, though, I am looking for different behavior.  I would like a sorting callback that only triggers once per sort of the entire table, instead of once per sort of each level of the table.
I just need to trigger an action whenever the user sorts, and I need that to happen only one time.

**Describe the solution you'd like**

A new callback or new way to use the existing callbacks such that they only occur once when a user sorts a data tree table.  A dataSorted type of callback for this case presents a small challenge in that the row component array provided in the callback may need to account for the fact that multiple sorts occurred.  For my specific purposes, I don't need to examine the rows that were sorted, I just need the callback to trigger an action external to the table.

**Describe alternatives you've considered**

I tried a workaround by examining the row components returned by each dataSorted callback, to only trigger my action when the top-most hierarchical rows are sorted.  But this did not work due to a bug where every dataSorted callback on the data tree table returns the same array of row components, always matching the top-most rows, instead of the rows that were sorted.  That is the bug report that I just filed:

dataSorted callback on data tree tables gives the wrong row components: https://github.com/olifolkerd/tabulator/issues/2790

But really my ideal solution is a single callback call on a data tree sort, hence this enhancement request.

Thanks in advance for your consideration of this request!

blankbadge

**Comment by olifolkerd** [comment]
Hey @blankbadge 

The correct approach in this instance would be to check if the first row in the rows array is a child using the ***row.getTreeParent()*** function, if it returns false then this is the top level sort.

I take on board your point about the bug in #2790 and will fix this in the next release so you can use this approach.

Cheers

Oli :)
