### ISSUE TITLE
dataFilter Callbacks (filters) [] NULL

### ISSUE THREAD

**Issue by cgountanis** [olifolkerd/tabulator#2795]
Trying to roll my own persistance on select ajax header filters maybe set on dataFiltered then some custom JS tableBuilt or something like that. Ran into this...

The filters param is never sent to the callbacks listed in the documentation.

https://jsfiddle.net/ChrisGo/wyjb4utg/5/

```
dataFiltering: function (filters) {
	console.log("dataFiltering");
	console.log(filters);
	//filters - array of filters currently applied

},
dataFiltered: function (filters, rows) {
	console.log("dataFiltered");
	console.log(filters);
	//filters - array of filters currently applied
	//rows - array of row components that pass the filters

	localStorage.setItem("shit-storm-test", JSON.stringify(filters));
},
```

**Comment by olifolkerd** [comment]
Hey @cgountanis 

Is there are reason you continue to not use the issue templates when submitting bugs? I dont think it is a great deal to ask? all they do is prompt you for the information i need to help you out and make things much easier for both of us??????

Oli

**Comment by cgountanis** [comment]
Sure I get it all that information is there just in maybe a different order fine understand that. This still seems to be a bug though so to close it when there's a screenshot explanation and JS fiddle seems strange to me.

**Comment by cgountanis** [comment]
The JS fiddle is pretty self-explanatory.

**Comment by cgountanis** [comment]
@olifolkerd would you like me to repost this in the proper format?

**Comment by olifolkerd** [comment]
please
