### ISSUE TITLE
 Cannot read property 'removeChild' of null

### ISSUE THREAD

**Issue by dileepunni1** [olifolkerd/tabulator#2796]
**Describe the bug**
When Using rowFormatter with more than one column , replace data throws bug on line this.element.parentNode.removeChild(this.element);

	Cell.prototype.delete = function () {

		if (!this.table.rowManager.redrawBlock) {

			this.element.parentNode.removeChild(this.element);
		}

		this.element = false;

		this.column.deleteCell(this);

		this.row.deleteCell(this);

		this.calcs = {};
	};

**Tabulator Info**
- v4.6.2

**To Reproduce**
```
formatter function code
  const element = row.getElement();
    const data = row.getData();
    const width = element.offsetWidth;
    // clear current row data
    if (data.tipoElemento === 'SEMPLICE') {
      while (element.firstChild) {
        element.removeChild(element.firstChild);
      }
      const componentRef = this.componentFactoryResolver.resolveComponentFactory(TabElementsComponent).create(this.injector);
      const instance = componentRef.instance as TabElementsComponent;
      setTimeout(() => {
       
        this.appRef.attachView(componentRef.hostView);
      }, 0);
      element.appendChild((componentRef.hostView as EmbeddedViewRef<any>).rootNodes[0] as HTMLElement);
    }
```
Initial rendering is always working as expected. When data source changed throws error.

**Expected behavior**
check if this.element.parentNode is present

**Screenshots**
<img width="1265" alt="Schermata 2020-05-16 alle 12 56 19" src="https://user-images.githubusercontent.com/323059/82118049-d85a0480-9774-11ea-8109-7139a7153fca.png">

**Comment by olifolkerd** [comment]
Hey @dileepunni1 

Please create a JS Fiddle that demonstrates your issue, it is very hard to offer a solution from chunks of code out of context.

Your row formmatter appears to be removing cell elements from the row. this will very likely result in malfunction of the table.

Please could you outline what you are trying to acheive.

Cheers

Oli :)
