### ISSUE TITLE
dataFiltering/dataFiltered callbacks function(filters) passing [] null

### ISSUE THREAD

**Issue by cgountanis** [olifolkerd/tabulator#2797]
**Describe the bug**
The filters param is never sent to the callbacks listed in the documentation. Trying to roll my own persistence on select ajax header filters maybe set on dataFiltered then some custom JS tableBuilt or something like that.

**Tabulator Info**
- 4.6.3

**Working Example**
https://jsfiddle.net/ChrisGo/wyjb4utg/5/

**To Reproduce**
To reproduce you can use the callBacks listed below and notice the filters are not included in the function.
```
dataFiltering: function (filters) {
	console.log("dataFiltering");
	console.log(filters);
	//filters - array of filters currently applied

},
dataFiltered: function (filters, rows) {
	console.log("dataFiltered");
	console.log(filters);
	//filters - array of filters currently applied
	//rows - array of row components that pass the filters
},
```

**Expected behavior**
I would assume the filters param would contain a JSON or Array list of filters actively being used.

**Screenshots**
![image](https://user-images.githubusercontent.com/14899817/82151352-c3d34600-9820-11ea-820e-fa6c4d2d1f72.png)
![image](https://user-images.githubusercontent.com/14899817/82151355-c9c92700-9820-11ea-8eb1-478e8a92ad96.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Firefox Developer

**Additional context**
Let me know if there is anything else I can provide or if anything is missing to explain this problem.

**Comment by cgountanis** [comment]
Shoot. I assumed that would include headerFilters but maybe I can just call `getHeaderFilters()` and call this one closed? Brainfart?

var headerFilters = table.getHeaderFilters();

I think I might have stubmled on this trying to use persistence on headerFilters and getting mix results. I think I can use getHeaderFilters and just try and roll my own headerFilter restore via LocalStorage now. I was having some issue with deprecated errors with populated headerFilters and the filter persistence.

https://jsfiddle.net/ChrisGo/wyjb4utg/11/

**Comment by olifolkerd** [comment]
Hey @cgountanis 

The dataFiltered callback only passes in filters set with the ***addFilter*** and ***setFilter*** function. 

The ***getHeaderFilters*** approach is the right one to take.

Cheers

Oli :)
