### ISSUE TITLE
function setColumns with column update type 'true' failed

### ISSUE THREAD

**Issue by MxFulder** [olifolkerd/tabulator#28]
function setColumns with column update type 'true' failed with column data without field name.
If exists column for buttons without property 'field', like described in documentation, and then we do next things:
```
var colDefs = $("#example-table").tabulator("getColumns");
$("#example-table").tabulator("setColumns", colDefs , true);
```
error occurs with message: "tabulator.js:438 Uncaught TypeError: Cannot read property 'field' of undefined"

**Comment by olifolkerd** [comment]
Could you post your column definition array so i have something to test with :)

**Comment by MxFulder** [comment]
`[{"title":"<label class=\"box-styled table-header-checkbox\"><input id=\"table-products-check-all\" type=\"checkbox\" class=\"check\" value=\"all\"><i class=\"fa\"></i></label>","width":"80px","align":"center","cssClass":"col-center","index":0,"visible":true},{"title":"sku","field":"product_sku","sortable":true,"editable":true,"sorter":"string","width":"100px","index":1,"visible":true,"cssClass":""},{"title":"name","field":"product_title","sortable":true,"editable":true,"sorter":"string","width":"100px","index":2,"visible":true,"cssClass":""},{"title":"status","field":"product_enabled","sortable":true,"editable":true,"sorter":"string","width":"100px","index":3,"visible":true,"cssClass":""},{"title":"type","field":"product_type","sortable":true,"editable":true,"sorter":"string","width":"100px","index":4,"visible":true,"cssClass":""},{"title":"price","field":"product_price","sortable":true,"editable":true,"sorter":"number","width":"100px","index":5,"visible":true,"cssClass":""}]`

Failed on first col. Unfortunately, I can't reproduce verstion as it is with bug, maybe in first col definition miss: sortable: false, editable: false. But, foremost, bug happen with no "field" param.

**Comment by olifolkerd** [comment]
I have just committed an update to include button columns in the setColumns Function
