### ISSUE TITLE
getColumns() not returning array of column strings.

### ISSUE THREAD

**Issue by YendorMc** [olifolkerd/tabulator#2801]
**Describe the bug**
Unless I'm misunderstanding something.  I believe getColumns() should return an array of strings of data columns, 
I'm getting what seems to be a Tabulator object of some sort. 

**Tabulator Info**
- Which version of Tabulator are you using?
4.6.3

**Working Example**
[https://codepen.io/yendormc/pen/yLYQRKB]
Observe console log.

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Execute Codepen 
2. Observe Console Log for variable cols after execution.

**Expected behavior**
Expected to get array of actual data columns, per documentation.  Not array of Tabulator objects

**Screenshots**
![ConsoleLog_getColumns](https://user-images.githubusercontent.com/10876357/82279709-2a5c7f00-995b-11ea-994c-4b6154de1d35.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 81.0.4044.138 (Official Build) (64-bit)

**Comment by takuy** [comment]
The documentation (in several places) says `getColumns` returns an array of column components. You can use these to get all sorts of data though. What exactly are you looking to do?

**Comment by YendorMc** [comment]
Thanks for the feedback!
Referencing this link: 
[http://tabulator.info/docs/4.6/columns#get-component]

It mentions "This will only return actual data columns not column groups." 

I'm cool with that, but wasn't expecting to access the _column object, like:
cols[0]._column.field
cols[1]._column.field

If that's design intent, I'm good to go.  I was just expecting an array of column names, but I can create with stepping through the array elements.  

Thanks!

**Comment by takuy** [comment]
You don't need to access it like that. Each Column component object has a set of functions defined for it. 

For your case: `cols[0].getField()` would be the proper way. 

See column component info here: http://tabulator.info/docs/4.6/components#component-column

**Comment by olifolkerd** [comment]
Hey @YendorMc 

you should never access an underscore property, the JavaScript convention is that these are private.

As @takuy says, it returns an array of column components, Components are JavaScript objects that represent parts of the tables such as cells, columns and rows, and have a wide selection of functions you can call to access all the relevant data or change settings on the component.

For full details on how to use a column component checkout the [Documentation[(http://tabulator.info/docs/4.6/components#component-column)

I would strongly recommend reading through the component documentation, they are the powerhouse behind Tabulator, are returned from most functions and passed into callbacks and are the primary way to access table data.

Cheers

Oli :)

**Comment by YendorMc** [comment]
Ahh! I get it now!  I didn't quite understand the concept.  Thank you @takuy and @olifolkerd !!!
