### ISSUE TITLE
Expected scroll bar is not created

### ISSUE THREAD

**Issue by Nazar84** [olifolkerd/tabulator#2802]
![_](https://user-images.githubusercontent.com/56727082/82444113-5e46ba00-9aab-11ea-9d43-55fa866cd48b.jpg)

**Describe the bug**
If columns of tested table is wider then parent table 
then scrollbar for this row should be created.

but instead of that scrollbar is created for parent table.

**Tabulator Info**
- 4.6

**Working Example**
See picture above

http://tabulator.info/examples/4.6#nested-tables

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to http://tabulator.info/examples/4.6#nested-tables
2. Change width for nested column
![_1](https://user-images.githubusercontent.com/56727082/82444362-ca292280-9aab-11ea-8766-b942ed882a01.jpg)

**Expected behavior**
Scroll bar should appear for row where table is nested

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Linux Mint 19
 - Browser FF
 - Version 75.0

**Comment by olifolkerd** [comment]
Hey @Nazar84 

You need to set a max width on your sub table

Cheers

Oli :)
