### ISSUE TITLE
Enable headerContextMenu and headerMenu for column groups

### ISSUE THREAD

**Issue by thenesk** [olifolkerd/tabulator#2803]
I would like table users to be able to show and hide columns easily.  A context menu attached to the column headers seems like a standard way to do this.  Following the documentation I was able to do this for most columns, but not for column groups.

It seems like this is not currently supported and I see the same limitation described on stackoverflow, so I think other people would benefit from this feature.  https://stackoverflow.com/questions/61292404/is-there-a-way-to-add-a-headermenu-to-a-group-column

I tried to fix the issue myself by editing `tabulator.js` and making `Column.prototype._buildGroupHeader` look more like `Column.prototype._buildColumnHeader`, specifically by adding `table.modules.menu.initializeColumnHeader(self);`, and this allowed the context menu to trigger.  However, I am not sure if this is the right way to do it.

The context menu that I am adding currently has two items, 'hide column' and 'show all columns'.  With the above hack in _buildGroupHeader, hiding columns seems to work, however showing a column group that has been hidden does not work - the header appears but none of the cells appear.  I am not sure if this is a separate issue or if I broke things by adding the context menu to the group in the first place.

Overall I am very impressed with Tabulator.  It is responsive, looks clean, and has useful features.  Thanks!

**Comment by thenesk** [comment]
Enabling the context menu by calling initializeColumnHeader seems to be working well so I created a pull request:  https://github.com/olifolkerd/tabulator/pull/2806

I resolved the issue with my show column callback by explicitly showing all child columns.

**Comment by thenesk** [comment]
Oops, I see that there is already a pull request addressing the lack of context menus on column group headers: https://github.com/olifolkerd/tabulator/pull/2757

The implementations are a bit different.  I am new to this code base and I am not sure what the trade offs are here, but it looks like the original PR is already slated for inclusion.

**Comment by olifolkerd** [comment]
Closing this issue as it was included in the last release
