### ISSUE TITLE
Star editor - cannot edit a cell twice in a row

### ISSUE THREAD

**Issue by AGrazka** [olifolkerd/tabulator#2804]
There is a problem with "double" edit a cell using star editor. After changing value I can't edit it without click somewhere else to blur it. 
The same problem is on your website http://tabulator.info/examples/4.6?#editable - click on a star and then try to change it immediately.
Version 4.6. 

It would be great if this bug could be resolved. Or it is intentional?

os w10, browser: Chrome v. 83.0.4103.61./64

**Comment by olifolkerd** [comment]
Hey @AGrazka 

Thanks for pointing that out, i will get a fix in for the next release.

Could i ask that if you have bugs to report in future, please use the [Bug Report Issue Template](https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Possible+Bug&template=bug_report.md&title=)

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @AGrazka 

I have pushed a fix for this to the master branch and will include it in today's release.

Cheers

Oli :)
