### ISSUE TITLE
Allow Esc key press to close context menus

### ISSUE THREAD

**Issue by thenesk** [olifolkerd/tabulator#2807]
**Is your feature request related to a problem? Please describe.**
Context menus do not close when the user hits the escape key.  If the user does not want to select an option from the menu they must click outside the menu to get rid of the menu, and may inadvertently change something in the process (for example clicking on another column and changing the sort).

**Describe the solution you'd like**
I would like the escape key to close any open tabulator context menu, just as the escape key can be used to close browser context menus.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by olifolkerd** [comment]
This change has been merged in and will be included in the 4.7 release later today :)
