### ISSUE TITLE
allow table access from downloadDataFormatter

### ISSUE THREAD

**Issue by thenesk** [olifolkerd/tabulator#2810]
**Is your feature request related to a problem? Please describe.**
When exporting table contents to CSV/JSON/etc it may be helpful to access the table itself.  In my case, the download data format needs special handling for html columns, and needs access to the column definitions to know which columns have html formatting.  In this case, I am grabbing the alt text instead of including all of the cell html, which make much more sense for CSV and JSON exports.  There may be other use cases where table access allows the downloadDataFormatter to be smarter about formatting data for export.

**Describe the solution you'd like**
Including the table as a property of the data that is passed to downloadDataFormatter would do the trick.  Something as simple as: 
'data.table = self.table;'

**Describe alternatives you've considered**
Not using html formatting in cells or not allowing data export.

**Additional context**
NA

**Comment by olifolkerd** [comment]
Hey @thenesk 

The download module is getting an overhaul in the next release to map its functionality through the export module so the current structure will be being replaced anyway and you will gain access to the component objects themselves.

Cheers

Oli :)
