### ISSUE TITLE
Add link to JS fiddle into bug report template

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#2819]
*Is your feature request related to a problem? Please describe.**
In your bug templates you write:
```
YOUR BUG REPORT MUST CONTAIN A LINK TO A JSFiddle OR Codepen THAT DEMONSTRATES THE ISSUE OR IT WILL BE CLOSED WITHOUT DISCUSSION
```
But it is wired a bit to create JS fiddle.

If you provide a link to already created snipped, this would be easy to people to demonstrate theirs problem.
Because the just copy basic snipped and just add code to demonstrate theirs problem

**Describe the solution you'd like**
https://jsfiddle.net/KES777/6heudjnk/7/
Add this link to bug report template, so people can copy and extend this basic example

**Describe alternatives you've considered**
Create same basic snipped for Codepen

**Additional context**
Thank you Oli. Your tabulator is wonderful. Hope this snipped helps people to create more issues in required format ;-)

**Comment by nrayburn-tech** [comment]
How long is a jsfiddle link valid for?  I mean, at some point it has to expire, right?

The resources would need to always point to the latest published version of Tabulator as well.  I am not really sure if there is a URL for getting the latest version from unpkg.

**Comment by KES777** [comment]
>How long is a jsfiddle link valid for? I mean, at some point it has to expire, right?

No, [ they live forever. ]( https://stackoverflow.com/a/8191278/4632019 )

>The resources would need to always point to the latest published version of Tabulator as well
When new version of tabulator is released then you can fork current fiddle and update resources to point to latest tabulator. Then update your templates for issues.
So new issue will point to latest tabulator

**Comment by olifolkerd** [comment]
Hey @KES777 

Thanks for the suggestion.

If im honest this sounds like a lot of work for each release. Im not sure i have seen any other libraries with a default JS Fiddle template, 

It is fairly intuitive to setup *(litterally hundreds of Tabulator users do it for issues each year)* and i dont want to force people down a particular route, im happy with JS Fiddle, CodePen or any other platform that people are happy using.

If there is a guide to setting up a JS Fiddle out there i would be happy to include a link to that, which may help people that havnt done it before. But i dont think i would be looking to go as far as to maintain a JS Fiddle project, 

Cheers

Oli :)

**Comment by nrayburn-tech** [comment]
@olifolkerd, It looks like this can be done with little to no additional maintenance on release.

JSFiddle can use a regular html link/script tag to point to the unpkg latest.  So, anytime the cdn is updated, the fiddle will be pointed to the latest version.
CodeSandbox can use the `package.json` to import the `latest` which again does basically the same thing.
I tried codepen, but it looks like that requires an account. If a 'default' is made, it should probably be made by you.  That way it lasts as long as you see fit.

Here are two links that you can look at and decide on.
https://jsfiddle.net/yopwc36d/
https://codesandbox.io/s/friendly-shamir-74wq7?file=/package.json (I don't use this, so I left it basically as the default when I opened it.)

I agree that making an example is not that difficult of a thing to do, so maybe this isn't really that important anyways.

I would have some concern always pointing the bug report fiddles to the latest Tabulator version.  If I submit a report today pointing to `latest`, then you open the report next week after a release the issue may not replicate itself.  Maybe this is a good thing, but it definitely makes the tracking of what version the bug replicated on more difficult.  Of course, if bug reports have a version then this would be a non-issue.
