### ISSUE TITLE
Question: spinner during sort?

### ISSUE THREAD

**Issue by shayo** [olifolkerd/tabulator#282]
I have a somewhat large table. 
How can I introduce a spinner while the table is being sorted? is there a way to hook up a callback before and after sort occurs?

**Comment by olifolkerd** [comment]
Hey,

you can use the ***dataSorting *** and ***dataSorted *** callbacks:

```js
$("#example-table").tabulator({
    columns:[...],
    dataSorting:function(sortList, dir){
        //sortList - the field name or array of fields being sorted
        //dir - the direction of the sort
    },
    dataSorted:function(sortList, dir){
        //sortList - the field name or array of fields being sorted
        //dir - the direction of the sort
    },
});
````

Let me know if that helps.

Cheers

Oli

**Comment by olifolkerd** [comment]
As a side note, version 3.0 of tabulator is coming out in a couple of weeks, and it has a mach faster sorting function.

**Comment by shayo** [comment]
Oli, Thank you for the quick reply.
For some reason, those callbacks are not being called. I'll have to investigate more why this happens.
Is 3.0 in beta mode, or still premature to test?

**Comment by olifolkerd** [comment]
Could you post a copy of your Tabulator constructor object, i will take a look at it for you.

3.0 Isnt ready for a public test just yet, but keep you eyes peels i will be putting up a notice soon.

Cheers

Oli

**Comment by shayo** [comment]
var groupBy= ""; // this is set externally

$("#example-table-theme").tabulator({
      sortable:true,
      fitColumns:false,
      groupBy:groupby,     
        columns:[
      {title:"Id", field:"id", align:"center",width:60},
      {title:"Setter", field:"setter", align:"center",width:100},
      {title:"Tape", field:"tape", align:"center",width:80

, formatter:function(value, data, cell, row, options, formatterParams){
        return "<div> <img src='"+data.tape+"' height='20px'> </div>"; // must return the html or jquery element of the html for the contents of the cell;
    }},
      {title:"Type", field:"type", align:"center",width:80},
      {title:"Grade", field:"grade", align:"center",width:80},
      {title:"Location", field:"location", align:"center",width:120},
      {title:"Days Alive", field:"days_alive", align:"center",width:100},
      {title:"Success", field:"success_rate", align:"center",width:90},
      {title:"Attempts", field:"attempts", align:"center",width:90},
      {title:"Ascents", field:"ascents", align:"center",width:90},
      {title:"Rating", field:"rating", formatter:"star", formatterParams:{stars:5}, align:"center", width:120},
      {title:"Beta", field:"beta", align:"center",width:80, formatter:"tickCross", sorter:"boolean"}
      ]
    });

**Comment by shayo** [comment]
Btw, is there a way to modify the groupBy field dynamically?

**Comment by olifolkerd** [comment]
You can pass a function to the ***groupBy*** option and control the grouping from there:
```js
groupBy:function(data){
    //data - the data object for the row being grouped

    return data.gender + " - " + data.age; //groups by data and age
}
```

**Comment by olifolkerd** [comment]
Hey,

You will be happy to hear that version 3.0 is now in beta release, the spinner is linked specifically to the ajax request. but you should no longer have any long loading times as the new virtual DOM renders any size of table almost instantly.

Head over to http://olifolkerd.github.io/tabulator/news/ to see the latest features!

Cheers

Oli
