### ISSUE TITLE
sample angular project - Tabulator grid in its own component. SCSS styling.

### ISSUE THREAD

**Issue by David-Mawer** [olifolkerd/tabulator#2822]
*Is your feature request related to a problem? Please describe.**
So - setting up the grid in angular takes a bit of fiddling. I created a mini repository with the basic setup all done (angular 9.1.7)

**Describe the solution you'd like**
Not sure if this has any value for the team - but just wanted to share if it is useful.

**Describe alternatives you've considered**
I had a look at the angular sample code - and it doesn't deal with changes gracefully (each change creates a new instance of the grid)

**Additional context**
this is not really urgent. I am just grateful for the use of this grid - so wanted to help out a bit if what I knew was worth anything.

**Comment by David-Mawer** [comment]
link to the repository: - https://github.com/David-Mawer/tabulator-angular-sample

**Comment by olifolkerd** [comment]
Hey @David-Mawer 

Thanks for sharing, it is always great to see how others are using Tabulator.

If you think this is an improvement over the current [Aungular Setup Guide](http://tabulator.info/docs/4.6/frameworks#angular) i would be happy to replace it with a simple example component if you could provide one in vanilla JS

Cheers

Oli :)

**Comment by David-Mawer** [comment]
Hi Oli,

 

OK – so there are some improvements over the existing code that I can easily show in a code snippet.

The code below has the following improvements: -

*        Some of the tabulator-grid events are converted to angular component events – this is documented so that newer people to angular can add events as they wish.

*        Changes to the table data of the column configuration are routed to the tabulator-grid’s .setData and .setColumns methods (respectively) – this allows the grid to do any object clean-up that’s necessary – preventing memory leaks if a grid is re-used for a different dataset on a page.

*        The Date handling in the angular demo didn’t work as expected – so the required procedures to fix this are built-in to the angular tabulator-grid.component that you see below.

*        The tabulator-grid div is accessed using the angular “ViewChild” declaration – this future-proofs the code a bit; but not much. This is more for the angular purists who don’t like to use document.getElementById in their projects (like me ;-) )

 

(this code snippet would replace the “Javascript” code section in the current documentation.)

----------------- Code snippet begins: --------------------------

import { Component, ElementRef, ViewChild, OnChanges, Input, SimpleChanges, EventEmitter, Output, OnDestroy } from '@angular/core';

// tabular grid: https://github.com/olifolkerd/tabulator

import Tabulator from 'tabulator-tables';

import * as moment from 'moment';

 

/*

* So - the whole point of TypeScript is to make things strictly typed.

*

* At the moment the input parameters (for column definitions and data) are not typed.

*

* Also - the events are not typed.

*

* So - if you want - then you can make types for things like tableData (then it will be a typed array).

* The variables are well documented here: http://tabulator.info/docs/4.2/options

*  (immediately after the overview at the top of the page)

*

*/

@Component({

  selector: 'app-tabulator-grid',

  templateUrl: './tabulator-grid.component.html',

  styleUrls: ['./tabulator-grid.component.scss']

})

export class TabulatorGridComponent implements OnChanges, OnDestroy {

  @ViewChild('tabularGridWrapper', { static: true }) wrapperDiv: ElementRef<HTMLDivElement>;

 

  @Input() tableData: any[] = [];

  @Input() columnConfig: any[] = [];

  @Input() dateFormat: string = '';

  @Input() height: string = ''; // default is to auto-adjust height with the grid contents.

  // These are for passing grid events back to the parent component.

  @Output() buildingTable = new EventEmitter<void>();

  @Output() builtTable = new EventEmitter<void>();

  @Output() loadingData = new EventEmitter<any[]>();

  @Output() loadedData = new EventEmitter<any[]>();

  @Output() cellChanged = new EventEmitter<any>();

 

  // private variables for keeping track of the table.

  private tableDiv = document.createElement('div'); // this is the div that will contain that tabulator-grid HTML.

  private myTable: any; // this will become a reference to the tabulator-grid object

  private gridClosing: boolean = false;

 

  constructor() {

    // Default the date format if it was not specified.

    this.dateFormat = this.dateFormat || 'DD MMM YYYY';

  }

 

  ngOnChanges(changes: SimpleChanges): void {

    // Configure the grid with whatever changes are made by the calling component.

    //  (this code also initialises the grid)

    this.drawTable(changes);

  }

 

  ngOnDestroy(): void {

    this.gridClosing = true;

    // Not sure if this is necessary - but remove all rows and columns from the grid.

    if (this.myTable) {

      this.myTable.setData([]);

      this.myTable.setColumns([]);

    }

  }

 

  private drawTable(changes: SimpleChanges): void {

    if ((this.gridClosing) || (!this.columnConfig)) {

      return;

    }

    // Re-route date sorting and editing to local overrides.

    //  (allows Angular to decide how/when the moment library is in use)

    this.fastForEach(this.columnConfig, colConfigEntry => {

      if (colConfigEntry.sorter == "date") {

        colConfigEntry.sorter = this.dateSorter.bind(this);

        colConfigEntry.editor = this.dateEditor.bind(this);

      }

    });

 

    // create the table if necessary - update it if it exists already.

    if (!this.myTable) {

 

      // create the table with the given Angular parameters

      // for details about the Tabulator parameters - check http://tabulator.info/docs/4.2/options

      this.myTable = new Tabulator(this.tableDiv, {

        data: this.tableData || [],

        reactiveData: true, // enable data reactivity - means that array content changes get reflected by the grid (without Angular having to worry)

        columns: this.columnConfig,

        layout: 'fitData',

        height: this.height,

        // pass some of the events back to the declaring code.

        // for a complete list of events - see: http://tabulator.info/docs/4.6/callbacks

        tableBuilding: this.tableBuilding.bind(this),

        tableBuilt: this.tableBuilt.bind(this),

        cellEdited: this.cellEdited.bind(this),

        dataLoading: this.dataLoading.bind(this),

        dataLoaded: this.dataLoaded.bind(this)

      });

      this.wrapperDiv.nativeElement.appendChild(this.tableDiv);

 

    } else {

      // Check what changed, and only update that stuff

      if (changes.columnConfig) {

        this.myTable.setColumns(this.columnConfig);

      }

      if (changes.tableData) {

        this.myTable.setData(this.tableData);

      }

 

    }

  }

 

 

  //////////////////////////////////////////////////////////////////

  // Passing grid events to the component that has the grid: Begin

  private tableBuilding() {

    this.buildingTable.emit();

  }

  private tableBuilt() {

    this.builtTable.emit();

  }

  private cellEdited(cell) {

    //cell - cell component

    this.cellChanged.emit(cell);

  }

  private dataLoading(data: any[]) {

    //data - the data loading into the table

    this.loadingData.emit(data);

  }

  private dataLoaded(data: any[]) {

    //data - the data loading into the table

    this.loadedData.emit(data);

  }

  // Passing grid events to the component that has the grid: End

  //////////////////////////////////////////////////////////////////

 

 

  //////////////////////////////////////////////////////////////////

  // Date Handling: Begin

  private dateSorter(a, b, aRow, bRow, column, dir, sorterParams) {

    //a, b - the two values being compared

    //aRow, bRow - the row components for the values being compared (useful if you need to access additional fields in the row data for the sort)

    //column - the column component for the column being sorted

    //dir - the direction of the sort ("asc" or "desc")

    //sorterParams - sorterParams object from column definition array

    var date1 = moment(a, this.dateFormat);

    var date2 = moment(b, this.dateFormat);

 

    return date1.diff(date2, "seconds"); // return the difference between the two dates

  }

 

  private dateEditor(cell, onRendered, success, cancel) {

    //cell - the cell component for the editable cell

    //onRendered - function to call when the editor has been rendered

    //success - function to call to pass the successfuly updated value to Tabulator

    //cancel - function to call to abort the edit and return to a normal cell

 

    //create and style input

    var expectedDataFormat = this.dateFormat;

    var cellValue = moment(cell.getValue(), expectedDataFormat).format("YYYY-MM-DD");

    var input = document.createElement("input");

 

    input.setAttribute("type", "date");

 

    input.style.padding = "4px";

    input.style.width = "100%";

    input.style.boxSizing = "border-box";

 

    input.value = cellValue;

 

    onRendered(function () {

      input.focus();

      input.style.height = "100%";

    });

 

    function onChange() {

      if (input.value != cellValue) {

        var successValue = moment(input.value, "YYYY-MM-DD").format(expectedDataFormat);

        success(successValue);

      } else {

        cancel();

      }

    }

 

    //submit new value on blur or change

    input.addEventListener("blur", onChange);

 

    //submit new value on enter

    input.addEventListener("keydown", function (e) {

      if (e.keyCode == 13) {

        onChange();

      }

 

      if (e.keyCode == 27) {

        cancel();

      }

    });

 

    return input;

  }

  // Date Handling: End

  //////////////////////////////////////////////////////////////////

 

  // Generic logic - this could be moved to a common library if you want.

  // foreach using the fastest iterator in Javascript (the while loop)

  private fastForEach<T>(inArr: T[], execFunc: (element: T, i: number) => void): void {

    let i = 0;

    while (i < inArr.length) {

      execFunc(inArr[i], i);

      i++;

    }

  }

 

}

----------------- Code snippet ends: ----------------------------

 

Then – for the HTML section of the code – the this is the required line of code: -

<div #tabularGridWrapper id="tabular-grid-wrapper"></div>

 

 

About the rest of the existing demo (the CSS)…

…I’ve changed that to use a SCSS file that can be included in a themed project as a mixin…

…This allows the grid’s colours are calculated based on the current theme.

 

If some-one wanted to use this – then they would create the following mixin scss file – and reference it in their project where they manage the styles for selected themes.

This is a new piece of code (an alternative to using the CSS code shown in the existing demo).

 

In this file – I’ve hard-coded the colours for projects that don’t use themes, but for each hard-coded colour I’ve put a comment showing how to retrieve the relevant colour from an angular material theme (all the variables that need changing are in the top 12 lines of the code).

 

SCSS File:

----------------- SCSS Code Begins: ----------------------------

@mixin Tabulator-default-theme($theme) {

  // Material like variables...

  // ...if you have theming in you app - then you should set these variables from the theme.

 

  // $primary: map-get($theme, primary);

 

  $background-color: white; // mat-color(map-get($theme, background), card);

  $foreground-color: black; // mat-color(map-get($theme, foreground), text);

  $primary-color: darkblue; // mat-color($primary);

  $accent-color: pink; // mat-color(map-get($theme, accent));

  $default-contrast-color: white; // mat-color($primary, default-contrast);

  // now set the grid's colours

 

  //Main Theme Variables

  $backgroundColor: $background-color !default; //background color of tabulator

  $borderColor: mix($background-color, $foreground-color, 90) !default; //border to tabulator

  $textSize: 14px !default; //table text size

  //header themeing

  $headerBackgroundColor: mix($background-color, $primary-color, 10) !default; //border to tabulator

  $headerTextColor: mix($primary-color, $default-contrast-color, 25) !default; //header text colour

  $headerBorderColor: mix($background-color, $primary-color, 67) !default; //header border color

  $headerSeperatorColor: mix($background-color, $primary-color, 60) !default; //header bottom seperator color

  $headerMargin: 4px !default; //padding round header

  //column header arrows

  $sortArrowActive: mix($primary-color, $default-contrast-color, 25) !default;

  $sortArrowInactive: mix($primary-color, $default-contrast-color, 55) !default;

 

  //row themeing

  $rowBackgroundColor: $background-color !default; //table row background color

  $rowAltBackgroundColor: mix($background-color, $primary-color, 85) !default; //table row background color

  $rowBorderColor: mix($background-color, $foreground-color, 67) !default; //table border color

  $rowTextColor: mix($background-color, $foreground-color, 10) !default; //table text color

  $rowHoverBackground: mix($background-color, $accent-color, 73) !default; //row background color on hover

 

  $rowSelectedBackground: mix($background-color, $primary-color, 75) !default; //row background color when selected

  $rowSelectedBackgroundHover: mix($background-color, $primary-color, 85) !default; //row background color when selected and hovered

 

  $editBoxColor: #1D68CD !default; //border color for edit boxes

  $errorColor: #dd0000 !default; //error indication

  //footer themeing

  $footerBackgroundColor: #e6e6e6 !default; //border to tabulator

  $footerTextColor: #555 !default; //footer text colour

  $footerBorderColor: #aaa !default; //footer border color

  $footerSeperatorColor: #999 !default; //footer bottom seperator color

  $footerActiveColor: #d00 !default; //footer bottom active text color

  //Tabulator Containing Element

  .tabulator {

    position: relative;

    border: 1px solid $borderColor;

    background-color: $backgroundColor;

    font-size: $textSize;

    text-align: left;

    overflow: hidden;

    -webkit-transform: translatez(0);

    -moz-transform: translatez(0);

    -ms-transform: translatez(0);

    -o-transform: translatez(0);

    transform: translatez(0);

 

    &[tabulator-layout="fitDataFill"] {

     .tabulator-tableHolder {

        .tabulator-table {

          min-width: 100%;

        }

      }

    }

 

    &.tabulator-block-select {

      user-select: none;

    }

    //column header containing element

    .tabulator-header {

      position: relative;

      box-sizing: border-box;

      width: 100%;

      border-bottom: 1px solid $headerSeperatorColor;

      background-color: $headerBackgroundColor;

      color: $headerTextColor;

      font-weight: bold;

      white-space: nowrap;

      overflow: hidden;

      -moz-user-select: none;

      -khtml-user-select: none;

      -webkit-user-select: none;

      -o-user-select: none;

 

      &.tabulator-header-hidden {

        display: none;

      }

      //individual column header element

      .tabulator-col {

        display: inline-block;

        position: relative;

        box-sizing: border-box;

        border-right: 1px solid $headerBorderColor;

        background: $headerBackgroundColor;

        text-align: left;

        vertical-align: bottom;

        overflow: hidden;

 

        &.tabulator-moving {

          position: absolute;

          border: 1px solid $headerSeperatorColor;

          background: darken($headerBackgroundColor, 10%);

          pointer-events: none;

        }

        //hold content of column header

        .tabulator-col-content {

          box-sizing: border-box;

          position: relative;

          padding: 4px;

          //header menu button

          .tabulator-header-menu-button {

            padding: 0 8px;

 

            &:hover {

              cursor: pointer;

              opacity: .6;

            }

          }

          //hold title of column header

          .tabulator-col-title {

            box-sizing: border-box;

            width: 100%;

            white-space: nowrap;

            overflow: hidden;

            text-overflow: ellipsis;

            vertical-align: bottom;

            //element to hold title editor

            .tabulator-title-editor {

              box-sizing: border-box;

              width: 100%;

              border: 1px solid #999;

              padding: 1px;

              background: #fff;

            }

          }

          //column sorter arrow

          .tabulator-arrow {

            display: inline-block;

            position: absolute;

            top: 9px;

            right: 8px;

            width: 0;

            height: 0;

            border-left: 6px solid transparent;

            border-right: 6px solid transparent;

            border-bottom: 6px solid $sortArrowInactive;

          }

        }

        //complex header column group

        &.tabulator-col-group {

          //gelement to hold sub columns in column group

          .tabulator-col-group-cols {

            position: relative;

            display: flex;

            border-top: 1px solid $headerBorderColor;

            overflow: hidden;

            margin-right: -1px;

          }

        }

        //hide left resize handle on first column

        &:first-child {

          .tabulator-col-resize-handle.prev {

            display: none;

          }

        }

        //header filter containing element

        .tabulator-header-filter {

          position: relative;

          box-sizing: border-box;

          margin-top: 2px;

          width: 100%;

          text-align: center;

          //styling adjustment for inbuilt editors

          textarea {

            height: auto !important;

          }

 

          svg {

            margin-top: 3px;

          }

 

          input {

            &::-ms-clear {

              width: 0;

              height: 0;

            }

          }

        }

        //styling child elements for sortable columns

        &.tabulator-sortable {

          .tabulator-col-title {

            padding-right: 25px;

          }

 

          &:hover {

            cursor: pointer;

            background-color: darken($headerBackgroundColor, 10%);

          }

 

          &[aria-sort="none"] {

            .tabulator-col-content .tabulator-arrow {

              border-top: none;

              border-bottom: 6px solid $sortArrowInactive;

            }

          }

 

          &[aria-sort="asc"] {

            .tabulator-col-content .tabulator-arrow {

              border-top: none;

              border-bottom: 6px solid $sortArrowActive;

            }

          }

 

          &[aria-sort="desc"] {

            .tabulator-col-content .tabulator-arrow {

              border-top: 6px solid $sortArrowActive;

              border-bottom: none;

            }

          }

        }

 

 

        &.tabulator-col-vertical {

          .tabulator-col-content {

            .tabulator-col-title {

              writing-mode: vertical-rl;

              text-orientation: mixed;

              display: flex;

              align-items: center;

              justify-content: center;

            }

          }

 

          &.tabulator-col-vertical-flip {

            .tabulator-col-title {

              transform: rotate(180deg);

            }

          }

 

          &.tabulator-sortable {

            .tabulator-col-title {

              padding-right: 0;

              padding-top: 20px;

            }

 

            &.tabulator-col-vertical-flip {

              .tabulator-col-title {

                padding-right: 0;

                padding-bottom: 20px;

              }

            }

 

            .tabulator-arrow {

              right: calc(50% - 6px);

            }

          }

        }

      }

 

      .tabulator-frozen {

        display: inline-block;

        position: absolute;

        // background-color: inherit;

        z-index: 10;

 

        &.tabulator-frozen-left {

          border-right: 2px solid $rowBorderColor;

        }

 

        &.tabulator-frozen-right {

          border-left: 2px solid $rowBorderColor;

        }

      }

 

 

      .tabulator-calcs-holder {

        box-sizing: border-box;

        min-width: 600%;

        background: lighten($headerBackgroundColor, 5%) !important;

 

        .tabulator-row {

          background: lighten($headerBackgroundColor, 5%) !important;

 

          .tabulator-col-resize-handle {

            display: none;

          }

        }

 

        border-top: 1px solid $rowBorderColor;

        border-bottom: 1px solid $headerBorderColor;

        overflow: hidden;

      }

 

      .tabulator-frozen-rows-holder {

        min-width: 600%;

 

        &:empty {

          display: none;

        }

      }

    }

    //scrolling element to hold table

    .tabulator-tableHolder {

      position: relative;

      width: 100%;

      white-space: nowrap;

      overflow: auto;

      -webkit-overflow-scrolling: touch;

 

      &:focus {

        outline: none;

      }

      //default placeholder element

      .tabulator-placeholder {

        box-sizing: border-box;

        display: flex;

        align-items: center;

 

        &[tabulator-render-mode="virtual"] {

          min-height: 100%;

          min-width: 100%;

        }

 

        width: 100%;

 

        span {

          display: inline-block;

          margin: 0 auto;

          padding: 10px;

          color: #ccc;

          font-weight: bold;

          font-size: 20px;

        }

      }

      //element to hold table rows

      .tabulator-table {

        position: relative;

        display: inline-block;

        background-color: $rowBackgroundColor;

        white-space: nowrap;

        overflow: visible;

        color: $rowTextColor;

        //row element

        .tabulator-row {

          &.tabulator-calcs {

            font-weight: bold;

            background: darken($rowAltBackgroundColor, 5%) !important;

 

            &.tabulator-calcs-top {

              border-bottom: 2px solid $rowBorderColor;

            }

 

            &.tabulator-calcs-bottom {

              border-top: 2px solid $rowBorderColor;

            }

          }

        }

      }

    }

    //footer element

    .tabulator-footer {

      padding: 5px 10px;

      border-top: 1px solid $footerSeperatorColor;

      background-color: $footerBackgroundColor;

      text-align: right;

      color: $footerTextColor;

      font-weight: bold;

      white-space: nowrap;

      user-select: none;

      -moz-user-select: none;

      -khtml-user-select: none;

      -webkit-user-select: none;

      -o-user-select: none;

 

      .tabulator-calcs-holder {

        box-sizing: border-box;

        width: calc(100% + 20px);

        margin: -5px -10px 5px -10px;

        text-align: left;

        background: lighten($footerBackgroundColor, 5%) !important;

 

        .tabulator-row {

          background: lighten($footerBackgroundColor, 5%) !important;

 

          .tabulator-col-resize-handle {

            display: none;

          }

        }

 

        border-bottom: 1px solid $rowBorderColor;

        border-top: 1px solid $rowBorderColor;

        overflow: hidden;

 

        &:only-child {

          margin-bottom: -5px;

          border-bottom: none;

        }

      }

 

      .tabulator-paginator {

        color: $footerTextColor;

        font-family: inherit;

        font-weight: inherit;

        font-size: inherit;

      }

      //pagination container element

      .tabulator-page-size {

        display: inline-block;

        margin: 0 5px;

        padding: 2px 5px;

        border: 1px solid $footerBorderColor;

        border-radius: 3px;

      }

 

      .tabulator-pages {

        margin: 0 7px;

      }

      //pagination button

      .tabulator-page {

        display: inline-block;

        margin: 0 2px;

        padding: 2px 5px;

        border: 1px solid $footerBorderColor;

        border-radius: 3px;

        background: rgba(255,255,255,.2);

 

        &.active {

          color: $footerActiveColor;

        }

 

        &:disabled {

          opacity: .5;

        }

 

        &:not(.disabled) {

          &:hover {

            cursor: pointer;

            background: rgba(0,0,0,.2);

            color: #fff;

          }

        }

      }

    }

    //column resize handles

    .tabulator-col-resize-handle {

      position: absolute;

      right: 0;

      top: 0;

      bottom: 0;

      width: 5px;

 

      &.prev {

        left: 0;

        right: auto;

      }

 

      &:hover {

        cursor: ew-resize;

      }

    }

    //holding div that contains loader and covers tabulator element to prevent interaction

    .tabulator-loader {

      position: absolute;

      display: flex;

      align-items: center;

      top: 0;

      left: 0;

      z-index: 100;

      height: 100%;

      width: 100%;

      background: rgba(0,0,0,.4);

      text-align: center;

      //loading message element

      .tabulator-loader-msg {

        display: inline-block;

        margin: 0 auto;

        padding: 10px 20px;

        border-radius: 10px;

       background: #fff;

        font-weight: bold;

        font-size: 16px;

        //loading message

        &.tabulator-loading {

          border: 4px solid #333;

          color: #000;

        }

        //error message

        &.tabulator-error {

          border: 4px solid #D00;

          color: #590000;

        }

      }

    }

  }

  //row element

  .tabulator-row {

    position: relative;

    box-sizing: border-box;

    min-height: $textSize + ($headerMargin * 2);

    background-color: $rowBackgroundColor;

 

 

    &.tabulator-row-even {

      background-color: $rowAltBackgroundColor;

    }

 

    &.tabulator-selectable:hover {

      background-color: $rowHoverBackground;

      cursor: pointer;

    }

 

    &.tabulator-selected {

      background-color: $rowSelectedBackground;

    }

 

    &.tabulator-selected:hover {

      background-color: $rowSelectedBackgroundHover;

      cursor: pointer;

    }

 

    &.tabulator-row-moving {

      border: 1px solid #000;

      background: #fff;

    }

 

    &.tabulator-moving {

      position: absolute;

      border-top: 1px solid $rowBorderColor;

      border-bottom: 1px solid $rowBorderColor;

      pointer-events: none;

      z-index: 15;

    }

    //row resize handles

    .tabulator-row-resize-handle {

      position: absolute;

      right: 0;

      bottom: 0;

      left: 0;

      height: 5px;

 

      &.prev {

        top: 0;

        bottom: auto;

      }

 

      &:hover {

        cursor: ns-resize;

      }

    }

 

    .tabulator-frozen {

      display: inline-block;

      position: absolute;

      background-color: inherit;

      z-index: 10;

 

      &.tabulator-frozen-left {

        border-right: 2px solid $rowBorderColor;

      }

 

      &.tabulator-frozen-right {

        border-left: 2px solid $rowBorderColor;

      }

    }

 

    .tabulator-responsive-collapse {

      box-sizing: border-box;

      padding: 5px;

      border-top: 1px solid $rowBorderColor;

      border-bottom: 1px solid $rowBorderColor;

 

      &:empty {

        display: none;

      }

 

      table {

        font-size: $textSize;

 

        tr {

          td {

            position: relative;

 

            &:first-of-type {

              padding-right: 10px;

            }

          }

        }

      }

    }

    //cell element

    .tabulator-cell {

      display: inline-block;

      position: relative;

      box-sizing: border-box;

      padding: 4px;

      border-right: 1px solid $rowBorderColor;

      vertical-align: middle;

      white-space: nowrap;

      overflow: hidden;

      text-overflow: ellipsis;

 

      &.tabulator-editing {

        border: 1px solid $editBoxColor;

        padding: 0;

 

        input, select {

          border: 1px;

          background: transparent;

        }

      }

 

      &.tabulator-validation-fail {

        border: 1px solid $errorColor;

 

        input, select {

          border: 1px;

          background: transparent;

          color: $errorColor;

        }

      }

      //hide left resize handle on first column

      &:first-child {

        .tabulator-col-resize-handle.prev {

          display: none;

        }

      }

      //movable row handle

      &.tabulator-row-handle {

        display: inline-flex;

        align-items: center;

        justify-content: center;

        -moz-user-select: none;

        -khtml-user-select: none;

        -webkit-user-select: none;

        -o-user-select: none;

        //handle holder

        .tabulator-row-handle-box {

          width: 80%;

          //Hamburger element

          .tabulator-row-handle-bar {

            width: 100%;

            height: 3px;

            margin-top: 2px;

            background: #666;

          }

        }

      }

 

      .tabulator-data-tree-branch {

        display: inline-block;

        vertical-align: middle;

        height: 9px;

        width: 7px;

        margin-top: -9px;

        margin-right: 5px;

        border-bottom-left-radius: 1px;

        border-left: 2px solid $rowBorderColor;

        border-bottom: 2px solid $rowBorderColor;

      }

 

      .tabulator-data-tree-control {

        display: inline-flex;

        justify-content: center;

        align-items: center;

        vertical-align: middle;

        height: 11px;

        width: 11px;

        margin-right: 5px;

        border: 1px solid $rowTextColor;

        border-radius: 2px;

        background: rgba(0, 0, 0, .1);

        overflow: hidden;

 

        &:hover {

          cursor: pointer;

          background: rgba(0, 0, 0, .2);

        }

 

        .tabulator-data-tree-control-collapse {

         display: inline-block;

          position: relative;

          height: 7px;

          width: 1px;

          background: transparent;

 

          &:after {

            position: absolute;

            content: "";

            left: -3px;

            top: 3px;

            height: 1px;

            width: 7px;

            background: $rowTextColor;

          }

        }

 

        .tabulator-data-tree-control-expand {

          display: inline-block;

          position: relative;

          height: 7px;

          width: 1px;

          background: $rowTextColor;

 

          &:after {

            position: absolute;

            content: "";

            left: -3px;

            top: 3px;

            height: 1px;

            width: 7px;

            background: $rowTextColor;

          }

        }

      }

 

      .tabulator-responsive-collapse-toggle {

        display: inline-flex;

        align-items: center;

        justify-content: center;

        -moz-user-select: none;

        -khtml-user-select: none;

        -webkit-user-select: none;

        -o-user-select: none;

        height: 15px;

        width: 15px;

        border-radius: 20px;

        background: #666;

        color: $rowBackgroundColor;

        font-weight: bold;

        font-size: 1.1em;

 

        &:hover {

          opacity: .7;

        }

 

        &.open {

          .tabulator-responsive-collapse-toggle-close {

            display: initial;

          }

 

          .tabulator-responsive-collapse-toggle-open {

            display: none;

          }

        }

 

        .tabulator-responsive-collapse-toggle-close {

          display: none;

        }

      }

 

      .tabulator-traffic-light {

        display: inline-block;

        height: 14px;

        width: 14px;

       border-radius: 14px;

      }

    }

    //row grouping element

    &.tabulator-group {

      box-sizing: border-box;

      border-bottom: 1px solid #999;

      border-right: 1px solid $rowBorderColor;

      border-top: 1px solid #999;

      padding: 5px;

      padding-left: 10px;

      background: #ccc;

      font-weight: bold;

      min-width: 100%;

 

      &:hover {

        cursor: pointer;

        background-color: rgba(0,0,0,.1);

      }

 

      &.tabulator-group-visible {

 

        .tabulator-arrow {

          margin-right: 10px;

          border-left: 6px solid transparent;

          border-right: 6px solid transparent;

          border-top: 6px solid $sortArrowActive;

          border-bottom: 0;

        }

      }

 

      &.tabulator-group-level-1 {

        padding-left: 30px;

      }

 

      &.tabulator-group-level-2 {

        padding-left: 50px;

      }

 

      &.tabulator-group-level-3 {

        padding-left: 70px;

      }

 

      &.tabulator-group-level-4 {

        padding-left: 90px;

      }

 

      &.tabulator-group-level-5 {

        padding-left: 110px;

      }

 

      .tabulator-group-toggle {

        display: inline-block;

      }

      //sorting arrow

      .tabulator-arrow {

        display: inline-block;

        width: 0;

        height: 0;

        margin-right: 16px;

        border-top: 6px solid transparent;

        border-bottom: 6px solid transparent;

        border-right: 0;

        border-left: 6px solid $sortArrowActive;

        vertical-align: middle;

      }

 

      span {

        margin-left: 10px;

        color: #d00;

      }

    }

  }

 

  .tabulator-menu {

    position: absolute;

    display: inline-block;

    box-sizing: border-box;

    background: $rowBackgroundColor;

    border: 1px solid $rowBorderColor;

    box-shadow: 0 0 5px 0 rgba(0, 0, 0, .2);

    font-size: $textSize;

    overflow-y: auto;

    -webkit-overflow-scrolling: touch;

    z-index: 10000;

 

    .tabulator-menu-item {

      padding: 5px 10px;

      user-select: none;

 

      &.tabulator-menu-item-disabled {

        opacity: .5;

      }

 

      &:not(.tabulator-menu-item-disabled):hover {

        cursor: pointer;

        background: $rowAltBackgroundColor;

      }

    }

 

    .tabulator-menu-separator {

      border-top: 1px solid $rowBorderColor;

    }

  }

 

  .tabulator-edit-select-list {

    position: absolute;

    display: inline-block;

    box-sizing: border-box;

    max-height: 200px;

    background: $rowBackgroundColor;

    border: 1px solid $rowBorderColor;

    font-size: $textSize;

    overflow-y: auto;

    -webkit-overflow-scrolling: touch;

    z-index: 10000;

 

    .tabulator-edit-select-list-item {

      padding: 4px;

      color: $rowTextColor;

 

      &.active {

        color: $rowBackgroundColor;

        background: $editBoxColor;

      }

 

      &:hover {

        cursor: pointer;

        color: $rowBackgroundColor;

        background: $editBoxColor;

      }

    }

 

    .tabulator-edit-select-list-notice {

      padding: 4px;

      color: $rowTextColor;

      text-align: center;

    }

 

    .tabulator-edit-select-list-group {

      border-bottom: 1px solid $rowBorderColor;

      padding: 4px;

      padding-top: 6px;

      color: $rowTextColor;

      font-weight: bold;

    }

  }

  // Table print styling

  .tabulator-print-fullscreen {

    position: absolute;

    top: 0;

    bottom: 0;

    left: 0;

    right: 0;

    z-index: 10000;

  }

 

  body.tabulator-print-fullscreen-hide > *:not(.tabulator-print-fullscreen) {

    display: none !important;

  }

 

  .tabulator-print-table {

    border-collapse: collapse;

 

    .tabulator-data-tree-branch {

      display: inline-block;

      vertical-align: middle;

      height: 9px;

      width: 7px;

      margin-top: -9px;

      margin-right: 5px;

      border-bottom-left-radius: 1px;

      border-left: 2px solid $rowBorderColor;

      border-bottom: 2px solid $rowBorderColor;

    }

 

    .tabulator-data-tree-control {

      display: inline-flex;

      justify-content: center;

      align-items: center;

      vertical-align: middle;

      height: 11px;

      width: 11px;

      margin-right: 5px;

      border: 1px solid $rowTextColor;

      border-radius: 2px;

      background: rgba(0, 0, 0, .1);

      overflow: hidden;

 

      &:hover {

        cursor: pointer;

        background: rgba(0, 0, 0, .2);

      }

 

      .tabulator-data-tree-control-collapse {

        display: inline-block;

        position: relative;

        height: 7px;

        width: 1px;

        background: transparent;

 

        &:after {

          position: absolute;

          content: "";

          left: -3px;

          top: 3px;

          height: 1px;

          width: 7px;

          background: $rowTextColor;

        }

      }

 

      .tabulator-data-tree-control-expand {

        display: inline-block;

        position: relative;

        height: 7px;

        width: 1px;

        background: $rowTextColor;

 

        &:after {

          position: absolute;

          content: "";

          left: -3px;

          top: 3px;

          height: 1px;

          width: 7px;

          background: $rowTextColor;

        }

      }

    }

  }

}

----------------- SCSS Code Ends: ------------------------------

 

 

 

 

That’s all really – I tried to be as brief as I could.

 

Take care,

David :)

**Comment by Fr1edrick** [comment]
this is other example: https://github.com/Fr1edrick/AngularTabulator 

Greetings!

**Comment by olifolkerd** [comment]
Hi Chaps,

I have added links to these projects to the new [Tabulator Ideas Repo](https://github.com/olifolkerd/tabulator-ideas/). a new area where developers can share their Tabulator code to the wider community.

Cheers

Oli :)
