### ISSUE TITLE
Tabulator 4.6.3 Filter Column Height Restore Issue

### ISSUE THREAD

**Issue by BirukTes** [olifolkerd/tabulator#2823]
Hello,

After enabling header filters and disabling again, the column height is not restored. 
- Is this the default behaviour? 
- Is there a way to restore to normal column height?

Take a look at this JS Fiddle:
[JS Fiddle](https://jsfiddle.net/biruktes/wak920us/24/)

1. ![image](https://user-images.githubusercontent.com/23151263/83399173-aa252780-a3f8-11ea-8475-be167f2a7f81.png)
2. ![image](https://user-images.githubusercontent.com/23151263/83399232-c759f600-a3f8-11ea-8888-8682fa7c7755.png)
3. ![image](https://user-images.githubusercontent.com/23151263/83399282-d771d580-a3f8-11ea-9813-e9e37c0d7418.png)

**Comment by BirukTes** [comment]
I thought this maybe stack-overflow question so I have created one: https://stackoverflow.com/q/62149666/5124710

**Comment by nrayburn-tech** [comment]
I am pretty sure it is a bug.  If it isn't a bug, then I would definitely say it is a feature enhancement that should be added.

I am not aware of any easy way to workaround it right now.  It looks like the height is not re-calculated properly (or at all) when you remove the header filters.

**Comment by BirukTes** [comment]
I noticed another thing with select filter drop down, that the font-size is not same as tabulator default:

1. ![image](https://user-images.githubusercontent.com/23151263/83627985-b394c800-a58f-11ea-9ad1-b2d52e54ff6f.png)
2. ![image](https://user-images.githubusercontent.com/23151263/83628165-fce51780-a58f-11ea-9cb8-db096f2c2676.png)
The second image became slightly larger in font (JSFiddle Firefox), however my project (Chromium based) it was larger, then became smaller to match tabulator with this code:
`
.tabulator-edit-select-list {
            font: inherit;
        }
`

**Comment by olifolkerd** [comment]
Hey @BirukTes 

That is definitely a bug, i will stick it on the fixit list for the next release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
@BirukTes 

The second issue is down to your CSS, the select element popup is not contained inside of Tabulator it is appended directly to the page body so it has no way to reference the font size of the table. You will need to tweak your CSS to resolve that.

A list of classes for the select popup can be found in the [Styling Documentation](http://localhost:8080/docs/4.7/style#css-editors)

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @BirukTes 

I have just pushed a fix for this to the 4.8 branch which will be released next weekend.

Cheers

Oli :)
