### ISSUE TITLE
Allow disabling of automatic event bindings for custom header filters

### ISSUE THREAD

**Issue by marovargovcik** [olifolkerd/tabulator#2826]
**Describe the bug**
When using `<select multiple>` as custom header filter together with custom header filter function, tabulator somehow manages to send string value to filter function instead of result passed with `success(values)` (variable values is an array). 

**Tabulator info**
4.6.3

**Example**
https://codepen.io/marovargovcik/pen/vYLEXPX

**To Reproduce**
1. Open example
2. Select multiple values in header filter (hold Ctrl and click any options)

At this point you should notice that table content changed twice for some reason.
Open developer console and there should be warning saying that custom filter function got `headerFilterValue` of type string instead of expected Array.

**Desktop (please complete the following information):**
 - OS: Windows 10, version 2004
 - Chrome
 - 83.0

**Comment by olifolkerd** [comment]
Hey @marovargovcik 

This is happening because the tabulator filter module adds additional event bindings to the filter element, which usually dont cause an issue but in your usage case trigger the string value to be sent.

I will look into ways to avoid this in future, but for now you should be able to safely ignore any filter calls with a string type.

Cheers

Oli :)

**Comment by marovargovcik** [comment]
Thanks for getting back to me. 
Yes that is exactly what I did. Here is a updated code example with workaround I ended up with. 
Someone might find it useful.
https://codepen.io/marovargovcik/pen/vYLEXPX

**Comment by olifolkerd** [comment]
The ***headerFilterLiveFilter*** column definition option now allows to you disable the built in header event triggers
```js
{title:"Name", field:"name", headerFilter:"input", headerFilterLiveFilter:false}
```
Cheers

Oli 👍
