### ISSUE TITLE
Browser Compatability with Microsoft Edge 17+

### ISSUE THREAD

**Issue by michaelcmelton** [olifolkerd/tabulator#2827]
Oli:

Has the library been tested with Microsoft Edge? My customers are experiencing issues with MS Edge primarily the following:

- Unable to clear header filters with the x, it does not show.
- when table data is updated, it does not replace the old data.
- Scrolling is ineffective.

Let me be clear, the library works wonderfully, and as expected in Chrome. I'm just wondering Edge compatability.

**Comment by olifolkerd** [comment]
It has worked on edge up till this point

If you think you have found an issue, please create a JS fiddle that
demonstrates the problem.

Cheers

Ol'

**Comment by michaelcmelton** [comment]
Closing. Had to implement redraws. Apologies.
