### ISSUE TITLE
Post build access

### ISSUE THREAD

**Issue by mmalenkov** [olifolkerd/tabulator#283]
After initial render any attempt to call $("#myDiv").tabulator results in "tabulator is not a function. Any advise on how handle cases like that

**Comment by olifolkerd** [comment]
could you post a copy of yout Tabulator constructor and then the next function you are trying to call on it.

Cheers

Oli

**Comment by olifolkerd** [comment]
if you can post an example of the code you were trying to use i would be happy to give you some pointers.

Cheers

Oli

**Comment by olifolkerd** [comment]
closed due to inactivity
