### ISSUE TITLE
Make pagination's page number titles translatable

### ISSUE THREAD

**Issue by BenjaminGoetz** [olifolkerd/tabulator#2831]
## Current situation

When positioning the cursor hover a page number in the pagination, the sentence "Show Page x" appears, accordingly to the code at https://github.com/olifolkerd/tabulator/blob/master/src/js/modules/page.js#L405

## Requested solution

Add an entry in the `langs` configuration to translate the "Show Page %d" sentence and use it in the `title` and `aria-label` attributes.

**Comment by olifolkerd** [comment]
Hey @BenjaminGoetz 

I have made a new localization option called "show_page" to make this possible. It will be available in tomorrows 4.7 release.

Cheers

Oli :)
