### ISSUE TITLE
Default DateTime Format 24h Issue

### ISSUE THREAD

**Issue by JonGinty** [olifolkerd/tabulator#2832]
**Describe the bug**
Default formatter for datetime displays all PM times as if they were AM (i.e. 12h).

I suspect this is a mistake although I'll accept if it's by design. The default input / output formatter specifies the time portion as "hh:mm:ss" however changing to "HH:mm:ss" will resolve this by outputting the time in 24h format.

Apologies if this is a duplicate, I had a look through existing issues but couldn't find anything.

**Tabulator Info**
4.6.3

**Working Example**
https://jsfiddle.net/JonGinty/x1m09nwh/7/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Create date column using date string value of which the time portion is after midday (e.g. 2020-06-09 13:56:25).

**Expected behavior**

Output is 09/06/2020 13:56:25 OR 09/06/2020 1:56:25 PM

Actual behaviour is 09/06/2020 01:56:25

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 76

**Comment by olifolkerd** [comment]
Hey @JonGinty 

Thanks for reporting that, it was certainly an oversight.

I have pushed a fix for this to the 4.7 branch that will be released tomorrow.

Cheers

Oli :)
