### ISSUE TITLE
Placeholder not showing up

### ISSUE THREAD

**Issue by Abourass** [olifolkerd/tabulator#2833]
**Describe the bug**
Placeholder doesn't show up even when table is empty.

**Tabulator Info**
- 4.6

**Working Example**
https://jsfiddle.net/e1graonk/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Add a placeholder value
2. Load table from ajaxURL

**Expected behavior**
DOM Node should be appended

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Brave
 - Version 1.3.115

**Comment by olifolkerd** [comment]
Hey @Abourass 

Im afraid that the Brave browser is not on our supported browser list. It looks like they have an issue with their layout engine. 

If you use Tabulator on a mainstream browser you will see that it works.

Cheers

Oli :)

**Comment by Abourass** [comment]
![image](https://user-images.githubusercontent.com/39917231/85210601-84f04e80-b2fe-11ea-8292-56654e212929.png)
@olifolkerd Brave is built on top of Chromium and uses the same view engine. I went ahead and loaded it in chrome and firefox, and exact same issue is present.

**Comment by Abourass** [comment]
@olifolkerd I'm still experiencing this issue in all browsers, on the most current release of Tabulator.
