### ISSUE TITLE
Lots of issues with select editor and scrolling

### ISSUE THREAD

**Issue by genyded** [olifolkerd/tabulator#2837]
**Describe the bug**
If using the select editor, horizontal scrolling does not work.

**Tabulator Info**
-4.6.3

**Working Example**
https://jsfiddle.net/9usL8znd/4/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://jsfiddle.net/9usL8znd/4/
2. Click on the 3rd column and start navigating using tab
3. The table will not scroll when naviating
4. Un-comment the cellEditing option for the table to try and force scrolling
5. Click on the 3rd col and it will jump (even though visible is set to false) and table focus is lost

**Expected behavior**
Table should navigate regardless of editor like an Excel spreadsheet. Once an off screen cell is hit, it should be scrolled to and edit enabled. The select editors drop down div is completely outside the table though so it will pop up off screen and outside the table. If the cell is partially visible you can sometimes see it, but no scrolling occurs (probably because the drop down div outside the table has the focus).

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version latest

**Additional context**
We LOVE tabulator so we'd hate to have to abandon it, but also a severe need for Excel like behavior with a slightly large (often wider than the table screen size) number of 'select' columns.

**Comment by olifolkerd** [comment]
Hey @genyded 

This is because your body element has no fixed height so when the text area resizes it makes the table bigger which then makes the body element bigger which then redraws the table.

If you manage the height of the containing element then this wont happen.

Cheers

Oli :)

**Comment by genyded** [comment]
OK, but then how do you get horizontal scrolling to work? https://jsfiddle.net/9usL8znd/4/ when the last (off screen) column is tabbed to, it is not scrolled into view.
