### ISSUE TITLE
Grouping Data with Frozen column does not freeze group header row

### ISSUE THREAD

**Issue by lac616** [olifolkerd/tabulator#284]
Hello,

Still loving this control. Thanks again.

In the screen shots below, I am grouping data by a subcategory with a freeze on the item column. When I scroll to the right, the group header row description scrolls as well. It would be nice to have the ability to freeze the group header row.

![groupdata1](https://cloud.githubusercontent.com/assets/27359692/25538710/c6f35664-2c11-11e7-882f-f12be64eb1c8.PNG)

![groupdata2](https://cloud.githubusercontent.com/assets/27359692/25538709/c6f11994-2c11-11e7-87c9-65ff5cb5ba1a.PNG)

**Comment by olifolkerd** [comment]
Hey,

Thanks for getting in touch, that is an outstanding issue at the moment, but not to worry when Tabulator 3.0 is released next month this will be addressed!.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey,

Tabulator 3.0 beta is now available, and fixes the horizontal scrolling group header issue.

Check it out in action [here](http://olifolkerd.github.io/tabulator/examples/3.0/#grouping)

Cheers

Oli

**Comment by Ashlalala** [comment]
I still have this exact issue in the 3.0 version 
Here is how my frozen group code looks like: 
`const columns = [
  { title: "Name", field: "name", width: 160, headerFilter: true, headerFilterPlaceholder: "Filter by name...",  },

  {//create column group
    title: "Personal Info",
    frozen: true,
    columns: [
      { title: "Gender", field: "gender", editor: "list", editable: false, editorParams: { values: { "male": "Male", "female": "Female", clearable: true } }, headerFilter: true, headerFilterParams: { values: { "male": "Male", "female": "Female", "": "All" }, clearable: true } },
      { title: "Favourite Color", field: "col", },
      { title: "Date Of Birth", field: "dob", hozAlign: "center", sorter: "date", },
    ],
  },`
