### ISSUE TITLE
Programatically call context menu upon component, or at least enable upon left click

### ISSUE THREAD

**Issue by vini-brito** [olifolkerd/tabulator#2841]
*Is your feature request related to a problem? Please describe.**
I'd like to trigger the context menu from a left click too. 

**Describe the solution you'd like**
Ideally, I'd like to have a function to call to do so programmatically, not just on left click, for example I have the context menu being called upon the row component, so would be great to be able to call `row.loadContextMenu()` or something along these lines.
In a less ideal manner, a flag (boolean) to set that would enable context menu by left clicking.

**Describe alternatives you've considered**
Tinkered for two hours on trying to dispatch the custom event "contextmenu" or to simulate a virtual right click to no avail.

**Additional context**
None.

**Comment by olifolkerd** [comment]
I'm not sure I understand why this would be useful.

The whole point of a context menu is that is loaded relative to where the user clicks, hence the context part of the name.

If there was a function to trigger a menu, Tabulator would have no knowledge of where to load the menu, and the row may even be off the screen.

Could you provide a more specific usage case so I can understand how people would benefit from this being added to Tabulator.

Cheers

Oli

**Comment by vini-brito** [comment]
Sure! The use case is triggering it with left click, in another words, with the main mouse click.

**Comment by olifolkerd** [comment]
Hey @vini-brito 

I think that is a bit of a neiche edge case and would not really be looking to add that into the tabulator on the whole.

I you want to make a tweak to your fork to make this possible, that should be fairly simple. in `/src/js/modules/menu.js` you will see it adds event listeners to the ***contextmenu*** event. if you change these to listen for the ***click*** event instead then it will do as you want.

Cheers

Oli :)
