### ISSUE TITLE
autocomplete field does not allow horizontal key (left/right arrow keys) 

### ISSUE THREAD

**Issue by anilkumar27** [olifolkerd/tabulator#2843]
{ title: "Email ", field: "email",  headerSort:true, validator:[
                {
                    type:this.validateEmailEntry.bind(this),
                    parameters:{  }
                }
            ], sorter:"alphanum", 
                editor:"autocomplete", editorParams:{
                    showListOnEmpty:true, //show all values when the list is empty,
                    freetext:true, //allow the user to set the value of the cell to a free text entry
                    allowEmpty:true, //allow empty string values
                    searchFunc:this.changeEmailAssignment.bind(this)
                }, width:'14%', editable:this.editCheck.bind(this)
    },

in the above code, we are using editor type 'autocomplete' and unable to use left/right arrow key inside this editor. however 'verticalNavigation' is given as a separate attribute or properties but could not find the same for horizontal navigation. is there a way to handle left/right navigation arrows  in 'autocomplete' editor ?

**Comment by olifolkerd** [comment]
Hey @anilkumar27 

No editor allows horizontal navigation using the arrow keys, Tabulator uses tab and shift+tab for horizontal table navigation.

Cheers

Oli :)

**Comment by anilkumar27** [comment]
hey @olifolkerd , 

Thanks for the response. 

Tab or shift+tab is navigating between next editable field (for switching to next or previous editable field ). That's works perfectly.
But my query was related to same editable field.

what i mean is, with in the same editable field with 'autoComplete' am not able to use left/right arrow key.  

Example: In 'autoComplete' field assume i have entered an emailID "**examp@company.com**" . Now i have to edit the emailID to "**example@company.com**" by navigation my cursor to certain index of the string . Currently its possible only my mouse cursor movement.

Same is not working using left/right arrow keys to move the cursor.

**Comment by olifolkerd** [comment]
Hey @anilkumar27,

Thanks for the clarification there, that is definitely a bug, it should allow you to move the cursor through the text.

I have pushed an update to the 4.7 branch to fix this. This will be released later today.

Cheers

Oli :)

**Comment by anilkumar27** [comment]
Thanks @olifolkerd .  Will wait for the update .

Cheers :)

**Comment by anilkumar27** [comment]
Hey @olifolkerd ,

i have observed one more issue in latest 47v of tabulator. 
with **editor:"select"** , if we select any option from dropdown, that entire row contents are getting hidden.

this was working in tabulator v46 and looks like a breakage in 47.

**Comment by olifolkerd** [comment]
Hey @anilkumar27 

If you think you have found an issue, please create a new issue using the bug reporting template, and provide a JS Fiddle. It is impossible to fix an issue based off of a one line description. I need to be able to see how your table is configured to understand what is happening.

Cheers

Oli :)
