### ISSUE TITLE
Table.redraw not redrawing table? Or do I not understand it?

### ISSUE THREAD

**Issue by jadenguitarman** [olifolkerd/tabulator#2846]
Here is a simplified version of my code:
Code: https://codepen.io/jadenguitarman/pen/dyGNKpW?editors=0110
Result: https://cdpn.io/jadenguitarman/debug/dyGNKpW/DqrDdgByOYor

Use the inspector view in the second link above to shrink the page's height, which will shrink the table's height since the table height is 50vh. table.redraw doesn't do anything to this paginated table. What am I missing?

I'd expect table.redraw to redraw the table, that is, make sure the table content fills all available space in, but doesn't overflow, the .tabulator-tableHolder. The amount of rows on this page should change if the available space does.

I'm using Tabulator 4.6.3 in both the Codepen and my actual program. I'm on the newest version of Chrome on Windows 10.

Does table.redraw not work how I think it does? How can I get the result I'm looking for otherwise?

Quick note on my use case: I'm paginating the table so it fits above the fold. However, content above the table changes in height depending on user action. So I've set transitions on the height of the table and the container above it and calling table.redraw when the height changes. But it doesn't do anything, the .tabulator-tableHolder either has empty dark gray space at the bottom (when the table gets larger) or it overflows and becomes scrollable (when the table gets smaller). Obviously I haven't implemented all of this in the CodePen, but I created another example that has the same behavior.

**Comment by jadenguitarman** [comment]
Is it possible that table.redraw just isn't working with pagination?

**Comment by olifolkerd** [comment]
Hey @jadenguitarman 

You havnt imported the tabulator CSS into that project so the browser has no idea how to render the table.

With the CSS imported correctly it all works fine.

Cheers

Oli :)

**Comment by jadenguitarman** [comment]
@olifolkerd I added the CSS file to the JSFiddle. It's also been in my project, looks like I forgot to include it. It's still not redrawing on resize for me.

**Comment by jadenguitarman** [comment]
@olifolkerd Any advice? I'm trying to use Tabulator on a second project now, with the CSS and JS included, and it still isn't redrawing.
