### ISSUE TITLE
Sorting on data no represented in column

### ISSUE THREAD

**Issue by Paraplegix** [olifolkerd/tabulator#285]
Aaaand more issues with sorting :smile: 
I know you are working on the 3.0 but this is just for signaling currents problem that i don't know if they will be adressed in 3.0

Fiddle for example
https://jsfiddle.net/5owx6cer/1/
Its a simple table with 4 column, and buttons to change the sorting (one button to sort asc on each columns)

So my problem is : you have to declare a column for the field if you want to have any kind of sorting done on it ! You might not want to have the id displayed but you probably still want to have it as the sorting column.
It's easily bypassed by adding a `visible:false` column on that field (the commented column declaration in the example), but it should IMHO be possible without.

Also (lazyness talking here) could the base sorting function detect if the field is number only or string, in the example the 3rd column is filled with 9, 80, 700 and 1000, and should be in this order (asc), But as it is sorted as string, it is in the reverse order

Another thing i've noticed but is not shown in the jsfiddle, but it apear that if you trigger sorting on unexisting column , and have more than 10-20 rows, most of the data will stay in the same row but a few will switch row with each other randomly

**Comment by olifolkerd** [comment]
Thanks for the feedback,

most of the issues you have mentioned will be resolved in version 3.0.

I can see your point about sorting on non visible columns, but to keep things clean i don't want to start defining sorting controls anywhere but in the column definition array so will be sticking with that route, unless you can think of a clean way of handling it,

As for the auto sorter definition, I toyed with the idea a while back of making it analyse the first rows value and sorting based on that, i think if i restrict it to sort by string, number or alpha numeric that might just work. i will have a look at including that at in version 3.0 as that would solve the sorting issues on "hidden" columns, by giving them a reasonable chance of successfully sorting by default.

Thanks for the feedback

Oli

**Comment by olifolkerd** [comment]
Hey,

You will be happy to hear that version 3.0 is now in beta release, sorters now automatically apply to all defined columns, with Tabulator making a guess as to the type of sorter to apply based on the content of the first row, it can detect strings, numbers, alpha numeric and booleans. There is now a ***headerSort*** option to allow you to turn header sorting off on a per column basis.

Head over to http://olifolkerd.github.io/tabulator/news/ to see the latest features!

Cheers

Oli
