### ISSUE TITLE
Parallel generator functions for cell and row context menus no longer work

### ISSUE THREAD

**Issue by vec2k4** [olifolkerd/tabulator#2852]
**Describe the bug**
If I add both a row context menu generator and a column cell context menu generator to a tabulator, only the column cell context menu generator is called. But if it doesn't return a result, the row context menu generator is no longer triggered. In [v4.6.3](https://github.com/olifolkerd/tabulator/tree/4.6.3) this was working.

This seems to be related to the changes introduced in [this ](https://github.com/olifolkerd/tabulator/commit/cac6d98fce1a3077d7af7263391d1bc6a7c0b648#diff-a4a2ccc70e01a222d10d1c8c8490e3ceL49-R50 )commit.

**Tabulator Info**
4.7.0

**Working Example**
https://jsfiddle.net/vec2k4/ouqdLrw5/

**To Reproduce**
1. Go to the fiddle.
2. Two functions are implemented:
    - `cellContextMenuGenerator`
    - `rowContextMenuGenerator`
3. The `cellContextMenuGenerator` should only display a context menu for cells that are in the 'Age' column. This is working when right clicking on a 'Age'-cell.
4. For all other cells, the `rowContextMenuGenerator` should open a menu. This is not working when right clicking on these cells.

**Expected behavior**
When returning `false` or `null `from the cellContextMenuGenerator, the `rowContextMenuGenerator `function should be called to show the menu.

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome / Chromium Edge / Firefox, all current version

**Additional context**
For me it's not clear why [`e.stopImmediatePropagation()`](https://github.com/olifolkerd/tabulator/blob/37429fa577311e91a5f80199595cc8c71c809a53/src/js/modules/menu.js#L44) has been added to `Menu.prototype.initializeCell` although at this point it is not yet determined whether a menu can be loaded or not which will be evaluated later in the  [`loadMenu`](https://github.com/olifolkerd/tabulator/blob/37429fa577311e91a5f80199595cc8c71c809a53/src/js/modules/menu.js#L74) function.

**Comment by olifolkerd** [comment]
Hey @vec2k4 

the `e.stopImmediatePropagation` was added to prevent accidental triggering of editors on cells when the context menu was added. but i can see in this case it is being triggered even if the function returns false which is incorrect. 

I have pushed a fix for this to the master branch and will include it in a patch update later today.

Cheers

Oli :)

**Comment by vec2k4** [comment]
Hey @olifolkerd 

Thanks for fixing this so fast :)

Cheers Ralf
