### ISSUE TITLE
multiselect header: selecting multiple values results in an empty table

### ISSUE THREAD

**Issue by jjech** [olifolkerd/tabulator#2854]
**Describe the bug**
When using the new multiselect header filter, selecting multiple values results in an empty table (possibly filtering with AND for the list of values instead of OR).

**Tabulator Info**
4.7.0

**Working Example**
https://jsfiddle.net/jjech/3th28pv0/264

**To Reproduce**
1. Click on the header filter field for the 'Species' column.
2. Select a single value from the dropdown and observe that the table filters as expected.
3. Select an additional value from the dropdown and observe that the table is filtered to an empty table.

**Expected behavior**
Selecting multiple values results in a filtered table that contains all selected values.

**Comment by olifolkerd** [comment]
Hey @jjech 

This is not an issue with tabulator,you are just using the wrong filter function. by default Tabulator uses the ***like*** / ***=*** filter functions for header inputs.

If you are using a multiselect header filter then you need to use the "in" filter, `headerFilterFunc:"in"` which will then check if the value is in the array returned from the header filter.

Cheers

Oli :)
