### ISSUE TITLE
cannot 'clear' the new multiselect header filter

### ISSUE THREAD

**Issue by jjech** [olifolkerd/tabulator#2855]
**Describe the bug**
When using the new multiselect editor as a header filter, I am unable to clear the filter (whether by clicking the 'x' or by manually clearing the field using backspace/delete keys).

**Tabulator Info**
4.7.0

**Working Example**
https://jsfiddle.net/jjech/3th28pv0/264

**To Reproduce**
1. Click on the header filter field in the 'Species' column.
2. Select one species to filter on (do not select more than one species as there is [another issue](https://github.com/olifolkerd/tabulator/issues/2854) with that).
3. Observe the table filtered as expected. Now click the 'x' to clear the header filter.
4. The table appears to clear the filter correctly, but when the dropdown menu is closed, the table reverts to the previous filter.

**Expected behavior**
Clicking the 'x' or manually clearing the filter with backspace resets the header filter persistently until a new filter is applied.

**Comment by olifolkerd** [comment]
Hey @jjech 

Thanks for letting me know, i have pushed a fix for this to the master branch and will include it in a patch release this evening.

Cheers

Oli :)

**Comment by jjech** [comment]
Thanks for all your help and clarification on the issues I opened! Looking forward to checking out the patch release.

**Comment by CrystalHuXPL** [comment]
Is the bug fixed yet?

**Comment by jjech** [comment]
> Is the bug fixed yet?

Yes, Oli pushed a fix on 06/27/2020 and the bug was closed.
