### ISSUE TITLE
exception when replacing data after edit

### ISSUE THREAD

**Issue by vec2k4** [olifolkerd/tabulator#2857]
**Describe the bug**
When I edit a cell, then get the tabulator data via `getData` and then set it again via `replaceData`, an exception occurs and the table display is broken. The same happens if I use `setData` instead of  `replaceData`.

**Tabulator Info**
4.7.0

**Working Example**
https://jsfiddle.net/vec2k4/3u70rmaj/

**To Reproduce**
1. Go to the fiddle.
2. Edit a name in the table, e.g. rename "Oli Bob" to "Oli Bobby" and press "Enter" to apply the change.
3. Press the "Reset" button.
4. See the exception in the browser console and the broken table display.

**Expected behavior**
No exception should occur and the table display shouldn't be broken.

**Screenshots**
![tabulator-validate](https://user-images.githubusercontent.com/9272347/85588411-f43da980-b642-11ea-9d79-35aaafe753be.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - All major browsers on windows, current versions

**Additional context**
The exception is:
![image](https://user-images.githubusercontent.com/9272347/85588706-37981800-b643-11ea-8027-28908e117021.png)

For me it looks like that [here ](https://github.com/olifolkerd/tabulator/blob/37429fa577311e91a5f80199595cc8c71c809a53/src/js/modules/edit.js#L435) a check should be implemented to make sure the validate module exists (i.e. is not `undefined`) for a given cell:
![image](https://user-images.githubusercontent.com/9272347/85589318-c1e07c00-b643-11ea-97c1-22bdbb25ca2d.png)

**Comment by olifolkerd** [comment]
Hey @vec2k4 

Thanks for the headsup. I have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)

**Comment by vec2k4** [comment]
Hey @olifolkerd 

Thanks for fixing this. 

Cheers Ralf
