### ISSUE TITLE
Adding new column after editting cell causes table to break and Tabulator emits errors in console.

### ISSUE THREAD

**Issue by mill1000** [olifolkerd/tabulator#2858]
**Describe the bug**
If a column is added to the table (via `addColumn`) after a cell has been edited (even if cancelled) the table breaks and some exceptions appears in the console.

**Tabulator Info**
Tabulator 4.7
Vanilla JS

**Working Example**
https://jsfiddle.net/0xawh2t3/1/

**To Reproduce**
1. Run JSFiddle.
2. Click to edit the cell under "Some Column".
3. Click "Break It".
4. Watch row disappear and table fall apart.

Alternate:
1. Run JSFiddle
2. Click "Break It" to add some new columns. (Everything OK so far).
3. Edit the row under "Some Column".
4. Click "Break It" and watch table fall apart. See screenshot.

**Expected behavior**
The table to add the column and not break. :)

**Screenshots**
![image](https://user-images.githubusercontent.com/6924622/85644718-07f20b80-b655-11ea-8eaf-1344f0ebb9e2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox 77.0.1, Edge 83.0.478.54 

**Additional context**
Here are the console errors when the issue is triggered.
> tabulator.min.js:4 Uncaught TypeError: Cannot read property 'removeChild' of null
>     at c.delete (tabulator.min.js:4)
>     at a.deleteCells (tabulator.min.js:4)
>     at a.initialize (tabulator.min.js:4)
>     at s._virtualRenderFill (tabulator.min.js:3)
>     at s.reRenderInPosition (tabulator.min.js:3)
>     at s.redraw (tabulator.min.js:3)
>     at e.d.redraw (tabulator.min.js:5)
>     at ResizeObserver.<anonymous> (tabulator.min.js:11)
> c.delete @ tabulator.min.js:4
> a.deleteCells @ tabulator.min.js:4
> a.initialize @ tabulator.min.js:4
> s._virtualRenderFill @ tabulator.min.js:3
> s.reRenderInPosition @ tabulator.min.js:3
> s.redraw @ tabulator.min.js:3
> d.redraw @ tabulator.min.js:5
> (anonymous) @ tabulator.min.js:11
> tabulator.min.js:7 Uncaught (in promise) TypeError: Cannot set property 'invalid' of undefined
>     at E.clearEdited (tabulator.min.js:7)
>     at c.delete (tabulator.min.js:4)
>     at a.deleteCells (tabulator.min.js:4)
>     at a.initialize (tabulator.min.js:4)
>     at a.reinitialize (tabulator.min.js:4)
>     at tabulator.min.js:3
>     at Array.forEach (<anonymous>)
>     at s.reinitialize (tabulator.min.js:3)
>     at tabulator.min.js:2
>     at new Promise (<anonymous>)
> E.clearEdited @ tabulator.min.js:7
> c.delete @ tabulator.min.js:4
> a.deleteCells @ tabulator.min.js:4
> a.initialize @ tabulator.min.js:4
> a.reinitialize @ tabulator.min.js:4
> (anonymous) @ tabulator.min.js:3
> s.reinitialize @ tabulator.min.js:3
> (anonymous) @ tabulator.min.js:2
> t.addColumn @ tabulator.min.js:2
> (anonymous) @ tabulator.min.js:5
> d.addColumn @ tabulator.min.js:5
> breakTable @ minimal.html:14
> onclick @ minimal.html:8
> Promise.catch (async)
> (anonymous) @ tabulator.min.js:5
> d.addColumn @ tabulator.min.js:5
> breakTable @ minimal.html:14
> onclick @ minimal.html:8
> tabulator.min.js:4 Uncaught TypeError: Cannot read property 'removeChild' of null
>     at c.delete (tabulator.min.js:4)
>     at a.deleteCells (tabulator.min.js:4)
>     at a.initialize (tabulator.min.js:4)
>     at s._virtualRenderFill (tabulator.min.js:3)
>     at s.reRenderInPosition (tabulator.min.js:3)
>     at s.redraw (tabulator.min.js:3)
>     at e.d.redraw (tabulator.min.js:5)
>     at ResizeObserver.<anonymous> (tabulator.min.js:11)
> c.delete @ tabulator.min.js:4
> a.deleteCells @ tabulator.min.js:4
> a.initialize @ tabulator.min.js:4
> s._virtualRenderFill @ tabulator.min.js:3
> s.reRenderInPosition @ tabulator.min.js:3
> s.redraw @ tabulator.min.js:3
> d.redraw @ tabulator.min.js:5
> (anonymous) @ tabulator.min.js:11

**Comment by vec2k4** [comment]
I think this is related to #2857 

To quick fix it you could override the clearEdited function and implement a check for the validate module, although I don't know if this is the right way to do it.

Here is a link to your modified fiddle that temporarily fixes the bug: https://jsfiddle.net/vec2k4/cv9xk56r/

Also you could have a look at #2858 which is also related to this issue.

**Comment by mill1000** [comment]
Thanks for the work around. Seems to work ok.

**Comment by olifolkerd** [comment]
This has been resolved in  a commit to the master branch.

Cheers

Oli :)
