### ISSUE TITLE
Table border formatting

### ISSUE THREAD

**Issue by arita37** [olifolkerd/tabulator#286]
Hi,

Is there  a way to show /remove some border of a table; column or row ?
I searched but could not find, and hope this question will be helpful to many people.

**Comment by olifolkerd** [comment]
Hey,

Sorry for the delay in getting back to you on this one.

All borders are controlled in the tabulator.css file. you want to change the border property on the ***.tabulator-cell*** and ***.tabulator-row*** classes.

full details on the available classes can be found [here](http://olifolkerd.github.io/tabulator/docs/#css)

Let me know if you need any more information.

Cheers

Oli

**Comment by kostmo** [comment]
Updated link to CSS documentation: http://tabulator.info/docs/4.4/style#css
