### ISSUE TITLE
validationFailed callback doesn't fire if validationMode is set to "highlight"

### ISSUE THREAD

**Issue by mill1000** [olifolkerd/tabulator#2861]
**Describe the bug**
When validationMode is set to "highlight" the validationFailed callback does not fire.

**Tabulator Info**
4.7

**Working Example**
https://jsfiddle.net/7065hmru/1/

**To Reproduce**
1. Enter a non-numeric value into the cell and navigate away.
2. See the cell highlighted as invalid.
3. See no alert popup.
4. Comment out  `validationMode: "highlight",` in table def
5. Enter non-number value into a cell and navigate away.
6. See alert popup

**Expected behavior**
This may be desired behavior but I think it should be possible to highlight invalid cells **and** trigger a callback. e.g. To assign a tooltip that explains why. 

~I think it is possible to workaround this by defining a custom validator but it shouldn't be necessary.~ I take it back. Custom validators can be defined, but not custom validation _modes_.

**Desktop (please complete the following information):**
* Windows 10
* Firefox 77.0.1

**Related Feature Request**
As a feature request, it would be nice if there was a method to query a cell not just for it it's valid, but which validators have failed. I could then define a column tooltip that check cell validity and outputs a proper message per cell. e.g. 
```
tooltip: (c) => { c.getFailedValidators().includes("unique") ? "Cell values must be unique." : ""}
```

**Comment by olifolkerd** [comment]
Hey @mill1000 

This is currently the correct behaviour, the ***validtionFailed*** callback is only called when the validation mode is ***blocking***, The ***highlight*** and ***manual*** modes are intended to be passive and it is up to the developer to choose when to check for valid data.

That being said, i do take your point on board that in highlight mode there would be no issue with triggering that callback, so i will add that in the next patch release later today.

The validation modes are tightly coupled with the internal working of the edit system, it would be impractical to provide an external option to customise the modes themselves. if you feel there is a mood missing please raise a feature request.

Cheers

Oli :)

**Comment by mill1000** [comment]
Great. Thanks for the update!
