### ISSUE TITLE
Scrolling issue with frozen columns

### ISSUE THREAD

**Issue by genyded** [olifolkerd/tabulator#2863]
**Describe the bug**
When frozen columns is used in tandem with editing, when you SHIFT+TAB back to a column, it is not fully visible.

**Tabulator Info**
- 4.7.0

**Working Example**
https://jsfiddle.net/6wxk05dg/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://jsfiddle.net/6wxk05dg/
2. Click on the second column (C111111) then tab at least 3 times (enough to make the table scroll horizontally)
3. Now click SHIFT+TAB to go back one column and see that it is not fully visible (it is partially under the frozen column)
4. If you comment out the first column from being frozen, this does not happen and scrolling works as expected
5. If you leave the first column frozen and force scrolling in the cellEditing property, then you can scroll back to the first non-frozen column without issue, but the first non-frozen column then has the issue instead.

**Expected behavior**
Table should adjust scroll to account for frozen column(s) when editing. 

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version latest

**Comment by genyded** [comment]
Hi Oli,

We were planning on making a generous donation to Tabulator if we could get Tabulator working the way we need, but we are running out of runway with regard to time. 

We realize this is a side project for you, but if we cannot find a working example with frozen columns combined with cell editing (of non-frozen columns) with scrolling working properly for the editable columns soon, we're going to have to try some alternative grids. That is not what we want, but we have already surpassed out timelines.

**Comment by olifolkerd** [comment]
Hey @genyded 

Thanks for bringing this issue to my attention, I will see if i can get a fix in for the patch release next weekend.

I am very grateful for any donations that people so kindly make to the project.

What i will say is that this is an open source project, and it is unrealistic to expect two day turnarounds on any project of this nature. You raised the issue on a Friday, and seem to have the expectation that i would solve it for you over the weekend, this is simply not how community projects work.

While i would of course love it if you continued to use Tabulator. If you require the level of service that your last couple of posts indicate, then it may be worth you considering a different library with a service plan suited to your needs. 

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @genyded 

You are in luck, it was a quick fix. I have pushed an update to the master branch with the fix. and will include it in next patch release.

Cheers

Oli :)
