### ISSUE TITLE
Tabulator like a form

### ISSUE THREAD

**Issue by B-tristan** [olifolkerd/tabulator#2864]
Hi,
It would be nice and very useful (specially in mobile context) to be able to use the grid as a form and display record by record. What do you think ?

![image](https://user-images.githubusercontent.com/19173125/85987382-db8c1580-b9ed-11ea-9da0-169ac2bb8270.png)

**Comment by olifolkerd** [comment]
Hey @B-tristan 

Thanks for your suggestion.

The purpose of Tabulator is to display grids of data. and all updates to the library add features around that core purpose.

A few people have suggested using the table as a form, but at that point there are a great many other libraries out there that are designed specifically for managing form data, and they will do a far better job of it.

For that reason i would not be looking to add form functionality to Tabulator

Cheers

Oli :)
