### ISSUE TITLE
Cannot access the input field in last few tabulator cells which has searchfunction defined

### ISSUE THREAD

**Issue by amv93** [olifolkerd/tabulator#2865]
**Describe the bug**
Input fields at the last few cells in a column with search function and editor values are not accessible

**Tabulator Info**
- 4.7.1

**Working Example**
https://jsfiddle.net/amv93/L0af9vkt/19/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://jsfiddle.net/amv93/L0af9vkt/19/
2. Click on Editor's Settings -> Tabs(Columns) 
3. Resize so that the table is displayed with max resolution
4. Click on the last 2 cells in the Email column, you cannot see the input option or the search list
5.Click on the first few cells in the Email column, input field and search list are shown.
6. Now reduce the resolution and try 4 and 5
7. Change the resolution to maximum , change autoResize to false and try 4 and 5
8. Change the resolution to maximum, replace
`values:{
              "steve":"steve@boberson.com",
              "bob":"bob@jimmerson.com",
              "jim":"jim@stevenson.com",
              "Harvy":"harvy@david.com",
              "Ken":"ken@thompson.com",
              "Denny":"denny@beckham.com",
              "Ram":"ram@kashyap.com",
              "Pranitha":"pranitha@chadda.com",
              "Iva":"ivanka@madena.com",
              "Rebecca":"rebecca@stevens.com",
              "Izzie":"izzie@harlock.com",
              "Janya":"janya@khanwald.com"
    			},`
with 
`values:{
              "steve":"steve@boberson.com",
              "bob":"bob@jimmerson.com",
              "Janya":"janya@khanwald.com"
},`
**Expected behavior**
Input field should be accessible at all resolutions 

**Desktop (please complete the following information):**
 - OS: Win
 - Browser  Chrome
 - Version 81.0.4044.138 (Official Build) (64-bit)

**Additional context**
Raised a stackoverflow question, but this usually does not get answered soon. Hence raising a bug.

**Comment by bakvat** [comment]
Are you facing issues in newly added rows after resolution change?

**Comment by amv93** [comment]
Yes, if I reduce the resolution , then then the last few input fields will be accessible

**Comment by olifolkerd** [comment]
Hey @amv93,

That is because the popup list element is set to appear  underneath the text element and the way you have your page setup does not allow for the page to overflow to show the rest of the element.

This isn't a Tabulator issue, this is to do with the setup of the page the table is in.

Cheers

Oli :)

**Comment by amv93** [comment]
@olifolkerd ,
But there is no other element enclosing this table.
Also, if autoresize is set to false, the issue will not be reproduced
