### ISSUE TITLE
Row Formatter Example 

### ISSUE THREAD

**Issue by LondonWebFactory** [olifolkerd/tabulator#2866]
**Website Page**
http://tabulator.info/examples/4.7#row-formatter

**Describe the issue**
The example has the following line of code that throws an error:

`width = element.element.offsetWidth,`

Changed it to this:

`width = element.offsetWidth,`

and it works fine.

Many thanks for producing a world-class table library!

Tabulator is my new favourite!

Kind Regards,
Adrian Smith

**Comment by olifolkerd** [comment]
Hey @LondonWebFactory 

Thanks for the headsup, i will get that fixed this evening.

Cheers

Oli :)
