### ISSUE TITLE
reactFormatter doesn't know the react state

### ISSUE THREAD

**Issue by pkitcha** [olifolkerd/tabulator#2869]
Hi olifolkerd, I am using the **reactFormatter** to display the value if data is changed (By comparing an old value with the react state).  
Problem is "Cannot read property 'state' of undefined". 

How can I resolve this. Any suggestion ?

      function LabelMatchedFormat(props) {
        const cellData = props.cell._cell.row.data;

        const index = this.state.orders.findIndex(o => o.clientOrderId === cellData.clientOrderId); 
        if(index !== -1)
        {
          if(cellData.cumulativeQty !== this.state.order[index].cumulativeQty){
            return <DynamicLabel value={cellData.cumulativeQty}/>;                 
          }
        }
        return <span>cellData.cumulativeQty</span>;
    }

**Comment by olifolkerd** [comment]
Hey @pkitcha 

There is no react formatter in core Tabulator

If you are using the react native wrapper for Tabulator, please create your issue in that repo.

Cheers

Oli :)
