### ISSUE TITLE
Partial Sum for GroupBy 

### ISSUE THREAD

**Issue by arita37** [olifolkerd/tabulator#287]
New feature:
   Add partial sum for GroupBy in tabulator, it would be very useful.

Thanks for your library, this is a good one.

**Comment by olifolkerd** [comment]
Hey,

Thanks for getting in touch.

Could you clarify what you mean by partial sum? you can already pass a callback to the groupBy option to create custom grouping functions.

Cheers

Oli

**Comment by olifolkerd** [comment]
You can use a custom ***groupBy*** function to achieve this.

```js
$("#example-table").tabulator({
groupBy:function(data){
        //data - the data object for the row being grouped

        var groupKey = // insert your logic to get country information

        return groupKey;
    }
});
```
