### ISSUE TITLE
Horizontal scrollbar appears (unnecessarily) when vertical scrollbar appears, even when layout is ""fitColumns".

### ISSUE THREAD

**Issue by Rickardo228** [olifolkerd/tabulator#2873]
**Describe the bug**
Firstly, amazing library - thank you for all your time and energy. Bug?:
Horizontal scrollbar appears (and table is scrollable horizontally) when vertical scrollbar appears, even when layout is ""fitColumns". Resizing the browser fixes this immediately. I tried different CSS themes, no change.

**Tabulator Info**
- 4.6.2

**Working Example**
https://jsfiddle.net/Rickardo228/cujknsx9/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to 'https://jsfiddle.net/Rickardo228/cujknsx9/'
2. Click on 'Run'
3. See the table has an unnecessary horizontal scrollbar and the vertical scrollbar sits on top of the data.
4. Resize the browser / window. See it is fixed now fixed, as expected:

**Expected behavior**
The vertical scrollbar sits next to the table data, and no horizontal scroll bar is present.

**Screenshots**
![image](https://user-images.githubusercontent.com/51801047/86404845-449eb200-bca8-11ea-91a0-d910e932921c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 83.0.4103.116 (Official Build) (64-bit)

**Additional context**
Mostly a user experience and aesthetic problem. I tried playing around with overflow on .tabulator-holder etc. but no luck. Couldn't find a script in the repo which adjusts overflow on browser resize either. Any help would be massively appreciated!

**Comment by olifolkerd** [comment]
Hey @Rickardo228 

Thanks for your kind words, it is always great to hear that Tabulator is appreciated :)

This is because you are building the table on an element before it is added to the DOM, in certain situations this can result in unusual layout.

If you need to do this, the best practice is to call the ***redraw*** function on the table after it is added to  the DOM.

```js
table.redraw()
```

Cheers

Oli :)

**Comment by Rickardo228** [comment]
Works great, thanks very much! :)

**Comment by McAronDev** [comment]
You have mistake in height definition. In html table height is set to 400px, but in tabulator options it is 90%. You should set it in one place.  If you remove 90% from options, no horizontal scrollbar appears.
https://jsfiddle.net/trpLave2/
