### ISSUE TITLE
Include a rows indicator in the pagination element

### ISSUE THREAD

**Issue by asnaseer-resilient** [olifolkerd/tabulator#2876]
*Is your feature request related to a problem? Please describe.**
I am moving over from a custom table implementation to this library (which I find amazing) but it is lacking one feature that our UI Designer insists we keep. At the bottom of our custom table we display the usual paging control plus an indication of the rows along the lines of:

> 1-25 of 80

The above indicator tells the user that they are currently viewing rows 1 to 25 out of a total of 80 rows. We display this indicator just to the left of the paging controls.

**Describe the solution you'd like**
A new option, say, **includeRowsIndicator**, that displays the data I need.

**Describe alternatives you've considered**
I tried setting **footerElement** to my own custom implementation but then Tabulator does not page the data. I have asked about this on SO here: https://stackoverflow.com/questions/62717705/tabulator-how-to-provide-my-own-custom-pagination-footer-and-have-tabulator-pag

**Additional context**
I am using React with these relevant npm libs:
- "react-tabulator": "^0.13.1"
- "tabulator-tables": "^4.7.1"

**Comment by olifolkerd** [comment]
Hey @asnaseer-resilient 

This would be really easy for you to implement yourself.

The ***footerElement*** option lets you add custom elements to the footer on the table

The ***pageLoaded*** callback is triggered whenever a page is loaded, along with the current page number. when this is called you can use it to update the element in your footer element. given you now know the page number and the page size that is enough to work out the first number, the second number you can call the ***getDataCount*** function on the table and there you have it.

All the info you need.

Cheers

Oli :)

**Comment by asnaseer-resilient** [comment]
Hi @olifolkerd 

Thanks for the suggestion, but how do I overcome the fact that adding my own **footerElement** with paging enabled results in both my pagination controls and Tabulators default pagination controls being displayed?

The Stackoverflow article I linked to has more details of the errors I saw.

**Comment by cseto** [comment]
I used this: http://tabulator.info/docs/4.9/page#element

Add a div in your markup with an id, e.g. `div_name` and add this line per the example.
`paginationElement: document.getElementById('div_name'),`
