### ISSUE TITLE
Support field, tooltip, formatter, etc for column groups which will span cells

### ISSUE THREAD

**Issue by brimimc** [olifolkerd/tabulator#2877]
*Is your feature request related to a problem? Please describe.**
I have a set of data where you either have one value for an attribute or two values for the attribute (one for each side of a call). I would like to be able to display, one or two values in a concise manor. Right now I need three columns to display the data and it takes up a lot of unnecessary space.

**Describe the solution you'd like**
While the general feature of column spanning may cover this, I just wanted to put in what seemed like a simpler case - support all the normal column attributes for column groups. e.g. 
```js
  {
                    title: "Value",
                    field: "value",
                    tooltip: true,
                    formatter: cdrhValueFormatter
                    columns: [

                        {
                            title: "Caller",
                            field: "caller",
                            tooltip: true,
                            formatter: cdrhValueFormatter
                        },
                        {
                            title: "Callee",
                            field: "callee",
                            tooltip: true,
                            formatter: cdrhValueFormatter
                        }]
                }
```
When the data has a value attribute, it should use it and the value should span all child columns, when it doesn't have a value attribute, but does have a caller and callee attribute, then it should render the child column values like it does today.

**Describe alternatives you've considered**
Three columns is the best I have right now - beside splitting the data into two tables

**Additional context**
Here is the three column example - in my case there are only 5 rows that have a value, but 120 rows with caller and callee
<img width="1546" alt="Screen Shot 2020-07-06 at 6 09 44 AM" src="https://user-images.githubusercontent.com/2230920/86582385-8e5cf600-bf4f-11ea-8071-ef1db2acc397.png">
and what I'd like it to look like (with the value values spanning both caller and callee columns
<img width="1125" alt="Screen Shot 2020-07-06 at 6 10 25 AM" src="https://user-images.githubusercontent.com/2230920/86582444-a16fc600-bf4f-11ea-94a5-ff78a0bcc16d.png">

If this is already covered under the 5.0 column spanning, great, go ahead and close this

**Comment by olifolkerd** [comment]
Hey @brimimc 

Thanks for getting in touch.

Colspan functionality is scheduled for the 5.0 release.

More info will follow then.

Cheers

Oli :)
