### ISSUE TITLE
Image Formatter Add formatterParams 

### ISSUE THREAD

**Issue by mpmullally** [olifolkerd/tabulator#2879]
A way to add a prefix and/or suffix to the Image Formatter so that a column can automatically add a url prefix or suffix so that the data would just be the image name. 

Usecase: All images are uploaded by person's name or id in same directory and with same file extension.

**Comment by olifolkerd** [comment]
Hey @mpmullally 

You can already do this with a [Custom Formatter](http://tabulator.info/docs/4.7/format#format-custom)

Cheers

Oli :)
