### ISSUE TITLE
SetHeaderFilterValue rendering problem with autocomplete header filter

### ISSUE THREAD

**Issue by langebangen** [olifolkerd/tabulator#2881]
**Describe the bug**
When setHeaderFilterValue() is called with a value on a column that has the "autocomplete" header filter, nothing is changed in the filter until it is clicked/focused.

It is basically the same issue described [here](https://github.com/olifolkerd/tabulator/issues/1721), but for autocomplete header filter instead of select.

**Tabulator Info**
Tabulator version: 4.7.1

**Working Example**
https://jsfiddle.net/wz5u2kf1/6/

**To Reproduce**
In the jsfiddle, the 'Gender' header filter value should initially be set to 'Female', and it is but it is not shown
in the header until that header filter input is focused/clicked.

**Expected behavior**
The header filter's input should display the value sent in via setHeaderFilterValue without needing to select the input.

**Comment by olifolkerd** [comment]
Hey @langebangen 

Thanks for the info, and for pointing out the similar fix to the select editor that was very helpful.

I have pushed an update to the master branch and will include it in a patch release later today.

Cheers

Oli :)
