### ISSUE TITLE
Freeze row throws an error

### ISSUE THREAD

**Issue by Vivaldib** [olifolkerd/tabulator#2882]
**Describe the bug**
I'm using the following code to freeze the rows. 

`    dataLoaded: function() {
    	console.log("Loaded");
    	let rows = this.getRows();
      rows[0].freeze();
      rows[1].freeze();
      rows[2].freeze();
    } `

**Tabulator Info**
Version 4.7.1

**Working Example**
https://jsfiddle.net/Lxmrc95j/20/

**To Reproduce**
No steps needed, the console shows the error "Uncaught TypeError: Cannot read property 'add' of undefined" at page load.

**Expected behavior**
I expected the row(s) to freeze without the error.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Browser version: 83.0.4103.116 (Official Build) (64-bit)

**Comment by olifolkerd** [comment]
Hey @Vivaldib 

You have an unnecessary ***setData*** call there, if you are already passing your data  into the table on the ***data*** property then there is no need to call the ***setData*** function, you are essentially redrawing the table a second time for no reason.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
This did also highlight an issue with frozen rows not being totally cleared out when the table is redrawn, and the ***dataLoaded*** callback being triggered a bit too early in the render lifecycle.

I have pushed fixes for these to the master branch and will include them in a patch release later today.

Cheers

Oli :)
