### ISSUE TITLE
If you clear the data, the layout may collapse.

### ISSUE THREAD

**Issue by Miyazaki-Ryuji** [olifolkerd/tabulator#2885]
Hello, called the Mick. (Japanese is automatically translated)

I am making it while looking at the latest version 4.7 sample etc. Please tell me.

Here is a simple source.

<!DOCTYPE html>
<html lang="en">

<head>
    <title>Example Test</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../Tabulator/tabulator.min.css">
    
    <script src="../Tabulator/tabulator.min.js"></script>
    <link rel="stylesheet" href="../Css/bootstrap.min.css">
    <link rel="stylesheet" href="../Css/fontawesome-all.min.css">
    <script src="../Scripts/jquery-3.4.1.min.js"></script>
    <script src="../Scripts/bootstrap.bundle.min.js"></script>
</head>

<body>
    <div class="container mx-auto">
        <div id="example-table"></div>
        <div class="col text-center pt-3">
            <button type="button" class="btn mx-2 btn-warning" id="BTNCLEAR"><i class="fas fa-eraser fa-fw"></i>Clear!</button>
        </div>
    </div>

    <script>
        var vNewData = [{ id: 1, name: "New Line", age: "", col: "", dob: "" }];

        var tabledata = [
            { id: 1, name: "Oli Bob", age: "12", col: "red", dob: "" },
            { id: 2, name: "Mary May", age: "1", col: "blue", dob: "14/05/1982" },
            { id: 3, name: "Christine Lobowski", age: "42", col: "green", dob: "22/05/1982" },
            { id: 4, name: "Brendon Philips", age: "125", col: "orange", dob: "01/08/1980" },
            { id: 5, name: "Margret Marmajuke", age: "16", col: "yellow", dob: "31/01/1999" },
        ];

        //create Tabulator on DOM element with id "example-table"
        var table = new Tabulator("#example-table", {
            height: 205, // set height of table (in CSS or here), this enables the Virtual DOM and improves render speed dramatically (can be any valid css height value)
            // data: tabledata, //assign data to table
            layout: "fitColumns", //fit columns to width of table (optional)
            tabEndNewRow: true,
            // layoutColumnsOnNewData: true,
            // reactiveData: true,
            columns: [ //Define Table Columns
                { title: "Name", field: "name", width: 150, editor: "input" },
                { title: "Age", field: "age", hozAlign: "left", formatter: "progress" },
                { title: "Favourite Color", field: "col", editor: "input" },
                { title: "Date Of Birth", field: "dob", sorter: "date", hozAlign: "center" },
            ],
        });

        $(function () {
            table.setData(tabledata);
        });

        $(document).on('click', '#BTNCLEAR', function () {
            table.clearData();
            // table.redraw(true);
            table.setData(vNewData);
            table.redraw(true);
        });
    </script>
</body>
</html>

Successful case
・When you click Clear without doing anything from the initial display.

Failure case 1
・If you click in any line to edit and clear Click, the layout will collapse from that position.

Failure case 2
-If you click Clear after inserting a row by moving the tab on the last row, the layout will be corrupted.

Is the usage incorrect?

Actually, I have already implemented the complicated calculations and aggregations such as order input, JSON input and output, etc. that I have already created, and they are working properly.
However, I could not solve the phenomenon that the layout collapsed during the clearing process, and I am reproducing it in a simple state.

**Comment by Miyazaki-Ryuji** [comment]
(I am sorry because it is an automatic translation in Japanese.)

Hello, After that, I tried various things and solved the layout collapse. However, a new problem occurred.

The layout solution was to redraw when the data changed.
 
           dataEdited: function (data) {
                table.redraw(true);
            },

The function argument ("") didn't help, it had to be ("true").


As a result, new problems are occurring.
Losing the next cursor position by redrawing after input/row addition,
Continuous movement with the tab key will be interrupted.

If only redrawing is a problem, enable the tab key movement of the cursor,
If it is written only at the beginning of the ClearClick event, the layout collapse will occur again.

Setting reactiveData:true, which stops the virtual DOM, did not resolve the layout collapse.

When "editor" is included in the columns definition,
Is there a way to achieve both redrawing and continuous tab key movement?

**Comment by olifolkerd** [comment]
Please create a working JS Fiddle or Code Pen that demonstrates your issue.

It is very hard to offer advice without seeing the table in action.

Cheers

Oli :)

**Comment by Miyazaki-Ryuji** [comment]
(I am sorry because it is an automatic translation in Japanese.)

Thanks Oli Folkerd.

By deploying to CodePen, the cause was clarified.
https://codepen.io/miyazaki-ryuji/pen/VweBPZb

The cause was in the version of "tabulator.min.js".


The download version as of June 22, 2020 is "v4.7.0".
I realized that the download version as of today is "v4.7.2", and it has been resolved.


Around April of this year, I met the most wonderful "Tabulator".
I think it was "v4.6.x" at that time, but I incorporated it into my project and verified it with reference to the documents and samples.

At some point I noticed the version of "4.7" and downloaded and used it, so I did not notice the difference in 4.7.2.

I'm sorry to notice it late. Please close this case.


We hope that Oli Folkerd will continue to play an active role and that "Tabulator" will continue to grow.

Thank you very much.
