### ISSUE TITLE
Load local data file example not showing if using autoColumns

### ISSUE THREAD

**Issue by stavnskov** [olifolkerd/tabulator#2886]
**Describe the bug**
I am trying to follow the example http://tabulator.info/examples/4.7?#file-load data from local JSON file seems to be loaded but does not show content in table

*Tabulator Info**
Version 4.7.1 on Chrome (also tried Edge and Internet Explorer)

**Working Example**
This seems to be a general problem with either the example or the Tabulator library. See someone else SO post here https://stackoverflow.com/questions/62481271/tabulator-4-6-load-table-data-from-local-file-fails-to-post-json-file-to-tabu

JSFiddle: https://jsfiddle.net/3pwymsot/
Example JSON: [ {"name":"Billy Bob", "age":"12"}, {"name":"Mary May", "age":"24"}, {"name":"Christine Lobowski", "age":"15"} ]

**To Reproduce**
1. Click on open file
2. Choose a simple JSON file

**Expected behavior**
Data should be shown in table.
Actual: Judging from scroll bar and that the placeholder text is replaced it seems that data is loaded, but it is not shown.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, IE, Edge
 - Version: 10

**Smartphone (please complete the following information):**
 - Device
 - OS
 - Browser
 - Version

**Additional context**
UPDATE: It seems to be a problem with autoColumns. If I use the below it seems to work:
```
//autoColumns:true,
columns:[
    {title:"Name", field:"name", sorter:"string", width:150},
    {title:"Age", field:"age", sorter:"number", hozAlign:"left", formatter:"progress"},
],
```

**Comment by olifolkerd** [comment]
Hey @stavnskov 

Thanks for the info. 

I have pushed a fix to the master branch and will include it in a patch release later today.

Cheers

Oli :)
