### ISSUE TITLE
dataEdited callback not fired when updateOrAddData changes data in an existing row

### ISSUE THREAD

**Issue by mill1000** [olifolkerd/tabulator#2888]
**Describe the bug**
The `dataEdited` callback is not fired when `updateOrAddData` modifies an existing row. If this is expected behavior it is inconsistent as the `dataEdited` callback is fired when `updateOrAddData` inserts rows in the table.

**Tabulator Info**
v4.7.2 & v.4.7.1

**Working Example**
https://jsfiddle.net/s7dknhjr/

**To Reproduce**
1. Click `Add Row` in Fiddle -> See alert from dataEdited callback when Row 1 is added.
2. Click `Add Missing Data` -> No dataCallback alert when Column2 is updated.

**Expected behavior**
I would expect `dataEdited` to fire anytime table data is updated, except perhaps for complete replacement of data source.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 78.0.2

**Comment by olifolkerd** [comment]
hey @mill1000 

Thanks for bringing this to my attention.

The **dataEdited*** callback should only be triggered when a user edits a field and not when data is programatically edited.

I will look to get this fixed in one of the next patch releases.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
On further thinking, i think this callback has become a bit muddied as Tabulator has  grown in features.

I think a few more callbacks are needed for different types of edit.

I will review this in the next minor release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @mill1000 

I have just pushed an update for this to the 4.8 branch.

On reflection, i think the ***dataEdited*** callback was poorly named, as it was triggered by  user edits and programatic updates.

In this release i have renamed it to ***dataChanged*** and ensured that it is also called when data is updated.

Cheers

Oli :)
