### ISSUE TITLE
Date picker in editable cell

### ISSUE THREAD

**Issue by ravikanth143** [olifolkerd/tabulator#289]
This may help someone who is looking for datepicker when cell is edited.
Use this editor for datepicker in any cell of Tabulator.JS table.
Pre-requisite.. Refer to bootstrap.js, JQuery files.

var DateEditor = function (cell, value, data) {
    //cell - JQuery object for current cell
    //value - the current value for current cell

    var editor = $("<input class='form-control'  placeholder='MM/DD/YYY' type='text' />");
    
    editor.css({
        "padding": "3px",
        "width": "100%",
        "box-sizing": "border-box",
    })
  
     editor.val(value);
 
    //set focus on the select box when the editor is selected (timeout allows for editor to be added to DOM)
    if (cell.hasClass("tabulator-cell")) {
        setTimeout(function () {
            editor.focus();
        }, 100);
    }
    editor.datepicker();
    editor.on("change", function () {
        var selected = $(this).val();
        cell.trigger("editval", editor.val());
        editor.val(selected);
     
    });

    return editor;
}

And in the tabulator use this

{ title: "From Date", field: "fromdate", width: 120, editable: true, editor: DateEditor },

Thanks,
Ravikanth

**Comment by olifolkerd** [comment]
Hey,

Thanks for leaving the tip. there has also been a solution posted for this already in issue #252 

Thanks for your contribution!
