### ISSUE TITLE
clearHeaderFilter along with setFilter

### ISSUE THREAD

**Issue by ecthelion07** [olifolkerd/tabulator#2890]
Hi team,

I was having a look at what's going on underneath for the following situation:

calling clearHeaderFilter (to undo whatever the user has filtered previously) and then apply a setFilter (so that it's the only one applied at the time) and noticed the following:

![image](https://user-images.githubusercontent.com/4159643/87325287-29923480-c529-11ea-9a7e-7283773ef550.png)

They are both calling the same methods, i.e filterRefresh. Is there a way to avoid the first set of calls? Perhaps a parameter to avoid rerendering when you know another setFilter call is coming in the next line of code?

Thank you very much.

**Comment by olifolkerd** [comment]
Hey @ecthelion07 

That is correct behaviour, if you clear a filter then the table data must be reset,  and the same goes for setting a filter.

I am slightly confused as to why you are calling both functions there, the ***setFilter*** function will replace all existing filters so there is no need to clear the filters. It is the ***addFilter*** function that adds a new filter to an existing set of filters.

Cheers

Oli :)

**Comment by ecthelion07** [comment]
Hey @olifolkerd,

Thank you for your quick response. I just had setFilter before, as I was expecting the rest of header filters to be cleared.
How ever, the setFilter filter seemed to be applied along with the previous header filters. As soon as I cleared the filters before calling setFilter the behaviour was what I expected.

In case it makes a difference,  we are calling it from react via a table object ref we have.
