### ISSUE TITLE
Wrong function call for Collapse Row section

### ISSUE THREAD

**Issue by ComicShrimp** [olifolkerd/tabulator#2893]
**Website Page**
http://tabulator.info/docs/4.7/tree#component

**Describe the issue**
In **Collapse Row** section, the documentation says `row.treeExpand();`,  when the correct code is `row.treeCollapse();`

**Comment by olifolkerd** [comment]
Hey @ComicShrimp 

Thanks for the headsup, i will get that fixed today.

Cheers

Oli :)
