### ISSUE TITLE
Use Header Filtering with Automatic Column Generation

### ISSUE THREAD

**Issue by PythonPhilipp** [olifolkerd/tabulator#2894]
First of all, I would like to thank you for this great library. It enriches my Vue.js SPA and makes my daily life easier.

*Is your feature request related to a problem? Please describe.**

My application retrieves data from a remote source by using the ajaxURL option. Due to many different tables, approx. 100 different schemas, I set the autoColumns option to true. Unfortunately demand many users to have a Header Filterung for each column. I only found the solution to set the headerFilter parameter in the column definition object for that column, but not for every column automatically.

**Describe the solution you'd like**

I would appreciate an option for setting a Header Filterung for all columns in combination with the autoColumns option.

**Describe alternatives you've considered**

If this option ist not possible to implement, I would be delighted to know how to add static definitions to the columns definition object in combination with the autoColumns option to reach all columns.

**Comment by PythonPhilipp** [comment]
The issue could be closed. I found a way to solve my request:

Instead of using the autoColumns option, I generate an options object at the python api and consume this object by using an GET - XMLHttpRequest.

Due to the setColumns function it is possible set the object from the api to this tabulator instance.

**Comment by PythonPhilipp** [comment]
Greate library :-)

**Comment by olifolkerd** [comment]
Hey @PythonPhilipp 

Thanks for getting in touch, and for your kind words about Tabulator.

I have had numerous feature requests around setting column definition options for autotable columns.

I will be looking into a new approach to make this easier for the 4.8 release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @PythonPhilipp 

I have just pushed an update to the 4.8 branch to help with this. *(which should be released next weekend)

There is a new ***autoColumnsDefinitions*** option that will let you manipulate the generated column definitions before they are passed into the table.

```js
var table = new Tabulator("#example-table", {
    data:tabledata,
    autoColumns:true,
    autoColumnsDefinitions:function(definitions){
        //definitions - array of column definition objects

        definitions.forEach((column) => {
            column.headerFilter = true; // add header filter to every column
        });

        return definitions;
    },
});
```

Cheers

Oli :)

**Comment by PythonPhilipp** [comment]
Hey @olifolkerd 

the new **autoColumnsDefinitions** option will decrease the complexity of my stack. I am really looking forward to the notification of the new release.

May I could close this part of my python-api and move the ColumnsDefinition-Function where it belongs, directly in the script section of Tabulator instance.

Thank you for considering this issue. I am still new to the open source community, but if there is something I could do. Let me know.

Kind regards Philipp
