### ISSUE TITLE
Add Rows Doesn't Add In Order

### ISSUE THREAD

**Issue by dragmecom** [olifolkerd/tabulator#2898]
**Describe the bug**
Simple iteration of adding rows to a table using 
```
for(i=0;i<=20;i++){
               table.addRow({"id" : i})
}  
```
and having the table with pagination results in correct behavior except for the latest row. Also note this behavior happens with or without the setting addRowPos : "bottom" - so they are not related.

**Tabulator Info**
Latest

**Working Example**
https://jsfiddle.net/fsn1jkwp/2/

👍 ( PS : Glad to seeing you're doing well, been a while since I found a bug keep up the great work! )

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Create any table
2. Create a basic FOR loop with the following :
```
for(i=0;i<=20;i++){
               table.addRow({"id" : i})
}   
```
3. It will add in order until the last row before pagination

**Expected behavior**
Added in order

**Screenshots**
https://ibb.co/b1mT8XK

**Desktop (please complete the following information):**
 Mac Chrome Latest

**Additional context**
Would love to hop on a zoom call one of these days to ask for your perspective on how some of the smart csv softwares are being done out there.

**Comment by olifolkerd** [comment]
Hey @dragmecom 

Sorry to hear you are having trouble. Looking at the JS Fiddle i can see a couple of tweaks you could make to resolve your issues.

There seems to be a height on your table and set a pagination size. when using pagination it is an either/or scenario. if you set the height it will choose the number of rows for the table, if you set the number of rows it will set the table height. By setting both it can cause the table to fight against itself. i the next minor release i will add a console warning if both are detected

It seems to be iteratively calling the ***addRow*** function, this has two issues, firstly it is every inefficient as it will trigger a partial redraw every time it is called, secondly you are not waiting for it to finish before calling it again, it returns a promise that resolves when it has finished redrawing the table, by not using the promise you risk corrupting the table layout. You can actually pass an array of row data into the ***addRow*** which would only redraw the table once, so the correct approach would be to build the array of rows and pass it into the ***addRow*** function.

You also call the ***addRow*** function straight after instantiating the table, if the table was complex this could result in the function being called before the table was finished building, the table has a ***tableBuilt*** callback that can be used to know when the table has been fully initialised.

I would be happy so hop on a call some time, drop me a message to oliver.folkerd@gmail.com and we can set something up.

Cheers

Oli :)
