### ISSUE TITLE
delay for (multi)select column header filters w/ ajaxdata

### ISSUE THREAD

**Issue by jjech** [olifolkerd/tabulator#2899]
This issue is somewhat similar to #2522 but it's for the (multi)'select' header filter type rather than 'input' type.

We are using tabulator with AJAX requests (column header filters) to work with large sets of data. The default behavior when using 'select' column header filters is to an issue an ajax request each time the user selects a value from the column header filter dropdown. This is perfectly fine if the column header filter is not using 'multiselect:true', since only a single value can be selected at any given time. However, if the table is configured with 'multiselect:true' and the user wishes to select more than one value from the dropdown menu to filter on, issuing a new ajax request and having tabulator update with each selection is not ideal. This is because with large sets of data as in our use case, AJAX requests can take a significant time to complete, so the user ends up waiting multiple times as the table issues a new request and updates once for each selected value.

**Describe the solution you'd like**
We were previously using our own custom header filter that allowed "ctrl" click to select multiple values before the ajax data request was issued. Interestingly, ctrl-click still works with the new native tabulator (multi)select dropdown as well; however tabulator ends up issuing a request for every click/selected value rather than combining the selections into one request. If it's possible to hold off on sending an ajax request for (multi)'select' header filters while the ctrl key is being depressed and then send a single combined request with all selected values when the ctrl key is released, that would be the ideal solution.

**Describe alternatives you've considered**
Another solution would be to update tabulator such that headerFilterDelay also applies to 'select' type column header filters. If headerFilterDelay is configured, then selecting a value in the column header filter would not issue the ajax request until after the headerFilterDelay has been reached. Alternatively, it might make sense to add a new configurable selectHeaderFilterDelay, since selecting values is a different type of action from the user than typing values, and it may be desirable to have shorter/longer delays for one type of action vs the other.

**Comment by olifolkerd** [comment]
Hey @jjech 

I can certainly see your usage case there.

In that case i think thee best option would be to used the existing ***headerFilterLiveFilter*** property and make the header filter aware of it so it only triggers the success function if the focus is blurred on the editor.

If that makes sens i can add that on the roadmap for the next release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
I have just pushed updates to the 5.2 branch that replaces the ***select*** and ***autocomplete*** editors with the new ***list*** editor, which will resolve this issue.

It will be included in the 5.2 release later this month.

Cheers

Oli :)
