### ISSUE TITLE
Create cascading dropdowns

### ISSUE THREAD

**Issue by ravikanth143** [olifolkerd/tabulator#290]
I need cascading dropdown in cells. So when i edit 2nd cell in table which has dropdown, this must have values depending on value of first cell. When first cell edited then 2nd cell value should reset to empty.
How this can be done.

In other words, i need to get value of cell 1 when i am editing cell 2.

Thanks,
Ravi

**Comment by olifolkerd** [comment]
Hey Ravi,

Thanks for getting in touch,

just so i am clear, the contents of the second drop down wont be dependant on the value of the first, only its current value?

Is that correct?

Cheers

Oli

**Comment by olifolkerd** [comment]
closed due to inactivity

**Comment by PDTDevs** [comment]
Hi oli, 
Above is related to mine, iam have a editable tabulator in which i hav 2 column with valuesLookup : data editor is list, based on first list selection, need to update the second list values.
Hope its clear.

**Comment by Kiran194747** [comment]
Hi oli,
Is it possible to implement cascading filters in Tabulator using predefined functions?
