### ISSUE TITLE
conflicting persistent read/write functions

### ISSUE THREAD

**Issue by pythonBerg** [olifolkerd/tabulator#2901]
No codepen so ignore as you wish. It appears that the persistenceReadFunc and persistentWriteFunc are conflicting with each other. I am using each to read/write table preferences to db. When rendering the table, persistenceReadFunc is first called, followed by persistentWriteFunc several times. Somehow the data in read is being ignored by write.

I did work around by setting some flags and externalizing setColumnLayout until table is fully rendered. Just FYI...

**Comment by olifolkerd** [comment]
Hey @pythonBerg 

It is normal for the wite function to be called during the setup process after the initial read.

It is almost impossible to get to the bottom of the issue without understanding what you are trying to read and write as different parts of the table are persisted in different ways.

Could you mockup a JS fiddle where the functions persist to local storage, that way you could do a demo that would help us get to the bottom of the issue.

Cheers

Oli :)
