### ISSUE TITLE
Custom filter function not working for Global Search

### ISSUE THREAD

**Issue by AyazBelim** [olifolkerd/tabulator#2902]
https://github.com/olifolkerd/tabulator/issues/505 I  tried with solution but not working to my tabulator.
i have central textbox in change event of this i'm calling this function.
this is pretty straight forward. it supposed to work.
![image](https://user-images.githubusercontent.com/34475248/88258524-f6486600-ccdd-11ea-8e70-a7704bed8a8f.png)

**Comment by Sachin4dotnet** [comment]
Hello Ayaz,

You are returning the `match` from the function which might be causing the issue. As per the documentation, the function must return boolean value.

Hope that helps!!

**Comment by AyazBelim** [comment]
Yeah that's the problem . thanks @Sachin4dotnet

**Comment by ppKrauss** [comment]
Hi, some news?  https://stackoverflow.com/q/63607444/287948
