### ISSUE TITLE
Cannot empty filter when click the cross for autocomplete / mutliselect heraderfilter

### ISSUE THREAD

**Issue by machanrk** [olifolkerd/tabulator#2903]
When using mutilselect /  autocolplete heradfilter, it cannot show all the data when I click the cross inside the input box, it still remain the last filter option.

Also, the mutilselect dropdown cannot show again after I clicked the cross

**Comment by olifolkerd** [comment]
Hey @machanrk 

Please use the [Bug Issue Template](https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Possible+Bug&template=bug_report.md&title=) when reporting a bug. There is a lot of information we need to know to help you out and the template will prompt you for the right info.

We will need to see a working JS Fiddle or Code Pen that demonstrates the issue and will need to know what browser you are experiencing the issue on.

Cheers

Oli :)
