### ISSUE TITLE
CSV custom delimiter not used for header

### ISSUE THREAD

**Issue by AsharLohmar** [olifolkerd/tabulator#2907]
As said in the title, calling 
```table.download("csv", "data.csv", {delimiter:";"});```
produces a file where the values in the rows are correctly wrapped with quotes and separated by the specified delimiter, but the header has no wrapping and uses "," as a separator, is probably just a "toString" of the array and the comma comes from my regional settings.

https://jsfiddle.net/zr0n7hev/
Version: 4.7 (downloaded yesterday 27/07/2020)

**Comment by darshanrampatel** [comment]
Yes, you can see this in `download.js`:

For the lack of quoting:
https://github.com/olifolkerd/tabulator/blob/673498817be34f9e229901de950959aedf819019/src/js/modules/download.js#L133

And for the lack of delimiter:
https://github.com/olifolkerd/tabulator/blob/673498817be34f9e229901de950959aedf819019/src/js/modules/download.js#L164

**Comment by AsharLohmar** [comment]
Exactly, the source of the problem is there. 
I think that those values should be passed through the same "mincer" as the "cell values".

**Comment by olifolkerd** [comment]
Hey @AsharLohmar 

Thanks for the headsup,

I will get that fixed in the next patch release, or feel free to submit a PR.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @AsharLohmar 

I have pushed a fix for this to the 4.8 branch which will be released later this month.

Cheers

Oli :)
