### ISSUE TITLE
Frozen columns with layout fitDataFill cause a horizontal scrollbar to appear

### ISSUE THREAD

**Issue by darshanrampatel** [olifolkerd/tabulator#2908]
**Describe the bug**
When adding a frozen column to a table that is set as `layout: "fitDataFill"`, a horizontal scrollbar appears, even though the table width is small enough to fit the screen.

**Tabulator Info**
- Which version of Tabulator are you using? 4.7.2

**Working Example**
https://jsfiddle.net/cwbL60vj/1/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://jsfiddle.net/cwbL60vj/1/
2. See error

**Expected behavior**
A horizontal scrollbar should not appear

**Screenshots**
![image](https://user-images.githubusercontent.com/14162899/88681708-c4723d80-d0e9-11ea-8018-c5ec1a062e6a.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version 83.0.4103.116 (Official Build) (64-bit)

**Additional context**
- Changing the frozen column to false hides the horizontal scrollbar, as shown in the below screenshot:
![image](https://user-images.githubusercontent.com/14162899/88681604-a6a4d880-d0e9-11ea-82b4-31722302fcda.png)

- Example code:
```js
 var tabledata = [
 	{id:1, name:"Oli Bob", age:"12", col:"red", dob:""},
 	{id:2, name:"Mary May", age:"1", col:"blue", dob:"14/05/1982"},
 	{id:3, name:"Christine Lobowski", age:"42", col:"green", dob:"22/05/1982"},
 	{id:4, name:"Brendon Philips", age:"125", col:"orange", dob:"01/08/1980"},
 	{id:5, name:"Margret Marmajuke", age:"16", col:"yellow", dob:"31/01/1999", details: "test"},
 ];

var table = new Tabulator("#example-table", {
    layout:"fitDataFill",
    height:"311px",
    data:tabledata, //assign data to table
    columns:[
    {title:"Name", field:"name"},
    {title:"Age", field:"age"},
    {title:"DOB", field:"dob"},    
    {title:"Favourite Color", field:"col"},
    {title: "Details", frozen: true, field: "details"},
    ],
});
```

**Comment by olifolkerd** [comment]
Hey @darshanrampatel 

Thanks for pointing that out, it definitly looks like the frozen column module and the layout mode are fighting against each other there. I will add that to the patch list.

Cheers

Oli :)

**Comment by manuelmazzuola** [comment]
any updates about this issue?

**Comment by olifolkerd** [comment]
Hey All,

I have just pushed a fix for this to the master branch and will include it in the next patch release.

Cheers

Oli :)
