### ISSUE TITLE
IE 11 setPageSize - JS Error

### ISSUE THREAD

**Issue by fhariano** [olifolkerd/tabulator#291]
Number.isInteger is not supported in Internet Explorer and thus when using ObjectLoader there is an error.

**Comment by olifolkerd** [comment]
Hey,

Thanks for letting me know. The great new is that Tabulator 3.0 will be coming out this month, and it no longer uses that function so all will be good shortly.

Cheers

Oli

**Comment by fhariano** [comment]
Ok, thanks!
