### ISSUE TITLE
Header filter with search and multi select

### ISSUE THREAD

**Issue by harshald28** [olifolkerd/tabulator#2912]
*Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by olifolkerd** [comment]
Hey @harshald28 

You seem to have only filled in the title of this issue.

If you ware looking for a new feature, you will need to fill in a full issue template explaining what the feature is, how it will work and why you think it is necessary.

Cheers

Oli :)
