### ISSUE TITLE
add a new row feature

### ISSUE THREAD

**Issue by julientype** [olifolkerd/tabulator#2916]
i'm new but i can explain......

When adding new record i would like it done in the tfoot  of the table without effecting the current array..... 
a clone array entry with a save button cancel button.....
it simply floats in the tfoot rather then at end of the tbody.....
i can then add run check operation on 1 complete recorder to check if the database will enter it.... save cancel....
when the add entry is a clone its not committed to the static  array copy of the tbody   retrieved off the server... no messy clean up this way....

It becomes part of the record navigation in the tfoot add and cancel ...update is the tbody the record has been committed at the server all ready..

like even with your many relation join tables  you have a tfoot for each table would simply popup a clone array  to be process would really be nice to see....

**Comment by olifolkerd** [comment]
Hey @julientype 

This seems like a bit of a niche usage case, 

Im not sure if in that scenario you wouldn't be better served managing that with either a form outside the table or by observing when focus is lost on the table and then determining if the row is new or not bu an id column that is only set when the data is saved to the server.

Im afraid the proposed feature is to heavily tied to your specific usage case and would not be necessary for the majority of Tabulator users. 

For that reason i would not be looking to add it to the table, but feel free to add the functionality to your own fork.

Cheers

Oli :)

**Comment by julientype** [comment]
Im new to your code.......
 i was looking for good data binding grid without having to build one..... 
Its seems i have to......
You can see in the image how the footer can act for record importing....
Only the last entry gets pined up...... 
When i delete the last footer row the next inline should pop up.....
They all get appended  at the bottom.....
Import css entry.... and commit them to the data array model..... 
 for sub joint relation  entry for nested transactions...... 
All the scroll bars work as its template.....
40kb max..... 20kb for the binding dom logic and 20kb for the component

![image](https://user-images.githubusercontent.com/23644389/89235816-f0476480-d5bc-11ea-8373-d555c103cf71.png)

**Comment by olifolkerd** [comment]
Hey @julientype 

I understand the functionality you are looking for, i just consider it to be a bit of an edge case usage scenario and a bit clunky from a user experience point of view.

It is not a matter of it taking up a lot of code, it is that I don't want to bloat Tabulator with functionality that i don't think adds value to the library. I get 100's of feature requests each year and if i added them all the Tabulator would be rendererd unusable under the sheer weight of configuration options for rarely used features.

Im sorry this isnt the answer you were hoping for but i will not be looking to add this feature to Tabulator

The closest available option to your usage case is to use the **addRow*** function to add a row to the bottom of the table list:

```js
table.addRow({name:"Billy Bob", age:"12", gender:"male", height:1}, false);
```

Cheers

Oli :)

**Comment by julientype** [comment]
Component as AN ISOLATE DOM
prototypess SERVER 
MAIN OBJECT <A VIEW
append child< element object .prototypes
 A CHILD  ELEMENT WITH prototype functions 
All DONE WITH Object prototypes reference
COMPONENT CREATED  
i don do things like you  do...
object created for you to play with

**Comment by julientype** [comment]
you should not use prototype  in code  unless you  know how to use it
var a =object prototype
object prototype is a client server object with nested objects with nested objects

**Comment by olifolkerd** [comment]
I am unsure what you are trying to say there, the structure of your sentence is rather broken.

With all due respect, please don't come on to this issues list and talk to me with such offensive language. I know what i am doing with JavaScript and prototypical object generation, and it works efficiently. Everyone has their own coding style and there are pros and cons to each approach, without understanding fully why someone has take an approach you cannot pass such broad sweeping comments.

If you believe there are areas where efficiency improvements can be made then i am open to suggestions, but please raise that as a separate issue as it is unrelated to this request and clearly state your case with a working example.

Cheers

Oli :)
