### ISSUE TITLE
Bug: Duplicate columns while enabling persistence with custom header sort toggler and redraw

### ISSUE THREAD

**Issue by The-Bright-Lord** [olifolkerd/tabulator#2917]
**Description:**
There seems to be a possible bug when using the persistence module with header sort and table.redraw() functions together
After a sort toggle, when the page is reloaded, each column is duplicated.

**Tabulator Info:**
Tabulator 4.7.2

**Working Example**
Code pen link: https://codepen.io/the-bright-lord/pen/OJMKaBo

**Steps to reproduce:**

1. Clicking on the search button will toggle `headerFilters` for the columns
2. Clicking on it again will disable the header filters.
3. Clicking on Redraw button will recreate the table.
4. Columns in the table are duplicated.
5. This can be verified by entering `Object.entries(localStorage)` in the console and checking the table-columns entries.

### Since this uses codepen's localStorage. Please run 
`localStorage['tabulator-example-table-columns'] = ""` 
### after testing to reset the table to  its original state.

**Possible cause of the Issue:**

In the function `toggleHeaderFilter`, if the line `table.redraw(true);` is removed, the issue does not occur.
what is the relationship between the redraw call and duplicate columns being stored in localStorage

**Expected behavior**
There should not be any duplication of the columns.

**Environment:**
 - OS: Windows
 - Browser:  Issue reproduced on Chrome, Firefox
 - Version: Latest available

**Comment by olifolkerd** [comment]
Hey @The-Bright-Lord 

This is because you have persistence enabled on multiple tables on the same page, but you haven't set an id on the table elements  or the ***persistenceID*** option on the tables to differentiate them from one another, so the persistence data for each table is overwriting the other.

```js
var table = new Tabulator("#example-table", {
    persistenceID:"example1", //id string, can only be numbers, letters, hyphens and underscores.
    persistentLayout:true, //Enable column layout persistence
});
```

The [Persistence Documentation](http://tabulator.info/docs/4.7/persist#id) explains in more detail how to use this feature.

Cheers

Oli :)

**Comment by The-Bright-Lord** [comment]
@olifolkerd 

Yes I get that, but now please see the updated codepen. I have removed the redraw function. There is essentially only one call to `Tabulator()` in the entire page.

Now, if you follow the same procedure, select the search option and then, reload the page. The issue still occurs.

Why is that then ?

Btw, never found a insanely well documented library like this. !! Hats off
