### ISSUE TITLE
Use of bottomCalc in a small window gives TypeError: this.botRow.getElement is not a function

### ISSUE THREAD

**Issue by ndg63276** [olifolkerd/tabulator#2918]
**Describe the bug**
If you use a bottomCalc, and the browser window is narrow enough, an error occurs saying that "this.botRow.getElement is not a function".

**Tabulator Info**
- 4.7.2

**Working Example**
https://jsfiddle.net/qL78nbgy/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://jsfiddle.net/qL78nbgy/
2. Narrow your browser window to <1000px
3. Press Run
4. Error in jsfiddle console of "Script Error". See browser dev console for full error message.

**Expected behavior**
Should display the table with one column of progress bars (all empty) and 4 columns of ticks.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 84.0

**Smartphone (please complete the following information):**
N/A

**Additional context**
Not sure if my progress bar formatting / mutating is causing any problems. Have tried to strip out as much as possible.

**Comment by olifolkerd** [comment]
Hey @ndg63276 

Thanks for letting me know, i have pushed a fix to the 4.8 branch which will be released later this month.

Cheers

Oli :)
