### ISSUE TITLE
Customize the group header

### ISSUE THREAD

**Issue by nghuuphuoc** [olifolkerd/tabulator#2919]
Currently, the `groupHeader` option must return a `String` that will be displayed as the header of group.

```javascript
groupHeader: function(value, count, data, group) {
  return 'header';
}
```

We have a use case that the header is more complex than that. We want to add more elements to the header.
These addition elements can interact with the rows in the group (that can be retrieved via `group`).

It's great if the `groupHeader` can return a HTML element:

```javascript
groupHeader: function(value, count, data, group) {
  const ele = document.createElement('div');

  group.getElement().appendChild(div);

  // Build the logics around `ele` ...

  return ele;
}
```

**Comment by olifolkerd** [comment]
Hey @nghuuphuoc 

Thanks for the suggestion, that is a great idea and should be easy to acheive.

I will add it to the roadmap.

Cheers

Oli :)

**Comment by LilDevil** [comment]
@nghuuphuoc, the groupHeader function can return an html string. Just `return ele.outerHTML` of the element you've created. This should work as long as you're not attaching event handlers to your element.

**Comment by olifolkerd** [comment]
@LilDevil 

Thanks for the suggestion, but the problem with returning a string is that if you want to bind event listeners they will be lost in the string conversion, @nghuuphuoc has a valid suggestion with making it accept returned nodes.

It would also make the function more consistent with the other formatting functions.

Oli :)

**Comment by olifolkerd** [comment]
Hey @nghuuphuoc 

Looking into the code, the ***groupHeader*** function will already accept the returning of a DOM node so your code should look like this, it will then append this to the header

```js
groupHeader: function(value, count, data, group) {
  const ele = document.createElement('div');
  // Build the logics around `ele` ...
  return ele;
}
```

I will make sure the docs reflect this.

Cheers

Oli
