### ISSUE TITLE
Never show background, last column expands instead

### ISSUE THREAD

**Issue by michaelbushe** [olifolkerd/tabulator#292]
Showing the background of the table when columns don't take up the full width of the table is a shocking user experience (Swing tables suffered from the same effect back in the day).  The gray color takes up space without providing value to the user and it's unclear to the user what the extra space is for.  Even when matching the background color of the rows (say, white/white), the result is surprising because the row lines do not extend all the way to the right.

Instead, the table should always extend the last column all the way to the right - on first render and even after any column resizing (and resizing the last column by dragging from the right to the left should be disabled, or a new virtual empty column with row lines should be added).  Almost all apps do this - Excel, Sheets, tax apps, etc.  Since 3.0 is coming this may be a good time to change the default.

Though this effect can be achieved when the table is first rendered by using fitToData and then setting the width of all columns except the rightmost column, the user can still create the grey space by resizing any column by dragging to the left.  

Having this as the new default is preferred, but lacking that, a table option (neverShowTableBackground or alwaysExpandLastColumn) would be good enough.  

Is there a way to achieve this effect with the current release?  There is no listener for ColumnResized, which would be a good place to start.

Thanks for an awesome table, this is hard stuff.

**Comment by olifolkerd** [comment]
Hey Michael,

You can use the ***fitColumns*** property to ensure that all columns fill the available space, this distributes the left over space amongst all the columns which is much more visually appealing than a single column set all the way to the right.

Failing that a css-tweak to set the min with of the ***.tabulator-table*** and ***.tabulator-row*** classes to 100% should resolve your issue.

I like the idea of the columnResized callback. i will add that to the to do list.

Cheers

Oli

**Comment by michaelbushe** [comment]
Hi Oli,

Thank you, I'll try the css trick.  

FitColumns shows even columns, which is nice, especially on small devices.  The app I am working on is similar to apps I commonly work on in sports where there is a name field that is wide, but then many statistical fields which are narrow.  It reduces eye scanning for the user to keep these numbers close to each other (like a baseball box score, if I can be so regional), rather than spreading them out across the screens, especially on wide screens.

It's too bad fitColumns ignores the width set on the columns, otherwise it could act like <table>'s "*" percentage width where you can distribute the width among some columns only instead of across all columns. I guess I'll get that with the css tweak, I'll update again after I try it.

Thanks Again!

Michael

**Comment by michaelbushe** [comment]
I think we need a declarative way of getting this behavior.

Changing the css as suggested seemed to have no effect, except adding the white background which makes it much less offensive..  I tried adding "min-width: 100% !important;" to  .tabulator-table and .tabulator-row, but detected no behavioral change.

A poor workaround is:
      let resizeHandles = tabulator.find('div.tabulator-handle');
      resizeHandles.on('click.' + EVENT_NAMESPACES.COLUMN_RESIZE, function () {
        tabulator.tabulator("redraw");
      });

It sort of works, but it is very quirky.  The rows don't extend during the during the drag (minor) and after the drag the table jumps.  Better than showing gray, but not professional looking.  

Worse is that sometimes the last column expands, as desired, but sometimes other columns expand instead.  If I have 4 columns, I can make the first one smaller, the second one expands instead of the last one, sometimes.  Then I can make the second smaller and no columns expand.  Then make the third smaller and the fourth expands (finally, the proper behavior).  After this, if I make any of the first three columns larger, the table extends, even to the point of extending off the page without a horizontal scrollbar appearing.  Stretching a column again, even making it smaller, make the last column disappear.

Worst is that sometimes the last column disappears.  I think the way it disappears is if I make the last column smaller (drag from the rightmost handle to the left), then make the first columns larger (drag it's right handle to the right).

Do you have another workaround idea?  Would you consider adding the desired behavior as a configuration option?  Thanks!

**Comment by olifolkerd** [comment]
@michaelbushe you will be happy to hear that in today's 3.3 release there is a new param***fitDataFill*** layout mode:
```js
$("#example-table").tabulator({
	layout:"fitDataFill",
});
```

Full details can be found in the new [Table Layout Documentation](http://tabulator.info/docs/3.3#layout).

Cheers,

Oli :)
