### ISSUE TITLE
Progressive loading data using Ajax

### ISSUE THREAD

**Issue by davebaldwin** [olifolkerd/tabulator#2920]
http://tabulator.info/docs/4.7/data

Example code for 'Scroll Mode' missing comment symbols

var table = new Tabulator("#example-table", {
    ajaxURL:"http://www.getmydata.com/now", //ajax URL
    ajaxProgressiveLoad:"scroll", enable progressive loading.   <<<<<<<<<<<<<<< needs //
    ajaxProgressiveLoadScrollMargin:300 //triger next ajax load when scroll bar is 300px or less from the bottom of the table.
});

**Comment by olifolkerd** [comment]
Hey @davebaldwin 

Thanks for the headsup, i will get that fixed on the next site update

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @davebaldwin 

I have fixed it my end and will push the changes live with the 4.8 site update later this month

Cheers

Oli :)
