### ISSUE TITLE
getRows('active') on a Filtered Tree View

### ISSUE THREAD

**Issue by jmeberst** [olifolkerd/tabulator#2922]
**Describe the bug**
I'm trying to limit my selections to only the filtered data that is visible, but in 4.7.2 when I call getRows('active') on my Tree View it only returns the parents, which was the behavior from Tabulator 4.1. I believe getRows('active') should include the filtered children as well as that is the behavior of 4.7.2 visually.

**Tabulator Info**
- Which version of Tabulator are you using?
4.7.2

**Working Example**
[https://codesandbox.io/s/tabulator-tables-sandbox-d8761?file=/src/index.js](https://codesandbox.io/s/tabulator-tables-sandbox-d8761?file=/src/index.js)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Enter a filter value of "Test2" in the name column, this will return 3 parent rows visually.
2. Two of the parent rows will have a single child.
3. Click the get filtered rows button.
4. Only the three parent rows will be logged to the console, not the 5 rows visible on the screen.

**Expected behavior**
the getRows('active') function should have the same behavior as the table, and return the 5 visible rows.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version 84

**Comment by jmeberst** [comment]
Here's a really inefficient work around. It gets set on the dataFiltered event. 

```
private setDataFiltered(filters, rows) {
        if (rows && rows.length > 0) {

            //Check if Row 0 is a parent
            if (rows[0].getTreeChildren().length > 0) {
                //clear the filteredRows on a new parent filter
                this.filteredRows = [];

                this.filteredRows = rows;

                //To keep from getting strange selects clear the selections on a new parent filter
                if (this.tabulatorTable) {
                    this.tabulatorTable.deselectRow();
                }
            }
            else {
                //This will add duplicate child rows, but that's okay because it's still filtered duplicates
                if (this.filteredRows) {
                    let newRows = this.filteredRows.concat(rows);
                    this.filteredRows = newRows;
                }
            }
        }


        console.log("Filtered Rows", this.filteredRows);
    }`

**Comment by olifolkerd** [comment]
Hey @jmeberst 

This is the correct and intended behaviour. All functions that access active row data only return the base rows. you can then access the child rows if needed using the ***getTreeChildren*** function on the rows.

This ensures that the parent child relationship is preserved in the output data.

Cheers

Oli :)

**Comment by jmeberst** [comment]
@olifolkerd I need the filtered tree children though, and getTreeChildren() returns all the rows children. Could this be a feature request for .getTreeChildren('active')?
