### ISSUE TITLE
Option to start viewing table scrolled all the way to the right

### ISSUE THREAD

**Issue by myeh98** [olifolkerd/tabulator#2923]
*Is your feature request related to a problem? Please describe.**
This might be a niche use case. However, I have several tables that are incredibly long column wise. On one such table, I want to preserve the order (I cannot just flip the columns) but want to see the right most column first instead of the default leftmost column.

**Describe the solution you'd like**
I would love it if there were an option in the tabulator documentation to enable this.

**Describe alternatives you've considered**
I've tried using the scroll to feature on load but this doesn't seem to work. (Possibly because I am actually using the React Tabulator library build on top of tabulator).

**Additional context**
For clarity, I have a table where the columns are dates in chronological order and I want to start at the current date (furthest to the right). But, I still want to preserve order.

**Comment by olifolkerd** [comment]
Hey @myeh98 

You can already do this yourself using a combination of features.

If you use the ***scrollToColumn*** function with the field name of the right most column, it will scroll to it.

if you put this inside the ***tableBuilt*** it will be called once the table has been fully loaded.

```js
var table = new Tabulator("#example-table", {
    tableBuilt:function(){
        table.scrollToColumn("last");
    },
});
```
I hope that helps

Cheers

Oli :)
