### ISSUE TITLE
PDF download don't show group headers for selected row range

### ISSUE THREAD

**Issue by Tschav** [olifolkerd/tabulator#2926]
**Describe the bug**
Grouping headers don't show in downloaded PDF if downloadRowRange is set to selected.

**Tabulator Info**
- Tabulator 4.7.2

**Working Example**
https://jsfiddle.net/Tschav/u7g0bzo4/29/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Select any number of columns
2. Click on the "PDF" button in the top
3. Download PDF or open in browser
4. Grouping Headers wont show in the downloaded PDF

**Expected behavior**
I expected the PDF to show the grouping headers of the selected Rows in the file. So in the example if you select some rows from the groupe "Male" that the header also would be displayed in the downloaded file.

**Screenshots**
![comparePdfToTable](https://user-images.githubusercontent.com/14344459/89709990-b5a84800-d97f-11ea-94d3-08ddc43efc0e.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 79.0

**Comment by olifolkerd** [comment]
@Tschav 

This is correct behavior when you are using the ***selected*** downloadRowRange option, with that option selected only the selected rows are included in the output, no other table formatting is includded.

Cheers

Oli :)
