### ISSUE TITLE
Custom sort indicator

### ISSUE THREAD

**Issue by JimSmithJr** [olifolkerd/tabulator#2927]
Oli,

As always, I am grateful for such a complete solution.  I can attest to the fact that even the commercial data grid do not provide the features you provide in Tabulator.  Thank you!!

With that said, I do have one request - and I do apologize if I have missed it in the documentation.  I have been searching for quite some time and can't find even solutions accomplished by other developers.  I am answering your questions below directly to make this easier to read as I'm sure your time is incredibly limited.

*Is your feature request related to a problem? Please describe.** No, it is not.  

**Describe the solution you'd like**
Custom sort indicator.  See screenshot for reference.  I've manipulated the css in the code and have been able to alter the appearance, however I would like to be able to change the sort indicator from the styled cell to an icon - such as the typical arrows found in FontAwesome.  I am working on my own personalized set of icons that I've tweaked to make my product less generic and more to my companies theme.  If I missed the how to in the documentation I sincerely apologize and thank you for your time and assistance.

**Describe alternatives you've considered**
Modifying the theme directly.

**Additional context**
The below is a screen shot to provide some context and clarity on the request.
![image](https://user-images.githubusercontent.com/34613151/89735048-c2837500-da2d-11ea-8a2b-978a2e4f3a23.png)

Jim Smith

**Comment by olifolkerd** [comment]
Hey @olifolkerd 

Thanks for your kind words, it is always great to hear that Tabulator is appreciated.

I think that is a great idea, thinking about it, it is the only icon in the whole of the table that is not directly customisable.

I will add this to the roadmap for the next release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @JimSmithJr

I have just pushed a commit with this functionality to the 4.8 branch. Which should be released in a couple of weeks.

You will then be able to set the sort icon using the new ***headerSortElement*** setup option.

Cheers

Oli :)

**Comment by JimSmithJr** [comment]
Oli,

This is great, thanks so much.  I'll be sure to provide some feedback on the functionality.

Jim
________________________________
