### ISSUE TITLE
Change groupValues after table creation

### ISSUE THREAD

**Issue by pgodw4** [olifolkerd/tabulator#2928]
When creating a tabulator table one can set the groupBy options using something like:

```
groupBy: ["CapType"],
groupValues: [["Large", "Medium", "Small", "Micro"]],
```

However there doesn't seem to be a similar method to change the groupValues after the table has already been created, like you can using `table.setGroupBy("")`

This would be super useful for so many reasons. Firstly you can then order the display of groups however you want and not be limited to it occurring in the order of the rows. Secondly you can assign custom names to groups without needing to use the underlying raw data. For example I want to group by rating, where the rating is stored as an integer 0-5 but displayed using stars. Currently if I apply `table.setgroupBy("Rating")` after the table is created, the group headings are literally the numeral 1 through 5, and NULL. While it is legible, it isn't exactly pretty.

Thank-you for your consideration.

**Comment by olifolkerd** [comment]
Hey @pgodw4 


For your proposed usage case you could simply us a groupHeader formatter:
```js
var table = new Tabulator("#example-table", {
    groupHeader: function(value, count, data, group){
        return value + "<span style='color:#d00; margin-left:10px;'>(" + count + " item)</span>";
    },
});
```

Checkout the [Grouping Documentation](http://tabulator.info/docs/4.7/group#setup-headers) for more details

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hi have pushed an update to the 4.8 brnach that has added the ***setGroupValues*** function to allow changing of values after the table has been initialized.

Cheers

Oli :)

**Comment by pgodw4** [comment]
Hi Oli

Thanks so much, I appreciate you taking the time to add this feature.

**Comment by maku** [comment]
@olifolkerd I set "groupBy" as a function, how can I change this after creation of the tabulator?
