### ISSUE TITLE
POSTing JSON data

### ISSUE THREAD

**Issue by leonardorame** [olifolkerd/tabulator#293]
Hi Oli, me again with a new feature request.

In this complex case I need to POST a JSON (or Javascript) object like this:

    var ajaxURL = "/cgi-bin/worklisttest.bf/cfind/";
    var ajaxParams =
        {
          "peer": "127.0.0.1",
          "port": 10400,
          "aet": "TEST",
          "aec": "WORKLIST",
          "queryType": "WORKLIST",
          "keys": [
            "0008,0052=STUDY",
            "0008,0020",
            "0008,0050",
            "0008,0061",
            "0010,0020",
            "0010,0010",
            "0020,000D"
          ]
        };
    table.tabulator("setData", ajaxURL, ajaxParams);

But, when I call this my `ajaxParams` are parsed and converted to an URL encoded string. Is there a way to send the javascript object as is?.

**Comment by olifolkerd** [comment]
If you need to pass a more complex object in the ajax request the you need to use the third argument in the ***setData*** function, which allows full configuration of the request object:

```js
var ajaxURL = "/cgi-bin/worklisttest.bf/cfind/";
var ajaxConfig ={
    type: "POST",
    contentType: "application/json; charset=utf-8",
    data: JSON.stringify({
      "peer": "127.0.0.1",
      "port": 10400,
      "aet": "TEST",
      "aec": "WORKLIST",
      "queryType": "WORKLIST",
      "keys": [
        "0008,0052=STUDY",
        "0008,0020",
        "0008,0050",
        "0008,0061",
        "0010,0020",
        "0010,0010",
        "0020,000D"
      ]
    }),
}
table.tabulator("setData", ajaxURL, null, ajaxConfig);
```

Full details of this feature can be found [here](http://olifolkerd.github.io/tabulator/docs/#ajax) in the advanced configuration section.

Let me know if that is what you are after.

Cheers

Oli

**Comment by leonardorame** [comment]
Thanks for the answer setting that object worked, but only after removing `tabulator.pagination = "remote"` in the tabulator config.

I think the need to remove the pagination option should be **stressed** in the ajax documentation.

**Comment by olifolkerd** [comment]
Hey,

You will be happy to hear that version 3.0 is now in beta release, it has improved ajax and pagination features.

Head over to http://olifolkerd.github.io/tabulator/news/ to see the latest features!

Cheers

Oli
