### ISSUE TITLE
Only first filtered page downloaded by default and also with downloadRowRange ="active" 

### ISSUE THREAD

**Issue by JawadHossain** [olifolkerd/tabulator#2930]
Hi,

I am having an issue where the download option only downloads the page in view by default and also with the "active" row range option. Please take a look at the JS Fiddle.
Tabulator Version used: 4.7.2

https://codepen.io/danny-khoo/pen/bGpbQVo

**Comment by olifolkerd** [comment]
That is the correct behaviour for active data in pagination mode. U need to use "all"

**Comment by JawadHossain** [comment]
Thanks for your reply. Is there an option to download filtered data from all pages?

**Comment by ptr-n** [comment]
Seems like that behaviour changed with recent 4.7 version.

To me this looks like a bug, or at least an inconsistency, as "active" in other contexts seems to apply to **all** filtered rows (independent of paging)

**Comment by olifolkerd** [comment]
in version 4.7 the download module was refactored to use the table export module like all other forms of exporting (printing, downloading, copy pasting etc) so they all function the same way now.

But @ptr-n i do take on board what you say about active rows in other contexts taking account of pagination.

I will review this in the next release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Thinking about it more, in a paginated view, the ***visible*** option provides the data for the current page, so active should return all paginated data.

I have pushed an update to the 4.8 branch to fix this and make the ***active*** option return all pages. It should be released later this month.

Cheers

Oli :)

**Comment by ptr-n** [comment]
Thanks Oli!

And also thanks for this incredibly useful javascript library!
