### ISSUE TITLE
Please add wrap Tabulator into a Panel widget to enable usage in python and data science

### ISSUE THREAD

**Issue by MarcSkovMadsen** [olifolkerd/tabulator#2934]
#### My Pain

I'm a developer data scientist and passionate about helping people create awesome analytics apps using Python and the tools they know and love.

I contribute to [Panel](https://panel.holoviz.org) which is a framework for data apps in Python.

The current data grid is based on SlickGrid. I believe Panel needs some alternatives. 

#### Solution

I've found Tabulator which looks and feels great, has awesome documentation and an api that Python developers and data scientists will understand.

So please wrap Tabulator into a Bokeh/ Panel widget for easy use in Python and data science applications.

**Comment by MarcSkovMadsen** [comment]
FYI. I have already implemented a first **experimental** version. Would just like to share information on the new use case.

Checkout the announcement here https://discourse.holoviz.org/t/awesome-panel-org-change-log/66/37

[<img src="https://mybinder.org/badge_logo.svg" style="height:25px;display:inline;margin:5px">](https://mybinder.org/v2/gh/MarcSkovMadsen/awesome-panel-extensions/master?filepath=examples%2Freference%2Fwidgets%2FTabulator.ipynb) [<img src="https://raw.githubusercontent.com/jupyter/design/master/logos/Badges/nbviewer_badge.svg" style="height:25px;display:inline;margin:5px">](https://nbviewer.jupyter.org/github/MarcSkovMadsen/awesome-panel-extensions/blob/master/examples/reference/widgets/Tabulator.ipynb)

<video style="max-width:100%;max-height:500px;" autoplay controls>

  <source src="https://raw.githubusercontent.com/MarcSkovMadsen/awesome-panel-extensions/master/assets/videos/Tabulator.mp4" type="video/mp4" controls>

    You browser does not support video

</video>

If you like it feel free to like or retweet the announcing tweet Feel free to like or retweet this announcement tweet https://twitter.com/MarcSkovMadsen/status/1295069038490550272?s=20

You may close this one.

**Comment by iursevla** [comment]
@MarcSkovMadsen you can close it yourself if you see fit (right side there's a button for that).

Cheers

**Comment by olifolkerd** [comment]
Hey @MarcSkovMadsen 

Great idea, I would be happy to include a link to it in the documentation if you would like.

Cheers

Oli

**Comment by MarcSkovMadsen** [comment]
A link would be awesome 👍

**Comment by olifolkerd** [comment]
Reopened so I can track adding a website link

**Comment by olifolkerd** [comment]
Hey @MarcSkovMadsen 

Do you have a link to a page that explains the widget you have built and provides instructions, rather than a tweet?

Cheers

Oli :)

**Comment by MarcSkovMadsen** [comment]
Hi @olifolkerd 

I've added it to the awesome-panel-extensions package with docs here https://awesome-panel.readthedocs.io/en/latest/packages/awesome-panel-extensions/index.html#tabulator

![image](https://user-images.githubusercontent.com/42288570/90542812-fe80ad80-e184-11ea-9382-4e8c4dff8af3.png)


But work has already started to include it in Panel. And maybe even into Bokeh one day which is the foundation for a lot of data visualization in Python. The current grid implementation is based on SlickGrid.

I will add a new link here once it's into Panel. Might take everything between 1 week and 6 months :-)

**Comment by olifolkerd** [comment]
Hey @MarcSkovMadsen 

Im just putting the updates to the Tabulator website for the 4.8 release next weekend, and i was wondering if you had any more info i could link to for this?

Cheers

Oli :)

**Comment by MarcSkovMadsen** [comment]
Not at the moment. Thanks for asking.

**Comment by olifolkerd** [comment]
Hey @MarcSkovMadsen 

I have added a link to the widget page to the newly created [Tabulator Ideas Repo](https://github.com/olifolkerd/tabulator-ideas) where developers can show off their work with Tabulator.

Cheers

Oli :)
