### ISSUE TITLE
Layout fitDataStretch with stretching of all columns instead of only last. Alternatively, fitColumns without shrinkage

### ISSUE THREAD

**Issue by imbasimba** [olifolkerd/tabulator#2935]
Dear Oli,

I would love a layout mode, which defaults the column size to fit its content, but if there is extra space available, the extra space is spread among all flexible columns.

Basically fitDataStretch, but spreading the available width among all columns instead of just the last.

Or fitColumns, where columns are never shrunk more than the size of its content.

Cheers,
Henrik Norman

**Comment by olifolkerd** [comment]
Hey @imbasimba,

If you set appropriate minimum widths on the columns in ***fitColumns*** layout mode, it should do what you want, you can also control the ratio of shrinkage using the ***widthShrink*** option


See the [FitColumns Docs](http://tabulator.info/docs/4.7/layout#fittowidth) for more details

Cheers

Oli  :)

**Comment by imbasimba** [comment]
Hi @olifolkerd,

Sure, I could manually determine the minimum width for each column. However, it is a hassle to determine the appropriate minimum width for all types of columns & the code is already in Column.prototype.fitToData.

What I want is to be able to set 'minWidth' to 'fitToData' instead of a pixel value, as the desired pixel value is not constant.

Cheers,
Henrik
