### ISSUE TITLE
How to make the selectall checkbox to select only filtered rows

### ISSUE THREAD

**Issue by YMPrasad** [olifolkerd/tabulator#2936]
Hello Team,

I started using tabulator recently and everything is fine so far except yesterday's observation while performing table level SelectAll  (& DeselectAll) on a filter operated table results. Means doing a table search with below code

 var input;
            input = document.getElementById("filter");

            input.addEventListener("keyup", function () {
                var filters = [];
                var columns = table.getColumns();
                var search = input.value;

                columns.forEach(function (column) {
                    filters.push({
                        field: column.getField(),
                        type: "like",
                        value: search,
                    });
                });

                table.setFilter([filters]);
            });

and then while performing SelectAll checkbox action in the header using below table code

columns: [
                 {
                     formatter: "rowSelection", titleFormatter: "rowSelection", print: false, hozAlign: "center", headerSort: false, cellClick: function (e, cell) {
                         cell.getRow().toggleSelect();
                     }
                 },
getting all records got selected (deselected) instead filtered results in the table.

Can anyone please help me on this.

Thanks,
YMPrasad

**Comment by olifolkerd** [comment]
This is not currently possible without creating a custom header, but i will review this situation for the next release as you make a good point there

Cheers

Oli :)

**Comment by olifolkerd** [comment]
I have just pushed this feature to the 4.8 branch which should be released later this month.

You will then be able to use a new ***rowRange*** option in the ***titleFormatterParams*** object to set the  range to only active rows

```js
var table = new Tabulator("#table", {
    columns:[
        {formatter:"rowSelection", titleFormatter:"rowSelection", titleFormatterParams:{
            rowRange:"active" //only toggle the values of the active filtered rows
        }, hozAlign:"center", headerSort:false},
    ],
});
```

Cheers

Oli :)

**Comment by YMPrasad** [comment]
Thank you so much Oli!
