### ISSUE TITLE
Split Tabulator options by context

### ISSUE THREAD

**Issue by iursevla** [olifolkerd/tabulator#2937]
**Is your feature request related to a problem? Please describe.**
As of now, on our usage of Tabulator we are using 40+ different options for the Tabulator columns definition and global definitions and also created some custom ones (10+) related with our use cases.
For me, what's frustrating, is that all those options aren't split by context. This is, I would split the options passed to Tabulator like they are split in the [options listing](http://tabulator.info/docs/4.7/options) 

**Describe the solution you'd like**
I would like the options to be split by context.

Currently:
```js
new Tabulator(element, {
  columnMinWidth: ...,
  height: ...,
  layout: ...,
 // along with 40 other options
})
```

Goal:
```js
new Tabulator(element, {
  tableConfig: {...},
  columns: {...},
  rows: {...},
  data: {...}
  // etc
})
```

**Describe alternatives you've considered**
Keep it as is.

**What do you guys think?**

**Comment by olifolkerd** [comment]
Hey @iursevla 

Thanks for the suggestion

I have deliberately avoided doing this, as i believe it overly complicates the setup process, simple commenting above groups of settings should group them in what ever way makes sense to you.

A number of the options could fit into several categories and so i dont want to confuse users, nor do i want to end up in a scenario where there are many layers of nesting necessary just to setup the table, if have used libraries that take this approach and it takes you down a rabbit hole where you can be doing 4 levels of nesting to setup even a simple table.

I would consider a table with 40 setup options to be more of an edge case than a standard usage scenario

Cheers

Oli :)
