### ISSUE TITLE
How to make the selectall checkbox to select only filtered rows

### ISSUE THREAD

**Issue by YMPrasad** [olifolkerd/tabulator#2939]
Hello Team,

I started using tabulator recently and everything is fine so far except yesterday's observation while performing table level SelectAll (& DeselectAll) on a filter operated table results. Means doing a table search with below code

var input;
input = document.getElementById("filter");

        input.addEventListener("keyup", function () {
            var filters = [];
            var columns = table.getColumns();
            var search = input.value;

            columns.forEach(function (column) {
                filters.push({
                    field: column.getField(),
                    type: "like",
                    value: search,
                });
            });

            table.setFilter([filters]);
        });
and then while performing SelectAll checkbox action in the header using below table code

columns: [
{
formatter: "rowSelection", titleFormatter: "rowSelection", print: false, hozAlign: "center", headerSort: false, cellClick: function (e, cell) {
cell.getRow().toggleSelect();
}
},
getting all records got selected (deselected) instead filtered results in the table.

Can anyone please help me on this.

Thanks,
YMPrasad

**Comment by olifolkerd** [comment]
Hey @YMPrasad 

Please dont raise duplicate issues, they only make it harder to track questions and responses.

Also please use the issue template when submitting a feature request as it will prompt you for the info we need to help you out.

I have already flagged your first issue as a feature request and have added it to the roadmap for consideration.

Cheers

Oli :)

**Comment by YMPrasad** [comment]
Apologies. 

Thanks for the response. :)
