### ISSUE TITLE
topCalc row in (each) group shows resize cursor, but not resizable

### ISSUE THREAD

**Issue by roxuss** [olifolkerd/tabulator#2941]
**Describe the bug**
On a standard resizable Tabulator with a topCalc row, the topCalc row cannot be used to resize the column, and does not show the resize cursor.

On a groupBy Tabulator that is resizable, the resize cursor shows when hovering over the column divider on a topCalc row within a group, but it is still not able to be used to resize the Column

**Tabulator Info**
4.7.2

**Working Example**
https://jsfiddle.net/kvdyjftL/

**To Reproduce**
1. Hover over column divider in topCalc in Grouped Tabulator. Cursor will change to a horizontal resize cursor, but the column cannot be resized.
2. Hover over the column divider in Grouped Tabulator on any row OTHER than the topCalc row, and the cursor will be changed to a resize cursor, and the column can be resized
3. Hover over column divider in topCalc in UnGrouped Tabulator. Cursor will NOT change to a horizontal resize cursor, AND the column cannot be resized.
4. Hover over the column divider in UnGrouped Tabulator on any row OTHER than the topCalc row, and the cursor will be changed to a resize cursor, and the column can be resized

**Expected behavior**
To be consistent, I would expect the topCalc row in the Grouped Tabulator to not show the resize cursor.
Though if you wish to add the resize functionality to topCalc rows, I would not be opposed ;)

**Desktop (please complete the following information):**
 - OS: Raspbian GNU/Linux 10 (buster)
 - Browser Chrome
 - Version 78.0.3904.108 (Official Build) Built on Raspbian , running on Raspbian 10 (32-bit)

**Comment by olifolkerd** [comment]
Hey @roxuss 

Thanks for the headsup

I have just pushed a fix to the 4.8 branch to remove the erroneous column resize handles. this should be released later this month.

Cheers

Oli :)
