### ISSUE TITLE
accessor function called on topCalc for all columns as long as at least 1 columns has topCalc defined

### ISSUE THREAD

**Issue by roxuss** [olifolkerd/tabulator#2942]
**Describe the bug**
If one column has a topCalc defined, then when using the new accessor functions when exporting data, a column without a topCalc defined will still call the accessor for that column passing 'undefined' as the value to the accessor()

**Tabulator Info**
4.7.3

**Working Example**
https://jsfiddle.net/fo15tajh/1/

**To Reproduce**
Check the browser console. The first 2 console.log() calls detail that 'undefined' was passed to the accessor, and the third call is the topCalc for the 3rd column.

**Expected behavior**
Tabulator should not call the accessor with topCalc values if no topCalc was requested. If NO topCalcs are requested on ANY column, there is no call to the accessor with ANY topCalc values.

**Desktop (please complete the following information):**
 - OS: Raspbian GNU/Linux 10 (buster)
 - Browser Chrome
 - Version 78.0.3904.108 (Official Build) Built on Raspbian , running on Raspbian 10 (32-bit)

**Comment by olifolkerd** [comment]
This is the correct behaviour for the table,

Accessors are called on row data, where each column of the row is parsed in turn and the accessor called on it. calc rows are handled in exactly the same way.

You should just ensure that your accessor function can correctly handle an undefined value.

Cheers

Oli :)

**Comment by roxuss** [comment]
I think you misunderstand. I can handle undefined in the accessor, but I don't know if its an undefined value that is perfectly valid in a normal row (in which case, I might print the string "UNDEFINED"), or an undefined value in a topCalc row, because I didn't ask for a topCalc calculation on this column, but you're calling the accessor anyway !
There doesnt seem to be any way for me, in the accessor to say "ahhh.. I'm being passed a topCalc undefined, and I dont want to put anything in the topCalc area of this download, so I would set it to '' so nothing is printed"

The only way I can think of is to put a flag in the accessorParam that says "dont do anything in the very first call to the accesor, coz its an undefined for a topCalc that you didnt ask for" ... but what would I do for the bottomCalc ? There's no way to flag "dont do anything for the LAST call to the accessor, coz you'll never know its the last row ?

**Comment by olifolkerd** [comment]
Hey @roxuss 

I do understand what you are asking, For a valid CSV there must always be something in the column, you cant simply skip it or the values no longer align correctly in columns. it is therefor correct that the accessor is called and that a value, even an empty value is shown there.

The correct approach would be for the accessor to return either underfined or an empty string if the value passed to it is undefined, which is exactly the value of the calculation on a column without a top calc.


Oli :)

**Comment by roxuss** [comment]
I only used CSV in the jsfiddle for expediency. In fact, the CSV doesnt create topCalc rows ANYWAY. I actually create PDF's, but now I have (for example) $0 at the top of a column in the PDF becoz it is a column of currency types (so the accessor returns a currency formatted string - which treats an undefined in the column as $0.00 - for ALL data rows, not just the topCalc) becoz the column next to it (Inventory count) has a topCalc:'sum'

**Comment by olifolkerd** [comment]
While i understand for your usage case this is undesirable, for the reasons outline above this is an intended feature and not a bug.

Thank you for raising the feature request, i will put further commends on there.

Cheers

Oli :)

**Comment by roxuss** [comment]
roger that !
