### ISSUE TITLE
bug: When editing a cell 'home' and 'end' scroll the table rather than moving the cursor

### ISSUE THREAD

**Issue by rathboma** [olifolkerd/tabulator#2945]
**Describe the bug**
When in an `input`, `home`, `end`, `page-up`, and `page-down` typically move the cursor around in the input. However, these keyboard shortcuts are used to scroll the table, so it cancels edit mode and jumps the user around in the table.

**Tabulator Info**
- 4.7.2

**Working Example**
http://tabulator.info/docs/4.7/edit
^ Edit the name field in the edit demo, then press home, end, page-up, or page-down

Note - the location field works as expected (select box)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. edit a text field with either an `input` or `textarea`
2. press 'home' or 'end' keys
3. editing gets cancelled, table scrolls

**Expected behavior**
cursor moves to front/end of the input.

**Comment by olifolkerd** [comment]
I have pushed an update to the master branch to resolve this in each of the respective editors.

I will be included in tommorow 4.8 release.

Cheers

Oli :)
