### ISSUE TITLE
ajaxURL setData Method.

### ISSUE THREAD

**Issue by cemmons** [olifolkerd/tabulator#295]
Hi, it's me again, thanks a lot for the new feature, now I'm implementing it and my response using a web method is something like this.

```
{"d":"
	[
	{\"surCode\":\"01\",\"intCode\":\"rpm011700002\",\"cusCode\":\"0001958259\",\"rotCode\":\"rpm01\",\"sicValid\":true},
	{\"surCode\":\"01\",\"intCode\":\"rpm011700004\",\"cusCode\":\"0001462551\",\"rotCode\":\"rpm01\",\"sicValid\":true}
	]"

```
I can't remove that d from the response, because it is a security fix implemente by .net3.5 so I was hoping you'd now any way to get inside that d.. from tabulator, using the setData function.

Right now my grid doesn't show any data. but it is returned correctly

**Comment by olifolkerd** [comment]
Hey,

sorry for the delay in getting back to you.

There is no need to modify the tabulator code, there is already a function for this.

The ***ajaxResponse*** callback allows you to alter the incomming data before it is passed to Tabulator:

```js
$("#example-table").tabulator({
    ajaxResponse:function(url, params, response){
        //url - the URL of the request
        //params - the parameters passed with the request
        //response - the JSON object returned in the body of the response.

        return response.d; //return the response data to tabulator
    },
});
```

Let me know if that helps.

Cheers

Oli

**Comment by cemmons** [comment]
Hi!! Nice, it works just fine... i missed it from the documentation.

**Comment by teeleh** [comment]
I am trying to pull in Lessons data in JSON, when I copy the stream into a variable it works fine but when I try to use:

$("#lessons").tabulator("setData", "http://www.squashenwellness.nl/ws/fridays.php");

I get a loading error on the page.

This is the code I use:

		$("#lessen").tabulator({
			height:"540px",
	 		fitColumns:true,
			tooltips:true,
			tooltipsHeader:true,
			movableCols:false,
	
		    responsiveLayout:true, // this option takes a boolean value (default = false)
			columns:[

			{title:"TIJD", field:"TIJD", sorter:"string", width: 100, align:"center", sortable:false},
			{title:"WAT" , field:"WAT",  sorter:"string", sortable:false},
			{title:"WAAR", field:"WAAR", sorter:"string", sortable:false},
			{title:"WIE" , field:"WIE",  sorter:"string", sortable:false},
			],
		});

		$("#lessen").tabulator("setData", "http://www.squashenwellness.nl/ws/fridays.php");

Any idea what the reason is the JSON is not being processed properly ?

Thanks !
