### ISSUE TITLE
priority for multi column sorting

### ISSUE THREAD

**Issue by xkacvinsky** [olifolkerd/tabulator#2954]
*Is your feature request related to a problem? Please describe.**
When activating several multi column sorting in sequence (column 1, column 2, column 3), is the table sorted with priority column 3, column 2, column1. 

**Describe the solution you'd like**
 It will come more naturally to sort columns in sequence column 1, column2, column3 not by last clicked column. Reverse will do that magic.

**Describe alternatives you've considered**
I also find it useful to display priorities (number of sequence next to the arrow, when the user sorts the table) of selected columns for multi column sorting.

**Comment by olifolkerd** [comment]
Hi @xkacvinsky 

This is actually an issue of great contention with different developers taking either side of the issue.

For this reason there is a ***sortOrderReverse*** flag, that inverts the sort order when things are set, to accommodate both view points

```js
var table = new Tabulator("#example-table", {
    sortOrderReverse:true,
});
```

Cheers

Oli 🥇
