### ISSUE TITLE
Allow "Row Index" to be inside data object

### ISSUE THREAD

**Issue by steosoft** [olifolkerd/tabulator#2955]
I'm using Tabulator to show statuses of devices in clear format. 
My data with status of device is formatted like this:
```
{
    "matrix_state":"OK",
    "version":"0.0.2.302",
    "error":false,
    "receive_time":1598351354018,
    [..]
    "device":{
        "devId":380655,
        "id":"LED-12x12-RGB-1",
        "deviceType":"LED"
    }
}
```

I have defined columns like devId, id, deviceType with custom formatters (formatter is using jsonpath library to extract value from object e.g. '$.device.devId').
I would like to update data in table based on row index which is "devId" inside "device" object.
Current implementation allows only to use field name in main tree of data object (or I don't know how to use it).

Proposition is to allow (using jsonpath or other simple format) extraction of nested values for "Row Index".

**Comment by olifolkerd** [comment]
Hey @steosoft 

In your usage case the easiest option is to use a hidden column with a mutator to map the id back to the root of the object:

```js
// define mutator function
var idMutator = function(value, data){
    return data.device.id;
}

var table = new Tabulator("#example-table", {
    data:tabledata,
    columns:[
        {field:"id", visible:false, mutator:idMutator}, //add hidden column that maps the id to the root object
    ],
});
```

I hope that helps,

Cheers

Oli :)
