### ISSUE TITLE
Allow multiple mutators on the same field

### ISSUE THREAD

**Issue by AndrewHutcheson** [olifolkerd/tabulator#2956]
If I have some fields like:

```
{title:"GenderID",	field:"Gender" },
{title:"M/W", 		field:"Gender",	mutator:genderMutator, 	formatter:"plaintext", editor:"select", editorParams:{values:{"2":"M","1":"W"}}},
```

where I define genderMutator as 
```
var genderMutator = function(value, data, type, params, component){
	if(value == 1)
		return "F";
	if(value == 2)
		return "M";
}
```
Then I would like to have the mutator not apply to the GenderID titled row. As it stands a mutator is applied to all fields that match a particular field name, not just the row where it is implemented.

**Comment by olifolkerd** [comment]
Hey @AndrewHutcheson 

You should not set multiple columns on the same field, this will cause all sorts of issues when it comes to editing etc. the field is bound directly back to the row data so it cannot have multiple values.

The correct approach in this instance is to use a [Mutator](http://tabulator.info/docs/4.7/mutators) to create a new field in the row data based off of the original field:

```
//generate mutated data from the original field
var genderMutator = function(value, data, type, params, component){
	if(data.Gender == 1)
		return "F";
	if(data.Gender == 2)
		return "M";
}
```

And then use a new unused field name for the column, in this example im opting for ***MutatedGender***:
```js
{title:"GenderID",	field:"Gender" },
{title:"M/W", 		field:"MutatedGender",	mutator:genderMutator},	
```

I hope that helps

Cheers

Oli :)
