### ISSUE TITLE
Feature request to align header content right and sort-arrow left.

### ISSUE THREAD

**Issue by RichardVogelij** [olifolkerd/tabulator#2957]
When I set some numeric sortable columns to align content right, the header is not aligned the same way which gives a somewhat restless look.

**Describe the solution you'd like**
I would like to be able to have the column sorting arrow to be rendered (far) left and the header content (far) right in order to make sure the header content and cell content are both aligned right when I set a column to be aligned right

Currently i'm getting this
![image](https://user-images.githubusercontent.com/998466/91179644-15745200-e6e7-11ea-9139-f6b4b86825dc.png)

I would like to be able to achieve something like this
![image](https://user-images.githubusercontent.com/998466/91179810-49e80e00-e6e7-11ea-8a7e-2c5c4441408a.png)

Using css I was unable to get this behavior. 

Tabulator is awesome by the way!

**Comment by olifolkerd** [comment]
Hey @RichardVogelij 

You are in luck, header alignment will be coming in version 4.8 in a couple of weeks, which will allow the text direction for the column header title to be changed.

I would not be looking to move the location of the sort icon though, that will remain to the right.

Cheers

Oli :)
