### ISSUE TITLE
Pass the click event to the menu item generator functions

### ISSUE THREAD

**Issue by LilDevil** [olifolkerd/tabulator#2959]
**Is your feature request related to a problem? Please describe.**
In my use case, I want to customize the context menu depending on exactly where within the header or row the user clicks.

**Describe the solution you'd like**
Pass the click event to the menu generator function so it can look at the event.target.

**Describe alternatives you've considered**
Attaching click handlers later, but this doesn't work well with the virtual DOM.

**Additional context**
In the column header, I want different menu options depending on if the user right-clicks on the column name, or within the header filter input.

When right-clicking on specific headers or fields within the responsive collapse area, I want to show similar menus to the associated regular column.

In each case I need to look at the event.target in order to build the appropriate menu.

**Comment by olifolkerd** [comment]
Hey @LilDevil 

Thanks for the PR, i think this is a great idea, I have approved the PR for merge in the next release.

Cheers

Oli :)
