### ISSUE TITLE
Progressive rendering completion in the background even when no scrolling.

### ISSUE THREAD

**Issue by alainpannetier** [olifolkerd/tabulator#296]
I have a few tables with 2000+ rows and progressive rendering is great to avoid freezing the gui.

However, there are a few reasons why you would like the rest of the rows to be appended regardless of whether the end user scrolls or not:
 - filters seem to work only on the displayed row
 - Collapsing groups (as in GroupBy) and group cardinality expose the trick.
Any trick?

**Comment by cemmons** [comment]
I have worked using filters  and progresive rendering and it works even in not displayed rows.

**Comment by alainpannetier** [comment]
Thanks Carlos, but my experience is different.
Am I missing something here?

1/ Have a table with groups and around 3000 rows.

2/ The last row of column 1 (when all rows are displayed) is "public ip"

3/ If I reload the table (and only the top 'progressiveRenderFill' rows are
displayed)

4/ and then type 'public' in the column 1 filter box, I have zero hits.

I can make a smaller example to make sure but I'm pretty sure in the
conditions above it does not work (all rows are on client side - of
course).  Do you have a different behaviour?

Regards,

**Comment by olifolkerd** [comment]
Hey alan,

In most cases the filter function does indeed filter all rows, however you have exposed  flaw in the progressive Render system there where it is only being applied to the first set of data progressively loaded and not any others.

Version 3.0 will be coming out this month and will resolve these issues.

what did you mean by "collapse groups"?

Cheers

Oli

**Comment by alainpannetier** [comment]
Hi Oli, thanks for being so dedicated and relieable.

Here is what I meant. Look at the 3 screen shots below
1. First one is taken immediately after building and rendering the table (default progressive parameters applied)

1.  Second one after collapsing all the group headers that came with the first batch of data. You can see, comparing with the next one, that only the loaded rows are taken into account

1. Third one I expanded back groups and (slowly :) ) loaded the rest of the table using the down arrow. Then collapsed things again for you to understand.

Indeed, I've got high expectations for 3.0 but I couldn't help trying out a few more things.
As for now, I can:

 1. Look into the source code and see if I can invoke the loader asynchronously in the background without waiting for the user to attempt reaching the bottom rows.

 2. Do sth else and may be I won't need progressive rendering at all in 3.0

![screenshot from 2017-05-12 11 32 01](https://cloud.githubusercontent.com/assets/1625152/25988076/aed525fc-3707-11e7-9799-b77ec17f4dbb.png)

![screenshot from 2017-05-12 11 32 22](https://cloud.githubusercontent.com/assets/1625152/25988083/b592df24-3707-11e7-8085-c71780c9b89c.png)

![screenshot from 2017-05-12 11 35 07](https://cloud.githubusercontent.com/assets/1625152/25988085/b98a2d3a-3707-11e7-816c-3386ac7e8872.png)

**Comment by olifolkerd** [comment]
Hey,

You will be happy to hear that version 3.0 is now in beta release, progressive rendering has now been replaced with the virtual DOM which can handle grouping without any issues

Head over to http://olifolkerd.github.io/tabulator/news/ to see the latest features!

Cheers

Oli
