### ISSUE TITLE
Nonsensical comparisons with typeof and "null"

### ISSUE THREAD

**Issue by evanw** [olifolkerd/tabulator#2962]
**Describe the bug**
This is a friendly FYI. This repo has some nonsensical code that compares the `typeof` operator with `"null"` even though that comparison will always be false (the value `"null"` is [never returned by that operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof)). This came up because a build tool automatically reported the issue: https://github.com/evanw/esbuild/issues/358.

There are at least two places in your code where this happens:

https://github.com/olifolkerd/tabulator/blob/9489e09d329a75966cd6882f1c588442838d07ef/src/js/modules/download.js#L133

and

https://github.com/olifolkerd/tabulator/blob/9489e09d329a75966cd6882f1c588442838d07ef/src/js/modules/clipboard.js#L95-L101

I'm reporting this to you because this probably indicates the presence of a bug. Presumably this code is trying to check for `col.value === undefined || col.value === null`. There is probably a bug here because `typeof null === "object"` in JavaScript, not `"null"`.

It's up to you if you want to do anything with this information. Even if it's not a bug, removing the nonsensical code would be appreciated because it would avoid this package being flagged by other tools.

**Tabulator Info**
This code is present on master.

**Comment by olifolkerd** [comment]
Thanks for the heads up. I will get those fixed in the 4.8 release next weekend

Cheers

Oli :)

**Comment by olifolkerd** [comment]
I have pushed fixes for these to the 4.8 branch for release next weekend.

Cheers

Oli :)
