### ISSUE TITLE
JSON data not wanting to play ball

### ISSUE THREAD

**Issue by teeleh** [olifolkerd/tabulator#297]
I am trying to pull in Lessons data in JSON format, when I copy the stream into a variable it works fine but when I try to use:

$("#lessons").tabulator("setData", "http://www.squashenwellness.nl/ws/fridays.php");

I get a "Loading Error" on the page.

This is the code I use:

		$("#lessen").tabulator({
			height:"540px",
	 		fitColumns:true,
	
			columns:[
			{title:"TIJD", field:"TIJD", sorter:"string", width: 100, align:"center", sortable:false},
			{title:"WAT" , field:"WAT",  sorter:"string", sortable:false},
			{title:"WAAR", field:"WAAR", sorter:"string", sortable:false},
			{title:"WIE" , field:"WIE",  sorter:"string", sortable:false},
			],
		});

		$("#lessen").tabulator("setData", "http://www.squashenwellness.nl/ws/fridays.php");

Any idea what the reason is the JSON is not being processed properly ?

Thanks !

**Comment by olifolkerd** [comment]
Hey,

Are you getting anything showing up in your developer console? 

If you are trying to access the data on www.squashenwellness.nl from a site hosted on a different domain you will get a cross origin request error due to browser safety restrictions.

You will need to use JSONP to make the request to a different domain.

Cheers

Oli

**Comment by teeleh** [comment]
Hi Oli,

Thanks for the quick response. I copied it to our www.squashenwellness.nl<http://www.squashenwellness.nl> server and it ran right away !

You have made some awesome libarary !

One more question: are you going to consider row grouping and first row CSS ?

If you look at: http://www.squashenwellness.nl/lesrooster/allelessen.php you can see an example: The DAG (DAY) of Zo 14/5 is not repeated on the second row because the value is the same (row grouping within the row rather than creating a header). Same for the first row CSS is shows in bold to indicate the first row of that day. On the TIJD (TIME) column you also see Row Grouping where the time of the lesson is ommitted if similar to the previous row.

We want to rewrite all this code into yours so we have responsiveness in the table ;)

Thanks, Teele

**Comment by olifolkerd** [comment]
Great to hear.

You could achieve what you are after with a few tabulator.css tweaks.

```css
.tabulator-group-body > div:first-child{
    font-weight:bold;
}

.tabulator-row .tabulator-cell[data-filed=DAG]{
    visibility:hidden;
}

.tabulator-group-body > div:first-child .tabulator-cell[data-filed=DAG]{
    visibility:visible;
}
```
Let me know if that helps

Cheers

Oli

**Comment by teeleh** [comment]
I added the below to the tabulator.css but I don’t see any changes. I guess I can just add these lines to the end of the file.

Any mods on the following to make this happen?

            $("#lessen").tabulator({
                                    height:"540px",
                                   fitColumns:true,
                                    tooltips:true,
                                    tooltipsHeader:true,
                                    movableCols:false,

Thanks a lot for your help ! Teele

**Comment by olifolkerd** [comment]
I would suggest you use the object inspector in your browser development tools to see what is overriding your CSS, you may need to be more specific with the selectors.

**Comment by teeleh** [comment]
Hi Oli,

Any chance we could hire you to make this thing work ?

Thanks, Teele

**Comment by olifolkerd** [comment]
Hey,

You will be happy to hear that version 3.0 is now in beta release, which should make your life a bit easier as the interface has been simplified.

Head over to http://olifolkerd.github.io/tabulator/news/ to see the latest features!

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey Teele,

Drop me an email to oliver.folkerd@gmail.com and i will see if i can help you out.

Cheers

Oli
