### ISSUE TITLE
table.copyToClipboard generates exception TypeError: row.getComponent is not a function and table.options.clipboardCopied isn't called

### ISSUE THREAD

**Issue by Joao-deOliveira** [olifolkerd/tabulator#2972]
**Describe the bug**
when using **table.copyToClipboard** if the table has multiple pages and therefore we have the paginator at the bottom (see image), on the **_Clipboard.prototype.copy_** the _range.endOffset_ returned by **_range.selectNodeContents(table.element);_** is 3 (header, body and paginator) and therefore an additional row is tried to be copied and in some situations cause an exception _TypeError: row.getComponent is not a function_ on **_Export.prototype.genereateRowElement_** at 				
if (setup.rowFormatter && _this53.config.formatCells !== false) {
	**var rowComponent = row.getComponent();**

the resolution found is to add the following after **_range.selectNodeContents(table.element);_**
        _if(range.endOffset > 2) // the table has multiple pages the offset includes the pagination ...
            range.setEnd(table.element, 2);_ 

maybe is because of that exception that the **table.options.clipboardCopied** callback isn't called ..

**Tabulator Info**
4.7.2

![image](https://user-images.githubusercontent.com/63957815/92315221-7c90e100-efda-11ea-8799-fc2539634431.png)

**Comment by olifolkerd** [comment]
Hey @Joao-deOliveira 

Thanks for getting in touch.

Please use the [Bug Issue Template](https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Possible+Bug&template=bug_report.md&title=) when reporting a bug, it will prompt you for the information we need to help you out.

As per the [Bug Reporting Guidelines](http://tabulator.info/community#bug) you MUST provide a JS Fiddle or CodePen that demonstates your issue. There are 1000's of ways to configure Tabulator, and most bugs are usually an unexpected conflict between two modules. Without seeing how your table is configured it is almost impossible to get to the bottom of the issue.

If you can post a link to an example of this along with a step by step to recreate it i would be happy to reopen this issue.

Cheers

Oli :)
