### ISSUE TITLE
Version 4.8 Released and new Community Ideas Repo

### ISSUE THREAD

**Issue by olifolkerd** [olifolkerd/tabulator#2973]
Hi All,

You will be happy to hear that v4.8 has been released today. It is jam packed full of new features as always, including:

* RTL Language Support
* Horizontal Virtual DOM *(great for tables with a large number of columns)*
* ESM Module Importing
* Updated AutoColumns Functionality
* Enhanced Context Menus
* Much More...

Checkout the [Release Notes](http://tabulator.info/docs/4.8/release) for full details

### Community Ideas Repo
Today also sees the launch of the new [Tabulator Ideas Repo](https://github.com/olifolkerd/tabulator-ideas), an open repo for members of the community to share links to useful snippets, examples, tutorials and showcase some of the Tabulator projects you may be working on.

I am looking for established members of the community to help manage this new repo, if anyone would be interested in helping manage PR's into the tabulator-ideas repo please let me know below.

Happy Tabulating

Cheers

Oli :)

**Comment by Jojoshua** [comment]
Good stuff @olifolkerd ! I am working the TypeScript definitions and DefinitelyTyped doesn't detect tabulator-tables 4.8 on NPM yet. Is this getting to NPM soon?

Also, is the 3rd snippet for auto column generation correct? http://tabulator.info/docs/4.8/release#autocolumns

**Comment by olifolkerd** [comment]
Hey @Jojoshua 

Thanks for the headsup, i totally forgot to run the publish command yesterday. This is now on npm 👍 
Cheers

Oli :)

**Comment by JimSmithJr** [comment]
Oli,
Thank you so much.  This release is fantastic.  Thank you for including the custom sort indicators which I've already implemented with great success.  I am using Semantic UI icons and it works.
![image](https://user-images.githubusercontent.com/34613151/94982307-6b6abf80-0507-11eb-956b-a5017289d3a8.png)

Although I did get it to work supremely easy I thought I should let you know of the CSS entries I updated.  (I'm using the tabulator_bootstrap.css in my project).  If it helps great, if not thats ok, might help someone with implementation.  The below got me to the screen shot.

And once again, thank you, thank you and thank you to you and every contributor!!

.tabulator .tabulator-header .tabulator-col .tabulator-col-content .tabulator-col-title {
  /*width: 100%;*/ --Commented out
float:left --Added
}
.tabulator .tabulator-header .tabulator-col.tabulator-sortable .tabulator-col-title {
 padding-right:10px; --Changed to 10px from 25px;
}
.tabulator .tabulator-header .tabulator-col .tabulator-col-content {
  padding-left: 8px; --Added all three.  Original was padding all 4 sides.
  padding-top: 8px;
  padding-top: 8px;
}
.tabulator .tabulator-header .tabulator-col.tabulator-sortable .tabulator-col-title {
/*padding-right:10px;*/ --Commented out
}

**Comment by olifolkerd** [comment]
Hey @JimSmithJr 

Thanks for the kind words, im glad you found the update helpful

If you feel you have found an issue then please raise a separate issue for it *(this issue is mainly intended as a notification to the community and a way for developers that build packages that are build on tabulator to ask questions)*. Though as an aside if you are customising the table then a degree of custom css may needed to get things exactly the way you want. You wont see float being used anywhere in Tabulator styling, as a layout method it is a bit outdated and flawed and causes more issues that it solves, flex is a much more powerful tool and should generally always be used in place of flex.

Cheers

Oli :)
