### ISSUE TITLE
typeError: Tabulator is not a constructor

### ISSUE THREAD

**Issue by nikhilakjoshi** [olifolkerd/tabulator#2977]
Describe the bug
React-Tabulator is used as mentioned in http://tabulator.info/docs/4.1/frameworks#react

Tabulator Info

issue is reproducible in v4.8 but not in v4.7.2

Working Example
I'm unable to upload a codepen example at this moment. Will update this as soon as possible.

To Reproduce
Use react-tabulator with tabulator-tables' version 4.8 in a react project, the error comes up. npm automatically pushed me to 4.8 as react-tabulator is compatible with 4.7.2 and greater. I uninstalled 4.8 and backported to 4.7.2 my tables are rendering via react-tabulator now.

**Comment by olifolkerd** [comment]
Hey @nikhilakjoshi 

This issues list is only for updates to the Tabulator core library. If you are having an issue with React Tabulator, please raise it on their issue list

Cheers

Oli :)

**Comment by davidias2004** [comment]
Hi, 
The same happened to me on Vue.

**Comment by olifolkerd** [comment]
Hey @davidias2004 

If you believe this is unrelated to the react native wrapper then i would be happy to look into it further, but someone will have to provide me with a JS fiddle that demonstrates the issue in order for me to get to the bottom of the problem.

Cheers

Oli :)

**Comment by exetico** [comment]
Damn.. I've tried to get this to work for more than an hour. I thought i made some kind of dump mistake in the way I was loading the component. But i can confirm that something is not working as it did.... 

@olifolkerd  Here's one with tabulator-tables 4.7.2 - which is working fine.
https://codesandbox.io/s/bootstrap-vue-4k89l?file=/src/main.js

Here's one with 4.8.1, which reporting the issue mentioned by OP.
https://codesandbox.io/s/bootstrap-vue-forked-v2snr?file=/src/main.js

![image](https://user-images.githubusercontent.com/3549445/94002933-d6dfbf00-fd9a-11ea-907b-efd3120f1451.png)

**Comment by olifolkerd** [comment]
Hey @exetico 

This is due to the ESM updates in 4.8.0

The [Upgrade Guide](http://tabulator.info/docs/4.8/upgrade) in the documentation explains that you have to replace your old ***require*** statement with an ***import*** statement:
```js
var Tabulator = require('tabulator-tables');
```
Should be replaced with:
```js
import Tabulator from 'tabulator-tables';
```

I hope that helps,

Cheers

Oli :)

**Comment by udos** [comment]
@olifolkerd: you missed to replace `var Tabulator = require('tabulator-tables');` in http://tabulator.info/docs/4.8/quickstart

cheers, udo

**Comment by rebeccasc** [comment]
Hi,
I get a quite similar error without using any framework. I tried the [Example Setup](http://tabulator.info/docs/4.0/quickstart#setup) and my code looks like this:

```
<!DOCTYPE html>
<html lang="en">
   <head>
     <link href="https://unpkg.com/tabulator-tables@4.9.3/dist/css/tabulator.min.css" rel="stylesheet">
     <script type="text/javascript" src="https://unpkg.com/tabulator-tables@4.9.3/dist/js/tabulator.min.js"></script>
   </head>
   <body>
    <div id="example-table"></div>
    <script>
      var table = new Tabulator("#example-table", {});
    </script>
  </body>
</html>

```

My error looks like this and occurs in `tabulator.min.js:6:10980`
```
Uncaught TypeError: h.prototype.moduleBindings[e] is not a constructor
    bindModules       https://unpkg.com/tabulator-tables@4.9.3/dist/js/tabulator.min.js:6
    _create           https://unpkg.com/tabulator-tables@4.9.3/dist/js/tabulator.min.js:5
    e                 https://unpkg.com/tabulator-tables@4.9.3/dist/js/tabulator.min.js:5
    <anonymous>       http://localhost:5500/:70
```

Did I miss some imports or something else? Does anyone have an idea what causes the error?

**Comment by exetico** [comment]
Hi

Try and open some of the examples, and see the source-code 😊 There's
plenty of good examples with code, too. You'll just need to open on of the
examples on CodePen (if I remember correctly?) - instead of just looking in
the docs.

lør. 3. apr. 2021 14.09 skrev Rebecca Schmidt ***@***.***>:
