### ISSUE TITLE
Intermittent Cell Context Menu

### ISSUE THREAD

**Issue by mikecbone** [olifolkerd/tabulator#2979]
When adding the cell context menu **with** columns persistence and the default persistence mode, after a refresh the cell context menu stops working and gives a console error. 

Removing the columns persistence fixes the issue. Changing the persistence mode to cookies fixes the issue. 

**Tabulator Info**
4.8.0

**Working Example**
https://jsfiddle.net/h8L2fn59/4/

**To Reproduce**
1. Right-click a cell and click open & the cell will be printed to the console.
2. Click 'Run' again in the top left.
3. Right-click a cell and click open again. The console will show an error and the cell won't get printed out.
4. Remove the column persistence or uncomment the cookie persistent mode and try again; works.

**Expected behaviour**
For the context menu to work after a refresh.

**Desktop**
 - OS: Windows 10 & Linux Mint
 - Browser: Chrome
 - Version: 85.0.4183.102 (Official Build) (64-bit)

**Comment by olifolkerd** [comment]
Hey @mikecbone 

Thanks for bringing that to my attention, it looks like the persistence system is trying to persist the callbacks in the menu array.

I will get a fix for that out in tommorows patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @mikecbone 

I have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)
