### ISSUE TITLE
Fits column to data question

### ISSUE THREAD

**Issue by mangkang** [olifolkerd/tabulator#298]
Hi,

I seem to be having issue with getting fit to data to work. I modify the fit to data example by removing the width specification for the name column to:

$("#example-table-fittodata").tabulator({
			height:"320px",
			columns:[
			{title:"Name", field:"name" },
			{title:"Age", field:"age", width:60, align:"right", sorter:"number"},
			{title:"Gender", field:"gender"},
			{title:"Height", field:"height", align:"center", width:80},
			{title:"Favourite Color", field:"col"},
			{title:"Date Of Birth", field:"dob", align:"center", sorter:"date"},
			{title:"Likes Cheese", field:"cheese", align:"center"},
			],
		});

As you can see in the attachment, the name column did not stretch to show the content of the name column values in the entirety. Please let me know if I am missing something and how i could get this to work.

Also, is there any possibility to automatically hide the dark gray unused background from the table when the table rows are set to the width of its data by calculating the width of tabulator-row class and using that to set the table width when fit to data is enabled so the table looks better?

Would be really nice if there is a way to make this works without extra customized coding.

Thanks!

<img width="816" alt="screen shot 2017-05-13 at 12 09 35 pm" src="https://cloud.githubusercontent.com/assets/13228625/26028435/27f0b500-37d5-11e7-9d6e-f27cb2df6643.png">

**Comment by olifolkerd** [comment]
Can you confirm which version of tabuator you are using?

**Comment by mangkang** [comment]
Hi,

I just downloaded the latest using the download button so it should be the latest from master. Same problem on both firefox and chrome (OS-X).

Thanks.

**Comment by olifolkerd** [comment]
Hey,

You will be happy to hear that version 3.0 is now in beta release, and should address the issues you were having.

Head over to http://olifolkerd.github.io/tabulator/news/ to see the latest features!

Cheers

Oli
