### ISSUE TITLE
Copy of cells don't work when editor is set. 

### ISSUE THREAD

**Issue by h-tendy** [olifolkerd/tabulator#2980]
Hi Oli - Wonder if this is a known issue. When you set editors for columns, we can't select the text of that column. Of course, it immediately drops to editing. But, even if you turn-off editing using some custom ui controls, it still won't let you select the cells. (You turn off editing by using `editCheck` call and simply returning false). Copying of the cells work alright when you set the editor to 'false'. 

http://tabulator.info/examples/4.8?#filter - Check in the demo table that you can easily copy the cells. Like so: 

![image](https://user-images.githubusercontent.com/40791586/92629547-18c52b80-f2ec-11ea-9b13-4dd6511332ba.png)

Here, you can't select any cell of any row as long as you first click somewhere inside the table and then drag the mouse to select... 

http://tabulator.info/examples/4.8?#editable

Thank you.

**Comment by h-tendy** [comment]
Also a quick jfiddle here: https://jsfiddle.net/4nzdj8gu/9/

Try to select a single word in column C, row 1. 

If you remove the 'editable' function for column C, (and turn off the editor), you can do it. 

I guess it is the `editable` function that is not propagating the event maybe?

**Comment by olifolkerd** [comment]
Hey @h-tendy 

When you are rasing test JS Fiddle, would you mind only including the minimal table configuration that replicates the issue, you have so many features turned on in that example (persistence, frozen columns, etc) that it is hard to see the wood from the trees.

A minimal test case should only have the smallest amount of code necessary to replicate the issue and no additional features.

If you can simplyfy the example i can have a look at it.

Also have you had a look at the [Clipboard Documentation](http://tabulator.info/docs/4.8/clipboard)

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @h-tendy 

I wouldn't really consider this a bug, simply how the table operates, when a table has an editor enabled on that cell when it gains focus the editor is triggered, it does not allow for selection in that instance.

If you want selection i would recommend looking at the clipboard example.

Cheers

Oli :)
