### ISSUE TITLE
tabulator.getHtml() throws an error if cell.getRow() is used inside a cell formatter function

### ISSUE THREAD

**Issue by nickfessel** [olifolkerd/tabulator#2981]
**Describe the bug**
If a cell formatter function is defined and `cell.getRow()` is called within the cell formatter function, a call to tabulator.getHtml() throws this error: `row.getComponent is not a function`.

The error is thrown at line 17532 in the https://unpkg.com/tabulator-tables@4.8.0/dist/js/tabulator.js file: `return row.getComponent();` If I change line 17532 to `return row.component;`, the call to tabulator.getHtml() works.

**Tabulator Info**
- 4.8.0

**Working Example**
https://jsfiddle.net/L4ahed1z/

**To Reproduce**

1. Go to JSFiddle: https://jsfiddle.net/L4ahed1z/
2. Click on the 'Print' button
3. 'Script error.' appears in the JSFiddle console.

**Expected behavior**
When calling tabulator.getHtml(), calls to cell.getRow() inside a cell formatter should not produce an error. I expect calls to tabulator.getHtml() to return the html for the tabulator table.

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit
 - Browser: Google Chrome 
 - Version 85.0.4183.83

**Comment by olifolkerd** [comment]
Hey @nickfessel 

Can I ask what it is you are actually trying to achieve with your table. There are special cases for handling printed output and not all formatting techniques are compatible.

If you can let me know what you want to see in the output i can let you know how best to achieve it.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @nickfessel 

Thanks for the headsup,

Looks like that line got missed when the export system moved over to the new ExportRow objects.

I have pushed an update for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)

**Comment by nickfessel** [comment]
> Hey @nickfessel 
> 
> 
> 
> Thanks for the headsup,
> 
> 
> 
> Looks like that line got missed when the export system moved over to the new ***ExportRow*** objects.
> 
> 
> 
> I have pushed an update for this to the master branch and will include it in this evenings patch release.
> 
> 
> 
> Cheers
> 
> 
> 
> Oli :)

Thank you very much for the prompt response, Oli :) I really appreciate it. 

Cheers!
Nick
