### ISSUE TITLE
remote pagination (TypeError: rowEl.classList is undefined)

### ISSUE THREAD

**Issue by MChr1Ss** [olifolkerd/tabulator#2983]
**Describe the bug**
I get an error, when I'm trying to use the remote pagination. The initial loading works fine, but then I get errors. (See "To Reproduce")

**Tabulator Info**
- 4.8

**Working Example**
https://jsfiddle.net/w5bLtuye/

**To Reproduce**
1. Go to: https://jsfiddle.net/w5bLtuye/
2. Click on '1' (first Page)
3. It's loading first and you get the error: 
`TypeError: rowEl.classList is undefined`
`tabulator.js:4988:4`
4. Click again on '1'
5. You get the same error
6. Click again on '1'
7. It will work again

Every 3 clicks it works

**Desktop:**
 - Browser FireFox
 - Version 68.12.0esr

 - Browser Microsoft Edge
 - Version 44.18362.449.0

**Comment by olifolkerd** [comment]
Hey @MChr1Ss 

Thanks for getting in touch,

That is an interesting one, and seems to only occur in firefox, i will investigate that further tommorow.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @MChr1Ss 

I have pushed a fix for this to the master branch. It will be included in the patch release later today.

Cheers

Oli :)
