### ISSUE TITLE
allow centering of empty table placeholder message, even when horizontal scrollbar in use

### ISSUE THREAD

**Issue by EnochG1** [olifolkerd/tabulator#2985]
**Describe the bug**
In case showing column headers when no table data,
width of tabulator-placeholder div is set automatically sum of columns' width.
But it makes placeholder text not showing when scroll width is too long.

I think appropriate position of placeholder text is center of tabulator-tableHolder.

**Tabulator Info**
4.7.2, 4.8.0

**Working Example**
https://jsfiddle.net/trkyagns/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
https://jsfiddle.net/trkyagns/

**Screenshots**
current
![image](https://user-images.githubusercontent.com/19601207/92835497-3e4e5400-f416-11ea-8b31-3d8b2e7805d6.png)

need
![image](https://user-images.githubusercontent.com/19601207/92835604-68a01180-f416-11ea-80d8-265658c1f6c1.png)

**Desktop (please complete the following information):**
 - windows, chrome

**Comment by olifolkerd** [comment]
Hey @EnochG1 

Thanks for the headsup,

That is certainly not expected behaviour, something must have regresed,

i will see if i can get a fix in for tommorows patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @EnochG1 

Looking further into this, this is actually by design and was specifically requested by the community as the default behaviour last year.

I will put it on the roadmap to consider options for configuration of this behaviour.

Cheers
Oli 👍

**Comment by olifolkerd** [comment]
Hey @EnochG1 

I have just pushed this update to the master branch and will include it in this weekends patch release.

Cheers

Oli :)
