### ISSUE TITLE
Rendering issue in datatree table after moving column

### ISSUE THREAD

**Issue by akitaylor** [olifolkerd/tabulator#2986]
**Describe the bug**
Moving columns in table with datatree extension causes rendering issue.

**Tabulator Info**
Version: reproduces in 4.8

**Working Example**
The following codepen page contains an example that deomstrates the problem:
https://codepen.io/akitaylor/pen/BaKxNJy

**To Reproduce**
After opening the codepen the example shows that gender column contains coutries and vica versa. But only values in nested rows are incorrect.

**Expected behavior**
The full content of the columns should have been swapped.

**Screenshots**
![image](https://user-images.githubusercontent.com/8057431/92902101-4a8bde80-f421-11ea-9e82-1150e3813f19.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome, egde, firefox also reproduces the issue

**Additional context**
The suspected cause is that the redraw event does not propagate to the nested rows or nested rown does not take changed column order into account when redrawing.

**Comment by olifolkerd** [comment]
Hey @akitaylor 

Thanks for the headsup, You never need to call the ***redraw*** function like that when updating the table, Tabulator will automatically update the view when data changes.

But you are correct that the move event is only being handled at the parent level when called programatically. I will look at getting a patch for this in tomorrows patch update.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @akitaylor 

I have pushed an update for this to the master branch. it will be included in the patch release later today.

Cheers

Oli :)

**Comment by akitaylor** [comment]
Thank you for the fast response and also for the great library :)
