### ISSUE TITLE
scrollToColumn() does not seem to scroll to left direction

### ISSUE THREAD

**Issue by akitaylor** [olifolkerd/tabulator#2987]
**Describe the bug**
In real life situation I noticed that scrolling seems to work only when the scrolling direction is to the right. So I tried to construct an example where scrolling to the left should happen, but actually it doesn't.

**Tabulator Info**
Version: 4.8.1

**Working Example**
https://codepen.io/akitaylor/pen/BaKxNJy

**To Reproduce**
The codepen example first scrolls full right (this is working), then tries to scroll to the left, but it does not happen.

**Expected behavior**
"Location" column should be visible (first column is frozen, so "location" column is only visible when the table is scrolled full left).

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, Firefox
 - Version: latest

**Additional context**
I tried to debug the problem, but could not find out how the scrolling happens.

**Comment by olifolkerd** [comment]
Hey @akitaylor 

Thanks for the info.

I have pushed a fix for this to the master branch and will include it in the next patch release.

Cheers

Oli :)
