### ISSUE TITLE
Custom column setup

### ISSUE THREAD

**Issue by stack-its** [olifolkerd/tabulator#299]
I'm wanting to create a non-editable column on the left, put a font-awesome icon in it that would show up on every record & then call a custom function when clicked/tapped.

I have the column showing up, but can't seem to get anything to show in the cell, even when setting to simple text::

i.e.
...
columns: [
field:"hello";
],
...
I prefer to put this in all the above column cells:
`<i class="fa fa-bars" aria-hidden="true"></i>`

When clicked, it selects the row (what I want) & I need to run a custom function that will change text properties in that row. Is this the right function to use?

`$("#example-table").tabulator({
        rowClick:function(e, id, data, row){
        //e - the click event object
        //id - the id of the row
        //data - the data for the row
        //row - the DOM element of the row
    },
});`

Thanks

**Comment by olifolkerd** [comment]
Hey,

Thanks for getting in touch, you can use a custom formatter to achieve the icons, there is a ***selectable*** option for allowing row selection, if you want to handle clicks on the handle cell only then you can use an ***onClick*** callback on the column:

```js
$("#example-table").tabulator({
    selectable:true,
    columns:[
        {title:"", formatter:function(){
            return $("<i class="fa fa-bars" aria-hidden="true"></i>")
        },  onClick:function(e, cell, value, data){
            //your on click code goes here
        }}
    ],
});
```

Let me know if you need any more help.

Cheers

Oli

**Comment by stack-its** [comment]
Hi Oli,

Thanks for your reply to #299 - that got me going in the right direction in Tabulator.  I have a few misc. questions for you:

1- When I set responsiveLayout: true & fitColumns:false, (I did this so the columns would hide on smaller screens) Most of the header column headers don't show until I change the width of the browser.  Obviously, on a mobile couldn't change width - is there any way to get it to show properly everywhere?

2- If I want the headers to fully show & not be clipped, is there a setting to auto-adjust the col. widths?

3- On money formatter: Is it easy to add a currency symbol in when the number loads?

4- On time:  I assume that the default is to store hours on server in 24-hr format, how hard would it be to convert to 12-hr w/ AM/PM formatter viewing in Tabulator?  And would need a way to convert back to 24-hr before saving back to server.

5- I normally put in jQuery Touch Events by Ben Major & jQuery UI Touch Punch by Dave Furfero into my products to handle mobile touch & mobile jquery-ui touch events, respectively.  Have you added support for mobile touch, i.e. do I need these plugins?

6- ajax jqXHR.success() & jqXHR.error() are deprecated & are removed in jQuery 3.0  You can use jqXHR.done() & jqXHR.fail() going forward.  My framework will soon move to jQuery3, so is it easy enough to simply search & replace the names in your script?

7- Do you have a minified version available?

Thanks,  Bill

**Comment by olifolkerd** [comment]
Hey Bill, 

In answer to your questions:

1 - There is a bug in responsive layout in the current release. the beta version of Tabulator 3.0 is coming out this week which should fix that.

2  - There is no setting for full width headers at the moment, though you could manually set the ***minWidth*** property on the column to prevent it getting too small.

3 - Not at the moment, you would have to create a custom formatter. this feature will be available in 3.0 though

4 - you should use a custom formatter to convert the 24 hour format to 12 and display it to the user, which wouldn't alter the data but would change how they see it, which would be best for sorting as well.

5 - in the current version of tabulator i recommend Touch Punch, it shouldn't be necessary in version 3.0

6 - at the moment Tabulator only supports jQuery 2.*, version 3.0 will be moved to using the updated ajax functionality. but just so you know it is in the roadmap to remove all jQuery dependencies from Tabulator.  by version 4.0 it will be pure JavaScript with no dependencies.

7 - not for the current version, but version 3.0 comes with minified versions of all files.

Cheers

Oli

**Comment by meaganjohnson** [comment]
Hey there,
Be careful using Oli's suggestion for adding an icon column if you are saving table data (to a server/DB/whatever) or exporting. These columns become part of your table definition, so for example: `getData` will include them. In my case, I had an icon to delete a row at the end of each table, I used `getData` to save edits to a DB...well...the saved objects looked like: `{"id":"1", "col_1":"Some cell data", "col_2":"More cell data", "undefined":""}`. To work around, I had to loop through each object returned by getData to remove items with the "undefined" key before doing the save. Since I use setData and getData for many things, I decided it was too much to account for in every case and am now using context menu instead.

**Comment by olifolkerd** [comment]
Hey Megan,

It definitely shouldn't be including them in the ***getData*** response. do you have an example of the tabulator constructor you were using so i can look inot that for you?

Cheers

Oli

**Comment by meaganjohnson** [comment]
I don't have a copy of the constructor on hand, but I can tell you that the column definition was set prior to initialization, it looked something like the code below--might not be exact. I don't recall whether I tried setting it to `' '` or not.

```
var deleteRowIcon = function(value, data, cell, row, options, table){
	return '<p class="a-ind-link a-padding-0"><a class="a-icononly a-delete-link a-textcolor-gray-30 ibm-small" style="vertical-align:text-top!important;" title="Delete row" data-tabulatorrow="'+data.id+'" data-tabulatoraction="deleteRow"></a></p>';
};
var deleteRowColumn = {
	title: "",
	formatter: deleteRowIcon,
	width:25,
	align:"center",
	onClick:function(e, cell, val, row){
		table = $("#"+tableId);
		console.log("Deleting row: " + row.id);
		$(table).tabulator("deleteRow", row.id);
	}
};
```

**Comment by olifolkerd** [comment]
The beta of Tabulator 3.0 is coming out this weekend. It is a complete rebuild with a load of enhanced functionality.If there was an issue it should be resolved in this release :)

**Comment by meaganjohnson** [comment]
Forgot to add:
The column would be added to the end of a predefined columns array (called `columns_offering_table`) like so: `columns_offering_table.push(deleteRowColumn);`

**Comment by meaganjohnson** [comment]
Possibly related... I'm running into issues with `deleteColumn` when said column was created using `addColumn`. Here's what a column would usually look like: 
`{"title":"","field":"edition_6","editableTitle":true,"editable":true,"editor":"input"}`
Notice `title` is blank.

1st issue: Once the column is added, the displayed title text is "&nbsp"
2nd issue: If I don't change the title to something else (it's editable), it'll save the column as "undefined".
3rd issue: `deleteColumn` runs and it looks like redraw happens (there's a blink), but the column and cell elements from said column aren't removed from the DOM and everything still shows up in `getData` and `getColumns`.

**Comment by olifolkerd** [comment]
Hey,

You will be happy to hear that version 3.0 is now in beta release, and should address the issues you were having.

Head over to http://olifolkerd.github.io/tabulator/news/ to see the latest features!

Cheers

Oli

**Comment by stack-its** [comment]
Hey Oli,

That columns OnClick function now doesn't work w/ 3.0 beta - what needs to change?
Thanks, Bill

**Comment by olifolkerd** [comment]
it is now ***cellClick***
