### ISSUE TITLE
getFilteredData()

### ISSUE THREAD

**Issue by 8483** [olifolkerd/tabulator#2990]
I've scoured the documentation for such a thing, as well as stackOverflow, and I was unable to find it.  

Is there a `getFilteredData()` method that works like `getData()` that returns just the data after a filter has been applied?

**Comment by 8483** [comment]
Alright, just came upon [this answer](https://github.com/olifolkerd/tabulator/issues/1185) stating to use `getRows(true)` to get just the filtered rows.  

I then applied the same to `getData(true)` and it worked!  

This was **not obvious at all** in the documentation, so it would be nice to have a mention somewhere, unless I am blind an missed it somehow.

**Comment by olifolkerd** [comment]
Hey @8483 

This is covered in detail in [The Data Documentation](http://tabulator.info/docs/4.8/update#retrieve-data)

It clearly states that the ***getData*** function accepts any of the standard [Row Range Lookup Options](http://tabulator.info/docs/4.8/components#row-lookup) with an example covering the "active" option and a link to a page explaining all different lookup option.

Cheers

Oli :)
