### ISSUE TITLE
persistence not working with column grouping

### ISSUE THREAD

**Issue by MChr1Ss** [olifolkerd/tabulator#2991]
**Describe the bug**
If you use persistence on a column which is grouped, then it doesen't work when you reload the website.

**Tabulator Info**
- 4.8.1

**Working Example**
https://jsfiddle.net/y0jm8tb9/2/

**To Reproduce**
1. Go to https://jsfiddle.net/y0jm8tb9/2/
2. Check the third column
3. Run again
4. Check the third column again

**Expected behavior**
That it would work like in the secound column

**Screenshots**
When you first run the code everything is fine
![grafik](https://user-images.githubusercontent.com/53866907/93464469-80c9d200-f8e9-11ea-8b8a-f3dce293b995.png)

When you reload the page, the formatter is not longer working
![grafik](https://user-images.githubusercontent.com/53866907/93464518-917a4800-f8e9-11ea-897e-83a1b131963e.png)

**Desktop :**
 - Browser FireFox
 - Version 68.12.0esr

Best regards
Christian

**Comment by olifolkerd** [comment]
Hey @MChr1Ss 

I am no longer able to replicate this error on firefox,

Can you confirm?

Cheers

Oli :)

**Comment by MChr1Ss** [comment]
Hey @olifolkerd 

I still get the error.
Here is a new fiddle with Tabulator 4.8.3. [https://jsfiddle.net/eqtz9nr2/](https://jsfiddle.net/eqtz9nr2/)

The error is in Firefox 78.4.0esr (Windows), Safari (iOS), Chrome Version 80.0.3987.87 (Windows), Edge.

First time you open the link:
![grafik](https://user-images.githubusercontent.com/53866907/97680012-521d4a80-1a96-11eb-9857-12b4a7f92b62.png)
Second time (or click run):
![grafik](https://user-images.githubusercontent.com/53866907/97680065-66614780-1a96-11eb-9c3a-5f51e8568b48.png)

The expected behavior is the first state.
If you want to get to the first state you have to delete the local storage.


Best regards
Christian

**Comment by olifolkerd** [comment]
ahh yes, i see you have to clear out the persistence cache otherwise it will work.

Thanks

**Comment by MChr1Ss** [comment]
Hey Oli,

it is not working _with_ the persistence cache, when you set
`columns: false, //persist columns`
Then it works. 
The cache is maybe set wrong. 

Thanks for your help

**Comment by olifolkerd** [comment]
Hey @MChr1Ss 

I have pushed a fix for this to the 4.9 branch that will be released later today.

Cheers

Oli :)

**Comment by MChr1Ss** [comment]
Thank you Oli :)
