### ISSUE TITLE
When columns are shown and column should be vertAlign, Cell.show set the wrong display style

### ISSUE THREAD

**Issue by brimimc** [olifolkerd/tabulator#2992]
**Describe the bug**
If you have a a table with `cellVertAlign: 'middle'` and you show a column that was hidden, it calls 

`Cell.prototype.show = function(){
	this.element.style.display = "";
};`

which sets the display to `""` vs checking on the `self.column.vertAlign` property and setting it to `inline-flex`

It should be setting `this.element.style.display = this.column.vertAlign ? "inline-flex" : "";`

**Tabulator Info**
4.7

**Comment by brimimc** [comment]
PR created https://github.com/olifolkerd/tabulator/pull/2993

**Comment by olifolkerd** [comment]
Hey @brimimc 

Thanks for pointing that out and for the PR.

I have merged in your PR and will include it in the next patch release.

Cheers

Oli :)
