### ISSUE TITLE
rowData is not defined

### ISSUE THREAD

**Issue by Cyrelc** [olifolkerd/tabulator#2995]
https://github.com/olifolkerd/tabulator/blob/74527f17a208dd7777bf7eb5b7226bc8d160be97/src/js/modules/export.js#L485

rowData is not defined at this point when calling print on table. Row object passed to function does not appear to have a getData() attribute, attempted as a workaround

**Comment by olifolkerd** [comment]
Hey @Cyrelc 

Thanks for the headsup, i have pushed a fix for this to master and will include it in the next patch release.

Could i ask that next time you report a bug, you use the [Bug Issue Template](https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Possible+Bug&template=bug_report.md&title=) and fill in the requested sections.

It really helps us get to the bottom of issues if you can provide a working JS Fiddle or CodePen that demonstrates the problem.

Cheers

Oli :)

**Comment by Cyrelc** [comment]
Will do, thanks for the quick response!
