### ISSUE TITLE
jQuery Dialog Busts Autocomplete?

### ISSUE THREAD

**Issue by csteph9** [olifolkerd/tabulator#2998]
**Describe the bug**
Options in autocomplete are not selectable when table is embedded in a jQuery modal window.

**Tabulator Info**
Tabulator: 4.8.1
jQuery: 3.5.1

**Working Example**
https://jsfiddle.net/1zg39d5j/3/

**To Reproduce**
1. Go to https://jsfiddle.net/1zg39d5j/3/
2. Observe the auto select works with the table embedded on the page (sorry for poor tabulator formatting)
3. Click on "pop-up" link.
4. Select the value in the row to produce the auto-complete drop down.
5. Observe that none of the items are selectable.

**Expected behavior**
When table isn't embedded in jQuery modal, it works fine.

In the jQuery modal, values don't seem to select.

**Desktop:**
 - OS: Windows 10
 - Browser: Tested on Chrome (Version 85.0.4183.102 (Official Build) (64-bit)) & Firefox (80.0.1 (64-bit))

**Comment by olifolkerd** [comment]
Hey @csteph9 

This is not a bug with Tabulator, it is just a z-index issue with the modal,

The select list element is appended to the DOM with a z-index of 10000, if your modal has a heigher z-index it will hide the select list.

Cheers

Oli :)
