### ISSUE TITLE
Order by number

### ISSUE THREAD

**Issue by pfloriginale** [olifolkerd/tabulator#3]
Hi!
complimento for good work... but I have find this problem...
somebody "order by text" don't work... this is because there is a space before the word

{
"id":1183,
"data_fattura":"2015-06-24 00:00:00",
"note":" PAOLO maxigross ",
"importo":-277.34,"
}

![cattura](https://cloud.githubusercontent.com/assets/16399563/11952903/464b1834-a89c-11e5-8fdc-a193b8790fda.PNG)

here my code

**Comment by olifolkerd** [comment]
could you show me the column definitions you used to setup the table and i will have a look for you this evening

**Comment by olifolkerd** [comment]
Hi, 

I have tested your example words and they are sorted correctly. To sort the note field you want to use sorter:"string", not "number".

If you want to sort by a column on data load set the options:
```js
sortBy:"note",
sortDir:"desc",
```
Text starting with a space will always be sorted above/below symbols as that is the correct way to sort a space. I would suggest that you remove spaces programatically before loading the data.

in javascript:
```js
str.trim();
```
in PHP:
```php
trim(str);
```

As a note, I have just added a new sorter "alphanum" to correctly sort alpha numeric strings, if that is of any use to you.

**Comment by pfloriginale** [comment]
Wow,  thanks for reply!
I have solved with trim function like you say!


I write from Italy

- Data here is dd/mm/yyy
- Price is 1.000,00 (1 thousand dollars). Decimal with comma;

I saw different setting for sort data and it's ok, but, for number i nedeed
to...

javascript .replace(",",".");

Maybe it will be helpful give this kind of setting for your beautiful table!

Now I'm testing but look like immediatly and functionally!
Good job!

2015-12-22 21:51 GMT+01:00 Oli Folkerd <notifications@github.com>:

**Comment by olifolkerd** [comment]
Hey,

Thanks, glad to hear you got it working, i will add a money formatter/sorter in the future.

In the mean time you could create your own custom sorter function for your money

Create a function with the following parameters:
```js
mySorter = function(a, b){ //sort numbers
	return parseFloat(a) - parseFloat(b); //return the difference between thw two numbers (add your own comparison code here)
}
```
Parameters ***a*** and ***b*** are the two values being compared.

The function must return the difference between the two values

Then assign this to the column using the sorter parameter:
```js
 {title:"money", field:"value", sortable:true, sorter:"number", width:200, sorter:mySorter},
```
