### ISSUE TITLE
Use input form's value into delete row function does not work

### ISSUE THREAD

**Issue by vonschbo** [olifolkerd/tabulator#30]
```javascript
$("#samples-table").tabulator("deleteRow",1);
```

This function works on my table,

However, when I want to set the deleteRow id from an input form, like 

```javascript
var tem = $("#txt_name").val();
            $("#samples-table").tabulator("deleteRow",tem);
```

It gets an error message on "item.data"

**Comment by olifolkerd** [comment]
This is because you are passing a string of "1" into an argument that is expecting an integer.

For the time being should use the following:
```js
var tem = $("#txt_name").val();
$("#samples-table").tabulator("deleteRow",parseInt(tem));
```
I will add an update this evening so the system can handle both string and integer number representations.

**Comment by olifolkerd** [comment]
This has now been resolved in the latest commit, ***deleteRow*** will now accept strings of integer values as well as integers.
