### ISSUE TITLE
select headfilter clear button is not showing on firefox

### ISSUE THREAD

**Issue by wunaidage** [olifolkerd/tabulator#3002]
**Describe the bug**
select headfilter clear button is not showing on firefox when hovering onto the filter

**Tabulator Info**
4.8

**Working Example**
https://jsfiddle.net/etfumxao/

**To Reproduce**
1. open firfox
2. open jsfiddle link
3. do filter on the column
4. hover over the filter again

**Expected behavior**
I should be able to see clear button when hovering onto the head filter and clear the filter

**Screenshots**
in firefox:
![image](https://user-images.githubusercontent.com/12276316/94035174-cb879600-fd90-11ea-882a-b30758742376.png)
in chrome:
![image](https://user-images.githubusercontent.com/12276316/94035571-3df87600-fd91-11ea-9ac3-2845dc81accb.png)

**Desktop (please complete the following information):**
 - OS: [macos]
 - Browser [firefox]
 - Version [80]

**Comment by olifolkerd** [comment]
Hey @wunaidage 

Thanks for getting in touch.

This is not actually a Tabulator bug, but an issue with Firefox. Tabulator uses standard "search" type input fields for column headers. Firefox has yet to implement the clear button in search type input elements.

Cheers

Oli :)

**Comment by wunaidage** [comment]
Thank you Oli for such quick response! I notice that the filter is actually an input. could you please make it at least editable? really need a way to clear the header

**Comment by wunaidage** [comment]
I also just found that the select header on the example page is not showing the clear button even on chrome now, eg. `favorite color`
http://tabulator.info/examples/4.8#filter-header
@olifolkerd could you please verify?

**Comment by mbulfair** [comment]
> I also just found that the select header on the example page is not showing the clear button even on chrome now, eg. `favorite color`
> http://tabulator.info/examples/4.8#filter-header
> @olifolkerd could you please verify?
> also the gender column, when I click the header filter again after I have selected `female`, it automatically select back to `male`

So I tested this out as well, it seems when you select `male` it's searching the entire string, so `female` is still shown, I think the search needs to be set as exact to prevent that
