### ISSUE TITLE
Calculations on specific columns being applied to all columns

### ISSUE THREAD

**Issue by joaodlf** [olifolkerd/tabulator#3004]
**Describe the bug**
Footer calculations are being applied to all columns, even ones that don't have a calc setting.

**Tabulator Info**
- 4.8.1

**Working Example**
https://jsfiddle.net/um3xgrwa/1/

**Additional context**
The example I have pasted above shows a footer calculation for the "name" column, which shouldn't happen. This is happening when a `bottomCalc` is set to the "clicks" column.

I am also using react-tabulator in other projects, where using the `reactFormatter` is having adverse effects as soon as a `bottomCalc` is introduced to any of the columns.

**Comment by olifolkerd** [comment]
Hey @joaodlf 

This is not a bug, but a change in behaviour in 4.8, users had requested that formatters be applied to all columns so they could format the empty calc cells.

You just need to make sure your formatters can handle undefined values (just do an undefined check in the formatter) or use the ***bottomCalcFormatter*** function to set an empty formatter on the affected column.

This change has resulted in some confusion within the community so i will be pushing a fix to make this easier to understand and updating the documentation to explain this in more detail.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
On further investigation i had misinterpreted your explanation. there was  indeed a bug in the formatting of the column calculations with the default formatter.

I have pushed a fix for this to the master branch and will include it i todays patch release.

Cheers

Oli :)
