### ISSUE TITLE
Add new row

### ISSUE THREAD

**Issue by 8483** [olifolkerd/tabulator#3007]
I am aware that this was posted before and that you don't want to bloat the library.

I also **really** think that Tabulator needs this feature, as it makes sense with the editable cells.  

We have no elegant way to add a new row, so my suggestion is to have [something like this](https://imgur.com/a/luAc1kU).

Which can be defined like so:

```js
 var table = new Tabulator("#table", {
    height: "auto",
    data: [...],
    columns: [...],
    addNewRow: true,                          // toggling the functionality on/off
    addNewRowLabel: "+ new",          // any custom text, or event better HTML for buttons
    addNewRowCallback: ( ) => { }     // used for POST and getting back an ID from the server, or whatever
})
```

I know that we can use...
```js
table.addRow({}, false);
```
...but, the problem is that we have to implement the logic to prevent inserting multiple blank rows, as well as having buttons outside the table. 

I honestly believe my suggestion is a good one and I would like to hear your opinion.

Much respect

**Comment by olifolkerd** [comment]
Hey @8483 

I would not be looking to add a feature in that way, i do not feel that provides a good user experience especially in a scrollable table.

Tabulator has extensive features to allow developers to choose how they want to add rows to a table, and it is down to developers to choose how and where add row buttons appear on their page.

If you wanted to add something like this to your table then you could easily make a custom row formatter that is only applied on a row with no data to show the add row button.

Thanks for your suggestion

Oli :)
