### ISSUE TITLE
boilerplate HTML at QuickStart incorrect

### ISSUE THREAD

**Issue by mark-zarandi** [olifolkerd/tabulator#3009]
**Website Page**
http://tabulator.info/basic/4.8

**Describe the issue**
i think maybe the rowclick called back defined in this html boilerplate is incorrect.

**Comment by olifolkerd** [comment]
Hey @mark-zarandi 

Thanks for the headsup, it looks like the demo hand been updated since the old 3.x versions.

I have pushed an updated version to the site.

Cheers

Oli :)
