### ISSUE TITLE
Error while attempting to updateData

### ISSUE THREAD

**Issue by troybail** [olifolkerd/tabulator#301]
Thank you for this very useful API.  Your documentation is excellent.  

I seem to be missing something with respect to the updateData method, however.  I have a table with a column of images, and I would like the user to be able to change the image using a right click.    When calling "updateData", I am getting the following error:

``tabulator.js:1386 Uncaught TypeError: data.forEach is not a function
``

... which is triggered from this: 

      onContext:function(e, cell, value, data){

        var filePaths = dialog.showOpenDialog(
          { filters: [{name: 'Images', extensions: ['jpg', 'png', 'gif']} ]}
        );

        var newData = '[{ SceneNum: \"' + data.SceneNum + '\", imagePath: \"' + filePaths[0] + '\" }]';
        alert(newData);
        $("#sbTable").tabulator("updateData", [newData]);
      }

Also, I am using my own index field called "SceneNum", as set in the tabulator initialization:

`` $("#sbTable").tabulator({   index:"SceneNum" });
``

On inspecting the contents of ``newData`` from the alert, things look fine to me.  Any idea what I may be doing wrong here?

**Comment by olifolkerd** [comment]
The issue is you are passing a string into the ***updateData*** function rather than an array of objects, you should be using the following line:
```js
 var newData = [{ SceneNum:  data.SceneNum, imagePath: filePaths[0]}];
```

Let me know if that helps you out.

Cheers

Oli

**Comment by troybail** [comment]
Aaah, of course!  Thank you.   I learned to code using perl, and I keep finding myself wanting to treat things as a scalar.

**Comment by arelbernardo** [comment]
Thank you for this Tabulator! It's really nice but I have this problem when it comes to load the table contents / re-render the table again.

Heres the code: https://gist.github.com/arelbernardo/740b42c50ba37c6189b14bac688144d1

I have my json data as stated on that link and I want to trigger the **renderAddButton** formatter function when I reload the table. I used `setData` but it gave me an empty contents. 

Your answer will be my best choice. Thanks.

Thanks Oli!

**Comment by olifolkerd** [comment]
Hi arelbernardo,

If you are loading data via ajax i would suggest you user your browsers dev tools to make sure you are sending back a valid response.

Tabulator 3.0 is now in beta release, and has better error messaging, so may help you get to the bottom of your problem faster.

Cheers

Oli.
