### ISSUE TITLE
add allowTruthy option to tickCross editor

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#3016]
**Describe the bug**
![image](https://user-images.githubusercontent.com/799021/94743898-c8883900-0380-11eb-873a-19fd02075c18.png)
The cell value is `2688` when I start to edit this value the editor unfortunately is not checked, despite on all other input filled in correct (see picture above)

**Tabulator Info**
- Which version of Tabulator are you using?
v4.6.3

**Expected behavior**
the `input` should have `checked` property.

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. cell with `tickcross` with `AllowTruthy` enabled and some value `12345`
2. Start to edit this value
3. I expect check is displayed in editor
4. but editor says like there is no value at cell at all

**Expected behavior**
editor should have `checked` property

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.3
 - FF v79.0

**Comment by KES777** [comment]
probably error is here:

```
input.checked = value === true || value === "true" || value === "True" || value === 1;
```

Here you do not take into account that value is `Truthy` and could be `223432`

So I suppose next condition: 
`... || AllowTruthy and value != false`

**Comment by KES777** [comment]
This patch fixes the problem
```diff
@@ -15626,6 +15626,7 @@ var _typeof = typeof Symbol === "function" && typeof Symbol.iterat
         tickCross: function tickCross(cell, onRendered, success, cancel, editorParams) {
             var value = cell.getValue(),
                 input = document.createElement("input"),
+                truthy = editorParams.allowTruthy,
                 tristate = editorParams.tristate,
                 indetermValue = typeof editorParams.indeterminateValue === "undefined" ? 
                 indetermState = false;
@@ -15659,7 +15660,7 @@ var _typeof = typeof Symbol === "function" && typeof Symbol.iterat
                 });
             }
 
-            input.checked = value === true || value === "true" || value === "True" || val
+            input.checked = truthy && value || value === true || value === "true" || valu
 
             function setValue(blur) {
                 if (tristate) {
```

**Comment by olifolkerd** [comment]
Feel free to submit a PR with your solution if you like

Cheers

Oli 😁

**Comment by KES777** [comment]
I do not think it is good for PR. Second this is for 4.6.3. First I should upgrade and check it with new versions.
I do not think this will be soon.

But this investigation could give you a root to fix bug ( if it is still exists in new versions)

**Comment by olifolkerd** [comment]
hey @KES777 

On further inspection i think you have become confused between the tickCross editor and the formatter.

The formatter has an ***allowTruthy*** property which does work correctly and allow all true values.

There is no such property on the editor, it only accepts values as either true, "true" or 1 in order to be ticked. and in that case it is working exactly as described.

I dont disagree that for consistencies sake this would be a useful addition to the editor, but as it is not currently a feature im going to class this as a feature request and not a bug and will look at considering it for the next minor release.

Cheers

Oli :)

**Comment by KES777** [comment]
Good news, thank you, Oli

**Comment by olifolkerd** [comment]
@KES777 On further consideration im not really convinced that is is a good idea, the editor cannot save a "truthy" result, when toggled the value will either change to true or false, there is no option for anything else there. so it would only be accepting a truthy value when the editor is loaded and then returning a true value after toggle.

In this case i think it would be better to use a mutator to correctly change the underlying data first for better consistency.

Cheers

Oli :)

**Comment by KES777** [comment]
@olifolkerd 
Why not allow that by default? it is expected that true/false editor will update cell to true/false value.
If user want more than it could add formater.

The described behavior is pretty expected by default.
Why we should force user to do something to get expected behavior? ;-)

**Comment by olifolkerd** [comment]
Im not talking about the users expected behaviour, im talking about the underlying data which is incorrectly formatted for that column.

Do you have a realistic usage case that would replicate this with data?

**Comment by KES777** [comment]
The field with date value. When date is not null then "Tick" is displayed.
In the table I do not care of date value.
When user want to turn off the false value is saved
when it turn in on again the value of 1 is saved. So tick is displayed again.

**Comment by olifolkerd** [comment]
In that case the correct approach would be to use a mutator to alter the data comming into the table into a Boolean.

The editor is designed only to work with booleans and I feel the truthy approach would be a fudge to deal with a situation that already has a non bodgy solution through mutators

**Comment by KES777** [comment]
No, that not boolean, that is the date field, but at user interface that have not matter what date is.
There should be displayed Tick and should be ability to swich that value. DB always store current date when date is going to be updated despite on its current value

The trigger just does: `update  action_date = now()`, so front interface can not set its value, so the value of `1` for date field after editing is OK. For updating actual value I can set mutator as you suggest, but tickeditor should work for not only booleans. 

With or without this feature your tabulator is great in any case ;-)

**Comment by olifolkerd** [comment]
Thanks for the explanation,

I think this is a bit too much of an edge case to include as a feature in the library. I would be uncomfortable making an editor that dealt with truthy values as all others dont behave that way.

Using mutators and accessors would still work in your approach, you would just set a mutator to set the value to true as it enters the table and an accessor to set it to the current date when it leaves the table if it is true, or you could use an editMutator to handle that more directly

If that still dosnt fix your issue then i would suggest a custom editor may be your best route. 

Thanks for your kind words, it is great to hear people are enjoying using Tabulator

Cheers

Oli :)
