### ISSUE TITLE
Ambiguous explanation of .selectRow arguments

### ISSUE THREAD

**Issue by arimeq** [olifolkerd/tabulator#3021]
**Website Page**
http://tabulator.info/docs/4.8/select#manage

**Describe the issue**
The documentation linked above says:

> To select a specific row you can pass the any of the standard row component look up options into the first argument of the function.

Phrase "row component look up" is a link to http://tabulator.info/docs/4.8/components#lookup, where it is explained that values used for looking up a `Row` are:

1. A `RowComponent`
2. The index value of the row
3. DOM node of the row

While I did not check 1. and 3., I was badly misguided by 2.

I understood this as a regular `Array` index, which it obviously is not. It is only after I read the selection module source code when I discovered that for this to work, my data MUST have a field called `id`.

Alternatively I can configure in Tabulator config the name of index field, by adding a string type property `index` to the configuration object.

Neither of this information can be found on neither of those two links I pasted above.

I was also further misguided by the example found at http://tabulator.info/docs/4.8/select#manage, which showed selecting rows by feeding the `.selectRow` method with an `Array` of numbers.

I think this information should be added to the docs, along with a correct example showing that the index field can be configured. In order to promote good practices, index field can contain UUIDs (the only reasonable substitute for numbers, when it comes to indexing a table data).

If the above information is already included somewhere else in the docs, there should be some kind of a pointer to that "somewhere" either in docs about select or in docs regarding component lookup.

**Comment by olifolkerd** [comment]
Hey @arimeq 

Thanks for getting in touch.

Sorry to hear that you had trouble with the documentation.

The concept of row position vs row index is actually described elsewhere in the documentation, but i can see how if this was the first time you encountered it reading that part of the documentation, it could be very confusing, i will ensure that an explanation of the two is included in that section.

If you would like to like to get a row by its position in the table then there are several functions to help you out there, checkout the [Documentation](http://tabulator.info/docs/4.8/update#retrieve-position) for full details

The index field is simply any field that a user chooses to set using the ***index*** property on the table. It is not for me to say what is or isnt good practice for an index in the use of a table as that will depend heavily on usage case. If the data is coming from a database then i totally agree with you, but if the user is simply generating the table in the front end for picking something like a colour for example then a unique string of the colour would be perfectly acceptable. As long as it is unique Tabulator dosn't care and i deliberately do not try and force users down a specific route, tabulator is used by thousands of developers on thousands of projects and i don't want to exclude any usage case if i can avoid it.

Cheers

Oli :)
