### ISSUE TITLE
updateData fails with dataTree

### ISSUE THREAD

**Issue by piccit** [olifolkerd/tabulator#3023]
**Describe the bug**
`updateData` is throwing an error on tables where `dataTree` is true. It looks like it's failing in dataTree `layoutRow` on rows that do not have any cells (which I imagine is because they aren't visible). Specifically it's failing on the `el = cell.getElement()` line

```
tabulator.js:14038 Uncaught (in promise) TypeError: Cannot read property 'getElement' of undefined
    at DataTree.layoutRow (tabulator.js:14038)
    at tabulator.js:7025
    at new Promise (<anonymous>)
    at Row.updateData (tabulator.js:6932)
    at tabulator.js:10104
    at Array.forEach (<anonymous>)
    at tabulator.js:10096
    at new Promise (<anonymous>)
    at Tabulator.updateData (tabulator.js:10082)
    at ?editor_console=true:147
```

**Tabulator Info**
- Which version of Tabulator are you using?
4.8.2 (https://unpkg.com/tabulator-tables@4.8.2/dist/js/tabulator.js)

**Working Example**
fiddle: https://jsfiddle.net/piccit/ktwxjLa6/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Run fiddle in chrome
    * the issue happens in firefox too in my actual code, but I'm only seeing the error logged in the fiddle with chrome
2. See error in console (and/or note that 'done' never logs in the `then` block)

**Expected behavior**
table is updated w/out errors

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 85.0.4183.121 (Official Build) (64-bit)

**Additional context**
Noticed this issue when updating from 4.2.7.

I don't know enough about the inner workings, but based on the fact that the affected rows do not have any cells, I would image that `layoutRow` could just gracefully do nothing?

**Comment by olifolkerd** [comment]
Hey @piccit 

Thanks for letting me know, that definitely looks like a bug,

I will get a fix out for that in the next patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @piccit 

I have pushed a fix for this to the master branch and will include it in the next patch release.

Cheers

Oli :)
