### ISSUE TITLE
Extending Ajax module to have default to method to 'POST' does not work 

### ISSUE THREAD

**Issue by bhaveshkgupta** [olifolkerd/tabulator#3026]
I wanted to have all of my AJAX to go as 'POST' so I tried extending this module as suggested in example page -
http://tabulator.info/docs/4.8/modules#extend
```
Tabulator.prototype.extendModule("ajax", "defaultConfig", {
    type:"POST",
    contentType : "application/json; charset=utf-8"
});

```
But still I see all call going as GET only

**Comment by olifolkerd** [comment]
Hey @bhaveshkgupta 

Please resubmit this issue using the [Bug Report Issue Template](https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Possible+Bug&template=bug_report.md&title=) without all the details requested in the template it is very hard to offer advice on how to resolve your issue.

It is likely a result of the way your code is setup but without seeing the whole table and setup code we cannot help you, which is whey the template asks for a JSFiddle or CodePen example.

Cheers

Oli :)
