### ISSUE TITLE
column title editable and header menu issue

### ISSUE THREAD

**Issue by Tiuipuv** [olifolkerd/tabulator#3028]
**Describe the bug**
When a column is set to `editableTitle:true, headerMenu:headerMenu`, The column title disappears and becomes a ... symbol, unless shrunk to below the title text length. Even when the column is shrunk, the editor is not visible on the title text.

**Tabulator Info**
Tabulator v4.8.2

**Working Example**
jsfiddle: [here](https://jsfiddle.net/exka4c3j/9/)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1) slide the column width on the second column from wide to very skinny to wide again. In chrome you will see the title appear and disappear depending on the column width.

**Expected behavior**
The header menu should appear to the left of the editable column name, with the column editor and title remaining visible.

**Screenshots**
In chrome, this is how it appears:

before shrinking column width:
![image](https://user-images.githubusercontent.com/23466445/95359052-54bdc300-088f-11eb-8649-d2b548a26add.png)

after shrinking column width:
![image](https://user-images.githubusercontent.com/23466445/95359115-64d5a280-088f-11eb-9b5f-82f1f93c1255.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 v1809
 - Browser: Chrome
 - Version: 86 (latest)

**Additional context**
I also tested on an older version of edge (pre chromium engine). It also had unexpected behavior.

**Comment by olifolkerd** [comment]
Hey @Tiuipuv 

Please use the [Bug Issue Template](https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Possible+Bug&template=bug_report.md&title=) when submitting a bug report, it is very important that you provide the details in the template as it will help in isolating your issue.

Without a JSFiddle that demonstrates your table setup it is very hard to get to the bottom of the issue.

Cheers

Oli :)

**Comment by Tiuipuv** [comment]
Hey @olifolkerd

I updated it to use the bug issue template, with a working jsfiddle.

Thanks Oli, you are doing great work!

**Comment by olifolkerd** [comment]
Hey @Tiuipuv 

I have pushed a fix for this to the mater branch and will include it in the next patch release.

Cheers

Oli :)
