### ISSUE TITLE
Feature: Collapsible/Expandable Column Groups

### ISSUE THREAD

**Issue by YendorMc** [olifolkerd/tabulator#3031]
*Is your feature request related to a problem? Please describe.**
**I recently saw a datatable that had grouped columns that had a (+) at the right side of the main grouped cell that had one child column, and once you clicked the (+), several additional children columns appeared.  The (+) toggled to a (-), and likewise, clicking on the (-) hid the child columns back to the single column of the group.   

I was jealous, and I tried noodling with Tabulator Column Menu system, and got a similar effect, but believe could be improved and more robustly handled within the library.

I also tried to manipulate the headerMenu variable, but could not get it to toggle to a different menu after creation.

For example: I initialized with a collapse, and in the action I tried to redefine the headerMenu to an expand, but it didn't allow.

**

**Describe the solution you'd like**

**I would like to see a collapse/expand functionality on the menu system or separate system on grouped columns to allow the expansion/contraction of 1 or more child columns, keeping one or more child columns in tact.
 
For example instead of the vertical menu icon, have a (-) or fa-minus-circle to collapse to 1 column or a defined set of columns, and when it is collapsed, the icon will turn to a (+)  or fa-plus-circle and you will be able to expand the other columns defined in the group.

The expand/collapse icon can be at the right side or opposite side of the header cell, not to interfere with the current menu icon and one can select default to be either collapsed or expanded.   

One would want to define which columns would be collapsible, as there could be more than one important column to view.  

It's important not to show "Expand" when the columns are expanded and not to show "Collapse" when the columns are collapsed.

Also would like to see a hover, if possible to indicate to either Collapse or Expand, depending on the icon.

Another option would be to allow the headerMenu to be updated after initialization, so one can dynamically change the menu after it is executed and/or allow the menu icon to be change dynamically.** 

**Describe alternatives you've considered**

** I tried redefining headerMenu data to toggle either "collapsed" or "expanded" but would not toggle, for some reason.  The field would need to be dynamic.

I also was able to simulate something similar using the existing menu system, but shows both collapse/expand components.

Here is a functional example of what I'm trying to do with Tabulator**
https://codepen.io/yendormc/pen/MWeYRKy

However, for the menu I would like to have a single (+) or (-) 

**Additional context**
See functional example.
https://codepen.io/yendormc/pen/MWeYRKy

Thanks for your consideration!

**Comment by olifolkerd** [comment]
Hey @YendorMc 

As of version 4.9 (released later today) you will the header menu function will be called each time the menu is loaded allowing you to change the contents of the menu whenever you like.

At which point you can implement this yourself with hiding and showing of columns, there would be no need to build anything additional into the core of the system

Cheers

Oli :)
