### ISSUE TITLE
Clear edited cells methods do not work with “select” column editor

### ISSUE THREAD

**Issue by farbohydrate** [olifolkerd/tabulator#3032]
**Describe the bug**
`table.clearCellEdited()` and `cell.clearEdited()` do not work when the column editor is set to "select". Also posted on StackOverflow: https://stackoverflow.com/questions/64322709/clearing-edits-does-not-work-with-select-column-editor

**Tabulator Info**
Tabulator v4.8.2

**Working Example**
JS Fiddle: https://jsfiddle.net/farbohydrate/nga3kw9f/

**To Reproduce**
1. Change either or both "Status" column cells from Active to Inactive, or Inactive to Active
2. Click on 'Edits Length' button, which will show you the number of edited Cells using `table.getEditedCells()` method
3. Click on either or both 'Clear Edits' buttons, which should clear all edit flags
4. Click again on 'Edits Length' and you will see the edited cells array remains unchanged

**Expected behavior**
After pressing the Clear Edits buttons, expected behavior would be for `getEditedCells()` to contain zero cells.

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser: Chrome
 - Version: 85

**Additional context**
This seems to work correctly when using any column 'editor' type other than "select".

**Comment by olifolkerd** [comment]
Hey @farbohydrate 

Thanks for letting me know,

I will look at getting a fix in for this in the next patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @farbohydrate 

On further inspection, this was working as intended,  (and wasn't limited to select editors, the same was true for editors) 

The intent of this function was to be used with the validtors, which werent set on your example. But i can totally understand your usage case and the documentation wasnt very clear.

I have just pushed an update to master branch to allow this these functions to be used event when validation isnt set.

Cheers

Oli :)

**Comment by farbohydrate** [comment]
Thanks Oli! Just tested out the new build and this works perfectly for use cases outside of validators. Very helpful.
