### ISSUE TITLE
Maintain grid sorting when altering data

### ISSUE THREAD

**Issue by wildcat-cs** [olifolkerd/tabulator#3033]
**Is your feature request related to a problem? Please describe.**
When using the functions to alter table data (e.g. updateOrAddData ) while the grid is sorted the grid will now be out of order (depending on data change) even though the column is still showing the grid is sorted by the column.  

**Describe the solution you'd like**
I'd like to be able to update and add data in the grid without replacing all data and have that data show up in the grid in sorted order based upon the current column sort order without the scrollbar being reset. 

**Describe alternatives you've considered**
The only workaround I can think of is to either replaceData on each update which seem to make the grid less performant for frequent updates (like a stock ticker, multiple updates a second for 1000+ items) or manually determine what the new grid position of an item is based on the sort and manually move the row after calling updateOrAddData.

**Comment by olifolkerd** [comment]
Hey @wildcat-cs 

The whole point of the update Data and add Data functions is to insert data into the existing layout of the table without triggering any rearrangement of data.

If you want to trigger a re-sort you can either use  the ***replaceData*** or ***setData*** function (the reasons these are less performant is because the retrigger filters and sorts which is exactly what you are after)

Alternatively you could trigger a resort at any point you like using:
```js
table.setSort(table.getSorters()); // resort the table with the existing sorters
```

Though if you are updating the table multiple times a second this may cause a significant performance drag.

Cheers

Oli :)

**Comment by wildcat-cs** [comment]
Hey @olifolkerd 

Thanks for the feedback, and trying your suggestions to see if they will meet our performance requirements but I'm still stumbling on the reason for the enhancement request.

replaceData would work assuming dataset is small enough (Which i'm hoping it is) but it doesn't persist selection making it quite obvious when updates are made to the grid and setSort resets the scroll bar.  

With the current API I'm thinking I need to use the returned promise from replaceData to reset the selection and hope that it is fast enough that the re-selection does not flicker on data replace.

Again, thanks for the help.  This seems like one of the best grids out there and hoping to get it to meet our needs.

**Comment by olifolkerd** [comment]
Hey @wildcat-cs 

Thanks for your kind words about tabulator, it is great to hear that people are enjoying using it.

The reason for closing this request was outlined above, that what you are asking for goes against the principal mode of operation for the functions you want updated. One of the main points of those functions is that they do not trigger sort and filters.

Retriggering sort, is a whole table data operation whether you are updating a single row or a whole tables data it all has to be resorted.

The replace data function is designed for in-place updating of row data. You shouldn't see much in the way of performance impact unless you are updating serious amounts of data, in which case it probably isn't advisable to be updating the table that fast anyway.

If you are in a scrollable table then most of the data will be off the screen anyway so from a human factors point of view a subsecond refresh rate for the data seems massively inefficient and unnecessary, especially when you are trying to transfer that much data over ajax. I would argue that it is very unlikely you be able to physically make the ajax requests as fast as you are hoping *(which is likely also part of the delay issue)*. A human wouldn't be able to keep track of data fluctuating that fast so what is the point in displaying it that way?

As it stands i'm just not convinced this would be broadly useful functionality to add, and i'm afraid i don't and edge case functionality to the table to avoid bloat of the code base.

Cheers

Oli :)
