### ISSUE TITLE
Pass array or struct to default options not documented

### ISSUE THREAD

**Issue by djiest** [olifolkerd/tabulator#3035]
**Website Page**
http://tabulator.info/docs/4.8/modules#default

**Describe the issue**
The documentation does not describe how to pass default options in a struct or array
e.g. 
```
Tabulator.prototype.defaultOptions.paginationSizeSelector=[2,4,8,16,32,64]
```
is not working, but it is unclear how this should be passed.

**Comment by olifolkerd** [comment]
Hey @djiest 

If you believe you have found an bug you will need to submit an issue using the [Bug Reporting Template](https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Possible+Bug&template=bug_report.md&title=)

It is pretty much impossible to offer you support from a single line of code. We need a JSFiddle or CodePen to see how your table is configured and runs.

Cheers

Oli :)

**Comment by djiest** [comment]
Hi
I wasn't reffering to a bug, the documentation is lacking some info

Regards
Djiest


Op zo 18 okt. 2020 13:31 schreef Oli Folkerd <notifications@github.com>:
