### ISSUE TITLE
Auto columns that contain dots in their names don't show data

### ISSUE THREAD

**Issue by birbilis** [olifolkerd/tabulator#3036]
With the CDN version of Tabulator, 
when I have auto columns (coming from JSON data loaded manually) that contain dot in their names, 
they don't show any data (only the column with the dot in its name). Just shows the column header and filter that is.

**Comment by olifolkerd** [comment]
Hey @birbilis 

This is not a bug, Tabulator uses [Dot Notation](http://tabulator.info/docs/4.8/columns#field-nesting) to reference nested data bu field name.

Dot Notation is a standard JS Practice and for this reason it is considered bad practice to use the "." symbol in object properties.

If you need to use dot notation in your field names the you can use the ***nestedFieldSeperatior*** option in the table constructor to change this character to something different and thus allow your field names to function correctly:

```js
var table = new Tabulator("#example-table", {
    nestedFieldSeparator:"|", //change the field separator character to a pipe
    autoColumns:true,
});
``

I hope that helps,

Cheers

Oli :)

**Comment by birbilis** [comment]
Thanks, data was coming like that in JSON from other system, managed to rename them earlier in the pipeline
