### ISSUE TITLE
JSON exporter doesn't respect downloadTitle of autoColumnDefinition

### ISSUE THREAD

**Issue by birbilis** [olifolkerd/tabulator#3038]
I use download and downloadTitle at my autoColumnDefinitions and they work fine when exporting to XLSX, but when exporting to JSON the downloadTitle doesn't seem to be respected (whereas any download: false is respected).

that is the keys in the JSON have same values as in the original data, not the titles that the user is seeing in the filtered view and that they'd expect to get

**Comment by birbilis** [comment]
also just noticed in the console this message, but changing downloadTitle to titleDownload didn't help with the names used in the exported JSON:

tabulator.min.js:2 downloadTitle definition property is deprecated, you should now use titleDownload
n._mapDepricatedFunctionality	@	tabulator.min.js:2
e	@	tabulator.min.js:2
t._addColumn	@	tabulator.min.js:2
(anonymous)	@	tabulator.min.js:2
t.setColumns	@	tabulator.min.js:2
t.generateColumnsFromRowData	@	tabulator.min.js:2
h._buildElement	@	tabulator.min.js:5
h._create	@	tabulator.min.js:5
e	@	tabulator.min.js:5
...
...

**Comment by olifolkerd** [comment]
Hey @birbilis 

If you believe you have found a bug you need to submit your issue using the [Bug Isssue Template](https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Possible+Bug&template=bug_report.md&title=)

It is very hard to offer you advice from a single line description and an error message, we need to see a JSFiddle that demonstrats your issue to understand more about how your table is setup.

What i would say is that the JSON downloader dosnt use the column titles at all, it uses the field properties of the column, which is based on the underlying of the structure. so changing the title in this case would have no affect at all.

If you wanted data to appear in the JSON that wasnt in the table then you would need to create a custom column build using a [mutator function](http://tabulator.info/docs/4.8/mutators#mutators) with a field name of the json property name you want. then i the column definition set the ***download*** property to ***true*** and the ***visible*** property to ***false*** to ensure it only shows up in the download and not on the table.

Cheers

Oli :)
