### ISSUE TITLE
data from JSON

### ISSUE THREAD

**Issue by firecz** [olifolkerd/tabulator#304]
Hello,

my table works when I include the data in the code, but when I want to get them from another server instead, it's stuck on "Loading Data".

I've seen this in another thread, but I have no idea how to do that...
> If you are trying to access the data from a site hosted on a different domain you will get a cross origin request error due to browser safety restrictions.
 You will need to use JSONP to make the request to a different domain.

**Comment by olifolkerd** [comment]
could you post a copy of your table constructor and your setData function if you are using it and i can post a relevant example for you.

Cheers

Oli

**Comment by firecz** [comment]
```
<script type="text/javascript">

$("#example-table").tabulator({
  height:"300px",
  fitColumns:true,
  columns:[
    {title:"Nick", field:"Name",  width:200},
    {title:"Quick Match", field:"fake1", formatter:function(value, data, cell, row, options){return data.LeaderboardRankings[0].CurrentMMR;}},
    {title:"Unranked Draft", field:"fake2", formatter:function(value, data, cell, row, options){return data.LeaderboardRankings[3].CurrentMMR;}},
    {title:"Hero League", field:"fake3", formatter:function(value, data, cell, row, options){return data.LeaderboardRankings[1].CurrentMMR;}},
    {title:"Team League", field:"fake4", formatter:function(value, data, cell, row, options){return data.LeaderboardRankings[2].CurrentMMR;}} 
  ]
});

var sampleData= [{
"PlayerID":1,
"Name":"Benthor",
"LeaderboardRankings":[
{
"GameMode":"QuickMatch",
"LeagueID":0,"LeagueRank":5527,
"CurrentMMR":2780
},
{
"GameMode":"HeroLeague",
"LeagueID":1,
"LeagueRank":null,
"CurrentMMR":2782
},
{
"GameMode":"TeamLeague",
"LeagueID":1,
"LeagueRank":2281,
"CurrentMMR":2558
},
{
"GameMode":"UnrankedDraft",
"LeagueID":null,
"LeagueRank":null,
"CurrentMMR":2174
}
]
}
]


$("#example-table").tabulator("setData", sampleData);
//$("#example-table").tabulator("setData", "https://api.hotslogs.com/Public/Players/1/Benthor_1644");

$(window).resize(function(){
  $("#example-table").tabulator("redraw");
});

</script>   
```

It works this way, but if I comment out the first row with setData, instead of the second one with the link (so, I just move the "//" one row higher), it's stuck at "Loading data", even though it should be the same.

**Comment by meaganjohnson** [comment]
I don't think Tabulator parses through data objects to figure out which items you want to use for the table. You need the server to either return the value of the `LeaderboardRankings` object directly, or do your own parsing before passing the data to Tabulator. I usually write a separate function to parse through the response object and save the values I need into new objects that match the format Tabulator expects.

**Comment by firecz** [comment]
Umm... I thought the data it would get from the link are exactly the same format as those that I successfully used in the variable in the test above.

**Comment by olifolkerd** [comment]
Hey,

Megan is right, Tabulator will not parse any further than the direct properties of the row object, anything that is to be set as a column needs to be a direct property of the row object, otherwise you will need to use a formatter to display it in the column.

Megan's approach of parsing through the object first to flatten it is the correct response. there is an example of this in issue #125 

Cheers

Oli

**Comment by firecz** [comment]
Glad that she's right, but I don't understand how does this relate to my issue :)
This doesn't really seem to answer my question on why it only works for me with internal input.

I already **did** use a formatter to display it in the column in the code above, which should deal with Tabulator's inability to access nested data.
But as I said, it doesn't work when trying to get data from external source, even though I expect their content and format to be the same.

Even when I comment out the calls for the nested data, so the only thing I ask for is the Name column, it **still** gets stuck at "Loading Data". Which looks to me like it doesn't want to work with my external data at all and the issue is in something else...

Flattened the sampleData, got over the "flattenRow undefined" error, figured out where to point the fields _again_ , but it just feels like an alternative to the formatter I already successfully used on the internal data.
Still no idea how to use that on the external data I'm trying to request from the api link...

**Comment by olifolkerd** [comment]
that suggest that you are not returning data in a format that Tabulator can understand, it must be a JSON encoded array of objects.

I would suggest using your browsers dev tool to inspect the response.

version 3.0 of tabulator has just entered public beta. it has enhanced error logging functionality in the console. it might be worth giving it a go on that.
Head over to http://olifolkerd.github.io/tabulator/news/ to see the latest features!

Cheers

Oli

**Comment by firecz** [comment]
With 3.0 dev tool says:
> The object does not allow the use of the forEach property or method.
> tabulator.min.js (1,16611)

**Comment by olifolkerd** [comment]
Looking at the code, that means that you are not passing an array into the ***setData*** function.

I have  just added an extra error handler to that function, if you download the latest version of 3.0 it will give you a detailed report in the console of what is being passed into the ***setData*** function if it is invalid.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey,

You will be happy to hear that Tabulator 3.2 has just been released, and with it the the ability to bind columns to nested data, simply use dot notation in the field name:
```js
{title:"age", field:"user.age"), //link column to age property inside user object
```

Full information can be found in the [Column Definition Documentation](http://olifolkerd.github.io/tabulator/docs/3.2/#field-nesting)

Cheers

Oli
