### ISSUE TITLE
Pagination height bug

### ISSUE THREAD

**Issue by GMihalkow** [olifolkerd/tabulator#3040]
**Describe the bug**
Recently updated from Tabulator 4.4.3 to 4.8.2 and noticed the following error in the console which you can see in the dev console within the **provided fiddle**.  This happens both with **local** and **remote** pagination options. 
I set the **height** property and it worked. But is this the intended behaviour? Shouldn't the table calculate the height based on the data and **paginationSize**? 

Also this clearly means that some of the examples in the **docs** are not working.

**Tabulator Info**
Tabulator version 4.8.2

**Working Example**
https://jsfiddle.net/GMihalkov/k4wbLuyo/6/

**To Reproduce**
1. Open the provided fiddle.
2. Open dev tools.
3. Observe the error.

**Expected behavior**
Data should appear in the table.

**Screenshots**
![image](https://user-images.githubusercontent.com/32070470/96336071-c2cf6a80-1085-11eb-9ed1-81cd9f9b6b40.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bit
 - Browser: Chrome
 - Version: 86.0.4240.75

**Additional context**
Nothing to add here.

**Comment by olifolkerd** [comment]
Hey @GMihalkow 

I have been unable to replicate this error in your JSFiddle, it works fine for me.

Does setting the ***virtualDom*** property to ***false*** fix the issue?

Cheers

Oli :)

**Comment by GMihalkow** [comment]
Yes it does work. Thanks!
Setting the **height** property also works.
I posted it here because I thought it was a bug.

**Comment by olifolkerd** [comment]
Is your browser zoomed out to 80% by any chance?

**Comment by GMihalkow** [comment]
No it's not. :/

**Comment by olifolkerd** [comment]
I would love to be able to replicate this. A couple of other users have experienced it but it works fine on every browser and device I try

**Comment by GMihalkow** [comment]
Well this is an interesting one isn't it? Could it be something from the OS? In contrast to you, it appears on all browsers and devices I test it on .

**Comment by GMihalkow** [comment]
I'm using Windows 10 Pro N 64 bit. Forgot to mention.

**Comment by olifolkerd** [comment]
@GMihalkow  same here all working fine for me running on Chrome  86.0.4240.111  on windows 10 64 bit. no error in the console, everything working fine

**Comment by olifolkerd** [comment]
but i would say that my console log donst match yours at all, could you screen print your console in the fiddle

**Comment by phme** [comment]
I have the same issue here, same error message with Chrome 86.0.4240.111 on Win10 64bit, no browser zoom, but (not sure it has anything to do with the issue at hand) display scaling to 125%. No issue on Firefox.
`virtualDom: false,` fixes it as well.

**Comment by olifolkerd** [comment]
Hey @phme,

I have just tried it with display scaling set to 125% and sadly i am still unable to replicate the error

:(

**Comment by phme** [comment]
Hi @olifolkerd, thanks for trying. If there's anything I can do to help pinpoint the issue, let me know. I'll try to look into the code today, but not sure I'll be able to figure it out :)

**Comment by olifolkerd** [comment]
Hey @phme  what i need more than anything else is a reproducible way to cause this, it will be a quick fix once i can reproduce it. I have already have one person submit a PR which supposedly fixed it, which i reluctantly included in the last release and it clearly hasn't resolved the issue, so until someone can provide a guaranteed way to reproduce it then i'm afraid not much will progress a i am not prepared to accept another PR on this until it can be proved to work.

I cannot get this issue to occur on any device / browser / OS that i try, and while there clearly is an issue, until i can replicate it there isnt anything i can do to help.

All help in reaching this goal would be appreciated

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey All,

I have managed to find a reproducible example of the issue which helped get to the bottom of what was going on, i have just pushed a fix for this to the 4.9 branch that should be released later this month.

Cheers

Oli :)
