### ISSUE TITLE
Copy Of Tabulator Not Preserving Columns

### ISSUE THREAD

**Issue by myeh98** [olifolkerd/tabulator#3042]
**Describe the bug**
Copy from the tabulator into excel does not preserve the columns. The table just turns into one giant column. 

**Tabulator Info**
- Which version of Tabulator are you using?
Tabulator v4.8.2 

**Working Example**
JSFiddle: https://jsfiddle.net/3btpLz5h/
A video attached if this doesn't work
[](url)
**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://jsfiddle.net/3btpLz5h/
2. Select multiple columns of a table
3. Command-c (mac), Ctr-c (windows)
4. Open excel and paste
5. See error

**Expected behavior**
I want tabulator to preserve the columns

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - OS: MacOS 10.15.4
 - Browser Chrome (mostly want this to work for React Tabulator)
- "react-tabulator": "^0.13.1", (@ngduc) 
 - Chrome Version 84.0.4147.105

**Additional context**

Thank you for your amazing library and for your great responsiveness maintaining it!!!

[Screen Recording 2020-10-19 at 12.41.39 AM.zip](https://github.com/olifolkerd/tabulator/files/5399340/Screen.Recording.2020-10-19.at.12.41.39.AM.zip)

**Comment by olifolkerd** [comment]
Hey @myeh98 

I afraid i am unable to replicate your issue, your JS Fiddle copies and pastes perfectly when i try it

Cheers

Oli
