### ISSUE TITLE
Autocomplete's list doesn't scroll down using the keyboard (selection highlighting disappears at the bottom)

### ISSUE THREAD

**Issue by birbilis** [olifolkerd/tabulator#3043]
**Describe the bug**
Autocomplete editor doesn't scroll the values list it shows when you move down in its list with the keyboard

**Tabulator Info**
latest (CDN) version

**Working Example**
see example at [editors doc page](http://tabulator.info/docs/4.8/edit#edit-builtin) or [here](http://tabulator.info/examples/4.8?#editable) 

**To Reproduce**
try the Location column (btw, one can't see that one is the one where they can try the autocomplete editor unless they open the source for that sample)

**Expected behavior**
expected the list to scroll with the keyboard, not the selection highlighting/rectangle to disappear as you move it down with the keyboard (also expected if hybrid navigation is set to wrap to the top of that vavlues' autocomplete list when having scrolled to the very bottom)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Edge-Chromium, Firefox
 - Version latest

**Comment by olifolkerd** [comment]
Hey @birbilis 

Thanks for pointing that out, i will get a fix in for that on the next patch release.

Cheers

Oli :)

**Comment by birbilis** [comment]
thanks for I'm using the CDN way, do I get the patch automatically, or will it be served later on at some major release only?

**Comment by olifolkerd** [comment]
Tabulator uses semantic versioning so there will be a patch release that contains a bunch of patches that will increment the patch number on the version, 4.8.x

So you would need to update your link to point to the new release

I tend to group patches together unless they are critical fixes so it will be a week or two before a patch release is published

Cheers

Oli

**Comment by birbilis** [comment]
Thanks, I think instead of the

> <link href="https://unpkg.com/tabulator-tables@4.8.2/dist/css/tabulator.min.css" rel="stylesheet">
> <script type="text/javascript" src="https://unpkg.com/tabulator-tables@4.8.2/dist/js/tabulator.min.js"></script>
 
that are suggested at [http://tabulator.info/docs/4.8/install](http://tabulator.info/docs/4.8/install)

I'll go for

> <link href="https://unpkg.com/tabulator-tables/dist/css/tabulator.min.css" rel="stylesheet">
> <script type="text/javascript" src="https://unpkg.com/tabulator-tables/dist/js/tabulator.min.js"></script>

to grab the fix automatically when available (seems to work fine and bring the latest available version)

I know I may run the risk of future major versions breaking something, but I guess Tabulator has matured enough in its API/design to make the risk not that high

**Comment by olifolkerd** [comment]
Hey @birbilis 

I have pushed a fix for this to the master branch and will include it in the next patch release.

Cheers

Oli :)

**Comment by birbilis** [comment]
Thanks Oli,
there seem to be some more strange behaviour (most probably bugs) with the autocomplete, will try to file separate bug reports for those
