### ISSUE TITLE
Add autocomplete header filter example

### ISSUE THREAD

**Issue by birbilis** [olifolkerd/tabulator#3044]
**Website Page**
[http://tabulator.info/examples/4.8?#filter-header](http://tabulator.info/examples/4.8?#filter-header)

**Describe the issue**
Should have a column at the header filter example to show the "autocomplete" too

**Comment by olifolkerd** [comment]
Hey @birbilis 

The purpose of the example page is to give a rough demonstration of the features available in Tabulator. if it were to include every available option it would simply be too bit to be navigable.

You will see that the editor section does in fact include the autocomplete editor which is the same thing as the header filter

Cheers

Oli :)

**Comment by birbilis** [comment]
Sorry, but the autocomplete editor example doesn't make it even clear it uses the autocomplete in the Location column (need to open its source to see it) and also doesn't allow one to refer to a working autocomplete header filter example that shows some behaviour they want to comment upon. So they're forced to make a fiddle for it. It's not that it's something rare to have, an autocomplete filter is one of the things people would first search for when trying examples to see what's available in terms of fuctionality.

Anyway, my cudos for Tabulator, amazingly powerful, just needs some common usage scenaria beter documented in my opinion

**Comment by olifolkerd** [comment]
Hey @birbilis 

Thankyou for your feedback.

Oli
