### ISSUE TITLE
support async persistence

### ISSUE THREAD

**Issue by brimimc** [olifolkerd/tabulator#3046]
**Describe the solution you'd like**
I would like to be able to make async calls in persistenceReaderFunc and persistenceWriterFunc in order to save the data in a database (behind an api call)

**Comment by olifolkerd** [comment]
Hey @brimimc 

This would be quite a big change to the system as it would essentially block the drawing of the table until the persistence function had been resolved, which on a slow internet connection could really impact the user experience. So im not sure if i would want to add this functionality to the table as it could create a poor/confusing user experience.

That being said, You can already do this if you structure your code differently.

There is nothing to stop you making an async call in the *** persistenceWriterFunc*** to save the persistence data else where as it currently stands.

To get that working for the reader side of things, i would recommend that you read the persistence data in asynchronously before your load your table *(outside of tabulator)* then when your async func resolves you store the returned data in a variable and then instantiate your table.

You can then use the ***persistenceReaderFunc*** function to read the tables persistence information from this variable.

Doing it this way would also give you control of what to display to the user while you are loading your table configuration.

I hope that helps.

Cheers

Oli :)

**Comment by brimimc** [comment]
Thanks @olifolkerd I had a similar thought late last night and will likely go that route. I just wanted to verify it was going to be as hard as I thought to support async as part of the persistence framework.
