### ISSUE TITLE
updateData with multiple rows having the same index

### ISSUE THREAD

**Issue by ybitso** [olifolkerd/tabulator#3048]
When attempting to run updateData() to a dataset that has multiple rows with the same index, it only updates the 1 row (the first row)

https://codepen.io/ybitso/pen/ExygYJX

**Expected behavior**
Update all rows with the same index value

**Comment by olifolkerd** [comment]
Hey @ybitso 

This is not a bug im afraid.

Row index's must be unique, they are intended for accessing a single row only.

This is literately the whole point of an index, it is a unique identifier for a role. You will find exactly the same principal in database design where the primary key can refer to only one row.

All the functions in Tabulator that deal with indexes as a lookup method will return only one row. It is integral to the way the table works.

This point is maid clearly in the [Data Documentation](http://tabulator.info/docs/4.8/data#overview) where it states that row indexes must be unique.

Cheers

Oli :)

**Comment by ybitso** [comment]
Thanks - thats what I expected
was just hoping for a group index
