### ISSUE TITLE
 uncaught typeerror: row.get element().classlist is undefined tabulator.es2015.js:20981

### ISSUE THREAD

**Issue by tianxingguo** [olifolkerd/tabulator#3049]
Uncaught TypeError: row.getElement().classList is undefined
    _selectRow tabulator.es2015.js:20981
    toggleRow tabulator.es2015.js:20902
    initializeRow tabulator.es2015.js:20855
    initializeRow tabulator.es2015.js:20849
    generateElement tabulator.es2015.js:4623
    Row tabulator.es2015.js:4596
    _setDataActual tabulator.es2015.js:2545
    _setDataActual tabulator.es2015.js:2543
    setData tabulator.es2015.js:2517
    setData tabulator.es2015.js:2501
    _setData tabulator.es2015.js:7145
    setData tabulator.es2015.js:7111
    componentDidUpdate ReactTabulator.js:346
    React 7
        commitLifeCycles
        commitAllLifeCycles
        callCallback
        invokeGuardedCallbackDev
        invokeGuardedCallback
        commitRoot
        completeRoot
    unstable_runWithPriority scheduler.development.js:255
    React 8
    loadRuleList RuleManager.js:471
    handleRefeshRule RuleManager.js:476
    React 16
    unstable_runWithPriority scheduler.development.js:255
    React 28
    js index.js:14
    Webpack 7

My column definition:

 ruleColumns =
        [
            {formatter:"rowSelection", width:5,titleFormatter:"rowSelection", hozAlign:"center", headerSort:false, cellClick:function(e, cell){
                    cell.getRow().toggleSelect();
                }},
            {width:5,hozAlign:"center",formatter:"rownum"},
            { title: "ID", field: "id",formatter:"textarea",hozAlign:"center",headerFilter:"input",width:150},
            { title: "Status", hozAlign:"center",field: "status",formatter:"textarea"},
            { title: "SQL", field: "sql",formatter:"textarea"},
            { title: "Sink", field: "actions" ,formatter:function(cell, formatterParams, onRendered){
                    if (cell.getValue() != null && typeof cell.getValue() != "string" )
                        return JSON.stringify(cell.getValue()) != null ? JSON.stringify(cell.getValue()) : "";
                    else
                        return cell.getValue() != null ? cell.getValue() : "";
                } },
            { title: "Options", field: "options" ,formatter:function(cell, formatterParams, onRendered){
                    if (cell.getValue() != null && typeof cell.getValue() != "string" )
                        return JSON.stringify(cell.getValue()) != null ? JSON.stringify(cell.getValue()) : "";
                    else
                        return cell.getValue() != null ? cell.getValue() : "";
                } },
            { formatter:deleteIcon,width:10 ,hozAlign: "center",
                cellClick:function(e, cell)
                { var result = window.confirm("Are you sure delete Rule: " + cell.getRow().getData().id + " ?") ;
                    if(result)
                    {   if (cell.getRow().getData().id != undefined)
                        {
                            fetch('/support-rule/rules/' + cell.getRow().getData().id , {
                                method: 'DELETE'
                            }).then(response => {
                                if (response.status == 400) alert("Rule name:" + cell.getRow().getData().id + " For incorrect or unparsable requests !");
                                if (response.status == 404) alert("Rule name:" + cell.getRow().getData().id + "cannot be found by the ID provided !");
                            }).catch(error => {
                                    console.log(error)
                                }
                            );
                            cell.getTable().deleteRow(cell.getRow());
                        }
                    }
                }
            }
        ];

after delete one row then the issue occurred.

**Comment by olifolkerd** [comment]
Hey @tianxingguo 

Please fill in the [Bug Report Issue Template](https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Possible+Bug&template=bug_report.md&title=) if you want to report a Bug.

It is really important that you provide all the info requested in that template in order for us to help you out. It is also important that you provide a link to a JS Fiddle that demonstrates your issue. Pasting large blocks of unformatted code into an issue make it impossible to read and impossible to help with as we cannot see the context of your code in action.

Cheers

Oli :)
