### ISSUE TITLE
How can I disable hover?

### ISSUE THREAD

**Issue by agustingrigoriu** [olifolkerd/tabulator#305]
Hi, I want to disable the hover from the table, I find it quite annoying. How can I do it without having to modify the css?

**Comment by olifolkerd** [comment]
you can set the ***selectable*** property to ***false*** in your tabulator constructor

```js
$("#example-table").tabulator({
	selectable:false,
});
```

Let me know if that helps.

Cheers

Oli

**Comment by agustingrigoriu** [comment]
Thanks for your answer! The problem is that I need to be able to select a row (I use `selectable:1` ) but I do not want the **hover** property when the cursor is over the row or the column title.

**Comment by olifolkerd** [comment]
Then you will need to look at overriding the :hover selectors in the tabulator.css

**Comment by agustingrigoriu** [comment]
Thank you, I have solved it by overriding the selectors.
