### ISSUE TITLE
add headerHozAlign option to column groups

### ISSUE THREAD

**Issue by marklofdahl** [olifolkerd/tabulator#3050]
**Describe the bug**
headerHozAlign seems to be ignored by column groups.

**Tabulator Info**
- 4.8

**To Reproduce**
https://jsfiddle.net/marklofdahl/tdL824wj/
Notice that "Foo" is left-aligned, even though headerHozAlign = 'center'

**Expected behavior**
headerHozAlign should not be ignored by grouped columns.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: All

Thanks!

**Comment by olifolkerd** [comment]
Hey @marklofdahl 

Thanks for getting in touch, this is not so much a bug as a feature request.

The [documentation](http://tabulator.info/docs/4.8/columns#groups) states which options are currently available for column groups .

That being said, your request makes a lot of sense so i will add it to the roadmap for the next minor release.

Cheers

Oli :)

**Comment by marklofdahl** [comment]
Thanks, that would be most helpful to have that feature.

**Comment by olifolkerd** [comment]
Hey @marklofdahl 

I have push a commit with this feature to the 4.9 branch that will be released later this month.

Cheers

Oli :)

**Comment by marklofdahl** [comment]
Great - thanks!
