### ISSUE TITLE
Scope for performance improvement with data grouping, sorting etc...

### ISSUE THREAD

**Issue by srixmk** [olifolkerd/tabulator#3051]
Hello Oli, first off, great job on creating Tabulator! It's a great piece of work and I'm seriously considering using it in place of SlickGrid, which I have been using for quite some time in a couple of projects. The only thing that's giving me pause is on the performance front with large volumes  (over 50,000 rows) of data.

I've hacked together a comparison page [here](https://plnkr.co/plunk/KzqmT5Vbi0mP1Xx3) based on one of the example pages from SlickGrid. This page generates a 100,000 records to populate a SlickGrid and a Tabulator (4.8.2) table. The initial data load for SlickGrid takes (on my i7 laptop) around 100 ms, versus around 800 ms for Tabulator. The data grouping takes around 50 ms for SlickGrid, versus 2000 ms for Tabulator. Expanding/collapsing any group is almost instantaneous in SlickGrid, but takes around 2 secs in Tabulator. Sorting on any column also is almost instantaneous in SlickGrid, while taking just that bit more in Tabulator. These numbers of course go up with a larger number of records. All of this is on my Linux laptop running Firefox 82. Tabulator  performs slightly better in Chrome but is still slower than SlickGrid by a factor of 6 or more.

Is this something that can be improved by any changes in managing the data or the configuration? If not, do you have any plans for further improvement of the performance?

Thanks...and congratulations on a great job again!

**Comment by olifolkerd** [comment]
Hey @srixmk 

Thanks for getting in touch, and thanks for your kind words, it is great to hear people are enjoying using Tabulator.

There are lots of ways that the performance of the table can be improved, but the settings needed depend heavily on the type of data you wish to process and the way you want it displayed. I must admit im a bit surprised by the load times you are experiencing as I have used far bigger tables without that much lag.

Every release comes with performance improvements targeted at specific areas of the table. The last release for example saw the release of the horizontal virtual DOM which has dramatically improved table load time for tables with 100's of columns.

The 5.0 release coming next year will include a complete rebuild of Tabulators virtual DOM systems which should see efficiency improvements across the board.

Cheers

Oli :)

**Comment by srixmk** [comment]
Hi Oli, thanks so much for looking into this and your detailed response, much appreciated!
I agree that the comparison page is  just hacked together quickly and not the ideal way to measure, but the page is more a reflection of my feel of the response when running them separately. Particularly the group expand/collapse operations visibly lag by a couple of seconds, even if I completely disable the slick grid.
In any case, thanks for the pointers you have given - I'll try playing around with some of the settings and see how that works out.
Thanks again, and looking forward eagerly to 5.0!!

**Comment by olifolkerd** [comment]
Hey @srixmk 

You will be happy to hear i have just pushed a few updates to the 4.9 branch *(which will be released later this month)* that improve the table loading speed by ***3x*** - ***4x*** and an update to the numeric sorter which improves its efficiency by ***8x***

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @srixmk 

4.9 is out now, have a play and see how you get on, on your demo it seems to slightly out perform slickgrid now when loading in data into the simple table.

It is still a lot slower when loading in the grouped data, but i didnt get a chance to look at that system. I will see if i can add some further improvements in the next patch update for that.

Cheers

Oli :)
