### ISSUE TITLE
Tabulator.prototype.defaultOptions.paginationSizeSelector not working

### ISSUE THREAD

**Issue by djiest** [olifolkerd/tabulator#3052]
**Describe the bug**
When setting the **paginationSizeSelector** via the defaultOptions, the dropdown does not show the elements of the array passed.

**Tabulator Info**
Tabulator v4.8.2

**Working Example**
This fiddle shows the difference in functionality between the two
https://jsfiddle.net/ypk7ohrb/

**To Reproduce**

1. Go to 'https://jsfiddle.net/ypk7ohrb/'
2. Click on 'Run'
3. Check the result pane
4. Open the dropdown on the two tables to see the diffence

**Expected behavior**
When using 
`Tabulator.prototype.defaultOptions.paginationSizeSelector=['1','2',true];`
I expect the dropdown to contain these three items

**Screenshots**
![image](https://user-images.githubusercontent.com/1582516/96840965-700dfe00-144b-11eb-8fd7-b0f2932ee8b0.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome,Firefox

**Comment by olifolkerd** [comment]
Hey @djiest 

Thanks for bringing this to my attention,

I have pushed a fix for this to the master branch and will include it in the next patch release.

Cheers

Oli :)

**Comment by djiest** [comment]
Thanks, I can confirm it now works as expected
