### ISSUE TITLE
Uncaught TypeError when calling updateColumnDefinition with topCalc/bottomCalc when virtualDomHoz is true

### ISSUE THREAD

**Issue by srixmk** [olifolkerd/tabulator#3055]
Here's the link to demonstrate the problem: [https://jsfiddle.net/39bwo6ms/3/](https://jsfiddle.net/39bwo6ms/3/
)
- "virtualDomHoz" is set to "true" 
- virtual DOM enabled by setting height on the table
- call "updateColumnDefinition" on a field to set "topCalc" or "bottomCalc" to "sum/min/max"
Column update fails with "Uncaught (in promise) TypeError: i is undefined"

Using Tabulator 4.8.2

**To Reproduce**
Run the fiddle from the link above and check the browser console. Also, the column total row appears but is not populated with the calculated value.

**Expected behavior**
The column total should appear at the top of the table.

**Desktop:**
 - OS: Linux (Ubuntu 18.04)
 - Browser: Firefox 82

**Additional context**
If "virtualDomHoz" is set to "false" it works fine.
If table height is not set, the console error still appears but the column total is computed and displayed. 
Calling updateColumnDefinition to set title or other values works, regardless of virtualDomHoz and height setting.

**Comment by olifolkerd** [comment]
Hey @srixmk 

The horizontal virtualDOM has only just been added as an experimental feature ahead of the 5.0 release to gain feedback from the community.

At the moment it does not support column calculations, though i can see this has been missed out in the documentation. I will update the documentation so this is clear.

Though to be fair you only really need ton include the horizontal virtual DOM in your table if you are having over about 60 columns in your table which is a fairly rare occurrence, most usage cases dont need it.

Cheers

Oli :)
