### ISSUE TITLE
Enabling virtualDomHoz and re-enabling visibility of column hidden during data change leads to missing data

### ISSUE THREAD

**Issue by fabscav** [olifolkerd/tabulator#3057]
**Describe the bug**
When columns that were hidden during a data change are re-introduced, the data for these columns is missing if the parameter `virtualDomHoz` is enabled. The visible data is being shifted, filling the gap and resulting in data/column mismatches. I suppose this is related to #3055?

**Tabulator Info**
- 4.8.2

**Working Example**
https://jsfiddle.net/4djrxctf/2/

**To Reproduce**
1. Run the jsfiddle.
2. Click on 'Toggle Column 1'. Column 1 should now be hidden.
3. Click on 'Refresh Data'.
4. Click on 'Toggle Column 1' again to re-introduce Column 1.
5. Column 1 is visible again but missing its data. Column 2 data is displayed under Column 1.

**Expected behavior**
Columns and data should be consistent and column data should be re-introduced with the column.

**Desktop (please complete the following information):**
 - OS: Windows 10 20H1
 - Browser: Firefox
 - Version: 83.0b2 Developer Edition

**Comment by olifolkerd** [comment]
Hey @fabscav 

Thanks for getting in touch,

The horizontal virtual DOM is very much an experimental option at the moment, that is only really intended for use on static tables. It is an initial offering to gauge user feedback on the efficiency of the enhancement.

In the version 5.0 release coming early next year there will be a fully function hoz vdom built in as standard.

The early release of the experimental version was actually built specifically to meet the needs of beekeeper studio and the European space agency, as you are looking to enhance the beekeeper platform i will see what i can do to get this in the next release. *(other updates to the hoz vdom are waiting to the 5.0 release)*

Cheers

Oli :)

**Comment by olifolkerd** [comment]
I have pushed a fix for this to the master branch and will include it in a patch release later today.

Cheers

Oli :)
