### ISSUE TITLE
select headerFilter not allowing input 

### ISSUE THREAD

**Issue by joaodlf** [olifolkerd/tabulator#3058]
**Describe the bug**
When using "select" as the headerFilter, the UI indicates that the user can use keyboard input in order to search the select box, but nothing happens on input, which can be quite misleading. 

**Tabulator Info**
- 4.8.3

**Working Example**
https://jsfiddle.net/Lm4c78jg/1/

**Additional context**
I could possibly be missing some sort of configuration here, but I can't seem to find anything in the docs. I can't be 100% sure, but I believe this was working on past versions of the library - If I am to believe colleague feedback, that is :).

**Comment by olifolkerd** [comment]
Hey @joaodlf 

The select editor does not allow you to input text into the editor it is simply a dropdown list. There is no indication that you can type in the editor at all. You can select the text string for the selected value but that is no different from text selection anywhere else in the table.

If you want to be able to look things up by typing into the editor then you want to be using the ***autocomplete*** editor not the select editor.

Cheers

Oli :)

**Comment by joaodlf** [comment]
Hi @olifolkerd,

Looking up "autocomplete" on the docs only mentions the ** row editor**, not the **headerFilter** I mentioned. What I mean exactly is this:
![image](https://user-images.githubusercontent.com/3275379/97553785-c93adc00-19cd-11eb-9141-bcbb7dccb3b8.png)

"filter column..." clearly shows a navigation caret.

In fact, if I am to load version 4.7.0 of the library (https://jsfiddle.net/xwLgk54v/1/), the feature does appear to work in order to filter the column:
![image](https://user-images.githubusercontent.com/3275379/97554049-23d43800-19ce-11eb-8003-0a6676105edf.png)

**Comment by olifolkerd** [comment]
Editors are header filters as is explained in the [Header Filter Documentation](http://tabulator.info/docs/4.8/filter#header)

It should not be editable at all as it is a select element and if it ever was then that was the bug, I will ensure that the cursor is hidden in future releases to prevent confusion

Cheers

Oli
