### ISSUE TITLE
fitDataStretch layout doesn't stretch last visible column in responsive mode

### ISSUE THREAD

**Issue by h4kst3r** [olifolkerd/tabulator#3059]
Hi  @olifolkerd,

**Describe the bug**
`fitDataStretch` layout has weird behaviour in `responsive` mode :
- 1st behavior : It doesn't stretch the last visible column but only the last one
- 2nd behavior : Sometimes it shrinks columns like in `fitColumns` layout
- 3rd behavior : In edge cases where you modify window width, it suddenly overflows the last column

**Tabulator Info**
4.8.3

**Working Example**
https://jsfiddle.net/oh4p17y9/

**To Reproduce**

_1st behavior_:
1. Go to JSfiddle
2. Narrow the result's viewport
3. Columns disappear as expected in `responsive` mode but the last visible column doesn't stretch

_2nd behavior_:
1. Go to JSfiddle
2. Widen the result's viewport
3. Columns appear as expected in `responsive` mode but shrinked and don't fit to data inside cells but only to `header`'s title

_3rd behavior (the weirdest)_ :
1. Go to JSfiddle
2. Widen the result's viewport until the last column appears
3. Run start again to reload the script and render the table as it does the first time
4. Narrow promptly the result's viewport to force columns to disappear
5. Widen promptly the result's viewport to make them reappear
6. There is now a scrollbar and the last column overflow the table's width

_You can repeat steps 4 & 5 to increase the last column overflow_

**Expected behavior**
I think in `responsive` mode `fitDataStretch` layout should behave as in _classic_ mode with the last visible column stretching to fill the remaining space.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Google Chrome
 - Version: 86.0.4240.111

**Additional context**
I tried to fix this issue tweaking the existing code but it doesn't work. `ResponsiveLayout` module is _sophisticated_ and tricky to manipulate (`show` and `hide` `Column`'s method callback `ResponsiveLayout.prototype.initialize` method which mess with visibility of `collapseHandleColumn` and possibility of inifinite loop but it's another issue i guess).

Finally I coded a new `fitDataStretch` to behave as expected and extended it. There are few (very few, i hope 😅) minor glitches depending on config and used features (e.g : with data trees it's necessary to trigger a `redraw` after `expand` and `collapse`). This code take account of column's options `visibility` and `responsive` order.

You can see the result here : https://jsfiddle.net/4juk3da1/ 

I can polish it and submit a PR if you want to.

Thanks for your work !

H.

**Comment by olifolkerd** [comment]
Hey @h4kst3r 

This is not so much a bug, but the intended functionality of the module, The responsive layout module works out when to hide columns based on their size, if you are consistently changing the size of the last column then it becomes increasingly difficult to work out what should be hidden when.

I would happily welcome a PR with a proposed solution if you think you can optimize this behaviour, as it is not something i would be looking to specifically change myself.

That being said please have a look at the complexity of your proposed solution as it has significantly increased the amount of processing needed for the table to render in that mode even when responsivity is not enabled, and i don't want to hurt other table configurations just to improve this one.

When submitting the PR, please take note that Tabulator is IE11 compatible and you are using several array manipulation functions that are not available in IE, so you may need to use more basic logic in places.

Cheers

Oli :)
