### ISSUE TITLE
Why don't  display loader when I click heade sort, and paging sort

### ISSUE THREAD

**Issue by yaxino** [olifolkerd/tabulator#306]
hi, 

pagination: 'remote',

Why don't  display loader when I click heade sort, and paging sort ?

How do you make it show?

thanks ,

**Comment by olifolkerd** [comment]
Hey,

At the moment the loader only shows when the ***setData*** function is called.

In version 3.0 of Tabulator, which is having its beta release later in the week, it will show the loader whenever an ajax request is made.

Cheers

Oli

**Comment by yaxino** [comment]
ok,  I am looking forward to it

**Comment by yaxino** [comment]
i have another things.


i change your code , Should you do the same?
![image](https://cloud.githubusercontent.com/assets/26379258/26143158/4a927aaa-3b16-11e7-87c1-76cb65c93b01.png)

**Comment by olifolkerd** [comment]
Hey,

You will be happy to hear that version 3.0 is now in beta release, and should address the issues you were having.

Head over to http://olifolkerd.github.io/tabulator/news/ to see the latest features!

Cheers

Oli

**Comment by yaxino** [comment]
hi， 
I just used it v3.0
but， the custorm 'paginator' not work.
and i debugger your ajax code, not find about the 'paginator' codes . 
```

$(obj.selector + ' .tabulator').tabulator({
                fitColumns: true,
                pagination: 'remote',
                ajaxURL: obj.url,
                ajaxParams: obj.postData,
                ajaxConfig: "POST",
                paginationSize: 15,
                paginator: function (url, pageNo, pageSize, ajaxParams) {
                    var sortor = $(obj.selector + ' .tabulator').tabulator('getSort');
                    url += '?page=' + pageNo + '&size=' + pageSize
                        + '&sort=' + (sortor.field ? sortor.field : '') + '&sortdir=' + sortor.dir
                        + '&token=' + g_s.user.Token;

                    return url;
                },
```

**Comment by olifolkerd** [comment]
Good spot! there was an issue with initializing the table with paged data, this is now fixed.

Thanks for letting me know :)
