### ISSUE TITLE
Multiple <th> without content overwrite each other

### ISSUE THREAD

**Issue by djiest** [olifolkerd/tabulator#3061]
**Describe the bug**
When using Tabulator with an HTML table with multiple empty `<th>`'s, these empty `<th>`'s overwrite each other

**Tabulator Info**
4.8.4

**Working Example**
See https://jsfiddle.net/x0yus4az/

**To Reproduce**
1. Go to https://jsfiddle.net/x0yus4az/
2. Click on 'run'
3. See 'result pane'
4. The table only has one column without a header, while 2 empty `<th>`'s are defined in the HTML code

**Expected behavior**
I expect to see a column without a header for every empty `<th>` defined in the HTML code. 

**Desktop (please complete the following information):**
 - Windows
 - Chrome, Firefox

**Comment by olifolkerd** [comment]
Hey @djiest 

There are two ways of importing table data into tabulator from an HTML table.

***EITHER***
You define your `th` cells with a value

**OR**
you define your columns in the ***columns*** array of the table definition and dont have header cells.


Each column of data in tabulator has to be linked to a filed value, when you use column definitions you defined this in the ***field*** property of the column definition. When you set the column headers in 'th' then Tabulator creates these field names by converting the titles to properties for the row data.

When you have multiple empty hr tags Tabulator has no way to bind that data back to a column value.

Cheers

Oli :)

**Comment by djiest** [comment]
Hey Oli,

Sorry to bother you again,, but I am stuck. Can you help me out? 

See this fiddle https://jsfiddle.net/etgm7z08/1/, with a predefined table in HTML

This is what I get
![image](https://user-images.githubusercontent.com/1582516/98012098-fab20e00-1df8-11eb-8eaa-79fcd8a114dd.png)

This is what I want
![image](https://user-images.githubusercontent.com/1582516/98012145-0bfb1a80-1df9-11eb-9bf1-17fd94041348.png)

What am I doing wrong?

Regards
Joost

**Comment by olifolkerd** [comment]
I think you are getting rather confused on how to setup Tabulator.

Is there a reason you are importing your data from an html table? it is far easier to configure the table if your simply pass the data in an array. with your current approach your magnifying glass and "i" symbol wont be clickable they will simply be displayed. the import from HTML is really only included to help legacy systems migrate to Tabulator, if your are starting afresh i would strongly recommend just [loading your data from a JavaScript array](http://tabulator.info/docs/4.8/data#array), this would then allow you to use column definitions fully and give you access to full table functionality.

As i mentioned above, it is an either/or scenario, you either define your columns using the table headers OR you define them using column definitions, you cant do both.

If you must import your data from an html table then you need to set your column configurations as properties on the `th` tags:
```html
<th tabulator-formatter="html">preview</th>
```

Cheers

Oli :)

**Comment by djiest** [comment]
Hi Oli,

I have a legacy App that I want to enrich with Tabulator. I was hoping as first step to use the HTML table as starting point. Turns out this won't be working.

I'm going to look if I can replace the HTML table with passing the data in an array

Regards
Joost

**Comment by olifolkerd** [comment]
Or you could simply look at removing the table header row before passing it in to Tabulator

**Comment by djiest** [comment]
Sorry to bother you again, but I feel really confused if not stupid now.

I've taken one of your examples and removed the `th`. In the constructor I've defined the columns. The table is generated as a  Tabulator table, but the rows are empty. What am I doing wrong?

https://jsfiddle.net/21dhknyc/

**Comment by djiest** [comment]
Never mind, I was able to get what I want with the following! Hoorah!

`{ formatter:"infoIcon", width:20, hozAlign:"center", headerSort:false,tooltip:function(cell){ return cell.getRow().getData().description; } }`

**Comment by olifolkerd** [comment]
@djiest as a quick hint there is a `getData` function on the cell component that is a shortcut for the `getRow().getData()` approach :)
