### ISSUE TITLE
setValue() does not add cell to Edited Cells

### ISSUE THREAD

**Issue by farbohydrate** [olifolkerd/tabulator#3063]
**Describe the bug**
cell.setValue() does not seem to give the cell an 'edited' flag, so editing a cell programmatically is not seen or tracked as an edit.

**Tabulator Info**
Tabulator v4.8.4

**Working Example**
JS Fiddle: https://jsfiddle.net/farbohydrate/7gfm31tu/12/

**To Reproduce**
1) Click on 'setValue(20)' button which will change the cell value from 5 to 20.
2) Click on 'Edited Cell Count' which will alert the # of cells in table.getEditedCells(). This will be zero.

Is this expected behavior? If so, is there any way to force a cell to be flagged as Edited?  We are trying to implement a feature where a user can "bulk edit" a cell in all selected rows, but we need to track if the cells were edited or not. It seems like editing a cell via setValue() should also be considered an edit.

**Comment by olifolkerd** [comment]
This is not a bug but the intended function of the table.

The edited flag is used specifically to track user interaction with the table and is only set when a user directly edits a cell, setting the value on the cell using the ***setData*** command does not use an editor and is therefor not counted as an edit.

This is the same across a wide variety of the tables systems where tracking information (validation, history , edit callbacks etc) is only tracked through user interaction with the cells. this way the programmer can make amends to the data (as may be needed for updates etc) without triggering the systems that track user changes.

If you want to track this type of update you would need to do this outside of Tabulator

Cheers

Oli :)
