### ISSUE TITLE
Simple frozen colum is lagging on chrome

### ISSUE THREAD

**Issue by SheepFromHeaven** [olifolkerd/tabulator#3064]
**Describe the bug**
Setting up a dynamic table with a frozen column leads to a phenomena, where the scrolling on chrome (especially on mobile) lead to lagging of the first column (not the header though)

**Tabulator Info**
- Which version of Tabulator are you using?
4.8.4 (lts)

**Working Example**
http://tabulator.info/examples/4.8?#frozen-col
https://codepen.io/SheepFromHeaven/full/ZEOMbjP

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Open the codepen on a small device in chrome
2. Scroll the content left and right
3. Look at the first (frozen) column

**Expected behavior**
The column stays fixed and does not move, as it does in other browsers.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 86

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: Android 10
 - Browser Chrome
 - Version 86

**Comment by SheepFromHeaven** [comment]
Btw.: I am happy to help fix this, I you could lead me in the right direction 🙂

**Comment by olifolkerd** [comment]
Hey @SheepFromHeaven 

Thanks for getting in touch, This is actually a well known issue on mobile devices that lack the processing power of desktop browsers.

The way the current frozen column system is built it requires a lot of processing power to keep the rows in place as you scroll and mobile browsers defer the processing till the move has finished which causes the gitteryness.

The frozen column system is due a complete rebuilt in the 5.0 release coming out early next year which should resolve the issue.

Cheers

Oli :)
