### ISSUE TITLE
Cell no longer support object as value

### ISSUE THREAD

**Issue by namibian** [olifolkerd/tabulator#3066]
Until version 4.7.2, I was able to store an object as a cell value (and use a custom formatter to  set the displayed value). This is a major break in functionality for my application.

**Comment by olifolkerd** [comment]
There has been no such change.

If you believe you have found a bug then you need to submit an issue using the bug issue template, it will prompt you to provide all the information we need to help you out.

The most important of these is a JS fiddle that demonstrates your issue so we can understand how your table is configured.

I use Tabulator with numbers cells using objects and they all still work for me on the latest version

Cheers

Oli
