### ISSUE TITLE
rowNumber formatter

### ISSUE THREAD

**Issue by Paraplegix** [olifolkerd/tabulator#307]
Little issue with the rownumber formatter, example here : https://jsfiddle.net/x702jspq/5/

If you update data with `updateOrAddData` , and you are using the rownumber formatter, the row number of updated data will be changed to the maximum row number, even if its the first row of the table.

In the example just press the `addRow` multiple time to notice the odd behavior

Sorting the column make the row number correct again

Keep up the good work ! Can't wait for 3.0 !

**Comment by olifolkerd** [comment]
Hey,

The rownumber formatter has been completely rewritten for 3.0 so that shouldnt be an issue any more.

Keep your eyes peeled for an announcement about 3.0 im hoping to release the public beta this weekend when i have finished the documentation!

**Comment by olifolkerd** [comment]
Hey,

You will be happy to hear that version 3.0 is now in beta release, and should address the issues you were having.

Head over to http://olifolkerd.github.io/tabulator/news/ to see the latest features!

Cheers

Oli
