### ISSUE TITLE
Table styles not overridden for calculator row

### ISSUE THREAD

**Issue by johnpitchko** [olifolkerd/tabulator#3072]
I have a Tabulator table that applies the **table-dark** Bootstrap4 theme: 
```
<div id="monthly-performance-table" class="table-dark"></div>
```

I am including the (latest?) Tabulator CSS for Bootstrap4:
```
<link href="https://cdnjs.cloudflare.com/ajax/libs/tabulator/4.8.4/css/bootstrap/tabulator_bootstrap4.min.css" rel="stylesheet">
```

When adding a **bottomCalc** calculation, the dark styling is not applied to the calculator row:
<img width="666" alt="Screen Shot 2020-11-11 at 10 07 25 PM" src="https://user-images.githubusercontent.com/7190681/98898308-903d4580-246a-11eb-9abe-4e8aeeecfac8.png">

Looking at the elements, I see that an **!important** selector is added that overrides the dark theme and applies a white background to the calculator row:
<img width="351" alt="Screen Shot 2020-11-11 at 10 10 14 PM" src="https://user-images.githubusercontent.com/7190681/98898394-c37fd480-246a-11eb-8cfa-2f1851db1cdc.png">

If I disable this selector, the styling is applied correctly:
<img width="645" alt="Screen Shot 2020-11-11 at 10 11 26 PM" src="https://user-images.githubusercontent.com/7190681/98898436-dd211c00-246a-11eb-945e-801b414e24db.png">

Would it be possible to update the stylesheet? Thank you.

**Comment by olifolkerd** [comment]
Hey @johnpitchko 

Thanks for the heads up

I have pushed a fix for this to the 4.9 branch that will be released later this month.

Cheers

Oli :)
