### ISSUE TITLE
Ability to show entities in columns instead of rows

### ISSUE THREAD

**Issue by Mahesha999** [olifolkerd/tabulator#3078]
I have a products data as json array.
Say for example, I have lots of features of three mobiles. How can I show them on web page using [tabulator], in a way say something like [this](https://www.gsmarena.com/compare.php3?idPhone1=10386&idPhone2=10237&idPhone3=10261)? 

The difficulty is that tabulator follows usual table format (horizontal rows contains entity and vertical columns contain different attributes of those entities). That is, each mobile feature will occupy new column. Instead, I want only three columns for three mobiles and each feature to occupy new row. I can transpose the json array that I have, but then I guess I will loose the functionality to format columns in tabulator. For example, in tabulator, you can specify certain column to have [star ratings](http://tabulator.info/examples/4.8?#frozen-col) as cell formatter. I can no more use this feature, right? As my column will contain different features for same mobile instead of same feature for different mobiles (say ratings number for different mobiles). Is there any way to achieve this with tabulator? 

If this is not possible, is there any way to specify styling (star rating, image, progress bar etc) for specific row, instead of for particulat column?

**Comment by olifolkerd** [comment]
I'm afraid that Tabulator does not have pivot table functionality at the moment.

The only way to achieve this would be to make a cut cell formatter that changed its output based on the row index

**Comment by Mahesha999** [comment]
> cut cell formatter

Do you mean [this](http://tabulator.info/docs/4.0/format#:~:text=Tabulator%20also%20allows%20you%20to,for%20the%20row%20being%20formatted.), by cut cell formatter?

Also any suggestion about plugin supporting such functionality?

**Comment by olifolkerd** [comment]
If I'm honest I don't think you want to be using any plugin, the layout is very simple you could easily build this layout yourself with a little html CSS and JavaScript. There isn't much to it
