### ISSUE TITLE
updateData vs updateRow

### ISSUE THREAD

**Issue by wp4nuv** [olifolkerd/tabulator#308]
Hello,

I'm trying to update row data using the function `updateData` yet internally it keeps referring to `updateRow`:

> `Uncaught TypeError: Cannot read property 'data' of undefined
>     at $.(anonymous function).(anonymous function).updateRow (https://bln.dev/Loans/js/tabulator.js:1206:74)
>     at $.(anonymous function).(anonymous function).updateRow (https://bln.dev/Members/js/jquery-ui.js:415:25)
>     at https://bln.dev/Loans/js/tabulator.js:1272:10
>     at Array.forEach (native)
>     at $.(anonymous function).(anonymous function).updateData (https://bln.dev/Loans/js/tabulator.js:1270:9)
>     at $.(anonymous function).(anonymous function).updateData (https://bln.dev/Members/js/jquery-ui.js:415:25)
>     at HTMLDivElement.<anonymous> (https://bln.dev/Members/js/jquery-ui.js:508:39)
>     at Function.each (https://bln.dev/members/js/jquery.min.js:657:23)
>     at init.each (https://bln.dev/members/js/jquery.min.js:266:17)
>     at init.$.fn.(anonymous function) [as tabulator] (https://bln.dev/Members/js/jquery-ui.js:494:9)`

My guess is that since I'm not following `updateRow` format the update fails. This is the instruction I'm attempting to run:

> `$.ajax({
> 							url: base + '/loans/user_documents/setDocumentType/'+row.doc_id+'/'+selected_action,
> 							type: "GET"
> 						}).done(function (d) {
> 							var s = JSON.parse(d);
> 							if(s.result == 1 || s.result === true){
> 								var r = cell.parent();
> 								cell.addClass("success");
> 								var n = r[0].attributes.getNamedItem('data-id').value;
> 								$("#table-bln-tabulator").tabulator("updateData",[{id:n,requires_date:s.requires_date}]);
> 							}
> });`

Could this be a scope issue?  Thanks for your work btw, it has been very helpful here!
Pedro M.

**Comment by wp4nuv** [comment]
A quick update: when I switch to using `updateRow` the update works fine.

**Comment by Paraplegix** [comment]
Hi,
What version of tabulator where you using ?
Seem's to me like you are not using the lastest version of tabulator available (2.12), try upgrading your version. Your code should work as it is (with `updateData`).

`updateData` is only a wrapper that call `updateRow` for each element of the array you pass, so the reference from the former to the latter is normal.
