### ISSUE TITLE
Ajax error message timeout option

### ISSUE THREAD

**Issue by Shreyas-BS** [olifolkerd/tabulator#3081]
Hi,
I am looking for a customisable error message timeout option.

So I have a custom error message like this
<img width="1051" alt="Screenshot 2020-11-18 at 1 27 30 PM" src="https://user-images.githubusercontent.com/31754538/99502050-94092480-29a2-11eb-862f-b35b3ca53a45.png">

And after 3 seconds the error message disappears and i will be left with a screen like this which looks awkward for the end user
<img width="1049" alt="Screenshot 2020-11-18 at 1 27 04 PM" src="https://user-images.githubusercontent.com/31754538/99502102-a2574080-29a2-11eb-906b-892ec1f74892.png">

So I went through the tabulator source code and found that in the ajax.js file there is a timeout feature which displays the error message for 3000 milliseconds and it could not be changed unless explicit modification of code by a developer. 

`setTimeout(function(){
					self.hideLoader();
				}, 3000);`

I am looking for a feature where this error message does not vanish at all and/or have more time before the timeout gets triggered. So could you add this feature something like an ajaxErrorTimeout parameter which helps in custom timeout feature and also for disabling the timeout feature(infinite timeout).

**Comment by olifolkerd** [comment]
Hey @Shreyas-BS 

I have pushed an update to the master branch with this feature, it will now be available on the `dataLoaderErrorTimeout` option. This will be included in the 5.1 release later today.

Cheers

Oli :)
