### ISSUE TITLE
Warning incorrectly shown when using formatterParams

### ISSUE THREAD

**Issue by andrewleith** [olifolkerd/tabulator#3082]
**Describe the bug**
(1). When using `formatterParams`, I am seeing a warning about null values even though none are provided.
(2). When opening the dropdown, the backing value (int) is displayed rather than the text provided.  If you select a value and set it back to itself, next time you open the dropdown, it correctly shows the text instead of the int.

**Tabulator Info**
- 4.8.4

**Working Example**
YOU MUST include a link to a JS Fiddle or Codepen that demonstrates the problem, it is very hard to diagnose an issue from a simple description.
https://jsfiddle.net/pLnj02v5/1/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
(1)
1. Go to https://jsfiddle.net/pLnj02v5/1/
2.  Look in the console to see warnings.
**Expected behavior**
No warnings should be given.

(2)
1. Go to https://jsfiddle.net/pLnj02v5/1/
2. Click a cell in the color column.
3. Cell shows int 
**Expected behavior**
It should show the string.    At this point if you select the same value again, and then click the cell again, you won't see the integer but only the text.

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome
 - 86.0.4240.183

**Comment by olifolkerd** [comment]
Hey @andrewleith 

Thanks for the headsup, i have pushed a fix for this to the 4.9 branch which should be released later today

Cheers

Oli :)

**Comment by andrewleith** [comment]
(1) is confirmed as fixed, thanks.

For (2), did you see that? Do you consider it a bug? Want me to fill out a separate issue?
