### ISSUE TITLE
(Tabulator - editor - progress) progress it is not possible to set the value equal to 100%

### ISSUE THREAD

**Issue by abvas** [olifolkerd/tabulator#3083]
** Please describe the error **
 I noticed that if you use editor - progress it is not possible to set the value equal to 100%.

** Tabulator Information **
Tabulator 4.8.4

** Working example **
A link to the JSFiddle OR Codepen is not required, as you have the same bug on the demo page in the "Examples" section - "Editable Data".

** Expected Behavior **
The ability to stretch the progress bar to its full width. But this cannot be done. There is always a blank space at the end.

** Screenshots **
![hRB16 (1)](https://user-images.githubusercontent.com/47285364/99847879-70e89b80-2b81-11eb-8188-cec6a5991271.png)

** Desktop (fill in the following information): **
 - OS: Windows 10
 - Browser: chrome
 - Version: 87

**Comment by olifolkerd** [comment]
Hey @abvas 

Thanks for letting me know.

I have pushed a fix for this to the 4.9 branch which will be released later today.

Cheers

Oli :)
