### ISSUE TITLE
Version 4.9 Released - Performance Improvements... (and some info on version 5.0)

### ISSUE THREAD

**Issue by olifolkerd** [olifolkerd/tabulator#3085]
Hi All,

The version 4.9 release is now available and includes a range of table wide performance improvements including

#### Data Loading Performance
Data loading has now been optimised, and you should see around a ***3x - 4x*** reduction in processing times when data is loaded into a simple table. This will be particularly noticeable in data sets with a large number of rows.

#### Numeric Sorting
The number sorter has been rebuilt to improve performance when working with simple integer and floating point numbers. By default it will no longer try and do any string manipulation on numbers being sorted (eg removing thousand separators etc). This has resulted in a ***7x*** reduction in numeric sort times.

#### Calculation Column Scrolling
The column calculation module has been tweaked to improve horizontal scroll performance when column calculation rows are visible.

#### Cell Container Initialization
Initialization of event binding and styling on cells now happens without the need to generate the cell contents.

### Version 5.0 Release Update
Now that version 4.9 has been released I will wait a couple of weeks to catch up on any minor bug fixes etc that come in and will then begin work on the big 5.0 release.

This is going to involve a wholesale refactor of the codebase to take advantage of the tree shaking functionality of ESM to improve package size and to make way for the implementation of unit testing across the library.

This is no small update, there will be wide ranging efficiency improvements across the system as well as a range of new features and functionality, to get an overview of the coming updates, have a look at the two 5.0 columns on the [Tabulator Roadmap](https://trello.com/b/rPZ0Yavc/tabulator-roadmap).

#### Unit Testing Contributors
Once I have finished the initial module refactor *(at the start of December)* I will be needing the help of the community to build out a series of unit tests for the system so they can be included in the 5.0 release. If this is something that you would be up for getting involved in then please leave a message below and I will create an issue to discuss things in more detail when things are ready.

#### Release Date
I am currently aiming to have version 5.0 release in either Feb or March 2021, and there will be pre-release versions before then to get community feedback.

Cheers

Oli :)

**Comment by sydesb** [comment]
Thank you for your fantastic work !

**Comment by uptonking** [comment]
love your data grid so much. good job!!!
My most wanted feature for v5 is column span(like cell merging), please.

**Comment by phaleth** [comment]
Hello Oli,

Are there still plans to support IE11 with promise polyfill for the versions 4.9, 5.0 and onwards?

I'm getting error as shown in the attached picture with 4.9.1.

**Comment by alimp5** [comment]
I must thank you Tabulator team.
Thanks to members, developers, testers. :X :X :X 
Thanks a lot.

**Comment by olifolkerd** [comment]
@phaleth Tabulator does still support IE11,

If you are experiencing problems can i ask that you create an issue to track the resolution, this issue is more for general release discussion.

As it would happen an issue for your particular bug was raised and a fix has been merged into master. it will be released with other patches later in the week.

Cheers

Oli :)

**Comment by Jojoshua** [comment]
@olifolkerd, since you are doing a large refactor with 5 you might consider doing it in typescript. I've found it very helpful with large projects.

**Comment by olifolkerd** [comment]
Hey @Jojoshua 

Thanks for the suggestion,

I'm afraid it is now a bit to late for that, iv'e been hard at work for the last few month and i am about two weeks away from the making a public 5.0 alpha release available for community feedback.

I will be honest with you though, while i can see the benefits of Typescript in certain projects, overall i'm not that big a fan of it and prefer the less constrained aspects of vanilla JavaScript. As the JavaScript language evolves i can see it starting to absorb some of TypeScripts features, just as it did with the query selecting magic of JQuery so i prefer to wait it out till it is part of the official language spec.

That being said, i am very happy for those that want to use Tabulator in TypeScript to do so, and happy to work with the community to make that as smooth a process as possible.

Keep your eyes peeled for a 5.0 release notification soon.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Version 5.0 alpha is now available for feedback, checkout #3286 for more info

**Comment by boumboum** [comment]
Hi, Is this great project stalled?

**Comment by olifolkerd** [comment]
Hey @boumboum

It has been, but it will be picking up again this month. unfortunately i've been completely snowed under at work the last few months which has stopped me having any time to work on Tabulator

But the good news is that the big projects finished last week so i will now be getting straight back on things. 

Version 5.0 is almost ready to go, there need to be some updates to the dependant libraries and a few tweaks following user feedback and it should be good to go.

Once version 5 is out the door, it should be much easier for others to contribute to tabulator (it is one of the main reasons for the huge refactor of the 5.0 code base) which should help make things more sustainable going forwards

Cheers

Oli :)
