### ISSUE TITLE
Header Filter using "select" returning just "true" instead of values

### ISSUE THREAD

**Issue by proautodinc** [olifolkerd/tabulator#3086]
Using the header filter : "select" (headerFilter:"select", headerFilterParams:{values:true})
All values in the dropdown show "true" instead of the values.

Tabulator Info
4.9.0

Working Example
https://codepen.io/Bodock/pen/QWEeyqR
see column 'Name'.

This is a fantastic library. Thank you.

**Comment by olifolkerd** [comment]
Hey @proautodinc 

Thanks for the heads-up, i have just release a fix for this in the new 4.9.1 release.

Cheers

Oli :)
