### ISSUE TITLE
Custom sorter: `aRow` and `bRow` are undefined

### ISSUE THREAD

**Issue by EdwinVanRooij** [olifolkerd/tabulator#3092]
**Describe the bug**
In a custom sorter, the `aRow` and `bRow` parameters do not seem to be passed, even though this is described in http://tabulator.info/docs/4.9/sort -> "Custom Sorters".

**Tabulator Info**
4.9 (latest)

**Working Example**
https://jsfiddle.net/edwinvanrooij/f8x7tu03/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Click on the first column to sort it
2. Notice the `undefined, undefined` logs.

**Expected behavior**
The aRow and bRow parameters to be filled.

I would be willing to look into the issue and create a PR if that's desirable. 

Thank you in advance, and a general thank you for this amazing (surprisingly extensible) library!

**Comment by EZWrighter** [comment]
Confirm, I have the same behavior.  I am pulling from the CDN https://unpkg.com/tabulator-tables@4.9.1/dist/js/tabulator.min.js and see the following call to the sorter function: o.modules.sort.sorter.call(this,e,t,void 0,void 0,o.getComponent(),i,n)

**Comment by EZWrighter** [comment]
In sort.js you commented out the assignment of the aRow & bRow components on line 333 in function - Sort.prototype._sortRow = function(a, b, column, dir, params)  Just uncommenting those should fix the issue.

**Comment by olifolkerd** [comment]
Hey @EdwinVanRooij 

I have pushed a fix for this to the master branch and will include it in this weeks patch release.

Cheers

Oli :)
