### ISSUE TITLE
BUG: Editing wide tables with virtDomHoriz: true causes table to 'jump' back to the middle

### ISSUE THREAD

**Issue by rathboma** [olifolkerd/tabulator#3094]
**Describe the bug**
Using this dataset:

```js
var tabledata = [{"id":1,"a1":"1","a2":"1","a3":"1","a4":"1","a5":"1","a6":"1","a7":"1","a8":"1","a9":"1","b1":"1","b2":"1","b3":"1","b4":"1","b5":"1","b6":"1","b7":"1","b8":"1","b9":"1","c1":"1","c2":"1","c3":"1","c4":"1","c5":"1","c6":"1","c7":"1","c8":"1","c9":"1"},{"id":2,"a1":"2","a2":"2","a3":"2","a4":"2","a5":"2","a6":"2","a7":"2","a8":"2","a9":"2","b1":"2","b2":"2","b3":"2","b4":"2","b5":"2","b6":"2","b7":"2","b8":"2","b9":"2","c1":"2","c2":"2","c3":"2","c4":"2","c5":"2","c6":"2","c7":"2","c8":"2","c9":"2"}]
```
Set up a tabulator instance that allows editing and enables `virtDomHoriz`
Scroll all the way to the right (past like ~b5)
Try to edit a field

Watch the table 'jump' back to the middle.

**Tabulator Info**
- 4.8 and 4.9

**Working Example**
https://jsfiddle.net/v0Lxtune/1/

**Expected behavior**
Field editing should happen normally. Disable virtDomHoz to see this.

See for context: https://github.com/beekeeper-studio/beekeeper-studio/issues/433

**Comment by rathboma** [comment]
@olifolkerd happy to take a look at this if you can give me a high level idea of where to look

**Comment by olifolkerd** [comment]
Hey @rathboma 

Sorry for the delay in getting back to you on this one, i had a couple of insanely busy weeks at work and didnt have a chance to do much else.

Im catching up on Tabulator stuff this week and will get a patch release out next weekend to resolve this.

Cheers

Oli :)

**Comment by rathboma** [comment]
Thanks mate!

I know the feeling, things are super busy here too!

**Comment by olifolkerd** [comment]
Hey @rathboma 

I have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)
