### ISSUE TITLE
Cell selection and copying

### ISSUE THREAD

**Issue by nl095059** [olifolkerd/tabulator#3095]
**Requirement**
We have a requirement to allow users to select data at a cell level. As most people are familiar with this functionality in spreadsheets, from a look and feel point of view it would be nice to mimic excel/libreoffice calc, etc.

**Proposed solution**
Allow the selection of a single range across cells/rows using either the mouse or via keyboard interaction.
Draw a border around the selection
Highlight the cells within the selection (Originating cell of selection a different colour)
Allow a clipboard copy to copy the cell contents (Optionally include headers via existing config)

**Additional info**
I have already implemented most of this on my forked repo, but as this is a bigger change I wanted to make sure that the requirement fits with tabulators goals. We currently have no requirement for pasting the copied content, or multiple range selection, so it does feel like it falls short from a full implementation of cell level functionality.

I will tidy up the branch and raise a PR. Please feel free to be critical of the feature request/my implementation :-)

**Comment by nl095059** [comment]
Added the following PR for debate/comments #3096

**Comment by xinxilas** [comment]
Is the mentioned Celler virtualdom ready on latest version ? 
The single cell selection already possible?

**Comment by tobiasBora** [comment]
Any news on this feature? I’d love to have it.

**Comment by joebonneau** [comment]
I would also love to have this feature. I'm considering implementing it myself, but don't want to repeat any work. 

@olifolkerd  Can you comment on whether this is currently on your roadmap and/or if it's currently being worked on? Apologies for tagging you if you'd prefer that I didn't (will keep it in mind for next time either way).

**Comment by olifolkerd** [comment]
Hey All,

Cell range selection is comming in the 5.6 release that i am hoping to have out in the next couple of weeks.

Cheers

Oli :)
