### ISSUE TITLE
Typos at release notes for 4.9

### ISSUE THREAD

**Issue by birbilis** [olifolkerd/tabulator#3098]
**Website Page**
http://tabulator.info/docs/4.9/release

**Describe the issue**

> You can now navigate the list in the select editor by typing the value u are loking for on the keyboard while the editor is open, the edtior will do a string comparison of the typed word against each label to find a labe that starts with the typed word and will then scroll to that item.

u - you
loking - looking
labe - label

**Comment by olifolkerd** [comment]
Thanks for the headsup,

this will be fixed in today s update

Cheers

Oli :)
