### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by birbilis** [olifolkerd/tabulator#3099]
**Website Page**
http://tabulator.info/docs/4.9

**Describe the issue**
The upgrade guide link inside the above page should point to http://tabulator.info/docs/4.9/upgrade (points to installation instead which is where the installation section also points to)

**Comment by olifolkerd** [comment]
Hey @birbilis 

Thanks for the headsup,

This will be fixed in todays update.

Cheers

Oli :)
