### ISSUE TITLE
Setting paginationInitialPage=n>1 with remote pagination prevents ajax fetching

### ISSUE THREAD

**Issue by yujiberra** [olifolkerd/tabulator#3101]
**Describe the bug**
Setting paginationInitialPage to a value other than 1 when using remote pagination results in an error `Pagination Error - Requested page is out of range of 1 - 1: 2` on the console, and no ajax call is made to fetch the data.

**Tabulator Info**
4.9.1

**Working Example**
https://stackblitz.com/edit/tabulator-tables-iz47wk

**Expected behavior**
The expectation would be for an ajax request to be made to fetch the designated page.

**Comment by olifolkerd** [comment]
Hey @yujiberra 

I have pushed a fix for this to the master branch and will include it in the patch release this evening

Cheers

Oli :)

**Comment by yujiberra** [comment]
Awesome, thanks Oli!
