### ISSUE TITLE
rowSelection columns checkbox are not in sync

### ISSUE THREAD

**Issue by Armaldio** [olifolkerd/tabulator#3103]
**Describe the bug**
Multiple columns with rowSelection are not synced.

**Tabulator Info**
4.9

**Working Example**
https://codesandbox.io/s/old-shadow-lh1xn?file=/src/columns.js

**To Reproduce**
- 1.
	- 1. Click on a checkbox on the left
	- 2. Header on the left is not in sync
- 2.
	- 1. Click on the header checkbox
	- 2. Rows checkbox on the left are not in sync

**Expected behavior**
All checboxes must be in sync

**Screenshots**
![xEQwcodXx9](https://user-images.githubusercontent.com/3089715/100712688-703adb00-33b3-11eb-937d-2b4b3eefefd5.gif)

**Desktop (please complete the following information):**
 - OS: W10
 - Browser Brave
 - Version 1.17.73 Chromium: 87.0.4280.67

**Comment by olifolkerd** [comment]
Hey @Armaldio 

The built in row selection formatter was only ever intended to be used in one column at a time.  It will not work in your configuration.

I would consider having multiple selection tick boxes to be bad UI design so i would not be looking to add that functionality into the table, but i will update the documentation to make it clear that this is the case.

Cheers

Oli :)

**Comment by Armaldio** [comment]
Thanks a lot!

I understand your point. I will just add that having the tickbox on the first column **and** on the last column make it easier to select a row when there are many columns and you have to scroll to the end of the row.
You can then directly tick the box instead of going back to the beginning of the row

Last question: can I do my own version using custom formatters/etc.. or are there behaviour internal to tabulator ?

**Comment by olifolkerd** [comment]
It is the internal behaviour in the row selection module that will be the issue, it has special functionality to bind to elements created by that formatter to track updating of those elements when the selection state changes, but it is only designed to  handle one element at a time per row.
