### ISSUE TITLE
Unable to `setColumnLayout(...)` with invisible columns & `virtualDomHoz: true`

### ISSUE THREAD

**Issue by EdwinVanRooij** [olifolkerd/tabulator#3104]
**Describe the bug**
Tabulator won't set a new table layout correctly when the new layout contains invisible columns and `virtualDomHoz` in the constructor is set to `true`. The returned message is `Uncaught TypeError: Cannot read property 'visible' of undefined`.

**Tabulator Info**
4.9

**Working Example**
https://jsfiddle.net/2t93zwrk/

**To Reproduce**
1. Go to the js fiddle.
2. Open the console
3. Execute "table.setColumnLayout(columns);"

**Expected behavior**
A return message of "true" in the console, indicating that the new column layout was applied.

(_I don't think browser info is relevant here_)

Edit: I'm willing to look into it & help fix the issue. First I'll wait for your reply, since it may take me a while to get into it and possibly you can see the problem much faster than me. Just let me know if you're too busy!

**Comment by olifolkerd** [comment]
Hey @EdwinVanRooij 

Thanks for the headsup, i have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)

**Comment by EdwinVanRooij** [comment]
Great, thank you!
