### ISSUE TITLE
When 'layoutColumnsOnNewData = true' resets cellEdit History when row.pageTo() 

### ISSUE THREAD

**Issue by Joao-deOliveira** [olifolkerd/tabulator#3105]
**Describe the bug**
Having the history active, multi-pages and pagination active, when getting the page and scrolling to it to, that resets the '**cellEdit**' history (removes all ...) and also provokes **component.getElement().style** **is undefined**

**Tabulator Info**
4.9.1

**Working Example**
https://jsfiddle.net/JoaoDeOliveira/9jxzvm6b/111/

**Expected behavior**
cellEdit History should be preserved as rowAdd, ...

**Additional context**
the need to get the page visible and scroll to it, to show the user the result of the 'redo' / 'undo'

**Comment by olifolkerd** [comment]
This is a limitation with the way the table handles paginated data,

I would consider it bad UX to be persisting that sort of information between different paginated data sets, if you need to track that information you can easily store the edit information in an external variable before switching page.

Cheers

Oli :)

**Comment by mormitech** [comment]
hi all!


> This is a limitation with the way the table handles paginated data,
> 
> I would consider it bad UX to be persisting that sort of information between different paginated data sets, if you need to track that information you can easily store the edit information in an external variable before switching page.
> 
> Cheers
> 
> Oli :)

I had the same issue which is really bothering:

https://jsfiddle.net/ue62cjrk/

Repro steps:

- Edit the only editable cell
- see console: prints array with getEditedCells() containing the only element
- click on page 1 to trigger page rerender
- check console again: value change is persisted but isEdited flag is lost so console output array with getEditedCells() is empty

Imho this is an inconsistent behavior. Either drop all changes and the isEdited alongside or preserve both.

What do you think?

**Comment by mormitech** [comment]
also, this only happend when layoutColumnsOnNewData = true which makes this towards being an actual bug even more.

If this "clear edited history" would be intentional as @olifolkerd mentioned why does it only occure when layoutColumnsOnNewData = true? With = false all changes and isEdited flags are kept.

**Comment by mormitech** [comment]
in fact I found another setting that breaks isEdited 😢 
I'll open another ticket, not sure it this is monitored anymore anyway..

**Comment by olifolkerd** [comment]
@mormitech please do open another ticket. This issue was opened on version 4.9 we are now on 6.2. the code base has literally been completely rewritten since the issue was first raised so it will most certainly have a different cause now

**Comment by mormitech** [comment]
@olifolkerd thanks for the quick reply, I already went ahead and opened a new one.
