### ISSUE TITLE
Mutator function on common fields doesn't works as expected

### ISSUE THREAD

**Issue by Codeout256** [olifolkerd/tabulator#3108]
**Describe the bug**
Mutator functions on common fields not working properly

**Tabulator Info**
4.8

**Working Example**
https://jsfiddle.net/ohzeyvga/22/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Fill in the time details for column "Finish time" column "A", column "C"
2. Calculation on time difference doesn't returns exepected value.

**Expected behavior**
Fields binded to mutator should provide the operation value.

**Desktop (please complete the following information):**
 - OS: WIndows
 - chrome, safari

**Comment by olifolkerd** [comment]
Hey @Codeout256 

This is not a bug,

This is the intended functionality of the table.

When a cell is edited, only its mutator is run, the table has no idea what goes on inside mutators so would not know when to trigger any other mutators that may depend on that cells value.

In this instance the correct approach would be to call the `setValue` function on the cell component for the caluclation cell using the `cellEdited``` callback on the edited cell, this will trigger a re-run of the calculation mutator.

Cheers

Oli :)
