### ISSUE TITLE
display glitch in frozen right column when fast scrolling

### ISSUE THREAD

**Issue by kkkisme** [olifolkerd/tabulator#3109]
**Describe the bug**
frozen right columns,drag the horizon scrollbar quickly, then will see the right frozen column title shown  wrong,like blow:
![image](https://user-images.githubusercontent.com/18638401/100848456-1a058f00-34bc-11eb-9229-9443666a14cb.png)

**Tabulator Info**
version 4.9.1

**Working Example**
[https://codepen.io/kkkisme/pen/ZEpbBbm?editors=1010](https://codepen.io/kkkisme/pen/ZEpbBbm?editors=1010)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to [https://codepen.io/kkkisme/pen/ZEpbBbm?editors=1010](https://codepen.io/kkkisme/pen/ZEpbBbm?editors=1010)
3. Scroll right quickly
4. See the frozen right column title

**Expected behavior**
the frozen right column title show completely

**Desktop (please complete the following information):**
 - Windows 7; Chrome 87

**Comment by kkkisme** [comment]
![image](https://user-images.githubusercontent.com/18638401/103066076-15cc1d80-45f3-11eb-9f0d-7d99ae485c7d.png)
hi oli, thanks you great work for this project.

here is a new bug here ,i am updated this example
when the table has 'vertical scroller' ,'horizen scroller' and 'frozen right column',the right top corner display glitch, it will see the other column title under right forzen column。it should add a patcher dom to cover this hole。

**Comment by olifolkerd** [comment]
If you think you have found another big then please create a new issue. It is strictly one issue per bug otherwise it will be impossible to track any progress on resolving them

Cheers

Oli

**Comment by MetallianFR68** [comment]
I also encountered this issue
Here's a video.
The bakcground can be seen on top right because the header doesn't expand to the full right
https://user-images.githubusercontent.com/6049266/182470724-ca95062b-6dc2-42c5-9ac3-7b72cf99f057.mp4

**Comment by ramen-curator** [comment]
我也遇到了这个问题

**Comment by ramen-curator** [comment]
@kkkisme 
thanks in advance
How did you end up dealing with this issue?

**Comment by olifolkerd** [comment]
This has now been resolved on the 5.4 branch that will be released in a weeks time.

Cheers

Oli :)
