### ISSUE TITLE
Pagination mix of text & icons

### ISSUE THREAD

**Issue by stack-its** [olifolkerd/tabulator#311]
I'm trying to add a font awesome icon to the pagination buttons, but when I do that in the script, I just get the default text.  Is there a way to force the fa tags to render as html ?

**Comment by olifolkerd** [comment]
Hey,

The buttons are generated by the localisation system, so any manual changes will be overwritten.

You can't get round this in the current release, but version 3.0 which has just been released on public beta allows you to pass HTML into the localization strings for the pagination buttons.

Head over to http://olifolkerd.github.io/tabulator/news/ to see the latest features!

Cheers

Oli
