### ISSUE TITLE
Dropdown values not displayed correctly in certain cases

### ISSUE THREAD

**Issue by andrewleith** [olifolkerd/tabulator#3110]
**Describe the bug**
In certain cases, when using dropdowns (`formatterParams`) in the table, tabulator shows the backing value instead of 
the string value.

**Tabulator Info**
- 4.9.1

**Working Example**
https://jsfiddle.net/mp15obek/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Click on a color cell.

**Expected behavior**
When dropdown opens, the value should remain set to the text value of the color.  Instead, it shows the underlying value.

**Screenshots**
Int showing instead of string:
![image](https://user-images.githubusercontent.com/823749/100873743-fe799480-3479-11eb-8d0d-d53a414fd6f1.png)

Should do this:
![image](https://user-images.githubusercontent.com/823749/100873873-236e0780-347a-11eb-9ec5-88efd9931fe3.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome 86

**Additional context**
If you change the data so it doesnt have ints, it seems to fix the problem, but its pretty hacky.
See this fiddle with manually fixed data:
https://jsfiddle.net/mp15obek/1/

**Comment by kkkisme** [comment]
i think beacause  'colorFormatterParams' Object 's key aways be to string, not a number. so this is not a bug of tabulator ,is a 'feature' of javascript language

**Comment by olifolkerd** [comment]
Hey @andrewleith 

@kkkisme is correct, this is because JavaScript treats array keys as strings and the values stored against rows are numbers, therefor the comparison used to check they are the same fails.

In this case the correct approach would be to to use the array format for the values list rather than the object format:

```js
var colorFormatterParams = [
        {
          label:"blue",
          value:1,
        },
        {
          label:"red",
          value:2,
        },
        {
          label:"green",
          value:3,
        }
      ];
```
