### ISSUE TITLE
"select" headerFilter set an incorrect selected value when opening a dropdown

### ISSUE THREAD

**Issue by LarryCrow** [olifolkerd/tabulator#3113]
**Describe the bug**
"select" headerFilter set an incorrect selected value when opening a dropdown

**Tabulator Info**
Tabulator version is 4.9.1

**Working Example**
[Stackblitz](https://stackblitz.com/edit/tabulator-issue?file=index.js)
[Doc example](http://tabulator.info/examples/4.9?#filter-header) (I've copied the example and remove unnecessary code, but the bug reproduces there as well)

**To Reproduce**
* Open dev console
* Click on the "gender" column filter and select the "Female" value. The table is sorted as it should be.
* Click on the filter one more time, the "Male" option is preselected.
* Check console. When we chose the "Female" options, the filter value is a string. But when the "Male" option is selected, the filter value property is an array.
![image](https://user-images.githubusercontent.com/37259001/101118606-05d8a380-361c-11eb-8873-c5fe6dad17fc.png)

**Expected behavior**
When a dropdown opens, a correct value is preselected.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser chrome
 - Version 87

**Additional context**
It seems there is a problem within `parseFunction` from `js/modules/edit.js`. I hope the call stack I got might be helpful
```
parseItems (edit.js:900)
showList (edit.js:1239)
(anonymous) (edit.js:1417)
```

**Comment by olifolkerd** [comment]
Hey @LarryCrow 

Thanks for the headsup,

A fix for this has been pushed to the master branch (it was related to another issue #3107), it will be included in the patch release this evening.

Cheers

Oli :)
