### ISSUE TITLE
Disable all user interaction and visually 'disable' the table

### ISSUE THREAD

**Issue by EdwinVanRooij** [olifolkerd/tabulator#3115]
**Is your feature request related to a problem? Please describe.**
In my application, I sometimes perform operations which take a lot of time. During this time, I show a bootstrap loading spinner and the UI thread is blocked right after that. The spinner can be overlooked, in which case the user tries to go on with their tasks on the page, clicking rows in the table, scrolling down, scrolling to the right, changing column widths, etc. All of these actions will immediately take effect once the UI thread is not blocked anymore; flashing many actions at once, shocking the user. 

**Describe the solution you'd like**
An option to temporarily disable all (user) interaction with the table, essentially "disabling" the table temporarily, blocking all clicks/resizes/scroll events/etc. Something like `table.disableUserInteraction();` and `table.enableUserInteraction();` (or a toggle).

**Describe alternatives you've considered**
I've looked at jQuery suggestions like `$("#example-table").prop('disabled', true);` and the docs (searching by "disable"), github issues here, but couldn't find anything similar to my desired solution.

**Comment by olifolkerd** [comment]
Hey @EdwinVanRooij 

I would say this is rather an edge usage case and not something i would be looking to include built in to Tabulator.

That being said it would be really easy for you to implement your end. simply put tabulator inside a containing element, and an absolutely positioned element that is the placeholder (that is set to display none by default).

Then when you want to disable the table simply apply a class to the container that makes the placeholder visible and sets CSS`pointer-events:none;` on the table to prevent users interacting with the table,

Cheers

Oli :)

**Comment by EdwinVanRooij** [comment]
Understandable, thank you for the suggested solution!
