### ISSUE TITLE
dataTreeSelectPropagate does not work when tree is collapsed

### ISSUE THREAD

**Issue by larslemberg** [olifolkerd/tabulator#3117]
**Describe the bug**
Using dataTree:true and dataTreeSelectPropagate:true the selection and deselection of checkboxes does not propagate to children rows if the dataTree is collapsed.

**Tabulator Info**
I have verified this on Tabulator versions 4.8 and 4.9

**Working Example**
jsFiddle is at [https://jsfiddle.net/llemberg/dvr5mq8e/81/]
(https://jsfiddle.net/llemberg/dvr5mq8e/81/)

**To Reproduce**
On JS Fiddle:
1. Expand the 'Photos' and 'Color' tree branches'
2. Select 'Photos' checkbox, see the selection correctly propagates to all children.
3. Collapse 'Photos' branch
4. Deselect 'Photos' checkbox
5. Expand 'Photos' branch, see all children are still selected

**Expected behavior**
I expected all checkbox selections to propagate to the children whether the tree is collapsed or expanded

**Screenshots**
No applicable screenshots

**Desktop (please complete the following information):**
 - OS: Linux Mint 20
 - Browser: Chrome
 - Chrome Version: 87.0.4280.66 (Official Build) (64-bit)

**Smartphone (N/A):**
 - Device: Samsung S20
 - OS: Android 10
 - Browser: Chrome
 - Version: 86

**Additional context**

**Comment by olifolkerd** [comment]
Hey @larslemberg 

Thanks for getting in touch,

I have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)
