### ISSUE TITLE
A thank you

### ISSUE THREAD

**Issue by flleeppyy** [olifolkerd/tabulator#3119]
Thank you devs, so so much for creating & maintaining this amazing library. It has saved me so much pain with account and token tables. I always had the mindset of "use as little librarys as possible; USE JUST JQUERY; MUST DO EVERYTHING FROM SCRATCH!!!" then i realized that was a dumb mindset to have. I tried to make something similar to this library before acknowledging its existence, and the outcome was not pretty so I tried looking for some table plugins, and came across this one and It's SO much easier to use than the hell i created.

Thank you!

**Comment by olifolkerd** [comment]
You are most welcome!
