### ISSUE TITLE
Edited row callback sets data to text rather than keeping as a number

### ISSUE THREAD

**Issue by dpatel20** [olifolkerd/tabulator#312]
I have just started using Tabulator and have a question/concern. I have a column set up as follows:
```
columns:[
...
          {title:"TEAM1SCORE", field:"TEAM1SCORE", sorter:"number", width:"7%", headerFilter:true, editor:"number"},
...
          ]
```
And I have a callback when the row is edited which I use to create a Parse object:

```
$("#example-table-demo").tabulator({
            cellEdited:function(id, field, value, oldValue, data, cell, row){
                //data - the data for the row

                data.className = "Fixtures_and_results";
                var fixObj = new Parse.Object(data);
                console.log(fixObj);
                fixObj.save();
            },
        });
```
This works great for string columns but for the above mentioned number column, the `data` has the value as a string rather than a number (i.e. `TEAM1SCORE:"60"`) - which means the `save()` to the server fails. Is there a way to get the data to set the field/column as number - i.e. `TEAM1SCORE:60`?

**Comment by olifolkerd** [comment]
Hey,

You will be happy to hear that version 3.0 is now in beta release, and should address the issues you were having.

Head over to http://olifolkerd.github.io/tabulator/news/ to see the latest features!

Cheers

Oli

**Comment by dpatel20** [comment]
Hi Oli - I tried v3.0 but get the same issue. I updated a number column (as per my example above) and had the following callback. But when I check the console log it shows the field as string instead of a number. Have I misunderstood what you meant?

```
cellEdited:function(cell){
	//cell - cell component
	console.log(cell.getRow().getData());
},
```

**Comment by olifolkerd** [comment]
Hey,

Sorry that was my bad, i misunderstood you there. i have adjusted the ***number*** editor so it now returns numbers instead of strings.

Let me know if that does the trick!

**Comment by dpatel20** [comment]
Works great, thanks!
