### ISSUE TITLE
download regard decimal separator

### ISSUE THREAD

**Issue by surfNicolas** [olifolkerd/tabulator#3120]
in my tabulator columns, I use the formatter and formatterParams:
formatter: "money"
formatterParams:
decimal: ","
precision: 2
thousand: "."

I expect the download also with the decimal separator like defined in the formatterParams, but its always the ".". The formatting of CSV, Excel and PDF is wrong! A calculation with the values is not possible.

**Comment by olifolkerd** [comment]
Hey @surfNicolas 

Formatters are only for rendering data in the actual table, if you want to change the data when it is output from the table then you need to be using [Accessors](http://tabulator.info/docs/4.9/mutators#accessors)

Cheers

Oli :)
