### ISSUE TITLE
updateColumnDefinition method update column mistake

### ISSUE THREAD

**Issue by kkkisme** [olifolkerd/tabulator#3121]
**Describe the bug**
when the column is a leaf node of column group, use table  instance method `updateColumnDefinition`.then the columns will render wrong
```
table.updateColumnDefinition('field', {...opts})
```

**Tabulator Info**
4.9.1

**Working Example**
[https://codepen.io/kkkisme/pen/rNMWmWj?editors=1010](https://codepen.io/kkkisme/pen/rNMWmWj?editors=1010)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to [https://codepen.io/kkkisme/pen/rNMWmWj?editors=1010](https://codepen.io/kkkisme/pen/rNMWmWj?editors=1010)
2. wait 2 second , will see the `n` column disappear, but is not expected

**Expected behavior**
update column definition correctly

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser  Chrome 87

**Comment by olifolkerd** [comment]
Hey @kkkisme 

Thanks for getting in touch

The update column definition function was not really intended to be used on grouped columns, but i can see your usage case.

In this instance i have have added a console warning to explain that this functionality is not available at the moment, and i have added it to the roadmap for the next release to ensure that this function works on grouped columns.

Cheers

Oli :)
