### ISSUE TITLE
rowStartMove callback inside table

### ISSUE THREAD

**Issue by janvrska** [olifolkerd/tabulator#3124]
I would find useful, that there will be callback, when someone start moving row inside table. when property **movableRows** is set to true. This callback(event) should be cancelable and in this callback there should be row parameter for indetifiing which row user trying to move

I´d like to have this feature in future, because it helps me a and some other peoples a lot.

**Comment by olifolkerd** [comment]
Hey @janvrska 

Could you explain how this feature would be used, i am unsure exactly what you would need this feature for?

Cheers

Oli :)

**Comment by janvrska** [comment]
Hi, I need this for canceling moving row when row has data of some type. Because I want that user wont be able to move that row. And nothing better than this come up to my mind.
