### ISSUE TITLE
Error on loading Tabulator table in IE11

### ISSUE THREAD

**Issue by KayakFisher205** [olifolkerd/tabulator#3125]
**Describe the bug**
After Upgrading from 4.8.4 to 4.9.0 (also 4.9.1 tested), I have an issue with Tabulator loading. It is erroring out on a line of code in tabulator.js
if (this.renderMode === "virtual") {

			var otherHeight = Math.floor(this.columnManager.getElement().getBoundingClientRect().height + (this.table.footerManager && !this.table.footerManager.external ? this.table.footerManager.getElement().getBoundingClientRect().height : 0));

**Tabulator Info**
- 4.9.1

**Working Example**
https://codepen.io/Bart205/pen/mdrOzrz?editors=1111 
(Have to export locally to load in IE11)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Open with Chrome/Edge and confirm the graph displays
2. Export locally, open the DIST folder, and open the index.html file in IE11. 
3. Right Click and Inspect Element (may have to refresh to see the error in the Console)
4. See error -Unspecified Error, Tabulator.js (5544,4)

**Expected behavior**
I would expect Tabulator work the same in IE11 and Chrome, for versions 4.9.x. I didn't see think in the release notes that mentioned any changes that might effect IE11.

**Screenshots**
![Chrome](https://user-images.githubusercontent.com/71768711/101930873-5614b000-3b9e-11eb-8ede-dee3c4cdc6bd.png)
![IE11](https://user-images.githubusercontent.com/71768711/101930879-5745dd00-3b9e-11eb-9623-e6aaf1b6cbd9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Browser Chrome ( 87.0.4280.88), IE11 (11.572.19041.0), Edge (87.0.664.60)

**Comment by olifolkerd** [comment]
Hey @KayakFisher205 

Thanks for the headsup,

I have just pushed a fix for this to master and will include it in the 4.9.2 release later this week.

Cheers

Oli :)

**Comment by phaleth** [comment]
Thank you alot, Oli.

Sorry about not posting issue myself.

**Comment by corinabioinformatic** [comment]
Is it any update about this? My Tabulator version 4.9.3 carry the same issue (empty table, just headers). I just  followed the instructions from the website to run the editor table example: http://tabulator.info/docs/4.9/edit

**Comment by olifolkerd** [comment]
This issue is closer as the problem it referenced has been fixed.

If you a still experiencing an issue, it will either be due to a configuration error or another bug.

In either case you will need to create a new issue and post a link to a JS fiddle that demonstrates the issue

**Comment by corinabioinformatic** [comment]
Thank you @olifolkerd  for the fast answer!
Actually I fixed it. I just suggest to extend the code in the "View source" script under the table.

There is a parameter that it is not declared in the Tabulator variable. Once is added, the information appeared. 
That was caused my confusion. Would I suggest to add the full script in order to not miss that 'data: tabledata' parameter?

Then the example code will be something like this (approx):

```
//Create Date Editor
var dateEditor = function(cell, onRendered, success, cancel){
    //cell - the cell component for the editable cell
    //onRendered - function to call when the editor has been rendered
    //success - function to call to pass the successfuly updated value to Tabulator
    //cancel - function to call to abort the edit and return to a normal cell

    //create and style input
    var cellValue = moment(cell.getValue(), "DD/MM/YYYY").format("YYYY-MM-DD"),
    input = document.createElement("input");

    input.setAttribute("type", "date");

    input.style.padding = "4px";
    input.style.width = "100%";
    input.style.boxSizing = "border-box";

    input.value = cellValue;

    onRendered(function(){
        input.focus();
        input.style.height = "100%";
    });

    function onChange(){
        if(input.value != cellValue){
            success(moment(input.value, "YYYY-MM-DD").format("DD/MM/YYYY"));
        }else{
            cancel();
        }
    }

    //submit new value on blur or change
    input.addEventListener("blur", onChange);

    //submit new value on enter
    input.addEventListener("keydown", function(e){
        if(e.keyCode == 13){
            onChange();
        }

        if(e.keyCode == 27){
            cancel();
        }
    });

    return input;
};

//define some sample data
var tabledata = [
    {id:1, name:"Oli Bob", age:"12", col:"red", dob:"",car:true},
    {id:2, name:"Mary May", age:"1", col:"blue", dob:"14/05/1982",car:true},
    {id:3, name:"Christine Lobowski", age:"42", col:"green", dob:"22/05/1982",car:true},
    {id:4, name:"Brendon Philips", age:"125", col:"orange", dob:"01/08/1980",car:true},
    {id:5, name:"Margret Marmajuke", age:"16", col:"yellow", dob:"31/01/1999",car:true},
];

//Build Tabulator
var table = new Tabulator("#example-table", {
    height:311,
    data: tabledata,
    columns:[
        {title:"Name", field:"name", width:150, editor:"input"},
        //{title:"Location", field:"location", width:130, editor:"autocomplete", editorParams:{allowEmpty:true, showListOnEmpty:true, values:true}},
        {title:"Age", field:"age", sorter:"number", hozAlign:"left", formatter:"progress", width:140, editor:true},
        //{title:"Gender", field:"gender", editor:"select", editorParams:{values:{"male":"Male", "female":"Female", "unknown":"Unknown"}}},
        //{title:"Rating", field:"rating",  formatter:"star", hozAlign:"center", width:100, editor:true},
        {title:"Date Of Birth", field:"dob", hozAlign:"center", sorter:"date", width:140, editor:dateEditor},
        {title:"Driver", field:"car", hozAlign:"center", editor:true, formatter:"tickCross"}//,

    ]//,
});
```
