### ISSUE TITLE
Autocomplete showListOnEmpty not displaying values after clearing header filters

### ISSUE THREAD

**Issue by tomheaps** [olifolkerd/tabulator#3131]
**Describe the bug**
After clearing all header filters with `table.clearFilter(true)` and clicking back in a header filter set to `headerFilter: "autocomplete",
      headerFilterParams: {
        values: true,
        sortValuesList: "asc",
        allowEmpty: true,
        showListOnEmpty: true
      }` the list of values does not re-populate unless you press backspace whilst in the header filter input.

**Tabulator Info**
4.9

**Working Example**
[codepen](https://codepen.io/tomheaps/pen/ExgmaWG)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to [my codepen](https://codepen.io/tomheaps/pen/ExgmaWG)
2. Click in the header filter under Color column and the list of possible values of all colors is displayed
3. Now click on the **Clear Filters** button underneath the table
4. Click back in the header filter under Color column and no list of possible values is displayed (unless you press backspace whilst in the header filter input)

**Expected behavior**
After clearing all header filters, clicking back in the input for the header filter should display list of all possible values as it does before clearing header filters

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 87.0.4280.88 (Official Build) (64-bit)

**Comment by olifolkerd** [comment]
Hey @tomheaps 

Thanks for the headsup.

I have pushed a fix for this to the mater branch and will include it in this evenings patch update.

Cheers

Oli :)

**Comment by tomheaps** [comment]
Thanks so much for sorting this quickly @olifolkerd. Have just tried out 4.9.3 and it is working like a charm! Has been over 2 years since I used tabulator (v3.5) and I am amazed by all the recent improvements since 4.0 - keep up the great work!
