### ISSUE TITLE
Issue with "Movable Rows Between Elements" example

### ISSUE THREAD

**Issue by roypardi** [olifolkerd/tabulator#3132]
Great library!  Not sure if this "loading" issue is just a doc detail or something with the lib itself but I figured I'd report it. Thanks again! – Roy

**Website Page**
http://www.tabulator.info/examples/4.9#movable-between-elements
http://www.tabulator.info/examples/4.9#movable-between-tables

**Describe the issue**
The example "Movable Rows Between Elements"  doesn't load on OSX Tried it in 
 - Firefox 83.0
 - Chrome 87.0.4280.88 
 -  Safari  12.1.1 (14607.2.6.1.1)

------------
![Screen Shot 2020-12-16 at 4 33 33 PM](https://user-images.githubusercontent.com/9053196/102409350-e72fc080-3fbc-11eb-8ce4-4ffda518307a.png)

------------

On Safari, the "Movable Rows Between Tables" example works but is a little glitchy

<img width="865" alt="Screen Shot 2020-12-16 at 4 43 05 PM" src="https://user-images.githubusercontent.com/9053196/102409904-d29ff800-3fbd-11eb-994d-6d0584a51419.png">

**Comment by olifolkerd** [comment]
Hey @roypardi 

Thanks for letting me know.

It loads fine on all my widows browsers, i will look into this further.

Cheers

Oli :)
