### ISSUE TITLE
adding a input.select()  when editorParams.select=true

### ISSUE THREAD

**Issue by mchendriks** [olifolkerd/tabulator#3134]
I don't know how to contribute. But in the tabulator.js

	//default data editors
	Edit.prototype.editors = {

		//input element
.
.
.
Adding these lines
			if(editorParams.select) {
			    input.select();
			}

gives a nice feature in selecting complete field value on entering the cell.

**Comment by slidertom** [comment]
I also need same feature.
Click on editable cell - auto select all text.
Current solution does not work for me: 
input.setAttribute("type", editorParams.search ? "search" : "text");

			input.style.padding = "4px";
			input.style.width = "100%";
            input.style.boxSizing = "border-box";
            input.select();

Also tried: to use: input.style.userSelect = "all"; 
also no result...

**Comment by olifolkerd** [comment]
Hey @mchendriks 

I have just pushed an update for this functionality to the 5.2 branch, it will use the `selectContents` param.

This will be included in the 5.2 release later this month.

Cheers

Oli :)
