### ISSUE TITLE
fitColumns to always create a scroll 

### ISSUE THREAD

**Issue by cubecleveland** [olifolkerd/tabulator#3138]
Hello,

Setting the Layout to fitColoumns  always shows a vertical scroll bar unless an explicit wisth is set to the table container.

The example below just shows the example provided on codepen:
https://codepen.io/beginnr/pen/oqXweo

Is that a bug, or a fixed width should be applied to the table in order to circumvent this issue?

**Comment by olifolkerd** [comment]
Im afraid i am unable to replicate the issue, no scroll bar appears for me in your example
