### ISSUE TITLE
How can I make Enter key works like TAB key after editing a cell but going to the cell below?

### ISSUE THREAD

**Issue by Leopala** [olifolkerd/tabulator#314]
Hello,

I need to be able to edit the cell below when I finish editing a cell and press enter,
Is that possible?

Thanks,

Leo.

**Comment by olifolkerd** [comment]
Hi Leo,

at the moment there is no support for that, it is possible but would be a bit of a bodge involving jQuery selectors to find the previous elements and select them.

but i think that it is a great idea so if you can wait a couple of days i will add it to the 3.0 beta release. if you cant wait let me know and i can show you how to do it another way

Cheers

Oli

**Comment by Leopala** [comment]
Hi Oli,

Thanks for the quick answer,

Yes, I can wait,

Cheers,

Leo.

**Comment by olifolkerd** [comment]
Hey,

I have some good news for you, with today's 3.1 release there is now a new set of cell navigation functions, documentation for which can be found in the [Navigation Documentation](http://olifolkerd.github.io/tabulator/docs/3.1/#navigation)

You can also customise all of the shortcut key bindings with the new [Keybindings Extension](http://olifolkerd.github.io/tabulator/docs/3.1/#keybindings)

Let me know how you get on.

Cheers

Oli :)

**Comment by Leopala** [comment]
Hi Oli,

Well, I tested it and it looks awesome, but I see a weird behavior:
When I press enter without changing a thing in an editable cell with a value on it, the value of the cell disappears.
All my editors are "input" (editor: "input").
I did not change a thing in the code, it was working perfectly fine in version 3.0.

Thanks,

Leo.

**Comment by olifolkerd** [comment]
Hey Leo,

I have just updated the release to fix the issue. Sorry about that.

Cheers

Oli

**Comment by Leopala** [comment]
Perfect now, thanks!

Cheers,

Leo.
