### ISSUE TITLE
updateColumnDefinition or column.updateDefinition are not working anymore

### ISSUE THREAD

**Issue by Armaldio** [olifolkerd/tabulator#3140]
**Describe the bug**
updateColumnDefinition or column.updateDefinition are not working anymore

**Tabulator Info**
- 4.9.2

**Working Example**
https://codesandbox.io/s/youthful-wescoff-3dxdj?file=/src/index.js

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to the sandbox
2. You should see a table and a button rendered
2. Open the console 
3. Click "Update definition"
4. -> The column header is not updated: 
5. error: `Column Update Error - The updateDefinition function is only available on ungrouped columns`

My column is not grouped thought

**Expected behavior**
I can update column definition

**Desktop (please complete the following information):**
 - OS: W10
 - Browser: Brave

**Additional context**
It worked on previous version
I suspect it's related to this commit: https://github.com/olifolkerd/tabulator/commit/9828f4f5f01feb5e0bd32c6d7b9b32a701f51cb4#diff-7b385e904def4689da7e3e5a6bddbbc0faf6b77c6ddfa3391891a287625a0b7c
Anyway, it's related to this line: https://github.com/olifolkerd/tabulator/blob/master/src/js/column.js#L1392
Because this.parent.isGroup is undefined

**Comment by olifolkerd** [comment]
Hey @Armaldio 

Totally my bad there, looks like i caused that when fixing another issue,

I have just published a new patch release to resolve that.

Cheers

Oli :)

**Comment by TI-AviBerko** [comment]
While this was fixed, the same issue happens if the column has a parent column
