### ISSUE TITLE
AJAX Configuration for set data results in error 

### ISSUE THREAD

**Issue by ipxnsv** [olifolkerd/tabulator#3142]
var ajaxConfigd = {
                        type: "POST", //set request type to Position
                        contentType: 'application/json', //set specific content type
                        data: JSON.stringify(getQueryToSend())
                    };
                    $("#results-grid").tabulator({});
                    $("#results-grid").tabulator('setData', "api/querySearch.ashx?onlygrid=1", null, ajaxConfigd)
               
I can see in the network trace only a get request is executed, without the POST and the "data" i need sent over.

Error:
tabulator.js:12980 Ajax Load Error:  SyntaxError: Unexpected end of JSON input
    at tabulator.js:13131
(anonymous) @ tabulator.js:12980
Promise.catch (async)
(anonymous) @ tabulator.js:12979
Ajax.sendRequest @ tabulator.js:12958
(anonymous) @ tabulator.js:12899
Ajax._loadDataStandard @ tabulator.js:12898
Ajax.loadData @ tabulator.js:12869
Tabulator._setData @ tabulator.js:10031
Tabulator.setData @ tabulator.js:9992
(anonymous) @ jquery-ui.min.js:6
each @ jquery-3.5.1.min.js:formatted:160
each @ jquery-3.5.1.min.js:formatted:78
k.fn.<computed> @ jquery-ui.min.js:6
(anonymous) @ querycreator?queryId=1:336
success @ querycreator?queryId=1:194
c @ jquery-3.5.1.min.js:formatted:1318
fireWith @ jquery-3.5.1.min.js:formatted:1371
l @ jquery-3.5.1.min.js:formatted:3772
(anonymous) @ jquery-3.5.1.min.js:formatted:3899
load (async)
send @ jquery-3.5.1.min.js:formatted:3907
ajax @ jquery-3.5.1.min.js:formatted:3679
getResults @ querycreator?queryId=1:187
bindallMetricExploreObjects @ querycreator?queryId=1:317
(anonymous) @ querycreator?queryId=1:311
dispatch @ jquery-3.5.1.min.js:formatted:2029
v.handle @ jquery-3.5.1.min.js:formatted:1961
tabulator.js:13131 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at tabulator.js:13131

my usecase:
All sorting/loading is server side.

**Comment by olifolkerd** [comment]
That error is saying there is a.json error in the data that is being returned from the server, this means that the server is returning invalid data.
