### ISSUE TITLE
Movable row - row array not updating when moved to beggining of group.

### ISSUE THREAD

**Issue by jarb99** [olifolkerd/tabulator#3143]
**Describe the bug**
When moving a row to the beginning of a group it does not update the row numbering, this is because of a percieved bug in `RowManager.prototype.moveRowActual`. I have outlined in more detail in my answer to [https://stackoverflow.com/questions/65412699/tabulator-movable-row-rowpositioning-not-updating-when-moved-to-top-of-group/65425200#65425200](url). 

**Tabulator Info**
4.9.3

**Working Example**
[https://jsfiddle.net/jarb99/hve74gwt/32/](url)

**To Reproduce**
1. Drag movable row to beggining of group
2. Look at the rownum column, it does not update as it does when dragged elsewhere in group

**Expected behavior**
Row num should update to reflect DOM row order

 - OS: OSX 10.15.7
 - Browser Firefox
 - Version 84.0

**Additional context**
I have a short term fix as described on SO here [https://stackoverflow.com/questions/65412699/tabulator-movable-row-rowpositioning-not-updating-when-moved-to-top-of-group/65425200#65425200](url). I am a new contributor so not confident enough to submit a Pull request just yet, this is the first time i have tried modding the Tabulator.js

**Comment by olifolkerd** [comment]
Hey @jarb99 

The issue there was a result of some inconsistencies in the row positioning system.

This has been rebuilt in the 5.3 release and should resolve this issue.

Checkout the 5.3 release in June.

Cheers

Oli :)

**Comment by jarb99** [comment]
Amazing, thanks @olifolkerd for solving and looking forward the upcoming 5.3👍
