### ISSUE TITLE
thousandSeparator misspelled in the documentation

### ISSUE THREAD

**Issue by LilDevil** [olifolkerd/tabulator#3144]
**Website Pages**
http://tabulator.info/docs/4.9/sort#func-builtin
http://tabulator.info/docs/4.9/upgrade#sort
http://tabulator.info/docs/4.9/release#performance

**Describe the issue**
`thousandSeparator` is misspelled as `thousandSeperator`. This is especially a problem when the misspelling is in sample code, as copy/pasting the code will not work. The spelling is correct in the Javascript code.

Further, on the following pages, `Separator` is misspelled as `Seperator`.

http://tabulator.info/docs/4.9/columns#field-nesting
http://tabulator.info/docs/4.9/menu#overview-items
http://tabulator.info/docs/4.9/format#format-builtin

**Comment by olifolkerd** [comment]
Hey @LilDevil 

Thanks for the headsup, i will get that fixed in the next website update.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Todays website update will resolve this typo

Cheers

Oli
