### ISSUE TITLE
Custom Row Range function for printing

### ISSUE THREAD

**Issue by tomheaps** [olifolkerd/tabulator#3145]
**Describe the bug**
I am trying to set a custom function for `printRowRange` using the example code in the docs however this function does not appear to be having any effect on the rows selected for printing - no error messages are being thrown in the console either...

**printRowRange: function () {  
    return this.getRows().filter((row) => {
      return row.getData().gender === "male";
    });
  },**

**Tabulator Info**
4.9

**Working Example**
[Codepen](https://codepen.io/tomheaps/pen/PoGmPrq)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Click on Print Table button
2. Preview of table to be printed shows ALL rows (including those with gender === "female")

**Expected behavior**
Using the `printRowRange` function should result in only those rows where gender === "male" being selected for printing.

**Screenshots**
![image](https://user-images.githubusercontent.com/13905479/103244838-26172c00-4956-11eb-9d6f-f13b12ca83bc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 87.0.4280.88 (Official Build) (64-bit)

**Comment by olifolkerd** [comment]
Hey @tomheaps 

You do not have the table configured to use HTML printing so it will just be printed as the page has it rendered. you need to enable the `printAsHtml` option in the constructor.

Checkout the [Printing Documentation](http://tabulator.info/docs/4.9/print) for more details.

Cheers
Oli :)

**Comment by tomheaps** [comment]
Thanks @olifolkerd but this does not solve the problem - see my updated [Codepen](https://codepen.io/tomheaps/pen/PoGmPrq) - after adding `printAsHtml: true` to the table construct, on clicking print, all rows of the table are still selected for printing rather than just those where `gender ==="male"` as specified by the `printRowRange` function.

**Comment by olifolkerd** [comment]
do you think you could simplify your code pen so that it only demonstrates the issue at hand, it is quite hard to see the wood from the trees as there is a lot of code in there.

Cheers

Oli :)

**Comment by tomheaps** [comment]
Sorry @olifolkerd please try [this codepen](https://codepen.io/tomheaps/pen/ExgmaWG) instead!

**Comment by olifolkerd** [comment]
Ahh that is much easier to read thanks,

Right I am with you now, this is happening because the print function has its own row range argument that is overriding the defaults (which i can see being confusing so i will resolve that in the next patch release)

in the mean time a workaround is to pass the row range function into the first argument of the `print` function:

```js
table.print(function () {
    return this.getRows().filter((row) => {
      return row.getData().gender === "male";
    });
});
```

Cheers

Oli :)

**Comment by tomheaps** [comment]
Cheers @olifolkerd much appreciated.

**Comment by olifolkerd** [comment]
Hey @tomheaps 

i have pushed a fix for this to the master branch and will include it in next weeks patch release.

Cheers

Oli :)
