### ISSUE TITLE
dataSorted triggered too soon

### ISSUE THREAD

**Issue by danielboven** [olifolkerd/tabulator#3146]
**Describe the bug**
I'm trying to get the current page when [`dataSorted`](http://tabulator.info/docs/4.9/callbacks#sort) is triggered, in order to set a variable based on the current page after sorting. Right now, calling `table.getPage()` on `dataSorted` returns the page before sorting, not after sorting.

**Tabulator Info**
Tabulator version: latest version as of 30-12-2020 -> _v4.9.3_

**Working Example**
A demo of the bug can be found here: https://codepen.io/danielboven/pen/rNMJeaW

**To Reproduce**
1. Go to the CodePen demo
2. Go to the second page of the table
3. Open the console
4. Now click a column header to sort the column -> the table will sort on this column and go to the first page again
5. The console should now log the page (being page 1) but instead it logs the page before all sorting was completed (which was page 2)

**Expected behavior**
Calling `table.getPage()` when `dataSorted` is triggered should return the page after the sorting is applied, not before. Meaning in this example, it should log `1` instead of `2`.

**Screenshot** after the sorting is applied:
![Screenshot after sorting](https://user-images.githubusercontent.com/55955019/103347733-19025600-4a98-11eb-86ba-4d732da63401.png)

**Desktop:**
 - OS: Linux
 - Distro: Manjaro 20.2 Nibia
 - Browser: Google Chrome
 - Version: 86.0.4240.75 

**Additional context**
After a little research the problem seems to be in the `sort.js` module: https://github.com/olifolkerd/tabulator/blob/9568b8893570f2aac048c8947d38cd245585b5db/src/js/modules/sort.js#L272-L278
Right now, I think the `rowComponents` have not been fully updated (by means of pushing new elements to it) when  `dataSorted` is called. In my own ES6 environment I have been able to solve this issue by using promises:
```javascript
if (self.table.options.dataSorted) {
    rowComponents = data.map(row => row.getComponent());
    Promise.all(rowComponents).then(() => {
        self.table.options.dataSorted.call(self.table, self.getSort(), rowComponents);
    })
}
```

I don't know whether it's possible to use this promise-based solution in the repository, but the solution might have to do with being sure that `rowComponents` have all been pushed and updated and _then_ calling `dataSorted`. I reckon there are different ways to accomplish something like that.

**Comment by olifolkerd** [comment]
Hey @danielboven 

This isnt a bug, this is because the `dataSorted` event is triggered as soon as the data has been sorted, but before the table has been redrawn. This is covered in the [Lifecycle Documentation[(http://tabulator.info/docs/4.9/lifecycle#row).

The page is reset when data is sorted so the page will always be 1 at that point.

Cheers

Oli :)
