### ISSUE TITLE
Bottom Calc returns NAN even

### ISSUE THREAD

**Issue by samad-kanton** [olifolkerd/tabulator#3147]
I am populating tabulator with data from localStorage which has id**,** **item**, **cp**, **rp** as keys of my object stored in localStorage. When i pull these keys with their respective values into Tabulator and try to add another column which does not have a key in my original object, it works alright but with my custom calculation function, it returns NAN(Not a number i guess).

var printFrameTable = new MyTabulator().init(`#example-table`, {
                  height: 311,
                  virtualDom: false, //disable virtual DOM rendering
                  layout:"fitColumns",      //fit columns to width of table
                  responsiveLayout:"hide",
                  columns: [
                    {title: "#", field: "id", formatter: "rownum", width: 40},
                    {title: "DESCRIPTION", field: "item"},
                    {title: "QTY", field: "qty", hozAlign: "right",  width: 50},
                    {title: "RATE", field: "rp", hozAlign: "right", width: 70},
                    {title: "EXT", field: "", hozAlign: "right", formatter: (cell, formatterParams, onRendered) => /*(parseFloat() * parseFloat(cell.getData().rp))*/ 200, bottomCalc: (values, data, calcParams) => { return 400; }, width: 70},
                    // {title: "EXT.", field: "amt", hozAlign: "right", formatter: (cell, formatterParams, onRendered) => this.$root.formatCurrency(parseFloat(cell.getData().qty) * parseFloat(cell.getData().rp)), width: 100, bottomCalc: (values, data, calcParams) => console.log(values)},
                    // {title: "AMOUNT", field: "amt", hozAlign: "right", formatter: (cell, formatterParams, onRendered) => { return this.$root.formatCurrency(cell.getData().qty * cell.getData().sp) }, bottomCalc: "sum", bottomCalcParams: { precision: 2, thousandSeperator: ","}, width: 100},
                  ],
});

**Comment by olifolkerd** [comment]
Hey @samad-kanton 

If you are having an issue and would like to report a bug, please use the [Bug Issue Template](https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Possible+Bug&template=bug_report.md&title=) it will prompt you to provide all the information we need to help.

It is important that you provide a link to a JS fiddle that shows the code in action.

Cheers

Oli :)
