### ISSUE TITLE
responsiveLayout set to 'collapse' will cause the column auto hide on refresh browser

### ISSUE THREAD

**Issue by dannykln** [olifolkerd/tabulator#3148]
ResponsiveLayout with 'collapse' are very useful feature to me,  however I'm noticed that the columns will auto hide when i refresh the browser.

**Tabulator Info**
version 9.3

**Working Example**
https://jsfiddle.net/dannykln/pv7xfgdu/15/

**To Reproduce**
- persistence set to true and responsiveLayout set to collapse, load the table for first time, narrow the browser screen size until responsive layout happen, then refresh the browser
- it work perfectly if persistence set to false

**Screenshots**
first time load , everything seems fine
![image](https://user-images.githubusercontent.com/18520941/103594798-a4fefc80-4f34-11eb-9449-77e0f54427fe.png)

when refresh the browser , columns disappear
![image](https://user-images.githubusercontent.com/18520941/103594858-ce1f8d00-4f34-11eb-94f5-f17ca0ca85d1.png)

**Desktop (please complete the following information):**
Google Chrome Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by desirade-fm** [comment]
I have the same problem with responsiveLayout=hide

**Tabulator Info**
4.9.3

**Working Example**
https://jsfiddle.net/chemarf/m24hg1no/

**To Reproduce**
In JsFiddle resize the browser to hide columns then reload browser and resize to fullscreen. The columns remain hidden.
Click on "Reset persistence" button and columns are shown.

**Browser version**
Chrome 89.0.4389.90 (Build officiel) (64 bits)
Firefox 86.0.1 (32 bits)

**Comment by olifolkerd** [comment]
This is because you have persistence enabled on the table which also persists column visibility, so the two systems are essentially fighting against eachother there.

If you exclude column visibility from the persistence options then it should work fine.

Cheers

Oli :)
