### ISSUE TITLE
Sort function name changed in version 3.0

### ISSUE THREAD

**Issue by yaxino** [olifolkerd/tabulator#315]
some function 'sort'  Not provided
.tabulator("sort", "Domain", "asc");
 ajaxType is removed.
paginator: function (url, pageNo, pageSize, ajaxParams) not work.

...
...

**Comment by olifolkerd** [comment]
Hey yaxino,

A number of the function and option names have changed in version 3.0 to make the naming more consistent across the system. please have a read through the [documentation](http://olifolkerd.github.io/tabulator/docs/3.0/) making sure you are looking at the correct version (there is now a version selector in the top right of the page)

in version 3.0 the ***sort*** function has been renamed ***setSort*** to fit in with the new naming convention:

```js
$("#example-table").tabulator("setSort", "Domain", "asc");
```
***ajaxType*** was replaced with ***ajaxConfig*** in version 2.12

could you explain your pagination issues a bit more?

**Comment by yaxino** [comment]
paginator: function (url, pageNo, pageSize, ajaxParams) {
                    var sortor = $(obj.selector + ' .tabulator').tabulator('getSort');
                    url += '?page=' + pageNo + '&size=' + pageSize
                        + '&sort=' + (sortor.field ? sortor.field : '') + '&sortdir=' + sortor.dir
                        + '&token=' + g_s.user.Token;

                    return url;
                },


I debugger my code ,  it is not work.
and i deep track of your code, not find related calls

**Comment by olifolkerd** [comment]
Turns out there was an issue with initializing the table with paged data, this is now fixed.

Thanks for letting me know :)
