### ISSUE TITLE
Progress formatter does not vertically center legend text

### ISSUE THREAD

**Issue by DeweertD** [olifolkerd/tabulator#3150]
The progress formatter leaves the legend text as a child of the column cell rather than a child or the progress bar element, this leaves the legend text to become "relative" to the parent cell instead of the bar element. I believe this is the main reason for the bug. Fixing this means updating the formatter to set the legend text as having a dynamic top spacing, or creating a containing div which the bar and legend text can both be relative to.

At least Tabulator versions 4.8.x - 4.9.3

https://codepen.io/ultilink3/pen/gOwKLEd

**To Reproduce**
See the progress legend text in the codepen is not vertically centered.  It hangs out the top of the progress bar.

**Expected behavior**
Legend text should always be inside the progress bar

**Comment by olifolkerd** [comment]
Hey @DeweertD 

I thinks that this has now been resolved in the 5.x releases, so i will close off this issue.

Cheers

Oli :)
