### ISSUE TITLE
tickCross formatterParam:{crossElement:false,} seems not working

### ISSUE THREAD

**Issue by ivostoykov** [olifolkerd/tabulator#3157]
**Describe the bug**
Tick Formatter is a deprecated function and recommends replacement (http://tabulator.info/docs/4.2/deprecated - search Tick Formatter)

It seems though replacing it with `tickCross formatterParam:{crossElement:false,}` as described not to have desired effect - only true to be visible

Tabulator version: 4.9.3

**Working Example**
https://jsfiddle.net/ivos/du8e1ags/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Open fiddler link - there'll be two tables on the right: 1st uses the recommended column formatter; 2nd - the obsolete one
2. See error in upper table - false are marked as red crosses

**Expected behavior**
false columns to be empty as shown in 2nd table

**Screenshots**
![image](https://user-images.githubusercontent.com/889184/104461192-e7fd4780-55a6-11eb-908e-dd4f8a11e0ef.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 fully patched
 - Browser Chrome latest 
 - Version 87.0.4280.141 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
n/a

**Additional context**
no

**Comment by bornova** [comment]
Hi @ivostoykov ,
You have misspelled `formatterParam`.  Correct spelling is `formatterParams` with an 's' as in plural.

**Comment by ivostoykov** [comment]
Hi @bornova 

Thanks for the reply. I didn't pay much attention as I copy/paste the documentation assuming it should work and didn't check further. My bad, sorry. 
![image](https://user-images.githubusercontent.com/889184/105001633-fb396880-5a27-11eb-96f7-60ca511c2e52.png)

Making it plural fixed the problem. Thank you.

**Comment by olifolkerd** [comment]
i will ensure the documentation is updated accoringly

**Comment by olifolkerd** [comment]
Todays website update will fix the documentation error.

Cheers

Oli :)
