### ISSUE TITLE
Pagination with option to show all records

### ISSUE THREAD

**Issue by pirex360** [olifolkerd/tabulator#3159]
Hi,

I'm in project that needs pagination of table to be like (25,50, 100, ALL).
In tabulator, i cannot use ALL option... only fixed number pagination.

Best Regards

**Comment by bornova** [comment]
@pirex360 From documentation - http://tabulator.info/docs/4.9/page:

```
You can also pass a boolean value of true into the array, this will show an "All" option that will show all available rows on one page

var table = new Tabulator("#example-table", {
    pagination:"local",
    paginationSize:10,
    paginationSizeSelector:[10, 25, 50, 100, true], //select list with an "all" option at the end of the list
});
```

**Comment by pirex360** [comment]
Thanks, i did not see this !
Any way to translate the "All" option ?

**Comment by bornova** [comment]
@pirex360 From documentation: http://tabulator.info/docs/4.9/localize#define

**Comment by olifolkerd** [comment]
Hey @pirex360 

As @bornova suggests, this is already available Checkout their suggested documentation links for full details.

Cheers

Oli :)

**Comment by pirex360** [comment]
Thanks for all the help, unfortunate I see my error was checking older documentation.
