### ISSUE TITLE
filter removed callback

### ISSUE THREAD

**Issue by ivostoykov** [olifolkerd/tabulator#3164]
*Is your feature request related to a problem? Please describe.**
Not at all

**Describe the solution you'd like**
It would be great to have in Filter Call-backs -- a hook on filter removed similar to dataFiltered

**Describe alternatives you've considered**
Attach a function to the filter input's on-change event and fire it when contents deleted.

**Additional context**
None

**Comment by olifolkerd** [comment]
Hey @ivostoykov 

The existing `dataFiltered` callback fullfills that function, it is called whenever the filters are changed.

Cheers

Oli :)

**Comment by ivostoykov** [comment]
Hi @olifolkerd 

Thanks for the fast reply. Great work! Thank you.
