### ISSUE TITLE
Native way of loading data from Google Application Script web

### ISSUE THREAD

**Issue by cimenta** [olifolkerd/tabulator#3167]
Hi

could you add native support for loading data from Google Application Script web? Current working solution for me is

```
google.script.run.withSuccessHandler(getZZData).getTabulatorData();

function getZZData(output){
   var tableDataGenerated = output;
  var table = new Tabulator("#zz-table", {
    movableColumns:true,
    data:tableDataGenerated,

```

I am not a coder guru but I think that it is not the best approach. More native way would be better.

Thank you
Radek

**Comment by olifolkerd** [comment]
Hey @cimenta 

Thanks for your suggestion.

I do not add any native integrations in to Tabulator, if i did, Tabulator would be come awash with a thousand different properties for different libraries.

Tabulator is a platform agnostic library. The documentation makes it very clear the format that data should be to be correctly ingested into the table. and it is usually a matter of a few lines of code for a developer to convert a different datasource if needed.

Cheers

Oli :)
