### ISSUE TITLE
Second header row at bottom?

### ISSUE THREAD

**Issue by cimenta** [olifolkerd/tabulator#3168]
Hi

can Tabulator have a feature to display header at bottom too? In case the table is big bottom header would be useful.  

https://i.stack.imgur.com/8byz5.png

I created StackOverflow question for that https://stackoverflow.com/questions/65782263/how-to-add-second-bottom-header-to-tabulator-js

Thank you
Radek

**Comment by olifolkerd** [comment]
Hey @cimenta 

Thanks for your suggestion.

Im afraid i would consider putting the headers again ad the bottom of the table to be poor UI design, in the example image the table is not big enough to need it, and should a table get big enough i would argue that the table area should be smaller and it allowed to scroll keeping the headers at the top as it currently does.

FOr that reason i would not be looking to include this as a feature in Tabulator.

Many Thanks

Oli :)
