### ISSUE TITLE
(cell) Right Click Menu - disable & pass parameters

### ISSUE THREAD

**Issue by cimenta** [olifolkerd/tabulator#3169]
Hi

is it possible to add these features

- add params to contextMenu so we can pass some params to the contextMenu function. Something like contextMenuParams:{type:"oil"}
- add an option to disable context menu for some cells or rows. For example the parent cell, row of nested tree does not have to have the menu

thank you
Radek

**Comment by olifolkerd** [comment]
Hey @cimenta 

I think those are great ideas, i will add them to the roadmap.

Cheers

Oli :)

**Comment by LilDevil** [comment]
You can already do these things if you use a [Menu Items Generator Function](http://tabulator.info/docs/4.9/menu#overview-generator) to define your menus.

For your first suggestion, just add it to the menu object, then in the `action` function, access your custom params with `this`.
```
menuItem = {
  label: 'Do something',
  action: function() {
      if (this.type === 'oil') ...
  },
  type: 'oil',
};
```

For the second suggestion, in your menu definition function, test for it.
```
function rowMenuDefinition(row, event) {
  if (event.target.textContent === 'oil') {  // use whatever test you need for your case
    // return appropriate menu 
  } else {
    return false;
  }
}
```

**Comment by Joao-deOliveira** [comment]
@LilDevil , 

Also looking for 'contextMenuParams' to be passed as an additional action function arguments, **menuItem.action(**_<event>, <element (column | row | cell)>, ctxMnuParams_**)** .

Thanks for the suggestions :-) looking forward to see it implemented :-)

Cheers

**Comment by olifolkerd** [comment]
Hey @LilDevil 

Thinking about this more i think the existing functionality offers all of this already. as @LilDevil states you can pass a function into the menu options to decide weather it shows or not.

The function also allows for changing menu items disabled state.

I would normally only add params objects for items that by default take params, which menus do not at present, so it would be a bit of an anti pattern to add them here. that being said there is nothing to stop you adding them to the column definition objects yourself and then calling the `getDefinition` function on the column component to access that prop yourself.

Cheers

Oli :)
