### ISSUE TITLE
Beta 3.0 22.5.2017

### ISSUE THREAD

**Issue by michaelongithub** [olifolkerd/tabulator#317]
Hi Oli
Congrats on all the extensions an new features !
I put this all in one issue.  No date/version in readme.md or tabulator.js Maybe helpful for future reference.
Only test chrome and IE11
Get data via Ajax.
Table height set:
                $('#tabulatortest').tabulator({
                    height: "400px",

Table with colums without text wrap:
2100 rows
Works basically ok. 
In Chrome fast. With 1 exception scrolling smooth. If scroll with mouse holds scroll cursor: scetchy.
Ctrl Home / End Work correctly. But have to click into grid each time.
IE sketchy and slow in general. You mentioned You still optimizing.

Table with colums WITH text wrap:
1900 rows.
Chrome and IE11:
Scrolling scetchy
Inital  varying rowheight correct.
Can often not scroll to end. Rows sometimes not visible. Come again when scroll anew. 
Generally most of the times cannot scroll to end. like stops at 1600 of 1900 or so.
So does not really work yet.

Working demo from you would be very helpful.

Row resize:
Runtime Error in IE11. In Chrome OK.

Cheers Michael

**Comment by olifolkerd** [comment]
Hey Michael,

Thanks for the feedback that is exactly what i need.

so i can help smooth things out could you post a copy of your tabulator constructor object, and also a couple of rows of data so i can test with something similar to you.

Thanks for testing all those scrolling methods, a couple of those hadn't occurred to me.

I think i know whats going on with text wrapping causing it to not reach the end, not reaching the end, did that affect both browsers?

which version of chrome are you running?

Cheers

Oli

**Comment by michaelongithub** [comment]
Hi Oli
unfortunately I cannot post example data, they are real and proprietary.

Constructor:
```
    $('#tabulatortestJournal').tabulator({
        height: "600px",
        fitcolumns: false,
        columns: [
            { title: "Rownum", field: "JourID", formatter:"rownum" },
            { title: "JourID", field: "JourID" },
            { title: "JourTime", field: "JourTime" },
            { title: "Zust1", field: "Zust1" },
            { title: "Dokname", field: "Dokname" },
            { title: "Doktype", field: "Doktype" },
            { title: "JourInhaltTextOnly", field: "JourInhaltTextOnly", formatter: "textarea", width:350},
        ],

        ajaxURL: daUrl,
        ajaxConfig: "GET"
    })
```
JourInhaltTextOnly: a plain text field that can have up to 8000 chars.

Scroll Test:
Keys: Up/Dn, CursorKeys Up/Dn, Ctrl Home/End
MouseWeel: Scroll and draw with wheel pressed. Scrollbar: Click Arrows, Empty Space, Hold Scroll Cursor with Mouse, 
List Complete? All these should work correct, right?

And it is not only not reaching the end but juddery and choppy, stopping, sometimes not displaying rows and so on. 

Chrome: Version 58.0.3029.110 (64-bit)
Cheeres, Michael

**Comment by olifolkerd** [comment]
Thanks for the info,

I completely understand about the data, no problem. in that case would you be able to let me know the data types you are sending to each field and approximate size in characters, it would help me generate some sample data that is as realistic as possible.

Thanks

**Comment by michaelongithub** [comment]
https://github.com/marak/Faker.js/ maybe helpful for You. 
My data all fields text in Json
JourID: int 
JourTime: datetime
Zust1: max 10 chars
Dokname: max 128 chars
Doktype: max 12 chars.
JourInhaltTextOnly: max 8000 chars.

**Comment by olifolkerd** [comment]
amazing thanks!

Im going to temporarily disable the row height recalculation on column resize until the virtual dom is running smoothly, then reintroduce it.

will let you know when the next version is available.

Thanks for all your help!

**Comment by michaelongithub** [comment]
Hi Oli
for future tests the examples with **many** columns of chdh that he had prepared for you might also come handy:
http://www.source-code.biz/temp/tableTests/tabulator/
and there:
http://www.source-code.biz/temp/tableTests/static-html/
and
http://www.source-code.biz/temp/tableTests/tabulator/SimpleTest.js
Cheers, Michael

**Comment by olifolkerd** [comment]
Hi Michael,

I have committed some tweaks to the virtual DOM scroll rendering that should keep the odd and even styling the same and smooth the process of key navigation.

Unfortunately the rendering process itself is fairly intensive given the number of configuration options that Tabulator can handle, and while the major current browsers cope well (Chrome, Firefox, Safari and Edge), the IE JavaScript engine simply isn't efficient enough to be able to handle this smoothly. It does function correctly it just isn't as smooth as possible,

Given the ever decreasing number of users of IE, I am currently focusing my efforts on making Tabulator as smooth as possible on modern browsers while maintaining table functionality for older browsers like IE.

For this reason I am not going to spend much more time optimising for IE as there are other areas of Tabulator that I put more urgency on.

That being said, I would welcome any input from yourself if you can see any points that could be optimised.

Cheers

Oli

**Comment by michaelongithub** [comment]
Hi Oli
I understand completely.
Is the current version of beta changed enough since 22.5, that it is helpful / meaningful to run my tests again`
Cheers, Michael

**Comment by olifolkerd** [comment]
He Michael,

Thanks for your understanding.

Barring a couple of small features that i will be adding tomorrow the beta is nearing its final stable state so it would be great if you would test it again.

I have moved the row height resizing on column width change to version 3.1 as it turned out to be a bit more complex than i originally thought and i want to ensure it gets the attention it needs to run smoothly.

I will be publishing a road-map on trello this week outlining the release schedule for the next few months.

Thanks for all the help.

Cheers

Oli
