### ISSUE TITLE
Multiline editing in tabulator cell with formatter = 'textarea' is not working

### ISSUE THREAD

**Issue by Danyshman** [olifolkerd/tabulator#3171]
**Describe the bug**
Multiline editing in tabulator cell with formatter = 'textarea' is not working

**Tabulator Info**
- 4.9

**Working Example**
YOU MUST include a link to a JS Fiddle or Codepen that demonstrates the problem, it is very hard to diagnose an issue from a simple description.

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://jsfiddle.net/pg89Lrce/15/
2. Column called Testing Column
3. When you are not editing, it is okay, shows multiline text. But when you try to edit and click to cell it does not show text as multine, but as single line and it is so unconfortable to edit multine text

**Expected behavior**
Support also multiline text when editing

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by olifolkerd** [comment]
Hey @Danyshman 

This is happening because you are using the wrong editor. if you are using a textarea formatter then you need to use a textarea editor as well. The input editor uses a standard input element which only supports single line input

Cheers

Oli :)
