### ISSUE TITLE
when dataTreeElementColumn is set and the column is editable, a click in the cell with the tree element makes the element disappear

### ISSUE THREAD

**Issue by NnMllr** [olifolkerd/tabulator#3173]
**Describe the bug**
When the dataTreeElementColumn is set and this column has an editor, by clicking in one cell of this column the branchElement or the Collapse/Expand Element disappear which makes the row not collapsible/expandable anymore.

**Tabulator Info**
4.9.3

**Working Example**
http://jsfiddle.net/6edcjxpf/2

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to any of the collapsable rows in the first table
2. Click on the cell of the row where the collapse/expand element is to edit it
3. Leave the cell
4. See error => the CollapseElement disappears

**Expected behavior**
The clicked cell should not loose the collapse/expand element as seen in the second table in the jsfiddle which has the dataTreeElementColumn not set.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 84 (Latest version)

**Additional context**
This isn't a problem when the dataTreeElementColumn option is not set.

**Comment by olifolkerd** [comment]
Hey @NnMllr 

That is definitely a regression there, 

I will look at getting a fix for that out in the next release

Cheers

Oli :)

**Comment by NnMllr** [comment]
Thanks, I really like using Tabulator :)

**Comment by danielHin** [comment]
Hey Guys,

ran into the same problem and had a look into that issue. I added a small fix and tested successfully on my local machine  (using the examples from the jsfiddle in this issue)

Hope this helps :)

**Comment by olifolkerd** [comment]
Hey @NnMllr 

I have pushed a fix for this to the master branch and will include it in the next patch release.

Cheers

Oli :)
