### ISSUE TITLE
Implement multiline text editor in cells

### ISSUE THREAD

**Issue by Danyshman** [olifolkerd/tabulator#3175]
*Is your feature request related to a problem? Please describe.**
It is so uncomfortable to edit multiline texts in tabulator cells with signle line editor input. It will be very nice, if you will implement multiline editor such textarea, so we can edit multiline texts in cells

**Describe the solution you'd like**
Implement multiline text editor using textarea tag html

**Describe alternatives you've considered**

**Additional context**
Sorry, i recenlty figured out that this functionality is already implemented. Thank you!

**Comment by olifolkerd** [comment]
Hey @Danyshman 

This is already a thing, there is a "textarea" editor built in to Tabulator. simply include it in your column definition:

```js
{title:"example", field:"example", editor:"textarea"}
```

Read the [Editor Documentation[(http://tabulator.info/docs/4.9/edit#edit-builtin) for a full list of built in editors

Cheers

Oli :)
