### ISSUE TITLE
dataFiltered possible bug in 1st parameter

### ISSUE THREAD

**Issue by ivostoykov** [olifolkerd/tabulator#3177]
**Describe the bug**
dataFiltered first parameter never changes.
From documentation:
```
  dataFiltered:function(filters, rows){
    //filters - array of filters currently applied
    //rows - array of row components that pass the filters
```
**Tabulator Info**
4.9.3

**Working Example**
https://jsfiddle.net/ivos/5pkjytmq/1/

**To Reproduce**
A step by step guide to recreate the issue:
1. Load the example. Should see current parameters' values below the table
```
filters: 0
rows: 5
```
2. Type **_ob_** in the filter box. Below the table are shown parameters' values during each call. Now you should have 4 rows:
```
filters: 0
rows: 2
filters: 0
rows: 5

```
3. See error: The filters parameter's value should be one (1) and the number of filtered rows (2). Instead - it is zero

**Expected behavior**
filters parameter to have length > 0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version  87.0.4280.141 (Official Build) (64-bit)

Description is from the documentation: [http://tabulator.info/docs/4.9/callbacks#filter](http://tabulator.info/docs/4.9/callbacks#filter) - section **Data Filtered**

**Comment by olifolkerd** [comment]
Hey @ivostoykov 

This is not a bug, but i can see how it is confusing

The dataFiltered callback is only passed in the actual table filters set with the `setFilter` and `addFilter` functions.

Realtime header filters are handled separately. to access these in the callback, use the `getHeaderFilters` function:
```js
var headerFilters = table.getHeaderFilters();
```

Cheers

Oli :)

**Comment by ivostoykov** [comment]
I see. Thanks Oli
