### ISSUE TITLE
question combine first name + last name into Name

### ISSUE THREAD

**Issue by Busbybabe** [olifolkerd/tabulator#318]
i have a JSON `{
		"id": 1,
		"first_name": "Jonathan",
	    "last_name": "Mendoza",
		"email": "jmendoza0@posterous.com", 
		"gender": "Male"
		},`

i want to combine it into {title:"Name", field:"first_name + last_name}

**Comment by olifolkerd** [comment]
Hey, no problem.

you can use a custom formatter to do that for you. you should create a column definition for your name column (it doesn't matter that the name field doesn't exist). and then use the formatter to join the values together

**Tabulator 2.12**
```js
{title:"Name", field:"name", formatter:function(value, data){
        return data.first_name + " " + data.last_name;
    },
}
```

**Tabulator 3.0**
```js
{title:"Name", field:"name", formatter:function(cell){
        var data = cell.getRow().getData();
        return data.first_name + " " + data.last_name;
    },
}
```

Let me know if that helps you out.

Cheers

Oli

**Comment by Busbybabe** [comment]
It helps me, thx a lot!
