### ISSUE TITLE
cell parameter in cellMouseMove not updated whilst mousedown in Firefox

### ISSUE THREAD

**Issue by richard-slabbert94** [olifolkerd/tabulator#3180]
**Describe the bug**
The cell parameter in the cellMouseMover callback is not updated if you have your mouse left click down in Firefox.

**Tabulator Info**
Tabulator v4.9.3

**Working Example**
[https://jsfiddle.net/rslabbert/duh8fq0b/8/](https://jsfiddle.net/rslabbert/duh8fq0b/8/)

**To Reproduce**
1. Open the fiddle in Firefox.
2. Open up the JS Fiddle console so you can view the cell values.
3. Without the mouse down, move across the tabulator table and you will see that the value updates in the console depending on which cell you are in.
4. Click on a table cell and keep the mouse down.
5. Now move around the table and you will see that only the value of that first cell is written to the console regardless of which cell you are moving over.

**Expected behavior**
The cell object from the cellMouseMove callback is meant to be the current cell you are over.

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6 (High Sierra)
 - Browser: Firefox
 - Version 84.0.2 (64-bit)

**Additional context**
It is interesting to note that if I take out text highlighting using this following css, the callback works as expected (I found the css [here](https://stackoverflow.com/a/4407335)). I cannot however take out the text highlighting like this as users sometime use it (plus the clipboardPasteParser doesn't fire).

```
-webkit-touch-callout: none; /* iOS Safari */
-webkit-user-select: none; /* Safari */
-khtml-user-select: none; /* Konqueror HTML */
-moz-user-select: none; /* Old versions of Firefox */
-ms-user-select: none; /* Internet Explorer/Edge */
user-select: none; /* Non-prefixed version, currently
                                  supported by Chrome, Edge, Opera and Firefox */
```

**Comment by olifolkerd** [comment]
Hey @richard-slabbert94 

Tabulator just uses the standard JS event bindings, this is more likely a limitation in the firefox event handling system *(of which there are many)*.

If you add the same event bindings in a simple div for example does it experience the same issues?

Cheers

Oli :)
