### ISSUE TITLE
Columns get confused when using virtualDomHoriz

### ISSUE THREAD

**Issue by rathboma** [olifolkerd/tabulator#3181]
Got another one for you unfortunately.

![tabulator-data-alignment](https://user-images.githubusercontent.com/279769/105939750-67ffc480-601f-11eb-9aff-735eb9ce9418.gif)

When scrolling around a table up/down/left/right, the columns eventually go out of sync.

Disabling virtualDomHoriz fixes it

The data isn't changing at all, or being modified in any way.

**Comment by rathboma** [comment]
@olifolkerd I'll work on browser replication as usual

**Comment by rathboma** [comment]
I'm probably going to just disable `virtualDomHoriz` until version 5 comes out. The data loading performance improvements you added mitigated many of the performance improvements anyway

**Comment by olifolkerd** [comment]
Hey @rathboma 

I would be happy to collaborate with you on the updated vDOM in version 5.0 if you fancy. You have a fantastic useage case for it and it would be great to help tailor it to meet your needs.

Cheers

Oli :)

**Comment by rathboma** [comment]
Hey Oli,

Yeah I'd love to collaborate on it. What's the best way to do that?

**Comment by olifolkerd** [comment]
@rathboma  Im in the process of finalizing the 5.0 alpha release this week, *(im hoping to make it publicly available  by the end of next weekend)*

At that point all renderers, both horizontal and vertical will have been abstracted away into the new Render class which has a standardised  API interface making it much easier to manage building and updating renderers.

With that in place, tweaking new render designs will be as simple as registering a new render with Tabulator when it is first imported.

Im quite excited about this next release.  The main focus of the refactor has been to make internals of Tabulator more accessible to developers, allowing them to easily customise any parts of the table as needed.

All modules have been isolated from one another and a new event bus system brought in to allow any part of the system to subscribe to updates from any other part.

I would love your feedback when it launches.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @rathboma 

Tabulator 5.0-alpha was released yesterday, it now has the horizontal DOM logic separated out into its own renderer class to make it easier to manage.

Checkout the [Rederers Documentation](http://tabulator.info/docs/5.0/render) for more info

It is still a little rough round the edges, but provides a sensible location for others to contribute to the renderers.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Is this still the case since the 5.x release?

Cheers

Oli :)

**Comment by rathboma** [comment]
@olifolkerd Oh yes, this is still a problem.

I'm poking around in the horizontal vdom renderer. I haven't figured it out yet, but I have a suspicion on what is causing it.

It looks like the renderer is losing track of scroll position and ending up with incorrect `vDomPadLeft` values, which throws the whole table off.

I can fix some issues by doing `Math.max(this.vDomPadLeft, 0)` when setting table padding, but that's just treating the symptoms.

In the example below:
```js
// in VirtualDomHorizontal.js

vDomPadLeft = -90 // should be 0

```
![image](https://user-images.githubusercontent.com/279769/150563581-58b6c34f-b712-4756-aa4d-96f62abe8487.png)


Maybe there's a way of changing this so that the renderer doesn't depend on `vDomScrollPosLeft`

**Comment by rathboma** [comment]
To replicate:

Check out my branch `hozer`: https://github.com/beekeeper-studio/tabulator/tree/hozer

```bash
# terminal 1:
yarn run dev

# terminal 2 (in root of tabulator directory):
python -m SimpleHTTPServer 8000 # python 2
# python 3: python -m http.server 8000

```

- Navigate to [localhost:8000/testing/](http://localhost:8000/testing)
- Switch page (Don't know why this helps)
- Scroll right and left a lot really fast
- Scroll all the way to left
- Check terminal (`window.hoz` in the terminal to look at the hoz renderer state)

**Comment by rathboma** [comment]
It's possible to manually fix the problem by setting `hoz.vDomPadLeft = 0` once you're scrolled all the way to the left, then scrolling slowly... but that fix doesn't work if you want to fix things once it's already out of sync

**Comment by rathboma** [comment]
Ok. I found it. One line fix :-)

**Comment by olifolkerd** [comment]
Hey @rathboma 

I am assuming this is now fixed in the latest release?

Cheers

Oli :)
