### ISSUE TITLE
select headerFilter default and initial value problems

### ISSUE THREAD

**Issue by wergio** [olifolkerd/tabulator#3182]
**Describe the bug**
I'm upgrading from Tabulator 3.5.1 to 4,9.3 and I noticed different (bugged?) behaviour of select headerFilter used in conjunction with formatter

**Tabulator Info**
4,9.3

**Working Example**
default value problem: https://codepen.io/Wergio/pen/KKgOJyR
initial value problem (using initialHeaderFilter): https://codepen.io/Wergio/pen/JjRgNPV

**To Reproduce**
1. Go to codepen links
4. See error on "Gender" header filter value

**Expected behavior**
In first codepen I expect the default select to be set to "All" (like was on 3.5.1) and not to appear like a common input header filter until I click it for the first time (then it becomes "All")

In the second codepen I wanted to specify the initial value to "Male" with initialHeaderFilter parameter, the only working way I found is to specify the associated int value "1", but I expected the select box to be rendered as "Male" and not "1". Unfortunately specifying "male" or "Male" value in initialHeaderFilter does not work.

**Desktop**
 - OS: Windows 10
 - Browser Firefox
 - Version 84.0.2 (64 bit)

**Comment by olifolkerd** [comment]
Hey @wergio 

The correct appraoch in this instance is not to use the default value, this is intended for editing functionality.

You should use the `initialHeaderFilter` option to set the initial value of a header filter

checkout the [Header Filtering Docs](http://tabulator.info/docs/5.1/filter#header) for full details.

Cheers

Oli :)
