### ISSUE TITLE
table.refreshFilters(); should be table.refreshFilter();

### ISSUE THREAD

**Issue by mjedlin66** [olifolkerd/tabulator#3184]
**Website Page**
http://tabulator.info/docs/4.9/release#filter
http://tabulator.info/docs/4.9/filter#manage

**Describe the issue**
In at least two places, the 4.9 documentation shows table.refreshFilters(); The correct function name is table.refreshFilter();

**Comment by olifolkerd** [comment]
Hey @mjedlin66 

Thanks for the headsup, i will get that fixed in todays website update.

Cheers

Oli :)
