### ISSUE TITLE
Why is title required in column definitions?

### ISSUE THREAD

**Issue by blazespinnaker** [olifolkerd/tabulator#3185]
Just looking at the second example on the example page - Virtual DOM - Horizontal

```
var table = new Tabulator("#example-table", {
    height:"311px",
    virtualDomHoz:true,
    columns:[
        {title:"col1", field:"col1"},
        //...
        {title:"col499", field:"col499"},
    ],
});
```

This is a very very common scenario, where field and title will be the same.  Even more ideal would be just passing a simple array of fields..

Also, iterating through the data and using the union of all columns would be a useful option for autoColumns, rather than just the first row.

A particular common use case is viewing json data with tabulator.  It'd be cool if nested json could be more easily viewable, but perhaps that is a stretch.

**Comment by kapenzo** [comment]
In my project we never had this scenario ;D
You can easly map your json: Object.keys().map(function(key){return { title: key, field:key};});

**Comment by olifolkerd** [comment]
You can already do this.

Tabulator has built in auto columns functionality. Simply set the autoColumns property to true in your table constructor and don't define the columns array.

Cheers

Oli
