### ISSUE TITLE
Pass function with cell argument to cellContextMenu to dynamically return false or true

### ISSUE THREAD

**Issue by Danyshman** [olifolkerd/tabulator#3187]
*Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Implement feature to dynamically return false or true in disable label in contextMenu

**Describe alternatives you've considered**

**Additional context**
Example: {
    action: ...
    label: ....
   disabled: (cell) => cell.getData().field === 'Disable';
}

**Comment by olifolkerd** [comment]
This already happens as per the documentation

Cheers

Oli :)
