### ISSUE TITLE
Multi column sort doesn't always work

### ISSUE THREAD

**Issue by isohelio** [olifolkerd/tabulator#3188]
Multi column sorting doesn't always work as far as I can see.

Chrome  88.0.4324.104, Windows 10 Professional

I don't have a fiddle or codepen, but you can see it on some of the example tables e.g.

http://tabulator.info/examples/4.9#fittodata

Steps to reproduce

1. Click on Gender column header
2. Table is now sorted by Gender, 5 female records, followed by 5 male records
3. Shift-click (or control-click) on Rating.
4. Gender and Rating header both show green arrows.

Expected Behaviour
Gender column should remain sorted into female, male groups, Rating values should be sorted within those groups.

Observed Behaviour
Gender column ordering is now lost, but Rating column is sorted.

On closer inspection it appears that the table is sorted first by Rating then by Gender.
If you first click on Rating then shift-click on Gender you get the table sorted by Gender, Rating.

It appears that columns are used in the wrong order for the sorting.

Thanks for your help.

**Comment by olifolkerd** [comment]
This works as intended, there are just two orders that sorts can be applied and everyone has their own prefference.

If you want sorting to apply the sorters in the reverse order then you can set the `sortOrderReverse` option to true in your table constructor:

```js
var table = new Tabulator("#example-table", {
    sortOrderReverse:true,
});
```

Cheers

Oli :)
