### ISSUE TITLE
headerFilter:true has disappeared :)

### ISSUE THREAD

**Issue by alainpannetier** [olifolkerd/tabulator#319]
Dear Oli,

I started porting today and things look promising. All I had to do to benefit from the virtual DOM was:

```javascript
        this.tabopts.height = table.height();
        table.tabulator( this.tabopts );
```
And indeed that solves a lot of issues.  Nomore spinner woes.

The code is 10 times clearer and I like the modular design. This is how I'm doing in my own webapp.
With some prototypal inheritance to sprite it up. I have one super class wrapping tabulator and plenty of data specific subclasses. Which are just there to declare columns, implement the data creation logic and add some data specific behaviour.  All the heavy weight lifting is done by my super class and ultimately by tabulator.  This also guarantees same look and feel across all pages. So thanks again.

Now about the glitches. This is still a beta fter all. Look line 6271 (#initializeColumn)

``` javascript
      switch (_typeof(column.definition.headerFilter)) {
        case "string":
          //
          break;

        case "function":
          //
          break;
      }
```
There's nothing for the 'boolean' (the doc still says 'true' is valid for headerFilter)
And if you look at your own [demo](http://olifolkerd.github.io/tabulator/examples/3.0/#filter-header) 

```javascript
 {title:"Gender", field:"gender", editor:genderEditor, headerFilter:true},
```
...as no filter in its header.
I guess there should be some kind of sensing mechanism to set to "input" or "number" in this case.
For now of course, I'll using "String" or "number" or whatever there is.

More feedback will come as I dig in. But great job.

**Comment by olifolkerd** [comment]
Hey,

Thanks for the feedback! always great to hear the effort is appreciated :)

Great spot on the header filter, i have just push an update to fix the headerFilter:true problem.

keep the feedback coming!

Cheers

Oli

**Comment by alainpannetier** [comment]
Just tested with editor. Works fine. :+1:
