### ISSUE TITLE
Reactivity Framework Compatibility

### ISSUE THREAD

**Issue by Xenoha** [olifolkerd/tabulator#3191]
**Website Page**
http://tabulator.info/docs/4.9/reactivity#frameworks

**Describe the issue**
Website currently states compatibility with framework reactivity is supported with vue, react, and angular. However, the reactivity does not work with vue3 (specifically the composition API "ref" - possibly due to the use of proxies) and this should be stated within the documentation and/or be more clear to say vue2.

**Comment by olifolkerd** [comment]
If you believe.you have found a bug with Tabulators comparability please create an issue using the bug template.and provide a link to a JS fiddle that demonstrates the issue. We can then look at resolving it to ensure suitable compatibility

**Comment by Xenoha** [comment]
Hello, I have created two issues per your request to fix the compatibility issue. Thanks!
