### ISSUE TITLE
groupUpdateOnCellEdit causing "TypeError: e is undefined" when moving rows between groups

### ISSUE THREAD

**Issue by cimenta** [olifolkerd/tabulator#3192]
hi

**Describe the bug**
groupUpdateOnCellEdit option is causing "TypeError: e is undefined" when moving rows between groups. Just comment it out and the error disappers.

**Tabulator Info**
4.9

**Working Example**
https://jsfiddle.net/radek/u48joxv6/107/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to 'https://jsfiddle.net/radek/u48joxv6/107/
2. Move a row to the other group 
3. See error in the console 
4. firefox - "Uncaught (in promise) TypeError: e is undefined"
4. chrome -Uncaught (in promise) TypeError: Cannot read property 'getGroup' of undefined

**Expected behavior**
no error

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win10
 - Browser - Firefox, Chrome
 - Version latest

**Comment by olifolkerd** [comment]
Hey @cimenta 

Thanks for the headsup,

I will look at resolving that in the next release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @cimenta 

This has been resolved in the 5.0.8 release.

Cheers

Oli :)
