### ISSUE TITLE
Vue3 proxy is not reactive when using the reactiveData flag with data provided.

### ISSUE THREAD

**Issue by Xenoha** [olifolkerd/tabulator#3194]
**Describe the bug**
When using the reactiveData flag as true, the table does not update when using the vue3 composition API [ref, reactive] proxies. Shown in the codesandbox, you can push data to a regular object and the table will update accordingly, but when pushing to the ref of proxyItems the table does not update accordingly. Per the documentation in the reactivity section, the table should follow vue framework data properties.

**Tabulator Info**
4.9.3

**Working Example**
https://codesandbox.io/s/quirky-gates-64hxe?file=/src/App.vue

**To Reproduce**
Create a 'ref' property within the component setup function of the composition API. Create a life cycle hook onMounted and create the table within this method. During table creation, set the 'reactiveData' flag to 'true', and the 'data' property to the 'ref'.value. See the table populate with values. Change the ref.value through some means and not the table does not update.

**Expected behavior**
When passing a Vue3 Ref to the table with the reactiveData flag set to 'true', the table should update when the ref value changes.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 20.04
 - Browser Chrome
 - Version 88.0.4324.146

**Smartphone (please complete the following information):**
NA

**Additional context**

**Comment by masterkain** [comment]
I have the same issue, I tried everything I could.

I use `useResult` which is a vue-apollo function that returns a Readonly Ref.
I tried passing the result to `toRaw`, `unref` and friends but I always have errors.

Any hints how to proceed?

```
const mediaFiles = useResult(
  playlistResult,
  [],
  (data) => data.playlist.mediaFiles
);

onMounted(() => {
  tabulator = new Tabulator(tableRef.value, {
    data: mediaFiles.value,
    reactiveData: true,
    columns: [{ title: "Artist", field: "artist" }],
  });
});
```

**Comment by masterkain** [comment]
one way

```
    data: JSON.parse(JSON.stringify(mediaFiles.value)),
    reactiveData: false,

...

watch(
  mediaFiles,
  (state, prevState) => {
    if (tabulator) {
      tabulator.replaceData(JSON.parse(JSON.stringify(state)));
    }
  },
  { deep: true }
);
```
