### ISSUE TITLE
ajaxRequestFunc property does not fire when using pagination: 'remote'

### ISSUE THREAD

**Issue by Xenoha** [olifolkerd/tabulator#3195]
**Describe the bug**
When configuring table instantiation with pagination: 'remote' while using the ajaxRequestFunc method, the ajaxRequestFunc does not fire. Only fires when pagination: 'local' is set which further doesn't allow correct pagination. 

**Tabulator Info**
4.9.3

**Working Example**
https://codesandbox.io/s/amazing-mestorf-8exhy?file=/src/App.vue

**To Reproduce**
Load the code or hit the refresh button and you should see console.log statements saying that the function fired and the response was provided when instantiation of the table occurs. Neither of these methods fire.

**Expected behavior**
When using the pagination: 'remote' flag you should be able to use the ajaxRequestFunc method to configure data as needed. The ajaxResponse method then should expect the format { last_page: Number, data: Array} following the typical flow pagination already provides.

**Screenshots**
N /A

**Desktop (please complete the following information):**
 - OS: Linux ubuntu 20.04
 - Browser Chrome
 - Version 88.0.4324.146

**Smartphone (please complete the following information):**
N / A

**Additional context**

**Comment by olifolkerd** [comment]
Hey @Xenoha 

This should be resolved on the 5.0 release as that system has now been completely rebuilt.

In the new release, you now have the ability to build custom module that tap into the internal data loading events of the table, this provides a much more comprehensive way to load data in a custom manor.

Checkout the [Database ModuleExample](http://tabulator.info/docs/5.0/module-examples#db) for an example of how to build a custom module to tap into the data loading functionality.

Cheers

Oli :)
