### ISSUE TITLE
Blocking top/bottom calc when updateData is called

### ISSUE THREAD

**Issue by danke02** [olifolkerd/tabulator#3196]
Hello.
First of all, thank you for your great product. I suggest some feature.
I experience short UI freeze when data is updated in case of table with bottom calc.
I have a table with 200 rows which is updated every 1-2 second and it has a bottom row for displaying summation.
When "table.updateData" is called with array of 200 object, Tabulator do recalc() for every element of an array.
I think sometimes it's better to block bottom/top row calculation for bulk update because it can cause UI freezing(even it's a really short time)
I temporarily solved this problem by unset/set bottomCalc before and after calling updateData.
Am I missing something? 
What do you think?

**Comment by olifolkerd** [comment]
Hey @danke02,

have you tried using the ***replaceData*** function instead.

Cheers

Oli :)

**Comment by danke02** [comment]
> Hey @danke02,
> 
> have you tried using the _**replaceData**_ function instead.
> 
> Cheers
> 
> Oli :)

Thank you, I'll try!
