### ISSUE TITLE
Implement feature to dynamically determine disabled property in context menus with function

### ISSUE THREAD

**Issue by Danyshman** [olifolkerd/tabulator#3197]
*Is your feature request related to a problem? Please describe.**
No, not related to a problem. Implement feature to dynamically determine disabled property in context menus with function which gets cell as it's argument

**Describe the solution you'd like**
 Implement feature to dynamically determine disabled property in context menus with function which gets cell as it's argument

**Describe alternatives you've considered**

**Additional context**

**Comment by olifolkerd** [comment]
You can do this already by passing a function into the disabled property of the menu item in the config object.

Checkout the [Disabled Menu Item Docs](http://tabulator.info/docs/4.9/menu#overview-items) for full details

Cheers

Oli :)
