### ISSUE TITLE
Rows not rendering when scrolling vertically grouped data

### ISSUE THREAD

**Issue by tkalicki** [olifolkerd/tabulator#3199]
I've created viewer for Linux journalctl JSON logs (1 row = 1 log message). Boot cycles are grouped by boot_id hash. I see this issue when log file has many boot cycles.

**Describe the bug**
Scrolling down vertically several times is causing bottom rows to be not rendered. Scrolling up is not filling up the empty space. Scrolling down when table has only empty space is causing "Uncaught TypeError: Cannot read property 'removeChild' of null" exception.

**Tabulator Info**
4.9.3

**Working Example**
https://jsfiddle.net/07L6npwd/ (warning: slow to load & run due to a lot of data)
standalone demo of issue: https://pastebin.com/n8MuZeuH

**To Reproduce**
1. Scroll down via page down key or mouse wheel to about 10% of table.
2. Scrolling down just increases size of empty space.
3. Resize window horizontally for rows to be rendered in empty space.
Firefox only: scrolling down via scroll bar also is causing this issue.

**Expected behavior**
All rows are rendered when scrolling up or down.

**Screenshots**
![image](https://user-images.githubusercontent.com/13311290/107119706-a308c000-6889-11eb-9590-5f90d0b8df37.png)

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser: Chrome 88.0.4324.146 (Official Build) (64-bit)
 - Browser: Firefox 85.0.1 (64-bit)

**Smartphone (please complete the following information):**
Not tested.

**Additional context**
Issue observed only when grouping is enabled. Input data is not grouped order.

**Comment by olifolkerd** [comment]
Hey @tkalicki 

This should have been resolved in the 5.x releases. Let me know how you get on, if you are still having issues we can reopen this.

Cheers

Oli :)
