### ISSUE TITLE
setSort correction

### ISSUE THREAD

**Issue by alainpannetier** [olifolkerd/tabulator#320]
Hi Oli,

Here's one I believe I have a patch for:

In setSort line#9924 change 

```javascript
    sortList.forEach(function (item) {
      var column;
      item.column = self.table.columnManager.findColumn(item.column);
```
With
```javascript
    sortList.forEach(function (item) {
      var column;
      item.column = self.table.columnManager.findColumn(item.field);
```
Otherwise the column is never found.

**Comment by alainpannetier** [comment]
Actually it's possibly an issue only with the doc.
The doc says to use 'field' but the code seems to use 'column` instead of field.
```javascript
initialSort:[
        {field:"age", dir:"asc"}, //sort by this first
        {field:"height", dir:"desc"}, //then sort by this second
    ]
```

**Comment by alainpannetier** [comment]
Eventually, I would recommend sth like

```javascript
      if ( typeof item.column === "undefined" ) {
          item.column = self.table.columnManager.findColumn(item.field);
      } else {
          item.column = self.table.columnManager.findColumn(item.column);
      }
```

**Comment by olifolkerd** [comment]
Hey,

i agree that could be a lot clearer, i will have a tweak this evening!

Cheers

**Comment by alainpannetier** [comment]
You're right. It should be column everywhere. It took me a while to understand.

However, when an initial sort is requested, only the field can be passed because the column component is not known yet. But that first call lands line#9924 and the sort is declined. Hence my last 'tweak'.
I have never made any pull request (I use git extensively at work but very little with github). I'll work it out though.

**Comment by olifolkerd** [comment]
Documentation has now been updated to reflect the new ***column*** property instead of  ***field***

Thanks for the spot there! your help is really appreciated!

Cheers

**Comment by alainpannetier** [comment]
Thanks. Works perfectly. I had failed to recognise that the column argument of findColumn can also be a string (field). So there was no need for my "warty" typeof test. :+1:  column works perfectly also with initialSort.
