### ISSUE TITLE
Resizing columns using dynamically generated columngroups does not resize the column header

### ISSUE THREAD

**Issue by vec2k4** [olifolkerd/tabulator#3202]
**Describe the bug**
I'm using a combination of static columns that are created prior data loading and dynamic columns that are created while the data loading is in progress. Some of the static columns form a column group and also the dynamic colums are grouped together forming another column group. 
So I create the dynamic columns and group using the `addColumn` function inside the `dataLoading` callback. Everything works as expected but when it comes to resizing the dynamic columns, I get weired results. The data part of the column is resized correctly, but the column header still remains at its old size. Please keep in mind that the fiddle is an extremly simplified version of my real `dataLoading` callback function. Column autogeneration is not an option for my use-case.

If I set the columns using `this.setColumns(this.getColumnDefinitions())` in the `dataLoading` callback after dynamically adding the columns as a workaround the error doesn't occur.

**Tabulator Info**
- Using Tabulator 4.9.3 and also tried current 5.0.0 branch

**Working Example**
- https://jsfiddle.net/vec2k4/abcypvmq/

**To Reproduce**
1. Go to the fiddle
2. Press "Load data" button
3. Resize one of the columns belonging to the "Dynamic column group" 
4. See the resizing error
5. Now resize one of the columns belonging to the "Static column group"
6. See the resize working
7. Press "Load data with workaround" button
8. See the dynamic and static columns resize correctly

**Expected behavior**
I would expect that resizing the columns, even if they are dynamically added, works as it should.

**Screenshots**
 - Error:
 ![Bug](https://user-images.githubusercontent.com/9272347/107420058-c5fcd380-6b18-11eb-8fcc-ac784cba7391.gif)
 - With workaround:
![Workaround](https://user-images.githubusercontent.com/9272347/107420297-0bb99c00-6b19-11eb-9e75-208c75cb6803.gif)

**Desktop (please complete the following information):**
 - OS: Win 10 latest
 - Browser: Edge version 88.0.705.63 (Chromium)

**Smartphone (please complete the following information):**
 - Didn't test on mobile browsers

**Comment by olifolkerd** [comment]
Hey @vec2k4 

This has been resolved in the 5.x releases.

Cheers

Oli :)
