### ISSUE TITLE
Ability to set default options for column definitions

### ISSUE THREAD

**Issue by ggggabri** [olifolkerd/tabulator#3204]
*Is your feature request related to a problem? Please describe.**
I've been asked to add a header context menu to all the columns in all the tables in my project, and I realized there's no way to do this without editing all the column definitions one by one

**Describe the solution you'd like**
I'd like to be able to set some default column options like you can do for table options, in the `Tabulator.prototype.defaultOptions` object

**Describe alternatives you've considered**
A separate object for default column options would also work, maybe `Tabulator.prototype.defaultColumnOptions`

**Comment by olifolkerd** [comment]
Hey @olifolkerd 

You already can for some options, but you make a great point that it would be useful for them all to be available,

I will add this to the 5.0 roadmap.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @ggggabri 

You will be happy to hear i have just pushed this functionality onto the 5.0 branch which i am hoping to release in a months time.

There is a new `columnDefaults` option that allows you to define the default props for all columns:
```js
var table = new Tabulator("#example-table", {
    columnDefaults:{
        width:200, //set the width on all columns to 200px
    },
    columns:[
        {title:"Name", field:"name"},
        {title:"Age", field:"age"},
        {title:"Address", field:"address", width:300}, //override the column default and set this column to 300px wide
    ],
});
```

Cheers

Oli :)
