### ISSUE TITLE
cell.validate & cell.isValid to return validators failing

### ISSUE THREAD

**Issue by Joao-deOliveira** [olifolkerd/tabulator#3206]
**Describe the solution you'd like**
When we **cell.validate()** the return is either _true or _false_ . In case of validation violation, we do not know what **validators** have failed (like we know upon cell edition using the callback), so it will very useful that **cell.validate()** when validation fails, to return the same as when editing.

In the same line of thought, when calling **cell.isValid()**, in case on **_not valid_**, should return the validators that didn't passed.

An option may pass to store the on the cell Component the failed validators information and implement a function **cell.getViolations()** which return:  { value: (cell value that failed validation), violations : [ (validator objects that failed) ] }

**Describe alternatives you've considered**
The alternative is "faking" cell edition to trigger the valididationFailed callback, but if we are validating an entire row or column or even table, this isn't a good solution :-(

Thanks a million 

P.S: if this can be part of a 4.9.x would be great :-)

cheers
João

**Comment by olifolkerd** [comment]
Hey @Joao-deOliveira 

Thanks for that suggestion, i think that is a great idea.

Because it changes the API of tabulator im afraid it cant be added in the 4.9.x release which would only be for patches.

I will include it on the roadmap for 5.0

Cheers

Oli :)

**Comment by RossCoeH** [comment]
I too am looking at validation, and seeking to return a user message as to why it fails.  Many of the React packages I have tried have a validation with a dual content cell - the second content after the input is a small red message text under the field, but narrow cells might need a button or tooltip instead.
I seems to me that the validator function needs an inversion of logic.  At the moment we return true from the validator if it is valid,  but we want to send either an array of messages or a single message back to the cell which triggered it.  (But this is also a truthy value so we would need an invert of current logic.  
Given the codebase out there we would probably not want to mess with the current validator option, so should add an alternate  isInvalid function that returned an array of errors back to the cell component (use undefined if no error) . We could then use it to highlight invalid cells, for mouseover or provide an input cell with message by tooltip.   

The important point is that all data is in the table and we no longer have to use state outside the table to manage the errors

**Comment by olifolkerd** [comment]
Hey all,

Most of the events triggered from cell validation were changed in the 5.0 release to return an array of failed validators.

I have just pushed some updates to the 5.2 branch to make this behaviour consistent across all functions events and callbacks.

This will be included in the v5.2 release later this month.

Cheers

Oli :)
