### ISSUE TITLE
Tabulator custom editing issue correlating to height property

### ISSUE THREAD

**Issue by Flavius1** [olifolkerd/tabulator#3207]
**Describe the bug**
If I have a custom editor field in Tabulator I cannot access the editing function unless I set the Tabulator's height property to a defined number of pixels. No editing is possible with the height property set as "100%".

**Tabulator Info**
- Which version of Tabulator are you using?
4.9.3

**Working Example**
YOU MUST include a link to a JS Fiddle or Codepen that demonstrates the problem, it is very hard to diagnose an issue from a simple description.
https://jsfiddle.net/Flavius01/f2k7sjyq/29/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Set the height property of the table to "100%"
2. Run the example
4. See the error as no editing is possible in the info field

**Expected behavior**
I expect working custom editing irrespective of the height setting of the table.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 88.0.4324.146

**Comment by olifolkerd** [comment]
Hey @Flavius1 

This is happening because you have the table inside an HTML element without a fixed height on it, therefore it is trying to resize indefinitly to fill an infinite amount of space.

If you want the table to work in this way you will need to set the `html` and `body` elements to have a height of 100% too:
```css
html, body{
  height:100%;
}
```

Cheers

Oli :)

**Comment by Flavius1** [comment]
Hi Oli,

That's it. I couldn't figure it out myself. Thanks a lot.

Cheers,
Ervin

Oli Folkerd ***@***.***> ezt írta (időpont: 2021. dec. 29.,
Sze, 17:26):
