### ISSUE TITLE
escaped characters don't show up in column titles when using responsive layout collapse

### ISSUE THREAD

**Issue by vec2k4** [olifolkerd/tabulator#3210]
**Describe the bug**
When using `responsiveLayout: "collapse"` in the options and setting a column title to an escaped character (e.g. `&#8960;` => ⌀), the character is not unescaped correctly if the column is shown up in the collapse list.

**Tabulator Info**
- Using version 4.9.3

**Working Example**
- https://jsfiddle.net/vec2k4/jhum6xbz/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to the fiddle.
2. See the last column showing up the correct symbol: ⌀
3. Now drag the vertical splitter to resize the window showing tabulator so that the last column collapses to the list
4. See the error

**Expected behavior**
The escaped characters should show up correctly even if collapsed.

**Screenshots**
![unicode](https://user-images.githubusercontent.com/9272347/107892075-0c8c6c80-6f23-11eb-9dbd-f62a364a1b7b.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge 88.0.705.68

**Smartphone (please complete the following information):**
 - Not tested on mobile devices

**Additional context**
Problem seems to be in module `responsive_layout.js` where `element.innerText` is used for column titles instead of `element.innerHTML` like it is used for the value:
https://github.com/olifolkerd/tabulator/blob/75799201323ac2f4a912aeec9a9668494c2c3099/src/js/modules/responsive_layout.js#L281
Fix could be using `innerHTML`, but I don't know the reason to use `innerText` here. If `innerHTML` is ok, I can provide a pull request.

**Comment by olifolkerd** [comment]
Hey @vec2k4 

Thanks for the headsup, i will stick that on the list to fix.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @vec2k4 

I have pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)
