### ISSUE TITLE
Tabulator date filter sorts incorrectly

### ISSUE THREAD

**Issue by Danyshman** [olifolkerd/tabulator#3212]
**Describe the bug**
Tabulator date sorter incorrectly sorts

**Tabulator Info**
- Which version of Tabulator are you using?
- 4.9

**Working Example**
YOU MUST include a link to a JS Fiddle or Codepen that demonstrates the problem, it is very hard to diagnose an issue from a simple description.
https://jsfiddle.net/tb68cqdf/4/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://jsfiddle.net/tb68cqdf/4/
2. Sort column created_at in ascending order
3. You will see that the third month(March) comes before second (February)

**Expected behavior**
The march month should be after the february

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by phaleth** [comment]
See this jsfiddle https://jsfiddle.net/w63t4kor/

I've added moment.js lib dependency and `sorter` and `sorterParams` parameters to the `created_at` field and now the sorter works the way you want.
