### ISSUE TITLE
Tooltips styling

### ISSUE THREAD

**Issue by fbenedetti06** [olifolkerd/tabulator#3214]
A way to customize tooltips (color, font size...) could be a good idea!

**Comment by olifolkerd** [comment]
Hey @fbenedetti06 

Tabulator uses the built in tooltips from the browser by setting the `title` property on the cell's div Tags, sadly these are not styleable in any browser at present.

That being said, there would be nothing to stop you using a third party tooltip library in your cell formatter to get customisable tooltips.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @fbenedetti06 

You will be happy to hear that in the upcoming 5.2 release, Tabulator will be supporting fully customisable tooltips.

Cheers

Oli :)

**Comment by fbenedetti06** [comment]
Hi Oli
That's so cool
Thanks a lot
⁣Fred

Envoyé de mon smartphone​

Le 9 avr. 2022 à 15:33, à 15:33, Oli Folkerd ***@***.***> a écrit:

**Comment by Mupli** [comment]
for those who hit this:

```javascript

//in columns
 tooltip: function (e, cell, obj) {
                const desc = cell.getRow().getData().desc;
                return  "<b style='font-size:14px'>"+(desc ? desc.replaceAll("\n", "<br/>") : desc ) +"</b>";
            },
            ```
