### ISSUE TITLE
In select editor, pass function as argument to values property to dynamically define list of values

### ISSUE THREAD

**Issue by Danyshman** [olifolkerd/tabulator#3216]
*Is your feature request related to a problem? Please describe.**
No, not related. In select editor, pass function with cell argument as argument to values property to dynamically define list of values

**Describe the solution you'd like**
In select editor, pass function with cell argument as argument to values property to dynamically define list of values

**Describe alternatives you've considered**

**Additional context**

**Comment by olifolkerd** [comment]
You can already do this.

You just pass a function to the `editorParams` argument that then contains the values array on the returned objects `values` prop.

Cheers

Oli :)
