### ISSUE TITLE
Create config property in tabulator configuration, to set left padding of grouped rows 

### ISSUE THREAD

**Issue by Danyshman** [olifolkerd/tabulator#3217]
*Is your feature request related to a problem? Please describe.**
It is not clear to what group row belongs when you grouped rows by multiple values. Here is the screenshot https://paste.pics/fe7f2ed07700ab7c69f5c2b466d0e97d
**Describe the solution you'd like**
Create property in table configuration to set left padding of row in grouped rows. Here is the screenshot, how should it be https://paste.pics/6526027d3ed852c20fae63e624936891

**Describe alternatives you've considered**

**Additional context**

**Comment by olifolkerd** [comment]
Hey @Danyshman 

Thanks for getting in touch.

Your proposal would see columns becoming misaligned from the column headers which would make for a very poor user experience. For this reason i would not be looking to add this functionality

Cheers

Oli :)
