### ISSUE TITLE
dataTree expand/collapse much slower in v4.9 compared to v4.8

### ISSUE THREAD

**Issue by larslemberg** [olifolkerd/tabulator#3218]
Hi Oli,
I considered holding off on reporting this to see if Version 5 exhibits the same behavior, but then thought if it is a real problem you might want to handle it as early as possible.

**Describe the bug**
Expanding and collapsing a dataTree that contains many children is very slow in v4.9 compared to v4.8.  The performance when expanding can be improved using Ajax and Progressive Loading, but even then, once the large number of children are loaded, collapsing the tree takes several seconds. Version 4.8 handled 1000 children (and more) with almost no noticeable delay. 

**Tabulator Info**
- I see this behavior in Tabulator version 4.9. If I revert my project back to Version 4.8 the performance is much faster.

**Working Example**
JSFiddle can be seen at https://jsfiddle.net/llemberg/dvr5mq8e/128/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://jsfiddle.net/llemberg/dvr5mq8e/128/
2. Expand the Road Number row, noting the 1-2 second delay before the children are displayed. 
3. Collapse the Road Number row, I see a 3-4 second delay before the display is updated. 

**Expected behavior**
I expected similar performance to Version 4.8. I don't have a Version 4.8 jsfiddle, but if I duplicate the jsfiddle on my test system using Tabulator 4.8 the expand/collapse response is very fast.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint 20
 - Browser Chrome 88.0.4324.182 and Firefox 85.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by olifolkerd** [comment]
Hey @larslemberg 

Due to a rebuild of the data tree module in the 5.x release this is no longer an issue, things now run much faster.

Cheers

Oli :)
