### ISSUE TITLE
Add mac shortcuts for copying rows as Cmd+C instead of Ctrl+C

### ISSUE THREAD

**Issue by max4ever** [olifolkerd/tabulator#3220]
Hi, it would be great if it would be possible to add mac keyboard shortcuts.

**Describe the solution you'd like**
The row copy feature: when I click CMD+C(Command+C) it should copy, just as when I click Ctrl+C(Control+C).

**Additional context**

![immagine](https://user-images.githubusercontent.com/1863265/108911016-f5d2cd80-7626-11eb-8eb2-06bcfbb31640.png)

**Comment by olifolkerd** [comment]
Hey @max4ever 

Very good point, i will look into that.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @max4ever 

I have pushed an update for this to the 5.1 branch and will include it in the next release.

Cheers

Oli :)
