### ISSUE TITLE
Autocomplete Editor Not Displaying List of Values in Dropdown on First Click

### ISSUE THREAD

**Issue by mtrmarko** [olifolkerd/tabulator#3222]
I am new to web development and Tabulator. So far, I like how easy it has been to pick up Tabulator and to get the initial data from a database. Thank you for a great product. However, I ran into a weird issue with autocomplete editor where list of values does not display on first click into the cell. 

Here is my table code:

```javascript
var table = new Tabulator("#pv-table", {
    layout:"fitColumns", //fit columns to width of table (optional)
    placeholder:"No Data Available",
    ajaxURL:"http://localhost:82/api/software",
        columns:[
            {title:"SoftwareID", field:"SoftwareId", visible:false},
            {title:"SoftwareName", field:"SoftwareName"},
            {title:"SoftwareVersion", field:"SoftwareVersion"},
            {title:"OwnerId", field:"OwnerId"},
            {title: "BackupOwnerId",
				field: "BackupOwnerId",
				headerSort: false,
				editor: "autocomplete",
				width: 250,
				editorParams: {
					values: ["red", "green", "blue", "orange"],
					allowEmpty: true,
					showListOnEmpty: true
				}
			}
        ]
});
```

As you can see the table gets its data from an ajax request to an API. Below is the payload the API returns:

```json
[
    {
        "SoftwareId": 1,
        "SoftwareName": "App Uno",
        "SoftwareVersion": "1.1",
        "OwnerId": "XXXXX",
        "BackupOwnerId": null
    },
    {
        "SoftwareId": 2,
        "SoftwareName": "App Dos",
        "SoftwareVersion": "2.1",
        "OwnerId": "YYYYY",
        "BackupOwnerId": null
    }
]
```

A few things to note. API gets its data from a SQL Server database. I am defining autocomplete editor for BackupOwnerId column. This column is defined as nvarchar(10) in the database, so the data it stores are essentially strings. This column is NULL for all rows by default. This is because, I am going to be asking users to go through the list of all software and assign a backup owner. To assist with this I was planning to populate a list of owners from an ajax call to an API. The list will include couple of thousand entries eventually. Users will go to BackupOwnerId column and select who should own a particular software by clicking in the cell and starting to type persons ID, then selecting the entry.

For testing purposes, I am providing a hard-coded list of values as I was running into issues with ajax calls to populate the list. Even with a hard-coded list of values, I see the same behavior.

This is what happens:

I load the page and the initial table with data displays as expected. I then go to BackupOwnerId cell in the first row and click inside it. No dropdown appears, or if I use a placeholder for empty, I get the placeholder text instead. I then click in the BackupOwnerId cell of the second row. Same issue. I then click back into the cell of the first row, and the dropdown with red, green, orange, blue finally appears. I think this has something to do with the fact that the cell is initially NULL. I tried setting the BackupOwnerId columns across all rows to an empty string rather than NULL, then adding an empty string to the list of values doe the dropdown. In this case, the dropdown appears on first click. I am not sure if this is a bug or expected behavior, or something I am doing wrong.

I can probably continue to use the empty string method to work around this, but it is not as elegant, and I was hoping there is something else I could do instead, or if improvements can be made to Tabulator to handle this use case a bit better.

Also, I think this is related to issue [2931](https://github.com/olifolkerd/tabulator/issues/2931)

**Comment by olifolkerd** [comment]
I have just pushed updates to the 5.2 branch that replaces the ***select*** and ***autocomplete*** editors with the new ***list*** editor, which will resolve this issue.

It will be included in the 5.2 release later this month.

Cheers

Oli :)
