### ISSUE TITLE
Interactively highlight the row that has background color

### ISSUE THREAD

**Issue by yiminli** [olifolkerd/tabulator#3224]
In the first example of [http://tabulator.info/examples/4.9?#formatters](http://tabulator.info/examples/4.9?#formatters), when move mouse over a row, the row will be highlighted, except the second row which has background color already.

Consider not only the second row has background color, but all the rows have background colors. This interactive highlight feature is not visible.

Is it possible to add support and highlight the row which may have background color already?

**Comment by olifolkerd** [comment]
Hey @yiminli 

This depends on how you set the background colour and is not actually related to tabulator but to the example.

By setting a colour directly on the element it has precedence over any colour set by CSS unles the `!important` flag is being used, which is bad practice for the library.

In your usage case you should set the background colour using a class, which would then allow the built in Tabulator styling to override it.

Cheers

Oli :)

**Comment by yiminli** [comment]
Thanks @olifolkerd.
I am not sure if I understand this correctly. Looks like I need to reuse below code:
```
    rowFormatter:function(row){
        if(row.getData().age >= 18){
            row.getElement().addClass("success"); //mark rows with age greater than or equal to 18 as successful;
        }
    },
``` from http://tabulator.info/docs/3.5. But addClass is deprecated in version 4.9. Is there an alternative option to addClass?

**Comment by yiminli** [comment]
Found a solution at:
https://stackoverflow.com/questions/61739079/tabulator-row-formatting-removes-hover-effect-while-cell-formatting-doesnt

**Comment by LilDevil** [comment]
> But addClass is deprecated in version 4.9. Is there an alternative option to addClass?

.addClass is part of [jQuery](https://api.jquery.com/addclass/) and is not deprecated.

.classList.[add](https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/add) is the equivalent plain JavaScript.
