### ISSUE TITLE
movable row issue

### ISSUE THREAD

**Issue by python3Berg** [olifolkerd/tabulator#3225]
Upgrade from 4.7 to 4.9.3. Can't do code pen because lots of proprietary data. When I now move rows between two tablulators, the data is properly updated via custom callbacks, but the floating row dragged and dropped does not disappear and is permanently floating until a screen refresh. Used this for many versions...something has changed.

Uncaught TypeError: Cannot read property 'mousemove' of undefined
    at tabulator.js:22537
    at Array.forEach (<anonymous>)
    at MoveRows._unbindMouseMove (tabulator.js:22536)
    at MoveRows.endMove (tabulator.js:22610)
    at MoveRows.dropComplete (tabulator.js:22815)
    at MoveRows.commsReceived (tabulator.js:22900)
    at Comms.receive (tabulator.js:12643)
    at Tabulator.tableComms (tabulator.js:11677)
    at tabulator.js:12630
    at Array.forEach (<anonymous>)
Delete if you wish...

**Comment by FacetsNovum** [comment]
macOS Mojave 10.14.6

I'm using 4.9.3 as well (not an upgrade), experiencing the same: floating row dragged and dropped, does not disappear, permanently floating until a screen refresh.

This occurs on all of the browsers I'm using:

- Safari 14.0.3 (14610.4.3.1.7)
- Firefox 86.0.1 (64-bit)
- Chrome Version 89.0.4389.90 (Official Build) (x86_64)

To compare, I'm using both **sample tables** and **custom tables**. The custom table receives its data via `ajaxURL` where the sample table is copy/pasted sample code provided here:

http://tabulator.info/examples/4.9?#movable-between-tables

The sample table works just fine, dragging/dropping all day long ... with the exception of Firefox. Firefox is still a little buggy with the sample code, as described in another post in that it does not consistently move rows from one table to another.

What is _consistent_ across all browsers is that when I use `ajaxURL` as my data source the row permanently floats until I refresh the screen.

Thanks for all of your work and all the best

**Comment by TassoPeperone** [comment]
I have same issue. In my experience the problem was when i had more than 20 rows. Less rows works. I check and in 4.7 version works, but not in 4.9.3

**Comment by olifolkerd** [comment]
Hey @FacetsNovum 
This has been resolved in the 5.x releases.

Cheers

Oli :)
