### ISSUE TITLE
The field "textarea" height does not change after editing

### ISSUE THREAD

**Issue by atitoff** [olifolkerd/tabulator#3227]
**Describe the bug**
The field "textarea" height does not change after editing

**Tabulator Info**
v4.9.3

**Working Example**
[https://jsfiddle.net/Alexander_Titov/w3bf2k40/3/](https://jsfiddle.net/Alexander_Titov/w3bf2k40/3/)

**To Reproduce**
Edit field and click button

**Expected behavior**
The field should automatically increase the height to fit the content

**Screenshots**
![image](https://user-images.githubusercontent.com/13304485/109483812-bbd35280-7a90-11eb-8f89-1a6ee0e81c54.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome 88.0.4324.190

**Comment by bornova** [comment]
Hi @atitoff,
You can force the height of the cell to auto in your css to accomplish that:
```css
.tabulator-row .tabulator-cell {
    height: auto !important;
}
```

[https://jsfiddle.net/edbavhru/](https://jsfiddle.net/edbavhru/)

**Comment by olifolkerd** [comment]
That is because you have not set the `variableHeight` property in the column definition. without this Tabulator does not expect the cells height to change after editing.

Cheers

Oli :)
