### ISSUE TITLE
Add `isTreeExpanded` method for RowComponent.

### ISSUE THREAD

**Issue by PeterShinners** [olifolkerd/tabulator#3228]
I'd like to determine if a given row with the tree model is expanded or collapsed. I couldn't find an exposed method to do this and am proposing adding a method to get this state. I am new to Tabulator, but I believe the method would look like this
```javascript
	RowComponent.prototype.isTreeExpanded = function () {
		if (this._row.table.modExists("dataTree", true)) {
                        return this._row.modules.dataTree.open;
		}
                return false;
	};
```
I feel like this name matches conventions already on the row component. I'm open to suggestion or feedback. Next I'd be pleased to submit a pull request. I intend to update the documentation as part of the change.

**Comment by PeterShinners** [comment]
I asked about this on StackOverflow last weekend. I looked again and could find no exposed solution.
https://stackoverflow.com/questions/66412966/how-to-know-if-tabulator-table-row-is-expanded

**Comment by olifolkerd** [comment]
Hey @PeterShinners 

Great idea, i will add that to the roadmap.

Cheers

Oli :)

**Comment by dynamicapps** [comment]
Just adding a second to this request.  
Oli, I have a request to persist the expanded/collapsed state.
I assume the only way to do this right now would be iterate and use the internal object or parse the HTML or to keep track opens/closes using the events.
Any thoughts?
Thanks.
John

**Comment by olifolkerd** [comment]
Hey All,

I have just pushed an update to the 5.1 branch that adds the proposed `isTreeExpanded` function to the row component.

This will be included in the next release.

Cheers

Oli :)
