### ISSUE TITLE
Row Details

### ISSUE THREAD

**Issue by LondonWebFactory** [olifolkerd/tabulator#3229]
Hi Oli,

As an idea, I bought a licence for the DataTables Editor for £85.00. If you had a similar system I would be happy to buy a licence for that too. 

Kind Regards,
Adrian

**Comment by olifolkerd** [comment]
Hey @LondonWebFactory 

While i want to keep Tabulator free for general use, i am actually looking to add a licensed Tier for tabulator 5.0, coming soon, for more coporate support and to allow users to support Tabulator.

Thanks for the info.

Cheers

Oli :)
