### ISSUE TITLE
dynamic rowContextMenu

### ISSUE THREAD

**Issue by ctlkkc** [olifolkerd/tabulator#3231]
Hi Oli, 

rowContextMenu seems to be set static when table initialized, but there are the following cases:
1. if chose single row, the rowContextMenu should only show some single row actions;
2. if chose multiple rows, the rowContextMenu should  only show some multiple rows actions;

those will involve a function to change the table's rowContextMenu dynamically based on rowSelectionChanged function. 

Is this/Will this be supported?

Thanks

**Comment by bornova** [comment]
Hi @ctlkkc,
As documented [here](http://tabulator.info/docs/4.9/menu#overview-generator), you can generate your own dynamic context menus.  Here is an example:
```javascript
rowContextMenu: (component, e) => {
    var menu = [];
    var selRows = component.getTable().getSelectedRows();

    if (selRows.length > 1) {
      menu.push({
        label: "Multiple rows selected",
        action: (e, column) => {/* Do stuff */}
      });
    } else {
      menu.push({
        label: "Single row selected",
        action: (e, column) => {/* Do stuff */}
      });
    }
    
    return menu;
}
```

**Comment by ctlkkc** [comment]
thanks a lot, that makes sense
