### ISSUE TITLE
Feature request: Left and right arrow cell nav

### ISSUE THREAD

**Issue by nmichale** [olifolkerd/tabulator#3232]
Just made this edit to tabulator in a project that I'm using it in, thought it could be useful for anybody else looking for it. This would be an edit to modules/keybindings.js. Change the navLeft and navRight functions to this (only works on inputs with "text" type). Check the caret position so it's at the end or beginning of the contents and also if an input is read-only it works

```javascript
navLeft:function(e){
		var cell = false;

		if(this.table.modExists("edit")){
			cell = this.table.modules.edit.currentCell;

			if (cell) {
					if(e.target.selectionStart == 0 || e.target.getAttribute('readonly')) {
						e.preventDefault();
						cell.nav().left();
					}
			}
		}
	},

	navRight:function(e){
		var cell = false;

		if(this.table.modExists("edit")){
			cell = this.table.modules.edit.currentCell;

			if (cell) {
				if(e.target.selectionStart == cell.value.toString().length || e.target.getAttribute('readonly')) {
					e.preventDefault();
					cell.nav().right();
				}
			}
		}
	},
````

And then add these to the `Keybindings.prototype.bindings`

I think this is helpful for users since the current Tab and Shift + tab are kind of far on the keyboard from up and down arrows

```javascript
navLeft: 37,
navRight: 39,
```

Thank you, I'm big fan of Tabulator,
Nick

**Comment by olifolkerd** [comment]
Hey @nmichale 

This should already work on all the built in formatters, if you feel this isnt the case please can you link to a JS fiddle that deomstrates your issue.

Cheers

Oli :)

**Comment by nmichale** [comment]
Hey @olifolkerd ,

Using Tab and Tab + Shift works to move from left to right on cells. However, specifically using the left and right arrow only lets you move around the cell not move between cells left and right. My feature suggestion would allow you to move to the left cell when you hit the left arrow and you are all the way left in the text of a cell. You can even see it here that when you are the all way left or right in a cell the caret just stops and you can't get to the next cell:

http://tabulator.info/examples/4.9#editable

I think it would be a lot more consistent with how up and down arrows are used for cell navigation by default and I have some end-users that have liked my modification. If this is available with some other feature let me know, but I don't even see 37 and 39 as key bindings in the source code (below), so I'm not sure how this would work in the current code.

https://github.com/olifolkerd/tabulator/blob/master/src/js/modules/keybindings.js#L169

Thank you,
Nick
