### ISSUE TITLE
Keep dataTree open/close status after setData

### ISSUE THREAD

**Issue by simusr2** [olifolkerd/tabulator#3233]
Hi, I'm using Tabulator 4.9 with dataTree enabled. When I do a data refresh (with setData) table reset dataTree open/close status.

After refresh all "groups" are close (or open, depends on initial configuration).

Can be added a persistence mode to keep dataTree status?

Thanks

**Comment by olifolkerd** [comment]
Hey @simusr2 

The `setData` function is intended to wipe all state in the table and load a new set of data. in your case i think you want to be using the `replaceData` or `updateData` functions which shouldnt alter the table state.

Cheers

Oli :)

**Comment by simusr2** [comment]
Thanks for your reply!
