### ISSUE TITLE
Group Header Freeze while vertical scrolling

### ISSUE THREAD

**Issue by n1ghthawk** [olifolkerd/tabulator#3234]
When I scroll vertically, the group header too scrolls away. I believe there is a need for a frozen group header option as it is seen in almost all grouping cases.

**Comment by olifolkerd** [comment]
Hey @n1ghthawk 

Thanks for the feedback

At the moment this is not something i would be looking to add to the table as it could lead to a very messy UI, especially when using nested groups.

Cheers

Oli :)
