### ISSUE TITLE
JSON export ignores 'titleDownload'

### ISSUE THREAD

**Issue by rathboma** [olifolkerd/tabulator#3235]
Take the following column:
```js
const columns = [ 
  {
    field: "a",
   title: "name",
   titleDownload: "Full Name"
  }

```

In the final json download we expect:

```json
{ "Full Name": "Bob Bobson" }
```

But we get:

```json
{ "a": "Bob Bobson" }
```

**Comment by olifolkerd** [comment]
Hey @rathboma 

This is the intended functionality for the JSON downloader, as it is a data format it contains the field names for the data not their titles.

Cheers

Oli :)

**Comment by rathboma** [comment]
So I have to use ids like c0 for my tables to avoid dupes, but would still like to specify a friendly name for download. Would you be open for a way to override this behavior?

**Comment by olifolkerd** [comment]
Hey @rathboma 

You make a fair point, while the naming of the variable doesn't fit its purpose in this case, i suppose it would be more consistent functionality and would certainly provide a good work around for your scenario.

I will reopen the issue and the PR

Cheers
Oli:)

**Comment by olifolkerd** [comment]
Closing this as the PR has been merged in and will be included in tommorows release.

Cheers

Oli :)
