### ISSUE TITLE
rowSelection formatter 'select all' and 'deselect all' does not trigger rowSelected and rowDeselected

### ISSUE THREAD

**Issue by fergalpower** [olifolkerd/tabulator#3238]
[https://jsfiddle.net/5ue7ca32/](url)

See jsfiddle above. 
When you click on top left of table to select all or deselect all rows, the rowSelected and rowDeselected callbacks are not triggered.

**Comment by bornova** [comment]
Hi @fergalpower,
There is also a `rowSelectionChanged` callback available which is triggered when select/deselect all is clicked.  Would that help?

[http://tabulator.info/docs/4.9/callbacks#select](http://tabulator.info/docs/4.9/callbacks#select)

**Comment by fergalpower** [comment]
Hi, thanks for your reply. I was able to find a workaround for the requirement I had. I just wanted to point out the behaviour above in case it is a bug. 
Regards,

Fergal.

**Comment by olifolkerd** [comment]
Hey @fergalpower 

Thanks for the headsup,

i will look into that further.

Cheers

Oli :)

**Comment by answerquest** [comment]
@bornova Thanks, `rowSelectionChanged` solved the same issue I was having.

**Comment by olifolkerd** [comment]
Hey All,

I have pushed a fix for this to the master branch and will include it in the next release.

Cheers

Oli :)
