### ISSUE TITLE
Change the Header Formatter - Code example wrong

### ISSUE THREAD

**Issue by schlundus** [olifolkerd/tabulator#3239]
**Website Page**
http://tabulator.info/docs/4.9/group#manage

**Describe the issue**
The shown example for the *setGroupHeader* function is wrong. It returns 
`   return count > 3; //all groups with more than three rows start open, any with three or less start closed`
which results in an exception because true/false is not a node.... 
It should return a string for example...

**Comment by olifolkerd** [comment]
Hey @schlundus 

Thanks for pointing that out, looks like a copy and paste error from another example,

I will get that fixed in the next site update.

Cheers

Oli :)
