### ISSUE TITLE
"Hide Ratings Column" option on the homepage sample of project page is not working

### ISSUE THREAD

**Issue by fahadash** [olifolkerd/tabulator#324]
Created this issue so one of the contributors fix the Sample.

On this page: http://olifolkerd.github.io/tabulator/

Under "Try it Yourself", the "Hide Ratings Column" button is not working. I am using Chrome Version 58.0.3029.110 (64-bit)

**Comment by alainpannetier** [comment]
Yes, should be 'hideColumn' and 'showColumn'. (new API).

**Comment by olifolkerd** [comment]
Haha,

Great spot! caught out by my own API changes :(

All sorted now, thanks for the help guys :)
