### ISSUE TITLE
Multiple keybindings

### ISSUE THREAD

**Issue by davidroeca** [olifolkerd/tabulator#3241]
**Is your feature request related to a problem? Please describe.**

Largely related to issue #2016

I'm trying to `table.navigateDown()` when the user hits the enter key in an editable cell. This problem is solved from the above, but now I can't `table.navigateDown()` when I hit the down key. There is likely a hack that can fix this but it would be really nice to just specify multiple keybindings.

**Describe the solution you'd like**

Right now we have a `keybindings` object that can be specified like the following:

```ts
{
  keybindings: {
    navDown: "13"
  }
}
```

However, this overrides the default down arrow key. It would be really nice to support an array of keybindings like this:

```ts
{
  keybindings: {
    navDown: ["13",  "40"],
  }
}
```

That way, this is more familiar and closer to the way excel behaves.

**Describe alternatives you've considered**

I'm currently digging into #2016 for a custom editor so I will post back if I find any better alternatives.

**Additional context**

Love this library, particularly the MIT license - this is definitely the best open source javascript table editor I've found, and I would like to start contributing when I've begun to wrap my mind around its internals.

**Comment by olifolkerd** [comment]
Hey @davidroeca 

Excellent idea, i will add that to the roadmap.

The 5.0 release *(currently in progress)* will see a complete rebuild of the source to make it easier to navigate.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @davidroeca 

I have pushed an update for this to the 5.1 branch and will include it in the next release.

Cheers

Oli :)
