### ISSUE TITLE
Column Calculations: Have the possibility to define only topCalcs, bottomCalcs

### ISSUE THREAD

**Issue by Joao-deOliveira** [olifolkerd/tabulator#3242]
*Is your feature request related to a problem? Please describe.**
When we define column calculations, the options available makes that both top and bottom rows are created. 

**Describe the solution you'd like**
Would be great if we can define on the **table.columnCalcs** = 'top' || 'bottom' || 'top-bottom'

**Describe alternatives you've considered**
Considering to delete the row with the totals if no topCalc or no bottomCalc

Thanks
Cheers
João

**Comment by olifolkerd** [comment]
Hey @Joao-deOliveira 

Tabulator only adds the rows needed if you dont defined any top-calcs you dont get a top calc row.

Cheers

Oli :)
