### ISSUE TITLE
Column Calculations:: When Multiple Pages, Custom Calculation and Custom Formatter functions are called everytime we change page

### ISSUE THREAD

**Issue by Joao-deOliveira** [olifolkerd/tabulator#3243]
**Describe the bug**
Custom functions for Column Calculations (topCalc and/or bottomCalc) are called multiple times with no reason for.. for example, are **called before the table being created** (_looks like one per each - top and bottom rows - plus one per page, plus one when table object is created_).

Custom functions are called twice when we change pages using paginator ( navigating page by page), looks like one time for the bottomCalc and another for the topCalc even if we just have one (the top of the bottom). 

**Tabulator Info**
4.9.3

**Working Example**
https://jsfiddle.net/JoaoDeOliveira/9jxzvm6b/138/

**Expected behavior**
The Column Calculations should be called only when the table has all rows on it and as the last action before rendering.
When changing page, the calculation should not be called as nothing has changed on the table, however are called (I suspect) on the rendering of the top and bottom calc rows ... which are not supposed to.

**Screenshots**
see video captured from the Fiddle execution
[2021-03-22_12-39-05.zip](https://github.com/olifolkerd/tabulator/files/6182174/2021-03-22_12-39-05.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10 Prof.
 - Browser FF and Chrome, latest versions

**Additional context**
This is not a good thing as for large tables has a Huge impact on performance and in user Experience, as every time user changes a page needs to wait several seconds (depends in how many columns and in the custom calculations complexity). Moreover, if we perform a table validation in a table with multiple pages the process is repeated every time we change a page.

**Comment by olifolkerd** [comment]
Hey @Joao-deOliveira,

Thanks for the info.

The column calculation that runs when the table is first initialized is done on an empty table and is done to initialize the calculation cell in case no data is subsequently loaded. As it is carried out on empty data it will not have any meaningful impact on performance and will be remaining as it is needed in certain circumstances

Your statement about carrying out the calcs is meaningful on locally paginated data, but data is loaded in remotely by page then these calcs need to change as new data comes in.

I have built out production workloads with tables using 1'000s of rows and calculation and not noticed any detrimental delay in calculations.

The row calculations are regenerated whenever the row render pipeline is triggered, which could include row filtering or grouping which certainly does affect the calculations, but there is no way at that point to know weather the pipeline trigger has affected the underlying data as any of the custom modules can register their own pipeline handlers and so it is safer to run everything again.

Unless there is a practical real life demonstration that can show a meaningfully degraded user experience then i will look to leave things as they are as they solve more problems than they cause in most usage cases.

Cheers

Oli :)
