### ISSUE TITLE
jsPDF 2.X not backwards compatible with 1.X

### ISSUE THREAD

**Issue by paulfilip** [olifolkerd/tabulator#3246]
I would like to use some new functions defined in jsPDF 2.X, but they are not backwards compatible with 1.X version.
The code from modules/download.js should be updated from new jsPDF to new jspdf.jsPDF.

**Comment by olifolkerd** [comment]
Hey @paulfilip 

Tabulator will be switching over to version 2.x in the upcoming 5.0 release.

Cheers

Oli :)
