### ISSUE TITLE
All cells always have an event handler for double click

### ISSUE THREAD

**Issue by knackstedt** [olifolkerd/tabulator#3248]
**Describe the bug**
All cells **always** have an event handler attached for double-click events. This causes performance issues because there are tons of event listeners loaded. 
Yes. I understand that I have a ton of columns being rendered. I just want to disable the double click handlers to reduce the footprint. I expect that setting `cellDblClick: false` would disable the attachment of event handlers, but I've had no dice.

**Tabulator Info**
- Which version of Tabulator are you using?
- 4.8/4.9

**Working Example**
Any Tabulator instance. Here's a CodePen:
https://codepen.io/Nazdak/pen/XWpbKQp?editors=0010
https://cdpn.io/Nazdak/debug/XWpbKQp/jVkpoERJeqxA

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Load data with lots of rows and columns
2. Use DevTools to inspect any rendered cell
3. See Event Handler for double click

**Expected behavior**
Option to not place double-click handler

**Screenshots**
![image](https://user-images.githubusercontent.com/29349167/112245991-5c4c0b00-8c28-11eb-8d75-44736867b50d.png)

**Desktop:**
 - OS: Windows 10
 - Browser Vivaldi / Chrome
 - Version 88.0.4324.85

**Comment by olifolkerd** [comment]
That event listener is needed to handle cell value selection.

Cheers

Oli :)

**Comment by knackstedt** [comment]
Is it possible to disable that functionality or move the event handler from individual cells to rows or the table itself?

I know part of the problem is that I misconfigured something or my CSS is causing the perf hit since the codepen has better performance compared to my project.

Thanks!

**Comment by olifolkerd** [comment]
Hey @knackstedt 

You make a gair
