### ISSUE TITLE
Get Cell div from CellClick function

### ISSUE THREAD

**Issue by stack-its** [olifolkerd/tabulator#325]
Hey Oli,

That columns OnClick function from #299  now doesn't work w/ 3.0 beta - what needs to change?

I did update it to : cellClick, but when I try to get cell object using 'cell', i.e. the actual cell div, it spits back functions, which I don't understand.
Thanks, Bill

**Comment by olifolkerd** [comment]
Hi Bill,

You are correct to use the ***cellClick*** callback.

All callbacks now pass in the new component objects. in this case the [Cell Component](http://olifolkerd.github.io/tabulator/docs/3.0/#component-cell)

This component can the be used to access all sorts of new features and parts of Tabulator, but in your case you want the ***getElement*** and ***getValue*** functions on this component:

```js
{title:"Name", field:"name", cellClick:function(e, cell){
        var value = cell.getValue(); //the current value of the cell
        var element = cell.getElement() //the query wrapped DOM element for the cell
    },
}
```

Let me know if that answers your question :)

Cheers

Oli
