### ISSUE TITLE
XLSX Download produces merged cells preventing sorting in Excel

### ISSUE THREAD

**Issue by joshbartley** [olifolkerd/tabulator#3252]
**Describe the bug**
Excel gives an error during sorting that the workbook contains merged cells and those most be unmerged before continuing. 

**Tabulator Info**
- 4.9.3

https://jsfiddle.net/joshbartley/txc032ys/2/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to the fiddle, click Download to Excel
2. Open in Excel, (enable editing), select the Amount column and Click Sort, Small to Largest. This is where things get difficult to reproduce, on my web app, we get an error the first time, in the JSFiddle, it takes 2 sorts to get the same error.
3. Click Sort again, select Amount and Largest to Smallest
4. Excel issues an error regarding merged cells of different height.
 
**Expected behavior**
No error should appear as merged cells were not requested. 

**Screenshots**
![image](https://user-images.githubusercontent.com/5738532/112502126-2f027880-8d60-11eb-914d-170fe895b409.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows, and Osx
 - Browser [e.g. chrome, safari] Chrome and Safari
 - Version [e.g. 22] Chrome 89, assuming latest Safari

**Additional context**
Debugging the issue lands me on the following line  https://github.com/olifolkerd/tabulator/blob/4.9/src/js/modules/download.js#L370 looking at the git blame there was a refactor so I don't know exactly why merges are pushed to SheetJS. Removing that line locally fixes the issue. I don't know what that would break so I didn't issue a PR as it looks like it's to fix a specific issue.

**Comment by olifolkerd** [comment]
Hey @joshbartley 

I have pushed a fix for this to the master branch and will include it in the next patch release.

Cheers

Oli :)
