### ISSUE TITLE
Failed undo for row movements if rows are sorted in descending

### ISSUE THREAD

**Issue by piroor** [olifolkerd/tabulator#3254]
**Describe the bug**

I'm trying to implement a behavior like "rows are basically movable, but prevent to move rows while they are sorted with columns". Thus I initialized a table with options `movableRows=true`, `history=true` and a `rowMoved` callback calling `table.undo()` on some conditions. Then I've realized that `table.undo()` sometimes fails to restore original order of rows.

**Tabulator Info**

- Tabulator 4.9.3

**Working Example**

https://jsfiddle.net/piro_or/ku0o79c2/9/

**To Reproduce**

1. Go to https://jsfiddle.net/piro_or/ku0o79c2/9/
2. Press the mouse button on the row with the index `0`.
3. Keep the button pressed and move your mouse up to the header row.
4. Release the mouse button over the header row.
6. The dragged row moves back to the bottom of the table, by the `table.undo()` called from the callback.
7. Press the mouse button on the row with the index `0`.
8. Keep the button pressed and move your mouse up to the header row.
9. Release the mouse button over  the header row.
10. The dragged row moves one line up, after the `table.undo()` called from the callback.
11. Repeat steps 7-10 multiple times. Then the dragged row moves one line up on every drop.

**Expected behavior**

At the step 10 (and further operations also), the dragged row is expected to be back to the bottom of the table consistently.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser and version: Mozilla Firefox 87.0, Google Chrome 89.0.4389.90

**Comment by piroor** [comment]
A moved row's internal information looks to become wrong when rows are sorted in descending. After a row is moved by a drag and drop, the moved row's `getPosition()` returns very odd values: `8`, `1`, `2`, and others. They are different from both the visual position and the logical position (in ascending) - I think it should be `0` (logical position) or `9` (visual position).

**Comment by olifolkerd** [comment]
Hey @piroor 

The position functionality is being overhaled in the 5.3 release as there was indeed some issue there around inconsistency in interpretation of the data.

Checkout the 5.3 release next month to see if it helps.

Cheers

Oli :)
