### ISSUE TITLE
Tabulator only works if imported with CDNJS

### ISSUE THREAD

**Issue by LukePrior** [olifolkerd/tabulator#3257]
I am importing Tabulator for use with my project through CDNJS. I am attempting to move to hosting it locally but am running into an issue, I'm not sure if this is a bug or an issue on my end so feel free to close/delete if that is the case. The way I would previously import it from CDNJS would be with:

`<script src="https://cdnjs.cloudflare.com/ajax/libs/tabulator/4.9.3/js/tabulator.min.js"></script>`

I have now download tabulator.min.js from CDNJS and Tabulator (error occurs with either download) directly and have linked to it locally with the following code:

`<script src="{{ url_for('static', filename='js/tabulator.min.js') }}"></script>`

This code does correctly link to the file as I'm using it to successfully import other libraries. When the code runs I receive the following error when trying to declare a table if importing Tabulator locally:

`Uncaught TypeError: Tabulator is not a constructor`

The error occurs at the line where I declare my table with the following command:

`table = new Tabulator(...);` (not all options shown)

If the library is successfully being imported how can there be an error with the local version but not the one hosted by CDNJS.

The only lead I have is that it's related to JQuery which seems confusing given that Tabulator no longer requires it. I have attached the exact error messages from Chrome below:

![image](https://user-images.githubusercontent.com/22492406/112717821-0ededf00-8f43-11eb-819a-2dbf1be52c96.png)

Any help would be greatly appreciated.

**Comment by olifolkerd** [comment]
Hey @LukePrior 

Tabulator has not supported CDNJS since version 4.0.

Checkout the [Install Documentation](http://tabulator.info/docs/4.9/install#sources-cdn) for compatible CDN's

Cheers

Oli :)
