### ISSUE TITLE
clearCellEdited()

### ISSUE THREAD

**Issue by jeetasingh** [olifolkerd/tabulator#3258]
table.clearCellEdited() is not clear the edited history. Is that a bug or i am missing something ??

    <ReactTabulator
      id="table"
      style={{
        maxHeight: "100%",
      }}
      index="FileId"
      columns={[]}
      data={this.state.results}
      ref={(ref) => (this.gridSearchRef = ref)}
      options={{
        history: true,
        pagination: "local",
        paginationSize: 20,
        placeholder: "No Files Available",
      }}
      footerElement={<span id="resultsCount" style={{ float: "left" }} />}
      pageLoaded={(pageNumber) => {
        this.setGridFooterText(pageNumber);
      }}
    />
this.gridSearchRef.table.clearCellEdited();
Clear cell edited is not working.
if I edited or not it always undefined I was looking for a way to clear edit history..

**Comment by olifolkerd** [comment]
Hey @jeetasingh 

If you think you have found a bug, please use the Bug Issue Template that will prompt you for all the information we need to help you out.

Also i'm afraid we can only deal with issues on the tabulator library, not for code using any of the wrappers written by 3rd party developers.

Cheers

Oli :)
