### ISSUE TITLE
Data-index Needed

### ISSUE THREAD

**Issue by stack-its** [olifolkerd/tabulator#326]
Oli,

Oh man, you stripped out cell's data-index & tabulator-col's data-index  !!
We need a way to store unique identifiers for those elements, as there is a need to cache that data so it can be used to move & show hidden elements & then move & set them back again.

Please, please (for the sanity of everything good) please put those data-index's back - they are desperately needed !!

**Comment by olifolkerd** [comment]
hey,

could you give me a specific example of what you used to do so i can understand what you need?

The cells never had a data-index, the rows did, is that what you mean? the cells now have a ***tabulator-field*** attribute with their field name, if that is what you are after.

Cheers

**Comment by stack-its** [comment]
Hey Oli,

I was freaked out because you changed so much, but after 2 days of work, I finally got the function I needed working - please don't change the layout again or I'll have a mental breakdown - ha !

BTW - Is there a way to hide my custom column's arrow (as mentioned in #325), as it won't ever be needed?
Thanks, Bill

**Comment by olifolkerd** [comment]
hey Bill,

if you want to hide the sorting arrow in the column header you can use the ***headerSort*** property of the column definition object, set it to ***false*** and the header will no longer allow for sorting.

Cheers

Oli
