### ISSUE TITLE
Toggling group visibility triggers a re-render of ALL group headers. (2+ times)

### ISSUE THREAD

**Issue by wesselvdv** [olifolkerd/tabulator#3260]
**Describe the bug**
The groupHeader callback is called way too many times, causing a lot of unnecessary re-renders. The biggest issue is that toggling any of the group headers causes a LOT of re-renders.

**Tabulator Info**
- Which version of Tabulator are you using?
Tabulator 4.9.3

**Working Example**
https://jsfiddle.net/b1esn2xy/

**To Reproduce**
1. Go to https://jsfiddle.net/b1esn2xy/
2. Click on any of the group header and observe the amount of calls to the groupHeader function.

**Expected behavior**

Only one invocation of the groupHeader function per header.

**Comment by wesselvdv** [comment]
Looking at the source code, I think I know what's going on. The groupHeader function is called for EACH row added into the group, which makes sense if you want to be able to show a count per group header. I'm not so sure why each group header would have to be re-rendered if one of 'm is toggled.

**Comment by wesselvdv** [comment]
I'm currently working around this by 'caching' the creation of DOM elements by a specific identifier. It doesn't prevent Tabulator from replacing the existing group header, but it does reduce the impact on FPS in the browser. Maybe something along those lines might be interesting for tabulator as well? As `trackBy` sort of function.

**Comment by olifolkerd** [comment]
Hi @wesselvd

Could you confirm you usage case in more detail? I'm struggling to see a practical scenario in which this would result in a significant performance bottleneck in real life?

Cheers

Oli :)
