### ISSUE TITLE
Rownum in PrintPreview

### ISSUE THREAD

**Issue by samad-kanton** [olifolkerd/tabulator#3262]
Tabulator displays the value "0" under "rownum" field when used with bottomCalc function during printing.

![MyShop OS _ Report Master — Mozilla Firefox 3_29_2021 6_35_13 PM](https://user-images.githubusercontent.com/31456450/112884677-512d2b00-90bf-11eb-977f-c37487cb017b.png)

**Comment by olifolkerd** [comment]
Hey @samad-kanton 

Good idea, i will stick that on the roadmap.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @samad-kanton 

I have pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)

**Comment by samad-kanton** [comment]
okay thanks, will check it out!
