### ISSUE TITLE
Provide a method to directly access the table instance in callbacks

### ISSUE THREAD

**Issue by vec2k4** [olifolkerd/tabulator#3264]
*Is your feature request related to a problem? Please describe.**
In version 4.9, some callbacks provide the possibility to directly access the table using `this`. An example is the `tableBuilt` callback:
```Javascript
const table = new Tabulator("#example-table", {
    ...
    tableBuilt: function() {
        console.log(this);
    },
    ...
});
```
Here, `this` is `Tabulator {options: {…}, columnManager: ColumnManager, rowManager: RowManager, footerManager: FooterManager, vdomHoz: null, …}`, which is the tabulator instance.

In version 5.0, since the new `ExternalEventBus` is used to trigger callbacks, the same code yields `ExternalEventBus {events: {…}, optionsList: {…}, dispatch: ƒ}`, so there is no way to directly access the table instance, or am I missing something?

**Describe the solution you'd like**
At least for the `tableBuilt` callback, a parameter should be introduced that pushes the table instance to the callback, like
```Javascript
this.externalEvents.dispatch("tableBuilt", this);
```
instead of https://github.com/olifolkerd/tabulator/blob/670f7bc951232e7186b3c2b77cae7f0ceedec2b0/src/js/core/Tabulator.js#L309

**Describe alternatives you've considered**
I tried using `Tabulator.findTable(...)`, but this is not an option since in a couple of callbacks, e.g. `tableBuilt` and `dataLoading`, it's not possible to lookup the table.

**Additional context**
Maybe it would be a good idea to add this parameter to all callbacks that do not provide a component object. At least for my usecase I make heavy use of this functionality in 4.9 and I'm currently a bit lost how to migrate my code to 5.0.

Another option would be to add the table instance to the `ExternalEventBus`, but this would introduce tight coupling which is maybe no good design.

**Comment by olifolkerd** [comment]
Hey @vec2k4 

The scope of all external events is set to the table so `this` in all events will be the table that called them.

Could you hold off on raising issues on the 5.0 branch yet. it isnt in public beta and if i have to answer questions about every feature before i have finished them its gonna really slow things down.

When it is finished *(it is taking a bit longer than i had hoped due to a busy couple of months at work)* i will put it out for beta for everyone to try and feedback on before the the release.

Cheers

Oli :)

**Comment by vec2k4** [comment]
Hey Oli,

that sounds good. I just ran into this issue when preparing my pull request for the 5.0 branch, but I have no problem waiting for the official release. And once again thumbs up for your great work! :thumbsup: :thumbsup:

Ralf
