### ISSUE TITLE
Buggy Implementation of columnResized Event

### ISSUE THREAD

**Issue by Elstermann** [olifolkerd/tabulator#3268]
Double click on a resizeable border will resize the column to fit the data it contains. Afterwards I expect a given columnResized callback to be called one time, which enables me to work with the new set columns width like `column.getWidth()`. But in contrast the columnResized event fires twice and only the old coulmns width value is available but not the new value.

- Tabulator 4.9
- https://codepen.io/elstermann/pen/wvggmMO?editors=0010

1. Grab the columns border and resize the columns width. When done the columnResized event fires one time and the new columns width is available via `column.getWidth()`-method. This is the expected behavior!
2. Now let Tabulator fit the columns width automatically by double clicking on the columns border. The columnResized event fires twice but the new columns width isn't available yet via `column.getWidth()`-method.

- Tested with various browsers always having the same issue(s).

After fiddling around for a while I got aware that the columnResized event actually fires everytime you click on a border of a resizable column which explains why the columnResized callback is called twice on double click. But on a single click no resizing occurs so the columnResized callback must not fire at all.

So actually we have 3 issues here:
1. columnResized fires every time when a resizables column border is clicked.
2. columnResized fires twice on double click (see above) but `column.getWidth`-method retrieves old value instead of the new width value.
3. columnResized doesn't fire at all when a column is resized per `column.setWidth`-method.

![Tabulator](https://user-images.githubusercontent.com/3453793/113421885-1af7f000-93cc-11eb-838e-1c258339dc5d.gif)

PS Tabulator Rocks <3

Cheers
Axel

**Comment by olifolkerd** [comment]
Hey @Elstermann 

Thanks for the feedback, I have pushed the following updates to the master branch and will include them in the next patch release.

- The `columnResized` event is now only triggered when the size of the column actually changes, if you click on the column resize handles without changing the width it no longer fires.
- When double clicking to resize to fit data the 'columnResized' event is now triggered after the column has changed size so you can access the correct width value.

In relation to your third point, that is the correct behaviour, the event is only triggered when a user changes the width of the column. If you resize a column width code then you can trigger any behaviour you like after calling the 1setWidth` function.

Cheers

Oli :)
