### ISSUE TITLE
Collapsible Non-tree Rows

### ISSUE THREAD

**Issue by AverTry** [olifolkerd/tabulator#3269]
*Is your feature request related to a problem? Please describe.**
The tree, is not like table rows, Responsive, forced collapse by blocking most rows collapsing works, but you lose EDIT, and SORT. And Table Nesting, has no collapse feature. 

**Describe the solution you'd like**
Nested Tables that can be hidden until needed, with a simple click. Like the Responsive collapse but with full control of content.
Example: TextArea's are very difficult to read and edit in a tiny square, by putting it in it's own row collapsed, you could open to full editing page? The possibilities are endless.

"GroupBy" is a great example, but with specific columns or tables.

**Describe alternatives you've considered**
Trying to hack your code to force a solution. But I'm a novice programmer.
If this is already possible and I've missed, But I pretty much took a magnifying glass to the Documentation and Examples.
Thank you For making your code Free.

**Additional context**
![Screenshot 2021-04-04 141155](https://user-images.githubusercontent.com/72357571/113509920-fb89d000-954f-11eb-8ab0-0d574efc09e4.jpg)

**Comment by olifolkerd** [comment]
Hey @AverTry 

You can already do this by adding a custom column to the table with a click event that hides your nested table.

Cheers

Oli :)
