### ISSUE TITLE
[Feature Request]Infinite scrolling

### ISSUE THREAD

**Issue by muthu32** [olifolkerd/tabulator#327]
As of version 3.0 tabulator renders its table using a Virtual DOM. 
So that is there any support for infinite scrolling in future release?

**Comment by olifolkerd** [comment]
Hey,

Could you give me an example of when you would need infinite scrolling in the table, so i can think of the best way to approach this.

As it stands you can load as many times into the table as you like with little performance impact. if you are talking about scroll navigation with keys then this is coming in this release, just not in the beta at the moment.

cheers

oli

**Comment by muthu32** [comment]
> Could you give me an example of when you would need infinite scrolling in the table

Some of my clients asked me to see all products without clicking on page no. Because they have lot of produkts to analyse daily, So that they don't want to click through pages.

These are my favourites when comes infinite scrolling.
http://w2ui.com/web/demos/#!combo/combo-9
https://paramquery.com/demos/infinite_scroll

**Comment by olifolkerd** [comment]
You have always been able to do that with Tabulator.

Simply don't include any of the ***pagination*** options in the table and it will render with a scroll :)

**Comment by muthu32** [comment]
Ok. I will try that :)

**Comment by olifolkerd** [comment]
Have a look at the [Examples Page](http://olifolkerd.github.io/tabulator/examples/3.0/) to have a play with some of the different tabulator configurations

**Comment by shaulnaim** [comment]
I don't see the example of an infinite scroll which means calling to the server to get the next package of rows when you scroll almost to the end.
do you have this Feature?

**Comment by olifolkerd** [comment]
Hey @shaulnaim 

You want to have a look at the {Progressive Loading Example](http://tabulator.info/examples/4.1#ajax-progressive)

Cheers

Oli :)

**Comment by shaulnaim** [comment]
@olifolkerd wow, thanks, look nice ..,.

i have 3 more questions, please.
1. when I use this progressive load is working with a virtual scroll together?
2. do you have angular implementations examples?
3. will it support IE 11? and how?

Thanks a lot, you are a saver...

**Comment by olifolkerd** [comment]
Hey @shaulnaim,

Please read through the website it explains everything.

As long as you define a table height the Virtual DOM will load correctly.

There is an [Angular Setup Guide](http://tabulator.info/docs/4.2/frameworks#angular)

And a [Browser Support](http://tabulator.info/docs/4.2/browsers#ie) page

If you cant find something, the search box on the top right of the site should get you to what you need.

Cheers

Oli :)

**Comment by shaulnaim** [comment]
managed to make it work  in angular 

now I am stuck with trying to implement tabulator 4.2  Nested data trees select all checkbox 
and when selecting parent to select all children of him.

can it be done using a column of checkboxes???
Thanks alot.

**Comment by olifolkerd** [comment]
@shaulnaim 

great to hear you are making progress

yes you can do that with a column of check boxes

Cheers

Oli :)

**Comment by shaulnaim** [comment]
thanks, @olifolkerd !
unfortunately, I couldn't make the tree grid work with a column of checkboxes so checking the parent of a group will select all its child's, tried using editor: 'tick' but it behaved really weird... :(
can you link me to a codepen example or so?

thanks for helping :)
