### ISSUE TITLE
setGroupBy does not work with dataTree set to true

### ISSUE THREAD

**Issue by IndyJoeA** [olifolkerd/tabulator#3271]
**Describe the bug**
With dataTree set to true, the table.setGroupBy() method does not set the grouping after the table has been created. If dataTree is set to false, the table.setGroupBy() method works correctly.

**Tabulator Info**
Tabulator version 4.9.3

**Working Example**
https://jsfiddle.net/kzy15st3/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to the jsfiddle link above
2. Above the table click on the "Group by Color" button
3. Notice that nothing happens
4. Change the table config option dataTree to false
5. Click Run
6. Click the "Group by Color" button and the "Remove Group" buttons and notice that grouping now works

**Expected behavior**
The table.setGroupBy() method should work whether the dataTree mode is turned on or off.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (v2004)
 - Browser: Chrome
 - Version: 89.0.4389.114

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 14.4.2
 - Browser: Safari
 - Version: 14.4.2

**Comment by epykure** [comment]
Any update related to this because I just noticed the same issue? @IndyJoeA : Did you manage to get a workaround? Thanks

**Comment by olifolkerd** [comment]
Hey all,

This should now be resolved in the 5.x releases.

Cheers

Oli :)
