### ISSUE TITLE
Use deep attribut in formatterParams.labelField

### ISSUE THREAD

**Issue by mhsis** [olifolkerd/tabulator#3273]
I tried to use an attribut in a child (for exemple att1.att2.att3) as labelField for my link. Currently, tabulator support just direct attribut (att1 in my exemple)

My solution is to parse labelField. If it contain a dot ".", i will get the first element as object, and the second,...
In my exemple:

- mydata = data[att1]
- mydata = mydata[att2]
- mydata = mydata[att3]

My final code is:

> if (formatterParams.labelField) {
				data = cell.getData();
				var labelArray = formatterParams.labelField.split(".")
				if(labelArray.length>1){
					var finalLabel =data
					for (var i = 0; i <= labelArray.length-1; i++) {
						finalLabel = finalLabel[labelArray[i]];
					}
					label = finalLabel;
				} else {
					label = data[formatterParams.labelField];
				}				
			}

**Comment by olifolkerd** [comment]
Hey @mhsis 

I have pushed the code for this to the 5.2 branch and will include it in the 5.2 release later this month. Rather than hard coding the "." symbol as the separator it pulls the symbol from the tables `nestedFieldSeparator` option.

Cheers

Oli :)
