### ISSUE TITLE
Sort column event is added to the entire header

### ISSUE THREAD

**Issue by iursevla** [olifolkerd/tabulator#3275]
**Describe the bug**
I want to sort the column but only in the arrow element icon, not the whole header.

**Tabulator Info**
- 4.7.2 but also happening in the latest version

**Working Example**
Any table in tabulator.info will do

**To Reproduce**
1. Just click on a column with a sort icon.  In the sort icon or the whole column content will do.

**Expected behavior**
I expect, to have the hability to only sort when clicking on the sort icon, not the whole column.

**Additional context**
Here in line 58 the click event is being added to the entire column.

https://github.com/olifolkerd/tabulator/blob/master/src/js/modules/sort.js#L58

**Comment by olifolkerd** [comment]
Hey,

This is not a bug, this is the correct behaviour of the table.


Thanks

Oli

**Comment by iursevla** [comment]
So it's expected that the click on the whole header to invoke the sorting? 

I want to use the sort icon to sort and the click on the header to select the whole column cells. Do you have any idea how to solve such a case?

Thanks

**Comment by iursevla** [comment]
For anyone that might have the same problem, i "solved" it by:

```js
 headerClick = (event) => {
        if (columnOptions.headerClick) {
          columnOptions.headerClick(event, getColumnComponentMethod());
        }
        event.stopImmediatePropagation();
};

if (headerSort) {
          this.setArrowClickEvent(tabulatorColElement);
}

---

setArrowClickEvent(colElement) {
      const tabulatorArrowIcon = colElement.firstChild.querySelector('.tabulator-arrow');
      tabulatorArrowIcon.onclick = (e) => {
        const currentSorting = this.tabulatorTable.tabulator.getSorters();
        const currentDirArray = currentSorting.filter((obj) => {
          return obj.field === this.field;
        });
        const newDir = this.getNewDir(currentDirArray);
        const sorting = [{column: this.field, dir: newDir}];
        this.tabulatorTable.tabulator.setSort(sorting);
        e.stopImmediatePropagation();
      };
    }
```

With this, the header click will  only trigger the headerClick event and the sort icon click will only trigger the sort action.
