### ISSUE TITLE
How to get tabulator table checked data?

### ISSUE THREAD

**Issue by ezat-dev** [olifolkerd/tabulator#3276]
![Tabulator_cellClick](https://user-images.githubusercontent.com/76994435/114698327-f3a10b80-9d59-11eb-90ac-00941d1e771a.PNG)

Currently, the data in the picture is expressed by calling the data in Ajax.

So, I want to display the checked data in another table by clicking the'button' as shown in the picture above.

Which function should I use?

Thank You.

**Comment by bornova** [comment]
Hi @ezat-dev,
You can use `table.getSelectedRows()` as documented here: http://tabulator.info/docs/4.9/select#manage

Example:
https://jsfiddle.net/2v5tzca6/

**Comment by ezat-dev** [comment]
Very good. Thank you. Examples and explanations have been very helpful.
