### ISSUE TITLE
incorrect npm tag: 'cookie'

### ISSUE THREAD

**Issue by connorjclark** [olifolkerd/tabulator#3277]
This results in Bundlephobia suggesting libraries that deal with cookie-management, none of which are related to rendering tables:

https://bundlephobia.com/result?p=tabulator-tables@4.9.3

**Comment by olifolkerd** [comment]
Hey @connorjclark 

Thanks for letting me know, it was originally tagged cookie because it had a lot of cookie based functionality, but this is no longer the case.

I have removed the keyword on the 5.0 branch and will include it in the 5.0 release.

Cheers

Oli :)

**Comment by connorjclark** [comment]
Thank you sir!
