### ISSUE TITLE
Tabulator Midnight theme - row highlighting misbehaves during scroll

### ISSUE THREAD

**Issue by NbrTDB** [olifolkerd/tabulator#3278]
**Describe the bug**
When using the Tabulator Midnight theme, the even-odd row highlighting shifts while scrolling the table (this does not appear to happen on the default Tabulator theme). Shown below are two screenshots taken between scrolls; you can see how the even/odd rows have swapped background colouration.

While scrolling this also makes the table look weird (it looks like somethings wrong/it's not scrolling smoothly as the row colouration appears to "hang" or "wobble" in place instead of scrolling with the text).

It can take a bit of scrolling for the issue to occur; in the JSFiddle I have provided, it begins to happen around the 30th row. 

**Tabulator Info**
Latest version 4.9.3

**Working Example**
https://jsfiddle.net/u910ed2L/6/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Scroll down the table; around the 30th row, the row backgrounds start to oscillate/change while scrolling
 
**Expected behavior**
Same behaviour as normal Tabulator theme (i.e. even/odd rows always retain their assigned background colour).

**Screenshots**
![image](https://user-images.githubusercontent.com/21238754/115016162-a08b9d80-9eac-11eb-9122-2de74f64b29f.png)
![image](https://user-images.githubusercontent.com/21238754/115016209-af725000-9eac-11eb-8543-7256b6f4963e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Browser: Chrome 89.0.4389.114 (also occurs on NW.js, v0.50.1)

**Comment by NbrTDB** [comment]
I'm wondering if this is just a CSS issue, really. As a workaround, using the default theme and overriding certain classes to get the same kind of midnight-theme appearance seems to work perfectly well and there are no problems with rows swapping background colour on scroll.

**Comment by olifolkerd** [comment]
Hey @NbrTDB 

This no longer appears to be an issue in the 5.x releases

Cheers

Oli :)
