### ISSUE TITLE
Dropdown Forms

### ISSUE THREAD

**Issue by AverTry** [olifolkerd/tabulator#3279]
Finding how to do things involves a lot of searching and experimentation.
I'll include my partial solution, but the main issues I haven't figured out is, -
   _Sub-Tables Data printing, downloading/Exporting, with the main row data. 

There is plenty of room for improvement here, and would be a much needed addition.

Here is a partial solution for Dropdowns.
[https://github.com/AverTry/Tabulator-Local](https://github.com/AverTry/Tabulator-Local)

**Comment by olifolkerd** [comment]
Thanks for getting in touch.

I would not be looking to add built in form functionality to Tabulator. It is primarily a library for building tables and I want to keep it focused on that.

That being said you can use the row formatters to add that sort of custom functionality for your tables.

Cheers

Oli
