### ISSUE TITLE
Refresh question on data call.

### ISSUE THREAD

**Issue by ezat-dev** [olifolkerd/tabulator#3280]
I am using ajax to call data.

I set it up as follows.

function getTestList(){
  testTable = new Tabulator("#test_list", {
    height:"550px",
    layout:"fitColumns",
    selectable:true,	//row Select
    reactiveData:true,
    rowContextMenu: headerMenu, //add context menu to rows
    headerHozAlign:"center",
    ajaxConfig:"POST",
    ajaxLoader:false, 
    ajaxURL:"/test/testListDetail",
    ajaxProgressiveLoad:"scroll",
    ......
  });
}

1. Call the "getTestList()" function when the page is loaded.
2. After registering and modifying data
"testTable.replaceData();" You are running the method.
3. The data in the table is being reloaded after refreshing.

*****
I tested the settings by referring to the content and documentation of the issue, but the refreshing phenomenon did not improve, so I ask a question.

If there are any settings to improve this, can you tell me?

Thank You.

**Comment by olifolkerd** [comment]
I am unsure what yu are actually asking here. you have pasted some code and some steps to do something but not mentioned what it is you actually want to acheive

**Comment by ezat-dev** [comment]
Thank you for your reply.

http://tabulator.info/examples/4.9?#adddel

What I want to achieve is that the data is updated without a refresh like in the example above.

I am fetching data from the current server. Is there a way to fetch the data without blinking?

**Comment by olifolkerd** [comment]
Hey @ezat-dev 

Please ask your question on Stack Overlfow. This issues list is reserved for bug reports and feature requests only.

Cheers

Oli :)
