### ISSUE TITLE
Different rowContextMenu for master and nested tables

### ISSUE THREAD

**Issue by RudiSchloesser** [olifolkerd/tabulator#3281]
I have a data structure which looks like this:
>
> >  warehouse1
> > > |-- Input
> > > |-- Storage1
> > > |        |-- Level1
> > > |        |        |-- Sublevel1
> > > |        |-- Level2
> > > |-- Storage2
> > >          |-- Level1
> > >          |        |-- Sublevel1
> > >          |-- Level2

> >  warehouse2
> > > |-- Input
> > > |-- Storage1  
> > >  ...

I'm using a table for the warehouses with a nested table with dataTree enabled using a rowFormatter under each warehouse.
Everything works perfectly. The only point missing is to have different rowContextMenus for the main and the
nested table, one being used to edit/delete warehouses, while the other used to edit/delete storages.

The rowContextMenu assigned to the warehouse table is also showing up in the nested table, where
I have assigned a different rowContextMenu.

Br, Rudi

**Comment by LilDevil** [comment]
You can already do that. Use a [menu generator function](http://tabulator.info/docs/4.9/menu#overview-generator) and detect which table/row it's in, and return the appropriate menu.

**Comment by RudiSchloesser** [comment]
Thanks for the hint. I tried this, but the component.getData() returns the data of the row in the master table, not the nested one.

**Comment by RudiSchloesser** [comment]
Thanks for the hint, got it to work
