### ISSUE TITLE
Selectable Rows With Tickbox - Mark Only the Tickbox or the TickBox and highlight the row

### ISSUE THREAD

**Issue by Joao-deOliveira** [olifolkerd/tabulator#3282]
*Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
when defining a column type 'Selector' (Selectable Rows With Tickbox) have the possibility to define if will use the Selector only or if also highlights the row.

This will allow to have multiple selections without saturating the UI, additionally, avoid to mix with some particular cell highlighting we may have implemented.

**Describe alternatives you've considered**
Create my Own selector (following some tips on StackOverflow)

**Additional context**
N/A

Thanks
Cheers
João

**Comment by MatthewJJohnson** [comment]
You can use the rowClick or cellClick events to conditionally preventDefault() which would stop (or allow) the row from being selected.

**Comment by olifolkerd** [comment]
Hey @Joao-deOliveira 

Thanks for the feedback, in this case im not really sure if a whole new setting is needed, you could just override the `tabulator-selected` class that is applied to the row to style it however you like for your site.

Cheers

Oli :)
