### ISSUE TITLE
Consider using Luxon instead of Moment.js

### ISSUE THREAD

**Issue by barbedCoil** [olifolkerd/tabulator#3283]
I found that the Date sorter requires moment.js which is fine.  However once I added the moment.js lib to my project Tabulator did not recognize it.  I did not see any additional directions so I had just included in the script tag of the page.

Could not get past the message that moment was required so I implemented my own sorter using Luxon (by the same team), it was fairly simple as shown (yes var assignments not needed but..):

```
sorter:function(a, b, aRow, bRow, column, dir, sorterParams)
{
    let dtA = luxon.DateTime.fromISO(a);
    let dtB = luxon.DateTime.fromISO(b);
    return dtA.toMillis() - dtB.toMillis()
}}
```
According to the Moment.js team:  **We now generally consider Moment to be a legacy project in maintenance mode. It is not dead, but it is indeed done.**

See the recommendations further down the following page.  Luxon is a great library as are many of the others without all of the bloat and with immutable dates.

https://momentjs.com/docs/#/-project-status/

**Comment by olifolkerd** [comment]
This is already on the roadmap for the 5.0 release and will be going in next week.

Cheers

Oli :)
