### ISSUE TITLE
Leverage on Json Schema for data display on Tabulator.

### ISSUE THREAD

**Issue by madruga8** [olifolkerd/tabulator#3284]
There are very good form Builders like json-editor among others that uses Json Schema to build forms automatically.

If Tabulator could leverage on this data standard of Json Schema to display those data it will be a great time saving for those working with document databases.

**Comment by olifolkerd** [comment]
Tabulator already parses in JSON data, I am unsure what it is you are asking for?

**Comment by madruga8** [comment]
> Tabulator already parses in JSON data, I am unsure what it is you are asking for?

I was thinking about tabulator to use the standard of JsonSchema for forms and data types. 

But im already parsing data from json-editor but a lot of formatter and "ifs" to separate each column by its name for correct format.
