### ISSUE TITLE
Persistence Config -> Question/Bug/"Feature"

### ISSUE THREAD

**Issue by schlundus** [olifolkerd/tabulator#3287]
Create a table with some config like 
--schnipp--
```
layout: 'fitDataFill',
resizableColumns: true,
pagination: 'local',
movableColumns: true,
persistence: {
	sort: true,
	columns: ['width'],
},
```
--schnapp--

The persistence config is saved within localstorage.

Now do this:
1. resize a column by hand (mouse)
    => width is correctly updated in localstorage
	
2. reload the page (that means create a new instance of the table) =>
   the persistence config takes effect and the column has the correct size from localstorage

Now do this:

Open page, table is created and now 
1. resize a column by hand (mouse)
    => width is correctly updated in localstorage
2. now call setData with new data (received by a search) followed by a table.redraw
   and now the manually resized column has the size BEFORE the resizing although in the localstorage is the correct size
   
   if i do a redraw() it works as intended, if i do a redraw(true) then it seems that it doesn't take care of  the persistence config as the code steps through
--schnipp--
```
	"fitDataFill": function fitDataFill(columns) {

		columns.forEach(function (column) {

			column.reinitializeWidth();
		});
```
--schnapp--		
   After that the column has its initial size from creation.

	
Is this a bug or intended or did i something wrong?	

Tabulator Version is 4.9.3

**Comment by olifolkerd** [comment]
That might be a bug there, i will look into that further.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @schlundus 

This should be resolved in todays patch release.

Cheers

Oli :)
