### ISSUE TITLE
Persistent column order for generated columns

### ISSUE THREAD

**Issue by TheCelebrimbor** [olifolkerd/tabulator#3288]
**Describe the bug**
Persistent column order does not work for columns which have no `field` option but are generated via formatters.

**Tabulator Info**
- 4.9.3

**Working Example**
https://jsfiddle.net/1qjvbf30/2/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:

1. Move the Id column to a new position
2. Run the Fiddle again
3. The column will move back to its original position

**Expected behavior*
Column order should stay the same between reloads

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 90.0.818.46

**Comment by LilDevil** [comment]
I've run into this before. I solved it by giving the columns a `field` name, even if it doesn't do anything. It should probably be fixed properly, but you can use this workaround in the meantime.

**Comment by TheCelebrimbor** [comment]
> I've run into this before. I solved it by giving the columns a `field` name, even if it doesn't do anything. It should probably be fixed properly, but you can use this workaround in the meantime.

Doesn't it throw warnings in the console if we do that ? Will try it out tho

**Comment by olifolkerd** [comment]
without a field name there is no property name for the persisted value to be stored against so @LilDevil provides the correct approach.

Cheers

Oli :)
