### ISSUE TITLE
Misalignment during horizontal scroll on Windows HiDPI monitor

### ISSUE THREAD

**Issue by ifsjbm** [olifolkerd/tabulator#3289]
**Describe the bug**
The performance of horizontal scroll is bad when window.devicePixelRatio is greater than 1.25. It works perfectly if the window.devicePixelRatio is 1.0 or 1.25, but when it is 1.5 or higher, then the column-headers are not aligned with the data-cells during horizontal scrolling. Furthermore, the frozen column is "jumbing" while scrolling.

**Tabulator Info**
4.9.3

**Working Example**
https://jsfiddle.net/da82031/apey0zuq/7/

**To Reproduce**
1. Ensure that the scale-factor on your Windows desktop is set to 150% or higher
2. Open the jsfiddle example above
3. Do horizontal scrolling
4. While scrolling, you'll see that the column-headers are not aligned with the data-cells and that the frozen column is "jumbing"

**Expected behavior**
While scrolling, I expect the column-headers to be smoothly aligned with the data-cells and that the frozen column has a fixed left-aligned position without "jumbing"

**Desktop:**
 - OS: Windows 10 pro
 - Browser [Chrome, Edge]
 - Version [90.0.4430.93, 90.0.818.49]

**Additional context**
Actually, you don't even need my jsfiddle. It's also reproducable in the frozen-column example on http://tabulator.info/examples/4.9#frozen-col

**Comment by ifsjbm** [comment]
Hi,
We're currently in the process of evaluating which table/grid library to use in our application. And we think that you've developed a fantastic product, so we're seriously considering to use it. However, the way our product works makes horizontal scroll performance a really important issue, so it's important for us to know if it is something you expect will be addressed in 5.0 or in a future release? What do you think?
Regards
Jesper

**Comment by mike-lischke** [comment]
This bug is not only limited to Windows. I see heavy disalignment on horizontal scroll on macOS 11 as well:


https://user-images.githubusercontent.com/2398704/120480784-b2b79180-c3af-11eb-8ac8-15d99f9c06e8.mp4
