### ISSUE TITLE
Clicking on Header filter shifts the table X scroll position.

### ISSUE THREAD

**Issue by Saithorx** [olifolkerd/tabulator#3290]
**Describe the bug**
I have an issue where clicking on column heading filter, when the table is scrolled to the right, causes the table to scroll and the table headers to become misaligned with the data below.

**Tabulator Info**
This occurs in all versions after 4.1

**Working Example**
https://jsfiddle.net/4sw1fxLz/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle:
1. Go to https://jsfiddle.net/4sw1fxLz/
2. Scroll the table all the way to the right
3. Click in the column 7 filter textbox

**Expected behavior**
I do not expect the table to move it's position when clicking inside of the textbox.

**Screenshots**
I pointed some red arrows at numerous areas where the table either scrolled or the columns became misaligned.
![tabulator_issue](https://user-images.githubusercontent.com/83367584/116454438-fdcd0a80-a82d-11eb-99e2-6fb3adf9b8ea.jpg)

**Desktop (please complete the following information):**
 - Google Chrome Version 90.0.4430.85 (Official Build) (64-bit)

**Additional context**
Scrolling left and right, especially when scrolled further to the right, seems to throw off the column alignment.

**Comment by Saithorx** [comment]
Just an FYI. 
My current workaround is that I create an empty column and when the user scrolls to the right, I scroll them back to the left until they line up with my last data column. 
https://jsfiddle.net/4sw1fxLz/3/

**Comment by olifolkerd** [comment]
Hey @Saithorx 

I have pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)
