### ISSUE TITLE
Significant difference in scrolling right vs left with virtualDomHoz enabled...

### ISSUE THREAD

**Issue by srixmk** [olifolkerd/tabulator#3291]
When virtual DOM - Horizontal is enabled (as in http://tabulator.info/examples/4.9), dragging the horizontal scroll slider to the right results in quick table update, but the table refresh when moving the scroll slider back to the left is extremely slow, often resulting in unresponsive page warning in the browser (Firefox 85 and Chrome 72 on Linux).

**Comment by olifolkerd** [comment]
Hey @srixmk 

The hoz vdom is currently only an experimental feature, it has been completely rewritten for the 5.0 release.

Cheers

Oli :)
