### ISSUE TITLE
Can't edit a cell editable.

### ISSUE THREAD

**Issue by David-Baron** [olifolkerd/tabulator#3294]
The parameter: autoColumns:true, disables editable fields 

tabulator 4.9.3
browsers: chrome, firefox, edge

[Link in codpen](https://codepen.io/david-baron/pen/NWdZexV)

**Comment by olifolkerd** [comment]
That is because you can't use the columns option if you are using auto columns. If you read the next section in the autocolumns documentation you will see it demonstrates how to use the autoColumnsDefinitions option to setup auto generated columns

Cheers

Oli

**Comment by David-Baron** [comment]
Thank you for your reply. 
Yes I had started my script with autocoluns and continued with colums without removing the option which caused this error. While browsing the web, I noticed that many were having problems with editor: .... and that it could come from there. I posted this to see if colums option couldn't have a function to disable this autocolums option or submit a warning in the console.

**Comment by olifolkerd** [comment]
If you don't want to use autocolumns, simply don't enable it in the table options. If you do want to use it then follow the auto columns documentation.

I think you may have gotten confused because you are trying to import from and html table at which point you don't need to use auto columns at all

**Comment by David-Baron** [comment]
Yes you are right!
But if we do not read our code there is no error in the console to prevent this kind of stupidity and we go around in circles for hours to find this error while a simple log in case of error would be welcome. (not for me because I know it now).
