### ISSUE TITLE
Retrieving Data 

### ISSUE THREAD

**Issue by vonschbo** [olifolkerd/tabulator#33]
Hello

When I use
```javascript
    var data = $("#example-table").tabulator("getData");
```
as this will return an array containing the data objects for each row in the table. 
I use toSource to view the edited data. 
However, I find that some attributes do not have " ".

```javascript
    [ { id:"3",
"Date Extracted":"12/3",
Experiment:"normal"},
{ id:"2",
"Date Extracted":"12/3",
Experiment:"powder",
Notes:"" },
{ id:"1",
"Date Extracted":"12/3",
Experiment:"fine",
Notes:"" }
]
```

**Comment by olifolkerd** [comment]
This is how Javascript represent object keys, if they do not have a space in the string then the key does not need quotation marks.  They are not values they are property keys

**Comment by vonschbo** [comment]
Thanks, I see.

**Comment by olifolkerd** [comment]
If you are looking to generate a JSON string from the data can i suggest using the ***JSON.stringify()*** function:

```js
var json_string = JSON.stringify($("#example-table").tabulator("getData"));
```
