### ISSUE TITLE
Context Menu Close Event

### ISSUE THREAD

**Issue by mikeciz** [olifolkerd/tabulator#3300]
We have a slew of great callbacks to use for context menus listed here: [Callbacks](http://tabulator.info/docs/4.9/callbacks), but it would be really useful to get one for when the context menu (cell/row/header) closes.
It's easy to know when the user clicks a button in the menu using the _action_ function, but we don't get any callback when a menu is cancelled (escape or clicked outside Menu).

**Why is this useful?** 
I'd like to add a CSS style to the cell that is right clicked so that it highlights the cell's border, otherwise it's not super clear which cell was clicked and without tapping into the "hideMenu" function somehow, I don't know when to remove the cell border.

**Is your feature request related to a problem? Please describe.**
Yes, I'd like to know when the menu closes.

**Describe the solution you'd like**
It would be nice to trigger a callback that will return the cell, row, or header that had been the focus of the initial context menu.

**Describe alternatives you've considered**
1. I tried using **Tabulator.prototype.extendModule** but that only works with objects and therefore doesn't allow me to replace the hideMenu function.  I'm no expert, so perhaps someone smarter than me can show me.
2. You might build in some CSS to automatically add in a style for those cell/row/headers that are the source of the context menu's attention.

**Additional context**
I love this lib! Keep up the great work folks!

**Comment by olifolkerd** [comment]
Hey @mikeciz 

Excellent Idea! i will stick this in the roadmap for a future release. Or if you fancy make a PR on the 5.0 branch to have it included in the next release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @mikeciz 

I have just pushed an update to the 5.1 branch that adds `menuOpened` and `menuClosed` events.

It will be included in the next release.

Cheers

Oli :)
