### ISSUE TITLE
Need to Click Twice to Open Custom SelectBox using Editor Option of Tabulator

### ISSUE THREAD

**Issue by VirViru7** [olifolkerd/tabulator#3303]
Hi All,

I am using tabulator grid for my project and I am implementing custom select box using editor option of the tabulator.

**Issue :** First time when I click on select box it's only getting focus, while clicking on second time I can able to open option list of dropdown.

Is it possible to open custom select box on **first click** in Tabulator???

**Note :** I have also tried to create custom select box using Formattor option Tabulator but It's having different design so It's not gonna help me.

**Comment by olifolkerd** [comment]
Hey @VirViru7 

If you wish to submit a bug report, please use the Bug Issue Template, and include a link to a JS Fiddle or Code Pen that demonstrates the issue. Without seeing how your table is configured it is pretty much impossible to offer advice to fix the issue.

Cheers

Oli :)
