### ISSUE TITLE
Tabulator for Svelte

### ISSUE THREAD

**Issue by cacuestai** [olifolkerd/tabulator#3304]
Hello:

It is a great project that I recommend in my courses. I have not tested it with the Svelte framework yet and would like to know if it is supported.

Thank you!

Carlos

**Comment by maku** [comment]
@cacuestai  I don't think it's officially supported. but I use it with svelte without any problems

**Comment by cacuestai** [comment]
Now everything is clear:
http://tabulator.info/docs/5.0/frameworks#svelte

**Comment by Gildedter** [comment]
I'm having problems with this, I'm using it with svelte-kit, I followed the install instructions (`npm i -D tabulator-tables`), but I keep getting this error: `500 import not found: default` on the svelte component example included in the docs
