### ISSUE TITLE
Tabulator event on adding every record

### ISSUE THREAD

**Issue by arelbernardo** [olifolkerd/tabulator#331]
Hi Oli,

Thank you for this plugin. So far, this is very nice.

I just want to ask if there's an event listener every time tabulator adds a record on the table when the table initialize?

For example:

```
var myTable = '#myTable';

$(myTable).tabulator({
**onEveryRecordAddedToTheTable**: function() {
    //code and event goes here
},
columns: [
    {column1}, {column2}, ...
]
});
```
Currently, I'm using _formatter_ on every columns to custom and call some functions

Thanks!

**Comment by olifolkerd** [comment]
There is no specific callback for row added to dom, but if you are looking to capture the point at which a row is first rendered you could use the ***rowFormatter*** callback:

$("#example-table").tabulator({
    rowFormatter:function(row, data){

    },
});

**Comment by arelbernardo** [comment]
I have this table:

link: http://prntscr.com/fc6pss 

with a column **_Added By_**

I want to create a callback whenever a row is added, I'll put it in an array **`addedByPerson`** without duplicates. I don't want to use a separate code for that if tabulator has that feature. 

My closest solution is to add an empty column with **`formatter`** and call an external function for me to add the person into **`addedByPerson`**

For example:


```
var init = function () {
    
    var sampledata = [
        {title: 'Title1', added_by: 'Daryl Bernardo', date_added: 'May 23, 2017'},
        {title: 'Title2', added_by: 'Oli Folkerd', date_added: 'May 24, 2017'},
        {title: 'Title3', added_by: 'Mark Zuckerberg', date_added: 'May 25, 2017'},
        {title: 'Title4', added_by: 'Bill Gates', date_added: 'May 26, 2017'},
        {title: 'Title5', added_by: 'Paul Allen', date_added: 'May 27, 2017'}
    ];
    
    $("#example-table").tabulator({
        data: sampledata,
        columns: [
            {   title: 'Title', field: 'title'  },
            {   title: 'Added By', field: 'added_by'    },
            {   title: ' &nbsp; ', field: 'date_added'  },
            {   title: ' &nbsp; ', visible: false,
                formatter: function (value, data, cell, row, options, formatterParams) {
                    addAddedByFilterToArray(data.added_by);
                }
            }
        ]
    });
};

var addAddedByFilterToArray = function(added_by) {
    //code goes here
};

init();
```

Thanks

**Comment by alainpannetier** [comment]
Dear Daryl,

You are using 2.x I presume. In tabular 3.0 you would have these callbacks
I believe

http://olifolkerd.github.io/tabulator/docs/3.0/#callbacks-row

For addition, deletion, update, moved, click, dclick, rclick

**Comment by arelbernardo** [comment]
Hi Alain,

Thanks for the heads up. Currently I'm using 2.12 but I will switch to 3.0 after the beta testing. 

Regarding on your link provided, I don't see any callbacks that will be useful on my problem (those will be triggered only when a user interacts with the row in the table). The closest solution for me I think is to use a **`formatter`** on a column and call a function to solve my problem.

So I think that tabulator haven't that feature yet that there will be a callback when a row is added to the table upon initialization.

Anyway, I think that my solution will fit the problem. Thanks for tabulator. I'll use this in future developments.

-Daryl
