### ISSUE TITLE
headerFilter select type calls ajax on initial click instead of selected option

### ISSUE THREAD

**Issue by xpresas** [olifolkerd/tabulator#3311]
**Describe the bug**
As you can understand we are trying to build an fully ajax table with sorting, filtering and etc. Tabulator is an amazing tool so thanks for that!.
But I came into a weird problem which happens when you have an already selected headerFilter with a value, and you try to change it.
What happens is when you normaly use 
`{field:"orderStatus", headerFilter:"select", headerFilterParams:{values:["cancelled", "Completed"]}}`
it fires an ajax event with a form data looking like this:
```
"page" => "1"
    "perPage" => "10"
    "filters" => array:1 [
      0 => array:3 [
        "field" => "orderStatus"
        "type" => "like"
        "value" => "Completed"
      ]
    ]
```

Then for example if you want to change filter ``orderStatus`` to `cancelled` you use your mouse to click on the headerFilter to get the dropdown to see the available values it instantly fires an ajax event with a form body like this:
```
"page" => "1"
    "perPage" => "10"
    "filters" => array:1 [
      0 => array:3 [
        "field" => "orderStatus"
        "type" => "like"
        "value" => array:1 [
          0 => "Completed"
        ]
      ]
    ]
```
Then ofcourse my backend gives me an error because it waits for the filter value to be a string.
**Tabulator Info**
- Which version of Tabulator are you using?
Tabulator 4.9.3
**Working Example**
I cant give you an example to codepen because it needs to be set to `ajaxFiltering: true`

**Expected behavior**
As I understand the problem is that headerFilter with a type of select fires an ajax on dropdown expand action. It would be cool to either turn it off or stop it from rendering an array of values.

**Additional context**
I might have not seen an option for this so I am sorry in advance.

**Comment by xpresas** [comment]
Dont get me wrong I can simply check the incoming value in my backend and adjust it. Its just weird that on the dropdown click it sends another ajax event with a slightly different request body.. :)

**Comment by olifolkerd** [comment]
Hey @xpresas 

Thanks for getting in touch,

This issue has already been reported and is on the list to be fixed in the next release.

Cheers

Oli :)
