### ISSUE TITLE
Add `filtered`-logic for `deselectRow`, simular to `selectRow(true)`

### ISSUE THREAD

**Issue by exetico** [olifolkerd/tabulator#3313]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
The [Row Selection](http://tabulator.info/docs/4.9/select) has the function called `selectRow`, which supports `true` as the first argument, to select only the filtered rows. Please add the same logics to `deselectRow`.

In short: I would like to have the option to use `deselectRow(true)`, like we have with `selectRow(true)`.

**Describe alternatives you've considered**
I can't come up with any alternative solution.

**Additional context**
Maybe it sounds wierd, but in some cases, it makes sense to started a list with all items selected, and offer the user to deselect a few things in the viewport, by filtering them - and hereafter, remove the filter.

**Comment by olifolkerd** [comment]
Hey @exetico 

There is already a setting to automatically deselect table rows when they are filtered, you can set the `selectablePersistence` option to `false`
```js
var table = new Tabulator("#example-table", {
    selectable:true,
    selectablePersistence:false, // disable rolling selection
});
```
Checkout the [Row Selection Documentation](http://tabulator.info/docs/4.9/select#setup-persistent) for full details.

I hope that helps,

Cheers,

Oli :)
