### ISSUE TITLE
Center the loading message in the viewport, not the table body

### ISSUE THREAD

**Issue by vmsh0** [olifolkerd/tabulator#3314]
*Is your feature request related to a problem? Please describe.**
When I have a table with a big number of columns (and thus an horizontal scrollbar), the loading message is hidden, as it is centered in the table body.

**Describe the solution you'd like**
I would like to see the loading message centered on the /visible/ part of the table body.

**Describe alternatives you've considered**
Temporarily scrolling to the horizontal center of the table before triggering a data update.

**Comment by olifolkerd** [comment]
Hey @vmsh0 

That is how the table should be working anyway,  i would consider it a bug that the message is hidden when the table is scrolled.

I will add that to the list to fix for the next release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
merging with #2985 as they share the same goal
