### ISSUE TITLE
Links pointing to wrong page

### ISSUE THREAD

**Issue by t-schroeder** [olifolkerd/tabulator#3315]
**Website Page**
http://tabulator.info/docs/4.9/edit

**Describe the issue**
The links with text "CellComponent" point to the wrong URL:

http://tabulator.info/docs/4.9/edit#component-cell

The links with the text "Cell Component" or "Cell Components" point to the correct URL:

http://tabulator.info/docs/4.9/components#component-cell

**Comment by olifolkerd** [comment]
Hey @t-schroeder 

Thanks for getting in touch,

i have pushed a fix for this to the docs.

Cheers

Oli :)
