### ISSUE TITLE
Interactive histogram filter for numeric columns

### ISSUE THREAD

**Issue by slowkow** [olifolkerd/tabulator#3316]
Recently, Github announced [Flat Data](https://octo.github.com/projects/flat-data).

One part of the project is a Javascript table viewer: https://github.com/githubocto/flat-viewer

Some of the table features are pleasant to use.

I really like the interactive histogram that can be used to filter date ranges:

https://user-images.githubusercontent.com/209714/119148662-b7c52a00-ba1a-11eb-8191-c9e96449766d.mp4

After exploring the `flat-viewer` repo, it seems like it might be difficult to repurpose that table viewer for my own projects. Also, I'm not able to find the relevant lines of code to render the histogram.

In contrast, Tabulator is fantastically simple to use in any of my projects. (Thanks for the thoughtful design, Oli!) So, I plan to continue using Tabulator due to the ease of use.

Could I please ask if anyone might be interested to try adding a fancy histogram filter as a new feature for Tabulator? Or maybe to demonstrate a minimal example of one might apply hacky code on top of Tabulator to implement the histogram filter?

I might eventually try to hack something together someday if time allows, but I want to encourage anyone who might have time to do this right now. I think it'd be a wonderful addition to Tabulator.

**Comment by olifolkerd** [comment]
Hey @slowkow 

Thanks for your kind words, it is always great to hear that Tabulator is appreciated.

I wouldn't look to add this to the core project as it is a bit of a neiche formatter.

But the good news is it is really easy to add your own custom formatters to the table. you would simply need to find an existing historgram library and then use it to create a formatter using the [Custom Formatter Documentation](http://tabulator.info/docs/4.9/format#format-custom)

There is in fact alread an example of just this sort of formatter on the [Examples Page](http://tabulator.info/examples/4.9#sparklines), which uses the sparklines library.

I hope that helps,

Cheers

Oli :)
