### ISSUE TITLE
Tabulator Core + Movable Rows Module Not Adding Row Handle Icon Elements

### ISSUE THREAD

**Issue by Pinaz993** [olifolkerd/tabulator#3319]
When using the single-script version of Tabulator (v4.9.3), movable rows have handles with HTML elements designed to look like a handle. This is as expected. 
https://jsfiddle.net/Pinaz993/a1yj6pr9/3/

However, when using the core version of Tabulator and the Movable Rows module (along with the required Sort module and the tabulator_midnight.css theme), these 'icons' are omitted from the generated table.
https://jsfiddle.net/Pinaz993/rsc0Ln8d/2/
The table cells that are designated as handles still function, and you can still move the rows. However, without the icon, some users may find this difficult to intuit.

Desktop running Windows 10 2004, using Chrome Version 90.0.4430.212 (Official Build) (64-bit)

**Comment by Pinaz993** [comment]
In addition, with the midnight theme, handles in odd rows are the same color as the background of the cell. You can see that in the first JSFiddle. If you need me to make a separate issue, I'll be glad to do so.

**Comment by olifolkerd** [comment]
Hey @Pinaz993 

That is because you need the formatter module as well for these to appear.

Cheers

Oli :)
