### ISSUE TITLE
Select lookup formatter doesn't run when focused if the key is an integer

### ISSUE THREAD

**Issue by setr** [olifolkerd/tabulator#3321]
**Describe the bug**
When using the Select Editor, and providing a dictionary of `{ value: text }`, text is shown in the dropdown list, but not in the cell value itself.

To make the cell value also be shown as the text, I use the `formatter: "lookup", formatter: { value: text }` options on the column as well.

However, if the value is an **integer**, when you open the dropdown, the formatter does not apply, and you see the value again.
![image](https://user-images.githubusercontent.com/7907343/119550624-7e0f5e80-bd4d-11eb-9730-3c531a7d9c15.png)

If value is a **string**, the lookup formatter works consistently, and you cannot see the value anywhere.
![image](https://user-images.githubusercontent.com/7907343/119550735-9a130000-bd4d-11eb-93d6-6b09eb8347bd.png)

There should be no deviation between using an integer key versus a string key. The string-key behavior should be maintained. 

**Separately**, it is my belief that the standard browser `<select>` behavior should be followed: In all data scenarios, the text should always be displayed.
1. If you provide an array of elements, then value == text. 
2. If you provide a list of `{value: text}`, then the values are set respectively, but the text should always be displayed -- unless overridden by lookup formatter. 

That is, the lookup formatter option should not be required in the default case, following normal expectation.

**Alternatively**, documentation should be added to the select editor to heavily recommend usage of lookup formatter because this behavior violates intuition.

**Tabulator Info**
- Tabulator 4.9

**Working Example**
https://jsfiddle.net/muvo80t2/2/

Note that the only difference between the `gender` and `gender2` column definition and tabledata is the dictionary key.

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Click on any field in Gender2 column. The cell will render the `text` everywhere -- this is the expected behavior.
2. Click on any field in Gender column. The cell will render the `value` instead of the text, but the other fields and dropdown itself will continue to show the `text` value. 
3. This is the error

**Expected behavior**
The cell should be formatted by the formatter when selecting the dropdown, as it does in all other cases. It should not have different behavior when the value is an integer, instead of a string.

**Screenshots**
![image](https://user-images.githubusercontent.com/7907343/119550624-7e0f5e80-bd4d-11eb-9730-3c531a7d9c15.png)
![image](https://user-images.githubusercontent.com/7907343/119550735-9a130000-bd4d-11eb-93d6-6b09eb8347bd.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 88.0.1

**Comment by olifolkerd** [comment]
Hey @setr 

Thanks for the headsup, that definitely looks like a bug, 

I will add that to the fixit list.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
I have just pushed updates to the 5.2 branch that replaces the ***select*** and ***autocomplete*** editors with the new ***list*** editor, which will resolve this issue.

It will be included in the 5.2 release later this month.

Cheers

Oli :)
