### ISSUE TITLE
Tooltip does not work if cell has false value

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#3322]
**Describe the bug**
![image](https://user-images.githubusercontent.com/799021/119654975-b2f4e180-be31-11eb-880b-bc315de482f4.png)

**Tabulator Info**
- v4.9.3

**Working Example**
ignore issue until I add link to JS fidle

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Move mouse over a cell with empty value
Actual: no tooltip

**Expected behavior**
expect tooltip

**Desktop (please complete the following information):**
 - OS: LinuxMint v19.3
 - Browser FFv84

**Comment by olifolkerd** [comment]
Hey @KES777 

Thanks for the headsup,

I will stick this on the fixit list.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
This has been resolved in the 5.0 release which will be released later today.

Cheers

Oli :)
