### ISSUE TITLE
Cell dropdown does not get displayed for few bottom rows

### ISSUE THREAD

**Issue by SandeepBadawe** [olifolkerd/tabulator#3329]
Environment:
I am using Tabulator 4.4.3. I have a table with 4-6 columns. I use inline editing feature with editorParams option to edit the value of the cell using the drop down list.

My browser Chrome in my laptop is full screen, Tabulator occupies full space available inside browser. Tabulator has rows spanning multiple pages.

My Observation : 
When I try to open the dropdown for cells, which are in the last or second last row, it does not get displayed. But it get displayed for cells in rows 4th or 5th last from bottom row.
This could be because, for last or second last row, dropdown window does not get the sufficient space (height of dropdown) to show  as Tabulator window end after that row. But when cell in rows 4th or 5th last from bottom row is clicked it gets sufficient space to accommodate the dropdown height.

Proposed solution:
Right now the dropdown is displayed with it's top edge is matching to top edge of cell. This means entire height of dropdown in below cell top edge, which may go outside Tabulator window for few bottom rows.
In such cases the bottom edge of dropdown should be aligned with bottom edge of cell. This logic should dynamic and flexible to accommodate all possible conditions.

Current workaround used:
I have set  autoResize: false, to avoid this situation. But as a side effect, Table does not get resized when parent gets resized, at the same time when dropdown displayed, tables gets scrollbar.

**Comment by olifolkerd** [comment]
Hey @SandeepBadawe 

You are using a very old version of Tabulator, the issue has likely been fixed in newer versions. please use version 4.9 before reporting issues as we only apply fixes to the live versions.

Cheers

Oli :)
