### ISSUE TITLE
Bug when combining pagination with images (Vertical scrolling always appear)

### ISSUE THREAD

**Issue by Hamza-Ghizaoui** [olifolkerd/tabulator#3331]
**Describe the bug**
This bug is super easy to reproduce. 
Just use pagination in combination with images (large images) in some column and the height of the table will be determined as if there are no images (a vertical scroll bar will appear).

**Tabulator Info**
- 4.9

**Working Example**
Any table with large images in a column and pagination will reproduce this problem

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Create a tabulator with images formatted in some column (let every image 400x400 px for example)
2. move to any other page
3. The table size will be the size of the rows without the large images, and then a scroll bar will appear

**Expected behavior**
I want the table to take the size that it needs (I did not set a height)

**Screenshots**

![grafik](https://user-images.githubusercontent.com/46027405/120791515-9bee7780-c534-11eb-8c72-30db6cb43434.png)

**Desktop (please complete the following information):**
 - OS: Linux + Windows
 - Browser Chrome, Firefox
 - Version Various verisons

**Additional context**

**Comment by olifolkerd** [comment]
Hey @Hamza-Ghizaoui 

The issue you have here is that your images are loading asynchronously after the table has loaded and therefor the row height will have been calculated with the images with their preloaded height of `0px`.

To get around this you can set the `height` property on the image formatter, which will then ensure the table knows how big the rows are when it is rendering, and will therefore workout the page size corectly:

```js
{title:"Example", field:"example", formatter:"image", formatterParams:{
    height:"50px",
}}
```

For more information please checkout the [Image Formatter Documentation](http://tabulator.info/docs/4.9/format#format-builtin)

Cheers

Oli :)
