### ISSUE TITLE
When refreshing a table for the first time, it only loads half of the rows. In the next refresh it loads all of them. 

### ISSUE THREAD

**Issue by pmendis** [olifolkerd/tabulator#3332]
The issue is there only in version 4.9 and not working in both Chrome and Edge. However, this bug is not there when using Firefox.

**Comment by olifolkerd** [comment]
This depends heavily on how you have set up your table.

If you wish to report a bug you must fill in the Bug Template Issue, and provide a link to a JS fiddle that demonstrates the issue and your table configuration.

Cheers

Oli :)
