### ISSUE TITLE
select header filters fire filter change two times

### ISSUE THREAD

**Issue by wergio** [olifolkerd/tabulator#3334]
**Describe the bug**
I noticed a strange behavior of select header filters: when the select box is clicked, filter value is changed (BEFORE I select an option) to a value = to an array containing a single element with the option value of the currently selected element. When I finally click the option, filter value is changed another time to a value = to the option value newly selected.

Example:
currently selected option value "aaa"
First click that opens the select:
filter value = [ "aaa" ]
Second click always on "aaa" element:
filter value = "aaa"

**Tabulator Info**
Tabulator 4.9.3

**Working Example**
https://codepen.io/Wergio/pen/OJpOeKB

See also the stranger behavior of the "all" option with empty string value and headerFilterFunc:"=" (list goes blank on the first click)

**To Reproduce**
A step by step guide to recreate the issue
1. Open console
2. click an header filter
3. See filter returned on console

**Expected behavior**
The first click should not fire any filter change I think. And also passing an array containing the element value isn't correct. 
Second click behavior is ok.

**Desktop (please complete the following information):**
 - OS: Window 10 64bit
 - Browser Firefox 
 - Version 89

**Additional context**
The same "double filter change" behavior is present also with ajax mode, slowing down things with double calls

**Comment by olifolkerd** [comment]
Hey @wergio 

Thanks for letting me know, that does sound a bit unusual.

I will have a look into that for a future release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
I have just pushed updates to the 5.2 branch that replaces the ***select*** and ***autocomplete*** editors with the new ***list*** editor, which will resolve this issue.

It will be included in the 5.2 release later this month.

Cheers

Oli :)
