### ISSUE TITLE
Better visual expand/collapse support with Tabulator trees

### ISSUE THREAD

**Issue by mike-lischke** [olifolkerd/tabulator#3335]
*Is your feature request related to a problem? Please describe.**
A common pattern in tree controls, both in web as well as desktop applications is the support of animated expand/collapse toggles.  For example: one may have a right pointing triangle for collapsed rows and a down pointing triangle for expanded rows. A pretty popuplar effect when toggling the expand state is to rotate the triangle by 90° in an animated fashion.

Currently Tabulator allows to set 2 different (!) HTML elements (or strings from which they are created internally) for expanded and collapsed rows. However, CSS animations can only be performed on the same element (with changing properties, like the rotation). Additionally, when the expand state of a row is changed, the entire row is re-rendered by Tabulator, replacing all elements, including the expand toggle.

**Describe the solution you'd like**
A possible solution is pretty simple, and requires 3 things:
- Set a new CSS class on the row, which indicates if that row is expanded or not. This is required to allow specifying a specific expand CSS selector for the tree toggle element:
```html
<div class="tabulator-row tabulator-selectable tabulator-row-odd tabulator-tree-level-0 tabulator-selected expanded" role="row" style="padding-left: 0px;">...</div>
```

CSS:
```css
.tabulator .tabulator-row.expanded .treeToggle {
    transform: rotate(90deg);
}
```

- Don't re-render the row div on expand/collapse. Only change its CSS class list. There's no sense in re-rendering that element, as it doesn't change. On expand new rows are added as siblings, not as children, so not even the row's child list changes.

- Use only a single tree toggle element, instead of two. The visual appearance can be adjusted depending on the `expanded` row CSS class. I'm aware that this would break compatibility with existing applications which use 2 elements for that, so a possible solution could be to use only one element for both expanded and collapsed state if only one (or none at all) is specified.

**Describe alternatives you've considered**
I started with 2 manually created HTML elements for the tree toggles, until I realized that CSS animation cannot be used between different elements. Then I tried to use the same element for both fields:

```typescript
            dataTreeExpandElement: expandToggle,
            dataTreeCollapseElement: expandToggle,
```

However, that doesn't work either, for 2 reasons: there's no indication currently if a row is expanded or not (hence the request for adding an extra CSS class) and the row is re-rendered on expand or collapse, which will stop any ongoing CSS animation.

**Comment by olifolkerd** [comment]
Hey @mike-lischke 

Tabulator has to redraw the row when it is clicked, just because in your case you don't do anything when a row is expanded does not mean that others do not. 

I know of many cases where people use row formatters linked to group opening events, in these cases the row must be redrawn in-order for the row formatter to completely render.

In this case i feel that we would be loosing a lot of built in functionality, simply to add a little bit of animation to the DOM, which i don't feel is a good trade off.

You are of course free to implement this your self in your own version if you would like an animation, but as it currently stands Tabulator does not offer any built in animation in the table, that is down to developers to manage themselves.

Cheers

Oli :)

**Comment by mike-lischke** [comment]
Thanks for you answer Oli. While it makes of course sense what you wrote, I'd like to note that Tabulator often recreates elements where it wouldn't strictly be necessary. Tabulator should optimize the general use (which is likely the more common case) than special use. it could certainly benefit with faster rendering.

I'm writing that as someone who has worked on treeview controls for more than 20 years and even created a very popular Delphi (Pascal) tree control. But anyway, Tabulator is a great piece of software and I'm happy to use it. Thanks for your hard work!

**Comment by olifolkerd** [comment]
Thanks for your feedback.

And that point I would like to mention that Tabulator isn't a tree control library, it is primarily a table layout library that happens to have tree layouts as one of Its 100's of features.

Tabulator has never claimed to be the most performant of libraries. Its goal is to be simple to use and offer a diverse range of features. Tabulator 5.0 has significantly reduced the footprint of the library as well as improved performance.

With 100s of features all interplaying with one another it would be a hurculean task to make sure they all played nicely with one another without triggering a clean redraw of the element. And while I totally agree it would be possible, it is simply overkill for the majority of Tabulators users, and with limited time resources to spend on the project I simple prioritise new features that befit the most users.

That being said, as I mentioned before I am always open to pull requests from users if they wish to see a new feature added that I do not have time to implement.

Many thanks

Oli
