### ISSUE TITLE
Strange code is found: null has no properties

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#3336]
Next code tries to access properties at `null` value

![image](https://user-images.githubusercontent.com/799021/121883768-d1584980-cd1a-11eb-92a6-4d771e6ece29.png)

probably `_typeof( null )` should not return `object`

**Comment by olifolkerd** [comment]
This would depend on the  you table configuration. if you want to report this as a bug, please follow the bug template and provide a working JSFiddle that demonstrates the issue you are facing and the config you are using.

Cheers

Oli :)
