### ISSUE TITLE
`autocomplete` editor is disappeared when its size is changed

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#3337]
**Describe the bug**
When I search through `autocomplete` editor it have different data: it maybe wide or narrow.
When  `autocomplete` is situated at right-bottom corner of window. Wide/narrow data may cause browser to show/hide horizontal scrollbar which case main table to resize/redraw. This event wipes opened editor

**Tabulator Info**
- v4.9.3

**Working Example**
see attached video

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. create autocomplete editor at right bottom
2. open it
3. enter some text so data is filtered
4. if resizing of `autocomplete` editor triggers horizontal scroll bar then editor is closed

**Expected behavior**
autocomplete editor should not be closed

**Screenshots**
https://user-images.githubusercontent.com/799021/122529195-dfadaa80-d025-11eb-90e1-26230b84c4ba.mp4

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.3
 - Browser FFv87

**Comment by KES777** [comment]
at this video you can see that if `autocomplete` is situated to the left and up, everything is fine.

but when position is moved to right-button, input lost focus and I can not write desired values

https://user-images.githubusercontent.com/799021/122530778-86467b00-d027-11eb-9b6c-77adb55b4cf6.mp4

**Comment by olifolkerd** [comment]
I have just pushed updates to the 5.2 branch that replaces the ***select*** and ***autocomplete*** editors with the new ***list*** editor, which will resolve this issue.

It will be included in the 5.2 release later this month.

Cheers

Oli :)
