### ISSUE TITLE
editor:"select" lead to a misconfusing behavior showing keys instead of descriptions

### ISSUE THREAD

**Issue by peironem** [olifolkerd/tabulator#3338]
### Describe the bug
Hello,
that's more a strange behavior rather than a bug in my opinion.
I think you guys already know about that, but i'm having troubles finding a clear topic on this.

When you define a select editor on a column, select element is going to show values rather than keys, wich is fine, but after user selection, table cell will show dict key instead of dict value

```javascript
var table = new Tabulator("#table", {
            data: [{item: 0, model: "model_name", lang: "English"}],
            pagination: "local",
            layout: "fitColumns",
            columns: [
                {title:"Item ID", field:"item", headerFilter:true},
                {title:"Model", field:"model", headerFilter:true},
                {title:"Language", field:"lang", headerFilter:true, editor:"select", editorParams:{
                    values: {
                        "it": "Italian",
                        "fr": "French",
                        "en": "English"
                    }
                }}
            ]
        })
```

If you click on any **Language** cell, you'll see a select box with 3 voices: **Italian, French, English**.
If you click on English option, table cell will be setted to **en** instead of **English**.
I mean, that's odd because on more complex tables (i have one wit alphanumerical ids), you get nonsense codes which doesn't lead to any real meaning.  

Let's say that my value dict is something like that
```javascript
values: {
    "MOD000SMA4DEF": "Din A4 standard shippping module",
    "MOD000SMA5DEF": "Din A5 compact shipping module",
    "MOD000EMA4DED": "Din A4 special module"
}
```

If any user is going to fill a table, he can never watch back to see what he already addedd and what he's missing: those codes mean nothing for him, they are just db ids. I red the docs point taht speaks about builtin select editor, but i'm not able to find a way to achive my goal: i don't want ids to be displayed to user, because that make no sense, only description have to be used here.

### Tabulator Info
Tabulator v4.9.3 (c)

### Working Example
n/A

### To Reproduce
HTML in body:
```html
<div id="table" class="abs w-100 h-100"></div>
```
JS:
```javascript
var table = new Tabulator("#table", {
            data: [{item: 0, model: "model_name", lang: "English"}],
            pagination: "local",
            layout: "fitColumns",
            columns: [
                {title:"Item ID", field:"item", headerFilter:true},
                {title:"Model", field:"model", headerFilter:true},
                {title:"Language", field:"lang", headerFilter:true, editor:"select", editorParams:{
                    values: {
                        "it": "Italian",
                        "fr": "French",
                        "en": "English"
                    }
                }}
            ]
        })
```
Just select any option to see table value displayed.

### Expected behavior
Table builtin select editor should show option descriptions instead of option keys.

### Desktop (please complete the following information):

    OS: Win10
    Browser: Firefox

**Comment by olifolkerd** [comment]
This is not a bug, you are just missing a step.

Because you are looking up values from a select list, you need to use a `lookup` formatter to then display the label instead of the value:

```js
var lookupValues = {
    "it": "Italian",
    "fr": "French",
    "en": "English"
};

//column definition
 {title:"Language", field:"lang", headerFilter:true, editor:"select", editorParams:{values:lookupValues}, formatter:"lookup", formatterParams:{values:lookupValues}}
```

Cheers

Oli :)

**Comment by peironem** [comment]
Many thanks, i'll try it today :)

**Comment by peironem** [comment]
May i suggest to add this hint in select editor definition?
@olifolkerd i red taht docs step before opening a TT, but i wasn't abe to find your hint (i can be wrog again, but i wasn't able to find it)
