### ISSUE TITLE
Separate calculations for groups and tables

### ISSUE THREAD

**Issue by IvanSavoskin** [olifolkerd/tabulator#3339]
Good day. I wanted to clarify if there are plans to add calculation separately for groups and for table? 
For example, there are situations where I would like to output calculation. in the group, but they are not needed in the table (shares). Or when I want to use different formatters in groups and tables

**Comment by olifolkerd** [comment]
Hey @IvanSavoskin 

Thanks for getting in touch,

There is no plan to add this functionality as i would feel it would be misleading to have two different type of calc value in the same column.

Cheers

Oli :)
