### ISSUE TITLE
Tabulator 3 beta tick and tickcross not recognising 1 as true

### ISSUE THREAD

**Issue by adrianjones1** [olifolkerd/tabulator#334]
Not sure if this is a bug or an error in my code. I have a field setup like this

{title:"CheckBox", field:"field12", sortable: true, sorter: "number", editor: "tick", align: "center", formatter: "tickCross", responsive: 1},

but its always showing a cross whether the number is 0 or 1. It may work ok with true or false but ideally I would like to use it with a numeric field storing 0 or 1.

**Comment by olifolkerd** [comment]
Hey,

The issue was that you were passing a string value of "1" instead of a numeric value of ***1***

Not to worry I have updated the formatter now to handle both strings and numeric 1's

Download the latest version of the repo and you should be sorted!

Cheers

Oli
