### ISSUE TITLE
Setting headerFilter in Grouped Column not working?!?

### ISSUE THREAD

**Issue by tbock75** [olifolkerd/tabulator#3341]
**Describe the bug**
I am using a grouped by language header and without an header filter in these grouped headers Everything works fine.

The error message in browser debug is: 
Ajax Load Error:  TypeError: cell.getData is not a function

See attachments.

**Tabulator Info**
- Which version of Tabulator are you using? tested with 4.8 and 4.9 the newest version

**Working Example**
None working example because I dont have an open and accessible Rest Api Server

https://jsfiddle.net/5cp0Lrku/8/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
When removing line 62, 69, 81 and 88 

**Expected behavior**
The table should be generated.

**Screenshots**

![working](https://user-images.githubusercontent.com/36043549/123093300-d2c8f680-d42b-11eb-98bf-84eecc46b11b.PNG)
![error](https://user-images.githubusercontent.com/36043549/123093303-d3618d00-d42b-11eb-8bb6-f2114e9c0352.PNG)

**Desktop (please complete the following information):**
Windows 10 on 
newest versions of
 - Firefox, Chrome and some other browsers

**Comment by olifolkerd** [comment]
Hey @tbock75 

Try explicitly setting which type of header filter you are using, rather than just setting them to true. and make sure they are on the column not the column group.

Cheers

Oli :)
