### ISSUE TITLE
Fast.Design stylesheet

### ISSUE THREAD

**Issue by MarcSkovMadsen** [olifolkerd/tabulator#3342]
I am a data scientist using [HoloViz Panel](https://github.com/holoviz/panel), templates based on Microsofts [Fast.Design](https://www.fast.design/) like [FastListTemplate](https://pyviz-dev.github.io/panel/reference/templates/FastListTemplate.html#templates-gallery-fastlisttemplate) and the [Panel Tabulator widget](https://pyviz-dev.github.io/panel/reference/widgets/Tabulator.html).

I would like the style of the Fast design templates and Tabulator to play nicely together. So I've created a stylesheet for using Tabulator with Fast design in any application.

You can find it here https://github.com/MarcSkovMadsen/awesome-panel-assets/tree/master/styles for now.

I would like to make it easier for Fast and Tabulator developers in general and Panel developers in particular to use this stylesheet.

One solution would be to get it added to the Tabulator list of stylesheets.

**Would you be interested?**

https://user-images.githubusercontent.com/42288570/123505675-b8c42980-d660-11eb-81c3-074abed667e6.mp4

## Additional Context

If you are interested you can find a Panel example with code here https://discourse.holoviz.org/t/tabulator-style-for-fast-templates/2478

I am also working on a PR to Panel for adding this stylesheet as one of the supported themes for the Panel Tabulator widget. See https://github.com/holoviz/panel/pull/2425.

**Comment by olifolkerd** [comment]
Hey @MarcSkovMadsen 

I would be happy to add a new theme to Tabulator, if you would like to see it included, please submit a PR against the 5.0 branch.

You could also add a  link to the [Tabulator Ideas](https://github.com/olifolkerd/tabulator-ideas) repo to help point other people at it.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @MarcSkovMadsen 

Just wondering if you are still interesting in submitting a PR for this (against the 5.1 branch now).

If not i will close of this issue to reduce clutter.

Cheers

Oli :)

**Comment by MarcSkovMadsen** [comment]
Hi @olifolkerd 

Thanks for asking. I would like to contribute a PR but have too many other things going on right now. 

Feel free to close this one.
