### ISSUE TITLE
Selection list in autocomplete and select editor renders HTML values

### ISSUE THREAD

**Issue by tmakowski** [olifolkerd/tabulator#3349]
**Describe the bug**
Currently if a value that is a valid HTML is rendered as HTML in a selection list. However, when we select the value the edited cell will have HTML text inserted, and it will be displayed as text. This goes for both, autocomplete and select editors. I would expect the value to be escaped and presented as a plain text in the selection list.

**Tabulator Info**
I have tested on v4.9.3. Additionally, I have tried the version present in dist folder on [current version of 5.0 branch](https://github.com/olifolkerd/tabulator/tree/7994a6f37c9150f5a384f55e7ee2cd167323db4d).

**Working Example**
https://jsfiddle.net/ef47jm6d/

**To Reproduce**
Click on an empty cell in _Autocomplete Editor_ or _Select Editor_ column.

**Expected behavior**
I expected the suggested values to appear in the same form as they are present in cells.

**Screenshots**
![Autocomplete Editor](https://user-images.githubusercontent.com/38053499/125435697-11173dae-a8fa-4bf4-8363-594a7dfc2b73.png)

![Select Editor](https://user-images.githubusercontent.com/38053499/125435649-071dde37-4450-4085-9b80-40cbafaa3d80.png)

**Desktop**
OS: Darwin 20.5.0 (Macbook M1)
Browsers (reproduced in all three):
 - Chrome - Version 91.0.4472.114 (Official Build) (arm64)
 - Firefox -  Version 89.0.2 (20210622155641)
 - Safari - Version 14.1.1 (16611.2.7.1.4)
 
___Thank you for this great library!___

**Comment by bornova** [comment]
Hi @tmakowski,
You can format your list items using the `listItemFormatter` property of the `editorParams` object as documented here: [http://tabulator.info/docs/4.9/edit#edit-builtin](http://tabulator.info/docs/4.9/edit#edit-builtin)

Here is an updated version of your example:
[https://jsfiddle.net/rtbykzj4/](https://jsfiddle.net/rtbykzj4/)
