### ISSUE TITLE
Change header input type from "text" to "search" to enable blink browsers filter clearing 

### ISSUE THREAD

**Issue by alainpannetier** [olifolkerd/tabulator#335]
Dear Oliver,

Just downloaded and started testing the new 3.0 beta update. Lots of changes.

One more thing I'd like to suggest is to change the header input elements from type "text" to "search".
In chromium based browsers this triggers an addictive behaviour: whenever the filter field is not empty a small cross appears on the right side (ltr) which clears the filter in one click.

Here are two examples. First my filter (look on the right side), then tabulator filters.

![screenshot from 2017-05-30 06 32 46](https://cloud.githubusercontent.com/assets/1625152/26566250/c782a9cc-4502-11e7-8ec2-8e29a4d91d4d.png)

![screenshot from 2017-05-30 06 33 11](https://cloud.githubusercontent.com/assets/1625152/26566238/b336a4f0-4502-11e7-9bbb-d8b1220bf696.png)

There is no effect on Gecko browsers (and I haven't tested IE/Spartan).

Thanks for considering.

**Comment by olifolkerd** [comment]
great idea! i will look at getting that in this evening!

**Comment by olifolkerd** [comment]
I have just committed this update :)
