### ISSUE TITLE
Add ability to collapse entire table

### ISSUE THREAD

**Issue by AndrewHutcheson** [olifolkerd/tabulator#3356]
It would be nice to be able to have a little arrow at the table header to collapse the entire thing. Similar to collapsing a group, but for the whole table. When I have multiple tables in a page this would make it useful to minimize them and get them out of the way.

**Comment by bornova** [comment]
Hi @AndrewHutcheson,
I can suggest a possible workaround. I do this by adding an empty column at the beginning and using the '[headerClick](http://tabulator.info/docs/4.9/callbacks#column)' callback to collapse the table. Here is an example:

https://jsfiddle.net/hzc6m438/

**Comment by olifolkerd** [comment]
Hey @AndrewHutcheson 

You could do this by calling `getRows` on the table and then itteratiing over the rows calling the `treeExpand` function

Cheers

Oli :)
