### ISSUE TITLE
[Feature] Get filetype in downloadReady callback

### ISSUE THREAD

**Issue by georg90** [olifolkerd/tabulator#3357]
*Is your feature request related to a problem? Please describe.**
I need to differentiate between CSV / Excel export. CSV should be downloaded right away (standard feature) and excel needs to be intercepted, sent to external server for processing and then returned to user (using downloadReady callback this is easy). However, the documentation didn't show any way to get the filetype requested within downloadReady callback. This would be very helpful feature to direct the return flow based on requested filetype.
Maybe this is also helping others.

**Describe the solution you'd like**
```javascript
var table = new Tabulator("#example-table", {
    downloadReady:function(fileContents, blob){
    //fileContents - the unencoded contents of the file
    //blob - the blob object for the download

    //custom action to send blob to server could be included here

    return blob; //must return a blob to proceed with the download, return false to abort download
    },
});
```

should extend to 
```javascript
var table = new Tabulator("#example-table", {
    downloadReady:function(filetype, fileContents, blob){
    //filetype - the file types requested (csv, excel, json, ...)
    //fileContents - the unencoded contents of the file
    //blob - the blob object for the download

    //custom action to send blob to server could be included here

    return blob; //must return a blob to proceed with the download, return false to abort download
    },
});
```
**Describe alternatives you've considered**
Currently I am using a global variable set previously to direct the flow to return the blob or not in downloadReady
```javascript
var table = new Tabulator("#example-table", {
    downloadReady:function(fileContents, blob){
    //fileContents - the unencoded contents of the file
    //blob - the blob object for the download

    //custom action to send blob to server could be included here
    if (globals.filetype == 'csv'): {
        return blob
    }
    else: {
        // do more
        return false
    }
});

**Comment by bornova** [comment]
Hi @georg90,
The `blob` object has a `type` property which returns the file type you may be looking for.  The [csv download](http://tabulator.info/docs/4.9/download#csv) will return `text/csv` so you can do something like this:
```javascript
var table = new Tabulator("#example-table", {
    downloadReady: function(fileContents, blob) {
        if (blob.type == 'text/csv') {
            return blob; //download csv file
        } else {
            // Do more
        }
    }
});
```

**Comment by georg90** [comment]
Yep, that’s a nice way to do it, iam not using the blob therefore I didn’t bother looking at it more closely. 
Thank you!
