### ISSUE TITLE
Beta: Formatters no longer have data object?

### ISSUE THREAD

**Issue by lac616** [olifolkerd/tabulator#336]
Hi Oli,

I'm evaluating the Beta version and one of the biggest changes appears to be that the formatter function parameters changed from:

function (value, data, cell, row, options) {}

to

function (cell, formatterParams)

When I create custom links I use values from other cells, not necessarily the same cell, which is why the data object was perfect as a function param. Is there is another way to access row data? It appears this problem occurs with creating custom editors as well.

Thanks!

**Comment by olifolkerd** [comment]
Hey,

You can use the cell component to access all of the features you had before.
```js
//get cell value
cell.getValue();

//get element
cell.getElement();

//get row component
cell.getRow();

//get row data
cell.getRow().getData();

//get row element
cell.getRow().getElement();

//get all cell components in row
cell.getRow().getCells()
```

Full documentation of the components can be found [here](http://olifolkerd.github.io/tabulator/docs/3.0/#components)

Let me know if that helps.

Cheers

Oli

**Comment by lac616** [comment]
Excellent, thank you!! Works like a charm!
