### ISSUE TITLE
maxHeight cause dragging scrollbar doesn't work in Chrome & Safari

### ISSUE THREAD

**Issue by RonzyC** [olifolkerd/tabulator#3362]
**Describe the bug**
When the maxHeight properties is set, dragging the scrollbar is not working properly in Chrome and Safari
In Firefox the scrollbar works fine, not sure in other browser
The issue is not apparent in smaller number of rows, but when it's higher, I think it will gradually get more and more unusable
In my end:

- 100 rows is still smooth
- 500 rows is a problem if dragged too fast
- 2000 rows still works if careful enough
- 10000 rows doesn't work (just move a little on each drag)

Note: "height" is fine

**Tabulator Info**
- Which version of Tabulator are you using?
4.9.3

**Working Example**
https://jsfiddle.net/RonaldoC/o8drhenc/
https://codepen.io/RonaldoC/pen/ZEKMqpQ
Note: When using JSFiddle, in Firefox the scrollbar doesn't work at all, even when not using maxHeight (probably it's JSFiddle side)
because I tried it in Codepen and it works fine there, so I give both fiddle

**To Reproduce**
1. First of all, you may want to tweak the row count, change it in the loop limit
2. Try to drag the scrollbar

**Expected behavior**
The scroll is smooth at any number of rows when using maxHeight

**Desktop (please complete the following information):**
 - OS: Windows, iOS
 - Browser: Chrome (92), Safari (14)

**Comment by olifolkerd** [comment]
Hey @RonzyC

This has been resolved in the 5.x releases.

Cheers

Oli :)
