### ISSUE TITLE
scrollToRow does not get resolved in case of ifVisible is set to false and rows already visible

### ISSUE THREAD

**Issue by danielHin** [olifolkerd/tabulator#3363]
Hey everyone!

**Describe the bug**
The promise returned by scroll to row doesn't get resolved or rejected in case the row is already visible and the ifVisible parameter is set to false. 

I could reproduce this issue using tabulator@4.9.3 and @5.0.0-alpha.0

**Tabulator Info**
4.9.3

**Working Example**
Example with 4.9.3
https://jsfiddle.net/9m80z7kp/51/

Line which I would expect resolve() should be called
https://github.com/olifolkerd/tabulator/blob/4.9/src/js/row_manager.js#L245

Example with 5.0.0-alpha.0
https://jsfiddle.net/c6h9jano/2/

Line which I would expect resolve() should be called
https://github.com/olifolkerd/tabulator/blob/5.0/src/js/core/rendering/Renderer.js#L151

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
The fiddle I've created basically scrolls to a row and selects the row. In case the scrollToRow isn't resolved, no row will get selected after clicking on the Button. In addition it will log to the console in case the promise is resolved or rejected

1. Click on 'Scroll to last Row'
1.1 --> Tabulator scrolls to last row and select the row
2. Click on 'Scroll to second Row'
2.1. --> Tabulator scrolls to second row (will get the top row) and selects the row
3. Scroll up until the first row is visible and no further scrolling is possible
4. Click on 'Scroll to second Row'
---> Tabulator won't scroll because the row is already visible, which is correct. But the Row won't get selected again and also no console output is created because the Promise isn't resolved

**Expected behavior**
Promise gets resolved once the row tabulator scrolls to is visible. Even it already was visible

**Comment by rob5n** [comment]
I am having this exact same issue with version 4.9.3 .  Like @danielHin says, `return false` is being called when `resolve()` should be.

**Comment by olifolkerd** [comment]
Hey @danielHin 

I have pushed a fix for this to the master branch and will include it in the next patch release.

Cheers

Oli :)
