### ISSUE TITLE
Enhance groupBy to support a list of fields; Then group rows per list

### ISSUE THREAD

**Issue by styson2222** [olifolkerd/tabulator#3371]
*Is your feature request related to a problem? Please describe.**
There is no problem. This is an enhancement request.

**Describe the solution you'd like**
Allow the "groupBy" attribute to accept a list of fields, then group the rows per that list.
First level grouping per list[0], second level grouping per list[1], etc

**Describe alternatives you've considered**
I have considered using the dataTree, but having an extensible groupBy is preferred.
Our current application is using the groupBy styling, and I would like to maintain that style.

**Additional context**
I think this is a generically useful option that others would find interesting.
(I guess everyone says this. haha)

Thanks for your consideration.

**Comment by bornova** [comment]
Hi @styson2222,
Looks like what you are asking for is already available: [Multi Level Grouping](http://tabulator.info/docs/4.9/group#setup-toggle)
Sorry if I am misunderstanding your request.

**Comment by styson2222** [comment]
Hi Oli,

Thanks for the quick reply.
I included a picture at the end to help clarify the request.

On the left, is groupBy with a list of fields. (ex, [ field0, field1 ] )
The field0 has a single value of “DCHIP”.
The field1 has values of “timing_0”, “power_0”, and “baseline_0”.
As you can see, the current Tabulator shows a single gray-row for each combination, labeled as “field0,field1”.

On the right is what I am requesting.
Specifically, a “parent” gray-row for each field0, with a “child” gray-row for field1.

This would come in handy for report where the field0 has multiple values.
(which is exactly what our users are requesting)

Does the request make sense now?

Thanks,
Scott

***@***.***

**Comment by LilDevil** [comment]
@styson2222 whatever picture you intended to attach didn't get attached. And please post directly, when you use email a whole bunch of gobblygook gets included.

**Comment by styson2222** [comment]
Hi Oli,

Thanks for the quick reply.

I attached a PDF to help clarify the request.

On the left, is groupBy with a list of fields. (ex, [ field0, field1 ] )

- **field0 has a single value** of “DCHIP”
- field1 has values of “timing_0”, “power_0”, and “baseline_0”

As you can see, the current Tabulator shows a single gray-row for each combination, labeled as “field0,field1”.

On the right is what I am requesting. Specifically, a “parent” gray-row for each field0, with a “child” gray-row for field1.

This would come in handy for report where the **field0 has multiple values**.
(which is exactly what our users are requesting)

Does the request make sense now?

Thanks,
Scott

[groupBy.pdf](https://github.com/olifolkerd/tabulator/files/6983490/groupBy.pdf)

**Comment by bornova** [comment]
@styson2222
I think `groupBy` and `groupHeader` options can already do what you want, you just need to prep your data accordingly. Here is an example:  https://jsfiddle.net/28sj3avo/

**Comment by styson2222** [comment]
Most excellent!
The jsfiddle you sent shows exactly what I requested.
I was not aware that groupHeader could additionally modify the behavior of groupBy.
Thank you very much.
