### ISSUE TITLE
Post-validation tooltips

### ISSUE THREAD

**Issue by IvanSavoskin** [olifolkerd/tabulator#3373]
How can you display some kind of hint after a cell validation error? Now the user does not understand why its value is not valid

**Comment by bornova** [comment]
Hi @IvanSavoskin,
You can use the `validationFailed` callback to add a tooltip or other forms of hints to failed cell: https://jsfiddle.net/rx1gLcj9/

http://tabulator.info/docs/4.9/callbacks#validation

**Comment by IvanSavoskin** [comment]
@bornova Thanks for your answer
