### ISSUE TITLE
Movable row callback on pick up

### ISSUE THREAD

**Issue by jjsiman** [olifolkerd/tabulator#3378]
*Is your feature request related to a problem? Please describe.**
With a combination of background tasks and user-editable rows, we have a Tabulator instance running on a page with an autosave timer. The rows are also movable, and we've run into an issue where the autosave trigger runs while the user has grabbed and is actively moving a row, causing a discrepancy with how the row order is stored on the backend and in Tabulator.

**Describe the solution you'd like**
Add a callback for when a row is picked up, not just dropped (`rowMoved`). That way we can temporarily disable the autosave timeout and resume when the row has been placed.

**Describe alternatives you've considered**
I've tried custom event handlers on the row handle, however they are blocked/have lower priority than Tabulator's movable row handlers and will not run on `mousedown`.

**Comment by olifolkerd** [comment]
Hey @jjsiman 

I have just pushed an update to the 5.1 branch with this functionality, which will be included in the next release.

it adds the `rowMoving` and `rowMoveCancelled` event.

Cheers

Oli :)
