### ISSUE TITLE
fitDataTable layout messing up with a "tall" table

### ISSUE THREAD

**Issue by reverseflow** [olifolkerd/tabulator#3379]
**Describe the bug**
I have a table set up with fitDataTable layout and layoutColumnsOnNewData set to true, but in some cases one column is cutting text. It seems related to table height? If the column with the longer value is towards the bottom of a tall table it might cause issues.

**Tabulator Info**
- Which version of Tabulator are you using? 4.9.3

**Working Example**
https://jsfiddle.net/a3rcfto1/4/
Note: setData is on a timeout to simulate how my website works. The tables start out without data, then I'm running a few web service requests to pull the data, and then I update the tables using setData.

**To Reproduce**
1. Open JFiddle. On both Firefox and Chrome, the last cell is bugged out: [screenshot](https://i.ibb.co/dB5hXxK/immagine.png)
3. Move the last data object (the one with the longer status) to the top of the array, and run fiddle again. The table now displays correctly across all browsers

**Expected behavior**
The column should always adapt to the data.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Latest versions of Firefox and Chrome

**Comment by bornova** [comment]
Hi @reverseflow
Looks like the issue may be related to Virtual DOM Rendering.  As a workaround, you can disable the virtual DOM (`virtualDom: false`) or set the virtualDomBuffer to a high number bigger than the visible table height. `virtualDomBuffer: 2000` for example.

**Comment by olifolkerd** [comment]
This works correctly for me in version 5.x

On a side not you do need to use ` getElementByID1 for setting up the table, Tabulator will do that for you, just use the CSS selector for the element instead:
```js
const table = new Tabulator(document.getElementById("table"), {
```
can be shortened to:
```js
const table = new Tabulator("#table", {
```

Cheers

Oli :)
