### ISSUE TITLE
Css formatting

### ISSUE THREAD

**Issue by stack-its** [olifolkerd/tabulator#338]
Hi Oli,

For developers, I would strongly suggest that you use the attached formatted css for Tabulator.  What you have currently is a visual mess & very hard to find things in.  I've kept everything as you have it, but just cleaned it up, so it's easy to read & understand.  This is the new css from the 5/29 beta release.

Thanks,  Bill
[Tabulator_proposed_css.txt](https://github.com/olifolkerd/tabulator/files/1039841/Tabulator_proposed_css.txt)

**Comment by olifolkerd** [comment]
Hi Bill,

All the CSS is auto generated from SASS files using Gulp. if you look at the 3.0 branch you will find them in the /src/scss directory, you will find them all neatly organised using nested classes's arranged by type.

Cheers

Oli

**Comment by olifolkerd** [comment]
i have tweaked the output settings of the gulp-scss module to generate a more readable css file :)
