### ISSUE TITLE
Beta Version: $(selector).tabulator('getRowData') is missing

### ISSUE THREAD

**Issue by lac616** [olifolkerd/tabulator#339]
Hi Oli,

The 3.0 documentation is as follows:
![image](https://cloud.githubusercontent.com/assets/27359692/26636622/5f4288fc-45eb-11e7-85b1-503a3692a507.png)

It appears that function 'getData' still works, but function 'getRowData' throws an error as missing:
![image](https://cloud.githubusercontent.com/assets/27359692/26636743/aceadee2-45eb-11e7-9a0d-6c7099f4b730.png)

I use getRowData by the index of the row when I need specific data for use in event listeners (either related to the table itself or outside of it). I can work around it by using getData and finding the Id in the collection.

Just thought I would let you know so you can either update your documentation, or put the function back in for final release!

Thanks.

**Comment by lac616** [comment]
Actually there is a better workaround -

var row = oTbl.tabulator('getRow', comcode);
var data = row.getData();

Is this the preferred way of getting the row component and it's data when the event listener is outside the table? 

Thanks!

**Comment by olifolkerd** [comment]
Hey,

The ***row.getData();***  function is the correct way to get data outside of a callback, I will remove the ***getRowData*** function from the documentation.

Thanks

Oli
