### ISSUE TITLE
Table Scrollbar Visibility

### ISSUE THREAD

**Issue by 500Foods** [olifolkerd/tabulator#3392]
**Is your feature request related to a problem? Please describe.**
When a table fills a large vertical space but the number of rows in the table do not fill up the space, the vertical scrollbar is hidden.  This introduces a slightly different appearance for the table and is inconsistent.  Would be better if the vertical scrollbar could be made visible in the same style as when the table has many records, but just disabled because there is no scrolling required.  I imagine the same could be done for the horizontal scrollbar.

**Describe the solution you'd like**
A layout option for vertical and horizontal scrollbar visibility.  ie: 
scrollbar-horiz: "auto", "scroll", "hidden"
scrollbar-vert: "auto", "scroll", "hidden"

**Describe alternatives you've considered**
Adjusting the CSS overflow-x and overflow-y to values of "scroll" instead of auto doesn't quite work the same.  While it is possible to add scrollbars in this way, it only adds to the parts of the table where the CSS is overridden. For example, to the area where the rows are, not extended through the header and footer like the normal layout does.

**Additional context**
Hopefully this is pretty straightforward and no additional context will be necessary.

**Comment by olifolkerd** [comment]
Hey @500Foods 

Thanks for getting in touch,

I can see your point, but personally i am not a big fan of disabled scrollbars where they are not needed. For that reason i would not be looking to add this to the library, but as you state this can be achieved with with a bit of custom CSS your end if you want to.

You could set a min height on the tableholder to ensure that it always takes up the full height of the table even when empty.

Cheers

Oli :)
