### ISSUE TITLE
Apply Header Filters Only To Visible/Filtered Rows

### ISSUE THREAD

**Issue by atebeta** [olifolkerd/tabulator#3393]
I'm using multiple header filters on my table and it would appear that each subsequent header filter that is applied attempts to filter all the rows in the table, even those that have already been filtered out.

Would it be possible to only apply the filters to rows that are visible or haven't been filtered out?

I attempted to use the header filter function parameters to access the row component in order to try to check if it had a dom element, but I'm only able to access the row data.

I feel like this would speed up the filtering of data when using multiple filters and more complex filtering functions with large sets of data.

**Comment by olifolkerd** [comment]
Hey @atebeta 

This is intended behaviour

When a filter is changed, all data is re-filtered against the whole filter list, because changing a filter can mean that data that was previously filtered is now valid.

Cheers

Oli :)
