### ISSUE TITLE
Column formatter definition from JSON

### ISSUE THREAD

**Issue by bobsort** [olifolkerd/tabulator#3394]
I'm trying to replace an existing grid with tabulator a I encountered a few tiny issues.

1- Column definition is coming from server side and is in JSON format. some columns have custom formatter. Obviously I cannot include javascript function as formatter in json, but I can include its name, as following:

**Javascript**

```Javascript
function key_formatter(){
    ....
}

var t = new Tabulator(containerId,{ columns: FROM_JSON_BELOW });
```

**JSON**
```JSON
[
    {"field":"key", "title":"Key", "formatter":"key_formatter"}
    ...
]
```
It would be nice if I could assign formatter like above.

2- Some of my columns have clickable icons, which in my current grid component, I handle all those clicks with one single event attached to table component. however with Tabulator it seems when I use for example rowClick, event is attached to every row which makes the page slow for large tables.

3- I noticed when Tabulator attaches a lot of events to elements in the table. This increases CPU load and memory use of the table. I have 10% CPU use on firefox at all time when tabulator is on any of pages, even a tab that is not in foreground and as soon as it is closed, CPU load drops to 0%.
Would be nice if instead only one or two event handler attached to whole table which then will handles all the events based on element that is double clicked or clicked or dragged.

**Comment by olifolkerd** [comment]
Hey @bobsort 

This is already possible by extending modules,

Checkout the [Extending Modules](http://tabulator.info/docs/4.9/modules#extend) docs for more info.

Cheers

Oli :)

**Comment by bobsort** [comment]
How do I access row data from formatter? 

For example I have a grid with 10 columns, but row data has 18 attributes which I want to show the remaining data in visible columns as tooltip or icon

**Comment by bobsort** [comment]
I found it,

I need to use `cellvalue.getRow().getData()` to access row data
