### ISSUE TITLE
Allow menus to open upwards when there is not enough space to accommodate the menu

### ISSUE THREAD

**Issue by antman3351** [olifolkerd/tabulator#3395]
Hello, I have an issue with the header menu when there's too many elements.

**Describe the bug**
When the header menu is longer than the available space the menu opens upwards (depending where the top of the table is on the page) hiding most of the menu items.

**Tabulator Info**
4.9.3

**Working Example**
https://jsfiddle.net/08oLhmr6/44/

**To Reproduce**
1. Go to https://jsfiddle.net/08oLhmr6/43/
2. Click on last column
3. Change number of columns in row 7 to see the difference (see gif below)

**Expected behavior**
Menu to open downwards and scroll (menu or page, not too important). Maybe it can be an optional parameter to force the direction of the menu?

**Screenshots**
![Tabulator menu header](https://user-images.githubusercontent.com/16060462/136784631-0df7beb0-23cb-4fa7-ad1a-6a0d25068d72.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 
 - Version 94.0.4606.81 (Official Build) (64-bit)

Thanks, 
Antonio

**Comment by antman3351** [comment]
Having a bit of a monolog here 🙈
The css fix only works when the table is at the top of the page. 

If say you have two tables, unsetting `bottom` will make the menu stick to the top of the viewport although the table may be way lower down the page 🤦‍♂️

I have a hacky fix that maybe could be incorporated into Tabulator. 
In the `headerMenu` function at the end I added this: 
```JS
headerMenu: function ()
{
    const menu = [
        // build the menu ....
    ];

    setTimeout( () =>
    {
        document.querySelectorAll( 'div.tabulator-menu' ).forEach( ( node ) =>
        {
            const top = node.getBoundingClientRect().top;
            if ( top < 0 ) // Only align the menu with the top of the viewport when the menu is too long
            {
                node.style.top = 0;
                node.style.bottom = null;
            }
        } );
    }, 0 );

    return menu;
}
```

**Comment by olifolkerd** [comment]
Hey @antman3351 

The issue here is that the menu is appended to the body so in that situation it still technically fits.

I have just pushed an update to the 5.1 branch that adds the `menuContainer` option, to specify which element the menu should be appended too, which should resolve this issue as the preventing overflow of a container is already built in.

This will be included in the next release.

Cheers

Oli :)

**Comment by AndrewHutcheson** [comment]
Hi @olifolkerd thanks for the update. I think I have the same situation?

I noticed when the browser window becomes too small, the menu opens up off screen. Here is a screenshot of my rather tall menu working correctly, and then a screenshot when I shrink the browser (or use a lower resolution) where the menu renders way off the screen.

![Screenshot from 2022-01-17 10-40-41](https://user-images.githubusercontent.com/24422717/149809127-bb1fd46a-952c-4a5b-abc0-8dee0ae0e501.png)
![Screenshot from 2022-01-17 10-43-18](https://user-images.githubusercontent.com/24422717/149809128-fbccdf0d-6f81-42b0-9db3-369f6406448b.png)
