### ISSUE TITLE
Add/Sort Columns

### ISSUE THREAD

**Issue by marcodeluca** [olifolkerd/tabulator#34]
How difficult would it be to extend this to add/sort columns?

**Comment by olifolkerd** [comment]
You can already add and sort columns, using the ***getColumns*** and ***setColumns*** functions.
see the [documentation for more details](http://olifolkerd.github.io/tabulator/docs/#movable) 

You just need to get the current column definition array using the ***getColumns*** function, perform any additions or manipulations to the array, then pass it to the ***setColumns*** function:
```js
var columns = $('#example-table').tabulator('getColumns');

//manipulate columns definition array

$('#example-table').tabulator('setColumns', columns');
```

**Comment by marcodeluca** [comment]
Ah okay. Your description stated add/sort rows but not columns. Will read through docs, thanks:)

**Comment by olifolkerd** [comment]
There is no explicit ***addColumn*** or ***sortColumns*** functions, it is all handled through ***setCoumns*** to give users greater flexibility on how they handle that side of things. I will have a think about adding these functions in the next release.

**Comment by marcodeluca** [comment]
Actually, @olifolkerd do you do any paid customization? I'm looking for a specific set of functions that allows people to add different types of columns, I could show you a demo. What you have is closer than other plugins I've seen, I'd be happy to pay for the extra features if you wanted to roll it in or fork a different branch.

**Comment by olifolkerd** [comment]
Send me some info on what you are after (demo would be helpful) to oliver.folkerd@gmail.com and i can tell you if it is already on the development roadmap.

Cheers

Oli

**Comment by olifolkerd** [comment]
The latest release of Tabulator now includes the ***addColumn*** and ***deleteColumn*** functions to allow for even easier column manipulation.

Full documentation on these features can be found [here](http://olifolkerd.github.io/tabulator/docs/#movable).
