### ISSUE TITLE
Tooltips documentation page shows old constructor option

### ISSUE THREAD

**Issue by Sotiris-k** [olifolkerd/tabulator#3404]
Hello,

**http://tabulator.info/docs/5.0/format#tooltips**

**The tooltips constructor option is invalid in 5.0**

**Comment by AadBr** [comment]
Hi Oli,
As far as I can see it's not corrected. Your code:
`var table = new Tabulator("#example-table", {
    columnDefaults:{
        tooltips:function(cell){
            //cell - cell component

            //function should return a string for the tooltip of false to hide the tooltip
            return  cell.getColumn().getField() + " - " + cell.getValue(); //return cells "field - value";
        },
    }
});`
'tooltips' should be 'tooltip'. cell.getColumn() & cell.getValue() are not accessible when the tooltip is generated.
![tooltip_error](https://user-images.githubusercontent.com/2004332/140653720-3e016096-cffa-454a-aeb2-1d47d30d3ef0.PNG)
Thanks,

Aad
