### ISSUE TITLE
footerElement broken in v5.0

### ISSUE THREAD

**Issue by mcaskill** [olifolkerd/tabulator#3406]
**Describe the bug**

The `footerElement` option does not work because `FooterManager` prepares the footer element before `Tabulator` resolves its options.

<details><summary>Excerpts</summary>

```js
	initialzeCoreSystems(options){
		// ...
		this.footerManager = new FooterManager(this);
		// ...

		this.options = this.optionsList.generate(Tabulator.defaultOptions, options)

		// ...
		this.footerManager.initialize();
```

```js
export default class FooterManager extends CoreFeature{

	constructor(table){
		super(table);

		this.active = false;
		this.element = this.createElement(); //containing element
		this.external = false;
		this.links = [];

		this.initializeElement();
	}

	initialize(){

	}

	createElement (){
		// ...
	}

	initializeElement(element){
		if(this.table.options.footerElement){

			switch(typeof this.table.options.footerElement){
				// ...
```

</details>

In v4.9, the options are resolved and assigned to `Tabulator` before creating the `FooterManager`.

**Tabulator Info**
- v5.0.1

**Working Example**

Does not work in v5.0.1: https://jsfiddle.net/mcaskill/z2cm0xk6/1/

Does work in v4.9.3: https://jsfiddle.net/mcaskill/uq23oLz1/2/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://jsfiddle.net/mcaskill/z2cm0xk6/1/
2. Look at JS window for `footerElement: "<button>Custom Button</button>"` in Tabulator setup options
3. Run fiddle and see that "Custom Button" does not appear; an empty `.tabulator-footer` element is rendered instead (as opposed to no element?).

**Expected behavior**

The `footerElement`, be it a CSS selector, a DOM node, or HTML, should appear within the table.

**Screenshots**

![image](https://user-images.githubusercontent.com/29353/137807030-c2f1f7f2-42e7-4c94-b94b-720c5d251639.png)

**Desktop (please complete the following information):**

 - OS: N/A
 - Browser Any browser
 - Version N/A

**Smartphone (please complete the following information):**

 - Device: N/A
 - OS: N/A
 - Browser Any browser
 - Version N/A

**Additional context**

To resolve the issue, `FooterManager` should call `initializeElement()` in `initialize()` instead of the constructor.

**Comment by olifolkerd** [comment]
Hey @mcaskill 

I have pushed a fix for this to the master branch and will include it in todays patch release shortly.

Cheers

Oli :)
