### ISSUE TITLE
"setData failed"in v5.0

### ISSUE THREAD

**Issue by bornova** [olifolkerd/tabulator#3407]
**Describe the bug**
Calling `setData` after creating new Tabulator instance fails with following message in console:
> "setData failed - table not yet initialized. To set initial data please use the 'data' property in the table constructor."

**Tabulator Info**
- v5.0.1

**Working Example**
- Issue with v5.0.1: https://jsfiddle.net/b2v8jpew/
- Same example with v.4.9.3, no issues: https://jsfiddle.net/9Lb3076d/

**To Reproduce**
See warning message in console

**Expected behavior**
Should be able to use `setData` after creating Tabulator table.

**Comment by mcaskill** [comment]
I forgot to mention that I tried that and it actually does not work: https://jsfiddle.net/mcaskill/ecqs0j4a/4/

**Comment by junjie** [comment]
It sounds like we're discouraged from using `table.setData()` now. The [documentation for 5.0](http://tabulator.info/docs/5.0/data#array) doesn't mentioned anything about needing to call this in the `tableBuilt` event. I think that could be improved on?

Thanks for the great library @olifolkerd!
