### ISSUE TITLE
If frozen option is used, each even row do not disappear when scrolled horizontaly

### ISSUE THREAD

**Issue by davyjansen** [olifolkerd/tabulator#3411]
**Describe the bug**
When you horizontally scroll the table, with frozen column(s), the even rows from the not frozen columns do not disappear under the frozen columns. This is only with the even(each second) rows. The uneven and hover rows do disappear as it should.

**We use the theme: tabulator_bootstrap4.css**

**Tabulator Info**
- 5.0.1

**Working Example**
https://jsfiddle.net/eLb50y9d/2/

**To Reproduce**
1. Opening the jsfiddle, the result is okay
2. Scroll horizontally
3. Each even row does not disappeer under the frozen (first) columns
4. Uneven rows, and rows you hover, doe disappear as it should and as you expected to do

**Expected behavior**
Each second/even row need a z-index or something to hide the text when scrolling horizontally. The text of the (not frozen) column has to go under the frozen column, just like the uneven rows and the hover rows are.

**Screenshots**
![image](https://user-images.githubusercontent.com/2939150/138046646-1166d5a4-c57a-4695-95ea-681e2c19de2b.png)

**Desktop:**
 - OS: Win 10
 - Browser: Chrome
 - Version: 94.0 + 95.0 (latest atm)

Thanks in advance.

**Comment by davyjansen** [comment]
It looks like something is wrong with the background-color, not with the z-index what was my first thought.

**Comment by olifolkerd** [comment]
Hey @davyjansen 

Thanks for the detailed investigation there, it was really helpful.

I have pushed a fix for this to the master branch and will include it in this evenings patch update.

Cheers

Oli :)
