### ISSUE TITLE
headerFilter not working on grouped table

### ISSUE THREAD

**Issue by jaguarxii** [olifolkerd/tabulator#3414]
**Describe the bug**
After upgrading to v5.0.2 the column filters on grouped tables stopped working, no error is thrown, it just doesn't filter the matching rows.

**Tabulator Info**
- v5.0.2

**Working Example**
[codepen example](https://codepen.io/jaguarito/pen/oNezjoZ)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. There is a grid with two text columns that has "headerFilter" enabled as "input"
2. in the filter of name column use "bob" as filter (without quotes)
3. Any rows are filtered matching the text "bob"
4. Same behavior if trying to filter the "color" column

**Expected behavior**
After typing "bob" as filter of name column, only the first row of the table should be shown.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: waterfox G3.2.6 (gecko 78.14.0), Chrome 94.0.4606.81

**Additional context**
this works perfectly on v4.9.3

**Comment by olifolkerd** [comment]
Hey @jaguarxii 

Thanks for the headsup, i have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)
