### ISSUE TITLE
Helpers.deepClone - complex objects or self-referencing objects

### ISSUE THREAD

**Issue by s-cork** [olifolkerd/tabulator#3415]
**Describe the bug**
Self referencing objects used in data can cause maximum recursion errors
Complex objects in the data lose their meaning when calling `getData()`

**Tabulator Info**
Any (observed in 4+ and 5+).

**Working Example**
https://codepen.io/s-cork/pen/GRvjoaR

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
Open the code pen and check the console
Observe that object `b` has lost its structure
Observe the maximum callstack from an object that references itself.

**Expected behavior**
I would expect Helper.deepClone to handle such cases in some way.
By not cloning complex objects and checking for self referencing.

**Additional context**
When using Tabulator 4 I manipulated the deepClone function to not bother deepCloning certain objects.
These objects were not Object literals but complex objects that would either be displayed using a custom formatter
Or were part of the data set but were not displayed in any Tabulator column/cell.

I had to change the deepClone function since deepCloning was bad news
(in the same way I imagine deepCloning a Date is bad news)
And worse - many of the objects were self referencing somewhere along the way so a deepClone wouldn't work anyway.

Overriding the deepClone function is not so easy in 5+ because it's no longer exposed somewhere on the prototype.

**Suggestion**
Why not only deepClone objects whose constructor is `Object` or `Array`.
Or have some sort of API to override this behaviour.

**Comment by s-cork** [comment]
Great thanks. 

---
re complex objects. 

I have a similar issue in my own project. 
My approach is to do

```js
// we already know typeof obj is "object" and it's not null and not an Array
base = obj.constructor
if (base !== Object && base !== null) {
    // also takes care of Object.create(null);
    return obj;
}
```

It works very reliable. 
Any object that was created using `new` and has a different `__proto__` to Object won't be cloned.

Any object that was created as an object literal will be cloned.

It's not full proof but it does work nearly perfectly. (I have come across libraries that, for whatever reason, have a class instance but actively delete the `constructor`). 

But for any object that was created in a standard JavaScript way it works well.

**Comment by olifolkerd** [comment]
Ive used it before and it has worked just fine, but if it is causing issues for you i can just as easily switch to an array of objects and check against that.

You are correct the date check can now come out, and the array will simply mean adding a [].__proto__ comparison to the mix as well.

I will finalize those tweaks this evening.

Cheers

Oli :)
