### ISSUE TITLE
Click away to Clear Selection

### ISSUE THREAD

**Issue by stack-its** [olifolkerd/tabulator#342]
Is there a function to clear any row selection?  Preferably when you click outside Tabulator, then it clears any selected rows.  Otherwise, holding down shift & clicking/reclicking each row is quite cumbersome ;)

Thanks, Bill

**Comment by olifolkerd** [comment]
are you using Tabulator 2.12 or 3.0?

**Comment by stack-its** [comment]
Tabulator v3.0 - 5/29

**Comment by olifolkerd** [comment]
Hi Bill,

If you dont pass any arguments into the ***selectRow** or ***deselectRow*** functions they will select/deselect the entire table.

i will update the documentation as this appears to have been missed out.

Cheers

Oli
