### ISSUE TITLE
Issues on "rowMouseEnter", "rowMouseLeave" events

### ISSUE THREAD

**Issue by Heran-foo** [olifolkerd/tabulator#3428]
Hello Olifolkerd,
Tabulator is really a great package to work with. And it has been really great that you have upgraded your package to 5.0, As I was upgrading tabulator 4.9 to 5.0, I noticed that "rowMouseEnter" and "rowMouseLeave" events are not working even tho I have imported "InteractionModule" as mentioned in the documentation. Hence I would be very grateful for the help if you could look into it. 
And here is my piece of code where I have implemented those two events:
tabulator.value.on("rowMouseEnter", function (e, row){
                alert("Mouse Entered)
                });
tabulator.value.on("rowMouseLeave", function(e, row){
                    alert("Mouse Leaved")
                });

**Comment by HunarAA** [comment]
I have the same issue and I really need mouse events. I opened an issue for it. I will close it and wait until you fix the bug.

**Comment by olifolkerd** [comment]
Hey @Heran-foo 

I have pushed a fix for this to the master branch and will include it in the next patch release.

Cheers

Oli :)

**Comment by Heran-foo** [comment]
apology for the delay, will check it out and let you know if there is any
issue.
