### ISSUE TITLE
Image tag - url to src

### ISSUE THREAD

**Issue by stack-its** [olifolkerd/tabulator#343]
I noticed in image cells, that the img tag has url="..." & the image is not rendering.  If you change it to src="..." then it renders as expected and the path is still editable when you click on the cell, which is good.

**Comment by olifolkerd** [comment]
are you using Tabulator 2.12 or 3.0?

**Comment by olifolkerd** [comment]
hey,

Good Spot!

i will fix that this evening.

Cheers

Oli

**Comment by olifolkerd** [comment]
This has now been resolved. :)
