### ISSUE TITLE
Issue with headerfilters and rowSelectionChanged.

### ISSUE THREAD

**Issue by ferriroberto** [olifolkerd/tabulator#3432]
**Describe the bug**
Upgrading the tabulator version from 4.9 to 5 I encountered a problem. When I insert a select filter in the header of the table, the "rowSelectionChanged" event is activated from the moment of clicking on the select form in the header table. This included any subsequent operations.

**Tabulator Info**
- Tabulator 5.0.5 (upgrade from 4.9)

**Working Example**
https://jsfiddle.net/Robertoferri/ax3q6gwc/21/

**To Reproduce**

1. Go to https://jsfiddle.net/Robertoferri/ax3q6gwc/21/
2. Click on gender row 'select' filter 
3. displays the log generated by clicking on the filter in the console

**Expected behavior**
In version 4.9 everything works fine. 

**Desktop (please complete the following information):**
 - OS: [e.g. windows, linux]
 - Browser [e.g. chrome]

**Smartphone (please complete the following information):**
 - Version [e.g. 95.0.4638.54]

**Comment by olifolkerd** [comment]
Hey @ferriroberto 

Thanks for the headsup, i have pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)
