### ISSUE TITLE
An error occurred while trying to move the column that was changed by updateDefinition

### ISSUE THREAD

**Issue by biv-21** [olifolkerd/tabulator#3433]
**Describe the bug**
An error occurred while trying to move the column that was changed by updateDefinition

**Tabulator Info**
- Tabulator 5.0.5

**Working Example**
https://jsfiddle.net/g0r8ahjk/11/

**To Reproduce**
1. Go to https://jsfiddle.net/g0r8ahjk/11/
2. Click on 'freeze first row' button
3. Click on 'update title for column 2' button
4. Move column 2 by drag'n'drop
5. See error in console (if scroll table down we can see problem shown on the screenshot)

**Expected behavior**
No error, column move correctly 

**Screenshots**
![tabulator-bug](https://user-images.githubusercontent.com/11851199/138861858-e4135bdc-2194-41f5-8926-568109ad3412.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 93.0

**Comment by olifolkerd** [comment]
Hey @biv-21 

Thanks for the info, i have pushed a fix for this to master and will include it in this afternoons patch release.

Cheers

Oli :)
