### ISSUE TITLE
Deleting a row fails: rowDeleted (history.js)

### ISSUE THREAD

**Issue by ivanuci** [olifolkerd/tabulator#3434]
When history is set to true, deleting row fails with an error: this.history.action is not a function

https://codepen.io/ivanuci/pen/ExvWqdP

`{
      key: "rowDeleted",
      value: function rowDeleted(row) {
        var index, rows;

        if (this.table.options.groupBy) {
          rows = row.getComponent().getGroup().rows;
          index = rows.indexOf(row);

          if (index) {
            index = rows[index - 1];
          }
        } else {
          index = row.table.rowManager.getRowIndex(row);

          if (index) {
            index = row.table.rowManager.rows[index - 1];
          }
        }

        // this.history.action("rowDelete", row, {
        this.action("rowDelete", row, {
          data: row.getData(),
          pos: !index,
          index: index
        });
      }
    }
`

**Comment by olifolkerd** [comment]
Hey @ivanuci 

Thanks for the headsup,

I have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)
