### ISSUE TITLE
Headers shifted after scrollToRow first row

### ISSUE THREAD

**Issue by julien-delenclos** [olifolkerd/tabulator#3435]
**Describe the bug**
Headers are shifted during a scrollToRow on the first line

**Tabulator Info**
4.9.3

**Working Example**
https://jsfiddle.net/y7v05td4/1/

**To Reproduce**
1. Scroll to right or use first button
2. Use second button to scrollToRow 0 (first)

**Expected behavior**
Correct header position or don't reset horizontal scroll

**Screenshots**
![image](https://user-images.githubusercontent.com/59362955/138912547-d6b906c1-972e-489f-9c7d-2e23d9e1cf8f.png)

**Additional context**
See https://github.com/olifolkerd/tabulator/blob/2ca07c5a917174a24210330046e4ade0a334659e/src/js/row_manager.js#L1425
"If(!position)" also includes the position 0

**Comment by olifolkerd** [comment]
Hey @julien-delenclos 

This issue has be resolved in the 5.0 release. I would suggest upgrading to the latest version of Tabulator.

Cheers

Oli :)
