### ISSUE TITLE
setgroupby does not work well (5.0.5)

### ISSUE THREAD

**Issue by jaguarxii** [olifolkerd/tabulator#3438]
**Describe the bug**
After upgrading to v5.0.5 the "setGroupBy" method is not working as expected, in some cases leaves all groups empty and in other cases creates extra groups.

**Tabulator Info**
5.0.5

**Working Example**
[Codepen sample](https://codepen.io/jaguarito/pen/oNezjoZ)

**To Reproduce**
I have two scenarios where "setGroupBy" fails:

scenario 1:
1. Click on "set group by" button, it will group the table by "name" 
2. The table duplicates each group, leaving one group empty and one group with the matching rows

**Expected behavior**
It should leave the table with five groups and one row within each group.

![name_group_result](https://user-images.githubusercontent.com/8013436/139075039-5d87636e-0a05-4c65-ada4-4a077cd5b6b7.png)

scenario 2:
1. edit any cell of the "favourite color" column
2. After editing the cell the table creates empty groups and again duplicates existing groups

**Expected behavior**
It should leave the table with one group for each color.

![color_group_result](https://user-images.githubusercontent.com/8013436/139075076-b4d36c51-32ff-4e9c-abce-d2f0aea661d6.png)

**Desktop (please complete the following information):**
 - OS: Window 10 Pro
 - Browser: WaterFox (latest), Chrome (latest)

**Comment by olifolkerd** [comment]
Hey @jaguarxii 

Thanks for the headsup, looks like the display handler was being bound a second time when the module was reinitialized after the settings change.

I have pushed a fix to the master branch and will include it in this evenings patch release.

Cheers

Oli :)
