### ISSUE TITLE
Generate AJAX params when the request is generated

### ISSUE THREAD

**Issue by KayakFisher205** [olifolkerd/tabulator#3439]
**Describe the bug**
AjaxParams are not being read again after the initial load.

**Tabulator Info**
- 5.0.6

**Working Example**
https://jsfiddle.net/bartlynn/02cdrtwo/33/
This is not a great representation, but maybe close enough to debug.
I have 2 calendars with a Start and an EndDate (Jquery-Ui DatePicker) and I use the value of those for the AJAX call. I've simulated with using a dropdown box, passing the value to the table.

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://jsfiddle.net/bartlynn/02cdrtwo/33/
2. Click on Run
3. The default selection is 2 and the Table shows the data where postId=2.
4. Change the drop down to 1 or 3 and the table flashes, but it remains showing the value of 2. The console is logging the selection and it is correct.

I have also tested passing the ajax data with the setData but all the parameters arrive as null to the server

table.setData('@Url.Action("GetHmWidthData", "Caster")',
                {
                    "startDate": moment(start).format("MM/DD/YYYY HH:mm:ss"),
                    "endDate": moment(end).format("MM/DD/YYYY HH:mm:ss"),
                    "orderBy": $('[name="rbOrderBy"]:checked').val(),
                    "grade": $("#ddlGrade").val(),
                    "aimWidthFilter": 0,
                    "page": pageIndex,
                    "pageSize": 20
                }
            );
**Expected behavior**
When the Dropbox changes values, the table should call the ajax passing the value.

**Screenshots**
none would be helpful.

**Desktop (please complete the following information):**
 - OS:Windows 10
 - Browser Chrome
 - Version 95.0.4638.54

**Additional context**
This was working 4.9.6 but maybe I'm not understand how the 5.0.x version works now with SetData.

**Comment by olifolkerd** [comment]
hey @KayakFisher205 

This s functioning correctly, values passed to an object property are point in time so that object property is only set when it is first defined.

In the next minor version update i will add the ability to pass a function to the `ajaxParams` property so that they can be generated as needed.

Cheers

Oli :)

**Comment by verdonfly** [comment]
after updating to 5.0.7 I am unable to send parameters in Get / Post with Ajax loading.

`table.setData($url,  {codart:codart,sigcos:sigcos,codgru:codgru,codsgr:codsgr,accountid :accountid});`

are you talking about this? @KayakFisher205 @olifolkerd

**Comment by wizarden** [comment]
how to set ajaxParams or ajaxURL without reloading data?

**Comment by verdonfly** [comment]
> how to set ajaxParams or ajaxURL without reloading data?

you have to use the setData, defining ajaxURL in the table definition the data will be loaded when the table object is created.

**Comment by wizarden** [comment]
table.options.ajaxParams ...

**Comment by olifolkerd** [comment]
Hi All,

I have just pushed an update to the 5.1 branch that adds the ability to pass a callback to the `ajaxParams` option , that will be called on each request and should return an object of request params.

This will be included in the 5.1 release.

Cheers

Oli :)

**Comment by pjanickovic** [comment]
Does anyone have experience with this very same problem in react?
