### ISSUE TITLE
Infinite height when trying to add a column in a sub-columns

### ISSUE THREAD

**Issue by simon-milleto** [olifolkerd/tabulator#3440]
**Describe the bug**
When I add a column next to a column which is inside a column, the table height keeps expanding 

**Tabulator Info**
v5.0.5

**Working Example**
https://jsfiddle.net/y5xj0dsw/

**To Reproduce**
1. Run exemple
2. Click "Add column"
3. Observe the height of the table

**Expected behavior**
The height of the table shouldn't expand

**Desktop (please complete the following information):**
 - OS: Mac Big sur
 - Browser: chrome
 - Version 95

**Smartphone (please complete the following information):**
not tested

**Additional context**
Message from the console -> `"ResizeObserver loop limit exceeded"`

**Comment by olifolkerd** [comment]
Hey @simon-milleto ,

Thanks for the headsup, i have pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)

**Comment by simon-milleto** [comment]
Hey @olifolkerd, thanks for the patch. Before the patch, the column that I added was inside the top level column, it was what I wanted to do, but there was the issue with the height of table. Now with the patch, if I add a column next to another one which is inside a column, the added column stays a the top level and not next to the column at sub level. 
How can I do to add a column next to a column at sub level ?
