### ISSUE TITLE
Advanced header based filters support

### ISSUE THREAD

**Issue by slidertom** [olifolkerd/tabulator#3442]
Hi, 
here is a quick and dirty port of filters from tablesorter solution:
https://mottie.github.io/tablesorter/docs/example-widget-filter-custom-search.html#builtin_filters

Source file:
[TabulatorFilters.zip](https://github.com/olifolkerd/tabulator/files/7447912/TabulatorFilters.zip)

Usage:
import {TabulatorFilters} from 'TabulatorFilters.js';

and add:
headerFilterFunc: TabulatorFilters.stringFilter,
in the column definition.

**Comment by olifolkerd** [comment]
Hey @slidertom 

Im afraid i cant accept any zip files as code sources as they can be corrupted or booby trapped and it isn't safe to open them from anonymous sources.

If you believe you have a useful code snippet, either include it directly in the issue or create a pull request for the new feature.

As there is already a filter module in Tabulator, i would not be looking to add a new module, if there is any filter features you would like to add then they would need to be included in the existing filter module.

Tabulator already provides extensive [built in filters](http://tabulator.info/docs/5.0/filter#func-builtin)

If you would like to add additional filter function and make a PR then these can be added to the `/src/modules/Filter/defaults/filters.js` file. 

Please not that if you want to add this functionality yourself it must be your code, we will not accept code copied ad pasted from another library.

Cheers

Oli :)
