### ISSUE TITLE
initialHeaderFilter not working (5.0.5)

### ISSUE THREAD

**Issue by proautodinc** [olifolkerd/tabulator#3444]
**Describe the bug**
On v5.0.5 the "initialHeaderFilter" is not working, data is not been filtered or showed.

**Tabulator Info**
- v5.0.5

**Working Example**
https://codepen.io/proautodinc/pen/gOxGXWB

**To Reproduce**
Removing the initialHeaderFilter from the code will make the table work.
 
**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 95

**Comment by olifolkerd** [comment]
Hey @proautodinc 

Thanks for the headsup, i have pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)
