### ISSUE TITLE
Movable rows between elements not working on Firefox

### ISSUE THREAD

**Issue by MWWorks** [olifolkerd/tabulator#3447]
This is on latest 5.0.7 version. Moving rows between tables or to another element seems not to be working in Firefox.

As per the examples here:
http://tabulator.info/examples/5.0?#movable-between-tables
http://tabulator.info/examples/5.0?#movable-between-elements

These work as expected in Chrome, but not in Firefox. (It seems FF is not getting the mouseup event that tabulator has attached the drop event to?)

(Awesome work BTW!)

**Comment by olifolkerd** [comment]
Closing this as it is a duplicate
