### ISSUE TITLE
Grouped column headers are glitchy to click/drag in v5

### ISSUE THREAD

**Issue by MWWorks** [olifolkerd/tabulator#3449]
**Describe the bug**
When columns are grouped, clicking one of the headers to sort is glitchy - it sort of starts a drag, then click again to change the sort direction. Additionally dragging the column to move it, also moves the parent column and results in misaligned columns.

**Tabulator Info**
5.0.7

**Working Example**
Demonstrated in current example: http://tabulator.info/examples/5.0?#column-groups

**Expected behavior**
Column moves as expected - this seems a bug in v5, v4 was working.

**Screenshots**
After I dragged (and released) 'Progress' one column right between 'Rating' and 'Driver':

![image](https://user-images.githubusercontent.com/1054446/140079222-bdb3c7ac-8a23-4bb3-bafb-f6cfee5282c0.png)

**Desktop**
Tested on Chrome and Firefox

**Comment by olifolkerd** [comment]
Hey @MWWorks 

looks like there was an issue with the movable columns module initializing when it hadnt been enabled. i have pushed a fix for this to the master branch and will include it in the next patch release.

Cheers

Oli :)
