### ISSUE TITLE
Custom Header Filters with non-editable cells

### ISSUE THREAD

**Issue by arelbernardo** [olifolkerd/tabulator#345]
Hi Oli,

I just want to ask if I can create a custom header filter with non-editable cells of the data?
Currently, When I create my custom header filter, It also applies to the data - all the cells within that column are editable and I want that to be non-editable. Thanks!

**Comment by olifolkerd** [comment]
Hi arelbernardo,

if you set the editor in the ***headerFilter*** property of the column definition array instead of the ***editor*** property it should work as needed.

Cheers

Oli

**Comment by juanluep** [comment]
I have a problem, does not show the select in the table header

The code is:

`var selectEditor = function(cell, onRendered, success, cancel, editorParams){
            //Recorro la lista de clientes
            var html = "";
            for(var i=0; i<app.listaClientes.length; i++){
                var nombreCliente = app.listaClientes[i].Nombre;
                nombreCliente = nombreCliente.split("(");
                nombreCliente = nombreCliente[0];
                html += "<option value='"+nombreCliente+"'>"+nombreCliente+"</option>";
            }
            
            //Estilos para el selector de clientes
            var editor = $("<select><option value=''></option>"+html+"</select>");
            editor.css({
                "padding":"3px",
                "width":"100%",
                "box-sizing":"border-box"
            });

            //Set value of editor to the current value of the cell
            editor.val(cell.getValue());

            //when the value has been set, trigger the cell to update
            editor.on("change blur", function(e){
                var valor = editor.val();
                if(/\s+$/.test(valor)) {
                    valor = valor.substring(0, valor.length - 1);
                }
                success(valor);
            });

            //return the editor element
            return editor;
        };`

In columns:

`{title:"Cliente", field:"cliente", sorter:"string", headerFilter:selectEditor, width:120},`

Help please

**Comment by olifolkerd** [comment]
Hey @juanluep,

I would be happy to help, but could i ask that you raise this as a new issue first

This issue has been closed and isn't directly related to your problem, so by creating a new issue you will make it easier for others to find it if they are having similar problems, and make it easier for me to track its resolution.

Cheers

Oli
