### ISSUE TITLE
scrollToRow issue when a horizontal scrollbar is present

### ISSUE THREAD

**Issue by rob5n** [olifolkerd/tabulator#3452]
**Describe the bug**
The scrollToRow() function does not work when there is a horizontal scrollbar present and the rowPosition parameter is "center" or "bottom".  When the row to scroll to is near the bottom of the table, the scroll amount is insufficent, resulting in the row not being visible.

**Tabulator Info**
- 4.9.3

**Working Example**
https://jsfiddle.net/n691xt7r/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://jsfiddle.net/n691xt7r/
2. Click on Scroll To Last Row button
3. Note: it does not scroll to the last row, only near to the last row

**Expected behavior**
I expect it to scroll to the last row.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: firefox
 - Version: 93.0

** tabulator.js code issue **

    RowManager.prototype.scrollToRow = function (row, position, ifVisible) {

    ...

                    case "virtual":

                       // Calling this changes _this11.element.scrollTop, making is smaller by the horizontal scrollbar height?
                        _this11._virtualRenderFill(rowIndex, true);

                        console.debug("scrollTop2 " + _this11.element.scrollTop);

                        break;

    ...

                    case "center":

                        // This is never true, because scrollTop has been changed by virtualRenderFill()
                        // to allow for the horizontal scrollbar height
                        if (_this11.element.scrollHeight - _this11.element.scrollTop == _this11.element.clientHeight) {

                            _this11.element.scrollTop = _this11.element.scrollTop + (rowEl.offsetTop - _this11.element.scrollTop) - (_this11.element.scrollHeight - rowEl.offsetTop) / 2;
                        } else {

                            _this11.element.scrollTop = _this11.element.scrollTop - _this11.element.clientHeight / 2;
                        }

                   // Same issue for this:
                   case "bottom":

**Comment by olifolkerd** [comment]
Hey @rob5n 

Thanks for getting in touch, We are now on version 5.0 which has had a complete rebuild of the redendering systems, so i would suggest you give things a try on that version as it should work better.

You are also not using that function correctly.

The value you pass into the first argument of the `scrollToRow` is either the component for the row or its `id`, not its position in the table. you are therefor trying to load the second from last row with your code. 

In your case i would recomend using the `scrollTo` function on the row component:
```js
table.getRows().pop().scrollTo();
```

which will scroll to that row
