### ISSUE TITLE
Invalid column definition /  Invalid table constructor option issues when using ESM import

### ISSUE THREAD

**Issue by mangkang** [olifolkerd/tabulator#3455]
Hi,

I seem to be having issue getting sorter, formatter and initialSort options to work when using Tabulator as import in React. The exact same code works using the <script> tag in html. Console log reveals the following problems:

Invalid table constructor option: initialSort 
    in TabulatorTable (created by App)
    in App 
Invalid column definition option: formatter 
Invalid column definition option: sorter 

Please let me know if i am missing something. Thanks!

To reproduce:
See console log in the following:
https://codesandbox.io/s/reverent-bassi-42o3f?file=/src/TabulatorTable.tsx

Expected Behavior (works perfectly using <script>):
https://jsfiddle.net/tor0L3z7/

Tabulator Version: 5.0.7

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version 95.0.4638.69 
 
![Screen Shot 2021-11-04 at 8 52 26 PM](https://user-images.githubusercontent.com/13228625/140455473-afe372ea-3bbf-4169-833f-465c488fce59.png)

**Comment by Puhgee** [comment]
Hi there,

I experienced the same "issue", but i could resolve it by looking into two documentation pages.
The import is quiet different: while on the one hand importing with html tag is loading a pre bundled Tabulator instance with basically all the available modules, on the other hand the module import is just importing the Core-module. So depending on what modules you want to use (like FormatModule, SortModule), you have to import them to and register them to the core (or use the TabulatorFull import).

So i guess in your case this will fix the problem:
`import {TabulatorFull as Tabulator} from 'tabulator-tables';`

The behavior is mentioned in the documentation under "Core With Optional Modules"
http://tabulator.info/docs/5.0/install#setup-basic

Overview of all available modules is also available in the documentation
http://tabulator.info/docs/5.0/modules

**Comment by mangkang** [comment]
Hi @Puhgee, Indeed that fixes the problem. Thanks!

**Comment by AndrewHutcheson** [comment]
@Puhgee 
This also helped me, thanks!
