### ISSUE TITLE
Click events doesn't work when tabulator object is created from HTML table

### ISSUE THREAD

**Issue by gregr77** [olifolkerd/tabulator#3457]
**Describe the bug**
When tabulator object is created from HTML table rowClick event doesn't work. Note that other left or right mouse click events I tried don't work in that case too. 

**Tabulator Info**
Version 5.0.7

**Working Example**
https://jsfiddle.net/bf1t9y0z/

**To Reproduce**
Click on any row.

**Expected behavior**
Alert message 'table row clicked' should be shown but it doesn't.

**Comment by cgountanis** [comment]
Same issue.

**Comment by olifolkerd** [comment]
Hey @cgountanis 

Defo a bug there, i have pushed a fix to the master branch and will include it in the next patch release.

Cheers

Oli :)
