### ISSUE TITLE
Multiselect editor causes unexpected deletions

### ISSUE THREAD

**Issue by hkcomori** [olifolkerd/tabulator#3459]
**Describe the bug**
Performing a special procedure in the multiselect editor will clear the cell data.

```js
editor: 'select',
editorParams: {
    multiselect: true
}
```

After step 3 of 'To Reproduce', choices are not hidden when I click elsewhere.
There may be a problem with the processing when right-clicking on a choice.

**Tabulator Info**
- 5.0.7
- 4.9.3

**Working Example**
https://jsfiddle.net/5t3h6x9u/

**To Reproduce**
1. Left click on Bob's select cell
2. Right click on any choice
3. Left click on Bob's select cell
4. Left click out of the table
5. Bob's select cell is cleared

**Expected behavior**
Bob's select cell is not cleared.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H1
 - Browser chrome
 - Version 95.0.4638.69

**Comment by olifolkerd** [comment]
I have just pushed updates to the 5.2 branch that replaces the ***select*** and ***autocomplete*** editors with the new ***list*** editor, which will resolve this issue.

It will be included in the 5.2 release later this month.

Cheers

Oli :)
