### ISSUE TITLE
Sorting with ajax data

### ISSUE THREAD

**Issue by adrianjones1** [olifolkerd/tabulator#346]
In V2 when the sort icon on a column was clicked tabulator would autmatically call my ajax handler to update the data. This was set using .tabulator("setData"). 

In V3 clicking a sort icon doesn't seem to trigger the ajax handler to be called. I tried adding

ajaxSorting: true,

but this didn't seem to make a difference. I also tried manually updating the table data using the dataSorting event handler but that seems to be called continuously rather than just once.

Is there some other way I can know when a user has clicked a columns sort icon so that I can manually update the table data from my ajax handler.

Thanks
Adrian

**Comment by adrianjones1** [comment]
I think I found a solution using the headerClick event.

**Comment by olifolkerd** [comment]
Hi Adrian,

As long as you set the ***ajaxURL*** and ***ajaxSorting*** properties, Tabulator will re-trigger the request when the header is clicked, unless you have disabled header sorting on that column.

```js
$("#example-table").tabulator({
    ajaxUrl:"ajaxdata.php",
    ajaxSorting:true,
    columns:[...],
});
```

**Comment by taniamm20022** [comment]
h

> Hi Adrian,
> 
> As long as you set the _**ajaxURL**_ and _**ajaxSorting**_ properties, Tabulator will re-trigger the request when the header is clicked, unless you have disabled header sorting on that column.
> 
> ```js
> $("#example-table").tabulator({
>     ajaxUrl:"ajaxdata.php",
>     ajaxSorting:true,
>     columns:[...],
> });
> ```

Hi I am so sorry sorry for bothering you, but 

foe example in my options I set
ajaxSorting: true,
then where should I sent the column names that should be sorted and if it should be asc or desc
I tried in my pagination data sent as I use  ajaxProgressiveLoad

paginationDataSent: {
page: 'page',
size: 'per_page', // change 'size' param to 'per_page'
columns: [
{
column: column,
field: "age",
dir: "asc"
},
{
column: column,
field: "height",
dir: "desc"
}
]
},

Thank you so much for the help
