### ISSUE TITLE
Basic example does not work 

### ISSUE THREAD

**Issue by bambita** [olifolkerd/tabulator#3461]
**Describe the bug**
Basic example for version 5.0 is not working

**Tabulator Info**
- 5.0

**Working Example**
https://jsfiddle.net/9ugfos84/

**To Reproduce**
A step by step guide to recreate the issue in the JS Fiddle
1. Go to 'https://jsfiddle.net/9ugfos84/'
2. Click on 'any row'
3. expected alert
4. nothing triggered
5. console error

```
OptionsList.js:20 Invalid table constructor option: rowClick
value @ OptionsList.js:20
OptionsList.js:20 Invalid column definition option: sortable
value @ OptionsList.js:20
content.js:94 Content Server Web Browser Extension: not applicable for href='http://tabulator.info/basic/5.0'; 
4datetime.js:3 Uncaught ReferenceError: luxon is not defined
    at r.Ie (datetime.js:3)
    at r.date (date.js:9)
    at r.value (Sort.js:422)
    at Sort.js:394
    at Array.sort (<anonymous>)
    at r.value (Sort.js:388)
    at r.value (Sort.js:348)
    at r.value (RowManager.js:671)
    at r.value (Module.js:64)
    at r.value (Sort.js:209)
```

**Expected behavior**
javascript alert for row click, sorting by date is giving another script error in the conole

**Screenshots**
![image](https://user-images.githubusercontent.com/16983664/140983360-ce7df062-bda7-47ca-9c33-1a503478f1b2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome, firefox
 - Version all latest

**Comment by bornova** [comment]
Hi @bambita,
In v5.0 callbacks have now been replaced with events (http://tabulator.info/docs/5.0/upgrade#callbacks)

You should use:
```javascript
table.on('rowClick', (e, row) => {
  alert("Row " + row.getIndex() + " Clicked!!!!")
})
```
For the sorting:
1. `sortable` is not a valid column definition, hence the warning.  You can use `headerSort: false` instead.
2. You will need to include the [luxon.js](https://moment.github.io/luxon) library to use the date sorter

Here is your updated jsfiddle: https://jsfiddle.net/7pf346qd/

**Comment by thjo100** [comment]
> Hi @bambita, In v5.0 callbacks have now been replaced with events (http://tabulator.info/docs/5.0/upgrade#callbacks)
> 
> You should use:
> 
> ```js
> table.on('rowClick', (e, row) => {
>   alert("Row " + row.getIndex() + " Clicked!!!!")
> })
> ```
> 
> For the sorting:
> 
> 1. `sortable` is not a valid column definition, hence the warning.  You can use `headerSort: false` instead.
> 2. You will need to include the [luxon.js](https://moment.github.io/luxon) library to use the date sorter
> 
> Here is your updated jsfiddle: https://jsfiddle.net/7pf346qd/

This is not working if you replace json-data with html table.

**Comment by bornova** [comment]
I was only referencing the JSFiddle you provided.  But, you are right, there seems to be a bug with data from HTML tables and looks like that issue was already reported a few days ago:  #3457

**Comment by olifolkerd** [comment]
The issue in this case was that the luxon include was missing, i have updated the source and will push it to the server with the documentation for the new patch release later today.

Cheers

Oli :)

**Comment by midnightelf** [comment]
i had the same problem. thanks to @bornova for the tip. here is my solution for the problem

1. `npm intall --save luxon`
2.
```
<script>
import { DateTime } from "luxon"
export default {
  ...
  setup(props) { 
    window.DateTime = DateTime 
  }
  ...
}
</script>
```

**Comment by kemken077** [comment]
Inspired in @midnightelf example, I solve it:

first run: `npm install --save luxon`

```
import { DateTime } from 'luxon';
const fixLuxonDepIssue = () => {
     // @ts-ignore
     if (!window.DateTime) {
      // @ts-ignore
      window.DateTime = DateTime;
    }
    // @ts-ignore
    if(!window.luxon) {
      // @ts-ignore
      window.luxon = DateTime;
    }
  };
```


@olifolkerd This should be addressed in a new issue? Thank you.
this still an issue on version `5.4.4`

**Comment by olifolkerd** [comment]
I'm confused, the sorter is working as expected, in your example you just hadn't made luxon globally available.

 I can update the docs to cover this but it isn't a bug, it's a stup issue

**Comment by kemken077** [comment]
> I'm confused, the sorter is working as expected, in your example you just hadn't made luxon globally available.
> 
> I can update the docs to cover this but it isn't a bug, it's a stup issue

I can see Documentation page examples sorting works as expected.
I'm confused now, should luxon be installed globally on my system or by global you meant my project? 
I'm running a SvelteKit one.

Thanks for your response!

**Comment by kemken077** [comment]
@olifolkerd I mean how luxon becomes globally available... Thank you!

**Comment by stefandanzl** [comment]
@kemken077 I was looking for the same answer for Svelte - you don't have to install the npm package.
It's enough to put `<script src="https://moment.github.io/luxon/global/luxon.min.js"></script>` into `index.html`.
See my https://github.com/stefandanzl/Svelte-Tabulator-Template for reference.
