### ISSUE TITLE
html table doesn't use tabulator-* attributes with 5.0.7

### ISSUE THREAD

**Issue by sellersj** [olifolkerd/tabulator#3462]
**Describe the bug**
This works with the examples provided.
If you have a plain html table, the styles get applied but attributes on the th do not get applied.
Doesn't work for tabulator-headerFilter, tabulator-formatter, or tabulator-hozAlign. I assume others.

**Tabulator Info**
Works in 4.9.3
Fails in 5.0.7

**Working Example**
Working example, "age" column is centered
http://tabulator.info/examples/4.9#table-load
Not working example, age isn't centered
http://tabulator.info/examples/5.0#table-load

**To Reproduce**
Just view the examples from the documentation.

**Expected behavior**
I expected the tabulator- to work like 4.9.3

**Screenshots**
![image](https://user-images.githubusercontent.com/4390/140994431-60a9c47a-5b02-402b-b095-8bd5d049d7ee.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser 1: Firefox 94.0.1
 - Browser 2: MS Edge 95.0.1020.44

**Additional context**
n/a

**Comment by olifolkerd** [comment]
Hey @sellersj 

I have pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)

**Comment by sellersj** [comment]
Thanks!
