### ISSUE TITLE
Horizontal VDOM - The column headers are invisible when scroll horizontally

### ISSUE THREAD

**Issue by nghuuphuoc** [olifolkerd/tabulator#3463]
**Describe the bug**
When scrolling horizontally, the column headers are invisible

**Tabulator Info**
5.0

**To Reproduce**
1. Go to http://tabulator.info/examples/5.0?#virtual-dom-hoz
2. Scroll horizontally
3. The header are invisible

**Screenshots**

https://user-images.githubusercontent.com/4226036/141071331-0f849158-301f-4c01-b844-3e9bb7f5d2fe.mp4

**Desktop**
 - OS: macOS 11.6
 - Browser: Chrome version 95.0.4638.69 (Official Build) (x86_64)

**Comment by olifolkerd** [comment]
Hey @nghuuphuoc 

I have pushed a fix for this to the master branch and will include it in the next patch release.

Cheers

Oli :)
