### ISSUE TITLE
DataTree minor issue with v5

### ISSUE THREAD

**Issue by macca44** [olifolkerd/tabulator#3465]
The DataTree expand / contract icons do not appear if the first defined column is set to visible = false

Tabulator Version 5.0.7

Example => https://codepen.io/macca87/pen/ExvpPXB
The DataTree expand / contract icons will only appear when the first column is made visible

This issue did not occur prior to version 5

**Comment by olifolkerd** [comment]
Hey @macca44 

I have pushed a fix for this to the master branch and will include it in the next patch release.

Cheers

Oli :)

**Comment by macca44** [comment]
Awesome, thanks Oli.On 23 Dec 2021 20:01, Oli Folkerd ***@***.***> wrote:
Hey @macca44
I have pushed a fix for this to the master branch and will include it in the next patch release.
Cheers
Oli :)
