### ISSUE TITLE
Call Custom Function on Cell Click/Tap

### ISSUE THREAD

**Issue by stack-its** [olifolkerd/tabulator#347]
Hi Oli,

I'm trying to run a custom function whenever the user clicks on any cell, whether in edit-mode or read-only mode.  I tried several approaches but nothing worked:
1) a basic on-singletap handler using jQuery Mobile Events, as I assumed this event wouldn't be handled by Tabulator & the function was in a separate js file
2) a cellClick function in columns:[] that called my function
3) a cellClick function in the 'root' of tabulator's settings that called my function, i.e.:
...
cellClick:function(e, cell) {
      console.log('Cell click fired');
      myclick(cell);  // call my custom function
},
...
There's got to be a way to do this, I know it can't be that hard, what am I missing?
Thanks,  Bill

**Comment by olifolkerd** [comment]
Hey,

There was an issue with editable cells where the editor blocked the click, i have just added a tweak to allow the cellClick callback to be triggered when a user clicks an editable cell.

Cheers

Oli

**Comment by stack-its** [comment]
Oli,
That's great that editable cell clicks are allowed now, but I still have the problem of detecting w/ read-only cells.  I'm displaying the cell contents in a modal, so it's much easier to see what's in there.  Can you give us a way to detect the click on the read-only cell?  Note: don't need to edit it, basically just getting the contents & viewing in modal ;)
Thanks, Bill

**Comment by olifolkerd** [comment]
Hi bill. 


The cellClick callback will work on all cells regardless of whether they have an editor or not.


Could you post a copy of your Tabulator constructor so I can replicate your issues.

Cheers

Oli

**Comment by stack-its** [comment]
I have it in there like this, as I want it to happen when I click ANY cell:

$("#example-table").tabulator({
  ...
    cellClick:function(cell){
        //cell - cell component
        myclick(cell); // call my custom function
    },
    ...
});

Thanks,  Bill

**Comment by olifolkerd** [comment]
Hi Bill,

could you post your entire constructor object including column definitions, it is important for me to be able to test the interactions between the cellclick function and any configuration options in your column definition array etc.

Cheers

Oli

**Comment by stack-its** [comment]
I'd pref not to post proprietary code 'in the open'  Can you send me a private email & I send it to you.  I just don't want that code showing up in github - I hope you understand.  bill   at    stack-its    dot   com

**Comment by olifolkerd** [comment]
The issue you are having there is that there is no ***cellClick*** callback globally in Tabulator, it must be called per column in the column definition array:

```js

var globalCellClick = function(e, cell){
    //do something
};

$("#example-table").tabulator({
    columns:[
        {title:"Name", field:"name", cellClick:globalCellClick},
        {title:"Age", field:"age", cellClick:globalCellClick},
    ]
});
```
