### ISSUE TITLE
Indentation in data tree is wrong

### ISSUE THREAD

**Issue by mike-lischke** [olifolkerd/tabulator#3470]
**Describe the bug**
A data tree with no tree lines computes wrong indentation and messes up the entire tree layout.

**Tabulator Info**
- Tabulator 5.0.7

**Working Example**
Try this fiddle: https://jsfiddle.net/ta6beLzg/10/

**To Reproduce**
1. Expand the first row (Oli Bob)
2. Check the indentation of the children of that row. At this point it's still correct.
3. Now expand "Brendan Philips".
4. The child rows of that row will be shown, but the parent node ("Brendan Philips") will jump to the same indentation as used for its child rows.
5. This gets worse with every further tree level.

When tree lines are enabled this problem does not occur. Inspecting the DOM shows that with tree lines the indentation is done using margins on the tree line images, while without them the indentation is accomplished by applying a left padding on the first child node.

*Side Bug*: There's another bug here with the data tree: when the tree is scrolled and you expand and collapse nodes the tree scrolls up a few pixels. Doing this often enough you will end up with the tree completely scrolled up (= showing its top node).

**Expected behavior**
When tree lines are not used the computation should be done so that the indentation is correct.

**Screenshots**

This is from my application:

![Bildschirmfoto 2021-11-15 um 13 32 52](https://user-images.githubusercontent.com/2398704/141783033-7b2ab613-303d-4aeb-aa0e-f9838c6242ce.png)

**Desktop (please complete the following information):**
 - OS: macOS 12.0.1
 - Browser: Chrome
 - Version: latest

**Comment by mike-lischke** [comment]
Work around, if you don't want tree lines: switch them on (`dataTreeBranchElement: true,`), but set their CSS class visibility to hidden.

**Comment by olifolkerd** [comment]
Hey,

I have pushed a fix for this to the master branch and will include it in the next patch release

Cheers

Oli :)

**Comment by mike-lischke** [comment]
Great news, like a Christmas gift :-) Thanks and have a great year's end.
