### ISSUE TITLE
Small documentation mistake for module import

### ISSUE THREAD

**Issue by mike-lischke** [olifolkerd/tabulator#3471]
**Website Page**
[A link to the page with the issue](http://tabulator.info/docs/5.0/upgrade#import)

**Describe the issue**
On this page (and only there) the description says one should use `Tabulator.bindModules`, which is wrong:

![Bildschirmfoto 2021-11-15 um 13 46 09](https://user-images.githubusercontent.com/2398704/141784499-cb029138-a9f9-43c3-bec6-e36a654da782.png)

That should be `Tabulator.registerModule`.

**Comment by olifolkerd** [comment]
Hey @mike-lischke 

Thanks for the headsup,

I will get that updated this evening.

Cheers

Oli :)
