### ISSUE TITLE
optional chaining "?" syntax is causing build error

### ISSUE THREAD

**Issue by ngduc** [olifolkerd/tabulator#3474]
**Describe the bug**
Hi @olifolkerd 
First, congrats on v5!! I'm excited trying it out now.
Currently I'm blocked due to this issue with the optional chaining "?" syntax. It's causing build issue like this (locally & in Codesandbox). If I remove the "?" after ("div")[0]... then it will work fine.
Is it possible to remove that syntax. It will help me upgrade react-tabulator. Thanks @olifolkerd 

![image](https://user-images.githubusercontent.com/639189/141929587-d02eab78-1bbd-42ca-9033-914e0917de51.png)

**Tabulator Info**
- Which version of Tabulator are you using? 5.0.7

**Working Example**
YOU MUST include a link to a JS Fiddle or Codepen that demonstrates the problem, it is very hard to diagnose an issue from a simple description.
https://codesandbox.io/s/0mwpy612xw?module=/src/components/Home.js&file=/package.json

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ngduc** [comment]
others are getting the same error:
https://github.com/olifolkerd/tabulator/issues/3403#issuecomment-961181920

**Comment by olifolkerd** [comment]
Which version of node are you building on. This error suggests you are using an old version of node or an old version of Babel that does not understand the newer JavaScript syntax. You may need to update node or your build tools.

I am successfully building this on node 14 without any issues.

**Comment by olifolkerd** [comment]
If you are on node 15 I would suggest checking your build tools.


I'm not saying there isn't an issue. But I have successfully built this in numerous projects since its release which suggest it is more related to the environment that is trying to build it.

Optional property chaining is perfectly valid modern JavaScript so there muse be something in the environment that is being used that is blocking it.

**Comment by ngduc** [comment]
yes, I agree chaining is not something new. It's just strange that even the above Codesandbox link couldn't understand chaining from tabulator_esm.js dist code.

**Comment by olifolkerd** [comment]
But you arnt importing Tabulator directly in that sandbox you are importing react-tabulator.

If you try a simpler example just importing tabulator-tables as a minimum test case and building a simple table it should then work.

If that doesn't work let me know

**Comment by ngduc** [comment]
I've just found out that Codesandbox link used older version of react-scripts (CRA, which used an old webpack 4 version - has issue with optional chaining). I upgraded & it fixed the issue.

not major thing, but I would maximize js compatibility as other users also reported it. but it's up to you :)

**Comment by grosscol** [comment]
I've run into this as well.  Explained in this comment: https://github.com/olifolkerd/tabulator/issues/3403#issuecomment-970540139

**Comment by mangkang** [comment]
Unfortunately, react-scripts (used by CRA) still uses Webpack4 (which internally uses acorn@6 which does not support optional chaining) and this is used in our project.

I tried setting up the pre-release react-scripts 5.0.0-next.47 but ran into other problems so it doesn't seem like a viable solution for us at this time. 

@olifolkerd, is it possible for you to remove the optional chaining code temporarily to ensure maximum compatibility for Webpack4 users ?

**Comment by olifolkerd** [comment]
Hey All,

Thanks for the feedback, i have just pushed an update to the master branch to remove option chaining and will include it in this evenings patch release.

Cheers

Oli :)
