### ISSUE TITLE
Error executing getData() on Row object

### ISSUE THREAD

**Issue by danilomartins90** [olifolkerd/tabulator#3476]
We are using the Tabulator version v4.9.3 and when I call "cell.getRow()" in the Calculations line it returns a Row object, however in the 5.0.7 version it doesn't return, or it returns but gives an error when calling getData() on the Row object.

And this is even preventing us from migrating to version 5 of Tabulator, I believe this is a bug in version 5.

Below is the Codepen link:
https://codepen.io/danilomartins90/pen/dyzwNYp

When opening the link, the error appears on the console and when clicking on the "print" button, the error also occurs.

![erro_tabulator](https://user-images.githubusercontent.com/9057480/142080254-e6262259-8369-4e48-9f53-934114406deb.png)

The expected behavior was to work correctly performing the calculation in the function calls and when printing too.

Could you help me with this?

**Comment by cfiles** [comment]
I get the exactly the same error when using rowFormatter with row.getData() on a Tabular object that has either bottomCalc or topCalc in any of the fields. 

If I remove all the bottomCalc and topCalc commands the rowFormatter works correctly.

**Comment by MarianSamartean** [comment]
I'm facing the same problem with rowFormatter without having any other  special functions.

var table_data = new Tabulator("#table_data", {
    addRowPos:"top",
    height:950,
    layout:"fitColumns",
    data: rowTableData,
    columns: columnsTableData,
    rowFormatter: function(row){
            const rowData = row.getData();
            ...
    }
}
And it gives me the same error with this._row.getData from CalcComponent like in the picture attached by @danilomartins90 
Did anyone solve this problem?

**Comment by olifolkerd** [comment]
Hey All,

I have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)
