### ISSUE TITLE
Multiselect with sorted group options breaks the groups

### ISSUE THREAD

**Issue by harold-padilla** [olifolkerd/tabulator#3478]
**Description**
I was scratching my head for a little bit because I had a multiselect editor combined with group options and also had sortValuesList set to `asc`. This made the list be sorted in ascending order but it totally ignores the defined groups. For example, I had two groups name Odd and Even; these had values of One and Three and Two, Four, and Six, respectively. With sortValuesList=asc, the dropdown list shows Odd group as it contains all the strings, except for Four, which in this case appears under Even (see fiddle).

**Tabulator Info**
5.0.7

**Working Example:**
https://jsfiddle.net/cdkmtyw8/2/

**To Reproduce:**
In the JS Fiddle:
1. Click any cell under the Select column.
2. See wrong order.

**Expected behavior:**
I think that if sorting will be enabled for grouped options, it should order first the groups by name and then also sort the options on a per group basis.

**Desktop:**
 - OS: macOS
 - Browser: Chrome
 - Version 96.0.4664.55 (Official Build) (x86_64)

**Comment by olifolkerd** [comment]
I have just pushed updates to the 5.2 branch that replaces the ***select*** and ***autocomplete*** editors with the new ***list*** editor, which will resolve this issue.

It will be included in the 5.2 release later this month.

Cheers

Oli :)
