### ISSUE TITLE
data.col always shows undefined 

### ISSUE THREAD

**Issue by swiftinitdotcom** [olifolkerd/tabulator#3479]
var data = row.getData();

**console.log(data);
console.log(data.col);**

data.col always shows undefined 
I see below in logs-

{ob_Subscriber_RID: 627036, importedpenname: 'Pen 5', date1: '2021-08-30T00:00:00', Corn [lb]: null, Corn: null, …}
undefined

**Comment by LilDevil** [comment]
I don't see a field named `col` in your data. What if you do `console.log(data.date1);` ?

Or if `col` is a variable containing a field name, `console.log(data[col]);`
