### ISSUE TITLE
Nested field unpacking

### ISSUE THREAD

**Issue by AfroYetty** [olifolkerd/tabulator#3480]
This might already be a feature but I can't seem to find it in the docs.

**Request**

Allow nested field unpacking

**Context**

The main reason for this is to avoid the manual pre-processing of the rows, as the dataset gets larger the additional overhead will reduce site performance. It's also a drag and dirty doing it manually.

*Current Solution*

Currently managed by the UI and server, but a built in function will help for future dynamic configuration of the table on my users profiles :)

**Current Data Structure**

```json
{
    "id": 810923,
    "rootKey": "Root Value",
    "data": {
        "value1": "Value One",
        "value2": "Value Two"
    }
}
```

**Configuration**

```js
autoColumnsDefinitions:[
    {title:"Column One", field:"data", mutator: (value, data, type, params, component) => {
        return value.value1
    }},
    {title:"Column Two", field:"data", mutator: (value, data, type, params, component) => {
        return value.value2
    }}
]
```

**Produced Output** 
```
+--------+------------+------------+
|   id   |  rootKey   | Column One |
+--------+------------+------------+
| 810923 | Root Value | Value One  |
+--------+------------+------------+
```

**Desired Output**
```
+--------+------------+------------+------------+
|   id   |  rootKey   | Column One | Column Two |
+--------+------------+------------+------------+
| 810923 | Root Value | Value One  | Value Two  |
+--------+------------+------------+------------+
```

**Proposed**

I believe tabulator is already 99% able to do this, by the looks of it, it's the "field" value that is preventing the duplication, a combination of the `field` and `title` values might help create a unique name in the context of the table

**Comment by LilDevil** [comment]
Why not just do [this](http://tabulator.info/docs/5.0/columns#field-nesting) ?

```
autoColumnsDefinitions:[
    {title:"Column One", field:"data.value1"
    },
    {title:"Column Two", field:"data.value2
    }
]

```

**Comment by AfroYetty** [comment]
@LilDevil You little devil you, yah that works, thanks :)
