### ISSUE TITLE
Problem after updating Chrome to version: 96.0.4664.45 and move row

### ISSUE THREAD

**Issue by verdonfly** [olifolkerd/tabulator#3483]
After updating Chrome in my projects I get this error when trying to move a row.

tabulator.min.js:10 Uncaught TypeError: Cannot read properties of null (reading 'insertBefore')
    at N.endMove (tabulator.min.js:10)
  

    The problem is not on Firefox.

    I tried to replicate the problem on JsFiddle but without success.
I have used tabulator in 10 complex projects and therefore cannot copy my table code.
The problem is repeated in different versions of tabulator from 4.7 to 4.9.3

**Comment by LilDevil** [comment]
It works in the [examples](http://tabulator.info/examples/5.0#movable), and it works in JsFiddle, so I dare say the problem is in your code, and not in Tabulator.

**Comment by verdonfly** [comment]
I know in fact I immediately tried both on tabulator and on JsFiddle. I wanted to know if anyone with this version had any problems.
Everything works perfectly with Firefox so I don't think it's a code problem.

**Comment by grosscol** [comment]
@verdonfly I also have a difficult time with jsfiddle.  Can you set up a gist that I can open locally in both browsers and see the problem?  Just inline the js in a static html file.

**Comment by verdonfly** [comment]
I  had to upgrade to 5.0.7 to get it to work. Now I'm trying to get the rest to work.
I don't understand what happened anyway.
