### ISSUE TITLE
Deprecated dataSentNames  and dataSentNames  setup options still being used by pagination module

### ISSUE THREAD

**Issue by jonolsu** [olifolkerd/tabulator#3484]
**Website Page**
Page 1 -> http://tabulator.info/docs/5.0/release
Page 2 -> http://tabulator.info/docs/5.0/modules#module-page
Page 3 -> http://tabulator.info/docs/5.0/page

**Describe the issue**
Page 1: In the Request & Params Mapping Section, there appears to be a typo with the dataSendParams. 
There is an errant double quote after size . . . or perhaps both last_page and size are both supposed to be enclosed in double quotes?  I'm struggling to get remote pagination to work and can't, and my weak JavaScript doesn't help.  So I can't be sure what this code in the document should be:

    dataSendParams:{
      page:"current_page",
      size":"page_size",
    },

Page 2: Again, trying to make remote pagination work but I see references to paginationDataSent . . . which is gone in 5.0, right?

At the top of the pagination section:
"Any of the default <i>paginationDataSent</i> options can be extended

    Tabulator.extendModule("page", "paginationDataSentNames", {
        "page":"pageNo",
    });

Also,if you search for paginationDataSent or paginationDataReceived you'll find three total pages where it's referenced as being a current construct.  Perhaps the most misleading for me is on Page 3 just below the Remote Pagination / Request URL sample code:

    var table = new Tabulator("#example-table", {
        pagination:true, //enable pagination
        paginationMode:"remote", //enable remote pagination
        ajaxURL:"http://testdata.com/data", //set url for ajax request
        paginationDataSent:{
            "page":"pageNo", //change page request parameter to "pageNo"
        } ,
    });

In fact, neither dataSendParams nor dataReceiveParams are referenced anywhere in the documentation except for the release notes.

I wonder -- does remote pagination in 5.0 work yet?  I stumbled across this code on lines 25 & 26 at https://github.com/olifolkerd/tabulator/blob/cd094482af8792ae16931809e55b834020aa496a/src/js/modules/Page/Page.js

		this.dataReceivedNames = {}; //TODO - remove once pagimation update is complete
		this.dataSentNames = {}; //TODO - remove once pagimation update is complete

Thank you for your help!  I wish I could help to contribute to the solution, but I'm more of a Python programmer. If I figure something out then I'll make a documentation update recommendation.

**Comment by grosscol** [comment]
I also ran into the `dataSentNames` not being implemented issue.

Instead you can manually build the url for the requests.  E.g. like I did with this [fiddle example](https://jsfiddle.net/grosscol/gcs0ronk/23/)
```js
  // Hack request to use albumId instead of page                                                                                            
  ajaxURLGenerator: (url, config, params) => {
    return url + "?albumId=" + params.page;
  },
```

**Comment by olifolkerd** [comment]
Hey @jonolsu 

Thanks for the info, i will get the updates to the documentation online this evening,

As for the missing params, you are correct, these seem to be missing in the release.

I will get these implemented in the next patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Looking into this further, the pagination modules were working correctly, the `TODO` notes only referred to variables used when generating the error messages for missing params in the response.

I have pushed a fix for this to master and will include it in the next patch release.

Cheers

Oli :)
