### ISSUE TITLE
Interaction Error with Column Calculations and rowMouseOver listener

### ISSUE THREAD

**Issue by danieleperilli** [olifolkerd/tabulator#3486]
**Describe the bug**
I created a table with a bottom calculations row and a listener for the rowMouseOver event; when I move the mouse over the calculations row the browser throws an error in the console. I didn't find a way to catch it.
Can you help me?

**Tabulator Info**
v5.0.7

**Working Example**
Check this code: https://jsfiddle.net/danieleperilli/xqzf4o6e/
Just open the JavaScript console and move the cursor over the last row of the table (the calculations one).

<img width="1272" alt="Screenshot 2021-11-25 at 17 47 49" src="https://user-images.githubusercontent.com/9072177/143478931-a31a9d86-dab4-4067-aec3-007d3699539c.png">

**Desktop**
 - OS: Mac OS
 - Browser: Chrome
 - Version: Latest

**Comment by olifolkerd** [comment]
Hey @danieleperilli 

I have pushed a fix for this to the master branch and will include it in the next patch release.

Cheers

Oli :)

**Comment by danieleperilli** [comment]
Thank!
