### ISSUE TITLE
paginationAddRow: "table" - not working.

### ISSUE THREAD

**Issue by LebCit** [olifolkerd/tabulator#3487]
**Describe the bug**
paginationAddRow option is not working.

**Tabulator Info**
- Which version of Tabulator are you using?
- v5.0.7

**Working Example**
[Tabulator - paginationAddRow](https://codepen.io/LebCit/pen/vYJobdJ)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Visit the link
2. Wait 3 seconds
3. The new row is added to the end of the page and not to the end of the table

**Expected behavior**
The new row should be added to the end of the table since the paginationAddRow option is set to table

For now, I've solved this issue like so :
```
table.setPage(lastPage)
    .then(function () {
        //run code after table has been successfuly updated
        table.addRow(dataObject)
    })
    .catch(function (error) {
        //handle error loading data
        console.log('Request Failed', error)
    });
```
After trying many JS grid, I just want to say **Thank you very much for your time and efforts**, Tabulator is Fantastic !

**Comment by LebCit** [comment]
For anyone reading my solution in the above comment
>table.setPage(lastPage)
    .then(function () {
        //run code after table has been successfuly updated
        table.addRow(dataObject)
    })
    .catch(function (error) {
        //handle error loading data
        console.log('Request Failed', error)
    });

Please don't try it, it's wrong !
**Explanation :**
If you have a paginated data, let's say 10 rows and each 5 rows are on a page, so you have 2 pages.
Now if you want to add a new row, the code above is looking for a lastPage variable (here 3, the third page).
But pagination have only 2 pages, so it will fail since their is no page 3 yet !
Of course their is a solution to this, but it's more like a tiny hack...
So be patient, and wait for the fix to be ready :slightly_smiling_face:

**Comment by olifolkerd** [comment]
Hey @LebCit 

I have just pushed a fix for this to the master branch and will include it in this afternoons patch release.

Cheers

Oli :)
