### ISSUE TITLE
setGroupBy not working on v5.0.7

### ISSUE THREAD

**Issue by proautodinc** [olifolkerd/tabulator#3488]
**Describe the bug**
In version 5.0.6 this bug was fixed but is back on 5.0.7

**Tabulator Info**
5.0.7

**Working Example:**
[https://jsfiddle.net/4r8phmeu/](url)

**To Reproduce**
Change the value in the dropdown select button

**Expected behavior**
setGroupByTable should run at load and also when the value change in the dropdown select button

**Comment by bornova** [comment]
Hi @proautodinc,
Seems like in your `run()` function you forgot to pass the `groupValue` variableto the `setGroupBy` call. Change `table.setGroupBy("status")` to `table.setGroupBy(groupValue)` and it works as expected.

**Comment by proautodinc** [comment]
Hi @bornova, Thank you, I forgot to change this part of the code, but it was correct on my localhost, The grouping is working but on my computer I'm getting an error in the debuging area that I couldn't reproduce in the jsfiddle:
`Uncaught (in promise) TypeError: Cannot create property 'innerHTML' on boolean 'false'`.
