### ISSUE TITLE
movableColumns: false not working

### ISSUE THREAD

**Issue by radixcl** [olifolkerd/tabulator#3489]
Hi,

I'm trying to build a spreadsheet where the columns cannot be moved.

I'm trying with "movableColumns: false" when building the object, but I still can move the columns by drag&drop:

`    custom_data.table = new Tabulator("#placeholder_spreadsheet", {
        movableColumns: false, // dont allow column moving
        data: tabledata, //assign data to table
`

Having a look at the source module, it seems that movableColumns attribute is never checked, thus, allowing the user to move the columns freely.

**Comment by Benjamin-K** [comment]
Hi, i'm having the exact same problem.

**Comment by radixcl** [comment]
I managed to get it working with an ugly workaround:

```
    document.querysSelector('#tabulator').addEventListener('mousedown', function(event) {
        // disable column drag & drop
        event.stopPropagation();
    }, true);
```

**Comment by Benjamin-K** [comment]
Should be fixed here:
https://github.com/olifolkerd/tabulator/blob/b3143137511aff8e7646267e54571d26c09e1374/src/js/modules/MoveColumns/MoveColumns.js#L38

I think, this line should be wrapped with
```if (this.table.options.movableColumns) {...} ```

**Comment by Benjamin-K** [comment]
> Should be fixed here:
> 
> https://github.com/olifolkerd/tabulator/blob/b3143137511aff8e7646267e54571d26c09e1374/src/js/modules/MoveColumns/MoveColumns.js#L38
> 
> I think, this line should be wrapped with `if (this.table.options.movableColumns) {...}`

I've tested the above change locally and can confirm, that this is working. But i'm unable to create a new build, otherwise i would create a PR. 

Change https://github.com/olifolkerd/tabulator/blob/b3143137511aff8e7646267e54571d26c09e1374/src/js/modules/MoveColumns/MoveColumns.js#L38 to:

```
if (this.table.options.movableColumns) {
    this.subscribe("column-init", this.initializeColumn.bind(this));
}
```

Btw: The almost same code is already used in the `MoveRows` module.

**Comment by olifolkerd** [comment]
This has now been resolved on master and will be included in a patch release later today.

Cheers

Oli :)
