### ISSUE TITLE
Resize Tabulator with window resize event

### ISSUE THREAD

**Issue by fdabrao** [olifolkerd/tabulator#349]
Hello all,

I tried to use $("#grid").tabulator("redraw") to redraw all the table, but only width happens. How about the height? Is there any way to redraw all table?

Regards

**Comment by olifolkerd** [comment]
Could you post a copy of your table constructor so i can see how you have your table set up.

How are you defining your tables height? in CSS or in the ***height*** property of the constructor object?

Cheers

Oli

**Comment by olifolkerd** [comment]
closed due to inactivity
