### ISSUE TITLE
ReferenceError: resolve is not defined

### ISSUE THREAD

**Issue by agbianchessi** [olifolkerd/tabulator#3490]
https://github.com/olifolkerd/tabulator/blob/41e79e1eacbb285783f561899e5e8836d2e0d75d/src/js/core/Tabulator.js#L647

**Comment by olifolkerd** [comment]
Hey @agbianchessi 

I have pushed a fix for this to the master branch, and will include it in todays patch release.

Could i ask next time you find an issue that you fill in a "bug Issue Template" as the issue you raise there had no context and was a bit cryptic.  we can get things fixed faster if you can provide us with more details.

Cheers

Oli :)
