### ISSUE TITLE
Tabulator 5.0 documentation bug

### ISSUE THREAD

**Issue by cfiles** [olifolkerd/tabulator#3494]
rowClick is implemented incorrectly in quickstart guide... should be table.on()

http://tabulator.info/docs/5.0/quickstart

Example startup: 
...
rowClick:function(e, row){ //trigger an alert message when the row is clicked
 		alert("Row " + row.getData().id + " Clicked!!!!");
 	},

**Comment by olifolkerd** [comment]
Hey @cfiles 

Thanks for the headsup,

I have updated this locally and will push an update to the site shortly.

Cheers

Oli :)
