### ISSUE TITLE
Custom setFilter not in persistence/saved filters

### ISSUE THREAD

**Issue by davyjansen** [olifolkerd/tabulator#3495]
**Describe the bug**
if i set a custom filter with setFilter it willl not be saved in the persistence

**Tabulator Info**
- latest / 5.0.7

**Working Example** / **To Reproduce**
`table_products.setFilter(
	[{field:"category", type:"=", value:filter_category.value},]
);`

it directly filter the results and also comes visible in `persistenceReaderFunc:function(id, type){`

but after refresh: `table_products.getFilters()` filter is `null`
sort and columns are in the getFilters(), but 'filter' isn't saved in the persistence if added with `setFilter`

**Expected behavior**
A saved result in the getFilters like `0: {field: 'category', type: '=', value: 'Plants'}` 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: latest / 96.0

**Comment by rain01** [comment]
I have the same issue.
It seems persistence feature can't remember "sort" either: http://tabulator.info/examples/5.0#persistence

It does remembers column order and width. 👍

**Comment by olifolkerd** [comment]
@davyjansen  or @rain01 

Please provide a link to a JS Fiddle or codepen that demonstrates your issue. Without seeing how your table is configured it is impossible to offer advice on what may be the issue there.

Cheers

Oli :)

**Comment by rjaros** [comment]
@olifolkerd Please check this fiddle: https://jsfiddle.net/7xqsgdym/
Neither column sorting nor pagination is remembered after re-running the code (although the data is saved correctly to the local storage).
It was working correctly on 4.9.

**Comment by rowenbuzz** [comment]
@olifolkerd 

I'm having the same issue after upgrading from 4.2 to 5.0 with column sorting.
For the line of code in question when I create a table...

From your documentation I followed this example previously (4.2) for the line I needed to change:

var table = new Tabulator("#example-table", {
    persistentSort:true, //Enable sort persistence
});

And for the new documentation I replaced it with the following (5.0) example:
var table = new Tabulator("#example-table", {
    persistence:{
        sort: true, //persist sort
    }
});

I was expecting this to be a 1 to 1 replacement, but it does not work.

**Comment by olifolkerd** [comment]
@davyjansen, That is the correct behaviour for a custom filter function, Tabulator can only persist built in filters as storing function literals in local storage would be dangerous

**Comment by olifolkerd** [comment]
Hey All,

I have just pushed a few fixes to the master branch to restore the persistence functionality. I will include them in todays patch release.

Cheers

Oli :)
