### ISSUE TITLE
Remote pagination with GraphQL and electron

### ISSUE THREAD

**Issue by chongma** [olifolkerd/tabulator#3496]
*Is your feature request related to a problem? Please describe.**
My needs are quite specific for remote pagination and do not seem to be supported.  The data is being called by GraphQL and my platform is electron.  With electron I need to make calls to the backend by ipc to update the data.  I also need to be able to set Authorization header on the request

**Describe the solution you'd like**
Instead of specifying an ajaxUrl (REST?) it would be good if I could make the requests manually.  If I could supply Tabulator with a subset of data, page number and a record count, and manually get access to the pagination parameters on navigation

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by chongma** [comment]
I have tried:
```javascript
var messages = {
   query:`...`,
   token:'fdfdfdfdfdf',
   id: 1
}
var table = new Tabulator("#table-placeholder", {
        layout: "fitDataFill",
        pagination: true,
        paginationMode: "remote",
        sortMode: "remote",
        ajaxURL: 'http://localhost:3001/graphql',
        ajaxConfig: {
            method: 'POST',
            headers: {
                'Content-type': 'application/json',
                'Authorization': `Bearer ${messages.token}`
            },
            body: JSON.stringify({ query: messages.query, variables: { id: messages.id } })
        },
        columns: [
            ...
        ]
    });
```
But i get a 400 from the server saying `SyntaxError: Unexpected token - in JSON at position 0`
Is there a way to see what body is being sent by Tabulator?  Also how to include the sorting and pagin parameters in my GraphQL query?

**Comment by chongma** [comment]
I console logged the config parameter just before this line:
https://github.com/olifolkerd/tabulator/blob/41e79e1eacbb285783f561899e5e8836d2e0d75d/src/js/modules/Ajax/defaults/loaderPromise.js#L62
and it looks like the body of the request has been changed to `{"page":1,"sort":[]}`
Is there any way to control the body of the POST request?

**Comment by chongma** [comment]
ok it seems to be working better with:
```javascript
        ajaxURL: 'http://localhost:3001/graphql/admin',
        ajaxContentType: "json",
        ajaxConfig: "POST", 
        ajaxContentType: {
            headers: {
                'Content-type': 'application/json',
                'Authorization': `Bearer ${messages.token}`
            },
            body: function (url, config, params) {
                return JSON.stringify({ query: messages.query, variables: { id: messages.id } })
            },
        }
```
i just need to figure out how to handle the response

**Comment by ajlive** [comment]
For anyone who arrives here by googling, like I did, the way to handle the response is with the ajaxResponse function:
http://tabulator.info/docs/5.2/data#ajax-alter

**Comment by olifolkerd** [comment]
Hey @ajlive 

Actually the better approach in version 5.x is to use the new custom module functionality to add a custom module to interface with the external data source. This will give you much more control over the request lifecycle.

Full details of this and a simplified example can be found in the [Custom Module Example Docs](http://tabulator.info/docs/5.2/module-examples#db)

Cheers

Oli :)

**Comment by ajlive** [comment]
Thanks, Oli! I'll look into it.
