### ISSUE TITLE
Empty values in columns containing a `.` in their title

### ISSUE THREAD

**Issue by NicolasFlandrois** [olifolkerd/tabulator#3497]
**Describe the bug**

**Tabulator Info**
- Which version of Tabulator are you using?

**Working Example**
YOU MUST include a link to a JS Fiddle or Codepen that demonstrates the problem, it is very hard to diagnose an issue from a simple description.

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by NicolasFlandrois** [comment]
When the tabulator is setting up a table, with a column title containing `.`, the values don't display.
Snipet:
'''
var my_Data = [{"Origin": "Uncle Sam", "Source": "xyz",
                  "Start date": "2015-02-22", "End date": "2019-06-24",
                  "No. id": 7247,
                  "Species": "ABC"},
               {"Origin": "Uncle Sam", "Source": "xyz",
                  "Start date": "2015-02-22", "End date": "2019-06-24",
                  "No. id": 7947,
                  "Species": "ABC"},
               {"Origin": "Uncle Sam", "Source": "xyz",
                   "Start date": "2015-02-22", "End date": "2019-06-24",
                   "No. id": 7297,
                   "Species": "ABC"},
               {"Origin": "Uncle Sam", "Source": "xyz",
                    "Start date": "2015-02-22", "End date": "2019-06-24",
                    "No. id": 7294,
                    "Species": "ABC"},
               ];
var table_from_data = new Tabulator('#table_from_data', {
data:my_Data,
ajaxLoader:false,
maxHeight:200,
layout:"fitDataStretch",
columns:[{'title': 'Origin', 'field': 'Origin', 'formatter': 'textarea'},
         {'title': 'Source', 'field': 'Source', 'formatter': 'textarea'},
         {'title': 'Start date', 'field': 'Start date', 'formatter': 'textarea'},
         {'title': 'End date', 'field': 'End date', 'formatter': 'textarea'},
         {'title': 'No. id', 'field': 'No. id', 'formatter': 'textarea'},
         {'title': 'Species', 'field': 'Species', 'formatter': 'textarea'}]
});
'''
The column "No. id" is then empty of any values.
The simple solution is to remove said problematic `.`
'''
var my_Data = [{"Origin": "Uncle Sam", "Source": "xyz",
                  "Start date": "2015-02-22", "End date": "2019-06-24",
                  "No id": 7247,
                  "Species": "ABC"},
               {"Origin": "Uncle Sam", "Source": "xyz",
                  "Start date": "2015-02-22", "End date": "2019-06-24",
                  "No id": 7947,
                  "Species": "ABC"},
               {"Origin": "Uncle Sam", "Source": "xyz",
                   "Start date": "2015-02-22", "End date": "2019-06-24",
                   "No id": 7297,
                   "Species": "ABC"},
               {"Origin": "Uncle Sam", "Source": "xyz",
                    "Start date": "2015-02-22", "End date": "2019-06-24",
                    "No id": 7294,
                    "Species": "ABC"},
               ];
var table_from_data = new Tabulator('#table_from_data', {
data:my_Data,
ajaxLoader:false,
maxHeight:200,
layout:"fitDataStretch",
columns:[{'title': 'Origin', 'field': 'Origin', 'formatter': 'textarea'},
         {'title': 'Source', 'field': 'Source', 'formatter': 'textarea'},
         {'title': 'Start date', 'field': 'Start date', 'formatter': 'textarea'},
         {'title': 'End date', 'field': 'End date', 'formatter': 'textarea'},
         {'title': 'No id', 'field': 'No id', 'formatter': 'textarea'},
         {'title': 'Species', 'field': 'Species', 'formatter': 'textarea'}]
});
'''
However, in some cases, our users would like to keep the `.` period in their title.

For now, I instructed my colleagues to work without period in their title.

~~~
My question is more:
- Why this behaviour? (is it a Regex rule, somewhere in the framework?)
- Is there a workaround already in place?
- Is it a bug, we may expect some fix, later on?

~~~
Thank you for any clues you (anyone) may provide.

**Comment by LilDevil** [comment]
The problem here is the dot is used to specify [nested data objects](http://tabulator.info/docs/5.0/columns#field-nesting). 

You can override this with 

`nestedFieldSeparator:"|", //change the field separator character to a pipe`

or any other character which will never appear in the titles.

**Comment by NicolasFlandrois** [comment]
Thanks
