### ISSUE TITLE
Freezing a column is quite buggy on Mac

### ISSUE THREAD

**Issue by asheerrizvi** [olifolkerd/tabulator#3500]
**Describe the bug**
Freezing a column makes it move back and forth when scrolling horizontally.

**Tabulator Info**
- Which version of Tabulator are you using?
- 5.0.7

**Working Example**
http://tabulator.info/examples/5.0?#frozen-col

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to the official example and scroll horizontally.

**Expected behavior**
The frozen columns shouldn't move back and forth

**Screenshots**
https://www.loom.com/share/99e6109a3617429ab9fac6d92149935b

**Desktop (please complete the following information):**
OS : MacOS Monterey 12.1 Beta (21C5021h)
Browser : Chrome - Darwin
Version : Version 96.0.4664.55 (Official Build) (x86_64)

**Comment by xufor** [comment]
I am facing the same issue on a Windows laptop.
OS: Windows 10
Browser: Google Chrome Version 95.0.4638.69 (Official Build) (64-bit)

**Comment by olifolkerd** [comment]
I have just pushed an update to the frozen columns system that should improve efficiency and reduce rendering issues.

I will include it in the next patch release.

Cheers

Oli :)
