### ISSUE TITLE
Issue with localization for Show Page 1, 2 etc

### ISSUE THREAD

**Issue by RonanMcCaffrey** [olifolkerd/tabulator#3501]
http://tabulator.info/examples/5.0#localization
A link to the page with the issue

Localization example shows clearly how to update column headers and most of the pagination buttons, however
The tooltip when hovering over 1 and 2, still shows "Show Page 1", and "Show Page 2" regardless of language chosen. And the documentation gives no indication of how the user can override these variables

![image](https://user-images.githubusercontent.com/4432512/145195250-02f74f67-f9f9-4b42-b2ae-4521f51452f3.png)

**Comment by bornova** [comment]
Hi @RonanMcCaffrey,
The example omits the `"page_title"` option therefore the Show Page tooltip is not localized.  However, you can set this option,[ as documented here](http://tabulator.info/docs/5.0/localize#define), and then the page titles will be localized.

https://jsfiddle.net/izmirli/vr9ksyqu/

**Comment by RonanMcCaffrey** [comment]
Brilliant, exactly what i was looking for. Thank you. It would be useful to include that in the localization table example in the future
