### ISSUE TITLE
5.0.7 large data causes "InternalEventBus.js:94 Uncaught RangeError: Maximum call stack size exceeded." Same data works in previous versions.

### ISSUE THREAD

**Issue by welford** [olifolkerd/tabulator#3502]
Noticed while updating from 4.2.7. to 5.0.7. 

https://jsfiddle.net/6gh48rqd/
https://jsfiddle.net/6gh48rqd/1/ <- 4.9.0 300k entries ok
https://jsfiddle.net/6gh48rqd/2/ <- 5.0.7 300k entries not working

5.0.7 fails to load large data sets that 4.9.0 and 4.2.7 are able to load.

In this example using a csv with ~300000 entries e.g.

```
var largeCSV = `name,number,string,path,email,phone
james,0001,"Hello world",C:\Program Files (x86)\WindowsPowerShell,bob@hotmail.com,1234567890
james,0001,"Hello world",C:\Program Files (x86)\WindowsPowerShell,bob@hotmail.com,1234567890
...
```

A smaller data set (e.g. 1k entries) on 5.0.7 works with the same setup.

InternalEventBus.js:94 Uncaught RangeError: Maximum call stack size exceeded
    at InternalEventBus.js:94
    at Array.forEach (<anonymous>)
    at e.value (InternalEventBus.js:93)
    at r.value (CoreFeature.js:86)
    at r.value (DataLoader.js:67)
    at n.value (Tabulator.js:286)
    at n.value (Tabulator.js:141)
    at Tabulator.js:57

**Tabulator Info**
5.0.7 Does Not Work
5.0.0 Does Not Work
4.9.0 Works
4.2.7 Works

**Working Example**
https://welford.github.io/tabulator/tabulator4.9.0.html
https://welford.github.io/tabulator/tabulator5.0.7.html
https://github.com/welford/welford.github.io/tree/master/tabulator

**Expected behavior**
the data should load as it has done since 4.2.7

**Desktop:**
 - OS: Windows 10
 - Edge 
 - Version 96.0.1054.53

Also tested in Opera with same results

**Comment by welford** [comment]
FWIW i've used 4.2.7 to load csv files with upward of 1,500,000  entries.

**Comment by rednaw** [comment]
I have the same issue
- On 4.9.3 I can load a table with > 400.000 rows
- On 5.0.8 I get the error below with a table of this size
```
Uncaught RangeError: Maximum call stack size exceeded
    at tabulator_esm.js:21797
    at Array.forEach (<anonymous>)
    at InternalEventBus._confirm (tabulator_esm.js:21796)
    at DataLoader.confirm (tabulator_esm.js:87)
    at DataLoader.load (tabulator_esm.js:21471)
    at TabulatorFull._loadInitialData (tabulator_esm.js:22840)
    at TabulatorFull._create (tabulator_esm.js:22694)
    at tabulator_esm.js:22610
```

When limiting the number of rows to 100.000 the error does not occur on 5.0.8

**Comment by olifolkerd** [comment]
Hey @welford 

I have pushed a fix for this to the master branch and will include it in the next patch release.

Cheers

Oli :)
