### ISSUE TITLE
Unable to send params (ajax/inline method)

### ISSUE THREAD

**Issue by hitodev** [olifolkerd/tabulator#3507]
**Describe the bug**
Unable to pass params with inline method
If params are set inside the new tabulator declaration, it works, but it doesn"t work if I try to pass params inline, as described in documentation: 

> If you wish to pass parameters when using the setData you can either include them in-line with the url string, or as an optional second parameter to the function. In the latter case they should be provided in the form of an object with key/value pairs.
[http://tabulator.info/docs/5.0/data#ajax-methods](http://tabulator.info/docs/5.0/data#ajax-method)
`table.setData("http://www.getmydata.com/now", {key1:"value1", key2:"value2"});
`

**Tabulator Info**
- 5.0.6 + 5.0.7

**Working Example**
When params are specified with new Tabulator, it works, all params are sent, GET or POST method and visible in browser console.
https://jsfiddle.net/qw4s52tz/5/](https://jsfiddle.net/qw4s52tz/5/)

The problem with inline method to pass params : params are not added to the ajax URL
**To Reproduce**
1. Go to [https://jsfiddle.net/qw4s52tz/2/](https://jsfiddle.net/qw4s52tz/2/)
2. Open console
3. No params visible

**Expected behavior**
REQUEST params should be posted

**Desktop (please complete the following information):**
 - OS: Unbuntu 
 - Browser Iron/chrome
 - Version 90.0.4600.0 (Official Build) (64-bit)

**Comment by verdonfly** [comment]
@hitodev yes it's a bug, i noticed this problem too.

**Comment by olifolkerd** [comment]
Hey all,

I have pushed a fix for this to the master branch and will include it in the next patch release.

Cheers

Oli :)
