### ISSUE TITLE
Complex filter `OR` syntax is not working

### ISSUE THREAD

**Issue by rain01** [olifolkerd/tabulator#3509]
**Describe the bug**
I am trying to use complex filters but `OR` syntax is not working.

**Tabulator Info**
- 5.0.7

**Working Example**
https://jsfiddle.net/rain01/796nsreg/2/

**To Reproduce**
1. Open JSFiddle link above

**Expected behavior**
I am expecting to see rows with "Favourite Color" `green` or `red`

**Desktop:**
 - OS: OS X
 - Browser: chrome
 - Version: 96

**Comment by LilDevil** [comment]
[Complex Filtering](http://tabulator.info/docs/5.0/filter#func-complex)

Working example:
https://jsfiddle.net/LilDevil/2vwjqos0/1/

**Comment by olifolkerd** [comment]
Hey @rain01 

You syntax is wrong there, both should objects should be in the array for it to be classed in the array:
```js
table.setFilter([[{"field":"col","type":"=","value":"green"},{"field":"col","type":"=","value":"red"}]]);
```

Your current code reads as:
col = "green" AND (col = "red" OR nothing)

Cheers

Oli :)
