### ISSUE TITLE
Extend group by to have column values in the group header

### ISSUE THREAD

**Issue by TomWhitson** [olifolkerd/tabulator#351]
Would it be feasible to make the group by extension create headers with column values? Ultimately this would mean having a function in each column which could be applied in case of a group by (in this case we could build averages/max/min, etc. and the default could be a linear sum).

At the moment we can customise the group name in the header but the header div takes up the entire table width, it would be great to be able to do calculations at the group level and display the results.

**Comment by olifolkerd** [comment]
Hi Tom,

Im not sure  i follow you, are you asking to duplicate the column headers to be below each group header?

Could you provide a sketch of what you are after, that would help a lot.

Cheers

Oli

**Comment by TomWhitson** [comment]
Hi Oli, 

What I was wondering is if we can do something like the below where we add columns at the group level header (rather than one long div with just the group title) and let them be defined by a formula.

Lets say we have data about the number and average cost of the widgets our company owns and we want to group by CCY and Location, I would like to apply a Sum formula in the Units column, an Average formula at in the Average column and take the text value at the CCY and Location level since these are used by the group.

Column Name    |    Units    |    Average Cost    |    CCY    |    Location
Group : Location    |    sum(child) = 200    |    avg(child)=1.5    |    EUR    |    Paris
Widget A    |    100    |    2    |    EUR    |    Paris
Widget B    |    100    |    1    |    EUR    |    Paris
Group : Location    |   sum(child) = 300    |    avg(child) = 2.5    |    GBP    |    Paris
Widget C    |    150    |    2    |    GBP    |    Paris
Widget D    |    150    |    3    |    GBP    |    Paris

Does that make sense? I am looking into the Group extension code see the feasibility myself but wanted to hear your thoughts.

**Comment by olifolkerd** [comment]
Hi Tom,

At present this isn't possible, although it is on the road map to add a calculations function to columns to do exactly the sort of thing you are after, unfortunately it will be a few months before i get round to that.

fundamentally it should be possible to add another extension for this, that just gets processed by the column manager when a table is built and inserts another row into the data that contains the sums.

If you come up with a solution it would be great to see.

Cheers

Oli

**Comment by Paraplegix** [comment]
I had this kind of requirement when i was using tabulator v2, and you can "paritaly manage it yourself", but its not extensible nor "good looking" method.
I also have no ready example for this but what you can do is use the `groupHeader:function(value, count, data)` function.
In the data parameter your have all the row that will be displayed inside the group, so you can do a `for(let row in data)` and do all your data calculation from there.

Pros of doing it this way : it work and its "simple"
Cons : you don't have the data aligned with column, and the header wont update on its own if data is added after (AFAIK)

Well sry i'm poping this thread back up after 12 days to give you a workaround that might not be what you want ^^

**Comment by olifolkerd** [comment]
with a bit of luck, column calculations should be coming in next months release :)

**Comment by olifolkerd** [comment]
Hey,

You will be happy to hear that Tabulator 3.2 has just been released, and with it the Column Calculations system:
```js
{title:"Cost", field:"cost", bottomCalc:"avg"} //show average cost in bottom calculation row
```

Full information can be found in the [Calculations Documentation](http://olifolkerd.github.io/tabulator/docs/3.2/#calculations)

Cheers

Oli
