### ISSUE TITLE
Incorrect Typescript type for updateRow

### ISSUE THREAD

**Issue by Darkle** [olifolkerd/tabulator#3510]
**Describe the bug**
The `updateRow` method returns a promise as described [here in the docs](http://tabulator.info/docs/5.0/update), but [the Typescript type](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/tabulator-tables/index.d.ts#L2116) has its return type as `boolean`. 

I believe it should instead return `Promise<Tabulator.RowComponent>` 

**Tabulator Info**
- tabulator version: 5.0.7

**Comment by Darkle** [comment]
Also it looks to be a similar issue for the `deleteRow` method: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/tabulator-tables/index.d.ts#L2096. It should also be a promise as per the docs.

**Comment by olifolkerd** [comment]
Hey @Darkle 

This repo is not respnsible for the maintenance of the typescript typings, if you have found an issue with them, please submit a PR to the appropriate repo.

Cheers

Oli :)
