### ISSUE TITLE
Uncaught TypeError: t.row.findCell is not a function

### ISSUE THREAD

**Issue by heliocj** [olifolkerd/tabulator#3512]
When use cellClick at the contructor, every time we click at the cell the console showing a warning with that message (Uncaught TypeError: t.row.findCell is not a function). But the function continue to execute without problem.

**Comment by olifolkerd** [comment]
Hey @heliocj 

If you think you have found a bug then please create an issue using the Bug Issue Template, it will prompt you for all the details we need as well as a JS Fiddle to demonstrate the problem.

Without knowing how your table is setup it is virtually impossible for us to the get to the bottom of what might cause the issue you describe.

Cheers

Oli :)
