### ISSUE TITLE
Failed Validation Border not Cleared when Exiting Edit

### ISSUE THREAD

**Issue by Firionus** [olifolkerd/tabulator#3515]
**Describe the bug**
When a cell fails validation during editing, a red border is displayed around it. This border does not go away when exiting the edit process with Esc. 

**Tabulator Info**
5.0.8

**Working Example**
Just try with the validation example: <http://tabulator.info/examples/5.0#validation>  
If you still want a dedicated JSFiddle, I'll happily to provide one. 

**To Reproduce**
1. Click on "Oli Bob"
2. Delete content
3. Hit Enter. Validation fails and cell border turns red. 
4. Hit Escape. Cell content is reset to the valid old value, but the red border stays. 
5. Click on "Oli Bob"
6. Remove one letter from the end
7. Hit Enter. The edit is successful and red border disappears. 

**Expected behavior**
After hitting Escape in step 4, the red border should disappear. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10
 - Browser: Chrome
 - Version: 96.0.4664.110

**Comment by olifolkerd** [comment]
Hey @Firionus 

I have just pushed a fix for this to the master branch and will include it in the next patch release.

Cheers

Oli :)
