### ISSUE TITLE
Documentation is not loaded properly

### ISSUE THREAD

**Issue by sunny-repo88** [olifolkerd/tabulator#3522]
**Website Page**
[A link to the page with the issue](http://tabulator.info/docs/5.0/data)

**Describe the issue**
code example is not loaded properly
![image](https://user-images.githubusercontent.com/30856837/147720354-697e3c18-a74b-4142-94cd-0fcfb03ea8ec.png)

**Comment by olifolkerd** [comment]
Works fine for me when i load it, Have you tried force refreshing.

Cheers

Oli :)
