### ISSUE TITLE
Uncaught ReferenceError: nav is not defined - tabEndNewRow 

### ISSUE THREAD

**Issue by cimenta** [olifolkerd/tabulator#3523]
**Describe the bug**

I want to use the function tabEndNewRow to create a new row and jump into the outer left cell but I get the following error message:

Uncaught ReferenceError: nav is not defined
    at Edit.js:91

The new row is created but the focus is not set on the wanted cell in the new row. I used tabEndNewRow in version 4.9 without any problems. 

More description is inside SO question https://stackoverflow.com/questions/70433499/tabulator-5-0-reference-error-on-tabendnewrow (I did not create that question)

**Tabulator Info**
- 5.0.8

**Working Example**
(https://jsfiddle.net/radek/Lkah397y/4/)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to a cell
2. press Tab key till you get the error
3. See error

**Comment by olifolkerd** [comment]
Hey @cimenta 

Thanks for the info, i have pushed a fix for this to the 5,1 branch and will include it in the next release.

Cheers

Oli :)
