### ISSUE TITLE
Filter not dispatched

### ISSUE THREAD

**Issue by FrantzUml** [olifolkerd/tabulator#3525]
When addinf Filter, no event is dispatched.
I think the problem is in modules/Filter/Filter.js file.

I suggest to change the addFilter method (because the trackChanges is never called) :

addFilter(field, type, value, params){
		var changed = false;
		if(!Array.isArray(field)){
			field = [{field:field, type:type, value:value, params:params}];
		}
		field.forEach((filter) => {
			filter = this.findFilter(filter);
			if(filter){
				this.filterList.push(filter);
				this.changed = true;
			}
		});
		if(changed){
			this.trackChanges();
		}
	}

**TO**

addFilter(field, type, value, params){
		**let isChanged = false;**
		if(!Array.isArray(field)){
			field = [{field:field, type:type, value:value, params:params}];
		}
		field.forEach((filter) => {
			filter = this.findFilter(filter);
			if(filter){
				this.filterList.push(filter);
				**isChanged = true;**
			}
		});
		**if(isChanged){**
			this.trackChanges();
		}
	}

**Comment by olifolkerd** [comment]
Hey @FrantzUml 

If you think you have foud a bug, please use the Bug Issue template, that will prompt you for all the information we need to help you out.

You must provide a link to a JS Fiddle or Code pen when raising a bug, without it we cannot see how your table is configured and what may be causing the issue.

Please resubmit this using the template

Cheers

Oli :)
