### ISSUE TITLE
table.clearCellEdited() crashes

### ISSUE THREAD

**Issue by matti777** [olifolkerd/tabulator#3527]
**Describe the bug**
Calling `clearCellEdited()` on a perceived table instance (from `cell.getTable()`) causes a crash.

**Tabulator Info**
- Which version of Tabulator are you using?

5.0.7

**Working Example**

https://codepen.io/matti777/pen/rNGKeJZ

**To Reproduce**

1. Wait for the table to load in Codepen
2. Click on the empty cell under column header "CLICK BELOW"
3. Observe JS Console for the crash:
```
Edit.js:121 Uncaught TypeError: Cannot read properties of undefined (reading 'edit')
    at r.value (Edit.js:121)
    at cellClickOpenClose (pen.js?key=pen.js-026467a0-142d-64a9-fd7f-512f34c4295c:11)
    at n.value (Interaction.js:299)
    at n.value (Interaction.js:233)
    at InternalEventBus.js:119
    at Array.forEach (<anonymous>)
    at e.value (InternalEventBus.js:118)
    at n.value (CoreFeature.js:78)
    at n.value (InteractionMonitor.js:206)
    at n.value (InteractionMonitor.js:112)
```

**Expected behavior**

Nothing, as nothing is being edited in the table. If some cell(s) were being edited, would expect them to stop being edited; not expecting a crash.

**Desktop (please complete the following information):**
 - OS: MacOS 12.1
 - Browser: Chrome 
 - Version:  95.0.4638.69 (Official Build) (x86_64)

**Comment by iamsubrataaich** [comment]
I also got the same issue.

**Comment by olifolkerd** [comment]
Try upgrading to 5.1 when it is release later today, i cant seem to replicate the issue in that release.

On a side note, you don't need to set your table data in the `tableBuilt` event, you can pass it directly into the `data` prop on the table constructor object.

Cheers

Oli :)
