### ISSUE TITLE
Remove zebra theme from tables

### ISSUE THREAD

**Issue by sanleong** [olifolkerd/tabulator#353]
Hi,
I'm trying to show tables without the zebra theme. I tried using tabulator_semantic-ui.css stylesheet but my tables still showing alternate row columns. What's the best way to remove this effect?

**Comment by olifolkerd** [comment]
the ***.tabulator-row-odd*** and ***tabulator-row-even*** classes are used to style odd and even rows, you can override these in the css

**Comment by sanleong** [comment]
Thank you Oli.
That certainly did it.

Regards,
Gilberto Leon

On Jun 7, 2017, at 9:39 PM, Oli Folkerd <notifications@github.com<mailto:notifications@github.com>> wrote:


the .tabulator-row-odd and tabulator-row-even classes are used to style odd and even rows, you can override these in the css
