### ISSUE TITLE
Frozen columns triggers cascades of layoutRow events

### ISSUE THREAD

**Issue by philippjfr** [olifolkerd/tabulator#3530]
With recent versions of Tabulator (i.e. >=5.0) there appears to be an undesirable cascade of events being triggered when you enable `fitData` and frozen columns. Specifically this cascade appears to occur:

1. For each column `Column.fitToData` is called
2. This calls `Column.setWidthActual`
3. This in turn dispatches a `"column-width"` event to the event bus
4. This event is picked up by all frozen columns
5. `FrozenColumn.layout` will now call `FrozenColumn.layoutRow` for each displayed row
6. This will now call getCell for every column in that row 

So in effect `FrozenColumn.layout` is pointlessly called `N_FROZEN_COLUMNS * N_COLUMNS - 1` times since I think a single call to `FrozenColumn.layout` after all columns have been fit correctly, would be sufficient.

Note I may be misdiagnosing this but I'm seeing a huge slowdown when I compare `<5.0` and `>=5.0` and when I look at the performance profiler this is where the majority of the time is spent:

<img width="1285" alt="Screen Shot 2022-01-06 at 2 35 18 PM" src="https://user-images.githubusercontent.com/1550771/148390927-377d254c-81af-42cf-a2d6-8f0c1f374c97.png">

**Comment by philippjfr** [comment]
Even without the frozen columns I'm seeing significant slowdown compared to <5.0 but that is presumably a distinct issue.

**Comment by olifolkerd** [comment]
Hey @philippjfr 

Thanks for the info. I have pushed a fix for this to the master branch and will include it in the next patch release.

Cheers

Oli :)

**Comment by philippjfr** [comment]
@olifolkerd thank you for all your work on Tabulator, it's incredibly powerful and a core component of Panel. Check it out here if you're interested: https://pyviz-dev.github.io/panel/reference/widgets/Tabulator.html

**Comment by olifolkerd** [comment]
Hey @philippjfr 

Thanks for sharing, it is always great to see what Tbualtor is being used for.

If you would like to share that link with others, could i suggest making a PR  with a link to the site to the [Tabulator Ideas Repo](https://github.com/olifolkerd/tabulator-ideas)

Cheers

Oli :)
