### ISSUE TITLE
Whole table populating with data except one column

### ISSUE THREAD

**Issue by HarrisonC** [olifolkerd/tabulator#3531]
I have data I am pulling from a CSV file and creating a JSON object from it.

The data is loaded from the JSON object and autoColumns true is set as true.

For some reason, one column named "Latest Del. Date" is not populating with data. The column is visible but none of the rows have data.

If I pull the row object and get the data from said column, it is in the row object.

I can't tell why the data for that column is not visible for any of the rows. I have other columns with dates which are populating fine.

**Comment by bornova** [comment]
Hi @HarrisonC,
Please try setting `nestedFieldSeparator: false` in your table options.

More details here: http://tabulator.info/docs/5.0/columns#field-nesting
