### ISSUE TITLE
Frozen rows Uncaught TypeError: targets.row.findCell is not a function

### ISSUE THREAD

**Issue by DimitriSebeschuk** [olifolkerd/tabulator#3532]
Version 5.0.10

1 row is frozzen:

`
//freeze first row once data has been processed into the table
table.on("dataProcessed", function(e, row){
    var firstRow = table.getRows()[0];

    if(firstRow){
        firstRow.freeze();
    }
});
`

The exception happens by mouseover event of frozen row

Uncaught TypeError: targets.row.findCell is not a function
    at InteractionManager.bindComponents (tabulator_esm.js?28e8:21446)
    at InteractionManager.track (tabulator_esm.js?28e8:21371)
bindComponents @ tabulator_esm.js?28e8:21446
track @ tabulator_esm.js?28e8:21371

The exception happens in InteractionMonitor.bindComponents() because
`let rows = this.table.rowManager.getVisibleRows(true);` in rows is missing frozen row

**Comment by olifolkerd** [comment]
Hey @DimitriSebeschuk 

Thanks for the info, i have pushed a fix for this to the master branch and will include it in todays 5.1 release.

Could i ask that you use the bug issue template next time you raise a bug, it will prompt you for all the info that we need in a clear and concise way, i found it quite hard to read your unformatted issue.

Cheers

Oli :)
