### ISSUE TITLE
Column header height recalculation loops infinitely at certain zoom levels

### ISSUE THREAD

**Issue by JLGarber** [olifolkerd/tabulator#3533]
**Description**
At specific zoom levels, the column header resize calculation enters an infinite loop, causing a blurring visual effect and making it near-impossible to activate table click events.

**Tabulator Info**
5.0.5+

**Working Example**
[Issue demonstration in 5.0.10](https://jsfiddle.net/zyha7vfe/3/)

[Expected behavior in 5.0.3](https://jsfiddle.net/zyha7vfe/4/)

**To Reproduce**
1. Open the linked Issue Demonstration
2. Set the zoom level to values under 100%. (80% and 75% reproduce on my machine.)
3. A repeated console message of `"ResizeObserver loop limit exceeded"` is printed when the loop is triggered on JSFiddle.

**Expected behavior**
Column headers should redraw themselves exactly zero or one times on a table resize.

**Environment:**
 - OS: Windows 10 Pro
 - Browser Versions: Chrome 97.0.4692.71 / Edge 97.0.1072.55

**Additional context**
This issue does not seem to be present in Firefox.

When running with `debugEventsInternal` active in Chrome/Edge, the following messages are shown in a loop while on a test page equivalent to the linked fiddles:
```
16:42:24.896 InternalEventBus.js:131 InternalEvent:table-redraw undefined
16:42:24.904 InternalEventBus.js:131 InternalEvent:render-virtual-fill
16:42:24.904 InternalEventBus.js:131 InternalEvent:scroll-horizontal 0
16:42:24.904 InternalEventBus.js:131 InternalEvent:scroll-horizontal 0
16:42:24.908 InternalEventBus.js:157 InternalEvent:table-redrawing undefined
[column information details, one per column]
16:42:24.909 InternalEventBus.js:131 InternalEvent:layout-refreshed
16:42:24.909 InternalEventBus.js:131 InternalEvent:table-redraw undefined
// etc
```

I suspect this issue was introduced in https://github.com/olifolkerd/tabulator/commit/66c834800db130b3c61145b359b8460f66083af0. It appears to be similar to but distinct from https://github.com/olifolkerd/tabulator/issues/3530.

Thanks much!

**Comment by olifolkerd** [comment]
Hey @JLGarber 

Thanks for the info, i have pushed a fix for this to the master branch and will include it in todays 5.1 release.

On a side note you don't need to set initial table data using the `setData` function, you can pass it straight into the `data` property on the table constructor object.

Cheers

Oli :)

**Comment by JLGarber** [comment]
Much appreciated!
