### ISSUE TITLE
tabulator.info lost?

### ISSUE THREAD

**Issue by CodeFreezr** [olifolkerd/tabulator#3534]
"https://tabulator.info/" vanished?

![grafik](https://user-images.githubusercontent.com/966869/148771442-3e9e40f4-4949-432f-a27a-4067cfff94b2.png)

**Comment by olifolkerd** [comment]
It was never there. Tabulator is currently only on http

**Comment by CodeFreezr** [comment]
Ok, even from a Google-Search click, Firefox replaced http to https... So I have to find how to disable this kind of "AutoFill". Do you have plans for doing https in the future?

**Comment by CodeFreezr** [comment]
Perhaps open another https request
