### ISSUE TITLE
Grouping with nested data

### ISSUE THREAD

**Issue by MChr1Ss** [olifolkerd/tabulator#3535]
Hey Oli,

thanks for your big update. It looks great! 

But I fround a missing function/bug.

**Tabulator Info**
- 5.10

**Working Example**
Tabulator 4.9.3 https://jsfiddle.net/54o76emb/1/
Tabulator 5.0.10 https://jsfiddle.net/7zu290nj/

**Expected behavior**
That the data is grouped as in the old version.

Kind regards
Christian

**Comment by olifolkerd** [comment]
Hey @MChr1Ss 

Thanks for the info, i have pushed a fix for this to the master branch and will include it in todays 5.1 release.

Cheers

Oli :)
