### ISSUE TITLE
topCalc supporting built in formatters

### ISSUE THREAD

**Issue by muffinimal** [olifolkerd/tabulator#3537]
**Is your feature request related to a problem? Please describe.**
Currently I have a colum with data formatted as money. I want the topCalc to display the result as I have formatted the column.

**Describe the solution you'd like**
topCalc and bottomCalc displaying the results exactly as I have formatted the column using the built in formatters. 
I don't expect topCalc to behave differently if I use a custom formatted column.

Other built in formatters that could be included would be time difference, star rating, progress bars and traffic lights. I really am unsure whether there are usecases for those to be implemented.

**Describe alternatives you've considered**
I know: writing a custom formatted like this would be trivial. However:
- I love the way tabulator performs. I don't want to slow down tabulator by my own unoptimized code
- From a user perspective, I expect this to happen. Tabulator does a great job in doing all kinds of wizardry and let's me focus on other things that are not table-related. If it's built in on one end of the system, I expect it to be implemented everywhere.

Another alternative would be to have the documentation reflect somewhere that the built-in formatters are not supported by topCalc/bottomCalc

**Additional context**
Thanks a lot for creating tabulator! I have been using it for one little project for a while now and absolutely love it! Great work on the product itself, but also the great documentation!

**Comment by olifolkerd** [comment]
Hey @muffinimal 

You can already do this with the `topCalcFormatter` column definition option. see the [Column Calc Docs](http://tabulator.info/docs/5.0/column-calcs#format) for full details.

Cheers

Oli :)

**Comment by muffinimal** [comment]
Thank you for taking the time to point me in the right direction. I just looked at the documentation and it is very clear and hard to miss. Sorry for taking up your time.
