### ISSUE TITLE
Dynamic submenus

### ISSUE THREAD

**Issue by saleyn** [olifolkerd/tabulator#3538]
I believe in the current implementation context menus can be dynamically created if they are assigned a function that returns a list of menu items. This works well except for sub-menus (e.g. [here](https://github.com/olifolkerd/tabulator/blob/master/src/js/modules/Menu/Menu.js#L213)), which don't contain a similar check, and expect  to be assigned a static list.  It would be very helpful to unify the functionality to allow sub-menus of context menu items to be assigned functions that would be evaluated at the time the submenu is about to open.

**Comment by olifolkerd** [comment]
Hi @saleyn 

Sub menus can be generated at the time the main menu is generated.

As there is no way to carry out any other actions on the table once the menu is opened, all information relating to sub menu state should be known at the point the main menu is opened.

For this reason i would not be looking to add your proposed functionality as it is already covered by the existing func tionality.

Thanks

Oli :)
