### ISSUE TITLE
Header filter

### ISSUE THREAD

**Issue by saleyn** [olifolkerd/tabulator#3539]
Presently when the headerFilter property of a column is set to the value `select`, the tabulator fills the dropdown for that column's header with the values from the column's data.  However, it's not possible to type the value in the filter, only to pick one from the dropdown list.

It would be helpful to have the functionality that would combine `select` and `input` together, so that the user can type or select the value.

**Comment by olifolkerd** [comment]
Hey @saleyn 

This already exists in the `autocomplete` header filter/editor

Cheers

Oli :)
