### ISSUE TITLE
Sort broken in 3.0

### ISSUE THREAD

**Issue by gandalf516** [olifolkerd/tabulator#354]
[Sort example for 3.0](http://olifolkerd.github.io/tabulator/examples/3.0/#sorters) gives error "no such method 'sort' for tabulator widget instance". 
[Same example for 2.12](http://olifolkerd.github.io/tabulator/examples/2.12/#sorters) works just fine

Tested on win 7 x64, ff 53.0.3, ie 11, chrome 58.0.3029.110 (64-bit)

Any quick workaround how to trigger the sort in 3.0? Obviously the sort arrows in column headers work just fine.

**Comment by olifolkerd** [comment]
Hey Gandlalf, 

In 3.0 the ***sort*** function was replaced with the ***setSort*** function.

```js
$("#example-table").tabulator("setSort", "age", "asc");
```

**Comment by olifolkerd** [comment]
Hey,  i must have missed that example, will tweak it now
