### ISSUE TITLE
table data validate lead to errors: row.validate() is not a function

### ISSUE THREAD

**Issue by PirlotNicolas** [olifolkerd/tabulator#3540]
**Describe the bug**
We work on a grid with following options inside a dynamics 365 environment web resources:
 - validationMode: "highlight",
 - reactiveData: true,
 - data: datatable, //assign data to table (Json object)
 - layout: "fitColumns",
 - movableColumns: false,
 - movableRows: !isDisable, // variable global : false (default)
 - groupBy: "ainos_quotelineid",
 - groupHeader: function (value, count, data, group)
			{
				var label = "";
				if (value !== null)
				{
					if (data.length > 0) label = data[0].productname;
				}
				return label + "<span style='font-weight:normal; color:black !important; margin-left:10px;'>(" + count + " item" + ((count > 1) ? "s" : "") + ")</span>";
			},
 - columnCalcs: "both",
 - groupClosedShowCalcs: true,
 - groupToggleElement: "header",
 

**Tabulator Info**
- Which version of Tabulator are you using? 
>Tabulator v5.0.7 (c) Oliver Folkerd 2021 

**Working Example**
Due to constraint in application ISV from Microsoft, I cannot give a direct link. But i can show you with a demo.

**To Reproduce**

1. Navigate to Quote(Test 333) and click on Tab "quote line items"
2. Add a new row, then fill data
3. Click on 'Save'
4. See error in developer console.
`table.validate() lead to row.validate() is not a function` 

**Expected behavior**
We expect to have the capability to validate manualy the data before saving. The idee is to validate(), if error display them in a dialog. Else save all records.

**Screenshots**
Could it be possible to make a screen sharing ? Since it's for a customer I don't want put his data in public.

**Desktop (please complete the following information):**
 - OS: Windows 10/11
 - Browser Edge and Chrome
 - Version latest

**Additional context**
We work within Microsoft Dynamics 365 web resources.

**Comment by olifolkerd** [comment]
Hey @PirlotNicolas 

You will need to make a minimal test case on JS fiddle for us to hep you with this one, it is too complicated a setup for us to understand from a few bits of config info.

You dont need to put your entire table setup with client data live, simply create a JS Fiddle or Code Pen that has the smallest table config needed to reproduce the issue including an example row or two of sample data.

Cheers

Oli :)

**Comment by PirlotNicolas** [comment]
Hey @***@***.***>

Thank you for taking time to answer me.
I will dump some record on my test case from azure devOps Tests.
Then I try to make the bug reproducible on a Code Pen or JS fiddle.

I can give you this on a 2-3 days bases because I’m full of work at the moment 😝

Best regards,

-Nicolas-
***@***.***
Nicolas PIRLOT
Analyst Developer

***@***.******@***.***>

T  : +352.621 654 839

18, rue de l’industrie |  L-8399 Windhof  |  Luxembourg
www.ainos.lu<http://www.ainos.lu>  ***@***.*** <https://www.linkedin.com/company/ainos-s.a./>  ***@***.*** <https://www.facebook.com/ainosdev>  [Résultat de recherche d'images pour "logo twitter png transparent"] <https://twitter.com/AinosDev>
P Please consider the environment before printing this eMail.

**Comment by olifolkerd** [comment]
Hey @PirlotNicolas 

I may have managed to peice togeather the issue here. i have pushed an update to the master branch and will include it in todays 5.1 release.

Have a play and let me know if it fixes your issue.

Cheers

Oli :)

**Comment by PirlotNicolas** [comment]
Hey @olifolkerd 

We have tested and most bug are fixed with new release.

Great work.

_I will create new feature/improvement request for example having possibiliby to conditionaly allow/restrict the contextual menu in group footer and general footer with calculation. For us it make no sence to have that capability ;)
And 2 small "bugs"._

Cheers,

Nicolas P.
