### ISSUE TITLE
In rowFormatter, cell.getElement() is not the "final" element?

### ISSUE THREAD

**Issue by jermerf** [olifolkerd/tabulator#3543]
Tabulator 4.9.3 working [JSFiddle](https://jsfiddle.net/ryac6m41/3/)

Tabulator 5.0.10 not working [JSFiddle](https://jsfiddle.net/bw8k9zdn/)

**Describe the bug**
We used to use the rowFormatter in 4.9 to take raw html from our database and just dump that into the cell as the innerHTML. We had to do it this way because fields are not known because this is in our report generator, and clients can do custom queries with our database to get highly varied results. 

We also have a lot, like a lot lot of stored procedures and functions from literally 20 years of usage which output html directly from the database. Not ideal, but I can't unilaterally throw it all away like I want to.

What we did was actually very simple:
```js
function rowFormatter(row) {
    for (var f of fields) {
        var c = row.getCell(f)
        c.getElement().innerHTML = c.getValue()
    }
}
```
Now when I do this I get "some" element, which is not the same element that ends up in the cell. It is identical, but not the actual element. It also makes me think the element is created twice which would be pretty inefficient.

I've looked through the docs for v5 and I can't find anything mentioning a change in the behavior of rowFormatter. If the lifecycle of tabulator is different now, is there a diagram somewhere showing the lifecycle of rows/cells/elements, and when the "final" element is available?

**Tabulator Info**
v5.0.10

**Expected behavior**
I expect cell.getElement() to give me the element in the cell?

 - OS: Windows 10
 - Browser chrome
 - Version 97

**Comment by erkum** [comment]
I can confirm #3544

**Comment by Vani8021** [comment]
Having the same issue with cell.getElement() when using rowFormatter.

**Comment by olifolkerd** [comment]
Hey All,

There was an issue with the internal intialization state of the row not being set before the row formatter was called.

I have pushed a fix for this to the master branch and will include it in todays release.

Cheers

Oli :)
