### ISSUE TITLE
editable callback is not working on custom checkbox added using formatter

### ISSUE THREAD

**Issue by gpremkumar** [olifolkerd/tabulator#3545]
**Describe the bug**

**Tabulator Info**
- v5.0.7

**Working Example**

Hi Oli,
Thanks for the wonderful product Tabulator. Please help with the below issue.

**(https://codepen.io/gpremkumar/pen/QWqRJBJ)**

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to 'Driver' column and click on the checkbox.
2. Editable property is set to false, still the checkbox is editable.

**Let me know for any concerns or details required.**

**Expected behavior**
What is expected to disable the cell click/editing in the custom html formatted cells.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome]
 - Version [e.g. 10]

**Comment by gpremkumar** [comment]
Dears,

Please for your comments on this.

**Comment by olifolkerd** [comment]
Hey @gpremkumar 

Tabulator is working as expected here.

This issue you are experiencing is because your tick box is in a formatter not an editor. the `editable` option is only applied to displaying the editor, formatters are always visible.

Cheers

Oli :)
