### ISSUE TITLE
Get CellComponent parameter at headerFilterFuncParams

### ISSUE THREAD

**Issue by MChr1Ss** [olifolkerd/tabulator#3547]
Hey Oli,

I wanted to build a custom filter function, so I used "headerFilterFunc" and "headerFilterFuncParams". The documentation ([http://tabulator.info/docs/5.0/filter#header](http://tabulator.info/docs/5.0/filter#header)) says the headerFilterFuncParams gets the cell(-parameter?), but instead it gets the same parameters as headerFilterFunc. So there is no way to get the CellComponent, RowComponent or the Tabulator object...

I wanted to build a recursive filter function. So I need the actual cell to get the row and the tabulator object to loop over the rows and use the build in functions like: row.getTreeParent(), row.getTreeChildren(), ...

A solution is to pass the tabulator object from the outsite and the field in every column as a headerFilterFuncParams like this, but it's a bit unintuitive and one can't use the columnDefaults to set a filter for the whole table.

```
{title:"ID",		field:"id",		headerFilter:"input", 	headerFilterFunc:recursiveHeaderFilter, headerFilterFuncParams:{field:"id"},},  
{title:"status", 	field:"status", 	headerFilter:"input", 	headerFilterFunc:recursiveHeaderFilter, headerFilterFuncParams:{field:"status"},},
{title:"type", 		field:"type", 		headerFilter:"input", 	headerFilterFunc:recursiveHeaderFilter, headerFilterFuncParams:{field:"type"},},
```

**Describe the solution you'd like**
It would be very helpful if the parameter was a CellComponent so that I can use the full functionality of the table without passing the table in from the outside. Like this:

```
{title:"status", 	field:"status", 	headerFilter:"input", 	headerFilterFunc:recursiveHeaderFilter, 
      headerFilterFuncParams: (headerValue, rowValue, rowData, cell) => {
        return  {field: cell.getColumn().getField(), row: cell.getRow(),  table: cell.getTable()};
      }
}
```

**So the fourth parameter could be the actual CellComponent**

Thank you very much
Christian

**Comment by olifolkerd** [comment]
Hey @MChr1Ss 

That looks like a documentation error, there is no cell to pass into that function as it is in a header filter not a cell.

The only component that might be passible into that would be the column component, is that what you are looking for?

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @MChr1Ss 

Thanks for the headsup, yes according to the docs, that should be passed into the `headerFilterParams` function to be consistent with the `headerFilter` option.

I have pushed a fix for this to the master branch and will include it in todays 5.1 release.

Cheers

Oli :)

**Comment by MChr1Ss** [comment]
Hey @olifolkerd 

Thanks for your reply, it would be very good to get a CellComponent somewhere in the FilterFunc/Params. Now it's almost impossible to get the parents of a Cell/Row.

Best regards

Christian

**Comment by olifolkerd** [comment]
Hey @MChr1Ss 

You can access the mock cell component in the `headerFilterParams` which will in turn give you access to the column the header is in.

Could you describe what it is you are trying to achieve, because the header filter has no specific cell or row, so there is nothing for you to actually access there.

If you are talking about in the actual filter function itself, data is filtered before a cell even exists for you to do anything with. As the filtering is purely a data based task, could you explain what it is about the cell that you need to access?

Cheers

Oli :)

**Comment by MChr1Ss** [comment]
Hey @olifolkerd,

you are right with the headerFilterParams, but I can't access the headerFilterParams in my headerFilterFunc (?) there is the headerFilterFuncParams.

I'm trying to build a recursive Filter:
- I want to show all rows, where the headerValue is in a parent or a child of the row.

So I thought about: 
Building a headerFilterFunc where I get the headerValue and and somehow the CellComponent (not only the rowValue).
Then I can use the build in functions (cell.getRow() and) row.getTreeParent(); and row.getTreeChildren(); to check recursive if the value is in one of the childs or the parents.

Thank you very much for your help and best regards
Christian
