### ISSUE TITLE
t.row.findCell is not a function

### ISSUE THREAD

**Issue by lukeorriss** [olifolkerd/tabulator#3548]
When clicking on a button inside the table that is intended to allow the cell to be edited and then updated. The action works properly on the first attempt. When updating the information and then clicking edit again (without reloading the page) the "t.row.findCell is not a function" error appears. 

Tabulator version: 5.00, although jsfiddle with the same issue is using Tabulator v5.0.10

Link to jsfiddle example. To recreate the issue: load the fiddle, right click on the preview window and click inspect element, go to console. Then on the preview window, click edit (should work, no errors), then click edit again and the "t.row.findCell is not a function" should appear. 

https://jsfiddle.net/b70jrcLt/16/

Expected behaviour is that the edit button should allow users to edit the cell, then when clicked again to edit another cell, should reproduce the same outcome without the error. 

 - OS: Windows 10 Business
 - Browser: Brave 
 -  Version: 1.34.80 

Also tested on Chrome, version 97.0.4692.71.

Note: This issue does not affect functionality, the outcome of clicking the edit button will still allow me to update the cell information. Although, I can't seem to get to the bottom of why this pops up. 

This could also be related to #3475 and #3512 but neither of those included a working example.

**Comment by BrianMcBrayer** [comment]
So I have run into this several times in a React app. Every time, it has been because I have not been unmounting components correctly. That's probably not what it is here, but the last five times I've had to fix it, it was my fault.

In particular, I'd be rerendering the table to a new div (or I'd have a reference to two tables on the same div).

**Comment by lukeorriss** [comment]
That makes sense... It did cross my mind that it could be as a result of trying to render a table that is already rendered... But each time I tried to update the data or use the table.redraw() option, it wouldn't work... Hence reloading the whole table being the option I went with. Did you come across a way unmount the table and then redraw it?

**Comment by BrianMcBrayer** [comment]
I used `redraw`. Are you using React or another front-end library?

**Comment by lukeorriss** [comment]
Ah, I tried `redraw` but for some reason I couldn't get it to work (definitely a problem on my end)... Just jQuery for me, nothing fancy...

**Comment by BrianMcBrayer** [comment]
I found, for me, it was because of a memory reference issue. I think I had rendered multiple tables without knowing it because they were being rendered within events, and even though the DOM nodes were not attached anymore the events were still being fired. Maybe that's related to your issue?

**Comment by olifolkerd** [comment]
Hey @lukeorriss 

This is not so much a big with tabulator, but an incorrect approach to staggering an edit of a cell.

What your code is doing is completely rebuilding a new Tabulator instance every time the button is pressed, creating more and more tables all based on the same dom element, one replacing the previous.

Im unsure what you are actually trying to achieve with that edit button, there is no need to redraw the table to edit a cell, Tabulator comes with built in [Editors](http://tabulator.info/docs/5.0/edit) that allow a user to edit the data in table.

If your intention is to edit some data outside the table and then reload the data, you should call the 'setData' function on the table passing the new data.

```js
table.setData(lData);
```

also there is no need to JSON encode your data array before passing it into Tabulator, you can simply pass the array directly to the data prop.

Cheers

Oli :)

**Comment by lukeorriss** [comment]
Hi Oli, 

Thanks for getting back to me on this issue. I implemented table.setData(); in the following way 

`if (table.initialized){
table.setData(lData)}
else {//make table}`

and it seems to have removed the issue that I was facing. 

Thanks again
