### ISSUE TITLE
CDNJS for 3.0

### ISSUE THREAD

**Issue by Leopala** [olifolkerd/tabulator#355]
Hi,

Is the CDNJS for 3.0 available?

Thanks,

Leo.

**Comment by scooterbelasco** [comment]
+1

**Comment by olifolkerd** [comment]
Hey,

Not yet, im doing a 3.0.1 release this weekend with some tweaks to the virtual DOM renderer, will submit this to CDNJS over the weekend.

Cheers

Oli

**Comment by freebeer42** [comment]
I didn't think to check for issues here before making the request in their project... I hope that didn't cause an issue

**Comment by freebeer42** [comment]
I didn't think to check for issues here before submitting to the cdnjs project:
https://github.com/cdnjs/cdnjs/pull/10472
My apologies if you still didn't want it published yet, but all current 3.x versions are available now.

**Comment by olifolkerd** [comment]
Hey,

No problem at all, yesterdays 3.1.1 fixed the issue. thanks for bringing that up with them, ur a star!

i will update the documentation today.

Cheers

Oli

**Comment by olifolkerd** [comment]
Links are now available in the documentation
