### ISSUE TITLE
Column headers and contents can get de-synced when using renderHorizontal: "virtual"

### ISSUE THREAD

**Issue by rathboma** [olifolkerd/tabulator#3551]
When using a very large (100 column) table with 'realisticish' data (from faker.js) it is fairly easy to de-sync the horizontal scrolling of columns and cells.

Also notice - the render performance in this mode is poor. This is local-side pagination with 1000 records of 100 columns.

![tabulator-desync](https://user-images.githubusercontent.com/279769/150580540-964726af-fb80-4843-a769-c7e9be0b5b90.gif)

Code to replicate (no codepen as I'm working on a patched tabulator):

https://github.com/beekeeper-studio/tabulator/tree/hozer2

To run:
```
yarn run dev # terminal 1

pythom -m SimpleHTTPServer 8000 #python 2

```
Go to http://localhost:8000/testing

**Comment by rathboma** [comment]
Easier way to replicate:
resize a column
scroll right a bunch
scroll left
![tabulator-resize-desync](https://user-images.githubusercontent.com/279769/150585847-bb661c7a-8aee-494d-8b1f-017300dd4fe6.gif)

This works on the official documentation page too, make some columns really wide and scroll a bunch
http://tabulator.info/examples/5.0

**Comment by olifolkerd** [comment]
Hey @rathboma 

Thanks for the info. There was an issue when the columns were being rerendered after the resize when they were forgetting a width initialization flag, resulting in the column width being altered when it was scrolled out of view and back in again.

I have pushed a fix for this to the master branch and will include it in todays 5.1 release.

Cheers

Oli :)

**Comment by rathboma** [comment]
Amazing work!
