### ISSUE TITLE
topCalc Avg does not ignore strings

### ISSUE THREAD

**Issue by muffinimal** [olifolkerd/tabulator#3554]
**Describe the bug**
When using the built in 'avg' for topCalc/bottomCalc the result is NaN when one of the cells contains a string.
 - according to the documentation: "The avg function calculates the average value of all numerical cells in a column."
 - sum does ignore strings (included in codepen)

**Tabulator Info**
Version 5.0.10

**Working Example**
Codepen: https://codepen.io/muffinimal/pen/xxPKbvq

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Inspect topCalc of column Age. 'avg' is used there.
2. Inspect bottomCalc to see sum in action.

**Expected behavior**
I expect Tabulator to ignore all rows that have strings in its calculation for the average. 
The total of ages in the column is '180'
There are 5 rows.
Only 4 rows have valid values.
Expected output of avg: 180/4 = 45

**Screenshots**
Should be self-explanatory.

**Desktop (please complete the following information):**
 - OS: Windows
 - Chrome
 - Version 11

**Additional context**
Doing an average with incomplete values is iffy. I expect to divide by the number of rows that have valid input. I can imagine someone else would either expect the value to be NaN or to be divided by the total number of rows. Because of this, I wouldn't mind leaving the avg-function as is. An update to the docs would be nice stating what is done with empty cells or cells that contain strings.

**Comment by muffinimal** [comment]
I just noticed that average actually divides by the number of rows, and doesn't ignore cells with no values. It would make more sense to implement an average that ignores strings in the same way.

**Comment by olifolkerd** [comment]
This is the correct behaviour of the average filter, it is an average across all rows.

If you want to have a different functionality for your average, then you can easily create a [Custom Calc Function](http://tabulator.info/docs/5.0/column-calcs#func-custom) that meets your needs.

Cheers

Oli :)

**Comment by muffinimal** [comment]
Sounds good to me. Please do consider updating the documentation that caused me to post this issue: "The avg function calculates the average value of all **numerical** cells in a column".

When avg is used & a string is present in any cell, no result is returned at all.
