### ISSUE TITLE
Header Filters not working with renderVertical: "basic"

### ISSUE THREAD

**Issue by Ferrer-Jeremy** [olifolkerd/tabulator#3555]
**Describe the bug**
Using `renderVertical: "basic"` with `headerFilter` cause the table to not be filtered anymore

**Tabulator Info**
5.0.10

**Working Example**
Working exemple based on [http://tabulator.info/examples/5.0#filter-header](http://tabulator.info/examples/5.0#filter-header) ==> [jsFiddle](https://jsfiddle.net/hey96zra/1/)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Have a table using Header Filters
2. Add `renderVertical: "basic"` to your table option
3. The filters do not work anymore
4. Remove `renderVertical: "basic"` from your table option
5. The filters work

**Expected behavior**
The filters should work

**Desktop (please complete the following information):**
 - OS: linux mint
 - Browser: firefox
 - Version: 96.0.1

**Additional context**

**Comment by olifolkerd** [comment]
Hey @Ferrer-Jeremy 

Thanks for the info. i have pushed a fix for this to the master branch and will include it in todays 5.1 release.

Cheers

Oli :)
