### ISSUE TITLE
Cell Editable function

### ISSUE THREAD

**Issue by stack-its** [olifolkerd/tabulator#356]
Still trying to get cell editable function to work ! Here's the updated method that partially works.  Your previous code didn't work at all:

```js 
$("#example-table").tabulator({
        columns:[
            {title:"Name", field:"name", cellClick:function(e, cell) {globalCellClick(e, cell);}
       ]
});
```

Function outside of tabulator:
```js
function globalCellClick(e, cell) {
    console.log('Inside cell select'); // works now, so function is being reached
    var mycell = cell.getElement();
    console.log('Cell: ' , mycell); // works
    var cellf = mycell.attr('tabulator-field');
    console.log('Selected cell field: ' + cellf); // works
    var celledit = mycell.getColumn().getDefinition().editable; // check if cell is editable
    console.log('Editable cell: ' + celledit); // **(BROKEN): mycell.getColumn() is undefined**
    var  celltxt = mycell.getValue();
    console.log('Selected cell text: ' + celltxt); // **(BROKEN): mycell.getValue() is undefined**
}
```

I can't figure out why the last two function call are broken - please help !!
Code formatting is broken, sorry about that - Github has bugs too ;)

**Comment by olifolkerd** [comment]
Hey, i fixed your code formatting, you need to use three backticks for code, one backtick is for inline code.

The issues you are having are because you are calling functions on your ***mycell*** variable which is the DOM element of the cell not the ***component***

```js
function globalCellClick(e, cell) {
    console.log('Inside cell select'); // works now, so function is being reached
    var mycell = cell.getElement();
    console.log('Cell: ' , mycell); // works
    var cellf = mycell.attr('tabulator-field');
    console.log('Selected cell field: ' + cellf); // works
    var editFunc = cell.getColumn().getDefinition().editable ;
    var celledit = typeof editFunc = "function" || editFunc(cell) ? false; // check if editable exists as a callback, if so execute the function and return the value
    console.log('Editable cell: ' + celledit); // **(BROKEN): mycell.getColumn() is undefined**
    var  celltxt = cell.getValue();
    console.log('Selected cell text: ' + celltxt); // **(BROKEN): mycell.getValue() is undefined**
}
```

**Comment by stack-its** [comment]
Ok,
Got the cellclick working, FYI - can't have two equals in celledit - I just used that as conditionals to check against & got it running.

Thanks,  Bill

**Comment by olifolkerd** [comment]
It will only return a value if you set up the ***editable*** function in the column definition array.

Please have a thorough read of the [Editing & Manipulating Data](http://olifolkerd.github.io/tabulator/docs/3.0/#manipulating-data) documentation, it will give you detailed insights into how this works.

Cheers

Oli
