### ISSUE TITLE
'tableBuilt' event, there isnt column() or setColumn() methods, correct is setColumns()

### ISSUE THREAD

**Issue by xinxilas** [olifolkerd/tabulator#3560]
**Website Page**
Saying its columns():
http://tabulator.info/docs/5.0/upgrade#initialize
Saying its setColumn():
http://tabulator.info/docs/5.0/release#initialize

**Describe the issue**
at 'tableBuilt' event, there isn't column() or setColumn() methods, correct is setColumns()

**Comment by olifolkerd** [comment]
Hey @xinxilas 

I have made the updates in the website source and will ensure they are included with the documentation update later today with the 5.1 release.

Cheers

Oli :)
