### ISSUE TITLE
On clicking cell ,Getting Uncaught TypeError: targets.row.findCell is not a function from tabulator.esm.js file

### ISSUE THREAD

**Issue by sagartalaviya91** [olifolkerd/tabulator#3561]
![image](https://user-images.githubusercontent.com/41993850/151404751-e025c919-60b4-4a9c-9ff1-cfe4c6447d1e.png)

This is what I am passing as config to tabulator
![image](https://user-images.githubusercontent.com/41993850/151406233-c056576d-0738-42e4-8dc6-5f7c1dd0838f.png)

**Comment by olifolkerd** [comment]
Hey @sagartalaviya91 

If you want to report a bug, please use the bug issue template, it will prompt you for the info w need to help you out. Im afraid screenshots of data are not helpful.

Please include a link to a JS Fiddle or code pen that demonstrate your issue.

Cheers

Oli :)
