### ISSUE TITLE
Selectable not working with tabulator_materialize.min.css

### ISSUE THREAD

**Issue by cimenta** [olifolkerd/tabulator#3562]
**Describe the bug**

I was working on my project I needed to select some rows. But it did not work. Debugging uncovered that the cause of such behaviour is tabulator_materialize.min.css. If I do not use this css every thing works fine. working jsFiddle

To replicate the issue try to select all rows one by one.

**Tabulator Info**
5.0.x

**Working Example**

(https://jsfiddle.net/radek/mq0L4gwc/7/)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Latest Firerox and Chrome

**Comment by cimenta** [comment]
@olifolkerd  not sure where and how to ask you ...

You pushed few fixes of "my bugs" to 5.1 branch but it was not released, was it. 

Thank you for pointing out how to use Tabulator better way
Radek

**Comment by olifolkerd** [comment]
@cimenta 

Im in the process of putting togeather the release now, it will come out later today

Cheers

Oli

**Comment by cimenta** [comment]
Hi Oli
it still is not working. Please check https://jsfiddle.net/radek/mq0L4gwc/11/

thank you
Radek
