### ISSUE TITLE
Tabulator Nested Tables doesn't appear in Printout

### ISSUE THREAD

**Issue by samad-kanton** [olifolkerd/tabulator#3566]
Tabulator Nested Tables doesn't appear in Printout.

**Comment by olifolkerd** [comment]
Hey @samad-kanton 

If you want to report a bug, please use the bug report issue template and provide the information asked for including a link to a JS Fiddle that demonstrates the issue.

WIthout understanding how your table is setup it is not possible to provide feed back from a one sentance message
Cheers

Oli :)
