### ISSUE TITLE
cell setValue doesn't dispatch cellEdited event when changing an empty string "" to 0.

### ISSUE THREAD

**Issue by segonzalez** [olifolkerd/tabulator#3567]
**Describe the bug**

When editing a cell with number editor and going from empty string to 0, cellEdited events don't dispatch. This works for every other change possible.

**Tabulator Info**
- Which version of Tabulator are you using?
- 5.0.10

**Working Example**
https://codepen.io/fideox1234/pen/eYeNqjK
(Changing the empty row with a value of 0 doesn't dispatch the alert event, while the other rows do)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Put an invalid value in a row (any not number should do)
2. Put 0.
3. Notice the cellEdited event doesnt dispatch
4. Any other change, even from null to 0 works.

**Expected behavior**
In the example, event cellEdited should dispatch and create a js alert. I believe it's because js treats (0 =="") as true.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Browser Firefox

**Smartphone (please complete the following information):**
None tested

**Additional context**

I've fixed this on my end by editing js/core/cell/Cell.js, on function setValueProcessData(value, mutate)
>- if(this.value != value){
>- if(this.value !== value){

but I'm not sure if this is the appropriate solution. It works for my use case.

**Comment by olifolkerd** [comment]
Hey @segonzalez 

Thanks for the headsup, i have pushed a fix for this to the master branch and will include it in this evenings 5.1 release.

Cheers

Oli :)
