### ISSUE TITLE
Filter icon in the column header

### ISSUE THREAD

**Issue by boumboum** [olifolkerd/tabulator#3568]
Is there any possibility to get a filter icon in the column header (like the sort arrow) to define some most common filtering ( starts with, contains, between etc).
headerFilter is fine but it takes a whole row even if its not needed and sometimes I would need more granular filtering possibilities (a bit like the solution provided by agGrid, or even Excel)

**Comment by harvetech** [comment]
I have a similar question.

**Comment by denisov-k** [comment]
Maybe something like slots for column headers? For injection any buttons.

**Comment by olifolkerd** [comment]
Hey @boumboum 

How would you want the header filter icon to work, do you have a mockup of the popup layout you are looking for?

I would not want to do a filter sidebar like AG grid, i personally thing that is overkill in terms of the space it takes up, and of neiche usage case. Though having said that you could easily write a [custom module](http://tabulator.info/docs/5.1/module-build) to add that functionality and i would happily accept a PR for it.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @boumboum ,

In the 4.2 release there will be a new ***popup*** functionality coming that will allow developers to add custom popups all over the table.

Given the fairly subjective nature of the range of options available for header filtering, i would not look to add this directly, but i will include an example on the popup demo that shows how to add a header filter in this way with a popup.

Cheers

Oli :)
