### ISSUE TITLE
GetPosition Child Rows

### ISSUE THREAD

**Issue by verdonfly** [olifolkerd/tabulator#3569]
**Describe the bug**
The getposition function should return the actual position of the row in the table. However, this does not happen in the Child rows

**Tabulator Info**
- 5.0 >

**Working Example**
YOU MUST include a link to a JS Fiddle or Codepen that demonstrates the problem, it is very hard to diagnose an issue from a simple description.
https://jsfiddle.net/verdonfly/j7osf8zh/3/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to Child rows
2. Click on Child Rows

**Expected behavior**
I expect the true row position to be returned, instead -1 is returned

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chome

**Comment by verdonfly** [comment]
@harbulot  thank you so much for your help. Your solution is very useful to me.
In my case I just need to give a real id to each row, so that I can remap the id when rows are moved / deleted.
In this I have a sort order when server side reprocessed the data.
However, I think that an improvement is needed, from the `row.getPosition(true)` I expect the real position of the row on the screen, even if it is children.

**Comment by olifolkerd** [comment]
Hey All,

At the moment, child rows are not counted as full members of the table and therefor dont have positions as such, This will be changing in one of the next couple of minor releases when the data tree module gets an overhaul.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
The positioning system has been overhauled for the 5.3 release and all rows position will accurately reflect their display position in the table.

As a result of this non-displayed rows (filtered data, collapsed groups, collapsed trees etc) will not have position as it would not be possible to accurately calculate its position when not processed through the display pipeline. In these cases a value of `false` will be returned from the functions.

This will be included in the 5.5 release in June.

Cheers

Oli :)
