### ISSUE TITLE
Documentation: addClass needs getElement() in v3

### ISSUE THREAD

**Issue by dpatel20** [olifolkerd/tabulator#357]
In the [CSS Classes and Theming](http://olifolkerd.github.io/tabulator/docs/#css) section, it shows examples of adding a class. With v3, this now needs the `getElement()` call in order to work - i.e:

`row.getElement().addClass("warning");`

Documentation needs an update.

**Comment by olifolkerd** [comment]
Hey,

Good Spot! this has now been resolved.

Thanks for letting me know.

Cheers

Oli

**Comment by dpatel20** [comment]
Hi Oli - you changed it under semantic ui but not under bootstrap theme.

**Comment by olifolkerd** [comment]
I should have searched further... all fixed now :)

**Comment by samansjukur** [comment]
Hi Oli,

got this error : 
TypeError: row.getElement(...).addClass is not a function

here's my code:
    rowFormatter:function(row) {
        var data = row.getData();
        if(data.field1 == "1") {
		row.getElement().addClass("approval");        
        }
    },

**Comment by olifolkerd** [comment]
Hey @samansjukur 

Which version of Tabulator are you using?

Cheers

Oli :)

**Comment by samansjukur** [comment]
the latest one, 4.2, i also tried 4.1 with the same result.

have a nice weekend
Sam

**Comment by olifolkerd** [comment]
That is because the code snippet above is referring to version 3 of Tabulator (as it says in the issue title)

Version 3 was dependent on jQuery and used jQuery elements which have an addClass function.

as of jQuery 4.0 it used DOM Nodes, where you have to use the ***classList.add*** function

```js
element.classList.add("mystyle");
```
I hope that helps,

Cheers

Oli :)

**Comment by samansjukur** [comment]
Thank's Oli,

I got it working now, my javascript knowledge is very limited (just a beginner).
Once again thank you.

**Comment by karan-chauhan** [comment]
thanks oli...it worked
