### ISSUE TITLE
Sort module documentation says it's included tabulator.js by default

### ISSUE THREAD

**Issue by smfukaya** [olifolkerd/tabulator#3570]
**Website Page**
http://tabulator.info/docs/5.1/modules#module-sort

**Describe the issue**
If you don't use Tabulator Full, if you try to issue ```table.setSort( )``` you will get ".setSort is not a function". One needs to import and register "SortModule" before using it.

**Comment by olifolkerd** [comment]
This is a documentation issue, this changed in version 5.0, it will only be available by default if you import the `TabulatorFull`

I will update the docs shortly

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @smfukaya 

The documentation for 5.0 and 5.1 has now been updated.

Cheers

Oli :)
