### ISSUE TITLE
API change documentation

### ISSUE THREAD

**Issue by mike-lischke** [olifolkerd/tabulator#3572]
Because Typescript typings must be maintained externally, it is important to learn about API changes that are done between releases. I looked at the release notes, but they don't have a summary of what changed in each new release. I also tried a diff between the 5.0 and 5.1 branches, but that gives a lot of internal code changes too, which make it very tricky to extract the public APIs changes.

So I would like to ask for better documentation of exported APIs and when they were added or removed, commonly called: a change log.

As a side question: would you consider switching to Typescript as your development language for Tabulator, which would make the separate maintenance obsolete?

Thanks!

**Comment by olifolkerd** [comment]
Hey @mike-lischke 

I would certainly be happy to include a change log in future release notes, no problem at all.

As for Typescript I intend to keep Tabulator as a pure JS project. Im not a big fan of TypeScript myself, and believe that in the long term the benefits brought by it will be integrated into the core ECMA Script spec and am happy to wait till then.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
@mike-lischke If you have any specific requirements for the changelog that would aid you in updating the typings then i would be happy to get more input from you.

Cheers

Oli :)

**Comment by mike-lischke** [comment]
This can actually be pretty simple: for each release (when you follow semantic versioning that would be for every minor + major release) you add and/or remove public functions or even classes. I'd just need which of them was removed or added. I can then look in the code to figure out the call signature to update the typings.

**Comment by olifolkerd** [comment]
In fairness @mike-lischke The release notes do already contain all this information, they outline every new function that has been added to the API with details of how to use it.

The upgrade guide also contains explicit instructions on any functions that have changed, including examples of the old approach and new approach

**Comment by mike-lischke** [comment]
Aha! Yes, you are right. This is indeed a good overview of the changes. Because of the amount of descriptions (which is actually very good!) I thought this is a more general thing about 5.1, not highlighting the changes from the previous release.

OK, then this issue can be closed. Oh wait, it's closed already 😁

**Comment by Jojoshua** [comment]
Hah just saw this. You now see what I've been going through @mike-lischke ^^. I definitely understand where you're coming from @olifolkerd. I wouldn't try to sway the project to Typescript but just know that it really doesn't have to be thought of as rigid. From looking at your documentation you are already trying to manually keep documentation regarding types in various places i.e http://tabulator.info/docs/5.3/options#columns . 

The typescript definition is basically self-documenting all this for you plus gives the added benefit of flagging an error or forgetting the API to some piece, reducing bugs. 

I would invite you to take a look at the latest definition so you can see it's just as expressive as the library is.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/053b5c9622d558bf71cb5caded8df1743ef7bdc0/types/tabulator-tables/index.d.ts
