### ISSUE TITLE
`console.log` leaking table data to console in DataTree.js

### ISSUE THREAD

**Issue by BrianMcBrayer** [olifolkerd/tabulator#3573]
**Describe the bug**
There is a `console.log` in the code that is showing up in my production app. If this is on purpose I apologize for the bug report. If it's a mistake... I do this all the time.

Code line is https://github.com/olifolkerd/tabulator/blob/c60286eeab4855f37f3797f5c6f0f7ec98abf7c0/src/js/modules/DataTree/DataTree.js#L582

On a side note, I love this library!

**Tabulator Info**
5.1.0

**Working Example**
See the following line of code:
https://github.com/olifolkerd/tabulator/blob/c60286eeab4855f37f3797f5c6f0f7ec98abf7c0/src/js/modules/DataTree/DataTree.js#L582

**To Reproduce**
Almost every time a row is updated, this method is called.

**Expected behavior**
I would expect no `console.log` output

**Additional context**
Thank you for this awesome library!

If I can, I will submit a PR for this. But I don't think I'll be able to get to it until next week at the earliest :(

**Comment by olifolkerd** [comment]
Hey @BrianMcBrayer 

Thanks for the headsup, i have pushed a fix for this to the master branch and will include it in the next patch release.

Cheers

Oli :)
