### ISSUE TITLE
Sorting Objects with toString()-Method by default

### ISSUE THREAD

**Issue by MChr1Ss** [olifolkerd/tabulator#3575]
I'm using objects als fields in Tabulator.
Then tabulator calls the toString()-Method of these objects to display and filter the data, but it is not using the toString()-Data to sort the fields.

**Describe the solution you'd like**
That tabulator uses the sorter "string" by default, when there is no match-method in the object.

[https://jsfiddle.net/o6h4j3r8/1/](https://jsfiddle.net/o6h4j3r8/1/)
(click the first col)

**Describe alternatives you've considered**
I could specify every column with:    sorter:"string"

Thank you :)

Christian

**Comment by olifolkerd** [comment]
@MChr1Ss Im afraid i dont follow you there, 

Tabulator makes its best guess for a columns sorter based on the value of the first cell in that column if it hasn't been set, if it is a number it chooses that for example.

Cheers

Oli :)

**Comment by MChr1Ss** [comment]
Hi @olifolkerd 

in this example: [https://jsfiddle.net/o6h4j3r8/1/](https://jsfiddle.net/o6h4j3r8/1/) the first column is:
` {title:"Person", 	field:"person", headerFilter:'input'},`
with the data:
`person: {name: "name1", group: "A", toString: () => {return "test1"} }`
So tabulator is displaying: "test1" and ich can filter for "te" for example, but I can't sort this column without an explicit sorter:
`      {title:"Person", 	field:"person", headerFilter:'input', sorter:'string'},`
or putting a matching method in the object:
`person: {name: "name1", group: "A", toString: () => {return "test1"}, match: () => {} }`

Without the matching method or the sorter tabulator is throwing (when clicking on the header to sort the first column):

Uncaught TypeError: i.match is not a function
    value Sort.js:299
    value Sort.js:335
    value Sort.js:328
    value RowManager.js:671
    value Module.js:64
    value Sort.js:209
    value Sort.js:199
    value Sort.js:132
    value InternalEventBus.js:119
    value InternalEventBus.js:118
    value CoreFeature.js:78
    value Column.js:299
    value Column.js:204
    r Column.js:70
    value ColumnManager.js:232
    value ColumnManager.js:219
    value ColumnManager.js:218
    value Tabulator.js:282
    value Tabulator.js:139
    i Tabulator.js:57
    setTimeout handler*i Tabulator.js:56
    c tabulator.min.js:2
    n TabulatorFull.js:6

It's just a small thing, but I thought it's maybe handy, if there is no matching function or a sorter that tabulator is sorting the data with "sorter: 'string'"


Thank you for your help and for replying so quickly :)
Christian

**Comment by olifolkerd** [comment]
Hey @MChr1Ss 

That seems like a pretty unusual edge case to me, i suggest using a custom sorter if you need to handle this. 

Cheers

Oli :)
