### ISSUE TITLE
server side download controls

### ISSUE THREAD

**Issue by mrtsrdm** [olifolkerd/tabulator#3576]
ı user Tabulator as server side for pagination, sorting and filtering. However, data on current page is being used for download options. 
Is there any thought to download data as server side rather than in Tabulator for "Download CSV", "Download XLSX" and "Download PDF" options ?

**Comment by olifolkerd** [comment]
Hey @mrtsrdm 

At that point why would it need any integration with Tabulator, you could just have a button that makes an ajax request to your server for the download.

Tabulator is a client side JS library only.

Cheers

Oli :)

**Comment by mrtsrdm** [comment]
hey @olifolkerd 
thanks for your quick response. I can put a button for downloading the data, but ı want to use capabilities of tabulator. For example, pdf creation is valuable feature. 
Also, ı think the tabulator offers extensive possibilities for server side usage, there are so many options for remote server side usage, It even offers server side use for all features except downloading. 
That's why it might be nice to manually give the data to use for the pdf
