### ISSUE TITLE
multiple selection header filter

### ISSUE THREAD

**Issue by mrtsrdm** [olifolkerd/tabulator#3577]
select type headerFilter allows just one selection. Is there any thought to enable multiple selection header filter ? 
![image](https://user-images.githubusercontent.com/65854951/152663247-28571065-eef5-48cd-95d5-f56a2fdb218c.png)
so that filtering can be done by making more than one selection.

**Comment by olifolkerd** [comment]
Hey @mrtsrdm 

This is already an option, the `select` editor used in your header filter has a `multiselect` param that will then allow for multiple options to be selected.

If you are using the filter client side then you need to make sure you are using the *in* function in the *headerFilterFunction* property, to allow it to match against multiple values.

Cheers

Oli :)

**Comment by mrtsrdm** [comment]
hey @olifolkerd 
thank you so much, ı am using filter server side, so it is okay now👍
