### ISSUE TITLE
Additional row in getRows("visible") with Column Calculations

### ISSUE THREAD

**Issue by danieleperilli** [olifolkerd/tabulator#3580]
It seems that in the latest version of Tabulator, if the Column Calculations is enabled for a column, the number returned by getRows("visible") includes the calculations row; this doesn't happen with getRows("active").

**Tabulator Info**
v5.1.0 (previous versions doesn't have this behavior)

**Working Example**
Check this code: <https://jsfiddle.net/danieleperilli/owmkxeu1/>

**Expected behavior**
getRows("visible") should not include the calculations row.

**Desktop:**
 - OS: Mac OS
 - Browser: Chrome
 - Version: 98.0.4758.80

**Comment by olifolkerd** [comment]
Hey @danieleperilli 

Thanks for the info, i have pushed a fix for this to the master branch and will include it in this weekends patch release.

Cheers

Oli :)
