### ISSUE TITLE
tabEndNewRow copies first fow instead of using provided data

### ISSUE THREAD

**Issue by cimenta** [olifolkerd/tabulator#3581]
In my code I pass to tabEndNewRow an intial empty row object. When you go to [jsFiddle](https://jsfiddle.net/radek/Lkah397y/17/) and enter something to C2 column and hit tab key then

    new row is inserted - correct
    entered value is assigned to C2 column of new row - error

if you use function for tabEndNewRow then it works as expected. Did I get it wrong?

    var cols = [
        { title: "Cell 1", field: "c1" },
        { title: "Cell 2", field: "c2", editor: "input" }
    ];
    
    var row = {"c1":"","c2":""}

    var table = new Tabulator('#table', {
        columns: cols,
        data: [row],
        height:"100%",
        tabEndNewRow: row,
   //      tabEndNewRow:function(row){
   //      return  {"c1":"1","c2":""}// return data object for new row
   //   }
    })

tabulator 5.1.0

SO https://stackoverflow.com/questions/70745341/tabendnewrow-copies-first-fow-instead-of-using-provided-data
working jsFiddle https://jsfiddle.net/radek/xe4qbL5k/5/

**Comment by olifolkerd** [comment]
Hey @cimenta 

You are using an old version of tabulator, this was fixed in the latest release.

Cheers

Oli :)

**Comment by cimenta** [comment]
Hi Oli
did you check the jsFiddle? There is a 5.1.0 used
please check
Radek

**Comment by olifolkerd** [comment]
Hey @cimenta looking at the includes it is using version 5.0.8

**Comment by cimenta** [comment]
oh, my mistake. please use the second fiddle at the bottom of this ticket. Also create more rows than just one. 

https://jsfiddle.net/radek/xe4qbL5k/5/ 

 <script src="https://cdnjs.cloudflare.com/ajax/libs/tabulator/5.1.0/js/tabulator.min.js"></script>

If you are not able replicate I will provide a video cast

**Comment by olifolkerd** [comment]
Ahh with you now, this was related to the other issue you raised about the value not being saved and will be fixed in the next patch release.

You are also passing in row data to the `tabEndNewRow` prop which will mean you will get some fields prepopulated to match that row.

Cheers

Oli :)

**Comment by cimenta** [comment]
this is related to the other issue but not the same. Maybe there is one fix to both. I do not know.

I do want the variable "row" to be inserted as a new row once "tab" is hit.

The row might include data. Not just empty "keys" as shown in this example https://jsfiddle.net/radek/xe4qbL5k/5/ 
the "new row" string is current date in my application

sorry for not being clear the first time
Radek

**Comment by olifolkerd** [comment]
@cimenta i have tried this on the master branch and it seems to be working. if you are unsure then please feel free to test the code on the master branch before i do the release later today

**Comment by cimenta** [comment]
how can I use master code in jsFiddle?

**Comment by cimenta** [comment]
let me know if you need more info 

https://youtu.be/YgnwikNxByY 

https://jsfiddle.net/radek/xe4qbL5k/34/

**Comment by olifolkerd** [comment]
try the next patch release when it comes out and let me know if you are still experiencing the issue, as far as i can tell i have resolved it.

**Comment by cimenta** [comment]
Hi Oli
I am using 5.1.2.
The expected behavior after hitting tab on cell 3 is a new row with data of variable row. Meaning cell 2 and cell 3 of the new row has NO value.

Test case 1:
1. load jsFiddle https://jsfiddle.net/radek/xe4qbL5k/43/
2. enter value 4 into cell 2 
3. enter value 5 into cell 3
4. hit tab
5. new row is inserted but it is a copy of the very first row

Test case 2:
1. change definition of tabEndNewRow, use the commented code where is NOT used variable row
2. run jsFiddle 
3. enter value 4 into cell 2 
4. enter value 5 into cell 3
5. hit tab
6. new row is inserted with values as expected

**Comment by olifolkerd** [comment]
Hey @cimenta 

This is happening because in your example you have a pass by reference issue, and not because of an issue within Tabulator.

By passing the same object into the data array and the `tableEndNewRow` they both reference the same actual object, so when that object gets updated when the row is changed, so dows the value in the `tableEndNewRow` prop. If you want to reference them from the same object you should use `Object.assign` before passing it into the prop to break the reference.

Cheers

Oli :)
