### ISSUE TITLE
tabEndNewRow deletes value of last cell

### ISSUE THREAD

**Issue by cimenta** [olifolkerd/tabulator#3582]
Tabulator version 5.1.0
jsFiddle https://jsfiddle.net/radek/xe4qbL5k/6/
SO https://stackoverflow.com/questions/71035658/tabendnewrow-deletes-value-of-last-cell

tab pressed on last cell if it is editable it DELETEs the value of last cell

**Comment by olifolkerd** [comment]
Hey @cimenta 

Thanks for the headsup,

i have pushed a fix for this to the master branch and will include it in this weekends patch release.

Cheers

Oli :)
