### ISSUE TITLE
cellTap not working on low width cells in Chromium based browsers

### ISSUE THREAD

**Issue by H3le** [olifolkerd/tabulator#3588]
**Describe the bug**
On Chromium based browsers, cellTap event is not being triggered on touch devices for columns with width ~< 40px. Gecko based browsers are responding as expected. That looks like as in Chromium based browsers something is overlaying the listener holder or the object has width/height equals to 0.

Reported behavior has been reproduced in multiple browsers with multiple touch screens wired to different comuters:
 - Firefox version 96.0.2 (64 bit)  `Tap working on small columns`
 - Chrome version 97.0.4692.99 (Official build) (64 bit) `Tap not working on small columns`
 - Edge version 44.18362.449.0 `Tap not working on small columns`
 -  Opera version 83.0.4254.19 `Tap not working on small columns`

**Tabulator Info**
- Tabulator version 5.1.0

**Working Example**
[Working example](https://jsfiddle.net/Peironem/b6shL54v/2/)

**To Reproduce**
1. Load the linked fiddle in any Gecko based browser
2. On touch monitor, tap the two X columns and look to the console: everything is working as expected
3. Now load the same page in any Chromium based browser
4. On touch monitor, tap the two X columns and look to the console: the bigger one is firing the event, the smaller one doesn't.

**Expected behavior**
On touch screens, X browser, cellTap should be called whenever a finger taps the table cell exactly as cellClick act when a click on the cell is performed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: that's the point, see the issue description
 - Version: -

**Comment by olifolkerd** [comment]
Hey @H3le 

This is happening because you have resizable columns enabled on your table. In columns that small the invisible resize handles take up most of the cells width meaning that the tap events are captured by the resize handles not the cell itself.

In this case i would recommend that you disable resizable columns.

That should fix your issue.

Cheers

Oli :)
