### ISSUE TITLE
Removal of decimals and zeroes in numbers. 

### ISSUE THREAD

**Issue by Sm00g15** [olifolkerd/tabulator#359]
![screen shot 2017-06-10 at 3 38 51 pm](https://user-images.githubusercontent.com/14209806/26999642-ef8a1100-4df2-11e7-8828-a189679e4c6e.jpg)
Anybody know of a way to get rid of the decimal point and zeroes behind it for numbers that still need a similar money formatting but don't require the last decimal and zeroes?

**Comment by olifolkerd** [comment]
Hey,

Are you looking to remove the decimals only if they are zero or do you always want to remove them, reguardless of value?

Cheers

Oli

**Comment by Sm00g15** [comment]
Hey Oli,

Only if they are zeroes. 



I’ll still need them in the price indicators, but for instance in Market Cap, 24hr Volume, and Available Supply they’re superfluous.

Thanks for the prompt response!

Best
Sean Magin

**Comment by olifolkerd** [comment]
Hey Sean,

so how would you want to handle a value of 22.10, would you want to remove just the single trailing zero?

**Comment by Sm00g15** [comment]
Nope, I’d want to keep both numbers in that case. Only want to remove both trailing numbers and the decimal point when the number is .00 . That make sense? Also, while I have your ear, do you have any good ideas/tutorials for how I could add a currency symbol in front of the price? And also make it to where I could change currency symbols?

**Comment by olifolkerd** [comment]
There is a parameter in the ***formatterParams*** object for this formatter that allows you to set the symbol:

```js
{title:"Market Cap", field:"cap", formatter:"money", formatterParams:{symbol:"£"},
```

Full details of this can be found [here](http://olifolkerd.github.io/tabulator/docs/#formatting)

When you say change symbol, do you mean change it for the column as a whole or change it on a cell by cell basis?

Cheers

Oli

**Comment by Sm00g15** [comment]
Cool, I tried that earlier and it wasn’t working for me but I’ll debug and figure out why not. I’m saying change the symbol for the whole column. For instance, I want to put in a button that will change the currency of bitcoin prices for all rows when clicked.


Sean Magin	
Farm Manager
Arrowburn Farm

**Comment by olifolkerd** [comment]
I have just committed a tweak to the money formatter to allow for precision to be set, if you download the latest version of tabulator from the repo. i have just updated the documentation on the site to show how to use this:

```js
{title:"Market Cap", field:"cap", formatter:"money", formatterParams:{symbol:"£", precision:false},
```

At the moment there is no way to update a column once it has been added (i will be adding this feature in a coming version). you would need to delete the column then immediately replace it with a new column with the updated foramtter params for the new symbol:

```js
// initial column definition (just for example)
$("#example-table").tabulator({
    columns:[
        {title:"Name", field:"name"},
        {title:"Market Cap", field:"cap", formatter:"money", formatterParams:{symbol:"£"},
    ],
});

//delete column
$("#example-table").tabulator("deleteColumn", "cap");

//insert new column with updated formatter after name column
$("#example-table").tabulator("addColumn", {title:"Market Cap", field:"cap", formatter:"money", formatterParams:{symbol:"$"}, false, "name");
```
Let me know if that helps.

Cheers

Oli

**Comment by Sm00g15** [comment]
Awesome Oli you're a legend. And yeah, the delete and update works for now, ill just setup those parameters for the onclick method on the button.

Thanks man

Sean Magin 
Farm Manager
Arrowburn Farm

**Comment by Sm00g15** [comment]
Hey Oli, 

I just tried that code out, and neither formatterParams for symbol or precision: false are working for me. Any ideas?

Sean Magin	
Farm Manager
Arrowburn Farm

**Comment by olifolkerd** [comment]
are you using the latest code from the repo?

**Comment by olifolkerd** [comment]
could you paste a copy of your table constructor

**Comment by Sm00g15** [comment]
Good call, forgot to get the latest code! 

Sean Magin 
Farm Manager
Arrowburn Farm

**Comment by Sm00g15** [comment]
Going to give that a shot in the morning and will let you know how it goes

Sean Magin 
Farm Manager
Arrowburn Farm

**Comment by Sm00g15** [comment]
Couldn’t sleep and gonna do it now lol. So I’m currently using the can, so are the CDN’s on the Tabulator documentation up to date? 

These are my current scripts: 

<link href="https://cdnjs.cloudflare.com/ajax/libs/tabulator/2.11.0/tabulator.min.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Bungee+Shade" rel="stylesheet">
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tabulator/2.11.0/tabulator.min.js"></script>



Sean Magin	
Farm Manager
Arrowburn Farm

**Comment by Sm00g15** [comment]
Also, here’s my  current code per your request: 

$("#example-table-theme").tabulator({
    height:"80%", // set height of table (optional)
    fitColumns:true,
    // responsiveLayout: true, //fit columns to width of table (optional)
       // langs:{
       //  "ch-ch":{ //Chinese language definition
       //      "columns":{
       //          "#":"#",
       //          "Symbol":"币名",
       //          "Coin":"币名",
       //          "Price":"价格",
       //          "Market Cap":"市值",
       //          "24hr Volume":"24小时交易量",
       //          "Available Supply":"现货供应",
       //      },
       //  },

    columns:[ //Define Table Columns
        {title:"#", field:"rank", sorter:"number", width:50},
        {title:"Symbol", field:"symbol", sorter:"string", width:150},
        {title:"Coin", field:"name", sorter:"string", width:150},
        {title: "Price", field:"price_usd", sorter:"number", align:"center", formatter:"money"},
        {title: "Market Cap", field:"market_cap_usd", sorter:"number", align:"center", formatter:"money"},
        {title:"24hr Volume", field:"24h_volume_usd", sorter:"number", align:"center", formatter:"money"},
        {title:"Available Supply", field:"available_supply", sorter:"date", align:"center", formatter:"money"},
    ],
});

$("#example-table-theme").tabulator({
    initialSort:[
        {title:"#", field:"rank", sorter:"number", width:50},
        {title:"Symbol", field:"symbol", sorter:"string", width:150},
        {title:"Coin", field:"name", sorter:"string", width:150},
        {title: "Price", field:"price_usd", sorter:"number", align:"center", formatter:"money"},
        {title: "Market Cap", field:"market_cap_usd", sorter:"number", align:"center", formatter:"money"},
        {title:"24hr Volume", field:"24h_volume_usd", sorter:"number", align:"center", formatter:"money", sortable:false},
        {title:"Available Supply", field:"available_supply", sorter:"number", align:"center", formatter:"money"},
    ],
});




//load sample data into the table
$("#example-table-theme").tabulator("setData", "https://api.coinmarketcap.com/v1/ticker/?limit=100");



Sean Magin	
Farm Manager
Arrowburn Farm

**Comment by olifolkerd** [comment]
Hi Sean,

There has been a major version update with a ton of new features, we are now on version 3.0! im just waiting for the CDN's to catch up which could take a week or so.

In the mean time i would suggest you download the latest version directly from github, as the latest tweak to add the precision has not been officially released you will need to use the /dist/tabulator.min.js from the master branch rather than the releases

Check out the [News Page](http://olifolkerd.github.io/tabulator/news/) for full details of all the new features in version 3.0

Cheers

Oli

**Comment by Sm00g15** [comment]
Sawweeeeeeet! Thanks for the help Oli!

Sean Magin 
Farm Manager
Arrowburn Farm

**Comment by Sm00g15** [comment]
Hey so I tried adding in the new folders to the project and executing Tabulator with local files instead of CDN’s and I’ve only broken it. Here’s my folder structure and <head>, anything you can see wrong that would be throwing it off? I installed with NPM install


Sean Magin 
Farm Manager
Arrowburn Farm

**Comment by olifolkerd** [comment]
Hey Sean,

As i said in my last post, because i have added the tweak to the money formatter for you, this isnt in an official release version, you will need to use the code directly from github. either clone the master branch or download it as a zip from github.

3.0 is a complete rebuilt of Tabulator, the entire directory structure has changed, you can now find the files you need in the ***/dist*** directory, there are also minified source files if you want.

A number of the options and functions have changed names to make things more uniform, so you may need to tweak some of your existing code.

Cheers

Oli

**Comment by Sm00g15** [comment]
Hey Oli, 

Got it all working. precision:false didn’t work but precision:null did the trick. 

Sean Magin	
Farm Manager
Arrowburn Farm

**Comment by Sm00g15** [comment]
Am having issues with rows now though. Used to display 100 rows, now it’s stopping at 2. 




Sean Magin	
Farm Manager
Arrowburn Farm

**Comment by Sm00g15** [comment]
GOT IT! 


Sean Magin	
Farm Manager
Arrowburn Farm
