### ISSUE TITLE
Combobox (autocomplete - select) : display crash when close to end of page

### ISSUE THREAD

**Issue by Bari77** [olifolkerd/tabulator#3591]
**Describe the bug**
When you display an autocomplete or select component in editable grid, if combo content is supposed to be heighter than container ans container do not have "overflow: scroll" set, the combo content will not be displayed.

**Tabulator Info**
- Which version of Tabulator are you using?
We use 4.9.3, but this bug is able too in 5.1.0.

**Working Example**
https://jsfiddle.net/1fjnqxka/

**To Reproduce**
Depending of your browser size (place item Test5 in center of browser screen), click on Test5 item, autocomplete of select column.
For autocomplete, delete contained value (this is filter).

**Expected behavior**
Display correctly datas (maybe rotate to top if bottom size is no able to display).

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome (98.0.4758.82)
 - Version: 5.1.0

**Additional context**

**Comment by doublehrajput** [comment]
Actually this is not a tabulator issue..
The output html height causing the issue i.e `cleaing the list(tabulator-edit-select-list-item) when html exceed window`. If you increase width of your js fiddle it will work normally 


![Screenshot at 2022-03-23 17-58-46](https://user-images.githubusercontent.com/16010816/159699284-2572fa8b-724a-4c62-bfd9-49224bd904fa.png)

**Comment by olifolkerd** [comment]
I have just pushed updates to the 5.2 branch that replaces the ***select*** and ***autocomplete*** editors with the new ***list*** editor, which will resolve this issue.

It will be included in the 5.2 release later this month.

Cheers

Oli :)
