### ISSUE TITLE
Interactive demo download pdf doesn't work

### ISSUE THREAD

**Issue by iuliacornea99** [olifolkerd/tabulator#3593]
http://tabulator.info/docs/5.1/download

When trying to use the interactive demo ( http://tabulator.info/docs/5.1/download), the download pdf button doesn't work. and in the console, the following error is shows: 

pdf.js:88 Uncaught TypeError: jspdf.jsPDF is not a constructor
    at n.pdf (pdf.js:88:12)
    at n.value (Download.js:65:17)
    at HTMLButtonElement.<anonymous> (download:491:32)
pdf @ pdf.js:88
value @ Download.js:65

**Comment by olifolkerd** [comment]
Hey @iuliacornea99 

Thanks for the headsup, i have just update the site to fix the issue.

Cheers

Oli :)
