### ISSUE TITLE
Placeholder text not wrapping when wider than table

### ISSUE THREAD

**Issue by Fountain-S** [olifolkerd/tabulator#3598]
**Describe the bug**
When a tabulator table is unpopulated the placeholder text is displayed, however when the placeholder text is longer than the table width the text overflows the container and a horizontal scroll is displayed.

**Tabulator Info**
Version 5.1

**Working Example**
https://jsfiddle.net/FountainS/rL9usyc4/15/

**To Reproduce**
Open JS Fiddle

**Expected behavior**
When the text is longer than the table the placeholder text wraps onto a new line so the whole message is displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/97625491/154455759-b8d7b79e-7179-4589-8734-58227b0da7f0.png)

**Desktop (please complete the following information):**
Has not been test on JSfiddle when a max-width set.

**Smartphone (please complete the following information):**
Initial realisation of the problem
 - Device: iPhone X
 - OS: iOS 15.1
 - Browser: safari
 - Version: 15.1

**Additional context**

**Comment by olifolkerd** [comment]
Hey @Fountain-S 

Thanks for reporting the issue, that definitely looks like a bug there, I will look at resolving it in the next minor release, when i also add the centring functionality requested in #2985 

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @Fountain-S 

I have just pushed this update to the master branch and will include it in this weekends patch release.

Cheers

Oli :)
