### ISSUE TITLE
Bottom column calculations overlap the contents of the table footer

### ISSUE THREAD

**Issue by APetrov1024** [olifolkerd/tabulator#3599]
**Describe the bug**
When using bottomCalc and some footer content (footerElement, pagination) calculations row overlap table footer content.
**Tabulator Info**
5.1.0

**Working Example**
https://jsfiddle.net/apetrov1024/naj2h356/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://jsfiddle.net/apetrov1024/naj2h356/
2. Run fiddle
3. Look at table footer

**Expected behavior**
Calculation row above the footer content

**Comment by markreddick** [comment]
same issue here as well

**Comment by olifolkerd** [comment]
Hey all,

I have pushed a fix for this to the master branch and will include it in this weekends release.

Cheers

Oli :)
