### ISSUE TITLE
Formatting single cell

### ISSUE THREAD

**Issue by vmontal** [olifolkerd/tabulator#36]
Is it possible formatting a single cell (i.e. background color, font size, etc) instead of the whole row?

**Comment by olifolkerd** [comment]
You can add column level formatters in the column definition array, [see the documentation for full details](http://olifolkerd.github.io/tabulator/docs/#formatting)

```js

var custom_formatter = function(value, data, cell, row, options, formatterParams){
        //value - the value of the cell
        //data - the data for the row the cell is in
        //cell - the DOM element of the cell
        //row - the DOM element of the row
        //options - the options set for this tabulator
        //formatterParams - parameters set for the column
        return "<div></div>"; // must return the html or jquery element of the html for the contents of the cell;
    }

{title:"Name", field:"name", formatter:custom_formatter }
```

If you wanted to target a specific cell in that colum you could use the ***data*** argument passed to the custom formatter to decided when to return the formatter and when to return just the value;
