### ISSUE TITLE
Does tabulator have an undo changes function?

### ISSUE THREAD

**Issue by dpatel20** [olifolkerd/tabulator#360]
Hi -

Does tabulator have any kind of undo changes option? To undo ALL changes since last save to server, I can implement a reload from server. But if I want to undo changes one-by-one (so, for example,  if user has made 5 changes but only wants to undo last 2 changes), is that possible?

**Comment by olifolkerd** [comment]
Hi,

at the moment this is not a feature, but it is a great idea! so i will add it to the development road map.

in the mean time i can show you how you can use the ***cellEdited*** callback to add this functionality yourself:

```js

var history = [];

function addHistory(cell){
    history.push({cell:cell, value:cell.getOldValue());
}

//undo one change
function undo(){
    if(history.length){
        var step = history.pop();
        
        //restore old value to cell
        step.cell.setValue(step.value);

        //remove additional history step that will be added when you change the cell value back to the old one
        history.pop();
    }
}

$("#example-table").tabulator({
    cellEdited:function(cell){
        //cell - cell component
        addHistory(cell);
    },
});
```

**Comment by dpatel20** [comment]
Great, I'll give it a go. I think I might have to extend this to also remove rows added by the user.

**Comment by olifolkerd** [comment]
Hey,

I liked your idea so much i have added it to the 3.1 release that will be coming out later today. there are now ***undo*** and ***redo*** functions available (on the 3.1 branch):

```js
$("#example-table").tabulator("undo");
```

```js
$("#example-table").tabulator("redo");
```

It tracks cell edits as well as rowAdd and rowDelete

I will also add in the ability to watch for ctrl-z + ctrl +y later on.

Cheers

Oli

**Comment by zouaiher** [comment]
Hi,

The undo works great :-)
Nevertheless, I have a question.
I use the cellEdited function to modify directly the value of a cell in my database thanks to Ajax.
I tried the Undo function, but if the value is changed in the table, it is not modified in the database.
So, is it possible to execute again the cellEdited function each time an Undo is done?
Or, is it possible to know the modified cell when an Undo is done, to be able to launch the update function on my own?

Thnak you foy your help.

**Comment by olifolkerd** [comment]
Hey @zouaiher,

At the moment the undo happens silently without triggering any of the callbacks, but i could certainly look at adding some additional callbacks that get triggered when the undo or redo functions are called.

I will add this to the roadmap for the next release, if you would like to be notified when this happens, please raise a new issue for the feature.

Thanks for the suggestion!

Oli

**Comment by zouaiher** [comment]
Thank you Oli!

Great job by the way :-)

**Comment by AndrewHutcheson** [comment]
Hi @olifolkerd, 

It looks like as of v4.9 the undo still happens silently and is not triggering the cellEdited callback. Is this correct?
