### ISSUE TITLE
Extend cellEdited event

### ISSUE THREAD

**Issue by lofcz** [olifolkerd/tabulator#3602]
Currently `cellEdited` event returns only edited `cell` but not context of the action. In our use case we need to know which action raised the event. There are three options:

- Another cell was clicked
- Confirm key was pressed (enter)
- User clicked outside the table

**Describe the solution you'd like**
Extend `cellEdited` event with second param `context`. Proposed API:

```js
table.on("cellEdited", function(cell, context) {
 // cell - cell component
 /* context - {
  reason: string // "anotherCellClicked", "confirmKeyPressed", "tableFocusLost"
  data: {} // in case of reason being "anotherCellClicked" this is set to that cell, otherwise null
 }*/
});
```

**Describe alternatives you've considered**
`context.reason` could be int / enum.

**Risks**
Proposed change is fully backwards compatible.

**Comment by olifolkerd** [comment]
Hey @lofcz 

This is a bit more complicated that that, there are a great many ways that cell can be edited, a lot of them are custom and controlled by the developers own code.

Could you explain a bit more around your usage case so i can understand why this would be necessary as i currently don't seen any benefit to this info being available.

Cheers

Oli :)

**Comment by lofcz** [comment]
Thanks Oli. 
We were able to find a workaround. Just `cellClick` being triggered on `mouseup` and `cellEditing` firing on `mousedown` is confusing so we initially thought that we would need this extra info which we are able to get from `cellEditing` event.
