### ISSUE TITLE
Editing data in nested tables works but fires a TypeError on click

### ISSUE THREAD

**Issue by H3le** [olifolkerd/tabulator#3603]
**Describe the bug**
Performing a doubleclick on any subtable cell is throwing a TypeError exception.
![immagine](https://user-images.githubusercontent.com/97023033/154647189-ff39c747-7046-4959-9e5c-70368fb05b30.png)  
In my application this exception is thrown with a single click too (same line, same column, same function) but i was't able to reproduce on a fiddle: i hope that you can consider this scenario too.
This is a non blocking exception: as far as i can see cell is being edited as normal, but exception should be handled.

**Tabulator Info**
Tabulator version: 5.1.0

**Working Example**
[JSFiddle working example](https://jsfiddle.net/Peironem/2owgptL7/49/)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Open the fiddle
2. double click on any subtable cell
3. Done! TypeError should be thrown

**Expected behavior**
No TypeError exception should be thrown

**Screenshots**
n/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 97.0 (64 bit)
 - 
**Additional context**
n/A

**Comment by olifolkerd** [comment]
Hey @H3le 

I have pushed a fix for this to the master branch and will include it in this weekends patch release.

Cheers

Oli :)
