### ISSUE TITLE
Get Filtered Data

### ISSUE THREAD

**Issue by larsvanherwijnen** [olifolkerd/tabulator#3605]
We are looking for a way of getting data that is filtered from visible and non-visible pages form a table. currently the situation is as follows:

`tabulatorData.getData(true);`
Gives all data from a table. This also gives the data that is not visible by filtering.

`tabulatorData.getData("visible");`
Gives only data that is visible in the table.

So we are looking for something like this:
`tabulatorData.getData("filtered");`

This would then give all filtered regardless if it is visible or not.

Thanks.

**Comment by olifolkerd** [comment]
Hey @larsvanherwijnen 

If you simply call `getData()` without any arguments it should do as you ask.

Cheers

Oli :)

**Comment by RoyvanEmpel** [comment]
Hey @olifolkerd,

This doesn't seem to work for me, using the `.setFilter()` command to set the filters and then running `tabulatorData.getData();` it returns all the data currently in the table. Not just the filtered data.

Greetings Roy

**Comment by larsvanherwijnen** [comment]
Hey @olifolkerd,

I am experiencing the same issues as @RoyvanEmpel mentions.

**Comment by RoyvanEmpel** [comment]
Looking through the code and searching in the documentation I found in the [Updating Data](http://tabulator.info/docs/5.1/update) section there is a `table.getData("active");` function under the `Retrieving Data` part.

This seems to work.

**Comment by thazell** [comment]
Would anyone have an example of the same when using react after filtering?
