### ISSUE TITLE
Responsive Layout: "collapse" option does not show collapsed data

### ISSUE THREAD

**Issue by crash-dive** [olifolkerd/tabulator#3606]
**Describe the bug**
The responsiveLayout: "collapse" options no longer works.

The columns are hidden, but the button to show the hidden data is not shown.

The button is rendered in the HTML but it is not shown to the user, the div that should contain the data is rendered but it is not shown to the user or populated with any data.

**Tabulator Info**
Does not work in 5.0.0 and 5.1.0

**Working Example**
You can see this in the official examples page:
On Version 4.0.0 it works fine: http://tabulator.info/examples/4.0?#responsive-layout-collapse
On Version 5.1.0 (and 5.0.0) it does not: http://tabulator.info/examples/5.1#responsive-layout-collapse

(If you would like JsFiddle examples happy to create them but I assumed the official examples would be better)

**To Reproduce**
Open the links and look at the tables, the collapse button is not there on either desktop or mobile.

**Expected behaviour**
The collapse button should be there

**Desktop (please complete the following information):**
Windows 10
Chrome: 98.0.4758.102

**Smartphone (please complete the following information):**
Pixel 4
Chrome

**Comment by olifolkerd** [comment]
Hey @crash-dive 

Thanks for the headsup, i have pushed a fix for this to the master branch and will include it in this weekends patch release.

Cheers

Oli :)
