### ISSUE TITLE
Inccorrect pagination with header filters

### ISSUE THREAD

**Issue by denisov-k** [olifolkerd/tabulator#3609]
**Describe the bug**
After changing header filters value, pages don't recount. If pages don't include relevant data, table shows empty list.

**Tabulator Info**
- Tabulator version: 5.1.2

**Working Example**
https://codepen.io/Diamant024/pen/xxPjGqR

**Screenshots**
[Page without relevant data](https://user-images.githubusercontent.com/80950305/154971347-f9e0c033-dc05-4249-8946-87e6e7ce9214.png)
[Page with relevant data](https://user-images.githubusercontent.com/80950305/154971411-7a7df049-ba0b-422a-9d11-cdbbf0ae388f.png)

**Comment by olifolkerd** [comment]
Hey @denisov-k 

Your Code Pen does not appear to be working, it should be a fully working example, not just a dump of some JS code.

Cheers

Oli :)

**Comment by denisov-k** [comment]
What if I don't have `page` param, but have `offset` (rows count)?
