### ISSUE TITLE
setHeaderFilterValue displaying value instead of label with "select" type header filter

### ISSUE THREAD

**Issue by markreddick** [olifolkerd/tabulator#3610]
**Describe the bug**
I've created a table with a "status" column. The "status" value is an integer.

I have a "select" header filter setup for that column. I have defined a setup of values array the define a "label" to be displayed for each possible value.

When I click on the header filter, it presents a list of the status labels as it should. I can set the value by selecting one of the "labels".

However, if I try setting the header filter in code using setHeaderFilterValue (grid.setHeaderFilterValue('status', 2), the header filter displays the value ("2") instead of displaying the associated label ("Enabled").

I don't see it documented that it should work this way, but it doesn't seem to make sense that this is intended.

**Tabulator Info**
Tabulator version 5.1

**Working Example**
https://jsfiddle.net/L3kyrtcz/

**To Reproduce**
1. Go to https://jsfiddle.net/L3kyrtcz/
2. Click Run
3. Look at the header filter for the status column
4. See the number "2" displayed instead of "Enabled"

**Expected behavior**
I would think setting the header filter value when using a "select" filter should result in the header filter displaying the "label" value instead of the "value" value - the same as what gets displayed if you select the filter from the SELECT dropdown manually.

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.2.1
 - Browser: Firefox
 - Version: 97.0.1

![tabulator-header-filter-but](https://user-images.githubusercontent.com/29404963/154994610-a70700b3-d90d-46be-a167-1734f0abf4bb.png)

**Comment by olifolkerd** [comment]
I have just pushed updates to the 5.2 branch that replaces the ***select*** and ***autocomplete*** editors with the new ***list*** editor, which will resolve this issue.

It will be included in the 5.2 release later this month.

Cheers

Oli :)

**Comment by timhemming-fico** [comment]
Would it be possible to backport a fix for the select header filter to 4.9.x?

**Comment by olifolkerd** [comment]
I'm afraid not, I simply don't have the time to maintain older versions as well as the main branch. And in this case the fix was part of a complete rebuild of a new editor and wouldn't work with the old select editor.

That being said it is just an editor so you could just copy of from the /src/modules/edit folder

Cheers

Oli :)
