### ISSUE TITLE
Add pageSize change event

### ISSUE THREAD

**Issue by sikor04** [olifolkerd/tabulator#3615]
*Is your feature request related to a problem? Please describe.**
I would like to do client side pagination so I need to keep track of all state that is related to the pagination. We already have sorting and page number events so pageSize is the only one left.

**Describe the solution you'd like**
Same API as `pageLoaded` event: http://tabulator.info/docs/5.1/events#page

**Describe alternatives you've considered**
I did not find any way how to listen on pageSize change.

**Comment by lukeorriss** [comment]
Hi @sikor04, I was also looking for this as a feature, and couldn't find what I was looking for. Although, I did manage to get it to work using a work around.. Take a look, hopefully it's the kind of thing that you were after. 

https://codepen.io/lukeorriss/pen/podBPZo

**Comment by doublehrajput** [comment]
or you can create `PageSizeChangeModule` as 

```
class PageSizeChangeListener extends Module {
  constructor(table) {
    super(table);
  }

  initialize() {
    table.on("pageLoaded", () => {
      this.dispatchExternal("pageSizeChange", table.getPageSize());
    });
  }

  pageSizeChange(pageSize) {}
}

PageSizeChangeListener.moduleName = "pagesizelistener";

```

A complete workaround of my solution [CodeSandbox](https://codesandbox.io/s/angry-wescoff-dxquco?file=/src/index.js)

**Comment by olifolkerd** [comment]
Hey @doublehrajput 

That is a a good use of the module system there. to add customisation.

Another option along that line would be to extend the existing pagination module and update the existing 'setPageSize' function, which would have the added benefit of only being called when the size is changed, not every time a page is loaded:

```js

import {PageModule} from 'tabulator-tables';

class PageSizeChangeEnhancer extends PageModule {
    setPageSize(size){
		if(size !== true){
			size = parseInt(size);
		}
		
		if(size > 0){
			this.size = size;
		}
		
		if(this.pageSizeSelect){
			// this.pageSizeSelect.value = size;
			this.generatePageSizeSelectList();
		}
		
		this.dispatchExternal("pageSizeChanged", size);

		this.trackChanges();
	}
}

Tabulator.registerModule([PageSizeChangeEnhancer]);
```

If either of these help, please leave the issue open as i will deffo be including this update in the next release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
I have just pushed this feature onto the 5.2 branch and will include it in the 5.2 release later this month.

Cheers

Oli :)
