### ISSUE TITLE
table.clearHistory() does not work

### ISSUE THREAD

**Issue by tayyeowleng** [olifolkerd/tabulator#3617]
Scenario: 

1) For every cell edit, the table ('cellEdited') code is called to retrieve the row data via cell.getRow().getData() and push into an array (editedRowArr), so that upon Save, I can push this array to update ALL edits in one go into the database.
2) For every Save, after triggering to database to update, I also do a table.clearHistory()
3) The issue occurs when I do an edit (e.g in this case the qtyUsed cell (from value 24 to 25)), and I do a Save (which should clear the history), and when I do an edit of another cell (of the same row), I realised that the oldValue of qtyUsed is still 24, and value is 25 (shoudn't the oldValue be refreshed with clearHistory?), and the cell.getRow().getData() is still retrieving the qtyConsumed object key (which should not be as after Save, I did not edit the qtyUsed field).

//CellEdit code

 this.table.on('cellEdited', cell => {
  
      const editedRow = cell.getRow().getData();

//insert a new object key on quantity consumed if 
  if (cell.getColumn().getField() === 'qtyUsed') {
        const qtyConsumed = cell.getValue() - cell.getOldValue();
        editedRow.qtyConsumed = qtyConsumed;
      
       console.log(editedRow);
    
      console.log(cell.getRow().getCell('qtyUsed'));

      //Push all rows with changes as an object to an array
      this.editedRowArr.push(editedRow);
    });

 //Event listener to Save button

  addHandlerSave(handler) {
    this._btnSave.addEventListener('click', () => {
      handler(this.editedRowArr); //returning the editRowArr to another .js file which contains code to be updated to database
      this.table.clearHistory(); //to clear the tabulator interaction history
    });
  }

//Console
Proxy {_cell: Cell}
[[Handler]]: Object
[[Target]]: CellComponent
_cell: Cell
column: Column$1 {table: TabulatorFull, definition: {…}, parent: ColumnManager, type: 'column', columns: Array(0), …}
component: Proxy {_cell: Cell}
element: div.tabulator-cell
height: 41
initialValue: 24
loaded: true
minWidth: null
modules: {validate: {…}, edit: {…}}
oldValue: 24
row: Row {table: TabulatorFull, parent: RowManager, data: {…}, type: 'row', element: div.tabulator-row.tabulator-selectable.tabulator-row-odd.tabulator-selected, …}
table: TabulatorFull {options: {…}, columnManager: ColumnManager, rowManager: RowManager, footerManager: FooterManager, vdomHoz: null, …}
value: 25
width: 170

**Comment by olifolkerd** [comment]
Hey @tayyeowleng 

This is a misunderstanding in the "history" part of the function.

In this case this is referring to the history stored in the [History Module}(http://tabulator.info/docs/5.1/history) which is used for undo/redo actions, It has nothing to do with the data used by the [Edit Module](http://tabulator.info/docs/5.1/edit) which is completely separate.

Cheers

Oli :)
