### ISSUE TITLE
Select Row during selectAll triggering rowSelected Event

### ISSUE THREAD

**Issue by KrisnaPrashatt** [olifolkerd/tabulator#3618]
**Describe the bug**
This issue rises during the selectAll checkbox selection. When the "Select All" checkbox for the table is selected, the "_selectRow" function triggers the "rowSelected" function without checking for the silent flag. However this was not the case in version 4.9. Is it possible to call the rowSelected function by passing the "silent" flag or is it possible to avoid triggering "rowSelected" function in the case of selectAll checkbox selection?

**Tabulator Info**
- Which version of Tabulator are you using?
v5.1.2

**Expected behavior**
There should be a way to obtain the silent flag's value in rowSelected eventListener or else the rowSelected event should not be triggered for selectAll case.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome 
 - Version [e.g. 22] 75.0.3770.80

**Smartphone (please complete the following information):**

**Comment by olifolkerd** [comment]
Hey @KrisnaPrashatt 

This is now the correct behaviour as of version 5. The general feedback from the community is that they would prefer to know when each row changes  selection state, so the function gets called with each one, so any action needed for that can be triggered. then the `rowSelectionChanged` event is fired once when all the rows have been changed.

This was documented in the [Release Notes](http://tabulator.info/docs/5.0/release) for the 5.0.9 patch release.

Cheers

Oli :)
