### ISSUE TITLE
No footer (Pagination) since latest update.

### ISSUE THREAD

**Issue by larsvanherwijnen** [olifolkerd/tabulator#3619]
Hi,

Since updating from 5.0.10 to 5.1.2 the footer (Pagination) options no longer seems to work.

![image](https://user-images.githubusercontent.com/77294984/155693833-b191b425-0451-4920-86cd-0d3a98463265.png)

Previously we enabled the footer (Pagination) with:
```javascript 
tabulatorData = new Tabulator(".tabular-data", {
  pagination: true,
  paginationSize: 20,
  paginationSizeSelector: [10, 20, 40, 100],
  footerElement:"#table-pagination",
  layout: "fitDataStretch",
  responsiveLayoutCollapseUseFormatters:false,
  columns:[
  ],
  initialSort:[
  ],
});
```

I know i should be making a fiddle, but since there is no console error or warning i find this unnecessary.

Destop:
OS: MacOS, Linux, WIndows Tested.
Brower: Chrome, Firefox, Safari Tested
Version: latest versions.

Smartphone:
No way of testing (Localhost)

Thanks,

**Comment by RoyvEmpel** [comment]
No, you are stupid @larsvanherwijnen
