### ISSUE TITLE
moduleInitOrder negative values

### ISSUE THREAD

**Issue by s-cork** [olifolkerd/tabulator#3622]
**Is your feature request related to a problem? Please describe.**
I noticed there was a moduleInitOrder that could be added to a module class.
I have a use case where I'd like to force my module's chained events to be called last rather than first.

**Describe the solution you'd like**
Support moduleInitOrder being negative which would append the modules after the list of unordered modules.
The more negative the later in the list.

**Alternatives**
Not sure.

**Additional context**
I'm currently relying on module precedence working based on the order I call registerModules.
This works but only because javascript object keys (which are strings) maintain insertion order.
But relying on that feels like i'm relying on an implementation detail.

_(I'm happy to write this PR - just let me know)_

**Comment by olifolkerd** [comment]
Hey @s-cork 

Could you explain a little more about your usage case?

When you say you want your chained events to be last, you don't need the module to be initialized last for that to happen, you can pass a value into the third argument of the subscribe function, which is the priority of the subscription, the higher the value the later down the chain it will be, by default subscribers have a value of 10,000

Having checked the docs I can see i missed of that little nugget of information so i will update the docs with the next release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
I have pushed an update to the 5.2 branch which alters the functionality of the `moduleInitOrder` option, setting this value to negative will load it before the default modules, setting it to a positive value greater than 0 will load the module after.

I will include it in the 5.2 release later this month.

Cheers

Oli :)

**Comment by s-cork** [comment]
perfect thanks for both of those!
