### ISSUE TITLE
footerEelement destroys paginationElement

### ISSUE THREAD

**Issue by qbroker** [olifolkerd/tabulator#3623]
In v5.1.10 adding a custom footerElement like <button>Add record</button> would render in the footer on the left and the pagination buttons on the right.

In v5.1.1 and v5.1.2 using the footerElement destroys the pagination buttons and only the footerElement is visible on the left in the footer.

I would expect same behavior as in v5.1.10, see screenshots and code in attached pdf, [tabulator.pdf](https://github.com/olifolkerd/tabulator/files/8148540/tabulator.pdf)

 - OS: Linux Mint
 - nw.js 61.0 and TWc framework

Have a nice day, Okido

**Comment by olifolkerd** [comment]
Hey @qbroker 

Please include a link to a JS Fiddle that demonstrates the issue, PDF's and screenshots are not helpful as we cant copy code from them to replicate issues.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @qbroker 

Thanks for the info, i have pushed a fix for this to the master branch and will include it in the next patch release.

Cheers

Oli :)

**Comment by nquirynen** [comment]
This seems to be broken again in v5.3.1 in case of using a dom element.
See: https://jsfiddle.net/L501ot7n/1/

**Comment by olifolkerd** [comment]
@nquirynen  if you believe you have found a bug please create a new issue rather than commending on a issue closed 6 months ago.

We cant the track progress against the symptoms you report rather than confusing things with an old issue

**Comment by nquirynen** [comment]
Thanks for the reply, I made issue #3900
