### ISSUE TITLE
row count is wrong when grid has no data

### ISSUE THREAD

**Issue by BernhardBaumrock** [olifolkerd/tabulator#3624]
Hi Oli,
that's really a small thing but I wanted to report it nonetheless:

![image](https://user-images.githubusercontent.com/8488586/155890728-0ed41404-ee44-4632-9ce3-bdfef1a16053.png)

I think it would be best to hide the row information completely in case of "no data". Or show "0 rows" but showing 1 to 0 is definitely wrong :)

**Tabulator Info**
5.1.2

**Comment by olifolkerd** [comment]
Hey @BernhardBaumrock 

Thanks for the headsup, i have pushed a fix for this to the master branch and will include it in this weekends patch release.

Cheers

Oli :)
