### ISSUE TITLE
bottomCalc breaks pagination

### ISSUE THREAD

**Issue by BernhardBaumrock** [olifolkerd/tabulator#3625]
As soon as I add bottomCalc to my money formatted column the pagination does not show page numbers any more (1, 2, 3...)

**Tabulator Info**
5.1.3

**Working Example**
https://jsfiddle.net/baumrock/sehpdrfg/13/

Without bottomCalc:
![image](https://user-images.githubusercontent.com/8488586/155891739-ce69e76b-60d4-4600-bc18-a451c7d1ab9a.png)

With bottomCalc:
![image](https://user-images.githubusercontent.com/8488586/155891751-f2236fc6-e2d4-44c4-89ea-fb8e33655638.png)

**Comment by olifolkerd** [comment]
Hey @BernhardBaumrock 

Thanks for the headsup, i have pushed a fix for this to the master branch and will include it in this weekends patch release.

Cheers

Oli :)
