### ISSUE TITLE
Missing ajaxLoaderError option?

### ISSUE THREAD

**Issue by rathboma** [olifolkerd/tabulator#3626]
In 4.x one could provide an `ajaxLoaderError`, either a string or a node, to be rendered on an error.

Looks like in 5.x this is no longer present? Is this intentional, or can this be added back in?

**Comment by rathboma** [comment]
Ah, I found it in the upgrade guide - `dataLoaderError`.

**Comment by olifolkerd** [comment]
It changed to dataLoaderError in 5.0 because it is no longer just for ajax but for any async data loading.

Checkout the upgrade guide for full details

Cheers

Oli
