### ISSUE TITLE
move bottom row fail

### ISSUE THREAD

**Issue by andreylisovskiy** [olifolkerd/tabulator#3628]
On a table with movable rows enabled, I experience no issues moving rows except for the bottom one.. When I try to drop a higher position row and drag it to the very bottom, it triggers .endMove() method/function before I release the mouse button and fails with these:
![image](https://user-images.githubusercontent.com/21151899/156030627-622109d8-a1fe-44f9-b3ab-9355dbfa3fb5.png)

Same issue when trying to move the most bottom row to higher position: it calls .endMove() method/function right after you start moving but still hold mouse button...

Here is how I define my table div:
<div id="table_2" style="height: inherit; border: none;" class="noselect"></div>

And here is my main Tabulator config definitions:
![image](https://user-images.githubusercontent.com/21151899/156031535-005d68e2-819d-437f-921b-f1d9b28b9258.png)

**Comment by olifolkerd** [comment]
Please link to a JS fiddle that demonstrates the issue. Without seeing how your table is configured it is very hard to get to the root cause of the issue.

**Comment by andreylisovskiy** [comment]
Sorry, I have a really hard time creating a fiddle that would have Tabulator library imported. I keep getting weird issues. Do you happen to have bare skeleton/template  fiddle I could copy/modify to add my code to it?

**Comment by olifolkerd** [comment]
Look at any other bug issue. Pretty much every single one of them has a fiddle.

Cheers

Oli

**Comment by andreylisovskiy** [comment]
I was able to recreate half of the situation in this Fiddle:
[<script async src="//jsfiddle.net/andreylisovskiy/fmtpaq0v/1/embed/js,html,css,result/dark/"></script>](url)
`<script async src="//jsfiddle.net/andreylisovskiy/fmtpaq0v/1/embed/js,html,css,result/dark/"></script>`

**Comment by andreylisovskiy** [comment]
I was able to re-create half of the problem with this Fiddle:
https://jsfiddle.net/andreylisovskiy/hka762fe/1/

Try dragging/moving any higher row to the very bottom.

**Comment by olifolkerd** [comment]
Hey @andreylisovskiy 

The issue in that Fiddle is that you have the height property of the table set to `fitDataFill` which is not a valid value, if you don't want a height on your table, don't declare this property. if you do want a height then make sure you use a number or a percentage.

Cheers

Oli :)

**Comment by andreylisovskiy** [comment]
Thanks a lot @olifolkerd ! You really helped me resolve my issues. Once I played with holding <div> height and layout properties of Tabulator, I was  able to make it all work.


- God Bless you!
