### ISSUE TITLE
Does not appear right aligned when printing Tabulator 5.1

### ISSUE THREAD

**Issue by zenderp2010** [olifolkerd/tabulator#3629]
https://stackoverflow.com/questions/71299704/does-not-appear-right-aligned-when-printing-tabulator-5-1

**Comment by olifolkerd** [comment]
Hey @zenderp2010 

If you wish to report a bug please create an issue using the [Bug Reporting Template](https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Possible+Bug&template=bug_report.md&title=) providing all the requested info and a JS Fiddle that demonstrates the problem.

Cheers

Oli :)

**Comment by zenderp2010** [comment]
Thanks
