### ISSUE TITLE
cellEditCancelled

### ISSUE THREAD

**Issue by saurabhgogia** [olifolkerd/tabulator#363]
I'm unable to get a callback when a cell edit is cancelled. cellEdited (call back when the cell is edited) works fine however. Any ideas? Just a bug? Here's a snippet of my code:
```javascript
cellEdited:function(cell){ //cell - cell component
        cellValidate(cell); //validates individual cell
    },
    cellEditCancelled:function(cell){
       //cell - cell component
       alert('cancelled');
       genomeValidate();
   },
```

**Comment by olifolkerd** [comment]
could you post your full tabulator constructor. not all types of editor call the cancelled callback.

Cheers

Oli

**Comment by saurabhgogia** [comment]
Sure. Thanks Oli.
```javascript
$('#catalog3').tabulator({
  //fitColumns:true,
  columns:[
        {rowHandle:true, formatter:"handle", headerSort:false, frozen:true, width:30, minWidth:30},
        {title:"Phenotype", field:"Phenotype", sorter:"string", editor: "string", editor:"input"},
        {title:"IC_Disease", field:"IC_Disease", sorter:"string",  editor:"input"},
        {title:"IC_Cohort", field:"IC_Cohort", sorter:"string",  editor:"input"},
        {title:"Analysis_status", field:"Analysis_status", sorter:"string",  editor:dropdownEditor},
        {title:"Analyst", field:"Analyst", sorter:"string",  editor:"input"},
        {title:"Analysis_Model", field:"Analysis_Model", sorter:"string",  editor:"input"},
        {title:"n_CMG_kindreds", field:"n_CMG_kindreds", sorter:"string",  editor:"input"},
        {title:"Gene_name", field:"Gene_name", sorter:"string",  editor:"input"},
    ],
    cellEdited:function(cell){ //cell - cell component
        cellValidate(cell); //validates individual cell
        document.getElementById('catalog3').style.backgroundColor = "lightblue";

    },
    cellEditCanceled:function(cell){
       //cell - cell component
       alert('cancelled');
       genomeValidate();
   },
   responsiveLayout:true,
   selectable:true,
   pagination:"local",
   paginationSize: 7,
   placeholder:"No Data Available", //display on empty table
   movableRows:true, //enables user to move rows up and down using handle
   movableColumns: true, //enables user to move columsn left and right
   tooltips:true, //hover over tooltip
});
```

**Comment by olifolkerd** [comment]
At the moment the input editor does not trigger a ***cellEditCanceled*** event, only star, progress and tick formatters do.

The input editor treats a blur like a submit and changes the value.

Are you saying you would like to treat an input editor blur event when the value hasn't changed as a cancel? i could certainly add that functionality as it makes sense.

Do you have a specific usage case in mind so i can understand what you are looking for.

Cheers

Oli

**Comment by saurabhgogia** [comment]
Yes, when the value doesn't change I would like it to call back cellEditCanceled. This is because I have a method that validates each cell according to what column it is in. But I need to tell it when to call validate.

**Comment by olifolkerd** [comment]
no problem, i will look at adding that functionality in for you this weekend.

**Comment by saurabhgogia** [comment]
thanks. appreciate it.

**Comment by olifolkerd** [comment]
Hey,

i have just committed this to the 3.1 branch, it should be released this weekend.

Cheers

Oli

**Comment by saurabhgogia** [comment]
Thanks for the quick turnaround time!

**Comment by olifolkerd** [comment]
You are most welcome,

let me know if you can think of any other tweaks.

Cheers

Oli

**Comment by sklickovic** [comment]
Hello, 
I know that this issue is already closed long time ago, but I have the same problem now, and I am not sure why this is happening. Here are two snippets of code. The first one works without problems, but the second one does not and it is 
almost exactly the same, except "validator" function. In the second part, that function checks only for numbers in some form. 

What I really want to do is to select entire row after clicking on cell, and if value in cell is changed or not to deselect it after clicking somewhere else. But in the second snippet of code it doesn't work properly. The "cellEditCancelled" function is not called when it could be, just sometimes, and I can't understand why sometimes it works and sometimes it doesn't. What am I doing wrong?

**First snippet of code:**
{title:"#title", field:"#field", width:420, editable: true, editor:"input", topCalc: customCalc2,
                validator: [{
                    type:customVal,
                    parameters: {
                        max:50
                    }
                }, "regex:^[A-Z][a-z,0-9]+( [A-Z]?[a-z,0-9]+)*$"],
                cellEdited:function(cell) {
                    //cell - the cell component
                    changeValueInCell(cell);
                    modifyDataStore(cell);
                    table1.deselectRow();
                },
                cellEditing:function(cell) {
                    table1.selectRow(cell.getRow().getCell("id").getValue());
                },
                cellEditCancelled:function(cell) {
                    table1.deselectRow();
                }
            },

**Second snippet of code:**
{title:"#title", field:"#field", width:420, editable: true, editor:"input", topCalc: customCalc3,
                validator:[
                    "required",
                    "regex:^(?<!\\+)^(?<!-)((0\\.[1-9]$)|([1-9]\\.[1-9]$)|([1-9][0-9]\\.[1-9]$)|([1-9]$)|([1-9][0-9]$))"
                ],
                cellEdited:function(cell) {
                    //cell - the cell component
                    modifyDataStore(cell);
                    table1.deselectRow();
                },
                cellEditing:function(cell) {
                    table1.selectRow(cell.getRow().getCell("id").getValue());
                },
                cellEditCancelled:function(cell){
                    table1.deselectRow();
                }
            },
