### ISSUE TITLE
GroupContextMenu not working after v5.1.0

### ISSUE THREAD

**Issue by proautodinc** [olifolkerd/tabulator#3632]
Describe the bug
Right click to show GroupContextMenu is not working after version 5.1.0
Tabulator Info

version 5.1.3
Working Example
https://jsfiddle.net/naexjwo3/3/

To Reproduce

Open fiddle above
Click on Run
Right click on the grouped table
Expected behavior
Context menu should be showing options FIRST and SECOND

Change CSS and JS to @5.1.0 instead of @5.1.3 and it will work again

Desktop:

OS: Windows
Browser: reproduced in Chrome, Opera and Brave
Versions 98, 83 and 1.35

**Comment by olifolkerd** [comment]
Hey @proautodinc 

Thanks for the headsup, i have just pushed a fix for this to master and will include it in this weekends patch release.

Cheers

Oli :)
