### ISSUE TITLE
Does not appear right/center aligned when printing Tabulator 5.1

### ISSUE THREAD

**Issue by zenderp2010** [olifolkerd/tabulator#3633]
Hi Oli Folkerd,
I am using Tabulator version 5.1 and trying to print a table using print function. Alignment of numbers/text which is set to right or center does not appear right/center aligned when printing. When printing all the cells are aligned to left. Please help me. Thanks.

working fiddle example here:

https://jsfiddle.net/zenderp/4Lj9teh2/14/

**Comment by olifolkerd** [comment]
Hey @zenderp2010 

Thanks for the headsup, I have pushed a fix for this to the master branch and will include it in this weekends patch release.

Cheers

Oli :)

**Comment by zenderp2010** [comment]
Hi Oli,

Thank you for your quick consideration and fixed(https://stackoverflow.com/questions/71299704/does-not-appear-right-aligned-when-printing-tabulator-5-1). So kind of you Oli.......Thank you so much for your fixed.
