### ISSUE TITLE
Can't reach the column sort arrows with the TAB key

### ISSUE THREAD

**Issue by paulrosen** [olifolkerd/tabulator#3636]
**Describe the bug**
Users who don't have pointing devices can't sort columns

**Tabulator Info**
version 5.1.3

**Working Example**

http://www.tabulator.info/examples/5.1

**To Reproduce**
press the TAB key repeatedly on this page. You will notice that link for "Documentation" is focused, then press the TAB key one more time. The first cell is focused and gets a cursor. The sort and resize buttons are skipped.

**Expected behavior**
Each element on the page that can be interacted with a mouse MUST also have a way to allow users without a mouse to get that functionality. It won't pass WCAG testing otherwise and I wouldn't be allowed to use it.

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
N/A

**Additional context**
I looked at the generated code and I see the code pasted below. The outer `div` should be a `button` and the `tabulator-col-resize-handle` element needs to allow keyboard control. 
```
<div class="tabulator-col tabulator-sortable" role="columnheader" aria-sort="none" tabulator-field="name" style="min-width: 40px; height: 36px; width: 150px;" title="">
  <div class="tabulator-col-content">
    <div class="tabulator-col-title-holder">
      <div class="tabulator-col-title">Name</div>
      <div class="tabulator-col-sorter">
        <div class="tabulator-arrow"></div>
      </div>
    </div>
  </div>
  <div class="tabulator-col-resize-handle"></div>
  <div class="tabulator-col-resize-handle prev"></div>
</div>
```

**Comment by olifolkerd** [comment]
Hey @paulrosen 

Thanks for getting in touch.

There are many areas of mouse interaction with the table that can't be focused and allowing tabbing through them would provide an unusual and unexpected experience. For example the row click event (rows shouldn't hold focus) the column resize handles, the row resize handles, the list grows to be very large when you consider all of Tabulators modules and I think the vast majority of usage cases for these people would find it inconsistent and counter intuitive when filling in a form that they must first tab through all the header elements.

The sort arrows (and the other elements outlined above) are intentionally divs and not button elements. Tabulator is built of divs for a very important reason. Elements like buttons and tables have a strongly opinionated styling by browsers that are often styled site wide without consideration of how they would fit in an independent element, as a result they will break the styling of the table. That is why they make use of aria tags, which allow for divs to be given meaning for accessibility. Also the header sort can be triggered not just on the sort icon by on the entire header element depending on table setup which would really break the layout if they were buttons

Tabulator isn't really intended for use in a non-pointer environment and has a great many functions that simply make no sense in a non pointer environment (row dragging for example). 

I'm afraid at the moment this seems like an extremely niche edge case, as I have worked with accessibility based users before (hence aria) without this concern coming up. Without a little more information as to why this might be useful I would not be looking to change this default behavior.

That being said, if you want to submit a PR that allows tabbable header sort then I would be happy to include it, as long as it was enabled by an option and not default behavior. And did not include changing the tag types.

Cheers

Oli :)

**Comment by paulrosen** [comment]
Thanks for the quick reply. Requiring a mouse to get functionality is something that our testers explicitly require. I have other options that I'm looking into, although I like how easy it is to set tabulator up.

**Comment by olifolkerd** [comment]
Hey @paulrosen 

There would be a lot that would need to be considered to add this as an accessibility mode with each of the modules available and without a specific use case in mind it is hard to justify time for it with the other features that are needed.

Im afraid just hitting WCAG testing targets in and of itself isnt really enough, there are hundreds of web standards out there and if i was to aim to perfectly hit them all this library would never have got off the ground. Im happy to help with specific use cases, but if it is a more general "hit this guideline" then im afraid unless it has a significant impact on the wider userbase it would need to be added via a PR or it will go lower down the priority list.

Cheers

Oli :)
