### ISSUE TITLE
Dropdown list on a select cell not displayed when the row is near the end of the browser

### ISSUE THREAD

**Issue by mcoAinos** [olifolkerd/tabulator#3637]
**Describe the bug**
When I click on a dropdown cell, if the table scroll event is triggered, the dropdown list is not displayed.
If the list "overflow" the browser, the scroll event is triggered and the list is automatically hidden.
To reproduce the issue, the last row of the table must be near the bottom of the browser.

**Tabulator Info**
Branch 5.1.3

**Working Example**
 [https://codepen.io/mcoAinos/pen/ZEawJwY](https://codepen.io/mcoAinos/pen/ZEawJwY)

**To Reproduce**
1) Go To [https://codepen.io/mcoAinos/pen/ZEawJwY](https://codepen.io/mcoAinos/pen/ZEawJwY)
2) Be sure the last is near the bottom of the browser 
3) On the rows at the end of the table, click on "Conditions" cell

**Expected behavior**
The list must be displayed

**Screenshots**
Working samples : 
![works](https://user-images.githubusercontent.com/100916484/156729010-d1b27325-5b1e-4a78-9e9f-e4e2709a953d.png)

![works far](https://user-images.githubusercontent.com/100916484/156730091-3d913d83-2e82-48bd-9a19-8354b94cafe2.png)

Issue:
![not work](https://user-images.githubusercontent.com/100916484/156729007-672fd5df-6a4d-4e79-9167-a51d41c7282c.png)

**Desktop (please complete the following information):**
- OS: Windows 10/11
- Browser Chrome
- Version latest

**Additional context**
We work within Microsoft Dynamics 365 web resources, but the issue is reproductible on codepen.

**Comment by Joao-deOliveira** [comment]
Hi there,

Have the same problem ... it works in Firefox as FF expands the frame where the tabulator is ... but not always.

**Comment by zenderp2010** [comment]
Your codepen sample is working fine on Chrome Version 99.0.4844.51 (Official Build) (64-bit). Please update chrome and check.

**Comment by zenderp2010** [comment]
![w](https://user-images.githubusercontent.com/100618190/156882315-db46a9a0-dd5b-40ce-bde2-ca06d8c40a1b.png)

**Comment by olifolkerd** [comment]
@zenderp2010 i can still replicate this on the latest version of chrome, the table must be at the edge of the browser window, but not overflowing the viewport.

I am planning a complete rebuild of the select list in the next minor release and will address this then.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
I have just pushed updates to the 5.2 branch that replaces the ***select*** and ***autocomplete*** editors with the new ***list*** editor, which will resolve this issue.

It will be included in the 5.2 release later this month.

Cheers

Oli :)
