### ISSUE TITLE
Provide a  JS Fiddle or CodePen template to help with bug logging

### ISSUE THREAD

**Issue by sdraper69** [olifolkerd/tabulator#3638]
I have raised a question on [stackoverflow ](https://stackoverflow.com/questions/70714799/tabulator-right-click-menu-doesnt-work-2nd-time-round) over a month ago and got no responses. I know questions are not allowed on the git page, and after further testing myself I wanted to log it as a potential bug. The problem is I have no idea how to create a JS fiddle or codepen especially when it needs to contain tabulator.

It would be great if there was a "template" that was available so that we can very quickly test and then raise issues where appropriate

**Comment by olifolkerd** [comment]
Hey @sdraper69 

I could certainly look at putting together a guide for the website.

I will see what i can do on the next minor release.

Cheers

Oli :)

**Comment by sdraper69** [comment]
Nice one! Your work on this is always much appreciated! Also, if you do have any thoughts on my [stackoverflow ](https://stackoverflow.com/questions/70714799/tabulator-right-click-menu-doesnt-work-2nd-time-round)question that would be handy!

**Comment by lukeorriss** [comment]
Feel free to use this one > blank canvas that contains a table ready to put your own data/ modifications into. https://codepen.io/lukeorriss/pen/podBPZo

To get tabulator to work in codepen (or other) you have to go into settings and get the js/css file from a cdn and paste it in the dependencies. If you take a look at the settings of the codepen above, you'll see what I mean. Hope this helps

**Comment by olifolkerd** [comment]
A quick guide on creating a JS Fiddle can now be found on the Tabulator website http://tabulator.info/community/jsfiddle
