### ISSUE TITLE
V2.11 to v3 tabledata not populating

### ISSUE THREAD

**Issue by firth650** [olifolkerd/tabulator#364]
hi,  I've taken an example from the Tabulator webpage to play around with.

     It worked fine under V2.11.0 but the datatable view is no longer initialised correctly when I switch to V3.0. Are there any syntax differences? I can't see any noted anywhere, but this is my real first foray into the wonders of Tabulator so apologies if I'm missing something obvious.

My complete code is as below

Regards
Steve 

<!DOCTYPE html>
<html>

<script type="text/javascript" src="js/jquery.min.js"></script>
<script type="text/javascript" src="js/jquery-ui-1.12.1/jquery-ui.min.js"></script>

<link href="css/tabulator.min.css" rel="stylesheet">
<script type="text/javascript" src="js/v3.0.tabulator.min.js"></script>
<script type="text/javascript" src=" js/js-xlsx/xlsx.full.min.js"></script> 

<html>
<div class="feature-box-legend">Download Controls</div>

    <div class="feature-box">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 content " role="main">
          <button id="download-csv">Download CSV</button>
          <button id="download-json">Download JSON</button>
          <button id="download-xlsx">Download XLSX</button>
          </div>
        </div>
      </div>
    </div>

</html>

<html>
<div id="example-table"></div>
<p>
</html>

<script>

//Build Tabulator
$("#example-table").tabulator({
    height:"311px",
    movableCols:true,
    columns:[
        {title:"Name", field:"name", width:200},
        {title:"Progress", field:"progress", width:100, sorter:"number"},
        {title:"Gender", field:"gender"},
        {title:"Rating", field:"rating", width:80},
        {title:"Favourite Color", field:"col"},
        {title:"Date Of Birth", field:"dob", align:"center", sorter:"date"},
        {title:"Driver", field:"car", align:"center", formatter:"tickCross"},
    ],
});

var tabledata = [
     {id:1, name:"Oli Bob", progress:12, gender:"male", rating:1, col:"red", dob:"14/04/1984", car:1},
     {id:2, name:"Mary May", progress:1, gender:"female", rating:2, col:"blue", dob:"14/05/1982", car:true},
     {id:3, name:"Christine Lobowski", progress:42, gender:"female", rating:0, col:"green", dob:"22/05/1982", car:"true"},
     {id:4, name:"Brendon Philips", progress:100, gender:"male", rating:1, col:"orange", dob:"01/08/1980"},
     {id:5, name:"Margret Marmajuke", progress:16, gender:"female", rating:5, col:"yellow", dob:"31/01/1999"},
     {id:6, name:"Frank Harbours", progress:38, gender:"male", rating:4, col:"red", dob:"12/05/1966", car:1},
     {id:7, name:"Jamie Newhart", progress:23, gender:"male", rating:3, col:"green", dob:"14/05/1985", car:true},
     {id:8, name:"Gemma Jane", progress:60, gender:"female", rating:0, col:"red", dob:"22/05/1982", car:"true"},
     {id:9, name:"Emily Sykes", progress:42, gender:"female", rating:1, col:"maroon", dob:"11/11/1970"},
     {id:10, name:"James Newman", progress:73, gender:"male", rating:5, col:"red", dob:"22/03/1998"},
     ];

$("#example-table").tabulator("setData", tabledata);

//trigger download of data.csv file
$("#download-csv").click(function(){
    $("#example-table").tabulator("download", "csv", "data.csv");
});

//trigger download of data.json file
$("#download-json").click(function(){
    $("#example-table").tabulator("download", "json", "data.json");
});

//trigger download of data.xlsx file
$("#download-xlsx").click(function(){
    $("#example-table").tabulator("download", "xlsx", "data.xlsx");
});
</script>
</html>

**Comment by olifolkerd** [comment]
Hey Steve,

Your code looks fine (if lacking in indentation for clarity). the only change is that ***movableCols*** is now ***movableColumns***.

Have a look in your console, 3.0 should post a warning there if you have an issues.

Cheers

Oli

**Comment by firth650** [comment]
Hi
    thanks for the response. 

Honestly, my code was nicely indented before I cut and pasted it  here ;-)
 
   The movableColumns made no difference to what I see. 

 I can also now be a little more specific about what I see when I try to initialize the table. 

For example: For  this first ROW
     {id:1, name:"Oli Bob", progress:12, gender:"male", rating:1, col:"red", dob:"14/04/1984", car:1},

I see the first COLUMN  being populated with this data, not the row. All other columns are then blank.   There are no warnings being issued in the console

 I'll keep playing around and see  what I can find.

Regards
Steve

**Comment by Sm00g15** [comment]
try making your browser full screen and doing Command + Shift + R (if you're on Mac)

**Comment by firth650** [comment]
Got it : my fault! I was careless when pointing to the new V3.0 js & css libraries, I'd mixes and matched old-and-new. Apologies!

**Comment by Sm00g15** [comment]
Awesome, glad you got it!
