### ISSUE TITLE
V5.0.1 : headFilter + editor ... error

### ISSUE THREAD

**Issue by pploume** [olifolkerd/tabulator#3640]
Hi,

When I add 'headFilter' to the table definition, and if there is an 'editor' also defined I get an error (from editor func):  cell.getData is not a function

If I remove one of them (or 'headFilter' or 'editor' ... it works)

Here is the table def : 
{title:"File",  field:"uploadFilename",   hozAlign:"right",  width:"auto", headerFilter:true, editor:showPDF},

thanks for any advice
:)

**Comment by olifolkerd** [comment]
Hey @pploume 

If you want to report a bug, please use the [Bug Issue Template](https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Possible+Bug&template=bug_report.md&title=)

We will need to see a js fiddle or code pen that demonstrates the issue, without seeing how your table is setup and the error that is produced it is not possible to offer any guidance.

Cheers

Oli :)
