### ISSUE TITLE
Row selection change with selectablePersistence

### ISSUE THREAD

**Issue by s-cork** [olifolkerd/tabulator#3641]
**Describe the bug**
the row selection change fires a lot when the `selectablePersistence` is set to `false`.
Specifically it fires anytime that `data-refreshing` happens.
But it doesn't need to fire if there are no rows to deselect.

**Tabulator Info**
- Which version of Tabulator are you using? 5.1.2

**Working Example**
https://codepen.io/s-cork/pen/ZEaPzbb

**To Reproduce**
Open the example
Observe the row selection change alert fires 4 times on load
Click any header sort in the example
Observe the row selection alert fires

**Expected behavior**
Don't raise selectionChange if no rows were deselected

**Additonal Context**
Here's the lines of source code I'm refering to:
https://github.com/olifolkerd/tabulator/blob/d0037aac148bc041a28363d677111a8f94e5c861/src/js/modules/SelectRow/SelectRow.js#L300-L308
There is no check as to whether anything was deselected so we get a rowSelectionChange on anything that can trigger a `data-refreshing` event (when `selectablePersistence` is `false`)

Suggested change?

```js
if (rowCount !== 0) self._rowSelectionChanged(silent);
```

**Comment by olifolkerd** [comment]
Hey @s-cork 

I have pushed an update to the master branch so that event is only fired if there are actually rows to be deselected. I will include it in this weekends patch release.

Cheers

Oli :)
