### ISSUE TITLE
setPage/setMaxPage with optional reload

### ISSUE THREAD

**Issue by mihaicristiantanase** [olifolkerd/tabulator#3642]
My setup includes Tabulator with remote pagination and I'd like to change the current and total pages numbers without automatically triggering a reload.
Is there a way of achieving this through existing Tabulator API?

Thank you!

**Comment by olifolkerd** [comment]
Hey @mihaicristiantanase 

If you are using remote pagination, there is no way to change the current page without reloading the data, because the current page is all the data there is in the front end, so there would be no other page to go to without loading additional data.

As for changing the max page independently this is also not possible im afraid, there would also be no way for Tabulator to know that the page count had changed without querying the server.

Cheers

Oli :)

**Comment by mihaicristiantanase** [comment]
Hi,

I see, then I'll continue searching for a solution/workaround.

Just in case the use case I'm trying to implement might be unclear, here it is:
- user does some action (Tabulator independent);
- an HTTP request is triggered (Tabulator independent);
- response is received with data corresponding to the current page (shown in Tabulator);
- sync data, current page and total pages in Tabulator;

Thanks for the quick reply!

**Comment by olifolkerd** [comment]
If all you want to do is refresh the current data you can call the `refreshData` function:
```js
table.refreshData();
```

**Comment by mihaicristiantanase** [comment]
I'll follow up with a workaround I found:

```typescript
// run "fun" with trigger function from Page module temporary disabled
runWithoutPageTrigger(fun: Function) {
    var triggerBkp = this.table.modules.page.trigger;

    this.table.modules.page.trigger = function() {
        return Promise.resolve();
    };

    fun();

    this.table.modules.page.trigger = triggerBkp;
}

// usage
this.runWithoutPageTrigger(() => {
    this.table.setMaxPage(42);
}
```

**Comment by DevinLindsey** [comment]
> If all you want to do is refresh the current data you can call the `refreshData` function:
> 
> ```js
> table.refreshData();
> ```

@olifolkerd is this still valid? I don't see a refreshData method on the table? I do see a refreshData method off the Page module `table.modules.page.refreshData`

**Comment by olifolkerd** [comment]
There is `replaceData`, but with remote pagination the only way to trigger an update of those values is to request the page again and get the data back from the server

**Comment by DevinLindsey** [comment]
So there’s no way to pass the data if we already have it (aka a http request outside of Tabulator) and we already have an update last page and last row count?

**Comment by olifolkerd** [comment]
Not if you are doing remote pagination no
