### ISSUE TITLE
Exclude Groups from Pagination Count

### ISSUE THREAD

**Issue by lukeorriss** [olifolkerd/tabulator#3643]
**Describe the bug**
When using groups with pagination, the groups are counted as rows. If pagination is set to 10 rows per page, and there are groups present on the page too, the number of groups will be included in the amount of items to show on the page. 

**Tabulator Info**
Version 5.1

**Working Example**
https://codepen.io/lukeorriss/pen/dyZwwez?editors=1010

**To Reproduce**
Create a table with pagination enabled, as well as groups in the data. Configure pagination options to use `paginationCounter: "rows"`, when the groups are displayed in the table, the total rows of data shown on the page will include the groups.

**Expected behavior**
Total number provided by pagination should exclude the number of groups on the page. 

**Screenshots**
![image](https://user-images.githubusercontent.com/73408132/157065365-409a8695-3354-4a74-9bed-50ada15e751f.png)

The above image shows 5 rows of data and 2 groups. So the pagination info at the bottom of the table should reflect that 1-5 of 5 rows are being shown. However, the groups are included. Showing 1-7 of 8 total.

**Desktop (please complete the following information):**
 - OS: Windows 10 Business
 - Browser: Brave
 - Version: 1.36.109

**Additional context**
Originally raised on Stack Exchange, asked to create a bug report: 
https://stackoverflow.com/questions/71337184/exclude-groups-from-pagination-count-in-tabulator/71371006#71371006

**Comment by olifolkerd** [comment]
Hey @lukeorriss 

Thanks for the feedback, up have just pushed a fix to master that will only include actual data rows in the counter. I will include this in this evenings patch release.

Cheers

Oli :)
