### ISSUE TITLE
Virtual horizontal dom scroll with fitDataFill makes data disappear (or fitData with a small width screen) 

### ISSUE THREAD

**Issue by rathboma** [olifolkerd/tabulator#3646]
Bug:

- Set layout to `fitData` (bad) or `fitDataFill` (much worse)
- Scroll right slowly
- See data disappear

I've replicated this on my test bench.

There are two videos below, first is fitData, second is fitDataFill

## FitData Video

https://user-images.githubusercontent.com/279769/157157857-a2a7b0e5-1660-451b-8894-0d5cb3b2d51d.mp4

**Comment by rathboma** [comment]
Replicated here: https://github.com/beekeeper-studio/tabulator/tree/hoz-dom-3646
start with `yarn web:dev`, go to http://localhost:5678/examples/hoz-dom.html

**Comment by rathboma** [comment]
Actually, with `fitDataFill` layout mode the data disappears entirely

https://user-images.githubusercontent.com/279769/157158431-1cf4e715-473f-4786-9555-f4f345ab1036.mp4

**Comment by rathboma** [comment]
In Beekeeper Studio using 5.1.4 I don't see the same amount of disappearing data, but I do see column headers go out of alignment, my guess is that it's a related issue. Beekeeper uses `fitDataFill` also

**Comment by olifolkerd** [comment]
Hey @rathboma 

Disappointing, that is probably an issue when the column being removed has a width larger that the viewport or the hoz vdom buffer.

I will add a couple of properties in this evening to allow manual management of the buffer size which should help resolve this, though it may also be worth combining it with a `maxWidth` on the columns to prevent them from becoming unmanageably wide.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @rathboma 

I have just pushed a couple of fixes for this to the master branch and will do a patch release shortly when i have a couple of other bits in.

There were two issues that needed fixing:

The special calculations needed when using `fitData` layout mode were only being applied when the mode was `fitData` and not any of the other similar modes like `fitDataFill`.

There was a fix buffer window of 200px (the area of the virtual DOM that exists beyond the visible area, any columns bigger than that eroded the buffer and lead to the whitespace being visible. I have upgraded it with an adaptive buffer that rescales to be to times either the width of the table or the widest column, whichever is bigger. which should prevent this from occurring.

Have a play and let me know if anything else needs tweaking. Thanks for all the details, they are really making it easy to resolve the bugs.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
The v5.1.5 release is now out!

**Comment by olifolkerd** [comment]
In relation to your last comment of the column headers going out of alignment, after i published the update i did notice it briefly once when scrolling, but it self corrected and i couldn't seem to replicate it again.

If you have a reproducible way to generate would you mind popping it in a separate issue and i can get straight on that.

Cheers

Oli :)

**Comment by rathboma** [comment]
Thanks Oli, you rock! Sorry for the barrage of issues on the horizontal DOM!

If I can figure out how to replicate the column alignment issue I'll be sure to open yet another issue :laughing:
