### ISSUE TITLE
sortMode remote and autoColumns True

### ISSUE THREAD

**Issue by s-cork** [olifolkerd/tabulator#3649]
**Describe the bug**
when sortMode is remote and autoColumns is set to True - clicking the header always provides `"asc"` in the data param for sort.dir.

**Tabulator Info**
- Which version of Tabulator are you using? 5.1.2

**Working Example**
https://codepen.io/s-cork/pen/qBVGeyG

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Open the console
2. Click the header sort repeatedly
3. observe that dir is always "asc" and the caret doesn't change direction
4. Comment autoColumns and uncomment the column definition
5. observe that dir switches between "asc" and "desc" and the caret changes direction

**Expected behavior**
clicking the header should switch between "asc" and "desc" when autoColumns is True and using sortMode remote

**Comment by olifolkerd** [comment]
Hey @s-cork 

This is happening because when auto columns are enabled, the act of loading data into the table rebuilds the column list, which then resets the sort as the columns are replaced.

I will look into changing this behaviour to only replace the columns if the list has changed.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @s-cork 

I have pushed a fix for this to the master branch and will include it on the next patch release in a few days time.

Cheers

Oli :)

**Comment by sniemetz** [comment]
Hi @olifolkerd 

I am running into the same issue with 6.3.0: In my case I define the columns in the ajaxResponse callback where I set editors and sorters. Passing the remoteSort parameters works fine but as above, the sort direction is always set to "asc".
Am I doing something I shouldn't do - or should I create a bug/fiddle?
