### ISSUE TITLE
Json with objects fields

### ISSUE THREAD

**Issue by lzacha** [olifolkerd/tabulator#365]
Hello Oli,

I have one simple questions and I'm not sure how manage this. I have a complex json with a list of amazon orders where one of the fields is an object like this (shipping_address & order_total)
(i'm using ajax to get them)

....
"order_status": "Shipped",
"fulfillment_channel": "ABC",
"sales_channel": "Amazon.com",
"ship_service_level": "Std ES Dom_2",
**"shipping_address": {
	"state_or_region": "New York",
	"city": "New York",
	"phone": "123456",
	"country_code": "US",
	"postal_code": "123456",
	"name": "Test Colomer",
	"address_line1": "C/ Capellades, 17 2-3",
},
"order_total": {
	"currency_code": "EUR",
	"amount": "23.99"
},**
"number_of_items_shipped": "1",
"number_of_items_unshipped": 0,
....

What would be the correct way to transform this objects so that the tabulator understands it and can be edited like any simple column?

It would be ideal to take these objects to my table in this format
http://olifolkerd.github.io/tabulator/examples/3.0/#column-groups

Regards,
Leo

**Comment by olifolkerd** [comment]
Hey Leo,

Thanks for getting in touch, just to confirm would you like a column group for the order_total and then a column for the currency_code and a column for the amount?

Cheers

Oli

**Comment by lzacha** [comment]
Yes, you are right

**Comment by olifolkerd** [comment]
At the moment Tabulator cant handle nested objects (though this feature is on the roadmap for this year).

In the mean time you will need to flatten your data so that tabulator can access it all, issue #125 already has some instructions on how you can do this. 

Let me know if you need any further help.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey,

You will be happy to hear that Tabulator 3.2 has just been released, and with it the the ability to bind columns to nested data, simply use dot notation in the field name:
```js
{title:"age", field:"user.age"), //link column to age property inside user object
```

Full information can be found in the [Column Definition Documentation](http://olifolkerd.github.io/tabulator/docs/3.2/#field-nesting)

Cheers

Oli

**Comment by RuchiTrehan** [comment]
Hello Oli,

Can tabulator have the feature to parse json of the following structure ? 
{
   "ObjectName" : "password",
   "ObjectType" : "",
   "Xpaths" : [ {
      "Value" : "//input[@id='password']"
   } ]
}

**Comment by olifolkerd** [comment]
Hey @RuchiTrehan 

Tabulator uses the inbuilt JSON.parse function of the browsers, so if it is valid JSON then Tabulator will be able to accept it.

Cheers

Oli :)

**Comment by RuchiTrehan** [comment]
But can I write Xpaths[0].Value when sending json data to the tabulator ? 
If not, how can i access this value ?
