### ISSUE TITLE
Filter Table by another fields value with setFilter method

### ISSUE THREAD

**Issue by samad-kanton** [olifolkerd/tabulator#3651]
I've gone through the documentation and realize there's no way I can use the setFilter() to filter data based on the value contained in an adjacent field. Looking at the doc, it looks as if you can only filter the table based on a passed value and not a field.

For instance:
I have a stocks table where I would want to filter all **quantities** below or equal to the **reorder level**.

So what I would wish to have is say:
tableStocks.setFilter({ field: 'qty', type: '<=', value: '**restock**' })

and by me passing 'restock' for the value property, it should loop through the entire table by querying rows that have quantities **lessThanOrEqual** to its respective value contained in the restock field. 

These are the fields contained in my table.

![Screenshot 2022-03-09 at 9 20 50 AM](https://user-images.githubusercontent.com/31456450/157411827-50b36b35-23ea-4d58-8c16-638006d7fca7.png)

**Comment by olifolkerd** [comment]
@samad-kanton You would need to use a [Custom Filter Function](http://tabulator.info/docs/5.1/filter#func-custom) for this.

Using a custom filter function means you can filter in any way you like.

Cheers

Oli :)
