### ISSUE TITLE
Navigation using keyboard arrows for Accessibility in non-editable tabulator Tables

### ISSUE THREAD

**Issue by sagartalaviya94** [olifolkerd/tabulator#3652]
To Implement Navigation using keyboard arrows for Accessibility in non-editable tabulator Tables.
As currently support is available for editable tabulator tables, but for non-editable tabulator Tables also It is must have feature for ADA users.

Currently for ADA users regular tabulator tables are not accessible. 
Feature should be like
1) user should be able to navigate to first row first cell using tab, then It should support up/down/left/right arrows for navigation.
2) Inside the table If user click on tab than It should go focus out of table. because If there are 100s of rows and user don't want to read full table than user should be able to move focus outside using tab.
Ideally table should support navigation like this [https://www.w3.org/TR/wai-aria-practices/examples/grid/dataGrids.html]

Thanks!!

**Comment by shirgans** [comment]
I would like to also ask few features, as I tried to implement it myself, but it seems to be very difficult:
1) When user reach bottom of page, it should go to the first row of the next page. And when reaching the top of the page (using up arrow) it should go to the last row of the previous page.
2) This behaviour should be kept even if the user is sorting. I found this some what difficult to follow the position of the row and calculate where to go next/prev after sorting.
3) An option to highlight the entire row (css class would be perfect)

**Comment by olifolkerd** [comment]
With the new range selection options this is now possible!

This includes [Cell Range Selection](https://tabulator.info/docs/5.6/range#overview) that lets you navigate around the table using arrow keys. This can be combined with editors.

Checkout the [Spreadsheet Example](https://tabulator.info/docs/5.6/range#spreadsheet) to see it in action!

Have a look at the [Release Notes](https://tabulator.info/docs/5.6/release) for full details of all the features added in this release :)

Cheers

Oli :)
