### ISSUE TITLE
Eslint configuration and github actions build to check lint rules?

### ISSUE THREAD

**Issue by rathboma** [olifolkerd/tabulator#3656]
There are some official repository rules (eg tabs not spaces), and some unofficial good practices (no unreachable code, don't define variables you don't use) that we all check for when making a PR.

Would you be open to me creating an eslint file and adding a github actions pipeline file to check lint rules for all commits?

I wanted to check with you before doing the work, but happy to do it.

I'd use eslint's recommended rules, plus some customizations based on the contribution guidelines.

**Comment by olifolkerd** [comment]
Hey, 

Yeah that sounds like a great idea. As long as it matches the current coding style I'd be very with that.

I've not done anything with GitHub actions before. Do you have any info on these?

Cheers

Oli :)

**Comment by rathboma** [comment]
Github actions are great, and totally free for open source projects (like this one!).

It basically just runs a bunch of commands on either ubuntu/mac/windows based on an event (commit, pr, etc)

Here's an example from Beekeeper Studio - https://github.com/beekeeper-studio/beekeeper-studio/blob/master/.github/workflows/sqltools-test.yml

**Comment by rathboma** [comment]
Ok, I'll get on it now.

**Comment by olifolkerd** [comment]
Sounds cool. What happens if you push and the lint fails?

Also on a side note, what tools do you use for unit testing? I would love to start getting some in for Tabulator. It's just a hurculean task to start. Once I have finished fully decoupling all the modules using the event system (over the next couple of minor releases) they should be in a good state to start. I've decoupled all the simple modules so far (about half of them)

**Comment by rathboma** [comment]
If it fails, it adds a red x next to the commit hash in GitHub, that's it, you're free to ignore it.

So for unit testing, I just use jest, it's super easy to set up.

If you want headless-browser testing, https://playwright.dev/ seems to be the de-facto choice right now.

**Comment by olifolkerd** [comment]
Hey @rathboma 

This has now been merged in to the 5.3 branch and configured.

Cheers

Oli :)
