### ISSUE TITLE
Row.deleteCells look wrong

### ISSUE THREAD

**Issue by nclemeur** [olifolkerd/tabulator#3658]
The `deleteCell`s method in the Row class seems to only delete the first cell. Is that something expected?

```	
      deleteCells(){
		var cellCount = this.cells.length;

		for(let i = 0; i < cellCount; i++){
			this.cells[0].delete();
		}
	}
```

**Comment by KAYFLUHR** [comment]
shouldn't it be this.cells[i].delete();

**Comment by olifolkerd** [comment]
Hey, feel free to submit a PR if you have found a bug 😁

**Comment by olifolkerd** [comment]
Hey @nclemeur 

No this works as expected. when the `deleted` function is called on a cell it deregisters itself from its parent row and removes itself from the cells array. Therefore each time it is called on `[0]` it is actually being called on the next cell in the ever shrinking array

Cheers

Oli :)
