### ISSUE TITLE
Looking to have a clickable row that leads to another page

### ISSUE THREAD

**Issue by Sm00g15** [olifolkerd/tabulator#366]
So I'm a super noob and still trying to wrap my head around this: 

```js
$("#example-table").tabulator({
        rowClick:function(e, row){
        //e - the click event object
        //row - row component
    },
});
```
I'm adding this into my code to make my rows clickable. 

So how can I make this clickable row render a new page at {domainhere}/:symbol, where :symbol is different for each clickable row in this case? The symbols I'm referring to will be coming from coinmarketcap.com...Does this question make sense?

**Comment by olifolkerd** [comment]
Hey,

if you are looking for the symbol in the row data, and you want to open  the link in a new tab then you can do the following:

```js
$("#example-table").tabulator({
        rowClick:function(e, row){
        //e - the click event object
        //row - row component

         window.open("http://yourwebsite.com/" + row.getData().symbol, "_blank");
    },
});
```
Let me know if that works for you

Cheers

Oli

**Comment by Sm00g15** [comment]
Nah, that didn’t do the trick. 



This is the console error I’m getting. 


Sean Magin	
Farm Manager
Arrowburn Farm
