### ISSUE TITLE
cell-delete subscription problem

### ISSUE THREAD

**Issue by nclemeur** [olifolkerd/tabulator#3660]
**Describe the bug**
When registering a listener for cell-delete events, the application crash

**Tabulator Info**
5.1.7

**Working Example**
https://codepen.io/nclemeur/pen/gOobLzO

**To Reproduce**
1. Open codepen above
2. Click on swap data button
3. See error in browser console.log (no error in integrated console)

**Expected behavior**
No error

**Additional context**
It is working as expected if the line `this.subscribe('cell-delete', this.cellDelete(this));` is commented out.
Sorry just jumped to conclusion too quickly in #3658, but for some reason I have a hard time debugging tabulator in my project using vitejs.

**Comment by nclemeur** [comment]
Sorry again for the noise I had again an issue in my codepen trying to reproduce the problem I am facing in my vue project

**Comment by olifolkerd** [comment]
Hey @nclemeur 

Your code pen works just fine when i use it, there is no crash or console error and the console logs come out as expected.

In your example there you have incorrectly bound the function
```js
this.subscribe('cell-delete', this.cellDelete(this))
```
It should be
```js
this.subscribe('cell-delete', this.cellDelete.bind(this))
```

Please can you clarify where the issue is in your example. It is very unlikely to be an issue with the internal event subscription system, if it was the entire table would simple have ceased to function as every part of table functionality is dependant on it.

Cheers

Oli :)

**Comment by nclemeur** [comment]
Hello Oli,
Yes the problem was with the subscribe call. I just noticed it a minute after pushing the submit issue button. So sorry again for all the noise. Having said that I wish there were other way to discuss with the tabulator community outside github issues or stackoverflow. For example I would have the following questions, that are not really relevant to a github issue or stackoverflow

o is there a codepen/js fiddle template that we should use to get started to describe a question/issue (one the thing I really love in the primevue framework for example, is the ability for every example to click on a button and this open a new window with the example running inside codepen)
o is the documentation sources available. Sometimes I wanted to check how an example is implemented from start to finish, but this is not really feasible
o is there any api documentation available outside the documentation guide (I am trying to integrate tabulator with vue 3 and it would be useful to know for example all the methods available on the instance)
o any forums/discord server available (I am not a super fan of discord, but if that was existing it would still be better than github issue/stackoverflow for simple discussion). What about github discussion (for example see https://github.com/vuetifyjs/vuetify/discussions)?

Anyway, great work on this library!

**Comment by olifolkerd** [comment]
Hey @nclemeur 

Thanks for your feedback, As part of the website refresh which is currently underway i am looking to add a JS Fiddle creation guide to make it easier to create your own Fiddle.

There is a install guide that goes through the numerous options for including Tabulator in a project. There are also quick start guide with a link to a basic example that show full start to finish code in the install docs, i would be happy to move the basic example to a fiddle if that is easier for others.

Every example on the tabulator site already comes with a "View Source" button that shows the source needed for that table, I don't believe it is the function of a library site to give full instruction on how to use JavaScript for a project, so it shows only the relevant library code. 

The documentation outlines every available function on the table, there is no hidden functionality in the library.  While i agree that a detailed API doc would be useful, given the sheer scale of Tabulator and all of its modules at this point it would be a massive undertaking to do this, and i simply do not have the time to do that while maintaining the library and the existing docs. So realistically it wont be appearing any time soon unless a member of the community volunteers to create it *(I would be happy to collaborate and accept PR's to the tabulator.info site, but the repo is private so it would be invite only)*.

As for a discussion, that is something I am looking to include with the next website update as well, I was considering a slack organisation, but I'm open to other ideas.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @nclemeur 

The website updates are complete, and i'm happy to announce the creation of the new Tabulator community Discord server.

Checkout the {Community Discord Announcement](http://tabulator.info/community/discord) for full details.

Cheers

Oli :)

**Comment by nclemeur** [comment]
Hello Oli,

Great news for the discord server and the new web site. It looks great.

Now, I am not sure if we should continue the discussion here or on discord? Anyway, just a few words probably to finish and give more context.

Regarding my remark about example from  start to finish, I was more talking about all the options of the tables. For example, the first example in the manual (virtual dom vertical), you have a table where the column can be resized, but this is not apparent in the code below how this is done (and there is not example specific to resizable column), so that what I mean by complete example. Also I am coming back with providing a link from each example to a codepen/fiddle. I think this would add really a lot of value to all the example. It is also making bug reporting very easy on code that you already know. If you haven't seen how primevue is doing it you can for example look [here](https://www.primefaces.org/primevue/#/datatable/templating), at the top right of the example there are a few button and clicking on the codepen one (the one next to the github button) (selecting one the three options (composition, browser or options), will open a fresh codepen with all the code required to run that example. 

Regarding the api I can certainly understand this is not a trivial task and would need to be automated from the source code so that it does not get outdated too quickly. But in the meantime I'll just use the source code.

**Comment by olifolkerd** [comment]
Given the number of options on Tabulator It is simple not practical to provide an interactive example for every possible setup option. But you can easily use the search box to find any feature you need along with some example code for that feature.

The "View source" button for each example reveals the full set of table options needed to recreate that table with nothing hidden. If you cannot recreate a specific example and believe something is missing then please create a bug issue and report the particular example.

While I appreciate the feedback, I certainly won't be looking to add a code pen for each example. I am happy with the current embedded approach and think it offers a good compromise between embedded examples, sample code and development time, and have broadly received positive feedback on this approach. Between maintaining the library and the website I simply don't have the time to then be maintaing a huge number of code pens as well. Especially when you consider each codepen would need duplicating for each release.

Cheers

Oli :)

**Comment by nclemeur** [comment]
From my undestanding, primevue don't maintain a huge number of codepen, they create a new codepen when you click that button passing on the code of the example along the request. I don't know the details of how this working, but I could dig into that if you are interested.

I'll create a bug/feature request issue for the missing column resizing example.

**Comment by olifolkerd** [comment]
If it is an automated process then I would certainly be up for including a button, if you can find details on how it works I would be happy to consider it further

**Comment by nclemeur** [comment]
I was wrong about primevue using codepen, they are actually using sandbox, but it is reasonably simple to prepare a new sandbox. The code is similar to this:
```
let sandboxData = null;
function getFiles(){
//functions that return an array of files, for example:
return  {
    'index.js': {
      content: "console.log('hello')",
    },
    'package.json': {
      content: { dependencies: {} },
    },
  },
}

fetch('https://codesandbox.io/api/v1/sandboxes/define?json=1', {
                method: "POST",
                headers: {
                    'Content-Type': 'application/json',
                    'Accept': 'application/json'
                },
                body: JSON.stringify(getFiles())
            })
            .then(response => sandboxData = { ...response.json()})
            .then(data => window.open(`https://codesandbox.io/s/${sandboxData.sandbox_id}`, '_blank'));
```

So depending a bit on how the server side of the documentation is done this could quite simple or not :-)

There is more info about the codesanbox api [here](https://codesandbox.io/docs/api)
