### ISSUE TITLE
Missing Group Component & virtual dom documentation

### ISSUE THREAD

**Issue by Narretz** [olifolkerd/tabulator#3661]
**Website Page**

http://tabulator.info/docs/5.1/group

and http://tabulator.info/docs/5.1/virtual-dom

**Describe the issue**

This link doesn't exist

http://tabulator.info/docs/5.1/group#component-group

http://tabulator.info/docs/5.1/virtual-dom links to itself, but there's nothing about configuration in this page.

**Comment by olifolkerd** [comment]
Hey @Narretz 

The link you are looking for is http://tabulator.info/docs/5.1/components#component-group

I will have a look through the docs and replace the broken links.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @Narretz 

An update to the broken link will be included in this evenings site update.

Cheers

Oli :)
