### ISSUE TITLE
redraw() only updates the "top level" rows in a tree data

### ISSUE THREAD

**Issue by anttir** [olifolkerd/tabulator#3664]
**Describe the bug**
When using formatters and calling redraw() -function only the rows in the top level of a tree data are updated. 
This functionality has changed since version 4.X

**Tabulator Info**
- version 5.1.7

**Working Example**
https://jsfiddle.net/h4gsn6vo/2/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://jsfiddle.net/h4gsn6vo/2/
2. Change the "age highlight threshold" (numeric input on top of the table)
3. Only the cells in the "top level" rows where the age is above threshold are highlighted

**Expected behavior**
All the cells in the age column that are above the threshold  should be highlighted.

**Screenshots**
![image](https://user-images.githubusercontent.com/481372/158595588-22ba6b89-b388-4815-9247-8edd54f2992b.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version 99

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Android 12
 - Browser Chrome (stock)
 - Version 99

**Additional context**
exact same code works when using version 4.9.3 of the tabulator https://jsfiddle.net/4u7avxwe/1/
![image](https://user-images.githubusercontent.com/481372/158597605-69748045-bb5d-4e7c-9f53-47835fc366fd.png)

**Comment by olifolkerd** [comment]
Hey @anttir 

Thanks for the info, i have just pushed a fix for this to the master branch that will be included in todays patch release.

Cheers

Oli :)

**Comment by anttir** [comment]
Excellent! Thank you very much for the fix and everything else with this fantastic tool!
