### ISSUE TITLE
table.updateColumnDefinition creates duplicate entries in array returned by table.getColumnDefinitions()

### ISSUE THREAD

**Issue by gruzk** [olifolkerd/tabulator#3667]
When updating a column definition (to change a formatter) there appears to be a duplicate column definition created in the result returned by table.getColumnDefinitions().  Subsequent errors occur when using tabulator if one of the duplicated column definitions has a sort applied.

As a workaround I have used table.setColumns, which does not create duplicate column definitions, but this does not preserve sort settings.

**Comment by gruzk** [comment]
Example code to demonstrate the error.  The second alert shows the "name" column definition exists twice.

Furthermore, the sort arrow in the column header is greyed out (indicating no sort order) when the rows remain sorted as "desc".  The arrow should be pointing downwards and not greyed out.

```
const data = [
    {name: 'a', age: '2'},
    {name: 'b', age: '1'}
];

var table = new Tabulator("#my_table", {
    data: data,
    height: "200px",
    initialSort: [
        {column: 'name', dir: 'desc'}
    ],
    columns: [
    {title: "Name", field: "name"},
    {title: "Age", field: "age"}
    ],
});

function test() {
    const before = JSON.stringify(table.getColumnDefinitions(), null, '\t');
    alert(before);

    table.updateColumnDefinition("name", {formatter: 'textarea'});
    
    const after = JSON.stringify(table.getColumnDefinitions(), null, '\t');
    alert(after);
}

table.on('tableBuilt', test);
```

**Comment by doublehrajput** [comment]
`table.updateColumnDefinition` is a Promise 

You can thenable your updateColumnDefinition or can use async..await


```
async function test() {
  const before = JSON.stringify(table.getColumnDefinitions(), null, "\t");
  console.log(before);
  await table.updateColumnDefinition("name", { formatter: "textarea" });
  const after = JSON.stringify(table.getColumnDefinitions(), null, "\t");
  console.log(after);
}

table.on("tableBuilt", test);


```

**Comment by gruzk** [comment]
Yes, you are right!  That has fixed all my problems.  I don’t know how I didn’t see that this was a Promise in the documentation… my mistake.  Thank you very much for your help.
