### ISSUE TITLE
Website Update  and Community Discord Server

### ISSUE THREAD

**Issue by olifolkerd** [olifolkerd/tabulator#3670]
Hi Everyone,

Its been a busy month and i have a couple of general announcements:

## Discord Server
Following feedback from the community that they would like a more open place to chat about Tabulator, i am happy to announce that our Discord server has just gone live!

To join the Tabulator Discord community, follow this invite link: https://discord.com/invite/G2DV8udCeB

## Website Update
Ahead of the v5.2 launch next month i am happy to announce that the refreshed Tabulator website has just gone live.

The http://tabulator.info URL is still the same, but you will be greeted with a whole new look and feel, here are a few of the updates that have been made to the site:

### Rebrand
Tabulator has had a bit of a rebrand, going for a cleaner simpler look to the logo and the site

### Fully Responsive Design
The website is now fully responsive, with menu and search access now available on mobile devices as well as desktops

### Code Copying
All of the code examples will now have a `copy` button appear in the top right when you hover over them, making it easier than ever to copy code from the site

### Link Sharing
Want to share a link to a specific part of a page? No problem, any header with the green `link` icon next to is is now a clickable hyperlink. Simply right click on the header and chose the "Copy link address` option from the context menu

### Improved Sidebar
The sidebar has been enhanced to make it easier to navigate around pages and documentation for older releases has been updated to use the new sidebar

### Version Picker
The documentation version picker will now keep you on the same relative page when switching between versions

### Community Pages
The community page has been split out into a number of other pages, to give more space for explaining how to raise PR's and how to help out with the Tabulator community

### Notifications
A new notifications popup has been added to the top right of the site, this will popup whenever there is something new to see, click the popup for more info

Happy Tabulating!

Oli :)

**Comment by zenderp2010** [comment]
Hi Oli,

Website is looking great....you are doing a great job.... Thank you....

Best regards

ZendERP

**Comment by doraemonxxx** [comment]
**The new design is really great!** and it has a Discord Server 🎉.

Question:
is there a button to toggle the dark theme into a light theme? Docs are kinda hard to read for me and maybe other users also.

Thanks, Oli!

**Comment by olifolkerd** [comment]
@doraemonxxx thanks for the feedback.

At the moment it is only dark theme. Though earlier this eve I did update the colour scheme to lighten the background so the contrast wasn't so agrresive.

Most Devs seem to prefer the dark theme these days but if there is enough desire from the community I will happily add a light theme to the site. Though it won't be soon I'm afraid, as I need to focus on the 5.2 release for the next few weeks.

Cheers

Oli :)

**Comment by Jojoshua** [comment]
Love the new site @olifolkerd . Browsing through framework support which I hadn't discovered before...pleasantly surprised there was a Svelte setup section. Professional work as always.
