### ISSUE TITLE
table.updateData() doesn't update child values

### ISSUE THREAD

**Issue by peters59** [olifolkerd/tabulator#3673]
**Describe the bug**
table.updateData() doesn't update child values

**Tabulator Info**
5.1.7

**Working Example**
https://jsfiddle.net/peters2/onv5trg2/19/

**To Reproduce**
click on both buttons

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
OS: Windows 10
Browser: Google Chrome
Version 99.0.4844.82 (Offizieller Build) (64-Bit)

**Comment by doublehrajput** [comment]
Since `id=7` is not a direct row of table, You can't update it as `table.updateData([{id:7, name:'77777'}]);`

Instead you must update your children data as

`table.updateData([{ id: 2, _children: {id: 7, name: "77777777"} }]);`

**Comment by netwiseguy** [comment]
Edit the table object and the cells will update. This is what I did successfully. 
I wanted to change the "factor" value in my data for a single child which was 2 child levels deep
(i.e. Parent >> children >> children >> [one sub child needs new value for "factor"]  )

I created a method passing in the id of the row and the new value for "factor" I want to update in my dataTree:
const updateRowData = (id, newFactorValue) => {
	var tblRows = tableRef.current.getRows();
	tblRows.forEach((row,index)=>{
		if (row.getTreeChildren().length > 0){
			row.getData()._children.forEach(child=>{
				const childRowChildren = child._children;
				if(child._children){
 				   child._children.forEach(subChild=>{
					if(id == subChild.id){
						const oneChild = childRowChildren.filter(child =>{return child.id == id});
							oneChild[0].factor = newFactorValue;
						}
					})
				  }
			  })
		}
	});
}
![github-tabulator-example](https://github.com/olifolkerd/tabulator/assets/5355869/0c1a763c-47ae-4a4e-b2b1-7ee5a572895f)
