### ISSUE TITLE
Add css class to expanded row

### ISSUE THREAD

**Issue by sikor04** [olifolkerd/tabulator#3674]
*Is your feature request related to a problem? Please describe.**
I would like to style background of expanded row with different color so the user could easily sport the parent / expanded row.

**Describe the solution you'd like**
Add css class `tabulator-row--expanded` & `tabulator-row--contracted` to the row div based on the state (visibility of children rows).

**Describe alternatives you've considered**
I did not find any way how to style expanded row.

**Comment by olifolkerd** [comment]
What do you mean by an expanded row?

**Comment by olifolkerd** [comment]
You could do this yourself with a row formatter.

you can call the `row.isTreeExpanded()` function on the row passed into the formatter to see if the row is expanded, then us the `row.getElement()` function to retrieve the row element and add the classes you need.

Cheers

Oli :)

**Comment by sikor04** [comment]
Ah you are right. I am sorry :)
