### ISSUE TITLE
Calling recalc() manually after data manipulation yields error

### ISSUE THREAD

**Issue by samad-kanton** [olifolkerd/tabulator#3679]
I'm using Tabulator v4.9.
When I call recalc() to recalculate the columns, it returns error on the browser's console
"Uncaught ReferenceError: table is not defined". Don't know why?

Isn't the recalc method supposed to be used for re-calculating as when you wish ?

![Screenshot (5)](https://user-images.githubusercontent.com/31456450/160833985-c8578adb-6520-4f06-86b7-7afb4f0f4878.png)

**Comment by olifolkerd** [comment]
If you wished to report a bug please use the bug reporting template and include a link to a js fiddle that demonstrates your issue. Without swing how the table is setup it is not possible to offer advice.

Cheers

Oli:)

**Comment by olifolkerd** [comment]
Hey @samad-kanton  You are also using an old version of Tabulator.

We are now on v5.1 which has had a complete rebuild.

Please try again on the latest version and [Raise a new bug](http://tabulator.info/community/bug) if you are still having trouble.

Cheers

Oli :)
