### ISSUE TITLE
downloadTitle column definition renamed in v5 but some pages still show it unchanged

### ISSUE THREAD

**Issue by ktsuench** [olifolkerd/tabulator#3680]
**Website Page**
A link to the page with the issue

Code example shows property as `downloadTitle` instead of `titleDownload`:
http://tabulator.info/docs/5.1/download#json-lines

Under the `Data Manipulation` section `downloadTitle` is listed instead of `titleDownload`:
http://tabulator.info/docs/5.1/columns#definition

**Describe the issue**
A clear and concise description of what the issue is.

The code example isn't a big issue since people can figure that one out as the updated column definition name is mentioned above the code example, but the column definitions is misleading as it doesn't show the column definition has been renamed.

It would be helpful to have this corrected on the column definitions page along with a note pointing out that it has been renamed.

**Comment by olifolkerd** [comment]
Hey @ktsuench 

As it happens i noticed that one myself the other day, i will fix it on the next website update.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
This has now been fixed
