### ISSUE TITLE
Tabulator Tree Filtering

### ISSUE THREAD

**Issue by LebCit** [olifolkerd/tabulator#3682]
**Describe the bug**
In the documentation we can read the following :
"_When you are filtering rows in the table, Tabulator will by default apply the filter to all child rows, showing only child rows that match the filter._"
So if I understand, filters can be applied to children rows.
I don't know if it's the intended behavior, but if I search for a child row, I get nothing.

**Tabulator Info**
- 5.1

**Working Example**
https://codepen.io/LebCit/pen/Exovedq

**To Reproduce**
Try to search/reach any child row from the filter.

**Expected behavior**
Display the child rows that match the filter.

Thank you very much for your time and all your efforts.

SYA

**Comment by olifolkerd** [comment]
Hey @LebCit 

This is behaving as expected. Child rows cannot be shown independant of their parent, if the parent fails the filter then the child will not be visible.

The meaning of this functionality is that if the parent and a child match then the children that match will be visible.

Cheers

Oli :)
