### ISSUE TITLE
The row selection formatter does not respect if a row is selectable or not

### ISSUE THREAD

**Issue by santor** [olifolkerd/tabulator#3685]
**Describe the bug**
The `rowSelection` formatter with [tickbox](http://tabulator.info/examples/5.1#selectable-tick) doesn't respect if a row is selectable or not. To disable the row selection I used the select option `selectableCheck` as documented in [selection eligibiltiy](http://tabulator.info/docs/5.1/select#setup-eligible). 

**Tabulator Info**
- Tabulator version 5.1

**Working Example**
[Link](https://codepen.io/s-ndor-t-r-k/pen/jOYaYEM?editors=1010) to codepen example.
In the example the rows containing users without `car` should not be selectable:

```
var table = new Tabulator("#example-table", {
    selectableCheck: function(row){
        //row - row component
        return row.getData().car; //allow selection of rows where car exists
    },
   ...
});
```

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
**Click on checkbox in a row**
1. click a checkbox in a row, where the  user does not have a car
2. the checkbox is **checked** despite that the row is not selectable
![image](https://user-images.githubusercontent.com/3255198/161394798-bc1dafd1-aad7-45f5-94a9-e8c414283ca2.png)

**Click on the checkbox in the header**
1. click the checkbox in the header to select all the rows
2. all the rows are selected, even thoose which shouldn't be selectable
![image](https://user-images.githubusercontent.com/3255198/161394904-599acc8e-cf01-4aec-8c92-92cf4bed9c1e.png)

**Expected behavior**
The checkboxes on rows, which are not selectable should be disabled.
Selecting all the rows with the header checkbox, should respect if a row is selectable or not.

**Comment by olifolkerd** [comment]
This is correct behaviour, i would consider it very bad UI to use a row selection column on a table where some rows are not selectable.

The selectable check was primarily intended for when using rows that are selected on click without the column.

Cheers

Oli :)

**Comment by Deepakeon** [comment]
@santor a possible workaround 
![image](https://github.com/olifolkerd/tabulator/assets/92251781/9a44c29e-8fe7-4727-b9c2-838ad6f6a5ba)
