### ISSUE TITLE
Children cell edit,dataTreeChildColumnCalcs and groupBy do not work together

### ISSUE THREAD

**Issue by verdonfly** [olifolkerd/tabulator#3686]
Hey @olifolkerd
when you change a cell in a child row, the total is not calculated correctly. This problem occurs when groupby is active.

Tabulator Info
latest 5.1.7

Working Example
https://jsfiddle.net/verdonfly/3g4udm5k/3/

To Reproduce
A step by step guide to recreate the issue in your JS Fiddle or Codepen:

right click on the first column to add a child to the row
change the total column of the new child.

![158610072-d53170a2-2db7-404e-ad06-fc9d08a27c9a](https://user-images.githubusercontent.com/49061831/161486897-6a534511-ba82-4afb-a929-b1a88ad3e9a4.png)

Expected behavior
the first total should be 103.

Additional context
if you comment the groupby the total works correctly.

![222222158610072-d53170a2-2db7-404e-ad06-fc9d08a27c9a](https://user-images.githubusercontent.com/49061831/161487009-35bffd4a-5161-42d2-b637-9508d89f0789.png)

**Comment by olifolkerd** [comment]
Hey @verdonfly 

I have just pushed a fix for this to the master branch and will include it in the next patch release in a few days.

Cheers

Oli :)
