### ISSUE TITLE
Keep classes from existing table

### ISSUE THREAD

**Issue by Pithikos** [olifolkerd/tabulator#3688]
I enjoy the library but formatting can be problematic for my use case - enhancement of a simple data report.

If I have the below table

```
<table class="benchmark-results-table">
  <thead>
    <tr>
      <th>Equipment</th>
      <th>Timing</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="metric string">SG342</td>
      <td class="metric timestamp">15:20:21.453</td>
    </tr>
  </tbody>
</table>
```

Then creating a new tabulator from that makes a very pretty table. Unfortunately the classes `metric string` and `metric timestamp` are totally removed and so is some CSS formatting that deal with coloring the values or adding some symbols.

It would be great if the classes would be left intact as to still allow easy formatting. I use `jinja2` templates to create the reports so mixing in javascript will make it really painful while keeping the classes would have simplified things greatly.

**Comment by Pithikos** [comment]
Workaround for the moment

```javascript
        // Copy classes
        var classes = Array();
        $(".benchmark-results-table").each(function(i){
          let table = Array();
          $(this).find("tbody tr").each(function(j){
            let row = Array();
            $(this).find("td").each(function(){
              row.push($(this).attr("class"))
            })
            table.push(row)
          })
          classes.push(table)
        })
        
        // .... Instantiate Tabulator ....
        
        // Re-apply classes to tabulator HTML
        $(".benchmark-results-table").each(function(i){
          $(this).find(".tabulator-row").each(function(j){
            $(this).find(".tabulator-cell").each(function(k){
              $(this).addClass(classes[i][j][k])
            })
          })
        })
        
        
```

**Comment by olifolkerd** [comment]
That wont work as a workaround on scrolling table as the virtual DOM only creates rows when they are scrolled into view.

There is no need for a work around in this case, Tabulator already provides the `cssClass` column definition class for appending classes to columns.

And as the [HTML Import Docs](http://tabulator.info/docs/5.1/data#table-options) stats you can add column definition options to your `th` tabs as attributes by prefixing them with `tabulator-`

Cheers

Oli :)

**Comment by Pithikos** [comment]
@olifolkerd OK thanks, I think I got it working :)

For anyone else running into the same, something like below seems to work fine:
```javascript
<td tabulator-cssClass="metric timestamp">
     15:20:21.453
 </td>
```

**Comment by olifolkerd** [comment]
It only need to be on the `th` tag in the header, it will be ignored on the `td` tag
