### ISSUE TITLE
paginatorDataReceived should also support object properties

### ISSUE THREAD

**Issue by liviu-vasut** [olifolkerd/tabulator#369]
When parsing remote data the current code tries to get the number of pages like this:

    this.max = parseInt(data[this.paginationDataReceivedNames.last_page]);

This only accepts a page count specified as:

    { ..., count: 4, data: [...], ... }

where the data is in response.data and the page count is in response.count. If one would like to load data from elasticsearch, for example, it would get this response:

    { ..., hits: { total: 16, ... }, ... }

where the data is in response.hits.hits and the record count is in response.hits.total. Note that no page count is returned and only the record count. This format is not supported now.
The code could be modified so that the configuration also accepts a function that takes the response and the page size and returns the page count.

**Comment by olifolkerd** [comment]
You are in luck, there is already a function available to help you there. The ***ajaxResponse*** callback lets you reformat your data into the format expected by Tabulator:
```js
$("#example-table").tabulator({
    ajaxResponse:function(url, params, response){
        //url - the URL of the request
        //params - the parameters passed with the request
        //response - the JSON object returned in the body of the response.

        return response; //return the response formatted response object to tabulator
    },
});
```

Documentation for this feature can be found in the [Callbacks Documentation](http://olifolkerd.github.io/tabulator/docs/3.0/#callbacks)

**Comment by liviu-vasut** [comment]
Well, I have read the documentation for the **ajaxResponse** but it says that the response should be an array, so that's where my confusion should have started from. Somehow, when checking the **paginationDataReceived** documentation I missed the remote server response format part, or I just did not make the connection with the **ajaxResponse**. I reviewed the documentation today and you are right, no changes were required, so sorry for the noise...

**Comment by olifolkerd** [comment]
no problem, I will see if i can update the documentation to make it a bit clearer in the remote pagination documentation what you should do.

**Comment by liviu-vasut** [comment]
Great, thanks!
