### ISSUE TITLE
headerFilter should not submit parent form on submit

### ISSUE THREAD

**Issue by lekoala** [olifolkerd/tabulator#3692]
**Describe the bug**
When typing enter on a headerfilter, it will submit the parent form

**Tabulator Info**
5.1.8

**Working Example**
https://codepen.io/lekoalabe/pen/LYedgow

**To Reproduce**
- Type something in the header filter
- Press enter
- You are redirected to the form handler

**Expected behavior**
- It should simply trigger the filter

Chrome Latest (win)

**Comment by olifolkerd** [comment]
That is the default behaviour of the form if it detects an enter key. This is just the standard enter key event propagating up the DOM, not a specific action on Tabulators part.

Tabulator deliberately does not block propagation of its events in case they are needed by anything outside of the table.

I would query why it is in a form in the first place as it is not an input element and not generating content for submission.

If you do not want the form to submit on enter then you should handle that event on the forms event bidings, this is outside the scope of tabulator im afraid.

Cheers

Oli :)

**Comment by lekoala** [comment]
@olifolkerd ah yes indeed it's not ideal it's in a form tag but that's how it is for my use case. It's easy to fix on my end so no worries :) thanks for this great script. I'm working on an integration for silverstripe.

**Comment by olifolkerd** [comment]
When you finish your integration, let us know on the discord channel. We can add a link on the website
