### ISSUE TITLE
scrollto does not scroll to the bottom of table correctly when there are large rows with many lines

### ISSUE THREAD

**Issue by parrnicholasj** [olifolkerd/tabulator#3693]
**Describe the bug**
when there are large rows with many lines in them it throws off the scrollto function when it tries to scroll to rows towards the bottom of the table

**Tabulator Info**
5.1

**Working Example**
https://codepen.io/parrnicholasj/pen/RwxQLrw

**To Reproduce**

1. Go to https://codepen.io/parrnicholasj/pen/RwxQLrw

2. may need to adjust screen to see the whole table
3. click on scroll to last row button in top left
4. table is not scrolled all the way to last row

**Expected behavior**
table should scroll to clearly show the last row

**Desktop (please complete the following information):**
 - OS: mac
 - Browser Chrome
 - Version 99

**Comment by olifolkerd** [comment]
Hey @parrnicholasj,

This is not due to their being many lines in the table, tis is due to the variable height of the rows, which can make it hard for Tabulator to calculate where exactly the row is in the table,

I will have a look and see if i can improve this functionality.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @parrnicholasj 

I have just pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)
