### ISSUE TITLE
column visible status does not persist after resize and refresh page 

### ISSUE THREAD

**Issue by Gogicool-geek** [olifolkerd/tabulator#3695]
**Describe the bug**
Collapsed columns are not showed again after resizing  and refreshing window when responsiveLayout is "collapse" and persistence feature is enabled.

**Tabulator Info**
5.1.3

**Working Example**
[https://codepen.io/gogicool-geek/pen/LYerdOK](https://codepen.io/gogicool-geek/pen/LYerdOK)

**To Reproduce**
1. Maximize web browser window 
2. Go to [https://codepen.io/gogicool-geek/pen/LYerdOK](https://codepen.io/gogicool-geek/pen/LYerdOK)
3. Narrow window in order to enable responsiveLayout "collapse" feature (see responsiveCollapse icons)
4. Refresh window
5. responsiveCollapse icons are disappeared 
6. Again maximize web browser window
7.  Hidden columns do not shown again

**Expected behavior**
After narrowing and refreshing window hidden columns should be available ether in responsiveCollapse dropdown area, or as a columns after resize browser window 

**Screenshots**
![Снимок экрана 2022-04-10 в 19 49 46](https://user-images.githubusercontent.com/54596689/162630843-27567c79-d9f1-4d27-8803-89617e28bbed.png)
After refresh window
![Снимок экрана 2022-04-10 в 19 50 57](https://user-images.githubusercontent.com/54596689/162630871-9e9945ad-e038-45e9-b4f2-c44935616bfe.png)

**Desktop (please complete the following information):**
 - OS: mac
 - Browser safari
 - Version 15.3 (15612.4.9.1.8, 15612)

**Additional context**
In order to recover back and reproduce bug again you need to remove relevant record in LocalStorage where columns status are saved.

**Comment by olifolkerd** [comment]
Yes this is expected behavior because the columns are hidden. If you are using the two modes together I would suggest that you turn of tracking column position/visibility in the persistence config
