### ISSUE TITLE
setGroupBy("field") needs 2 clicks to fire !

### ISSUE THREAD

**Issue by LebCit** [olifolkerd/tabulator#3696]
**Describe the bug**
To change the layout of a normal table to a grouped one, I'm using  `setGroupBy("field")` after a click on a button.
The function is not executed on the first click but on the second one.

**Tabulator Info**
- 5.1.8

**Working Example**
[Tabulator setGroupBy](https://codepen.io/LebCit/pen/ZEvjypa)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Visit the pen
2. Click on the button, it will not work
3. Click on the button again, it will work

**Expected behavior**
Expecting the function to fire from the first click

Thanks in advance for your time and guidance.

**Comment by bornova** [comment]
I had mentioned this in https://github.com/olifolkerd/tabulator/issues/3666#issuecomment-1069524575 but looks like the bug still exists.  As a workaround, you can set the initial `groupBy` table option to an empty array.  Ex. referencing your codepen:
```javascript
var table = new Tabulator("#example-table", {
  data: tabledata, //assign data to table
  autoColumns: true, //create columns from data field names
  groupBy: []
});
```

**Comment by LebCit** [comment]
Thank you very much @bornova
