### ISSUE TITLE
Creating table takes long time using 5.1.8 - shows instantly using 4.9.3

### ISSUE THREAD

**Issue by Martino-Martinez** [olifolkerd/tabulator#3697]
I've used version 4.9.3 with large tables (30,000 row; 35 columns). After upgrading to 5.1.8 the same table takes around one minute to be displayed. I have no clue what I am doing wrong.

      var table = new Tabulator("#table",
        {
          height: "100%",
          layout: "fitData",

          dataTreeFilter: false,
          nestedFieldSeparator: false,

          data: tableData,
          columns: tableColumns,
          index: "id",

          movableColumns: true,
          movableRows: false,

          selectable: true,
        });

Also destroying the table takes at least 30 seconds.

Can you please help?

**Comment by olifolkerd** [comment]
The most likely explanation for it taking so long is that the VItrualDOM hasnt been engaged. If you set a fixed height on the table (in pixels) do you have the same issue?

Given that you are using % height it is likely that the parent dosnt have a height set on it which is throwing off the calculations.

If that dosnt help you will need to create a JS Fiddle that demonstrates this issue as it is hard to offer advice without seeing your table in context.

Cheers

Oli :)

**Comment by Martino-Martinez** [comment]
Hi Oli -

I did some more tests. I created a table with height = 100. The table has 2 visible rows and there are 20 rows in the DOM, so that is not the issue.

However, as soon as I use frozen columns it takes long to display the table. Without frozen columns it is as fast as 4.9.3.

Hope that helps!

-- Martin

**Comment by Martino-Martinez** [comment]
Hi Oli -

thanks for letting me know. And I guess you mean 5.2 (not 4.2).

-- Martin

**Comment by olifolkerd** [comment]
Hey @Martino-Martinez 

I have just pushed a fix to the 5.2 branch that fixes the table loading time issue.

It will be included in the 5.2 release later this month.

Cheers

Oli :)
