### ISSUE TITLE
Discrepancy between setSort and getSorters

### ISSUE THREAD

**Issue by Martino-Martinez** [olifolkerd/tabulator#3698]
From documentation (http://tabulator.info/docs/5.1/sort#manage):

```
table.setSort([
    {column:"age", dir:"asc"}, //sort by this first
    {column:"height", dir:"desc"}, //then sort by this second
]);

```
getSorters:

```
[
    {
        column:column,
        field:"age",
        dir:"asc"
    },
    {
        column:column,
        field:"height"
        dir:"desc"
    }
]
```

For consistency, the fieldname in setSort should be "field" and not "column".

-- Martin

**Comment by olifolkerd** [comment]
Hey @Martino-Martinez 

It is correct in its current form.

The column option can take any of the standard [Column Lookup Options](http://tabulator.info/docs/5.1/components#lookup) of which only one of the options is the field name of the column.

Cheers

Oli :)

**Comment by Martino-Martinez** [comment]
Hi Oli -

thanks. I can see your point. Maybe this should be mentioned in the documentation on setSort(), but maybe it is mentioned and I missed it :-)

-- Martin

**Comment by olifolkerd** [comment]
Ahh yes good spot. I will improve the docs on that one.

Cheers

Oli :)
