### ISSUE TITLE
Tabulator 5.2 Released Today!

### ISSUE THREAD

**Issue by olifolkerd** [olifolkerd/tabulator#3699]
Tabulator 5.2 Released Today!

Hi Everyone, im happy to announce that i have just published the 5.2 release of Tabulator, Which is absolutely stuffed full of new features including:

- Tons of new features to help out people building their own modules
- Improved console feedback
- A Bootstrap 5 theme
- A rebuilt column resizing module with new features to help maintain column fit during resize
- Efficiency improvements to the frozen column module, to fix the slowdown since v5.0
- Mutate Link functionality to allow updating one cell to recalculate the value in another
- New internal and external events
- Customize header menu icons
- A new Popup module to allow full custom popups not just menus, checkout the header filter example!
- Fully customizable tool tips
- Access to the alert messaging system (loading spinners etc)
- Fixed row height options
- Improved luxon DateTime object handling
- Formatter updates
- Editor Updates, Including the new super powerful list editor (the successor to select/autocomplete)
- Validation Improvements
- Bug Fixes

For full details head on over to the website and checkout the release notes http://tabulator.info/docs/5.2/release

**Comment by Martino-Martinez** [comment]
Great!

This `Efficiency improvements to the frozen column module, to fix the slowdown since v5.0` is a great improvement.

Many thanks!

-- Martin

**Comment by carsonwood1** [comment]
I agree! Updating just fixed the issue I was running into with slowdowns!
Thanks!
