### ISSUE TITLE
Posibility to add formatter to headers or set custom tooltips for them

### ISSUE THREAD

**Issue by MxFulder** [olifolkerd/tabulator#37]
It's ussualy column with checkbox to select few rows to do smth with them, has checkbox in header too -  for "Select All" function.
But now, if I add this functionlity by setting column 'title' with checkbox html content. Checkbox will appear in header, but its tooltip on hover action will be same with title - inner html for this case.

**Comment by olifolkerd** [comment]
Hi Mx,

Good find! i will sort that this weekend.

Cheers

Oloi

**Comment by olifolkerd** [comment]
You can now set custom column header tooltips using the ***tooltipHeader*** parameter in the column definition array.

```js
{title:"name", field:"name", width:40, align:"center", tooltipHeader:"Users Full Name"},
```

Full documentation can be found [here](http://olifolkerd.github.io/tabulator/docs/#formatting).

**Comment by MxFulder** [comment]
Excellent, thanks!
