### ISSUE TITLE
Bug in datetime sorter

### ISSUE THREAD

**Issue by Martino-Martinez** [olifolkerd/tabulator#3701]
datetime.js, line 11 ff:

//sort datetime
export default function(a, b, aRow, bRow, column, dir, params){
	var DT = window.DateTime || luxon.DateTime;
	var format = params.format || "dd/MM/yyyy HH:mm:ss",
	alignEmptyValues = params.alignEmptyValues,
	emptyAlign = 0;

	if(typeof DT != "undefined"){
		if(DT.isDateTime(a)){
			 a = a;
		}else if(inputFormat === "iso"){
			 a = DT.fromISO(String(a));
		}else{
			 a = DT.fromFormat(String(a), inputFormat);
		}

**inputFormat** is not defined. I guess it should be **format**.

-- Martin

**Comment by Martino-Martinez** [comment]
Check here: http://tabulator.info/examples/5.2#sorters. Sorting on datetime column throws error.

**Comment by vansteen** [comment]
Same crash here.
Suddenly I got the same error using tabulator on some live data. Removing the sorter settings makes the error go away.

columns:[ 
        {.....},
        {.....},
        {
          title:"Date",
          field:"date",
          hozAlign:"left",
          sorter: "datetime",
          sorterParams: {
            alignEmptyValues:"bottom",
            format:"yyyy-MM-dd HH:mm"
          },
          formatter: 'datetime',
          formatterParams:{
            inputFormat:"yyyy-MM-dd HH:mm",
            outputFormat:"MM/dd/yyyy HH:mm",
            invalidPlaceholder:"(invalid date)",
          }
        },
      ],

**Comment by olifolkerd** [comment]
Hey Everyone, 

Totally my bad, i merged in a PR and didnt fully test it. i will have a patch release out to fix this shortly

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Release 5.2.1 is out now and resolves this issue.

Cheers

Oli :)

**Comment by nicholascarroll** [comment]
Thanks for your tabulator.js @olifolkerd

**Comment by vansteen** [comment]
Thanks a lot Oli :)
