### ISSUE TITLE
Date Sort gives Uncaught ReferenceError: inputFormat is not defined

### ISSUE THREAD

**Issue by nicholascarroll** [olifolkerd/tabulator#3702]
**Describe the bug**
Date sort does not work and error is seen in browser debug console (F12). 
`
Uncaught ReferenceError: inputFormat is not defined
`

**Tabulator Info**
version 3.6.0 via CDN
also luxon.js 2.0.2 via CDN

**Working Example**
https://jsfiddle.net/g8wrte93/1/

Data  looks like this:
`
{ name: "Mary May",  age: "1",  col: "blue",  dob: "14-Apr-1983"  },
`
Column def looks like this:
`
 {  title: "Date of Birth",  field: "dob",  sorter: "date",  sorterParams: { format: "dd/MMM/yyyy" }, headerFilter: "input" }
`

**To Reproduce**
1. Go to the jsfiddle
Try to sort by *Date of Birth*. Notice that it does not sort.

**Expected behavior**
Sort. 

**Desktop (please complete the following information):**
 - Ubuntu
 - Firefox Version 90

**Comment by olifolkerd** [comment]
This is a duplicated of #3701
