### ISSUE TITLE
5.2.1. - bug in datetime.js

### ISSUE THREAD

**Issue by Martino-Martinez** [olifolkerd/tabulator#3704]
Hi Oli -

there is an issue in datetime.js, line 20.

`a = DT.fromISO(String(b));`

**a** =... should be **b** = ...

`b = DT.fromISO(String(b));`

-- Martin

**Comment by olifolkerd** [comment]
Dam, I did a terrible job of reviewing that PR!

I will go through it with a fine tooth comb this eve and do another patch. Sorry for the bugs there

**Comment by olifolkerd** [comment]
Hey @Martino-Martinez 

I have pushed a fix for this to the master branch and will include it in the patch release later today.

Cheers

Oli :)

**Comment by Martino-Martinez** [comment]
Thanks!
