### ISSUE TITLE
An Ideal Layout?

### ISSUE THREAD

**Issue by 500Foods** [olifolkerd/tabulator#3705]
With the release of 5.2.1, I think it is awfully close to what I'd consider an ideal layout.  Yes, I totally realize that if you ask 100 people you'll get 100 ideal layout definitions.  And there are enough options that maybe I've overlooked something and we actually are there already.  Apologies for not having a better way to convey this.  A lot of screenshots would probably just muddy things up worse, and a jsFiddle isn't going to do any better if it doesn't actually do what I'm after.  Not really a bug after all.  So here goes.  Too many words, truly sorry.  

1. I'd like the columns to fill up _exactly_ the width of the table.  The tables are typically in places where the space available can be changed, like a dashboard widget, so the table changing size should cause it to be adjusted to compensate.  I can issue a redraw(true) as I know when the size of the table changes, not worried about the Observer stuff not kicking in, no worries there. And my tables don't typically have 10,000 records so most of this is instant anyway.  Tabulator is pretty fast so I'm not at all worried about calling redraw(true) any time there's any trouble at all.

2. So the best layout for this initially seems to be fitColumns.  All good.  So the columns should always fill exactly the width of the table except if either (a) the minWidth of all of the visible columns is greater than the width of the table or (b) the maxWidth of all  of the columns is less than the width of the table. No horizontal scrollbars ever except if (a) or (b).  And if (a) or (b) are not present initially, it should aggressively work against any column resizing that would lead to (a) or (b).

3. Let's assume minWidth and maxWidth are set for every column. I actually do this now just by setting both to 50 as a defaultOption for all columns.  Forces me to make sure they're set to something sensible everywhere (50 is pretty commonly used though, which is why I've set it as my default).  Any defaults would work though.

4. If a column's minWidth and maxWidth are the same value, this would deactivate the resizable option for the column as it clearly can't be resized, and under no circumstances should it ever be resized, either by the user or by any other table interactions.  It doesn't matter whether width is set as it has nowhere to go between minWidth and maxWidth.

5.   If a column's minWidth and maxWidth are not the same, then the column could conceivably be of a size in that range.  widthGrow = 1 by default, so if a width is supplied, use that as the starting point before any stretching or shrinking.  If width is not set, then let's use the width of the data for that column, somewhere between minWidth and maxWidth, and use whatever that is as the starting value for any subsequent grow/shrink instead of the missing width value.

6. Whenever a column's visibility is changed, these rules should be reapplied.  Can do this manually through redraw(true) again, no problem there.

7. After applying the width explicitly supplied, or by using the data-width calculations the columns are then fit to the width of the table.  This can be done using the widthGrow optoin to grow/shrink as is already done, logic is the same.  Default of widthGrow = 1 works well enough but having that as an option is already pretty fantastic.

8. If there is only one column that can be resized (only one column specifying resizable and all other columns having minWidth=maxWidth) then it isn't really resizable as it has nowhere to go, so resizable should be turned off.

9. If there is more than one column, then the resizing should do what your new option does - trade the difference with the next column that is also resizable.  So if you just had two resizable columns, the divider would allow you to shift the balance between the two, respecting the minWidth and maxWidth of both, but also be constrained by the width of the table.  IE, block resizing beyond the amount that would cause the columns to overflow the table. 

10. This should work the same even if there are multiple non-resizable columns between.

11. If there are more than two columns, then this rebalancing would just happen between the nearest column, not necessarily all of the resizable columns.  So resizing the first column would 'squeeze' the last column if the first and last were resizable, but there were other columns between.  But it could only be squeezed up to the last column's minWidth, at which point it would stop and not allow the table width to grow beyond the width of the table's container.

12. The same works in reverse.  If the first column is resized smaller, then the last column would be stretched  up to its maxWidth, but it would prevent you from shrinking the first column to the point where the columns couldn't fill the available space.

13. If persistence is set, this stretching and squeezing would be remembered.  At the moment if I turn on persistence, there's about a 20px gap on the right end of the table (columns don't stretch to fill) but I would have to do a jsFiddle or something to confirm as it could be something to do with some styling issues I've fiddled with over the past many months.

14. If new data is loaded, this process would be repeated with the current "squeezing" adjustments used for setting a default width if one is not already being supplied. I think you have a new option that does the resizing to fit the data when new data is loaded, but not sure what it does about any existing resizing. 

15. Most of the time, my tables are created without data, sometimes even without any columns defined. So I'd expect that adding columns would continue to be expensive, and that redraw(true) or equivalent would need to be called when columns are added or changed.

So if you made it this far, thanks very much.  I think it does 99% of this, which is already pretty cool.  Maybe just the limits on resizing beyond what the table can tolerate without breaking out the scrollbars and it might be there?

I can troubleshoot the persistence thing it if it isn't something that you're seeing.  And I can work up a jsFiddle for any of this if you think it would help, but I'm not entirely sure it would.

**Comment by olifolkerd** [comment]
Hey @500Foods 

Wow that is quite the list there, i must admit with all the info there im a a little unsure what you are looking for specifically as as you say Tabulator already does the vast majority of that list.

Could i suggest resubmitting this as an issue with a specific requirement for a new feature you would like to see on Tabulator that you feel is currently missing, one item per issue so it is possible to track updates/fixes.

Cheers

Oli :)

**Comment by 500Foods** [comment]
Yeah, sorry, that was more thinking out loud for me and not so useful for you!  Stream-of-consciousness does not make for actionable requests.  Hard to make one issue as it is just one issue - layout - and the individual pieces are interrelated.  But I will try again!
