### ISSUE TITLE
ui and data are in disorder when dragging column group

### ISSUE THREAD

**Issue by bytrix** [olifolkerd/tabulator#3706]
**Describe the bug**
ui and data are in disorder when dragging column group

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
- Open the working example [https://jsfiddle.net/ynl0zq/vhkLqf7p/](https://jsfiddle.net/ynl0zq/vhkLqf7p/)
- Drag the column group (top or sub column) to other column position

**Tabulator Info**
- 5.2.1

**Working Example**
[https://jsfiddle.net/ynl0zq/vhkLqf7p/](https://jsfiddle.net/ynl0zq/vhkLqf7p/)

**Expected behavior**
Dragging column group should not break ui.

**Screenshots**

ui broken when dragging sub-column of the column group

![image](https://user-images.githubusercontent.com/7734124/164954706-c2743679-d6dc-4e70-9001-0bfd31971950.png)

data's order not change when dragging top-column of the column group

![image](https://user-images.githubusercontent.com/7734124/164954883-9a472c5f-4941-4489-a555-216b45d359c7.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome

**Comment by olifolkerd** [comment]
Hey @bytrix 

Moving of column groups is not currently a feature, i have pushed a fix to the master branch to disable this errant functionality, which will be included in todays patch rlease and updated the docs to reflect this.

If you would like to see this functionality added to the table please raise a feature request.

Cheers

Oli :)
