### ISSUE TITLE
delay loading alert

### ISSUE THREAD

**Issue by lekoala** [olifolkerd/tabulator#3709]
Would it be possible to only display the loading alert (when using server side pagination) after a given delay (eg 0.5s) ? most if the time, if the server respond swiftly, it's not really necessary to show a big alert

**Describe the solution you'd like**
Introduce a new setting (maybe even make that a default), something like 'ajaxAlertDelay' ?

Another option would be to replace that alert altogether (or only show if the server is really slow) and simply use some kind of loading icon that would show next to the pagination

**Describe alternatives you've considered**
I've played with css animation, it works, but applies to all alerts. not ideal.

**Comment by olifolkerd** [comment]
Hey @lekoala 

Thanks for getting in touch. 

I would consider it very bad UI design to have the user waiting for any amount of time for content to load without something explaining why, it just looks like the UI has frozen in that instance.

If the data loads quickly then the loader will be barely visible anyway.

For that reason i would not be looking to include this feature in Tabulator. That being said if you want to customize your own version to add the functionality you need it should be relatively simple.

You can find the code for the data builder here: https://github.com/olifolkerd/tabulator/blob/master/src/js/core/tools/DataLoader.js

You will see the `alertLoader` function responsible for showing the alert on line 105.

Checkout the [Build Documentation](http://tabulator.info/docs/5.2/build) to see how to built your updated code into a new set of minified JS

Cheers

Oli :)

**Comment by lekoala** [comment]
Well I agree that's it needed to show activity but the alert is very invasive and i would rather have something more lightweight. I quite like how it's done in ag grid for example. But maybe it only requires a bit of css

**Comment by olifolkerd** [comment]
Each to their own, everyone has their own idea of what works for them, but in this case I will be sticking with he current functionality.

The good news is Tabulator has a full set of classes to aid with styling. You can find out more in the [Styling Docs](http://tabulator.info/docs/5.2/style)

Cheers

Oli :)
