### ISSUE TITLE
Read only edited data

### ISSUE THREAD

**Issue by firth650** [olifolkerd/tabulator#371]
Hi 
    just a quick question: Is it possible to use a function like "getData" but to only return edited cells rather than all/visible cells? (if it matters? All of my data is client side only )

Regards
Steve

**Comment by firth650** [comment]
I should have said to return only edited ROWS not cells.

**Comment by olifolkerd** [comment]
Hey,

There is no built in function for this but it should be fairly easy to add on your own.

You could use the ***cellEdited*** callback to push the row into an array that you could then iterate through when needed.

As a rough example :

```js
//hold edited rows
var editedRows = [];

//add an edited row to the list
function addEditedRow(newRow){
    var match = false;

    //make sure we dont add the same row twice
    editedRows.forEach(function(row){
        if(newRow === row){
            match = true;
        }
    });

    if(!match){
        editedRows.push(newRow);
    }
}

//get edited row data
function getEditedRows(){
    rows = [];
    
    editedRows.forEach(function(row){
        rows.push(row.getData());
    });

    editedRows=[];

    return rows;
}

///build your table
$("#example-table").tabulator({
    columns:[...],
    cellEdited:function(cell){
        //cell - cell component
        addEditedRow(cell.getRow());
    },
});
```

Let me know if that helps.

Cheers

Oli

**Comment by firth650** [comment]
Thank you.




Steve




From: Oli Folkerd


Sent: Saturday, 17 June, 11:25


Subject: Re: [olifolkerd/tabulator] Read only edited data (#371)


To: olifolkerd/tabulator


Cc: firth650, Author






Hey,




There is no built in function for this but it should be fairly easy to add on your own.




You could use the cellEdited callback to push the row into an array that you could then iterate through when needed.




As a rough example :




//hold edited rows var editedRows = []; //add an edited row to the list function addEditedRow(newRow){ var match = false; //make sure we dont add the same row twice editedRows.forEach(function(row){ if(newRow === row){ match = true; } }); if(!match){ editedRows.push(newRow); } } //get edited row data function getEditedRows(){ rows = []; editedRows.forEach(function(row){ rows.push(row.getData()); }); editedRows=[]; return rows; } ///build your table $("#example-table").tabulator({ columns:[...], cellEdited:function(cell){ //cell - cell component addEditedRow(cell.getRow()); }, });




Let me know if that helps.




Cheers




Oli

**Comment by firth650** [comment]
Hi
   I built the above code into my own tabulator but without success. I always get an "Uncaught TypeError: row.getData is not a function" reported from the console. This is from the call inside the "getEditedRows" function. 

In order to simplify the debug, I took a sample html from the Tabulator documentation, and built the above into there instead. However I still see the same error when I press on the "send email button" on my web page. I'm almost certainly making some "silly" error in both cases but I cannot find it. Could the community please help? My full page/script is below. 

Note: The sendplay.php file, which (should) send the edited Tabulator contents to a recipient simply looks like this.

<?php
    mail("myemailaddress.com","Tabulator updates",$_POST['EditedTable'],"From: myemailaddress.com");
?>

Main code follows
--------------------
<!DOCTYPE html>
<html>

<script type="text/javascript" src="js/jquery.min.js"></script>
<script type="text/javascript" src="js/jquery-ui-1.12.1/jquery-ui.min.js"></script>

<link href="css/V3.0.tabulator/tabulator.min.css" rel="stylesheet">
<script type="text/javascript" src="js/V3.0.tabulator/tabulator.min.js"></script>

<div class="feature-box-legend">Download Controls</div>

    <div class="feature-box">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 content " role="main">
          <button id="download-csv">Download Raw CSV</button>
          <button id="SendUpdate">Send Edited Table as Email</button>
          </div>
        </div>
      </div>
    </div>

<div id="example-table"></div>


<script>
//hold edited rows
var editedRows = [];

function downloadData(){
//get data from tabulator
var data = getEditedRows();
//generate header row
var csvContent = [Object.keys(data[0]).join("	")];
//generate each row of the table
data.forEach(function(row){
var rowString = Object.keys(row).map(function(e) { return row[e] })
rowString = rowString.join("	")
csvContent.push(rowString);
});
$.post("sendplay.php",{EditedTable: csvContent.join("\n")});
};


//hold edited rows
var editedRows = [];

//add an edited row to the list
function addEditedRow(newRow){
    var match = false;

    //make sure we dont add the same row twice
    editedRows.forEach(function(row){
        if(newRow === row){
            match = true;
        }
    });
    if(!match){
        editedRows.push(newRow);
    }

}

//get edited row data
function getEditedRows(){
    rows = [];
    
    editedRows.forEach(function(row){
    // Cannot get past this error
        rows.push(row.getData());
    });

    editedRows=[];

    return rows;
}


//Build Tabulator
$("#example-table").tabulator({
    height:"311px",
    columns:[
        {title:"Name", field:"name", width:150, editor:"input"},
        {title:"Progress", field:"progress", sorter:"number", align:"left", formatter:"progress", width:200, editor:true},
        {title:"Rating", field:"rating",  formatter:"star", align:"center", width:100, editor:true},
        {title:"Date Of Birth", field:"dob", align:"center", sorter:"date", editor:"input"},
        {title:"Driver", field:"car", align:"center", editor:true, formatter:"tickCross"},
    ],
    cellEdited:function(cell){
        //This callback is called any time a cell is edidted
        addEditedRow(cell.getRow());
    },
});


//define some sample data
var tabledata = [
     {id:1, name:"Oli Bob", progress:12,  rating:1, col:"red", dob:"14/04/1984", car:1, lucky_no:5},
     {id:2, name:"Mary May", progress:1,  rating:2, col:"blue", dob:"14/05/1982", car:true, lucky_no:10},
     {id:3, name:"Christine Lobowski", progress:42, rating:0, col:"green", dob:"22/05/1982", car:"true", lucky_no:12},
     {id:4, name:"Brendon Philips", progress:100, rating:1, col:"orange", dob:"01/08/1980", lucky_no:18},
     ];
//load sample data into the table
$("#example-table").tabulator("setData", tabledata);

var unediteddata = $("#example-table").tabulator("getData");
editedRows[0] = unediteddata[0];


$("#SendUpdate").click(function(){
downloadData();
});

//trigger download of data.csv file
$("#download-csv").click(function(){
    $("#example-table").tabulator("download", "csv", "data.csv");
});

</script>


</html>

**Comment by firth650** [comment]
In order to prevent my html being formatted as a web page on this submission, and thus to be legible I've swapped "<" for "^" in the text below.

Steve

^!DOCTYPE html>
^html>

^script type="text/javascript" src="js/jquery.min.js">^/script>
^script type="text/javascript" src="js/jquery-ui-1.12.1/jquery-ui.min.js">^/script>

^link href="css/V3.0.tabulator/tabulator.min.css" rel="stylesheet">
^script type="text/javascript" src="js/V3.0.tabulator/tabulator.min.js">^/script>

^div class="feature-box-legend">Download Controls^/div>

    ^div class="feature-box">
      ^div class="container">
        ^div class="row">
          ^div class="col-lg-12 content " role="main">
          ^button id="download-csv">Download Raw CSV^/button>
          ^button id="SendUpdate">Send Edited Table as Email^/button>
          ^/div>
        ^/div>
      ^/div>
    ^/div>

^div id="example-table">^/div>


^script>
//hold edited rows
var editedRows = [];

function downloadData(){
//get data from tabulator
var data = getEditedRows();
//generate header row
var csvContent = [Object.keys(data[0]).join("	")];
//generate each row of the table
data.forEach(function(row){
var rowString = Object.keys(row).map(function(e) { return row[e] })
rowString = rowString.join("	")
csvContent.push(rowString);
});
$.post("sendplay.php",{EditedTable: csvContent.join("\n")});
};


//hold edited rows
var editedRows = [];

//add an edited row to the list
function addEditedRow(newRow){
    var match = false;

    //make sure we dont add the same row twice
    editedRows.forEach(function(row){
        if(newRow === row){
            match = true;
        }
    });
    if(!match){
        editedRows.push(newRow);
    }

}

//get edited row data
function getEditedRows(){
    rows = [];
    
    editedRows.forEach(function(row){
    // Cannot get past this error
        rows.push(row.getData());
    });

    editedRows=[];

    return rows;
}


//Build Tabulator
$("#example-table").tabulator({
    height:"311px",
    columns:[
        {title:"Name", field:"name", width:150, editor:"input"},
        {title:"Progress", field:"progress", sorter:"number", align:"left", formatter:"progress", width:200, editor:true},
        {title:"Rating", field:"rating",  formatter:"star", align:"center", width:100, editor:true},
        {title:"Date Of Birth", field:"dob", align:"center", sorter:"date", editor:"input"},
        {title:"Driver", field:"car", align:"center", editor:true, formatter:"tickCross"},
    ],
    cellEdited:function(cell){
        //This callback is called any time a cell is edidted
        addEditedRow(cell.getRow());
    },
});


//define some sample data
var tabledata = [
     {id:1, name:"Oli Bob", progress:12,  rating:1, col:"red", dob:"14/04/1984", car:1, lucky_no:5},
     {id:2, name:"Mary May", progress:1,  rating:2, col:"blue", dob:"14/05/1982", car:true, lucky_no:10},
     {id:3, name:"Christine Lobowski", progress:42, rating:0, col:"green", dob:"22/05/1982", car:"true", lucky_no:12},
     {id:4, name:"Brendon Philips", progress:100, rating:1, col:"orange", dob:"01/08/1980", lucky_no:18},
     ];
//load sample data into the table
$("#example-table").tabulator("setData", tabledata);

var unediteddata = $("#example-table").tabulator("getData");
editedRows[0] = unediteddata[0];


$("#SendUpdate").click(function(){
downloadData();
});

//trigger download of data.csv file
$("#download-csv").click(function(){
    $("#example-table").tabulator("download", "csv", "data.csv");
});

^/script>


^/html>

**Comment by olifolkerd** [comment]
you have a line:
```js
editedRows[0] = unediteddata[0];
```

which is filling your ***editedRows***  array with row data instead of row component objects which is causing your issue. If you remove this line it should all work fine.

Cheers

Oli

**Comment by firth650** [comment]
Wonderful: Works like a dream: I can see that I have  a lot to learn here! 

Thanks for all the support and for Tabulator itself.
