### ISSUE TITLE
GroupBy doesn't work when using pagination

### ISSUE THREAD

**Issue by samad-kanton** [olifolkerd/tabulator#3712]
I just upgraded to Tabulator v5.2.2 and using the esm module imports but the GroupBy option not working when pagination is set.
However when using the TabulatorFull module, it works regardless. Not sure if am missing out on a module import

These are the modules I've imported and registered.

import { Tabulator, ResponsiveLayoutModule, PageModule, FormatModule, FilterModule, TooltipModule, PopupModule, EditModule, ColumnCalcsModule, ValidateModule, SortModule, InteractionModule, GroupRowsModule, SelectRowModule, ExportModule, PrintModule, DownloadModule } from '../plugins/tabulator-master/dist/js/tabulator_esm.min.js';
Tabulator.registerModule([ ResponsiveLayoutModule, PageModule, FormatModule, FilterModule, TooltipModule, PopupModule, EditModule, ColumnCalcsModule, ValidateModule, SortModule, InteractionModule, GroupRowsModule, SelectRowModule, ExportModule, PrintModule, DownloadModule ]);

**Comment by olifolkerd** [comment]
Without a js fiddle showing how your table is setup it is not possible to offer you advice.

If you believe you have found a bug please creat a new issue using the bug issue template and provide the requested information so we can help you further
