### ISSUE TITLE
Row selection in filtered table using Tickbox Formatter

### ISSUE THREAD

**Issue by Martino-Martinez** [olifolkerd/tabulator#3715]
If filters are set and you click the checkbox in the header of the Tickbox Formatter column, all rows are selected, but I think only filtered rows should be selected.

My current workaround is to use `table.getRows("active").filter(x => x.isSelected())` to get the list of selected rows that pass the filter, but I think rows that do not pass the filter should not be selected in the first place.

This also works, but I do not consider this a clean solution

```
table.on("rowSelected", row =>
  {
    const activeRows = table.getRows("active");

    if (activeRows.indexOf(row) === -1)
    {
      row.deselect();
    }
  });
```

Maybe there is a much better way to do this, but I did not find one...

-- Martin

**Comment by Martino-Martinez** [comment]
Update: 

`table.getRows("active").filter(x => x.isSelected())`

does not return selected child rows, but this works for me:

```
const activeRows = table.getRows("active");
table.getSelectedRows().filter(x => x.getTreeParent() !== false || activeRows.indexOf(x) !== -1));
```

... and I added getActiveSelectedData() to Tabulator like this:

```
Tabulator.prototype.getActiveSelectedData = function ()
{
  const activeRows = this.getRows("active");

  return this.getSelectedRows().filter(x => x.getTreeParent() !== false || activeRows.indexOf(x) !== -1).map(item => item.getData());
};

```

Not sure this is the right way to do it...

-- Martin

**Comment by olifolkerd** [comment]
This is the correct behaviour, if do deleselected all rows using the header check box then undid the filter, it would be extreemly odd, to then have only unselected the active rows.

I would be happy to look into this behaviour as a featured update for the formatter as params so people can choose what types of row are selected.

Cheers

Oli :)

**Comment by Martino-Martinez** [comment]
I agree that there are different use cases for selecting / deselecting in the table header on filtered tables. I could argue my case, because it makes perfect sense to me, but I am sure you will then be able to point out why my use case does not make sense :-)

Is my way of adding `getActiveSelectedData()` to Tabulator correct or what would be the proper way to do it?

Thanks!

-- Martin

**Comment by olifolkerd** [comment]
@Martino-Martinez  on firther inspection i had already added the ability to change the selection range to the `rowSelection` formatter, but it was only documented in the formatter documentation, not the selection documentation.

I will update the selection docs to make this clearer with the 5.3 release, but for now you can find  the info here: http://tabulator.info/docs/5.2/format#formatter-rowselection

Deselection will still deselect all selected rows, visible or not.

Cheers

Oli :)
