### ISSUE TITLE
Current selection is not visible in filter and edit select drop-downs when using Bootstrap 5 theme

### ISSUE THREAD

**Issue by cmjcharlton** [olifolkerd/tabulator#3718]
**Describe the bug**
If the Bootstrap 5 theme is used and a table is defined using the "list" editor or filter then when the select box is dropped down the currently selected option value is not visible. This is also the case for any options that you hover over. This is demonstrated with the "Gender" column in the example provided below.

**Tabulator Info**
- Which version of Tabulator are you using?
v5.2.2

**Working Example**
https://jsfiddle.net/5ar10n6z/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to (https://jsfiddle.net/5ar10n6z/)
2. Click on 'female' in the second row of the Gender column
3. See error

**Expected behavior**
I would expect to see all the possible options with the currently selected one highlighted. If I hover over an option I would expect to see that highlighted as I did so.

**Screenshots**
![image](https://user-images.githubusercontent.com/90400333/165121547-430df0c5-6e81-4ea5-b0f5-603573c91f98.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [e.g. 100.0.4896.127]

**Additional context**
This appears to be caused by the definition of table-bg changing from:
`$table-bg:                    #fff !default;`
to:
`$table-bg:                    transparent !default;`
between Bootstrap versions 4 and 5.

This is used to define `$backgroundColor` and subsequently `$rowBackgroundColor` in tabulator_bootstrap5.scss which is then used in the tabulator-edit-list class in tabulator.scss.

**Comment by olifolkerd** [comment]
Hey @cmjcharlton 

Thanks for the info, i have just pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)

**Comment by cmjcharlton** [comment]
Thanks very much for looking at this @olifolkerd. I just updated to the new release and it is indeed now working as I would expect.
