### ISSUE TITLE
Incorrect href value in CDN CSS link

### ISSUE THREAD

**Issue by bornova** [olifolkerd/tabulator#3719]
**Website Page**
http://tabulator.info/docs/5.2/install#sources-cdn

**Describe the issue**
CDN CSS link `href` is incorrect, `@` is in wrong position:
```
<link href="https://unpkg.com/tabulator-tables5.2.2@/dist/css/tabulator.min.css" rel="stylesheet">
```
Should be:
```
<link href="https://unpkg.com/tabulator-tables@5.2.2/dist/css/tabulator.min.css" rel="stylesheet">
```

**Comment by olifolkerd** [comment]
Hey @bornova 

Thanks for the info,

I will ensure this is fixed on the website this afternoon when the patch release update is deployed.

Cheers

Oli :)
