### ISSUE TITLE
renderStarted does not fire on sort

### ISSUE THREAD

**Issue by antonkatz** [olifolkerd/tabulator#3721]
**Describe the bug**
http://tabulator.info/docs/5.2/events#layout states that `renderStarted` and `renderComplete` should fire on table sort/filter. They do not. See the example.

**Tabulator Info**
5.2.2

**Working Example**
https://jsfiddle.net/bmyseakc/2/

**To Reproduce**
1. Go to fiddle
2. Open console
3. See the render events fire on table load
4. Click on headers to sort
5. See that render events do not fire

Removed the rest of the info, seems self-explanatory to me.

**Comment by olifolkerd** [comment]
Hey @antonkatz 

Thanks for the info,

I have pushed a fix to the master branch and will include it in this afternoons patch release.

Cheers

Oli :)
