### ISSUE TITLE
Trigger event on table.destroy()

### ISSUE THREAD

**Issue by Martino-Martinez** [olifolkerd/tabulator#3722]
**Is your feature request related to a problem? Please describe.**

I am keeping track on the row count in tables via some of the available events, but there is no notification if a table is destroyed.

**Describe the solution you'd like**

It would be great if an event could be trigger when table.destroy() is called.

**Describe alternatives you've considered**

I created `customDestroy()` in which I first call `table.clearData()` - this fires _dataProcessed_ - and then call `table.destroy()`.

**Additional context**

No additional context.

**Comment by olifolkerd** [comment]
There is no need for this event because a user cannot trigger the action, you must programmatically call the destroy function. The destroy function completely removes all data from the table so I am unsure why you would need to call clearData first

**Comment by olifolkerd** [comment]
Hey @Martino-Martinez 

As there has been no feedback on this i will close this issue, should you wish to persue it further, please add another comment an i will be happy to reopen.

Cheers

Oli :)

**Comment by Martino-Martinez** [comment]
Hi Oli - sorry, been busy...

I know that I do not need to call `table.clearData()` before calling `table.destroy()`, but this was the easiest way to trigger an event (`dataProcessed`) when a table is destroyed.

Yes, a user cannot trigger this action, but in my app creating and destroying tables is decoupled from the other code and is triggered by events sent from different fetch calls. Yet another component displays the number of total rows / filtered rows based on `dataProcessed` and `dataFiltered` events. Destroying a table is done when a fetch call returns null. Without an event sent on table destruction I need to manually update the component that displays the number of total rows / filtered rows.

Does that make sense to you?

-- Martin

**Comment by olifolkerd** [comment]
Hey @Martino-Martinez 

Thanks for the additional details there, Happy to add this event to the roadmap for a future release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @Martino-Martinez 

I have just pushed an update to the 5.3 branch with the new `tableDestroyed` event.  Version 5.3 should be released around early June.

Cheers

Oli :)
