### ISSUE TITLE
 can I merge rows?

### ISSUE THREAD

**Issue by Aspire0423** [olifolkerd/tabulator#3725]
![image](https://user-images.githubusercontent.com/37784957/165671675-0fc4188b-6433-430f-b2c4-b5e010489e25.png)

like this , I think this is Commonly used function；

**Comment by olifolkerd** [comment]
Nope, not at present.

Tabulator is intended as a tabluar data representation library, not a full browser spreadsheeting solution. as such this functionality is not available.

It is on the roadmap to consider for a future release, but this will not be for at least a year.

Cheers

Oli :)

**Comment by ChillarAnand** [comment]
Is there a way to achieve this with tabulator now?
