### ISSUE TITLE
Cursor based remote pagination

### ISSUE THREAD

**Issue by pate313373** [olifolkerd/tabulator#3726]
*Is your feature request related to a problem? Please describe.**
I'm considering to use tabulator for a project with a very volatile data warehouse. So offset based pagination like it is already implemented is not really an option.

**Describe the solution you'd like**
Hence, I was wondering if there are any plans to implement cursor based pagination?

**Describe alternatives you've considered**
No alternatives considered

**Additional context**
[What is cursor based pagination?](https://jsonapi.org/profiles/ethanresnick/cursor-pagination/)

**Comment by olifolkerd** [comment]
Hey @pate313373 

At the moment this isnt on the roadmap, but i would happy to consider adding this to the roadmap in future. But i would need some more details from you on how this would work in practice before i could begin

How would you envisage this working in practice? how would tabulator know what the maximum page is to display this to the user?

When the user clicks on a pagination button, how would tabulator know which value to request on the server?

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @pate313373 

Any thoughts on the above? I would be happy to add this, but as the person needing this i will need some feedback from you in order to implement this.

Im starting on the 5.3 release this week. If i dont hear back from you in the next week or so i will assume this feature is no longer needed and close this issue.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @pate313373 

I am aware of cursor based pagination and have used it on projects for work.

What i am asking you is not about the theory of the interaction, but how you see this working in practice with Tabulator with the challenges i have outlined above.

This is something i would be happy to add, but it is not a priority so i would be looking for some clarity of thought from you as to how this should actually function. As the dev making the request, you must have thought through how you would like to see it work in practice and this is what i am looking for here. As the person looking for this functionality, how would YOU like to see it work in reality

How would you envisage this working in practice? how would tabulator know what the maximum page is to display this to the user?

When the user clicks on a pagination button, how would tabulator know which value to request on the server?

Cheers

Oli :)

**Comment by olifolkerd** [comment]
I will close this off then if you don't have any thoughts on the questions asked.

Thanks for your interest in Tabulator

Oli
