### ISSUE TITLE
Frozen column support with horizontal virtual dom

### ISSUE THREAD

**Issue by blankbadge** [olifolkerd/tabulator#3727]
Hi Oli,

Great library!  Thanks so much for all of your time and energy invested in it.  

Ever since I saw you make reference to plans for horizontal virtual dom support in v5.0, I've been very excited to try it out as I'm one of the users who has some applications that require a large number of columns, and I've noticed the performance issues that appear when using tables of more than about 20-30 columns.

I wasn't able to try it in v4.8 because of the release notes about lack of frozen column support -- all of my tables use both frozen columns and frozen rows.  I recently updated to 5.2 and tried flipping on the horizontal vdom feature to see if frozen column support is added with the more robust horizontal vdom support in that release.  But I see a console message indicating it is not yet available:

     "Horizontal Virtual DOM is not compatible with frozen columns"

So this issue is for the purpose of tracking addition of that feature.  I didn't provide a testcase as I know you are familiar with the issue already, but do let me know if you'd like an example.  Thanks!

**Comment by olifolkerd** [comment]
Hey @blankbadge 

Thanks for getting in touch. Glad to hear you are interested in this feature. 

This is on the roadmap for this year but won't be out for a few months yet. As this is already on the road map I will close this issue as I don't really want to crowd out the issue list with documented coming features. It is more of a Todo list for me than anything.

Keep an eye out in the discord channel for anouncments of when this feature is released

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @blankbadge 

You will be happy to hear this functionality is now available as of release 5.4.

Cheers

Oli :)

**Comment by blankbadge** [comment]
Thanks, Oli!  That's great news.  I need to find some time soon to migrate
to 5.4 and try it out.  Appreciate all of your hard work.

-james
