### ISSUE TITLE
Performance issues when toggling visibility of many columns

### ISSUE THREAD

**Issue by blankbadge** [olifolkerd/tabulator#3728]
I am encountering an issue with tables containing larger numbers of columns.  The performance when toggling the visibility of columns (col.show(), col.hide(), or col.toggle()) degrades with larger number of columns.  I was expecting a fixed runtime to show/hide each column, for example 1ms per column.  But what I find is that the more columns, the more time each column takes to toggle (it might instead take 10ms per column with more total columns).

This fiddle shows the issue.  You can change the numCols variable at the beginning of the script to test with different number of columns.  Console messages are printed which show the amount of time it takes to toggle visibility of each column.  This is only an issue when visibility actually toggles.  If I call col.hide() on an already hidden column, the runtime is basically zero.

https://jsfiddle.net/blankbadge/w60ychzo/

In my testing, the runtime per column is:

- 5 columns: 1.20ms (6ms total)
- 10 columns: 2.10ms (21ms total)
- 20 columns: 5.10ms (102ms total)
- 40 columns: 9.97ms (399ms total)
- 60 columns: 17.45ms (1047ms total)
- 80 columns: 27.34ms (2187ms total)
- 100 columns: 33.12ms (3312ms total)

As you can see, increasing columns from 5 to 100 (20x more columns) results in a 500x+ increase in runtime to toggle the column visibilities.

I've also observed that the runtime is highly dependent on number of rows as well, even with vertical virtual dom enabled.  Is that expected?  For example, with five columns the runtime per column for toggling visibility is shown below.  In this case, the scaling is better (50x more rows is a 20x increase in runtime to toggle column visibility), but I would have thought that perhaps the number of rows wouldn't matter once most of them are prevented from rendering with the virtual dom.

- 10 rows: 1.00ms
- 20 rows: 1.40ms
- 50 rows: 3.00ms
- 100 rows: 4.80ms
- 200 rows: 9.00ms
- 500 rows: 20.20ms

This becomes a performance issue for my application because I'm allowing the user to toggle visibility of any of the columns, and they might change visibility on dozens of columns at one time.  Upon doing so, there can be a delay of ten seconds or longer to rerender the table if working with a table containing 20-30 columns and many rows.

I have tried to avoid the issue using blockRedraw() and restoreRedraw(), but that seems to have no effect when it comes to toggling column visibility.

Expected behavior is that runtime to toggle visibility of a column is not a function of the total number of columns.  i.e. if five columns take 1ms per column to hide (for a total of 5ms), then I would hope 100 columns would take about 100ms (100 * 1ms) to hide the columns, or something closer to a fixed runtime per column.

Tested using Tabulator v5.2.2 in Chrome 101.0.4951.41 on a Windows 10 desktop machine.

Thanks very much for all of your work on this wonderful library!

**Comment by olifolkerd** [comment]
This is happening because you are not using the Virtual Dom in your table setup. To rnguage the vertical virtual Dom you must define a height on your table. At that point only the visible rows are rendered speeding up render times dramatically.  If you have a large number of columns you should use enable the virtual rendered for the columns as well which will remove the performance degredation you are seeing there

**Comment by blankbadge** [comment]
Hi Oli,

Thanks for the feedback.  Regarding the performance changing with number of rows, I defined a height to enable the vertical virtual dom (failed to do that initially in my testcase, sorry about that).  In that case, I see consistent time to show/hide columns once the rows exceed the virtual dom buffer.  So that looks good -- no problem related to the number of rows.

But the main issue I was reporting is the reduced performance to show/hide columns with larger number of columns, I still see the issue even with the horizontal virtual dom enabled.

I updated the testcase with a variable at the top renderHorizontal that is set to either "virtual" or "basic" and passed to Tabulator.  So you can change that variable as well as the numCols variable to run it with different number of columns.

https://jsfiddle.net/blankbadge/w60ychzo/

Here is some profiling of runtime per column to toggle visibility, swept across different column counts.  I ran with both basic and virtual horizontal rendering.  I set a fixed width on the table (is it necessary for enabling the horizontal virtual dom?  I didn't see it in the docs, but I set it just to be safe).

|Columns|Basic|Virtual|
|---|---|---|
|5|1ms|2.2ms|
|10|1.5ms|4.1ms|
|20|3.2ms|8.2ms|
|40|8.2ms|14ms|
|60|15ms|19ms|
|80|23ms|25ms|
|100|34ms|32ms|

This shows that horizontal virtual dom is not helping with this issue.  It still shows a pattern of increasing runtime per column when showing/hiding larger number of columns.  In most cases, this is slower with the virtual dom than with the basic dom.  It's only when it gets to 100 columns that virtual dom is performing faster.  Which I can understand -- at a smaller number of columns, there will be some overhead to using virtual dom but no benefit since standard dom can render it fast enough.  

But regardless, the same trend is there which makes toggling column visibility on wide tables perform very slowly.  5 columns runs in only 5-10ms, but 100 columns takes 3+ seconds, and that scales even worse at 1000 columns (runs so slow that the browser thinks the webpage has hung).

thanks,
blankbadge

**Comment by blankbadge** [comment]
Hi Oli,

Not sure if you see the new comments on closed issues.  Was curious about your feedback with my latest comments that enabling horizontal vdom as you suggested did not help the performance issue with toggling visibility of columns.  It actually slowed it down further.  Do you see this one as a valid issue?

Thanks!
blankbadge
