### ISSUE TITLE
Opening a new window on clickable rows

### ISSUE THREAD

**Issue by Sm00g15** [olifolkerd/tabulator#373]
Hey Oli, 

Is there another way to open rows in a new window upon clicking?  I toyed around with the last code you sent to try and get it working but no dice.

**Comment by olifolkerd** [comment]
Hey,

The below code has been tested on chrome and works.

Im afraid there is no universal solution to this, it is up to the browser to choose if it opens a new tab or window:

```js
$("#example-table").tabulator({
    columns:[...],
    rowClick:function(){
        window.open("https://www.bbc.co.uk");
    },
 });
```

If you run into difficulties could you be a bit more specific about the issues you have with the sample code.

Cheers

Oli

**Comment by Sm00g15** [comment]
Ahhh, makes sense, I was using rowClick as a separate function. And cool, thank you Oli.
