### ISSUE TITLE
"Select All" checkbox doesn't respect `selectable: 1`

### ISSUE THREAD

**Issue by sybrenstuvel** [olifolkerd/tabulator#3730]
**Describe the bug**
When limiting the number of selectable rows with the `selectable: 1` option, the "Select All" checkbox doesn't respect this and still selects all rows.

**Tabulator Info**
- 5.2.2

**Working Example**
https://jsfiddle.net/drSybren/tny6bzc0/

This takes the [Quick Start example](http://www.tabulator.info/docs/5.2/quickstart) and adds a new column for row selection checkboxes as described in the [Formatter: Row Selection](http://tabulator.info/docs/5.2/format#formatter-rowselection) section:
```javascript
{ formatter: "rowSelection", titleFormatter: "rowSelection", hozAlign: "center", headerHozAlign: "center", headerSort: false },
```

**To Reproduce**
1. Go to https://jsfiddle.net/drSybren/tny6bzc0/
2. Click on Run.
3. Click on some of the rows, and see that every click will select that row and deselect the previously selected one, as expected.
4. Click on the "select all" checkbox at the top of the row of checkboxes.
5. See that all checkboxes are checked, and all rows are selected.

**Expected behavior**
I'd expect the selection count limit to be respected. Since that violates the "select all" concept and thus has some issues, one of these options I'd find acceptable for sure:
- With the `selectable: N` option, select the first `N` rows only.
- Always limit the checkbox functionality to deselecting everything, so whenever anything is selected, clicking it will deselect, and otherwise do nothing.

**Screenshots**
![image](https://user-images.githubusercontent.com/1092128/165931373-60c1ad6f-36c2-4251-9db5-bb67f8ff399b.png)

**Desktop (please complete the following information):**
 - OS: Kubuntu 20.04
 - Browser: Firefox
 - Version: 99.0

**Comment by sybrenstuvel** [comment]
I would at least expect a warning in the documentation about this. The docs for `selectable: number` don't mention that there are still ways to select more than that. The row selection header documentation also doesn't mention that it won't adhere to the maximum number of selected rows. If not a bug in the software, I do feel that this is an issue in the documentation.

**Comment by Martino-Martinez** [comment]
Hi Oli - is there a way to intercept the header "select all" event?

**Comment by olifolkerd** [comment]
There is no such event, you are welcome to build a custom header select formatter that works in the way you like.

The code for built in one can be found here: https://github.com/olifolkerd/tabulator/blob/master/src/js/modules/Format/defaults/formatters/rowSelection.js

Cheers

Oli :)
