### ISSUE TITLE
Frozen columns: only last frozen column can be resized

### ISSUE THREAD

**Issue by Martino-Martinez** [olifolkerd/tabulator#3731]
**Describe the bug**

- When using more than one frozen column (e.g., first three columns are frozen) only the last of the frozen columns can be resized.

**Tabulator Info**

- 5.2.3

**Working Example**

- https://jsfiddle.net/o9bp3n1z/

**To Reproduce**

- Try to resize first column: _not possible_
- Try to resize second column: _not possible_
- Try to resize third column: _**possible**_

**Expected behavior**

- All frozen columns can be resized

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Browser: Chrome
 - Version: 100.0.4896.127

**Comment by olifolkerd** [comment]
Hey @Martino-Martinez 

Thanks for the info, i have just pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)

**Comment by Martino-Martinez** [comment]
Thanks. Works like a charm.
