### ISSUE TITLE
Tooltip is visible after navigating to new URL

### ISSUE THREAD

**Issue by etomanon** [olifolkerd/tabulator#3733]
**Describe the bug**
I redirect users to different URL when they click on a row. The cell has also the default tooltip.
When they hover over the cell => tooltip is visible => they move the cursor a little (but cursor stays over the cell) => tooltip is hidden because they moved the cursor a little => user click on cell and is redirected to the new URL (page without any table) and the tooltip is visible again (I guess because they stopped moving the cursor for a moment before they clicked).

Is it possible to remove all tooltips programmatically?
The tooltip disappears when I click somewhere on the new page. However, when I try to dispatch the click / mousedown events in javascript the tooltip is still visible => I must click with my mouse manually :(

**Tabulator Info**
5.2.3

**Comment by olifolkerd** [comment]
Hey @etomanon 

If you want to report a bug, please use the [Bug Issue Template](https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Possible+Bug&template=bug_report.md&title=).

You must provide a link with a JS fiddle that demonstrates the issue. Without seeing how your table is setup, it is not possible for us to advise on a solution or work through where the issue might be.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @etomanon Im afraid without an example that replicates this behaviour i will be unable to help you. I will close this issue for now. If you would like any assistance please provide a link to a JS Fiddle.

Checkout the [Bug Reporting Guide](http://www.tabulator.info/community/bug) for more details.

Cheers

Oli :)
