### ISSUE TITLE
Built-in min/max column filter

### ISSUE THREAD

**Issue by ingebert** [olifolkerd/tabulator#3739]
It would be great to be able to set a value range filter (min max) as a built-in filter function, like in the example ('Progress' column):
http://tabulator.info/examples/5.2#filter-header

This came up by using Tabulator in Panel library and adding this functionality would enable us to pass this directly as a parameter:
https://discourse.holoviz.org/t/dynamic-column-name-in-add-filter-method-of-tabulator/3669/3
Thanks!

**Comment by olifolkerd** [comment]
There are already greater than and less than header filter functions available.

Look for the headerFilterFunc column definition in the filter docs: http://tabulator.info/docs/5.2/filter#header
