### ISSUE TITLE
3.1 branch : Ctrl Home: empty space before first row

### ISSUE THREAD

**Issue by michaelongithub** [olifolkerd/tabulator#374]
Hi Oli

congrats, much improved. The only bug so far in my very quick test (the faker test i sent you):
Generate Grid
Klick into grid
Ctrl End: somtimes last row not in visible area, but after scroll coming.
Ctrl Home: somtimes blank area before first row, or no rows visible. After some scrolling coming again.

But quite smooth now, And always all rows rendered

Cheer,  Michael

**Comment by olifolkerd** [comment]
Hey Michael,

Thanks for the feedback, i have just pushed a commit to 3.1 to fix the blank areas at the start and end of the table.

The last row not being visible all the time is to do with the way the table adaptably adjusts the scroll height of the table to cope with the changing height of rows, it appears that when you press "End" the browser just scrolls to what ever the end was at the point you pressed the button, if the end changes during the scroll it dosnt notice.

I think i have a way around this but it will probably have to wait to version 3.2 now.

Cheers

Oli

**Comment by michaelongithub** [comment]
Hi oli
tested, ok now.
And: Even IE 11 is with your 3.1 relatively acceptable, really kudos. Initialisation even acceptably fast. everything rendered ok. Of course sometimes slightly sluggish when scrolling, but that is to be expected with the general bad rendering of IE 11.
Thanks again for Your work.
Cheers, Michael
