### ISSUE TITLE
Bootstrap 5 theme: layout wrong for table-sm if bootstrap CSS is included

### ISSUE THREAD

**Issue by Martino-Martinez** [olifolkerd/tabulator#3740]
**Describe the bug**

- the layout for **table-sm** is wrong if the bootstrap CSS is included

**Tabulator Info**

- 5.2.4

**Working Example**

- https://jsfiddle.net/90n3y84s/ (without bootstrap CSS)
- https://jsfiddle.net/69canht2/ (with bootstrap CSS)

**To Reproduce**

- Look at the two examples

**Expected behavior**

- Layout is correct

**Screenshots**

- Layout Correct

![layout-correct](https://user-images.githubusercontent.com/103148068/167421061-40f545b3-f519-4b37-b138-0359758cdb04.PNG)

- Layout wrong

![layout-wrong](https://user-images.githubusercontent.com/103148068/167421101-19f25bc0-9c64-4835-bda7-ee6506f5ef2e.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 100.0.4896.127

**Comment by olifolkerd** [comment]
Hey @Martino-Martinez 

I have pushed a fix for this to the master branch and will include it in this weekends patch release.

Cheers

Oli :)
