### ISSUE TITLE
dataChanged should be triggered after clearData()

### ISSUE THREAD

**Issue by Martino-Martinez** [olifolkerd/tabulator#3743]
**Describe the bug**

- no `dataChanged` event after `clearData()`

http://tabulator.info/docs/5.2/events#data

> The dataChanged event is triggered **whenever the table data is changed**. Triggers for this include editing any cell in the table, adding a row and deleting a row or updating a row.

Removing all data via `clearData()` is in my opinion covered by `whenever the table data is changed`

**Tabulator Info**

- 5.2.4

**Expected behavior**

- `dataChanged` event is triggered after `clearData()`

**Screenshots**

![dataChanged event](https://user-images.githubusercontent.com/103148068/167668610-77072a6e-d5eb-4a2e-8fe9-8e5ca69f16b8.PNG)

**Comment by olifolkerd** [comment]
Hey @Martino-Martinez 

The `dataChanged` event is intended for when an individual row has been updated, it is not called when events globally replace data, such as the `setData` and `clearData` functions, in these cases you should be looking for the `dataProcessed` events.

Cheers

Oli :)
