### ISSUE TITLE
Trigger a row toggle event in a tree structure

### ISSUE THREAD

**Issue by jdessaint** [olifolkerd/tabulator#3744]
*Is your feature request related to a problem? Please describe.**
I would like to trigger the toggle event in a Tree Structure. For example, my goal is to save the tree status after some navigations in the app. When I return to the page which contain the tree, it rebuilds according to its old state. I didn't found any solution to achieve this.

**Describe the solution you'd like**
It's possible to add a TreeStructure's callback like that ?

```
table.on('treeToggle', (e, row) => {
  /** Example of that i would like to do **/
  row.getData().expand= !row.getData().expand;
});
```

or better, directly in table config :

```
var table = new Tabulator("#example-table", {
    dataTree:true,
    dataTreeStartExpanded:function(row, level){
        return row.getData().collapse;
    },
    dataTreeOnToggle:function(row, level, onExpand){
        // onExpand is a boolean which means if we are onExpand state or onCollapse state
        row.getData().expand= !row.getData().expand; // For my example
    }
});
```

**Describe alternatives you've considered**
I tried to use the `rowClick` event but my row expand/collapse only when I click on the tree button and I want to keep this behavior.

Thanks in advance.

**Comment by olifolkerd** [comment]
Hey @jdessaint 

These already exist, checkout the [Event Docs](http://tabulator.info/docs/5.2/events#tree)

Cheers

Oli :)
