### ISSUE TITLE
Header list filter with option multiselect triggers error

### ISSUE THREAD

**Issue by lekoala** [olifolkerd/tabulator#3745]
**Describe the bug**
When setting the option multiselect to true, there is an error 'List.js:73 Uncaught TypeError: this.initialValues.join is not a function'

**Tabulator Info**
5.2.4

**Working Example**
https://codepen.io/lekoalabe/pen/PoQPYVp

**To Reproduce**
go to the codepen and uncomment the line 14, on reload the table fails and throw the error.

**Expected behavior**
The list is displayed

**Additional context**
I tried various type of ways for values (just values, key/values, value/labels ...)
I also tried with an array as empty or default value, but that doesn't help

I think the issue is simply that the script expects the initialValue to be an array with multiselect true when clearly this is not always the case.

**Comment by lekoala** [comment]
happy to help or propose a PR if needed :)

**Comment by lekoala** [comment]
https://github.com/olifolkerd/tabulator/pull/3753

**Comment by olifolkerd** [comment]
Hey @lekoala 

I have pushed a fix for this to the master branch and will include it in the next patch release.

Cheers

Oli :)
