### ISSUE TITLE
List Editor does not allow empty

### ISSUE THREAD

**Issue by robinp456** [olifolkerd/tabulator#3746]
### Description
The new list editor (with autocomplete) is not working correctly for empty inputs. If I reset the Input to the empty input and press enter the data is not updated (the value is not set to empty). However, it works if I set the input empty and pressing tab, or if I click outside of the input field.
--> The cell edit callback is not called when pressing enter with an empty input

Link to [fiddle]( https://jsfiddle.net/u6L8eao2/30/) 
#### To Reproduce:

1. Open [Fiddle]( https://jsfiddle.net/u6L8eao2/30/) 
2. Click on the Cell in the name column
3. Set Input empty (delete input)
4. Press enter

#### Expected Behaviour:
The cell is updated to the empty value

**Comment by olifolkerd** [comment]
Hey @robinp456 

That seems to work perfectly for me in the JS Fiddle, Have you got a cached copy of the source in your browser?

Which browser are you using?

Cheers

Oli :)

**Comment by robinp456** [comment]
Hey @olifolkerd ,

Thanks for the reply, unfortunately it is not due to the cached browser. I tested it on chrome and edge, in both cases it doesn't work. Did you make sure to confirm the empty input with **enter**? Because it works as expected if you press tab or click outside of the box. But it doesn't if you confirm the choice with enter.

Best regards
Robin

**Comment by olifolkerd** [comment]
Hey @robinp456 

Thanks for the feedback, i see what you mean, i will include a fix for this in the next patch release.

Cheers

Oli :)

**Comment by robinp456** [comment]
Hey @olifolkerd,

Thanks a lot :) Btw great work with Tabulator, I really appreciate it :)

Greetings

**Comment by olifolkerd** [comment]
Hey @robinp456 

I have pushed a fix for this to master and will include it in sundays patch release.

Cheers

Oli :)

**Comment by robinp456** [comment]
Hey @olifolkerd,

Nice, thank you! works as expected :)

Best regards,
Robin
