### ISSUE TITLE
Frozen columns: still issues when one than one column is frozen

### ISSUE THREAD

**Issue by Martino-Martinez** [olifolkerd/tabulator#3747]
**Describe the bug**

- See #3731
- Bad experience when more than one column is frozen

**Tabulator Info**

- 5.2.4

**Working Example**

- https://jsfiddle.net/mco6y2ap/

**To Reproduce**

- Open jsFiddle
- Move mouse slowly from column 1 to column 2 in row 1
- Resize pointer appears on the column divider, disappears, and appears again when moving over the "4" in "84" in row 1, column 2
- This does not happen when moving mouse from column 2 to column 3
- Not able to resize column 3 ("Gender")
- Move scrollbar completely to the right
- Not able to resize column 1 nor column 2, but now able to resize column 3

- Refresh jsFiddle
- Move scrollbar to the right until left border of column "Favourite Color" is roughly in the middle of column Gender (of course you cannot see the left border, because the first three columns are frozen and the left border of this column is below column Gender)
- Move mouse roughly in the middle of border Gender (where left border of column Favourite Color should be)
- A resize handle will appear and you can resize column Rating (which is left of column Favourite Color

**Comment by olifolkerd** [comment]
Hey @Martino-Martinez 

All of the resize handles seem to be working perfectly in that example for me. Maybe your browser has cached an old version of the CSS?

What browser are you using?

Cheers

Oli :)

**Comment by Martino-Martinez** [comment]
Hi @olifolkerd -

I am using Chrome 101.0.4951.64 on Windows 10.

Here is a new Fiddle using 5.2.5: https://jsfiddle.net/nkre9gvx/

- Try resizing column Gender - it does not work
- Resize column Name
- Now you can also resize column Gender

- Refresh Fiddle
- Scroll right
- Resize  column Rating
- Scroll left
- Cannot resize column Gender
- Grab resize handle near left border of column Gender
- This will resize column Gender, not - as you would expect - column Progress

Resizing the three frozen columns works from time to time, but horizontal scrolling and resizing "something" else can brake it. I cannot detect a pattern...

-- Martin

**Comment by olifolkerd** [comment]
Hi Martin

Resizing the gender column is working just fine for me straight away on page loading and after scroll, not having a problem resizing any of the columns in your fiddle at any point i'm afraid.

Sorry

Oli

**Comment by Martino-Martinez** [comment]
https://user-images.githubusercontent.com/103148068/171006052-c3338f73-72c9-4976-8bc7-c752978251a6.mp4

**Comment by olifolkerd** [comment]
Yeah, im literrally unable to recreate your video, i have now tried it on 3 different devices and several different browsers. not sure what to say

**Comment by Martino-Martinez** [comment]
From my past experience: I am sure there is a bug somewhere, but you are convinced everything is right. Once you find the bug, it is so obvious and you are wondering why you didn't see it before...

But I understand it is hard trying to fix something when it is not broken for you...

**Comment by olifolkerd** [comment]
Yeah, I'm not saying it isn't broken. I'm very open to their being an issue
but as you say if I can't reproduce it I can't start to fix it.

Cheers

**Comment by mhotsiy** [comment]
I’m experiencing the same issue on my end. After performing horizontal scrolling, I encounter the same problem as shown in the video @Martino-Martinez sent when I try to change the column width. So, guess this should be reopend and review one more time. 

Thanks

ENV:
Chrome 127.0.6533.99, 
"@types/tabulator-tables": "^6.2.3",
"tabulator-tables": "^6.2.5"
