### ISSUE TITLE
freetext set to true ignored (with autocomplete set to true)

### ISSUE THREAD

**Issue by groucho86** [olifolkerd/tabulator#3748]
Column editor set to list with autocomplete and freetext set true is rejecting user's freetext input. 

Running tabulator 5.2.4.

Example:
https://jsfiddle.net/quav0eor/

To reproduce:
Type "sss" in name field and it will not be accepted.

**Comment by olifolkerd** [comment]
Hey @groucho86 

Seems to work perfectly for me in the JS Fiddle, i can type anything i like, click or tab out the cell and it saves.

Cheers

Oli :)

**Comment by groucho86** [comment]
Hi Oli,
Maybe it's a Mac OS specific bug? Hitting "enter" after typing in the freetext rarely works, but clicking outside does. If I use the mouse once, freetext behaves better.

Attaching screen recording where I use the onscreen keyboard to demonstrate

https://user-images.githubusercontent.com/6825568/170705448-787a8544-89e3-45ac-b05b-18fa7ad45f96.mov

**Comment by olifolkerd** [comment]
Hey @groucho86 

I think this is specifically an issue with using  the enter key. that detail was missing from the bug report.

Please make sure you fill in all the fields on the bug report template, including the step by step guide, there are many ways to do the same thing and without the step by step instructions it is hard to replicate

I will have a look into this for the next patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @groucho86 

I have pushed a fix for this to the master branch and will include it in sundays patch release.

Cheers

Oli :)
