### ISSUE TITLE
dataFiltered not called anymore when not filtered

### ISSUE THREAD

**Issue by MarcFlynn** [olifolkerd/tabulator#375]
With Tabulator 2.11, the dataFiltered callback was called:
1. when the data are refreshed (setData called)
2. when the user enter something in a filter
3. when the user empty the filters

I used this callback to display the number of rows (when filtered or not).

With Tabulator 3.0, it is only called on case 2.
I can easily workaround for case 1, but I don't know how to do for case 3.
Can you recover the old behavior or give me a workaround ?

**Comment by olifolkerd** [comment]
Hey,

You are correct, the ***dataFiltered*** callback is now only called when data is actually filtered.

I would be happy to make some tweaks to the system, could you give me an example usage case of what you are trying to achieve so i can better understand what you need.

Cheers

Oli

**Comment by MarcFlynn** [comment]
Hi Oli,
What a fast reply !
My use case is that I use paging and I display the number of row aside the table.
When the user enter some filtering, the callback is triggered so I can refresh the counter.
When the user clear the filters, the callback is not triggered so I cannot refresh the counter.
If this is not easy to fix, I can run a kind of timeout loop to refresh the counter periodically.
I switched from 2.11 to 3.0 because the a some very nice stuffs in 3.0, such as the column move and resize with callbacks, so I can save the prefered column layout in the users preferences.
Kind regards,
Marc

**Comment by olifolkerd** [comment]
Hey Mark,

No problem, i will add a filtersCleared callback into tomorrows 3.1 release :)

Oli

**Comment by MarcFlynn** [comment]
It would be perfect !
This is not so urgent, please take your time.
Thanks
Marc

**Comment by olifolkerd** [comment]
Looking into it a bit further, i can see why it would be useful for ***dataFiltered*** to be triggered when there is no filter set.

I have just pushed an update to the 3.1 branch with this change on.

Cheers

Oli

**Comment by MarcFlynn** [comment]
Pretty cool. I get my counter back.
Thank you Oli
Tabulator is a killer.
