### ISSUE TITLE
Unable to paste clipboard data when there are column groups

### ISSUE THREAD

**Issue by groucho86** [olifolkerd/tabulator#3750]
Unable to paste data back into table when there are column groups, despite clipboardCopyConfig having columnGroups set to false.

tabulator 5.2.

https://jsfiddle.net/gpynmrve/

1. Copy clipboard data (including header)
2. Paste clipboard data
3. The result is a misaligned paste where tabulator doesn't understand the header was included.

I think the issue stems from defaultPasteParsers looking at this.table.columnManager.columns and not distinguishing column groups from columns.

(An absolutely amazing tool, thank you so much.)

**Comment by olifolkerd** [comment]
Hey @groucho86 

This is not an available feature in Tabulator due to the complexities in interpreting how many levels of grouping there are in the pasted data.

As stated in the docs:

> Column Groups Parsing - It is worth noting that if you include column group headers in your output data it will not be possible to paste that data back into Tabulator. The paste parse functions can only handle the actual column headers or no headers.

Cheeers

Oli :)

**Comment by groucho86** [comment]
Thanks Oli. My understanding of the doc was that it could work as long as "columnGroups" was set to False and columnHeaders set to True.

**Comment by olifolkerd** [comment]
Hey @groucho86 

Im afraid not, the issue is that there is no way to Tabulator to determine where the header rows end and the data rows begin, so it just assumes that the top row is the columns and works from there.

Cheers

Oli
