### ISSUE TITLE
bootstrap 5 theme dist file contains function

### ISSUE THREAD

**Issue by lekoala** [olifolkerd/tabulator#3763]
**Describe the bug**
The css theme file contains invalid calls to theme-color-level

**Tabulator Info**
5.2.4

**Working Example**
https://github.com/olifolkerd/tabulator/blob/ef7485e98ce1d6184c69867b5e86db9dac909b86/dist/css/tabulator_bootstrap5.css#L1477-L1479

**To Reproduce**
Simply see the file

**Expected behavior**
this is probably due to
https://github.com/olifolkerd/tabulator/blob/master/src/scss/themes/bootstrap/functions5.scss
missing the theme-color-level function
it's in the bs4 version
https://github.com/olifolkerd/tabulator/blob/master/src/scss/themes/bootstrap/functions4.scss

**Comment by olifolkerd** [comment]
Hey @lekoala 

Thanks for the headsup,

I have pushed a fix for this to the master branch and will include this in the weekends patch release.

Cheers

Oli :)
