### ISSUE TITLE
HIdden columns cause unwanted horizontal scroll bar

### ISSUE THREAD

**Issue by Sulhrive** [olifolkerd/tabulator#3768]
**Describe the bug**
If the column definitions contain columns with the "visible:false" setting the table will be rendered in such a way that it now has a horizontal scroll bar.  In looking at the dom, i could see that the hidden column(s) are added with display:none.  If you delete these from the dom directly, the scrollbar goes away. 
**Addendum**:  You actually have to delete the extra resize handles, not the hidden columns themselves.

**Tabulator Info**
- 5.2.4
**Working Example**
https://codepen.io/bcostello/pen/RwQgxoJ

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. the two tables are use the same data, the bottom one has the last column hidden
2. notice that the bottom table is scroll-able horizontally

**Expected behavior**
There should be no scroll bar as there is no "visible" data outside the viewable area.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: safari, chrome, firefox

**Comment by olifolkerd** [comment]
Hey @Sulhrive 

I have pushed a fix for this to the master branch and will include it in this weekends patch release.

Cheers

Oli :)
