### ISSUE TITLE
headerDblClick and headerClick callbacks firing two events

### ISSUE THREAD

**Issue by creativecontrol** [olifolkerd/tabulator#3769]
**Describe the bug**
`headerDblClick` and `headerClick` callbacks are firing two events which means they can no longer toggle a state; as the state toggles and toggles back.

**Tabulator Info**
Recently upgraded from v4.9 to v5.2. This bug occurs in version 5.2.

**Working Example**
https://codepen.io/creativecontrol/pen/bGLRLqw

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://codepen.io/creativecontrol/pen/bGLRLqw
2. Open the console at the bottom left
3. Double click on the `Rack Info` header
4. Look at the Console to see the callback is triggered two times.
5. To see the same issue with `headerClick` comment out the `headerDblClick` callback definition and uncomment the `headerClick` definition.

**Expected behavior**
The expected behavior (as worked in v4.9) is a callback will be triggered one time. In the example this should cause the `Rack Info` group to collapse down to a single column by hiding the other child columns. 

Here is a working example ( same code as above) using Tablulator v.4.9
https://codepen.io/creativecontrol/pen/XWZgZYP

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian Linux, Mac OS
 - Browser: Chrome
 - Version: various v100+

**Comment by olifolkerd** [comment]
Hey @creativecontrol 

Thanks for the headsup.

I have pushed a fix for this to master and will include it in this weekends patch release.

Cheers

Oli :)
