### ISSUE TITLE
rowClick

### ISSUE THREAD

**Issue by Sm00g15** [olifolkerd/tabulator#377]
rowClick:function(){
        window.open("https://cryptoreport.com/" + row.getData().symbol + "_blank");
    },

Using this code, when I click on a row my console logs: 
```
tabulator.js:12 Uncaught ReferenceError: row is not defined
    at Object.rowClick (tabulator.js:12)
    at HTMLDivElement.<anonymous> (tabulator.min.js:1)
    at HTMLDivElement.dispatch (jquery.js:4435)
    at HTMLDivElement.r.handle (jquery.js:4121)
```

If I remove the        + row.getData().symbol + "_blank")      portion of the code it opens a new window and works, so the issue is definitely here.

**Comment by Sm00g15** [comment]
and row isn't defined because I'm render all my JSON data in columns, however I want the rowClick to trigger a URL from the symbol column no matter where they click on the row. That make sense?

**Comment by olifolkerd** [comment]
you are getting that error because row needs to be passed into the rowClick callback as an argument:

```js
rowClick:function(row){
    window.open("https://cryptoreport.com/" + row.getData().symbol + "_blank");
},
```

Cheers

Oli

**Comment by Sm00g15** [comment]
I get this error after setting the argument to row

**Comment by olifolkerd** [comment]
Could you post your full Tabulator constructor as i cannot replicate the issue you are having.

Cheers

Oli

**Comment by Sm00g15** [comment]
$(document).ready(function() {
    // all custom jQuery will go here



$("#example-table-theme").tabulator({
    height:false, // set height of table (optional)
    fitColumns:true,
    headerFilterPlaceholder:"Search Coins",
    resizableColumns: false,
    rowClick:function(row){
        window.open("https://cryptoreport.com/" + row.getData().symbol + "_blank");
    },
    responsiveLayout: false, //fit columns to width of table (optional)

    columns:[ //Define Table Columns
        {title:"#", field:"rank", sorter:"number", width:50, frozen: true},
        {title:"Coin", field:"name", sorter:"string", width:150, frozen: true, headerFilter:"input"},
        {title:"Symbol", field:"symbol", sorter:"string", width:100},
        {title: "Price", field:"price_usd", width:150, sorter:"number", align:"center", formatter:"money", formatterParams:{symbol:"$"}},
        {title: "Market Cap", field:"market_cap_usd", width:200, sorter:"number", align:"center", formatter:"money", formatterParams:{symbol:"$", precision:null}},
        {title:"24hr Volume", field:"24h_volume_usd", width:200, sorter:"number", align:"center", formatter:"money", formatterParams:{symbol:"$", precision:null}},
        {title:"Available Supply", field:"available_supply", sorter:"date", align:"center", formatter:"money", formatterParams:{precision:null}},
    ],
});

$("#example-table-theme").tabulator({
    initialSort:[
        {title:"#", field:"rank", sorter:"number", width:50},
        {title:"Symbol", field:"symbol", sorter:"string", width:150},
        {title:"Coin", field:"name", sorter:"string", width:150},
        {title: "Price", field:"price_usd", sorter:"number", align:"center", formatter:"money", formatterParams:{symbol:"$"}},
        {title: "Market Cap", field:"market_cap_usd", sorter:"number", align:"center", formatter:"money", formatterParams:{symbol:"$", precision:null}},
        {title:"24hr Volume", field:"24h_volume_usd", sorter:"number", align:"center", formatter:"money", formatterParams:{symbol:"$", precision:null}},
        {title:"Available Supply", field:"available_supply", sorter:"number", align:"center", formatter:"money", formatterParams:{precision:null}},
    ],
});

//load sample data into the table
$("#example-table-theme").tabulator("setData", "https://api.coinmarketcap.com/v1/ticker/?limit=100");

$("#example-table-theme").tabulator({
    virtualDom:true, //disable virtual DOM rendering
});

//Re-render table when viewport width is changed
$(window).resize(function(){
    $("#example-table-theme").tabulator("redraw", true); //trigger full rerender including all data and rows
});


});

**Comment by Sm00g15** [comment]
```
$(document).ready(function() {
    // all custom jQuery will go here



$("#example-table-theme").tabulator({
    height:false, // set height of table (optional)
    fitColumns:true,
    headerFilterPlaceholder:"Search Coins",
    resizableColumns: false,
    rowClick:function(row){
        window.open("https://cryptoreport.com/" + row.getData().symbol + "_blank");
    },
    responsiveLayout: false, //fit columns to width of table (optional)

    columns:[ //Define Table Columns
        {title:"#", field:"rank", sorter:"number", width:50, frozen: true},
        {title:"Coin", field:"name", sorter:"string", width:150, frozen: true, headerFilter:"input"},
        {title:"Symbol", field:"symbol", sorter:"string", width:100},
        {title: "Price", field:"price_usd", width:150, sorter:"number", align:"center", formatter:"money", formatterParams:{symbol:"$"}},
        {title: "Market Cap", field:"market_cap_usd", width:200, sorter:"number", align:"center", formatter:"money", formatterParams:{symbol:"$", precision:null}},
        {title:"24hr Volume", field:"24h_volume_usd", width:200, sorter:"number", align:"center", formatter:"money", formatterParams:{symbol:"$", precision:null}},
        {title:"Available Supply", field:"available_supply", sorter:"date", align:"center", formatter:"money", formatterParams:{precision:null}},
    ],
});

$("#example-table-theme").tabulator({
    initialSort:[
        {title:"#", field:"rank", sorter:"number", width:50},
        {title:"Symbol", field:"symbol", sorter:"string", width:150},
        {title:"Coin", field:"name", sorter:"string", width:150},
        {title: "Price", field:"price_usd", sorter:"number", align:"center", formatter:"money", formatterParams:{symbol:"$"}},
        {title: "Market Cap", field:"market_cap_usd", sorter:"number", align:"center", formatter:"money", formatterParams:{symbol:"$", precision:null}},
        {title:"24hr Volume", field:"24h_volume_usd", sorter:"number", align:"center", formatter:"money", formatterParams:{symbol:"$", precision:null}},
        {title:"Available Supply", field:"available_supply", sorter:"number", align:"center", formatter:"money", formatterParams:{precision:null}},
    ],
});

//load sample data into the table
$("#example-table-theme").tabulator("setData", "https://api.coinmarketcap.com/v1/ticker/?limit=100");

$("#example-table-theme").tabulator({
    virtualDom:true, //disable virtual DOM rendering
});

//Re-render table when viewport width is changed
$(window).resize(function(){
    $("#example-table-theme").tabulator("redraw", true); //trigger full rerender including all data and rows
});


});

**Comment by olifolkerd** [comment]
Got to the bottom of it, you were also missing the event argument:

```js
rowClick:function(e,row){
    window.open("https://cryptoreport.com/" + row.getData().symbol + "_blank");
},
```
Also looking at your code, have you intentionally disabled the virtual dom? if you set a height on the table it will render more efficiently.

Cheers

Oli

**Comment by Sm00g15** [comment]
LOL should've known! Ah, and nope just was playing with virtualDOM and that was where I last had it, thanks for the heads up. What height is ideal for rendering?

**Comment by olifolkerd** [comment]
choose any height you like, you can set any valid css in the height

**Comment by Sm00g15** [comment]
Thanks for the help Oli, tabulator's great

**Comment by olifolkerd** [comment]
Thanks for the kind words! its always great to hear Tabulator is appreciated :)

**Comment by Sm00g15** [comment]
You’re very welcome. You’ve been a ton of help and super on the ball with responses, much appreciated
