### ISSUE TITLE
Ability to save order of columns for responsiveCollapse 

### ISSUE THREAD

**Issue by maxxdev** [olifolkerd/tabulator#3770]
*Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Now if we use `formatter: "responsiveCollapse"` and set` responsive: 0` for the last column it will be displayed first when columns collapsed, but would like to have him at the last place.
For example 1, 2, 3( responsive: 0 )
Now displays
3
1
2

Would be great to display in the original order
1
2
3

**Describe alternatives you've considered**

**Additional context**

**Comment by olifolkerd** [comment]
I don't follow you there. I think there might be a bug in the setup. Please provide a link to a JS fiddle as the first column hidden will be the first last shown. It shouldn't change the row order

**Comment by maxxdev** [comment]
Sure, [ the fiddle](https://jsfiddle.net/maksim_dev/9p6e4r30/7/)
The _age_ field is above collapsed data, but I would like to see him after collapsed data event without  toggle+/- button

**Comment by olifolkerd** [comment]
Hey @maxxdev 

Thanks for the clarification, i think that would make for a poor user experience, as the left to right order of precedence is replicated in the top to bottom precedence of the list. For this reason i would now be looking to make this a feature built into Tabulator.

However you can easily add this functionality to your table using the `responsiveLayoutCollapseFormatter` to determine how the data is displayed.

Checkout the [Responsive Collapse Documentation](http://tabulator.info/docs/5.2/layout#responsive-collapse) for full details.

Cheers

Oli ;)
