### ISSUE TITLE
using deepscan

### ISSUE THREAD

**Issue by lekoala** [olifolkerd/tabulator#3772]
**Is your feature request related to a problem? Please describe.**
Recently i've been working with some of the internal features of tabulator. While that overall quality is very solid, it seems inconsistent in some places (it could be considered as nitpicking https://github.com/olifolkerd/tabulator/pull/3767 or as an actual issue https://github.com/olifolkerd/tabulator/pull/3759).

Sometimes, (return) types are not always clear or consistent, also due to a lack of jsdoc (which, i guess, is deliberate?) and it could lead to actual issues (eg: getValue never returns undefined, but "" in https://github.com/olifolkerd/tabulator/pull/3753).

**Describe the solution you'd like**
Automated tooling should help to fix (current) issues and prevent future issues and regressions. I've recently came across [deepscan](https://deepscan.io/dashboard/) which is free for open-source projects. I think it would be a valuable addition to the eslint automated checks. For some examples of issues it can catch, see screenshot below.

I'm pretty sure the overall quality of the project would benefit from this and some bugs that haven't been discovered yet could be fixed easily.

Some of them are obvious "false positives", but there seems to be some valid issues as well.

**Example**
<img width="779" alt="image" src="https://user-images.githubusercontent.com/250762/169809571-156294a5-d21e-4459-acb7-93478c971b75.png">

**Comment by olifolkerd** [comment]
Hey @lekoala 

Just had a play with deepscan, it was very useful thanks.

I have applied its suggestions to the 5.3 branch which will be released in a few weeks.

Cheers

Oli :)
