### ISSUE TITLE
Aria Issues from discord channels

### ISSUE THREAD

**Issue by spormeon** [olifolkerd/tabulator#3773]
been asked on the discord channel to raise an issue here:

**Describe the bug**

There seems to be a bug with Aria group and child on the table

it seems tabulator-header is using role=rowgroup, where should be =rowheader

then tabulator-tableholder & tabulator-table both use role=rowgroup, should only be one of, most likely -table

![DevTools_-_stats_adysis_com_stats_video](https://user-images.githubusercontent.com/8503167/169998271-28b38b79-1b8f-4e99-a47d-c41c6b71ba0c.png)
![Accessible_Rich_Internet_Applications__WAI-ARIA__1_1](https://user-images.githubusercontent.com/8503167/169998483-8364f9a5-130f-4870-8d50-58b4222386bf.png)

Then the second problem is aria-sort="asc" doesnt exist in spec, its should be aria-sort="ascending",  I've tested changing this and it gets rid of the error when chnaged, but the table then is not in asending order

![DevTools_-_localhost_8080_stats_video](https://user-images.githubusercontent.com/8503167/170002814-3c3731e3-edc2-4913-ac2b-b91ae1f3ec36.png)
![DevTools_-_localhost_8080_stats_video](https://user-images.githubusercontent.com/8503167/170002966-ccfea5de-7ef6-49bf-853b-1a6ea36c8ef3.png)
![Accessible_Rich_Internet_Applications__WAI-ARIA__1_1](https://user-images.githubusercontent.com/8503167/170003081-8db9e827-8b5d-4ba6-aaa2-deb8c258013c.png)

![Main_vue_—_statsadysis](https://user-images.githubusercontent.com/8503167/170003514-c1412956-8f5e-4807-89f8-2bbadc4fa3d6.png)

**Tabulator Info**
5.2.0

**Comment by olifolkerd** [comment]
Hey @spormeon 

Thanks for the info, im not sure about the proposed aria roles for the elements you have mentioned.

As you can see from the [MDN Docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/rowheader_role) the existing use of the `rowgroup` is correct for containing the colum headers and for containing the table rows. Which is the approach Tabulator currently follows. The example provided on the page matches Tabulators layout. And i dont get any accessibility warnings about this in my browser accessibility tool bar.

`rowheader` is not the right choice as this is the equivalent of `columnheader` and is to be used for a left hand row header.

and the `tabulator` element already has the `table` aria tag, it would not be appropriate to include this again inside the table itself.

Your accessibility browser may be being confused by there being more tags inside the table than a standard table, but there is little i can do about that, all the div's that exist in Tabulator are needed for a reason. 

The `aria-sort` attribute values on the other hand is clearly wrong. i have pushed a fix for this to the master branch and will include it in this weekends patch release.

Cheers

Oli :)

**Comment by spormeon** [comment]
ok sure on the aria-sort.  Think i got it slightly wrong before, but why cant you do tabulator-tableholder = role="rowheader" and then tabulator-table role="rowgroup" then its right isnt it?

**Comment by olifolkerd** [comment]
because `rowheader` is the row equivalent of `columnheader` it is not for containing a row of headers, it refers to a "cell" that is a header. 

Look at how column headers are used in the table, they are the headers of each column, rowheader is the same but for a row, it is intended to be the first cell in a row that is the header content for that row. It is not the equivalent of an `hr` tag, it does not perform the function of grouping cells together. as the example of the link in the above post shows that is the role of the `rowgroup`

Cheers

Oli :)

**Comment by spormeon** [comment]
ok, so just leave out any row= in tabulator-tableholder, so there is non there at all. Then there are not 2 "conflicting" row="rowgroup"?

**Comment by olifolkerd** [comment]
@spormeon That might work, what accessability tool are you using to check? just wanna make sure this actually fixes your issue

**Comment by spormeon** [comment]
god google and chrome browser, lighthouse

**Comment by olifolkerd** [comment]
Hey @spormeon That did the trick. i have pushed the updates to the master branch and will include them in a patch release later today.

Cheers

Oli :)
