### ISSUE TITLE
Frozen columns are currently not supported in RTL mode

### ISSUE THREAD

**Issue by hosseinprince** [olifolkerd/tabulator#3774]
You wrote in version 5.2 that this problem will be fixed in version 4.9.
But the problem still exists.
![Untitled](https://user-images.githubusercontent.com/12623693/170240864-c18de112-9df2-4702-98a3-18949a6fc42b.png)

**Comment by olifolkerd** [comment]
Hey @hosseinprince 

Thanks for the note, i will update the docs to remove the invalid version number in that message. It isnt a bug or a problem, just a known limitation of the current system.

It will get looked at in the future but im afraid there are more pressing updates needed on other parts of the library at the moment so this is unlikely to be resolved any time soon. If this is a concern for you, please feel free to create a PR that adds the functionality yourself.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @hosseinprince 

I have made an update to the site code to improve the messaging on this and will include this i the site update with the next patch release.

Cheers

Oli :)
