### ISSUE TITLE
position: "bottom" in scrollToRow function does not work

### ISSUE THREAD

**Issue by viper0203** [olifolkerd/tabulator#3775]
**Describe the bug**
When the second argument of the scrollToRow function is set to "bottom", it behaves the same as "top".

**Tabulator Info**
5.2.4

**Working Example**
`tabulator.scrollToRow(targetRow, "bottom", false);`

**Expected behavior**
I want targetRow to scroll to the bottom.

**Screenshots**
[Renderer.js - ScrollToPosition()]
![code](https://user-images.githubusercontent.com/106292943/170413432-43ab75ac-c0da-4708-8ee4-d3aba860a52b.PNG)

**Desktop (please complete the following information):**
 - OS: Win10 21H1
 - Browser: Edge
 - Version: 101.0.1210.53

**Comment by olifolkerd** [comment]
Hey @viper0203 

Thanks for the headsup,

I have pushed a fix for this to the master branch and will include it in this weekends patch release.

Cheers

Oli :)
