### ISSUE TITLE
Small error in Persistent Column Layout section

### ISSUE THREAD

**Issue by qforce85** [olifolkerd/tabulator#3777]
**Website Page**
[Persistent Column Layout section](http://tabulator.info/docs/5.2/persist#columns)

**Describe the issue**
The first sentence is currently: "You can ensure the layout of columns is stored for the next page load by setting the **page** property of the persistence option to true"

I believe that sentence was copied and pasted from the preceding section and should instead be: "You can ensure the layout of columns is stored for the next page load by setting the **columns** property of the persistence option to true"

**Comment by qforce85** [comment]
Reading the linked section, I noticed some more typos at the end:

> Note: If you are going to use this mode of operation the property must **existi** in the column definition when the column is first initialized. Tabulator can only monitor properties that have been changed **no** those that have been added.

**Comment by olifolkerd** [comment]
Hey @qforce85 

Thanks for the headsup, i will fix those in this evenings site update.

Cheers

Oli :)
