### ISSUE TITLE
Accessing the row data (data param) in a formatter v3

### ISSUE THREAD

**Issue by iagoswi** [olifolkerd/tabulator#378]
Hi everyone!

With the previous version of tabulator,.js, I had made a table with a column containg a text linking to a page, something like (simplified):
```
field: "hike",
formatter: "linkFormatter"
```
The data array had an additional "link" field where I stored the link. The formatter linkFormatter could build the link using data.link:
```
//format hike name as link
linkFormatter:function(value, data, cell, row, options){
return "<a href='" + data.link + "'>" + value + "</a>";
}
```
Now, with the new formatters in v3, I don't see how can access the whole row to retrieve the link value any more. Do I have to rewrite my array and send the link as formatParam ?

Thanks for the great plugin!

**Comment by olifolkerd** [comment]
Hey,

With 3.0 all callbacks are now passed [components](http://olifolkerd.github.io/tabulator/docs/3.0/#components) which you can use to access all the old functions and much more!

Your formatter should now look something like this:
```js
linkFormatte = function(cell, formatterParams){
    return "<a href='" + cell.getRow().getData().link + "'>" + cell.getValue()+ "</a>";
}
```

Let me know if that helps

Cheers

Oli

**Comment by iagoswi** [comment]
Thanks Oli. It's working great. [Proof](http://www.noth.ch/fr/randos/liste-des-randos.html).
Despite checking the doc several times, I missed the fact that getRow and getData were available.

--
Philippe
