### ISSUE TITLE
Theme for the v3 release of the Tailwind CSS framework

### ISSUE THREAD

**Issue by cacuestai** [olifolkerd/tabulator#3780]
Hello:

Some solution to use Tailwind v3? Styles behave strangely with this framework.

Thank you very much,

Carlos

**Comment by olifolkerd** [comment]
Hey @cacuestai 

Feel free to submit a PR with a theme that matches your framework. they are very simple to setup, you simply import the base setup and add any changes to it in the theme style sheet, check out some of the existing themes for examples.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Im going to merge this with #4325 as it covers things in more details

Cheers

Oli :)
