### ISSUE TITLE
List Editor with Multiselect:true does not save edits to cell

### ISSUE THREAD

**Issue by mikeciz** [olifolkerd/tabulator#3781]
### Describe the bug
The built-in list editor still does not fire the cellEdited consistently when 'multiselect' is true. See the "Cheese" column in the jsfiddle. After you select one or two cheeses, clicking to the **left** of the input cancels the edit.  If you click outside of tabulator it will sometimes save it but any click within the window will be canceled.

FYI - You closed my prior bug reporting this but I noticed your release notes referred to fixing the list with the _headerfilter_. I'm not using a headerfilter.

### Tabulator Info
Tabulator v5.2.5

### Working Example
https://jsfiddle.net/mikeciz/w07tdjqz/10/

### To Reproduce
1. Go to the "Cheese" column
2. Click on an empty cell to select one or two cheeses
3. Click on another cell in the table to confirm your edit and close the list dropdown

Most, but not all the time, the edit is cancelled and the data in the cell reverts back to the original value. I assume this is due to a blur issue, but I'm not sure.

### Expected behavior
I would hope that a multiselect = true would fire the cell edited once you clicked outside the list.

Thanks Oli!

**Comment by christianitis** [comment]
Happening to me as well

**Comment by olifolkerd** [comment]
Hey All,

I have just pushed a fix for this to the master branch and will include it in sundays patch release.

Cheers

Oli :_
