### ISSUE TITLE
Sort icons don't change when the sort order changes

### ISSUE THREAD

**Issue by rjaros** [olifolkerd/tabulator#3782]
**Describe the bug**
Sort icons in headers don't change when the sort order is changed.

**Tabulator Info**
5.2.5

**Working Example**
https://jsfiddle.net/04gshfe1/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://jsfiddle.net/04gshfe1/
2. Click on any header a few times

**Expected behavior**
Sort icons should change to up and down arrows.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome 102, Firefox 100

**Comment by Martino-Martinez** [comment]
Same can be seen on the sort examples at http://tabulator.info/examples/5.2#sorters

**Comment by olifolkerd** [comment]
Yeah, my bad I broke it with aria tag updates in the last release. I will
do a patch release this eve to fix things

**Comment by olifolkerd** [comment]
I have pushed a fix for this to the master branch and will include it in a patch release a little later this evening.

Cheers

Oli :)

**Comment by jaguarxii** [comment]
Hi, I updated to the latest release, but the sort icons does not display custom color, grey only

**Comment by olifolkerd** [comment]
If you have made css overrides then you will need to change them. The aria
sort attributes now use ascending/descending instead of asc/desc

**Comment by ScottTyson** [comment]
Hi Oli,
I'm using Tabulator 5.5.2 and react-tabulator 0.19.2.
I see this same issue with the sort icon. I don't have any Tabulator CSS.
I'm not sure which version of Tabulator is used for your sort examples, but those are working.
Running Firefox on MacOS.

Any thoughts on this?
