### ISSUE TITLE
Allow customisation of the column header sort icons

### ISSUE THREAD

**Issue by lekoala** [olifolkerd/tabulator#3787]
**Is your feature request related to a problem? Please describe.**
i'm working on a project where i'm replacing a dynamic table. one area that is slightly better in my current solution is the sort icon. indeed, in tabulator, an unsorted column show a lighter triangle (which is the same as the descending sort icon).
in my current solution, there is a distinct icon which i think is more accessible

**Describe the solution you'd like**
by using a distinct icon that reflect the aria sort value, we don't rely only on color and have a more accessible experience

example
https://codepen.io/lekoalabe/pen/XWZYzYX

side note: this involve making the triangle smaller. i've set a css var to easily switch and test between values but i think 4px is looking good

bonus: this codepen also shows a sticky header, which is a common feature. it's easy add to add yourself but maybe it might be worth it to document this somewhere in the docs for those asking.

**Describe alternatives you've considered**
ag grid is not displaying any icon at all when no sort is applied but i think that's confusing because you cannot see sortable columns

datatables keeps both arrow and have a similar issue

**Comment by olifolkerd** [comment]
Hey @lekoala 

Thanks for the suggestion,

Those sort icons look nice, im sure they will fit in well with your theme, this actually raises a very good point, pretty much every part of Tabulator can be customized but at the moment it isn't possible to load custom sorter iconography.

I will add custom sort icons to the roadmap for the next minor release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @lekoala 

On investigating this further, i realised i had forgotten there is already a `headerSortElement` option for customizing the sort element, i have just pushed an update to the 5.3 branch to allow this option to take a callback to allow for customisation of icons for each sort state.

Cheers

Oli :)
