### ISSUE TITLE
Bootstrap 5 styling issues with table classes

### ISSUE THREAD

**Issue by JacobGralinski** [olifolkerd/tabulator#3788]
Hi Oli,

**Describe the bug**
When using the Bootstrap 5 theme, I have the following classes added to the div that holds my table.

- table
- table-bordered
- table-striped

The headers do not align with the data columns, and the stripes do not show. If you hover over the different rows, the hover highlight suggests that something is there, but maybe it's transparent. Removing the "table" class from the Tabulator div does fix the issue, but the "table" class is what makes it a true Bootstrap table from what I understand.

I have included the example from Bootstrap's website for comparison.

**Tabulator Info**
5.2.6

**Working Example**
https://jsfiddle.net/jacobgralinski/f374xj5L/6/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://jsfiddle.net/jacobgralinski/f374xj5L/6/
2. Compare the first table to the second table
3. See error
4. OPTIONAL: Remove the "table" class from the example-table to see a somewhat fixed version

**Expected behavior**
With the table, table-bordered, and table-striped classes, the first (Tabulator) table should look like the second table (Bootstrap example).

**Screenshots**
With "table" class
![image](https://user-images.githubusercontent.com/32072855/171910058-140d5e38-aaeb-43bc-99d2-290718958299.png)

Without "table" class
![image](https://user-images.githubusercontent.com/32072855/171910170-7d8615b6-bf7f-489f-9450-bf5ff841c058.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 101.0.4951.67

**Additional context**
The stripes part of the issue appears to be something with the transparency styling on the rows.

**Comment by olifolkerd** [comment]
Hey @JacobGralinski 

The issue is that you are applying the `table` class to the table, this tries to force it to use the bootstrap standard table styles on an element it isnt built for. if you remove that class and let the tabulator stylesheet handle the table then the other clases will work as expected.

Also as a side note, you don;t need to include two tabulator stylesheets, it is either the basic theme OR the bootstrap theme, you don't need both

Cheers

Oli :)

**Comment by JacobGralinski** [comment]
Hey Oli,

I had a feeling that was the case. Just wanted to make sure I wasn't missing something. Thanks again!
