### ISSUE TITLE
registerTableFunction("clearSelection")

### ISSUE THREAD

**Issue by fprijate** [olifolkerd/tabulator#3789]
I'am using a function

```
async function deselectAll(table) {
  const selectedRows = table.getSelectedRows();
  for (const row of selectedRows) {
    row.deselect();
  }
}
```
It would be nice if there is a method table.deselectAll  (maybee some other name)
Maybee just exposing clearSelectionData

**Comment by olifolkerd** [comment]
Hey @fprijate 

You can already do this with the `deselectRow` function if you dont pass any arguments to it.

```js
table.deselectRow();
```

This functionality is covered in the [Row Selection Documentation](http://tabulator.info/docs/5.2/select#manage)

Cheers

Oli :)
