### ISSUE TITLE
Take a specific cell

### ISSUE THREAD

**Issue by neorm5** [olifolkerd/tabulator#379]
Hi, its possible take a value of a specific cell when double click in a row?

Thanks

**Comment by olifolkerd** [comment]
Hey,

That is no problem at all, the row component passed to the callback has a ***getCell*** function that lets you get a cell by its field name:
```js
$("#example-table").tabulator({
    columns:[...],
    rowDblClick:function(e, row){
        //e - the click event object
        //row - row component

       var cellValue = row.getCell("hasCar").getValue();// get the value of the cell with a field name of "hasCar" in this row
    },
});
```
Let me know if that helps

Cheers

Oli

**Comment by neorm5** [comment]
Thanks for the support, works perfect!

Great library!
