### ISSUE TITLE
Horizontal scroll bug in tabulator 5,2 

### ISSUE THREAD

**Issue by vrman** [olifolkerd/tabulator#3790]
There is a bug in horizontal scroll in new tabulator 5,2 , it always show scrollbar on overflow by no reason, and on single row data scroll bar flickering on resizing column , im using tabulator 5,2 in vue 3,

![screen](https://s8.gifyu.com/images/Animation95e2d7ac8f217e23.gif)

and here is my tabulator setup :
```const initTabulator = () => {
  tabulator.value = new TabulatorFull('#tabulator', {
    data: props.formData,
    layoutColumnsOnNewData: true,
    autoColumns: true,
    layout: 'fitDataFill',
    resizableColumnFit: true,
    autoResize: false,
    placeholder: 'There is nothing to show',
    columns: [...props.formData, ...props.printData],
  })
}```

**Comment by olifolkerd** [comment]
Hey @vrman 

If you are experiencing an issue, please create a JS fiddle that demonstrates the problem, im afraid there is little that can be worked out from a video alone. it is likely that there is an issue with the styles applied to the site that is conflicting with Tabulator, but without seeing the setup it is hard to offer any further advice.

Please submit a bug using the [Bug Issue Template[(https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Possible+Bug&template=bug_report.md&title=) as it will prompt you for all the info we need to help you out.

Cheers

Oli ;)
