### ISSUE TITLE
Frozen columns are jittering on horizontal scroll

### ISSUE THREAD

**Issue by creataceousplum** [olifolkerd/tabulator#3791]
Hi, Oli!
Thank you for this amazing library!
However, I found this bug which manifests itself as described below:
Frozen columns either on the left or right, or on both sides of the table are strongly jittering when the table is scrolled horizontally

Tabulator Info
- v5.2.6

Working Example:
https://codepen.io/cbracco/details/xxVOoQd

How To Reproduce
1. Using Chrome or Opera, go to https://codepen.io/cbracco/details/xxVOoQd (an example I found, not created by me)
2. Adjust the viewport so that part of the table rows are hidden (horizontally)
3. Scroll the table downwards
4. And then just scroll the table on the right and left fast
5. And see the strong jittering of the both frozen columns (one on the left and the other one on the right)

Expected behavior
No jittering of the frozen columns on either left or right side

Environment:
 - OS: MacOS Catalina v 10.15.7 (19H2)
 - Browsers: Chrome v 102.0.5005.61 (Official Build) (x86_64) and Opera v 87.0.4390.45 (x86_64)

NOTES: 
- The bug is not present in Firefox v 101.0 (64-bit), nor in Safari v 14.0 (15610.1.28.1.9, 15610)
- On my local machine the bug is present no matter what layout settings I apply
- Also with setting width, minWidth and maxWidth to the same value is not helping
- There is no memory issue on my machine, no CPU overload that may cause the slowdown of the browsers.

**Comment by olifolkerd** [comment]
Hey @creataceousplum 

This is a known issue on some browsers, it seems to be related to the amount of processing used to manage keeping the frozen elements in place. this is becoming less of an issue as modern browsers become more powerful and seems to mainly be an issue on apple devices at the moment.

It is on the list to look into and there may be a rebuild of the frozen columns system in the future to make this smoother.

Cheers

Oli :)
