### ISSUE TITLE
Filters on headers: fetch the values from html elements of type datalist

### ISSUE THREAD

**Issue by massimosala** [olifolkerd/tabulator#3792]
Hi
On the web page I put a form (for user input) and a Tabulator table.

To give hints to the users, most of the input textboxes fetch their values from datalist elements.

It will be nice: when building a table, in the definition of the columns we can write

```
headerFilter: true,
headerFilterDatalist: ... id of the datalist element ...

```

The logic is the same as the input element: these are hints, not mandatory options.

Best regards, Massimo

**Comment by massimosala** [comment]
Pls note: I have these values inside javascript lists, but I cannot understand how to pass them during the table definition.

**Comment by olifolkerd** [comment]
Hey @massimosala 

You can already use the list editor to display a list of options for a header filter. The input editor is for trying only. The list editor is for lists.

The list editor has extensive options for loading in lists of data. I would not want to add a method for looking up data from the DOM as that is a bit of an anti pattern, data should be displayed in the DOM, it should be managed in variables. but if that is what you need you can easily pass a functions to the valuesLookup property of the list editor and lookup the values from the DOM yourself.

Cheers

Oli :)

**Comment by massimosala** [comment]
Hi Oli

I don't understand how to use valuesLookup.

I see your answer to this Q:
https://stackoverflow.com/questions/64438285/creating-a-header-filter-in-tabulator-for-choice-field-that-can-accept-multiple

As per the docs, I update from _select_ to _list_ and I wrote

```
column.headerFilter = "list";
column.headerFilterParams = { values: [ ... ] };

```

I want to give hints, but this solution doesn't permit the user to type in other values.

Pls help!

**Comment by olifolkerd** [comment]
i dont understand what you mean by hints im afraid, do you have an example?

**Comment by massimosala** [comment]
See the HTML tag _input_ with attribute _list_: users can choose from the suggested values and she/he can also type in new values.
The dropdown values are hints, not mandatory choices.

**Comment by olifolkerd** [comment]
Hey @massimosala 

That effect is achievable with the **list** editor with the **autocomplete** and **freetext** options enabled.

But if you insist on using the input editor then you can pass any of the standard attributes through to it on the **elementAttributes** prop of the **headerFilterParams**.

```js
{title:"Example", field:"example", headerFilter:"input" headerFilterParams:{{
    elementAttributes:{
        list: //whatever standard list values you would normally pass into the list attribute
    }
}}
```

Cheers

Oli :)

**Comment by massimosala** [comment]
I tried and it doesn't work:
```
column.headerFilter = "input";
column.headerFilterParams = { elementAttributes: { list: ['a', 'b', 'c'] }};

```

Can you pls update the docs?
I cannot find how to use _input_ with _elementAttributes_ and a list of values:
http://tabulator.info/docs/5.2/edit

Have a nice Sunday
m

**Comment by massimosala** [comment]
I get it!
_elementAttributes_ permits to set the HTML _input_ element attributes.
So _list_ value is the id of the _datalist_ HTML element defining the values.

It fits perfectly the opening question of this issue.
