### ISSUE TITLE
headerFilterParams: after click on X to clear the filter, the dropdown stays visible

### ISSUE THREAD

**Issue by massimosala** [olifolkerd/tabulator#3793]
It seems to me a bug.
The user has to click on the table rows to make the dropdown disappear.
Pls see the example.

```
<html>
<head>
<link href="https://unpkg.com/tabulator-tables@5.2.6/dist/css/tabulator.min.css" rel="stylesheet">
<script src="https://unpkg.com/tabulator-tables@5.2.6/dist/js/tabulator.min.js"></script>

<script>
function onLoad()
{
const tabledata = [
	{id:1, name:"Oli Bob", progress:12, location:"United Kingdom", gender:"male", rating:1, col:"red", dob:"14/04/1984", car:1, lucky_no:5},
	{id:2, name:"Mary May", progress:1, location:"Germany", gender:"female", rating:2, col:"blue", dob:"14/05/1982", car:true, lucky_no:10},
	{id:3, name:"Christine Lobowski", progress:42, location:"France", gender:"female", rating:0, col:"green", dob:"22/05/1982", car:"true", lucky_no:12},
	{id:4, name:"Brendon Philips", progress:100, location:"USA", gender:"male", rating:1, col:"orange", dob:"01/08/1980", lucky_no:18},
	{id:5, name:"Margret Marmajuke", progress:16, location:"Canada", gender:"female", rating:5, col:"yellow", dob:"31/01/1999", lucky_no:33},
	{id:6, name:"Frank Harbours", progress:38, location:"Russia", gender:"male", rating:4, col:"red", dob:"12/05/1966", car:1, lucky_no:2},
	];

const c = "name location gender dob".split(' ');
var columns = [];
for (let i = 0; i < c.length; i ++)
{
	let prop = c[i];
	let column = {
			title		: prop,
			field		: prop,
			frozen		: prop == "name",
			headerFilter: "list",
			headerFilterParams: { values: ['c','i','a','o'] }
	}
	columns.push(column);
}

var table = new Tabulator("#example-table", {
	data			: tabledata,
	layout			: "fitColumns",
    columns			: columns
});
}
</script>
</head>

<body onLoad="onLoad()">
<div id="example-table"></div>
</body>
</html>

```

![headerFilterParams_stuck_on_dropdown](https://user-images.githubusercontent.com/20907433/172044899-dd918835-d51e-4e6b-a383-2d2f09604e32.png)

**Comment by olifolkerd** [comment]
Hey @massimosala 

Please stop rasing bugs without using the issue template, which can be found [HERE](https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Possible+Bug&template=bug_report.md&title=) We have already asked you to use this template. it is not asking much, in return for using this free library and getting free help, we only ask that you take a couple of extra mins to provide the information we need to help you out effectively

The template will prompt you for all the information we need to help you out.

You MUST include a link to a JS Fiddle or code pen that demonstrates your issue and you MUST include the information about the browser you are using.

Without these it is very hard for us to offer you any advice or to confirm an issue has been fixed. I will close and lock any future issues raised without the correct template without discussion.

Cheers

Oli
