### ISSUE TITLE
Document how to setup Vue 3 component

### ISSUE THREAD

**Issue by sajjadalis** [olifolkerd/tabulator#3794]
I love Tabulator. I have used it in a few Vue 2 Projects but unfortunately, Vue 3 is not getting any love. It will be awesome if someone creates a wrapper for Vue 3.

Vue 3 is the future (with script setup) and this awesome library needs to be supported.

**Comment by olifolkerd** [comment]
Hey @sajjadalis 

Thanks for getting in touch. You can certainly use Tabulator on vue3 ,it is very simple to get up and running and you can easily add it into a custom component with data and column props and away you go. I would be happy to add an example of that in the docs section to help if that is what you need.

If you are asking for someone to make a wrapper for vue3 in a similar way to vue-tabulator was for Vue 2 then I'm afraid this isn't the right place for it. Wrappers are left for the community to develop, I'm afraid I only have the time to maintain the core Tabulator library. But if you want to start one I would be happy to include a link to it on the website.

If you want to discuss setting up a wrapper then can I suggest heading on over to the discord server and chatting with other members of the community to see if you can drum up any support.

Cheers

Oli :)

**Comment by sajjadalis** [comment]
Hi @olifolkerd 

Thanks for the reply. I would love to see an example in documentation. I have tried Manual setup from [this](http://tabulator.info/docs/5.2/frameworks#vue) page earlier before posting this issue. The problem I have with the watch and computed for filtering data in Vue 3.

```js
<script setup>
import { ref, onMounted, computed, watch } from 'vue';
import {TabulatorFull as Tabulator} from 'tabulator-tables';

const search = ref('')
const tabulator = ref(null)
const data = ref([
  {id:1, name:"Oli Bob", age:"12", col:"red", dob:""},
  {id:2, name:"Mary May", age:"1", col:"blue", dob:"14/05/1982"},
  {id:3, name:"Christine Lobowski", age:"42", col:"green", dob:"22/05/1982"},
  {id:4, name:"Brendon Philips", age:"125", col:"orange", dob:"01/08/1980"},
  {id:5, name:"Margret Marmajuke", age:"16", col:"yellow", dob:"31/01/1999"},
])
const columns = [
  { title: "Name", field: "name", width: 150 },
  { title: "Age", field: "age", hozAlign: "left", formatter: "progress" },
  { title: "Favourite Color", field: "col" },
  { title: "Date Of Birth", field: "dob", hozAlign: "center" },
  { title: "Rating", field: "rating", hozAlign: "center", formatter: "star" },
  { title: "Passed?", field: "passed", hozAlign: "center", formatter: "tickCross" }
];

onMounted(() => {
  tabulator.value = new Tabulator(tabulator.value, {
    data: data.value, //link data to table
    reactiveData:true, //enable data reactivity
    columns: columns, //define table columns
  });
})

watch(data, (newData, oldData) => {
  tabulator.value.replaceData(newData);
})

const filterData = computed(() =>{
    return data.value.filter((item) => {
        return item.title.toLowerCase().match(search.value.toLowerCase())
    })
})

</script>
```

With vue-tabulator (Vue 2), I can use filterData computed property as v-model and use the input field to search data. But in this case, I'm a bit lost as to how to use a computed property to filter data via input field. And how to use the watch method properly.

**Comment by sajjadalis** [comment]
Thanks @olifolkerd 

I had some issues with watcher and computed property. In the end, it turned out quite easier and there is no need for v-model unless you need search value inside script.

```
<input type="text" @input="e => table.setFilter('name', 'like', e.target.value)" />
```

**Comment by olifolkerd** [comment]
Hey @sajjadalis 

Thanks for the info, i will push an update to the docs this eve to add a basic vue 3 example

Cheers

Oli :)
