### ISSUE TITLE
column definition to allow multiple "copy sets"

### ISSUE THREAD

**Issue by jaguarxii** [olifolkerd/tabulator#3795]
*Is your feature request related to a problem? Please describe.**
I am trying to have multiple "sets of columns" copied to clipboard, this is useful when you have a grid with several columns and want to give the user some extra functions, such as:

- Export certain columns (to excel)
- Export/import another set of columns

**Describe the solution you'd like**
I have two proposals: 

1. have an array that defines the columns that will be copied to the clipboard.
2. the "clipboard" option of the column allows a function returning true or false.

**Describe alternatives you've considered**
I already tried to update the column definition before calling the "copytoclipboard" method but is not working as expected: it is too slow updating column definitions and the clipboard module seems to "override" the new definition.

Since I am using the "headerMenu" to call the "copyToClipboard" method I got an "Uncaught TypeError: r.rootPopup is null" error, I think its because the popup gets destroyed before the "new definitions"

I created a promise that resolves once the definition of the columns are finished.

**Comment by olifolkerd** [comment]
There is already a clipboard option on the column definition that lets you define weather a column should be included in the clipboard or not. Does this not do what you are after?

**Comment by olifolkerd** [comment]
https://shop.scouts.org.uk/accessories/scouts-pride-bisexual-woven-fun-badge#selection.size=One%20Size&selection.color=NULL

**Comment by olifolkerd** [comment]
http://tabulator.info/docs/5.2/clipboard#visbility

**Comment by jaguarxii** [comment]
Hi, the current feature allows me to have only one "set" of columns to copy to the clipboard.

I would like to have different "sets", as I described, updating the column definitions does not work and takes a lot of time (in my sample I only have 21 columns).

**Comment by olifolkerd** [comment]
Ahh with you now, I wouldn't go for the array as that goes against the standard options, but I can certainly make it take a function, no probs. Will add that to the list

**Comment by olifolkerd** [comment]
Hey @jaguarxii 

I have pushed an update to the 5.3 branch (released in a few weeks) that will allow a function to be passed to the clipboard option in each column definition to make it possible to change column visibility every time the data is copied to clipboard.

Cheers

Oli :)
