### ISSUE TITLE
Key binding action to commit changes without focus change

### ISSUE THREAD

**Issue by maximlt** [olifolkerd/tabulator#3796]
Hi and thanks for this great library!

I was wondering whether it would make sense and be possible to add a Key Binding Action that would commit changes made in an editable cell while not changing the focus to another cell. A good default candidate for that would be `CTRL + Enter`, to my knowledge this is the exact behavior you get in Excel.

**Comment by maximlt** [comment]
Hi @olifolkerd ,

I think I wasn't clear enough in my original post. I'm neither an English native speaker nor a seasoned front-end developer, it's not always easy to express yourself precisely 🙃 I'll try to do better this time!

> Tabulator is not intended as an in-browser replacement for excel, if you are looking for something that comprehensive then you should look at a paid for library that implements all those features.

Oh of course. I never meant that I would like Tabulator to be on par with Excel. Sorry if I wasn't clear on this.

To give you the context of this request, I am one of the maintainers of [Panel](https://github.com/holoviz/panel), an open-source Python library to build dashboards and which offers a Python interface to [Tabulator](https://panel.holoviz.org/reference/widgets/Tabulator.html) as a widget. I'm personally extensively using this widget and came up with this suggestion, which I'll precise now.

To edit the text of a cell in a free-form way one can choose to set the column editor to the `input` type. Then editing happens by focusing on that cell (clicking on it, or with the keyboard), typing some text and finally hitting `Enter`. My suggestion is for the case where the column editor is set to **`textarea`**. With this editor, hitting `Enter` adds a new line which is I believe a fine behavior. When I'm done editing text in a `textarea` cell, I wish I had at this point a key binding that would do the equivalent as hitting `Enter` in an `input` cell. I don't think there's such a key binding right now, but please correct me if I'm wrong. What I currently do instead if either click away, or use a combination of `Tab + Escape` or `Arrow + Escape`.

I suggested `CTRL + Enter` to be the key binding that would provide this behavior as this is indeed what Excel offers but it's a general UX when editing some text, this is for instance what [Slack](https://slack.com/help/articles/115005523006-Set-your-Enter-key-preference) offers too.

Please let me know if you need me to provide a code snippet or more context and details with respect to this request. I'd also be happy to try to work on a PR if you think it's in the end a valid request, that would improve Tabulator's UX.

**Comment by olifolkerd** [comment]
Hey @maximlt 

Thanks for the detailed response there, that makes more sense now.

Yes i would be happy to add shift+enter as a way to sumbit the value of the text area.

I will shcedule this for the next minor release in a few weeks time. If you fancy feel free to submit a PR, otherwise i will get round to it before the release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @maximlt 

I have just pushed an update to the 5.3 branch (released in a few weeks) that adds the new 'shiftEnterSubmit' editor param for the 'textarea' editor that will enable the functionality you deisre.

Cheers

Oli :)

**Comment by maximlt** [comment]
Wow great thanks! I had suggested CTRL + Enter but I'm also fine with SHIFT + Enter :) Cheers!
