### ISSUE TITLE
needed? on prev row

### ISSUE THREAD

**Issue by Salexmineralex** [olifolkerd/tabulator#3797]
Hello, my name is Alejandro

i'm trying to update a previous row with the 

cell.getRow().getPrevRow().update({ "name": prevrow.othercell });

the console it is giving "needed?"

Thank you for your help!

**Comment by olifolkerd** [comment]
Hey @Salexmineralex,

Could you put togeather a JS Fiddle or code pen that demonstrates the issue, without seeing how your table is setup or knowing the version of Tabulator you are using it is very hard to offer advice.

In future, can you please use the Bug Issue Template when reporting bugs as it will prompt you for all the information we need to help you out. Please see the [Reporting a Bug Guide](http://tabulator.info/community/bug) on the website for more info.

Cheers

Oli :)
