### ISSUE TITLE
Resposive feature (column show and hide) not working if we call tabulator from ifram (Shadow dom).

### ISSUE THREAD

**Issue by anandkrishna93** [olifolkerd/tabulator#3798]
**Describe the bug**

**Tabulator Info**
- Which version of Tabulator are you using?

**Working Example**
YOU MUST include a link to a JS Fiddle or Codepen that demonstrates the problem, it is very hard to diagnose an issue from a simple description.

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by olifolkerd** [comment]
@anandkrishna93  you haven't included any details of your issue. I'm afraid there is no way to offer you assistance with just a title to go on. Please read through the issue template and fill in the requested details fully so we can help you out

**Comment by anandkrishna93** [comment]
@olifolkerd sorry I forgot to add details.
I am trying to implement responsive table, I have added below configuration please refer attached screenshot. The issue is responsive feature not working in shadow dom (please refer screenhot).


![image](https://user-images.githubusercontent.com/21081931/173175620-4ebea64a-981a-402d-b64b-823232edca38.png)

![image](https://user-images.githubusercontent.com/21081931/173176144-317de5ce-1db4-40fe-b14c-ae63ca7c706a.png)

**Comment by anandkrishna93** [comment]
@olifolkerd sorry I forgot to add details.
I am trying to implement responsive table, I have added below configuration please refer attached screenshot. The issue is responsive feature not working in shadow dom (please refer screenhot).

![image](https://user-images.githubusercontent.com/21081931/173176255-d53ebbce-a9ce-4697-988a-9a8bf11457c0.png)


![image](https://user-images.githubusercontent.com/21081931/173176144-317de5ce-1db4-40fe-b14c-ae63ca7c706a.png)

**Comment by olifolkerd** [comment]
Could you please provide a link to a JS fiddle or code pen that.shows your issue in action. It is important that we see how you have your table setup and the environment in which it is running. You mention you are using the shadow Dom but there is no way for us to see how you are doing that.

Please do not send another screenshot. Pictures of code aren't that helpful.

What we need to see to help you out is a JS fiddle or code pen that actually shows the problem you are having.

Please have a read through the template info above and provide the details requested if you want further help

Cheers

Oli
