### ISSUE TITLE
Not working with readonly data

### ISSUE THREAD

**Issue by FrantzUml** [olifolkerd/tabulator#3800]
When the data of Tabulator is readonly (no setter for a field's data), the tabulator bugs.

I suggest to modify the 2 functions '_setFlatData' and '_setNestedData' of Column class :
   - add a condition in _setFlatData : && data[this.field] !== value
_setFlatData(data, value){
   if (this.field && data[this.field] !== value){data[this.field] = value}
}

   - add a condition in _setNestedData : && dataObj[structure[i2]] !== value

 _setNestedData(data, value){
   let dataObj = data;
   const structure = this.fieldStructure, length = structure.length;
   for (let i2 = 0; i2 < length; i2++){
      if (i2 === (length - 1) && dataObj[structure[i2]] !== value){
         dataObj[structure[i2]] = value;
      }
      else {
......
......

**Comment by olifolkerd** [comment]
Tabulator allows editing of data and is designed to take a simple array built up of simple objects to allow references to be maintained to the original object.

If you are using something more complex then I would suggest converting it to a standard object configuration before passing it to Tabulator

Cheers

Oli
