### ISSUE TITLE
Visible columns are larger than table

### ISSUE THREAD

**Issue by FrantzUml** [olifolkerd/tabulator#3801]
Using bootstrap theme, and setting layout to 'fitColumns', a table showing 3 columns (none gets a width in configuration) an horizontal scrollbar appears.

The 'div' of the Tabulator is : `**div** id="tableNaf" class="table table-striped tabulator" style="width: 100%; height: 100%;" role="grid" tabulator-layout="fitColumns">`

The 3 columns are :
`**div** class="tabulator-col tabulator-sortable" role="columnheader" aria-sort="none" tabulator-field="code" style="min-width: 40px; width: 314px; height: 100px;">...</div>
**div** class="tabulator-col tabulator-sortable" role="columnheader" aria-sort="none" tabulator-field="label" style="min-width: 40px; width: 942px; height: 100px;">...</div>
**div** class="tabulator-col" role="columnheader" aria-sort="none" tabulator-field="otherEa" style="min-width: 40px; width: 318px; height: 100px;">...</div>`

and an horizontal scrollbar appears.

When I resize the last column to 308px, the scrollbar dissapears.

I think it's the 'div' with the 'tabulator-row' class that is too large (1582px as the container is 1574px).

The container of Tabulator is a flex container.
The flexGrowUnits variable is 5 (1 for first column, 3 for second column and 1 fort last column).

**Comment by olifolkerd** [comment]
Please provide a js fiddle that demonstrates your issue. Without seeing how your table is setup it is not possible to understand what is happening or offer advice on how it may be resolved

**Comment by FrantzUml** [comment]
Thanks for the response.
I changed the 'renderEmptyScroll' function in the RowManager class and it's OK now:
`if(this.placeholder){
....
}
else{
this.tableElement.style.width = this.table.columnManager.getWidth() + "px"
}`

Changing style.minWidth to style.width

**Comment by olifolkerd** [comment]
This is not the correct approach generally as it would prevent tables wider
that the table which is the case if min width on columns combined is
exceeded

I'm glad you got your usage case working but incase anyone else reads this
thread, the correct approach is the CSS fix outlined above
