### ISSUE TITLE
row not defined in initializeGroupHeader function

### ISSUE THREAD

**Issue by Cyrelc** [olifolkerd/tabulator#3803]
**Describe the bug**
row variable not defined on line 73 of MoveRows.js

This will result in a console error always being thrown as row is undefined

**Tabulator Info**
- 5.2

![image](https://user-images.githubusercontent.com/15618831/173449792-14d90bec-7e81-4409-89de-59070495f6c9.png)

**Comment by Cyrelc** [comment]
I'm guessing this was copied from initializeRow() function below it, which is passed a row component rather than a group one

**Comment by olifolkerd** [comment]
Hey @Cyrelc 

This has already been fixed on the 5.3 branch that will be released in a couple of weeks.

Cheers

Oli :)
