### ISSUE TITLE
Freeze first column and first row synchronously

### ISSUE THREAD

**Issue by BoBoDouDou** [olifolkerd/tabulator#3804]
**Describe the bug**
I want freeze both the first column and first row at the same time. But the result seems that the first row can not be frozen as the column perspective.

**Tabulator Info**
I am using tabulator version 5.2 

**Working Example**
https://jsfiddle.net/czm480ud/

**To Reproduce**
1. When you scroll to right the first column have been frozen, **but not the first cell.**

**Expected behavior**
1. When scroll to right , I want to the **whole first column** can been frozen
2. When scroll to down, i want to the first row can been frozen

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [ Chrome]

**Comment by olifolkerd** [comment]
Hey @BoBoDouDou 

Thanks for the information, i have pushed an update to the 5.3 branch that fixes this issue. it should be released in the next couple of weeks.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
@BoBoDouDou 

You might like to know that when the 5.3 release comes out in a couple of weeks it will have some advanced row freezing functionality, that should make it even easier to freeze rows.

Cheers

Oli :)

**Comment by BoBoDouDou** [comment]
Thanks for your response. Looking forward to the 5.3 release.
