### ISSUE TITLE
Project reference for Typescript types is outdated

### ISSUE THREAD

**Issue by krstns** [olifolkerd/tabulator#3805]
**Website Page**
[A link to the page with the issue](http://tabulator.info/docs/5.2/language#typescript)

**Describe the issue**
The link mentioned on this page is providing types for an outdated version of the tabulator and does not seem to be maintained.
There's another one: https://github.com/DefinitelyTyped/DefinitelyTyped which is not perfect but at least it's more up-to-date.

**Comment by olifolkerd** [comment]
Hey @krstns 

Thanks for the info, i will update the website docs later this eve.

Cheers

Oli :)
