### ISSUE TITLE
groupClick

### ISSUE THREAD

**Issue by rossofiorentino** [olifolkerd/tabulator#3808]
Hello, 
i have passed fron 4.9 to 5.2 tabulator and groupClick seems to be stopped working.

    groupClick: function (e, group) {
      var click = '';
      if (e.target.hasAttribute("hdclk")) {click = e.target.attributes.hdclk.value };

      switch (click){
        case "note":
          mostranoteobiettivo(e);
          break;
        case "osservazioni":
          mostraOsservazioniObiettivo(e, '')
          break;
        case "valida":
          finisciObiettivo(e, 'accettato')
          break;  
        case "rifiuta":
          finisciObiettivo(e, 'rifiutato')
          break; 
        case "validato":
          mostraValidato(e, '')
          break;    
        case "addInt":
          aggiungiIndicatore(e, group)
          break;   
        case "editaobiettivo":
          editaobiettivo(e, group)
          break;     
        default:
          break;  
      }
    },

In version 4.9.3 works.
am I wronging in somethig?
Sorry from my bad english.

**Comment by olifolkerd** [comment]
Tabulator has moved from callbacks to events, checkout the [Upgrade Guide](http://tabulator.info/docs/5.0/upgrade#callbacks) for more details

**Comment by rossofiorentino** [comment]
True! Thanks OLI!!!
