### ISSUE TITLE
Built-in `list` editor doesn't keep the selected values when used as `headerFilter` and with `multiselect` param

### ISSUE THREAD

**Issue by viicslen** [olifolkerd/tabulator#3809]
**Describe the bug**
When the list editor is used as a header filter in conjunction with the headerFilterParam `multiselect` set to true, the selected options are not saved upon opening and closing the dropdown menu. In addition to that, if any of the previously selected options are selected again, it will add a duplicate entry to the input.

**Tabulator Info**
Version: 5.2.6

**Working Example**
[https://jsfiddle.net/eyzLqbhd/1/](https://jsfiddle.net/eyzLqbhd/1/)

**To Reproduce**
1. Click on the header filter
2. Select any options from the dropdown menu
3. Click anywhere outside of the input
4. Click on the header filter again
5. The previously selected options are not selected anymore
6. Click on the same options again

**Expected behavior**
Header filter dropdown menu should keep the selected options when opening and closing

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Opera 88

**Comment by olifolkerd** [comment]
Hey all,

I have pushed a fix for this to the 5.3 branch which will be released in a couple of weeks.

Cheers

Oli :)
