### ISSUE TITLE
Column header height 0px.

### ISSUE THREAD

**Issue by mikeshow** [olifolkerd/tabulator#381]
Hi,

In a page I have 3 tabulators. I have a problem with one of them where tabulator, for some reason, set the height of the header column in the element.style to 0px.

Where can I look to find why, or what can I do to set the height right?

Thanks.

**Comment by olifolkerd** [comment]
Hey,

are they all on display at the same time? if you created the table when it was not displayed you will need to call the ***redraw*** function when you fist show it so it can adjust to the height.

```js
$("#example-table").tabulator("redraw");
```

Also are you running the latest version of Tabulator?

Cheers

Oli

**Comment by olifolkerd** [comment]
on further inspection, i can see there is a bug there, i will see if i can get a fix into the 3.1 release toniight

**Comment by olifolkerd** [comment]
I have updated the 3.1 release, if you call the following function when you make it visible it should now work:
```js
$("#example-table").tabulator("redraw");
```

Cheers

Oli

**Comment by mikeshow** [comment]
Hi Oli,
I've installed the latest 3.1 and added a tabulator("redraw", true) and now it works. without the 'true' it doesn't.
Thanks.
Mike.
