### ISSUE TITLE
movableRows fails near end of the table

### ISSUE THREAD

**Issue by lekoala** [olifolkerd/tabulator#3810]
**Describe the bug**
I try to move a row on the last line of my table and it's really tricky because you can get a js error near the end

**Tabulator Info**
latest

**Working Example**
https://codepen.io/lekoalabe/pen/XWZYzYX

**To Reproduce**
1. Scroll near the end of the table
2. Try to drag the white background row under the last line
3. An error message appears

MoveRows.js:355 Uncaught TypeError: Cannot read properties of null (reading 'removeChild')
    at r.value (MoveRows.js:355:33)
value @ MoveRows.js:355
2MoveRows.js:351 Uncaught TypeError: Cannot read properties of null (reading 'insertBefore')
    at r.value (MoveRows.js:351:40)

**Expected behavior**
Dropping should not break near the table footer

**Comment by olifolkerd** [comment]
Hey @lekoala 

Thanks for the headsup, the issue was the element being able to leave the physical bounds of its parent, throwing off the maths, i have pushed an update to the 5.3 branch to fix this, which should be released in a couple of weeks

Cheers

Oli :)

**Comment by pepocero** [comment]
I have the same problem with Tabulator 5.4
When I want to move a column to the end, I get the error:
tabulator.min.js:2 Uncaught TypeError: Cannot read properties of null (reading 'insertBefore').
