### ISSUE TITLE
groupBy not cleared

### ISSUE THREAD

**Issue by andrewburw** [olifolkerd/tabulator#3811]
**Describe the bug**
After clearing grouping in table (groupBy(false), or groupBy([])), there still returning grouped information by function: getGroups.

**Tabulator Info**
- 5.1.7

**Working Example**

https://codepen.io/hornespill/pen/wvyOJoW

**To Reproduce**

1. Click button test.
2. Or uncomment commented js file lines.

**Expected behavior**
After clearing groups expected result is getting empty array. 

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser: chrome
 - Version: 89.0.4389.114

**Additional context**

**Comment by olifolkerd** [comment]
Hey @andrewburw 

Thanks for the info, i have pushed a fix for this to the 5.3 branch, which should be released in the next couple of weeks.

Cheers

Oli :)
