### ISSUE TITLE
Header Filter List Clearable Attribute Not Working in Firefox

### ISSUE THREAD

**Issue by ncrawford** [olifolkerd/tabulator#3813]
**Describe the bug**
In Firefox, the "clearable" attribute for headerFilterParams should display an "x" to allow you to clear the filter selection. This "X" does not appear in Firefox.  It will appear in Chrome.

**Tabulator Info**
- Latest, 5.2

**Working Example**
https://jsfiddle.net/o23u7vk8/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. In Firefox, In the results frame, click the header filter for the "Favourite Color" column and select a color
2. Hover your mouse over the filter list field

**Expected behavior**
An "x" should appear at the right side of the header filter list to click on and clear selection

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 101.0.1

**Additional context**
Works as expected in Chrome

**Comment by sxe** [comment]
Can confirm and the same happens on the list-editor.

(Unrelated: The documentation for the list editor mostly shows editor:"autocomplete", in the examples.)

Cheers

**Comment by olifolkerd** [comment]
Hey @sxe  Just so you are aware, the list editor and the header filter are the same thing, the code is reused, but thanks for the confirmation all the same :)

**Comment by olifolkerd** [comment]
Hey All,

This is a limitation of firefox, Tabulator uses a search type input to add the clearable X in the editor, for some reason firefox have chosen not to add this element to the search input.

Cheers

Oli :)

**Comment by sxe** [comment]
> Hey @sxe Just so you are aware, the list editor and the header filter are the same thing, the code is reused, but thanks for the confirmation all the same :)
Alright, thx for the explanation, wasn't aware.

> This is a limitation of firefox, Tabulator uses a search type input to add the clearable X in the editor, for some reason firefox have chosen not to add this element to the search input.
I suggest implementing a cross browser solution then. Focusing on one specific browser and not on open web standards is not good for the free web. We have enough of that already and google can more and more decide how the web looks like. 

Just my 2 cents. 

Cheers

**Comment by olifolkerd** [comment]
Thanks for your feedback. Tabulator is developed for all browsers, and in this case it is just Firefox that is misbehaving, things havnt just been built out for chrome, all other browsers big and small work.

I would certainly be happy to look into it further but right now I have other bigger priorities to look into.

And if I'm honest Firefox is really starting to let itself down. Not only is it now hovering at around 3% market share, which is decreasing all the time. It is becoming increasingly buggy and implementing less consistent behavior than any of the other browsers. If it keeps up this pace it will be the next IE in a couple of years. Pretty much everything I build out works straight away in every browser and it is always Firefox that has the edge case issues. With the decreasing market share and increases in bugs it is becoming less and less worth the effort, especial for the more edge case useage cases

Cheers

Oli

**Comment by sxe** [comment]
Hey Oli,
I didn't mean to imply that you guys are not doing good work.

I also don't want to make this a discussion about browsers but I feel the need to clarify one point;
I understand your frustration but I think you got it reversed. Firefox gets worse and worse, I agree but not because they suddenly do less it's because everybody is now a days testing vs chromium (blink) based browsers and is mostly ignoring what the specifications actually say. It's a chicken egg problem. Websites work better in chromium based browsers which makes Firefox work less good over time which results in less users and then even less devs test for it. It sucks. Google can shamelessly do this because they have the money and services to promote chrome which Mozilla has not.
 
Personally I develop for Firefox first to prevent this.

Anyways, that's all I am gonna say about it, I just could let you comment stay uncommented. ;)

Have a nice weekend!

**Comment by olifolkerd** [comment]
All good,

Thanks for your feedback, and you raise a fair point. And yeah this doesn't need to turn into a debate. 

But for the record I have raised several bug reports on Firefox and not a single one has ever been actioned even after years of feedback and acceptance that they are bugs, so they brought this one on themselves.

Cheers

Oli

**Comment by ilmari-lauhakangas** [comment]
In Firefox, [this is currently behind a config flag](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#layout_for_input_typesearch).

1. Go to about:config
2. Enter this option name and double-click to set to true: `layout.forms.input-type-search.enabled`

I confirm it works with Tabulator. There are still [some issues to be solved](https://bugzilla.mozilla.org/show_bug.cgi?id=1654288) before it can be enabled by default.

**Comment by m10x** [comment]
> In Firefox, [this is currently behind a config flag](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#layout_for_input_typesearch).
> 
>     1. Go to about:config
> 
>     2. Enter this option name and double-click to set to true: `layout.forms.input-type-search.enabled`
> 
> 
> I confirm it works with Tabulator. There are still [some issues to be solved](https://bugzilla.mozilla.org/show_bug.cgi?id=1654288) before it can be enabled by default.

It does not work for me. When clicking the x the Dropdown List selection is cleared, however the rows are still filtered
