### ISSUE TITLE
Uncaught TypeError: this.moving.getComponent is not a function

### ISSUE THREAD

**Issue by krisara4727** [olifolkerd/tabulator#3814]
Here is the codesandbox link for the issue when trying to move row from one table to another table getting this.moving.getComponent is not a function.

https://codesandbox.io/s/movablerowstabulator-3ncq9s

**Describe the bug**
I want to move row from one table to another table and vice versa, but when i am trying to move row from one table to another table getting this.moving.getComponent is not a function.

**Tabulator Info**
Tabulator version 5.1

**Working Example**
https://codesandbox.io/s/movablerowstabulator-3ncq9s

-->

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Create 2 tables with tabulator
2. configure the options required for moving rows from one table to another table
3. now drag and drop a row from one table to another table

**Expected behavior**
when we drag a row from one table to another table and vice versa , the row should be deleted from the sending table and added to the receiving table.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 
 - chrome 
 - Version 102.0.5005.115 

![Screenshot 2022-06-21 at 6 06 33 PM](https://user-images.githubusercontent.com/56177028/174800962-0c97f900-480d-4e83-9c34-f151bc57ecaa.png)

**Comment by olifolkerd** [comment]
Hey @krisara4727 

I cant seem to replicate this in vanilla JS my end, so anything you can help to narrow it down would help, im afraid im not a react developer myself. If react is redrawing the table due to the data chaging on drop then this could cause the issue.

Ive pushed an update to the 5.3 branch that might fix this, which will be released in a couple of weeks, but without being able to replicate it is hard to know if i have fixed it.

Cheers

Oli :)

**Comment by krisara4727** [comment]
Hey  *@olifolkerd*

I am using the tabulator latest version 5.3.1 , but still the issue with moving rows from one table to another table persists.
[link to the the issue on codesandbox](https://codesandbox.io/s/movablerowstabulator-forked-c4leql?file=/src/App.js)
[link to issue itself](https://c4leql.csb.app/)

image of the issue. This time the error is different. reading a property from undefined.
![screenshot of the issue](https://user-images.githubusercontent.com/56177028/180958078-4d4633a9-c984-41c7-8865-d9c2a5e53ffe.png)
)

It is working fine with javascript and html.
index.html
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://unpkg.com/tabulator-tables@5.3.1/dist/css/tabulator.min.css"
      rel="stylesheet"
    />
    <script
      defer
      type="text/javascript"
      src="https://unpkg.com/tabulator-tables@5.3.1/dist/js/tabulator.min.js"
    ></script>
    <script defer type="text/javascript" src="./script.js"></script>
    <title>Document</title>
  </head>
  <body>
    <p id="para"></p>
    <div id="table"></div>
    <div id="tabulator"></div>
  </body>
</html>
```
script.js
```javascript
var table = document.getElementById("table");
var table2 = document.getElementById("tabulator");
const tableData = [
  {
    id: 1,
    name: "name1",
    age: 32,
    color: "white",
  },
  {
    id: 2,
    name: "name2",
    age: 45,
    color: "green",
  },
  {
    id: 3,
    name: "name3",
    age: 73,
    color: "yellow",
  },
  {
    id: 4,
    name: "name4",
    age: 87,
    color: "red",
  },
];
const tabulator2 = new Tabulator(table2, {
  //table setup options
  layout: "fitColumns",
  movableRows: true,
  movableRowsConnectedTables: table,
  movableRowsReceiver: "add",
  movableRowsSender: "delete",
  data: tableData,
  autoColumns: true,
});

const para = document.getElementById("para");
para.innerHTML = "moving rows";

const tablulator = new Tabulator(table, {
  //table setup options
  layout: "fitColumns",
  movableRows: true,
  movableRowsConnectedTables: table2,
  movableRowsReceiver: "add",
  movableRowsSender: "delete",
  data: tableData,
  autoColumns: true,
});
```
**but when using with a javascript framework like react, facing this issue even in tabulator latest version 5.3.1**
Any solution for this.
