### ISSUE TITLE
Clicking away from "list" editor clears value

### ISSUE THREAD

**Issue by christianitis** [olifolkerd/tabulator#3815]
**Describe the bug**
When using the "List" editor, clicking away while the value list is open causes the cell to display a blank value.

**Tabulator Info**
- Which version of Tabulator are you using?
5.2.7

**Working Example**
https://jsfiddle.net/wd7czt9j/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Click on a cell
2. Click away from the cell while the editor list is open

**Expected behavior**
It should return to its previous value or a default value.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 101.0.1

**Additional context**
Also you left in a `console.log("choose")` somewhere :)

**Comment by olifolkerd** [comment]
Hey @christianitis 

This is happening because you have set the value of the cells to a value that isnt in the value list, in select mode the editor is limited to allowing values in the list only and so the value is cleared.

If you want to allow freetext values, the you should put the list editor in `autocomplete` mode and and add the `freetext` param as well.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
thanks for the headsup about the console log, i have removed that on the 5.3 branch.

Cheers

Oli :)

**Comment by buste** [comment]
> Hey @christianitis
> 
> This is happening because you have set the value of the cells to a value that isnt in the value list, in select mode the editor is limited to allowing values in the list only and so the value is cleared.
> 
> If you want to allow freetext values, the you should put the list editor in `autocomplete` mode and and add the `freetext` param as well.
> 
> Cheers
> 
> Oli :)

How can I still show the current value without clearing it? Just want to set as is without updating the value.

**Comment by kpetrow** [comment]
How do i set a label and a value to match my editParams.values array?  The formatter doesn't(if you catch and set back then it triggers cellEdited) work and clicking off the list does not call the edit cancel function?

**Comment by olifolkerd** [comment]
Have a look at the lookup formatter

**Comment by kpetrow** [comment]
Can i use a formatter along with the lookup formatter?  It would be nice to have the editParams and the lookupformatter take the same object

**Comment by olifolkerd** [comment]
You can only use one formatter at a time. But you can use a formatter and an editor
