### ISSUE TITLE
listOnEmpty is not working as expected

### ISSUE THREAD

**Issue by sogrbilja** [olifolkerd/tabulator#3816]
**Describe the bug**
listOnEmpty described here: http://tabulator.info/docs/5.2/edit#editor-list is not working as expected.

**Tabulator Info**
ver. 5.2.7

**Working Example**
here is an example:
https://codepen.io/sogrbilja/pen/zYRQXeR

**To Reproduce**
1. click on any empty cell (first or second row) in the first column and a list will appear even if listOnEmpty is set to false

**Expected behavior**
I expect NOT to have the list there because I don't need the entire list when the user clicks on the empty cell. It should appear only when the user starts typing. This 

**Screenshots**
[N/A]

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 102.0.5005.115 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
[N/A]

**Additional context**
[N/A]

**Comment by sogrbilja** [comment]
I've found the solution, so in tabulator.js you have this:

      value: function _showList() {
        var startVis = this.popup && this.popup.isVisible();

```
        if (this.input.parentNode) {
          if (this.params.autocomplete && this.input.value === "" && !this.params.listOnEmpty) {
            if (this.popup) {
              this.popup.hide(true);
              return;
            }
          }
```

it should be like this:

```
      value: function _showList() {
        var startVis = this.popup && this.popup.isVisible();

        if (this.input.parentNode) {
          if (this.params.autocomplete && this.input.value === "" && !this.params.listOnEmpty) {
            if (this.popup) {
              this.popup.hide(true);
            }
            return;
          }
```

Tell me will you update source code?

**Comment by olifolkerd** [comment]
Hey @sogrbilja 

Thanks for the headsup,

Your proposed solution doe fix your issue, but im afraid it break other functions of the editor.

I will add this to the list to fix for the next release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @sogrbilja 

I have pushed a fix for this to the 5.3 branch. You were almost there, it just needed a bit of additional logic on the input blur event and resolveValue functions.

The 5.3 branch will be released in a couple of weeks.

Cheers

Oli :)

**Comment by sogrbilja** [comment]
Thanks, I have some more questions for you, but I can't create it so detailed as this one. Where can I write them?

**Comment by olifolkerd** [comment]
If it is a general question, stick them on the questions channel on the
discord server
