### ISSUE TITLE
placeholder and type are predefined for input provided as custom headerFilter 

### ISSUE THREAD

**Issue by dbauszus-glx** [olifolkerd/tabulator#3819]
In Tabulator 5.2.7 we define the headerFilter as a function.

The function returns an input element with the placeholder and and type defined.

```JS
        {
          title: "Email",
          field: "email",
          headerFilter: (
            cell,
            onRendered,
            success,
            cancel,
            headerFilterParams
          ) => {
            return html.node`<input
              type="text"
              placeholder="Starts"
              style="width: 100%"
              placeholder="Filter"
              oninput=${(e) => {
                const field = cell.getColumn().getField()
                const filters = userTable.getFilters()
                const filter = filters.find(f => f.field === field)
                filter && userTable.removeFilter(...Object.values(filter))
                userTable.addFilter(field, 'starts', e.target.value)
              }}>`;
          }
        },
```

When we inspect the dom we can see that the placeholder is defined as empty and the type of the input element is set to search instead of text.

We can circumvent the issue by packing the the input in a span element which will have the empty placeholder and empty type defined.

I created a codepen to highlight this possible bug. https://codepen.io/dbauszus-glx/pen/BaYgwMR

**Comment by olifolkerd** [comment]
Hey @dbauszus-glx 

That does not look like it has been structured correctly.

Please see the [Custom Editor Docs](http://tabulator.info/docs/5.2/edit#edit-custom) for how to correctly build your custom editor, which is then used as the header filter

Cheers

Oli :)

**Comment by dbauszus-glx** [comment]
I am afraid that doesn't work as outlined in the documentation.

Instead of using uhtml I am now building the input element using createElement and assigning the type and placeholder with setAttribute.

```JS
var input = document.createElement("input");
input.setAttribute("type", "text");
input.setAttribute("placeholder", "Starts");
input.style.width = "100%";
input.oninput = (e) => console.log(e);
return input;
```

The input element is still rendered as type search with an empty placeholder.

```html
<input type="search" placeholder="" style="width: 100%;">
```

I have updated the codepen to show the behaviour https://codepen.io/dbauszus-glx/pen/BaYgwMR

Will dig a little into the tabulator code to see whether I can find where the issue originates.

**Comment by olifolkerd** [comment]
Yes, that is because the placeholder is set using the `headerFilterPlaceholder` prop, 

As outlined in the "Placeholder Text" section of the [Header Filter Docs](http://tabulator.info/docs/5.2/filter#header)

**Comment by dbauszus-glx** [comment]
I see. Thanks for clarifying. How can I set the input type?

**Comment by olifolkerd** [comment]
Hey @dbauszus-glx 

Im unsure why you need a custom input looking at your code, you are just using an input edtior and Tabulator already has one of those built in: http://tabulator.info/docs/5.2/edit#editor-input

Just use that one, the only thing you need to do is set your header filter function, which Tabulator comes with may prebuilt ones that will do the job for you: http://tabulator.info/docs/5.2/filter#func-builtin

If you want it to be a number type input, then there is already a `numeric` editor that will do this for your, complete with all the setup options you will need: http://tabulator.info/docs/5.2/edit#editor-number

Cheers

Oli :)

**Comment by dbauszus-glx** [comment]
We don't need a custom input but were looking for a way to apply some logic to an element which is linked to the same data source. I have an openlayers map control which shows the same locations from the tabulator table. I wanted to apply the same filter to the map control as in the table. I am now able to do this by adding our logic to either the filterFunction or updating the map control after the success() call in the input change event.
