### ISSUE TITLE
Set a row to always be on bottom and not sortable?

### ISSUE THREAD

**Issue by dakuwan** [olifolkerd/tabulator#382]
Is it possible to anchor a row to the bottom of the table and make it not sort?  I have a total row in my tables and I'd prefer if it always appeared on the bottom while all other rows can sort based on the header clicks.  Essentially a table footer.

I'm also trying to color it differently but no luck so far but if i can't anchor it on the bottom then i won't need to worry about it being colored separately.

Thanks

**Comment by olifolkerd** [comment]
Hey,

if you are running on the latest version of Tabulator (3.1) you can use the new ***footerElement*** option to define your own table footer element.

```js
$("#example-table").tabulator({
    columns:[...]
    footerElement:$("<div class='tabulator-footer'><button>Custom Button</button></div>"); //set custom table footer with custom button
});
```
Let me know if that is what you are after.

Cheers

Oli

**Comment by dakuwan** [comment]
I saw this but that would not be part of the table right?  Essentially i have a total row with totals for each column so want it to show as part of the table.  In my old code i had this in a <tfoot> and used tablesorter.  Tablesorter would do it's sort but ignore anything in put in the footer.  Does that make sense?

I'm planning on using the footer for my download CSV button when i saw it was there.  Also love the library and replacing all my tables with it. 

Thanks

**Comment by olifolkerd** [comment]
Ahh i see what you mean,

A calcs row is actually on the road-map but im afraid it is a couple of months away at the moment.

If you want to do it manually then you could still use the ***footerElement*** option with a number of divs in for each of the columns, then use the ***columnResized*** and ***columnMoved*** callbacks to ensure the divs match up with the columns.

**Comment by michael-ts** [comment]
@olifolkerd Is there some way to make this row more interactive?  I am trying to create a fixed row at the bottom of the table that let's me enter a value for certain columns, with a button below each that when clicked applies that value to every cell in that column.   I tried returning HTML and a DOM element from my calc function, but it seems to only expect a string.  I also considered a footer, but what Tabulator calls a footer is different from the HTML concept of a footer, the latter of which is what I would need.  Using a tabulator footer to manually trying to create a row that appears to be part of the table (including all changes such as when columns are hidden) seems insanely complete or impossible?

Or maybe there is some other way to accomplish this that I am missing?
