### ISSUE TITLE
Allow Authorization header for Tabulator built in request

### ISSUE THREAD

**Issue by vneal2** [olifolkerd/tabulator#3823]
I am trying to implement a tabulator table with server side pagination using the tabulator built in ajax url and config.

I have been able to get ajax fetch() request working separately but I want to use the built in pagination and I keep getting a 401 error as I think the ajax request is ignoring the headers : { "Authorization": token} 

![image](https://user-images.githubusercontent.com/72927695/175914550-4c012fb9-abea-41cc-86fc-d312eda8d1d4.png)

I have tried the beforeSend function and an ajaxSetup with the token which haven't worked either. Is it possible to allow for the Authorization token to be picked up from the ajaxConfig headers?

**Comment by olifolkerd** [comment]
Hey @vneal2 

You can already set any headers you like on the request in the `ajaxConfig` object.

Checkout the [Ajax Documentation](http://tabulator.info/docs/5.2/data#ajax-advanced) for more details

Cheers

Oli :)
