### ISSUE TITLE
Filter dropdown is missing all available options

### ISSUE THREAD

**Issue by pni-swilliams** [olifolkerd/tabulator#3824]
**Describe the bug**
In Tabulator 4.9.3, if you added the following to a column, then it would automatically populate the filter dropdown with all available options for that column:
`
{
    headerFilter: 'select',
    headerFilterParams: { values: true },
    /* ... other fields */
}
`

Now in 5.2.7, this doesn't work. The dropdown will simply say "No Results Found". I do notice a warning which states "The select editor has been deprecated, please use the new list editor". I haven't been able to locate documentation regarding this change on http://tabulator.info/ but I assume it wants me to replace `headerFilter: 'select',` with `headerFilter: 'list,`. If I do that, then the warning goes away, however the dropdown still says "No Results Found".

**Tabulator Info**
5.2.7

**Working Example**
YOU MUST include a link to a JS Fiddle or Codepen that demonstrates the problem, it is very hard to diagnose an issue from a simple description.

Example of desired behavior with 4.9.3: https://jsfiddle.net/wo46pmuv/2/

Example of it not working in 5.2.7 after changing `headerFilter: 'select',` to `headerFilter: 'list,` https://jsfiddle.net/wo46pmuv/3/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://jsfiddle.net/wo46pmuv/3/
2. Click "Load Data" button.
3. Click on "filter..." under "Bool test" or ""String test"

**Expected behavior**
The dropdown should contain all available filter options for that column.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS v12.3.1
 - Browsers:  Brave (v1.38.119), Safari (v15.4), Electron (v18.3.0)

**Additional context**

**Comment by olifolkerd** [comment]
This is because the new list editor uses the valuesLookup property instead. As the upgrade guide states. This is a new editor and the old params do not directly map over

Have a read through the list editor document. It explains all the possible configuration options http://tabulator.info/docs/5.2/edit#editor-list

Cheers

Oli :)
