### ISSUE TITLE
Column Resize on addRow

### ISSUE THREAD

**Issue by LondonWebFactory** [olifolkerd/tabulator#3827]
Hi Oli

**Describe the bug**
I am adding data to the table using addRow. When the data reaches the bottom of the table the column width resets to the default width.  I created 20 second [video](https://photos.app.goo.gl/WhtMfn7gXHF99LyF7) showing the issue.

**Tabulator Info**
5.2.7

**Working Example**
[https://codepen.io/LondonWebFactory/pen/wvmvKLP](https://codepen.io/LondonWebFactory/pen/wvmvKLP)

**To Reproduce**
1. Load Data
2. Resize Column 1
3. Add More Data
4. Column Initially Keeps New Width
5. When Data Gets to Bottom of Table Column Reverts to Default Width

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Browser: Chrome
 - Version: 103.0.5060.53

**Comment by olifolkerd** [comment]
This is related to the issue in #3756 which has now been fixed on the 5.3 branch, which will be released in a couple of weeks.

Cheers

Oli :)

**Comment by LondonWebFactory** [comment]
Many thanks Oli :)

Kind Regards,
Adrian
