### ISSUE TITLE
First select after filtering doesn't respond.

### ISSUE THREAD

**Issue by sanleong** [olifolkerd/tabulator#383]
Hi,
I have a table with "selectable: true," option. and Filter in the header. The problem is when I try to select a row after apply a filter the program doesn't respond to the 1st click. I have to do a 2nd click and then the selectable start to work as expected. If this a normal behavior or do I have something wrong in my code? 
I think that is related with the loss of focus, but is kind of confuse for the user to understand that. Is there a workaround for this?

`$("#preset-table").tabulator({
                        sortable: true,
                        height: "400px", // set height of table (optional),
                        sortBy: "Name",
                        sortDir: "asc",
                        columns: [ //Define Table Columns
                            { title: "Select preset(s) (Total:" + chCount + ")", field: "Name", width: "100%", headerFilter: "input" }
                        ],
                        selectable: true,

                        
                        rowClick: function (e, id, data, row) { 
                            var cssVal = row.css

                            var index = -1;
                            if (satSel.length > 0) {

                                index = satSel.indexOf(data.Name);

                            }
                            if (index == -1) {
                                satSel.push(data.Name);

                            
                            } else {
                                satSel.splice(index, 1);

                             
                            }
                           
                            
                               
                            
                        },
                    });`

**Comment by olifolkerd** [comment]
Hey,

The issue was being caused because clicking out of the input box caused a filter event immediately after the click on the row which was redrawing the table preventing the click.

I have just pushed an update to the master branch with a fix for this, i will make it into the production release next month.

Cheers

Oli

**Comment by sanleong** [comment]
Hi Oli,
Is this change will be available for pre-3 versions? I'm using 2.12 right now.

Regards,
Gilberto Leon

On Jun 19, 2017, at 4:26 PM, Oli Folkerd <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey,

The issue was being caused because clicking out of the input box caused a filter event immediately after the click on the row which was redrawing the table preventing the click.

I have just pushed an update to the master branch with a fix for this, i will make it into the production release next month.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey Gilberto ,

Im afraid not, Tabulator has had a complete rebuild in version 3.0 which make the header filters much easier to use, it wouldn't be be a quick fix for 2.12 im afraid, though i could look at giving you some instructions if you're really stuck.

I would strongly recommend moving to 3.1 Tabulator is now much more efficient and has a ton of new features and fixes, there any a few tweaks to property name etc for the change over, but i would be happy to guide you through it. some users have also created a some issues on here, detailing the steps the took for the transition.

Cheers

Oli

**Comment by sanleong** [comment]
Thanks Oli,
I have several tables that depends on this version and have to weight if it worth to redo all over. If you have the time and can give me some insight on
how to fix it myself maybe I can do it and post it on your github for the previous versions.

Once again thanks for a great library and the effort to help others.
Regards,
Gilberto Leon

On Jun 19, 2017, at 4:39 PM, Oli Folkerd <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey Gilberto ,

Im afraid not, Tabulator has had a complete rebuild in version 3.0 which make the header filters much easier to use, it wouldn't be be a quick fix for 2.12 im afraid, though i could look at giving you some instructions if you're really stuck.

I would strongly recommend moving to 3.1 Tabulator is now much more efficient and has a ton of new features and fixes, there any a few tweaks to property name etc for the change over, but i would be happy to guide you through it. some users have also created a some issues on here, detailing the steps the took for the transition.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey No problem,

Having looked into it a bit more it should be fairly simple for you,  if you open your tabulator.js file on line ***3265*** you should find a blank line of code below an if statement.

You will need to insert the following snippet into this gap:
```js
if(cellEditor.attr("type")== "text"){
    cellEditor.attr("type").off("change blur");
}
```

Let me know if that works for you.

Cheers

Oli

**Comment by sanleong** [comment]
Hi Oli,

Unfortunately it doesn't work...

This is the error on console after the change... It seems to me that tabulator wasn't loaded...


jquery-1.10.2.js:516

jquery-1.10.2.js:516 Uncaught Error: cannot call methods on tabulator prior to initialization; attempted to call method 'redraw' at Function.error (http://localhost:51780/Scripts/jquery-1.10.2.js:516:9) at HTMLDivElement.<anonymous> (http://localhost:51780/Scripts/jquery-ui-latest.js:520:15) at Function.each (http://localhost:51780/Scripts/jquery-1.10.2.js:657:23) at init.each (http://localhost:51780/Scripts/jquery-1.10.2.js:266:17) at init.$.fn.(anonymous function) [as tabulator] (http://localhost:51780/Scripts/jquery-ui-latest.js:516:9) at showSatScreen (http://localhost:51780/Scripts/recommend.js:328:41) at HTMLDivElement.activate (http://localhost:51780/Scripts/recommend.js:318:37) at $.(anonymous function).(anonymous function)._trigger (http://localhost:51780/Scripts/jquery-ui-latest.js:821:13) at $.(anonymous function).(anonymous function)._superApply (http://localhost:51780/Scripts/jquery-ui-latest.js:421:37) at $.(anonymous function).(anonymous function)._trigger (http://localhost:51780/Scripts/jquery-ui-latest.js:14321:16)
﻿

Just to let you know. If you don't have time to look at it is ok. Thanks for your effort.

Best regards

Gilberto



________________________________

**Comment by olifolkerd** [comment]
My Bad,

There was a typo there, it should be:
```js
if(cellEditor.attr("type") == "text"){
    cellEditor.off("change blur");
}
```

**Comment by sanleong** [comment]
Dude,

That was awesome. It worked like a charm. Thanks a lot buddy.

Regards

Gilberto



________________________________

**Comment by sanleong** [comment]
Do you gonna apply the fix to the official version?

Regards,
Gilberto Leon

On Jun 21, 2017, at 3:34 PM, Oli Folkerd <notifications@github.com<mailto:notifications@github.com>> wrote:


My Bad,

There was a typo there, it should be:

if(cellEditor.attr("type") == "text"){
    cellEditor.off("change blur");
}

**Comment by olifolkerd** [comment]
Fixes are applied to the latest version as it is released, issues raised in 2.11 were fixed in 2.12 and so on.

Im afraid I only have the time available to work on one release at a time, all fixes are always applied to the next release. this fix was applied to version 3.1

Cheers

Oli

**Comment by sanleong** [comment]
Understand,
If I may, and you allow it, I can do the change for version 2.12. Only if you want it.

Regards,
Gilberto Leon

On Jun 21, 2017, at 6:10 PM, Oli Folkerd <notifications@github.com<mailto:notifications@github.com>> wrote:


Fixes are applied to the latest version as it is released, issues raised in 2.11 were fixed in 2.12 and so on.

Im afraid I only have the time available to work on one release at a time, all fixes are always applied to the next release. this fix was applied to version 3.1

Cheers

Oli

**Comment by olifolkerd** [comment]
Yeah, That would be great!

Submit the pull request and i will get that approved :)

**Comment by sanleong** [comment]
Hi Oli, 
We have a side effect on the fix. Now, when you submit a process on the screen, the selected rows in the table are cleared. I found out it was the fix because I removed it and tested and the selected items are preserved after the submit execution. Any idea of what's going on?
