### ISSUE TITLE
Create input box in pagination to go on specific page

### ISSUE THREAD

**Issue by sunildeveloper07** [olifolkerd/tabulator#3832]
I have a table that has more than 10k records. With current pagination, It takes too much time to go on the specific page. For example, if I want to open a page number 5k or 5006 then currently it's not possible or takes too much time. I am not sure if this feature is already available in the current code. I tried to find it in the pagination section but didn't find anything regarding it.

I think this feature is also useful for other developers too who are playing with too many records.

**Comment by olifolkerd** [comment]
Hey @sunildeveloper07 

Thanks for the feedback,

I can totally see your usage case, but i think in the vast majority of cases this wouldn't be that useful and would clutter the UIe.

That being said it would be really easy for you to add this to the table footer without needing to modify Tabulator.

You can add custom content to the footer with the `footerElement` option, See [Footer Documentation](http://tabulator.info/docs/5.2/layout#footer) for more details.

You could then add a change event listener to that input and call the `setPage` function when the value is changed.

You could then put a listener on the tables `pageLoaded` event to then update that input to the current page when it changes.

I hope that helps,

Cheers

Oli :)
