### ISSUE TITLE
Tabulator 5 - Non fixed height table no longer updates height on filter apply

### ISSUE THREAD

**Issue by AlgirdasR** [olifolkerd/tabulator#3833]
**Describe the bug**
Non fixed height table no longer updates height on filter, table height remains the same. 
It seems that 
this.table.rowManager.adjustTableSize();
is no longer called as it used to be in version 4

I applied a quick fix for my project by calling
this.table.rowManager.adjustTableSize();

in the 
function refreshData

**Tabulator Info**
5.2.7

**Working Example**
Fiddle for Tabulator 4.9.3
https://jsfiddle.net/chg0vmo5/1/

Fiddle for Tabulator 5.2.7
https://jsfiddle.net/yfs0mw6L/

**To Reproduce**
Enter filtering data to header filter

**Expected behavior**
Table height to change based on filtered rows like it does in 4.9.3

**Comment by olifolkerd** [comment]
Hey @AlgirdasR 

Thanks for the info, i have pushed a fix for this to the 5.3 branch that should be released in a week or so.

Cheers

Oli :)
