### ISSUE TITLE
Destroy fails on table which has groups

### ISSUE THREAD

**Issue by AlgirdasR** [olifolkerd/tabulator#3834]
**Describe the bug**
If a table has grouping (groupBy is set), exception is thrown on destroy method call.

**Tabulator Info**
5.2.7

**Working Example**
https://jsfiddle.net/ndwb5y2j/1/

**To Reproduce**
Click "Destroy" button

**Expected behavior**
Table is destroyed

**Additional context**
It works on 4.2.9. Destroy also works if 
groupBy: 'type',
is commented out

**Comment by olifolkerd** [comment]
Hey @AlgirdasR 

I have pushed a fix for this to the 5.3 branch that should be released in a week or so.

Cheers

Oli :)

**Comment by AlgirdasR** [comment]
This bug seems to persist even in 5.3

'Uncaught TypeError: Cannot read properties of undefined (reading 'add')'
when table.destroy(); is called

I have updated the fiddle to use 5.3
https://jsfiddle.net/Lasph5tg/1/
