### ISSUE TITLE
groupBy and topCalc issue on 5.2.7

### ISSUE THREAD

**Issue by tsiporn** [olifolkerd/tabulator#3836]
**Information**
Tabular: 5.2.7

**Fiddle**: https://jsfiddle.net/tsiporn/zL3vcfxp/95/

**Problem Description**
2 issues below;
1. Require to click Group button (groupBy) **TWICE!!** to get the groupBy action (compare to a SINGLE CLICK for Filter (setFilter). 

2. **topCalc lost** after Group and Upgroup (groupBy="").  Reload the entire page helps but inconvenient.

**Comment by olifolkerd** [comment]
Hey @tsiporn 

thanks for the info,

I have pushed a fix for this to the 5.3 branch that should be released in a week or so.

Cheers

Oli :)
