### ISSUE TITLE
Col resize behaviour for textfields

### ISSUE THREAD

**Issue by michaelongithub** [olifolkerd/tabulator#384]
Hi Oli
for 3.1 cols with text formatted with textarea (initial rendering correct) cut off text on col smaller (no rowheight growth) and leave empty space when col wider. 

- Intended behaviour ?
- Options to control ?
- Planned ?

Thanks for info and cheers
Michael

**Comment by olifolkerd** [comment]
Hey Michael,

This is still a hangover from 3.0. as the virtual DOM was still maturing i removed the row height adjustment for resizing text areas until i could be confident the system could handle variable height row data.

Now that things have stabilized and the virtual DOM is rendering correctly for all row configurations i will look at adding that back in in the next release next month.

Cheers

Oli

**Comment by michaelongithub** [comment]
great, thanks for the info, cheers

**Comment by olifolkerd** [comment]
Hey,

I have just added textarea height resizing to the ***rendering_performance***improvements branch.

It will be included in this weekends 3.1.3 patch release.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey,

Version 3.1.4 has just been released with these fixes in.

Cheers

Oli
