### ISSUE TITLE
stopImmediatePropagation not working in cellContext callback

### ISSUE THREAD

**Issue by anishjana** [olifolkerd/tabulator#3841]
**Describe the bug**
Want to hide context menu on cell right click based on a parameter. However e.stopPropagation/ e.stopImmediatePropagation is not working as expected, resulting in showing menu anyway. 

**Tabulator Info**
- 5.2.7

**Working Example**
[jsfiddle](https://jsfiddle.net/anish_jana/u2k1bg0j/2/)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to any cell in name column
2. right click

**Expected behavior**
stop triggering context menu

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser: chrome
 - Version: latest

**Comment by olifolkerd** [comment]
Hey @anishjana 

That appears to be a misunderstanding on how to use the table,

The `cellContext ` event and `contextMenu` events are completely un-related.  They are managed from two different modules an their functionality is kept completely seperate.

While you can use `e.preventDefault` to stop the browser default context menu from opening, that is not how you stop the tabulator context menu from opening. 

If you want to choose when to display a menu, then the correct approach in tabulator is to pass a function to that menus option that then either returns the menu when you want it to be displayed or returns false to prevent the menu being displayed.

Checkout the [Menu Generator Function Documentation](http://tabulator.info/docs/5.2/menu#overview-generator) for a full explanation.

Cheers

Oli :)
