### ISSUE TITLE
Virtual dom fails to render row (pagination + scrollable container)

### ISSUE THREAD

**Issue by lekoala** [olifolkerd/tabulator#3845]
**Describe the bug**
When using pagination and when the table is within a scrollable container, the virtual dom isn't able to display rows properly (tested in chrome/firefox)

**Tabulator Info**
5.2.7

**Working Example**
https://codepen.io/lekoalabe/pen/bGvEBrL

**To Reproduce**
Click on the pagination
Scroll down
The rows are not displayed until the end

**Expected behavior**
Virtual dom renders rows regardless

**Screenshots**
<img width="532" alt="image" src="https://user-images.githubusercontent.com/250762/177732948-3d24d743-f4da-4d61-a337-149b35a466a6.png">

**Additional context**
using renderVertical: "basic" works fine, so it's really a vdom issue

ps : sorry for reporting three issues at once, let me know if I can help to solve them

**Comment by olifolkerd** [comment]
Hey @lekoala 

Yeah, that should be switching into basic mode when paginating like that, i will look into getting a patch out for that.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @lekoala 

Could you please provide a bit more info on the issue, i seem to be having trouble replicating it

i may have been a bit confused as to the original issue you were experiencing, on your fiddle i had originally assumed you were referring to the data missing in some of the columns, but i can see on closer inspection i can see that is just the data is being added without those values.

I can see in your screen shot it looks like there is whitespace below the rows but i have tested your code pen in both firefox and chrome and seem unable to replicated the issue.

Cheers

Oli :)

**Comment by lekoala** [comment]
@olifolkerd i've updated the codepen to the latest tabulator

in order to replicate:
- navigate in the pagination
- then scroll down, and you will see that some of the rows will not be displayed by the vdom

switch to renderVertical: "basic" fixes the issue

**Comment by olifolkerd** [comment]
On further inspection, this is happening because the containing element has no height so when you set it to 100% it has no defined height to work to.

If you set it into a container with a height then this is not an issue, also if you set no height on the table at all this is also not an issue.

Cheers

Oli :)
