### ISSUE TITLE
Email release notes link = 404

### ISSUE THREAD

**Issue by LondonWebFactory** [olifolkerd/tabulator#3848]
Hi Oli

A quick note to say that the release notes  link In the email that you just sent out about the 5.3 release has a 404 for error.

kind regards 
Adrian 

**Describe the bug**

**Tabulator Info**
- Which version of Tabulator are you using?

**Working Example**
YOU MUST include a link to a JS Fiddle or Codepen that demonstrates the problem, it is very hard to diagnose an issue from a simple description.

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by olifolkerd** [comment]
What email?

**Comment by olifolkerd** [comment]
I havnt sent an email???

I put a post on the discord channel and i made a release on git hub, but both of those links are working for me.

Where abouts did this email come from @LondonWebFactory ?

Cheers

Oli :)

**Comment by LondonWebFactory** [comment]
I received an email at 7:26 and it had the following text… 

This release has 2 assets:

Source code (zip)
Source code (tar.gz)
Visit the [release page](https://github.com/olifolkerd/tabulator/releases/tag/5.3.0) to download them.

when I clicked on the release notes link it came up 404. However, it’s working now.

many thanks 
Adrian

**Comment by olifolkerd** [comment]
Hey @LondonWebFactory 

Ahh, you are an eager beaver, yeah i normally do the release and then update the website, you must have clicked through in the couple of minutes the website was updating)

I must admit i had no idea GitHub sent out an email, i will do things in a different order next time so that dosnt happen.

Cheers

Oli :)

**Comment by LondonWebFactory** [comment]
PS: In case it helps - here's a screenshot of the email I received. 

![2022-07-08_08-52-36](https://user-images.githubusercontent.com/26409558/177944587-96515d67-7ba3-4a4b-8898-0103561793a0.png)
