### ISSUE TITLE
Redrawing Table - including headers - when hidden table becomes visible

### ISSUE THREAD

**Issue by alainpannetier** [olifolkerd/tabulator#385]
I have 2 different tabulator instances in 2 different tabs.

At page creation time, both tabulators are built (including the one in the inactive tab). 
However the once inside the hidden/background tab has headers with tabulator-header class height: 0px.

This is because - line # 1298 (of dist) we measure the innerHeight of an element in a hidden DOM tree.

There's not much to do to get the height right from the start. However, one can decide to redraw the table when the parent tab becomes active.  Only issue: that does not redraw the header - if my experiments are correct.

Still working on it, but a hint would be welcome.

**Comment by olifolkerd** [comment]
Hey,

There were some issues with the ***redraw*** command in version 3.0, give it a go with 3.1.

You can also add the optional ***true*** to force a redraw of everything:
```js
$("#example-table").tabulator("redraw", true);
```

Let me know if that helps


Cheers

Oli

**Comment by olifolkerd** [comment]
on further inspection the was an issue with the redraw function.

I have just updated the 3.1 release, if you pull it down again the above code should work for you.

Thanks

Oli

**Comment by alainpannetier** [comment]
Thanks Oli. Works perfectly. :+1: 
I took the latest from master branch and added a handler for the 'onTabShow' (using primefaces as a JSF2 jar-bundler) with just a redraw - true and it's all good now.
Thanks for the responsiveness (demo tomorrow :) )

**Comment by ritesh058** [comment]
hello,
I am new to tabulator and currently using "tabulator-tables", "version": "4.0.4".

I have multiple tab like dashboard,search, view report and  tabulator is used with search tab.
The problem arise when search tab is used at different position(when Tabular CSS is hidden) other the first position.

The code work fine if tabulator used as default and show the data in order
Code:-
var table = new Tabulator("#searchContainer", {
        columns: DataCollHead,
        layout:"fitColumns",        
        height:"auto",
        pagination:"local",
        paginationSize:20,
        clipboard:true,
        clipboardPasteAction:"replace",
        responsiveLayout:"collapse",        
    })
    var tableData = DataCollList;
    table.setData(tableData);   

Read about redraw() method but unable to implement in my code.....request you guidance to the issue

Thanks 
ritesh
