### ISSUE TITLE
Tab behavior with "editor: 'list'" doesn't honor the tabindex

### ISSUE THREAD

**Issue by johnbrun** [olifolkerd/tabulator#3850]
**Describe the bug**
If you use the 'Tab' key to focus on a 'list' type editor element then pressing 'Tab' again brings you to the next row's 'list' editor element instead of continuing along that same row.

**Tabulator Info**
5.2

**Working Example**
https://jsfiddle.net/sv95rzy4/3/

**To Reproduce**
1. Go to the jsfiddle link above
2. Click on 'Alice' in the table
3. Press the 'Tab' key. This opens the select menu in the 'Level' column
4. Press the 'Tab' key again. This goes to the next row's 'Level' column and activates the select menu

**Expected behavior**
Tab should go to the next element in the same row, honoring the tabindex. In this case it should go to the button in the 'Actions' column in the first row. 
Interestingly if you press 'Enter' when the select menu is open then the menu closes and you can tab to the button in the 'Actions' column in the same row with two 'Tab' presses. Not an ideal workaround, but could be used in the short-term.
I have two ideas for better behavior:
1) A single 'Tab' should close the opened select menu and proceed to the button in the 'Actions' column. 
2) OR 'Enter' should be required to open the select menu. So 'Tab' into the select element just highlights it and doesn't open the select menu until 'Enter' is pressed.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome / Firefox 
 - Version: 102.0.5005.63 / 101.0.1 
(Did not test with other browsers)

**Smartphone (please complete the following information):**
n/a

Thank you!

**Comment by olifolkerd** [comment]
Hey @johnbrun 

You example is working exactly as expected. when using an editor in Tabulator the navigation of the table is from editor to editor, if you had another editable column next to your list you would find that navigation moves directly to that cell.

This is the default functionality for the Tab key with Tabulator, which is managed with the keybindings module. The good news is that you can customise this behaviour using a custom key binding.

Checkout the [Keybindings Documentation](http://tabulator.info/docs/5.3/keybindings) for detailed instructions on how to customize the tab action

Cheers

Oli :)
