### ISSUE TITLE
Cannot set header context menu on sub-column of grouped menu

### ISSUE THREAD

**Issue by alexkzone** [olifolkerd/tabulator#3851]
Hi,

I failed to set a context menu on the sub-column of a grouped column (tested on 5.3 and 5.2.7 versions)
Here is my test case:
[https://jsfiddle.net/hdbp1tmv/6/](https://jsfiddle.net/hdbp1tmv/6/)

I can set the context menu on the ungrouped column ("Name" in my example)
And context doesn't work on "Date Of Birth"

**Comment by olifolkerd** [comment]
Hey @alexkzone 

Thanks for the headsup, there was an issue with the way the interaction monitor was tracking events on grouped columns, i have pushed a fix to the master branch and will include it in tommorows patch release.

Cheers

Oli :)
