### ISSUE TITLE
Issue upgrading version 5.2.3 to version 5.2.4 or 5.3 - Datatree : getTreeParentRoot 

### ISSUE THREAD

**Issue by Catvert** [olifolkerd/tabulator#3852]
Hello,

First of all, I can't reproduce this on JSFiddle or Codepen, I apologise for this.
I have been using tabulator for a few months/years but recently, when I wanted to upgrade to 5.3 (I was in 5.2.3), I get an error like this when using the dataTree and groupBy functionnality :
```
Uncaught (in promise) TypeError: o.modules is undefined
    getTreeParentRoot http://itcs.localhost:8000/build/assets/offer-wysiwyg.6df44db0.js:3
    getRowGroup http://itcs.localhost:8000/build/assets/offer-wysiwyg.6df44db0.js:5
    recalcRowGroup http://itcs.localhost:8000/build/assets/offer-wysiwyg.6df44db0.js:3
    rowsUpdated http://itcs.localhost:8000/build/assets/offer-wysiwyg.6df44db0.js:3
    ...
```
I tried to track the problem and came to the conclusion that something broke in the version 5.2.4.
It seems to be related to this line : https://github.com/olifolkerd/tabulator/blob/ef7485e98ce1d6184c69867b5e86db9dac909b86/src/js/modules/DataTree/DataTree.js#L435, added in 5.2.4.

I can trigger this bug on my firefox/chromium with this simple example (but not on JSFiddle/Codepen) : 
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Tabulator bug</title>

    <link href="https://unpkg.com/tabulator-tables/dist/css/tabulator.min.css" rel="stylesheet">
    <script type="text/javascript" src="https://unpkg.com/tabulator-tables/dist/js/tabulator.min.js"></script>
</head>

<body>
    <div id="table"></div>

    <script lang="js">
        let tabulator;

        tabulator = new Tabulator("#table", {
            groupBy: "group",
            dataTree: true,
            resizableRows: true,
            columns: [
                //Define Table Columns
                {
                    title: "Name",
                    field: "name"
                }
            ],
        });

        tabulator.on("tableBuilt", function () {
            tabulator.addRow({ "group": 0, "name": "hello" });
        });
    </script>
</body>

</html>
```
Thanks for your help!

**Comment by olifolkerd** [comment]
Hey @Catvert 

Thanks for the info. I have pushed a fix for this to the master branch and will include it in this weekends patch release tommorow.

Cheers

Oli :)
