### ISSUE TITLE
Download nested data

### ISSUE THREAD

**Issue by JAIC-be** [olifolkerd/tabulator#3853]
Download data tree is set to true but data from the children is still not downloaded.
What could also help is being able to specify a level in the data tree for download.
I've tried using accessorDownload but are unsure how (and if) I can loop over the children instead of returning an array.

_Originally posted by @JAIC-be in https://github.com/olifolkerd/tabulator/issues/2323#issuecomment-1181482335_

**Comment by olifolkerd** [comment]
Hey @JAIC-be 

This is not currently a feature im afraid, The child rows are not full rows in the table, they are visual only.

If you would like to see this as a feature, please create a [Feature Request](https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Suggested+Feature&template=feature_request.md&title=) and fill in the required info.

Cheers

Oli :)
