### ISSUE TITLE
layout fitColumns + responsiveLayout collapse horizontal scrollbar flashing on Chrome

### ISSUE THREAD

**Issue by antman3351** [olifolkerd/tabulator#3856]
**Describe the bug**
Horizontal scrollbar appears when stretching columns with `layout: fitColumns`. ( Chrome and FireFox )

If  `layout: fitColumns` is used with `responsiveLayout: collapse` on some cases the scrollbar starts appearing and disappearing causing a flashing effect ( on Chrome, but not FireFox ).

It seems more likely for the flashing to happen when no data is in the table ( like when loading by ajax while the loading message is shown, maybe because I use `maxHeight:80vh` instead of a fixed height? ) but can also happen with data in the table, I think when the horizontal scrollbar causes the vertical scrollbar to appear.

In the 1st screenshot you can see the flashing effect with no data.
In the 2nd screenshot you can see the horizonal scrollbar appear when making the HTML area bigger.

I'm not sure if it's the cause of the issue but in fitColumns.js commenting the following lines fixes the issue
```js
//increase width of last column to account for rounding errors
if(flexColumns.length && gapFill > 0){
	flexColumns[flexColumns.length-1].width += + gapFill;
}
```

**Tabulator Info**
5.3

**Working Example**
https://jsfiddle.net/fte7c3q4/4/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle:
1. Open fiddle
2. Close the console
3. Resize (probably larger) the HTML area until the horizontal scrollbar starts flashing
4. ( If you can't reproduce it with the data, try with an empty table )

**Screenshots**
![tabulator-chrome-scroll-bug1](https://user-images.githubusercontent.com/16060462/178523451-fdff9b11-075e-4cfa-84ef-3e773c6a02b0.gif)

![tabulator-chrome-scroll-bug2](https://user-images.githubusercontent.com/16060462/178523474-0a0277f3-fe22-4b2e-b9e7-680e1a6a1d2c.gif)

**Desktop (please complete the following information):**
 - Windows 10 Pro
 - Chrome 
 - Version 103.0.5060.114 (Official Build) (64-bit)

**Additional context**
This is the second time that I write this because I stupidly clicked jsFiddle link to check it was the right version while in Preview and lost what I wrote 🙄, so I hope I included everything I wrote the first time 😬

Thanks! Ant.

**Comment by olifolkerd** [comment]
Hey @antman3351 

hanks for the inf, i will look into this further.

Just as a quick note, for your `minWidth` and `maxWidth` column definition options, you should be passing in an integer not a string.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @antman3351 

I have pushed a fix for this to the master branch and will include it in tommorows patch release.

Cheers

Oli :)

**Comment by antman3351** [comment]
Super, Thanks!

**Comment by martijnvankekem** [comment]
Happening on 5.4 as well, using fitColumns with 2 columns, with widthGrow: 1 on the first column, and width: 150 on the second.
