### ISSUE TITLE
Small issue with Format Page (tooltips have moved)

### ISSUE THREAD

**Issue by johnbrun** [olifolkerd/tabulator#3857]
**Website Page**
http://tabulator.info/docs/5.3/format

**Describe the issue**
There is no "Tooltips" section. It exists in the table of contents at the top, but there is nothing about "Tooltips" anywhere else on the page. Looks like tooltips have moved to here: http://tabulator.info/docs/5.3/menu#tooltips

**Comment by olifolkerd** [comment]
Hey @johnbrun 

Thanks for the headsup, i will remove that unneeded link from the contents in this weekends site update.

Cheers

Oli :)
