### ISSUE TITLE
Double click on a cell should select the text of just that cell and not other columns

### ISSUE THREAD

**Issue by vinitkp** [olifolkerd/tabulator#3859]
**Describe the bug**
Double click on a cell should select the text of just that cell and not other columns. This bug was introduced in version 5.0. Till 4.9, double click on a cell was working fine and just selecting text of that cell.
**Tabulator Info**
- Which version of Tabulator are you using?
5.2
**Working Example**
Not working fine - 
http://tabulator.info/examples/5.2
Working Fine - 
http://tabulator.info/examples/4.9

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. [Go to '...'] http://tabulator.info/examples/5.2
2. Go to the first table - [Virtual DOM - Vertical](http://tabulator.info/examples/5.2#virtual-dom)
3. Steps - Double click on any cell in
4. The text from whole row gets selected

**Expected behavior**
Only text of that particular cell should get selected

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ios
 - Browser chrome
 - Version 103.0.5060.53
<img width="634" alt="Screenshot 2022-07-16 at 1 28 05 PM" src="https://user-images.githubusercontent.com/2684618/179346092-31a771f7-8be8-4b53-bb1a-ce284b115d0a.png">
<img width="933" alt="Screenshot 2022-07-16 at 1 27 02 PM" src="https://user-images.githubusercontent.com/2684618/179346097-f9fc2cd0-a856-43ad-b4f8-bb8a3c80af93.png">

**Additional context**

**Comment by olifolkerd** [comment]
Hey @vinitkp 

Thanks for the info. I have pushed a fix for this to the master branch and will include it in tomorrows patch release.

Cheers

Oli :)

**Comment by snowman** [comment]
But even in latest version https://tabulator.info/examples/6.3,
when double click on the cell to select text,
for example, when click on text of the `Name` field,
if click on first name, it'll temporary highlight(flash) left column (`ID`)
if click on last  name, it'll temporary highlight(flash) right columns (`Progress,Gender,Rating,Favourite Color,Date Of Birth`)

Although in the end it's select on the whole cell text correctly,
the flash(select then de-select) of other columns of text in the same row confuses me

![Image](https://github.com/user-attachments/assets/98a51d1f-cbe0-414b-a03c-81c2c79c9d7b)
