### ISSUE TITLE
Moving a child row does not persist the change

### ISSUE THREAD

**Issue by cacuestai** [olifolkerd/tabulator#3861]
Hello:

When moving a child row and checking the state of the table data after the rowMoved event, table.getData() does not report the change.

![possible-bug](https://user-images.githubusercontent.com/2236441/179411420-1c9a2ff5-27dc-4616-9889-75ebe8ad9762.jpg)

Greetings and thank you very much!

Carlos

**Comment by olifolkerd** [comment]
Hey @cacuestai ,

DataTree functionality does not currently support movable rows because it is ambiguous where a child should be moved if it is moved out of its parents. 

I will update the documentation to reflect this.

Cheers

Oli :)
