### ISSUE TITLE
Cannot read properties of undefined (reading 'indexOf') - Delete Rows with History

### ISSUE THREAD

**Issue by schipani** [olifolkerd/tabulator#3862]
The below error message can be observed when trying to delete rows from tabulator with History enabled.
![image](https://user-images.githubusercontent.com/50174482/179429761-8aed0dec-b9e2-436e-83ab-c522e82d9c56.png)

**Tabulator Info**
v5.3.0

**Steps to Reproduce**
1) Select a row from the table
2) Click the delete button

**Working Example**
https://codepen.io/schipani/pen/xxWgQGJ

**Comment by olifolkerd** [comment]
Hey @schipani 

Thanks for the info, i have pushed a fix for this to master and will include it in the patch release tomorrow.

Cheers

Oli :)
