### ISSUE TITLE
Console.log("choose")

### ISSUE THREAD

**Issue by DavLagoHern** [olifolkerd/tabulator#3863]
**Describe the bug**
When choose option on editor:"list" show in console "choose", the error is in line 13418

**Tabulator Info**
- 5.3
- 
**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Create table with editor:"list"
2. Click on some option
3. See console log

**Comment by olifolkerd** [comment]
Hey @DavLagoHern 

Cant replicate this my end, not can i see the console log anywhere in the source. It is possible one of the dist files didnt get fully updated in the last release.

Checkout the 5.3.1 release in a couple of days time and let me know if you still have an issue.

Cheers

Oli :)
