### ISSUE TITLE
RTL directionality glitches

### ISSUE THREAD

**Issue by yarons** [olifolkerd/tabulator#3865]
**Describe the bug**
Presenting Tabular in Hebrew has some glitches (the sorting arrows are misplaced.

**Tabulator Info**
- 5.3

**Working Example**
https://wiki.documentfoundation.org/Documentation/Calc_Functions/List_of_Functions/he

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to 'https://wiki.documentfoundation.org/Documentation/Calc_Functions/List_of_Functions/he'
2. Look at the sorting arrows and filter placeholder.

**Expected behavior**
Should be aligned left.

**Screenshots**
![IMG_20220719_231752.jpg](https://user-images.githubusercontent.com/406826/179840596-8388641b-4035-4a9c-9ae8-c087e30a695c.jpg)

Orange: misplaced arrows (should be on the left).
Light blue: misaligned text (should be aligned right).

**Smartphone (please complete the following information):**
 - Device: Pocophone F1
 - OS: Android 10
 - Browser Firefox
 - Version Nightly (July 19, 2022)

**Additional context**
May potentially also effect Persian, Arabic, Urdu, etc.

**Comment by olifolkerd** [comment]
Hey @yarons 

I cannot replicate this behaviour on any of the built in themes, everything seems to be correctly aligned when i use it.

Please create a [JS Fiddle](http://tabulator.info/community/jsfiddle) that contains a [Minimal Reproducible example](http://tabulator.info/community/mre). I can see on the site you are pointing to it isnt working, but there is no way for me to see how that table is setup, which themes is being used or if there is any external CSS interfering with the layout.

Cheers

Oli :)

**Comment by marmor** [comment]
One of the classes of BODY is sitedir-ltr, which is defined by CSS to set directions of all of the input fields to LTR, which affects the placeholder alignment:

.sitedir-ltr textarea, .sitedir-ltr input {
    direction: ltr;
}

Changing to sitedir-rtl, or removing it from the class list of BODY, or removing the above CSS, resolves the problem.

**Comment by olifolkerd** [comment]
I'm unsure how that directly related to this.

At this point it looks like there is external CSS interfering with the table.

Have you explicitly set the table into RTL mode?

If you feel this is a Tabulator issue i will need to see a minimal example that replicates this as everything is working fine my end

**Comment by marmor** [comment]
Hi Oli,
I'm not sure if your comment is to me or to the issue opener.
I just saw a strange class in his BODY, probably with nothing to do with Tabulator, and tried to suggest a solution by removing that class.
IMHO it has nothing to do with Tabulator, but if we can help this guy, why not?  ;-)
BTW: I plan to use RTL too (sometime in the far future...), and guess I'll find some glitches (there is already one thing that I'm sure I'll have a patch for).
And in any case, thanks for this great library!

**Comment by yarons** [comment]
Thanks @marmor!
Actually this is a problem with the way Wikimedia (TranslateWiki) have implemented your widget, I can try and ask if someone knows anything about it and send them the link to this discussion.
