### ISSUE TITLE
ajaxError function not catching Data Load Error

### ISSUE THREAD

**Issue by bruneaubrora** [olifolkerd/tabulator#3866]
**Describe the bug**
The ajaxError Call Back and the .catch used when we call the setData function on the table itself is not catching any ajax errors. I have tried both methods as shown in the documentation [here](http://tabulator.info/docs/5.3/data#ajax-errors). For the ajaxError callback sepcification, I receive a warning stating "Invalid table constructor option: ajaxError". Seems that the ajaxError specification is not being registered by tabulator.

**Tabulator Info**
Tabulator Version 5.2

**Working Example**
[jsfiddle example](https://jsfiddle.net/bruneaubrora/9bnao63j/1/)

**To Reproduce**
1.Run the program in jsfiddle
2. inspect the console to see the "invalid table constructor option: ajaxError" warning.

**Expected behavior**
I expect the documentation to reflect proper methodology for ajaxError callbacks and catching (Unless I am missing something and in fact am the root of the issue). And to be able to write custom code when such errors are caught.

**Desktop (please complete the following information):**
 - OS: Windows 19044.1766
 - Browser: Chrome
 - Version: 103.0.5060.114

**Comment by olifolkerd** [comment]
Hey @bruneaubrora 

Looks like there is abit of outdated documentation there, the `ajaxError` callback was removed in the 5.0 release and replaced with the `dataLoadError` event. you can find details of this in the [Data Events Docs](http://tabulator.info/docs/5.3/events#data)
I will get the docs updated this weekend.

Cheers

Oli :)

**Comment by bruneaubrora** [comment]
Thank Oli, that cleared it up.

One more question for you if you would be so kind. I am trying to get the body's response text from the error object specified as the first argument to the dataLoadError Callback. I do see that it is a readable stream. But I am wondering if we have to utilize the readable stream or if there is a property somewhere on that error object that I can reference otherwise?

**Comment by olifolkerd** [comment]
It is just uses the standard JavaScript fetch API, so it will be whatever the standard response object for this is https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

**Comment by YvesGomes** [comment]
`****''/github/behaviors/ajax-error'****`


[discord.gg/styless](discord.gg/styless)
