### ISSUE TITLE
tiny column (maxWidth) missaligns its header/contents

### ISSUE THREAD

**Issue by jaguarxii** [olifolkerd/tabulator#3869]
**Describe the bug**
Setting a column's maxWidth to any value less than "40" causes a missalignment between its header and its contents.
I would like to have a tiny column to display a color marker.

**Tabulator Info**
- 5.3.0

**Working Example**
[Sample](https://codepen.io/jaguarito/pen/bGvWPZp)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to the link above, it shows the missalignment between the column header and contents

**Expected behavior**
The column header should have the same width as its contents, by using the value set as "maxWidth".

**Screenshots**
![image](https://user-images.githubusercontent.com/8013436/180302251-fc6abff5-8096-4282-877a-eac3b9ab3c15.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser 
 - Waterfox G4.1.3.2
 - Chrome 103.0.5060.114 

**Smartphone (please complete the following information):**
 - Not tested on smartphone

**Comment by olifolkerd** [comment]
That is probably as a result of the max width being smaller than the min width which is 40 by default.

Have you tried setting your min width?

**Comment by jaguarxii** [comment]
Hi, I did not try setting minWidth, it actually works.

I thought setting maxWidth was the logical solution.

Thanks for your time
