### ISSUE TITLE
responsive nested table issue

### ISSUE THREAD

**Issue by ampminfo** [olifolkerd/tabulator#3870]
**Describe the bug**
Responsive table with nested responsive table using rowformatter.   Nested table does not get responsive like it should be.

**Tabulator Info**
version 5.3

**Working Example**
https://jsfiddle.net/w1xtkLgy/1/

**To Reproduce**
Shrink browser until main table get collapse into responsive mode and check the nested table if it does the same

**Expected behavior**
all tables should get collapsed into responsive mode

**Screenshots**
![2022-07-21_22h08_35](https://user-images.githubusercontent.com/7786859/180347516-a8c17c51-d185-4bd2-9d1b-d53f06924612.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Chrome 103.0.5060.134

**Comment by olifolkerd** [comment]
Tabulator does not support responsive nested tables. As it would lead to a very confusing table layouts
