### ISSUE TITLE
Horizontal Virtual Scrolling - cell and header misalignment in some cases 

### ISSUE THREAD

**Issue by rathboma** [olifolkerd/tabulator#3871]
I cannot replicate this myself yet, but it is a reported issue from other Beekeeper Studio users.

I've asked for GIFs and steps to replicate, so hopefully that can help narrow it down.

See https://github.com/beekeeper-studio/beekeeper-studio/issues/1299

![screenshot](https://user-images.githubusercontent.com/46631787/178858230-fdcb4b9b-0334-4ad5-b1b5-ce688a3c6712.png)

**Comment by olifolkerd** [comment]
Hey @rathboma 

That is an interesting one, which version of Tabulator are you on? 
did it only crop up in the latest release?
do you have an example table setup that might point me in the correct direction?

Cheers

Oli :)

**Comment by rathboma** [comment]
I'm on the latest version I think. I cannot reliably replicate it yet, lol. Working on it.

I've asked the users for steps to replicate, so we'll see what comes of it.

**Comment by jonas-hoebenreich** [comment]
I have the described problem with tables with many columns (and from the feeling if there are json/boolean columns):


https://user-images.githubusercontent.com/64426524/180614684-8787dea8-f8fc-4a0c-a876-479f2dd50f66.mp4



beekeeper studio version 3.5.1
Operating system: Ubuntu
Postgres database
table structure:
```
CREATE TABLE
  jsample.project_meta (
    gid bigint NOT NULL,
    fork boolean NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    pushed_at timestamp without time zone NOT NULL,
    codeql_since timestamp without time zone NOT NULL,
    size integer NULL,
    stargazers_count integer NULL,
    watchers_count integer NULL,
    languages json NULL,
    javascript_size integer NULL,
    has_issues boolean NULL,
    has_projects boolean NULL,
    has_downloads boolean NULL,
    has_wiki boolean NULL,
    forks_count integer NULL,
    open_issues_count integer NULL,
    license json NULL,
    is_template boolean NULL,
    is_random_sample boolean NULL,
    default_branch character varying(1024) NULL,
    number_pulls integer NULL,
    number_contributors integer NULL,
    criticality_score double precision NULL
  );

ALTER TABLE
  jsample.project_meta
ADD
  CONSTRAINT project_meta_pk PRIMARY KEY (gid)
```

**Comment by olifolkerd** [comment]
@rathboma I cant seem to replicate this on the 5.4 branch, would you mind having a look and seeing if it has been resolved.

There were some tweaks unrelated to this that might have resolved it 

Cheers

Oli :)
