### ISSUE TITLE
History Callbacks Documentation

### ISSUE THREAD

**Issue by beatrizsanchez** [olifolkerd/tabulator#3872]
**Website Page**
[Interaction History](http://tabulator.info/docs/5.3/history)

**Describe the issue**
In the [callbacks section](http://tabulator.info/docs/5.3/history#callbacks), there is a link to the [history callbacks documentation](http://tabulator.info/docs/5.3/callbacks#history) which is supposed to be a section under the callbacks page but the section does not seem to exist.. Could anyone point me to the place where documentation on history callbacks is located?

**Comment by olifolkerd** [comment]
These are now the [History Events](http://tabulator.info/docs/5.3/events#history) i will update the docs to fix the issue.

Cheers

Oli :)

**Comment by beatrizsanchez** [comment]
Thanks Oli 😊
