### ISSUE TITLE
SetData with url, params and ajaxoptions issue using pagination. Parameters not retained by the SetData function so losing it.

### ISSUE THREAD

**Issue by ampminfo** [olifolkerd/tabulator#3873]
**Describe the bug**
I'm using the setData function to query since I'm doing a dynamic load of data passing a parameters, can't define it on the table creation options....

 table.setData('http://URLHERE', {guid: myguid}, ajaxConfig)

On page change,  guid is lost and not sent to my API. I presume it because setData does not save the paramter for pagination use.

**Tabulator Info**
5.3

**Working Example**
Sorry can't provide ajax data to simulate on jsfiddle

**Expected behavior**
All parameters should be saved for pagination function to keep sending them to API.

**Screenshots**
First load of SetData:
![image](https://user-images.githubusercontent.com/7786859/180621955-2dcc20e5-cdbc-4a71-887e-7b6f56faa6bf.png)

Page change:
![image](https://user-images.githubusercontent.com/7786859/180621973-b708b2fe-5627-4a2e-bf2a-848e222acddc.png)

**Desktop (please complete the following information):**
- Windows 10 Pro
- Chrome 103...

**Comment by olifolkerd** [comment]
You can pass a function to the ajaxParams option that is called every time a request is made. You can use this to manage your changing parameters.

Does that solve your usage case?

**Comment by ampminfo** [comment]
does the pagination functions use that function?

**Comment by olifolkerd** [comment]
The Ajax module will do which is called by the pagination module.

All the pagination module does is workout the pagination params and then pass them to the Ajax module. It then merges them with other params set on table options

Give it a try and let me know how you get on.

**Comment by ampminfo** [comment]
So you mean that I pass it when creating the table and not using the SetData right?

**Comment by olifolkerd** [comment]
Correct, but as a function you can make sure it returns the correct params for each request as it is made

**Comment by ampminfo** [comment]
trigger setData(true) afterward?

**Comment by olifolkerd** [comment]
Just setData() should do it

**Comment by olifolkerd** [comment]
Or setPage to whatever page u want

**Comment by ampminfo** [comment]
var  GUID = function() {
       return {
         guid : this.drawer2GUID
       }
    },

 this.drawer2table = new Tabulator(this.$refs.drawer2ttable, {
      layout:"fitColumns",
      ajaxURL:"http://URL", //set url for ajax request
      ajaxConfig: 'POST',
      ajaxContentType:"json", // send parameters to the server as a JSON encoded string
      ajaxParams:  GUID,
..


![image](https://user-images.githubusercontent.com/7786859/180624076-28425359-7678-456e-8d30-d7a2fcf49865.png)

![image](https://user-images.githubusercontent.com/7786859/180624080-fc1e0b21-8708-4b5c-8f4f-6569c0ee555c.png)

I do not find why its not working... I see that it's looking for an object or array but tried to make my function return an object but did not work.

**Comment by ampminfo** [comment]
Just tried 

ajaxParams:  JSON.stringify(this.GUID),   

no error but does not load my params

**Comment by olifolkerd** [comment]
That is because you are not passing a function and returning the object as needed. Please look at the docs link I included in my first response it shows and example of how to do this

**Comment by ampminfo** [comment]
Lol I don't know where I answered but it's not here.

It work.. I had to bind the function to the this (of vusjs) to be able to access the variable.

thanks a lot
