### ISSUE TITLE
initialSort not working correctly when multi sorting

### ISSUE THREAD

**Issue by Icebreaker83** [olifolkerd/tabulator#3877]
`initialSort` doesn't sort data properly when multisorting.
![image](https://user-images.githubusercontent.com/24209614/180832618-40a30618-5b88-4870-9b87-33a41eb63ed3.png)
Array that I've passed to initialSort: `[{ column: 'id', dir: 'desc' }, { column: 'name', dir: 'asc' }]`
Order shoud be: 10, 7, 4, 1, 9, 6, ...

Tabulator version: 5.3.0

Example: [JSFiddle](https://jsfiddle.net/dusan_cankovic/p6jw071r/)

`table.setSort` has the same behaviour if `initialSort` is passed to setup options.
If there is no `initialSort` in setup options,  `table.setSort` works correctly.
Example: [JSFiddle](https://jsfiddle.net/dusan_cankovic/zb26hyp4/)
**To Reproduce correct setSort without initialSort**
1. click on `Set sort` button

Sorting is fine now

**Expected behavior**
Sort by id and name should be in order: 10, 7, 4, 1, ...

**Desktop:**
 - OS: Win10
 - Browser: Chrome
 - Version: 103.0.5060.134

**Comment by olifolkerd** [comment]
That is sorting as expected, that is the order the sort function are applied so it sorts the data by Id then resorts by name.

To get the sort you want either reverse the order of your intial sort array or use the sortOrderReverse:true setup option to do that automatically

**Comment by Icebreaker83** [comment]
> That is sorting as expected, that is the order the sort function are applied so it sorts the data by Id then resorts by name.
> 
> To get the sort you want either reverse the order of your intial sort array or use the sortOrderReverse:true setup option to do that automatically

Hi @olifolkerd
This is 100% bug. Your recommended solution achieves something completely different.
![image](https://user-images.githubusercontent.com/24209614/180963782-747c100a-1682-4645-87f1-47dc1b14507c.png)

How does it look in real project.
I have tables throughout project, some with local and some with remote data. All sorting, filtering, pagination formats the url so that client can share the url between different users and retain the same filters/sorts/pagination on table.

Sorting is done programatically with `table.setSort`. Url is formated.
User reloads the page and sorts from url are put in `initialSort`.
Order of rows changes.

OR

User 1 sends a link to User 2 and tells him "Look at the item 1 in the table".
After some back and forth User 2 realises that he's looking at the wrong item, and that in his table item 1 is item 3.

As it is `initialSort` is useless for local sorting.
Workaround for me is to check if table has local or remote data. If local then use `table.setSort` when table has been mounted, if remote then use `initialSort`.

**Comment by olifolkerd** [comment]
Hey @Icebreaker83 

No it is not a bug, looking at your code, you are not telling tabulator the correct sorter to use for that column so it is treating it as text, if you set the soerter on the id column to `number` the sort works just fine.
```js
columns:[
    {title:"Id", field:"id", sorter:"number"},
    {title:"Name", field:"name"},
],

```

Cheers

Oli :)

**Comment by Icebreaker83** [comment]
@olifolkerd 
Thanx m8 :)

Problem with that is when I get my sorters from url there is no info on column sorter type.
So I should either write that info also in url, or loop through column definition to get the sorter for each sort in url so I can pass it to `initialSort`.
My workaround seems better :) Code is clearer and no need to loop through column definition, so more performative (in theory :) ).

Just a food for your thought :)
