### ISSUE TITLE
Destroy fails on table which has groups on 5.3.1 aswell

### ISSUE THREAD

**Issue by AlgirdasR** [olifolkerd/tabulator#3878]
**Describe the bug**
If a table has grouping (groupBy is set), exception is thrown on destroy method call.

**Tabulator Info**
5.3.1

**Working Example**
https://jsfiddle.net/Lasph5tg/1/

**To Reproduce**
Click "Destroy" button

**Expected behavior**
Table is destroyed

**Additional context**
It works on 4.2.9. Destroy also works if 
groupBy: 'type',
is commented out.

This is also a reference to same issue that I reported and it was supposedly fixed, but still persists.
https://github.com/olifolkerd/tabulator/issues/3834

**Comment by olifolkerd** [comment]
Hey @AlgirdasR 

Thanks for the info, the issue was caused because the row manager was attempting to redraw the table contents at the same time as it being destroyed.

I have pushed a fix for this to master and will include it in the next patch release.

Cheers

Oli :)
