### ISSUE TITLE
Moving rows between tables is not working with React.

### ISSUE THREAD

**Issue by krisara4727** [olifolkerd/tabulator#3879]
Hey  *@olifolkerd*

*About the Bug*
I want to move row from one table to another table and vice versa, but when i am trying to move row from one table to another table getting **Cannot read properties of undefined (reading 'delete')**.

*Working Example*
[link to the the issue on codesandbox](https://codesandbox.io/s/movablerowstabulator-forked-c4leql?file=/src/App.js)
[link to issue itself](https://c4leql.csb.app/)

*Tabulator Info*
Tabulator version 5.3.1

*To Reproduce*
A step by step guide to recreate the issue in your JS Fiddle or Codepen:

1. Create 2 tables with tabulator
2. configure the options required for moving rows from one table to another table
3. now drag and drop a row from one table to another table

*Expected behavior*
5. when we drag a row from one table to another table and vice versa , the row should be deleted from the sending table and added to the receiving table.

**Desktop (please complete the following information):**

OS: macOS Big Sur
chrome
Version 102.0.5005.115

image of the issue. This time the error is different. reading a property from undefined.
![screenshot of the issue](https://user-images.githubusercontent.com/56177028/180958078-4d4633a9-c984-41c7-8865-d9c2a5e53ffe.png)
)

It is working fine with javascript and html.
index.html
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://unpkg.com/tabulator-tables@5.3.1/dist/css/tabulator.min.css"
      rel="stylesheet"
    />
    <script
      defer
      type="text/javascript"
      src="https://unpkg.com/tabulator-tables@5.3.1/dist/js/tabulator.min.js"
    ></script>
    <script defer type="text/javascript" src="./script.js"></script>
    <title>Document</title>
  </head>
  <body>
    <p id="para"></p>
    <div id="table"></div>
    <div id="tabulator"></div>
  </body>
</html>
```
script.js
```javascript
var table = document.getElementById("table");
var table2 = document.getElementById("tabulator");
const tableData = [
  {
    id: 1,
    name: "name1",
    age: 32,
    color: "white",
  },
  {
    id: 2,
    name: "name2",
    age: 45,
    color: "green",
  },
  {
    id: 3,
    name: "name3",
    age: 73,
    color: "yellow",
  },
  {
    id: 4,
    name: "name4",
    age: 87,
    color: "red",
  },
];
const tabulator2 = new Tabulator(table2, {
  //table setup options
  layout: "fitColumns",
  movableRows: true,
  movableRowsConnectedTables: table,
  movableRowsReceiver: "add",
  movableRowsSender: "delete",
  data: tableData,
  autoColumns: true,
});

const para = document.getElementById("para");
para.innerHTML = "moving rows";

const tablulator = new Tabulator(table, {
  //table setup options
  layout: "fitColumns",
  movableRows: true,
  movableRowsConnectedTables: table2,
  movableRowsReceiver: "add",
  movableRowsSender: "delete",
  data: tableData,
  autoColumns: true,
});
```
**but when using with a javascript framework like react, facing this issue even in your latest version 5.3.1**

**Comment by olifolkerd** [comment]
Hey @krisara4727 

The issue appears to be that your `componentDidMount` is being called twice, which is therefore initializing Tabulator on a div that already contains a table, this is causing duplicate event listeners which is breaking the table functionality

Stick a console log in your `componentDidMount` function and you will see it is called multiple times.

To prevent this being an issue you can check to see if your table variable have been set before trying to insatiate them, thus preventing a duplocate:

```js
     if (!this.tabulator) {
         this.tabulator = new Tabulator(this.el, {
            ...
        });
    }
`````

Cheers

Oli :)

**Comment by krisara4727** [comment]
Thanks @olifolkerd, that worked!
