### ISSUE TITLE
Row lines disappear on mouseover in MS Edge 

### ISSUE THREAD

**Issue by michaelbushe** [olifolkerd/tabulator#388]
Go to the Tabulator Themeing examples (http://olifolkerd.github.io/tabulator/examples/#theming) using MS Edge, the version used in this test is "Microsoft Edge 25.10586.672.0, Microsoft EdgetHTML 13.110586".  Go to Theming and make the Simple Theme table visible.

Start with your mouse outside the table, say below the bottom, and move the mouse vertically across the rows of the table.  Some lines (the first seen on mouse enter?) have much lighter, nearly invisible row lines.  See the attached screenshot.
![tabulatoredgerowlinesdisappear](https://user-images.githubusercontent.com/168178/27351077-2a7f4b8e-55ca-11e7-83b0-28a4ef80ca4f.PNG)

**Comment by olifolkerd** [comment]
Hey,

This is a known rendering bug in the edge browser [issue #71191570](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7119159/)

So unfortunately it is down to Microsoft to fix that one.

Thanks for letting me know though.

Cheers

Oli
