### ISSUE TITLE
[notreallyabug]: Tabulator.info serves no https connection.

### ISSUE THREAD

**Issue by Emporea** [olifolkerd/tabulator#3880]
This should be fixed. Self Explanatory.

**Comment by reviewher** [comment]
Was this fixed? https://tabulator.info/ chrome reports "NET::ERR_CERT_AUTHORITY_INVALID"

https://downforeveryoneorjustme.com/tabulator.info?proto=https shows a failure while https://downforeveryoneorjustme.com/tabulator.info?proto=http (no HTTPS) succeeds

**Comment by olifolkerd** [comment]
Hey @reviewher 

It hasnt been implemented yet no.

The site isn't broken it just isn't available in HTTPS yet, There is no user based or non public info in to the site, so while i am to do it at some point, it isn't a pressing priority.

There are no public links that point to an https variant so you are only getting those warnings if you are specifically trying to go to the https site for some reason.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @reviewher 

As of this evening tabulator.info is now available with HTTPS

Cheers

Oli :)

**Comment by Emporea** [comment]
Nice. You successfully used Let's Encrypt. Thanks :)
