### ISSUE TITLE
getSubColumns function is missing in Code Base but defined in Interface Tabulator.ColumnComponent

### ISSUE THREAD

**Issue by MickeWest** [olifolkerd/tabulator#3884]
**Describe the bug**
As usual thanks for a great tool. I/We have discussed before about enhancing the Sub-Column (or groups) features of Tabulator and thanks for all the great fixes. One issue that we encountered today was that the getSubColumns function is missing in the Tabulator Code Base but is defined in the Interface Tabulator.ColumnComponent. This causes some issues as we cannot grab the available Sub-Columns of a parent Column.
We can of course use the parentCol.columns property to do the same. However the getSubColumns function is very descriptive in the code. 
This may be something that you have elected to not support any more and want the programmer to use parentCol.columns instead and the @types/tabulator-tables is outdated?

**Tabulator Info**
- 5.3

**Working Example**
I understand this requirement and agree. Usually I add a Fiddle but this issue is not so much that something is not working when using code as it is that the code (function getSubColumns) is actually missing from the Tabulator codebase. Not sure how a fiddle would help in this case. If I need to add a one-liner in the JS Fiddle please let me know and I will add that. I have copied in the steps in here but I would just search the GitHub and see that the function is missing. I apologies before-hand for breaking that requirement as I understand the difficulty without it.
```

// Find/Locate the Parent Column to add the Sub-Column to
const parentColumn: Tabulator.ColumnComponent = this.table.columnManager.columns.find((column: Tabulator.ColumnComponent) => column.getDefinition().field === parentColumnFieldName);

if (parentColumn) {
    const subColumns: Tabulator.ColumnComponent[] = parentColumn.getSubColumns();
}


```

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to 'https://github.com/olifolkerd/tabulator'
2. Search for 'getSubColumns'
3. Scroll down to results of search
4. See error that the function 'getSubColumns' is missing from the code base but defined in @types/tabulator-tables

**Expected behavior**
If the function 'getSubColumns' is still supported by Tabulator we expect it to be defined in the Tabulator Codebase. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version: Version 103.0.5060.134 (Official Build) (64-bit)

**Additional context**
As a suggestion, if I may, when adding Sub-Columns, I would suggest adding the addColumn() function to Tabulator.ColumnComponent so that the code can be made shorter and safer when adding new sub-columns and more error checking can take place in your code as you know what is required to create new columns. This way the addition of a Sub-Column could be performed like below AND you could maintain the functionality of allowing the new Sub-Column to be inserted at a specific location, like addColumn() already does:
```

// Find/Locate the Parent Column to add the Sub-Column to
const parentColumn: Tabulator.ColumnComponent = this.table.columnManager.columns.find((column: Tabulator.ColumnComponent) => column.getDefinition().field === parentColumnFieldName);

if (parentColumn) {
    // Insert Sub-Column
    parentColumn.addColumn(columnAttributes, insertBefore, insertPosition).catch((error: any) => {
    });


```

Versus the user code attempting all the steps needed:
```

// Find/Locate the Parent Column to add the Sub-Column to
const parentColumn: Tabulator.ColumnComponent = this.table.columnManager.columns.find((column: Tabulator.ColumnComponent) => column.getDefinition().field === parentColumnFieldName);

if (parentColumn) {
    // Get Parent Column definitions to get access to the 'columns' property
    const parentDef: Tabulator.ColumnDefinition = parentColumn.getDefinition();

    // If no prior Sub-Columns, create a new Sub-Columns Array
    if (!parentDef.columns) {
        parentDef.columns = new Array<Tabulator.ColumnDefinition>();
    }

    // Finally, insert the new Sub-Column
    // If you wanted it at a specific location, for example left or right of a certain file name the code would be much more involved,
    // something that addColumn() function already handles
    const numSubCols: number | undefined = parentDef.columns?.push(columnAttributes);


```

**Comment by olifolkerd** [comment]
Hey @MickeWest 

I must admin i am very confused by your issue, there is a lot of detail here and it isnt clear exactly what your issue is.

If you are saying that the 'getSubColumns' function is no longer available on the column component, then i think you have made a mistake beccause it is very much still available in the latest release. it is one of the standard functions on the column component and is still 100% included in the code base. If it is not in the typing's then that is an issue to take up with that repo but it is 100% still in Tabulator and having just checked, in all versions of the release code.

It will not be visible directly on the component object since the 5.x release because from that point all components are proxy objects that allow each module to register functions with them, but if you call the function it is very much still there.

If you still belive it is missing in your setup then i will need to see a JS fiddle demonstrating the console error you see when you try to call the function because it is defo in the codebase and works for me.

Cheers

Oli :)
