### ISSUE TITLE
Provide `mouseDown` and `mouseUp` events on cells

### ISSUE THREAD

**Issue by rathboma** [olifolkerd/tabulator#3885]
I'm implementing a bespoke way of row selection and for selecting a range of rows via dragging the mouse these would be very helpful. Right now I'd have to manually bind the events, which I'd rather avoid.

**Comment by olifolkerd** [comment]
I thought I had already added these. But looking at the docks it looks like I might have missed them. Will stick them in the next release.

Cheers

Oli

**Comment by dogadogan** [comment]
Any updates on this? :)

**Comment by olifolkerd** [comment]
As per the previous comment u will see them in on the next feature release.

As per the community guidelines, please don't chase on feature requests, this is a free library built in our free time. Features will be added as and when I have time.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @rathboma 

I have just pushed this functionality onto the 5.4 branch which i hope to release towards the end of Sept.

Cheers

Oli :)

**Comment by Fiercekilla** [comment]
Hey @olifolkerd 

Now it working? I cant use (click) (mouseDown) (mouseUp) with tabulator 5.5.1.
