### ISSUE TITLE
Sorting by clicking the sort button rather than the header column

### ISSUE THREAD

**Issue by azmy60** [olifolkerd/tabulator#3887]
**Is your feature request related to a problem? Please describe.**
As stated in beekeeper-studio/beekeeper-studio#1297, some users accidentally triggered sort operation when resizing the column headers.

**Describe the solution you'd like**
An option to listen to a sort button rather than the header column would be a good idea.

**Comment by edgar-koster** [comment]
I can agree with this. Not only the accidental trigger could be an issue, but when you also have the popup option the hover doesn't tell you what you will click.

**Comment by olifolkerd** [comment]
Hey All,

I think this would be a great feature, but as an option to allow users to choose how this is added to the table.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
This functionality has been merged into the 5.4 branch and will be included in the release in a week or so time.

Cheers

Oli :)
