### ISSUE TITLE
Filtering not working for tree structure

### ISSUE THREAD

**Issue by robertkewei** [olifolkerd/tabulator#3888]
I am using Tabulater 5.3. I have a Tree structure Tabulator table, and I need to filter for parent and child, but looks like the filter function is only work for the parent level. Is this a bug?

**Comment by olifolkerd** [comment]
http://tabulator.info/docs/5.3/tree#manage

**Comment by robertkewei** [comment]
Thanks @olifolkerd, I have try dataTreeSort:true, but it is not working.
Any ideas?

Thanks
