### ISSUE TITLE
setdata with click in cell

### ISSUE THREAD

**Issue by ramonrt** [olifolkerd/tabulator#389]
Hi, i have 2 tables, I want when click in a cell of first table, setdata of second table.

`rowDblClick:function(e,row){var cellValue = row.getCell("id").getValue();
alert(cellValue);
$("#table-2").tabulator("setData","http://www.getmydata.com/now", {key1:cellValue),}, "POST");}`

only work with a button
$("#button").click(function(){
	    $("#table-2").tabulator("setData","http://www.getmydata.com/now", {key1:cellValue),}, "POST");}`
});

Thanks for the support and great work!

**Comment by olifolkerd** [comment]
Hey,

You have to use the ***cellClick*** callback in the column definition array to detect a click on cells. because Tabulator uses a virtual dom you cannot use jQuery to bind to the cells as they are created and destroyed as you scroll:

```js

var cellClickHandler = function(e, cell){
    //e - the click event object
    //cell - cell component

    $("#table-2").tabulator("setData","http://www.getmydata.com/now", {key1:cell.getValue()),}, "POST");}`
}


$("#example-table").tabulator({
    columns:[
        {title:"Name", field:"name", cellClick:cellClickHandler }
    ]
});
```

Let me know if that helps

Cheers

Oli

**Comment by ramonrt** [comment]
thank you for the quick reply, work perfect
