### ISSUE TITLE
HVDom: Frozen Column support

### ISSUE THREAD

**Issue by rathboma** [olifolkerd/tabulator#3890]
Looking to add a frozen column to the left side of my tables for user selecting of rows (which is working great btw, looks awesome).

That requires I add a single frozen column on the left.

I can try to add this myself, but not sure how to go about it.

**Comment by olifolkerd** [comment]
Hey @rathboma 

Ahh yes, i can see why you would want to add that.

That could be a tricky one, because both the frozen column module and the hozVDOM use the same padding/margin attributes to ensure things remain in position. so they would probably fight against eachother.

Hmmmmmm, that may take some thought.

I was looking to possibly rebuild out the frozen column module to work in a completely different way to improve scroll performance but that wouldnt be for another 6 months or so.

I would be happy to arrange a chat and take you through both systems some time if you fancy.

Cheers

Oli :)

**Comment by rathboma** [comment]
@olifolkerd It'd be great to chat about this and do a code walkthrough to understand how these work together.

Something I think it would be good to give some thought to: How easy it would be to hack this a little for a fixed-width single frozen column. I suspect that would solve a common use case (certainly that would be good enough for me) , and I wonder if that's doable quickly.

I'll shoot you an email about a session :-)

**Comment by olifolkerd** [comment]
Hahahaha @rathboma 

You have read my mind there!

I had that exact same thought last week and stuck it on the todo list for the 5.4 (end of sept) release with that exact functionality, Though it would need to be two, one for the left frozen and one for the right.

Yeah i think it will be a really quick win, ive also had some thoughts about how to improve the efficiency of the frozen horizontal scroll which i will be sticking in too if they pan out.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @rathboma 

Progress update for you, i have just rebuilt the frozen columns module to make it ready to integrate with the hoz vdom. (on the 5.4 branch

Ive removed all the padding, margins an everything else and have moved to using sticky positioning, it has resulted in a massive performance improvement when scrolling and some much simpler code.

Now that is out the way i will start integrating with the hoz vdom

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @rathboma 

And now that the changes to the frozen columns module were in, it was super simple to make the hoz vdom work with it.

I have just pushed the functionality to the 5.4 branch  if you want to have a peek, im hoping to get it released in the next week.

Im going to be tinkering around with the hoz renderer a bit more to see if i can improve the performance.

Cheers

Oli :)

**Comment by rathboma** [comment]
Damn, this is amazing :-)

**Comment by rathboma** [comment]
I'm going to poke around with this over the next week and use it for the release after next of Beekeeper Studio. This will enable a HUGE improvement in my table views. :heart:
