### ISSUE TITLE
Multicolumn sort with tristate doesn't clear the sort when toggling column the third time

### ISSUE THREAD

**Issue by edgar-koster** [olifolkerd/tabulator#3892]
If you have mult-column selection enabled, and also tristate, there is an issue with the third click when using 'ctrl+click' on a column. The third click doesn't clear the selection instead it keeps toggling the sort of the column you are clicking. When tristate is enabled, the third click on for sort is to remove the sort of the column

See this fiddle with : https://jsfiddle.net/ekoster/7c0kq2to/9/

**Comment by olifolkerd** [comment]
Hey  @edgar-koster 

Thanks for the headsup, i have pushed a fix for this to the master branch and will include it in the next patch release.

Cheers

Oli :)
