### ISSUE TITLE
When using a function to set the icon for sorting, it doesn't work

### ISSUE THREAD

**Issue by edgar-koster** [olifolkerd/tabulator#3893]
In the documentation there is a section `Different icons depending on Sort Direction` with a function. This function changes the icon based on the sort sequence. The given example doesn't seem to work in jsfiddle, see: https://jsfiddle.net/ekoster/Lzofjr2m/4/

Looking into this, it seems that the switch through the options of `headerSortElement` does detect it as a function, however it is set to do nothing with the function. This means there is no icon in the defined element `arrowEl`. It then goes to the function `setColumnHeaderSortIcon` to set the icon. Passed to the function is an empty `div`. Due to this, the while loop fails, there is no first child.

Possible solution (I haven't jumped to trying it out yet) is to only do the while loop if the passed div is not empty.

**Comment by olifolkerd** [comment]
Hey @edgar-koster 

It works exactly as it should do, in the fiddle you linked to you have not included the font awesome library which is needed for that particluar set of i tags to work, if you include it it all works fine.

Below is a link to a js fiddle with no code changes but has the link to the font awesome icon set in the resources list:
https://jsfiddle.net/w6p1mnhv/1/

as you will see the icons are there as expected

Cheers

Oli :)
