### ISSUE TITLE
Possibility for a user to freeze a column (just like filter, sort)

### ISSUE THREAD

**Issue by edgar-koster** [olifolkerd/tabulator#3894]
*Is your feature request related to a problem? Please describe.**
With a lot of columns, user often want to have columns 'pinned'. This help with understanding the data they are looking at etc when scrolling, or they don't need to scroll to the right.

**Describe the solution you'd like**
It would be nice to have a button in the title, to the right of the sort button. It can be turned on/off like the sorting, and also accept the normal behaviour to change icons. There will be one icon to pin and one to unpin the column. Since it is logical to have these pinned columns at the start of the row, an option of the feature will be to move the pinned column to the front of the row, starting at a specific position. 

Concept of the new options:
enable pinning - yes/no defaults to no
icons - defaults normal pin icons, but you can pass to different ones
move to start pinned column at position n - when this is set (e.g. 0) the first pinned will move to position 0, the next to position 1 etc

Small visualization of the suggested icon location
![image](https://user-images.githubusercontent.com/24190040/182408111-bd9dd0df-cedf-41de-9eb5-ce35928ec2de.png)

**Describe alternatives you've considered**
It is offcourse possible to put a button in a title description formatter which in turn triggers the freeze function of tabulator. I'm not sure have localization of the title will then react, but positioning it nicely will become tricky, especially when the '...' is activated for long titles, and you won't be able to place it at the most right side of the header where it usually will be located

**Comment by olifolkerd** [comment]
Hey @edgar-koster 

Thanks for your suggestion.

While your usage case may mean left, different usage cases would need to work in different ways, left, right, or to closest end.

Im not sure this would make for good UX, if someone clicks the icon and the column is in the middle of the table it would provide an inconsistent result and there is no clear way of the user knowing which way it goes,

In most usage cases I have seen developers add a custom context popup that allows the user to manage which columns are frozen (providing access to toggle all columns frozen state, and i am inclined to agree with them that this is a cleaner solution. The headers don't want to become congested with icons for every function, advanced things should be in a menu.

I think this would bring up more issues that it would solve, so would not be looking to add this as a feature at this point

Cheers

Oli :)
