### ISSUE TITLE
Frozen rows are not displayed when using row.freeze()

### ISSUE THREAD

**Issue by DuredhelFinceleb** [olifolkerd/tabulator#3897]
**Describe the bug**
When using row.freeze() the row is not displayed in the frozen section above the table.
If pagination is used, the row just does not move
If pagination is not used, the row disappears completely and reappears when using row.unfreeze()

**Tabulator Info**
5.3.1

**Working Example**
https://jsfiddle.net/74Luorjw/

**To Reproduce**
1. Run the fiddle & click on the "Freeze" button : nothing happens
2. Disable pagination (ie: comment out line 12) 
3. Run the fiddle again & click on the Freeze button: this time row with ID 1 disappears completely. Click on the Unfreeze button to make it reappear

**Expected behavior**
The expected behavior is to see the frozen row displayed in the frozen section when clicking on 'Freeze'

**Desktop (please complete the following information):**
- OS: Windows 10
- Browsers: FF 103.01, FF developer Edition 104.0b5, Chrome 104.0.5112.81, Edge 103.0.1264.77

**Smartphone (please complete the following information):**
 - Not tested on smartphones

**Comment by DuredhelFinceleb** [comment]
My current solution to this is to patch tabulator.js

      key: "_virtualRenderFill",
      value: function _virtualRenderFill(position, forceMove, offset) {
        var element = this.tableElement,
            holder = this.elementVertical,
            topPad = 0,
            rowsHeight = 0,
            heightOccupied = 0,
            topPadHeight = 0,
            i = 0,
            ------  rows = this.rows(),
            ++++++  rows = this.rows().filter(row => !(row.modules && row.modules.frozen)),
            rowsCount = rows.length,
            containerHeight = this.elementVertical.clientHeight;
        position = position || 0;
        offset = offset || 0;

I do not know enough of Tabulator to send a proper PR. There is more than one renderer in the sources so not sure this patch works everywhere

Moreover I'm not sure it does not have side effects. For example if the contents of the frozen rows change (some event triggered a change in the store), I'm not sure that with this patch the changes will be reflected on screen

**Comment by olifolkerd** [comment]
Hey @DuredhelFinceleb 

Thanks for bringing this up, i will look to get a fix in the next patch release.

What i would say is that this is a very odd combination of features to use, a frozen rows primary usage is to keep a row fixed while scrolling, to do so on a paginated table would be an unusual move.

Thanks for your suggestion for the fix but this functionality is handled in the frozen row module not the renderer, functionality for modules should be kept to the module to keep the code maintainable.

Cheers

Oli :)

**Comment by DuredhelFinceleb** [comment]
Thanks for your answer, we'll wait for the next patch release.

Our use case is that we have big tables with rows we need to compare
Rather than  paginate back and forth between rows, we can pin the relevant ones with freeze/unfreeze

We could have use a other table to do this or some other mechanism but the frozen module fit this purpose well for us

**Comment by olifolkerd** [comment]
Hey @DuredhelFinceleb 

I have pushed a fix for this to the master branch and will include it in the next patch release

Cheers

Oli :)
