### ISSUE TITLE
Can't combine headerSortElement and having columns with headerSort as false

### ISSUE THREAD

**Issue by nquirynen** [olifolkerd/tabulator#3898]
**Describe the bug**
Combining the use of the `headerSortElement` configuration option and having columns with the `headerSort` option set to `false` breaks and throws following error:

```
Uncaught (in promise) TypeError: sortEl is undefined
    setColumnHeaderSortIcon tabulator.js:26779
    clearColumnHeaders tabulator.js:26760
    clearColumnHeaders tabulator.js:26755
    sort tabulator.js:26707
    refreshPipelines tabulator.js:5786
    refreshActiveData tabulator.js:5752
    _setDataActual tabulator.js:5308
    setData tabulator.js:5282
    setData tabulator.js:5266
    load tabulator.js:6748
    ...
```

It seems that the code is trying to set the sorting icon on a column that was configured to not be sortable.

**Tabulator Info**
v5.3.1

**Working Example**
Combination that breaks the code:
https://jsfiddle.net/djuofev1/

**To Reproduce**
Either disable the `headerSortElement` configuration on the table or remove the use of `headerSort: false` in the column configuration and both will work separately.

**Desktop:**
 - OS: OSX
 - Browser: Firefox
 - Version: 103.0.1

**Comment by olifolkerd** [comment]
Thanks for the info

I will look into what I'd going on with the error as that shouldn't happen. But it is not a valid configuration in the first place to have a sort element on a non sortable column, so I would be interested to know what you were trying to achieve?

**Comment by nquirynen** [comment]
Thanks for the fast reply!
I want to override the sorting UI with fontawesome icons (in the jsfiddle example I just used some text instead). Setting this is a setting on the table configuration.
But I also want to have some columns set as not sortable (setting on the column configuration).
It's the combination of these two that seems to break the code (as seen in the jsfiddle example).
When debugging it seems that it tries to apply this sorting UI override on the not sortable column resulting in an error.

Or maybe there is another way I have to implement this?
I use server side data (and column configuration setup) by the way, not sure if this makes a difference though).

**Comment by olifolkerd** [comment]
Hey @nquirynen 

I have pushed a fix for this to master and will include it in the next patch release.

Cheers

Oli :)
