### ISSUE TITLE
moveColumn function does not work correctly with resisable columns on

### ISSUE THREAD

**Issue by AlgirdasR** [olifolkerd/tabulator#3899]
**Describe the bug**
If a table has resizable columns option on and moveColumn function is called
tabulator-col-resize-handle
is left behind (DOM position of the item is not updated)

**Tabulator Info**
5.3.1

**Working Example**
On tableBuilt event name column is moved after surname column by calling moveColumn
The resize handle is left behind and resizing no longer works properly.
https://jsfiddle.net/hdza82kv/

**Comment by olifolkerd** [comment]
Hey @AlgirdasR 

Thanks for the info,

I have pushed a fix for this to the master branch and will include it in the next patch release.

Cheers

Oli :)
