### ISSUE TITLE
enhance custom filter

### ISSUE THREAD

**Issue by bilbot75** [olifolkerd/tabulator#39]
Hi, first, thank you for tabulator, it's very useful for me.
I would like to know if it's possible to add the filter type and the filter values to the custom function ?

`if(typeof(self.filterField) == "function"){`
`	return self.filterField(row, self.filterType, self.filterValue); <-- here `
`}else{`

sorry i'm not native english

Thanks in advance

**Comment by olifolkerd** [comment]
Hi Bilbot, 

Thanks, its always great to hear people are enjoying using Tabulator.

Im not sure i get what you are after. In which custom function do you want to check the current filter type/values?

If you are asking if you can check the current filter values in a custom filter function then the answer is no. in this instance the custom filter function **is** the current filter type/values, so there is nothing to check for.

If you just want to get the current filter then you certainly can using the ***getFilter*** function.

```js
$("#example-table").tabulator("getFilter");
```

This will return an object with the details of the current filter information, if no filter is set it will return ***false***.

```js
{
    "field":"age",
    "type":">",
    "value":10,
}
```

for full information on filtering checkout the [Filtering Data](http://olifolkerd.github.io/tabulator/docs/#filtering) section of the documentation

**Comment by bilbot75** [comment]
ok thanks olifolkerd, i will try to adapt my code with 'getFilter'

Regards
