### ISSUE TITLE
Formatter doesn't seem work on 3.1.0

### ISSUE THREAD

**Issue by ryc16** [olifolkerd/tabulator#390]
Hi, downloaded tabulator and its dependency and I got below version on my package.json
    "jquery": "^3.1.1",
    "jquery.tabulator": "^3.1.0",
    "jqueryui": "^1.11.1",

I am not sure what is missing but rownum doesn't show row index, formatter with below editIcon or deleteIcon doesn't work (same html on title property works). Also buttonCross doesn't show the "cross" sign too.

```
        var editIcon = function (cell, formatterParams) { //plain text value
            return "<span class='glyphicon glyphicon-pencil'></span>";
        };
        var deleteIcon = function (cell, formatterParams) { //plain text value
            return "<span class='glyphicon glyphicon-trash'></span>";
        };

 columns: [ //Define Table Columns
  { title: "#", formatter: "rownum", align: "center", width: 40, headerSort: false },
  { title: "<span class='glyphicon glyphicon-pencil'></span>", formatter: editIcon, width: 40, headerSort: false, align: "center", cellClick: function (e, cell) { alert("Edit") } },
  { title: "<span class='glyphicon glyphicon-trash'></span>", formatter: deleteIcon, width: 40, headerSort:false, align: "center", cellClick: function (e, cell) { alert("Delete") } },
:
:
  { formatter: "buttonCross", width: 40, align: "center", headerSort: false },
  ],
```

By looking at the browser DOM, I don't see there is associated html tag inserted. 

`<div class="tabulator-cell" role="gridcell" style="width: 40px; text-align: center; height: 28px;"></div>`

Below is on your sample from your site.

`<div class="tabulator-cell" role="gridcell" title="" style="width: 40px; text-align: center; height: 32px;"><i class="fa fa-print"></i> <div class="tabulator-col-resize-handle"></div><div class="tabulator-col-resize-handle prev"></div></div>`

Thanks

**Comment by olifolkerd** [comment]
I cant seem to replicate your issue im afraid,

Could you post a copy of your full tabulator constructor.

Which browser are you using?

**Comment by ryc16** [comment]
I also feel straight too.  I tried IE, Firefox and Chrome, results are the same. I guess probably not because of the browser because your sample from http://olifolkerd.github.io/tabulator/examples/3.1/ works on Chrome. By the way, I am using it with angular.io. Not sure if this will cause any conflict.

```
        var editIcon = function (cell, formatterParams) { //plain text value
            return "<span class='glyphicon glyphicon-pencil'></span>";
        };
        var deleteIcon = function (cell, formatterParams) { //plain text value
            return "<span class='glyphicon glyphicon-trash'></span>";
        };
        $(this.table.nativeElement).tabulator(
            {
                height: "400px", // set height of table (optional)
                headerFilterPlaceholder: "...", //set column header placeholder text
                pagination: "local", //enable local pagination.
                placeholder: "No Data Set", // show on the center of table when there is no data
                addRowPos: "top",
                columns: [ //Define Table Columns
                   { title: "#", formatter: "rownum", align: "center", width: 40, headerSort: false },
  { title: "<span class='glyphicon glyphicon-pencil'></span>", formatter: editIcon, width: 40, headerSort: false, align: "center", cellClick: function (e, cell) { alert("Edit") } },
  { title: "<span class='glyphicon glyphicon-trash'></span>", formatter: deleteIcon, width: 40, headerSort:false, align: "center", cellClick: function (e, cell) { alert("Delete") } },
:
:
  { formatter: "buttonCross", width: 40, align: "center", headerSort: false },
  ],
}
```

**Comment by olifolkerd** [comment]
Hey,

The row number formatter works correctly with your code, with the other two formatters  are inserting the correct span tags into the cells, i can see it on the inspector.

are you missing the glyphicon CSS from your project?

**Comment by ryc16** [comment]
Hey,

From your sample on the website, it looks great but once I use on my angular project, it doesn't seem to work well. It shouldn't be missing glyphicon CSS because title takes it and show correctly 
` title: "<span class='glyphicon glyphicon-pencil'></span>"` (see attached screenshot). Also if it is just missing glyphicon CSS, the html should have the div but it is not.

`<div class="tabulator-cell" role="gridcell" style="width: 40px; text-align: center; height: 28px;"></div>`

Not sure if it conflicts with angular.io. Any idea?
![image](https://user-images.githubusercontent.com/5568006/27469839-e95efbfc-5823-11e7-88b8-8e05f17142bc.png)

**Comment by olifolkerd** [comment]
Hey,

i know people have used it with angular before without issue.

how did you pull the source code into your project? bower, npm?

**Comment by ryc16** [comment]
Hey,

People are using angular v1 or angular v2+? I am using angular 4.0.3. I used npm to install, and I did the following. 

angular>npm install jqueryui --save
angular>npm install jquery.tabulator --save

Thanks

**Comment by olifolkerd** [comment]
i will have a test this evening.

a couple of people are having issues with the npm release, i may rerelease it under 3.0.1 this eve incase anything went wrong with the publish

**Comment by ryc16** [comment]
Cool. Thanks

**Comment by olifolkerd** [comment]
3.1.1 released,

there was an issue in the package.json that was causing problems
