### ISSUE TITLE
footerElement  removes pagination when passing a DOM element

### ISSUE THREAD

**Issue by nquirynen** [olifolkerd/tabulator#3900]
**Describe the bug**
Passing a html string to `footerElement` appends the html in front of the pagination element as expected (?).
But passing a DOM element to `footerElement` removes (replaces?) the pagination element.

I need to be able to add DOM elements to the footer while also using the built in pagination. Is this a bug or do I need to use another way to implement this?I guess I can rebuild the pagination myself in the DOM element I pass to the `footerElement`.

**Tabulator Info**
v5.3.1

**Working Example**
https://jsfiddle.net/L501ot7n/1/

**To Reproduce**
The jsfiddle shows both cases having different behaviour.

**Comment by olifolkerd** [comment]
Hey @nquirynen 

When you pass an element or a selector for an element into the `footerElement` prop you are telling Tabulator that you want to move the footer element outside of the table into the element you have provided. Tabulator will then put the contents of the footer, including things like the pagination element inside that element.

If you for example append your element beneath the table you will see the footer controls appear inside it.

Cheers

Oli :)
