### ISSUE TITLE
Add composer installation method

### ISSUE THREAD

**Issue by ChrisKar96** [olifolkerd/tabulator#3902]
Hi and thanks for this amazing project!

I would like to suggest adding an installation method using php composer.

Thanks in advance for considering it and keep up the excellent work.

**Comment by olifolkerd** [comment]
This is a JavaScript front end package. It is not written in PHP not intended for backend use which is what composer is for

This sounds like a misunderstanding as to how this library should be used. Please ask for clarification on the discord channel if you need help getting started

**Comment by ChrisKar96** [comment]
Thanks for the quick response.

Although composer is not typically used for front-end packages, many front-end libraries get published in https://packagist.org/.
Take for example https://packagist.org/packages/twbs/bootstrap, https://packagist.org/packages/fortawesome/font-awesome, and even the similar project https://packagist.org/packages/datatables.net/datatables.net.

My use-case (although arguably not best-practice) is avoiding to install/use a second package manager for front-end packages for small projects, utilizing composer scripts (https://getcomposer.org/doc/articles/scripts.md) to copy the front-end packages to the right location after they get installed.

That said, I understand if it's in your opinion out of the scope of the project.
