### ISSUE TITLE
Titiles are dupicated after column group

### ISSUE THREAD

**Issue by Kelvinyhl** [olifolkerd/tabulator#3903]
I used column group function in my project follow this demo:
http://tabulator.info/docs/5.3/columns#definition

After i group those columns, it was sucessed but **Original Titiles** are still there dose not
meet my expectations.(please see the pic)maybe it was because my language is Chinese so i report it.

Here is my code.
https://codepen.io/kelvinyhl/pen/Barqoge

**Expected behavior**
I expected that the titiles are individually in the table.  

**Desktop (please complete the following information):**
<img width="663" alt="99" src="https://user-images.githubusercontent.com/111147802/184495181-a5b902c8-44f3-44ff-82fa-c43617dda2ca.png">

**Comment by olifolkerd** [comment]
Hey @Kelvinyhl 

I am unable to replicate your issue, grouped columns are working as expected.

You will need to create a JS Fiddle that demonstrates the issue you are having. the JS Fiddle that you linked to only included the javascript part of the code without actually showing a functional table, and when i cpied that code it worked correctly.

If you can post a link to a demonstration of the issue then i will happily look into it further, but at this stage i would say it is likely an issue with the structure of your column definition object or row data

Cheers

Oli :)
