### ISSUE TITLE
Error with cellMouseEnter event on nested tables

### ISSUE THREAD

**Issue by atebeta** [olifolkerd/tabulator#3904]
**Describe the bug**
the cellMouseEnter event will give an error if you subscribe to the event on a table and have a nested subtable using the row formatter that also subscribes to the cellMouseEnter event.

**Tabulator Info**
- 5.3

**Working Example**
https://jsfiddle.net/atebeta/4mohedfb/3/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. move the mouse over any of the cells in the main table and/or sub table
2. see error in console log

**Expected behavior**
No error. Expect the cellMouseEnter event for the main table to fire when moving the mouse over main table cells and the cellMouseEnter vent for the sub table to fire when moving the mouse over the sub table.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari / Chrome

**Additional context**

**Comment by atebeta** [comment]
I managed to work around this error by unsubscribing to the cellMouseEnter event on the main table when the cellMouseEnter event on the sub table fires. Then I resubscribed to the cellMouseEnter event on the main table on the cellMouseLeave event on the sub table.

**Comment by olifolkerd** [comment]
Hey @atebeta 

Thanks for the info,

I have pushed a fix for this to master and will include it in the next patch release.

Cheers

Oli :)
