### ISSUE TITLE
No caso de carregar dados no modo Ajax, quando eu rolar horizontalmente até o final da coluna, a barra de rolagem re request retornará automaticamente ao cabeçalho da coluna

### ISSUE THREAD

**Issue by Teadeno** [olifolkerd/tabulator#3905]
*Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by olifolkerd** [comment]
Hey @Teadeno 

Thanks for getting in touch,

Tabulator can only accept feature requests in english, please fill the details of the request in the body of the issue, the title should only be  a brief summary.

Having used a quick google translate on the title, i can see you are looking for ajax loading of column headers,  which would make little sense im afraid. Tabulator loads data into the table by row, not by column, and already has the option to progressively load data in this way.

Columns in Tabulator are simple definitions of how to display the data contained in table rows.

As this would not be compatible with the underlying mechanic of how Tabulator works i would not be looking to take this further

Cheers

Oli :)
