### ISSUE TITLE
Tooltip function is down at 5.2.3 version

### ISSUE THREAD

**Issue by Kelvinyhl** [olifolkerd/tabulator#3906]
**Describe the bug**

**Tabulator Info**
- Which version of Tabulator are you using?

**Working Example**
YOU MUST include a link to a JS Fiddle or Codepen that demonstrates the problem, it is very hard to diagnose an issue from a simple description.

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by olifolkerd** [comment]
Hey @Kelvinyhl 

You appear to have only added a title to this bug report, Please read through the contents of the issue and provide the required info.

Telling us something is "down" does not help if you dont include a description of what you are attempting and a link to a JS Fiddle that demonstrates your configuration as it is likely related to your specific setup.

If you can provide the needed information i would be happy to reopen this issue

Cheers

Oli :)
