### ISSUE TITLE
Builtin editor "list" 'clearable: true' option is not showing the clear button 

### ISSUE THREAD

**Issue by OgarOgarovic** [olifolkerd/tabulator#3907]
**Describe the bug**
Builtin editor "list" used as a cell editor or as a headerFilter with option `clearable: true` in both cases no clear button is shown and there is no way to clear the cell/filter

**Tabulator Info**
- 5.3.1

**Working Example**
Tabulators own documentation example:
http://tabulator.info/examples/5.3#filter-header

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Setting a column with cell editor of type "list" or a headerFilter on that column of type "list"
2. Setting the option `clearable: true`
3. No clear button shown in cell/headerFilter input

**Expected behavior**
Some clear button should be shown for user to have the option to clear the input. There is no way to clear the input now.

**Screenshots**
![image](https://user-images.githubusercontent.com/8025689/185093867-3b3f36a7-cf9f-43de-ad39-6172989e4571.png)

**Desktop (please complete the following information):**
 - OS: Linux, Windows
 - Browser: Chrome, Chromium, Firefox
 - Version: newest

**Comment by maximlt** [comment]
I also observe this issue.

**Comment by OgarOgarovic** [comment]
Ok, so it's not a bug in tabulator. The `clearable` property is just setting the input element to type search, which browsers standardly equip with a clear button pseudoelement, visible if some characters are present in the input. Some CSS frameworks use to hide this button as a default with CSS rules, I was using one of them, and so is the documentation page.
 Also the `clearable` property is just clearing the input of characters for search (autocomplete), what I needed from the `list` editor is a possibility to "choose an empty value", which seems to be a different problem.

**Comment by davidkurutz** [comment]
@OgarOgarovic @maximlt I am also seeing this issue in multiple browsers, and different Tabular versions -- even the "working example" provided above by @OgarOgarovic doesn't actually work -- Tabular's own examples aren't working.
Did anyone find a fix for this?

**Comment by olifolkerd** [comment]
@davidkurutz This is due to firefox not correctly implementing the search type input element

**Comment by davidkurutz** [comment]
@olifolkerd thanks so much for your reply, however the problem is not limited to Firefox. 
If you check https://tabulator.info/examples/5.4#filter-header in Firefox, Chrome, or Safari (mac) --- the problem exists clearly in Tabular's own examples

For future readers of this post: here is how i fixed it for my own use case:
`input[type=search]::-webkit-search-cancel-button {
      -webkit-appearance: searchfield-cancel-button;
    }`

Given that Tabular's own examples have this problem in multiple browsers, and the above code fixed it for me, i'd suspect a default browser CSS rule is the cause, or some other CSS framework (which tabular is using on their own site).  

I'd think that Tabular would also be able to mention this in their docs as a fix, or provide the proper CSS rules such that the search input 'X' is always displayed.

**Comment by davidkurutz** [comment]
for what its worth:  i see the problem on Tabulator's own examples in the following browsers:

all on Mac OS 12.1
Chrome Version 107.0.5304.110 (Official Build) (x86_64)
Firefox 107.0
Safari Version 15.2 (17612.3.6.1.6)

**Comment by ilmari-lauhakangas** [comment]
In Firefox, [this is currently behind a config flag](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#layout_for_input_typesearch).

1. Go to about:config
2. Enter this option name and double-click to set to true: `layout.forms.input-type-search.enabled`

I confirm it works with Tabulator. There are still [some issues to be solved](https://bugzilla.mozilla.org/show_bug.cgi?id=1654288) before it can be enabled by default.

**Comment by IncidGeo** [comment]
Instead of clearing the field with "x" button, filtering with "all" or "-----" could be possible ?
