### ISSUE TITLE
Scrolling performance degraded in 5.3 versus 4.x

### ISSUE THREAD

**Issue by blankbadge** [olifolkerd/tabulator#3908]
**Describe the bug**
Hi Oli, I've been working through issues migrating my project from 4.6.1 to 5.3.1, and I have everything working, but there is one performance issue that is holding me back from completing the migration.  In my project I have some tables that can be around 80 columns and several thousand rows.  I use vertical vDom but not horizontal vDom yet because I'm still on 4.6.1, and I'm relying on the frozen columns module which isn't yet supported with the horizontal vDom in 5.x (I've asked you about this one before and you said it was on the roadmap).

What I find with such tables is that the scrolling performance is noticably worse in 5.3.1 compared to 4.6.1.  I was able to reproduce with a simple setup:

v4.6.1
https://jsfiddle.net/blankbadge/v3gjnfd7/

v5.3.1
https://jsfiddle.net/blankbadge/u2098qwt/

Both are identical with a table of 80 columns and 1000 rows shown in a 700x1200px div.

If you scroll through the table vertically, you can probably see the difference quite noticably.  I have tried mouse wheel scrolling as well as keyboard scrolling holding the down arrow.  With 4.6.1 there is a good sense of scrolling with the table updating frequently.  in 5.3.1, it tends to start off quick, but then you'll notice it only rerenders the display every 10 rows, then 20, then 30, etc.  It seems to get more sluggish the longer the scrolling is happening.  It doesn't feel as responsive.  This is true for both the row display refreshing as it scrolls, as well as with the row formatting that happens to show the dark grey bar over the currently hovered row.  Both seem to update more frequently in 4.6.1 vs 5.3.1.

I do have an option in that v5.3.1 testcase to set the renderHorizontal variable from 'basic' to 'virtual' to enable horizontal vDom.  When I enable it, I see significant performance improvement -- the vDom is definitely helping address the challenges of displaying many columns.  And I do plan to move to using the horizontal vDom once it supports all of the features I'm using in my project (frozen columns being the one missing feature that I am aware of).

But the reason I file this issue is because in this equivalent comparison of 4.6.1 vs 5.3.1 with the same exact setup, there is a clearly observable performance difference, and I thought you might be interested to see this.  I don't know if you are expecting this behavior or not with the many changes you made to the library in 5.x.

So, I understand if you close the issue with the suggestion to wait for updated horizontal vDom support and use that once available.  It will solve the problem.  But I thought there may also be room for improvement in the general v5.3.1 performance.

Thanks as always for your support and development of Tabulator!

**Tabulator Info**
v4.6.1 and v5.3.1

**Working Example**
v4.6.1
https://jsfiddle.net/blankbadge/v3gjnfd7/

v5.3.1
https://jsfiddle.net/blankbadge/u2098qwt/

**To Reproduce**
Look at each version and scroll vertically with mouse wheel or keyboard.  Scrolling should be noticably more sluggish in 5.3.1 vs 4.6.1

**Expected behavior**
Expectation is comparable scrolling performance when moving to 5.3.1.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome v104

**Comment by olifolkerd** [comment]
Hey @blankbadge 

When using that number of columns you should 100% be using the horizontal virtual renderer, Tabulator has never performed well with a large number of columns without that.

Tabulators performance has generally increased significantly against 4.9 and has been externally benchmarked to confirm that, but the performance for large numbers of columns requires the use of the horizontal virtual renderer.

Apologies that it does not currently support the frozen column functionality that you need but at the moment that module uses the same margins on the same element as the hoz renderer so they are not compatible, i hope to get the changes in to resolve this at some point in the next year but cant say when as it will be a large amount of work and require a complete rebuild of the frozen columns module.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @blankbadge 

It turns out that the bable transpilation for the UMD package was radically reducing the performance of the code in the UMD package, the version u are using in your demo `(i test on the ESM version so hadn't noticed)`

I have removed the transpilation in the 5.4 release last weekend and it is about 8 times faster at loading data.

Hope that helps,

Cheers

Oli :)
