### ISSUE TITLE
Is it possible to set the field to data child member?

### ISSUE THREAD

**Issue by ryc16** [olifolkerd/tabulator#391]
I have data like 
[{
        "product": {
          "num": "123456",
        },
        "productId": 1,
        "id": 1
      },
]

How can I set the field to "product.num"? 

I try { field: "product.num" ....} but it doesn't work.

Thanks

**Comment by olifolkerd** [comment]
Hey,

At the moment Tabulator cannot handle nested objects in data, although this feature is in the road map for release in a few months,

For the time being i would suggest you use a function to flatten your data before putting it into tabulator, The function below will flatten it into a single object with underscore separated names:
```js
function flattenData(data){
	var output = [];
	function flatternRow(row){
		var outputRow = {};
		for(var prop in row){
			if(typeof row[prop] !== "object"){
				outputRow[prop] = row[prop];
			}else{
				var flat = flattenRow(row[prop]);
				for(var flatProp in flat){
					outputRow[prop + "_" + flatProp] = flat[flatProp];
				}
			}
		}
		return outputRow;
	}
	data.forEach(function(row){
		output.push(flatternRow(row));
	});
	return output;
}
```

if your data is pulled in by ajax you could call this function in the ***ajaxResponse*** callback to format the returned data before it is parsed into the table.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey,

You will be happy to hear that Tabulator 3.2 has just been released, and with it the the ability to bind columns to nested data, simply use dot notation in the field name:
```js
{title:"age", field:"user.age"), //link column to age property inside user object
```

Full information can be found in the [Column Definition Documentation](http://olifolkerd.github.io/tabulator/docs/3.2/#field-nesting)

Cheers

Oli
