### ISSUE TITLE
Problem with Frozen Columns in RTL mode

### ISSUE THREAD

**Issue by SMNRST** [olifolkerd/tabulator#3910]
**Describe the bug**
I have a problem with Frozen Columns in RTL mode.
As you can see in Screenshot the frozen column moved to the left (instead of right) and the data of this column not showing up. 

**Tabulator Info**
   5.3

**Working Example**
https://jsfiddle.net/s9caqw3p/1/

**To Reproduce**
Just scrolling the tabulator

**Screenshots**

![Screenshot (60)](https://user-images.githubusercontent.com/59201091/185789054-0941dea7-91a7-4600-99b1-85e9a52b96c4.jpg)

**Desktop :**
 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome

**Comment by olifolkerd** [comment]
Hey @SMNRST 

As per the documentation, frozen columns are not supported in RTL mode:
