### ISSUE TITLE
Bootstrap Stripes displaying on all rows

### ISSUE THREAD

**Issue by JacobGralinski** [olifolkerd/tabulator#3911]
Hi Oli,

**Describe the bug**
Every now and then when scrolling on a table with table-striped, all the rows will suddenly have the darker highlight. Continuing to scroll will cause a flicker effect.

**Tabulator Info**
v5.3.0

**Working Example**
https://jsfiddle.net/jacobgralinski/f374xj5L/12/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to the JSFiddle
2. Scroll just over halfway down the table and the rows should all be striped with the darker highlight.

**Expected behavior**
The striping on the table should be uniform and remain that way while scrolling

**Screenshots**

Good Styling:
![image](https://user-images.githubusercontent.com/32072855/186051371-36500304-38e6-4ae5-ab03-6576ef08de73.png)

Bad Styling:
![image](https://user-images.githubusercontent.com/32072855/186050378-c5329e4e-f193-4e1b-ae20-32abc13559f1.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, Edge
 - Version: Chrome: 104.0.5112.101, Edge: 104.0.1293.63

**Additional context**
From my testing, the issue seems to be competing CSS styling. I commented out/removed the below on line 1296 and that seems to resolve it

Line 1296
.tabulator.table-striped:not(.table) .tabulator-row:nth-child(even) {
  background-color: #e9ecef;
}

I believe it is competing with this styling.

Line 473
.tabulator-row.tabulator-row-even {
  background-color: #e9ecef;
}

Thanks!
Jacob

**Comment by olifolkerd** [comment]
Hey @JacobGralinski 

Thanks for the headsup, I have pushed a fix for this to the master branch and will include it in todays patch update.

Cheers

Oli :)
