### ISSUE TITLE
initialSort - can't sort by rightmost column then left

### ISSUE THREAD

**Issue by okohll** [olifolkerd/tabulator#3913]
**Describe the bug**
The sort docs http://tabulator.info/docs/5.3/sort say

'When using multiple sorters, the order in the array is the order in which the sort functions will be applied to the data'.

However that only works if the columns are defined in the same order as they appear in the table, left to right. You can't sort first on say the second column, then on the first.

That has repurcussions on other things. For example, if I want to group by the second column, have the groups alphabetically sorted, then sort within the group by the first column, that can't be accomplished. Of course you could swap the columns, but if I also want to freeze the first column and hide the grouping column there are side-effects. It would be a lot simpler if the order defined in initialSort were honoured, however the columns are laid out.

**Tabulator Info**
- Which version of Tabulator are you using?
5.3

**Working Example**
https://jsfiddle.net/qymf52a3/

**To Reproduce**
See fiddle

**Expected behavior**
The example should be sorted first by colour alphabetically, then by height. Instead it's sorted by height then colour.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS:OSX
 - Browser: Chrome
 - Version: 104.0.5112.101

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by olifolkerd** [comment]
Hey @okohll 

Thanks for getting in touch,

I think there is a missunderstanding here of how the sort affect the table.

The order of the columns in the table has no affect on the sort at all, the sort system itself isn't even aware of column order.

The sort system, simply works through an array of sorters in the order they are defined, the data is then accessed by row as a prop of an object, there is no concept of column order at any point in the entire sort process.

Sorting on a hidden column will still affect the data in just the same way as it would if it was visible, the data is still inside the table, so the act of toggling columns will have no affect on sort at all. 

There is also common misunderstanding at time, the order of sort is the order in which the sort functions are applied to the data not the precedence of the sort, to resolve this there is a ` sortOrderReverse` option that reverse the order and may give you the sort you are looking for.

Cheers

Oli :)
