### ISSUE TITLE
Calling selectRow() when using a string based row index incorrectly selects all rows.

### ISSUE THREAD

**Issue by omfgicbf** [olifolkerd/tabulator#3914]
**Describe the bug**
When using paged AJAX based data, calling `selectRow()` with an id that does not exist on the current page results in all rows on that page being selected.

This only occurs when using a string based id. Using a numeric id works as expected.

**Tabulator Info**
5.2.3

**Working Example**
https://codepen.io/omfgicbf/pen/MWVdaep?editors=1011

**To Reproduce**
1. Navigate to https://codepen.io/omfgicbf/pen/MWVdaep?editors=1011
2. Note that a single row is selected on the first page as expected.
3. Click page 2 on the pager.
4. Note that all rows are now selected and no warning is displayed in the console.

**Expected behavior**
On a page that does not contain a row with the id passed to `selectRow()`, no rows are selected and the `Selection Error - No such row found, ignoring selection:x` warning is shown in the console.

**Screenshots**
![tabulator](https://user-images.githubusercontent.com/39300379/186629681-b96a1356-f7e5-4513-b52c-0c86fa7ddc63.gif)

**Desktop (please complete the following information):**
- Windows 10 Version 21H1 (Build 19043.1889)
- Chrome 104.0.5112.102 (Official Build) (64-bit) (cohort: Stable)

**Comment by olifolkerd** [comment]
Hey @omfgicbf 

Thanks for the headsup, i will have a look into that for the next patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @omfgicbf 

I have pushed an update for this to the master branch and will include it in todays patch release.

Cheers

Oli :)
