### ISSUE TITLE
The display becomes strange when the cell width is changed

### ISSUE THREAD

**Issue by regppe** [olifolkerd/tabulator#3915]
**Describe the bug**
When there is no data in the initial state, after adding a record, if you reduce the cell width with the mouse, an unnecessary display is displayed on the right end.

**Tabulator version**
Tabulator : 5.3.2

**Working example.**
https://jsfiddle.net/regppe/xv15u8gc/15/

**To Reproduce.**
1.Open to jsfiddle.
2.Click to 'clickme'.  -> line is added.
3.Decrease cell width.  -> Unnecessary drawing remains on the right side.

![image](https://user-images.githubusercontent.com/40412730/186701931-c42ea2b0-f1ae-4edf-9d6f-504f5d9cf3ad.png)

However, if I do 'this.tabulator.redraw(true);' it will redraw successfully.

 - OS: Windows11
 - Browser chrome
 - Version 104.0.5112.102

Not tested on smartphone.

Thanks!!

**Comment by olifolkerd** [comment]
Hey @regppe 

Thanks for the headsup, that does look strange,

I will have a look into that on the next patch release,

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @regppe 

I have pushed a fix for this to master and will include it in todays patch release.

Cheers

Oli :)

**Comment by regppe** [comment]
Thanks! Oli!

But, looks like it hasn't been fixed.

See -> https://jsfiddle.net/regppe/md9ern5c/2/
This sample is uses 5.3.3.

**Comment by olifolkerd** [comment]
Hey @regppe 

Interesting, i will have a check and see what went on there

Oli :)-

**Comment by olifolkerd** [comment]
Hey @regppe 

i have just published release 5..3.4 that fixes this, the 5.3.3 release did fix the situation, but only when a placeholder was set.

Cheers

Oli :)

**Comment by regppe** [comment]
I made sure it was fixed!

Thank you for your quick response!
