### ISSUE TITLE
Can't do columnTitleChanged in constructor

### ISSUE THREAD

**Issue by mikeymckay** [olifolkerd/tabulator#3916]
**Website Page**
(http://tabulator.info/docs/5.3/columns#edit-titles)

**Describe the issue**
Page says you can hook up the listener like this:

```
var table = new Tabulator("#example-table", {
    columnTitleChanged:function(column){
        //column - the column component for the changed column
    },
});
```

But this results in:

tabulator.js:2176 Invalid table constructor option: columnTitleChanged

I got it to work by setting up the event listener after initializing:
```
tabulator.on "columnTitleChanged", (column) =>
      console.log column

```

**Comment by olifolkerd** [comment]
Hey @mikeymckay 

Thanks for the headsup,

looks like this got missed in the documentation update in 5.0

i will get that fixed in the next site update.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
This will be included in todays site update.

Cheers

Oli :)

**Comment by Ariharan2002** [comment]
Hi @mikeymckay, i need some clarification regarding **columnTitleChanged**, after this event fires the title actually changes but i cannot able to make sorting on that edited column as the title name and field name is not same but after refresh i can able to follow the flow. Have you experienced any issue like this?
