### ISSUE TITLE
deleteColumn() should delete corresponding data found by getData()

### ISSUE THREAD

**Issue by mikeymckay** [olifolkerd/tabulator#3917]
If I delete a column using tabulator.deleteColumn(nameOfColumn), then the column disappears in the table, but calling getData() shows that the data is still there.

If I delete a row, then the row disappears in both the table and the underlying data.

These should be consistent and there should be an easy way to delete the columnar data.

**Describe alternatives you've considered**
Write code that loops through the data and removes the data corresponding with the deleted column.

**Comment by olifolkerd** [comment]
Hey,

Thanks for the suggestion

The columns are just a visualization of the underlying row data. Columns have no direct effect on the table data that is always handled by the row component

To add this in would break backwards compatibility and break the existing paradigm of the rows controlling the data.

Given this would be easy enough to do yourself with a simple for loop iterating over each of the rows and deleting the value (you could use blockRedraw and restoreRedraw around the loop to increase efficiency).

I would therefore not be looking to implement this, but thanks for the suggestion.

Cheers

Oli :)
