### ISSUE TITLE
Uncaught errors with custom placeholder only with fitDataStretch or fitColumns layout options

### ISSUE THREAD

**Issue by yogiderek** [olifolkerd/tabulator#3918]
I recently upgraded to v5.3.2 from 4.8 and noticed I was getting the uncaught javascript errors shown below when using a custom placeholder with either fitDataStretch or fitColumns for the layout and the table contains no data. The other 3 layout options were okay. My placeholder was     placeholder: "No cases have been deleted yet"

If I delete my custom placeholder, no errors are thrown. Note, It is not always consistent which of the 3 errors I get

![image](https://user-images.githubusercontent.com/2614368/186856990-0a1cfcad-2609-41df-966b-9b5e16971f9c.png)

![image](https://user-images.githubusercontent.com/2614368/186857055-c5720788-0de0-46ed-bac1-a95846feaf93.png)

![image](https://user-images.githubusercontent.com/2614368/186857114-5d8914af-157b-4bef-a392-7c09243f8692.png)

**Comment by olifolkerd** [comment]
Can you provide a link to a jsfiddle that demonstrates your issue.

Without seeing the table in operation and the full table configuration it will be hard to get to the bottom of what is going on there.

I am actively using a custom placeholder on several configurations of table without issue so there must be a combination of factors at play here and a demo will help get to the bottom of it.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @yogiderek 

I have been unable to replicate your issue, and as i have yet to hear back from you i will assume you have fixed the exception your end and will close this issue.

If you still believe there to be a problem please post a link to a JS Fiddle that demonstrates the issue, without that it will not be possible o ascertain what is going wrong for you.

Cheers

Oli :)
