### ISSUE TITLE
Remote pagination configuration

### ISSUE THREAD

**Issue by omfgicbf** [olifolkerd/tabulator#3919]
**Website Page**
[Remote Pagination](http://tabulator.info/docs/5.3/page#remote)

**Describe the issue**
The description says:

    To enable remote pagination, set the `pagination` option to `remote`

However, the code example shows setting the `pagination` parameter to `true` and the `paginationMode` parameter to `"remote"`.

Setting `pagination` to `"remote"` does not seem to work.

**Comment by olifolkerd** [comment]
Thanks for the headsup, looks like that bit of the docs is out of date, that functionality changed in 5.0

I will get that changed in the next update

Cheers

Oli :)

**Comment by olifolkerd** [comment]
A fix for this will be going in todays website update

Cheers

Oli :)
