### ISSUE TITLE
First frozen column makes the header disappear

### ISSUE THREAD

**Issue by nghuuphuoc** [olifolkerd/tabulator#3920]
**Describe the bug**
If the table has only one column which is also frozen, then the header will be disappeared.

**Tabulator Info**
v5.3.2

**Working Example**
https://jsfiddle.net/o8fx9m73/11/

The header is displayed as usual

![Screen Shot 2022-08-30 at 15 14 19](https://user-images.githubusercontent.com/4226036/187385878-62cc522f-2b5c-4523-b0a0-289960d03ea1.png)

**To Reproduce**
Go to this fiddle https://jsfiddle.net/o8fx9m73/12/

Set the first column frozen:

```js
var table = new Tabulator("#example-table", {
    data: tableData,
    columns:[
      {title:"Name", field:"name", frozen: true }, // <--- This causes the issue
    ],
});
```

The header is disappeared

![Screen Shot 2022-08-30 at 15 14 56](https://user-images.githubusercontent.com/4226036/187386140-4a4c33fd-3af0-45ef-a672-45210cc1500d.png)

**Browser**
- Chrome Version 104.0.5112.101 (Official Build) (x86_64)
- macOS 12.5

**Comment by olifolkerd** [comment]
Hey @nghuuphuoc 

I would agree this is a bug, but i would also argue there is never actually a scenario in which this functionality should be used.

Using frozen columns when there are no other columns to move would be an invalid configuration from a user experience perspective.

Could you provide an example of why you would want a single frozen column on your table?

Cheers

Oli

**Comment by nghuuphuoc** [comment]
We have been using Tabulator in our production application and it allows our users to manage the columns dynamically.
They can add/remove columns from the table.

There is a case where the default set of columns contains only one single column which leads to the issue.

**Comment by olifolkerd** [comment]
Hey @nghuuphuoc 

Thanks for explaining your usage case, that was very helpful. 

I have pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)

**Comment by nghuuphuoc** [comment]
Thanks a lot ❤️ . I can confirm that the issue is fixed.
