### ISSUE TITLE
"Setup Options" button links to the quick start guide

### ISSUE THREAD

**Issue by MichaelRHaddad** [olifolkerd/tabulator#3921]
**Website Page**
http://tabulator.info/docs/5.3

**Describe the issue**
This button is linked to the quick start guide instead of the setup options.
![image](https://user-images.githubusercontent.com/41021500/187422960-a3c6b9fb-e0d9-4ba1-ab6c-cc132f6c6e7e.png)

**Comment by olifolkerd** [comment]
Hey @MichaelRHaddad 

Thanks for the headsup, i will get that fix in the website update with todays patch release.

Cheers

Oli :)
