### ISSUE TITLE
Cannot refresh data after removing groupBy

### ISSUE THREAD

**Issue by yevhensayenko** [olifolkerd/tabulator#3922]
**Describe the bug**
I would like to make dynamic grouping / ungrouping by click on button. To ungroup I use setGroupBy method by passing either false or undefined. It works OK but when I remove grouping and try reload data in ungrouped view it fails. Based on stacktrace it still calls `updateGroupRows` to update groups.

**Tabulator Info**
- Tabulator 5.3.2

**Working Example**
I have just copied example from documentation and changed a bit - https://jsfiddle.net/xpenuo0z/

**To Reproduce**
1. Go to https://jsfiddle.net/xpenuo0z/ The table is grouped by default.
2. Click on 'remove grouping' button - groups are removed successfully.
3. Click on 'reload' button
5. See error in browser console

**Expected behavior**
I would expect it to just load data without grouping. Maybe I am doing it incorrectly.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: latest Chrome, Firefox

**Comment by olifolkerd** [comment]
Hey @yevhensayenko 

Thanks for the info. I have pushed a fix for this to master and will include it in todays patch release.

Cheers

Oli :)
