### ISSUE TITLE
Persistence.initializeColumn() wrong this

### ISSUE THREAD

**Issue by juchunwei** [olifolkerd/tabulator#3923]
this.save("columns") not working.

`keys.forEach((key)=>{
				var props = Object.getOwnPropertyDescriptor(def, key);
				var value = def[key];
				if(props){
					Object.defineProperty(def, key, {
						set: function(newValue){
							value = newValue;
							if(!this.defWatcherBlock){
								this.save("columns");
							}

							if(props.set){
								props.set(newValue);
							}
						},
						get:function(){
							if(props.get){
								props.get();
							}
							return value;
						}
					});
				}
			});`

**Comment by olifolkerd** [comment]
@juchunwei  Tabulator has no external save functio .

To what are you referring?

If you want to report a bug, please include a link to a JS fiddle that demonstrates your issue. Without seeing how your table is configured it is hard to offer advice or replicate the issue

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @juchunwei 

I think i get your jist,

I will push a fix for this in todays patch release.

Cheers

Oli :)
