### ISSUE TITLE
row update json nested data error

### ISSUE THREAD

**Issue by juchunwei** [olifolkerd/tabulator#3924]
for example the data: 
`
{
  name: '123',
  line:{
      qty: 1,
      price: 1, 
     amount: 1
}
}
`
If I use this code `row.update({line:{qty:2}})`, the data above will change to 
`
{
  name: '123',
  line:{
      qty: 2
}
}
`, the price and amount field are disapeared.

**Comment by olifolkerd** [comment]
@juchunwei  yes that is the correct behaviour, you have  replaced the line object with a new object with only the one property.

Tabulator has no way of knowing weather you mean to update the nested property or replace it, the action is ambiguous.

The update function simply replaces the top level property with the value specified

**Comment by juchunwei** [comment]
@olifolkerd, is it okay if change the code for row.updateData() like this?
```for (let attrname in newRowData) {
            if (typeof newRowData[attrname] == 'object') {
			for (var attr in newRowData[attrname]) {
			    this.data[attrname][attr] = newRowData[attrname][attr];
			}
	  }
        else
	        this.data[attrname] = newRowData[attrname];
        } 
}`

**Comment by olifolkerd** [comment]
You can do anything you like to your own copy of the code.
