### ISSUE TITLE
"dataFiltered" event occurs before table data has been updated.

### ISSUE THREAD

**Issue by welford** [olifolkerd/tabulator#3925]
**Describe the bug**
"dataFiltered" event occurs before table data has been updated.

http://tabulator.info/docs/5.3/events#filter
states: `The dataFiltered event is triggered after the table dataset is filtered.`

http://tabulator.info/docs/5.3/update#retrieve-data
states: `var data = table.getData("active"); //return currently filtered data`

Calling table.getData("active") within "dataFiltered" event returns the previous state of the data. 

**Tabulator Info**
5.3.0

**Working Example**

https://jsfiddle.net/52hLn8dw/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://jsfiddle.net/52hLn8dw/
2. filter phone column by 99
3. Filtered total should be 57, which is correct for the rows data sent to the event, but not when you query the table directly (it's 3001 it's previous value).
4. Clear the filter
5. Filtered total should be 3001, which is correct for the rows data sent to the event, but not when you query the table directly (it's now 57 the previous value).

**Expected behavior**
If the docs are correct then table.getData("active"); should return the current filtered data when called within the dataFiltered event.

**Screenshots**
![image](https://user-images.githubusercontent.com/4590399/188305744-9746fdcc-7cc9-47d7-8429-0c7bb23e5f6b.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version 105.0.1343.27 (Official build) (64-bit)
 
Also reproduced on chrome mobile / safari iOS

**Additional context**

If this is an  error in the documentation, then what is the correct event in which we can get the filtered data directly from the table?

**Comment by welford** [comment]
> If this is an error in the documentation, then what is the correct event in which we can get the filtered data directly from the table?

To answer my own question here: in the renderComplete event table.getData("active") seems to return the actual filtered data.

**Comment by olifolkerd** [comment]
Hey @welford 

This is a misunderstanding as to how this event works,

It is called the moment the data has been filtered by the filter module, but before it has been passed back into the table to be rendered. The filtered rows are passed directly into the callback to allow you to process them there without needing to query the rest of the table.

As you have pointed out in your second post, the `renderComplete` is the event called when the render has been updated.

Cheers

Oli :)

**Comment by welford** [comment]
Perhaps the documentation should be made clearer? i feel like what i expected is covered by 

"The dataFiltered event is triggered after the table dataset is filtered."

I queried the table data during that event is some callbacks from higher level code which is updating graphs.

**Comment by welford** [comment]
Either way - thank you for the answer @olifolkerd 
.

**Comment by olifolkerd** [comment]
@welford this isnt a special case, this is literally how all the events work, the only event that signifies that everything has been updated is render complete. But thanks for the feedback

**Comment by welford** [comment]
@olifolkerd no problem. I feel like this is maybe a disconnect between you being very familiar with the internals of this code and me as a (very grateful :) ) user who is only familiar with the api.

I don't see anything in the render complete event that suggests that the table data is ready by this point either. 

http://tabulator.info/docs/5.3/events#layout : The renderComplete event is triggered after the table has been rendered

Me finding it was pretty much through experimentation (also tried tablebuilt, but that is only hit on construction which in retrospect makes sense)

Thanks again,
James
