### ISSUE TITLE
Cell List editor not working when using a function to retrieve the list items

### ISSUE THREAD

**Issue by peyrona** [olifolkerd/tabulator#3926]
**Describe the bug**
Cell List editor not working (exception is thrown) when using a function to retrieve the list items: even using Tabulator provided example.
(I checked all previous steps as you requested in: http://tabulator.info/community/bug)

**Tabulator Info**
Version 5.2.3

**Working Example**
https://jsfiddle.net/m3hnykL1/

Everything works fine with 1st (input) column and 2nd (list with fixed values) column.
But 3rd column (obtains its values by invoking a function) always reports an error.
The error in Chromium is:
Uncaught ReferenceError: cell is not defined
    at i.value (List.js:478:51)
    at i.value (List.js:450:14)
    at i.value (List.js:241:14)
    at i.value (List.js:86:20)
    at r.value (Edit.js:640:7)
    at HTMLDivElement.<anonymous> (Edit.js:463:11)

**To Reproduce**
1. Run it
2. Click on cell in 3rd column (title is 'Name')
3. Check console: there is an error

**Expected behavior**
It should show a ListBox with the options returned by the function; but nothing happens due to the error thrown.

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**
 - OS: Debian 11.
 - Browser chromium (104.0.5112.101 (Official Build)) 
 -               firefox (ver. 104.0.1 (64-bit))
 - Version 104 (for both Chromium and Firefox)

**Smartphone (please complete the following information):**
Not tested in smart phones

**Additional context**
None.

Thanks a million for your help, your time and the excellent work done with Tabulator.

**Comment by olifolkerd** [comment]
Hey @peyrona 

This issue was resolved in the 5.3 release, please make sure you are running on the latest version of the code,

Cheers

Oli :)

**Comment by peyrona** [comment]
Hi Oli,

I'm terribly sorry for this stupid mistake.

Thanks a million and sorry for bothering you...
====================
Frasquito Morero Peyrona
