### ISSUE TITLE
topCalc Removed when setGroupBy Called

### ISSUE THREAD

**Issue by welford** [olifolkerd/tabulator#3927]
**Describe the bug**
Calling setGroupBy removes topcalc values on columns

**Tabulator Info**
- 5.3

**Working Example**
https://jsfiddle.net/sjxnavg2/ 5.3  Top calc disappears
https://jsfiddle.net/tLyfv1hk/     4.9 Does not have the same behaviour

**To Reproduce**
1. Go to https://jsfiddle.net/sjxnavg2/
2. Once table has loaded Click on "CLICK ME AFTER THE TABLE HAS LOADED"
3. notice that the topCalc does not show for path column
4. this is not the case in 4.9 https://jsfiddle.net/tLyfv1hk/ 

**Expected behavior**
table column top calcs should remain.

**Desktop (please complete the following information):**
 - OS: Win11
 - Edge
 - Version 105.0.1343.27 (Official build) (64-bit)

**Additional context**
Tried "table" and "both" which work, but columnCalcs:true does not revert to having the totals at the top
http://tabulator.info/docs/5.3/column-calcs#layout

"true - show calcs at top and bottom of the table, unless grouped, then show in groups (boolean, default)"

**Comment by olifolkerd** [comment]
Hey @welford 

Thanks for the info, I have pushed a fix for this to the master branch and will include it later in todays patch release.

Cheers

Oli :)

**Comment by welford** [comment]
great, thanks Oli!
