### ISSUE TITLE
& is rendered as &amp;

### ISSUE THREAD

**Issue by stambetto** [olifolkerd/tabulator#393]
The original table contains string like "C&S" and it's displayed as "C&amp;amp;S"

**Comment by olifolkerd** [comment]
Could you post an example of your table constructor and the data you are passing in.

Cheers

Oli

**Comment by stambetto** [comment]
Hi Oli :)

The table HTML is as simple as

```
<table class="table table-hover job-report" border="2" id="jobs_day_report">
        <thead>
          <tr>
            <th style="width:80px;">Date</th>
            <th>CAD Ref</th>
            <th>Location of vehicle</th>
            <th>Vehicle Category</th>
            <th>Recovery Agent</th>
            <th>Time Received</th>
            <th>EID</th>
            <th>Arrived on scene</th>
            <th>Arrived at pound</th>
            <th>Time exceeds 30 mins</th>
            <th>Time exceeds 45 mins</th>
            <th>Time exceeds 60 mins</th>
            <th>Time exceeds 90 mins</th>
            <th>Operator Name</th>
            <th>Sub Contractor</th>
          </tr>
        </thead>
        
        <tbody>
           <tr>
               <td></td>
               ........
               <td>C&S</td>
               .......
           </tr>
        </tbody>
</table>
```

Please see also the attached screenshots
![original](https://user-images.githubusercontent.com/7084916/27432961-2b840d70-575b-11e7-889a-0334ccc8c8b9.png)
![tabulator](https://user-images.githubusercontent.com/7084916/27432962-2b859a78-575b-11e7-9919-8870f5657021.png)

**Comment by olifolkerd** [comment]
That is because tabulator pulls the data out of cells as HTML rather than as a text string, in case users want to pull the HTML content from their tables, with ```&``` being encoded to ```&amp;``` as is required in the HTML spec.

A way round this would be to extend tabulator with a custom mutator to force the incoming HTML to plain text. include this in your code before you instantiate any Tabulator instances:
```js
Tabulator.extendExtension("mutator", "mutators", {
    plaintext:function(value, type, data){
        var deHTML = $("<div></div>");
        return deHTML.html(value).text() //return the plaintext value for the cell data.
    },
});
```

Then all you need to do is add an additional attribute to any of the affected column headers to trigger the mutator when they are read into the table:
```html
<th tabulator-mutator="plaintext">Recovery Agent</th>
```

Let me know if that helps.

Cheers

Oli

**Comment by stambetto** [comment]
Thanks Oli - works perfectly! :) 👍

**Comment by cswroe** [comment]
Curious if this is still working?  I have been struggling with the same issue and it is still showing &amp;  in the tabulator result.

**Comment by olifolkerd** [comment]
@cswroe try using the ***html*** formatter on the column.

Checkout the [Formatter Documentation](http://localhost:8080/docs/4.1/format#format-builtin) for more information.

Cheers

Oli :)

**Comment by cswroe** [comment]
Amazing. Thank you!

**Comment by cswroe** [comment]
Is there a way to carry this into the downloads?  When I set up the download feature, csv, json, xml, or pdf, the &amp; is used. For the time being, I am just referencing the original CSV file used to make the table and have a link to that but would love to expand what is available. If you need, I can make a separate issue.

**Comment by olifolkerd** [comment]
Hey @cswroe 

Look at using a [Download Accessor](http://tabulator.info/docs/4.1/mutators#accessors) to change the data as it is loaded into the download.

I hope that helps,

Cheers

Oli :)

**Comment by cswroe** [comment]
Thank you.  It is pretty powerful but it must be over my head, I can't get it to work. No worries, I can do without getting it to work, but will continue to mess with it. I appreciate your assistance.
