### ISSUE TITLE
Frozen row disappear when use row.freeze() - follow up of #3897

### ISSUE THREAD

**Issue by DuredhelFinceleb** [olifolkerd/tabulator#3931]
Describe the bug
Situation is better than #3897 with 5.31 but now when using row.freeze() the row is not displayed in the frozen section above the table. This happens regardless of pagination usage.

Tabulator Info
5.3.3

Working Example
https://jsfiddle.net/b54cLrkn/1/

To Reproduce

Run the fiddle & click on the "Freeze" button : row with ID 1 disappears completely.
Click on the Unfreeze button to make it reappear

Expected behavior
The expected behavior is to see the frozen row displayed in the frozen section when clicking on 'Freeze'

Desktop (please complete the following information):
OS: Windows 10
Browsers: FF 103.01, FF developer Edition 104.0b5, Chrome 104.0.5112.81, Edge 103.0.1264.77

Smartphone (please complete the following information):
Not tested on smartphones

**Comment by olifolkerd** [comment]
Hey @DuredhelFinceleb 

Thanks for the info,

There was a regression in that release that hid any elements in the header that were not part of the column headers.  I have just published release 5.3.4 that fixes that and ensures frozen rows work with paginated tables with no height set.

Cheers

Oli :)
