### ISSUE TITLE
Remove old documentation from the internet?

### ISSUE THREAD

**Issue by HenrikDK** [olifolkerd/tabulator#3933]
Hi, 

Thanks for an amazing js grid component, I have only one "issue" with it :D, and that's when im looking up how to do something 9 times out of 10 google will serve me up some old version of the documentation.

Would it be possible to remove old documentation from indexing for all but the last 2 major releases? (ie the 5.x and 4.x series?)

**Website Page**
A link to the page with the issue

http://tabulator.info/docs/4.2/options

**Describe the issue**
Too much old documentation makes it hard to find accurate information on the components capabilities..

**Comment by olifolkerd** [comment]
Nope, because people using older versions may still want to find it, There are still a large number of users on 4.9 because they dont have the time to upgrade

There is a wacking great header at the top of each page that wans that you are on an old release.

Cheers

Oli :)

**Comment by HenrikDK** [comment]
Hi I think you misunderstood my question. 

I am well aware that alot of users are on the 4.9 branch. But is it really necessary to keep 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8 docs around? At some point the out date documentation accumulates in search indexes and starts working against you.

This is why I suggested to only keep docs for the last 2 major relases around (currently 5.1.3 and 4.9.3) you could call them "Tabulator 5" and "Tabulator 4" (similar to how projects like Vue.js only keeps their v2 and v3 docs around and not one for every point release)

Anyway I understand the considerations of trying to support as many users as possible. But still think this might be worth considering.

**Comment by olifolkerd** [comment]
Hey @HenrikDK 

It is completely necessary to keep them about, people are using every version of Tabulator all the way back to 3.x, each minor has a whole set of new features and their own sets of upgrade criteria and deprecations. I often get people getting in contact asking for information about a specific version, where as you are the only person to ever ask to have less.

Merging them would make it impossible for people to use their specific version and judge how to use it.

Keeping the extra versions around has no effect on hosting, the usability of the site isn't hurt as there is a simple drop down to pick your version.

Thankyou for your feedback, but in this case things will be staying as they are

Cheers

Oli
