### ISSUE TITLE
Warning: cannot remove event, no matching event found: cell-editing f hide(silent =false) {...}

### ISSUE THREAD

**Issue by tadmi** [olifolkerd/tabulator#3934]
Warnings appear in the console when the options `tooltip: true or headerTooltip: true` are active and when moving the mouse cursor over the rows of the table:

![image](https://user-images.githubusercontent.com/63556979/189126056-5b78520b-0475-4d2e-b4f1-ac9e1ad3913e.png)

**Comment by olifolkerd** [comment]
Hey @tadmi 

if you wish to report an issue please submit it with the issue template, providing the info required and including a JS Fiddle so we can see your setup.

So many issues are heavily dependant on the tables full configuration, without that we are working in the dark.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @tadmi 

I have pushed a fix for this to the 5.4 branch and will include it in todays release.

Cheers

Oli :)
