### ISSUE TITLE
Context menu is not shown in tabulator wrapped with dialog opened using showModal()

### ISSUE THREAD

**Issue by yevhensayenko** [olifolkerd/tabulator#3936]
**Describe the bug**
I would like to show tabulator with context menu in html dialog tag. To open it I use dialog.showModal() function so elements under the dialog are not clickable. But when I open a context menu - it seems to be shown under the dialog too because it is added as the last element of body so is not in the top stacking layer - https://fullscreen.spec.whatwg.org/#new-stacking-layer . Currently I have managed to create a workaround that listens to `rowContext` event and moves `.tabulator-menu` element to the dialog element using setTimeout, but hopefully it can be changed so it would not require a workaround.

**Tabulator Info**
Tabulator 5.3.3

**Working Example**
https://jsfiddle.net/0nv6r13t/1/ - Example from documentation for context menus but wrapped in a dialog.

**To Reproduce**
1. Go to https://jsfiddle.net/0nv6r13t/1/
2. Right-click on any row
4. No context menu is shown while it is present in DOM when opening browser console.

**Expected behavior**
I would expect `.tabulator-menu` element to be added inside a tabulator's element or after it.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version 105.0.5195.102

**Comment by olifolkerd** [comment]
Hey @yevhensayenko 

You can set where the popup element appears, it is on the body by default as this is the most flexible option and prevents overflow issues.

If you change the `popupContainer` element to something the modal then this should't be a problem. Checkout the [Menus and Popups Docs for more details](http://tabulator.info/docs/5.3/menu#overview-container)

Cheers

Oli :)
