### ISSUE TITLE
If I make the cell a zero string and then try to set it to 0 in update, nothing is displayed.

### ISSUE THREAD

**Issue by regppe** [olifolkerd/tabulator#3938]
Describe the bug

If I make the cell a zero string and then try to set it to 0 in update, nothing is displayed.

Tabulator version
Tabulator : 5.3.4

Working example.
https://jsfiddle.net/regppe/t4qa502p/54/

To Reproduce.
1.Open to jsfiddle.
2.Remove "1.00" from "Progress" to make it a zero-length string.
3.Confirm with Enter key.  -> Nothing is displayed in the cell.

However, it appears that the parameter in the 'update' statement uses the letter '0' instead of the number 0.

OS: Windows11
Browser chrome
Version 104.0.5112.102
Not tested on smartphone.

Thanks!!

**Comment by olifolkerd** [comment]
Hey @regppe 

Thanks for the info, looks like the `update` function was not using a strict comparison to check for value changes.

I have pushed a fix for this to the 5.4 branch that i should be releasing in a week or so.

Cheers

Oli :)
