### ISSUE TITLE
Missing example in the documentation

### ISSUE THREAD

**Issue by JustinBertrams** [olifolkerd/tabulator#3939]
Hello, I'm currently trying to import a JSON into my tabulator. As the documentation says in the chapter "Load Data From Array/JSON" (http://tabulator.info/docs/4.4/data), it should be possible to do that but I'm getting a bit confused because it's just showing how to import an array. For me it's not possible to import a JSON that way.

**Comment by olifolkerd** [comment]
Hey @JustinBertrams 

That depends on what you are meaning by JSON, if you are talking about a JSON string then you can pass it into Tabulator in the same way as the array, If you are talking about loading it from a file then you need to use an importer.

If you have a specific question, please ask it on the discord channel.

Cheers

Oli :)

**Comment by JustinBertrams** [comment]
I'm trying to import a JSON string which is coming by a database. But I'm always facing the error: "Uncaught (in promise) TypeError: Cannot read properties of null (reading 'verticalFillMode')"
![image](https://user-images.githubusercontent.com/75430669/189897932-a9f5a0b6-71f4-4207-ba9e-4684e14c30f6.png)
