### ISSUE TITLE
3.1 did not work in latest joomla

### ISSUE THREAD

**Issue by vasiliyaltunin** [olifolkerd/tabulator#394]
I have error:

`TypeError: $ is not a function   tabulator.js:5580:26`

**Comment by olifolkerd** [comment]
That message suggest that your jQuery library is missing...

are you just upgrading an existing project to 3.1 or is this a new one?

**Comment by olifolkerd** [comment]
Try updating now, i have just released 3.1.1 with some patches

**Comment by vasiliyaltunin** [comment]
I manage work latest version:

on line 17 i change 

`(function () {`
to 
`(function ($) {`

on line 11533 i change
`})();`
to
`})(jQuery);`

and all seems works.

**Comment by olifolkerd** [comment]
Hey,

Thanks for that, it pointed me to exactly where the fault lie, i have tweaked the way the core.js file is included  in the wrapper to fix this and pushed the update to the master branch.

It will be officially released in next months 3.2 release

Cheers

Oli
