### ISSUE TITLE
wrong placement of closing parenthesis on example code

### ISSUE THREAD

**Issue by hairullana** [olifolkerd/tabulator#3940]
**Website Page**
[A link to the page with the issue](http://tabulator.info/examples/4.0?#filter)

**Describe the issue**
there is a code error in the documentation on the filter documentation page, that should not exist closing bracket ")" after "table.clearFilter()"
![image](https://user-images.githubusercontent.com/56705867/190065529-ce89deaf-9eff-40c0-a2c0-22078614861c.png)

**Comment by olifolkerd** [comment]
Hey @hairullana 

Thanks for the headsup, i have committed a fix for this and will publish it in a weeks time with the site update docs.

Cheers

Oli :)
