### ISSUE TITLE
Automatic Content Wrapping Feature Triggered by a Column Property

### ISSUE THREAD

**Issue by wollo** [olifolkerd/tabulator#3941]
In this[ issue](https://github.com/olifolkerd/tabulator/issues/2558#issuecomment-1246662082l) it is described how you can achive a field to wrap its content within the column.
Currently this can only be achieved, as described in the issue by adding the required css to the field within a custom formatter code.
It would be nice, if we could have column property like e.g. wordWrap:true. 
If this is set, then the column receive automatically the required  style.whiteSpace = "pre-wrap"; To make the content wrapped within the field.

**Comment by olifolkerd** [comment]
Hey @wollo 

Thanks for raising that as a feature, i will look at sticking that on the roadmap.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @wollo 

I have just pushed an update to the 5.4 branch to add the new `headerWordWrap` column definition option to manage this.

It should be released in the next week or so.

Cheers

Oli :)

**Comment by wollo** [comment]
Wow, that was blazing fast!
Many thanks for your great tool!

Gesendet von Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Oli Folkerd ***@***.***>
Gesendet: Sunday, September 25, 2022 5:29:06 PM
An: olifolkerd/tabulator ***@***.***>
Cc: wollo ***@***.***>; Mention ***@***.***>
Betreff: Re: [olifolkerd/tabulator] Automatic Content Wrapping Feature Triggered by a Column Property (Issue #3941)


Closed #3941<https://github.com/olifolkerd/tabulator/issues/3941> as completed.

**Comment by kczx3** [comment]
Oddly, the actual request didn't seem to specify the wrapping of header cells specifically.  To me, it sounds as though the OP wanted a column definition property that would apply to all cells of that column.
