### ISSUE TITLE
placeholder stilll rendering if you use replaceData

### ISSUE THREAD

**Issue by vrecan** [olifolkerd/tabulator#3942]
Whenever tabulator has an empty table and we call replace data the placeholder is not removed.

**Tabulator Info**
5.3.4

**Working Example**
https://jsfiddle.net/0dzga1up/5/

**Expected behavior**
The placeholder showing only when there is no data.

**Screenshots**

**Desktop (please complete the following information):**
OS: Linux 
Firefox, Chrome, Edge

**Comment by olifolkerd** [comment]
Hey @vrecan 

I have pushed a fix for this to the 5.4 branch that should be released in the next week or so.

Cheers

Oli :)
