### ISSUE TITLE
ajaxRequestFunc never gets called as per docs unless we pass data as blank string

### ISSUE THREAD

**Issue by jaydeep987** [olifolkerd/tabulator#3943]
https://github.com/olifolkerd/tabulator/blob/master/src/js/modules/Ajax/Ajax.js#L67

Above line should check if `ajaxRequestFunc` exist in options, then return true. Or some other better way idk, but current way is definitely hacky if I want to use `ajaxRequestFunc`.

**Tabulator Info**
- Which version of Tabulator are you using?
5.3.4

**Working Example**
https://codesandbox.io/s/stoic-worker-k5zobb?file=/App.svelte

**Expected behavior**
Should not need to have `data` option as `ajaxRequestFunc` is already provided

**Comment by olifolkerd** [comment]
Hey @jaydeep987 

Yes that is correct, without a URL being set it wouldnt work.

The problem you are having here is you are using an old approach to resolving your issue.

As of 5.x you should be using a custom module to handle async no ajax based data retreiveal.

There is a full example here: http://tabulator.info/docs/5.3/module-examples#db

Cheers

Oli :)
