### ISSUE TITLE
placeholder issue in column filter

### ISSUE THREAD

**Issue by anishjana** [olifolkerd/tabulator#3945]
**Describe the bug**
When the column filter is cleared, the placeholder is still visible in table

**Tabulator Info**
- 5.3.4

**Working Example**
[jsfiddle demo](https://jsfiddle.net/anish_jana/ah817n43/10/)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Search/filter non existing data in any column.
2. remove the filter text
3. "No Data available" placeholder still exists

**Expected behavior**
Should not show placeholder when filter
 is removed

**Screenshots**
<img width="673" alt="Screenshot 2022-09-19 at 1 42 52 PM" src="https://user-images.githubusercontent.com/52600343/190975742-53047ce5-3204-4481-819e-ccb36b30c2fa.png">

**Desktop (please complete the following information):**
 - OS: Mac Monteray
 - Browser chrome
 - Version 105.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aStarlikeMine** [comment]
I can concur - I have the same problem when upgrading from 5.2.3 -> 5.3.4

**Comment by olifolkerd** [comment]
Hey @anishjana 

I have pushed a fix for this to the 5.4 branch that should be released in the next week or so.

Cheers

Oli :)
