### ISSUE TITLE
Column header height for text wrapping

### ISSUE THREAD

**Issue by Coding-1001** [olifolkerd/tabulator#3946]
**Describe the bug**
Column header height not being adjusted accordingly for header text wrapping; but it works only on resize.

**Tabulator Info**
5.3.0

**Working Example**
https://jsfiddle.net/yo03dk6m/

**To Reproduce**
1. Click on Run
2. Resize second column (Name-Name-Name) to wrap text onto next line
3. See error (header height not adjusting accordingly)

**Expected behavior**
Column header height should be immediately updated to correctly/fully display the newly-wrapped text.

 - OS: Windows 10
 - Browser: Chrome
 - Version: 105.0.5195.125

**Additional context**
Already discussed on community questions' page (3rd of August 2022):
https://discord.com/channels/954040083613376572/955128115783421972/1004404369673957436

**Comment by olifolkerd** [comment]
Hey @Coding-1001 

Thanks for the info,

I have pushed a fix to the 5.4 branch that i am hoping to release in a week or so.

Cheers

Oli :)

**Comment by Coding-1001** [comment]
Hi Oli,

Thank you for the prompt reply.
Looking forward to the next release! 😊

As always, appreciate all your hard work.

All the best!

**Comment by olifolkerd** [comment]
@Coding-1001 

It is already out! checkout the release notes for full details.

Cheers

Oli :)
