### ISSUE TITLE
Add getTable function to the mock cell component passed into the titleFormatter

### ISSUE THREAD

**Issue by aStarlikeMine** [olifolkerd/tabulator#3947]
**Describe the bug**
When using a custom function in the titleFormatter for a column, the cell parameter has just the `cell.getElement` and `cell.getValue` methods. `cell.getTable()` is undefined. 

When I look at the methods available on [cell component](http://tabulator.info/docs/5.3/components#component-cell) (and indeed in other functions we use in Tabulator, as well as the typescript Tabulator.CellComponent definition) it seems that much more should be available. 

The reason this is a problem is that our client is needing (aka _would_really_like_ ) a custom checkbox. Using `cell.getTable()` would allow us to set the way the select all box displays by seeing what rows have been selected. 

I thought I may be missing something so I [asked on Stackoverflow](https://stackoverflow.com/questions/73746405/why-is-the-function-cell-gettable-undefined-in-tabulator-s-titleformatter-functi) but no luck so far.

It does seem to me that this is missing functionality (unless I'm really misunderstanding). 

**Tabulator Info**
- 5.3.4

**Working Example**
[JS Fiddle example](https://jsfiddle.net/wj6pc0ot/2/)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to [JS Fiddle example](https://jsfiddle.net/wj6pc0ot/2/)
2. Run the example
4. See error in console: `cell.getTable is not a function`

**Expected behavior**
I was expecting the `cell.getTable` to return the table thereby making it possible to gain access to info about how many rows are selected. 

**Desktop (please complete the following information):**
 - OS: windows Version 10.0.19042 Build 19042
 - Browser: Chrome 
 - Version 105.0.5195.127

**Smartphone (please complete the following information):**
Not tested on on a smartphone

**Additional context**
The JSFiddle renders the grid incorrectly (even with the example from the Tabulator website). 

I tried to do a workaround by getting the table via Tabulator.findTable however the way we've set this up with a svelte component means we're passing in the component to the Tabulator constructor rather than a selector string so this option doesn't seem viable (I have tried with an id set on the div as well).

**Comment by aStarlikeMine** [comment]
Thanks @olifolkerd, much appreciated.

**Comment by olifolkerd** [comment]
Hey  @aStarlikeMine 

I have just pushed a commit for this feature to the 5.4 branch, which i am hoping to release in the next week or so.

Cheers

Oli :)

**Comment by aStarlikeMine** [comment]
Amazing @olifolkerd !

I checked out the branch to confirm that the changes would work however I am getting build errors on 5.4 (but not on master).

`C:\Repositories\tabulator>npm run build

> tabulator-tables@5.3.4 prebuild
> eslint src


C:\Repositories\tabulator\src\js\core\rendering\renderers\VirtualDomHorizontal.js
  36:7  warning  'columns' is assigned a value but never used  no-unused-vars
  37:3  warning  'frozen' is assigned a value but never used   no-unused-vars

C:\Repositories\tabulator\src\js\modules\ColumnCalcs\ColumnCalcs.js
  178:1  error  Expected indentation of 5 tabs but found 4  indent
  179:1  error  Expected indentation of 6 tabs but found 5  indent
  180:1  error  Expected indentation of 5 tabs but found 4  indent
  181:1  error  Expected indentation of 6 tabs but found 5  indent
  
  ...`

**Comment by olifolkerd** [comment]
Yeah, that will be because i havn't linted the code on that branch yet, i do that just before the version number increment  as im about to release it. if you use the `dev:esm` or `dev:umd` commands instead (depending on the package you want) then that should not try and lint things

Cheers

Oli

**Comment by aStarlikeMine** [comment]
I couldn't get it running so will wait for the release. Thanks again.
