### ISSUE TITLE
HeaderMenu null exception thrown

### ISSUE THREAD

**Issue by Jojoshua** [olifolkerd/tabulator#3948]
**Describe the bug**
Crash in browser after using HeaderMenu

**Tabulator Info**
- 5.3.4

**Working Example**
https://jsfiddle.net/jojoshua/h3y52pdf/9/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to jsfiddle
2. Click on the column header menu and choose either Left Column or Right Column
3. Observe the script error in the browser console
```
Cannot read properties of null (reading 'hide')
    at HTMLDivElement.<anonymous> (Menu.js:254:19)
```

**Expected behavior**
I expected the operation to work without a crash

**Desktop (please complete the following information):**
 - OS: [Win 10]
 - Browser [Edge]
 - Version [105]

**Comment by olifolkerd** [comment]
Hey @Jojoshua 

Thanks for the headsup,

I have pushed a fix for this to the 5.4 branch, which i hope to release in the next week or so,.

Cheers

Oli :)
