### ISSUE TITLE
prevRow() and nextRow() doesn't work with AJAX

### ISSUE THREAD

**Issue by hitodev** [olifolkerd/tabulator#3949]
**Describe the bug**
prevRow() and nextRow() doesn't work with AJAX

**Tabulator Info**
Tabulator 5.3

**Working Example**
With non-AJAX, I can get previous row data (see console)
https://jsfiddle.net/a1sm3prL/2/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1.  Use AJAX
2.  Use the same rowFormatter
3.  See error : Uncaught (in promise) TypeError: prevRow.getData is not a function

**Expected behavior**
Access to previous row data, like with the non-AJAX version above

**Also tried**
I also tried to get previous data using a formatter, without success:
`    var altFdpFormatter = function(row, cell, editorParams, onRendered){
        var prevRow = row.getPrevRow();
        var prevRowData = prevRow.getData();
        console.log("prevRowData");
    };`

error : 
The row component does not have a getPrevRow function, have you checked that you have the correct Tabulator module 
Uncaught TypeError: row.getPrevRow is not a function

**Comment by olifolkerd** [comment]
Hey @hitodev 

If you think you have found an issue, please create a JS Fiddle that demonstrates the issue so that we can see how your table config affects the issue. Posting a link to a fiddle that shows everything is ok wont help us get to the bottom of the issue im afraid.

Cheers

Oli :)
