### ISSUE TITLE
Downloading a table with Tree Structure has no effect on the exported file

### ISSUE THREAD

**Issue by aolle99** [olifolkerd/tabulator#3950]
**Describe the bug**
En la documentación, deja a entender que si se pueden descargar tablas con DataTree, pero cuando lo he probado no funciona. No detecta la herencia y, a parte de no seguir la identacion, tampoco muestra los elementos colapsados. No funciona en ningun tipo de exportacion (csv,json,xlsx,pdf,html).

**Tabulator Info**
- Tabulator version: 5.3.4

**Working Example**
[https://jsfiddle.net/g3farz9y/](https://jsfiddle.net/g3farz9y/)

**To Reproduce**
1. Click any download button

**Expected behavior**
The downloaded file contains the indentation created by the dataTree.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 22

**Comment by olifolkerd** [comment]
Hey @aolle99 

That is correct, tree structure is a visual only representation of data in the table, it is not included in downloads, as most of the formats couldnt meaningfully support it.

Cheers

Oli :)
