### ISSUE TITLE
Edit tickCross not working with Safari

### ISSUE THREAD

**Issue by Thallius** [olifolkerd/tabulator#3951]
There is nothing more to say.

Open your manual page 

http://tabulator.info/docs/5.0/edit

with newest Safari Browser and try to change a tickCross in the example table 

It doesn't work.

**Comment by olifolkerd** [comment]
@Thallius 

It looks like you are using an old version of Tabulator.

Checkout the latest version http://tabulator.info/docs/5.3/edit

Cheers

Oli :)

**Comment by Thallius** [comment]
http://tabulator.info/docs/5.3/edit

is the version I have tried and it is still not working.
