### ISSUE TITLE
Suspend topCalc and bottomCalc updates when table.blockRedraw is applied

### ISSUE THREAD

**Issue by 500Foods** [olifolkerd/tabulator#3952]
*Is your feature request related to a problem? Please describe.**
When applying many consecutive updates to a table, using table.blockRedraw and table.restoreRedraw can help improve performance by suspending table redraws.  However, if your table has column calculations, like a bottomCalc: "count" applied to a column, these calculations are still updated.  As some of these can be computationally expensive, one can imagine that disabling them might also help performance.  But perhaps just as importantly, the displayed calculations don't match the table as it is displayed.  For example, if a table has four records displayed when the table is put into blockRedraw mode, and then rows are added, the count will show the actual count even though only the original four records are visible. 

**Describe the solution you'd like**
Updates to the these calculations should be suspended.  If the calculations themselves (internally) can also be suspended, I'd imagine that would help with performance as well.

**Describe alternatives you've considered**
Removing the calculation and then adding it again, but then the visual effect of the footer appearing and disappearing is undesirable.

**Comment by olifolkerd** [comment]
Hey @500Foods 

Great idea! i will get this in the 5.4 release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @500Foods 

I have just pushed this feature to the 5.4 branch which im hoping to release in the next week or so.

Cheers

Oli :)
