### ISSUE TITLE
New selection mode

### ISSUE THREAD

**Issue by 500Foods** [olifolkerd/tabulator#3953]
*Is your feature request related to a problem? Please describe.**
Currently, tabulator supports the idea of a "selection" where one or more rows can be highlighted, controlled by the "selectable" table option.  This works well and makes it easy to see what is selected.  In most of my tables (and in virtually every tabulator-like component I used in the decades prior to tabulator), the idea generally is to have one row selected at all times.  Except when there are no records at all.  

**Describe the solution you'd like**
A new table option, something like "selectionMode: persist".  This would then change tabulator's behavior slightly.
1. Implies "selectable: 1" (perhaps)
2. A row is always selected, the first row by default, and cannot be toggled off.
3. Cursor up/down moves the selected row.
4. Deleting a row selects the next row (or the previous row if the row is the last in the view)
5. Adding a row automatically selects it.

**Describe alternatives you've considered**
This can be implemented already by applying a number of separate adjustments.  For example, when deleting a row, the next (or previous if it was the last row) record can be selected.  Or when adding a row, the newly added row can be selected.  Or when a row is clicked, the new row can be marked as selected.  The trouble is that if you want to do this for a bunch of tables, then this becomes tedious and burdensome, requires much testing, and so on.

**Comment by olifolkerd** [comment]
Hey @500Foods 

Thanks for the suggestion,

This seems like a really specific usage case, It feels a lot like this is targeted a a specific need, and I i feel the combination of requirements is very specific..

I think the majority of this could be achieved quite easily with already existing functionality without needing to extend the table:

- You can already use `selectable:1` to define that it should be a rolling selection of 1, selecting another moves the selection.
- You could use the `dataProcessed` event to select the first row automatically on table load
- You could use the `rowAdded` event to select a row when it is added
- You `could use the `rowDeselected` event to ensure the table always has a row selected
- You could register the up and down arrows as keybindings to move the selection.

For that reason i would not be looking to add this mode, but i would happily chat on discord about how you can go about achieving this with existing functionality.

Cheers

Oli :)

**Comment by 500Foods** [comment]
Hi there....  I'm not sure I agree at all that my suggestion for having a different 'selectable' mode is a niche case.  It would be the default for all of the hundreds of Tabulators I've setup, save the handful that benefit from multi-selection, if it were available.  The main benefit is to make it easier to set this mode with less effort and testing required.  As it is now, my "default options" for Tabulator tend to be longer than the table declarations, as those almost always are just a list of column definitions.  But perhaps I'm just being lazy 😆 and really just need to setup my own "selectedTabulator()" function that sets all of these "on" functions to do my bidding when the tables are first created.

Such a function would need to define all of the above, but also deal with the unselection of a selected record and probably a few other things I'll have to get a handle on.  Likely at least half-a-dozen functions defined for each table.

**Comment by olifolkerd** [comment]
Hey @500Foods 

My point was more along the lines that this "mode" is a combination of many different features that is not very configurable and only has a very specific usage case.

To use your custom functionality more easily on multiple tables, the best approach would be to build out a [Custom Module](http://tabulator.info/docs/5.3/module-build) or set some [Default Options](http://tabulator.info/docs/5.3/modules#default);

Cheers

Oli :)
