### ISSUE TITLE
Placeholder text is not disappearing

### ISSUE THREAD

**Issue by Thallius** [olifolkerd/tabulator#3955]
You need a table with header filter and only one or two entries but a height for 10 or more entries.

When you enter some nonsense in the filter input, so that you get no results in the table, the placeholder text appears. 
That's fine. 
But when you then clear the filters content and the rows are appearing, the placeholder text is not disappearing but just scrolling down by the number of rows which were shown in the table.

![image](https://user-images.githubusercontent.com/666946/191957244-5b63bcd2-a5ed-42df-b411-879dc0dc754b.png)

**Comment by olifolkerd** [comment]
Hey @Thallius 

I have pushed a fix for this to the 5.4 branch that should be released in the next week or so.

Cheers

Oli :)

**Comment by robertkewei** [comment]
Hello @olifolkerd,

Is it possible to hide vertical scrollbar when using placeholder for empty table? I am using Tabulator 5.3

Robert
