### ISSUE TITLE
TextArea, 100%height - "ResizeObserver loop limit exceeded"

### ISSUE THREAD

**Issue by Jojoshua** [olifolkerd/tabulator#3956]
**Describe the bug**
Attempting to edit a TextArea editor when the table height is 100% fails with either "ResizeObserver loop limit exceeded" or allows a single character to be entered but then automatically canceled

**Tabulator Info**
- 5.3.4

**Working Example**
https://jsfiddle.net/jojoshua/Laz506eh/13/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to jsfiddle
2. Click in the first cell to try to edit the cell
3. Observe the error in the browser console

**Expected behavior**
Edit the textarea normally

**Desktop (please complete the following information):**
 - OS: [Win 10]
 - Browser [Edge, Chrome]
 - Version [105]

**Comment by olifolkerd** [comment]
Hey @Jojoshua 

This is because your table is set to 100% height in a body/html element with no defined height, the text area then tries to resize as it does the body changes size and the loop contiues.

If you put the table in an element with a defined height this shouldnt happen.

Cheers

Oli :)

**Comment by Jojoshua** [comment]
@olifolkerd I wouldn't know what to set the container element to, in fact this is probably going to be put inside a flexbox anyway....I expected setting height 100% for the table to do exactly that. If I specify an arbitrary height for the container then the table is cut off, if I specify a larger height than the table needs, it shows a huge amount of gray space. 

I tried setting maxHeight:'100%' from the variable height documentation http://tabulator.info/docs/5.4/layout#height-variable on the table and set a larger parent height then the table doesn't show the gray space but the textarea doesn't resize either, back to square 1.

What is the right combination to tell Tabulator to use variable height + allow the textarea to resize properly?

Am I supposed to use maxHeight 100% and the force redraw everytime text area changes?

**Comment by Jojoshua** [comment]
Just a note that this issue is now fixed since v5.5.1
