### ISSUE TITLE
Placeholder is incorrectly added to table when calling replaceData

### ISSUE THREAD

**Issue by iwiita** [olifolkerd/tabulator#3958]
**Describe the bug**
If `replaceData` is called on a table that uses pagination, then the placeholder is incorrectly added to the table.

**Tabulator Info**
5.3.4.

**Working Example**
https://codepen.io/iwiita/pen/VwxQyBN

**To Reproduce**
1. Open the codepen
2. Click on the 'replace' button
3. The placeholder is added to the table

**Expected behavior**
The placeholder should not be added to the table because the table contains data.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS 11.6.8
 - Browser: Chrome
 - Version: 105.0.5195.125

**Smartphone (please complete the following information):**
Not tested on a smartphone.

**Additional context**
This bug is also present when loading data using AJAX.
If pagination is not enabled, this bug is not present (with or without AJAX).

**Comment by olifolkerd** [comment]
Hey @iwiita 

Thanks for the info, this will be resolved in todays 5.4 release.

Cheers

Oli :)
