### ISSUE TITLE
clearData clears only the first page if ajaxUrl is set

### ISSUE THREAD

**Issue by cschnelting** [olifolkerd/tabulator#396]
Hi,

I have an tabulator with ajaxUrl set and when i use "clearData", only the first page is cleared. When I switch the pages, for example from 1 to 2 and then back to 1, the data on page 1 is back.
Also when I use "setData" with an empty data-array, the data in table is not cleared. This also occours, when the ajaxUrl returned an empty data-array.
Is this a bug?

EDIT: I'm using Tabulator v 3.1

**Comment by olifolkerd** [comment]
Hey,

If you are remotely paging your table, then clear data will not have any sensible affect because page 2 of the data still exists on the remote URL.

Could you explain what you are trying to achieve and i can suggest a suitable approach.

Cheers

Oli

**Comment by cschnelting** [comment]
Hi,
i would like to clear all the table-data on "clearData". Is this possible?
And, if the ajaxUrl returns an empty data-array, why is the table not cleared?

**Comment by olifolkerd** [comment]
could you give an example of the ajax response you are expecting to clear the table?

**Comment by cschnelting** [comment]
When I get an empty Data-Object from the Ajax response, the table keeps the last displayed rows.I would like to clear all the table rows if the response is empty.
I've tried with the following empty responses:
	{}
	{"data":[]}

**Comment by cschnelting** [comment]
Hi Oli,
do you have a solution how can i clear the grid if my Ajax-Respons is one of the following:
- {}
- {"data": [ ] }
?

Thanks!

**Comment by olifolkerd** [comment]
Hey,

the correct ajax responses for clearing your data are:

- for non-paginated data ```[]```
- for paginated data ```{last_page: 1, data: []}```

Cheers

Oli
