### ISSUE TITLE
Horizontal vdom breaks if scrolling all the way to the right

### ISSUE THREAD

**Issue by rathboma** [olifolkerd/tabulator#3960]
I'm going to try and replicate this outside of Beekeeper Studio. Here's what I do:

- Load a table
- Scroll all the way to the right
- Scroll all the way to the bottom
- Scroll all the way back to the left
- Scroll all the way to the top

Columns become totally misaligned

![tabulator-break-hoz-v-dom](https://user-images.githubusercontent.com/279769/193142022-520dff67-f1e9-4536-be29-c89fd0ec7e12.gif)

**Comment by rathboma** [comment]
Here's a way to replicate:

https://github.com/beekeeper-studio/tabulator/tree/example-hvdom

see examples/demo.html

**Comment by olifolkerd** [comment]
@rathboma Thanks,

I think this may be related to the other column missalignment bug you raise. I will have a look through it this weekend and see what i can do.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @rathboma 

On further inspection i cant seem to replicate this on my local updated version of Tabulator that fixed the other misalignment issues, so i am going to assume for now that it is resolved.

Im going to release 5.4 in the next couple of hours. If you are still having trouble after that, drop me a message on here and i can reopen it.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @rathboma 

I hear you are still seeing this issue your end.

Do you have a repeatable test case? i have been unable to replicate this my end.

If we can come up with a way to replicate it im happy to put out a patch release to fix it.

Cheers

Oli :)

**Comment by rathboma** [comment]
Hey!
I opened a new issue, but can close it:
https://github.com/olifolkerd/tabulator/issues/3970

**Comment by rathboma** [comment]
@olifolkerd here's my copy-pasta summary:

Version: 5.4

Replicated here: https://github.com/rathboma/tabulator-playground

Steps to reproduce:
- Set columns to 200
- Reset column widths
- Scroll all the way to the right
- scroll all the way to the bottom
- scroll all the way to the top
- Notice the column misalignment

GIF:

![broken-scroll](https://user-images.githubusercontent.com/279769/193655761-2dd03f66-2048-434b-8d8f-7f61cd7d3210.gif)

**Comment by j-lim-sigma** [comment]
Perhaps related to this issue.  When scrolling left / right,  the header is not scrolling along.

**Comment by j-lim-sigma** [comment]
Perhaps my problem is similar to this. When installing via NPM, the header is not following along when scrolling left / right (just like the GIF above). However, when using CDN, it works just fine (i.e. header is following left / right) like this: https://jsfiddle.net/jlimfiddle/a7mLocpk/5/.

**Comment by olifolkerd** [comment]
Hey @rathboma 

Thanks for the example, that was very helpful.

I have pushed a fix for this to the master branch and will include it in the patch release later today.

Cheers

Oli :)
