### ISSUE TITLE
Persistence page.page not reset when remote sorting

### ISSUE THREAD

**Issue by antman3351** [olifolkerd/tabulator#3961]
Hi, 

I think there's a bug with the page persistence when using remote sorting

**Describe the bug**
When using remote sorting & pagination, when the sort is changed Tabulator returns to the first page but doesn't store the value to the persistence

**Tabulator Info**
5.3.4

**Working Example**
https://jsfiddle.net/zd0fh58w/17/

**To Reproduce**
With the console open:
1) Go to page 3 ( in the console the call to persist the page can be seen )
2) Click the header to change the ordering  ( in the console NO call to persist the page can be seen )

**Expected behaviour**
The page reset is persisted

Thanks!
Antonio

**Comment by olifolkerd** [comment]
Hey @antman3351 

Thanks for the feedback, i have pushed a fix for this to the master branch and will include it in todays patch rlease.

Cheers

Oli :)
