### ISSUE TITLE
GroupComponent.isVisible() always undefined

### ISSUE THREAD

**Issue by andy-5** [olifolkerd/tabulator#3963]
**Describe the bug**
`GroupComponent.isVisible()` always returns `undefined`. See console output of https://jsfiddle.net/ne3rv8k5/1/ .

The reason is that `isVisible()` [returns the field](https://github.com/olifolkerd/tabulator/blob/dbb5cb544b228e573ac50bbb3a94e12af84dea87/src/js/modules/GroupRows/GroupComponent.js#L43) `_visible` of the group, which is not defined - it should be `visible` (without underscore).

**Tabulator Info**
The bug is present in the latest git version.

**Working Example**
https://jsfiddle.net/ne3rv8k5/1/

**To Reproduce**
- Go to https://jsfiddle.net/ne3rv8k5/1/ and run it
- See console output with the results of `isVisible()`

**Expected behavior**
`isVisible()` should return either `true` or `false`, depending on the `visible` field of the group

**Comment by olifolkerd** [comment]
Hey @andy-5 

As per the comment on the PR, this fix will be available on the 5.4 release in a couple of hours.

Cheer

Oli :)
