### ISSUE TITLE
Widths not persisted when calling `setWidth`

### ISSUE THREAD

**Issue by rathboma** [olifolkerd/tabulator#3965]
## Description

When using `persistence` for column widths, calling `column.setWidth` is not permanent, so if you refresh the page, the columns snap back to their previous sizes.

## Replication
1. Enable local persistence for column widths
2. Load a table with `fitData`
3. Call `setWidth` on a column to set it to, say, 200px.
8. Reload the page and the widths are not 200px

## Workarounds

If using a fixed width, I can use `setColumnLayout`, but if I want to size the widths to the content, there's no easy way to do that, and persist it. (eg using `column.setWidth(true)`)
 
Here is this in action:
https://github.com/rathboma/tabulator-playground

![200-no-stick](https://user-images.githubusercontent.com/279769/193346305-7c349908-6ffd-4a5c-ae18-c620a317aa92.gif)

**Comment by olifolkerd** [comment]
Hey @rathboma 

Thanks for the info,

I have pushed a fix for this to the 5.4 branch that i will be releasing in a couple of hours.

Cheers

Oli :)
