### ISSUE TITLE
cant't initialise table empty without ajaxUrl

### ISSUE THREAD

**Issue by cschnelting** [olifolkerd/tabulator#397]
hi,

I would like to initialize the table empty. If I init the tabulator without ajaxUrl, I can't set the ajaxURL later.
Is this a bug?

EDIT: I'm using Tabulator v 3.1

**Comment by olifolkerd** [comment]
If you want to set the ajaxURL later you can use the ***setData*** method:
```js
$("example-table").tabulator("setData", "http://my.domain.com");
```

Let me know if that helps

Cheers

Oli

**Comment by cschnelting** [comment]
Ok, thank you!

**Comment by cschnelting** [comment]
I have still errors. I initialize my Tabulator as follows:
`var myGrid = $("#myGrid");
myGrid.tabulator({
height:"400px",
fitColumns:true,
movableColumns: true,
persistentLayout:"cookie",
persistentLayoutID:"myGrid",
selectable:1,
selectablePersistence:false,
paginationSize:25,
columns:[
    {title: i18n('id'), field:"id", sorter:"number"},
    {title: i18n('text'), field:"text", sorter:"string"}
]
});`

Then, later I would like to set the Data:
`$("#myGrid").tabulator("setData", "../query?relation=myGrid&id="+row.data['0'].id);`

The Ajax-Response is the following:
`{ "data": [{"id":100001422,"text":"EXAMPLE_TEXT"}], "last_page": 1 }`

And i receive the Error:

> Data Loading Error - Unable to process data due to invalid data type 
> Expecting: array 
> Received:  object 
> Data:      Object {data: Array(1), last_page: 1}
