### ISSUE TITLE
Columns de-sync when changing column widths and scrolling to bottom of table

### ISSUE THREAD

**Issue by rathboma** [olifolkerd/tabulator#3970]
Version: 5.4

Replicated here: https://github.com/rathboma/tabulator-playground

Steps to reproduce:
- Set columns to 200
- Reset column widths
- Scroll all the way to the right
- scroll all the way to the bottom
- Scroll all the way to the left
- scroll all the way to the top
- Notice the column misalignment

GIF:

![broken-scroll](https://user-images.githubusercontent.com/279769/193655761-2dd03f66-2048-434b-8d8f-7f61cd7d3210.gif)

**Comment by rathboma** [comment]
@olifolkerd firstly - 5.4 is amazing. Thanks for pushing that out.

Wanted to make sure you're able to replicate this problem, and if not, what else I can do to help you debug (or fix?) it.

**Comment by olifolkerd** [comment]
Thanks. Glad to hear it is working for you.

Sorry for the delayed response to your last message, I haven't had a chance to look through it yet. I'm planning on doing a patch release on Sunday, so will look into it more then

**Comment by rathboma** [comment]
Sounds good. I've put together a Beekeeper release, but I'm going to sit on it until we can hopefully figure this one out because hide/show columns is a big part of it.

**Comment by olifolkerd** [comment]
Hey @rathboma 

Thanks for the example, that was very helpful.

I have pushed a fix for this to the master branch and will include it in the patch release later today.

Cheers

Oli :)

**Comment by rathboma** [comment]
@olifolkerd you are amazing. Thanks!
