### ISSUE TITLE
JS error is thrown when trying to refresh a filtered table with grouped data

### ISSUE THREAD

**Issue by yevhensayenko** [olifolkerd/tabulator#3971]
**Describe the bug**
JS error is thrown when trying to refresh a filtered table. It not always can be reproduced but I created a JSFiddle where it always fails.

**Tabulator Info**
- 5.3.4, 5.4.0 also has this bug.

**Working Example**
https://jsfiddle.net/27sdL3ph/ - It is a table with grouping and sorting.

**To Reproduce**

1. Go to https://jsfiddle.net/27sdL3ph/
2. Enter 'bob' into search field of first column. It will leave one row filtered.
3. Click 'reload' button
4. See error in browser console. Table layout becomes invalid.

Seems it tries to redraw table while it is refreshing. I have managed to make a hack-workaround for refresh in my project to make it working - it can be run in this JSFiddle using 'fixed reload' button.

**Expected behavior**
It should reload without error.

**Desktop:**
 - OS: Linux
 - Browser: latest Chrome and FF.

**Comment by olifolkerd** [comment]
Hey @yevhensayenko 

Thanks for the info.

It looks like an unusual interaction between the filter and group modules. i will have a look into this further.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @yevhensayenko 

I have pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)
