### ISSUE TITLE
The select type data filters in header scroll the options menu if there is a scroll and they do not match the column

### ISSUE THREAD

**Issue by aolle99** [olifolkerd/tabulator#3973]
**Describe the bug**
When you have a set of columns large enough to generate horizontal scrolling, if you press a filter that was not initially visible (you have scrolled to see it), when you press it, the scroll restarts and the options menu appears in another column.

**Tabulator Info**
This has started to happen in version 5.4. In version 5.3 it does not happen.

**Working Example**
https://jsfiddle.net/nrbuj9oc/1/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Adjust the size of the viewing window so that the horizontal scroll bar appears.
2. Move the bar to the right to see the columns that do not fit on the screen
3. Click on any of the filters in the click me columns
4. Watch how the horizontal scroll returns to the left and the scrolled options menu appears.

**Expected behavior**
The filter options menu appears below the filter it belongs to, in the same column.

**Screenshots**
![image](https://user-images.githubusercontent.com/9889357/194249454-fbbee568-3c04-4aaf-abed-aa9238797022.png)
When you press the filter of the last column:
![image](https://user-images.githubusercontent.com/9889357/194249283-612eb9b7-9a9a-4272-a7cc-1b9a8187efcc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 106.0.5249.103

**Comment by olifolkerd** [comment]
Hey @aolle99 

Thanks for the headsup, i have pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)
