### ISSUE TITLE
Error with pagination and ajax

### ISSUE THREAD

**Issue by cschnelting** [olifolkerd/tabulator#398]
Hi,
If I don't set the property pagination to "remote" and use ajaxUrl, I get the following Error:

Tabulator.js Code-Line 1923:
Data Loading Error - Unable to process data due to invalid data type Expecting: array Received: object

If I only add the property pagination:"remote" to tabulator-init, it's fine. Is there a way to disable paging and using AjaxUrl?

EDIT: I'm using Tabulator v 3.1

**Comment by olifolkerd** [comment]
If you use remote pagination you need to format the data you return from the server differently:
```js
{
    "last_page":15, //the total number of available pages
    "data":[ // an array of row data objects
        {id:1, name:"bob", age:"23"}, //example row data object
    ]
}
```
If you are just sending remote data with out the pagination (which is perfectly fine, just dont include the pagination option in your constructor, you should be returning a JSON ecoded array of the table data:
```js
[ 
    {id:1, name:"bob", age:"23"}, //example row data object
]
```

The error you are receiving is indicating that you are sending data in an unexpected format.

Let me know if that clears things up
