### ISSUE TITLE
Select filtered rows documentation error

### ISSUE THREAD

**Issue by antman3351** [olifolkerd/tabulator#3980]
Hi Oli,

**Website Page**
[Select rows](http://tabulator.info/docs/5.4/select)

**Describe the issue**
Documentation states:
"If you do not pass any arguments to the `selectRow` function, all rows will be selected. **To select only rows that have been filtered pass `true` as the first argument.**" 

Passing `true` selects the row with ID 1, passing `active` works.

Antonio.

**Comment by olifolkerd** [comment]
Hey @antman3351 

Thanks for the feedback, i will ensure that is fixed in todays docs update.

Cheers

Oli :)
