### ISSUE TITLE
Horizontal Scroll Bar returns left when scrolling to a column in another column group

### ISSUE THREAD

**Issue by gaiteram** [olifolkerd/tabulator#3983]
Hi Tabulator Developers, 

This bug is about the horizontal scroll bar returning to left (base position) when the column it scrolls to is inside a different column group, instead of continuing the horizontal scroll when "scrollTo" and "scrollToColumn" are called.

I am using a public resource of tabulator for js fiddle using tabulator version 5.1.0. I tried changing it to 5.4.0 but same issue occurs. 

Here is the jsfiddle link:            https://jsfiddle.net/testdev1/43pcumyL/4/

A step by step guide to recreate the issue in JS Fiddle:
(I would suggest to open console to know the incremental value)
- click button "move right" until the last column of the ungrouped columns which is driver(dob)
- watch carefully where the horizontal scroll bar is positioned(image 3)
- click button "move right" and see what happens to horizontal scroll bar position(image 2)

By now the column scrolled to is "test1", this column should be on the left side and horizontal scroll bar should be positioned as seen in the screenshot(image 1) below.
But instead, the horizontal scroll bar returns to the left even when the column it is holding right now is "test1", as seen in the screenshot(image 2) below.
This error happens when I scroll to a column inside a column group.

-image 1-
![image 1](https://user-images.githubusercontent.com/52522062/195042030-b33a1b72-ea1b-4271-887a-892b59a7bf3e.jpg)

-image 2-
![image 2](https://user-images.githubusercontent.com/52522062/195042055-d0d83c3d-7fad-4470-9557-eba393244553.jpg)

-image 3-
![image 3](https://user-images.githubusercontent.com/52522062/195044637-a80f8f65-37f9-4be3-91e9-4dd3d337ab9d.jpg)

 - OS: windows 11
 - Microsoft Edge / Google Chrome
 - Version 106.0.1370.37
 
 I hope you can help me fix this problem!

Thanks!

**Comment by olifolkerd** [comment]
Hey @gaiteram 

Thanks for the headsup,

I have pushed a fix for this to the master branch and will include it later in todays patch release.

Cheers

Oli :)

**Comment by gaiteram** [comment]
Many thanks!
