### ISSUE TITLE
edit cell after filtering throws error

### ISSUE THREAD

**Issue by jaguarxii** [olifolkerd/tabulator#3985]
**Describe the bug**
after filtering by a column header filter, any edit throws an error.

**Tabulator Info**
5.4.1

**Working Example**
[tabuletor filter+editting possible bug](https://codepen.io/jaguarito/pen/yLjwQmy)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Enable browser console to see the error
2. Use any column header filter (name, last name or type) to filter some records on the table
3. edit any cell of any filtered record
4. you get an error (console) like `Uncaught TypeError: t is undefined` using waterfox
    the error is more descriptive using Chrome `GroupRows.js:524 Uncaught TypeError: Cannot read properties of undefined (reading 'getPath')
    at ce.reassignRowToGroup (GroupRows.js:524:31)`

**Expected behavior**
edit the cell content of the selected row after filtering the table by any column header filter

the table option that causes this error is `groupUpdateOnCellEdit: true`, if this option is not set everything works as expected

**Screenshots**
![image](https://user-images.githubusercontent.com/8013436/196013076-6df23345-ac6c-4e2c-9b2d-5bef99823ca1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Waterfox G5.01, Chrome 106.0.5249

**Comment by olifolkerd** [comment]
Hey @jaguarxii 

Thanks for the headsup, i have pushed a fix for this to the master branch and will include it later in todays patch release.

Cheers

Oli :)
