### ISSUE TITLE
getDataCount("selected") does not return the correct value.

### ISSUE THREAD

**Issue by carsonwood1** [olifolkerd/tabulator#3988]
**Describe the bug**
Calling `table.getDataCount("selected")` does not return the correct value.

**Tabulator Info**
- Latest version, but I tested back and see it regressed with version 5.3.3

**Working Example**
- Last working version: https://codepen.io/carsnwd95/pen/rNGxQLv
- Current not-working version: https://codepen.io/carsnwd95/pen/OJZYxbL

**To Reproduce**
1. Make sure the console in code pen is open, I am listening for the `rowSelectionChanged` event and logging `getDataCount("selected")`
2. Click "Select All", all 10 rows should be selected.
3. Notice in the current version, `getDataCount` says there are 0 selected rows. Notice in the 5.3.2 version it says the correct amount of 10 rows.

**Expected behavior**
I would expect `getDataCount` when given the argument of "selected" to report back the number of rows selected. 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Latest

**Comment by carsonwood1** [comment]
Calling `getSelectedRows().length` essentially does the same thing, but think still might be worth fixing this original issue or updating the documentation?

**Comment by olifolkerd** [comment]
Hey @carsonwood1 

Thanks for the headsup,

I have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)
