### ISSUE TITLE
Examples Very Difficult to Read

### ISSUE THREAD

**Issue by teamayu** [olifolkerd/tabulator#3989]
Firstly, thank you for this awesome plugin.

The docs would be a lot better if the example text wasn't so dark. I am colour blind and I find it very difficult to see, I either have to highlight the page or copy / paste into an editor. It can give people a headache after a while. A touch brighter would be most helpful, thank you.

![21-10-2022_163039](https://user-images.githubusercontent.com/10624092/197150647-de8185d0-e3e2-419c-87ff-e348c207ff89.png)

**Comment by olifolkerd** [comment]
Hey @teamayu 

It looks like something has gone wrong in your browser there, the code examples are all fully coloured and syntax highlighted on the website, as you can see from the screenshot i have just taken:
![image](https://user-images.githubusercontent.com/6840524/197196645-34f9b90c-b971-47bc-940b-4320fd621988.png)

This is all managed by googles 'code-prettify' functionality which is pulled in via one of their CDNS. it may be this was temporarily unavailable when your page loaded. Could you try clearing your cache of the page and loading it again, and checking your dev console for any errors.

Failing any of that what browser are you on?

Cheers

Oli

**Comment by 500Foods** [comment]
I see this on Firefox...
![image](https://user-images.githubusercontent.com/41052272/197201257-e643bb78-5113-4389-9854-e53461799ebf.png)
And Chrome...
![image](https://user-images.githubusercontent.com/41052272/197201795-2947f8d2-95d4-4855-ba95-f2983fe9a2da.png)

**Comment by olifolkerd** [comment]
Firefox: 
![image](https://user-images.githubusercontent.com/6840524/197203704-0dea0d38-f29e-4fb0-ae8b-8edecdf8aa41.png)

Chrome:
![image](https://user-images.githubusercontent.com/6840524/197203746-0834b9c0-e9c2-4353-9309-a965ce336931.png)

**Comment by 500Foods** [comment]
I just check Firefox/Chrome on Linux, Firefox/Chrome on Windows, and Safari on an iPad and it is all the same - no highlighting.  I think it might have been this way for a while.  Not sure.  Too shy to bring it up as last time I brought up an issue with website colors I had mistakenly changed the brightness on my desktop and it was actually fine.  Once bitten, twice shy sort of thing!

And I'm sure dark mode is set everywhere I look.  I tried changing it in a couple of places, but no change.  I think I posted the console log showing that the google library just isn't loading?  Maybe?

**Comment by olifolkerd** [comment]
Hey @500Foods 

I have tried it across numerous devices, mobile, tablet, desktop and laptop, on multiple OS's and browsers and it works on all of them for me.

Not sure where to go from there, i have cleared caches and everything.

Cheers

Oli :)

**Comment by 500Foods** [comment]
Perhaps this is CDN shenanigans - a broken library that is fixed but not deployed everywhere perhaps?  Just tried again and now Firefox/Linux looks lovely but nothing else....
![image](https://user-images.githubusercontent.com/41052272/197207322-0b01f591-60fa-43ab-8d80-d70d300525ef.png)
So maybe give it a day and see if it gets sorted?  I've tried the same -reload/delete caches/etc and can't seem to get any others to work, and didn't do anything special for the Firefox/Linux to suddenly start working for the first time.  

Fun times!

**Comment by olifolkerd** [comment]
I will have a look switching from pulling the source from a CDN to a locally hosted copy and see if that reduces some of the shinnanigans.

**Comment by teamayu** [comment]
Sorry for the late reply. Well, I'm happy that the colours should be better. I have tested in FF, Edge, Chrome and Opera, all the same. I have cleared all the caches. But on my android phone and tablet it is fine. That's good I can use the tablet for reference.

Not sure about the browsers though, will try reinstalling them to see if it makes any difference.

**Comment by teamayu** [comment]
Could these errors be causing the issue?

![22-10-2022_010318](https://user-images.githubusercontent.com/10624092/197250224-72ed7f38-a5fe-4a3d-aa69-23bb681358fa.png)

I see them in the error console.

**Comment by olifolkerd** [comment]
Hey Everyone,

I have pushed an update to the site to pull the pretty print files from a local source as that CDN is clearly having issues.

I have also updated the base font colour of the code areas to be a much brighter colour so they are legible even if the pretty print doesnt load.

Thanks for the feedback

Cheers

Oli :)

**Comment by teamayu** [comment]
Fantastic, thanks Oli, that looks great. :)
