### ISSUE TITLE
ajax sort option -  disable specific field 

### ISSUE THREAD

**Issue by mohanen** [olifolkerd/tabulator#399]
Hi oli, 
 
Your 3.1.1 patch working well in ajax sorting.
Is there a way to disable sorting option for specific field in ajax sorting.

Say like a scenario of printer icon fields i don't wanna sort that field. 

but getting a call with (field argument for that column not given )
..... 
`sort      :  undefined`
`sortDir :  asc/desc`  
.....
stopping it making a ajax call will be a better way.

**Comment by olifolkerd** [comment]
If you set the ***headerSort*** property to ***false*** in that columns definition object it will prevent users from being able to sort with it by clicking on the header.
