### ISSUE TITLE
Row formatters that depend on row data aren't applied to the exported HTML

### ISSUE THREAD

**Issue by gagamilano** [olifolkerd/tabulator#3991]
**Describe the bug**
If a row formatter depends on table data (e.g. only change the background color if a data field is true), the formatter is not applied correctly to the exported HTML that you get from `getHtml()`

**Tabulator Info**
- Which version of Tabulator are you using? I'm using version 4.9, but I get the same error on 5.4.2.

**Working Example**
[jsfiddle](https://jsfiddle.net/7ac8L29m/)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Create table with a row formatter that changes background color based on a data field
2. Export table using `getHtml()`
3. The condition to change the background color is met in the original table but not in the exported table. The odd part is that if there's an `else` after checking the data field, then that condition is met. So it seems that row data is not accessed at all/missing when exporting?

**Expected behavior**
I expect the row formatter to be applied in the same way.

**Screenshots**
In [this](https://i.postimg.cc/VLjfTCNB/immagine.png) screenshot of the above jfiddle you can see that the row formatter is applied to the first table but not to the exported table. However the cell formatter is applied correctly to both.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 106.0.5249.119

**Comment by olifolkerd** [comment]
Hey @gagamilano 

Thanks for the headsup,

I have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)
