### ISSUE TITLE
onRendered not called for custom editor when used as headerFilter

### ISSUE THREAD

**Issue by omfgicbf** [olifolkerd/tabulator#3992]
**Describe the bug**
When `onRendered` is used in a custom editor it does not fire when that editor is used as a header filter.

When that same custom editor function is used as a column editor, `onRendered` is called as expected.

**Tabulator Info**
- 5.4.2

**Working Example**
https://codepen.io/omfgicbf/pen/NWMQBab

**To Reproduce**
1. Load the CodePen https://codepen.io/omfgicbf/pen/NWMQBab
2. The custom editor is displayed in the column header, however, `onRendered` does not fire and the alert is not shown.
4. Click in any of the cells in the Email column and `onRendered` fires as expected.

**Expected behavior**
`onRendered` fires when a custom editor is used as a header filter.

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome 106.0.5249.119

**Comment by olifolkerd** [comment]
Hey @omfgicbf 

Thanks for the headsup,

i have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)
