### ISSUE TITLE
New Built-In Calculation Function: Distinct

### ISSUE THREAD

**Issue by 500Foods** [olifolkerd/tabulator#3993]
*Is your feature request related to a problem? Please describe.**
Not especially.

**Describe the solution you'd like**
There are already several column calculation functions that can be added via topCalc and bottomCalc, like min, max, and count, for example.  Would be handy to have another built-in function called "distinct" which returns the number of distinct values rather than just a count of values.  If you had a column that consisted of something like IP Addresses, for example, this would return how many different IP addresses were in the column.

**Describe alternatives you've considered**
It isn't hard to implement this using a custom calculation:
```
            bottomCalc:  function(values, data, calcParams) {
              return new Set(values).size;
            }
```
**Additional context**
I realize this is a slippery slope, as you might not want to muddy Tabulator with too many built-in things that just cause bloat.  But I think this comes up plenty often enough that it might well rise to the level of a useful built-in function, saving the work of having to figure out how to do this using a custom function.

**Comment by olifolkerd** [comment]
Hey @500Foods 

Sounds like a great idea, though could i uggest naming it "unique" instead to avoid confusion.

Sounds like the perfect candidate for a PR if you already have the logic. The other calc functions can be found in `/src/js/modules/ColumnCalcs/defaults/calculations`

Cheers

Oli :)

**Comment by 500Foods** [comment]
I went with distinct primarily because it is what SQL uses, but unique works just as well.  Will check out the possibility of a PR in the coming days.  Not my area of expertise, but would like to contribute so I'll give it a shot... 🤷🏻‍♂️ 😄 👍🏻

**Comment by olifolkerd** [comment]
Hey @500Foods 

I have pushed this update to the 5.5 branch and will include it in next months v5.5 release.

Cheers

Oli :)

**Comment by 500Foods** [comment]
That's great!  I'm sorry I couldn't manage a PR for this.
