### ISSUE TITLE
Tabulator 5.4.2 destroy() fails if setFilter() was used

### ISSUE THREAD

**Issue by AlgirdasR** [olifolkerd/tabulator#3995]
**Describe the bug**
If setFilter() was used destroy() causes an exception

**Tabulator Info**
 5.4.2

**Working Example**
https://jsfiddle.net/k4nh9Lmz/1/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Click destroy button
2. 'Group.js:489 Uncaught TypeError: Cannot create property 'innerHTML' on boolean 'false'' is thrown

**Comment by AlgirdasR** [comment]
If no groups exist (comment out  //groupBy: 'type', ) -> destroy() works

**Comment by olifolkerd** [comment]
Hey @AlgirdasR 

Thanks for the headsup, i have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)
