### ISSUE TITLE
Alternative parameter names for sort

### ISSUE THREAD

**Issue by buste18** [olifolkerd/tabulator#3996]
**Website Page**
[A link to the page with the issue](https://tabulator.info/docs/5.4/page#remote-url)

**Issue**
Changing the default sort[0][field] and sort[0][dir] params into custom names to orderby and dir don't work.

Based on the "Request URL" documentation, you can use the "dataSendParams" option to set alternative parameter names. But I tried this code but seems not to work:

dataSendParams:{
    "page":"pageNo",
    "size":"limitTo",
    **"sort[0][field]":"orderBy",**
    **"sort[0][dir]":"dir"**
},

**Comment by olifolkerd** [comment]
Checkout the Ajax docs to see how you can handle complex Param scenarios using the ajaxParams callback
https://tabulator.info/docs/5.4/data#ajax-params

Cheers

Oli :)

**Comment by pageagency** [comment]
Do you have any more details on this? I am trying to modify the sorters to work with an API that accepts sorting parameters like this:
`
?sort=sort,-date_created,author.name

// or

?sort[]=sort
&sort[]=-date_created
&sort[]=-author.name
`
I would appreciate some pointers. I've tried modifying them in ajaxParams, ajaxConfig, dataSendParams, ajaxURLGenerator, and I am at a loss.
