### ISSUE TITLE
Placeholder Not Rendered When Configured with HTMLElement 

### ISSUE THREAD

**Issue by Bryconc** [olifolkerd/tabulator#3997]
# Placeholder Not Rendered When Configured with HTMLElement 

**Describe the bug**
According to [documentation for placeholder](https://tabulator.info/docs/5.4/layout#placeholder)

> You can use the placeholder option to display a message to your users when the table has no data set. The function can either take a string to display or, the HTML or DOM Node to display in the empty table. 

Further the [Typescript type](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/tabulator-tables/index.d.ts#L872) also shows placeholder as accepting an `HTMLElement`.

```typescript
placeholder?: string | HTMLElement | undefined;
```

However, when configured with the result of `document.createElement` nothing is shown for the table placeholder.

**Tabulator Info**
- Which version of Tabulator are you using? **5.4.2**

**Working Example**

https://codepen.io/Bryconc/pen/KKeKRoQ

**Expected behavior**

I expect the table should render the HTMLElement as the placeholder, assuming I am reading the docs correctly.

With the Codepen example, I expect the `placeholderText` text to be rendered inside the table as a placeholder.

**Screenshots**
![tabulator_htmlelement_placeholder](https://user-images.githubusercontent.com/7593369/197850279-c102f5b0-9f25-4dcb-b5c6-f84e49ad7348.png)

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.6
 - Browser: Chrome
 - Version: Version 106.0.5249.119 (Official Build) (x86_64)

**Comment by Alex-Github-Account** [comment]
Probably related to the bug I am expiriencing: https://github.com/olifolkerd/tabulator/issues/4037
Looks like we wont get any fix soon (if ever), so I have provided temprorary fix for this, look up my opened issue
I encourented at least 4 more bugs which are still unsolved. 
I reccommend to switch to react-tables and abandon this abandoned project

**Comment by olifolkerd** [comment]
Hey @Bryconc 

Thanks for the headup,

I have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)
