### ISSUE TITLE
Bug in date/time/datetime editor when using Luxon dates

### ISSUE THREAD

**Issue by abwterrym** [olifolkerd/tabulator#3998]
**Describe the bug**
When a column uses:

        editor:"date",
        editorParams:{format: true}

User editing via the datetime picker clears the field.

**Tabulator Info**
I've reproduced the problem under 5.3.4 and 5.4.2.

**Working Example**
https://jsfiddle.net/xdubow7q/1/

**To Reproduce**
Run the jsfiddle example, above.
Change a date cell using the date picker in the Hire Date column.  The cell value disappears.

**Expected behavior**
The cell value should be the date chosen via the date picker.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version 106.0.1370.52

**Additional context**

The bug is specific to date columns using "editorParams:{format: true}" in the column configuration, indicating the date format is a Luxon date.  From https://tabulator.info/docs/5.4/edit#editor-date:

> format - the format for the date to be stored in the table. This accepts any valid [Luxon format string](https://moment.github.io/luxon/#/parsing?id=table-of-tokens), or the value "iso" which accept any ISO formatted data. If the input value is a luxon DateTime object then _**you should set this option to true**_. (emphasis added)

Lines 11685-11687 of the 5.4.2 version of tabulator.js are:

	if(value && inputFormat){
		value = DT.fromFormat(String(value), "yyyy-MM-dd").toFormat(inputFormat);
	}

Variable "inputFormat" is set to boolean "true" from "editorParams:{format: true}" in the column configuration.  Passing boolean "true" into the "toFormat()" function above produces an empty string, which is then put into the cell.

I fixed the problem by changing this code to:

	if(value && inputFormat){
		if (typeof inputFormat === "string") {
			value = DT.fromFormat(String(value), "yyyy-MM-dd").toFormat(inputFormat);
		} else {
			value = DT.fromFormat(String(value), "yyyy-MM-dd");
		}
	}

There's similar code under the "time" format function at line 11784 and in the "datetime" function at line 11882 which probably need similar changes, but I haven't tested those editor functions specifically.

**Comment by olifolkerd** [comment]
Hey @abwterrym 

Thanks for the headsup, i have pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)
