### ISSUE TITLE
Reactivity: deleting selected row does not trigger rowSelectionChanged

### ISSUE THREAD

**Issue by Martino-Martinez** [olifolkerd/tabulator#3999]
**Describe the bug**
- Reactivity: deleting selected row does not trigger rowSelectionChanged

**Tabulator Info**
- Version 5.4.2

**Working Example**
- https://jsfiddle.net/92euw6q8/

**To Reproduce**
- See console
- When deleting a selected row only rowDeselected, but not rowSelectionChanged, is triggered

**Expected behavior**
- deleting selected row triggers rowSelectionChanged

**Screenshots**

![image](https://user-images.githubusercontent.com/103148068/198024592-9d49d1a1-0472-40f8-b959-6a07a09bef93.png)

![image](https://user-images.githubusercontent.com/103148068/198023428-30186c6b-20c5-42f4-9819-c69daaa82c75.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome 105.0.5195.127

**Comment by Martino-Martinez** [comment]
Thanks for your answer. I would find it more consistent if rowSelectionChanged would also be fired, because after all the selection did change (per user interaction or not). Since it doesn't get fired, I need to listen to several events to get the desired result (I am using tabulator in vue3).

Cheers
-- Martin

**Comment by olifolkerd** [comment]
I understand your point of view, but say for example you setData on the table replacing 1000s of rows, that would a huge number of events, which could potentially be blocking. In this case it is just one event.

Also when a row is deleted it looses it's component so there is nothing to pass to the callback 

While I take your point on board,the current functionality works and all it requires for your usage case is an additional event listener so I will not be looking to include this feature (this is true across multiple modules so is consistent)

I will however look at improving the docs to make this clearer

Cheers

Oli

**Comment by Martino-Martinez** [comment]
Hi Oli -

thanks for your response. As mentioned, I am using tabulator in vue3 and I am modifying the data in-place with splice. When I am removing a lot of (selected) records with splice, I am getting one rowDeselected event per row that is removed, which is exactly what you wrote: 
`that would a huge number of events, which could potentially be blocking`
Maybe there is a better way to do it, but this is the only way I could get it to work in my scenario.

Cheers
-- Martin
