### ISSUE TITLE
DragDrop Rows, reorder / sortable

### ISSUE THREAD

**Issue by patagoniahiker** [olifolkerd/tabulator#4]
Hi, is it possible to use the jquery UI sortable as an option on the rows, with a fixed link for the consistent column sizes http://bit.ly/1RbVrPM

        // Return a helper with preserved width of cells
        var fixHelper = function(e, ui) {
	                ui.children().each(function() {
		         $(this).width($(this).width());
	     });
	  return ui;
        };

        $("#sort tbody").sortable({
	      helper: fixHelper
        }).disableSelection();`

we can then use the toArray func https://api.jqueryui.com/1.10/sortable/ to past back to as p srvr
http://jsfiddle.net/bgrins/tzYbU/

**Comment by olifolkerd** [comment]
Hi,

Im not sure what you are asking there? the column widths are can be set in the column definitions using the **width** property, and all columns can be sorted already by clicking on the arrow in the header.

You can define a custom sorting function in the column definition. see : https://github.com/olifolkerd/tabulator/wiki/Sorting-Data for more information on this.

are you asking for a programmatic way to trigger the sort?

Oli

**Comment by olifolkerd** [comment]
On re-reading that i now follow what you are after.

i will be adding the ability to move reorder rows (using JQuery sortable) in the next couple of weeks.

**Comment by patagoniahiker** [comment]
Thanks I will wait :+1:

**Comment by olifolkerd** [comment]
Movable rows and columns are now available in the latest release (1.6.0).

You can enable movable rows by setting the ***movableRows*** parameter to **true**.

You can enable movable columns by setting the ***movableCols*** parameter to **true**.

Full instructions on this feature can be found [Here.](https://github.com/olifolkerd/tabulator/wiki/Movable-Rows-and-Columns)

**Comment by patagoniahiker** [comment]
you rockstar, you :+1:

**Comment by olifolkerd** [comment]
Which demo isn't working, I cant seem to find any issues at this end? which browser is the issue on?

A guide to creating icon/button columns can be found [here](https://github.com/olifolkerd/tabulator/wiki/Formatting-Data#iconbutton-columns)

Cheers

Oli

**Comment by olifolkerd** [comment]
Hi Guys,

I have just launched a new documentation site for tabulator, check it out:
http://olifolkerd.github.io/tabulator/

Oli
