### ISSUE TITLE
column disintegrated with header

### ISSUE THREAD

**Issue by craigcosmo** [olifolkerd/tabulator#40]
![screen shot 2016-07-23 at 4 17 54 pm](https://cloud.githubusercontent.com/assets/538657/17077202/7a515cbc-50f1-11e6-98d3-d21eaeb9c5c4.png)

reproduce:
switch position between headers `name` and `task progress`. Then sort `name`

**Comment by olifolkerd** [comment]
Well spotted. Will get a fix in for that on sunday

**Comment by olifolkerd** [comment]
Im having issues replicating the bug,

Could you send of a copy of your table constructor object so i can see what settings have been used. also which version of which browser are you using?

Cheers

**Comment by craigcosmo** [comment]
it's the first example of demo page

**Comment by olifolkerd** [comment]
Could you give me a url, as that table only appears on the home page of the website at  http://olifolkerd.github.io/tabulator/ and i cant seem to replicate the fault.

Which browser/version/OS are you using as it may be a specific compatibility issue i need to look into.

**Comment by craigcosmo** [comment]
http://olifolkerd.github.io/tabulator/

system: macos, safari & chrome

**Comment by olifolkerd** [comment]
I have just tried on macOS and i am still not seeing the bug appear when swapping the name and progress columns. which version numbers of safari/chrome are you using? have you tried force refreshing your browser in case something is corrupt?

**Comment by craigcosmo** [comment]
Have u seen the vid? You  can follow the steps in the vid to reproduce.





On Wed, Jul 27, 2016 at 12:41 AM +0700, "Oli Folkerd" <notifications@github.com> wrote:












I have just tried on macOS and i am still not seeing the bug appear when swapping the name and progress columns. which version numbers of safari/chrome are you using? have you tried force refreshing your browser in case something is corrupt?

**Comment by olifolkerd** [comment]
This has now been fixed. Thanks for the video, it was a great help.
