### ISSUE TITLE
Is there any way to have custom footer?

### ISSUE THREAD

**Issue by ryc16** [olifolkerd/tabulator#400]
Hey,

Is there any way to show ie. "Showing 1-10 of 128" on the footer of the table?

Thanks

**Comment by olifolkerd** [comment]
you can use the ***footerElement*** option in the constructor object to add a custom footer to the table:
```js
$("#example-table").tabulator({
    footerElement:$("<div class='tabulator-footer'><button>Custom Button</button></div>"); //set custom table footer with custom button
});
```
You can then use any pf tabulators callbacks to update the contents of it.

Cheers

Oli

**Comment by ryc16** [comment]
Thank you. Instead of counting our own, does tabulator has the options to show "Showing 1-10 of 128" on the footer left?

**Comment by olifolkerd** [comment]
It does not have that falicity built in, you would have to add that yourself. but it would be fairly easy to do as you know the total number of rows, your page size and the current page
