### ISSUE TITLE
 Calculation rows can be selected unexpectedly

### ISSUE THREAD

**Issue by urara4** [olifolkerd/tabulator#4000]
**Describe the bug**
If "selectable" option of table and calc option of column are used together, the calculation row can be selected by clicking unexpectedly.

**Tabulator Info**
5.4.2

**Working Example**
https://codepen.io/urara4/pen/poKveJe

**To Reproduce**
1. Click on the calculation row at the bottom(arround "2").
2. The title checkbox of the rowselection column shows "-" and selected becomes 1;

**Expected behavior**
Calculation row is not selected when clicked.

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: Chrome
 - Version: 106.0.5249.119

**Comment by olifolkerd** [comment]
Hey @urara4 

Thanks for the headsup.

I have pushed a fix for this to master and will include it in this evenings patch release.

Cheers

Oli :)
