### ISSUE TITLE
.updateData is not working

### ISSUE THREAD

**Issue by evanNyew** [olifolkerd/tabulator#4001]
**Describe the bug**
The Updating data API. table.updateData(); is not working properly. I guess it's not picking up the id as it should. When I apply table.updateOrAddData API. All row data with existed id being add a again which cause duplicate data. 

**Tabulator Info**
v5.4.1

**Working Example**
YOU MUST include a link to a JS Fiddle or Codepen that demonstrates the problem, it is very hard to diagnose an issue from a simple description.

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Monterey v12.6
 - Browser safari v16

**Comment by olifolkerd** [comment]
Please create a JS fiddle that demonstrates the issue. 

The function works correctly on my test, without a n example to show how you are using the table it will not be possible to offer advice on how to resolve the issue


Cheers

Oli

**Comment by olifolkerd** [comment]
Closing this issue as no further info provided
