### ISSUE TITLE
Add the ability to add more than one bottomCalc or topCalc row to the table.

### ISSUE THREAD

**Issue by Dasm2k** [olifolkerd/tabulator#4003]
For a shift roster am displaying attendance data in a table. In the bottomCalc i am displaying how much coworkers there are present during the daytime. If  the number reaches below a certain threshold the cell is formatted red to indicate a shortage. To display the number of coworkers that are present during the night shift i now have to clone the table and do a different bottomCalc calculation and display the second table below the first one but with the cells hidden. Doing so it appears as if the table has two calculation rows.

It would be great thow if both calculations could be done in the original table just by adding a bottomCalc2 or bottomCalc3 or use bottomCalc as an array of calculations that have to be performed.

![Calculations](https://user-images.githubusercontent.com/97875862/198852072-c622d3c1-d165-4c96-9869-86210df2f241.png)

**Comment by lstgithub578** [comment]
I agree with this idea and I also want this feature.😊
