### ISSUE TITLE
Placeholder in empty table in Tabulator

### ISSUE THREAD

**Issue by RJR-Robert-Kewei-Zhang** [olifolkerd/tabulator#4004]
Hello,

I am using Tabulator 5.3, I use placeholder for empty table, but I don't want to show vertical scrollbar, can any one tell me how to do that?

Thanks in advance.
Robert

**Comment by olifolkerd** [comment]
Try upgrading to v 5.4, there were some bugs with the placeholder in that release

**Comment by robertkewei** [comment]
Hi @olifolkerd,

Thanks for your reply. I just upgraded from 5.3 to 5.4 (upgraded tabulator.min.js and tabulator.min.css), when I use the placeholder for the empty table, I still can see the vertical scrollbar.  Any ways to remove the vertical scrollbar?

Thanks,
Robert

**Comment by olifolkerd** [comment]
Please post a link to a JS fiddle that shows your table setup

**Comment by robertkewei** [comment]
Hi @olifolkerd,

My code is very simple as below: after user input filter in the head columns, if the filter result is empty, I just want to show a empty table without vertical scrollbar, I am using placeholder and set it to an empty string, but the vertical scrollbar always show up, I try to find a way to hide the vertical scrollbar, but I can't.

Thanks,
Robert
------------------------ code is here ----------------------------------------
var table = new Tabulator("#my-table", {
    height: 300,
    layout: "fitColumns",
    placeholder: "", 
    maxWidth: "100%",
    columns: [
        { title: "Friendly Name", field: "friendlyName", headerFilter: "input", width: 200 },
        { title: "Display Type", field: "displayType", headerFilter: "input", minWidth: 200 },
        { title: "File Name", field: "FileName", headerFilter: "input", width: 200 },
        { title: "File Size", field: "fileSize", headerFilter: "input", width: 100 },
        { title: "File Tags", field: "fileTags", headerFilter: "input", width: 150 }
    ],
});

**Comment by olifolkerd** [comment]
You don't need a placeholder if it has not text. Simply don't set the property

**Comment by robertkewei** [comment]
Hi @olifolkerd,

If I don't use placeholder, when user move to far right and input the filter in the head columns, if the result is empty, the horizontal scrollbar will disappear, and the table was reset to the left side, and user can't reach the far right column to clear the filter. Actually that is the reason I want to use placeholder to solve the issue. Maybe I am in a wrong direction?

Thanks,
Robert

**Comment by Alex-Github-Account** [comment]
you can use this styles as temporary fix

.tabulator-tableholder:has(tabulator-placeholder-contents) {overflow: visible}

**Comment by robertkewei** [comment]
@Alex-Github-Account 

Thanks Alex, it help me a lot.
Robert

**Comment by Alex-Github-Account** [comment]
> @Alex-Github-Account
> 
> Thanks Alex, it help me a lot. Robert

Glad to help. Looks like I have missed a dot in the class name and it should ne
`.tabulator-tableholder:has(**_._**tabulator-placeholder-contents) {overflow: visible}`
I have other fixes, since unfortunately I have integrated tabulator in my app and it turned out tabulator is more of hobby-grade project not suitable for production. I'd reccommend to replace it with react-tables wherever it possible. Unfortunately issues I open there getting closed but I'd be happy to help for anyone asking.

**Comment by Jojoshua** [comment]
Does the latest release with having an empty placeholder callback help? https://tabulator.info/docs/5.5/release#placeholder

**Comment by lehao-212** [comment]
I want to display placeholder when filter data empty. I using placeholderHeaderFilter but not working. you can help me
