### ISSUE TITLE
Typo in code snippet

### ISSUE THREAD

**Issue by Thenafi** [olifolkerd/tabulator#4005]
**Website Page**
[A link where the issue is](https://tabulator.info/docs/5.4/data#ajax-progressive)

**Describe the issue**
In the code snippet, a '//' is missing before the word "enable". As a result, it is not registered as a comment. 
![Screenshot](https://is.gd/5Jb8vC)
The code snippet is in the Getting Started > Loading Data > Progressive Ajax Loading > Load Mode -2nd Snippet.

Another typo in another code snippet. 
**Website Page**
[A link where the issue is](https://tabulator.info/docs/5.4/data#ajax-params)
**Describe the issue** 
In the Real Time Parameters snippet there should be a semicolon instead of comma.  
![This is an image](https://f000.backblazeb2.com/file/ShareX2022/ShareX/chrome_EH7NR3aQAX.png)

**Comment by olifolkerd** [comment]
Thanks for the heads-up,

I will get that fixed in the next site update

Cheers

Oli

**Comment by olifolkerd** [comment]
Those should now be fixed.

Let me know if you find any other issues.

Cheers

Oli :)
