### ISSUE TITLE
Column field containing period doesn't work

### ISSUE THREAD

**Issue by abwterrym** [olifolkerd/tabulator#4007]
**Describe the bug**
I'm replacing an existing ActiveX Object grid with Tabulator in a large intranet application, and thus must use the existing SQL code to populate the tables.  Some of the queries are aliasing the column with column names containing a period, ie:

`select EmplNo as [Empl No.], <etc>`

When this is the case, the grid doesn't display any values in the column.  Removing the period from the field name resolves the issue.

**Tabulator Info**
Version 5.4.2

**Working Example**
https://jsfiddle.net/z583ds6r/1/

**To Reproduce**
The above fiddle shows the issue.  If you remove the period in the line:

`let emplNoField = "Empl No."	// works if you remove the period`

the values display.

**Expected behavior**

For tabulator to work if the field name contains a period.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - Version: 106.0.1370.52

**Comment by olifolkerd** [comment]
https://tabulator.info/docs/5.4/columns#field-nesting
