### ISSUE TITLE
Animation on addRow() ? 

### ISSUE THREAD

**Issue by romanman** [olifolkerd/tabulator#401]
How I add some animation to addRow event: e.g: fadeOut, highlight, etc...

Thanks.

**Comment by olifolkerd** [comment]
Hey,

That depends on what elements you want to animate, i would recommend that you create a CSS class that runs the animation, then use the ***rowAdded*** callback to add the class to the element.

```js
$("#example-table").tabulator({
    rowAdded:function(row){
        //row - row component
        row.getElement().addClass("animation-class");
    },
});
```

Let me know if that helps

Cheers

Oli

**Comment by romanman** [comment]
```row.getElement()```

... I get no `getElement` is exist on row? any idea?

**Comment by romanman** [comment]
ok, found that one: 
```
rowAdded:function(item, row){
```
item was missing from the callback

**Comment by olifolkerd** [comment]
Which version of Tabulator are you using?

as of 3.0 the rowAdded function only receives one argument, a row component that then provides access to all other row, cell and column functions

**Comment by romanman** [comment]
@olifolkerd : got it, thanks.

**Comment by Kwadz** [comment]
Hi,

Do you know if it's possible to add an animation using [`.animate()`](https://api.jquery.com/animate/)?  
I created an [example on JSFiddle](https://jsfiddle.net/rcarree/dv31gmoL/6/), but the animation does not render properly.
