### ISSUE TITLE
selected rows lost when using replace data

### ISSUE THREAD

**Issue by vrecan** [olifolkerd/tabulator#4013]
**Describe the bug**
Selections in tabulator get lost after a call to replaceData even when the new data has the same id's. 

https://jsfiddle.net/mc73yjnw/

After 2 seconds the fiddle calls replace data. If you select something you will see the selection go away after the replace data call. 

**Tabulator Info**
- Which version of Tabulator are you using?
5.4.2

**Working Example**
https://jsfiddle.net/mc73yjnw/

**To Reproduce**
- Once it loads, select a row within the first two seconds
- After 2 seconds the selection will go away because of the replace  data call.

**Expected behavior**
The selection would stay as long as the underline id's match.

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Firefox & Chrome 
 - Version: latest

**Comment by AmolPawar7181** [comment]
Hi @vrecan If you are still interested, please use `table.updateOrAddData` instead of `table.replaceData`
