### ISSUE TITLE
renderVertical: basic breaks datatree toggle on first click

### ISSUE THREAD

**Issue by lekoala** [olifolkerd/tabulator#4015]
**Describe the bug**
when using     renderVertical: 'basic', the datatree toggle doesn't work on first click
you need to click again to make it work, and then the icon is out of sync (- for collapsed, + for expanded)

**Tabulator Info**
5.4.2

**Working Example**
https://codepen.io/lekoalabe/pen/NWzprxV

**To Reproduce**
Click on a datatree toggle. It doesn't work until you try again.

**Expected behavior**
Datatree should work the same regardless of virtual dom being enabled

**Comment by olifolkerd** [comment]
Hey @lekoala 

I have just pushed a fix for this to master and will include it in todays patch release.

Cheers

Oli :)
