### ISSUE TITLE
Date cell editing issue

### ISSUE THREAD

**Issue by adryx92** [olifolkerd/tabulator#4019]
Hello, 

**Describe the bug**
when editing a date cell input with the keyboard, Tabulator triggers the `cellEdited` event before the input is complete. This can lead to inconsistent or wrong dates. 

**Tabulator Info**
I'm using Tabulator 5.4.2.

**Working Example**
I created this pen to demonstrate the issue https://codepen.io/adryx_92/pen/zYadQLJ

**To Reproduce**
Try to edit the date cell using the keyboard: the `cellEdited` is triggered while the user is still editing. With text and number everything is fine.

**Expected behavior**
The `cellEdited` should be triggered after the edit is complete.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Tested on Firefox and Edge

Thank you

**Comment by adryx92** [comment]
After some research, I found out that for `<input type='date'>` fields the `onchange` event is fired as soon as the browser detects a "valid" date in the field.

https://stackoverflow.com/a/60996719/3352304

 This weird behaviour is the root of the problem.

**Comment by olifolkerd** [comment]
Closing this as it has been fixed in the #4112 merge that will be included in todays patch release.

Cheers

Oli :)
