### ISSUE TITLE
No localization for grouped rows

### ISSUE THREAD

**Issue by vasiliyaltunin** [olifolkerd/tabulator#402]
There are no localization for grouped items count, for example 

John Smith (22 **items**)

Cannot be translated, only if i changes it in script.

**Comment by olifolkerd** [comment]
good point, i will have a look into that for the next release

**Comment by olifolkerd** [comment]
Hey,

You will be happy to hear that Tabulator 3.2 has just been released, and with it the ability to localize the ***items*** text:
```js
$("#example-table").tabulator({
    locale:true,
    langs:{
        "en-gb":{
            "groups":{ //copy for the auto generated item count in group header
                "item":"item", //the singluar for item
                "items":"items", //the plural for items
            },
        }
    }
});
```

Full information can be found in the [LocalizationDocumentation](http://olifolkerd.github.io/tabulator/docs/3.2/#localization)

Cheers

Oli
