### ISSUE TITLE
How to add Column Calculations from a pagination call with ajax for Tabulator?

### ISSUE THREAD

**Issue by tungdt91** [olifolkerd/tabulator#4022]
When using loading data from ajax, the Column Calculations functions are no longer correct for remote pagination. So how can I show the calculated data from the server into the footer via an ajax call?

Or is there any other solutions for it?

I'm thinking of assigning the data received from the ajaxResponse callback function, but I can't use the data from this function for Column Calculations custom functions

I have created [a thread on stackoverflow](https://stackoverflow.com/questions/74470030/how-to-add-column-calculations-from-a-pagination-call-with-ajax-for-tabulator).
Looking forward to your support.

Thanks

**Comment by olifolkerd** [comment]
Hey @tungdt91 

If you believe you have found a bug, please use the bug issue template and submit a link to a js fiddle that demonstrates the issue.

Cheers

Oli
