### ISSUE TITLE
Editable Checkbox not working in Safari 15.6.1

### ISSUE THREAD

**Issue by Thallius** [olifolkerd/tabulator#4023]
https://tabulator.info/examples/5.4

Try it on your own example page. You cannot change the checkmark status here

<img width="1808" alt="Bildschirmfoto 2022-11-18 um 14 06 34" src="https://user-images.githubusercontent.com/666946/202712513-c686a673-1b13-499b-8593-63a24b97ec89.png">

**Comment by geospiza-fortis** [comment]
Can confirm that the latest version of tabulator has broken checkboxes on Safari (ios). I think https://github.com/olifolkerd/tabulator/issues/2157 is related.

**Comment by olifolkerd** [comment]
Hey everyone,

I have just pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)
