### ISSUE TITLE
updateDefinition does not update headerFilterPlaceholder

### ISSUE THREAD

**Issue by jaguarxii** [olifolkerd/tabulator#4024]
**Describe the bug**
updateDefinition does not update headerFilterPlaceholder

**Tabulator Info**
5.4.2

**Working Example**
[Sample](https://codepen.io/jaguarito/pen/ZERarNa)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to the sample
2. Click on 'update name column'

**Expected behavior**
the title should change to "new column", this is OK
the placeholder should change to "new placeholder", the placeholder remains unchanged.

**Desktop (please complete the following information):**
 - OS: windows 10 pro
 - Browser waterfox G5.1, chrome latest

**Comment by olifolkerd** [comment]
Hey @jaguarxii 

Thanks for the headsup, i have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)
