### ISSUE TITLE
Export to pdf, html, xlsx is not sorted as a table (range = "all")

### ISSUE THREAD

**Issue by peterprvy** [olifolkerd/tabulator#4025]
**Describe the bug**
Export to pdf, html, xlsx is not sorted as a table

**Tabulator Info**
5.4.2

**Working Example**
https://jsfiddle.net/peterprvy/1nyx8mzs/

**To Reproduce**
1. Go to the sample
2. Click on buttons
3. See saved pdf, html

**Expected behavior**
Function "generateExportList" in class Export should return rows according to the current sorting

**Screenshots**

Table:
![image](https://user-images.githubusercontent.com/36068077/202775900-a157b7eb-9c52-470a-b315-28a17d032494.png)

PDF:
![image](https://user-images.githubusercontent.com/36068077/202775945-f602f3a6-2fbc-4595-a57f-fc923d69479b.png)

**Desktop (please complete the following information):**
 - OS:  Win10
 - Browser: Chome
 - Version: Last  107.0.5304.107

**Comment by peterprvy** [comment]
It might be enough to add another "case" to the Export.rowLookup(range) function:

case "all_active":
    rows = this.table.rowManager.activeRows;
    break;

**Comment by olifolkerd** [comment]
Hey @peterprvy 

Thanks for getting in touch.

This is the correct behaviour, i will explain why below.

The "all" option includes all data, visible or not. it is the unprocessed data in the table. 

When you sort or filter on the table this happens on the "active" set of data, which is all data that is currently filtered into the table, this is done to improve table performance, as there is no point in sorting data that has not passed a filter.

Therefore if you you want to show your sorted data you should be using the `active` option in the export, not the `all` option.

Cheers

Oli :)
