### ISSUE TITLE
A few bug fixes I found while using

### ISSUE THREAD

**Issue by peterprvy** [olifolkerd/tabulator#4026]
Please excuse my English (google translate)

First of all, I would like to thank you for a great plugin.

I found a few errors in it, and made the following corrections. I will describe them as the original version and modified by me with line numbers in the "tabulator_esm.js" module

- class Popup, function constructor,  destroyBinding:
   actual vesion:
![image](https://user-images.githubusercontent.com/36068077/202779070-a8c85fe6-1cff-4edb-8651-ea483249042e.png)
  
   my version:
![image](https://user-images.githubusercontent.com/36068077/202779127-a22b1267-f283-4164-8105-e474a2541f94.png)

- class Edit, function _resolveValue(blur)

    actual version
![image](https://user-images.githubusercontent.com/36068077/202779498-0d553299-e70d-4c4c-ae68-6d1a256ae15f.png)

    my version:
![image](https://user-images.githubusercontent.com/36068077/202779551-24e09289-9082-49c6-a30a-099d6fd7c192.png)

- class Export, function generateRowElement(row, setup, styles)

   setup.rowFormatter(row.component);    is called for each row column, but it should probably only be called once per row

actual version:

![image](https://user-images.githubusercontent.com/36068077/202780093-ef739368-6b80-4bfb-b647-b914b66651df.png)

my version:
![image](https://user-images.githubusercontent.com/36068077/202780197-cd1238a6-29a5-47fe-aa3e-5d2e414c57a8.png)

- class Popup$1, 
   I needed a list of open popups so that I could close them in certain cases, so I added it  
    in function loadPopup(e, component, contents, renderedCallback, position) 
    array of opened popus in table:

![image](https://user-images.githubusercontent.com/36068077/202780961-91d17218-38ea-49c6-a10f-e2caf24eb1ea.png)

**Comment by olifolkerd** [comment]
Hey @peterprvy 

Thanks for the feedback, I have made some changes this time, but feel free to submit any future fixes as PR's

I have implemented several of your proposed fixes:

- The `destroyedBinding` issue, good spot there, i had missed that one
- Export row formatting, very good spot there, that should make things more efficient

The following needed a bit more work:
- the `_resolveValue` fix,  should not be forced to a null, it should be allowed to default to the original initial value if the value is not an array.
- 
Cheers

Oli :)
