### ISSUE TITLE
Sort by multiple columns not work

### ISSUE THREAD

**Issue by peterprvy** [olifolkerd/tabulator#4027]
**Describe the bug**
Sort by multiple columns not work

**Tabulator Info**
5.4.2

**Working Example**
https://jsfiddle.net/peterprvy/8bx2fnhk/12/

**To Reproduce**

1. Go to the sample
2. Inital sort is :

		id, asc
		txt, desc

    but sorting is indescribable

**Expected behavior**
after sorted:

	1  ddddd
	2  ccccc
	3  bbbbb
	4  aaaaa
	4  abbbb
	4  acccc
	4  bbbbb
	4  ccccc

**Screenshots**

data after sorting:

![image](https://user-images.githubusercontent.com/36068077/202856740-9271f482-3a28-486b-bfc9-9ac8a7d6793b.png)

**Desktop (please complete the following information):**
 - OS:  Win10
 - Browser: Chome
 - Version: Last  107.0.5304.107

**Comment by olifolkerd** [comment]
Hey @peterprvy 

That is working correctly, the sort functions are being applied in the order you have specified.

For more details on how sorting works, checkout the "Sort Order" part of the sorting docs:: https://tabulator.info/docs/5.4/sort#overview

Cheers

Oli :)
