### ISSUE TITLE
Merge cells

### ISSUE THREAD

**Issue by nghuuphuoc** [olifolkerd/tabulator#4029]
I want to merge cells in some cases, such as the following screenshot

![Screenshot 2022-11-21 at 12 25 09](https://user-images.githubusercontent.com/4226036/202972122-2b4da949-8aa9-4817-be7d-9cb2ddc923ef.png)

According to this [StackOverflow question](https://stackoverflow.com/questions/61997131/tabulator-cell-span) and issue #2877, the feature should be available in v5, however, I can't find the documentation for it.

**Comment by olifolkerd** [comment]
Hey @nghuuphuoc 

That is not currently a feature, it will probably come in the 6.0 release.

Cheers

Oli :)
