### ISSUE TITLE
Different placeholder for when "no data" and "filter filtered out all the data"

### ISSUE THREAD

**Issue by Alex-Github-Account** [olifolkerd/tabulator#4030]
*Is your feature request related to a problem? Please describe.**
There is only one placeholder parameter available. If we put text like "Table is empty", this placeholder will show up when some filter filtered out all the data, and may confuse user. 

**Describe the solution you'd like**
parameters.allDataFilteredPlaceholder = "No data match current filters"

**Describe alternatives you've considered**
hiding with CSS is walkaround

**Additional context**

**Comment by olifolkerd** [comment]
Hey @Alex-Github-Account 

That is a great idea, i will schedule that for the next minor release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @Alex-Github-Account 

Im reopening this because, i think this a great idea for the library and im using this to track the progress of the addition before the next release version.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
I have now added this feature via the `placeholderHeaderFilter` option.

This has been pushed to the 5.5 branch and will be included in todays release.

Cheers

Oli :)
