### ISSUE TITLE
Cannot paste into masked editors

### ISSUE THREAD

**Issue by JPM72** [olifolkerd/tabulator#4031]
**Describe the bug**
i cant paste valid input into a masked input column

**Tabulator Info**
- Which version of Tabulator are you using?
5.4.2

**Working Example**
https://jsfiddle.net/a0z71r6n/

**To Reproduce**
Try pasting `1234` into the Example column

**Expected behavior**
1234 appearing in the cell

Tested on Windows 10 / Firefox

Edit: copying from the input element (while it is focused and selected) is also blocked.

**Comment by olifolkerd** [comment]
Hey @JPM72 

Thanks for the headsup, I have pushed a fix to master to allow command actions through the mask. I will include that in the next patch release next week.

I will need to add an additional set of functionality to validate the pasted strings as the mask system is currently only set to handle things one character at a time, but i will add this in the next feature release as i want to add an optional param to handle this action.

Cheers

Oli :)
