### ISSUE TITLE
Minor typo: Manuipulate Columns

### ISSUE THREAD

**Issue by bcazur** [olifolkerd/tabulator#4032]
**Website Page**
[Columns manipulation](https://tabulator.info/docs/5.4/columns#manipulation)

**Describe the issue**
**Manuipulate** Columns -> Should be **Manipulate** Columns

**Comment by olifolkerd** [comment]
Hey @bcazur 

Thanks for the headsup, i have just pushed a fix for the typo, let me know if you find any more.

Cheers

Oli :)
