### ISSUE TITLE
When field has an "accessor" set up, a filter applied seems to ignore accessor and filters using raw data instead

### ISSUE THREAD

**Issue by Alex-Github-Account** [olifolkerd/tabulator#4036]
lets have a field samplefield with accessor:somefunctionname set up
then we do tabulator.addFilter(someFilterForSamplefield)
the Tabulator will apply filter agains "raw" data, accessor function not getting called.
lets say one have a column full of ID's and accessor that transforms IDs to corresponding human names,
then user typed "jo" and filter got added 
**expectation**: 
column will have only cells containing "jo" left (like John, Josheph, Joker)
**reality**:
filter will be useless since it would filter by ID, which is number, not human name.
Or am I getting it wrong?

**Comment by olifolkerd** [comment]
This is the correct, accessors are used to change data as it leaves the table.

If you want to change the data as it comes into the table you need to use a mutator
