### ISSUE TITLE
Placeholder not shows up when there is no data left due to filter applied

### ISSUE THREAD

**Issue by Alex-Github-Account** [olifolkerd/tabulator#4037]
Tabulator deeply integrated into the project, but nothing extraordinary 
What information I need to provide for you to have insights on why this bug is happening?
Currently I solve it by detecting empty ".tabulator-table" tag and injecting placeholder HTML into there but this is uncool solution
I know JS and can go throught code execution with debugger, but don't know where to look at inside tabulator code.
No errors thrown into console, and behavior does not fixes itself on clearing and re-adding the filters
However, when react re-draws the component containing tabulator, the placeholder instantly shows up (and if I had my injected placeholder, here would be 2 placeholders now) 
.redraw(true) did not helps

**Comment by Alex-Github-Account** [comment]
Looks like no interest to this bug. For everyone here from google, here is ugly temporary solution:
```
            var tableContent = tableDOMElement.current.getElementsByClassName('tabulator-table')[0]
            var existingPlaceholder = tableDOMElement.current.getElementsByClassName('tabulator-placeholder')[0]
            if (existingPlaceholder || !tableContent || tableContent?.children?.length > 0) {
                return
            }
            tableContent.innerHTML = '<div class="tabulator-placeholder" tabulator-render-mode="basic" ><div class="tabulator-placeholder-contents"  >' 
                + (tabulator?.options?.placeholder || 'no data') 
                +'</div></div>'

```

**Comment by olifolkerd** [comment]
Hey @Alex-Github-Account 

You only raised the bug 4days ago. It isn't that there is no interest. Just that we haven't got round to looking at it yet.

This is a free open source project, you need to be realistic in your expectations for when things will be actioned. We all have things going on outside Tabulator and will respond when practical.

There will be a patch release in early December and it will get reviewed then

Cheers

Oli

**Comment by Alex-Github-Account** [comment]
here is the very same bug formatted with your beloved issue template https://github.com/olifolkerd/tabulator/issues/3997
is has no comments or attention 
so please answer:
what the point of formatting with issue template if it changes nothing? 
Listen, I create issues for people who lands there from google, and unlike you, I do actually provide help and fixes/walkaround for people to use. Currently only one issue I found is without solution from me (headers lag) since issue root are deep into the weird way tabulator is built (separate headers with no OPTION to have them as first row). I made an frmatter that sets first row as a header to walkaround this but it is not solution I'd reccommed.
