### ISSUE TITLE
Header lags on horizontal scrolling on mobile devices

### ISSUE THREAD

**Issue by Alex-Github-Account** [olifolkerd/tabulator#4041]
When scrolling horizontally on mobile devices (iphone, android), header moves with noticeable lag behind the table contents.
The table size is very small (about 10 rows and less than 10 columns) and it happens with both virtual dom and regular dom
Currently I have no solution for this, since for some reason headers are separated from content and there is no div with display: grid or display: table can be used to make header actually attached to content.

**Comment by olifolkerd** [comment]
Hey @Alex-Github-Account 

as per issue #4039 please can you raise issues with the bug template.

While i'm happy that you have a solution that works for you and your usage case. you proposed solution will not work for the table in general

The reasons for keeping them separate are complex and revolve around the different scroll bar usage cases and a number of complex interactions between the modules that necessitate the header functionality being isolated from the body.

At the moment this lag is only noticeable on some mobile devices and is not present on desktop. While i am aware of it, and am tracking it in the general performance updates,  it has no affect on the usability of the table and is only a transient visual glitch during scroll animation so at this point it is very low down the priority list.

Thanks for your feedback

Cheers

Oli :)

**Comment by Alex-Github-Account** [comment]
> Hey @Alex-Github-Account
> 
> as per issue #4039 please can you raise issues with the bug template.
> 
> While i'm happy that you have a solution that works for you and your usage case. you proposed solution will not work for the table in general
> 
> The reasons for keeping them separate are complex and revolve around the different scroll bar usage cases and a number of complex interactions between the modules that necessitate the header functionality being isolated from the body.
> 
> At the moment this lag is only noticeable on some mobile devices and is not present on desktop. While i am aware of it, and am tracking it in the general performance updates, it has no affect on the usability of the table and is only a transient visual glitch during scroll animation so at this point it is very low down the priority list.
> 
> Thanks for your feedback
> 
> Cheers
> 
> Oli :)

Odd. I literally wrote "Currently **I have no solution** for this" then you misread it as if I have some solution and more of it, stated that it is bad/unsuitable? 
Which solution, dear? When I said I have **no solution**, it means I have **no solution**. Did you got used so much to fact that I provide fix for every bug issue I open, that you just assumed I have solution for this? and fantasied that it is not suitable?
