### ISSUE TITLE
responsiveLayout:"collapse" prevents usage of column formatter

### ISSUE THREAD

**Issue by Alex-Github-Account** [olifolkerd/tabulator#4042]
if responsiveLayout:"collapse" is set, then 'collapsed' columns will have raw, unformatted value.
When window resized that way that columns are not collapsed anymore, then formatted value will be shown.

**Comment by olifolkerd** [comment]
Hey.

If you want to report a bug then please use the bug template and provide a js fiddle. Without seeing how your table is configured it is not possible to help you out.

The responsive collapse system is in related to the formatters so it is likely there is a misconfiguration in your table. If you can link to a fiddle we can help you out futher

**Comment by Alex-Github-Account** [comment]
You missed: I have provided the configuration literally in first words
`responsiveLayout:"collapse"`
thats it. With that configuration (hint: consisting of 1 (one) item) the effect described starts to appear - no formatters applied. should I provide all formatters theoretically possible? :D.
