### ISSUE TITLE
Need possibility to scroll to row by field name and value

### ISSUE THREAD

**Issue by Thallius** [olifolkerd/tabulator#4043]
Hi,

standard behavior:

You scroll to a row in the table. You click on the row and the entry is edited in an upcoming edit window. When the edit window is closed, the tabulator data must be completely refreshed because other rows could have been affected by the edit also.
After the setData() the table is always scrolled to top but I need to scroll back to the edited row (Which could be on another index of course)
I have tried to use the old rowComponent which was clicked before setData(), but that doesn't work (Which I have guessed as this Component no longer exists after setData())

**Comment by olifolkerd** [comment]
You should use the replaceData function . This replaces the data and maintains scroll position
