### ISSUE TITLE
Memory leak in .destroy()

### ISSUE THREAD

**Issue by antman3351** [olifolkerd/tabulator#4044]
Hi Oli,

When calling `table.destroy()` memory isn't freed. 

The first issue is Print.js doesn't remove the event listeners attached to the window, so the garbage collector doesn't remove the table instance.

The second is `destroy()` doesn't empty the `activeRowsPipeline` array, so if a reference to the table is still being held after calling `destroy` memory is still being occupied.

![Tabulator-memory-leak](https://user-images.githubusercontent.com/16060462/204791102-8c645435-235b-4fd6-a8ff-d75676441895.png)

**Tabulator Info**
5.4.2

**To Reproduce**
1. Instance the table
2. load a lot of data
3. call table.destroy()

**Comment by olifolkerd** [comment]
Hey @antman3351 

Thanks for getting in touch, and thanks for the PR, it is always fantastic when people want to help with improving the Table.

I will review the PR this weekend and get back to you.

Thanks again for your contribution.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @antman3351 

I have merged this into master and will include it in this evenings patch release.

Cheers

Oli :)

**Comment by antman3351** [comment]
Hi @olifolkerd 

I'm glad I could help :)

Thanks for your constant work on Tabulator!
