### ISSUE TITLE
updateData might never resolve

### ISSUE THREAD

**Issue by s-cork** [olifolkerd/tabulator#4050]
**Describe the bug**
calling `table.updateData([{}])` will never resolve/reject
This would happen with an array of invalid data that can't be updated.

**Tabulator Info**
5.4

**Working Example**
https://codepen.io/s-cork/pen/oNyaQvr

```js
table.updateData([{}]).then(
    () => {alert("done")},
    (e) => {alert("fail")}
)
```

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to 'https://codepen.io/s-cork/pen/oNyaQvr
2. observe the alert never fires

**Expected behavior**
I'd expect the call to updateData to resolve or reject

**Additional context**
My use case wraps the Tabulator Module so whilst I can be careful that this works
My users aren't so careful and one got quite confused when their next line of code never fired

**Comment by olifolkerd** [comment]
Hey @s-cork 

Thanks for the headsup, i have pushed a fix to master and will include it in this evenings patch release.

Cheers

Oli :)
