### ISSUE TITLE
Adding Row Adds 2 Rows and Gives Error When Deleting

### ISSUE THREAD

**Issue by atebeta** [olifolkerd/tabulator#4052]
**Describe the bug**
I add a row via keyboard shortcut 'ctrl+i' and 2 identical rows are added. Subsequently when trying to delete this row via a keyboard shortcut 'ctrl+,'  there is an error

**Tabulator Info**
- Which version of Tabulator are you using? 5.4.3

**Working Example**
https://jsfiddle.net/atebeta/eysmqoz8/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Click on the 'Name' header filter
2. Insert a row by using keyboard shortcut Ctrl+i
3. Can see the group header say 2 items even though just 1 row should be added
4. Delete the row by using keyboard shortcut Ctrl+, (make sure a cell in the row has an open editor)
5. Can see the group header still say 1 item and the Uncaught TypeError: Cannot read properties of undefined (reading 'add') in the console

**Expected behavior**
Add 1 row and delete 1 row without error.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Brave/Chrome

**Additional context**
Problem was not there on version 5.4.2

**Comment by atebeta** [comment]
Seems Type error when deleting a row only occurs when the data is grouped. Also the error can be reproduced even after deleting the row by expanding and minimising the group.

**Comment by olifolkerd** [comment]
Hey @atebeta 

I have pushed a fix for this to the master branch and will include it in the next patch release.

Just a quick headsup for next time, can you make sure you example is very simple code, it should only demonstrate the issue, not have loads of other code that makes it hard to see the wood from the trees.

Checkout the community docs for more info: https://tabulator.info/community/mre

Cheers

Oli :)

**Comment by atebeta** [comment]
Hi @olifolkerd sure will do, I just reused a previous jsfiddle to show the error, will clean it up next time.
