### ISSUE TITLE
ColumnManager.scrollToColumn not resolving Promise

### ISSUE THREAD

**Issue by abwterrym** [olifolkerd/tabulator#4053]
**Describe the bug**
When the ColumnManager.scrollToColumn() function is called with the ifVisible (third) argument false, the code may execute a "return false" statement (at line 3144 in the 5.4.2 version of tabulator.js).  Since this is inside a new Promise object, this line should be doing "resolve(false)" rather than "return false".

**Tabulator Info**
5.4.2

**Working Example**
https://jsfiddle.net/947oc8qt/5/

**To Reproduce**
Execute the above jsFiddler with the console window displayed

**Expected behavior**
The code does two calls to scrollToColumn, one with isVisible = true and one with isVisible = false, and writes to the console after each.  Expect to see both console messages, but only see the first because the returned Promise when isVisible == false is never resolved due to missing "resolve" statement.

**Additional context**
I changed my copy of tabulator.js ver 5.4.2, changing line 3144 to "resolve(false)" and this fixed the issue.

**Comment by olifolkerd** [comment]
Hey @abwterrym 

You shouldn't be accessing the internal functionality of the table. the ColumnManager is not for external use, atempting to manipulate it in such a way will result in unpredictable behaviour.

To scroll to a column use the `scrollToColumn` function directly on the table object:
https://tabulator.info/docs/5.4/navigation#scroll-column

Or the `scrollTo` function on a column component:
https://tabulator.info/docs/5.4/components#component-column

Cheers

Oli :)
