### ISSUE TITLE
onRendered callback shifts focus to header filter when changed programmatically

### ISSUE THREAD

**Issue by atebeta** [olifolkerd/tabulator#4054]
*Is your feature request related to a problem? Please describe.**
I have a header filter "A" which will amend header filter "B" depending if "A" is empty or not. Problem now is that with the onRendered callback being triggered on the header filter editor "B" the focus is moving to header filter "B" automatically

**Describe the solution you'd like**
Would like the focus not to shift to the header filter that was changed programmatically.

**Describe alternatives you've considered**
I have created a custom editor which adds a guard clause on the onRendered callback which exits if the input is a child of the header-filter class. This works, but would be nice to not have to use a custom editor.

**Comment by travisbhartwell** [comment]
@atebeta I am also seeing this issue; I'm new to using Tabulator. Do you have an example of what you had to do to work around this?

**Comment by hiljusti** [comment]
Is the current behavior that the last-touched filter gets focus?

If so, can you do something like make some kind of no-op change to the "Filter A"?

```
filterA = filterA;
```

**Comment by olifolkerd** [comment]
Hey all,

This was a regression in the last patch release.

I have just pushed a fix for this to master and will include it in the next patch release in a few days.

Cheers

Oli :)
