### ISSUE TITLE
debugInvalidOptions option doesn't work for 5.4.2 version

### ISSUE THREAD

**Issue by di-shu** [olifolkerd/tabulator#4057]
**Describe the bug**
debugInvalidOptions option doesn't work for 5.4.2 version

**Tabulator Info**
- 5.4.2

**To Reproduce**
1. Provide ```debugInvalidOptions: false``` to options
2. Warnings are shown in console.

**Expected behavior**
Provided option works.

**Screenshots**

**Comment by olifolkerd** [comment]
@di-shu could you provide a like to a fiddle that demos your setup. What custom options are you using?

**Comment by STsaruk** [comment]
> @di-shu could you provide a like to a fiddle that demos your setup. What custom options are you using?

I prepared an example 

https://codesandbox.io/s/ecstatic-kilby-1hkm9n?file=/src/components/HelloWorld.vue

Here I specified the `debugInvalidOptions: false`

<img width="968" alt="CleanShot 2022-12-08 at 09 08 26@2x" src="https://user-images.githubusercontent.com/17137906/206381656-f10501ce-218c-40c0-a714-91ee5ee7cb33.png">

There are unknown properties in the columns and warning still here:

![CleanShot 2022-12-08 at 09 06 23@2x](https://user-images.githubusercontent.com/17137906/206381354-7dfaef53-89fc-4305-aa8f-2be73f324bd0.png)

**Comment by olifolkerd** [comment]
Ahh you are setting it in the column definition.

That option is primarily intended to suppress custom options on the table itself not the columns, but I can certainly extend it to cover the column definitions, that makes a lot of sense.

Thanks for the example that is a bit help

**Comment by STsaruk** [comment]
Thank you, you'll help us a lot, as we really need the extra fields in the column for additional actions

**Comment by STsaruk** [comment]
Hey @olifolkerd, are there any changes on this issue yet?

**Comment by olifolkerd** [comment]
Nope, I've taken a few weeks off from Tabulating for Xmas.

Will pick up things in the new year :)

Merry xmas

**Comment by STsaruk** [comment]
Please let me know when you're done) Thanks in advance 

Merry Christmas 🎄

**Comment by olifolkerd** [comment]
Hey @STsaruk 

I have pushed a fix for this to the master branch and will include it in this weekends patch release.

Cheers

Oli :)
