### ISSUE TITLE
height: "100%" behaviour changes on 5.4.0

### ISSUE THREAD

**Issue by glutamate** [olifolkerd/tabulator#4058]
**Describe the bug**

When a a tabulator is initialised with `height: "100%"` (as advised in [docs](https://tabulator.info/docs/5.4/layout#height-fixed)) the result is very counterintuitive on the transition from 5.3.4 to 5.4.0. Only a subset of the rows are displayed, there is a scrollbar but on scrolling down no rows are displayed

The issue only appears on certain screen widths, limit of which is determined by the number and content of columns. It is the width on the initial page load that matters, resizing the window on a loaded page doesn't make any difference.

Removing  `height: "100%"` seems to improve so that is my work around for the moment.

**Tabulator Info**

This issue is present on all versions 5.4.0 - 5.4.3. Not present on 5.3.4

**Working Example**

[https://jsfiddle.net/glutamate/crpy8v36/7/](https://jsfiddle.net/glutamate/crpy8v36/7/)

**To Reproduce**

This only to be an issue on narrower screen widths. You need to resize the windows in the fiddle so the output (the white panel) is ~ 630px and and then reload the fiddle. Scroll down and stare into the void. 60 rows should be displayed but only about 20 are shown

**Expected behavior**

Not sure but whatever is happening doesn't look right! Before 5.4.0 this would display all rows as expected

**Screenshots**

![Screenshot 2022-12-08 at 15 19 14](https://user-images.githubusercontent.com/43804/206484125-0a51c164-491a-4124-bff6-559449931335.png)

**Desktop (please complete the following information):**

Chrome, on macOS

**Additional context**

It's possible that the fix to this issue is just in changing the docs and adding to the 5.4 upgrade guide.

**Comment by olifolkerd** [comment]
Hey @glutamate 

The issue here is that your parent element has no height set on it so there is no way for the DOM to calculate 100% of what, if you want to use percentage height then at least one parent must have  a height.

If you set the following on your fiddle to define the max height then you will see it works as expected:
```css
body,html {
  height:100%;
}
```

Cheers

Oli :)
