### ISSUE TITLE
call to row.reformat() in cellEdited event is producing error and focus is lost

### ISSUE THREAD

**Issue by sogrbilja** [olifolkerd/tabulator#4059]
**Describe the bug**
I need to call row.reformat() somewhere, I was told that cellEdited event is the best place to do it, but it doesn't work!

**Tabulator Info**
5.4.0

**Working Example**
https://jsfiddle.net/cr64fpds/7/

**To Reproduce**
1. just edit any cell and hit TAB focus will not go to another cell, instead, you will get an error in the console

**Expected behavior**
In this example, if you change progress to > 70 then the row should be colored red, and the focus should navigate to the next cell. But the focus is lost and the error in the console is shown.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: windows
 - OS: windows 11
 - Browser: Firefox 
 - Version: 107.0.1

**Additional context**

**Comment by olifolkerd** [comment]
Hey @sogrbilja 

Yes this is the correct behaviour, by trying to reformat the row you are asking the table to redraw the row, therefor the cell that has just gained focus is destroyed and recreated, thus focus is lost.

If you want to maintain focus, you would need to get the current editing cell, store is column field name then when the reformat is finished use the `getCell` function on the row with that field value and call the `edit` function on it to restore the edit.

Cheers

Oli :)
