### ISSUE TITLE
Types inconsistent for cell getting methods

### ISSUE THREAD

**Issue by br3nd4nn34l** [olifolkerd/tabulator#406]
![image](https://user-images.githubusercontent.com/22160828/27542535-856fba8a-5a55-11e7-85aa-50884589442d.png)

Documentation says that getRow -> getCell should return a CellComponent object, and getRow -> getCells should return a collection of CellComponent objects. However, only getCells seems to be returning a collection of CellComponent objects.

**Comment by olifolkerd** [comment]
Good Spot!

That was mistakenly returning one of Tabulators internal objects instead of the correct cell component.

I have just pushed an update to the master branch to fix this.

I will be officially released in next months 3.2 release.

Thanks for letting me know.

Cheers

Oli
