### ISSUE TITLE
Formatter "rownum"  with pagination on follows number of records per page

### ISSUE THREAD

**Issue by qbroker** [olifolkerd/tabulator#4060]
**Describe the bug**
Prior to version 5.3.0 the formatter "rownum" and pagination option set would number the rows from 1 to number of rows.
Since version 5.3.0 the numbering follows the pagination, every page starts with 1 to max number set in pagination option.
>= 5.3.0 pagination set to 10, rownums on page 1: [1,2,3,4,5,6,7,8,9,10], page 2: [1,2,3,4,5,6,7,8,9,10] etc.
< 5.3.0 pagination set to 10, rownums on page 1: [1,2,3,4,5,6,7,8,9,10], page 2: [11,12,13,14,15,16,17,18,19,20] etc.

**Tabulator Info**
- 5.3.0 to 5.4.3?

**Expected behavior**
Formatter "rownum" is expected to number from 1 to last record number in all use cases.

**Desktop (please complete the following information):**
 - OS: Linux and NW.js
 - Browser Firefox 105

Have a nice day, Okido

**Comment by olifolkerd** [comment]
Hey @qbroker 

This is because the nature of row numbers changed in this release. they now refer to the visual position of the row in visible table data, with the pagination system, the visible rows are only the current page so the numbers are the same on each page.

Cheers

Oli :)

**Comment by ferulisses** [comment]
Hi,

I made an custom function that calculates the row number, hope that this help someone:
```
    var calculateRowNumber = function(cell, formatterParams, onRendered){
        let startRecord = 0;
        # when using server side, need calculation
        if (this.table.getAjaxUrl()) {  
            startRecord = (this.table.getPage() - 1) * this.table.getPageSize();
        }
        return this.table.rowManager.activeRows.indexOf(cell.getRow()._getSelf()) + 1 + startRecord;
    }
```

Declare column as follow:
```
{
    formatter: calculateRowNumber,
    title: "#",
    hozAlign: "center",
    sorter: false,
    headerSort: false
}
```
