### ISSUE TITLE
Add horizontal scrolling on header from mouse wheel

### ISSUE THREAD

**Issue by python3Berg** [olifolkerd/tabulator#4061]
*Is your feature request related to a problem? Please describe.**
My app uses frozen rows to summarize the data below. The number of columns often exceed screen space. It would be nice if horizontal scroll wheel over frozen worked the same as over data.

**Describe the solution you'd like**
Seemless scrolling horizontally wherever overflow-x

**Describe alternatives you've considered**
IN 4.9 used Hamster to listen to scrolling and apply to frozen-rows-holder and tableholder. Hoping to eliminate extraneous packages.

**Additional context**
Thanks

**Comment by olifolkerd** [comment]
Hey @python3Berg 

I am unsure what you are refering to here, frozen rows scroll as the columns are scrolled.

Do you have an example of the issue you are describing?

If you are asking for an additional scroll bar just for the frozen rows then i think that would make for a very confusing UI.

Cheers

Oli :)

**Comment by python3Berg** [comment]
See [](https://jsfiddle.net/vp5Lf27j/)
My expectation is when mouse is hovering over frozen top row, the table will scroll horizontally the same as if the mouse were hovering over non frozen row.

**Comment by python3Berg** [comment]
https://jsfiddle.net/vp5Lf27j/

**Comment by olifolkerd** [comment]
Hey @python3Berg 

thanks for the fiddle that was very helpful, im assuming your are referring to having a horizontal scroll wheel in this instance.

It isnt actually the frozen row specifically but the whole header that this dosnt apply to.

I will add this to the list to have a look into, but i will be honest with you that this is a fairly niche issue and so will be fairly low down the priority list. If you need it soon i would suggest submitting a PR

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @python3Berg 

I have pushed the update for this to the 5.5 branch and will include it in marches feature release.

Cheers

Oli :)
