### ISSUE TITLE
rowSelectionChanged  triggering on initializing table

### ISSUE THREAD

**Issue by AzarJahrom** [olifolkerd/tabulator#4065]
Hello
I'm using Tabulator version 5.3.
The `rowSelectionChanged` event triggering  when table initializing and not yet rendered compeletely. I think it should be triggered just when user click on the row or when user clicking on the checkbox (in check box selection mode).

The parameters passing to the function are :
data: [],
rows: []

**Comment by olifolkerd** [comment]
Hey @AzarJahrom 

Thanks for the headsup,

I have pushed a fix for this to the master branch and will include it in this weekends patch release.

Cheers

Oli :)
