### ISSUE TITLE
Does not work with Svelte

### ISSUE THREAD

**Issue by ethanfox** [olifolkerd/tabulator#4067]
I've copied and pasted all of the examples on the website from the Svelte section and nothing shows up.

**Comment by olifolkerd** [comment]
Hey @ethanfox 

If you are having issues, could i ask that you use the bug issue template, it will help you include all the info we need to help you.

Without as JS Fiddle or similar to see how you have things setup,  it is hard to offer any feedback to assist in getting you up and running.

I must admit, im not a svelt developer myself, the guide for that is provided by members of the community. If you feel it can be improved, feel free to post an updated example snippet here and i can look into updating it on the docs site.

Cheers

Oli :)
