### ISSUE TITLE
Grouping by Number Blocks/ranges

### ISSUE THREAD

**Issue by xola123** [olifolkerd/tabulator#4068]
*Is your feature request related to a problem? Please describe.**
Grouping is not possible for number blocks. I would like to have the ability to group by, let's say, numbers from 0-49, 50-99, 100-149 and so on. This comes in handy if you have a good amount of numbers in your source (which do not necessarily need to be in order).

**Describe the solution you'd like**
Something like:
```
...
groupBy: "t_number",
groupParams: {
    method: "numberblock",
    range: 50,
    hideNaN: true
}
...
```

**Describe alternatives you've considered**
Displaying hundreds of Tabulator Tables, all having only 50 values in it. Not really applicable.

**Additional context**
Already asked my question on Stackoverflow: [here](https://stackoverflow.com/questions/74824663/possible-to-group-rows-by-number-range)

**Comment by olifolkerd** [comment]
@xola123 

You can group by anything you like, if you pass a callback function to the `groupBy` function, you can then define custom logic for the grouping.

Cheers

Oli :)

**Comment by xola123** [comment]
Okay thank you for the hint. But unfortunately, this is not well documented, so it took some time for me to learn how that grouping works.
