### ISSUE TITLE
Persistence: paginationInitialPage and column visibility are not recalled

### ISSUE THREAD

**Issue by MetallianFR68** [olifolkerd/tabulator#4073]
I'm using Tabulator 5.3.4

I declare columns with only fields, and title. Nothing else.

`{ field: 'city_name', title: 'Ville' },`

I set the following options at initialization :

`persistence: true,
persistenceMode: 'local',
persistenceID: 'test',
persistence: true`

**paginationInitialPage** is stored in the LocalStorage but the table always restarts at page 1 and the LocalStorage is then updated at 1

If I hide a column using toggle() I can see the LocalStorage beeing updated with visible:false but everytime I restart, the column is visible and the LocalStorage is reset to visible: true

Every other persistence option are recalled well (column order, filters, sort)

I think this may be related to the fact I'm using remote sort, filter and pagination with a ajaxRequestFunc

`sortMode: 'remote',
filterMode: "remote",
paginationMode: 'remote',`

Everything else is working very well

Sorry I can't add a CodePen demo since this is affecting remote Ajax Calls

**Comment by olifolkerd** [comment]
Please post a link to a JS fiddle that demonstrates your issues without seeing how the table is fully setup it is hard to offer advice on the issue

**Comment by MetallianFR68** [comment]
Hi

Here a JSFIDDLE : 
https://jsfiddle.net/MetallianFR68/ngxvhdtb/42/

I think i figured out the problem with the column **visibility**.
`visible:true` has to be set in the column definition at initialization, otherwise tabulator can't track the changes.

About **paginationInitialPage **, I just figured out by creating the JSFIDDLE that it works if I set the path with `ajaxURL: myurl` before initialization.

I was initializing tabulator first and then :
`tabulator.on('tableBuilt', () => tabulator.setData(myurl))`

As you can see in the jsfiddle, if the url is set after initialization with setData, paginationInitialPage is ignored and overwritten

If you don't consider this a bug, you can close this report

Thanks and Merry Christmas !

**Comment by olifolkerd** [comment]
Hey @MetallianFR68 

Thanks for the detailed reply,

Yes you have correctly figured out the issue there, it needs the prop set to track it, i would say this is more down to your edge case usage than a bug so i will leave it for now, but do let me know if you have any other issues.

Cheers

Oli :)
