### ISSUE TITLE
Issue with progressiveLoad scroll when height set to 100%

### ISSUE THREAD

**Issue by edwbaker** [olifolkerd/tabulator#4075]
**Website Page**
[A link to the page with the issue](https://tabulator.info/docs/5.4/data#ajax-progressive)

**Describe the issue**
On a table with height set to 100% the progressiveLoad when set to scroll continuously loaded additional rows, which was solved by giving a height in px. It might be good to document this as continuously loading data may cause performance issues.

**Comment by olifolkerd** [comment]
This will be because you have not set a height on the parent container so the element will continue to grow indefinitely
