### ISSUE TITLE
Moving moved row back to original table: removeEventListener is not a function

### ISSUE THREAD

**Issue by JacobGralinski** [olifolkerd/tabulator#4076]
**Describe the bug**
When moving a row from one table to another, and then moving that same row back to the original table, an error occurs in the console for "removeEventListener is not a function"

**Tabulator Info**
- Version 5.4.3

**Working Example**
https://jsfiddle.net/jacobgralinski/o4n8k36s/16/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://jsfiddle.net/jacobgralinski/o4n8k36s/16/
2. Select any row from the "Available Statuses" table and drag it to the "Applied Statuses" table.
3. Once moved, select the row that was just moved and drag it back to the "Available Statuses" table.
4. In the Chrome console, there should be an "Uncaught TypeError" for "e.getElement().removeEventListener is not a function"

**Expected behavior**
If a row is moved from one table to another, it is expected that I can move that row back to the original table in the same manner.

**Screenshots**
![image](https://user-images.githubusercontent.com/32072855/210114380-5404a2e4-2227-4c64-81fd-6cb27b6d87b5.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 108.0.5359.125

**Additional context**
**The issue does not appear to happen in version 5.4.2**

The row will reappear in the original table, but a clone will still be hovering over with the mouse. If you click in the table with that row, a second identical row will be added back to the table, and that data row can then be duplicated back and forth

![image](https://user-images.githubusercontent.com/32072855/210114744-75b6ca7e-c527-4d78-b784-fc4a01f47d10.png)

**Comment by olifolkerd** [comment]
Hey @JacobGralinski 

I have pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)
