### ISSUE TITLE
Update Grouping after table created

### ISSUE THREAD

**Issue by vasiliyaltunin** [olifolkerd/tabulator#408]
I think there must be a way to update Group after table initialized, for example to use different grouping on click buttons or when data changes.

I know there are `groupBy:function(data)` but i dont think it usable in my case.

**Comment by olifolkerd** [comment]
Hey,

There is no way to update that at the moment, but that feature will be coming in the 3.2 release next month.

Could you explain your usage case and i will see if i can propose a suitable solution for you.

Cheers

Oli

**Comment by vasiliyaltunin** [comment]
Well I have a table and i want to regroup it on different columns or remove grouping when button clicked.

For now i just pass field name when object first created, but in future i want to allow to user decide which grouping to use or not use it at all.

**Comment by olifolkerd** [comment]
Are you looking to do this with a select box, or a series of buttons?

**Comment by vasiliyaltunin** [comment]
Buttons outside of table will be just fine.

**Comment by olifolkerd** [comment]
Hey,

You will be happy to hear that Tabulator 3.2 has just been released, and with it the new grouping structure functions (***setGroupBy***, ***setGroupStartOpen***, ***setGroupHeader***) that let you change the group structure after the table is created :
```js
$("#example-table").tabulator("setGroupBy", "gender");
```

Full information can be found in the [Grouping Documentation](http://olifolkerd.github.io/tabulator/docs/3.2/#grouping)

Cheers

Oli
