### ISSUE TITLE
Table is scrolling on adding rows if horizontal scrollbar exists. 

### ISSUE THREAD

**Issue by McAronDev** [olifolkerd/tabulator#4081]
**Describe the bug**
When adding new row scroll position, moves up. I found that it is because horizontal scrollbar adjustment does not work (if condition is always false).

https://github.com/olifolkerd/tabulator/blob/9c8c72f2815243e167760383e903918323d285bd/src/js/core/rendering/renderers/VirtualDomVertical.js#L319-L323

if i change offsetWidth to clientWidth it works fine.

**Tabulator Info**
- Tabulator v5.4.3

**Working Example**
https://jsfiddle.net/qx8530s2/

**To Reproduce**
1. Open JS Fiddle =)

**Expected behavior**
Scroll position should persist.

**Desktop (please complete the following information):**
 - OS: Win 11
 - Chrome 108

**Comment by olifolkerd** [comment]
Hey @McAronDev 

Thanks for the headsup and the proposed fix.

I have pushed an update to the master branch and will include it in todays patch release.

Cheers

Oli :)
