### ISSUE TITLE
[Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive

### ISSUE THREAD

**Issue by dohoangtung** [olifolkerd/tabulator#4082]
**Describe the bug**
Chrome Violation Warning

**Tabulator Info**
5.4.3

**Working Example**
https://tabulator.info/examples/5.4#movable

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1.  Setup table with moveable row with handle like in example
2. Try to scroll up/dowm
3. See console log warning

**Expected behavior**
No Violation message

**Screenshots**
![image](https://user-images.githubusercontent.com/40049759/210927312-d07ce8c7-a55f-4582-9c66-d6053a51e0e7.png)

**Comment by olifolkerd** [comment]
Hey @dohoangtung 

This is not an issue, in this particular case the listener is running passive, but there is logic in there that in different circumstances means this is a non passive listener, and as such it cannot be marked as passive. 

This can warning be safely ignored

Cheers

Oli :)
