### ISSUE TITLE
Rows added to top of table lose "striped" formatting

### ISSUE THREAD

**Issue by python3Berg** [olifolkerd/tabulator#4083]
**Describe the bug**
Bug fix released 12/4 fixes add row positioning. However, the fix introduces new issue wrt row formatting. Upon adding >1 rows, the table will lose track of tabulator-row-even vs tabulator-row-odd and create multiple consecutive rows with same ordering class. This will cause issues with formating dependent on these classes including apparent tabulator default

**Tabulator Info**
5.4.3

**Working Example**
https://jsfiddle.net/python3berg/qmwxz6jn/7/ 

**To Reproduce**
Follow JS fiddle link and click add row 3-4 times.

**Expected behavior**
Rows should be added with expected classes

**Screenshots**
![image](https://user-images.githubusercontent.com/73388511/211196651-bd984c21-732d-4d9c-abac-87c7c68271ff.png)

Environment:
Ubunto 20.04 server, windows chromium browser

**Comment by Tiuipuv** [comment]
I am also experiencing this issue, thanks for the report @python3Berg!

**Comment by olifolkerd** [comment]
Hey @python3Berg 

Thanks for the info, this should be a simple one to fix, i will aim to get something in for the patch release next week.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
I have just pushed a fix for this to the master branch and will include it in this weekends patch release.

Cheers

Oli :)
