### ISSUE TITLE
scrollbars disappear when using `maxHeight` and `minHeight`

### ISSUE THREAD

**Issue by Tiuipuv** [olifolkerd/tabulator#4087]
**Describe the bug**
When initializing tabulator with both the `minHeight` and `maxHeight` properties, overflow looses scrollbars.

**Tabulator Info**
- Which version of Tabulator are you using?
5.4.3

**Working Example**
https://jsfiddle.net/2wpsj69z/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Click add row.
2. Click add column (3x). A horizontal scrollbar will appear.
3. Click add row (4x). Both vertical and horizontal scrollbars will disappear.
4. Any further rows and columns added will not be available via scrollbar.

**Expected behavior**
After the end of step 3 of bug reproduction steps, overflow is accessible via scrollbar.

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Browser Chrome v108.0

**Comment by olifolkerd** [comment]
Hey @Tiuipuv 

Thanks for the headsup, i have pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)
