### ISSUE TITLE
If Tabulator is initiated within a function, error: Uncaught (in promise) TypeError: this.renderer is null

### ISSUE THREAD

**Issue by grufas** [olifolkerd/tabulator#4088]
Tabulator version v5.4.3.
Browsers: Firefox, Chrome, Opera

To replicate the problem press refresh button. Error appears in browsers console (error not visible in jsfiddle log)
https://jsfiddle.net/Grufas/613pneqz/1/

The same error appears with all methods like setData, replaceData, updateData. After error is raised, setData, replaceData, updateData... methods stop working.

If tabulator is not placed inside a function, there is no such issue. I wrap multiple tabulator instances into a function to initiate tabulator objects when it is necessary, because my project loads data dynamically. Also my post on [Stackoverflow](https://stackoverflow.com/questions/75121029/javascript-library-tabulator-uncaught-in-promise-typeerror-this-renderer-is)

I made a temporary solution which stops showing error in console, but doesn't fix failure of setData, replaceData, updateData...
`if(this.renderer.verticalFillMode === "fill"){`
Changed to
`if(this.renderer != null && this.renderer.verticalFillMode === "fill"){`

**Comment by dbauszus-glx** [comment]
@grufas I just hit the same problem. You will need to await a promise which resolves on the Tabulator tableBuilt event like so:

```js
  // Built Tabulator instance
  let T = new Tabulator(...arguments);

  // Await for the Tabulator table instance to be built in Promise
  await new Promise(resolve => T.on('tableBuilt', resolve))

  // Return built Tabulator instance.
  return T
```

**Comment by grufas** [comment]
Thanks, I figured it out and using same method:

`grid.on("tableBuilt", function() {
// All the magic is located here
});`
