### ISSUE TITLE
Download filtered data only

### ISSUE THREAD

**Issue by MikhailKlemin** [olifolkerd/tabulator#409]
Hello!

2.xx version I think export was downloading only filtered data... 
Does it possible to make it same way with 3.xx?

**Comment by olifolkerd** [comment]
Hey,

This is the same in version 3.xx are you having issues? do you have a copy of your constructor object i could have a look at?

Cheers

Oli

**Comment by MikhailKlemin** [comment]
Hi sorry! The constructor is rather same  as per my previous questions: 

```
$(document).ready(function() {
$("#example-table").tabulator({
       
        height:800,
        index: "ProductCode",
        fitColumns:true,
        sortBy:"Name", 
        sortable:true,
        sortDir:"asc", 
        showLoader: true,
        pagination:"local",
        paginationSize:150,
        columns:[ 
 {title:"Product Title", field:"Name", headerFilter: "input", sorter:"string", align:"left", visible:true, tooltipHeader:true},
 {title:"Brand", field:"Brand",sorter:"string", align:"left", visible:true, headerFilter:"input",width:125},
 {title:"Details", field:"Details", sorter:"string", formatter:"textarea",  align:"left", visible:true, width:400},
 {title:"Normal Price", field:"NormalPrice", sorter:"number",  formatter:"money", align: "center", sortable:true,headerFilter:"input", width:120},
 {title:"Sale Price", field:"SalePrice", sorter:"number",  formatter:"money", sortable:true, align: "center", headerFilter:"input", width:110}, 
 {title:"Category", field:"Category", sorter:"string", sortable:true, align:"left",headerFilter:"input"},
 {title:"Product ID", field:"ProductCode", sorter:"string",  align: "left", sortable:true,headerFilter:"input"},
 {title:"Color", field:"Color", sorter:"string",  align: "left", sortable:true,headerFilter:"input"},
 {title:"Size", field:"Size", sorter:"string",  align: "left", sortable:true,headerFilter:"input"},
 {title:"Stock", field:"Stock", sorter:"string", align: "left", sortable:true,headerFilter:"input",width:75, formatter:function(cell, formatterParams){
        
        
        if (cell.getValue()=="OS"){
            return "<span style='color:red'>out of stock</span>"; 
        }else if (cell.getValue()=="LS"){
            return "<span style='color:orange'>low stock</span>"; 
        }else if (cell.getValue()=="IS"){
            return "<span style='color:green'>in stock</span>"; 
            
        }
    },},
 {title:"Supplier", field:"Link", sorter:"string",  align: "left", sortable:true,width:100, formatter:"link"},
 {title:"Img", field:"Image", sorter:"string",  align: "left", sortable:true,width:100},
 {title:"Listed", field:"Ebay", align: "center", headerFilter:"input",width:75},
 {title:"Ebay Link", field:"EbayLink", sorter:"string",  align: "left", sortable:true,width:75, formatter:"link"},
 {title:"Time Stamp", field:"TimeStamp", sorter:"date",  align: "left", sortable:true, width:75},
        ]
    });
```
And the call to dnd functions is like this:

```
<div class="container" style="padding-bottom:5px">
<button type="button" id="#download-csv" class="btn btn-default" onclick='$("#example-table").tabulator("download", "csv", "data.csv");'>Export</button>
</div>

```

The header 

```
<head>
        <title>tabulator</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="css/tabulator.min.css">
        <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script type="text/javascript" src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
        <script type="text/javascript" src="js/tabulator.min.js"></script>
        <script type="text/javascript" src="js/edit.js"></script>
        <script type="text/javascript" src="js/format.js"></script>
        <script type="text/javascript" src="js/filter.js"></script>
        <script type="text/javascript" src="js/download.js"></script>
        <script type="text/javascript" src="js/sort.js"></script>
        <script type="text/javascript" src="js/responsive_layout.js"></script>

       <style type="text/css">
            body{ padding-top:10px;margin: 0px}
           .tabulator .tabulator-header .tabulator-col .tabulator-col-content .tabulator-col-title{ white-space: normal;}
            
        </style>  
</head>
```

**Comment by MikhailKlemin** [comment]
Hey, just checking up if @olifolkerd  seen my reply.

**Comment by MikhailKlemin** [comment]
Tried 3.1.2 - no difference, export everything regardless of head filters.

**Comment by olifolkerd** [comment]
Ive just noticed you seem to include the edit.js, format.js, download.js separately. They are all included in the ***tabulator.min.js*** by default, so this isn't necessary.

Is there a specific reason you are doing this, are you using your own package. The extensions aren't designed to be loaded separately, i cant predict how they would behave if used in that way.

Could you try with the default tabulator.min.js and no other extension files and let me know how that goes for you.

Cheers

Oli

**Comment by MikhailKlemin** [comment]
oh! I did  not knew that! will check asap

**Comment by MikhailKlemin** [comment]
Hi, no chances to look at it?  I just do not want to roll back to 2.8 
The header is OK now

>    <head>
>         <title>Title</title>
>         <meta charset="UTF-8">
>         <meta name="viewport" content="width=device-width, initial-scale=1.0">
>         <link rel="stylesheet" href="css/tabulator.min.css">
>         <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
>         <script type="text/javascript" src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
>         <script type="text/javascript"  src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
>         <script type="text/javascript" src="js/tabulator.min.js"></script>
>         
>        <style type="text/css">
>             body{ padding-top:10px;margin: 0px}
>            .tabulator .tabulator-header .tabulator-col .tabulator-col-content .tabulator-col-title{ white-space: normal;}
>             .container{margin:20px}
>         </style>  
> </head>
>

**Comment by olifolkerd** [comment]
Hey,

Thanks for sending of the test data, that was a great help!

it looks like there was a problem with an if statement in the getData function that was inverting the data array selection logic. I have just pushed a fix to the master branch, if you download that you should be good to go.

I will be doing another patch release soon so i will make sure it is included in that.

Cheers

Oli

**Comment by MikhailKlemin** [comment]
Thanks a lot!

5 июля 2017 г. 10:07 PM пользователь "Oli Folkerd" <notifications@github.com>
написал:
