### ISSUE TITLE
Empty space after last columns

### ISSUE THREAD

**Issue by mhlozek** [olifolkerd/tabulator#4092]
I want to create table from data stored in js variable with `fitColumns` option.

Problem: Generated table has empty space after last column (dark grey space in the fiddle).

The same table generated from ajax data is ok (no space after last column).

- Which version of Tabulator are you using?
5.4.3.

**Working Example**
https://jsfiddle.net/szowpLbk/3/

**Screenshots**
![space](https://user-images.githubusercontent.com/2743172/213178664-9856e831-14b5-45c9-a936-e615ee803120.png)

**Comment by olifolkerd** [comment]
Hey @mhlozek 

Thanks for the headsup, i have just pushed a fix for this to master and will include it in todays patch release.

Cheers

Oli :)
