### ISSUE TITLE
Tabulator rowFormatter (row.getElement().appendChild()) no longer respects fixed column.

### ISSUE THREAD

**Issue by VictorioBerra** [olifolkerd/tabulator#4093]
**Describe the bug**
In tabulator 5.3.4, HTML that I inject into a column with rowFormatter (`row.getElement().appendChild(whatever);`) would respect the fixed column.

In 5.4.3 I found that my HTML slides all the way to the left, and ignores the fixed columns.

**Tabulator Info**
- Upgraded from 5.3.4 to 5.4.3
- Bootstrap 5.2.3

**Working Example**
YOU MUST include a link to a JS Fiddle or Codepen that demonstrates the problem, it is very hard to diagnose an issue from a simple description.

- WORKING 5.3.4 https://jsfiddle.net/5wj0z9cb/2/
- NOT WORKING  5.4.3 https://jsfiddle.net/5wj0z9cb/3/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to WORKING 5.3.4 https://jsfiddle.net/5wj0z9cb/2/
2. Click on the "+" symbol to expand a child table.
3. Notice the table respects the fixed column, and is pushed to the right equal to the size of the column.
4. Now, go to NOT WORKING  5.4.3 https://jsfiddle.net/5wj0z9cb/3/
5. Do the same, notice the table is slammed all the way over to the left, ignoring the fixed column.

**Expected behavior**
In Tabulator 5.4.3, any child elements appended using rowFormatter (`row.getElement().appendChild(whatever);`) should respect the fixed column.

**Screenshots**

![image](https://user-images.githubusercontent.com/2934507/213478350-44af9aef-50dd-4d3f-9a39-b0ab53d679e1.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version Version 108.0.5359.126 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by olifolkerd** [comment]
Hey @VictorioBerra 

This is not a bug so much as Tabulator has fundamentally changed how the frozen columns are handled in the 5.4 release and you are performing an unsafe action with your row formatter.

in the 5.4 release the frozen column module was rebuilt using the 'sticky' display type. This made it much more efficient and user friendly, but is no longer compatible with your usage of the table.

Injecting a pusdo column in that fashion is unsafe as it Tabulators renderer is unaware of it and cannot adjust the column layouts.

In your case i would recommend listening to table [events](https://tabulator.info/docs/5.4/events) like `columnResized` to recalculate the amount you will need to set your left position to and then adopting the 'sticky' display approach of the new frozen column module.

Cheers

Oli :)

**Comment by VictorioBerra** [comment]
@olifolkerd I appreciate your reply, I have not used the Tabulator events, and I am not familiar with sticky display type, would you be willing to show me a simple example of what you mean using my fiddle?

**Comment by olifolkerd** [comment]
Hey @VictorioBerra 

Im afraid there isn't really a simple example for your usage case, it will involve a bit of work to get there, but i can point you to some examples.

With position 'sticky' you would use the 'left' CSS prop to determine how far left the table can go before it sticks. This page has some examples of how sticky works:
https://elad.medium.com/css-position-sticky-how-it-really-works-54cd01dc2d46

My suggestion (and it is how the frozen column system works) is to calculate the width of each of the columns that are frozen, and then use that sum to set the left position on the sticky object.  You can see how the Frozen columns module does it here:
https://github.com/olifolkerd/tabulator/blob/master/src/js/modules/FrozenColumns/FrozenColumns.js

To make sure this works, after initially setting the 'left' value, you will need to change this if the column widths change, to keep alignment. you can use various events that are triggered when things on the table change. A full guide for this can be found on the docs site:
https://tabulator.info/docs/5.4/events

Cheers

Oli :)
