### ISSUE TITLE
Get the ids of the unchecked rows in Selectable Rows With Tickbox

### ISSUE THREAD

**Issue by ferriroberto** [olifolkerd/tabulator#4094]
*Is your feature request related to a problem? Please describe.**
I created a table with rows selectable using a tickbox. the tickbox in the column header allows me to get the ids of the selected rows via the "rowselectedchanged" function. When I deselect the rows, however, I expect to be able to massively withdraw the "deselected" ids in order to act programmatically on these ids (for example deleting rows from a database). The "rowDeselected" function only works on one row at a time, so if I have to delete, for example, 100 rows from a database the "rowDeselected" function calls me the delete script 100 times (and I don't want to!!).

**Describe the solution you'd like**
I propose a function like "rowselectedchanged" but that does the opposite .... "rowDESELECTEDchanged" :)

**Comment by mastrdev** [comment]
I can't think of a use case for this, but couldn't you just store the selected ids in a variable and then compare the new list of selected ids the next time "rowSelectionChanged" fires (or at any time with the _table.getSelectedRows()_ function) to get the "deselected" ids?

**Comment by ferriroberto** [comment]
Grazie mille

Dott. Roberto Ferri

*Studio Luca Monteverdi - Elaborazioni e servizi s.r.l.*

*Via San Domenico 2 *
* 43043 Borgo Val di Taro (PR) *

*Tel. 0525/921217 - Fax 0525/921631 *
*e-mail: ***@***.***
***@***.***>** - web: *
*www.elaborazionieservizi.com
<http://www.elaborazionieservizi.com>**Condivisione
file Google Workspace: ***@***.***
***@***.***>*
*PEC: ***@***.**** ***@***.***>

*SKYPE: robbyferri*

*Le informazioni contenute nella presente comunicazione e i relativi
allegati possono essere riservate e sono, comunque, destinate
esclusivamente alle persone o alla Societa sopraindicati.La diffusione,
distribuzione e/o copiatura del documento trasmesso da parte di qualsiasi
soggetto diverso dal destinatario e proibita, sia ai sensi dell'art. 616
c.p. , che ai sensi del D.Lgs. n. 196/2003. Se avete ricevuto questo
messaggio per errore, vi preghiamo di distruggerlo e di informare
immediatamente il mittente. *



*The information in this e-mail (which includes any files transmitted with
it) is confidential and may also be legally privileged. It is intended for
the addressee only. Access to this e-mail by anyone else is unauthorised.
It is not to be relied upon by any person other than the addressee, except
with our prior written approval. If no such approval is given, we will not
accept any liability (in negligence or otherwise) arising from any third
party acting. Unauthorised recipients are required to maintain
confidentiality. If you have received this e-mail in error please notify us
immediately, destroy any copies and delete it from your computer system.
Any use, dissemination, forwarding, printing or copying of this e-mail is
prohibited. *


Il giorno lun 30 gen 2023 alle ore 10:20 mastrdev ***@***.***>
ha scritto:

**Comment by olifolkerd** [comment]
Hey @ferriroberto 

Thanks for your suggestion.

In this case i feel that the existing functionality works just fine, you could easily handle most usage cases without issue.

I will have a look in the future at adding an additional argument for the `rowSelectionChanged` event to pass the rows selected and deselected during that change.

Cheers

Oli :)
