### ISSUE TITLE
tabEndNewRow option not working

### ISSUE THREAD

**Issue by dorje77** [olifolkerd/tabulator#4095]
**Describe the bug**
tabEndNewRow option does not create a new row when tab key is pressed on last editable cell.

**Tabulator Info**
Tabulator 5.4.3

**Working Example**
https://codepen.io/dorje77/pen/XWZjwVd

**To Reproduce**
1. Click on the "description" cell on the last (empty) row of the table.
2. Compile the row (first two controls are lists), until reaching the last editable cell (column "total").
3. hit "tab" once more

**Expected behavior**
After last "tab", a new row should appear and the focus should be on the first editable cell. Instead, no row is created and the focus move on the first editable cell of the same row.

**Desktop (please complete the following information):**
 - OS: Macos Ventura 13.0.1
 - Browser: Firefox, Chrome
 - Version 109.0 and 109.0.5414.87

**Smartphone (please complete the following information):**

**Additional context**
Working in 5.4.2 in Firefox (but not on Chrome)

**Comment by olifolkerd** [comment]
Hey @dorje77 

I have pushed a fix for this to the master branch and will include it in this weekends patch release.

Cheers

Oli :)
