### ISSUE TITLE
bottomCalcFormatter doubling up on first row value and group item count

### ISSUE THREAD

**Issue by rcldave** [olifolkerd/tabulator#4096]
Here's a jsfiddle that show the problem

https://jsfiddle.net/drod62/j12p8xq4/53/

Using v5.4.3 with 'bottomCalc: sum'.
I have an 'addRow' button that adds a new row to the table.
Click on that and add a value - say 10 - this updates the bottomCalc, but doubles the value to add 20.
The group item count is also doubled from 1 to 2

I can switch the library out for v5.4.0 and the calc works correctly. I think I've seen this issue with a previous version too that was subsequently fixed.

I'm using a Mac/chrome

**Comment by olifolkerd** [comment]
Hey @rcldave 

I have pushed a fix to the master branch to fix this, it will be included in this weekends patch release.

Cheers

Oli :)
