### ISSUE TITLE
Center rowSelection checkbox in titleFormatter

### ISSUE THREAD

**Issue by argo-uka** [olifolkerd/tabulator#4097]
This is an aesthetic feature request. But I already found a solution. It is nice to center vertically and horizontally the checkbox in the header.

**Describe the solution you'd like**
```js
export default function (cell, formatterParams, onRendered) {

    onRendered(() => {
        let container = cell.getElement();
        let parent = container.parentElement;
        let grandParent = parent.parentElement;


        parent.style.height = "100%";

        grandParent.style.height = "100%";

        container.style.height = "100%";
        container.style.display = "flex";
        container.style.justifyContent = "center";
        container.style.alignItems = "center";

    })

    var checkbox = document.createElement("input");

    checkbox.type = 'checkbox';

    if (this.table.modExists("selectRow", true)) {

        checkbox.addEventListener("click", (e) => {
            e.stopPropagation();
        });

        if (typeof cell.getRow == 'function') {
            var row = cell.getRow();

            if (row instanceof RowComponent) {

                checkbox.addEventListener("change", (e) => {
                    row.toggleSelect();
                });

                checkbox.checked = row.isSelected && row.isSelected();
                this.table.modules.selectRow.registerRowSelectCheckbox(row, checkbox);
            } else {
                checkbox = "";
            }
        } else {
            checkbox.addEventListener("change", (e) => {
                if (this.table.modules.selectRow.selectedRows.length) {
                    this.table.deselectRow();
                } else {
                    this.table.selectRow(formatterParams.rowRange);
                }
            });

            this.table.modules.selectRow.registerHeaderSelectCheckbox(checkbox);
        }
    }

    return checkbox;

}
```
**Describe alternatives you've considered**
I tried modify the css for `tabulator-col-title` , `tabulator-col-title-holder` and `tabulator-col-content`. But they have an effect also on others column header.

**Comment by olifolkerd** [comment]
Hey @argo-uka 

Thanks for getting in touch.

This is already possible with the `headerHozAlign` column definition option.
https://tabulator.info/docs/5.4/columns#alignment

Cheers

Oli :)

**Comment by olifolkerd** [comment]
@argo-uka If you look at the next section down in the docs you will see there is a vertical align option also

**Comment by argo-uka** [comment]
@olifolkerd you mean `columnHeaderVertAlign`, but doesn't that align all headers? If I understand correctly, there isn't a way to selectivley vertically align a header, right?

**Comment by olifolkerd** [comment]
Correct, can you give an example of a table where individual vertical alignment would be nessisary, in most cases it tends to look messy if the the column headers have different alignments

**Comment by argo-uka** [comment]
You are absolutely right on that in some scenario it would look messy. In my situation, when all columns, except the first one, have a header filter, it looks better when the checkbox is aligned vertically in the middle.

Without alignment
![image](https://user-images.githubusercontent.com/87370407/222152581-a685159c-95f8-4c8f-aa5f-cc043ed16f67.png)

With alignment
![image](https://user-images.githubusercontent.com/87370407/222152716-c150a3c4-b03c-49d9-a0cf-4865b2b8526e.png)

At the end, it boil down to personal preferences. But I think it would be great to have option.
