### ISSUE TITLE
Set grid height to 100% + offset to fix height problem in mobile browsers

### ISSUE THREAD

**Issue by grufas** [olifolkerd/tabulator#4099]
Example: 
We have a div column with children elements: custom header with 200px height and tabulator grid. We want to make grid to fill the rest height of the page. To achieve that, I used height: "calc(100vh - 200px)". It works perfectly in desktop browsers, but the issue appears in mobile browsers because browsers search bar height varies (portrait, landscape, browser type, etc), so by setting grid height statically, it doesn't work in all situations. 

I made a temporary solution.
1. I do not set any height property for the grid
2. Run custom function after the grid is initialized

It would be great to have a native option in Tabulator to set grid height to 100% with offset option that will dynamically adjust height while resizing window. The offset will give more flexibility. 

`
// gridId: Id of the Tabulator grid
// parentId: Id of the parent element
// offset: number which represents height of child element besides grid itself 
function setMaxHeight(gridId, parentId, offset) {
		setHeight();
		let height;
		window.onresize = function(){
		  clearTimeout(height);
		  if(document.getElementById(gridId)) {
			height = setTimeout(setHeight(), 100);
		  }
		};
		function setHeight() {
			let parentHeight = document.getElementById(parentId).offsetHeight;
			document.getElementById(gridId).style.height = parentHeight - offset+'px';
		}
	};`

To my knowledge, it doesn't violate or negatively affect Tabulator native functionality or virtual DOM. I hope Oliver can give some insights on this. Thank you.

**Comment by olifolkerd** [comment]
Hey @grufas 

You could easily manage this through styling the containing element of the table. It would be outside the reemit of Tabulator to look beyond the .tabulator element, and would risk it interfering with other libraries.

Cheers

Oli :)
