### ISSUE TITLE
make it lib independent

### ISSUE THREAD

**Issue by craigcosmo** [olifolkerd/tabulator#41]
Are you interested in making this plugin independent? I will be happy to help. I can take care 50% of workload.

**Comment by olifolkerd** [comment]
Hey,

That has always been on the roadmap. I would greatly appreciate the help. Would be looking to do it in such a way that a jquery wrapper could be put roubd it if  people needed.

I have few changes to commit on sunday. Will then create a branch for the project.

**Comment by craigcosmo** [comment]
hey, what's the status now?

**Comment by olifolkerd** [comment]
I made a start on this, and have an outline for how i want the library to function. 

Unfortunately there is too much active development going on in the main branch at the moment, and the wholesale refactoring of the library while other lots of other development is ongoing is going to be too tricky as we will constantly have to merge back in jquery dependant changes.

For the next couple of months i am planning a new release of tabulator every two weeks, with whole new feature sets in each version.

Once all of the updates are in (end of October at this rate) i would then be looking to take a break from active releases for a month or so to do the migration to a non jquery dependent version of the library.

If you were still up for it at that point i would be extremely grateful for your assistance.

**Comment by olifolkerd** [comment]
In terms of work that will need doing, I would be looking to manage refactoring the overall structure of the library, public function access and creating a JQuery wrapper for backwards compatibility.

What would be of great help would be assistance in moving from the JQuery DOM selectors to querySelector() functions, and coming up with an alternative to the JQuery data() function which is used extensively throughout the library.

**Comment by craigcosmo** [comment]
that's doable. I can help that

**Comment by olifolkerd** [comment]
Brilliant stuff, i will stick a new branch in in October and drop a message on here with more info.

**Comment by olifolkerd** [comment]
Hey @craigcosmo 

You will be happy to hear that Tabulator is no longer jQuery Dependent!

It just took a little longer that we first thought to get there.

have a look at www.tabulator.info for more information.

Cheers

Oli :)

**Comment by craigcosmo** [comment]
Hey, I know it’s kind of late reply. but great work man. Very nice.



On Sep 24, 2018, at 4:33 AM, Oli Folkerd <notifications@github.com> wrote:

Hey @craigcosmo <https://github.com/craigcosmo>
You will be happy to hear that Tabulator is no longer jQuery Dependent!

It just took a little longer that we first thought to get there.

have a look at www.tabulator.info <http://www.tabulator.info/> for more information.

Cheers

Oli :)
