### ISSUE TITLE
Moving rows between groups breaks multiple features

### ISSUE THREAD

**Issue by mastrdev** [olifolkerd/tabulator#4100]
**Describe the bug**
Moving rows between groups can work in a barebones configuration, but a few useful features are broken when using _movableRows_ with _groupBy_. These problems appear to be related to the same root cause, so I'm including all of them in a single bug report.
- _groupValues_ **must** be set or rows can't be moved between groups (throws an _error_).
- Mutators break when moving rows between groups because the _value_ passed to the mutator is _undefined_.
- _groupUpdateOnCellEdit_ works at first, but causes an _error_ to be thrown after moving rows between groups.

**Tabulator Info**
- 5.4.3

**Working Examples**
- [Barebones](https://jsfiddle.net/hw9ebas1/) - This works fine.
- [groupValues removed](https://jsfiddle.net/52ca6soy/) - Can't move rows between groups. Throws error: _Uncaught TypeError: Cannot create property 'innerHTML' on boolean 'false'_ at Group.js:492
- [mutator added](https://jsfiddle.net/gnwzckao/) - _value_ received by mutator is _undefined_, so the field gets cleared.
- [groupUpdateOnCellEdit added](https://jsfiddle.net/1fvhea4d/) - Works at first for cell edits by user, but moving rows throws same _TypeError_ as above at Group.js:492. Editing the moved row can throw _Uncaught TypeError: Cannot read properties of null (reading 'insertBefore')_ at MoveRows.js:349, and the row disappears.

**To Reproduce**
1. Open one of the JSFiddle examples above
2. Drag either row to a new group
3. (In the final example, change the Gender field for the row you just moved)

**Expected behavior**
Moving rows between groups is really useful, but shouldn't break mutators,_groupUpdateOnCellEdit_, and dynamic grouping without specified _groupValues_.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browsers: Edge 109, Chrome 109, Firefox 102.6

**Smartphone:**
 - Device: iPhone Xs Max
 - OS: iOS 15.7
 - Browser: Safari (stock browser)
 - Version: 15.6

**Comment by olifolkerd** [comment]
Hey @mastrdev 

Thanks for getting in touch, your detailed explanations and JS Fiddles were very helpful.

I have pushed fixes for these to the master branch and will include them in this weekends patch release.

Just a quick not for future issues, would you mind creating separate issues for each bug you find, it makes it much easier to track progress in resolving things. these were each distinct bugs with their own fixes so it makes it easier if they can be marked as resolved individually that way we don't end up with part fixed issues.

Cheers

Oli :)
