### ISSUE TITLE
rowMoved Callback doesn't exist

### ISSUE THREAD

**Issue by mastrdev** [olifolkerd/tabulator#4101]
**Website Page**
"Callbacks" under [Movable Rows](https://tabulator.info/docs/5.4/move#rows) heading, 

**Describe the issue**
The documentation describes a _rowMoved_ callback that doesn't actually exist (anymore?). We have an event instead. Recommend removing this section.

![image](https://user-images.githubusercontent.com/6566403/214508301-dff6fe3d-2eb6-415b-aa8d-b140550f221e.png)

**Comment by olifolkerd** [comment]
Hey @mastrdev 

This is a legacy docs issue, it is now the `rowMoved` event, https://tabulator.info/docs/5.4/events#row-move

I will get the docs fixed in the next patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
I have pushed an update to the doc codepase so will close this issue, it will be deployed with the next patch release towards the end of the week.

Cheers

Oli :)
