### ISSUE TITLE
Date editor is glitchy with manual entry and/or picker

### ISSUE THREAD

**Issue by MWWorks** [olifolkerd/tabulator#4102]
Great to see the date editor now built in (and happy that it uses the native date input type). But it seems a bit glitchy - see example using 5.4.3:

https://jsfiddle.net/js6hwanu/3/

- The native datepicker widget works as expected in Chrome; but in Firefox, clicking a date doesn't change the cell content
- In either browser, manual entry doesn't work - eg I'm UK locale and the picker shows dd/mm/yyyy - I can't type a full date, at some point during keying the focus drops and no change is saved to the cell
 
Looks like some event handling is amiss?

**Comment by wdehoog** [comment]
I noticed it as well. It used to work so I guess it is due to an update of Firefox.
Seems that now one needs to listen to "input" events.

**Comment by MWWorks** [comment]
As a followup, some experimenting and hunting around has shed a little light on this. Roughly:

- When using the picker, FF and Chrome fire a change event with the new value
- But FF also precedes this with a blur event with the old value - hence the tabulator editor 'succeeds' with that
- When manually entering dates, both browsers fire 0 or more change events for each component of the date - this also causes the editor to succeed before input is complete

Although not perfect, this is my current setup which covers most use patterns; it starts with the change event (that works for for using the picker), then when keying starts, removes it in favour of blue (after keying):

    Tabulator.extendModule("edit", "editors", {

        cdate:function(cell, onRendered, success, cancel, editorParams){
            let input = document.createElement("input");

            input.type = "date";
            input.style.padding = "4px";
            input.style.width = "100%";
            input.style.boxSizing = "border-box";
            input.value = cell.getValue();;

            onRendered(function(){
                input.focus();
                input.style.css = "100%";
            });

            let accept = function(e){success(input.value)};

            input.addEventListener("change", accept);
            input.addEventListener("keydown", function(e){
                input.removeEventListener("change", accept)
                input.addEventListener("blur", accept)
            });

            return input;
        }
    });

**Comment by mastrdev** [comment]
@MWWorks Interestingly, I couldn't replicate this bug with Firefox ESR (v102); I had to install Firefox v109.

**Comment by MWWorks** [comment]
> @MWWorks Your suggested code was still buggy since built-in date pickers update the input when selecting month/year, firing a change event prematurely.

Oh, good catch - I knew it would fail if starting keying then used the picker - but I hadn't tried the month picker. Just tried yours, seems working well, thanks for going the extra mile :)

**Comment by olifolkerd** [comment]
I have just merged @mastrdev PR into master, that should resolve this issue.

I will include it in the next patch release in a few days.

Cheers

Oli :)
