### ISSUE TITLE
Deleteing a row from receiving table breaks move from first table functionality

### ISSUE THREAD

**Issue by Magic-Music** [olifolkerd/tabulator#4103]
**Describe the bug**
Deleting a row from a 'receiving table' breaks drag fuctionality on the first table
After dragging elements from table one to table two, then deleting a row using cell.getRow() delete, a further drag attempt throws an error

**Tabulator Info**
5.4

**Working Example**
https://jsfiddle.net/r8met5zg/2/

**To Reproduce**
1. Drag a row from the first table to the second. 
2. Use the 'delete' button on the second table to delete the entry
3. Now try another drag from the first table. 
4. An error appears in the console: Uncaught TypeError: e.getElement(...).addEventListener is not a function
    at MoveRows.js:479:23

**Expected behavior**
Rows should continue to be draggable from the first to the second table after deleting an row from the second table

**Desktop (please complete the following information):**
 - OS:Windows 10
 - Browser Chrome
 - Version 109.0.5414.76

**Comment by Magic-Music** [comment]
I can work around this by doing the following in the cellClick event function:

cell.getRow().delete()
let data = table.getData()
table.replaceData(data)

**Comment by Magic-Music** [comment]
I can work around this bug by doing the following in the cellClick event of the delete button:

cell.getRow().delete()
let tableData = table.getData()
table.replaceData(tableData)

**Comment by iutarian** [comment]
@Magic-Music You are genius, thanks!

**Comment by olifolkerd** [comment]
Hey All,

I have pushed a fix for this to the master branch and will include it in this weekends patch release.

Cheers

Oli :)

**Comment by Magic-Music** [comment]
Amazing, thanks Oli, and thank you for an incredible product!
