### ISSUE TITLE
Sorting on a number column descending has incorrect rounding / precision on column calc row.

### ISSUE THREAD

**Issue by lukecotter** [olifolkerd/tabulator#4110]
**Describe the bug**
Sorting on a number column descending has incorrect rounding / precision on column calc row.
Sorting ascending works correctly.

**Tabulator Info**
5.4.3

**Working Example**
https://jsfiddle.net/bes97L5f/1/

![image](https://user-images.githubusercontent.com/4013877/215805836-4d7d9c58-9426-4bf0-87f1-c256b443a945.png)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://jsfiddle.net/bes97L5f/1/
2. Look at the calc column for time on the top grid (sorted desc by default)
3. It should be rounded to 2dp
4. Sorting ascending works fine.
5. Click on the column header to re sort ascending and see the correct value.

**Expected behavior**
Sorting descending or ascending should result in the same sum regardless of column sort.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Macbook pro
 - OS: Ventura 13.2 
 - Browser Google Chrome
 - Version: 109.0.5414.119

**Comment by olifolkerd** [comment]
Hey @lukecotter 

This isnt a Tabulator issue as such, it just uses standard JavaScript math functionality,

This is actually a floating point precision issue that is common across all math functions with decimals in JavaScript, your example just happens to have found a bad combinations of numbers.

The good news is that you can easily constrain the precision in the calculation function to force it to whatever level you like:
```js
{title:"Time", field:"time", bottomCalc: "sum", bottomCalcParams:{precision:2}},
```

Cheers

Oli :)

**Comment by lukecotter** [comment]
Thanks @olifolkerd 

I am using typescript and the definition file did not make that obvious. 
I have opened a PR to hopefully resolve it 
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64309
