### ISSUE TITLE
header filters doesn't work properly when virtualdom is disabled

### ISSUE THREAD

**Issue by factec-kyle** [olifolkerd/tabulator#4113]
**Describe the bug**
* headerfilter:'list' doesn't work properly when virtualdom is disabled.

**Tabulator Info**
- Which version of Tabulator are you using?
5.4.3

**Working Example**
YOU MUST include a link to a JS Fiddle or Codepen that demonstrates the problem, it is very hard to diagnose an issue from a simple description.

https://codepen.io/factec-kyle/pen/WNKYezJ?editors=1111

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. click column header for "book name"
2. select one item and click blank space to apply
3. see no filtering applied
4. click column header again
5. select another item. total of 2
6. see only 1 row filtered which I selected at step 2

**Expected behavior**
* filtering is applied immediately when I select items in column header

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] 109.0.5414.75

**Smartphone (please complete the following information):**

**Additional context**
1. I know you dont recomment disabling virtual dom but I found users sometimes use Ctrl+F to find data. I disabled virtual dom option to cope with this issue because I have tables with relatively small data (< 300 rows).

2.
https://codepen.io/factec-kyle/pen/KKBrKdY?editors=1111

above is a messy version that used to find a way to reproudce. 
It has a same error and one more thing to check. 
It prints a message to console
```
"Event Target Lookup Error - The row this cell is attached to cannot be found, has the table been reinitialized without being destroyed first?"
```
I couldn't find what causes this error message.

**Comment by olifolkerd** [comment]
Hey @factec-kyle 

Thanks for getting in touch, it wasn't the list editor, it was all filter actions so i have updated the title of the issue to match.

I have pushed a fix for this to the master branch and will include it in the weekends patch release.

Cheers

Oli :)
