### ISSUE TITLE
Typo on the Examples Page

### ISSUE THREAD

**Issue by riziles** [olifolkerd/tabulator#4116]
**Website Page**
<https://tabulator.info/examples/5.4#virtual-dom>

**Describe the issue**
"Vertical" is misspelled in the first item on the sidebar.

**Comment by olifolkerd** [comment]
Hey @riziles 

Thanks for the headsup, i have pushed a fix for this to the site source and will update it publicly with the patch release towards the end of the week.

Cheers

Oli :)
