### ISSUE TITLE
Data rows sometimes over column headers after page refresh (Chrome)

### ISSUE THREAD

**Issue by DamianReloaded** [olifolkerd/tabulator#4117]
Pressing page refresh F5 and or ctrl refresh alternately makes, sometimes, the data rows go over the column headers
I'm using remote pagination.

[
        { title: "Id", field: "Id", sorter: "string"},
        { title: "Description", field: "Description", sorter: "string" }
]; 

EDIT: It also happens with any of the provided stylesheets, so it's not related to changes in the grid stylesheet.
EDIT: It seems to correct itself when resizing the window or dragging resizing the development console
EDIT: It happens independently of whether autoColumns is true of false
EDIT: It also occurs on Edge browser.

EDIT: Problem seems to be in the elements with class "tabulator-placeholder" and "tabulator-tableholder" that seems to have an incorrect size sometimes between refreshes.

A workaround is to call columnManager.redraw from the dataLoaded event
```
                let tmpTabulator = this.tabulator; 
                this.tabulator.on("dataLoaded", function (data) {
                    tmpTabulator.columnManager.redraw(true);
                });
```
![image](https://user-images.githubusercontent.com/20878963/217277406-ef1f1c66-bc80-4a75-bc35-17be5302fb78.png)
![image](https://user-images.githubusercontent.com/20878963/217279506-a6e5b4cb-32a7-4944-af7e-ebae1e0823f3.png)
![image](https://user-images.githubusercontent.com/20878963/217279598-a5075e21-8593-4cc5-a0d5-124c1b366b40.png)
![image](https://user-images.githubusercontent.com/20878963/217280339-b600f11d-b8f5-48d3-b78a-23c1f7ac013e.png)
![image](https://user-images.githubusercontent.com/20878963/217299176-f841859c-0a8b-471a-a8b9-f222441d3296.png)
![image](https://user-images.githubusercontent.com/20878963/217299252-b5a57aa9-1770-40b9-920c-00c806fb25fc.png)

![image](https://user-images.githubusercontent.com/20878963/217303109-98c00113-5918-482c-bc68-8e61c9010f8e.png)

**Comment by olifolkerd** [comment]
Hey @DamianReloaded 

Could you  please provide a link to a JS Fiddle that demonstrates this issue.

The auto columns feature is completely unrelated to table layout, so this is more likely an unusual interaction between tabulator and your environment.  If you could provide an example fiddle we can get to the bottom of this issue and get a patch in if needed.

Cheers

Oli :)

**Comment by DamianReloaded** [comment]
`<script src="https://unpkg.com/vue@3.2.47/dist/vue.global.js"></script>
<script src="https://unpkg.com/tabulator-tables@5.4.0/dist/js/tabulator.js"></script>

<script type="module">
   

class GridPage {
  constructor(ajaxUrl, appElementId = "app") {
    this.AjaxURL = (ajaxUrl) ? ajaxUrl : "";
    this.AppElementId = appElementId;
    this.AppTopBarId = appElementId + "TopBar";
    this.GridElementId = appElementId + "TabulatorGrid";
    this.AjaxParams = {};
    this.Module = null;
    this.FormData = new FormData();
    this.GridHeight = "72vh";
    this.PaginationSelector = [1000, 5000, 10000, 50000, true];
    this.PaginationSize = this.PaginationSelector[0];
    this.AutoColumns = false;
    this.ColumnConfig = [];
    this.MovableColumns = true;
    this.FooterElement = "";
    this.Data = [];
    this.tableBuilt = () => {};
    this.dataLoaded = (data) => {};
    this.Tabulator = null;
    this.ShowButtonNew = true;
    this.ShowQuickSearch = true;
    this.ShowExportCSV = true;
    this.ShowEditButton = false;
    Object.seal(this);
  }

  init() {
    this.initColumnConfig();
    this.initTabulator();
    Vue.createApp(this.Module).mount('#' + this.AppElementId);
  }
  AppElementId

  setPageSize(value) {
    this.Module.tabulator.setPageSize(value);
  }

  customFilterAll(data, val) {
    var value = '' + ((typeof val === 'string') ? val : '');
    value = value.trim().toLowerCase();
    for (var key of Object.keys(data)) {
      let cell = ('' + data[key]).toString().toLowerCase();
      if (cell && cell.includes(value)) return true
    }
    return (value == "");
  }

  initColumnConfig() {
    let finalConfig = [];

    if (this.ShowEditButton) {
      finalConfig.push({
        width: 40,
        hozAlign: "center",
        field: "Id",
        formatter: (cell, fp, or) => {
          return "<a href='#' class='gridfix_button'><i class='icon_edit icon_edit_color'></i></a>";
        },
        cellClick: function(e, cell) {
          var row = cell.getRow();
          showModal(cell.getData());
        }
      });

    }

    for (let i = 0; i < this.ColumnConfig.length; i++) {
      finalConfig.push(this.ColumnConfig[i]);
    }

    this.ColumnConfig = finalConfig;
  }

  initButtonNew(divElement) {
    {
      let colNewDiv = document.createElement("div");
      colNewDiv.classList.add("col-sm");
      colNewDiv.style.textAlign = "left"; {
        if (this.ShowButtonNew) {
          let buttonNew = document.createElement("a");
          buttonNew.id = this.AppElementId + "_ButtonNew";
          buttonNew.classList.add("btn");
          buttonNew.classList.add("btn-primary");
          buttonNew.classList.add("btn-grid-new");
          buttonNew.attributes['href'] = '#';
          buttonNew.onclick = function() {
            window["showModal"]({
              Id: 0
            });
          }; {
            let buttonIcon = document.createElement("i");
            buttonIcon.classList.add("mdi");
            buttonIcon.classList.add("mdi-file");
            buttonNew.appendChild(buttonIcon);
            let span = document.createElement('span');
            span.innerHTML = "&nbsp;Nuevo";
            buttonNew.appendChild(span);
          }
          colNewDiv.appendChild(buttonNew);
        }
      }
      divElement.appendChild(colNewDiv);
    }
  }

  initExportCSV(divElement) {
    {
      let outerDiv = document.createElement("div");
      outerDiv.style.verticalAlign = "middle";
      outerDiv.style.textAlign = "center";
      outerDiv.style.width = "40px";
      outerDiv.style.padding = "0px";
      outerDiv.style.paddingRight = "8px"; {
        let innerDiv = document.createElement("div");
        innerDiv.id = this.AppElementId + "_CSVIconDiv";
        let self = this;
        innerDiv.onclick = () => {
          
        }; {
          if (this.ShowExportCSV) {
            let buttonCSV = document.createElement("a");
            buttonCSV.id = this.AppElementId + "_buttonCSV";
            buttonCSV.attributes['href'] = '#'; {
              let imgCSV = document.createElement("img");
              imgCSV.classList.add("icon_excel");
              buttonCSV.appendChild(imgCSV);
            }
            innerDiv.appendChild(buttonCSV);
          }
        }
        outerDiv.appendChild(innerDiv);
      }
      divElement.appendChild(outerDiv);
    }
  }

  initQuickSearch(divElement) {
    {
      let colQuickSearchDiv = document.createElement("div");
      colQuickSearchDiv.classList.add("col-sm");
      colQuickSearchDiv.style.textAlign = "right"; {
        if (this.ShowQuickSearch) {
          let inputSearch = document.createElement("input");
          inputSearch.id = this.AppElementId + "_SearchText";
          inputSearch.classList.add("gridfix-search-input");
          inputSearch.attributes['type'] = 'text';
          inputSearch.placeholder = "Búscar en esta página...";
          let self = this;
          inputSearch.onkeyup = () => {
            self.Tabulator.setFilter(self.customFilterAll, document.getElementById(self.AppElementId + '_SearchText').value)
          };
          colQuickSearchDiv.appendChild(inputSearch);
        }
      }
      divElement.appendChild(colQuickSearchDiv);
    }
  }

  initTopBar() {
    let topBar = document.getElementById(this.AppTopBarId); {
      let outerDiv = document.createElement("div");
      outerDiv.style.width = "100%";
      outerDiv.style.paddingBottom = "5px"; {
        let rowDiv = document.createElement("div");
        rowDiv.classList.add("row");
        this.initButtonNew(rowDiv);
        this.initQuickSearch(rowDiv);
        this.initExportCSV(rowDiv);
        outerDiv.appendChild(rowDiv);
      }
      topBar.appendChild(outerDiv);
    }
  }

  initTabulator() {
    let self = this;
    this.Module = {
      components: {

      },
      data() {
        return {
          tabulatorId: self.GridElementId,
          tabulator: null,
        }
      },
      mounted() {
        let verificationToken = "asdfasdf";
        this.tabulator = new Tabulator('#' + this.tabulatorId, {
          ajaxURL: self.AjaxURL,
          ajaxParams: function() {
            return self.AjaxParams;
          },
          height: self.GridHeight,
          autoColumns: self.AutoColumns,
          columns: self.ColumnConfig,
          paginationSize: self.PaginationSize,
          paginationSizeSelector: self.PaginationSelector,
          movableColumns: self.MovableColumns,
          footerElement: self.FooterElement,

          ajaxConfig: "POST",
          ajaxContentType: "json",
          ajaxContentType: {
            headers: {
              "Content-Type": "application/x-www-form-urlencoded",
              "Accept": "application/json",
              "RequestVerificationToken": verificationToken,
            },
            body: function(url, config, params) {
              return new URLSearchParams(self.FormData);
            },
          },
          dataLoaderLoading: "Cargando Datos",
          pagination: true,
          paginationMode: "remote",
          paginationCounter: "rows",
          ajaxURLGenerator: function(url, config, params) {
            return url + "&params=" + encodeURI(JSON.stringify(params));
          },
          layout: "fitDataFill",
          placeholder: "No se encontraron datos",
          locale: "es-ar",
          langs: {
            "es-ar": {
              "columns": {
                "name": "Nombre", //replace the title of column name with the value "Name"
              },
              "data": {
                "loading": "Cargando", //data loader text
                "error": "Error", //data error text
              },
              "groups": { //copy for the auto generated item count in group header
                "item": "item", //the singular  for item
                "items": "items", //the plural for items
              },
              "pagination": {
                "page_size": "Items por página", //label for the page size select element
                "page_title": "Mostrar Página", //tooltip text for the numeric page button, appears in front of the page number (eg. "Show Page" will result in a tool tip of "Show Page 1" on the page 1 button)
                "first": "<<", //text for the first page button
                "first_title": "Primera Página", //tooltip text for the first page button
                "last": "»",
                "last_title": "Última Página",
                "prev": "<",
                "prev_title": "Página Anterior",
                "next": ">",
                "next_title": "Página Siguiente",
                "all": "Todo",
                "counter": {
                  "showing": "Mostrando",
                  "of": "de",
                  "rows": "filas",
                  "pages": "páginas",
                }
              },
              "headerFilters": {
                "default": "filtrar columna...", //default header filter placeholder text
                "columns": {
                  "name": "filtrar nombre...", //replace default header filter text for column name
                }
              }
            }
          },
        });

        self.initTopBar();
      },
      modules: {

      },
      created() {

      },
      methods: {

      },
      template: /*html*/ (`
                    <div id="appTopBar"></div>
                    <div ref="table" :id="tabulatorId"></div>
                `),
    };
  }
}
    
    
    let page = new GridPage("https://tabulator.info/exampledata/ajaxprogressive");
    page.AutoColumns = true;
    page.ShowEditButton = true;
    page.init();
</script>

<div id="app"></div>`

**Comment by olifolkerd** [comment]
Hey @DamianReloaded 

I am unable to replicate the issue, i would suggest this is down to some external CSS on the page conflicting with the Tabulator style sheets.

If you can put together a minimal reproducible example i may be able to help you more, but im afraid i dont have time to debug an entire pages worth of code.

Checkout the Community documentation for an example of how to build a simple fiddle and what a Minimal reproducible example looks like

https://tabulator.info/community/mre

Cheers

Oli :)
