### ISSUE TITLE
Scrollbar and pagination

### ISSUE THREAD

**Issue by edicson** [olifolkerd/tabulator#4118]
In agular the pagination and the horizontal and vertical scrollbar do not work

**Comment by olifolkerd** [comment]
Hey @edicson 

Please fill out the bug report issue template and provide a JS fiddle to demonstrate the issue, without seeing how your table setup it is hard to offer advice, im afraid that your 1 line description is not much to go on.

I can say categorically that Tabulator does work in angular, so this is likely a configuration/setup issue. If you can provide more details, I would be happy to point you in the right direction.

Cheers

Oli :)
