### ISSUE TITLE
RSS Connectivity

### ISSUE THREAD

**Issue by gogulf1954** [olifolkerd/tabulator#4119]
Is it possible to connect Tabulator directly to a RSS Feed?
It would be great to be able to pull RSS feeds into Tabulator.
Simple Feature Request.

Tabulator is by far the best JS grid availale.
Thanks for a great product.

**Comment by olifolkerd** [comment]
Hey @gogulf1954 

Thanks for your kind words about Tabulator.

I have to admit i dont use RSS at all.

Could you go into a bit more details of what you are hoping to achieve here? any example feed?

Cheers

Oli :)

**Comment by 500Foods** [comment]
I don't know that there's a need to implement such a thing directly in Tabulator.  Converting from RSS (XML I suppose) into JSON isn't too difficult.  Here's a JS Fiddle:

https://jsfiddle.net/500Foods/9r81numo/136/

Getting the main fields out of the XML isn't too tough.  What is likely less fun is dealing with CORS.  But for some RSS feeds, this is not an issue.

![image](https://user-images.githubusercontent.com/41052272/218317551-46e11517-925e-497d-8b73-75565facd8bc.png)

**Comment by olifolkerd** [comment]
Following on from @500Foods comments,

If it is simply a matter of making an ajax request, Tabulator can already do that for you using the AJAX module, which will handle all the CORS etc automatically. https://tabulator.info/docs/5.4/data#ajax

You can then use the `ajaxResponse` callback to parse the XML into something that Tabulator can understand. https://tabulator.info/docs/5.4/data#ajax-alter

I hope that helps,

Cheers

Oli :)
