### ISSUE TITLE
cell is not defined in Cell.prototype.setValueProcessData

### ISSUE THREAD

**Issue by silv2015** [olifolkerd/tabulator#412]
Hi!

I just downloaded the latest release today (3.1.1). I really liked all the updates! A lot of thing have been simplified and everything is so more flexible, just like I want it!

As I was testing, I came through a problem though.Not a big one!. I have a custom mutator and custom editor for a cell and when I call success() function in the editor, tabulator.js complains about 'cell is not defined'

The problem was in setValueProcessData and to fix the problem, all I had to do is change the variable 'cell' to 'this' at line 3660 (when calling this.table.extensions.mutator.transformCell) since we are in Cell

Thank you and continue your great work!

**Comment by olifolkerd** [comment]
Hey,

Thanks for the feedback, great spot! i have pushed an update to the master branch, it will be included in the next hotfix release.

Cheers

Oli
