### ISSUE TITLE
Using cursor left/right in list editor freetext mode 

### ISSUE THREAD

**Issue by 500Foods** [olifolkerd/tabulator#4121]
**Describe the bug**
The list editor is fantastic!  I can type in a value using the freetext mode, or I can pick a value out of a list that popups up just how I'd like.  The only issue I seem to have trouble with is in the handling of the cursor when editing the text.  I can enter new text.  I can set the cursor position with a mouse click.  I can double-click a word, which is then selected. I can even use Shift+End to select from the cursor position to the end. But I can't seem to change the cursor position by using left/right cursor keys in the input field.

**Tabulator Info**
5.4.3

**Working Example**
https://jsfiddle.net/500Foods/9r81numo/17/

**To Reproduce**
1. Click on an entry in the second column.
2. Edit the text by typing in something new.
3. Try to cursor left/right to move the cursor to a different spot to edit.
4. No cursor movement takes place.

**Expected behavior**
Would like this to work like a normal input field in this respect.  Might not seem like a huge issue, but I've got some really long text to edit (URLs with lots of parameters) so using the cursor keys would sure make things easier.

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox (desktop), Chrome (desktop)

**Comment by olifolkerd** [comment]
Hey @500Foods 

Oooh that is an interesting one, 

That will be because i block a lot of the default key events to enable list navigation rather than text navigation, but you are totally right, it should be enabled for left right navigation.

I will get a fix in for that on the next patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @500Foods 

Was a really easy fix, i have just pushed it to master and will include it in the patch release in a few days time.

Cheers

Oli :)
