### ISSUE TITLE
Adding editing on all cells at once

### ISSUE THREAD

**Issue by j-guzik** [olifolkerd/tabulator#4122]
My goal is to set the edit mode on all cells of the table BUT in the form that occurs in the cell only when you click on a specific cell. Now it works in such a way that when edit mode is enabled to edit a cell you have to click on it - only then the style changes to edit style. I would like this editing style to be shown immediately on all cells at once and not just on one when clicked. I tried calling this with the cell.edit() function which mimics this, and using dispatchEvent.

```
cells?.forEach((cell) => {
         console.log("cell edit", cell);
         let cellEl = cell.getElement();
         cellEl.dispatchEvent(new Event("click"));
    // // cell.edit();
    });
```
However, I was surprised to see that the end result is to enable this mode only for the last cell in the loop. Is there any option at all to enable such editing or any other way to get the same styles after the click and before (both in edit mode)? The problem with using cell.edit() is also that when you click anywhere the styles disappear anyway. I'm also trying to use a formatter to solve the problem but I don't quite know how to finish it either.

```
column.formatter = function (cell) {
         cell.getElement().classList.add("tabulator-editing");
         return cell.getValue();
        };
```

 Isn't it worthwhile to think about such an edit of the whole tabulator? I'm a bit at a loss as to how to get out of this situation now, because it looks like it's just impossible to do what I need.

**Comment by olifolkerd** [comment]
Hey @j-guzik 

Im unsure what you mean, you can only edit one cell at a time in tabulator.

If you are referring to highlighting editable cells which can be edited, Tabulator already applies a class to cells for this purpose. The class 'tabulator-editable'  is automatically applied to all cells with the possibility of editing.

Checkout the [Styling Docs](https://tabulator.info/docs/5.4/style#css-editors) for more details.

Cheers

Oli :)
