### ISSUE TITLE
Vertical scrolling breaks after repeated addRow()

### ISSUE THREAD

**Issue by TI-AviBerko** [olifolkerd/tabulator#4123]
**Describe the bug**
Vertical scrolling breaks after repeated addRow().

**Tabulator Info**
v5.4.3

**Working Example**
[https://jsfiddle.net/aviberko/zLxwu18y/](url)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Create a table with height to enable virtualdom
2. Add lines with addRow() until the scroll bar appears
3. Scroll up and down
4. Observe that rows at the bottom of the table aren't being rendered

**Expected behavior**
Rows should be rendered correctly.
This jsfiddle example works correctly with v5.4.2

**Screenshots**
![image](https://user-images.githubusercontent.com/15981321/218346411-1427b87e-b5a7-4813-abb8-75c45f524d38.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox, Electron

**Comment by olifolkerd** [comment]
Hey @TI-AviBerko 

I have pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)

**Comment by TI-AviBerko** [comment]
@olifolkerd it works fine now, thank you.
