### ISSUE TITLE
Tabulator version 5.4 - formatter:"rownum" increment not functioning correctly when table.addRow({}, true). Works well with version 5.3

### ISSUE THREAD

**Issue by pmendis** [olifolkerd/tabulator#4124]
**formatter:"rownum"** isn't working as expected on **table.addRow({}, true)**. Pls refer the jsfiddle below.

https://jsfiddle.net/Lksbw96r/ 

Tabulator version 5.4
Web browser: Chrome/Edge
![Capture](https://user-images.githubusercontent.com/16347630/218723233-5f9ce8c7-35f9-47f5-a03a-d964f350adc9.PNG)

Os: Windows 10

**Comment by olifolkerd** [comment]
Hey @pmendis 

Thanks for the headsup, I have pushed a fix for this to master and will include it in this weekends patch release.

Cheers

Oli :)
