### ISSUE TITLE
Horizontal and vertical scrollbars shown with placeholder + fitColumns

### ISSUE THREAD

**Issue by cassiolana** [olifolkerd/tabulator#4125]
**Describe the bug**
Tabulator is showing horizontal and vertical scrollbars with placeholder + fitColumns
The horizontal bar hide the placeholder as well

**Tabulator Info**
5.4.3

**Working Example**
https://jsfiddle.net/7ar2zybu/

**To Reproduce**
Open the link above
Resize fix the horizontal scroll

**Expected behavior**
Do not show any scrollbar

**Screenshots**
![image](https://user-images.githubusercontent.com/1101750/218800675-bb30a0ae-690e-4115-9d08-6eb539e85c43.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome 110.0.5481.77, Firefox 109.0.1

**Comment by olifolkerd** [comment]
Hey @cassiolana 

Thanks for the info, i have pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)
