### ISSUE TITLE
Table header sticky feature

### ISSUE THREAD

**Issue by BaskarR96** [olifolkerd/tabulator#4126]
When i have multiply data on table, without setting table height, while i scrolling on page, i cant guess particular columns because the table header are getting hide on scrolling page

i feel it is better to show secondary table header over the table while scrolling on page, after the primary table header hide after scrolling 

![Screenshot 1](https://user-images.githubusercontent.com/87247127/218935427-8997c2c9-3e89-4ffc-976a-04c4ecfbf2a1.png)
![Screenshot 2](https://user-images.githubusercontent.com/87247127/218935459-bb20a9e3-85c3-45e3-8292-1a09d7602556.png)

**Comment by olifolkerd** [comment]
Hey,

thanks for your feedback

The headers are sticky when you define either a height, min height or max height on the table as it then knows to allow the table to scroll and keep the headers fixed.

If the table is set to expand height indefinitely then keeping the headers fixed when any number of scroll containers outside the table are scrolling would lead to inconsistent behaviour as there is not nesisarily context as to what the "top" of the scrollable area should be as it resides outside the table.

I was also consider it bad UI to have pagination that also scrolls. The point of pagination is to break things into usable chunks. If the user is also having to scroll it suggests you are putting too much data into a single page.

For these reasons this is not a feature I will be looking to add.

Cheers

Oli
