### ISSUE TITLE
Tickbox toggle not working in Safari.

### ISSUE THREAD

**Issue by pankoum** [olifolkerd/tabulator#4127]
The tickbox column does not work in Safari. Clicking does nothing.

I am using Tabulator version 5.4.3.
The issue can be checked directly on tabulator's sample page: https://tabulator.info/examples/5.4#editable

Normal behaviour should toggle between x and tick when clicked.

I am testing this with the following:
 - OS: macOS Ventura 13.0.1 (22A400)
 - Browser: Safari
 - Version: 16.1 (18614.2.9.1.12)

**Comment by olifolkerd** [comment]
duplicate of #4023
