### ISSUE TITLE
Unable to retrieve custom ( user defined)  options in columns using getDefinition()

### ISSUE THREAD

**Issue by Vani8021** [olifolkerd/tabulator#4128]
Reproducible codepen sample 

https://codepen.io/vanisundar/pen/bGxdPdR

**Describe the bug**
Not able to get the user defined options when we try to get the column definition using getDefinition(). This was working fine in 4.9. Having this issue when trying to upgrade to 5.4
**Tabulator Info**
Current tabulator version - 5.4.3

**Working Example**
Previously worked fine with 4.9

https://codepen.io/vanisundar/pen/abaOgmr

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to the sample link given above
2. Click on 'Get Column Definition ' button
3. Check the console 
4. See that `_customOption` is listed among the options in the working example with Tabulator 4.9 whereas it is not  listed in the sample with Tabulator 5.4.3

**Expected behavior**
List the custom option like how it was working with Tabulator 4.9

**Screenshots**
Console log with Tabulator 5.4.3

![image](https://user-images.githubusercontent.com/10887426/219823454-d13c4533-88df-464e-ba9b-01073397dff3.png)

Console log with Tabulator 4.9

![image](https://user-images.githubusercontent.com/10887426/219823436-aa99f779-fc21-4d6e-b765-9914aed4084d.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 109.0.5414.119

Appreciate your help on this issue. Thank you

**Comment by olifolkerd** [comment]
Hey @Vani8021 

Thanks for the headsup,

I have pushed a fix for this to the master branch and will include it in this weekends patch release.

Cheers

Oli :)

**Comment by Vani8021** [comment]
Awesome ...Thanks a  lot @olifolkerd
