### ISSUE TITLE
Editor List : Tab key should validate the selected element

### ISSUE THREAD

**Issue by MetallianFR68** [olifolkerd/tabulator#4129]
I'm a heavy user of key bindings to edit my tables quickly

I think the EditorModule builtin "List" selector should get an upgrade
Indeed, the handling of the TAB key is somekind breaking the key navigation

This behaviour can be tested on the Edit Functionality Overview Demo here
https://tabulator.info/docs/5.4/edit#overview
- Click on the top left cell : Oli bob
- Press Tab to activate the second cell
- Empty the cell to show the full list of choices
- Use the up/down arrow keys to select Germany
- Press Tab to go to the next cell
- the cell remains empty

I think that GERMANY should have been validated
This is the expected behaviour in my opinion

Otherwise, the only way to validate is to press Enter, which interrupt the process because I have to use my mouse to start again

Can you please implement this behaviour ?

**Comment by olifolkerd** [comment]
You have to push enter to select the value from the list otherwise it counts as a cancel from the editor

**Comment by MetallianFR68** [comment]
Hi,

I'm sorry to insist but the default behaviour of any standard SELECT in HTML is to validate the currently selected entry when pressing TAB

Allowing only validation on ENTER is not a rational solution.

ENTER key causes the select to blur() and then you cannot use TAB to select the next input anymore.
You have to use your mouse again to click on the next input.
This breaks anyone wanting to use keyboard only.

In my application, people are required to enter a whole bunch of data
They have to create 100 or 150 rows by minute.
Many of them are only using the keyboard with TAB to switch from one field to another

Try to edit one line on the demo here : https://tabulator.info/examples/5.4?#editable
It's impossible without using the mouse.

**Comment by olifolkerd** [comment]
Hey,

Thankyou for your additional context that is most helpful.

I will consider this mode of operation as a extra param that can be passed to the editor. And will look to add it in the next feature release.

Just a quick caution about your phrasing, this is a freely distributed open source project, no member of this community may insist that any feature be added, people may suggest and recommend and submit pull request if they are keen to see something added. Trying to used directive language to get your way will result in your issue being deprioritized.

Please do not conflate your usage case as being the primary mode of operation of the table, this editor has been in for over a year and widely used and you are the first person to report this as problematic. 

Cheers

Oli

**Comment by MetallianFR68** [comment]
Sorry I didn't want to be rude
English is not my native language and I sometimes don't have the right words

I really appreciate your work on tabulator which is really useful in my project.
I'm also developping a free opensource software

My project is getting donations
I would be glad to share some with you.
Is there a donation page somewhere or a Patreon ?

**Comment by olifolkerd** [comment]
Hey @MetallianFR68 

No problem, translation is rarely perfect.

Dont feel you have to donate because of this misunderstanding. All good here

But if you do wat to donate, have a look at the [Donation Page](https://tabulator.info/community/support) on the website for more details.

Looking into this issue futher, it will be a bit more complex, becuase the list editor will have lost focus at the point tab is pressed, so i will have to refocus on it first then trigger the tab again, but should be doable.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @MetallianFR68 

I have pushed an update for this to the 5.5 branch and will include it in the march feature release.

Cheers

Oli :)
