### ISSUE TITLE
Horizontal scrollbar appears with fitColumns and visibility toggle in Chrome

### ISSUE THREAD

**Issue by Andrisa1** [olifolkerd/tabulator#4131]
**Describe the bug**
Horizontal scrollbar appears with fitColumns after visibility toggle

**Tabulator Info**
5.4.4

**Working Example**
https://jsfiddle.net/2p4cqxoh/

**To Reproduce**
1. Go to https://jsfiddle.net/2p4cqxoh/
2. Click on addRow multiple times until table is filled, verify that horizontal scrollbar doesn't appear
3. Click on "toggle" twice
4. Horizontal scrollbar appears in table

**Expected behavior**
Horizontal scrollbar shouldn't appear as fitColumns is used

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version 109.0.5414.119 (Official Build) (64-bit)

**Additional context**
This might be related with https://github.com/olifolkerd/tabulator/issues/4130

**Comment by olifolkerd** [comment]
Hey @Andrisa1 

As per your previous bug, the layout is only calculated on redraw of the table due to resize or complete data or column replacement.

If you want to trigger the redraw yourself then call the `redraw` function after you have made the change. If the function returns a promise you may need to wait for it to resolve before calling the redraw.

Cheers

Oli :)

**Comment by Andrisa1** [comment]
Hi @olifolkerd 

I did call redraw() here(in fiddle) and after that table appeared fine. Scrollbar appears only after visibility changes. Should redraw() be called also after visibility changes?

Regards,
Andris

**Comment by olifolkerd** [comment]
It is only needed after the update, but the function is asynchronous and returns a promise so you must call it after the function resolved not immediately after you call it

**Comment by Andrisa1** [comment]
Even with that horizontal scrollbar appears: https://jsfiddle.net/8x65pzyo/
