### ISSUE TITLE
feat: option to display calculation columns in row for grouped rows

### ISSUE THREAD

**Issue by lukecotter** [olifolkerd/tabulator#4132]
*Is your feature request related to a problem? Please describe.**
The extra row for the column calculation in a group take up quite a bit of room, it would be great if we could display them in line.

**Describe the solution you'd like**
I think it would be a little neater to display the group column calculations in row instead of a separate row, having this as a built in feature would mean the columns would resize correctly etc.
I would be more than happy if it was an additional option.

I have done an approximation by doing my own calcs and adding the inline via `groupHeader:` but obviously this would not play nice with things like the column resizing. I think it would be awesome to add this as a built in feature.

**Additional context**
**Current** 
![group-sum-row](https://user-images.githubusercontent.com/4013877/220884566-491d9897-b6f2-492f-8b2c-81f55e2eb189.png)

**Ideal**
![group-sum-inline](https://user-images.githubusercontent.com/4013877/220884579-024887d0-80e3-453e-bbfb-931d7197f2d1.png)

**Comment by olifolkerd** [comment]
Hey @lukecotter 

Thanks for the suggestion, but in this case i think this will only work in a neiche set of layout situations, so would be up to the dev to add in themselves depending on usage case.

Cheers

Oli :)

**Comment by lukecotter** [comment]
@olifolkerd 
If I raised a PR to add this behind an opt in flag would you accept it? Or do you definitely want it to be custom?

**Comment by olifolkerd** [comment]
Hey, if you want to submit a PR to submit this as an optional feature I'd be happy to accept it as long as it didn't break any existing functionality

Cheers

Oli :)
