### ISSUE TITLE
feat: renderer performance improvements

### ISSUE THREAD

**Issue by lukecotter** [olifolkerd/tabulator#4133]
*Is your feature request related to a problem? Please describe.**

I have been playing with some changes in a fork which generally improve renderer performance for both fixed height and dynamic height cases.  

**Describe the solution you'd like**
Here is a summary of changes in the PR

- BasicHorizontal and BasicVertical Render will add to dom in bulk which reduces reflow
- Add elements to the dom in bulk instead of one at a time in VirtualDomVertical
- Only reRenderInPosition if the table height changes

**Comment by olifolkerd** [comment]
Hey @lukecotter 

Thanks very much for the PR, I think it is a great idea.

I have put a couple of notes on the PR to discuss.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Closing this as it was included in the 5.5 release.

Cheers

Oli :)
