### ISSUE TITLE
rowTap event fires when table is merely scrolled

### ISSUE THREAD

**Issue by rbubley** [olifolkerd/tabulator#4135]
**Describe the bug**
When using Safari on an iPhone, and scrolling the table, the 'rowTap' event is fired when you lift your finger from the scroll.

**Tabulator Info**
- Which version of Tabulator are you using? 5.4.4

**Working Example**
<https://jsfiddle.net/Bubz0/8edporqy/6/>

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to '<https://jsfiddle.net/Bubz0/8edporqy/6/>'
2. Scroll the table upwards
3. See alert, indicating error.

**Expected behavior**
rowTap event is not fired on a scroll, only on an explicit tap.

**Smartphone (please complete the following information):**
 - Device:iPhone11
 - OS: iOS16.3.1
 - Browser Safari

**Comment by olifolkerd** [comment]
Hey @rbubley 

Thanks for the headsup, i have pushed a fix for this to the 5.5 branch and will include it in the march release.

Cheers

Oli :)
