### ISSUE TITLE
Second money formatting for accounting style

### ISSUE THREAD

**Issue by khaos13** [olifolkerd/tabulator#4136]
Accounting formatting requires a different style for showing negatives, surrounded by parentheses. I think a lot of people would benefit from this style as well since it is a fairly common style and it only requires another format type in Tabulator. I have written code below. This works with IE and even though IE is dead people still use IE mode in Edge, we do sadly. I hope this can be added as it will also allow easier upgrades.

    moneyParen: function money(cell, formatterParams, onRendered) {
            var floatVal = parseFloat(cell.getValue()),
                number,
                integer,
                decimal,
                rgx;

            var decimalSym = formatterParams.decimal || ".";
            var thousandSym = formatterParams.thousand || ",";
            var symbol = formatterParams.symbol || "";
            var after = !!formatterParams.symbolAfter;
            var precision = typeof formatterParams.precision !== "undefined" ? formatterParams.precision : 2;

            if (isNaN(floatVal)) {
                return this.emptyToSpace(this.sanitizeHTML(cell.getValue()));
            }

            number = precision !== false ? floatVal.toFixed(precision) : floatVal;
            number = String(number).split(".");

            integer = number[0];
            decimal = number.length > 1 ? decimalSym + number[1] : "";

            //var isNeg = (integer.includes("-"));
            var isNeg = (integer.indexOf("-")>-1);

            if (isNeg === true) { integer = integer.replace("-", ""); }

            rgx = /(\d+)(\d{3})/;

            while (rgx.test(integer)) {
                integer = integer.replace(rgx, "$1" + thousandSym + "$2");
            }

            var retPt1 = after ? integer + decimal + symbol : symbol + integer + decimal;

            return isNeg ? "(" + retPt1 + ")" : retPt1;
        },

**Comment by olifolkerd** [comment]
Hey @khaos13 

Thanks for getting in touch.

I think that is a great idea, but im not sure there is a need for a whole new formatter for this, a slight tweak to the existing formatter to allow for the accounting format should needed.

Could you show me a sample of exactly how aa negative number should look? is it essentially `(1)` instead of `-1`?

We could just tweak the existing formatter so that if you passed a value of `true` to the `negativeSign` option, it wrapped negatives in brackets instead. how does that sound?

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @khaos13 

Thanks for your kind words, it is great to hear people enjoying using Tabulator.

I have have just pushed an update to the 5.5 branch to add this feature, which will be included in next months feature release.

You will be able to enable it by passing a value of `true` to the `negativeSign` formatter param

```js
{title:"Example", field:"example", formatter:"money", formatterParams:{
    negativeSign:true, //show negative numbers wrapped in parentheses
}}
```

Cheers

Oli :)
