### ISSUE TITLE
movable + editable columns issue

### ISSUE THREAD

**Issue by Tiuipuv** [olifolkerd/tabulator#4138]
**Describe the bug**
When columns are set to movable and editable, highlighting text with the mouse becomes difficult.

**Tabulator Info**
Tabulator v5.4.4

**Working Example**
https://jsfiddle.net/87t492wq/2/

**To Reproduce**
Attempt to rename the column by selecting and dragging the text with your mouse. It will deselect, and start moving the column.

**Expected behavior**
Mouse drags started outside of the textbox (but on the column) move the column order. Mouse drags started inside of the textbox highlight the column name, but do not move the column order

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Browser: Chrome
 - Version: 110

**Comment by olifolkerd** [comment]
Hey @Tiuipuv 

Thanks for the headsup, i will aim to get that fixed in this months feature release.

Cheers

Oli :)

**Comment by david-fiaty** [comment]
Is there any progress on this? I'm having the same issue with the latest master branch version.

**Comment by olifolkerd** [comment]
Hey @Tiuipuv 

Thanks for the headsup, i have pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)

**Comment by Tiuipuv** [comment]
Thanks @olifolkerd!
