### ISSUE TITLE
Not getting correct selected data

### ISSUE THREAD

**Issue by Leopala** [olifolkerd/tabulator#414]
Hi Oli,
I am having a weird behavior when I call "getSelectedData" after "selectRow" and deselecting some rows.
The thing is that I am not getting the exact selected data when I first select all rows and then deselect one or more rows. It seems like when one row is selected by selectRow and then deselected, it responds backwards.
I've created an example: https://jsfiddle.net/rge4fedn/, please take a look.
The steps to reproduce the error would be:
1) Select all rows
2) Deselect row 2 (or any)
3) Show selected rows

Regards,

Leo.

**Comment by sigmer** [comment]
I'm hitting the same bug.

**Comment by olifolkerd** [comment]
Hey,

Good spot, there was an in-precise comparison in the deselect function.

i have pushed an update to the master branch to fix this. it will be included in next months 3.2 release

Cheers

Oli
