### ISSUE TITLE
Tree structure callback section is wrong

### ISSUE THREAD

**Issue by aurelien-leloup** [olifolkerd/tabulator#4144]
**Website Page**
[A link to the page with the issue](https://tabulator.info/docs/5.4/tree)

**Describe the issue**
The link leads to the callback page, but it should probably lead to [this one](https://tabulator.info/docs/5.4/events#tree) 
It is very minor, but it took me time to figure out why there were no callbacks for tree structure because of this.

**Comment by olifolkerd** [comment]
Hey @aurelien-leloup 

Thanks for the headsup, i have pushed a fix for the website to the 5.5 branch and will include it in the docs update later today with the 5.5 release.

Cheers

Oli :)
