### ISSUE TITLE
Hiding a column programmatically leaves empty space in table layout

### ISSUE THREAD

**Issue by bennidi** [olifolkerd/tabulator#4145]
I am sorry, that I can not allow myself the time to extract a working JSFiddle from my current code at this point.
Maybe you still want to consider my report. In case it should be worth an investigation from your side, I might be able to take the time to create one.

I am seeing this issue, when hiding a column programmatically with #hideColumn(). The layout of the visible columns is not recalculated which results in empty space being occupied. Maybe I am not setting some properties correctly on the table  (I use layout=fitColumns)

I did not find anything about this in the documentation. It may as well be a case of misuse but probably a bug. I see this issues with and without column grouping.

**Comment by olifolkerd** [comment]
Hey,

Thanks for getting in touch, this is the intended behaviour.

You can force a redraw If you want by calling the redraw(true) function after toggling the column visibility

Cheers

Oli

**Comment by bennidi** [comment]
Thank you very much. I had hoped so. Anyhow, maybe mention this in the docs at the section about hiding columns?
