### ISSUE TITLE
Header row does not align with the rest of the table in the "Modern Theme"

### ISSUE THREAD

**Issue by lzettel** [olifolkerd/tabulator#4147]
**Describe the bug**
The header row of the table in the modern theme is not aligned with the rest of the table, because there is a padding-left of 10px.

**Tabulator Info**
Version: 15.4

**Working Example**
There is no need for a jsfiddle, because it can be seen on the official documentation website at the examples section: https://tabulator.info/examples/5.4#theming-modern

**To Reproduce**
1. Go to https://tabulator.info/examples/5.4#theming-modern
2. Hover over header cells

**Expected behavior**
Be aligned

**Screenshots**
![image](https://user-images.githubusercontent.com/33696143/224702670-35330817-f1b7-4656-8607-72dfc5e41e9b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 / Windows 11
 - Browser: Firefox and Chrome

**Additional context**
This can be fixed with:
```css
.tabulator .tabulator-header {
  padding-left: 0 !important;
}
```

**Comment by amolpawar** [comment]
Hi @lzettel, I would like to fix this issue. Could you please assign it to me.

**Comment by olifolkerd** [comment]
Hey @lzettel 

Thanks for the PR,

Unfortunately it looks like you have tried to adjust the spacing for parenthesis on every line of the src file. A pr should only contain the functional change you are making, please do not try and update the code styling, this makes the commit very hard to read.

I would normally feed this back and give you a chance to correct, but im just about to make the v5.5 release so i will make the change directly in the 5.5 branch and close this PR.

If you are on the discord server, drop me a message and i will give you the contributor badge for your user.

Thanks for your contribution

Cheers

Oli :)
