### ISSUE TITLE
Invalid config in datatree

### ISSUE THREAD

**Issue by lekoala** [olifolkerd/tabulator#4148]
I was recently playing around with the datatree module and I've seen this line

I don't have an actual issue to show, but I believe it should simply be `config = row.modules.dataTree;` 

https://github.com/olifolkerd/tabulator/blob/0a75da61b24625015483e1f2a87f1f224d1478b2/src/js/modules/DataTree/DataTree.js#L308

Just wanted to let you know ;-) feel free to close or ignore this issue if i'm wrong

**Comment by olifolkerd** [comment]
Hey @lekoala 

Good spot, i have pushed a fix to the 5,5 branch and will include it in todays release.

Cheers

Oli :)
