### ISSUE TITLE
Add a cellEditCancelling event

### ISSUE THREAD

**Issue by salfakir** [olifolkerd/tabulator#4149]
I'm trying to allow users to select another cell to edit and have the current cell being edited to be saved. However, I could not find an event in tabulator that would fire before my custom editor is removed and the cell is returned to normal.
cellEditCancelled fires after the cell has been restored.
I'm currently trying to do this through pointerdown event, but its not working too well.
It would be a nice feature to have, thanks :)

**Comment by olifolkerd** [comment]
Could you explain why that event would be nessesary, what does it offer that the existing event does not?

Generally Tabulator only has -ing events for actions that take a lot of processing in the middle before they are resolved. Cancelling an edit is simply the removal of the editor and restoration of the formatter.

As the event cannot be blocked there is little that could be done during it and the editor is about to be destroyed so changing anything in it would not be worth while.

If they have cancelled the edit then the value hasn't changed so there is nothing to save. If they have changed the value then the cellEdited event would be fired which would include the update value of the cell that you could save

Cheers

Oli

**Comment by salfakir** [comment]
Thanks for the reply, 
What I had in mind is to do a success(currentValueOfEditor) in the cellEditCancelling event, but I had troubles doing the same in cellEditCanceled event since the editor was removed, but im now i figured a way to do it through the cellEditCanceled event by having a global variable to keep track of the editor's value. so i guess its pointless to add a new event.
