### ISSUE TITLE
How do I get the current row id on rowClick

### ISSUE THREAD

**Issue by sanleong** [olifolkerd/tabulator#415]
Hi,
I had tried everything but only get undefined values. How do I get the id of the clicked row on version 3.1?
Thanks in advance.
Regards

**Comment by olifolkerd** [comment]
Hey,

You can get the index with the ***getIndex*** function:

```js
$("#example-table").tabulator({
        rowClick:function(e, row){
        //e - the click event object
        //row - row component

        var index = row.getIndex();
    },
});
```

Cheers

Oli

**Comment by sanleong** [comment]
Hi Oli,

Sorry to bother you, but for some reason it doesn't work for me. I only get undefined return... I also keep receiving this error after implementing ver 3.1.

Uncaught TypeError: t.widget(...) is not a function
    at tabulator.min.js:4
    at tabulator.min.js:4
    at tabulator.min.js:4


Here's my table, if you have time and spot something out or order.


 $("#current-table").tabulator({

                        height: 400,
                        selectable: true,
                        columns: [
                                    { title: "Select current channel:", field: "Name", sorter: "string", width: 690, headerFilter: "input" }
                        ],
                        rowClick: function (e,  row) {

                            var index = row.getIndex();
                            alert(index);
                            if (currentCh == undefined || currentCh == "") {
                                currentCh = e.currentTarget.innerText;
                            } else {

                                if (currentCh !== e.currentTarget.innerText) {
                                    currentCh = e.currentTarget.innerText;
                                } else {
                                    currentCh = "";
                                }
                            }
                            $("#solrRequest").html("<p>Presets selected: {" + JSON.stringify(satSel) + "}</p><p>Current selected: {" + JSON.stringify(currentCh) + "}</p>");
                            $("#selSatCh").html("Presets selected: <b>{" + JSON.stringify(satSel) + "}</b><br>Current selected: <b>{" + JSON.stringify(currentCh) + "}</b>");
                        }
                    });


Any help would be really appreciated.

________________________________

**Comment by olifolkerd** [comment]
Are you actually setting the index on your data? by default tabulator will use the ***id*** column of the data you pass into the table.

If you want to use a different field, you can set the ***index*** property in your constructor to the name of that field.

Cheers

Oli

**Comment by sanleong** [comment]
Man,
I thought that tabulator generates the id. Thanks a lot for your help. Now I got my id and table working like a charm.
Really appreciate it.

**Comment by koosvanderkolk** [comment]
Having the same issue (3.2.2.). My data has no index column. 

The documentation says: 

> If the index is missing from the provided data, tabulator will generate one from the position of the data in the original array.

But apparently, this is not the case. Looking into the code, I also don't see how this should work, as getIndex seems to be quite detached from the overall data array.

**Comment by sanleong** [comment]
Hi Koos,
You have to add your own index in your data. On versions previous to 3 Tabulator has it's own index, but not anymore.

Regards,
Gilberto Leon

On Aug 7, 2017, at 8:21 AM, Koos van der Kolk <notifications@github.com<mailto:notifications@github.com>> wrote:


Having the same issue (3.2.2.). My data has no index column.

The documentation says:

If the index is missing from the provided data, tabulator will generate one from the position of the data in the original array.

But apparently, this is not the case. Looking into the code, I also don't see how this should work, as getIndex seems to be quite detached from the overall data array.

**Comment by olifolkerd** [comment]
@sanleong is right, it looks like the documentation wasnt updated with the 3.0 release, i will get an update in for that in the next couple of days

**Comment by olifolkerd** [comment]
I have now removed the outdated line from the documentation.

To add a bit of clarity as to why this is now the case, Tabulator used to need a unique row index to be able to link a row data back to its DOM element. From version 3.0 onwards the Row Component object was added that encapsulates both the row data, its state, configuration and DOM element, so a unique index is no longer necessary.

If you would like to make Tabulator generate a unique ID for each of your rows that is no problem, i can show you how to created a mutator to do that for you.

Could you explain why you need this though, as there is likely a cleaner solution to your issue.

Cheers

Oli

**Comment by koosvanderkolk** [comment]
Dear Oli,

Thanks for your reply! In my case, each displayed item has a reference to an entity in the back-end. In the 'parent' library I use (the library embedding your great tabulator plugin in my app) there is a mapping between the index in the original data array and the entities in the back-end. 

Of course I could change this 'parent' library as well, but that would be much more work than 

```
getIndex: function getIndex() {
  var index;
  if (typeof row.getData(true)[row.table.options.index] !=='undefined'){
    index = row.getData(true)[row.table.options.index];
  }else if(row.parent && row.parent.rows) {
    index = row.parent.rows.indexOf(row);
  }
  return index;
},
```

Do you expect problems with this new getIndex function?

**Comment by olifolkerd** [comment]
Hey,

If your data is filtered or sorted then its order in the array returned by the ***getData*** function will change so this method is not safe.

If you are linking to data on your server then it is considered best practice and i would say essential that the reference id for your data be passed from your server in the data as there is no other way to ensure referential integrity.

Cheers

Oli

**Comment by koosvanderkolk** [comment]
Ok thanks!
