### ISSUE TITLE
FitData does not take all rows into account when computing the column width

### ISSUE THREAD

**Issue by o485** [olifolkerd/tabulator#4150]
**Describe the bug**
The fitData column layout modes do not take all rows into account when computing the column width, only the top rows are used. As a result, wider cells further down in the table do not fully fit in the column.

**Tabulator Info**
- Which version of Tabulator are you using? Latest, 5.4.4

**Working Example**
[https://jsfiddle.net/0zm4cqan/7/](url)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to [https://jsfiddle.net/0zm4cqan/7/](url)
2. Scroll down to the bottom of the table where the cells contain longer entries
3. See that the column width is not fitting the data

**Expected behavior**
For the column width to take _all_ data into account when setting the width not only the first rows. 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 111

**Comment by olifolkerd** [comment]
Yes, it only takes the visible rows into account, this is because Tabulator uses a virtual dom, which only creates rows as they are first scrolled into view. This is how tabulator can handle large numbers of rows without blocking the browser

Therefore this is the intended behavior.

Cheers

Oli
