### ISSUE TITLE
offline  document

### ISSUE THREAD

**Issue by yuandian-m** [olifolkerd/tabulator#4153]
Hello! I am a Chinese developer,can you provide a document repository?  I would be very grateful to you！

**Comment by olifolkerd** [comment]
All of Tabulators documentation can be found on tabulator.info

**Comment by yuandian-m** [comment]
Due to my work, I cannot view 'tabulator.info' online, so I would like to a document that I can view in an offline environment.

**Comment by olifolkerd** [comment]
Sorry, as is fairly standard these days with most libraries, due to the complex nature of the docs, they are only available online

**Comment by zuopf769** [comment]
where is docs github repo
