### ISSUE TITLE
Progress formatter - formatterParams legend does not show toLocaleString()

### ISSUE THREAD

**Issue by 8483** [olifolkerd/tabulator#4154]
**Describe the bug**
toLocaleString() does not work in leged, in formatterParams, in progress formatter.

**Tabulator Info**
5.4

**Working Example**
https://codesandbox.io/s/festive-ben-rcf1zr?file=/src/index.js

**To Reproduce**
None

**Expected behavior**
toLocaleString() to show thousands separators.

**Screenshots**
![foo](https://user-images.githubusercontent.com/16456606/230078001-33a9f9ac-2ef6-4c69-8695-dd908fcdbeb1.jpg)

**Code**

```js
new Tabulator("#app", {
  height: "100%",
  data: data,
  layout: "fitDataFill",
  groupBy: "ym",
  groupStartOpen: true,
  groupToggleElement: "header",
  columnCalcs: "both",
  columnVertAlign: "bottom",
  columns: [
    {
      title: "Sales",
      field: "value",
      formatter: "progress",
      formatterParams: {
        color: "red",
        min: 0,
        max: 10000000,
        legend: (value) => {
          console.log(value);
          return value + "%";
        }
      }
    },
    {
      title: "Sales",
      field: "value",
      formatter: "progress",
      formatterParams: {
        color: "red",
        min: 0,
        max: 10000000,
        legend: (value) => {
          console.log(value);
          return value.toLocaleString();
        }
      }
    }
  ]
});
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 111.0.5563.147 (Official Build) (64-bit)

**Comment by olifolkerd** [comment]
Hey @8483 

The `value` argument is just the data that comes from the cell, in whatever data type it was added in. there is nothing special going on there, i would suggest that you inspect the type of data passed in. this isnt part of tabulator as such.

Cheers

Oli :)

**Comment by 8483** [comment]
Thanks for pointing me in the right direction.

It turns out that the value was of type string, even though it's a number. So I just converted it back to a number.

```js
legend: (value) => {
    return Number(value).toLocaleString();
}
```
