### ISSUE TITLE
Bootstrap 5 Theme striped forced

### ISSUE THREAD

**Issue by TanguyPa** [olifolkerd/tabulator#4158]
**Describe the bug**
When using tabulator with the theme for bootstrap 5, I have a problem with the lines having the default stripe style.
The concerned rows have the "tabulator-row-even" class while the table has not been defined with the "table-striped" class

**Tabulator Info**
Using tabulator 5.4.4 with bootstrap 5.2.3
**Working Example**
https://codesandbox.io/s/javascript-forked-j1c3h1)

**To Reproduce**
Creating table using tabulator and bootstrap 5 theme
**Expected behavior**
Default table style (like this https://getbootstrap.com/docs/5.2/content/tables/#overview , not striped) 

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser Microsoft Edge (chromium)
 - Version : 112.0.1722.34

**Comment by olifolkerd** [comment]
This no longer appears to be an issue, closing ticket.

Cheers

Oli :)
