### ISSUE TITLE
validationFailed event is firing multiple times for a single validation failure

### ISSUE THREAD

**Issue by AaronAMcGuire** [olifolkerd/tabulator#4159]
**Describe the bug:**
I am trying to use the `.validationFailed` event to capture when a validation rule has failed so that I can invoke a component to popup a message to the user. However, if the initial edit attempt is invalid the event is fired at least 3 times. Any subsequent edit and attempts to step off the same field only trigger the event once.

**Tabulator Info:**
- 5.4.4

**Working Example:**
[CodePen Example](https://codepen.io/aaronmcg/pen/QWZyMoG?editors=1111)

**To Reproduce:**

1. Go to [Codepen Mockup](https://codepen.io/aaronmcg/pen/QWZyMoG?editors=1111)
2. Click on any cell in the "**name**" column to enable the editor
3. type 31 characters into the cell or paste the following text "**Lorem ipsum dolor sit amet, consectetur adipiscing**"
4. try to click outside of the cell
5. check the console you will see 3 console logs of the same cell instance

**Expected behavior:**
I believe the expected behaviour should be that only a single `validationFailed` event is triggered so therefore you should only see a single console log when trying to click outside of the cell

**Desktop:**
 - OS: Windows
 - Browser: Chrome
 - Version 112.0.5615.50 (Official Build) (64-bit)

**Comment by olifolkerd** [comment]
Hey @AaronAMcGuire 

I have added some debounce logic to prevent some of the duplicate events, however you may still see some duplication due to the way the blur event is triggered on an input, as the mousedown and up events can both trigger a blur which can cause the input to need to validate multiple times.#

Cheers

Oli :)
