### ISSUE TITLE
remote sort

### ISSUE THREAD

**Issue by halittiryaki** [olifolkerd/tabulator#416]
I'm getting a "table is not defined" exception when trying to sort a column and remote sorting is turned on by the option `ajaxSorting:true`

`tabulator.min.js:2 Uncaught ReferenceError: table is not defined
    at i.sorterRefresh (tabulator.min.js:2)
    at HTMLDivElement.<anonymous> (tabulator.min.js:5)
    at HTMLDivElement.dispatch (1_jquery.min.js:8)
    at HTMLDivElement.g.handle (1_jquery.min.js:8)`

any ideas?

**Comment by olifolkerd** [comment]
Could you post a copy of your tabulator constructor and the code you are using to sort the table so i can test.

Cheers

Oli

**Comment by olifolkerd** [comment]
which version of tabulator are you running?

**Comment by halittiryaki** [comment]
your question which version I'm running made me get the latest build (3.1.1) which solved the issue. The version before which had this issue was 3.0.0.

Thanks for the support and this great component anyways.
