### ISSUE TITLE
Horizontal Scroll Lost On Header Filter Or Sort

### ISSUE THREAD

**Issue by aleruizj** [olifolkerd/tabulator#4161]
'll start by saying this is an awesome project and appreciate all of the work that has gone into it.

Describe the bug
When filtering or sorting a table that has enough columns and data to horizontal scroll, if you scroll to the far right column and sort/filter it will return the horizontal scroll position back to the far left (0) position.

Tabulator v5.4 the problem is still here. with vue

const peticionapi = async (url, config, params) => {
  return new Promise(function (resolve, reject) {
    props.apicall
      .get(props.url, params)
      .then((data) => {
        resolve(data.data);
      })
      .catch((error) => {
        reject(error);
      });
  });
};

tabulator.value = new Tabulator(tableRef.value, {
    ajaxURL: "https://:ejemplo.com",
    height:"500px",
    ajaxRequestFunc: peticionapi,
    filterMode: "remote",
    sortMode: "remote",
    printAsHtml: true,
    printStyled: true,
    progressiveLoad:"scroll",
    paginationSize: 10,
    layout: "fitColumns",
    responsiveLayout: "collapse",
    placeholder: "No matching records found",
    columns: props.columns,
  });

**Comment by karpiq24** [comment]
I'm having the same issue.

**Comment by dev-oiram** [comment]
The same issue here, any help will be appreciated 🙏

**Comment by olifolkerd** [comment]
Hey @aleruizj 

Please submit a JS Fiddle that demonstrates the issue

Cheers

Oli :)
