### ISSUE TITLE
Placeholder not disappearing when pagination and maxHeight are set

### ISSUE THREAD

**Issue by sergehauri** [olifolkerd/tabulator#4162]
**Describe the bug**
When pagination and maxHeight are set, the placeholder does not disappear and no data is shown on setData().

**Tabulator Info**
5.4.4
The issue does not happen with 5.4.3

**Working Example**
https://jsfiddle.net/bqg0hf1n/1/

**To Reproduce**
1. Run the JS Fiddle
2. Switch version to 5.4.3 to see the expected behavior

**Expected behavior**
When setting data with setData, the placeholder disappears and the data is shown

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version 112.0.5615.49

**Comment by arpsmack** [comment]
Hah that's pretty funny. Something causes the page size to get set to Infinity, resulting in this hilarious loop from -Infinity to NaN, which... doesn't go so well.

![image](https://user-images.githubusercontent.com/163742/236956296-8c1cec60-cf97-4409-9b99-b62d390a1e7d.png)

**Comment by olifolkerd** [comment]
This no longer seems to be replicable, so closing for now.

Cheers

Oli :)
