### ISSUE TITLE
Improve error message

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#4163]
*Is your feature request related to a problem? Please describe.**
```
Unable to process data due to invalid data type 
```

**Describe the solution you'd like**
Rephrase this error message like this:
```
Unable to process incoming data. Expecting array of rows
```

**Describe alternatives you've considered**
This is not so easy to guest about which data and type it means. For me it was not clear which `data` and what `data type`.

**Comment by olifolkerd** [comment]
Hey @KES777 

It already does, it is a multi line error message that shows the type it was expecting and what was received

Cheers

Oli :)
