### ISSUE TITLE
Can not find documentation how methods was renamed

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#4166]
**Describe the issue**
I am moving from Tabulator v4.9.3 to 5.4.4 and can not find where these options disappeared:
`newRowPosition`, `ajaxError` etc.

Are there description how these was changed?

**Comment by KES777** [comment]
Found `dataLoadError` event, but there is not description for `DataLoaderError` callback
![image](https://user-images.githubusercontent.com/799021/232619528-ee07642d-8fb2-4c6a-bcb8-f4d8fc95eac2.png)

Though it is at source:
![image](https://user-images.githubusercontent.com/799021/232619604-a5bc6a95-0134-4bea-b9e4-22a8c11f75e3.png)

Would be nice to have a documentation page with a description for all `defaultOptions`

**Comment by KES777** [comment]
Seems new version does not provide this callback:
![image](https://user-images.githubusercontent.com/799021/232621631-acae2c0d-5ea1-4b4b-bfb8-992b11865fcf.png)

In compare to old version:
![image](https://user-images.githubusercontent.com/799021/232622126-185d2fd2-081e-4c7e-9f33-39e44174b777.png)

Is there a way to handle ajaxErrors?

**Comment by olifolkerd** [comment]
https://tabulator.info/docs/5.0/upgrade
