### ISSUE TITLE
The code assignment in footerElement fails.

### ISSUE THREAD

**Issue by cacuestai** [olifolkerd/tabulator#4169]
Hello:

When using backquotes and leading newlines, the code assignment in footerElement fails.

Versión 5.4.4

Link error: https://codepen.io/cacuestai/pen/yLRVdVb

Steps:
1. Run the code as it appears. The table will not be displayed. Error: _caught (in promise) DOMException: Failed to execute 'querySelector' on 'Document': `'<div> ...</div>'` is not a valid selector. FooterManager.js:46_
2. Comment lines 17 through 18 and uncomment line 20. The table will display correctly.

Happens in all modern browsers.

Thank you very much for your attention.

Carlos

**Comment by olifolkerd** [comment]
Hey @cacuestai 

This is because the code you are providing is not a valid `innerHTML`  string. if you remove the empty space and carriage returns at the start and end, it will work just fine.

Cheers

Oli :)

**Comment by cacuestai** [comment]
Hello:

However, keep in mind that html does not generate errors for extra spaces, tabs and line breaks. A simple trim() from Tabulator could correct this detail.
