### ISSUE TITLE
Can not make column more narrow than 40px

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#4170]
**Describe the bug**

![image](https://user-images.githubusercontent.com/799021/233813936-d2c7c700-d570-4625-971a-05a47170fc8c.png)

I tried to setup to 20px and 5px:

![image](https://user-images.githubusercontent.com/799021/233813992-c803b006-9b48-4cc0-9f0b-821cb5036a35.png)

I even can not do columns more narrow with help of mouse.

**Tabulator Info**
- 5.4.4

**To Reproduce**
```javascript
{
  headerSort: false,
  formatter:printIcon, width:20, hozAlign:"center", cellClick:function(e, cell){
    alert("Printing row data for: " + cell.getRow().getData().name)
  }
}
```

**Expected behavior**
Column should be narrow.

**Comment by arpsmack** [comment]
Did you try setting `minWidth`? The default `minWidth` for a column is 40px.

If you have several columns that need small widths, I'd set it in the `columnDefaults` for your table: https://tabulator.info/docs/5.4/columns#defaults
