### ISSUE TITLE
Date editor: incorrect description

### ISSUE THREAD

**Issue by jaguarxii** [olifolkerd/tabulator#4172]
**Website Page**
Date editor(https://tabulator.info/docs/5.4/edit#editor-date)

**Describe the issue**
Instead of "date editor" displays "progress bar".

![image](https://user-images.githubusercontent.com/8013436/234311418-a6662e83-1335-4250-bdd0-c231e2f8be88.png)

**Comment by olifolkerd** [comment]
Hey @jaguarxii 

Thanks for the headsup, i have pushed a fix to the 5.5 branch and will include it in the website update later today.

Cheers

Oli :)
