### ISSUE TITLE
Dynamically change frozen column to unfrozen trigger error

### ISSUE THREAD

**Issue by pianetarosso** [olifolkerd/tabulator#4173]
**Describe the bug**
Hi, I've added an option in the header's context menu to froze / unfroze the columns. 
When transitioning from **frozen** to **unfrozen** status, I get this error in console:

```
tabulator.min.js:2 Uncaught TypeError: Cannot set properties of undefined (setting 'position')
    at ae.layoutElement (tabulator.min.js:2:242162)
    at tabulator.min.js:2:240795
    at Array.forEach (<anonymous>)
    at ae.layoutColumnPosition (tabulator.min.js:2:240374)
    at ae.layout (tabulator.min.js:2:241457)
    at tabulator.min.js:2:83426
    at Array.forEach (<anonymous>)
    at y._dispatch (tabulator.min.js:2:83402)
    at c.dispatch (tabulator.min.js:2:1119)
    at c.redraw (tabulator.min.js:2:42231)
```

This is the code I use in the context menu:
```
 const columnDef = column.getDefinition();
 column.updateDefinition({
        frozen: !columnDef.frozen
 });
```

**Tabulator Info**
- Which version of Tabulator are you using? **5.4.4**

**Working Example**

**Codepen**: [https://codepen.io/pianetarosso/pen/MWPmQNg](https://codepen.io/pianetarosso/pen/MWPmQNg)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Open the link [https://codepen.io/pianetarosso/pen/MWPmQNg](https://codepen.io/pianetarosso/pen/MWPmQNg)
2. Open the browser's console
3. Right click on Header **Name** field
4. Click **Froze / Unfroze Column**
5. Repeat point 3 and 4
6. See error in console

**Expected behavior**
The column change its status from **frozen** to **unfrozen** without triggering an error 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: 112.0.5615.138

**Additional context**

**Comment by olifolkerd** [comment]
Hey @pianetarosso 

Thanks for the headsup,

I have pushed a fix for this to the 5.5 branch and it will be included in todays release.

Cheers

Oli :)
