### ISSUE TITLE
generalAjaxDelay - wait for the last ajax request

### ISSUE THREAD

**Issue by alvise** [olifolkerd/tabulator#4177]
It could be useful to have a general delay for every ajax request made by tabulator.
Let's say **generalAjaxDelay**  that works like "headerFilterLiveFilterDelay", waiting 300ms and then fetching only the last url requested.

I know there is "progressiveLoadDelay" but it works only in progressive mode and its not really the same thing.

**Comment by alvise** [comment]
Nevermind i just debounced **ajaxRequestFunc** and it works for all kind of requests.
Maybe less elegant than a global option but it does the job.

if anyone is interested its something like this

`const debounce = function (func, wait) {
  let timeout;
  return function (...args) {
    clearTimeout(timeout);
    return new Promise((resolve) => {
      timeout = setTimeout(() => {
        resolve(func.apply(this, args));
      }, wait);
    });
  };
};

const fetchData = debounce(async function (url, config, params) {
  const response = await fetch(url);
  return response.json();
}, 500);

const table = new Tabulator("#example-table", {
  ajaxRequestFunc: fetchData,
  ajaxResponse: function (url, params, response) { 

  }
  and the rest of the options...`

**Comment by olifolkerd** [comment]
Hey @alvise 

Could you explain why this would be necessary? it seems it would just add a delay to the user experience. Tabulator only requests data on request at a time, so it shoulnt be choking out an end point?

Cheers

Oli :)

**Comment by alvise** [comment]
I have several elements (mostly presets buttons) outside the table that sets/cancel the order and the filtering.
Debouncing the requests prevents to many calls to our database when the user randomly click everywehere.
(if the data is a local javascript object i don't care, its fast and its their cpu).

Basically its a sort of Live Filter Delay system wide, i could debounce every single control element but i do not see the point.

As a bonus the user can also ctrl click different columns to set a multiple ordering with a single request (if they are fast)
And if you need you can also do multiple "addFilter" or "removeFilter" triggering the request only at the end.
(I know i could use setFilter but maybe you need to remove a headerFilter and set a tableFilter in one go)

Now i made a custom module to load data from Featherjs services instead of "ajaxRequestFunc" but it works the same.

**Comment by olifolkerd** [comment]
Hey @alvise 

I think given the uniqueness of that usage case the timeout should really be debounced at the custom button level as those sit outside the table.

But great to hear that you have been making custom modules!

Cheers

Oli :)

**Comment by alvise** [comment]
You are right it would be cleaner debouncing the external controls.
But then, is there a way to set Filter + HeaderFilter + Sort with one request?
For example a Users Table:  table filter = "Active", header filter = "Admins", sort by "Surname"

Its not a suggested feature, i am just trying to understand if there is a better way that i do not know :P
