### ISSUE TITLE
css height game

### ISSUE THREAD

**Issue by romanman** [olifolkerd/tabulator#418]
![image](https://user-images.githubusercontent.com/5822633/27762379-a550c56a-5e79-11e7-8668-60f0ab568478.png)

I am trying to bring the text and the image to 
be nicely aligned vertically but no matter what
I specify in height of the cell and the raw, I can't
change it. Please advice.

**Comment by olifolkerd** [comment]
Hey,

They height of the cells is automatically adjusted by Tabulator to ensure they are all the same height, so any changes you have made to the height will be overwritten.

If your content is always the same height, then you could adjust the padding of the cells to move the text down.

Alternatively you could use a custom formatter to put all the cells content in another div, and then set the following css properties on the cells to turn them into flex boxes allowing for automatic vertical centering:
```css
display:inline-flex;
align-items:center;
```

Let me know if that helps,

Cheers

Oli

**Comment by romanman** [comment]
Yep it worked, 10x. 🥇

**Comment by olifolkerd** [comment]
which option did you go for out of curiosity?

**Comment by romanman** [comment]
![image](https://user-images.githubusercontent.com/5822633/27763857-9295c34c-5e94-11e7-8874-4621d61b485a.png)
```css
custom{
  padding-top: 5px;
  display:inline-flex;
  align-items:center;
 }
```

```javascript
 {title:"Host", field:"host", sorter:"string", width:80, headerFilter:"input", 
 formatter:function(value){return "<div class='custom'>" + value + " </div>" }},
```
