### ISSUE TITLE
Scroll to active column not working on 5.4

### ISSUE THREAD

**Issue by OleAd** [olifolkerd/tabulator#4180]
**Describe the bug**
When using tab to navigate in a table with overflow (horizontal scrollbar), the table does not scroll to the active column, it only scrolls when the user has started to edit the cell. 

This behaviour is new in version 5.4 and up. It works as intended in version 5.3.

**Tabulator Info**
Bug exists in 5.4.4.

**Working Example**
[https://jsfiddle.net/0pyju65g/5/](https://jsfiddle.net/0pyju65g/5/)

**To Reproduce**
Run the JS Fiddle. Ensure viewport is small enough for the table to have a horizontal scrollbar. Activate a cell, and use tab to navigate to the next. The table will not scroll to the active cell.

**Expected behavior**
When using tab to navigate, the table should scroll to the active cell. This behaviour is present in i.e. version 5.3.4.

**Desktop (please complete the following information):**
 - Windows 10 
 - Chrome
 - 112

**Comment by OleAd** [comment]
As an add-on: Shift+tab going back to right-most cell in previous row does not work on 5.3.4, but does work on 5.4.4.

**Comment by olifolkerd** [comment]
Hey @OleAd 

Thanks for the headsup, i have just pushed a fix for this to the 5.5 branch and will include it in todays release.

Cheers

Oli :)

**Comment by OleAd** [comment]
Thanks, and thanks for your great work!
