### ISSUE TITLE
Filtering by date input does not work until input unfocus

### ISSUE THREAD

**Issue by yevhensayenko** [olifolkerd/tabulator#4182]
**Describe the bug**
When filter by date, the filtering dies not occur after the date selected, I need to click somewhere else, it filtered immediately on 5.4.3

**Tabulator Info**
- 5.4.4

**Working Example**
https://jsfiddle.net/2uyk9gxp/2/

**To Reproduce**
1. Select some date on date input of Date Of Birth column - the filtering does not occur
2. Click somewhere else on the page to unfocus input - the filtering happens.
3. Clear date input and enter something into Name filter - filtering happens after short delay.

**Expected behavior**
I would expect immediate fitnering, like it happens with text input filters.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome 112.0.5615.139

**Comment by olifolkerd** [comment]
Hey @yevhensayenko 

This is a limitation of the built in browser date editor,

Cheers

Oli :)

**Comment by yevhensayenko** [comment]
Hello @olifolkerd But it worked OK on 5.4.3. I checked the Tabulator code and in the 5.4.3 both "change" and "blur" event was handled, but in 5.4.4 only "blur" event is. So if it was done intentionally it is still unclear why it was done.
