### ISSUE TITLE
Table Layout: Column Layout Modes in table of contents points to incorrect anchor

### ISSUE THREAD

**Issue by michaelhuch** [olifolkerd/tabulator#4183]
**Website Page**
https://tabulator.info/docs/5.4/layout

**Describe the issue**
"Column Layout Modes" link in table of contents points to anchor "col-layout" while the id on the actual header is "layout".

And thank you for creating tabulator :)

**Comment by chirag8153** [comment]
The table-layout property defines the algorithm used to lay out table cells, rows, and columns. Tip: The main benefit of table-layout: fixed; is that the table renders much faster. On large tables, users will not see any part of the table until the browser has rendered the whole table.

**Comment by olifolkerd** [comment]
Hey @michaelhuch 

Thanks for the headsup, i have pushed a fix for this to the 5.5 branch and will include it in the docs update with todays 5.5 release.

Cheers

Oli :)
