### ISSUE TITLE
Toggling a responsive row cause a layout jump

### ISSUE THREAD

**Issue by laraDuPreezKrs** [olifolkerd/tabulator#4184]
**Describe the bug**
Same as Toggling a responsive row cause a layout jump #3843

**Tabulator Info**
- 5.2.7

**Working Example**
https://codepen.io/lekoalabe/pen/bGvEBrL

**To Reproduce**
Scroll down
Toggle a row
It will jump to top of the page

**Expected behavior**
The page doesn't jump

**Additional context**
Is there a work around for this problem?

**Comment by lekoala** [comment]
The workaround is to add a minheight to the table, you can see an example here
https://github.com/olifolkerd/tabulator/issues/4155

Actually it think this is not even a workaround. It would be a sane default: when redrawing the table, assign a min height of the current height then remove it. Not sure when/where this should be done however.

**Comment by laraDuPreezKrs** [comment]
Thank you @lekoala I appreciate the reply. The minHeight set to auto works really well.
