### ISSUE TITLE
headerSortElement does not work correctly

### ISSUE THREAD

**Issue by kakarot218** [olifolkerd/tabulator#4188]
**Describe the bug**
Hello has anyone used tabulator?  When using custom headerSort in tabulator using headerShortElement it displays a whole function.
this is my tabulator code 

```
<ReactTabulator
                  columns={columns}
                  data={applications}
                  options={{
                    pagination: "local",
                    paginationSize: 10,
                    paginationSizeSelector: [5, 10, 15],
                    headerSortElement: test
                  }}

                  layout="fitColumns"
                  id="tabulator"
                  placeholder="No Data Available"
                />
```

and the test function : 

```
const test = (column, dir) => {
    console.log(dir)
    switch (dir) {
      case "asc":
        return "<i class='fas fa-sort-up'></i>";
        break;
      case "desc":
        return "<i class='fas fa-sort-down' ></i>";
        break;
      default:
        return "<i class='fas fa-sort'></i>";
    }
  }
```

I am following tabulator's doc

So here instead of showing the icons only it displays whole test function

**Tabulator Info**
5.4

**Working Example**
YOU MUST include a link to a JS Fiddle or Codepen that demonstrates the problem, it is very hard to diagnose an issue from a simple description.
<!--
Please read the Minimal Reproducable Example guide if you are unsure what the example should look like http://tabulator.info/community/mre
A quick guide on creating a JS Fiddle can be found on the Tabulator website http://tabulator.info/community/jsfiddle

**Comment by bornova** [comment]
Try calling the function `test` rather than referencing it: `headerSortElement: test()`

**Comment by kakarot218** [comment]
@bornova still sir it does not working as expected dir and column are undefined so inside switch we are only getting default condition satisfied.

**Comment by bornova** [comment]
> @bornova still sir it is not working as expected. dir and column are undefined so inside switch we are only getting default condition satisfied.

You are right, calling the function directly would return dir and column to be undefined. My mistake.  But still not sure why your example doesn't work.  Here is a working jsfiddle based on your example: https://jsfiddle.net/izmirli/krx46osy/

**Comment by kakarot218** [comment]
Hello @bornova sir. it works fine using vanilla js. can you please try it using react js by importing `import { reactFormatter, ReactTabulator }` same as my above example. i think it's an issue with react-tabulator library. i also tried it using vanilla js and works but need it to be run with react like above

**Comment by olifolkerd** [comment]
Hey @kakarot218 

I would recommend against using the react-tabulator library, it is not maintained by the Tabulator team and is now very out of date.

The [React Documentation](https://tabulator.info/docs/5.4/frameworks#react) explains how to get things working on react using vanilla Tabulator.

Cheers

Oli :)
