### ISSUE TITLE
Small enhancment for row.scrollTo()

### ISSUE THREAD

**Issue by python3Berg** [olifolkerd/tabulator#4189]
Hello,
One of my projects many Tabulator uses involved grouping rows by a specific display field. When I add a row to this table that happens to have a header that puts it at the top, the scrollTo (or scrollToRow(id,'top')) I invoke after promise return truncates the header and shows only the contents. Not the end of the world, but...I can work around it when disabling VDOM, but this adds more problems that it fixes. It would be great if the scrollToRow would, when using groups, anchor the row by the group header instead of the content. I can see instances where this could cause problems if many in group so perhaps make it optional parameter. 

Thanks

**Comment by olifolkerd** [comment]
Hey @python3Berg ,

Thanks for your feedback.

I think it would be counter intuitive to make the scrollToRow function scroll to a group as that isnt the purpose of the function and the vast majority of usage cases will explicitly expect it to scroll to the row.

That being siad i do think this would be a useful addition for usage cases like your, so I have added the `scrollTo` function to the Group Component.

So you could now call:
```js
table.getRow(63).getgroup().scrollTo("top");
```

This will be going live in the 5.5 release later roday.

Cheers

Oli :)

**Comment by python3Berg** [comment]
That's an outstanding outcome. Thank you.
