### ISSUE TITLE
Add write options to xlsx download

### ISSUE THREAD

**Issue by sergehauri** [olifolkerd/tabulator#4190]
*Is your feature request related to a problem? Please describe.**
The SheetJS library allows configuring the file writing, most notably the output format ("bookType") to support file formats other than "xlsx" (https://docs.sheetjs.com/docs/api/write-options#writing-options).
Tabulator sets these options to hardcoded values, but it would be useful if they could be passed in the options argument in the download method.

**Describe the solution you'd like**
The options argument of the .download method supports a property "writeOptions", which will be passed to the XLSX.write method:

```
table.download(
    "xlsx",
    "example.xls",
    {sheetName:"sheet1", writeOptions: {bookType:'biff8', bookSST:true}}
);
```
The writeOptions should passed through to XLSX.write as they are, with the exception that .type is always set to 'binary' (as otherwise the download method will not work correctly).

**Describe alternatives you've considered**
If you want to change the SheetJS output format, there's no way to do it with tabulator right now. You'd have to implement the download function yourself.

The passing of the options could be handled differently, e.g. as a callback function passing the default options object as an argument (similar to "documentProcessing"). This way you could keep the current tabulator default options as they are and just add/update properties on the default options object. In my opinion this would be an unecessary overhead though.

**Additional context**
This change is small and does in no way affect current usage and functionality.

**Comment by olifolkerd** [comment]
Hey @sergehauri 

This functionality will be included in todays 5.5 release.

Cheers

Oli :)
