### ISSUE TITLE
Accessor is not applied on table getEditedCells()

### ISSUE THREAD

**Issue by araghav23** [olifolkerd/tabulator#4193]
**Describe the bug**
While using table.getEditedCells function, the values of the cells being returned are not going through the accessor configured for that column. With this, the combination scenarios of modified data collection on table with columns that have accessors gives us the data without transformation that accessor does. I could see that the accessor is being called and applied when calling table.getData() as expected

If this is an expected behavior or the accessors are consciously omitted for getEditedCells() function, can you please suggest the best way to apply accessor transformation on data that is returned by getEditedCells() ?

**Tabulator Info**
-5.4.4

**Working Example**
https://jsfiddle.net/rsgyw2uc/60/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to the jsfiddle link https://jsfiddle.net/rsgyw2uc/60/
2. Edit any row's value (it has only one column) and choose a different value from the list
3. Click on Get Updated Data button 
4. Observe data being consoled out.

**Expected behavior**
I expect to see the value being returned by table.getEditedCells()[0]['_cell']['value'] to be a transformed value via accessor defined for that column.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser All browsers

**Smartphone (please complete the following information):**

**Additional context**

**Comment by olifolkerd** [comment]
That function is working as anticipated, the getData function on the cells returns the raw data.

The `getEditedCells` function returns an array of cell components, these are the same components regardless of where they are generated in Tabulator, it is the same function call wherever.

In your case i would recommend calling the row components `getData` function, passing in the transform that you want to see:
```js
table.getEditedCells()[0].getRow.getData("data"));
```

Cheers

Oli :)

**Comment by araghav23** [comment]
Hey, thank you so much @olifolkerd . That works for me :)
