### ISSUE TITLE
Use (vue) components as formatters

### ISSUE THREAD

**Issue by Extarys** [olifolkerd/tabulator#4194]
*Is your feature request related to a problem? Please describe.**
It is hard to reuse previous formatters outside Tabulator when using Vue (3).

Let's say I have a formatter showing (in some fancy way): 4 waiting (10 total)
This could be reused pretty much everywhere we need it to (product page, ordering forms, and tabulator), but we would need to recreate it as a component to match the same text and style everywhere.

**Describe the solution you'd like**
Ability to pass a Vue component to the formatter.

**Describe alternatives you've considered**
Put all formatters in a single file and import them as needed, without the flexibility of Vue components. And recreate them as components when needed.

**Additional context**
Examples on how this can be used: https://www.ag-grid.com/vue-data-grid/component-cell-renderer/#simple-cell-renderer-example

```
Formatters are called Renderers in AG Grid.
// Import component
import TotalValueRenderer from './totalValueRendererVue.js';
// Use it as a formatter
columns: [
{
   field: "gold",
   formatter: "medalCellRenderer"
},
```

Sorry if this is somewhat already possible, I looked but didn't find what I was looking for.
P.S Just found Tabulator and I love it!

**Comment by olifolkerd** [comment]
Hey @Extarys 

This would be out of scope of the core library as it is framework agnostic.

Cheers

Oli :)
