### ISSUE TITLE
Performance issue with addData method

### ISSUE THREAD

**Issue by yevhensayenko** [olifolkerd/tabulator#4197]
**Describe the bug**
When add new data to Tabulator (2k rows), it freezes page for about half of a second.

**Tabulator Info**
- Issue is present in 5.4.4 and 5.5.0

**Working Example**
See https://jsfiddle.net/uo3rygw8/1/ It loads new data every second (case from production). If you repeatedly click any column header to sort column, it freezes every second. If you downgrade Tabulator version to 5.4.3 and do the same, the page will be more responsible and almost no freezes.

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://jsfiddle.net/uo3rygw8/1/
2. Repeatedly click on any sorting column to sort it
4. See freezing page every second.

**Expected behavior**
I would not expect Tabulator to be freezed like it was on 5.4.3.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 113.0.5672.94

**Comment by ironirc** [comment]
I believe I experience similar problem.
I'm using a custom function for ajaxRequestFunc and progressiveLoad = load.
With each page load, the freezes become longer.
Profiling shows that most time is spent in setActiveRows

**Comment by olifolkerd** [comment]
Hey @ironirc,

For frequent updates i would suggest using the `replaceData` function as it is much more efficient.

Cheers

Oli
