### ISSUE TITLE
5.5 cell height is not computed anymore

### ISSUE THREAD

**Issue by lekoala** [olifolkerd/tabulator#4199]
**Describe the bug**
The cell height is not computed anymore

From what i can see, it's the new vdom with document fragment that does this
this.element.clientHeight == 0 in calc height

**Tabulator Info**
5.5

**Working Example**

5.5 : no height
https://codepen.io/lekoalabe/pen/oNamzxx
<img width="748" alt="image" src="https://github.com/olifolkerd/tabulator/assets/250762/870c4356-1fd9-429b-8eca-83526399454c">

5.4 : no issue
https://codepen.io/lekoalabe/pen/NWzprxV
<img width="683" alt="image" src="https://github.com/olifolkerd/tabulator/assets/250762/deba3a6a-9ade-4dc3-a0a5-8cf8b07c5237">

**Comment by olifolkerd** [comment]
Hey @lekoala 

Thanks for the headsup, i have pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)
