### ISSUE TITLE
Export to XLSX

### ISSUE THREAD

**Issue by LogisApp** [olifolkerd/tabulator#4200]
*Is your feature request related to a problem? Please describe.**
Cuando se hace un exportacion de una tabla a formato XLSX, las columnas de numeros se muestran en formato de texto. para solucionar esto hay que ir a celda por celda y pulsar enter o usar la funcion de texto en columnas de excel.

**Describe the solution you'd like**
La solucion seria que la funcion de exportar tomara los formatos que estan establecidos en cada columna y de esta misma forma los exportara a excel

**Describe alternatives you've considered**
Otra alternativa seria que la funcion de exportar tomara todo las columnas que sean de tipo numero y las exportara como numero a excel

**Additional context**

**Comment by technofreakz** [comment]
Export to XLSX Documentation available, check website please  [https://tabulator.info/docs/5.5/download#xlsx](url)
