### ISSUE TITLE
Default filter parmater name is filter not filters 

### ISSUE THREAD

**Issue by moamenhredeen** [olifolkerd/tabulator#4202]
**Website Page**
[A link to the page with the issue](https://tabulator.info/docs/5.5/filter)

**Describe the issue**
Default filter parmater name is filter not filters

**Comment by olifolkerd** [comment]
Hey @moamenhredeen  Im afraid im not sure to which particular part of the documentation you are refering, could you include a screenshot of the particular issue.

Cheers

Oli :)
