### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by Tyoneb** [olifolkerd/tabulator#4203]
This is a low priority issue, you'll find a list of typos I found while reading the documentation. I would definitely recommend you use an IDE extension like "Code Spell Checker" in VS Code to help you get this under control 😆 

I stopped listing typos at the Table Layout page but I can push further if you want me to!

### https://tabulator.info/docs/5.5/release
* Virtical Vitrual Renderer -> Vertical Virtual Renderer
* redender -> renderer
* Formating -> Formatting
* infront -> in front
* usefull -> useful
* aruguments -> arguments (x2)

### https://tabulator.info/docs/5.5/install
* In the CDN ESM Import section, the link is missing the version number.
* initialise -> initialize
* bolierplate -> boilerplate
* for an SCSS project whis would be -> for an SCSS project this would be

### https://tabulator.info/docs/5.5/columns
* Customising -> Customizing
* fieldproperty -> field property
* autocolumns -> autoColumns (x3) and some are missing the proper "code" tag
* propertys -> properties
* renderd -> rendered
* Seperator -> Separator
* assumped -> assumed
* ingored -> ignored

### https://tabulator.info/docs/5.5/data
* Calbacks -> Callbacks
* formatterd -> formatted
* strucutred -> structured
* reusues -> reuses
* untill -> until
* repeates -> repeated
* triger -> trigger
* ususal -> usual
* dont -> don't

### https://tabulator.info/docs/5.5/options
* customise -> customize
* seperate -> separate
* receving -> receiving (x2)
* feilds -> fields
* incomming -> incoming
* tirggering -> triggering
* defaut -> default
* constuctor -> constructor
* lauyout -> layout

### https://tabulator.info/docs/5.5/callbacks
* bingings -> bindings

### https://tabulator.info/docs/5.5/events
* thetableDestroyed event will triggered -> the tableDestroyed event will be triggered
* dont -> don't (x2)

### https://tabulator.info/docs/5.5/reactivity
* Compatability -> Compatibility
* reativity -> reactivity
* comming -> coming
* compatable -> compatible

### https://tabulator.info/docs/5.5/build
* Compatability -> Compatibility
* Sorce -> Source
* overwrittenwhen -> overwritten when
* dont -> don't

### https://tabulator.info/docs/5.5/layout
* Whene -> When
* withs -> widths
* resiizable -> resizable
* resizeable -> resizeable
* reszie is occuring -> resize is occurring
* cofiguring -> configuring
* Virual -> Virtual
* degredation -> degradation
* temporarlity -> temporarily
* riggering -> triggering

**Comment by olifolkerd** [comment]
Wowza! Big list, thankyou very much that is a big help. I will get that sorted in the next update

**Comment by olifolkerd** [comment]
Hey @Tyoneb 

All the typos from your list that aren't UK/US differences should now be fixed on the live site, not just on the pages you highlighted, but on all pages in the site.

Thanks for info.

Cheers

Oli :)
