### ISSUE TITLE
onRendered callback isn't triggered properly

### ISSUE THREAD

**Issue by nghuuphuoc** [olifolkerd/tabulator#4208]
**Describe the bug**
`onRendered` isn't triggered properly.
In the previous version (v5.4.x), we are able to render a custom cell using a custom formatter. We integrate Tabulator with external library, and `onRendered` can be used to trigger the custom rendering.

It's mentioned here https://tabulator.info/docs/5.5/format#format-custom

> The formatter code is run before the element is added to the DOM, on the whole this is not a problem, but some other libraries require the element they are attached to to be visible before they are run. To do this Tabulator provides the onRendered callback function.

```js
// Our formatter
function(cell, formatterParams, onRendered) {
  onRendered(() => {
     const div = document.createElement('div');

     // Append to the cell
     cell.getElement().appendChild(div);

     // Render custom content to newly created `div` ...
     // Work with v5.4.x, but not v5.5.0
     // It seems that the `cell.getElement()` doesn't really exist in the DOM tree at the moment
     console.log(document.body.contains(cell.getElement()))     // return `false`
  })
}
```

**Tabulator Info**
5.5.0

**Working Example**
I am sorry that I can't give you a fiddle since we are using Tabulator with an external library.

**Comment by olifolkerd** [comment]
Hey @nghuuphuoc 

Thanks for the info, i have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)

**Comment by nghuuphuoc** [comment]
Thank a lot! I will let you know if the next version fixes the issue.

**Comment by nghuuphuoc** [comment]
@olifolkerd I have updated the latest version 5.5.1 and can confirm that the bug is fixed.
Thank you a lot for your hard work.
