### ISSUE TITLE
layout: 'fitColumns' causes page to freeze/hang when it is resized.

### ISSUE THREAD

**Issue by AvishekPaul** [olifolkerd/tabulator#4209]
When I resize the screen multiple times, the page gets hang. And the tab has to be closed and then restarted again to solve it.
I am using version "tabulator-tables": "^5.5.0",
using windows and chrome brower, using it in vue 3.
`tabulator.value = {
      value: new Tabulator(
        table.value as HTMLDivElement,
        {
          data: props.data,
          reactiveData: true,
          columns: props.columns,
          layout: "fitColumns",
          // responsiveLayout: "collapse",
        } as TabulatorOptions
      ),
    };`
This only happens when I use  layout: 'fitColumns'. Otherwise, it's okay. I can't give any js fiddle link, apologies for that. But this bug is old and I found a previous issue on this. This is the link describing same issue. My problem is quite similar.
the issue link: [https://github.com/olifolkerd/tabulator/issues/3464](https://github.com/olifolkerd/tabulator/issues/3464)
Please Look into this issue. Thank You.

**Comment by olifolkerd** [comment]
Hey @AvishekPaul 

Without a JS Fiddle that demonstrates the issue im afraid there is just no way we can help you as we cant see where the problem may be coming from.

If this is still an issue for you, please recreate this ticket using the issue template and provide a link to an example and we can pick things up from there.

Cheers

Oli :)

**Comment by vcollado** [comment]
Hi, while integrating tabulator we found the same issue. This was related to the parent container having a display flex and tabulator not being able to shrink correctly, in our case was:

```html
<div class=d-flex>
   <div style="width: 250px"></div>
   <div>tabulator instance here</div>
</div>
```

In this situation and with tabulator layout set to `fitColumns` when resizing the navigator windows (Google Chrome 133.0.6943.53 on Manjaro OS) the freeze happened.

  codepen: https://codepen.io/vcollado/pen/ogNGzvj
