### ISSUE TITLE
Link - renders data as an anchor with a link to the given value --- Issue

### ISSUE THREAD

**Issue by azizur-rahman** [olifolkerd/tabulator#421]
How can i apply "link - renders data as an anchor with a link to the given value." 

Please provide an example that is helpful for me.

**Comment by olifolkerd** [comment]
Hey,

As per the documentation in the [Formatting](http://olifolkerd.github.io/tabulator/docs/#formatting) section, you can apply any of the default formatters by assigning it to the ***formatter*** property in the columns definition object

```js
$("#example-table").tabulator({
    columns:[
        {title:"A Special Link", field:"url", formatter:"link"},
    ]
});
```

I will update the documentation to make this clearer.

Cheers

Oli

**Comment by azizur-rahman** [comment]
Thanks

CHEERS
