### ISSUE TITLE
Regression in Tabulator 5.5.0: selectRow() does not work anymore for id=0

### ISSUE THREAD

**Issue by hwalinga** [olifolkerd/tabulator#4215]
**Describe the bug**
In Tabulator 5.5.0 `selectRow()` does not work anymore for `id=0`.

**Tabulator Info**
5.5.0

**Working Example**

Here you can see the bug in action. It worked on versions before 5.5.0

https://jsfiddle.net/hielke96/e398g4ko/13/

**To Reproduce**
1. Create a table with a row with id=0
2. Try to programmatically select it with `selectRow(0)`

**Expected behavior**
It should be selected.

**Comment by olifolkerd** [comment]
Hey @hwalinga 

Thanks for the headsup, i have pushed a fix for this to the 5.6 branch and will include it in the feature release in a couple of weeks time.

Cheers

Oli :)
