### ISSUE TITLE
Multiselect Header Filter sends raw string if key is pressed

### ISSUE THREAD

**Issue by Bobcat64** [olifolkerd/tabulator#4220]
**Describe the bug**
While a multiselect header filter is open, pressing a key will set the filter value to the raw comma separated string displayed, and not an array.

**Tabulator Info**
Version 5.5.0

**Working Example**
[JSFiddle Example](https://jsfiddle.net/14es6qmp)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Click on header to select from a list to filter, have at least 1 or more items selected
2. Click off to have the filter apply correctly
3. Click on header filter again and press almost any key ('a' definitely works), be sure you have the input field selected
4. Observe that the header filters are set with a value that is *not* an array, but just the raw string. Console warnings will appear if using the built in filtering. Remote ajax calls will also be given a filter with a value of a string and not an array.

**Expected behavior**
Multiselect header filters should consistently use values that are arrays, not strings. (Barring custom code)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome 
 - Version: 114.0.5735.134

**Workaround**
Known workaround is to set `headerFilterLiveFilter: false` for the column. However this does not appear to be an intended 'requirement' nor documented. I believe there is a desire to apply filtering as items are selected and that flag would seem appropriate to control that (though that is getting into feature request territory)

**Notes**
The bug appears related to the live filtering feature that is enabled by default. The multiselect header filter is still an input, just keypresses have their default action prevented. A listener is setup for a keyup event to trigger searching/filtering on the input's raw value. However for multiselect that raw value is for display purposes and is not an array.

Also once the header filter is closed it does set the filter value to an appropriate array.

**Comment by olifolkerd** [comment]
Hey @Bobcat64 

The example is showing it functioning correctly and returning an array.

Cheers

Oli :)
