### ISSUE TITLE
SemanticUI: frozen columns overlap scrolled columns on grey rows due to transparency

### ISSUE THREAD

**Issue by JanRomero** [olifolkerd/tabulator#4221]
**Describe the bug**
The SemanticUI style gives even rows a transparent background. This seems to lead to unsightly overlapping text when frozen columns and horizontal scrolling are involved. Odd rows are opaque white and do not present this problem.

**Tabulator Info**
Version 5.5

**Working Example**
https://jsfiddle.net/pwbv9ykL/

**To Reproduce**
1. Scroll the table to the left
2. See Steve’s shoe size overlap his name

**Expected behavior**
Text should not overlap, scrolled columns should disappear behind frozen columns the way it works with odd/white rows.

**Screenshots**
![grafik](https://github.com/olifolkerd/tabulator/assets/7873027/83cbd961-2355-45e2-aed7-d333f5c8780d)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox, Edge, Chrome
 - Version: latest

**Additional context**
Thanks!

**Comment by mayorbyrne** [comment]
For what it's worth, the materialize theme also presents this problem, except on every row, not just the odd ones

**Comment by olifolkerd** [comment]
Hey @JanRomero  and @mayorbyrne 

Thanks for the info, i have pushed fixes for both of these themes to the master branch and will include them in todays patch release.

Cheers

Oli :)
