### ISSUE TITLE
Clear "x" button header filter not working on iOS (tested on iPhone)

### ISSUE THREAD

**Issue by dennisvd** [olifolkerd/tabulator#4222]
**Describe the bug**
Clear button ("x") on the left of a header filter input field does not appear on iOS (iPhone).

**Tabulator Info**
Tabulator version 5.5

**Working Example**
JSFiddle link: https://jsfiddle.net/Dennism/btc90y5m/10/

Code snippet:
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Tabulator Table with Header Filters</title>
  <link href="https://unpkg.com/tabulator-tables/dist/css/tabulator.min.css" rel="stylesheet">
</head>
<body>
  <h1>Clear x missing for Gender on iPhone Safari</h1>
  <div id="table"></div>

  <script src="https://unpkg.com/tabulator-tables/dist/js/tabulator.min.js"></script>
  <script>
    // Sample data for the table
    var tableData = [
      { name: "John Doe", age: 30, gender: "Male", city: "New York" },
      { name: "Jane Smith", age: 25, gender: "Female", city: "London" },
      { name: "Bob Johnson", age: 40, gender: "Male", city: "Paris" },
      // Add more data rows as needed
    ];

    // Create the Tabulator table
    var table = new Tabulator("#table", {
      data: tableData,
      layout: "fitColumns",
      columns: [
        { title: "Name", field: "name", headerFilter: "input" },
        { title: "Age", field: "age", headerFilter: "number" },
        { title: "Gender", field: "gender", headerFilter: "select", headerFilterParams: { values: ["Male", "Female"] } },
        { title: "City", field: "city", headerFilter: "select", headerFilterParams: { values: true, clearable: true } },
        // Add more columns as needed
      ],
    });
  </script>
</body>
</html>
```

ISSUES CREATED WITHOUT THIS EXAMPLE WILL BE CLOSED WITHOUT DISCUSSION
-->

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to 'Gender' header input field and select a value
2. Click again on 'Gender' header input field. 
3. Do step 1 & 2 on desktop (macOS Chrome) and you will see a clear icon button ("x"). 
4. Do step 1 & 2 on desktop (iOS Safari) and you will NOT see a clear icon button ("x"). 

**Expected behavior**
The clear icon button ("x") should appear also on iOS Safari.
Without it there is no way the clear the header filter.

**Screenshots**
Attached are 2 screenshot.
1) iPhone iOS (does not work as expected, missing clear icon "x" button)
![image](https://github.com/olifolkerd/tabulator/assets/7593391/0038714c-fd50-41c2-8d24-e6d76dfb0952)
2) MacBook (ARM) Chrome (works as expected)
![image](https://github.com/olifolkerd/tabulator/assets/7593391/6efbd0ed-a88f-4d43-887f-8606448dca8f)

**Desktop (please complete the following information):**
 - OS: macOS version 13.4
 - Browser Chrome
 - Chrome version 114.0.5735.90

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 16.5
 - Safari
 - Version Safari is equal to iOS 16.5

**Comment by umer936** [comment]
Same as this? https://github.com/olifolkerd/tabulator/issues/3813
