### ISSUE TITLE
"groupClick" and "groupDblClick" are not firing on header click when groupToggleElement is set to "header"

### ISSUE THREAD

**Issue by FreshMulgogi** [olifolkerd/tabulator#4223]
**Describe the bug**
groupClick and groupDoubleClick events do not fire when groupToggleElement is set to "header". However, when groupToggleElement is set to "arrow", it will fire when the header is clicked but not when the arrow itself is clicked. Other group events such as groupContext and groupVisibilityChanged still fire appropriately even when the toggle is set to "header". 

**Tabulator Info**
- 5.5

**Working Example**
https://codepen.io/FreshMulgogi/pen/OJaRpBV

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to Line 29 and 30
2. Decide toggle type
3. Scroll down to Lines 49 through 63
4. Comment out different group events and see console logs

**Expected behavior**
I expect the console.log("Left clicked") or console.log("Double clicked") to appear in the console when those events are present.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Tested in Edge and Firefox
 - Version 114.0.1823.51 and Version 114.0.1 respectively

**Additional context**
Potentially related to this previous issue from version 3.4: https://github.com/olifolkerd/tabulator/issues/828

**Comment by AadBr** [comment]
I have encountered the same behavior as described above.

**Comment by olifolkerd** [comment]
Hey @FreshMulgogi 

Thanks for the info, i have pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)
