### ISSUE TITLE
Use Vitepress or Vuepress for the documentation

### ISSUE THREAD

**Issue by DylanThomasFr** [olifolkerd/tabulator#4227]
The problem : 

I have been using Tabulator for a while and it has a lot of features. What is frustrating for me is navigating through the documentation. I find it hard to find the solution for my problem if it exists. Sometimes we need to be multiple people searching to find the solution.

The solution offered : 

Vite and Vue JS are using [Vuepress](https://vuepress.vuejs.org/) or [Vitepress](https://vitepress.dev/) to document their code and the community love how easy it is to find a solution there and how easy it is to build a doc with these tools.

It is all written in Markdown and includes Markdown extensions for customization. Also it has a powerful search bar to search through the doc.

I don't know if others feel the same but this is my suggestion to improve our DX.

**Comment by olifolkerd** [comment]
Hey @DylanThomasFr 

Thanks for the suggestion, but on the whole i have received very positive feedback on the structure of the documentation website.

There is a search in the top right hand corner of the page that will let you  find anything you need, and an extensive [Examples Page](https://tabulator.info/examples/5.5) that shows you all the features in action.

If you have a specific issue you would are struggling with in using the site i would be happy to hear more details, but im not looking to rebuild the site at the moment.

Cheers

Oli :)
