### ISSUE TITLE
undo() after reordering rows misses by 1

### ISSUE THREAD

**Issue by goodsign** [olifolkerd/tabulator#4228]
**Describe the bug**
When you re-order rows by dragging the handle and then click `undo`, it misses by 1, incorrectly placing the row one position lower than it should.

**Tabulator Info**
5.5.0

**Working Example**
https://jsfiddle.net/Lz36b9mn/

**To Reproduce**
1. Move 'D' between A and B. Becomes `ADBCE`
2. Wait 1 second
3. `undo()` makes it `ABCED` instead of `ABCDE`

**Expected behavior**
It becomes same as before: ABCDE

**Additional context**
Was also reproducible on 5.4.4.

**Comment by olifolkerd** [comment]
Hey @goodsign 

Thanks for the info.

This was actually two issues, you should not need to call the `redraw` function after the undo action, it should do that itself. and then it was not correctly repositioning the rows.

I have pushed fixes for both of these to the master branch and will be including them in todays patch release.

Cheers

Oli :)
