### ISSUE TITLE
"ResizeObserver loop..." error when setting empty data on a table with "maxHeight" set to "100%" and "placeholder" set to a string

### ISSUE THREAD

**Issue by kermit-the-frog** [olifolkerd/tabulator#4229]
**Describe the bug**
An "ResizeObserver loop..." error occurs, when setting empty data on a table with "maxHeight" set to "100%"  and "placeholder" set to a string

**Tabulator Info**
5.5.0

**Working Example**
https://jsfiddle.net/Kermit_the_frog/Lsgmo5at/8/

**To Reproduce**

1. Go to https://jsfiddle.net/Kermit_the_frog/Lsgmo5at/8/
2. Click on 'Clear table'
3. See error in console
"ResizeObserver loop limit exceeded" in Chrome /  "ResizeObserver loop completed with undelivered notifications." in Firefox

**Expected behavior**
No "ResizeObserver loop..." errors should not be thrown, when setting empty data

**Desktop**
 - OS: Windows
 - Browser: Chrome: 114.0.5735.199 (64-Bit) / Firefox 114.0.2 (64-Bit)

**Additional context**
No Error occurs with version 5.4.
See https://jsfiddle.net/Kermit_the_frog/h50s3f6o/1/

**Comment by olifolkerd** [comment]
Hey @kermit-the-frog,

I am unable to replicate this on the new version, please try after the patch release and see if it is still a problem.

Cheers

Oli :)

**Comment by kermit-the-frog** [comment]
Yes, the issue seems to be fixed.
