### ISSUE TITLE
The placeholder is not visible after initalization with empty data and "maxHeight" set to "100%"

### ISSUE THREAD

**Issue by kermit-the-frog** [olifolkerd/tabulator#4231]
**Describe the bug**
The placeholder is not visible after initalization with empty data and "maxHeight" set to "100%"

**Tabulator Info**
5.5.0

**Working Example**
https://jsfiddle.net/Kermit_the_frog/p5rd3t6s/4/

**To Reproduce**

1. Go to https://jsfiddle.net/Kermit_the_frog/p5rd3t6s/4/
2. See the error: the placeholder ist not visible after initalization
3. Resize the browser window or move the horizontal or vertical splitter of the right bottom pane in JSFiddle

**Expected behavior**
The placeholder should be visible after initalization

**Desktop**
 - OS: Windows
 - Browser: Chrome: 114.0.5735.199 (64-Bit) / Firefox 114.0.2 (64-Bit)

**Additional context**
No Error occurs with version 5.4.
See https://jsfiddle.net/Kermit_the_frog/wLfdpkjg/1/

**Comment by olifolkerd** [comment]
Hey @kermit-the-frog 

Thanks for the info, i have pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)

**Comment by kermit-the-frog** [comment]
Thanks for the fix
