### ISSUE TITLE
Header filter multi select duplication

### ISSUE THREAD

**Issue by mrolfe98** [olifolkerd/tabulator#4232]
Hello, 

I have run into an issue when setting an initial header filter for a multi select. When I click onto the filter, it seems to double up the selected option. 

In the below example, then I click on the gender dropdown, it doubles up the selected 'Male' option to 'Male,Male'.

`<body>

<div id="example-table"></div>

<script>
    // Define table data
    var tableData = [
        { name: "John", age: 25, gender: "Male" },
        { name: "Sarah", age: 30, gender: "Female" },
        { name: "Michael", age: 28, gender: "Male" },
        { name: "Emily", age: 32, gender: "Female" }
    ];

    // Define header filter options
    var headerFilterOptions = {
        "gender": ["Male", "Female"]
    };

    // Create the tabulator table
    var table = new Tabulator("#example-table", {
        data: tableData,
        initialHeaderFilter:[
            {
                "field": "gender",
                "value": [
                    "Male"
                ]
            }
            ],
        columns: [
            { title: "Name", field: "name", headerFilter: "input" },
            { title: "Age", field: "age", headerFilter: "number" },
            { title: "Gender", field: "gender", headerFilter: "select", 
                headerFilterParams: { 
                    values: headerFilterOptions.gender,
                    multiselect:true,
                    clearable:true,
                    uniqueValues: true
                } }
        ]
    });

</script>

</body>`

**Comment by olifolkerd** [comment]
Hey @mrolfe98 

Thanks for getting in touch, if you want to report a bug you will need to link to a JS Fiddle or CodePen that replicates the issue and provide the information requested in the bug issue template or we will not have enough information to help you.

Cheers

Oli :)
