### ISSUE TITLE
Tabulator with jquery-whrapper does not working

### ISSUE THREAD

**Issue by AkiYoss** [olifolkerd/tabulator#4233]
**Describe the bug**
Tabulator with jquery-whrapper does not whrap modules correctly (have only bind modules)

**Tabulator Info**
- Tabulator 5.5 (latest)
- Jquery 2.2.4
- Jquery-ui 1.12.2

**Working Example**
[My code](https://codepen.io/akiyoss/pen/yLEWbeE)

**To Reproduce**
1. Run codepen
2. see console

**Expected behavior**
Row object in console

**Screenshots**
Mozilla Firefox: 
![image](https://github.com/olifolkerd/tabulator/assets/44725292/ef0b6459-81c7-4870-bb83-f358321b1be2)
Google Chrome:
![image](https://github.com/olifolkerd/tabulator/assets/44725292/07ba5d17-a594-4af4-b500-07c924389e14)

**Desktop:**
 - OS: Windows 11
 - Browser Mozilla Firefox v115.0, Google Chrome v114.0.5735.199

**Additional context**
I tried to debug jquery-whrapper and it says that only one field that Tabulator.prototype has is bindModules
![image](https://github.com/olifolkerd/tabulator/assets/44725292/094daf45-d7ba-4c84-8b72-96a00b709f3d)
![image](https://github.com/olifolkerd/tabulator/assets/44725292/50e5cf47-9309-44a3-94b9-aa0c99645cc4)

and when i tryed to use getRow just like from example 
![image](https://github.com/olifolkerd/tabulator/assets/44725292/7e0c634f-d7f5-4215-a8bd-15025dc4c539)

![image](https://github.com/olifolkerd/tabulator/assets/44725292/94844373-1384-4f7e-b324-109b7338edab)

i'm getting an error 
![image](https://github.com/olifolkerd/tabulator/assets/44725292/4899f0b5-e34c-40d8-816c-a33cd085e684)

**Comment by olifolkerd** [comment]
Hey @AkiYoss 

Thanks for the info. I have pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)

**Comment by R3ady2Code** [comment]
Hello @olifolkerd 

I same faced with this problem. However, after updated to 5.5.1 version i see this console error. 

![image](https://github.com/olifolkerd/tabulator/assets/86206439/a0b736e3-1dd2-44db-ae73-f44ce457400b)

If I init without Jquery everything goes fine.
