### ISSUE TITLE
Interrupt Ajax requests whenever Tabulator is destroyed

### ISSUE THREAD

**Issue by mythsmith** [olifolkerd/tabulator#4234]
*Is your feature request related to a problem? Please describe.**
If a tabulator instance is destroyed while progressive tabulation is being performed, one or more exceptions will be logged from the ajax module, because ajaxRequestFunc keeps being called.

**Describe the solution you'd like**
Destroy should neutralize all table modules and avoid any further async action.

**Describe alternatives you've considered**
Before calling destroy, we patch ajaxParams and pass no-op parameters which will neutralize any further call.

**Additional context**
Under some circumstances, the ajax system performs tens or hundreds of calls, like if trying to fill a very long or infinite table.

**Comment by olifolkerd** [comment]
Hey @mythsmith 

Thanks for the feedback. I have taken this one step further and made it so the data manager will not request any data from any modules if the table has been destroyed, not just the ajax module. Similarly it will ignore any async data returned after the table is destroyed and provide a console warning to let the developer know that has happend.

I have pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)
