### ISSUE TITLE
TypeError when calling table.redraw(true) on a table with header filter and dataTree: true

### ISSUE THREAD

**Issue by atebeta** [olifolkerd/tabulator#4237]
**Describe the bug**
Redrawing a table with dataTree: true and an active header filter raises an error. This happens when doing table.redraw(true), but not table.redraw(). Also happens when redraw is triggered by window resize and autoResize is set to true in the table config.

**Tabulator Info**
5.5

**Working Example**
[JSFiddle](https://jsfiddle.net/atebeta/92k6r8zx/32/)

-->

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Click on the redraw table button at the bottom of the table and check the console.

**Expected behavior**
The table should be able to be redrawn with dateTree enabled and an active header filter..

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOs
 - Browser [e.g. chrome, safari] Chromium
 - Version 113

**Additional context**
dataTree.js:573 Uncaught TypeError: Cannot read properties of undefined (reading 'children')
at DataTree.getTreeChildren (DataTree.js:573:13)
at DataTree.reinitializeRowChildren (DataTree.js:211:23)
at DataTree.js:142:10
at Array.forEach ()
at DataTree.tableRedrawing (DataTree.js:141:9)
at InternalEventBus.js:94:28
at Array.forEach ()
at InternalEventBus._confirm (InternalEventBus.js:93:21)
at ColumnManager.confirm (CoreFeature.js:86:30)
at ColumnManager.redraw (ColumnManager.js:738:12)

**Comment by olifolkerd** [comment]
Hey @atebeta 

Thanks for the headsup, I have pushed a fix for this to master and will include it in todays patch release.

Cheers

Oli :)
