### ISSUE TITLE
5.5.0 addRow() throws "TypeError: Cannot read properties of undefined (reading 'func')"

### ISSUE THREAD

**Issue by ortwic** [olifolkerd/tabulator#4238]
**Describe the bug**
await tabulator.addRow({ ... }) throw error resulting in the following stack trace.

GroupRows.js:527 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'func')
    at GroupRows.assignRowToGroup (GroupRows.js:527:40)
    at GroupRows.rowAddingIndex (GroupRows.js:208:9)
    at InternalEventBus.js:76:33
    at Array.forEach (<anonymous>)
    at InternalEventBus._chain (InternalEventBus.js:75:21)
    at RowManager.chain (CoreFeature.js:82:30)
    at RowManager.addRowActual (RowManager.js:388:16)
    at RowManager.addRow (RowManager.js:318:18)
    at RowManager.js:338:20
    at Array.forEach (<anonymous>)

**Tabulator Info**
- version 5.5.0

**Working Example**
You can check it out here: https://song-repo.web.app/
Code: https://github.com/ortwic/song-repo/blob/2e310622d53570dd307ff3dd980a1e372d54e450/src/components/table/SongTable.svelte#L53

**To Reproduce**
1. Load Samples from right side menu
2. Click on header menu and select group by e.g. "genre"
3. Click on header again and ungroup e. g. "genre"
4. Click on plus sign in the right corner
5. See error

**Expected behavior**
Tabulator creates a new row on the bottom of the page.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 
 - Version 114.0.5735.199

**Comment by olifolkerd** [comment]
Hey @ortwic,

I will updat the docs to make it clear you are expected to set this value to false or empty if you wish to clear all grouping.

Cheers

Oli :)

**Comment by maxborisov1983** [comment]
@ortwic, Great thank You. I started little project about 1.5 month ago for my colleagues from previous work. I want to transfer one web app from Asp net web forms to Asp net MVC with replacement different Asp tables bindings to Tabulator.
I meet this problem and didnt know how to fix it. Firstly thought that asp net incorrectly attach js via bundle registering, but it was replayable via unpkg and any other methods of js attaching.
Your code fixed problem.
