### ISSUE TITLE
5.5.0 Download PDF TypeError: jspdf.jsPDF is not a constructor

### ISSUE THREAD

**Issue by ortwic** [olifolkerd/tabulator#4239]
**Describe the bug**
Trying to download PDF throws TypeError: jspdf.jsPDF is not a constructor. Tabulator is used in a svelte component. Files are added like this:

```
<svelte:head>
  <script async type="text/javascript" src="https://oss.sheetjs.com/sheetjs/xlsx.full.min.js"></script>
  <script async type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.5/jspdf.min.js"></script>
  <script async type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/2.3.2/jspdf.plugin.autotable.js"></script>
</svelte:head>
```

Stacktrace:

Table.svelte:183 TypeError: jspdf.jsPDF is not a constructor
    at TabulatorFull.pdf (pdf.js:85:12)
    at Download.download (Download.js:74:17)
    at table.<computed> [as download] (Module.js:38:12)
    at download (Table.svelte:180:16)
    at Object.action (Table.svelte:61:21)
    at HTMLDivElement.<anonymous> (Menu.js:261:14)

XLSX Download is working though.

**Tabulator Info**
- version 5.5.0

**Working Example**
You can check it out here: https://song-repo.web.app/
Code: https://github.com/ortwic/song-repo/blob/2e310622d53570dd307ff3dd980a1e372d54e450/src/components/table/SongTable.svelte#L95

**To Reproduce**
1. Load Samples from right side menu
2. Right click to open context menu and select Export PDF
5. See error

**Expected behavior**
Tabulator creates a PDF for download.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 
 - Version 114.0.5735.199

**Comment by ortwic** [comment]
This works

```
        if (!window['jspdf']) {
            const { default: jsPDF } = await import('jspdf');
            await import('jspdf-autotable');
            
            // Tabulator expects this, see https://github.com/olifolkerd/tabulator/issues/4239
            window['jspdf'] = { jsPDF };
        }
```

**Comment by olifolkerd** [comment]
Hey @ortwic 

This is because you have not included jspdf in your project as per the documentation and is not a bug as such.

Cheers

Oli :)
