### ISSUE TITLE
5.5.0 when grouping more than one level, most upper group has no child rows in data parameter

### ISSUE THREAD

**Issue by ortwic** [olifolkerd/tabulator#4240]
**Describe the bug**
When grouping more than one level, most upper group has no child rows in data parameter.
It is not that important of a bug but it'll nice to have if it would work as expected.

![grafik](https://github.com/olifolkerd/tabulator/assets/5402079/93873a9d-66a4-47f2-a4c0-8f1491389c68)

**Tabulator Info**
- version 5.5.0

**Working Example**
You can check it out here: https://song-repo.web.app/
Code: https://github.com/ortwic/song-repo/blob/2e310622d53570dd307ff3dd980a1e372d54e450/src/components/table/formatter.helper.ts#L120

**To Reproduce**
1. Load Samples from right side menu
2. Click on header menu and select group by e.g. "genre"
3. Click on another header menu and select group by e.g. "style"
4. See screenshot

**Expected behavior**
I'd expect all child rows of the corresponding groups so the average progress could be calculated correctly. Count is working though.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 
 - Version 114.0.5735.199

**Comment by olifolkerd** [comment]
Hey @ortwic 

Thanks for the feedback, i have pushed a fix for this to master and will include it in todays patch release.

Cheers

Oli :)
