### ISSUE TITLE
Overflow: ellipsis not working in combination with vertAlign.

### ISSUE THREAD

**Issue by novasilva-jelle** [olifolkerd/tabulator#4242]
**Describe the bug**
In case of setting the vertAlign on a Column, the text is not abbreviated anymore showing the ellipsis at the end in case the cells are to small for the text that is being shown.

**Tabulator Info**
Version 5.5.0

**Working Example**
https://jsfiddle.net/2vnqmwky/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
Go to the dropdown that mentions "Select the cell Alignment of the first Column:" and change the vertical alignment to middle or bottom.

**Expected behavior**
In case of changing/setting the vertical alignment, I would expect the text still to be(come) truncated. This is currently not the case.
_**Please note:**_ To underline the fact that the ellipsis don't work when setting the vertAlign property, the vertAlign property will not be set in case the Vertical Alignment to top.

**Additional context**
After doing some investigation, this problem occurs because of the fact that the display css property changes to inline-flex. After trying different approaches (adding additional divs to the cell's using a custom cell formatter) we unfortunately did not manage to get this functionality working properly.

**Comment by olifolkerd** [comment]
Hey @novasilva-jelle 

Thanks for the info, this is because in that mode it uses a flex layout which does not allow for elipsisizng of text.

In that layout as you have a lot of vertical space, i would suggest using the `textarea` formatter as that will allow the text to wrap.

Cheers

Oli :)
