### ISSUE TITLE
Multiselect filter while selecting items

### ISSUE THREAD

**Issue by n8diver** [olifolkerd/tabulator#4244]
Problem (still occuring in v5.5):
Since v5.2 there is the new list editor as a replacement for the select editor in headerFilter.
Behavior changed since then, since there is no instant filtering possible any more. You always have to close the selection popup for the list to get filtered.

Solution:
Restore the previous behavior

Temporary solution:
Look at the attached file to invoke a solution with very few code changes. All changes are marked with  FIXME:.

[tabulator.multiselect.js.txt](https://github.com/olifolkerd/tabulator/files/12094663/tabulator.multiselect.js.txt)

**Comment by olifolkerd** [comment]
The list editor does function correctly, when you select an item the filter is triggered, it does not filter table data while you type which is the correct behaviour. it should only filter the lists internal list
