### ISSUE TITLE
Icon reset filter in header-filter

### ISSUE THREAD

**Issue by PierreLeGit** [olifolkerd/tabulator#4245]
I think it is a bug:
Where is this icon? I cannot modify it:
Appear when focused and data not null

![Capture d’écran 2023-07-19 180115](https://github.com/olifolkerd/tabulator/assets/30028400/6d7d7b97-6d0a-4216-92be-7556a6b4dbdf)

**Comment by olifolkerd** [comment]
That is a search type input element, the cross is added by the browser, there is no control available for it
