### ISSUE TITLE
z-index of frozen cols is the same as for the column resizer-handles

### ISSUE THREAD

**Issue by zoi-smeraner** [olifolkerd/tabulator#4249]
**Describe the bug**
I descovered that the z-index of frozen cols is the same as for the column resizer-handles. That leads to the effect that you can click and move them, even if they are behind the frozen columns.

**Tabulator Info**
- 5.5.0

**Working Example**
https://jsfiddle.net/3129u06k/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to jsFiddle
2. Scroll a little to the right, so that more than one column is under the frozen first col.
3. Hover over the frozen col and you see the mouse pointer changing to resize because of the col resizer in the background

**Expected behavior**
Col in the back means resizer in the background.

**Screenshots**
I changed the bg color of the resizer to make it visible
![image](https://github.com/olifolkerd/tabulator/assets/109514429/f5c55f09-2a59-4623-9081-77d2eb295bb4)
![image](https://github.com/olifolkerd/tabulator/assets/109514429/47787369-a72f-414d-b589-64152f3ffdc1)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser chrome
 - Version 114.0.5735.205
 
I changed the following to fix it for me:

.tabulator-row .tabulator-cell.tabulator-frozen {
    z-index: 11;
}

**Comment by olifolkerd** [comment]
Hey @zoi-smeraner 

Thanks for the headsup,

I have pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)
