### ISSUE TITLE
headerWordWrap not working when layout "fitColumns" is used

### ISSUE THREAD

**Issue by toneb** [olifolkerd/tabulator#4251]
**Describe the bug**
```headerWordWrap ``` config is not working as expected when ```layout: "fitColumns``` is used.
![image](https://github.com/olifolkerd/tabulator/assets/616279/ec007297-2628-4478-9248-d230a0107fb1)

**Tabulator Info**
Version 5.5.1

**Working Example**
JS Fiddle: https://jsfiddle.net/wzc03do1/9/

**To Reproduce**
**Important** - on JS Fiddle it works on the first load, but doesn't work on subsequent loads (when CTRL+S is pressed, or javascript source is edited). On our site, it consistently doesn't work.
1. Open JS Fiddle, 
2. Go to javascript source and type "CTRL + S", or change source code to trigger reavaluation of JS Fiddle.

**Expected behavior**
Header text to be wrapped:
![image](https://github.com/olifolkerd/tabulator/assets/616279/6496f8d9-0f53-415e-8ecf-3c997381ab52)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome 115, Firefox 115

**Additional context**
Working workaround is to override ```CoreFeature.layoutRefresh``` method to also call ```verticallAlignHeaders```:
![image](https://github.com/olifolkerd/tabulator/assets/616279/e05e6ffd-c9df-413b-a818-b67b82824492)

**Comment by Paddy-Farmeye** [comment]
Also, experiencing the same issue.

**Comment by Paddy-Farmeye** [comment]
Hi @olifolkerd, no pressure. But just wondering if this is on a release schedule or is something folks should be circumventing themselves?

**Comment by olifolkerd** [comment]
Hey @toneb 

Thanks for the headsup, i have pushed a fix for this to the 5.6 branch and hope to release it in the next couple of weeks.

Cheers

Oli :)
