### ISSUE TITLE
Nested Tables don't get printed

### ISSUE THREAD

**Issue by McLoo** [olifolkerd/tabulator#4254]
**Describe the bug**
Nested Tables don't get printed

**Tabulator Info**
5.5.1

**Working Example**
https://jsfiddle.net/w5jLnxfb/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Load JS Fiddle 
2. Click on 'print'
3. --> only rows of main table are printed

**Expected behavior**
Print all nested tables
 
 **Screenshots**
 Table
![grafik](https://github.com/olifolkerd/tabulator/assets/5326916/278b47e9-ee93-4ac5-b9b5-50a621e11031)

Print Preview
![grafik](https://github.com/olifolkerd/tabulator/assets/5326916/2adc7e9d-4830-4995-bb28-0fcfce0e4f15)

**Comment by olifolkerd** [comment]
The print module does not support nested tables
