### ISSUE TITLE
about tfoot

### ISSUE THREAD

**Issue by Nsuidara** [olifolkerd/tabulator#426]
How made "tfoot" or block sorting row ? 
mean, i need "summary" rows :)

but NICE plugin!! Good JOB!

**Comment by Nsuidara** [comment]
Ok, i used grouping data and hide column... :) but meybe in feature ? normal ? tfoor pls

**Comment by olifolkerd** [comment]
Hey,

You can already create a table footer with the ***footerElement*** property:

```js
$("#example-table").tabulator({
    footerElement:$("<div class='tabulator-footer'><button>Custom Button</button></div>"); //set custom table footer with custom button
});
```

A column calculations row will be coming in the next update, see #351 for more info.

Cheers

Oli
