### ISSUE TITLE
ajax based paging/sorting/filtering with grouping 

### ISSUE THREAD

**Issue by vjnagar** [olifolkerd/tabulator#4260]
I have a big data set to render (>100000 records), I want to use this grid with its ajax based paging, sorting, filtering features but grouping does not work accordingly. Grouping is done based on what rows that have already arrived on the browser rather than from the server.

**Comment by olifolkerd** [comment]
Hey @vjnagar 

That is correct because grouping is a complex operation and should not be done with a partial data set.

Cheers

Oli :)

**Comment by vjnagar** [comment]
Thanks Oli, but are there any plans to support callbacks for such a feature?
