### ISSUE TITLE
multi column sorting is not working

### ISSUE THREAD

**Issue by cimenta** [olifolkerd/tabulator#4261]
**Describe the bug**
Multi column sorting is not working. The first column is sorted then after clicking next column's header while pressing CTRL I was expecting the second column to be sorted AND the first sorting to be kept. 

**Tabulator Info**
latest v5

**Working Example**
(https://jsfiddle.net/radek/np123x9k/8/)

-->

**Desktop (please complete the following information):**
 - OS: win11
 - Browser: latest firefox, latest Brave

**Comment by olifolkerd** [comment]
Hey @cimenta 

It is working correctly, it is just sorting first by the last column you clicked and then by the first.

You can change this behaviour by using the `sortOrderReverse` option
https://tabulator.info/docs/5.5/sort#sort-order

Cheers

Oli :)
