### ISSUE TITLE
The result of mutatorEdit is not checked to see if the data has changed or not

### ISSUE THREAD

**Issue by man9090** [olifolkerd/tabulator#4263]
The result of mutatorEdit is not checked to see if the data has changed or not. In some cases, this results in the history recording non-existent changes.

Tabulator v5.5.1

[Example](https://codepen.io/manell-reg/pen/JjeVygO)

A step by step guide to recreate the issue:

1. Change the value in "test column" from 10 to 100.
2. Press Enter key.
3. The value changed from 100 to 15.
4. Change the value from 15 to 150.
5. Press Enter key.
6. The value changed from 150 to 15.
7. Change the value from 15 to 150.
8. Press Enter key.
9. The value changed from 150 to 15.

10. Click button "Undo Edit".
11. The value has not changed (see 15)
12. Click button "Undo Edit".
13. The value has not changed (see 15)
14. Click button "Undo Edit".
15. The value changed (see 10)

Expected behavior:

Steps 11-14 should be omitted because there are no data changes

I fixed it by adding one line to the setValueProcessData method of the Cell class:

```
setValueProcessData(value, mutate, force){
	var changed = false;

	if(this.value !== value || force){

		changed = true;

		if(mutate){
			value = this.chain("cell-value-changing", [this, value], null, value);
			
			changed = this.value !== value || force; 	//new line  <<<<<<<<<<<<<<<<<<<<<<<<<<< 
		}
	}

	this.setValueActual(value);

	if(changed){
		this.dispatch("cell-value-changed", this);
	}

	return changed;
}
```

**Comment by olifolkerd** [comment]
Hey @man9090 

History is not changed as a result of mutation, it is only triggered on user edit, what the mutator does after that point is not part of the edit but a seperate process.

Cheers

Oli :)
