### ISSUE TITLE
The "horizontalPageBreak" parameter for autoTable does not work when creating a PDF.

### ISSUE THREAD

**Issue by abvas** [olifolkerd/tabulator#4265]
**Describe the bug**
The "horizontalPageBreak" parameter for autoTable does not work when creating a PDF.

**Tabulator Info**
Tabulator version 4.9.3

**Working Example**
```
  table.download("pdf", "data.pdf", {
    orientation:"portrait",
    autoTable:function(doc){
      return {
        styles: {
          minCellWidth: 50,
          horizontalPageBreak: true,
        },
      };
    },
  });
```
An live example is here:
[https://codepen.io/abvas/pen/YzRbKRg?editors=0010](https://codepen.io/abvas/pen/YzRbKRg?editors=0010)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Click the "Create PDF" button

**Expected behavior**
The table is wider than the width of the page and must be divided into two parts.
But instead, the table goes outside the document and is not split.

**Screenshots**
![Image 12](https://github.com/olifolkerd/tabulator/assets/47285364/14228fb9-1e27-427c-b043-ac3e7c5752c6)

What am I doing wrong?
Thank you.

**Comment by olifolkerd** [comment]
Hey @abvas 

Please raise this with autoTable, Tabulator just passes those options straight to the library, it has no control over the creation of the table.

Cheers

Oli :)
