### ISSUE TITLE
Placeholder not working in basic rendering

### ISSUE THREAD

**Issue by notetwo** [olifolkerd/tabulator#4267]
**Describe the bug**
The placeholder for filtering isnt initialised when using basic rendering. It will appear once you change the row count, but it wont be vertically centered.

**Tabulator Info**
V5.5

**Working Example**
https://jsfiddle.net/rgLu3on0/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Filter any row with the header filter so that no row remains
2. if you change the row count now, it the placeholder will appear

**Expected behavior**
I expect it to behave the same way it does in virtual rendering

**Desktop (please complete the following information):**
 - OS: Win10/11
 - Browser chrome
 - Version  115.0.5790.171 Official Release

**Comment by see365** [comment]
you can temporarily solve this problem by covering your style as follows:
.tabulator .tabulator-tableholder .tabulator-placeholder {
  justify-content: flex-start;
}

**Comment by notetwo** [comment]
Hi @see365, sorry for the late response. People on the discord also mentioned that, but that isnt the problem. The problem is that the placeholder element itself is never created, until the table is somehow updated, for example by changing the page size. Even then its not vertically centered like it is in virtual rendering. If you go on my fiddle, filter the data, so that no rows are visible and then inspect the table, you will see that div.tabulator-tableholder only contains div.tabulator-table. div.tabulator-placeholder is missing.

**Comment by olifolkerd** [comment]
Hey @notetwo 

I have pushed a fix for this to the 5.6 branch which i hope to release in the next couple of weeks.

Cheers

Oli :)
