### ISSUE TITLE
widthGrow not working when used on TH element

### ISSUE THREAD

**Issue by kczx3** [olifolkerd/tabulator#4268]
**Describe the bug**
When attempting to load from an HTML table, the widthGrow property for a column definition does not work properly if used as "tabulator-widthGrow" on the TH element.

**Tabulator Info**
5.5.0

**Working Example**
https://jsfiddle.net/193dq72t/

**To Reproduce**
View above JSFiddle.
Both tables should have the first column rendered with a `widthGrow` of 3 however the first table, which uses the `tabulator-widthGrow` attribute, does not.

**Expected behavior**
The first table should properly render the first column's width just the same as if the property were defined on the column via the `columns` option.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Edge
 - Version: 115

**Smartphone (please complete the following information):**
Untested on mobile

**Comment by olifolkerd** [comment]
Hey @kczx3 

Thanks for the headsup,

I have pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)
