### ISSUE TITLE
materializecss - bad display header in modals/collapsible

### ISSUE THREAD

**Issue by Nsuidara** [olifolkerd/tabulator#427]
Hi, again :) 

I have problem with
```
            if (this.parent.isGroup) {
                this.element.css("height", this.parent.getGroupElement().innerHeight());
            } else {
                this.element.css("height", this.parent.getElement().innerHeight());
            }
```
what problem ? i don't know about bootstrap but
i have problem with http://materializecss.com/modals.html "modals"
because when i put table into modals 

header columns 
this.element.css("height", this.parent.getElement().innerHeight());
return -1
and columns isn't visable...

**Comment by olifolkerd** [comment]
Hi,

Im sorry i dont follow what you are asking, there is no callback anywhere in Tabulator that will give you meaningful access to the ***this*** variable.

Could you post a copy of the entire callback you are trying to use and explain a bit more about what you are trying to achieve?

**Comment by Nsuidara** [comment]
The problem exists also in collapsible too http://materializecss.com/collapsible.html

clue, i comment in **"Column.prototype.verticalAlign = function (alignment) {"** this lines
```
            // if (this.parent.isGroup) {
            //     this.element.css("height", this.parent.getGroupElement().innerHeight());
            // } else {
            //     this.element.css("height", this.parent.getElement().innerHeight());
            // }
```
is example, problem 
http://imgur.com/AcJR1Cc
when i comment... 
http://imgur.com/3v4FLyq

**Comment by olifolkerd** [comment]
That is happening because you are creating the table when the table is hidden so it cannot correctly work out the height of the header element.

You need to call the ***redraw*** function straight after making the table visible, that will solve the problem.

```js
$("#example-table").tabulator("redraw", true);
```

Let me know if that helps

Cheers

Oli
