### ISSUE TITLE
5.5.1 Cells are not editable in reponsive layout mode

### ISSUE THREAD

**Issue by ortwic** [olifolkerd/tabulator#4275]
**Describe the bug**
When reponsive layout mode is enabled the expanded cells are not editable anymore.

**Tabulator Info**
5.5.1

**Working Example**
https://stackblitz.com/edit/typescript-vcgxg4?file=index.ts

**To Reproduce**
Try to change value of favorite color or lucky number from the stackblitz example.

**Expected behavior**
Cells should stay editable regardless whether in collapsable area or not.

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome, Firefox
 - latest

**Comment by lekoala** [comment]
it's not a bug, it's currently designed this way

there is a work in progress PR that i made https://github.com/olifolkerd/tabulator/pull/3875 but my current approach is not 100% aligned with what oli thinks good :-)

If you need this, in the meantime you can use my custom element that implement the custom features that i need
https://formidable-elements.vercel.app/demo/tabulator-grid.html (check the flexResponsive example)

**Comment by ortwic** [comment]
Thank you very much. I'll give it a try. 

Is it generally possible to inject "own" modules for tabulator? It kinda looks that way.

**Comment by ortwic** [comment]
I tried to register the module but it was not working. 

Copying the logik from tabulator isn't an ideal solution neither.
https://github1s.com/lekoala/formidable-elements/blob/master/src/classes/TabulatorGrid.js

It would be really helpful if you'd be able to access the row handle when using a custom func for the responsible layout.

**Comment by ortwic** [comment]
The fix is actually quite easy. I can do a PR if desired.
