### ISSUE TITLE
The height of cells is not being properly updated 

### ISSUE THREAD

**Issue by mhlozek** [olifolkerd/tabulator#4277]
**Describe the bug**
The height of cells is not being properly updated when I resize the table.

**version 5.4.4:**
- the cells stretch end expand according to its content

**version 5.5.1:** 
- in Chrome browser rows expand in height, but when I enlarge the window, the rows remain too tall
- in Firefox content is cropped when I narrow the window, and rows are too tall when I enlarge window

**Tabulator Info**
- Which version of Tabulator are you using? latest - 5.5.1

**Working Example**
https://codepen.io/mhlozek-the-bold/pen/vYvEMvw

**To Reproduce**
Open codepen link and try to resize the window.

**Expected behavior**
The height of rows (cells) should be properly calculated and refreshed when I resize window/container.

**Screenshots**
version 5.4.4 (showing correct behavior):
https://github.com/olifolkerd/tabulator/assets/2743172/e376e204-2e9c-4669-ae04-3be2f4db9f48

version 5.5.1 (cells stays too tall when I expand the window):
https://github.com/olifolkerd/tabulator/assets/2743172/733717a4-8b69-4e1f-b990-b497800f5348

**Desktop (please complete the following information):**
 - OS Windows 11
 - tested in latest Chrome and Firefox browsers

**Comment by lieser** [comment]
I encountered the same bug (version 5.5.2), and found the following workaround that works for me if added to the example above:
```js
faq.eventBus.subscribe("table-redraw", (force) => {
  if (!force) {
    for (const row of faq.getRows()) {
      row.normalizeHeight();
    }
  }
});
```

**Comment by mhlozek** [comment]
Thank you very much @lieser! 
Seems to be working good without any performance issues. 
It was a blocking error for me that prevented me from updating to version 5.5. Now it's (temporarily) resolved 👍

**Comment by olifolkerd** [comment]
Hey @mhlozek 

Thanks for the headsup, i have pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)
