### ISSUE TITLE
Setting the height of the table to a smaller size after the table is built leads to data appearing twice

### ISSUE THREAD

**Issue by crispzendisc** [olifolkerd/tabulator#4278]
**Describe the bug**

Setting the height of the table to a smaller size after the table is built leads to data appearing twice when initially scrolling through the table. Additionally, two even rows will appear next to each other.

**Tabulator Info**

v5.5

**Working Example**

JSFiddle: https://jsfiddle.net/cxr75h8n/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to [that link](https://jsfiddle.net/cxr75h8n/)
2. Click `Run`
3. Scroll down through the table. Entries from the top of the table will reappear further down the first time you scroll through.

**Expected behavior**

The original data should appear as expected when scrolling through.

**Screenshots**

Initially, before scrolling down through the table:

![image](https://github.com/olifolkerd/tabulator/assets/53126331/242a5fa9-6e04-437d-a49e-9696daeefa14)

Then, scrolling down a bit:

![image](https://github.com/olifolkerd/tabulator/assets/53126331/5516a719-8d44-4836-953c-3c5498303eab)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 116

**Smartphone (please complete the following information):**
 
NA

**Additional context**

None

**Comment by piccit** [comment]
Another data point is that `getRows('visible')` returns the wrong number of rows when this happens. Calling `rowManager.reRenderInPosition()` seems to fix the issue, but this is not invoked during the call to setHeight because `adjustTableSize` is returning false. Seems like adjustTableSize returns false because fixedHeight is true, but it seems like that's a logic flaw since we actually _are_ changing the height in this scenario

```js
table.on('tableBuilt', () => {
window.setTimeout(()=>{
  console.log(table.getRows('visible').length);
  table.setHeight(200);
  console.log(table.getRows('visible').length);
  //table.redraw(true);
  table.rowManager.reRenderInPosition();
  console.log(table.getRows('visible').length);
  }, 5000);
});
```

```
"Running fiddle"
12
1
8
```

**Comment by olifolkerd** [comment]
Hey @piccit 

I have pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)
