### ISSUE TITLE
How to add classed to a particuler cell

### ISSUE THREAD

**Issue by appl4e** [olifolkerd/tabulator#428]
In my table there is a column which will have cells with contents and their background color will vary according to the class attribute we add to that cell.

How can I do that with tabulator.  Those classes have the necessary style for the cell.

**Comment by olifolkerd** [comment]
Hey,

You  can use a custom formatter to do this:

```js

//create custom formatter
var cellClassFormatter = function(cell, formatterParams){
    //cell - the cell component
    //formatterParams - parameters set for the column

    cell.getElement().addClass("custom-class");

    return cell.getValue(); //return the contents of the cell;
},

//create table
$("#example-table").tabulator({
    columns:[
        {title:"Name", field:"name", formatter:cellClassFormatter},
    ],
});
```
Let me know if that helps

Cheers

Oli

**Comment by appl4e** [comment]
Hi,

I understood your code but that will add the same class for all cells in a column right?

But what if I just want to add a class to the 4th cell of 2nd column... How do I do that?

Sorry I am new to tabulator.... 

Thanks
Apple

**Comment by olifolkerd** [comment]
Hey Apple,

How will you be deciding which cell gets a given class, will it be decided based on an attribute in that rows data?

Cheers

Oli

**Comment by G-IV** [comment]
I can't find this answered anywhere - if you want me to reopen this somewhere else I can.  In my case, when a cell is edited, I want to be able to add a class indicating to a user that that cell was edited.

I just can't find any way that I can do this - is there any chance you could help out with this?
