### ISSUE TITLE
feat: indent mult line textarea when using datatree

### ISSUE THREAD

**Issue by lukecotter** [olifolkerd/tabulator#4282]
*Is your feature request related to a problem? Please describe.**
If you have the data tree control element in the same column as a text area the second line in the text area will be aligned fully left instead of aligning to the start of the text from the above row.

**Describe the solution you'd like**
I would like all following rows of the wrapped text to align with the text above when it is in the same cell as the datatree element.

I have implemented a work around by doing this
```
const el = cell.getElement();
el.style.whiteSpace = "pre-wrap";

const row = cell.getRow();
if (row._row.modules.dataTree) {
  const row = cell.getRow();
  const treeLevel = row._row.modules.dataTree.index || 0;
  const indent = cell.getTable().options.dataTreeChildIndent || 0;
  const levelIndent = treeLevel * indent;
  el.style.paddingLeft = `${levelIndent + 4}px`;
  el.style.textIndent = `-${levelIndent}px`;
  el.style.wordBreak = 'break-all';
}

return this.emptyToSpace(this.sanitizeHTML(cell.getValue()));
```
The only issue is that this would cause an unwanted indent for other cells in the row that use the datatree and textarea.
So this indent should only apply to the cell with the control element (expand/ collapse).

**before**
![Screenshot 2023-08-25 at 17 35 15](https://github.com/olifolkerd/tabulator/assets/4013877/0ee9a23d-434c-4235-aa03-002958e7e16a)

**after**
![Screenshot 2023-08-25 at 17 55 54](https://github.com/olifolkerd/tabulator/assets/4013877/c1f80f63-267e-4759-b4ef-fa7bea6c574f)

**Describe alternatives you've considered**

**Additional context**

**Comment by olifolkerd** [comment]
Hey @lukecotter 

If you create an empty column on the left of your table that you use to hold the tree toggle then this will work out the box.

Cheers

Oli :)

**Comment by lukecotter** [comment]
@olifolkerd You are right, that does work and thanks for the suggestion.
However the toggle and text do not align and indent quite right and with a tree of unknown depth it is hard to get the width of column 1 right the way I have things setup.

I think I will keep my workaround for now 👍🏻
