### ISSUE TITLE
Tabulator integration with PostgREST

### ISSUE THREAD

**Issue by igor-suhorukov** [olifolkerd/tabulator#4284]
Tabulator is perfect for table display in JavaScript with rich feature set. PostgREST provide ready to use and uniform API endpoints for table/view/procedure in database with pagination and sorting support. It will allow make fast prototype for data related applications. It also provide OpenAPI schema for each endpoint.

I am expect the same magic like "autoColumns:true" do if I provide RestAPI of PostgREST in Tabulator parameter. It can parse schema, create column definition from it, auto fetch data from provided API and allow use pagination. To customize Tabulator behavior some extension/redefenition point like autoColumnsDefinitions:function(definitions) expected. ajaxURL works perfect until parameter paginationMode:"remote" activated. Server side pagination not works as expected.

I compare different solution like ToolJet, Directus, react-admin, Jmix, supabase, appsmith and all this projects are to heavyweight for existing table rendering from PostgreSQL. TanStack Table, ag-grid, react-data-grid is not so easy to use like Tabulator

**Comment by olifolkerd** [comment]
Hey @igor-suhorukov 

Thanks for getting in touch,

Im afraid i dont build out integrations with specific 3rd party libraries into the core library otheriwse things would become very bloated, I tend to try and keep the core very generic,

but if you want to build you a custom module yourself i would happily include a reference from the Tabulator website.

A guide to building your own module can be found here:
https://tabulator.info/docs/5.5/module-build

Cheers

Oli :)

**Comment by igor-suhorukov** [comment]
@olifolkerd got it, thank you and all community for awesome tabulator

**Comment by igor-suhorukov** [comment]
FYI [generate a simple web interface for viewing PostgreSQL tables](https://habr-com.translate.goog/ru/articles/757990/?_x_tr_sl=ru&_x_tr_tl=en&_x_tr_hl=ru&_x_tr_pto=wapp&_x_tr_hist=true)
