### ISSUE TITLE
headerFilter 'list' position

### ISSUE THREAD

**Issue by dbauszus-glx** [olifolkerd/tabulator#4285]
Is it possible to control the positioning of the input 'list' element used in a headerFilter with **Tabulator 5.5.2**?

I created a very basic [example on codepen](https://codepen.io/dbauszus-glx/pen/RwEaQLq):

```js
new Tabulator(document.getElementById("Table"), {
  layout: "fitColumns",
  columns: [
    {
      title: "Number",
      field: "number"
    },
    {
      title: "Letter",
      field: "letter",
      headerFilter: "list",
      headerFilterFunc: "in",
      headerFilterParams: {
        values: ["A", "B", "C", "D"],
        multiselect: true,
        clearable: true
      }
    }
  ],
  data: data
});
```

The list input is off the screen...
![image](https://github.com/olifolkerd/tabulator/assets/22201617/17e493be-a963-44de-892e-1a3b19f5da9d)

**Comment by nickswalker** [comment]
The behavior appears to be the same in 6.3.0:

https://codepen.io/nickswalker/pen/GRVVBjv

**Comment by rajniszp** [comment]
Problematic fragment of code:
https://github.com/olifolkerd/tabulator/blob/2febe77981eec51803fd40e5ee5e97e02321b170/src/js/core/tools/Popup.js#L182-L215
If `document.body` is the popup parent element (`this.container`) and width/height of the body is not 100% of viewport, it may go crazy. Maybe if `this.container == document.body` it would be worth checking `document.documentElement.clientWidth` / `.clientHeight`?

Also, it does not check if it won't go out of bounds the other way, so it can still display out of the viewport - that's another TODO.

Temporary workaround:
```css
body {
  min-width: 100dvw;
  min-height: 100dvh;
  box-sizing: border-box;
}
```
(https://codepen.io/rajniszp/pen/EaxZPdO)

Unfortunately it also "remembers" if it was reversed in horizontal direction (`this.reversedX = true`). This flag was added with submenu functionality in 2021, so I guess it provides proper positioning of submenus. Setting it to `false` in `hide` method fixes the problem, but I am not sure if it does not cause another one in submenus, thus no PR from me.

@olifolkerd I am sorry to tag you, but please reopen - it's still an issue.

**Comment by hdbonnett** [comment]
This is still an issue in 6.5.0 on both Firefox and Chrome (on Windows 11). The fix by @rajniszp works for me.

> Temporary workaround:
> 
> body {
>   min-width: 100dvw;
>   min-height: 100dvh;
>   box-sizing: border-box;
> }
