### ISSUE TITLE
Editor method is not called again unless focus is set on a different but not adjacent row.

### ISSUE THREAD

**Issue by dbauszus-glx** [olifolkerd/tabulator#4286]
Tested with Tabulator 5.5.2

[I've created a codepen for a very simple custom date type input.](https://codepen.io/dbauszus-glx/pen/KKbMewL)

I'd expect to click on a cell and execute the editor. Then on success I'd be able to click on the same or any other cell and edit that cell.

What happens is. I click on a cell and can edit that cell. I then must edit a cell which is not the same or in the previous/next row.

```js
    {
      title: "Date",
      field: "date",
      formatter: (cell, formatterParams, onRendered) => {
        let val = parseInt(cell.getValue());

        if (isNaN(val)) return;

        let str = new Date(val * 1000).toLocaleString("en-GB", {
          year: "numeric",
          month: "short",
          day: "numeric"
        });

        // Colour text red if account has expired.
        return val < new Date() / 1000
          ? `<span style="color:red;">${str}</span>`
          : str;
      },
      editor: (cell, onRendered, success, cancel) => {
        let rowData = cell.getRow().getData();

        var editor = document.createElement("input");

        editor.setAttribute("type", "date");

        if (!rowData.expires_on) {
          const date = new Date();
          editor.value = date.toISOString().slice(0, 10);
        } else {
          const date = new Date(rowData.expires_on * 1000);
          editor.value = date.toISOString().slice(0, 10);
        }

        onRendered(function () {
          editor.focus();
        });

        function successFunc() {
          const val = new Date(editor.value).getTime() / 1000 || null;
          console.log(val);
          cell.setValue(val);
        }

        editor.addEventListener("blur", successFunc);

        return editor;
      }
    }
```

**Comment by sonal1687** [comment]
I am also facing same issue with custom editors.

**Comment by olifolkerd** [comment]
Hey @sonal1687 

This is because of the unique way that the date type input element functions, and the fact that you are only handling successful edits and not cancelling on abort.

If you use the built in date editor you will see it behaves correctly.

The code for the built in date editor can be found here:
https://github.com/olifolkerd/tabulator/blob/master/src/js/modules/Edit/defaults/editors/date.js

Cheers

Oli :)

**Comment by dbauszus-glx** [comment]
@olifolkerd  Thanks for explaining this. I have now updated my codepen to make this work.
