### ISSUE TITLE
Placeholder is not cleared when "rowDelete" undo or "rowAdd" redo actions triggered 

### ISSUE THREAD

**Issue by Deejerz88** [olifolkerd/tabulator#4287]
**Describe the bug**
When the last row of a table is deleted and then table.undo() is triggered, if a placeholder exists, the placeholder element is not cleared and remains underneath the row that was added back to the table.

Similarly, if a row is added, then table.undo() is triggered, then table.redo() is triggered, the placeholder remains under the added row.

**Tabulator Info**
- Which version of Tabulator are you using? 5.5.2

**Working Example**
https://codesandbox.io/p/sandbox/tabulator-placeholder-bug-hdhjtv?file=/app/Table.tsx

**To Reproduce**

Undo:
1. Go to codesandbox link
2. Click on the check in the Delete Row column
3. Click Undo button above the table
4. Row is added back and placeholder remains under the added row

Redo:
1. Click on the check in the Delete Row column to remove row
2. Click on the Add Row button to add a new row
3. Click Undo to remove the new row
4. Click Redo to add the row back
5. Row is added back and placeholder remains under the added row

**Expected behavior**
The placeholder should be removed when a row is added back to an empty table using undo or redo.

**Screenshots**

![image](https://github.com/olifolkerd/tabulator/assets/103090951/37592fb0-b6c9-497d-b4ff-6ca45350f2e3)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 116.0.5845.141 (Official Build) (64-bit)

**Additional context**
In my fork, I added 
```
if (this.table.rowManager.getDisplayRows().length) {
	this.table.rowManager._clearPlaceholder();
}
```
to the default undoers rowDelete method and default redoers rowAdd method of the History module to produce the desired results.

Thanks for your hard work on everything!

**Comment by olifolkerd** [comment]
Hey @Deejerz88 

Thanks for the headsup, i have pushed a fix for this to the 5.6 branch that i hope to release in the next couple of weeks.

Cheers

Oli :)
