### ISSUE TITLE
Dot in column name makes all column elements invisible

### ISSUE THREAD

**Issue by pietrodito** [olifolkerd/tabulator#4288]
**Describe the bug**
Dot in column name makes all column elements invisible

**Tabulator Info**
5.5.2

**Working Example**
https://jsfiddle.net/pietrodito/h8dstLf1/2/

**Comment by pietrodito** [comment]
This is expected behavior: dot is used to treat nested objects...

**Comment by olifolkerd** [comment]
https://tabulator.info/docs/5.5/columns#field-nesting
