### ISSUE TITLE
Requesting for tabulator to provide an option for scrolling to specific position in vertical scrollbar.

### ISSUE THREAD

**Issue by rakshithns10** [olifolkerd/tabulator#4291]
We need tabulator to provide an option for scrolling to specific position in vertical scroll bar.

Currently tabulator provides option for scrolling to specific row. But there no option to scrolling to specific position. We have a scenario where we have tabulator and DHTMLX gantt side by side in a single container and using the gantt vertical scroll bar to scroll to any position parallelly syncing the tabulator rows. Here we are using the scrolled position of the gantt scroll bar and internally calculating the specific row to be scrolled on tabulator by performing some rounding operation on gantt scrolled position by tabulator row size. This extra calculation is being done to adjust the gantt scroll bar to correct position once the tabulator is correctly scrolled to row as we don't have an option in tabulator to scroll to a spefic position. 

Below is an example about syncing of rows between dhtmlx gantt and Tabulator. Here we are using the tabulator table holder to adjust the position. But still there is inconsistency in sync as the tabulator takes some time to render rows if it contains huge data. We need tabulator to provide a way to scroll to specific position just like scrollToRow().

https://snippet.dhtmlx.com/5/08cf6704d

**Comment by olifolkerd** [comment]
Hey @rakshithns10 

Because Tabulator uses a virtual DOM and the actual height of each row is not known until it is rendered, it would not be practical to add a scroll to Y-axis feature to the table, because without rendering all the rows between the current position and the new position, the table would not know which row to show.

Cheers

Oli :)
