### ISSUE TITLE
New module: Spreadsheet Mode - Google Sheets style row, column, and cell selection.

### ISSUE THREAD

**Issue by rathboma** [olifolkerd/tabulator#4294]
This has been brought up before (#3095), but I think it's time to build it.

I plan on having myself, or another Beekeeper Studio team member, tackle this work. So I'm detailing below all the different features this needs.

Broad goal: Column, row, and cell selection should 'just work like Google Sheets'.

## Row selection features:
- [ ] The first column of the table is module-provided, and displays the row number. We call this the 'row header' (similar to the column header)
- [ ] Clicking the row header selects that row
- [ ] Clicking row-header x and dragging vertically  to row y selects all rows that were moused over in range {x..y}
    - Note, the mouseover might move into the table cells, this is ok.
- [ ] Clicking a row header x, then shift-clicking row-header y selects all rows in the range {x..y}
- [ ] Clicking a row header x then ctrl/meta cliking row-header y selects rows {x, y}
- [ ] Ctrl/Meta + C when rows are selected copies them to clipboard in an excel-friendly format

https://github.com/olifolkerd/tabulator/assets/279769/8a26e8af-5475-42fb-8dae-2260e29abede

## Column selection features
Column selection behaviors are the same as row selection behaviors.
- [ ] The column header is modified such that clicking the header does NOT sort by that column, instead a button is added to the right of the column title for actions such as sorting and filtering
- [ ] Clicking the column header selects that row
- [ ] Clicking col-header x and dragging horizontally  to col y selects all cols that were moused over in range {x..y}
    - Note, the mouseover might move into the table cells, this is ok.
- [ ] Clicking a col header x, then shift-clicking col header y selects all cols in the range {x..y}
- [ ] Clicking a col header x then ctrl/meta cliking col-header y selects cols {x, y}
- [ ] Ctrl/meta + C when cols are selected copies them to clipboard in an excel-friendly format

https://github.com/olifolkerd/tabulator/assets/279769/961687e3-9480-4cb7-a2c3-5fc105bb166c

## Cell selection features
This is the most complex behavior. It behaves with similar primitives to the row and column selection
- [ ] Clicking a cell selects that cell (easy)
- [ ] Clicking cell a,x and dragging horizontally or vertically  to cell b,y selects all cells that were moused over in range {a..b, x..y}
    - Note, that this is a rectangle of cells
- [ ] Clicking a cell a,x, then shift-clicking cell b,y selects all cells in the range {a..b, x..y}
- [ ] Clicking a cell a,x then ctrl/meta cliking cell b,y selects cells {a,x & b,y}
- [ ] Ctrl/meta + C when cells are selected copies them to clipboard in an excel-friendly format

https://github.com/olifolkerd/tabulator/assets/279769/252fd6fb-ef55-4d6f-b268-a96a6bf90447

## For all cases
- [ ] Clicking any cell, or header clears the current selection, even if clicking on a cell in the selected range
- [ ] Right-clicking in the selected area DOES NOT clear the selection, but provides an appropriate context menu
- [ ] Right clicking OUTSIDE of the selected area does clear the selection
- [ ] Escape does not clear the selection
- [ ] Clicking outside of the table area does not clear the selection

**Comment by rathboma** [comment]
Implementation notes:
- Row headers should be implemented as a frozen column without a title. Make sure this value isn't part of table exports!
- Draft off-of other modules like [this one](https://github.com/olifolkerd/tabulator/blob/master/src/js/modules/ResizeColumns/ResizeColumns.js) to get a sense of how to do things
- This will require use of Tabulator's [Internal Event Bus](https://tabulator.info/docs/5.5/events-internal#overview). Don't use the public events, use these internal ones.
- This should be a PR that creates a new file in a folder:  `src/js/modules/SpreadsheetMode`
- It should work in Beekeeper Studio, so add any hooks or events you need for this (<-- this is for whoever at BKS implements this)
- There was a prior attempt at this (https://github.com/olifolkerd/tabulator/pull/3096/files). It's really out of date, don't bother looking at it as it is based on old APIs and ways of doing things in Tabulator

**Comment by joebonneau** [comment]
Hey @rathboma - I wouldn't say that I was going as far as implementing all of the things you listed above, but I have started up on a fork that aims to implement cell-level selection and copy/paste functionality. This is also an effort related to my full-time job and will become relevant to pick back up within Q4 when the related project starts up.

I'm curious if it might be valuable to touch base or collaborate in some way on this.

**Comment by olifolkerd** [comment]
Hey @rathboma 

You will be happy to hear that I merged in the pr a couple of weeks back and have refactored and extended it into a new "Selectable Range" module, that breaks apart a load of the built-in features from the PR into user customizable options.

It now adds cell range selection along with a load of customizable options for column header behaviour and optional row header cells.

Im aiming to get this out in the 5.6 release in the next couple of weeks and would welcome any feedback on ways to extend/improve the initial offering.

Cheers

Oli :)

**Comment by revofusion** [comment]
hey @olifolkerd the range selection works great, only wish is that if you are dragging a range and go to the end of visible rows, it continues moving the sheet down as a user would expect
