### ISSUE TITLE
Validation isn't performed on every row in the table

### ISSUE THREAD

**Issue by TI-AviBerko** [olifolkerd/tabulator#4296]
**Describe the bug**
Validation isn't performed on every row in the table.
Rows that weren't scrolled into view aren't validated.
This can be observed when calling .validate() as it will return an incrementally larger list of rows when scrolling through a table with a lot of validation errors.

A workaround is to call row.getCells() for every row, and then call validate() which will return the correct array, although highlighting of failed cells is still wrong.

**Tabulator Info**
- v5.4.4
- v5.5.0
- 
**Working Example**
[https://jsfiddle.net/aviberko/qphs4t3f/](url)

This example creates a table with a validator on the "name" column that always returns false.

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:

Scenario #1
1. Wait 5 seconds for the table to be created
2. Click on row #1
-  The jsfiddle console should print out: "validation errors: 20" (it might be a slightly different number depending on your view port, 
at the very least it should be less than 100.
- Only a portion of the cells are highlighted
4. Scroll down to row #20 and click on it
-  The console print out should output a validation error number higher than 20
- Only a portion of the cells are highlighted
6. Scroll to the end, and press a row.
- The console print out should say 102
- All the cells should be highlighted now

# Scenario #2 - workaround
1. Uncomment line 34 in the javascript code in the HTML view
2. Repeat Scenario #1
- This time the console output should always report 102 validation errors, but the highlighting won't work correctly until you reach the end of the table.
 
**Expected behavior**
Validation should work on every validated cell and highlighted correctly.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser vscode 1.8x Firefox 102

**Additional context**

**Comment by TI-AviBerko** [comment]
**Describe the bug**
Validation isn't performed on every row in the table.
Rows that weren't scrolled into view aren't validated.
This can be observed when calling .validate() as it will return an incrementally larger list of rows when scrolling through a table with a lot of validation errors.

A workaround is to call row.getCells() for every row, and then call validate() which will return the correct array, although highlighting of failed cells is still wrong.

**Tabulator Info**
- v5.4.4
- v5.5.0
- 
**Working Example**
[https://jsfiddle.net/aviberko/qphs4t3f/](url)

This example creates a table with a validator on the "name" column that always returns false.

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:

Scenario #1
1. Wait 5 seconds for the table to be created
2. Click on row #1
-  The jsfiddle console should print out: "validation errors: 20" (it might be a slightly different number depending on your view port, 
at the very least it should be less than 100.
- Only a portion of the cells are highlighted
4. Scroll down to row #20 and click on it
-  The console print out should output a validation error number higher than 20
- Only a portion of the cells are highlighted
6. Scroll to the end, and press a row.
- The console print out should say 102
- All the cells should be highlighted now

# Scenario #2 - workaround
1. Uncomment line 34 in the javascript code in the HTML view
2. Repeat Scenario #1
- This time the console output should always report 102 validation errors, but the highlighting won't work correctly until you reach the end of the table.
 
**Expected behavior**
Validation should work on every validated cell and highlighted correctly.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser vscode 1.8x Firefox 102
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by olifolkerd** [comment]
This is the correct behaviour, validation is ONLY for user edited data, you may load any data you like into the table

Cheers

Oli
