### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by tranquochuy29** [olifolkerd/tabulator#43]
Hi all,

First of all, thank you so much for your library and for everything.
This is amazing library. Everything is really great.
And I have a small idea.
Could we enhance a new function to allow user in order to filter on each column ?
I mean that we will have a textbox below the caption (header).
And then user can enter some text for filtering.
How do you think about that ?
Thank you so much for your time.

Cheer,
Tony

**Comment by olifolkerd** [comment]
Hi Tony,

Thanks for the kind words, Its always great to hear people are enjoying Tabulator!

That is a great idea i can see when it would be useful to people. the great news is it is entirely possible with a bit of jiggery pokery with the existing system. as it is such a great idea i will add a new example of exactly that in the examples section in the next few days and post a link here when it is up.

Cheers

Oli

**Comment by olifolkerd** [comment]
I have added an example of how to do this to the demo section of the website:

[Column Header Filtering Demo](http://olifolkerd.github.io/tabulator/examples/#filter-header)

This uses the standard Tabulator library without any modifications.

The demo does case insensitive comparison for strings (any partial match counts) and direct comparison for other data types.

let me know if you need any further info.

Cheers

**Comment by tranquochuy29** [comment]
Hi there,

Thank you so much for your information.
I wish you have a good day.
I checked that. It's really awesome.
But I think you forgot to udpate the documentation. Is that right ?
Because we do not see the configuration for the column.

[image: Hình ảnh nội tuyến 1]

Thank you so much for your help from my heart.

Cheer,
Tony

2016-08-10 2:09 GMT+07:00 Oli Folkerd <notifications@github.com>:

**Comment by olifolkerd** [comment]
Your image hasn't made it into your comment.

What do you mean you cant see the the configuration for the column? if you look at the source for the page you can see the script used to build the table.

**Comment by tranquochuy29** [comment]
Hi there,

Thank you so much for your reply.
I mean that is there a place to declare that we will use the filter
function on column (yes or not) ?
For example:

filterOnClumn: true|false


$("#example-table").tabulator({
    columns:[
        {title:"Name", field:"name", sortable:true, filterOnClumn:
true|false , sorter:"string", width:200, editable:true}
    ],});

Because I don't see that configuration in the documentation.
Could you let me know where is it ? Because I cannot find that. Do I have
to download a new version ?

Thank you so much.

Cheer,
Tony



2016-08-10 13:34 GMT+07:00 Oli Folkerd <notifications@github.com>:

**Comment by olifolkerd** [comment]
There is no specific setting, it uses a number of features together to deliver the functionality you want, if you look in the scripts section of the [Examples Page](http://olifolkerd.github.io/tabulator/examples/) on the website you will see the definition of the table that creates the filters.

I will have a play with the demo site this evening and add some toggles for showing source under the table.

**Comment by tranquochuy29** [comment]
Hi there,

Thank you so much for your reply.
I will have a check from my side.
Btw, this lib is amazing and awesome.

Thank you so much for your support.

Cheer,
Tony

2016-08-10 14:21 GMT+07:00 Oli Folkerd <notifications@github.com>:

**Comment by olifolkerd** [comment]
I have added a new view source button below each example on the examples site so you can now see the code used easily.

Checkout the [Filter Data In Header Example](http://olifolkerd.github.io/tabulator/examples/#filter-header) for more information;

**Comment by tranquochuy29** [comment]
Hi there,

How are you today ?
During working with your library, I found out one issue.
I also give you the solution.

As you see the below image, the *deleteRow* function.

At the comment *//remove from data*, we should change
*item.tabulator_delete_row
*to *rowData.tabulator_delete_row.*
Because *item* is a not apart of loop. In this case, *line* *variable* will
have no value. And we cannot delete the selected row in *actual data
(self.data*)
You can try one time by this step.

1. Filter data by an column.
2. Select one row and delete that row. The selected row is disappear.
3. Repeat with step 1. You will see the deleted row again. Because we
cannot delete the selected row in *actual data (self.data*)
So that's why I say '*we should
change item.tabulator_delete_row to rowData.tabulator_delete_row*'

​


Thank you so much for your time.

Cheer,
Tony


2016-08-11 1:55 GMT+07:00 Oli Folkerd <notifications@github.com>:

**Comment by olifolkerd** [comment]
Hi Tony,

Thanks for the information, that was a good catch.

You were close with the solution. What actually needed doing was the line

```js
var line = self.data.find(function(rowData){
```
needed replacing with the line

```js
var line = self.data.find(function(item){
```

This has now been fixed and committed.

Just as a note for the future, would you mind creating a new issue if you find a new bug rather than adding it to the bottom of an existing bug. It will make it easier to track the progress of fixing things.

Cheers
