### ISSUE TITLE
Automatically expand height of Row to fit data in column

### ISSUE THREAD

**Issue by carterwe** [olifolkerd/tabulator#430]
I need my Row Height to automatically expand to fit my data in a specific column - as an html table naturally would.  If I can't have that then I need to at least be able to specify the height of a row to include several lines that will wrap for columns that need it.  I can set the row height in css but nothing wraps and the side borders do not extend the height of the row.

**Comment by olifolkerd** [comment]
Hey, 

You need to use the ***textarea*** formatter con the columns where you want the text to wrap

```js
$("#example-table").tabulator({
    columns:[
        {title:"Name", field:"name", width:200, formatter:"textarea"},
    ],
});
```

Let me know if that helps.

Cheers

Oli
