### ISSUE TITLE
Multi Select Dropdown AJAX Filter Causing Issue with Draggable Columns

### ISSUE THREAD

**Issue by pstraatmann** [olifolkerd/tabulator#4300]
**Describe the bug**
When using a multi select filters, remote AJAX filtering and draggable columns causes draggable columns to lock in draggable mode. After selecting filter option in the multi select if you click out to apply the filter in the header, the loading of the results causes the the mouse up event to be interrupted. This causes the mouse down, and dragging event on the column to persist even after the the mouse click is complete. 

However if you hold down on the button until the load is complete or click out of the table area the the event will behave as normal.

This is has been causing issues on tables we have that have load times of more than a couple of seconds.

**Tabulator Info**
Version 5.5.2

**Working Example**
https://jsfiddle.net/7bpwsejx/

**To Reproduce**
1. Go to multi select filter.
2. Click open the filter and select any number of the filter options.
3. Click on the header with out holding down on the mouse button to close the filter. 
4. Drag mouse left and right and see that the column header you clicked on is locked in drag mode.

**Expected behavior**
Clicking out of filter and triggering data filtering should not lock the the click on mouse down and should not allow the the column to be draggable with out holding down on the mouse button. 

**Desktop**
 - OS: Windows 10
 - Browser: Chrome 
 - Version: 116.0.5845.187 (Official Build)

**Comment by olifolkerd** [comment]
Hey @pstraatmann 

Thanks for the headsup, i have pushed a fix for this to the 5.6 branch and will include it in the release in a couple of weeks time.

On a side node, I really like your ajax shim, great way to mock up a test environment.

Cheers

Oli :)
