### ISSUE TITLE
List editor fetch function override

Would it be possible to have a fetch function override for valuesURL in the editor. Sometimes you have to put  some headers.

or maybe just use the queryRelm used for ajax loading.

Thanks

### ISSUE THREAD

**Issue by pjanickovic** [olifolkerd/tabulator#4302]
*Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by memer-s** [comment]
Perhaps you could create an asynchronous function that fetches the data and returns it in the format [{value: "", label: ""},...], and then assigning it to the editorParams property valuesLookup?
