### ISSUE TITLE
When grouping data with columnCalcs: "both" option on a wide table, the horizontal scrollbar appears above the last visible row

### ISSUE THREAD

**Issue by Db-pckr** [olifolkerd/tabulator#4303]
**Describe the bug**
When using the options: groupBy: "name", columnCalcs: "both", a column with bottomCalc: "sum", alongside a table that is wide, the horizontal scrollbar is located above the last visible row represented by the colum calculation total.

**Tabulator Info**
v5.5

**Working Example**
https://jsfiddle.net/L4gh35x6/13/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Activate groupBy: "name", columnCalcs: "both"
2. Have a wide table that requires horizontal scrolling
3. Use bottomCalc: "sum" for a column

**Expected behavior**
The horizontal scrollbar should be at the bottom of the table, rather than above any rows. The bug appears to be related to how the HTML is created, with the groupby overall total appear in the table footer.

**Desktop (please complete the following information):**
Browser: Chrome (Ubuntu), Mozilla (Windows 11)

**Comment by olifolkerd** [comment]
Hey @Db-pckr 

This is the correct layout, you have selected "both" which means you want a footer calculation row too, this is in the table footer which sits below the table scroll bar.

Cheers

Oli :)
