### ISSUE TITLE
Can I use Tabulator engine to create a card list?

### ISSUE THREAD

**Issue by clabnet** [olifolkerd/tabulator#4308]
First, thanks for this beautiful project.

In addition to table view, is it possible to get the same features as table using a card list ?

Each row should be be a rectangular box to see few details, organized on matrix of "col" x "row" elements,
with pagination controls and remote lazy loading, best plus with search (remote ajax) elements with a search text input.

**Comment by pageagency** [comment]
Are you talking about something like the row formatter? https://tabulator.info/examples/5.5#row-formatter
