### ISSUE TITLE
Selection in editable cell

### ISSUE THREAD

**Issue by Maligosus** [olifolkerd/tabulator#4310]
**Describe the bug**
When you try to select edited text in an edited cell, the edited text is not selected and editing is immediately reset. I tried to add a ban on the propagation of the `onclick` event by the parent via `event.stopPropagation`, but it didn’t work either.

**Tabulator Info**
- 5.5.2

**Working Example**
https://codesandbox.io/s/sharp-nobel-jc3tlm?file=/src/table/table.tsx

**Expected behavior**
The text should be highlighted in the edited cell

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version 118.0

**Comment by olifolkerd** [comment]
Hey @Maligosus 

Could you please submit a {Minimal Reproducible Example](https://tabulator.info/community/mre) that demonstrates the issue, there is so much going on in your example it is hard to see the wood for the trees.

Cheers

Oli :)
