### ISSUE TITLE
Breaking print on latest version of chrome 117 (chromium based browsers) with high number of columns

### ISSUE THREAD

**Issue by vinitkp** [olifolkerd/tabulator#4312]
**Describe the bug**
When the number of columns are high or on few occasions when there is html print header, the print breaks completely of chrome. However it works perfectly fine on firefox and other browsers.
Our clients have have observed this b
**Tabulator Info**
- latest version and tried on 5.4, 5.,3 as well

**Working Example**
https://jsfiddle.net/u098fx7a/5/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to  the fiddle on chrome browser
2. Click on  print
3. check the broken preview

**Expected behavior**
The print should not break and the columns should repeat on every page. The print on firefox is perfect

**Screenshots**
firefox - working fine
<img width="439" alt="Screenshot 2023-10-03 at 11 51 59 PM" src="https://github.com/olifolkerd/tabulator/assets/2684618/225b96c3-9759-434a-ab77-5cbd61b40806">

chrome - issue
<img width="471" alt="Screenshot 2023-10-03 at 11 51 47 PM" src="https://github.com/olifolkerd/tabulator/assets/2684618/35bf91d2-468f-428b-a521-87888679e349">

**Desktop (please complete the following information):**
 - OS: Mac, Windows
 - Browser Chrome
 - Version 117.0.5938.132

**Comment by olifolkerd** [comment]
Hey @vinitkp 

This looks like it was a bug in Chrome and not Tabulator.

Looks like it is fixed now.

Cheers

Oli :)
