### ISSUE TITLE
setPageToRow typo

### ISSUE THREAD

**Issue by daveelcock** [olifolkerd/tabulator#4314]
Not so much a bug report as a fix report

Calling setPageToRow with a row index value was causing an exception

                tabTableCFA.setPageToRow(parseInt(pxid));

debugging this issue led to a missing .table Tabulator v5.5.2
adding the .table between this and .rowManager when calling findRow fixes the issue

		///////////////////////////////////
		///////// Table Functions /////////
		///////////////////////////////////
		
		userSetPageToRow(row){
			if(this.table.options.pagination){
				row = this.table.rowManager.findRow(row);
				
				if(row){
					return this.setPageToRow(row);
				}
			}
			
			return Promise.reject();
		}

**Comment by olifolkerd** [comment]
Hey @daveelcock 

Thanks for the headsup, i have pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)
