### ISSUE TITLE
Oli's Back :)

### ISSUE THREAD

**Issue by olifolkerd** [olifolkerd/tabulator#4315]
**I'm Back!**

Hey Everyone, you have probably noticed that I've been a bit quite over the last few months...

I Started a new job earlier in the year and it has kept me very busy so I haven't had the time to put into Tabulator that i would have liked.

But the good news is that things are settling down and im starting to phase back in to Tabulator, over the next couple of week i will start getting my ducks in a row, revieing outstanding tickets and PR's and will start preparing the next release.

Thanks for your patience

Oli :)

**Comment by Jojoshua** [comment]
Welcome back!

**Comment by suyashsuvare** [comment]
Welcome back Oli!

**Comment by mhlozek** [comment]
Hello Oli,
I wish you all the best for the new year and one cheeky question: how is it going with the further development of Tabulator?

**Comment by olifolkerd** [comment]
Hey @mhlozek 

Thanks for the message, I took a long break last year to balance work and personal pressures, but im starting to phase back in now. Im doing a patch release this evening and starting to work through the backlog of issues.

Im going to phase back in slowly, but it looks like the community has been busy while im away, so i will be assembling a number of the bigger PRs that have been submitted into a feature release soon.

Cheers

Oli :)

**Comment by 851091009** [comment]
Welcome back!

**Comment by olifolkerd** [comment]
Tabulator 5.6 Released Today!

This update focuses on one big new feature, [Cell Range Selection](https://tabulator.info/docs/5.6/range#overview) that lets you select and manipulate ranges of cells. 

Combining this with new edit, clipboard and navigation functions lets you use the table as a basic Spreadsheet!, checkout the [Spreadsheet Example](https://tabulator.info/docs/5.6/range#spreadsheet) to see it in action!

Have a look at the [Release Notes](https://tabulator.info/docs/5.6/release) for full details of all the features added in this release (including a load of bug fixes)!

Happy Tabulating

Oli :)
