### ISSUE TITLE
Smart Phone Keyboard unstable in editable list cells.

### ISSUE THREAD

**Issue by samad-kanton** [olifolkerd/tabulator#4316]
**Describe the bug**

**Tabulator Info**
- Which version of Tabulator are you using?

**Working Example**
YOU MUST include a link to a JS Fiddle or Codepen that demonstrates the problem, it is very hard to diagnose an issue from a simple description.

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: A07
 - OS: Android v12
 - Browser Edge, Firefox, Chrome
 - Version 12

**Additional context**
When I click on the editable list, the keyboard comes up and goes back down so fast that you can tab any key.

https://github.com/olifolkerd/tabulator/assets/31456450/61e56f4a-5100-4da2-ada4-de710604c9da

**Comment by JaumeAG** [comment]
Any solution??

**Comment by olifolkerd** [comment]
This is a duplicate of #4305
