### ISSUE TITLE
"disabled" pagination button styles incorrect

### ISSUE THREAD

**Issue by brimimc** [olifolkerd/tabulator#4317]
**Describe the bug**
When you hover over the disabled buttons this style still takes effect because it's using the wrong css selector

https://github.com/olifolkerd/tabulator/blob/0675efd4b7532d91415b9b5ac3bd11b602ba57cf/src/scss/tabulator.scss#L581C13-L581C13
```
&:not(.disabled){
				@media (hover:hover) and (pointer:fine){
					&:hover{
						cursor:pointer;
						background:rgba(0,0,0,.2);
						color:#fff;
					}
				}
			}

```
so the button look like you can click on them because the pointer changes and the background color changes.

the selector of :not(.disabled) doesn't work because the element doesn't have a disabled class, but a disabled attribute.

I think it should be :not(:disabled) or :not([disabled])

**Tabulator Info**
- Which version of Tabulator are you using? latest

**Working Example**
You can see this reproduced on the pagination demo https://tabulator.info/examples/5.5?#pagination

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to the pagination demo https://tabulator.info/examples/5.5?#pagination
2. Hover over the "First" or "Previous" buttons that are disabled
3. See that the cursor changes to pointer and background color changes

**Expected behavior**
The buttons should be disabled and not change when hovered over

**Comment by olifolkerd** [comment]
Hey @brimimc 

Thanks for the feedback, i have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)
