### ISSUE TITLE
Tabulator.setData() ignoring ajaxParams given in function call

### ISSUE THREAD

**Issue by impaex** [olifolkerd/tabulator#4318]
**Describe the bug**
The Tabular.setData() function ignores the Ajax parameters given upon calling the function, instead uses the Ajax params set during initialization of the Tabular object.

**Tabulator Info**
Latest, 5.5.

**Working Example**
https://codepen.io/impaex/pen/OJrGRKR

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Open the Codepen
2. Open the Developer Console in your browser, head to the Network tab
3. Click on one of the two buttons. 
4. After clicking, the network tab will show the Ajax call made, which contains the ajax params set during initialization, ignoring the params given in the setData() function.

**Expected behavior**
The setData() function should use the params given within the function call, not using the 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 117

**Comment by KilianCalmedica** [comment]
Hello, same problem here.

I have turn ajaxParams to a function generator and it work correctly now.

`ajaxParams() {
 return {key1:"value1", key2:"value2"};
}`

**Comment by olifolkerd** [comment]
Hey,

Thanks for the info, i have pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)

**Comment by impaex** [comment]
Thanks for fixing, Tabulator is an awesome piece of work!
