### ISSUE TITLE
Inconsistent focus placement when editing a text field that stretches outside the viewport

### ISSUE THREAD

**Issue by marczinusd** [olifolkerd/tabulator#4319]
**Describe the bug**
If an editable column's content and the column itself stretch outside of the current viewport, then focus placement becomes inconsistent and sometimes incorrect. When editing is triggered Tabulator will sometimes place the focus on the right edge of the text input, and other times it'll focus on the left edge of the text input, completely ignoring the length of the content that is being edited.

**Tabulator Info**
- Which version of Tabulator are you using? 5.5.0

**Working Example**
https://jsfiddle.net/marczinusd/8b2ht1sL/7/

**To Reproduce**
1. Go to https://jsfiddle.net/marczinusd/8b2ht1sL/7/
2. Click on 'Oli Bob' in the first row's name column. Focus will either be placed on the right edge of the text input field (incorrect as the text being edited is completely obscured) or on the left edge of the input field (correct)
3. Click on the second's row Name field, which contains a long string that stretches out the column. Focus will again either be place on the right edge of the text input field (which in this case is correct) or on the left edge of the input field (incorrect, as the blinking cursor is not visible)
4. This issue can be reproduced for any field in the Name column

**Expected behavior**
Focus on editable fields should always be aligned with the blinking cursor inside the field, even if the column stretches outside of the viewport.

**Screenshots**
![Recording of repro](https://github.com/olifolkerd/tabulator/assets/1497791/9d6bf648-c3d4-4175-bd2f-0ffa029549f9)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 117 (can also repro using Firefox Developer Edition v119)

**Comment by olifolkerd** [comment]
Hey @marczinusd 

This is not an action of Tabulator, the browser chooses where the cursor is placed based on element focus.

Cheers

Oli :)
