### ISSUE TITLE
is there a way to load the table after initialisation based on onchange event?

### ISSUE THREAD

**Issue by madhumithavenkat** [olifolkerd/tabulator#432]
Hi oli,
is there a way to load the table based on a on change event?
$('#productSelector').change( function() {

var value = $(this).val();
alert(value);

$("#device-table").tabulator({
            
            ajaxURL:window.location.protocol+ "//" + window.location.host + "/users/getDevice", //ajax URL
            ajaxparams:{key1:value}, //ajax parameters
            

            pagination:"remote", //enable remote pagination
            paginationSize:10,
            ajaxSorting:true, //send sort data to the server instead of processing locally
            resizableColumns:true,
            movableColumns: true,
            selectable:1,
            ajaxFiltering:true,
            fitColumns:true, //fit columns to width of table (optional)
            placeholder:"No Data Found, Clear Your Search/Filter if Applied", 
            columns:[ //Define Table Columns
                {title:"DeviceID ", field:"id",width:125 },
                {title:"Device Name ", field:"name" ,minWidth:130, editor:deviceNameEditor, formatter:iconEditor},
                {title:"Device Group ", field:"groupname" , minWidth:130 ,formatter:iconEditor, editor:deviceGroupEditor},
                {title:"Current Version", field:"version" ,width:100},
                {title:"OS", field:"os" ,width:100},
                {title:"Last Update Status", field:"upgradeStatus",width:100, formatter:upgradeStatusFormatter },
                {title:"Approval Status ", field:"authenticationStatus",minWidth:130,editor:approvalStatusEditor, formatter:approvalStatusFormatter},
                {title:"Last Seen", field:"lastSeenDate", width:150 },
                {title:"Device Type", field:"productionStatus",width:100 ,formatter:deviceTypeFormatter },
                
                

            ],
                initialSort:[
                    {column:"id", dir:"asc"}, //sort by this first
                ]
	},
});
});

**Comment by olifolkerd** [comment]
Are you asking if you can change the table data after the table has been created?

Or do you mean can you change the config (column layout) after the table is created?

**Comment by madhumithavenkat** [comment]
Hi oli,
I am asking if i can change the table data after the table  has been created based on an onchange event.
Thabk you!

**Comment by olifolkerd** [comment]
You can use the ***setData*** function at any point to update the table data:

```js
$("#device-table").tabulator("setData");
```
For more infomation check out the [Setting Data Documentation](http://olifolkerd.github.io/tabulator/docs/3.1/#set-data)

Let me know id that is what you are after.

Cheers

Oli

**Comment by madhumithavenkat** [comment]
setData works fine! Thank you!
is there a way i can use fileFormatter to format one or more cells and download the formatted table as excel sheet?

**Comment by olifolkerd** [comment]
Hey,

what do you mean by format one of the cells for the excel spreadsheet, can you give an example?

Cheers

Oli

**Comment by madhumithavenkat** [comment]
hi,
for example,i want to format the rows of the column device type based on its value and then export the entire table as excel sheet.
or is there a way to export the table as it was formatted rather than exporting it with the values that is got from the ajax call?
Thank you!
$('#productSelector').change( function() {

var value = $(this).val();
alert(value);

$("#device-table").tabulator({

        ajaxURL:window.location.protocol+ "//" + window.location.host + "/users/getDevice", //ajax URL
        ajaxparams:{key1:value}, //ajax parameters
        


        pagination:"remote", //enable remote pagination
        paginationSize:10,
        ajaxSorting:true, //send sort data to the server instead of processing locally
        resizableColumns:true,
        movableColumns: true,
        selectable:1,
        ajaxFiltering:true,
        fitColumns:true, //fit columns to width of table (optional)
        placeholder:"No Data Found, Clear Your Search/Filter if Applied", 
        columns:[ //Define Table Columns
            {title:"DeviceID ", field:"id",width:125 },
            {title:"Device Name ", field:"name" ,minWidth:130, editor:deviceNameEditor, formatter:iconEditor},
            {title:"Device Group ", field:"groupname" , minWidth:130 ,formatter:iconEditor, editor:deviceGroupEditor},
            {title:"Current Version", field:"version" ,width:100},
            {title:"OS", field:"os" ,width:100},
            {title:"Last Update Status", field:"upgradeStatus",width:100, formatter:upgradeStatusFormatter },
            {title:"Approval Status ", field:"authenticationStatus",minWidth:130,editor:approvalStatusEditor, formatter:approvalStatusFormatter},
            {title:"Last Seen", field:"lastSeenDate", width:150 },
            {title:"Device Type", field:"productionStatus",width:100 ,formatter:deviceTypeFormatter },
            
            

        ],
            initialSort:[
                {column:"id", dir:"asc"}, //sort by this first
            ]
},

});
});

**Comment by olifolkerd** [comment]
at the moment there is no way to do this directly, because the system has no way to know what you will be doing in the formatter and it cant render graphical formatter output into the excel spreadsheets.

You would be able to do this if you created a custom downloader to handle this yourself.

The good news is that the the download system will be getting an upgrade in the next month or so to allow for manipulation of the table data before it is passed into the downloader.

Cheers

Oli

**Comment by madhumithavenkat** [comment]
hey oli,
thank you!

**Comment by madhumithavenkat** [comment]
is there a way to export all the pages on a single click?

**Comment by olifolkerd** [comment]
if you are using remote pagination then this is not possible, if you are using local pagination, or no pagination then this will happen by default

**Comment by madhumithavenkat** [comment]
hey,
thank you!

**Comment by olifolkerd** [comment]
Hey,

You will be happy to hear that Tabulator 3.2 has just been released, and with it the ***downloadDataMutator*** option that allows you to alter table data before it is passed to the downloader:
```js
$("#example-table").tabulator({
    downloadDataMutator:function(data){
        //data - active table data array

        data.forEach(function(row){
            row.age = row.age >= 18 ? "adult" : "child";
        });

        return data;
    }
});
```

Full information can be found in the [Download Documentation](http://olifolkerd.github.io/tabulator/docs/3.2/#download)

Cheers

Oli
