### ISSUE TITLE
Option to add "border" spacing for `fitColumns` layout with `responsiveLayout`

### ISSUE THREAD

**Issue by exetico** [olifolkerd/tabulator#4320]
*Is your feature request related to a problem? Please describe.**
I have a design where I'd like a border around my `.tabulator-row`. If I add the border, due to the calculated weight, I end up with horizontal scroll-bars, due to the overflow of 2*1px borders (left and right). This is in a situation, where I also use responsiveLayout `collapse`.

![billede](https://github.com/olifolkerd/tabulator/assets/3549445/33c69bda-586f-4210-b624-eab6946f79b5)

_Example with borders added to `.tabulator-row` with CSS.

**Describe the solution you'd like**
I'd like to impact the calculations of the total table width, so I have 2px to use for other things, like borders. It could be called `spacing` or similar.

**Describe alternatives you've considered**

I've already through about multiple alternatives:

- Add a logics in Tabulator to expose the last **visible** tabulator-cell, so I'm able to use `:first-of-type` and the new ".tabulator-cell-last" selector, cause I'm [unable to use the :last-of-type pseudo-class](https://stackoverflow.com/a/29859852/4880226) to find the last **visible** cell in my row (else, allowing me to style the first and last cell with proper borders)
- Add a "border"/styling prop to the table row, but I'd really like to have the option to style this with CSS, without having to push CSS styling into my Tabulator Class.

**Additional context**

Right now, I've personally forced my "rowSelection". to a width of 30px. It renders as 40px every time (due to spacing, i guess). 

Therefore I'm exposing the colum.field or colum.formatter as a class on the cell:
```js
		this.column_options.forEach((column,i) => {
			this.column_options[i].cssClass = column.field ? "column_" + column.field : "column_" + column?.formatter?.toLowerCase();
		});
```

And using that to force a 38px width on my selector colum cells:
```css
    /* Workaround to prevent overflow, by forcing it 2px smaller */
    .tabulator-cell.column_rowselection{
        width: 38px!important;
    }
```

![billede](https://github.com/olifolkerd/tabulator/assets/3549445/c709861c-51e4-464f-9006-f1ffcd7696a9)

I'd like it to be a option, instead of having to modify the function to render the row or similar. I'm also willing to use other workarounds or adjustments, but the current one are not that pretty 😄 ...

I hope I've not missed some documentation here. This is the first time playing with v5, and I really like it. Keep of the great work!

Mentioned on Discord: https://discord.com/channels/954040083613376572/955128115783421972/1163442205244002314

**Comment by exetico** [comment]
Adding something like `row.getElement().style = "border:5px solid red;";` to the rowFormatter function doesn't solve the problem. It also triggers the overflow issue.

**Comment by olifolkerd** [comment]
Hey @exetico 

If you want a border on the side of the row, why not add it to the table itself or the `.tabulator-table` element?

Cheers

Oli :)

**Comment by exetico** [comment]
Cause I need it for every row, as explained with class and how it's impacting the weight if I add it to that? :-) Huh. 

Well, thanks for the answer, but it doesn't fit my needs. However, I found Tabulator too heavy to be used as a Lit Component, even after trying to optimize as much as possible.
