### ISSUE TITLE
`autoResize` doesn't work when the browser is in Mobile + EditModule is not registered

### ISSUE THREAD

**Issue by jmanke** [olifolkerd/tabulator#4321]
**Describe the bug**

The table fails to resize when the following conditions are met:
1. `autoResize=true`
2. The `EditModule` is not registered
3. The browser is running on a mobile device

**Tabulator Info**
- 5.5.1

**Working Example**

[codepen](https://codepen.io/jmanke/pen/ZEwzGBL?editors=1010)

**To Reproduce**

1. Open the codepen in a mobile mode (with chrome dev tools for example), or on a mobile device
2. Click on the 'Resize' button to resize the table from 50% -> 100% width
3. Observe that the table does not resize its columns properly.
4. Observe console error 

**Expected behavior**

Given the conditions described in the `Describe the bug` section, autoResize should work.

**Screenshots**

| Initial load  | After resizing table |
| ------------- | ------------- |
| ![Screenshot 2023-10-19 at 8 59 52 AM](https://github.com/olifolkerd/tabulator/assets/19629809/25dc0149-97ce-4bae-b0e1-cb91e94591e4) |  ![Screenshot 2023-10-19 at 9 02 33 AM](https://github.com/olifolkerd/tabulator/assets/19629809/5e58b46c-3433-435f-8e07-d90b76ca65fa) |

Console error:
![Screenshot 2023-10-19 at 9 00 10 AM](https://github.com/olifolkerd/tabulator/assets/19629809/aae19ff8-337b-47e1-8aad-4f16284e07f6)

**Desktop:**
 - OS: MacOS
 - Browser: Chrome
 - Version: 117.0.5938.149

**Smartphone:**
 - Device: Pixel 7a
 - OS: Android v13
 - Browser: Chrome
 - Version: 118.0.5993.80

**Additional context**

The above workflow works fine on non-mobile environments.

Thank you in advance for looking into this, this package is fantastic!

**Comment by olifolkerd** [comment]
Hey @jmanke 

Thanks for the headsup,

I have pushed a fix for this to the 5.6 branch that i hope to release in the next couple of weeks.

Cheers

Oli :)

**Comment by jmanke** [comment]
> Hey @jmanke
> 
> Thanks for the headsup,
> 
> I have pushed a fix for this to the 5.6 branch that i hope to release in the next couple of weeks.
> 
> Cheers
> 
> Oli :)

Much appreciated Oli 🙂
