### ISSUE TITLE
clickPopup: in Scope of responsiveLayoutCollapseFormatter

### ISSUE THREAD

**Issue by bscNinja** [olifolkerd/tabulator#4323]
Is it possible that we add this Function?

**Comment by olifolkerd** [comment]
Hey @bscNinja 

Im afraid that wouldnt be possible without a massive rewrite as the formatter is only provided with raw cell data, it has no context of the cells it is formatting.

That being said, i todays 6.0 release, i am changing the scope of the function to the table, so you can manually trigger a popup from there

Cheers

Oli :)
