### ISSUE TITLE
Function setColumnLayout does not respect the visibile attribute.

### ISSUE THREAD

**Issue by Kamo1966** [olifolkerd/tabulator#4324]
**Describe the bug**
Function setColumnLayout does not respect the visibile attribute.

**Tabulator Info**
Tabulator 5.5.2

**Working Example**
(https://jsfiddle.net/ou5e482y/5/)

**To Reproduce**
1. Click button **Modify** (it will change the table layout)
2. Click button **Memo** (it will get the definition of the table with getColumnLayout)
3. Click button **Reset** (it will apply the same layout with setColumnLayout)
4. You can see **"gender"** column that were hided with the modify button.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser chrome

**Comment by Tim-jn** [comment]
Same problem here

**Comment by unamedplayer** [comment]
Ditto :).

**Comment by nick-mcd** [comment]
Same

**Comment by olifolkerd** [comment]
Hey,

Thanks for the feedback.

I have just pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)

**Comment by unamedplayer** [comment]
Thanks Oli,

I'm ever impressed by Tabulator, it's extremely well thought out and 
comprehensive. It's an amazing contribution to the world. Hats off to 
you for your talent, dedication & generosity.

-- 

Ben

> Hey,
> 
> Thanks for the feedback.
> 
> I have just pushed a fix for this to the master branch and will include 
> it in todays patch release.
> 
> Cheers
> 
> Oli :)
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you commented.Message ID: 
> ***@***.***>



Links:
------
[1] 
https://github.com/olifolkerd/tabulator/issues/4324#issuecomment-1902666944
[2]
