### ISSUE TITLE
float validator does not validate correctly in simple example

### ISSUE THREAD

**Issue by isohelio** [olifolkerd/tabulator#4326]
**Describe the bug**
Adding  validator: "float" to a simple tabulator example makes it impossible to correctly validate the field

**Tabulator Info**
- 5.5.0

**Working Example**
https://jsfiddle.net/wa2h4Lxy/6/

**To Reproduce**
1. Click on the input in the float column.
2. Enter a simple number e.g. 1.0 or 1
3. Click on the input in the input column
4. The float input retains focus, indicating that the cell has not validated.

**Expected behavior**
The cell will validate successfully with a valid number entered.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Chrome
 - Version 117.0.5938.150 

**Additional context**

Entering values into the Integer column input will correctly validate integer input.
The Integer column input will also accept floating point numbers such as 1.0. This behaviour is unexpected.

**Comment by olifolkerd** [comment]
Hey @isohelio 

The `float` validator is to check that a number is specifically a non integer floating point number.

If you want to allow integers as well you should be using the `numeric` validator instead.

Cheers

Oli :)
