### ISSUE TITLE
Column persistence doesn't work when using an ajax data source

### ISSUE THREAD

**Issue by Sairenity** [olifolkerd/tabulator#4327]
**Describe the bug**
Column persistence doesn't work when using an ajax data source.

**Tabulator Info**
- v5.5.2

**Working Example**
https://jsfiddle.net/ztecgmsp/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Check out the provided jsfiddle, https://jsfiddle.net/ztecgmsp/
2. Mess around with column orders in the four provided samples
3. Refresh the page
4. Notice how in Sample 3 & 4, all settings were reset.

**Expected behavior**
The table persists all settings, even when using ajax data.

**Desktop (please complete the following information):**
 - OS: Windows 11 v22H2
 - Browser: Chrome v118

**Comment by erdkuk** [comment]
I found a similar issue that may be related. Auto completion with custom lookup function (which returns a promise) does not work anymore once table persistence is configured like this:

column config:
```
                    editorParams: {
                        autocomplete: true,
                        freetext: true,
                        valuesLookup: searchAccount,
                        clearable: true,
                        filterDelay: 300,
                        allowEmpty: true
                    },
```

persistence config: 
```
            persistence:{
                sort: false, //persist column sorting
                filter: false, //persist filters
                headerFilter: false, //persist header filters
                group: false, //persist row grouping
                page: false, //persist page
                columns: true, //persist columns
            },
```

However, autocomplete works if the following persistence config is used:
```
            persistence:{
                columns: ["width"], //persist changes to the width, visible and frozen properties
            },
```

**Comment by olifolkerd** [comment]
Hey @Sairenity,

This is correct, this happens because the persist module is called as soon as the table is loaded and requires the columns to be defined at the point the table is loaded, in the case of autocolumns, when no columns exist, an the data taes time to load, there are no columns in the table for the persistence module to configure.

Cheers

Oli
