### ISSUE TITLE
Validate lines when rendered

### ISSUE THREAD

**Issue by BastienRimbert** [olifolkerd/tabulator#4329]
- Should fix #4296

**Describe the solution you'd like**
From what I've seen, the easiest solution would simply to validate cell on render, I've played a bit that way and does not seems to suffer from it (performance wise)

So my idea is just to add this line into Validate.js (inside `initialize`)
```js
this.subscribe("cell-rendered", this.cellValidate.bind(this));
```
Since this internal seems to be only called whenever a cell is rendered for the first time, this work well but I may be wrong on that event. 

But doing so will force validation which could not be desirable for everyone I guess. Honestly I don't really see a case where it could be problematic.

**Describe alternatives you've considered**
As the author of the issue said, getting all the rows without the RowManager will work, but that's because all the lines are loaded, which impact performance IMO.

**Comment by olifolkerd** [comment]
Hey @BastienRimbert 

Tabulator has no concept of row editing, editing happens at a cell level, therefore this would not fir with the paradaigm,

If you want to do this, you could always use the "manual" row validation mode and then run your row validation script yourself
https://tabulator.info/docs/5.5/validate#mode

Cheers

Oli ;)

**Comment by olifolkerd** [comment]
@BastienRimbert  As mentioned on the previous issue, validation is only indended for user edited data, not for when new data is loaded into the table.

Cheers

Oli :)
