### ISSUE TITLE
After setting height of an tabulator instance I get errors in console  "Event Target Lookup Error" when using tooltip function

### ISSUE THREAD

**Issue by maku** [olifolkerd/tabulator#4333]
**Describe the bug**

After set the height of an existing tabulator instance I get the following error when tooltip is enabled and I move the cursor over a field:
"Event Target Lookup Error - The row this cell is attached to cannot be found, has the table been reinitialized without being destroyed first?"

**Tabulator Info**
- Using version 5.5.2 of tabulator

**Working Example**
https://jsfiddle.net/maku/aeb683mg/

**To Reproduce**
After starting the fiddle click on then button "Set height" and look at the console output and you see the errors

**Comment by maku** [comment]
BTW, in version 5.4 this worked without an error

**Comment by olifolkerd** [comment]
Hey @maku 

Thanks for the headsup, I have pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)
