### ISSUE TITLE
Editor list does not preselect value when using lookup

### ISSUE THREAD

**Issue by ff-ils** [olifolkerd/tabulator#4335]
**Describe the bug**
When using a lookup object to format and edit a cell with a list editor, the current value is not preselected in the dropdown, so it's lost if the user clicks outside the cell. This does not happen if ESC is pressed, in this case the value remains.

**Tabulator Info**
latest version 5.5.2

**Working Example**
https://codesandbox.io/p/sandbox/tabulator-test-edit-list-v9vxt2

**To Reproduce**
1. select a cell in the "Prop" column
2. click outside the cell
4. cell value is left empty

**Expected behavior**
The value shoul be retained, like when ESC is pressed

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Any

**Workaround**
A temporary workaround is to restore the value if empty on the "cellEdited" event:

```
tabulator.on("cellEdited", (c) => {
	if (!c.getValue() && c.getColumn().getDefinition().editor === "list") {
		c.restoreOldValue();
	}
});
```

**Comment by olifolkerd** [comment]
Hey @ff-ils 

That is because you are using numbers for your lookup heys and objects only support strings as props so there is a type conversion preventing equivalance checks in the lookup.

If you need to use numbers for the lookup, you need to use the structured lookup list format:
```js
const lookup = [
    {
        label:"empty",
        value:0,
    },
    {
        label:"first",
        value:1,
    },
    {
        label:"second",
        value:2,
    },
]
```

Cheers

Oli :)
