### ISSUE TITLE
Datatree performance improvement

### ISSUE THREAD

**Issue by lukecotter** [olifolkerd/tabulator#4336]
*Is your feature request related to a problem? Please describe.**
I have made some changes to improve performance of the datatree, but for me the main benefit I saw was when applying filter to a tree with 251890 expandable nodes. 

More specifically it centres around two methods 

1. [getTreeChildren](https://github.com/lukecotter/tabulator/blob/feat-datatree-perf/src/js/modules/DataTree/DataTree.js#L587) in DataTree.js
2. [rowsToData](https://github.com/lukecotter/tabulator/blob/feat-datatree-perf/src/js/modules/ColumnCalcs/ColumnCalcs.js#L402) in ColumnCalcs.js

**Comment by olifolkerd** [comment]
Hey @lukecotter 

Wowza that is a lot of nodes there!

Thanks for the PR, much appreciated, i have merged that into the 6.0 branch and will include it in todays release.

Cheers

Oli :)
