### ISSUE TITLE
getColumns returns not all cols available

### ISSUE THREAD

**Issue by tripower** [olifolkerd/tabulator#4338]
Hello

my data from JSON is like this
[
   {
      "name": "BirthDay",
      "date": "04/01/2022",
      "date_orig": "2022-01-04T00:00:00Z",
      ...
      
the definition in the code
`columns:[`
`   {title:"EventName",   field:"name",     headerHozAlign:"center", width:200 },                         },`
`   {title:"EventDate",    field:"date",        headerHozAlign:"center", hozAlign:"center", sorter:"date" },`
`   ...`
 
 so, 
 the table displays the cols EventName and EventDate which is OK
 in my customFilter function which is set at setFilter also **date_orig** is available ?? (but is GOOD :) )
` customFilter(data, filterParams)`
` table.setFilter(customFilter, {query:strQuery, doSql:pDoSql}`

so, I expected that also getColumns or getColumnsDefintions will return ALL cols
but only name and date but **NOT date_orig** is there??
is that a bug? if not, whould it be possible to implement a function that returns really all?
would be fine!

greetings
Klaus

**Comment by olifolkerd** [comment]
Hey @tripower ,

The `getColumns` function returns the column that have been defined on the table, not the data that is passed into the rows, you can have as many props as you like on your row data, but the columns are the items defined in your column definition array and shown on the table.

Cheers

Oli :)
