### ISSUE TITLE
Expandable row/columns

### ISSUE THREAD

**Issue by hannit** [olifolkerd/tabulator#434]
Hi,
I have a table containing a large multi-line area that varies in size.
I want to make it into extendable div, is there a way to do that with tabulator ?
Thanks

**Comment by olifolkerd** [comment]
Hey,

Are you asking for a variable height cell that will resize with content, If that is the case i suggest you use the ***textarea*** formatter for this. ( i would recommend updating to the 3.1.4 release that came out today as it has some enhancements for this formatter in).

```js
$("example-table").tabulator({
    columns:[
        {title:"Big Text", field:"bigtext", formatter:"textarea"}
    ]
});
```

If that is not what you are after could you give me an example of what this div will be doing and i can suggest an alternative approach.

Cheers

Oli

**Comment by hannit** [comment]
Hi,
I was no looking for 'textarea', but rather something like bootstrap collapse.
I want to show 2 text lines and a link that when clicked will show the rest of the data.
