### ISSUE TITLE
Abort previous ajax request before do a new one

### ISSUE THREAD

**Issue by yeestrada** [olifolkerd/tabulator#4342]
Hi community, i am trying to use a search input, but i need to abort a previous request on insert a new letter in the search input, the idea is something like this, can anybody help me?
thanks in advance.

```
$("#processing-log-table-search").on("input", function() {
            processing_table.jqXHR.abort();
            processing_table.setData(); 
});
```

**Comment by olifolkerd** [comment]
Hey @yeestrada 

Tabulator will automatically do this if you call the function again.

Cheers

Oli :)
