### ISSUE TITLE
pagination responsive issue , pagination goes outside of page in mobile devices

### ISSUE THREAD

**Issue by alirezadigi** [olifolkerd/tabulator#4343]
**Describe the bug**
I am using Tabulator to create a responsive table that fetches data with AJAX. I need both the table and the pagination to be responsive. However, my pagination currently appears like this on mobile devices:

![image](https://github.com/olifolkerd/tabulator/assets/47608350/1a0796bc-9da9-4512-af82-1b533a2ec307)

However I can see that the pagination example on Tabulator's website displays well on mobile devices.

**Tabulator Info**
- Which version of Tabulator are you using?
I use v5.5.2

**Working Example**
YOU MUST include a link to a JS Fiddle or Codepen that demonstrates the problem, it is very hard to diagnose an issue from a simple description.

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1.create your project and import Bootstrap 5 and tabulator 5.5.
2.create your body using this code:
```html
<div class="container my-3">
    <div class="card">
        <div class="card-header" dir="rtl">
            infos
        </div>
        <div class="card-body">
            <table id="example-table">
            </table>
        </div>
    </div>
</div>
```
and add this script element below it:
```js

var table = new Tabulator("#example-table", {
    progressiveRender:true, 
    // pagination setup
    textDirection:"rtl",
    autoColumns: true,
    minWidth: 200, 
    layout:"fitData",
    pagination:"local",
    paginationSize:6,
    paginationSizeSelector:[10, 25, 100, 500],
    movableColumns:true,
    paginationCounter:"rows",
    pagination:"local",
  
    // data setup
    ajaxURL:"{% url 'viewListAjax' %}",
    ajaxContentType:"json", 
    ajaxConfig:"GET",
    columns:[
        {title:"Name", field:"excelRow"},
        {title:"Age", field:"age"},
        {title:"Gender", field:"gender"},
        {title:"Height", field:"height"},
        {title:"Favourite Color", field:"col"},
        {title:"Date Of Birth", field:"dob"},
        {title:"Cheese Preference", field:"cheese"},
    ],

});
table.on("tableBuilt", function(){
    table.setData();
});

```

3. Open the project in the Chrome browser (I believe it should work in any other browser as well).
4. Right-click and select 'Inspect Element.'
5. Click on the mobile icon at the top left of the 'Inspect Element' window.
6. Click on the text 'Responsive' at the top and choose 'iPhone XR.'
7. Now, you can observe that the pagination is broken.

**Expected behavior**
I would like the pagination to be responsive on smaller devices, resembling the example demonstrated on Tabulator's website at the following link: https://tabulator.info/examples/5.5#pagination.

**Screenshots**
I have included screenshots above for reference.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version 119.0

**Smartphone (please complete the following information):**
 - Device: Chrome emulator
 - OS: Chrome emulator
 - Browser Chrome emulator
 - Version 119.0

**Comment by olifolkerd** [comment]
Hey @alirezadigi 

In this case you can use CSS selectors to choose which pagination controls to hide as the screen gets small, this is not defined on Tabulator itself as it is very subjective what needs to be hidden, depending on usage case.

Have a look a the [Styling Guide](https://tabulator.info/docs/5.5/style#css-page) for more details, or try inspecting the elements in your dev tools to see which classes are assigned where.

Cheers

Oli :)
