### ISSUE TITLE
The table is re-rendering when I scrolling down. So I can go to the last row.

### ISSUE THREAD

**Issue by hourloop-jeffcai** [olifolkerd/tabulator#4344]
**Describe the bug**
The table is re-rendering when I scrolling down.
So I cannot go to the last row(the bottom).
It happens when the rows are all grouped.
There is about 100,000 - 150,000 rows.

**Tabulator Info**
- Which version of Tabulator are you using?
Tabulator v5.5.2 (c) Oliver Folkerd 2023 */

**Working Example**
YOU MUST include a link to a JS Fiddle or Codepen that demonstrates the problem, it is very hard to diagnose an issue from a simple description.
```html
<div class="page-header">
  <h3>Promotions
    <span id="download" class="btn fa fa-download" onclick="promotionTable.setGroupBy(null);promotionTable.download('csv', 'promotions.csv')"></span>
  </h3>
</div>

<div id="promotion-table"></div>
<script>
  let promotionTable = new Tabulator('#promotion-table', {
    data: <%= raw(@promotions.to_json()) %>,
    columns: [
      { title: 'Type', field: 'type', sorter: 'string', width: 245 },
      { title: 'ASIN', field: 'asin', sorter: 'string', width: 95 },
      { title: 'Start Date', field: 'start_date', sorter: 'date' },
      { title: 'End Date', field: 'end_date', sorter: 'date' },
      { title: 'Amazon Promotion ID', field: 'amazon_promotion_id', sorter: 'string' },
    ],
    layout: 'fitDataFill',
    height: 1000,
    columnCalcs: 'both',
    groupBy: 'type',
    groupToggleElement: 'header',
    groupClosedShowCalcs: true,
    groupStartOpen: false
  });
</script>

```

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. wait the page load
2. try to scroll to the buttom.
3. And you can never go to the buttom, because it's keep bringing you up to the very top of the table.

**Expected behavior**
I want to go to the bottom of my grouped table.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Version all latest

**Smartphone (please complete the following information):**

**Additional context**

**Comment by olifolkerd** [comment]
Hey @hourloop-jeffcai 

Im afraid without sing this inaction i cannot offer any advice, please add a link to a working example, not just code and we can see if we can help.

Cheers

Oli :)
