### ISSUE TITLE
When iam exporting data to excel format the original styles are not there in downloaded excel file (i.e, font styles,alignment). I have implemented Tabulator in LWC (salesforce)

### ISSUE THREAD

**Issue by muraliaswilco** [olifolkerd/tabulator#4345]
Below is the code i have implemented in LWC iam able to download the file but styles are not there, Please help or suggest am i doing anything wrong or missing something?
[Uploading Actual & Percent Variation.xlsx…]()

 
  const XLSX = window.XLSX;
       let inputFields = this.template.querySelector('.example-table1');
    var table1 = new Tabulator(inputFields, {
        data: this.apDetails,
        layout:"fitColumns",
        columnGroups: true, //include column groups in column headers for download
        titleRowStyle: {
         font: { bold: true },
         alignment: { horizontal: "center" }
      }, 
        columns: [
            {//create column group
                title: "Indianapolis Weather Station",cssClass: "bold",
                align:"center",
                columns: [
                    {//create column group
                        title: "Actual & Percent Variation in heating , Cooling  & Total degree",hozAlign:"center",cssClass: "bold",
                        columns: [
                            {
                                title: "From year 2022 to year 2023",hozAlign:"center",cssClass: "bold", columns: [
                                    {//create column group
                                        title: "Actual Change In",
                                        columns: [
                                            { title: "HDD", field: "actualHDD",align: " right", sorter: "number", width: 100 },
                                            { title: "CDD", field: "actualCDD", align: "center", width: 80 },
                                            { title: "TDD", field: "actualTDD", align: "center", width: 80 },
                                        ],
                                    },
                                    {//create column group
                                        title: "% change in the",
                                        columns: [
                                            { title: "TDD", field: "actualPerTDD", align: "right", sorter: "number", width: 100 }
                                        ],
                                    }]
                            },
                            {
                                title: "",
                                columns: [
                                    { title: "", 
                                    columns: [
                                        { title: "Month", field: "month", align: "right", sorter: "number", width: 100 }
                                    ] }
                                ]
                            },
                            {
                                title: "From NOAA Normal to year 2023", columns: [
                                    {//create column group
                                        title: "Actual Change In",
                                        columns: [
                                            { title: "HDD", field: "normalPerTDD", align: "right", sorter: "number", width: 100 },
                                            { title: "CDD", field: "normalHDD", align: "center", width: 80 },
                                            { title: "TDD", field: "normalCDD", align: "center", width: 80 },
                                        ],
                                    },
                                    {//create column group
                                        title: "% change in the",
                                        columns: [
                                            { title: "TDD", field: "normalTDD", align: "right", sorter: "number", width: 100 }
                                        ],
                                    }]
                            },
                        ],
                    }
                ],
            },
        ],
    });
 table1.download("xlsx", "Actual & Percent Variation.xlsx", { sheetName: this.wsName });

**Comment by olifolkerd** [comment]
Hey @muraliaswilco 

This is the correct behaviour, Tabulator allows any possible combination of styles, not all of which are possible in excel, so instead of working on the formatted output it generates the download from the raw data itself.

If you have a look at the download documentation you will see that there are parameters you can pass to the download request that allow you to manipulate the spreadsheet yourself using the functionality of the SheetJS library, which should help you out.

Cheers

Oli :)

**Comment by arianmares** [comment]
SheetJS library allow cell styling only in PRO version.
