### ISSUE TITLE
Reloading tabulator with all the filters which was set before reloading from the table. 

### ISSUE THREAD

**Issue by rohitshakyaa** [olifolkerd/tabulator#4346]
**Website Page**
https://tabulator.info/docs/5.5/data#ajax

**Describe the issue**
The documentation and suggested the code of `table.setData()` for reloading the ajax call, it's working fine with javascript but with typescript `setData()` is searching for the default parameter data which is of type any

![image](https://github.com/olifolkerd/tabulator/assets/92146757/0afd73c6-a274-475d-9fcd-4860337eeb07)

Is there any way to reload ajax call with all the selected filters from the table which was before reloading. And i think the documentation needs to be updated for the typescript too.. 

Thank you very much for the response.

**Comment by olifolkerd** [comment]
Hey @rohitshakyaa 

Im afraid the typescript typings are not maintained as part of this repo, if you belive there is an issue with the typings, please raise it on https://github.com/DefinitelyTyped/DefinitelyTyped

Cheers

Oli :)
