### ISSUE TITLE
Field names with . (dot) character do not work in data update API when option "nestedFieldSeparator" disabled

### ISSUE THREAD

**Issue by feng-zh** [olifolkerd/tabulator#4347]
**Describe the bug**
The update table API not update data for column field name contains "." (dot) even "nestedFieldSeparator" operation is set as "false".

The version 5.5 code ColumnManager does not respect "nestedFieldSeparator" table option but hardcode use "." (dot) as field separator.

**Tabulator Info**
- Which version of Tabulator are you using?
v5.5.0

**Working Example**
https://jsfiddle.net/v49ndq27/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Click on 'Update Row' button
2. The column with field "my.title" (Title as "My Title") is not updated in 2nd row.
3. The column with field "content" (Title as "Content") is updated in 2nd row.

**Expected behavior**
The "nestedFieldSeparator" set as "false" (https://tabulator.info/docs/5.5/columns#field-nesting) should disable nested field parsing, and it should consistent with insert data behavior, and other no "." (dot) field updating.

**Screenshots**
Refer to jsfiddle

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari]: Chrome

**Additional context**

The root cause is the Column Manager method "getColumnsByFieldRoot" use "." as nested field for spliting, but not check "nestedFieldSeparator" settings -- See line 390

https://github.com/olifolkerd/tabulator/blob/0675efd4b7532d91415b9b5ac3bd11b602ba57cf/src/js/core/ColumnManager.js#L386-L397

**Comment by olifolkerd** [comment]
Hey @feng-zh 

Thanks for the headsup, i have pushed a fix to master and will include it in todays patch release.

Cheers

Oli :)
