### ISSUE TITLE
Bootstrap 5 modal weird z-index when created with eventFormatter

### ISSUE THREAD

**Issue by guarnacciaa** [olifolkerd/tabulator#4349]
**Describe the bug**
It seems that Bootstrap 5 modal doesn't work properly when generated by a column eventFormatter.

**Tabulator Info**
Tabulator 5.5.2 

**Working Example**
https://codepen.io/guarnacciaa/pen/qBgwXpd)

**To Reproduce**
1. Click on the Delete button in the table
2. Modal shows up but it is unclickable as it is hidden behind the modal backdrop.

**Expected behavior**
Modal should be clickable

**Screenshots**
![image](https://github.com/olifolkerd/tabulator/assets/18616620/26c65c01-4c16-41d6-b784-84f4868a14d0)

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux
 - Browser: Brave
 - Version v1.61.100

**Comment by olifolkerd** [comment]
Hey @guarnacciaa 

This is outside the scope of tabulator, you seem to be trying to append body level elements from inside the table as HTLM. I would strongly suggest implementing this outside the table and then calling a function to execute it.

You will need to have a look at your own CSS to resolve this.

Cheers

Oli :)
