### ISSUE TITLE
Scroll down and then up - empty gap in the begin of the table

### ISSUE THREAD

**Issue by MikhailKlemin** [olifolkerd/tabulator#435]
Hi! 
I have this problem in Firefox and Chrome, when I scroll  up/down sometimes when I scroll it back there just empty table. I need to scroll down again and then back and data is back in place, but sometimes it doesn't works.  
But if I do scroll down/up several times, the problem disappears... 
It looks like the data is loading/processing anachronistically  but the scroll height is not synced with that process. 
![screenshot from 2017-07-09 20-46-39](https://user-images.githubusercontent.com/8426672/27996310-1794024e-64e8-11e7-9dc3-ff2e547854a2.png)

**Comment by olifolkerd** [comment]
Hey,

Download the just released 3.1.5 release and you should be all sorted.

Let me know if the problem is still there.

Cheers

Oli

**Comment by MikhailKlemin** [comment]
Hi Olly, 
I replaced the js and css files from 3.1.5 - no difference, cleared cash too just in case.  Still the gap, it is very easy to spot, just click on pagination page and scroll to bottom and then up -- and there 99% will be what space for several rows, sometimes whole screen worth....

**Comment by olifolkerd** [comment]
Could you post a copy of your table constructor object so I can test against your setup.

Cheers

**Comment by MikhailKlemin** [comment]
Sure!
Constructor: 

```

$(document).ready(function() {
    $("#example-table").tabulator({
        responsiveLayout:false,
        index: "ProductCode",
        fitColumns:true,
        height:1000,
        sortable:true,
        showLoader: true,
        pagination:"local",
        paginationSize:100,
        tooltips:true,
        columnVertAlign:"bottom", 
        initialSort:[
            {column:"TimeStamp", dir:"desc"}
        ],
        cellEdited:function(cell){
            var id = cell.getRow().getCells()[0].getValue();
            var val = cell.getValue();
            
            postComment(id, val)
        },  
        columns:[ 
            {title:"Product Code", field:"ProductCode", sorter:"string",  align: "left", sortable:true,headerFilter:"input", minWidth:100,width:100},
            {title:"Category", field:"Category", sorter:"string", sortable:true, align:"left",headerFilter:"input", minWidth:110, width:110,formatter:categoryFormatter},
            {title:"Brand", field:"Brand",sorter:"string", align:"left", visible:true, headerFilter:"input",minWidth:90, width:90, formatter:"textarea"},
            {title:"Product Title", field:"Name", headerFilter: "input", sorter:"string", align:"left", visible:true, tooltipHeader:true, minWidth:125, width:125, formatter:"textarea"},
            {title:"Details", field:"Details", sorter:"string", formatter:"textarea",  align:"left", visible:true,headerFilter:"input", minWidth:300},
            {title:"Normal Price", field:"NormalPrice", sorter:"number",  formatter:"money", align: "left", sortable:true,headerFilter:"input", minWidth:90, width:90},
            {title:"Sale Price", field:"SalePrice", sorter:"number",  formatter:"money", sortable:true, align: "left", headerFilter:"input", minWidth:90,width:90}, 
            {title:"Color", field:"Color", sorter:"string",  align: "left", sortable:true, headerFilter:"input", minWidth:90, width:90},
            {title:"Size", field:"Size", sorter:"string",  align: "left", sortable:true, headerFilter:"input", minWidth:75, width:75},
            {title:"Stock", field:"Stock", sorter:"string", align: "center", sortable:true, headerFilter:"input",minWidth:90,width:90, formatter: stockFormatter},
            {title:"Supplier", tooltipHeader:true, field:"Link", sorter:"string",  align: "left", sortable:true, minWidth:90, width:110, headerFilter:"input",formatter:linkFormatter},
            {title:"Img", field:"Image", sorter:"string",  align: "left", sortable:true, minWidth:100, width:100, headerFilter:"input", formatter:imageLinkFormatter},
            {title:"Listed", tooltipHeader:true, field:"Ebay", align: "center", headerFilter:"input", minWidth:60, width:60},
            {title:"Ebay Link", field:"EbayLink", sorter:"string",  align: "left", sortable:true, minWidth:90, width:90, headerFilter:"input", formatter:linkFormatter},
            {title:"Updated", field:"TimeStamp", sorter:"date", align: "left", sortable:true, minWidth:100, width:100,headerFilter:"input"},
            {title:"Comment", field:"Comment", sorter:"string", formatter:"textarea", align: "left", headerFilter:"input", visible:true, editor:"input", minWidth:90}
        ]
    });
    $("#example-table").tabulator("setData","/foo");
});


$(window).resize(function(){
   $("#example-table").tabulator("redraw");
});
```

The data [https://github.com/olifolkerd/tabulator/files/1118033/foo.json.zip](https://github.com/olifolkerd/tabulator/files/1118033/foo.json.zip)

**Comment by olifolkerd** [comment]
Hey,

Is there a reason you are using pagination and scrolling? usually people either go for only enough rows to fill a given area and paginate, or they go for infinite scrolling. to paginate at 100 rows but fix the table height so they cant all be displayed seems a bit odd. For pagination you would normally specify a small row count and then not set the height which stops the scrollbar appearing.

I have just run your code and cant seem to replicate the error, i get smooth scrolling with no visual issues.... could you try running your code in a boilerplate HTML template with no other css classes or javascript acting on it and see if you get the same result.

i also didn't have your custom formatters so it maybe some weird interaction with them, if the boilerplate test still shows the issue could you send over the code for your formatters and i will see if they have any problems.

I have a coupe of tips outside of this error for you, as it looks like you are using some code there from a version <3.0.

responsive layout is disabled by default so there is no need for the ```responsiveLayout:false``` line.

as of version 3.0 the ***sortable*** option does not exist in either the global scope or column definitions so you no longer need those in your constructor.

**Comment by MikhailKlemin** [comment]
Hi thanks a lot! 
The reason that I use it as it is (pagination with height) , is when width is not enough there is scroll bar at the bottom, but If I am not specified height, it is the problem, you can't scroll it to see the headers unless you scrolled to the bottom...

**Comment by AHgPuK** [comment]
I can confirm that this issue is reproduced when a height of table is specified (Virtual DOM is enabled)

Here is an error that causes the problem:
Uncaught TypeError: rowEl.parentNode is null
    _removeTopRow http://192.168.1.11/js/tabulator.js:5404
    _removeTopRow http://192.168.1.11/js/tabulator.js:5416
    _removeTopRow http://192.168.1.11/js/tabulator.js:5416
    _removeTopRow http://192.168.1.11/js/tabulator.js:5416
    _removeTopRow http://192.168.1.11/js/tabulator.js:5416
    _removeTopRow http://192.168.1.11/js/tabulator.js:5416
    _removeTopRow http://192.168.1.11/js/tabulator.js:5416
    _removeTopRow http://192.168.1.11/js/tabulator.js:5416
    _removeTopRow http://192.168.1.11/js/tabulator.js:5416
    _removeTopRow http://192.168.1.11/js/tabulator.js:5416
    scrollVertical http://192.168.1.11/js/tabulator.js:5310
    initialize http://192.168.1.11/js/tabulator.js:3458

Tabulator v4.9.3

**Comment by olifolkerd** [comment]
This issue is on version 3.5 of Tabulator which is 3 years old. The version of Tabulator you are using is written with entirely different source code at this point.

If you feel you have found a bug please creat a new issue using the issue template provided along with a JS fiddle that reliably duplicates the bug. Pleaser do not try and reopen closed issues on very outdated versions of the library.

Cheers

Oli
