### ISSUE TITLE
setFilter Method Giving Console Error While Using Server Side Pagination

### ISSUE THREAD

**Issue by lalitdhami** [olifolkerd/tabulator#4351]
**Describe the bug**
setFilter Method Giving Console Error While Using Server Side Pagination . i am using server side pagination to fetch the data then after i am using setfilter method to filter data based on some check box 
 
**Tabulator Info**
- using version 5.5 but it's not giving any error in 4.8 version

**Screenshots**

Error we are getting in console
tabulator.min.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'slice')
    at b.refreshPipelines (tabulator.min.js:2:75853)
    at g.rerenderRows (tabulator.min.js:2:57863)
    at b.reRenderInPosition (tabulator.min.js:2:77879)
    at b.refreshActiveData (tabulator.min.js:2:75244)
    at oe.refreshData (tabulator.min.js:2:103986)
    at oe.refreshFilter (tabulator.min.js:2:246996)
    at oe.userSetFilter (tabulator.min.js:2:238569)
    at table.<computed>.table.<computed> [as setFilter] (tabulator.min.js:2:103152)
    at We.<anonymous> (Testcase_Result_Detail_report.html?testcase=onid_pv_r1.1_testcases&bug=onid_pv_r1.1_bug&project=ONID%20PV%20R1.1:411:23)
    at tabulator.min.js:2:93275

Example Code:

var table = new Tabulator("#testreport", {
                ajaxURL: trgt_url,
                ajaxConfig: "GET",
                pagination: true,
                groupBy:"testSetTag",
                paginationMode: 'remote',
                placeholder:"No Matching Data",
                dataTree:true,
                dataTreeStartExpanded:true,
                dataTreeFilter:false,
                dataTreeSort:false,
                tooltips: true,
                layout: "fitDataFill",
                autoResize:true,
                layoutColumnsOnNewData:true,
                paginationCounter:"rows",
                paginationSize: rowValue.value === "" ? 200 : rowValue.value,
                dataSendParams: {
                  page: "page",
                  size: "size",
                },
                /*autoColumns:true,*/
                columns: [
					{
                        title: "Section",
                        field: "sectionName",
                        sorter: "string",
                        resizable:true,
                    }, {
                        title: "Case Title",
                        field: "case_title",
                        sorter: "string",
                        hozAlign: "left",
                        editor: "select",
                        resizable:true,
                        formatter:"textarea",
                    }, {
                        title: "Status",
                        field: "case_status",
                        sorter: "string",
                        hozAlign: "left",
                        editor: "select",
                        resizable:true,
                    }, 
                ],
              }); 
              }

              table.on("tableBuilt", function(){
                temp_filter = [];
                var ele = document.getElementsByName('Filter_Status');
                for (i = 0; i < ele.length; i++) {
                    if (ele[i].checked) {
                      temp_filter.push(ele[i].value)
                    }
                }
                table.setFilter([{field:"case_status", type:"in", value:temp_filter}])
            })

**Comment by olifolkerd** [comment]
Hey @lalitdhami 

Thanks for the info, i have pushed a fix for this to master and will include it in todays patch release.

Cheers

Oli :)
