### ISSUE TITLE
Tabulator 5.5 not working column header filter with children data

### ISSUE THREAD

**Issue by DenishTechtic** [olifolkerd/tabulator#4352]
Tabulator 5.5 not working column header filter with children data
![image](https://github.com/olifolkerd/tabulator/assets/122869784/4021fc20-2d6a-4cd6-854b-8a121d3145ba)

![image](https://github.com/olifolkerd/tabulator/assets/122869784/74b9b9d7-f9ad-4110-9fc1-af1cdd867532)

**Comment by olifolkerd** [comment]
Hey @DenishTechtic 

Have you enabled the `dataTreeFilter` table option: https://tabulator.info/docs/5.5/tree#overview-compatibility

Cheers

Oli :)
