### ISSUE TITLE
validator does not work when tabEndNewRow is set.

### ISSUE THREAD

**Issue by Federico-Luna** [olifolkerd/tabulator#4354]
**Describe the bug**
Validator does not work when tabEndNewRow is set,

**Tabulator Info**
- Which version of Tabulator are you using? Tabulator 5.5

**Working Example**
JSFiddle with validator: "required": https://jsfiddle.net/Federico_Moon/c2ya45vd/
JSFiddle with validator function: https://jsfiddle.net/Federico_Moon/96bm2dhp/

**To Reproduce**
Click on comment cell (don't write nothing) and press tab key.

**Expected behavior**
What is expected to happen is that the new row is not created and the focus remains on the comment cell.

**Desktop (please complete the following information):**
 - OS: Windows 10 and Windows 11
 - Browser: chrome
 - Version 120.0.6099.72 (Build oficial) (64 bits)

**Comment by olifolkerd** [comment]
Hey @Federico-Luna 

Thanks for the headsup, i have just pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)
