### ISSUE TITLE
Issue on frozen column and dynamically frozen row when scrolling with large columns table

### ISSUE THREAD

**Issue by missill** [olifolkerd/tabulator#4355]
Hi guys,

First, thanks for this amazing lib.

I encounter a bug when i freeze dynamically a row with some already frozen columns in a large columns table.
So when i scroll, the `.tabulator-frozen-rows-holder` class seems to have a fixed width contrary the `.tabulator-headers` class and the scroll doesn't work well anymore.

I reproduce the bug on [jsfiddle](https://jsfiddle.net/4Lj8oqrk/2/).

You just have to select a row, click to freeze row button and scroll right.
Once the fixed visible width is exceeded, the problem occurs.

Maybe i forgot a tabulator option or other to fix this. I don't know. If you can tell me thanks.

**Comment by olifolkerd** [comment]
Hey @missill 

Thanks for the headsup, i have pushed a fix for this to the 5.6 branch which i hope to release in the next couple of weeks.

Cheers

Oli :)

**Comment by missill** [comment]
Hi @olifolkerd 
Thanks for the fix, nice job, you rock !
Cheers
