### ISSUE TITLE
Frozen Fields Hidden  Causes blank space and the fields behind do not move to the left

### ISSUE THREAD

**Issue by Kokocoding** [olifolkerd/tabulator#4356]
[for example](https://jsfiddle.net/phLq3wo7/5/)

Fields                 A B C D E F G  I hidden Field B 
now become     A    C D E F G
I hope become  A C D E F G

I think this is a bug ?

thanks

**Comment by olifolkerd** [comment]
Hey @Kokocoding 

Thanks for the headsup,

I have pushed a fix for this to the 5.6 branch that i hope to release in a couple of weeks time.

Cheers

Oli :)
