### ISSUE TITLE
table.updateColumnDefinition ->update column frozen

### ISSUE THREAD

**Issue by reut-halfon** [olifolkerd/tabulator#4357]
i have table with right frozen column,
i this column i have clickMenu :[], i want to update this props with updateColumnDefinition 
 but when i update this i get "Uncaught TypeError: Cannot set properties of undefined (setting 'position')
    at n.value (FrozenColumns.js:295:18)..."

i have the last versions ->5.2.0

Exp:
this me column:
 columns.push({
        frozen: true,
        headerSort: false,
        resizable: false,
        field: 'action',
        title: "<button class='btn btn-link-light btn-link-optdropdown-toggle' ><i class='fas fa-ellipsis-h' aria-hidden='true'></i></button>",
        headerClickMenu: () => headerClick(),
        formatter: menuIcon,
        maxWidth: 60,
        minWidth: 60,
        clickMenu: getMenu(),
        hozAlign: "center",
        vertAlign: "middle",
        headerHozAlign: "center",
    })

and this the update :table.updateColumnDefinition("action", { clickMenu: getMenu() }).then(function (column) {
            })
                .catch(function (error) {
                    **//this enter here**
                    debugger;

                });

**Comment by olifolkerd** [comment]
Hey @reut-halfon 

I have pushed a fix for this to the 5.6 branch and will include it in the release in a couple of weeks.

Cheers

Oli :)
