### ISSUE TITLE
I have already set the `values`, but the error message is still pops up.

### ISSUE THREAD

**Issue by Jeff19981025** [olifolkerd/tabulator#4358]
<img width="922" alt="Screenshot 2024-01-04 at 1 09 15 PM" src="https://github.com/olifolkerd/tabulator/assets/57737383/492945e2-7353-4fdf-8bc7-732c90c4401a">

**Describe the bug**
I have already set the `values`, but the error message is still pops up.

**Tabulator Info**
- Which version of Tabulator are you using?
- 5.5.2

**Working Example**
```javascript
{
            title: 't',
            field: 'f',
            hozAlign: 'center',
            vertAlign: 'middle',
            headerFilter: true,
            headerHozAlign: 'center',
            editor: 'list',
            editorParams:{
                values: ['a', 'b', 'c']
            },
```
YOU MUST include a link to a JS Fiddle or Codepen that demonstrates the problem, it is very hard to diagnose an issue from a simple description.

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. create a tabulator object with a column using 'list' editor
2. See error

**Expected behavior**
No error.

**Screenshots**

**Desktop (please complete the following information):**
 - Macbook

**Additional context**

**Comment by olifolkerd** [comment]
Hey @Jeff19981025 

I am unable to replicate your issue, it all seems to work fine when  try it.

If you are still having trouble, please create a working JS Fiddle and include a link to it in this ticket, i can then see if get the same warning.

Cheers

Oli :)
