### ISSUE TITLE
Enhance resizableColumnFit + fitColumns layout with a setting to stop table from growing wider and creating horizontal scrollbar

### ISSUE THREAD

**Issue by NeuralSixty** [olifolkerd/tabulator#4361]
Please consider this as a follow-up to https://github.com/olifolkerd/tabulator/issues/2609.

Quoting from https://tabulator.info/docs/5.5/layout#fittowidth:

> In this layout mode, columns without a width set are resized to fill any remaining space on the table. **If all columns cannot fit on the table then a scrollbar will appear.**

The bolded statement is important for the next part, where I quote https://tabulator.info/docs/5.5/layout#resize-column-fit:

> It is worth noting that **should the neighbouring column reach is max or min width while the resize is occurring, that the next column over will then begin to resize in its place.** If the resize runs out of columns then the total width of all the columns will change.

We have a use case in our project, demonstrated at https://jsfiddle.net/bwoeh51a/11/. All of the columns are resizable. As we resize a column to the right, that column or the resizableColumnFit cascade it's part of (proven by the second bolded statement) will eventually hit the right border of the table. As per the first bolded statement, this will cause the table to grow in width and spawn a horizontal scrollbar. The following video shows this in action: 

https://github.com/olifolkerd/tabulator/assets/112021767/550f3ee8-9616-44be-89c2-5c9842feb979

It's understood that this is default behavior from Tabulator. Unfortunately for our use case, however, we don't want the table to grow wider at all. This means that, as soon as the right border of the table is hit, the resize should stop. Ideally we would have a setting for this.

As a bonus (if possible - quoting from https://tabulator.info/docs/5.5/layout#resize-column):

> Note: If you double click on a resizable border it will resize the column to fit the data it contains.

We would also enjoy if the table didn't grow in width as well in this case. Perhaps clip the resize shorter if the right border of the table is hit.

Thank you.

**Comment by olifolkerd** [comment]
Hey @NeuralSixty 

Thanks for the feedback, 

They layout mode only covers the initial render, and i dont feel it needs any augmentation at this point as the data has to go somewhere.

That being said, for your reszing needs, have you tried using the `resizableColumnFit` option to help manage the resize of your columns and maintain overall data width [Resize Column Docs](https://tabulator.info/docs/5.5/layout#resize-column-fit)

Cheers

Oli :)
