### ISSUE TITLE
Incorrect table rendering if the element has any transforms applied

### ISSUE THREAD

**Issue by AdiDD** [olifolkerd/tabulator#4364]
**Describe the bug**
If the DOM element on which we create the `Tabulator` has any transforms applied while the table is being drawn, it will not render properly. (table's width and header's height)

**Tabulator Info**
5.5.2

**Working Example**
Open the modal, and click on a table row in order to redraw it while no `transform` is being applied to the element.
https://jsfiddle.net/asce90/jxdv1Lpn/42/

**To Reproduce**
1. Create an element that has initially `scale: 0;`
2. Set `scale:1` and initialize or redraw the table

**Expected behavior**
The tabulator should have the element's layout width and height, instead it had the element's rendering width and height.

**Screenshots**

- how the table renders 
![image](https://github.com/olifolkerd/tabulator/assets/16980592/9ce4466a-74ed-461f-b370-ec34bdbe81f7)
- how it should render 
![image](https://github.com/olifolkerd/tabulator/assets/16980592/784ce1a7-566a-4a3b-b0e8-912a32a2ab58)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 120.0.6099.217

**Comment by AdiDD** [comment]
I investigated the problem, I will submit a PR shortly.

**Comment by olifolkerd** [comment]
Hey @AdiDD 

Thanks for the PR, but your suggested solution will break the rendering in other ways im afraid.

Have you tried applying the transform to a parent element of the table rather than the table itself?

Cheers

Oli :)
