### ISSUE TITLE
Use multiple group by with custom formatter

### ISSUE THREAD

**Issue by ortwic** [olifolkerd/tabulator#4368]
**Describe the bug**
It should be possible to group by multiple columns with custom formatter like so:
```
var table = new Tabulator("#example-table", {
    groupBy: {
      gender: true,
      // group by progress in steps of 10
      progress: function(data){
        var group = Math.floor(data.progress / 10) * 10;
        return group + "-" + (group + 9);
    }
   },
});
```

**Tabulator Info**
5.5.2

**Working Example**
[Example](https://stackblitz.com/edit/typescript-vcgxg4?file=index.ts)

**To Reproduce**
See example

**Expected behavior**
It should be possible to group by multiple columns with custom formatter like so:
```
var table = new Tabulator("#example-table", {
    groupBy: {
      gender: true,
      // group by progress in steps of 10
      progress: function(data){
        var group = Math.floor(data.progress / 10) * 10;
        return group + "-" + (group + 9);
    }
   },
});
```

It would be very nice to set the custom group by formatter in the column definition.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome (latest)

**Comment by olifolkerd** [comment]
Hey @ortwic 

You can already group by multiple columns by passing an array to the `group` option, or using a custom group function, checkout the [Grouping Documentation[(https://tabulator.info/docs/5.5/group) for more info.

Cheers

Oli :)

**Comment by ortwic** [comment]
Yes it is possible to group by multiple columns but like in the description it is not possible to group by multiple columns AND use custom group functions PER column to do custom operations like described in the example.

**Comment by olifolkerd** [comment]
What happens if you pass functions in the array?

**Comment by ortwic** [comment]
Well I see. 
This is a problem from ```@types/tabulator-tables``` then and the persistance modul as it is not able to persist groupBy functions but field names only.

**Comment by olifolkerd** [comment]
Ahh yes, you can't persist custom functions, because it stores things json encoded, it can't handle functions.

That is a hard limit I'm afraid

**Comment by ortwic** [comment]
Well, is it worth to reopen this issue to fix this persistance problem?

This is a workaround for that:
```
    persistenceWriterFunc(id, type, data) {
		  localStorage.setItem(id + "-" + type, JSON.stringify(data, (key, value) => {
		  return type === 'group' && key !== 'groupHeader' && typeof value === 'function' ? value.name : value;
      }));
    },
```

On table init you have to call ```setGroupBy([...])``` with your funcs.

**Comment by olifolkerd** [comment]
This isn't a bug it is a limitation of json encoding the data. 

In this instance the proposed work around would only work on named functions in the global namespace, it wouldn't work on anonymous functions or scoped functions.

**Comment by ortwic** [comment]
That is right. Don't know a better solution yet. I'm sure this problem happens elsewhere too and might be solved already? How about custom sorter funcs?

**Comment by olifolkerd** [comment]
There would be a need to serialize the function if it is anonymous, which is what a lot of users will do. There are so many different caveats here that it would be impossible to do thoroughly, for example if the function passed in was from an instantiated class with a bound function there would be literally no way to rebind that on start up.

I understand that for your usage case there is a solution but it is not wholistic so it will not be ok for the library as a whole.

The good news is you can easily override the functionality for your own logic using the functionality you have setup so the issue has been resolved for your codebase

**Comment by ortwic** [comment]
The hacky "workaround" by using the function name is really bad and not relyable. I'd really suggest that object could be taken as an argument to reconstructed the used fieldname when reading persisted groupBy settings. 

```
var table = new Tabulator("#example-table", {
    groupBy: {
      gender: true,
      // group by progress in steps of 10
      progress: function(data){
        var group = Math.floor(data.progress / 10) * 10;
        return group + "-" + (group + 9);
    }
   },
});
```

If I'd like to contribute those changes, is there an opened issue required?

PS: I tried another workaround by customizing the groupHeader (field name is there available) but it won't work since the grouping logic respects only the groupBy arguments, see `assignRowToExistingGroup()`.
