### ISSUE TITLE
Tabulator is not defined

### ISSUE THREAD

**Issue by ErickRodriguezH** [olifolkerd/tabulator#4369]
Hi everyone,

I am experiencing an issue with a specific error. The problem is that it only occurs for a few users. The data on the tables doesn't load, and the error message is "tabulator is not defined." However, on most computers, it works normally. I don't know why this error only happens for a few users.

![MicrosoftTeams-image](https://github.com/olifolkerd/tabulator/assets/99165760/4c20331c-fd4e-4371-9a28-5bd08332a065)
![MicrosoftTeams-image (1)](https://github.com/olifolkerd/tabulator/assets/99165760/f6f0917c-8090-407a-935c-becd5c341ed3)
link href="[https://unpkg.com/tabulator-tables@5.2.4/dist/css/tabulator.min.css"](https://unpkg.com/tabulator-tables@5.2.4/dist/css/tabulator.min.css%22) rel="stylesheet">
<link href="[https://unpkg.com/tabulator-tables@5.2.4/dist/css/tabulator_modern.min.css"](https://unpkg.com/tabulator-tables@5.2.4/dist/css/tabulator_modern.min.css%22) rel="stylesheet">
<script type="text/javascript" src="[https://unpkg.com/tabulator-tables@5.2.4/dist/js/tabulator.min.js"></script>](https://unpkg.com/tabulator-tables@5.2.4/dist/js/tabulator.min.js%22%3E%3C/script%3E)

**Comment by olifolkerd** [comment]
Hey @ErickRodriguezH 

This is likely due to the order in which your code executes, are you making sure the document is ready before instatiating your table?

Cheers

Oli

**Comment by ErickRodriguezH** [comment]
Hi, @olifolkerd 

I already checked this, and the issue is that it only happens to some users and not to others
