### ISSUE TITLE
Expandable row/columns - re issue #434

### ISSUE THREAD

**Issue by hannit** [olifolkerd/tabulator#437]
Hi,
I have a table containing a large multi-line area that varies in size.
I want to make it into extendable div, is there a way to do that with tabulator ?

I was not looking for 'textarea', but rather something like bootstrap collapse.
I want to show 2 text lines and a link that when clicked will show the rest of the data

Thanks

**Comment by olifolkerd** [comment]
would you be looking to have any of the traditional cells/columns in the table or would you like a completely custom row formatter?

**Comment by hannit** [comment]
I don't really care which way to solve this :-)
I started with trying to create BS 'collapse' inside a cell with 'html' formatter - but it didn't work as expected
will try whatever you have to solve this

**Comment by olifolkerd** [comment]
You could use a custom ***rowFormatter*** to do this, the important thing is to make sure that you call the ***row.normalizeHeight()*** function after the elements change to update the row height.

in fact this would probably work with your bootstrap collapse object as well as long as you call the normalizeHeight function on the row after the changes have been made.

```js
$("#example-table").tabulator({
    rowFormatter:function(row){
        //row - row component
        var visible = $("<div class='visible-line'>You can see me</div>");
        var hidden = $("<div class='hidden-line'>You cant see me to start with</div>");
        
        visible.click(function(){
            hidden.toggle();
            row.normalizeHeight(); //recalculate the row height
        });

        row.empty().append(visible).append(hidden);
    },
});
```
