### ISSUE TITLE
Array field update not triggering for all same field columns formatter

### ISSUE THREAD

**Issue by Xiuer0x0** [olifolkerd/tabulator#4373]
**Describe the bug**
After setting multiple identical array fields for different displays in columns, updating the array fields cannot trigger the update of each field.

It was observed that after update data, only last setting array field column formatter working.

**Tabulator Info**
5.5.3

**Working Example**
https://codepen.io/Xiuer0x0/pen/YzgxGmx

**To Reproduce**
In example
Click the "Set row 2 random list" button to see that the "List Count" formatter is not working, only the last "List Content" works.
If you reverse the order of two items using 'list' from the columns option, you will still get that only the last set 'formatter' takes effect.

**Desktop (please complete the following information):**
 - OS: window 10 Pro (64 bit) 22H2
 - Browser: Chrome
 - Version: 120.0.6099.110 (official version) (64 bit)

Please forgive my poor English.

**Comment by lstgithub578** [comment]
You can use "mutator" and "mutateLink". I don't know if you want this effect.
![image](https://github.com/olifolkerd/tabulator/assets/55378864/486f8774-d5b7-41e8-82bc-9add69a99269)

**Comment by Xiuer0x0** [comment]
> You can use "mutator" and "mutateLink". I don't know if you want this effect. ![image](https://private-user-images.githubusercontent.com/55378864/299576440-486f8774-d5b7-41e8-82bc-9add69a99269.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMjQ4NDYsIm5iZiI6MTcwNjMyNDU0NiwicGF0aCI6Ii81NTM3ODg2NC8yOTk1NzY0NDAtNDg2Zjg3NzQtZDViNy00MWU4LTgyYmMtOWFkZDY5YTk5MjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDAzMDIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwYzllMmU3ZjRmYjU5OTBkZGJhMjk2NzYwOGRlZmI2NDcyNTI3NTY1OTQ5YmE5ZDcwZDI4OTNmN2YxYmE5MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RZzGU0q0HrYiLc5M2daltEyp-DcbzEfjqKmibBz3kD0)

Thank you very much for your reply, let me learn one more usage.

This method can be used for simple applications, but when I need more fields to reference the same data, the cooperation between `mutator` and `mutateLink` does not seem to go smoothly.

And further found that `mutateLink` also has the same problem. Only the `mutator` set in the last field is triggered, and the last `mutator` will overwrite the settings of the previous fields during the first rendering.
![image](https://github.com/olifolkerd/tabulator/assets/30082521/ea626ce5-c7fc-40d8-baf9-8926718c5f4d)

The `mutator` in the last column pollutes the `mutator` setting in the previous column.

![image](https://github.com/olifolkerd/tabulator/assets/30082521/3fceea8e-9897-4f9b-a73d-5ff57a99a169)

try `mutator` and `mutateLink`, working example: https://codepen.io/Xiuer0x0/pen/qBvVYxw

**Comment by lstgithub578** [comment]
@Xiuer0x0  You can set a different `field and then use `mutator`.
![image](https://github.com/olifolkerd/tabulator/assets/55378864/d6560a7a-1b2d-456a-8c3a-245717e551d2)

**Comment by Xiuer0x0** [comment]
> @Xiuer0x0 You can set a different `field` and then us...

It turns out that `mutateLink` can set multiple `field`.
Although the bug I originally encountered still exists, I can ignore the original problem and use `mutateLink` to achieve the effect I need.

Thank you very much for your help.

**Comment by olifolkerd** [comment]
Hey,

You should not use multiple columns bound to the same field, Tabulator expects the field name to be unique, otherwise you may encounter issues,

If you want to bind multiple active columns to the same field, then i would suggest using a mutator to map the value to a second field.

Cheers

Oli :)
