### ISSUE TITLE
Tabulator fails to populate when HTML tag is on a new line

### ISSUE THREAD

**Issue by j-madden** [olifolkerd/tabulator#4377]
**Describe the bug**
Unusual behaviour when initialising a tabulator table with a `table` tag.
When the tag is on the same line, tabulator populates the table fine. With a new line, it fails. 

**Tabulator Info**
- v 5.5.0

**Working Example**
https://jsfiddle.net/thcv1fLz/

**To Reproduce**
1. Open JS Fiddle example
2. See the rendered table on the right with both working/broken tables
- `example-table-1` is populated by tabulator
- `example-table-2` is **not** populated by tabulator

**Expected behavior **
Both approaches would lead to the same result. 

**Desktop**
 - OS: MacOS 14.2.1
 - Browser: Chrome
 - Version: 120.0.6099.234

**Additional context**
I see the warning:
> "Unable to parse data from empty table tag, Tabulator should be initialised on a div tag unless importing data from a table element."

When I swap `table` to `div` it resolves the issue I am experiencing, although it doesn't work with `table`.
If I'm missing something, some insight on the proper approach would be great.

**Comment by olifolkerd** [comment]
@j-madden 

If you are passing data into your table programatically you should be creating it on a `div` tag. As the message states, you should only use a `table` tag if you are trying to import data directly from an HTML table, and in that case the table element will contain the rows of the table and not through an error.

In summary use a `div` tag as per all the examples

Cheers

Oli :)
