### ISSUE TITLE
Not able to build custom module using Tabulator

### ISSUE THREAD

**Issue by kaashok** [olifolkerd/tabulator#4379]
**Describe the bug**
I am using Tabulator version 5.5.4 within my TypeScript application and intend to develop a custom module. I am following the steps outlined in the [Tabulator documentation](https://tabulator.info/docs/5.5/module-build). However, I am encountering an error during the custom module creation process, and the specific error message is provided below.

**Tabulator Info**
- 5.5.4 

**Working Example**

**custom-Module.ts**

```
import * as Tabulator from "tabulator-tables";
    class CustomModule extends Tabulator.Module{
        constructor(table){
            super(table);
    
            //register table options
            //register column options
            //register table functions
            //register component functions
        }
    
        initialize(){
            //subscribe to internal events
            //register data handlers
        }
    }
    
    CustomModule.moduleName = "custom";
```

**tabulator.ts**

```
import * as Tabulator from "tabulator-tables";
Tabulator.Tabulator.registerModule(CustomModule );
```

**Screenshots**
![image](https://github.com/olifolkerd/tabulator/assets/22614984/e9dc5dd5-0a97-4fe3-9143-fc324c144924)

![image](https://github.com/olifolkerd/tabulator/assets/22614984/32475958-f13c-4bf9-a9ec-6506203a61bf)

**Environment Configuration**

- @types/tabulator-tables 5.5.7
- tabulator-tables 5.5.4
- tsconfig.json
   - target: es5
    - module: amd

**Comment by olifolkerd** [comment]
Your import statement does not look correct, you appear to trying to import the entire file as an object, you should be importing the classes you need:

```js
import {TabulatorFull as Tabulator, Module} from "tabulator-tables";
```

Cheers

Oli :)
