### ISSUE TITLE
is there a way to disable pagination if the number of pages returned is one?

### ISSUE THREAD

**Issue by madhumithavenkat** [olifolkerd/tabulator#438]

**Comment by olifolkerd** [comment]
what do you mean by disable pagination? 

do you mean hide the pagination controls?

**Comment by madhumithavenkat** [comment]
Yes,to hide pagination controls if there only one page returned.

**Comment by olifolkerd** [comment]
are you using local or remote pagination?

**Comment by madhumithavenkat** [comment]
remote pagination

**Comment by olifolkerd** [comment]
In that case i would suggest you use the ***ajaxResponse*** callback, to check the number of pages available and hide/show the footer as needed:

```js
$("#example-table").tabulator({
    ajaxResponse:function(url, params, response){
        //url - the URL of the request
        //params - the parameters passed with the request
        //response - the JSON object returned in the body of the response.

        if(response.last_page == 1){
            $(".tabulator-footer").hide();
        }else{
            $(".tabulator-footer").show();
        }

        return response; //return the response data to tabulator
    },
});
```

**Comment by madhumithavenkat** [comment]
hey oli,
could i use ajaxResponse call back and setData function together?
i tried using and ended up with errors
$("#device-table").tabulator("setData",{
    url:window.location.protocol+ "//" + window.location.host + "/users/getDevice",
    params:{key1:value},
    ajaxResponse:function(url, params, response){
        //url - the URL of the request
        //params - the parameters passed with the request
        //response - the JSON object returned in the body of the response.

        if(response.last_page == 1){
            $(".tabulator-footer").hide();
        }else{
            $(".tabulator-footer").show();
        }

        return response; //return the response data to tabulator
    },
});
thank you!

**Comment by olifolkerd** [comment]
Hey,

they ajaxResponse callback has to be defined in your tabulator constructor, you cannot pass it to the setData function.

Cheers

Oli

**Comment by madhumithavenkat** [comment]
hi oli,
works well!
how do i do the same thing for local pagination?
thank you!

**Comment by olifolkerd** [comment]
for local pagination you could do something similar on the dataLoaded callback:


```js
$("#example-table").tabulator({
    dataLoaded:function(data){
        //data - all data loaded into the table

        if($("#example-table").tabulator("getPageMax")){
            $(".tabulator-footer").hide();
        }else{
            $(".tabulator-footer").show();
        }
    },
});
```

Actually having thought about it, this approach should work for both local and remote pagination

Cheers

Oli

**Comment by madhumithavenkat** [comment]
yaay!! thanks again!

**Comment by madhumithavenkat** [comment]
hey oli,
is there a way to hide pagination if after filtering only one page is returned?

**Comment by olifolkerd** [comment]
with remote or local pagination?

**Comment by madhumithavenkat** [comment]
remote pagination

**Comment by olifolkerd** [comment]
are you filtering remotely as well or filtering localy in the table?

**Comment by madhumithavenkat** [comment]
i am filtering remotely

**Comment by olifolkerd** [comment]
if you are filtering remotely then your server should be updating the ***last_page*** value in the response to match the number of pages available to match your filtered response. In which case the previous code snippets should work for you

**Comment by madhumithavenkat** [comment]
it works good now! 
thabnk you!
