### ISSUE TITLE
Error on _virtualRenderFill using Vue 3

### ISSUE THREAD

**Issue by dylanFdvhuset** [olifolkerd/tabulator#4381]
After updating to Vue 3.4, I get an error :  TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node

This comes from  _virtualRenderFill function from VirtualDomVertical.js

row.getElement (line 302 in code) returns false instead of an actual row.

It is happening when having a lot of cells in a row but when we remove some randomly it dissapears.

On created I fetch my data and the table first has an empty array then quickly after it gets a new array of data using replaceData. And it breaks.
But if I set a v-if on the tabulator component and display it after data is fetched then it works

**Comment by olifolkerd** [comment]
Hey @dylanFdvhuset 

That is a rather complicated issue you are describing, please fill in the issue template and include a link to a working JS fiddle so we can see the problem in action.

Cheers

Oli :)
