### ISSUE TITLE
Tooltips: currently mousemove, why not mouseenter?

### ISSUE THREAD

**Issue by JuulJuup** [olifolkerd/tabulator#4382]
Currently when I use the tooltip in a column definition, the standard event is triggered on a cell-mousemove. However, the tooltip gets redrawn every single time I make a little movement with my mouse. I think the tooltip will be much more beautiful when it's triggered on mouseenter and is hidden on mouseleave, instead of flickering.

`{ title: "EXPIRES", field: "whois_expires", formatter: skeletonFormatter, tooltip: true}`

I noticed the `Tooltip` class has the following lines of code:
```
if(column.definition.tooltip && !this.tooltipSubscriber){
			this.tooltipSubscriber = true;
			
			this.subscribe("cell-mousemove", this.mousemoveCheck.bind(this, "tooltip"));
			this.subscribe("cell-mouseout", this.mouseoutCheck.bind(this, "tooltip"));
		}
```

It can be adjusted here.

Or is there something I'm doing wrong?

**Comment by olifolkerd** [comment]
@JuulJuup if we did this the tooptip would only appear at the edge of the cell, which would feel odd
