### ISSUE TITLE
group row inconsistencies if rows > pageSize

### ISSUE THREAD

**Issue by Tzaoh** [olifolkerd/tabulator#4383]
**Describe the bug**
Context. Original table:
![image](https://github.com/olifolkerd/tabulator/assets/5722357/a4d9a337-80f5-43cc-a801-ba0af08405ca)

1. In a table with grouped data, the group row does count with regarding `pageSize`:
For instance, in the provided example with a `pageSize` of 5, 4 data rows are rendered and 1 group row is rendered.
![image](https://github.com/olifolkerd/tabulator/assets/5722357/e78ea383-4bf0-4444-a368-e563b15e48c4)

2. In a table with two or more group rows, when a group row is expanded and contains more rows than the `pageSize` the lower collapsed group rows are not displayed.
For instance, in the below images it can be seen the original table grouped by `gender` but only `male` is shown (not `female`).
![image](https://github.com/olifolkerd/tabulator/assets/5722357/fbf19fcd-4287-4458-b5b9-5002e811e273)

**Tabulator Info**
- Which version of Tabulator are you using?
5.5.4

**Working Example**
https://jsfiddle.net/z5hxLv24/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to ['Fiddle example'](https://jsfiddle.net/z5hxLv24/)
2. Click on collapse and expand in the upper group row arrow
3. Observe the described behavior

**Expected behavior**
- I expect to have `pageSize` (5) number of data rows.
- I expect to always see the collapsed group rows

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 122.0 (64-bit

Tabulator is great Oli, congratz for such an awesome project.
Thank you

**Comment by olifolkerd** [comment]
Hey @Tzaoh 

This is the correct behaviour, as you move through the pages of the table you will see the female group.

Cheers

Oli :)

**Comment by DirtyWhite** [comment]
@olifolkerd It makes sticky-group-row impossible😢
