### ISSUE TITLE
Pin rows feature

### ISSUE THREAD

**Issue by harshilsharmaa** [olifolkerd/tabulator#4384]
*Is your feature request related to a problem? Please describe.**
I want to pin some important rows and a sorting feature to show pinned rows.

**Describe the solution you'd like**
A cell which contains a "pin" icon and when we click on that than the color must changed of that icon also when it is clicked it should call an event which return the data of that row so that we can perform specific actions on that pinned row.

**Describe alternatives you've considered**

**Additional context**
For example in this we can pin or star the important rows.
![tabulator-fea](https://github.com/olifolkerd/tabulator/assets/71216106/b536a3be-bd44-4e47-a71d-d474f21382e5)

**Comment by olifolkerd** [comment]
Hey,

You can already freeze rows to the top of the table with the frozen rows feature:
https://tabulator.info/docs/5.5/layout#frozen-row

Cheers

Oli :)
