### ISSUE TITLE
The CellComponent type argument of the custom formatter does not have a getTable method when printing.

### ISSUE THREAD

**Issue by sinbino** [olifolkerd/tabulator#4386]
**Describe the bug**
The CellComponent type argument of the custom formatter does not have a getTable method when printing.

**Tabulator Info**
5.5.4

**Working Example**
https://jsfiddle.net/sinbino/xdrbmu4c/25/

**To Reproduce**
1. Go to example  https://jsfiddle.net/sinbino/xdrbmu4c/25/
2. Click the print button
3. Printing is not executed and an error is printed to the console "Uncaught TypeError: cell.getTable is not a function"

**Expected behavior**
Printing is performed correctly

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser chrome  
 - Version 121.0.6167.160

**Comment by olifolkerd** [comment]
Hey @sinbino 

Thanks for the headsup.

I have just pushed a fix for this to the 5.6 branch and will include it in the next feature release in a week or so.

Cheers

Oli :)
