### ISSUE TITLE
MultiLevel Grouping Calculation

### ISSUE THREAD

**Issue by equalinfocom** [olifolkerd/tabulator#4389]
add all level grouping calculation 
![Capture](https://github.com/olifolkerd/tabulator/assets/159624699/6553460d-46e1-4195-ae27-8805c596b387)

**Comment by olifolkerd** [comment]
Because the group calc lines are the same format as rows, bottom calcs in nested groups would stack on top of each other with no clear distinction between them

**Comment by equalinfocom** [comment]
ANY OTHER SOLUTION ???
