### ISSUE TITLE
Select cell content after moving cursor in spreadsheet mode

### ISSUE THREAD

**Issue by BernhardBaumrock** [olifolkerd/tabulator#4393]
Hey @olifolkerd, congrats to the new release!!

**Describe the solution you'd like**

Just played around with the spreadsheet demo and I want to suggest that when editing one cell and then jumping to another to select the cells content so that I can instantly overwrite it.

At the moment the cursor is placed at the end of the cell, which means I have to either hit several strokes on the keyboard or use the mouse. In excel I can move the active cell focus and then just type and it will overwrite the cell's value.

I think this should be the preferred behaviour, because if anybody doesn't want that, he/she can still hit the right arrow key and the cursor will be at the end of the cell's content.

Thx in advance!

If there's already a setting for it and I did not properly RTFM please apologise :)

**Comment by olifolkerd** [comment]
The good news is there is already an option for that on the input editor, you can use the selectContents option in the editorParams for the editor

 
Checkout the docs here:
https://tabulator.info/docs/5.6/edit#editor-input

Cheers

Oli :)

**Comment by BernhardBaumrock** [comment]
Nice, thank you! The new release is looking really great!
