### ISSUE TITLE
Datetime editor value incorrectly set with 12 hour format

### ISSUE THREAD

**Issue by nmih** [olifolkerd/tabulator#4397]
**Describe the bug**
When using the `formatter: "datetime"` option on a column, the value fed to the HTML input element is a 12 hour string without AM/PM instead of the 24 hr time. Thus times like "2023-10-15 17:30:00" are shown on the editor as 5:30 AM rather than PM.

**Tabulator Info**
- Which version of Tabulator are you using?
    - 5.6

**Working Example**
- https://jsfiddle.net/nathan_mih/t7Lbj16a/31/

**To Reproduce**
1. Load JSFiddle, note if datetime value is AM or PM 
2. Click on any of the PM datetimes for editing
3. See input switch to AM

**Expected behavior**
- Time should remain in PM.
- https://github.com/olifolkerd/tabulator/blob/master/src/js/modules/Edit/defaults/editors/datetime.js#L40 should have "HH:mm" rather than "hh:mm" for the time format.

**Screenshots**
Before edit:
![image](https://github.com/olifolkerd/tabulator/assets/1766428/746a0ac4-1417-4eb2-9e96-c90b82c0f1cf)

After click to edit:
![image](https://github.com/olifolkerd/tabulator/assets/1766428/26eda3df-67c8-4019-a01c-ae5bfd98acc4)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 121

**Comment by olifolkerd** [comment]
Hey @nmih 

Thanks for the headsup, i have pushed a fix for this to the master branch and will include it in todays patch update.

Cheers

Oli :)
