### ISSUE TITLE
 'select' is missing in the "Editor" type

### ISSUE THREAD

**Issue by schlundus** [olifolkerd/tabulator#4399]
**Describe the bug**
It seems that 'select' is missing in the "Editor" type

![image](https://github.com/olifolkerd/tabulator/assets/17083185/538bf02b-f6d2-410e-8475-6c8e7d307bf7)

**Tabulator Info**
- Which version of Tabulator are you using?
 "@types/tabulator-tables": "^5.5.9",
   "tabulator-tables": "^5.6.0",

**Comment by olifolkerd** [comment]
There is no select editor. It was replaced with the list editor a couple of years ago

Cheers

Oli

**Comment by schlundus** [comment]
Hm, i'using 'select' in the headerfilters Options and it work's as expected...

![image](https://github.com/olifolkerd/tabulator/assets/17083185/07353bba-d855-4383-ab53-1e83b694b6f6)

**Comment by olifolkerd** [comment]
It has been deprecated and uses list under the hood. You should be using list.

**Comment by schlundus** [comment]
Ah, ok... i've tried 'list' and all is cool.... thanks for the hint... but who reads documentation (-; ?
So this is resovled for me... thanks for the hint
