### ISSUE TITLE
removeRow not working on IE lt 11

### ISSUE THREAD

**Issue by chaissac** [olifolkerd/tabulator#44]
Bonjour :)

Prior to IE12, Array.prototype.find is not defined, so the removeRow method doesn't work.
Adding this code can help :
```
if (!Array.prototype.find) {
Array.prototype.find = function (predicate, thisValue) {
        var arr = Object(this);
        if (typeof predicate !== 'function') {
            throw new TypeError();
        }
        for(var i=0; i < arr.length; i++) {
            if (i in arr) {  
                var elem = arr[i];
                if (predicate.call(thisValue, elem, i, arr)) {
                    return elem;  
                }
            }
        }
        return undefined;  
    }
}
```
There's also warnings in firefox's console : "ReferenceError: reference to undefined property item.tabulator_delete_row" but the row is deleted however.

Thanks for your great work, it helped me a lot !

Philippe

**Comment by olifolkerd** [comment]
Hey Philippe,

Great spot! thanks for the polyfill, i have just committed an update using the above code so all should be working now.

Cheers
Oli
