### ISSUE TITLE
Horizontal scolling issue with fixed, hidden columns

### ISSUE THREAD

**Issue by Kallius74** [olifolkerd/tabulator#4400]
**Describe the bug**
When using multiple fixed columns with some of them hidden, horizontal scrolling also moves the headers of the visible fixed colums but leave the data row part of the fixed colums at their position.

**Tabulator Info**
5.6.0

**Working Example**
https://jsfiddle.net/xwghn7ds/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Use the horizontal scroll bar to scroll right
2. Watch the header of the first column titled "Name", it scrolls out to the left but the data row part stays in place

**Expected behavior**
Horizontal scrolling with fixed, hidden columns should behave like in latest 5.5.x version.

**Screenshots**

-> Wrong (screenshot taken from fiddle with Tabulator version 5.6.0):
![image](https://github.com/olifolkerd/tabulator/assets/65338536/44d3e508-ad77-4717-8397-857a9427f819)

-> Right (screenshot taken from fiddle, but changed version info in script ref/css ref to version 5.5.4)
![image](https://github.com/olifolkerd/tabulator/assets/65338536/681b7ba3-65d7-4715-8b7d-844e7e0bf523)

**Desktop (please complete the following information):**
 - OS: Windows 11 
 - Browser: Chrome
 - Version: Latest

**Comment by azmy60** [comment]
Ah This also happened to me. Been looking since yesterday, hopefully I can put up a PR this week.

**Comment by olifolkerd** [comment]
Hey all,

Thanks for the PR @azmy60, i will include that in todays patch release

Cheers

Oli :)

**Comment by Kallius74** [comment]
Thanks a lot for fixing it!
