### ISSUE TITLE
Header Filter error when using simultaneously "initialSort" and "updateColumnDefinition"

### ISSUE THREAD

**Issue by jawher-tabessi** [olifolkerd/tabulator#4402]
**Description**
Error "Uncaught TypeError: e.getElement(...).setAttribute is not a function" when using simultaneously "initialSort" and "updateColumnDefinition"

**Tabulator Info**
- Tabulator version : 5.6

**Working Example**
https://jsfiddle.net/q9o2agms/5/

**To Reproduce**
1. Filter year by clicking 2020 fire an error
2. If comment initialSort filter works
3. If comment on dataLoaded block, initialSort works

**Expected behavior**
Both initialSort and updateColumnDefinition works

**Desktop :**
 - OS: Linux RedHat
 - Browser: Chrome and Firefox
 - Version: Chrome: 121.0.6167.185 (Build officiel) (64 bits)  / Firefox: 115.7.0esr (64 bits)

**Comment by olifolkerd** [comment]
That is because the table hasnt finished bein built before you call those functions, define that in the `tableBuilt` event and it should work fine.

Cheers

Oli :)

**Comment by jawher-tabessi** [comment]
Thank you @olifolkerd for your reply
I tried with tableBuilt but have same issue: https://jsfiddle.net/5uzqgmop/
Do you have a working example please ?
