### ISSUE TITLE
Nested Table Data Export into PDF,XLSX etc.

### ISSUE THREAD

**Issue by spbert29** [olifolkerd/tabulator#4408]
It would be nice if it is able to Export Nested Tables, nested tree data into Export Files - its not possible ATM as far as i have seen here:

https://github.com/olifolkerd/tabulator/issues/3853

**Comment by olifolkerd** [comment]
Hey,

Thanks for your feedback

It isn't possible at the moment, nor do most output formats support that as an option which is why it isn't available

For that reason I don't plan on adding that feature to the system.

Cheers

Oli
