### ISSUE TITLE
Editor-list

### ISSUE THREAD

**Issue by sydesb** [olifolkerd/tabulator#4412]
**Website Page**
[https://tabulator.info/docs/5.6/edit#editor-list](https://tabulator.info/docs/5.6/edit#editor-list)

**Describe the issue**
In the first big sample :
`  values:["red", "green", "blue", "orange"],`
and not `  values:["red", "green", "blue", orange],`

`itemFormatter:function(label, value, item, element)`
and not  `itemFormatter:(label, value, item, element)`

`return "<strong>" + label + " </strong><br/><div>" + item.subtitle + "</div>";` 
and not `return "<strong>" + label + " </strong><br/><div>" + item.subtitle + "</div>" : "");`
or condition? is missing.

`   sort:"asc", //sort direction for the values list`
and not `   sort:"asc", sort direction for the values list`

`maxWidth:true,// prevent width of list item from exceeding width of cell`
and not `maxWidth:true, prevent width of list item from exceeding width of cell`

`    placeholderLoading:"Loading List...",// set custom placeholder when loading list values
    placeholderEmpty:"No Results Found",// set custom placeholder when list is empty`
and not `    placeholderLoading:"Loading List...", set custom placeholder when loading list values
    placeholderEmpty:"No Results Found", set custom placeholder when list is empty`

Little mistakes in the code :
**Values - Lookup From Column for the three samples } and not ) at the end**
`{title:"Name", field:"name", editor:"list", editorParams:{
    valuesLookup:"active",  //lookup filtered unique values in this column
}}`
Same problem with  **Values - Remote Ajax Source**,  **Formatting List**, **Sorting List** and **Filtering List**

Thank you very much for your wonderful tabulator.js !!

**Comment by olifolkerd** [comment]
Hey @sydesb 

Thanks for the detailed feedback there, i have made those amendments in the site docs and will deploy them to the live site with the 6.0 release in a few days.

Cheers

Oli :)
