### ISSUE TITLE
Tree Structure has a reference to rowClick option

### ISSUE THREAD

**Issue by Sicklou** [olifolkerd/tabulator#4416]
**Website Page**
[Tree Structure and Nested Data #Component](https://tabulator.info/docs/5.6/tree#component)

**Describe the issue**
The documentation makes a reference to a `rowClick` table option that doesn't seem to exist anymore.
It leads into an incomprehension.

**Comment by olifolkerd** [comment]
Hey @Sicklou 

Thanks for the headsup, i will get this fixed with the 6.0 updates later today.

Cheers

Oli :)
