### ISSUE TITLE
SvelteKit app crashes due to Tabulator performance issue

### ISSUE THREAD

**Issue by nanyx95** [olifolkerd/tabulator#4418]
**Describe the bug**
I've noticed a performance issue in Tabulator that leads to unresponsiveness or crashes in a SvelteKit app, particularly when using the `setData` function. I've also attempted to resolve it by using the `replaceData` function, but the issue persists.

**Tabulator Info**
- 5.6.1

**Working Example**
https://www.sveltelab.dev/1sosnk3zrcdhpzp

**To Reproduce**
1. Go to Page A.
2. Switch to Page B.
3. Repeat steps 1-2 multiple times until the app crashes.

**Expected behavior**
The app should not crash.

**Screenshots**
<img width="1014" alt="tabulator performance issue" src="https://github.com/olifolkerd/tabulator/assets/24499799/adc8487f-6d45-4f55-bb75-cc422ea1c4bf">

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 122

**Comment by olifolkerd** [comment]
Hey @nanyx95 

This is because Tabulators `reactiveData` functionality is fighting against the svelt reactive data functionality.

It is not recommended that you use them both at the same time. If  you disabled `reactiveData1 on the table, it will work as expected.

Cheers

Oli :)
