### ISSUE TITLE
updateRow bug

### ISSUE THREAD

**Issue by maximp68** [olifolkerd/tabulator#442]
Hi, great job, the component I always dreamed of !!

I found a bug in tabulator.js row 4872 (actual unencoded file):

row = this.rowManager.findRow(index);

should be:

var row = this.rowManager.findRow(index);

Hope this helps.

Massimo.

**Comment by olifolkerd** [comment]
Hey Massimo,

Thanks for the kind words, it is always great to hear that Tabulator is appreciated!

and Great spot on that bug, i have pushed an update to the 3.2 branch which will be released later in the month!

feel free to submit pull requests with any fixes you find for stuff like that

let me know if you have any other feedback.

Cheers

Oli
