### ISSUE TITLE
Wrong reference to changed API

### ISSUE THREAD

**Issue by mike-lischke** [olifolkerd/tabulator#4423]
**Website Page**
https://tabulator.info/docs/5.6/release

**Describe the issue**
The release nodes mentioned changed APIs and one makes a wrong reference (`selectablePersistence`):

![Bildschirmfoto 2024-03-04 um 15 33 11](https://github.com/olifolkerd/tabulator/assets/2398704/079eb2e9-640c-46e7-8389-f87747624d85)

That should be `selectableRangeMode` as mentioned in the code block.

**Comment by olifolkerd** [comment]
Hey @mike-lischke 

Thanks for the headsup, I wlll get a fix out for that today.

Cheers

Oli :)
