### ISSUE TITLE
v3.0 custom formatter columns do not get restored when persistent column layout is ON

### ISSUE THREAD

**Issue by gandalf516** [olifolkerd/tabulator#443]
Hi,
when I activate persistent column layout in v3.0, columns with custom formatters do not get restored properly. The built-in one "rownum" works fine.

Gandalf

**Comment by olifolkerd** [comment]
Hey Gandalf,

formatters are not stored in the persistent column layout so im not sure i follow, only column position, width and visibility are persistent.

Could you give an example of what you mean by not restored properly?

do you have an example of a constructor object for a table you are having issues with, i would be happy to take a look at it for you.

Cheers

Oli

**Comment by gandalf516** [comment]
Hello Oli,
I mean when I activated the persistent column, then upon refreshing the page, tabulator table columns that contains custom formatters, did not show at all. As soon as I removed persistent layout settings, they showed up again, so I assumed it is due to the persistent layout.
Hope this helps you to reproduce the issue.

Gandalf

**Comment by olifolkerd** [comment]
Hey Gandalf,

if you change the column setup in your code with persistent columns enabled you will need to change the ***persistentLayoutID*** to ensure they columns are updated correctly.

If you are still running into issue after that, could you post a copy of your tabulator constructor object so i can run some tests against your setup to see where the issue may lie.

Cheers

Oli

**Comment by gandalf516** [comment]
Thanks for the hint, Oli, will give it a try and if the issue still persists, will post my table's constructor.

Cheers

Gandalf

**Comment by gandalf516** [comment]
That was not it, still the columns having custom formatters are not shown upon page refresh. The code is something along these lines:

```
function getEditLink(cell, formatterParams){            
      var row = cell.getRow();
      var itemId = cell.getRow().getData().ID;                                     
      return "<a href='URL?ID=" + itemId +'>Edit</a>";               
};

function getDeleteLink(cell, formatterParams){
   var row = cell.getRow();
   var itemId = cell.getRow().getData().ID;
   return "<a>Delete</a>";
};

function onDeleteClick(e, cell){
   console.log("delete link clicked");      
   var row = cell.getRow();
   var itemId = cell.getRow().getData().ID;                  
   //deleteItem(itemId);
}

$('#tabdata').tabulator({
   //this breaks the custom formatter columns display - columns with edit/delete links below
   persistentLayout: true,
   persistentLayoutID:"tabDataLayout",            
   height:"500px",
   pagination:"local",
   paginationSize:20,            
   placeholder:"No data",
   columns:[
           {formatter:"rownum", sorter:"number", align:"center"},                               
           {title:"ID", field:"ID", sorter:"number", width:75, align:"center"},
           {title:"Number", field:"number", sorter:"string", width:100, headerFilter:"input"},                                                  
           // row links
           {formatter:getEditLink, width:50, align:"center"},
           {formatter:getDeleteLink, width:50, align:"center", cellClick:onDeleteClick}
       ],                         
   selectable:1                                    
});
```

The last 2 columns with Edit/Delete links are not shown while persistentLayout: true setting is used.

**Comment by olifolkerd** [comment]
The issue you are probably having is that you have changed the formatter (or other column definition data) assigned to a column at some point during your development, if you alter the column definition while ***persistentLayout*** is enabled you need to either clear the cookie or change the ***persistentLayoutID*** value to prevent the table from loading cached column layout information that is no longer valid.
