### ISSUE TITLE
Tabulator with column grouping does not render properly

### ISSUE THREAD

**Issue by leo-bogastry** [olifolkerd/tabulator#4430]
**Describe the bug**
I have a table that contains 4 columns, 3 of which are grouped under another header. The html table renders well, but when I define a Tabulator to render on top of it, it adds extra columns and the data now not appear in the correct columns.

**Tabulator Info**
5.6.1

**Working Example**
https://jsfiddle.net/nofuL01y/15/

**To Reproduce**
The jsFiddle contains some html and some js code.
1. If you comment the js code you will see this table:
<img width="200" alt="just_html" src="https://github.com/olifolkerd/tabulator/assets/20278579/72718edf-2abe-43bc-80bd-52f9488a9778">

2. If you uncomment the js it renders a tabulator table that contains extra columns and misaligned data. The data for the second column does not show up:
<img width="846" alt="with_tabulator" src="https://github.com/olifolkerd/tabulator/assets/20278579/af4141e0-3a3e-4dc3-900d-59b6f4b0f650">

**Expected behavior**
The table generated by the tabulator should have the same structure as the html table with 4 columns, where 3 are grouped under the same header, and the same data

**Desktop (please complete the following information):**
OS: [iOS]
Browser [Chrome]
Version [122.0.6261.112 ]

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

Please let me know if the HTML should be done differently for this to work. In my use case I DO NOT use the `data` field available in the tabulator to load the data. It loads it from the HTML.
Thanks in advance

**Comment by olifolkerd** [comment]
Hey @leo-bogastry 

Tabulator only supports loading simple columns from an HTML table. The import from table functionality is only really intended for legacy systems where there used to be no option but to send data to the front end as an HTML table.

If you are building a new system, then i would strongly recommend that you pass your column structure in as a column definition array:
https://tabulator.info/docs/5.6/columns#groups

and pass your data in as a data array:
https://tabulator.info/docs/5.6/data#array-initial

Cheers

Oli :)
