### ISSUE TITLE
selectable not working in v6.0.0

### ISSUE THREAD

**Issue by CourtHive** [olifolkerd/tabulator#4433]
**Describe the bug**
Selectable: true not working in v6.0.0

**Tabulator Info**
- 6.0.0

**Working Example**
JS Fiddle
https://jsfiddle.net/qdhjgsm9/1/

**To Reproduce**
A. attempt to select any row

**Expected behavior**
row should be highlighted

**Comment by CourtHive** [comment]
change the version to 'https://unpkg.com/tabulator-tables@5.6.1/dist/js/tabulator.min.js' in the jsfiddle and it works as expected

**Comment by olifolkerd** [comment]
Hey @CourtHive,

That option was deprecated in 5.6 (you will see console warnings) and removed in 6.0.

The functionality is still there it has just been renamed to `selectableRows`. 

A full guide on the changes was included in the [5.6 Upgrade Guide](https://tabulator.info/docs/5.6/upgrade)

Cheers

Oli :)

**Comment by CourtHive** [comment]
Oil - apologies!  I looked at 6.0.0 upgrade guide and totally missed 5.6 deprecation warning.  Many thanks!
