### ISSUE TITLE
Some  dataTree questions/issues

### ISSUE THREAD

**Issue by schlundus** [olifolkerd/tabulator#4435]
It seems that it's not possible to programmatically select child nodes with datatrees?

I want to select the child row/node by its id but the code seems to look only a the top level rows?
deselect has the same issue...

![image](https://github.com/olifolkerd/tabulator/assets/17083185/2a8ba198-99ea-44cf-bb8f-778ce5e4ef10)

Another question:
*getRows('active')* seems to get only the top-level rows and not its child nodes.... -Is this intended?
If so, how to get the amount of currently active rows of the table including all displayed children?

Best regards and thanks for your time!

**Tabulator Info**
6.0.0

**Comment by olifolkerd** [comment]
Hey @schlundus 

This is correct, the rows deeper in the tree are only virtual they are not represented by data at the top level and so cant be referenced by index.

You can however select them programmatically if you can get their [Row Components](https://tabulator.info/docs/6.0/components)

You will see in that documentation that you can call the 'getTreeChildren' to retrieve the child rows of a parent or 'getTreeParent' to get the parent row of a child.

Cheers

Oli :)
