### ISSUE TITLE
autoColumns dont work with ajaxURL in ver 6.0

### ISSUE THREAD

**Issue by via986** [olifolkerd/tabulator#4437]
**Describe the bug**
When use autoColumns:true setting in my table, and url for ajaxURL, table don't render in version 6.0. In 5.6 it works fine!

**Tabulator Info**
6.0 and 5.6

**Working Example**
web page with simple table:

```
var tbltr = new Tabulator("#table_test", {
    ajaxURL: "/api/table",
    autoColumns:true,
});
```

server send simple json like 
`[{"one":1, "two":2, "three":3}]`

In version 5.6 everything works fine. And in ver 6.0 table don't render and I should type 
`tbltr.setData()`
in browser console to show table.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Firefox, Edge

**Comment by olifolkerd** [comment]
Hey @via986 

Thanks for the headsup, ive pushed a fix to master for this and will do a 6.0.1 patch release shortly.

Cheers

Oli :)
