### ISSUE TITLE
Iterate through each cell

### ISSUE THREAD

**Issue by saurabhgogia** [olifolkerd/tabulator#444]
Hi,

I'm trying to create a validation function that iterates through each cell and runs a different validation method depending on what column it is in. Is there a native way to iterate through each cell? I'm aiming to get an array of all columns, and from that, to get all cell components in that column and iterate through that way.  

I previously created a validation method this way by JavaScript's getElementsByClassName, but since I can't call the Tabulator call backs upon this (can't call .getColumn() ), this is futile. 

Thanks for the help.

**Comment by olifolkerd** [comment]
You can use the ***getColumns*** function to return an array of column components, then use ***getCells*** on the column to get an array of the columns cell components. form there you can do whatever you like with them,  you can use ***getValue*** on the cell components to get their values.

For example:
```js
var cols = $("#example-table").tabulator("getColumns") //get array of column components

cols.forEach(function(col){
    var cells = col.getCells();

    cells.forEach(function(cell){
        customValidationFunction(cell.getValue());
    });
});
```

Let me know if that helps.

What do you intend to do with the results of the validation? do you want to alter the table in some way. is the aim to validate user data as it is entered to the table? if that is the case i can suggest a different approach.

Cheers

Oli

**Comment by saurabhgogia** [comment]
Yes, more or less it will validate user data, but not as they input it manually into the table. The user will be uploading a XLS file, and Tabulator will validate the information before exporting it into a JSON to be later entered into a database.

**Comment by olifolkerd** [comment]
would you like to highlight any validation failures in the table? i could give you an example of a general purpose validation error formatter that you could use with the cells if that would be of help.

**Comment by saurabhgogia** [comment]
Yes, I am thinking about highlighting the invalid cell text red. Sure, I'd be interested to see what you come up with versus me.

**Comment by Paraplegix** [comment]
For displaying the errors you could use [Formatting](http://olifolkerd.github.io/tabulator/docs/#formatting)

You create your own formatter to return the value in a red background if it doesn't pass the corresponding validation.
There is a [example](http://olifolkerd.github.io/tabulator/examples/3.1/#formatters) that make a text apear red if there is an 'o' somewhere in the text.

**Comment by olifolkerd** [comment]
@Paraplegix is bang on there,

There are some good examples of this in action on the examples page of the website.

Cheers

Oli
