### ISSUE TITLE
Tabulator fails to move row

### ISSUE THREAD

**Issue by drypatrick** [olifolkerd/tabulator#4445]
First of all, thanks for this wonderful library, and the detailed and clear documentation provided.

Using Tabulator, I've encountered something that could be a bug, I would like to programmatically move some rows, but the function `table.move()` seams to not work as expected.
The [basic setup in codepen](https://codepen.io/drypatrick/pen/vYMmoKV) shows the unexpected behavior.
When I call `table.move(2, 3, true)`, tabulator seams to be unable to find the rows, and return the following error in the console:

> Move Error - No matching row found: 2

I'm I doing something wrong or is it a bug?

Thanks again, have a nice day.

**Tabulator Info**
- Tabulator 6.0.1

**Working Example**
[Codepen](https://codepen.io/drypatrick/pen/vYMmoKV)

**Expected behavior**
The second row should be moved after the third row

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version 122.0.6261.131

**Comment by drypatrick** [comment]
I've just realized that data needs to have [row index](https://tabulator.info/docs/6.0/data#row-index) to programmatically alter that data.

**Comment by olifolkerd** [comment]
Correct, if you want to call the function like that you will need an index.

You can also pass in row components to that function or call the move function directly on a row component, then you wouldn't need an index

**Comment by olifolkerd** [comment]
If you want to move them by their position without needing an index you could use the getRowFromPosition function

var row = table.getRowFromPosition(5); //return 5th row in the visible table data

Then pass the row components for the row you want to move to and from to move function

**Comment by drypatrick** [comment]
> Correct, if you want to call the function like that you will need an index.
> 
> You can also pass in row components to that function or call the move function directly on a row component, then you wouldn't need an index

I've end up to use `table.moveRow(selectedRow, latestRowMoved, false);`

Thanks for the hint!
