### ISSUE TITLE
padding inserted at top of tabulator table when scrolling down and back up

### ISSUE THREAD

**Issue by carterwe** [olifolkerd/tabulator#445]
I am getting padding, e.g. 37px, inserted at the top of my tabulator table when I scroll down and back up.  The only think unique about my table is that I have three lines in my column headers created by <br/>tags inserted in my title attribute in my column definitions.  Do you have solution or work around?  Thanks, Ed
![tabprb](https://user-images.githubusercontent.com/4616266/28132724-e4410fda-66fa-11e7-8838-3bb194ed836f.png)

**Comment by olifolkerd** [comment]
Are you using version 3.1.5 it contains a patch for that issue
