### ISSUE TITLE
Get Mobile Double Tap to Work

### ISSUE THREAD

**Issue by stack-its** [olifolkerd/tabulator#446]
Hi Oli,

I'm trying to fire in Mobile only when I double-tap.  I have this set for a particular column:

    cellDblClick:function(e, cell) {

        alert('DoubleTap Fired on Mobile');

      //  whatever
    }

What am I doing wrong?  I'm using v3.0  Thanks.

**Comment by olifolkerd** [comment]
Tabulator uses the standard jQuery ***dblClick*** event fot that callback.

Unfortunately that event cannot be triggered by taps, only clicks.

I will look at extending the vent to handle taps for this months 3.2 release.

Thanks for the feedback.

Oli

**Comment by olifolkerd** [comment]
Hey,

You will be happy to hear that Tabulator 3.2 has just been released, and with it full support for touch gestures:
```js
{title:"Name", field:"name", cellDblTap:function(e, cell){
        //e - the tap event object
        //cell - cell component
    },
}
```

Full information can be found in the [Callbacks Documentation](http://olifolkerd.github.io/tabulator/docs/3.2/#callbacks)

Cheers

Oli
