### ISSUE TITLE
row.reformat() Causes Loss of Focus

### ISSUE THREAD

**Issue by stephen-lemp** [olifolkerd/tabulator#4461]
**Describe the bug**
`row.reformat()` causes loss of focus on current cell

**Tabulator Info**
6.2

**Working Example**
https://jsfiddle.net/splemp/0k9Lw2b4/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Select Quantity cell on row 1
2. Enter "2"
3. Hit tab

**Expected behavior**
Focus should remain on the next cell (Committed).

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 123.0.6312.107 (Official Build) (arm64)

**Additional context**
It took a while to figure out why I was losing focus, so if this isn't a bug maybe it could be documented somewhere? I was suspicious for a while that it was due to doing `row.getCell('field').setValue('bar')`, but that wasn't it. I'm hoping to be able to set the value of cells in the `rowFormatter` section, but if that's not supported, that would be nice to know.

**Comment by olifolkerd** [comment]
Hey @stephen-lemp 

It will cause loss of focus, it literally rebuilds the row so the old element will be destroyed so focus cannot be maintained.

Im happy to update the docs to make that cleaerer.

Cheers

Oli :)
