### ISSUE TITLE
Fail to load: "https://unpkg.com/tabulator-tables/dist/js/tabulator.min.js".

### ISSUE THREAD

**Issue by RodrigoPinel-Tower** [olifolkerd/tabulator#4463]
**Describe the bug**
The table doesn't show because it doesn't recognise Tabulator when i create it (const table = new Tabulator...).
Also it appears this message on the browser: 
El recurso de “https://unpkg.com/tabulator-tables/dist/js/tabulator.min.js” fue bloqueado debido a una discordancia del tipo MIME (“text/html”) (X-Content-Type-Options: nosniff).
Last months it wordked perfectly but suddenly it stop working. I didnt touch anything on the program on the last months, and suddenly, it doesnt show the table: <div id="tablaOt"></div>

**Tabulator Info**
6.1

**Working Example**
[YOU MUST include a link to a JS Fiddle or Codepen that demonstrates the problem, it is very hard to diagnose an issue from a simple description.](https://codepen.io/Rodrigo-Pi-el/pen/RwOJBgx)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:

**Expected behavior**
To see the table, but it doesnt't show

**Screenshots**
![imagen](https://github.com/olifolkerd/tabulator/assets/138485232/3fd07f2d-b44d-4679-9f5c-ca2aef7d0561)
![imagen](https://github.com/olifolkerd/tabulator/assets/138485232/ed95ad10-34c5-4276-a932-88ac9bec9a07)

**Desktop (please complete the following information):**
 - OS: WINDOWS 10 (it occurs in all pcs or laptos)
 - Browser: Firefox
 - Version: latest

**Comment by olifolkerd** [comment]
hey @RodrigoPinel-Tower 

It looks like there is an extra quotation month at the end of your URL, if you remove that it all works fine:
https://unpkg.com/tabulator-tables@6.2.0/dist/js/tabulator.min.js

Cheers

Oli :)
