### ISSUE TITLE
Tabulator loses sort state with auto columns after page change

### ISSUE THREAD

**Issue by HenriqueSabino** [olifolkerd/tabulator#4468]
**Describe the bug**
When the tabulator is configured with auto columns, after changing the page, the sort caret no longer represents the current sorting state of the table (running tabulator.getSorters() returns correct column).

**Tabulator Info**
- tabulator 5.5, also tested on most recent version, same problem is reproducible.

**Working Example**

The JsFiddle reproducing the issue https://jsfiddle.net/v02qyorf/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to the JsFiddle provided
2. Click on id column twice so it sorts by descending order
3. Change to page two
4. Id column sort caret is reset to default state

**Expected behavior**
The sort caret of the column should stay the same because the new column loaded has same field name or alternatively there should be a way to set the column sort direction programatically

**Screenshots**
Initial state
![image](https://github.com/olifolkerd/tabulator/assets/22148178/79c4b8ea-661e-4a7b-b8de-fe52b18a3dc6)
Sorted column
![image](https://github.com/olifolkerd/tabulator/assets/22148178/a2e63afc-4e6e-4489-8541-e41dad40c326)
After page change
![image](https://github.com/olifolkerd/tabulator/assets/22148178/ebe9720e-c8f1-451f-86d8-9ad1778ea89c)

**Desktop (please complete the following information):**
 - Windows 11
 - Opera GX, Edge
 - Opera GC LVL5 (core: 107.0.5045.89), Edge 123.0.2420.97

**Comment by olifolkerd** [comment]
You can't use auto columns with remote paginated data, it will reset the column layout on every page load breaking the sort

**Comment by HenriqueSabino** [comment]
Ok. I got a work around for anyone in need

```js
table.on('renderComplete', () => 
{
    let columns = table.getColumns();
    for (let column of columns) {
  
    var sorters = table.getSorters();
    const columnField = column.getField();
    var sortingColumn = sorters.find(x => x.field === columnField);
    
    console.log(sortingColumn)
    
    if (sortingColumn) {
    	const dir = sortingColumn.dir === 'asc' ? 'ascending' : 'descending' ;
      column.getElement().setAttribute('aria-sort', dir)
    }
  }
})
```
