### ISSUE TITLE
Issue with persistentLayout:true

### ISSUE THREAD

**Issue by azizur-rahman** [olifolkerd/tabulator#447]
When I set persistentLayout: true or local or cookie (any of them) next showing the following error.
**TypeError: self.table is undefined** 

Can you give me a solution of it with its sample code? 
Basically, I need your help.

Cheers

**Comment by olifolkerd** [comment]
Hey,

Which version of tabulator are you using? could you post a copy of your table constructor object so i can test against it.

Cheers

Oli

**Comment by azizur-rahman** [comment]
Hi,
I've used the following version of Tabulator

> https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.1.5/css/tabulator.min.css
> https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.1.5/js/tabulator.min.js

 
Please check it and reply me. I hope that I will get the proper solution.

Cheers

**Comment by azizur-rahman** [comment]
Hey,
I need your reply that is very necessary for me.

Cheers

**Comment by olifolkerd** [comment]
when you get the error in your console log, does it tell you which line the error is comming from?

**Comment by olifolkerd** [comment]
The issue you are probably having is that you have changed the formatter (or other column definition data) assigned to a column at some point during your development, if you alter the column definition while ***persistentLayout*** is enabled you need to either clear the cookie or change the ***persistentLayoutID*** value to prevent the table from loading cached column layout information that is no longer valid.
