### ISSUE TITLE
Missing event.touches when resizableColumnGuide is set to true and Chrome  Dev-Tools are used 

### ISSUE THREAD

**Issue by schlundus** [olifolkerd/tabulator#4470]
**Describe the bug**
When *resizableColumnGuide* is set to *true*, then  the following error appears when resizing a column while 
the chrome dev-Tools are open and the device is set to "Ipad Air"  (happens also with  Surface duo) ... no idea if this also happens with a real device..

![image](https://github.com/olifolkerd/tabulator/assets/17083185/c1704f2b-2c47-41bb-8894-9e0640fa94ce)

**Tabulator Info**
- Which version of Tabulator are you using?
6.2.0
Chrome 123.0.6312.123

**Comment by olifolkerd** [comment]
Hey @schlundus 

Please follow the bug issue template, without an example setup of the issue to help us replicate it we are unable to offer a fix.

Cheers

Oli

**Comment by schlundus** [comment]
Happens only when using 
 resizableColumnGuide: true

no error when using
 resizableColumnGuide: false
