### ISSUE TITLE
persistence of scroll position

### ISSUE THREAD

**Issue by Hoogkamer** [olifolkerd/tabulator#4472]
When I leave the table and then return to it, I would like to have the same scroll position as when I left it, so I can easier find back where I left off. And maybe even also save the row/cell I have the cursor in.
It would be nice if this is build into the persistence functions.

What have I tried: 
I saved it myself now with this code.
In my data I have a field for the row number and id
```javascript
function saveScrollPosition() {
 const { rownr, id } = table.getRows('visible')[0].getData()
 cytoStore.tabulatorPersistence.Custom[tabletype].scrollPosition = { rownr, id }
}

function setScrollPosition(rownr, id) {
 const rows = table.searchRows('id', '=', id)
 let row
    if (!rows.length) {
      row=table.searchRows('rowwnr', '=', rownr)[0]
    } else {
      row=rows[0]
    }
  table.scrollToRow(topRow, 'top', true)
}
```

**Comment by olifolkerd** [comment]
It will do, the only way the scroll position will change is if you have rebuilt the component or changed the data. There is no reason for the scroll to change on a visibility toggle

**Comment by olifolkerd** [comment]
I think that is a bit of a niche edge case and not something that would be used day to day, so I wouldn't be looking to add it to the library.

But It looks like you have a solution that works for your use case so all good there
