### ISSUE TITLE
Event Target Lookup Error during cellMouseEnter event

### ISSUE THREAD

**Issue by riccarpin** [olifolkerd/tabulator#4477]
Goodmorning, I'm working with tabulator 6.2.

I created a table and I inserted the the event of "cellMouseEnter" but every time the event is generated, I have the following string error on the console log:

_Event Target Lookup Error - The row this cell is attached to cannot be found, has the table been reinitialized without being destroyed first?_

Event:
![image](https://github.com/olifolkerd/tabulator/assets/167760449/71acfabf-8388-451d-85bd-0c341b74d6d7)

Error message:
![image](https://github.com/olifolkerd/tabulator/assets/167760449/1e470939-3b4a-43b6-88ee-6de53afd55c2)

Could you help me, please?
Thanks for your kindly collaboration

**Comment by olifolkerd** [comment]
Hey @riccarpin 

This error usually occurs when a table has been rebuilt on the same element as a previous table, if you are using a reactive framework to instantiate your table, id suggest adding a console log just before your table instantiation and you will see it is occurring multiple times.

You either need to instantiate only once, or call the `destroy` function on the existing table before you instantiate a new one.

Cheers

Oli :)

**Comment by riccarpin** [comment]
Hi Oli,
you're right. The table was created two times.
Resolve the issue about the table creation the "_Event Target Lookup Error_" is disapear.

Thanks for the help.
Bye
Riccardo
