### ISSUE TITLE
GroupBy for a table created from Html Table

### ISSUE THREAD

**Issue by amit-ix** [olifolkerd/tabulator#448]
Hi,
I created a Tabulator table for an existing Html Table. I want to group by the rows by one of the columns of existing Html Table. It groups the column with group title as "undefined" and all rows are added to that group. Also the grouping doesn't happen on actual valued under that column.

I tried...
1. tabulator-groupBy:"columnName" on <table> node
2. tabulator-groupBy:"true" on <th> node
3. In javascript start function, added groupBy:"column header text"

Please guide me on how to use groupBy for Html table.

Thanks,
Amit

**Comment by olifolkerd** [comment]
Hey,

Thanks for getting in touch,

Could you post a copy of your current tabulator constructor object so i can give you an example of what to do, relevant to your scendarion

Cheers

Oli

**Comment by amit-ix** [comment]
Hey Oli,
You are simply awesome! I have become big fan of Tabulator control...

Here I am giving few code snippets which I tried...
1. 
```
<script type="text/javascript">
        $(document).ready(function () {
            $('#testTable').tabulator({
                groupBy: "userName",
                columns: [
                    {title:"User Name", field:"userName"}
                ]
            });
        });
</script>
```

2. 
```
<script type="text/javascript">
        $(document).ready(function () {
            $('#testTable').tabulator({
                groupBy: "User Name"
            });
        });
</script> 
```
3. 
```
<table id="testTable" class="very compact" tabulator-groupBy="User Name">
    <thead>
        <tr>
            <th tabulator-formatter="html" tabulator-headerFilter="true">
                User Name
            </th>
```

I am seeing the UI like below image
![image](https://user-images.githubusercontent.com/30158076/28183151-06b12fbe-682c-11e7-86d4-27755cd293e5.png)

**Comment by olifolkerd** [comment]
Hey,

Thanks for the kind words :) it is great to hear that Tabulator is appreciated :D :D :D 

So there are a couple of issues there, the first is your header text is on a different line to the tags which is causing tabulator to try and parse the carriage returns into the field name (this is definitely a Tabulator bug, that i will fix for version 3.2) in the mean time this can be fixed by making sure your header text is in the same line as the tags:
```html
<th>User Name</th>
```
The second is that you want to be using ***user_name*** as the field name for the group by:
```js
groupBy:"user_name",
```

Let me know if that helps.

Cheers

Oli

**Comment by olifolkerd** [comment]
Just to let you know i have made a commit to the 3.2 branch to remove caridge returns in header titles when imported from a table.

The will be officially released in a few weeks time.

**Comment by amit-ix** [comment]
Great!
Saw your other reply about fixes for newline issue. Appreciate your quivk turn around!

Just a small question, is it yoyr default handling to treat space in header text as '_'? Also are these field names are always expected to be in small cases?

For example: "User Name" as user_name, "Total Amount" as total_amount?  
Thanks,
Amit

---- On Fri, 14 Jul 2017 01:26:04 +0530 notifications@github.com wrote ----

Hey,

Thanks for the kind words :) it is great to hear that Tabulator is appreciated :D :D :D

So there are a couple of issues there, the first is your header text is on a different line to the tags which is causing tabulator to try and parse the carriage returns into the field name (this is definitely a Tabulator bug, that i will fix for version 3.2) in the mean time this can be fixed by making sure your header text is in the same line as the tags:

<th>User Name</th>
The second is that you want to be using user_name as the field name for the group by:

groupBy:"user_name",
Let me know if that helps.

Cheers

Oli

**Comment by olifolkerd** [comment]
In general you can name your fields whatever you like in whatever case you like,

It is only when Tabulator is importing HTML tables that it converts names to camel case if no column definition has been set. The reason for doing this is most people will use camel case as the naming convention for database keys and if these are direct transformed into a json object then that is how they will appear in the table data. and based on the assumption that 99% no one will have a dataset with keys with spaces in.

I can your point that this is not always the case, and some flexibility in this reguard may be useful, so i will ad an enhancement to the 3.2 branch to allow for specifying a ***tabulator-field*** attribute in the column header tag to allow you to force the field name in the HTML.

**Comment by olifolkerd** [comment]
I have just added this functionality to the 3.2 branch,

You will now be able to force the column field to a specific value but setting the ***tabulator-field*** attribute in the column header element:

```html
<th tabulator-field="userName">User Name</th>
```

**Comment by amit-ix** [comment]
Superb!
I will be waiting for upgrade to 3.2, Thanks much again!

**Comment by olifolkerd** [comment]
You are welcome,

If you want to start using the tweaks now feel free to download the 3.2 branch yourself:
https://github.com/olifolkerd/tabulator/tree/3.2

Cheers

Oli
