### ISSUE TITLE
doc - fix typo in Vue 3 setup paragraph

### ISSUE THREAD

**Issue by senerh** [olifolkerd/tabulator#4487]
**Website Page**
https://tabulator.info/docs/6.2/frameworks#vue3

**Describe the issue**
:x: you can ~~inport~~ the library to your project
:heavy_check_mark: you can **import** the library to your project

**Comment by olifolkerd** [comment]
Hey @senerh 

Thanks for the headsup, i will fix that in todays patch release website update.

Cheers

Oli :)
