### ISSUE TITLE
No way to set a pagination counter when a custom pagination element is in use

### ISSUE THREAD

**Issue by jonatanschroeder** [olifolkerd/tabulator#4488]
**Describe the bug**

When `paginationElement` is set, `paginationCounter` is not set, even if a `paginationCounterElement` is used. There is no mention in the docs about any incompatibility in this regard.

**Tabulator Info**
- Which version of Tabulator are you using?
  - 6.2

**Working Example**
YOU MUST include a link to a JS Fiddle or Codepen that demonstrates the problem, it is very hard to diagnose an issue from a simple description.

https://jsfiddle.net/6mvt4juz/2/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Set `paginationElement` to any element outside of the table.
2. Set `paginationCounter` to either a function or a built-in counter (e.g., `'rows'`).
3. Set `paginationCounterElement` to any element outside of the table.

Note that there is no counter in place anywhere.

**Expected behavior**
The counter should be listed in the custom element specified in `paginationCounterElement`.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser [e.g. chrome, safari]: Edge
 - Version [e.g. 22]: 124.0.2478.51

It seems this is set in https://github.com/olifolkerd/tabulator/blob/7333c33730288f7f192943ebc3ed396b2e576fb8/src/js/modules/Page/Page.js#L432-L433 but there is no indication or comment about why this is the case.

**Comment by olifolkerd** [comment]
Hey @jonatanschroeder 

That is because the pagination counter is not appended to the pagination element.

The pagination element is just the buttons on the right hand side of the footer, the pagination counter is loaded into the left hand side of the footer. so what you need to be setting is the `footerElement`.

An updated JS Fiddle can be found here:
https://jsfiddle.net/6mvt4juz/2/

Cheers

Oli :)

**Comment by jonatanschroeder** [comment]
Hi, @olifolkerd,

The JS fiddle you linked is the same that I sent, so I can't see the changes you have done, can you please update it?

**Comment by Panbou** [comment]
Hello, I have exactly the same problem. In your message @olifolkerd, you mentioned the use `footerElement`, the problem with this is that it seems to move the defined `footerElement` in the `.tabulator `, this isn't really convenient to style the table.
Maybe my use of Tabulator isn't quite right, I've been using it for a week only, wonderful library 😍

But, if anyone is struggling with the same (edge) case, here is a little workaround I applied in my project :

```js
...in the table config

paginationCounter:function(pageSize, currentRow, currentPage, totalRows, totalPages){
    let rowEnd: number = currentRow + pageSize - 1;
    // So we dispatch an event to update the counter manually in the "renderComplete" event
    const event = new CustomEvent("paginationCounterUpdate", {
        detail: { currentRow, rowEnd, totalRows },
    });
    document.dispatchEvent(event);
    return `${currentRow} - ${rowEnd} / ${totalRows}`; // This isn't displayed anywhere due to the bug
},
paginationElement: "#myCustomPaginationElement", // My pagination element, it happens to contain "#myCustomPaginationCounter"
```

And then, I listen to my custom event : 
```js
// Listen to event paginationCounterUpdate
document.addEventListener("paginationCounterUpdate", function(event: CustomEvent) {
    const { currentRow, rowEnd, totalRows } = event.detail;
    document.getElementById("myCustomPaginationCounter").innerText = `${currentRow} - ${rowEnd} / ${totalRows}`;
});
```

**Comment by ilmari-lauhakangas** [comment]
You indeed can't mix paginationElement with footerElement, it is ignored. Here is a working edit of the fiddle: https://jsfiddle.net/2gsh09dz/

One issue is that we can't control the order of the counter vs. the pagination navigation element. The nav will always be inserted after the counter.
