### ISSUE TITLE
Load data from HTML which contains attributes `rowspan=1` and `colspan=1`

### ISSUE THREAD

**Issue by Spixmaster** [olifolkerd/tabulator#4495]
*Is your feature request related to a problem? Please describe.**
I have an HTML with `rowspan=1` and `colspan=1`.

**Describe the solution you'd like**
Following https://tabulator.info/docs/6.2/data#table, an error occurs as these attributes are present as stated in the note.

**Describe alternatives you've considered**
Since `rowspan=1` and `colspan=1` are the default anyway, this should be accepted without issue.

**Comment by olifolkerd** [comment]
As per the docs, tabulator does not process colspan or rowspan tables.

If your table is only single rows and columns it has no need for these options either.

In this case Tabulator is operating as anticipated so I'm not looking to make a change here

Chee lrs

Oli
