### ISSUE TITLE
Filter data by its formatted value

### ISSUE THREAD

**Issue by demetriomontalto** [olifolkerd/tabulator#4496]
**Is your feature request related to a problem? Please describe.**
Currently Tabulator uses raw cell values to filter data, I need to filter data by its formatted value instead.

**Describe the solution you'd like**
While default behaviour of simple filters will stay up to you, it might be good to have an additional parameters, such as `formattedValue`, on 'custom filters and/or header filters' callback functions.

**Describe alternatives you've considered**
1. Mutators are not an option as the underlying data **must not** change.
2. Using a 'label' field and filter by that is not an option for the same reason above, original data is to be taken **as is**.
3. The following example uses a function to pre-format values that results in a duplicated logic which I don't really like and can also be resource consuming, it would be better to have access to a stored value inside Tabulator. 
```js
const getPageName = (value) => {
    // very complex and possibly resource consuming logic
    const url = new URL(value);
    return `${url.hostname} homepage`;
};

new Tabulator('#tabulator', {
    data: [
        { id: 1, url: 'https://youtube.com/' },
        { id: 2, url: 'https://google.com/' },
    ],
    columns: [
        {
            title: 'URL',
            field: 'url',
            headerFilter: 'input',
            headerFilterPlaceholder:"Filter by page name...",
            headerFilterFunc: (headerValue, rowValue, rowData, filterParams) =>
                // here I would like not to call this expensive function
                getPageName(rowValue).includes(headerValue),
            formatter: (cell, formatterParams, onRendered) =>
                `<a href="${cell.getValue()}" target="_blank">${getPageName(cell.getValue())}</a>`,
        },
    ],
});
```

**Comment by olifolkerd** [comment]
Formatters are purely visual. You couldn't meaningfully filter by a pie chart or progress bar.

If you want your underlying data to be filtered you should either use a mutator to alter it as it comes into the table or a custom filter function
