### ISSUE TITLE
Support of 'value' argument in addFilter for custom filters

### ISSUE THREAD

**Issue by alainpannetier** [olifolkerd/tabulator#450]
Proposal:
In source filter.js at line 209 (master) the addition of the line below would allow passing parameters to custom filters (accessible through this.param - or this.value supposing filter.value = ...).

```javascript
    if(filterFunc){
      filter.func = filterFunc;
      filter.param = filter.value;    // <==== also support passing value to filter
      self.filterList.push(filter);

      self.changed = true;
    }

```

**Comment by olifolkerd** [comment]
Hey,

Could you give me a usage case for this scenario, so i have a bit of context around why this feature is needed. What is the purpose of the additional information you want to pass in, is it from row or column data, is it only set at the point you call the setData function, so should it be passed through at that point, is it defined per columns etc....

As all custom filter functions are defined outside of tabulator could you not just include the variable at the same level you declare the filter and reference it when needed?

I would be potentially be interested in this as a feature, but I would not implement it by passing adding any parameters to the ***this*** object, as that would be inconsistent with the way that any other callbacks work. all data mast be passed into a callback through its arguments.

Let me know your usage case and i can have a look intp the best way to add the needed functionality

Thanks for your suggestion, keep them comming

Cheers

Oli

**Comment by alainpannetier** [comment]
Hi Oli, thanks for your fast answer. Here is more context info.

When custom filters are invoked by tabulator (filter.js l#327)

```javascript
  self.filterList.forEach(function(filter){
    if(!filter.func(data)){   // here func is invoked in the context of filter.
      match = false;
    }
  });
```
it would be great to have access to some parameter (i.e. equivalent to the `value` argument in regular field filters) because the custom filtering criterion is run time dependent.
In my particular case, the filter criterion in only some part of the data in the field and the extraction of that selection criterion from that field value is a custom logic. I'm only interested in rows where part of the value of that field satisfies some condition that is selected by the user.
I used to simply rely on closures. But now I have several instances of a class wrapping tabulator and it is cleaner to pass information through args or members.
In addition, the filters are triggered through buttons and the context of the button is the button DOM object (as per jquery event handler). But here I pass arguments to the jquery event handler through usual `event.data.myparam` mechanism. So no issue.
I'm perfectly ok with an additional argument though.

**Comment by olifolkerd** [comment]
Sounds sensible,

so in that case i would look at doing it like this:

```js
//define custom filter
function customFilter(data, filterParams){
    //data - the data for the row being filtered
    //filterParams = aditional filter params
    return data.name == "bob" && data.height < 3; //must return a boolean, true if it passes the filter.
}

//use filter at later point in time, pass custom prams into final argument
$("#example-table").tabulator("setFilter", customFilter, {someParam:true, anotherParam:false});
```

How does that work for you?

**Comment by alainpannetier** [comment]
Yes Oli. Absolutely perfect. Thanks.

**Comment by alainpannetier** [comment]
Sorry. A word of warning though if you go ahead:
As I had implemented my idea locally (highjacking the value filter member). This actually breaks the 'removeFilter' method because

```javascript
            return filter.field === element.field && filter.type === element.type && filter.value === element.value;
```
is returning false on the last test on value.

So I' rolling back my 'enhancement` for now.

**Comment by olifolkerd** [comment]
Hey,

You will be happy to hear that Tabulator 3.2 has just been released, and with it parameters for custom filter functions:

```js
function customFilter(data, filterParams){
    //data - the data for the row being filtered
    //filterParams - params object passed to the filter

    return data.name == "bob" && data.height < filterParams.height; //must return a boolean, true if it passes the filter.
}

$("#example-table").tabulator("setFilter", customFilter, {height:3});
```

Full information can be found in the [FilteringDocumentation](http://olifolkerd.github.io/tabulator/docs/3.2/#filtering)

Cheers

Oli

**Comment by alainpannetier** [comment]
Thanks oli, I'll try it today...
