### ISSUE TITLE
Typo: or or

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#4501]
**Website Page**
https://tabulator.info/docs/6.2/release

>The new toggle formatter displays as a toggle switch that shows itself as either or or off depending on value.

**Describe the issue**
![image](https://github.com/olifolkerd/tabulator/assets/799021/56a82b39-4c45-4665-a613-4936e42add02)

**Comment by olifolkerd** [comment]
Hey @KES777 

Thanks for the headsup,  i will include a fix for that typo with todays patch release site update.

Cheers

Oli :)
