### ISSUE TITLE
Ability to choose headerFilterFunc from user input

### ISSUE THREAD

**Issue by md-redwan-hossain** [olifolkerd/tabulator#4507]
**Describe the solution you'd like**
Currently, I can specify a [built-in filters](https://tabulator.info/docs/6.2/filter#func-builtin) in the `headerFilterFunc` like `headerFilterFunc: ">="` for a column but it seems like this approach does not allow to harness the full power of Tabulator. I want to choose available [built-in filters](https://tabulator.info/docs/6.2/filter#func-builtin) from an html option and pass it to the backend via ajax. A very nice demo is here: [primeng table](https://primeng.org/table#filter-basic)
Is this possible?

**Comment by olifolkerd** [comment]
Hey @md-redwan-hossain 

You could already do this using a custom filter function that references some external user choice and then applies the appropriate filter logic.

Cheers

Oli :)
