### ISSUE TITLE
tabulator("clearSort") question

### ISSUE THREAD

**Issue by MikhailKlemin** [olifolkerd/tabulator#451]
Hi! 
I have these two functions on buttons:
Export one, works fine: 
`<button type="button" id="#download-csv" class="btn btn-default" onclick='$("#example-table").tabulator("download", "csv", "data.csv");'>Export</button>
`

But clearSort bellow seems like does nothing or I misunderstand it's purpose:
`<button type="button" id="#unsort-btn" class="btn btn-default" onclick='$("#example-table").tabulator("clearSort")'>Unsort</button>
`
I assume that it should revert sorting from everything user have sorted by clicking on the headers? Am I correct, or it does something different? 

I use 3.1.5

**Comment by olifolkerd** [comment]
Hey,

At the moment the ***clearSort*** removes all existing sorters, which will clear the sort arrows from the header, but as their is no "default" state of the data it will not change the sort order.

Thinking about it i could make this default back to the ***initialSort*** if it is defined, but if it is not there is no way to restore it back to the original data loaded state as the system has now reference for what this should be.

What do you think the action should do in your scenario?

Cheers

Oli

**Comment by answerquest** [comment]
Hi @olifolkerd even I had assumed clearSort would "reset" the table to the original order of rows. Good to know that's not what it's for (I'll advise creating another function for that), but even the intended functionality isn't happening on my end. : After executing this command: `$("#stops-table").tabulator("clearSort");` the sortable columns remain sortable. v3.4.4.
