### ISSUE TITLE
table.download downloads all data not just current pagination page

### ISSUE THREAD

**Issue by Calabashmc** [olifolkerd/tabulator#4512]
I use remote pagination. I would like to download the complete dataset as csv but using table.download only downloads the rows of the current displaed page. I'm using flask-sqlalchemy for the paginated data. Is it possible to be able to download the entire paginated data set (page 1 to last page in table)?

**Comment by olifolkerd** [comment]
This is not possible. With remote pagination the table only holds the current page worth of data, the rest remains on the server so is unavailable for the table to use
