### ISSUE TITLE
Bootstrap / Popper tooltips with Bootstrap theme

### ISSUE THREAD

**Issue by jakubkrolikowski** [olifolkerd/tabulator#4513]
*Is your feature request related to a problem? Please describe.**

I use the Bootstrap library and the Bootstrap 5 theme for Tabulator.
Bootstrap uses the Popper library to display nice tooltips.
https://getbootstrap.com/docs/5.3/components/tooltips/#overview
For Tabulator I use this settings:
```
columnDefaults : {
     headerTooltip:true
 }
```
and I'd like the tooltips on the header to look like they do everywhere else in my web [age, i.e. like in Bootstrap.

**Describe the solution you'd like**
It would be great if you could integrate Tabulator with Popper to display tooltips.

**Describe alternatives you've considered**

**Additional context**
My temporary solution (with jQuery):
```
...
columnDefaults : {
     headerTooltip:false
 }
..
     
table.on("tableBuilt", function(){
      $(tableElement).find(".tabulator-col[role=columnheader").each(function(ind,el) {
         new bootstrap.Tooltip(el, {
            trigger: 'hover',
            title: $(el).find(".tabulator-col-title").text(),
            delay: { "show": 500, "hide": 10 }
       });
}); 

```

**Comment by olifolkerd** [comment]
Hey @jakubkrolikowski 

The bootstrap theme is CSS only, it uses its own internal functionality for managing tooltips and popups.

It would bean inefficient use of time to add different sets of dependency for every front end framework it works with, You are of course welcome to tweak the CSS for the exisiting popups on your project if you would prefer.

Cheers

Oli :)

**Comment by jakubkrolikowski** [comment]
Hey @olifolkerd
Sure, I understand, however, Boostrap is not CSS only. Bootstrap is support by some javascript and uses Popper for tooltips, as I mentioned.
Popper is a universal, stable library for tooltips (among others). Popper/Bootstrap tooltips looks much better and are very usefull when a column has a short name and we would like to describe it fully in the tooltip.

**Comment by olifolkerd** [comment]
Yes but the whole point of Tabulator is that it operates without needing to pull in loads of dependencies. You can of course pull in any Library you like.

But my point stands that just because bootstrap uses it does not mean tabulator will. Tabulator only provides CSS themes for other libraries, that is all

Cheers

Oli
