### ISSUE TITLE
sum line get wrong result when sum rows value is 3.3

### ISSUE THREAD

**Issue by saobee** [olifolkerd/tabulator#4515]
**Describe the bug**
javascript add float number bug.
example: ``` 1.1+1.1+1.1 ``` will output 3.3000000000000003

**Tabulator Info**
v 6.2

**Working Example**

(https://jsfiddle.net/o0yp9m7g/3/)

**Screenshots**
![image](https://github.com/olifolkerd/tabulator/assets/4122529/ffa20576-f8a3-4a6c-9a1c-59486e366c53)

**Comment by olifolkerd** [comment]
Hey @saobee 

This isnt a Tabulator issue, just a standard JS floating point math issue if you enter the following into your dev console:
```js
1.1+1.1+1.1
```
You will get exactly the same issue, this is a common problem with floating point maths.

To get round it, Tabulator offers the `precision` option to restrict the number of available decimal places:
```js
{title:"Example", field:"example", bottomCalc:"sum", bottomCalcParams:{
    precision:1,
}}
```

Cheers

Oli :)
