### ISSUE TITLE
Column group -> same row layout?

### ISSUE THREAD

**Issue by sistason** [olifolkerd/tabulator#452]
I did not find a similar question here, so:

When I create a column group like

```
  Name
Age|Color
```

is there a simple way to also have every row be "double sized", with the exact same layout of `data.name<br />data.age | data.color`? Name would here be a field, not (only) the name of the group.
It does not seem to be a feature, right? I could of course reproduce the effect with a rowFormater, but then I would have to rewrite the entire row, having not much of a benefit from tabulator, no resizing, no layouting etc... ;)

**Comment by olifolkerd** [comment]
Hey,

At the moment i am afraid the only way to do this would be to use a custom row formatter as you suggest.

Cheers

Oli
