### ISSUE TITLE
A way to distinguish between bottomCalc row & "normal" rows in rowFormatter

### ISSUE THREAD

**Issue by jakovpucekovic** [olifolkerd/tabulator#4520]
*Is your feature request related to a problem? Please describe.**

I'm having a table with a `bottomCalc` row. I would like to provide a different row formatting for the `bottomCalc` row by using the `rowFormatter` option. Currently the only way to distinguish between the "normal" table rows and the `bottomCalc` row (as far as I can tell) is that the `bottomCalc` row has the css-class `tabulator-calcs`.

**Describe the solution you'd like**

I would like a way to distinguish between `bottomCalc` row and "normal" table rows in the `rowFormatter`. Perhaps the `bottomCalc` row could have a property which says that it's the bottomCalc row (the property could be added to CalcComponent.js).

**Describe alternatives you've considered**

Currently the way is check whether the row is a `bottomCalc` row is 
```
myRowFormatter(row){
    if(row.getElement().classList.contains("tabulator-calcs"))
        return formatCalculationRow(row);
}
```

**Comment by olifolkerd** [comment]
Hey @jakovpucekovic 

You can already do this by checking if the row is an instance of `RowComponent` or `CalcComponent`

Cheers

Oli :)
