### ISSUE TITLE
Custom Editor - HTML Textfield behaviour

### ISSUE THREAD

**Issue by spbert29** [olifolkerd/tabulator#4529]
**Describe the bug**
Hello,

I am not really sure if it is bug or i am doing it wrong - but i think it is a bug, if not - feel free to close(with a small hint please ;) )

As you can see from the jsFiddle, I'm trying to combine Tabulator JS and jquery Flexdatalist - I'm using a custom editor for this. I want to use a search with all the advantages of jquery flexdatalist. (https://projects.sergiodinislopes.pt/flexdatalist/)

To do this, a text field is placed in the cell and the data list is then appended there. 

However, you have to keep the text field (the browser column in the example) active with the mouse to be able to rewrite the value.

As described - I'm not really sure if this is a bug, but I suspect that Tabulator JS does not recognise that there is an HTML element behind it.

**Tabulator Info**
6.2.1

**Working Example**
https://jsfiddle.net/tmjo6xqw/1/

**To Reproduce**
open fiddle - click a value from the browser column and try to type.
hold a value clicked and wit will work

**Expected behavior**
click value and let me type

**Screenshots**
![grafik](https://github.com/olifolkerd/tabulator/assets/42182294/be2f883f-1e89-4827-aad4-37ea6ee323ee)

**Comment by olifolkerd** [comment]
Hey @spbert29 

The issue here is highlighted by the console waning you get when you try and use the editor. you should be retuning the contents of the edtor (it the input, dropdown, whatever) and not the value.

When you have a value you can call the `success` function to pass that to the table.

Cheers

Oli :)
