### ISSUE TITLE
Get rowIndex outside of Tabulator

### ISSUE THREAD

**Issue by stack-its** [olifolkerd/tabulator#453]
I'm trying to get the rowIndex that I know you must store for a row in data.   The row is already targeted outside of Tabulator & thus can't use tabulator's cell, row, etc to get it, i.e.:

Pseudo outside code:  $('targeted row').data('rowIndex');

I'll then be using that found rowIndex to select the row using Tabulator's selectRow function.

**Comment by olifolkerd** [comment]
Hey,

There is nothing stored in the rows data elements any more, because Tabulator now uses a virtual DOM, the rows are created and destroyed as the user scrolls through the table, so they wont always been there for a DOM query.

Could you give me an example of your usage case and how/why your are trying to select the table from outside the table and i can put together a suitable solution for you.

Cheers

Oli

**Comment by stack-its** [comment]
Hi Oli,

Ok, the situation would be in mobile, using long-hold on a custom defined column, which tabulator doesn't support. But, assuming I've targeted a row using long-hold & want to select the row using Tabulator, what can be done?

**Comment by olifolkerd** [comment]
I have had a couple of people asking for touch event bindings in tabulator recently so i am going to include them in next weeks 3.2 release (tap, dblTap and tapHold)

If you need them more urgently let me know and i can suggest a work around i think will work.

Cheers

Oli

**Comment by stack-its** [comment]
Yes, if you could give a temporary way to get the row selected, it would be appreciated, as I am trying to wrap up development for initial release of product.  P.S. I was one asking about double-tap - I think tap-hold is better, as less chance of hitting other row when tapping ;)

**Comment by olifolkerd** [comment]
You can use the ***dataLoaded*** callback to act as a trigger for setting your event bindings. you can then retrieve all the rows components in the table and make event bindings to thier elements.

As a rough example for a tap hold scenario:

```js
$("#example-table").tabulator({
    dataLoaded:function(data){
        var rows = $("#example-table").tabulator("getRows");

        rows.forEach(function(row){
            var tapHold = null;
            var element = row.getElement();

		element.on("touchstart", function(e){
			clearTimeout(tapHold);

			tapHold = setTimeout(function(){
				clearTimeout(tapHold);
				tapHold = null;
				tap = false;
				
                                //DO WHATEVER CUSTOM ACTION YOU NEED HERE
                                //the "row" variable is the component for the row where the tap has occured

			}, 1000)

		});

		element.on("touchend", function(e){
			clearTimeout(tapHold);
			tapHold = null;
		});
        });
    },
});
```

**Comment by stack-its** [comment]
Hi Oli,
Finally got back to this:  I assume the dataLoaded can be placed anywhere in the main attributes definition of tabulator (ie. doesn't have to be before or after something), right?  I placed it before my Columns definition ( would prefer to have this on my custom column, but can live w/ it working on any of the cells in a row)

Anyway, it's throwing an error:   no such method 'getRows' for tabulator widget instance
Is getRows not defined in v3.0?  Could I put this in my custom column and change getRows to getRow & eliminate forEach loop & just use touchstart/touchend stuff ?  Just throwing out rough guesses to get your opinion, as I need this ;)  Thanks.

**Comment by olifolkerd** [comment]
You will need to download the latest version of tabulator, 3.1.5 to use this.

Touch events will be in the 3.2 release this sunday, so if you can hold off till then the behaviour will be available natively.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey,

You will be happy to hear that Tabulator 3.2 has just been released, and with it full support for touch gestures:
```js
{title:"Name", field:"name", cellTap:function(e, cell){
        //e - the tap event object
        //cell - cell component
    },
}
```

Full information can be found in the [Callbacks Documentation](http://olifolkerd.github.io/tabulator/docs/3.2/#callbacks)

Cheers

Oli
