### ISSUE TITLE
Horizontal scroll bars not appearing when required

### ISSUE THREAD

**Issue by starryvistas** [olifolkerd/tabulator#4530]
**Describe the bug**
if you use a table to position 3 tabulator tables side by side then the horizontal scroll bar on each table  will not appear and tabulator tables are not contained within width of parent table 

**Tabulator Info**
- 6.2

**Working Example**
this illustrates the problem   https://codepen.io/Steve-Wells-the-decoder/pen/bGyXqew

**To Reproduce**
 https://codepen.io/Steve-Wells-the-decoder/pen/bGyXqew

**Expected behavior**
three tabulator tables displayed within the defined dimension of the parent table and each table displaying a horizontal scroll bar

**Comment by sthkn** [comment]
I think the issue is the combination of HTML and CSS you're using.
Here is a working example I got going by modifying your example:
https://codepen.io/sthkn/pen/gONYmmY

HTML tables are funky when used for layouts

**Comment by starryvistas** [comment]
Seth, Thank you for that, I have implemented something similar. I came across the issue while updating legacy code to use tabulator. I posted the issue to GitHub in case it is something that you fellas want to resolve
Regards

Yahoo Mail: Search, organise, conquer 
 
  On Thu, 4 Jul 2024 at 16:18, ***@***.***> wrote:   


I think the issue is the combination of HTML and CSS you're using.
Here is a working example I got going by modifying your example:
https://codepen.io/sthkn/pen/gONYmmY

HTML tables are funky when used for layouts

**Comment by olifolkerd** [comment]
Hey @sthkn 

This is an issue with your setup and not the library. Tables should be declared on div elements not td's

td tags are extremely opinionated and come with a whole host of their own CSS. the correct approach would be to put a div inside each td and instantiate your tables on those.

Cheers

Oli :)

**Comment by starryvistas** [comment]
Thanks, for responding 

Yahoo Mail: Search, organise, conquer 
 
  On Sun, 14 Jul 2024 at 14:06, Oli ***@***.***> wrote:   


Hey @sthkn

This is an issue with your setup and not the library. Tables should be declared on div elements not td's

td tags are extremely opinionated and come with a whole host of their own CSS. the correct approach would be to put a div inside each td and instantiate your tables on those.

Cheers

Oli :)
