### ISSUE TITLE
Very impressed, how to you like to be shown gratitude?

### ISSUE THREAD

**Issue by gbcgit** [olifolkerd/tabulator#454]
For the fine work in this very comprehensive project, surely you must appreciate some sort of gratitude.   You have put in some time, no doubt, both in product and documentation.   Impressed.   If it's just a hardy thanks, then thanks!

**Comment by alainpannetier** [comment]
:+1:

**Comment by olifolkerd** [comment]
Hey,

Thanks for your kind words.

Tabulator is a labor of love for me, and a chance to give back to the coding community, a hardy thanks is much appreciated, and if you have a second would you mind staring the repo so others know you like it, that would be great 😄 

In a couple of months i will be moving the documentation site to its own servers so i can add a load of new features like monthly mailing lists, forums, project road maps etc. At that point i will add a donations page in case any of the community would like to help out with the hosting costs (or buy a friendly developer a drink or two 😄)

In the mean time, nothing would please me more that to see members of the community helping each other out in the issues list, posting ideas for future Tabulator features, and generally spreading the word of Tabulator.

Thanks for choosing Tabulator, and thanks for taking the time to let me know that you are enjoying using it, it is great to hear how much people appreciate it 😄 

Cheers

Oli

**Comment by hrstoyanov** [comment]
Super impressed by the work of Oli! The planned  v4.0 features blew my mind ... will popularize this project anyway I can, Thank you Oli!

**Comment by Sm00g15** [comment]
look forward to getting you a beer Oli

**Comment by lac616** [comment]
I agree with everyone here. We are getting ready to launch a redesign of our market quotes using this control and I couldn't be happier with the results. Oli, when you are ready to accept an additional form of gratitude other than our heartfelt thanks then please make it known to us!

**Comment by jsEveryDay** [comment]
Keep up the good work. With minor fixes (css mostly) this is better than Kendo Grid or UI Grid.
Keep it lightweight and conflict free.

Cant wait for 4.0 :))

**Comment by olifolkerd** [comment]
Hey,

Thanks for the kind words, 

If you have found any issues with the CSS please raise an issue so i can ensure they are fixed.

Cheers

Oli

**Comment by JimSmithJr** [comment]
I second that!  I've done extensive research and so far have found Tabulator to be cleanest solution out there.  The documentation is extensive and examples thorough.  Thank you!

**Comment by olifolkerd** [comment]
Hey All,

Thanks for all your kind words, it really is awesome to hear that you are enjoying using the library.

A few people have kindly offered to donate to help support the cost of the website etc.

I have now setup a Patreon page, for those generous souls if they want to make a donation. More information can be found on the {Community Page](http://www.tabulator.info/community)

Cheers

Oli :)
