### ISSUE TITLE
Context menu position and size are not drawn correctly

### ISSUE THREAD

**Issue by sinbino** [olifolkerd/tabulator#4549]
**Describe the bug**
If rowContextMenu is opened at the bottom of the browser document area, the context menu is expected to expand upward from the cursor position, but it expands downward and is displayed off-screen.
Also, if it is opened at the bottom edge of the table, a context menu with an odd height is generated.

**Tabulator Info**
- Which version of Tabulator are you using?
Tabulator 6.2.5

**Working Example**
https://jsfiddle.net/sinbino/0g32xpck/4/

**To Reproduce**
1. Go to https://jsfiddle.net/sinbino/0g32xpck/4/
2. Right-click on row near the bottom of the table to open the context menu
3. Even at the bottom of the browser's document area, the context menu is drawn downward and cannot be manipulated. They may also be drawn at odd lengths

**Expected behavior**
Context menus should be drawn at the correct height in the upward direction.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows10 22H2  19045.4046
 - Browser chrome
 - Version 127.0.6533.88

Edit:
Add a sample Tabulator table with a height to match the browser viewport.
Right-clicking at the bottom of the table opens a context menu off-screen.
https://jsfiddle.net/sinbino/1xg7vfts/24/

**Comment by Martino-Martinez** [comment]
#4510

**Comment by sinbino** [comment]
That's right. Sorry, I guess I overlooked that.
