### ISSUE TITLE
Add multiple rows at a time

### ISSUE THREAD

**Issue by minalkArmstrong** [olifolkerd/tabulator#455]
Dear Oli,
I want to add multiple rows from one tabulator to other . Selected rows of first tabulator must added to another using add rows functions and rows must be added to already load tabulator.

Waiting for your reply......

Code-
```js
  $scope.AddPartToSP = function () {
              
                var selRow = $("#GRNTable").tabulator("getSelectedData");
             option-1                 
                $("#stckplantable").tabulator("setData", selRow);
             option-2
                $("#stckplantable").tabulator("addRow", $("#GRNTable").tabulator("getSelectedData"), false);

};
```

----------------------------------------------------------------------------------------------
Using option 1 Old data clear and new rows are added to second table .
option 2 add blank row.

**Comment by olifolkerd** [comment]
Hey,

Are you looking to replace the contents of the second table with the selected rows from the first, or are you looking to add the selected rows to the existing data in the second table.

Cheers

Oli

**Comment by minalkArmstrong** [comment]
Hello Oli,
I dont want to replace the content ,I want to append the selected rows on existing rows.

**Comment by Paraplegix** [comment]
A bit late to the party.

This is how i did it in previous version of tabulator, but it should in theory still work now (if it doesn't then crap) : 

`var selectedData = board1.tabulator("getSelectedData").slice(0);
board2.tabulator("updateOrAddData", selectedData);
board1.tabulator("deselectRow");`

Where `board1` and `board2` are just shortcut for the `$("#boardDivId")`
`board1.tabulator("deselectRow");` is optional.
Can't test it right now on my side but i'm confident it did work at some point in the past

❗️ Also keep in mind that this will not allow you to add two time the same row, for that you would have to run through selectedData entries and remove the index field from each entry

**Comment by olifolkerd** [comment]
@Paraplegix is right, the correct way is to use the ***updateOrAddData*** function, which you can pass an array of row object to:
```js
$("#example-table").tabulator("updateOrAddData", [
    {id:1, name:"bob"}, //a new row
    {id:3, name:"steve"} //another new row
]);
```

Cheers

Oli
