### ISSUE TITLE
TabulatorFull does not include Export module with getHtml() 

### ISSUE THREAD

**Issue by ecofi** [olifolkerd/tabulator#4566]
**Describe the bug**
 table.getHtml() is not available. Error output: function not available. I'm using tabulator as esm with TabulatorFull

**Tabulator Info**
Tabulator version 6.2

**Working Example**
Demo example with the issue: https://jsfiddle.net/hleogr/qc0hdg78/10/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Run jsFiddle example 
2. See error output in console

**Expected behavior**
According to documentation import {TabulatorFull as Tabulator} from ... includes all modules and therefore html table output function should be available

**Additional context**
Running client side in browser

**Comment by bornova** [comment]
You need to wait for the table to be built first:
```javascript
newTable.on('tableBuilt', () => {
  console.log(newTable.getHtml())
})
```

**Comment by ecofi** [comment]
> You need to wait for the table to be built first:
> 
> ```js
> newTable.on('tableBuilt', () => {
>   console.log(newTable.getHtml())
> })
> ``

Indeed, thank you! Issue closed. Ideally, documentation can be enriched to indicate if function are only available after tableBuilt event. Merci again.
