### ISSUE TITLE
Feature comparison with Smart client grid

### ISSUE THREAD

**Issue by hrstoyanov** [olifolkerd/tabulator#458]
Oli and all,
If you ever run out of ideas of what to do next, try beating this [grid widget](http://www.smartclient.com/smartclient/showcase/?id=gridsFolder):

**Comment by olifolkerd** [comment]
Thanks for the suggestion,

Tabulators new features are driven by the needs of its users, I have enough on the roadmap already to keep me busy for the next year and a half, and the roadmap is always shifting to take in the latest needs of its users into account.

In a couple of months the Tabulator site is getting an upgrade and i will make the full development roadmap available for everyone to see.

To wet your appetite, version 3.2 will be coming out in just over a week and will feature column calculations, nested row grouping, and handling of multi-dimensional data and lots more!

If you have any specific features you feel you need from Tabulator, please create an issue and i will see when i can get them added.

Cheers

Oli

**Comment by hrstoyanov** [comment]
Thanks Oli, looking forward to 3.2 and 4.0 !

I think you are pretty close to the perfect "nirvana grid", comparing you to other OSS grids such as [this one](http://js-grid.com/) . 

The reason I pointed out the Smartclient Grid is because I know there grid features were all driven 100% by their long list of enterprise customers, and up until now it was the most mature grid control I have seen.

One thing I noticed in your 4.0 feature set is "muti-dimensional" grid? So, if you need inspiration - [here](http://www.smartclient.com/smartclient/showcase/?id=analyticsFS) is one.
