### ISSUE TITLE
Website is unavailable

### ISSUE THREAD

**Issue by zakharRealogic** [olifolkerd/tabulator#4582]
Website is unavailable today.
DNS works fine and resolves tabulator.info as 52.56.224.52
Telnet opens the session by 80 and 443.
However, curl https://tabulator.info is being timed out.

**Comment by olifolkerd** [comment]
Hey all. Sorry for the delayed reply, just got in from work.

Looking into this now. Please bare with

**Comment by olifolkerd** [comment]
All back up and running! We server just needed rebooting :) 

Thanks for the heads up

Happy Tabulating

Oli :)

**Comment by ramyakrish85** [comment]
thanks for fixing this
