### ISSUE TITLE
Need a custom url for each row to produce images

### ISSUE THREAD

**Issue by Sm00g15** [olifolkerd/tabulator#459]
So I'm calling data using an AJAX request like so: 

//load sample data into the table
$("#example-table-theme").tabulator("setData", "https://api.coinmarketcap.com/v1/ticker/?limit=100");

However, using this API doesn't include images for each coin. That being said, I'd like to include a column that does, by using the API data mixed with a url. For example: 

{title:"", field:"http://www.coincap.io/images/coins/" + name + ".png", sorter:"string", width:50, frozen: true},

^ I've tried the above however and no dice, any ideas on how I could accomplish this using tabulator?

**Comment by Sm00g15** [comment]
also, while I'm thinking about it, if the above is able to be accomplished is there a way to limit the size of the .png images?

**Comment by olifolkerd** [comment]
Hey, 

You can achieve that using a custom formatter.

Here is an example that replaces the name column with the image:

```js
//define your custom formatter
var imageFomratter = function(cell, formatterParams){
        //cell - the cell component
        //formatterParams - parameters set for the column

        return "<img src='http://www.coincap.io/images/coins/" + cell.getValue() + ".png' />"; //return the contents of the cell;
    },
}

//create the table
$("#example-table").tabulator({
    columns:[
        {field:"name", sorter:"string", width:50, frozen: true, formatter:imageFormatter},
    ]
});
```

Here is an example that adds the image in another column to the left of the name column

```js
//define your custom formatter
var imageFormatter = function(cell, formatterParams){
        //cell - the cell component
        //formatterParams - parameters set for the column

        return "<img src='http://www.coincap.io/images/coins/" + cell.getData().name + ".png' />"; //return the contents of the cell;
    },
}

//create the table
$("#example-table").tabulator({
    columns:[
        {sorter:"string", width:50, frozen: true, formatter:imageFormatter},
        {title:"Name", field:"name", sorter:"string", width:50, frozen: true},
    ]
});
```
If you want to restrict the size of the image you could add some inline styles to the returned ***img*** element to set the ***max-width*** and ***max-height***

full documentation on custom formatters can be found in the [Formatter Documentation](http://olifolkerd.github.io/tabulator/docs/#formatting)

Let me know if that helps

**Comment by Sm00g15** [comment]
I used the provided example and not getting anything. Double checked for potential errors and can’t see anything off the back..

**Comment by olifolkerd** [comment]
when you say you are not getting anything what do you mean?

What is happening to the cells in that column?

Which of the two options did you try?

Ca

**Comment by Sm00g15** [comment]
It just breaks my entire grid, and nothing renders. 

I tried the second option, the example you sent that adds the image to the left of the name column.

//cell - the cell component //formatterParams - parameters set for the column

^ I didn't add parameters in the function for these guys, could that be an issue?

**Comment by olifolkerd** [comment]
could you post a copy of your table constructor so i can test it and get to the bottom of the issue.

Cheers

**Comment by Sm00g15** [comment]
Sure thing.

var imageFormatter = function(cell, formatterParams){
        //cell - the cell component
        //formatterParams - parameters set for the column

        return "<img src='http://www.coincap.io/images/coins/ <http://www.coincap.io/images/coins/>" + cell.getData().name + ".png'/>"; //return the contents of the cell;
    },
}


$("#example-table-theme").tabulator({
    height: false, // set height of table (optional)
    fitColumns:true,
    headerFilterPlaceholder:"Search Coins",
    resizableColumns: false,
    rowClick:function(e, row){
        window.open("https://cryptoreport.com/ <https://cryptoreport.com/>" + row.getData().symbol);
    },
    responsiveLayout: false, //fit columns to width of table (optional)

    columns:[ //Define Table Columns
        {title:"#", field:"rank", sorter:"number", width:50, frozen: true},
        {sorter:"string", width:50, frozen: true, formatter:imageFormatter},
        {title:"Coin", field:"name", sorter:"string", width:150, frozen: true, headerFilter:"input"},
        {title:"Symbol", field:"symbol", sorter:"string", width:100},
        {title: "Price", field:"price_usd", width:150, sorter:"number", align:"center", formatter:"money", formatterParams:{symbol:"$"}},
        {title: "Market Cap", field:"market_cap_usd", width:200, sorter:"number", align:"center", formatter:"money", formatterParams:{symbol:"$", precision:null}},
        {title:"24hr Volume", field:"24h_volume_usd", width:200, sorter:"number", align:"center", formatter:"money", formatterParams:{symbol:"$", precision:null}},
        {title:"Available Supply", field:"available_supply", sorter:"date", align:"center", formatter:"money", formatterParams:{precision:null}},
    ],
});


$("#example-table-theme").tabulator({
    initialSort:[
        {title:"#", field:"rank", sorter:"number", width:50},
        {sorter:"string", width:50, frozen: true, formatter:imageFormatter},
        {title:"Symbol", field:"symbol", sorter:"string", width:150},
        {title:"Coin", field:"name", sorter:"string", width:150},
        {title: "Price", field:"price_usd", sorter:"number", align:"center", formatter:"money", formatterParams:{symbol:"$"}},
        {title: "Market Cap", field:"market_cap_usd", sorter:"number", align:"center", formatter:"money", formatterParams:{symbol:"$", precision:null}},
        {title:"24hr Volume", field:"24h_volume_usd", sorter:"number", align:"center", formatter:"money", formatterParams:{symbol:"$", precision:null}},
        {title:"Available Supply", field:"available_supply", sorter:"number", align:"center", formatter:"money", formatterParams:{precision:null}},
    ],
});

**Comment by olifolkerd** [comment]
You seem to be trying to declare your table twice for some reason

Your second table declaration seems to be trying to pass column definitions into the initalSort options. 

what were you aiming to do with the second table definition? let me know and i can suggest the correct approach.

**Comment by Sm00g15** [comment]
ahhh, basically just to get the columns initially sorted in that particular order, but I could see how a) they potentially may not even need that b) I could just add it to the original table declaration. That being said, the grid was rendering before with the 2 table declarations, it was only after I added the custom formatter and tried to add it to the table when the grid stopped rendering.

**Comment by Sm00g15** [comment]
I can add it to a repo and invite you in if you’d like to see the full code

**Comment by olifolkerd** [comment]
There are a few issues with the code:
### The imageFormatter Function
For some reason i managed to include an extra closing curly brace in the function i sent over (i have removed if from the example now), you should remove the ```},``` from near the end of the function.

This issue did show up in the developer console of the browser, if you use this tool, not only will it show you code errors, but Tabulator will provide useful feeback through it if its properties are setup incorrectly.

### Not using Virtual DOM
by not setting a height for your table you are not using the virtual DOM, this means that if you load a lot of rows into the table it will slow down as it tries to display them all in the DOM. by setting the height, Tabulator will only display the visible rows, increasing performance of the table.

### Sorting
You can only define a table once, after that you need to use available functions to make the changes to the table

You two options are:

**Set the initial sort in your original constructor**
```js
$("#example-table-theme").tabulator({
    height: false, // set height of table (optional)
    fitColumns:true,
    headerFilterPlaceholder:"Search Coins",
    resizableColumns: false,
    rowClick:function(e, row){
        window.open("https://cryptoreport.com/ <https://cryptoreport.com/>" + row.getData().symbol);
    },
    responsiveLayout: false, //fit columns to width of table (optional)
    initialSort:[
        {column:"rank", dir:"asc"}, //sort by this first
        {column:"name", dir:"desc"}, //then sort by this second
    ],
    columns:[ //Define Table Columns
        {title:"#", field:"rank", sorter:"number", width:50, frozen: true},
        {sorter:"string", width:50, frozen: true, formatter:imageFormatter},
        {title:"Coin", field:"name", sorter:"string", width:150, frozen: true, headerFilter:"input"},
        {title:"Symbol", field:"symbol", sorter:"string", width:100},
        {title: "Price", field:"price_usd", width:150, sorter:"number", align:"center", formatter:"money", formatterParams:{symbol:"$"}},
        {title: "Market Cap", field:"market_cap_usd", width:200, sorter:"number", align:"center", formatter:"money", formatterParams:{symbol:"$", precision:null}},
        {title:"24hr Volume", field:"24h_volume_usd", width:200, sorter:"number", align:"center", formatter:"money", formatterParams:{symbol:"$", precision:null}},
        {title:"Available Supply", field:"available_supply", sorter:"date", align:"center", formatter:"money", formatterParams:{precision:null}},
    ],
});
```

**Set the sort after the table is defined**
In this case you use the  ***setSort*** function
```js
$("#example-table-theme").tabulator("setSort", {
     {column:"rank", dir:"asc"}, //sort by this first
     {column:"name", dir:"desc"}, //then sort by this second
});
```

In either case you only include the columns that you want to sort by, not the entire list of columns. For full documentation have a read of the [Sorting Documentation](http://olifolkerd.github.io/tabulator/docs/3.1/#sorting);

**Comment by Sm00g15** [comment]
Doooooooooooood, works like a charm! Huge thanks Oli
