### ISSUE TITLE
Bad data position in addRow

### ISSUE THREAD

**Issue by chaissac** [olifolkerd/tabulator#46]
Hi, 

I found a little problem in addRow method : the unshift and the push method are inverted.
The row is not inserted correctly in activeData.
We should have : 
```
		//append to top or bottom of table based on preference
		if(top == "top"){
			self.activeData.unshift(item);
			self.table.prepend(row);
		}else{
			self.activeData.push(item);
			self.table.append(row);
		}
```
Cheers,
Philippe

**Comment by olifolkerd** [comment]
well spotted, i have just uploaded a fix for this
