### ISSUE TITLE
Grouping and Pagination

### ISSUE THREAD

**Issue by mcnams** [olifolkerd/tabulator#460]
Hello,

Is it true that Tablulator will only support Grouping or Pagination, but not both?

Regards,

SM

**Comment by olifolkerd** [comment]
Hey SM,

At present this is this is true. though it is on the roadmap for later in the year.

Do you have a particular usage case for this?

Cheers

Oli

**Comment by mcnams** [comment]
Hi Oli,

Sorry for the very late reply. Your reply went into a spam folder. 

The use case is I have a table with 3000 rows. The subject is cats (not true, but a good example) and I have multiple columns in the table as well. I want to be able to group by any column and also refine to data within that column. So, I choose Type and want to then focus on Angora cats. I still have 50 pages with 25 rows each. I want to be able to page through the 50 pages using the pagination feature. And, this can't all exist on the client side because the large data hit will bring the whole thing to its knees.

Thanks for your reply, and again, sorry for my late return.

**Comment by olifolkerd** [comment]
Have you considered using the ***filter*** system to display only the selected type of "cat", it will give a much more pleasant user experience.

You could add a custom header filter element with a select element to select from the values in the column

More information on this can be found [here](http://olifolkerd.github.io/tabulator/docs/#filtering)

**Comment by mcnams** [comment]
You are exactly right, and I have considered that, but I am just the User Experience Designer - and that's all I can really say about that. Thanks so much for your feedback. I sincerely appreciate it.
