### ISSUE TITLE
Child rows

### ISSUE THREAD

**Issue by vasiliyaltunin** [olifolkerd/tabulator#462]
It will be nice if tabulator have similar functionality - https://www.datatables.net/examples/api/row_details.html

**Comment by olifolkerd** [comment]
Hey,

The good news is you can already do this with the ***rowFormatter*** you can use it to insert any other element you want into the row.

checkout the [Formatting Documentation](http://olifolkerd.github.io/tabulator/docs/3.1/#formatting) for more details.

Cheers

Oli
