### ISSUE TITLE
QuickStart basic example version 3 error on RowClick

### ISSUE THREAD

**Issue by vasiliyaltunin** [olifolkerd/tabulator#463]
In http://olifolkerd.github.io/tabulator/quickstart/3.1/

Basic Example

`rowClick:function(e, id, data, row){ //trigger an alert message when the row is clicked`
is wrong for version 3, it must be

`rowClick:function(e, row){`

**Comment by olifolkerd** [comment]
Great Spot, I had forgotten to update those to 3.0 syntax.

The quickstart guides have now been updated

Thanks for letting me know :)
