### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by Dkkemaries** [olifolkerd/tabulator#464]
Hello, 
I just started to use tabulator and  it is great , but I can't find some information.
Is here a way to create filter for one field using "and(or) ", for example possibility to write Bob and(or) Sandra  ( in SQL we use WHERE name like 'Bob' and(or) name like 'Sandra' ).

BR,

**Comment by olifolkerd** [comment]
Hey,

To do that you would need to use a custom filter, for example:
```js
function customFilter(data){
    //data - the data for the row being filtered
    
    //like comparison function
    like(field, value){
    	if(value === null){
    		return field === value ? true : false;
    	}else{
    		return field.toLowerCase().indexOf(value.toLowerCase()) > -1 ? true : false;
    	}
    }
    
    //return filter result
    return like(data.name, "Bob") || like(data.name, "Sandra");
}

//set filter
$("#example-table").tabulator("setFilter", customFilter);
```

Let me know if that helps

Cheers

Oli

**Comment by Dkkemaries** [comment]
Good morning,

yes, it works. 
May be I did't write correctly , but is it possible to use this with header filters ( in header filter field we write something like (Sandra;Bob) and as a result we will get name all rows with Bob and Alice 
 // I think in this case we can use  ||

**Comment by Paraplegix** [comment]
As far as i know, you can't implement a custom filtering function based directly on the header filter field.

However you can still create a filter function that will read an external input for `(Sandra;Bob)` and then will filter only the name `Sandra` and `Bob`.

**Comment by Dkkemaries** [comment]
Yep, just created by combining  olifolkerd  and Paraplegix methods. Thanks.

Another question :  is it possible to use in tabulator Autosum , for every  filtered row/column , like in Excel (for example , SUM(A2:A10))?

**Comment by olifolkerd** [comment]
At the moment, there is no autosum but...

The great news is column calculations will be available in version 3.2 which is being released this weekend!

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey,

You will be happy to hear that Tabulator 3.2 has just been released, and with it comes column calculations, and the ability to add custom filter functions to header filters:

Column Calculation:
```js
{title:"Rating", field:"rating", topCalc:"avg"} //show average rating
```

Header Filter Function:
```js
{title:"Age", field:"age", headerFilter:"input", headerFilterPlaceholder:"Max Age", headerFilterFunc:"<="} //show only rows with an age less than or equal the entered value
```

Full information can be found in the [Calculations Documentation](http://olifolkerd.github.io/tabulator/docs/3.2/#calculations) & [FilteringDocumentation](http://olifolkerd.github.io/tabulator/docs/3.2/#filtering)

Cheers

Oli

**Comment by Paraplegix** [comment]
Very nice !
