### ISSUE TITLE
Retain position after a redraw? 

### ISSUE THREAD

**Issue by GavinOG** [olifolkerd/tabulator#466]
Hey, 
Thanks for all the work on the library, I find it very easy to get up and running with. 

I am experimenting with implementing a tool for interacting with data in a table. I click on a cell, record that cell's value in an array, and then highlight every row that has the same matching cell value. 

On a cell click, I store the value into the array, and then call 
`$("#example-table").tabulator("redraw", true);`

The rowFormatter:function(row) then checks to see if the value is present in the current row, and if so, highlights it. This works fine, however, because the table is re-drawn, the location of the table jumps back to the very first row. Is there a way to record what row(s) are currently being displayed, and then force the view to jump back to that, after a redraw? 

Or maybe there's a better way to highlight the row, rather than a redraw of the entire table.

**Comment by GavinOG** [comment]
Ah, I see the "scrollToRow" option, however when I try this after calling "redraw", I get the following error

"ReferenceError: assignment to undeclared variable row"

I have tried using a number and cell.getRow, but same error. 

`cellClick:function(e, cell){
			ioc_data.push({'id':ioc_id,'ioc':cell.getValue(), 'type':'age', 'guid_count':'5'})
			ioc_id+= 1; 
			$("#ioc-table").tabulator("setData", ioc_data);
			$("#example-table").tabulator("redraw", true);
			$("#example-table").tabulator("scrollToRow", cell.getRow());
		}`

**Comment by olifolkerd** [comment]
Hey,

could you post your entire tabulator constructor object so i can run a quick test and see where the issue is coming from.

Cheers

Oli

**Comment by GavinOG** [comment]
Hey, 
Thanks for the reply! Testing page attached. 

[table_test.txt](https://github.com/olifolkerd/tabulator/files/1163342/table_test.txt)

**Comment by olifolkerd** [comment]
Thanks for sending that over.

I now see what you are trying to do, in this instance calling redraw on the table is a bit overkill, you dont really want to cause tabulator to redraw all the elements that make up the table, all you want to do is update the rowFormatter on each of the rows. there is a way to do this that should update what you need without redrawing all the components of the table, using the ***update*** function on the row components.

You will need to using tabulator 3.1.5 for this to work

In your ***cellClick*** callback you should replace these two lines:
```js
$("#example-table").tabulator("redraw", true);
$("#example-table").tabulator("scrollToRow", 10);
```
With the following code which will itterate through each row on the table and trigger an update on the row data (but you wont pass in any new data so the values wont change but the rowFormatter will be re triggered):
```js
$("#example-table").tabulator("getRows").forEach(function(row){
    row.update({}); //trigger row formatter without updating data
});
```

Then in your row formatter you need to adjust your if statement to reset the row background if the row is no longer highlighted:
```js
if (data[elem['type']] == elem['ioc']){
    row.getElement().css({"background-color":"#A6A6DF"});
}else{
    row.getElement().css({"background-color":""});
}		
```

Let me know if that helps.

Cheers

Oli

**Comment by GavinOG** [comment]
Just noticed I never replied to this, sorry. It worked perfectly, thanks !
