### ISSUE TITLE
Editing windows cutting off text

### ISSUE THREAD

**Issue by stack-its** [olifolkerd/tabulator#468]
<img width="105" alt="text_clipped" src="https://user-images.githubusercontent.com/1207542/28505184-fe1239a8-6fe6-11e7-9778-fc2a81501e3a.png">
Hi Oli,

Just loaded 3.2 - mobile events work great now - thank you very much for adding those ! (big smile)

- Noticed in editing integer/floating/date/time/money - the text is shifted down w/in the editing window & is partially cut off.

What would the css fix for this be?

Thanks,  Bill

**Comment by olifolkerd** [comment]
Hey,

I cannot seem replicate your issue,

Have you loaded the new CSS to go with the new JavaScript? and tried force refreshing your browser?

Which browser are you using and what is your table constructor?

Cheers

Oli

**Comment by stack-its** [comment]
Hey Oli,

Yeah, I had everything updated & refreshed - I found some stray padding this morning that was the culprit - as usual a simple fix buried in the css ;)
