### ISSUE TITLE
Calculation and grouping export 

### ISSUE THREAD

**Issue by Dkkemaries** [olifolkerd/tabulator#469]
Hello, 
at first I want to say how much I am impressed about tabulator and its new functions. Great library and easy to implement.

During the tests of new functions some questions appeared :
1. I found that I can't export the calculation results into Excel . I can imagine that it is still possible to add this results as a new row into my existing table ?
2. Is it possible to export grouping results into Excel too?

BR,

**Comment by olifolkerd** [comment]
Hey,

At the moment it is only possible to export the table data itself into the file. however you could use the ***downloadDataMutator*** function to manipulate data going into the file formatter to add extra rows if you liked.

If you wanted to include groups in your download you would need to write your own custom file formatter to decide how to lay them out in the file.

Cheers

Oli
