### ISSUE TITLE
add row may add multiple times

### ISSUE THREAD

**Issue by vonschbo** [olifolkerd/tabulator#47]
I am using NW.js and I save table data in a local file, I use your add table function, but I find if I did not close the current page, and open a saved table data file, the add new row function will add multiple new empty rows not just one empty row. 

    $("#add_table").click(function() {
				$("#samples-table").tabulator("addRow");
			});

**Comment by olifolkerd** [comment]
I dont understand what you mean vonschbo,

Are you saying that calling the ***addRow*** function is adding more than one row?

Could you confirm if it is a graphical glitch or it is extra rows showing up in the table data when you call ***getData***
Could you describe the chain of events that causes your issue to happen.

**Comment by vonschbo** [comment]
It is extra rows showing up. As my first language is not English, pardon me please. 
I start from an empty table, then I added some rows and columns and saved it. At current page, I loaded the data to the table, when I press add new row button(with a simple onclick method on add new empty row), it will add multiple empty rows.

**Comment by olifolkerd** [comment]
Are you creating an index value for the new rows when you save them out of tabulator?

**Comment by vonschbo** [comment]
Yes, different row id

**Comment by vonschbo** [comment]
DOM manipulation problem

**Comment by olifolkerd** [comment]
Was there a problem with Tabulator? Or was ot something outside the library?

**Comment by vonschbo** [comment]
It should be something else, nwjs's event handling problem.
