### ISSUE TITLE
onClick vs cellClick

### ISSUE THREAD

**Issue by kurtknippschild** [olifolkerd/tabulator#470]
Hi Oli,

by teh test vo the new version 3.2 I have a big problem.

In the old Version I have this column Definition:

								{title:"<bean:message bundle="<%= resources %>" key="imaAktivitaeten_liste.label.to_beschreibung"/>", field:"to_beschreibung", width: 450, onClick:function(e, cell, val, data){
								$.post("imaAktivitaeten_AJ.ims", 
								{
									cache: false,
					 				contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
									TO_ID: data.TO_ID,
									EXP_ID_VATER: '<%= EXP_ID_VATER %>',
									EXP_ID: '<%= EXP_ID %>',
									OG_ID: '<%= OG_ID %>',
									OG_NAME: '<%= OG_NAME %>',				     		  
									OBJ_NAME: '<%= OBJ_NAME %>',
									OBJ_NAME_VATER: '<%= OBJ_NAME %>',  		  
									OK_ID:'<%= OK_ID %>',
									OBJ_ID: '<%= OBJ_ID %>',
									OBJ_ID_VATER: '<%= OBJ_ID %>',
									FU_RECHT: '<%= FU_RECHT %>',
									IST_INVENTAR: '<%= IST_INVENTAR %>',  
									darstart: 'edit',
									aktion: 'infoAk'
								},
								function(data) 
								{		 	
			          		$('#objektAktivitaeten_tabs_<%= OBJ_ID %>').html(data);
										$('#progressbar').css('display', 'none');
			      	 	}, "html")
	
				        	},},

In the new version when I change onClick to cellClick(e, cell) {
								$.post("imaAktivitaeten_AJ.ims", 
								{
									cache: false,
					 				contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
									TO_ID: data.TO_ID,
									EXP_ID_VATER: '<%= EXP_ID_VATER %>',
									EXP_ID: '<%= EXP_ID %>',
									OG_ID: '<%= OG_ID %>',
									OG_NAME: '<%= OG_NAME %>',				     		  
									OBJ_NAME: '<%= OBJ_NAME %>',
									OBJ_NAME_VATER: '<%= OBJ_NAME %>',  		  
									OK_ID:'<%= OK_ID %>',
									OBJ_ID: '<%= OBJ_ID %>',
									OBJ_ID_VATER: '<%= OBJ_ID %>',
									FU_RECHT: '<%= FU_RECHT %>',
									IST_INVENTAR: '<%= IST_INVENTAR %>',  
									darstart: 'edit',
									aktion: 'infoAk'
								},
								function(data) 
								{		 	
			          		$('#objektAktivitaeten_tabs_<%= OBJ_ID %>').html(data);
										$('#progressbar').css('display', 'none');
			      	 	}, "html")
}, },

thats not work.
Can you help me?

Thanks in advance.

VG Kurt

**Comment by kurtknippschild** [comment]
Hi Oli,

the Problem ist this row:
TO_ID: data.TO_ID,

Without this row it's work.
But i need the information for the action.

VG Kurt

**Comment by kurtknippschild** [comment]
Sorry, te close was my issue.

**Comment by olifolkerd** [comment]
The ***cellClick*** function accepts different arguments to the old ***onClick*** function.


it now only passes in the click event and the ***Cell Component Object*** which you can use to access all other cell data.

You will want to replace this:
```js
onClick:function(e, cell, val, data){
```

With this:
```js
cellClick:function(e, cell){
    var data = cell.getData();
```

That should get you back up and running.

Checkout the [Cell Component Documentation](http://olifolkerd.github.io/tabulator/docs/3.2/#component-cell) For more information.

Cheers

Oli
