### ISSUE TITLE
ColumnMinWidth

### ISSUE THREAD

**Issue by kurtknippschild** [olifolkerd/tabulator#471]
Hi Oli,

can I change the columnMinWidth to 5px and the width of the Volumen also to 5px.

The Column is at the end of the row and has only a Background-Color.
The value for the color is a data.

Thanks in advance.

VG Kurt

**Comment by olifolkerd** [comment]
Hey,

Im afraid i dont understand, what is ***Volumen ***

Cheers

Oli

**Comment by kurtknippschild** [comment]
Hi Oli,

Volumen is Column.
Sorry, Spell checking.

VG Kurt

**Comment by olifolkerd** [comment]
You can certainly set the ***minWidth*** and ***width*** properties of a column to the same value there is no problem there.

the ***color*** formatter can be used to set the background color of a cell, there is an example of this in the [Formatter Example](http://olifolkerd.github.io/tabulator/examples/3.2/#formatters)

The column definition for this column would look something like this:
```js
{title:"Color", field:"color", width:5, minWidth:5, formatter:"color"},
```

Let me know if that helps

Cheers

Oli

**Comment by kurtknippschild** [comment]
Hi Oli,

thank for your great help.

VG Kurt
