### ISSUE TITLE
How to get group by parameters from table ?

### ISSUE THREAD

**Issue by minalkArmstrong** [olifolkerd/tabulator#472]
Hi Oli,
I want list of parameter by which table rows are grouped on button click .

  groupBy: "GRNNo"

I want list of GRNno from tabulator.

**Comment by olifolkerd** [comment]
Hey,

Tabulator has the ***dataGrouped*** callback that gets called any time data is grouped and passes in an array of the top level group components.

You can then call the ***getKey*** function on these components to get their key:
```js
$("#example-table").tabulator({
    dataGrouped:function(groups){
        //groups - array of top level group components
        groups.forEach(function(group){
            var key = group.getKey();
        });
    },
});
```

Let me know if that helps.

Cheers

Oli

**Comment by minalkArmstrong** [comment]
Hey Oli ,
I want function like this

> selectedData = $("#example-table").tabulator("getSelectedData"); //get array of currently selected data.

This returns selected data likewise i want group keys after data is added to tabulator  in certain function .

**Comment by olifolkerd** [comment]
That function dosnt exist at the moment, but you can use the above code in a similar way:

```js
var groupList = [];

function getGroups(){
    return groupList;
}

$("#example-table").tabulator({
    dataGrouped:function(groups){
        //groups - array of top level group components

        groupList = [];

        groups.forEach(function(group){
            groupList.push(group.getKey());
        });
    },
});
```

**Comment by olifolkerd** [comment]
i have added a ***getGroups*** function to the roadmap for version 3.3
