### ISSUE TITLE
Feature Request: Number of items display without grouping

### ISSUE THREAD

**Issue by lac616** [olifolkerd/tabulator#473]
Hi!

It would be great if tabulator had an option such a "showRowCount" that would display the row count similar to screenshot: 

![capture](https://user-images.githubusercontent.com/27359692/28539006-25f7fdee-707e-11e7-8d8b-6f58e009fe65.PNG)

Currently I provide a hack to achieve the desired result:
`groupBy: function(data){
               return '';
}`
The expand/collapse caret wouldn't be necessary since the rows would be in an ungrouped state.

Thanks!

**Comment by olifolkerd** [comment]
Hey,

Im not sure I follow, in grouped mode it does this for you,

If you just want to access the number of rows in the table you can use the ***getDataCount*** function;
```js
var count = $("#example-table").tabulator("getDataCount") // get total number of rows in table
var count = $("#example-table").tabulator("getDataCount", true) // get number of rows filtered in table
```

If you want to display it as part of the table you can use the Column Calculation feature that was added in the 3.2 release with a ***count*** calculation type:
```js
$("example-table").tabulator({
    columns:[
        {title:"Item", field:"item", topCalc:"count"} //ccount the number of cells in this column with data
    ],
});
```

if you wanted to you could also use a custom  ***footerElement*** to display this value at the base of the table have a look at issue #400 for mote info on this.

Let me know if any of those are what you are after?

Cheers

Oli
