### ISSUE TITLE
Documentation: Example for custom editor has incorrect reference

### ISSUE THREAD

**Issue by wp4nuv** [olifolkerd/tabulator#474]
When describing a custom editor, the example states
```
onRendered(function(){
     input.focus();
});

```
It should read
```
onRendered(function(){
     editor.focus();
});

```
BTW, This library is the most awesome thing since sliced bread. We're looking forward to the dedicated hosting and donation button to gladly sponsor a few rounds!!

**Comment by olifolkerd** [comment]
Hey,

Thanks for the kind words! always great to hear people are enjoying using tabulator!

Thanks for the heads up, I have pushed an update to the documentation so it should all be sorted in the next min or so.

Let me know if you find anything else.

Cheers

Oli :)
