### ISSUE TITLE
tabulator_bootstrap Theme Issue

### ISSUE THREAD

**Issue by minalkArmstrong** [olifolkerd/tabulator#476]
I  applied this css to tabulator and added two css classes for "table-striped table-condensed" .
Due to table-striped color of selected row is not applied to light gray color row but it works for white color strip.
Is there any solution for this?

**Comment by olifolkerd** [comment]
Hey,

I have just pushed an update to the master branch with a fix for this.

I will include it in the 3.2.1 patch release this weekend.

Thanks for letting me know

Cheers

Oli

**Comment by minalkArmstrong** [comment]
Ok Oli ...thank you for your support.
