### ISSUE TITLE
Sort Bytes

### ISSUE THREAD

**Issue by rthill** [olifolkerd/tabulator#477]
Hi,

is it possible to sort bytes or GB ascending and descending properly in tabulator.js? I couldn't find a way to make the column containing a disk size sorting properly.

Thanks.

**Comment by Paraplegix** [comment]
Hi
I would recommend you to use a numerical value (like 4.25, 10248 or 0.012) representing the most common "scale" your data is (Megabyte, Gigabyte or Kilobyte) so all your data are at the same level, then you use a [formatter ](http://olifolkerd.github.io/tabulator/docs/#formatting)to display things more properly, and the `number` [sorter ](http://olifolkerd.github.io/tabulator/docs/#sorting)

If i take the two value i gave you for example, and considering the base value is Megabite, then the formatter would display 4.25 Mb, 10.25Gb, and 12Kb (depending on how you do the conversion)

Then, you set your size column with the `number` sorter, then you can use either header sorting (little arrow icon in the header) or set sorting programmatically

If you directly inject "4.25Mb" in the column, the sorting will be donne on a string value and by character comparison, so if you sort ascending 1000 wil come before 2. I'd guess that was your problem.

Hope i helped

**Comment by rthill** [comment]
Hi,

You are right that I fill MB or GB and the sorting is done on string. I
will look into formatter and do my sorting based on numbers.

Thanks for your help.
