### ISSUE TITLE
Column alignment broke when sorting

### ISSUE THREAD

**Issue by Paraplegix** [olifolkerd/tabulator#478]
Was looking at [column calculation example](http://olifolkerd.github.io/tabulator/docs/3.2?#calculations) and noticed a little bug 

If you scroll horizontaly to view right most columns, and click on header to trigger a sort, the column header wont move, but the data column will snap back to the left.
To reproduce : 
1) go on the [column calculation example](http://olifolkerd.github.io/tabulator/docs/3.2?#calculations)  (or any other large table where data can be sorted on the example page)
2) Resize tour windows to make the horizontal scrollbar apear if needed.
3) move the scrollbar to the left
4) Click on any column header to trigger a sort
5) notice how the column moved but the header stayed in place

The table isn't permanently broken as just moving the scrollbar make everything go back in place.

Viewed on Firefox 54

**Comment by olifolkerd** [comment]
Hey,

I noticed exactly the same issue yesterday, i pushed a fix to the master branch last night.

I will be doing a patch release this weekend to include any other issues people find in the next few days,

Thanks for the heads up.

Cheers

Oli

**Comment by Cerebres** [comment]
I am noticing the same problem when using the code in de master branch, dist folder when adding frozen columns at the left of the table.
