### ISSUE TITLE
Poor "sorter" functionality

### ISSUE THREAD

**Issue by zopyx** [olifolkerd/tabulator#48]
The implemented functionality for custom sorters by specifying a comparison function is too weak.
The comparison function receives two cell values. However you can image a column displaying relative time information like "2 seconds ago", "10 minutes ago" etc. Usually you want to store the absolute timestamp either in your data or as data attribute on the table cell..However there is no way for getting hold of these data instead of "human readable" representation of the real value.

**Comment by olifolkerd** [comment]
Hi zopyx.

In your case what you want to do is store the data as a time stamp,  then create a custom formatter for that column that displays it as "10 minutes ago", that way when you sort it will work of the time stamp data, but display the human readable formatted data.

for information on generating your own custom formatter have a look at the [Formatting Documentation](http://olifolkerd.github.io/tabulator/docs/#formatting)

**Comment by zopyx** [comment]
This might help for easy usecase. But in many case you receive the data as-is from the backend - means the formatting is basically done on the backend and the frontend is just a "dumb" renderer. Good or bad - reality is full of such usecases.

**Comment by olifolkerd** [comment]
I can see where you are coming from.

I have another release coming out next week, i will add another couple of arguments to the sorter call that pass in the entire data object for that row to give you more to go off, that should cover all such usage cases.

Thanks for the great usage case example!

**Comment by zopyx** [comment]
Makes sense...or you pass in the index of the rows to be compared (if the sorter function has access to the global row data).

**Comment by olifolkerd** [comment]
It was such an easy tweak i have just stuck it in now. updated documentation can be found [here](http://olifolkerd.github.io/tabulator/docs/#sorting).

I will include full information in next weeks release.
