### ISSUE TITLE
Issue in column calculation

### ISSUE THREAD

**Issue by wp4nuv** [olifolkerd/tabulator#480]
First, thanks for a wonderful product!. I've come across something strange with column calculations involving money formatted columns.. Money formatting defaults to 2 decimal points precision, but the bottom sum precision is very odd:
```
1000.001000.004000.003509.004000.005000.0010000.001000.00
```
The current values on the column total 25,509 which is what I expected.  Have you seen this before?

**Comment by wp4nuv** [comment]
This is my constructor:
```
// Define Table
        $("#table-bln-tabulator").tabulator({
            height: "400px",
            dateFormat: "mm/dd/yyyy",
            progressiveRender: true,
            index: "budget_id",
            fitColumns: true, //fit columns to width of table (optional)
            responsiveLayout: true,
            placeholder: "No Data Available",
            columns: [ //Define Table Columns
        { title: "Item", field: "rehab_item", width: 188, editable:false },
        { title: "Description", field: "notes", editor:"textarea", editable: true, width: 443, formatter:"textarea"},
        { title: "Quantity", field: "quantity", align:"right", editable: true, editor:"number", width: 105 },
        { title: "Amount",bottomCalc:"sum", field: "budget_amount", formatter: "money", editable: true, width: 99 },
        /*{
            title: "", field: "", editor: false, align: "center", width: 81, formatter: edit_button, headerSort: false, cellClick: function (e, cell) {
                console.log(cell.getRow());    }
        },*/
        {
            title: "", editor: false, align:"center", width: 53, formatter: delete_button, headerSort: false, tooltip:"Delete", cellClick: function (e, cell) {
                console.log(cell.getData());
                var _data = cell.getData();
                var budget_id = _data.budget_id;
                var base = getBaseURL();
                var request_url = base + 'rehab_budget/delete_value';
                $.ajax({
                    url: request_url,
                    type: "POST",
                    data: { id: budget_id }
                }).done(function (data) {
                    var row = cell.getRow();
                    row.delete();
                    $("#table-bln-tabulator").tabulator("setData");
                });

            }
        },
            ],
            ajaxURL: request_url,
            ajaxResponse: function (url, params, response) {

                //save property id in hidden field
                $('#prop_id').val(response[0].client_property_id);
                return response;

            },
            cellEdited: function (cell) {
                var id = cell.getRow().getIndex();
                var data = cell.getData();
                var field = cell.getColumn().getField();
                data.property_rehab_item_id = data.rehab_item;
                var base = getBaseURL();
                var request_url = base + 'rehab_budget/update_value';
                $.ajax({
                    url: request_url,
                    type: "POST",
                    data: { dbid: id, dbfield: field, dbdata: data }
                }).done(function (data) {
                    cell.getElement().addClass("success");
                });
            }
        });

```

**Comment by Paraplegix** [comment]
It appear that when you send your data to tabulator, they are stored as string  and instead of adding each number together, the top calc sum just append them together, (also the sum i count from what you copypasted is 29.509)

Do you notice the same behavior if you don't put `formatter: "money"` on your column definition ?
If the problem is still here even without `formatter: "money"`, be sure to that the `budget_amount` is a number and not a string.

Good luck :)

**Comment by wp4nuv** [comment]
I did try it without the ```formatter:"money"``` and it results in the same value.  I also checked on a column formatted by "money" and the bottomCalc also shows what seems to be a concatenated value. ```budget_amount``` is stored in the database as a decimal.. I'll try forcing the number typesetting on table load and report back.

**Comment by wp4nuv** [comment]
That helped!  Forcing the integer cast on data collection fixes the issue on initial page load... This column is editable, so when editing it appears to revert to string.  Looks like I'll have to use a custom editor instead. Thanks for the tip!

**Comment by olifolkerd** [comment]
hey @Paraplegix  was on the right track, but i would suggest one small tweak.

If you use mutators to change the type of the data as it enters the table it will work for both the initial data and user edited data. checkout the [Mutators Documentation](http://olifolkerd.github.io/tabulator/docs/3.2/#get-set) for more info.

On a side note i can see this being a problem for others so in the patch release this weekend i will make the sum and other maths calculations do this casting for you, and will add a new concat calc that is designed for joining strings.

Thanks for the feedback!

**Comment by olifolkerd** [comment]
Version 3.2.1 has just been released, it now casts all values to numbers before summing them.

There is also a new ***concat*** calculation incase you want to join strings togeather
