### ISSUE TITLE
resize columns

### ISSUE THREAD

**Issue by kurtknippschild** [olifolkerd/tabulator#481]
Hi Oli,

first, thanks for your help with the cellClick.

I have in the Old-Version a Table with a groupHeader function and the resize do not work.

Here the code:
```js
//resize columns to match group columns
setTimeout(function(){ //allow elements to be rendered before calculating widths
    $("[data-field=benutzername]", groupHeader).css("width", $("#tabulator_user .tabulator-cell[data-field=at_typ]:first").outerWidth()
    + $("#tabulator_user .tabulator-cell[data-field=anrede]:first").outerWidth() + 2);
				
    $("[data-field=organisation]", groupHeader).css("width", $("#tabulator_user .tabulator-cell[data-field=firmenname]:first").outerWidth()
    + $("#tabulator_user .tabulator-cell[data-field=vorname]:first").outerWidth());
				
    $("[data-field=angelegt]", groupHeader).css("width", $("#tabulator_user .tabulator-cell[data-field=nachname]:first").outerWidth());
				
    $("[data-field=letzte]", groupHeader).css("width", $("#tabulator_user .tabulator-cell[data-field=telefon]:first").outerWidth());
}, 300)
```
What is wrong?

Thanks in advance.

VG Kurt

**Comment by olifolkerd** [comment]
Hey,

Without the first part of the function it is tricky to tell how your function should be working as i cant see the arguments you are passing in to the function.

What i would say is that the argument lists have changed for pretty much ***all*** callbacks from the 3.0 release onwards so i would have a read of the documentation to see what the new arguments are.

here is the new structure for the ***groupHeader*** callback:
```js
groupHeader:function(value, count, data){
    //value - the value all members of this group share
    //count - the number of rows in this group
    //data - an arrya of all the row data objects in this group

    return value + "<span style='color:#d00; margin-left:10px;'>(" + count + " item)</span>";
},
```

Let me know if that helps

Cheers

Oli

**Comment by kurtknippschild** [comment]
Hi Oli,

in the old-version the user table looks like so:

![bildschirmfoto 2017-07-27 um 07 12 26](https://user-images.githubusercontent.com/22855656/28655565-05d14144-729d-11e7-9e32-c4b906f660d4.png)

With the Version 3.2. the is one problem the resize and the other problem ist the group header.
Here are the example files
[aktivitaeten_tabulator_v3.2.zip](https://github.com/olifolkerd/tabulator/files/1178906/aktivitaeten_tabulator_v3.2.zip)
.

Can you help me.

Thanks in advance.

VG Kurt

**Comment by olifolkerd** [comment]
In adition to the changes i outlined above, you want to change the ***data-field*** selectors to ***tabulator-field*** selectors in your code snippet

**Comment by kurtknippschild** [comment]
Hi Oli,
 thanks for the info.
It works, but only when groupStartOpen:true,.
In my Example groupStartOpen:false,.

Ist there a way that can i do this?

I have on the Example another Problem.
The hight of the Group Header.
Look at the Screenshot:
![bildschirmfoto 2017-08-04 um 08 27 05](https://user-images.githubusercontent.com/22855656/28956879-89b0d7b0-78ef-11e7-9b09-58d5c39da2cc.png)

Here is the example with the changes of tabulator-field.
[aktivitaeten_tabulator_v3.2.zip](https://github.com/olifolkerd/tabulator/files/1199419/aktivitaeten_tabulator_v3.2.zip)

Can you help me.

Thanks in advance.

VG Kurt

**Comment by kurtknippschild** [comment]
Hi Oli,

i added this at the end of the script:
		$('.tabulator-col.tabulator-col-group').css('height','46px');
		$('.tabulator-col.tabulator-col-group').css('display','inline-block');

Now the table-header looks like so:
![bildschirmfoto 2017-08-23 um 08 30 56](https://user-images.githubusercontent.com/22855656/29601908-2c59bbce-87de-11e7-8392-6cb49c887fe0.png)

For the moment i have no other idea.
The last two columns too high, she must have a height of 23px.

Do you have a better idea?

Thanks in advance.

Kurt
