### ISSUE TITLE
Cell click callback 

### ISSUE THREAD

**Issue by tbhuy** [olifolkerd/tabulator#482]
Hello,
I would like to add a cell click callback to the tabular. 
- But according to the guide (http://olifolkerd.github.io/tabulator/quickstart/3.2/), we must use row.getData().id, the code does not work (and  either the guide).
- According to the examples (http://olifolkerd.github.io/tabulator/examples/3.2/), we must use row.getIndex(), the example works but my code does not
- Here is how my code look like:
$("#example-table").tabulator({
    height:205, // set height of table
    fitColumns:true, //fit columns to width of table (optional)
    columns:[ //Define Table Columns
      ....
    ],
    rowClick:function(e, row){ //trigger an alert message when the row is clicked
        alert("Row " + row.getData().id + " Clicked!!!!");
    },
});
$("#example-table").tabulator("setData", "list.jsp"); // Get JSON by AJAX
I've got a "undefined" error with both of two methods.
Thanks

**Comment by olifolkerd** [comment]
Hey,

In order for this to work you muse set up the ***id*** field in your data for it to be read, otherwise it is undefined.

Is there a particular reason you need to know this, if i knew what your end goal was i could suggest a possible solution.

Cheers

Oli
