### ISSUE TITLE
Sorting only rows, not groups

### ISSUE THREAD

**Issue by Lazaroth** [olifolkerd/tabulator#483]
Hi,

Is it possible to sort only the rows in a group, and not the groups themselves?

For example:
In your example "grouping data", clicking progress also makes male and female switch places. I would like them to stay, but the content in the groups to sort themselves.

Best regards!

**Comment by olifolkerd** [comment]
Tabulator sorts the data before it is groups so there is no specific setting for achieving this.

However you are in luck, there is a workaround that will get you the functionality you want. 
By binding to the ***headerClick*** event you can trigger a specific sort on the table, sorting by gender then the column that has been clicked on.

In the example below i assume that you want to group by the gender column, and that it is initially sorted in ascending order,

```js
//click binding to for sort order
sortWithFixedGroup = function(e, column){
	var dir = "asc";

	$("#example-table").tabulator("getSort").forEach(function(sort){
		if( column.getField() == sort.column.getField()){
			dir = sort.dir;
		}
	})

	$("#example-table").tabulator("setSort",[
		{column:"gender", dir:"asc"},
		{column:column, dir:dir}
	]);
}

//build table
$("#example-table").tabulator({
    initialSort:[
	{column:"gender", dir:"asc"},
    ],
    groupBy:"gender",
    columns:[
        {title:"Gender", field:"gender"},
        {title:"Name", field:"name", headerClick:sortWithFixedGroup),
        {title:"Age", field:"age", headerClick:sortWithFixedGroup),
    ]
});

The only side effect of this is that the ***dataSorting*** and ***dataSorted*** callbacks will be called twice for each header click, because it actually carries out the initial sort, then the header click triggers the sort you want. That shouldnt be a problem in most situations. if it is i can give you a way to deal with that too.

Let me know if that helps you out.

Cheers

Oli

**Comment by Lazaroth** [comment]
Works like a charm.

Thank you for a quick answer and solution! :)

**Comment by Lazaroth** [comment]
Actually, there is a problem. I have 3 groups; "Annonser", "Kuponger" and "Banners". However, only "Annonser" stays in place, the other 2 still switches. Could it be a bug?

dir is set to "asc" for the column
`$(table).tabulator('setSort',
		[
			{column: 'catname', dir: 'asc'},
			{column: column, dir: dir}
		]);`

**Comment by Lazaroth** [comment]
Another thing:
I'm also not able to use initialSort with multiple values. If I use 2 (group first, group row second), the first one (group) is ignored.

**Comment by olifolkerd** [comment]
Hey.

Try swapping the order of the two sorters in both the initialSort and the headerClick function

**Comment by Lazaroth** [comment]
That worked! :)

**Comment by Lazaroth** [comment]
I should stop answering so quickly... It worked for initialSort, but the other one is behaving strange if I flip them. If the group is open it sorts asc, if it's closed it sorts desc.

**Comment by olifolkerd** [comment]
could you post a copy of your table constructor so i have something to test against

Cheers

**Comment by Lazaroth** [comment]
Below is how it looks.
The groups (catname) is as previously mentioned "Annonser", "Kuponger" and "Banners".


```
$('.salestable').tabulator({
	groupBy: 'catname',
	headerFilterPlaceholder: 'Filtrera',
	initialSort: [
		{
			column: 'company',
			dir: 'asc'
		},
		{
			column: 'catname',
			dir: 'asc'
		}
	],
	columns:[
		{
			title: 'M',
			field: 'select',
			cssClass: 'hideHeader',
			headerSort: false,
			cellClick: function(e, cell)
			{
				cell.getRow().toggleSelect();
			},
			formatter: function(cell, formatterParams)
			{
				return '<i class="fa fa-thumb-tack" aria-hidden="true"></i>'
			}
		},
		{
			title: 'Företag',
			field: 'company',
			formatter: 'html',
			headerFilter: 'input',
			headerClick: sortWithFixedGroup
		},
		{
			title: 'R',
			field: 'edit',
			cssClass: 'hideHeader',
			headerSort: false,
			formatter: function(cell, formatterParams)
			{
				return '<a href="'+cell.getValue()+'"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>'
			}
		},
		{
			title: 'Orter',
			field: 'area',
			formatter: 'html',
			cssClass: 'orterExtra',
			editor: selectEditor
		},
		{
			title: 'Format',
			field: 'format'
		},
		{
			title: 'Grafiker',
			field: 'designer',
			headerFilter: 'input',
			editor: selectEditor
		},
		{
			title: 'Status',
			field: 'status'
		},
		{
			title: 'Pris',
			field: 'price',
			editor: 'number',
			formatter: 'money',
			formatterParams:
			{
				precision: 0,
				symbolAfter: true,
				symbol: ':-'
			},
			align: 'right'
		},
		{
			title: 'Säljare',
			field: 'seller',
			align: 'right',
			headerFilter: 'input',
			editor: selectEditor
		},
		{
			title: 'Typ',
			field: 'catname',
			visible: false
		}
	]
});
```

**Comment by Lazaroth** [comment]
Hey!

Any news regarding this?

**Comment by olifolkerd** [comment]
Hey, 

sorry for the delay in getting back to you on this.

Loooking at your code you have only applied the ***sortWithFixedGroup*** function to one column, it should be applied to all columns except the column that is being grouped by.

Do you have a copy of your version of the ***sortWithFixedGroup***  function so i can test with that as well, that is likey where the problem lies, that should its sort objects in the same order as your updated ***initialSort*** array

On a side note, i would strongly suggest setting the ***height*** option on the table, this will engage the virtual renderer and result in your table rendering much faster if it has a lot of rows.

Cheers

Oli

**Comment by Lazaroth** [comment]
Hey!

Sorry for not answering earlier. I fixed the problem. It was very simple actually. A misspelling on my part... Thank you for all your support! 👍

**Comment by rafaeldcsantos** [comment]
Hi, very impressed by your work!

I noticed that sorting is a bit complex when grouping rows.
With a table like this:

```
            {id: 1, orientador: "Rafael", orientado: "Thiago", nivel: "M", progresso: "i2015/1"},
            {id: 2, orientador: "Rafael", orientado: "Ivo", nivel: "M", progresso: "i2010/1,t2011/1,t2011/2,t2014/1,c2015/1"},
            {id: 3, orientador: "Rafael", orientado: "Amita", nivel: "M", progresso: "i2014/1"},
            {id: 4, orientador: "Rafael", orientado: "Mauro", nivel: "M", progresso: "i2015/1,t2016/2"},
            {id: 5, orientador: "Rafael", orientado: "Guilherme", nivel: "M", progresso: "i2016/2"},
            {id: 6, orientador: "Lorena", orientado: "Guilherme", nivel: "M", progresso: "i2016/2"},
            {id: 7, orientador: "Vijay", orientado: "Matheus", nivel: "M", progresso: "i2015/2,c2017/3"},
            {id: 8, orientador: "Elbert", orientado: "Barbara", nivel: "M", progresso: "i2011/1"},
            {id: 9, orientador: "Elbert", orientado: "Antonio", nivel: "M", progresso: "i2017/3"},
            {id: 10, orientador: "Margarete", orientado: "Barbara", nivel: "M", progresso: "i2011/1"},
```
and
```
           groupBy: "orientador",
                initialSort:[
                  {column:"orientador", dir:"asc"}, 
                  {column:"orientado", dir:"asc"}, 
                ],
```
The table is sorted by `orientado` inside each group, but the groups themselves are not sorted. In my example groups are defined by `orientador`, and those appear on the same order they are declared.

Is it possible to group data by a field, then sort primarily by this field then by another field inside the groups?

thanks
Rafael

**Comment by rafaeldcsantos** [comment]
I was able to solve it by sorting by `orientado` with a custom sort function:

```
                         sorter:function(a, b, aRow, bRow, column, dir, sorterParams)
                           {
                           var fa = aRow.getData().orientador+" / "+aRow.getData().orientado;
                           var fb = bRow.getData().orientador+" / "+bRow.getData().orientado;
                           return (fa.localeCompare(fb)); 
                           },    
```
Thanks!
