### ISSUE TITLE
doesn't send headerFilters in ajax request

### ISSUE THREAD

**Issue by milenip** [olifolkerd/tabulator#484]
Hi Oli
I don't see filters rows and data in POST request
My configuration
```
        $("#example-table").tabulator({
            fitColumns: true,
            ajaxURL: "/reader",
            ajaxConfig: {
                type: "POST",
            },
            pagination: "remote",
            paginationSize: 30,
            ajaxSorting: true,
            ajaxFiltering: true,
            selectable: 1,
            columns:[
                {title:"Subject", field:"subject", sorter:"string", headerFilter:true},
                {title:"From", field:"from", align:"center", width:550},
            ],
        });
```

request variables in server
```
page 1
size 30
```

sortable is work
```
page 1
size 30
sort subject
sort_dir asc
```

filtering not work
**
tabulator v.3.2.0
jquery v.3.2.1
jquery-ui v.1.12.1
**

**Comment by olifolkerd** [comment]
how are you triggering the filter?

**Comment by milenip** [comment]
> how are you triggering the filter?

typing text into input field

![field](https://user-images.githubusercontent.com/30477673/28642435-b20ea29e-7252-11e7-9b64-0c879aa32a83.png)

**Comment by olifolkerd** [comment]
At the moment only the first programmatic filter is sent over ajax, and header filters are not.

in next months 3.3 release all filters and sorts will be sent over ajax

**Comment by milenip** [comment]
what is **first programming filter?**
is it here [http://olifolkerd.github.io/tabulator/examples/3.2/#filter](http://olifolkerd.github.io/tabulator/examples/3.2/#filter)?

Oli, thank you for you help

**Comment by milenip** [comment]
**mistake** [L:12051 C:21-22](https://github.com/olifolkerd/tabulator/blob/master/dist/js/tabulator.js#L12051)

**Comment by olifolkerd** [comment]
The first programmatic filter is the first one set using the ***setFilter*** or ***addFilter*** function.

Im afraid i don't see any error on the line you are referring to, if you think there is an error could you post a copy of the line as it is and what you think it should be and why. That would be a great help.

Thanks

Oli

**Comment by milenip** [comment]
```
@@ -12048,7 +12048,7 @@
 
       "filter_value": "filter_value",
 
-      "filter_type": "fitler_type"
+      "filter_type": "filter_type"
 
     };
```

"filter_type": "fi**t**ler_type"

**Comment by olifolkerd** [comment]
Brilliant stuff!! I Couldn't see that!

I have just pushed a fix to the master branch, it will be included in this weekends patch release.

Give me a shout if you find any other bugs.

Cheers

Oli
