### ISSUE TITLE
Custom Header Sort Issue

### ISSUE THREAD

**Issue by azizur-rahman** [olifolkerd/tabulator#485]
I have two fields as **PickupDate & PickupTime**. 
When I click on the column hear of PickupDate then sort will be work on both (**PickupDate & PickupTime**). OR will be work on another third field.

**HOW CAN I DO THIS?**
PLEASE HELP WITH SAMPLE CODE THAT IS VERY MUCH HELPFUL FOR ME.

CHEERS
AZIZUR

**Comment by olifolkerd** [comment]
Hey Azizur,

Thanks for getting in touch, i have already asked you kindly to stop posting your issues in all capital letters, it is not appropriate, and will not lead to your issues getting solved any faster. if you continue doing this i will take action to ban you from the issue list as this is a place where all users are treated fairly and evenly.

That being said i have just posted a similar solution on issue #483.

I am heading to work now but will post a custom answer for your usage case when i am back.

Cheers

Oli

**Comment by Paraplegix** [comment]
Hey,

It might help if you provide additional information like : 
- Format of PickupDate and PickupTime : is it dd-MM-yyyy and HH:mm:ss , or timestamps, just using a number with a formatter)
- More informaiton on the  third field as what is it ? a number, a name. And also in what case would you do the sorting on this field and not PickupDate and Time ?

**Comment by olifolkerd** [comment]
Here is a solution to your issue:

By binding to the ***headerClick*** event you can trigger a specific sort on the table, that will override the default behavior.

```js
//click binding to for sort order
datetimeSort= function(e, column){
	var dir = "asc";

	$("#example-table").tabulator("getSort").forEach(function(sort){
		if( column.getField() == sort.column.getField()){
			dir = sort.dir;
		}
	})

	$("#example-table").tabulator("setSort",[
		{column:"PickupDate", dir:dir},
		{column:"PickupTime", dir:dir},
	]);
}

//build table
$("#example-table").tabulator({
    columns:[
        {title:"Date", field:"PickupDate", sorter:"date", headerClick:datetimeSort),
        {title:"Time", field:"PickupTime", sorter:"time", headerClick:datetimeSort),
    ]
});
```

Let me know if that helps,

Cheers

Oli

**Comment by azizur-rahman** [comment]
Hey Oli,
It does not work properly. It's working only 'asc' order. But I need to  sort by  'asc' and 'desc' order.

Please reply with proper solution

Cheers
Azizur

**Comment by olifolkerd** [comment]
Appologies, there was a issue with the code, i have updated the example,

You will notice i have swapped the order of the sorts, and added the new ***currentSort*** variable outside the function.

Cheers

Oli

**Comment by rasadulalam** [comment]
Date is shorting but time is not changing.

**Comment by azizur-rahman** [comment]
This is not working for multi-column sorting till now.
Please help with reply

Cheers

**Comment by azizur-rahman** [comment]
Hi !
Any news about this ....

**Comment by olifolkerd** [comment]
please post a copy of your not working code

**Comment by azizur-rahman** [comment]
`//hold current sort direction
var currentSort = "desc";
//click binding to for sort order
datetimeSort = function (e, column) {
    var newso = currentSort;
    currentSort = currentSort == "asc" ? "desc" : "asc";
    var colName = column.getField();    
        $("#dvDisTbl").tabulator("setSort", [
            { column: colName.toString(), dir: currentSort.toString() },
            { column: "ReqDate", dir: currentSort.toString() }
        ]);   
}

// Tabulator Builder
function ReAll(ConsiderDate, fIndex) {
    var Date_Time = "";
    var Start_Date = "";
    var End_Date = "";
    var Others = "";
    if (fIndex != "") {
        Others = fIndex;
    }

    if (ConsiderDate == "Y") {
        if (typeof (Storage) !== "undefined") {
            Start_Date = sessionStorage.StartDate != undefined ? sessionStorage.StartDate : "";
            End_Date = sessionStorage.EndDate != undefined ? sessionStorage.EndDate : "";
        }
        else {
            Start_Date = $("#ReqStartDate").val();
            End_Date = $("#ReqEndDate").val();
        }
    }
    if (Start_Date != "" && End_Date != "") {
        Date_Time = "'" + Start_Date + "' AND '" + End_Date + "'";
    }

    var GoFor = "";
    var ReqFor = "";
    GoFor = $(':radio[name=ArcType]:checked').val();
    ReqFor = $(':radio[name=rdoCompany]:checked').val();
    var url = "/EventReq/ReAll/?gf=" + GoFor + '&reqfor=' + ReqFor + '&dt=' + Date_Time + '&oth=' + Others;

    var oTabulator = $("#dvDisTbl");

    //Build Tabulator
    oTabulator.tabulator({
        height: '200px',
        fitColumns: true,
        pagination: "local",
        paginationSize: 200,
        movableColumns: true,
        responsiveLayout: true,
        resizableColumns: true,
        tooltips: true,
        selectable: 1,
        initialSort: [
            { column: "ISL", dir: "asc" },
        ],
        renderComplete: function () {
            TotalData();
        },
        columns: [
            { title: "Req #", field: "EventReqID", align: "center" },
            { title: "For", field: "ReqFor", align: "center"},
            { title: "Svc Area", field: "ServiceArea", sorter: "string", headerSort: false, headerClick: datetimeSort},
            {
                title: "Req Date", field: "ReqDate", align: "center", formatter: customDate, tooltip: customDate, headerClick: datetimeSort
            },
            {
                title: "Req Time", field: "ReqTime", align: "center",sorter: "time", formatter: customTime, tooltip: customTime, headerClick: datetimeSort
            },
            { title: "Name", field: "Name"},
            { title: "Company", field: "Company" },
            { title: "Phone", field: "Phone", headerSort: false },
            { title: "Start Date", field: "StartDate", align: "center",  formatter: customDate, tooltip: customDate },
            { title: "End Date", field: "EndDate", align: "center",  formatter: customDate, tooltip: customDate },
            { title: "Budget", field: "Budget", align: "right", formatter: addCommaSeparateNumberLink },
            { title: "Svc Note", field: "SvcNotes", headerSort: false, formatter: addSvcNotesLink },
            { title: "Attch", field: "FileAtt", headerSort: false },
            { title: "Due Date", field: "DueDate", align: "center", sorter: "date", formatter: customDate, tooltip: customDate, formatter: customDate, tooltip: customDate },
            { title: "Status", field: "Status" },
            { title: "Claimed By", field: "ClaimedUser" },
            { title: "Ref Emp", field: "ReferralEmp" },
            { title: "Ref Com", field: "ReferralCom" }
            { title: "SL", field: "ISL", sorter: "number", hideColumn: true } 
        ],

        rowSelected: function (data, row) {
            $('#ReqID').val(data.getData().EventReqID);
            $('#IsArc').val(data.getData().IsArc);
        },
        rowDeselected: function (data, row) {
            $('#ReqID').val('');
            $('#IsArc').val('');
        },
        rowDblClick: function (data, row) {
            $('#ReqID').val(row.getData().EventReqID);
            $('#IsArc').val(row.getData().IsArc);
            ViewEventReq();
        }
    });
//trigger download of data.csv file
    $("#btnDownload").click(function () {
        $("#dvDisTbl").tabulator("download", "csv", "data.csv");
    });

    //Set Data
    oTabulator.tabulator("setData", url, ajaxConfig);

    //Set initial page
    oTabulator.tabulator("setPage", 1);

    //hide Column
    oTabulator.tabulator("hideColumn", "ISL");


    //Searching
    $("#mySearch").on("keyup", function () {

        var term = $(this).val().toLowerCase();

        if (term.length >= 3) {
            oTabulator.tabulator("setFilter", function (data) {
                return data.EventReqID.toString().toLowerCase().indexOf(term) > -1
                    || data.ServiceArea.toLowerCase().indexOf(term) > -1
                    || data.Name.toLowerCase().indexOf(term) > -1
                    || data.Company.toLowerCase().indexOf(term) > -1
                    || data.ClaimedUser.toLowerCase().indexOf(term) > -1
                    || data.ReferralEmp.toLowerCase().indexOf(term) > -1
                    || data.ReferralCom.toLowerCase().indexOf(term) > -1;
            });
        } else {
            oTabulator.tabulator("clearFilter");
        }

    });

    function TotalData() {
        $('.tabulator-footer #totalRow').remove();
        if (oTabulator.tabulator("getDataCount") > 0) {           
            $('.tabulator-paginator').before('<span id="totalRow" class="pull-left"> Total: ' + oTabulator.tabulator("getDataCount") + '</span>');
        }
        else {
            $('.tabulator-paginator').before('<span id="totalRow" class="pull-left"> Total: 0</span>');
        }
    }
}

`

**Comment by azizur-rahman** [comment]
Do you have any update ?
Please reply..
Cheers

**Comment by how2talk** [comment]
Hi, I have been looking for a software that works like tabulator for many many months, and I am so happy to have found it. I am a self-taught html user and do not know programming. As I am not a developer, I have problem integrating tabulator into cpanel and my website. I do not understand the installation steps on tabulator.info, as I do not know how to install bower or npm. Can someone extend a helping hand to me? Thanks, Michelle
