### ISSUE TITLE
Issue to print and export to pdf tabulator and export csv file

### ISSUE THREAD

**Issue by minalkArmstrong** [olifolkerd/tabulator#486]
![test1](https://user-images.githubusercontent.com/24350278/28661172-6f8bd8fc-72d3-11e7-85aa-1d3f57cb8676.PNG)
![test2](https://user-images.githubusercontent.com/24350278/28661177-75da7704-72d3-11e7-89c7-d5d61f761647.PNG)

**I am trying to print this this tabulator table but in print it look like mentioned in second screenshot.**

>  var print = document.getElementById("stckplantable").innerHTML;         
            var WinPrint = window.open('', '','left=0,top=0,width=0,height=0,toolbar=0,scrollbars=0,status=0');
            WinPrint.document.write(print);
            WinPrint.document.close();
            WinPrint.focus();
            WinPrint.print();
            return false;
            WinPrint.close();

I am using abouve code to print tabulator.

**And At time of export table to csv to display hiddden fields also**
![209025 13](https://user-images.githubusercontent.com/24350278/28661342-f58fc0b2-72d3-11e7-87d3-0be87a0861ed.png)

>  columns: [
                    { title: "Product Name", field: "ProdCode", sorter: "string", align: "left",  headerFilter: "input",width:180 },
                    { title: "Description", field: "ProdDesc", sorter: "string", headerFilter: "input",width:260 },
                    { title: "GRN No.", field: "GRNNo", sorter: "number", align: "left", visible:false },
                    { title: "GRN Qty.", field: "GRNQty", sorter: "string", visible: true, headerFilter: "input", width: 80 },
                    { title: "ASRS Stock Qty.", field: "StckQty", sorter: "string", editor: "input", headerFilter: "input", visible: true, width: 80 },
                    { title: "GRN Date", field: "GRNDate", sorter: "string", align: "left", visible:false },
                    { title: "ProjCode", field: "ProjCode", sorter: "number", align: "left",visible: false },
                    { title: "UOM", field: "StdUOM", sorter: "string", headerFilter: "input", width: 80 },
                    { title: "ProdID", field: "ProdID", visible: false, download: false },
                    { title: "GRNID", field: "GRNID", visible: false, download: false },
                       { title: "SpPartID", field: "ID", visible: false, download:false },
                ],

**Comment by Paraplegix** [comment]
For the printing issue, looks like you are loosing the css when exporting, if the aspect of the table isn't an absolute requirement for you, you could checkout #479, maybe using classic `<table>` tags
Might not be the perfect solution but can be the beginning of a workaround

Never have played with printing webpage so its just a though : Try adding html, head and body tag to the document you are creating for exporting your table. Put the table div into the body, and in the head, you copy paste all the css and style code.

As for the csv download, that is strange, check the source code and it is checking for `download:false` so i have no idea why, this should work with lastest version of tabulator.

**Comment by olifolkerd** [comment]
That is Happening because you are only passing the html to your print window, not the CSS as @Paraplegix  says, so it cannot style the table appropriatly.

These days it is considered better practice to use css media queries with the ***@media print*** tags set on the actual page, rather than opening a new window to print a a document, it leads to a better user experience. More info on this can be found [here](https://www.smashingmagazine.com/2011/11/how-to-set-up-a-print-style-sheet/).

With regards to the hidden columns showing, you just need to set the ***download:false*** property in the hidden columns definitions (you will need to be using Tabulator 3.2 for this function):
```js
$("#example-table").tabulator({
    columns:[
        {title:"Hidden Column", field:"secret", download:false} //hide data in download
    ]
});
```

I hope that clears things up.

Cheers

Oli

**Comment by minalkArmstrong** [comment]
The code given in  #479 is working absolutely fine .It resolve my problem  Thank you for your support.

**Comment by jamesmstone** [comment]
I noticed print styling has been added to the roadmap. I was just wondering what you had planned for this. This is a feature that I (depending on how it works) would be interested in.  And potentially, would be able to help develop it for tabulator, rather than just for my project.

**Comment by olifolkerd** [comment]
Hey @jamesmstone,

Thanks for your interest :)

The print styling will allow the table to be printed in its own page with a ***print*** command:
```js
$("#example-table").tabulator("print");
```

if you want to add your own table styles for when the table is printed as part of a page i would suggest using the ```@media print``` CSS query.

Cheers

Oli
