### ISSUE TITLE
Documentation: Tabulator cloudflare link is incorrect

### ISSUE THREAD

**Issue by corgidesu** [olifolkerd/tabulator#488]
The Cloudflare link for Tabulator CSS and JS files are incorrect.

Current values from http://olifolkerd.github.io/tabulator/docs/3.2/ is:
https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.2/css/tabulator.min.css
https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.2/js/tabulator.min.js

But should be changed to
https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.2.0/css/tabulator.min.css
https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.2.0/js/tabulator.min.js

**Comment by olifolkerd** [comment]
Great spot! i have just pushed an update to the site.

Thanks for the headsup!

**Comment by corgidesu** [comment]
Wow that's some really quick response times, will check it out thank you

**Comment by corgidesu** [comment]
Yup its perfect
Fixed
