### ISSUE TITLE
Data validation

### ISSUE THREAD

**Issue by markomijat** [olifolkerd/tabulator#489]
Hello,

Thank you for sharing your work ! I'm pretty new to JavaScript, so my opinion on the actual code is not very relevant, although I can say that using your libraries seems to be easy and the results I got so far are beautiful. I'd like to ask you two, probably pretty basic questions :  
1) Can  you give me a simple example on data validation ? ie. I want my cell to keep the focus and/or change font color if the user enters a string for a numeric value and so on. I could do it on the server side but I prefer checking it on the front-end.
2) I'd like to have a cell with a dropdown list populated from a database with some ajax for auto-complete if possible. Can you point me to any examples for achieving this within the tabulator? 

Thanks !

**Comment by olifolkerd** [comment]
Hey,

Thanks for getting in touch.

### Validation
There is no in-built validation function in Tabulator at the moment, but the good news is it will be coming in the 3.3 release next month.

In the mean time you can use a custom formatter to highlight the cell in the event the value doesn't match the expected input, for example:
```js
//validation formatter
function validateNumber(cell, formatterParams){
    //cell - the cell component
    //formatterParams - parameters set for the column

    var value = cell.getValue();

    if(isNaN(value)){
        cell.getElement().css({"background-color":"red"});
    }

    return value ; //return the contents of the cell;
}



//table constructor
$("#example-table").tabulator({
    columns:[
        {title:"Age", field:"age", editor:"number", formatter:validateNumber),
    ]
});
```
### Custom Editor
You can use a custom ***editor*** to add any functionality you like, have a look at the [Editing & Manipulating Data Documentation](http://olifolkerd.github.io/tabulator/docs/#manipulating-data) for examples of how to create your own editor.

There is an example of a custom select dropdown in the documentation that you could adapt to load its options over ajax, or you could creating a custom editor using the jQuery [Autocomplete Widget](https://jqueryui.com/autocomplete/)

Let me know if that helps

Cheers

Oli

**Comment by markomijat** [comment]
Thanks a lot for your swift response ! I pretty much used the formatters for my project. 
You've done some really good job with the validation in the new version !
Thanks  !
