### ISSUE TITLE
Filter data in header

### ISSUE THREAD

**Issue by tranquochuy29** [olifolkerd/tabulator#49]
Hi there,

Hope you're still fine.
Wish you have a good day.

I found out an issue during working with tabulator.
The problem comes from 'Filter data in header'.
So here is my step.

Following your example,
Step 1 : I resize the column width to make it bigger  (the scroll-bar will appear).
Step 2 : I scroll to the right. Because I would like to filter based on 'Date of birthday'
Step 3 : I type '14' and then I have a broken html.
You can have a check for the attachment
![step1](https://cloud.githubusercontent.com/assets/4382757/17765575/f3e02248-6550-11e6-9946-46ffa691ec7d.png)
![step2](https://cloud.githubusercontent.com/assets/4382757/17765576/f3e7a0a4-6550-11e6-958c-6b133a60ede1.png)

Could we keep the state of scroll after filtering ?
I mean that everything I type something for filtering based on the 'Date of birthday'.
The scroll is alway back to the left. I have to scroll to the right to change the text-search.
It would be better it we can keep the state of scroll. Because it's not good for user's experience.

Thank you so much.

Cheer,
Tony

**Comment by olifolkerd** [comment]
Hi tony.

I can certainly maintain the horizontal scroll position.

I will get an update in the next few days.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hi tony,

I have uploaded a fix for this, horizontal scroll position will now be maintained whenever a table is redrawn.

let me know if you are still having that graphical glitch and i will reopen the issue.

cheers
