### ISSUE TITLE
Problem with call function in dataLoaded and cellClick

### ISSUE THREAD

**Issue by neorm5** [olifolkerd/tabulator#491]
Hi, 
I develop a program in J2ee with 50 tables diferents. I need load the definition of table and columns dynamically with JSON. The data of table is in other JSON and work.
The problem with the JSON of the definition and columns because the functions in dataLoaded and cellClick dont work. I cant call this functions.
I think that when i create the json dataloaded converter to string...
The code have modification for the privacy.
I do a ajax with this:

`               $.ajax({
						url : 'www.url.net/url',
						type : 'POST',
						data : {
							key : "init",
							table : "1",
						},
						success : function(table) {
						 $("#table1").tabulator(table); //request of definition and columns in JSON
						 $("#table1").tabulator("setData", "'www.url.net/url", {
									key : "1",
								}, "POST");
						},
						error : function(table) {
							console.log("error" + (table));
						}
					});
				});`
Servlet:
`if (request.getParameter("key").equals("init")) {
			JsonObject config = new JsonObject();
			config.addProperty("height", "523px");		
			config.addProperty("dataLoaded",	"function(data){alert(\"f\");}";
			JsonObject fila = new JsonObject();
			String [] col =...
			JsonArray datasets = new JsonArray();
			String[] fields =...;
			if (col.length > 0) {
				for (int i = 0; i < col.length; i++) {
					fila = new JsonObject();
					fila.addProperty("title", col[i]);
					fila.addProperty("field", fields[i]);
					fila.addProperty("cellClick", "cellClickFunction");
					fila.addProperty("sorter", "string");
					fila.addProperty("headerFilter", "input");
					datasets.add(fila);
				}
				config.add("columns", datasets);
			}
			Gson gson = new GsonBuilder().setPrettyPrinting().serializeNulls()
					.disableHtmlEscaping()
					.setFieldNamingPolicy(FieldNamingPolicy.UPPER_CAMEL_CASE)
					.create();
			response.getWriter().write(gson.toJson(config));`

JSP
`<script>
var cellClickFunction = function(e, cell) {
						var val = cell.getRow().getCell("id").getValue();
                                                alert(val);
}
</script>`

Output
`	$("#table1).tabulator({
  "height": "523px",
  "dataLoaded":"function(data){alert("f");},"
  columns: [
    {
      "title": "ID",
      "field": "id",
      cellClick: cellClickFunction,
      "sorter": "string",
      "headerFilter": "input"
    },
....
  ]
});`
The code work but never run the dataloaded function and dont do anything when I click.

Thanks for the support and great library and updates
PD: I used the 3.2 version of tabulator

Thanks

**Comment by olifolkerd** [comment]
Hey,

Thanks for getting in touch, 

The issue you have is your are passing your ***dataLoaded*** function in quotation marks so it is being passed as a string not a function, and therefore cannot be executed.

If you remove the quotes around the function literal you should be all good.

Let me know if that helps.

Cheers

Oli
