### ISSUE TITLE
Group Headers "clickable" and displays multiple data

### ISSUE THREAD

**Issue by tcox1111** [olifolkerd/tabulator#492]
I was curious if anyone can help me with an issue I cannot seem to solve. I am attempting to create a table that has grouped rows of data and that data being grouped by one field, but I want other data, such as the sum of amounts of money to also be displayed on the same group header row. The sums of money are derived from the information given in the rows under the group. I do not want to create subgroups. I am also curious as to if the group header rows can be made clickable so as to open the containing rows of data. Any and all advice would be greatly appreciated. Thank you.

**Comment by tcox1111** [comment]
topCalc: "sum", no longer showing. Pops up when a group is open and I sort the group by a field and then stays when I close the group, but is not around otherwise.

**Comment by olifolkerd** [comment]
hey,

Could you post a copy of your Tabulator constructor object.

Cheers

Oli

**Comment by tcox1111** [comment]
`    <div id="UcrTable"></div>

    <script>

        var sortWithFixedGroup = function (e, column) {
            var dir = "asc";

            $("#UcrTable").tabulator("getSort").forEach(function (sort) {
                if (column.getField() == sort.column.getField()) {
                    dir = sort.dir;
                }
            })

            $("#UcrTable").tabulator("setSort", [
                { column: column, dir: dir },
                { column: "statementDate", dir: "asc" }

            ]);
        }
        
        var formatDate = function (cell, formatterParams) {
            var date = new Date(cell.getValue());
            return date.getFullYear() + "/" + date.getMonth() + "/" + date.getDate();

        }


        $("#UcrTable").tabulator({
            ajaxURL: "/Reports/Agency/UnearnedCommissions/data",
            initialSort: [
                { column: "statementDate", dir: "asc" },
            ],
            selectable: 1,
            responsiveLayout: true,
            fitColumns: true,
            groupBy: "statementDate",
            groupHeader: function (value, count, data) {
                var date = new Date(value);
                return date.getFullYear() + "/" + date.getMonth() + "/" + date.getDate() + "<span style='color:#d00; margin-left:10px;'>(" + count + " item)</span>";
            },
            groupStartOpen: false,
            placeholder: "No Data Set",
            columns: [
                { title: "Statement Date", field: "statementDate", align: "center", responsive: 0, formatter: formatDate },
                { title: "Contract", field: "contract", align: "center", responsive: 0, headerClick: sortWithFixedGroup },
                { title: "Start Date", field: "startDate", align: "center", responsive: 0, formatter: formatDate, headerClick: sortWithFixedGroup },
                { title: "End Date", field: "endDate", align: "center", responsive: 0, formatter: formatDate, headerClick: sortWithFixedGroup },
                { title: "Paid To Date", field: "ptd", align: "center", responsive: 0, formatter: formatDate, headerClick: sortWithFixedGroup },
                { title: "Premium Amount", field: "pamount", formatter: "money", formatterParams: { symbol: "$" }, align: "right", responsive: 0, headerClick: sortWithFixedGroup, topCalc: "sum", topCalcParams: { precision: 2 }, },
                { title: "Commission Rate", field: "crate", formatter: "money", formatterParams: { symbol: "$" }, align: "right", responsive: 0, headerClick: sortWithFixedGroup,  topCalc: "sum", topCalcParams: { precision: 2 },},
                { title: "Commission Amount", field: "camount", formatter: "money", formatterParams: { symbol: "$" }, align: "right", responsive: 0,  headerClick: sortWithFixedGroup },
                { title: "Unearned Amount", field: "uamount", formatter: "money", formatterParams: { symbol: "$" }, align: "right", responsive: 0, headerClick: sortWithFixedGroup,  topCalc: "sum", topCalcParams: { precision: 2 },}
            ],
        },
        );

        $(window).resize(function () {
            $("#UcrTable").tabulator("redraw");
        });

    </script>`

**Comment by olifolkerd** [comment]
Thanks for posting that,

First of i would say you should probably be setting a table ***height*** so that the virtual renderer is used, without a height the virtual rendered wont be used and it will dramatically slow down your table rendering speed.

To answer your questions:

### Other values in group header
The ***data*** argument that is pass into the row formatter contains all the row data for that group so you could calculate sums of that data by iterating through the array, for example:
```js
 groupHeader: function (value, count, data) {
     var date = new Date(value);
     var paidToDate = 0;

    data.forEach(function(rowData){
        paidToDate += rowData.ptd;
    });      
         
    return date.getFullYear() + "/" + date.getMonth() + "/" + date.getDate() + " - PTD:" + paidToDate + "<span style='color:#d00; margin-left:10px;'>(" + count + " item)</span>";
},
```

### Clickable Group Headers
There is no simple way to do this at the moment, but i will add the feature in the 3.5 release at the end of the month. in the mean time you could use the ***dataGrouped*** callback in your table definition to do this for you:

```js
$("#example-table").tabulator({
    dataGrouped:function(groups){
        //groups - array of top level group components

        groups.forEach(function(group){
            group.getElement().onClick(function(e){
                group.toggle();
            });
        });
    },
});
```

### Hidden Column Calculations
It is expected behaviour that when you close a group its column calculations are hidden too

### Row Background Colours
Tabulator applies the ***.tabulator-row-odd*** and ***.tabulator-row-even*** classes to alternating rows to add the stripey styling. you can easily override these by adding your own styling for the classes:

```css
.tabulator .tabulator-tableHolder .tabulator-table .tabulator-row.tabulator-row-odd,
.tabulator .tabulator-tableHolder .tabulator-table .tabulator-row.tabulator-row-even{
    background-color:#fff !important;
}
```

## Resize issues
try passing ***true*** in the optional second parameter to the redraw function:
```js
$("#UcrTable").tabulator("redraw", true);
```

Let me know if that helps

Cheers

Oli

**Comment by tcox1111** [comment]
Thank you for responding in such a timely manner. I will let you know if it works when I implement what you have suggested. Another note, the column calculations are not only hidden when the rows are closed, they are not visible at all until I do a column sort. And after i do a column sort, they will not go away unless i refresh the page, even if I close the group. The issue with the alternating rows is that they are no longer alternating. I haven't changed anything but the rows are now all white. This is also fixed upon clicking to sort the columns. And again, thank you for your help.

**Comment by tcox1111** [comment]
When implementing the Clickable group headers I get this error: Uncaught TypeError: group.getElement(...).onClick is not a function. Every other suggestion has worked though. Thank you. The column calculations and the rows are also fixed. I do not know what did it, but I probably did not have something set right. Now my only issue is the column calculations, even though formatter is set to money and topCalcParams is set to a precision of two, they have alot of zeros after them. Thank you for all your help.

**Comment by olifolkerd** [comment]
Sorry about that there was a typo there, it should be ```group.getElement().on("click", function(e){``` i have updated the example accordingly.

could you post a copy of your table constructor object so i can test the calculation result myself.

cheers

oli

**Comment by tcox1111** [comment]
Attached is a copy of my table constructor. Also, the clickable headers works like a charm! Thank you so much for everything, Oli.

`<script>

        var sortWithFixedGroup = function (e, column) {
            var dir = "dsc";

            $("#UcrTable").tabulator("getSort").forEach(function (sort) {
                if (column.getField() == sort.column.getField()) {
                    dir = sort.dir;
                }
            })

            $("#UcrTable").tabulator("setSort", [
                { column: column, dir: dir },
                { column: "statementDate", dir: "dsc" }

            ]);
        }

        var formatDate = function (cell, formatterParams) {
            var date = new Date(cell.getValue());
            return date.getFullYear() + "/" + (date.getMonth() + 1) + "/" + date.getDate();

        }


        $("#UcrTable").tabulator({
            dataGrouped: function (groups) {

                groups.forEach(function (group) {
                    group.getElement().on("click", function (e) {
                        group.toggle();
                    });
                });
            },
            initialSort: [
                { column: "statementDate", dir: "dsc" },
            ],
            selectable: 1,
            responsiveLayout: true,
            fitColumns: true,
            height: 670,
            groupBy: "statementDate",
            groupHeader: function (value, count, data) {
                var date = new Date(value);
                var premiumAmount = 0;
                var cAmount = 0;
                var uAmount = 0;

                data.forEach(function (rowData) {
                    premiumAmount += rowData.pamount;
                    cAmount += rowData.camount;
                    uAmount += rowData.uamount;
                });

                return date.getFullYear() + "/" + date.getMonth() + "/" + date.getDate() + " - Premium Amount: " + premiumAmount + " - Commission Amount: " + cAmount + " - Unearned Amount: " + uAmount + "<span style='color:#d00; margin-left:10px;'>(" + count + " item)</span>";
            },
            groupStartOpen: false,
            placeholder: "No Data Set",
            columns: [
                { title: "Statement Date", field: "statementDate", align: "center", responsive: 0, formatter: formatDate },
                { title: "Contract", field: "contract", align: "center", responsive: 0, headerClick: sortWithFixedGroup },
                { title: "Start Date", field: "startDate", align: "center", responsive: 0, formatter: formatDate, headerClick: sortWithFixedGroup },
                { title: "End Date", field: "endDate", align: "center", responsive: 0, formatter: formatDate, headerClick: sortWithFixedGroup },
                { title: "Paid To Date", field: "ptd", align: "center", responsive: 0, formatter: formatDate, headerClick: sortWithFixedGroup },
                { title: "Premium Amount", field: "pamount", formatter: "money", formatterParams: { symbol: "$" }, align: "right", responsive: 0, headerClick: sortWithFixedGroup, topCalc: "sum", topCalcParams: { precision: 2 } },
                { title: "Commission Rate", field: "crate", formatter: "money", formatterParams: { symbol: "$" }, align: "right", responsive: 0, headerClick: sortWithFixedGroup, },
                { title: "Commission Amount", field: "camount", formatter: "money", formatterParams: { symbol: "$" }, align: "right", responsive: 0, headerClick: sortWithFixedGroup, topCalc: "sum", topCalcParams: { precision: 2 } },
                { title: "Unearned Amount", field: "uamount", formatter: "money", formatterParams: { symbol: "$" }, align: "right", responsive: 0, headerClick: sortWithFixedGroup, topCalc: "sum", topCalcParams: { precision: 2 } }
            ],
        },
        );

        $(window).resize(function () {
            $("#UcrTable").tabulator("redraw", true);
        });

        if (@Model.Agents.Count() > 1) {
            $("#submit").click(function () {
                var agentid = $("#AgentsList").val();
                $("#UcrTable").tabulator("setData", "/Reports/Agency/UnearnedCommissions/data?agentid=" + agentid);
            });
        }
        else {
            debugger;
            var agentid = "@Model.Agents.First().Value";
            $("#UcrTable").tabulator("setData", "/Reports/Agency/UnearnedCommissions/data?agentid=" + agentid);

        }
    </script>`

**Comment by olifolkerd** [comment]
You are most welcome, im happy to help.

The precision parameter is currently only available on the ***avg*** calculation, so it will not have any effect on the ***sum*** calculation.

Looking at this, it looks like a floating point precision calculation issue. not to worry, you can use a custom calculation function to sort this for you:

```js
//custom calculation function
var sumPrecision = function(values, data, calcParams){
    var output = 0;

    if(values.length){
        values.forEach(function(value){
            output += !isNaN(value) ? Number(value) : 0;
        });
    }

    return output.toFixed(2);
}

//then replace the "sum" calculation with your new function in your column definitions:
topCalc: sumPrecision
```

I hope that helps

Cheers

Oli :)

**Comment by tcox1111** [comment]
It most certainly did help. Thanks for everything Oli!

**Comment by olifolkerd** [comment]
Hey @tcox1111 

You will be happy to hear that in Tabulator 3.3 there is now inbuilt support for clickable group headers. you can use the ***groupToggleElement*** option to make the entire header element clickable instead of just the arrow:
```js
$("#example-table").tabulator({
   groupToggleElement:"header", //toggle group on click anywhere in the group header
});
```

There are also loads of build in callbacks for different click and tap events on the group header.

Checkout the [Row Grouping Documentation](http://tabulator.info/docs/3.3#grouping) for more info.

Cheers

Oli
