### ISSUE TITLE
Request : Ability to Render certain rows

### ISSUE THREAD

**Issue by br3nd4nn34l** [olifolkerd/tabulator#493]
Is there a way to trigger a render for certain rows? Right now it seems like we can only trigger a render for the entire table to see the results of new data. 

I have an editor that affects values in multiple columns by editing a single column. The editor splits a Google maps location into pieces (e.g. country, city, etc.) and outputs each piece to a different column. It edits the row data values correctly but won't display this new data unless a redraw is triggered). It seems like a huge overhead cost to have to re-render the entire table each time I want to see this new data appear in the row I'm editing. If I could trigger the render for that row only I could eliminate this overhead entirely.

**Comment by olifolkerd** [comment]
If you just want to update a single row you can either use the ***updateRow*** function, specifying the value of the index field of the row:
```js
$("#example-table").tabulator("updateRow", 1, {id:1, name:"bob", gender:"male"});
```
or you can call the ***update*** function on the row component directly:
```js
row.update({"name":"steve"}); //update the row data for field "name"
```

Cheers

Oli

**Comment by br3nd4nn34l** [comment]
That was fast. Thanks Oli!
