### ISSUE TITLE
progress formatter conditional formatting

### ISSUE THREAD

**Issue by samshah777** [olifolkerd/tabulator#494]
Hi Oli,

I'm trying to create conditional formatting for the progress formatter (below 10-red, 10 to 15- orange and 15 over-green) 
Just wondering if you are looking to add this as part of the formatter feature sometime soon ?

Could you guide me how I can do this otherwise?

**Comment by olifolkerd** [comment]
Hey,

That exact type of formatter is on the roadmap for the 3.4 release in September, in the mean time here is a custom formatter based on the progress bar that you could use instead:
```js
var progressFormatter = function(cell, formatterParams){ //progress bar
	var value = this.sanitizeHTML(cell.getValue()) || 0,
	element = cell.getElement(),
	max = formatterParams && formatterParams.max ? formatterParams.max : 100,
	min = formatterParams && formatterParams.min ? formatterParams.min : 0,
	color, percent;

	//make sure value is in range
	value = parseFloat(value) <= max ? parseFloat(value) : max;
	value = parseFloat(value) >= min ? parseFloat(value) : min;

	//workout percentage
	percent = (max - min) / 100;
	value = 100 - Math.round((value - min) / percent);

	if(percent < 10){
		color = "#ff0000";
	}else if(percent < 15){
		color = "##FFA800";
	}else{
		color = "#00ff00";
	}

	element.css({
		"min-width":"30px",
		"position":"relative",
	});

	element.attr("aria-label", value);

	return "<div style='position:absolute; top:8px; bottom:8px; left:4px; right:" + value + "%; margin-right:4px; background-color:" + color + "; display:inline-block;' data-max='" + max + "' data-min='" + min + "'></div>";
},
```

Let me know if that helps

Cheers

Oli

**Comment by samshah777** [comment]
Hey Oli,

Thanks for the info. As for the code you posted, how would I apply it?
{title:"totalp", field:"totalp", align:"left", formatter:"progressFormatter"}  does not seem to work

**Comment by olifolkerd** [comment]
You were very close, when using a custom formatter you can pass the variable in directly, no need to put it in quotes:
```js
{title:"totalp", field:"totalp", align:"left", formatter:progressFormatter}
```
Cheers

Oli

**Comment by samshah777** [comment]
Thanks but that does not work either. Breaks the code. Table no longer appears

**Comment by olifolkerd** [comment]
Appologies, there was a comma at the end of the function for some reason, it was also calculating the colours incorrectly.

I have updated the example with the correct code now.

Cheers

Oli

**Comment by samshah777** [comment]
Thank you ..that works hallelujah ! Your technical altruism will go a long way my friend. Definitely recommending tabulator to my peers. Cheers
