### ISSUE TITLE
Required JSON format?

### ISSUE THREAD

**Issue by mhaddy** [olifolkerd/tabulator#497]
I have JSON that is in the form of {index -> {column -> value}} - see sample below, and it's not loading correctly as I am receiving the following error. How can I fix this?

``
Data Loading Error - Unable to process data due to invalid data type
``
Sample JSON data:

``
{"UNIQUEINDEXID01":{"ACTUALSTART":"08\/04\/2017 4:00 AM","CODE":"ABCD","EXP_LABEL":1.0,"LAST_TESTED":"2017-08-03","PRECISION":0.7361574173},"UNIQUEINDEXID02":{"ACTUALSTART":"17\/04\/2017 12:10 PM","CODE":"DTRG","EXP_LABEL":1.0,"LAST_TESTED":"2017-08-03","PRECISION":0.7637881041}}
``

**Comment by olifolkerd** [comment]
Tabulator expects data to be passed in as an array of objects with each object being the data for a row.

I would suggest you iterate over your object to convert it into an array, (this assumes you have converted your original JSON data into an object:
```js
var tableData = [];

for (var index in originalData){
    var rowData = originalData[index];
    rowData.id = key;

    tableData.push(rowData);
}
```
you can then pass the tableData array into tabulator.

Cheers

Oli

**Comment by mhaddy** [comment]
Perfect - thank you!
