### ISSUE TITLE
How would I go about freezing the top row?

### ISSUE THREAD

**Issue by br3nd4nn34l** [olifolkerd/tabulator#498]
I know I can freeze column headers in the column configurations for scrolling horizontally but how would I go about freezing column headers at the top of the tabulator for scrolling vertically?

**Comment by olifolkerd** [comment]
Hey,

The column headers are frozen, if you define the ***height*** of the table then it will be scrollable with the headers remaining where they are:

```js
$("#example-table").tabulator({
    height:200,
    columns:[...],
});
```

If you mean freeze the first row of data, the bad news is you cant do this yet, but i have added it to the roadmap for the 3.4 release due out in September.

The good news is you might be able to achieve this with a bit of a work around using column calculations.

You can define your own calculation function that returns the first value from the column:

```js
//custom calc function that returns the first value of the column
var freezeTopRow = function(values, data, calcParams){
    return values[0];
}
```
Then assign it to every column in your column definition array:
```js
$("#example-table").tabulator({
    columns:[
        {title:"Name", field:"name", topCalc:freezeTopRow},
        {title:"Age", age:"name", topCalc:freezeTopRow},
        {title:"Gender", field:"gender", topCalc:freezeTopRow},
    ]
});
```
Let me knows how that works for you,

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @br3nd4nn34l 

You will be happy to hear the ability to freeze rows  has just been pushed to the 3.4 branch.

you can now call the ***freeze*** function on a row component to freeze it at the top of the table:

```js
row.freeze();
```

The 3.4 release should be coming out in the next couple of weeks.

Cheers

Oli

**Comment by olifolkerd** [comment]
Tabulator version 3.4 has now been officially released!

You can find details of the new release in the [News Section](http://tabulator.info/news)

Full documentation of all the new features can be found [Here](http://tabulator.info/docs/3.4)

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @sanleong 

Thanks for the question.

I have just updated the website to include an [Example](http://tabulator.info/examples/3.4#frozen-row)

there was a small issue with the frozen row not displaying correctly if it was frozen before it was visible on the table, i have just released patch version 3.4.5 to fix this issue.

Let me know if you need any further info,

Cheers

Oli :)

**Comment by sanleong** [comment]
Thank you Oli. I appreciate your prompt attention.
Regards

**Comment by sanleong** [comment]
Hey Oli,
Please disregard the question about table size. I️ find a way by setting the font size of the div element.

Regards,
Gilberto Leon

On Mar 14, 2018, at 7:39 AM, Oli Folkerd <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @sanleong<https://github.com/sanleong>

Thanks for the question.

I have just updated the website to include an Example<http://tabulator.info/examples/3.4#frozen-row>

there was a small issue with the frozen row not displaying correctly if it was frozen before it was visible on the table, i have just released patch version 3.4.5 to fix this issue.

Let me know if you need any further info,

Cheers

Oli :)

**Comment by sanleong** [comment]
Hi Oli,

Does Tabulator support resizable div? Does table can be auto adjusted on drag the container div? Please advice.

Best regards,

Gilberto

**Comment by olifolkerd** [comment]
Hi @sanleong,

There is no inbuilt drag to resize on the table element itself. only on columns and rows, but you would be able to add that functionality yourself by creating some resize elements on the edge of the div, using some JS to allow those to resize the div, then call the ***redraw*** function on the table.

Just a note, could you make sure you ask new questions in new issues, it just makes it easier for others to find the answers.

Cheers

Oli :)

**Comment by sanleong** [comment]
Thank you,
Should I️ post the question as new request? Just let me know. Sorry about that.

Regards,
Gilberto Leon

On Mar 29, 2018, at 11:57 AM, Oli Folkerd <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @sanleong<https://github.com/sanleong>,

There is no inbuilt drag to resize on the table element itself. only on columns and rows, but you would be able to add that functionality yourself by creating some resize elements on the edge of the div, using some JS to allow those to resize the div, then call the redraw function on the table.

Just a note, could you make sure you ask new questions in new issues, it just makes it easier for others to find the answers.

Cheers

Oli :)
