### ISSUE TITLE
Column - not visible with bottomCalc or topCalc

### ISSUE THREAD

**Issue by bluedog** [olifolkerd/tabulator#499]
![visible_header_issue](https://user-images.githubusercontent.com/71191/28998525-33c697b0-79fb-11e7-9cf6-e9fe818d159f.PNG)
When a column is set to "visible: false" space for that column still exists in the topCalc or bottomCalc rows. 

I also have a use case where when one column is set to visible: false the column header of the column before disappears but the data is shown in the details. 
[tab_visible.html.zip](https://github.com/olifolkerd/tabulator/files/1202647/tab_visible.html.zip)
<img width="637" alt="visible_calcrows" src="https://user-images.githubusercontent.com/71191/28998510-e827293c-79fa-11e7-8efd-984c864079d7.png">

**Comment by olifolkerd** [comment]
Hey,

Good spot, I am doing a patch update release tommorrow afternoon, i will include a fix for this in that release.

Thanks for letting me know.

Cheers

Oli

**Comment by olifolkerd** [comment]
I have just pushed a fix for this to the master branch, it will appear in the patch release this afternoon.

Cheers

Oli
