### ISSUE TITLE
Fix when we don't use id named field

### ISSUE THREAD

**Issue by Astalavista70** [olifolkerd/tabulator#5]
This fix is for
- Find the first column with a field name or with the param unique set to true (and the table use it as id)
- Add hidden option to columns
- Fix the drawing of column when we init Tabulator before send columns headers (Create _init, _colRedraw method )

[tabulator.txt](https://github.com/olifolkerd/tabulator/files/88316/tabulator.txt)

**Comment by olifolkerd** [comment]
Hey,

Thanks for the suggestion. i like the idea of allowing the user to change the index column.

I will add a parameter to the options list called indexField, that will allow the user to specify the name of the index field (means they dont have to create hidden columns etc). and if the index field is missing the system will auto create and id based on its position in the initial data array.

I will get that in the next release this weekend.

Cheers

**Comment by olifolkerd** [comment]
Also the ability to toggle columns visibility will be coming in the next release. 

Though it is worth noting that you can include data in the data array that isnt in the column list and it will still end up in the row data etc, just not displayed on the table.

**Comment by olifolkerd** [comment]
This has now been added in release **1.5.0**

You can define a specific index field using the ***index*** options parameter:
```js
$("#example-table").tabulator({
	index:"age", //set the index field to the "age" field.
});
```

You can set a columns visibility using the ***visible*** parameter in the column definition. *(the default value for visibility is true)*:
```js
{title:"Favourite Color", field:"col", sorter:"string", visible:false},
```
