### ISSUE TITLE
Enhancement Request - Show top/bottom calc rows when groupByStartOpen is false. 

### ISSUE THREAD

**Issue by bluedog** [olifolkerd/tabulator#500]
Enhancement Request - ability to show top and/or bottom calc rows when groupByStartOpen: false. 

![groupby_closed_calcrow](https://user-images.githubusercontent.com/71191/28998652-c08a2db2-79fe-11e7-8fcc-21309671f443.png)

**Comment by olifolkerd** [comment]
I can see where you are coming from with this request,

I wouldn't alter the current function, having a group collapse should by default hide all contents of that group. But i would be happy to add another config option that would allow for stats to remain visible when groups are closed.

I will schedule this for the 3.3 release later this month.

Thanks for the suggestion.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @bluedog 

You will be happy to hear that in today's 3.3 release you can now set the visibility of column calculations in groups using the new ***groupClosedShowCalcs*** option:
```js
$("#example-table").tabulator({
    groupClosedShowCalcs:true, //show column calculations when a group is closed
});
```

Full details can be found in the [Column Calculations Documentation](http://tabulator.info/docs/3.3#calculations)

Cheers,

Oli
