### ISSUE TITLE
addColumn breaks layout if fitColumns==false

### ISSUE THREAD

**Issue by Zuur** [olifolkerd/tabulator#501]
first off, thanks for your tab ordering fix after moving columns in the recent 3.2 update!

Another one for you Oli:

If you set fitColumns:false, and then add a new column into the grid, the column is made only as big as it needs to be for _each individual row_ (instead of finding the minimum for all rows), so breaks the layout.

That's probably not too clear - please see jsfiddle [here](https://jsfiddle.net/Zuur/be6mx0yp/8/).

**Comment by olifolkerd** [comment]
Thanks for the heads up,

I have just pushed a fix for this to the master branch, it will be included in this afternoons patch release

Cheers

Oli
