### ISSUE TITLE
addColumn doesn't add cells for each existing row

### ISSUE THREAD

**Issue by Zuur** [olifolkerd/tabulator#502]
The addColumn call appears not to add matching cells for the new column - ie: if there are 5 rows in the table, adding a new column without data doesn't add 5 empty cells for it - no cells are added at all.

This might be by design, I'm not sure, but because getCells() on the new column returns only one item (the header) it seems like there's no way to set a value in a cell of the new column? Also, the thing that's tripping me up is that I've got movable columns and I get an error in tabulator.js, line 11025 because it's trying to address a cell that doesn't exist (presumably to move it). I haven't been able to reproduce this same error in a jsfiddle, but here's one that shows a count of the cells in each column after adding a column, adding a row, then adding another column: [https://jsfiddle.net/Zuur/be6mx0yp/10/](https://jsfiddle.net/Zuur/be6mx0yp/10/).

**Comment by olifolkerd** [comment]
Hey,

Looking at your example, the cells are being created correctly, you are not specifying any data for them so they are empty.

What is confusing you is that the column cells array is getting bigger than you are expecting. Every time the row is redrawn (for example when you add a column) the cells are recreated and pushed to the cells array for that column. in this instance there appears to b a memory leak where old cells are not being cleared from the array, so some of the cells you are trying to access no longer exist.

I will add a tweak to the patch release today to fix the memory leak.

Cheers

Oli

**Comment by olifolkerd** [comment]
I have just pushed an fix for this to the maser branch,

it will be included in this afternoons patch release
