### ISSUE TITLE
Height of the row

### ISSUE THREAD

**Issue by kurtknippschild** [olifolkerd/tabulator#503]
Hi Oli,

the height of the column is when i open the dialog not in the CSS:
<div class="tabulator-cell" role="gridcell" tabulator-field="st_bezeichnung" title="" style="width: 20px; text-align: center; color: rgb(153, 153, 153); background-color: rgb(153, 153, 153);">open<div class="tabulator-col-resize-handle"></div><div class="tabulator-col-resize-handle prev"></div></div>
The table looks like so:
![bildschirmfoto 2017-08-06 um 12 09 53](https://user-images.githubusercontent.com/22855656/29002386-b9a3980a-7aa1-11e7-96c2-638aa63cf63d.png)
I make a redraw of table for the first time.  Without the redraw i see only the tabulator-header,
the tabulator-tableHolder is empty.

After i generate a new row then the height is in the CSS:
<div class="tabulator-cell" role="gridcell" tabulator-field="st_bezeichnung" title="" style="width: 20px; text-align: center; color: rgb(153, 153, 153); background-color: rgb(153, 153, 153); height: 44px;">open<div class="tabulator-col-resize-handle"></div><div class="tabulator-col-resize-handle prev"></div></div>
and now the table looks like OK:

This is my script:
<script language="JavaScript" type="text/javascript">
	$(document).ready(function() {

				var fontSizeFormatter = function(cell, formatterParams){
				    //cell - the cell component
				    //formatterParams - parameters set for the column
				
				    var element = cell.getElement();
				    element.css({
				    	"vertical-align":"top",
				    	"font-size":14,
				    	"cursor":"pointer",
				    	"white-space":"pre-wrap",
				    })
				
				    element.tooltip({ track: true, });
				
				    return cell.getValue(); //return the contents of the cell;
				}	

				var colorFormatter = function(cell, formatterParams){
				    //cell - the cell component
				    //formatterParams - parameters set for the column
				
				    var element = cell.getElement();
				    //console.log(cell.getValue());
					  if(cell.getValue() == "open")
						{
								element.css({
					    	"color":"rgb(153,153,153)",
					    	"background-color":"rgb(153,153,153)",
					  		})
						} else 
						if(cell.getValue() == "In Progress")
						{
								element.css({
					    	"color":"rgb(251,207,4)",
					    	"background-color":"rgb(251,207,4)",
					  		})
						} else 
						if(cell.getValue() == "Done")
						{
								element.css({
					    	"color":"rgb(0,178,0)",
					    	"background-color":"rgb(0,178,0)",
					  		})
						} else 
						if(cell.getValue() == "Deprecated")
						{
								element.css({
					    	"color":"rgb(0,107,117)",
					    	"background-color":"rgb(0,107,117)",
					  		})
						} 

				    return cell.getValue(); //return the contents of the cell;
				}	

				var fontColorFormatter = function(cell, formatterParams){
				    //cell - the cell component
				    //formatterParams - parameters set for the column
				
				    var element = cell.getElement();
					  if(cell.getValue() == "open")
						{
								element.css({
					    	"color":"rgb(153,153,153)"
					  		})
						} else 
						if(cell.getValue() == "In Progress")
						{
								element.css({
					    	"color":"rgb(251,207,4)"
					  		})
						} else 
						if(cell.getValue() == "Done")
						{
								element.css({
					    	"color":"rgb(0,178,0)"
					  		})
						} else 
						if(cell.getValue() == "Deprecated")
						{
								element.css({
					    	"color":"rgb(0,107,117)"
					  		})
						} 

				    return cell.getValue(); //return the contents of the cell;
				}	

		$("#tabulator_bot_ergebnis").tabulator({
		    columnMinWidth: 20,
		    fitColumns:true, //fit columns to width of table (optional)
		    colResizable:false,
				columns:[
		    {title:"OBJ_ID", field:"obj_id", sorter:"number", align:"center", width:60, visible:false},
        {title:"<bean:message bundle="<%= resources %>" key="imaObjektAttributsWerte_liste.label.obj_name"/>", field:"obj_name", sorter:"string", headerSort:false, align:"left", formatter:fontSizeFormatter, cellClick:function(e, cell){
						var data = cell.getData();
	  					$('#ism_progressbar').show();
							$.post("imaObjektDetails.ims", 
							{
								cache: false,
								aktion: 'info',
								AKTION_OLD: '',
								OBJ_ID: data.obj_id,
								OG_ID: data.og_id,
								OG_ID_VIRTUELL: data.og_id_virtuell,
								OBJ_EBENE: '1',
								OK_ID: data.ok_id,
								OBJ_NAME: data.obj_name,
								OK_NAME: data.ok_name,
								OK_HAT_AUSSTATTUNG: 'j',
								OK_HAT_ADRESSEN: 'j',
								OK_HAT_DOKUMENTE: 'j',
								OK_HAT_FLAECHEN: 'j',
								OK_IST_VERFUEGBAR: 'j'
							},
							function(data,status,xhr) {
								$("#inhalt").html(data);
								$('.baumObjektText').css('color', 'rgb(255,255,255)');
								$('.baumObjektText').css('font-weight', 'normal');
						   	$('#ism_progressbar').hide();	
			      	 }, "html") 				
        	 }, 
					},

        {title:"Pfad", field:"pfad", sorter:"string", headerSort:false, align:"left"},
        {title:"<bean:message bundle="<%= resources %>" key="imaDashboardStruktur.label.st_bezeichnung"/>", field:"obj_status", sorter:"string", align:"right", width:80,formatter:fontColorFormatter},
        {title:"", field:"st_bezeichnung", headerSort:false, align:"center", width:5, formatter:colorFormatter},
				],
			});
		
  var tabulator_bot_ergebnis_data = [	
	<logic:present name="cbtErgebniss">
		<logic:iterate id="cbte" name="cbtErgebniss">
			<bean:define id="ogID" name="cbte" property="og_id" type="Integer"/>
			<bean:define id="ogIDVirtuell" name="cbte" property="og_id_virtuell" type="Integer"/>
			<bean:define id="okID" name="cbte" property="ok_id" type="Integer"/>
			<bean:define id="objID" name="cbte" property="obj_id" type="Integer"/>
			<bean:define id="objName" name="cbte" property="obj_name" type="String"/>
			<bean:define id="okName" name="cbte" property="ok_name" type="String"/>
			<bean:define id="pfad" name="cbte" property="obj_name_vater" type="String"/>
			<bean:define id="stBezeichnung" name="cbte" property="st_bezeichnung" type="String"/>
			<% anzBotRows++; %>
			{id:<%= anzBotRows %>
			, og_id: "<%= ogID %>"
			, og_id_virtuell: "<%= ogIDVirtuell %>"
			, ok_id: "<%= okID %>"
			, obj_id: "<%= objID %>"
			, obj_name: "<%= objName %>"
			, ok_name: "<%= okName %>"
			, pfad: "<%= pfad %>"
			<% if(stBezeichnung.equals("aktiv")) { stBezeichnung = "open"; %>
			<% } else if(stBezeichnung.equals("inaktiv")) { stBezeichnung = "Deprecated"; } %>
			, st_bezeichnung: "<%= stBezeichnung %>"
			, obj_status: "<%= stBezeichnung %>"
			},
		</logic:iterate>
	</logic:present>
    ];
    
		$("#tabulator_bot_ergebnis").tabulator("setData", tabulator_bot_ergebnis_data);
		
		tabulatorRedrawName = "#tabulator_bot_ergebnis";

		$(window).resize(function(){
		    $("#tabulator_bot_ergebnis").tabulator("redraw", true); //trigger full rerender including all data and rows
		});

	});
</script>	

I hope you can help.

Thanks in advance.

MG Kurt

**Comment by kurtknippschild** [comment]
Sorry the screenshots leck.
![bildschirmfoto 2017-08-06 um 12 09 53](https://user-images.githubusercontent.com/22855656/29002460-44123464-7aa3-11e7-90df-4a9f04ee8493.png)
![bildschirmfoto 2017-08-06 um 12 10 13](https://user-images.githubusercontent.com/22855656/29002462-4a980e30-7aa3-11e7-8b5d-71607b65e8f0.png)

**Comment by kurtknippschild** [comment]
Soory, and here the CSS  without the height:
<div class="tabulator-cell" role="gridcell" tabulator-field="st_bezeichnung" title="" style="width: 20px; text-align: center; color: rgb(153, 153, 153); background-color: rgb(153, 153, 153);">open<div class="tabulator-col-resize-handle"></div><div class="tabulator-col-resize-handle prev"></div></div>
and here with height:
<div class="tabulator-cell" role="gridcell" tabulator-field="st_bezeichnung" title="" style="width: 20px; text-align: center; color: rgb(153, 153, 153); background-color: rgb(153, 153, 153); height: 44px;">open<div class="tabulator-col-resize-handle"></div><div class="tabulator-col-resize-handle prev"></div></div>

**Comment by olifolkerd** [comment]
Hey,

If you create the table, or set the data when the table is not visible it will be unable to calculate the correct row heights because elements do not have a height or width until they are visible.

In situations like this, you must call the ***redraw*** function after the table is visible for it to be displayed correctly.

Cheers

Oli
