### ISSUE TITLE
Global filter which searches all columns?

### ISSUE THREAD

**Issue by koosvanderkolk** [olifolkerd/tabulator#505]
How can I apply a global filter to all columns? 

I expected setFilter to have an optional 'field' parameter, but its mandatory.

I know I can add a filter for each column, but these filters are "AND" (so the keyword should be found in each of the columns) in stead of "OR" (row is displayed if keyword appears in one of the columns).

**Comment by olifolkerd** [comment]
Hey,

Thanks for getting in touch,

You could use a custom filter function for this:

```js
//custom filter function
function matchAny(data, filterParams){
    //data - the data for the row being filtered
    //filterParams - params object passed to the filter

    var match = false;

    for(var key in data){
        if(data[key] == filterParams.value){
            match = true;
        }
    }

    return match;
}

//set filter to custom function
$("#example-table").tabulator("setFilter", matchAny, {value:5});
```

Let me know if that helps.

Cheers

Oli

**Comment by wolfygit** [comment]
if you want to start searching while you are writting the if would be:
```
 if (JSON.stringify(data[key]).search(filterParams.value) != -1) {
match = true; 
}
```

vdf

**Comment by hookedupjoe** [comment]
Here is a version that can take optional columns (the column specs or columns that should be searched only).  Also has a flag to search starting with only .. by default it searches it all.  Of course case insensitive.   Just a quick set of updates to maybe help others.

`function matchAny(data, filterParams) {
    var checkVal = filterParams.value.toLowerCase();
    var tmpIsCols = Array.isArray(filterParams.columns);
    var tmpKeyList = data;
    if( tmpIsCols ){
      tmpKeyList = {};
      for( var iPos in filterParams.columns){
        var tmpCol = filterParams.columns[iPos];
        var tmpKey = tmpCol.field;
        if( tmpKey ){
          tmpKeyList[tmpKey] = true;  
        }
      }
    }
    
    var match = false;
    var key = '';
    if( filterParams.startsWith === true ){
      for ( key in tmpKeyList) {
        if (data[key].toLowerCase().indexOf(checkVal) === 0) {
          match = true;
          break;
        }
      }  
    } else {
      for ( key in tmpKeyList) {
        if (data[key].toLowerCase().indexOf(checkVal) > -1) {
          match = true;
          break;
        }
      }  
    }
    return match;
  }
`


Then to call it using the jquery wrapper (how we are using it) ..
`this.mainTableEl.tabulator("setFilter", matchAny, {columns: this.columnSpecs, value:tmpSS, startsWith: true});
`

**Comment by ppKrauss** [comment]
Hi, some news here? I not see solution in the guide, please post some help at https://stackoverflow.com/q/63607444/287948

**Comment by AndreasMueck** [comment]
Here is my solution for filtering the table with JS RegExp and NO JQuery required.
The search filters all results of the entry regardless of upper or lower case. Parts of an Word are also found.
Thanks to all where I could found information for this solution and thanks to @olifolkerd for his wonderful tabulator work.

HTML [Input field]: 
```html
<label for="fSearch">Search</label>
<input type="text" id="fSearch" name="fSearch">
```

JS [Handler for input field]:
```js
const input = document.getElementById("fSearch");
input.addEventListener("keyup", function() {
    table.setFilter(matchAny, { value: input.value });
    if (input.value == " ") {
        table.clearFilter()
    }
});
```

JS [Function for filtering]:
```js
function matchAny(data, filterParams) {
      //data - the data for the row being filtered
      //filterParams - params object passed to the filter
      //RegExp - modifier "i" - case insensitve

    var match = false;
    const regex = RegExp(filterParams.value, 'i');

    for (var key in data) {
        if (regex.test(data[key]) == true) {
            match = true;
        }
    }
    return match;
}
```

**Comment by abhijitgujar86** [comment]
search from all columns ( visible or hidden ) is a standard and very important requirement in my opinion. so you guys have plan to add this as basic in-build feature ?

**Comment by olifolkerd** [comment]
Hey @abhijitgujar86 

The issue above literally explains how to add this functionality to your table if needed.

Cheers

Oli :)

**Comment by grufas** [comment]
> 

Thank you for the solution! Can anyone give an idea how to set columns where search must be performed? For example: search not within all columns, but only Column A and Column B?

**Comment by DierkesL** [comment]
> > 
> 
> Thank you for the solution! Can anyone give an idea how to set columns where search must be performed? For example: search not within all columns, but only Column A and Column B?
> 
> Unfortunately method below doesn't work:
> 
> `tabulator.setFilter([ {field:"col_a", type:"like", value:input.value}, {field:"col_b", type:"like", value:input.value}, ]);`

`function matchAny(data, filterParams){
    //data - the data for the row being filtered
    //filterParams - params object passed to the filter

    let columnsIncluded = {'row1':1, 'row2':2};
    let match = false;

    for(var key in data){
        if((key in columnsExcluded) == true) {
            if(data[key] == filterParams.value){
                 match = true;
             }
        }
    }

    return match;
}`

**Comment by MarcelKluth** [comment]
Hello I have a problem with my code. i'm trying to implement the approach of @AndreasMueck, but if i enter the text into the searchbar the filter is not applied.

**Html File**

```
<body>

  <?!= include('JavaScript'); ?>

<input type="text" id="fSearch" name="fSearch" placeholder="Suche ...">

  <div id="example-table" ></div>
  </div>
</body>
```
**JS File**

```
<script type="text/javascript" src="https://unpkg.com/tabulator-tables@5.6.1/dist/js/tabulator.min.js"></script>
<script>

  document.addEventListener("DOMContentLoaded", createTable);

  function createTable(){
    google.script.run.withSuccessHandler((tableData)=>{
      console.log(tableData);
      let table = new Tabulator("#example-table",{
        data:tableData,
        pagination:false,
        layoutColumnsOnNewData:true,
        layout:"fitDataStretch",
        paginationSize:10,
        paginationSizeSelector:true,
        movableColumns:true,
        columnDefaults:{tooltip:true,},
        columns:[
          
          {title:"Task",field:"Task",},
          {title:"Text",field:"Text",},

        ],
      });
    }).getData();
  }


const input = document.getElementById("fSearch");

input.addEventListener("keyup", function() {
    table.setFilter(matchAny, { value: input.value });
    if (input.value == " ") {
        table.clearFilter()
    }
});


function matchAny(data, filterParams) {
      //data - the data for the row being filtered
      //filterParams - params object passed to the filter
      //RegExp - modifier "i" - case insensitve

    var match = false;
    const regex = RegExp(filterParams.value, 'i');

    for(var key in data){
        if (regex.test(data[key]) == true) {
            match = true;
        }
    }
    return match;
}

</script>
```

if someone could help me, id be very greatful.
