### ISSUE TITLE
selectRow in combination with filtered data behavior

### ISSUE THREAD

**Issue by koosvanderkolk** [olifolkerd/tabulator#506]
From the docs:

> To programmatically select a row you can use the selectRow function. (...) If you do not pass any arguments to the selectRow function, all rows will be selected.

In case of filtered data, the current behavior is that filtered out rows can still be selected. Omitting the arguments will also select all rows, not just the visible ones.

Would it not be more logical to only select the _visible_ rows (or to make it an optional argument to do so?)

**Comment by olifolkerd** [comment]
Hey,

That is a great idea, i will add the ability to choose how you select to the 3.3 release.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @koosvanderkolk,

You will be happy to hear that in toady's 3.3 release you can now choose which rows to select with the ***selectRows*** function.
```js
$("#example-table").tabulator("selectRows"); //select all rows in the table
$("#example-table").tabulator("selectRows", true); //select all filtered rows in the table
```
Cheers,

Oli :)

**Comment by koosvanderkolk** [comment]
Great, thanks!
