### ISSUE TITLE
Selecting multiple rows with Shift key --> new behavior?

### ISSUE THREAD

**Issue by koosvanderkolk** [olifolkerd/tabulator#507]
From the docs http://olifolkerd.github.io/tabulator/docs/#selectable:

> Holding down the shift key and click dragging over a number of rows to toggle the state of all rows the cursor passes over. 

Would it not be better to stick to the Excel/Google Sheets/OO behaviour? So:

1. User clicks row n
2. User clicks row m while holding Shift key
3. System selects rows n-m (or m-n when m<n)

Many end users will expect this kind of behaviour when interacting with tabular data.

**Comment by olifolkerd** [comment]
Hey,

Thanks for your suggestion,

The current selection behaviour has been designed to match the needs of a number of Tabulator users. There is always a balance to strike between making Tabulator match with desktop spreadsheet systems and online list selection systems and a great many other interface styles, and it is impossible to catch every usage case.

In this case the selection system has been in use for over a year without issue and changing it at this point would cause disruption to the user base, so i would not look to make the suggested change.

If you would like to add this functionality to your table i can certainly show you how using the ***rowClick*** callback to trigger a selection event,

In a release later this year there will be some major upgrades to the selection systems including cell group selection.

Thanks for your feedback, let me know if you have any other suggestions :)

Cheers

Oli

**Comment by koosvanderkolk** [comment]
> If you would like to add this functionality to your table i can certainly show you how using the rowClick callback to trigger a selection event,

That would be great, thanks! Maybe there can be a 'selectionBehavior' setting, allowing for switching between the current Shift/Ctrl behavior and 'spreadsheet' behavior?

**Comment by olifolkerd** [comment]
Hey @koosvanderkolk 

Just realised i never got back to you on this one, sorry about that.

each row component has a ***select*** deselect*** and ***togggleSelect*** function, so you can combine these with the ***rowClick*** callback to get:
```js
$("#example-table").tabulator({
    rowClick:function(e, row){
        //e - the click event object
        //row - row component

        row.toggleSelect();
    },
});
```
and you can wrap any logic you want around that.

Cheers

Oli

**Comment by koosvanderkolk** [comment]
Thanks!
