### ISSUE TITLE
Inconsistency in API: setColumns / getColumns / getColumnDefinitions 

### ISSUE THREAD

**Issue by koosvanderkolk** [olifolkerd/tabulator#509]
setColumns accepts a column configuration array
getColumns returns a ColumnComponent array
getColumnDefinitions returns a column configuration array

Wouldn't it be more logical to keep the function names consistent? E.g.

setColumns accepts a ColumnComponent array
getColumns returns a ColumnComponent array
setColumnDefinitions accepts a column configuration array
getColumnDefinitions returns a column configuration array

**Comment by olifolkerd** [comment]
Thanks for the feedback,

There would never be a situation where you could create a column based off of its column component so i wouldn't be keen to use it that way.

I don't change function names in minor releases as it breaks the API, each year in May i do a major version release, at that point i update the function names if any of them have drifted from convention.

Thanks for your feedback

Oli
