### ISSUE TITLE
Column Headers Do Not Show

### ISSUE THREAD

**Issue by edc1970** [olifolkerd/tabulator#51]
Hi! First, kudos to a great plugin. I've just discovered Tabulator recently and I am now using it on a project but I seem to be having an issue with the column headers. Here's how it looks like:

![oss](https://cloud.githubusercontent.com/assets/12137657/17831531/e0bf53cc-671d-11e6-95d2-5b118180eac9.png)

On page load, the column headers are not shown. But if I resize or just click on the border that separates the other columns from the rest, all the headers just "magically" appears.

I tried all sorts of "redraw" - on page load, on tab click, etc, - which somehow works as a workaround, but I don't really know why it's even doing that in the first place.

Is this a bug or is there something I am not doing. Here's how my code looks like:

$("#bipd-table").tabulator({
		pagination: false,
		fitColumns: false,
		sortBy: "cover_limit",
		sortDir: "asc",
		progressiveRender:true,
		ajaxURL: "bipd.php?trans_type=get",
		columns:[
			{title:"ID", field:"id", visible:false, align:"center",  editable:false},
			{title:"Cover Limit", field:"cover_limit", formatter:"money", sortable: true, sorter:"number", align:"center", width:143, editable:false},
	        {title:"BI PC", field:"bi_pc", formatter:"money", align:"right", width:100, editable:true, editor:"number"},
	        {title:"BI LM", field:"bi_lm", formatter:"money", align:"right", width:100, editable:true, editor:"number"},
	        {title:"BI HV", field:"bi_hv", formatter:"money", align:"right", width:100, editable:true, editor:"number"},
	        {title:"BI MC", field:"bi_mc", formatter:"money", align:"right", width:100, editable:true, editor:"number"},
	        {title:"PD PC", field:"pd_pc", formatter:"money", align:"right", width:100, editable:true, editor:"number"},
	        {title:"PD LM", field:"pd_lm", formatter:"money", align:"right", width:100, editable:true, editor:"number"},
	        {title:"PD HV", field:"pd_hv", formatter:"money", align:"right", width:100, editable:true, editor:"number"},
	        {title:"PD MC", field:"pd_mc", formatter:"money", align:"right", width:100, editable:true, editor:"number"},
	    ],
    }
});
`

**Comment by olifolkerd** [comment]
hi edc,

looking at you code you have an extra close curly brace in at the end of your definition object, but aside from that your code looks fine. if i take out the extra curly brace it works fine in chrome on my end, what browser/os version are you using?

**Comment by olifolkerd** [comment]
Did you manage to resolve this, or are you still having issues?
