### ISSUE TITLE
FF/GC: bug when table put inside <fieldset>

### ISSUE THREAD

**Issue by koosvanderkolk** [olifolkerd/tabulator#510]
Something weird happens when the tabulator is put inside a fieldset and the table columns are wider than the table.

I created a demo with 2 tabulators: one inside a div, one inside a fieldset

In IE everything looks fine: a horizontal scrollbar is shown for both tables:

![IE](https://i.imgur.com/z9HthRW.png)

In both FF and GC the table scollbar is missing for the fieldset table. A window scrollbar appears instead

![FF](https://i.imgur.com/4Rxgcse.png)
![GC](https://i.imgur.com/CS00VtU.png)

See http://jsbin.com/rolocu/edit?html,css,js,output

**Comment by koosvanderkolk** [comment]
https://stackoverflow.com/questions/31597348/overflow-of-div-inside-fieldset-not-working-in-chrome

Adding a 'min-width: inherit' property to the <fieldset> does the trick.

**Comment by olifolkerd** [comment]
Thanks for the headsup,

I will have a look into that this weekend.

Cheers

Oli

**Comment by UweHeber** [comment]
Thanks for this tipp! Had the same problem.
