### ISSUE TITLE
datepicker working on tabulator 3.2

### ISSUE THREAD

**Issue by hadikmsh** [olifolkerd/tabulator#511]
hi
both of issue #252 & issue #289 datepicker do not work with tabulator 3.2.
how i can implement datepicker with this version?
 i tried this code but it did not work.

 var DateEditor = function (cell, onRendered, success, cancel) {

            var editor = $("<input class='form-control'   type='text' />");

            editor.css({
                "padding": "3px",
                "width": "100%",
                "box-sizing": "border-box",
            })

            editor.val(cell.getValue());

//set focus on the select box when the editor is selected (timeout allows for editor to be added to DOM)

            onRendered(function () {

                editor.focus();
            });

            editor.datepicker();
            editor.on("change blur", function (e) {
                var selected = $(this).val();
                success(editor.val());

                editor.val(selected);

            });

            return editor;

        }

thanks.

**Comment by olifolkerd** [comment]
You need to use the code that is provided in the solution to #252

**Comment by hadikmsh** [comment]
thanks

**Comment by agustingrigoriu** [comment]
Hi Oli! I have some questions, I want to use your solution but with a little modificactions. The only thing I got to work is this:
```
input.datepicker({
  changeMonth: true,
  changeYear: true,
  dateFormat: "dd-mm-yy",
  onSelect: function(date) {
    $(document).off("mousedown", inputBlur);
    success(input.val());
   }
});
```
This makes the ajax request when I select a day from the datepicker, but I want to avoid the tabulator making ajax requests every time I write something in the input (if i want to edit it manually), I want only to send the ajax when I select a date directly or when I click the enter key. 
Thank you in advance!

**Comment by olifolkerd** [comment]
That shouldn't make any ajax requests, there is no code in there to trigger a request to the server. do you mean trigger the ***success*** function?

fFr full details on how to use the jquery datepicker widget checkout their [Documentation](https://jqueryui.com/datepicker/)

Cheers

Oli

**Comment by wisdom-17** [comment]
Hi @olifolkerd,

Thanks for the updated code on the datepicker implementation. I'm having trouble implementing it on my tabulator table. The daterpicker appears but selecting a date does nothing. `input.val()` seems to be empty throughout.

Can you provide some pointers please?

**Comment by wisdom-17** [comment]
I found that the cause of my issue was a conflict between jQuery's daterpicker plugin and another plugin that I'm using in my application.
