### ISSUE TITLE
correlated columns

### ISSUE THREAD

**Issue by hadikmsh** [olifolkerd/tabulator#512]
hi 
i have column product name and product code and they should point two unique product.
i want when some one insert product code, product name complete automatically and inverse.
someone can give me an idea how i can do this?

thanks.

**Comment by olifolkerd** [comment]
That would depend on where you are storing the product name and code, will you be looking up the name from  a client side JavaScriptarray or making an ajax request to retrieve it?

**Comment by hadikmsh** [comment]
thanks for your fast response
i make an ajax request when page loaded and store them in an array.

**Comment by olifolkerd** [comment]
in that case you could use the ***cellEdited*** callback to do the lookup for you.

this example assumes your are storing your name lookup in the ***productNameLookup*** array indexed by product code:

```js
$("#example-table").tabulator({
	columns:[
		{title:"Product Code", field:"code"},
		{title:"Product Name", field:"name"}
	],
	cellEdited:function(cell){
        //cell - cell component
        var value = cell.getValue();

        if(cell.getField() == "code" && value){
        	if(productNameLookup[value]){
        		cell.getRow().getCell("name").setValue(productNameLookup[value]);
        	}
        }
    },
});
```

Let me know if that helps.

Cheers

Oli

**Comment by hadikmsh** [comment]
thank you so much.
it works great.
