### ISSUE TITLE
Problem head filter

### ISSUE THREAD

**Issue by juanluep** [olifolkerd/tabulator#513]
I have a problem, does not show the select in the table header

The code is:

```js 
var selectEditor = function(cell, onRendered, success, cancel, editorParams){
//Recorro la lista de clientes
var html = "";
for(var i=0; i<app.listaClientes.length; i++){
var nombreCliente = app.listaClientes[i].Nombre;
nombreCliente = nombreCliente.split("(");
nombreCliente = nombreCliente[0];
html += ""+nombreCliente+"";
}

//Estilos para el selector de clientes
        var editor = $("<select><option value=''></option>"+html+"</select>");
        editor.css({
            "padding":"3px",
            "width":"100%",
            "box-sizing":"border-box"
        });

        //Set value of editor to the current value of the cell
        editor.val(cell.getValue());

        //when the value has been set, trigger the cell to update
        editor.on("change blur", function(e){
            var valor = editor.val();
            if(/\s+$/.test(valor)) {
                valor = valor.substring(0, valor.length - 1);
            }
            success(valor);
        });

        //return the editor element
        return editor;
    };
```
In columns:

{title:"Cliente", field:"cliente", sorter:"string", headerFilter:selectEditor, width:120},

Help please

**Comment by olifolkerd** [comment]
are you getting any errors in your console log?

**Comment by ABPTech** [comment]
I tried using this and found that the html markup gets the _html_ var added in the wrong spot:
` var editor = $("<select><option value=''></option>"+html+"</select>");`
should be 
` var editor = $("<select><option value=''>"+html+"</option></select>");`

Also, I changed the loop to this where the option available in the "active_options" array is used for the value and name of the option:

`
for(var i=0; i<active_options.length; i++){
var val = active_options[i];
html += "<option value=\""+val+"\">"+val+"</option>";
}
`

Hope this helps.

**Comment by juanluep** [comment]
Sorry error in insert code.

`
var selectEditor = function(cell, onRendered, success, cancel, editorParams){
            //Recorro la lista de clientes
            var html = "";
            for(var i=0; i<app.listaClientes.length; i++){
                var nombreCliente = app.listaClientes[i].Nombre;
                nombreCliente = nombreCliente.split("(");
                nombreCliente = nombreCliente[0];
                html += "<option value="+nombreCliente+">"+nombreCliente+"</option>";
            }
            
            //Estilos para el selector de clientes
            var editor = $("<select><option value=''></option>"+html+"</select>");
            editor.css({
                "padding":"3px",
                "width":"100%",
                "box-sizing":"border-box"
            });

            //Set value of editor to the current value of the cell
            editor.val(cell.getValue());

            //when the value has been set, trigger the cell to update
            editor.on("change blur", function(e){
                var valor = editor.val();
                if(/\s+$/.test(valor)) {
                    valor = valor.substring(0, valor.length - 1);
                }
                success(valor);
            });

            //return the editor element
            return editor;
        };
`

**Comment by juanluep** [comment]
Hi, no error in the console:

![image](https://user-images.githubusercontent.com/973123/29401935-5f475c8a-8333-11e7-8e24-5c77173c30a1.png)

I create table ...

![image](https://user-images.githubusercontent.com/973123/29402048-d060c406-8333-11e7-92f7-33f521bef2cd.png)
