### ISSUE TITLE
Open group when clicking on row

### ISSUE THREAD

**Issue by vasiliyaltunin** [olifolkerd/tabulator#515]
When you need to open (expand) group you need to click triangle button, but it so small so i can't hit it with first attempt, so i suggest change it behavior and add div around button, so it increase clickable box size.

Also it would be nice if i able to expand group by clicking in any place of group row header

**Comment by tcox1111** [comment]
This is what Oli posted for me in reference to clicking the group headers. 

**Clickable Group Headers**

There is no simple way to do this at the moment, but i will add the feature in the 3.5 release at the end of the month. in the mean time you could use the dataGrouped callback in your table definition to do this for you:

`$("#example-table").tabulator({
    dataGrouped:function(groups){
        //groups - array of top level group components

        groups.forEach(function(group){
            group.getElement().on("click", function(e){
                group.toggle();
            });
        });
    },
});`

**Comment by olifolkerd** [comment]
The group headers actually used to be triggered by clicking anywhere on the header, but a large number of users put other clickable content in their headers which prevents this from being a viable option.

It is on the roadmap to add the ability to choose how this functionality works, but it wont be for a few months now.

In the mean time as @tcox1111 says, a solution that should work for you has already been posted.

Let me know if you need any further help.

Cheers

Oli
