### ISSUE TITLE
redraw do not work

### ISSUE THREAD

**Issue by kurtknippschild** [olifolkerd/tabulator#516]
Hi Oli,

I have a problem wit the redraw of a table in a jQuery ui dialog.
By the first generation of the table all is fine and the table looks so:
![bildschirmfoto 2017-08-14 um 10 13 32](https://user-images.githubusercontent.com/22855656/29263948-5d4f6396-80db-11e7-8155-1f329772937f.png)

when I close the dialog and new open the table looks like so:
![bildschirmfoto 2017-08-14 um 10 14 00](https://user-images.githubusercontent.com/22855656/29263955-69e14e3a-80db-11e7-8a4f-f1d33c8b7338.png)

After a manual resize of the browser-window the table looks fine.
The script for the generation is always the same.
And on the end of the script  I have  this lines:
$(window).resize(function(){
   $("#tabulator_bot_ergebnis").tabulator("redraw", true); 
});
$("#tabulator_bot_ergebnis").tabulator("redraw", true);

Have you any idea what is the problem?
Thanks in advance.

MG Kurt

**Comment by kurtknippschild** [comment]
I found the problem.

**Comment by ryc16** [comment]
I got the same problem. The tabulator doesn't redraw. What is the problem and what is the solution? Kindly to post your solution. 

Note: I am currently using v3.1.1
