### ISSUE TITLE
Html broken

### ISSUE THREAD

**Issue by tranquochuy29** [olifolkerd/tabulator#52]
Hi there,

I hope you're still fine.
I have just found out one new issue.

You can following this step.
Step 1: Config the width of each column more than 400px (make the total width of all columns is greater than the width of table). Because I woud like to have horiz-scroll-bar at the first time.
Step 2: After render tabulator table, the html will be broken as the below image.
Could you have a check from your side ?

![new issue tabulator](https://cloud.githubusercontent.com/assets/4382757/17843062/e731041c-6853-11e6-8ae8-0b7507be1cae.png)

Thank you so much

Cheer,
Tony

**Comment by olifolkerd** [comment]
Hi Tony,

could you let me know which browser and os you are using so i can make sure i can replicate the bug properly.

**Comment by tranquochuy29** [comment]
Hi there,

Thank you so much for your information.
I'm using tablulator on the Chrome browser.
I'm using the same as your document
columns:[
    {title:"Ref1", field:"ref1", width:500, headerFilter:true},
    {title:"Val1", field:"val1", width:500, headerFilter:true},
    {title:"Date", field:"date", width:250, headerFilter:true}
]

Cheer,
Tony

**Comment by olifolkerd** [comment]
Hi tony,

could you post the full tabulator constructor, for example:

$("#example-table-fittowidth").tabulator({
    height:"311px",
    fitColumns:true,
    columns:[
    {title:"Name", field:"name", width:200},
    {title:"Progress", field:"progress", align:"right", sorter:"number"},
    {title:"Gender", field:"gender"},
    {title:"Rating", field:"rating", align:"center", width:60},
    {title:"Favourite Color", field:"col"},
    {title:"Date Of Birth", field:"dob", align:"center", sorter:"date"},
    {title:"Driver", field:"car", align:"center"},
    ],
});

**Comment by tranquochuy29** [comment]
Hi there,

Thank you so much for your reply.
If we use 'fitColumns:true,', that's ok. the html format is ok.
But in my case, the width of column will be bind dynamiclly.
So I cannot use 'fitColumns:true,' in this case.

Cheer,
Tony

**Comment by olifolkerd** [comment]
Hi tony,

I was using that as an example could you post ***your*** Tabulator constructor including any options you have set so i can match your setup exactly.

**Comment by olifolkerd** [comment]
Hi Tony,

I have tried replicating your bug, using every combination of setup options that i think off but i cannot replicate it.

Please could you include your full tabulator constructor with all of your chosen options, so i can replicate the it as closely as possible.

I also have a few questions that may help narrow down where this may be coming from.

Is the table visible when you create it? if not it will not be able to calculate widths and heights properly. if this is the case you will need to call the ***redraw*** function, when you make the table visible:
```js
 $("#example-table").tabulator("redraw");
```

Are you sure you have downloaded the latest version of Tabulator, both the javascript and css files? have you force refreshed your browser a couple of times (ctrl+F5) to make sure it has loaded in the new files correctly.

Do you have any other functions or library trying to modify the Tabulator object?

Have you tried creating the tabulator on a blank HTML page, that only includes the tabulator resources, that way you can check if any other factors are influencing Tabulator

**Comment by olifolkerd** [comment]
Hi Tony,

Could you confirm if the above info helped you resolve your issue?

**Comment by tranquochuy29** [comment]
Hi there,

I'm sorry. I forgot to check my email.
Yes, you're right. Your advice can help me to solve that problem.
Because I use so many different libraries in my webiste. Perhaps, there is a little bit conflict.
Thank you so much for your help.

Cheer,
Tony
