### ISSUE TITLE
How to pass column editor to column from ajax query

### ISSUE THREAD

**Issue by vasiliyaltunin** [olifolkerd/tabulator#523]
I using this code to load columns and rows to table:

`var TabulatorTableInit = 0;

jQuery(document).ready(function ($) {

    var groupBys;
    var tableColumnsData;
    var initTable;
    var updateTable;

    gotoRecord = function (id)
    {
        document.location = "/index.php?option=com_inventory&view=inventory_form&layout=edit&listid=" + listid + "&id=" + id;
    }

    var selectEditor = function (cell, onRendered, success, cancel, editorParams) {
        //cell - the cell component for the editable cell
        //onRendered - function to call when the editor has been rendered
        //success - function to call to pass the succesfully updated value to Tabulator
        //cancel - function to call to abort the edit and return to a normal cell
        //editorParams - editorParams object set in column defintion

        //create and style editor
        var editor = $("<select><option value=''></option><option value='male'>male</option><option value='female'>female</option></select>");
        editor.css({
            "padding": "3px",
            "width": "100%",
            "box-sizing": "border-box",
        });

        //Set value of editor to the current value of the cell
        editor.val(cell.getValue());

        //set focus on the select box when the editor is selected (timeout allows for editor to be added to DOM)
        onRendered(function () {
            editor.focus();
        });

        //when the value has been set, trigger the cell to update
        editor.on("change blur", function (e) {
            success(editor.val());
        });

        //return the editor element
        return editor;
    };

    doInventSearch = function ()
    {
        var adata = ajaxParams;
        adata['id'] = $("#vid").val();
        adata['listid'] = listid;

        adata[token] = "1";

        registerAjax();
        $.ajax({
            url: "/index.php?option=com_inventory&task=ajax_inventory.getAllColumns",
            type: 'GET',
            cache: false,
            dataType: "json",
            data: adata,
            error: function (xhr, status, error) {
                alert("Ошибка запроса: " + error + " Статус: " + status + " Ответ: " + xhr.responseText);
                unRegisterAjax();
            },
            success: function (response) {

                console.log(response);

                tableColumnsData = response;
                groupBys = response[2];

                if (TabulatorTableInit === 0)
                {
                    initTable();
                    TabulatorTableInit++;
                } else
                {
                    updateTable();
                }

            }
        });

    }

    updateTable = function ()
    {
        $("#listtable").tabulator("setColumns", tableColumnsData[0]);

        $("#listtable").tabulator("clearSort");
        $("#listtable").tabulator("setSort", tableColumnsData[1]);

        $("#listtable").tabulator("setData", "/index.php?option=com_inventory&task=ajax_inventory.getAllInvent",
                ajaxParams);
    }

    initTable = function ()
    {

        registerAjax();
        $("#listtable").tabulator({
            locale: true,
            langs: {
                "ru": {
                    "ajax": {
                        "loading": "Загрузка", //ajax loader text
                        "error": "Ошибка", //ajax error text
                    },
                }
            },
            height: "450px",
            progressiveRender: true,
            movableCols: true,
            fitColumns: true,
            groupBy: groupBys,
            groupHeader: function (value, count, data) {
                //value - the value all members of this group share
                //count - the number of rows in this group
                //data - an arrya of all the row data objects in this group

                return value + "<span style='color:#000; margin-left:10px;'>(" + count + ")</span>";
            },
            dataGrouped: function (groups) {
                groups.forEach(function (group) {
                    group.getElement().on("click", function (e) {
                        group.toggle();
                    });
                });
            },
            dataLoading: function (data, params) {
            },
            dataLoaded: function (data) {
                $("#a_overlay").hide();
                $("#ajax_cnt_big").hide();
                unRegisterAjax();
            },
            tableBuilt: function () {
                updateTable();

            },
            ajaxResponse: function (url, params, response) {
                return response;
            },
            rowClick: function (e, row) {
                gotoRecord(row.getIndex());
                registerAjax();
            },
        });

        $("#listtable").tabulator("setLocale", "ru"); //set locale to rus
    }

    doInventSearch();

});`

Now i need for few columns have combobox filters with uniq values from rows from this colums to fast and easy filtering.

i try to just test editor and add `selectEditor ` function just to test how it looks like, and also i change all comuns, for now, to test how it works, here JSON for columns:
`
0	[4]
0	Object
title	"user"
field	"name"
headerFilter	"input"
editor	"selectEditor"
1	Object
title	"Date"
field	"date"
headerFilter	"input"
editor	"selectEditor"
2	Object
title	"Cat
field	"cat"
headerFilter	"input"
editor	"selectEditor"
3	Object
title	"Text"
field	"text"
headerFilter	"input"
editor	"selectEditor"
1	[1]
0	Object
column	"name"
dir	"asc"
2	null
`
But i get this error when i load this page:

**Editor Error - No such editor found:  selectEditor**

I think it just because i pass editor as string, but there no other way to pass it as object to JSON.

So how i can pass editor to column???

**Comment by olifolkerd** [comment]
Hey,

This is happening because you are trying to access the editor that you have defined in a function using a string literal.

To load it in this way you will need to add the editor as an extension to the edit module, this will allow you to access it with a string

```js
Tabulator.extendExtension("edit", "editors", {
    selectEditor:function(cell, onRendered, success, cancel, editorParams){
        //your editor code goes here
    },
});
```

for more information see the [Edit Extension Documentation](http://olifolkerd.github.io/tabulator/docs/#extension-edit)

Let me know if that helps

Cheers

Oli

**Comment by vasiliyaltunin** [comment]
Ok, i add this code:

`  Tabulator.extendExtension("edit", "editors", {
        selectEditor: function (cell, onRendered, success, cancel, editorParams) {
        //cell - the cell component for the editable cell
        //onRendered - function to call when the editor has been rendered
        //success - function to call to pass the succesfully updated value to Tabulator
        //cancel - function to call to abort the edit and return to a normal cell
        //editorParams - editorParams object set in column defintion

        //create and style editor
        var editor = $("<select><option value=''></option><option value='male'>male</option><option value='female'>female</option></select>");
        editor.css({
            "padding": "3px",
            "width": "100%",
            "box-sizing": "border-box",
        });

        //Set value of editor to the current value of the cell
        editor.val(cell.getValue());

        //set focus on the select box when the editor is selected (timeout allows for editor to be added to DOM)
        onRendered(function () {
            editor.focus();
        });

        //when the value has been set, trigger the cell to update
        editor.on("change blur", function (e) {
            success(editor.val());
        });

        //return the editor element
        return editor;
        },
    });
`
my JSON
`
0	[4]
0	Object
title	"Пользователь"
field	"name"
headerFilter	"true"
editor	"selectEditor"
1	Object
title	"Дата"
field	"date"
headerFilter	"true"
editor	"selectEditor"
2	Object
title	"Категория"
field	"cat"
headerFilter	"true"
editor	"selectEditor"
3	Object
title	"Описание работ"
field	"text"
headerFilter	"true"
editor	"selectEditor"
1	[1]
0	Object
column	"name"
dir	"asc"
2	null
`

and i still have error:

**Filter Error - Cannot build header filter, No such editor found:  selectEditor tabulator.min.js:3:20331**

**Comment by olifolkerd** [comment]
you must include the ```Tabulator.extendExtension...``` line before you setup your table, did you do that?

**Comment by vasiliyaltunin** [comment]
Yes, here how my code looks like now:

`var prosroch = 0;
var istek = 0;

var gotoRecord;
var listid;

var TabulatorTableInit = 0;


jQuery(document).ready(function ($) {

    var groupBys;
    var tableColumnsData;
    var initTable;
    var updateTable;




    doInventSearch = function ()
    {
        var adata = ajaxParams;
        adata['id'] = $("#vid").val();
        adata['listid'] = listid;

        adata[token] = "1";


        registerAjax();
        $.ajax({
            url: "/index.php?option=com_inventory&task=ajax_inventory.getAllColumns",
            type: 'GET',
            cache: false,
            dataType: "json",
            data: adata,
            error: function (xhr, status, error) {
                alert("Ошибка запроса: " + error + " Статус: " + status + " Ответ: " + xhr.responseText);
                unRegisterAjax();
            },
            success: function (response) {

                console.log(response);


                tableColumnsData = response;
                groupBys = response[2];

                if (TabulatorTableInit === 0)
                {
                    initTable();
                    TabulatorTableInit++;
                } else
                {
                    updateTable();
                }

            }
        });

    }

    updateTable = function ()
    {
        $("#listtable").tabulator("setColumns", tableColumnsData[0]);

        $("#listtable").tabulator("clearSort");
        $("#listtable").tabulator("setSort", tableColumnsData[1]);

        $("#listtable").tabulator("setData", "/index.php?option=com_inventory&task=ajax_inventory.getAllInvent",
                ajaxParams);
    }

    initTable = function ()
    {

    Tabulator.extendExtension("edit", "editors", {
        selectEditor: function (cell, onRendered, success, cancel, editorParams) {
        //cell - the cell component for the editable cell
        //onRendered - function to call when the editor has been rendered
        //success - function to call to pass the succesfully updated value to Tabulator
        //cancel - function to call to abort the edit and return to a normal cell
        //editorParams - editorParams object set in column defintion

        //create and style editor
        var editor = $("<select><option value=''></option><option value='male'>male</option><option value='female'>female</option></select>");
        editor.css({
            "padding": "3px",
            "width": "100%",
            "box-sizing": "border-box",
        });

        //Set value of editor to the current value of the cell
        editor.val(cell.getValue());

        //set focus on the select box when the editor is selected (timeout allows for editor to be added to DOM)
        onRendered(function () {
            editor.focus();
        });

        //when the value has been set, trigger the cell to update
        editor.on("change blur", function (e) {
            success(editor.val());
        });

        //return the editor element
        return editor;
        },
    });


        registerAjax();
        $("#listtable").tabulator({
            locale: true,
            langs: {
                "ru": {
                    "ajax": {
                        "loading": "Загрузка", //ajax loader text
                        "error": "Ошибка", //ajax error text
                    },
                }
            },
            height: "450px",
//            persistentLayout: true,
//            persistentLayoutID: "inventory_meria_zayav",
            progressiveRender: true,
            movableCols: true,
            fitColumns: true,
            groupBy: groupBys,
            groupHeader: function (value, count, data) {
                //value - the value all members of this group share
                //count - the number of rows in this group
                //data - an arrya of all the row data objects in this group

                return value + "<span style='color:#000; margin-left:10px;'>(" + count + ")</span>";
            },
            dataGrouped: function (groups) {
                groups.forEach(function (group) {
                    group.getElement().on("click", function (e) {
                        group.toggle();
                    });
                });
            },
            dataLoading: function (data, params) {
            },
            dataLoaded: function (data) {
                $("#a_overlay").hide();
                $("#ajax_cnt_big").hide();
                unRegisterAjax();
            },
            tableBuilt: function () {
                updateTable();

            },
            ajaxResponse: function (url, params, response) {
                return response;
            },
            rowClick: function (e, row) {
                gotoRecord(row.getIndex());
                registerAjax();
            },
        });

        $("#listtable").tabulator("setLocale", "ru"); //set locale to rus
    }


    doInventSearch();

});`

If i click on cell it actually shown editor, but i dont need it there i only need that checkbox on header so i can filter table by it values, and it still show error:

`Filter Error - Cannot build header filter, No such editor found:  selectEditor`

**Comment by olifolkerd** [comment]
could you post an example of the column definition object you are passing to the table

**Comment by vasiliyaltunin** [comment]
Ok, i will make working demo for you.
