### ISSUE TITLE
Like filter and null values

### ISSUE THREAD

**Issue by MaksMshn** [olifolkerd/tabulator#525]
Applying "like" filter to fields containing null values causes:

Uncaught TypeError: Cannot read property 'toLowerCase' of null

**Comment by olifolkerd** [comment]
thanks for the headsup, i will get that fixed in the next release.

Cheers

Oli

**Comment by olifolkerd** [comment]
This has now been fixed in toady's 3.3 release :)

**Comment by SteveDeFacto** [comment]
@olifolkerd Problem doesn't appear to be fixed in version 3.3.3?

**Comment by olifolkerd** [comment]
Hi @SteveDeFacto 

Have you tried the latest version, 3.4.6?

Cheers

Oli :)
