### ISSUE TITLE
Expand / collapse within a cell

### ISSUE THREAD

**Issue by GerritKnippschild** [olifolkerd/tabulator#526]
Hi Oli,

does Tabulator.js support  expand / collpase function within a cell. I have attached a screenshot to illustrate the idea:
![image](https://user-images.githubusercontent.com/8235074/29519302-34d22898-867d-11e7-9fe0-573e43b1b957.png)

We have some very long text in some rows, this is why we would like to clip the text after 100 words and add a "Read more" link to expand the entire text in the respective cell if required.

Thank you very much in advance.

Kind regards,
Gerrit

**Comment by olifolkerd** [comment]
hey, you could use a custom formatter to add the "Read More" links into the cell. 

you would just need to make sure that when the link is pressed, after the extra content is shown it calls the following function to redraw the rows height correctly:

```js
cell.getRow().normalizeHeight()
```

Let me know if that helps

Cheers

Oli

**Comment by GerritKnippschild** [comment]
Hi Oli,

thank you very much. It is working very well.

Cheers, Gerrit
