### ISSUE TITLE
headerFilter for Multiple values

### ISSUE THREAD

**Issue by isadeveloper** [olifolkerd/tabulator#527]
Hi all,

I have succeeded in adding a select headerFilter to my table, however it can only filter for one value. I am looking to add a filter for a list of countries, where the user can filter based on more than one country, e.g. the user could filter observations for India, Australia and Poland, instead of just India.

Is there any way to achieve this? I've looked at issue #147 but havent been able to get it to work for the updated Tabulator js. 

This is an example of my js code, but I am using the year column as an example (too many countries):

`<script type="text/javascript">
      var yearEditor = function(cell, onRendered, success, cancel, editorParams){
 
        var editor = $('<select id="filter-year" multiple="multiple"><option value=""></option><option value="2005">2005</option><option value="2006">2006</option><option value="2007">2007</option><option value="2008">2008</option><option value="2009">2009</option><option value="2010">2010</option><option value="2011">2011</option><option value="2012">2012</option><option value="2013">2013</option><option value="2014">2014</option><option value="2015">2015</option><option value="2016">2016</option></select>');
        editor.css({
          "padding":"3px",
          "width":"100%",
          "box-sizing":"border-box",
        });

       
        editor.val(cell.getValue());

       
        onRendered(function(){
          editor.focus();
        });

       
        editor.on("change blur", function(e){
          success(editor.val());
        });

    
        return editor;
      };
     
      
      $("#main-table").tabulator({
        height:"600px",
        fitColumns:true,
        pagination:"local",
        paginationSize:100,
        placeholder:"No Data Set",
        selectable:true,
        columns:[
          {title:"Country Name", field:"contname", sorter:"string", width:200, frozen:true},
          {title:"Country Code", field:"contcode", sorter:"string", align:"center"},
          {title:"Year", field:"year", sorter:"number", align:"center", editor:yearEditor, headerFilter:true},
          {title:"Trade (% GDP)", field:"trade_gdp", sorter:"number", align:"center"}, 
          ]
      });`

**Comment by olifolkerd** [comment]
Hey,

you could use a standard input element filter, and allow the user to enter a comma delimited list, then use a custom filter function to look for any item in the list:


```js
//custom filter function
function matchAnyFilter(headerValue,cellValue, rowData, filterParams){
    //headerValue - the value of the header filter element
    //cellValue- the value of the column in this row
    //rowData - the data for the row being filtered
    //filterParams - params object passed to the headerFilterFuncParams property

    var matched = false;
    var values = headerValue.split(","); //break header into list of options

    values.forEach(function(val){
        if(val.toLowerCase().indexOf(cellValue.toLowerCase()) > -1){
            matched = true;
        }
    });

    return matched;
}

//column definition
{title:"Country Name", field:"contname", sorter:"string", width:200, headerFilter:"input", headerFilterFunc:matchAnyFilter },
```

let me know if that helps,

Cheers

Oli

**Comment by isadeveloper** [comment]
Works perfectly, thanks! 👍

**Comment by AkshayaBrianTauro** [comment]
Hi All,

I'm able to make the functionality(filter data by selecting multiple values in the header filter dropdown) work successfully, this is how columns headers has been defined: 'select' for headerFillter, 'in' operator for headerFilterFunc, and for headerFilterParams provide following as values {values:true, multiselect:true}

**Example:**
   {
      field: "book_name",
      width: 390, 
      title: "Book Name",
      **headerFilterPlaceholder: " ",
      headerFilter: 'select',
      headerFilterFunc:"in",
      headerFilterParams: {values:true,   sortValuesList:"asc",   multiselect:true},**
      editor: "input",
      editorParams: {
        allowEmpty: true       
      },
    },

Thanks,
Akshaya

**Comment by sahil-singla-03** [comment]
Wow @AkshayaBrianTauro. Thanks for the solution.

**Comment by DenishTechtic** [comment]
Not working with Tabulator 5.5
