### ISSUE TITLE
showColumn/hideColumn fails in combination with persistentLayout

### ISSUE THREAD

**Issue by bparquet** [olifolkerd/tabulator#528]
If the table is created with persistentLayout: true option, calling showColumn or hideColumn triggers an exception.

The problem is in Column.prototype.show and Column.prototype.hide, "self.table" should be "this.table"

I reproduced the problem here: https://jsfiddle.net/bparquet/a970azmv/

**Comment by olifolkerd** [comment]
Hey,

Great spot, i have just pushed a fix for this to the master branch, i will include it in the next release.

Thanks for the heads up!

Cheers

Oli
