### ISSUE TITLE
Table height

### ISSUE THREAD

**Issue by kurtknippschild** [olifolkerd/tabulator#529]
Hi Oli,

One question,
I set the height of the table dynamic:
var tableHeight = $(window).height() - 420;
height: tableHeight, 
After a resize of the Window-height and a redraw of the table how can i set the new table-height?

With best thanks in advance.

Kurt

**Comment by olifolkerd** [comment]
there is a ***setHeight*** function you can call on the table:
```js
$("#example-table").tabulator("setHeight", $(window).height() - 420);
```

**Comment by ryc16** [comment]
Hi,

I did the same above and called redraw to resize the table shown below

```
$("#example-table").tabulator("setHeight", $(window).height() - 420);
$(window).resize(() => { $("#example-table").tabulator("redraw", true); });
```

"setHeight" is working but redraw doesn't seem working while resizing chrome. I confirmed `$(window).resize(() => { $("#example-table").tabulator("redraw", true); }) `got called.

I am using angular with tabulator v3.1.1 

Thanks

**Comment by olifolkerd** [comment]
Hey @ryc16,

Try upgrading to the latest version of Tabulator 3.2.2 as there were some issue with the redraw function in 3.1

Cheers

Oli

**Comment by ryc16** [comment]
Hey @olifolkerd, just upgrade to v3.2.2 by doing npm install jquery.tabulator@3.2.2 --save

But the height is still not changed when I resize the chrome height.

Any idea or suggestion?

Cheers

**Comment by olifolkerd** [comment]
Could you post a copy of your table constructor so i can get a better ide of what is happening.

Cheers

Oli

**Comment by ryc16** [comment]
@olifolkerd, I am using angular.io with typescript. Below is the code.
```
 ngOnInit(): void {
   $(this.table.nativeElement).tabulator(
            {
                height: "1px", // set height of table (optional)
                headerFilterPlaceholder: "...", //set column header placeholder text
                placeholder: "No Data Set", // show on the center of table when there is no data
                selectable: 1, // make single row selection
                columns: [ //Define Table Columns
                    { formatter: "rownum", align: "center", headerSort: false },
                    {
                        formatter: editIcon, width: 40, headerSort: false, align: "center",
                        cellClick: (e, cell) => { this.editMold(cell.getRow().getData()); }
                    },
                    { title: "Item<br />No.", field: "productNum", headerFilter: "input", sorter: "string", width: 100 },
                    { title: "Item<br />Description", field: "productDescription", headerFilter: "input", sorter: "string", width: 200 },
                    {
                        formatter: "buttonCross", width: 40, align: "center", headerSort: false,
                        cellClick: (e, cell) => { this.deleteMold(cell.getRow().getData()); }
                    },
                ],
            }
        );
        $(this.table.nativeElement).tabulator("setHeight", $(window).height() - 230);

        $(window).resize(() => {
            $(this.table.nativeElement).tabulator("redraw", true);
        });
}
```

Thanks
