### ISSUE TITLE
Lookup and Match

### ISSUE THREAD

**Issue by samshah777** [olifolkerd/tabulator#530]
Hey Oli,

I was wondering if the new version has a predefined lookup and match function?
I'm looking for the table to return the value of a column for the row clicked and output it into a div with ID 'output'. 

Cheers
Sam

**Comment by samshah777** [comment]
Just to be clearer,
I have 2 tables both with a common 'ID' column, clicking on the row in table 1, should match the ID for table 1 with the same ID for table 2 and output the value of a particular value in column for table 2. It works like the VLOOKUP function in excel

Cheers,
Sam

**Comment by olifolkerd** [comment]
Hey Sam,

Not directly but that would be easy to implement in code. you just need to make sure that the ***id*** field is set as the table ***index*** in the table constructor:
```js
$("#example-table").tabulator({
    index:"id",
});
```

You can then retrieve the appropriate row using the ***getRow*** function:

```js
 $("#example-table-1").tabulator({
    index:"id",
    columns:[...],
    rowClick:function(e, row){
        var otherRow =  $("#example-table-2").tabulator("getRow", row.getIndex());
        alert(otherRow.getData()["other-column"]); //alert with data from the other tables column value in matching row
    }
});
```

Let me know if that helps

Cheers

Oli

**Comment by samshah777** [comment]
Thank you Oli. That works great !

Also curious if there is a predefined write handler into the cells. For example: If I want to 'write' the value from the other table into one of the columns of table 2, how would that go ?

I know I could write a function with document.write but how do I reference the cell in the table I want to write to ? Via the formatter parameter?

Regards,
Sam

**Comment by olifolkerd** [comment]
if you have the cell component for that cell you can call the ***setValue*** function on it, so from the example above:
```js
 $("#example-table-1").tabulator({
    index:"id",
    columns:[...],
    rowClick:function(e, row){
        var field = "column-field" //filed name of column you are copying
        var otherRow =  $("#example-table-2").tabulator("getRow", row.getIndex());

        row.getCell(field).setValue(otherRow.getData()[field]); //copy value from matching cell in other table to this cell
    }
});
```

If you want to be able to to it based on a clicking in a specific cell in the table rather than a row, let me know and i can show you how to do that as well.


Cheers

Oli

**Comment by samshah777** [comment]
Yes, this is kind of what I was asking about. 

I'm trying to understand this line-
`row.getCell(field).setValue(otherRow.getData()[field]);`
The first 'field' is the variable from the previous line and the second 'field' is the target cell's field name that I should define??

What I want to do is match ID from table 1 to table 2, get value of column from corrosponding row of table 2 and write into the next cell of table 2.  

Cheers,
Sam

**Comment by samshah777** [comment]
Sorry there's a typo

What I want to do is match ID from table 1 to table 2, get value of column from corrosponding row of table 2 and write into the next COLUMN of table 2.

**Comment by samshah777** [comment]
I understand now and have solved the issue. Thank you for the help Oli

Cheers,
Sam
