### ISSUE TITLE
Export to Excel multiple table data into one worksheet of xlsx

### ISSUE THREAD

**Issue by ramyadv** [olifolkerd/tabulator#531]
i have three table in one screen and i want to download  all this  data into single xlsx file.
is der any Option of having such kind of download

thanks

**Comment by olifolkerd** [comment]
Hey,

Great question, at the moment there is no way to o this directly though it is something im looking into.

In the mean time it should be fairly easy to create a function to do this yourself. you can use the ***getData*** function on each of the tables to return arrays of the table data.

Then you could use the xlsx downloader function as example to build tour own spreadsheet with multiple sheets. if you have a look in the src/js/sxtensions/download.js file you will find the xlsx file generation function from line 165. It wouldnt take much work to adapt this to iterate over several arrays generating a sheet for each.

Inter table functionality is something i am looking at now and is on the roadmap for a releasing in 2 to 3 versions time.

let me know if that helps,

Cheers

Oli

**Comment by gnasit** [comment]
any update on this?

**Comment by olifolkerd** [comment]
Hey @gnasit 

It will be at least next year before i can add in this functionality im afraid, the next 2 releases are already outlined in the roadmap, and i wouldn't have the time for the additional feature.

at the moment i am releasing a new version aproximatly every 2 months.

Sorry it isnt better news,

Oli

**Comment by olifolkerd** [comment]
Hey @ramyadv and @gnasit 

You will be happy to hear i have just push an update with this functionality to the 3.5 branch. it allows you to pass the tables and the tab names to the options object in the download function:
```js
var sheets = {
    "Accounts Data": "#accounts-table", //first tab with table set using a query selector
    "Example Data": this, //second tab, generated from this table
    "Finance Data" : $("#finance-table"), //third tab with table set to JQuery element
};

$("#example-table").tabulator("download", "xlsx", "AllData.xlsx", {sheets:sheets}); //download a Xlsx file that has a tab for each table
```
Version 3.5 will not be officialy released for a couple of weeks yet, but i am keeping a version of the documentation updated as i work on 3.5, you can find out more [Here](http://tabulator.info/docs/3.5#download)

Let me know how you get on.

Cheers

Oli :)
