### ISSUE TITLE
Dogge cell Value

### ISSUE THREAD

**Issue by kurtknippschild** [olifolkerd/tabulator#533]
Hi Oli,

have you an example for a cellClick:function(e,cell) that toggle the value of a cell from a  cell there is no visible and back.
This are my example-table:
		$("#tabulator_example").tabulator({
		    height: 400,
		    columnMinWidth: 20,
		    fitColumns:true, 
		    resizableColumns:false,
		columns:[
		{title:"Description_long", field:"description_long", visible:false},
		{title:"Description", field:"description_short", headerSort:false, align:"left" formatter:"textarea", cellClick:function(e,cell) {
      				**toggle between the value of field:"description_long" and field: "description_short"**
				},
			],
		});	

Thanks in advance.

Kurt

**Comment by kurtknippschild** [comment]
Hi Oli,

i have change the cellClick.function(e, cell) to:

				var data = cell.getData();
      				cell.setValue(data.description_long);
      				cell.getRow().normalizeHeight();

that's work fine.

Now i need only a idea for the toggle.

Thanks in advance.

Kind regards,

Kurt

**Comment by olifolkerd** [comment]
To get the value of another cell in the row you can use ```cell.getData['field-name']``` so if we assume you create another parameter in the cell data to hold the state of the column you want to change you could do something like this:
```js
cellClick:function(e,cell) {
    var data = cell.getData();
    data.cellState = !data.cellState; ////set the cellstate paramter that will hold which of he two columns should be referenced on click
    
    //set cell value to one of the two columns
    cell.setValue(data.cellState ? data.description_long : description_short);
},
```

Let me know if that helps

Cheers

Oli
