### ISSUE TITLE
Calculated columns (ignoring pagination)

### ISSUE THREAD

**Issue by mhaddy** [olifolkerd/tabulator#534]
I have a #question wrt the ability for the new Tabulator 3.2 functionality of 'Calculated Columns' to display the data including the filtering but ignoring the pagination. My use case is such that I have, for example, >3000 rows across 10 pages, let's say. I have filtering enabled and header filtering enabled, so I'd like to see how many records contain the text "blue" in their description but as this is common, its results are spread across many pages. Unfortunately, the calculated columns is only showing the # of rows on that page instead of across the entire dataset.

Is there a way to adjust this?

**Comment by olifolkerd** [comment]
Hey,

The column calculations in paginated for are set to work on only the currently visible page. im afraid there is no option to change this at the moment.

though you could make changes to the page extension if you wanted to force this behaviour

Cheers

Oli
