### ISSUE TITLE
Multi-Sort

### ISSUE THREAD

**Issue by CBlakeButler** [olifolkerd/tabulator#536]
Curious if it is possible already or on the roadmap to do multi-sort? I previously used https://www.dynatable.com/ which I migrated to Tabulator from due to lack of ongoing support. One of my favorite features that I have not been able to recreate with Tabulator is the ability to sort on multiple fields at once using a CTRL+Click. Any help is greatly appreciated.

Best,
CB

**Comment by olifolkerd** [comment]
Hey,

It is on the roadmap, depending on time it will be in one of the next two releases.

If it is urgent i could show you how to code in a workaround with the current version.

Cheers

Oli

**Comment by CBlakeButler** [comment]
Not urgent, but I'm very interested in adding it to a solution when you have a moment to share. Glad to test the feature addition once implemented as well!

Best,
CB

**Comment by olifolkerd** [comment]
Hey @CBlakeButler 

You will be happy yo hear that today's 3.3 release contains multi column header sorting. Holding ***ctrl*** or ***shift*** while clicking on header columns allows you to sort by multiple columns.

Cheers

Oli :)

**Comment by C2BB** [comment]
Thank you for adding this feature Oli! However I am unable to make it work. Using Chrome and updated to the latest 3.3. Do any settings need to be defined to enable this behavior?
