### ISSUE TITLE
using datalist in each cell

### ISSUE THREAD

**Issue by hadikmsh** [olifolkerd/tabulator#538]
hi
tanks for your lovely library.
i need a peace of advice about how to use HTML datalist in each cell.
i tried it with custom editor but it did not work correctly.

**Comment by olifolkerd** [comment]
Hey,

No problem, im happy to help.

would you mind posting a copy of the editor you tried and i can see if i can suggest some tweaks

Cheers

Oli

**Comment by hadikmsh** [comment]
Hi 
this is my function : 
var hhh = function(cell, onRendered, success, cancel, editorParams){
            //cell - the cell component for the editable cell
            //onRendered - function to call when the editor has been rendered
            //success - function to call to pass the succesfully updated value to Tabulator
            //cancel - function to call to abort the edit and return to a normal cell
            //editorParams - editorParams object set in column defintion

            //create and style editor
            var editor = $("<input list='datalist'><datalist id='datalist'><option value='1'><option value='2'><option value='3'></datalist>");
            editor.css({
                "border": "1px",
                "background": "transparent",
                "padding": "4px",
                "width": "100%",
                "box-sizing": "border-box",
            });

            //Set value of editor to the current value of the cell
            editor.val(cell.getValue());

            //set focus on the select box when the editor is selected (timeout allows for editor to be added to DOM)
            onRendered(function(){
                editor.focus();
            });

            //when the value has been set, trigger the cell to update
            editor.on("change blur", function(e){
                success(editor.val());
            });

            //return the editor element
            return editor;
        };


its now work.
thanks for your response.
