### ISSUE TITLE
Adding rows from JSON

### ISSUE THREAD

**Issue by codevite** [olifolkerd/tabulator#54]
If I create the Tabulator from Html table, how I set it as Editable?

**Comment by olifolkerd** [comment]
Ho codevite,

sorry for not getting back to you for a while, ive been away with work. i will post an explanation of how to do this, this evening.

Oli

**Comment by olifolkerd** [comment]
There is no direct way to do this in the constructor at present, however once the table has been built, you can extract the column definition array, update it and assign the changes like follows:

#### HTML
```html
<table id="example-table-table">
		<thead>
			<tr>
				<th width="200">Name</th>
				<th>Age</th>
				<th>Gender</th>
				<th>Height</th>
				<th>Favourite Color</th>
				<th>Date of Birth</th>
				<th>Likes Cheese</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>Oli Bob</td>
				<td>12</td>
				<td>male</td>
				<td>1</td>
				<td>red</td>
				<td></td>
				<td>1</td>
			</tr>
			<tr>
				<td>Mary May</td>
				<td>1</td>
				<td>female</td>
				<td>2</td>
				<td>blue</td>
				<td>14/05/1982</td>
				<td>true</td>
			</tr>
		</tbody>
	</table>
```
#### Javascript
```js

//convert table to tabulator
$("#example-table-table").tabulator({});

//get column definition array
var cols = $("#example-table-table").tabulator("getColumns");

//update definition to make cells editable
cols.forEach(function(col){
	col.editable = true;
});

//assign new column definitions to Tabulator
$("#example-table-table").tabulator("setColumns", cols);
```

I am looking at adding a more elegant way to handle this in future. I am currently thinking of designing it so you can define the column definitions array and have them override those created from the table,

Any thoughts or feedback on this would be great.

Cheers

oli

**Comment by codevite** [comment]
That works fine. It does what I need.
Thank you a lot.
