### ISSUE TITLE
Multiple row selection using ( ctrl+ on mouse left click ) on row ???

### ISSUE THREAD

**Issue by azizur-rahman** [olifolkerd/tabulator#541]
I'm using tabulator, it's fine till now.Okay, now I want an event that will select multiple rows. 
I'w press ctrl and click by mouse on those rows that will be selected and rest of rows will be deselected.
When I'w click on the row without ctrl key then only one row will select.

Will you help me by reply with proper samples

Cheers
Azizur

**Comment by olifolkerd** [comment]
Hey,

The select rows example on the [Tabulator Website](http://olifolkerd.github.io/tabulator/examples/#selectable) does exactly what you are after.

Cheers

Oli
