### ISSUE TITLE
Background color of colom with value

### ISSUE THREAD

**Issue by ravikanth143** [olifolkerd/tabulator#543]
To have a background color of column other than value (Show value and background color both).
I had a requirement to show a column with different color (Just to differentiate editable and non-editable coloms), so have added below code after Line 9147 in tabulator.js.

backcolor: function backcolor(cell, formatterParams) {

		  cell.getElement().css({ "background-color": formatterParams.backcolor});

		  return cell.getValue();
	  },

And in tabulator binding code create column with below properties.

{ title: "Spent ($)", field: "spentbudget", width: 120, editable: true, formatter: "backcolor", formatterParams: { backcolor: "#e6ffe6" } },

Thanks,
Ravikanth

**Comment by olifolkerd** [comment]
Hey,

Thanks for getting in touch.

Did you know that Tabulator has an extension mechanism that lets you add your own default formatters without having to change the source code.

In this case it would be:
```js
Tabulator.extendExtension("format", "formatters", {
    backcolor:function(cell, formatterParams){
        cell.getElement().css({ "background-color": formatterParams.backcolor});
	return cell.getValue();
    },
});
```

You just need to add that script after you have imported the tabulator library but before your table definition.

This has the added benefit of allowing you to pull in updated tabulator libraries without overwriting your changes.

Full information on formatters can be found in the [Documentation](http://olifolkerd.github.io/tabulator/docs/#extension-format)

Cheers

Oli

**Comment by diffcultpro** [comment]
Or if i want change the row background-Color， how to do it ？

**Comment by olifolkerd** [comment]
you can use the ***rowFormatter*** to do this.

you can either set the background color directly on the row:
```js
$("#example-table").tabulator({
    columns:[...],
    rowFormatter:function(row){
         row.getElement().css({"background-color":"#A6A6DF"});
    },
});
```

or use the row formatter to set a class on the row and then add the css styling yourself:
```js
 row.getElement().addClass("blue-row");
```

Let me know if that helps

Cheers

Oli
