### ISSUE TITLE
Column Resizing Breaking Cell Functionality

### ISSUE THREAD

**Issue by stack-its** [olifolkerd/tabulator#544]
Hi Oli,

Having a tough time w/ column resizing.  I want to allow it.  I have set:
`resizableColumns:"header",`

as resizing controls within just the columns seems logical.  When a column is resized, it tends to mess up columns that I am showing & heights go crazy.  I added this to hopefully redraw the table and fix stuff:
`columnResized:function(column) {
        //column - column component of the resized column
        $('#mytableid').tabulator('redraw', true);
        console.log('Redraw All from colResize');
  },`

Unfortunately, after resizing a column, my custom modals & the 1st column w/ custom column shows are not running when clicking cells.  It seems resizableColumns is being applied to cells which is not what I set.
Can you give me a patch for this, please.   Thanks, again.  Bill

**Comment by olifolkerd** [comment]
Could you post a copy of your table constructor

**Comment by stack-its** [comment]
It's huge & I am really concerned about showing proprietary code in open like this.  Is there a certain piece of it that you need? or we could do a screen share easily.

**Comment by olifolkerd** [comment]
The column definition for the column that is not residing correctly would be a good start

**Comment by stack-its** [comment]
Oh man, that's 200 lines for the columns definition & where most of the proprietary stuff is ;)
The problem is not that they don't resize, it's that the columnResized function tends to prevent all my other custom stuff from running.

**Comment by olifolkerd** [comment]
Im afraid it is quite hard to diagnose the problem without anything to test against.

My first suggestion would be that if you are altering the height of elements in the column you should set the ***variableHieght*** property in the column definition for that column to ***true***, that will cause it to resize the cells to fit their content.

if that dosn't work you could look at using the ***normalizeHeight*** function on the affected row components.

When you say the height "goes crazy" what do you mean, are the cells in the row different heights, or do the cells suddenly take up the entire height of the table. If it is the latter it is worth noting that you should use % heights on cells or their contents as this can lead to them rendering badly.

Cheers

Oli

**Comment by stack-its** [comment]
Let me show you what's happening, maybe this will shed some light on a solution:
https://www.dropbox.com/s/it7tiysxs412gkz/003.mov.zip?dl=0
Let me know you got the vid & I'll take it down - thanks,  Bill

**Comment by olifolkerd** [comment]
Thanks for sending over the video.

It looks like something about the setup of the table, likely the significant custom row formatting functionality, is interacting badly with the column resize functionality. 

I would say that calling the ***redraw*** function after a column resize may well result in unusual behaviour,

Unfortunately in this instance the table is so heavily customised im afraid there is no way i can offer you a solution without the source to test against.

What i would suggest as a first step, is start with a standard un-customised table setup and column definitions and reintroduce your features one at a time until the issues start appearing, then you can isolate where the unusual interaction is coming in.

Are you getting any errors or warnings in the console log at any point?

if you can find that then i can probably tell you how to resolve it.

Cheers

Oli

**Comment by stack-its** [comment]
Ok, I appreciate you looking at this - I don't see any errors that would help w/ debugging.
Short of spending several weeks rebuilding & debugging, I'll just rely on users setting column minWidth & turn off column resizing, just to save what last brain cells I have left ;)
... Maybe when I have more time, I'll try to revisit this.  Thanks, again

**Comment by olifolkerd** [comment]
Ok no probs, sorry i couldn't be more help
