### ISSUE TITLE
visual constructor  for generate all kinds of tasks requirements

### ISSUE THREAD

**Issue by bambus1980** [olifolkerd/tabulator#546]
Will be cool if tabulator have an interactive visual designer for ability of creating table with rapid technologies used for many visual website creaters and programming IDEs as sample in Delphi, Visual Studio, but in borders of Tabulator functions.

**Comment by bambus1980** [comment]
I have an idea and can share it with developers.

**Comment by bambus1980** [comment]
sample: https://webix.com/form-builder/

**Comment by olifolkerd** [comment]
Hey,

Thanks for getting in touch, that is an interesting idea you have there.

Tabulator has a huge array of options available to configure the table, which ones would you see being available in the tool?

Cheers

Oli

**Comment by bambus1980** [comment]
It will be excellent add all functions, but the most important is made it very easy for understanding and no extra overloaded elements. In other words it would be simple and gracefully.

**Comment by bambus1980** [comment]
sample process can be viewed as:
1. creating table (white box) with main parameters: datasource, etc.
2. new standard table with data will appear near of the box.
3. right click on the box and select "add option1" and input option1 parameters. New leaf of the box will be created with this option.
4. rigth click on the option leaf and able to create another leaf with suboptions, etc.
5. after adding all options and parameters to the box you got boxes tree which all tabulator options, theme, properties.
Sorry for my english, writing as I imagine it.

**Comment by bambus1980** [comment]
main feature is intellisence ability on each of steps.

**Comment by olifolkerd** [comment]
Hey @bambus1980 

As Tabulator has grown, so has its feature set. 

I still love your idea and think it would be a great tool for people to use, but at this point i think there are now so may ways to configure Tabulator that to build and maintain this tool would be a full time job in itself.

For that reason i am going to have to opt out of implementing it myself on the Tabulator site. But if you had the time and wanted to develop it i would be happy to provide technical support and to link to it from the Tabulator site.

Thanks for your input

Cheers

Oli :)
