### ISSUE TITLE
cell editor to be displayed only on left click!

### ISSUE THREAD

**Issue by madhumithavenkat** [olifolkerd/tabulator#547]
hi oli,
is there a way to enable the editor on left click only??

**Comment by olifolkerd** [comment]
Hey,

Im not sure what you mean, the editor is triggered by a left click. what actions are you hoping to disable?

Cheers

Oli

**Comment by madhumithavenkat** [comment]
hey,
i have an editor set up in the tabulator and it gets triggered by both left and right click ! i want to disable the triggering of the editor by right click.

Thank you!

**Comment by olifolkerd** [comment]
That is definitely not intended behaviour, it must have regressed in the 3.2 release.

I will put in a fix in the 3.3 release.

As a temporary fix you could try adding a ```e.stopImmediatePropagation()``` call into the ***cellContext *** callback, that might prevent the edit.

Thanks for the heads up.

Cheers

Oli

**Comment by madhumithavenkat** [comment]
Hey,
thanks! .i will try adding that.
BTW we love your tabulator! Its awesome. :)
