### ISSUE TITLE
exporting xlsx column title

### ISSUE THREAD

**Issue by lenny76** [olifolkerd/tabulator#548]
hi,
how to set the column title of the exported xlsx to the field value and not to the title value?
 
{ title: "Info", field: "INFOUTILIXCONSEGNA", sorter: "string", editor: 'input', width: 250},

thanks

**Comment by olifolkerd** [comment]
You would need to create a custom downloader to do this,

I can post some example code for this if you would like.

Cheers

Oli

**Comment by lenny76** [comment]
why not to add another field like "dl-name" and so if it exist it will use this? :)

**Comment by olifolkerd** [comment]
I can certainly look at adding that as a feature in a later release, but it dosnt exist at the moment.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @lenny76 

You will be happy to hear that in today's 3.3 release you can now use the ***downloadTitle*** column definition property to set custom column titles in downloaded files:

```js
$("#example-table").tabulator({
    columns:[
        {title:"Name", field:"name", downloadTitle:"Full Name"} //change column title to "Full Name" in download
    ]
});
```

More information can be found in the [Download Documentation](http://tabulator.info/docs/3.3#download)

Thanks for the great suggestion!

Cheers

Oli :)

**Comment by alfredormorales** [comment]
Hi Oli, theres is a new about this request on 4.1 version or is on queue for next features on other next version?

Cheers
