### ISSUE TITLE
Header filter

### ISSUE THREAD

**Issue by tranquochuy29** [olifolkerd/tabulator#55]
Hi there,

I hope you're still fine.
I wish you have a good day.

I have just found out a new problem with the header filter function.
You can have a check with some below images.

1. Here is the loaded table with the some big columns.
![1](https://cloud.githubusercontent.com/assets/4382757/18341020/3857d1c8-75d2-11e6-9dc8-e9713839b005.png)
2. I scroll to the right side
![2](https://cloud.githubusercontent.com/assets/4382757/18341019/385648e4-75d2-11e6-827d-2b547ffee9eb.png)
3. I enter some text for searching on Date of birthday column. If we have no data, the format of table will be break.
![3](https://cloud.githubusercontent.com/assets/4382757/18341018/38562fda-75d2-11e6-8bfd-d6f8f98fac59.png)

I think that we have a problem with the scrollbar.
Thank you so much for your reading this issue.

Cheer,
Tony

**Comment by olifolkerd** [comment]
Hi tony, i will have a look into that for you this evening!

**Comment by olifolkerd** [comment]
I have just pushed a fix to resolve this.

Out of curiosity have you changed the css on the .tabulator or .tabulator-holder elements as that looks like the overflow styles have been changed.
