### ISSUE TITLE
Code Example for Updating Edited Cell on the Server?

### ISSUE THREAD

**Issue by c-zakkaroff** [olifolkerd/tabulator#550]
Hi Oli,

I've browsed the documentation (which is very helpful) and yet I'm unclear on what code needs to be added to send and edited cell back to the server to update the data source (MySQL database) where the data came from in the first place?

BTW, amazing work with Tabulator! Thank you very much.

Many thanks,
Constantine

**Comment by olifolkerd** [comment]
Hey Constantine,

Thanks for getting in touch. The reason that there is no specific example for this is because it depends entirely on how you want to send the data back to the server.

Some people will send back the value for a given cell when a cell is edited, others will send back a row when ever any cell on that row is edited, others will only send data back to the server when the use clicks  a save button, and then some will send the whole table back, and others will only send the updated rows back.

The will all follow the same basic design though, an action on the table or a button will trigger an ajax request to the server that will pass back the data.

You can use the ***cellEdited*** callback to catch when a cell is edited and then trigger all your actions from that.

if you have a specific case in mind i would be happy to give you some more specific pointers.

Cheers

Oli

**Comment by c-zakkaroff** [comment]
Hi Oli,

Thank you very much for your response.

Yes, out of the possible options you listed, in my case I favour the option of sending the edited cell value. Sending the whole row would do, but as you say, the design would be similar for these options.

I guess my question is about having a loot an an example how the ajax request is put together, in terms of the primary key for the row and updated values. My server talks PHP with MySQL, although it is not as important as putting the right data in the request, which I guess would have to be a POST request.

I appreciate your help and tips.

Best regards,
Constantine

**Comment by olifolkerd** [comment]
Hey,

You would need to pass any primary key into the table data. tabulator allows you to define one data field as the rows index, Using the ***index*** config option, which is by default set to the ***id*** filed.

you can then call the ***getIndex()*** function on the row component to get the index of that row,

I hope that helps

Cheers

Oli

**Comment by c-zakkaroff** [comment]
Thank you for your response once again! Yes, I understand now. I got my code working using JQuery $.post(...) method.

I'm wondering, what is the suggested approach for responding to unsuccessful requests where data in the Tabulator table should be reset to the old value (prior to editing)?

Many thanks!

**Comment by olifolkerd** [comment]
Hey,

each of the cell components in the table has an ***oldValue*** method that can be called to get its previous value, you could then use ***setValue*** to reapply this to the cell.

In the next release there will be a data validation extension to allow for advanced data entry.

Cheers

Oli

**Comment by c-zakkaroff** [comment]
Hi Oli,

Thank you for your response. I can see you've thought things through. This is a quality piece of work!

Best regards,
Constantine

**Comment by mobi35** [comment]
I can't understand how to use those function :/

Please give me a pointers

    cellEdited:function(cell){
        //This callback is called any time a cell is edidted
      	
   	alert(cell);
   	$.ajax({

   		url :"server.php",
   	 	method :"post",
   	 	data: {data:cell},
   	 	success:function() {

   	 		
   	 	}
   	

   	});
            }

How can I update the cell that I edited on my PHP file 
just like ajax posting ? How can I send the Id of the specific columns and name to my 
PHP ?

**Comment by olifolkerd** [comment]
Thanks for your kind word @c-zakkaroff

**Comment by olifolkerd** [comment]
@mobi35 
You can get the column and row components from the cell component that is passed into the callback using `cell.getColumn()` and `cell.getRow()` you can then use the ***getData***, ***getFiled***, and ***getIndex*** functions on these to get the data you need.

Checkout the documentation for [Component Objects](http://olifolkerd.github.io/tabulator/docs/#components) for more information.

Cheers

Oli

**Comment by c-zakkaroff** [comment]
@mobi35, here's a partial example from my prototyping, based on Oli's examples. The main thing is to define this callback, `cellEdited`. And in the callback one can call all those methods Oli mentioned, to their heart's content. The `url` property in the definition of the in the `ajax` call is where you want to send the data, and on the PHP side you catch the request as you'd normally deal with a POST (or GET) request. The `success` and `error` callbacks in this case just produce alert messages, but in a real world you'd put some useful code in them.

 ```javascript
      $("#example-table").tabulator({
        height: 205, // Set height of table.
        fitColumns: true, // Fit columns to width of table (optional).
        columns: [ // Define table columns.
          {title: "Name", field: "name", width: 150, editor:true},
          // ...
          // ...
        ],
        rowClick: function(e, row) { // Trigger an alert message when the row is clicked.
          alert("Row " + row.getData().id + " Clicked!");
        },
        cellEdited:function(cell){
          // This callback is called any time a cell is edited.
          $.ajax({
            url: "response-request.php?action=update",
            data: cell.getRow().getData(),
            type: "post",
            success: function(response, textStatus, xhr){
              alert("AJAX result: " + response + "; status: " + textStatus);
            },
            error: function(XMLHttpRequest, textStatus, error){
              alert("AJAX error: " + textStatus + "; " + error);
            }
          })
        },
      });
```

**Comment by BobtheIdiot** [comment]
Hi Oli,
Could you please give also give me some pointers on how to implement that cellEdited callback to an MVC controller?

I followed c-zakkaroff sample but couldn't get it to it the controller.

many thanks.

btw, great work. Thank you.

**Comment by olifolkerd** [comment]
Hey @BobtheIdiot 

I cant really offer advice on how to do things server side as that is entirely dependent on the development stack you are using and your server architecture.

As explained above you can get all the data from the edited row in the cellEedited callback by cusing the cell component.

```js
cell.getRow().getData();
```

and you can pass this back to the server with a post request, how you structure that request will be dependent on how your server is setup.

I hope that helps,

Cheers

Oli :)

**Comment by BobtheIdiot** [comment]
Thanks for the reply Oli, much appreciated.

I solved it following the example from c-zakkaroff by using single speech mark ['] instead of the ["]. Sorry, I'm new to this. 

Here's the full js. Hope it help someone using MVC and new to it like me.

` <script>
        $("#fpos-table").tabulator({
            //height: "320px",
            fitColumns: true,
            groupHeader:function(value){return value;},
            index: "orgid",
            groupBy: ["parentdeso"],

            columns: [
               { title: " ", field: "orgid", headerSort:false, visible: false },
                { title: " ", field: "parentdeso", headerSort:false, visible: false }, //sorter: "string"
                 { title: " ", field: "deso",  width:500, headerSort:false },
                    { title: "myNotes", field: "mynotes", align:"left", headerSort:false, editor: "input" },
                    {title: " ", field: "ffsv", width:200, align:"left", headerSort: false, editor: "number", formatter:"money", bottomCalc:"sum",

                        bottomCalcFormatter: function(cell, formatterParams){ return cell.getValue().toFixed(2).toString().replace(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1,");   }

                    }
            ],

            //rowClick: function (e, id, data, row) {
            //    alert("Row " + id + " Clicked!!!!");
            //},

            cellEdited: function (cell) {
                // This callback is called any time a cell is edited.
                var datax = cell.getData();
                var mynotes = datax.mynotes;
                var ffsv = datax.ffsv;
                var orgid = datax.orgid;
                var fields = cell.getField();
                $.ajax({

                    url: '@Url.Action("Action", "Crtroller")',
                    data: { 'orgid': orgid, 'mynotes': mynotes, 'ffsv': ffsv, 'fieldn': fields },
                    type: 'post'

                })
            },
        });

        $("#fpos-table").tabulator("setData", "/dciBaMain/qfpos/@ViewBag.id", { cmyyr: @Model.cmyyr, key2: "value2" });

    </script>`



Also noticed that the Cell Edited, and this could just be me, it fired at the last column when I made changes on the second column and tab out of the third/last col. 

I was expecting it to fire the Ajax right away after tabbing to next cell. 

But it could be just me being a newbie. No biggie either way, I just do switch and if statements in the controller and it works great.


Thanks again. It's an incredible app. Thank you very much for sharing.
