### ISSUE TITLE
Visual Problem with the table

### ISSUE THREAD

**Issue by neorm5** [olifolkerd/tabulator#551]
Hi, 
I have a problem with the table, the table load perfect and fit to the width but if you refresh sometimes the table apper just like the attachement.

I don't know if be a problem with persistent or cache, I tried with the option redraw but nothing. 

Thanks for your help

Best regards
![table](https://user-images.githubusercontent.com/9249979/30022029-c46204e6-9169-11e7-9d54-2ff6a2286ccc.PNG)

**Comment by olifolkerd** [comment]
Hey,

That looks like the table is being loaded when the element it contains is not visible. it would suggest you are loading it into an element that isnt visible on page load.

Cheers

Oli

**Comment by neorm5** [comment]
Thanks, great support and great plugin
