### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by michaelongithub** [olifolkerd/tabulator#552]
Hi Oli
Have You decided, when You intend to make that available ? During Beta or only after final ?
Thanks for info
Cheers, Michael

**Comment by olifolkerd** [comment]
Hi Michael,

Now that it is in beta i will add it to the road-map, though realistically it is probably a couple of months off at this point.

If you fancy tackling it yourself i would be happy to accept a pull request with the new theme.

Cheers

Oli

**Comment by michaelongithub** [comment]
ok, b4 tables have not changed much (contrary to other things), so for the moment I could probably live with just changing the base font (The default web fonts (Helvetica Neue, Helvetica, and Arial) have been dropped in Bootstrap 4 and replaced with a “native font stack” ) and to 16px/ 1rem which is large for tables.  So for the moment I can manage. Cheers, Michael

**Comment by olifolkerd** [comment]
Hey @michaelongithub 

You will be happy to hear I have just pushed a Bootstrap 4 theme to the 3.5 branch, which will be officially released later this week.

For a sneek peek of the documentation [Click Here](http://tabulator.info/docs/3.5#theme-bootstrap4)

Cheers

Oli :)

**Comment by michaelongithub** [comment]
Great, thanks
