### ISSUE TITLE
getting / setting header filter

### ISSUE THREAD

**Issue by sawibo** [olifolkerd/tabulator#553]
Hi,

Is there currently a way to set and get the header filters, I can't find it in the documentation anywhere. When going through the code all I can find is that 'getFilter' returns only the filters in 'filterList' and not in 'headerFilters'.

Best,

Sander

**Comment by olifolkerd** [comment]
Hey,

Thanks for getting in touch, you are right, at the moment programmatic access to the header filters is not available.

Though you wont have to wait long. the filter system is getting an overhaul in next months release so this functionality will be added then.

If you have any other filter base functionality you would like to see could you let me know and i can focus on including it in the next update.

Cheers

Oli

**Comment by sawibo** [comment]
Hi Oli,

Great news and great work so far. 

Best,

Sander

**Comment by olifolkerd** [comment]
Thanks for the kind words sawibo,

Im gonna keep the issue open till it has been release just so i can keep track of things.

Thanks for the great suggestion.

Cheers

Oli

**Comment by sawibo** [comment]
Good luck with the updates. Closed the issue out of habit, can imagine you want to keep it open.

Best,

Sander

**Comment by olifolkerd** [comment]
Hey @sawibo 

You will be happy to hear that in today's 3.3 release the ***getFilters*** function has been improved:

```js
var filters = $("#example-table").tabulator("getFilters"); //get programmatic filters
var filters = $("#example-table").tabulator("getFilters", true); //get programmatic and filters
var filters = $("#example-table").tabulator("getHeaderFilters"); //get header filters
```

More information can be found in the [Filtering Documentation](http://tabulator.info/docs/3.3#filtering)

Cheers

Oli :)
