### ISSUE TITLE
Reinitialize tabulator on same DOM element with new data and different column configuration

### ISSUE THREAD

**Issue by zohaibshoaib90** [olifolkerd/tabulator#557]
I am working with tabulator. I want to re-initialized the tabulator on same div element with different column config and data dynamically. Below is the sample div and script that I am using, It refresh the data but doesn't update the columns and if I use setColumn, it will disturb the sorting. I feel that, tabulator not allow to change the column configuration once its render.

```
$("#sample_div").tabulator(tabulator_display_config);    //initialize and apply tabulator
$("#sample_div").tabulator("setData", table_data.Data);    //load data into the table
```

**Comment by olifolkerd** [comment]
Hey,

You cannot pass a new config object into the table once it has been initialized, the setup process is to involved.

if you want to completetly rebuild the table you need to call the ***destroy*** function before you then reinitialize it:
```js
$("#sample_div").tabulator("destroy"); 
$("#sample_div").tabulator(tabulator_display_config);    //initialize and apply tabulator
```

Let me know if that helps

Cheers

Oli

**Comment by zohaibshoaib90** [comment]
Thanks oli,
Thats what I'm looking for.

**Comment by tristanheilman** [comment]
Would the same solution be required if there is only 1 single property that I would like changed out of the entire config? I'd like to be able to set movableRows to false/true depending on if there is 1/or more items returned from the ajax call.... Is it possible to have a dynamic property like so?
