### ISSUE TITLE
dataLoading

### ISSUE THREAD

**Issue by vmontal** [olifolkerd/tabulator#558]
Hi,
how can i show a message while data is loading? (i.e. "Waiting... data loaging").

I realize that "dataLoading" is the right callback, but I have no idea what to do!

**Comment by olifolkerd** [comment]
Hey,

if you are loading data via ajax then tabulator will automatically do this for you, if you are doing it any other method then it should load instantly.

Could you post a copy of your table constructor and give a bit more info about any trouble loading data you are experiencing.

Cheers

Oli

**Comment by vmontal** [comment]
of course! I'm loading data via ajax; 
here the code to load data;

`        function getData(id) {
            var ricerca = {};
            ricerca.ID = id;
            ricerca.ID_Gruppo = dataUser.ID_Gruppo;
            var criterio = JSON.stringify(ricerca);
            $.ajax({
                type: "POST",
                url: "/aspnet_client/appGetData.aspx/GetAnagrafe",
                data: criterio,
                cache: false,
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: getData_success,
                error: errorDialog
            });
        };

       function getData_success(response) {
            var jsonData = JSON.stringify(xml2json(response.d));
            var nrc = jsonData.slice(-3);
            var pqa = (nrc == "]}}" ? "" : "[");
            var pqc = (nrc == "]}}" ? "" : "]");

            if (dataCliente.IDCliente == 0) {
                var jsonOutput = pqa + JSON.stringify(xml2json(response.d).NewDataSet.anagrafe) + pqc;
                $("#tabella").tabulator("setData", jsonOutput);
            };
        };`

and here the table costructor:

`     
function tabellaAnagrafe() {

            $("#tabella").tabulator({
                fitColumns: true,
                colVertAlign: "center",
                selectable: 1,
                colResizable: false,
                sortable: false,
                pagination: "local",
                paginationSize: 10,
                progressiveRenderSize: 12,
                progressiveRenderPeriod: 500,

                columns: [
                    { title: "", formatter: mask.iconProfilo, width: parseInt(larghezza * 0.05), align: "center"}, //, onClick: schedaAnagrafe, tooltip: "Scheda Anagrafe Cliente" },
                    { title: "id", field: "ID_Cliente", visible: false },
                    { title: "Ragione Sociale", field: "ragioneSociale", width: parseInt(larghezza * 0.25), sorter: "string", align: "left", headerFilter: true }, //, onClick: schedaAnagrafe, tooltip: "Scheda Anagrafe" },
                    { title: "Località", field: "citta", width: parseInt(larghezza * 0.15), sorter: "string", align: "left", headerFilter: true }, //, onClick: schedaAnagrafe, tooltip: "Scheda Anagrafe" },
                    { title: "Prov.", field: "provincia", width: parseInt(larghezza * 0.05), align: "center", headerFilter: true }, //, onClick: schedaAnagrafe, tooltip: "Scheda Anagrafe" },
                    { title: "NR Banche", field: "NRB", width: parseInt(larghezza * 0.05), sorter: "number", align: "center" }, //, onClick: schedaBanca, tooltip: "Scheda Banca" },
                    { title: "Rapporti a Breve",
                        columns: [
                            { title: "NR", field: "LB_NRAP", width: parseInt(larghezza * 0.05), sorter: "number", align: "center" }, //, onClick: schedaBanca, tooltip: "Scheda Banca" },
                            { title: "Importo", field: "LB_UTILIZZO", formatter: mask.moneyFormatter, sorter: "number", width: parseInt(larghezza * 0.11), align: "right" }, //, onClick: schedaBanca, tooltip: "Scheda Banca" },
                            ]
                    },
                    { title: "Rapporti a MedioLungo",
                        columns: [
                            { title: "NR", field: "ML_NRAP", width: parseInt(larghezza * 0.06), sorter: "number", align: "center" }, //, onClick: schedaBanca, tooltip: "Scheda Banca" },
                            { title: "Importo", field: "ML_UTILIZZO", formatter: mask.moneyFormatter, sorter: "number", width: parseInt(larghezza * 0.11), align: "right" }, //, onClick: schedaBanca, tooltip: "Scheda Banca" },
                            ]
                    },
                    { title: "Attivo", field: "Attivo", width: parseInt(larghezza * 0.05), align: "center", formatter: "tickCross" },
                ],
                
                dataLoading: function (data) {

                },

                index: "ID_Cliente, ragioneSociale",

                rowClick: function (e, id, data, row) {
                    dataCliente.IDCliente = parseInt(data.ID_Cliente);
                    dataCliente.ragioneSociale = data.ragioneSociale;
                    dataCliente.IDAzione = 0;
                    Auth.paginaStudio = parseInt($("#tabella").tabulator("getPage"));
                    $scope.tabMenu = 99; //<span class='caret'></span>
                    //$("#navCliente").show(250);
                    $("#navCliente").html("<span class='glyphicon glyphicon-hand-right'></span> " + dataCliente.ragioneSociale);
                    $scope.anagrafeAttivo = (data.Attivo == "true" ? true : false);
                    getData(dataCliente.IDCliente);
                },

                rowSelectionChanged: function (data, rows) {
                    if (data.length == 0) {
                        //$("#navCliente").hide(500);
                        $("#navCliente").html("<span class='glyphicon glyphicon-hand-right'></span>");
                        $scope.tabMenu = -1;
                    };
                },
            });
        };`

Ciao
Valerio.NET

**Comment by olifolkerd** [comment]
Tabulator should be displaying the loader, it may be that your data is returning so fast that the loader isnt displayed for more than a couple of milisconds

**Comment by olifolkerd** [comment]
Why you have set the ***index*** option to "ID_Cliente, ragioneSociale", this will have no effect as it is not a valid field name and Tabulator cannot handle compound indecies. what are you hoping this will do?
