### ISSUE TITLE
Assigning 'max-width' to a column on initial load. Resize possible.

### ISSUE THREAD

**Issue by sarfarazm** [olifolkerd/tabulator#560]
Is there a way by which I can assign a max-width to a column when the table is first loaded but still allow the user to resize and increase the width?

This is needed for columns which contain large amount of text and I do not want them to hog all the display. But if the user wants to increase a width by resizing and see more, he should be able to do it.

**Comment by olifolkerd** [comment]
Hey,

There is no max width setting for columns at the moment, have you tried using ***fitColumns*** it should re-scale your columns to fit the width of the table.

Cheers

Oli

**Comment by thewh1teagle** [comment]
Hey, is there an update regarding that issue? does it possible today having a maxWidth with option to resize columns?
Thanks
