### ISSUE TITLE
default secondary sort?

### ISSUE THREAD

**Issue by nosenfield** [olifolkerd/tabulator#566]
aside from a custom sort function, is there was any way to define a default secondary sort for either all items or specific columns (eg. sorting a list of songs by album would also sort them by track order as a secondary)

also, is there any way to reference the pre-existing sort functions so i could do something like:
```
function customSort(a, b, aData, bData){
    var result = Tabulator.sorters.string(a, b);
    return result == 0 ? secondarySort(aData.secondary, bData.secondary) : result;
}

function secondarySort(a, b)
{
    return a - b
}

```

really loving this plugin, btw. very easy to use and customize

**Comment by olifolkerd** [comment]
If you want to sort two columns at the same time then im afraid the only way is to use ***setSort*** with multiple sorters:
```js
$("#example-table").tabulator("setSort", [
    {column:"age", dir:"asc"}, //sort by this first
    {column:"height", dir:"desc"}, //then sort by this second
]);
```

Do you want to achieve this from a header sort or a programmatic sort?

Cheers

Oli

**Comment by nosenfield** [comment]
from a header sort (ie. user interaction). so for now i've just implemented it via a custom sort:

```
function primarySort(a, b, aData, bData, column, dir, sorterParams) {
                    var result = String(a).toLowerCase().localeCompare(String(b).toLowerCase());
                    return (result == 0 ? secondarySort(a, b, aData, bData, column, dir, sorterParams) : result);
                }

function secondarySort(a, b, aData, bData, column, dir, sorterParams) {
                    return String(aData.data.secondary).toLowerCase().localeCompare(String(bData.data.secondary).toLowerCase());
                }
```
