### ISSUE TITLE
Can the data still be paged after the groupBy?

### ISSUE THREAD

**Issue by diffcultpro** [olifolkerd/tabulator#567]
After groupBy , if the datas are too much to show on the page ,can it be paged ? or make a scroll bar ?

![qq 20170912143920](https://user-images.githubusercontent.com/31839891/30311527-540a37a8-97c8-11e7-8413-b895873db6a7.jpg)

**Comment by olifolkerd** [comment]
Hey,

At the moment, Tabulator cannot paginate and group at the same time, although this will be comming in the next few releases.

If you set a ***height***  in the table constructor then it will show a scroll bar when the data overflows the table

Cheers

Oli

**Comment by diffcultpro** [comment]
OK ,thank you , may the Tabulator will be more and more perfect !
