### ISSUE TITLE
Filter area is not getting applied in the first place. Do we have to create text field to take filter queries?

### ISSUE THREAD

**Issue by vickyvishal** [olifolkerd/tabulator#569]
Hi Oli,
Tabulator is awesome. I need some help. I am new to coding, ergo this might be a silly question.
Here is my code:

var tableData = [
        {id:1, name:"dummydata1?sourceid=1343&hui", status: "200", rtype:"document", type: "dummylink.doc", size: "537B", time: "34ms", waterfall: "40"},
        {id:2, name:"dummydata1?sourceid=1343&hui", status: "OK", rtype:"document", type: "dummylink.doc", size: "78KB", time:"34ms", time1: ""},
        {id:3, name:"dummydata1?sourceid=1343&hui", status: "OK", rtype:"xhr", type: "dummylink.xhr", size: "78KB", time:"34ms", time2: "100", time3: "35"},
        {id:4, name:"dummydata1?sourceid=1343&hui", status: "OK", rtype:"xhr", type: "dummylink.xhr", size: "2MB", time:"34ms", time3: "35"},
        {id:5, name:"dummydata1?sourceid=1343&hui", status: "200", rtype:"css", type: "dummylink.css", size: "1PB", time:"34ms", time4: "50"},
        {id:6, name:"dummydata1?sourceid=1343&hui", status: "OK", rtype:"JS", type: "dummylink.js", size: "1TB", time:"34ms", time5: "100" },
        {id:7, name:"dummydata1?sourceid=1343&hui", status: "OK", rtype:"xml", type:"dummylink.xml", size: "100B", time:"34ms", time6: "80"},
    ];

    $("#tabulator-example").tabulator("setData", tableData);

    function customFilter(data){
        return data.id < 7;
    }

    function updateFilter(){

        var filter = $("#filter-field").val() == "function" ? customFilter : $("#filter-field").val();

        if($("#filter-field").val() == "function" ){
            $("#filter-type").prop("disabled", true);
            $("#filter-value").prop("disabled", true);
        } else {
            $("#filter-type").prop("disabled", false);
            $("#filter-value").prop("disabled", false);
        }
    $("#tabulator-example").tabulator("setFilter", filter, $("#filter-type").val(), $("#filter-value").val());
    }

//Update filters on value change
    $("#filter-field, #filter-type").change(updateFilter);
    $("#filter-value").keyup(updateFilter);

    //Clear filters on "Clear Filters" button click
    $("#filter-clear").click(function(){
        $("#filter-field").val("");
        $("#filter-type").val("=");
        $("#filter-value").val("");

        $("#tabulator-example").tabulator("clearFilter");
    });

**Comment by olifolkerd** [comment]
Hey,

Thanks for getting in touch, what do you mean by the "Filter Area" is not being applied?

Cheers

Oli

**Comment by vickyvishal** [comment]
I want to custom filter my table exactly the way it is shown in the example. But it seems it doesn't work as there is not filter field in the html.  

`$("#tabulator-example").tabulator("setData", tableData);

function customFilter(data){
    return data.id < 7;
}

function updateFilter(){

    var filter = $("#filter-field").val() == "function" ? customFilter : $("#filter-field").val();

    if($("#filter-field").val() == "function" ){
        $("#filter-type").prop("disabled", true);
        $("#filter-value").prop("disabled", true);
    } else {
        $("#filter-type").prop("disabled", false);
        $("#filter-value").prop("disabled", false);
    }
$("#tabulator-example").tabulator("setFilter", filter, $("#filter-type").val(), $("#filter-value").val());
}
$("#filter-field, #filter-type").change(updateFilter);
$("#filter-value").keyup(updateFilter);

$("#filter-clear").click(function(){
    $("#filter-field").val("");
    $("#filter-type").val("=");
    $("#filter-value").val("");

    $("#tabulator-example").tabulator("clearFilter");
});
`

My table is defined in $("#tabulator-example"). So I was wondering, do I have to create a input field in html with  $("#filter-field"),  $("#filter-type") and  $("#filter-value") name ?

**Comment by olifolkerd** [comment]
Hey,

The ***setFilter*** method is used to programatically trigger a sort in the table, it does not create any input elements, so it would be up to you to add input elements anywhere on your page and an an event binding on the keyup or change events to then trigger the filter.

If you want the filter to be a column header filter, where an element appears in the header for the column then you need to use the ***headerFilter*** property in the column definition array, documentation on how to use the header filter can be [found here](http://olifolkerd.github.io/tabulator/docs/3.2/#header-filters).

Let me know if that helps.

Cheers

Oli

**Comment by vickyvishal** [comment]
Thanks a lot.
