### ISSUE TITLE
Problem with filtering values UPPERCASE is not working .

### ISSUE THREAD

**Issue by fabricecouvert** [olifolkerd/tabulator#57]
Hi olifolerd,

I have a problem when filtering values ...  

![1](https://cloud.githubusercontent.com/assets/20986741/18476202/6ac0ee4c-79c9-11e6-861e-6a54e4ba7664.PNG)
![2](https://cloud.githubusercontent.com/assets/20986741/18476208/7020d3c0-79c9-11e6-9c2c-4f3d1d331207.PNG)
![3](https://cloud.githubusercontent.com/assets/20986741/18476211/71b68842-79c9-11e6-858b-4e1465ac6afe.PNG)

it looks like filtering the values is only working with lower case (my data's title is in Uppercase ...)
Is that a bug or is there anything i miss ?

Regards,
Fabrice

**Comment by olifolkerd** [comment]
Hi Fabrice,

That was indeed a bug, well spotted.

I have uploaded a fix now.

Cheers

Oli
