### ISSUE TITLE
accessor functions for sorting?

### ISSUE THREAD

**Issue by nosenfield** [olifolkerd/tabulator#570]
I'm having trouble understanding how to format the displayed data for proper sorting.

I have certain data points that exist as strings in my table, but need to be sorted numerically (displayed value = "N/A", sort value = 0). Doing a swap in the sorting function isn't great for performance and the accessor function doesn't seem to get run before sorting.

How should I set this up?

**Comment by olifolkerd** [comment]
Hey,

Accessors are only applied to data as it is retrieved from the table using the ***getData*** functions.

your options are to mutate the data as it comes into the table with a mutator or use a custom sorting function as you mentioned that does the conversion as the sort runs. Unless you are sorting 100,000's of rows you shouldn't notice much of a performance hit from the second approach.

**Comment by nosenfield** [comment]
yeah, i thought that might be the case.

unfortunately, the mutator function affects the data for all time. it doesn't just change the values written to the table, it changes the actual data that then gets used in all subsequent sorts, so i lose whatever the initial value was.

i'll parse it in the custom sort. thanks!
