### ISSUE TITLE
Can i make a click function on the GroupHeader ? because except the table ,i need another function that  can control another div to show，hide or refresh.

### ISSUE THREAD

**Issue by diffcultpro** [olifolkerd/tabulator#571]
Can i make a click function on the GroupHeader ? because except the table ,i need another function that  can control another div to show，hide or refresh.
just like when i am click the male or female , 
![qq 20170913134427](https://user-images.githubusercontent.com/31839891/30361726-286fc7c0-988b-11e7-9a8c-c4b92f38cb71.jpg)

**Comment by olifolkerd** [comment]
there is no click binding on the group header yet, but this will be coming in the next release.

**Comment by olifolkerd** [comment]
Hey @diffcultpro 

You will be happy to hear that in today'a 3.3 release there is a full set of click event callbacks for group headers; ***groupClick***, ***groupDblClick***, ***groupContext***, ***groupTap***, ***groupDblTap*** and ***groupTapHold***:

```js
$("#example-table").tabulator({
        groupClick:function(e, group){
        //e - the click event object
        //group - group component
    },
});
```

You can also set the group header to toggle the group visibility on click with the new ***groupToggleElement*** option:
```js
$("#example-table").tabulator({
   groupToggleElement:"header", //toggle group on click anywhere in the group header
});
```

More information can be found in the [Grouping Documentation](http://tabulator.info/docs/3.3#grouping)

Cheers,

Oli :)
