### ISSUE TITLE
rowClick not always firing

### ISSUE THREAD

**Issue by Dundee2308** [olifolkerd/tabulator#572]
When using Windows10 platform the rowClick is not always firing.

With Windows 7, it works like a charm.

**Comment by olifolkerd** [comment]
which browsers are you using on which operating system? and which version of Tabulator are you using?

**Comment by Dundee2308** [comment]
Tested with Firefox and Chome on windows10
Both will not always fire.
Version of tabulator (tabulator.min.js) version 3.1.5

**Comment by Dundee2308** [comment]
Hi Oli,
I tested with the newest version 3.2 and with version 3.1.5
So it seems like it has nothing to do with windows10.

But what i found out is when you select a row (rowClick)
it does NOT fire if you hold down the mouse to long.
Only when you click and quicky release the mouse button on a row, then it will always fire.

Maybe .mousedown() and/or  .mouseup() event in JQ is the culprit ?
Maybe .mouseclick() or .click() will solve the problem ?

Hope this helps.
And thanks for this wonderful plugin.
Dundee.
