### ISSUE TITLE
dose  one  of the columns can be hide ?

### ISSUE THREAD

**Issue by diffcultpro** [olifolkerd/tabulator#574]
dose  one  of the columns can be hide ?

**Comment by olifolkerd** [comment]
You can hide columns in a couple of ways:

When creating a column in the column definition array set the ***visible*** property to ***false***:
```js
$("#example-table").tabulator({
    columns:[
        {title:"Hidden Column", field:"name", visible:false},
    ],
});
```

Or you can hide it progamatically at any point using the ***hideColumn*** function:
```js
$("#example-table").tabulator("hideColumn","name") //hide the "name" column
```

Let me know if that helps,

Cheers

Oli

**Comment by harishbudhwani** [comment]
hi i am not able to find tabulator method. It gives an error , says tabulator method is undefined.

**Comment by olifolkerd** [comment]
Hey @harishbudhwani 

If you are having problems please create a new issue using the appropriate template and fill in the required details.

Cheers

Oli :)
