### ISSUE TITLE
update ajaxUrl after tabulator is initialized

### ISSUE THREAD

**Issue by cschnelting** [olifolkerd/tabulator#575]
Hi Oli,

is it possible to update the ajaxUrl after the tabulator is already initialized? 
I need to set the ajaxUrl at runtime and later read the ajaxUrl from options. So i tried this:
- use setData to fill the frid:
  - grid.tabulator("setData", url);
- read ajayUrl and get false:
  - var ajaxURL = grid.tabulator("option").ajaxURL

**Comment by olifolkerd** [comment]
Thanks for getting in touch,

You are correct in using ***setData*** to change the URL.

At the moment there is no way to read the url back from the table, but if you are going to set it programatically any way then you could assign it to a variable before you set it in your table and then read it back from that variable when needed.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @cschnelting 

You will be happy to hear that in today's 3.3 release there is a new ***gtAjaxUrl*** function for retrieving the current URL:
```js
var url = $("#example-table").tabulator("gtAjaxUrl");
```
Thanks for the suggestion!

Cheers

Oli :)
