### ISSUE TITLE
"column is not defined" if tooltipHeader is a function

### ISSUE THREAD

**Issue by bparquet** [olifolkerd/tabulator#576]
If tooltipHeader in the column definition is a function, then a javascript error occurs.

Example: https://jsfiddle.net/bparquet/a970azmv/2/

```
diff --git a/src/js/column.js b/src/js/column.js
index 795accb..4654ed1 100644
--- a/src/js/column.js
+++ b/src/js/column.js
@@ -185,7 +185,7 @@ Column.prototype._buildHeader = function(){
 
 		}else{
 			if(typeof(tooltip) == "function"){
-				tooltip = tooltip(column.getComponent());
+				tooltip = tooltip(self.getComponent());
 			}
 
 			self.element.attr("title", tooltip);
```

**Comment by olifolkerd** [comment]
Great Spot!

That was a bug, i have just pushed a fix to the master branch, it will be included in the next patch release.

Feel free to make a pull request with fixes like that in future :)

Thanks

Oli
