### ISSUE TITLE
Any option to customise "progress formatter" to start and end at a particular point in the column ?

### ISSUE THREAD

**Issue by vickyvishal** [olifolkerd/tabulator#577]
Hi Oli,
Sorry to bother you again. Is there any way to create a progress field like the attached screenshot? 
![screen shot 2017-09-01 at 12 23 21 pm]
(https://user-images.githubusercontent.com/22187019/30469526-4a1cb9c6-9a0e-11e7-95da-e8b398c0ec8f.png)

I have written a script to find the progress field and change the css to have this effect, but its not changing the css.

Thanks in advance.

**Comment by olifolkerd** [comment]
Hey,

You would need to create a custom formatter to achieve that. you could use the ***progress*** formatter as a starting point.

Checkout the [Custom Formatter Documentation](http://olifolkerd.github.io/tabulator/docs/#formatting) for more information.

Cheers

Oli

**Comment by vickyvishal** [comment]
Thanks Olifolkerd. That helped :+1:
