### ISSUE TITLE
How to restore cell value without triggering cellEdited?

### ISSUE THREAD

**Issue by c-zakkaroff** [olifolkerd/tabulator#578]
Hi Oli,

I'm wondering, say if I want to restore the old cell value like this `cell.setValue(cell.getOldValue())` in my `cellEdited` callback when something didn't go right on the server side, how do I do this without triggering this callback again, because now when I use `setValue` it triggers `cellEdited`, thus creating a redundant update?

Many thanks!

**Comment by olifolkerd** [comment]
Hey,

There is no direct way to do this. a workaround would be to create a Boolean variable outside of tabulator that you set to ***true*** when you make a restore action, in the cell edited check if this value is true, if so set it to false and carry out no action otherwise trigger the update.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @c-zakkaroff,

You will be happy to hear that in today's 3.3 release there is a new ***restoreOldValue*** function on the cell component to restore it back to its old value without triggering the usual callbacks:

```js
cell.restoreOldValue();
```

You may also be interested to hear that Tabulator now has [Input Validation](http://tabulator.info/docs/3.3#validation) to help you prevent users from entering invalid data in the first place.

Thanks for the great suggestion!

Cheers

Oli :)

**Comment by c-zakkaroff** [comment]
Thank you Oli. This is really great how you keep improving Tabulator. It is really helping my web project, although at this stage it is in the Alpha stage.

**Comment by olifolkerd** [comment]
No Problem, im happy to help.

If there are any other features you would like to see raise another issue and i can add them to the road map.

Cheers,

Oli :)

**Comment by c-zakkaroff** [comment]
Thank you. I'll be on the look out for features as I explore Tabulator's API. There's so many thins I'm still to figure out.
