### ISSUE TITLE
How to give values to formatterParams and topCalcParams. disable editing for specific cell.

### ISSUE THREAD

**Issue by Praveene7** [olifolkerd/tabulator#579]

**Comment by olifolkerd** [comment]
Hey,

Your question is a bit vague.

the ***formatterParams*** and ***topCalcParams*** objects are passed into functions from their column definitions. for example to set the formatterParams:

```js
$("#example-table").tabulator({
    columns:[
        {title:"Rating", field:"rating", formatter:"star", formatterParams:{stars:6}}
    ],
});
```

For setting cell edition, you should pass a callback to a column definitions ***editable*** property that returns true if a cell is editable and false if it is not:
```js
var editCheck = function(cell){
    //cell - the cell component for the editable cell

    //get row data
    var data = cell.getRow().getData();

    return data.age > 18; // only allow the name cell to be edited if the age is over 18
}

//in your column definition for the column
{title:"Name", field:"name", editor:"string", editable:editCheck}}
```

Let me know if that helps,

Cheers

Oli
