### ISSUE TITLE
How do I filter records by today's date and return a count?

### ISSUE THREAD

**Issue by verlager** [olifolkerd/tabulator#581]
I would like to maintain a membership list with this excellent jquery table plugin. I have a prototype at http://communitychessclub.com/cccr-pairing/members.html and would like to sort in descending order by Expiration date ("Expires") and have the records with fixed numbers in the left column. Then I could just scroll to the nearest current expiration date and read the count at the left column. Any suggestions, please?

**Comment by vipera7** [comment]
You mean something like this ?
``` javascript
$("#example-table").tabulator({
    initialSort:[
        {column:"age", dir:"asc"}, //sort by this first
        {column:"height", dir:"desc"}, //then sort by this second
    ]
});
```

**Comment by verlager** [comment]
No. I just want numbers in a left column like 1, 2, 3, 4 so I can count the applicable records.

**Comment by olifolkerd** [comment]
Hey,

if you just want a number to show the position in the list you can use the ***rownum*** formatter.

If you are looking to assign each row a unique id no, then i would suggest you add this to your row data and add a column to show it. alternatively you could add a mutator to create this data for you as the table loads.

Cheers

Oli

**Comment by verlager** [comment]
This doesn't work: {title:"Row", formatter:"rownum"}, // what would work, if you please?

$("#example-table").tabulator({
    history:true,
	persistentLayout: true,
    persistentLayoutID:"examplePerststance",
	redraw: false,
	height: "100%",
	pagination: "local",
	paginationSize:9,
    fitColumns:true, //fit columns to width of table (optional)
    columns:[ //Define Table Columns
        {title:"Row", formatter:"rownum"},
        {title:"Last, First", field:"Name", headerFilter:"input", editor:"input"},
        {title:"Expires", field:"Expires", align:"left", editor:"input"},
            ],
});

**Comment by verlager** [comment]
I added a column but it doesn't help:

 var members = [
	{
		"row":"", 
 "Name": "Ahmed, Jamshed",
		"Expires": "2017.10.05"
	},
	{
		"row":"", 
 "Name": "Attaya, James",
		"Expires": "2018.01.12"
	},
	{
		"row":"", 
 "Name": "Badamo, Anthony",
		"Expires": "2018.09.12"
	},

**Comment by olifolkerd** [comment]
when you say it dosnt work, what do you mean?

is the column blank? is the contents not what you expect?

**Comment by verlager** [comment]
I have http://communitychessclub.com/cccr-pairing/members.html and http://communitychessclub.com/cccr-pairing/assets/cccr_mems.json which show that although the "row" field is present in code, in reality it doesn't display. Thank you for your help BTW.

**Comment by verlager** [comment]
I got it! The persistentLayout: true, has to be set to false temporarily.
