### ISSUE TITLE
More on AjaxFiltering (continued from #411)

### ISSUE THREAD

**Issue by leonardorame** [olifolkerd/tabulator#582]
Hi Oli, thanks for adding `cell.getFilter()`to the `headerFilter` function.

Apart from that, I also needed a way to *avoid* the ajax call, so I've included a new event  called `beforeAjaxRequest` into the `Ajax.prototype.sendRequest` method.

Here are the additions:

```javascript
    Ajax.prototype.sendRequest = function (callback) {

      var self = this;

     // ---- beforeAjaxRequest
      if (self.table.options.beforeAjaxRequest) {
        if(!self.table.options.beforeAjaxRequest())
          // exit sendRequest if beforeAjaxRequest returns false.
          return;
      };
      // ---- end beforeAjaxRequest
      if (self.url) {
     ....
````

The new event is pretty easy to use, just add it to the *options* of your tabulator, then return `false`if you want to avoid the ajax call and true if you want to let it run.

Example:

```javascript
    table.tabulator({
      height: '320px',
      selectable: 1,
      headerFilterPlaceholder: "",
      pagination: "remote",
      paginationSize: 10,
      ajaxURL: "/cgi-bin/mycgi/route",
      ajaxFiltering: true,
      beforeAjaxRequest: function() {
        return false; // false to avoid ajax call, true to let it run 
      },
      columns: [
        { title: "#", field: "position", headerFilter: "ajaxEditor", sortable: true, sorter: "number",
        { title: "Ingreso", field: "ingreso", headerFilter: "ajaxEditor", sortable: true, sorter: "numb
        { title: "Creado", field: "creado", headerFilter: "ajaxEditor", sortable: true, sorter: "string
        { title: "Fecha", field: "fecha", headerFilter: "ajaxEditor", sortable: true, sorter: "date", w
      ],
    });
```

Why I needed this?, because I was implementing a *headerFilter* for Ajax an didn't want the request called immediately every time I was typing something on the header editor, so I used the same typingTimer you used for *local* filters, but, as I did'n have a way to avoid the call to `sendRequest` I implemented this.

Hope you find it useful.

**Comment by olifolkerd** [comment]
Hey @leonardorame 

You will be happy to hear that in today's 3.3 release I have added your suggested functionality, but with a couple of tweaks.

Tabulator already has a ***ajaxRequesting*** callback that is called just before the request is made, you can now return ***false*** from this callback to prevent the request:

```js
$("#example-table").tabulator({
    ajaxRequesting:function(url, params){
        return false; //abort ajax request
    },
});
```
You may also be interested to hear that Tabulator now has [Input Validation](http://tabulator.info/docs/3.3#validation) to help you prevent users from entering invalid data in the first place.

Thanks for the suggestion! 

Cheers,

Oli :)

**Comment by leonardorame** [comment]
Great!, I'll take a look at it.
