### ISSUE TITLE
Keeping selected rows on filter

### ISSUE THREAD

**Issue by br3nd4nn34l** [olifolkerd/tabulator#583]
Hello,
Is there a way to make selected rows display even when the data is filtered? 

For example, if I have the table:
**Name**
Alice
Bob
Charlie

If I select the "Alice" row, then filter name on "Bob", I want to see
**Name**
Alice
Bob

Currently, I'm trying to add selected row components to the second argument (row components array) of the _dataFiltered_ callback, but the selected rows aren't appearing if they don't match the given filters.  From what I can tell the array IS being modified, but the rendering takes place BEFORE _dataFiltered_ is called, so the changes aren't being rendered.

I've also tried modifying the functions in the _dataFiltering_ callback, but I don't think that it exposes the header filters of the table. Even if it did, according to the documentation the filters would be objects, not functions, so I can't make a wrapper function that OR's those together with a selected checker.

More generally, is there any way to display rows when they don't match the currently filters, or to make "unionized" filters?

**Comment by olifolkerd** [comment]
Hey,

The only way to achieve this would be to use a custom filter function that checked to see if a row was in the selected columns array (you can retrieve this with the ***getSelectedRows*** function) and to then check if it matched the filter value.

Checkout the [Filter Documentation](http://tabulator.info/docs/3.2#filtering) for examples on how to build a custom filter.

Let me know if that helps

Cheers

Oli
