### ISSUE TITLE
rowDblClick:function,how to get value from one of the columns in this row ? 

### ISSUE THREAD

**Issue by diffcultpro** [olifolkerd/tabulator#585]
hi ,oil !
 i am sorry to trouble you again and again .
when i  use this function ,how to get value from one of the columns in this row ? 
$("#example-table").tabulator({
        rowDblClick:function(e, row){
        //e - the tap event object
        //row - row component
    },
});

**Comment by diffcultpro** [comment]
ok . i have resovled it

**Comment by joalcava** [comment]
Hi, How have you solved it?
