### ISSUE TITLE
New roadmap content questions

### ISSUE THREAD

**Issue by michaelongithub** [olifolkerd/tabulator#586]
Hi Oli
compliments on your new organisation of site and content. Had a look at roadmap.

Did not find serverside infinite scroll or similar (for very large tables). Not any more in Your plans?

Data Reactivity (3.5) What would that be ? Some kind of sockets feature?

Thanks again for all Your work, very good features I need on roadmap!
Cheers, Michael

**Comment by olifolkerd** [comment]
Hey Michael,

Thanks for your kind words, now that Tabulator has its own server the will be a load of new and exciting website features coming in the next few months.

I missed the infinite scroll on the roadmap, i have now added it into release 3.4

When i say reactive data, think along the lines of reactive frameworks like vue.js. When you enable reactive data on Tabulator, when you set the table data to an array, any changes to data in that array will instantly update in the table without the need to call functions.

Thanks for your feedback on the roadmap, i have updated a number of the items to include more descriptive title and comments.

Let me know if there are any other features you would like to see.

Cheers

Oli

**Comment by leonardorame** [comment]
Sorry, I couldn't find the roadmap, where is it?.

**Comment by olifolkerd** [comment]
Hey @leonardorame 

Have a look at the [Community Page](http://tabulator.info/community) for more details.

The roadmap itself can be found on trello at https://trello.com/b/rPZ0Yavc/tabulator-roadmap

Cheers

Oli
