### ISSUE TITLE
Prevent column from being dragged when moving rows

### ISSUE THREAD

**Issue by tomheaps** [olifolkerd/tabulator#588]
I have a table where I have set `movableRows: true` so that I can rearrange and drag the rows up and down.

However, I would like the first column (my index column) and the values contained within the cells in this column NOT to move when dragging the other cells in that row around i.e. the first column remains fixed in place but all other columns are dragged up and down by the row handle.

I am pretty sure that tabulator does not offer this functionality built in - `frozen: true` only fixes the column when scrolling horizontally and not when dragging rows.

Would be very grateful if anyone could suggest a jQuery override solution to achieve what I am after?

**Comment by olifolkerd** [comment]
Hey,

Im afraid this would not be possible as Tabulator contains all cells of a row inside a row div in the dom, so there would be no way of separating out the column like you ask with out a significant rewrite of the rendering system.

Sorry it isn't better news.

Oli
