### ISSUE TITLE
Frozen Column render error with tabulator_bootstrap.css

### ISSUE THREAD

**Issue by michaelongithub** [olifolkerd/tabulator#589]
Hi Oli
if one has
```
    <LINK href="tabulator/tabulator.min.css" rel="stylesheet">
    <LINK href="tabulator/tabulator_bootstrap.min.css" rel="stylesheet">
```
and frozen cols on left f.i.
moving scrollbar overlays frozen cols with scrolled cols.
Cause: 
.tabulator .tabulator-row {
    position: relative;
    box-sizing: border-box;
    min-height: 30px;
    background-color: transparent;
    border-bottom: 1px solid #ddd;
}
Temp fix for me: background-color: #fff;

But this is in general not good.

Problem known?
Ideas how to fix ?

Cheers Michael
[TabulatorTests.zip](https://github.com/olifolkerd/tabulator/files/1324577/TabulatorTests.zip)

**Comment by olifolkerd** [comment]
Hey Michael,

you should only include one CSS file. not both.

Let me know if that helps

Cheers

Oli

**Comment by michaelongithub** [comment]
Hey Oli
as far as I can test (in Example I sent), problem remains.

Cheers, Michael

**Comment by michaelongithub** [comment]
BTW, how can I set standard Bootstrap classes for stripes, condensed, border of table etc with Your Bootstrap theme.
In Your example on Your site:
Also no table border and Headers not visible,

**Comment by olifolkerd** [comment]
You should just be able to apply the bootstrap classes to your tabulator element and they should work. let me know if they dont

**Comment by michaelongithub** [comment]
Yes, works, thanks, very good solution. So the original problem remains.
Cheers, Michael

**Comment by michaelongithub** [comment]
Closed by accident. 
I meant the frozen column problem with the bootstrap theme

**Comment by michaelongithub** [comment]
and again, sorry

**Comment by olifolkerd** [comment]
On further investigation this is because by default bootstrap sets the background colour of its tables to transparent, this is then pulled through to the rows, which then don't render correctly when frozen.

i will look at fixing this in this weekends release, but it may well end up with the default background colour being set to white

**Comment by michaelongithub** [comment]
Thanks a lot for having a look at it.

**Comment by olifolkerd** [comment]
Hey @michaelongithub 

You will be happy to hear that in today's 3.3 release this bug has now been fixed.

Cheers

Oli :)
