### ISSUE TITLE
[BUG] formatter:"money" 

### ISSUE THREAD

**Issue by soo1025** [olifolkerd/tabulator#59]
When I used "formatter:'money'" in columns, there was bug in a screen.
`{title:"price", field:"price", sorter:"number", formatter:"money", align:"right",width:100,editor:editOption},`
 When I had "addRow", the result was "NaN" in the result screen.

It need change the "money" formatter code.
----------  now -----------------------------

> money:function(value, data, cell, row, options, formatterParams){
>		var number = parseFloat(value).toFixed(2);
>	        var number = number.split(".");
>                var integer = number[0];
>	        var decimal = number.length > 1 ? "." + number[1] : "";
>		var rgx = /(\d+)(\d{3})/;
>		while (rgx.test(integer)){
>			integer = integer.replace(rgx, "$1" + "," + "$2");
>		}
>		return integer + decimal;
>}
 
---------- to be -------------------------------
> money:function(value, data, cell, row, options, formatterParams){
>           **if(isNaN(parseFloat(value)))**
>	     **{**
>		     **return value;**
>	     **}else{**
>		    var number = parseFloat(value).toFixed(2);
>	            var number = number.split(".");
>                    var integer = number[0];
>	           var decimal = number.length > 1 ? "." + number[1] : "";
>		   var rgx = /(\d+)(\d{3})/;
>		   while (rgx.test(integer)){
>	       		integer = integer.replace(rgx, "$1" + "," + "$2");
>	           }
>	        	return integer+ decimal;
>             **}**
>},`

**Comment by olifolkerd** [comment]
Thanks for the heads up,

I have just committed a fix for this issue.

Cheers

Oli
