### ISSUE TITLE
Selectrow is not working in version 2.12

### ISSUE THREAD

**Issue by Deepti-Rajput** [olifolkerd/tabulator#590]
Hi,

I am using tabulator version 2.12 with progressiveRender and remote pagination,

```js
$("#applicants-table").tabulator({
        index: "NomineeId",
        sortable: false,
        movableCols: true,
        height: "600",
        columns: columnListForGrid,
        ajaxURL: window.GetDataUrl, //set url for ajax request
        ajaxConfig: "POST",
        fitColumns: true,
        ajaxParams: {
       
        },
        pagination: "remote",
        progressiveRender: "remote",
        paginationSize: 20,
        progressiveRenderSize: 20, //sets the number of rows to render per block (default = 20)
        progressiveRenderMargin: 50,
        progressiveRenderFill: true,
        paginationDataSent: {
            "page": "PageNo", //change page request parameter to "pageNo"
            "size": "PageSize",
            "sort": "Sort",
            "sort_dir": "SortDir"
        },
        paginationDataReceived: {
            "current_page": "current_page",
            "last_page": "max_pages",
            "data": "data"
        },
        ajaxResponse: function (url, params, response) {
                return response;
       
        },
        //loader element
        rowSelectionChanged: function (data, rows) {
            $(".nominee-column").removeAttr("checked");
            $.each(rows, function (index, row) {
                $(row).find(".tabulator-frozen").find(".tabulator-cell").find(".nominee-column").attr("checked", "checked");
                $(row).find(".tabulator-frozen").find(".tabulator-cell").find(".nominee-column").prop('checked', true);
            });
        },
        rowFormatter: function (row, data) {
       //some row formatter i have written here
        },
    });
```
I am getting error in selecting row

tabulator-new-version.js?v=1.0.0.0:3977 Uncaught TypeError: Cannot read property 'NomineeId' of undefined

Please help me out.

**Comment by olifolkerd** [comment]
Hey,

Im not sure where you are getting the file ***tabulator-new-version.js*** from, no version of tabulator has ever been released with that file name, are you using an official release?

Tabulator is now on version 3.2 (soon to be 3.3), I would strongly recommend moving to the new version as they contain many improvements and bugfixes on the old versions.

Many Thanks

Oli

**Comment by Deepti-Rajput** [comment]
Hi,

I renamed the file to tabulator.js to  tabulator-new-version.js . I am using version 2.2 and @ this moment we can't switch to new version.

Can you help me out progressive render with remote pagination?

**Comment by olifolkerd** [comment]
looking at the error message it suggest that you are not passing data correctly into the table,

what are you returning from your server when the ajax request is made? It should be in the format:
```js
{
    "last_page":15, //the total number of available pages
    "data":[ // an array of row data objects
        {id:1, name:"bob", age:"23"}, //example row data object
    ]
}
```

Cheers

Oli

**Comment by Deepti-Rajput** [comment]
Hi,

Like this I have set it....
 paginationDataSent: {
        "page": "PageNo", //change page request parameter to "pageNo"
        "size": "PageSize",
        "sort": "Sort",
        "sort_dir": "SortDir"
    },
    paginationDataReceived: {
        "current_page": "current_page",
        "last_page": "max_pages",  
        "data": "data"
    },
    ajaxResponse: function (url, params, response) {
            return response;
   
    },

**Comment by olifolkerd** [comment]
sorry,

I think there was a mis-understanding there, what is the format of the data you are returning from the server? Could you post and example of a response your server sends back from the ajax request.

Cheers

Oli

**Comment by olifolkerd** [comment]
also you mention you are getting an error on row select but you don't appear to have the ```selectable:true``` in your table definition anywhere.

**Comment by Deepti-Rajput** [comment]
$("#applicants-table").tabulator({
        index: "NomineeId",
        sortable: false,
        movableCols: true,
        height: "600",
        columns: columnListForGrid,
        ajaxURL: window.GetDataUrl, //set url for ajax request
        ajaxConfig: "POST",
	selectable: true, 
        fitColumns: true,
        ajaxParams: {
            Columns: columnData,
            Filters: filterData,
            AwardId: window.AwardId,
            isSavePreferrence: true,
            isFilterData: false,
            activityName: window.ActivityName,
            phaseSettingId: window.PhaseSettingId,
            OrderBy: OrderBy,
            onlyFinalNominators: window.OnlyFinalNominators,
            finalPhaseSubCode: window.LOIPhaseSubcode
        },
        pagination: "remote",
        progressiveRender: "remote",
        paginationSize: 20,
        progressiveRenderSize: 20, //sets the number of rows to render per block (default = 20)
        progressiveRenderMargin: 50,
        progressiveRenderFill: true,
        paginationDataSent: {
            "page": "PageNo", //change page request parameter to "pageNo"
            "size": "PageSize",
            "sort": "Sort",
            "sort_dir": "SortDir"
        },
        paginationDataReceived: {
            "current_page": "current_page",
            "last_page": "max_pages",
            "data": "data"
        },
        ajaxResponse: function (url, params, response) {
            $("#no-of-applicants").text(response.total_results);
            if (response.current_page === 1 && response.total_results === 0 && !isApplicantEmptyFirstLoad) {
                $("#applicants-table").attr("style", "height: auto;max-height: 100px;overflow:auto;border:none");
                if (window.HasStudySection != null && window.HasStudySection.toUpperCase() === "TRUE") {
                    $("#applicants-table").html("<div class='well-div'>There are no applications which are recommended / triaged in the study section. Please mark the applications as recommended / triaged to proceed for awardee list.</div>");
                } else {
                    $("#applicants-table").html("<div class='well-div'>There are no applications received till now</div>");
                }
                $(".no-of-applicants").hide();
                $(".columns-parent").hide();
                $(".filter-parent").hide();
                $("#notify-all-action").hide();

                $("#bulk-action").hide();
                isApplicantEmptyFirstLoad = true;
                return response;
            } else {
                $("#applicants-table").attr("style", "height: auto;max-height: 600px;overflow:auto");
                var height = $('#applicants-table').prop('scrollHeight');
                if (response.total_results === 0) {
                    height = 100;
                }
                if (height > 600) {
                    height = 600;
                }
                height = height + 5;
                $("#applicants-table").attr("style", "height: " + height + "px;overflow-y:auto;width:100%");
                $("#applicants-table").tabulator("redraw");
                return response; //return the response data to tabulator
            }
        },
        //loader element
        rowSelectionChanged: function (data, rows) {
            $(".nominee-column").removeAttr("checked");
            $.each(rows, function (index, row) {
                $(row).find(".tabulator-frozen").find(".tabulator-cell").find(".nominee-column").attr("checked", "checked");
                $(row).find(".tabulator-frozen").find(".tabulator-cell").find(".nominee-column").prop('checked', true);
            });
        },
        rowFormatter: function (row, data) {
                   },
    });


this is my full configuration for tabulator. The first column I have a checkbox to select a row, If there is only one page everything works fine. If more than one pages loaded(progressive rendering). If I select checkbox it gives error
Uncaught TypeError: Cannot read property 'NomineeId' of undefined.
this error is coming in _selectrow function.

**Comment by olifolkerd** [comment]
@Deepti-Rajput ,

I don't think you are understanding what i am asking for, i need to see the data that is returned from the server ***NOT***  your table constructor object. I dont think the issue ahs anything to do with how you have setup your table, i dont think your ajax request is returning things in the correct format.

Cheers

Oli

**Comment by Deepti-Rajput** [comment]
Thanks,

Oli, I made some minor changes in this and its working. Did not get time to reply your previous question.
Thanks for the awesome plugin.
