### ISSUE TITLE
Download xlsx

### ISSUE THREAD

**Issue by vmontal** [olifolkerd/tabulator#593]
why doesn't it work?

`        <script src="scriptApiJs/js-xlsx-master/dist/xlsx.full.min.js"></script>`

`
        $scope.download_xlsx = function () {
            $("#tabellaScalare").tabulator("download", "xlsx", "data.xlsx");
        };
`
As you can see, it's an angularJs environment (could it be a problem?)

**Comment by vmontal** [comment]
and here the table constructor:

`$("#tabellaScalare").tabulator({
                fitColumns: false,
                sortable: false,
                colResizable: false,
                pagination: "local",
                paginationSize: 10,
                progressiveRenderSize: 10,
                progressiveRenderPeriod: 100,

                columns: [
                    { title: "id", field: "ID", visible: false },
                    { title: "idR", field: "ID_Rapporto", visible: false },
                    { title: "ppp", field: "Periodo", visible: false },
                    { title: "EC", field: "EC", visible: false },
                    { title: "SCA", field: "SCA", visible: false },
                    { title: "(X)", field: "Lavorato", width: parseInt(larghezza * 0.02), sorter: "string", formatter: "tickCross", align: "center" },
                    { title: "Periodo", field: "Data", width: parseInt(larghezza * 0.075), align: "center" },
                    { title: "Numeri Dare", field: "Num_Deb", formatter: mask.decimalFormatter, sorter: "number", width: parseInt(larghezza * 0.09), align: "right" },
                    { title: "Interessi Dare", field: "INT_DEB_E", formatter: mask.moneyFormatter, sorter: "number", width: parseInt(larghezza * 0.085), align: "right" },
                    { title: "Commissioni", field: "COMMISSIONI_E", formatter: mask.moneyFormatter, sorter: "number", width: parseInt(larghezza * 0.085), align: "right" },
                    { title: "Spese Scalare", field: "SPESE_E", formatter: mask.moneyFormatter, sorter: "number", width: parseInt(larghezza * 0.085), align: "right" },
                    { title: "Spese Movimenti", field: "GESTIONE_E", formatter: mask.moneyFormatter, sorter: "number", width: parseInt(larghezza * 0.085), align: "right" },
                    { title: "Costo Totale", field: "COSTO", formatter: mask.moneyFormatter, sorter: "number", width: parseInt(larghezza * 0.085), align: "right" },
                    { title: "Utilizzato", field: "GMD_E", formatter: mask.moneyFormatter, sorter: "number", width: parseInt(larghezza * 0.09), align: "right" },
                    { title: "Accordato", field: "ACCORDATO_E", formatter: mask.moneyFormatter, sorter: "number", width: parseInt(larghezza * 0.09), align: "right" },
                    { title: "TAN", field: "TAN", formatter: mask.percentFormatter, sorter: "number", width: parseInt(larghezza * 0.055), align: "right" },
                    { title: "TEG 108", field: "TEG108",formatter: mask.percentFormatter, sorter: "number", width: parseInt(larghezza * 0.055), align: "right"},
                    { title: "Tasso Soglia", field: "TUSURA", formatter: mask.tassoFormatter, sorter: "number", width: parseInt(larghezza * 0.055), align: "right" },
                    { title: "Int_COSTO", field: "Int_COSTO", formatter: mask.moneyFormatter, visible: false },
                    { title: "COSTO_TOTALE", field: "COSTO_TOTALE", formatter: mask.moneyFormatter, visible: false },
                    { title: "ACC_COSTO", field: "ACC_COSTO", formatter: mask.moneyFormatter, visible: false },
                    { title: "COSTO_TOTALE_ACC", field: "COSTO_TOTALE_ACC", formatter: mask.moneyFormatter, visible: false },
                ],

                index: "ID",

                rowClick: function (e, id, data, row) {
                    dataCliente.IDScalare = parseInt(data.ID);
                    currentPage = parseInt($("#tabellaScalare").tabulator("getPage"));
                    $scope.tabMenu = 0;
                    $scope.nuovoScalare = false;
                    $scope.$apply();
                    getData(dataCliente.IDRapporto, dataCliente.IDScalare);
                },

                rowFormatter: function (row, data) {
                    var scalare = parseInt(data.SCA);
                    if (scalare > 1) {
                        row.css({
                            color: "red"
                        });
                    };
                },

            });`

**Comment by vmontal** [comment]
version 2.9.0

**Comment by olifolkerd** [comment]
im afraid xlsx download functionality is only available in versions 3.0+
