### ISSUE TITLE
rowClick and cellClick

### ISSUE THREAD

**Issue by vipera7** [olifolkerd/tabulator#594]
Hello again Oli !

I'm having an issue about cellClick and rowClick. I want to display a modal on a row click but I don't want to display it if I click on a partiular cell (in my issue it's on **_action_** cell).

Here is my constructor:
``` javascript

$("#example-table").tabulator({
    index:"id",
    columns:[
        {title:"Id", field:"id", visible:false},
        {title:"Status", field:"status"},
        {title:"Date d'ajout", field:"date_add"},
        {title:"Action", field:"action", headerSort:false, formatter:"html",                   
        cellClick:function(e, cell){ $('#info').modal('hide'); }},
    ],
    rowClick:function(e, row){
        $('#info').modal('show');
    },
});
```

Thank you !

**Comment by olifolkerd** [comment]
Hey,

That is no problem, you just need to put the following line of code in the ***cellClick*** callback on the cell you don't want to trigger a row click:

```js
e.stopPropagation();
```

That will prevent the click event propagating up the DOM and give you the functionality you are after.

Cheers

Oli

**Comment by vipera7** [comment]
It works perfectly ! Thank you again Oli.

Just one more question, how can I change the cursor style on hover on particular cell (on _**status**_ and _**date_add**_ field) ?

**Comment by olifolkerd** [comment]
You would need to make a css tweak for that. if for example you wanted to change the status cell cursor to a crosshair:

```css
.tabulator .tabulator-row .tabulator-cell[tabulator-field="status"]:hover{
    cursor:crosshair !important;
}
```

Cheers

Oli

**Comment by Bhagyagali** [comment]
e.stopPropagation(); - this is not working for me in React js :( Anybody knows why it is not working

**Comment by Bhagyagali** [comment]
I have a radio button in the first column and on click of the row I am redirecting to another page. I have tried e.stopPropagation(); but still redirection is happening.

**Comment by leo-bogastry** [comment]
HI @olifolkerd I'm on version 6.2.4 of the tabulator, and I have this same scenario, a `rowClick` event but a cell has a `cellClick` event. The `e.stopPropagation()` is not having the desired effect because the `rowClick` event seems to be triggered first. Any suggestion?

**Comment by vitjaz** [comment]
@olifolkerd  Same problem with tabulator 6.3. 

> HI @olifolkerd I'm on version 6.2.4 of the tabulator, and I have this same scenario, a `rowClick` event but a cell has a `cellClick` event. The `e.stopPropagation()` is not having the desired effect because the `rowClick` event seems to be triggered first. Any suggestion?
