### ISSUE TITLE
2 tables per page

### ISSUE THREAD

**Issue by dimatk** [olifolkerd/tabulator#596]
Hi Oli,

U menya problema s dvumya tablitsami na stranitse. Kazhdaya tablitsa nakhoditsya v butstrap tabe. Pervaya tablitsa zagruzhayetsya uspeshno. Vtoraya tablitsa, kotoraya skryta vo vtorom tabe, teryayutsya razmery kolonok.
I have a problem with two tables on the page. Each table is in the bootstrap tab. The first table is loaded successfully. The second table, which is hidden in the second tab, loses the size of the columns.

table 1
![table1](https://user-images.githubusercontent.com/1029174/30957510-259fdc56-a443-11e7-9fe6-7acc54ea807e.png)

table 2
![table2](https://user-images.githubusercontent.com/1029174/30957529-344ad0da-a443-11e7-952e-b1e317681318.png)

**Comment by olifolkerd** [comment]
The issue is happening because the second table is being created when it is hidden.

When an element is hidden Tabulator cannot correctly calculate the width and height of the element so cannot render it correctly.

To get round this you should call the ***redraw*** function as soon as the table is made visible:
```js
$("#example-table").tabulator("redraw", true);
```

Cheers

Oli

**Comment by dimatk** [comment]
Some of the problems are solved, but some have remained. After applying the function, the data was drawn, but the columns remained pressed and small in width.

**Comment by olifolkerd** [comment]
that would suggest that the redraw function is still being called while the table is hidden, try adding a setTimeout of a second to test if that is the case.

if you are still having trouble could you post a copy of your table constructor.

Cheers

Oli
