### ISSUE TITLE
getPageSize

### ISSUE THREAD

**Issue by dimatk** [olifolkerd/tabulator#597]
Hi Oli,

I can set the number of records per page
.tabulator ("setPageSize", 50)
And how do I get how many records are currently installed on the table
.tabulator ("getPageSize") ???

**Comment by olifolkerd** [comment]
There is currently no function to get the number of rows per page, would this be a useful feature for you?

**Comment by dimatk** [comment]
This function is very useful (and very logical). When working with a table, I need to know how many records per page are installed. It is always necessary to set this value hard, which leads to unnecessary queries on the server.

**Comment by olifolkerd** [comment]
Hey @dimatk 

You will be happy to hear than in today's 3.3 release there is a new ***getPageSize*** function that returns the current number of rows per page:

```js
var pageSize = $("#example-table").tabulator("getPageSize"); // returns number of rows allowed per page
```

Thanks for the suggestion!

Cheers

Oli :)
