### ISSUE TITLE
Pagination and Row Grouping

### ISSUE THREAD

**Issue by Krigen** [olifolkerd/tabulator#599]
When I try to do 'groupBy' and 'pagination' I get the error:
_Invalid Setup Combination - Pagination and Row Grouping cannot be enabled at the same time_

My code needs Row Grouping, but it takes a long time to load. If I do plain Pagination, then the code loads a lot quicker. I have a large data set being used. 
Is there a way to speed up the row grouping, sorting or loading of the page?

**Comment by olifolkerd** [comment]
It sounds like you havn't defined the ***height*** of your table.

Once you define the height option it will enable the virtual DOM and will render almost any number of rows instantly.

Checkout the [Documentation](http://tabulator.info/docs/3.2#virtual-dom) for more info on the Virtual DOM.

Cheers

Oli

**Comment by Krigen** [comment]
Do you mean like
```
$("#tabulator").tabulator({
   pagination:"local",
   paginationSize:100,
   height: "100%";
   groupBy: "srcip",
```

**Comment by olifolkerd** [comment]
yup, thats the one.

At the moment Tablulator cannot offer pagination and grouping at the same time, but if you have the height defined you shouldnt have any loading time issues when using row grouping.

if you are still having loading issue, how are you loading ur data, from an ajax request or from loadcal sources, and how many rows are you talking about.

If you are still having trouble, could you post a copy of your table constructor. Also which version of Tabulator are you using?

Cheers

Oli

**Comment by Krigen** [comment]
It works. Thank you
