### ISSUE TITLE
Visual Bug when table width as a percentage.

### ISSUE THREAD

**Issue by Astalavista70** [olifolkerd/tabulator#6]
The main div width is : 1336.5 px
Tabulator use a width of 1334.5 px

To fix that i've change a Math.floor to a Math.ceil at line 1236
~~I've changed the line 1214~~ (This fix generate an owerflow-x of 1 or 2 px)

from
```javascript
1214 var totWidth = options.movableRows ? self.element.innerWidth() - 30 : self.element.innerWidth();

1236 var proposedWidth =Math.floor((totWidth - widthIdeal) / (colCount - widthIdealCount))
```
to
```javascript
/* This fix generate an owerflow-x of 1 or 2 px */
1214 var totWidth = options.movableRows ? self.element.outerWidth() - 30 : self.element.outerWidth();
/* This fix work */
1236 var proposedWidth =Math.ceil((totWidth - widthIdeal) / (colCount - widthIdealCount))
```

![abug](https://cloud.githubusercontent.com/assets/1778008/12503608/f9e13c10-c0d5-11e5-9f1d-28416f4b47fa.JPG)

**Comment by olifolkerd** [comment]
Nice Spot,  i will get that fixed this evening

**Comment by olifolkerd** [comment]
I have added a ***Math.Floor*** to the ***totWidth*** on line 1215, so all widths are worked out from a integer pix width. please confirm if this works for you. This way there is no overflow.

Cheers

**Comment by Astalavista70** [comment]
You are well annoyed to fix this visual concerns (and me too). with your calculated gap and all the rest ...
I reflected a little and I found the following fix:
```javascript
_init: function() {
	this.element.width(this.element.width);
	this.element.height(this.element.height);
},
```

jQuery work with rounded width and height (not the real), with that fix, we will make the integer.

**Comment by olifolkerd** [comment]
Thanks for the code. I have a solution worked out. if you can wait till this evening i will have an update available with the changes in.

Cheers

**Comment by Astalavista70** [comment]
I've used the last fix I posted, it suits me. anyway, the screens do not display half pixels...

**Comment by Astalavista70** [comment]
I think I'll have to learn to use this site to create a Fork ...

**Comment by olifolkerd** [comment]
the last fix was not quite right which is why i removed the comment.

As i was saying if you can be patient and give me a few hours i will get something in this evening.

**Comment by olifolkerd** [comment]
This has now been fixed and should render correctly to the edge of the table.
