### ISSUE TITLE
order column of value (€ xx,xx)

### ISSUE THREAD

**Issue by ffamos** [olifolkerd/tabulator#60]
Hi.. i have a problem to order a column of value (ex. €100,00 €50,00 €200,00 etc).
If i don't use the "€" all ok using **sorter:"number"** but if i insert the symbol Euro i can't order.. also if use other type of **sorter**

es:
{id:1, cliente:"Pippo", totale_anno_cliente:"€ 100,00" },
{id:1, cliente:"Pluto", totale_anno_cliente:"€ 50,00" },

can help me ?
thanks (and sorry for my english)

**Comment by olifolkerd** [comment]
Hi ffamos,

There are a couple of ways you can do this.

The best option would be to pass the numeric values in the data and then use a custom formatter to present the data in the table formatted as a currency. This would keep the data as a number and allow you to use the number sorter:

```js

var tableData = [
	{id:1, cliente:"Pippo", totale_anno_cliente:"100.00" },
	{id:1, cliente:"Pluto", totale_anno_cliente:"50.00" },
];

$("#example-table").tabulator({
	columns:[
		{field:"cliente", title:"Cliente"},
		{field:"totale_anno_cliente", title:"Totale Anno Cliente",  sorter:"number", formatter:function(value, data, cell, row, options, formatterParams){
			return "€ " + value;
		}},
	],
});

$("#example-table").tabulator("setData", tableData);
```

Another option would be to pass the data as you are currently doing, as a string, but define a custom sorter that converts the string back to a number before sorting:

```js
var tableData = [
	{id:1, cliente:"Pippo", totale_anno_cliente:"€ 100,00" },
	{id:1, cliente:"Pluto", totale_anno_cliente:"€ 100,00" },
];

$("#example-table").tabulator({
	columns:[
		{field:"cliente", title:"Cliente"},
		{field:"totale_anno_cliente", title:"Totale Anno Cliente",  ssorter:function(a, b, aData, bData){
			return parseFloat(String(a).replace(",","").replace("€ "," ")) - parseFloat(String(b).replace(",","").replace("€ "," "));
		}},
	],
});

$("#example-table").tabulator("setData", tableData);
```

Let me know if you need any more help.

Oli

**Comment by ffamos** [comment]
Hi.. thanks for help.. but the order don't work correctly... but solved using the first method changing sorter with "alphanum"

thanks again :)
