### ISSUE TITLE
scrollTo()

### ISSUE THREAD

**Issue by brenow** [olifolkerd/tabulator#602]
Hello,

I am using 3.1 and trying to call row.scrollTo(). The indexOf() in scrollToRow() always returns -1. In the debugger, I can see my row in the list of displayRows. For testing, I added a for loop to match row id's and that worked great. Is there a bug here? 

Thank you!

**Comment by olifolkerd** [comment]
could you post an example of the code you are trying to use and your table constructor.

Cheers

Oli
