### ISSUE TITLE
When using  variableHeight = true, seems like it's not rendering correctly

### ISSUE THREAD

**Issue by KoreBcn** [olifolkerd/tabulator#603]
Hi,

The column settings look like this:

columns:[
		{title:"Canal", field:"channel", formatter:"image", align:"center", variableHeight:true},..]

but the images are still hiding the overflow.

The example you have in the documentation is with a customized formatter.  Does this property only work with that?

Thanks in advance for this.

**Comment by olifolkerd** [comment]
could you post a copy of your whole table constructor so i can test with your setup

**Comment by KoreBcn** [comment]
$("#sponsorsTable").tabulator({
			fitColumns:true,
			tooltips:true,
	columns:[
		{title:"Patrocinador", field:"sponsor", formatter:"image", align:"center", variableHeight:true},
		{title:"Ingrés incial", field:"startincome", sortable:true, sorter:"number", formatter:"money", formatterParams:{precision:0, thousand :'.', symbol:'€', symbolAfter:true}},
		{title:"Regal exclusiu", field:"extra", sorter:"string", formatter:"textarea"},
		{title:"Bonus", field:"bonus", sortable:true, sorter:"string", formatter:"textarea"},
		{title:"Fixes", field:"fixed", sortable:true, sorter:"number", formatter:"money", formatterParams:{precision:0, thousand :'.', symbol:'€', symbolAfter:true}},
		{title:"Variables", field:"variable", sortable:true, sorter:"string", formatter:"textarea"},
		{formatter:printIcon, width:40, align:"center", cellClick:function(e, cell){
			
			alert(cell.getRow().getCell("sponsor").getValue() + " ?")
			
			
			}}	
		]
	});
	
	$("#sponsorsTable").tabulator("setData", "sponsorsInfo.php");

**Comment by olifolkerd** [comment]
do you have an example of an image that overflows that i could use?

Cheers

Oli

**Comment by KoreBcn** [comment]
![acs](https://user-images.githubusercontent.com/32383486/31153689-ed91f2e8-a8e5-11e7-8dcb-bd5a52f5a4d6.PNG)

It looks like it renders to the text of the field with the textarea formatter. However, I tried it without it and not working either.

Do I need to load another lib other than the main one?

Thank you again.

Carlos

**Comment by olifolkerd** [comment]
Hey Carlos,

The issue you seem to be having is that the image is taking a little too long to load, so Tabulator has already finished the height/width maths calculations before the image loads.

The best option would be to use a custom image formatter that would trigger a row height adjustment when the image has loaded:
```js
//define image formatter
var imageFormatter = function(cell, formatterParams){
	var value = this.sanitizeHTML(cell.getValue());
	var img = $("<img src='" + value + "'/>");

	img.on("load", function(){
		cell.getRow().normalizeHeight();
	})

	return img;
}

//add in column definition object
{title:"Patrocinador", field:"sponsor", formatter:imageFormatter, align:"center", variableHeight:true},
```

Let me know if that helps

Cheers

Oli

**Comment by olifolkerd** [comment]
If you wanted the image to resize to fit the column, you could add an extra style to the formatter to make it resize to fit the width:

```js
//define image formatter
var imageFormatter = function(cell, formatterParams){
	var value = this.sanitizeHTML(cell.getValue());
	var img = $("<img src='" + value + "'/>");
        
        img.css({width:"100%"});

	img.on("load", function(){
		cell.getRow().normalizeHeight();
	})

	return img;
}
```

**Comment by KoreBcn** [comment]
Hi Oli,

That worked perfectly. 

Thank you for your time :)

Carlos
