### ISSUE TITLE
how to rowspan ? just like the picture .

### ISSUE THREAD

**Issue by diffcultpro** [olifolkerd/tabulator#605]
![image](https://user-images.githubusercontent.com/31839891/31008450-bef36a5a-a536-11e7-89f2-cda5ec1c492c.png)

**Comment by olifolkerd** [comment]
Im afraid col-span and row-span options are not yet available in Tabulator,

But they are on the roadmap for a future release so check back later in the year.

Cheers

Oli

**Comment by Identity404** [comment]
Hi, is this feature still on the roadmap?

It would be really helpful :)

**Comment by Identity404** [comment]
> Im afraid col-span and row-span options are not yet available in Tabulator,
> 
> But they are on the roadmap for a future release so check back later in the year.
> 
> Cheers
> 
> Oli

Hi, is this feature still on the roadmap?

It would be really helpful :)

**Comment by olifolkerd** [comment]
Hey @Identity404 

It is on the roadmap for the 5.0 release.

Cheers

Oli :)

**Comment by KayakFisher205** [comment]
Looks like it was on the RoadMap for 5.3 but I guess its not in 5.4? I'm sure its a difficult task but I just wanted to confirm.
