### ISSUE TITLE
How to "addRow" when using custom formatters?

### ISSUE THREAD

**Issue by DevilWarrior** [olifolkerd/tabulator#607]
Hi, I'm using my own formatter, a simple pass-through that creates a select with some options given by the server. Than I'm using select2 to convert the select into a dropdown. All works except when I try to create a new row the column with the select is populated blank. How can I pass or set a default when creating a row?

PS: I spend some time here looking for an answer but I couldn't find one. Sorry if I'm asking a duplicate.

Best.

**Comment by olifolkerd** [comment]
Hey @DevilWarrior 

Thanks for getting in touch, no need to apologise, Im always happy to answer questions.

To create a row with data you can use the ***addRow*** function, passing an object containing any of the initial values you want to set:

```js
$("#example-table").tabulator("addRow", {name:"Billy Bob", age:"12", gender:"male", height:1});
```

Let me know if that helps,

Cheers

Oli :)

**Comment by DevilWarrior** [comment]
Thanks, that worked!
