### ISSUE TITLE
Exclude specific row from standard function like Group

### ISSUE THREAD

**Issue by dasio86** [olifolkerd/tabulator#608]
Hi,
it's possible to exclude specific rows from the functions like GroupBy and rowHandle?
Thank you

**Comment by olifolkerd** [comment]
Im not sure what you mean by exclude? you can certainly filter rows from the table.

Could you explain your usage case in more detail, i can then hopefully provide a solution to your problem.

Cheers

Oli

**Comment by dasio86** [comment]
Thank you for your support.
I have some rows of the table (i can use an hidden column for recognize it) that musn't be affected from GroupBy and for theese rows i need to disable rowhandle too.
This is necessary because i need to insert a "fake rows" with a subtotal price under specific rows. 

![image](https://user-images.githubusercontent.com/32384431/31114842-34f0ca04-a820-11e7-9b75-c67a2559e71b.png)

How you can see in the image the highlighted rows musn't be affected by GroupBy (I use "Categoria Merceologica" column for that) and i need to disable rowHandle. 
Actually i use an index for ordering the rows so if  an user move one of theese two rows in another position or enable the groupby function the result is wrong.
I hope I was clear.
Meanwhile thanks for the support

**Comment by olifolkerd** [comment]
I would suggest grouping your rows that need totals togeather, then using column calculations to do the totals for you.

An example of column calculations can be found [here](http://tabulator.info/examples/3.3#calculations)

When column calculations are used as well as groups the calculations are worked out per group.

Let me know if that helps.

Cheers

Oli

**Comment by dasio86** [comment]
Thank you for you support. I find the best solution for me. I create a bundle object that can be explore on click.
