### ISSUE TITLE
Movable rows: move a row from one table to another?

### ISSUE THREAD

**Issue by AndrewHutcheson** [olifolkerd/tabulator#610]
Any way to do this? It would be useful.

The easy case is when the columns are identical in both tables, however it would be nice to call a function to parse data if the tables are not the same size/type.

**Comment by olifolkerd** [comment]
Hey @AndrewHutcheson 

You can't do this at the moment, but it is scheduled for the next release!

Cheers

Oli

**Comment by mikeshow** [comment]
ok, cheers.

**Comment by AndrewHutcheson** [comment]
Good to hear. 

It would also be nice to switch two cells within the same table. I.e. drag cell A to a different row (same column) and then the cell that was there goes to cell A's previous place.

**Comment by olifolkerd** [comment]
Hey @AndrewHutcheson 

You will be happy to hear that I have just pushed an update for this to the 3.5 branch which should be released later in the week.

You will be able to enable this by passing a css selector for the receiving tables to the ***movableRowsConnectedTables*** option:

```js
$('#example-table').tabulator({
    movableRows: true, //enable movable rows
    movableRowsConnectedTables: "#table2, #table3", //connect to these tables
})
```

For a sneek preview of the documentation [Click Here](http://tabulator.info/docs/3.5#row-move-table);

Cheers

Oli :)
