### ISSUE TITLE
How to make movableRows persistent?

### ISSUE THREAD

**Issue by mikeshow** [olifolkerd/tabulator#613]
Hello,

I have added "movableRows:true", the column "rowHandle:true, formatter:handle". I can move the rows.
But then what? I can't see nothing in the documentation telling me how to make that new sort persist.

**Comment by olifolkerd** [comment]
Hey,

Thanks for getting in touch, by persist, do you mean update that data in your database?

There is a ***rowMoved*** callback that is called after a row as been moved, you can put any logic in here to write that back to your database:

```js
$("#example-table").tabulator({
    rowMoved:function(row){
        //row - row component
    }
});
```

Let me know if you need any more info.

Cheers

Oli

**Comment by mikeshow** [comment]
I am already using rowMoved. But what can I do with it to persist the order. There is a hidden variable or something known to just a select few?

**Comment by olifolkerd** [comment]
whay do you mean by persist the order?

**Comment by olifolkerd** [comment]
what do you mean by persist the order, do you mean between page loads? In that case you would have to write it back to a server side database. if you want to retreive the current table data in the ***rowMoved*** callback you can use the ***getData*** function:
```js
var data = $("#example-table").tabulator("getData");
```

if you are talking about prevent sorts changing the order then you cant do that, sorting inherently reorders the table, usually when using row movement you wouldn't have column sorters so the positions would remain fixed

Just so you know, there are never hidden features, every feature of Tabulator is open to all and the documentation is written at the same time as the code to ensure it is always fully accessible.

Cheers

Oli

**Comment by mikeshow** [comment]
Hi,
I thought you had a mechanism to save the sort order and sort back at load time. As it is, rowMoved is useless because a ton of work is necessary to do that.
Thanks anyway Oli.

**Comment by olifolkerd** [comment]
Hey,

The persistent column layouts it only for columns, not sorting, but it would be really easy to write a bit of code that gets triggered in the ***dataSorted*** callback to store the sorts in local storage and then load them back again on page load, That would work for column sorting but not reodering.

If that would be useful to you let me know, i would be happy to post some example code.

Cheers

Oli

**Comment by mikeshow** [comment]
Hi Oli,
I have added a sort order field in the table and the user enters what he wants. It is in a master/detail scenario and the number of lines involved for each detail is limited like 3 to 5. So not worth it to spend time on that to implement something more complex.

**Comment by olifolkerd** [comment]
sounds like a good solution
