### ISSUE TITLE
Problems with groupStartOpen.

### ISSUE THREAD

**Issue by mikeshow** [olifolkerd/tabulator#614]
Hi,
1 - The arrow once pointing down never points right again when the group is opened/closed, remains down.
2 - If groupStartOpen is false, the rows are displayed in descending sort order. If groupStartOpen is true they are in ascending order (as expected). The parameter dir:"asc" changes nothing. The sorter:function() changes nothing as it is not triggered.

**Comment by olifolkerd** [comment]
Hey,

when you refer to arrow, are you referring to the sort arrow on the header, or the arrow in the group header.

Could you post a copy of your table constructor object?

What version of Tabulator are you using?

Cheers

Oli

**Comment by mikeshow** [comment]
Nothing fancy:

Ajax call to get the datas in php with wordpress. Each line in an array as follow:
$sp_data[]  = array(
	'id'            => $category->id,
	'categ_name'    => $categ_name,
	'categ_parent'  => $category->parent,
	'categ_groupby' => $categ_groupby,
	'category_name' => $category_name,
);

When it's done, send the result:
$value = array( 'content' => $sp_data, 'message' => '' );
wp_send_json_success( $value );

In the js file, populate tabulator:
var dp_list = response.data.content;
$("#thetable").tabulator("setData", dp_list);

And in tabulator (version simplified that's working):
$("#thetable").tabulator({
 layout: 'fitColumns',
 sortable: false,
 virtualDom: false,
 placeholder: i18n[current_language].t_no_data,
 groupBy: 'categ_groupby',
 groupStartOpen: true,
 groupToggleElement: "header",
 groupHeader: function (value, count, data) {
	return data[0].categ_name;
 },
 columns: [
	{title: i18n[current_language].t_name, field: "categ_name", align: "left", formatter: "html", headerSort: false}
 ]
});

The arrow being the one in the group header.
Tabulator 3.2 and now 3.3.

**Comment by olifolkerd** [comment]
Thanks for sending over the constructor, it was a great help.

It looks like there is an issue updating the arrow when the virtual DOM is disabled. i will get a fix in for this in this weekends patch release.

Could i ask why you have disabled the virtual DOM, it would be helpful for me to know the usage case so i can tailor Tabulators features to its users? are you working on a table that can grow indefinitely?

**Comment by olifolkerd** [comment]
I have pushed a fix to the master branch for the issue in your first point, this will be included in this weekends 3.3.1 release.

I don't understand what you mean in point 2, you don't appear to trigger a sort anywhere in your code, so no sorter will be triggered. If you want your table sorted when it first loads then you need to set the ***initialSort*** property:
```js
$("#example-table").tabulator({
    initialSort:[
        {column:"age", dir:"asc"},
    ]
});
```

Let me know if that helps,

Cheers

Oli

**Comment by mikeshow** [comment]
I'm not using the virtual dom because it changes nothing to me. I'm not using your pagination system. I get solely the number of lines for a page with each ajax request.
For the point 2, I'm not using any sort anywhere because my rows are sorted and I didn't know I had to. I thought tabulator would just display the rows as they without changing the order. I'll look into it tomorrow.

**Comment by mikeshow** [comment]
Hi Oli,

Here's the content of the array for the field 'sort_categ'. The first word is the 'category_name'(accomodation,activities,artistes):

Accommodation-Accommodation
Accommodation-3 Star
Accommodation-4 Star
Accommodation-5 Star
Accommodation-Autres

Activities-Activities
Activities-Creative Team Game
Activities-Gourmet
Activities-Public Events
Activities-Sports Boating Water Activities
Activities-Sports Driving Riding
Activities-Sports Flying
Activities-Sports Others
Activities-Wellness

Artistes-Artists
Artistes-Agence Show Performers
Artistes-Animateur
Artistes-Baroque M\u00e9dieval Equestre
Artistes-Casino Poker Wine Casino
Artistes-Cocktail Wine Cooking Party

As you can see the order is right.


Heres's the tabulator's code:

```javascript
var tbltr = $("#thetable");

tbltr.tabulator({
 layout: 'fitColumns',
 sortable: false,
 virtualDom: true, // or false in my case changes nothing
 placeholder: i18n[current_language].t_no_data,
 groupBy: 'categ_groupby',
 groupStartOpen: false,
 groupToggleElement: "header",
 groupHeader: function (value, count, data) {
	return data[0].category_name;
 },
 columns: [
	{title: i18n[current_language].t_name, field: "sort_categ", align: "left", headerSort: false, sorter:"alphanum"},
	{title: i18n[current_language].t_name, field: "categ_name", align: "left", formatter: "html", headerSort: false},
 }
});
tbltr.tabulator("hideColumn", "sort_categ");
tbltr.tabulator("setSort", "sort_categ", "asc");
```


Here's what I get initially:

>group-Accommodation
 Autres
 Accommodation
 5 Star
 4 Star
 3 Star

>group-Activities
 Wellness
 Sports Others
 Sports Flying
 Sports Driving Riding
 Sports Boating Water Activities
 Public Events
 Gourmet
 Creative Team Game
 Activities

>group-Artistes
 Cocktail Wine Cooking Party
 Casino Poker Wine Casino
 Baroque Médieval Equestre
 Artistes
 Animateur
 Agence Show Performers
  
  
They are in reverse order initially. And when I redraw tabulator they are in the right order.

If I write this:

```javascript
tbltr.tabulator("setSort", "sort_categ", "desc"); // see -> 'desc'
```

They are in right order initially. And when I redraw tabulator they are in reverse order.

**Comment by olifolkerd** [comment]
Hey @mikeshow 

Im afraid i still can't seem to replicate your issue, do you have a working JSFiddle or CodePen example i could see in action?

Cheers

Oli
