### ISSUE TITLE
Display Images from MYSQL DB into Table

### ISSUE THREAD

**Issue by dravecki** [olifolkerd/tabulator#616]
Is there anyway for tabulator to display images from a mysql db?
Tabulator can see that there is something there using this code, but nothing seems to show up in the cell.
_________________________________________________________________________________________________________
<img width="1256" alt="screen shot 2017-10-05 at 12 20 39 pm" src="https://user-images.githubusercontent.com/31296802/31238352-b4126cf4-a9c7-11e7-8add-4a8856735fb9.png">

NODEJS APP.JS
app.get('/api/maptable/:site_id?', function(req, res, next) {
var site_id = req.params.site_id;
        var query = `SELECT * FROM site_maps WHERE site_id LIKE '${site_id}'`;
        db.query(query, function(err, result) {
            res.send(JSON.stringify(result));
            console.log(req.params.site_id);
        })
});
_________________________________________________________________________________________________________
TABULATOR JS CODE
function displayMapDataInTable() { 
  $("#map-table").tabulator({
    fitToData:true, 
    fitColumns:true, 
    columns:[ 
        {title:"Room Map", field:"room_map", sortable:true},
	    {title:"Demarc Map", field:"demarc_map", sortable:true},
	    {title:"Site Network Diagram", field:"site_net_diag", sortable:true, editable:true},
    ],
    },
  })}

**Comment by olifolkerd** [comment]
Hey,

Tabulator can display images in any way you like, it just depends on how you want to display that data,

How are you passing the row data into the table?

Will you be passing the image as a URL or a base64 encoded data url?

Cheers

Oli

**Comment by dravecki** [comment]
Hi Oli,

I believe URL.
Right now it's coming back like this in inspector
"[{"site_id":"PIT11","room_map":{"type":"Buffer","data":[137,80,78,71,13,10,26,10,0,0....."


-Dave Zarzecki

On Oct 05, 2017, at 05:10 PM, Oli Folkerd <notifications@github.com> wrote:

Hey,
Tabulator can display images in any way you like, it just depends on how you want to display that data,
How are you passing the row data into the table?
Will you be passing the image as a URL or a base64 encoded data url?
Cheers
Oli

**Comment by olifolkerd** [comment]
If it is just a url then you can use the image formatter in the column definition:

```js
{title:"Image Col", field:"image", formatter:"image"},
```
Though looking at your screen shot you dont appear to have any values in that table row, which suggest either your row data is empty strings or the object is not properly formatted. 

As an example Tabulator will expect its data as an array of objects *(an actual array, JSON is only accepted as an ajax response)*:

```js
var data = [
    {id:1, name:"steve", image:"/images/1.jpg"},
    {id:2, name:"bob", image:"/images/2.jpg"},
    {id:3, name:"jom", image:"/images/3.jpg"},
]

$("#example-table").tabulator("setData", data);
```

Let me know if that helps.

Cheers

Oli

**Comment by dravecki** [comment]
I think I got everything you listed there but I am not sure about the var data portion.  I am getting a an error in a TypeError in inspector.  The shots are below.  Thanks for helping out a newbie by the way.

-Dave Zarzecki

On Oct 05, 2017, at 08:24 PM, Oli Folkerd <notifications@github.com> wrote:

If it is just a url then you can use the image formatter in the column definition:
{title:"Image Col", field:"image", formatter:"image"},
Though looking at your screen shot you dont appear to have any values in that table row, which suggest either your row data is empty strings or the object is not properly formatted.
As an example Tabulator will expect its data as an array of objects (an actual array, JSON is only accepted as an ajax response):
var data = [
    {id:1, name:"steve", image:"/images/1.jpg"},
    {id:2, name:"bob", image:"/images/2.jpg"},
    {id:3, name:"jom", image:"/images/3.jpg"},
]

$("#example-table").tabulator("setData", data);
Let me know if that helps.
Cheers
Oli

**Comment by olifolkerd** [comment]
tthe var data is just an example of the expected format of an array or row objects being passed into the table, in that instance there were three columns worth of data in each row, ***id*** , ***name*** and ***image***

If you are having trouble with your table i suggest passing in an array of test data to make sure your table is configured correctly, then try linking to the database.
