### ISSUE TITLE
Custom Filtering Functions

### ISSUE THREAD

**Issue by hunsinger08** [olifolkerd/tabulator#617]
I'm experimenting with Tabulator on C9.  When trying to use a row.click event to I keep getting console error "Uncaught TypeError: 
$(...).tabulator is not a function.  "

In my code I'm using $("#example-table").

I am lost..any debugging suggestions?

    
    $("#example-table").tabulator({
    layout:"fitDataFill",
    height:"311px",
    selectable:true,
    selectablePersistence:true,
    // responsiveLayout:true,
    // columnVertAlign: "bottom",
    columns:[ //Define Table Columns
        // {title:"id", field:"id"},
        {title:"Project", field:"proj_id", headerFilter:true},
        {title: "Activity", field:"activity", headerFilter:true},
        {title: "Finish", field:"finish", headerFilter:true},
        {title: "Work Package", field:"wp_id", headerFilter:true, cellClick:function(e, cell){WP_ID=cell.getValue()}},
    ],
    
    rowClick:function(e, row){
        console.log(WP_ID);
        $("#example-table").tabulator("addFilter", "wp_id", "=", '03-P');

**Comment by hunsinger08** [comment]
I suppose I am open to any suggestion which will allow me to accomplish the goal.

I have two tables with a similar data field.  I want to be able to click/select a row in one table and have it automatically filter the second table based on the common identifier (here is wp_id)

**Comment by hunsinger08** [comment]
I have resolved the issue.  Somehow I was calling out jQuery twice apparently.  The latter did not like me.

**Comment by olifolkerd** [comment]
Great news!
