### ISSUE TITLE
CDNJS links return Error 404

### ISSUE THREAD

**Issue by javierpacareu** [olifolkerd/tabulator#618]
Nothing to add but these two links are returning 404

https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.3.0/tabulator.min.css
https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.3.0/tabulator.min.js

Cheers

**Comment by javierpacareu** [comment]
Found the solution is missing the "js" and "css" in the route:

https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.3.0/css/tabulator.min.css
https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.3.0/js/tabulator.min.js

Now is correct

Cheers

**Comment by olifolkerd** [comment]
i have just updated the readme, good spot!
