### ISSUE TITLE
Set/Unset groupBy

### ISSUE THREAD

**Issue by shashankaugurs** [olifolkerd/tabulator#620]
Hi,
I have used this code to set group by on click of a button:
$("#tabulator-b").tabulator("setGroupBy", "master_group");

Now how can I remove that groupBY setting on click of a button??

Thanks

**Comment by olifolkerd** [comment]
you can remove the grouoBy by passing ***false*** to the **setGroupBy*** function:
```js
$("#tabulator-b").tabulator("setGroupBy", false");
```
