### ISSUE TITLE
Possible wrong line

### ISSUE THREAD

**Issue by notom** [olifolkerd/tabulator#621]
https://github.com/olifolkerd/tabulator/blob/75ab938714cca189bcb11c80b4ffe632c7e74dfb/dist/js/tabulator.js#L12853

Should't this be:
pageParams[this.paginationDataSentNames.sorters] = sorters;

**Comment by olifolkerd** [comment]
Good Spot!

I must have missed that one in the 3.3 update. I have pushed a fix to the master branch and will include it in this weekends patch update.

Let me know if you spot anything else.

Cheers

Oli
