### ISSUE TITLE
Bug in initial rendering of empty cells in closed group

### ISSUE THREAD

**Issue by tomheaps** [olifolkerd/tabulator#623]
Have just discovered a bug in the initial rendering of cells with no values when the rows that contain these cells are closed by the groupStart open function. Any cell which is empty does not increase in height when you subsequently open the row group leading to a very odd appearance - look at the empty cells under the row group in the image below:

![render](https://user-images.githubusercontent.com/13905479/31311463-82fa0044-aba4-11e7-989b-4eb764ed553c.png)

**Comment by olifolkerd** [comment]
Hi Tom,

I cant seem to replicate your error, what version of tabulator are you running and in which browser?

Do you have a copy of your table constructor you could share and a row of sample data that causes the issue?

Have you tried loading the table in a blank html page with no other libraries or css to check that no other styles are affecting it?

Is the table hidden when it is first created?

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @tomheaps 

Did you get to the bottom of this?

Cheers

Oli

**Comment by tomheaps** [comment]
Sorry, not had time to tackle yet - it is on my todo list.....

**Comment by tomheaps** [comment]
It appears that when rows are closed using the `groupStartOpen` option and you then subsequently open the rows (by clicking on the group header / arrow), if a cell within any of the newly opened rows is empty, that cell does not expand to the full height of the row so the cell (and the right border of the cell) is only 4px high (height is dictated only by any vertical padding applied to the cell as the cell has no content).

The same issue does not apply to any empty cells in rows that are visible on initial table rendering - such cells seem to have their height set to match the height of the row by javascript (tabulator I presume?).

I have tried running my page with all additional css / js resources removed and I still experience the same problem.

A workaround is that I have set a `min-height` property in tabulator.css to all cells that is equal to the height of the rendered row (30px) in my case:

```
.tabulator .tabulator-row .tabulator-cell {
   min-height: 30px;
}
```

It would be much better if tabulator set cell-height = row-height when opening rows from a closed row group?

**Comment by olifolkerd** [comment]
Hey @tomheaps 

Ahh, now i understand your problem, if you create your table while it is hidden you must call the ***redraw*** function once the table becomes visible.

The reason this is happening is because DOM elements have no height or width until they are first shown so tabulator cannot correctly calculate the height of cells when they are created and the table is not visible.

When you make your table visible call the following function and you should be all sorted:
```js
$("#example-table").tabulator("redraw", true);
```

Cheers

Oli
