### ISSUE TITLE
Custom groupHeader after sorting

### ISSUE THREAD

**Issue by Lazaroth** [olifolkerd/tabulator#627]
Hey,

I'm using a custom groupHeader when the table is created. However when someone has sorted, this is replaced with just the default text, and all styling is gone. How can I fix this?

**Comment by Lazaroth** [comment]
I did a workaround for this, but if you have an easy solution let me know.

**Comment by olifolkerd** [comment]
could you post a copy of your table constructor and group header function please?

also which version of Tabulator are you running?

**Comment by Lazaroth** [comment]
Latest version.

I can write everything, but in essence wrote something similar to:
```
groupHeader:function(value, count, data, group){
    return '<div style="background: blue;">' + value + "<span style='color:#d00; margin-left:10px;'>(" + count + " item)</span></div>";
},
```

I had two layers of groups and it was the top group which changed (didn't check the other one though).
Basically it would revert to (no outer div):
`return value + "<span style='color:#d00; margin-left:10px;'>(" + count + " item)</span>";`

**Comment by olifolkerd** [comment]
I cant seem to replicate your error, Could you paste your full table constructor so i can accurately replicate the issue.

Which version of Tabulator are you using?

Cheers

Oli

**Comment by Lazaroth** [comment]
I will get back on this issue soon.
