### ISSUE TITLE
Disable rowHandle on the fly

### ISSUE THREAD

**Issue by dasio86** [olifolkerd/tabulator#628]
Hi,
i set the MovableRow = True with rowHandle in a specific column but, in some , i need to set the rowHandle=false.
There is a build-in function for do that or i have to manage it by Row Moved callback?
Thank you

**Comment by dasio86** [comment]
Hi,
i added the rowHandle to a column that i hide when the row musn't be moved.
The solution works but if there is another available option is welcome.
Thank you

**Comment by olifolkerd** [comment]
That sounds like a good solution to me :)
