### ISSUE TITLE
Add additional data rows to parent object without full table refresh

### ISSUE THREAD

**Issue by cmfloyd13** [olifolkerd/tabulator#629]
Tabulator newbie here,

Searched for this in the docs and may have missed it.  I have a JS object that holds my JSON data retrieved from the server (oData.oCurrentrows).  I load 50 rows of data from the server on the initial page load and then make subsequent async AJAX calls to get more rows behind the scenes. I add these additional rows to oData.oCurrentRows using $.merge(). Ajax works, getting data, adding to oData.oCurrentRows works. All good on the communication and data sides.

My Tabulator table height is fixed at 650px (about 15 rows), and as I scroll down Tabulator is dynamically adding/deleting displayed rows as it should. It just isn't adding the additional rows beyond the first 50, even though the oData.oCurrentRows object now contains 200 or more rows. 

If I call the $("#div-mytable").tabulator("setData", oData.oCurrentRows) it does work. The table refreshes with all 200 rows.  The issue I am trying to resolve is that by calling $("#div-table-docbox").tabulator("setData", oDocbox.oCurrentRows) the table completely refreshes, so the user is taken to row 1, even if they were viewing row 20.  I am thinking that there is a Tablulator call that simply tells Tabulator that more rows were added to the initial data object without actually refreshing the table display on the screen at that time.  The "Loading Data by AJAX" option is a possibility, but I want to control what data loads and when, and I want to keep a reference to the data object in JS for other uses in the UI. Still reading, maybe I'll find the answers.

Thanks for feedback on this. - Chris

**Comment by olifolkerd** [comment]
Hi Chris,

The function you are looking for is the ***addData*** function, available in version 3.3 onwards
```js
$("#example-table").tabulator("addData", [{id:1, name:"bob", gender:"male"}, {id:2, name:"Jenny", gender:"female"}], true);
```
It will allow you to update the table data without triggering a full load.

If you are looking to update existing data and create new rows if they don't exist then the ***updateOrAdd** function is the one for you.

Let me know if that helps

Cheers

Oli

**Comment by cmfloyd13** [comment]
Well, they both sounded as though the should work, but the end result was a table reload with the new data in it. I’m still debugging to be sure there isn’t more happening behind the scenes.

I’ll can send a video screen capture if you want to see the data in action as it updates the table from the addData and updateOrAdd calls.

$("#div-table-docbox").tabulator("addData”, oDocbox.oCurrentRows)  // Updates the table display, scrolls to record 1 at top.

$("#div-table-docbox").tabulator(“updateOrAdd”, oDocbox.oCurrentRows)  // Updates the table display, scrolls to record 1 at top.


Hmmmm…..

Thanks

Chris

**Comment by olifolkerd** [comment]
Ahh yes,

Sorry, at the moment, adding any rows to the table will cause it to reset to the top, only updating a row will keep the table in the same position.

I will look into changing this behaviour in the next release as it could definitively be handled more smoothly.

Thanks for the suggestion

Cheers

Oli

**Comment by Lazaroth** [comment]
> as it could definitively be handled more smoothly
Could you look into doing something similar when filtering as well?

**Comment by olifolkerd** [comment]
The filtering is a lot harder, when you start removing rows from the table there is no reference point as to where it should stay. I would treat a filter as a change in data set and so redraw the table, but this could be an option. I will have a look into it

**Comment by Lazaroth** [comment]
And sorting too possibly. That shouldn't pose the same problem with reference point.

Regarding filtering, I would have used the scroll offset as the reference point, unless it's less than the height of items left.

**Comment by solarplex** [comment]
This would be a nice feature. 

Every time i send UpdateOrAdd, it resets back to the top of the page.

**Comment by olifolkerd** [comment]
Hey Guys,

You will be happy to hear that this issue has been resolved on the 3.4 branch and will be included in the release later today.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Tabulator version 3.4 has now been officially released!

You can find details of the new release in the [News Section](http://tabulator.info/news)

Full documentation of all the new features can be found [Here](http://tabulator.info/docs/3.4)

Cheers

Oli :)

**Comment by seb303** [comment]
I was reading this thread with interest, as it's exactly what I'm try to do - update data in a table without resetting the scroll position.  It works quite well using a mixture of the "deleteRow" and "updateOrAddData" commands.

The only problem is that newly inserted rows are always appended to the end of the table, seemingly in the order of the new data array.

Is there a way to insert the rows within the current sort order?  Calling "setSort" after the update resets the table scroll position unfortunately.

Another minor thing I noticed was that if the added rows cause a vertical scrollbar to be added, then a horizontal scroll bar appears.  To work around this I'm calling "redraw" after every update.  Not sure if there is a more efficient way to do this?

**Comment by irupeshprasai** [comment]
$('#InvoiceDetail').tabulator("addData", {}, false); is adding same value to all fileld when i am clicking add new row

**Comment by olifolkerd** [comment]
@irupeshprasai 

please create a new issue if you are having problems, this one has been closed for a very long time.

Cheers

Oli :)
