### ISSUE TITLE
How to get row data using .find('.a-cell-class')?

### ISSUE THREAD

**Issue by hohozhao** [olifolkerd/tabulator#63]
Hi Oli, @olifolkerd 

When adding a new row, I use "formatter" to set a button inside a cell "<button class='button-class'>Save</button>" and attach click event on it. 

So now some new rows added, and then click to sort the table, and then my attached click event get removed from the button after table sorted.

Now I want my click event back, I can use $("#table").find("button.button-class") to locate the buttons, but how to get the data for that particular row where the button resides in?

Thanks,

**Comment by olifolkerd** [comment]
Hi hohozhao,

The table is redrawn on a sort event so if you bound your click outside of the formatter it would have been lost when the elements were redrawn.

There are two ways you could avoid this.

You could bind the click event in the formatter, that would recreate the binding when the table is redrawn.
```js
var buttonFormatter = function(value, data, cell, row, options, formatterParams){
        
        var button = $("<button></button>");

        button.on("click", function(){
        	//do something on button click
        })

        return button; 
},

//create the Tabulator and assign custom formatter to column
$("#example-table").tabulator({
	columns:[
		{title:"Button", formatter:buttonFormatter},
	],
});
```

Or you could bind the event listener to the parent container and catch any events originating from the buttons there, that way it wouldn't matter that the button elements were destroyed as the binding is to the table containing element..

```js
var buttonFormatter = function(value, data, cell, row, options, formatterParams){
    var button = $("<button class='example-button'></button>");
    return button; 
},

//create the Tabulator and assign custom formatter to column
$("#example-table").tabulator({
	columns:[
		{title:"Button", formatter:buttonFormatter},
	],
});

$("#example-table").on("click", ".example-button", function(){
	//do something on button click
});
```

I Hope that helps

**Comment by olifolkerd** [comment]
if

**Comment by olifolkerd** [comment]
If you want to then get the row data from inside either of those event bindings you can find the parent row element and get its ***data*** data value. use the following code inside the event binding:

```js
var data = $(this).closest(".tabulator-row").data("data");
```

As an alternative option, you could also look at using the column onClick property to handle clicks on the buttons cell, which would be passed the row data as a parameter.

```js
var buttonFormatter = function(value, data, cell, row, options, formatterParams){
    var button = $("<button class='example-button'></button>");
    return button; 
},

//create the Tabulator and assign custom formatter to column
$("#example-table").tabulator({
    columns:[
        {title:"Button", formatter:buttonFormatter, onClick:function(e, cell, value, data){
            //e - the click event object
            //cell - the DOM element of the cell
            //value - the value of the cell
            //data - the data for the row the cell is in
        }},
    ],
});
```

**Comment by hohozhao** [comment]
Hi Oli,

Thank you so much. I just tested your suggested option 1, binding the click event on the formatter, and it works out as what I want. But I don't think option 2 should work, as what I want is to click and get the data for that row and post it. Just saw your latest reply, I did not know there's a .data() function to get the data for particular row. (just looked it up in jQuery). 

Thanks so much for your excellent work! I choose your plugin as I know you're pushing it to excellence day by day, and most actively than the others. :)

Cheers,
HoHo

**Comment by hohozhao** [comment]
Btw, the last option, using column onClick is not what I want, as there maybe a few buttons for different purpose inside 1 cell. It was my first choice and then I found the problem hence came to you when I got trap. :)

**Comment by olifolkerd** [comment]
Thanks for the kind words, its always nice to hear that people are enjoying using Tabulator.

If you want to give any feedback, bug report, requested features, etc, then just create another issue, one per bug/request. and i will look into them from there.

Cheers,
Oli
