### ISSUE TITLE
How to get the value of a cell that is not the current cell in a cellClick

### ISSUE THREAD

**Issue by joalcava** [olifolkerd/tabulator#630]
Hi, First of all, I want to say Thank you! for your really impressive and awesome work.
I wonder how to get the value of another cell in a cellClick, something like this:

```
$('#my-table').tabulator({
    { title: "The title", field: "id", ...}
    { title: "The name", field: "name",
        cellClick: function(e, cell){
            window.location.href = "/Some/Path/" + fields.id;
        }
    }
});
```

Is it possible? 

Thank You!

**Comment by olifolkerd** [comment]
is it a cell in the same row? if so you can call the ***getData*** function on the cell that was clicked that will return the data object for the whole row:
```js
$('#my-table').tabulator({
    columns:[
        { title: "The title", field: "id", ...}
        { title: "The name", field: "name",
            cellClick: function(e, cell){
                window.location.href = "/Some/Path/" + cell.getData().id;
        }
    ]
});
```
Let me know if that helps,

Cheers

Oli

**Comment by joalcava** [comment]
Hi @olifolkerd, That's just what I was looking for. Again thank you so much.
