### ISSUE TITLE
Edit on double click

### ISSUE THREAD

**Issue by notom** [olifolkerd/tabulator#631]
Can I change the edit trigger?

**Comment by notom** [comment]
Thank you, Oli.
In that case, can I trigger edit mode with a button? The thing is, edit mode is triggered too easily and you can edit a cell by mistake.

**Comment by olifolkerd** [comment]
Yeah that should be really easy. you would need to define a variable outside of tabulator to hold the editable state, then have a ***editable*** function check the state:

```js
//hold editable state
var tableEditable = false;

//check editable state
var editCheck = function(cell){
    return tableEditable;
}

$("#example-table").tabulator({
    columns:[
        {title:"Name", field:"name", edittor:"input", editable:editCheck),
    ]
});
```

You could then make your button toggle the value of the ***tableEditable *** variable.

I hope that helps

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @notom

I decided against allowing direct rebinding of the edit trigger as it would have interfered with a lot of other system functions. however when version 3.4 comes out tomorrow you will be able to do it with the following column definition:

```js
{title:"Name", field:"name", editor:"input", editable:false, cellDblClick:function(e, cell){
    cell.edit(true);
}},
``` 

The 'editable:false' prevents the editor from opening, the `cell.edit(true)' tiggers the cell edit and tells Tabulator to ignore the ***editable*** option.

I hope that helps,

Cheers,

Oli :)

**Comment by olifolkerd** [comment]
Tabulator version 3.4 has now been officially released!

You can find details of the new release in the [News Section](http://tabulator.info/news)

Full documentation of all the new features can be found [Here](http://tabulator.info/docs/3.4)

Cheers

Oli :)

**Comment by mateddy** [comment]
Hello Oli, thank you for providing help on all matters :)

I ran into this thread when I wish to have edit triggered by dblClick rather than click, but the hack above no longer works in Tabulator 3.5.3 :(

`{title:"Name", field:"name", editor:"input", editable:false, cellDblClick:function(e, cell){
    cell.edit(true);
}},`

**Comment by c3pos-brother** [comment]
Is there a resolution? doesnt seem to work on 3.5
