### ISSUE TITLE
Sorting with ajax

### ISSUE THREAD

**Issue by notom** [olifolkerd/tabulator#632]
Hi, Oli!

I'm having all asynchronous table. Everything is loaded with ajax. I'm trying to make the sorting sorted :). When I click on the column header (to sort by this column) the proper data is loaded in the proper way (direction: asc). Now, if I click again on the same cell header I expect the data to be sorted by the same cell in desc direction. But the request that it's send by the ajax is the same. 

The column is basic, no custom anything. And is numerical. And the sorting doesen't work on any column. Always send the "asc" direction.

**Comment by olifolkerd** [comment]
Hey,

Great Spot, turns out there was a bug in the axajSorting that was preventing sort direction changing when using only one column.

I have just pushed a fix to the master branch for this and will include it in this weekends patch release.

Thanks for letting me know.

Cheers

Oli :)

**Comment by funkindy** [comment]
Hi! Exactly the same issue is appeared with 4.2.3. When using ajaxSorting the sorting icon doesnt change on click and the sorter data in request always has dir: asc.
