### ISSUE TITLE
Question about programmatically resizing columns

### ISSUE THREAD

**Issue by distraub** [olifolkerd/tabulator#633]
When I call updateRow on a row that contains a text area, and the new text takes up a different amount of lines than the original, it doesn't update automatically. I found that if I change the width of the column it auto adjusts the height of text area cells. 

Is there a way to programmatically set the width of a column, or better yet a way to just call that auto cell sizing code?

**Comment by olifolkerd** [comment]
Hey @distraub 

You can set the ***variableHieght*** height property in a column definition to ***true*** :

```js
{title:"Name", field:"name", formatter:myCustomFormatter, variableHeight:true}
```

Or if you have access a row component you can call its ***normalizeHeight*** function:
```js
row.normalizeHeight();
```

Let me know if that helps

Cheers

Oli

**Comment by distraub** [comment]
row.normalizeHeight(); is exactly what I needed!
Thank you!
