### ISSUE TITLE
Issue with row height and image

### ISSUE THREAD

**Issue by dasio86** [olifolkerd/tabulator#634]
Hi,
i have some trouble with Row height with image inside.
I load the page that contain table and function inside a div on button pressure.
The first time when the table is rendered there is an issue with the height but if i click another time the button for load the table the height is perfect. 
Below you can find the screenshot and the code.
Thank you
**First**
![tabulator1](https://user-images.githubusercontent.com/32384431/31440103-02b9a84c-ae8f-11e7-9038-47e0df9b677e.JPG)
**Second**
![tabulator2](https://user-images.githubusercontent.com/32384431/31440104-02e54f56-ae8f-11e7-8228-393dd6cd110f.JPG)

**Code**

`        
$("#tabella_prospetto").tabulator({
       
                height: ($(window).height()-150)+'px', // set height of table
                groupClosedShowCalcs:true,
                addRowPos:"bottom",
                movableRows: true,
                placeholder:"Nessun prodotto registrato",
                groupHeader:function(value, count, data, group){
                

                    return value + "<span style='color:#d00; margin-left:10px;'>(" + count + " oggetti)</span>";
                },
                groupBy:raggruppamento,
                layout:"fitDataFill",
                groupToggleElement:"header", 
                    langs:{
                            "it-it":{ //French language definition
                                
                                "pagination":{
                                    "first":"Prima Pagina",
                                    "first_title":"Premier Page",
                                    "last":"Ultima Pagina",
                                    "last_title":"Dernier Page",
                                    "prev":"Pagina Precedente",
                                    "prev_title":"Précédent Page",
                                    "next":"Pagina Successiva",
                                    "next_title":"Prochain Page",
                                },
                                "headerFilters":{
                                    "default":"Filtro", //default header filter placeholder text
                                    "columns":{
                                        "name":"Filtro", //replace default header filter text for column name
                                    }
                                }
                            }
                        },
                        columnVertAlign:"bottom",
                        columns: [ //Define Table Columns
                            {
                                title: "",field: "id", headerSort:false,frozen:true, visible:false
                            },
                            {
                                title: "",field: "custom", headerSort:false,frozen:true, visible:false
                            },
                            {
                                rowHandle:true, formatter:"handle", headerSort:false, frozen:true, width:30, minWidth:30
                            }
                            ,
                            {
                                title: "Seleziona",field: "sel", headerSort:false,align:"center",formatter:'html',width:20,frozen:true
                            }, 
                            {
                                title: "Opzione",field: "opzione", headerSort:false,align:"center",editor:selectEditor 
                            }, 
                            {
                                title: "Quantità",field: "qtn",headerSort:false,editor:"number",validator:"min:0",align:"center",bottomCalc:"sum"
                            }, 
                            {
                                title: "Immagine",field: "img", formatter:"image",headerSort:false,align:"center",width:120,minWidth :50, variableHeight:true
                            }, 
                            {
                                title: "Descrizione",field: "desc",formatter:"textarea",headerSort:false,width:300,minWidth :100,align:"center",editor:"textarea"
                            },
                            {
                                title: "Marca",field: "marca",headerSort:false,align:"center"
                            },
                            {
                                title: "Modello",field: "modello",headerSort:false,align:"center", headerFilter:"input",bottomCalc:"count"
                            },
                            {
                                title: "Part Number", field: "pn",headerSort:false,align:"center"
                            },
                            {
                                title: "Tipologia",field: "tipologia", headerSort:false,align:"center", headerFilter:"input",width:50
                            },
                            {
                                title: "Funzione",field: "funz", headerSort:false,align:"center",editor:"input", headerFilter:"input",width:50
                            },
                            {
                                title: "Sala",field: "sala",headerSort:false,editor:"input",width:80, minWidth:80,align:"center", headerFilter:"input"
                            },
                            {
                                title: "Categoria</br>Merceologica", field: "cm",headerSort:false,align:"center", headerFilter:"input"
                            },
                            {
                                title: "Listino",field: "listino",headerSort:false,formatter:"money",formatterParams:{symbol:"€",symbolAfter:true,decimal:",",thousand:"."},align:"center",bottomCalc:"sum",bottomCalcFormatter:"money",bottomCalcFormatterParams:{symbol:"€",symbolAfter:true,decimal:",",thousand:"."},minWidth:"100",editor:"number",validator:"min:0"
                            },
                            {
                                title: "Totale Listino",field: "tot_listino",headerSort:false,formatter:"money",formatterParams:{symbol:"€",symbolAfter:true,decimal:",",thousand:"."},align:"center",bottomCalc:"sum",bottomCalcFormatter:"money",bottomCalcFormatterParams:{symbol:"€",symbolAfter:true,decimal:",",thousand:"."},minWidth:"100",validator:"min:0"
                            },
                            {
                                title: "Costo",field: "costo",headerSort:false,formatter:"money",formatterParams:{symbol:"€",symbolAfter:true,decimal:",",thousand:"."},align:"center",bottomCalc:"sum",bottomCalcFormatter:"money",bottomCalcFormatterParams:{symbol:"€",symbolAfter:true,decimal:",",thousand:"."},minWidth:"100"
                            },
                            {
                                title: "Totale Costo", field: "tot_costo",headerSort:false,formatter:"money",formatterParams:{symbol:"€",symbolAfter:true,decimal:",",thousand:"."},align:"center",bottomCalc:"sum",bottomCalcFormatter:"money",bottomCalcFormatterParams:{symbol:"€",symbolAfter:true,decimal:",",thousand:"."},minWidth:"100"
                            },
                            {
                                title:"Sconto 1", field:"sconto1",headerSort:false,formatter:"percento",align:"center",editor:"number",validator:"min:0"
                            },
                            {
                                title:"Sconto 2", field:"sconto2",headerSort:false,formatter:"percento",align:"center",editor:"number",validator:"min:0"
                            },
                            {   
                                title:"Sconto 3", field:"sconto3",headerSort:false,formatter:"percento",align:"center",editor:"number",validator:"min:0"
                            },
                            {
                                title:"Sconto 4", field:"sconto4",headerSort:false,formatter:"percento",align:"center",editor:"number",validator:"min:0"
                            },
                            {
                                title: "Sconto</br>Effettivo",field: "sconto_eff",headerSort:false,formatter:"percento",align:"center"
                            },
                            {
                                title: "Bid",field: "bid",headerSort:false,formatter:"money",formatterParams:{symbol:"€",symbolAfter:true,decimal:",",thousand:"."},align:"center",editor:"number",width:100,minWidth :100,bottomCalc:"sum",bottomCalcFormatter:"money",bottomCalcFormatterParams:{symbol:"€",symbolAfter:true,decimal:",",thousand:"."},minWidth:"100",validator:"min:0"
                            },
                            {
                                title: "Totale Finale",field: "tot_bid",headerSort:false,formatter:"money",formatterParams:{symbol:"€",symbolAfter:true,decimal:",",thousand:"."},align:"center",width:100,minWidth :100,bottomCalc:"sum",bottomCalcFormatter:"money",bottomCalcFormatterParams:{symbol:"€",symbolAfter:true,decimal:",",thousand:"."},minWidth:"100"
                            },
                            {
                                title: "Note",field: "note",formatter:"textarea",headerSort:false,width:300,minWidth :100,align:"center",editor:"textarea"
                            },
                        ],
                        
            });
            $("#tabella_prospetto").tabulator("setLocale", "it-it");
            $.ajax({
                                    type: "POST",
                                    url: "server url",
                                        data:{data to server},
                                    dataType: "JSON",
                                    success: function (result) {
                                        $("#tabella_prospetto").tabulator("setData", result);
                                        
                                    },
                                    error: function (jqXHR, textStatus, errorThrown) {
                                        console.log('jqXHR:');
                                        console.log(jqXHR);
                                        console.log('textStatus:');
                                        console.log(textStatus);
                                        console.log('errorThrown:');
                                        console.log(errorThrown);
                                    }
                                });`

**Comment by olifolkerd** [comment]
Hey @dasio86 

This is happening because it is taking a while for the images to load so the table is rendering before they know their height.

A solution to this has been posted in issue #603

Cheers

Oli
