### ISSUE TITLE
Problem with persistentLayout

### ISSUE THREAD

**Issue by mikeshow** [olifolkerd/tabulator#636]
Hi Oli,

I have added this to my tabulator (3.3.1):

```javascript
         persistentLayout: true,
         persistentLayoutID: "quoteManage",
```
It's very nice.

The problem comes when, for instance, I change the order of the columns in my definition. Because it is saved in the local storage, the new order doesn't appear. It is worse if I remove a column. Ctrl+F5 doesn't do the trick.

One has to go in the devtools->application->clear storage. 

I'm not sure if my users/clients will understand that.

So if you don' find a solution I think I'll remove the option.

Cheers.

**Comment by olifolkerd** [comment]
Hey @mikeshow,

If you change the setup of the columns you need to change the ***persistentLayoutID*** to ensure the changes are correctly picked up.

I usually increment a number on the end of the id every time i change my column layouts:
```js
persistentLayoutID: "quoteManage2",
```

Cheers

Oli
