### ISSUE TITLE
Minor JS error on demo page

### ISSUE THREAD

**Issue by mathieu-veron** [olifolkerd/tabulator#638]
On the "Filter" example, on the demo page 
http://tabulator.info/examples/3.3#filter

Options Error - Tabulator does not allow options to be set after initialization unless there is a function defined for that purpose
&nbsp;anonymous function).(anonymous function)._setOption (/js/tabulator/3.3/tabulator.min.js:3)

**Comment by olifolkerd** [comment]
Hey @mathieu-veron 

Thanks for the heads up, there was an issue in one of the page templates, this should now be fixed.

Cheers

Oli
