### ISSUE TITLE
Improving the scrollToRow if row not visible.

### ISSUE THREAD

**Issue by mikeshow** [olifolkerd/tabulator#639]
Hi Oli,

Are you planning on improving $("#example-table").tabulator("scrollToRow", 23); because currently if the row is not visible we get the "Scroll Error - Row not visible" warning.

Cheers.

Mike.

**Comment by olifolkerd** [comment]
Hi @mikeshow 

That is the intended behaviour, the table cannot scroll to a row that isnt there. i can make it so the function returns true or false based on weather or not it can scroll to that row.

What behaviour would you be looking for?

Cheers

Oli

**Comment by mikeshow** [comment]
Hi Oli,

Unless I am mistaken, if I write this:

```javascript
               tabulHeight = getHeight4Tabulator();
               var tbltr = $("#thetable");
               tbltr.tabulator(
                  "setData",
                  mcdmcdash.ajaxurl,
                  {
                     action: 'tabulator_categories_server_side',
                     categ_nonce: mcdmcdash.categ_nonce,
                     do_what: 'list'
                  },
                  "POST"
               );

               tbltr.tabulator("scrollToRow", 23);
```
and elswhere I have this in the description:

```javascript
      tbltr.tabulator({
         layout: 'fitData',
         sortable: false,
         virtualDom: true,
         height: tabulHeight,
...
```
the ajax call returns all the rows.

Even if the line with the id 23 is not visible it is present. I can see it if I scroll down and I see that no further ajax call is made. So I would like tabulator to do the scroll for me.

Now maybe I am not using the function correctly because "The first argument should be any of the standard row component looukup options for the row you want to scroll to." is not very clear to me as to how to use that function.

Cheers.

**Comment by olifolkerd** [comment]
If the row is in the data it should be possible to scroll to it.

Could you post a copy of the data object for row 23 so i can see what is going on? 

If the 23 is stored in a parameter other than ***id*** you will need to set the ***index*** option of the table to point to that parameter instead.

Cheers

Oli

**Comment by mikeshow** [comment]
Hi Oli,

23 is just an example. At the beginning I thought the parameter was the line number.

So my code is like this, I have a global variable defined:

```javascript
   var rowIdToScroll = 0;
```

The structure of the array is like this:

```javascript
$sp_data[] = array(
	'id'            => $category->id,
	'categ_groupby' => $categ_groupby,
	'categ_name'    => $category_name,
	'categ_parent'  => $category->parent,
	'item_name'     => $item_name,
);
```

In the rowClick of tabulator, for instance, I have this:

```javascript
 rowClick: function (e, row) {
	var id = row.getIndex();
	var categparent = row.getData().categ_parent;
	// check if not clicked the bottom calc
	if (id !== undefined)
	{
	   rowIdToScroll = id; // set the global variable
	   console.log('rowclick: '+ id);
	   $.ajax({
		  type: 'POST',
		  url: mcdmcdash.ajaxurl,
		  data: {
			 action: 'view_request_category_server_side',
			 categ_nonce: mcdmcdash.categ_nonce,
			 do_what: 'request',
			 dmc_id: id
		  },
		  success: function (response) {
			 if (response.success)
			 {
				if (categparent === "0")
				{
				   showView('tabvw_updt_categ', id, response.data.content);
				} else
				{
				   showView('tabvw_updt_item', id, response.data.content);
				}
				return false;
			 } else
			 {
                             ...
			 }
		  },
		  error: function (error_msg) {
                     ...
	   });
	}
	return false;
 },
```

When I come back, in showView() I have this:

```javascript
	tabulHeight = getHeight4Tabulator();
	var tbltr = $("#thetable");
	tbltr.tabulator(
	  "setData",
	  mcdmcdash.ajaxurl,
	  {
		 action: 'tabulator_categories_server_side',
		 categ_nonce: mcdmcdash.categ_nonce,
		 do_what: 'list'
	  },
	  "POST"
	);

	if (rowIdToScroll > 1)
	{
	  console.log('showview: ' + rowIdToScroll);
	  tbltr.tabulator("scrollToRow", rowIdToScroll);
	}
```

The console.log show the same id, there is a unique id for each line, there is no warning but there is no scroll.

Cheers.

Mike.

**Comment by olifolkerd** [comment]
Looking at your code, i think the the ***scrollToRow*** function is being called too soon.

You are calling it as soon as you make the ajax request, but with ajax being asynchronous, the scrollToRow function is being called before the request is returned.

You should use the ***renderComplete*** callback in the table constructor to trigger the ***scrollToRow*** function:
```js
$("#example-table").tabulator({
    columns:[...],
    renderComplete:function(){
        if (rowIdToScroll > 1)
	{
	  console.log('showview: ' + rowIdToScroll);
	  tbltr.tabulator("scrollToRow", rowIdToScroll);
	}
    },
});
```
Let me know if that helps

Cheers

Oli

**Comment by mikeshow** [comment]
Hi Oli,

It helped a lot. Now it works. Thanks.

By the way Oli, you see I use the virtual dom now. You asked me a few days ago why I wasn't using it. I thought about it again and asked me "yeah, why am I not?". So now I'm using the virtual dom, the ajax call, and the rest of it. I'm starting to use tabulator more in depth and I like it. It's a very good piece of software that you are developing. Indeed, it comes with questions and remarks that I will not fail to ask.

**Comment by olifolkerd** [comment]
Great news,

It is great to hear you enjoying using Tabulator! please feel free to ask as many questions as you like!

Cheers

Oli
