### ISSUE TITLE
Extending Tabulator: Needs "mutators"

### ISSUE THREAD

**Issue by hohozhao** [olifolkerd/tabulator#64]
@olifolkerd ,

Now can not extend mutators like this:

```
$.widget("ui.tabulator", $.ui.tabulator, {
    mutators:{
        datetime:function(value){
            return formatDate(Date(value));
        },
    },
}
```

Thanks,

**Comment by olifolkerd** [comment]
Great idea!

i will get that in tommorow!

**Comment by olifolkerd** [comment]
Mutator and Accessor extensions are now available.

Have a look at the [Extension Documentation](http://olifolkerd.github.io/tabulator/docs/#extending) for more info.
