### ISSUE TITLE
editor: "number" no longer works

### ISSUE THREAD

**Issue by mythsmith** [olifolkerd/tabulator#642]
The following example is from the quickstart. If you specify "number" as age column editor, it will no longer be possible to modify it. I would expect a spinbox editor.
Omitting it will allow the standard progress editor, or setting to "input" will show the textbox. 
I have other examples where it's clear it does not depend on the formatter, either. 

```
<html>
<head>

<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script type="text/javascript" src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.3.1/css/tabulator.min.css" rel="stylesheet">
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.3.1/js/tabulator.min.js"></script>

</head>
<body>
<div id="example-table"></div>

<script type="text/javascript">
//create Tabulator on DOM element with id "example-table"
$("#example-table").tabulator({
    height:205, // set height of table, this enables the Virtual DOM and improves render speed dramatically (can be any valid css height value)
    fitColumns:true, //fit columns to width of table (optional)
    columns:[ //Define Table Columns
        {title:"Name", field:"name", width:150},
        {title:"Age", field:"age", align:"left", formatter:"progress", editor: "number"},
        {title:"Favourite Color", field:"col"},
        {title:"Date Of Birth", field:"dob", sorter:"date", align:"center"},
    ],
});
//define some sample data
var tabledata = [
    {id:1, name:"Oli Bob", age:"12", col:"red", dob:""},
    {id:2, name:"Mary May", age:"1", col:"blue", dob:"14/05/1982"},
    {id:3, name:"Christine Lobowski", age:"42", col:"green", dob:"22/05/1982"},
    {id:4, name:"Brendon Philips", age:"125", col:"orange", dob:"01/08/1980"},
    {id:5, name:"Margret Marmajuke", age:"16", col:"yellow", dob:"31/01/1999"},
];

//load sample data into the table
$("#example-table").tabulator("setData", tabledata);
</script>


</body>
</html>
```

**Comment by olifolkerd** [comment]
Hey @mythsmith 

I dont seem to be able to replicate your issues, i get a standard number type input element.

which version of tabulator are you using?

which browser are you using?

**Comment by mythsmith** [comment]
Hi @olifolkerd 
The version of tabulator is linked in the cdn: https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.3.1/css/tabulator.min.css.
I was using Firefox 56.0/64bit under ubuntu 16.04. 
I tried with Chromium (same OS), _and it works_. 
I tried restarting firefox in safe mode (no extension) but this had no effect. Still I cannot get the number editor under firefox.

**Comment by olifolkerd** [comment]
ahh so this may be an issue with firefox, thanks for the information, i will investigate futher

**Comment by olifolkerd** [comment]
i have just pushed a fix for this to the master branch, it should be included in this evenings patch update.

Cheers

Oli

**Comment by mythsmith** [comment]
It works! 
Thanks,
Daniele

**Comment by themantalope** [comment]
Hi Oli,

I'm having the same issue on firefox. Here are the versions of Tabulator, jQuery and Firefox I'm using:

```html
  <link href="https://unpkg.com/tabulator-tables@4.2.4/dist/css/tabulator.min.css" rel="stylesheet">
  <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
  <script type="text/javascript" src="https://unpkg.com/tabulator-tables@4.2.4/dist/js/tabulator.min.js"></script>
```

Firefox (mac OSX):

```bash
Firefox Quantum 66.0.2 (64-bit)
```

Let me know if there are any tricks to get this to play nice with firefox.

**Comment by olifolkerd** [comment]
Hey @mythsmith 

Sorry to hear you are having trouble

This issue was closed over 2 years ago, the source for Tabulator has been rewritten twice since then so it is very unlikely to be related.

Please do not post on posts this old, i will only confuse other developers.

If you are having issues please create a new issue and follow the guidelines on the [Communities  Page](http://tabulator.info/community) it is impossible to provide specific advice unless we can see how your table is setup, with ideally a woking JS Fiddle or Code Pen, or at the very least a copy of your table constructor.

Cheers

Oli :)

**Comment by themantalope** [comment]
@olifolkerd 

Thank you! No problem, I'll update as needed.

-themantalope
