### ISSUE TITLE
jQuery upgrade issue - (offtopic)

### ISSUE THREAD

**Issue by shayo** [olifolkerd/tabulator#643]
I was using an old version of tabulator and wanted to upgrade to version 3.3
However, that requires upgrading jQuery as well.
I tried switching to 3.2.1, but as soon as I did that, I encountered a problem where click events are no longer firing.
I basically had something very simple like this:

```
$(document).on('click', '#toggle_nav_btn', function (e) {

		return false;
	});

```

and it no longer works.

Do you have an idea how to fix this?

**Comment by olifolkerd** [comment]
The function in your example wont do anything, what are you trying to achieve with it?

**Comment by shayo** [comment]
Thank you for the quick reply.
Oh I removed the inside, just to make the point.
The original code was this:
```

$(document).on('click', '#toggle_nav_btn,#open_right_sidebar,#setting_panel_btn', function (e) {
		$(".dropdown.open > .dropdown-toggle").dropdown("toggle");
		return false;
	});
	$(document).on('click', '#toggle_nav_btn', function (e) {
		$wrapper.removeClass('open-right-sidebar open-setting-panel').toggleClass('slide-nav-toggle');
		return false;
	});
```

Doesn't really matter. If I put a breakpoint inside the function, execution never stops there when I use jQuery 3.2.1.
It works well when I use 2.1.4

**Comment by olifolkerd** [comment]
There is no reason that should stop working as ling as the elements still have the correct id's and classes, and exist.

Have you tried adding a console log to the click binding to check if it fires

**Comment by shayo** [comment]
> Have you tried adding a console log to the click binding to check if it fires

How do you do such binding?

**Comment by shayo** [comment]
Another question: 
Is there a tabulator query I can do to get all the rows that have been selected, or do I need to have a global variable and update it on every rowClick event?

**Comment by olifolkerd** [comment]
Hey,

you can add the console.log command like so:
```js
$(document).on('click', '#toggle_nav_btn,#open_right_sidebar,#setting_panel_btn', function (e) {
	console.log("click has worked");
	$(".dropdown.open > .dropdown-toggle").dropdown("toggle");
	return false;
});
```

You can use the ***getSelectedRows*** function:
```js
var selectedRows = $("#example-table").tabulator("getSelectedRows");
```

There are also ***rowSelected*** and ***rowDeselected*** callbacks that are called when the row selection changes.

Cheers

Oli
