### ISSUE TITLE
getData only works for data that was inserted with setData and not with addRow ?

### ISSUE THREAD

**Issue by shayo** [olifolkerd/tabulator#646]
Unexpected behavior: 
I have an empty table. I add rows one by one. Then query ("GetData") and I get empty array.

**Comment by olifolkerd** [comment]
***getData*** should be working with all rows, could you post a copy of your table constructor, and an example of your ***adddRow*** and ***getData*** function.

Cheers

Oli

**Comment by shayo** [comment]
see https://github.com/olifolkerd/tabulator/issues/644
I was trying
`
tabledata= $("#grouped_table").tabulator("getData");`

**Comment by olifolkerd** [comment]
in #664 Your ***buildentry*** entry isnt returning anything.

You need to add `return table_entry;` at the end of the function

Cheers

Oli
