### ISSUE TITLE
setfilter or addfilter triggers reload of data/page and filters do not apply

### ISSUE THREAD

**Issue by mariokitz** [olifolkerd/tabulator#648]
Hi! 

let me start with a big THANK YOU for your great work! 

I am trying to filter a table using the setfilter/addfilter functions when the user hits a button. Shortly after the button is pressed the filtered table shows briefly only ID 114 but immedialty after that the complete data of the table seems to reload and the filter is gone again.

Attached my complete code (sorry its a little long).

Thanks a lot 
Mario
`</style>
<div class="table-controls">
  <button id="download-csv">Tabelle als CSV Datei herunterladen</button>
  <button id="rzBerlinFilter">Nur RZ Berlin Einträge</button>
  <button id="rzBonnFilter">Nur RZ Bonn Einträge</button>
  <button id="rzFrankfurtFilter">Nur RZ Frankfurt Einträge</button>
  <button id="rzKoelnFilter">Nur RZ Köln Einträge</button>
  <button id="rzIlemnauFilter">Nur RZ Ilmenau Einträge</button>
  <button id="rzWiesbadenFilter">Nur RZ Wiesbaden Einträge</button>
</div>
</p>
<div id="tblZutritte"></div>
<script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<link href="https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.3.0/css/semantic-ui/tabulator_semantic-ui.min.css" rel="stylesheet">
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.3.0/js/tabulator.min.js"></script>

<script>

//Globale Variablen
var adAccountAktuellerBenutzer="";

//Main
ExecuteOrDelayUntilScriptLoaded(adAccountErmitteln,'sp.js');

function adAccountErmitteln()
{
	var ctxt = new SP.ClientContext.get_current();
	this.website = ctxt.get_web();
	this.currentUser = website.get_currentUser();
	ctxt.load(currentUser);
	ctxt.executeQueryAsync(Function.createDelegate(this, this.onSucceess), Function.createDelegate(this, this.onFail));
}

function onFail(sender, args)
{
alert('request failed ' + args.get_message() + '\n'+ args.get_stackTrace());
}

function onSucceess(sender, args)
 {
	adAccountAktuellerBenutzer = currentUser.get_loginName().slice(currentUser.get_loginName(). indexOf("\\") + 1);
	tabelleErstellen();
}

function tabelleErstellen()
{

	$("#tblZutritte").tabulator({
    height:900, // set height of table, this enables the Virtual DOM and improves render speed dramatically (can be any valid css height value)
    layout:'fitColumns',
	movableColumns:true,
	initialSort:[{column:"asName", dir:"asc"}],
	langs:{
        "de-de":{ //German language definition
            "pagination":{
                "first":"<<",
                "first_title":"erste Seite",
                "last":">>",
                "last_title":"letzte Seite",
                "prev":"<",
                "prev_title":"zurück",
                "next":">",
                "next_title":"vor",
            },
        },
    },
    columns:[ //Define Table Columns
		{title:"GS", field:"frmGenehmigungsstufe", width:100, formatter:"star", formatterParams:{stars:3}, mutator:function(value, data, type, mutatorParams, cell)
			{
			var neuerWert = 0;
			
			switch (value)
			{
				case "keine":
					neuerWert = 0;
					break;
				case "Genehmigt durch RL":
					neuerWert = 1;
					break;
				case "SÜ2-G positiv":
					neuerWert = 2;
					break;
				case "Genehmigt durch IV B 2":
					neuerWert = 3;
					break;
			};
					
			return neuerWert;
			}
		},
        {title:"ID", field:"ID", width:100},
        {title:"Link", field:"LinkZumAntrag", width:150, formatter:"html"},
        {title:"Vorname", field:"asVorname", headerFilter:"input", headerFilterPlaceholder:"<Suchtext>"},
        {title:"Name", field:"asName",headerFilter:"input", headerFilterPlaceholder:"<Suchtext>"},
        {title:"Email-Adresse", field:"asEmail",formatter:"email", headerFilter:"input", headerFilterPlaceholder:"<Suchtext>"},
        {title:"Stellenzeichen", field:"asStellenzeichen",headerFilter:"input", headerFilterPlaceholder:"<Suchtext>"},
        {title:"ITZBund Rechenzentren/-Räume", field:"tmpAuswahl", headerFilter:true, align:"left"},
		{title:"Antragstyp", field:"frmAntragstyp", align:"left",visible:false},
		{title:"Zutritt ab", field:"ZutrittAb", align:"left"},
		{title:"Zutritt bis", field:"ZutrittBis", align:"left"},
		{title:"Antragsstatus", field:"frmAntragsstatus", headerFilter:true, align:"left"},
		{title:"Genehmigungsstufe", field:"Genehmigungsstufe", headerFilter:true, align:"left"},
		{title:"Workflowhistorie", field:"LinkZurWorkflowHistorie",formatter:"html", align:"left"}
	],
	groupBy:"frmAntragstyp",
	ajaxResponse:function(url, params, response){
        
		//url - the URL of the request
        //params - the parameters passed with the request
        //response - the JSON object returned in the body of the response.
		var tableData = [];
		
		$.each(response.d.results,function(i,eintrag){
		eintrag["Genehmigungsstufe"] = eintrag.frmGenehmigungsstufe;
		eintrag["LinkZumAntrag"] = "<a href='https://sp.vzd.zivb.net/sites/08F6/Portal_Zutrittsberechtigungen/Lists/Zutrittsberechtigungen/Item/displayifs.aspx?ID=" + eintrag.ID + "'>Antrag öffnen</a>";
		eintrag["LinkZurWorkflowHistorie"] = "<a href='https://sp.vzd.zivb.net/sites/08F6/Portal_Zutrittsberechtigungen/Lists/ZutrittsverwaltungWorkflowHistorie/AllItems.aspx#InplviewHash857e3c77-8543-4083-96a5-b15024111c90=FilterField1%3DItem-FilterValue1%3D" + eintrag.ID + "'>Workflowhistorie öffnen</a>";
		eintrag["ZutrittAb"] = eintrag.ZutrittAb.slice(8,10) + "." + eintrag.ZutrittAb.slice(5,7) + "." + eintrag.ZutrittAb.slice(0,4);
		eintrag["ZutrittBis"] = eintrag.ZutrittBis.slice(8,10) + "." + eintrag.ZutrittBis.slice(5,7) + "." + eintrag.ZutrittBis.slice(0,4);

		
		switch (eintrag.frmAntragsstatus)
		{
			case "genehmigt":
				eintrag["LinkZumAntrag"] = "<a href='https://sp.vzd.zivb.net/sites/08F6/Portal_Zutrittsberechtigungen/SitePages/Zutritt%20erweitern%20oder%20%C3%A4ndern.aspx?View=%7BA06BD530%2D257B%2D4185%2DA051%2DB8941B792BCE%7D&SelectedID=" + eintrag.ID + "'>Antrag öffnen</a>";
				break;
			case "zwischengespeichert":
				eintrag["LinkZumAntrag"] = "<a href='https://sp.vzd.zivb.net/sites/08F6/Portal_Zutrittsberechtigungen/SitePages/Zutrittsberechtigungen%20fertigstellen%20oder%20stornieren.aspx?View=%7B68D715FA%2D814E%2D49FE%2D9DEE%2DA832D09972AE%7D&SelectedID=" + eintrag.ID + "'>Antrag öffnen</a>";
				break;
				
			default:
				eintrag["LinkZumAntrag"] = "<a href='https://sp.vzd.zivb.net/sites/08F6/Portal_Zutrittsberechtigungen/SitePages/Zutrittsgenehmigungsantrag.aspx?View=%7B7738D770%2DAD3B%2D4198%2D91C3%2DB1E13DE12B18%7D&SelectedID=" + eintrag.ID + "'>Antrag öffnen</a>";
						
		}
				
		if (eintrag.asADAccount==="keiner") {eintrag.frmAntragstyp="Anträge für Mitarbeitende ohne SharePoint Zugriff"};
		if (eintrag.rlADAccount==="keiner") {eintrag.frmAntragstyp="Anträge für Mitarbeitende mit SharePoint Zugriff"};
		if (eintrag.rlADAccount!=="keiner" && eintrag.asADAccount!=="keiner") {eintrag.frmAntragstyp="Fehlerhaft, bitte prüfen"};
		
		});
       
		return response.d.results; //return the tableData peroperty of a response json object
    },
	});

	var queryString

	queryString = _spPageContextInfo.webAbsoluteUrl + "/_api/Web/Lists/GetByTitle('Zutrittsberechtigungen')/items?$select=ID,Title,asADAccount,rlADAccount,asVorname,asName,asEmail,asStellenzeichen,ZutrittAb,ZutrittBis,frmAntragsstatus,frmGenehmigungsstufe,tmpAuswahl&$top=5000";

	var ajaxConfig = {
		url: queryString,
		type: "GET",
		dataType: "json",
		headers: {
		Accept: "application/json;odata=verbose"
	}}

	$("#tblZutritte").tabulator("setData",queryString, {},ajaxConfig);
	$("#tblZutritte").tabulator("setLocale", "de-de");
	$("#download-csv").click(function(){
		$("#tblZutritte").tabulator("download", "csv", "data.csv");
	});
	
	$("#rzBerlinFilter").click(function(){
		debugger;
		$("#tblZutritte").tabulator("addFilter", "ID", "=", 114);
	});

	
	
	}

</script>

`

**Comment by olifolkerd** [comment]
Hey @mariokitz,

Thanks for getting in touch.

Could you format  and indent the code in your question, i cannot read it in that minified format.

Cheers

Oli

**Comment by mariokitz** [comment]
`<style>

.table-controls {
    margin-bottom: 10px;
    padding: 10px 5px 10px 5px;
    background: #eee;
    font-size: 14px;
}

</style>

<div class="table-controls">
  <button id="download-csv">Tabelle als CSV Datei herunterladen</button>
  <button id="rzBerlinFilter">Nur RZ Berlin Einträge</button>
  <button id="rzBonnFilter">Nur RZ Bonn Einträge</button>
  <button id="rzFrankfurtFilter">Nur RZ Frankfurt Einträge</button>
  <button id="rzKoelnFilter">Nur RZ Köln Einträge</button>
  <button id="rzIlemnauFilter">Nur RZ Ilmenau Einträge</button>
  <button id="rzWiesbadenFilter">Nur RZ Wiesbaden Einträge</button>
</div>

</p>
<div id="tblZutritte"></div>

<script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<link href="https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.3.0/css/semantic-ui/tabulator_semantic-ui.min.css" rel="stylesheet">
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.3.1/js/tabulator.min.js"></script>

<script>

//Globale Variablen
var adAccountAktuellerBenutzer="";

//Main
ExecuteOrDelayUntilScriptLoaded(adAccountErmitteln,'sp.js');


function adAccountErmitteln()
{
	var ctxt = new SP.ClientContext.get_current();
	this.website = ctxt.get_web();
	this.currentUser = website.get_currentUser();
	ctxt.load(currentUser);
	ctxt.executeQueryAsync(Function.createDelegate(this, this.onSucceess), Function.createDelegate(this, this.onFail));
}

function onFail(sender, args)
{
alert('request failed ' + args.get_message() + '\n'+ args.get_stackTrace());
}

function onSucceess(sender, args)
 {
	adAccountAktuellerBenutzer = currentUser.get_loginName().slice(currentUser.get_loginName(). indexOf("\\") + 1);
	tabelleErstellen();
}


function tabelleErstellen()
{

	$("#tblZutritte").tabulator({
    height:900, // set height of table, this enables the Virtual DOM and improves render speed dramatically (can be any valid css height value)
    layout:'fitColumns',
	movableColumns:true,
	initialSort:[{column:"asName", dir:"asc"}],
	langs:{
        "de-de":{ //German language definition
            "pagination":{
                "first":"<<",
                "first_title":"erste Seite",
                "last":">>",
                "last_title":"letzte Seite",
                "prev":"<",
                "prev_title":"zurück",
                "next":">",
                "next_title":"vor",
            },
        },
    },
    columns:[ //Define Table Columns
		{title:"GS", field:"frmGenehmigungsstufe", width:100, formatter:"star", formatterParams:{stars:3}, mutator:function(value, data, type, mutatorParams, cell)
			{
			var neuerWert = 0;
			
			switch (value)
			{
				case "keine":
					neuerWert = 0;
					break;
				case "Genehmigt durch RL":
					neuerWert = 1;
					break;
				case "SÜ2-G positiv":
					neuerWert = 2;
					break;
				case "Genehmigt durch IV B 2":
					neuerWert = 3;
					break;
			};
					
			return neuerWert;
			}
		},
        {title:"ID", field:"ID", width:100},
        {title:"Link", field:"LinkZumAntrag", width:150, formatter:"html"},
        {title:"Vorname", field:"asVorname", headerFilter:"input", headerFilterPlaceholder:"<Suchtext>"},
        {title:"Name", field:"asName",headerFilter:"input", headerFilterPlaceholder:"<Suchtext>"},
        {title:"Email-Adresse", field:"asEmail",formatter:"email", headerFilter:"input", headerFilterPlaceholder:"<Suchtext>"},
        {title:"Stellenzeichen", field:"asStellenzeichen",headerFilter:"input", headerFilterPlaceholder:"<Suchtext>"},
        {title:"ITZBund Rechenzentren/-Räume", field:"tmpAuswahl", headerFilter:true, align:"left"},
		{title:"Antragstyp", field:"frmAntragstyp", align:"left",visible:false},
		{title:"Zutritt ab", field:"ZutrittAb", align:"left"},
		{title:"Zutritt bis", field:"ZutrittBis", align:"left"},
		{title:"Antragsstatus", field:"frmAntragsstatus", headerFilter:true, align:"left"},
		{title:"Genehmigungsstufe", field:"Genehmigungsstufe", headerFilter:true, align:"left"},
		{title:"Workflowhistorie", field:"LinkZurWorkflowHistorie",formatter:"html", align:"left"}
	],
	groupBy:"frmAntragstyp",
	ajaxResponse:function(url, params, response){
        
		//url - the URL of the request
        //params - the parameters passed with the request
        //response - the JSON object returned in the body of the response.
		var tableData = [];
		
		$.each(response.d.results,function(i,eintrag){
		eintrag["Genehmigungsstufe"] = eintrag.frmGenehmigungsstufe;
		eintrag["LinkZumAntrag"] = "<a href='https://sp.vzd.zivb.net/sites/08F6/Portal_Zutrittsberechtigungen/Lists/Zutrittsberechtigungen/Item/displayifs.aspx?ID=" + eintrag.ID + "'>Antrag öffnen</a>";
		eintrag["LinkZurWorkflowHistorie"] = "<a href='https://sp.vzd.zivb.net/sites/08F6/Portal_Zutrittsberechtigungen/Lists/ZutrittsverwaltungWorkflowHistorie/AllItems.aspx#InplviewHash857e3c77-8543-4083-96a5-b15024111c90=FilterField1%3DItem-FilterValue1%3D" + eintrag.ID + "'>Workflowhistorie öffnen</a>";
		eintrag["ZutrittAb"] = eintrag.ZutrittAb.slice(8,10) + "." + eintrag.ZutrittAb.slice(5,7) + "." + eintrag.ZutrittAb.slice(0,4);
		eintrag["ZutrittBis"] = eintrag.ZutrittBis.slice(8,10) + "." + eintrag.ZutrittBis.slice(5,7) + "." + eintrag.ZutrittBis.slice(0,4);

		
		switch (eintrag.frmAntragsstatus)
		{
			case "genehmigt":
				eintrag["LinkZumAntrag"] = "<a href='https://sp.vzd.zivb.net/sites/08F6/Portal_Zutrittsberechtigungen/SitePages/Zutritt%20erweitern%20oder%20%C3%A4ndern.aspx?View=%7BA06BD530%2D257B%2D4185%2DA051%2DB8941B792BCE%7D&SelectedID=" + eintrag.ID + "'>Antrag öffnen</a>";
				break;
			case "zwischengespeichert":
				eintrag["LinkZumAntrag"] = "<a href='https://sp.vzd.zivb.net/sites/08F6/Portal_Zutrittsberechtigungen/SitePages/Zutrittsberechtigungen%20fertigstellen%20oder%20stornieren.aspx?View=%7B68D715FA%2D814E%2D49FE%2D9DEE%2DA832D09972AE%7D&SelectedID=" + eintrag.ID + "'>Antrag öffnen</a>";
				break;
				
			default:
				eintrag["LinkZumAntrag"] = "<a href='https://sp.vzd.zivb.net/sites/08F6/Portal_Zutrittsberechtigungen/SitePages/Zutrittsgenehmigungsantrag.aspx?View=%7B7738D770%2DAD3B%2D4198%2D91C3%2DB1E13DE12B18%7D&SelectedID=" + eintrag.ID + "'>Antrag öffnen</a>";
						
		}
				
		if (eintrag.asADAccount==="keiner") {eintrag.frmAntragstyp="Anträge für Mitarbeitende ohne SharePoint Zugriff"};
		if (eintrag.rlADAccount==="keiner") {eintrag.frmAntragstyp="Anträge für Mitarbeitende mit SharePoint Zugriff"};
		if (eintrag.rlADAccount!=="keiner" && eintrag.asADAccount!=="keiner") {eintrag.frmAntragstyp="Fehlerhaft, bitte prüfen"};
		
		});
       
		return response.d.results; //return the tableData peroperty of a response json object
    },
	});

	var queryString

	queryString = _spPageContextInfo.webAbsoluteUrl + "/_api/Web/Lists/GetByTitle('Zutrittsberechtigungen')/items?$select=ID,Title,asADAccount,rlADAccount,asVorname,asName,asEmail,asStellenzeichen,ZutrittAb,ZutrittBis,frmAntragsstatus,frmGenehmigungsstufe,tmpAuswahl&$top=5000";

	var ajaxConfig = {
		url: queryString,
		type: "GET",
		dataType: "json",
		headers: {
		Accept: "application/json;odata=verbose"
	}}


	$("#tblZutritte").tabulator("setData",queryString, {},ajaxConfig);
	$("#tblZutritte").tabulator("setLocale", "de-de");
	$("#download-csv").click(function(){
		$("#tblZutritte").tabulator("download", "csv", "data.csv");
	});
	
	$("#rzBerlinFilter").click(function(){
		debugger;
		$("#tblZutritte").tabulator("addFilter", "ID", "=", 114);
	});

	
	
	}

</script>



`

**Comment by mariokitz** [comment]
`<style>

.table-controls {
    margin-bottom: 10px;
    padding: 10px 5px 10px 5px;
    background: #eee;
    font-size: 14px;
}

</style>

<div class="table-controls">
  <button id="download-csv">Tabelle als CSV Datei herunterladen</button>
  <button id="rzBerlinFilter">Nur RZ Berlin Einträge</button>
  <button id="rzBonnFilter">Nur RZ Bonn Einträge</button>
  <button id="rzFrankfurtFilter">Nur RZ Frankfurt Einträge</button>
  <button id="rzKoelnFilter">Nur RZ Köln Einträge</button>
  <button id="rzIlemnauFilter">Nur RZ Ilmenau Einträge</button>
  <button id="rzWiesbadenFilter">Nur RZ Wiesbaden Einträge</button>
</div>

</p>
<div id="tblZutritte"></div>

<script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<link href="https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.3.0/css/semantic-ui/tabulator_semantic-ui.min.css" rel="stylesheet">
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.3.1/js/tabulator.min.js"></script>

<script>

//Globale Variablen
var adAccountAktuellerBenutzer="";

//Main
ExecuteOrDelayUntilScriptLoaded(adAccountErmitteln,'sp.js');


function adAccountErmitteln()
{
	var ctxt = new SP.ClientContext.get_current();
	this.website = ctxt.get_web();
	this.currentUser = website.get_currentUser();
	ctxt.load(currentUser);
	ctxt.executeQueryAsync(Function.createDelegate(this, this.onSucceess), Function.createDelegate(this, this.onFail));
}

function onFail(sender, args)
{
alert('request failed ' + args.get_message() + '\n'+ args.get_stackTrace());
}

function onSucceess(sender, args)
 {
	adAccountAktuellerBenutzer = currentUser.get_loginName().slice(currentUser.get_loginName(). indexOf("\\") + 1);
	tabelleErstellen();
}


function tabelleErstellen()
{

	$("#tblZutritte").tabulator({
    height:900, // set height of table, this enables the Virtual DOM and improves render speed dramatically (can be any valid css height value)
    layout:'fitColumns',
	movableColumns:true,
	initialSort:[{column:"asName", dir:"asc"}],
	langs:{
        "de-de":{ //German language definition
            "pagination":{
                "first":"<<",
                "first_title":"erste Seite",
                "last":">>",
                "last_title":"letzte Seite",
                "prev":"<",
                "prev_title":"zurück",
                "next":">",
                "next_title":"vor",
            },
        },
    },
    columns:[ //Define Table Columns
		{title:"GS", field:"frmGenehmigungsstufe", width:100, formatter:"star", formatterParams:{stars:3}, mutator:function(value, data, type, mutatorParams, cell)
			{
			var neuerWert = 0;
			
			switch (value)
			{
				case "keine":
					neuerWert = 0;
					break;
				case "Genehmigt durch RL":
					neuerWert = 1;
					break;
				case "SÜ2-G positiv":
					neuerWert = 2;
					break;
				case "Genehmigt durch IV B 2":
					neuerWert = 3;
					break;
			};
					
			return neuerWert;
			}
		},
        {title:"ID", field:"ID", width:100},
        {title:"Link", field:"LinkZumAntrag", width:150, formatter:"html"},
        {title:"Vorname", field:"asVorname", headerFilter:"input", headerFilterPlaceholder:"<Suchtext>"},
        {title:"Name", field:"asName",headerFilter:"input", headerFilterPlaceholder:"<Suchtext>"},
        {title:"Email-Adresse", field:"asEmail",formatter:"email", headerFilter:"input", headerFilterPlaceholder:"<Suchtext>"},
        {title:"Stellenzeichen", field:"asStellenzeichen",headerFilter:"input", headerFilterPlaceholder:"<Suchtext>"},
        {title:"ITZBund Rechenzentren/-Räume", field:"tmpAuswahl", headerFilter:true, align:"left"},
		{title:"Antragstyp", field:"frmAntragstyp", align:"left",visible:false},
		{title:"Zutritt ab", field:"ZutrittAb", align:"left"},
		{title:"Zutritt bis", field:"ZutrittBis", align:"left"},
		{title:"Antragsstatus", field:"frmAntragsstatus", headerFilter:true, align:"left"},
		{title:"Genehmigungsstufe", field:"Genehmigungsstufe", headerFilter:true, align:"left"},
		{title:"Workflowhistorie", field:"LinkZurWorkflowHistorie",formatter:"html", align:"left"}
	],
	groupBy:"frmAntragstyp",
	ajaxResponse:function(url, params, response){
        
		//url - the URL of the request
        //params - the parameters passed with the request
        //response - the JSON object returned in the body of the response.
		var tableData = [];
		
		$.each(response.d.results,function(i,eintrag){
		eintrag["Genehmigungsstufe"] = eintrag.frmGenehmigungsstufe;
		eintrag["LinkZumAntrag"] = "<a href='https://sp.vzd.zivb.net/sites/08F6/Portal_Zutrittsberechtigungen/Lists/Zutrittsberechtigungen/Item/displayifs.aspx?ID=" + eintrag.ID + "'>Antrag öffnen</a>";
		eintrag["LinkZurWorkflowHistorie"] = "<a href='https://sp.vzd.zivb.net/sites/08F6/Portal_Zutrittsberechtigungen/Lists/ZutrittsverwaltungWorkflowHistorie/AllItems.aspx#InplviewHash857e3c77-8543-4083-96a5-b15024111c90=FilterField1%3DItem-FilterValue1%3D" + eintrag.ID + "'>Workflowhistorie öffnen</a>";
		eintrag["ZutrittAb"] = eintrag.ZutrittAb.slice(8,10) + "." + eintrag.ZutrittAb.slice(5,7) + "." + eintrag.ZutrittAb.slice(0,4);
		eintrag["ZutrittBis"] = eintrag.ZutrittBis.slice(8,10) + "." + eintrag.ZutrittBis.slice(5,7) + "." + eintrag.ZutrittBis.slice(0,4);

		
		switch (eintrag.frmAntragsstatus)
		{
			case "genehmigt":
				eintrag["LinkZumAntrag"] = "<a href='https://sp.vzd.zivb.net/sites/08F6/Portal_Zutrittsberechtigungen/SitePages/Zutritt%20erweitern%20oder%20%C3%A4ndern.aspx?View=%7BA06BD530%2D257B%2D4185%2DA051%2DB8941B792BCE%7D&SelectedID=" + eintrag.ID + "'>Antrag öffnen</a>";
				break;
			case "zwischengespeichert":
				eintrag["LinkZumAntrag"] = "<a href='https://sp.vzd.zivb.net/sites/08F6/Portal_Zutrittsberechtigungen/SitePages/Zutrittsberechtigungen%20fertigstellen%20oder%20stornieren.aspx?View=%7B68D715FA%2D814E%2D49FE%2D9DEE%2DA832D09972AE%7D&SelectedID=" + eintrag.ID + "'>Antrag öffnen</a>";
				break;
				
			default:
				eintrag["LinkZumAntrag"] = "<a href='https://sp.vzd.zivb.net/sites/08F6/Portal_Zutrittsberechtigungen/SitePages/Zutrittsgenehmigungsantrag.aspx?View=%7B7738D770%2DAD3B%2D4198%2D91C3%2DB1E13DE12B18%7D&SelectedID=" + eintrag.ID + "'>Antrag öffnen</a>";
						
		}
				
		if (eintrag.asADAccount==="keiner") {eintrag.frmAntragstyp="Anträge für Mitarbeitende ohne SharePoint Zugriff"};
		if (eintrag.rlADAccount==="keiner") {eintrag.frmAntragstyp="Anträge für Mitarbeitende mit SharePoint Zugriff"};
		if (eintrag.rlADAccount!=="keiner" && eintrag.asADAccount!=="keiner") {eintrag.frmAntragstyp="Fehlerhaft, bitte prüfen"};
		
		});
       
		return response.d.results; //return the tableData peroperty of a response json object
    },
	});

	var queryString

	queryString = _spPageContextInfo.webAbsoluteUrl + "/_api/Web/Lists/GetByTitle('Zutrittsberechtigungen')/items?$select=ID,Title,asADAccount,rlADAccount,asVorname,asName,asEmail,asStellenzeichen,ZutrittAb,ZutrittBis,frmAntragsstatus,frmGenehmigungsstufe,tmpAuswahl&$top=5000";

	var ajaxConfig = {
		url: queryString,
		type: "GET",
		dataType: "json",
		headers: {
		Accept: "application/json;odata=verbose"
	}}


	$("#tblZutritte").tabulator("setData",queryString, {},ajaxConfig);
	$("#tblZutritte").tabulator("setLocale", "de-de");
	$("#download-csv").click(function(){
		$("#tblZutritte").tabulator("download", "csv", "data.csv");
	});
	
	$("#rzBerlinFilter").click(function(){
		debugger;
		$("#tblZutritte").tabulator("addFilter", "ID", "=", 114);
	});

	
	
	}

</script>



`

**Comment by mariokitz** [comment]
Sorry, it keeps loosing its format. I have attached it now as a txt:

[Source Code.txt](https://github.com/olifolkerd/tabulator/files/1401203/Source.Code.txt)

**Comment by olifolkerd** [comment]
is there any chance you could post a working example in codepen or post a link to a video of the issue, the code you sent over has dependencies so i cant run it on my computer directly without setting up the project.

Which version of Tabulator are you using?

Cheers

Oli

**Comment by mariokitz** [comment]
Problem solved and not related to Tabulartor. Forgot to add the type="button" to the button, If not present SharePoint thinks it is a submit button and refreshes the page.

**Comment by JoseCintra** [comment]
Thank you , @mariokitz  
I fell into the same error and, thanks to your tip, i managed to fix the code.
