### ISSUE TITLE
希望支持ajax 分页，支持laravel paginate分页，First column支持checkbox。

### ISSUE THREAD

**Issue by wangat** [olifolkerd/tabulator#65]
希望支持ajax 分页，支持laravel paginate分页，First column支持checkbox。

**Comment by hohozhao** [comment]
Translate: Hope it supports ajax pagination, supports  laravel paginate, and first column supports checkbox. [ Well, I managed to add checkbox and buttons using current available functions ]

**Comment by olifolkerd** [comment]
Thanks for the translate.

You can put a checkbox anywhere in the table using a formatter/editor, im in a bit of a ush this morning, but will upload a full bit of example code for you this evening for that.

Inbuilt Ajax pagination is coming in the next release in a couple of weeks. in the mean time you could manually achieve it by passing parameters to the ***getData*** function. i will upload an example this evening for this.

**Comment by wangat** [comment]
@hohozhao 感谢翻译
感谢我主要是想实现的首行的全选功能，ajax支持分页和排序，另外希望支持footer sum功能

**Comment by olifolkerd** [comment]
I should be able to get the ajax pagination controls in this weekend, i will post a message on here when they are in.

Apologies if this is a bad translation, i am using google translate


我应该能得到这个周末的AJAX分页控件，我将张贴在这里的消息时，他们英寸

道歉，如果这是一个糟糕的翻译，我使用谷歌翻译

**Comment by hohozhao** [comment]
@olifolkerd you almost got it. @wangat want to have a function to select all the rows ("select all or select one by one") and may or may not include rows hidden in other pages etc etc. At the end, he requests for "footer sum" function, which I think it is used to calculate field/column (sub)totals etc.

**Comment by olifolkerd** [comment]
Version 2.7 has just been released.

This version includes Laravel compatible remote Ajax pagination.

For full information have a look at the [Pagination documentation](http://olifolkerd.github.io/tabulator/docs/#pagination)

**Comment by wangat** [comment]
@olifolkerd 非常好，感谢付出的辛苦，我会向朋友和同事推荐。

**Comment by olifolkerd** [comment]
You are welcome,

Let me know if there are any other features that would be useful.
