### ISSUE TITLE
Options Error

### ISSUE THREAD

**Issue by kurtknippschild** [olifolkerd/tabulator#652]
Hi Oli,

after the change to Version 3.3.1 I have this error:
![bildschirmfoto 2017-10-20 um 08 06 51](https://user-images.githubusercontent.com/22855656/31807311-b67bcb6e-b56d-11e7-8fdc-064b52d7688e.png)

This is my code:
<div id="tabulator_objektaktivitaeten" style="margin-bottom: 90px;"></div>

<script language="JavaScript" type="text/javascript">
	$(document).ready(function() {

				var fontSizeFormatter = function(cell, formatterParams){
				    //cell - the cell component
				    //formatterParams - parameters set for the column
				
				    var element = cell.getElement();
				    element.css({
				    	"font-size":14,
				    	"cursor":"pointer",
				    	"white-space":"pre-wrap",
				    })
				
				    element.tooltip({ track: true, });
				
				    return cell.getValue(); //return the contents of the cell;
				}	
								
				var fontColorFormatter = function(cell, formatterParams){
				    //cell - the cell component
				    //formatterParams - parameters set for the column
				
				    var element = cell.getElement();
					  if(cell.getValue() == "open")
						{
								element.css({
					    	"color":"rgb(153,153,153)"
					  		})
						} else 
						if(cell.getValue() == "Done")
						{
								element.css({
					    	"color":"rgb(0,178,0)"
					  		})
						} 

				    return cell.getValue(); //return the contents of the cell;
				}	

				var colorFormatter = function(cell, formatterParams){
				    //cell - the cell component
				    //formatterParams - parameters set for the column
				
				    var element = cell.getElement();
				    //console.log(cell.getValue());
					  if(cell.getValue() == "open")
						{
								element.css({
					    	"color":"rgb(153,153,153)",
					    	"background-color":"rgb(153,153,153)",
					  		})
						} else 
						if(cell.getValue() == "Done")
						{
								element.css({
					    	"color":"rgb(0,178,0)",
					    	"background-color":"rgb(0,178,0)",
					  		})
						} 

				    return cell.getValue(); //return the contents of the cell;
				}	

		var tableHeight = $(window).height() - 430;
				
		$("#tabulator_objektaktivitaeten").tabulator({
		    height: tableHeight,
		    columnMinWidth: 20,
		    layout:"fitColumns",
		    groupBy: "zeitlich",
		    colResizable:false,
				columns:[
	        			{title:"ID", field:"TO_ID", sorter:"number", align:"center", visible:false},
			        	{title:"<bean:message bundle="<%= resources %>" key="imaAktivitaeten_liste.label.to_aktivitaetennr"/>", field:"to_aktivitaetennr", headerSort:false, align:"left", width: 120, formatter:fontSizeFormatter, cellClick:function(e, cell){
									var data = cell.getData();
								$.post("imaAktivitaeten_AJ.ims", 
								{
									cache: false,
					 				contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
									TO_ID: data.TO_ID,
									EXP_ID_VATER: '<%= EXP_ID_VATER %>',
									EXP_ID: '<%= EXP_ID %>',
									OG_ID: '<%= OG_ID %>',
									OG_NAME: '<%= OG_NAME %>',				     		  
									OBJ_NAME: '<%= OBJ_NAME %>',
									OBJ_NAME_VATER: '<%= OBJ_NAME %>',  		  
									OK_ID:'<%= OK_ID %>',
									OBJ_ID: '<%= OBJ_ID %>',
									OBJ_ID_VATER: '<%= OBJ_ID %>',
									FU_RECHT: '<%= FU_RECHT %>',
									IST_INVENTAR: '<%= IST_INVENTAR %>',  
									darstart: 'edit',
									aktion: 'infoAk'
								},
								function(data) 
								{		 	
			          		$('#objektAktivitaeten_tabs_<%= OBJ_ID %>').html(data);
										$('#progressbar').css('display', 'none');
			      	 	}, "html")

				        	},
				        },
								{title:"<bean:message bundle="<%= resources %>" key="imaAktivitaeten_liste.label.to_beschreibung"/>", field:"to_beschreibung", headerSort:false, width: 450, formatter:fontSizeFormatter, cellClick:function(e, cell){
									var data = cell.getData();
								$.post("imaAktivitaeten_AJ.ims", 
								{
									cache: false,
					 				contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
									TO_ID: data.TO_ID,
									EXP_ID_VATER: '<%= EXP_ID_VATER %>',
									EXP_ID: '<%= EXP_ID %>',
									OG_ID: '<%= OG_ID %>',
									OG_NAME: '<%= OG_NAME %>',				     		  
									OBJ_NAME: '<%= OBJ_NAME %>',
									OBJ_NAME_VATER: '<%= OBJ_NAME %>',  		  
									OK_ID:'<%= OK_ID %>',
									OBJ_ID: '<%= OBJ_ID %>',
									OBJ_ID_VATER: '<%= OBJ_ID %>',
									FU_RECHT: '<%= FU_RECHT %>',
									IST_INVENTAR: '<%= IST_INVENTAR %>',  
									darstart: 'edit',
									aktion: 'infoAk'
								},
								function(data) 
								{		 	
			          		$('#objektAktivitaeten_tabs_<%= OBJ_ID %>').html(data);
										$('#progressbar').css('display', 'none');
			      	 	}, "html")
	
				        	},},
				        {title:"<bean:message bundle="<%= resources %>" key="imaAktivitaeten_liste.label.to_zustaendige_pers"/>", field:"to_zustaendige_pers", headerSort:false, align:"left"},
				        {title:"<bean:message bundle="<%= resources %>" key="imaAktivitaeten_liste.label.to_beginn"/>", field:"to_beginn", headerSort:false, align:"left"},
				        {title:"<bean:message bundle="<%= resources %>" key="imaAktivitaeten_liste.label.to_erinnerung"/>", field:"to_erinnerung", headerSort:false, align:"left", visible:false},
				        {title:"<bean:message bundle="<%= resources %>" key="imaAktivitaeten_liste.label.st_bezeichnung"/>", field:"to_status", headerSort:false, sorter:"string", align:"right", width:80,formatter:fontColorFormatter},
			 	        {title:"", field:"st_bezeichnung", headerSort:false, align:"center", width: 5, formatter:colorFormatter},
							],
		});	

  var tabulator_objektaktivitaeten_data = [	
		<logic:present name="imaAktivitaetens">
		<logic:iterate id="to" name="imaAktivitaetens">
			<bean:define id="gruppierung" name="to" property="page" type="Integer"/>
			<bean:define id="toSerie" name="to" property="to_serie" type="String"/>
			<bean:define id="toAktivitaetdatum" name="to" property="to_aktivitaetdatum" type="java.sql.Timestamp"/>
			<bean:define id="toStbezeichnung" name="to" property="st_bezeichnung" type="String"/>
			<bean:define id="toId" name="to" property="to_id" type="Integer"/>
			<logic:present name="to" property="to_bemerkung">
				<bean:define id="toBemerkungDB" name="to" property="to_bemerkung" type="String"/>
						<% toBemerkung = toBemerkungDB; %>
			</logic:present>
			<logic:notPresent name="to" property="to_bemerkung">
						<% toBemerkung = " - "; %>
			</logic:notPresent>
				<% anzObjektaktivitaeten++; 
						if(toSerie.equals("1")) { istSerie = "true"; } else { istSerie = "false"; }
						if(toSerie.equals("1")) { %>
						<bean:define id="toAktivitaetdatum" name="to" property="to_serienbeginn" type="java.sql.Timestamp"/>
				<% } else { %>
						<bean:define id="toAktivitaetdatum" name="to" property="to_aktivitaetdatum" type="java.sql.Timestamp"/>
				<% } %>
			<% if(gruppierung.compareTo(3) == 0) { zeitGruppierung = "Abgabetermine in der Vergangenheit"; }
				 else if(gruppierung.compareTo(2) == 0) { zeitGruppierung = "Abgabetermine in der Zukunft"; }
				 else if(gruppierung.compareTo(1) == 0) { zeitGruppierung = "Zeitnaher Abgabetermin"; } %>
			{id:<%= anzObjektaktivitaeten %>
			, TO_ID: "<%= toId %>"
			, info_icon:'<bean:message bundle="<%= resources %>" key="button.img.info"/>'
			, delete_icon:'<bean:message bundle="<%= resources %>" key="button.img.delete"/>'
			<% if(toStbezeichnung.equals("erledigt")) { %>
				, erledigt_icon:"/transparent.png"
			<% } else { %>
			, erledigt_icon:'<bean:message bundle="<%= resources %>" key="button.img.hinzu"/>'
			<% } %>
			, to_aktivitaetennr:"<bean:write format="#" name="to" property="to_aktivitaetennr"/>"
			/*, st_bezeichnung:"<%= toStbezeichnung %>"*/
			, to_beginn:"<%= fmt.format(toAktivitaetdatum) %>"
			, to_erinnerung:"<bean:write format="#" name="to" property="to_erinnerung"/>"
			, to_zustaendige_org:"<bean:write format="#" name="to" property="to_zustaendige_org_s"/>"
			, to_zustaendige_pers:"<bean:write format="#" name="to" property="to_zustaendige_pers_s"/>"
			, to_serie:"<%= istSerie %>"
			, to_beschreibung:"<bean:write format="#" name="to" property="to_beschreibung"/>"
			<% if(toStbezeichnung.equals("erfasst")) { toStbezeichnung = "open"; %>
			/*,st_bezeichnung: "rgb(153,153,153)"*/
			<% } else if(toStbezeichnung.equals("erledigt")) { toStbezeichnung = "Done";%>
			/*,st_bezeichnung: "rgb(0,178,0)"*/
			<% } %>
			, st_bezeichnung: "<%= toStbezeichnung %>"
			, to_status: "<%= toStbezeichnung %>"
			, zeitlich:"<%= zeitGruppierung %>"
			},
		</logic:iterate>
	</logic:present>
    ];

		$("#tabulator_objektaktivitaeten").tabulator("setData", tabulator_objektaktivitaeten_data);
		
		tabulatorRedrawName = "#tabulator_objektaktivitaeten";

		$(window).resize(function(){
				$("#tabulator_objektaktivitaeten").tabulator("setHeight", $(window).height() - 430);
		    $("#tabulator_objektaktivitaeten").tabulator("redraw", true); //trigger full rerender including all data and rows
		});
		
	});
</script>	

Can you tell me whats wrong?

Thanks in advance:
Kurt

**Comment by olifolkerd** [comment]
Hey Kurt,

Sorry for the delay in getting back to you on this one.

It is quite hard to tell whats going on when your posting unformatted code :(

Usually that error means one of two things, you are trying to use the jQuery ***setOption*** function which Tabulator does not support, and i can see you are not using, or you are trying to pass the constructor object to an element that has already been initialized as a Tabulator.

If you are doing the second thing then you must destroy the original Tabulator before reinitializing it:
```js
$("#example-table").tabulator("destroy");
```

I hope that helps

Cheers

Oli

**Comment by kurtknippschild** [comment]
Hi Oli,

thanks for the info.
But this not work.

I  search in all my JSP's  and there is no "setOption" and for the search of "tabulator_objektaktivitaeten"  I find this.
![bildschirmfoto 2017-10-25 um 08 09 27](https://user-images.githubusercontent.com/22855656/31983202-95b56154-b95c-11e7-967d-5d2a460f601c.png)

But this is always in the script.

Is there a problem with the version of jQuery 3.2.1 or jqueryui 1.12.1?

Thanks in advance Kurt

**Comment by olifolkerd** [comment]
Hi Kurt,

Could you post a formatted copy of your code so i can read it more ealisy, then i should be able to tell you what is going on.

Cheers

Oli

**Comment by kurtknippschild** [comment]
Hi Oli,

thanks for the quick answer.
Here the Code.
I hope this helps.

<script language="JavaScript" type="text/javascript">
	$(document).ready(function() {

				var fontSizeFormatter = function(cell, formatterParams){
				    //cell - the cell component
				    //formatterParams - parameters set for the column
				
				    var element = cell.getElement();
				    element.css({
				    	"font-size":14,
				    	"cursor":"pointer",
				    	"white-space":"pre-wrap",
				    })
				
				    element.tooltip({ track: true, });
				
				    return cell.getValue(); //return the contents of the cell;
				}	
								
				var fontColorFormatter = function(cell, formatterParams){
				    //cell - the cell component
				    //formatterParams - parameters set for the column
				
				    var element = cell.getElement();
					  if(cell.getValue() == "open")
						{
								element.css({
					    	"color":"rgb(153,153,153)"
					  		})
						} else 
						if(cell.getValue() == "Done")
						{
								element.css({
					    	"color":"rgb(0,178,0)"
					  		})
						} 

				    return cell.getValue(); //return the contents of the cell;
				}	

				var colorFormatter = function(cell, formatterParams){
				    //cell - the cell component
				    //formatterParams - parameters set for the column
				
				    var element = cell.getElement();
				    //console.log(cell.getValue());
					  if(cell.getValue() == "open")
						{
								element.css({
					    	"color":"rgb(153,153,153)",
					    	"background-color":"rgb(153,153,153)",
					  		})
						} else 
						if(cell.getValue() == "Done")
						{
								element.css({
					    	"color":"rgb(0,178,0)",
					    	"background-color":"rgb(0,178,0)",
					  		})
						} 

				    return cell.getValue(); //return the contents of the cell;
				}	

		//$("#tabulator_objektaktivitaeten").tabulator("destroy");
		
		var tableHeight = $(window).height() - 430;
				
		$("#tabulator_objektaktivitaeten").tabulator({
		    height: tableHeight,
		    columnMinWidth: 20,
		    layout:"fitColumns",
		    groupBy: "zeitlich",
		    colResizable:false,
				columns:[
	        			{title:"ID", field:"TO_ID", sorter:"number", align:"center", visible:false},
			        	{title:"Aktivit&auml;ten-Nr.", field:"to_aktivitaetennr", headerSort:false, align:"left", width: 120, formatter:fontSizeFormatter, cellClick:function(e, cell){
									var data = cell.getData();
								$.post("imaAktivitaeten_AJ.ims", 
								{
									cache: false,
					 				contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
									TO_ID: data.TO_ID,
									EXP_ID_VATER: '',
									EXP_ID: '',
									OG_ID: '39',
									OG_NAME: '',				     		  
									OBJ_NAME: '2017_000047',
									OBJ_NAME_VATER: '2017_000047',  		  
									OK_ID:'212',
									OBJ_ID: '100006036',
									OBJ_ID_VATER: '100006036',
									FU_RECHT: '0',
									IST_INVENTAR: 'n',  
									darstart: 'edit',
									aktion: 'infoAk'
								},
								function(data) 
								{		 	
			          		$('#objektAktivitaeten_tabs_100006036').html(data);
										$('#progressbar').css('display', 'none');
			      	 	}, "html")

				        	},
				        },
								{title:"Aktivit&auml;tenbeschreibung", field:"to_beschreibung", headerSort:false, width: 450, formatter:fontSizeFormatter, cellClick:function(e, cell){
									var data = cell.getData();
								$.post("imaAktivitaeten_AJ.ims", 
								{
									cache: false,
					 				contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
									TO_ID: data.TO_ID,
									EXP_ID_VATER: '',
									EXP_ID: '',
									OG_ID: '39',
									OG_NAME: '',				     		  
									OBJ_NAME: '2017_000047',
									OBJ_NAME_VATER: '2017_000047',  		  
									OK_ID:'212',
									OBJ_ID: '100006036',
									OBJ_ID_VATER: '100006036',
									FU_RECHT: '0',
									IST_INVENTAR: 'n',  
									darstart: 'edit',
									aktion: 'infoAk'
								},
								function(data) 
								{		 	
			          		$('#objektAktivitaeten_tabs_100006036').html(data);
										$('#progressbar').css('display', 'none');
			      	 	}, "html")
	
				        	},},
				        {title:"Verantwortlicher", field:"to_zustaendige_pers", headerSort:false, align:"left"},
				        {title:"Abgabedatum", field:"to_beginn", headerSort:false, align:"left"},
				        {title:"Erinnerung", field:"to_erinnerung", headerSort:false, align:"left", visible:false},
				        {title:"Status", field:"to_status", headerSort:false, sorter:"string", align:"right", width:80,formatter:fontColorFormatter},
			 	        {title:"", field:"st_bezeichnung", headerSort:false, align:"center", width: 5, formatter:colorFormatter},
							],
		});	

  var tabulator_objektaktivitaeten_data = [	
		
		
			
			
			
			
			
			
			
						
			
				
						
				
			
			{id:1
			, TO_ID: "48"
			, info_icon:'/Dashboard/details.png'
			, delete_icon:'/reghub/icons/Close_active.png'
			
			, erledigt_icon:'/icon_bearbeitung_angenommen.gif'
			
			, to_aktivitaetennr:"2017_000048"
			/*, st_bezeichnung:"erfasst"*/
			, to_beginn:"29.10.2017 09:00"
			, to_erinnerung:"1"
			, to_zustaendige_org:"Compliance"
			, to_zustaendige_pers:"Iris Bujatti"
			, to_serie:"false"
			, to_beschreibung:"Abstimmung mit Reghub"
			
			/*,st_bezeichnung: "rgb(153,153,153)"*/
			
			, st_bezeichnung: "open"
			, to_status: "open"
			, zeitlich:"Zeitnaher Abgabetermin"
			},
		
			
			
			
			
			
			
			
						
			
				
						
				
			
			{id:2
			, TO_ID: "47"
			, info_icon:'/Dashboard/details.png'
			, delete_icon:'/reghub/icons/Close_active.png'
			
			, erledigt_icon:'/icon_bearbeitung_angenommen.gif'
			
			, to_aktivitaetennr:"2017_000047"
			/*, st_bezeichnung:"erfasst"*/
			, to_beginn:"20.10.2017 04:00"
			, to_erinnerung:"1"
			, to_zustaendige_org:"Compliance"
			, to_zustaendige_pers:"Iris Bujatti"
			, to_serie:"false"
			, to_beschreibung:"Projekt anlegen"
			
			/*,st_bezeichnung: "rgb(153,153,153)"*/
			
			, st_bezeichnung: "open"
			, to_status: "open"
			, zeitlich:"Abgabetermine in der Vergangenheit"
			},
		
	
    ];

		$("#tabulator_objektaktivitaeten").tabulator("setData", tabulator_objektaktivitaeten_data);
		
		tabulatorRedrawName = "#tabulator_objektaktivitaeten";

		$(window).resize(function(){
				$("#tabulator_objektaktivitaeten").tabulator("setHeight", $(window).height() - 430);
		    $("#tabulator_objektaktivitaeten").tabulator("redraw", true); //trigger full rerender including all data and rows
		});
		
	});
</script>

**Comment by olifolkerd** [comment]
Hi Kurt,

I will read through that later today, 

just so you know i had to edit your post to show the code correctly, you should be enclosing code in \```js \``` tags to make it render correctly in github.

Cheers

Oli

**Comment by kurtknippschild** [comment]
Hi Oli,
 now as file.
[objektaktivitaeten.txt](https://github.com/olifolkerd/tabulator/files/1413533/objektaktivitaeten.txt)

Kurt
