### ISSUE TITLE
Cannot resize and move Column in Mobile

### ISSUE THREAD

**Issue by robertwong68** [olifolkerd/tabulator#654]
Tabulator persistent Column layout work perfectly on PC with column move and resize but not in mobile device. Cannot move or resize a column. Pls help.

**Comment by robertwong68** [comment]
Sorry, I have been using tabulator extensively on web application and just want to know whether it works on also on mobile browser.

**Comment by olifolkerd** [comment]
Hey @robertwong68 

Sorry for the delay in getting back to you,

Tabulator is mobile compatible, but you are right at the moment the column moving and resizing are not available through touch interaction as it became very hard to offer both without the interface becoming cluncky and confusing as it is hard to trigger a touch event precisely on the edge of a column for the resize, and then allow dragging further in, on a lot of mobile devices columns can be rather narrow and this causes a bad user experience.

It is on the roadmap to look into this further in the future.

Cheers

Oli
