### ISSUE TITLE
clearHeaderFilters() should trigger filtering

### ISSUE THREAD

**Issue by cheppsn** [olifolkerd/tabulator#658]
When calling `clearHeaderFilters()` I think re-filtering should occur, this does currently not happen. 

I.e. if I filter a table with 100 entries down to 50 entries with a header filter, and then call `clearHeaderFilters()` the header filter fields are cleared as expected, but the table stays at 50 entries and does not go back to showing a 100 entries.

When I tried workarounds I couldn't find a method to trigger the filtering of a table explicitly. Is there a way to do that?

Otherwise: great work, really! Thank you.

**Comment by cheppsn** [comment]
On a related issue: I would like to set "example queries" on the header filter inputs and then trigger filtering. I am able to do this:

```
var headerField = $("#example-table div.tabulator-header-filter input").eq(0); 
headerField.val('foo')
```
will set "foo" to appear in the first header filter input field, however filtering does not take place. 

I tried triggering change afterwards with `headerField.val('foo').change()` but I can not get the filtering to run. So an explicit filtering-trigger would be nice...

**Comment by olifolkerd** [comment]
Hey @cheppsn,

Looks like you have found a bug there, you are right, it should trigger a re-filter at that point, i will get a fix out for that in the next patch release.

If you want to trigger the search in that way you need to trigger the ***keyup*** event:
```js
headerField.val('foo').keyup();
```

Cheers

Oli

**Comment by cheppsn** [comment]
Hi Oli

thanks, that helped!

Keep up the good work,
Kaspar

**Comment by olifolkerd** [comment]
I have just pushed a fix for this to the master branch, it will be included in this evenings patch release
