### ISSUE TITLE
Update column group header (title) after initialization

### ISSUE THREAD

**Issue by aditya-thimphu** [olifolkerd/tabulator#659]
Hi Oli,

Is there a way to update column group header (title) after initialization? E.g. update column group header after an ajax call.

Thanks,
Aditya

**Comment by olifolkerd** [comment]
at the moment, i think the only way to do this would be to reinitialize the columns passing a new column definition array to the ***setColumns*** function.

I will add a columnGroup component to the roadmap to make this functionality available in future

**Comment by aditya-thimphu** [comment]
Thanks Oli, I look forward to the new release.

**Comment by olifolkerd** [comment]
Hey @aditya-thimphu 

Sorry my previous advice was wrong, you can use the ***setGroupHeader*** to update the header generation function after the grouping has been completed:

```js
$("#example-table").tabulator("setGroupHeader", function(value, count, data, group){
    //value - the value all members of this group share
    //count - the number of rows in this group
    //data - an array of all the row data objects in this group
    //group - the group component for the group

    return count > 3; //all groups with more than three rows start open, any with three or less start closed
});
``

Cheers

Oli :)

**Comment by SusannaHolmquist** [comment]
Is there a way to update the column titles that are part of a Column Group? I receive 'Column Update Error - No matching column found:'

[https://jsfiddle.net/gLbmsv97/](url)

```
const table = new Tabulator("#example-table", {
  layout: "fitColumns",
   columns:[
    {title:"Name", field:"name", width:160},
    {//create column group
        title:"Work Info",
        columns:[
             {title:"Progress", field:"progress"},
             {title:"Rating", field:"rating"},
             {title:"Driver", field:"car"}]}],
});

var updatedTitle1 = 'goo';
var updatedTitle2 = 'foo';
var updatedTitle3 = 'boo';

table.updateColumnDefinition({
        title:"Work Info",
             columns:[
                  {title: updatedTitle1, field:"progress"},
                  {title: updatedTitle2, field:"rating"},
                  {title: updatedTitle3, field:"car"},
                  ]
         });

```

-----------------------------ERROR-----------------------------
"Column Update Error - No matching column found:", {
  columns: [{
  field: "progress",
  title: "goo"
}, {
  field: "rating",
  title: "foo"
}, {
  field: "car",
  title: "boo"
}],
  title: "Work Info"
}


Thank you!
