### ISSUE TITLE
Mutator issue: can not update field

### ISSUE THREAD

**Issue by hohozhao** [olifolkerd/tabulator#66]
Hi @olifolkerd,

I want to replace the password or hashed password, like this:

```
    {title:"Password", field:"password", sortable:false, editor:"password",
        mutator:function(value){ return "*Hash Encrypted*" },
```
In this case, when I click on password field and change value, mutator always change it to the string I defined and the field value will never get updated. Also noticed that, I set celledited event, but it happens after mutator change the value. If mutator happen after celledited event, I can get what I want.

Any resolution for this? Thx,

**Comment by olifolkerd** [comment]
When you update a data value by editing a cell, the following should happen in this order:

- the mutator (if present) will be applied to the value
- the mutated value will be stored in the row data array
- the the formatter (if present) will be called on this value
- the value (formatted (if present) will be displayed in the cell.
- the cellEdited callback will be called.

So in the case of the mutator you have above, you will always be changing the data to the string "*Hash Encrypted".

if you want to encrypyt the data with your mutator, but display the sting "*Hash Encrypted*" to the user then you need to be using a formatter as well:

```js
{
   title:"Password",
   field:"password", 
   sortable:false, 
   editor:"password",
   mutator:function(value){ return hashData(value);},  
   formatter:function(value){ return "*Hash Encrypted*";}
},

//the hashData function would be where you place your encrypting code.
```

So just to clarify:

-  ***formatter*** - change how the data for a cell is displayed in the cell without changing the value of the data
- ***mutator*** - change the actual data for the cell.

**Comment by hohozhao** [comment]
Thx Oli. Your recommended way works perfectly!
