### ISSUE TITLE
visible:false for one or more but not all of a set of grouped columns not working

### ISSUE THREAD

**Issue by aditya-thimphu** [olifolkerd/tabulator#660]
Hi Oli,

I guess this is a bug - when I set visible:false to one or more but not all of a set of grouped columns, the headers lose shape/order. Please advise.

Thanks,
Aditya

**Comment by olifolkerd** [comment]
Hey @aditya-thimphu 

Could you post a copy of your table constructor object so i have somthing to test against.

Thanks

Oli

**Comment by aditya-thimphu** [comment]
Thanks for your response. I want to hide some of the columns (under column groups) initially. I have a feature where a user can show/hide columns after loading. Show/hide after loading works fine, but the constructor's visible:false for grouped columns doesn't work. Below is the constructor code.

$("#report-table-detailed").tabulator({
            placeholder:"Select required parameters/filters to view report.",
            columns:[
                {title:"Account Type",field:"AccountType",visible:false,hasShowHide:true,hasGrouping:true},
                {title:"Main Group",field:"MainGroup",visible:false,hasShowHide:true,hasGrouping:true},
                {title:"Sub-Group",field:"SubGroup",visible:false,hasShowHide:true,hasGrouping:true},
                {title:"Activity",field:"BudgetHead",minWidth:180},
                {title:"Project",
                    columns:[
                        {title:"Initial Budget",field:"NewBudget_0",align:"right",formatter:"money",headerSort:false,visible:false,bottomCalc:sumCalc,hasShowHide:true},
                        {title:"Re-appropriation",field:"Reappropriation_0",align:"right",formatter:"money",headerSort:false,visible:false,bottomCalc:sumCalc,hasShowHide:true},
                        {title:"Supplimentary",field:"Supplimentary_0",align:"right",formatter:"money",headerSort:false,visible:false,bottomCalc:sumCalc,hasShowHide:true},
                        {title:"Total Budget",field:"TotalBudget_0",align:"right",formatter:"money",headerSort:false,bottomCalc:sumCalc,hasShowHide:true},
                        {title:"Total Expenditure",field:"TotalExpenditure_0",align:"right",formatter:"money",headerSort:false,bottomCalc:sumCalc,hasShowHide:true},
                        {title:"Variation",field:"VariationAbsolute_0",align:"right",formatter:"money",headerSort:false,visible:false,bottomCalc:sumCalc,hasShowHide:true},
                        {title:"Variation in %",field:"VariationPercent_0",align:"right",formatter:"money",headerSort:false,bottomCalc:avgPercentCalc_0,hasShowHide:true}]
                },
                {title:"Year",
                    columns:[
                        {title:"Initial Budget",field:"NewBudget_1",align:"right",formatter:"money",headerSort:false,visible:false,bottomCalc:sumCalc,hasShowHide:true},
                        {title:"Re-appropriation",field:"Reappropriation_1",align:"right",formatter:"money",headerSort:false,visible:false,bottomCalc:sumCalc,hasShowHide:true},
                        {title:"Supplimentary",field:"Supplimentary_1",align:"right",formatter:"money",headerSort:false,visible:false,bottomCalc:sumCalc,hasShowHide:true},
                        {title:"Total Budget",field:"TotalBudget_1",align:"right",formatter:"money",headerSort:false,bottomCalc:sumCalc,hasShowHide:true},
                        {title:"Total Expenditure",field:"TotalExpenditure_1",align:"right",formatter:"money",headerSort:false,bottomCalc:sumCalc,hasShowHide:true},
                        {title:"Variation",field:"VariationAbsolute_1",align:"right",formatter:"money",headerSort:false,visible:false,bottomCalc:sumCalc,hasShowHide:true},
                        {title:"Variation in %",field:"VariationPercent_1",align:"right",formatter:"money",headerSort:false,bottomCalc:avgPercentCalc_1,hasShowHide:true}]
                },
                {title:"Quarter",
                    columns:[
                        {title:"Initial Budget",field:"NewBudget_2",align:"right",formatter:"money",headerSort:false,visible:false,bottomCalc:sumCalc,hasShowHide:true},
                        {title:"Re-appropriation",field:"Reappropriation_2",align:"right",formatter:"money",headerSort:false,visible:false,bottomCalc:sumCalc,hasShowHide:true},
                        {title:"Supplimentary",field:"Supplimentary_2",align:"right",formatter:"money",headerSort:false,visible:false,bottomCalc:sumCalc,hasShowHide:true},
                        {title:"Total Budget",field:"TotalBudget_2",align:"right",formatter:"money",headerSort:false,bottomCalc:sumCalc,hasShowHide:true},
                        {title:"Total Expenditure",field:"TotalExpenditure_2",align:"right",formatter:"money",headerSort:false,bottomCalc:sumCalc,hasShowHide:true},
                        {title:"Variation",field:"VariationAbsolute_2",align:"right",formatter:"money",headerSort:false,visible:false,bottomCalc:sumCalc,hasShowHide:true},
                        {title:"Variation in %",field:"VariationPercent_2",align:"right",formatter:"money",headerSort:false,bottomCalc:avgPercentCalc_2,hasShowHide:true}]
                }
            ],
//            dataLoading:function() {
//                loadColumnsAndGroupsSelectors(this.columns);
//            },
//            renderComplete:function(){
//                displayGrandTotal($("#report-table-detailed"));
//            }
        });

var sumCalc = function(values, data, calcParams){
    var sum = 0.00;
    values.forEach(function(value){
        sum += Number(value);
    });
    return sum.toFixed(2).toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
};

**Comment by olifolkerd** [comment]
Hey @aditya-thimphu 

Sorry for the delay in getting back to you on this one, i have traced the issue back to a bug. I have pushed an updated to the master branch to fix this, it will be included in this evenings patch release.

Cheers

Oli

**Comment by aditya-thimphu** [comment]
Thanks a lot Oli. I had been waiting for this.
