### ISSUE TITLE
How can I replace a cell's content wrapped in html, like <del/> ??

### ISSUE THREAD

**Issue by bobabarbanel** [olifolkerd/tabulator#664]
I want to mark deleted rows with altered text that uses the stricke-through font.
I do not see a way to replace the "text" with <del>text</del> as the first child of tabulator-cell.

**Comment by olifolkerd** [comment]
You could use the ***rowFormatter*** to do this:

In the example below i assume you have set a ***deleted*** property on the row if it is deleted:

```js
$("#example-table").tabulator({
    rowFormatter:function(row, data){
        if(data.deleted){
            row.getElement().css({"text-decoration":"line-through"});
        }else{
            row.getElement().css({"text-decoration":""});
        }
    },
});
```

Let me know if that helps

Cheers

Oli

**Comment by bobabarbanel** [comment]
2 questions.
1) How do I set such a property for the row? I can have the original data start with deleted = true, but I do not see how to toggle it.

2) Won't this rowFormatter run all the time? Is there a way I can simply invoke it just when it's needed.
At the moment I am using a formatter function for the cells but they require a change in the data, I think, for THAT CELL, to get run.
function strikeout(cell, formatterParams) {
    let val = $(cell.getRow().getElement()).css("background");
    if (val === pink) { // and I am checking the background color which has been set
        return "<del>" + cell.getValue() + "</del>";
    }
    return cell.getValue();
}
I'd love to use the rowFormatter with "text-decoration" if I can establish the data.deleted === true.

**Comment by olifolkerd** [comment]
You could add a column with a delete button in, you could then also handle your row formatting in this too:
```js
$("#example-table").tabulator({
    columns:[
        ....
        {field:"deleted", formatter:function(cell){
            if(cell.getValue()){
                row.getElement().css({"text-decoration":"line-through"});
            }else{
                row.getElement().css({"text-decoration":""});
            }
            return "<button>Delete</button>";
        }, cellClick:function(e, cell){
            cell.getRow.update({deleted:true});
        }}
    ]
});
```
