### ISSUE TITLE
1000+datas When the record is displayed, the page is jammed

### ISSUE THREAD

**Issue by yaxino** [olifolkerd/tabulator#669]
Returns 20 column (and 1000+ and 700k) data from the server.

When the record is displayed, The page cannot operate for 5s

cannot click, cannot scroll.

please help me!

**Comment by yaxino** [comment]
at v3.3.1

**Comment by yaxino** [comment]
sorry , not tabulator `s problem.  my codes has bug.

>`console.log('begin count:'+ new Date());
                        var pls = [];
                        var os = [];
                        var lt = [];
                        var tempOwnerHtml = '';
                        var tempPLHtml = '';
                        var tempLTHtml = '';
                        for (var i in allData) {
                            if (allData[i].Approvers && allData[i].Approvers.length > 0) {
                                var cks = allData[i].Approvers.split("|");
                                var tempUser = null;
                                for (var j in cks) {
                                    if (cks[j].length > 0) {
                                        tempUser = cks[j];
                                        if (!machArr(os, tempUser)) {
                                            os.push(tempUser);
                                            tempOwnerHtml += '<option>' + tempUser + '</option>';
                                            
                                        }
                                    }
                                }
                               
                                 
                            }


                            if (allData[i].ProjectLead != '' && !machArr(pls, allData[i].ProjectLead)) {
                                pls.push(allData[i].ProjectLead);
                                tempPLHtml +='<option>' + allData[i].ProjectLead + '</option>';
                            }

                            if (allData[i].LeadTower != '' && !machArr(lt, allData[i].LeadTower)) {
                                lt.push(allData[i].LeadTower);
                                tempLTHtml += '<option>' + allData[i].LeadTower + '</option>';
                                
                            }

                            $('#search_owner,#search_projectlead,#search_leadtower').css({ 'width': '100%' }).select2({
                                tags: false
                            });
                            //resetPhase()


                        }
                        $('#search_owner').append(tempOwnerHtml);
                        $('#search_projectlead').append(tempPLHtml);
                        $('#search_leadtower').append(tempLTHtml);
                        resetPhaseCount(allData);
                        //end: resetPhase()
                    }
                    allPhase = '<div>' + $('#steps_model_view').html() + '</div>';
                    console.log('end count:' + new Date());`

**Comment by olifolkerd** [comment]
you need to make sure you set the ***height*** property of the table so it can use the virtual DOM:

```js

$("example-table").tabulator({
 height:"100px",
columns:[...],
});
```

Cheers

Oli
