### ISSUE TITLE
Undo/redo callback

### ISSUE THREAD

**Issue by Lazaroth** [olifolkerd/tabulator#673]
I would like to run a function whenever a user does undo/redo. Would it be possible to add a callback? (or is there already one?)

**Comment by olifolkerd** [comment]
There currently arent any callbacks for these actions, but you are in luck they are on the roadmap for the next release!

**Comment by olifolkerd** [comment]
Hey @Lazaroth 

You will be happy to hear i have pushed an update to the 3.4 branch with these new features in:

```js
$("#example-table").tabulator({
    historyUndo:function(action, component, data){
        //action - the action that has been undone
        //component - the Component object afected by the action (colud be a row or cell component)
        //data - the data being changed
    },
});
```

```js
$("#example-table").tabulator({
    historyRedo:function(action, component, data){
        //action - the action that has been redone
        //component - the Component object afected by the action (colud be a row or cell component)
        //data - the data being changed
    },
});
```
They will be released with a load of other updates in a couple of weeks time.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Tabulator version 3.4 has now been officially released!

You can find details of the new release in the [News Section](http://tabulator.info/news)

Full documentation of all the new features can be found [Here](http://tabulator.info/docs/3.4)

Cheers

Oli :)
