### ISSUE TITLE
Minimizing subgroup not working properly

### ISSUE THREAD

**Issue by Lazaroth** [olifolkerd/tabulator#674]
Hey,

In my current setup I'm using two layers of group, lets call them topgroup and subgroup. Minimizing the topgroup works perfectly, but doing the same with the subgroup gives erratic behavior where it's not hiding the correct columns.

I also tested groupStartOpen: [true, false], which provided similar but other weird results.

**Comment by olifolkerd** [comment]
could you post a copy of your table constructor so i have something to test against.

what browser are you using?

what do you mean by erratic behaviour, when you say the correct columns, hiding groups should not affect the column visibility at all. do you have any screenshots?

**Comment by Lazaroth** [comment]
Can I send more info in a more private location?
