### ISSUE TITLE
On adding headerClick event to the column header, the default sort event is not stopped

### ISSUE THREAD

**Issue by snehilameta** [olifolkerd/tabulator#675]
When I try to add following function to the headerClick property of every column
`function(e,column){
     alert(column.title +"column is right clicked");
}`
The default sort action is also applied on the rows.

I would like to run only my custom function defined above when user clicks one of the column header.

**Comment by tomheaps** [comment]
Then set `headerSort: false `on all the columns!

**Comment by jerrens** [comment]
I have a similar need, except I still want to offer sorting, so the proposed solution to set headerSort: false won't work for me.

I was able to work around this using the titleFormatter as described in https://stackoverflow.com/a/59201107/2136313, but that approach doesn't seem to work for sub-columns... the parent's headerClick event is still triggered.

It would be nice if we the region around the sort arrow could trigger the sort event, and the title trigger the headerClick (and related) events.
