### ISSUE TITLE
PHP and Ajax Example

### ISSUE THREAD

**Issue by Krigen** [olifolkerd/tabulator#676]
I want to get my data using a PHP file. The data is in a SQL file. I use PHP to call the data and do some stuff to it. 
I tried looking at your example for AJAX call, but I don't understand parts of the code.
http://tabulator.info/examples/3.3?#ajax and http://tabulator.info/docs/3.3?#ajax

1.  Is the PHP suppose to be in :
  ```
 $data = array(
    array(id=>1, name=>"Billy Bob", age=>"12", gender=>"male", height=>1, col=>"red", dob=>"", cheese=>1),
    array(id=>2, name=>"Mary May", age=>"1", gender=>"female", height=>2, col=>"blue", dob=>"14/05/1982", cheese=>true),
);
```
or 
```
var tabledata = [
    {id:1, name:"Oli Bob", age:"12", col:"red", dob:""},
    {id:2, name:"Mary May", age:"1", col:"blue", dob:"14/05/1982"},
];
```
2. Is the PHP array var suppose to have certain format or name?
3. In the js file, for the AJAX, 
   $("#example-table").tabulator("setData", "/sample_data/ajax/data.php");
   Is the code suppose to call something a function?
4. Is "echo(json_encode($data));" all that's needed for the PHP side?
     a). When I tried it, it just printed out under the table.

Thank You for your help

**Comment by tomheaps** [comment]
To set the initial data in your instance of tabulator using the `setData` function use the following line of code after defining your table and column options:

` $('#your-table-name').tabulator("setData", "php/setData.php");`

You will need to create a `setData.php` file and put this in the same directory as your tabulator web page, the code for this file could be something like:

```
<?php
   $servername = "localhost";
   $username = "YOURUSERNAME";
   $password = "YOURPASSWORD.";
   $dbname = "YOURDATABASENAME";

   $connection = new mysqli($servername,$username,$password,$dbname) or die("Error " . 
   mysqli_error($connection));

    $sql = "select * from YOURTABLENAME";
    $result = mysqli_query($connection, $sql) or die("Error in Selecting " . mysqli_error($connection));

    $emparray = array();
    while($row =mysqli_fetch_assoc($result))
    {
        $emparray[] = $row;
    }
    echo json_encode($emparray);

    mysqli_close($connection);
?>
```

**Comment by Krigen** [comment]
When I try this code, it is echoing to the page under the table. If I hit the button, nothing happens.
PHP
```
<?
 $rowArr=array();

 if (mysqli_num_rows($result) > 0)
  {
   date_default_timezone_set('America/New_York');
   $i=0;
   while($row = mysqli_fetch_assoc($result))
    {
        $row['destport']=getPort($row['destport']);
        $row['logdate']=date('Y m d H:i:s',$row['logdate']);

       $sqlInfo='"id"=>"'. $i.'", "logdate"=>"'. $row['logdate'].'", "srcip"=>"'. $row['srcip'].'", "destip"=>"'. $row['destip'].'", "destport"=>"'. $row['destport'].'", "service"=>"'.$row['service'].'", "rule"=>"'. $row['rule'].'"';

       $sqlInfo="{".$sqlInfo."}";
       $i++;
       array_push($rowArr, $sqlInfo);
    }
  }
 else
  {
   echo '0 results';
  }

 echo json_encode($rowArr);
 mysqli_close ($db);
?>
```
JS
```
$("#button").click(function(){
  $("#tabulator").tabulator("setData", "getinfo.php");
});
```

**Comment by olifolkerd** [comment]
what do you mean it is echoing to the page under the table, could you post a screenshot?

**Comment by Krigen** [comment]
![screenshot](https://user-images.githubusercontent.com/1379368/32382432-91b16f9a-c08b-11e7-80ba-2dc77fb431c0.png)

**Comment by olifolkerd** [comment]
that would suggest there is either an error in your javascript or the way you are loading your pages on the PHP side

**Comment by Krigen** [comment]
I did a work around. I'll look into the issue later. Thank you
