### ISSUE TITLE
Is it possible to "redraw" ONLY a row after gotten refresh data?

### ISSUE THREAD

**Issue by hohozhao** [olifolkerd/tabulator#68]
Hi @olifolkerd ,

For example, I make a post/get to get a specific row data in json format, and I would like to update that row only instead of redrawing a whole table by "setData" (which causes a flash which I don't like). 

Thx,

**Comment by olifolkerd** [comment]
Are you adding this as a new row to the table or updating a row that has be already been rendered?

**Comment by hohozhao** [comment]
Let's say adding a new row, as some fields are automatically added by database, so not all fields in the table need to be filled by need to be updated after posting.

**Comment by olifolkerd** [comment]
If you are adding a new row to the table, you can use the ***addRow*** function:
```js
$("#example-table").tabulator("addRow", {name:"Billy Bob", age:"12", gender:"male", height:1});
```
Full documentation for this can be found [here](http://olifolkerd.github.io/tabulator/docs/#manipulating-data).

**Comment by hohozhao** [comment]
I know, that's what I am using, but even I use the callback event:
```
$("#example-table").tabulator({
    rowAdded:function(data, row){
        //data - the data for the row
        //row - DOM element for the row
    },
});
```
The "data" doesn't contain the full data in database, and I need to make a get/post to database to retrieve the full data, e.g. the newly pulled data stored in var named "new_data" which is in json format, how to use "new_data" to update the current row?

**Comment by olifolkerd** [comment]
At the moment the only way to update existing data in the table is to call ***setData*** and update it all at once.

I would be happy to add an ***updateRow*** function to allow for updating of an individual rows data without updating the entire table. would that be of use to you?

**Comment by hohozhao** [comment]
Yes, very cool. I am looking forward to your "updateRow" function. When ready, you can send the individual function/patch to me before your next release (can't wait!). ;) I did hack a bit of your codes and will give you more and more feedback as I use it more.

**Comment by olifolkerd** [comment]
There will be a release coming out today with Ajax pagination in, i will see if i can include it in that

**Comment by hohozhao** [comment]
In the meantime, I would like to ask another question but related. When use "setData", table will be redrawn with new data, but showing a somewhat "data loading" screen (normally it's a flash screen) before table redrawn, which I don't like to see. Is there a way to prevent that "data loading" screen?

**Comment by olifolkerd** [comment]
In the css set ***.tabulator-loade***r to ***display:none !Important;***


```css
.tabulator .tablulator-loader{
    display:none !important;
}
```
That should permanently hide the loader

**Comment by hohozhao** [comment]
Cool. It works. Btw, I just saw your update tabulator.js, with comments for adding "updateRow" function. Shall I give it a try now? Or have you done for today? :)

**Comment by olifolkerd** [comment]
im just putting in the last few tweaks now, i will drop a post on hear when it is ready for you to have a play with

**Comment by olifolkerd** [comment]
The ***updateRow*** and ***updateData*** functions are now available for use.

Full documentation on each function can be found [here](http://localhost/docs/#manipulating-data).

**Comment by hohozhao** [comment]
Hi @olifolkerd , I just tried, it's not what I want. 

I am not sure whether the "updateRow" or "updateData" functions work or not, but I tried these:

```
$("#table-body").tabulator("updateData", [res_data]);
$("#table-body").tabulator("redraw");
or
$("#table-body").tabulator("updateRow", data.rid, res_data);
$("#table-body").tabulator("redraw");
```
I don't see the table/row is updated. Maybe the data is updated, well, I am not sure but my tests failed. 

What I want to see is to see the table updated with new data in the cells.

**Comment by olifolkerd** [comment]
Have you told your tabulator that the index for each row is the "rid" parameter that you are using? If not, it will not be able to correctly identify the rows that need updating.

To do this you need to set the ***index*** option in the table constructor:

```js
$("#example-table").tabulator({
    index:"rid",
});
```

You shouldn't need to call redraw after the functions, that will happen as part of the update

If this still dosnt work, could you post an example of the data array/object you are passing to the function

**Comment by hohozhao** [comment]
Yes, that's the first thing I did. I think I am familiar with that.

**Comment by olifolkerd** [comment]
I will need a bit mor information to be able to work out where the issue is coming from.

Could you post a copy of your tabulator constructor and some example data that you are struggling with.

**Comment by hohozhao** [comment]
Table constructor: 

```
 $("#table-body").hide().html("").off().tabulator({
        index: "rid",
        sortBy: "rid",
        sorDir: "desc",
        columns: cols_def_array,
        fitColumns: true,
        ajaxURL: protocol + "//"+ host + "/search?s_ent_id=" + ent_id
            + "&type=" + type + "&keywords=" + keywords,
        pagination: true,
        paginationSize: 20,
        dataLoaded: function(data){
            $("#table-head").show();
            $("#table-body").show();
        },
        rowFormatter: function(data, row){
            row.css({"height":"28px"});
        },
    });
```
The problem happens here when I click the post, the following code is working, but it updates the whole table, but what I want is to only update the 1 row which just added.
  ```
formatters:{
      ridCell:function(value, data, cell, row, options, formatterParams){ //plain text value
            if (value != 0) {
                var checkbox = $('<input type="checkbox">');
                return checkbox;
            } else {
                cell.css({ "padding":"2px" });
                var button = $('<button class="my-button">Save</button>');
                button.on("click", function(){
                    $.post('/' + type + '/insert/' + ent_id, data, function(result){
                        if (result.insertId) {
                            data.rid = result.insertId;
                            // Needs improvement - Waiting for tabulator author to add new "updateRow" function
                            $("#table-body").tabulator("setData");
                        } else {
                            alert('Failed');
                        }
                    }, 'json');
                });
                return button;
            }
        },
```

**Comment by olifolkerd** [comment]
I think the issue you are having is because you are trying to alter the index of the row as part of the update, in this case you want to pass the row jQuery object to the ***updateRow*** function instead of the index. and you want to make sure the new row data object has the rid set to the new value.

So  assuming your post statement returns the row data as an object, you want to replace the contents of the ```if (result.insertId) {``` statement as follows:
```js
if (result.insertId) {
     $("#table-body").tabulator("updateRow", row, result);
}
```

**Comment by hohozhao** [comment]
Awesome! It works that way you mentioned! This can be closed! Cheers.

**Comment by olifolkerd** [comment]
It was because you were altering it using the line:
```js
data.rid = result.insertId;
```
This only altered it in the row data, it didnt update any of the bindings to the DOM element. By updating it through the ***updateRow*** method, Tabulator regenerates all the internal data structures and the DOM elements to match the new index.

**Comment by hohozhao** [comment]
Cool. Understand. Thx.
