### ISSUE TITLE
Remove All HeaderFilter Criteria with Button

### ISSUE THREAD

**Issue by hunsinger08** [olifolkerd/tabulator#680]
Is there any way to assign a button on the page to remove all headerfilter inputs?  For example a user has headerfilter input on three different columns but wants to jump back to an overall view?  Would I just have to call setData again and refresh?

**Comment by tomheaps** [comment]
Assign the `clearFilter` function to your button click?

`$("#example-table").tabulator("clearFilter", true); // true removes all header filters as well as filters which have been set programmatically`

**Comment by hunsinger08** [comment]
Awesome, thank you.  I was aware of the "clearFilter" function but did not know the true argument.  Much appreciated.
