### ISSUE TITLE
Is there a way not to have sorting in some columns?

### ISSUE THREAD

**Issue by florencioq** [olifolkerd/tabulator#682]
I do not need sorting in some columns and the sorting arrow occupies precious space in my table.
Thanks in advance and congratulations for the project.
José.

**Comment by florencioq** [comment]
Sorry for the issue. There is an option (headerSort) to control this. Thanks.

**Comment by E3V3A** [comment]
@florencioq  That doesn't work!

**Comment by olifolkerd** [comment]
@E3V3A  please checkout your original issue, #861 

I understand that you need help with your table, but please refrain from spamming every slightly related question with the same comment, your original question will be answered quickly enough.

Cheers

Oli :)
