### ISSUE TITLE
Retrieving data from JSON URL

### ISSUE THREAD

**Issue by gusboxbr** [olifolkerd/tabulator#683]
Hi Guys,

I´m newbie in tabulator and programing, but i have one question. I need to retreve a JSON XML data froma URL. I create a page like the code below, but don´t work... Can you guys save me please?

`<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script type="text/javascript" src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.3.1/css/tabulator.min.css" rel="stylesheet">
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.3.1/js/tabulator.min.js"></script>

<div id="example-table"></div>

<script type="text/javascript">
$("#example-table").tabulator({
	index:"id",
    height:205, // set height of table, this enables the Virtual DOM and improves render speed dramatically (can be any valid css height value)
    layout:"fitColumns", //fit columns to width of table (optional)
    columns:[ //Define Table Columns
        {title:"ID", field:"id"},
        {title:"Nome", field:"name"},
       
    ],
    rowClick:function(e, row){ //trigger an alert message when the row is clicked
        alert("Row " + row.getData().id + " Clicked!!!!");
    },
});
	

//load sample data into the table
$("#example-table").tabulator("setData", "https://URL TO RETRIVE THE DATA");	
</script>
`

Thanks a lot!
Gus

**Comment by olifolkerd** [comment]
Hi Gus,

I think you might be a bit confused there, JSON and XML are two entirely different ways of encoding data, it would be one or the other, not both.

Could you post a copy of the data your are returning from your server and i will try and point you in the right direction.

Cheers

Oli
