### ISSUE TITLE
Is there a way to change the background of the cell, keeping its text?

### ISSUE THREAD

**Issue by florencioq** [olifolkerd/tabulator#685]
Hi,
I am able to change the background color of the text (using html formatter). However, I'd like to change the background color of the cell. Is it possible?
Thanks in advance.

**Comment by olifolkerd** [comment]
Hey,

Yes if you return the value of the cell in the formatter you can do anything else you like before this:

```js
$("#example-table").tabulator({
    colums:[
        {title:"Age", field:"age", formatter:function(cell){
            var age = cell.getValue();
            
            //do anything you want here
            if(age < 18){
                cell.getElement().css({"background":"red"});
            }
    
            //return the original value of the cell
            return age;
        }},
    ]
});
```

**Comment by mountaindude** [comment]
Hmm, is css() a jQuery function by any chance...?
If so the code above won't work in recent(ish) Tabulator versions where jQuery is no longer  included.

How would this be done in current (4.9) version of Tabulator? @olifolkerd 

Thx
