### ISSUE TITLE
placeholder effect for editable fields?

### ISSUE THREAD

**Issue by AydinChavez** [olifolkerd/tabulator#686]
Hi!

Is it possible to add a placeholder for editable fields (input) like the standard HTML placeholder attribute for input type text 
(example: https://www.w3.org/wiki/images/5/52/Input_text02.png )

If not (yet), can this easily be added?

**Comment by tomheaps** [comment]
You could use a custom formatter to place text in the cell if the cell is empty i.e. before it is edited e.g. 

```
var placeHolder = function(cell, formatterParams) {
    var cellValue = cell.getValue();
    if (cellValue === "") {
      return "Your Placeholder Text..."
    } else {
      return cellValue
    }
  };
```

Then in your column definitions:

```
{
        title: "Title",
        field: "Field",
        editor: true,
        formatter: placeHolder,
        etc.
      },
```

**Comment by AydinChavez** [comment]
Thanks mate, seemed to work!

**Comment by harihsb** [comment]
In my case, the table data will be sent to the server. If I follow the above approach of setting the placeholder as the cell value directly, I would need to replace the placeholder by empty string before sending it to the server.

Instead, I would like to define the placeholder along with the column definition. Would this be possible ?`columns : [{title: 'City',field: 'city', editor: true, placeholder: 'Enter city'}]`

**Comment by olifolkerd** [comment]
Hey @harihsb 

You would still need to use a custom formatter to get it to display on the table.

**Comment by harihsb** [comment]
Thanks Oli, I was aware of that anyway. This is just a kind suggestion.

**Comment by 8483** [comment]
Here's a different approach to this problem: 

```js
formatter: (cell, formatterParams) => {
        let data = cell._cell.row.data;

        cell.getElement().style.cssText += `
            background-image: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' version='1.1' height='20px' width='120px'><text x='0' y='15' font-size='14' font-family='Sans,Arial' fill='black' fill-opacity='0.2'>YOUR TEXT HERE</text></svg>") !important; 
            background-repeat: no-repeat !important;
            background-position: 10px 50% !important;
        `;

        return cell.getValue();
    },
```
