### ISSUE TITLE
Unable to apply dropdown in header column

### ISSUE THREAD

**Issue by naghuntdworld** [olifolkerd/tabulator#687]
Even after applying editor, header column with dropdown filter is not working. Still can see only input filter.

**Comment by tomheaps** [comment]
Hi, you will need to post a copy of your table constructor code to help diagnose what is wrong with your table setup.

**Comment by naghuntdworld** [comment]
"use strict";
var includeColumnsInFilter = [{}];
var viewDatajson = null;

// View field SQL names
var projectDetailIdFieldName = "ProjectDetailId";
var projectNameFieldName = "ProjectName";
var sectorIdFieldName =  "SectorId";
var regionIdFieldName =  "RegionId";
var approvalStatusFieldName =  "ApprovalStatus";
var projectClassificationIdFieldName =  "ProjectClassificationId";
var projectGroupIdFieldName =  "ProjectGroupId";
var businessUnitIdFieldName =  "BusinessUnitId";
var siteMuIdFieldName =  "SiteMuId";
var categoryIdFieldName =  "CategoryId";
var submitterFieldName =  "Submitter";
var projectManagerFieldName =  "ProjectManager";
var grandTotalLCCPFieldName =  "GrandTotalLCCP";
var grandTotalLCEXPFieldName =  "GrandTotalLCEXP";
var grandTotalLCWOFieldName =  "GrandTotalLCWO";
var grandTotalLCOTFieldName =  "GrandTotalLCOT";
var totalLCFieldName =  "TotalLC";
var grandTotalLCCPFieldName =  "GrandTotalLCCP";
var grandTotalUSDCPFieldName =  "GrandTotalUSDCP";
var grandTotalUSDCPFieldName =  "GrandTotalUSDCP";
var grandTotalUSDEXPFieldName =  "GrandTotalUSDEXP";
var grandTotalUSDWOFieldName =  "GrandTotalUSDWO";
var grandTotalUSDOTFieldName =  "GrandTotalUSDOT";
var totalUSDFieldName =  "TotalUSD";
var createdDateTimeFieldName =  "CreatedDateTime";
var modifiedDateTimeFieldName =  "ModifiedDateTime";
var createdByFieldName =  "CreatedBy" ;
var modifiedByFieldName =  "ModifiedBy";
var projectStatusFieldNameFieldName =  "ProjectStatus";

var columnsJSON = [
    {
        title: "Project Detail ID", field: "ProjectDetailId", sorter: "number", headerFilter: "input", formatter: function (cell, formatParams) {
            var value = cell.getValue();
            return "<a href ='" + decodeURIComponent(ESSACapexSM.GetQueryStringParameter('SPHostUrl')) + "Site Pages/Project%20Details.aspx?PID=" + value + "' target='_blank'>" + value + "</a>";
        },
    },
    { title: "Project Name", field: projectNameFieldName, width: 150, headerFilter: "input" },
    { title: "Sector", field: sectorIdFieldName, headerFilter: "input"},
    { title: "Region", field: regionIdFieldName, headerFilter: "input", editor: selectEditor },
    { title: "Approval Status", field: approvalStatusFieldName, headerFilter: "input" },
    { title: "Project Classification", field: projectClassificationIdFieldName, headerFilter: "input" },
    { title: "Project Group", field: projectGroupIdFieldName, headerFilter: "input" },
    { title: "Business Unit", field: "BusinessUnitId", headerFilter: "input" },
    { title: "Site Mu", field: siteMuIdFieldName, headerFilter: "input" },
    { title: "Category", field: categoryIdFieldName, headerFilter: "input" },
    { title: "Submitter", field: submitterFieldName, headerFilter: "input" },
    { title: "Project Manager", field: projectManagerFieldName, headerFilter: "input" },
    { title: "GrandTotalLC CP", field: grandTotalLCCPFieldName, sorter: "number", headerFilter: "number" },
    { title: "GrandTotalLC EXP", field: grandTotalLCEXPFieldName, sorter: "number", headerFilter: "number" },
    { title: "GrandTotalLC WO", field: grandTotalLCWOFieldName, sorter: "number", headerFilter: "number" },
    { title: "GrandTotalLC OT", field: grandTotalLCOTFieldName, sorter: "number", headerFilter: "number" },
    { title: "Total LC", field: totalLCFieldName, sorter: "number", headerFilter: "number" },
    { title: "GrandTotalUSD CP", field: grandTotalUSDCPFieldName, sorter: "number", headerFilter: "number" },
    { title: "GrandTotalUSD EXP", field: grandTotalUSDEXPFieldName, sorter: "number", headerFilter: "number" },
    { title: "GrandTotalUSD WO", field: grandTotalUSDWOFieldName, sorter: "number", headerFilter: "number" },
    { title: "GrandTotalUSD OT", field: grandTotalUSDOTFieldName, sorter: "number", headerFilter: "number" },
    { title: "Total USD", field: totalUSDFieldName, sorter: "number", headerFilter: "number" },
    { title: "Created", field: createdDateTimeFieldName, sorter: "date", headerFilter: "input" },
    { title: "Modified", field: modifiedDateTimeFieldName, sorter: "date", headerFilter: "input" },
    { title: "Created By", field: createdByFieldName, editable: true, headerFilter: "input" },
    { title: "Modified By", field: modifiedByFieldName, headerFilter: "input" },
    { title: "Project Status", field: projectStatusFieldNameFieldName, headerFilter: "input" },
];

var selectEditor = function (cell, value, data) {
    //cell - the cell component for the editable cell
    //onRendered - function to call when the editor has been rendered
    //success - function to call to pass the succesfully updated value to Tabulator
    //cancel - function to call to abort the edit and return to a normal cell
    //editorParams - editorParams object set in column defintion
    
    //create and style editor
    var editor = $("<select><option value=''></option><option value='EAST'>EAST</option><option value='WESA'>WESA</option><option value='Europe HQ'>Europe HQ</option></select>");
    editor.css({
        "padding": "3px",
        "width": "100%",
        "box-sizing": "border-box",
    });

    //Set value of editor to the current value of the cell
    //editor.val(cell.getValue());

    //return the editor element
    return editor;
};


$(document).ready(function () {
    try {
        // Getting decoded JSON string
        viewDatajson = $("#content").val();

        // Checking whether string is empy or not
        if (viewDatajson !== "") {
            // Parsing to JSON object
            viewDatajson = JSON.parse(decodeURIComponent(viewDatajson).replace(/\+/g, ' '));

            // Checking whether data exists or not
            if (viewDatajson.data.length > 0) {
                // Looping columns from the result set to get the JSON to format the columns in grid
                for (var column in viewDatajson.data[0]) {
                    var columnsJSONCount = 0;
                    for (columnsJSONCount; columnsJSONCount < columnsJSON.length; columnsJSONCount++) {
                        if (columnsJSON[columnsJSONCount].field === column) {
                            // Pushing the columns to be displayed in the view
                            includeColumnsInFilter.push(columnsJSON[columnsJSONCount]);
                            break;
                        }
                    }
                }

                // Setting the options for Grid View Template
                $("#example-table").tabulator({
                    height: "500px",
                    columns: includeColumnsInFilter
                });

                // Passing the data for displaying Grid View
                $("#example-table").tabulator("setData", viewDatajson.data);
            }
            else {
                $("#message").text("Results not found!");
            }
        }
    }
    catch (ex) {
        ESSACapexSM.ExceptionMessage("Error occured. Message: " + ex.message, ex.message);
    }

**Comment by naghuntdworld** [comment]
Except header dropdown filter everything is working fine.

**Comment by olifolkerd** [comment]
if you want the header filter to your select editor you need to set ***headerFilter*** property to the editor instead of "input" in your column definition objects:

```js
headerFilter: selectEditor
```

Cheers

Oli

**Comment by naghuntdworld** [comment]
Thanks for the reply Tom. 

Even after I set "headerFilter: selectEditor", it is not working (not at all hitting "selectEditor" function).

Also, I have to pass the data to selectEditor in order to pass the dropdown HTML dynamically (different for different columns).

Please help me.

**Comment by olifolkerd** [comment]
Could you post an updated copy of your table constructor and your header filter?

If you want to pass additional parameters to the header editor you can set the ***headerFilterParams*** property with an object to pass into custom editor functions params argument.

Please have a thorough read through the (Header Filters Documentation)[http://tabulator.info/docs/3.3#header-filters] as it takes you through how to do all of this in detail.

Cheers

Oli

**Comment by naghuntdworld** [comment]
After keeping the selectEditor in document ready event it is start working. And everything is working fine. Thank you very much :)
