### ISSUE TITLE
bottomCalc sums to zero when a send nested data

### ISSUE THREAD

**Issue by florencioq** [olifolkerd/tabulator#688]
Hi,
I am using nested data to bring value and color for my cells. In this case, bottonCalc sums to zero.
Column "Total" sums perfectly, whereas other columns sum to zero.
Is it a normal behavior because of the nested data?
Thanks in advance.
José

My constructor:

                    $("#example-table").tabulator({
                        selectable:true,
                        columns:[
                            {title:"Week", field:"data"},
                            {title:"Mo", field:"1", formatter:function(cell, formatterParams){
                                    var celValue = cell.getValue()
                                    var valor = celValue.valor;
                                    cor = celValue.cor;
                                    cell.getElement().css({"background":cor});
                                    return valor;
                                }, headerSort:false, bottomCalc:"sum"},
                            {title:"Tu", field:"2", formatter:function(cell, formatterParams){
                                    var celValue = cell.getValue()
                                    var valor = celValue.valor;
                                    cor = celValue.cor;
                                    cell.getElement().css({"background":cor});
                                    return valor;
                                }, headerSort:false, bottomCalc:"sum"},
                            {title:"We", field:"3", formatter:function(cell, formatterParams){
                                    var celValue = cell.getValue()
                                    var valor = celValue.valor;
                                    cor = celValue.cor;
                                    cell.getElement().css({"background":cor});
                                    return valor;
                                }, headerSort:false, bottomCalc:"sum"},
                            {title:"Th", field:"4", formatter:function(cell, formatterParams){
                                    var celValue = cell.getValue()
                                    var valor = celValue.valor;
                                    cor = celValue.cor;
                                    cell.getElement().css({"background":cor});
                                    return valor;
                                }, headerSort:false, bottomCalc:"sum"},
                            {title:"Fr", field:"5", formatter:function(cell, formatterParams){
                                    var celValue = cell.getValue()
                                    var valor = celValue.valor;
                                    cor = celValue.cor;
                                    cell.getElement().css({"background":cor});
                                    return valor;
                                }, headerSort:false, bottomCalc:"sum"},
                            {title:"Sa", field:"6", formatter:function(cell, formatterParams){
                                    var celValue = cell.getValue()
                                    var valor = celValue.valor;
                                    cor = celValue.cor;
                                    cell.getElement().css({"background":cor});
                                    return valor;
                                }, headerSort:false, bottomCalc:"sum"},
                            {title:"Su", field:"7", formatter:function(cell, formatterParams){
                                    var celValue = cell.getValue()
                                    var valor = celValue.valor;
                                    cor = celValue.cor;
                                    cell.getElement().css({"background":cor});
                                    return valor;
                                }, headerSort:false, bottomCalc:"sum"},
                            {title:"Total", field:"total", headerSort:false, bottomCalc:"sum"},
                        ],
                    });

**Comment by olifolkerd** [comment]
Could you post a few rows of sample data so we can see what the calculations are summing?

**Comment by florencioq** [comment]
Thanks for your reply
```
[{'1': {'cor': 'rgb(102,194,164)', 'valor': 5}, '7': {'cor': 'rgb(247,252,253)', 'valor': 0}, '6': {'cor': 'rgb(35,139,69)', 'valor': 7}, '3': {'cor': 'rgb(0,109,44)', 'valor': 9}, '2': {'cor': 'rgb(35,139,69)', 'valor': 7}, '5': {'cor': 'rgb(102,194,164)', 'valor': 5}, 'total': 100, '4': {'cor': 'rgb(35,139,69)', 'valor': 8}, 'data': '2015-03'}, {'1': {'cor': 'rgb(204,236,230)', 'valor': 2}, '7': {'cor': 'rgb(229,245,249)', 'valor': 1}, '6': {'cor': 'rgb(35,139,69)', 'valor': 7}, '3': {'cor': 'rgb(35,139,69)', 'valor': 7}, '2': {'cor': 'rgb(204,236,230)', 'valor': 2}, '5': {'cor': 'rgb(65,174,118)', 'valor': 6}, 'total': 70, '4': {'cor': 'rgb(153,216,201)', 'valor': 4}, 'data': '2015-02'}, {'1': {'cor': 'rgb(247,252,253)', 'valor': 0}, '7': {'cor': 'rgb(35,139,69)', 'valor': 7}, '6': {'cor': 'rgb(153,216,201)', 'valor': 4}, '3': {'cor': 'rgb(247,252,253)', 'valor': 0}, '2': {'cor': 'rgb(247,252,253)', 'valor': 0}, '5': {'cor': 'rgb(102,194,164)', 'valor': 5}, 'total': 48, '4': {'cor': 'rgb(153,216,201)', 'valor': 4}, 'data': '2015-01'}]
```

**Comment by olifolkerd** [comment]
This is because you are trying to use the sum calculation on an object, but the sum function is only designed to work on numeric values.

in your case you should use a custom calculation function to handle this:

```js
var valorSum = function(values, data, calcParams){
    //values - array of column values
    //data - all table data
    //calcParams - params passed from the column defintion object

    var count = 0;

    values.forEach(function(value){
        if(value.valor){
            count += value.valor;
        }
    });

    return calc;
}
```

then you can use this instead of sum in the column definition:
```js
 {title:"Fr", field:"5", bottomCalc:valorSum},
```

Let me know if that helps,

Cheers

Oli

**Comment by florencioq** [comment]
It worked! Thank you very much!
