### ISSUE TITLE
Customer header filter with two widgets

### ISSUE THREAD

**Issue by mitchelljkotler** [olifolkerd/tabulator#689]
Is it possible to have two input widgets in a custom header filter?  I would like a range filter for a numeric field, allowing both a minimum and maximum filter.

**Comment by olifolkerd** [comment]
A very interesting question, i think it might be possible, i will have a play over the next couple of days and get back to you.

**Comment by mitchelljkotler** [comment]
Is this closed and fixed or closed and won't fix?

**Comment by olifolkerd** [comment]
sorry, was tidying things up and must have prematurely closed this.

I will see if i can post an example of this tomorrow, sorry for the delay in getting back to you on this one, its been a bit on the crazy busy side of late.

**Comment by mitchelljkotler** [comment]
No problem, I appreciate you looking into it

**Comment by mitchelljkotler** [comment]
Any update on this?

**Comment by git265** [comment]
Anybody able to achieve this functionality , I am also looking for data range filter

**Comment by qlj** [comment]
See the example code oli provided in answer to my question https://github.com/olifolkerd/tabulator/issues/1011

**Comment by mitchelljkotler** [comment]
Thanks!
