### ISSUE TITLE
Id or name atribute in each cell/filter input on the html generated

### ISSUE THREAD

**Issue by neorm5** [olifolkerd/tabulator#691]
Hi, 
I need to put the id or name atribute in each cell on the html generated by tabulator and in each input search filter is possible?

EXAMPLE:
`<div class="tabulator-col tabulator-sortable" role="columnheader" aria-sort="none" style="min-width: 40px; width: 158px; height: 61px;" title="ID"><div class="tabulator-col-content"><div class="tabulator-col-title">ID</div><div class="tabulator-header-filter"><div class="tabulator-arrow"></div><input style="padding: 4px; width: 100%; box-sizing: border-box;" placeholder="Filtrar..." type="search" id="ID_FILTER"></div></div><div class="tabulator-col-resize-handle"></div><div class="tabulator-col-resize-handle prev"></div></div>`

Thanks for the support

Great plugin

**Comment by vipera7** [comment]
Could we get your tabulator constructor ?

For filtering for each column you can use in your column declaration:
``` javascript
{title:"Name", field:"name", headerFilter:true}
```

Full doc http://tabulator.info/docs/3.3#header-filters
