### ISSUE TITLE
setting the height of the tabulator when it is in an invisible container

### ISSUE THREAD

**Issue by AnatolyAG** [olifolkerd/tabulator#694]
Hi Oli,
thanks for the wonderful component.
when using the following question
if you initialize the tabulator  when it is in the off container, the height and scroll bars will not be counted.
This leads to the fact that I can not initialize many tables at once, while they are hidden from the user.
in principle in the code you have to check if the container is hidden then do not calculate the height.
You only have to initialize after displaying the table.
prompts out of the situation.

**Comment by olifolkerd** [comment]
Hey @AnatolyAG,

In order for tabulator to draw itself correctly it needs to be able to calculate the height and width of its components, unfortunately DOM elements have no dimensions until they are first made visible, which means that tables that are initialised hidden will look a bit odd.

The great news is we have planned for that. as soon as you make the element visible, call the ***redraw*** function on the table and it will instantly resolve your issue:

```js
$("#example-table").tabulator("redraw", true);
```

Cheers

Oli

**Comment by AnatolyAG** [comment]
thanks It works

**Comment by HHough** [comment]
Oli,

Thank you so much for providing this amazing library.  Your documentation is very thorough and has helped me a ton.  The above fix is exactly what I needed as well, so simple.  Glad I finally decided to look and see if someone else was having the same issue.   But I really should have understood that you mention this aspect in the documentation.  

Cheer,
Heather
