### ISSUE TITLE
frozen columns and control height

### ISSUE THREAD

**Issue by lrowleyUB** [olifolkerd/tabulator#696]
Hi Oli,

It appears that we must specify a height on Tabulator if we use frozen columns. Why is this and will this change in the future? Fixed height is causing complaints on larger monitors. 

Thanks!

**Comment by lrowleyUB** [comment]
Ah nevermind - I decided to set the height dynamically and use "setHeight" on resize. Clears up the issues :-)

**Comment by olifolkerd** [comment]
you can also set the height as a percentage, it can be any valid CSS value
