### ISSUE TITLE
Tabulator not refreshing

### ISSUE THREAD

**Issue by kittos** [olifolkerd/tabulator#697]
Hi, 

When i edit my table and save the data to a json file in my server the json file saves correctly the new data, but when i alternate in my web page with diferent tabs with other tables, when i get back to the table i have saved it doesnt has the new data.

Even if i setData again..... cache maybe???  if you can help.

Sorry about the english.

**Comment by hunsinger08** [comment]
We're experiencing a similar problem.  We have tables on different tab panels (boostrap).  Only the initial active panel will have the table rendered properly.  The column headers show up on the other tab panels but the data is absent.

**Comment by olifolkerd** [comment]
Hey,

The issue you are having is setting data on a table when it isnt visible, This is because Tabulators virtual DOM needs to know the dimensions of row elements to know how to display them, but DOM elements do not have any dimensions until they are first made visible.

To get round this you need to call the ***redraw*** function on the table when it is made visible in a tab:

```js
$("#example-table").tabulator("redraw", true);
```

Let me know if that helps,

Cheers

Oli

**Comment by kittos** [comment]
I will try to explain better what's happening, let's say i have two tables each one in separated tabs, i edit one of them and after edited i call the function that saves the new data in a json file, for example in the start i have two records in that table: name: Bob (1 row), name: Marcos (2 row), then i add another row and create a new user name: Sandra (3 row) then i save into json in server.
After this i change the active tab to the other tab with another table, then i change to the tab where i made changes in, and the records that appears are only the 2 rows, i have checked the json file and has the new data, even if i set the data again it doesnt appears, after a while the record eventually apears.

**Comment by kittos** [comment]
well i guess i have solved the issue when i setData again i have to use a parameter like file.json?d=+ new Date().getTime(), maybe a cache issue, i will run some more tests and say the results.

**Comment by kittos** [comment]
No... it happen again... i really don't like when sometimes works and others don't, that makes a little difficult to get the error :)
