### ISSUE TITLE
how to make a pagination

### ISSUE THREAD

**Issue by AnatolyAG** [olifolkerd/tabulator#698]
Hi
Help me to understand
create a component

```js
$("#logs_grid").tabulator({
            height: 'calc(100% - 35px)', 
            layout: "fitColumns",
            selectable: 1,
            placeholder: "Not data",
            ajaxConfig: "POST", //ajax HTTP request type
            ajaxURL: "baseworker.php", //set url for ajax request
            ajaxSorting: true, //
            ajaxFiltering: true, //send filter data to the server instead of processing locally
            pagination: "remote", //enable remote pagination
            paginationSize: 10, //optional parameter to request a certain number of rows per page
            index: "id_log",
            columns: [//Define Table Columns
                {title: "№", field: "id_log", width: 50, align: "center"},
                {title: "user name", field: "id_user", width: 150, headerFilter: true, align: "left"},
                {title: "event", field: "log_event", width: 200, headerFilter: true, align: "left"},
                {title: "descr", field: "log_comment", headerFilter: true},
                {title: "date", field: "log_datetime", width: 150, headerFilter: true, align: "center"}
            ]
           
            , ajaxRequesting: function (url, params) {
                //url - the URL of the request
                //params - the parameters passed with the request
                var t_params = [];
                //t_params = {page: 1, size: 5, sorters: Array(0), filters: Array(0)};

//                t_params['filters'] = params['filters'];
//                t_params['page'] = params['page'];
//                t_params['size'] = params['size'];
//                t_params['sorters'] = params['sorters'];



                params['command'] = 'get_logs_all';
                params['params'] = {};
                params['params']['page'] = params['page'];
                params['params']['size'] = params['size'];
                params['params']['filters'] = params['filters'];
                params['params']['sorters'] = params['sorters'];



                return true;
            }

        });
```

in the database of 20 lines
last_page returns 20
component draws at the bottom 20 pages
**where I was mistaken?**

![default](https://user-images.githubusercontent.com/18345451/32631605-66018092-c5a9-11e7-9668-418083dc466a.png)

**Comment by olifolkerd** [comment]
you need to remove the ***paginationSize*** property from your table definition

**Comment by AnatolyAG** [comment]
I removed the 
`paginationSize: 10, // optional parameter to request a certain number of rows per pag`

now on the server leaves in the request 
`page = 1 & size = 3`
respectively, the server returns three rows
and prints 20 pages at the bottom

part of answ

`{"last_page":"20","data":[{"id_log":"1","id_user":"1","us_name":`

![default](https://user-images.githubusercontent.com/18345451/32658095-0f69d2fc-c621-11e7-9c04-3fda10a9ff02.png)

strange behavior
under google chrome ` (Version 62.0.3202.89 (Official Build) (64-bit))`
in query parameters
page: 1
size: 3
under firefox `56.0.2 (64-бит)`
page: 1
and work correct

**Comment by AnatolyAG** [comment]
under firefox
in the bottom still drawn 20 pages

**Comment by AnatolyAG** [comment]
under opera as well as google chrome

**Comment by olifolkerd** [comment]
That is because you have your table height set, so the table will always be that height

**Comment by AnatolyAG** [comment]
If I remove the height in the table definition, then the number of pages is calculated correctly?

**Comment by AnatolyAG** [comment]
It remains to find out why the page size in chrome and opera is incorrectly calculated.
At the set height and if the paginationSize property is not set, the component calculates how many rows it will fit into it and issues this quantity in the request to the server - right now all the time will be 3 although the place is for 25
in the firefox the size is always missing
