### ISSUE TITLE
How to achieve this grouping?

### ISSUE THREAD

**Issue by Rodbjartson** [olifolkerd/tabulator#704]
Not the best topic name, could not find any better(feel free to change it).

Here is my table that GROUPS by a certain ID:
![2017-11-13 12_38_12-localhost_51301_ss3_purchaseorder aspx](https://user-images.githubusercontent.com/11444201/32724857-30376810-c873-11e7-874a-05d2311b82c4.png)

Here is what I want to achieve:

![2017-11-13 12_39_11-localhost_51301_ss3_purchaseorder aspx](https://user-images.githubusercontent.com/11444201/32724875-411da6ee-c873-11e7-85e0-9b6dd95f4123.png)

In case it is not clear, these images are photoshopped haha. I want to create subcolumns so that each item of a group has its columns etc. 
Is this possible?

Also at last: My column header looks bad, because I have to style it myself with the groupheader function. Is there a way that the values can align the way they are supposed to be? Without setting margin etc

**Comment by olifolkerd** [comment]
Hey @Rodbjartson ,

Im afraid that isn't possible at the moment, Tabulator only allows for column headers at the top of the table at the moment.

Cheers

Oli

**Comment by Rodbjartson** [comment]
W

**Comment by olifolkerd** [comment]
it is on the roadmap, but wont be available till at least version 4
