### ISSUE TITLE
Responsive table

### ISSUE THREAD

**Issue by vipera7** [olifolkerd/tabulator#706]
Hey Oli,

After trying to make a nice responsive table, I saw the function `responsiveLayout:true,` but we have to hide column not really the way I want to achieve. I thought something similar to this https://datatables.net/extensions/responsive/examples/styling/bootstrap.html where the data is display verticaly.
From issue #121

Cheers

**Comment by olifolkerd** [comment]
Hey @vipera7,

This option is on the roadmap but im afraid it wont be available for a few months yet.

in the mean time you could use a custom rowFormatter or column formatter to decided how to layout the data based on the table width.

Cheers

Oli
