### ISSUE TITLE
Reciving data from json url, with ajax callback

### ISSUE THREAD

**Issue by martinl86** [olifolkerd/tabulator#709]
Hi guys i love you plugin, but i cant get to work with my data from url. 
The first problem i had,  it was expection json array but was recieving objects .

 now i am tried to create an callback,  so it will accept objects. 

My code is wrong

        $('#addButton').click(function () {

            var word = $("#<%=txtWord.ClientID%>").val();

            $("#example-table").tabulator("setData", "url");

        });

      
        //Build Tabulator
        $("#example-table").tabulator({
            ajaxResponse: function (url, params, response) {
                //url - the URL of the request
                //params - the parameters passed with the request
                //response - the JSON object returned in the body of the response.

                return response.data; //return the data property of a response json object
            },
            height: "311px",
            layout: "fitColumns",
            placeholder: "No Data Set",
            columns: [
                { title: "Name", field: "adverts.companyName", sorter: "string", width: 200 },

            ],
            rowClick: function (e, row) { //trigger an alert message when the row is clicked
                alert("Row " + row.getData().id + " Clicked!!!!");
            },
        });

**Comment by vipera7** [comment]
Hey @martinl86,

Can we see how you're encoding your data ?

**Comment by martinl86** [comment]
I am pretty new at this Jquery/Json stuf. I want to see my Json file?

**Comment by martinl86** [comment]
you*

**Comment by vipera7** [comment]
Yup, the problem is probably coming from here.

**Comment by martinl86** [comment]
okay its pretty large,  
{
	"title": "blanked out",
	"query": "http://api/cs/search/basic?country=dk&search_word=hotel&version=1.1.3",
	"totalHits": 1827,
	"totalCount": 1827,
	"startIndex": 1,
	"itemsPerPage": 25,
	"adverts": [
		{
			"eniroId": "66797761",
			"companyInfo": {
				"companyName": "Sandbjerg Gods",
				"orgNumber": "11838774",
				"cvrPNumber": "1009585482",
				"companyText": null
			},
			"address": {
				"streetName": "Sandbjergvej 102",
				"postCode": "6400",
				"postArea": "Sønderborg",
				"postBox": null
			},
			"location": {
				"coordinates": [
					{
						"longitude": 9.749616,
						"latitude": 54.950004
					},
					{
						"use": "route",
						"longitude": 9.749225,
						"latitude": 54.949747
					}
				]
			},
			"phoneNumbers": [
				{
					"type": "std",
					"phoneNumber": "73 46 52 00",
					"label": null
				}
			],
			"companyReviews": "http://www.dethitter.dk/brugeranmeldelse/f/66797761/hotel",
			"homepage": "http://api.eniro.com/proxy/homepage/uANwPf5aVK0Ohow7-elNIzis02CGN5TDk5v21Yr4fKTAL1qH1rWppbyPnWjiaUWSQCq053GVY44=",
			"facebook": null,
			"infoPageLink": "http://www.krak.dk/f/sandbjerg-gods:66797761?search_word=hotel"
		},
		{
			"eniroId": "66801935",
			"companyInfo": {
				"companyName": "Sørup Herregaard",
				"orgNumber": "27905390",
				"cvrPNumber": "1000996958",
				"companyText": null
			},
			"address": {
				"streetName": "Sørupvej 26",
				"postCode": "4100",
				"postArea": "Ringsted",
				"postBox": null
			},
			"location": {
				"coordinates": [
					{
						"longitude": 11.794362,
						"latitude": 55.386152
					},
					{
						"use": "route",
						"longitude": 11.796904,
						"latitude": 55.385955
					}
				]
			},
			"phoneNumbers": [
				{
					"type": "std",
					"phoneNumber": "57 64 30 02",
					"label": null
				}
			],
			"companyReviews": "http://www.dethitter.dk/brugeranmeldelse/f/66801935/hotel",
			"homepage": "http://api.eniro.com/proxy/homepage/uANwPf5aVK1toiNgJWhct3HytKcgibp8XdtR3bwHWQmcAYcxVhBoi-PcIlmhmNEk",
			"facebook": null,
			"infoPageLink": "http://www.krak.dk/f/sørup-herregaard:66801935?search_word=hotel"
		},
		{
			"eniroId": "65939763",
			"companyInfo": {
				"companyName": "NYBORG STRAND",
				"orgNumber": "18574985",
				"cvrPNumber": "1003504774",
				"companyText": null
			},
			"address": {
				"streetName": "Østerøvej 2",
				"postCode": "5800",
				"postArea": "Nyborg",
				"postBox": null
			},
			"location": {
				"coordinates": [
					{
						"longitude": 10.811264,
						"latitude": 55.317877
					},
					{
						"use": "route",
						"longitude": 10.812503,
						"latitude": 55.318002
					}
				]
			},
			"phoneNumbers": [
				{
					"type": "std",
					"phoneNumber": "65 31 31 31",
					"label": null
				}
			],
			"companyReviews": "http://www.dethitter.dk/brugeranmeldelse/f/65939763/hotel",
			"homepage": "http://api.eniro.com/proxy/homepage/uANwPf5aVK3zvCZaY19iLtX6G-rsrLikojAW28ov7X7ft9hjh8qeKO7hAb3Iqc8HP1fYjNPIjZ0=",
			"facebook": null,
			"infoPageLink": "http://www.krak.dk/f/nyborg-strand:65939763?search_word=hotel"
		},
		{
			"eniroId": "66851267",
			"companyInfo": {
				"companyName": "Hotel Outrup",
				"orgNumber": "28907419",
				"cvrPNumber": "1015152490",
				"companyText": null
			},
			"address": {
				"streetName": "Jernbanegade 2",
				"postCode": "6855",
				"postArea": "Outrup",
				"postBox": null
			},
			"location": {
				"coordinates": [
					{
						"longitude": 8.345174,
						"latitude": 55.71816
					},
					{
						"use": "route",
						"longitude": 8.345327,
						"latitude": 55.718101
					}
				]
			},
			"phoneNumbers": [
				{
					"type": "std",
					"phoneNumber": "75 25 18 00",
					"label": null
				}
			],
			"companyReviews": "http://www.dethitter.dk/brugeranmeldelse/f/66851267/hotel",
			"homepage": "http://api.eniro.com/proxy/homepage/uANwPf5aVK162YtuxRF3Tg7Hfz3lpsSVRJikohljLPdrmC7lwkaeBbHyM2lH-DXgU67X3Fa0rTo=",
			"facebook": null,
			"infoPageLink": "http://www.krak.dk/f/hotel-outrup:66851267?search_word=hotel"
		},
		{
			"eniroId": "67023391",
			"companyInfo": {
				"companyName": "Skanderborg Park ApS",
				"orgNumber": "34699356",
				"cvrPNumber": "1017911550",
				"companyText": null
			},
			"address": {
				"streetName": "Skovsvinget 10",
				"postCode": "8660",
				"postArea": "Skanderborg",
				"postBox": null
			},
			"location": {
				"coordinates": [
					{
						"longitude": 9.95407,
						"latitude": 56.037251
					},
					{
						"use": "route",
						"longitude": 9.954066,
						"latitude": 56.037253
					}
				]
			},
			"phoneNumbers": [
				{
					"type": "std",
					"phoneNumber": "89 93 33 10",
					"label": null
				}
			],
			"companyReviews": "http://www.dethitter.dk/brugeranmeldelse/f/67023391/hotel",
			"homepage": "http://api.eniro.com/proxy/homepage/uANwPf5aVK2F1cq2vstT0hf2Gndkn937NJQ9-lzN1e4bnG3rEMGauw5wyF2TUBbBaPxyEnuE9QAfv04LgXc4mQ==",
			"facebook": null,
			"infoPageLink": "http://www.krak.dk/f/skanderborg-park-aps:67023391?search_word=hotel"
		},
		{
			"eniroId": "66294034",
			"companyInfo": {
				"companyName": "Den Gamle Grænsekro",
				"orgNumber": "13146381",
				"cvrPNumber": "1000508822",
				"companyText": null
			},
			"address": {
				"streetName": "Koldingvej 51",
				"postCode": "6070",
				"postArea": "Christiansfeld",
				"postBox": null
			},
			"location": {
				"coordinates": [
					{
						"longitude": 9.4805104,
						"latitude": 55.3803156
					},
					{
						"use": "route",
						"longitude": 9.4805104,
						"latitude": 55.3803156
					}
				]
			},
			"phoneNumbers": [
				{
					"type": "std",
					"phoneNumber": "75 57 32 18",
					"label": null
				}
			],
			"companyReviews": "http://www.dethitter.dk/brugeranmeldelse/f/66294034/hotel",
			"homepage": "http://api.eniro.com/proxy/homepage/uANwPf5aVK3puF0hLgg2Wfb63m0gtF-DyHxL52a-bioLWnAE9U2wJbl0Siyn4namcHtis9o9mPE=",
			"facebook": null,
			"infoPageLink": "http://www.krak.dk/f/den-gamle-grænsekro:66294034?search_word=hotel"
		},

**Comment by vipera7** [comment]
Your json data are not valid. (https://jsonformatter.curiousconcept.com/), you're not sending an array,
 and you have only one column in your tabulator build.

**Comment by martinl86** [comment]
Ok it is valid i was not sending the whole json file, because it's so large :) But ok thanks
