### ISSUE TITLE
rowFormatter: can change position of parametes? 

### ISSUE THREAD

**Issue by hohozhao** [olifolkerd/tabulator#71]
Hi @olifolkerd ,

Almost all the other functions have parameter sequence "data" before "row", except rowFormatter().
What I request is to swap "data" and "row" position, but it may affect other users who may already adopted it from current/old versions.
```
                //apply row formatter
                if (self.options.rowFormatter) {
                    $(".tabulator-row", self.table).each(function() {
                        //allow row contents to be replaced with custom DOM elements
                        var newRow = self.options.rowFormatter($(this).data("data"), $(this)); //HoHo@2016-10-10

                        if (newRow) {
                            $(this).html(newRow);
                        }
                    });
                }
            }

```

**Comment by olifolkerd** [comment]
While i understand where you are coming from, this was done for a specific reason.

All of the other functions are about data manipulation or specific representations of the data, therefore the data was more contextually relevant than the DOM objects.

The rowFormatter is primarily about altering the look of the row, the data is just a guide if you need it, therefore the row object came first.

**Comment by hohozhao** [comment]
Understand and learned. Often I am negligent and overlook required parameters and optional ones.  When I program, I know it, but when I look into others', negligent.

> 
While i understand where you are coming from, this was done for a specific reason.

Is this related to where I am coming from? ;D interesting to know!
