### ISSUE TITLE
sparklines do not work

### ISSUE THREAD

**Issue by sourrounder** [olifolkerd/tabulator#712]
Hello,
soemhow the sparklines don't work, if using the code in your docu.

It isn't an issue of the browser oder sparkline.js. It has somethin to do with the docu.
I tried sparkline.js with jquery the way, the sparkline page exlains. It works great.

But when i youse your formatters as desribed with code example on http://tabulator.info/examples/3.3?#formatters sparklines, theres nothing but a table with a correct header but no data. Everything is dark grey in data rows.

Tried it several times, no change.

Thanks for the great script.

**Comment by olifolkerd** [comment]
Hey @sourrounder ,

Could you post a copy of the table constructor code that you are having trouble with so i can recommend a solution.

Cheers

Oli

**Comment by sourrounder** [comment]
Here's my table builder, 1:1 the same as in your online documentation. The header works, table date is dark grey. Several changes in code solve the problem, so i went back to the original. 

Under the code you find the code from Github sparkline, which is working fine. Both codes are in different php-files. Both use same libraries. Browser: FF 54.01, Explorer 11.674

-----------------------------------------------------
EO Code Tabulator
-----------------------------------------------------

        <div id="example-table"></div>

<script>
//Formatter to generate line chart
var lineFormatter = function(cell, formatterParams){
    setTimeout(function(){ //give cell enough time to be added to the DOM before calling sparkline formatter
        cell.getElement().sparkline(cell.getValue(), {width:"100%", type:"line", disableTooltips:true});
    }, 10);
};

//generate bar chart
var barFormatter = function(cell, formatterParams){
    setTimeout(function(){ //give cell enough time to be added to the DOM before calling sparkline formatter
        cell.getElement().sparkline(cell.getValue(), {width:"100%", type:"bar", barWidth:14, disableTooltips:true});
    }, 10);
};

//generate discrete chart
var tristateFormatter = function(cell, formatterParams){
    setTimeout(function(){ //give cell enough time to be added to the DOM before calling sparkline formatter
        cell.getElement().sparkline(cell.getValue(), {width:"100%", type:"tristate", barWidth:14, disableTooltips:true});
    }, 10);
};


//generate box plot
var boxFormatter = function(cell, formatterParams){
    setTimeout(function(){ //give cell enough time to be added to the DOM before calling sparkline formatter
        cell.getElement().sparkline(cell.getValue(), {width:"100%", type:"box", disableTooltips:true});
    }, 10);
};

//Sample Data with array values for graph fields
var sparkData = [
    {id:1, name:"Oli Bob", line:[1, 20, 5, 3, 10, 13, 17, 15, 9, 11], bar:[1, 20, 5, 3, 10, 13, 17, 15, 9, 11], tristate:[1, 20, -5, -3, 10, 13, 0, 15, 9, 11], box:[1, 20, 5, 3, 10, 13, 17, 15, 9, 11]},
    {id:2, name:"Mary May", line:[10, 12, 14, 16, 13, 9, 7, 11, 10, 13], bar:[10, 12, 14, 16, 13, 9, 7, 11, 10, 13], tristate:[-10, 12, 14, 16, 13, 9, 7, 0, 10, 13], box:[10, 12, 14, 16, 13, 9, 7, 11, 10, 13]},
    {id:3, name:"Christine Lobowski", line:[1, 2, 5, 4, 1, 16, 4, 2, 1, 3], bar:[1, 2, 5, 4, 1, 16, 4, 2, 1, 3], tristate:[1, 2, 5, 0, 1, 16, 4, 2, 1, 3], box:[1, 2, 5, 4, 1, 16, 4, 2, 1, 3]},
    {id:4, name:"Brendon Philips", line:[3, 7, 9, 1, 4, 8, 2, 6, 4, 2], bar:[3, 7, 9, 1, 4, 8, 2, 6, 4, 2], tristate:[3, 7, 9, 1, 4, 8, 2, 6, 4, 2], box:[3, 7, 9, 1, 4, 8, 2, 6, 4, 2]},
    {id:5, name:"Margret Marmajuke", line:[1, 3, 1, 3, 3, 1, 1, 3, 1, 3], bar:[1, 3, 1, 3, 3, 1, 1, 3, 1, 3], tristate:[1, -3, 1, 3, -3, 1, -1, 3, 1, 3], box:[1, 3, 1, 3, 3, 1, 1, 3, 1, 3]},
    {id:6, name:"Frank Harbours", line:[20, 17, 15, 11, 16, 9, 12, 14, 20, 12], bar:[20, 17, 15, 11, 16, 9, 12, 14, 20, 12], tristate:[20, 17, 15, 11, 16, -9, 12, 14, 20, 12], box:[20, 17, 15, 11, 16, 9, 12, 14, 20, 12]},
    {id:7, name:"Jamie Newhart", line:[11, 7, 6, 12, 14, 13, 11, 10, 9, 6], bar:[11, 7, 6, 12, 14, 13, 11, 10, 9, 6], tristate:[11, 7, 6, -12, 1-13, 11, 10, 9, 6], box:[11, 7, 6, 12, 14, 13, 11, 10, 9, 6]},
    {id:8, name:"Gemma Jane", line:[4, 17, 11, 12, 0, 5, 12, 14, 18, 11], bar:[4, 17, 11, 12, 0, 5, 12, 14, 18, 11], tristate:[4, 17, 11, -12, 0, 5, 12, -14, 18, 11], box:[4, 17, 11, 12, 0, 5, 12, 14, 18, 11]},
    {id:9, name:"Emily Sykes", line:[11, 15, 19, 20, 17, 16, 16, 5, 3, 2], bar:[11, 15, 19, 20, 17, 16, 16, 5, 3, 2], tristate:[11, 15, 19, -20, 17, 16, 16, -5, 3, 2], box:[11, 15, 19, 20, 17, 16, 16, 5, 3, 2]},
    {id:10, name:"James Newman", line:[1, 2, 3, 4, 5, 4, 2, 5, 9, 8], bar:[1, 2, 3, 4, 5, 4, 2, 5, 9, 8], tristate:[1, 2, 0, -4, -5, -4, 2, 5, 9, 8], box:[1, 2, 3, 4, 5, 4, 2, 5, 9, 8]},
];


//Table Constructor
$("#example-table").tabulator({
    height:"311px",
    columns:[
        {title:"Name", field:"name", width:190},
        {title:"Line Chart", field:"line", width:160, formatter:lineFormatter},
        {title:"Bar Chart", field:"bar", width:160, formatter:barFormatter},
        {title:"Tristate Chart", field:"tristate", width:160, formatter:tristateFormatter},
        {title:"Box Plot", field:"box", width:160, formatter:boxFormatter},
    ],
});
</script>

-----------------------------------------------------
EO Code Tabulator
-----------------------------------------------------
BO Code from sparkline
-----------------------------------------------------
    $(function() {
        /** This code runs when everything has been loaded on the page */
        /* Inline sparklines take their values from the contents of the tag */
        $('.inlinesparkline').sparkline(); 

        /* Sparklines can also take their values from the first argument 
        passed to the sparkline() function */
        var myvalues = [10,8,5,7,4,4,1];
        $('.dynamicsparkline').sparkline(myvalues);

        /* The second argument gives options such as chart type */
        $('.dynamicbar').sparkline(myvalues, {type: 'bar', barColor: 'green'} );

        /* Use 'html' instead of an array of values to pass options 
        to a sparkline with data in the tag */
        $('.inlinebar').sparkline('html', {type: 'bar', barColor: 'red'} );
    });
    </script>
</head>
<body>

<p>
Inline Sparkline: <span class="inlinesparkline">1,4,4,7,5,9,10</span>.
</p>
<p>
Sparkline with dynamic data: <span class="dynamicsparkline">Loading..</span>
</p>
<p>
Bar chart with dynamic data: <span class="dynamicbar">Loading..</span>
</p>
<p>
Bar chart with inline data: <span class="inlinebar">1,3,4,5,3,5</span>
</p>

-----------------------------------------------------
EO Code from sparkling
-----------------------------------------------------

Thanks!

**Comment by sourrounder** [comment]
Screenshop of both tables:

![grafik](https://user-images.githubusercontent.com/33666879/32829510-9337e77a-c9f2-11e7-9636-82af464998b1.png)

**Comment by olifolkerd** [comment]
Hey @sourrounder 

You don't appear to be loading your table data into your table at any point, which would explain why there are no rows.

```js
$("#example-table").tabulator("setData", sparkData);
```

**Comment by sourrounder** [comment]
Thanks for your quick response!

I still have no table working as desired. Maybe m'm just to blind to see ...

Of course i tried your table constructor 
$("#example-table").tabulator("setData", sparkData);
but without any success: instead of a dark grey table i get a whole white browser page.

By the way, here is a screenshot from your homepage with your sample code, which i used with different table constructors etc. If i use tables without sparkline, everything in tabulator works fine. 

URL:
![grafik](https://user-images.githubusercontent.com/33666879/32894333-d55e6cce-cadc-11e7-9b2e-bbc654d8cc4c.png)



![grafik](https://user-images.githubusercontent.com/33666879/32894125-2b81d268-cadc-11e7-8b8a-2c36e27ce59b.png)

![grafik](https://user-images.githubusercontent.com/33666879/32894375-ed52e38c-cadc-11e7-9f53-7b46c2f045dd.png)

**Comment by olifolkerd** [comment]
are you getting any errors in your developer console?

**Comment by sourrounder** [comment]
Oh, didn't answer you, because i thought i already did. It seems, i forget to close an send my already written comment. Maybe i made same kind of careless mistake with your demo-code.

So i tried your table-constructor once more, with same negative result. When i use the table constructor from you demo-code i get a grey data-table, but with correct column header.

When i use the modified table-constructor you offered here ($("#example-table").tabulator("setData", sparkData); i get a totaly white page.

So i tried to find the mistake with my given tools, Firefoxes Fresh Dom Tree View and Firefoxes Firebug. As far as i see, there is no error found.

The librares are correct loaded, i use bootstrap, jquery, tabulator and sparklines. Maybe the habe to be in a certain order. But i tested several configurations withour success.

The versions of these libraries work together as expected. The sparkline work for itself correct (see above) as well as tabulator. Both within bootstrap.

I would like to please you, to test your demo-code from your page http://tabulator.info/examples/3.3?#formatters. Can you please insert this code in a vanilla page for testing? Maybe there is an error in that code.

Thanks!

**Comment by sourrounder** [comment]
Oh, didn't answer you, because i thought i already did. It seems, i forget to close an send my already written comment. Maybe i made same kind of careless mistake with your demo-code.

So i tried your table-constructor once more, with same negative result. When i use the table constructor from you demo-code i get a grey data-table, but with correct column header.

When i use the modified table-constructor you offered here ($("#example-table").tabulator("setData", sparkData); i get a totaly white page.

So i tried to find the mistake with my given tools, Firefoxes Fresh Dom Tree View and Firefoxes Firebug. As far as i see, there is no error found.

The librares are correct loaded, i use bootstrap, jquery, tabulator and sparklines. Maybe the habe to be in a certain order. But i tested several configurations withour success.

The versions of these libraries work together as expected. The sparkline work for itself correct (see above) as well as tabulator. Both within bootstrap.

I would like to please you, to test your demo-code from your page http://tabulator.info/examples/3.3?#formatters. Can you please insert this code in a vanilla page for testing? Maybe there is an error in that code.

Thanks!

**Comment by sourrounder** [comment]
DO NOT CLOSE (closed by mistake!)

Oh, didn't answer you, because i thought i already did. It seems, i forget to close an send my already written comment. Maybe i made same kind of careless mistake with your demo-code.

So i tried your table-constructor once more, with same negative result. When i use the table constructor from you demo-code i get a grey data-table, but with correct column header.

When i use the modified table-constructor you offered here ($("#example-table").tabulator("setData", sparkData); i get a totaly white page.

So i tried to find the mistake with my given tools, Firefoxes Fresh Dom Tree View and Firefoxes Firebug. As far as i see, there is no error found.

The librares are correct loaded, i use bootstrap, jquery, tabulator and sparklines. Maybe the habe to be in a certain order. But i tested several configurations withour success.

The versions of these libraries work together as expected. The sparkline work for itself correct (see above) as well as tabulator. Both within bootstrap.

I would like to please you, to test your demo-code from your page http://tabulator.info/examples/3.3?#formatters. Can you please insert this code in a vanilla page for testing? Maybe there is an error in that code.

Thanks!

**Comment by sourrounder** [comment]
We can close this one.
Don't know why, but everything works now.

Just changed a few more times the way i included the liberies ... 

Sorry about that.

But I'm happy, to get it done at least. THANK YOU!

**Comment by Rodo1982** [comment]
Here you have a complete example which is definitely working:

```html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>


    <link href="https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.5.2/css/tabulator.min.css" rel="stylesheet">
    
</head>
<body>

    <!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.2.1.min.js" ></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" ></script>

  <!-- Bootstrap Core JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" ></script>
  <script src="http://tabulator.info/js/tabulator/3.5/tabulator.min.js"></script>

  <script src="http://tabulator.info/js/sparkline.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.js"></script>

  <div id="example-table2"></div>

 <script type="text/javascript">
	$("#example-table2").ready(function() {

    var barFormatter = function(cell, formatterParams){
        setTimeout(function(){ //give cell enough time to be added to the DOM before calling sparkline formatter
            cell.getElement().sparkline(cell.getValue(), {width:"100%", type:"bar", barWidth:'14', disableTooltips:false, barColor:'#7fff00'});
        }, 10);
    };

	$("#example-table2").tabulator({
	    data:tabledata,
	    layout:"fitColumns", //fit columns to width of table (optional)
	    columns:[ //Define Table Columns
                     { "title":"rS", "field":"rS",},
                     { "title":"rD", "field":"rD", },
                     { "title":"rN", "field":"rN", },
                     { "title":"pppp", "field":"pppp", },
                     { "title":"pY", "field":"pY", "formatter":"money"  },
                     { "title":"bara", "field":"bara", "formatter":barFormatter},
	    ],
	    tooltips:function(cell){
        return  cell.getColumn().getField() + ":" + cell.getValue(); //return cells "field:value";
    },
    });

	var tabledata = [

 { "id":"1", "rS":"Testroute1", "rD":"2017-06-01", "rN":"12:00", "pppp":"5", "pY":"640000.0", "bara":[0, 64]},
 { "id":"2", "rS":"Testroute3", "rD":"2018-06-01", "rN":"12:00", "pppp":"0", "pY":"None", "bara":[]},
 { "id":"3", "rS":"Testroute1", "rD":"2017-01-01", "rN":"12:00", "pppp":"8", "pY":"62.5", "bara":[20, 120, 90, 190]},
 { "id":"4", "rS":"Testroute2", "rD":"2018-01-01", "rN":"12:00", "pppp":"5", "pY":"50.0", "bara":[50, 50]},

	];

    $("#example-table2").tabulator("setData", tabledata);

});
</script>



</body>
</html>
```
