### ISSUE TITLE
Exporting table to xlsx - where to find formatting parameters?

### ISSUE THREAD

**Issue by ekoslav** [olifolkerd/tabulator#714]
Where can I find information on how to format the excel file, like setting the row color, font size / color, etc?

I've followed the documentation, and managed to get the xslx download, but it comes up almost the same as csv -  just the cell value information.

Also it took me some time to find out that xlsx.full.min.js library is needed. Maybe a note next to the example can be placed  ?

**Comment by olifolkerd** [comment]
Hey @ekoslav ,

at the moment the inbuilt xlsx file formatter only produces simple tables with no formatting, you would need to create a custom file formatter to do this. see the [Download Documentation](http://tabulator.info/docs/3.3#download) for more information on how to do this

there is already a note in the documentation "xlsx - Excel File (Requires the SheetJS Library)" in the list, are you talking about the examples page?

**Comment by ekoslav** [comment]
I've figured it out by looking at the source of the example page - then after I've noticed it in the detailed documentation.
Would it make sense to have this:
 
<script src="//rawgit.com/SheetJS/js-xlsx/master/dist/xlsx.full.min.js"></script>
<div id="example-table"></div>

to the "View source" part of the demo, since it is an external requirement?

**Comment by olifolkerd** [comment]
I will have a look at making it clearer in the example that it is dependant on a 3rd part library

Cheers

Oli
