### ISSUE TITLE
Callback issue 

### ISSUE THREAD

**Issue by mariopena** [olifolkerd/tabulator#715]
Let me start by saying this is an incredible project!

Thanks so much for sharing this!

I am having an issue with Callbacks when trying to retrieve cell data.

I am getting the following error:

      Row [object Object] Clicked!!!!

Do you have any suggestions?

**Comment by olifolkerd** [comment]
Hey @mariopena ,

Thanks for your kind words, it is always great to hear Tabulator is appreciated.

Could you post a copy of the code for callback you are using so i can advise on where the error may be.

Cheers

Oli

**Comment by mariopena** [comment]
Here is the relevant parts.

Let me know if you need more

NOTE: $json_complete is a PHP variable loads the actual data

<article>
    <div id="example-table">
        <div class="loader"><i class="fa fa-spinner fa-pulse fa-fw"></i><div><h1>An Error has occured!</h1></div></div>
    </div>
</article>
 
<script type="text/javascript">
   
    //sample data to be used in all tabulators
    var tabledata = [
         $json_complete
    ];
    
    //Callbacks Example
    $("#example-table").tabulator({
        fitColumns:true,
        data:tabledata,
        columns:[
            {title:"SUBMID", field:"SUBMID", width:100, sorter:"string", onClick:function(e, cell, val, data){alert("cell clicked - " + val)}},
            {title:"Job Name", field:"JOBNAME", sorter:"string", width:400},
            {title:"Docs", field:"TOTALTOPRINT", sorter:"number", align:"right", width:125},
            {title:"Printed", field:"TOTALPRINTED", formatter:"number", align:"right", width:100},
            {title:"Inserted", field:"TOTALINSERTED", sorter:"number", align:"right", width:125},
            {title:"Receive Date", field:"CREATEDDATE", sorter:"date"},
        ],
        rowClick:function(value, data, cell, row, options){
            alert("Row " + value + " Clicked!!!!")
        },
        rowContext:function(e, id, data, row){
            alert("Row " + id + " Context Clicked!!!!")
        },
    });

 </script>

**Comment by mariopena** [comment]
Crap! how do I make that more readable?

**Comment by mariopena** [comment]
```
<article>
    <div id="example-table">
        <div class="loader"><i class="fa fa-spinner fa-pulse fa-fw"></i><div><h1>An Error has occured!</h1></div></div>
    </div>
</article>
 
<script type="text/javascript">
   
    //sample data to be used in all tabulators
    var tabledata = [
         $json_complete
    ];
    
    //Callbacks Example
    $("#example-table").tabulator({
        fitColumns:true,
        data:tabledata,
        columns:[
            {title:"SUBMID", field:"SUBMID", width:100, sorter:"string", onClick:function(e, cell, val, data){alert("cell clicked - " + val)}},
            {title:"Job Name", field:"JOBNAME", sorter:"string", width:400},
            {title:"Docs", field:"TOTALTOPRINT", sorter:"number", align:"right", width:125},
            {title:"Printed", field:"TOTALPRINTED", formatter:"number", align:"right", width:100},
            {title:"Inserted", field:"TOTALINSERTED", sorter:"number", align:"right", width:125},
            {title:"Receive Date", field:"CREATEDDATE", sorter:"date"},
        ],
        rowClick:function(value, data, cell, row, options){
            alert("Row " + value + " Clicked!!!!")
        },
        rowContext:function(e, id, data, row){
            alert("Row " + id + " Context Clicked!!!!")
        },
    });

 </script>
```

**Comment by mariopena** [comment]
NOTE: the $json_complete is a PHP variable that holds all of the data.

I am also getting that error even when I use the full Callbacks example from your site so I am wondering if I am missing a javascript function or library.

**Comment by olifolkerd** [comment]
which version of tabulator are you using? that looks like a very old table constructor

**Comment by mariopena** [comment]
I downloaded 3.3

**Comment by mariopena** [comment]
when I try using this format it does not load at all:

``
    $("#example-table-callbacks").closest("article").on("build", function(){

    //Callbacks Example
    $("#example-table-callbacks").tabulator({
        height:"311px",
        fitColumns:true,
        columns:[
        {title:"Name", field:"name", sorter:"string", width:150},
        {title:"Progress", field:"progress", sorter:"number", align:"right", formatter:"progress"},
        {title:"Gender", field:"gender", width:100, sorter:"string", onClick:function(e, cell, val, data){alert("cell clicked - " + val)}},
        {title:"Rating", field:"rating", formatter:"star", align:"center", width:100},
        {title:"Favourite Color", field:"col", sorter:"string", sortable:false},
        {title:"Date Of Birth", field:"dob", sorter:"date", align:"center"},
        {title:"Driver", field:"car", align:"center", formatter:"tickCross", sorter:"boolean"},
        ],
        rowClick:function(e, id, data, row){
            alert("Row " + id + " Clicked!!!!")
        },
        rowContext:function(e, id, data, row){
            alert("Row " + id + " Context Clicked!!!!")
        },
    });

    $("#example-table-callbacks").tabulator("setData", tabledata);

    });
...

**Comment by mariopena** [comment]
this constructor*

**Comment by mariopena** [comment]
Here is the version I have with the other contructor:

**Comment by mariopena** [comment]
...
<article>
    <div id="example-table">
        <div class="loader"><i class="fa fa-spinner fa-pulse fa-fw"></i><div><h1>An Error has occured!</h1></div></div>
    </div>
</article>
 
<script type="text/javascript">
   
    //sample data to be used in all tabulators
    var tabledata = [
         $json_complete
    ];
    
    $("#example-table").closest("article").on("build", function(){
    
            //Callbacks Example
            $("#example-table").tabulator({
                fitColumns:true,
                data:tabledata,
                columns:[
                    {title:"SUBMID", field:"SUBMID", width:100, sorter:"string", onClick:function(e, cell, val, data){alert("cell clicked - " + val)}},
                    {title:"Job Name", field:"JOBNAME", sorter:"string", width:400},
                    {title:"Docs", field:"TOTALTOPRINT", sorter:"number", align:"right", width:125},
                    {title:"Printed", field:"TOTALPRINTED", formatter:"number", align:"right", width:100},
                    {title:"Inserted", field:"TOTALINSERTED", sorter:"number", align:"right", width:125},
                    {title:"Receive Date", field:"CREATEDDATE", sorter:"date"},
                ],
                rowClick:function(value, data, cell, row, options){
                    alert("Row " + value + " Clicked!!!!")
                },
                rowContext:function(e, id, data, row){
                    alert("Row " + id + " Context Clicked!!!!")
                },
            });
            
            
            $("#example-table").tabulator("setData", tabledata);

    });

 </script>
...

**Comment by mariopena** [comment]
``
<article>
    <div id="example-table">
        <div class="loader"><i class="fa fa-spinner fa-pulse fa-fw"></i><div><h1>An Error has occured!</h1></div></div>
    </div>
</article>
 
<script type="text/javascript">
   
    //sample data to be used in all tabulators
    var tabledata = [
         $json_complete
    ];
    
    $("#example-table").closest("article").on("build", function(){
    
            //Callbacks Example
            $("#example-table").tabulator({
                fitColumns:true,
                data:tabledata,
                columns:[
                    {title:"SUBMID", field:"SUBMID", width:100, sorter:"string", onClick:function(e, cell, val, data){alert("cell clicked - " + val)}},
                    {title:"Job Name", field:"JOBNAME", sorter:"string", width:400},
                    {title:"Docs", field:"TOTALTOPRINT", sorter:"number", align:"right", width:125},
                    {title:"Printed", field:"TOTALPRINTED", formatter:"number", align:"right", width:100},
                    {title:"Inserted", field:"TOTALINSERTED", sorter:"number", align:"right", width:125},
                    {title:"Receive Date", field:"CREATEDDATE", sorter:"date"},
                ],
                rowClick:function(value, data, cell, row, options){
                    alert("Row " + value + " Clicked!!!!")
                },
                rowContext:function(e, id, data, row){
                    alert("Row " + id + " Context Clicked!!!!")
                },
            });
            
            
            $("#example-table").tabulator("setData", tabledata);

    });

 </script>
``

**Comment by mariopena** [comment]
```
<article>
    <div id="example-table">
        <div class="loader"><i class="fa fa-spinner fa-pulse fa-fw"></i><div><h1>An Error has occured!</h1></div></div>
    </div>
</article>
 
<script type="text/javascript">
   
    //sample data to be used in all tabulators
    var tabledata = [
         $json_complete
    ];
    
    $("#example-table").closest("article").on("build", function(){
    
            //Callbacks Example
            $("#example-table").tabulator({
                fitColumns:true,
                data:tabledata,
                columns:[
                    {title:"SUBMID", field:"SUBMID", width:100, sorter:"string", onClick:function(e, cell, val, data){alert("cell clicked - " + val)}},
                    {title:"Job Name", field:"JOBNAME", sorter:"string", width:400},
                    {title:"Docs", field:"TOTALTOPRINT", sorter:"number", align:"right", width:125},
                    {title:"Printed", field:"TOTALPRINTED", formatter:"number", align:"right", width:100},
                    {title:"Inserted", field:"TOTALINSERTED", sorter:"number", align:"right", width:125},
                    {title:"Receive Date", field:"CREATEDDATE", sorter:"date"},
                ],
                rowClick:function(value, data, cell, row, options){
                    alert("Row " + value + " Clicked!!!!")
                },
                rowContext:function(e, id, data, row){
                    alert("Row " + id + " Context Clicked!!!!")
                },
            });
            
            
            $("#example-table").tabulator("setData", tabledata);

    });

 </script>
```

**Comment by mariopena** [comment]
Forgot to remove the data:tabledata element! 

```
<article>
    <div id="example-table">
        <div class="loader"><i class="fa fa-spinner fa-pulse fa-fw"></i><div><h1>An Error has occured!</h1></div></div>
    </div>
</article>
 
<script type="text/javascript">
   
    //sample data to be used in all tabulators
    var tabledata = [
         $json_complete
    ];
    
    $("#example-table").closest("article").on("build", function(){
    
            //Callbacks Example
            $("#example-table").tabulator({
                fitColumns:true,
                columns:[
                    {title:"SUBMID", field:"SUBMID", width:100, sorter:"string", onClick:function(e, cell, val, data){alert("cell clicked - " + val)}},
                    {title:"Job Name", field:"JOBNAME", sorter:"string", width:400},
                    {title:"Docs", field:"TOTALTOPRINT", sorter:"number", align:"right", width:125},
                    {title:"Printed", field:"TOTALPRINTED", formatter:"number", align:"right", width:100},
                    {title:"Inserted", field:"TOTALINSERTED", sorter:"number", align:"right", width:125},
                    {title:"Receive Date", field:"CREATEDDATE", sorter:"date"},
                ],
                rowClick:function(value, data, cell, row, options){
                    alert("Row " + value + " Clicked!!!!")
                },
                rowContext:function(e, id, data, row){
                    alert("Row " + id + " Context Clicked!!!!")
                },
            });
            
            
            $("#example-table").tabulator("setData", tabledata);

    });

 </script>
```

**Comment by olifolkerd** [comment]
the constructor your are posting looks like it is from version 2.x, there have been a load of updates to the system in 3, so you will need to update your constructor, also all callbacks are now passed [Component Objects](http://tabulator.info/docs/3.3#components) which is why you are getting the error.

Don't use the build event from the examples page, that is not part of any example, it is used to load the tables in the order they are viewed and not all at once, it will not work outside of the example site.

The following is an updated version of your constructor, you will notice that the ***fitColumns*** property has been replaced with ***layout*** and the ***onClick*** callback is now ***cellClick*** and uses the ***getValue*** function on the cell component to get the cells value:

```js
$("#example-table-callbacks").tabulator({
    height:"311px",
    layout:"fitColumns",
    columns:[
    {title:"Name", field:"name", sorter:"string", width:150},
    {title:"Progress", field:"progress", sorter:"number", align:"right", formatter:"progress"},
    {title:"Gender", field:"gender", width:100, sorter:"string", cellClick:function(e, cell){alert("cell clicked - " + cell.getValue())}},
    {title:"Rating", field:"rating", formatter:"star", align:"center", width:100},
    {title:"Favourite Color", field:"col", sorter:"string", sortable:false},
    {title:"Date Of Birth", field:"dob", sorter:"date", align:"center"},
    {title:"Driver", field:"car", align:"center", formatter:"tickCross", sorter:"boolean"},
    ],
    rowClick:function(e, id, data, row){
        alert("Row " + id + " Clicked!!!!")
    },
    rowContext:function(e, id, data, row){
        alert("Row " + id + " Context Clicked!!!!")
    },
});

```
I would strongly suggest reading through the documentation or at the very lease the release news articles on the [Tabulator Website](http://tabulator.info) to catch up on the hundreds of great changes in th last few releases.

Cheers

Oli

**Comment by olifolkerd** [comment]
i have just updated the above example as i forgot to update the ***rowClick*** and ***rowContext***, it is worth noting that the ***getIndex*** function will return the value of the index field of the row data (by default the "id" field), you must set this value otherwise an undefined value will be returned

**Comment by mariopena** [comment]
That is awesome! It worked like a champ!

Have a great day!
