### ISSUE TITLE
Do not move column header

### ISSUE THREAD

**Issue by mibieri** [olifolkerd/tabulator#716]
When creating a tabulator with no "height" attribute, the column header will scroll together with the rest of the table. When creating a tabulator with a height attribute, the column header will be frozen and only the table data will scroll.

How can I achieve that my column header does not move on scrolling, without explicitly specifying a pixel height? The tabulator should just use the full available space.

**Comment by olifolkerd** [comment]
Hey @mibieri,

That is expected behaviour, when you dont specify a height, you are telling Tabulator to grow as big as it needs to to hold all the data.

if you want it to take up all the available height in a div, i would suggest setting the height to 100%, the ***height*** property takes any valid css height value:

```js
$("#example-table").tabulator({
    height:"100%";
});
```

Cheers

Oli

**Comment by mibieri** [comment]
Hey @olifolkerd,

Thanks for your answer. Unfortunately, that doesn't work.

HTML-Snippet (I tried with and without the `table-container`):
```
  <body>
        <div id="table-container">
            <div id="example-table"></div>
        </div>
  </body>
```

Javascript-Snippet:
```
    $(table_name).tabulator({
        columns: columns,
        height: "100%"
        //layout: "fitColumns"
    })
```

CSS-Snippet (I tried with and without setting those heights):
```
#table-container{
    height: 100%;
}

#example-table{
    height: 100%;
}

```

**Comment by mibieri** [comment]
Or here is the full code to reproduce the issue, just unzip into the same folder. Images are missing, but I think that should not be a problem (table looks exactly the same):

[tabulator_problem.zip](https://github.com/olifolkerd/tabulator/files/1478269/tabulator_problem.zip)

**Comment by olifolkerd** [comment]
Hey,

It will only grow as big as its parent container, so if you are setting it in the body you will need to make sure the body also has a height of 100% set on its css.

Cheers

Oli
