### ISSUE TITLE
columnMoved callback

### ISSUE THREAD

**Issue by Manbec** [olifolkerd/tabulator#719]
Hello There! Thanks for this awesome library!

I have a question regarding the usage of **columnMoved** callback.

Here:
 `$("#example-table").tabulator({
    columnMoved:function(column, columns){
        //column - column component of the moved column
        //columns- array of columns in new order
    }
});`

When I drag columns to rearrange them, the callback is succesfully called. However **_columns_** variable is undefined so i cannot use the array with the new ordered columns. I am using this according to the docs http://tabulator.info/docs/3.3#callbacks

Am I missing something?

**Comment by olifolkerd** [comment]
Hey @Manbec ,

Thanks for your kind words, it is always great to hear that Tabulator is appreciated.

It looks like you have found a bug there, i will include a fix for that in this months patch release.

In the mean time you can get a list of columns using the ***getColumns*** command:
```js
$("#example-table").tabulator("getColumns") 
```

**Comment by Manbec** [comment]
Thank you!

**Comment by olifolkerd** [comment]
I have just pushed a fix for this to the master branch, it will be included in this evenings patch update
