### ISSUE TITLE
editor: css for input & number

### ISSUE THREAD

**Issue by hohozhao** [olifolkerd/tabulator#72]
Hi @olifolkerd,

For nicer look across different browsers, please add
`"height": "100%",`
to css for input and number.

**Comment by olifolkerd** [comment]
can you give me an example of a browser where the current settings do not work consistently so i can compare.

**Comment by hohozhao** [comment]
I am using RHEL7 and RHEL6 as my primary OS. I forgot how it looks using Chrome in RHEL7, but my home computer is RHEL6 with Firefox and Chromium installed.  Chromium gets the problem. "Input" area/size is smaller than the cell area/size if not setting height to 100%.

**Comment by olifolkerd** [comment]
While Tabulator is tested against and supports chrome on windows and iOS, i have not tested it against chromium on any version of linux.

I will see if i can fit in a test this weekend on chromium. Given it is a browser i havnt not tested on before, I will look at how Tabulator performs as a whole and make all the necessary adjustments in one go.

let me know if you have any other chromium based rendering issues.

**Comment by olifolkerd** [comment]
I had just run some tests on chromium and it is all working fine, there dont appear to be any issues with the height of the input elements.

have you checked to make sure you don't have any other css that is applying styles to the input elements?

which of the tabulator themes are you using?

**Comment by hohozhao** [comment]
![grey-bar](https://cloud.githubusercontent.com/assets/22469290/19462579/7059c992-9520-11e6-9199-7f77d8eeaa07.png)

"Grey-Bar" issue happen on both Chrome and Chromium. 
My Chrome version is "Version 50.0.2661.86 (64-bit)", using RHEL7 OS. 

This "Grey-Bay" is gone when clicking on any of the cells.

**Comment by hohozhao** [comment]
Answer your question, yes other css loaded, using uikit as my frame work. The cell height issue only exists in Chromium, it works fine in Chrome and Firefox. And it's difficult to troubleshoot, as when clicking in as "focus", and then click out to inspect, it lose focus, even I set ":focus" event for the DOM, not work well all the time. Can you teach me how to troubleshoot suck kind of events?

**Comment by hohozhao** [comment]
Now I see what this "Grey-Bar" it is. 
`<div style="min-height: calc(100% - 12px); max-height: calc(100% - 12px);" class="tabulator-tableHolder"><div style="min-width: 1902px; min-height: 1px; visibility: hidden;" class="tabulator-table"></div></div>`
It has 20px height when there's no data in the table. When there's data, in Firefox, the "Grey-Bar" doesn't show, but in Chrome/Chromium shows.

**Comment by olifolkerd** [comment]
That grey bar is the background of the table when there is not enough data to fill the table. 

I will have a look into this today
