### ISSUE TITLE
Selectable not working 

### ISSUE THREAD

**Issue by Rodbjartson** [olifolkerd/tabulator#721]
Hey there!
I have a table which I have styled, where I used the styling under the section called "Manually adjusted theme". The reason for why I mention this is that when I select a row in my table, there is no visual change to the row(you would expect the row to change color). I think this MIGHT have something to do with css.
But my real problem is that I feel that the row is not selected at all(even not behind the scenes). '
What I want to achieve is to be able to select a row, and click on my button that deletes this row.

Here is my table:

       

```
     $("#item-table").tabulator({
                height: 340, // set height of table, this enables the Virtual DOM and improves render speed dramatically (can be any valid css height value)
                layout: "fitColumns", //fit columns to width of table (optional)
                selectable: true,     //true means we can select a row              
                columns: [ //Define Table Columns
                    { formatter: "rownum", align: "center", width: 40 },
                    { title: "Fabrikat", field: "fabrikat", width: 150, align: "center" },
                    { title: "Varegruppe", field: "varegruppe", align: "center" },
                    { title: "Delenr", field: "delenr", align: "center" },
                    { title: "Antall bestilt", field: "antbest", align: "center" },
                    { title: "Kostkjøp", field: "kostkjøp", align: "center" },
                    { title: "Totalkostnad", field: "totalkostnad", align: "center" },
                ],
                rowClick: function (e, row) {
                    //e - the click event object
                    //row - row component

                    
                    var selectedRows = $("#example-table").tabulator("getSelectedRows")
                    console.log(selectedRows);
                },

            });
```
Here is my table after adding some data, and also after having clicked on several rows:

![2017-11-16 12_46_48-localhost_51301_ss3_purchaseorder aspx](https://user-images.githubusercontent.com/11444201/32889720-5cdef6d4-cacc-11e7-8ef3-9876652f92d8.png)

![2017-11-16 12_48_49-localhost_51301_ss3_purchaseorder aspx](https://user-images.githubusercontent.com/11444201/32889785-84848c4e-cacc-11e7-890a-6c9cb706dfcb.png)

This is the output I get when I console log the selected rows. Seems like no rows are selected, even though I have clicked on them!

What is happening here? Why can I not select rows in my table?

**Comment by olifolkerd** [comment]
Hey,

You dont need to use the rowClick callback to detect this, it will be triggered before the row is selected. There is a ***rowSelectionChanged*** callback that is triggered whenever the row selection is changed and passes in an array of row components for all selected rows:

```js
$("#example-table").tabulator({
    rowSelectionChanged:function(data, rows){
        //rows - array of row components for the selected rows in order of selection
        //data - array of data objects for the selected rows in order of selection
    },
});
```

With regards your styling, it is likely that the styling you are using to override the row colour is also overriding the selected style. I would recommend having a look at the scss or non-minified css of the tabulator stylishness you are using, to check how the styles are applied.
I hope that helps

Cheers

Oli

**Comment by Rodbjartson** [comment]
Yet again, thank you! Sloppy of me to not know that callback.
I think, however, that I might have found a bug.
From the documentation about the selectable option:

> integer - any integer value, this sets the maximum number of rows that can be selected (when the maximum number of selected rows is exceded, the first selected row will be deselected to allow the next row to be selected).

Hence I set `selectable: 1`
You would think that when you select row #1, and then select #2, that the rowDeselected: callback is triggered?
Here is the code:
```
 $("#item-table").tabulator({
                height: 340, // set height of table, this enables the Virtual DOM and improves render speed dramatically (can be any valid css height value)
                layout: "fitColumns", //fit columns to width of table (optional)
                selectable: 1,     //true means we can select a row              
                columns: [ //Define Table Columns
                    { formatter: "rownum", align: "center", width: 40 },
                    { title: "Fabrikat", field: "fabrikat", width: 150, align: "center" },
                    { title: "Varegruppe", field: "varegruppe", align: "center" },
                    { title: "Delenr", field: "delenr", align: "center" },
                    { title: "Antall bestilt", field: "antbest", align: "center" },
                    { title: "Kostkjøp", field: "kostkjøp", align: "center" },
                    { title: "Totalkostnad", field: "totalkostnad", align: "center" },
                ],
                rowSelected:function(row){
                    //row - row component for the selected row
                    row.getElement().css({ "background-color": "#f44242" });
                    console.log("ss");
                },

                rowDeselected: function (row) {
                    //row - row component for the deselected row
                    row.getElement().css({ "background-color": "#fff" });
                    console.log("a");
                },
                
                    
               
            });

```
Now, when I select a row, then I select another row, the rowDeselected function is NOT called. It should call since I want to change the styling back to default when it is not selected.
Am I right or is there a way to acheive this in a better way?

**Comment by olifolkerd** [comment]
Hey @Rodbjartson,

The ***rowDeselected*** callback is only called when a row is explicitly deselected by a user not when it happens to deselect because of another row being selected.

Now that you mention it, this behaviour does seem a bit inconsistent, i will look at changing it in the next release.

You don't need to use the ***rowSelected*** and ***rowDeselected*** function to style rows, when a row is selected, the ***tabulator-selected*** class gets applied to the row, which you can use to style it.

Cheers

Oli

**Comment by Rodbjartson** [comment]
Thanks again Oli, we really appreciate you taking your time answering our question.
Just for completeness I will show I solved my problem.



> **Problem:** You select rows, but the styling does not change, so it LOOKS like rows are not selected even though you set the "Selectable" option to true.

> **Reason:** Default styling was overridden by me. I did not only override the classes I wanted to override, but also other classes were affected. In this case the class was _**.tabulator-selected**_

> **Solution:** Manually override the class like this:

```
.mytabulatorclass .tabulator-selected{
            color: #37901b !important;
        }
```
.mytabulatorclass is just the div class. It can be something different for you, but I named it this. The color can be whatever you want. adding !important can help if it does not work when you omit it.
