### ISSUE TITLE
Groupclosed sum to zero

### ISSUE THREAD

**Issue by MBHOOTS** [olifolkerd/tabulator#722]
Hi Oli,
I have a problem with multi level grouping (3 group). When group 1,2 is closed, bottomCal is sum to zero.
any solution?

PICTURE:
![group tabulator](https://user-images.githubusercontent.com/33787686/32982971-a634cdf0-ccbf-11e7-8b5f-ef55cbcdde28.png)

CODE:
```js
$("#example-table").tabulator({
    height:"300px",
	layout:"fitColumn",
	groupClosedShowCalcs:true,
	groupBy:["quarter","month", "type"],
	groupToggleElement:"header",
	groupHeader:[
    function(value, count, data, group){ 		
        return "Quarter: "+value + "<span style='color:#d00; margin-left:10px;'>(" + count + " item)</span>";
    },
    function(value, count, data, group){ 
        return "Month: "+value + "<span style='color:#d00; margin-left:10px;'>(" + count + " item)</span>";
    },
	function(value, count, data, group){ 
        return value + "<span style='color:#d00; margin-left:10px;'>(" + count  + " item)</span>";
    },
	],
    columns:[
        {title:"Quarter", field:"quarter"},
        {title:"Month", field:"month"},
        {title:"Type", field:"type"},
        {title:"Date", field:"date"},
		{title:"Value", field:"value", align:"right", formatter:"money", formatterParams:{decimal: ',', thousand: '.'}, bottomCalc:"sum", bottomCalcFormatter:"money", bottomCalcFormatterParams:{decimal: ',', thousand: '.'}},
    ],
});
$("#example-table").tabulator("setData", "data.php");
```
DATA:

`
[{"quarter":"Q1","month":"1","type":"APP","date":"2017-01-21","value":"10.00"},{"quarter":"Q1","month":"1","type":"APP","date":"2017-01-22","value":"30.00"},{"quarter":"Q1","month":"1","type":"BPJ","date":"2017-01-21","value":"45.00"},{"quarter":"Q1","month":"1","type":"BPJ","date":"2017-01-22","value":"20.00"},{"quarter":"Q1","month":"2","type":"APP","date":"2017-02-01","value":"14.00"},{"quarter":"Q1","month":"2","type":"APP","date":"2017-02-05","value":"39.00"},{"quarter":"Q1","month":"2","type":"BPJ","date":"2107-02-10","value":"21.00"},{"quarter":"Q1","month":"2","type":"BPJ","date":"2017-02-23","value":"52.00"}]
`

**Comment by olifolkerd** [comment]
Hey @MBHOOTS ,

That looks like a bit of a bug there, the calculations should only be showing on the lowest level of groups, so when you collapse the top level the calcs should have been hidden entirely.

I have just pushed a fix for this to the master branch, it will be included in this evenings patch update

Cheers

Oli
