### ISSUE TITLE
UpdateData does not remove deleted rows

### ISSUE THREAD

**Issue by tomheaps** [olifolkerd/tabulator#723]
I have a table whereby rows can be dynamically added or deleted by the user and I am storing table data in a MySQL database. If a user on one computer updates the values in a row or adds a new row, these changes are reflected on another user's computer using a setTimeOut function which periodically queries my database and updates tabulator using the updateOrAddData function.

My problem is that if a user deletes a row, this row is also deleted from the MySQL database but these changes are not reflected on a different user's computer because tabulator just ignores the fact that the deleted row's index and data has not been passed back, and just updates the rows that still exist in the database.

The only way around this is to use setData instead of updateOrAddData but I don't want to call setData every 20s due to the issues this causes with memory bloat highlighted in #625.

Can you provide any ideas for a fix to remove rows whose index is missing from the JSON array returned from my database using updateOrAddData so that dynamic row deletion is reflected for all users viewing the table?

In a future update to tabulator, I guess what I am asking for is UpdateAddOrDelete functionality.

**Comment by olifolkerd** [comment]
Hey @tomheaps,

the ***updateData*** function is only meant to update data in the table, not delete exiting rows or add news ones.

It is on the roadmap for the next release to fix the memory leak issue, and provide a more comprehensive way of handling updates to existing table data With full reactive data handling coming in two releases time (update an array and tabulator will automatically update to match the arrays contents).

In the mean time as a work around i would suggest comparing the data in the table and the data from the requests, diffing them to determine  old missing rows and deleting them with the ***deleteRow*** function.

You will be happy to hear that my house moving/renovation has eased up a bit, so i am working on a bug fix release for the end of the week and starting work on the 3.4 release at the end of the week, so usual progress should be resumed shortly.

Cheers

Oli

**Comment by tomheaps** [comment]
Thanks Oli, that is exactly what I have done as a workaround.

The reactive handling of updates to existing table data sounds very exciting - exactly what I have been longing for!

Once again, thanks for all the hard work and for providing what is without doubt, THE best interactive table plugin around - DataTables doesn't even come close to Tabulator.

Will continue to try to help out on the issues side where I can so you have a few more precious minutes to work on the next release....

**Comment by olifolkerd** [comment]
Hey @tomheaps 

You will be happy to hear i have pushed a fix for the memory leak on the ***setData*** function to the 3.4 branch ready for tomorrows release, so that should fix your problem here.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Tabulator version 3.4 has now been officially released!

You can find details of the new release in the [News Section](http://tabulator.info/news)

Full documentation of all the new features can be found [Here](http://tabulator.info/docs/3.4)

Cheers

Oli :)
