### ISSUE TITLE
Grouping vs Paging: swiching mode after initialisation

### ISSUE THREAD

**Issue by cchalend** [olifolkerd/tabulator#726]
Hi,

I'm trying to _dynamically_ change tabulator view from grouping style (set at construction time) to paging one but I cannot make it work properly (no setter method linked to pagination and paginationSize members).

Am I missing something or is this kind of feature under development please ?

King regards,
Christophe

**Comment by olifolkerd** [comment]
Hey @cchalend 

Tabulator is not designed to allow a switch between paged and non-paged rendering modes.

In this instance i would recommend you call the ***destroy*** function on your existing  tabulator instance and then reinitialize it with a new setup

I hope that helps

Cheers

Oli

**Comment by cchalend** [comment]
Hi Oli,

Thanks a lot for this answer: reinitialisation sounds like a nice solution to cope with this problem.
I'll have to check w/if data caching can be used in such context or not but I guess this will perfectly do the job !

Cheers,
Christophe

**PS**: this component and its documentation are very impressive - very good job Oli ;o)
