### ISSUE TITLE
SetFilter anomaly 

### ISSUE THREAD

**Issue by YendorMc** [olifolkerd/tabulator#727]
Oli - this is an amazing piece of art that you have going here - just absolutely amazing!

I'm stumped on an area that I need some help...I'm wanting to set two filter parameters after the table is drawn.

I've tried three different methods which creates an identical JSON.stringify results from my eye, but the table is coming back blank in all except for when I use a "setFilter" on the 1st filter and "addFilter" on the 2nd filter.  No errors come back on Try1 and Try 2.

//Try 1: doesn't work (get a blank table)
var myfilt = [{field:"MARK",type:"=",value:"RRRR"},{field:"Year",type:"=",value:"2017"}];
$("#example-table").tabulator("setFilter",myfilt);

//Try 2: doesn't work (get a blank table)
$("#example-table").tabulator("setFilter", 
[{field:"MARK",type:"=",value:"RRRR"},{field:"Year",type:"=",value:"2017"}]);

//Try 3: works (data is filtered by Mark and Year)
$("#example-table").tabulator("setFilter", "MARK", "=", "RRRR");
$("#example-table").tabulator("addFilter", "Year", "=", "2017');

//Try 3's JSON via the following line of code,
//  console.log(JSON.stringify($("#example-table").tabulator("getFilters",true)));
// is the same as Try1's myfilt and Try 2's

Any idea what I'm doing wrong?

**Comment by olifolkerd** [comment]
Hey @YendorMc 

Thanks for your kind words, it is always great to hear people are enjoying using Tabulator.

could you post a copy of the table constructor object you are using so i can run some tests also what version of tabulator are you using on what browser?

Cheers

Oli

**Comment by YendorMc** [comment]
Hi Oli!

Sorry for the delay!  

Running Tabulator 3.3.1  on FireFox 54.4.0.

Rename the enclosed file Sample.txt to Sample.html and note dependencies on the JS/CSS at the top.  You'll be able to see my comments of working/not working code.

[Sample.txt](https://github.com/olifolkerd/tabulator/files/1512407/Sample.txt)

Thanks so much for looking into it!  Not a big item, as there's an easy workaround, but seems like it's not behaving as documented.   The only difference in the JSON data is that my years are Strings, but this JSON converted it into numbers, but still has the same effect.

**Comment by olifolkerd** [comment]
Hey @YendorMc 

Sorry for the delay in getting back to you on this one, turns out there was a bug in the filter system that was causing the filters to fail when more than one columns were filtered, i have just pushed a fix to the master branch for this.

It will be included in this evenings patch update.

Cheers

Oli
