### ISSUE TITLE
pagination remote

### ISSUE THREAD

**Issue by marquesjuniorpalmas** [olifolkerd/tabulator#73]
I'm not getting the popular datagrid. using the remote paging. if possible help me.

**Comment by olifolkerd** [comment]
Im afraid i do not understand what you are trying to ask.

Are you saying that remote pagination is not working for you? If so could you post some of following information so i can help you with your problem:

- The tabulator constructor object (settings) you are using to setup your tabulator.
- The URL your server is expecting to process the pagination request.
- A sample of the JSON data your server is returning to Tabulator.
- Which browser you are using

Once i have that information i should be able to help you out.

**Comment by marquesjuniorpalmas** [comment]
`<script>
    $("#load_marca").tabulator({
        ajaxURL: "_controller/_marca.php?acao=load",
        paginationDataSent:{
            "page":"pageNo",
        },
        ajaxParams:{token:"ABC123"},
        paginationSize:5,
        columns:[
            {title:"ID", field:"marca_ID", sorter:"int", width:200},
            {title:"Descrição", field:"marca_DESCRICAO", sorter:"string", width:200}
        ],
        pagination: "remote",
        fitColumns:true
    });
</script>`

Json

[{"marca_ID":"1","marca_DESCRICAO":"01","marca_STATUS":"1"},{"marca_ID":"2","marca_DESCRICAO":"02","marca_STATUS":"1"},{"marca_ID":"3","marca_DESCRICAO":"03","marca_STATUS":"1"},{"marca_ID":"4","marca_DESCRICAO":"04","marca_STATUS":"1"},{"marca_ID":"5","marca_DESCRICAO":"05","marca_STATUS":"1"}]

**Comment by marquesjuniorpalmas** [comment]
Google Chrome

**Comment by olifolkerd** [comment]
Are you actually trying to paginate your data or do you just want to load it from a remote data source?

**Comment by olifolkerd** [comment]
if you just want to pull in data from a remote source without pagination then you can use a much simple constructor like this:

```js
$("#load_marca").tabulator({ 
    fitColumns:true,
    ajaxURL: "_controller/_marca.php?acao=load", 
    columns:[ 
        {title:"ID", field:"marca_ID", sorter:"int", width:200}, 
        {title:"Descrição", field:"marca_DESCRICAO", sorter:"string", width:200} 
    ], 
});
```

**Comment by marquesjuniorpalmas** [comment]
I want to create the pagination, the tabulator is managing to send the information by GET. But I am not able to populate the grid with json

**Comment by olifolkerd** [comment]
There are a few issues that we can resolve to get your pagination working.

### Tabulator Constructor

Firstly, the ***ajaxParams*** option, is there to send any additional ajax parameters with the request, you seem to have copied this straight from the demo , the ***token*** parameter was just there as a demo. In this case you would want to use it for your ***acao*** parameter instead of putting it in the url string:
```js
ajaxParams:{acao:"load"},
```

The ***paginationDataSent*** should only be used if you do not want the default pagination parameters to be used in the request to the server. if you are expecting the requested page number in the ***pageNo*** parameter then that is ok, if not i would remove that definition and it will be sent  in the ***page*** parameter by default.

Putting this together gives us the constructor:

$("#load_marca").tabulator({ 
    fitColumns:true,
    ajaxURL: "_controller/_marca.php", 
    ajaxParams:{acao:"load"},
    paginationDataSent:{ "page":"pageNo", },
    columns:[ 
        {title:"ID", field:"marca_ID", sorter:"int", width:200}, 
        {title:"Descrição", field:"marca_DESCRICAO", sorter:"string", width:200} 
    ], 
});

Which will make a GET request to the server which will look like this (using a request for page 1 as an exmaple):
```js
_controller/_marca.php?acao=load&pageNo=1
```

### Returned Data

If you are using remote pagination then you need to be returning your data in the following format:
```js
{
    "last_page":15, //the total number of available pages
    "data":[
        {"marca_ID":"1","marca_DESCRICAO":"01","marca_STATUS":"1"},                     
        {"marca_ID":"2","marca_DESCRICAO":"02","marca_STATUS":"1"},                
        {"marca_ID":"3","marca_DESCRICAO":"03","marca_STATUS":"1"},
        {"marca_ID":"4","marca_DESCRICAO":"04","marca_STATUS":"1"},
        {"marca_ID":"5","marca_DESCRICAO":"05","marca_STATUS":"1"}
    ]
}
```

You must return a ***last_page*** parameter that tells Tabulator how many pages are available, and the table data must be in the ***data*** parameter.

**Comment by marquesjuniorpalmas** [comment]
With this example the tabulator is not sending the pageno

**Comment by olifolkerd** [comment]
Try this:

$("#load_marca").tabulator({ 
    fitColumns:true,
    ajaxURL: "_controller/_marca.php?acao=load", 
    paginationDataSent:{ "page":"pageNo" },
    columns:[ 
        {title:"ID", field:"marca_ID", sorter:"int", width:200}, 
        {title:"Descrição", field:"marca_DESCRICAO", sorter:"string", width:200} 
    ], 
});

**Comment by marquesjuniorpalmas** [comment]
GET _controller/_marca.php?acao=load

**Comment by marquesjuniorpalmas** [comment]
You are being sent this way

**Comment by olifolkerd** [comment]
Sorry about that, I managed to remove the ***pagination*** parameter from the example.

This is the correct constructor
```js:
$("#load_marca").tabulator({ 
    fitColumns:true,
    ajaxURL: "_controller/_marca.php", 
    ajaxParams:{acao:"load"},
    pagination:"remote",
    paginationSize:5,
    paginationDataSent:{ "page":"pageNo" },
    columns:[ 
        {title:"ID", field:"marca_ID", sorter:"int", width:200}, 
        {title:"Descrição", field:"marca_DESCRICAO", sorter:"string", width:200} 
    ], 
});
```

**Comment by marquesjuniorpalmas** [comment]
thank you, I can now generate a json with php and will work. Thank you so.

**Comment by olifolkerd** [comment]
You are welcome! 

let me know if you have any further issues

**Comment by ribipul** [comment]
hi!

$('#error-table').tabulator({
        ajaxURL: '@Url.Action("GetErrorListPaging", "Error")',
        ajaxParams: { db: $('#dbname option:selected').text(), pgNo: 0, pgSize: 20 },
        pagination: "remote",
        paginationSize: 50,
        paginationDataSent: { "page": "pageNo" },
        paginationDataReceived: {
            "last_page": 10,
        },
        columns: [
            { title: "Serial", field: "ID", sortable: false, sorter: "number", align: "center", formatter: "rownum" },
            { title: "Procedure Name", field: "ProcedureName", sortable: false, sorter: "string", width: 300 },
            { title: "Err Number", field: "ErrorNumber", sortable: false, sorter: "number", width: 120, align: "center" },
            { title: "Err Line", field: "ErrorLine", sortable: false, sorter: "number", width: 100, align: "center" },
            { title: "Error Message", field: "ErrorMessage", sortable: false, sorter: "string", width: 470, formatter: "textarea" },
            { title: "Error Date", field: "DateofErr", sortable: false, sorter: "date", width: 170 },
        ],
    });


always show "Loading Error" message. what is wrong in my code?

**Comment by olifolkerd** [comment]
If you are getting a loading error that means there was an issues loading the data in over ajax,

Either the returned data was invalid JSON or there was an error on the server.

I would suggest having a look at the network tab in the debug console of your browser to see what the response is to the request. there is likely a server side error.

Cheers

Oli

**Comment by ribipul** [comment]
but when i use

pagination: "local"

then it work properly..

**Comment by ribipul** [comment]
$('#error-table').tabulator({
ajaxURL: '@Url.Action("GetErrorListPaging", "Error")',
ajaxParams: { db: $('#dbname option:selected').text(), pgNo: 0, pgSize: 20 },
pagination: "remote",
paginationSize: 50,
paginationDataSent: { "page": "pageNo" },
paginationDataReceived: {
"last_page": 10,
},
columns: [
{ title: "Serial", field: "ID", sortable: false, sorter: "number", align: "center", formatter: "rownum" },
{ title: "Procedure Name", field: "ProcedureName", sortable: false, sorter: "string", width: 300 },
{ title: "Err Number", field: "ErrorNumber", sortable: false, sorter: "number", width: 120, align: "center" },
{ title: "Err Line", field: "ErrorLine", sortable: false, sorter: "number", width: 100, align: "center" },
{ title: "Error Message", field: "ErrorMessage", sortable: false, sorter: "string", width: 470, formatter: "textarea" },
{ title: "Error Date", field: "DateofErr", sortable: false, sorter: "date", width: 170 },
],
});

If i use **pagination: "remote"** then no data display.

But when use **pagination: "local"** then data display properly.

What is the problem in **pagination: "remote"** ???

Thank u...

**Comment by olifolkerd** [comment]
Hey,

As i explained in the above answer, if you are using remote pagination then the server has to send additional information in the json request so that tabulator knows how to paginate the table.

you must return your data in the following format:
```js
{
    "last_page":15, //the total number of available pages
    "data":[
        {"marca_ID":"1","marca_DESCRICAO":"01","marca_STATUS":"1"},                     
        {"marca_ID":"2","marca_DESCRICAO":"02","marca_STATUS":"1"},                
        {"marca_ID":"3","marca_DESCRICAO":"03","marca_STATUS":"1"},
        {"marca_ID":"4","marca_DESCRICAO":"04","marca_STATUS":"1"},
        {"marca_ID":"5","marca_DESCRICAO":"05","marca_STATUS":"1"}
    ]
}
```

Cheers

Oli

**Comment by ribipul** [comment]
$('#error-table').tabulator({
ajaxURL: '@Url.Action("GetErrorListPaging", "Error")',
ajaxParams: { db: $('#dbname option:selected').text(), pgNo: 0, pgSize: 20 },
pagination: "remote",
paginationSize: 50,
paginationDataSent: { "page": "pageNo" },
paginationDataReceived: {
"last_page": 10,
},
columns: [
{ title: "Serial", field: "ID", sortable: false, sorter: "number", align: "center", formatter: "rownum" },
{ title: "Procedure Name", field: "ProcedureName", sortable: false, sorter: "string", width: 300 },
{ title: "Err Number", field: "ErrorNumber", sortable: false, sorter: "number", width: 120, align: "center" },
{ title: "Err Line", field: "ErrorLine", sortable: false, sorter: "number", width: 100, align: "center" },
{ title: "Error Message", field: "ErrorMessage", sortable: false, sorter: "string", width: 470, formatter: "textarea" },
{ title: "Error Date", field: "DateofErr", sortable: false, sorter: "date", width: 170 },
],
});

If i use **pagination: "remote"** then no data display.

But when use **pagination: "local"** then data display properly.

What is the problem in **pagination: "remote"** ???

Thank u...
