### ISSUE TITLE
Data overflows, but no scrollbar

### ISSUE THREAD

**Issue by Rodbjartson** [olifolkerd/tabulator#730]
I have a table where I get 20 results+, but only those results that fit into the height of my table are shown, the rest I cannot see because there is no scrollbar available for some odd reason.

I suspect that this might be an issue concerning CSS and my Semantics framework, and not something related with tabulator, but I cannot figure it out so I ask you guys.

This is my data after I loaded it in with an AJAX request.

![2017-11-22 09_58_10-localhost_51301_ss3_purchaseorder aspx](https://user-images.githubusercontent.com/11444201/33118425-1bcd9502-cf6c-11e7-8b90-fe01b7b29b5b.png)

Table constructor:

```
 $("#example-table").tabulator({
                    height: 263, // set height of table, this enables the Virtual DOM and improves render speed dramatically (can be any valid css height value)
                    layout: "fitColumns", //fit columns to width of table (optional)                  
                          
                    ajaxResponse: function (url, params, response) {                       
                        return response.d; //return the d property of a response json object
                    },
                    columns: [ //Define Table Columns
                        { title: "Bestillingsnr", field: "PONUMBER", width: 150, align: "center" },
                        { title: "Leverandørnavn", field: "SUPP_NAME", align: "center" },
                        { title: "Ordreslag", field: "ID_ORDERTYPE", align: "center" },
                        { title: "Ordredato", field: "DT_POORDER", sorter: "date", align: "center" },
                        { title: "Forventet levert", field: "DT_EXPDLVDATE", sorter: "date", align: "center" },
                        { title: "Sum", field: "BUYCOST", align: "center" },
                        { title: "Antall deler", field: "DELIVERED", align: "center" },
                        { title: "Levert", field: "DELIVERED", align: "center", formatter: "tickCross" },

                    ],

                });
```
Then I setData with a buttonClick that correctly loads in my data. There is not scrollbar however! How can this be solved?

**Comment by tomheaps** [comment]
What happens if you don't set a height in your table?

**Comment by olifolkerd** [comment]
Hey @Rodbjartson 

Have you by any chance put your Tabulator inside another div that is smaller than the table with an overflow set to ***hidden*** ?

Cheers

Oli
