### ISSUE TITLE
Will getFilter works on Header Filter

### ISSUE THREAD

**Issue by robertwong68** [olifolkerd/tabulator#734]
var filters = $("#example-table").tabulator("getFilter");

I know this work for filter data using setFilter, will it work for Header Filter also ?
i.e. to get all the header filter entries' value of a filtered tabulator.

Thanks in advance.

**Comment by olifolkerd** [comment]
Hey @robertwong68 

If you are using version 3.3+ you can pass an optional parameter to the ***getFilters*** function to get the header filters as well
```js
var allFilters = $("#example-table").tabulator("getFilters", true);
```

If you want to get just the header filters you can use the ***getHeaderFilters*** function:
```js
var headerFilters = $("#example-table").tabulator("getHeaderFilters");
```

Cheers

Oli

**Comment by robertwong68** [comment]
Thanks for the quick response.
