### ISSUE TITLE
Accessing values of invisible cells 

### ISSUE THREAD

**Issue by filip-langvad** [olifolkerd/tabulator#736]
Oli - very impressive - I'm bereft of superlatives !

Is it possible to access/manipulate content of invisible cells when entering/leaving another cell in a given row ?

Best wishes for you and Tabulator

**Comment by olifolkerd** [comment]
Hey @filip-langvad 

Thanks for the kind words!

there multiple ways of manipulating cells, what do you want to do with the content exactly as that will affect the answer i give

**Comment by filip-langvad** [comment]
I am qualifying/describing the content of a given string, say a date in a broad sense:
f.ex: "before start of 3rd century BC" , where I codify the statements as before/after; in the beginning/middle/end of ; season (f.ex: "beginning of spring 589 AD"); year/century/millenium etc etc.
I display these qualifiers as option lists in a div, and the individual values are contained in the invisible field. So when I click on a date-cell (which is a rendition of a number and its qualifier ), I need to be able to access this qualifying string so I can display my options correctly in the div.
Of course after editing has been completed, I need to be able to update the invisible cell...

Thanks for swift response
