### ISSUE TITLE
Persistent Layout

### ISSUE THREAD

**Issue by a-naslund** [olifolkerd/tabulator#737]
Hi,

Looks like some strange things are happening when I enable **persistenLayout**.
Two of my columns share the same field but I'm using the **formatter** function to separate the original value and show it in two different columns.
The original string in the field looks like "NA# - US" or "EMEA# - Sweden" and my column definition looks like:
```
{
	title: "Region",
	field: "ent_region",
	width: 80,
	formatter:function(cell, formatterParams){
		var tmp = cell.getValue();
		tmp = tmp.substring(0,tmp.indexOf("#"));
		return tmp;
	}
},
{
	title: "Sub Region",
	field: "ent_region",
	width: 120,
	formatter:function(cell, formatterParams){
		var tmp = cell.getValue();
		tmp = tmp.substring(tmp.indexOf(" - ") + 3,tmp.length);
		return tmp;
	}
}
```

If I enable persistent layout the second column definition is being replace by the first one, which means that the first definition appears twice and my Sub Region is gone. Can't two columns not share the same field or how can I avoid this from happening?

**Comment by Rodbjartson** [comment]
Can you provide a screenshot?

**Comment by a-naslund** [comment]
Before
![image](https://user-images.githubusercontent.com/23699779/33442785-491148c0-d5f6-11e7-8bac-66ec5e2915e0.png)

After (look at the difference for row 8 & 9)
![image](https://user-images.githubusercontent.com/23699779/33442824-632ffc7e-d5f6-11e7-85a3-599c8517f313.png)

Column definition that is stored in the localstorage
[
{"title":"<div id='select-all'></div>","field":"row","width":35,"visible":false},{"title":"ID","field":"ent_id","width":60,"visible":true},{"title":"Name","field":"ent_org_name","width":230,"visible":true},
{"title":"Address 1","field":"ent_address1","width":230,"visible":true},
{"title":"Address 2","field":"ent_address2","width":232,"visible":true},{"title":"City","field":"ent_city","width":120,"visible":true},{"title":"State","field":"ent_state","width":80,"visible":true},
{"title":"Zip Code","field":"ent_zip_code","width":80,"visible":true},{"title":"Region","field":"ent_region","width":120,"visible":true},{"title":"Region","field":"ent_region","width":120,"visible":true},{"title":"Active","field":"ent_active","width":66.5469,"visible":false}
]

**Comment by Rodbjartson** [comment]
@olifolkerd can you help?

**Comment by olifolkerd** [comment]
Hey @a-naslund,

You should not set two columns to use the same field, that will result in some very unpredictable behaviour. in your case i would recommend using a placeholder field name for your sub region column (the field does not have to exist in the data) and updating the formatted:

```js
{
	title: "Sub Region",
	field: "ent_region_sub",
	width: 120,
	formatter:function(cell, formatterParams){
		var tmp = cell.getData().ent_region;
		tmp = tmp.substring(tmp.indexOf(" - ") + 3,tmp.length);
		return tmp;
	}
}
```

Let me know if that helps,

Cheers

Oli
