### ISSUE TITLE
How to take care of error when using ajaxURL for data

### ISSUE THREAD

**Issue by hohozhao** [olifolkerd/tabulator#74]
Hi @olifolkerd ,
If the ajaxURL gets error (internal server error etc) or incorrect json data, how to take care of the error instead of continue the tabulator initiation?

**Comment by olifolkerd** [comment]
In the event of an error during an ajax load, the ***dataLoadError*** event will be triggered, you can bind a callback to this event in the table constructor and then handle it however you like.

```js
$("#example-table").tabulator({
    dataLoadError:function(xhr, textStatus, errorThrown){
        //xhr - the XHR object
        //textStatus - error type
        //errorThrown - text portion of the HTTP status
    },
});
```

**Comment by hohozhao** [comment]
I will try it out and give you feedback. Thx

**Comment by hohozhao** [comment]
It works. Looks like these 3 parameters return different error info, but I know which ones to choose. 

function(jqXHR, textStatus, errorThrown){
           alert(textStatus + ": " + errorThrown)
           alert(jqXHR.statusText+ ": " + jqXHR.responseText)
}
