### ISSUE TITLE
Column calculation : no update on row deletion ?

### ISSUE THREAD

**Issue by NicoKiaru** [olifolkerd/tabulator#740]
Dear Oli,

First of all, thanks for the very nice work and for the superb documentation. I am a beginner in JS and web development, but nonetheless I was able to use your repo super easily. Congrats again!

While playing around, I noticed that the sum calculation (I didn't check the other modes), is not updated if the user is deleting a row. If I'm not mistaken, this is probably not the behaviour you want.

Best,

Nicolas

**Comment by olifolkerd** [comment]
Hey @NicoKiaru ,

Thanks for the feedback, at the moment the column calculations don't update on row addition/deletion, i will add this functionality in the next release.

Cheers

Oli

**Comment by shashankaugurs** [comment]
You can call redraw method after delete, that will update the calculations.

**Comment by olifolkerd** [comment]
Hey @NicoKiaru 
you will be happy to hear i have just pushed an update to the 3.4 branch to force column calculation updates on row addition/deletion.

This will be released in the next couple of weeks.

Cheers

Oli :)

**Comment by NicoKiaru** [comment]
Awesome, thanks!

**Comment by olifolkerd** [comment]
Tabulator version 3.4 has now been officially released!

You can find details of the new release in the [News Section](http://tabulator.info/news)

Full documentation of all the new features can be found [Here](http://tabulator.info/docs/3.4)

Cheers

Oli :)
