### ISSUE TITLE
Persist Filtering and Sorting

### ISSUE THREAD

**Issue by fvfv** [olifolkerd/tabulator#741]
On Persisting, I see that only Column layout is persisted.  How do I go about persisting Filters and sorting so that when the users presses the back button after clicking on a column which is formatted as URL, the users returns to the previous state of the grid, including sort and filter.

Thanks for your support.

**Comment by olifolkerd** [comment]
Hey @fvfv,

At the moment that functionality is not built in to Tabulator, however you could use the ***dataSorted** and ***dataFiltered*** callbacks as triggered to store any changes to the filters/sorters.

Both of these callbacks pass in an array of the filters/sorters as the first argument. you could JSON encode this and store it in the browser using the ***localStorage*** JS API.

You could then retrieve these values after instantiating your Tabulator on page load, convert them back into objects and use the ***setFilter*** and ***setSorter*** functions to restore the values.

I hope that helps.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @fvfv 

You will be happy to hear that i have just pushed an update to the 3.4 branch to allow persistence of sorting and filtering data.

you can enable these with the ***persistentSort*** and ***persistentFilter*** options:
```js
$("#example-table").tabulator({
    persistentSort:true, //Enable sort persistence
    persistentFilter:true, //Enable filter persistence
});
```
Version 3.4 will be released later today.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Tabulator version 3.4 has now been officially released!

You can find details of the new release in the [News Section](http://tabulator.info/news)

Full documentation of all the new features can be found [Here](http://tabulator.info/docs/3.4)

Cheers

Oli :)
