### ISSUE TITLE
Select Group after Group By

### ISSUE THREAD

**Issue by robertwong68** [olifolkerd/tabulator#742]
After using the Group By function, is there a way I can select and return a Group Name? Current seems that we need to expand the group and select one of the rows within the group?
Thanks.

<img width="500" alt="screenshot 2017-11-26 19 57 36" src="https://user-images.githubusercontent.com/4545068/33239780-461b8546-d2e4-11e7-9a3d-8f00dae08d66.png">

**Comment by Rodbjartson** [comment]
What do you mean by select and return?

**Comment by robertwong68** [comment]
Say I want to select the "General" group and return the group name "General" to my program.

Currently, I cannot highlight the Group heading so I need to expand the "General" group and select one of the rows within the group and then get the value of the group name "General"

**Comment by Rodbjartson** [comment]
Is this what you want?

> The headerClick callback is triggered when a user left clicks on a column or group header, it can be set on a per column basis using the option in the columns definition object.

```
{title:"Name", field:"name", headerClick:function(e, column){
        //e - the click event object
        //column - column component
    },
}
```

**Comment by robertwong68** [comment]
Sorry, I want to click on the group heading e.g. CAMERA and return the group name "CAMERA" 
Current we cannot actually select a Group Name.

**Comment by Rodbjartson** [comment]
It did not work for me either, but that is weird since it states it should work on clicking a group header

**Comment by olifolkerd** [comment]
Hey Guys,

You want to use the ***groupClick*** function to get this data:
```js
$("#example-table").tabulator({
        groupClick:function(e, group){
        //e - the click event object
        //group - group component

        alert(group.getKey());
    },
});
```
