### ISSUE TITLE
getHtml issues and enhancements

### ISSUE THREAD

**Issue by lrowleyUB** [olifolkerd/tabulator#743]
Hi Oli,

I playing with the getHtml method for printing purposes. Here is a screenshot of my grid on screen:
![capture](https://user-images.githubusercontent.com/33427660/33272916-b38c3ad8-d359-11e7-8862-59d286a050dd.PNG)

And here is the html output with a little styling added:
![capture2](https://user-images.githubusercontent.com/33427660/33273008-fce954b8-d359-11e7-860e-43f7810aa34e.PNG)

1) Columns that are grouped do not have the first header row in the output. The weekly row in my onscreen shot is missing.

2) Columns with blank title have the word "undefined" showing. First column in html table screenshot.

3) Enhancement - would be nice to have a HideInHTML option as a property on the column object. In my html table, I would like to hide the first column (which is the move row indicator onscreen), and the sparkline column since the values are already showing in subsequent columns and the chart does not display.

Let me know if you have any questions! Otherwise, still loving this control.

Regards,
Laura

**Comment by tomheaps** [comment]
Why don't you just hide the rows you don't want to display using CSS or alternatively, remove them using JavaScript?

**Comment by lrowleyUB** [comment]
The columns are generated dynamically server side based on user selections. There is no CSS on the html returned from the getHTML method. It would be difficult to locate the columns to hide. I'm using the getHTML method is for printing purposes so it would be nice to be able to have the visibility options when I'm constructing the column objects dynamically. Or even a callback might help - I could look for field names but that would become messy.

Oli, any updates on the column grouping header bug? I may have to consider another printing alternative if I can't use this method. Thanks!

**Comment by olifolkerd** [comment]
Hey @lrowleyUB,

Thanks for getting in touch, at the moment the ***getHTML*** function is very simplistic and only deals with basic table data, not groups.

I have just pushed a fix to the master branch that will be included in this evenings patch release to fix the "undefined" issue.

As this feature is clearly being used quite a bit now i will look at adding in some additional functionality in one of the next couple of releases.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @lrowleyUB 

You will be happy yo hear i have just added the ***hideInHTML*** option to the 3.4 branch, which will be released later today.

you can now set ***hideInHtml*** in a column definition object:

```js
{title:"Name", field:"name", hideInHtml:true}
```

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Tabulator version 3.4 has now been officially released!

You can find details of the new release in the [News Section](http://tabulator.info/news)

Full documentation of all the new features can be found [Here](http://tabulator.info/docs/3.4)

Cheers

Oli :)
