### ISSUE TITLE
Drag and Drop Location

### ISSUE THREAD

**Issue by JSonnabend** [olifolkerd/tabulator#744]
When I drag and drop a row, I am not seeing any indication of where the row has been dropped, i.e., what the new index is for the row.  How do I find that?

TIA

**Comment by tomheaps** [comment]
As far as I am aware, dragging and dropping a row will not change its index, only its position in the Dom tree.

**Comment by olifolkerd** [comment]
Hey @JSonnabend,

Im not sure what you mean by index of the column, but the ***columnMoved*** callback will tell you the column moved and provide an array of all columns in their new order so you could find the index of the column in that array:

$("#example-table").tabulator({
    columnMoved:function(column, columns){
        //column - column component of the moved column
        //columns- array of columns in new order
    }
});
