### ISSUE TITLE
Grouping Headers not displaying properly all the time.

### ISSUE THREAD

**Issue by Krigen** [olifolkerd/tabulator#748]
I have large database. I am using the grouping feature. When I scroll down, sometimes the group tab header displays across the entire window, and sometimes it does not.

![screenshot from 2017-11-29 12-08-25](https://user-images.githubusercontent.com/1379368/33388452-0b13adea-d4fe-11e7-8ecb-aa7797f6ef92.png)
![screenshot from 2017-11-29 12-08-30](https://user-images.githubusercontent.com/1379368/33388552-3cfca3a2-d4fe-11e7-99c8-070d7e0e73f2.png)

Is there a way to make the group tab header open/close when clicked on, compared to just the arrow?

Also, small documentation error: "var noDivideFive = functioncell, value, parameters){" in the validating documentation section.

**Comment by tomheaps** [comment]
Did you read the documentation? The groupToggleElement function is well described in the section about row grouping.

**Comment by Krigen** [comment]
Thanks for the info, I'll see if it has anything to do with the weird spacing.

**Comment by Rodbjartson** [comment]
I have the same issue. 

> Redraw

 often fixes the issue.
