### ISSUE TITLE
Is it possible to add ajax data approaching the last rows of a scrolling table ?

### ISSUE THREAD

**Issue by bagnus** [olifolkerd/tabulator#749]
Hi Oli,
I have to deal with hudge tables (> 60k items) and I would like to minimize the loading time using a scrolling table.
I am thinking to do a scrolling table of about 50 items, loading at beginning (ajax) only the first 50 rows, and adding other rows (chunks of 50 rows by ajax) when the user scrolls to the last few rows in the bottom. Some sort of dynamic pagination.
Is there a way to trigger en event in such condition, to launch the ajax load ?
Regards Andrea

**Comment by olifolkerd** [comment]
Hey,

At the moment this is not possible but it is on the roadmap, if you make sure you set the ***height*** property of the table this will enable the Virtual DOM allowing for near instantaneous rendering of any number of rows, the only delay there would be the ajax response time.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @bagnus 

You will be happy to hear I have just pushed an update to the 3.5 branch with this functionality. it should be officially released later in the week.

You will be able to enable it with the ***ajaxProgressiveLoad*** option:
```js
$("#example-table").tabulator({
    ajaxURL:"http://www.getmydata.com/now", //ajax URL
    ajaxProgressiveLoad:"scroll", //load data into the table as the user scrolls
});
```

For an advance preview of the documentation [Click Here](http://tabulator.info/docs/3.5#ajax-progressive).

Thanks for the great suggestion.

Cheers

Oli :)
