### ISSUE TITLE
Sparklines using Height attribute overflow cell content

### ISSUE THREAD

**Issue by dop0qob** [olifolkerd/tabulator#750]
Hi,

I am trying tabulator together with sparklines. I made the example work but when adding the "height" attribute of the sparkline, I can see the bars get longer but overflows the cell not resizing the cell.

Like this.

	 //generate bar chart
	 var barFormatter = function(cell, formatterParams){
	     setTimeout(function(){ //give cell enough time to be added to the DOM before calling sparkline formatter
	         cell.getElement().sparkline(cell.getValue(), {width:"100%", type:"bar", height: '30',barWidth:3, zeroAxis: false, disableTooltips:true});
	     }, 100);
	 };

Is it possible to autoresize table cells height? Or at least change it to manually to a bigger size?

Regards

**Comment by olifolkerd** [comment]
Hey @dop0qob,

There are two ways to handle this, you can add the ***variableHeight*** property to a column definition this will cause the cell height to adjust on column resize.

```js
{title:"Name", field:"name", formatter:myCustomFormatter, variableHeight:true}
```

you can also call the ***normalizeHeight*** function on the row component after the sparkline formatter has finished rendering:

```js
cell.getRow().normalizeHeight();
```

Let me know if that helps.

Cheers

Oli
