### ISSUE TITLE
IE error with `-Quotes

### ISSUE THREAD

**Issue by kurtknippschild** [olifolkerd/tabulator#751]
Hi Oli,

for a while you send me the information, that i shall this character "\`" when i have a String with line break.
Example:			, obj_bezeichnung: \`<%= objbez %>\`

This works fine in Safari, Chrome, Firefox, but in the Internet Explorer i become always a Error:
Script1014: Invalid character.

Have you any idea what can I do?

Thanks in advance.

Kurt

**Comment by olifolkerd** [comment]
Hey @kurtknippschild 

Im afraid i don't understand what you are asking, the markdown in your example has got a bit confused.

Could you provide a sample row data object containing the data and a copy of your table constructor.

Cheers

Oli

**Comment by kurtknippschild** [comment]
Hi Oli,

the problem is that backticks not supported in Internet Explorer.
I have a table and one column has a value with multiline string.
You can see this on the screenshot:
![bildschirmfoto 2017-12-05 um 08 14 50](https://user-images.githubusercontent.com/22855656/33594778-8fc49efa-d995-11e7-863b-53e1b234d88d.png)
My question was, have you any idea what can i do, that Tabulator.js with multiline-strings works in IE?

Thanks in advance

Kurt

**Comment by olifolkerd** [comment]
@kurtknippschild 

Backticks wont work in IE, that isnt a Tabulator issue, that is an Internet Explorer issue.

i would suggest that instead of using template strings *(strings using backticks)* you use normal single or double quotation marks and store your carriage returns as `\n` or `\r`

**Comment by kurtknippschild** [comment]
Hi Oli,

thanks for your answer.
I know that this not a issue of Tabulator.

Thanks
Kurt
