### ISSUE TITLE
Set CELL id not possible

### ISSUE THREAD

**Issue by dop0qob** [olifolkerd/tabulator#753]
Hi,

im trying to assign a cell ID to a specific cell but the value does no stay. If retrieved after table build, the value dissapears.

```
	 var barFormatter = function(cell, formatterParams){
	     setTimeout(function(){ //give cell enough time to be added to the DOM before calling sparkline formatter
	         cell.getElement().id = 'cellid1';
			 //cell.id = 'cellid1';
			 cell.getElement().sparkline(cell.getValue(), {width:"100%", type:"bar", height: '30',barWidth:3, zeroAxis: false, disableTooltips:true });
			 cell.getRow().normalizeHeight();
	     }, 100);
	 };
```

Is there any other way to tag cells dinamically so i can retrieve the element with getElementbyID or alternatives?

Regards,

**Comment by olifolkerd** [comment]
Hey,

the reason you are having issues is because the ***getElement()*** function returns a jQuery object not a DOM element so you need to do the following:
```js
cell.getElement().attr("id", "cellid1");
```

Can i ask why you want to access the DOM directly, because Tabulator uses a virtual DOM elements are created and destroyed as the table is scrolled so event bindings etc will not hold if added externally, there are a load of inbuilt functions in tabulator that will meet with almost any need, if you let me know what you are trying to achieve i could point you in the right direction.

Cheers

Oli

**Comment by dop0qob** [comment]
Thank you Oli,

Im trying to build a table with 200 rows, each of them with 2 columns that contains a sparkline each.
The sparkline bar with 260 lines. The data will change at a rate of 1new line added for each sparkline every minute at the same time oldest line will be removed. I made a php json script that will give me the 200*2*260 array of data on the first call, but i pretend to return only the new lines on following calls.
As the new data will be produced at a rate of 1 line per sparkline per minute, but not all within the same second (200*2 per minute), so, Im trying to call the json script every 5-10 seconds to retrieve and refresh partial data until the 200*2 is updated every minute.

In Tabulator I could only find the way to refresh the entire table by using

`$("#example-table-sparkline").tabulator("setData", sparkData);
`

But I think a table with an array of 200*2*260 data will not perform good if refreshed every 5-10 seconds.

If its possible i want to update only the cells wich data really updated.
In native sparkline pluguin i could perform this by 
```
 <span class="dynamicbar1">Loading..</span><br/>
$('.dynamicbar1').sparkline(mpoints['spark1'], { type: 'bar', height: '30', barWidth: 3, zeroAxis: false, disableTooltips: true }
```

Do you think its possible to do this with tabulator? Alternativelly I was thinking of building the table myself and then apply tabulator over the simple table. But I dont know if I can get funtionalities like sorting or so.(over a cell that is not an sparklinebar)

sorry for the long reply!!

Regards,
David

**Comment by olifolkerd** [comment]
Hey David,

Sorry for the delay in getting back to you, if you call the ***updateData*** function, the ***updateRow*** function or the ***update*** function on the Row Component or the ***setValue*** function on the Cell Component it will trigger tabulator to only update the affected cells.

Cheers

Oli
