### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by kurtknippschild** [olifolkerd/tabulator#754]
Hi Oli,

i have a table she looks like so:
![bildschirmfoto 2017-12-05 um 14 30 18](https://user-images.githubusercontent.com/22855656/33609598-0afdc7f8-d9c9-11e7-8f46-f291f741f67d.png)

I need a tooltip on the first visible column (Objekt-Name).
But the value of the tooltip is on the not visible column (pfad).
Hera are the code of the columns:
{title:"pfad", field:"pfad", visible:false},
{title:"Objekt-Name", field:"obj_name", sorter:"string", headerSort:false, align:"left", formatter:fontSizeFormatter,  tooltip: ????, cellClick:function(e, cell){

Can you help?

Thanks in advance.

Kurt

**Comment by olifolkerd** [comment]
Hey @kurtknippschild ,

you can pass a callback into the tooltip property to generate the tooltip, you can then use the cell component passed into this to get the value of any data in the row:

```js
{title:"Objekt-Name", field:"obj_name", tooltip:function(cell){
    return cell.getData().pfad;
}}
```
