### ISSUE TITLE
sorting group by alphabetically

### ISSUE THREAD

**Issue by sumitpatil2405** [olifolkerd/tabulator#755]
for table i am using group by for grouping but i want to sort this grouping alphabetically is it possible to do so 

$("#table-bln-tabulator").tabulator({
			dateFormat: "mm/dd/yyyy",
			index: "LoanApplicationCondition.condition_number",
			groupBy:"0.is_condition",

});
is_condition is the array field got from the Jason response.

**Comment by olifolkerd** [comment]
groups are sorted according to the sort applied to the table.

have a look at the [Sorting Documentation](http://tabulator.info/docs/3.3#sorting) for more information.

Cheers

Oli

**Comment by sumitpatil2405** [comment]
![image](https://user-images.githubusercontent.com/20032364/33671078-a4bf2052-da74-11e7-80ec-b9751174bac0.png)
 Sorting Documentation is not helpful plz can you look the table image i attach here..
here the grouping is done in 3 way document , condition ,policy exception resp.
$("#table-bln-tabulator").tabulator({
			dateFormat: "mm/dd/yyyy",
			index: "LoanApplicationCondition.condition_number",
			groupBy:"0.is_condition",
			responsiveLayout: false,
            fitColumns: true,
			placeholder: "No Data Available",
			columns: [ //Define Table Columns
				{title:"#", field:"LoanApplicationCondition.condition_number", align:"center", sorter:"number", width: 40},
				{title:"Condition Type", field:"LoanCondition.condition", sorter:"string"},
				{title:"Document Type", field:"DocumentType.document", sorter:"string"},
				{title:"Note", field:"LoanApplicationCondition.condition_notes", sorter:"string",formatter: noteFormatter, mutator: function (value, data, type, mutatorParams, cell) { return nl2br(value, true); }, variableHeight: true },
				{title: "Status", field: "LoanConditionStatus.status_desc", sorter: "string", width: 140, formatter: statusFormatter},
				{title:"IsCondition", field:"0.is_condition", sorter:"string",visible:false},
				{title:"Status Note", field:"LoanApplicationCondition.condition_status_desc", sorter:"string",formatter: statusnoteFormatter,mutator: function (value, data, type, mutatorParams, cell) { return nl2br(value, true); }, variableHeight: true},
				{title: "", field: "LoanConditionStatus.status_desc", sorter: "boolean", align: "center", width: 75, formatter: statusFormatter, visible: false},
				{title:"Actions", field:"LoanApplicationCondition.condition_status_id", sorter:"boolean", align:"center", width: 140, formatter: actionsFormatter},
			]
		});
		
 all of these are value i get in array from in the 0.is_condition filed  now i passed 0.is_condition in table group by. but  i want to do  grouping as condition , document ,policy exception i.e alphabetically is it possible to do so.
