### ISSUE TITLE
Total as group header

### ISSUE THREAD

**Issue by the-supercoach** [olifolkerd/tabulator#757]
I'm very impressed with the new grouping features, but it appears like the intent is to have groups come under a header that doesn't give too much information about the group itself.
Is it possible to have the group header display as a sub-total for the group similar to using the topcalc/bottomcalc options on columns?

**Comment by olifolkerd** [comment]
Hey @the-supercoach 

you can pass anything you want into the group header element using the ***groupHeader*** option in the table constructor, this passes all the row data for the group as an argument and allows you to return the content of the header so you can use this to calculate anything you want:

```js
groupHeader:function(value, count, data, group){
    //value - the value all members of this group share
    //count - the number of rows in this group
    //data - an arrya of all the row data objects in this group
    //group - the group component for the group

    return value + "<span style='color:#d00; margin-left:10px;'>(" + count + " item)</span>";
},
```
