### ISSUE TITLE
onload, onclick events for cells

### ISSUE THREAD

**Issue by solarplex** [olifolkerd/tabulator#761]
Is it possible to add onload and onclick events to cells that are marked as <img>? I couldn't seem to find it in the documentation.

If there's an alternative, I am basically trying to refresh an image source with a new time ending "&t=______" every 3 seconds.

Even more info:
My Column for Image Thumbnails:
{title:"Thumbnail", field:"Thumbnail", formatter:function(cell, formatterParams){return '<img src="' + cell.getValue() + '&t=" onload="setTimeout(function() {src = src.substring(0, (src.lastIndexOf("t=")+2))+(new Date()).getTime()}, 5000)">';},

Ends up placing a space at " t=")+2
img src="LINK&t=" onload="setTimeout(function() {src = src.substring(0, (src.lastIndexOf(" t=")+2))+(new Date()).getTime()}, 5000)"

**Comment by olifolkerd** [comment]
Hey @solarplex 

There should be no need for an onload event for a cell, if you are using a formatter it will generate the content for the cell at the point it is created,

There is a **cellClick*** callback you can register in a column definition to handle cell clicks:
```js
{title:"Name", field:"name", cellClick:function(e, cell){
        //e - the click event object
        //cell - cell component
    },
}
```

See the [Column Definition Documentation](http://tabulator.info/docs/3.3#define-column-headers) for more information.

Cheers

Oli

**Comment by solarplex** [comment]
Thanks Oli
