### ISSUE TITLE
Calling getRows from tabulator

### ISSUE THREAD

**Issue by TSE-jc** [olifolkerd/tabulator#762]
Hi,

In the provided documentation, when need to get a specific row in tabulator it's said to do the following
```
var row=$('#element').tabulator("getRows",1);
...
var value=row.getCell('m1').getValue();
```
But in order to make it work, i had to do the following
`var row=$('#element').tabulator("getRows",1)[0];`
Then it has been possible to call getCell() without any error.

I suppose it's not the intented behavior, so i report it for update.

Regards,

**Comment by olifolkerd** [comment]
Hey @TSE-jc 

I think you are confusing the ***getRow*** function with the ***getRows*** function, the first retrieves the Row Component with an index value matching the provided value (the value of the defined index field, not is position in the table), the second function retrieves and array of all Row Components in the table.

Cheers

Oli
