### ISSUE TITLE
Cell height problem

### ISSUE THREAD

**Issue by dchristof** [olifolkerd/tabulator#765]
Oli hi and thanks for a great script! I have an issue with a table I'm constructing where I apply height:100% to the .tabulator-cell elements. When I do the cells display all the content (one or more divs in each cell) but the column borders disappear. I've tried various css styles but can't get it to work. 

You can see the table [here](http://elementia.gr/files/occwebview/year.html)

It's a big table and takes some time to load, I'm using nedb which progressively fills in the table. 

I would really really appreciate it if you could have a look !

**Comment by olifolkerd** [comment]
Hey @dchristof,

Can i ask why you need to set the height of the cells? this will likely break the rendering of the table, as tabulator will manually override this when it normalises the height of the rows.

If you can describe the effect your after i can suggest a solution for you.

Could you post a copy of your table constructor object on here please so i can tailor the solution to you.

Cheers

Oli

**Comment by dchristof** [comment]
@olifolkerd thanks so much for you prompt reply. If I don't set a height for .tabulator-cell then the cells don't expand to display all the content and get a default height of 22px. Maybe I'm missing something here? I really tried various combinations. Here's my constructor: 

```javascript
	jQuery("#eventstable").tabulator({
		height:"800px", // set height of table, this enables the Virtual DOM and improves render speed dramatically (can be any valid css height value)
		virtualDomBuffer:300, //set virtual DOM buffer to 300px
		columns:[
			{title:"", field:"day", align:"center", width:30, variableHeight:true, frozen:true},
		],	
		 index:"day",
	});
```

and then I generate the columns (9 columns for every month): 

```javascript
	while (dateEnd2 > dateStart2) {
		mon = dateStart2.format('M');
		monTitle = dateStart2.format('MMMM') + ' ' + dateStart2.format('YYYY')
		$("#eventstable").tabulator("addColumn", {title:monTitle, columns:[
			{title:"", field:mon+"dayname", align:"center", width:10, variableHeight:true},
			{title:"Main Stage", field:mon+"room1", formatter:"html", align:"center", width:100, variableHeight:true},
			{title:"Upper Stage", field:mon+"room2", formatter:"html", align:"center", width:100, variableHeight:true},
			{title:"Foyer", field:mon+"room3", formatter:"html", align:"center", width:100, variableHeight:true},
			{title:"Outdoor", field:mon+"room4", formatter:"html", align:"center", width:100, variableHeight:true},
			{title:"Back of house", field:mon+"room5", formatter:"html", align:"center", width:100, variableHeight:true},
			{title:"Εκθεσιακός χώρος", field:mon+"room6", formatter:"html", align:"center", width:100, variableHeight:true},
			{title:"Υπ.θέατρο+Hytra", field:mon+"room7", formatter:"html", align:"center", width:100, variableHeight:true},
			{title:"Rehearsal", field:mon+"room8", formatter:"html", align:"center", width:100, variableHeight:true},		
		], align:"left"}, false);		
		dateStart2.add(1,'month');
	}	
```

and then I add empty rows : 

```javascript
while(d <= 31) {
		$("#eventstable").tabulator("addRow", {day:d});	
		d++;	
	}
```

and then I populate the cells I want with UpdateData

If you check the [table](http://elementia.gr/files/occwebview/year.html) now I removed the height:100% style and as you will see the cell height cuts off the content.

**Comment by dchristof** [comment]
@olifolkerd I think I fixed it by adding a text formatter like that

```javascript
var textareaFormatter = function(cell, formatterParams){
	cell.getElement().css({"height":"100%"});
	return cell.getValue();
}
```

and now [as you can see](http://elementia.gr/files/occwebview/year.html) the column borders are visible

A quick question: can I assign a cell background color only in cases where my cell contains one div and not many?

**Comment by olifolkerd** [comment]
Hey @dchristof 

The cell should always take up the maximum height needed if the formatters have been used correctly. there is already a built in ***textarea*** formatter for handling multi-line text

You can set the background of the cell however you like. if you want to check how many divs are in a cell you could use the following formatter:

```js
var backgroundFormatter = function(cell, formatterParams){
    var element = cell.getElement();

    element.css( {
        "background-color": $("div", element).length > 1 ? "red"  : "green";
    });

    return cell.getValue();
}
```

Cheers

Oli

**Comment by sab24** [comment]
Had a similar problem, adding <!DOCTYPE html> solved the problem.
