### ISSUE TITLE
Order in the columns.

### ISSUE THREAD

**Issue by potlanos** [olifolkerd/tabulator#767]
I do not want to order columns but I can not remove the order.
I have tried with : "sortable:false" but it does not work.
What I want is to remove the arrow from the header

thk!

potlanos

**Comment by olifolkerd** [comment]
Hey @potlanos 

You need to user the ***headerSort*** property in the column definition object:

```js
{title:"Name", field:"name", headerSort:false},
```

Cheers

Oli

**Comment by potlanos** [comment]
ok. thanks!!
