### ISSUE TITLE
Transfer auto new data from table to other 

### ISSUE THREAD

**Issue by rodaina31** [olifolkerd/tabulator#768]
I have table in json format and need to transfer new data from this table to other table   in myphpadmin

**Comment by olifolkerd** [comment]
Hey @rodaina31,

Does this question have anything to do with the Tabulator plugin? Tabulator is not used in myphpadmin

Cheers

Oli

**Comment by rodaina31** [comment]
Ok can you give me any contact to person or page or website it's can help me

**Comment by olifolkerd** [comment]
I would suggest asking your question on https://stackoverflow.com/
