### ISSUE TITLE
What happen if initiate tabulator more times?

### ISSUE THREAD

**Issue by hohozhao** [olifolkerd/tabulator#77]
Oli,

If I set ajaxURL: '/url/' when initiate tabulator, and then I want to change the ajaxURL, can I use `("#table").tabulator(ajaxURL: '/new/url' );`
to update it?

All I want is to update the ajaxURL, and then call "setData" to update the data from updated URL.

Can I use "setData" like this when ajaxURL is in use? (Seems I works, I tested it,but not sure if there's any side effect, will the ajaxURL updated by this way?)
`$("#example-table").tabulator("setData","http://www.getmydata.com/now", {key1:"value1", key2:"value2"});`

**Comment by olifolkerd** [comment]
You were correct in your assumption,, using ***setData*** is the correct way to change the url.

Your example should work perfectly:
```js
$("#example-table").tabulator("setData","http://www.getmydata.com/now", {key1:"value1", key2:"value2"});
```
