### ISSUE TITLE
Focus on row

### ISSUE THREAD

**Issue by leonardorame** [olifolkerd/tabulator#770]
Hi Oli, I wonder if is there a way to focus on a specific row.

When I call `selectRow` the row isn't visually selected, I mean, the result is not the same as when I click on that row, and that's what I want to achieve.

**Comment by michaelongithub** [comment]
Hi
As far as I have seen, this is only possible, if you programmatically maintain that for yourself.  You can do things like:
      tabulatorDiv.tabulator("deselectRow");
        tabulatorDiv.tabulator("selectRow", keyValue);
        tabulatorDiv.tabulator("scrollToRow", keyValue);

where you have to manage yourself, what is the desired keyValue.

But there is in https://trello.com/b/rPZ0Yavc/tabulator-roadmap, the 3.4 getPosition function which probably will make this easyer.

Cheers, Michael

**Comment by olifolkerd** [comment]
Hey @leonardorame 

Im not sure i follow you, when you call the ***selectRow*** function it is exactly the same as selecting a specific row with the mouse as far as Tabulator is concerned.

Could you post a copy of your table constructor, the code you are using to select a row, the data for that row and a couple of screen shots of what you are expecting and what you are getting?

Cheers

Oli
