### ISSUE TITLE
Column resize border doubleclick default: fit to data

### ISSUE THREAD

**Issue by michaelongithub** [olifolkerd/tabulator#771]
Hi Oli
rationale:  the layout: "fitData" option only affects the data visible at start. (when height is set and virtual mode is effective).  So if one scrolls down, it would be very handy to be able to just doubleclick the border to fit again if one sees a lager cell. 

Since it is probably not achievable with virtual rendering to have the largest width from the beginning.

And it would be a nice user friendly feature just as in Excel.

Cheers Michael

**Comment by Rodbjartson** [comment]
Agreed. What happens when you redraw the table AND data though?

**Comment by michaelongithub** [comment]
if You mean tabulator("redraw");Never tried that.

**Comment by olifolkerd** [comment]
Hey @michaelongithub 

Good idea, i will add it to the roadmap,

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @michaelongithub 

You will be happy to hear this feature has just been pushed to the 3.4 branch.

when you double click on a column resize handle the row will resize to fit its data.

This will be included in the 3.4 release in a couple of weeks time.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Tabulator version 3.4 has now been officially released!

You can find details of the new release in the [News Section](http://tabulator.info/news)

Full documentation of all the new features can be found [Here](http://tabulator.info/docs/3.4)

Cheers

Oli :)
