### ISSUE TITLE
Column widths when dynamically adding/removing columns

### ISSUE THREAD

**Issue by sophlouiseh** [olifolkerd/tabulator#772]
I'm using tabulator to dynamically show columns based on user selections. It's all working pretty great except that the added columns don't respect the width of the data in them. Some of them are too thin. I've tried calling redraw in render complete but it makes no difference.

I've managed to fix this using a workaround where I expose the layout method and call it in render complete (See below). This works but is not ideal as it requires me to change the source code for tabulator.

Any advice? Or anything you can do?

```

$('#my-table').tabulator({
        layout: "fitDataFill",
        pagination: "remote",
        paginationSize: 100,
        selectable: 1,
        ajaxURL: //server url,
        ajaxRequesting: function (url, params) {
            //add user column selections as parameters
        },
        ajaxConfig: 'POST',
        ajaxSorting: true,
        ajaxResponse: function (url, params, response) {
            if (response.columns) {
                //return list of columns to show in response.columns
                //dynamically add and remove given columns using tabulator methods
            }

            return response; 
        },
        renderComplete: function (data) {
            $('#my-table').tabulator('layout');
        }
    });

```

**Comment by olifolkerd** [comment]
Hey @sophlouiseh,

could you post a copy of some of the column definitions you are setting when you add columns, so i can replicate the issue more accurately.

Cheers

Oli

**Comment by sophlouiseh** [comment]
My column definitions are very basic. They consist of a field and a title only. For example:

columns:[
		{title:"Name", field:"name"},
		{title:"Task Progress", field:"progress"},
		{title:"Activity", field:"activity"},
		{title:"Gender", field:"gender"},
		{title:"Rating", field:"rating"},
		{title:"Color", field:"col"},
		{title:"Date Of Birth", field:"dob"},
		{title:"Car", field:"car"},
	]

**Comment by olifolkerd** [comment]
Hey @sophlouiseh 

Thanks for sending that over, this is because in fit data mode the table only resizes the column on data-load not when columns are changed, if you want the columns to change width again you will need to call the ***setData*** function again.

The next release will include some new properties that let you set when/how column widths are recalculated.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey All,

You will be happy to hear that I have just pushed some new functionality to the 3.4 branch (which will be released tomorrow) to address this issue.

The new ***layoutColumnsOnNewData*** option will allow you to tell Tabulator to update the column widths when the ***setData*** function is called:

```js
$("#example-table").tabulator({
    layoutColumnsOnNewData:true,
});
```

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Tabulator version 3.4 has now been officially released!

You can find details of the new release in the [News Section](http://tabulator.info/news)

Full documentation of all the new features can be found [Here](http://tabulator.info/docs/3.4)

Cheers

Oli :)

**Comment by sophlouiseh** [comment]
Thanks a lot! I'll definitely check out the new version :)
