### ISSUE TITLE
Convert HTML table to Tabulator

### ISSUE THREAD

**Issue by rri195** [olifolkerd/tabulator#773]
HI, I am having trouble to Convert HTML table to Tabulator, which contains HTML tags like  div  a etc..

please see the link
https://jsfiddle.net/odmg2wnd/1/

thanks

Greg

**Comment by Rodbjartson** [comment]
From the documentation:

> Note: Tabulator can only parse simple tables. Tables using multiple header rows, colspan or rowspan attributes will cause the import to fail.

Seems like this might be the issue.

**Comment by rri195** [comment]
found solution added tabulator-formatter="html" in the TH.

but another question came up. I destroyed the table the re initiated, the table is not render.

**Comment by rri195** [comment]
Found the solution: need to put tabulator-formatter="html"  in TH

**Comment by vishwas09** [comment]
Hello,
i'm Trying to convert HTML table to Tabulator,
In html table i have heading as a html element checkbox 

**<th tabulator-formatter="html"><input type="checkbox" id="checkall" /></th>**

during the conversion from table to Tabulator this heading get blank.
