### ISSUE TITLE
Hierarchical Child/Nested/Sub Table

### ISSUE THREAD

**Issue by JimSmithJr** [olifolkerd/tabulator#775]
When do you think you might have child tables implemented?

A similar request was made in Feb in issue #175 and a similar request was made Oct 2016 in issue #62.

The screen shots provided in #175 are close however implementations such as this:
https://www.jqwidgets.com/jquery-widgets-demo/demos/jqxdatatable/javascript-datatable-nested-tables.htm
I think are more clear to the user as to what is going on.  More specifically the nested table is a duplicate implementation of the parent table - just with related data with a hide/show function.  If no child data exists then there is an indicator saying "no child data here".

Tabulator has every functionality and does it better than even commercial JQuery libraries and frameworks.  Tabulator is clean, the code is clear best I've seen.  It's just missing this behavior.  So I am hoping to get an ETA.  I checked the roadmap https://trello.com/b/rPZ0Yavc/tabulator-roadmap
And it is there but on "future" with no timeline other than 2018.

If you have code than can facilitate the hide/show on the custom row formatter until the complete solution is ready that would be great!

Thanks very much and awesome product.
Jim

**Comment by LMJS1974** [comment]
HI Oli,

Congratulations for the great work. This is an awesome plugin.

I am a newbie trying to implement the solution you suggested above, but with no success so far....

Would you be so kind to provide a code example of this would be achieved?

Many thanks,

Luis

**Comment by olifolkerd** [comment]
Hey @JimSmithJr 

You can now find an example of nested tables on the [Examples Page](http://tabulator.info/examples/3.5#nested-tables)

Let me know if you need any further info.

Cheers

Oli :)
