### ISSUE TITLE
Column head and text non alignment

### ISSUE THREAD

**Issue by yaxino** [olifolkerd/tabulator#778]
hi oli.

When I drag the scroll bar to look at a column of data behind. 
Then filter for data on a condition.
The list style is disorderly. Please look at the following picture
![image](https://user-images.githubusercontent.com/26379258/34097717-f68cfdf6-e414-11e7-87b5-c9a13ecd9519.png)

but, When I drag the scrollbar again, it's normal.

**Comment by olifolkerd** [comment]
are you using the latest version of Tabulator? 

A fix for this was released in 3.3.2

**Comment by yaxino** [comment]
/* Tabulator v3.3.1 (c) Oliver Folkerd */

**Comment by yaxino** [comment]
ok，i will try 。。。 thanks

**Comment by yaxino** [comment]
I'm sorry to tell you, It still doesn't work properly

**Comment by yaxino** [comment]
![image](https://user-images.githubusercontent.com/26379258/34099308-243ee494-e41a-11e7-88ba-d04003d470d4.png)

**Comment by olifolkerd** [comment]
Interesting, i will try and fix that in this weeks patch release.

Could you post a copy of your table constructor so i have something to test against.

Cheers

Oli

**Comment by yaxino** [comment]
`$(obj.selector).append('<div class="tabulator"></div>');
            $(obj.selector + ' .tabulator').tabulator({
                data: tableData,
                groupBy: obj.groupby,
                groupStartOpen:false,
                height: $(obj.selector).height() + 'px',
                layout:'fitColumns',
                movableColumns: true, 
                columns: obj.columns
            });`

and

`var columns = [
            {
                title: "ID", field: "RequestSN", width: 120, formatter: function (value) {
                    var data = value.getData();
                    value = value.getValue();
                    var curr_user = g_s.user.FirstName + ' ' + g_s.user.LastName

                    if (data.Checkers.indexOf(curr_user) >= 0) {
                        return "<a href='/pipeline/approve/?formid=" + data.ID + "'>" + value + "</div>";
                    }
                    else {
                        return "<a href='/pipeline/view/?formid=" + data.ID + "'>" + value + "</div>";
                    }
                }
            },
			{ title: "Title", field: "Title", width: 200, visible: hasColumn(tabid, 'Title') },
			{ title: "Submit Date", field: "ApplyDate", width: 150, visible: hasColumn(tabid, 'ApplyDate') },
             { title: "Domain", field: "Domain", width: 100, visible: hasColumn(tabid, 'Domain') },
             { title: "Lead Tower", field: "LeadTower", width: 150, visible: hasColumn(tabid, 'LeadTower') },
			{
			    title: "Status", field: "FormState", width: 150, visible: hasColumn(tabid, 'FormState'), formatter: function (value) {

			        function phaseColorClass(currstepid) {
			            if (machArr(phaseConfig.ConceptPhase, currstepid)) {
			                return 'label-warning';
			            }
			            if (machArr(phaseConfig.SolutionPhase, currstepid)) {
			                return 'label-pink';
			            }
			            if (machArr(phaseConfig.ExecutionPhase, currstepid)) {
			                return 'label-success';
			            }
			            if (machArr(phaseConfig.ClosePhase, currstepid)) {
			                return 'label-inverse';
			            }

			        }
			        var data = value.getData();
			        value = value.getValue();
			        if (value == 'Reject') {
			            value = '<div><span class="label ' + phaseColorClass(data.CurrentStepID) + '">Reject</span></div>';
			        }
			        if (value == 'Pending Submission') {
			            value = '<div><span class="label ' + phaseColorClass(data.CurrentStepID) + '">Pending Submission</span></div>';
			        }
			        if (value == 'Waiting for Approval') {
			            value = '<div><span class="label ' + phaseColorClass(data.CurrentStepID) + '">Waiting for Approval</span></div>';
			        }
			        if (value == 'PMO Verification') {
			            value = '<div><span class="label ' + phaseColorClass(data.CurrentStepID) + '">PMO Verification</span></div>';
			        }
			        if (value == 'Approved') {
			            value = '<div><span class="label ' + phaseColorClass(data.CurrentStepID) + '">Approved</span></div>';
			        }
			        if (value == 'Closed') {
			            value = '<div><span class="label ' + phaseColorClass(data.CurrentStepID) + '">Closed</span></div>';
			        }
			        if (value == 'Cancelled') {
			            value = '<div><span class="label label-grey">Cancelled</span></div>';
			        }
			        if (value == 'Submitted') {
			            value = '<div><span class="label ' + phaseColorClass(data.CurrentStepID) + '">Submitted</span></div>';
			        }

			        return value == '' ? '<div>TBD</div>' : value;
			    }
			},
            {
                title: "Owner", field: "Approvers", width: 150, visible: hasColumn(tabid, 'Checkers'), formatter: function (value) {
                    var data = value.getData();
                    value = value.getValue();
                    var reassign = ((value.indexOf('(' + g_s.user.UserID + ')') > 0 || machArr(g_s.user.RoleIDs, 1) || machArr(g_s.user.RoleIDs, 3) || machArr(g_s.user.RoleIDs, 5) || machArr(g_s.user.RoleIDs, 7) || machArr(g_s.user.RoleIDs, 12) || machArr(g_s.user.RoleIDs, 17) || machArr(g_s.user.RoleIDs, 22)) && data.CurrentStepID != 0)
                        ? '<button type="button" data-id="' + data.ID + '"  class="btn btn-bold btn-minier reassign-user" title="Re-assign User"><i class="ace-icon fa fa-users"></i></button>'
                        : '';
                    return "<div>" + reassign + '<span id="spnApprove">' + value + "</span></div>";
                }
            },
            { title: "Tower Lead", field: "TowerLead", width: 150, visible: hasColumn(tabid, 'TowerLead') },
            { title: "Project Lead", field: "ProjectLead", width: 150, visible: hasColumn(tabid, 'ProjectLead') },
			{ title: "Priority", field: "Priority", width: 100, visible: hasColumn(tabid, 'Priority') },
			{ title: "Last Modified", field: "ApprovedDate", width: 150, visible: hasColumn(tabid, 'ApprovedDate') }
        ];`


thank you

**Comment by olifolkerd** [comment]
Hey @yaxino 

Im afraid i still cant replicate the issue. which browser are you using? are you loading data via ajax at any point?

Could you post a working example to [JS Fiddle](https://jsfiddle.net/) or [CodePen](https://codepen.io/) so that i can see it in action.

Cheers

Oli

**Comment by yaxino** [comment]
I'm very sorry, I'm late.
this is my all codes(no JS Fiddle or CodePen):
`List.Default = function (id, tableData, columns,groupby) {
        var obj = new Object();
        obj.selector = '#' + id;
        obj.columns = List.Utils.getColumns(id, columns);
        obj.groupby = groupby;

        //render tabulator
        obj.render = function () {
            $(obj.selector).append('<div class="tabulator"></div>');
            $(obj.selector + ' .tabulator').tabulator({
                data: tableData,
                groupBy: obj.groupby,
                groupStartOpen:false,
                height: $(obj.selector).height() + 'px',
                layout:'fitColumns',
                movableColumns: true, 
                columns: obj.columns
            });

            //$(obj.selector + ' .tabulator').tabulator('setData', tableData);

        }
        obj.resetData = function (newData) {
            $(obj.selector + ' .tabulator').tabulator('setData', newData);
        }
        obj.sort = function (column, dir) {
            $(obj.selector + ' .tabulator').tabulator('setSort', column, dir);
        }
        obj.setNewColumns = function (newColumns) {
            $(obj.selector + ' .tabulator').tabulator("setColumns", newColumns, true)
        }
        obj.downloadCSV = function () {
            //Tabulator.extendExtension("download", "downloaders", {
            //    string: function (columns, data, options) {
                    
            //        var fileContents = data.toString();
            //        return 'data:application/csv;charset=utf-8,' + encodeURIComponent(fileContents);
            //    }
            //});
            $(obj.selector + ' .tabulator').tabulator("download", "xlsx", "GPMP DASHBOARD.xlsx");
        }
        //the end return obj
        return obj;
    }`

**Comment by olifolkerd** [comment]
This should be resolved in version 3.4 when it is released tomorrow.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Tabulator version 3.4 has now been officially release!

You can find details of the new release in the [News Section](http://tabulator.info/news)

Full documentation of all the new features can be found [Here](http://tabulator.info/docs/3.4)

Cheers

Oli :)
