### ISSUE TITLE
Can't find variable: hasIndex

### ISSUE THREAD

**Issue by andybutkaj** [olifolkerd/tabulator#780]
Latest version gives me this error in Safari... same with CDN version and downloaded min.js version. It's for the tables which are automatically imported from HTML.

Version from October works fine.

**Comment by olifolkerd** [comment]
Hey @andybutkaj 

Could you give an example of the function you are calling when you get this error? and when you say latest version could you provide a version number.

Cheers

Oli

**Comment by andybutkaj** [comment]
Thank you for your answer. The version I tried was 3.3.2.

Code:
`            $("[id^=table-participants]").tabulator({
                fitColumns:true,
                colResizable:false,
                movableCols:true,
                selectable:true,
                height: 500,
            });`


Currently I'm using older version and it transfers my html table (with tabulator params) into filtered searchable jquery table - works quite well.

Note: I also debugged where exactly the error occured and where hashIndex is missing. Putting hasIndex = false, just before the line with a jQuery error helped that the table was transferred from HTML and jQuery did not stop executing the script with an error. But I found, that the table content in the columns was mixed (ie. same content in more columns) and I did not investigate further. Let me know if you need more information.

**Comment by olifolkerd** [comment]
could you post a copy of the HTML table you are trying to parse, that would really help in finding the issue.

Cheers

Oli

**Comment by andybutkaj** [comment]
Yes, sorry! It failed to parse all our dynamically generated tables, but for example this one: 

`<div class="table-wrapper">
<table id="table-candidates-9" class="alt small">
<thead><tr><th width="50" tabulator-headerFilter="input"> ID</th><th width="50" tabulator-headerFilter="input">Application ID</th><th width="150" tabulator-headerFilter="input" tabulator-headerFilter="true">Firstname</th><th width="150" tabulator-headerFilter="input" tabulator-headerFilter="true">Lastname</th><th width="250" tabulator-headerFilter="input" tabulator-formatter="email">Email</th><th tabulator-headerFilter="input" tabulator-headerFilter="true">Nationality</th><th tabulator-headerFilter="input" tabulator-headerFilter="true">Birth Date</th><th width="50" tabulator-headerFilter="input">Gender</th><th width="50" tabulator-headerFilter="input">Shortlisted</th><th width="50" tabulator-headerFilter="input">Verified</th><th width="50" tabulator-headerFilter="input">OSCE</th><th width="50" tabulator-headerFilter="input">UPEACE</th><th tabulator-headerSort="false" tabulator-formatter="html" tabulator-download="false"> </th></tr></thead>
<tr><td>646</td><td>2965</td><td>example</td><td>example</td><td>email@example.com</td><td>UK</td><td>1986-01-01</td><td>F</td><td>4</td><td>1</td><td>0</td><td>0</td><td><a href="index.php?go=account&do=documents&person_id=1">View Documents</a></td></tr>
</table>
</div>
`

**Comment by olifolkerd** [comment]
Thanks for that, great help!

Yup that is definitely a bug, i have pushed a fix for it to the master branch and will include it in the patch release later in the week.

Cheers

Oli

**Comment by andybutkaj** [comment]
Thank you! Have a Happy Holiday season! 
Cheers 
Andy

**Comment by olifolkerd** [comment]
I will be publishing a patch release including this fix this evening

**Comment by andybutkaj** [comment]
Perfect! I’ll test it most probably tomorrow! Thanks a lot. And happy new year!
