### ISSUE TITLE
Transpose Data?

### ISSUE THREAD

**Issue by mconnelley** [olifolkerd/tabulator#781]
Hello,
Is there functionality to flip the rows and the columns?  I have a large data set with many columns and a few rows.  So the user does not have to scroll left/right a lot I was wanting to have my rows become the columns and the columns become the rows.

By the way I am a huge fan of tabulator.  It has helped me out a lot in figuring great way to display my data sets visually.

-Thanks.

**Comment by olifolkerd** [comment]
Hey @mconnelley 

Thanks for getting in touch, and thanks for your kind words about Tabulator.

There is no way to do this built in to tabulator, but you could easily create two different column definition arrays and alternate between them using the ***setColumns*** function.

You would also need a function to parse through your data array and flip the data around but that should also be fairly easy to implement.

Let me know if you need any pointers on this.

Cheers

Oli

**Comment by mconnelley** [comment]
Oli,

Thanks for the information.  I will work towards the solution you suggested.  If you already have an example of how you have done this I will gladly take any and all pointers on this.  That way I can hopefully learn how to develop the best solution for what I am looking for.

Thanks again.

-Mconnelley

**Comment by manishji123** [comment]
I am trying out tabulator and it is just amazing.. However I have a similar requirement for transposing the rows @mconnelley / @olifolkerd -Can you please give some more pointers or an example.

Thanks,
Manish
