### ISSUE TITLE
Column Calculation is not removed after column definitions changed

### ISSUE THREAD

**Issue by lrowleyUB** [olifolkerd/tabulator#782]
Hi Oli,

Hopefully I will explain this correctly because it is a bit complicated!

I am creating column layouts dynamically based on user input. The first view (A) has column calculations. The second view (B) does not. When user switches from from A to B via Ajax request,  I specifically remove topCalc from the column on server side, and call "setColumns" method client side. However the columns still have the same field names, and it appears to recalculate instead of being removed. I tried using methods "clearData" and "redraw" to remove the calculation but neither appear to work. Is there something else I should try?

Thank you!
Laura

**Comment by olifolkerd** [comment]
Hi @lrowleyUB 

Thanks for getting in touch.

Could you provide an example of both of the column definitions arrays so i have something i can test against, also could you confirm the version number of the Tabulator library you are using?

Cheers

Oli
