### ISSUE TITLE
Custom Column Calculation Based on Other Column Calculations

### ISSUE THREAD

**Issue by hunsinger08** [olifolkerd/tabulator#785]
I've used the Custom Column Calculation Example successfully but am wondering how to use the quotient of bottomCalc values from two other columns in the table?

(I'm using bottomCalc:"sum" on the other two columns.  I want to divide their values by one another as the third bottomCalc in the table.)

**Comment by olifolkerd** [comment]
Hey @hunsinger08 

You would need to use a custom column calculation function for this, have a look at the (Column Calculations Documentation)[http://tabulator.info/docs/3.3#calculations]

You have access to all of the columns data in this function and can perform any calculations you want and return the result.

Cheers

Oli

**Comment by RyhillSibaprasad** [comment]
Hai Oli,
Thanks to giving such a good answers in Tabulator

my issue is when i'm generating my Report in Tabulator version - 3.5.3. the column calculation is generating every page (Pagination) my requirement is it will show only in Last Page can u help this issue ?
![page_1](https://user-images.githubusercontent.com/37332145/50080872-1adf8080-0213-11e9-91e0-479a851e521b.jpg)
![page_2](https://user-images.githubusercontent.com/37332145/50080874-1adf8080-0213-11e9-8f87-966c5154cd56.jpg)
![page_3](https://user-images.githubusercontent.com/37332145/50080875-1b781700-0213-11e9-8fe5-a4d232d1a74c.jpg)

**Comment by olifolkerd** [comment]
@RyhillSibaprasad as i have already told you in the past if you are having trouble that you think is a bug you MUST CREATE YOUR OWN ISSUE FOR IT.

Posting unrelated issues on old closed issues only confuses users. If you continue to behave like this i will start deleting your posts to keep issues clear.
