### ISSUE TITLE
Can I combining movable rows with data grouping - so if I move one row from group A to group B it changes the appropriate values?

### ISSUE THREAD

**Issue by AndrewHutcheson** [olifolkerd/tabulator#786]
So I want a rowhandle listener that knows when it's been moved to a different group. In the documentation example there's the male/female group split. So if I move a row on there I want it to change the gender.

**Comment by olifolkerd** [comment]
Hey @AndrewHutcheson 

That is a very interesting question you ask there, and you could certainly trigger an action in the ***rowMoved*** callback but you wouldnt know the new group the row is in.

I can see a whole set of fuctionality i could add to make this more use full.

- getGroup function on the row component
- rowRemoved callback on a group
- rowAdded callback on a group
- a property to allow rows to be moved between groups or block it.

I will add these to the roadmap

Great idea you had there!

Cheers

Oli

**Comment by AndrewHutcheson** [comment]
Alright so I have a custom dropdown menu to change gender and I'm grouped by gender. 

I tried calling $("#tableID").tabulator("redraw", true); when my cellEdited callback is triggered. The callback gets called just fine but the table redraw call won't update the groups. Passing true in the function is supposed to redraw all rows, yes? Or do I need to use setData (not my preference as its technically slower, I want to redraw, not load and redraw)?

**Comment by olifolkerd** [comment]
Hey @AndrewHutcheson 

The ***redraw*** function will trigger a redraw of the data as it is currently organised, it will not trigger a regrouping of the data. you could use the ***setGroupBy*** function to trigger the regrouping:
```js
$("#example-table").tabulator("setGroupBy", "gender");
```
The next version of tabulator will be getting an overhaul to the row grouping functionality to ensure updates like this happen automatically.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @AndrewHutcheson 

i have just pushed an update to the 3.4 branch to make it so dragging a row between groups will update the appropriate values.

This branch will be released later today.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Tabulator version 3.4 has now been officially release!

You can find details of the new release in the [News Section](http://tabulator.info/news)

Full documentation of all the new features can be found [Here](http://tabulator.info/docs/3.4)

Cheers

Oli :)
