### ISSUE TITLE
Changing column width sometimes selects row

### ISSUE THREAD

**Issue by gregorydimitriadis** [olifolkerd/tabulator#787]
When I alter the width of a column, it will select the row in which I do that, so long as my mouse stays within that row during the entire motion.

Is this due to some configuration, possibly? Or if it is a default behavior, can I possibly disable it?

**Comment by olifolkerd** [comment]
Hey @gregorydimitriadis 

Could you post an example of this happening, the source code for your table constructor with a bit of sample data, or a video/gif of the issue.

which browser are you experiencing the issue in?

which version of tabulator are you using?

Cheers

Oli
