### ISSUE TITLE
Example of ajax get with authentication token

### ISSUE THREAD

**Issue by gabriele86** [olifolkerd/tabulator#788]
Hi

Can you provide an example for an ajax cal with token authentication?

**Comment by olifolkerd** [comment]
Hey @gabriele86 

That is a bit of an open ended question, how do you need to pass the token, as a header? as a parameter?

Have a look at the (Set Table Data Documentation)[http://tabulator.info/docs/3.3#ajax] it explains how to pass additional parameters with your ajax request. it also provides a link to the jQuery documentation that will take your through how to configure headers on the ajax request if that is what you need to do.

Cheers

Oli
