### ISSUE TITLE
Re-initiate editors on the fly

### ISSUE THREAD

**Issue by hohozhao** [olifolkerd/tabulator#79]
Hi @olifolkerd,

If I define my own editor "testEditor", which requires some external or global vars, so when the global vars change, how can I re-initiate my own "testEditor"?
```
        testEditor:function(cell, value, data){
            var editor = $(editor_global_var);
            return editor;
        },
```

**Comment by hohozhao** [comment]
I think this can be closed, as it is what I want now! Stupid again. :)

**Comment by olifolkerd** [comment]
that is correct :)
