### ISSUE TITLE
Question: JS modify value of a cell?

### ISSUE THREAD

**Issue by shayo** [olifolkerd/tabulator#790]
Is it possible to access a specific cell in a desired row and update its value dynamically in javascript?

**Comment by olifolkerd** [comment]
Hey Shayo,

There are loads of ways to do this, could you give a bit more detail about how this function is to be used so i can suggest the best solution for your usage case.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey Shayo,

There are loads of ways to do this, could you give a bit more detail about how this function is to be used so i can suggest the best solution for your usage case.

Cheers

Oli

**Comment by alataknet** [comment]
Hello
There are different ways, may be this example can help you ?
did you try this
```
 cellEdited: function (cell) {
                        var row = $("#my_table").tabulator("getRow", cell.cell.row.data.id);
                         row.update({"field": field_value});
}
```

**Comment by shayo** [comment]
Yes. Thank you. I think I figured it out now.

Shay Ohayon, PhD
Research Scientist, DiCarlo Lab, MIT
