### ISSUE TITLE
Question: Group by after table data set?

### ISSUE THREAD

**Issue by shayo** [olifolkerd/tabulator#791]
Version 3.3
Is there a way to regroup the table after the data has been set?

Alternatively, how can I destroy the table and recreate a new one?

**Comment by olifolkerd** [comment]
Hey @shayo 

Have a read through the (Grouping Documentation)[http://tabulator.info/docs/3.3#ajax]

You can use the ***setGroupBy*** function for this:
``js
$("#example-table").tabulator("setGroupBy", "gender");
```

Cheers

Oli
