### ISSUE TITLE
remote pagination - c# webforms

### ISSUE THREAD

**Issue by lubosmarek** [olifolkerd/tabulator#794]
Hello,
I am trying to set the remote pagination but the code is not working:
```
 $("#example-table").tabulator({
                columns: [ //Define Table Columns
                    { title: "Name", field: "Name", sorter: "string", frozen: true},
                    { title: "Value", field: "Value", sorter: "string" },
                    { title: "Category", field: "Category", sorter: "string"}

                ],
                ajaxResponse: function (url, params, response) {

                    return response.d; //return the tableData peroperty of a response json object
                },
                ajaxURL: "ws.aspx/GetItemsList",
                ajaxConfig: "POST",
                pagination: 'remote',
                paginationSize: 5
            });
```
I think there is a problem that the sending data (page, size) is not in Json format and due to this the params not come to my method:

there is screen from Google Chrome (Developer tool):

![data](https://user-images.githubusercontent.com/18445569/34254692-6f72b276-e64d-11e7-977c-e3d24a5a938d.PNG)

and C# code:

```

 [WebMethod]
    public static string GetItemsList(string size, string page)
```

Any idea? thanks

**Comment by olifolkerd** [comment]
Hey @lubosmarek 

Do you get any errors showing up in your console log?

what is the structure of the JSON object you are returning?

Cheers

Oli
