### ISSUE TITLE
How to add a custom pagination element like pages 1-2-3 on the main page of your site?

### ISSUE THREAD

**Issue by Qwentor** [olifolkerd/tabulator#796]
How to add a custom pagination element like pages 1-2-3 on the main page of your site?
Can't find in documentation

**Comment by olifolkerd** [comment]
Hey @Qwentor 

Do you want to create your own custom pagination element to control Tabulator or move Tabulators existing pagination controls into your own element elsewhere on the page?

Cheers

Oli

**Comment by Qwentor** [comment]
Hmm...
In Chrome browser it works fine https://prnt.sc/htgx1g
In Firefox (version 57.0.2) it does not work http://prntscr.com/htgxad
Buttons 1-2-3-4-5 are invisible

**Comment by olifolkerd** [comment]
do you get any errors in the console?

could you post a copy of your table constructor so i can test against it please.

Cheers

Oli

**Comment by Qwentor** [comment]
`$("#koefs_table").tabulator({
		layout:"fitColumns",
		history:true,
		pagination:"local",
		paginationSize:20,
		columns:[
			{title:"User name", field:"username", sortable:true, tooltip: true, headerFilter:true, headerFilterPlaceholder:"Search..."},
			{title:"Deposit", field:"bt_sum", sortable:true, tooltip: true, headerFilter:selectEditor},
			{title:"First start date", field:"bt_start", sortable:true, tooltip: true},
			{title:"Day", field:"day_period", sortable:true, tooltip: true},
			{title:"Profit", field:"profit", sortable:true, tooltip: true},
			{title:"Max daily profit", field:"max_day_profit", sortable:true, tooltip: true}
				
		]
	});`

But after I update my Firefox to 57.0.3 all works fine.

**Comment by olifolkerd** [comment]
Hey @Qwentor 

That sounds like a transient rendering bug in firefox that they have now fixed, let me know if it pops up again.

Cheers

Oli
