### ISSUE TITLE
Custom editor (select menu) where display value and editor value are different

### ISSUE THREAD

**Issue by AndrewHutcheson** [olifolkerd/tabulator#798]
So in the example in the docs we have:
```
<select>
	<option value = "men">men</option>
	<option value = "women">women</option>
</select>
```

and the value is passed by 

```
editor.on("change blur", function(e){
	success(editor.val());
});
```

What I want to do is assign a different value, like:

```
<select>
	<option value = "1">men</option>
	<option value = "2">women</option>
</select>
```

Is there a way to do this?

**Comment by AndrewHutcheson** [comment]
I'm thinking I'd have to have a hidden table column with the val (1|2) and a visible one with the display (men|women). How would I update two values at once?

**Comment by olifolkerd** [comment]
Hey @AndrewHutcheson 

This should be fairly simple, if you do this as a custom formatter and use the ***formatterParams*** option to pass in an array of objects that contain a ***title*** property and a ***value*** property, you could then use this to build your options object.

Cheers

Oli

**Comment by AndrewHutcheson** [comment]
Works, thanks.
