### ISSUE TITLE
How to add row into ASP.Net database

### ISSUE THREAD

**Issue by hkbeer** [olifolkerd/tabulator#799]
My web server is IIS and web page is asp.net with database
I can see there is a add row function in this tabulator.js
When user add row in this JS, how to make my C# code fire and add such row of data to the database ?
Any sample code ?

Pls help. Thanks

**Comment by olifolkerd** [comment]
Hey @hkbeer,

This isnt really a Tabulator question, how you communicate with your server is up to you. usually it would be done with a POST or PUT ajax request depending on what your are trying to achieve.

You can use any of Tabulators many [Callbacks](http://tabulator.info/docs/3.3#callbacks) to trigger your communication code, depending on when you want to make the request, in your question you mention adding a row, in that case you want to use the ***rowAdded*** callback:

```js
$("#example-table").tabulator({
    rowAdded:function(row){
        //row - row component

        var data = row.getData(); //get the data object for the row

        //Make your ajax request here
    },
});
```

I hope that helps.

Cheers

Oli

**Comment by hkbeer** [comment]
Thanks
