### ISSUE TITLE
Alternating Row Back Color

### ISSUE THREAD

**Issue by pujasanjay** [olifolkerd/tabulator#8]
Sir
Kindly consider adding a property of Alternating RowBack Color. 

Regards

Sanjay

**Comment by olifolkerd** [comment]
Great idea!, will get that in this weekend

**Comment by olifolkerd** [comment]
This has now been added in the latest release 1.8.1.

The ***rowAltBackgroundColor*** options parameter can be used to set the alternate row colour.

**Comment by diffcultpro** [comment]
Is there any example for  rowAltBackgroundColor ？

**Comment by olifolkerd** [comment]
This option no longer exists, as of version 3.0 all styling is contained in the sass files.

There is now a ***$rowAltBackgroundColor*** vairable at the top of each of the theme scss files *(found in /src/scss directory)* which you can change and then use ***gulp*** to compile to a new css file.

alternatively you could override the css with the following:

```js
.tabulator .tabulator-row.tabulator-row-even{
    background-color: #f00 !important;
}
```

Cheers

Oli
