### ISSUE TITLE
Keep selected row

### ISSUE THREAD

**Issue by leonardorame** [olifolkerd/tabulator#80]
Hi, I didn't know this component until now and it looks really neat, a candidate to replace DataTables in some of my apps.

What I don't see in the examples is a way to keep displaying the currently selected row, something like the "select" plugin from DataTables.

**Comment by olifolkerd** [comment]
At the moment there is no inbuilt way to do this, but this is next on the road map. 

In the mean time it is fairly easy to implement yourself.

All you need to do is have a column that you use for selecting your rows (could be a tick box a handle or anything, your choice), see the field to ***selected*** or any particular field name that fits in with your scheme. if you are using a check box then you should use the ***tick*** editor to allow users to toggle the selected state of the row.

You can then use the ***rowFormatter*** callback to format selected rows appropriately:
```js
$("#example-table").tabulator({
    rowFormatter:function(row, data){
        //row - JQuery object for row
        //data - the data for the row

        if(data.selected){
            row.css({"background-color":"#A6A6DF"});
        }
    },
});
```

**Comment by leonardorame** [comment]
Great!, that's what I need.

BTW, new question. how can I get a reference to that selected row from the outside?, somethig like $('#example-table').rows[0].data.selected. I hope you understand what I mean...

**Comment by olifolkerd** [comment]
you could use the row formatter to add a class to the selected row:
```js
$("#example-table").tabulator({
    rowFormatter:function(row, data){
        //row - JQuery object for row
        //data - the data for the row

        if(data.selected){
            row.css({"background-color":"#A6A6DF"});
            row.addClass("selected");
        }else{
            row.removeClass("selected");
        }
    },
});
```

**Comment by leonardorame** [comment]
Here's an example of what I need:

`$("#example-table").tabulator(....);

$("#button1").click(function() {
    var selectedRow = $(#example-table").tabulator.getSelectedRow();
    console.log(selectedRow.data);
});`

Something like that, is it possible?.

**Comment by leonardorame** [comment]
Sorry, I found it `var data = $("#example-table").tabulator("getData");`

That returns the internal data object, now I need to iterate over it and get all the `.selected` values.

**Comment by olifolkerd** [comment]
that is correct

**Comment by olifolkerd** [comment]
There is now a new selectable rows feature which may be exactly what you are after!

If you set the ***selectable*** option to true in your constructor then it will allow rows to be seleted
```js
$("#example-table").tabulator({
    selectable:true,
});
```

You can then use the ***getSelectedData*** function to retrieve the data from the selected rows:
```js
var selectedRows = $("#example-table").tabulator("getSelectedData");
```

Full details can be found in the documentation [here](http://olifolkerd.github.io/tabulator/docs/#selectable)

Happy Tabulating!

Oli
