### ISSUE TITLE
Tooltips via editor

### ISSUE THREAD

**Issue by markomijat** [olifolkerd/tabulator#801]
Hello Oli,

Can you please help me with one thing : 
I am trying to define  the tooltips for a particular column via my customized autocomplete editor.
In my editor, I make an ajax call, and instead of having as a tooltip the actual value passed to the cell , I wish some other data showing up as a tooltip  when I hover the cell. (i.e. the description). I have access to this description only in my editor. How can I use it to define my tooltip ?

Thanks !

**Comment by olifolkerd** [comment]
Hey @markomijat 

Thanks for getting in touch,

are you setting that value on a cell by cell basis or per column? is it just one column or multiple?

Cheers

Oli

**Comment by markomijat** [comment]
Hi,
I am setting it on a cell by cell basis.
Whichever column is defined with my autocomplete editor will have the cells of that column behaving the same way.
The value-description pair for a cell will depend on the selected item from the autocomplete list and will normally be different for each cell. It is the description I want to use as a tooltip and not the value.

in the editorParams I am passing : 
- url for the data 
- "valeur"   : a string with the name of the database field I am using as a value to pass to a cell, 
- "description"   : a string with the name of the database field I want to use as a description in the autocomplete list.

So to summarize :  I was wondering if I could somehow define the tooltip by using item[editorParams.description] .

Here's my editor code : 

`var autoCompleteEditor = function(cell, onRendered, success, cancel, editorParams){
    //cell - the cell component for the editable cell
    //onRendered - function to call when the editor has been rendered
    //success - function to call to pass the succesfully updated value to Tabulator
    //cancel - function to call to abort the edit and return to a normal cell
    //editorParams - editorParams object set in column defintion   
    

    var valeur = "";    
    var editor = $("<input id='acinput'/>");   
         
    editor.css({
        "padding":"3px",
        "width":"100%",       
    });

    //Set value of editor to the current value of the cell
    editor.val(cell.getValue());

    //set focus on the select box when the editor is selected (timeout allows for editor to be added to DOM)
    onRendered(function(){
      editor.focus();
    });

    //when the value has been set, trigger the cell to update
    editor.on("change blur", function(e){                
        // checking if cell value corresponds to a selected item from autocomplete list
        if(valeur == editor.val() ) {
         success(editor.val());   
        } else {            
         success();    
        }       
    });       
    
    
    $(function(){              
    $( "#acinput" ).autocomplete({
       
    minLength: editorParams.minLength,     
      
    source : function(request, response) {
    // response  is a jquery function
    // request is an object with one field : term (containing whatever is typed in the input box)        
    
        $.ajax({      
      url : editorParams.url,      // passed in as editor parameter
      data : {term: request.term}, 
      type : "POST",
      dataType : "json",
      success : function(data){           
        // mapping data in order to have label and value fields - must for autocomplete widget                    
          response($.map( data, function( item ) {             
                return {                                                          
                    label: item[editorParams.valeur] + " - " + item[editorParams.description],
                    value: item[editorParams.valeur]
                }
            }));          
      },
     error : function (xhr,status,error) {
         console.log('Error !');
         console.log('xhr:', xhr);
         console.log('status:', status);
         console.log('error:', error);         
     }
     });       
        
    },  
        
    select: function( event, ui ) {       
        valeur = ui.item.value;        
    },       
    
   // adding classes to autocomplete list and list elements for css styles
    }).data("uiAutocomplete")._renderItem = function (ul, item) {     
     $(ul).addClass("mmACMenu");      
    var html = "<div class = 'mmACElement'>" + item.label + "</div>";    
    var t = $("<li></li>").data("item.autocomplete", item).append(html);         
     $(t).addClass("mmACItem");    
    return t.appendTo(ul);
 };        
  });          
    //return the editor element - tabulator
    return editor;
};` 

Cheers

**Comment by markomijat** [comment]
Hi,
I am setting it on a cell by cell basis.
Whichever column is defined with my autocomplete editor will have the cells of that column behaving the same way.
The value-description pair for a cell will depend on the selected item from the autocomplete list and will normally be different for each cell. It is the description I want to use as a tooltip and not the value.

in the editorParams I am passing :

1. url for the data
2. "valeur" : a string with the name of the database field I am using to get the value I want to pass to a cell
3. "description" : a string with the name of the database field I want to use as a description in the autocomplete list.

So to summarize : I was wondering if I could somehow define the tooltip by using item[editorParams.description] .

Here's my editor code :
```
var autoCompleteEditor = function(cell, onRendered, success, cancel, editorParams){
    //cell - the cell component for the editable cell
    //onRendered - function to call when the editor has been rendered
    //success - function to call to pass the succesfully updated value to Tabulator
    //cancel - function to call to abort the edit and return to a normal cell
    //editorParams - editorParams object set in column defintion   
    

    var valeur = "";    
    var editor = $("<input id='acinput'/>");   
         
    editor.css({
        "padding":"3px",
        "width":"100%",       
    });

    //Set value of editor to the current value of the cell
    editor.val(cell.getValue());

    //set focus on the select box when the editor is selected (timeout allows for editor to be added to DOM)
    onRendered(function(){
      editor.focus();
    });

    //when the value has been set, trigger the cell to update
    editor.on("change blur", function(e){                
        // checking if cell value corresponds to a selected item from autocomplete list
        if(valeur == editor.val() ) {
         success(editor.val());   
        } else {            
         success();    
        }       
    });       
    
    
    $(function(){              
    $( "#acinput" ).autocomplete({
       
    minLength: editorParams.minLength,     
      
    source : function(request, response) {
    // response  is a jquery function
    // request is an object with one field : term (containing whatever is typed in the input box)        
    
        $.ajax({      
      url : editorParams.url,      // passed in as editor parameter
      data : {term: request.term}, 
      type : "POST",
      dataType : "json",
      success : function(data){           
        // mapping data in order to have label and value fields - must for autocomplete widget                    
          response($.map( data, function( item ) {             
                return {                                                          
                    label: item[editorParams.valeur] + " - " + item[editorParams.description],
                    value: item[editorParams.valeur]
                }
            }));          
        //myOutput(data);
      },
     error : function (xhr,status,error) {
         console.log('Error !');
         console.log('xhr:', xhr);
         console.log('status:', status);
         console.log('error:', error);         
     }
     });       
        
    },  
        
    select: function( event, ui ) {       
        valeur = ui.item.value;        
    },       
    
   // adding classes to autocomplete list and list elements for css styles
    }).data("uiAutocomplete")._renderItem = function (ul, item) {     
     $(ul).addClass("mmACMenu");      
    var html = "<div class = 'mmACElement'>" + item.label + "</div>";    
    var t = $("<li></li>").data("item.autocomplete", item).append(html);         
     $(t).addClass("mmACItem");    
    console.log(': nb results');
    return t.appendTo(ul);
 };        
  });      
    
    //return the editor element - tabulator
    return editor;
};

```

**Comment by olifolkerd** [comment]
Hey @markomijat 

Sorry for the delay in replying.

I would recommend that you set the tooltip description to another value in your row data (you don't have to set it as a row) then you can pass a function to the tooltip property that looks it up from this value.

I hope that helps,

Cheers,

Oli :)
