### ISSUE TITLE
Is there any way to select columns?

### ISSUE THREAD

**Issue by donnyv** [olifolkerd/tabulator#802]
I'm thinking when a user clicks anywhere left of the sort arrow in a field it selects the whole column. This can be done to multiple columns like the row select. Probably have access to an array of selected columns in the api. This would give developers an option to apply an action against these selected columns like hiding the selected ones or deleting them.

**Comment by olifolkerd** [comment]
Hey @donnyv 

You could you the ***headerClick*** callback in the column definition to trigger the action on a click of the column header, then use the ***getCells*** function on the column component passed into the callback to iterate through each of the cells to apply a class to them that you could then style:
```js
{title:"Name", field:"name", headerClick:function(e, column){
        //e - the click event object
        //column - column component

        var cells = column.getCells();

        cells.forEach(function(cell){
            cell.getElement().addClass("column-selected");
        });
    },
}
```

let me know if that helps.

Cheers

Oli

**Comment by donnyv** [comment]
But if you had the sorted feature on. Would this trigger a sort also?

**Comment by olifolkerd** [comment]
you could call `e.stopPropagation()` to prevent the sort from occurring

**Comment by donnyv** [comment]
Yeah this is the issue. What if you want 2 click areas assigned to the column header? 

This could be solved by adding hooks into the rendering of the header. Then a dev could create what ever they want in the headers. Add icons, buttons, dropdowns, multiple click surfaces, etc.

**Comment by olifolkerd** [comment]
Hey @donnyv 

A **headerFormatter*** callback is on the roadmap for a future release, but going into much more detail that that would be a bit of an edge case based on previous Tabulator usage cases.

The functionality you are after could still be achieved through the ***headerClick*** callback, you can use the ***target*** property of the event object passed into the callback to determine which of the elements in the header was clicked and then take the appropriate action based on that:

```js
var target = e.target;
```

Cheers

Oli
