### ISSUE TITLE
line chart use html table tag unsuccessful, help

### ISSUE THREAD

**Issue by hkbeer** [olifolkerd/tabulator#803]
I am using html table tag as data to display line chart (sparkline) but it is not displaying the data correctly.
The text column is displaying correctly though.

My values for line chart is 10,5,2,1,6,8
Now my tag is like
`<td>10 5 2 1 6 8</td>`
The line chart shows the points 1,0,0,5,0,2,0,1,0,6,0,8
Seems it treat 0 in 10 and comma as a separate 0 value items
I tried 
`<td>10,5,2,1,6,8</td>` then it becomes a flat line having all commas converted to NaN.
I also tried `[10,5,2,1,6,8]` in <td> then it becomes a flat line having some values NaN on square bracket and commas..
Pls help, how can I fix this up ? Thanks

My code
 ```
<thead>
			<tr>
				<th>Country</th><th>line</th>
			</tr>
		</thead><tbody>
			<tr>
				<td>US</td><td>10 5 2 1 6 8</td>
			</tr><tr>
				<td>UK</td><td>10 5 2 1 6 8</td>
			</tr>
var lineFormatter = function (cell, formatterParams) {
                setTimeout(function () { //give cell enough time to be added to the DOM before calling sparkline formatter
                    cell.getElement().sparkline(cell.getValue(), { width: "100%", type: "line", disableTooltips: true });
                }, 10);
            };
 columns: [ //Define Table Columns
{title:"line", field:"line", formatter:lineFormatter},
                ],
```

**Comment by olifolkerd** [comment]
Hey @hkbeer,

The issue you have is that any value you are parsing in from your HTML table is being entered as a string and the spark-line formatter is expecting an array. 

To get round this you should use a mutator on the line column. If we work with your space separated list then we need the following mutator

```js

//create mutator
var arrayMutator = function(value, data, type, mutatorParams, cell){
    return value.split(" "); //create an array from the space separated value
}

//use mutator in column definition
{title:"line", field:"line", formatter:lineFormatter, mutator:arrayMutator },
```
For more information see the [Mutator Documentation](http://tabulator.info/docs/3.3#get-set)

Cheers

Oli
