### ISSUE TITLE
Possible to pay for consultation?  I'm stumped already!

### ISSUE THREAD

**Issue by adstore** [olifolkerd/tabulator#804]
Hi - I'm sorry I'm having some difficulty understanding how to install and use your program.  I have been using Mobirise 4.x to create my data tables (usually just a few hundred records per page) but I'd like to upgrade to yours and go to larger (1000+ records) tables that load quickly, without resorting to PHP/MySQL.  (I do own AppGini by BigProf but find that its tables are rather drab on mobile devices). 

Here is a typical local application I created using Mobirise: http://servingsooke.com/Arts-Community.html.   Note that individual field contents can be formatted and hyperlinked, and there is a search function that filters the records.  

Key concerns: 

1.  It's awkward to insert or rearrange records for the default view presentation, especially given the size of the code surrounding each record.
2.  The record data is shown explicitly in the html file, and the links are vulnerable to immediate bulk copy and extraction to competing sites.  I'd prefer to find a way to discourage this.
3.  The data scrolls somewhat slowly, and I've had memory issues when using much more than 300 records.
4.  Very little flexibility in the layout - it's a generic tool with almost no options.

My initial goal is to create a dynamic classified directory (read-only for public users) with individual records linked to detailed local PDF's (compared to the traditional sub-sub-category structures of typical classified sites and tedious paging through unsorted results).

I copied the files in the "dist" directory of your version 3.3 download onto my test site, and uncertain as to how to place them, I did it this way:
![image](https://user-images.githubusercontent.com/34956770/34452669-d68cefe6-ecf9-11e7-8f6f-ff79bec9a0e9.png)
![image](https://user-images.githubusercontent.com/34956770/34452671-e57052f0-ecf9-11e7-84dd-ccd7be34bfd2.png)

I then did a pure cut/paste of your "basic example" (http://tabulator.info/quickstart/3.3), and created an html file and posted it on my test site: www.adscanusa.com/tabulator/test1.html .  It failed.  Obviously quite a few more standard html elements are required!!

Could I please pay you to show me what the directory contents should look like and what a basic table like the one I am already using requires in terms of a standalone, ready-to-run HTML file?  Also, is there a way of "hiding" the source data file itself?  Clearly the Virtual DOM approach is critical in this case.  

Your program appears to be amazing and certainly saleable, but it seems like it may take a long time for me to get it working - there are obviously much smarter people using it without problems!

Thank you!

Sooke, British Columbia, Canada

**Comment by vipera7** [comment]
Hey adstore,

I inspected your test1.html, you need to add jquery and tabulator at the top of the page put your code in javascript tag () and you have  : 
```
<script type="text/javascript" src="jquery.min.js"></script>
<script type="text/javascript" src="jquery-ui.min.js"></script>
```
after that you're ready to add tabulator:
```
<link href="tabulator.min.css" rel="stylesheet">
<script type="text/javascript" src="tabulator.min.js"></script>
```
and you declare your tabulator object with: 
```
<div id="example-table"></div>
<script type="text/javascript">

//create Tabulator on DOM element with id "example-table"
--
  | $("#example-table").tabulator({
  | height:205, // set height of table, this enables the Virtual DOM and improves render speed dramatically (can be any valid css height value)
  | layout:"fitColumns", //fit columns to width of table (optional)
  | columns:[ //Define Table Columns
  | {title:"Name", field:"name", width:150},
  | {title:"Age", field:"age", align:"left", formatter:"progress"},
  | {title:"Favourite Color", field:"col"},
  | {title:"Date Of Birth", field:"dob", sorter:"date", align:"center"},
  | ],
  | rowClick:function(e, row){ //trigger an alert message when the row is clicked
  | alert("Row " + row.getData().id + " Clicked!!!!");
  | },
  | });
  |  
  | //define some sample data
  | var tabledata = [
  | {id:1, name:"Oli Bob", age:"12", col:"red", dob:""},
  | {id:2, name:"Mary May", age:"1", col:"blue", dob:"14/05/1982"},
  | {id:3, name:"Christine Lobowski", age:"42", col:"green", dob:"22/05/1982"},
  | {id:4, name:"Brendon Philips", age:"125", col:"orange", dob:"01/08/1980"},
  | {id:5, name:"Margret Marmajuke", age:"16", col:"yellow", dob:"31/01/1999"},
  | ];
  |  
  | //load sample data into the table
  | $("#example-table").tabulator("setData", tabledata);


</script>
```

You're ready to go
