### ISSUE TITLE
Is there a way to know the previous value of a cell on the cellEdited callback? OR which cell/column# was edited?

### ISSUE THREAD

**Issue by AndrewHutcheson** [olifolkerd/tabulator#805]
So I have a kind of "totals" column - it's a checkbox if all other checkboxes in the row are unchecked/checked. It is toggled on either the other cells being checked, or checking it makes all the other cells unchecked/checked.

However I can only do half of the functionality, because I cannot distinguish between if all the rows were checked and one was unchecked or if the totals row was checked. (and vice versa).

So what I need is either:
- to know the previous value of what was edited
- to know the column name of the cell that was edited or
- be able to have different cellEdited listeners on each column  (probably a more useful improvement to tabulator)

The only thing I can think of is to have a column-based cellEditing callback that toggles a control variable within my cellEdited function. This seems clunky though - is this the best solution?

**Comment by AndrewHutcheson** [comment]
nevermind I'm dumb I forgot I can do cell.getColumn

I do however think that column-based edited listeners would be useful, that way I don't have to shove everything into one edit function.

**Comment by olifolkerd** [comment]
Hey @AndrewHutcheson 

Great idea on the column event listeners, i will add these to the roadmap!

I will reopen this issue and close it when the feature has been added

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @AndrewHutcheson 

You will be happy to hear just pushed some updates to the 3.4 branch to add the ***cellEditing***, ***cellEdited*** and ***cellEditCancelled*** in the column definitions as well as for the table as a whole.


The 3.4 update should be released in the next couple of weeks.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Tabulator version 3.4 has now been officially release!

You can find details of the new release in the [News Section](http://tabulator.info/news)

Full documentation of all the new features can be found [Here](http://tabulator.info/docs/3.4)

Cheers

Oli :)
