### ISSUE TITLE
Bugs? Grouping data does not refresh when adding new rows

### ISSUE THREAD

**Issue by AndrewHutcheson** [olifolkerd/tabulator#806]
I have three issues:

1. When adding a new row to a table with data already in it, the group totals row does not update. The new row appears underneath the totals row. Is there a way to refresh the table on adding?

2. When I add the first row to an empty table, the group is not there and again the table needs to be refreshed. (actually if the table is initialized as empty, then the totals row just doesn't show up, even after adding rows, I have to sort or move stuff to trigger a refresh).

3. I am using tick as a formatter for a checkbox. I also have a count on my bottomCalc. When I change any row's checkbox, then the bottomCalc row glitches, displaying checkmarks instead of the number. I again have to trigger a manual refresh by sorting a column or something.

**Comment by AndrewHutcheson** [comment]
Actually here's another:

4. If I remove the last row in a group, the group row doesn't disappear (neither do any group calcs update).

**Comment by olifolkerd** [comment]
Hey @AndrewHutcheson 

The next release will include an overhaul to the row addition/deletion/moving functionality that should fix any issues with grouping.

If you have any examples of your table constructor that i could test against that would be great.

Cheers

Oli

**Comment by AndrewHutcheson** [comment]
Actually I had another:

5. the group total formatter doesn't work

{title:"Fee", 			field:"Fee",	 	formatter:"money", 	formatterParams:{symbol:"$", precision:2}, bottomCalc:"sum", bottomCalcFormatterParams :{symbol:"$", precision:2}},

This works just fine for the column, but not on the totals row. It totals correctly, but it does not format. No precision or symbol.

**Comment by olifolkerd** [comment]
Hey @AndrewHutcheson 

would you mind rasing that as another issue so i can track the progress in fixing it better.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @AndrewHutcheson 

You will be happy to hear i have just pushed a fix for all of these to the 3.4 branch.

It will be included in the release later today.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Tabulator version 3.4 has now been officially release!

You can find details of the new release in the [News Section](http://tabulator.info/news)

Full documentation of all the new features can be found [Here](http://tabulator.info/docs/3.4)

Cheers

Oli :)
