### ISSUE TITLE
bottomCalc on table total? (i.e. sum over all groups)

### ISSUE THREAD

**Issue by AndrewHutcheson** [olifolkerd/tabulator#807]
I want to show a super calculation of my values across all groups, that would be a nice feature.

Also, to be able to do that *and* do it for each group and subgroups if any.

**Comment by olifolkerd** [comment]
Hey @AndrewHutcheson 

Im not sure i follow you, there are [Column Calculations](http://tabulator.info/docs/3.3#calculations) already built into Tabulator. Do these not meet your needs?

Cheers

Oli

**Comment by hunsinger08** [comment]
I think what the intention is would be to have a "grand total" of the various group's "subtotals".

My application could also use this

**Comment by AndrewHutcheson** [comment]
Yes, what hunsinger08 said. I want a grand total.

**Comment by olifolkerd** [comment]
Good suggestion,

i will add that to the roadmap

Cheers

Oli

**Comment by hunsinger08** [comment]
Is there any way to make it work in the meantime?  Maybe using addRow but I couldn't get it to appear below the Subtotal Row.

**Comment by olifolkerd** [comment]
There is no direct way to do this at the moment,

The calculation rows are rendered in a different way to normal rows so you cannot trigger a row to be inserted around them;

You would have to manually create a row yourself in the table footer to handle this if you wanted to.

Sorry i couldnt be more help

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @AndrewHutcheson  and @hunsinger08 

You will be happy to hear i have just pushed an update for this to the 3.5 branch, which should be officially released later in the week.

There will be a new ***columnCalcs*** option that will let you enable the calculation for both:

```js
$("#example-table").tabulator({
    columnCalcs:"both", //show column calculations at top and bottom of table and in groups
});
```

You can get an advanced preview of the documentation [Here](http://tabulator.info/docs/3.5#calculations)

Cheers

Oli :)
