### ISSUE TITLE
Combining Undo/Redo Functions

### ISSUE THREAD

**Issue by Krigen** [olifolkerd/tabulator#808]
Is there a way to combine Tabulator's undo/redo functions with our own undo/redo functions?
Currently, my function works a cell is being edited. In Tabulator, I know in order for the undo/redo function to work, the table needs to be in focus, and no cells being edited.

**Comment by olifolkerd** [comment]
Hey @Krigen 

If you want to programatically trigger an undo/redo event on the table when the table is not in focus you can call the ***undo*** and ***redo*** functions:
```js
$("#example-table").tabulator("undo");
$("#example-table").tabulator("redo");
```

If you want to change the keybindings for the undo/redo actions this can be done in the ***keybindings*** setup property, more details of which can be found in the [Keybindings Documentation](http://tabulator.info/docs/3.3#keybindings)

Let me know if that helps

Cheers

Oli

**Comment by Krigen** [comment]
Here is my code so far:
```
function KeyPress(e) {
   var evtobj = window.event? event : e
//UNDO
   if (evtobj.keyCode == 90 && evtobj.ctrlKey){
     console.log('undo');
     undoRedoArr.push(changedArr.pop());
   }
//REDO
   if (evtobj.keyCode == 89 && evtobj.ctrlKey){
     console.log('redo');
     changedArr.push(undoRedoArr.pop());
   }
}
document.onkeydown = KeyPress;
```
I want my undo function to go off when tabulator's undo function goes off. If I'm editing a cell, I don't want my function to go off.

**Comment by olifolkerd** [comment]
Hey @Krigen 

if you are looking to use the undo events triggered in Tabulator then you would need add a couple of custom keybindings to the tabulator library then override the default undo/redo keybindings.

Before you instantiate your table , use the following code to setup your own bespoke keybindings

```js
Tabulator.extendExtension("keybindings", "actions", {
    "undoCustom":function(){ //delete selected rows
    	console.log('undo');
    	this.table.undo();
    	undoRedoArr.push(changedArr.pop());
    },
    "redoCustom":function(){ //delete selected rows
    	console.log('redo');
    	this.table.redo();
    	changedArr.push(undoRedoArr.pop());
    },
});
```

Then you need to remap the keyboard bindings in your table constructor:
```js
$(".table").tabulator({
	keybindings:{
		"undo" : false,
		"redo" : false,
		"undoCustom" : "ctrl + 90",
		"redoCustom" : "ctrl + 89"
	},
});
```

Let me know if that helps,

Cheers

Oli

**Comment by Krigen** [comment]
It works. Thank you
