### ISSUE TITLE
Drop Down Box using HeaderFilter

### ISSUE THREAD

**Issue by epikdota** [olifolkerd/tabulator#809]
Hello,

I am a beginner coder and I am looking for help in getting a drop down box filter similar to the one used in the "Examples" section on the Tabulator site under the "Gender" column with "Male" and "Female" being used as separate filters. I would like to do something similar with 5-10 different filter options in a drop down box without using the "editor" that is in the example (from what I understand, it is not necessary for the drop down box; feel free to correct me if I am wrong.) 

If this is not possible with Tabulator, thank you for your help anyway!

**Comment by olifolkerd** [comment]
Hey @epikdota 

That is entirely possible, though you are wrong on the editor front, you have to set an editor for a column in order for a user to edit it, that is how Tabulator works.

I would suggest you use the gender editor in the example as a basis for your editor, to customise the values you just need to change the ***options*** tags inside the editor element definition in the following line:

```js
 var editor = $("<select><option value=''></option><option value='male'>male</option><option value='female'>female</option></select>");
```

Let me know if that helps.

Cheers

Oli

**Comment by epikdota** [comment]
Hi Oli,

This is very helpful. Thank you very much!

**Comment by epikdota** [comment]
Using your method Oli, that makes it so that the data can be edited
correct? If so, that is not my goal. I simply wanted people to be able to
filter between different options. Looking at the code in the tabulator
documentation, it seems that is the intent of the editor.

**Comment by olifolkerd** [comment]
Hey @epikdota 

Ahh i understand what you mean now.

In that case the editor function is still valid, you just need to pass it into the ***headerFilter*** property in the column definition object:

```js
{title:"Name", field:"name", headerFilter:customEditorFunction}
```

Cheers

Oli

**Comment by epikdota** [comment]
Hey Oli,

That worked perfectly! Thanks again. On a side note, I have a similar
question.

I've been asked to make the same drop down box as you helped me before, but
this time the filter data will be based on a different column.

Basically, filter Column A based on Column B data with a drop down box in
the header of Column A. I've tried a few methods, but I can't seem to get
it to work. Would you be able to recommend anything?

Thanks again.

**Comment by olifolkerd** [comment]
Hey @epikdota 

Great News! Thanks for letting me know.

for your second dropdown i would suggest that you programatically build your select element, by creating an empty one and the appending option elements to it.

if you get all the table data, iterate through each of the rows you can then build up a list of all the available options.

I hope that helps

Oli

**Comment by uinfobrera** [comment]
Hi folks, I call the data from a json. Is it possible to populate select/option from it?

**Comment by olifolkerd** [comment]
Hey @epikdota 

You will be happy to hear that in version 3.4 there will be a built in select editor / header filter.

You can checkout the documentation when it is release tomorrow evening.

Cheers

Oli )

I

**Comment by olifolkerd** [comment]
Tabulator version 3.4 has now been officially release!

You can find details of the new release in the [News Section](http://tabulator.info/news)

Full documentation of all the new features can be found [Here](http://tabulator.info/docs/3.4)

Cheers

Oli :)
