### ISSUE TITLE
How Filter data internally?

### ISSUE THREAD

**Issue by codevite** [olifolkerd/tabulator#81]
I'd like to filter the Data based on the Row selected in a Master Table. 
So show the table data without showing the Filters options.
Master and Childs tables will allow CRUD operation.
How can I achieve this filter operation?

**Comment by olifolkerd** [comment]
You can programatically filter tables using the ***setFilters*** function:

```js
$("#example-table").tabulator("setFilter", "age", ">", 10);
```

You can perform simple filters or pass custom filter functions for more complex operations. Full details can be found in the [Filter Documentation](http://olifolkerd.github.io/tabulator/docs/#filtering).

You could use the ***rowClick*** or ***cellClick*** calbacks to determine when a row is clicked, or use the example code from the row selection examples in [this issue](https://github.com/olifolkerd/tabulator/issues/80#issuecomment-256947059) as a basis for handing the selection in the master table

**Comment by codevite** [comment]
Good!
