### ISSUE TITLE
Overwriting sass variables

### ISSUE THREAD

**Issue by Rodbjartson** [olifolkerd/tabulator#811]
Hey!
I was wondering how I could overwrite sass variables.
I am using the CDN version of tabulator, so I want to overwrite certain values.

rowHoverBackground is the specific attribute I would like to change. How can this be done?
Thanks in advance!

**Comment by olifolkerd** [comment]
Hey @Rodbjartson 

You cannot overwrite a sass variable client site, the sass files are compiled down to CSS and it is the CSS that is sent to the client.

Cheers

Oli :)
