### ISSUE TITLE
Create from HTML Table Element

### ISSUE THREAD

**Issue by dipeshpatel306** [olifolkerd/tabulator#814]
I am trying sorting Date 'mm/dd/yy' format but its sorting as string

**Comment by rafaeldcsantos** [comment]
Did you check the documentation? http://tabulator.info/docs/3.3#sorting
Define your column with `sorter:"date"` and include `moment.js`. Ex.
```
{title: "Admission", field: "admission", width: 110, sorter:"date",visible: true,headerFilter:false, headerSort:true},
```

**Comment by dipeshpatel306** [comment]
Yes I installed moment.js and  I am using simple HTML format rest of sorting works. only Date sort not working


<table id="breachtable" class="essfullreport">
    <thead>
        <tr>
            <th width="200">Service</th>
            <th width="150" tabulator-sorter="number" tabulator-title="# of Emp Accounts"></th>
            <th width="100" tabulator-sorter='date'>Date</th>
            <th width="130" tabulator-sorter="alphanum">Records</th>
            <th>Compromized Data</th>
        </tr>
    </thead>

**Comment by olifolkerd** [comment]
Have you set the format for the date to sort. By default it is expecting dd/mm/yy

**Comment by dipeshpatel306** [comment]
Yes set tabulator-sorter='date'

**Comment by olifolkerd** [comment]
I think you missed understood me. There is an additional parameter you need to set to define the date format to sort. Please check the documentation

**Comment by dipeshpatel306** [comment]
i need date sort in given example 
http://tabulator.info/docs/3.3?#table-load

**Comment by dipeshpatel306** [comment]
I used <th width="100" tabulator-sorter='date'>Date</th>

**Comment by rafaeldcsantos** [comment]
Please posts a minimum working example so others can run it and see if it is working or not, and why.

**Comment by olifolkerd** [comment]
As per the [Sorting Documentation](http://tabulator.info/docs/3.3#sorting) you will have to pass the format to be sorted in the ***sorterParams*** property in the column definition array:

```js
{title:"Name", field:"name", sorter:"date", sorterParams:{format:"MM/DD/YY"}}
```

Cheers

Oli

**Comment by dipeshpatel306** [comment]
Hello OliFolkerd, 

                Thanks for for response but sorting not working correctly for me if I am try to disable sorting its not working. 
th width="" tabulator-sorter="string" tabulator-headerSort="false" tabulator-cssClass="hidearrow" </th>Risk</th>
            <th width="" tabulator-sorter="string" tabulator-headerSort="false" tabulator-cssClass="hidearrow">Action</th>
