### ISSUE TITLE
Tabulator v3.3 - Remote Pagination Empty Table

### ISSUE THREAD

**Issue by fhariano** [olifolkerd/tabulator#815]
Hi, I get the warning message in Chrome console: 
      "Remote Pagination Error - Server response missing 'last_page' property"

But, I am returning the JSON: { last_page: 1, data: [] }

**Comment by olifolkerd** [comment]
Could you post a copy of your table constructor.

Cheers

Oli

**Comment by fhariano** [comment]
Follow:
**@ And my table is reloading when click next page or page number.**

`		$("#table-titulos").tabulator({
			ajaxURL:"formularios/crud-titulos.php",
			ajaxConfig:"POST",
			ajaxParams:{"type":"busca", "filtro":$("#search").val(), "panel": ""}, //ajax parameters
			responsiveLayout:true,
			pagination:"remote", //enable local pagination.
			// paginationElement:$("#pagination-top"), //build pagination controls in this element
			paginationSize:5, // this option can take any positive integer value (default = 10)
			// height:"320px", // set height of table (optional)
			// fitColumns:true, //fit columns to width of table (optional)
			layout:"fitColumns", // new version 3
			locale:true,
			langs:{
				"pt-br":{ //Portuguese language definition
					"pagination":{
						"first":"Prim.",
						"first_title":"Prim. Pag.",
						"last":"Ult.",
						"last_title":"Ult. Pag.",
						"prev":"Ant.",
						"prev_title":"Pag. Ant.",
						"next":"Prox.",
						"next_title":"Prox. Pag.",
					},
				},
			},
			columns:[ //Define Table Columns
				{title:"idTitulo", field:"idTitulo", visible:false},
				{title:"Descricao", field:"descricao", visible: false},
				{title:"Parcelado", field:"parcelado", align:"right", sorter:"number", visible: false},
				{title:"Num. Parc.", field:"numParcela", align:"right", sorter:"number", visible: false},
				{title:"Total Parc.", field:"totalParcelas", align:"right", sorter:"number", visible: false},
				{title:"PF/PJ", field:"pf_pj", visible:false},
				{title:"CPF/CNPJ", field:"cpf_cnpj", sorter:"string" , formatter:function(cell, formatterParams){
					// console.log(data.pf_pj);
					var value = cell.getValue();
					var data = cell.getData();
					if(data.pf_pj == '0'){
						return value.replace(/^(\d{3})(\d{3})(\d{3})(\d{2}).*/, '$1.$2.$3-$4'); // '000.000.000-00'
					} else {
						return value.replace(/^(\d{2})(\d{3})(\d{3})(\d{4})(\d{2}).*/, '$1.$2.$3/$4-$5'); // '00.000.000/0000-00'
					}
				}},
				{title:"Nome", field:"nome", sorter:"string"},
				{title:"No. Título", field:"numTitulo", sorter:"string"},
				{title:"Contrato", field:"numContrato", sorter:"string"},
				{title:"Tipo", field:"tipo", sorter:"string"},
				{title:"Vencimento", field:"dtVencimento", align:"center", sorter:"date", width:100},
				{title:"Atraso (dias)", field:"atraso", align:"right", sorter:"number", formatter:"money", formatterParams:{decimal:",", thousand:".", precision: "0"}},
				{title:"Valor R$", field:"valor", formatter:function(cell, formatterParams){
					//cell - the DOM element of the cell
					//formatterParams - parameters set for the column
					var value = cell.getValue();
					if(isNaN(parseFloat(value)))
					{
						return value;
					}else{
						var number = parseFloat(value).toFixed(2);
						var number = number.split(".");
						var integer = number[0];
						var decimal = number.length > 1 ? "," + number[1] : "";
						var rgx = /(\d+)(\d{3})/;
						while (rgx.test(integer)){
							integer = integer.replace(rgx, "$1" + "." + "$2");
						}
					   if(value < 0){
							return "<span style='color:red;'>" + integer + decimal + "</span>";
						}else{
							return integer + decimal;
						}
				}}, sorter:"number", align:"right", width:85, bottomCalc : "sumValor", bottomCalcFormatter: "money", bottomCalcFormatterParams: {decimal:",", thousand:"."}},
				{title:"Multa R$", field:"vlMulta", formatter:function(cell, formatterParams){
					//cell - the DOM element of the cell
					//formatterParams - parameters set for the column			
					var value = cell.getValue();					
					if(isNaN(parseFloat(value)))
					{
						return value;
					}else{
						var number = parseFloat(value).toFixed(2);
						var number = number.split(".");
						var integer = number[0];
						var decimal = number.length > 1 ? "," + number[1] : "";
						var rgx = /(\d+)(\d{3})/;
						while (rgx.test(integer)){
							integer = integer.replace(rgx, "$1" + "." + "$2");
						}
					   if(value < 0){
							return "<span style='color:red;'>" + integer + decimal + "</span>";
						}else{
							return integer + decimal;
						}
				}}, sorter:"number", align:"right", width:85, bottomCalc : "sumValor", bottomCalcFormatter: "money", bottomCalcFormatterParams: {decimal:",", thousand:"."}},
				{title:"Juros R$", field:"vlJuros", formatter:function(cell, formatterParams){
					//cell - the DOM element of the cell
					//formatterParams - parameters set for the column
					var value = cell.getValue();
					if(isNaN(parseFloat(value)))
					{
						return value;
					}else{
						var number = parseFloat(value).toFixed(2);
						var number = number.split(".");
						var integer = number[0];
						var decimal = number.length > 1 ? "," + number[1] : "";
						var rgx = /(\d+)(\d{3})/;
						while (rgx.test(integer)){
							integer = integer.replace(rgx, "$1" + "." + "$2");
						}
					   if(value < 0){
							return "<span style='color:red;'>" + integer + decimal + "</span>";
						}else{
							return integer + decimal;
						}
				}}, sorter:"number", align:"right", width:85, bottomCalc : "sumValor", bottomCalcFormatter: "money", bottomCalcFormatterParams: {decimal:",", thousand:"."}},
				{title:"Vl Atual R$", field:"vlTotal", formatter:function(cell, formatterParams){
					//cell - the DOM element of the cell
					//formatterParams - parameters set for the column
					var value = cell.getValue();
					if(isNaN(parseFloat(value)))
					{
						return value;
					}else{
						var number = parseFloat(value).toFixed(2);
						var number = number.split(".");
						var integer = number[0];
						var decimal = number.length > 1 ? "," + number[1] : "";
						var rgx = /(\d+)(\d{3})/;
						while (rgx.test(integer)){
							integer = integer.replace(rgx, "$1" + "." + "$2");
						}
					   if(value < 0){
							return "<span style='color:red;'>" + integer + decimal + "</span>";
						}else{
							return integer + decimal;
						}
				}}, sorter:"number", align:"right", bottomCalc : "sumValor", bottomCalcFormatter: "money", bottomCalcFormatterParams: {decimal:",", thousand:"."}},
				{title:"Status", field:"status", sorter:"string"},
				// {title:"Del", formatter:delIcon, width:40, align:"center", onClick:function(e, cell, val, data){popInfo(data, 'del')}},
				// {title:"Edit", formatter:editIcon, width:40, align:"center", onClick:function(e, cell, val, data){popInfo(data, 'atualiza')}},
			],
			/* rowClick:function(e, id, data, row){
				// alert("Rows " + id + " Clicked!!!!");
				console.log("Rows: "+JSON.stringify(data));
				// rowTitulo = data;
			}, */
			ajaxResponse:function(url, params, response){
				//url - the URL of the request
				//params - the parameters passed with the request
				//response - the JSON object returned in the body of the response.
				
				if(response.last_page > 0){
					//set max and min values
					var page_size =  Math.floor(response.data.length / response.last_page);
					// console.log("row_count: "+response.data.length);
					// console.log("last_page: "+response.last_page);
					// console.log("total_rows: "+response.total_rows);
					
					// Registro inicial
					var start = (response.size * (response.page - 1)) + 1;
					var str = '' + start;
					if (str.length > 3){
						if(str.length == 4){
							str = str.substr(0, 1) + '.' + str.substr(1);
						} else if (str.length == 5){
							str = str.substr(0, 2) + '.' + str.substr(2);
						} else {
							str = str.substr(0, 3) + '.' + str.substr(3);
						}
					}
					$("#table-info .start").text(str);
					
					// Registro final
					var end_row = response.size * response.page;
					end_row = end_row > response.total_rows ? response.total_rows : end_row;
					var str = '' + end_row;
					if (str.length > 3){
						if(str.length == 4){
							str = str.substr(0, 1) + '.' + str.substr(1);
						} else if (str.length == 5){
							str = str.substr(0, 2) + '.' + str.substr(2);
						} else {
							str = str.substr(0, 3) + '.' + str.substr(3);
						}
					}
					$("#table-info .end").text(str);
					
					// Total de Registros
					var str = '' + response.total_rows;
					while (str.length < 6) {
						str = '0' + str;
					}
					str = str.substr(0, 3) + '.' + str.substr(3);
					$('#table-info .max').text(str);
				} else {
					$("#table-info .start").text('0');
					$("#table-info .end").text('0');
					$('#table-info .max').text('0');
				}
				
				// verifica se retornou error
				if(response.error){
					if(filtrar){
						$("#table-titulos").tabulator("clearData");
					}
					filtrar = 0;
					// $("#div-titulos").hide();
					swal(response.message,'', 'error');
					return false;
				}
				if(filtrar){
					$("#div-titulos").show();
					$("#table-titulos").tabulator("redraw");
				} 

				filtrar = 0;

				return response; //return the response data to tabulator (you MUST include this bit)
			}
		});
		$("#table-titulos").tabulator("setLocale", "pt-br");`

**Comment by olifolkerd** [comment]
Hey @fhariano 

if you put a console log on the ***response*** variable just before it is returned from the ***ajaxResponse*** callback what do you get? is it a string or an object?

Cheers

Oli

**Comment by fhariano** [comment]
An objetct.

![chrome-console](https://user-images.githubusercontent.com/7996929/34720455-ed2a642a-f525-11e7-8424-fd28ea9b0c8e.png)

**Comment by fhariano** [comment]
Other issue is: Why the page is reloading when I click on next or prev page?

**Comment by olifolkerd** [comment]
Hey @fhariano 

There was a bug in the button definitions that was causing them to trigger a page submit if the table was inside of a form, this has now been fixed and will be included in tomorrows 3.4 release.

The last_page error is triggered when either the last page value is missing or is set to 0.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Tabulator version 3.4 has now been officially release!

You can find details of the new release in the [News Section](http://tabulator.info/news)

Full documentation of all the new features can be found [Here](http://tabulator.info/docs/3.4)

Cheers

Oli :)

**Comment by mateddy** [comment]
@olifolkerd 
> The last_page error is triggered when either the last page value is missing or is set to 0.

1. It seems that I have to manually set last_page to 1 to avoid the error when no result is found.
2. Also, when I set last_page to 1 and placeholder to be a string "No result found", the placeholder is rendered in a box which is too small (and scrollbar is shown).
<img width="867" alt="screen shot 2018-06-10 at 12 08 25 pm" src="https://user-images.githubusercontent.com/2744288/41198249-9ede9a8a-6ca7-11e8-9bc9-8bb5f135226c.png">

I may use a jQuery object $("&lt;p&gt;No result found&lt;/p&gt;") and style it to circumvent this issue.  However is there a better solution (to 1 and 2)?
