### ISSUE TITLE
I think there's an IE breaking typo in core.js and tabulator.js?

### ISSUE THREAD

**Issue by AndrewHutcheson** [olifolkerd/tabulator#816]
You define a variable called browser, initialize it to the current useragent, then retroactively set it to IE to call compatibility codes, however, the variable, defined as browser, is later called via brower, missing the "s".
see here:
https://github.com/olifolkerd/tabulator/search?utf8=%E2%9C%93&q=ie&type=

My pages work just fine, but not in IE, 11, I get a jquery  error: this object doesn't support property or method .tabulator

**Comment by olifolkerd** [comment]
Hey @AndrewHutcheson 

Good Spot! i will include a fix for that in the next weeks patch update

Cheers

Oli

**Comment by AndrewHutcheson** [comment]
in tabulator-master/ your example/license file thing is also called bower. Not sure if that's on purpose.

**Comment by AndrewHutcheson** [comment]
Hmm I updated the core and tabulator files but I still have the error in IE11, Object doesn't support property or method 'tabulator'. Any other ideas? 

I was trying to see what the browser variable is actually set to but IE's debug tools are a bit difficult.

**Comment by AndrewHutcheson** [comment]
So the typo is still a thing, but it turns out that my fix didnt work because I had a specific issue was caused by me calling multiple libraries of jquery.

**Comment by olifolkerd** [comment]
i have just pushed a fix for this to the master branch, it will be included in this evenings release
