### ISSUE TITLE
highlighting editable cells

### ISSUE THREAD

**Issue by cschnelting** [olifolkerd/tabulator#818]
Hi Oli,

i would like to highlighting editable cells. I've tried to use the following tabulator-extension, but without success:

`
Tabulator.extendExtension("format", "formatters", {
    bordercolor:function(cell, formatterParams){
        cell.getElement().css({ "border-color": "red",
         "border":"5px"});
	return cell.getValue();
    }
});
`

The Border is not shown on the column-Cells. If i try the same extension with background-color instead of border-color, the Cells are displayed red. Maybe you can help me?

And is it possible to remove the border, if the cell was valid edited?

Thanks!

**Comment by alataknet** [comment]
Hello
I have done almost the same; May be my example can help you

```
 var formatter_product_in_stock= function (cell, formatterParams) {
            var data = cell.getData();
            var field=formatterParams.param;
            var background_color=data[field];
            cell.getElement().css({ "background-color": background_color });
            return cell.getValue();
        };
```
with 

`
title: "My Column",
                    field: "product_in_stock",
                    editor: "input",
                    validator: ["numeric"],
                    formatter: formatter_product_in_stock, formatterParams:{param: 'stock_status'},
                    headerFilter: "input",
                    headerFilterPlaceholder: 'my_place_holder_text
`

**Comment by cschnelting** [comment]
Hi,
Thanks for your example, but the Problem is the following:
When i use background-color as css, it works fine. But when i use border-color, the border isn't displayed colored.

**Comment by olifolkerd** [comment]
Hey @cschnelting 

Your issue is because you are not setting the border fill type in the css so it isnt rendering correctly, it should be:
```js
cell.getElement().css({ "border":"5px solid red"});
```

Cheers

Oli

**Comment by cschnelting** [comment]
Thanks!
