### ISSUE TITLE
issue with row hover highlight

### ISSUE THREAD

**Issue by sawibo** [olifolkerd/tabulator#819]
Hi Oli,

I'm stuck on something here. I'm using the rowFormatter to change the color of the rows depending on a column value and this works fine. What does annoy me is that it seems to cancel out the row highlighting that normally happens when you hover over a row. Is there a way to circumvent this ?

Best,
Sander

**Comment by olifolkerd** [comment]
Hey @sawibo 

how are you setting your background color? if you are setting it directly on the element then it will take precedence over any CSS styling applied elsewhere. I would suggest applying a class to the row, that way the :hover styling will still work if you use the right level selector for the row.

Cheers

Oli
