### ISSUE TITLE
Editor double quote issue

### ISSUE THREAD

**Issue by hohozhao** [olifolkerd/tabulator#82]
Hi @olifolkerd ,

Today I found a new issue, about editor:

In console log, I found the value that I will assign to editor is
`"<select><option value="MacBook Air 13">MacBook Air 13</option><option value="MacBook Air 13\"">MacBook Air 13"</option><option value="MacBook Pro 13\"">MacBook Pro 13"</option><option value="MacBook Pro 15\"">MacBook Pro 15"</option></select>"`

After above value assign to editor, console.log(editor.html()) shows me this:
`"<option value="MacBook Air 13">MacBook Air 13</option><option value="MacBook Air 13\" "="">MacBook Air 13"</option><option value="MacBook Pro 13\" "="">MacBook Pro 13"</option><option value="MacBook Pro 15\" "="">MacBook Pro 15"</option>"`

This is bad. I am struggling to deal with select option value that contains a double quote.

**Comment by olifolkerd** [comment]
The editor is created each time the editor is shown on the page, and destroyed each time the value is selected, accessing any value of the editor once it is destroyed is meaningless as it isnt in use.

You should be escaping the quotations you are using, there are numerous options for how to achieve this,

The simplest would be to use a mix of single and double quotation marks to avoid the conflict, though this dosnt allow for great flexibility in the string.

the best option would be to escape the quotes using the appropriate html character \&quot;

If you are building the options list programatically then you can get jQuery to do this for you automatically:

```js
var select = $("<select><select>")
var options = ['MacBook Pro 13"', 'MacBook Pro 13"'];

options.forEach(function(item){
    var option = $("<option></option>").attr("value", item).text(item);
    select.append(option)
});
```

**Comment by hohozhao** [comment]
I am trying ... give you feedback soon. Thx a lot.

**Comment by hohozhao** [comment]
Seems using &quot; do the magic! Interesting thing!

Here's my code to assemble the "select"
```
        var _option_head = '<option value="';
        var _option_midl = '">';
        var _option_foot = '</option>';

        var select = "<select>";
        for (var i=0; i < rows.length; i++) {
            select += _option_head + rows[i][field].replace(/"/g,'&quot;') + _option_midl +  rows[i][field]+ _option_foot;
        }
        select += "</select>";
I like your way of using array and assemble, but the result from mysql is in json format, so has to convert it to array like `var options = ['MacBook Pro 13"', 'MacBook Pro 13"'];` and then can use your way.
```

**Comment by hohozhao** [comment]
The most interesting part is
`"<option value="MacBook Air 13">MacBook Air 13</option><option value="MacBook Air 13&quot;">MacBook Air 13"</option><option value="MacBook Pro 13&quot;">MacBook Pro 13"</option><option value="MacBook Pro 15&quot;">MacBook Pro 15"</option>"`

The value presents " instead of \&quot; when sending the value to server.

**Comment by olifolkerd** [comment]
if you need to parse the data in from a JSON string you can use the javascripts ***JSON.parse*** function:

```js
var example_json = '['MacBook Pro 13', 'MacBook Pro 13']',
var options = JSON.parse(example_json);
```

**Comment by hohozhao** [comment]
Mysql return json should be like
[
{model: "MacBook Pro 13\""},
{model: "MacBook Air 13\""},
]

**Comment by olifolkerd** [comment]
the you need to adjust your forEach loop appropriately to handle the objects:

```js
var select = $("<select><select>")
var options = JSON.parse(json_from_server);

options.forEach(function(item){
    var option = $("<option></option>").attr("value", item.model).text(item.model);
    select.append(option)
});
```

**Comment by hohozhao** [comment]
Looks much better! I will try it out! Thanks for the teaching!

**Comment by hohozhao** [comment]
Btw, is there any shortcuts for this OR condition? 

if (data.field == "manuf" || data.field == "model" || data.field == "type")

**Comment by olifolkerd** [comment]
if(["manuf", "model", "type"].indexOf(data.field) > -1)

**Comment by hohozhao** [comment]
OH!!! Looks much nicer! thx mentor.

**Comment by hohozhao** [comment]
Hmm... indexOf, seems it can match mmmmodellll for model.

**Comment by olifolkerd** [comment]
nope it can only match exact  matches as you are comparing entries to an array not looking for the index of a character in a string

**Comment by hohozhao** [comment]
Oh, OK, let me think it again.

**Comment by hohozhao** [comment]
Hi @olifolkerd , a question regarding how to get data from json array.

[
    {"region": "China", "value": [ 1, 2, 3]},
    {"region": "UK", "value": [4,5,6]},
    ...
]

How can I extract the China region value array [1, 2, 3] to a var? I don't want to loop and compare if the region is "China" or not. Is there a way to directly get the value and assign?

**Comment by hohozhao** [comment]
Hmm... I think there's no way unless compare them.

**Comment by olifolkerd** [comment]
You can use the find method, although it dosnt work in ie.

```js
var china = json_rows.find(function(item){
   return item.region === "china";
});
```

**Comment by prsanjay** [comment]
Hi @olifolkerd , the issue I am facing is with a single quote. If I enter value as `D'Sauza` and when table is rendered it shows as `D&#39;Souza` I am using v4.7. I am making sure that string is coming as `D'Sauza` but it seems something goes wrong while rendering it in the table. Thank you for the amazing library
