### ISSUE TITLE
Can we setfilter using array

### ISSUE THREAD

**Issue by krunalpatel55** [olifolkerd/tabulator#820]
var filterParams=['Project A','Project B'];
$("#PMO-alert").tabulator("setFilter", "SiteTitle", "like", filterParams);

**Comment by olifolkerd** [comment]
Hey @krunalpatel55 

There is no inbuilt filter for that, but i love the idea so will include it in next months release using a new ***in*** filter

In the mean time you could achieve this using a custom filer function:
```js
function inArrayFilter(data, filterParams){
    //data - the data for the row being filtered
    //filterParams - params object passed to the filter

    return filterParams.indexOf(data.SiteTitle) > -1;
}

$("#example-table").tabulator("setFilter", inArrayFilter, ['Project A','Project B']);
```

For more information check out the [Filtering Documentation](http://tabulator.info/docs/3.3#filtering)

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @krunalpatel55 

You will be happy to hear i have just pushed an update for the new ***in*** filter to the 3.4 branch.

You will be able to filter by values in an array:
```js
$("#example-table").tabulator("setFilter", "name", "in", ["steve", "bob", "jim"]); // name must be steve, bob or jim
```

The 3.4 release should be out in the next couple of weeks.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Tabulator version 3.4 has now been officially release!

You can find details of the new release in the [News Section](http://tabulator.info/news)

Full documentation of all the new features can be found [Here](http://tabulator.info/docs/3.4)

Cheers

Oli :)
