### ISSUE TITLE
Custom Editor DropDown not show text but show value

### ISSUE THREAD

**Issue by kathawut** [olifolkerd/tabulator#822]
I custom editor to create dropdown component. But when I select data from dropdown.  (First image) 
![Image of 1](https://lh3.googleusercontent.com/7oMA-pZgc-ruFgaNZFQaCdeIJLnZAroscGmBJTYPSOdg3O0uULliPIWzNH1x_-BKhAGuF9zh_3zZFgULvPu4hgtXQx6yDSudqWL1NSG3BF1-b2ULWL-DeZyHnxK7hbpsqoY03zaBfHVGTo1-xvNz_ngJPtodh--KO5YWuQeWh01Xr6GwgRK7Zr8ngSI3mf9jXT6aVB1DM1pUbb-JUGheVWI1tjBLa2j_PHudvFhhwACEcdl-UJom0yVScz-7OljMDFSsr9tX-GLMh75sZOSoujK3X5JxjLi3hONxS_NCf4BpASdS9YCeztbtapFPRwTguiKfpuJ9S9IXqPrZzqfrY4XWxhrztAXYS8NizL997oePExDLSKQeWL_I-lr3iSfHKZkNiVluE0hX0j6WV4NJa_BKjrHe5ry-lacCsRAeoZD32aiN5yxRQmcYW_64w-PIR53CaVDFRyMf39aI3-X069lJHmpyJaGJwik3u-m5noNZ_-UKE8g2q33Mt9zQyNzPoK8jWjl7P3vFU7o7TZthDMU03CQRAutRXHWyBtwBiu63v7gJYZQovEdJoKizzjTO=w1366-h662)

After I select data it show value. So how can I show textdata?

![Image of 2](https://lh3.googleusercontent.com/U7vE9sA95nU58BNMcfbqWv1gFT3Sfpn1XinJS5bOW_vI-zeE70euuA7m6PxULCZJJfBkScwYWRWjhCKzDh0V_zt9VTraowBI7F5vh0kh8LUwryxr3DCPNeUfpv5Uz2PZuRiJcEc4h1nnRKgoByIsNdVglragbc-A2BNDeiAO1UJq5Z3HICDgtZG2CXvjCMdpfU5YygnnuHbmjIwfaolgIshxg_0geaINrfH1R0g8nQLbt8E8X_MV1NYv8r2usoXiq5XUumSHZrl6TnWOGoR9qZzt8bFOqzcP6HpKEAOOSze-98-LTeKiwhLCdL53S_4nFeSxrqaB97A1dw8zJOYOZ5H4Pp3ywIqfRlMBqLQz-KyfVlaKq77DtFpSriVI8bf1Afv4-SouKT3_omU9Lx9b3KEodZmGxsOs31fv-lhU6cvdvHXocFrVX5ZfUEeONtYNTlJD-8FZaKeo8STFkys2nX3b0-Hdg2apMaLwFjAQj04bO4gyYWLHtfxbscke_xpvwDwq6AzUUR5bXOkQveES3jppYaTiK58FpIaM4DrLCy5MtmX1rTg6pQE4LA6pubc0=w1366-h662)

**Comment by Rodbjartson** [comment]
You need to provide some code here, when you set the data.

**Comment by kathawut** [comment]
What code should I provide?
Cloud you please show example.

**Comment by kathawut** [comment]
[Solved]Hi, I got solution by create function for formatter 

Thank you

**Comment by JimSmithJr** [comment]
Hello Kathawut,

Could you please share the code you built for the custom drop down editor.

Thanks very much
Jim

**Comment by kathawut** [comment]
Hi JimSmithJr,
`columns:[ //Define Table Columns
	       	{title:"ลำดับ", field:"no", width:100, formatter:"rownum", align:"center"},
	        {title:"ชื่อสินค้า", field:"marketItemId", width:300, editor:selectItemEditor, formatter:itemFormatter, validator:["required"], align:"left"},
	        {title:"จำนวน", field:"quantity", width:100, editor:"number"},
	        {title:"หน่วย", field:"unitId", width:100, editor:selectUnitEditor, **formatter:unitFormatter,** validator:["required"], align:"left"}
	    ],`

You can create function and set it into formatter like code below:
`var itemFormatter = function(cell, formatterParams){ //plain text value
	   	var itemName = "";
	   	itemJson.forEach(function(obj) {
	   		if(obj.marketItemId == parseInt(cell.getValue())){
	   			itemName = obj.itemName;
	   		}
	   	});
	    return itemName;
	};`

**Comment by olifolkerd** [comment]
Hey @kathawut 

You do not need to use a custom editor for this, there is already a ***select*** editor built into tabulator that does just that.

an example of it in action can be found on the [Editable Data Example](http://tabulator.info/examples/3.5#editable) in the gender column.

Let me know if that helps.

Cheers

Oli :)
