### ISSUE TITLE
New tabulator version 3.4

### ISSUE THREAD

**Issue by Rodbjartson** [olifolkerd/tabulator#824]
Hi!
When is version 3.4 set to release?
I know that it is very difficult to give an exact date, but will it be released in february or is it more likely to come out later this spring?

**Comment by olifolkerd** [comment]
Hey @Rodbjartson,

As it happens i started on v3.4 this week with an aim to release in the first or second week of feb!

Cheers

Oli

**Comment by olifolkerd** [comment]
Tabulator version 3.4 has now been officially release!

You can find details of the new release in the [News Section](http://tabulator.info/news)

Full documentation of all the new features can be found [Here](http://tabulator.info/docs/3.4)

Cheers

Oli :)
