### ISSUE TITLE
Editable tick not working on Firefox on Mac

### ISSUE THREAD

**Issue by jereze** [olifolkerd/tabulator#825]
It takes the focus, but clicking does not change the tick.

http://tabulator.info/examples/3.3#editable
![e6gpufettj](https://user-images.githubusercontent.com/4386500/34914419-0f53ab88-f913-11e7-9e92-2c9d84d5cb61.gif)

Firefox 57.0.4 (64 bits)
Mac OS X 10.12.6

**Comment by olifolkerd** [comment]
Hey @jereze 

I cannot replicate your issue, it is working fine when i try it.

Which version of firefox are you using, some of there recent releases have had issues.

Cheers

Oli

**Comment by jereze** [comment]
Hi @olifolkerd,

I'm with the last version of Firefox, on Mac. (see my first message) I tried in the "without extension" mode, and I still have the issue.

**Comment by olifolkerd** [comment]
Hey @jereze 

Im afraid the "latest version" isnt very helpful when it comes to debugging, could you follow [This Guide](https://support.mozilla.org/en-US/kb/find-what-version-firefox-you-are-using) and let me know the version number so i can match your setup as best as possible.

Cheers

Oli

**Comment by jereze** [comment]
Hi Oli,

I already wrote the version in my initial message, under the screenshot.

**Comment by olifolkerd** [comment]
Hey @jereze 

Sorry i completely missed that, it does look like there is an issue on the later versions of firefox on a mac. i will have a look into this further.  in the mean time if you want to toggle the values of the ticked column you could use a ***cellClick*** binding instead of an editor:

```js
{title:"Driver", field:"car", width:50, align:"center", formatter:"tickCross", cellClick:function(e, cell){
    cell.setValue(!cell.getValue());
}},
```


Cheers

Oli

**Comment by jereze** [comment]
Hi @olifolkerd,

Thank you for the confirmation of the bug and the workaround (I already did the same actually :) ).

With best wishes,
Jeremy

**Comment by xXmrotsXx** [comment]
This also seems to be an issue on iPhone and iPad with both Chrome and Safari. I'll try and track down versions as it was not I who saw the issue...

**Comment by olifolkerd** [comment]
Hey All,

it turns out to be an issue with the order events are fired on the mac version of firefox, i have pushed an update to the 3.5 branch with a fix for this.

It should be officially released at some point next week.

Cheers

Oli :)
