### ISSUE TITLE
Typo's Column Calculations (website)

### ISSUE THREAD

**Issue by hugovoerman** [olifolkerd/tabulator#826]
At http://tabulator.info/examples/3.3?#calculations
the first paragraph contains multiple typo's

Current text: "Column calculations can be **useed** to add a row of **calcualted** values to the top or bottom of your table to display **infmation** such as the sum of a columns data."

My proposal: "Column calculations can be used to add a row of calculated values to the top or bottom of your table to display information such as the sum of a columns data."

**Comment by olifolkerd** [comment]
Hey @hugovoerman 

Good Spot! thanks for the heads-up, this has now been resolved.

Cheers

Oli :)
