### ISSUE TITLE
Is this an error: " margin-left: 1000px;"

### ISSUE THREAD

**Issue by roypardi** [olifolkerd/tabulator#829]
I was going through the `tabulator_midnight.css` theme and saw the line below:

```
.tabulator .tabulator-row.tabulator-group.tabulator-group-level-5 .tabulator-arrow {
    margin-left: 1000px;
}
```
I'm no CSS hero but it looks like the progression is +20px and then there is that jump.
Should it be 100px?

-----
***For context:***
```
.tabulator .tabulator-row.tabulator-group.tabulator-group-level-1 .tabulator-arrow {
    margin-left: 20px;
}

.tabulator .tabulator-row.tabulator-group.tabulator-group-level-2 .tabulator-arrow {
    margin-left: 40px;
}

.tabulator .tabulator-row.tabulator-group.tabulator-group-level-3 .tabulator-arrow {
    margin-left: 60px;
}

.tabulator .tabulator-row.tabulator-group.tabulator-group-level-4 .tabulator-arrow {
    margin-left: 80px;
}

.tabulator .tabulator-row.tabulator-group.tabulator-group-level-5 .tabulator-arrow {
    margin-left: 1000px;
}

```

**Comment by olifolkerd** [comment]
Hey @roypardi 

Great Spot! Thanks for letting me know.

Turns out that issue was in all the themes, looks like no one else has tried grouping down to 5 levels since the feature went live!.

I have pushed a fix to the master branch for this and will include it in the next release.

Cheers

Oli

**Comment by olifolkerd** [comment]
Tabulator version 3.4 has now been officially release!

You can find details of the new release in the [News Section](http://tabulator.info/news)

Full documentation of all the new features can be found [Here](http://tabulator.info/docs/3.4)

Cheers

Oli :)
