### ISSUE TITLE
Header Rows and Span option

### ISSUE THREAD

**Issue by vmontal** [olifolkerd/tabulator#83]
Hi,
is it possible set two rows as TableHeader and, if possibile, can I set a colspan and/or rowspan option?

see attached file
[TableHeader.pdf](https://github.com/olifolkerd/tabulator/files/560398/TableHeader.pdf)

**Comment by olifolkerd** [comment]
At present, you cannot have dual row headers, but these are on the roadmap so they should appear soon. although it would be possible to manually implement this by adding a div above the tabulator and adding some event bindings to check when columns are resized etc.

there are no col/row span options at presnet either, though they are also on the roadmap

**Comment by olifolkerd** [comment]
With the release of Tabulator 2.8 today, you can now use column grouping to create mutli-row/multi-column headers.

Based on the pdf you sent over, the following column definition should work for you:
```js
$("example-table").tabulator({
    columns:[
        {title:"Col1", field:"col1"},
        {
            title:"Item1",
            columns:[
                {title:"Col2", field:"col2"},
                {title:"Col3", field:"col3"},
                {title:"Col4", field:"col4"},
            ],
        },
    ],
});
```

[Check out the documentation](http://olifolkerd.github.io/tabulator/docs/#column-groups) for fore info.

**Comment by vmontal** [comment]
What can I say?
When in a room the air is missing and you open the window, the air doesn't go in only for you, but for everyone who is in the room!!!
Great, great, great!!!

Get Outlook for iOS




On Sun, Nov 6, 2016 at 7:01 PM +0100, "Oli Folkerd" <notifications@github.com> wrote:












With the release of Tabulator 2.8 today, you can now use column grouping to create mutli-row/multi-column headers.



Based on the pdf you sent over, the following column definition should work for you:

$("example-table").tabulator({
    columns:[
        {title:"Col1", field:"col1"},
        {
            title:"Item1",
            columns:[
                {title:"Col2", field:"col2"},
                {title:"Col3", field:"col3"},
                {title:"Col4", field:"col4"},
            ],
        },
    ],
});



Check out the documentation for fore info.

**Comment by vmontal** [comment]
Houston, we have a problem!!!
Cols and Rows span is working fine, but, unlike the previous release, the title inside a single cell doesn't split in two rows (when necessary)!

however, thanks a lot!

**Comment by vmontal** [comment]
... and what about a colHorizAlign (left, center, right) ?

always thanks in advance!

**Comment by olifolkerd** [comment]
I have uploaded a fix to the css to adjust for the new way the headers are created to help fix this. once you have downloaded the latest version you will need to do the following.

As of version 2.8 column title text is now contained in a *** .tabulator-col-title*** element. By default the headers are set to truncate text that is too long using ellipsis. to change this so the text wraps, you will need to include the following css after the tabulator.css to override this behaviour:
```css
.tabulator .tabulator-header .tabulator-col .tabulator-col-content .tabulator-col-title{
    white-space: normal;
    overflow:visible;
}
```
To change the horizontal alignment you can add a ***text-align*** property to the css for the ***.tabulator-col-title*** selector.

I am only adding configuration options that require processing in js, the ***colVertAlign*** option is activly handled in javascript, where as horizontal alignment can be easily done with CSS and leaving it that way gives more flexibility to the user.

Hopefully this should help you out.

**Comment by vmontal** [comment]
OK!

thanks a lot!
