### ISSUE TITLE
How to get row Id on cellClick

### ISSUE THREAD

**Issue by pavankomarina** [olifolkerd/tabulator#832]
i would like to know the row id on cellClick ,because each cell have different functionalities but their database is related to their row id. So is there any way to do this?

**Comment by Rodbjartson** [comment]
```
$("#example-table").tabulator({
    columns:[
        {title:"Name", field:"name", sorter:"string", width:200, editor:true},
 ],


{title:"Name", field:"name", cellClick:function(e, cell){
        //e - the click event object
        //cell - cell component
       var row = cell.getRow()
       var rowIndex = row.getIndex();
    },
}
});
```

Something like this?

**Comment by ShinobiWPS** [comment]
I'd like to re-open the issue since I just done what the guys said and I get `undefined`
<img width="612" alt="Screenshot 2019-10-24 at 12 34 08 PM" src="https://user-images.githubusercontent.com/11430881/67477539-92afe000-f65a-11e9-8f73-96ef39da2074.png">
Using `cellClick`

**Comment by ShinobiWPS** [comment]
<img width="468" alt="Screenshot 2019-10-24 at 12 42 16 PM" src="https://user-images.githubusercontent.com/11430881/67478124-bc1d3b80-f65b-11e9-8cde-3d1927d627d5.png">

**Comment by ShinobiWPS** [comment]
@olifolkerd

**Comment by olifolkerd** [comment]
@ShinobiWPS 

Without seeing where that function is called from it is impossible to offer you help, it is likely that your setSelectedCell function is being called without the cell component being passed into it.

Oli

**Comment by ShinobiWPS** [comment]
that's all
<img width="286" alt="Screenshot 2019-10-24 at 2 08 23 PM" src="https://user-images.githubusercontent.com/11430881/67484136-b62d5780-f667-11e9-9c2b-c0eea59fe8f9.png">

**Comment by ShinobiWPS** [comment]
the arguments are from Tabulator, i'm not doing anything else like manipulating or filtering arguments,so if something is missing, is a library bug or something

**Comment by olifolkerd** [comment]
The cell click function is working exactly as expected when I use it. Please confirm which version of Tabulator u are using.

Also please create a JS Fiddle so we can see how your table is configured. As I mentioned it is impossible to diagnose your issue without the context in which it is being used.

Cheers

Oli

**Comment by ShinobiWPS** [comment]
Sure!

https://jsfiddle.net/rzyen2vw/

**Comment by olifolkerd** [comment]
Thanks that was very helpful,

The reason you are getting undefined is because you have no ***id*** property defined on your row data which is what the ***getIndex*** function returns, *(or whatever field you have specified in the ***index*** setup option)*

If you want to get the position of the row in the table, ie the number of rows from the top of the table then you need to call the ***getPosition*** function on the row component.

If in future you could provide a JS Fiddle or a bit more information about how you are using your table when you first post it will make it easier for us to help you

Cheers

Oli :)

**Comment by ShinobiWPS** [comment]
thank you @olifolkerd ,that was enlightning!
Leaving everything here for the the next @me having same issue
