### ISSUE TITLE
Tabulator v2.12 - How to disable pagination to export data?

### ISSUE THREAD

**Issue by fhariano** [olifolkerd/tabulator#834]
When I export the table to CSV aren't sent all data because of the pagination.

**Comment by Rodbjartson** [comment]
If that is the case, you have found a bug.

**Comment by fhariano** [comment]
I not using the method Download of the Tabulator, I created my self method to download in CSV and XLSX, but when I sends the data are going only the data of actual page. I whish of clear  the pagination and sends all data to my method.

**Comment by olifolkerd** [comment]
Hey @fhariano ,

I would strongly suggest you upgrade to the latest version of Tabulator, the download functionality in 3.3 is much more advanced than in 2.12 and will resolve all your issues.

Cheers

Oli :)
