### ISSUE TITLE
Tabulator 3.3.3 : How to toggle selection on all rows ?

### ISSUE THREAD

**Issue by jros64** [olifolkerd/tabulator#835]
HI!
It is possible to select/unselect all rows but there is no function to toggle selection of all rows.
I have done this with external javascript but it is very slow on big tables. The script is : 
`
         var rows = $("#myTable").tabulator("getRows", true);
	   for(var i in rows) rows[i].toggleSelect();
`
Could you help me to add this function directly into tabulator.js ?

**Comment by jros64** [comment]
It's ok, I've found a solution. Here is the modified code of toggleRow function in tabulator.js : 

`    //toggle row selection


    SelectRow.prototype.toggleRow = function (row) {

      switch (typeof row === 'undefined' ? 'undefined' : _typeof(rows)) {
	
	case "undefined" :
		this.table.rowManager.rows.forEach(function (row) {

			if (row.extensions.select.selected) {

				this._deselectRow(row, true, true);
			} else {

				this._selectRow(row, true, true);
			}
		});

		this._rowSelectionChanged();
	break;
	case "boolean" :
		if (rows === true) {

			this.table.rowManager.activeRows.forEach(function (row) {
				if (row.extensions.select.selected) {

					this._deselectRow(row, true, true);
				} else {

					this._selectRow(row, true, true);
				}
			});
			this._rowSelectionChanged();
		}
	break;
	default:
		if (this.table.options.selectableCheck(row.getComponent())) {

			if (row.extensions.select.selected) {

				this._deselectRow(row);
		} else {

			this._selectRow(row);
		}
	
		break;		
	}

      };
    };

`

**Comment by olifolkerd** [comment]
Hey @jros64 

The quick way to do this would be to get all the rows in the table, then iterate through them and call the ***toggleSelect*** function:

```js
var rows = $("#example-table").tabulator("getRows");
rows.forEach(function(row){
    row.toggleSelect();
});
```

Cheers

Oli :)
