### ISSUE TITLE
Website Documentation typos

### ISSUE THREAD

**Issue by jamesmstone** [olifolkerd/tabulator#836]
Re #823 here are some minor typos on the website, sorry hate to come across as being picky for the sake of it.

# [Documentation](http://tabulator.info/docs/3.3)
## Grouping Data

- [ ] `arrya`  -> `array` (times 3)

## Localization
- [ ] `retrive` -> `retrieve`

## Extensions
- [ ] `As gulp is an Node.js tool,` -> `As gulp is a Node.js tool,`

- [ ] `re-delcaring` -> `re-declaring`

**Comment by olifolkerd** [comment]
Thanks for picking up on the typos, 

I'm terrible at spelling so i'm very grateful for any of the issues you find. i will get those fixed this weekend

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @jamesmstone 

Thanks for pointing those out, i have updated the source for the site and will push the changes live when the 3.4 branch is released in a couple of weeks.

Let me know if you find any more

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Tabulator version 3.4 has now been officially release!

You can find details of the new release in the [News Section](http://tabulator.info/news)

Full documentation of all the new features can be found [Here](http://tabulator.info/docs/3.4)

Cheers

Oli :)

**Comment by jamesmstone** [comment]
congrats, cheers for all your work, appreciate it!
