### ISSUE TITLE
filter with multiple items on same field

### ISSUE THREAD

**Issue by jameswhite4684** [olifolkerd/tabulator#838]
Having trouble to filter specific items on a single field.

I have tried the following but nothing seems to work. I only want to see the selected items I specify. 

`//$("#getcsqTable1").tabulator("setFilter", [
//    {field:"VoiceIAQStats.esdName", type:"=", value:"Main Operator", "Backup Operator"},
//]);

//$("#getcsqTable1").tabulator("setFilter", [
//	{field:"VoiceIAQStats.esdName", type:"like", value:"Main Operator},
//	{field:"VoiceIAQStats.esdName", type:"=", value:"Backup Operator"},
//	{field:"VoiceIAQStats.esdName", type:"=", value:"Customer Support Level 1"},
//	{field:"VoiceIAQStats.esdName", type:"=", value:"Strategic Support Level 1"},
//	{field:"VoiceIAQStats.esdName", type:"=", value:"Strategic Support Level 2"},
//	{field:"VoiceIAQStats.esdName", type:"=", value:"Strategic Support Level 3"},
//]);`

there are many more values but only need to focus on these.

**Comment by Rodbjartson** [comment]
Why are you using the "=" operator and not the "like"?

**Comment by jameswhite4684** [comment]
Another way of putting it, how would I display only certain rows.

**Comment by jameswhite4684** [comment]
I have tried both but, names are not similar enough so I can’t use exact. Basically it needs to be specific

Thank you,

James White
334-589-9080
Sent from phone
________________________________

**Comment by jameswhite4684** [comment]
field:"VoiceIAQStats.esdName", type:"like", value:"Main Operator", "Backup Operator" only the last value shows "Backup Operator"

**Comment by olifolkerd** [comment]
Hey @jameswhite4684 

Filters will be applied in an additive manner so that would be looking for a row that matches all of those criteria not just one of them.

for a filter that complex i would suggest you use a custom filter function, documentation for which can be [Found Here](http://tabulator.info/docs/3.3#filtering).

Let me know if that helps,

Cheers

Oli
