### ISSUE TITLE
Check if Exist

### ISSUE THREAD

**Issue by vmontal** [olifolkerd/tabulator#839]
How can I check if myTable already exist to avoid to recreate the tabulator object every time?
I tried 

if ($("#myTable").tabulator()) { don't create tabulator object and only refresh data} else { create tabulator object and load data}

but it doesn't work!
Always thanks in advance!

**Comment by olifolkerd** [comment]
Hey @vmontal 

I dont understand why you would be recreating your Tabulator at all?

if you want to change the data in the table you can simply call the ***setData*** function:
```js
$("#example-table").tabulator("setData", tableData);
```

Cheers

Oli

**Comment by vmontal** [comment]
but I don't know if the tabulator object already exist!

I can't use .tabulator("setData") if the object doesn't yet  exist so I have to create the tabulator object

**Comment by olifolkerd** [comment]
in that case check to see if the ***tabulator*** class has been applied to the object.

Cheers

Oli

**Comment by vmontal** [comment]
It's right my question!!!

How can I check  if the tabulator class has been applied to the object.

Thanks in advance
Valerio

**Comment by olifolkerd** [comment]
if ($("#myTable").hasClass("tabulator"))

**Comment by vmontal** [comment]
OK!
Always Thanks!!!!
