### ISSUE TITLE
Web Service Data data object in "Item" 

### ISSUE THREAD

**Issue by msftW8** [olifolkerd/tabulator#84]
My web service source of data gives me the following format of data object;

{"Item":[
{"Name1":"NameValue1","Name1Parameter":"Name1ParameterValue"},
{"Name2":"NameValue2","Name1Parameter":"Name2ParameterValue"}
]}

in contrast the Tabulator example data is an array of objects rather than an object containing arrays; 
[
	{"id":1,"name":"Billy Bob","age":"12","gender":"male","height":1,"col":"red","dob":"15\/07\/1983","cheese":1},
	{"id":2,"name":"Mary May","age":"1","gender":"female","height":2,"col":"blue","dob":"14\/05\/1995","cheese":true},
]

So what is the proper way to get the data into the table with the above web service output?

The provided syntax is not working;
columns:[ {title:"Name1", field:"NameValue1", sorter:"string", width:200},

data = $.parseJSON(data) seems wrong for tabulator as the data is sent in with ajaxURL:

**Comment by olifolkerd** [comment]
If you are loading data via ajax via a url using the ***setData*** function then the returned data must be of the format:

```js
[
      {"id":1,"name":"Billy Bob","age":"12","gender":"male","height":1,"col":"red","dob":"15/07/1983","cheese":1},
      {"id":2,"name":"Mary May","age":"1","gender":"female","height":2,"col":"blue","dob":"14/05/1995","cheese":true},
}
```

If you are providing a different format, you will need to make your own request, map it into the expected structure and pass it to the setData function. for your example you need to pass the ***Item*** parameter of the returned object :

```js
$.ajax({
	url: "/get/data",
	type: "get",
	async: true,
	dataType:'json',
	success: function (sourceData) {
		$("#example-table").tabulator("setData", sourceData.Item);
	},
});
```

**Comment by msftW8** [comment]
The solution provided by olifolkerd worked great, thanks. 

Nice Product!

**Comment by olifolkerd** [comment]
Thanks, Always great to hear you are enjoying using it!
