### ISSUE TITLE
Return one of the pre-built editor formatters from customeditor

### ISSUE THREAD

**Issue by AndrewHutcheson** [olifolkerd/tabulator#840]
So I'm using your tickcross as my editor. But I wanted to be able to disable the editor on certain events. What I did was create a customeditor:

```
var checkMarkEditor = function(cell, onRendered, success, cancel){
		if(teamMenuEditable)
			return "tick";
		else
			return false;
	};
```

unfortunately it's retutning the html string and instead of a checkbox it just says the word "tick", so I need to go back and re-construct the already built-in editor in tabulator, even though that code already exists. So I am either asking for this as a feature request, or if there is a way to programatically disable the editor _without_ having to call $.tabulator() again.

**Comment by olifolkerd** [comment]
Hey @AndrewHutcheson ,

One option would be for you to use the ***editable*** calback on that column, that would let you choose weather on not to allow editing of that cell:

```js
var editCheck = function(cell){
    //cell - the cell component for the editable cell

    //get row data
    var data = cell.getRow().getData();

    return data.age > 18; // only allow the name cell to be edited if the age is over 18
}

//in your column definition for the column
{title:"Name", field:"name", editor:"input", editable:editCheck}
```

If you wanted to create a custom version of an inbuilt editor then that is really easy, all the inbuilt editors are in the */src/js/extensions/edit.js* file.

The tick editor is:
```js
var tickEditor = :function(cell, onRendered, success, cancel, editorParams){
		var value = cell.getValue(),
		input = $("<input type='checkbox'/>");

		//create and style input
		input.css({
			"margin-top":"5px",
			"box-sizing":"border-box",
		})
		.val(value);

		onRendered(function(){
			input.focus();
		});

		if(value === true || value === "true" || value === "True" || value === 1){
			input.prop("checked", true);
		}else{
			input.prop("checked", false);
		}

		//submit new value on blur
		input.on("change blur", function(e){
			success(input.is(":checked"));
		});

		//submit new value on enter
		input.on("keydown", function(e){
			if(e.keyCode == 13){
				success(input.is(":checked"));
			}
			if(e.keyCode == 27){
				cancel();
			}
		});

		return input;
	},
```

If you would like to extend your version of tabulator to include a different editor, please have a look at the [Extensions Documentation](http://tabulator.info/docs/3.3#extension-edit)

Let me know if that helps,

Cheers

Oli :)
