### ISSUE TITLE
Programatically hide a column without re-calling $.tabulator()?

### ISSUE THREAD

**Issue by AndrewHutcheson** [olifolkerd/tabulator#841]
I have a column I want to hide sometimes. Can I set the column visible property programatically?

**Comment by Rodbjartson** [comment]
Hide a column:
`$("#example-table").tabulator("hideColumn","name") //hide the "name" column`

Hide directly on column component:
`column.hide();`

Toggle visibility:
`$("#example-table").tabulator("toggleColumn","name") ////toggle the visibility of the "name" column`

Toggle visibility on column component:
`column.toggle();`
