### ISSUE TITLE
Group header row functionality

### ISSUE THREAD

**Issue by wisdom-17** [olifolkerd/tabulator#843]
Hi,

Thanks for all your work on the plugin and documentation @olifolkerd.

I am looking into the grouping functionality - I want users to be able to add/edit data in header rows too (so they'll be just like other rows in that they'll show data for each column but they'll also have child rows according to the group column).

Is this possible?

**Comment by olifolkerd** [comment]
Hey @wisdom-17 

Thanks for your kind words,

At the moment, this wouldnt be directly possible, but Tabulator does allow for the creation of [Custom Group Headers](http://tabulator.info/docs/3.3#grouping) which may be of some use to you for this.

Cheers

Oli
