### ISSUE TITLE
Use 'groupBy' with an array?

### ISSUE THREAD

**Issue by roypardi** [olifolkerd/tabulator#844]
Hi – this is more of a question than an issue and sorry if my title is not very clear. 

I am able to use "groupBy" with a flat array of objects and it works well. However my data is already "grouped" into objects and arrays and I am trying to find a way to get the "groupBy" behavior without first flattening my data. I've been through the docs and searched through prior issues but haven't discovered if what I am trying to do is possible.

With the example JSON data below, I'd like to be get a table like this:

◀️  **flowers**
 -tulip
 -rose
◀️  **fruits**
 -apples
 -pears

Does this functionality exist? I know I can flatten my data into one array, giving each member a "groupID" and then use that with "groupBy" but am wondering if there is a more direct way.

thanks! 😺 

```
{
	"collection": [{
		"groupName": "flowers",
		"description": "colorful",
                "id": 3,
		"groupMembers": [{
				"name": "tulip",
				"id": 23
			},
			{
				"name": "rose",
				"id": 12
			}
		]
	}, {
		"groupName": "fruits",
		"description": "tasty",
                "id": 4,
		"groupMembers": [{
				"name": "apples",
				"id": 45
			},
			{
				"name": "pears",
				"id": 35
			}
		]
	}]
}
```

**Comment by roypardi** [comment]
I've dug around a bit more and see that need to flatten my data – perhaps using mutators and accessors. I'll close this so as not to clutter up the issues list.

**Comment by olifolkerd** [comment]
Hey @roypardi 

At the moment Tabulator is designed to accept an array of row objects and would not be able to discern from your structure what data goes where, but you can use dot notation in the field names to access nested data for other functionality.

Cheers

Oli
