### ISSUE TITLE
Column Calculations : sum function bug

### ISSUE THREAD

**Issue by jiaqianliCn** [olifolkerd/tabulator#845]
After computing, there are a lot of decimal points.
for example
121.19999999999999

**Comment by olifolkerd** [comment]
hey @jiaqianliCn 

If there are that many decimal places in the data you are summing then that would be an expected output.

In the upcoming 3.4 release there will be additional precision parameters added to the calculation functions to give you more control over their output.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @jiaqianliCn 

You will be happy to hear i have just pushed an update for this to the 3.4 branch, all numerical column calculations now have a ***precision*** calcParam that allows you to set how many decimals you want:

```js
{title:"Age", field:"age", topCalc:"avg", topCalcParams:{precision:2}"}, //calculate average age to 2 decimal places
```

Version 3.4 will be released in the next couple of weeks.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Tabulator version 3.4 has now been officially release!

You can find details of the new release in the [News Section](http://tabulator.info/news)

Full documentation of all the new features can be found [Here](http://tabulator.info/docs/3.4)

Cheers

Oli :)
