### ISSUE TITLE
Small doc error in section about "Movable Rows"

### ISSUE THREAD

**Issue by roypardi** [olifolkerd/tabulator#846]
I was looking for the functionality described in this issue ([Can I combining movable rows with data grouping - so if I move one row from group A to group B it changes the appropriate values?](https://github.com/olifolkerd/tabulator/issues/786) and saw the doc note below ([here](http://tabulator.info/docs/3.3#movable))

<img width="587" alt="screen shot 2018-01-25 at 3 19 38 pm" src="https://user-images.githubusercontent.com/9053196/35410391-49bfaf32-01e3-11e8-8559-8c39960e5775.png">

Is that out of date? I am able to move rows between groups – works great – though as noted in #786, having some additional parameters for the `rowMoved` event (oldValue, newValue, etc.) would make it easier to fully implement updating the row & group data.

And small issue: if I drag all rows out of a group, I am not able to then drag any rows back in.

![test](https://user-images.githubusercontent.com/9053196/35410402-57d3e23c-01e3-11e8-87d7-cfe4a01613d6.gif)

**Comment by olifolkerd** [comment]
Hey @roypardi 

That is actually an error with the behaviour of the row moving, when it moves the rows between groups it is only visual, as the data used to group the row does not change.

In next months 3.4 release this section will be getting an overhaul so the functionality should be come a bit more predictable.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @roypardi 

I have just pushed a load of fixes for the grouping system to the 3.4 branch which will be released later today.

When a group is empty it is now removed from the table , as there are no rows in it and groups cannot exist on their own.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Tabulator version 3.4 has now been officially release!

You can find details of the new release in the [News Section](http://tabulator.info/news)

Full documentation of all the new features can be found [Here](http://tabulator.info/docs/3.4)

Cheers

Oli :)
