### ISSUE TITLE
Column Values are misaligned with Headers after sorting and paging

### ISSUE THREAD

**Issue by rogelioii** [olifolkerd/tabulator#85]
I cannot figure out how to make the column values line up with headers after applying sorting and paging to my dataset.

My javascript is pretty simple.  I've got JSON as input (jsonStr['rows']) 

        //Build Tabulator
        $("#example-table-editable").tabulator({
            columns:[
            {title:"Timestamp", field:"timestamp", sortable:true, sorter:"string", editable:false, width:127, colResizable:true},
            {title:"CDR ID", field:"cdrId", sortable:true, sorter:"string", align:"left", editable:false, width: 150},
            {title:"Local Session ID", field:"localSessionId", sortable:true, sorter:"string", align:"center", editable:false, width:231},
            {title:"Remote Session ID", field:"remoteSessionId", sortable:true, sorter:"string", align:"center", editable:false, width:228},
            {title:"Cause (Calling)", field:"callingCauseValue", align:"right", sortable:true, sorter:"string", editable:false},
            {title:"Cause (Called)", field:"calledCauseValue", align:"right", sortable:true, sorter:"string", editable:false},
            {title:"Host", field:"host", sortable:true, sorter:"string", align:"center", editable:false, width:221},
            {title:"DateTimeOrigination", field:"dateTimeOrigination", align:"center", sortable:true,  sorter:"string", editable:false},
            {title:"DateTimeConnect", field:"dateTimeConnect", align:"center", sortable:true, sorter:"string", editable:false},
            {title:"DateTimeDisconnect", field:"dateTimeDisconnect", align:"center", sortable:true, sorter:"string", editable:false},
            {title:"Duration", field:"duration", align:"center", sortable:true, sorter:"string", editable:false},
            {title:"Jira", field:"Jira", align:"center", sortable:true, sorter:"string", editable:true, editor:"input"},
            {title:"Comments", field:"Comments", align:"center", sortable:true, sorter:"string", editable:true, editor:"input"},
            {title:"Customer Name", field:"CustomerName", sortable:true, sorter:"string", editable:false},
            ],
            cellEdited:function(id,data,value,oldVal,rowData,cell,row){
                console.log("cellEdit: id=" + id);
                console.log("cellEdit: data=" + data);
                console.log("cellEdit: value=" + value);
            },
            fitColumns:true,
            index:"cdrId",
            pagination:true,
            paginationSize:30,
            sortBy:"timestamp",
            sortDir:"desc",
        });

        // set data
        $("#example-table-editable").tabulator("setData", jsonStr['rows']);

When my page first loads, everything is lined up.  but as soon as I click a column heading to sort or click on a page number, the following happens.  How can I get the data to always line up?  Please see screenshot of problem.  Thank You.

![screen shot 2016-11-01 at 4 59 39 pm](https://cloud.githubusercontent.com/assets/5953508/19909309/12f3c682-a055-11e6-87e2-ab6d787194ca.png)

**Comment by olifolkerd** [comment]
which browser are you using?

**Comment by rogelioii** [comment]
I've also tested on Chrome and Firefox and see the same unwanted result.  
Chrome: Version 54.0.2840.71 (64-bit)
Firefox: 49.0.2
Hardware: Macbook Pro

Here's sample data that I've put directly into the javascript file
        jsonData = "{\"rows\":[{\"timestamp\":\"2016-11-01 23:47:48\",\"cdrId\":\"1478035697162_3880\",\"CustomerName\":\"SomeCustomer1\",\"localSessionId\":\"2b2999fb00105000a000d42c448461d0\",\"remoteSessionId\":\"e690a0d5d93658c893680a777bd4c635\",\"callingCauseValue\":0,\"calledCauseValue\":102,\"host\":\"subdomain.moresub.domain.com\",\"dateTimeOrigination\":1478044048,\"dateTimeConnect\":0,\"dateTimeDisconnect\":1478044068,\"duration\":0,\"Jira\":\"\",\"Comments\":\"\"},{\"timestamp\":\"2016-11-01 23:50:13\",\"cdrId\":\"1478035697162_3943\",\"CustomerName\":\"Some Other Customer\",\"localSessionId\":\"cecff28d00225000a743598d86ec0000\",\"remoteSessionId\":\"0b51926d91230097bbd8f7c239810eee7\",\"callingCauseValue\":0,\"calledCauseValue\":102,\"host\":\"abc.abc123.abc123.com\",\"dateTimeOrigination\":1478044193,\"dateTimeConnect\":0,\"dateTimeDisconnect\":1478044213,\"duration\":0,\"Jira\":\"\",\"Comments\":\"\"}]}"
        jsonStr = JSON.parse(jsonData)

$("#example-table-editable").tabulator("setData", jsonStr['rows']);

**Comment by rogelioii** [comment]
I figured out my problem.   I was using an older version of jquery/jquery-ui
I updated to the latest version and it's fixed.  Thank You.

**Comment by olifolkerd** [comment]
Out of curiosity what version of jQuery and jQueryUI were you using?
