### ISSUE TITLE
Number Formatter question

### ISSUE THREAD

**Issue by YendorMc** [olifolkerd/tabulator#851]
Hi all!
Gotta question.  I would like a number in my tabulator table to have comma separator (e.g. 1,000 instead of 1000) and return a blank if the number is actually zero.

I put in a formatter function (see below) that calls CheckNumFilter() that seems to be working, however I eventually want to put these configurations into a JSON array to dynamically load, and I see all kinds of nightmares brewing.  I wanted something separate, as I have several column elements in the table and would like to show it all on one line.

I thought about using the money formatter, but that doesn't return blank.  Thinking about this, it may be counter intuitive, as then I may not be able to take advantage of totaling.  It also seems like I'm more replacing the data (mutating) rather than formatting...

Is there some more conventional way that I'm missing that could be use for the column options in order to put these options in a JSON array?

```js
//example
{title:"Parmeter 1", field:"Parm1", align:"center", headerSort:false,width:100,cssClass:"breakout",**formatter:function(cell,formatterParams){return(checkNumFilter(cell.getValue())**);}},
});
//End Tabulator fields

function **checkNumFilter(num**){
      var tempnum = "";
	  if (num == "0"){
		   tempnum = "";
	  }
	  else if (num == ""){
		 tempnum = "";
	  }
	  else{
		tempnum = Number(num).toLocaleString();
	  }
	  return(tempnum);
}
```

**Comment by olifolkerd** [comment]
you could pass the options for configuring your formatter in the ***formatterParams*** property and then pass this in when you construct the table.

Does that help?

Cheers

Oli

**Comment by YendorMc** [comment]
I'm sorry, I'm still not seeing the light...

I can see:
{title:"Thousands", field:"value", formatter:"money", formatterParams:{"thousand"}
Which will format "10000" to "10,000"

Are you saying I can configure my own formatterParams, say "fred" and put that in the json data?
e.g.
{title:"Thousands", field:"value", formatter:"money", formatterParams:{"fred"}

seems like 'fred' should be a function though...

Thanks!

**Comment by olifolkerd** [comment]
Hey @YendorMc 

It depends on what you want to acheive, if you want to have custom formatting functionality then your only option is to use a function. if you always want to use that function but be able to store that as a string then you could look at [Extending the Formatter Extension](http://tabulator.info/docs/3.3#extension-format) with your own custom formatter, you could then set it with a string like the other built in formatters.

If you are looking to have one formatter that behaves differently for different columns, that is when you would use the ***formatterParams*** to pass in that configuration.

I hope that clears things up a bit.

Cheers

Oli

**Comment by YendorMc** [comment]
Ahhh! how cool!   I think that'll be what I need!  I'll noodle around with that a bit and post an example if others our curious.

Thanks for the support!

**Comment by YendorMc** [comment]
**_It works Oli! 

Wow!  Amazing!  Now I can do all kinds of formatting, use JSON for the configurations and keep it clean!  

So just to document what I did.._**
**_//this goes before invoking tabulator...This will return a number with commas in the 1000's and return blank if zero._**
Tabulator.extendExtension("format", "formatters", {
    numberfmt:function(cell, formatterParams){
	  var num = cell.getValue();
      var tempnum = "";
	  if (num == "0"){
		   tempnum = "";
	  }
	  else if (num == ""){
		 tempnum = "";
	  }
	  else{
		tempnum = Number(num).toLocaleString();
	  }
	  return(tempnum);
    },
});	

**_// then run tabulator as normal with your new command._**
	$("#example-table").tabulator({
		height:600, // set height of table, this enables the Virtual DOM and improves render speed dramatically (can be any valid css height value)
		columnVertAlign:"bottom", //align header contents to bottom of cell
		columns:[ //Define Table Columns
			{title:"Count", field:"Count", align:"center", headerSort:false, width:100, frozen:true, formatter:"numberfmt"},
{title:"Grand Total", field:"Grand Total", align:"center", headerSort:false, width:100, formatter:"numberfmt"},
		],
	});

**_//End example._**

**_//**NOW the column configs can be in JSON!!!**  
//Now just got to make sure I read the JSON file synchronous! :)_** 

**_// Comparison of a sample of what was working before, with messy code (using 1 of the previous line)_**
**_//(in other words, ignore the code below and use the code above)_**

{title:"Count", field:"Count", align:"center", headerSort:false, width:100, frozen:true, formatter:function(cell, formatterParams){return(checkNumFilter(cell.getValue()));}},

**_//and calling this function out side of invoking tabulator_**
function checkNumFilter(num){
	//var num = cell.getValue();
      var tempnum = "";
	  if (num == "0"){
		   tempnum = "";
	  }
	  else if (num == ""){
		 tempnum = "";
	  }
	  else{
		tempnum = Number(num).toLocaleString();
	  }
	  return(tempnum);
}

**Comment by olifolkerd** [comment]
Hey @YendorMc 

Great news! I'm glad to hear it worked for you. i have tweaked the markdown in your last post to make the code easier to read.

you don't need to worry about synchronously reading the JSON file, if you want to do it by ajax, then you can use the ***setColumns*** function update the column setup after the table is built.

Cheers

Oli :)

**Comment by fuinyroot** [comment]
There is a simpler solution than extension:

```
formatter:"money", formatterParams:{precision:false}
```

It will display `18605840`  as `18,605,840`.
