### ISSUE TITLE
How can I hide the grey overlay while reloading AJAX ?

### ISSUE THREAD

**Issue by fsxpilot44** [olifolkerd/tabulator#854]
Hello,

I have a button on my form which refreshes the tabulator using the following line:
$("#projectsTable").tabulator("setData", "/api/Project");

I want to hide the "Loading" message and its grey overlay. 
I tried setting ajaxLoader:false while setting up my tabulator like this
            $("#projectsTable").tabulator({
                layout: "fitColumns",
                placeholder: "No Data Set",
                **ajaxLoader: false**,
                pagination: "local",
with no success.

Thanks for your help !

**Comment by Rodbjartson** [comment]
> When loading data, Tabulator can display a loading overlay over the table. This consists of a modal background and a loader element. The loader element can be set globally in the options and should be specified as a div with a display style of inline-block

`<div style='display:inline-block; border:4px solid #333; border-radius:10px; background:#fff; font-weight:bold; font-size:16px; color:#000; padding:10px 20px;'>Loading Data</div>`

**Comment by fsxpilot44** [comment]
I think I was misunderstood. I want to HIDE the overlay and NOT display one if my own.

**Comment by Rodbjartson** [comment]
@olifolkerd 
Oli, can we set ajaxLoader to false?

**Comment by fsxpilot44** [comment]
hello, the only solution I found was to edit the minified CSS file and add
display:none to the loader. Would be nice if it was a config parameter. Thnx


On 5 Feb 2018 11:04 am, "Rodbjartson" <notifications@github.com> wrote:

@olifolkerd <https://github.com/olifolkerd>
Oli, can we set ajaxLoader to false?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/olifolkerd/tabulator/issues/854#issuecomment-363021572>,
or mute the thread

**Comment by olifolkerd** [comment]
Hey Guys,

sorry for the delay in getting back to you, i was away this weekend.

as @Rodbjartson said, you should just be able to pass a value of ***false*** to the ***ajaxLoader*** option to prevent it loading.

is this not the case?

Cheers

Oli

**Comment by fsxpilot44** [comment]
Thanks for your reply. I'm afraid setting the ajaxloader to false(as suggested in the documentation) didn't work

**Comment by olifolkerd** [comment]
I will have a look into that this evening

**Comment by drGrabol** [comment]
Its true, ajaxloader  options unfortunately doesn't work.

**Comment by drGrabol** [comment]
@fsxpilot44 Can you point what to change in  minified CSS file as a workarounbd. I cant figure out.

**Comment by olifolkerd** [comment]
Hey guys,

This is definitely a bug, i will make sure a fix for it is included in the 3.4 release this weekend.

Cheers

Oli :)

**Comment by fsxpilot44** [comment]
I changed as follows (I added "display:none" in bold):
....  .tabulator-loader{position:absolute;display-ms-flexbox;display:flex;**display:none**;-mx-flex-align:center;align-items:center......

**Comment by olifolkerd** [comment]
Hey All,

You will be happy to hear i have just pushed a fix for this to the 3.4 branch which will be released tomorrow.

Cheers

Oli :)

**Comment by fsxpilot44** [comment]
Thank you Oli for the quick fix ! Tabulator is awesome and you're doing great job

**Comment by olifolkerd** [comment]
Tabulator version 3.4 has now been officially release!

You can find details of the new release in the [News Section](http://tabulator.info/news)

Full documentation of all the new features can be found [Here](http://tabulator.info/docs/3.4)

Cheers

Oli :)
