### ISSUE TITLE
Can tabulator undo after row moved?

### ISSUE THREAD

**Issue by ZinThiThiTun** [olifolkerd/tabulator#855]
Hello!
I'm using tabulator and occurring some problems.
Please tell me how can i do to solve following problem.
1.After moving tabulator row,can we undo?
2.After moving tabulator row,can rownum column recaculate?

Hope you can help me.
Thanks.

**Comment by olifolkerd** [comment]
Hey @ZinThiThiTun 

There is no inbuilt row undo function, but i like that idea, i will add it to the roadmap to add it to the history extension.

In the version 3.4 release which will be coming out this weekend, you will be able to call a new ***reformat*** function on row components to trigger exactly that.

Hopefully you can hold out for one week.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @ZinThiThiTun 

You will be happy to hear i have just pushed this feature to the 3.4 branch, row moves will now be tracked by the history extension so they can be undone.

Version 3.4 will be released tomorrow.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Tabulator version 3.4 has now been officially release!

You can find details of the new release in the [News Section](http://tabulator.info/news)

Full documentation of all the new features can be found [Here](http://tabulator.info/docs/3.4)

Cheers

Oli :)
