### ISSUE TITLE
Dynamic Horizontal scrollTo column

### ISSUE THREAD

**Issue by kerkh004** [olifolkerd/tabulator#856]
Hi,
I'm using the tabulator for creating a table with two frozen columns (Left) and next to that all the months of the year (12 columns). If the table is loaded first, you see all the columns until september and you have to scroll horizontal to see column okt, nov and dec. In this way I can load also 52 weeks of the year in the same table with a max width of the table.
 
Now when I edit a cell, for instance a cell in november and I reload the table, I like to scroll or go to the cell I've recently have edit. So, that my view of the table still is on the column november and the cell I have edited. Now it's jumping back to the first view and I have to scroll back to november.
The reason why I reload the table after editing a cell, is that the row above the cell I'm editing has the sum of the total.

Is there a way to scroll to a cell or column dynamicly after the table is rendered in the same way as scroll to a row?

For vertical scroll (ScrollToRow) I use this code and works perfect:
var tbltr = $("#tabelinvoer").tabulator({
            	            	 height:"500px",
            	            	 ajaxURL:"ajax/ophalenajax.php", //ajax URL
         	            	     ajaxParams:{keuze:"tabelsenop",overzicht: $('#overzichtcombobox').val(), periode: $('#tijdcombobox').val(), jaar: $('#jaarcombobox').val()}, //ajax parameters
         	            	     ajaxConfig:"POST", 
            	                 columns:kolommen,
            	                 cellEdited:function(cell){
            	                	 var data = cell.getRow().getData();
            	                	 var kolom = cell.getColumn().getField();
            	                	 var id = data.id;
            	                	 var waarde = cell.getValue();
            	                	 rowIdToScroll = id;
            	                	 cell2 = cell; 
            	                	 $.post("ajax/ophalenajax.php", {keuze: "opslaandriver", kolom: kolom, iddriver: id, waarde: waarde, jaar: $('#jaarcombobox').val(), overzicht: $('#overzichtcombobox').val(), periode: $('#tijdcombobox').val()},
             	             				function(data){
            	                		 			overzicht_keuze(periode);
            	                		 			tbltr.tabulator("setColumns", kolommen);
            	                		 			tbltr.tabulator("setData","ajax/ophalenajax.php", {keuze:"tabelsenop",overzicht: $('#overzichtcombobox').val(), periode: $('#tijdcombobox').val(), jaar: $('#jaarcombobox').val()}, "POST");	
                       	             		 });
            	                 },
            	                 rowFormatter:function(row){
            	                     if(row.getData().col == "green"){
            	                         row.getElement().css({"font-weight": "bold", "background-color":"#F4FAE3","border":"solid 1px #dfdfdf"});
            	                     }
            	                     if(row.getData().col == "red"){
            	                         row.getElement().css({"background-color":"#FEEACC","border":"solid 1px #dfdfdf"});
            	                     }
            	                     if(row.getData().col == "blue"){
            	                         row.getElement().css({"background-color":"#007700","border":"solid 1px #dfdfdf","color":"#fff"});
            	                     }
            	                 },
            	                 renderComplete:function(){
            	                	 if (rowIdToScroll > 1){ 
            	                		 tbltr.tabulator("scrollToRow", rowIdToScroll);
         	                		}
            	                 },
            	                 
            	             });

Best regards,
Eric

**Comment by olifolkerd** [comment]
Hey @kerkh004 

There is currently no inbuilt scroll to column functionality, but i think that is a great idea!

i will add it to the roadmap!

Cheers

Oli:)

**Comment by olifolkerd** [comment]
Hey @kerkh004 

You will be happy to hear i have just pushed the code for this feature to the 3.4 branch which will be released tomorrow.

You will be able to trigger a scroll to any column using the new ***scrollToColumn*** function:
```js
$("#example-table").tabulator("scrollToColumn", "age"); //scroll to the column with a field of "age"
```
I hope that helps,

Cheers,

Oli :)

**Comment by olifolkerd** [comment]
Tabulator version 3.4 has now been officially release!

You can find details of the new release in the [News Section](http://tabulator.info/news)

Full documentation of all the new features can be found [Here](http://tabulator.info/docs/3.4)

Cheers

Oli :)

**Comment by mikexmagic** [comment]
hi @olifolkerd 
I have an issue with this function :-(
If I call it, the header scrolls to the right position, but the rows not. As soon I start scrolling manually, the header jumps back to the default position (matching the rows).

known issue?
thx, Mike :-)
