### ISSUE TITLE
Correct the release version date on the website.

### ISSUE THREAD

**Issue by git265** [olifolkerd/tabulator#857]
http://tabulator.info/news

Version 3.3 Released01/10/2017  - I think this should be 2018

**Comment by olifolkerd** [comment]
Hey @git265 

Nope that is the correct date that 3.3 was released, we are currently on v3.3.3

version 3.4 will be released in a week or so.

Cheers

Oli

**Comment by olifolkerd** [comment]
Tabulator version 3.4 has now been officially release!

You can find details of the new release in the [News Section](http://tabulator.info/news)

Full documentation of all the new features can be found [Here](http://tabulator.info/docs/3.4)

Cheers

Oli :)
