### ISSUE TITLE
No working examples found

### ISSUE THREAD

**Issue by E3V3A** [olifolkerd/tabulator#858]
I'm a first time user of your package, but even going through the extensive [documentation](http://tabulator.info/docs/), examples, and even quick start, **there is not a single working example**, that take you from a HTML or node file, to a working page with the table. 

What you seem to provide as examples when clicking view source, only provide the JS part, no data or anything else. 

I've tried the following with all kinds of variations, but no table appears... 

Any idea, what I'm doing wrong here? 

```javascript

<!DOCTYPE html>
<html>
<title>Test Page</title>

<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8"/> 

  <!--script type="text/javascript" src="node_modules/jquery/dist/jquery.min.js"></script>
  <scr-ipt type="text/javascript" src="node_modules/jquery-ui-dist/jquery-ui.min.js"></script-->

  <script type="text/javascript" src="dist/jquery.min.js"></script>
  <script type="text/javascript" src="jquery-ui-dist/jquery-ui.min.js"></script>


  <link href="https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.3.3/css/tabulator.min.css" rel="stylesheet">
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.3.3/js/tabulator.min.js"></script>

  <!--link href="node_modules/jquery.tabulator/dist/css/tabulator.min.css" rel="stylesheet">
  <script type="text/javascript" src="node_modules/jquery.tabulator/dist/js/tabulator.min.js"></script-->

<script  type="text/javascript">
//'use strict'
//const tabulator = require('jquery.tabulator');

var sampleData = [
  {id:1, name:"Oli Bob", progress:12, gender:"male", rating:1, col:"red", dob:"", car:1, lucky_no:5, cheese:"Cheader"},
  {id:2, name:"Mary May", progress:1, gender:"female", rating:2, col:"blue", dob:"14/05/1982", car:true, lucky_no:10, cheese:"Gouda"},
  {id:3, name:"Christine Lobowski", progress:42, gender:"female", rating:0, col:"green", dob:"22/05/1982", car:"true", lucky_no:12, cheese:"Manchego"},
  {id:4, name:"Brendon Philips", progress:100, gender:"male", rating:1, col:"orange", dob:"01/08/1980", lucky_no:18, cheese:"Brie"},
  {id:5, name:"Margret Marmajuke", progress:16, gender:"female", rating:5, col:"yellow", dob:"31/01/1999", lucky_no:33, 
cheese:"Cheader"},
];

$("#example-table").tabulator("setData", sampleData);

$("#example-table").tabulator({
  columns:[
    {title:"Name", field:"name", sortable:true, width:200},
    {title:"Progress", field:"progress", sortable:true, sorter:"number"},
    {title:"Gender", field:"gender", sortable:true},
    {title:"Favourite Color", field:"col", sortable:false},
    {title:"Date Of Birth", field:"dob"},
    {title:"Cheese Preference", field:"cheese"},
  ],
});

</script>
</head>

<body>
  <h1>This is a heading</h1>
  <p>This is a paragraph.</p>
  <div id="example-table"></div>
</body>
</html>

```

**Comment by Rodbjartson** [comment]
Car and lucky no? Where do you define those columns in your table constructor? ;)

**Comment by E3V3A** [comment]
@Rodbjartson 
> Car and lucky no? 

Huh? 

Anyway, I finally got a table going. By realizing:

1. Surprisingly the order of `var ...` vs. `#blahblah.tabulator(...` matters.
2. resulting paths after `npm install jquery.** --save` are not found properly. Manually copying all *.js, *.css seem to work for now. No idea what is wrong.
3. please provide some better working examples in you docs.

**Comment by olifolkerd** [comment]
Hey @E3V3A 

Im afraid i dont follow...

Tabulator is a library that is used across a wide variety of platforms not just Node.js and to be as neutral as possible i keep to just instructions on how to install and use the library.

It should be installed just like any other node library. I have used it on quite a few node projects and never had to copy any files so that is a bit concerning to hear. is this a blank project you are adding it into?

The reason you were having difficulties is because you were trying to set the data of the table before table had been created,

The [Set Table Data Documentation](http://tabulator.info/docs/3.3#set-data), the [Quickstart Guide](http://tabulator.info/quickstart/3.3) and the {Ajax Example](http://tabulator.info/examples/3.3#ajax) all include sample data sets if you need some guidance]

I hope that helps

Cheers

Oli :)

**Comment by E3V3A** [comment]
@olifolkerd 
> Tabulator is a library that is used across a wide variety of platforms not just Node.js and to be as neutral as possible i keep to just instructions on how to install and use the library and not tips on how to use a specific platform. 

I normally agree on that, but given that googling on the subject for a working example (for this specific package), is giving close to zero results, whereas on the more general subject of jQ and alternative JSON to HTML packages, results in zillions, I think one full example that actually work (from e.g. a `git clone example...`), could save people (like me) a lot of time and futile efforts in trying to decipher and extrapolate its use. For example, it probably took me an hour in total just to figure out how to sort the darn thing. From reading through all docs, too brief examples, and options that does not seem to do what one expects. (Why is my table still sortable with (sort arrows) even though I have declared `headerSort:false` and made all columns `sortable:false`?)

Anyway, thank you very much for at least trying to support and giving quick answers.

**Comment by Ferrous256** [comment]
Adding the jsquery wrapper to the head of my html file to the above example worked for me.
```
<head>
  <script type="text/javascript" src="/js/jquery-3.1.1.min.js"></script>
  <script type="text/javascript" src="/js/jquery-ui.min.js"></script>
  <script type="text/javascript" src="/js/jquery_wrapper.min.js"></script>
  <script type="text/javascript" src="/js/tabulator.min.js"></script>
  <link rel="stylesheet" href="/css/jquery-ui.min.css">
  <link rel="stylesheet" href="/css/tabulator.min.css">
</head>
```
I'm using Node JS and Express. I'm sure there's a way to get the ./node_modules/tabulator/ path to work, but I couldn't get it working so I manually added jquery and tabulator .js and .css files to my ./public/js and ./public/css folders respectively.
