### ISSUE TITLE
Concat Columns

### ISSUE THREAD

**Issue by vmontal** [olifolkerd/tabulator#859]
For several reasons I'd need to concat more fields in the same columns;
i.e.
 { title: "List", 
field: elencoCampi[1] + " - " + elencoCampi[2] + " - " + elencoCampi[3] + " - " + elencoCampi[4], ...

elencoCampi[x] = name of fields that I retrieve dinamically 

How can I do?

Thanks in advance!

**Comment by Rodbjartson** [comment]
Try using:

`var cells = column.getCells();`

Console.log(cells) and see what you can use.

Perhaps var cellValue = cells[0].getValue();

Just try and play around with these, check the console on what these arrays contain!

**Comment by olifolkerd** [comment]
Hey @vmontal ,

If you want to be able to sort by that data etc i would suggest using [Mutators](http://tabulator.info/docs/3.3#get-set) and assigning the column to a non existent field that you then create with a mutator:

```js
{title:"List", field:"list", mutator:function(value, data, type, mutatorParams, cell){
        //value - original value of the cell
        //data - the data for the row
        //type - the type of mutation occuring (data|edit)
        //mutatorParams - the mutatorParams object from the column definition
        //cell - when the "type" argument is "edit", this contains the cell component for the edited cell, otherwise it is undefined

        return data[elencoCampi[1]] + " - " + data[elencoCampi[2]] + " - " + data[elencoCampi[3]] + " - " + data[elencoCampi[4]];
    },
}
```

Let me know if that helps.

Cheers

Oli :)

**Comment by vmontal** [comment]
Hey Oli, it's working! after upgraded to 3.3!

.... but now why "visible:false" doesn't work? (I'm driving up the wall!)

Always Thanks

**Comment by olifolkerd** [comment]
Hey @vmontal 

the ***visible*** column definition is still working in 3.3, i just tested it to be sure.  could you post a copy of your table constructor so i can see what advice i can give.

Cheers

Oli

**Comment by vmontal** [comment]
`        var tabella = function (larghezza, parametri, callback) {
            //console.log(larghezza);
            var tabella = parametri.tabella;
            var elencoCampi = parametri.elencoCampi;
            var headerTabella = parametri.headerTabella;
            var scheda = parametri.scheda;
            $scope[scheda] = false;
            $("#tabella" + tabella).tabulator({
                height: "400px",
                responsiveLayout: true,
                //layout: "fitColumns",
                //colResizable: false,
                sortable: false,
                colVertAlign: "center",
                selectable: 0,
                //pagination: "local",
                //paginationSize: 10,

                columns: [
                    { title: headerTabella[0], field: elencoCampi[0], visible: false },
                    { title: "Elenco " + parametri.tabella, field: "list", mutator: function (value, data, type, mutatorParams, cell) { return data[elencoCampi[1]] + " - " + data[elencoCampi[2]] + " - " + data[elencoCampi[3]] + " - " + data[elencoCampi[4]]; }, width: parseInt(larghezza * 0.80), minWidth: 10, sorter: "string", align: "left", headerFilter: true, responsive: 0 },
                    //{ title: headerTabella[1], field: elencoCampi[1], width: parseInt(larghezza * 0.30), minWidth: 10, sorter: "string", align: "left", headerFilter: true, responsive: 0 }, 
                    //{ title: headerTabella[2], field: elencoCampi[2], width: parseInt(larghezza * 0.25), minWidth: 10, sorter: "string", align: "left", headerFilter: true, responsive: 2 }, 
                    //{ title: headerTabella[3], field: elencoCampi[3], width: parseInt(larghezza * 0.20), minWidth: 10, sorter: "string", align: "left", headerFilter: true, responsive: 3 }, 
                    //{ title: headerTabella[4], field: elencoCampi[4], width: parseInt(larghezza * 0.20), minWidth: 50, sorter: "string", align: "left", headerFilter: true, responsive: 4 }, 
                ],

                index: elencoCampi[0],

                rowClick: function (e, row) {
                    var data = row.getData();

                    if (idKey === data[elencoCampi[0]]) {
                        $scope[scheda] = false;
                        idKey = 0;
                    } else {
                        $scope[scheda] = true;
                        idKey = data[elencoCampi[0]];
                        var id = parametri.idKey;
                        parametri.campoID[id] = idKey ;
                        getAnagrafe(parametri);
                    };
                    $scope.$apply();
                },

                //rowSelectionChanged: function (data, rows) {

                //},

                //rowEdit: function (row, data) {

                //},

                rowFormatter: function (row) {
                    //var data = row.getData();

                    row.getElement().css({
                        height: 40,
                        backgroundColor: style.backColor,
                        color: style.color,
                        fontWeight: style.fontWeight,
                        border: "1px solid",
                        borderColor: "lightgray"
                    });

                },
            });

            if (callback && typeof callback === "function") {
                callback();
            };

        };`
and in the css file I changed 'white-space:normal' in order to wrap the text inside the cells
