### ISSUE TITLE
How to disable sorting and remove sort arrows?

### ISSUE THREAD

**Issue by E3V3A** [olifolkerd/tabulator#861]
I've been searching around here for a solution to do the following:
* Do an initial sort of table on one column.  `ok` ✔️
* Disable table click sorting from rendered page. `not ok` ✖️  
* Remove sort "arrows" from table header. `not ok` ✖️ 

Any suggestions?

**Comment by olifolkerd** [comment]
set the ***headerSort*** property to ***false*** in the column definition:
```
{title:"Name", field:"name", sorter:"string", headerSort:false}
```

Checkout the [Sorting Documentation](http://tabulator.info/docs/3.3#sorting) for more info.

Cheers

Oli :)

**Comment by E3V3A** [comment]
@olifolkerd 
I did that, and it is not working, which is why I am asking and filing an issue.  And I also tried both #372 and #682, to no effect. So if this is working for everyone else, I guess I must have a system issue. My table still sortable with (sort arrows) even though I have declared `headerSort:false` and made all columns `sortable:false`.

Here's my CSS:
```css
/* Remove the sort arrows in table headers */
.tabulator .tabulator-header .tabulator-col[data-sortable=true] .tabulator-col-title {width: 100%;}
.tabulator-arrow {display: none;}
```

and here's the relevant part of my table stuff:
```javascript
...
$("#mytable").tabulator({
    height:205,                         // Set height of table, this enables the Virtual DOM and improves render speed
    //layout:"fitColumns",              // Fit columns to width of table (optional)
    headerSort:false,                   // Disable header sorter
    resizableColumns:false,             // Disable column resize
    responsiveLayout:true,              // Enable responsive layouts
    placeholder:"No Data Available",    // Display message to user on empty table
    initialSort:[                       // Define the sort order:
        {column:"altitude",     dir:"asc"},     // 1'st
    ],
    columns:[
        {title:"Flight",        field:"flight",         sortable:false, responsive:0, align:"left"}, // , width:250},
        {title:"CallSig",       field:"callsign",       sortable:false, responsive:3},
...
```

This is really weird. 

Is there a way to check my installation?

**Comment by olifolkerd** [comment]
@E3V3A 

Thanks for posting the table constructor that is a big help.

You need to set the ***headerSort*** property in the column definition object for the column you want to not be sortable, not on the table as a whole. the ***sortable*** property you are currently using in your column definition was removed in version 3.0

I hope that helps.

Cheers

Oli :)

**Comment by E3V3A** [comment]
That did it! Thank you!

**Comment by erikdemarco** [comment]
there is no way to disable and remove this sorting mechanism globally when setting: "autoColumns:true,"?

**Comment by olifolkerd** [comment]
@erikdemarco yes you can use the columnDefaults option object to set this in all columns
