### ISSUE TITLE
Column misalignment on row hover in Chrome 64

### ISSUE THREAD

**Issue by tomheaps** [olifolkerd/tabulator#863]
Hey @olifolkerd. I have noticed a bug in the latest version of chrome (64) using tabulator 3.3.3.

If you have a cell containing text that overflows with an ellipsis, column alignment is initially fine however as soon as you hover over the row the right border of the cell containing the overflowing text moves slightly to the right out of alignment - see screenshot below. Alignment is corrected if you reload the page however hovering over that row again causes the same misalignment.

Interestingly this doesn't happen in IE11!

![download](https://user-images.githubusercontent.com/13905479/35886393-cb59b5e8-0b88-11e8-86e4-46ac1bef1578.png)

**Comment by olifolkerd** [comment]
Hey @tomheaps 

Do you have a copy of your table constructor that i can use to replicate the issue?

Cheers

Oli

**Comment by tomheaps** [comment]
Hi @olifolkerd, table construct below:

 $("#aec-whiteboard").tabulator({
    layout: "fitColumns",
    resizableColumns: false,
    initialSort: [{
      column: "elapsed",
      dir: "desc"
    }],
    ajaxLoaderLoading: "<img src='img/spinner.gif'/><p>Updating Data</p>",
    ajaxLoaderError: "<img src='img/spinner-red.gif'/><p>Connection Error!</p><p>Unable to update data...</p>",
    columns: [{
        title: "ID",
        field: "id",
        align: "center",
        visible: false,
        sorter: "number"
      },
      {
        title: "Patient Name",
        field: "name",
        width: 280,
        sorter: sortString,
        cellClick: function(e, cell) {
          if (cell.getValue() === "") {
            return false
          } else {
            var row = cell.getRow()
            var index = row.getIndex();
            var name = cell.getValue();
            var fullName = name.split(', ');
            var lastName = fullName[0];
            var firstName = fullName[fullName.length - 1];
            $('#index').text(index);
            $('#forenameEdit').val(firstName);
            $('#surnameEdit').val(lastName);
            $('#editModal').modal('show');
          }
        }
      }, {
        title: "<i class='fal fa-map-marker-alt'></i>",
        field: "loc",
        align: "center",
        width: 80,
        editor: locEditor,
        sorter: sortString
      },
      {
        title: "Type",
        field: "type",
        align: "center",
        width: 120,
        editor: typeEditor,
        sorter: sortString,
      },
      {
        title: "TOA",
        field: "time",
        align: "center",
        editor: flatpickerEditor,
        width: 80,
        headerSort: false,
      }, {
        title: "Elapsed",
        field: "elapsed",
        mutator: timeElapsed,
        width: 120,
        align: "center",
        sorter: "number",
        editor: true,
        visible: false,
      }, {
        title: "<i class='fal fa-stopwatch'></i> LOS",
        field: "los",
        align: "center",
        width: 120,
        mutator: mutateLOS,
        formatter: formatLOS,
        headerSort: false,
        sorter: function(a, b, aRow, bRow, sorterParams) {
          return (aRow.getData().elapsed) - (bRow.getData().elapsed);
        }
      },
      {
        title: "Specialty",
        field: "specialty",
        align: "center",
        width: 120,
        editor: specialtyEditor,
        sorter: sortString,
        formatter: specialtyFormatter,
        tooltip: true
      },
      {
        title: "Obs",
        field: "obs",
        cellClick: cellClicker,
        formatter: doneNotdone,
        align: "center",
        width: 100,


      },
      {
        title: "Bloods",
        field: "bloods",
        cellClick: cellClicker,
        formatter: doneNotdone,
        align: "center",
        width: 100,
      },
      {
        title: "ECG",
        field: "ecg",
        cellClick: cellClicker,
        formatter: doneNotdone,
        align: "center",
        width: 100,
      }, {
        title: "CXR",
        field: "cxr",
        cellClick: cellClicker,
        formatter: doneNotdone,
        align: "center",
        width: 100,
      }, {
        title: "Clerk",
        field: "clerk",
        editor: true,
        align: "center",
        width: 100,
      }, {
        title: "Cons",
        field: "cons",
        cellClick: cellClicker,
        formatter: doneNotdone,
        align: "center",
        width: 100,
      },
      {
        title: "Notes / Plan",
        field: "notes",
        editor: true,
        headerSort: false,
        width: 280,
      },
      {
        title: "Outcome",
        field: "outcome",
        editor: outcomeEditor,
        formatter: outcomeFormatter,
        headerSort: false,
        width: 100,
        align: "center"
      },
      {
        title: "TOD",
        field: "tod",
        width: 80,
        align: "center",
        editor: flatpickerEditor,
        headerSort: false,
      },
      {
        title: "Delete",
        formatter: deleteIcon,
        align: "center",
        headerSort: false,
        cellClick: function(e, cell) {
          var id = cell.getRow().getIndex();
          var name = cell.getRow().getData().name
          var deleteModal = $('#deleteModal');
          $('#dischargeName').text(name);
          deleteModal.modal('show');
          deleteModal.one('click', '.button-danger', function() {
            $.ajax({
              type: "POST",
              url: "php/aec-delete.php",
              data: 'id=' + id,
              complete: function() {
                $('#aec-whiteboard').tabulator('deleteRow', id);
                deleteModal.modal('hide');
                updateOnce();
              }
            });
          });
        }
      }
    ],
    dataEdited: function(data) {
      localStorage.setItem("tabulator-data", JSON.stringify(data));
    },

    cellEditing: function(cell) {
      clearTimeout(timeOut);
      timeOut = null;
    },
    cellEdited: function(cell) {
      var value = cell.getValue();
      var field = cell.getField();
      var id = cell.getRow().getIndex();
      $.ajax({
        data: 'field=' + field + '&value=' + value + '&id=' + id,
        url: "php/aec-update.php",
        type: "POST",
        complete: function() {
          if (timeOut == null) {
            updateTable();
          }
          if (field === "type") {
            statusUpdate();
          }
        }
      })
    },
    ajaxError: function(xhr, textStatus, errorThrown) {
      var data = localStorage.getItem("tabulator-data");
      if (data) {
        $("#aec-whiteboard").tabulator("setData", JSON.parse(data));
      }
    },
  });
  //$("#aec-whiteboard").tabulator("setData", tableData);
  $("#aec-whiteboard").tabulator("setData", "php/aec-fetch.php", {}, ajaxSet);
  $(window).resize(function() {
    $("#aec-whiteboard").tabulator("redraw", true);
  });

**Comment by tomheaps** [comment]
Don't know if you also need all the custom variables I have set:

```
 var locEditor = function(cell, onRendered, success, cancel) {
    var editor = $("<select class='form-control'><option value='WR'>WR</option><option value='Triage'>Triage</option><option value='XR'>XR</option><option value='Clinic 1'>Clinic 1</option><option value='Clinic 2'>Clinic 2</option><option value='Clinic 3'>Clinic 3</option><option value='Clinic 4'>Clinic 4</option><option value='Bay 1'>Bay 1</option><option value='Bay 2'>Bay 2</option><option value='Bay 3'>Bay 3</option><option value='Bay 4'>Bay 4</option><option value='Bay 5'>Bay 5</option><option value='Bay 6'>Bay 6</option></select>");
    editor.val(cell.getValue());
    onRendered(function() {
      editor.focus();
    });
    editor.on("change blur", function(e) {
      success(editor.val());
    });
    return editor;
  };

  function flatpickerEditor(cell, onRendered, success, cancel) {
    var cellValue = cell.getValue();
    var hoursNow = moment().format('HH');
    var minutesNow = moment().format('mm');
    var timeNow = hoursNow + ':' + minutesNow;
    var toa = cell.getRow().getCell("time").getValue();
    var input = $("<input id='flatpickr' type='text'/>");
    const fp = input.flatpickr({
      enableTime: true,
      noCalendar: true,
      enableSeconds: false,
      time_24hr: true,
      dateFormat: "H:i",
      minuteIncrement: 1,
      locale: 'en',
      defaultDate: cellValue,
      defaultHour: hoursNow,
      defaultMinute: minutesNow,
      onReady: function() {
        $("<div/>", {
          class: 'flatpickr-confirm',
          on: {
            click: function() {
              fp.close();
            }
          },
          append: ' <i class="fal fa-check-circle"></i>',
          appendTo: '.flatpickr-calendar',
        });
      },
      onOpen: function() {
        if (cellValue === "" || cellValue == null) {
          input.val(timeNow);
        } else {
          input.val(cellValue);
        }
      },
      onChange: function() {
        if (cell.getField() === "tod") {
          fp.set("minDate", toa);
        }
      },
      onClose: function(selectedDates, dateStr, instance) {
        evt = window.event;
        var isEscape = false;
        if ("key" in evt) {
          isEscape = (evt.key === "Escape" || evt.key === "Esc");
        } else {
          isEscape = (evt.keyCode === 27);
        }
        if (isEscape) {
          cancel();
        } else {
          success(dateStr);
        }
      }
    });
    input.css({
      "border-radius": "0",
      "background": "#fff",
      "padding": "2px",
      "width": "100%",
      "height": "100%",
      "box-sizing": "border-box",
      "text-align": "center"
    });
    var inputBlur = function(e) {
      if (e.target !== input[0]) {
        if ($(e.target).closest(".flatpicker-input").length === 0) {
          $(document).off("mousedown", inputBlur);
        }
      }
    };
    $(document).on("mousedown", inputBlur);
    onRendered(function() {
      input.focus();
    });
    return input;
  }

  var specialtyEditor = function(cell, onRendered, success, cancel) {
    var editor = $("<select class='form-control'><option value=''></option><option value='Cardiology'>Cardiology</option><option value='DALT'>DALT</option><option value='Frailty'>Frailty</option><option value='Gastroenterology'>Gastroenterology</option><option value='Haematology'>Haematololgy</option><option value='Oncology'>Oncology</option><option value='OPAT'>OPAT</option><option value='Respiratory'>Respiratory</option><option value='Stroke'>Stroke</option><option value='ENT'>ENT</option><option value='Surgery'>General Surgery</option><option value='Gynaecology'>Gynaecology</option><option value='Orthopaedics'>Orthopaedics</option><option value='Urology'>Urology</option></select>");
    editor.val(cell.getValue());
    onRendered(function() {
      editor.focus();
    });
    editor.on("change blur", function(e) {
      success(editor.val());
    });
    return editor;
  };
  var typeEditor = function(cell, onRendered, success, cancel) {
    var editor = $("<select class='form-control'><option value='New-GP'>New-GP</option><option value='New-ED'>New-ED</option><option value='New-Other'>New-Other</option><option value='F/U'>Follow-Up</option></select>");

    editor.val(cell.getValue());
    onRendered(function() {
      editor.focus();
    });
    editor.on("change blur", function(e) {
      success(editor.val());
    });
    return editor;
  }
  var outcomeEditor = function(cell, onRendered, success, cancel) {
    var editor = $("<select class='form-control'><option value=''></option><option value='DCnoFU'>Discharge-no F/U</option><option value='DCwFU'>Discharge-with F/U</option><option value='Admit'>Admit</option></select>");
    editor.val(cell.getValue());
    onRendered(function() {
      editor.focus();
    });
    editor.on("change blur", function(e) {
      success(editor.val());
    });
    return editor;
  }
  var outcomeFormatter = function(cell, formatterParams) {
    var cellValue = cell.getValue();
    if (cellValue == "DCnoFU") {
      return '<i class="blue fal fa-home"></i>';
    } else if (cellValue == "DCwFU") {
      return '<span class="blue"><i class="fal fa-home"></i><sup> +F/U<sup></span>';
    } else if (cellValue == "Admit") {
      return '<em class="red">ADMIT</em>'
    } else {
      return cellValue
    }
  }
  var cellClicker = function(e, cell) {
    var cellValue = cell.getValue();
    if (cellValue == "true") {
      cell.setValue("false")
    } else {
      cell.setValue("true")
    }
  }
  var doneNotdone = function(cell, formatterParams) {
    var cellValue = cell.getValue();
    if (cellValue == "true") {
      return "<i class='green fal fa-check'></i>"
    }
    if (cellValue == "false") {
      return "<i class='red fal fa-times'></i>"
    }

  };
  var specialtyFormatter = function(cell, formatterParams) {
    var cellValue = cell.getValue();
    if (cellValue == "Surgery") {
      cell.getRow().getElement().css({
        "background-color": "rgba(250,82,82,0.2)"
      });
      return "<i style='font-size:1.125rem' class='red flaticon-scalpel'></i>";
    } else if (cellValue == "Gynaecology") {
      cell.getRow().getElement().css({
        "background-color": "rgba(250,82,82,0.2)"
      });
      return "<i style='font-size:1.2rem' class='red flaticon-uterus'></i>";
    } else if (cellValue == "ENT") {
      cell.getRow().getElement().css({
        "background-color": "rgba(250,82,82,0.2)"
      });
      return "<i style='font-size:1.125rem' class='red flaticon-ear'></i>";
    } else if (cellValue == "Urology") {
      cell.getRow().getElement().css({
        "background-color": "rgba(250,82,82,0.2)"
      });
      return "<i style='font-size:1.125rem' class='red flaticon-kidneys'></i>";
    } else if (cellValue == "Respiratory") {
      cell.getRow().getElement().css({
        "background-color": "transparent"
      });
      return "<i style='font-size:1.125rem' class='red flaticon-lungs'></i>";
    } else if (cellValue == "Frailty") {
      cell.getRow().getElement().css({
        "background-color": "rgba(105, 219, 124, 0.2)"
      });
      return "<i class='green flaticon-frame'></i>";
    } else if (cellValue == "Orthopaedics") {
      cell.getRow().getElement().css({
        "background-color": "rgba(250,82,82,0.2)"
      });
      return "<i style='font-size:1.2rem;' class='red flaticon-bone'></i>";
    } else if (cellValue == "Cardiology") {
      cell.getRow().getElement().css({
        "background-color": "rgba(250,82,82,0.2)"
      });
      return "<i class='red fa fa-heartbeat'></i>";
    } else if (cellValue == "Haematology") {
      cell.getRow().getElement().css({
        "background-color": "transparent"
      });
      return "<i class='red flaticon-blood'></i>";
    } else if (cellValue == "Gastroenterology") {
      cell.getRow().getElement().css({
        "background-color": "transparent"
      });
      return "<i style='font-size:1.125rem' class='red flaticon-stomach'></i>";
    } else if (cellValue == "Oncology") {
      cell.getRow().getElement().css({
        "background-color": "transparent"
      });
      return "<i style='font-size:1.125rem' class='red flaticon-cancer'></i>";
    } else if (cellValue == "OPAT") {
      cell.getRow().getElement().css({
        "background-color": "rgba(121, 80, 242, 0.2)"
      });
      return "<i style='color:rgba(121,80,242,1)' class='flaticon-bug'></i>";
    } else if (cellValue == "DALT") {
      cell.getRow().getElement().css({
        "background-color": "transparent"
      });
      return "<i class='red fa fa-glass-martini'></i>";
    } else if (cellValue == "Stroke") {
      cell.getRow().getElement().css({
        "background-color": "transparent"
      });
      return "<i style='font-size:1.125rem' class='red fa fa-bolt'></i>";
    } else {
      cell.getRow().getElement().css({
        "background-color": "transparent"
      });
      return cellValue;
    }
  }
  var sortString = function(a, b, aRow, bRow, column, dir, sorterParams) {
    if (dir == "asc") {
      if (a === "") return 1;
      if (b === "") return -1;
      return ((a < b) ? -1 : ((a > b) ? 1 : 0));
    } else if (dir == "desc") {
      if (a === "")
        return -1;
      if (b === "")
        return 1;
      return ((a < b) ? -1 : ((a > b) ? 1 : 0));
    }
  };
  var timeElapsed = function(value, data, type, mutatorParams) {
    var timeCol = data.time;
    var startTime = moment(timeCol, "HH mm");
    var currentTime = moment();
    var elapsedTime = currentTime.diff(startTime, 'minutes');
    if (timeCol === "") {
      return ""
    } else {
      return elapsedTime
    }
  }

  var formatLOS = function(cell, formatterParams) {
    var cellValue = cell.getValue();
    var elapsedCol = cell.getData().elapsed
    if (elapsedCol === "") {
      return ""
    } else if ((elapsedCol > 119) && (elapsedCol < 240)) {
      cell.getElement().css('color', '#fcc419');
      return cellValue;
    } else if (elapsedCol > 239) {
      cell.getElement().css('color', '#fa5252');
      return cellValue;
    } else {
      return cellValue
    }
  }

  var mutateLOS = function(value, data, type, mutatorParams) {
    var elapsedTime = data.elapsed;
    var los = moment.duration(elapsedTime, "minutes").format("d[d] h[h] m[m]");
    if (elapsedTime === "") {
      return ""
    } else {
      return los
    }
  }


  var deleteIcon = function(cell, formatterParams) {
    return "<i class='red fal fa-minus-circle'></i>";
  };

  function saveData() {
    var data = $("#aec-whiteboard").tabulator("getData");
    localStorage.setItem("tabulator-data", JSON.stringify(data));
  }

  function statusUpdate() {
    var patientFU = $('[tabulator-field="type"]:contains("F/U")').length;
    var patientNew = $('.tabulator-row').length - patientFU;
    $('#patientNew').text(patientNew);
    $('#patientFU').text(patientFU);
  }

  function sortByBed() {
    $("#aec-whiteboard").tabulator("setSort", "elapsed", "desc");
  }

  function checkDuplicates() {
    var index = {},
      getText = function() {
        return $.trim($(this).text().split(', ')[0]);
      };
    $("#aec-whiteboard").find(".tabulator-row").each(function() {
      var rowKey = $(this).find('.tabulator-cell[tabulator-field="name"]').map(getText).toArray().join("|");
      if (index.hasOwnProperty(rowKey)) {
        index[rowKey].push(this);
      } else {
        index[rowKey] = [this];
      }
    });
    $.each(index, function(rowKey, rows) {
      $(rows).toggleClass("duplicate", rows.length > 1);
    });
  }
  var ajaxSet = {
    type: "POST",
    complete: function() {
      statusUpdate();
      checkDuplicates();
    }
  };
  var timeOut;
  var lastUpdated = moment();
  var updateTable = function() {
    $.ajax({
      url: "php/aec-fetch.php",
      type: "POST",
      async: true,
      dataType: 'json',
      success: function(data) {
        $("#aec-whiteboard").tabulator("setData", data);
        lastUpdated = moment();
      },
      complete: function() {
        statusUpdate();
        checkDuplicates();
        sortByBed();
        timeOut = setTimeout(updateTable, 20000);
      }
    });
  }
  timeOut = setTimeout(updateTable, 20000);

  var updateOnce = function() {
    $.ajax({
      url: "php/aec-fetch.php",
      type: "POST",
      async: true,
      dataType: 'json',
      success: function(data) {
        $("#aec-whiteboard").tabulator("updateOrAddData", data);
      },
      complete: function() {
        statusUpdate();
        checkDuplicates();
        sortByBed();
      }
    });
  }


  var updateTime = function() {
    var timeAgo = moment().diff(lastUpdated, 'seconds');
    var timeElapsed = moment.duration(timeAgo, 'seconds').format("d[d] h[h] m[m] s[s]");
    $('#lastUpdated').html(timeElapsed);
    setTimeout(updateTime, 1000);
  };
  updateTime();
```

**Comment by olifolkerd** [comment]
Hey @tomheaps 

I cant seem to replicate the issue.

You seem to be using a custom table style in your example, could you try your table on a plain HTML page, using one of the default Tabulator style-sheets, just to check that it is not an interaction with other code?

Cheers

Oli :)

**Comment by tomheaps** [comment]
Hey @olifolkerd, this issue seems to have been fixed after updating to v3.4 - not sure what was going on!

BTW really loving the new release, thanks for sorting the memory bloat issue with setData!

**Comment by olifolkerd** [comment]
@tomheaps 

Very glad to hear that, was worried it might crop up again.

Great to hear you are enjoying the new release, was good to finally get it out after so long. Turns out the memory issue was because the DOM elements and their bindings wern't being destroyed properly so just kept on building up thousands of them in memory. Ive got a few more optimisations in mind for 3.5

Ive already started planning a load of features for 3.5, and im hoping to get it out much faster than the last release.

Let me know if there are any features that would be useful for you.

Cheers

Oli :)

**Comment by Liam-OShea** [comment]
I also encountered this issue on v4.9.

I resolved the issue by left aligning the contents of the affected cells (originally centre aligned). It may have something to do with a customized autocomplete module we are using.

`  .tabulator-cell {
      &[tabulator-field='myFieldName'] {
      text-align: left;
      }
    }`
    
   I hope this helps anyone with the same issue.
