### ISSUE TITLE
Editing Stylesheet (CSS) Files

### ISSUE THREAD

**Issue by xXmrotsXx** [olifolkerd/tabulator#864]
I'm sorry, I feel this is a very basic question but after searching far and wide I am unable to find an answer - I'm missing something that is right in front of me I'm sure if it.

Basing my question on the "Quick Start" Example, I am seeing the table with no errors in the Chrome console etc (Woohoo!), however my formatting does not match the example output table - my font is all Times New Roman, for example.

I thought I could just edit the stylesheet (tabulator.min.css) but this opens on one line with no indents and is very hard to read using notepad++. Nevertheless, I found the font-family and changed "inherit" to "arial" with no luck.

Any help on this specific problem, or more importantly going forward making more significant changes to the stylesheet while displayed in a readable format would be great.

Thanks so much in advance.

**Comment by xXmrotsXx** [comment]
UPDATE: 
The tabulator_site.css file is formatted nicely in a readable way, unlike the tabulator.min.css file... When switching to this stylesheet and adding `font-family: arial;` to the .tabulator class, the change carries though to my table correctly.

I've since read that changing the CSS file directly may not be a good idea and I should change the SCSS file. Is this the case? When is the CSS file overwritten by the SCSS if it hasn't been updated?

Why is there no tabulator.min.scss file?

**Comment by olifolkerd** [comment]
Hey @xXmrotsXx 

Minified CSS files are programtically generated by gulp, they are designed to have the smallest number of characters possible to allow for faster transfer over the internet and are not supposed to be human readable.

Here is an [article](https://developers.google.com/speed/docs/insights/MinifyResources) that explains minifiication.

Tabulator simply uses the font styling of the site that it is included in (which in most browsers will default to a serif font like times new roman), doing this makes it easier for the table to fit in with the style of any site it is included with.

I would suggest that as with most sites you have another css file to deal with your site styling and include your site font in that.

As a side note, SCSS files cannot be read by the browser, sass is a pre-processor language that must be complied to CSS by a task automation tool like gulp, in the [Extension Documentation](http://tabulator.info/docs/3.3#extending) there are instructions on how to use this to create your own custom tabulator build. But if you are just tweaking the styles, i would recommend just using a second stylesheet and overriding Tabulators inbuilt styling using the classes applied to each element of the table, a list of which can be found in the [Theming Documentation](http://tabulator.info/docs/3.3#css)

Cheers

Oli

**Comment by xXmrotsXx** [comment]
Thanks so much for your detailed reply.


-------- Original message --------
