### ISSUE TITLE
cellClick and cellDblClick in the same Cell does not work

### ISSUE THREAD

**Issue by kurtknippschild** [olifolkerd/tabulator#865]
Hi Oli,

I have a column with cellClick and cellDblClick but only cellClick works.
I need two function of the same cell.
What can I do?

Thanks in advance. Kurt

**Comment by olifolkerd** [comment]
Hey @kurtknippschild 

Could you post a copy of your code?

Cheers

Oli

**Comment by kurtknippschild** [comment]
Hi Oli,

here is my Code:
[cellClickCellDblClick.txt](https://github.com/olifolkerd/tabulator/files/1706752/cellClickCellDblClick.txt)

Thanks in advance Kurt

**Comment by olifolkerd** [comment]
Hey @kurtknippschild 

I cant seem to replicate your issue, to start with i would suggest just trying a simple click and double click binding that dumps to the console log just to identify if your are getting both triggered properly:
```js
{title:"Birthday", field:"dob", cellDblClick:function(){console.log("dbl")}, cellClick:function(){console.log("click")}},
```

you should see the click binding fire twice and the double click binding fire once.

Cheers

Oli
