### ISSUE TITLE
Saving Table Data

### ISSUE THREAD

**Issue by jordie324** [olifolkerd/tabulator#866]
Hi Oli,

I'm trying to build an editable table that retains the data entered. It works for everything except a column with a custom editor used to select months from a dropdown. Each time I add a new row or column or refresh the page, the month selection from other rows deletes.

Any ideas?

Thanks,
Jordan

**Comment by olifolkerd** [comment]
Hey Jordan,

Could you post your code or a link to an example of your current setup.

Cheers

Oli :)

**Comment by jordie324** [comment]
`<script>
	var monthEditor = () => {
	  var editor = $("<select><option value=''></option><option value='January'>January</option><option value='February'>February</option><option value='March'>March</option><option value='April'>April</option><option value='May'>May</option><option value='June'>June</option><option value='July'>July</option><option value='August'>August</option><option value='September'>September</option><option value='October'>October</option><option value='November'>November</option><option value='December'>December</option></select>");
	  return editor;
	  }; //dropdown options for Month column
	  
	$("#SpendingTable").tabulator({ //the table, duh
	placeholder:"No Data Available", // for empty table
	layout:"fitData", // fit the columns to the view
	history:true, // remember history for undo and redo
	addRowPos:"top", // add new rows to the top of the table
	pagination:"local",
	paginationSize:12,
	movableColumns:true,
	initialSort:[
		{column:"Year", dir:"desc"},
		{column:"Month", dir:"desc"}
	],
	columns:[
    	{title:"Year", field:"Year", sorter:"number", editor:"number", validator:"min:1900"},
		{title:"Month", field:"Month", sorter:"string", editor:monthEditor},
        {title:"Income", field:"Income", sorter:"number", editor:"number", formatter:"money", formatterParams:{symbol:"$"}, bottomCalc:"sum",  bottomCalcFormatter:"money", bottomCalcFormatterParams:{symbol:"$"}, topCalc:"avg", topCalcFormatter:"money", topCalcFormatterParams:{symbol:"$"}},
		{title:"Giving", field:"Giving", sorter:"number", editor:"number", formatter:"money", formatterParams:{symbol:"$"}, bottomCalc:"sum",  bottomCalcFormatter:"money", bottomCalcFormatterParams:{symbol:"$"}, topCalc:"avg", topCalcFormatter:"money", topCalcFormatterParams:{symbol:"$"}},
		{title:"Savings", field:"Savings", sorter:"number", editor:"number", formatter:"money", formatterParams:{symbol:"$"}, bottomCalc:"sum",  bottomCalcFormatter:"money", bottomCalcFormatterParams:{symbol:"$"}, topCalc:"avg", topCalcFormatter:"money", topCalcFormatterParams:{symbol:"$"}},
		{title:"Rent/Mortgage", field:"RentMortgage", sorter:"number", editor:"number", formatter:"money", formatterParams:{symbol:"$"}, bottomCalc:"sum",  bottomCalcFormatter:"money", bottomCalcFormatterParams:{symbol:"$"}, topCalc:"avg", topCalcFormatter:"money", topCalcFormatterParams:{symbol:"$"}},
		{title:"Water", field:"Water", sorter:"number", editor:"number", formatter:"money", formatterParams:{symbol:"$"}, bottomCalc:"sum",  bottomCalcFormatter:"money", bottomCalcFormatterParams:{symbol:"$"}, topCalc:"avg", topCalcFormatter:"money", topCalcFormatterParams:{symbol:"$"}},
		{title:"Natural Gas", field:"NaturalGas", sorter:"number", editor:"number", formatter:"money", formatterParams:{symbol:"$"}, bottomCalc:"sum",  bottomCalcFormatter:"money", bottomCalcFormatterParams:{symbol:"$"}, topCalc:"avg", topCalcFormatter:"money", topCalcFormatterParams:{symbol:"$"}},
		{title:"Electricity", field:"Electricity", sorter:"number", editor:"number", formatter:"money", formatterParams:{symbol:"$"}, bottomCalc:"sum",  bottomCalcFormatter:"money", bottomCalcFormatterParams:{symbol:"$"}, topCalc:"avg", topCalcFormatter:"money", topCalcFormatterParams:{symbol:"$"}},
		{title:"Phone", field:"Phone", sorter:"number", editor:"number", formatter:"money", formatterParams:{symbol:"$"}, bottomCalc:"sum",  bottomCalcFormatter:"money", bottomCalcFormatterParams:{symbol:"$"}, topCalc:"avg", topCalcFormatter:"money", topCalcFormatterParams:{symbol:"$"}},
		{title:"Internet", field:"Internet", sorter:"number", editor:"number", formatter:"money", formatterParams:{symbol:"$"}, bottomCalc:"sum",  bottomCalcFormatter:"money", bottomCalcFormatterParams:{symbol:"$"}, topCalc:"avg", topCalcFormatter:"money", topCalcFormatterParams:{symbol:"$"}},
		{title:"Gas", field:"Gas", sorter:"number", editor:"number", formatter:"money", formatterParams:{symbol:"$"}, bottomCalc:"sum",  bottomCalcFormatter:"money", bottomCalcFormatterParams:{symbol:"$"}, topCalc:"avg", topCalcFormatter:"money", topCalcFormatterParams:{symbol:"$"}},
		{title:"Food", field:"Food", sorter:"number", editor:"number", formatter:"money", formatterParams:{symbol:"$"}, bottomCalc:"sum",  bottomCalcFormatter:"money", bottomCalcFormatterParams:{symbol:"$"}, topCalc:"avg", topCalcFormatter:"money", topCalcFormatterParams:{symbol:"$"}},
		{title:"Misc", field:"Misc", sorter:"number", editor:"number", formatter:"money", formatterParams:{symbol:"$"}, bottomCalc:"sum",  bottomCalcFormatter:"money", bottomCalcFormatterParams:{symbol:"$"}, topCalc:"avg", topCalcFormatter:"money", topCalcFormatterParams:{symbol:"$"}},
		{title:"Insurance", field:"Insurance", sorter:"number", editor:"number", formatter:"money", formatterParams:{symbol:"$"}, bottomCalc:"sum",  bottomCalcFormatter:"money", bottomCalcFormatterParams:{symbol:"$"}, topCalc:"avg", topCalcFormatter:"money", topCalcFormatterParams:{symbol:"$"}},
		{title:"Debt", field:"Debt", sorter:"number", editor:"number", formatter:"money", formatterParams:{symbol:"$"}, bottomCalc:"sum",  bottomCalcFormatter:"money", bottomCalcFormatterParams:{symbol:"$"}, topCalc:"avg", topCalcFormatter:"money", topCalcFormatterParams:{symbol:"$"}},
		{title:"Remove", field:"Remove", formatter:"buttonCross", align:"center", cellClick: function(e, cell) {$("#SpendingTable").tabulator("deleteRow", cell.getRow());}}
	],
	dataEdited:function(data){
        //JSON encode data and store in local storage.
        localStorage.setItem("spending-data", JSON.stringify(data));
    },
    });

addRow = () => {$("#SpendingTable").tabulator("addRow");} //function to add row to the table - used with Add Row button

addColumn = () => {$("#SpendingTable").tabulator("addColumn", {
	layout:"fitColumns",
	history:true,
	addRowPos:"top",
	pagination:"local",
	paginationSize:12,
	movableColumns:true,
	sorter:"number",
	editor:"number",
	headerFilter:"input",
	formatter:"money",
	formatterParams:{symbol:"$"},
	bottomCalc:"sum",
	topCalc:"avg",
	editableTitle:true
	});
	} //function to add column to the table - used with Add Column button

downloadSpendCSV = () => {$("#SpendingTable").tabulator("download", "csv", "Spending.csv");} //function to download CSV of table date - used with Download CSV button

$(document).ready(function() {
    //Load any saved data from localStorage
    var data =  localStorage.getItem("spending-data");
    
    //If data is present fill the table with it
    if(data){
        $("#SpendingTable").tabulator("setData", JSON.parse(data));
    }
});
</script>`

**Comment by jordie324** [comment]
[Spending.txt](https://github.com/olifolkerd/tabulator/files/1705111/Spending.txt)

**Comment by olifolkerd** [comment]
Hey @jordie324 

Your month editor is not setup correctly, there are a number of arguments passed into an editor function that let you tell Tabulator when you have chosen a new value, you need to call the ***success*** function that is passed into the editor.

The [Editing Data Documentation](http://tabulator.info/docs/3.3#manipulating-data) contains details of how to setup a custom select editor and the callbacks you need to use.

The [Editable Data Example](http://tabulator.info/examples/3.3#editable) also contains a working copy of the editor.

If you can hold off till tomorrow when version 3.4 is released, it contains a built in select editor to make it easier to work with dropdowns.

Cheers

Oli :)

**Comment by jordie324** [comment]
Thank you!
