### ISSUE TITLE
Reference Calc Data in Another Table

### ISSUE THREAD

**Issue by jordie324** [olifolkerd/tabulator#867]
Hey Oli,

I have another question. Is it possible to combine column calculations and load that data in another table? For example, I want to create a table to log 3 forms of income - one column for each, sum each column, then add those sums together and load them into a single Income column in another table.

Is that possible?

Thanks,
Jordan

**Comment by olifolkerd** [comment]
Hey Jordan,

At the moment those values are not programatically accessible, but i like the idea so i will se if i can get it in the 3.4 release this weekend.

Cheers

Oli :)

**Comment by jordie324** [comment]
That would be AMAZING!

**Comment by olifolkerd** [comment]
Hey,

I have just pushed the code for this to the 3.4 branch which will be released tomorrow, you will be able to call the ***getCalcResults*** function to get the results of the column calculations:

```js
var results = $("#example-table").tabulator("getCalcResults");
```

Cheers

Oli :)

**Comment by jordie324** [comment]
Great, thanks!

**Comment by olifolkerd** [comment]
Tabulator version 3.4 has now been officially release!

You can find details of the new release in the [News Section](http://tabulator.info/news)

Full documentation of all the new features can be found [Here](http://tabulator.info/docs/3.4)

Cheers

Oli :)
