### ISSUE TITLE
Setting height hides horizontal scroll

### ISSUE THREAD

**Issue by msantos82** [olifolkerd/tabulator#87]
Hi!

I've inserted a table in an accordion widget. I had to place it into a div width a fixed height (200px) to avoid double scroll bars (accordion and table) and set the height property of the table to 150px, but when I do this y can't see the entire table. Part of the last row and the horizontal scrollbar are cropped.  If I don't place it inside the div, I can see the entire table but, as I said, double scrollbars. I tried redrawing the table but nothing happened. Any idea?

Thanks

Manuel

**Comment by olifolkerd** [comment]
could you post some example code of the html/css for the element and the Tabulator constructor you are using and i can run a quick test.

Which browser are you using?

**Comment by olifolkerd** [comment]
It is likely because the height of the table changes as the accordion unfolds.

I would recommend calling ***redraw*** on the table once it is at its full height.
```js
$("#example-table").tabulator("redraw");
```
