### ISSUE TITLE
Group usage example

### ISSUE THREAD

**Issue by roypardi** [olifolkerd/tabulator#872]
Hi – this isn't an "issue". I wanted to thank you for this great component and show an example of how I am using the group functionality so you have some feedback for future development.

I don't know if it is your intention that Tabulator work as a kind of "tree" widget or component but that is how I am using (...abusing 😃 ) it.  This kind of evolved because of project changes. Maybe there is another more appropriate component out there I could use. . . but I haven't found it.

--------

<img width="500" alt="screen shot 2018-02-11 at 1 25 19 pm" src="https://user-images.githubusercontent.com/9053196/36076874-821dd1a6-0f30-11e8-8a21-121f7ec6700b.png">

Control-click on group header brings up a context menu. The commands are backed up by functions which manipulate the underlying data – for example, each data object has "groupName" and "groupID" properties. The `groupBy` uses the "groupName". So "rename group" pops up a dialogue for a new and unique group name and then sets that property on all the data objects.

- it would be convenient to be able to specify the display name of a group rather than have it automatically use the `groupBy` parameter.
- my group header can have a `Semantic` checkmark icon which the user can set. A group can also be in a "selected" state. I end up using `setData` and blowing out the entire table since I couldn't figure out a way to target a particular group through the API to change a specific header.
- my data is already organized in "groups" (multi-diminsional array) so I have to flatten it at runtime and add the "groupName" and "groupID" properties mentioned above.

--------
<img width="500" alt="screen shot 2018-02-11 at 1 25 37 pm" src="https://user-images.githubusercontent.com/9053196/36076881-8caecbe8-0f30-11e8-970f-8e3df6bb8781.png">

Each group member has a dropdown menu with various commands to handle moving and copying them between groups (moving rows between groups not yet supported in Tabulator).  The underlying code does what you would expect and there are enough hooks from `cellClicked` to get the data, etc.

None of this is criticism!  Just some feedback on how your component is being used. Perhaps my use of it as a "tree component" is unusual, but as the "group" functionality develops, it seems a natural way folks will use Tabulator. I did see in an earlier something about "if a group has no members it will be deleted". It would offer more flexibility if that were a set-up option (`deleteEmptyGroups: false`) etc.

Anyway – thanks again and feel free to close this rambling 😃

**Comment by olifolkerd** [comment]
Hey @roypardi 

Thanks for sharing how you use the component, It is great to see all the novel ways that Tabulator is used, and you certainly have an interesting take on it

I think you will like the changes coming out in v3.4 later today, the group system has had a massive overhaul and is much more reliable than before.

In response to your points:

- you can use the ***groupHeader*** function to specify a different title for your header if the key isnt what you are after.
- you can use the ***getGroups*** function to get the Group Components for each group, which allow you to manipulate them, you can also access the group a row is in by calling the ***getGroup*** function on the row component *(new in v3.4)*
- a ***setTitle*** function for the group component is on the roadmap for v3.5 in a couple of months time

Keep up the good work!

Cheers

Oli :)
