### ISSUE TITLE
formatterParams legend question (3.4)

### ISSUE THREAD

**Issue by YendorMc** [olifolkerd/tabulator#876]
Hi Oli,

Noodling around with 3.4 and the new legend formatterParms.

I'm trying to get something like the following:
http://jsfiddle.net/kedctfmj/5/

Simply, I just tried this:
{title:"Data", field:"data", align:"center", width:100,headerSort:false,formatter:"progress",formatterParams:{legend:true}},

But I'm still seeing bar graphs with no overlay text.

Can you help me understand what I'm missing?

Also, would formatterParams accept an array of values?
as in: 
formatterParams:{[color:"red"],[legend:true]}

Many thanks!

**Comment by olifolkerd** [comment]
Hey @YendorMc 

You pass an object to ***formatterParams*** so for multiple values it would be `formatterParams:{color:"red", legend:true}`


Your above code should be working, i just ran a test with it on chrome, firefox and ie and it worked on all three. are you storing a number in the field?

Are you sure you are running on the 3.4 version of the Tabulator source?

Cheers

Oli :)

**Comment by YendorMc** [comment]
Thanks for th quick responses!   Yes. A number is in the field - is that an issue?

I downloaded from the home page... it says 3.3 but the source show 3.4.  So I thought it would be okay. I’ll d/l from git to make sure.

**Comment by olifolkerd** [comment]
Hey @YendorMc 

No it isnt a problem, a number is the expected type of value.

The v3.3 on the home page was my bad, i forgot to update the button, it will have downloaded 3.4,  i have just fixed that now.

If you are using a site that was previously running 3.3 you may need to force refresh your browser a couple of times to flush out any previously cached versions

Which browser are you using?

If you are still having problems, can you post a copy of your table constructor and a line of sample data so i can run a more detailed test.

Cheers

Oli

**Comment by YendorMc** [comment]
Darn it!  Even though I updated I was looking at a different folder (e.g. using 3.3).

This is pretty sexy, Oli!  Please consider closed!

For those interested here's a pic of the code below...

![image](https://user-images.githubusercontent.com/10876357/36139464-9ddb1b06-106b-11e8-85c9-0baf4ccf682b.png)


`<html>
<head>

	<meta content="text/html;charset=utf-8" http-equiv="Content-Type">
	
<title>TEST</title>
<script type="text/javascript" src="../vendor/jquery-3.2.1.min.js"></script>
<script type="text/javascript" src="../vendor/jquery-ui.min.js"></script>
<script type="text/javascript" src="../vendor/xlsx.full.min.js"></script>
<script type="text/javascript" src="tabulator-master/tabulator-master/dist/js/tabulator.min.js"></script>
<link href="tabulator-master/tabulator-master/dist/css/tabulator.min.css" rel="stylesheet"> 

<head>
<body>
<h1>Hi there!</h1>
<div id="example-table"></div>
<script type="text/javascript" >
var jsondata = [
				{data: 123},
				{data: 235},
				{data: 135},
				{data: 56},
				{data: 3}
				];
console.log (jsondata);
$("#example-table").tabulator({
		height:600, // set height of table, this enables the Virtual DOM and improves render speed dramatically (can be any valid css height value)
		columnVertAlign:"bottom", //align header contents to bottom of cell
		columns: [
		{title:"data", field:"data", align:"center", width:100,headerSort:false,formatter:"progress",formatterParams:{max: 300, legend:true}}
		//{title:"data", field:"data", align:"center", width:100,headerSort:false}
		]
	});

	

///Tabulator
	
//load sample data into the table
$("#example-table").tabulator("setData", jsondata);
</script>
</body>
</html>`
