### ISSUE TITLE
Bug with "scrollToRow" in 3.4

### ISSUE THREAD

**Issue by mikeshow** [olifolkerd/tabulator#877]
Hi Oli,

In scroll mode, no pagination.
If I do something like:

`$("#thetable").tabulator("scrollToRow", 30);`

The first row displayed is the row after 30. All the rows before are missing. If I scroll down I have a bunch of blank lines.

Tested on Firefox 58.0.2 - Chrome 64.0.xxx

**Comment by olifolkerd** [comment]
Hey Mike,

You found a bug there, i have just released version 3.4.1 with a patch for that.

Thanks for letting me know.

Cheers

Oli :)

**Comment by mikeshow** [comment]
Hi Oli,

If I do that (3.4.1):

`$("#thetable").tabulator("scrollToRow", 30);`

It works now. It goes to the line with the id=30.

Now the question is: what about `row.getPosition()`?
It returns the row position but I don't see a function 'scrollToPosition'.

**Comment by olifolkerd** [comment]
Hey @mikeshow 

There is no need to get the row position to scroll to it, you can pass the entire row object into the ***scrollTo*** function and it will scroll there:
```js
$("#thetable").tabulator("scrollToRow", row);
```

Cheers

Oli :)

**Comment by mikeshow** [comment]
Hey Oli,

Ok I get it. With getPosition() I get the position, and with getRowFromPosition() I get the row.

Cheers.

Mike.

**Comment by olifolkerd** [comment]
Hey Mike,

You don't even need to use get position, you can call the ***scrollTo*** function on the row component you are calling getPosition on.

For example if you wanted to scroll to a row when it is added to the table:
```js
$("#example-table").tabulator({
    columns:[...],
     rowAdded:function(row){
        //row - row component
        row.scrollTo();
    }
});
```

Or you could pass that component to the tables ***scrollTo*** function:
```js
$("#example-table").tabulator({
    columns:[...],
     rowAdded:function(row){
        //row - row component
        $("#example-table").tabulator("scrollTo", row);
    }
});
```

There a loads of functions you can call on [Row Components](http://tabulator.info/docs/3.4#component-row), and anywhere you pass in the index of a row to a function, you can also pass in the row component or a jQuery wrapped SOM element of the row. They can be used all over the place.

Cheers

Oli :)

**Comment by mikeshow** [comment]
ok, that's interesting. Thanks.
