### ISSUE TITLE
Handling Multiple Formatters Question (3.4)

### ISSUE THREAD

**Issue by YendorMc** [olifolkerd/tabulator#878]
Ok, you got me all excited now with the legend

Is it possible to handle multiple formatters without a specialized function?

For example I would like a **progress bar** with a **legend** that has a html **link** to take me to the details of the counts.  

Taking a SWAG, I tried this:

'''{title:"data", field:"data", align:"center", width:100,headerSort:false,formatter:["progress", "link"],formatterParams:{max: 300, legend:true, url:"www.google.com"}}
'''
Which didn't work.

**Comment by olifolkerd** [comment]
Hey @YendorMc 

That is an interesting idea you have there, sadly that is not an option in Tabulator at the moment.

You could get round it be building your own custom formatter. if you have a look at the `/src/js/extensions/format.js` file you will be able to get the source for the progress formatter and use that to make your own one with hyperlink lookup.

I hope that helps.

Cheers

Oli :)
