### ISSUE TITLE
After deleting a column, getData returns incorrect data

### ISSUE THREAD

**Issue by ilutin** [olifolkerd/tabulator#879]
**Hey!**
1. How to return data from the table to the current moment? For example, after deleting a column, the GetData returns also the data that was stored in this column.
2. How to change the column name so that the new name is returned in getData

**Comment by olifolkerd** [comment]
Hey @ilutin 

Thanks for getting in touch,

Deleting the column only removes it visually it dosn't affect the row data at all. so you would need to do that yourself after you have retrieved the data.

You cant alter the field name of the data in tabulator, you would need to do that after you have received the data.

Cheers

Oli :)

**Comment by ilutin** [comment]
Thanks @olifolkerd
