### ISSUE TITLE
Who am I in the RowClick event?

### ISSUE THREAD

**Issue by codevite** [olifolkerd/tabulator#88]
I'm adding a rowClick event. But How can I read my id inside this event?
```
.tabulator({
rowClick:function(e, id, data, row){
//Once here how get my id?
}
}); 
```

**Comment by olifolkerd** [comment]
Do you mean the index of the row that was clicked? if so it is passed in as an argument to the function as the ***id*** argument. alternatively all ro data is passed in as the ***data*** object..

If you are looking for the row DOM element then this is passed in as a jQuery object to the ***row*** argument

**Comment by codevite** [comment]
I would like to the Tabulator Id attr inside the rowClick.

**Comment by olifolkerd** [comment]
in that case:

```js
$("#example-table").tabulator({
    rowClick:function(e, id, data, row){
      var tableID = row.closest(".tabulator").attr("id");
    }
}); 
```

**Comment by codevite** [comment]
That was what I needed.
Thank you.
