### ISSUE TITLE
Filter data fields not shown

### ISSUE THREAD

**Issue by florosx** [olifolkerd/tabulator#882]
Hello, 
I am trying to use tabulator to show some json data I have for a research database project.
The problem is that using the sample code from the "Filter data" section I get no filter buttons/input above my table. The header filters work fine.
I also removed the customFilter but didn't solve the issue.
Any ideas of what could be going wrong?

Thanks a lot,
Xenofon

**Comment by olifolkerd** [comment]
Hey @florosx 

The only inbuilt filter elements that tabulator has are the header filters. The other filter functions can be called programatically by your won code, so you would need to create your own input element and then bind it to a filter.

Tabulator works this way to give developers more control on how they want to display filters, rather than making arbitrary choices for you.

So for example
**HTML**
```html
<input id="filter-name"></input>
<div id="example-table"></div>
```
**JavaScript**
```js
//define table
$("#example-table").tabulator({
    columns:[
        {title:"Name", field:"name"},
    ]
});

//bind input change event to filter function
$("#filter-name").change(function(e){
    $("#example-table").tabulator("setFilter", "like", $(this).val());
});
```

I hope that helps,

Cheers

Oli :)

**Comment by florosx** [comment]
Hi Uli,
I am really grateful for your kind, fast and detailed response. Retrospectively my question seems a bit stupid, but i m just a data scientist that promised a website to a friend. Thanks again for all the help !

**Comment by florosx** [comment]
Can I just ask one last thing regarding filtering?
I am trying now to get a global search running, so I am using the "like" type but I cannot see how to combine the searches across different columns.  Is that possible?

Could you also point me to any direction to implement a slider to filter out the entries of the table? I found this https://stackoverflow.com/questions/27841464/jquery-slider-range-apply-range-as-a-filter-on-table-rows
but I suppose it will interact with your table generation routines..

**Comment by olifolkerd** [comment]
Hey @florosx 

No problem, ask as many questions as you need to.

There is no inbuilt filter for that so you would have to create a filter function instead:

```js
//create custom filter function
function customFilter(data, filterParams){
    //data - the data for the row being filtered
    //filterParams - params object passed to the filter

    var fields = filterParams.fields || []; //fields to check against
    var value = filterParams.value || ""; //value to filter for
    var match = false; //if match is found or not

    fields.forEach(function(field){
    	if(data[field].toLowerCase().indexOf(filterVal.toLowerCase()) > -1){
    	    	match = true;
    	}
    });

    return match;
}


//apply filter function with value to search for
$("#example-table").tabulator("setFilter", customFilter, {fields:["firstname", "surname"], value:"bob"});
```
If you want a range slider i would suggest something like the [jQuery slider](http://jqueryui.com/slider/#range) which you can watch for a change event on and update the filter just like you would with an input.

Let me know if that helps.

Cheers

Oli :)
