### ISSUE TITLE
Pagination not working neither in manual or auto mode

### ISSUE THREAD

**Issue by florosx** [olifolkerd/tabulator#883]
Apparently I cannot make the pagination option work, neither by setting the height of the tabulator or by specifying the options below. Any ideas? Thanks a lot !!

    $("#example-table").tabulator({
        pagination:"local",
        paginationSize:5,
        columnVertAlign:"bottom", //align header contents to bottom of cell
        ajaxURL:"http://localhost:8888/data/testIndustrialCases2.json",
        columns:[
            {formatter:"rownum", align:"center", width:40},
            {title:"Name", field:"Name", sorter:"string", width:200},
            {title:"Country", field:"Country", sorter:"string", width:100, editor:"select", editorParams:{"Netherlands":"Netherlands", "Greece":"Greece"},
                headerFilter:true, headerFilterParams:{"Netherlands":"Netherlands", "Greece":"Greece"}},
            {title:"Address", field:"Address", sorter:"string", formatter:"textarea", width:150},
            {//create column group
              title: "Architects",
              columns:[
                {title:"Original", field:"Architect (original)", width:150, sorter:"string"},
                {title:"Re-use", field:"Architect (re-use)", formatter:"textarea", width:150, sorter:"string"},
              ],
            },
            {title:"Construction <br> year", field:"Construction year", width:100, sorter:"string"},
            {title:"Former use", field:"Former Use", width:100, sorter:"string"},
            {title:"Re-use <br> year", field:"Re-use year", width:100, sorter:"string"},
            {title:"New use", field:"New use", width:100, sorter:"string"},
        ],

    });

**Comment by olifolkerd** [comment]
Hey @florosx 

That is quite an unusual combination you are using there, most people would use local pagination with local data, or remote pagination with remote data.

In local pagination mode Tabulator does not check for an ajaxURL on load, however i definitely think it should and i have just pushed an update to the master branch to correct this, it will be included in this weekends patch up date.

In the mean time you can get round this by calling the ***setData*** function after you have created the table which will force it to load from the ajaxUrl:

```js
$("#example-table").tabulator("setData");
```

I hope that helps.

Cheers

Oli :)

**Comment by florosx** [comment]
Oli, once again thanks for all the help. Keep up your great work !
