### ISSUE TITLE
component argument in history callbacks is not an instance of Component

### ISSUE THREAD

**Issue by pallxk** [olifolkerd/tabulator#884]
I'm running Tabulator 3.4.1. In the history callback I have to run `component.getComponent()` to get what I want..

Not sure if this should be fixed in doc or code.

Here is a clip of my code on how I'm using history functionality:

```
  cellEdited = cell => {
    // cell.getField() is only available on CellComponent, not Cell
    const field = cell.getField();

    // .....

    // Reformat row so that custom tooltips get updated
    cell.getRow().reformat();
  }

  historyUndo = (action, component, data) => {
    if (action === 'cellEdit') {
      this.cellEdited(component.getComponent());
    }
  }
```

In the case of `cellEdited`, `cell` argument is actually an instance of `CellComponent`, while in the case of `historyUndo` with `action === 'cellEdit'`, `component` is actually an instance of `Cell`.

I was writing those method signatures following the doc.

---

By the way, the history action name rowMove**d** seems not consistent with cellEdit, rowAdd & rowDelete.

Tabulator is a great library though, thanks!

**Comment by olifolkerd** [comment]
Hey @pallxk 

Thanks for the feedback, you are correct, the only publicly exposed objects should be components, i will look at fixing that in this weekends patch release.

Good spot on the getComponent method, that is what Tabulator uses internal to build the component objects, as you have clearly figured out for yourself.

Ah yes i see what you mean about "rowMoved", ive gone all past tense there, i will look at rectifying that in the patch release as well.

Thanks for the feedback, keep it coming!

Cheers

Oli :)

**Comment by olifolkerd** [comment]
I have just pushed a fix for both of these to the master branch, i will update the documentation on the ***rowMove*** action when the patch release is published on the weekend.

Cheers

Oli :)
