### ISSUE TITLE
Date Range Filter and element ID for header filter

### ISSUE THREAD

**Issue by git265** [olifolkerd/tabulator#886]
Hi Oli,

Could you please let me know if there is any date range filter on the table? User should be able to input start and end date . 

And also is it possible for you to add the element id for the columns in the header filter bar. This will be useful for automated testing. With ID, i can use the xpath to verify the header name and input the data if i want to filter the data.

Thanks,
Praveen

**Comment by olifolkerd** [comment]
Hey @git265 

There is no date range filter built in but you could easily add your own using a [Custom Filter Function](http://tabulator.info/docs/3.4#filtering) and moment.js

I dont use  element ***id*** attribute anywhere in Tabulator, because it would likely create duplicate id's if multiple tables are used on the same page *(as you can only have one of the same id on the same page as im sure you know)*.

That being said there is a ***tabulator-field*** attribute set on all cells containing the field they are linked to, I have just pushed an update to the master branch to add this to the column headers as well, which will be included in this weekends patch release.

Cheers

Oli :)

**Comment by git265** [comment]
![image](https://user-images.githubusercontent.com/4753090/36341828-49951bc8-13c2-11e8-97f3-5ed0341d6437.png)


Hi Oli,

I have a table that contains more than million rows in the database, and i want to show only top 2000 records. Once the grid is shown , user would explicitly  filter by multiple inputs and that should be passed to server and fetch the new data asynchronously.  Could you please help me on how to achieve this.?

**Comment by olifolkerd** [comment]
Hey @git265 

Im afraid that is not the point of the header filters, they are designed to provide real time filtering of the data in the columns.

This is not a feature i would be looking to include in Tabulator as the ***setFilter*** function provides a much more flexible way to provide users with custom filter forms.

Cheers

Oli :)

**Comment by Projo94** [comment]
Hello Oli,

I have similar question.

(https://user-images.githubusercontent.com/36087151/59918973-81de2c00-9426-11e9-8a7f-ca4c4d49979a.png)

As you can see, I need to filter column **Event StartTime**, which means to make date range( from date - to date), but I can't workaround this. 

Here it is my code:

<!DOCTYPE html>
<html lang="en">
<title>Roaming Record History Report</title>
<head>

 <link href="/home/marko//dist/css/bulma/tabulator_bulma.min.css" rel="stylesheet">
 <script type="text/javascript" src="https://unpkg.com/tabulator-tables@4.1.2/dist/js/tabulator.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.5/jspdf.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/2.3.2/jspdf.plugin.autotable.js"></script>
<script type="text/javascript" src="http://oss.sheetjs.com/js-xlsx/xlsx.full.min.js"></script>

</head>
<body>
<h1 style="background-color:LightBlue;">WMobile</h1>
<p>
<h1 style="background-color:LightSkyBlue;">Roaming Record History Report</h1>
<p>
<h2 style="background-color:LightGrey;" id="title">Asset Id</h2>
<p>
<p>
<p>
<div class="table-controls-legend" style="color:red;margin-left:10px">Download Controls</div>

<div class="table-controls">
<button id="download-csv" style="color:grey">Download CSV</button>
<button id="download-json" style="color:grey">Download JSON</button>
<button id="download-xlsx" style="color:grey">Download XLSX</button>
<button id="download-pdf" style="color:grey">Download PDF</button>
</div>

<div id="example-table"></div>
<p>
<p>

<script type="text/javascript">
/** no jquery here  **/
/****** some essential functions for our data - called further down ******/

        function loadJSONCall(callback) {   

    		var xobj = new XMLHttpRequest();
        	xobj.overrideMimeType("application/json");
    		xobj.open('GET', './resultsCall.json', false); // Replace 'my_data' with the path to your file
    		xobj.onreadystatechange = function () {
          		if (xobj.readyState == 4 && xobj.status == "200") {
            		// Required use of an anonymous callback as .open will NOT return a value but simply returns undefined in asynchronous mode
					callback(xobj.responseText);
					
          		}
    		};
    		xobj.send(null);  
	 }
	 

	 function loadJSONSMS(callback) {   

		var xobj = new XMLHttpRequest();
		xobj.overrideMimeType("application/json");
		xobj.open('GET', './resultsSMS.json', false); // Replace 'my_data' with the path to your file
		xobj.onreadystatechange = function () {
			if (xobj.readyState == 4 && xobj.status == "200") {
				// Required use of an anonymous callback as .open will NOT return a value but simply returns undefined in asynchronous mode
				callback(xobj.responseText);
			
			}
		};
		xobj.send(null);
	}


	function loadJSONData(callback) {

		var xobj = new XMLHttpRequest();
		xobj.overrideMimeType("application/json");
		xobj.open('GET', './resultsData.json', false); // Replace 'my_data' with the path to your file
		xobj.onreadystatechange = function () {
			if (xobj.readyState == 4 && xobj.status == "200") {
				// Required use of an anonymous callback as .open will NOT return a value but simply returns undefined in asynchronous mode
				callback(xobj.responseText);
				
			}
		};
		xobj.send(null);
	}

        // alternative method - but not needed at this point
        /*
        function XHR(file, callback){
    		var xhr = new XMLHttpRequest();
    		xhr.onreadystatechange = function(){
        		if(xhr.readyState === 4 && xhr.status === 200){
            		callback(xhr.responseText);
        		}
    		}
    		xhr.open('GET', file, true);
    		xhr.send();
	}

        */

       // Need to replace the 'State' numbers, with real status - the structure is below
       // the declared 'changeName' function (earlier) does the replace work and called later on
        var cpState = {  
			REGISTERED: 1,
   			COMPLETED: 2,
    		SETTLED: 3
		      };
        
        function changeName(object) {
	    object.forEach(function(obj) {
        	if (obj.Value.currentState == '1') obj.Value.currentState = 'REGISTERED';
        	if (obj.Value.currentState == '2') obj.Value.currentState = 'COMPLETED';
        	if (obj.Value.currentState == '3') obj.Value.currentState = 'SETTLED';
				if (obj.Value.creator == 'Admin@org1.example.com') obj.Value.creator = 'Alice';
				if (obj.Value.creator == 'User1@org1.example.com') obj.Value.creator = 'Peter';
    	    });
	}





	

/****** end function area ******/

        // need to set tabledata with some sample data, but gets overwritten further down
	var tabledata = [
	    {id:1, name:"Oli Bob", age:"12", col:"red", dob:"12/08/2017"},
	    {id:2, name:"Mary May", age:"1", col:"blue", dob:"14/05/1982"},
	    {id:3, name:"Christine Lobowski", age:"42", col:"green", dob:"22/05/1982"},
	    {id:4, name:"Brendon Philips", age:"125", col:"orange", dob:"01/08/1980"},
		{id:5, name:"Margret Marmajuke", age:"16", col:"yellow", dob:"31/01/1999"},
		{id:6, name:"Margret Marmajuke", age:"16", col:"yellow", dob:"31/01/1999"},
		{id:7, name:"Margret Marmajuke", age:"16", col:"yellow", dob:"31/01/1999"},
		{id:8, name:"Margret Marmajuke", age:"16", col:"yellow", dob:"31/01/1999"},
	    ];

   	var table = new Tabulator("#example-table", {
    	data:tabledata,  /// set the table data
    		    layout:"fitDataFill", //fit columns to width of table (optional)
		    //height:190, // set height of table (optional)
                  //  width:2000,
                    addRowPos:"top",
		    history:true,
		   
			columnVertAlign:"bottom", //align header contents to bottom of cell
			groupBy:"IMSI",
			pagination:"local",
    paginationSize:11,
    paginationSizeSelector:[3, 6, 8, 10],
			//responsiveLayout:"collapse",
		    columns:[ //Define Table Columns
			//{formatter:"responsiveCollapse", width:30, minWidth:30, align:"center", resizable:false, headerSort:false},
		//	{title:"Progress", field:"progress", width:100, sorter:"number", bottomCalc:"avg", bottomCalcParams:{precision:3}},
			{title:"Txn Id", field:"TxId", sorter:"string", formatter:"textarea", width:300, headerFilter:"input", headerFilterPlaceholder:"Find a Person..."},
            {  title:"Personal Info",   align:"center",
				
				columns:  [ {title:"Time Executed", field:"Timestamp", sorter:"string", width:250},
                        {title:"Txn State", field:"Value.currentState", sorter:"string", width:150},
	  		 ]
			   },
						{title:"Invoking ID", field:"Value.creator", sorter:"string", width:150},
						{title:"Type of event", field:"Value.typeofevent", formatter:"money", sorter:"string", width:150},
						{title:"HPLMN", field:"Value.HPLMN", sorter:"string", width:200},
                       	{title:"chargeable units", field:"Value.chargeableunits", formatter:"money", sorter:"string", width:150},
						{title:"IMSI", field:"Value.IMSI",  sorter:"string", width:150},
						{title:"MSISDN", field:"Value.MSISDN", sorter:"string", width:150,headerFilter:"input", headerFilterPlaceholder:"Find a Person..."},
						{title:"Callreference ID", field:"Value.callreferenceID", sorter:"string", width:150},
						{title:"Event Start Time", field:"Value.eventStartTime", sorter:"string", align:"left", width:200},
						{title:"Event Duration", field:"Value.eventduration", sorter:"string", align:"left", width:200},
						{title:"Cause For Term", field:"Value.CauseForTerm", sorter:"string", formatter:"money", align:"left", width:200},
						{title:"Destination", field:"Value.destination", sorter:"string", align:"left", width:200},
							  ],
		    rowClick:function(e, row){ //trigger an alert message when the row is clicked
		    alert("Row " + id + " Clicked!!!!");
			},
			



			
	});

        //load sample data into the table by calling our load function
        var actual_JSONCall="";
        loadJSONCall(function(response) {
    		actual_JSONCall = JSON.parse(response); 
	});

	var actual_JSONSMS="";
	loadJSONSMS(function(response) {
		actual_JSONSMS = JSON.parse(response); 
	}); 
	var actual_JSONData="";
	
	loadJSONData(function(response) {
		actual_JSONData = JSON.parse(response); 
	});
        //function to change the 'state' (paper State) to meaningful statuses for HTML rendering
        changeName(actual_JSONCall);
		changeName(actual_JSONSMS);
		changeName(actual_JSONData);

        table.setData(actual_JSONCall); // this is where the JSON payload is loaded
		table.addData(actual_JSONSMS);
		table.addData(actual_JSONData);
        //console.log("actual JSON element is " + actual_JSON[0]);
        // Set which Asset ID is being reported upon and display it to appropriate element
        var element = document.getElementById("title");
	element.innerHTML = "Asset ID: " + actual_JSONCall[0].Value.key + " "+actual_JSONSMS[0].Value.key +" "+actual_JSONData[0].Value.key ; 
 

//trigger download -- these jquery buttons are not implemented, just placeholder buttons shown for now
	
//$("#download-csv").click(function(){
    //$("#example-table").tabulator("download", "csv", "data.csv");
//});

//trigger download of data.json file
//$("#download-json").click(function(){
    //$("#example-table").tabulator("download", "json", "data.json");
//});

//trigger download of data.xlsx file
//$("#download-xlsx").click(function(){
    //$("#example-table").tabulator("download", "xlsx", "data.xlsx", {sheetName:"My Data"});
//});

//trigger download of data.pdf file
//$("#download-pdf").click(function(){
    //$("#example-table").tabulator("download", "pdf", "data.pdf", {
        //orientation:"portrait", //set page orientation to portrait
//        title:"Example Report", //add title to report 
//});
//});



</script>
</body>
</html>


Do you have any idea how to add filters?
