### ISSUE TITLE
Refresh the Tooltip ? 

### ISSUE THREAD

**Issue by GavinOG** [olifolkerd/tabulator#888]
Hi, 
I have a tooltip that is populated by a function. The tooltip may change over time, but it seems that the call to the tooltip function is only made when the row is created and not everytime that the mouse hovers over the cell/column. Is that correct? Is there a way to force an update to the tooltip? 

Thanks,
Gavin

**Comment by olifolkerd** [comment]
Hey @GavinOG 

Thanks for getting in touch, you are correct Tabulator used to only create the tooltip on render, but i liked your idea so much i have included it in this mornings patch release, as of version 3.4.2 header tooltips are now regenerated when the mouse enters the header element.

Keep the good suggestions coming!

Cheers

Oli :)

**Comment by GavinOG** [comment]
Thanks for the quick work !

**Comment by silv2015** [comment]
Hi!

This is a really good Idea indeed! But I needed this same flexibility on the cell element.

I don't know if I did it right, but I tweaked `Column.prototype.generateCell` to add the same event that you did on the header:

`var cell = new Cell(self, row);`
`cell.element.on("mouseenter", function (e) {`
    `cell._generateTooltip();`
`});`

This way, If I put my mouse on a cell after I call `$("#myDiv").tabulator("updateData", data);`, the tooltips are all updated.

I hope I did it right! :)

**Comment by olifolkerd** [comment]
Hey @silv2015 

That should do the trick.

I will look at adding an option in the next release to let users decided weather to update tooltips on hover or on load. i would be reluctant to make it so the load on hover by default as some people do complex calculations to create their tooltips and it would create a lot of load on the system to run those calculations as the user drags their mouse over the table.

Cheers

Oli

**Comment by silv2015** [comment]
yeah, I understand. Thanks Oli!
