### ISSUE TITLE
json file to data

### ISSUE THREAD

**Issue by hg2355** [olifolkerd/tabulator#89]
I have a json file that I want to use as the dataset. It is on the same server as the tabulator code and page. what is the script for me to link this code to tabulator? sorry I'm new to this...any help would be great.

**Comment by olifolkerd** [comment]
Hi hg2355 Welcome to Tabulator!!!

To load a json file into Tabulator you can use the ***setData*** method.

In this example we assume that the testdata.json file is in the root directory of your website:
```js
$("#example-table").tabulator("setData", "/testdata.json");
```

If you want to load the data as soon as your Tabulator is built then you can set the ***ajaxURL*** property in the constructor object:
```js
$("#example-table").tabulator({
    ajaxURL:"/testdata.json",
    columns:[],
});
```

**Comment by hg2355** [comment]
Hmm..I can't seem to make it work. 

I took the first example from the website and removed the data that was defined in the variable into a separate document here: http://176.32.230.51/harpreet.us/tabular/demo.js

Then I did as you suggested: 

$("#example-table-demo").tabulator("setData","http://176.32.230.51/harpreet.us/tabular/demo.js");

But the tabulator is still empty:
http://176.32.230.51/harpreet.us/tabular/mission.html


Any help would be appreciated. I currently use exhibit (http://simile-widgets.org/exhibit3/) to display data to some people at the charter school company I work at. But the tabulator formatting is far superior.

**Comment by olifolkerd** [comment]
looking at the source for your site there are a couple of issues that need to be addressed for it to function correctly.

If you are using the ***ajaxURL*** parameter you need to set it in the constructor with the rest of your setup parameter, not run the constructor a second time.

If you are referencing a file in the same domain as the site you can use a path relative to the root of the site rather than a full URL.

If you are storing the data as JSON you should be using a .json file not a .js file

So your constructor should be (taking code from your site), notice the new ***ajaxURL*** parameter:
```js
$("#example-table-demo").tabulator({
	height:"320px",
	fitColumns:true,
	tooltips:true,
	tooltipsHeader:true,
	movableCols:true,
	ajaxURL:"/demo.json",
	columns:[
		{formatter:printIcon, width:40, align:"center",onClick:function(e, cell, val, data){alert("Printing row data for: " + data.name)} },
		{title:"Name", field:"name", sorter:"string", width:150, tooltipHeader:"Custom Header Tooltip"},
		{title:"Age", field:"age", sorter:"number", align:"left", formatter:"progress"},
		{title:"Gender", field:"gender", width:100, sorter:"string", onClick:function(e, val, cell, data){console.log("cell click - " + val, cell)}},
		{title:"Height", field:"height", formatter:"star", align:"center", sorter:"number", width:100},
		{title:"Favourite Color", field:"col", sorter:"string", sortable:false},
		{title:"Date Of Birth", field:"dob", sorter:"date", align:"center"},
			{title:"Likes Cheese", field:"cheese", align:"center", formatter:"tickCross", orter:"boolean"},
	],
	rowClick:function(e, id, data, row){
		alert("Row " + id + " Clicked!!!!")
	},
	rowContext:function(e, id, data, row){
		alert("Row " + id + " Context Clicked!!!!")
	},
});
```

There is also an issue with your json file, at the moment the file contains a JavaScript object, not a json formatted JavaScript object. to be properly formatted all of the parameter names should be in quotation marks. for example:
```js
{
	"id": 1,
	"name": "Oli Bob \n steve",
	"age": "12",
	"gender": "male",
	"height": 1,
	"col": "red",
	"dob": "",
	"cheese": 1,
	"lucky_no": 5
}
```

**Comment by hg2355** [comment]
Thanks, Oli! It worked.

So now the hard part. For exhibit, I've been using their online translator that helped me take a tsv and make it into json file that worked with exhibit (see: http://service.simile-widgets.org/babel). In their format, the parameters are NOT to be placed inside quotations.

What is the best way for me to take my tsv file and convert it into json that will work with tabulator?

**Comment by olifolkerd** [comment]
You can use the js function ***JSON.stringify()*** to convert a js object to json
