### ISSUE TITLE
Download formatted table data in csv and how to disable the real time filtering

### ISSUE THREAD

**Issue by git265** [olifolkerd/tabulator#891]
Hi Oli,

1) Can you please let me know when the feature of downloading the formatted data in the table to CSV will be available ? Currently "download to csv" downloading raw csv data.

2) How can i disable the real time header bar filtering ? Instead i want to have a button "apply filter" in header bar so that user can click on it after all various filters on different columns in header bar.

THanks,

**Comment by olifolkerd** [comment]
Hey @git265 

I Just clocked what you meant by formatters for the download, i will add a ***downloadFormatter*** property to the roadmap for the next release

Cheers

Oli.

**Comment by git265** [comment]
![image](https://user-images.githubusercontent.com/4753090/36341781-6dfbb248-13c1-11e8-8a1b-212fddc63240.png)
Hi Oli,
In the above image i want formatted data of status and createdOn fields.  This property would be really useful.

Thanks,

**Comment by olifolkerd** [comment]
Hey @git265 

I will add this to the roadmap :)

In the mean time you could use the ***downloadDataMutator*** to change the data before it is loaded into the CSV.

More info on this can be found in the [Download Documentation](http://tabulator.info/docs/3.4#download)

Cheers

Oli :)

**Comment by git265** [comment]
thank you
