### ISSUE TITLE
Download Table Data in Phonegap/Cordova App

### ISSUE THREAD

**Issue by oxfordian** [olifolkerd/tabulator#892]
Firstly, thanks for the wonderful work called tabulator.  I am sure this is going to grow into something amazing in the coming months.

One question I have is how to use the "download" option when tabulator is wrapped in a Phonegap/Cordova hybrid app.  Currently, the download option does not seem to work when running the code as a mobile app on android/ios device, however, it works when the app is loaded via the chrome Browser on the same android/ios device.

Code snippet:

`$("#my-data-table").tabulator("download", "csv", "servicedata.csv"); `

kind regards.

**Comment by olifolkerd** [comment]
Hey @oxfordian,

the Tabulator download function works by creating an anchor tag, setting the source to a data url and triggering a click on that element. If Phonegap or Cordova are configured to block this then the download will not function.

Cheers

Oli :)
