### ISSUE TITLE
Feature Request - ignore blank/empty cells on sorting

### ISSUE THREAD

**Issue by tomheaps** [olifolkerd/tabulator#893]
Hi @olifolkerd. Thanks so much for fixing the rendering bugs, working perfectly now in all browsers with 3.4.2.

When sorting a column e.g. by "alphanum" it would be great if there was an option so that any rows with blank/empty cells in this column were moved to the bottom irrespective of whether the sort direction is "asc" or "desc". Currently if the direction is "asc" rows with empty cells in the column are moved to the top of the table which is not desirable behaviour.

Would you consider adding this functionality (i.e. ignore empty cells on sort) to v3.5?

**Comment by olifolkerd** [comment]
Hey @tomheaps 

Great idea, i will add it as a ***sorterParam*** for all sorters, i have put it on the roadmap for 3.5

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @tomheaps 

I have just pushed an update for this to the 3.5 branch. you will now be able to use the ***alignEmptyValues*** sorter param to force empty cells to the top or bottom of the table:

```js
(title:"Name", field:"name", sorter:"string", sorterParams:{alignEmptyValues:"bottom"}, //force empty cells to bottom of table
```

version 3.5 has not been release yet as i will be working on it for the next couple of weeks, but i have published the documentation on the website and will be updating it as i add the features to the 3.5 branch.

Documentation for the new sorter params can be found [Here](http://tabulator.info/docs/3.5#sorting);

Cheers

Oli :)
