### ISSUE TITLE
Hiding Rows Question

### ISSUE THREAD

**Issue by YendorMc** [olifolkerd/tabulator#894]
Oli,

Thank you for your help on the "height impacting jquery css updates" #890 ticket.  That worked brilliantly.  

The colors wouldn't change, so I used the !important css tag for now, which works, until I investigate alternatives.  

One of the items I was implementing with the row color was the ability to hide the items directly under the subtotals, so one can only see the subtotal items, instead of every item.  Ideally I would use 'grouping' but can't yet as I need calculations of each column within the group.   So I decided to calculate subtotals externally and just use tabulator for viewing.  Easy Peasy!

However hiding the rows under each subtotal is again causing me grief due to the virtual dom.  Again the easy fix would be to increase the table height, but why would we want that? :o)

Following your lead, I implemented this:
```
	$("#example-table").tabulator({
		rowFormatter:function(row, data){
			// row - row component for the row
			// data - data object for row
			var data = row.getData();
			//check on data object for the "Subtotal" word
			if (data.Market == "Subtotal"){
				console.log("adding style");
				//add style
				row.getElement().addClass("subtotal");
			}
			else{
				console.log("nonsubtotal tag");
				row.getElement().addClass("nonsubtotal");
			}
		},
```
Now comes the fun...
I have two buttons called Hide and Show implemented after the dom is ready.

So using  jquery...
```
$(document).ready(function(){
	//Hide nonsubtotals
	$("#hide").click(function(){
		$('.nonsubtotal').hide();
	});
	$("#show").click(function(){
		$('.nonsubtotal').show();
	});
});
```
I'm again running into trouble, as you said, due to the virtual DOM, as they are out of view...Clicking Hide, only hides a part of the rows.

Granted I can fix by using the a larger 'height' parameter, but was curious about a "hiderow" parameter implementation in tabulator would be feasible in this case.
Granted there's probably 100 other better ways to address this... and that's another reason to ask.

In order for it to work in jquery, I'm thinking I would need to conceptually hide, and read through remaining virtual dom elements, hiding each time until the virtual DOM is empty.

Would you (or anyone else) have any suggestions to address this?

**Comment by olifolkerd** [comment]
Hey @YendorMc 

To filter rows you should use the in built [Filter System](http://tabulator.info/docs/3.4#filtering), you should create a custom filter that only allows through the subtotal rows.

I would stay away from direct DOM manipulation in all situations, it should never be necessary. Tabulator has a huge array of features that allow you to do almost anything you can imagine to the table data, have a look through the [Examples](http://tabulator.info/examples/3.4) and [Docs](http://tabulator.info/docs/3.4#filtering) for more information.

Cheers

Oli :)

**Comment by YendorMc** [comment]
I'm banging my head on my desk for not thinking about using a filter!!!  I was sooo focused on using CSS because it was working in another application, I didn't think of the obvious!  Thank you!
