### ISSUE TITLE
Passing in 'data' in rowFormatter:function(row, data)

### ISSUE THREAD

**Issue by YendorMc** [olifolkerd/tabulator#895]
Oli,
Referencing #890 ,
I was working on the code and noticed something odd, I thought I'd ask.  

Take for example this code:
```
	$("#example-table").tabulator({
		rowFormatter:function(row, data){
			// row - row component for the row
			// data - data object for row
			console.log(data);   //this is undefined
		},
```
Shouldn't both 'row' and 'data' be passed in?
When I do a console log of 'data' it's undefined, whereas row is available.
I can get it obviously, doing this:  var data = row.getData();

But when reviewing the tabulator documentation, it seems 'data' can be passed in:
```
$("#example-table").tabulator({
    rowFormatter:function(row, data){
        if(data.age >= 18){
            row.getElement().addClass("success"); //mark rows with age greater than or equal to 18 as successfull;
        }
    },
});
```
Is this expected?

Also a supplement question... what all can be passed into the function?  Are there an unlimited 'tabulator' set of variables that can be passed in?  Are those defined somewhere?
I've seen 'e','cell','value','data', etc.  

Thanks!

**Comment by olifolkerd** [comment]
Hey @YendorMc 

That is a documentation issue, i copied the example i sent you from the website. there is only one argument passed into the callback, which is the Row Component, everything else can be accessed through the row component. you can use the ***getData*** function to access the row data:

```js
var data = row.getData();
```

The arguments passed into each callback can be found in the [Callback Documentation](http://tabulator.info/docs/3.4#callbacks). As a general rule all most callbacks will be passed in a component object that relates to the action, that will allow you access to all the table functions and DOM elements you need, if it is a standard event like a mouse click then the event is also passed into the function. Sorters, filters, editors etc also receive an additional params object that allows additional information to be passed in to customise the working of a standard function.

Full information on components objects can be found [Here](http://tabulator.info/docs/3.4#components)

Cheers

Oli
