### ISSUE TITLE
True <table> Layout

### ISSUE THREAD

**Issue by Darkseal** [olifolkerd/tabulator#897]
Hello and thank you for this awesome project!

I see that you used a nested `<div>` structure to actually render the tables, instead of going with the standard `<table>` based layout. Although this is great for DOM traversing and responsiveness in general, it's quite limiting for those who need the data to be formatted into an actual HTML `<table>` element (repeating headers for printing, table-based chrome plugins to fetch data, and so on).

How about adding a `renderMode` initialization switch with `"div"` and `"table"` option?

**Comment by olifolkerd** [comment]
Hey @Darkseal 

Glad to hear you are enjoying Tabulator :D

im afraid Tabulator has to use a ***div*** element for a number of reasons:

**Complex Layout**
Tabulator offers a lot more functionality that an standard table, which requires a lot of different nested divs and spans to achieve and could not be replicated with a ***tr*** ***td*** structure.

**Default Tag Styling**
a lot of styles are applied by default to a ***table*** element, which tabulator would have to override on a browser by browser basis. and people do often apply styles to the table element site wide which would interfere with the tables operation

**Invalid HTML structure***
the only elements you are technically allowed to have directly under a table element are ***thead*** and ***tbody***, divs are not valid direct descendants of a table element in HTML and would fail validation.

Tabulator uses ARIA accessibility tags to ensure it is still correctly recognised as a table structure by screen readers and other accessibility tools.

If you are just looking to get an HTML table out of tabulator then you can use the ***getHtml*** function:
```js
var table = $("#example-table").tabulator("getHtml");
```

I hope that answers your question.

Cheers

Oli
