### ISSUE TITLE
If cell edited then press tab key it's getting old value of the cell

### ISSUE THREAD

**Issue by Praveene7** [olifolkerd/tabulator#898]
While press tab key after edited the cell old value replaced. Tabulator version 3.4

**Comment by olifolkerd** [comment]
Hey @Praveene7 

Thanks for the heads up, i will have a look at that and get a patch release out in a few hours.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @Praveene7 

You will be happy to hear i have just release version 3.4.3 to address this issue and a couple of others that have cropped up.

Thanks for your feedback, let me know if you find anything else.

Cheers

Oli :)
