### ISSUE TITLE
date sort issue I added momnet.js library but still getting error 

### ISSUE THREAD

**Issue by dipeshpatel306** [olifolkerd/tabulator#899]
Hello Oli, 

              You doing great with this. I appreciate for your effort. I am using tabulator and its works great but when I'm trying to use "date"  sort then getting error as below.

![image](https://user-images.githubusercontent.com/16158843/36427282-c1de3524-161a-11e8-900f-a0b09fbf469f.png)

I added momnet.js library in my cakephp but still getting that error. 

![image](https://user-images.githubusercontent.com/16158843/36427362-084f34d6-161b-11e8-99c5-03eb3d4b74c3.png)

**Comment by dipeshpatel306** [comment]
![image](https://user-images.githubusercontent.com/16158843/36427441-36f71038-161b-11e8-9f02-886e318c04ad.png)

**Comment by dipeshpatel306** [comment]
![image](https://user-images.githubusercontent.com/16158843/36427492-55eb0882-161b-11e8-88dc-64792bcb8bb4.png)

**Comment by olifolkerd** [comment]
Hey @dipeshpatel306 

That message means that the moment.js library is not available. which suggest that you havn't included it in your HTML.

Im not a cake developer, but usually adding a js library as a dependency only pulls the source into the project, you then have to call it in your code.

Just like you will have had to include a script link or a require statement to pull in the tabulator library you will also need one for moment, and you should pull in moment before Tabulator to ensure it is available when Tabulator loads.

Cheers

Oli

**Comment by dipeshpatel306** [comment]
Thanks   @olifolkerd  its works

**Comment by dipeshpatel306** [comment]
Hello @olifolkerd , 

              Is their any way to change date sorting format to 'MM/DD/YY'  into create from HTML Table Element

 I am trying to apply <th tabulator-sorter='date' tabulator-sorterParams='{format:"MM/DD/YY"}' >
