### ISSUE TITLE
Paging and Persistnet Data

### ISSUE THREAD

**Issue by pujasanjay** [olifolkerd/tabulator#9]
Sir
Thanking you for incorporating the Alternate Row Color

Request to consider

a) Page Size with reference to no of records per page
b) Persistence of Data in case of post back. Although the user can write the document ready code but if the application could take care of the same

Regards

Sanjay Gupta

**Comment by olifolkerd** [comment]
Hi Sanjay,

I like the persistent data idea, i will add that to the dev schedule.

could you explain a bit more what you mean by page size? ar you talking about pagination?

**Comment by pujasanjay** [comment]
Hi 
Yes is pagination. I am sorry if it is already implemented. !

Regards

**Comment by olifolkerd** [comment]
Pagination isnt implemented yet. it is planed for an upcoming release in a couple of weeks time.

**Comment by olifolkerd** [comment]
Just a quick update to let you know i have begun work on pagination and it should be available next weekend

**Comment by pujasanjay** [comment]
Hi
Thanks

You have made a  good table

Regards

Sanjay

**Comment by sethisidd** [comment]
Hi,

Was just checking if the Pagination\Async load is done. I am waiting eagerly for the feature.

Thanks
Siddharth

**Comment by olifolkerd** [comment]
Hey Siddharth,

sorry for the delay in getting this feature out, work has been a bit busy of late.

Im currently working on version 2.0 which should include this feature and well as significant improvement in loading times for large data sets.

It should be ready in the next couple of weeks.

Cheers

Oli

**Comment by sethisidd** [comment]
Hi Oli,

Great to know that the development is still active and in full pace. Looking forward to using the version 2.0

Nice to see quick response

Siddharth

**Comment by olifolkerd** [comment]
Hi Guys,

Just a quick update to let you know that the pagination feature will be available from tomorrow afternoon.

Thanks for your patience on this one.

Cheers

Oli

**Comment by olifolkerd** [comment]
Pagination is now available on Tabulator!!!

To enable pagination, set the ***pagination*** option to true when you create your Tabulator.

```js
$("#example-table").tabulator({
	pagination:true, // this option takes a boolean value (default = false)
});
```
[Click here for full details on all the pagination options.](https://github.com/olifolkerd/tabulator/wiki/Pagination)

**Comment by olifolkerd** [comment]
Hi Guys,

I have just launched a new documentation site for tabulator, check it out:
http://olifolkerd.github.io/tabulator/

Oli
