### ISSUE TITLE
issue with row hover highlight using cssClass 

### ISSUE THREAD

**Issue by YendorMc** [olifolkerd/tabulator#901]
Hi Oli,

Referencing "issue with row hover highlight" #819

I'm also having issues with row hover when cssClass is used on a column.  I'm a layer deep, though.
```
/*css*/
.nsbsecclass{
	background: rgb(238,243,248);
}

///Tabulator Column:
columns:[
{"title":"2018","columns":[
{"title":"Approval", "field":"Approval", "align":"center", width":80, "headerSort":false, "cssClass":"nsbsecclass"},
{"title":"Approval2", "field":"Approval2", "align":"center", width":80, "headerSort":false, "cssClass":"nsbsecclass"}
]
}
]
```
If I remove the cssClass the hover highlights the whole line.  Otherwise the hover is behind the cssClass.

Any thoughts to where I can patch where the whole line is hover-highlighted? :)

Thanks!

**Comment by olifolkerd** [comment]
Hey @YendorMc 

assuming you are using the standard tabulator theme have a look at the /dist/css/tabulator.css file around line 260:
```css
.tabulator .tabulator-row.tabulator-selectable:hover {
  background-color: #bbb;
  cursor: pointer;
}
```

You either need to give your column styling greater specificity than this, or add another line with the same specificity after this one,  or use the ***!important*** keyword.

Cheers

Oli :)

**Comment by YendorMc** [comment]
Holy CSS thinking BatMan!

Thanks for the push!

I ended up putting the following in my own CSS and now it works like magic!

This is what's in tabulator.css
```
.tabulator .tabulator-row.tabulator-selectable:hover {
  background-color: #bbb;
  cursor: pointer;
}
```
Then I added this to my own css
```
.tabulator .tabulator-row.tabulator-selectable:hover .nsbsecclass {
  background-color: #bbb;
  cursor: pointer;
}
```
