### ISSUE TITLE
Example and Demo code using node on the MagicMirror electron framework

### ISSUE THREAD

**Issue by E3V3A** [olifolkerd/tabulator#903]
Hi Guys!

Just for your general info, I have developed a [MagicMirror](https://github.com/MichMich/MagicMirror) module, that demonstrate the use of *Tabulator* in Node.js, and running on the electron framework. I found it extremely challenging trying to do this from the documentation on your website, so I hope this may help others looking for working examples. 

In my [MMM-Tabulator](https://github.com/E3V3A/MMM-Tabulator) repo, there are two different versions, showing the same data.
1. In the native MagicMirror environment (and over server) and
2. Directly by loading embedded JSON via HTML from `demo.html`.

I hope this help provide easier access to Tabulator, so feel free to share this with your new users. 

Cheers,
E:V:A

**Comment by olifolkerd** [comment]
Hey @E3V3A 

Thanks for sharing your module, it is great to see the variety of uses that Tabulator gets put to!

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @E3V3A 

You will be happy to hear that as of version 4.0 Tabulator is no longer jQuery dependent and now comes with a tabulator_core.min.js without all the modules installed to make it even more light weight.

:)
