### ISSUE TITLE
Vertical Scroll Bar

### ISSUE THREAD

**Issue by vmontal** [olifolkerd/tabulator#904]
Hi Oli,
how can I avoid the vertical scroll bar shift the header columns and so header is not align to cell?

thanks
![screenshot 5](https://user-images.githubusercontent.com/10527458/36489300-f8fcaef8-1725-11e8-9203-6797031872f0.png)

**Comment by olifolkerd** [comment]
Hey @vmontal 

It shouldn't be doing that, that looks a bit wonky...

Which version of tabulator are you using?
What browser are you using?
Could you post a copy of your table constructor.

Cheers

Oli :)

**Comment by vmontal** [comment]
[example.js.txt](https://github.com/olifolkerd/tabulator/files/1745446/example.js.txt)


...and the first column, even if with the parameter "visible: false" is still visible!!!!

**Comment by olifolkerd** [comment]
Hey @vmontal 

To get to the bottom of this one i need to know which version of Tabulator you are using and in which browser, so i can run a test that matches your setup.

Cheers

Oli :)

**Comment by vmontal** [comment]
Hi Oli, the version is 3.3 with Chrome!
Thanks
		
		

		SalutiValerio.NET
When I was in the meddle of the river, I rised my arms crying with a loud voice: " Is there anybody over there?".The Might One answered; so I became coding...
	




On Wed, Feb 21, 2018 at 11:07 PM +0100, "Oli Folkerd" <notifications@github.com> wrote:












Hey @vmontal


To get to the bottom of this one i need to know which version of Tabulator you are using and in which browser, so i can run a test that matches your setup.


Cheers


Oli :)

**Comment by olifolkerd** [comment]
Hey @vmontal 

Could you try with the latest 3.4.3 and let me know if the issue is still there?

Cheers

Oli :)

**Comment by vmontal** [comment]
Hi Oli,
I just updated with last version 3.4.3, but nothing change!

Attached the <head> of the document where load the css and script file...
[example-head.html.txt](https://github.com/olifolkerd/tabulator/files/1746893/example-head.html.txt)

Always Thanks in advance! :-)

**Comment by olifolkerd** [comment]
Hey @vmontal 

Looking at the photo of your table posted in issue #918 you appear to have applied some classes to the table that are causing the headers and table data to be horizontally center aligned within the table.

Tabulator is not designed to work like this, and relies on the left alignment for its calculations. this is what is causing your issues. if you remove that styling your table will work correctly.

Cheers

Oli

**Comment by vmontal** [comment]
Thanks a lot! :-)
		
		

		SalutiValerio.NET
When I was in the meddle of the river, I rised my arms crying with a loud voice: " Is there anybody over there?".The Might One answered; so I became coding...
	




On Fri, Feb 23, 2018 at 7:13 PM +0100, "Oli Folkerd" <notifications@github.com> wrote:












Closed #904.
