### ISSUE TITLE
Bug with responsive layout and hidden columns

### ISSUE THREAD

**Issue by tomheaps** [olifolkerd/tabulator#905]
Hi @olifolkerd, I have just noticed a bug with `responsiveLayout: true` using latest tabulator v3.4.3 on Chrome 64.

I have set `layout: 'fitColumns'` and all of my columns have a `width` or `minWidth` assigned (except for 2 columns that are set to `visible: false`.

If I load the table in various screen sizes, everything works great. If I start out with a large screen size and gradually shrink the window by dragging from right to left, everything behaves as expected and columns disappear in the priority according to the `responsive` integer values I have set for each column.

The bug occurs if I then start to increase window size again by dragging from left to right - columns that are set to `visible: false` start appearing. I have tried setting the width of these invisible columns to 0 but the problem still persists.

**Comment by olifolkerd** [comment]
Hey @tomheaps 

Do you think that has come in with 3.4? looking at the code i think that may have been a bug with the responsive system since it was included in 3.2.

I will have a look into that this weekend.

Cheers

Oli

**Comment by tomheaps** [comment]
@olifolkerd bug may have been present in earlier versions - I only just started playing around with responsive layouts today. Thanks for taking a look.

Out of curiosity, if you have a table with most columns set to a defined width and the remaining 2 columns set with a minWidth, how is any excess width allocated to the minWidth columns - is the extra width distributed equally between them or is it allocated proportionally depending on their original size i.e. if one column has minWidth: 50 and the other minWidth: 100, and there is 30px of excess width available, is this distributed 15px/15px or 10px/20px?

**Comment by olifolkerd** [comment]
renaming space is spread evenly across all rows that do not have a ***width*** set

**Comment by olifolkerd** [comment]
That being said i love the idea of being able to allocate portions of the available space to the different columns.

i will add a new ***fillRatio*** property to the column definition that in ***fitColumns*** layout will allocate the remaining space differently to each column based on the value of the ratio.

i will schedule this for the 3.5 release.

Thanks for the good idea.

Cheers

Oli :)

**Comment by tomheaps** [comment]
Thanks @olifolkerd, that is exactly what I was after. 

Would be even better if there was a reverse option for controlling how columns lose width when available space is reduced - similar to the CSS flexbox properties flex-grow and flex-shrink, where values of 0 mean the column should not increase or decrease in width respectively?

**Comment by olifolkerd** [comment]
Hey @tomheaps 

The shrinking option is an interesting one, i will have a think about that one.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @tomheaps 

You will be happy to hear i have just pushed a fix for this issue to the 3.5 branch.

I have also added the ***widthShrink*** and ***widthGrow*** column definition properties to allow for a more controlled  ***fitColumns*** experience.

Although 3.5 is a few weeks away from release you will be happy to hear the documentation is already available online, and I'm updating it as I add new features. 

You can find out more about the new layout features [Here](http://tabulator.info/docs/3.5?#fittowidth)

You are welcome to have a play with the features on the 3.5 branch but i will warn you that it is still in development and not stable.

Let me know what you think.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @tomheaps 

Version 3.5 has now been released!
