### ISSUE TITLE
Header Name is not visible 

### ISSUE THREAD

**Issue by minalkArmstrong** [olifolkerd/tabulator#909]
This is definition  of table

$("#Example-PaymentTerm").tabulator({
              //  fitColumns: true, //example option (sets column widths to fill table)
               // pagination: "local",
               // paginationSize: 5,
                columnVertAlign: "Top", //align header contents to bottom of cell
                tooltips: true,
               // headertooltips: true,
               groupBy: "Type",
               columns: [
                   {
                       formatter: DeleteIcon, align: "center",  visible: true, cellClick: function (e, cell) {
                           //alert("Printing row data for: " + cell.getRow().getData().name)
                           DeletePaymentTerm(cell.getRow());
                       }
                   },
                   {
                       title:"PaymentTerms", field:"PaymentTerms", visible:true,  cellClick: function (e, cell) {
                           //FetchPaymetermDataToEdit(cell);
                       }, formatter: function (cell, formatterParams) {
                           //cell - the cell component
                           //formatterParams - parameters set for the column
                           // console.dir("Payment to be made " + cell.getData().Formula.replace("*", " of ").replace("*", " of ") + " within " + cell.getData().Days + " against " + cell.getData().DocumentName)
                           return "Payment to be made " + cell.getData().Formula.replace("*", " of ").replace("*", " of ") + " within " + cell.getData().CrdDays + " days against " + cell.getData().DocumentName; //return the contents of the cell;
                       },
                   }, 
                   {
                       title:"Amount", field:"Amount",  align:"right", visible:true, cellClick: function (e, cell) {
                        //   FetchPaymetermDataToEdit(cell);
                       }, formatter: function (cell, formatterParams) {

                           return (parseInt(cell.getData().Amount) + parseInt(cell.getData().Amount1)).toLocaleString("en-IN");
                       },
                   },  //link column to name property of user object
                   { title: "id", field: "Id",  visible: true },  //link column to name property of user object
                   { title: "Documents", field: "Documents",  visible: false },  //link column to name property of user object
                   { title: "PTID", field: "PTID",  visible: false },  //link column to name property of user object
                   { title: "Type", field: "Type", visible: false },  //link column to name property of user object

                  //link column to name property of user object

                   //link column to name property of user object
                   { title: "Formula", field: "Formula",  visible: false },
                   
                    {
                        title: "Amount1", field: "Amount1",  align: "right", visible: false
                    }, 
                    { title: "Credit Days", field: "CrdDays",  visible: false},  //link column to name property of user object
                      //link column to name property of user object
                    { title: "DocumentName", field: "DocumentName",  visible: false}
                  
                ],
                groupHeader: function (value, count, data, group) {
                    //value - the value all members of this group share
                    //count - the number of rows in this group
                    //data - an arrya of all the row data objects in this group
                    //group - the group component for the group
                    if (value == 1)
                        return "<span style='color:#3aa99e; margin-left:10px;'>Supply-" + count + "</span>";
                    else
                        return "<span style='color:#3aa99e; margin-left:10px;'>Service-"+count+"</span>";
                },
               
            });

This how it looks

![test](https://user-images.githubusercontent.com/24350278/36520743-cfde6e1a-17b8-11e8-8d79-38776f10b6f2.PNG)

I dont understand what goes wrong ?

**Comment by olifolkerd** [comment]
Hey @minalkArmstrong 

That looks like your table wasnt visible when you created it. 

Tabulator needs to be visible when it renders otherwise it cannot correctly calculate the height of components because non-visible elements have no dimensions.

To get round this, call the ***redraw*** function when you make it visible for the first time:
```js
$("#example-table").tabulator("redraw", true);
```

Cheers

Oli :)

**Comment by minalkArmstrong** [comment]
Hey Oli ,
Its not working .Is there any other option for this?
