### ISSUE TITLE
Undo not working if changes made through updateOrAddRow function

### ISSUE THREAD

**Issue by answerquest** [olifolkerd/tabulator#910]
I'm seeing the Undo/Redo functionality work when I make direct edits to my table.
However, if I make changes using the `updateOrAddRow` function, it seems that change isn't being recorded. If I click Undo, then nothing happens, and the console log says there's no changes to Undo. (But I can clearly see there have been changes made).

Additionally, if I edit a cell directly, and later use the  `updateOrAddRow` function to change another cell in the same row, and then click Undo, then again no result. It seems the history of the first direct edit got erased with the change made by `updateOrAddRow`.

I'll try using the work-around described in #360 for now.

[EDIT] Just wanted to add a big Thank You for this amazing work. Using this script has helped me outsource a whole lot of data maintenance work handling to the browser and cut down the more complicated work if I had to everything, even re-ordering rows, at serverside. After everything is over, the user can just press Commit Changes and it sends the final data in JSON back to the backend.

**Comment by olifolkerd** [comment]
Hey @answerquest 

Thanks for your kind words, it is great to hear you are enjoying using Tabulator.

At the moment the undo functionality only tracks changes to the table data if it is done by editing cells in the UI.

It is primarily there as a way for a user to undo an action they have done, and as a starting point i have singled out the cell edit, add row, delete row and move row actions as the most likely to be done by the user.

The update data action on the whole tends to be used to automatically update data in the background by the system and so i have avoided tracking it.

I can see your point though, and could see it would be useful to have this option, so i will add it to the roadmap for future development.

Thanks for the feedback

Cheers

Oli :)
