### ISSUE TITLE
HELP PASSING  LARGE JSON FILE TO TABULATOR

### ISSUE THREAD

**Issue by edtaaffe** [olifolkerd/tabulator#913]
APOLOGIES FOR CAPS, JUST BROKE MY KEYBOARD.

I AM NOT VERY EXPERIENCED WITH JAVASCRIPT AND NEED ADVICE ON USING TABULATOR.
I HAVE A LARGE JSON FILE TO BUILD A TABLE FROM.
I HAVE SET UP THE COLUMNS PART MANUALLY FOLLOWING YOUR EXAMPLE. 
TO DO THE DATA FOR MY TABLE, CAN I JUST PASS IT THE JSON OBJECT , OR DO I HAVE TO WRITE OUT THE WHOLE THING AS PER YOUR EXAMPLE. IF I HAVE TO WRITE IT, IS DOCUMENT WRITE THE WAY TO GO? OR STRINGIFY ETC?  CURRENTLY I JUST GET ERRORS AND DON'T KNOW WHERE THEY ARE COMING FROM. 
THANKS

**Comment by answerquest** [comment]
Load the json file using jquery, and inside the callback run the tabulator command. Sample code:
```
$.getJSON("test.json", function(json) {
    $("#your-table").tabulator("setData", json);
});
```

**Comment by answerquest** [comment]
unrelated question: if your keyboard's broken, how are you able to code? ;)

**Comment by olifolkerd** [comment]
Hey @edtaaffe 

If it is a file on the site, you can just pass the URL to the file directly into the ***setData*** function and it will read it in for you:

```js
$("#example-table").tabulator("setData", "/data/test.json");
```

Cheers

Oli

**Comment by edtaaffe** [comment]
Thanks everyone. 
I had to go out and buy a keyboard so the answer to question two was I couldn't
Ed

**Comment by edtaaffe** [comment]
While I have your attention, can I check that my plans are sane?
I have a large json representing 30 days records. The one mentioned.#I have designed created a menu that lets the user click on a day(e.g.30 rows). I need to display other data about the day outside of tabulator so paging is not probably the ideal solution.
When the menu is clicked, My code then grabs the day object from the json.
I was hoping I could pass that day object to tabulator to show the user a single day.
Can I do it something like this:
assuming myObject is objOneDay

$("#example-table").tabulator("setData",objOneDay);

**Comment by olifolkerd** [comment]
Hey @edtaaffe 

You certainly can pass that directly into tabulator as long as it is an array containing an object of data for each row

Cheers

Oli
