### ISSUE TITLE
header filter based on cellclick

### ISSUE THREAD

**Issue by NidhiChandak** [olifolkerd/tabulator#915]
Hey again Oli,
Thanks for your help.
Is it possible for me to filter my data based on a cell click? I mean, in the attached file, if i click on Chandler, it should be filtered based on Chandler.
![1](https://user-images.githubusercontent.com/36695295/36555482-23ee8660-1828-11e8-81d0-b79dd7efdf97.png)

**Comment by olifolkerd** [comment]
Hey @NidhiChandak 

If you are running on the latest version of Tabulator (3.4.3) you can use the new ***setHeaderFilterValue*** function:

```js
$("#example-table").tabulator({
	columns:[
		{title:"id", field:"id"},
		{title:"location", field:"location", hederFilter:"input", cellClick:function(e, cell){
			$("#example-table").tabulator("setHeaderFilterValue", cell.getColumn(), cell.getValue());
		}}
	]
});
```

Let me know if that helps,

Cheers

Oli

**Comment by NidhiChandak** [comment]
It works perfectly fine Oli.
Thank you so much. Thanks for your spontaneous help always.
