### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by KimBelanger** [olifolkerd/tabulator#92]
I need a way to choose a language at instanciation, or dynamically (without repainting all the table). I guess i could do it by simply replacing strings, but have you thought about adding an api to do that ?

And if you do it, an api to ajax load json strings from a server would be even awesomer ;)

**Comment by olifolkerd** [comment]
Which parts of the table are you looking to localise? the column titles, the data, the pagination controls?

**Comment by olifolkerd** [comment]
At the moment you would have to do it by replacing the text value of the DOM elements.

However i think this is a great idea and will include it in this months release. i will make it so you can set a JSON object containing the localisation values for the table and then call a function to switch between each locale.

I would be great to know which parts of the table you are looking to localise so i can cover this scenario for you

**Comment by KimBelanger** [comment]
"Which parts of the table are you looking to localise? the column titles, the data, the pagination controls?"

Just english strings coming from your code really. Pagination ctrls, error messages etc. 
All text strings seen by a user, that come from the plugin.

Thanks for being so responsive and fast to implement suggestions.

**Comment by olifolkerd** [comment]
no problemo, i already have an idea for the system now.

will drop you a message on here when it is live

**Comment by olifolkerd** [comment]
I have some great news!

While the feature wont be officially released for a couple of days, Localization is now available through Tabulator, and I thought you may appreciate a sneek peek before the official version 2.9 release date.

It has now been merged into the master branch.

At present you can localize pagination controls and column header titles, let me know if you think I have missed anything.

I have built it in a modular fashion so it would be easy to integrate the rest of your page localization into the system if you wanted.

It also has the ability to auto-detect the current localization from the browser.

An example of localization in action can now be found [here](http://olifolkerd.github.io/tabulator/examples/#localization)

Documentation can be found [here.](http://olifolkerd.github.io/tabulator/docs/#localization)

I would love to hear your thoughts on it!

Cheers

Oli!
