### ISSUE TITLE
tabulator default area too big

### ISSUE THREAD

**Issue by kreamas** [olifolkerd/tabulator#920]
Hello.

I've generated two tables that lays within two separated "div" areas.

My tables only contains three rows of data but the table area displayed by default is too big (maybe for up to 10 to 15 available rows).

Is there a way to set tabulator default area that suits for only those three rows?

Thanks

**Comment by olifolkerd** [comment]
Hey @kreamas 

Tabulator has no default area, if you specify a height on the table element it will take up that height, if you dont it will take up the height needed to display all its rows.

The [Quickstart Guide](http://tabulator.info/quickstart/3.4) explains how to set/not set a height on the table

Cheers

Oli :)
