### ISSUE TITLE
The documentation about "Wrap Column Header Title Text"

### ISSUE THREAD

**Issue by hhsprings** [olifolkerd/tabulator#922]
Is there a divergence between document and reality? "Wrap Column Header Title Text" says:
```html
.tabulator .tabulator-header .tabulator-col .tabulator-col-content .tabulator-col-title {
    white-space: normal;
}
```
but actually `.tabulator-col` is not exist but `.tabulator-cell`  is exist, etc.

BTW.
Because there are few permanent links in the document, it is difficult to explain like this. Would you like to add more permanent links throughout?

**Comment by olifolkerd** [comment]
Hey @hhsprings 

 Im afraid you are incorrect there,

`.tabulator .tabulator-header .tabulator-col .tabulator-col-content .tabulator-col-title` does exist, but as it states in the documentation it is used to style text in the header element of the column, not the cells.

`.tabulator-cell` is used to style the cells in a column. if you want the text to wrap in the columns then you need to use the ***textarea*** formatter in the column definition for that column.

```js
$("#example-table").tabulator({
    column:[
        {title:"Details", field:"details", formatter:"textarea"}
    ],
});
```

I hope that helps,

Cheers

Oli :)

**Comment by hhsprings** [comment]
Oh, I overlooked the "header". Sorry, and thanks for suggestion to use `textarea`! (I also overlooked it...)
