### ISSUE TITLE
cdnjs.cloudflare.com URL for 3.4.4 returns 404?

### ISSUE THREAD

**Issue by hossman** [olifolkerd/tabulator#925]
I tried upgrading to 3.4.4 using the cdnjs.cloudflare.com URLs currently displayed in the docs...

```
<link href="https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.4.4/css/tabulator.min.css" rel="stylesheet">
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.4.4/js/tabulator.min.js"></script>
```

And according to the network debugger in my browser they are currently both returning 404?

**Comment by JonHaymanFCX** [comment]
I can confirm this.
Happened yesterday for me.

Ended up downloading the files and referencing them locally.

**Comment by olifolkerd** [comment]
Hey @hossman  and @JonHaymanFCX 

Could you let me know if you are still having issues as i can access the files now.

Cheers

Oli

**Comment by JonHaymanFCX** [comment]
Working great.

Thanks Oli.
