### ISSUE TITLE
Is there a way to call predefined formatter from my custom formatter?

### ISSUE THREAD

**Issue by hhsprings** [olifolkerd/tabulator#926]
Re: [#922](https://github.com/olifolkerd/tabulator/issues/922).

My column definition is like this:
```javascript
    "columns": [
        {
            "field": "p",
            "title": "url",
            "formatter": function (cell) {
                let v = cell.getValue();
                let url = calc_url_from_pathcomponent(v);
                return url;
            },
        },
        // ...
    ],
```
I want to invoke the predefined `textarea` formatter. Any idea? (Of course I know it's easy to implement "textarea-like" feature, but I want to know how to chain multiple formatters, because I have a lot of different formters with slightly overlapping roles and I registered them with extendExtension.)

**Comment by olifolkerd** [comment]
Hey @hhsprings 

you can only apply one formatter at a time im afraid. But if all you are after it to allow thos cells height to change to fit their contents you can set the ***variableHeight*** property of the column to ***true*** and it will have the same effect:

```javascript
    "columns": [
        {
            "field": "p",
            "title": "url",
            "variableHeight" :true,
            "formatter": function (cell) {
                let v = cell.getValue();
                let url = calc_url_from_pathcomponent(v);
                return url;
            },
        },
        // ...
    ],
```

Let me know if that helps

Cheers

Oli

**Comment by hhsprings** [comment]
> Let me know if that helps

Sorry, this seems not to help my case. Originally, I wish:

![i_wish](https://user-images.githubusercontent.com/2637305/36833627-6e6f4f30-1d73-11e8-93fc-2d4aa41ecfa2.PNG)

And my question [#922](https://github.com/olifolkerd/tabulator/issues/922) was a workaround for this case (for me). I wondered if it could be like this:
```javascript
    "columns": [
        {
            "field": "p",
            "title": "url",
            "variableHeight" :true,
            "formatter": function (cell) {
                let v = cell.getValue();
                let url = calc_url_from_pathcomponent(v);
                return Tabulator.getExtension("format", "formatter")["textarea"](url);
            },
        },
        // ...
    ],
```
