### ISSUE TITLE
rowspan data

### ISSUE THREAD

**Issue by vmontal** [olifolkerd/tabulator#927]
Hi Oli,
is it possible grouping data in a column with a rowspan model?

I attach an Excel file to show what I'd like to get. (it's easier to see that to explain!)
[pf_elencoOfferte.xlsx](https://github.com/olifolkerd/tabulator/files/1761941/pf_elencoOfferte.xlsx)

Always thanks in advance!

**Comment by olifolkerd** [comment]
Hey @vmontal 

There is no rowspan yet in Tabulator, but if you use the ***textarea*** formatter on a column it cause the cells height to vary to fit its contents which is what it looks like you are after.

Cheers

Oli :)
