### ISSUE TITLE
Continuing to add rows doesn't respect pagination size

### ISSUE THREAD

**Issue by davidawad** [olifolkerd/tabulator#929]
Hello! 

I noticed that if I continue to add new rows to my tabulator, and the number of rows I've added pushes the total over the pagination boundary **that should begin a second page**, the table does not begin paginating to adjust for this. 

Is this a bug or do I need to enable a certain flag? 

Thanks

**Comment by olifolkerd** [comment]
Hey @davidawad 

It is not so much a bug as a design choice as a result of feedback from other users who didn't want new rows appearing on other pages.

However the paging system hasn't really been updated in about a year, and is scheduled for an overhaul in the next release, so i will look at adding a variety of options to allow users to customize how rows are added in future.

Thanks for your thoughts.

Cheers

Oli :)
