### ISSUE TITLE
First row has header

### ISSUE THREAD

**Issue by mohanen** [olifolkerd/tabulator#930]
Hi Oli,

Is it possible to have the first row has header instead of the column in v3.2.x?

**Comment by olifolkerd** [comment]
Hey @mohanen 

Im afraid you have to define the columns separately from the rows, though in version 3.4 you can now freeze a row at the top of the table.

There is nothing to stop you making your ajax request for the row data outside of Tabulator, then using your own code to call the ***setColumns*** function an building the table columns from the data.

Cheers

Oli
