### ISSUE TITLE
Disabled or readonly tabulatorHolder div

### ISSUE THREAD

**Issue by ZinThiThiTun** [olifolkerd/tabulator#931]
If some condition is occured, i want to disabled or readonly tabulatorHolder Div(※all data row in tabulator).
How can i do that?

**Comment by tomheaps** [comment]
You could achieve this through your CSS using the [pointer-events Property](https://css-tricks.com/almanac/properties/p/pointer-events/) e.g. by setting your tabulator div to `pointer-events: none` using CSS media queries or JavaScript?

**Comment by ZinThiThiTun** [comment]
Yes,
I got it.
Thanks.

**Comment by olifolkerd** [comment]
Hey @ZinThiThiTun  and @tomheaps 

Great suggestion there @tomheaps 

As another option you can also pass a function to the ***editable*** property in a column definition that could check a variable to see if the page was in an editable state or not:

```js
var canEditTables = true; //change this variable to determine if users can edit table

var editCheck = function(cell){
    return canEditTables;
}

//in your column definition for the column
{title:"Name", field:"name", editor:"input", editable:editCheck}
```

Cheers

Oli :)

**Comment by ZinThiThiTun** [comment]
Yeah,
Thanks Oli and @tomheaps 
but I have two conditions with editable cell
First: the whole table can't edit
Second: if one checkbox cell is checked,the other textbox is can't edit
That's why i use your first suggestions.
Thanks You.
