### ISSUE TITLE
Column field property values set to certain strings matching JS built in prop/function names such as "length" cause errors

### ISSUE THREAD

**Issue by jamesbarnett91** [olifolkerd/tabulator#936]
Hi, thanks for such a great project, it's been really easy to use. However I've recently noticed this issue:

Tested with latest tabulator 3.4.4 in Chrome and FF. Example fiddle [here](https://jsfiddle.net/y337t0tf/6/)

If the column field property is set to the same string literal as certain built in JavaScript properties/functions, either errors are thrown, or the function with the same name is actually evaluated and set as the displayed column title.

E.g. setting a column field property to "length"
``` 
$("#example-table").tabulator({
    columns:[ 
        {title:"foo", field:"length"}
    ],
});

var tabledata = [
    {length:"bar"}
];

$("#example-table").tabulator("setData", tabledata); 
```
causes `Uncaught RangeError: Invalid array length at ColumnManager.registerColumnField` which corresponds to [https://github.com/olifolkerd/tabulator/blob/master/src/js/column_manager.js#L118](https://github.com/olifolkerd/tabulator/blob/master/src/js/column_manager.js#L118)

Similarly a field property of "toString" 
 ```
$("#example-table").tabulator({
    columns:[ 
        {title:"foo", field:"toString"}
    ],
});

var tabledata = [
    {toString:"bar"}
];

$("#example-table").tabulator("setData", tabledata)
```
The column title is literally displayed as `[object HTMLDivElement]`

Since I am generating the row and column data dynamically based on user data, I can’t guaranete what the property values will be.
I’ve worked around it by intercepting the data and prefixing every field with underscores to avoid clashing, which is easy enough, but it would be nice if tabulator could handle this issue internally?

**Comment by olifolkerd** [comment]
Hey @jamesbarnett91 

Thanks for getting in touch

Im afraid this is a restriction with javascript objects, they are not allowed to have values set on properties that are reserved words.

While i understand that it is inconvenient in this usage case it would be a major burden to re-architect the system to cover every reserved word (which are subject to change), and most developers just avoid using them as standard practice.

If this is a constraint unique to your data set then i would recommend the course you have taken to parse the data into valid objects first.

Cheers

Oli :)

**Comment by c-dante** [comment]
This isn't an error with JavaScript objects.

The bug here is specifically this line in column manager:

https://github.com/olifolkerd/tabulator/blob/0290bcd302637d61a4c81e2f675cd58778e8f31f/src/js/column_manager.js#L8

By setting the prototype to an array, the "length" property is reserved (as well as some other baggage). This is also not good practice, since that object is being used as a string mapping everywhere else in the code. You can address this by just setting it to `{}`.

**Comment by olifolkerd** [comment]
Hey @c-dante 

Thanks for the detailed reply there, you are correct that is definitly a bug, i will get a fix out for that in the next patch release.

Cheers

Oli :)

**Comment by c-dante** [comment]
Thanks @olifolkerd!

**Comment by olifolkerd** [comment]
I have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)
