### ISSUE TITLE
columnVisibilityChanged not fired

### ISSUE THREAD

**Issue by ProxiBlue** [olifolkerd/tabulator#937]
Hi,

Can I check if columnVisibilityChanged callBack is working in latest release?
Defined as such:

![selection_169](https://user-images.githubusercontent.com/4994260/36825685-c3a26314-1d43-11e8-97a8-aad3a044c7de.png)

I use responsiveLayout, which hides a column. (works 100%)
The callBack is not called (using chrome debug breakpoint, never gets set / no console log happens)

I then placed a test visibility change on a rowClick event, to test if it is an issue with responsive
```

rowClick:function(e, row){
                            jQuery(".custom-product-list").tabulator("hideColumn","part")
                            //jQuery(location).attr('href', row.getData().url);
                        },
```

The click hides the column, but the callback does not fire.

TIA

**Comment by olifolkerd** [comment]
Hey @ProxiBlue 

Thanks for getting in touch, looks like you have found a bug there.

I have just pushed a fix to the master branch and will include it in this weekends patch release.

Let me know if you have any other issues.

Cheers

Oli :)

**Comment by ProxiBlue** [comment]
:+1: 

Thanks heaps man.
