### ISSUE TITLE
Delete tabulator

### ISSUE THREAD

**Issue by ZinThiThiTun** [olifolkerd/tabulator#938]
Hi,
Can i delete tabulator in my javascript?

**Comment by olifolkerd** [comment]
Hey @ZinThiThiTun 

if you want to remove an existing Tabulator you can use the ***destroy*** function:

```js
$("#example-table").tabulator("destroy");
```

Cheers

Oli :)

**Comment by ZinThiThiTun** [comment]
Hi Oli
This answer is really help me 
Thank You Very Much
:)
