### ISSUE TITLE
How can i set an Image in column

### ISSUE THREAD

**Issue by kurtknippschild** [olifolkerd/tabulator#94]
Hi,
 i'm new testing the Tabulator-plugin.
My first table works but i hab a problem with icons in cell.
Here is my code-snippet:

       var infoIcon = function(value, data, cell, row, options){ //plain text value
            return "<span class='infoImage'></span>";
        };
		
		$("#tabulator_objektgruppe").tabulator({
		    pagination:"local",
		    paginationSize:20,
		    //fitColumns:true, //fit columns to width of table (optional)
		    columns:[ //Define Table Columns
		{formatter:infoIcon, width:40, align:"center", onClick:function(e, cell, val, data){alert("Info data for: " + data.og_id)}},
		{title:"ID", field:"og_id", sorter:"number", align:"center", width:24},
		 ],

and here my css.class:
.infoImage {
	background-image: url('../../img/Dashboard/details.png');
	background-repeat: no-repeat;
	background-size: 16px 16px;
	cursor: pointer;
}

The icon was not show in the first column.

![bildschirmfoto 2016-11-16 um 12 37 21](https://cloud.githubusercontent.com/assets/22855656/20345928/a5563e60-abf9-11e6-8e11-c8683a553776.png)

**Comment by olifolkerd** [comment]
The images isn't showing because you havnt set a size for your span. so it has a width and height of 0 and this dosnt display the image.

Given that you are just using an image you could use an ***img*** tag instead (adjust image path as appropriate):
```js
var infoIcon = function(value, data, cell, row, options){ 
        return "<img class='infoImage' src='../../img/Dashboard/details.png'>";
};
```
```css
.infoImage {
    height:16px;
    width:16px;
    cursor:pointer;
}
```

**Comment by kurtknippschild** [comment]
Hi Oli,

thanks for the quick answer.
It works.
I have a other question.
The data for a column is a name for a icon (for Example: /og_projekte.png)
What is the best way the Icon to show in the Column an not the name of the
icon?

Thank you in advance.

MG Kurt
mit freundlichen Grüßen
 
Kurt Knippschild
 
Kurt Knippschild
Am Kränzenberg 17
64646 Heppenheim
 
Telefon:            +49 6252 9679817
Mobil:              +49 170 3851198
Telefax:            +49 6252 670611
EMail:              kurt@knippschilds.de
<mailto:kurt@ingenieurbuero-knippschild.de>
Internet:            www.knippschilds.de
<http://www.ingenieurbuero-knippschild.de/>

Von:  Oli Folkerd <notifications@github.com>
Antworten an:  olifolkerd/tabulator
<reply+015cbfe86adbff45a4e2ecea0cc62f44fda2eb6916ae242592cf0000000114446b329
2a169ce0b4e414e@reply.github.com>
Datum:  Mittwoch, 16. November 2016 um 20:45
An:  olifolkerd/tabulator <tabulator@noreply.github.com>
Cc:  Kurt Knippschild <kurt@knippschilds.de>, Author
<author@noreply.github.com>
Betreff:  Re: [olifolkerd/tabulator] How can i set an Image in column (#94)

> <img class='infoImage' src='../../img/Dashboard/details.png'>

**Comment by olifolkerd** [comment]
In that case you want to use a custom formatter, which sets the src of the image to the value of the field. 

So for this example lets assume that the field that contains the image is called icon.

```js
//custom icon formatter
var iconFormatter= function(value, data, cell, row, options){ //plain text value
    return "<img class='infoImage' src='" + value + "'>";
};

$("#example-table").tabulator({
    columns:[
        {title:"icon", field:"icon", align:"center", formatter:iconFormatter},
    ]
});

```

**Comment by kurtknippschild** [comment]
Hi Oli,

thanks for the quick answer.
It works great.
Here is the first result:

MG Kurt
mit freundlichen Grüßen
 
Kurt Knippschild
 
Kurt Knippschild
Am Kränzenberg 17
64646 Heppenheim
 
Telefon:            +49 6252 9679817
Mobil:              +49 170 3851198
Telefax:            +49 6252 670611
EMail:              kurt@knippschilds.de
<mailto:kurt@ingenieurbuero-knippschild.de>
Internet:            www.knippschilds.de
<http://www.ingenieurbuero-knippschild.de/>

Von:  Oli Folkerd <notifications@github.com>
Antworten an:  olifolkerd/tabulator
<reply+015cbfe81384856776265aecbcab3ac775d05d8ee2307df092cf00000001144495d09
2a169ce0b4e414e@reply.github.com>
Datum:  Mittwoch, 16. November 2016 um 23:46
An:  olifolkerd/tabulator <tabulator@noreply.github.com>
Cc:  Kurt Knippschild <kurt@knippschilds.de>, Author
<author@noreply.github.com>
Betreff:  Re: [olifolkerd/tabulator] How can i set an Image in column (#94)

**Comment by sarkariajatt** [comment]
tabulatorActionButton:function(e, cell){
		var html = '<div class="dropdown">'+
		  '<button class="btn btn-secondary-icon dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="far fa-ellipsis-v"></i></button>'+
		  '<div class="dropdown-menu dropdown-menu-right animated fadeIn fastest">'+
		  '<a class="dropdown-item" esqTabulatorAction="edit" href="#!">Edit</a>'+
		  '<a class="dropdown-item" data-toggle="modal" data-target="#confirmdeletion" esqTabulatorAction="delete" href="#!">Delete</a>'+
		  '</div>'+
		  '</div>';
		return html;
	},

hi this the formatter function i have and i am using this in tabulator to make a cell as a dropdown which says edit or delete. 

				{	
					title:"Action",
					cssClass:'action-column',
					formatter:util.tabulatorActionButton, 
					width:140, 
					align:"left", 
					cellClick:function(e, cell){
						e.stopPropagation(); 
						var clicked=$(e.target).attr('esqTabulatorAction');
						if(clicked=='edit'){
							alert("edit data connection");
						}else if(clicked=='delete'){
							alert("delete data connection")
						}
					}
				},
above code is used to intiate the formatter for action cloumn. but as there is no field attribute for this custom so i can see that tabulator is modifying the original json i am providing to tabultor to draw table. it adds extra prop:value in that json which says undefined:undefined

**Comment by olifolkerd** [comment]
Hey @sarkariajatt 

This issue is closed and the problem your are posting has nothing to do with this issue.

Please create a new issue with your proplem to make it easier for others to find the solution if they are having the same issue

Cheers

Oli

**Comment by shrutis0896** [comment]
Hi @olifolkerd , 

I am trying to add two icons in a column but even after setting a height and width they are not showing up. I can see them being appended in HTML on inspecting elements. Can you let me know if I am missing out anything. Below is my code:


deleteIcon = function(cell, formatterParams){
  return `<fa-icon [icon]="['fas', 'edit']" size="sm"  style="cursor: not-allowed;color: lightgray; width:20px; height:20px;">
  </fa-icon>

  <fa-icon [icon]="['fas', 'trash']" size="sm" style="cursor: pointer;color: #E74C3C; width:20px; height:20px;">
  </fa-icon>`;
}
  
table;
  createKPITable(){

  this.table = new Tabulator("#kpiTable", {
      layout:"fitColumns",
      pagination :5,
      
      columns:[
      {formatter: this.deleteIcon , hozAlign:"center", cellClick: this.globalClick},
      {title:"KPI Name", field:"kpi_master_name", hozAlign:"center",formatter:"textarea"},
      {title:"Description", field:"kpi_master_description", hozAlign:"center",formatter:"textarea"},
      {title:"Display Name", field:"display_name" , hozAlign:"center",formatter:"textarea"},
      {title:"Aggregation", field:"aggregate_function" , hozAlign:"center",formatter:"textarea"},
      {title:"UoM", field:"uom" , hozAlign:"center",formatter:"textarea"},
      {title:"Data Type", field:"kpi_datatype" , hozAlign:"center",formatter:"textarea"},
      ],
  });
     
  }
