### ISSUE TITLE
Secondary Sort doesn't seem to work (Tabulator 3.4.3)

### ISSUE THREAD

**Issue by lesarrow** [olifolkerd/tabulator#940]
I am sorting first (desc) by a number column with the secondary being a (asc) string column.  The result is the table is sorted by only the string column. I've tried a few different combinations and it seems the table is just sorted by whichever record is specified last in the initialSort array seemingly ignoring the primary sort. 

The result is the same with both initialSort and setSort. 

I also tried with two string columns to see if it could be type specific, but the same result occurred.

**Comment by olifolkerd** [comment]
Hey @lesarrow 

In order to help you out it would be useful if you can post a copy of your table constructor and the code you are using to trigger different sorts so i can see where any issues may be.

Cheers

Oli :)

**Comment by lesarrow** [comment]
Sorry about that. I should have just done that originally.

$(document).ready(function() {
    $('#example-table').tabulator({
        layout: "fitColumns",
        height:"1200px",
        columns:[
            {title:"Name", field:"name", sorter:"string", minWidth:130},
            {title:"Team", field:"team", sorter:"string", width:75, align:"center"},
            {title:"Pos", field:"pos", headerSort:false, minWidth:100},
            {title:"$", field:"orig_value", sorter:"number", width:35, align:"right"},
            {title:"AVG", field:"avg", sorter:"number", align:"center", width:70},
            {title:"R", field:"r", sorter:"number", width:35, align:"right"},
            {title:"HR", field:"hr", sorter:"number", width:35, align:"right"},
            {title:"RBI", field:"rbi", sorter:"number", width:60, align:"center"},
            {title:"SB", field:"sb", sorter:"number", width:35, align:"right"},
            {title:"ABs", field:"ab", sorter:"number", width:60, align:"center"},
            {title:"W", field:"w", sorter:"number", width:35, align:"right"},
            {title:"SV", field:"sv", sorter:"number", width:35, align:"right"},
            {title:"ERA", field:"era", sorter:"number", width:70, align:"center"},
            {title:"WHIP", field:"whip", sorter:"number",width:75, align:"center"},
            {title:"K", field:"k", sorter:"number", width:35, align:"right"},
            {title:"IP", field:"ip", sorter:"number", width:60, align:"center"},
        ],
        initialSort:[
            {column:"orig_value", dir:"desc"},
            {column:"name", dir:"asc"},
        ], 
    }) 
});

**Comment by olifolkerd** [comment]
Hey @lesarrow 

Thanks for posting that, it looks correct. could you post a few rows of sample data so i have something to test against.

Cheers

Oli

**Comment by lesarrow** [comment]
Hi Oli,

Here's some code with data that fails:

$(document).ready(function() {
    $('#example-table').tabulator({
        layout: "fitColumns",
        height:"1200px",
        columns:[
            {title:"Name", field:"name", sorter:"string", minWidth:130},
            {title:"Team", field:"team", sorter:"string", width:75, align:"center"},
            {title:"Pos", field:"pos", headerSort:false, minWidth:100},
            {title:"$", field:"orig_value", sorter:"number", width:35, align:"right"},
        ],
        initialSort:[
            {column:"orig_value", dir:"desc"},
            {column:"name", dir:"asc"},
        ], 
    });
    
    input = [
  {
    "rbi": 33,
    "c": 0,
    "orig_value": -2,
    "rp": 0,
    "primary_key": 310,
    "ss": 0,
    "of": 0,
    "sp": 0,
    "avg": 0.262,
    "pos": "UT",
    "ut": 1,
    "player_key": 175,
    "hr": 10,
    "fb": 0,
    "ab": 217,
    "b2": 0,
    "team": "LAA",
    "sb": 2,
    "r": 32,
    "tb": 0,
    "name": "Ohtani(H), Shohei"
  },
  {
    "rbi": 86,
    "c": 0,
    "orig_value": 27,
    "rp": 0,
    "primary_key": 136,
    "ss": 0,
    "of": 0,
    "sp": 0,
    "avg": 0.31,
    "pos": "2B",
    "ut": 1,
    "player_key": 1,
    "hr": 18,
    "fb": 0,
    "ab": 600,
    "b2": 1,
    "team": "HOU",
    "sb": 25,
    "r": 96,
    "tb": 0,
    "name": "Altuve, Jose"
  },
  {
    "rbi": 63,
    "c": 0,
    "orig_value": 16,
    "rp": 0,
    "primary_key": 137,
    "ss": 0,
    "of": 0,
    "sp": 0,
    "avg": 0.31,
    "pos": "2B",
    "ut": 1,
    "player_key": 2,
    "hr": 9,
    "fb": 0,
    "ab": 580,
    "b2": 1,
    "team": "COL",
    "sb": 9,
    "r": 95,
    "tb": 0,
    "name": "LeMahieu, DJ"
  },
  {
    "rbi": 76,
    "c": 0,
    "orig_value": 18,
    "rp": 0,
    "primary_key": 138,
    "ss": 0,
    "of": 0,
    "sp": 0,
    "avg": 0.31,
    "pos": "2B",
    "ut": 1,
    "player_key": 3,
    "hr": 17,
    "fb": 0,
    "ab": 501,
    "b2": 1,
    "team": "WSH",
    "sb": 2,
    "r": 73,
    "tb": 0,
    "name": "Murphy, Daniel"
  },
  {
    "rbi": 105,
    "c": 0,
    "orig_value": 41,
    "rp": 0,
    "primary_key": 139,
    "ss": 0,
    "of": 1,
    "sp": 0,
    "avg": 0.308,
    "pos": "OF",
    "ut": 1,
    "player_key": 4,
    "hr": 37,
    "fb": 0,
    "ab": 513,
    "b2": 0,
    "team": "LAA",
    "sb": 20,
    "r": 110,
    "tb": 0,
    "name": "Trout, Mike"
  },
  {
    "rbi": 103,
    "c": 0,
    "orig_value": 38,
    "rp": 0,
    "primary_key": 140,
    "ss": 0,
    "of": 1,
    "sp": 0,
    "avg": 0.301,
    "pos": "OF",
    "ut": 1,
    "player_key": 5,
    "hr": 36,
    "fb": 0,
    "ab": 514,
    "b2": 0,
    "team": "WSH",
    "sb": 9,
    "r": 101,
    "tb": 0,
    "name": "Harper, Bryce"
  },
  {
    "rbi": 93,
    "c": 0,
    "orig_value": 34,
    "rp": 0,
    "primary_key": 141,
    "ss": 0,
    "of": 1,
    "sp": 0,
    "avg": 0.3,
    "pos": "OF",
    "ut": 1,
    "player_key": 6,
    "hr": 28,
    "fb": 0,
    "ab": 594,
    "b2": 0,
    "team": "BOS",
    "sb": 21,
    "r": 106,
    "tb": 0,
    "name": "Betts, Mookie"
  },
  {
    "rbi": 68,
    "c": 0,
    "orig_value": 27,
    "rp": 0,
    "primary_key": 142,
    "ss": 1,
    "of": 0,
    "sp": 0,
    "avg": 0.298,
    "pos": "SS",
    "ut": 1,
    "player_key": 7,
    "hr": 17,
    "fb": 0,
    "ab": 591,
    "b2": 0,
    "team": "WSH",
    "sb": 50,
    "r": 98,
    "tb": 0,
    "name": "Turner, Trea"
  },
  {
    "rbi": 92,
    "c": 0,
    "orig_value": 24,
    "rp": 0,
    "primary_key": 143,
    "ss": 0,
    "of": 0,
    "sp": 0,
    "avg": 0.297,
    "pos": "2B//3B",
    "ut": 1,
    "player_key": 8,
    "hr": 21,
    "fb": 0,
    "ab": 598,
    "b2": 1,
    "team": "CLE",
    "sb": 17,
    "r": 91,
    "tb": 1,
    "name": "Ramirez, Jose"
  },
  {
    "rbi": 83,
    "c": 0,
    "orig_value": 22,
    "rp": 0,
    "primary_key": 144,
    "ss": 0,
    "of": 1,
    "sp": 0,
    "avg": 0.296,
    "pos": "OF",
    "ut": 1,
    "player_key": 9,
    "hr": 24,
    "fb": 0,
    "ab": 580,
    "b2": 0,
    "team": "MIL",
    "sb": 12,
    "r": 96,
    "tb": 0,
    "name": "Yelich, Christian"
  },
  {
    "rbi": 84,
    "c": 0,
    "orig_value": 16,
    "rp": 0,
    "primary_key": 145,
    "ss": 0,
    "of": 0,
    "sp": 0,
    "avg": 0.296,
    "pos": "1B",
    "ut": 1,
    "player_key": 10,
    "hr": 20,
    "fb": 1,
    "ab": 541,
    "b2": 0,
    "team": "HOU",
    "sb": 4,
    "r": 74,
    "tb": 0,
    "name": "Gurriel, Yuli"
  },
  {
    "rbi": 71,
    "c": 1,
    "orig_value": 15,
    "rp": 0,
    "primary_key": 146,
    "ss": 0,
    "of": 0,
    "sp": 0,
    "avg": 0.296,
    "pos": "C//1B",
    "ut": 1,
    "player_key": 11,
    "hr": 16,
    "fb": 1,
    "ab": 492,
    "b2": 0,
    "team": "SF",
    "sb": 3,
    "r": 69,
    "tb": 0,
    "name": "Posey, Buster"
  },
  {
    "rbi": 130,
    "c": 0,
    "orig_value": 34,
    "rp": 0,
    "primary_key": 147,
    "ss": 0,
    "of": 0,
    "sp": 0,
    "avg": 0.296,
    "pos": "3B",
    "ut": 1,
    "player_key": 12,
    "hr": 38,
    "fb": 0,
    "ab": 582,
    "b2": 0,
    "team": "COL",
    "sb": 3,
    "r": 99,
    "tb": 1,
    "name": "Arenado, Nolan"
  },
  {
    "rbi": 80,
    "c": 0,
    "orig_value": 27,
    "rp": 0,
    "primary_key": 148,
    "ss": 0,
    "of": 1,
    "sp": 0,
    "avg": 0.295,
    "pos": "OF",
    "ut": 1,
    "player_key": 13,
    "hr": 26,
    "fb": 0,
    "ab": 598,
    "b2": 0,
    "team": "COL",
    "sb": 15,
    "r": 103,
    "tb": 0,
    "name": "Blackmon, Charlie"
  }, 
 
];
    
    $('#example-table').tabulator("setData", input);
    
});

**Comment by olifolkerd** [comment]
Hey @lesarrow 

Using your example above it works it works correctly, though you wouldn't be able to see the secondary sort on your example because none of the "orig_value" values are the same so it would just look like a single sort.

If you tried the following initialSort:
```js
initialSort:[
	{column:"name", dir:"asc"},
	{column:"pos", dir:"desc"},
],
```

You will see that the data is sorted by position, and then those with the same position are sorted alphabetically by name,

I hope that helps,

Cheers

Oli :)

**Comment by lesarrow** [comment]
Hi Oli,

You are mistaken in your reply. There are several records where "orig_value" is the same. 

"orig_value" is the same for records "Arenado", and "Betts"
"orig_value" is also the same for records Blackmon, Altuve, and Turner.

But I did catch something in your reply...

The initialSort setting is processed in reverse order.

So, 

initialSort:[
{column:"orig_value", dir:"desc"},
{column:"name", dir:"asc"},
],

...actually sorts by "name" and then by "orig_value".

This is opposite than it says in the documentation. The documentation says:

$("#example-table").tabulator("setSort", [
    {column:"age", dir:"asc"}, //sort by this first
    {column:"height", dir:"desc"}, //then sort by this second
]);

In this example, tabulator would actually sort by height first and then by age.

Thank you for your help.

--Les
