### ISSUE TITLE
Need advice, how to get the best performance using .tabulator("addRow", data);

### ISSUE THREAD

**Issue by ipalfy** [olifolkerd/tabulator#941]
Tabulator is awesome and  fast enough for most purposes.

However this time I need to populate tabulator with a extreme amount of data coming in extremely fast. Now I am not sure which potentially unneeded features could slow down the process.

Do you have any best practices when it comes to sqeezing out the last millisecond? What to do and what to avoid?

**Comment by olifolkerd** [comment]
Hey @ipalfy 

Thanks for getting in touch,

Could you explain a bit more about what you are trying to achieve?  what sort of data throughput are you looking at? how many rows?

are you just looking to add rows or are you going to be updating existing data? how many updates per minute are you looking to do to the table?

Cheers

Oli
