### ISSUE TITLE
CellClick with ajax loaded columns definitions

### ISSUE THREAD

**Issue by vasiliyaltunin** [olifolkerd/tabulator#943]
I load columns definitions via ajax and then in tabulator like that:

`$("#listtable").tabulator("setColumns", tableColumnsData[0]);`

In my table when i click on row new page with this item opened.

Now i need to able to select few rows to apply to them some actions at once. So i just add empty column with width 40px and enable table select.

All seems work fine except i cant stop tabulator got to record every time row clicked. So i modify my script to that:
```
            rowClick: function (e, row) {
		if ( (isSelectable != true) && (row.row.getCellIndex()!=0) )
		{
	                gotoRecord(row.getIndex());
        	        registerAjax();
		}
            },

```

but it seems `(row.row.getCellIndex()` did not work. All i need to limit gotoRecord to all rows except first one. 

How i can do it, i find that i can use CellClick, but have problem with that may be there other way to do so?

**Comment by olifolkerd** [comment]
Hey @vasiliyaltunin 

im afraid there is no row property on the row object, there is also no ***getCellIndex*** function, where did you get that information from?

To get the position of the row in the table you can call the ***getPosition*** function on the row object
```js
rowClick: function (e, row) {
    //position of row
    var position = row.getPosition();
}
```
Let me know if that helps,

Cheers

Oli

**Comment by vasiliyaltunin** [comment]
Nope it returns row index, but i need column index. So if user click on cell of first column it returns 0, but if it click at cell of second column it returns 1 and etc, so if user click at any cell of first column it does nothing and just select row and if any other cell with any other column clicked it just go to page for this record. And also it good if i can control if row selected based on some criteria.

**Comment by vasiliyaltunin** [comment]
I solve it in different way:

1. i set column width to 40.4321px
2. Just checking column width:
```
            rowClick: function (e, row) {
		if (e.target.style.width!="40.4321px")
		{
	                gotoRecord(row.getIndex());
        	        registerAjax();
		}
            },

```

**Comment by vasiliyaltunin** [comment]
Is there a way to deselect row when i click other columns than first?

**Comment by vasiliyaltunin** [comment]
Ok i get it $("#listtable").tabulator("deselectRow");
