### ISSUE TITLE
Filtering TypeError when Tabulator runs toLowerCase()

### ISSUE THREAD

**Issue by xXmrotsXx** [olifolkerd/tabulator#944]
Hi Oli,

I've run into a strange problem with a simple filter similar to your example where you select a field from a drop-down, and then enter text as an input to filter the table contents. However, selecting any other than the first field from the drop-down produces the following error when the input string is entered...

![image](https://user-images.githubusercontent.com/36215684/37018022-8a2438be-215e-11e8-939c-aa489b796754.png)

I'm using the NOT min file to try to debug. Typing `filterInput.value` and `filterInput.value.toLowerCase()` in the console yield what would be expected regarding the input string...

Any suggestions as to where things are going wrong?

Thanks.

**Comment by JonHaymanFCX** [comment]
Try using:
`filterInput.val().toLowerCase()`

**Comment by xXmrotsXx** [comment]
`Uncaught TypeError: filterInput.value is not a function`... 

Forgive me as I'm still new to this @JonHaymanFCX, how does that help me?

**Comment by olifolkerd** [comment]
Hey @xXmrotsXx 

Could you post a copy of the code you are using to set the filter along with the value of the filter that is causing the error to occur.

Is this a header filter or a select element you have created outside the table?

Cheers

Oli

**Comment by xXmrotsXx** [comment]
Thanks Oli, I literally just found my problem... 

It was actually the rowVal in tabulator.js that was throwing the exception due to a dodgy null value in one of my rows...

I see there is a check for filterVal being null but not rowVal so it was sneaking through.

In any case, all good now. 

Thanks again for your prompt reply as always.

**Comment by olifolkerd** [comment]
Hey @xXmrotsXx 

Glad you got to the bottom of the problem, what do you mean by a rowVal of null? do you mean the entire row data object was instead a null?

Cheers

Oli :)

**Comment by xXmrotsXx** [comment]
I had an empty row in my data therefore rowVal was undefined.

Thanks again.
