### ISSUE TITLE
Same options json doesn't work for two tables on the same page, but deep copying gives a workaround

### ISSUE THREAD

**Issue by answerquest** [olifolkerd/tabulator#945]
Hi, I have defined a json variable having the table options:
```
var tabulatorOptions = {
 index: 'stop_id',
 ...
 columns: [
  {rowHandle:true, formatter:"handle", headerSort:false, frozen:true, width:30, minWidth:30 },
  {title:"stop_id", field:"stop_id", headerFilter:"input", headerFilterPlaceholder:"filter by id", headerSort:false },
  {title:"stop_name", field:"stop_name", headerFilter:"input", headerFilterPlaceholder:"filter by name", headerSort:false }
 ],
 rowSelected:function(cell){
  console.log("Just to let you know, something got selected.");
 }
}
```
I now want to have the same table structure to be loaded on two div's:
```
$("#sequence-0-table").tabulator(tabulatorOptions);
$("#sequence-1-table").tabulator(tabulatorOptions);
```
But when I load the data, first table is loaded properly while the other table appears empty, no columns even. There is no console error. The data is fine. 
If instead of using `tabulatorOptions` json variable I paste the whole options all over again in the second table's declaration, then it loads properly.
Which means two tabulator tables don't like sharing the same options json variable.
Since objects/arrays are handled as pointers or something in JS, this trick doesn't work either:
```
var tabulatorOptions1 = tabulatorOptions;
$("#sequence-0-table").tabulator(tabulatorOptions);
$("#sequence-1-table").tabulator(tabulatorOptions1);
// nope, not buying it!
```
However, this ['deep copy' hack](https://stackoverflow.com/a/5164215/4355695) worked:
```
var copiedObject = jQuery.extend(true, {}, tabulatorOptions); // deep copy of a json object.
$("#sequence-0-table").tabulator(tabulatorOptions);
$("#sequence-1-table").tabulator(copiedObject);
```
I even added a `rowSelected` function definition and that got copied as well it seems with this. So I've done a workaround at my end, but just want to put it out there for the community if anyone else also faces same issue. Oli could look into this, but I've seen this quirk in other libraries too so I don't expect this to be taken as a bug. I'm happy I found an easy workaround and didn't have to re-write the same code (and make future edits twice, gasp!).

**Comment by olifolkerd** [comment]
Hey @answerquest 

That is because JavaScript passes objects by reference not by value, so when one table uses that object and makes changes to the config object they are also changed in the second table, and the fight between both tables trying to change the same object is what causes the issue.

A deep clone is a good solution to this.

Cheers

Oli
