### ISSUE TITLE
Multiple Groupheader Calc

### ISSUE THREAD

**Issue by dasio86** [olifolkerd/tabulator#946]
Hi,
i'm using the last released version (3.4)
I have a table with multiple GroupBy Field. I added a bottomCalc in the column definition and it work perfectly for the second level grouping. I need to know if exist a method to extend the Calc to the first colum level used for the grouping.

Below You can find my code:

`
$("#example-table").tabulator({
                    groupToggleElement:"header",
                    groupClosedShowCalcs:true,
                    groupBy:["tipologia","cliente"],
                    groupHeader:[
                        function(value, count, data){
                            
                                console.log(data);
                           
                            return value 
                        },
                        function(value, count, data){ 
                            console.log(data);
                            return value ;
                        },
                    ],
                    
                    height:'70%', 
                    layout:"fitColumns", 
                    columns:[ 
                        {title:"Tipologia", field:"tipologia", width:150},
                        {title:"Cliente", field:"cliente", align:"left"},
                        {title:"Descrizione", field:"descrizione"},
                        {title:"Data Fine", width:150,field:"data_fine", align:"center"},
                        {title:"Importo Infrastruttura", field:"imp_inf",  align:"center",formatter:'money',bottomCalc:'sum',formatterParams:{symbol:' €',symbolAfter :true,decimal:',',thousand:'.'}},
                        {title:"Importo Audio Video", field:"imp_av", align:"center",formatter:'money',bottomCalc:'sum',formatterParams:{symbol:' €',symbolAfter :true,decimal:',',thousand:'.'}},
                        {title:"Importo New Media", field:"imp_nm",  align:"center",formatter:'money',bottomCalc:'sum',formatterParams:{symbol:' €',symbolAfter :true,decimal:',',thousand:'.'}},
                        {title:"Importo Altro", field:"imp_altro", align:"center",formatter:'money',bottomCalc:'sum',formatterParams:{symbol:' €',symbolAfter :true,decimal:',',thousand:'.'}},
                        {title:"Importo Totale", field:"imp_totale", align:"center",formatter:'money',bottomCalc:'sum',formatterParams:{symbol:' €',symbolAfter :true,decimal:',',thousand:'.'}},
                    ],
                    
                });
`

**Comment by olifolkerd** [comment]
Hey @dasio86 

Im afraid that in nested groups the calculations are only shown on the bottom level.

It is on the roadmap to add this functionality to multiple group levels, so it will be added in a future release.

Cheers

Oli :)
