### ISSUE TITLE
Bug: Table scroll position moves on resize

### ISSUE THREAD

**Issue by seb303** [olifolkerd/tabulator#947]
When the table is resized (either horizontally or vertically), the scroll position creeps.  For some tables it creeps upwards, for some tables downwards, but always in the same direction for a particular table, until with enough resizing back and forth it eventually reaches the top or bottom of the table.

Expected behaviour is that the scroll position should stay the same when resizing.

Seems to happen on all the tables I have, but let me know if you need some specific example code.

Using v3.4.4

**Comment by olifolkerd** [comment]
Hey @seb303,

That definitely isn't intended behavior

Could you post a copy of your table constructor, also which browser are you using on which OS?

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @seb303 

Have you tried setting the line-height on the ***.tabulator-cell*** class instead of on the table itself?

Cheers

Oli

**Comment by seb303** [comment]
That fixes the problem on Internet Explorer, but doesn't help on Firefox.

In Firefox, the problem occurs even if the line-height is removed altogether.  The only thing that stops it is setting the top & bottom border of .tabulator-row to 0.

**Comment by olifolkerd** [comment]
Hey @seb303 

If you run standard Tabulator with no CSS changes at all are you still seeing the issue in firefox?

Cheers

Oli

**Comment by seb303** [comment]
Hi @olifolkerd 

With default CSS, there is no issue with Firefox.  The single CSS change which causes this issue is adding a top and/or bottom border to .tabulator-row

(This is needed in my use case so that the hover style can have a top and bottom bottom.  When not hovered, the top and bottom border are set to match the background colour of the cells.)

It also seems to be related to my high-DPI display.  If I change the Firefox zoom to 67%, which gives exactly 1 screen pixel to 1 CSS pixel, then the problem goes away.  You should be able to simulate the problem on a normal 1:1 display by setting the Firefox zoom to 150%.

Admittedly, a fairly narrow set of circumstances are triggering this, but it's still an annoying effect.

Seb

**Comment by olifolkerd** [comment]
Hey Seb,

could you confirm the exact css styling including selectors your are applying.

cheers

oli

**Comment by seb303** [comment]
There simplest case to reproduce the bug is the test code posted earlier, with the .tabulator line-height bits removed.  On a normal resolution screen with 1 screen pixel to 1 CSS pixel, you will also have to set the Firefox zoom to something other than 100% (try 150% which should emulate my display settings).

So the only CSS applied to .tabulator is this bit:

```
.tabulator .tabulator-row {
	border: solid #ffffff;	/* Removing the border */
	border-width: 1px 0;	/* stops the problem */
}
```

**Comment by olifolkerd** [comment]
Hey @seb303 

It appears to be down to a rounding error as a result of the scaling in the browser and windows poor handling high-DPI displays.

As this is a bit of an edge case, with custom modification to the CSS and a selection of changes to the browser setup im not going to look to fix it at the moment as it will not affect the vast majority of the user base.

When I start work on the 4.0 release i will see if any solutions emerge then.

If you find a solution, please feel free to submit a pull request.

Cheeers

Oli :)

**Comment by seb303** [comment]
Fair enough :)
I will have a play when I get a moment and see if I can find a solution.
Seb
