### ISSUE TITLE
how to get xlsx blob?

### ISSUE THREAD

**Issue by harishh1** [olifolkerd/tabulator#949]
hey @oli

i am creating web app i need the xlsx blob.what is the best way to get xlsx blob?

**Comment by olifolkerd** [comment]
Hey @harishh1 

Thanks for getting in touch,

Im afraid there is no way to do this at the moment without making some customisation to the download extension, which you are of course welcome to do, it can be found here:
`/src/js/extensions/download.js`

The blob is generated on line 77 of that file in the ***triggerDownload*** function. you would then need to follow the build instructions in the [Extension Documentation](http://tabulator.info/docs/3.4#extending)

I have added some new download callbacks to the roadmap for the 3.5 (estimated release april) release to give people access to this functionality if they want to handle downloads in their own way.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @harishh1 

Version 3.5 has now been released!
