### ISSUE TITLE
Ajax Pagination Loading help for Lloyd McDermott 

### ISSUE THREAD

**Issue by olifolkerd** [olifolkerd/tabulator#95]
Hi Lloyd,

I have created an issue for you on here so we can track the progress of its resolution.

so to sum up when you try and load data over AJAX you get a "Loading Error" dialog show up when you have over 35 rows.

**Comment by olifolkerd** [comment]
If you are getting a ***Load Error*** dialog that suggest that the AJAX call to the server failed.

I would suggest you use the developer console in you browser to have a look at the result of the request and see what response the server has given. there is probably a null value or incorrectly formatted variable somewhere. In chrome push f12 to open the console, then click on the networks tab, when once you make your ajax request it will show up in the list (only requests made after the console is open show up in the list).

Tabulator does have a ***dataLoadError*** callback that is called in the event of an error when loading data over AJAX, this is passed back some of the information from the request if you want to deal with errors programatically.

to use the callback you just need to bind it in the Tabulator constructor object with the rest of your setup options:
```js
$("#example-table").tabulator({
    columns:[...],
    dataLoadError:function(xhr, textStatus, errorThrown){
        //xhr - the XHR object
        //textStatus - error type
        //errorThrown - text portion of the HTTP status
    },
});
```

**Comment by mcderllo** [comment]
Thanks for the suggestion. You are brilliant. I redid the data.php file, not using Zend. After quite a few missteps, I eventually got it to work. It works very well indeed and quite fast. I have previously tried other techniques and by comparison, this is much faster.

**Comment by olifolkerd** [comment]
Great to hear!!!

If you need any other advice with your Tabulator feel free to create another issue on here and i can advise you on how to best resolve it.

Happy Tabulating!!!
