### ISSUE TITLE
Suspect memory leak when repeatedly 'setData' via ajax

### ISSUE THREAD

**Issue by ctlkkc** [olifolkerd/tabulator#953]
Hi there, 

Tabulator is a great tool and I like using it to build tables. But recently I found that there is a memory leak from my page when passing an array of hash objects to tabulator every second to build a table:

Initialization:
$("#example-table").tabulator("setData","s_c.pass", {}, ajaxConfig);
Repeat:
$("#example-table").tabulator("setData");

As followed the documentation, I found that the webpage is continuously consuming more memory after each ajax request completed. Using the chrome dev tool to profile the memory allocation, I  found new memory allocation at each "setData" action, which are similar allocation of same objects and arrays. The GC is working and can see the heap raises and drops, but the total gradually grows, something stayed in memory. 

Wondering if it is related to History option, I added 
    history:false, //not record table history
into the table's configuration, but things are the dame. 

Do I miss anything that result in the leak using ajax to setdata into the table repeatedly? 

Any one have similar experience or ideas? 

Thanks 
Charlie

**Comment by olifolkerd** [comment]
Hey Charlie,

Are you running the latest version? There was a memory leak in version 3.3 but it was fixed in the 3.4 release.

Cheers

Oli

**Comment by ctlkkc** [comment]
Hey Oli 

Perfect fix! There is no memory leak in version 3.4 as I tested. Performance even better.

Thank you
Charlie
