### ISSUE TITLE
Move Rows with Clicks not Dragging

### ISSUE THREAD

**Issue by xXmrotsXx** [olifolkerd/tabulator#954]
Hi Oli,

Is there a way to use the `movableRows` option somehow to allow clicking a start and end point for a row instead of dragging it around the table? Maybe it would be better to use `rowClicked `and build on that...

Thanks.

**Comment by xXmrotsXx** [comment]
I wrote my own **_SwapRows_** function and called it from within **_rowClicked_**... Hopefully I didn't reinvent the wheel...

**Comment by olifolkerd** [comment]
Hey @xXmrotsXx 

Sorry for not getting back to you sooner, had a bit of a manic few days.

Glad to hear you found a solution yourself, the is no inbuilt way to do this with Tabulator, but you could use the ***insertRow*** and ***deleteRow*** functions to achieve something similar.

Would you mind sharing your solution on here to help out others that may have the same issue?

Cheers

Oli :)
