### ISSUE TITLE
Question: Any plans for master/detail view (or nested grids)?

### ISSUE THREAD

**Issue by lrowleyUB** [olifolkerd/tabulator#956]
Hi Oli,

I have a requirement for a master/detail grid display where I need the ability to expand/collapse rows to show more information. Is there any plans to add this to Tabulator? This control would be my first choice to use in the project!

Thanks,
Laura

**Comment by lrowleyUB** [comment]
Also FYI - I am aware of the row grouping and will be evaluating this as a possibility. The detail portion of the requirement is comprehensive and I'm not sure if row grouping alone would satisfy it. I will keep you posted!

**Comment by olifolkerd** [comment]
Hey @lrowleyUB 

Thanks for getting in touch.

You would be able to do this using the ***rowFormatter*** callback, you can use it to insert other elements into the row, which in this case could be your details section.

Let me know if you need any further info.

Cheers

Oli :)

**Comment by lrowleyUB** [comment]
Excellent, thank you! I will look into this callback as well.

**Comment by olifolkerd** [comment]
There is now an example of nested tables [here](http://tabulator.info/examples/3.5#nested-tables)

**Comment by lrowleyUB** [comment]
Hi Oli,

Diving into this callback further, it appears that adding a nested table is adding two copies of the table. Here is my code:

```
var rowElement = row.getElement();
                var data = row.getData();
                var $divW = $('<div class="divAlertWrapper" style="display:none;"></div><br />');
                var $table = $('<table class="tblInsertAlerts" data-comcode="' + data.Comcode + '"><tr><td>TEST</td></tr></table>');

                $divW.append($table);              
                rowElement.append($divW);

                //check how many added
                $('.tblInsertAlerts[data-comcode="' + data.Comcode + '"]').each(function (i) {
                    console.log(data.Comcode + ' index ' + i);
                });
```

For example, if data.Comcode = 10, then the output in the console is always: 
10 index 0
10 index 1

Is this by design? My dynamic table has a class defined only (no id attribute), which makes it difficult to use as a selector when there are two tables of the same.

Thanks,
Laura

**Comment by lrowleyUB** [comment]
Oli I found the problem!  Looking at the source I noticed that the 2nd table was appending to the linebreak that was in my div wrapper:

` var $divW = $('<div class="divAlertWrapper" style="display:none;"></div>**<br />**');`

When I removed the line break - the table stopped duplicating. I'm assuming your rowFormatter is using line break for parsing/appending the new html. Just thought I would point this out to you so you can reproduce and address it.

Thanks,
Laura

**Comment by olifolkerd** [comment]
Hi Laura,

Tabulator does not process any line breaks at all.

The issue is in the way that you have created the ***divW*** element. You should only pass one top level element in that string otherwise it will be counted as an array of elements and therefore when you call the ***append*** function it will append the table element to both and initialise them both.

That isnt an Tabulator thing, that is just how jQuery works im afraid.

I would be happy to suggest a solution for you if needed.

Cheers

Oli :)

**Comment by lrowleyUB** [comment]
Ahh yes, so sorry!! I should've picked up on this. I changed it like so and all is good:

```
var $divW = $('<div class="divAlertWrapper" style="display:none;"><br /></div>');
$divW.prepend($table);
```

My apologies again!

**Comment by olifolkerd** [comment]
@lrowleyUB 

No need to apologise, every day is a school day.

Glad to hear you got it working.

Cheers

Oli :)
