### ISSUE TITLE
On resizing Window getting  redraw error on console in Tabulator grid

### ISSUE THREAD

**Issue by Munesh101** [olifolkerd/tabulator#957]
Uncaught Error: cannot call methods on tabulator prior to initialization; attempted to call method 'redraw'
 at Function.error (/scripts/jquery-1.9.1.js:507:9)
    at HTMLDivElement.<anonymous> (/Content/JQueryUI/js/jquery-ui-1.10.3.js:487:15)
    at Function.each (/scripts/jquery-1.9.1.js:648:23)
    at init.each (/scripts/jquery-1.9.1.js:270:17)
    at init.$.fn.(anonymous function) [as tabulator] (/Content/JQueryUI/js/jquery-ui-1.10.3.js:483:9)
    at /Content/tabulator/js/tabulator.js:15170:27
    at dispatch (/scripts/jquery-1.9.1.js:3074:9)
    at elemData.handle (/scripts/jquery-1.9.1.js:2750:28)

**Comment by olifolkerd** [comment]
Hey @Munesh101 

I would be happy to help you out there, could you answer a few questions:

What version of Tabulator are you using?
Which browser are you using?
Could you post a copy of you table constructor?

That error looks like it is trying to redraw a table that no longer exists, have you deleted a table at any point?

Cheers

Oli

**Comment by Munesh101** [comment]
I am using 3.4.4 version.
Browser Google Chrome.
It was working fine on version  3.3 but when i update  version to 3.4.4 getting this error.
 this.tableOptions = {
                layout: "fitColumns",
                responsiveLayout: true,
                pagination:"local",
                ajaxURL: "/User/GetUser",
                tooltip: true,
                resizableColumns: true,
                ajaxParams: {
                     pageSize: 20, pageNum: 1,
                },
                paginationElement: $("#pagination-element"),
                paginationSize: 20,
                ajaxResponse: (url, params, result) => {
                    
                         for (var userItem of result.Items) {
                            var userModel = new UserModel().mapFromDto(userItem);
                            userModel.userProfileUrl(String.format(this.configuration.userDetailViewUrl, userItem.Id));
                            this.userList.push(userModel);
                        }
                        this.totalResults(result.TotalItemCount);
                        this.isLoading(false);
                    $("#user-table").tabulator("setSort", "name", "asc");
                    return this.userList;
                },

/////////////
 $("#user-table").tabulator("setData", userList)
 $("#user-table").tabulator("redraw", true);

**Comment by olifolkerd** [comment]
Hey @Munesh101 

Can i ask why you are redrawing the table after setting the data? that is not necessary.

You also seem to be configuring the table to use remote ajax data and then setting the data to a local data array with the ***setData*** function, that seems confusing. if you want to trigger Tabulator to request data from the ajax url, you can call the ***setData*** function without any additional arguments:
```js
$("#example-table").tabulator("setData");
```


The error is being caused because you are calling ***setData*** and ***redraw*** on a table that does not exist yet. you have defined the tables constructor object, but nowhere in your code above are you actually creating the table.

Cheers

Oli

**Comment by Munesh101** [comment]
Thanks Oli for your reply.
