### ISSUE TITLE
Question: Attach tabulator to pre-built tabulator HTML

### ISSUE THREAD

**Issue by ProxiBlue** [olifolkerd/tabulator#958]
Hello,

Loving tabulator.

As subject suggests, I am looking for a way to attach tabulator functionality to an existing, prebuilt version of the tabulator HTML.

Basically, my client is not happy to have the page render initially without the product grid data. Although tabulator supports slurping in a table, the data is complex, and there is a noticed delay between original table elements in DOM, and then tabulator replacing with its own output.

So, what I did was to create the exact same HTML, generated by PHP, as the initial page load. So it is already tabulator generated HTML (divs)
I ajax in the tabulator data arry that matches that display.

If I attach tabulator to that container element, will it still generate (and replace) teh DOM elements? So essentially recreated the same?
Is there a way to attach and not generate?

I hope that is clear.

TIA

**Comment by olifolkerd** [comment]
Hey @ProxiBlue 

Are you sure you are using the Virtual DOM rendering mode, there should be no delay in displaying the table upon load if this is enabled.

Usually a slow render suggest that the table is trying to render a large number of rows in standard render mode which is very slow.

Have a look at the detailed explanation of the rendering modes in the [Quick Start Guide](http://tabulator.info/quickstart/3.4) for more information.

Also you should make sure you are running on the latest version of Tabulator.

you can also instantiate the table as soon as the tabulator and jQuery sources have loaded, you do not need to wait for the document to be "ready" if that is also causing you delay.

You will notice that the table on the home page of http://tabulator.info/ loads instantly with no delay

I hope that is of some help

Cheers

Oli :)

**Comment by ProxiBlue** [comment]
Yep, all of the above is done, and very sure using Virtual DOM.

I suspect something else is causing a block with js executing (this is a magento website, so there is a lot going on)

Busy investigating.

So, just to clarify, there is no option to not need to 'repaint' on initial attach?

**Comment by ProxiBlue** [comment]
Yes, there was some blocking JS waiting for a response, which was blocking all other js code on page, issue solved.
