### ISSUE TITLE
How to include a footer with spans?

### ISSUE THREAD

**Issue by E3V3A** [olifolkerd/tabulator#959]
I tried to follow the example with:

```js
$("#example-table").tabulator({
    footerElement:$("<div class='tabulator-footer'><button>Custom Button</button></div>"); //set custom table footer with custom button
});
```

and replace the button with my own `<span>` elements to render a type of colored legend, like this:
```js
            footerElement:$("<div class='tabulator-footer'>" +
                                "<span style='color:#33D9FF;'>▉</span> = To" +
                                "<span style='color:#0ff;'>▉</span> = From" +
                                "<span style='color:#f00;'>▉</span> = Emergency" +
                                "<span style='color:#f0f;'>▉</span> = watchList</br>" +
                                "<span style='color:#0f0;'>▉</span> = Military/Gov" +
                                "<span style='color:#ffa500;'>▉</span> = UFO" +
                             "</div>");
```

But it didn't work, and there were no error messages anywhere. The table just didn't render. 
I tried to insert it [here](https://github.com/E3V3A/MMM-FlightsAbove/blob/b1076f7790c41574c22892c37095615b073cbc50/MMM-FlightsAbove.js#L257). 

**What am I missing?**

**Comment by olifolkerd** [comment]
Hey @E3V3A 

It looks like you have a semi-colon at the end of your ***footerElement*** defintion, this should be a comma as it is inside an object.

Let me know if that helps.

Cheers

Oli :)

**Comment by E3V3A** [comment]
Thanks! That was it!  :) 
*Jesus! One sand grain ruining en entire empire!*

![pict](https://raw.githubusercontent.com/E3V3A/MMM-FlightsAbove/master/images/FlightsAbove_footer.png)
