### ISSUE TITLE
example.html file not loading examples on iPad

### ISSUE THREAD

**Issue by kurtknippschild** [olifolkerd/tabulator#96]
When i open the Examples-Website on iPad with Safari no Examples show.
Is this a general problem with Safari and iPad?

**Comment by olifolkerd** [comment]
Tabulator does work with both Safari and iPad, if you view the examples page of the website you will see it in action:
http://olifolkerd.github.io/tabulator/examples/

there does however seem to be an issue with the examples file that ships with the tabulator.js library. i will have a look into that for you now and let you know when it is fixed

**Comment by olifolkerd** [comment]
Upon inspection of the **examples.html** file i cant find any issues, it seems to work correctly on my test iPad. sometimes if the network connection is slow it can fail to render the tabled quickly enough, if you refresh the page it should be fine.

could you try refreshing the page and let me know if yo are still running into issues.

what version of ios or safari are you running?

**Comment by kurtknippschild** [comment]
Hi Oli,

i think that is a problem of the Version.
We have two iPads one is older with Version 9.3.5.
On this, the Examples Page does not work.
On the other iPad with Version 10.0.2 the page works.

Sorry, but i'm testing only one the older iPad.

MG Kurt


Mit freundlichen Grüßen
 
Kurt Knippschild
 
Ingenieurbüro
Kurt Knippschild 
Am Kränzenberg 17
64646 Heppenheim
 
Telefon:            +49 6252 670610
Mobil:              +49 170 3851198
Telefax:            +49 6252 670611
EMail:              kurt@ingenieurbuero-knippschild.de
Internet:            www.ingenieurbuero-knippschild.de

**Comment by olifolkerd** [comment]
Thanks for sending over the version no, it should still work on that so i will have a test on that version tomorrow and get to the bottom of the problem for you

**Comment by kurtknippschild** [comment]
Hi Oli,

is there an example for Column Groups with more than one row for the data?
See the example:

Thank you in advance.

MG Kurt
mit freundlichen Grüßen
 
Kurt Knippschild
 
Kurt Knippschild
Am Kränzenberg 17
64646 Heppenheim
 
Telefon:            +49 6252 9679817
Mobil:              +49 170 3851198
Telefax:            +49 6252 670611
EMail:              kurt@knippschilds.de
<mailto:kurt@ingenieurbuero-knippschild.de>
Internet:            www.knippschilds.de
<http://www.ingenieurbuero-knippschild.de/>

Von:  Oli Folkerd <notifications@github.com>
Antworten an:  olifolkerd/tabulator
<reply+015cbfe8d106b8fabbd03a2b26ca73e97ee1700a472995c692cf000000011445eb239
2a169ce0b53d857@reply.github.com>
Datum:  Freitag, 18. November 2016 um 00:03
An:  olifolkerd/tabulator <tabulator@noreply.github.com>
Cc:  Kurt Knippschild <kurt@knippschilds.de>, Author
<author@noreply.github.com>
Betreff:  Re: [olifolkerd/tabulator] example.html file not loading examples
on iPad (#96)

**Comment by olifolkerd** [comment]
Im not sure i follow you. an interactive example of column grouping can be found [here](http://olifolkerd.github.io/tabulator/examples/#column-groups)

Are you asking how to nest column groupings so you can have groups within groups?

**Comment by kurtknippschild** [comment]
Hi Oli,

thanks for your answer.

In my webapplication im-suite.de <http://im-suite.de>  there are three forms
of tables.

The first form is a normal table with one table-header and one row for for
the data. This works great with your Plugin.
The second form is a table with more then one table-header and more then one
row for the data. The second , third and fourth rows data are all multilines
(formatter:³textarea").
The third form is a table with two table-header and the one row for data of
the first header and at least one row for the data of the second header.
But the data for the second header can more then one row.

In this example there are a list of the user of the application.
The first row for every user are the user-data and in the second row the
adress-data of the user.
Every user can more then one adresses (Privat-adress, business-adress and so
on).

I hope you unterstand my problem and you have an example for the second and
third table-form.

Thanks in advance.

MG Kurt
mit freundlichen Grüßen
 
Kurt Knippschild
 
Kurt Knippschild
Am Kränzenberg 17
64646 Heppenheim
 
Telefon:            +49 6252 9679817
Mobil:              +49 170 3851198
Telefax:            +49 6252 670611
EMail:              kurt@knippschilds.de
<mailto:kurt@ingenieurbuero-knippschild.de>
Internet:            www.knippschilds.de
<http://www.ingenieurbuero-knippschild.de/>

Von:  Oli Folkerd <notifications@github.com>
Antworten an:  olifolkerd/tabulator
<reply+015cbfe83f1b9e943d2d4fea5d3283d0a8b4636190304b1e92cf00000001144b15519
2a169ce0b53d857@reply.github.com>
Datum:  Montag, 21. November 2016 um 22:04
An:  olifolkerd/tabulator <tabulator@noreply.github.com>
Cc:  Kurt Knippschild <kurt@knippschilds.de>, Author
<author@noreply.github.com>
Betreff:  Re: [olifolkerd/tabulator] example.html file not loading examples
on iPad (#96)

**Comment by olifolkerd** [comment]
Im afraid i still dont follow, you can have as many rows of data as you like in a table.

Could you perhaps sketch me out they layout you are after with a diagram for each type of table with some labels on it, then i can show you how to make them.

Cheers

Oli

**Comment by kurtknippschild** [comment]
Hi Oli,

i send you for each table-Form a html-file and on excel-file with both
sheets.
For the second Form i have one array with one ore more records of the
termin-data.
For the third table-form i have two Arrays.
in the first array are the user-records and in the second array are the
adress-records.
I iterate over the first array and write the first row and then iterate over
the second array und search for the adresses from the user

I hope this helps to unterstand my problem.

MG Kurt
mit freundlichen Grüßen
 
Kurt Knippschild
 
Kurt Knippschild
Am Kränzenberg 17
64646 Heppenheim
 
Telefon:            +49 6252 9679817
Mobil:              +49 170 3851198
Telefax:            +49 6252 670611
EMail:              kurt@knippschilds.de
<mailto:kurt@ingenieurbuero-knippschild.de>
Internet:            www.knippschilds.de
<http://www.ingenieurbuero-knippschild.de/>

Von:  Oli Folkerd <notifications@github.com>
Antworten an:  olifolkerd/tabulator
<reply+015cbfe895d9910ec268ec353e0d623b3159cdf87f245c6492cf00000001144c66ad9
2a169ce0b53d857@reply.github.com>
Datum:  Dienstag, 22. November 2016 um 22:03
An:  olifolkerd/tabulator <tabulator@noreply.github.com>
Cc:  Kurt Knippschild <kurt@knippschilds.de>, Author
<author@noreply.github.com>
Betreff:  Re: [olifolkerd/tabulator] example.html file not loading examples
on iPad (#96)

**Comment by olifolkerd** [comment]
I cant see any attached file, if you are going to add attachments to the git hub issue, you will need to do it through the github website not via an email response im afraid.

**Comment by kurtknippschild** [comment]
Hi Oli,

i have generate a new issue with the attachments.

MG Kurt
mit freundlichen Grüßen
 
Kurt Knippschild
 
Kurt Knippschild
Am Kränzenberg 17
64646 Heppenheim
 
Telefon:            +49 6252 9679817
Mobil:              +49 170 3851198
Telefax:            +49 6252 670611
EMail:              kurt@knippschilds.de
<mailto:kurt@ingenieurbuero-knippschild.de>
Internet:            www.knippschilds.de
<http://www.ingenieurbuero-knippschild.de/>

Von:  Oli Folkerd <notifications@github.com>
Antworten an:  olifolkerd/tabulator
<reply+015cbfe8e734f95e6497e45495f29f516d3f576f9594873392cf00000001144da24c9
2a169ce0b53d857@reply.github.com>
Datum:  Mittwoch, 23. November 2016 um 20:30
An:  olifolkerd/tabulator <tabulator@noreply.github.com>
Cc:  Kurt Knippschild <kurt@knippschilds.de>, Author
<author@noreply.github.com>
Betreff:  Re: [olifolkerd/tabulator] example.html file not loading examples
on iPad (#96)

**Comment by olifolkerd** [comment]
perfect! i will post an example on the new issue shortly
