### ISSUE TITLE
Is it possible to make cells immediately editable? (preventing two clicks)

### ISSUE THREAD

**Issue by davidawad** [olifolkerd/tabulator#960]
Hey oli, thanks for answering all the questions on the issues. I think you're doing a great job. 

I unfortunately have another question for you. Take a look at the sample editable table on the documentation [here](http://tabulator.info/examples/3.4#editable), it takes two clicks to edit it. 

Meaning, if I want to edit a cell, I have to click on the cell, and then I have to click on it again to make my edit. Take the example of editing a user from male to female, I'd have to click on the cell once to bring it into focus, at which point I click again to get the editable menu. 

Is it possible to automatically set the focus to wherever in the tabulator the mouse is? That way I'd only have to click one time to begin editing my data? 

Thanks for your help.

**Comment by davidawad** [comment]
I could submit a PR for this if you think it would help. It's a relatively simple move in jquery ui to watch the focus I'm guessing.

**Comment by olifolkerd** [comment]
I don't know what u mean there. Tabulator does use focus. You just can't trigger the drop-down on a select to show without user action.

I would love to see it if you have a solution. But I would advise against any watchers on the tabulator element. If you want to target a cell you should use the formatter

**Comment by davidawad** [comment]
Here are screenshots from my specific use case where I will demonstrate what I mean.

Take a look at the "event type" column. In that column there is an editor that I've written. 

Before interacting with the table this is what that cell looks like. 

<img width="759" alt="screen shot 2018-03-14 at 2 48 23 pm" src="https://user-images.githubusercontent.com/4019054/37424466-e774edcc-2796-11e8-89a8-77ccc884c529.png">

#### after first click

<img width="733" alt="screen shot 2018-03-14 at 2 48 32 pm" src="https://user-images.githubusercontent.com/4019054/37424467-e7850626-2796-11e8-8f4c-b46e1cebc3a9.png">

#### after second click 

<img width="728" alt="screen shot 2018-03-14 at 2 48 40 pm" src="https://user-images.githubusercontent.com/4019054/37424468-e793759e-2796-11e8-991d-c2f99d9e485d.png">


What I'm suggesting here is that I'd like the table to always appear the way that it does after that first click. 

Because otherwise it requires three clicks to change this value. One to bring the cell in focus, another to actually trigger the drop down, and then a third to select the value. 


Are you saying I can use a formatter to show the editor by default?

**Comment by olifolkerd** [comment]
Hey @davidawad 

Thanks for the image, yes you are correct, im saying you can use a custom formatter to show the select element by default, that way when a user clicks on the already existing element it will trigger the drop-down.

Using an editor it is impossible to create a select box and open the drop-down with a single click, Browser security means that you can only programtically focus on the select element, not trigger its drop down. 

As the editor creates and focuses on the select element in the first click, you cannot trigger the drop-down to appear, that can only happen as the result of user interaction with the select element after it is created, which is why it works that way. Im afraid there is no change i could make to alter that, it is an inherent restriction put in place on all modern web browsers.

Cheers

Oli :)

**Comment by davidawad** [comment]
Could you potentially give me an example or refer me to an example of how this would work? 

Thanks.

**Comment by olifolkerd** [comment]
Hey @davidawad 

no problem. so below is a simplified version of the select editor changed into a formatter that takes its option list from the ***formatterParams*** property:

```js
// create custom formatter
var selectFormatter = function(cell, formatterParams){
	//create and style select
	var select = $("<select><select/>");

		//add options elements
		formatterParams.forEach(function(item){
			select.append($("<option></option>").attr("value", item).text(item));
		});

	//define styling
	select.css({
		"padding":"4px",
		"width":"100%",
		"box-sizing":"border-box",
		"font-family":"",
	})

	//set cell value
	.val(cell.getValue())


	//submit new value on blur
	select.on("change blur", function (e) {
		cell.setValue(select.val());
	});

	//submit new value on enter
	select.on("keydown", function (e) {
		if (e.keyCode === 13) {
			cell.setValue(select.val());
		}
	});

	return select;
}

//in column definition assign formatter and define options 
{title:"Gender", field:"gender", formatter:selectFormatter, formatterParams:["male", "female"]}
```

Let me know if that helps,

Cheers

Oli :)

**Comment by lehoanglu0ng** [comment]
Hi Oli,

I used Semantic-UI dropdown class instead of html select-option. But, the dropdown menu is clipped. Could you check this, please?
![screenshot 22](https://user-images.githubusercontent.com/22902128/39504211-3f59246c-4df4-11e8-8c27-0020df35fabc.png)

**Comment by lehoanglu0ng** [comment]
Hi again,

I fixed this by changing overflow to visible for .tabulator, .tabulator-tableHolder and .tabulator-cell.
