### ISSUE TITLE
Question: Remote pagination and first page data

### ISSUE THREAD

**Issue by lgraziani2712** [olifolkerd/tabulator#961]
Hello!

Is it possible to hidrate the table with data on the initial render without querying an ajax when the pagination is remote?

E.g.

```js
$("#table").tabulator({
  pagination: 'remote',
  // Ajax config
  initialPaginationData: {
    last_page: 15,
    data: [/* data */],
  },
});
```

Thank you!

**Comment by olifolkerd** [comment]
Hey @lgraziani2712 

Im afraid this isnt possible, in remote pagination mode the table will only load data from the remote source.

Cheers

Oli
