### ISSUE TITLE
Keyboard navigation

### ISSUE THREAD

**Issue by leonardorame** [olifolkerd/tabulator#962]
Hi Oli, I would like to be able to move the selected row with the UP and DOWN keyboard arrows. I noticed this work when cell editing is enabled,but not with row selection.

Is there a way to workaround this?.

**Comment by olifolkerd** [comment]
Hey @leonardorame 

The [Keybindings Extension](http://tabulator.info/docs/3.4#keybindings) that is included with tabulator lets you map behaviours to specific keys.

Could you confirm the exact behaviour you are after?

Cheers

Oli :)

**Comment by leonardorame** [comment]
The exact behavior I want is let the user move the row selector up or down by using the keyboard, just like many applications out there, like Ms Outlook for example.

When the user press Down Key, the selector should move down one row, when he press Up Key, the selector should move up one row.

Currently, when selection is enabled, if I press down key, the whole page is scrolled down, but not the row selector.

**Comment by olifolkerd** [comment]
does your table only allow one element to be selected?

**Comment by leonardorame** [comment]
Yes

**Comment by olifolkerd** [comment]
Great! so there are a few things you would need to do to achieve this.

### Record Currently Selected Rows
First of all you would need to record the currently selected row somewhere outside of Tabulator, lets say in a global variable called ***currentSelection***, you could do this using the ***rowSelectionChanged*** callback.

### Create Keybinding Actions
You would then need to add a couple of new actions to the keybindings extension by [Extending It](http://tabulator.info/docs/3.4#extension-keybindings), these actions, lets call them ***selectNext*** and ***selectPrev*** would need to find the next/prev row in the table, you could use the ***getRows*** function to get an array of all the row components and find the position in the array to get the next/prev row. if a row is available trigger the ***select*** function on the row.

### Bind Actions to Key Combinations
You would the need to bind your new actions to the up and down keys, info on how to do that can be found in the [Keybindings Documentation](http://tabulator.info/docs/3.4#keybindings)

Let me know if that helps,

Cheers

Oli :)

**Comment by leonardorame** [comment]
Thanks!, I'll try this.

**Comment by olifolkerd** [comment]
In fact i have just through of a way to remove the first step, i have just updated the instructions to make it even simpler
