### ISSUE TITLE
Can I rorate the column label 45 or 90 degrees? 

### ISSUE THREAD

**Issue by AndrewHutcheson** [olifolkerd/tabulator#964]
I have a lot of check boxes so it would help if my header (which is much wider than a checkbox) could be angled so that the column width could be narrower.

Also, a related issue is how to I repeat column headers when grouping data? (this would be for horizontal headers, not rotated ones).

**Comment by olifolkerd** [comment]
Hey @AndrewHutcheson 

There is no inbuilt way to do this, but you can probably achieve it with a bit of CSS by using a `transform:rotate(45deg)` on the ***.tabulator-col-title*** class, you will probably need a few other CSS tweaks to increase the height of the column headers and to correctly align the rotated titles.

What do you mean by "repeat the headers", could you give an example.

Cheers

Oli
