### ISSUE TITLE
Data Loading Error - Unable to process data due to invalid data type 

### ISSUE THREAD

**Issue by vietvunguyen** [olifolkerd/tabulator#965]
Hello,
I am getting this err `Data Loading Error - Unable to process data due to invalid data type 
Expecting: array 
Received:  object 
Data:      {condition: "mining", version: "1.3.0", driver: "amdgpu", miner: "claymore", gpus: "10", …`

Here my JSON data:
```
 {
  "rigs": {
    "7e4533": {
      "condition": "just_booted",
      "version": "1.3.0",
      "driver": "amdgpu",
      "miner": "claymore",
      "gpus": "10",
      "miner_instance": "10",
      "miner_hashes": "30.30 30.24 30.29 30.30 30.24 30.24 30.29 30.30 30.23 30.22
    }
  },
  "total_hash": 302.65,
}
```
here my js file:

```
$("#data-table").tabulator({
    ajaxResponse:function(url, params, response){
            return response.rigs["7e4533"];
    },
    height:205, 
    layout:"fitColumns", 
    columns:[ 
        {title:"Hash rate", field:"rigs.'6e8353'.miner_hashes"},
    ],
   
});
var data = {} //the above data
$("#data-table").tabulator("setData", data);```

Please help. Thank you in advance.

**Comment by olifolkerd** [comment]
Hey @vietvunguyen 

Tabulator expects an array of objects, one for each row.

It looks like you are only passing in a single object. if you could explain what your are hoping to display from your data i can point you in the right direction.

Cheers

Oli

**Comment by vietvunguyen** [comment]
@olifolkerd Thank your for the prompt reply,

I want to display all the child property of 7e4533 to my table. 

My table will have 7 collumns: condition, version, miner, gpus, miner_instance and miner_hashes.

**Comment by olifolkerd** [comment]
Hey @vietvunguyen 

Are you saying you just want one row of data in the table?

**Comment by vietvunguyen** [comment]
@olifolkerd It is actually more complicated, but at this stage I just want 1 row.

**Comment by olifolkerd** [comment]
Hey @vietvunguyen 

See my above answer with how you need to present the data to tabulator to get one row

Cheers

Oli

**Comment by vietvunguyen** [comment]
@olifolkerd Thank you so much. That really helps.
