### ISSUE TITLE
Too much recursion error from v3.4.3

### ISSUE THREAD

**Issue by lgraziani2712** [olifolkerd/tabulator#966]
Hello!

When the TAB key is pressed while editing an input and the validation fails, tabulator enters in an infinite loop.

Here is a pen with the steps to reproduce the error: https://codepen.io/lgraziani/pen/EEyxdY

I think this line creates the infinite loop:

https://github.com/olifolkerd/tabulator/blob/f88eb7262b315c3e8e14b21fca40a79b46b06a5a/src/js/extensions/edit.js#L113-L117

Thank you! Luciano.

**Comment by olifolkerd** [comment]
Hey @lgraziani2712 

is this still the case with the latest release 3.4.5?

Cheers

Oli

**Comment by lgraziani2712** [comment]
Yes, it is. The codepen has the v3.4.5.

Luciano.

**Comment by olifolkerd** [comment]
It seems to work fine for me in the code pen,

what are the exact steps to replicate the issue and what browser are you using?

Cheers

Oli :)

**Comment by lgraziani2712** [comment]
Oh... 

The steps are written in the CSS section of the pen.

Browser: Firefox 60.0b3

**Comment by olifolkerd** [comment]
Hey @lgraziani2712 

It appears to be an issue that affects firefox, i will look into it in more details tomorrow.

Thanks for letting me know

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @lgraziani2712 

I have just pushed a fix to the master branch that should resolve this and a few other editor issues

Cheers

Oli :)
