### ISSUE TITLE
Minor doc bug

### ISSUE THREAD

**Issue by seb303** [olifolkerd/tabulator#967]
From the docs:

```
$("#example-table").tabulator({
    tooltips:function(cell){
        //cell - cell component

        //function should return a string for the tooltip of false to hide the tooltip
        return  cell.getColumn().getField() + " - " + cell.getValue(); //return cells "field - value";
    },
});
```

But actually returning false displays a tooltip of "false".
Returning an empty string works however.

**Comment by seb303** [comment]
Sorry, should point out that I'm actually defining a function for the "tooltip" parameter in the columns definition.  Maybe the behaviour is different for a global tooltips function.

**Comment by olifolkerd** [comment]
Hey @seb303 

Thanks for the info, i will have a look into that one.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @seb303 

I have updated the functionality of tooltip functions to match the documentation and not display when false.

I have pushed the update to the 3.5 branch and will include it in that release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @seb303 

Version 3.5 has now been released!
