### ISSUE TITLE
page number input

### ISSUE THREAD

**Issue by jfmarasigan** [olifolkerd/tabulator#968]
hi, thanks for the plugin, your docs are really easy to follow.

I have a few questions though
1. Does tabulator have a feature for inputting page numbers instead of having a "list" of buttons indicating page numbers?
2. Does tabluator have a feature for creating child columns? I plan to use several columns then apply a "parent" column so that when I sort, I can just click the "parent" column applying either ascending or descending functions sent to the server.

**Comment by olifolkerd** [comment]
Hey @jfmarasigan 

Thanks for getting in touch.

You could easily implement that yourself and have an input or select element that triggers the ***setPage*** function on change. If you wanted to hide the existing controls you could always use CSS to set the ***.tabulator-paginator*** class to `display:none`

Tabulator has [Column Group](http://localhost:8080/examples/3.4#column-groups) functionality which combined with the ***headerClick*** callback should do what you are after.

Cheers

Oli :)
