### ISSUE TITLE
Very slow on big data

### ISSUE THREAD

**Issue by Tpona** [olifolkerd/tabulator#97]
Hi all!

I try to load upto 3 000 rows and it very slow for me (~ 12 seconds).
Maybe exists another, more fast way of rendering?

Thx!

**Comment by olifolkerd** [comment]
Hi Tpona,

For large data sets you should set the ***progressiveRender*** option to ***true***. This will cause tabulator to render elements as you scroll to them rather than all in one go. you can set this option in your constructor object:

```js
$("#example-table").tabulator({
    progressiveRender:true, //enable progressive rendering
    columns:[
        ...
    ]
});
```

Full documentation on the Progressive Render functionality can be found [here](http://olifolkerd.github.io/tabulator/docs/#progressive-render)

**Comment by olifolkerd** [comment]
Has this helped at all?

**Comment by Tpona** [comment]
Hi, olifolkerd! And thx for answer!
But, this solution, not exactly help for me.
I need fast scrolling, but with progressiveRender i have some delay when i scroll table.
You did not think about use virtual dom for rendering? 
It seems to me that it would be faster.

**Comment by olifolkerd** [comment]
Hey,

If you want to speed up the progressive render try tweaking the ***progressiveRenderSize*** and ***progressiveRenderMargin*** values to meet your needs. 

```js
$("#example-table").tabulator({
    progressiveRender:true, //enable progressive rendering
    progressiveRenderSize:500, //sets the number of rows to render per block (default = 20)
    progressiveRenderMargin:350, //distance in px before end of scroll before progressive render is triggered (default = 200)
});
```

I have used it on tabled of up to 10,000 rows without any scroll loading delay, what browser are you using? how many columns are there in your data?

I am planning some tweaks to the progressive system in this months release, to allow for real-time ajax pagination based progressive rendering, and to keep only the visible rows rendered. this should speed things up considerably for you, so hold on for a few weeks and i will have the changes in.

Cheers

Oli

**Comment by aswzen** [comment]
rendered 10000 rows at once, got lagging when loading and scrolling.
but when using progressiveRender:true its fine to scroll (only a bit lagging at first)

chrome 54

**Comment by olifolkerd** [comment]
Thanks for letting me know the browser info.

You should always use progressive rending for large data sets otherwise it will be slow as it will try and render all the data first.

i should have the updates to progressive rendering in soon so it will be even more responsive!

**Comment by olifolkerd** [comment]
You will be happy to hear that progressive rendering with remote ajax pagination is now available:

you can now load individual pages of data automatically as the user scrolls through the table:

```js
$("#example-table").tabulator({
    progressiveRender:"remote", //enable progressive rendering
    ajaxURL:"/data/page", //set the ajax URL
});
```

Full documentation on this feature can be found [here](http://olifolkerd.github.io/tabulator/docs/#progressive-ajax)
