### ISSUE TITLE
Tabulator does not allow options to be set after initialization 

### ISSUE THREAD

**Issue by OsemaPatron** [olifolkerd/tabulator#970]
Hello sir 
I have this problem . My application works just fine I am sending lines each 1ms from my server to the tabulator and it is receiving each line just fine . But for each line it display that massage "Tabulator does not allow options to be set after initialization " in the consol and i think it is slowing down my browser espacially that some times i have to load over 10000 line sent by the server . 
Could you please tell me how to fix it ?

**Comment by olifolkerd** [comment]
Hey @OsemaPatron 

That sounds like you are trying to use the ***options*** function to set an option after the table has been initialized. Tabulator does not allow this, which is why you are getting the error.

If you could post a copy of your table constructor along with a description of what you are trying to achieve I should be able to point you in the right direction to fix the issue.

Cheers

Oli :)

**Comment by OsemaPatron** [comment]
OK here is my constructor and at each time i am loading new line to table by "addRow"
`$( document ).ready(function() {     
  $("#Tabulator").tabulator({
        virtualDomBuffer:1000,
        layout:"fitColumns",
        selectable:true, 
               
        columns:
        [
        {title:"ID", field:"id",headerFilter:"input", width:60},
        {title:"TimeStamp", field:"TimeStamp",headerFilter:"input", width:200},
        {title:"Tcid", field:"Tcid", align:"left",headerFilter:"input" },
        {title:"Direction", field:"Direction", align:"left",headerFilter:"input" },
        {title:"Action", field:"Action",headerFilter:"input"},
        {title:"ME class name", field:"MEName",headerFilter:"input"},
        {title:"ME class number", field:"MEClasseNumber", sorter:"date", align:"center",headerFilter:"input", width:60},
        {title:"ME ID", field:"ManagedIdentityIDDecimal", sorter:"date", align:"center",headerFilter:"input", width:60},
        {title:"Result(only reply)", field:"Result", sorter:"date", align:"center",headerFilter:"input"},
        ],
 $("#Tabulator").tabulator("addRow",{id:i, TimeStamp:TimeStamp, Tcid:Tcid, Action:MT,MEName:FieldName,Direction:Direction, MEClasseNumber:ManagedIdentityNameFieldDecimal });
 }); `

**Comment by olifolkerd** [comment]
Hey @OsemaPatron 

Your ***addRow*** function seems to be inside your table constructor, it should be outside of it.

```js
$( document ).ready(function() {     
  $("#Tabulator").tabulator({
        virtualDomBuffer:1000,
        layout:"fitColumns",
        selectable:true, 
        columns:
        [
            {title:"ID", field:"id",headerFilter:"input", width:60},
            {title:"TimeStamp", field:"TimeStamp",headerFilter:"input", width:200},
            {title:"Tcid", field:"Tcid", align:"left",headerFilter:"input" },
            {title:"Direction", field:"Direction", align:"left",headerFilter:"input" },
            {title:"Action", field:"Action",headerFilter:"input"},
            {title:"ME class name", field:"MEName",headerFilter:"input"},
            {title:"ME class number", field:"MEClasseNumber", sorter:"date", align:"center",headerFilter:"input", width:60},
            {title:"ME ID", field:"ManagedIdentityIDDecimal", sorter:"date", align:"center",headerFilter:"input", width:60},
            {title:"Result(only reply)", field:"Result", sorter:"date", align:"center",headerFilter:"input"},
        ],
   });

  //addRow function outside constructor object
  $("#Tabulator").tabulator("addRow",{id:i, TimeStamp:TimeStamp, Tcid:Tcid, Action:MT,MEName:FieldName,Direction:Direction, MEClasseNumber:ManagedIdentityNameFieldDecimal });
});
```

It would also be more efficient to pass in all the data at once using the ***setData*** function, that way the table would only need to be rendered once. By calling ***addRow*** 1000's of times, you are redawing the table 1000's of times which is going to be slowing things down massively. 

If you are loading data from the server, Tabulator has built-in ajax request functionality, more information on this can be found in the [Ajax Documentation](http://tabulator.info/docs/3.4#ajax)

You also need to make sure your table has a height set on it to enable the Virtual DOM, otherwise it will render in standard mode which is very slow for large data sets,

Let me know if that helps,

Cheers

Oli :)

**Comment by OsemaPatron** [comment]
Sorry my bad . Because i had to cut too many lines of my code i had made this error "addRow function inside  table constructor" .
Otherwise data is needed to be loaded each time in table and display it because my application intercepts traffic and show it so i can not wait intill all data is loaded to display it (it is not an option in real time application) .
Concerning AJAX request functionality can't help me either  because data is sent to my IHM (browser html ) via "server sent event" so can't choose data incomming format.


So sir my question is why is it displaying an error message for each iteration while every thing works just fine and things are working just as i wished them to do ?

**Comment by olifolkerd** [comment]
Ahh, that makes sense,

it would only be displaying that message if you were calling the ***options*** function. are you sure you are not interacting with Tabulator in any other way?

**Comment by OsemaPatron** [comment]
Yes that was ALL . 
I can sent to you the project code in private if you like me to . And if you could find what went exactly wrong you can put it for everyone to see .

**Comment by OsemaPatron** [comment]
Yes ALL of it .
Pretty much sure

**Comment by olifolkerd** [comment]
Hey @OsemaPatron 

you can send it to oliver.folkerd@gmail.com

cheers

Oli

**Comment by OsemaPatron** [comment]
Hello sir
I have send it but no reply from you yet :(

2018-03-16 17:25 GMT+01:00 Oli Folkerd <notifications@github.com>:

**Comment by OsemaPatron** [comment]
Yes that was the probleme . I was calling the constractor each iteration .
Thank you sir it helped ..alot



2018-03-22 21:26 GMT+01:00 Oli Folkerd <notifications@github.com>:
