### ISSUE TITLE
Custom Row Formatting and Editing

### ISSUE THREAD

**Issue by pmamatsis** [olifolkerd/tabulator#971]
Hi @olifolkerd ,
   firstly let me thank you for the great control ! I wanted to ask a quick question...is it possible to use custom row formatting and editing? My end-goal is to create a free form control based on Tabulator. Is it something doable? The reason of my question is because i cannot find any such example and maybe this control has not been designed for this action.

Best regards,
Panos.

**Comment by olifolkerd** [comment]
Hey Panos,

You can use row formatting and editors at the same time as long as the cell elements in the row are left intact.

If you want to replace the row contents with your own UI then you can update the row data by calling the ***update*** function on the row component when the data changes, passing in the updated data.

It really depends on what you are doing in the row formatter as to the best route to take.

Let me know if that helps

Cheers

Oli :)

**Comment by pmamatsis** [comment]
Hi @olifolkerd 
   actually I am using this control for over six months now and i am really happy about the features. Recently my team had an idea to build a free form data entry screen that will be based on absolute positioning per row (record row) and will be provided by the back-end (through the use of a JSON object). 
This means that the control will not be "aware" of what each row must renders until runtime (of course each row is going to be exactly the same as the previous or the next) but the whole idea is to extend this in order to accommodate for all our future needs in creating data entry screens.

Thanks the main idea. :)

Best regards,
Panos.
