### ISSUE TITLE
Bravo & trying to render the same table with different columns

### ISSUE THREAD

**Issue by rugged-service** [olifolkerd/tabulator#973]
First - Got to say, this is really nice, and it looks like there was a lot of thought put into it. Having sass as an option is a big plus for styling. 

I'm wondering what is the best approach to render the same table with different column headers? Basically, I have one table that is displaying different years, so if the user selects 2012, it will populate with 2012 data. That part is working, but I'd like to give the user an option to display the table with all years data, and for that, I would need to build out a new columns object, and pass to the table. 

In your experience what is the best approach for this? Thank you in advance, and again- great work.

**Comment by olifolkerd** [comment]
Hey @rugged-service 

Thanks for your kind words, it is great to hear that you are enjoying Tabulator.

You are in luck, there is a function just for this. The ***setColumns*** function lets you pass in a new column definition array after the table has been initialized:
```js
//new column definition array
var newColumns = [
    {title:"Name", field:"name", sorter:"string", width:200},
    {title:"Age", field:"age", sorter:"number", align:"right", formatter:"progress"},
    {title:"Height", field:"height", formatter:"star", align:"center", width:100},
    {title:"Favourite Color", field:"col", sorter:"string"},
    {title:"Date Of Birth", field:"dob", sorter:"date", align:"center"},
],

$("#example-table").tabulator("setColumns", newColumns) //overwrite existing columns with new columns definition array
```

You can also do it one column at a time with the ***addColumn*** and ***deleteColumn*** functions if you wanted:
```js
//add column
$("#example-table").tabulator("addColumn", {title:"Age", field:"age"}, true, "name");

//delete column by field name
$("#example-table").tabulator("deleteColumn", "name");

//delete column by calling the delete function on a column component
column.delete();
```

For more information have a look at the [Column Management Documentation](http://tabulator.info/docs/3.4#column-management)

Let me know if that helps.

Cheers

Oli

**Comment by rugged-service** [comment]
Awesome! It works great. How does the redraw function work, and is that something I should be enabling if I'm rebuilding the table with different datasets?

**Comment by olifolkerd** [comment]
The ***redraw*** function should be used for redrawing the table if any changes are made while the table is not visible.

It is used to prevent visual corruption when loading data on a hidden or resized table. If you are changing config options while the table is visible it will automatically redraw the table for you.

Cheers

Oli :)
