### ISSUE TITLE
Custom header filter triggering

### ISSUE THREAD

**Issue by leonardorame** [olifolkerd/tabulator#975]
Hi Oli, I wonder if there's a way to define when a change in the headerFilter will trigger the ajax request. I think those filter are tied to the `blur` event, but in a specific project I need to trigger the call when the user press Enter only.

**Comment by olifolkerd** [comment]
Hey @leonardorame 

If the header filter is a input element it will update on keyup, search, change or blur.

Most of these event bindings are specifically added to the header filter by Tabulator to allow the filters to apply as the user is typing.

You would need to create a custom editor and pass it to the ***headerFilter*** parameter to undo these extra event bindings, in the case of the input editor:

```js
//input element
var inputHeaderFilter = function(cell, onRendered, success, cancel, editorParams){

	//create and style input
	var input = $("<input type='text'/>");

	input.css({
		"padding":"4px",
		"width":"100%",
		"box-sizing":"border-box",
	})
	.val(cell.getValue());

	//submit new value on enter
	input.on("keydown", function(e){
		if(e.keyCode == 13){
			success(input.val());
		}
	});

	//remove extra event bindings added by tabulator
	setTimeout(function(){
		input.off("change type search keyup")
	}, 100)

	return input;
},
```

The `setTimeout` function is a bit of a hack to allow Tabulator time to add the extra event bindings to the editor and the remove them.

Let me know if that helps.

Cheers

Oli :)

**Comment by leonardorame** [comment]
Hi Oli, can you re-open this?.

I tested your code, but found it only works on in non-ajax mode, how an I adapt this to work with ajax?.

**Comment by olifolkerd** [comment]
Hey @leonardorame 

It seems to work correctly on my end both locally and remotely, can you post a copy of your table constructor?

Given the way the sorting system is built, if it works locally it should work remotely, they are both triggered after the sort order has been determined.

does the request being sent to the server not match up to the header sort arrows on the table?

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @leonardorame 

ignore my last response, i got mixed up with which issue this was

**Comment by olifolkerd** [comment]
Hey @leonardorame 

It works fine on both local and ajax my end. the way the filtering is built should mean it isnt possible to only work one way, the filters are set before the filters are then triggered either locally or remotely.

Does the request not match up with the header filter?

Cheers

Oli :)

**Comment by leonardorame** [comment]
Sorry Oli, my fault. I was using a `customPaginator` that was removing the `filters` array.

By the way, is there a way to do a `POST` containing a JSON object with all the filters and sorters?. For me is difficult to parse the array sent in the `GET` request.

**Comment by olifolkerd** [comment]
Hey @leonardorame 

You can use the ***ajaxConfig*** option for that:
```js
$("#example-table").tabulator({
    ajaxURL:"http://www.getmydata.com/now", //ajax URL
    ajaxConfig:"POST", //ajax HTTP request type
});
```

Cheers

Oli :)

**Comment by leonardorame** [comment]
Thanks, everything is working perfectly right now. You can close this.
