### ISSUE TITLE
possible to group columns by field?

### ISSUE THREAD

**Issue by rugged-service** [olifolkerd/tabulator#976]
for instance here is my columns: 

`columns:[`
    `    {title:"Name", field:"name", width:160},`
      `  {   title:"2009",`
    `        columns:[`
`                {title:"January", field:"jan", sorter:"number"},`
         `       {title:"February", field:"feb",sorter:"number"},`
        `        {title:"Totals", field:"total", sorter:"number"},`
       `    ],`
  `      },`
  `      {`
   `         title:"2008",`
     `       columns:[`
       `         {title:"January", field:"jan", sorter:"number"},`
          `     {title:"February", field:"feb",sorter:"number"},`
          `      {title:"Totals", field:"total", sorter:"number"},`
        `    ],`
  `      },`
 `   ]`

And my data would like something like this: 

  `var tabledata = [`
   `{id:1, name:"foo", jan:"22", feb:"22", toal:"44" colgroup:"2009"},`
  `  {id:1, name:"foo", jan:"22", feb:"22", toal:"44" colgroup:"2009"},`
 `   {id:1, name:"foo", jan:"22", feb:"22", toal:"44" colgroup:"2009"},`
 `   {id:1, name:"foo", jan:"22", feb:"22", toal:"44" colgroup:"2009"},`
 `   {id:1, name:"foo", jan:"10", feb:"22", toal:"32" colgroup:"2008"},`
  `  {id:1, name:"foo", jan:"10", feb:"22", toal:"32" colgroup:"2008"},`
  `  {id:1, name:"foo", jan:"10", feb:"22", toal:"32" colgroup:"2008"},`
  `  {id:1, name:"foo", jan:"10", feb:"22", toal:"32" colgroup:"2008"},`
`];`

**Comment by olifolkerd** [comment]
Hey @rugged-service 

Im afraid i don't understand what you mean, all row data is shown in all columns, and columns are not dependent on row data, they define the structure of the table.

You can certainly [Group Columns](http://tabulator.info/docs/3.4?#column-groups) and you can [Group Rows](http://tabulator.info/docs/3.4?#grouping)

If you want to change the layout of your columns based on row data, then i suggest you retrieve your row data outside of Tabulator, process it to work out what your  new column arrangement should be, change your column arrangement using the ***setColumns*** function and then pass the data into Tabulator using the ***setData*** function.

Let me know if that helps.

Cheers

Oli :)
