### ISSUE TITLE
Insert Rowe after a certain row

### ISSUE THREAD

**Issue by kurtknippschild** [olifolkerd/tabulator#978]
Hi Oli,

thanks for the new release 3.4, it's getting more and more perfect.

Now to my question is it possible to insert new rows into a table after a certain row?
If so, do you have an example?
If not, is this planned for a particular release?

Thanks in advance for all your efforts.

VG Kurt

**Comment by olifolkerd** [comment]
Hey @kurtknippschild 

You can use the ***addRow*** function for this. the first argument should be the row data, the second should be whether the row is being inserted before or after the target row (***true*** before, ***false*** after), the third argument should be the target row to be inserted next to, this takes any of the [Row Component lookup options](http://tabulator.info/docs/3.4#component-lookup)

```js
$("#example-table").tabulator("addRow", {name:"Billy Bob", age:"12"}, true, 3);
```

Let me know if that helps

Cheers

Oli :)
