### ISSUE TITLE
json stored Configuration

### ISSUE THREAD

**Issue by jawa-the-hutt** [olifolkerd/tabulator#98]
I have possible enhancement request.  Not sure if the use case is just me or whether there might be a wider use case for it.  I'd like to bring in the entire configuration for Tabulator from a database.  For data and most of the options this isn't a big deal, but for some things, you need to be able to call a function.  Since well formed json data doesn't really allow for functions to be stored in it, the next best thing you can do is bring in a string and then convert the string to a function call.

so, a specific use case would be icon/button columns.  According to the documentation, this looks something like this today:  
```
//custom formatter definition
var printIcon = function(value, data, cell, row, options){ //plain text value
  return "<i class='fa fa-print'></i>"
};

//column definition in the columns array
{formatter:printIcon, width:40, align:"center", onClick:function(e, cell, val, row){alert("Printing row data for: " + row.name)}},
```

With the json limitation it would end up like this:
```
//custom formatter definition
var printIcon = function(value, data, cell, row, options){ //plain text value
  return "<i class='fa fa-print'></i>"
};

//column definition in the columns array
{formatter:'printIcon', width:40, align:"center", onClick:function(e, cell, val, row){alert("Printing row data for: " + row.name)}},
```

With the tabulator's code as it stands, it will try and process `printIcon` as a string and try to figure out which of the existing formatters we're calling.  Since that formatter doesn't exist, formatter gets returned as `undefined`.  In some limited testing, I think I have a possible fix for this. 

It would mean adding a general private function to tabulator that would convert the string to a function.    So something like this:
```
_getFunctionFromString:function(string, scope) {
  var scopeSplit = string.split('.');
        
  for (let i = 0; i < scopeSplit.length - 1; i++) {
    scope = scope[scopeSplit[i]];
    if (scope == undefined) return;
  }
        
  return scope[scopeSplit[scopeSplit.length - 1]];
},
```

It would also mean you'd have to adjust all of the functions that are processing options that can be a custom function as well.  So for the `_formatCell` function that's used for Icon/Button columns it would mean having it look something like this:  
```
//format cell contents
_formatCell:function(formatter, value, data, cell, row, formatterParams){
  var self = this;
  var tmpFormatter = formatter;

  var formatter = typeof(formatter) == "undefined" ? "plaintext" : formatter;
  formatter = typeof (formatter) == "string" ? this.formatters[formatter] : formatter;
            
  if (formatter == undefined) {
    formatter = self._getFunctionFromString(tmpFormatter, window);
  }

  return formatter.call(self, value, data, cell, row, this.options, formatterParams);
},

```

Note that with the `_getFunctionFromString` function call, we're setting the scope to the `window`.   Not sure how else to do this to allow this to work that will allow the flexibility needed.  

So, I say all that to ask this question:  Is this something that would be of wider benefit?  I would submit a pull request, but quite honestly I've only been working with Tabulator for the last couple of days so I'm not sure where all the custom functions are allowed to be set in the options.  Because of that I have no real idea where all of that code would need changed to accommodate for an across the board change like this.

**Comment by olifolkerd** [comment]
You can already programatically set the column data using the ***setColumns*** function, and extend tabulators inbuilt formatters so you can reference them by strings.

The ***setColumns*** function works like this:
```js
//new column definition array
var newColumns = [
    {title:"Name", field:"name", sortable:true, sorter:"string", width:200, editable:true},
    {title:"Age", field:"age", sortable:true, sorter:"number", align:"right", formatter:"progress"},
    {title:"Height", field:"height", sortable:true, formatter:"star", align:"center", width:100},
    {title:"Favourite Color", field:"col", sorter:"string", sortable:false},
    {title:"Date Of Birth", field:"dob", sortable:true, sorter:"date", align:"center"},
],

$("#example-table").tabulator("setColumns", newColumns , false) //completely overwrite existing columns with new columns definition array
```
Full documentation for setting column data can be found [here](http://olifolkerd.github.io/tabulator/docs/#movable)

You can extend Tabulators built in formatters to include your own custom formatters, which can then be accessed using strings just like the inbuilt ones. There is a guide to adding extended functionality to Tabulator [here](http://olifolkerd.github.io/tabulator/docs/#extending)


I wouldn't be up for adding the string to function parsing into Tabulator as it would be a non standard way of doing things and there already options available for doing exactly what you are after. I try to keep Tabulator as open ended as possible, providing broad access to all the core functionality with an extensive set of existing functions, while allowing people to add their own functions on top to tailor it to their needs,

I would be happy to put together a more detailed example for you that covers your usage case with existing functionality if that would be of use to you.

**Comment by jawa-the-hutt** [comment]
Thanks for the information.  I guess I just didn't put it all together enough to think through how I could use the custom extensions to be written to work this out like I wanted.  

I created a custom formatter that accomplishes what I needed so I think I'm good.

**Comment by olifolkerd** [comment]
You are welcome! Give me a shout if you need any other advice on using tabulator :)
