### ISSUE TITLE
height question

### ISSUE THREAD

**Issue by YendorMc** [olifolkerd/tabulator#981]
I have about 40 rows of data and would like the container div to be the same height as my tabulator table.  I've been specifying a height of 600 which gives some extra space at the end.

I'm on v3.4.5.  And see that there are a couple of points below that are mentioned.

Can you help me understand that I can now omit/leave off the height:600 and have a perfectly size table height to the parent div?

**Documentation > Virtual DOM** 
Note: In version 3.3 and below you were required to set the height option to use the virtual DOM, as of 3.4 this is no longer the case and you can define the height inline on the element or in the CSS and the virtual DOM will still work.

**Quick Start > Virtual DOM and Table Rendering**
In order for the virtual DOM to work, Tabulator needs to know how big the table is. This means that you must set a height for the table element to engage the virtual DOM, this can be in the CSS, an inline style, or using the height property in the table constructor.

If there is no height set on the table the Tabluator cannot use the virtual DOM, and the table will be rendered with no scroll bar, taking up as much space as is needed to show all rows at once. In this mode it will be very slow to render large numbers of rows.

**Comment by olifolkerd** [comment]
Hey @YendorMc 

If you do not set the height on the element you are turning into a Tabulator, then it will take up the exact amount of space needed to fit all the rows in.

So just dont set the **height*** option in your Tabulator config and dont set any height properties in the CSS for the element and you should be all good.

Let me know if that helps.

Cheers

Oli :)

**Comment by YendorMc** [comment]
Perfect!  Thanks Oli!

**Comment by flightsurvey** [comment]
I'm using Split.js and wondered if the tabulator object can be made to automatically resize when its container div is resized?

**Comment by olifolkerd** [comment]
Hey @flightsurvey 

Tabulator will already do this if you are using chrome.

Currently the only way to detect the resize of a div, without constantly polling, is to use a ***ResizeObserver***, unfortunately this is a cutting edge JS feature and is currently only available in chrome.

To make it so that this would work cross-browser you would need to call the ***redraw*** function when the containing div had been resized:

```js
$("#example-table").tabulator("redraw");
```

I hope that helps.

Cheers

Oli :)

**Comment by flightsurvey** [comment]
Oli,

That's good to hear. I'm using Electronjs so it sounds just right. Does that mean that Tabulator can give me a one column, header-less table where the column width, table width and table height automatically adjust to the size of the Split.js container? I wish to emulate the properties table that are found in many IDEs.

All the best,

Paddy.

**Comment by flightsurvey** [comment]
Thanks for the info
