### ISSUE TITLE
column param question

### ISSUE THREAD

**Issue by YendorMc** [olifolkerd/tabulator#982]
I have many rows defined in the columns layout that use the same parameters: 
As in: 
``
	columns: 
		[

	{title:"Name", field:"name", align:"center", headerSort:false,headerTooltip:"My Value is defined as blah2"},

	{title:"Age", field:"age", align:"center", headerSort:false,headerTooltip:"My Value is defined as blah2"}

		]

``
is there a way to define align:"center" and headerSort globally as default somewhere and then change in each column definition, if anything else is needed?

Something like:
``
columnDefault: {align:"center", headerSort:false},

	columns: 

		[

	{title:"Name", field:"name", headerTooltip:"My Value is defined as blah2"},

	{title:"Age", field:"age", headerTooltip:"My Value is defined as blah2"}

		]
``
Thanks!

**Comment by olifolkerd** [comment]
Hey @YendorMc 

The header tooltips can be set globally using the ***tooltipsHeader*** option:
```js
$("#example-table").tabulator({
    tooltipsHeader:"My Value is defined as blah2",
});
```

Unfortunately it is not possible to do this with the ***headerSort*** option.

It is on the roadmap for version 4.0 to make it so defaults for all of these values can be set globally.

Let me know if that helps

Cheers

Oli :)

**Comment by YendorMc** [comment]
That'll work Oli!

A wish list would be "align", "width", "headerSort" and if possible custom formatters or something similar.  

May also be cool to establish your own 'set' of defaults:
eg. 
"width100":{"align":"center","width":100","headerSort":false},
"width50":{"align":"center","width":50","headerSort":false}

and call on it like:
{"title":"Name", "field":"name", "option":"width100","headerTooltip":"My Value is defined as blah2"}

Closing for now!
