### ISSUE TITLE
Tab key not working to move through forms when using custom validators? 

### ISSUE THREAD

**Issue by davidawad** [olifolkerd/tabulator#983]
I'm not sure why this is, but it would seem that on certain cells that have validators, I can't use the tab key to submit what I've typed and move onto the next column of that row. 

What currently happens is if I type values into a custom field, and I hit tab, the value I typed is removed. 

Is there any reason you can think of that custom formatters or validators would cause this behavior? 

Thanks

**Comment by olifolkerd** [comment]
Hey @davidawad 

This is a know regression that came in on one of the 3.4 releases, there is a pull request to fix it that will be pulled in this weekend.

The issue is being tracked in issue #966

Cheers

Oli

**Comment by davidawad** [comment]
Just confirming that switching to 3.4.6 fixed my issue! you need to make a patreon! I will give you money to support this project! 

Thanks again~
