### ISSUE TITLE
Remote Pagination Error - Server response missing 'last_page' property"

### ISSUE THREAD

**Issue by AnnaBurak** [olifolkerd/tabulator#987]
Hi, Oli.

I'm using Tabulator 3.2.2.
I need to do remote pagination for the usage log.
First of all, I simply displayed all received via ajax data from server in Tabulator without any pagination, it works. Then I add pagination options, but it doesn't work. I'm getting error "Remote Pagination Error - Server response missing 'last_page' property". But I see the value of last_page in console.log(response.last_page)  in  ajaxResponse.

I will be grateful if you will advise what the problem is.

Via service response is sended in next format:
{"last_page": 12, "data": [{"user_id": 10, "type_id": "test", "id": 1111, "user_name": "test","record_time": "2018-03-22 14:04:15", "message": "test"}]}

Here is the example of tabulator code:
            $("#log-records-table").tabulator({
                    paginationSize: 20,
                    pagination:"remote", 
                    ajaxURL: 'http://' + services_server + ":" + services_port + '/get_log' + "?key=" +services_key,
                    ajaxConfig: "POST",
                    paginationElement: $('#pagination_log_records_table'),
                    columns: [
                          //....columns definition
                    ],
                    initialSort: [
                        {column: "record_time", dir: "desc"}
                    ],
                    ajaxResponse: function (url, params, response) {
                        console.log(response);
                        console.log(response.last_page);
                        return response.data;
                    }
        });

Sincerely, Anna.

**Comment by olifolkerd** [comment]
Hey @AnnaBurak 

Thanks for getting in touch, the issue is because you are using the ***ajaxResponse*** callback and only returning the data object, if you remove that entire callback then it should work just fine.

Let me know how you get on.

Cheers

Oli :)

**Comment by AnnaBurak** [comment]
Thank you, @olifolkerd , for the quick answer.

That works fine ;)
