### ISSUE TITLE
"no data" view should be customizable (or at least nicer)

### ISSUE THREAD

**Issue by bbrand84** [olifolkerd/tabulator#989]
Hi, 
we use your framework in our project and are very content!
But in out meetings, people always complain about the fat "no data" text. Can you maybe make this adjustable (cannot be aesily done via CSS or Jquery manipulation as far as I can see)? This would really mak some people happy.

Regards, Ben

**Comment by olifolkerd** [comment]
Hi Ben, 

You are in luck, there is all ready an option to change this, the ***placeholder*** option. You can either pass in a string or HTML content for it:
```js
$("#example-table").tabulator({
    placeholder:"No Data Available", //display message to user on empty table
});
```

You can also add any styling you want to the placeholder using the ***.tabulator-placeholder*** class.

Let me know how you get on.

Cheers

Oli :)
