### ISSUE TITLE
Sorting broken

### ISSUE THREAD

**Issue by Jumace** [olifolkerd/tabulator#99]
Hey there,

first of all I want to congratulate to this nice piece of software you wrote!

It looks like I've found a bug in the sorting:
When you have a <th> with more than one space in it you can't sort it anymore.
You can test it in your documentation:
http://olifolkerd.github.io/tabulator/examples/#table-load (with the last row)

I've made some further tests and it's the same for the '/' as a sign. The '-' is fine, for me it looks like a issue with special chars.

Would love to play a bit more with tabulator but with the current issue I can't use it.

Cheers
J

**Comment by olifolkerd** [comment]
If you are loading from an HTML table then you will need to define the column definition array to assign the correct sorter.

For more information on this see the documentation for HTML table loading [here](http://olifolkerd.github.io/tabulator/docs/#table-load)

If you can post an example of your current Tabulator constructor and an example HTML table or data set containing some of the data you are having issues with i would be happy to post a solution for you.

**Comment by Jumace** [comment]
Hey Oli,

thanks for the fast reply.

The link in your reply also has the issue I'm talking about.
But I've also made a codepen to illustrate the issue:
http://codepen.io/anon/pen/woeWRG

Sorting for the first three columns is working, for the next three it's not.
One of the error messages:
Error: Syntax error, unrecognized expression: .tabulator-col[data-sortable=true][data-field!=slash/slash/slash]

Hope that helps to make tabulator even more awesome!

Cheers
J

**Comment by Jumace** [comment]
I've solved it.

I needed to use title and field for the column declaration, like in your ajax example:
			{title:"Name", field:"name", sorter:"string", width:200},
			{title:"Age", field:"age", sorter:"number", align:"right", formatter:"progress"},
			{title:"Gender", field:"gender", sorter:"string"},
			{title:"Height", field:"height", formatter:"star", align:"center", width:100},
			{title:"Favourite Color", field:"col", sorter:"string", sortable:false},
			{title:"Date Of Birth", field:"dob", sorter:"date", align:"center"},
			{title:"Likes Cheese", field:"cheese", align:"center", formatter:"tickCross", sorter:"boolean"},

**Comment by olifolkerd** [comment]
Yup thats the one!
