### ISSUE TITLE
How can i get topCalc row of group.

### ISSUE THREAD

**Issue by MusinAmir** [olifolkerd/tabulator#993]
Is it possible to get topCalc row of group?

**Comment by olifolkerd** [comment]
Hey @MusinAmir 

if you use ***topCalc*** with row grouping enabled the calculations will be displayed at the top of each group, under the group header.

Cheers

Oli :)

**Comment by MusinAmir** [comment]
Hello @olifolkerd 
I need to get topCalc row object to dynamically change it's values/formattings

**Comment by olifolkerd** [comment]
Hey @MusinAmir 

Im afraid i dont follow. topCalc will automatically update if a cell in that column is changed

Cheers

Oli
