### ISSUE TITLE
mutator for multiple columns

### ISSUE THREAD

**Issue by quangkieu** [olifolkerd/tabulator#995]
Hi, 
I am using version 3.4 and I set multiple columns to use the same mutator.
As because the mutator is for multiple columns, I would like to check for which column I am working with during the operation but the cell.getField() only available during an edit. Right now I am use work around by set mutatorPar per column and use the value in there for lookup. But it is better to have getField or other during the operation than set Par value per column.

Quang
Edit: sentence

**Comment by olifolkerd** [comment]
Hey @quangkieu,

you could pass in the field name in the ***mutatorParams*** property:

```js
//mutator
var customMutator = function(value, data, type, mutatorParams, cell){
    var currentField = mutatorParams.field;
   
    //do something with value

    return value
}

//column definition
{title:"Name", field:"name", mutator:customMutator, mutatorParams:{field:"name"}}}
```

Let me know if that helps,

Cheers

Oli :)

**Comment by quangkieu** [comment]
Hi @olifolkerd, thank you for the suggestion. But that is what I current doing by using mutatorParams. But when I have like a lot of columns that it become hard to maintain as the need to update multiple place.

**Comment by olifolkerd** [comment]
Hey @quangkieu 

Im afraid there is no other solution for this for mutators that are applied on the data as it is loaded into the table.

Cheers

Oli :)

**Comment by quangkieu** [comment]
@olifolkerd, I saw at H.prototype.transformRow function, you able to have e.getField() so I wonder if that could be passed to mutator function?

**Comment by olifolkerd** [comment]
At the moment there is no built in functionality that would allow access to that information in the mutator function.

I can certainly look at adding it to the road map in the future that the column component is passed into the mutator when it is transforming newly inserted data.

But currently nothing passed into the mutators arguments will be usable to determine the current column,

You are of course welcome to make any changes you wish to your version of the source, in which case I would suggest you have a look in the `\src\extenstions\mutator.js` file at line ***42***, you could then choose to pass the field or the column component into the mutator function.

Details on how to extend Tabulator can be found in the [Extension Documentation](http://tabulator.info/docs/3.4#extending)

Let me know if you need any more information.

Cheers

Oli

**Comment by olifolkerd** [comment]
Infact, i really like the idea of passing in the column to the data mutator, and it was really easy to do so i have just pushed the update to the 3.5 branch which will be being released in a couple of weeks.

The 4th argument for the function is the component, in "edit" mode this is the cell component, in "data" mode this is the column component.

Update documentation can be found [Here](http://tabulator.info/docs/3.5#get-set)

Thanks for the suggestion.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @quangkieu 

Version 3.5 has now been released!
