### ISSUE TITLE
Bug in navigations with groups

### ISSUE THREAD

**Issue by MusinAmir** [olifolkerd/tabulator#997]
Hello!
Can't move to next cell of another group with "Tab".
Steps: 
1. Go to cell at the end of the group
2. Click "Tab"
Expectation: move to first cell of another group
Reality: error
![image](https://user-images.githubusercontent.com/14330661/38012080-7ce53e24-3279-11e8-8493-91b30d306ada.png)
"Shift + Tab" to prev also not working, but doesn't through exception.
Cheers

**Comment by olifolkerd** [comment]
Hey @MusinAmir 

Looks like you might have found a bug there, good work.

I will have a look into that this weekend.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @MusinAmir 

I have pushed an update to the 3.5 branch that allows for navigation across column calculations and group headers.

v3.5 will be officially launched in a couple of weeks time.

let me know if you find anything else.

Cheers

Oli :)
