### ISSUE TITLE
How can I remove the sorted indicator

### ISSUE THREAD

**Issue by leonardorame** [olifolkerd/tabulator#998]
Hi again Oli, I'm playing with sorters and found apparently there's no way to remove the sorting state of a column. I mean, initially all columns aren't sorted, then if I click on one of them its sorting state changes (displaying the black triangle), then if I click again the sorting direction changes, then, if I click for the 3rd time _I hope the sort triangle disappear removing the sort by this column_, but instead the sorting direction changes again, keeping the column in sorted state, and sending it as a parameter to the server in the sorters array.

**Comment by olifolkerd** [comment]
Hey @leonardorame 

The behaviour of the header sorters is consistent with the function of most other table systems. it isnt an "enable/disable" setup it is more of a toggle sort direction. it is just replaced with a new sort when you click on the next column.

If you want to clear the sort you can use the ***clearSort*** command.

```js
$("#example-table").tabulator("clearSort");
```
You could get the effect your are after by using the ***headerClick *** callback to check the current sort of the table and trigger ***clearSort*** if needed

Cheers

Oli

**Comment by leonardorame** [comment]
Yes, I knew that command, but I was thinking of a way to remove the sorting from the user interface side.

I insist, in my opinion the sorting toggle (when the user clicks on the column header) should iterate over three stages:

1. Sort descending
2. Sort ascending
3. Not sorting at all

Leonardo.

**Comment by olifolkerd** [comment]
Hey @leonardorame 

Thankyou for your opinion, but im afraid thats just not the way that Tabulator works.

I can also direct you to [datatables sorting](https://datatables.net/examples/basic_init/table_sorting.html) which works in exactly the same way.

Thanks for your input.

Cheers

Oli :)

**Comment by leonardorame** [comment]
Thanks, ok, let's keep this as is.
