### ISSUE TITLE
setData after selection doesn't trigger rowSelectionChanged

### ISSUE THREAD

**Issue by leonardorame** [olifolkerd/tabulator#999]
Hi Oli, me again, sorry for keeping posting here, but believe me, I love **Tabulator** and really want to help you at least with some testing from time to time.

I found something that looks like a bug. In `pagination: remote` mode, and `selectable: 1`, after selecting one row, if I call `setData` to reload the table the event `rowSelectionChanged` isn't seem to be triggered (at least the selected row isn't selected anymore).

The correct behavior should be to keep the row selected and if the data of that row doesn't exist anymore after refreshing the `rowSelectionChanged` should be triggered to let the programmer do something util.

One use case is a toolbar above the table. When there's a row selected some buttons of that toolbar are enabled, and disabled when there's no row selected. Currently, if I first select a row, my toolbar buttons are enabled, then when I refresh the table, there's no selected row anymore, but my buttons are still selected, because I enable/disable them when the table triggers the `rowSelectionChanged` event.

**Comment by olifolkerd** [comment]
Hey @leonardorame 

Thanks for you input, post as much as you like, the feedback helps everyone.

All selection data is cleared when the setData command is used, as that is designed to completely wipe down the table, Nothing related to the data is preserved in that instance so i would not be looking to allow selected rows to be maintained past that point (this is documented in the persistent selection part of the docs)

I am looking to add a new function for adding data in a way that updates the table data in-situ and deletes rows not present in the new data.

I do agree that that the ***rowSelectionChanged*** event should be triggered in that event, i have just pushed an update to the 3.5 branch to make this the case.

version 3.5 will be released in a couple of weeks.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @leonardorame 

Version 3.5 has now been released!
